### ISSUE TITLE
RouterConfig config is undefined when importing via ES6 imports

### ISSUE THREAD

**Issue by iamjohnlong** [angular/angular#10004]
```
[X] bug report
```

**Current behavior**

`RouterConfig` config is undefined when importing via ES6 imports

**Expected/desired behavior**

Following https://angular.io/docs/ts/latest/guide/router.html#!#child-routing-component 

I would expect to be able to import `RouterConfig` in the same way using ES6/7 modules

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Angular Router version:** 2.0.0-beta.2
 
* **Browser:** [ Chrome Version 51.0.2704.103 (64-bit) ] 
 
* **Language:** [ES6/7]

**Comment by iamjohnlong** [comment]
Maybe I'm confused on what the `RouterConfig` is supposed to be doing? It's also undefined in the TypeScript example here https://angular.io/resources/live-examples/router/ts/plnkr.html if you `console.log(RouterConfig)`. When I remove all imports and references to it everything works the same. http://plnkr.co/edit/PJEsYWBPvXUSaYGvQfw2?p=preview

**Comment by brandonroberts** [comment]
`RouterConfig` is a `type` and types only exist at compile time when using `TypeScript`. Since you are using ES6 modules you don't need to use `RouterConfig`

**Comment by iamjohnlong** [comment]
Ah.. makes sense. thanks @brandonroberts
