### ISSUE TITLE
Animation: ngClass not working on exit (* => void) transition

### ISSUE THREAD

**Issue by jeeyun** [angular/angular#10008]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
A component that has dynamic class assigned via ngClass styles correctly on enter (void => &lowast;). The ngClass isn't applied on exit (&lowast; => void).

**Expected/desired behavior**
I would expect the ngClass to be preserved while the exit animation is in play.

**Reproduction of the problem**
https://plnkr.co/edit/JDYNvs3RLzjBVnzHe5Cq?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

**Comment by dharders** [comment]
Definitely looks like *ngIf is prematurely removing the *ngClass styles.

Note: this bug only appears for **dynamic** styles. 

Static styles appear to work correctly. i.e.

Changing the plunker src/app.ts line 16:

From:

```typescript
<div class="cmp" [ngClass]="blue" *ngIf="exp" @flyInOut="exp">Hello world</div>
```
To:
```typescript
<div class="cmp blue" *ngIf="exp" @flyInOut="exp">Hello world</div>
```
shows the desired outcome (but of course this is static styling, where the OP wants dynamic **ngClass** styles to work)

**Comment by matsko** [comment]
@pkozlowski-opensource why do we cleanup classes in the end when the element is destroyed?

**Comment by matsko** [comment]
This PR fixes the issue: https://github.com/angular/angular/pull/10303

**Comment by pkozlowski-opensource** [comment]
@matsko I think that this might be a left-over from the times when we were caching views, Tobias introduced it at one point if my memory doesn't fail me. Can dig it out if needed.
