### ISSUE TITLE
Route guards only trigger when navigating between child routes.

### ISSUE THREAD

**Issue by daotoad** [angular/angular#10014]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

~~Not sure if this is a bug or a feature request.~~

When navigating between to components that are children of a parent component that has a CanActivate hook applied, the parent hook is not executed.

https://plnkr.co/edit/5EABzO?p=preview

**Expected/desired behavior**

**Reproduction of the problem**

https://plnkr.co/5EABzO?p=info

To see the exact behavior, 

1. Click on the links to **Child 1** and **Child 2**.  Notice that the message shows that the Auth Guard has rejected attempts to navigate.
2. Click the button that says "Logged Out" to toggle authorization status.
3. Click on the **Child 1** and **Child 2** links.  Notice that the AuthGuard message timestamp only updates once.
4. Click the button again to log out ( it says "Logged In" now).
5. Click on the **Child 1** and **Child 2** links.  Notice that you are still able to view the "protected" routes despite not being logged in.  The AuthGuard is not running, so it cannot prevent you from accessing them.
6. Click on **Home** or **List** then click on the  **Child 1** and **Child 2** links.  Notice that the AuthGuard now runs and blocks access to the links.

**What is the expected behavior?**

Specifically, the AuthGuard should run when navigating from **Child 1** to **Child 2**.

In the generalized case, every navigation should activate all route guards in the path, including those that have the same route as destination, for example navigation form `/account/1234/edit` to `/account/8901/edit` where the numerical portion is captured as a route parameter.

The @ngrx/router guard clauses work this way and are very easy to work with and provide a powerful way to manage user behavior.

**What is the motivation / use case for changing the behavior?**

Guard code should run on every navigation. 

Consider paths like '/account/1234/view' and '/account/4556/edit', if we can reliably check guards with every navigation, I can have one authorization guard applied at the 'account' level that verifies if the user has access to a particular account id and the capability to complete the action embodied in the components (i.e. View or Edit).  As the code works now, if I am authorized for one action on one account, I am authorized for all actions on all accounts.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript X.X]

**Comment by brandonroberts** [comment]
This is just a difference in the way ngrx/router and the angular/router work. ngrx/router runs guards at the path traversal level, where if a path candidate guard fails, its no longer considered a valid path. The angular/router traverses the paths first, then runs all the guards to see if activation can occur.

You can achieve the same result with the angular/router using a a guard on a component-less route. This route doesn't consume any URL segments, and the guard will run on each of its children each time.

Here is a plunker demonstrating this: https://plnkr.co/edit/wEdGbM?p=preview

Link to Victor's original post: http://victorsavkin.com/post/146722301646/angular-router-empty-paths-componentless-routes

**Comment by brandonroberts** [comment]
This is just a difference in the way ngrx/router and the angular/router work. ngrx/router runs guards at the path traversal level, where if a path candidate guard fails, its no longer considered a valid path. The angular/router traverses the paths first, then runs all the guards to see if activation can occur.

You can achieve the same result with the angular/router using a a guard on each child route. 

Here is a plunker demonstrating this: https://plnkr.co/edit/wEdGbM?p=preview

Link to Victor's original post: http://victorsavkin.com/post/146722301646/angular-router-empty-paths-componentless-routes

**Comment by daotoad** [comment]
@brandonroberts , thanks for taking the time to respond.

Having to repeatedly specify the same guards when I really want them to run for a whole subtree is not great.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

Perhaps there could be a guard enforcement strategy.  We already have the concept of a path matching strategy, so it could be extended to cover route guards (canActivate and canDeactivate).  

One strategy could be **boundary**, where guards are only called when navigation crosses into a route tree.  Another could be **subtree**, where guards are called when any navigation occurs within the route branch.

**Comment by brandonroberts** [comment]
@daotoad this PR https://github.com/angular/angular/pull/10056has landed and will come with the next release which should handle your situation.

**Comment by vsavkin** [comment]
The next release of the router will support canActivateChild (https://github.com/angular/angular/pull/10056), which should handle your use case. Closing this issue.
