### ISSUE TITLE
When using ComponentFixture for testing Model driven forms, method detectChanges() throws an error.

### ISSUE THREAD

**Issue by bluefalcon** [angular/angular#10028]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
First time calling ComponentFixture.detectChanges() (for ngOnInit) throws an exeption when doing model driven form.

**Expected/desired behavior**
No exception should be thrown and unit test successfully runs.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

I have a github repo for an example if suffice.
https://github.com/bluefalcon/angular2-model-form-spec

1st window -ng serve
2nd window - ng test --build=false
open debugger in browser.
in setting.component.spec.ts there there is a 'debugger' in the catch to see the exception.

**What is the expected behavior?**
No error is thrown.

**What is the motivation / use case for changing the behavior?**
To be able to run a test successfully when doing testing a form that is model driven.

**Please tell us about your environment:**

Using Angular-cli
angular-cli: 1.0.0-beta.8
node: 6.2.2
os: win32 x64 (Windows 10)

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 using chrome 51.0.2704.103 m
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
--Typescript 1.8.10

--Stack Trace
[StackTrace.txt](https://github.com/angular/angular/files/360622/StackTrace.txt)

**Comment by kara** [comment]
@bluefalcon It looks like you're using the new forms module in your code (through `disableDeprecatedForms()` and `provideForms()` in `main.ts`), but not in your tests.  As such, your tests are throwing.    If you add the following to your spec file, your tests should not throw that error:

```ts
import {disableDeprecatedForms, provideForms} from '@angular/forms';

beforeEachProviders(() => [
   disableDeprecatedForms(),
   provideForms()
]);
```

Closing, as this does not seem to be a bug.

**Comment by bluefalcon** [comment]
Hi Kara - Thanks for the tip.  I know beforeEachProviders has been deprecated as well.  I went ahead and added the following (see below).  I am still getting the same exception.  I have tried everything and am at a loss.  What you suggested I actually tried and still had the same error so I figured it wasn't needed, but it is. :)
 beforeEach(() => {
        mockSettingService = new MockSettingService();
        addProviders(
            [
                disableDeprecatedForms(),
                provideForms,
                { provide: SettingService, useClass: MockSettingService },
                FormBuilder
            ]);
    });
