### ISSUE TITLE
Issue with observer.error(...) not propagating the error to the observable stream

### ISSUE THREAD

**Issue by huyph** [angular/angular#10027]
```
[ x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
`let testObservable = new Observable<any>(observer => testObserver = observer)`

`testObserver.error(an_error)` does not propagate this error to the observable's onError callback: `testObservable.subscribe(onNext, onError, onComplete)`

**Expected/desired behavior**
`testObserver.error(...)` should result in `onError` to be called

**What is the motivation / use case for changing the behavior?**
`testObserver.next()` and `testObserver.complete()` does result in onNext and onComplete in `observable` to be called. Hence, I would expect `.error(...)` should does that as well?

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **RxJS version:** 5.0.0-beta.6
* **Browser:** N.A

**Comment by DzmitryShylovich** [comment]
How is this related to angular? Looks like rxjs issue.

I would be nice to see a plnkr with reproduction.

**Comment by huyph** [comment]
Uhm on a 2nd retry, I can't replicate this error with pure RxJS 

Let close this issue for now. 

The exact situation I am in also involves the use of `mockBackend` with `.mockError(...)`, `fakeAsync() and tick()`. So let me try to create a plunker. 

Any idea on how I can quickly get angular rc4, it seems missing in https://code.angularjs.org/, not sure why?
