### ISSUE TITLE
feature request: provide a getter for a component's template

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1002]
In Ionic v2, we need to be able to change the template that a component at run-time, based on any combination of these factors:

- The current device
- The screen size
- User-set configuration 
- Attributes the user puts on the element

We could do this in angular 1:

```js
module.directive('ionButton', {
  return {
    restrict: 'E',
    template: function(el, attr) {
      return attr.superButton ? 'super-template' : 'normal-template';
    }
  };
]);
```

In Angular 2, we can't do this. @mhevery mentioned a proposed syntax where different templates could be set based upon some conditions:

```js
@Component({
  selector: 'ion-button'
})
@Template({
 device: 'ios',
 media: '(min-width: 720px)',
 url: 'ios-ipad-button.html'
})
class Button {}
```

This is still too limiting.  We still can't have each Button instance potentially use a different template. We need something more dynamic.  The simplest way to fix this problem would be to allow a getter for the template.

```js
@Template({
  url: function() {
    // depending on a condition, return a templateUrl
  }
})
```

**Comment by mhevery** [comment]
see #1239

**Comment by naomiblack** [comment]
Closing because #1239 covers this use case. Please add to discussion there if you find any more to add.
