### ISSUE TITLE
parent child routing(nested routing) in angular2 cli (RC4)

### ISSUE THREAD

**Issue by venkatesh707** [angular/angular#10031]
Hi Guys,

I am newbie to angular2,please any one could give an good example for parent child routing in angular cli (rc4) project..I have two views.. sideview(have list).. rightside(detailview of the list).. if call the main view it should render left and right view as well as..like ui-routing in angular js..

Thanks & Reagards
Venky

**Comment by brandonroberts** [comment]
@venkatesh707 you should take a look at this blog post: http://victorsavkin.com/post/146722301646/angular-router-empty-paths-componentless-routes
