### ISSUE TITLE
Angular.io Website SSL Certificate Problem.

### ISSUE THREAD

**Issue by nickhod** [angular/angular#10035]
The angular.io website does not work with ESET NOD32, I believe there is a certificate problem.
The certificate has many spam sites in the SAN field. 

In NOD32 I have to "Disable HTTPS checking" to view the site or it is blocked.

This happens on no other sites that I visit regularly.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular.io docs repo

**Comment by nickhod** [comment]
Thanks.
