### ISSUE TITLE
Bad non-generic Typings

### ISSUE THREAD

**Issue by nickwinger** [angular/angular#10030]
Hi,

can anyone please tell me why such a popular framework like angular 2 provides such bad non-generic typings ?

EVERYWHERE are stupid any's instead of generic.
e.g.:

http / Response
json(): any;

why not:
json<T>(): T;

or ElementRef:
nativeElement: any;

why not:
ElementRef<T>
nativeElement: T;

Right now you have to cast every any to have Typedefinition instead of just providing a generic.

Would make life easier and the code more readable and useable.

Cheers,
Nick

**Comment by nickwinger** [comment]
wow

Von: Victor Berchet [mailto:notifications@github.com]
Gesendet: Mittwoch, 13. Juli 2016 07:30
An: angular/angular <angular@noreply.github.com>
Cc: office@bit4bit.at; Author <author@noreply.github.com>
Betreff: Re: [angular/angular] Bad non-generic Typings (#10030)


Closed #10030<https://github.com/angular/angular/issues/10030>.

**Comment by jakobgruber** [comment]
Why has this issue been closed? any´s are a real pain...

Everytime i am using an angular-method, i have to cast to the right type. With generics, it would be so much easier...
