### ISSUE TITLE
Global router change animate?

### ISSUE THREAD

**Issue by ruanzy** [angular/angular#10034]
Global router change animat

**Comment by skreborn** [comment]
Please follow the template when creating an issue, as it helps both the developers and the community to help you. If this isn't an issue with Angular, but rather a question about its usage, please ask on an [appropriate channel](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).

**Comment by pkozlowski-opensource** [comment]
Thnx @skreborn

**Comment by zoechi** [comment]
See https://github.com/angular/angular/issues/9350#issuecomment-227354109

**Comment by zoechi** [comment]
And https://github.com/angular/angular/issues/9845#issuecomment-232476173
