### ISSUE TITLE
Field value in component class updated too late

### ISSUE THREAD

**Issue by berndpb** [angular/angular#10038]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I am running the following code:

```
import {Component} from '@angular/core'

@Component({
  selector: 'my-app',
  template: `
    <form>
      <input type="checkbox" [(ngModel)]="test" (change)="someAdditionalAction($event);"/>
    </form>
  `
})
export class App {

  test: boolean;

  someAdditionalAction(event) {
    console.log("test="+this.test);
  }
  
}
```

**Current behavior**
The value of the field "test" is updated to the views current value (cheked or not) after processing the event handler. So inside this eventhandler-method, the value of that field differs from the value of the view.

**Expected/desired behavior**
Fields bound to form elements should be updated before processing actions/eventhandlers.

**Reproduction of the problem**
 A litte different form the code above, because I did not find any console-output

https://plnkr.co/edit/9L9CyFwHSyb1g2FeYurL?p=preview

**What is the expected behavior?**
The value of test1 should display the checkbox checked-status. Currently it' inverse because the field test is updated too late.

**What is the motivation / use case for changing the behavior?**
I really like Angular2 and want to help it to run better

**Please tell us about your environment:**
OSX, Visual Studio Code, Chrome-Debug-Extension, npm
package.json
{
      "name": "",
      "version": "1.0.0",
      "scripts": {
        "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
        "lite": "lite-server",
        "postinstall": "typings install",
        "tsc": "tsc",
        "tsc:w": "tsc -w",
        "typings": "typings"
      },
      "license": "ISC",
      "dependencies": {
        "@angular/common": "2.0.0-rc.4",
        "@angular/compiler": "2.0.0-rc.4",
        "@angular/core": "2.0.0-rc.4",
        "@angular/forms": "0.2.0",
        "@angular/http": "2.0.0-rc.4",
        "@angular/platform-browser": "2.0.0-rc.4",
        "@angular/platform-browser-dynamic": "2.0.0-rc.4",
        "@angular/router": "3.0.0-beta.1",
        "@angular/router-deprecated": "2.0.0-rc.2",
        "@angular/upgrade": "2.0.0-rc.4",
        "systemjs": "0.19.27",
        "core-js": "^2.4.0",
        "reflect-metadata": "^0.1.3",
        "rxjs": "5.0.0-beta.6",
        "zone.js": "^0.6.12",
        "angular2-in-memory-web-api": "0.0.14",
        "bootstrap": "^3.3.6"
      },
      "devDependencies": {
        "concurrently": "^2.0.0",
        "lite-server": "^2.2.0",
        "typescript": "^1.8.10",
        "typings":"^1.0.4"
      }
    } 

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [Chrome Version 51.0.2704.103 (64-bit) | Safari Version 9.1.1 (11601.6.17) 
 
* **Language:** [TypeScript X.X]

**Comment by awerlang** [comment]
Use the `ngModelChange` event instead of `change`

**Comment by berndpb** [comment]
Thanks a lot for answering that much fast. With `ngModelChange` it works fine.
