### ISSUE TITLE
bug(router/modules) RouterModule cannot be injected into Lazy-loaded submodules

### ISSUE THREAD

**Issue by choeller** [angular/angular#10041]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Trying to use `RouterModules` in a lazy-loaded submodule like this:

```ts
@AppModule({
  modules: [
    RouterModule
  ],
  providers: [
    provideRoutes([
      { path: '', component: LazyChildList},
      { path: ':id', component: LazyChildDetail }
    ])  
  ],
  precompile: [LazyChildList, LazyChildDetail] //temporary
})
export class LazyModuleOne {}
```
leads to a DI-Error:

```ts

browser_adapter.ts:82 Error: No provider for ApplicationRef!
    at new BaseException (exceptions.ts:21)
    at _NullInjector.get (injector.ts:18)
    at AppModuleInjector.get (app_module_factory.ts:82)
    at eval (router_module.ts:46)
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.ts:61)
    at ZoneDelegate.invokeTask (zone.js:355)
    at Zone.runTask (zone.js:256)
    at ZoneTask.invoke (zone.js:423)
```

**Expected/desired behavior**

RouterModule should be injectable into submodule.

**Reproduction of the problem**

This plnkr shows the problem. Just click on "Lazy 1 default". https://plnkr.co/edit/MV1SSn6NzhuiFtWtd5BS?p=preview

Commenting out `RouterModule` in module1.ts fixes the DI-Error.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

Being able to use Routing Functionality in Sub-Modules 

**Please tell us about your environment:**

* **Angular version:** Current master: 5725c5925c254ecc52cc80a1492695b5aac27e0c
 
* **Browser:** [all  ] 
 
* **Language:** [all]

**Comment by vsavkin** [comment]
This is by design.

The router module should be registered only once, at the root level, i.e., lazy-loaded modules can provision their routes, but cannot create their own routers. 

The main reason for this is that the router uses a global resource: the location. So there must be only one router in the system.
