### ISSUE TITLE
Tracking: Change semantics of `@AppModule.directives` / `@AppModule.pipes`.

### ISSUE THREAD

**Issue by tbosch** [angular/angular#10043]
This is a major rewrite of the modules support in Angular.

For more details, see [this doc](https://docs.google.com/document/d/130o_T7GO8cag2V5NcGDrUW_8ucYvGNYqzsW5HFd4NhQ/edit#).

- [x] Part 1: Main changes (see https://github.com/angular/angular/pull/10164)
- [x] Part 2: Required features for final (see https://github.com/angular/angular/pull/10268)
  - rename `precompile` into `entryComponents` for @NgModule and @Component
  - support `ModuleWithProviders` in `imports` section..
  - add NgModule.schemas (see design doc)

Related changes:
- support static properties / methods in static reflector / metadata collection (https://github.com/angular/angular/issues/10266)
  * remove `RouterModuleWithoutProviders` class

**Comment by tbosch** [comment]
This is on hold for now until all the cases are defined.

**Comment by fknop** [comment]
Is there a new design doc ? I can't access this link.

**Comment by tbosch** [comment]
This has landed in master now.
