### ISSUE TITLE
Radio button name property and ngModel don't work

### ISSUE THREAD

**Issue by amagyar** [angular/angular#10049]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Can't set name of radio button with ngModel presence.
`<input type="radio" [name]="variable2" [(ngModel)]="variable1">`
The name becomes ng reflect name and it simply don't work.

**Expected/desired behavior**
Keep the name attribute.

**Reproduction of the problem**
http://plnkr.co/edit/aPs2ax2f6qsnSkTw2Ad7

**What is the expected behavior?**
Name is removed and replaced with name reflection.

**What is the motivation / use case for changing the behavior?**
Dynamically group the radio buttons by name

**Please tell us about your environment:**
Visual code studio 1.3.1

* **Angular version:**
 2.0.0-rc.4

* **Browser:**
 Chrome 51.0.2704.106 (64-bit)

* **Language:**
Typescript 1.8.10

**Comment by amagyar** [comment]
There's also the problem that I didn't wrote that is the value of ngModel binding become "{ checked : true}".

**Comment by dmay-work** [comment]
Use ```attr``` prefix for native attributes. In your case, ```[attr.name]```

**Comment by vicb** [comment]
Thanks @dmay-work
