### ISSUE TITLE
bug(modules) Unable to inject service provided by a sub-module into lazy-loaded component

### ISSUE THREAD

**Issue by choeller** [angular/angular#10044]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently it is not possible  to inject a service provided by a sub-module into lazy-loaded component:

```ts
@Component({
  selector: 'lazy-child-detail',
  template: `
    <h3>lazy child detail</h3>
  `
})
export class LazyChildDetail {}


@AppModule({
  modules: [
    RouterModule
  ],
  providers: [
    MyService,
    provideRoutes([
      { path: '', component: LazyChildList},
      { path: ':id', component: LazyChildDetail }
    ])  
  ],
  precompile: [LazyChildList, LazyChildDetail] //temporary
})
export class LazyModuleOne {}
```
```ts
@Component({
  selector: 'lazy-child-list',
  template: `
    <h3>lazy child list</h3>
  `
})
export class LazyChildList {
  
  constructor(myService: MyService) {
    console.log(myService.sayEek())
  }
  
}
```
leads to 
```ts
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./LazyChildList class LazyChildList_Host - inline template:0:0
ORIGINAL EXCEPTION: No provider for MyService!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (https://cdn.rawgit.com/angular/core-builds/master/src/facade/exceptions.js:27:23)
    at NoProviderError.AbstractProviderError [as constructor] (https://cdn.rawgit.com/angular/core-builds/master/src/di/reflective_exceptions.js:43:16)
    at new NoProviderError (https://cdn.rawgit.com/angular/core-builds/master/src/di/reflective_exceptions.js:80:16)
```

**Expected/desired behavior**

It should be possible to inject Services in sub-modules

**Reproduction of the problem**

This plnkr shows the problem https://plnkr.co/edit/r2qHinshrCHgnOVg8ArM?p=preview

Click on "Lazy 1 default"

**What is the expected behavior?**

No DI-Error should be thrown / MyService should be accessible by the lazy-loaded component

**What is the motivation / use case for changing the behavior?**

Being able to encapsulate Services and Components in a Module

**Please tell us about your environment:**

* **Angular version:** current master 5725c5925c254ecc52cc80a1492695b5aac27e0c
 
* **Browser:** [all  ] 
 
* **Language:** [all]

**Comment by brandonroberts** [comment]
This issue has been fixed in master

**Comment by tbosch** [comment]
Please note that modules are still experimental and will likely change when
we cut rc.5...
