### ISSUE TITLE
Creating a Component with an @ViewChild property off of a base class that has @Input properties does not transpile

### ISSUE THREAD

**Issue by mattschlitz** [angular/angular#10042]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Creating a Component with an `@ViewChild` property off of a base class that has `@Input` properties does not transpile with an error message of "Can't bind to 'myproperty' since it isn't a known native property"

**Expected/desired behavior**
Transpilation works

**Reproduction of the problem**
http://plnkr.co/edit/eJjxhg0pucM6w8PyENzj?p=preview
Note the comment in the "app/child-component.ts" file which, when uncommented, will reveal the issue.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome 51.0
 
* **Language:** TypeScript 1.9.0

**Comment by ericmartinezr** [comment]
Search for components inheritance in the repo, it's full with them and you'll see that inheritance doesn't really work.

**Comment by zoechi** [comment]
#5415

**Comment by mattschlitz** [comment]
@zoechi Your rational seems solid. This seems like a duplicate of that issue.

**Comment by Besnik18** [comment]
eeee

**Comment by mattschlitz** [comment]
@Besnik18 eeee?
