### ISSUE TITLE
TemplateRef shares context between instances when none is provided

### ISSUE THREAD

**Issue by jdohert** [angular/angular#10045]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`angular/modules/@angular/core/src/linker/template_ref.ts` currently uses a single object for `EMPTY_CONTEXT`. The problem is when `ViewContainerRef #createEmbededView` is called without providing a context object the shared one is used causing pollution between all instances utilizing the context.

**Expected/desired behavior**
Object sharing doesn't happen between instances relying on the context.

Maybe some solutions could be:
* `TemplateRef_<C>` instantiates a new object when none is provided
* `ViewContainerRef #createEmbededView` makes context mandatory and `TemplateRef_<C>` stops checking isBlank of context.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

https://plnkr.co/edit/UhGsjLaHxiwI0n0nTYtN?p=preview
//TypeError: Cannot read property 'name' of undefined on second instance

Simplified Plunk: http://plnkr.co/edit/CQQembTFT0nOxGwCzSgc?p=preview
You can see the sharing of the context, `test2` is listed twice in first block

**What is the expected behavior?**
No sharing of the context between instances

**What is the motivation / use case for changing the behavior?**
Errors

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by vicb** [comment]
Please try to simplify your plunker with the minimal amount of code required to reproduce the issue.

**Comment by jdohert** [comment]
Here's the new plunk, I hope it's simplified enough.

http://plnkr.co/edit/CQQembTFT0nOxGwCzSgc?p=preview
