### ISSUE TITLE
Angular Forms 0.2.0, form submitted twice

### ISSUE THREAD

**Issue by DavideViolante** [angular/angular#10052]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
It seems that the form is submitted twice.

**Expected/desired behavior**
Submitted once.

**Reproduction of the problem**
https://plnkr.co/edit/BcjWUzm2U2xUpc2znUEt?p=preview
I don't know if it's only me or I'm doing something wrong...

* **Angular version:** 2.0.0-rc.4
* **Browser:** Chrome, Edge

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/9954

**Comment by DavideViolante** [comment]
Sorry for dup, didn't find it before. Anyway I fixed it:
I had to write disableDeprecatedForms() instead of disableDeprecatedForms in bootstrap method.

Closing.
