### ISSUE TITLE
Facade code duplicated in published modules

### ISSUE THREAD

**Issue by bryanforbes** [angular/angular#10055]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The code contained in `modules/@angular/facade/src` is duplicated in the following published modules:

* `@angular/common`
* `@angular/compiler`
* `@angular/core`
* `@angular/forms`
* `@angular/http`
* `@angular/platform-browser`
* `@angular/platform-browser-dynamic`

This causes application builds to be larger than they need to be.

**Expected/desired behavior**

That `facade` would be contained within either `@angular/common`, `@angular/core`, or published as `@angular/facade` and the modules above would use `facade` from an external module rather than an internal copy of the code.

**What is the motivation / use case for changing the behavior?**

Smaller application builds.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** n/a
 
* **Language:** TypeScript X.X | ES6/7 | ES5

**Comment by vicb** [comment]
Thanks for reporting. This is a known issue and will be addressed.
