### ISSUE TITLE
source maps seems not working

### ISSUE THREAD

**Issue by pleerock** [angular/angular#10062]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In chrome dev tools, in source code of angular I don't see its ts code, only js sources.

**Expected/desired behavior**

In chrome dev tools, in source code of angular I should see its ts code.

Source maps exist in the code and seems correct, `sourcesContent` exist in the code and also seems correct. But realtive path of `sources` does not seems to be correct, and I think thats why chrome dev tools cant show ts code of the js

**Comment by Vexra** [comment]
I have this issue tool, but I'm not sure if this is an angular issue. Going into the dev tools options and disabling source maps, followed by re-enabling them, fixes this issue for a certain amount of time.

Version 51.0.2704.103 m

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for support request.

**Comment by pleerock** [comment]
Its not a support request, its a bug I'm reporting
