### ISSUE TITLE
bug(forms): with async validators parent control status is changing wrong

### ISSUE THREAD

**Issue by nick1247** [angular/angular#10064]
When using async validation for control and its child controls, parent control status changes if validation of child controls complete although its own validation is pending.

So there is a bag with parent control statuses. 
For example, form contains one child control. Child controls validation complete before form validation and child control is valid, form status changes to valid too. Then form validation complete and form status changes to invalid.

[plnkr for reproduce](http://plnkr.co/edit/GgckqxRtsSLq1BlyHAyH?p=preview)

Expected:
Form status changes to valid only if its own validator is in valid state and child controls validators are in valid state

**Comment by kara** [comment]
@nick1247  Yep, this is a bug. We should be checking whether the group level is pending when we calculate status.

**Comment by DzmitryShylovich** [comment]
@nick1247 is this still an issue? can u update the plunkr because it doesn't load?

**Comment by nick1247** [comment]
@DzmitryShylovich yes
[updated plunker](http://plnkr.co/edit/IlfpQRjAzPQr0TuuenxA?p=preview)

**Comment by benbraou** [comment]
I am going to give this a try (hopefully working on the fix this weekend).

**Comment by johnsonb2** [comment]
I want to be able to indicate in the UI that a complex form group has been validated, which has an async validator both on its child and on itself. This significantly impacts my ability to do so.

**Comment by faridanthony** [comment]
+1
