### ISSUE TITLE
Documentation proposal: It should be more confined and targeted

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#10067]
Trying to learn how to use Angular 2 I feel that the current documentation is far too verbose and random.

I personally don't understand what the documentation is trying to convery.

Topic | Perceived Purpose
--- | ---
QuickStart | Some explanation on how to work with _node_ and _npm_, but no particular information on _Angular 2_, its prerequisites and why it requires an prerequisites at all.
Tutorial | Loads of kindergarten waffle. Too much node. No table or bullet list of what's required to get a simple Angular 2 setup up and running.<br/>Content doesn't focus on header topic (see Master/Detail). Menu on the left should be more fine grained. You cannot find any of the information read in Master/Detail (e.g. styling) by browsing the menu.
Basics | Well made. Yet, it's just dealing with the code, not the setup. No table or bullet list of what's required to get a simple Angular 2 setup up and running.
Developer Guide | Visual Studio 2015 chapter: Why should some experienced programmer want to "copy the QuickStart files we downloaded from github into the folder containing the .csproj file"? Why isn't there a basic "add the _Angular2_ package to _DevDependencies_ in _package.json_ and set your module loader to load "Angular2.js"?
Cookbook	 | In-depth analysis of Angular features and development practices.
API Reference | Many items show "not yet implemented" - so why are they in the documentation anyway?

I would very much prefer if the Quickstart was a simple "add the _Angular2_ package to _DevDependencies_ in _package.json_ and set your module loader to load "Angular2.js". No more prerequisites, no other factors described. That should be enough in the Quickstart for getting the _**quick**_--start to work.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular.io docs repo

**Comment by SetTrend** [comment]
??

**Comment by SetTrend** [comment]
??

**Comment by skreborn** [comment]
@SetTrend This isn't an issue with Angular itself, but rather with the docs, which are not part of this repository. Please create this issue over at the [angular.io](https://github.com/angular/angular.io) repository, as per @DzmitryShylovich's comment.

**Comment by SetTrend** [comment]
@DzmitryShylovich / @skreborn : Ah, I see. Thanks for the valuable hint! :bouquet: 

As a non-member of Angular development I wasn't aware of the differenciation.
