### ISSUE TITLE
Observable.toPromise undefined in test Environment

### ISSUE THREAD

**Issue by najor** [angular/angular#10068]
Hi,

I am testing this method:
<pre>getIpAddress(): Promise<string> {
        return this.http.get('http://api.ipify.org')
            .toPromise()
            .then((response: any) => {
                return response._body
            });
    }</pre>

And testing like this:

<pre>it('Get IP address', (done: Function) => {
        geolocationService.getIpAddress()
            .then((ip: string) => {
                expect(ip).toBeDefined();
                expect(ip).toMatch(/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/);
                done();
            })
            .catch((error: Error) => {
                fail(error);
                done();
            });
    }, 10000);</pre>

And get this error:

<pre>this.http.get(...).toPromise is not a function</pre>

In running environment this works charmly, but in the test it fails, as if toPromise is not defined.

Thanks

**Comment by DzmitryShylovich** [comment]
U need to `import 'rxjs/add/operator/toPromise';` in your test env.

btw what the point in converting observable to promise?

**Comment by pkozlowski-opensource** [comment]
@DzmitryShylovich is right (thnx for helping out with the issues, this is very much appreciated!)
