### ISSUE TITLE
bug(http) data POSTs incorrectly with latest http-builds

### ISSUE THREAD

**Issue by qdouble** [angular/angular#10073]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```
**Current behavior**
If I run the current code below using http-builds, instead of RC4, the data in the post request will be sent as `[object Object]` instead of `{username: 'coolUser'}`. This causes the body parser on the server to give an error, so I can no longer use the latest http-builds with my server.

Here's it with angular builds: https://plnkr.co/edit/Kw3T7apUNFBvKmNc95L4?p=preview , you can see the data is sent as "data": "[object Object]"

Here's with RC: https://plnkr.co/edit/qXr0PrsPtJOvXLG3QVl7?p=preview , you can see the data is posted correctly with : "data": "{\"username\":\"coolUser\"}"

**Please tell us about your environment:**

* **Angular version:** 2.0.0-angular-builds
 
* **Browser:** [all | Chrome] 
 
* **Language:** [all | TypeScript ]

**Comment by vicb** [comment]
@jeffbcross could you take a look at this ? 

How is this tested in the http module ?

**Comment by thelgevold** [comment]
I believe the code needs a header and a stringify
```
var headers = new Headers();
    headers.append('Content-Type', 'application/json');
    this.http.post(`https://httpbin.org/post`, JSON.stringify({username: this.name}),{headers:headers})
      .map(res => res.json())
      .subscribe(data => {
        this.postResponse = data
        console.log(data)
      })
```
Here is a working post sample: http://www.syntaxsuccess.com/angular-2-samples/#/demo/http

**Comment by qdouble** [comment]
@thelgevold well it's not an issue with the header, it's the `JSON.stringify()` which makes your example work. If that's what we're supposed to do now, it's a breaking change, as it wasn't required in RC4.

**Comment by awerlang** [comment]
Prior to rc.2, it was required to add the header and stringify yourself.
This [commit](https://github.com/angular/angular/commit/0f0a8ade7cc7021ae17a69e1bf1222378f7aaefb) in rc.2 handles JSON for object payloads.
Looks like current master broke it with [this commit](https://github.com/angular/angular/commit/e7a8e2757b06d572f614f53b648d2fd75df370d2).

**Comment by cassand** [comment]
Indeed, this is due to the implementation of the function to convert to json 

Here is the old implementation :

` json(): string { return isPresent(this._body) ? JSON.stringify(this._body) : ''; }
`

Here is the new :
```
json(): any {
     if (isString(this._body)) {
       return Json.parse(<string>this._body);
     }
 
     if (this._body instanceof ArrayBuffer) {
       return Json.parse(this.text());
     }
 
     return this._body;
   }
```
Whereas the old one convert a json object to a string, the new one convert to a json object.

Therefore, if it is intended to pass json object as the string to the request, we have to update static_request.ts :


```
getBody(): any {
    switch (this.contentType) {
      case ContentType.JSON:
        return this.json();
      case ContentType.FORM:
        return this.text();
      case ContentType.FORM_DATA:
        return this._body;
      case ContentType.TEXT:
        return this.text();
      case ContentType.BLOB:
        return this.blob();
      case ContentType.ARRAY_BUFFER:
        return this.arrayBuffer();
      default:
        return null;
    }
  }
```
and change return for JSON to a text value.

**Comment by cassand** [comment]
@vicb  This is tested here : 
(angular/modules/@angular/http/test/backends/xhr_backend_spec.ts line 259)
`expect(sendSpy).toHaveBeenCalledWith(body);`

Which should become :
`expect(sendSpy).toHaveBeenCalledWith(JSON.stringify(body));` 
If we intend to convert json objects to string when there are passed as the request body.

If you want a fix for that, let me know.

**Comment by vicb** [comment]
@cassand yep a PR would be great, thanks.

We also probably need to fire up a server for the tests but that you be yet another PR.
