### ISSUE TITLE
[Router] Enable wildcard params in Component router

### ISSUE THREAD

**Issue by rcchen** [angular/angular#10078]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**

A route that is configured as so is not recognized when I go to a path called `foo/a`

```
{
  path: 'foo/*bar',
  component: FooComponent
}
```

**Expected/desired behavior**

I expect anything from `foo/a` to `foo/a/b/c` and so on to match against the same RouteConfig, where the param `bar` would equal `a` and `a/b/c` respectively. 

**What is the motivation / use case for changing the behavior?**

I'm trying to implement a file browser interface similar to what Github has and would like to be able to capture a path like `https://github.com/angular/angular/blob/master/modules/angular1_router/index.html` (in this example, my ideal route from the root would be represented as `:owner/:repo/blob/:ref/*path` with the following values in a params object

```
{
  owner: "angular",
  repo: "angular",
  ref: "master",
  path: "modules/angular1_router/index.html"
}
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4, angular/router 3.0.0-beta.2
 
* **Browser:** all
 
* **Language:** TypeScript 1.8.10

**Comment by rcchen** [comment]
Would be more than happy to attempt a PR to implement this feature if a maintainer feels this feature is reasonable and can give a bit of guidance on how this might be implemented 😃

**Comment by brandonroberts** [comment]
You can do this with wildcard matching already:

```ts
{
  path: 'foo',
  children: [
    { path: '**', component: FooComponent }
  ]
}
```

**Comment by rcchen** [comment]
Sorry, should have clarified and looked more closely for dupe issues, came across https://github.com/angular/angular/issues/6770 which describes what I'm looking for (specifically named params, if I'm not mistake I think your example makes the wildcard part of the path anonymous?)

**Comment by brandonroberts** [comment]
You're correct in that its not a named parameter, but retrieving the path that was used with the wildcard is still available in `ActivatedRoute.url`

**Comment by vsavkin** [comment]
Dup of https://github.com/angular/angular/issues/6770
