### ISSUE TITLE
Preventing duplicate IDs when emulating shadow DOM

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1007]
#### Problem
Say you have a component template:
```html
<div class="autocomplete">
  <input role="combobox" class="autocomplete-trigger" 
      aria-autocomplete="list" 
      aria-active-decendant="" <!-- = Whichever option ID is focused -->
      aria-owns="autocomplete-menu">
  <ul id="autocomplete-menu" tabindex="-1">
    <li *foreach="#opt in options" role="option" [id]="opt.id">Alpha</li>
  </ul>
</div>
```

In this example, use of an ID is necessary for the `aria-owns` attribute. With the current shadow DOM emulation, it will not work to have multiple instances of this component on the page at the same time because the IDs would be duplicated.

Other use cases include `<label>`, `aria-labelledby`, `aria-controls`, `aria-described-by`, `aria-flowto`

#### Possible solutions
There are a few different ways we could handle this.

##### Put the burden on the user
```html
   <input [id]="myGeneratedUniqueInputId">
   <label [for]="myGeneratedUniqueInputId">
```

This is what people would have done in Angular 1. Adopting this should just be a matter of documentation.

##### Automatically recognize ID attributes and shim ID isolation
If the user writes:
```html
   <input id="name">
   <label for="name">
```

Angular will recognize any standard attributes that use an ID reference (or list of ID references) and automatically convert them into document-unique IDs them. 

##### Add some syntax to identify IDs for unique conversion
Specific syntax aside, something like:
```html
   <input ##id="name">
   <label ##for="name">
```

This has the benefit of not having to hard-code the list of ID-reference attributes, but still incurs the same performance cost as the previous solution.

**Comment by jelbourn** [comment]
Note that this is something that would have to be done for `EmulatedScopedShadowDomStrategy`, but not `EmulatedUnscopedShadowDomStrategy`

**Comment by mhevery** [comment]
Will not support with the new `ng-content`
