### ISSUE TITLE
ContentChild object always undefined

### ISSUE THREAD

**Issue by bobbywarner** [angular/angular#10076]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This issue is similar to https://github.com/angular/angular/issues/8937, but that issue states it occurs in RC1.  My use-case actually worked in RC1, but now fails in RC4.

**Expected/desired behavior**

**Reproduction of the problem**
https://github.com/bobbywarner/quickstart/commit/325e297a1c76773c9a00affc44eeac244d8bb8e5

```
ngAfterContentInit() {
  // this always logs undefined
  console.log(this.control);
}
```

**What is the expected behavior?**
```
ngAfterContentInit() {
  // this should not log undefined as ContentChild should be populated, right?
  console.log(this.control);
}
```

**What is the motivation / use case for changing the behavior?**
Not changing behavior, just trying to use `ContentChild`.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Language:** [TypeScript 1.8]

**Comment by pkozlowski-opensource** [comment]
> Reproduction of the problem
bobbywarner/quickstart@325e297

Please put it in a minimal plunker - it is very hard and time-consuming for us to debug full projects.

**Comment by bobbywarner** [comment]
Sure, I can, but it's the Angular Quickstart app (https://github.com/angular/quickstart) with one commit that shows all the changes to demonstrate the problem.  I thought that would be better than Plunker, but happy to create a Plunker if that's what you prefer.

**Comment by bobbywarner** [comment]
https://plnkr.co/edit/C5BS0Cf4Qsnh7VosSGYE?p=preview

The `@ContentChild` property (`@ContentChild(FormControl) control: FormControl;`) in `src/form.field.ts` is never populated and always undefined.

**Comment by vicb** [comment]
Any chance you ant to do `@ContentChild(FormControlDirective) ctrlDir` ?

**Comment by bobbywarner** [comment]
@vicb Awesome!  That works.  Thanks!

**Comment by pkozlowski-opensource** [comment]
Plunker magic :-)

**Comment by BrainCrumbz** [comment]
Not sure anyone reads this from a closed issue, let's try.

It seems this stops working when you have an app structure similar to:

```html
<form>
  <wrapper>
    <field label="SKU" input="skuInput">
      <input type="text" id="skuInput" placeholder="SKU" [formControl]="myForm.controls['sku']">
    </field>
  </wrapper>
</form>
```

where *WrapperComponent* is like:

```html
<div class="some-wrapper-class">
  <div class="some-other-thing">
    <ng-content></ng-content>
  </div>
</div>
```

Here, when *WrapperComponent* has a `@ContentChild(FormControlDirective)` field, that is correctly set by framework. But now the `@ContentChild(FormControlDirective)` field in *FormFieldComponent* is never set.

**Comment by stguitar** [comment]
Oh my god, this is exactly what I was looking for.  However, for those that arrive here later, I was using the 'formControlName' directive, and what allowed this to work for me was by using:

`@ContentChild(FormControlName) control;`
