### ISSUE TITLE
NG2 Animation (Web Animation) support in Firefox/Safari - official plunker demo not working in mentioned browsers

### ISSUE THREAD

**Issue by vsimak** [angular/angular#10088]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Cannot get the void => * transition animations to work in Firefox (47.0.1) and Safari (9.1.1) on MacOSX on our production website. To make it simpler, after trying to find a solution (included the web-animation polyfill for cross browser support) I went to the official NG2 Animation Docs plunker and opened it in Safari/Firefox respectively: the animations did not work.

**Expected/desired behavior**
The animations via NG2 Animations working in Safari/Firefox 

**Reproduction of the problem**
Open in Safari or Firefox: https://angular.io/resources/live-examples/animations/ts/plnkr.html.

**What is the expected behavior?**
NG2 animations working in major modern browsers

**What is the motivation / use case for changing the behavior?**
Better UX on the web overall

**Please tell us about your environment:**
The production is ran on webpack node ng2 combo.
But the official plunker for ng2 animation also does not work cross-browser which is my main example to go by

* **Angular version:** 2.0.0-rc.X
2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 Chrome:  51.0.2704.103 (64-bit), Firefox: 47.0.1, Safari: 9.1.1 (10601.6.17),

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
TypeScript 1.8.10.

**Comment by skreborn** [comment]
Since this is an angular.io issue, please submit it in the [appropriate repository](https://github.com/angular/angular.io/issues).

**Comment by matsko** [comment]
@Foxandxss did the plnkr generator for the docs get created? Can we include the polyfill into the example files or do we need to edit the plnkrs manually?

**Comment by Foxandxss** [comment]
I am a bit lost in here.

That concrete plunker has the animation polyfills and should work everywhere. The others doesn't have it but we don't have animations elsewhere.

**Comment by matsko** [comment]
My mistake. It looks like it is fixed.
