### ISSUE TITLE
Add support for setting attributes to Component host element

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1008]
We currently have `@PropertySetter` to set properties to a component host element, but there's no way to set *attributes*, specifically for aria purposes. This would be useful for things like `aria-checked`, `aria-disabled`, `aria-selected`, etc.

**Comment by mhevery** [comment]
@pkozlowski-opensource both#1008 and #1009. I think that `@PropertySetter('a.b')` should go through same code path as `[a.b]`. Since we already have `[a.b]` this should be straight forward.
