### ISSUE TITLE
AppModule

### ISSUE THREAD

**Issue by eyalvardi** [angular/angular#10087]
Hi,
I think you need to change the name of AppModule to **Package**, the word module can confuse with JavaScript and TS module.

One more thing, I think you need to add to Component decorator a property packages for array of Package class, This will make it much simpler from the use of: directives,pipes,providers... one for all (packages).

**Comment by Pablo-Ivan** [comment]
Agreed!

**Comment by otodockal** [comment]
I was thinking about the same @AppModule -> @Package.

But I guess the core team had considered this name before :).

**Comment by IgorMinar** [comment]
Package collides with npm package. We are considering NgModule instead of AppModule. We'll take your feedback into consideration.
