### ISSUE TITLE
error TS2345: Argument of type 'ElementRef' 

### ISSUE THREAD

**Issue by nivinpaul** [angular/angular#10086]
Hi,

I have got an error when on executing angular2 autocomplete.

error TS2345: Argument of type 'ElementRef' is not assignable to parameter of type 'ViewContainerRef'.
 Property 'element' is missing in type 'ElementRef'

Please help

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for support request.
