### ISSUE TITLE
Lifecycle interfaces became abstract classes

### ISSUE THREAD

**Issue by kemsky** [angular/angular#10083]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
export declare abstract class OnInit {
    abstract ngOnInit(): any;
}
```

**Expected/desired behavior**

```
export interface OnInit {
    ngOnInit(): void;
}
```

This is valid in TypeScript, but it does not look right:

```
class Some extends OnInit {
      ...
}
```

vs

```
class Some implements OnInit,OnChanges {
     ...
}
```

vs

```
class Some extends OnInit, OnChanges { //compile error
     ...
}
```

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4

**Comment by vicb** [comment]
IIRC this was due to a limitation of ts2dart. We should be able to solve that but it is not a priority.

**Comment by aluanhaddad** [comment]
@kemsky TypeScript allows you to _implement_ abstract classes as follows:
```TypeScript
class Some implements OnInit, OnChanges { //compile error
     ...
}
```

Still though, this should be fixed. It is a confusing change. It is disappointing that this is Dart related...
