### ISSUE TITLE
Ability to set attrs/properties on root element of a component

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1009]
I have a `<side-menu>` component in 2.0.0-alpha.13. Currently, to set the `open` class on the side menu to show/hide it, I have to manually manipulate the dom element:

```js
import {Component, Template, NgElement} from 'angular2/angular2';
@Component({
  selector: 'side-menu'
})
@Template({
  inline: `<div class="scroll-area">
    <content></content>
  </div>`
})
class SideMenu {
  constructor(@NgElement() el: NgElement) {
    this.element = el;
  }
  //drag logic ommitted...
  setOpen(isOpen) {
    this.isOpen = isOpen;
    this.element.domElement.classList[isOpen ? 'add' : 'remove']('open');    
  }
}
```

I'd like to be able to setup a `[class.open]="isOpen"` binding on my component's element instead of having to do this.

@mhevery suggested injecting `@PropertySetter('class.open') setter: Function` into the constructor, but that errors when used because the actual `setter` function tries to set `domElement.class.open`. And `domElement.class` does not exist.

**Comment by ajoslin** [comment]
Duplicate of #1008

**Comment by mhevery** [comment]
@pkozlowski-opensource both#1008 and #1009. I think that `@PropertySetter('a.b')` should go through same code path as `[a.b]`. Since we already have `[a.b]` this should be straight forward.
