### ISSUE TITLE
http.delete method not working

### ISSUE THREAD

**Issue by mikmar88** [angular/angular#10092]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The http.delete method doesn't work. It send an OPTIONS method instead DELETE method.

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by vicb** [comment]
Please provide a plunker

**Comment by vicb** [comment]
You are probably accessing an external domain, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

**Comment by amikitevich** [comment]
Hi, please see code: http://plnkr.co/edit/DazdhfsHpGopWlSzQPDa?p=preview 

I receive the error: 

```
browser_adapter.js:84 Error: Uncaught (in promise): TypeError: Cannot read property 'toString' of null
    at resolvePromise (zone.js:538)
    at zone.js:515
    at ZoneDelegate.invoke (zone.js:323)
    at Object.onInvoke (ng_zone_impl.js:53)
    at ZoneDelegate.invoke (zone.js:322)
    at Zone.run (zone.js:216)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.onInvokeTask (ng_zone_impl.js:44)
    at ZoneDelegate.invokeTask (zone.js:355)
```

Http.delete method work without any headers.

Thank you.

**Comment by amikitevich** [comment]
Should I create new issue?

**Comment by pkozlowski-opensource** [comment]
> Should I create new issue?

No need, you issue is a duplicate of #10612

**Comment by amikitevich** [comment]
Ok, thank you.
