### ISSUE TITLE
Trigger dynamic  css updates for updated style metadata

### ISSUE THREAD

**Issue by agalazis** [angular/angular#10093]
**I'm submitting a ...** 

```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Css is compiled only once based on the metadata configured in the component decorator

**Expected/desired behavior**
Expose the functionality to recompile (Maybe we could achieve this by updating metadata and triggering a recompile )

**What is the expected behavior?**
After recompiling the component should have its encapsulated css based on the updated metada

**Comment by vicb** [comment]
What is the use case ?

**Comment by agalazis** [comment]
I have a scenario like this:
https://github.com/cstefanache/ng2-styler
 but the variables come from a service so I need support for asynchronous compilation:
First case I might what to disable initial compilation of css until I retrieve the data from the service and the trigger compilation when I want to. (forgot to mention about the need to control initial compilation)

(I tried to use a resolver(on the router) but it doesn't seem to have any effect on css compilation)

Second case when this variables change eg. I want to change theme I want to be able to trigger recompilation.

An other solution is to make the styles observable and just recompile if somebody updates something in the array

**Comment by zoechi** [comment]
Sounds similar to #2567 and #6274

**Comment by agalazis** [comment]
not entirely  since updating css is not entirely solved by just the use of css variables but of course if the variables are declared in an import then that would be fine for the first use-case. My import should hit the service and get the right variables.

**Comment by jimitndiaye** [comment]
@agalazis probably doesn't directly address your use case since you're still statically setting styles via a decorator, but the best workaround I've found for dynamic CSS variables is use of the NgStyle directive bound to a component property.

**Comment by agalazis** [comment]
thought of that but not as elegant. If we co down that path I could write inline css from variables or use set style properties of dom elements in js .  Anw, hopefully we'll get css variable shims soon as  that would also solve the main part of my usecase xD

**Comment by vinayakpatil** [comment]
+1
