### ISSUE TITLE
ANY directive conditional? directive-if option possible?

### ISSUE THREAD

**Issue by poziminski** [angular/angular#10097]
[ X ] feature request

Is there possible for angular (1) to provide functionality for ANY directive to be conditional?
I would suggest a parameter in a directive that would handle "if" statement:
`app.directive('ngNicescroll', function () {
    return {
        conditional: true
    }
});
`
And then user could add optional -if parameter in HTML:
`<div ng-nicescroll-if="myStatement"></div>`

I know it can be impossible in some cases, but can you consider this option in future? It would be very helpful for directive downloaded with bower etc.

Sorry, this is a repo for Angular 2, missed this...

**Comment by vicb** [comment]
Angular1 is at https://github.com/angular/angular.js
