### ISSUE TITLE
Angular CSS encapsulation/injection with nested components targets incorrectly

### ISSUE THREAD

**Issue by layton-glympse** [angular/angular#10102]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
CSS in nested components doesn't always take all styles. Presently I'm using webpack to transform SCSS files, and with nested components I've run into issues where styles declared at the root level (i.e. global) will _seemingly_ override styles that are at higher levels of specificity. However, on closer inspection I'm seeing that the Angular mechanism for adding the auto-generated selectors seems to be failing.

Here is one example (though I've run into this problem in many cases):

*Outer File* - app.scss
```
h1 {
    color: #F00;
}
```

*Inner Component 1* - template-wrapper - no ViewEncapsulation set (uses default)
```
.template-wrap{
    //...some styles
    h1 {
        color: #7774 ;
    }
}
```

The template-wrapper component contains another component that contains h1 tags. An important note, ViewEncapsulation.None is set on it (and changing it has no effect). Those h1 tags come out red, not gray as you might expect. Inspecting what's injected into the head, I see this:

```
<style>
.template-wrap[_ngcontent-htg-8] {
  //other styles...
  .template-wrap[_ngcontent-htg-8] h1[_ngcontent-htg-8] {
    color: #777; }
  .template-wrap[_ngcontent-htg-8] template-iframe[_ngcontent-htg-8] {
    //other styles....
  }
</style
```

The injection looks correct! Yippee!

However... inspecting the component itself, the h1 tag has no `[_ngcontent-htg-8]` attribute applied to it. See for yourself:

```
<h1>HeIlo World</h1>
```

So, either the CSS is being injected improperly, or the
However... inspecting the component itself, the h1 tag has no `[_ngcontent-htg-8]` attribute applied to it. See for yourself:

```
<h1>HeIlo World</h1>
```

So, either the CSS is being injected improperly, or the template is being output incorrectly. Related issues:

https://github.com/angular/angular/issues/7562
https://github.com/angular/angular/issues/6511
https://github.com/angular/angular/issues/5064

Clearly there are/were some issues around this (I'm sure its a complex problem), however what's happening right now is breaking stuff.

I also am aware that encapsulation is to the component and not it's children, so it could be argued that the parent is actually being correctly targeted. But even if you do something like:

```
.parentComponent .childComponent h1{
    color: #F00;
}
```

It doesn't take. Every selector in that class gets the [_ngcontent.....] tag added to it.
What exactly is the approach, then, to using CSS as a cascading system in this case?

**Expected/desired behavior**

Proper targeting of CSS. Since ::shadow and /deep/ are deprecated, I feel like I'm coming up dry with the right way to do this... Perhaps I don't understand how to use it but it seems to be a bug to me.

Using Angular 2.0.0.RC4

**Comment by vicb** [comment]
The CSS shimming still supports `/deep/`.

I you think there is an issue in the code please create an issue attaching a plunker with the minimal amount of code to reproduce. Thanks.

**Comment by layton-glympse** [comment]
@vicb yes, but why use something that has been deprecated? Is there really no other answer besides use a thing that will break your code eventually? For now, we're opting to turn encapsulation off entirely, which kind of defeats the point, it seems.

Why does angular emulate shadown dom by applying the [custom-selector] to every single element in the css selector chain instead of just the first one, which would be sufficient for targeting? It makes it impossible to target child _components_ when a component's encapsulation is turned on, despite the fact that the child component is _inside_ the current one.  Does that make sense?

This is at this point purely a design discussion, and I'm happy to file a ticket somewhere (not sure where to do that) to have people consider the use cases, but currently from what I'm seeing it, it is literally impossible to override styles on child component elements from within the scss file of the parent due to how encapsulation works, since the child component's elements do not get the custom selector applied to them, but their CSS does.

**Comment by zoechi** [comment]
@layton-glympse   `/deep/` is implemented in Angular and is not related to `/deep/` from Chrome (which is actually deprecated). Whether Chrome deprecates `/deep/`or not does not have any effect to your Angular2 app (as long as you're not using `ViewEncapsulation.Native`)
