### ISSUE TITLE
Router: Cannot link directly to parent route

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#10116]
**I'm submitting a ...**
```
[x] bug report
```

If I have the following route config:

```ts
export const routes: RouterConfig = [{
  path: 'home',
  component: Home,
  children: [{
    path: 'about',
    component: About
  },{
    path: 'list',
    component: List
  }
}];
```

And I try to link to /home:

```html
<a [routerLink]="['/home']">Home</a>
```

**Current behavior**

The link doesn't work. It is not possible to link directly to /home.

The only solution I can find is to add an additional empty-path, componentless child route to the home route.

**Expected/desired behavior**

It should be possible to link directly to /home, without loading any of its child components.

**What is the motivation / use case for changing the behavior?**

Easy of use. Avoidance of confusion. Sanity.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all
 
* **Language:** all

**Comment by zoechi** [comment]
Plunker to reproduce the problem?

**Comment by jonrimmer** [comment]
http://plnkr.co/edit/Tuz5RbAGIjEmMTyA5P0B?p=preview

As you can see, the links to /home/about and /home/contact work, but the link simply to to /home does not.

**Comment by zoechi** [comment]
The `/home` route shows the `HomeComponent` that contains a `<router-outlet>` but doesn't have a matching child route.

In http://plnkr.co/edit/ghilH44tfR1FeV9emw90?p=preview I added a `DummyComponent` default child route  
and I switched to `HashLocationStrategy`.   
It should work with `PathLocationStrategy` locally as well if you use a server that supports it.

**Comment by jonrimmer** [comment]
@zoechi I know that you can "fix" it by adding a dummy child component. I said so the original report.

You shouldn't need to add a pointless child component just so you can link directly to its parent. You should be to link to directly home and have it load nothing in the router-outlet. The current behaviour is completely unintuitive and insane.

**Comment by akomm** [comment]
Just moved back from ngrx/router to angular/router and now simple setup that worked does not work :-7

**Comment by vsavkin** [comment]
Dup of https://github.com/angular/angular/issues/12133
