### ISSUE TITLE
CONTRIBUTING.md contains a lot of misinformation

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#1011]
It looks like the file was just compied from Angular 1 repo with some superficial changes.

Concrete problems:

- `Got a Question or Problem?` section points people to gitter and Angualar 1 mailing list that we don't actively monitor.
- `Coding Rules` section is mostly obsolete
- `Signing the CLA` section references the steps from before SignCLA launch

**Comment by chalin** [comment]
It is a first cut / work-in-progress. Feedback is most welcome!

> Got a Question or Problem? section points people to gitter and Angualar 1 mailing list that we don't actively monitor.

Right, and this issue has been raised in #928. Once a decision is made, I'll gladly update the docs (once new groups are created, if that is what is decided). 

On a similar topic, someone might want to give some though to which [Stackoverflow tags](http://stackoverflow.com/tags) we want to standardize on for Angular 2. FYI: so far there are `angular2`, `angularjs-2` and `angularjs-2.0`.

> Coding Rules section is mostly obsolete

The first two bullets say 'write tests to exercise your code changes' and 'document public APIs'. That seems generally applicable. The third bullet (about JS style guide and wrap at 100) is probably ok until a TypeScript style guide comes out :). 

What do you find obsolete? I'd be glad to update it. Maybe you are referring to the `Commit Message Guidelines` as being obsolete? Folks seem to be following it none-the-less --- maybe out of habit :). That section can be cut / edited if needed.

> Signing the CLA section references the steps from before SignCLA launch

That is how the [angular.js/CONTRIBUTING.md](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md) and [angular.dart/CONTRIBUTING.md](https://github.com/angular/angular.dart/blob/master/CONTRIBUTING.md) are setup and it seemed acceptable. Note that the second step of [Submitting a Pull Request](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-a-pull-request-pr) asks to "Please sign our Contributor License Agreement (CLA)" with a (forward) link to the Signing the CLA section.

> It looks like the file was just compied from Angular 1 repo with some superficial changes.

No, it was carefully edited to the best of my knowledge and decisional powers (e.g. it is up to the core team to decide if they want a new Google group or not -- #928).

**Comment by naomiblack** [comment]
Updated the contributing doc.
