### ISSUE TITLE
Core: Production Mode function calling

### ISSUE THREAD

**Issue by Pablo-Ivan** [angular/angular#10118]
General Inquiry: When I deploy an app and see it in the browser, the console logs "The app is currently in development mode, please call 'enableProdMode()'". What does this function do, in what file and from where should I call it?
**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [ Chrome 50 ] 
 
* **Language:** [ TypeScript 1.8 ]

**Comment by ericmartinezr** [comment]
What does it do
https://angular.io/docs/ts/latest/api/core/index/enableProdMode-function.html

An example
https://github.com/angular/angular/blob/master/modules/@angular/examples/core/ts/prod_mode/prod_mode_example.ts

Pro tip
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by Pablo-Ivan** [comment]
Ok, thanks! Now it seems really obvious to look in the API Docs.
