### ISSUE TITLE
`ngModel` is no longer ambient by default

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10117]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```
Most apps use `[(ngModel)]` even if they don't use Forms.

The "toy" (aka "experimental") bootstrap method that is supposed to bridge existing apps to RC5 without breaking them creates an `AppModule` that does **not** make `ngModel` ambient.

That means that ​all current documentation samples that use `ngModel` are broken* and all userland apps will be broken by current head in master.

**Current behavior**

Most current documentation apps fail, reporting that they don't know what `ngModel` is, when they reference the current (16 July 2016) builds.

**Expected/desired behavior**

Most existing apps should *just work* after installing RC5 without changing how they are bootstrapped.

**Reproduction of the problem**

See https://plnkr.co/edit/yMCUFebehxjuyGCRIGap?p=preview

Follow instructions for exposing `ngModel`.

**Solutions?**

An obvious approach would be to revise the "toy" (aka "experimental") `bootstrap` so that its dynamic `AppModule` either includes the `FormsModule` or the directive(s) that support `ngModel`.

There may still be a problem for apps that use that deprecated forms.

We could also look into adding **a lightweight `NgModel` directive to core** that does the minimum simulation of two-way data binding. Such a directive would only select for known controls in the absence of parent elements with `NgForm` or perhaps not select when inside `<form>` tags.  We could further minimize it's impact by excluding it from `BrowserModule` but adding it as part of the "toy" bootstrap.

**Comment by wardbell** [comment]
I learned from @kara a fatal flaw in my proposal: it would require that `platform-browser-dynamic` take a dependency on `Forms`.

Clearly we can't have that.  The developer will almost always choose to load the `FormModule` and pay the price just to get `ngModel`. But that must still be the developer's choice. We can't _require_ the `FormsModule`.

One other possibility is to create a NEW project, call it: `@angular/bootstrap-deprecated`.

This one DOES have the requisite dependencies on both `platform-browser-dynamic` and `Forms`. It only exposes the "toy" (aka "experimental") bootstrap.

Now all apps will still be broken when RC5 lands. But the short term fix is easy:
```
import { bootstrap }    from '@angular/platform-browser-dynamic'; // before RC5
import { bootstrap }    from '@angular/bootstrap-deprecated'; // after RC5
```

If we can't have that, then we have to teach proper bootstrapping with `AppModule` where we can include the `FormModule` explicitly and provide a lot of immediate guidance for people upgrading to RC5 _right now_.  The  "toy" (aka "experimental") bootstrap is effectively useless. We might as well just delete it and be done with it.

**Comment by thelgevold** [comment]
I guess you can make an argument in favor of exposing developer to these new concepts early, but I personally think they should hold the next rc release until this concept is in a final state.

I think it's fair to incrementally roll out an experimental product during the beta phase, but at this point I think the term rc is used very loosely with Angular 2.0. 

In my book an rc version should have a fighting chance of getting released "as is". After all it's named release candidate...

We will soon be on the fifth iteration of "rc" and it doesn't seem like it's about to stop anytime soon. 

My vote is to publish the proposed api changes and hold releases until things are stable and figured out. 

I think I get the intention behind these partial releases, but it adds a lot of overhead to documentation and training efforts.   As a developer I also find it very frustrating to have to keep rewriting my code very late in the release cycle.

**Comment by naomiblack** [comment]
Just commenting that RC5 has not been released yet, so these concerns are about the current master branch. We'll discuss this week and clarify before RC5 lands.

**Comment by wardbell** [comment]
This working alternative _entry level_ bootstrap may be a suitable upgrade-to-RC5 alternative:
```
import { bootstrap }    from '@angular/platform-browser-dynamic';
import { FormsModule }  from '@angular/forms';

import { AppComponent } from './app.component';

bootstrap(AppComponent, {modules: [FormsModule]});
```
Yes it requires an update to everyone's bootstrap. But it's pretty lightweight and postpones the day that someone has to learn to create a new `AppModule` class.

It's also a small step for anyone who was previously using the bootstrap providers array. They just do this:
```
bootstrap(AppComponent, {
  modules: [FormsModule],
  providers: [ /* what they had before */]
});
```
I think most developers would appreciate the explicitness of this choice. It will feel like a step up, especially when they learn they can add their own ambient directives this way:

```
bootstrap(AppComponent, {
  modules: [FormsModule],
  directives: [MY_AMBIENT_DIRECTIVES],
  providers: [ /* what they had before */]
});
```

**Comment by wardbell** [comment]
I want to make one more impassioned pitch for ***some kind of `ngModel` in core***.

Long ago it became very clear that the community wants a native two-binding syntax. They don't want to write a whole bunch of lines like this:
```
<input #nameBox [value]="hero.name" (change)="hero.name=nameBox.value">
```
They don't want to have to remember what is the "value" property and what is the "change" property for every element. They just want it to work. And I feel the same way.

Having to bring in the `FormsModule` certainly does the job. And it's no worse than what we had to do before ... because all of what is now `FormsModule` was buried inside `core`.

But now that we've broken it out, there's an opportunity to do a lightweight version of `ngModel` that just does 2-way data binding.

As I recall, the old directive had two modes: one in the presence of forms, one without. We could do that again. 

Two ideas:
1) An `NgModel` in core that gets out of the way when/if `NgForms` appears
2) A new directive dedicated to two-way data binding, plain and simple. Call it `Ng2Way` or `NgBind`. Then no risk of confusion.

Food for thought.

**Comment by IgorMinar** [comment]
summary of our conversation where we decided to keep NgModel in the forms module:

- ngModel can only be used with forms (input and other form controls), so it makes logical sense that it's part of the forms module
- ngModel only makes sense if you are using template driven forms, so it should be available only if application uses template driven forms
- with AppModules/NgModules you will be able to make ngModel visible within your application module using a simple import (no need to list NgModel everywhere) which will improve the ergonomics
- internal argument: NgModel has a lot of implementation-level dependencies on other things in the forms module, so extracting it out is not possible and having two implementation (one in core and one in forms) is a recipe for problems

There is an ongoing discussion about making it possible to use banana in a box syntax on input fields without NgModel, if we reach consensus about this we'd work on this feature after 2.0

**Comment by wardbell** [comment]
That's a great summary @IgorMinar .  I agree with this decision. For those who want more background and my opinions, I wrote an extended explanation (from my point of view) in [this google doc](https://docs.google.com/document/d/1Kr_LmYc1fqnVcOQdSLiSCD6X4-SMqsKRLiZU6rY3wsY/)
