### ISSUE TITLE
Angular quick start not working with latest typescript

### ISSUE THREAD

**Issue by Drag13** [angular/angular#10129]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
Angular 2 quick start package works with typescript "typescript": "^1.8.10". But the latest version of TS has breaking changes with default export. So, when using latest TS, it is not working. Using 1.8.10 typescript fixes the problem. So the best idea (for now) is to update quick start and fix version of typescript.

**Expected/desired behavior**
Quick start should work correctly.

**Reproduction of the problem**
Create new application and install fresh and latest packages. Pay attention to the typescript version. Start an application. Open console.

**What is the motivation / use case for changing the behavior?**
Working angular with latest TS.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [ Chrome  ] 
 
* **Language:** [TypeScript]

**Comment by zoechi** [comment]
Any link to the breaking change info?

**Comment by Drag13** [comment]
I found my problem here. 

http://www.2ality.com/2014/09/es6-modules-final.html

Default exports (one per module)

_Modules that only export single values are very popular in the Node.js community. But they are also common in frontend development where you often have constructors/classes for models, with one model per module. An ECMAScript 6 module can pick a default export, the most important exported value. Default exports are especially easy to import._

After downgrading from latest TS to the 1.8.10 my app works fine.

**Comment by qdouble** [comment]
I guess it just depends on your settings, I'm running typescript 2.1 beta

**Comment by Drag13** [comment]
My TS buidler forced me to add "default" keyword in this statement: 
export **default** class AppComponent { }
And after this application throws errors about not found metadata. After downgrading TS and removing  default keyword all works fine. 
Possibly TS version is not the reason but I can not see other reason of such behavior.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource Can be closed or moved to docs repo.

**Comment by pkozlowski-opensource** [comment]
Thnx @Drag13 - @Drag13 could you please check if this is still a problem and move over to https://github.com/angular/angular.io if that's the case? Thnx!

**Comment by Drag13** [comment]
For release version this is not a problem already.
Ty!
