### ISSUE TITLE
How to setup test environment with jasmine & karma for Angular2 app

### ISSUE THREAD

**Issue by micronyks** [angular/angular#10122]
I want to test my app component. How to setup with [testing tutorial](https://angular.io/docs/ts/latest/guide/testing.html)

I have followed angular-2 quick start tutorial.
My folder setup is as follow:

NOTE: This app is working.

Angular2<bR>
|_______app<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |____________test.spect.ts<br> 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |____________app.component.ts<br> 
|_______node_modules<br>
|_______typings<br>
|_______index.html<br>
|_______package.json<bR>
|_______systemjs.config.js<bR>
|_______tsconfig.json<br>
|_______typings.json<bR>
|_______unit-tests.html

Now after successful execution of angular2 app, I want to setup test environment So I have done following steps.

1). Created **unit-tests.ts** file sibling to **index.html** (file code is shown below after steps)

2). installed `npm install jasmine-core --save-dev --save-exact`

3). updated **tsconfig.json** as said 

    {
      "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "suppressImplicitAnyIndexErrors": true //<-----added this line as said to existing file 
      }
    }

4). created **test.spec.ts** under **app folder**

    describe('1st tests', () => {
      it('true is true', () => expect(true).toEqual(true));
    });

5). tried to load this **test.spec.ts** through **system loader** in **unit-tests.html**

**unit-tests.html**

    <!DOCTYPE html>
    <html>
    <head>
      <meta http-equiv="content-type" content="text/html;charset=utf-8">
      <title>Ng App Unit Tests</title>
      <link rel="stylesheet" href="../node_modules/jasmine-core/lib/jasmine-core/jasmine.css">
      <script src="../node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
      <script src="../node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js"></script>
      <script src="../node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>
    </head>
    <body>
       <script src="../node_modules/systemjs/dist/system.src.js"></script>
       <script src="systemjs.config.js"></script>
      <script>
        // #2. Configure systemjs to use the .js extension
        //     for imports from the app folder
        System.config({
          packages: {
            'app': {defaultExtension: 'js'}
          }
        });
    
        // #3. Import the spec file explicitly
        System.import('app/test.spec')    //<--------look at here
    
          // #4. wait for all imports to load ...
          //     then re-execute `window.onload` which
          //     triggers the Jasmine test-runner start
          //     or explain what went wrong.
          .then(window.onload)
          .catch(console.error.bind(console));
      </script>
    </body>
    </html>

 
6). npm run tsc

7). npm start

problem: I thought it will load or look for **unit-tests.html**, but every time it runs **index.html**

What is missing? How to load or look for **unit.tests.ts** with **npm start**???

**Comment by thelgevold** [comment]
You should take a look at Angular CLI. It sets up a complete karma unit testing environment:
https://github.com/angular/angular-cli

**Comment by micronyks** [comment]
I don't use angular cli. Want to integrate with core angular2 project without cli.

**Comment by thelgevold** [comment]
That is fine. You can use the Angular CLI setup as a template for your own project.

**Comment by thelgevold** [comment]
In any event. This will be categorized as a support request and will likely be closed since it's not a bug with Angular 2.
You are better off asking this question in the Gitter chat room: https://gitter.im/angular/angular

**Comment by micronyks** [comment]
Yes I agree. But I have already asked this question at Stackoverflow but still haven't got any help from anyone.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by napstercake** [comment]
@micronyks did you resolve your issue?

**Comment by micronyks** [comment]
@napstercake nope. I ended up using it with cli only.
