### ISSUE TITLE
router: relative nav expression w/ param in RouterLink produces bad URL

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10128]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
The following _absolute_ `routerLink` assigment produces the expected URL
```
<a routerLink="/heroes/{{hero.id}}">  -> ~/heroes/12
```

Here are examples of `routerLink` assignments that produce unexpected URLs
```
<a routerLink="../{{hero.id}}"> -> ~/heroes/(12)
<a routerLink="{{hero.id}}">  -> ~/heroes/(12)
<a [routerLink]="hero.id">  -> ~/heroes/(12)
<a routerLink="['../', hero.id]"> -> ~/heroes/(%5B'../'%2C%20hero.id%5D)
```
Notice that the id parameter is surrounded in parens.

This isn't just an ugly artifact. While the router can handle it within the app, pasting it into a new tab (deep linking) results in a navigation failure. 

Moreover, our eyes are becoming trained to the notion that a value in parens has something to do with named outlets.

In my `HeroDetailsComponent` example,  I have a link back to the `HeroListComponent` that I can't get right:
```
<a routerLink="../"> -> ~/heroes/()
```
Clicking it gets me back to the list but THEN all my calculated links from above become like this:
```
http://localhost:3000/heroes/(/(12))
```
Notice the `(/(12))`. Obviously that goes no where as a deep link ​_pasted into the address bar_​.

Curiously, I can click that as much as I like as long as I stay ​_within the app session_​. If I keep toggling back and forth I end up with this:

```
http://localhost:3000/heroes/(/(/(/(12))))
```

**Expected/desired behavior**

The pertinent link in the hero list should always produce: `http://localhost:3000/heroes/12`.

**Reproduction of the problem**
Try http://plnkr.co/edit/17wH7sSm87TXUajNPQ1q?p=preview

To see the address bar effects, click the tiny blue-square-w/-white-x, top right, near the eyeball; that opens a pop-up (edited)

Play with the "Heroes"; all of the hero-specific code is in files "app/hero/..."

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 (candidate 16 July 2016)
 
* **Browser:** [Chrome] 
 
* **Language:** [TypeScript 1.8]

**Comment by zoechi** [comment]
`RouterLink` requires an array, not a string. I guess the expected behavior should be an error.

    <a routerLink="/heroes/{{hero.id}}"> 

should be

    <a [routerLink]="['/heroes/' + hero.id"> 

or

    <a [routerLink]="['/heroes',hero.id">
