### ISSUE TITLE
Bug? ContentChild not working with nested directives.

### ISSUE THREAD

**Issue by vagarenko** [angular/angular#10121]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Consider this code:
```
import {Component, Directive, ContentChild} from '@angular/core'

@Directive({
  selector: '[target]'
})
export class Target {}

@Directive({
  selector: '[findTarget]'
})
export class FindTarget {
  @ContentChild(Target) target: Target;
  
  ngAfterContentInit() {
    console.log('Content', this.target)
  }
}

@Component({
  selector: 'comp',
  template: `<div target>Target</div>`,
  directives: [Target]
})
export class Comp {}

@Component({
  selector: 'my-app',
  template: `<comp findTarget></comp>`,
  directives: [Comp, FindTarget]
})
export class App {}
```
plunker: http://plnkr.co/edit/mZdFvTVTFGO01DFnITZc?p=preview
I have 2 directives `target` and `findTarget` and I want to find if element with `findTagret` directive has a descendant with `target` directive. This works when both directives are in the same template:
```
<div findTarget><div target></div></div>
```
but doesn't work if they are in different components. 
Using ViewChild instead of ContentChild doesn't work in both cases.
Using Query doesn't work either.
Is this expected behaviour? If so, what is the proper way to do this?

**Comment by DzmitryShylovich** [comment]
According to the [docs](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#components-only) `ngAfterContentInit` is component only hook.

**Comment by vagarenko** [comment]
It is being called and I get `undefined` in console.
Also other docs https://angular.io/docs/ts/latest/api/core/index/ContentChild-var.html has:
```
@Directive({
  selector: 'someDir'
})
class SomeDir {
  @ContentChild(ChildDirective) contentChild;
  @ContentChild('container_ref') containerChild
  ngAfterContentInit() {
    // contentChild is set
    // containerChild is set
  }
}
```

**Comment by vicb** [comment]
It is the expected behavior, you can only query direct children. 

The rationale being that you might not know about inner component implementation and should not be affected by them.
