### ISSUE TITLE
(Bug)NgFor trackBy fails silently for undefined functions

### ISSUE THREAD

**Issue by sfabriece** [angular/angular#10123]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
trackBy attribute of *ngFor fails silently for a non valid function

**Expected/desired behavior**
an error indicating that the function is not defined

**Reproduction of the problem**
http://plnkr.co/edit/GXf8iIGfWBwNbNuigon8?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome XX] 
 
* **Language:** [TypeScript X.X]

**Comment by vicb** [comment]
fails silently ? 

Why should passing `undefined` be an error ? Wouldn't it mean that you only don't want to use it ?

**Comment by sfabriece** [comment]
How can one be sure that `trackBy` is being used? Let's say that you misspelled the function in html. I would expect to be notified that the function I'm using doesn't exist. 

Unless I have misunderstood the use of trackBy. 

Thanks

**Comment by vicb** [comment]
> Let's say that you misspelled the function in html. I would expect to be notified that the function I'm using doesn't exist.

JS is a dynamic language and a method can be added to the context at any time (this is probably more likely to happen in ES5 rather than TS). If we implement what you request, this use case would not be supported any more. I agree that this use case is probably something you should never do but we would deviate for JS behavior. WDYT ?

**Comment by kemsky** [comment]
So the same should apply to all functions including event handlers, but it does not and you got NPE.
