### ISSUE TITLE
Ability to run angular 2 without server

### ISSUE THREAD

**Issue by Rafi993** [angular/angular#10137]
**I'm submitting a ...**  
```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular 2 currently requires nodejs and it cannot be served without a server directly from cnd or aws s3 etc..

**Expected/desired behavior**
It would be good if angular js allowed to be used without a server directly. So that it can be served from aws s3 by directly clicking index.html so as to ease the deployment and reduce cost since allowing to be served from anywhere.

**What is the expected behavior?**
It would be good if angular js allowed to be used without a server directly. So that it can be served from aws s3 by directly clicking index.html so as to ease the deployment and reduce cost since allowing to be served from anywhere.

**What is the motivation / use case for changing the behavior?**
It will improve the ease of deployment of angular 2 and allow users to use static page hosting services to be used for angular 2 thus reducing the cost and increase its adoption for wide range of problems.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all ] 
 
* **Language:** [all]

**Comment by zoechi** [comment]
Angular2 doesn't need a node server. You might need to create a deployable.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by Rafi993** [comment]
sorry for raising it as feature request. So angular pages can be run just by opening index.html instead of node app.js ?

**Comment by zoechi** [comment]
I added a comment there.

**Comment by pkozlowski-opensource** [comment]
> Angular 2 currently requires nodejs and it cannot be served without a server directly from cnd or aws s3 etc..

This is simply not true. You can run Angular 2 application using any web / application server. _Some_ tools _might_ require node.js as a build platform, but this is all together different topic.

Closing as there is nothing to do for us here.

**Comment by Rafi993** [comment]
thank you @zoechi
