### ISSUE TITLE
Cannot compile RouterModule with compiler-cli

### ISSUE THREAD

**Issue by laco0416** [angular/angular#10132]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I try to compile the code below, an error occurs.

```ts
@AppModule({
    modules: [BrowserModule, RouterModule],
    providers: [
        ...provideRoutes(APP_ROUTES),
    ],
    precompile: [AppComponent, HeroDetailComponent]
})
export class MainModule {
    constructor(public appRef: ApplicationRef) {
        appRef.bootstrap(AppComponent)
    }
}
```

```
error: Error encountered resolving symbol values statically. Function calls are not supported. 
Consider replacing the function or lambda with a reference to an exported function (position 39:40 in the original .ts file), 
resolving symbol ROUTER_PROVIDERS in /Users/laco/Works/ng2-compiler-test2/node_modules/@angular/router/src/router_module.d.ts, 
resolving symbol RouterModule in /Users/laco/Works/ng2-compiler-test2/node_modules/@angular/router/src/router_module.d.ts, 
resolving symbol RouterModule in /Users/laco/Works/ng2-compiler-test2/node_modules/@angular/router/src/router_module.d.ts
```

The reason is [this line](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router_module.ts#L39):

```ts
 {provide: ActivatedRoute, useFactory: (r: Router) => r.routerState.root, deps: [Router]},
``` 

compiler-cli doesn't support unnamed functions. It should be written with an exported function as well as `Router` with `setupRouter`: 

```ts
{provide: UrlSerializer, useClass: DefaultUrlSerializer}, {
    provide: Router,
    useFactory: setupRouter,
    deps: [
      ApplicationRef, ComponentResolver, UrlSerializer, RouterOutletMap, Location, Injector,
      AppModuleFactoryLoader, ROUTES, ROUTER_CONFIGURATION
    ]
  },
```

**Expected/desired behavior**

That should be compiled well.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** *-builds (latest builds)
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [TypeScript 1.9.0-dev] 

cc/ @vsavkin

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/10284

**Comment by laco0416** [comment]
Thank you!

**Comment by laco0416** [comment]
@vsavkin after the above commit, another error is happening.

```
Error: Resolution of relative paths requires a containing file.
    at ReflectorHost.findDeclaration (/Users/laco/Works/ng2-compiler-test2/node_modules/@angular/compiler-cli/src/reflector_host.js:90:23)
    at StaticReflector.importUri (/Users/laco/Works/ng2-compiler-test2/node_modules/@angular/compiler-cli/src/static_reflector.js:44:38)
    at StaticAndDynamicReflectionCapabilities.importUri (/Users/laco/Works/ng2-compiler-test2/node_modules/@angular/compiler-cli/src/static_reflection_capabilities.js:41:111)
    at Reflector.importUri (/Users/laco/Works/ng2-compiler-test2/node_modules/@angular/core/src/reflection/reflector.js:167:90)
    at CompileTokenMetadata.Object.defineProperty.get [as assetCacheKey] (/Users/laco/Works/ng2-compiler-test2/node_modules/@angular/compiler/src/compile_metadata.js:436:60)
    at CompileTokenMetadata.equalsTo (/Users/laco/Works/ng2-compiler-test2/node_modules/@angular/compiler/src/compile_metadata.js:454:22)
    at /Users/laco/Works/ng2-compiler-test2/node_modules/@angular/compiler/src/metadata_resolver.js:418:31
    at Array.forEach (native)
    at CompileMetadataResolver.getProvidersMetadata (/Users/laco/Works/ng2-compiler-test2/node_modules/@angular/compiler/src/metadata_resolver.js:407:19)
    at CompileMetadataResolver.getAppModuleMetadata (/Users/laco/Works/ng2-compiler-test2/node_modules/@angular/compiler/src/metadata_resolver.js:212:58)
Compilation failed
```

this is caused by `provideRoutes` function and `ROUTES` token. `ROUTES` is an internal reference which isn't contained in index.ts

https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router_config_loader.ts#L20
https://github.com/angular/angular/blob/master/modules/%40angular/router/index.ts

Please fix this too! 

P.S. I think some router+compilei integration tests are needed...

**Comment by laco0416** [comment]
current my module: 

```ts
import {AppModule, ApplicationRef} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {FormsModule} from '@angular/forms';
import {RouterModule, provideRoutes} from '@angular/router';
import {COMMON_DIRECTIVES} from '@angular/common';

import {AppComponent} from './app.component';
import {HeroesComponent} from './heroes.component';
import {HeroDetailComponent} from './hero-detail.component';
import {appRoutes} from './app.routes';

@AppModule({
    modules: [
        BrowserModule,
        FormsModule,
        RouterModule
    ],
    providers: [
        ...provideRoutes(appRoutes)
    ],
    directives: [
        ...COMMON_DIRECTIVES,
    ],
    precompile: [
        AppComponent,
        HeroesComponent,
        HeroDetailComponent
    ]
})
export class MainModule {
    constructor(public appRef: ApplicationRef) {
        appRef.bootstrap(AppComponent)
    }
}
```

**Comment by laco0416** [comment]
Workaround is the following (use `ROUTES` directly) : 

```ts
import {AppModule, ApplicationRef} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {FormsModule} from '@angular/forms';
import {RouterModule, provideRoutes} from '@angular/router';
import {ROUTES} from '@angular/router/src/router_config_loader';
import {COMMON_DIRECTIVES} from '@angular/common';

import {AppComponent} from './app.component';
import {HeroesComponent} from './heroes.component';
import {HeroDetailComponent} from './hero-detail.component';
import {appRoutes} from './app.routes';

@AppModule({
    modules: [
        BrowserModule,
        FormsModule,
        RouterModule
    ],
    providers: [
        {provide: ROUTES, useValue: appRoutes }
    ],
    directives: [
        ...COMMON_DIRECTIVES,
    ],
    precompile: [
        AppComponent,
        HeroesComponent,
        HeroDetailComponent
    ]
})
export class MainModule {
    constructor(public appRef: ApplicationRef) {
        appRef.bootstrap(AppComponent)
    }
}
```

**Comment by laco0416** [comment]
I find another bug. A declaration of `RouterLinkWithHref` class doesn't have its own constructor. 

```ts
export declare class RouterLinkWithHref implements OnChanges, OnDestroy {
    private router;
    private route;
    private locationStrategy;
    target: string;
    private commands;
    queryParams: {
        [k: string]: any;
    };
    fragment: string;
    routerLinkOptions: {
        preserveQueryParams: boolean;
        preserveFragment: boolean;
    };
    preserveQueryParams: boolean;
    preserveFragment: boolean;
    private subscription;
    href: string;
    urlTree: UrlTree;
    routerLink: any[] | string;
    ngOnChanges(changes: {}): any;
    ngOnDestroy(): any;
    onClick(button: number, ctrlKey: boolean, metaKey: boolean): boolean;
    private updateTargetUrlAndHref();
}
```

This causes an error when I use `routerLink` in my component

```
// app.component.ngfactory.ts L89

this._RouterLinkWithHref_4_3 = new import10.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
```

```
Error: Error at /Users/laco/Works/ng2-compiler-test2/src/app.component.ngfactory.ts:89:36: Supplied parameters do not match any signature of call target.
```

This bug is in router_link.ts . The constructor is commented with `@internal`.
https://github.com/angular/angular/blob/master/modules/%40angular/router/src/directives/router_link.ts#L133-L135

**Comment by laco0416** [comment]
In addition, an error occurs at runtime.

![image](https://cloud.githubusercontent.com/assets/1529180/17127991/8bafbc7e-5344-11e6-9108-0b36267cb849.png)

`ANALYZE_FOR_PRECOMPILE` works well and `HeroesComponentNgFactory` is existing. but the router doesn't use it.

**Comment by KeatonTech** [comment]
I ran into this same issue. From what I gather, the precompiled pages end up in the AppComponent's instance of ComponentFactoryResolver (makes sense, since that's where the precompile attribute lives). Unfortunately, the Router is provided by the bootstrap function, so it uses the global ComponentFactoryResolver instead of the application one, and therefore has no reference to the precompiled pages.

I have not found a workaround yet although I assume there's some sort of injector hack to make it work.

As a solution, I'd recommend moving the responsibility of precompiling page components from the AppComponent to the RouterConfig. Honestly I'm not sure why it's not just automatic, it seems like any component passed directly into a route should get precompiled, no extra config necessary.

**Comment by SonakshiGupta24** [comment]
I have an app which uses AOT,lazyloading and webpack. I got the same error that 'RouterModule cannot be compiled'. As suggested by @laco0416 I have used appRoutes directly but it gave the error as "No Provider for Router" in the browser console. When I included "Router" in the providers array. With npm run webpack , it is throwing the error :  'Supplied parameters do not match any signature of call target.'' The line number in app.module.ngFactory.ts is
 `if ((this.__Router_29 == (null as any))) { (this.__Router_29 = new import17.Router()); }
    return this.__Router_29;`

The AppModule is as follows:
```
@NgModule({
    declarations: [AppComponent],
    imports: [BrowserModule,CommonModule],
    providers: [{provide: ROUTES, useValue: appRoutes},Router],
    bootstrap: [AppComponent],
    schemas:[
        CUSTOM_ELEMENTS_SCHEMA
    ]
})
export class AppModule {
}
```

The app.routing with Lazy-loaded modules is as follows:
```
export  function loadSales(){
        return require('es6-promise!../sales/sales.module')('SalesModule');
}
export function loadServices(){
        return require('es6-promise!../service/service.module')('ServiceModule');
}
export const appRoutes: Routes = [
        {path:'', redirectTo:'/sales', pathMatch:'full'},
        {path : 'sales',  loadChildren:loadSales},
        {path : 'service',  loadChildren:loadServices}
];
```

Angular2 Dependencies Version: 'github:angular/*-builds',
Webpack Version: 2.1.0-beta.24
Is there is any workaround for this issue?

**Comment by vicb** [comment]
Please do not comment on closed issue. Open a new issue for new problems. Thanks
