### ISSUE TITLE
router: should export `NavigationExtras` 

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10130]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
`import { NavigationExtras } from '@angular/router';` won't compile.

`NavigationExtras` is not exported in the barrel.

It is the second param of `Router.navigate` 
```
navigate(commands: any[], extras?: NavigationExtras): Promise<boolean>;
```
and therefore should be public so we can shape conforming objects in type-safe manner (e.g, when creating a mock router for testing).

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 (Candidate 16 July 2016)
 
* **Browser:** [all ] 
 
* **Language:** [all]

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/pull/10149
