### ISSUE TITLE
Required field validation working even after the value is entered

### ISSUE THREAD

**Issue by DeveBj** [angular/angular#10133]
Hello,

I have got the value from preTag and assigning that value to the text box, after the value is assigned to the text box also am getting the required error, if I press a space bar the error goes off what is the actual error can any body solve this

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

The question also doesn't provide enough information to provide any support. If you ask in the mentioned channels please provide more details (code that demonstrates what you try to accomplish)

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi !

**Comment by DeveBj** [comment]
@zoechi if you don't mind check this [link](http://stackoverflow.com/questions/38372856/angular-2-text-box-required-validation-message-still-showing-even-after-the-valu) for the detailed code and the explanations
