### ISSUE TITLE
DEVELOPER.md contains misinformation

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#1013]
- [x] the dart dependencies are not required in order to build Angular 2 (however we currently do require dart dependencies to run tests, see #1012)
- [x] instructions state that either dev or stable version can be downloaded from the archive but that's not currently true since no stable dart version is supported
- [ ] `npm install -g gulp` - we should really encourage people to install `gulp-cli` which doesn't suffer the problems caused by global dependencies
- [ ] `npm install -g protractor` - @juliemr can you please confirm that protractor really can't run in a local mode via a global launcher like gulp-cli or karma work? If it can't we should fix it.
- [ ] `you might need to prefix this command with sudo` - installing npm packages with sudo is dangerous and strongly discouraged. people should use `nvm` or other ways of installing node and npm that don't require `sudo`

**Comment by IgorMinar** [comment]
we should also simplify the dart installation instruction and just tell people how to install dart via brew on mac or point mac users down that path as the recommended option.

**Comment by gautelo** [comment]
Also needs a better description for us heathens, erm.. I mean us Windows users. Environment variable references and paths look different to us and brew is OS X only as I understand it.

I had trouble with protractor, until I looked up [Installing Protractor](http://seleniumeasy.com/protractor-angularjs-tutorials/install-protractor). Either something like that should be referenced, or we should be told that installing protractor doesn't install an up-to-date webdriver, and so we must run `webdriver-manager update`.

**Comment by mhevery** [comment]
@IgorMinar is this still relevant or can this be closed?

**Comment by kylecordes** [comment]
I think this issue is still relevant - it leads a wayward developer to install Dart needlessly.

**Comment by alexbecker** [comment]
Almost every instruction involving `gulp` is broken as of https://github.com/angular/angular/commit/2bcdec5aaf96e29c33ade8c6f1592d6a60a1a49a, which renamed `gulpfile.js` to `gulpfile.js.old`. Was this intentional?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

We are in the process of redoing our built system.
