### ISSUE TITLE
*ngIf is not working with ! sign

### ISSUE THREAD

**Issue by rashfmnb** [angular/angular#10138]
I am using Angular JS 2 RC 4 for the small project i am facing a problem here i have with *ngIf is not working with ! operator

**HTML**

```
      <ul class="nav navbar-nav">
        <li><a [routerLink]="['/Home']">Home</a>
        <span style="color:red">isAdmin: {{auth.isAdmin}}</span><<br/>
        <span style="color:red">isLoggedIn: {{auth.isLoggedIn}}</span><<br/>
        <span style="color:red">!isAdmin && isLoggedIn: {{!auth.isAdmin && auth.isLoggedIn}}</span><<br/>
        <span style="color:red">isAdmin && isLoggedIn: {{auth.isAdmin && auth.isLoggedIn}}</span><<br/>
        </li>

        <li *ngIf="auth.isAdmin && auth.isLoggedIn"><a [routerLink]="['/Category']">Category</a></li>
        <li *ngIf="auth.isAdmin && auth.isLoggedIn"><a [routerLink]="['/Products']">Product</a></li>
        <li *ngIf="!auth.isAdmin && auth.isLoggedIn"><a [routerLink]="['/BuyProduct']">Buy Products</a></li>
        <li *ngIf="!auth.isAdmin && auth.isLoggedIn"><a [routerLink]="['/Cart']"><i class="fa fa-shopping-cart"></i><span class="badge" >11</span></a></li>
        <!--<li *ngf="isLoggedIn"><a [routerLink]="['/Folder']"><i class="fa fa-shopping-cart"></i><span class="badge" >Folder</span></a></li>-->
      </ul>
```

here is the screen shot how it is displaying on screen http://i.stack.imgur.com/snkP6.png

**Comment by pkozlowski-opensource** [comment]
I'm pretty sure that this is some kind of error on the user side. Please provide a _minimal_ plunker with a reproduction scenario (as requested in the issue template!) - otherwise it is not actionable and will be closed.

**Comment by DzmitryShylovich** [comment]
what router version do u use? there was an issue with `ngIf` and `routerLink` on the same element but it should be fixed in v3.0.0-beta.2

**Comment by rashfmnb** [comment]
same issue even after changing it to    "@angular/router": "3.0.0-beta.2" from one

**Comment by rashfmnb** [comment]
@pkozlowski-opensource it is working well with plunkr but not on my machine i also clear the cache but nothing helps here is the plunker but it is working fine over there https://plnkr.co/edit/3haJZS?p=preview

**Comment by pkozlowski-opensource** [comment]
> it is working well with plunkr but not on my machine

Then I'm afraid that you will have to dig into the setup you've got on your side. We can't debug your project and till we've got a reproduce scenario in which we can see a bug there is not much we can do.

Closing for now, feel free to re-open when you've got a minimal plunk demonstrating the problem.

**Comment by rashfmnb** [comment]
can i zip it and send it to you
