### ISSUE TITLE
ngModelGroup doesn't work with ng-container

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#10136]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The following code causes an error: 

``` ts
      <form #f="ngForm" (ngSubmit)="submit(f)">
        Foo: <input name="foo" ngModel><br>
        <ng-container ngModelGroup="group">
          Bar: <input name="bar" ngModel><br>
        </ng-container>
        <button type="submit">Submit</button>
      </form>
```

```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./App class App - inline template:7:8
ORIGINAL EXCEPTION: TypeError: element.setAttribute is not a function
```

`ngModelGroup` cannot be used with `ng-container`. 

**Expected/desired behavior**

`ngModelGroup` works well with `ng-container`

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/tOqcPZuspsV9a7ZB62WH?p=preview

**What is the expected behavior?**

Errors in the console

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by zoechi** [comment]
The `<ng-container>` isn't actually added to the DOM, why would you want to add `ngModelGroup` to it?

**Comment by laco0416** [comment]
The form's value structure is not matching its DOM structure always by some reasons (CSS styling, Avoiding div-nesting-hell or something).
In similar case, I want to use `ngSwitch` with `ng-container` and it works well.

**Comment by zoechi** [comment]
@laco0416 I don't understand your last comment.

**Comment by DzmitryShylovich** [comment]
The issue with `NgControlStatusGroup` and virtual tags

**Comment by AndrewKushnir** [comment]
It looks this works with the most recent version of Angular, so I'm closing this ticket. Thank you.
