### ISSUE TITLE
Internet Explorer 11 Datepipe

### ISSUE THREAD

**Issue by yusijs** [angular/angular#10147]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Submitting valid dates to the DatePipe will return an exception:

ORIGINAL EXCEPTION: Invalid argument '2016-07-19 16:00:00' for pipe 'function DatePipe() {'

**Expected/desired behavior**
Datepipe working as expected

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Created a plunk, but it's not working in IE for me (SystemJS issue)
http://plnkr.co/edit/BrwlpKZ0wc4m8kYsUUOn?p=preview

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** IE 11 
 
* **Language:** TypeScript X.X

**Comment by laskoviymishka** [comment]
IE :sob: 
I'll take a look.

**Comment by yusijs** [comment]
Cool beans. And yeah, I know, the horrors. Most end users at work are forced to use it. :<

**Comment by laskoviymishka** [comment]
@yusijs amine, but most probably this issue will stack on chakra side :cry: 
Does this reproduced in Edge?

**Comment by yusijs** [comment]
Works fine in edge as far as I could tell. My app crashed with a random af error in edge, so wasnt able to test outside of the plunk.

**Comment by laskoviymishka** [comment]
That strange, they have same engine inside.
Chackra code is not quite human readable :sob: , so i can just sit and wait when they fix issues.

**Comment by laskoviymishka** [comment]
Yep, it not reproduced in Edge,
in the end it just check does result of this `new Date('2016-07-19 16:00:00')` is valid date. Only in IE it not valid.

**Comment by yusijs** [comment]
Silly IE..

**Comment by kemsky** [comment]
using `new Date(...)` may lead to unpredictable results: http://dygraphs.com/date-formats.html

**Comment by yusijs** [comment]
new Date(...) on those strings work fine I think.

**Comment by ExFlo** [comment]
Internally with String input like your case we are directly using new Date(String) and IE11 does follow the specs here 
https://www.w3.org/TR/NOTE-datetime
http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15
so '2016-07-19 16:00:00' is not a valid date (but '2016-07-19T16:00:00' is!)
Chrome or FF are more flexible with the inputString format.
Not sure we want to touch the input in the angular pipe.
I suggest you to build a custom filter to normalize your date input if you want to support IE and to close this issue.

**Comment by gfrSE** [comment]
What about this snippet:

```javascript

if (new RegExp(/\d{1,4}-\d{1,2}-\d{1,2}[T ]\d{1,2}:\d{1,2}:\d{1,2}/).test(__dateString__)) {
   var dt = __dateString__.split(/[- :.TZ]/);
   // TODO: keep UTC in mind!
   return new Date(+dt[0], +dt[1]-1, +dt[2], +dt[3], +dt[4], +dt[5]);
}
return new Date(__dateString__);

```

Wether in your filter or angular..

**Comment by mlaval** [comment]
`new Date('2016-07-19 16:00:00')` also fails in latest Safari.

As shown by http://dygraphs.com/date-formats.html , it is better

**Comment by yusijs** [comment]
Alright.

P.s
Screw ie.

**Comment by milleraundra** [comment]
I ran into this issue again recently. The best solution for me was to just use the Moment.js library.

**Comment by yusijs** [comment]
We decided to use date-fns (moment adds like 350kb to the bundle). Generally we only use 2-3 formats, and no IE issues this far :)

**Comment by ocombe** [comment]
You could also update to Angular 5, the date pipe has been completely rewritten and it doesn't use intl anymore
