### ISSUE TITLE
<div [innerHTML]=.... not working with iframe html

### ISSUE THREAD

**Issue by tchoulihan** [angular/angular#10145]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
An empty div where the HTML for an iframe should be injected. 

**Expected/desired behavior**

It should display the iframe in the innerHTML. 

Example and plunkr demonstrating it below: 
```ts
@Component({
  selector: 'my-app',
  providers: [],
  template: `
    <div>
      <h2>Hello {{name}}</h2>
      <div [innerHTML]="html"></div>
    </div>
  `,
  directives: []
})
export class App {
  private html: string = '<iframe src=\"https://www.youtube.com/embed/2a4Uxdy9TQY\"></iframe>';
  constructor() {
    this.name = 'Angular2 (Release Candidate!)'
  }
  
}
```

**Reproduction of the problem**
[plunkr demonstrating problem](http://plnkr.co/edit/3zgLWDcgKQAkBXUDyTBc).

**What is the expected behavior?**
It should load up an iframe into the innerHTML. 

**What is the motivation / use case for changing the behavior?**
I'm trying to convert youtube URLs to iframe embeds dynamically. 

**Please tell us about your environment:**

**Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome and FF
 
* **Language:** [Typescript]

**Comment by zoechi** [comment]
See the console output

> WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).

https://angular.io/docs/js/latest/api/platform-browser/index/DomSanitizationService-class.html

**Comment by tchoulihan** [comment]
Okay, so how do I get the component to trust anything, or certain domains, etc.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by LukeNZ** [comment]
1. Inject `DomSanitizationService` into your constructor
2. Wrap whatever you were previously returning inside the necessary method off that class:

```
return this.sanitizer.bypassSecurityTrustHtml(this.html);
```

Done.

**Comment by tchoulihan** [comment]
Just tried this, it still didn't work. Here's the [plunkr](http://plnkr.co/edit/3zgLWDcgKQAkBXUDyTBc?p=preview). This likely is a bug.

**Comment by vicb** [comment]
Check the console log to find one of your errors.

http://plnkr.co/edit/gQfyf7

**Comment by tchoulihan** [comment]
Ah, figured it out, sorry about that. Thanks.

**Comment by sinthu225** [comment]
What was your solution?
