### ISSUE TITLE
while using [routerLinkActiveOptions]="{exact: true}", routerLink still sets an active class initially, even when it's not an exact match

### ISSUE THREAD

**Issue by MrCroft** [angular/angular#10141]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
Given (in `app.routes.ts`):
```
export const APP_ROUTES: RouterConfig = [
    { path: '', component: HomeComponent },
    { path: 'about', component: AboutComponent }
];
```
And (in a template):
```
<a [routerLink]="['/']" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Home</a>
<a [routerLink]="['/about']" routerLinkActive="active">About</a>
```
Then some css to easily notice the issue:
```
a { display: inline-block; padding: 5px 10px; color: #000; transition: 1s all; text-decoration: none; }
a.active { color: #fff; background-color: green; }
```

If the user inputs "http://my-domain/#/about" so they go straight to the about route, as soon as the application bootstraps, you can notice the "Home" link being active for a blink of an eye, before the router removes the "active" class from the "Home" link and puts it on the "About" link.

**Expected/desired behavior**
The "Home" link for the "/" route should not have the active class at all, not even for a fraction of a second, if we load the app on a different route (ie. by typing in the url directly and hiting enter).

**Reproduction of the problem**
https://plnkr.co/edit/CzJRA1tBdTyV0t6doVuN?p=preview - open in popup window. Click the "About" link to navigate to the about route and then hit F5 to reload the page on the about route. Notice that initially, when the app bootstraps, the "Home" link has the active class on it. And then it is taken off and placed on the "About" link.
P.S. Went with HashLocationStrategy because... plunkr. But behavior is the same, doesn't matter if it's HTML5 or Hash, of course.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Router version:** 3.0.0-beta.2

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/pull/10193
