### ISSUE TITLE
Angular 2 @output property does not bubble up the event to the Angular 1 parent.

### ISSUE THREAD

**Issue by TechJana** [angular/angular#10140]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have an Angular2 component which I am downgrading to use in an Angular 1 app. Using the @output property inside my app component class does not seem to bubble up the event to my Angular 1 app in which my app component is downgraded and used.
Ex:

```
@ component{
-------------------
-------------------
}
export class AppComponent {
@output() back:EventEmitter<any> = new EventEmitter();   //THIS DOES NOT WORK
------------------
goBack() {
        console.log("trying to go back...");
        this.back.emit();
    }
}
```

In my app, I downgrade this component like the below.

```
------------------------
app
    .controller('MyController', MyController)
    .directive('test', adapter.downgradeNg2Component(AppComponent))
-----------------------
```

My HTML and Controller look like this.

```
-------------------------------------------
<div ng-controller="MyController as vm">
    <test (back)="vm.goBack($event)">
    </test>
</div>
---------------------------------------------
```

```
export class MyContoller{
    ............................
    goBack($event){
        console.log("This is the event from Downgraded Angular 2 component."); //THIS IS NOT WORKING
    }
}
----------------------------------------------
```

**Interestingly when I use the outputs array inside the component selector instead of the @output property, it works.**

```
@Component{
outputs: ['back'] // THIS WORKS
-------------------
}
export class AppComponent {
///////@Output() back:EventEmitter<any> = new EventEmitter();  **//This event is not captured**
back:EventEmitter<any> = new EventEmitter();
------------------
goBack() {
        console.log("trying to go back...");
        this.back.emit();
    }
}
```

**Expected/desired behavior**

I would expect the @output property to behave the same way the outputs array inside the @Component selector does while bubbling up the event.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:** Chrome 51.0.2704.84 
- **Language:**TypeScript

**Comment by zoechi** [comment]
I don't know about ngUpgrade/ngDowngrade but events from `@Outputs()` are not supposed to bubble - at least in plain Angular2.

**Comment by vicb** [comment]
Please provide a plunker with a repro.

**Comment by dlombardi** [comment]
+1 this is a problem I'm encountering as well

**Comment by mhevery** [comment]
Hi @hannahhoward do you think you could have a look at this?

**Comment by vicb** [comment]
closing as we don't have a repro available

**Comment by epelc** [comment]
I also ran into this with `2.3.0` and sadly had to add a watcher on the ng1 side to detect the changes.

@vicb is there a plunker with @angular/upgrade setup? I'd be happy to make a repro if I can get a template to start with.

It might also be nice having a link to one documented for any other @angular/upgrade related issues.

**Comment by epelc** [comment]
I think this has to do with capitalization of the output events. I got mine working when I renamed to an all lower case name.

PS I also checked that it was coming over the network with proper casing and it is.

**Comment by HerrDerb** [comment]
I just faced that problem right now. The work around with the `outputs` array solves it. Altought now  I need to specify a special typscript exclusion and need to mark the code for refactoring after the migration is complete.
