### ISSUE TITLE
Router: Query parameters should not persist to links after page refresh

### ISSUE THREAD

**Issue by pleerock** [angular/angular#10142]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Query parameters are working globally between components what is expected. However if I navigate between different routes (lets say from /questions?a=1 to /posts; question route or question route's children set query parameter), they are not persisted what is expected. But if I navigate to  /questions?a=1 and refresh a page, it will generate /post?a=1 for posts link too.

**Expected/desired behavior**

After page refresh routerLink should not generate query parameters for different routes (e.g. /post?a=1). If I am wrong and this is expected behaviour (which I afraid of), then looks like routerLink does not work correctly and does not updat its links with query parameters that were changed

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8]

**Comment by slubowsky** [comment]
Yes. Current design very difficult to work with. Different results if navigate to url or if refresh url. Makes it required to handle this manually on every single routerlink or behavior will inevitably be incorrect one way or the other. See https://github.com/angular/angular/issues/9924
