### ISSUE TITLE
For RC5, need to note breaking changes for testing ngModel 

### ISSUE THREAD

**Issue by juliemr** [angular/angular#10148]
This is a note for whoever's preparing the Changelog for RC5 :)

With the split into new forms, `ngModel` is now always asynchronous when updating. This means that in tests, instead of calling `ComponentFixture.detectChanges`, you'll need to use `ComponentFixture.whenStable`, which is asynchronous.

Before:

``` js
    let fixture = builder.createSync(InputComp);
    fixture.detectChanges();

    let inputBox = <HTMLInputElement> fixture.debugElement.query(By.css('input')).nativeElement;
    expect(inputBox.value).toEqual('Original Name');
```

After:

``` js
    let fixture = builder.createSync(InputComp);
    fixture.whenStable().then(() => {

      let inputBox = <HTMLInputElement> fixture.debugElement.query(By.css('input')).nativeElement;
      expect(inputBox.value).toEqual('Original Name');
   });
```

**Comment by vikerman** [comment]
Assigned Stephen who is the changelog master :) and Robert who is the current caretaker

**Comment by juliemr** [comment]
It's more complex than that actually - we need to do both `detectChanges` AND `whenStable`. And `autoDetectChanges` isn't doing the right thing. So after would be

```js
    let fixture = builder.createSync(InputComp);
    fixture.detectChanges();
    fixture.whenStable().then(() => {

      let inputBox = <HTMLInputElement> fixture.debugElement.query(By.css('input')).nativeElement;
      expect(inputBox.value).toEqual('Original Name');
   });
```

To go the other way, from a DOM change to the data in the component, we'll need to trigger an event with `inputBox.dispatchEvent(new Event('input'))`

**Comment by choeller** [comment]
@juliemr Is this supposed to be the final solution? To be honest this `whenStable`, `autoDetectChanges` and `detectChanges` hell is super frustrating. At the moment I find myself randomly adding all that stuff + some `tick` calls until at some point the test passes. :confused:

**Comment by juliemr** [comment]
@choeller we're discussing and brainstorming :) I get the frustration.

**Comment by IgorMinar** [comment]
docs added via f444c11d218d26ac817d5f3b12e19c6b4b8d2390

**Comment by tycho01** [comment]
So uh, to reduce noise from this change, basically `await fixture.whenStable();` huh. :)

**Comment by forforeach** [comment]
I think this worth to be described in official documentation. I didn't find anything related to this except the changelog.

**Comment by DzmitryShylovich** [comment]
@IgorMinar I think it's outdated and can be closed

**Comment by jsgoupil** [comment]
@DzmitryShylovich No I don't see this as outdated.

http://stackoverflow.com/questions/41274000/angular-2-unit-test-must-call-whenstable-multiple-times-when-nesting-ngmodel-ele

**Comment by vikerman** [comment]
A clarifying example around ngModel and async issues would be useful. 

@kyliau - Please add this as part of #12409
