### ISSUE TITLE
(change) can not work properly

### ISSUE THREAD

**Issue by felix307253927** [angular/angular#10156]
![image](https://cloud.githubusercontent.com/assets/9459249/16941958/dd850bf0-4dc5-11e6-8837-bbf56b575de8.png)
Every time I choose a value through (change) to get the value of the last selected, with [(ngModel)] to get the value is correct. How can I get my chosen value in (change) event?

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chromium 51.0.2704.79] 
 
* **Language:** [TypeScript 1.8 ]

**Comment by laserfists** [comment]
I think you want something like: `(change)="onCityChange($event)"` - in your example, `agent.province` will not have been updated yet when `#onCityChange()` is called.

**Comment by zoechi** [comment]
You can use `(ngModelChange)="onCiteyChange($event)"`

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by felix307253927** [comment]
ok thanks
