### ISSUE TITLE
testing(ComponentFixture):  certain methods should support chaining

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10152]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request (nice to have)
[ ] support request
```

_This is a nice-to-have request. Certainly not a priority._

**Current behavior**

These methods return void

```
    detectChanges(checkNoChanges?: boolean): void;
    checkNoChanges(): void;
    autoDetectChanges(autoDetect?: boolean): void;
```

That means we can't chain them. We have to call them on separate lines like this:

```
let fixture = builder.createSync(InputComp);
fixture.autoDetectChanges();
```

**Expected/desired behavior**
If the methods returned the fixture ...

```
    detectChanges(checkNoChanges?: boolean): ComponentFixture<T>;
    checkNoChanges(): ComponentFixture<T>;
    autoDetectChanges(autoDetect?: boolean): ComponentFixture<T>;
```

we could chain them like this:

```
let fixture = builder.createSync(InputComp).autoDetectChanges();
```
- **Angular version:** 2.0.0-rc.5 candidate
- **Browser:** [all  ] 
- **Language:** [all ]

**Comment by vikerman** [comment]
Obsolete. We should have better wrappers for the ComponentFixture methods.
