### ISSUE TITLE
how to mock providers specified in @component meta data in  angular-2.0.0-rc-4

### ISSUE THREAD

**Issue by ramana-chavakula** [angular/angular#10158]
since, overrideProviders is not supported in angular-2.0.0-rc-4.

i tried using
 `beforeEach(() => {
    addProviders([
      TestComponentBuilder,
      FeedsListComponent,
      {provide: FeedsService, useClass: MockFeedsService}
    ]);
  });`
 i am able to mock the service if it was provided at bootstrap phase.
but if it's provided @componet level like below
`
@component({
...
providers: ['FeedsService']
})
class FeedsListComponent {
}
`
even if i used provide it's not taking the mockedService. So, is there any alternative way to mock the services specified in @component meta data instead of overrideProviders

**Comment by tbosch** [comment]
Please use the new `TestBed.overrideComponent` method.
