### ISSUE TITLE
Validator.pattern should accept a Regular Expression instead of a String

### ISSUE THREAD

**Issue by batchu** [angular/angular#10150]
**I'm submitting a ...**  (check one with "x")
```
[* ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Here's how I'm building a form input field
Regular expression pattern:
 regexPattern:string  is "/^\d{2}\/\d{2}\/\d{4}$/"

group[question.key] = ['', Validators.compose([Validators.required,Validators.pattern(regexPattern)])];
FormBuilder.group(group)

During Debugging I see:
regexPattern : "/^d{2}/d{2}/d{4}$/"
{ "pattern": { "requiredPattern": "^/^d{2}/d{2}/d{4}$/$", "actualValue": "01/01/2001" } }

**Expected/desired behavior**
As you can see the requiredPattern adds an extra ^ at the beginning and a $ at the end. Validators.pattern(String) should accept a Regexp not a String. The regexPattern set was "/^\d{2}\/\d{2}\/\d{4}$/" but as you can see it's value while debugging is obvsiously requiredPattern": "^/^d{2}/d{2}/d{4}$/$"

Validators.patterns(String) should instead accept a regular expression literal Validators.pattern(RegExp). It should have  the same input signature as str.match(regexp) in javascript https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [TypeScript X.X]

**Comment by istiti** [comment]
Is this normal when I use my regex in html attribute pattern="" it works and when I use in `Validators.pattern("https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)")`
this is alway INVALID ?

**Comment by zoechi** [comment]
@istiti you already answered yourself in #11159

**Comment by balteo** [comment]
What is the status of this issue? It would be nice to be able to accept a regex instead of a string...
