### ISSUE TITLE
touched/untouched not updating in custom input component

### ISSUE THREAD

**Issue by sharpmachine** [angular/angular#10151]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
untouched/touched properties do not update, but ng-touched class is being added properly, but pristine/dirty and validators do.

**Expected/desired behavior**
I would expect untouched/touched to updated on blur, just like pristine/dirty and validators are.

**Reproduction of the problem**
https://plnkr.co/edit/O9KWzwhjvySnXd7vyo71?

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:**
Chrome 51
 
* **Language:**
Typescript

**Comment by zoechi** [comment]
You need to call `onTouched()` (`this._onTouchedCallback`) from inside your component when you want the controls status set to touched. Same for `this._onChangeCallback`

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by sharpmachine** [comment]
Sorry @zoechi I edited the Plunker after you looked it. I added `(blur)="onTouched($event)"` to the input. But it still looks a bug to me because touched/untouched state is meant to update on blur. If I just click into the field and then off the field, it updated, however if I actually type something into the field, then click off, the touched/untouched state does not update.

https://plnkr.co/edit/O9KWzwhjvySnXd7vyo71

**Comment by zoechi** [comment]
This is because 

`<p *ngIf="control.errors.required` 

throws an exception and then the blur handler doesn't work anymore

If you change it to 
`<p *ngIf="control?.errors.required` all is working as desired.

Please always check the browser console...

**Comment by sharpmachine** [comment]
I had to change it to `<p *ngIf="control?.errors.required`

Thanks.

**Comment by yash5862** [comment]
What if i want to check if control is touched or not in this..?
