### ISSUE TITLE
*for iterations in <content></content>

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [angular/angular#10155]
As far as I remember, Angular 2 this was a problem in iterations in `<content>` tag, as things stand now? If you like, I advise you how to implement this. I can tell how I did it in my framework.

I recorded a video for you (4 min)
https://www.youtube.com/watch?v=tmKMAfzR8Ow

Solution: When rendering shadow dom, I do not move a virtual DOM tree nodes!

Physically, even in the virtual dom, the elements are in place. In this <content> element does not move anything anywhere, and only serves to mark the renderer that when rendering nodes projection  in place `<content>` tag.

This is npm of my framework https://www.npmjs.com/package/ui-js
This is GitHum of my framework https://github.com/uMaxmaxmaximus/ui-js/tree/master/modules/ui-js

I understand, I went into the enemy camp, to its competitors. But I am ready to share with you the experience).

**Comment by vicb** [comment]
We don't have any enemy but friends only... Good luck with you framework

**Comment by uMaxmaxmaximus** [comment]
@vicb I asked you! Repeat?
