### ISSUE TITLE
form  radio/checkbox default checked demo?

### ISSUE THREAD

**Issue by ruanzy** [angular/angular#10153]
form  radio/checkbox default checked demo?

<form class="form-horizontal" role="form" [ngFormModel]="form">
<div class="form-group">
		<label for="start" class="col-sm-3 control-label">started</label>
		<div class="col-sm-8">
			<label class="radio-inline"> <input type="radio"
				name="start" value="1" ngControl="start">yes
			</label> <label class="radio-inline"> <input type="radio"
				name="start" value="0" ngControl="start">no
			</label>
		</div>
	</div>
</form>

`export class MyComponent {
	name: Control;
        ...
 	start: Control;
 	form: ControlGroup;
 	
	constructor(private builder:FormBuilder) {
		this.name = new Control('monitor1', Validators.required);
		...
	   	this.start = new Control("1", Validators.required);
	   	this.form = builder.group({
			name: this.name,
                        ...
	     	        start: this.start
	   	});
    }
	
	ngOnInit(){
		
	}
}`

but the radio unchecked.

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
