### ISSUE TITLE
Testing: Global keyboard event listeners registered via HostListener decorator are never removed

### ISSUE THREAD

**Issue by mkemmerling** [angular/angular#10161]
**I'm submitting a**
```
[x] bug report
```

**Current behavior**

When testing a component which registers a keyboard event listener like this:

```
@HostListener('document:keypress', ['$event'])
onKeyPress(event: KeyboardEvent) {
  console.log("Pressed key", event.keyCode);
}
```

the listener is never removed.

When a test dispatches a keyboard event it is received by n + 1 event listeners where n is the
number of tests that created the component before the actual test.

This happens only in tests where the component is created with the TestComponentBuilder.

**Reproduction of the problem**

See http://plnkr.co/edit/SKiOYqsezY2xyhi0m5Wz?p=preview

The plunker defines three tests each of which creates a component with a keyboard event listener
that outputs a console message. The tests test actually nothing, but the third test dispatches a
keyboard event. Open the console to verify that the event is processed three times. If the app
itself is also loaded (uncomment the two lines in index.html) it is even processed four times.

**What is the expected behavior?**

Global keyboard events registered via HostListener decorator should be removed in tests that create
the component with the TestComponentBuilder.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all when running tests
 
* **Language:** TypeScript 1.8.10

**Comment by tbosch** [comment]
`TestComponentBuilder` was removed in Angular 2 final, but the issue is actually independent of `TestComponentBuilder`.

**Comment by mkemmerling** [comment]
Thank you Tobias for looking into this. Since the old plunker doesn't work anymore I updated it to Angular 2 final:

http://plnkr.co/edit/wFsdmn0m6GMxcvjkgei5?p=preview

To my astonishment--and pleasure--the problem no longer occurs. The global keyboard event in one test is no longer handled by the two other ones.

I don't know if the problem vanished by replacing `TestComponentBuilder` with `TestBed` based component creation or for some other reason. But since it is gone, I close the issue.
