### ISSUE TITLE
Unhelpful missing route component declaration error message

### ISSUE THREAD

**Issue by FredLoney** [angular/angular#10168]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

A route defined without a component declaration results in the error message:

`TypeError: Cannot read property 'annotations' of undefined`

**Reproduction of the problem**

Make a route but omit the component.

**What is the expected behavior?**

This error message crops up in different situations, and is difficult to trace. In my case, it results from the router resolve.ts code:

_ => resolver.resolveComponent(<any>node.value.component).then(factory => { node.value._resolvedComponentFactory = factory;

which cascades as an error in a wholly different call stack.

The assignment above should be guarded by checking for a factory value and issuing the appropriate error. In addition, the route should be validated beforehand. Furthermore, there should be a separate task to ensure that the forthcoming route documentation specifically states what is required.

**What is the motivation / use case for changing the behavior?**

This issue is symptomatic of a pervasive cavalier disregard for defensive programming in the Angular development process. I appreciate how developers under pressure let issues like this slide, but technical leads and QA should know better. Code review, anyone? Unfortunately, defensive programming must be integral to the development process and is difficult to address after initial functional goals are achieved.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2, **router version:** 3.0.0-alpha.3
 
* **Browser:** all
 
* **Language:** all

**Comment by ericmartinezr** [comment]
I reported this issue a time ago (https://github.com/angular/angular/issues/9414) buy I got an answer not related at all. I hope you get a real solution.

**Comment by FredLoney** [comment]
The other infamous error in the same vein is `Cannot read property 'isSkipSelf' of null`. This masks other unguarded assignment errors.

**Comment by ericmartinezr** [comment]
@FredLoney that was fixed already, you should be on ng2 rc4 and routet beta 2.

**Comment by FredLoney** [comment]
Nice, thanks for the update.

**Comment by vsavkin** [comment]
Dup of #9414.

Please see my last comment there:
https://github.com/angular/angular/issues/9414

The error should no longer present in master. If you can still see it in master (you can get the latest build of the router here https://github.com/angular/router-builds), please provide a plunker reproducing the issue.

Closing this issue.
