### ISSUE TITLE
Custom Validator / TypeScript 2.0 with strictNullChecks Compilation Error

### ISSUE THREAD

**Issue by KaneFreeman** [angular/angular#10166]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When adding a custom validator to a FormControl and the TypeScript 2.0 strictNullChecks compiler option, the following error occurs:

```
Argument of type '(c: FormControl) => { customValidation: boolean; } | null' is not assignable to parameter of type 'ValidatorFn | ValidatorFn[] | undefined'.
```

When trying to enforce the expected return type of { [key: string]: boolean; } upon the validation function, the above error goes away, but a new one appears:

```
Type '{ customValidation: boolean; } | null' is not assignable to type '{ [key: string]: boolean; }'.
```

**Expected/desired behavior**
As custom validators require you return null when valid, the ValidatorFN and Validator interface definitions need to allow for null in the return type.

```
export interface Validator {
    validate(c: AbstractControl): {
        [key: string]: any;
    } | null;
}
```

```
export interface ValidatorFn {
    (c: AbstractControl): {
        [key: string]: any;
    } | null;
}
```

**Reproduction of the problem**
Create a new FormControl with a custom validator or set the validators for a FormControl.
```
this.control = new FormControl('', this.createCustomValidator());
this.control.setValidators(this.createCustomValidator());

createValidateSite() {
    return function(c: FormControl) {
        let obj = c.value;

        return obj.id === -1 ? {
            customValidation: false
        }: null;
    }
}
```

Create a directive that implements the Validator class.
```
import { Directive, forwardRef } from '@angular/core';
import { NG_VALIDATORS, Validator, FormControl } from '@angular/forms';

export const ID_VALIDATOR: any = {
    provide: NG_VALIDATORS,
    useExisting: forwardRef(() => IdValidatorDirective),
    multi: true
};

@Directive({
    selector: '[validateId][formControlName],[validateId][formControl],[validateId][ngModel]',
    providers: [ID_VALIDATOR]
})
export class IdValidatorDirective implements Validator {
    validate(c: FormControl): { [key: string]: boolean; } | null {
        let isValid = c.value && c.value.id && c.value.id > 0;

        return isValid ? null : {
            validId: false
        };
    }
}
```

**What is the expected behavior?**
As custom validators require you return null when valid, the ValidatorFN and Validator interface definitions need to allow for null in the return type.

**What is the motivation / use case for changing the behavior?**
This is needed to have custom validators and have the strictNullChecks flag on for the TypeScript compiler.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome 51
 
* **Language:** TypeScript 2.0

**Comment by KaneFreeman** [comment]
As a temporary work around I have manually modified the validators.d.ts file in the @angular/forms module to what is mentioned in the Expected/desired behavior section

```
export interface Validator {
    validate(c: AbstractControl): {
        [key: string]: any;
    } | null;
}
```

```
export interface ValidatorFn {
    (c: AbstractControl): {
        [key: string]: any;
    } | null;
}
```

**Comment by vicb** [comment]
will fix when TS2.0 is released

**Comment by GiuseppePiscopo** [comment]
Has this been fixed as of today? Thanks

**Comment by DzmitryShylovich** [comment]
nope. angular will support ts 2.0+ officially in 4.0 version
