### ISSUE TITLE
NgModelGroup doesn't bring NgControlStatus

### ISSUE THREAD

**Issue by davidTurczi** [angular/angular#10162]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
NgControlStatus' `selector: '[formControlName],[ngModel],[formControl]'`
Therefore if I have a fieldset/div, with a NgModelGroup and a custom (group) validator, which goes invalid, nothing gets a `ng-invalid` class. 

**Expected/desired behavior**
Neither of the grouped controls are technically invalid, so it should be on the group, and let the user decide through css. (whether to write `fieldset.ng-invalid` or `fieldset.ng-invalid *`....) 

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**
Put the ng-invalid on the model group

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [**all** | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | **TypeScript 1.8** | ES6/7 | ES5 | Dart] 

(Sorry, my first ever raised issue, please don't be harsh :) also not sure whether it's by design - therefore it should be a feature request - or by omission - in which case it's a bug).

**Comment by kara** [comment]
Thanks for the issue.  This is something we've been planning to add :)  Closed by https://github.com/angular/angular/pull/10667
