### ISSUE TITLE
2.0 Final version do I need to wait until next year ?

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular#10176]
## If release next year, we can't wait to use the react ?

please tell me 

thank you very much

**Comment by Raziaar** [comment]
Why not use it in RC4? The changes between each of the RC's is not likely to be great. You can adjust to them slightly modifying your application. It's come a long ways since Beta.

**Comment by pkozlowski-opensource** [comment]
@iloveyo123u1 you can track progress towards 2.0 looking at the milestones here: https://github.com/angular/angular/milestones
