### ISSUE TITLE
Angular 2 new router api does not navigate to the page

### ISSUE THREAD

**Issue by joshivis** [angular/angular#10178]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
While using router in html as shown below, it works fine and the application navigates to the target when clicking on the link.

`<a [routerLink]="['target']">`

However, if I change above link to call a function (e.g. showTarget()) and use router api as shown below, it does not navigate to target.

```
import { Router, ActivatedRoute, ROUTER_DIRECTIVES } from '@angular/router';
showTarget() {
    let link = ['target'];
    this.router.navigate(link).then(
      function(){
          console.log('navigate success');
      },
      function(){
          console.log('navigate failure');
      }
    );
}
```
With above code, the console shows 'navigate success' but nothing happens on the screen. URL on the browser and the current page both stay unchanged.

I also tried navigating to some dummy link to see if it logs 'navigate failure' but it always shows 'success' no matter what link is specified.

    import { Router, ActivatedRoute, ROUTER_DIRECTIVES } from '@angular/router';
    let link = ['target'];
    this.router.navigate(link).catch(err => console.error(err));
    link = ['non-existing-target'];
    this.router.navigate(link).then(
      function(){
          console.log('navigate success');
      },
      function(){
          console.log('navigate failure');
      }
    );
How do I debug what's causing this behaviour?

**Expected/desired behavior**

I expect the application to navigate to target page when router.navigate() is complete.

* **Angular version:** 2.0.0-rc.1  **Router Version:=** 3.0.0-alpha.5
 
* **Browser:** [Chrome 51] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by zoechi** [comment]
Please provide a Plunker to reproduce. 

I think you first need to convert the `let link = ['target'];` to an `UrlTree` by using `let urlTree = this.router.createUrlTree(this.link);` and then pass it to `navigate(...)` instead.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by joshivis** [comment]
`router.navigate()` takes a link `['target']` as parameter. Passing `UrlTree` results into compile errors. Surprisingly, even the wrong link does not cause any error on the console. Basically router.navigate() does not complain at all about the given link, valid or invalid.

**Comment by zoechi** [comment]
Sorry for the noise, I mixed it up with `navigateByUrl` or something.

**Comment by brandonroberts** [comment]
If you're navigating relatively with `router.navigate`, you need to inject the `ActivatedRoute` and provide it. This is going to be in the docs soon.

```ts
constructor(private router: Router, private route: ActivatedRoute) {}

router.navigate(['target'], { relativeTo: this.route })
```

This works with routerLinks because the ActivatedRoute is implicit

**Comment by joshivis** [comment]
I think I have understood the problem and it suggests there is a bug with navigate function. While using `relativeTo` with relative links, the navigation fails and shows error. 

However, if you omit `relativeTo` and provide any target (existing or invalid) as relative link, it does not throw any error.

I would expect navigate to at least throw an error in case relative is missing and it does not understand the link. May be this is fixed in later versions, I will check once we upgrade to latest version. Closing the issue for now.
