### ISSUE TITLE
Browser Back Button in Safari does not Trigger Change Detection

### ISSUE THREAD

**Issue by Spittal** [angular/angular#10171]
**I'm submitting a ...**
[X] bug report

**Current behavior**
Running Safari Version 9.1.1 (11601.6.17)

When I visit a route, then hit the browser back button, change detection does not occur and I'm left with a blank screen.

**Expected/desired behavior**
When I hit the browser back button I expect to see the applicable component with data showing in the router outlet.

**Reproduction of the problem**
GIF OF BEHAVIOUR
http://imgur.com/a/pNRYa

STEPS TO REPRODUCE
1. Open this plunk: http://plnkr.co/edit/ER0tf8fpGHZiuVWB7Q07?p=preview
2. Launch Preview in Another Window (small blue 'expand' button top right of preview pane)
3. Click on any link
4. Hit browser back button

**Please tell us about your environment:**
Mac OSX 10.11.5 Running Safari Version 9.1.1 (11601.6.17)

*CAN CONFIRM THIS WORKS IN CHROME AND FIREFOX.*

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Safari 9.1.1 |  iOS 9 Safari ] 
 
* **Language:** [TypeScript 2.0]

**Comment by ericmartinezr** [comment]
That was fixed here https://github.com/angular/angular/commit/f08060b0b00c98341c7e1fd9acb984402c280396

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !

**Comment by thanhtrungit97** [comment]
@ericmartinezr how to override
