### ISSUE TITLE
Show username (String) using "Alert"

### ISSUE THREAD

**Issue by tecnicoEA** [angular/angular#10179]
Hello! I have a probem because in my function doAlert() I would like show the username using "alert", so... I need convert it to string for that. Somebody know how can I solve it?
Thanks in advance.

Best regards. 

`import {Component} from "@angular/core";
import {NavController , Alert} from 'ionic-angular';
import {Principal} from '../principal/principal';
import { FORM_DIRECTIVES, FormBuilder,  ControlGroup, Validators, AbstractControl } from '@angular/common';
import {CustomValidators} from '../validators/CustomValidators';

@Component({
  templateUrl: 'build/pages/home/home.html',
  directives: [FORM_DIRECTIVES]
})
export class HomePage {

    authForm: ControlGroup;
	username: AbstractControl;
	password: AbstractControl;
    
    
  constructor(private navController: NavController , private fb: FormBuilder) {
    this.navController=navController;
    
        this.authForm = fb.group({  
            'username': ['', Validators.compose([Validators.required, Validators.minLength(4), CustomValidators.checkFirstCharacterValidator])],
            'password': ['', Validators.compose([Validators.required, Validators.minLength(4), CustomValidators.checkFirstCharacterValidator])]
        });
 
        this.username = this.authForm.controls['username'];     
        this.password = this.authForm.controls['password'];  
    }
	
    onSubmit(value: string): void { 
        if(this.authForm.valid) {
            console.log('Submitted value: ', value);
        }
    } 
    
    goToPrincipal(){
        
      this.doAlert();
            
    }
    
    doAlert() {
            let alert = Alert.create({
                title: 'New Friend!',
                subTitle: this.username,
                buttons: ['OK']
            });
            this.navController.present(alert);
        }
    
    
}`

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi - you are doing grant work here!
