### ISSUE TITLE
CurrencyPipe does not respect currency defined number of digit

### ISSUE THREAD

**Issue by jvelo** [angular/angular#10189]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Defined number of digits for a currency is not respected by NumberFormatter API and CurrencyPipe. For example for EUR expected precision is 2 digits (http://www.unicode.org/cldr/charts/dev/supplemental/detailed_territory_currency_information.html#EUR) ; but the pipe gives :

```
{{ 1.1234 | currency:'EUR' }}
=> EUR1.123
```

**Expected/desired behavior**

By default when no formatting option is passed, the currency defined number of digit should be respected. i.e. :

```
{{ 1.1234 | currency:'EUR' }}
=> EUR1.12
```

**Reproduction of the problem**
See above the example with the currency pipe.

**What is the motivation / use case for changing the behavior?**
Make the currency pipe actually suited to display money values using the currency defined precision instead of an arbitrary precision.

**More info**
```NumberFormatter.format``` takes formatting options for the underlying Intl call, with default values : ```minimumIntegerDigits = 1, minimumFractionDigits = 0, maximumFractionDigits = 3``` ; this makes it not very well suited to deal with currencies where you don't want to set any decimal precision leaving it up to the precision of the currency instead.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Browser:** all
* **Language:** all

**Comment by zoechi** [comment]
How is that related to Angular2?
Seems to be plain JavaScript https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by jvelo** [comment]
It's a behavior of NumberFormatter in @angular/common/src/facade/intl ; not the Intl API which it uses.

**Comment by vicb** [comment]
@jvelo could you describe the current and expected behavior (not worrying about implementation details) ? Thanks

**Comment by jvelo** [comment]
@vicb thanks, I described it more high level.

**Comment by vicb** [comment]
Thanks the updated description is very good !

**Comment by jvelo** [comment]
@vicb Thanks ! very quick response :)
