### ISSUE TITLE
Simultaneous primary and auxiliary <router-outlet> routing issue

### ISSUE THREAD

**Issue by autopulous** [angular/angular#10180]
**I'm submitting a ...**

```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

The new router produces an error when simultaneously routing to a primary and auxiliary `<router-outlet>`

`<a [routerLink]="['dog(under:/bird)']">Over Dog & Under Bird</a>`

I've sought help on the issue via the following sources:

https://groups.google.com/forum/#!topic/angular/mAKbiQgxibg
http://stackoverflow.com/questions/38338038/angular-router-3-0-0-beta-2-routerlink-to-a-primary-and-auxiliary-route
https://www.udemy.com/the-complete-guide-to-angular-2 (Q&A with instructor)

By all accounts my syntax is correct (but maybe we're misunderstanding the syntax/what is possible)... 

**Expected/desired behavior**

No error

**Reproduction of the problem**

http://plnkr.co/edit/PI7qaWLVwG6CYOwm7iJC?p=preview

**What is the expected behavior?**

No error

**What is the motivation / use case for changing the behavior?**

No error

**Please tell us about your environment:**
- **Angular version:** "@angular/router": "3.0.0-beta.2"
- **Browser:** Chrome Version 51.0.2704.106 m (64-bit) 
- **Language:** ES6 / "typescript": "1.8.10"
- **OS:** Windows 7 Enterprise Service Pack 1

**Comment by zoechi** [comment]
This recently merged PR seems related #10003

**Comment by autopulous** [comment]
Just to clarify: the plunker that I provided shows routing to an auxiliary `<router-outlet>` by itself did work...

**Comment by sqlsolver** [comment]
+1 to @autopulous - not resolved.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)

**Comment by thekalinga** [comment]
Try [this](https://github.com/angular/angular/blob/master/modules/@angular/router/test/create_url_tree.spec.ts#L87-L91).

I have tested this in my local project.

It works

**Comment by atscott** [comment]
Stackblitz example of this working in Angular v9: https://stackblitz.com/edit/angular-ivy-zskdsb?file=src%2Fapp%2Fapp.component.ts
```
  <li><a [routerLink]="[{outlets: {under: 'bird'}}]">Under Bird</a></li>
  <li><a [routerLink]="[{outlets: {primary: 'dog', under: 'bird'}}]">Over Dog & Under 
```

`[routerLink]` uses `Router#createUrlTree` internally, which documents how to navigate to different outlets simultaneously: https://angular.io/api/router/Router#createUrlTree-usage-notes

Closing as fixed.
