### ISSUE TITLE
Router: CanDeactivate doesn't provide future RouterState snapshot 

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#10186]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using the `CanDeactivate` guard, the `RouterStateSnapshot` is a snapshot of the current state.

**Expected/desired behavior**

The `RouterStateSnapshot` in the `canDeactivate(component, route, state)` should provide the `state` as the future `RouterState`.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/8SBz5eKZOBh1vuFiNWtW?p=preview

1. Open the developer console
2. Click on the `Away` link
3. Click on the `Home` link
4. Note the console logs `destination url: /away` from the `RouterStateSnapshot.url`

**What is the expected behavior?**

The console logs `destination url: /` from the `RouterStateSnapshot.url`

**What is the motivation / use case for changing the behavior?**

To provide some context as to the proposed destination URL and other information. The current `RouterState` is already available through the `Router` service

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 

cc: @vsavkin

**Comment by zoechi** [comment]
like #9853 ?

**Comment by brandonroberts** [comment]
Yea, I'm not proposing adding another argument to the method though. I'll leave a comment there
