### ISSUE TITLE
Upgrade adapter wrongly interprets optional attributes

### ISSUE THREAD

**Issue by chrisse27** [angular/angular#10181]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I would like to integrate a ng1 directive into a ng2 component that has optional attributes:
```
...
scope: {
  test: '=?'
},
...
```
Whatever I set as a value for 'test', it is not reflected in my ng1-directive. If I remove the '?' everything works as expected.

**Expected/desired behavior**

Optional attributes should be correctly parsed by the upgrade adapter. Currently, there is this faulty piece of code (introduced in commit 8e1d2fb3255f69b796ae26938ab9aec8e58d6f05):

```
88          var type = localName.charAt(0);
89	          localName = localName.substr(1) || name;
```

When the attribute is optional then localName is set to '?' instead of 'name'.

**Reproduction of the problem**

This Plunkr demonstrates the problem: http://embed.plnkr.co/hRiZUzFmGFQzyF2hS3Ip/

**Please tell us about your environment:**

* **Angular version:** 1.5.7 and 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by palmanis** [comment]
https://github.com/angular/angular/issues/8856
I also had reported it a while back, but does not look like anything happened on this.

**Comment by chrisse27** [comment]
Thanks for referencing your issue. At least we are not alone with that problem.

**Comment by chrisse27** [comment]
@mhevery Can you give us any indication, whether there is a plan from your side to fix this issue in the near future or whether you see this as intended behaviour? A fix shouldn't be too difficult, so I would give it a try. Would be just good to get some feedback from the original author before starting any work.
