### ISSUE TITLE
Router 3.0.0-beta.2 does not work with rxjs UMD bundle

### ISSUE THREAD

**Issue by adamfoley** [angular/angular#10183]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
While configuring router (**createUrlTree()**), exception thrown trying to call access undefined **rxjs_observable_of**.  

**Expected/desired behavior**
Router library to properly utilize existing rxjs UMD

**Reproduction of the problem**
Create any application with routing using Router 3.0.0-beta.2 and rxjs UMD bundle.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
To use UMD modules

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4, router 3.0.0-beta.2, rxjs 5.0.0-beta.6
 
* **Browser:** Chrome; Firefox
 
* **Language:** typescript 1.8.10

**Comment by adamfoley** [comment]
This shim loaded after rxjs and before router fixes the issue.  Not sure if this an rxjs or router issue:

```
(function () {
	var g;
	if (typeof (window) != null) g = window;
	else if (typeof (global) != null) g = global;
		// couldn't locate global
	else return;
	g.rxjs_observable_of =
	g.rxjs_observable_forkJoin =
	g.rxjs_observable_fromPromise = g.Rx.Observable;
})();
```

**Comment by brandonroberts** [comment]
This has been fixed in master and will be ready with the next release. See: https://github.com/angular/angular/issues/9872

**Comment by adamfoley** [comment]
Thanks for heads up brandon.  Sorry for the duplicate.
