### ISSUE TITLE
Animation allow specifying pseudo-classes in state() and transition()

### ISSUE THREAD

**Issue by cherrydev** [angular/angular#10196]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`transition()` allows only `*`, `void` or a custom state declared in `state()` as its expression.
`state()` only allows an expression that is compared to the value assigned in the template expression.

**Expected/desired behavior**

`state()` and `transition()` allows css pseudo-classes to be used in determining state.
Example:

```
animations: [
    trigger('heroState', [
      state('-:active', style({
        backgroundColor: '#eee',
        transform: 'scale(1)'
      })),
      state(':active',   style({
        backgroundColor: '#cfd8dc',
        transform: 'scale(1.1)'
      })),
      transition('-:active => :active', animate('100ms ease-in')),
      transition(':active => -:active', animate('100ms ease-out'))
    ])
  ]
```

The presence of a pseudo-class with a colon would refer to the applied element having the pseudo-class applied.  The presence of a pseudo-class with a negative sign and then a colon would refer to the applied element not having the pseudo-class applied. This is a potential way of adding this to the DSL and I'm sure somebody might think of a better or more general way to express this.

An alternative syntax would be to allow a named state to refer to the state of a pseudo-class which is then used in the transition:

```
animations: [
    trigger('heroState', [
      state('active :active', style({
        backgroundColor: '#eee',
        transform: 'scale(1)'
      })),
      state('inactive -:active',   style({
        backgroundColor: '#cfd8dc',
        transform: 'scale(1.1)'
      })),
      transition('inactive => active', animate('100ms ease-in')),
      transition('active => inactive', animate('100ms ease-out'))
    ])
  ]
```

**What is the motivation / use case for changing the behavior?**

There seem to be two ways of achieving this behaviour currently.
1. Use the native web animation expressions directly in the styles declaration of the directive
2. Add listeners for hover/click/etc events on your directive and store the state in a property of your directive to bind to `state()`

The problem with 1) is that you now have to use two different syntaxes for expressing your animation and you will lose the (upcoming) ability to pull your animation styles from existing styles declared in the `styles:` section. Furthermore you are unable to use the extremely convenient syntax of `@animationTrigger` on an element

The obvious problem with 2) is that you are now required to add listeners to all of your directives that will store state about the element.

The motivation behind this is to allow for a consistent and convenient way of expressing animations regardless of if they use programmatic state of a directive or if they applicable using native web animations.

Please note that it seems entirely plausible to be able to use this as a general-purpose method of querying to see if a particular selector matches the applied element, such as a regular css class.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** all 
- **Language:** TypeScript 1.8

**Comment by davd33** [comment]
I'd like to see this feature as well :+1:

**Comment by mslawins** [comment]
Would kill for that feature! Cheers 👍

**Comment by matsko** [comment]
Unfortunately this can't be supported with how the current @ triggers work. You'll need to handle the pseudo state detection within your component code.
