### ISSUE TITLE
Relative routerLink doesn't get updated on url changing

### ISSUE THREAD

**Issue by stranbird** [angular/angular#10209]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Plunkr: http://plnkr.co/edit/QPW3qrQmSPrDwwXYK6Wx?p=preview

Here shows an item detail page embeds a child view which exhibits the related items. When I click the related items to visit other item's detail page, the links of the tab("Overview" and "Related") doesn't update accordingly.

When clicks "Item: 2", the link of the tab is still "/item/1/related".

**Expected/desired behavior**

When clicks "Item: 2", the link of the tab should change to "/item/2/related".

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Plunkr: http://plnkr.co/edit/QPW3qrQmSPrDwwXYK6Wx?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Angular Router version:** 3.0.0-beta.2
 
* **Browser:** [ Chrome 51 ] 
 
* **Language:** [TypeScript ]

**Comment by zoechi** [comment]
sounds like #10207

**Comment by stranbird** [comment]
Yes, they describe the same issue. Should I close the issue for duplication?

**Comment by zoechi** [comment]
Yes, please. If you have additional information (Plunker link, ...) please post it there as comment.
