### ISSUE TITLE
html input change event propagates out of wrapping component

### ISSUE THREAD

**Issue by npx** [angular/angular#10204]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When wrapping an html input in a component, without giving the component an explicit `@Output change` the html input's change event propagates out of the component.

**Expected/desired behavior**
Do not let change events propagate out of components. This behavior is confusing when adding your own `@Output change` that suddenly emits events that you are not emitting yourself.

**Reproduction of the problem**
https://embed.plnkr.co/AxWhbEi5GKi71NSV3vF0/

**What is the expected behavior?**
If a component does not have an `@Output change` it should not react to emit change events:

```
<my-component (change)="onChange($event)"></my-component>
```
In a setup like this I only expect change event fired from my component and not change events of html inputs (even nested in other child components).

**What is the motivation / use case for changing the behavior?**
I was hit by surprise where the premature change events came from when I defined my own `@Output change` EventEmitter and only emit on button press

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Only tested in Chrome
 
* **Language:** Typescript 1.8

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/4059

**Comment by zoechi** [comment]
That's by design. DOM events bubble as always and Angular is not involved here in any way.
Only events from `@Output()` don't bubble. 
There were several similar issues already. Just don't use DOM event names for custom events.

**Comment by vicb** [comment]
Thanks zoechi for helping
