### ISSUE TITLE
Router: expose preventPushState

### ISSUE THREAD

**Issue by cghislai** [angular/angular#10202]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no way to trigger a navigation while preventing a pushState event

**Expected/desired behavior**
There should by a way of preventing the pushState event, maybe using the NavigationExtras:
```
this.router.navigate(['/myRoute', {id= id}], {preventPushState: true});
```

**What is the motivation / use case for changing the behavior?**
I have a route that listen for its fragment parameters. When they are not present, I setup default values and trigger a navigation so that the url is updated correctly. There is no way for the user to go back since it will always be redirected from [route without param]->[route with param]. I would like to update the url without pushing an history state.

**Comment by zoechi** [comment]
#9608

**Comment by cghislai** [comment]
duplicate of #9579
