### ISSUE TITLE
Exception - "reflect-metadata shim is required when using class decorators"

### ISSUE THREAD

**Issue by karolmarchewka** [angular/angular#10201]
**I'm submitting a 

[x] bug report
[ ] feature request
[ ] support request 

Problem description:
-----------------------
I receive an exception during debugging the Angular 2 source code in Visual Studio Code.

Steps to reproduce:
----------------------
1. Take a sample project i.e. angular2-quickstart.
2. Choose Node.js as your debugger as I've showed on screen1.
![screen1](https://cloud.githubusercontent.com/assets/11705687/17017219/bd927490-4f32-11e6-9cc5-971b39c591e5.PNG)
3. Set sourceMaps to "True" in launch.json setting (screen2).
![screen2](https://cloud.githubusercontent.com/assets/11705687/17017224/c15ef83c-4f32-11e6-9fc0-07db54c0857b.PNG)
4. Run debugger.

You will receive an exception in a part of code of the decorator.ts file.
```
var Reflect = global.Reflect;
// Throw statement at top-level is disallowed by closure compiler in ES6 input.
// Wrap in an IIFE as a work-around.
(function checkReflect() {
  if (!(Reflect && Reflect.getMetadata)) {
    throw 'reflect-metadata shim is required when using class decorators';
  }
})();
```
![screen3](https://cloud.githubusercontent.com/assets/11705687/17017626/5f195c38-4f34-11e6-8e19-facb2cee45d7.PNG)
Please check it. Thanks.

Environment:
--------------

* **Angular version:** 2
 
* **System:** Windows 10
 
* **Language:** TypeScript 1.8

**Comment by karolmarchewka** [comment]
Third screenshot below:
![screen3](https://cloud.githubusercontent.com/assets/11705687/17017626/5f195c38-4f34-11e6-8e19-facb2cee45d7.PNG)

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
