### ISSUE TITLE
Http request: Unable to override default content-type with set headers value.

### ISSUE THREAD

**Issue by joshgerdes** [angular/angular#10210]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using angular2-rc.4

When making a http request, the headers 'Content-Type' is being set from a type check of the data entered (from the detectContentType method).  If a 'Content-Type' header is added as an option to the request call it is ignored.

**Expected/desired behavior**
I would expect if a 'Content-Type' is specifically defined in the options of the request call it would override any default 'Content-Type' set.

**Reproduction of the problem**
Easier explained through code.

**What is the expected behavior?**
See attached proposed PR.

**What is the motivation / use case for changing the behavior?**
Would be nice to be able to specifically set a Content-Type for any given data being sent.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8]

**Comment by reenezden** [comment]
Same behaviour here
