### ISSUE TITLE
Can't Access Parent Router Params inside of Child

### ISSUE THREAD

**Issue by DerekTBrown** [angular/angular#10219]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Current behavior**
I am using a route guard to verify that a route actually exists.  I have placed the router guard inside the child route I would like to protect, but doing so, I can't see the parameters of the parent router.  For example, if I have a route /parent/:parentid and have child routes /parent/:parentid/child/:childid,, if I were to protect the childb route with a route guard, then I can only see :childid as a parameter, not :parentid.

**Expected/desired behavior**
I should be able to see :parentid and :childid as params.

**What is the motivation / use case for changing the behavior?**
Undoubtedly the operation of a subpage depends on that of the parent.  Likewise, this data needs to be passed into the child.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
Angular 2.0.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
Typescript

**Comment by DerekTBrown** [comment]
This was actually a problem with the original router as well:
https://github.com/angular/angular/issues/8335

**Comment by brandonroberts** [comment]
The `canActivate ` method takes two arguments, `canActivate(route, state)` . You can use `state.parent(route).params` to get the parent params in the guard

**Comment by DerekTBrown** [comment]
I mean, this works- but I don't see why we couldnt just have an array which contains all the parameters.

**Comment by brandonroberts** [comment]
Mainly because there would be parameters with the name which would cause its own problems. The route segments are designed to be independent of each other, with the RouterState holding the information to traverse the route tree to get what you need. There could be an easy way to get at this information in the future, but that's how it works currently.

**Comment by DerekTBrown** [comment]
That makes sense
