### ISSUE TITLE
Rename DOM elements representing components without selectors 

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#10216]
Components without selectors are rendered as `<undefined>` which feels like a bug. Could we give them a new name?

**Comment by pkozlowski-opensource** [comment]
Are the components without selectors allowed? We need to cross-check it with #3464 which is about improving an error message when a component is missing a selector (!).

**Comment by vicb** [comment]
Cc @tbosch

**Comment by mhevery** [comment]
@tbosch can we change it to default to `<component>`?

**Comment by tbosch** [comment]
Maybe <Ng-component>?

**Comment by tbosch** [comment]
Lowercase ...

**Comment by vicb** [comment]
ng-undefined ;)
