### ISSUE TITLE
Not able to bind dynamic json data to dynamically loaded child component

### ISSUE THREAD

**Issue by snkrishnan1** [angular/angular#10212]
I am trying to dynamically load a child component from the parent component. From the parent component I need to pass some parameter to the child which would be used in the child component to make a service call and retrieve some data from WebAPI Service. the returned data should be bound to some input controls in the child component.
for testing purpose I have created a plunker wherein I am loading a child component from the parent and I am trying to bind the input controls data from the JSON object which i have initialized locally. 
I am facing some issues here, I am getting 2 instances of the same child component loaded (1 during the initial load itself and then during the actual event on the parent component) and also the data is not getting bound in the child component properly ?

https://plnkr.co/edit/xROfBv?p=preview

Similar to DynamicComponentLoader method like loadAsRoot, don't we have any methods to ensure only 1 instance is being loaded in the ComponentResolver?

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
