### ISSUE TITLE
[Feature][HTTP] Add support for easy 2-Cookie-Handoff 

### ISSUE THREAD

**Issue by vicb** [angular/angular#10215]
Looks like a nice pattern: https://developers.google.com/web/updates/2016/06/2-cookie-handoff

Needs investigation to know how we can ease the usage of the 2CH with angular

**Comment by bsittler** [comment]
Which cookie operations will you need? Are you able to accomplish some or all of it in the meantime using postMessage coordination with a cooperating IFRAME or document context?

**Comment by gkalpak** [comment]
It sounds like this pattern didn't catch on and there's been low demand.
