### ISSUE TITLE
docs: life-cycle - directives support "VIEW" lifecycle hooks, the docs say they dont

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#10221]
**I'm submitting a ...**  Hard to say....

**Current behavior**
- ngAfterContentInit
- ngAfterContentChecked
- ngAfterViewInit
- ngAfterViewChecked

Fire on directives.

**Expected/desired behavior**
According to the [docs](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#hooks-overview) these lifecycle hooks are **Components only**
- ngAfterContentInit
- ngAfterContentChecked
- ngAfterViewInit
- ngAfterViewChecked

The compiler registers them to invoke on directives as well.
The view factory of a component containing a directive will invoke the lifecycle hook on that directive. This is not by change, this is by intent from the compiler as it requires accessing the directive instance and calling the hook within the `detectChangesInternal` method.

Here's a [plunker](https://plnkr.co/edit/7jXGGE?p=preview)
I can only assume the docs are incorrect...

**Comment by tbosch** [comment]
`ngAfterContentInit/Checked` is also valid for directives, as they can also use `@ContentChildren` -> docs need to be changed. 

`ngAfterViewInit` also fires for directives so that they can be notified when all components in the template that they are in have been processed.

**Comment by vicb** [comment]
Anybody from the community wants to submit a docs PR ?
@shlomiassaf ?

**Comment by Drumarcco** [comment]
@vicb PR submitted :smiley:

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource docs issue

**Comment by btinoco** [comment]
Why is this closed? The documentation is still wrong.

**Comment by gkalpak** [comment]
Probably closed because docs issues used to be tracked on `angular/angular.io`. Reopening since we are now tracking docs issues on this repo. @Drumarcco, could you please submit a new PR against [this file][1]?

[1]: https://github.com/angular/angular/blob/5d4b36f80f295455f4250c4257462b22ce6b3372/aio/content/guide/lifecycle-hooks.md

**Comment by Drumarcco** [comment]
PR Opened @gkalpak 😄

**Comment by sandangel** [comment]
5 months to process a docs fix PR ??? And it hasn't been merge yet.
