### ISSUE TITLE
(docs): Wrong dynamic forms with new forms API subtitle

### ISSUE THREAD

**Issue by ShadowManu** [angular/angular#10225]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
In the TS Documentation, in the [Dynamic Forms Cookbook page](https://angular.io/docs/ts/latest/cookbook/dynamic-form.html) using the new forms API has a subtitle of 'Render dynamic forms with NgFormModel'

**Expected/desired behavior**
It should use a different subtitle more alike to the technique explained, like 'Render dynamic forms using FormGroup/FormBuilder'

**Reproduction of the problem**
Just visit the doc page linked above

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
Not to be pedantic, just to catch typos.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4 (latest docs)
 
* **Browser:** all
 
* **Language:** TypeScript (all others too?)

**Comment by ericmartinezr** [comment]
Hey @ShadowManu , would you mind to re-open this suggestion in the website repo https://github.com/angular/angular.io?

**Comment by ShadowManu** [comment]
Just did t ;)

**Comment by kara** [comment]
Thanks for reporting! Looks like this has been posted in the docs repo, so closing here.
