### ISSUE TITLE
Cannot provide Provider when an Attribute Decorator is used in constructor of a component.

### ISSUE THREAD

**Issue by MyOnlyGH** [angular/angular#10229]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

When we have a component where in constructor we specify an Attribute decorator, it never let's you inject that component with error related to "No Provider for @Attribute('attribute').

There should be a way to provide a provider so that we can inject that component.

**Reproduction of the problem**
 We have a third party library which provides a table. We change this pure JavaScript library to an angular 2 component using code. 

```
@component({selector: 'mytable', templateUrl:'URL of template'}
export class mycomp{ 
//data members.....
constructor (element ref injection, @Attribute('sampleString') private sampleString:string){}
//public methods......
private ngOninit(){ this.dataview = dataview of third party lib.    }
}
```

Now that we have a component, we want to write unit test for this component itself.
//Test
```
Describe("my test",()=>{ 
beforeEachProviders(()=>[ mycomp, provider for elementRef]);

It('test', async(inject ([TestComponentBuilder,mycomp], (tcb: TestComponentBuilder) => {
tcb.createAsync(mycomp)
.then ((fixture)=> {
expect(true). toBe(false)
})
 });
```

However this code returns in an error
Error: DI Exception: No Provider for @Attribute('sampleString')

**What is the expected behavior?**
There should be a way to provide a provider for this, or it should not throw error.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Angular version: 2.0.0-rc.1
 
* **Browser:** [Chrome 50] 
 
* **Language:** [ TypeScript]

**Comment by vicb** [comment]
If you provide some valid repro code it would help us handle the issue quicker. Thanks

**Comment by zoechi** [comment]
I'ts a support question or feature request. I have investigated a bit but haven't found anything.

Is it possible to provide explicitly (by adding to providers of bootstrap or a component) something that is passed for constructor parameters that have an `@Attribute()` decorator?

The only way I found is to instantiate the component by adding it to the template of another component and passing an attribute. 

The question is, is there (for example for tests) to provide such an attribute selector so it's not necessary to use an additional test component to wrap the component that actually should be tested.

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have a reproduce scenario in plunker. Happy to re-open when one surfaces.

**Comment by zoechi** [comment]
@pkozlowski-opensource I think it's a simple feature request (or a question if something already exists)

How can one provide a provider that gets injected to a constructor parameter decorated with `@Attribute()`? 

The only way I know is to use `<some-comp some-attr="some-value">` for 

```ts
class SomeComp {
  constructor(@Attribute('some-attr') private someAttr;) {}
}
```
Is there a way to register a provider that is passed to the constructor of `SomeComp` so that `SomeComp` can be tested without the need of HTML?
