### ISSUE TITLE
Support ngOptions

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#1022]
Currently, the only way to use select is to generate the list of options manually, as follows:

```
<div [control-group]="form">
  <select control="city">
     <option value="SF">San Fran</option>
     <option value="NYC">New York City</option>
  </select>
</div>
```

It might be a good idea to support something like `ngOptions`. 

Implementation notes:

* One way to implement it is to define a new component that can be used as follows:

```
<select-with-options [value]="SF" [options]="[['SF', 'San Fran'], ['NY', 'New York City']]">
</select-with-options>
```

**Comment by mhevery** [comment]
we dropped this in AngularDart and just went with `ng-repeat` and `ng-value`. Any reason why we can't do the same for Ng2?

**Comment by vsavkin** [comment]
Not really. I actually did not use ngOptions even in Angular 1 because I always found it too confusing.

I created this issue so we can talk about it here.

**Comment by yjbanov** [comment]
Removed from M7. It's not a blocker.

**Comment by mhevery** [comment]
So the way we did this in AngularDart is:

```
<div [control-group]="form">
  <select control="city">
     <option>-- select one --</option>
     <option *for="var option in options" [value]="option">{{option.name}}</option>
  </select>
</div>
```

Is this not sufficient?

**Comment by vsavkin** [comment]
I think it is sufficient. We can close the issue and open it again when there is a lot of demand for ngOptions.
