### ISSUE TITLE
Linting specs should not complain about missing `@internal`

### ISSUE THREAD

**Issue by vicb** [angular/angular#10226]
currently we have a lint check that requires all class members prefixed with _ to also have `@internal` annotation. This is not necessary when creating classes in tests.

see #10224

/cc @alexeagle

**Comment by alexeagle** [comment]
now that Dart is forked, we can stop using the leading underscore and remove the lint check altogether, right?

**Comment by vicb** [comment]
`_` could help with transpiled code, I think we should keep it. 

Whatever way we end up choosing, it would be great to have consistency in the code base (which is not here today)

**Comment by gkalpak** [comment]
I believe this is obsolete now. I see `_` properties without `@internal` (e.g. [query_spec.ts#L1273][1]).
Closing...

[1]: https://github.com/angular/angular/blob/fcbc38cb2/packages/core/test/acceptance/query_spec.ts#L1273
