### ISSUE TITLE
Clarify the error message on "{"

### ISSUE THREAD

**Issue by vicb** [angular/angular#10227]
`{` are used to start an ICU message.

If users have a `{` in their template w/o it being the start of an ICU message, the error message should be explicit (i.e. contain the escape sequence`{{ '{' }}`).

**Comment by vicb** [comment]
Please fill out the GH template when creating a new issue ;)

**Comment by foxjazz** [comment]
<div ngNonBindable> can be used to tell compiler to skip parsing (per Rob)
