### ISSUE TITLE
Browser / app hangs on refresh

### ISSUE THREAD

**Issue by sam-wheat** [angular/angular#10228]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Refreshing page with F5 / Refresh button causes browser to hang

**Expected/desired behavior**
Refreshing page with F5 / Refresh button will reload page

**Reproduction of the problem**
Start App, press F5 in Chrome,IE,FF.  Browser hangs with no error message

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 Chrome, IE 11, FF 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
TypeScript

http://stackoverflow.com/questions/38005928/hashlocationstrategy-in-angular2-rc3-doesnt-work  // proposed answer does not work
http://stackoverflow.com/questions/38265536/angular-2-rc-4-hashlocationstrategy-no-longer-working  // same as my config, proposed answer does not work
When I first started troubleshooting this I had no idea what was causing my app to hang so I started deconstructing my app thinking it was one of my components.  I wound up writing this ticket which no doubt has a wrong conclusion but was as far as I got to reconstruct the problem:  
http://stackoverflow.com/questions/38440303/including-router-outlet-router-outlet-causes-app-to-hang-on-refresh

For kicks I tried the fix recommended here: https://github.com/angular/angular/issues/9099
My default route did not load but if I hit f5 before navigating the page would refresh.  After navigating it would not refresh.

I have exhausted every resource I can think of.  I have been working on this for a couple days.  Last time I spent a couple days working on an RC2 issue only to find out the code was deprecated.  I sure hope that does not happen again.  This guy wasn't pleased about it either lol:   https://github.com/angular/angular/issues/9088

Main.ts

	require('./css/site.css');
	import { provide } from '@angular/core';
	import { bootstrap }    from '@angular/platform-browser-dynamic';
	import { Location, LocationStrategy, HashLocationStrategy } from '@angular/common';  
	import { AppComponent } from './app.component';
	import { SessionService } from './services/SessionService';
	import { APP_ROUTER_PROVIDERS } from './app.routes';

	bootstrap(AppComponent, [APP_ROUTER_PROVIDERS, { provide: LocationStrategy, useClass: HashLocationStrategy }]);

app.routes.ts

	import { ROUTER_DIRECTIVES, provideRouter, RouterConfig } from '@angular/router';
	import { Contact } from './contact/contact';
	import { BlogIndex } from './blog/blogIndex';
	import { BlogDetail } from './blog/blogDetail';
	import { Home } from './home/home';

	const routes: RouterConfig = [
		{ path: '', component: Home },
		{ path: 'Contact', component: Contact },
		{ path: 'BlogIndex', component: BlogIndex },
		{ path: 'Post/:slug', component: BlogDetail }
	];

	export const APP_ROUTER_PROVIDERS = [provideRouter(routes)];
	
package.json

	{
	  "version": "1.0.0",
	  "name": "samsblog",
	  "private": true,
	  "scripts": {
		"start": "webpack-dev-server --inline --progress --port 8080",
		"test": "karma start",
		"build": "webpack --progress --profile --bail --display-error-details --minimize",
		"copy": "xcopy C:\\Git\\Blog\\src\\Blog\\node_modules\\bootstrap\\*.* C:\\Git\\Blog\\src\\Blog\\wwwroot\\app\\css\\bootstrap /s",
		"postinstall": "typings install",
		"typings": "typings"
	  },
	  "dependencies": {
		"@angular/common": "2.0.0-rc.4",
		"@angular/compiler": "2.0.0-rc.4",
		"@angular/core": "2.0.0-rc.4",
		"@angular/forms": "0.2.0",
		"@angular/http": "2.0.0-rc.4",
		"@angular/platform-browser": "2.0.0-rc.4",
		"@angular/platform-browser-dynamic": "2.0.0-rc.4",
		"@angular/router": "^3.0.0-beta.2",
		"@angular/upgrade": "2.0.0-rc.4",
		"bootstrap": "^3.3.6",
		"systemjs": "0.19.27",
		"core-js": "^2.4.0",
		"html-webpack-plugin": "^2.22.0",
		"reflect-metadata": "^0.1.3",
		"rxjs": "5.0.0-beta.6",
		"ts-loader": "^0.8.2",
		"zone.js": "^0.6.12"
	  },
	  "devDependencies": {
		"css-loader": "^0.23.1",
		"extract-text-webpack-plugin": "^1.0.1",
		"file-loader": "^0.9.0",
		"image-webpack-loader": "^2.0.0",
		"source-map-loader": "^0.1.5",
		"style-loader": "^0.13.1",
		"typings": "^1.0.4",
		"webpack": "^1.13.1",
		"typescript": "^1.8.10",
		"webpack-dev-server": "^1.14.1",
		"webpack-merge": "^0.14.0"
	  }
	}

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
