### ISSUE TITLE
Animations don't play nice with dynamic innerHTML

### ISSUE THREAD

**Issue by benelliott** [angular/angular#10233]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Animations with wildcard properties don't play nice with dynamic innerHTML values. See
[this plunkr](http://plnkr.co/edit/dZXBbRSINPTr8WDXzU3y?p=preview).

**Expected/desired behavior**

I expected the height transition to be smooth. It seems like the dynamic content is not considered when computing the final value of the `height` property.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

See [this plunkr](http://plnkr.co/edit/dZXBbRSINPTr8WDXzU3y?p=preview)

**What is the motivation / use case for changing the behavior?**

Impoved aesthetics/user experience.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [ Chrome 51 ] 
 
* **Language:** [ TypeScript 1.8 ]

**Comment by vicb** [comment]
@matsko could probably answer in more details but in general nothing plays well with setting `innerHtml` directly - the framework is not aware about the added content and it will an opaque blob for angular.

**Comment by benelliott** [comment]
Is there no way to push the height computation back until the dynamic content has been added to the DOM? They are both happening in the same 'tick'.

**Comment by matsko** [comment]
@benelliott is there any way you can run your application on master? #9887 did fix an issue that may be relative to this. I think it's already resolved, but since RC5 hasn't been released yet you can only test on master.

If you want to use the master builds, set your `package.json` contents to include the following:
```
    "@angular/common": "angular/common-builds",
    "@angular/compiler": "angular/compiler-builds",
    "@angular/core": "angular/core-builds",
    "@angular/platform-browser": "angular/platform-browser-builds",
    "@angular/platform-browser-dynamic": "angular/platform-browser-dynamic-builds",
```

Let me know if this works please.

**Comment by benelliott** [comment]
That seems to have fixed it, thanks @matsko!
