### ISSUE TITLE
URLSearchParams.clone() should also clone the QueryEncoder.

### ISSUE THREAD

**Issue by weini01** [angular/angular#10235]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
URLSearchParams.clone() should also clone the QueryEncoder.
On every http.get request the URLSearchParams are cloned but without the QueryEncoder so the desired custom encoding behavior doesn´t work.

**Expected/desired behavior**
passing URLSearchParams with custom QueryEncoder should work with http.get, http.post, ...

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript X.X]

**Comment by rolandjitsu** [comment]
I have the same issue. I was using `.merge()` and I could not understand why my query encoder is never called. Then I noticed it calls `.clone()` [internally](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/base_request_options.ts#L124), where it actually creates a new `URLSearchParams` object ([@angular/http/src/url_search_params.ts#L91](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/url_search_params.ts#L91)), but without the encoder.

**Comment by asnowwolf** [comment]
@vicb could you please assign this to me? It seems not so complex, I'll try to resolve it.

**Comment by asnowwolf** [comment]
Oh, someone has created a pull request to fix it:

https://github.com/angular/angular/pull/9900

Good job :-)
