### ISSUE TITLE
Adding the CACHED_TEMPLATE_PROVIDER on the test shim fails

### ISSUE THREAD

**Issue by lcrodriguez** [angular/angular#10237]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have this code for loading the CACHED_TEMPLATE_PROVIDER for use in Karma as defined in the plugin https://github.com/karma-runner/karma-ng-html2js-preprocessor.

```
Promise.all([
  System.import('@angular/core/testing'),
  System.import('@angular/platform-browser-dynamic/testing'),
  System.import('@angular/platform-browser-dynamic')
])


.then(function (results) {
  var testing = results[0];
  var testingBrowser = results[1];
  var platformBrowser = results[2];

  testing.setBaseTestProviders(
    testingBrowser.TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS,
    [testingBrowser.TEST_BROWSER_APPLICATION_PROVIDERS, platformBrowser.CACHED_TEMPLATE_PROVIDER]);
})
```
I can confirm that platformBrowser.CACHED_TEMPLATE_PROVIDER is correct.
I get this error on karma:

```
 ERROR: 'Error: Invalid provider - only instances of Provider and Type are allowed, got: undefined
    at InvalidProviderError.BaseException [as constructor] (http://localhost:9876/base/node_modules/@angular/core/src/facade/exceptions.js:20:23)
    at new InvalidProviderError

```

**Expected/desired behavior**

It should define to use the CacheXHR instead.

* **Angular version:** 2.0.0-rc.2

**Comment by cvwilliams** [comment]
If you change "TEST_BROWSER_APPLICATION_PROVIDERS" -> TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS you should be good to

**Comment by pkozlowski-opensource** [comment]
This sounds like a support request so closing it and it doesn't belong here, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Hopefully @cvwilliams hint will get you going.
