### ISSUE TITLE
named `ng-content` directives w/ if expressions not working correctly

### ISSUE THREAD

**Issue by amcdnl** [angular/angular#10236]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When I dynamically switch out named `ng-content` directives using `*ngIf` expressions, it honors the named `ng-content` directive instead of the abstract one. Take the following:

```javascript
@Component({
  selector: 'accordion',
  template: `
    <ng-content></ng-content>
  `,
  directives: [ AccordionGroup ]
})
export class Accordion {
  @Input() closeOnExpand = true;
  @ContentChildren(AccordionGroup) groups;

  ngAfterContentInit() {
    this.groups.forEach(g => g.onToggle.subscribe(::this.toggled));
  }

  toggled(selected) {
    if(this.closeOnExpand) {
      this.groups.forEach(g => g.open = (g === selected));
    } else {
      selected.open = !selected.open;
    }
  }
}

@Component({
  selector: 'accordion-group',
  template: `
    <div class="panel panel-default">
      <h4 (click)=" this.onToggle.emit($event)">
        <a role="button" href="#" *ngIf="header">
          {{header}}
        </a>
        <ng-content *ngIf="!header" select="accordion-header"></ng-content>
      </h4>
      <div class="panel-collapse collapse" [class.in]="open">
        <div class="panel-content">
          <ng-content *ngIf="!header"></ng-content>
          <ng-content *ngIf="header" select="accordion-content"></ng-content>
        </div>
      </div>
    </div>
  `
})
export class AccordionGroup {
  @HostBinding('class.active')
  @Input() open;
  @Input() header;
  @ViewChild('accordion-header') header;
  @Output() onToggle = new EventEmitter();
}
```

I could use it like:

```
<accordion>
  <accordion-group header="Foo" open="true">
    Hello Foo
  </accordion-group>
  <accordion-group>
    <accordion-header>
      <h1>BARRRRS</h1>
    </accordion-header>
    <accordion-content>
      Hello Bar
    <accordion-content>
  </accordion-group>
</accordion>
```

**Expected/desired behavior**
It would dynamically allow you based on the expression to use the ng-content you like

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.4
* **Browser:**All
* **Language:** All

**Comment by vicb** [comment]
`ng-content` is for *static* content projection (ie it is resolved at compile time).

**Comment by amcdnl** [comment]
@vicb got it, would a `<template` be a better suited use case for this?

**Comment by vicb** [comment]
Check https://github.com/angular/angular.io/blob/master/public/docs/_examples/homepage-tabs/ts/app/di_demo.ts

And remember:

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by amcdnl** [comment]
@vicb appologize re: support req comment, was just following up on my bug report. Thanks for info!
