### ISSUE TITLE
Chrome ignores target attribute inside Angular2 app

### ISSUE THREAD

**Issue by wschaef** [angular/angular#10231]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I want to open a link in an iframe like it is described in W3Schools:

```
<iframe height="300px" width="100%" src="demo_iframe.htm" name="iframe_a"> </iframe>
<p><a href="http://www.w3schools.com" target="iframe_a">W3Schools.com</a></p>
```
When I put it inside an Angular2 app like:
```
<my-app>  
  <iframe height="300px" width="100%" src="demo_iframe.htm" name="iframe_a"></iframe>
  <p><a href="http://www.w3schools.com" target="iframe_a">W3Schools.com</a></p>    
</my-app>
```
then it works in IE 11 fine, but in Chrome the link is opening in a new tab.

It works fine in Chrome, if it is outside of Angular2 app.

**Expected/desired behavior**

The link should be opened in the iframe and not in new tab

**Reproduction of the problem**
Just take Getting Started plunker and put the two lines inside template.
I've created a showcase in Plunker: http://plnkr.co/edit/TNfGuCFZ3cl5IwFHUhIw?p=preview

**What is the expected behavior?**

see above

**What is the motivation / use case for changing the behavior?**

I want open a link in an iframe using target attribute. Of cause I can do it in JavaScript, but then I have to sanitize the link and probably introduce a XSS problem. 

**Please tell us about your environment:**
Windows 7, Chrom 51.0.2704.106 m
* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [ Chrome 51.0.2704.106 m|  IE 11  ] 
 
* **Language:** [default from Angular2.0.0-rc.4]

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by wschaef** [comment]
Why support request?
I'm describing a basic HTML feature in a standard browser. Nothing special.

**Comment by wschaef** [comment]
Please reopen the issue.

**Comment by abhishekhingu** [comment]
I am agree with wschaef, please reopen this issue I am facing same issue.

**Comment by rjdsilv** [comment]
Same issue here. Anyone have a fix to that?
