### ISSUE TITLE
Create a test helper to avoid explicit test component class creation

### ISSUE THREAD

**Issue by vikerman** [angular/angular#10241]
Currently the pattern is that you have to declare a test component that instantiates the component under test and then use that to drive the unit test.

In the following example SearchResultCard is the component under test while SearchResultTestComponent is the test component.

``` js
it('should display', async(() => {
       builder.createAsync(SearchResultTestComponent).then((fixture) => {
...
}

@Component({
  selector: 'my-comp',
  template: '<search-result-card [video]="result"></search-result-card>',
  directives: [SearchResultCard]
})
class SearchResultTestComponent {
...
}
```

If we wanted to create different test cases controlling different parameters to the component under test we would probably end up creating different test components which is a lot of typing.

One option would be to create a helper function that actually returned the Test Component class as a return value that can be used in the test.

``` js
function getTestComponent(template: string, viewCount: number,
                          likeCount: number) {
  @Component({
    selector: 'my-comp',
    template: template,
    directives: [SearchResultCard]
  })
  class SearchResultTestComponent {
    result: SearchResult;
    constructor() {
      ...
      let stats = new VideoStatistics();
      stats.setViewCount(viewCount);
      stats.setLikeCount(likeCount);
      ...
      this.result = result;
    }
  }
  return SearchResultTestComponent;
}
```

and the tests could use this parametrized helper function

``` js
it('should display', async(() => {
       builder.createAsync(getTestComponent(
         '<search-result-card [video]="result"></search-result-card>', 2, 1))
           .then((fixture) => {
            ...
           });
     }));

  it('should display without parameters', async(() => {
       builder.createAsync(getTestComponent(
         '<search-result-card></search-result-card>', 2, 1)).then((fixture) => {
          ...
         });
     }));
```

But can we generalize this into a core testing helper method that would take in a template and a property bag that can be used to fill the template and we can totally avoid declaring the test component. Maybe we need to think a bit more if this can create test components that can also handle events in addition to just properties.

``` js
builder.createAsync(getTestComponent('<search-result-card [result]="testInput"></search-result-card>', {testInput: mockedResult})).then(...)
```

**Comment by schmuli** [comment]
Can't you just use the `overrideTemplate` function of the `TestComponentBuilder` to use the same test component with different templates? You would still need to support parameters, but how would these parameter overrides be passed into the test component?

**Comment by vikerman** [comment]
Add example to example repo here - #12409
