### ISSUE TITLE
request| feat(NgModule): provide life cycle hooks

### ISSUE THREAD

**Issue by PatrickJS** [angular/angular#10244]
With the introduction of `NgModule` to solve some problems of having to run code before bootstrap. I think it's better to provide lifecycle hooks for these modules for example theses would be great to have

ngBeforeLoad: before loading the module
ngAfterLoad: after the module is loaded
ngBeforeChangeDetection: do something before change detection happens for this module
ngAfterStable: do something after the zones are stable (a great use-case for this is prefetching async lazy routes after boot that doesn't affect the ui)

ngAfterStable is probably the best feature since universal and jasmine can use it 

might also help with https://github.com/angular/angular/issues/9975
also see ng1 `.config` and `.run` https://github.com/angular/angular.js/issues/4003

[![github-tipe-logo](https://user-images.githubusercontent.com/1016365/34912701-7edec34c-f89c-11e7-8c89-bed6cef064b5.png)](https://tipe.io?ref=github-comment)

**Comment by laco0416** [comment]
IMHO, the constructor of the module class is usable as `ngBeforeLoad`.  
And the `bootstrap()` function returns a promise that can be used as `ngAfterLoad`.

`ngAfterStable` can be replaced by using `NgZone` and `ngZone.onStable`.

I think we need the `ngModuleLoaded` hook, which is called after the module was loaded.
`AppModule` is not only for modules to be bootstrapped but as shared-packages like `RouterModule` .

**Comment by gdi2290** [comment]
The benefit of having these lifecycle hooks is giving control back to the developer for modules. For example, if a 3rd party modules does something async in the constructor there's no way to track it or even know there was an async call. If there was an async method then you would know to invoke it.

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
