### ISSUE TITLE
Router Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by billsworld** [angular/angular#10252]
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am using mgechev seed to do some testing so I have a [home routes](https://github.com/mgechev/angular2-seed/blob/master/src/client/app/%2Bhome/home.routes.ts) and [about routes](https://github.com/mgechev/angular2-seed/blob/master/src/client/app/%2Babout/about.routes.ts)

In my [app component](https://github.com/mgechev/angular2-seed/blob/master/src/client/app/app.component.ts) I am trying to navigate to the home route with `this.router.navigate(['', {foo: 'bar'}]);` 

The issue is that this does not work as expected. If the user is currently on the `about` route `this.router.navigate(['', {foo: 'bar'}]);` will send them to /about;foo=bar, if the user is on the `home` route it produces the error `Cannot read property 'path' of undefined`

**Expected/desired behavior**

If the user is on the `about` route `this.router.navigate(['', {foo: 'bar'}]);` should send them to the `home` route with query params ;foo=bar. If the user is already on the `home` route it should just change the query params.

If the user is on the `about` route and wants to change the query params it should require this code instead `this.router.navigate(['about', {foo: 'bar'}]);` otherwise there is no way to navigate to the `home` route from the `about` route

**What is the motivation / use case for changing the behavior?**
Being able to change the query params on a route with an empty path such as the home route in this example.
- **Angular version:** 2.0.0-rc.4

**Comment by DzmitryShylovich** [comment]
Pls create a plunker with reproduction.

**Comment by billsworld** [comment]
@DzmitryShylovich here is plunker showing the error http://plnkr.co/edit/ZlTV5Y0K3fymu9wz0tPf?p=preview

I made a few changes to the live example from this docs page https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

app.routes.ts and app.component.ts were changed. Click the ```<a (click)="nav()">Test</a>``` to see the error.

**Comment by DzmitryShylovich** [comment]
You incorrectly use `navigate` method. See examples [here](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L289).

**Comment by billsworld** [comment]
I think it's the valid way if you want to just append a query string. See
milestone #4
https://angular.io/docs/ts/latest/guide/router.html#!/%23query-parameters

**Comment by sod** [comment]
`router.navigate(['', {foo:'bar'}])` can only work if the route target has a placeholder defined, like `/my-path/:placeholder`. Then the router can put the `foo=bar` into the placeholders position in *Matrix URL* fashion.

You can still append normal parameters as:

```typescript
this.router.navigate([''], {
    queryParams: {foo: 'bar'}
});
```

**Comment by billsworld** [comment]
@sod hmm the example doesn't seem to have a placeholder but your suggestion did work for me.

app/heroes/heroes.routes.ts
```
export const heroesRoutes: RouterConfig = [
  { path: 'heroes',  component: HeroListComponent },
  { path: 'hero/:id', component: HeroDetailComponent }
];
```

app/heroes/hero-detail.component.ts
```
this.router.navigate(['/heroes', { id: heroId, foo: 'foo' }]);
```

Planning to look into a possible docs clarification on this.

Thanks.

**Comment by billsworld** [comment]
after discussion with @brandonroberts this does in fact seem to be a bug. 

```this.router.navigate(['', {foo: 'bar'}]);``` should work when the user is at the / route just like it works when they are at the /about route.

**Comment by vicb** [comment]
Is this still an issue ?

**Comment by vicb** [comment]
Seems like it's no more. Please re-open if still an issue

**Comment by hgoebl** [comment]
We have this problem. Unfortunately our routing is quite complicated and I haven't got a Plunkr.

For me it seams like `route.snapshot._lastPathIndex` is not always calculated correctly.

The last track before getting lost is `recognize.ts`

```
const snapshot = new ActivatedRouteSnapshot(
    consumedSegments, parameters, Object.freeze(this.urlTree.queryParams),
    this.urlTree.fragment, getData(route), outlet, route.component, route,
    getSourceSegmentGroup(rawSegment), getPathIndexShift(rawSegment) + consumedSegments.length,
    getResolve(route));
```

I suppose in certain conditions the expression `getPathIndexShift(rawSegment) + consumedSegments.length` evaluates to a value which is 1 more than it should be.

Our project has really a lot of `Route` definitions having `path: ""`. Maybe above expression is counting something which not not be counted.

I'm sorry, but I don't see me in a position to better contribute to this problem.

The workaround with `router.navigate(['', {foo: 'bar'}])` doesn't work, because the first part is eliminated by `normalize...`.

We'll change from matrix parameter to path parameter as a workaround, or maybe queryParams.

**Comment by DzmitryShylovich** [comment]
@hgoebl thx, but it's very hard to do something without reproduction

**Comment by hgoebl** [comment]
@DzmitryShylovich you're right.

But maybe somebody with insight knowledge could have a few on `getPathIndexShift(rawSegment)`. I suppose this method has a bug (without knowing what exactly it does). With some luck sometimes bugs can be found by just reading the code.

**Comment by chpasha** [comment]
this is still an issue, trying to reload current route with different matrix parameters and having no mandatory params 
`this.router.navigate(["./", {foo: 'bar'}], {relativeTo: this.route})`
causes Cannot read property 'path' of undefined

**Comment by DzmitryShylovich** [comment]
@chpasha can u reproduce in plunkr?

**Comment by Andrey-Pavlov** [comment]
@chpasha  @DzmitryShylovich 
I've found workaround. **Two dots.**

All this  - **works**
```
this.router.navigate(['..', options], {relativeTo: this.route});
this.router.navigate(['../', options], {relativeTo: this.route});
this.router.navigate(['../////<unlimited>///////', options], {relativeTo: this.route});
```

**Comment by dpalita** [comment]
@Andrey-Pavlov I ran into the exact same problem (converting existing routes to lazy-loaded ones), you helped me pinpoint it.
It seems like you can't put matrix parameters on a lazy-loaded route that has an emtpy path ('').
I worked around it with (adapted to your example) ...
```
export const routes = [
    { path:'', redirectTo: 'test', pathMatch: 'full'},
    { path: 'test', component: TestComponent }
];
```
... and now it does work. 
I don't mind the extra path, but it might not be very meaningful in some situations.

**Comment by gmfun** [comment]
https://plnkr.co/edit/ER9grtq3kipfvJYP8nRC?p=preview
here is a plunkr @DzmitryShylovich 
Click on test on the top nav.. It would open CrisisListComponent which has a link 
`<a [routerLink]="['./', {}]">live</a>`.
It works if the link is `<a [routerLink]="['./']">live</a>`

**Comment by raphaelluchini** [comment]
I'm having this issue too when I have children routes and same path as '' and send parameters, for exemple:

```
export const routes = [
    { path:'', component: MainComponent, children: [{
                path: '', component: ChildComponent,
         }]
    }
];
```

``<a [routerLink]="['./', {queryParams: {param:'value'}]">Link</a>``

**Comment by lazarljubenovic** [comment]
This is still an issue. Any workarounds?

**Comment by mathiasslawik** [comment]
We're also seeing the same issue when using components with empty paths (e.g., "list" components) and using matrix parameters to represent the selected item through [routerLink], e.g., "['.', {id: entry.id}]".

**Comment by uvv001** [comment]
same issue https://github.com/angular/angular/issues/22643
