### ISSUE TITLE
Change detection stops working when using timers in web workers

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#10256]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am reopening https://github.com/angular/angular/issues/9201 since this is still reproducible.
In the plunker the UI is updated based on a timer. It's essentially a clock component where the current time is displayed based on timer ticks.

My observation is that the UI will update for several iterations - in some cases for 30-60 seconds, but after a while the UI will stop updating. 
This is only reproducible when running in a web worker.

**Expected/desired behavior**
I would expect the timer to not stop updating the UI for as long as the application is running

**Reproduction of the problem**
http://plnkr.co/edit/7ycV3GzAqXmvpyOMTKIl?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

* Mac user
 
This issue is specific to Chrome beta 52. Other browsers I've tried have been ok

**Comment by vicb** [comment]
> This issue is specific to Chrome beta 52. Other browsers I've tried have been ok

This is probably a Chrome bug - could you please try to reproduce not using Angular ?

Thanks

**Comment by Pablo-Ivan** [comment]
You little renacuajo. So you have time to answer Chrome questions but not questions on your product itself? I will incinerate you!

**Comment by thelgevold** [comment]
Yeah it is probably a Chrome bug.

@robwormald showed me an interesting workaround.
For some weird reason it appears that adding a button tag with a handler fixes it 

```<button (click)="null"></button>```
