### ISSUE TITLE
Compiler does not support selectors with multiple attributes

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#1025]
Currently, the compiler will not match `input[type=text][control]` with  `<input type=text control=one>`, but it should.

**Comment by pkozlowski-opensource** [comment]
@mlaval is saying that it seems to work under test, let's add one to see.

**Comment by mlaval** [comment]
Here are the tests which are passing successfully:
https://github.com/mlaval/angular/commit/c1d6cfb23c15418eb2070a077faea769a7d1bd47

@vsavkin Can you please clarify the issue?

**Comment by pkozlowski-opensource** [comment]
@mlaval maybe open a PR with those tests so we've got them for the future?

**Comment by mlaval** [comment]
Done with #1117
