### ISSUE TITLE
expose pathMatch and pathMatchAfterRedirects

### ISSUE THREAD

**Issue by agalazis** [angular/angular#10259]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no way to retrieve the current path in the form of unreplaced parameters in the from something/:id/somethingelse. There exist a ton of ways to get the replaced version eg. something/1/somethingelse . 
**Expected/desired behavior**
IMO  it is important to have access to the matched path as it gives you the option to identify where you are in the application independently of path parameters.

**Reproduction of the problem**
 Currently it can only be used for debugging purposes:
https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/router/src/router_state.ts#L182

**What is the expected behavior?**
I should be able to check which path from router config was matched independently of the parameters
Convenient way to expose it:
- Privde path match to navigation end event

```
this._router.events.subscribe( (e)=> {
  if(e instanceof NavigationEnd){
    console.log(e.url)
    console.log(e.urlAfterRedirects)
    console.log(e.pathMatch)
    console.log(e.pathMatchAfterRedirects)
  }
})
```

**What is the motivation / use case for changing the  behaviour?**
Being able to add behaviour based on path-matching in a component (In my case navbar)

**Please tell us about your environment:**
centos 6
- **Angular version:** 2.0.0-rc.4 router v3
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by jrolheiser-va** [comment]
Have you been able to find a work around for this at all? I'm trying to figure out how to do this from a service in the least hacky way possible. Because of https://github.com/angular/angular/issues/11023 I can't use an `ActivatedRoute`. I have a subscription setup to listen for `NavigationEnd` events, but I'd like to do something with the normalized matched route.
