### ISSUE TITLE
Template tag with service variable isn't updated when service variable changes

### ISSUE THREAD

**Issue by PiusNyakoojo** [angular/angular#10255]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Template tag (that contains service variable) isn't updated when service variable changes

**Expected/desired behavior**
Template tag updates from service variable

**Reproduction of the problem**
http://plnkr.co/edit/HxGUgJrvsK2bzgnAqSYH?p=info

**What is the expected behavior?**
I expect service variables to be updated in the template of components that use those services. Please refer to example below for more details.

**What is the motivation / use case for changing the behavior?**

My goal is to have a service that contains the relevant variables and functions that animate a page when navigating to a certain path.

For example, when the user enters my site, they are brought to the About page. The content on the About page slides in from bottom to top. When the user navigates to the Portfolio page (for example), the About page content slides out from top to bottom and the Portfolio page slides in from the bottom to the top.

My issue is that in order to do this, I have to create the variable (for when to animate in and away) inside each of my pages that I want to animate in this manner.

Let's call this variable "animateAway: boolean". Instead of having this variable in the service that I create, I have to place it as part of the class for each component that will use this feature.

My expected behavior is that 

**Example**

**main.ts**
```typescript
// add the AnimationService to bootstrap..
```

**animation.service.ts**
```typescript
// imports..
export class AnimationService {
    animateAway_fromService: boolean = false;
}
```

**about.component.ts**
```typescript
// imports..

@Component({
// other things..
    template: `
        <div [ngClass]="{animateIn: !animateAway, animateOut: animateAway }">
             // This works fine.. i.e. the classes are updated when animateAway is updated
        </div>
        <div [ngClass]="{animateIn: !this?.animService?.animateAway_fromService, animateOut: this?.animService?.animateAway_fromService}">
             // This works.. but only on the first call.. it isn't updated when animateAway_fromService is updated
        </div>
    `
})

export class AboutComponent {
    animateAway: boolean;

    constructor(private animService: AnimationService) {  }
}
```

**Code/Classes**
If you want a working example of this issue you can get the code from https://github.com/piusnyakoojo/personal-website

The animateIn and animateOut css classes are in the src/app/app.style.scss file.
The services are in src/app/shared/Services
And of course the about, portfolio, etc.. are in src/app/about, src/app/portfolio, etc..

**Version/Specification Details**

**Browser:** Chrome 52.0.2743.82 m

"dependencies": {
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/router": "3.0.0-alpha.8",
    "es6-shim": "0.35.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "angular-cli": "1.0.0-beta.9",
    "codelyzer": "0.0.20",
    "ember-cli-inject-live-reload": "1.4.0",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "protractor": "3.3.0",
    "ts-node": "0.5.5",
    "tslint": "3.11.0",
    "typescript": "1.8.10",
    "typings": "0.8.1"
  }

**Comment by vicb** [comment]
It should work provided the change detection is triggered when the variable is updated (ie updated as a result of an async call).

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
