### ISSUE TITLE
ngModel two-way binding.

### ISSUE THREAD

**Issue by Pablo-Ivan** [angular/angular#10257]
So I have a question conscerning multicomponent binding, refer it [here](https://hashnode.com/post/how-to-bind-ngmodel-value-across-components-ciqzr5o4v095boh538c6ycypg).

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by Pablo-Ivan** [comment]
Oh, thanks!
