### ISSUE TITLE
angular2 Only support at most 9 interpolation values!

### ISSUE THREAD

**Issue by asvifi85** [angular/angular#10254]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
```

**Current behavior**
When I am trying to interpolate more than 9 properties of an object in template I am getting the following error:
Error: Uncaught (in promise): Template parse errors:
Only support at most 9 interpolation values!

**Expected/desired behavior**
It should be able to print any number of properties of an object

**Reproduction of the problem**
The issue could be reproduced at : 
http://plnkr.co/edit/3M7lw6U4RAuOPacM4rmj?p=preview

**What is the expected behavior?**
It should be able to interpolate any number of properties of an object

**What is the motivation / use case for changing the behavior?**
I am unable to print all details details of users

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc4
 
* **Browser:** all 
 
* **Language:** Typescript

**Comment by pkozlowski-opensource** [comment]
Same as #10253
