### ISSUE TITLE
@angular/router new release

### ISSUE THREAD

**Issue by onhate** [angular/angular#10263]
**I'm submitting a ...**
```
[X] feature request
```
Is there any plan to relase a new @angular/router version on npm with the latest fixes?

**Current behavior**
[State changes not reflected in Safari + IE11](https://github.com/angular/angular/issues/10199)

**Expected/desired behavior**
[fix(router): back button does not work in IE11 and Safari](https://github.com/angular/angular/pull/10096)

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [IE XX | Safari XX | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript]

**Comment by ericmartinezr** [comment]
Yes, you have to wait.

**Comment by onhate** [comment]
Thanks @ericmartinezr
