### ISSUE TITLE
Angular 2 Mobile Gestures Block Vertical Scroll 

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#10261]
Mobile gestures blocks vertical scroll on the page.

For example I have the below div:

```
<div (swipeleft)="onSwipeLeft()" (swiperight)="onSwipeRight()">
contents....
</div>
```

When I swipe left or swipe right, its works properly, but has a problem with the pages that have long contents it doesn't allows vertical scroll on such pages.

**Comment by vicb** [comment]
Please reopen providing the requested information

**Comment by naveedahmed1** [comment]
Can you please elaborate which requested information?

**Comment by zoechi** [comment]
If you create a new issue you get a template that requests several things. One is a Plunker to reproduce.
