### ISSUE TITLE
Url value not able get in other component in angular 2.0.0-rc.1

### ISSUE THREAD

**Issue by krushnachandra** [angular/angular#10269]
http://localhost:5555/dashboard

Currently I am in dashboard component. In view I have a grid that will having link button will move to another component  city component. So I need to pass state id dynamically from view.

http://localhost:5555/dashboard/states/1/cities
http://localhost:5555/dashboard/states/2/cities
http://localhost:5555/dashboard/states/3/cities

I am trying with this code in my component in angular 2.0.0-rc.1

 export class CityComponent {
       public cities:Object;
       public  urlPath:string;
       constructor(private _cityService: CityService) {
                this.getCities();
              this.urlPath= location.pathname;
          //here i need to get the cityId
	 }

  getCities() {
    this._cityService.getCities().subscribe(
      data => { this.cities = data},
      err => { this.countries_error = true }
   );
  }
}

This is giving me dashboard url http://localhost:5555/dashboard not  city url http://localhost:5555/dashboard/states/3/cities

Any Help......

**Comment by brandonroberts** [comment]
Are you using the latest router? The RC router has been superseded by the V3 router and will no longer be developed.

**Comment by zoechi** [comment]
Also posted at http://stackoverflow.com/questions/38570679/url-value-not-able-get-in-other-component-in-angular-2-0-0-rc-1

**Comment by pkozlowski-opensource** [comment]
Since this is a support question and we've got a SO question already I don't see any point in keeping this issue open. Thnx @brandonroberts and @zoechi for helping out with the issues!

**Comment by krushnachandra** [comment]
So can you please suggest me how can i achieve this its very urgent for me i am trying from last 3 days

Like in angualr 1 we have fromstate and tostate  i need to state value in in my component
