### ISSUE TITLE
Browser does not refresh correctly

### ISSUE THREAD

**Issue by sam-wheat** [angular/angular#10260]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After navigating to a route refreshing the browser results in page not found or file index on root dir.

**Expected/desired behavior**
Page refreshes correctly

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

See also:  https://github.com/angular/angular/issues/10239

I've been all over the map trying to chase this down and I have posted questions about items which in hindsight were red herrings.  Having been duped a couple times I hesitate to speculate on the nature of this issue execept to say there is a possiblity it is of my own doing.  If that is the case I apoligize and ask that you point me in the right direction on how to fix it.  
Note in my development project I use two different root pages for my site: index.html for webpack/production and debug.html for systemjs/development.  

Steps to reproduce:
Download code from https://github.com/sam-wheat/ngRouter3
From node command window run the following:
npm install
npm run-script copyfiles  // When prompted if /lib a directory press "d".

Start web server:
lite: npm start from node window
kestral:  F5 from visual studio 2015

From the browser click one of the links on the home page then press F5. Note request for index.html which returns 404.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
See package.json
* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
Observied in IE 11, Chrome, FF
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
Typescript

**Comment by zoechi** [comment]
Sounds like http://stackoverflow.com/questions/31415052/angular-2-0-router-not-working-on-reloading-the-browser

**Comment by sam-wheat** [comment]
Answer to cited question refers to html5 routing - I am using HashLocation..
Note bs-config.json file in my submitted code as well as launchsettings.json.

**Comment by pkozlowski-opensource** [comment]
@sam-wheat it is next to impossible to diagnose what is going on based just on the information provided. Please try to isolate the issue and reproduce it in a plunker or similar. I'm afraid that we can't debug entire projects....

**Comment by sam-wheat** [comment]
Did you even look at the project I provided? 
Did you run the two (2) commands required to install it?  
Is one mouse click and one keystroke too time consuming of a debugging process?
Are any of the packages I've installed in any way non-standard or something that a typical developer would not use?
Are any of the install/debugging processes unusual, complex, or ambiguous?
Are my instructions on  how to reproduce the problem in any way unclear?
Please show the courtesy of attempting to resolve this issue.   The information I've provided for you is available for all too see.

**Comment by zoechi** [comment]
I actually think checking out some GitHub repo locally is too time consuming. Why would anyone load a bunch of files of a foreigner onto the local disk anyway. 
There are usually several people involved where each one would have to do this to verify, triage, reproduce, ...
There are quite a few from the community that try to figure out if it is actually a bug or just missing knowledge how to do it properly,  to allow core Angular developers can keep developing cool stuff instead of answering support requests. Each one would have to check out your repo in order to be able to run it and to be able to debug and investigate.

Are you aware of the size of the Angular2 community and how many bug reports are actually support requests. Its a lot of work to get the good reports separated from the bad.
Angular2 is a free product and if you want it customized to better fit your requirements, a bug report that makes it as easy as possible for the Angular team to work with should be feasible.

A plunker that only contains the code necessary to reproduce the issue is a great indicator that the report is a serious bug report instead of a support request and usually gets more attention which often leads to faster fixes. Decide yourself ;-)

Besides that bug reports are highly welcome, because the whole community benefits from fixed bugs and improved quality of the project.

I'm not an Angular team member.

**Comment by sam-wheat** [comment]
Well you have a point about downloading files from GitHub but it seems to the way to exchange files now so that is where I put them.  As far as it being too time consuming and all the other drama you are talking to the wrong person because I do this all day long.  Truthfully I don't mean  to be rude by calling your points drama but that is exactly what they  are so lets just call it what it is.  As for customizations I think you may have replied to the  wrong issue (??).  
I will again post the specific questions I poised to pkozlowski.  If you wish to go on about how time consuming of a request this is, please also provide answers to my questions.

Did you even look at the project I provided? 
Did you run the two (2) commands required to install it?
Is one mouse click and one keystroke too time consuming of a debugging process?
 Are any of the packages I've installed in any way non-standard or something that a typical developer would not use?
 Are any of the install/debugging processes unusual, complex, or ambiguous?
 Are my instructions on how to reproduce the problem in any way unclear?
 
For the record one of the reasons I posted the project as I did is that I wanted to provide my development environment as it may be required to reproduce the  issue.  I don't know.  

This may be a support request in the end but if that is case I am sorry (as I stated in my question).  Hopefully this will provide value for  the next guy who makes the same mistake I did.  Note that I referenced similar questions posted on StackOverflow that were at the time unanswered.

**Comment by sam-wheat** [comment]
To provide some factual info:  I followed my own instructions and started the process at 8:09 am and observed the reported behavior at 8:17.  Almost all of that time was spent waiting for the painfully slow wireless at the building I'm in.  I did not record the time I actually spent typing but I suspect it was in the area of three to four minutes.

**Comment by vicb** [comment]
> Note that I referenced similar questions posted on StackOverflow that were at the time unanswered

You are right, SO is the best place for asking support.

**Comment by sirajc** [comment]
The page refresh works for me and many others so this issue at instant sounds like support query.
Reproduce in plunker and we will be happy to help. Also if it takes 4 mins to type , y don't u type that in plunker and help us look at this issue a bit seriously

**Comment by sam-wheat** [comment]
Thank you sirajc but at this point I'm going to let it go.  I will finish up my current project in Angular and than move my attention to React.  At least I wont be bugging you with support requests anymore :)
Thanks again.
