### ISSUE TITLE
how to reload/refresh the component view forcefully? 

### ISSUE THREAD

**Issue by snkrishnan1** [angular/angular#10270]
in my application I have a json object which is hardcoded. that values are bound with the input controls in the view. but if i changes the values of the json object during/based on some events, then those changes values are not getting reflected in the view/input controls? how do i forcefully reload/refresh the view?

please look the component below. In that the values which i have assigned inside the constructor gets reflected in the view during the load of the component.
based on some events on the parent component, the method LoadExtractorQueueDetails is called and the same variable this.sampleData is being set with some other values.
ideally i expect these values to be reflected in the view? but this doesn't seem to happen? 
why it is not happening? how do i reload/refresh the views ?

`import { Component, Input, OnInit } from '@angular/core'
import { FORM_DIRECTIVES } from '@angular/common';

@Component({
    selector: 'extractorQueueDetails',
    directives: [FORM_DIRECTIVES],
    templateUrl: './HTML/Admin/ExtractorQueueDetails.html'
})
export class ExtractorQueueDetails {
  
    resultData: ExtractorQueueItem;
    sampleData: Sample;
 
    constructor() {
        console.log("ExtractorQueueDetails component is loaded");
   
        this.sampleData = { queueId: 123, name: "Krishnan" };
     }
	public LoadExtractorQueueDetails() {
		this.sampleData = { queueId: 456, name: "Krishnan123" };
	}
}`
	 
My HTML template is like below
`   <input type="text" name="txtQueueID" class="form-control" id="txtQueueID" [(ngModel)]="sampleData.queueId" />
   <input type="text" name="Description"  class="form-control" [(ngModel)]="sampleData.name" id="Description" />`

**Comment by pkozlowski-opensource** [comment]
A support question already asked (and answered!) on the mailing list: https://groups.google.com/forum/#!topic/angular/9ZiHT4go7Pg

No need to duplicate, especially that this question doesn't belong here, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by ericmartinezr** [comment]
Too fast Pawel!!
