### ISSUE TITLE
Template Expression Parsing Breaks When Using ES2015 Object Literal Properties Shorthand

### ISSUE THREAD

**Issue by efreiberg** [angular/angular#10277]
**I'm submitting a ...**  (check one with "x")

```
[] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
HTML espression parsing throws an exception when using object literal shorthand syntax.  When attempting to use this syntax, I get the following error.

`<template [ngTemplateOutlet]="templateRef" [ngOutletContext]="{ item }"></template>`

Throws: 

`EXCEPTION: Template parse errors:
Parser Error: Missing expected : at column 8 in [{ item }] in App@4:47 ("
      <h2>{{_item}}</h2>
    </template>
    <template [ngTemplateOutlet]="templateRef" [ERROR ->][ngOutletContext]="{ item }"></template>
  "): App@4:47
VM9574 platform-browser.umd.js:1900 EXCEPTION: Template parse errors:
Parser Error: Missing expected : at column 8 in [{ item }] in App@4:47 ("
      <h2>{{_item}}</h2>
    </template>
    <template [ngTemplateOutlet]="templateRef" [ERROR ->][ngOutletContext]="{ item }"></template>
  "): App@4:47BrowserDomAdapter.logError @ VM9574 platform-browser.umd.js:1900BrowserDomAdapter.logGroup @ VM9574 platform-browser.umd.js:1910ExceptionHandler.call @ VM9573 core.umd.js:4329(anonymous function) @ VM9573 core.umd.js:9844ZoneDelegate.invoke @ VM9533 zone.js:323onInvoke @ VM9573 core.umd.js:9100ZoneDelegate.invoke @ VM9533 zone.js:322Zone.run @ VM9533 zone.js:216(anonymous function) @ VM9533 zone.js:571ZoneDelegate.invokeTask @ VM9533 zone.js:356onInvokeTask @ VM9573 core.umd.js:9091ZoneDelegate.invokeTask @ VM9533 zone.js:355Zone.runTask @ VM9533 zone.js:256drainMicroTaskQueue @ VM9533 zone.js:474ZoneTask.invoke @ VM9533 zone.js:426
...
`

**Expected/desired behavior**
Object literal shorthand parsing is supported. Ex. { foo } is equivalent to { foo: foo }.  

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

https://plnkr.co/edit/J89FfkINlII9t3gaHG7J

**What is the motivation / use case for changing the behavior?**
This is valid object literal syntax, currently supported by transpilers and natively by evergreen browsers(Minus IE 10/11 and Safari 8).

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** Chrome 51.0.2704.106
- **Language:** TypeScript 1.8.10

**Other Information**
In `@angular/compiler/expression_parser`, the
parseLiteralMap() method of the _ParseAST class doesn't handle the literal shorthand syntax.

**Comment by zoechi** [comment]
Binding syntax isn't supposed to support full ESx syntax. There are several other things that are not supported.

**Comment by vicb** [comment]
It should not be too hard to add but don't expect this before or in 2.0

**Comment by funkizer** [comment]
Hi, was this forgotten / ever coming? I know it's a very minor thing, but anything that makes writing templates even a bit cleaner is for the good.  :)
