### ISSUE TITLE
Only OnDestroy lifecycle hook fires for Pipes

### ISSUE THREAD

**Issue by mattschlitz** [angular/angular#10279]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Only OnDestroy lifecycle hook fires for Pipes

**Expected/desired behavior**
OnInit fires (and maybe other hooks?)

**Reproduction of the problem**
http://plnkr.co/edit/DBaLGrPzodtaHfDccmlz?p=preview
(Review console.log after toggling)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome 51.0
 
* **Language:** TypeScript 1.9

**Comment by fknop** [comment]
I think it is the intended behavior. A pipe has no @Input property. It does not need ngOnChanges or ngOnInit.

**Comment by RoopeHakulinen** [comment]
@mattschlitz Do you have some use case for some other lifecycle hook? The documentation for lifecycle hooks states for `ngOnInit`: 

> Initialize the directive/component after Angular initializes the data-bound input properties.

and since there can't be any inputs, what is the point of the `ngOnInit` hook?

**Comment by mattschlitz** [comment]
This may be a fundamental misunderstanding of angular on my part so feel free to correct what I have wrong. This is what I thought happened:

There are multiple phases to the rendering process, the first of which is constructing a tree based off of the template and the second of which is initializing each node of that tree that will be rendered. The constructor is used in the first phase and the `ngOnInit` hook is used in the second phase. If this is the case, then it would generally be a good idea to not load data that is strictly used by the pipe until the `ngOnInit` hook is called.

As long as `ngOnDestroy` continues to work so I can do cleanup, I can deal with putting the data loading logic into the constructor. However, I do think that the fact that `ngOnDestroy` is the only lifecycle hook that is supported by pipes should be documented in the developer guide if that is the intention. The only reason I found out that `ngOnDestroy` works in the first place was by looking at the source for `AsyncPipe` when trying to write a pipe that has a subscription associated with it. I don't know who I would talk to about changing that but, if someone could either add that or tell me where to go to get it added, I think the community would benefit from that question being answered.

**Comment by fknop** [comment]
I think it's not really a good idea at all to do data loading in a pipe. A pipe is more for data manipulation. You pass your data in, and something comes out. You can do stateful pipes but I think it's a better practice to keep it stateless.

If you absolutely have to do data loading in the pipe, you should do it in the constructor.

And for the lifecycle:

* The component is created
* Inputs are bound
* ngOnInit is called

**Comment by mattschlitz** [comment]
For my purposes, which is localization, it's somewhat unavoidable that localization data needs to be loaded before data is displayed. 

It's understandable that the desire is for pipes to be stateless as much as possible but I'm at somewhat of a loss as to how it could be accomplished without forcing the application to wait until every localization file is loaded or forcing the application to reload any time someone decides to change their locale, which isn't completely unreasonable but seems like it should be unnecessary.

Any ideas as to updating the documentation? Should I create a separate "Issue" for that?

**Comment by fknop** [comment]
Yes, I have the same use case. In that case, you can have a "stateful" pipe. I use a service which load the translations. I inject it in my pipe and I do `Service#getObservable` which gives me an observable for my translation. When the value change, you call the `markForCheck` of the  `ChangeDetector` and it should work.

I don't need to use the constructor of the pipe except for injecting the `ChangeDetectorRef` and my service.


> I'm at somewhat of a loss as to how it could be accomplished without forcing the application to wait until every localization file is loaded or forcing the application to reload any time someone decides to change their locale, which isn't completely unreasonable but seems like it should be unnecessary.


Note that this is almost the approach that Angular has chosen for the i18n if it didn't change since I read the design docs a few months ago.

**Comment by mattschlitz** [comment]
Yes, I have mimicked the way `AsyncPipe` works in order to get change detection to work. At some point, you must need to subscribe to that observable. Would you suggest doing that in the `constructor` or the `transform`? It looks like the route that has been chosen for the `AsyncPipe` is to perform the subscription in the `transform` so maybe, in some way, `transform` is taking the place of an initialization step?

I can't imagine how the approach that is being suggested by the current i18n pipes could be sustainable. I suppose if you moved the localization information into a separate constants file when you build your application, it could be doable for a small application but, for larger scale applications that translate into multiple languages, bundling the constants in would make the file size explode. You could `require` in the information as a separate script but, either way, you will be blocking until all of the constants for all of the languages are downloaded. Or, maybe, when you build the application, it could be injected directly into the application as smaller chunks of `require`d constants so that each component makes an HTTP request to load a smaller list of tokens? 

I know this is a bit off-topic but I would love to use the i18n that's already built into angular but I'm concerned it's not extensible.

**Comment by fknop** [comment]
If your input changes, do it in the transform but make sure you're cleaning the subscription for every change detection. Otherwise do it in the constructor.

**Comment by pkozlowski-opensource** [comment]
i18n is still in the works so if you want to go down the route of using pipes for translations the best suggestion comes from @fknop here:

>  In that case, you can have a "stateful" pipe. I use a service which load the translations. I inject it in my pipe and I do Service#getObservable which gives me an observable for my translation.

**Comment by TeodorKolev** [comment]
So many comments and issue still persists
