### ISSUE TITLE
[formControlName] doesn't work with CKEditor

### ISSUE THREAD

**Issue by keyiis** [angular/angular#10288]
I uesed Formgroup with CKEditor to create the forms dynamically,
but Validators.required not work  when I type something in editor.
Is it ckeditor prevents the spread of textarea value change events?
or
Formgroup  Validators can't monitor ckeditor change textarea value?

[(ngModel)] has same problem.

Maybe ckeditor set style display:none to  textarea that angular can't find textarea?

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by kara** [comment]
Closing because this is a support request, but please feel free to open an issue if you find a bug in Angular itself.
