### ISSUE TITLE
RC5 - Validation tasks for the @NgModules proposal

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#10282]
- [ ] Periscope reference app (@matsko) 
- [ ] Mission Control reference app (@stephenfluin)
- [ ] Ionic (@adamdbradley)
- [ ] Angular Material (@jelbourn)
- [ ] Developer Docs - All Doc tests pass and content to explain NgModules (@wardbell) 
- [ ] Synced into g3 and internal projects are green (@alxhub)

Please fill in status in comments. Assigning to @bradlygreen for final signoff.

**Comment by vicb** [comment]
obsolete
