### ISSUE TITLE
Invalid argument '2500' for pipe 'CurrencyPipe' - Strings not allowed

### ISSUE THREAD

**Issue by ChristopherHoffman** [angular/angular#10285]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When binding a model from an <input> with type of "range", that model throws an error:
Invalid argument '2494' for pipe 'CurrencyPipe'

This is due to the input field being looked at as a string, which the CurrencyPipe does not allow.

**Expected/desired behavior**
Strings which can be converted safely into a number should be able to be used with a currency pipe.

**Reproduction of the problem**
Bind a range input, and use the CurrencyPipe on it.
https://plnkr.co/edit/uS47YR1Pch3d7FVts4h6?p=preview

**What is the motivation / use case for changing the behavior?**
Currency pipes can correctly used with the range and text <input> tags, and will follow the same behavior as was recently added to the DecimalPipe (https://github.com/angular/angular/issues/10159)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript]

**Comment by vicb** [comment]
As far as I remember the fix also applies for the currency pipe. However it's probably not release in a RC. Could you please check the change log and close this PR if this is the case. It should be fixed in the next RC. Thanks (I have limited network access until Wednesday)

**Comment by RoopeHakulinen** [comment]
@vicb you seem to be right about the both. 

It is affected (and probably fixed) by your [PR](https://github.com/angular/angular/pull/10163/files) where you fix the common function `formatNumber` used also by the `currency` pipe.

Since the PR is only merged 7 days ago, it obviously isn't in the RC4 yet, but will be in the RC5. RC5 isn't going to be released this week, though.
