### ISSUE TITLE
Using parenthesis in parameters throws an exception in RC4

### ISSUE THREAD

**Issue by felipedrumond** [angular/angular#10280]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When trying to access a route using parameters that contain parenthesis, the application throws an exception: Error: Uncaught (in promise): Error: Cannot match any routes: '724,692'

When accessing **http://localhost:5000/abajur;f=(724,692)**, the application throws the above mentioned exception. 

On the other hand, **http://localhost:5000/abajur;f=724,692** runs as expected.

**Expected/desired behavior**
Route parameters should be allowed to contain parenthesis. 

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
As per  [RFC 3986 ](https://tools.ietf.org/html/rfc3986), (see Section 2: Characters) may contain any of the following characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=. Any other character needs to be encoded with the percent-encoding (%hh). 

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc. and "@angular/router": "3.0.0-beta.2",
- **Browser:** [all | Chrome 51  ] 
- **Language:** [all | TypeScript 1.8 | ES6/7 | ES5 | Dart]

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/4895 where you already commented. It is still open.

**Comment by alexeagle** [comment]
thanks @ericmartinezr

**Comment by ocombe** [comment]
Can you reopen this one please @alexeagle ? @vicb just closed the other issue

**Comment by felipedrumond** [comment]
What would be the url when using the router to navigate? 

If I use 
<a [routerLink]="['/test', { f: '[724,692]' }]"></a>
the target url is **/test;f=[724,692]** (fine)

But if I navigate using this.router.navigate (code bellow), the target url is **/test?f=[724,692]** (it seems wrong)

```
var rote = '/';
var params = {
            f:  this.criarParametroDeFiltrosDeCategoria(),
            fv: this.criarParametroDeFiltrosValor(),
            o:  this.criarParametroOrdem(),
            pg: this.pagina,
        };

        var navigationExtras = { queryParams: params };
        this.router.navigate([rote], navigationExtras);
```
Reading angular documentation on [https://angular.io/docs/ts/latest/guide/router.html](https://angular.io/docs/ts/latest/guide/router.html), I could find what is the expected target url .

**Comment by reach4thelasers** [comment]
I'm having a similar issue with route params.  I'm passing as a parameter a Forex currency code.  E.g. "USD/GBP" - this is being passed to the router un-encoded and so it tries to route to /routename/USD/GBP

**Comment by wulfsberg** [comment]
I definitely second this, and consider it quite high priority. If I send an arbitrary string in a routerLink, it should arrive as parameter in the route component, without caveats.
Otherwise, it is impossible to reliably use route parameters for any kind of user-supplied data, which severely cripples the potential use cases for the router.

**Comment by wardbell** [comment]
Looking into it. Stay tuned.

**Comment by dchacke** [comment]
I am having the same problem, and it's also a security issue in the case of user supplied data as it will break routes, so I'm thinking this should be treated with a bit more urgency. Any progress on this?

To speed things up, I *think* that one could change the `encode` function in `modules/@angular/router/src/url_tree.ts:344` to:

```typescript
export function encode(s: string): string {
  return encodeURIComponent(s).replace(/[!'()*]/g, (c) => {
    // Also encode !, ', (, ), and *
    return '%' + c.charCodeAt(0).toString(16);
  });
}
```

I hope this is the right place in the code! It may also be needed for query params. Essentially, you want to be looking for

```html
<a [routerLink]="['foo', '(bar)']"></a>
```

to be turned into

```html
<a href="/foo/%2528bar%2529"></a>
```

The reasoning for this is explained [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#Description) (see last paragraph in the section called "Description").

I was going to submit a PR for this, but [this legal nonsense](https://cla.developers.google.com/about/google-individual?csw=1) ruined it for me.

For anyone needing a workaround, use the following pipe:

```typescript
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'encodeURIComponent'
})

export class EncodeUriComponentPipe implements PipeTransform {
  transform(uriComponent: string): string {
    return encodeURIComponent(uriComponent).replace(/[!'()*]/g, (c) => {
      // Also encode !, ', (, ), and *
      return '%' + c.charCodeAt(0).toString(16);
    });
  }
}
```

and then

```html
<a [routerLink]="['foo', ('(bar)' | encodeURIComponent)]">your link</a>
```

That fixes it for me, but it would be nice to see this adopted in Angular (if this is the correct solution, that is, as I may well be wrong).

**Comment by Romstar** [comment]
This is really a show stopper when attempting to utilize the URI for state, e.g. example.com/(sessionid) => www.example.com/ Cannot match any routes: 'sessionid' (it removes the parenthesis from the error).  Any ETA would be very helpful to at least notify my manager of this issue.

**Comment by felipedrumond** [comment]
What I started doing is using [ and ] instead of ( and ). The problem now is that release version encodes the url.

**Comment by linglun3** [comment]
[Issue 12436](https://github.com/angular/angular/issues/12436) may be helpful for this.

**Comment by vicb** [comment]
`( & )` are used for matrix params, you need to urlencode them if you need to use them.

**Comment by wulfsberg** [comment]
That makes sense, but the problem is then with routerLink, which does not encode parenthesis, but _do_ encode other special characters (including %).
So it results in a double encoding if we manually encode the parenthesis before using them as parameters in a routerLink, or a broken route if we don't.

**Comment by achimha** [comment]
I have ran into this bug as well. The router cannot parse URLs with a matrix parameter containing `(` or `)` in its value. Replacing them with `%28` and `%29` respectively fixes the problem invoking the application but when navigating inside the application and setting such a parameter, the characters remain unquoted.

I find this rather problematic because I couldn't come up with a good workaround. As soon as the `(` etc. appears in the browser's URL bar, I have a link that cannot be copied and pasted.

**Comment by ribizli** [comment]
I've tried a really wild solution as I read the comment from @dchacke.

As a workaround what about patching encodeURIComponent?
```typescript
const encode = encodeURIComponent;
window['encodeURIComponent'] = (component: string) => {
  return encode(component).replace(/[!'()*]/g, (c) => {
    // Also encode !, ', (, ), and *
    return '%' + c.charCodeAt(0).toString(16);
  });
}
```
It seems working for me, but I cannot predict the side effects of patching a global function.

**Comment by ribizli** [comment]
How can we urge the fix of this issue? It is really a small thing, what @weltschmerz1 already mentioned.

**Comment by mbn18** [comment]
@ribizli 
To what file you added the suggested code?

**Comment by ribizli** [comment]
@mbn18 e.g. in main.ts, it monkey patches the `window.encodeURIComponent` method. You just need to let this code run before any routing happens, best before Angular's bootstrap.
Until know I haven't found any side effect of the patching, encoding URL-allowed characters too doesn't affect decoding.

**Comment by mbn18** [comment]
@ribizli , thx. It didnt worked for me. Maybe because my build is mixed with webpack and universal.
I will upgrade Angular to v4 so I hope this will solve the problem.
Mean while I configured Nginx to remove any () from the URL

**Comment by anthonydresser** [comment]
Is there any update on this issue? This is a serious problem when using angular within an electron app, since, at least on windows, '(' and ')' are valid to be apart of a system path, which is what window.location uses.

**Comment by centaure** [comment]
@mbn18, placing the patch of code (@ribizli suggested) in **typings.d.ts** worked for me [1]. I am using webpack. 

[1] It did not work when I placed it in main.ts

**Comment by centaure** [comment]
In order to allow parentheses in the url, I defined my own custom [URL serializer](https://angular.io/api/router/UrlSerializer) (also see suggestion [here](https://stackoverflow.com/questions/39541185/custom-encoding-for-urls-using-angular-2-router-using-a-sign-in-place-of-a-sp)):

    import { DefaultUrlSerializer, UrlSerializer, UrlTree } from '@angular/router';

    export default class CustomUrlSerializer implements UrlSerializer {
        private _defaultUrlSerializer: DefaultUrlSerializer = new DefaultUrlSerializer();

        parse(url: string): UrlTree {
           // Encode parentheses
           url = url.replace(/\(/g, '%28').replace(/\)/g, '%29');
           // Use the default serializer.
           return this._defaultUrlSerializer.parse(url)
        }

        serialize(tree: UrlTree): string {
           return this._defaultUrlSerializer.serialize(tree).replace(/%28/g, '(').replace(/%29/g, ')');
        }
    }

and I included CustomUrlSerializer in my providers array (within **AppModules**):

    providers: [
        { provide: UrlSerializer, useClass: CustomUrlSerializer },
        ...
    ]

**Comment by weltschmerz1** [comment]
Unsubscribing... I don't have high hopes these days that these issues are actually addressed at some point.

**Comment by MariMax** [comment]
this issue is really annoying when app has named outlets and routes with params which may have parentheses in the body. The most disappointing I have route like 
```
{path: '**', component: NotFoundPageComponent}
```
and app doesn't show this component, because of exception in the routing.

Thanks @centaure great solution

Any progress here?

**Comment by verydapeng** [comment]
any progress, what are we going to do with this?

**Comment by chanm003** [comment]
Monkey patching encodeUriComponent---how does that fix the issue?  

For instance, I may have anchors in my sidebar menu where parentheses are encoded properly as %28 and %29, but when the user clicks the links, Google Chrome will automatically replace %28 and %29 with open and closed parentheses respectively.  If the user bookmarks this page, they will get an error.

**Comment by chris13524** [comment]
Bump.

Any updates here? This is a big issue.

**Comment by jasonaden** [comment]
Notes/fix plan:

1. The URL in in the original issue above appears it should not work. The issue states that http://localhost:5000/abajur;f=(724,692) fails to match a route. However, http://localhost:5000/abajur;f= is a valid URL. Therefore if there's something in parenthesis it would get parsed as another route. What if the URL were instead  http://localhost:5000/abajur;f=(main:abc)? This would parse into two top-level `UrlSegmentGroups`.

Based on this, can we agree the URL above is invalid? And that a valid version of it would be: http://localhost:5000/abajur;f=%28main:abc%29

2. Parentheses (not encoded) in URL parameters and/or fragments should probably not cause errors (this should match current behavior).

3. Serializing a URL where params contain parens should serialize to the encoded version so refreshing and deep linking won't cause errors.

**Comment by wulfsberg** [comment]
Sounds reasonable to me. From what I can see, it is really just a matter of RouterLink erroneously letting unencoded parentheses through. Everything else seems to be by spec.

**Comment by MartinMa** [comment]
Why was the fix reverted in https://github.com/angular/angular/commit/a4032296cc1647cd2bac36d63304fadf60fea9d8?

**Comment by wulfsberg** [comment]
...and does the revert mean this issue should be re-opened?

**Comment by alexeagle** [comment]
Yes, thanks @wulfsberg - Jason is working to land it again.

**Comment by MartinMa** [comment]
Thanks @wulfsberg 👻

**Comment by jaj1014** [comment]
'While these changes are not considered breaking because applications should be decoding URLs and key/value pairs, it is possible that some unit tests will break if comparing hard-coded URLs in tests since that hard coded string will represent the old encoding. _Therefore we are releasing this fix in the upcoming Angular v6 rather than adding it to a patch for v5._'

Wondering why this statement was made to hold off until v6, but it was included in 5.2.8? Was this a mistake or am I understanding this wrong? 

Our app, which uses oidc-client-js, began failing yesterday until we reverted to 5.2.7 - in looking this morning at other comments/references for https://github.com/angular/angular/pull/22337 it appears it's breaking for others as well - of note is https://github.com/okta/okta-oidc-js/issues/140

**Comment by mgol** [comment]
It turns out encoded parens pose a problem for Firefox which decodes them when entering the URL, leading to an incorrect final URL. :( See https://bugzilla.mozilla.org/show_bug.cgi?id=1429786 for more details.

**Comment by Matmo10** [comment]
With this routing pattern: `path: 'items/:paramA/:paramB'` and this url: `localhost:4200/items/BA(p9)677/Something`, I get `Error: Cannot match any routes. URL Segment: 'p9'`. Even if I manually decode it to ``localhost:4200/items/BA%28p9%29677/Something`, I get the same error.

So this is fixed and will be released with the v6 release? Is it in any v6 betas?

**Comment by arangates** [comment]
https://github.com/angular/angular/issues/24921

**Comment by srinidhi-krishnan** [comment]
> `( & )` are used for matrix params, you need to urlencode them if you need to use them.

please explain hoe to encode '&' manually
