### ISSUE TITLE
router-outlet takes time to render the view

### ISSUE THREAD

**Issue by beckmeindia** [angular/angular#10296]
I have observed that while loading the page for the first time, the router-outlet takes time for the view to be rendered which is about (2-3 secs). 

I was thinking if I could show some elements during that time which would go once the view has been rendered. I know 2-3 seconds is not a great time problem, but the emptiness in the main-view is bad user experience. 

I have looked at angular-universal and I am looking for an alternate solution with maybe something like a *ngIf directive

Thanks.

**Comment by ericmartinezr** [comment]
???

See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by pkozlowski-opensource** [comment]
This is definitively not a bug report nor a feature request and is not actionable as-is. See our GitHub submission guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit
