### ISSUE TITLE
revise documant about CanActivate

### ISSUE THREAD

**Issue by amazingandyyy** [angular/angular#10291]
every canActivate in document, 
**canActivate** should be changed to "**CanActivate**"(capitalized)

for example: in sample code(crisis-center.routes.ts (guarded admin route) 
`{
  path: 'admin',
  component: CrisisAdminComponent,
  canActivate: [AuthGuard]
}`

should be 
`{
  path: 'admin',
  component: CrisisAdminComponent,
  CanActivate: [AuthGuard]
}`

or user will have log.erorr:
`EXCEPTION: Error: Uncaught (in promise): No provider for e!`

version @angular RC4 and Router 3.00-beta.2

**Comment by fknop** [comment]
It's `canActivate` not `CanActivate`. You just have to provide your guard in the providers array of the bootstrap.

**Comment by amazingandyyy** [comment]
I already import this two in the routes.ts

`import { LoginGuard } from '../shared/services/auth-guard.service';
import { CanActivate } from '@angular/router';
`

**Comment by ericmartinezr** [comment]
Your error is not there. Dont minify your code and you will see the full error. This is not a bug but a support question.

**Comment by amazingandyyy** [comment]
but when I comment out the` canActivate: [AuthGuard]`, no more errors.

**Comment by amazingandyyy** [comment]
can you help me with this?

this is my auth-guard file: https://github.com/amazingandyyy/yeah-ng2/blob/master/client/app/shared/services/auth-guard.service.ts

this is my route: https://github.com/amazingandyyy/yeah-ng2/blob/master/client/app/dashboard/dashboard.routes.ts

I want to add a loginGuard to my dashboard routes.

**Comment by fknop** [comment]
> You just have to provide your guard in the providers array of the bootstrap. Of course it will not produce any error with CanActivate because it's ignored by the router.

**Comment by amazingandyyy** [comment]
@fknop as this file https://github.com/amazingandyyy/yeah-ng2/blob/master/client/app/dashboard/dashboard.routes.ts

I already import guard. What I missed? thanks for helps

**Comment by ericmartinezr** [comment]
Go to Gitter or StackOverflow and provide a plnkr with your question.

**Comment by amazingandyyy** [comment]
Thank you. 

I fix the problem by adding my guard to the `appRouterProviders` in routes.tx file.

(https://angular.io/docs/ts/latest/guide/router.html)
