### ISSUE TITLE
Angular2, ngModel and Forms : list doesn't display correctly

### ISSUE THREAD

**Issue by FCourtine** [angular/angular#10294]
**I'm submitting a bug report**

**Current behavior**
I've got an array of item displayed in an input using ngModel. I use an ngFor directive inside a form with a basic control (required). The list doesn't display corrrectly : it's always the last item of the array which is displayed.
If i use mustache syntax to display the array outside the input, it's ok. If i remove the form and the control it's ok.

**Expected/desired behavior**
Correct display of the array with ngModel and forms.

**Reproduction of the problem**
You can test it in plunker : 
https://plnkr.co/edit/HVz0N2mfJMqzOv3gWaYH?p=preview

* **Angular version:** 2.0.0-rc.4
* **Forms version:** 0.2.0
 
* **Browser:** all 
* **Language:** ES6/7

**Comment by fknop** [comment]
You need to use `FormArray` for arrays of input. 

For example:

```typescript
this.personControl = this._formBuilder.group({
    persons: this._formBuilder.array(
          this.persons.map((person) => new FormControl(person.libelle), Validators.required)
    )
});
```

```html
<form [formGroup]="personControl">
  <div formArrayName="persons">
        
      <div *ngFor="let person of persons; let i = index">
            libelle : {{person.libelle}}<br/>
            index : {{i}}<br/>
            <input type="text" 
                   maxlength="30" 
                   [id]="person.id" 
                   [formControlName]="i"/>
      </div>
    </div>
</form>
```

You may want to keep the `FormArray` in a separate variable if you need to update it dynamically.

**Comment by FCourtine** [comment]
Hello,
I've tested your solution but it seemed to be that it doesn't work if you have many inputs in the loop: for example one input bind on person.libelle and an another input bond on person.value.
Beside, i want to keep ngModel on input just to do the double binding between view and model.
Somebody has an idea?
Thanks

**Comment by fknop** [comment]
Check this doc: https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub and the documentation on `angular.io`. Otherwise, ask on StackOverflow.

**Comment by FCourtine** [comment]
I've updated the plunker to show my problem (https://plnkr.co/edit/HVz0N2mfJMqzOv3gWaYH?p=preview).
I've a look to the documentation, but i can't find something about my problem (many inputs inside a loop with form and validation).

**Comment by FCourtine** [comment]
The problem is that the formControlName must be unique.
Here is a another plunker with the correction:
https://plnkr.co/edit/chiCdN5A7Vb4MCrAYaSE?p=info
