### ISSUE TITLE
Property 'toPromise' does not exist on type 'Observable<Response>'

### ISSUE THREAD

**Issue by khanstudio-github** [angular/angular#10292]
**I'm submitting a ...
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am going through your tutorial from this [link](https://angular.io/docs/ts/latest/tutorial/toh-pt6.html). You asked to import a property from "import 'rxjs/add/operator/toPromise'" i imported the module BUT I am getting an error saying:

> Property 'toPromise' does not exist on type 'Observable<Response>'

Moreover, .map() also shows the same error 

**You can view my source on GitHub** [here](https://github.com/khanstudio-github/Angular2AppASPNet).

Please provide you help to the earliest. Looking forward for a positive response. Thank you

**Expected/desired behavior**
toPromise() or map() should not show any error.  

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome 51.0.2704.103 m |] 
 
* **Language:** [all | TypeScript 1.8.10 | ES6/7 | ES5 |]

**Comment by fknop** [comment]
Make sure you're running the same version of `RxJS` than the dependency of `Angular`.  I don't see any imports in your code.

**Comment by zoechi** [comment]
You also need to import `toPromise`

**Comment by thelgevold** [comment]
Add this line `import 'rxjs/add/operator/toPromise';`

**Comment by khanstudio-github** [comment]
I have added the imports. As you can see in the project files [here](https://github.com/khanstudio-github/Angular2AppASPNet/tree/master/Angular2StarterApp/Angular2StarterApp/app) i have added a file named **[rxjs-operators.ts](https://github.com/khanstudio-github/Angular2AppASPNet/blob/master/Angular2StarterApp/Angular2StarterApp/app/rxjs-operators.ts)**. You can find those import lines in the file

- import 'rxjs/add/operator/toPromise';
- import 'rxjs/add/operator/map';

Afterwards, I have added a reference to this file in **[app.component.ts](https://github.com/khanstudio-github/Angular2AppASPNet/blob/master/Angular2StarterApp/Angular2StarterApp/app/app.component.ts)** BUT still it gives the same error in the **[dragon.service.ts](https://github.com/khanstudio-github/Angular2AppASPNet/blob/master/Angular2StarterApp/Angular2StarterApp/app/services/dragon.service.ts)** file. so i commented those lines for now. 

**Can you please identity the error or see if the approach is correct.** 

Also at @fknop can you please tell me how can I make sure that my `RxJs` version is same as that of dependency of `Angular`. I'm using the `RxJs version 5.0.0-beta.6`, same used in [Angular 5 Min Quickstart](https://angular.io/docs/ts/latest/quickstart.html). Even though the latest version of `Rxjs` is 5.0.0-beta.10, which is not compatible with Angular 2

**Comment by pkozlowski-opensource** [comment]
@khanstudio-github your questions sound like a support request and as such should be taken to an appropriate support channel, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by JeroMiya** [comment]
If you googled this error, found yourself here, and still can't find the solution: update your typescript compiler to ^2.0.0 (you may also need gulp-typescript ^3.0.0 and/or the latest VS tools for typescript, which must be manually installed).
