### ISSUE TITLE
Router.events does not return a proper Observable

### ISSUE THREAD

**Issue by MathiasTim** [angular/angular#10295]
```
[x] bug report
```

**Current behavior**
Router in (`'@angular/router'`) should have an `events`-key of type `Observable<Event>`.
As stated in documentation: https://angular.io/docs/ts/latest/api/router/index/Router-class.html
However current events are type of `Subject`. I can do a simple `.subscribe()`, but I can't use `.filter()` like this:
```
this.router.events
  .filter((event) => false)
    .subscribe((event) => {
      console.log(event);
  });
```
I get the following error: `TypeError: this.router.events.filter is not a function`

**Expected/desired behavior**
The `events`-key should return an standard Observable as documented.

**Reproduction of the problem**
Just use the implementation described above

Howeever you can do a workaround like this:
```
Observable.from(this.router.events)
  .filter((event) => false)
  .subscribe((event) => console.log(event);
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome 54.0.2806.0 canary (64-bit)
 
* **Language:** TypeScript 1.8

**Comment by brandonroberts** [comment]
Filterng router events works fine. You need to import the filter operator first.

`import 'rxjs/add/operator/filter';`

**Comment by MathiasTim** [comment]
@brandonroberts thanks! Works after the import!

**Comment by dudewad** [comment]
Sorry if I'm missing something, but why is this considered not broken? Shouldn't importing the RouterModule bring with it the rxjs observable stuff, as it is documented? Having to import additional functionality to get a component to work seems weird.
I have other NG2 projects where this is not an issue, for some reason. In other words, I have the exact "bug" situation above that works fine, and in a newer project, it breaks.

**Comment by brandonroberts** [comment]
@dudewad the framework only imports what it needs. If you're using `.filter` on the `router.events` observable, you need to import the operator. The rxjs that is used in the framework is done by importing the function and not patching the Observable so it can be tree-shaken out if needed.

Most likely, the reason yours works in other projects is because somewhere in your project you've already imported that operator and patched the Observable.

**Comment by brunobertechini** [comment]
Weird behavior is in my case, without AOT it works without importing filter.

When I deploy using AOT compilation, I get the error `TypeError: this.router.events.filter is not a function`

Bruno

+1 for fixing it.

**Comment by vinayakpatil** [comment]
This does not seem to work after upgrading to ^4.3.0.

**Comment by brandonroberts** [comment]
This issue is not an error in the framework. Please use the support channel at https://gitter.im/angular/angular if you are still seeing this issue
