### ISSUE TITLE
URL Params not being encoded

### ISSUE THREAD

**Issue by reach4thelasers** [angular/angular#10307]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using routerLink with a variable parameter e.g.: <a [routerLink]="['/instrument', instrument.Name]">{{ instrument.Name }}</a>

the Paramter is not encoded.  In this scenario the param is a Forex Instrument name which contains a slash e.g. "USD/GBP".  This is being routed to /instrument/usd/gbp.

The same happens if for a test I pass "USD&GBP" - the & is not encoded

**Expected/desired behavior**
I would expect the route to be generated as /instrument/usd%2fgbp.  

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all |
 
* **Language:** [all | TypeScript 1.8

**Comment by reach4thelasers** [comment]
I wrote this pipe which fixes it for now.  But this is definitely a bug.
```

import {PipeTransform} from '@angular/core/src/change_detection/pipe_transform';
import {Pipe} from '@angular/core/src/metadata';
@Pipe({name: 'escapeurl', pure: false})
export class EscapeUrlPipe implements PipeTransform {
   transform(value: any, args: any[] = []) {
      return encodeURIComponent(value);
   }
}
```

**Comment by brandonroberts** [comment]
This has already been fixed in master and will be in the next release

**Comment by reach4thelasers** [comment]
awesome thanks!!
