### ISSUE TITLE
Angular Template Compiler RouterLink "Supplied parameters do not match any signature of call target."

### ISSUE THREAD

**Issue by defabien** [angular/angular#10301]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using the Angular Template Compiler, templates with the new router compile with [routerLink] like this (RouterLink instead of _RouterLinkWithHref_2_3 for non e elements);

`
this._RouterLinkWithHref_2_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
`

But the constructor of RouterLinkWithHref or RouterLink expects 0 parameters. Resulting in "Supplied parameters do not match any signature of call target." error.

**Expected/desired behavior**
No "Supplied parameters do not match any signature of call target." error when using the Angular Template Compiler on templates that use [routerLink].

* **Angular version:** 2.0.0-rc.4
* **Angular router** 3.0.0-beta.1
* **Language:** [TypeScript 2.1.0-dev.20160726]

**Comment by ericmartinezr** [comment]
For reference https://github.com/angular/angular/issues/10132#issuecomment-235166470 @laco0416

**Comment by defabien** [comment]
The same issue exists on RouterOutlet with 4 parameters

**Comment by vicb** [comment]
Please provide a minimal repro thanks

**Comment by robwormald** [comment]
fixed in https://github.com/angular/angular/commit/9d9e9c6ff1eb37d54a6e4af0a88f05a41f75d7a9
