### ISSUE TITLE
Animation "onDone" callback support missing

### ISSUE THREAD

**Issue by matsko** [angular/angular#10304]
We need this:

```html
<div [@animation]="exp" (@animation.done)="onDone()" (@animation.start)="onStart()">...</div>
```

**Comment by ThomasBurleson** [comment]
@matsko  - 👍

**Comment by b-strauss** [comment]
@matsko what happened to AnimationControl? You showed this at [ng-conf](https://youtu.be/Hr4IKlr9mhg?t=12m4s). Isn't this kind of higher level API better than just a callback that gets invoked?

**Comment by matsko** [comment]
Good question. `@AnimationControl` will become `@Animation`.

`@Animation` is used for animations that are not bound to transitions. Those will come around once we get the reusable animations feature in there.

```ts
@Component({
   animations: [
     // notice how it's not bound to a trigger
     // this animation can also be referenced inside of a transition via (animate(dur, animation("rotateStuff"))
     animation('rotateStuff', [
        animate('1s', keyframes([
           style({ 'transform': 'rotate(0deg)' }),
           style({ 'transform': 'rotate(360deg)' })
        ])
     ])
  ]
})
class Cmp {
  @Animation("rotateStuff") animator;
  innerRef: ElementRef;  

   constructor(@Query("#innerChild") inner) {
      this.innerRef = inner;
   }

   start() {
       var player = this.animator.start(this.innerRef);
       player.setPosition(0); //0% into the animation
       player.setPosition(1); //100% into the animation
       player.reverse();
       player.pause();
       player.play();
       player.onDone( () => { });
   }
}
```

**Comment by matsko** [comment]
Originally `@AnimationControl` was designed for player access. But transition animations always end at the last animation anyway. So the split allows for programmatic animations to be available in component code.

Unless there's a usecase that `<div (@animation)="exp()">` doesn't solve then `@AnimationControl` won't be required.

**Comment by b-strauss** [comment]
Thank you for the fast and detailed answer!

**Comment by silvanaacc** [comment]
Hello. When is this feature going to be ready? 
Practically we need it now to trigger an event at the end at the end of an animation. How can we work it out at the moment? thanks

**Comment by matsko** [comment]
As soon as this bizarre IE test disconnection is fixed: https://github.com/angular/angular/pull/10360. Hopefully Monday in time for RC6.

**Comment by matsko** [comment]
Yaaay finally! https://github.com/angular/angular/pull/10892
