### ISSUE TITLE
Cannot inject global `Window`

### ISSUE THREAD

**Issue by laco0416** [angular/angular#10309]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The following code doesn't work.  

```ts
@Component({
  selector: 'my-app',
  providers: [
      { provide: Window, useValue: window }  
  ],
  template: `
    <div>
      <h2>Hello {{name}}</h2>
    </div>
  `,
  directives: []
})
export class App {
  constructor(private w: Window) {
    this.name = this.w.location.href;
  }
}
```

```
platform-browser.umd.js:1900 Error: Can't resolve all parameters for App: (?).
```

But with `@Inject`, it works well.

```ts
@Component({
  selector: 'my-app',
  providers: [
      { provide: Window, useValue: window }  
  ],
  template: `
    <div>
      <h2>Hello {{name}}</h2>
    </div>
  `,
  directives: []
})
export class App {
  constructor(@Inject(Window) private w: Window) {
    this.name = this.w.location.href;
  }
}
```

**Expected/desired behavior**

The first example works as well as the second.

**Reproduction of the problem**
http://plnkr.co/edit/2JhQ01Y6cfbWGnhhRYt0?p=preview

**What is the expected behavior?**

It works well. 
Removing `@Inject(Window)` and it will crash.

**What is the motivation / use case for changing the behavior?**

I want to create mock `window` for testing.
If `Window` can be a DI token, it's so intuitive and I'm happy.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:**  Chrome 52
 
* **Language:** TypeScript 1.8

**Comment by sod** [comment]
Seems more of a "limitation" of typescript metadata.

![image](https://cloud.githubusercontent.com/assets/905328/17167230/55166012-53dc-11e6-9bbb-6908a47e213f.png)

Normally the metadata returns the token. But here it just says `Object`. I guess typescript won't preserve variables, that are not explicitly declared.

Maybe you want to use angulars [Location](https://angular.io/docs/ts/latest/api/common/index/Location-class.html) instead.

**Comment by laco0416** [comment]
@sod Thank you. Sure, my example uses `window.location` but it's just an example.
In real applications, we use `window.alert` , `window.confirm` and other functions or any global variables. `window` is the context and it has a lot of features.

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/34177221/angular2-how-to-inject-window-into-an-angular2-service

**Comment by StefH** [comment]
Currently I only want to use **window.location.origin** in my Injectable class. Can I just replace this with **location.path** ?

**Comment by tbosch** [comment]
This seems to work with the 2.x version of Typescript. I get the following output:
```
var Test = (function () {
    function Test(w) {
    }
    Test = __decorate([
        Test(), 
        __metadata('design:paramtypes', [Window])
    ], Test);
    return Test;
}());
```

**Comment by skdhir** [comment]
I upgraded to latest Angular (^2.4.0) and angular-cli (1.0.0-rc.0) and it stopped working.
Funny thing is ng build compiles with no problem but ng build --prod gives an error saying unknown type : Window

**Comment by AarjavP** [comment]
Same thing is happening for me as well. `ng build` works file, `ng build --prod` does not. Using Angular ^4.2.4, and angular/cli 1.4.0

**Comment by IcodeNet** [comment]
https://github.com/angular/angular/issues/15640

Taken from the above issue from https://github.com/mtinner 
the following worked for me
 
 **export const Window_Injection = new InjectionToken('window.injection');**
...
**providers: [{ provide: Window_Injection, useValue: window }]**
...
constructor(**@Inject(Window_Injection) private window**) {}
