### ISSUE TITLE
Child Routers, redirectTo & Safari

### ISSUE THREAD

**Issue by db3dev** [angular/angular#10311]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you attempt to create a route array that includes something along the lines of:

`[
  {
    path: 'main', 
    component: HeaderComponent,
    children: [
        { path: '', redirectTo: /main/component },
        ...ARoutes,
        ...BRoutes
    ]
  }, 
]`

This will work successfully on Chrome. If you try the same exact directions using safari the console complains:

> EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: '...'

**Expected/desired behavior**

Safari should redirect the path successfully with the same behavior as Chrome.

**Comment by zoechi** [comment]
Please provide a Plunker that allows to reproduce.

**Comment by vsavkin** [comment]
Closing the issue. Please reopen it with a plunker.
