### ISSUE TITLE
ng-model in select element does play well

### ISSUE THREAD

**Issue by felquis** [angular/angular#10322]
[x] bug report
[ ] feature request
[ ] support request

**Current behavior**

When the value of a ng-model is 1 or any number, angular prepend a `<option value="? number:n ?"></option>` to my `select` and it is just broken

![image](https://cloud.githubusercontent.com/assets/736728/17177072/0689653e-53e6-11e6-9cb5-899ae2dda6ab.png)

**Expected/desired behavior**

Should find the `option` where `value=" ' + model + '"` and make it the selected one.
Should not break

**Reproduction of the problem**

Check out this codepen observe the difference between $scope.aString and $scope.aNumber http://codepen.io/felquis/pen/YWvApR

**What is the expected behavior?**

Check out the **Expected/desired behavior**

**What is the motivation / use case for changing the behavior?**

Angular should be smart enough

**Please tell us about your environment:**

* **Angular version:** https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.7/angular.min.js
 
* **Browser:** tested on Firefox and Chrome on Ubuntu, both as the problem
 
* **Language:** JavaScript, Babel

**Comment by ericmartinezr** [comment]
This repo is for ng2, you are looking for https://github.com/angular/angular.js :p
