### ISSUE TITLE
Importing service from barrel index.ts file got undefined

### ISSUE THREAD

**Issue by ptomaszi** [angular/angular#10320]
I have the following app folder structure:

--app (index.ts)
   --components (index.ts)
      --home (home.component.ts)
      --login (user-info.service.ts, login-details.ts, login.component.ts, login.routes.ts, index.ts)

The login "index.ts" file exports all services and components:

```
export * from './user-info.service';
export * from './login-guard.service';
export * from './login.service';
export * from './login-details';
export * from './login.component';
export * from './login.routes';
```
The components "index.ts" file exports all index files from child folders:

```
export * from './user-registration/user-registration.component';
export * from './login/index';
export * from './welcome/welcome.routes';
export * from './welcome/welcome.component';
export * from './home/home.component';
```

In my "Home" component I am trying to import "user-info.service" from the "Login" barrel index file:

```
import { Component } from '@angular/core';
import { UserInfoService } from '../index';

@Component({
    moduleId: module.id,    
    templateUrl: 'home.component.html',
    styleUrls: ['home.component.css']    
})
export class HomeComponent {
    public userName: string;
    constructor(private userInfo: UserInfoService) {
        this.userName = userInfo.loginDetails.email;
    }
}
```

I got the following exception:

> browser_adapter.ts:82 EXCEPTION: Error: Uncaught (in promise): Can't resolve all parameters for HomeComponent: (?)

When I change the import statement to import directly from the "user-infor.service.ts" file it works without any issues:

`import { UserInfoService } from '../login/user-info.service';`

I am not really sure why there is an issue when I try to import from the "index.ts" file.

My "system-config.ts" file looks like:

```
var barrels: string[] = [
  // App specific barrels.
  'app',
  'app/shared',  
    'app/shared/di-core',
    'app/shared/upgrade',
    'app/components',
    'app/components/welcome',
  'app/components/login',
  'app/components/home'
];

var cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});  
```
Any ideas or suggestions please?

**Comment by BaruchFisherman** [comment]
Hi, 
You  sure, that you don't need to add "provider" for HomeComponent?

@Component({
    moduleId: module.id,    
    templateUrl: 'home.component.html',
    styleUrls: ['home.component.css'],
    **providers: [UserInfoService]**
})

**Comment by ptomaszi** [comment]
No as my "UserInfoService" is registered at the bootstrap level and not per individual component. I only want to have a single instance of the service available for every component in the application.

**Comment by sod** [comment]
Maybe your build adds the file twice for each import path. So the reference wont be identical.

**Comment by awerlang** [comment]
See https://github.com/angular/angular.io/issues/1301

**Comment by tbosch** [comment]
You might have a circular dependency, so that the `UserInfoService` class was not yet declared. You can try to do a `console.log(UserInfoService)` right before you declare `export class HomeComponent ...` to check this.

**Comment by tbosch** [comment]
This does not seem related to Angular but rather the module system. Closing as not actionable.
