### ISSUE TITLE
fix(router): canDeactivate should not change the url when returns false

### ISSUE THREAD

**Issue by markletters** [angular/angular#10321]
This issue was closed here [https://github.com/angular/angular/pull/8360]. However, the problem still remains when using the browser back and forward buttons.

**Comment by CaselIT** [comment]
The problem can also bee seen in the sample [plnkr](https://angular.io/resources/live-examples/router/ts/plnkr.html) of the [router and navigation develorper guide](https://angular.io/docs/ts/latest/guide/router.html) on the angular website.
Steps:
*  pop out the preview window to see the address bar
*  click on a crisis and edit the text
*  use the browser back commands to go back. 

The url changes even if the user clicks cancel on the popup

**Comment by Hegemege** [comment]
Can confirm that using `Location.back()` changes the URL as well, not just the browser buttons. I have a modal where the user selects to stay on the page or go back - the component stays active, but the URL changes, and subsequent presses on the return button change the URL further back. This also happens if one uses `window.history.back()`

**Comment by loic49** [comment]
+1, I confirm location.back() changes the URL on final version 2.0.0. Any news about a future fix ?

**Comment by strpipe** [comment]
I can confirm this problem too and want to highlight another problem related to this one.

Pressing the browsers back-button will also trigger `window.history.back()` even if the guard returns _false_, so if the user continues to navigate in a forward direction but then decides to go back and presses the browsers back-button he will navigate too far back.

For example: 
```
VIEW_1 -- navigate to --> VIEW_2
(backButton) --> guard returns false       //still triggers window.history.back()
VIEW_2 -- navigate to --> VIEW_3
(backButton) --> results in Navigation to VIEW_1
```

**Comment by CaselIT** [comment]
@strpipe This will also appen in this case
```
VIEW_1 -- navigate to --> VIEW_2
VIEW_2 -- navigate to --> VIEW_3
(backButton) --> guard returns false
User does something to correct the guard fail
(backButton) --> guard returns true --> Navigation to VIEW_1
```

Since the `window.history.back()` is always called when finally the guard returns true it will navigate to a page that depends on the number of times the `window.history.back()` was called.

**Comment by dennis-g** [comment]
+1

**Comment by CodeJason** [comment]
It seems like [d509ee0](https://github.com/angular/angular/commit/d509ee078b24cdce2a3fa3fe906f4c6b60bec777) fixed the issue of restoring the valid url when navigation is denied, but the issue from @strpipe is still there, where the stack state is not maintained.
 
Can anyone confirm?

**Comment by jsgoupil** [comment]
@vsavkin This seems to still be an issue if you first navigated to a route with { skipLocationChange: true }

    this.router.navigate(['edit'], { relativeTo: this.route, skipLocationChange: true });

Then when you are about to navigate away and return `false`, the `/edit` creeps in the URL.

This is my routing:

    path: 'view',
    children: [
        {

            path: ':id',
            component: CustomerViewComponent,
            resolve: {
                customerViewData: CustomerResolve,
            },
            canDeactivate: [CanDeactivateGuard],
            children: [
                {
                    path: 'edit',
                },
                {
                    path: ''
                }
            ]
        }
    ]

Do you want to open a new bug for this?

**Comment by vicb** [comment]
> Do you want to open a new bug for this?

Please, comments on closed issue will probably get lost
