### ISSUE TITLE
Listen to pinchmove and pan event simultaneously with hammerjs?

### ISSUE THREAD

**Issue by Gabriel0402** [angular/angular#10328]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

NG2 can listen to pan OR pinch/pinchmove either by using the template or HostListener:
```  
@HostListener('pinchmove', ['$event'])
onPinchMove(e: any) {
 console.dir(e);
}
```
But it cannot listen to pinch AND pan simultaneously. The following is not working.
```  
@HostListener('pinchmove pan', ['$event'])
onPinchMove(e: any) {
 console.dir(e);
}
```
If I added both HostListener Decorator, the events are not firing simultaneously: 
```  
@HostListener('pinch', ['$event'])
onPinchMove(e: any) {
 console.dir(e);
}

@HostListener('pan', ['$event'])
onPinchMove(e: any) {
 console.dir(e);
}
```

**Expected/desired behavior**
Add recognizeWith support from hammerjs in ng2 to fire events simultaneously. So it's possible to use hostlistener decorator to listen to events. 

```  
@HostListener('pinchmove pan', ['$event'])
onPinchMove(e: any) {
 console.dir(e);
}
```

**What is the motivation / use case for changing the behavior?**

We can do pinch and pan simultaneously on the web app. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome  | Firefox | IE  | Safari | Mobile Chrome  | Android Web Browser | iOS Safari ] 
 
* **Language:** [all | TypeScript 2.0 | ES6 ]

**Comment by vicb** [comment]
You can do that by injecting your own hammer configuration, see https://github.com/angular/angular/blob/master/modules/@angular/platform-browser/src/dom/events/hammer_gestures.ts#L33

**Comment by Gabriel0402** [comment]
Thanks for the help. For future reference, I'll added the configuration I made: 
main.ts
```
bootstrap(MyApp, [
   provide(HAMMER_GESTURE_CONFIG, {useClass: MyHammerConfig})
])
```
MyHammerConfig.ts
```
class MyHammerConfig extends HammerGestureConfig  {
  events: string[] = ['pinch pan']; //necessary for ng2 to recognize "pinch pan" event
  buildHammer(element: HTMLElement): HammerInstance {
    let mc = new Hammer(element, {domEvents: true});
    mc.get('pinch').set({enable: true});
    mc.get('pinch').recognizeWith(mc.get('pan'));
    return mc;
  }
}

```

**Comment by vicb** [comment]
@Gabriel0402 Thanks for reporting the solution, could be helpful to others.
