### ISSUE TITLE
ngFor with model driven forms. Unexpected behavior 

### ISSUE THREAD

**Issue by AAAnderson7301** [angular/angular#10333]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am not seeing a way to use model driven forms with ngFor. The formControlName is set to the last item in the array. 

**Expected/desired behavior**
To be able to bind formControlName to the formBuilder so each ngFor is its own formGroup

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via 

http://plnkr.co/edit/ZXPY3hwai9giLJHhZBx3?p=preview

**What is the expected behavior?**
To find a way to use model driven forms and ngFor. I tried to use [ngModelOptions]="{standalone:true}" but then I do not have a formgroup. I need a formGroup to detect any change (.dirty) between the repeated fields. 

**What is the motivation / use case for changing the behavior?**
I have a form that is a list of expenses(*ngFor). Anytime a field is changed on one of the repeated lines. I need to notify the user so that the line is saved. using standalone means I would have to look at all fields instead of the group. 

**Please tell us about your environment:**
"@angular/core": "2.0.0-rc.4",
 "@angular/forms": "0.2.0",
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web  ALL 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

http://plnkr.co/edit/t7Ia7GwKn9YLo65W9dhr?p=preview

**Comment by gfrSE** [comment]
> GitHub issues are for bug reports and feature requests.
For support questions please use other channels like the ones listed in CONTRIBUTING - Got a Question or Problem?
http://plnkr.co/edit/t7Ia7GwKn9YLo65W9dhr?p=preview

@zoechi you are right, but nice that you help though! :)

A little modified plunker (to see changes for each line):

http://plnkr.co/edit/dqC7wetyUAPeQRCsviDm?p=preview

**Comment by AAAnderson7301** [comment]
@gfrSE , @zoechi. Thank you both for the help. I will be sure to post in the support questions section next time. Thank you,
