### ISSUE TITLE
Cannot mix Async Validator with Synchronus Validators

### ISSUE THREAD

**Issue by Bretto** [angular/angular#10341]
**I'm submitting a** 
bug report

**Current behavior**
If you add ```Validators.minLength,``` and an async validation it doesn't work

**Expected/desired behavior**
I would like to be able to mix synchronous and async validators.

**Reproduction of the problem**
You can see in this https://plnkr.co/edit/awcG2k?p=preview
this doesn't works
``` 
this.form2 = formBuilder.group({
        'username': [this.model.username, [Validators.minLength(2), Validators.required, this.uniqueNameAsync]]
    });
```

**What is the expected behavior?**
It should work (IMHO)

**What is the motivation / use case for changing the behavior?**
Flexibility

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by zoechi** [comment]
async validators are to be passed as the 3rd parameter https://angular.io/docs/ts/latest/api/forms/index/FormControl-class.html
https://plnkr.co/edit/fSm0qv?p=preview

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
