### ISSUE TITLE
pipes of angular2 don't work in Safari browsers

### ISSUE THREAD

**Issue by suplch** [angular/angular#10345]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report

**Current behavior**


**Expected/desired behavior**


**Reproduction of the problem**
{{12345 | number}}  
   This expression will display 12,345 in chrome browser, this is correct
   But in safari browser, this expression will display empty string, and then throw an exception on console of browser.
like this:
    format
formatNumber
transform
[native code]

detectChangesInternal
detectChanges
detectViewChildrenChanges
detectChangesInternal
detectChanges
detectContentChildrenChanges
detectChangesInternal
detectChanges
detectViewChildrenChanges
detectChangesInternal
detectChanges
detectChanges

forEach@[native code]
tick

invoke
onInvoke
invoke
run
runInner
run


__tryOrUnsub
next
_next
next
_finalNext
_next
...........



**What is the expected behavior?**

We expected this expression {{12345 | number}}  output 12,345 in safari browser, and no error.


**What is the motivation / use case for changing the behavior?**
So important function don't work in safari browser.


**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Safari 9.1.1 (11601.6.17)] 
 
* **Language:** [all | TypeScript 1.8.10 ]

**Comment by sod** [comment]
Plunkr: http://plnkr.co/edit/UMLF9z632LxRNmxHQAy6?p=preview

The error reads: `Can't find variable Intl`

![image](https://cloud.githubusercontent.com/assets/905328/17207479/1047343c-54b5-11e6-8f82-ee9cc86ddaa0.png)

The [number_pipe.ts source code file](https://github.com/angular/angular/blob/master/modules/@angular/common/src/pipes/number_pipe.ts#L63-L65) suggests to use a polyfill like https://github.com/andyearnshaw/Intl.js/

But I can't find that notice in the documentation. Neither the [reference](https://angular.io/docs/ts/latest/api/#!?apiFilter=number) nor the [pipes guide](https://angular.io/docs/ts/latest/guide/pipes.html) :(

**Comment by ericmartinezr** [comment]
If the error the OP is seeing is the same @sod mentioned then this is dup of https://github.com/angular/angular/issues/3333

**Comment by DaSchTour** [comment]
As this is mainly an documentation issue. I added a request to angular.io

**Comment by vicb** [comment]
> https://github.com/angular/angular/issues/9751

:+1: Thanks
