### ISSUE TITLE
select: option with 'null' value

### ISSUE THREAD

**Issue by kemsky** [angular/angular#10349]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
```

**Current behavior**

```
<select id="idState" name="state" [ngModel]="user?.state" (ngModelChange)="user==null || user.state=$event">
      <option value="">N/A - 1</option>
      <option [ngValue]="">N/A - 2</option>
      <option [ngValue]="null">N/A - 3</option>
      <option *ngFor="let s of states" [ngValue]="s">{{s.shortName}}</option>
</select>
```

I can not set `user.state` to `null`:
N/A - 1 produce empty string
N/A - 2 produce "N/A - 2"
N/A - 3 produce "0: null"

**Expected/desired behavior**

Should be able to set `null`.

**What is the motivation / use case for changing the behavior?**

I don't want to clean up values manually for every nullable field. 

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [all] 
- **Language:** [TypeScript 1.8]

**Comment by kemsky** [comment]
It is also quite confusing to have 3 possible results.

**Comment by sod** [comment]
Plunkr of your case: http://plnkr.co/edit/x3YCwSqzzMeHcx2RVDyp?p=preview

With FormsDeprecated it was possible via `ngControl`

```twig
<form [ngFormModel]="type.control">
    <select class="form-control" ngControl="country">
        <option [ngValue]="null">Please select value</option>
        <option *ngFor="let country of countries" [ngValue]="country.value">{{ country.label }}</option>
    </select>
</form>
```

```typescript
import {ControlGroup, Control} from '@angular/common';

    // ...
    public control = new ControlGroup({
        country: new Control(null)
    });
    // ...
```

Don't know about the new forms - or in your case - without ngForms, through.

**Comment by kemsky** [comment]
Problem has two sides:
1. i have to convert `null` to empty string to select correct option
2. i have to convert empty string to `null` to set correct value

it means that i have to write many if's in `[ngModel]` and `(ngModelChange)`.

**Comment by sam-s4s** [comment]
Yes, this is a very annoying problem for us! having null in ngValue would be so useful!

Currently we have to do a lot of extra work to deal with nulls, just like @kemsky has stated above.

It looks like @kb3eua may have fixed this problem for a future release?

**Comment by francosioquim** [comment]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
```
<select id="idState" name="state" [ngModel]="user?.state"  
(ngModelChange)="user==null || user.state=$event">
       <option value="">N/A - 1</option>
       <option [ngValue]="">N/A - 2</option>
       <option [ngValue]="null">N/A - 3</option>
       <option *ngFor="let s of states"  
[ngValue]="s">{{s.shortName}}</option>
</select>
```
I can not set `user.state` to `null`:
N/A - 1 produce empty string
N/A - 2 produce "N/A - 2"
N/A - 3 produce "0: null"

**Expected/desired behavior**

Should be able to set `null`.

**What is the motivation / use case for changing the behavior?**

I don't want to clean up values manually for every nullable field.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

* **Browser:** [all]

* **Language:** [TypeScript 1.8]


---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/angular/angular/issues/10349

**Comment by sam-s4s** [comment]
@kara Hey Kara - any idea on when this will make it into a release?

Very important issue for us! :D

**Comment by ClementParis016** [comment]
I can confirm the bug appears in IE, Edge & Safari in Angular v2.1.2.
Here is a [plunkr](https://plnkr.co/edit/VKLWkJBmRtTwfGYJSoLz?p=preview) demonstrating the issue (in IE, Edge & Safari, the Angular select gets a default value)

**Comment by morphin77** [comment]
offtop, but You can try
`<option [ngValue]='U+0000'>{{value}}</option>`
where U+0000 it 'null' in Unicode

**Comment by sam-s4s** [comment]
@morphin77 this did get fixed a few years ago though, so you can actually use null :)
