### ISSUE TITLE
Page not refresh on IE when type in URL

### ISSUE THREAD

**Issue by zheng671** [angular/angular#10342]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The problem happened only on IE. After doing redirection by clicking on the link in page, if we enter the URL directly in address bar on browser, the page does not refresh. However, if we change from HashLocationStrategy to normal LocationStrategy. it works fine without any problem.

**Expected/desired behavior**

Page should refresh if we enter the URL directly.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Angular Router version:** 3.0.0-beta.2
 
* **Browser:** [IE 11 ] 
 
* **Language:** [TypeScript X.X]

**Comment by zheng671** [comment]
[src.zip](https://github.com/angular/angular/files/387700/src.zip)

Project file

**Comment by zoechi** [comment]
Please provide a Plunker to reproduce instead of a zip file.

**Comment by zheng671** [comment]
@zoechi I don't have access to plunker right now, but any project using new router will have such problem.

**Comment by tbosch** [comment]
This seems to be a general problem with IE, independent of Angular, as no javascript application can intercept the a user entering an url into the address bar.
