### ISSUE TITLE
Router:  should flatten configuration array 

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10340]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request
```
It appears that as of July 27 master we're still not flattening router configs.  This example works with spread operator
```
/// all arrays of routes
export const routes: RouterConfig = [
  ...heroesRoutes,
  ...loginRoutes,
  ...crisisCenterRoutes
];
```
... this does not
```
/// all arrays
export const routes: RouterConfig = [
  heroesRoutes,
  loginRoutes,
  crisisCenterRoutes
];
```
Here is `heroesRoutes`; the others are similar
```
export const heroesRoutes: RouterConfig = [
  { path: 'heroes',  component: HeroListComponent },
  { path: 'hero/:id', component: HeroDetailComponent }
];
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 candidate (July 27)
 
* **Browser:** [all ] 
 
* **Language:** [all ]

**Comment by sod** [comment]
What a coincidence, there is already https://github.com/angular/angular/pull/10258

**Comment by vsavkin** [comment]
Dup of 10258
