### ISSUE TITLE
Data driven forms

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1034]
Goals:
- To be able to generate a form dynamical based on specified structure.
- It should allow for marshaling data from/to form and model.
- Should support layout strategies
- Should support selecting of right component type

Things to consider:
- Impedance mismatch of model vs form control

Implementation note:
- We need to develop a component which will look through this and generate a dynamic component for each type and load the private component based on type.

```
import {forms, required, materialDesign} from 'angular2/forms';

// Our model
class Address {
  street: string;
  city: string;
  state: string;
  zip: string;
  residential: boolean;
} 

@Component({
  selector: 'form-example'
})
@Template({
  // Form layout is automatic from the structure
  inline: `<form [form-structure]=”form”></form>`
  directives: [forms]
})
class FormExample {
  constructor(fb: FormBuilder) {
    this.address = new Address();

    // defining a form structure and initializing it using 
    // the passed in model
    this.form = fb.fromModel(address, [
      // describe the model field, labels and error handling
      {field: 'street', label: 'Street', validator: required},
      [ {field: 'city', label: 'City', validator: required},
        {field: 'state', label: 'State', size: 2, validator: required},
        {field: 'zip', label: 'Zip', size: 5, validator: zipCodeValidator},
      ],
      {field: 'isResidential', type: 'checkbox',label: 'Is residential'}
    }, {
      // update the model every time an input changes
      saveOnUpdate: true,
      // Allow setting different layout strategies
      layoutStrategy: materialDesign
    });
  }
}

function zipCodeValidator(control) {
  if (! control.value.match(/\d\d\d\d\d(-\d\d\d\d)?/)){
    return {invalidZipCode: true};
  }
} 
```

**Comment by martinmcwhorter** [comment]
There are a few prior arts that should be considered, as they provide real world use cases. 

    * angular-formly
    * angular-autoFields
    * angular-schema-form

I believe a real world use case that each of these provide is the ability to test form business logic independent of the controller. 

In essence you should be testing the form/schema isolated from the controller. Ideally with the new forms in angular2 we should be able to fully test the forms (all the way to the control)  generated from schema independent of a controller.

Another use case these prior arts demonstrate is the ability to set element attributes (probably want to set element properties instead) such as: required, minlenth, maxlength, pattern, placeholder... from the form schema.

**Comment by DanWahlin** [comment]
It'd be really nice to reduce the amount of code required by annotating the model (something that would be optional). I suggested this and just saw that someone else did as well to reduce the amount of boilerplate code:

https://github.com/angular/angular/issues/1047
https://github.com/angular/angular/issues/1043

**Comment by martinmcwhorter** [comment]
@DanWahlin I like it. This is very similar to attributes in ASP.Net MVC where we have a model and we use attributes (annotations in TypeScript) to provide field metadata for generating the form. I can still see valid use cases where the field metadata (form schema) would come from a seperate datasource than property annotations. 

Example use case: A single model that can use multiple message form schemas depending on the state of the user. 

We have a user details form that is backed by UserDetails model containing: name, address, phone, etc. Initially for a NEW user we use a form schema named userDetailsNew which allows the user to enter all there details. Once the user is no longer in the NEW state, we use the schema userDetailsExisting schema, which has the first and last name fields disabled -- so the user cannot change there name. 

This would allow us to use the same model, the same controller, the same view -- we would just use a separate form schema dynamically. 

There is also a use case to be able to change the schema on the fly. Following on from the last use case, we have generated form schemas for each country with a pattern for the phone number. The userSchemaUS declares a pattern for phone /^\+1/ and userSchemaGB declared pattern for phone /^\+44/. The user has a US address and phone number set. If the user changes there country to GB the controller will replace the form schema with userSchemaGB and the player will get a validation error on the phone field.

**Comment by mohsen1** [comment]
One very common use case for data-driven forms is generating forms based on a JSON Schema. Backend and API developers love to give front-end developers a JSON Schema and tell them this is what the model should look like when you're submitting a from. It makes a lot of sense to use that same schema to build the form. Please take a look at [json-editor](https://github.com/jdorn/json-editor). It does a great job at generating forms off a JSON Schema. 

Main challenges in generating forms from a  JSON Schema are:

* JSON Schema has validation rules like `minimum`, `format` and so on. Forms that are generated from A JSON Schema should have that validation logic in there.
* JSON Schema supports arrays. Forms should support mechanism for adding new items to array. (Removing items and sorting items in array are required too)
* JSON Schema can have `additionalProperties: true` property which means the model can have unlimited number of key/value pairs.
* JSON Schema is recursive and base case is `{}` which means **any object**. Other base cases are `{type: 'string`}` or `{type: 'array'}`.
* JSON Schema supports `anyOf`, `oneOf` and `allOf`. Learn more about them [here](http://jsonary.com/documentation/json-schema/?section=keywords/General%20keywords). This makes JSON Schema very powerful and at the same time very hard to generate forms and validators. 


I would love to see Angular 2 Forms module supports JSON Schema out of the box, but if that's not aligned with project goals please consider making it easy for developers to build forms from JSON Schema.

**Comment by royreiss** [comment]
@mohsen1 I agree.  JSON schema already has a large ecosystem for server-side APIs and would be a great starting point if nothing else.

You can create reusable component schemas via the [$ref / definitions keywords](http://json-schema.org/latest/json-schema-validation.html#anchor94)

**Comment by spectre3ooo** [comment]
I would love to see a way to dynamically hide/disable fields based on the value of other fields like in the angular autofields example here: http://justmaier.github.io/angular-autoFields-bootstrap/

ng-show is set on one select based on the value of another:
```javascript
...
{ property: 'gender', type: 'select', list: 'key as value for (key,value) in genders', attr: {required: true}},
{ property: 'genderCheck', label:'Are you really?', type: 'select', list: 'key as value for (key,value) in genderCheck', attr: {required: true, ngShow:'$data.gender != null'}},
...
```

**Comment by mhevery** [comment]
I think we should leave this for the community.

**Comment by hitmanmcc** [comment]
I think it's a pity you guys closed this and didn't make this a feature in angular 2, most of the approaches to this that I see detailed here in several issues and even the one that @vsavkin wrote [Forms in Angular 2](http://angularjs.blogspot.pt/2015/03/forms-in-angular-2.html) are better than the alternative. At the moment, it seems overly verbose to build a form with FormBuilder and try to keep controls and models in synched. Either that, or I'm missing something.

**Comment by basvandenheuvel** [comment]
Is this topic of the agenda for ever? Will it ever be implemented?

**Comment by baloodevil** [comment]
Would really like to see this functionality as well.  It is important for enterprise applications which allow a client to define metadata.  It would be nice to know when deciding what should be implemented as part of the main project and what should be a community project, what factors are considered.  I would like to see this as part of the officially supported project (or an officially supported extension to it).  It is a higher level abstraction of writing an application, rather than 'lower level' functionality that is part of template syntax of base forms.  Maybe that is why Misko leans towards the community implementing.

Dynamic form generation is part of a larger whole of functionality for a metadata driven application, like 'higher stack' application builders like salesforce.com and rollbase.  Angular has the lower level building blocks, and when paired with projects like caching, workflow, real-time updates to datastore, (and probably several more) it could form a beautiful open source, meta-data driven, application building tool.

Would love to see it reconsidered.

**Comment by martinmcwhorter** [comment]
FYI - OT

I have started a project for adding metadata to forms:
https://github.com/martinmcwhorter/modelmetadata

This can generate an instance of `FormBuilder` based off a decorated class. 

I hope to soon (in the next week) start another project that will then render these forms from the metadata and generated `FormBuilder` instance.

**Comment by deadZedd** [comment]
+ 1 Agrees with everything @baloodevil said. And angular could be the ones who set the metadata-forms-schema standard

**Comment by pauleveritt** [comment]
@martinmcwhorter Fascinating repo you have there for modelmetadata. You mention a companion project to render forms...did you start on that?

**Comment by travist** [comment]
One solution to consider is [Form.io](https://form.io). We currently have an Open Source Angular 1 JSON form renderer found [here](https://github.com/formio/ngFormio), but I wanted to mention that we are within a month away of having our TypeScript based Angular 2 Dynamic JSON powered form library. This is a complete rewrite for Angular 2 and will serve as a solid solution to this problem.

I will post an update when it is released and available on github for download.  Stay Tuned!

**Comment by tycho01** [comment]
Like mohsen1 I like json-schema, and among his repositories I found mozilla's [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form), and its spin-off Kinto's [formbuilder](https://github.com/Kinto/formbuilder), though not Angular.
[angular-schema-form](https://github.com/json-schema-form/angular-schema-form) appears also to have had plans of transitioning to ng2, though I don't think they've gotten there yet.

**Comment by travist** [comment]
Good to know... I should also mention that we have released an Angular.js [Form Builder](https://github.com/formio/ngFormBuilder) and the [Renderer](https://github.com/formio/ngFormio) as open source which a demo can be seen here http://codepen.io/travist/full/xVyMjo/.  We also have a renderer in [React.js](https://github.com/formio/react-formio). Our big initiative right now is to rewrite all these libraries for Angular 2 starting with the Form Renderer, and moving onto the Form Builder shortly after. 

Great things to come!

**Comment by travist** [comment]
Just wanted to update everyone that we have just released the first iteration of our Form renderer for Angular 2, which brings data-driven, JSON powered forms to Angular 2. Please check it out @ https://github.com/formio/ng2-formio.

We are working to get all of the components in place so that it has feature parity with the Angular 1 renderer @ https://github.com/formio/ngFormio. We are hoping to get to that point by Sept 1st. 

In the meantime, please try it out and contribute!

Thanks!

**Comment by mhelvens** [comment]
@travist: An interesting contribution, but from the examples in the documentation it look like it uses its own json format, rather than [json-schema](http://json-schema.org/)? Does it support json-schema?

**Comment by CSchulz** [comment]
@mhelvens https://github.com/makinacorpus/angular2-schema-form should match your requirement to use JSON schema, haven't tested it yet.

**Comment by mhelvens** [comment]
@CSchulz: Looks good at face value (though it seems the build is broken). We'll have a look, thanks!

**Comment by CSchulz** [comment]
@mhelvens There is a new version which works.
