### ISSUE TITLE
400 HTTP Error not able to access body and status code is 0

### ISSUE THREAD

**Issue by crebuh** [angular/angular#10343]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am shooting an HTTP-Call to our API with the following code.

        public login(body): void  {
             this.http.post(this.apiUrl + '/login', body, { headers: contentHeaders }) 
            .subscribe(response => {
                this._loggedIn.next(!this.jwtHelper.isTokenExpired(response.json().token));
                this._router.navigate(['/']);
            },
            error => {
                console.log(error);
                this._notes.add(new Notification('warning', this.translate.instant('notifications.generalError')));
            }
            );
        }

But when I log the error there is no response body in the Network-Tab of chrome. And also the console is showing me that the error code is 0?

![404_console](https://cloud.githubusercontent.com/assets/5765733/17203284/cf7d4e20-549e-11e6-8206-be9e8b5a6b56.png)
![404_requests](https://cloud.githubusercontent.com/assets/5765733/17203285/d12998fa-549e-11e6-91f1-1fb6776d8c7f.png)

**Expected/desired behavior**

I tested the excact same call with Postman. And I was able to see the body of the response which should look like this:

        {
           "message": "Bad request: login payload data is not valid"
        }

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [all] 

Does anybody has similar issues and which workaround are you using?

**Comment by zoechi** [comment]
http://stackoverflow.com/questions/10143093/origin-is-not-allowed-by-access-control-allow-origin

Postman probably doesn't care about CORS but browsers enforce it.

**Comment by crebuh** [comment]
@zoechi 

thx! we now added the following line to our express app. it works now

      response.setHeader('Access-Control-Allow-Origin', '*');

**Comment by zoechi** [comment]
@crebuh would you mind closing the issue?
