### ISSUE TITLE
No "Restore Packages" option on right-click (it required in tutorial)

### ISSUE THREAD

**Issue by amurtola** [angular/angular#10344]
I'm submitting a

[] bug report
[ ] feature request
[ x] support reques

I am trying to start with angular 2 with this tutorial 

https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html
it's contains these steps:
Step 1: Download the QuickStart files
Step 2: Set up Visual Studio for TypeScript
Step 3: Create the Visual Studio ASP.NET project
Step 4: Copy the QuickStart files into the ASP.NET project folder
Step 5: Restore required packages

i have done  steps 1-4 but with step 5 i have a problem

I have no "Restore Packages" option on right click in visual studio 2015 (on package.json - file)
Any hints?

**Comment by zoechi** [comment]
Documentation issues should be filed in https://github.com/angular/angular.io

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by MarkPieszak** [comment]
This should be filed there, yes, Gunter is right. The documentation there looks right though, it should be there.

Do you have the absolute latest VS2015 update 3, etc? 
Restore Packages can be found when you right click `package.json` or `Dependencies` folders. @amurtola

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by amurtola** [comment]
My question is on stuckoverflow also. Yes i have latest vs2015 and update 3.

**Comment by MarkPieszak** [comment]
Did you see it under the Dependencies folder? Are you using .NET Core or older (4.5 or something)
If you do npm install from the command line that should at least work. @amurtola

**Comment by ebellas** [comment]
@amurtola I had this issue too when following https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html 

After a restart of visual studio the "Restore packages" option appeared when right-clicking packages.json

**Comment by ToxikGoat** [comment]
@mannybellas Thanks!  Restarting Visual Studio (again in my case) did the trick.  And I was also working on the same Angular 2 Startup project.

**Comment by ishwarpadade** [comment]
i have not getting restore package option but after restart visual studio its displayed

**Comment by nizam6431** [comment]
open your project clean solution and try restore package.json

**Comment by TrueBarber** [comment]
I restarted my project and its working fine for me as well. :)

**Comment by ashraf002** [comment]
I restarted visual studio and its working.

**Comment by Fun-Systems** [comment]
Restarted VS and Restore Package appears as top item when right clicked on package.json
