### ISSUE TITLE
Add internationalization to number pipes

### ISSUE THREAD

**Issue by mark-langer** [angular/angular#10356]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The number pipes (decimal, date, etc.) do not provide internationalization; they are hardcoded to en-US format.

**Expected/desired behavior**
Differences in number formatting exist in punctuation. For German users with their preferred language set to de-DE, the format function of the pipes mentioned above should be called with that locale, not with en-US.

**Reproduction of the problem**
{{3500.34 | number: '1.2-2'}} should be displayed as 3.500,34 on e. g. a German system. It is currently displayed as 3,500.34, though, conforming only to US standards.

**What is the expected behavior?**
The format function used by the pipes could possibly be called with userLocale = navigator.language instead of hardcoded "en-US". That way, the number is displayed in the user's set language.
Perhaps, the pipes should accept another parameter, too, which would enable the developer to set a cutom locale that is not influenced by the user.

See [this pull request](https://github.com/angular/angular/pull/10353) for more info. The PR has been rejected since it only solved the problem locally.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Firefox 47] 
 
* **Language:** [TypeScript 1.8 | ES5]

**Comment by vicb** [comment]
closing as pipes not use the `LOCALE_ID`

disclaimer: there are other bugs handled in other issues
