### ISSUE TITLE
Request dependency <=2.68 opens to potential memory exposure vulnerability

### ISSUE THREAD

**Issue by evilaliv3** [angular/angular#10352]
**Do you want to request a _feature_ or report a _bug_?**
This ticket is to report a a potential security vulnerability caused by the request dependency.

**What is the current behavior?**
Various of the dependencies used by angular.js make use of a vulnerable version of the request package (<2.68) that allow potential memory exposure.

Involved dependencies are: insight, fsevents

details:
- https://snyk.io/vuln/npm:request:20160119
- https://github.com/yeoman/insight/pull/48
- https://github.com/strongloop/fsevents/issues/145

In order to address a short term fix it is suggested to modify the current npm shrinkwrap to use request==2.74.0

**Comment by vicb** [comment]
It should be a dev dependency only ?

**Comment by evilaliv3** [comment]
sure it is, but for relevant projects like angular impacting the core developers is even more risky for the whole community.

**Comment by dblVs** [comment]
@alexeagle just checked the yarn lock and the installed version of `request` is `2.88.0` and most outdated dependency is `^2.72.0` if that matters at all. can this be closed?

**Comment by M-a-c-Carter** [comment]
@evilaliv3 
@IgorMinar 
heartbeat

**Comment by pkozlowski-opensource** [comment]
This is obsolete (https://github.com/angular/angular/pull/12738#issuecomment-364284603)
