### ISSUE TITLE
Bug: Router 3.0.0.beta2 – Nested routes not activating

### ISSUE THREAD

**Issue by sharpmachine** [angular/angular#10357]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If I navigate to 'Subject Two' while on 'Subject One', the route is not activated. So once I navigate to 'Subject Two', if I then navigate to Case Plans, it takes me back to 'Subject One' (and visa versa).

I get no routing errors in the console.

**Expected/desired behavior**
I would expect that when I navigate to Subject Two that 'Assessments' is highlighted (active class being added), and navigating between 'Assessments' and 'Case Plans' would do so in the context of Subject Two

**Reproduction of the problem**

1. Navigate to Subject One
2. From within Subject One, navigate back and forth between Assessments and Case Plans. Notice the Route id always remains '1'
3. Navigate to Subject Two
4. From within Subject Two, navigate back and forth between Assessments and Case Plans. Notice the Route id will change back to '1'

If you navigate back to home and then try navigating to Subject Two and go between Assessments and Case Plans, it works...until you try to go to Subject One

https://plnkr.co/edit/upLeYcMNctfGtvKrBeVo

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome 52 OSX El Capitan
 
* **Language:** Typescript

**Comment by brandonroberts** [comment]
This issue has already been fixed in master and will go out with the next release

**Comment by sharpmachine** [comment]
Awesome. Thanks @brandonroberts.
