### ISSUE TITLE
Router: how to launch with other than index.html

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10359]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request
[ ] support request 
```

**Current behavior**
Routed apps work fine when the web host page is named `index.html`.

Don't know how to make it work if the file is not called `index.html`. 

The real world example for this is a server that serves the application web page out of someplace like `~/views/tour-of-heroes.html`.

I can't just set the base href to `~/views` because other resources ... including images and css ... are served from another server location such as `~/resources`.

**Expected/desired behavior**

We need a way to tell the router that the base for routed components is a different place than the base for everything else.

**Reproduction of the problem**

Can't show in plunker because not allowed to tell plunker to use anything other than `index.html` in the root folder.

Attached a zip file of the sample code for the  "Tour-of-Heroes - Router" chapter (ToH-5).

[toh-router-no-index-html.zip](https://github.com/angular/angular/files/388982/toh-router-no-index-html.zip)
1. Install the typings and node_modules
2. Make sure the node_modules/@angular are for the appropriate build
3. `npm start` launches the app with `index.html`
4. Confirm it works
5. Adjust browser bar to reference `app.html` (the alternative to `index.html`) - it fails

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5 candidate July 28, 2016
- **Browser:** [Chrome] 
- **Language:** [all]

**Comment by vsavkin** [comment]
Low priority. Pushing it until after the final is out.
