### ISSUE TITLE
bug(router) unable to navigate to aux route via router dsl

### ISSUE THREAD

**Issue by choeller** [angular/angular#10351]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When defining an aux route in a nested route there is no way to enable this aux-component. Having this config:

 ```ts
[
  {path: 'dashboard', component: DashboardComponent}, 
  ...
  {path: 'tasks',  component: TasksComponent,
    children: [
      {path: '', component: TaskListComponent},
      ...
      {path: 'overview/:id', component: TaskOverviewComponent, outlet: "right"},
    ]
  },
```

and this code in TasksComponent html:

```
<div id="left">
  <router-outlet></router-outlet>
</div>

<div id="right">
  <router-outlet name="right"></router-outlet>
</div>
```

I can enable the right-outlet next to the task-list by manually entering the url:

```
http://localhost:4200/tasks/(right:overview/3)
```

Nevertheless I can't find a way to activate this route via Router-DSL. I found this commit:

https://github.com/angular/angular/commit/ded518d47f6555c779a2c34e3627601c9480ec5f

But none of the provided examples works for me, when trying to activate the aux-route when being on URL:

```
http://localhost:4200/tasks
```

I tried:

```html
  <a [routerLink]="['/tasks', {outlets: {'right': ['overview',task.id]}}]">
    Show task overview
  </a>
```
this creates the following URL:
```
http://localhost:4200/tasks;outlets=%5Bobject%20Object%5D
```
trying to use a relative link is even worse:
```html
  <a [routerLink]="['./', {outlets: {'right': ['overview',task.id]}}]">
    Show task overview
  </a>
```
this leads to an exception:
```
Uncaught EXCEPTION: Error in package:841 class TaskItemComponent - inline template:2:5
ORIGINAL EXCEPTION: TypeError: Cannot read property 'path' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'path' of undefined
    at createNewSegment (http://localhost:4200/main.bundle.js:68910:58)
    at updateSegment (http://localhost:4200/main.bundle.js:68850:16)
    at Object.createUrlTree (http://localhost:4200/main.bundle.js:68708:9)
    at Router.createUrlTree (http://localhost:4200/main.bundle.js:16882:34)
    at RouterLinkWithHref.updateTargetUrlAndHref (http://localhost:4200/main.bundle.js:36241:36)
    at RouterLinkWithHref.ngOnChanges (http://localhost:4200/main.bundle.js:36228:74)
    at DebugAppView._View_TaskItemComponent0.detectChangesInternal (TaskItemComponent.ngfactory.js:215:58)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/main.bundle.js:62841:14)
    at DebugAppView.detectChanges (http://localhost:4200/main.bundle.js:62946:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:4200/main.bundle.js:62867:19)
```

One other strange fact is, that when I first activate one aux route manually with the correct URL (smth. like http://localhost:4200/tasks/(right:overview/3) ) afterwards both versions seem to create the correct link in the navigation preview of the browser but when clicking on the link I get:

```
Error: Uncaught (in promise): Error: Cannot match any routes: 'tasks'
    at resolvePromise (zone.js:538)
    at zone.js:515
    at ZoneDelegate.invoke (zone.js:323)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (ng_zone_impl.js:53)
    at ZoneDelegate.invoke (zone.js:322)
    at Zone.run (zone.js:216)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.js:44)
    at ZoneDelegate.invokeTask (zone.js:355)
```

**Expected/desired behavior**

It should be possible to enable aux-routes by Router-DSL

**What is the motivation / use case for changing the behavior?**

Being able to use aux-routes ;)

**Please tell us about your environment:**

* **Angular version:**  2b63330a361a9832a73f59c2104758990dea889c
 
* **Browser:** [all] 
 
* **Language:** [TS]

**Comment by vsavkin** [comment]
@choeller could your provide a repro plunker using a nightly build? 

We haven't released in about a month. So the latest release of the router on NPM doesn't contain the changes you are trying to use.

**Comment by zoechi** [comment]
I created a Plunker for a similar [SO question](http://stackoverflow.com/questions/38647327/angular2-auxiliary-route-not-working) http://plnkr.co/edit/hAFHwhh41H0rRJJ1J2rJ?p=preview but I don't know how to make it use nightly build.

**Comment by choeller** [comment]
@vsavkin The bug is based on commit https://github.com/angular/angular/commit/2b63330a361a9832a73f59c2104758990dea889c , so the changes needed should be in there. I'll try to get a plnkr up with the latest nightly build!

**Comment by choeller** [comment]
@vsavkin Here is the plnkr: http://plnkr.co/edit/r2qHinshrCHgnOVg8ArM?p=preview

Just click "To tasks" and then "Open aux route". I also added the attempt to open the aux with a relative link, but this leads to an exception immediately.

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/commit/afcb3c0035d216ddfffe02c42d1d1d6ce2daa8b7
