### ISSUE TITLE
Transform `Template#url` values to `inline` templates

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#1035]
Per @yjbanov 's recommendation, this avoids unnecessary `XmlHttpRequest`s in the deployed application.

**Comment by mhevery** [comment]
Sounds right to me.

**Comment by kegluneq** [comment]
@jakemac53, for the future this is another issue iirc you already have some experience with.

Angular apps are single-screen, so all url references in `@Component` annotations should be relative to the entry point's location -- I'm fairly certain the way we're doing this right now is incorrect at least some of the time.

**Comment by mhevery** [comment]
@kegluneq yes, this area needs work. The URLs should be relative to the components (so that they can be reusable), but i don't think that is working yet.

**Comment by gautelo** [comment]
+1 That's been an issue in 1.x since the start. Glad to hear it's being addressed in 2.x!
