### ISSUE TITLE
ngSwitch with Async Pipe not working

### ISSUE THREAD

**Issue by smith64fx** [angular/angular#10358]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
<div [ngSwitch]="(superhero | async).name">
	<div *ngSwitchCase="Son Goku">Beats 'em all</div>
	<div *ngSwitchDefault>Mr. Noname</div>
</div>
```

Produces Error

> browser_adapter.js:84 ORIGINAL EXCEPTION: TypeError: Cannot read property 'name' of null

**Expected/desired behavior**

Should work!

I used to make it work using this pre-check

```
<div *ngIf="(superhero | async)">
        <div [ngSwitch]="superhero.name">
	        <div *ngSwitchCase="Son Goku">Beats 'em all</div>
	        <div *ngSwitchDefault>Mr. Noname</div>
        </div>
</div>
```
**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [ Chrome 51.0 ] 
 
* **Language:** [ TypeScript ]

**Comment by vicb** [comment]
`superhero | async` so you probably can't `superhero.name`.

Please add expected, current behavior and a Plunker when submitting an issue.

However this looks like a support request, please use gitter orStackOverflow

**Comment by smith64fx** [comment]
This is a bug!
You can try doing this and you will get the error.

Expected behaviour is, that I won't get an error?! Current behaviour is getting an error? Why is this not enough..

**Comment by ericmartinezr** [comment]
Try with ` <div [ngSwitch]="(superhero | async)?.name">`

**Comment by smith64fx** [comment]
@ericcarraway Thx Bro, solved the problem :)
