### ISSUE TITLE
Digesting problem with IE10 and websocket usage

### ISSUE THREAD

**Issue by matthewdaniel** [angular/angular#10350]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a websocket calls obs.next (in various methods) it will not cause the dom to be updated in IE10.

If I remove the websocket and instead of the observable.create just do a timeout that emits the value like
setTimeout(() => { obs.next('some value'); }, 100) 
then things work fine. it is only when the websocket is calling the obs ( or calling a function which calls the obs).

**Expected/desired behavior**
Expect the websocket.onmessage to cause the dom to reflect new data

**Reproduction of the problem**
My plnkr doesn't load in IE, but here is the link http://embed.plnkr.co/T3osLgSKOenaMQD1bBmG/
The changeset that reproduces the issue can be seen here
https://github.com/matthewdaniel/angular2-ie10-bug/commit/eaf8a7cef79550d3b0a7c80fc711595b71c6b3da

**What is the expected behavior?**
In chrome the text will show after 1 second but in IE it doesn't show. However in my app i have something bound to a form element and as soon as I click into that the result shows.

**What is the motivation / use case for changing the behavior?**
Trying to get a shared list of items to be dynamically updated between concurrent users. User A clicks list item 1 and user B sees it now as being edited.

**Please tell us about your environment:**
ng new -> brokect is currently at rc.4 - backend doesn't matter since i can reproduce it with echo.websocket.org
- **Angular version:** 2.0.0-rc.4
- **Browser:** IE10 IE?
- **Language:** Typescript

**Comment by keithmichelson** [comment]
I'm having the exact same issue. Same release and I also see the problem in edge. No console errors just the data doesn't update.

**Comment by sicaner** [comment]
rc4, ie: 
the same problem.

**Comment by matthewdaniel** [comment]
For a work around I check to see if the browser is ie and if so i put the results into a private variable. then outside the websocket functions i set up a setInterval for about 100ms that just watches for non null in that variable and calls next with the data and resets to null.

**Comment by keithmichelson** [comment]
Another work around that I'm doing (not sure if it's ideal) is to manual update with an NgZone every time I get a message.

**Comment by woppa684** [comment]
Also forcing a change detection with a ChangeDetectorRef seems to do the trick. By the way, I also notice this issue without using observers, it doesn't update with everything you do in a websocket message without manually triggering the change detection.

**Comment by woppa684** [comment]
I've create a minimal plunker to demonstrate this. When viewing in IE the bound {{name}} will only be updated when the lines to run in the angular zone are uncommented. In other browsers this just works as expected.

http://plnkr.co/edit/LFGFJzT6twH5ZejD33zx?p=preview

**Comment by woppa684** [comment]
@vicb @btford Any news on this? Could this be a bug in https://github.com/angular/zone.js?

**Comment by woppa684** [comment]
FYI, I managed to fix this issue by patching the zone.js NO_EVENT_TARGET array to also include WebSocket, like so:

```
var NO_EVENT_TARGET = 'ApplicationCache,EventSource,FileReader,InputMethodContext,MediaController,MessagePort,Node,Performance,SVGElementInstance,SharedWorker,TextTrack,TextTrackCue,TextTrackList,WebKitNamedFlow,Window,Worker,WorkerGlobalScope,XMLHttpRequest,XMLHttpRequestEventTarget,XMLHttpRequestUpload,IDBRequest,IDBOpenDBRequest,IDBDatabase,IDBTransaction,IDBCursor,DBIndex,WebSocket'.split(',');
```

This looks like a bug in zone.js to me...

**Comment by DzmitryShylovich** [comment]
Seems was fixed here https://github.com/angular/zone.js/issues/468

**Comment by atscott** [comment]
Fixed in https://github.com/angular/zone.js/pull/493
