### ISSUE TITLE
Tutorial https://angular.io/docs/ts/latest/tutorial/toh-pt6.html is broken

### ISSUE THREAD

**Issue by ghoben** [angular/angular#10361]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The last steps within the tutorial are not given. futhermore the outlines of the example contents provides a bad MD file.

**Expected/desired behavior**

All steps are shown
**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by ghoben** [comment]
BAD FILENAME: ../../../_fragments/toh-6/ts/app/rxjs-operators.ts.md   Current path: docs,ts,latest,tutorial,toh-pt6 PathToDocs: ../../../

**Comment by vicb** [comment]
Please re-open on https://github.com/angular.io
