### ISSUE TITLE
Router: Redirecting to a route with lazy loaded children fails

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#10376]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Given the route config

```js
export const routes: RouterConfig = [
  {
    path: '',
    redirectTo: '/lazy',
    pathMatch: 'full'
  },
  {
    path: 'lazy',
    component: LazyParentComponent,
    loadChildren: 'app/lazy/lazy-loaded.module#LazyModule'
  }
];
```

When navigating to `/` an error is thrown: `TypeError: Cannot read property 'routes' of undefined`

**Expected/desired behavior**

Redirecting to a route with lazy loaded children should navigate correctly

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by mikmar88** [comment]
I have the same problem with the router.navigate inside a callback function generate from a web servise response.

Cannot read property router of undefined

**Comment by brandonroberts** [comment]
@mikmar88 sounds like a separate issue. Will you open another issue with an example?

**Comment by brandonroberts** [comment]
cc: @vsavkin

**Comment by vsavkin** [comment]
I cannot repro the issue on using the latest master. Could you repro the problem using the nightly build?

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/commit/3a307c27945b052420b16936388e299e7977088e
