### ISSUE TITLE
Why DynamicComponentLoader.loadNextToLocation is actually not next to Element

### ISSUE THREAD

**Issue by golfapipol** [angular/angular#10374]
**I'm submitting a loadNextToLocation issue**
```
[x] bug report
```

**Current behavior**
when I use DynamicComponentLoader.loadNextToLocation to make list of component but it's append after component that I created with DynamicComponentLoader

**Expected/desired behavior**
It's should append next to targeted location correctly, or I do something wrong

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 2.0.0-beta]

**Comment by ericmartinezr** [comment]
The explanation is here https://github.com/angular/angular/issues/9035, DCL is deprecated anyway.

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr for helping out with the issues. Your answer is spot-on, as always!
