### ISSUE TITLE
request| feat: expand build-time features

### ISSUE THREAD

**Issue by PatrickJS** [angular/angular#10371]
There should be more build-time, or precompile-time, features such as default selector by converting the class name to a dash-case selector. Since Angular 2 is an html compiler and webpack is a js compiler there's really something powerful that can come out of the two if they work together more. For example, determining defaults for selector/template/styles/inputs/output by analysing the code base or class could remove all the decorators or at least provide a lot of powerful default values. With ngc you won't really need the decorators after compiling the template. With webpack or ngc you won't need Reflect since you can annotate the class. There would be so much sugar that everybody will have cavities 

[![github-tipe-logo](https://user-images.githubusercontent.com/1016365/34912701-7edec34c-f89c-11e7-8c89-bed6cef064b5.png)](https://tipe.io?ref=github-comment)

**Comment by sirajc** [comment]
Agree on this, convention over configuration

**Comment by pkozlowski-opensource** [comment]
If we want to move it forward then we need very concrete proposals. Here are few ideas:
* infer a selector from the class name (only if not provided)
* default template / style URLs (#5183)
* generate code to convert inputs to their declared type (for numbers, booleans)
* ...

**Comment by gdi2290** [comment]
@pkozlowski-opensource that features you listed out can easily be created with a webpack-loader so let's think of more 😄 

The idea here is being able to configure everything after your app reaches a certain scale. In the beginning of creating an Angular2 app you can avoid configuration by sticking with convention and progressively applying configurative when needed. For example, we can make everything an input that's not private. This makes a lot of sense and if you wanted to scope your inputs then you would include `@Input()`. For output, we can do the same for EventEmitter of having any EventEmitter prop be an output. For templates and style we can also look for a corresponding file with the correct type. Components and decorations for NgModule would be a lot more involved but they can also be hidden. To be honest, all of NgModule can be hidden away with webpack so you won't even need to know that it exists. We can even hide bootstrap which is assuming you're developing for the browser. Again all this magic would be great for developers starting off so it will be like Angular1 magic days of everything just working. If a developer wants more control then they just need to configure their app and they can do so using all these decorators

**Comment by gdi2290** [comment]
k I just now got template,selector,styles all working to default values in webpack. will publish soon

**Comment by vicb** [comment]
Is there support for offline compile too ?

**Comment by gdi2290** [comment]
I published the `@Component` metedata defaults package
https://github.com/AngularClass/angular2-conventions-loader
this provides defaults for metadata in the component decorator then ngc can run afterwards to convert the decorators to annotations. This is also at build-time so you won't run into any problems with minification because that runs afterwards

**Comment by robwormald** [comment]
there's a number of these sorts of things i'd like to do as well, but I think the correct answer is going to be extensibility in the compiler layer - then it should work for both online and offline, but it'll require significant planning. See also transforms coming to typescript soon.

**Comment by jessicajaniuk** [comment]
Closing this issue as it has insufficient votes.
