### ISSUE TITLE
Still seeing Cannot resolve parameters after using @Intectable and @Inject

### ISSUE THREAD

**Issue by davetayls** [angular/angular#10373]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I get the error message given when Angular can't find the meta data for DI. This is during a Karma (mocha) test.

Error: "Cannot resolve all parameters for 'CountryAndStateService'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'CountryAndStateService' is decorated with Injectable."

```typescript

// CountryAndStateService.ts
@Injectable()
export class CountryAndStateService {

  constructor(@Inject(Http) private http:Http) {
  }

// ...

// CountryAndStateService.spec.ts
describe('CountryAndStateService', () => {

  beforeEach(() => {
    addProviders([
      HTTP_PROVIDERS,
      Http,
      CountryAndStateService
    ]);
  });

  it('can load the CountryAndStateService',
    inject([CountryAndStateService],
      (svc:CountryAndStateService) => {
        should.exist(svc);
      }));

});
```

I notice that the JS output is different for what my TypeScript 1.8 is emitting to what the Angular code has.

Http JS looks like

```javascript
    /** @nocollapse */
    Http.ctorParameters = [
        { type: interfaces_1.ConnectionBackend, },
        { type: base_request_options_1.RequestOptions, },
    ];
```

CountryAndStateService JS looks like
```javascript
	    CountryAndStateService = __decorate([
	        core_1.Injectable(),
	        __param(0, core_1.Inject(http_1.Http)), 
	        __metadata('design:paramtypes', [http_1.Http])
	    ], CountryAndStateService);
	    return CountryAndStateService;
```

Inside the angular reflection_capabilities.js it isn't finding `this._reflect` even though as you can see the class is being decorated

```javascript
        // API for metadata created by invoking the decorators.
        if (isPresent(this._reflect) && isPresent(this._reflect.getMetadata)) {
            var paramAnnotations = this._reflect.getMetadata('parameters', typeOrFunc);
            var paramTypes = this._reflect.getMetadata('design:paramtypes', typeOrFunc);
            if (isPresent(paramTypes) || isPresent(paramAnnotations)) {
                return this._zipTypesAndAnnotations(paramTypes, paramAnnotations);
            }
        }
```

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

See above ^^

**What is the expected behavior?**

I expect `@Injectable()` on the `CountryAndStateService` class to annotate the code so the DI knows where to get Http from.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome, PhantomJS
 
* **Language:** TypeScript 1.8 ES5

**Comment by vicb** [comment]
Please try to reproduce in a plunker.

**Comment by davetayls** [comment]
Hi. Sorry for the delay. I'm on holiday and will create one as soon as I return. Thanks for your patience

**Comment by vicb** [comment]
No pb, please create a new issue when you have a plunkr
