### ISSUE TITLE
npm package dependencies for reflect-metadata & rxjs in the package.json cause unmet peer dependencies.

### ISSUE THREAD

**Issue by faddah** [angular/angular#10389]
**I'm submitting a ...  (check one with "x")
```
[**X** ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

currently, in your angular2 v2.0.0-beta.17, the npm package dependencies for relfect-metadata & rxjs are listed as thus in your package dependencies in your package.json file —

```

...
 "name": "angular2",
  "optionalDependencies": {},
  "peerDependencies": {
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
...

```

so when you do an `$ npm ls -g --depth=0` (or `$npm ls` if you have it stored in a local directory/repository), you get —

```

...  // ^^^ many other packages listed before this, including angular2
├── mongoose@4.5.7
├── n@2.1.3
├── node-inspector@0.12.8
├── nodemon@1.10.0
├── npm@3.10.5
├── npmlog@4.0.0
├── protractor-coffee-preprocessor@0.0.1
├── pug@2.0.0-beta4
├── UNMET PEER DEPENDENCY reflect-metadata@0.1.3
├── require@2.4.20
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.10
├── sass@0.5.0
├── socket.io@1.4.8
├── sync-exec@0.6.2
├── typescript@1.8.10
├── webpack@1.13.1
├── yo@1.8.4
└── zone.js@0.6.12

npm ERR! peer dep missing: reflect-metadata@0.1.2, required by angular2@2.0.0-beta.17
npm ERR! peer dep missing: rxjs@5.0.0-beta.6, required by angular2@2.0.0-beta.17

```

**Expected/desired behavior**

you should have done a `^` before each of the version dependencies for reflect-metadata & rsjx in the package.json file, like thus —

```

...
 "name": "angular2",
  "optionalDependencies": {},
  "peerDependencies": {
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.2",
    "rxjs": "^5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
...

```

...then any `$ npm ls` on your packages will not give the `UNMET PEER DEPENDENCY`.  i can probably do a pull request fixing this.

**Reproduction of the problem**

1. install latest node.js LTS or current, v4.4.7 or 6.3.1 as of today, 29-July-2016 )and npm along with that.
2. install npm packages, either globally (`-g`) or to a local directory/repository, including your angular2 and its npm package dependencies.
3. after all is installed, run an `$ npm ls -g --depth=0` if you installed angular2 package globally, or `$npm ls --depth=0` if installed to a local directory/repository. you will see the `UNMET PEER DEPENDENCY` error.

**What is the expected behavior?**

no `UNMET PEER DEPENDENCY` errors when compiling or running a `$npm ls`.

**What is the motivation / use case for changing the behavior?**

this should not be happening, all you need to do is add a `^` before 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all  & command line/terminal
 
* **Language:** all , particularly JavaScript ES5 or ES6/2015, Node.js v6.3.1, npm v3.10.5, npm angular2 package v2.0.0-beta17, and whatever you are using as a command line shell (bash, tsh, etc.).

**Comment by CarlCui** [comment]
If you have been working with unstable libs, including angular 2 :smile: , you will see that we don't like `^`. If you let npm do the update for you, often after a `npm install`, something breaks. :joy:

**Comment by faddah** [comment]
@CarlCui  - however, if you go in, edit the package.json and just use the standard semver '^' in the `.../node_modules/angular2/package.json` for the dependencies, the error goes away and there are no more issues like that. and having to go hunt down the package.json like that is annoying to most users that just want their packages to work together. doing a PR.

best,

— faddah
    portland, oregon, u.s.a.

**Comment by CarlCui** [comment]
@faddah The warning is to warn you that program might fail if you insist on using a different version. It's not trying to annoy you. :smile:

**Comment by faddah** [comment]
@CarlCui - it is erroneous. these are new, updated version of the npm package dependencies you have production. i have not seen it break anything by using updated versions of the dependent npm packages. semver is an industry standard and these packages get updated constantly. anyway, filed a PR #10393 (tho' i have zip idea on how to "unit-test" on a simple one character package.json fix). if the angular team doesn't want it, they don't have to include it.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by ericmartinezr** [comment]
Those are the versions the framework depends on, not your project. If they depend on new versions without testing them it could break everything, that is why they use specific versions. If everything works in your project cool, but your PR may break a lot of other projects. 

The message it is not erroneous, it's warning you, you can simply ignore it.

**Comment by robwormald** [comment]
we're keeping versions locked during angular2's development process, on purpose. once we release 2.0.0 stable, we'll loosen the restrictions up.
