### ISSUE TITLE
ngMessage

### ISSUE THREAD

**Issue by brycecr** [angular/angular#10384]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In bower-angular-message-format, the minified version of the package is imported directly in index.js.

from https://github.com/angular/bower-angular-message-format/blob/master/index.js
```
require('./angular-message-format.min');
module.exports = 'ngMessageFormat';
```

**Expected/desired behavior**
It seems like this package should be at parity with other bower-angular packages, for example angular-touch, in order to play nice with clients build processes:

https://github.com/angular/bower-angular-touch/blob/master/index.js
```
require('./angular-touch');
module.exports = 'ngTouch';
```

@metamatt

**Comment by metamatt** [comment]
Note this isn't just a cosmetic issue; see https://github.com/angular/angular.js/issues/14966

**Comment by vicb** [comment]
Close as this repo is angular 2
