### ISSUE TITLE
core: OnPush strategy for exported components

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#10380]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
```

**Current behavior**

While working on [Bootstrap-powered directives](https://ng-bootstrap.github.io) I'm trying to agressivelly use the `OnPush` change detection strategy. Most of the time all works pretty well but there is a certain situation where using `OnPush` leads to inconsistent behavior. 

Let's assume that we've got a component that:
- uses `ChangeDetectionStrategy.OnPush`
- is exported
- has a public method that can be called on an exported instance.

In such a case it is possible to call a method on an exported instance. Such a method call can change component's state, emit events etc. but those changes won't be picked up for rendering.

**Expected/desired behavior**

In the scenario described above a component should be refreshed if a called methods results in a custom event being emitted. This would be a strong indicator that some state changed and UI needs to get updated.

**Reproduction of the problem**

https://plnkr.co/edit/JP1vMvryva5nJq8Ez1ON?p=preview

**What is the expected behavior?**

Using https://plnkr.co/edit/JP1vMvryva5nJq8Ez1ON?p=preview both buttons should increment the counter.
- **Angular version:** 2.0.0-rc.4

Discussed with @mhevery

**Comment by vicb** [comment]
Is it really a "bug" ?
Couldn't you explicitly trigger the CD ?

**Comment by pkozlowski-opensource** [comment]
> Is it really a "bug" ?

One could argue. In any case I've discussed this with @mhevery and he advised to open an issue.

> Couldn't you explicitly trigger the CD ?

I'm sure that there are work-arrounds, but that's not the point. As for your suggestion: the thing is that a given method can be called either from "inside" or "outside" so sometimes I would have to trigger CD and sometimes no. And I'm not sure I could reliably distinguish between the 2 "sometimes"

**Comment by vicb** [comment]
An issue can be a feature :)

If even you can't distinguish how would angular do ?
And do you actually really need to distinguish ? (It would not hurt to mark the component as dirty of it really is ?)

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
