### ISSUE TITLE
Framework should `preventDefault` for form submit events

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1039]
The `ng-submit` directive in angular 1 automatically does `preventDefault()` for form submit events, since most people haven't wanted this behavior for about a decade. Angular 2 should probably do the same thing.

UPDATE:
Event handling for `submit` seems to be broken. I have this in my template:
```html
  <form (submit)="submit('form submit')">
    <button md-button>SUBMIT</button>
    <button>Native button</button>
  </form>
```
(tried both `(submit)` and `(^submit)`)

and this method in my component:
```js
  submit(msg: string, event: Event) {
    debugger;
    alert('HALT');
    event.preventDefault();
    this.greeting = msg;
  }
```

Interacting with either button just causes a full form submit and my event handler is never executed. There are no errors thrown. 

@rkirov Any ideas?

**Comment by naomiblack** [comment]
Decision: The return value of the event handler should control whether or not `preventDefault` happens.

@pkozlowski-opensource can you own this?
