### ISSUE TITLE
router fragment in the last router package doesn't work totally

### ISSUE THREAD

**Issue by Flounn** [angular/angular#10395]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Fragment in the last router package (3.0.0-beta.2)  doesn't work totally. The browser needs to resfresh to go on the fragment.
Also, the fragment stay from the URL. Impossible to remove the fragment.

**Expected/desired behavior**
router.navigate() with a fragment => web navigator go to the fragment without refresh
router.navigate() without the old fragment => old fragment remove from the url
  

**Reproduction of the problem**
https://plnkr.co/edit/yIorBdAqjnK3QtywsJg3
On the crisis-center page, i had a fragment in the html and 2 buttons binding on 2 function : 1 to go on the fragment and the other one to remove the fragment from the url.
The observer on the routerstate.fragment in the ngOnInit show the remove problem.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **@angular/router version:** 3.0.0-beta.2
 
* **Browser:**

Firefox 47.0 | IE 11
 
* **Language:** TypeScript 1.8.10 | ES5 |

Sorry if the bug has already reported.

Thank you for this framework, it's a really nice job.

**Comment by brandonroberts** [comment]
This has already been changed in master(23ee29b6a2ae396f6ec13f71c9552e3e0a983c3c) and fragments and query params no longer persist across navigation unless specifically told to do so.

**Comment by pkozlowski-opensource** [comment]
Thnx @brandonroberts !

**Comment by DanielYKPan** [comment]
I tried the New Version(RC5). The fragments and query params did no longer persist across navigation. But when I navigate to a route with a fragments (#myFragment),  web navigator didn't go to the fragment.

**Comment by Flounn** [comment]
I have the same issue.

**Comment by brandonroberts** [comment]
That's a separate issue that needs to be filed.
