### ISSUE TITLE
Support CSS on components (backport from ng2)

### ISSUE THREAD

**Issue by schmod** [angular/angular#10390]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Has there been any discussion about backporting Angular 2's [component CSS support](https://angular.io/docs/ts/latest/guide/component-styles.html) (with emulated view encapsulation) support to work with Angular 1 components?

While projects like [angular-css](https://github.com/castillo-io/angular-css) provide similar functionality, there does not appear to be a solution for Angular 1.x applications that provides true view-encapsulation.  

IMO, this is one of the most useful (and under-appreciated) features of Angular 2.  This feature would be an enormous benefit to existing Angular 1.x applications, and could provide another tool for owners of legacy applications to gradually adopt Angular 2 (while improving the modularity of their existing applications).

----

If this has been discussed before, please feel free to close as a duplicate -- I couldn't find any previous discussion on this topic.

**Comment by pkozlowski-opensource** [comment]
I don't think this was discussed, maybe @petebacondarwin has more info. In any case this issue doesn't belong here - if such thing is to be discussed / implemented it is going to happen in the Angular 1 repo: https://github.com/angular/angular.js

**Comment by schmod** [comment]
Doh.  My bad.
