### ISSUE TITLE
Router: add RouterModule.appendRoutes method

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10396]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request 
```
We like to factor an application into sub-modules organized around feature areas. Each of these sub-modules may have its own routes referencing its own components.

We'd like to load these sub-modules together in one flat route-space.

We _choose not not_ to load these sub-modules asynchronously. We just want to pool their routes with the routes of other sub-modules resulting in a single, consolidated route space for the entire app.

That's what we're doing for the samples in the A2 docs "style-guide".

**Current behavior**

The syntax we have to use is less than ideal. Here's an excerpt from the style-guide
```
// ... other imports

//// Submodule imports /////
import  * as s0101 from '../01-01/app/sub.module';
import  * as s0410 from '../04-10/app/sub.module';
// ... more submodule imports

///////////////////
const moduleMetadata = {
  imports: [
    s0101.SubModule,
    s0410.SubModule,
      ... more sub-module imports ...

    RouterModule.forRoot([
      { path: '', redirectTo: '/01-01', pathMatch: 'full' },
      s0101.route,
      s0410.route,
      ... more sub-module routes.
    ], { }),
  ],
  declarations: [ AppComponent ],
  entryComponents: [ AppComponent ]  
};

import { bootstrap } from '@angular/platform-browser-dynamic';
bootstrap(AppComponent, moduleMetadata);
```
Notice that our sub-module files have to export a `route` and we have to add them to the top-level route configuration by hand.

An example sub-module file
```
export const route =  {  path: '01-01', component: SubComponent  };

@NgModule({
  imports: [ BrowserModule, FormsModule ],
  declarations: [
    SubComponent,
    HeroesComponent,
    // ... other module-private components,
  ],
  exports: [ SubComponent ]
})
export class SubModule {}
```

**Expected/desired behavior**

I'd rather each sub-module could add its routes without help from the parent module.
```
// ... other imports

//// Submodule imports /////
import  { SubModule as s0101 } from '../01-01/app/sub.module';
import  { SubModule as s0410 } from '../04-10/app/sub.module';
// ... more submodule imports

///////////////////
const moduleMetadata = {
  imports: [
    s0101,
    s0410
      ... more sub-module imports ...

    RouterModule.forRoot([ { path: '', redirectTo: '/01-01', pathMatch: 'full' }  ], { }),
  ],
  declarations: [ AppComponent ],
  entryComponents: [ AppComponent ]
};

import { bootstrap } from '@angular/platform-browser-dynamic';
bootstrap(AppComponent, moduleMetadata);
```
Now the master parent module is simpler and knows less about its sub-modules.

The revised sub-module file with **new *RouterModule.appendRoutes* method**:
```
@NgModule({
  imports: [ 
     BrowserModule, FormsModule,
     RouterModule.appendRoutes([ {  path: '01-01', component: SubComponent  } ])
  ],
  declarations: [
    SubComponent,
    HeroesComponent,
    // ... other module-private components,    
  ],
  exports: [ SubComponent ]
})
export class SubModule {}
```
**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 candidate
 
* **Browser:** [all ] 
 
* **Language:** [all]

**Comment by filipesilva** [comment]
I'd really like to see something like this as well. Having to pull routes out of modules to register them creates a bit more coupling than I'd like, especially with several levels deep of NgModules.

**Comment by brandonroberts** [comment]
This makes me wish you could use the `children` entry in the route configuration for a module since you have to use `loadChildren` to load a module asynchronously.

**Comment by wardbell** [comment]
When we do this, `appendRoutes` should probably `export` the configured components from the submodule as well as add them to `entryComponents`

**Comment by brandonroberts** [comment]
To add some more context to this issue, let's use our current router dev guide as an example. I want to break up the app into 3 modules, App, Heroes and Crisis Center. Each one of these modules has associated components and routes. 

Currently the router will add any components in its configuration to the `entryComponents` of the module where the routes are defined. This would include routes that use components from the Heroes and Crisis Center modules. Those modules need to explicitly declare and export those components to prevent the main App module from "taking ownership" of those components since they have been automatically added to the main App module's `entryComponents`.

Ideally, `RouterModule.appendRoutes` would allow us to define routes in sub-modules, it would add the route configuration component to that respective module's `entryComponents` and `exports`. Then we could have a clear separation of those routes and components that are exclusive to each App, Heroes and Crisis Center modules in this case.

**Comment by wardbell** [comment]
Hooray!  Btw, there is no `appendRoutes`. Rather the work of appending is accomplished with existing `forRoot` and `forChild`. That's even better.
