### ISSUE TITLE
[Bug] Animation API error in Safari, undefined.

### ISSUE THREAD

**Issue by Luchillo** [angular/angular#10407]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
The same animation works ok on chrome, but the animation breaks on safari, be it mobile or pc browser, currently using `web-animations-js` polyfill.

![image](https://cloud.githubusercontent.com/assets/9698639/17272170/3b18d21e-5655-11e6-96bc-23e8ade10b4e.png)

**Please tell us about your environment:**
Mac: El Capitan
Safari: 9.1.1

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Safari 9.1.1, iOS XX Safari 
 
* **Language:** all

**Comment by matsko** [comment]
Thanks for making the issue. Can you please provide a plunkr example of this? It's not possible for me to deduce what's going on here with just the callstack.

**Comment by Luchillo** [comment]
Yes, but is there an starter plunkr to fork?

**Comment by matsko** [comment]
Use this one: http://plnkr.co/edit/414ar3acXpHymiPrSeun?p=preview

**Comment by Luchillo** [comment]
What version is using that plunkr?

**Comment by matsko** [comment]
HEAD

**Comment by Luchillo** [comment]
Hmm i will try to trigger the error but maybe it has to do with the RC.4 version.

**Comment by matsko** [comment]
This most likely has to do with: #9752

**Comment by Luchillo** [comment]
Not so sure about that, my animations does have an ease function defined:
```ts
import {
  Component,
  Input,
  trigger,
  state,
  style,
  transition,
  animate
} from '@angular/core';

export var animHeight = trigger('animHeight', [
  state('true', style({
    height: '*',
    opacity: '1',
  })),
  state('false', style({
    height: 0,
    opacity: 0,
    overflow: 'hidden',
    display: 'none'
  })),
  transition('* => *', animate('250ms linear'))
]);
```

**Comment by Luchillo** [comment]
Funny thing it works in one page and in other it doesn't, let me check better if it's because i nest animations.

**Comment by Luchillo** [comment]
Ok i found something, it seems to work with the one above named 'animHeight' but when using this error pops out:
```ts
export var taoTableRowSelected = trigger('taoTableRowSelected', [
  state('true', style({
    height: '*',
    opacity: '1',
    background: 'rgba(236, 233, 203, 0.7)'
  })),
  state('false', style({
    height: 0,
    opacity: 0.7,
    overflow: 'hidden'
  })),
  transition('* => *', animate('250ms linear'))
])
```

However i don't see why would that break.

**Comment by Luchillo** [comment]
Nailed it, it's the background one, idk why but when i put it all breaks in an horrendous way, i'll try to make it happen in the plunkr.

**Comment by Luchillo** [comment]
I tough was because i didn't defined the background of the false state (the default one) and the error happened when in click, however after defining the animation in false state now it breaks the moment i open the page.

**Comment by Luchillo** [comment]
There you go, a working example, however i didn't use the style property so it may be a different issue:
http://plnkr.co/edit/ir2ct4ov2DjLpAHrXT7V?p=preview

**Comment by Luchillo** [comment]
I'm such a derp, `background` isn't the same as `background-color`, even if css allows it as the shorthand and defines everything else as initial, that doesn't mean that the animation would do the same, changing from `background` to `'background-color'` fixed the issue, however if the chrome version does work that means is the polyfill who fails to deal with such a case right?

**Comment by Luchillo** [comment]
In case needed i link the same issue in the `web-animations-js` repo.

**Comment by matsko** [comment]
@Luchillo is this still an issue?

**Comment by Luchillo** [comment]
Dunno, i am using the explicit `background-color`, however this is in the `web-animations-js` side, the issue in that repo should suffice.
