### ISSUE TITLE
Swap default behavior for event propagation

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1040]
Right now:
` (click)="run()"` does not do anything for propagated events, and
`(^click)="run()"` does

Here's my argument for swapping those.
Say I have an `MdButton` component:
```js
@Component({selector: '[md-button]:not([href])'})
@Template({url: '../button.html'})
export class MdButton {}
```
with template:
```html
<link href="../button.css" rel="stylesheet">
<span class="md-button-wrapper"><content></content></span>
```

Very simple, great! Now I pass this component along to a user to put in an app. User writes:
```html
<button md-button (click)="party()">Party time!</button>
```

But alas, there is no party. The click handler won't fire now because of that `<span>` in the template, which the user knows nothing about. As far as the user is concerned, that `<button>` is a total leaf. To get this to work, the user would have to write `(^click)`.

Alternatively, we could change the button itself...
```html
<link href="../button.css" rel="stylesheet">
<span (^click)="click($event)" class="md-button-wrapper"><content></content></span>
```
```js
@Component({selector: '[md-button]:not([href])'})
@Template({url: '../button.html'})
export class MdButton {
  clickEmitter: Function;
  constructor(@EventEmitter('click') clickEmitter: Function) {
    this.clickEmitter = clickEmitter;
  }

  click(event: Event) {
    this.clickEmitter(event);
  }
}
```

Adding a click handler and event emitter just to propagate an event (which happens by default in the DOM)? That's as boilerplate as you can get.

**Comment by matanlurey** [comment]
+1. Almost any event with a ShadowDOM component body won't work without `^`.

**Comment by dylanb** [comment]
+1

**Comment by jimthedev** [comment]
Just a clarifying question. Are you proposing that the default functionality of `(event)` change to bubble in all cases or just in the case of nested elements in a template. 

To put it another way, after this change, would an `(event)` on a top level template element still, by default, bubble up or would it stop at the component boundary?

**Comment by jelbourn** [comment]
It should always bubble but, as in the shadow dom spec, the event target should be changed whenever the event crosses a component boundary.

**Comment by jimthedev** [comment]
Great. Thanks for clarifying.

**Comment by naomiblack** [comment]
Assigning to @jelbourn to test native mode.

**Comment by jelbourn** [comment]
@mhevery I tested this in native mode and found that my button use-case actually works as expected without the `^` marker. I filed #1168 to track this.

That done, I still feel that swapping the default would be the most expected behavior for people used to web development.

**Comment by jelbourn** [comment]
Assigning back to @mhevery for decision or further assignment.

**Comment by jelbourn** [comment]
Closing for now.
