### ISSUE TITLE
[feature request] pass variable to template without let-statement (bind context to template in createEmbeddedView)

### ISSUE THREAD

**Issue by neuronetpl** [angular/angular#10406]
Simplified version:
There is a method `createEmbeddedView(template,context)` in `ViewContainerRef`.
Arguments are `template` and `context`.
Why not to bind context to template automatically (inside a method)?
Now we must use `let-` statement on the template html to get the context why?
There is nothing between context and template in this method but we must rewrite context to template in html. That is weird.

``` html
<template let-item="item"></template>
```

tltr;
I want create clean directive that is easy to use where inside it I can write a custom template that is automatically binded without `let-statement`.

For example repeater directive:

``` javascript
<myDirective [items]="items">
  <template #template let-item="item">
    <!-- I want variable item here - without let-item statement -->
    <div class="my-template">{{item.title}}</div>
  </template>
</myDirective>
```

where myDirective iterates through items and applies template inside the view
in `myDirective` Directive template looks like:

``` javascript
selector:'myDirective',
template:`
<div class="one-item" *ngFor="let item of items">
  <itemDirective [item]="item" [tmpl]="template">
  <!-- this template will have only variables defined in template let- attribute -->
  <!-- much easier will be to bind context to template without let-statement in createEmbeddedView -->
  </itemDirective>
</div>
`
```

in `itemDirective` directive I'am getting `item` and `tmpl` though input binding like in code above and then with `viewContainerRef` I'm creating embedded view

``` javascript
constructor(public viewContainer:ViewContainerRef){}
...
let context={item:this.item};
this.viewContainer.createEmbeddedView(this.tmpl,context);
```

For now I can only use the `let-statement` on template element  (in the first code block) to ensure that the repeated template will have item available.
But there is no way (that I know) to implement this behavior without `let-` statement on template element. 
It would be nice to have context binded to template with `createEmbeddedView(template,context)` method.
- **Angular version:** 2.0.0-rc.4

**Comment by Luchillo** [comment]
That would break encapsulation, you're not supposed to have variables that go beyond their container's scope, that's why we need the 1-2 way databinding, allowing what you ask seems to me as repeating the Angular 1 errors again.

**Comment by neuronetpl** [comment]
I understand, but when creating embedded view`this.viewContainer.createEmbeddedView(this.tmpl,context);` there is context for some reason,
now I must rewrite context to template with `let-` statement
maybe when template have context binded it would be few thing less to do and code will look cleaner?

**Comment by Luchillo** [comment]
I'm sorry, embedded views are outside of my knowledge in Angular 2, however it may seems as what you call embedded views is what i know as transclusion (basically the content you put from parent html inside child component tags get's rendered by child in an specific part of it's own template), am i right to assume that or is at least related?

**Comment by neuronetpl** [comment]
It was related :) but after all I just want to bind context to template without `let-` statement in `createEmbeddedView(template,context)` method. No transclusion, no parent child connection, just new embedded view with context without rewriting it to template.

I think that `let-` attribute is useless because there is context already and template as arguments in `createEmbeddedView` method
why I must connect context to template again(in html)? :)

**Comment by trotyl** [comment]
> but after all I just want to bind context to template without let- statement in `createEmbeddedView(template,context)` method. No transclusion, no parent child connection, just new embedded view with context without rewriting it to template.

Then you cannot even access `items` but only `item` in the `EmbeddedView`:

```html
<ul>
  <li *ngFor="let item of items">{{ item.name }} of all {{ /* error here */items.length }} items</li>
</ul>
```

**Comment by ciekawy** [comment]
looks like a workaround may be to use `let-dummy` and pass `context: { $implicit: myContextData }`

**Comment by DoctorBlue** [comment]
I'm learning templates today and have too wondered why you have to create a dummy object, essentially, if you want to get what you pass in. It's probably some fundamental piece about the way template context binding is supposed to work that I'm not understanding, but if I say my context is `foo`, I'd like to be able to access `foo`, not just its keys / properties.

The workaround is the ugly passing of an anonymous object `context: { $implicit: foo }` instead. I actually don't mind having to `let-localName="thingToBind"` but I'd love to just stick `foo` in there.

**Comment by sdepouw** [comment]
I'm learning templates today and have too wondered why you have to create a dummy object, essentially, if you want to get what you pass in. It's probably some fundamental piece about the way template context binding is supposed to work that I'm not understanding, but if I say my context is `foo`, I'd like to be able to access `foo`, not just its keys / properties.

The workaround is the ugly passing of an anonymous object `context: { $implicit: foo }` instead. I actually don't mind having to `let-localName="thingToBind"` but I'd love to just stick `foo` in there.
