### ISSUE TITLE
Make resolves(router) work with functions

### ISSUE THREAD

**Issue by Maqsim** [angular/angular#10405]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently to use resolve in your routes you have to declare @Injectable class-resolver with method resolve() and put it to resolve: {}

**Expected/desired behavior**
It's works good, but I would like to do it like in angular1 – use functions instead of classes. Also you mentioned that possibility in the documentation.

> You can also provide a function with the same signature instead of the class.

**What is the motivation / use case for changing the behavior?**
Make the resolve usage more compact and easier.

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

Chrome 51
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
TypeScript 1.7

**Comment by zoechi** [comment]
Please provide a Plunker that demonstrates what you try to accomplish. I have seen a similar question recently and there was a misunderstanding about what a guard is and what a provider is that provides a guard.

**Comment by brandonroberts** [comment]
To use a function for a resolve instead of a class, you provide it with a token.

routes
```ts
[
  {
    path: '/resolve-path',
    component: ResolveComponent,
    resolve: { two: 'TwoResolve' }
  }
]
```

resolve function
```ts
function TwoResolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
  return 2;
}
```

bootstrap
```ts
bootstrap(AppComponent, [
  { provide: 'TwoResolve', useValue: TwoResolve }
]
```

Here is an example plunker: https://plnkr.co/edit/nW5xEa2pqRFF1gpDnwYA?p=preview

**Comment by Maqsim** [comment]
@brandonroberts Thanks dude
