### ISSUE TITLE
Did ComponentResolver have create Component before or after targeted ViewContainerRef

### ISSUE THREAD

**Issue by golfapipol** [angular/angular#10401]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request
```

**Current behavior**
Do angular 2 have something prepend component, like jQuery Prepend, because I try ComponentResolver to create list like this
```
@Component({
  moduleId: module.id,
  selector: 'list-component',
  template: `
  <header #header></header>
  `,
  directives: [ItemComponent]
})
export class WidgetComponent implements OnInit {
  @ViewChild('header', { read: ViewContainerRef }) header: ViewContainerRef;

  constructor(public eleRef: ViewContainerRef, private resolver: p) {
      for(let i = 0; i < 5; i++) {
          this.resolver.resolveComponent(StreamComponent)
               .then((factory) => {
                   this.header.createComponent(factory)
               });
       }
  }
}
```
but when create it again, it should be after the targeted ViewContainerRef. But It append after component that created by resolver already
**Expected/desired behavior**
It's should append after targeted ViewContainerRef

**What is the motivation / use case for changing the behavior?**
Prepend component at targeted ViewContainerRef

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 2.0]

**Comment by pkozlowski-opensource** [comment]
I think that you are confused about nature of ViewContainerRef. There is no such thing as before / after ViewContainerRef - you insert things _inside_ ViewContainer as a _specific_ index; you might check detailed discussion in #9035 for more info.

By controlling index when calling `createComponent` you can have precise control of items inserted to a view container.
