### ISSUE TITLE
Router: error if no extraOptions parm  in `forRoot` call

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10418]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
Application fails with
```
TypeError: Cannot read property 'useHash' of null at provideLocationStrategy 
```
when no second parameter in `forRoot` call as in
```
 RouterModule.forRoot(routes)
```
For some reason, `provideLocationStrategy` in `router_module.ts` is unable to set the `options: ExtraOptions` parameter to the default `{}` value and the function crashes trying to execute `return options.useHash ? ...` because `options` is null.

This is true despite the signature:
```
function provideLocationStrategy( ..., options: ExtraOptions = {})
```

**Expected/desired behavior**

The `RouterModule.forRoot(routes)` should default the second parameter to `{}`.

**Reproduction of the problem**

Try any routed application that calls  `RouterModule.forRoot(routes)`

Workaround: 
```
 RouterModule.forRoot(routes, {})
```

**Please tell us about your environment:**

Angular version: 2.0.0-rc.5 candidate July 30

**Comment by vsavkin** [comment]
The issue has been fixed in master.
