### ISSUE TITLE
Angular 2 Http with promise issue

### ISSUE THREAD

**Issue by vipeeshbyt** [angular/angular#10416]
Hi,

i am try to create a login app using angular 2 http with promise.please find my code below.

issue is before printing the response object in extractData function in service, "Got response" console is printing from login component. Please someone help me to how to wait till response come from webservice.

Login component

import {Component} from '@angular/core';
import { Router} from '@angular/router';

import {User} from '../model/user';
import {UserService} from '../service/user-service';

@Component({
	selector : 'login-form',
	templateUrl : 'app/template/login.html',
	providers : [
		UserService
	]
})

export class LoginComponent{

	user: User;

	constructor(private userService: UserService,private router: Router){}

	loginUser(form: any): void {  
    	this.userService.loginUser(form.username,form.password).then(user => this.user = user)
    	console.log("Got response");
    	//console.log(this.user);
    	try {
    		console.log(this.user.userID);
    		console.log(this.user.name);
    		console.log(this.user.mobile);
    		console.log(this.user.email);
    		this.router.navigate(['/']);
		}
		catch(err) {
		}
  }
}

And my service 

import { Injectable }    from '@angular/core';
import { Headers, Http, Response, RequestOptions } from '@angular/http';

import '../rxjs-operators';

import {User} from '../model/user';

@Injectable()
export class UserService{

	private userUrl = 'http://localhost:8080/khalibottle/user/';
  private headers = new Headers({ 'Content-Type': 'application/json' });

	constructor(private http:Http){}

	getUsers (): Promise<User[]> {
  	return this.http.get(this.userUrl + "list")
                  .toPromise()
                  .then(this.extractData)
                  .catch(this.handleError);
	}

  loginUser (userName,password): Promise<User> {
    let body = JSON.stringify({ userName, password });
    let options = new RequestOptions({ headers: this.headers });
    return this.http.post(this.userUrl + "login",body,options)
                  .toPromise()
                  .then(this.extractData)
                  .catch(this.handleError);
  }

  registerUser (name,mobile,email,password,roleID): Promise<string> {
    let body = JSON.stringify({ name, mobile, email, password, roleID });
    let options = new RequestOptions({ headers: this.headers });
    return this.http.post(this.userUrl + "register",body,options)
                  .toPromise()
                  .then(this.extractData)
                  .catch(this.handleError);
  }

	private extractData(res: Response) {
    	let body = res.json();
      console.log(body);
    	return body || { };
  	}

	private handleError(error: any) {
    	console.error('An error occurred', error);
    	return Promise.reject(error.message || error);
  	}
}

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
