### ISSUE TITLE
request| feat: provide public api as a module on npm

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#10411]
Before there was an array of the public API for each module. I would like to have the array of types available per module to determine available types so I can auto inject import statements for anything Angular2

related https://github.com/angular/angular/issues/10410 use-case

**Comment by tbosch** [comment]
We are now generating flattened `.d.ts` files, and check whether they changed. This is a lot more efficient and easier to debug.
However, you could create an own tool to do this...
