### ISSUE TITLE
[Form] Collection type in the new API

### ISSUE THREAD

**Issue by nomack84** [angular/angular#1042]
Hello,
I've just end reading the post on Angular2 new Form API and I think is awesome. I have great expectations for Angular2. This new Form API seems to be very powerful, much more that Angular1's. 
I'd just like to know if it will be possible to have a better API for collections within the form, which could mark the entire form as invalid when validators such as GreaterThanX, LessThanX or EqualsToX return false to validation. 
What I'm trying to say is if I have my model object which contains an array of objects, and I like the collection to have at least 1 item, the form gets marked as invalid if that condition is not fulfilled. With Angular1 this is impossible, at least AFAIK. It will be really useful to have this included in the new API.
If you need some guidance, the popular PHP framework SYMFONY, have a Form component which already contains a control named COLLECTION which is specifically designed for this use case and it works really fine. Maybe we could have something like that in Angular2 Forms..
Keep the hard work and thanks for such an amazin tool.

**Comment by noetix** [comment]
I highly recommend looking at the Symfony2 form component, a lot of time and effort was put into it and its very similar to the new Form API (from what slides I've seen on the subject :D.)

**Comment by vicb** [comment]
`ControlArray` seems to be what you're looking for, see the [implementation](https://github.com/angular/angular/blob/6600ac7031944703ff7bb1f1aeee9650e8572460/modules/angular2/src/forms/model.js#L207) and the [tests](https://github.com/angular/angular/blob/6600ac7031944703ff7bb1f1aeee9650e8572460/modules/angular2/test/forms/model_spec.js#L302).

**Comment by mhevery** [comment]
This should already be supported. Closing.

**Comment by nomack84** [comment]
Awesome!
