### ISSUE TITLE
HTTP client request

### ISSUE THREAD

**Issue by newnewb** [angular/angular#10422]
**I'm submitting a ...**  (check one with "x")

[x ] bug report

**Current behavior**
No response *only locally* when i use a get request.

```
let url = http://192.168.1.xx/site/get/data?id='+id;
return this._http.get(url).map(
      res => res.json()
```

**Expected/desired behavior**

It should show a response, but it's currently acting as if the server is unreachable and i repeat only locally, if i an external host connects it will show results

It works fine with
```

let url = http://localhost/site/get/data?id='+id;
return this._http.get(url).map(
      res => res.json()

```
on my server 

**Reproduction of the problem**

and let me reiterate that when i use an IP, the application works fine when i use my mobile/laptop (other devices) to connect to my LAN server, but the server itself will see no results when it tests out the application, also the problem isn't from my  network since the get request is functioning right when i test it out in the browser/postman app using the IP address.

**What is the expected behavior?**

To show on my on my server the same results its showing on clients when the server acts as a client.

**What is the motivation / use case for changing the behavior?**

If this happens to my server during testing phase, maybe a client will also experience the same error.

**Please tell us about your environment:**
```
Windows 10 professional x64
* **Angular version:** 2.0.0-rc.4
WAMP server, Apache version 2.4.9

```
```
 
angular-cli: 1.0.0-beta.10
node: 4.4.7
os: win32 x64
```

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
```
Chrome 52.0.2743.82 m
Edge 25
```
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
```

├─┬ angular-cli@1.0.0-beta.10
│ └── typescript@1.8.10
```

**Comment by sirajc** [comment]
This problem could be related to CORS and not Angular Http itself. The fact that Postman works for the API because the strip CORS security check. Configure your server to handle CORS and you are good to go
