### ISSUE TITLE
Compiler-cli creating duplicate imports

### ISSUE THREAD

**Issue by KeatonTech** [angular/angular#10434]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

ngc is creating the following code for app.component.ngfactory.ts

```typescript
...
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/router/src/router_outlet_map';
import * as import11 from '@angular/core/src/linker/component_factory_resolver';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory_resolver';
import * as import14 from './model/navigation.service';
import * as import15 from '@angular/router/src/router';
...
```

Notice that import11 and import13 refer to the same file. This creates a naming conflict which in turn breaks dependency injection (No provider found for ComponentFactoryResolver$1) when used with rollup.js. Even if that weren't the case, this would unnecessarily increase the project's code size.

The original app.component.ts file looks like this:
```typescript
import { Component }                    from '@angular/core';
import { RouterOutlet }                 from '@angular/router';
import { SelectorPageComponent }        from './pages/selector.component';
import { NavigationService }            from './model/navigation.service';

@Component({
    selector: 'my-app',
    directives: [RouterOutlet],
    providers: [NavigationService],
    template: '<router-outlet></router-outlet>',
    precompile: [ SelectorPageComponent ]
})
export class AppComponent {}
```
NavigationService imports @angular/router, as does AppComponent. Given the order of the imports in the ngfactory file, this seems to be the source of the issue.

This may be related somehow to #10132, although ngc succeeds without any warnings so it's a different issue.

**Expected/desired behavior**

Regardless of the cause, ngc should never import the exact same thing twice.

**Reproduction of the problem**

I have not yet figured out how to reproduce this exact problem in a smaller project. Does anybody have insight as to what might cause this to happen? I am using @angular/compiler-cli (ngc) 0.4.1 and Angular 2.0.0-rc.4 with a fairly standard tsconfig.json file.

One odd thing is that `"angularCompilerOptions": {"debug": true}` doesn't seem to do anything. I'd hoped it would shed insight on where imported files are coming from.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all
 
* **Language:** TypeScript 1.8.2

**Comment by pkozlowski-opensource** [comment]
@KeatonTech could you please verify that this is still the issue with the latest compiler-cli and Angular? There were many changes past Angular 2.0.0-rc.4.

If this is still an issue could you please put together a minimal repository on GitHub so we can reproduce? There is little hope that we can act on this one with reproduce scenario. Thnx!

**Comment by KeatonTech** [comment]
Oh, sorry, should've closed this. It was fixed when @NgModule rolled out. Thanks!
