### ISSUE TITLE
Reduce forms boilerplate code

### ISSUE THREAD

**Issue by akorchev** [angular/angular#1043]
I've just finished reading [Victor Savkin's blog post](http://angularjs.blogspot.com/2015/03/forms-in-angular-2.html) about Angular 2 Forms. The general idea is spot on but the code required to make it work looks too much to me.

I couldn't help but [implement the last demo in Angular 1.x](http://jsbin.com/fareharupi/1/edit?html,output). It was a lot shorter and didn't have any code for setting up the form in the controller. The only "hard" thing was creating a custom directive for zip code validation.

The Angular 2 version requires code to bind model fields to controls and one line of code which wires up the two-way data binding: `this.form.changes.forEach(() => this.form.writeTo(this.address));`

The first thing that occurred to me when I saw this was "People will just keep forgetting that line". I already see all the stackoverflow questions.

Can we reduce the boilerplate somehow? Can we use attributes and type information in to create a form? Here is what I mean:

```javascript
class Address {
  // Tells the form builder the street field is required
  @Required  
  street: string;
  @Required( { message: "City is required" } )
  city: string;
  @Required
  state: string;
  //Custom validation
  @Custom({ validator: zipCodeValidator })
  zip: string;
  @Checkbox
  residential: boolean;
}

@Component({
  selector: 'form-example'
})
@Template({
  // bind the form to the "address" field
  // form builder uses the Address type information to get the validation rules
  inline: `<form [form-for]="address">
Street <input control="street">
      <div *if="form.hasError('street', 'required')">Required</div>

      City <input control="city">
      <div *if="form.hasError('city', 'required')">Required</div>

      State <input control="state" size="2">
      <div *if="form.hasError('state', 'required')">Required</div>

      Zip <input control="zip" size="5">
      <div *if="form.hasError('zip', 'invalidZipCoed')">
        Zip code is invalid
      </div>

      Residential <input control="isResidential" type="checkbox">
   </form>`
})
class FormExample {
   // annotate so the form builder knows the type
   address: Address; 
   constructor() {
      this.address = new Address();
      /* we don't need anything else */
   }
}
```

**Comment by DanWahlin** [comment]
I saw this after adding my own form suggestion. Very similar to what I suggested so I'm in total agreement with you. Here was what I posted:

https://github.com/angular/angular/issues/1047

**Comment by aeigenmann** [comment]
+1

**Comment by TiagoBraga39** [comment]
Given the Entity class:
```javascript
class Entity {
    code : string;

    @Required
    name : string;
}
```
And the SubEntity subclass:
```javascript
class SubEntity extends Entity {
    @Required
    @Custom({ validators: zipCodeValidator })
    zipCode : string;
}
```

Should it be possible to define the validator of Entity's code from the SubEntity class? 
It could be usefull to do so if I wanted to limit the code length, depending on the subclass.

Thanks in advance,
Tiago Braga

:+1: for @akorchev request !

**Comment by kara** [comment]
Thanks for the feedback!  We have implemented a number of changes to forms since March of last year. You can read about them in [the proposal](https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub) or on our [docs site](https://angular.io/docs/ts/latest/guide/forms.html).  Closing, as this issue is probably stale. Feel free to open a new issue if you have feedback for the new forms changes.
