### ISSUE TITLE
HashLocationStrategy fires locationchange twice using browser buttons

### ISSUE THREAD

**Issue by amariniello** [angular/angular#10430]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

if you subscribe to the location service running the application with HasLocationStrategy, the subscription will fire twice if using the browser navigation buttons. This causes issues like calling the guards twice on the router.

**Expected/desired behavior**

The subscirption should fire only once like when running in PathLocationStrategy mode.

**Reproduction of the problem**
you can use the navigation sample on the angular documentation and change the location strategy.
subscribe to the location and you will experience the bug

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc4
 
* **Browser:** [Chrome ] 
 
* **Language:** [TypeScript 1.8.X ES5]

**Comment by sirajc** [comment]
@amariniello Plunker with minimal reproduction will help in investigating this further

**Comment by amariniello** [comment]
http://plnkr.co/edit/iz3NK4y3zUOOI64Jkx52?p=info
remember to use the browser navigation to reproduce the bug. You should see the alert called twice on location change.

**Comment by brandonroberts** [comment]
This is already fixed in master and will go out with the next release
