### ISSUE TITLE
Forms error checking prevents formGroupName being used under formArrayName.

### ISSUE THREAD

**Issue by EricABC** [angular/angular#10432]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In RC4 an array could have child groups of an array like this:
```html
<div formGroup="form">
    <div formArrayName="widgetList">
        <div *ngFor="let widget of widgets; let i = index" [formGroupName]="i">...</div>
    </div>
    ...
</div>
```

In current RC5 (*-builds) the error checks added on [this line](https://github.com/angular/angular/blob/2dfc9c653b6008b378ab6fb3dd0ea4e48056bb67/modules/%40angular/forms/src/directives/reactive_directives/form_group_name.ts#L89) prevents this.

**Expected/desired behavior**
Consider allowing the conditional right above that line to include arrays or perhaps add a formArrayIndex directive.

* **Angular version:** 2.0.0-rc.5-ish (angular/*-builds)

**Comment by kara** [comment]
@EricABC  Yikes, good catch!  I should be able to fix the check now. It should be less restrictive to include arrays.
