### ISSUE TITLE
Class Inheritance with Decorator behaves differently with Bootstrap/Component Providers 

### ISSUE THREAD

**Issue by tlaverdure** [angular/angular#10435]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I create a decorator that is used on a service class with dependencies, all the injected dependencies are accounted for using:
```ts
construct(...args) {
  super(...args);
}
```
in the decorator. This works fine when I add the service as a provider in the app component, but not as provider during bootstrap.

**Bootstrap Providers:**
http://plnkr.co/edit/id5XKz2l2AgELJShiMqg?p=preview

**Component Providers:**
http://plnkr.co/edit/uPbaU0m8jxZT2UMYC8BS?p=preview

**Expected/desired behavior**
I don't know if there is a specific reason for this not to work the same, but if they did that would be great.

**What is the motivation / use case for changing the behavior?**
I'm working on a package that contain services that use custom decorators and it would be ideal to implement at bootstrap. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome
 
* **Language:**TypeScript 1.8.10

**Comment by tbosch** [comment]
Looking at the example you are passing in a decorator to `bootstrap`, which does not make sense / is not supported by Angular. 
Also, I don't see where you are using inheritance in your example.

Closing this issue as we can't act upon it.
