### ISSUE TITLE
Errors while using navigation and routing( angular2 with es5 / plain javascript)

### ISSUE THREAD

**Issue by chakradhar-s** [angular/angular#10443]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Doesn't provide any routing and navigation using plain javascript or es5 because of errors in zone.js and platform-browser.umd.js.

**Expected/desired behavior**
To navigate to a new location on clicking any anchor tag or button and to display the new view at <router-outlet></router-outlet> of app component.

**Reproduction of the problem**
you see live code on http://plnkr.co/edit/yhtJ0oBO7mi84Ad9MpKK.

**What is the motivation / use case for changing the behavior?**
Having the deprecated router.js and new router.umd.js don't work.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by brandonroberts** [comment]
Support for ES5 with the new router has been fixed in master and will go out with the next release:
Here is a working plunker: http://plnkr.co/edit/a8s0eB?p=preview

**Comment by tbosch** [comment]
Sorry, but using the both routers at the same time is not supported.
Also the router deprecated is no longer supported (it was removed when we cut final).
