### ISSUE TITLE
Default route not working in Cordova iOS/Android applications

### ISSUE THREAD

**Issue by sudhishsasi** [angular/angular#10446]
I am creating a Angular 2 + Cordova  project to support iOS and Android devices. All the functionalities are working fine as expected in browser, but when I port the code to Cordova project default URL is not working.
default url :   { path: '', component: LandingComponent } 
and getting error in android adt bundle like :

08-02 18:20:57.565: I/chromium(1957): [INFO:CONSOLE(1900)] "EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: 'android_asset/www'", source: file:///android_asset/www/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js (1900)
08-02 18:20:57.565: I/chromium(1957): [INFO:CONSOLE(1900)] "STACKTRACE:", source: file:///android_asset/www/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js (1900)
08-02 18:20:57.565: I/chromium(1957): [INFO:CONSOLE(1900)] "Error: Uncaught (in promise): Error: Cannot match any routes: 'android_asset/www'
08-02 18:20:57.565: I/chromium(1957):     at resolvePromise (file:///android_asset/www/node_modules/zone.js/dist/zone.js:538:32)
08-02 18:20:57.565: I/chromium(1957):     at file:///android_asset/www/node_modules/zone.js/dist/zone.js:515:14
08-02 18:20:57.565: I/chromium(1957):     at ZoneDelegate.invoke (file:///android_asset/www/node_modules/zone.js/dist/zone.js:323:29)
08-02 18:20:57.565: I/chromium(1957):     at Object.NgZoneImpl.inner.inner.fork.onInvoke (file:///android_asset/www/node_modules/@angular/core/bundles/core.umd.js:9100:45)
08-02 18:20:57.565: I/chromium(1957):     at ZoneDelegate.invoke (file:///android_asset/www/node_modules/zone.js/dist/zone.js:322:35)
08-02 18:20:57.565: I/chromium(1957):     at Zone.run (file:///android_asset/www/node_modules/zone.js/dist/zone.js:216:44)
08-02 18:20:57.565: I/chromium(1957):     at file:///android_asset/www/node_modules/zone.js/dist/zone.js:571:58
08-02 18:20:57.565: I/chromium(1957):     at ZoneDelegate.invokeTask (file:///android_asset/www/node_modules/zone.js/dist/zone.js:356:38)
08-02 18:20:57.565: I/chromium(1957):     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (file:///android_asset/www/node_modules/@angular/core/bundles/core.umd.js:9091:45)
08-02 18:20:57.565: I/chromium(1957):     at ZoneDelegate.invokeTask (file:///android_asset/www/node_modules/zone.js/dist/zone.js:355:43)", source: file:///android_asset/www/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js (1900)
08-02 18:20:57.565: I/chromium(1957): [INFO:CONSOLE(461)] "Unhandled Promise rejection:", source: file:///android_asset/www/node_modules/zone.js/dist/zone.js (461)
08-02 18:20:57.565: I/chromium(1957): [INFO:CONSOLE(463)] "Error: Uncaught (in promise): Error: Cannot match any routes: 'android_asset/www'", source: file:///android_asset/www/node_modules/zone.js/dist/zone.js (463)

So I added ""  base href="file:///android_asset/www/"   ""
 now in Android it is working fine but the issue is still exist in  iOS device.

I also tried 
  { path: '', redirectTo: '/landing’},
  { path: '', redirectTo: 'landing'},
       location.go('/landing');
       this.router.navigate([‘landing']); 
       this.router.navigate([‘/landing']); 
       this.router.navigateByUrl(‘landing’);
       this.router.navigateByUrl(‘/landing');

Current behavior:
Not navigated to default URL

Expected/desired behavior:
Should be navigated to the default URL

Reproduction of the problem

Issue is reproducible in Cordova  appliction

Environment:

Tested devices : 
OS : iOS
device :iPhone 6   
version 9.0.1
OS : Android
device : Samsung S5
Version : 4.4.2

Angular version:
 "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.4",
    "angular2-in-memory-web-api": "0.0.14",
    "angular2-modal": "^1.0.8",
    "angular2-swiper": "^0.4.0",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
 

 
Language:

TypeScript

**Comment by jinshad** [comment]
To resolve this issue, Please modify the base href tag in index.html as **base href ="./"**

**Comment by Lindstrom1989** [comment]
This is still an issue for me, using meteor & angular 2, no errors just a blank where ```<router-outlet>``` should be but everything before and after is rendered.
```
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "3.0.0-alpha.8",
```

The following in my app.component constructor works
```
setTimeout(() => {
    this.router.navigate(['/']);
}, 1);
```
But is a crappy solution. I can navigate around but the initial route view will not render on IOS only.

**Comment by vincentdu101** [comment]
Hey @Lindstrom1989,

I'm facing this exact problem as well only I'm focusing on the ios. So far I've tried to grab the script src to get the local ios file path, but it hasn't worked. It throws the same error where it couldn't match the route. I've also tried to set the base href, but so far nothing. 

I'm at @angular 2.0.0-rc.6 with nodejs 4.5.0. 

    private static determineFilePath(): string {
        if (window.cordova) {
            let scripts = document.getElementsByTagName("script");
            let scriptPath = scripts[0].src;
            let base = document.getElementsByTagName("base")[0];
            let cordovaFilePath = scriptPath.substring(0, scriptPath.indexOf("www/") + 4);
            base.setAttribute("href", cordovaFilePath);
            return cordovaFilePath;
        } else {
            return "./";
        }
    }

**Comment by vincentdu101** [comment]
Hey @Lindstrom1989,

So I found this fix that someone posted regarding our issue and it seems the solution is to remove the provide APP_BASE_HREF in the app.modules. Instead you would load the base href tag as is. I did that and the routes worked for me now. Hope it helps!

http://stackoverflow.com/questions/38475460/angular-2-app-base-href-with-cordova-ios

**Comment by Lindstrom1989** [comment]
@vincentdu101 I don't think you have the same issue, I already have that set, are you using meteor?

**Comment by SamVerschueren** [comment]
@Lindstrom1989 Are you sure you **REMOVED** the `APP_BASE_HREF` provider? That with a `<base href="file:///android_asset/www">` in my `index.html` did the trick for me.

**Comment by Lindstrom1989** [comment]
I never had that in the first place but I have tried with and without
