### ISSUE TITLE
Rendering using emulated shadow DOM is an order of magnitude slower than native

### ISSUE THREAD

**Issue by jwcarroll** [angular/angular#1044]
I have written a simple Angular 2.0 application that simply displays a list of custom `message` components to the screen using `*foreach`.

**When using native Shadow DOM, the application can render 5000 messages to the screen in ~1 second. However, when switching to emulated mode (default rendering mode), then it takes upwards of 10 seconds to render the list.**

It's possible that something in my component is causing the slowdown, but the difference in rendering is pretty stark.

The project can be found here: https://github.com/jwcarroll/ng2-message-list

To get it up and running, clone the repo and then:

```
npm install
bower install
gulp play
```

There are directions in the readme for this as well, but if you want to switch between modes, there is a line at the bottom of `app.js` that can be uncommented to switch to `NativeShadowDomStrategy`.

```javascript
var shadowDomBindings = [
    bind(ShadowDomStrategy).toClass(NativeShadowDomStrategy)
];

bootstrap(MyAppComponent
    //,shadowDomBindings // <-- Uncomment this line to use Shadow DOM
    );
```

**Comment by mhevery** [comment]
Our tests show otherwise. Are you sure you are not running dev mode? (which has all kinds of assertions which make the code slow)

**Comment by jwcarroll** [comment]
Not sure how to know if I am in dev mode or not.

**Comment by rkirov** [comment]
Looks like prod - https://github.com/jwcarroll/ng2-message-list/blob/master/gulpfile.js#L55 . I will have to investigate further.

**Comment by mhevery** [comment]
since this is prod, moving to later milestone
