### ISSUE TITLE
Issue while passing data from parent component to child

### ISSUE THREAD

**Issue by nandhaaas** [angular/angular#10456]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am dealing with parent and child component where i have a list in parent and action can be triggered against each item. Child component is more of a reusable one think of picker kind of scenario which has to load data (a list) based on what is selected from the parent. So for achieving this i am calling a method inside child component from parent component which will accept selected item id from parent and then update a property in child component. But the update is not actually updating the child component property because of which i could not able to proceed loading child data 

In Parent i am rendering the client and calling it in this way
````
<group-picker (onCompleteSelection)="associateServices($event)"></group-picker>

this.groupPicker.open(selId);
````
And in client
````
open(selId: any) {
		$('div#examination-picker').modal('show');
		this.selId = selId;
	}
// a lazy loading event gets triggered to read the selId and load data and bind it to a list
````
But when control goes to the load event selId is undefined

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: 
http://plnkr.co/edit/UHXj3rsQyIu6XOmCeMiI?p=preview

**Expected/desired behavior**
Updated component value to be available across the component life cycle

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript 1.8.10 | ES6/7 | ES5]

**Comment by ericmartinezr** [comment]
This sounds more like a support question. What you are trying to accomplish is absolutely possible so I wouldn't vote for a bug. You need to reproduce it in a plnkr, otherwise you can ask on Gitter's chatroom.

**Comment by nandhaaas** [comment]
I have created a plnkr with a simple scenario where passing data between two components is not working. Already tried detect changes and zone for this.

http://plnkr.co/edit/UHXj3rsQyIu6XOmCeMiI?p=preview

**Comment by woppa684** [comment]
My guess is that you're:
- Using ProductPicker as well as an injected service as well as a directive
- The ProductPicker you're injecting is not the same instance as the ProductPicker component in  your template
- Therefore you do see the alerts, but you don't see them in the list...

You could for example pass "App" to your component via an input or get a reference to your ProductPicker instance with ContentChild ... There are probably some other solutions to this problem as well but this is definitely no bug.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
