### ISSUE TITLE
ControlValueAccessor: add dynamically to FormGroup

### ISSUE THREAD

**Issue by meriturva** [angular/angular#10465]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you develop a new ControlValueAccessor is really easy to add it to form template, but there is no way to add it dynamically using `addControl` method of FormGroup. Every time we call method `formGroup.AddControl("newid", new MyControlCalueAccessor())` there is an exception about method `setParent` not found. Why i could use ControllValueAccessor on template and not calling formGroup directly? The interface is respected but programmatically you can work only with AbstractControl.

**Expected/desired behavior**
A way to have same behavior about ControlValueAccessor on template and code.

**Reproduction of the problem**
https://plnkr.co/edit/YtkNyyNSsWC9O3HshPUE?p=preview

and see console error about "setParent" method.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all
 
* **Language:** TypeScript

**Comment by stephanjust** [comment]
[`addControl`](https://angular.io/docs/ts/latest/api/forms/index/FormGroup-class.html#!#addControl-anchor) does not expect a [`ControlValueAccessor`](https://angular.io/docs/ts/latest/api/common/index/ControlValueAccessor-interface.html) but an [`AbstractControl`](https://angular.io/docs/ts/latest/api/common/index/AbstractControl-class.html). These objects have a `setParent` method. I'm not sure what you're trying to do as I never used `ControlValueAccessor`, but it's clear that this is not a bug but you're using the wrong object/calling the wrong function.

**Comment by meriturva** [comment]
I found that i have to create an empty FormControl and link to ControllValueAccessor 

Modified sample:
https://plnkr.co/edit/L011yH0NMFhuSCJc8QKV?p=preview
