### ISSUE TITLE
(index):1 Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by Soolan** [angular/angular#10467]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Hi,
In my Angular2 code, I'm trying to get Google Trends keywords via this URL http://hawttrends.appspot.com/api/terms/?callback=JSONP_CALLBACK

It converts the last bit into this:
http://hawttrends.appspot.com/api/terms/?callback=__ng_jsonp__.__req0.finished

and when I check my Network tab, I see the 200 response but it returns the "unexpected token :" error in my console
**Expected/desired behavior**
What I'm looking for is a way to fetch the google trends and use them in my app.
I tried Http(), Jsonp() and even pure XMLHttpRequest() methods. 
The google server for trends does not provide CORS (as you know according to whois info, appspot.com belongs to google) so Http() and XMLHttpRequest() are not working and the Jsonp approach returns with the error I mentioned.
To be honest I'm not sure if I should call it a bug. Because JSONP works fine for other urls (i.e. wikipedia). But since appspot.com is owned by Google I wonder if you could give an insight .
**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [ Chrome 51.0.2704.103 ] 
 
* **Language:** [TypeScript 1.8.9 | ES6/7 | ES5]

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
