### ISSUE TITLE
Change detection on referenced input fields

### ISSUE THREAD

**Issue by filipbech** [angular/angular#1046]
I really don't know if this is a bug, a missing/forgotten feature or a choice, however I think 

```html
<input type="checkbox" #checker /> 
<div [hidden]="checker.checked">toggled</div>
```

should work, but the change-detection doesn't kick in on change. It needs an (possibly empty) event-listener, like this.

```html
<input type="checkbox" #checker (change)="" /> 
<div [hidden]="checker.checked">toggled</div>
```

Thoughts on this?

**Comment by chalin** [comment]
FYI: might be related to #992, though there has been no response yet for that issue either.

**Comment by alexpods** [comment]
@filipbech It's really related to #992. See this comment https://github.com/angular/angular/issues/992#issuecomment-84688354. Your code will work if you just declare "change" event binding (without initializing it with empty string):

```js
<input type="checkbox" #checker (change) /> 
<div [hidden]="checker.checked">toggled</div>
```

**Comment by filipbech** [comment]
Agreed, its a dublicate!
Ill close this issue again!
