### ISSUE TITLE
issues with 404 page missing when refresh current page

### ISSUE THREAD

**Issue by wfsovereign** [angular/angular#10466]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I will get 404 page missing when I refresh current page ,eg : http://localhost:30000/#/user/login;redirect=true/user/list, but if I first link to this page, there are not this exception.

**Expected/desired behavior**

I think this is bug , but I can't confirm where it belongs. I expected it can be correct show this page.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

 I expected it can be correct show this page.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:**  Chrome Version 51.0.2704.103 (64-bit)
 
* **Language:** "typescript": "~1.8.10",

thanks advance.

**Comment by zoechi** [comment]
It would at least require a minimal Plunker to reproduce. Even when it can't be reproduced directly in Plunker, it shows what code you use to get that behavior.

A guess is http://stackoverflow.com/questions/31415052/angular-2-0-router-not-working-on-reloading-the-browser

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by dashng** [comment]
I meet the same problem on reloading the page.
Resolve my issue by steps below:
* 404 means no page found. So use the way of listening url hash changes.
* for different version of angular, hash change listening directive is different.
* for rc.4 solutions below:
```
import {  
  PlatformLocation,  
  Location,  
  LocationStrategy,  
  HashLocationStrategy,  
  PathLocationStrategy,  
  APP_BASE_HREF
} from '@angular/common'; 
const routes: RouterConfig = [
   
    {
        path: 'device', 
        component: DeviceComponent
    },
    {
        path: 'user', 
        component: UserComponent
    },
    {
        path: '**', 
        component: DeviceComponent 
    }
];

export const appRouterProviders = [
  provideRouter(routes)
];


```

``` html
 <li>
                <a [routerLink]="['user']"><i class="fa fa-users"></i> <span >User Management</span>  </a>
            </li>
            <li>
                <a [routerLink]="['device']"><i class="fa fa-codepen"></i> <span >Device Management</span>  </a>
            </li>
```

**Comment by wfsovereign** [comment]
@dashng thanks very much 码雷锋

I'm already try to modify boot file like yours, but still not work.

We have the same html, but router file. I don't known why import PlatformLocation,  Location from common, you are not use them?

**Comment by wfsovereign** [comment]
@zoechi  thanks your help.

Firstly, I search it in stackoverflow, I also find it than you offer me link, I've tried many method, but not work, so I think it's angular problem ? so I'm here, because I want to show it to geek as soon as possible, I thought of github..

**Comment by dashng** [comment]
@wfsovereign  It works well for me.

Actually you just need to modify boot ts file.  please ignore router.

**Comment by wfsovereign** [comment]
tried to weep, but failed to shed a tear.
I often encounter this problem - -、

In brief,  I add this code that below for boot file, but it still joke to me - -
```
{provide: LocationStrategy, useClass: HashLocationStrategy},
```

**Comment by pkozlowski-opensource** [comment]
This sounds like a support question that got resolved.

**Comment by bakoserge** [comment]
for me using angular 4 setting up the routes as such using HashLocationStrategy fixed my issue;
RouterModule.forRoot(ROUTES, {
      useHash: true
    }),

**Comment by suom7** [comment]
@bakoserge thank you very much. you saved my day.

**Comment by jonasfabian** [comment]
> for me using angular 4 setting up the routes as such fixed my issue;
> RouterModule.forRoot(ROUTES, {
> useHash: true
> }),

Thanks a lot!

**Comment by tanvirstreame** [comment]
after so many days later, i have solved the issue 
in .htaccess just write
ErrorDocument 404 /index.html

**Comment by tanvirstreame** [comment]
after so many days later, i have solved the issue 
in .htaccess just write
ErrorDocument 404 /index.html
