### ISSUE TITLE
Custom FormControls are not being added to the parent

### ISSUE THREAD

**Issue by jondejong** [angular/angular#10462]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using a custom FormControl inside a Template driven form, the form can be valid without the FormControl being valid. Debugging this a bit I found that addControl() is called on the NgForm for each input in the form, unless they have a custom FormControl. I'm guessing the problem lies there. I tried to find a manual way to add the Control, but other than defining the whole form as a Model, I can't find a way.

**Expected/desired behavior**
If an input field on a form has a custom for control, it should be added to the parent (in this case an NgForm). By default that parent can be invalidated by the Control. Presumably this can be overwritten, however, by providing custom validation to parent.

**Reproduction of the problem**
Reproduced in the is plunker. This create
http://plnkr.co/edit/Y6NDFYRPyeOMrhCrxHCu

**What is the motivation / use case for changing the behavior?**
Custom form validation without defining an entire form as a model.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome 51.0.2704
 
* **Language:** Typescript

**Comment by kara** [comment]
@jondejong the `[formControl]` directive is meant for registering individual form controls.  If you want to register a form control in a larger group, you'll want the `[formGroup]` directive and the `formControlName` directive.   Example plunker here: http://plnkr.co/edit/LI3LMxtVt0oQmUBNp1Cy?p=preview.

**Comment by jondejong** [comment]
Thanks for the response, @kara. I appreciate you taking the time to respond to me when it appears I possibly just don't understand this API. Especially generating a plunker. Thank you. Unfortunately, your understanding of what I'm _trying_ to do is incorrect. I probably oversimplified it for the sake of generating a plunker. Essentially what we have is large form in which only 2 fields need custom validators. I'm trying to find a way to add just those custom validators without needing to redefine the entire form in the model (and then translate it to the Typescript object to hand off to the service). It appears, however, that with the current API, the only way to add custom validator is via model driven forms. 

Thanks again.

**Comment by kara** [comment]
No problem. You can actually add custom validators with template-driven forms as well.  No need to switch to model-driven if you don't want to. It's just a bit hairier (something we're looking to improve). For a good example of how this works, check out how the "required" validator directive works:

https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/validators.ts#L40

You'll just want to create a directive for your validator, and ensure it provides the custom validator you created as an NG_VALIDATOR.

**Comment by jondejong** [comment]
That makes sense. Thanks for the help.
