### ISSUE TITLE
Feature Request: Make property/event binding syntax optional for web components implemented using NG2

### ISSUE THREAD

**Issue by giancarloa** [angular/angular#10473]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
<some-component (someOutputProperty)="someFunction($event)" [someInputProperty]="someProperty"></some-component>

@Component({selector: 'some-component'})
export class SomeComponent {
    @Input() someInputProperty = 0;
    @Output() someOutputProperty = new EventEmitter();
}
```

**Expected/desired behavior**
```
<someComponent someOutputProperty="someFunction($event)" someInputProperty="someProperty"></someComponent>

@Component({selector: 'some-component'})
export class SomeComponent {
    @Input() someInputProperty = 0;
    @Output() someOutputProperty = new EventEmitter();
}
```

**What is the expected behavior?**
Be able to consume web components implemented in NG2 using plain old HTML attribute syntax without having to pollute the markup with property/event binding syntax. The NG2 data binding syntax for inputs and outputs is unnecessary noise. NG2 can use the component's metadata to figure out which attributes in the markup correspond to bindable properties. By doing so, the markup for web components implemented using NG2 remains plain old vanilla, thereby making it much more maintainable, portable, and adaptable to future versions of angular.

**What is the motivation / use case for changing the behavior?**
My team and I have begun the process of evaluating NG2. We have a very large investment in NG1. We would like to move this investment to NG2. As part of our NG1 architecture we have a very large suite of reusable web components implemented using NG1 directives. All of our NG1 apps use these web components exclusively to build their views. In other words, none of the views of our NG1 apps have NG1 syntax inside of them. Instead the markup of the views consists exclusively of plain old html with web components implemented using NG1 directives. 

For example, in all of our NG1 apps binding to an input happens like this: 
`<textbox model="name"></textbox>`

None of our NG1 apps ever bind to an input like this:
`<input ng-model="name"></input>`

We had a number of reasons for this architecture, but one of them was to facilitate future upgrades of the client side web components framework. So we are at this stage right now of trying to find a new framework for implementing our web components. Naturally we would like to move to NG2, since we currently use NG1. But after a couple of sprints of evaluating NG2, we've run into a couple of problems. One of those problems is the subject of this request. We don't believe the property/event binding syntax is architecturally a good idea. It just adds noise to the markup and makes it less portable/maintainable. Besides, everything NG2 needs to make things work is already in the component metadata, at least for web components implemented using NG2. If the reason behind the binding markup syntax is to support arbitrary web components implemented using something besides NG2, well first of all I think in general that's a much less common use case, and when that does happen, then in that case one could use property/event binding syntax. But why force everyone to use it? It's not necessary, at least most of the time. I like a lot of what I see in NG2, but it seems like some key very architecturally solid NG1 ideas/principles are being abandoned, one of those being plain old vanilla web component syntax, which went hand in hand with being able to use plain old objects as sources of data binding. I also disagree with NG2's handling of data binding context (aka $scope) but that's the subject of another request.

Thank you for listening... and please keep up the excellent work!!! We are grateful...

**Comment by robertmirro** [comment]
Are you opposed to the cononical form of syntax? 
```js
<some-component on-some-output-property="someFunction($event)" bind-some-input-property="someProperty"></some-component>
```

**Comment by giancarloa** [comment]
Thanks @robertmirro ... Yes I am opposed because it requires adding "stuff" in order to drive the framework's behavior... I am not in particular against the [()] syntax... I don't find it any better or worse than the cononical form... However I am generally against the idea of having to pollute the markup with these "hints", whatever form they may be in, for web components implemented using NG2... Again, the metadata the framework needs in order to drive is already provided by the component class.... And again, I  understand perhaps why it may be needed in order to use in an NG app a web component implemented using something other than NG, but again that's a less common use case, and even in that case there are better solutions that don't involve adding noise to the markup... thanks for your feedback...

**Comment by vicb** [comment]
`someInputProperty="someProperty"` is valid syntax, it will initialize the property with the **string** `"someProperty"` while `[...]` will initialize it with an expression.

This is required to disambiguate the bindings and allow tooling support. You'll be able to find long discussions in the issue tracker if you are interested in more details.

**Comment by giancarloa** [comment]
Thanks @vicb ... 

I understand that it is valid syntax... We figured that out already during our extensive evaluation of NG2... But as I explained above, this behavior/syntax is problematic on many levels... First, if the component is telling you through its metadata that a property is bindable, then there's no need for any other information. There is zero ambiguity. Second, as far as tooling is concerned, tooling is almost always driven by available type information. The presence of [()] is not going to make developing tools any easier or harder...

And to your point, we have already gone over many of the online discussions on this topic... We have spent the last couple of sprints exclusively researching NG2... That is, we have spent thousands of dollars in developer time trying to figure out how we can use NG2... In the end we remain unconvinced... 

I am sorry to say that I am somewhat disappointed this feature request was closed, prematurely I think... I understand you guys are the brilliant developers developing this magnificent framework, and we applaud and are grateful for all your hard work and effort... After all, it's a "free" framework... But at the same time I kindly and respectfully ask that you guys understand our point of view, that of the consumers of your hard work... We also work very hard to learn and implement solutions with your framework...

Please do consider reopening this request and having others on your team weigh in on it...

Thank you

**Comment by zoechi** [comment]
> However I am generally against the idea of having to pollute the markup with these "hints", 

Using `[]` or `()` are no hints, they change the behavior. As @vicb explained it's either (without `[]`, `()`)  normal (plain HTML) attribute definition or (with `[]`, `()`) Angular2 binding.

    xxx="yyy"

adds and attribute `xxx` with the value "yyy" to the element

    [xxx]="yyy"

binds the value of the component property "yyy" to the elements property `xxx`

**Comment by giancarloa** [comment]
@zoechi ... Thank you for the feedback...

I agree and understand already that the presence or absence of [()] drives the behavior of the framework... However whether you call it a hint or not is besides my point...

My point is that this syntax is absolutely unnecessary. All it does is add noise to the markup. It was not needed in NG1 and there's no good reason to have it in NG2.

One more time, from the beginning, please take a close look one more time at the example I provided... If my NG2 component is telling you through its metadata that it has a bindable input property called "someInputProperty", then a plain old attribute definition with the name "someInputProperty" should absolutely without a shadow of a doubt be treated as an angular binding... Why does this make sense? Because that's the common use case!!! I ask you to put your hand on your heart and honestly tell me how many times have you created a component with an @Input property and then in the markup used a plain old attribute to pass a string to the component??? My guess is that you have done this zero or close to zero times... My guess is that you always or almost always use a property binding... And that makes total sense because you've declared in your component that the property is an @Input property... It never or almost never makes sense to pass in a plain old string... So knowing this then why on earth do we need the property/event binding syntax in the markup? The answer is, again, we don't need it! I understand the need exists perhaps to pass in a plain old string to the component... I get that... I don't argue that... But that's NOT the common use case, and in that case, if the component is really expecting a plain old string for one of its properties, then it should simply declare the property WITHOUT the @Input decorator...

Am I really the only one that sees the property/event binding syntax as completely unnecessary?

Thanks for the feedback @zoechi ... I wish the angular team would consider this...

**Comment by zoechi** [comment]
Just look at the form directives

    <div formGroupName="address">
      <input name="street">

This is pretty common. 

What about the distinction about one-way and two-way binding
   
   [ngModel]="prop"

vs

  [(ngModel)]="prop"

vs 

   (ngModel)="eventHandler(x)"

If you want this changed (which I'm sure won't happen) then you need to provide a solid analysis instead of some guesses and wishes.

This topic was discussed to death and you're beating a death horse.

**Comment by giancarloa** [comment]
@zoechi ... Thanks

But with all due respect these aren't guesses and wishes... Instead we've spent a lot of money on very good developers evaluating... I wish we could have done this earlier in the process while you all were discussing this very topic, but unfortunately resources are limited and we have systems here to build and maintain...

Your examples just enforce my conclusion on how bad this design is... Again, it's all in the metadata...

Thanks again
