### ISSUE TITLE
Bootstrap modal window causes change detections in angular 2

### ISSUE THREAD

**Issue by zim32** [angular/angular#10475]
![selection_019](https://cloud.githubusercontent.com/assets/538976/17376105/ad6d9bdc-59bc-11e6-864f-ca5b4f664469.png)
[ x] bug report

**Current behavior**
Change detection is performed regardless of any bindings in template

**Expected/desired behavior**
No change detection

**Reproduction of the problem**
Just make dummy project with simple bootstrap modal window

**What is the expected behavior?**
No change detection

**What is the motivation / use case for changing the behavior?**
Performance and strange bugs with "property changed after change detection..."

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all

* **Language:** TypeScript 1.8

```
import {Component, ElementRef, ViewChild} from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css']
})
export class AppComponent {
  title = 'app works!';

  @ViewChild('modal')
  modal: ElementRef;

  ngAfterViewInit(): void {
    jQuery(this.modal.nativeElement).modal({});
  }

  ngDoCheck(): void {
    console.log('check');
  }

```
}

**Comment by zoechi** [comment]
You might want to switch to use https://angular.io/docs/js/latest/api/core/index/ChangeDetectionStrategy-enum.html#!#OnPush-anchor

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
It is definitively a support request and as such should go to the appropriate support channel, as pointed out by @zoechi .

Moreover it is not clear at all what kind of modal impl you are using. Is it a hand-rolled one? As existing library? if you are using a 3rd party library please ask for support using their support channel.
