### ISSUE TITLE
 Cannot read property 'pathsWithParams' of undefined(…)

### ISSUE THREAD

**Issue by matanshukry** [angular/angular#10477]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Console error (at least) when using two routes with same path, one having optional parameter.
```
{ path: 'users', component: UsersComponent },
{ path: 'users/:id', component: UserComponent }
```

Also, when using the path with the parameter, and looking at the params object, e.g.:

```
this.router.routerState.queryParams.subscribe(params => { console.log(params); });
```
The object is empty.

The error:
```
 Cannot read property 'pathsWithParams' of undefined(…)
```
I am using webpack, and not entirely sure why, but the stacktrace isn't pretty and I couldn't get more info from it. However, With a little debugging (of the compiled js files, I'm afraid), I found the source of it, which is:

https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/router/src/url_tree.ts#L40

I know the code has changed (looking at the master branch), but both seems to come from the same point, and both assume ```container: UrlSegment``` isn't empty (which as the error shows, it is).

**Expected/desired behavior**
1. There shouldn't be a console error message
2. The route should be chosen based on the parameter provided (or missing)
3. The parameter should be filled in the params object, assuming the was a parameter

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Not sure how to create a plnkr with Angular2.
Either way, simply using two routes with same path (with only a query parameter as difference), the result should be the same.

**What is the expected behavior?**
Written above..

**What is the motivation / use case for changing the behavior?**
To allow one to use an optional query parameter in a rout.
The way I've tried to do it was the way I found one should do it in Angular.

**Please tell us about your environment:**
- Windows 10
- Node v6.3.0

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome 52.0.2743.32 (Official Build) m (64-bit)] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by jondejong** [comment]
In this case, you need to set pathMatch to full on the first route. It defaults to prefix. You'll never hit the second route.

**Comment by matanshukry** [comment]
Actually, my bad.
1. Route paths in Angular must not start with '/', it was a typo above, doesn't exists in my code. Edited the post.

2. The actual problem came from using an attribute routerLink with placeholder query parameter in it (part of the "system" I'm using). The result html was something like:
```<a ... [routerLink]=['user/:id'] ..>```, which shows the error.

Obviouslly this is not correct, so feel free to close this issue.
One might want to throw a better message though, in such a case.

3. Now that I fixed the problem (2), everything is working, including routing to both the route with and without the query parameter. Currently, the 'user' route is before the 'user/:id' route, and it is working. Also, none of them has any pathMatch attribute, so both use default (which is prefix?).

**Comment by vsavkin** [comment]
Closing this issue.

>Now that I fixed the problem (2), everything is working, including routing to both the route with and without the query parameter. Currently, the 'user' route is before the 'user/:id' route, and it is working. Also, none of them has any pathMatch attribute, so both use default (which is prefix?).

The pathMatch attribute is useful mostly for redirects. You can read more about it here: http://vsavkin.tumblr.com/post/146722301646/angular-router-empty-paths-componentless-routes

Briefly, the router will do backtracking until it finds a route that matches. So if you are navigating to `/user/1`, it will try the first route first. It won't succeed (cause there is unconsumed '1'), so it will try the second one next.
