### ISSUE TITLE
PUT request makes POST request

### ISSUE THREAD

**Issue by jacksoncharles** [angular/angular#10470]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Submitting a http PUT request without subscribing to the observable sends a POST request instead.

**Expected/desired behavior**
Suitable error else make the PUT request

**Reproduction of the problem**
  ** When called with this line of code
   this.socialMediaAccountService.update( this.socialMediaAccount.id, this.socialMediaAccount );

   *** socialMediaAccountService.ts
    update( id, socialMediaAccount ) : Observable<SocialMediaAccount> {

        let url = this.socialMediaAccountUrl + '/social_media_accounts/' + id;
        let body = JSON.stringify( socialMediaAccount );
        let headers = new Headers({ 'Content-Type': 'application/json'});
        let options = new RequestOptions({ headers: headers });

        return this.http
        .put(url, body, options)
        .map(this.extractData)
        .catch(this.handleError);
    }

The "update" method makes a POST request

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
**Language:** TypeScript

**Comment by vicb** [comment]
Please add a plunker

**Comment by markpritchett** [comment]
It appears to work correctly for me.  Here's a working plunker - https://plnkr.co/edit/ZOQJHCiLeq92mPoN02ZU?p=preview. 

If you look at the **app/data.service.ts** file, you should see the following method:

``` typescript
makePutRequest (): Observable<any[]> {
    let headers = new Headers();
    headers.append('Content-Type', 'application/json');
    
    let bodyObj = {
      userId: 1,
      id: 1,
      title: "new title",
      body: "new body"
    };
    
    return this.http
      .put('https://jsonplaceholder.typicode.com/posts/1', JSON.stringify(bodyObj), {headers: headers})
                    .map(this.extractData)
                    .catch(this.handleError);
  }
```

Using the developer tools in your browser of choice, look at the network requests.  You should see that it's making a **PUT** request.

**Comment by zoechi** [comment]
Shouldn't it do **nothing** unless subscribed to?

**Comment by vicb** [comment]
> It appears to work correctly for me. Here's a working plunker

thanks @markpritchett
