### ISSUE TITLE
Error With New Router

### ISSUE THREAD

**Issue by jspenc72** [angular/angular#10474]
```
[ x] bug report
```

**Current behavior**
Nested Parent/Child Routes and Route Redirects Are Buggy...

- I have the following route configuration which works perfectly.

```ts
//app.routes.ts

const routes: RouterConfig = [
  { path: '', component: LaunchComponent },
  ...freelancerDashboardRoutes,                       //Parent/Child Route Definition listed first
  { 
    path: 'freelancer-dashboard',                       //Redirect Route Definition
    redirectTo: '/freelancer-dashboard/projects',
    pathMatch: 'full'   	 
  }  
];

//freelancer-dashboard-routes.ts

export const freelancerDashboardRoutes: RouterConfig = [
  {
    path: 'freelancer-dashboard',
    component: FreelancerDashboardComponent,
    children: [
      { path: 'projects',  component: FreelancerProjectsComponent },
      { path: 'account',  component: FreelancerAccountComponent },
      { path: 'freelancers',  component: FreelancerTeamComponent },
    ]
  }
];
```

- However this slightly different route definition does not work. 

- Changing the order in which the parent / child and redirect routes are defined makes it impossible to access the other child routes.

```ts
//app.routes.ts

const routes: RouterConfig = [
  { path: '', component: LaunchComponent },
  { 
    path: 'freelancer-dashboard', 
    redirectTo: '/freelancer-dashboard/projects',     //Redirect Route Definition
    pathMatch: 'full'   	 
  } ,
  ...freelancerDashboardRoutes,                              //Parent/Child Route Definition
];

//freelancer-dashboard-routes.ts

export const freelancerDashboardRoutes: RouterConfig = [
  {
    path: 'freelancer-dashboard',
    component: FreelancerDashboardComponent,
    children: [
      { path: 'projects',  component: FreelancerProjectsComponent },
      { path: 'account',  component: FreelancerAccountComponent },
      { path: 'freelancers',  component: FreelancerTeamComponent },
    ]
  }
];

``` 
In short, if the parent redirect route is defined before the children routes then when trying to navigate to a child route results in having the redirect occur before you reach the child route.

**Expected/desired behavior**
- Nested Parent Route redirects should work regardless of the order in which they are defined.

**Reproduction of the problem**
1. create new project with angular cli
2. setup routing as I have shown above.

**What is the expected behavior?**
- Nested Parent Route redirects should work regardless of the order in which they are defined.

**What is the motivation / use case for changing the behavior?**
- Under normal use, developers will encounter this bug and may not think of simply switching the order. 

-  The goal is that when navigating to a parent route you can redirect to a child so that the "default" child view is visible without the user having to navigate manually. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript]

**Comment by brandonroberts** [comment]
This is something that can be cleared up in the docs, but its intended behavior. The order of the route configuration matters in the URL matching process. It would have been more prone to error if different weight had to be give to different types of routes.

**Comment by jspenc72** [comment]
Can you provide an example of how to get this to work? Because the behavior is not consistent?

**Comment by jspenc72** [comment]
I am just trying to have the parent to automatically load a child route?

**Comment by jspenc72** [comment]
This is an expansion on what is shown above. However the redirect does not occur with the second parent route.

**Comment by jspenc72** [comment]
nvm i had a previous declaration of the employer-dashboard route defined which was causing it to fail.

**Comment by yaroslavya** [comment]
@jspenc72 did you figure out is this an intended behavior or its a bug? Just digging into the router right now and have similar issues.

**Comment by jspenc72** [comment]
@yaroslavya its the intended behavior. Whatever route is defined first will be applied first... Router will match the first route it can and change to that state, ignoring any subsequent ones.

**Comment by vicb** [comment]
from @brandonroberts above:

> This is something that can be cleared up in the docs, but its intended behavior. The order of the route configuration matters in the URL matching process. It would have been more prone to error if different weight had to be give to different types of routes (static, wildcard, parameter).

Please open an issue on angular/angular.io to ask the docs to be clarified. Thanks

**Comment by jspenc72** [comment]
Filed an issue now.

**Comment by brandonroberts** [comment]
An explanation for the route matching strategy has already been added to
the docs.

**Comment by vicb** [comment]
👍
