### ISSUE TITLE
ngOnInit Issue

### ISSUE THREAD

**Issue by porf25** [angular/angular#10478]
I have a problem that I can't consistently reproduce. Once my app loads up, ngOnInit function doesn't always run right away. Rest of the page functions correctly and ngOnInit function will run a few seconds (sometimes a minute) later.

I don't know what could be causing this, it might have to do with zones.js and application lifecycle? I think something is preventing ngOnInit function from running rightaway, even when the page visually reloads, but I don't know how to check what is hanging it.

**Comment by jondejong** [comment]
How can you verify that it's not being run? The reason I ask: I've noticed the same thing with console.log statements not showing up right away, yet ngOnInit has clearly run. It's being (in my case) used to initialized data in the template. The template is rendered seconds before the console log will appear. I assume this is something (possibly Zone) buffering up the output of console before executing them.

**Comment by porf25** [comment]
I am sure because I placed a break point. also, I just noticed that it runs after I click any button with an event attached to it, for example (change)

**Comment by jondejong** [comment]
Ok. I have not seen that issue as you have described it.

**Comment by ericmartinezr** [comment]
Sounds like a support question, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question , also you are missing the most inportant part : the reproduction. But as suggested you could ask in the support forums.
