### ISSUE TITLE
Multiple level children routes

### ISSUE THREAD

**Issue by joeSaad** [angular/angular#10480]
Is there a way to have multiple level children routes with one router outlet? 

/a/b/c 
/a/b/c/d 
/a/b

They all have the same router-outlet 

Thanks, 

**I'm submitting a ...**  (check one with "x")

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Seems like every route has to have one router-outlet

**Expected/desired behavior**


**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).



**What is the expected behavior?**



**What is the motivation / use case for changing the behavior?**



**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [all | TypeScript 1.8.7| ES5]

**Comment by brandonroberts** [comment]
Router outlets are intended to only serve one level of grouping/routing at a time.

**Comment by StephenFluin** [comment]
@joeSaad I believe this works as you are hoping already.  For example, this works:

    { path: 'experts', component: ExpertsComponent },
    { path: 'experts/:id', component: ExpertViewComponent },
    { path: 'experts/:id/edit', component: ExpertEditComponent },
    { path: 'events', component: EventsComponent },
    { path: 'events/submit', component: EventSubmitComponent },
    { path: 'events/:id', component: EventViewComponent },
    { path: 'events/:id/edit', component: EventEditComponent },
    { path: 'communities', component: CommunitiesComponent, },
    { path: 'communities/submit', component: CommunitySubmitComponent },
    { path: 'communities/:id', component: CommunityViewComponent, },
    { path: 'communities/:id/edit', component: CommunityEditComponent },
    { path: 'login', component: LoginComponent },
