### ISSUE TITLE
Controller 'ngMessages', required by directive 'ngMessagesInclude', can't be found!

### ISSUE THREAD

**Issue by xbagir** [angular/angular#1048]
Does not work directive ngMessagesInclude:

`<ng-messages for="myForm.myName.$error" ng-messages-include="common/templates/errors.html">   
</ng-messages>`

**Comment by pkozlowski-opensource** [comment]
Wrong repo, this one is for Angular 2, I guess you are looking for https://github.com/angular/angular.js

Having said this, I don't think anyone will be able to help you based just on the info provided - there is just not enough context... Put together a minimal reproduce scenario using plunker or similar before opening a new issue....
