### ISSUE TITLE
FocusEvent relatedTarget is null on sometimes

### ISSUE THREAD

**Issue by MyHeartsECO** [angular/angular#10481]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you lose focus to a certain dom, you cannot find this "target" dom sometimes. I can't figure out which situation but it happens frequently.

to explain:

`(blur)="onNoteSubmit($event)"`

when you log this event you can see relatedTarget is null.

`FocusEvent {isTrusted: true, relatedTarget: null, view: Window, detail: 0, which`

**Expected/desired behavior**
This relatedTarget works for **inputs**, like:

`FocusEvent {isTrusted: true, relatedTarget: input#input1.col-xs-10.title.ng-untouched.ng-pristine.ng-valid, view: Window, detail: 0, which:
`
but I couldn't make this work anywhere else.

**What is the motivation / use case for changing the behavior?**
I want to know if I've lost focus to another dom inside my form or not, so I can collapse my form inputs or not. If I'm doing wrong I'm open to any solutions, since there isn't enough wiki on web.

**Please tell us about your environment:**
Webstorm 2016

* **Angular version:** 2.0.0-rc.4
 
* **Browser:**
Latest Chrome.
 
* **Language:**
all

**Comment by zoechi** [comment]
Please provide a Plunker to reproduce. Does this work in plain JS?

**Comment by vicb** [comment]
Angular only forward the events.

There should be no reason why it works in plain JS and not within angular. If you can create a plunkr showing a real bug please re-open an issue. Thanks.
