### ISSUE TITLE
Looping binded @input on ngFor - iterator problem

### ISSUE THREAD

**Issue by salvasanzandres** [angular/angular#10495]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

[plnkr](http://embed.plnkr.co/JBViihqmm1PcjouRZzlq/)

In app.ts I load a big array, (notice the array ends with "X","Y","Z" elements).
the array is an @Input.
the array has a selection range also in @Input that can be moved with navigator.

Dragging the navigator makes you move on the array box (red section). When you drag the left side of navigator towards the right sometimes elements are not displayed in the correct position. you can check with the "X","Y","Z" at the end of the box.

If you check the console you'll see how the iterator is messed (sometimes)

![ap7co](https://cloud.githubusercontent.com/assets/14203720/17405453/cae1c014-5a5f-11e6-9da1-0bc084ee2c47.jpg)

* **Angular version:** 2.0.0-rc.X

 
* **Browser:** [Chrome] 
 
* **Language:** [ TypeScript]

**Comment by zoechi** [comment]
If you use primitive values you need to use `trackBy`

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by vicb** [comment]
what @zoechi said, thanks !

**Comment by salvasanzandres** [comment]
Thanks for your comments.
I updated the project with trackBy:index and using the reference to the object and the values still no correct (sometimes).
[plnkr.co](http://embed.plnkr.co/JBViihqmm1PcjouRZzlq/)

**Comment by zoechi** [comment]
It's still a support question and should be asked in the listed channels.
