### ISSUE TITLE
a question about single-page applications

### ISSUE THREAD

**Issue by CK110** [angular/angular#10490]
hello!

From the official website, it seems, angular2 is used in single-page applications, I want to know whether it is suitable for multi-page applications. if it is recommended in multi-page applications ?

**Comment by zoechi** [comment]
Aren't multi-page applications only multi single-page applications ;-)

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by sod** [comment]
1. You have to setup offline compiling of the components or you have the component compile lag (~1 second) on each request.
2. You can't use angular2 to enhance the templates you build from the template engine of your backend like you used to in angular1. The templates must be part of the angular2 components. And from the point on where everything is written in angular2, you might as well do a single-page-app where the backend will just remain as an API.

**Comment by pkozlowski-opensource** [comment]
GitHub is not an appropriate place for this type of general discussion. Please use forums pointed out by @zoechi
