### ISSUE TITLE
Router Outlet's activate event doesn't seem to fire

### ISSUE THREAD

**Issue by joeeames** [angular/angular#10507]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
the activate event doesn't fire

**Expected/desired behavior**
the activate event should fire

**Reproduction of the problem**
http://plnkr.co/edit/e03oqajVmV4O7aEURC6L?p=preview

There's a parent component with 2 child routes. one is the default, the other is an option. there's a link to go between the child routes. The activate event doesn't fire for that router outlet.

**What is the expected behavior?**
the activate event should fire

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
plunker rc4
* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [ Chrome XX ] 
 
* **Language:** [TypeScript X.X ]

**Comment by qdouble** [comment]
I don't think this feature is on RC4, you'll have to use incremental builds or wait for RC5: http://plnkr.co/edit/qT0bFN?p=preview

**Comment by joeeames** [comment]
that would make sense. should it be closed then?

**Comment by qdouble** [comment]
@joeeames yes you can close, as it works as expected, it's just not in rc4.

**Comment by vsavkin** [comment]
Closing this issue. The feature is not in RC4.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
