### ISSUE TITLE
Validation attribute binding doesn't work fine.

### ISSUE THREAD

**Issue by tolemac** [angular/angular#10505]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you bind validation attributes the ngModel doesn't expose the correct errors.
When I set binding for `minlength` attribute ngModel.errors never expose `minlength` error.
When I set binding for `pattern` attribute ngModel.error has `pattern` error but with wrong pattern value (^null$).

**Expected/desired behavior**
ngModel.errors has to expose the correct errors.
For `minlength` validation ngModel.errors has to expose `{"minlength": { "requiredLength": 2, "actualLength": 1}`
For `pattern` validation ngModel.errors has to expose `{ "pattern" : ....}`

**Reproduction of the problem**
Here is the plunkr: http://plnkr.co/edit/BCJ8wMpaYMT7PdrpgAFI
There are two inputs with validation attributes showing value, classes and ngModel validation errors. 

The first one has attributes setted with values and works fine.
The second one has validation attribute bindings on `require`, `minlength`, `maxlength` and `pattern`, but only required works fine, `minlength` never apperars in validation errors and `pattern` has wrong value (example:  { "pattern": { "requiredPattern": "^null$", "actualValue": "dd" } }). `maxlength` seems to work fine but I think that it is due to native HtmlInputElement implementation.

**What is the expected behavior?**
I think we should able to bind `minlength` and `maxlength` directly without ' attr.'  preffix, but the most important is that ngModel.errors can to expose the correct error to be used to show error messages.

**What is the motivation / use case for changing the behavior?**
We need validation attribute binding in order to create custom input components.
For example you can see [`md-input` implementation of angular material 2](https://github.com/angular/material2/blob/master/src/components/input/input.html) it has `[attr.minlength]` binding however its doesn't work ...

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript]

**Comment by tolemac** [comment]
Btw, I have seen some issues where people tell about that but I can't find an issue about it directly.

I think isn't a duplicate issue.

**Comment by zoechi** [comment]
dup of #7393

**Comment by tolemac** [comment]
@zoechi #7393 is about maxlength and it has a tricky solution using attr.maxlength binding. 
I think that issue is more concrete and correct. In addition here tells about problem with minlength and patter. 

IHMO.

**Comment by zoechi** [comment]
I think it's the same for all validator attributes in combination with binding.

**Comment by tolemac** [comment]
I have created a pull request (#10518) that solve it.
