### ISSUE TITLE
FF Date pipe repeats string

### ISSUE THREAD

**Issue by hartjus** [angular/angular#10509]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
*FireFox Only* The date pipe is producing the string incorrectly when using a custom formatting mask.  

I'm aware of the fact that there are support problems with the Intl api on Firefox, but want to get this in your backlog.

**Expected/desired behavior**
The date string should be produced as per the formatting string.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Unfortunately, I couldn't reproduce this in plunkr, but if I set a breakpoint in my code and ran the following it produces the error:
```
datePipe.transform(new Date(), "MM/dd/y");
#   =>  "8/4/2016/8/4/2016/8/4/2016"
```
We see this behavior in a child component that is created from a page via the `<router-outlet>`.

One additional thing to note, is that using 'shortDate' as the format seems to work in FF.  But if we feed a custom format in there, the error occurs.

**What is the expected behavior?**

I would expect the following code to produce:
```
datePipe.transform(new Date(), "MM/dd/y");
#   =>  "08/04/2016"
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | **Firefox 45.2.0** | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | **TypeScript 1.8** | ES6/7 | **ES5**]

**Comment by vicb** [comment]
We can not do anything without a repro, sorry
