### ISSUE TITLE
unexpected behavior of the html object for {{ }} interpolation in IE 10.

### ISSUE THREAD

**Issue by KiranKumar1986** [angular/angular#10506]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using the html object tag to show the pdf document in the webpage.
data attribute is provided with the angular 2 interpolation. This result in a dark page, in IE 10.
It is working as expected in Chrome. 

   docLocation:string='../docs/training.pdf';
 	
`<object data={{docLocation}} 
        type='application/pdf' 
        width='100%' 
        height="700">
		<p>This browser does not support inline PDFs. Please download the PDF to view it: <a href={{docLocation}}>Download PDF</a></p>
		</object>`

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

The behavior of the html object should be same as the google chrome, across the browsers. 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [ | IE 10 | ] 
 
* **Language:** [ | TypeScript 1.8.10 | ]

**Comment by vicb** [comment]
Could you try `[attr.data]="docLocation"` instead ?

**Comment by vicb** [comment]
Seems like a known issue: http://stackoverflow.com/questions/32282956/pdf-embedding-in-ie10-not-working-with-object-tag

If you can make it work in plain html (w/o using angular) and it does not work in angular p[lease open an issue and provide a plunker. Thanks.

**Comment by KiranKumar1986** [comment]
It is working in IE 10 , if I am not using the angular functionality of interpolation.
I tried below it is working good.
<object data="../docs/training.pdf" type='application/pdf' width='100%' height="700">
