### ISSUE TITLE
Multiple Aux route not working when in same component

### ISSUE THREAD

**Issue by ranjanmadhu** [angular/angular#10504]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Current behavior**
multiple aux route in the same component can not be activated at the same time.

**Expected/desired behavior**
multiple aux route in the same component should be activated at the same time.

**Reproduction of the problem**
http://plnkr.co/edit/5DElSz6QslBljFtoHzrc?p=preview

**What is the motivation / use case for changing the behavior?**
Aux routes are very powerful feature of new Routing engine, There can be multiple situation when one needs to activate multiple aux routes. 

For e.g. there may be a aux routes for showing a chat window and another one for showing some tools in the same main component.   

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Angular Router version:** 3.0.0-beta.2

**Comment by mlc-mlapis** [comment]
There should be used syntax bellow for "allroute" and then it works correctly:

allroute= () =>{
     this.router.navigateByUrl('/route1(aux1:aux1-route//aux2:aux2-route)');
}

**Comment by ranjanmadhu** [comment]
Thanks that works!!!
