### ISSUE TITLE
Tutorial pt. 6 Routing, problem/concern

### ISSUE THREAD

**Issue by CaesarOG** [angular/angular#10508]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The following code below in pt. 6 of the Tutorial (Routing) doesn't work. Specifically, the getHero.then promise in the ngOnInit is async so it causes an error in the template. That is, when the first attempt to interpolate hero.name or hero.id occurs, hero is still undefined and you get all sorts of ugly red errors saying "cannot read property name/id of undefined". I found that moving the promise to the constructor works, but this doesn't seem like a good practice for debugging. What is a good solution?

import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { Hero } from './hero';
import { HeroService } from './hero.service';

@Component({
  selector: 'my-hero-detail',
  templateUrl: 'app/hero-detail.component.html',
})
export class HeroDetailComponent implements OnInit, OnDestroy {
  hero: Hero;
  sub: any;

  constructor(
    private heroService: HeroService,
    private route: ActivatedRoute) {
  }

  ngOnInit() {
    this.sub = this.route.params.subscribe(params => {
      let id = +params['id'];
      this.heroService.getHero(id)
        .then(hero => this.hero = hero);
    });
  }

  ngOnDestroy() {
    this.sub.unsubscribe();
  }

  goBack() {
    window.history.back();
  }
}

--------------------------------------------------------------------------------------------------
**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all] 
 
* **Language:** [ES6 typescript]

**Comment by vicb** [comment]
Wrong repo, please re-open on https://github.com/angular/angular.io/issues
