### ISSUE TITLE
When `inject` is before `fakeAsync` (and probably async), tests do not use the expected zone

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#10503]
When calling `TestBed.createComponent` or `TestCombponentBuilder.createAsync`, [the function uses `injector.get` to retrieve the `NgZone`](https://github.com/angular/angular/blob/master/modules/@angular/core/testing/test_bed.ts#L355). Any tasks (microTasks or macroTasks) that occur as part of the `createComponent` are added to this zone (and not to `Zone.current`). 

The `NgZone` is instantiated when `inject` is called, using whatever zone is `Zone.current` when the [constructor](https://github.com/angular/angular/blob/master/modules/@angular/core/src/zone/ng_zone_impl.ts#L47) is run.

This means that when `inject` is called _outside_ of a `fakeAsync` or `async`, then `Zone.current` will be `"angular"` (direct child of `"<root>"`).

As a result of this, any tasks spawned from calling `createComponent` will be added to the `"angular"` zone _instead_ of the testing zone when the test uses either `async` or `fakeAsync`.

Example:
```ts
beforEach(inject((tcb: TestComponentBuilder) => {
  builder = tcb;
}));

it('should test something with fakeAsync', fakeAsync(() => {
  let appFixture: ComponentFixture<any>;
  builder.createAsync(SomeComponent).then(fixture => {
    appFixture = fixture;
  });

  flushMicrotasks();

  expect(appFixture).toBeTruthy(); // FAIL, appFixture is undefined
}));
```

Here, the call to `flushMicrotasks` will *not* cause the `then`'ed function to execute because the task for the `createAsync` was added to the `"angular"` zone and *not* the `fakeAsyncTestZone`.

As a workaround, you can write:
```ts
  beforeEach(fakeAsync(inject([TestComponentBuilder], (tcb: TestComponentBuilder) => {
    builder = tcb;
  })));
```
When the function returned from `fakeAsync` is called, the current zone is forked into the `fakeAsyncTestZone`, so that `Zone.current` is the expected zone when `inject` runs and instantiates the `NgZone`, which is then consumed by `createAsync`, causing the microtasks to be added to the expected zone.

cc @IgorMinar @mhevery @juliemr

**Comment by juliemr** [comment]
The same root problem can also cause issues with race conditions in tests, even when `inject` is not used. If `TestBed.createComponent` is used in an `async` test block, tasks spawned on that component will be tied to that first test block. That means that a later test block won't know about those actions, and could exit early. For example:

```ts
    beforeEach(async(() => {
      TestBed.configureTestingModule({
        declarations: [AsyncInitTestApp],
      });

      TestBed.compileComponents().then(() => {
        fixture = TestBed.createComponent(AsyncInitTestApp);
      });
    }));

    it('should show tabs when they are available', async(() => {
      fixture.detectChanges();

      fixture.whenStable().then(() => {
        // The test won't properly wait for stability before continuing!!
      });
    }));
  });
```

(full example: https://gist.github.com/juliemr/d78fe8313bdb775acd7f4c944584ce67)

**Comment by juliemr** [comment]
See https://github.com/angular/angular/commit/16cc9b46aa166b19620979bac19d82d025a2ac0c, which explains why the two different `fakeAsync` calls in Jeremy's example share one zone and his workaround works. We do NOT currently do something like this for `async`, which explains my problem.

**Comment by juliemr** [comment]
cc @vikerman as well

**Comment by IgorMinar** [comment]
@juliemr yes, Tobias came across the issue of spawning brand new test zones for beforeEaches and its and fixed that for fakeAsync in 16cc9b4 - would you have time to send a PR for `async`? The solution should be similar to that in 16cc9b4

As far as fixing the original issue reported by @jelbourn. I'll discuss this with @mhevery. We have several options but none of the ones I currently know of I pretty.

**Comment by juliemr** [comment]
I can't think of anything pretty either. I can do the fix for async, but unless we have a larger solution we'll still have failures if we try to do something like mix async and fakeAsync.

**Comment by IgorMinar** [comment]
Rough proposal to create a special zone spec that knows how to proxy to delegate specs:

```
// global
=========
let _testProxyZoneSpec = null;


// lots of hand-waving here.. actual implementation will likely be very different
function async(fn) {
  _testProxyZoneSpec.setDelegate(new AsyncTestSpec());
  ...
  fn();
  ...
  _testProxyZoneSpec.setDelegate(null);
}

// lots of hand-waving here.. actual implementation will likely be very different
function fakeAsync(fn) {
  _testProxyZoneSpec.setDelegate(new FakeAsyncTestSpec());
  ...
  fn();
  ...
  _testProxyZoneSpec.setDelegate(null);
}

beforeEach(() => {
  // Zone.current: root
  // ngZone: null
  _testProxyZoneSpec = new TestProxyZoneSpec();
  Zone.current.fork(_testProxyZoneSpec);
  // Zone.current: root -> testZone(spec redirecting to: null)
  // ngZone: null
})


// spec
=======
beforeEach(inject(tcb: TestComponentBuilder) => {
  // Zone.current: root -> testZone(spec redirecting to: null)
  // ngZone: root -> testZone -> ngZone
})


it('should ...', async(() => {
  // Zone.current: root -> testZone(spec redirecting to: async)
  // ngZone: root -> testZone -> ngZone
  doAsyncWork();
}));


it('should ...', fakeAsync(() => {
  // Zone.current: root -> testZone(spec redirecting to: fakeAsync)
  // ngZone: root -> testZone -> ngZone
  doAsyncWork();
  flushMicrotasks();
}));
```

**Comment by juliemr** [comment]
I think this looks like the best option for now!

**Comment by rbnzdave** [comment]
but https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-8 explicitly states that fakeAsync is required to wrap inject and it wont work the other way around, 4 months before you listed this as a bug. as a result, I do see how fakeasync is actually supposed to be used now, as the documentation shows it the way you are trying, and there is no indication in the changelog that this order was changed back in a breaking way.
