### ISSUE TITLE
Flow type information across *ngFor-like directives

### ISSUE THREAD

**Issue by mhevery** [angular/angular#10510]
Alternative proposal for the: [Allow template local variables to publish type information so that IDEs can provide better completion](https://github.com/angular/angular/issues/4850)

Thanks to @chuckjaz for the clever idea.

```
class Person {
	first: string;
	last:string;
}

class MyComp {
	items: string[];
	people: Person[];
}


/**
 * Assume we have template such as this:
 * <div *ngFor="let person of people; trackBy: foo">
 *   {{people.length}}{{item.first}}
 * </div>
 */

// These global variables are here only to flow the type information.
var _comp: MyComp;
var _peopleLetType = NgFor.extractTypeFromOf(_comp && _comp.people);

class MyComponentFactory{
	context: MyComp;
	ngFor: NgFor<typeof _peopleLetType> = new NgFor<typeof _peopleLetType>(new DivInnerFactory());
	create() {
		this.ngFor.of = this.context.people;
	}
}

class DivInnerFactory {
	context: NgForRow<typeof _peopleLetType>;
	text: string;
	create() {
		this.context.$implicit.first; // expected type OK because $implicit is Person
		this.context.$implicit.name;  // expected type error because $implicit is Person
	}
}

class NgForRow<T> {
	$implicit: T;
}

@Component({
	// we need some way to hint to the template generated which property to use for type extraction
	// and which static function to use with that property.
	typeTransformation: ['of', NgFor.extractTypeFromOf]
})
class NgFor<T>{
	@Input({typeTransform: NgFor.extractTypeFromOf})
	of: T[];
	constructor(factory: Factory) {}
	static extractTypeFromOf<T>(expr: T[]|Iterable<T>): T {return undefined;}
}

interface Factory {
	create();
}
interface Iterable<T> {}
function Component(a:any): Function { return null; }
function Input(a:any): Function { return null; }
```

Try it out in [TypeScript playground](http://www.typescriptlang.org/play/index.html#src=class%20Person%20%7B%0D%0A%09first%3A%20string%3B%0D%0A%09last%3Astring%3B%0D%0A%7D%0D%0A%0D%0Aclass%20MyComp%20%7B%0D%0A%09items%3A%20string%5B%5D%3B%0D%0A%09people%3A%20Person%5B%5D%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F**%0D%0A%20*%20Assume%20we%20have%20template%20such%20as%20this%3A%0D%0A%20*%20%3Cdiv%20*ngFor%3D%22let%20person%20of%20people%3B%20trackBy%3A%20foo%22%3E%0D%0A%20*%20%20%20%7B%7Bpeople.length%7D%7D%7B%7Bitem.first%7D%7D%0D%0A%20*%20%3C%2Fdiv%3E%0D%0A%20*%2F%0D%0A%0D%0A%2F%2F%20These%20global%20variables%20are%20here%20only%20to%20flow%20the%20type%20information.%0D%0Avar%20_comp%3A%20MyComp%3B%0D%0Avar%20_peopleLetType%20%3D%20NgFor.extractTypeFromOf(_comp%20%26%26%20_comp.people)%3B%0D%0A%0D%0Aclass%20MyComponentFactory%7B%0D%0A%09context%3A%20MyComp%3B%0D%0A%09ngFor%3A%20NgFor%3Ctypeof%20_peopleLetType%3E%20%3D%20new%20NgFor%3Ctypeof%20_peopleLetType%3E(new%20DivInnerFactory())%3B%0D%0A%09create()%20%7B%0D%0A%09%09this.ngFor.of%20%3D%20this.context.people%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20DivInnerFactory%20%7B%0D%0A%09context%3A%20NgForRow%3Ctypeof%20_peopleLetType%3E%3B%0D%0A%09text%3A%20string%3B%0D%0A%09create()%20%7B%0D%0A%09%09this.context.%24implicit.first%3B%20%2F%2F%20expected%20type%20OK%20because%20%24implicit%20is%20Person%0D%0A%09%09this.context.%24implicit.name%3B%20%20%2F%2F%20expected%20type%20error%20because%20%24implicit%20is%20Person%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20NgForRow%3CT%3E%20%7B%0D%0A%09%24implicit%3A%20T%3B%0D%0A%7D%0D%0A%0D%0A%40Component(%7B%0D%0A%09%2F%2F%20we%20need%20some%20way%20to%20hint%20to%20the%20template%20generated%20which%20property%20to%20use%20for%20type%20extraction%0D%0A%09%2F%2F%20and%20which%20static%20function%20to%20use%20with%20that%20property.%0D%0A%09typeTransformation%3A%20%5B'of'%2C%20NgFor.extractTypeFromOf%5D%0D%0A%7D)%0D%0Aclass%20NgFor%3CT%3E%7B%0D%0A%09%40Input(%7BtypeTransform%3A%20NgFor.extractTypeFromOf%7D)%0D%0A%09of%3A%20T%5B%5D%3B%0D%0A%09constructor(factory%3A%20Factory)%20%7B%7D%0D%0A%09static%20extractTypeFromOf%3CT%3E(expr%3A%20T%5B%5D%7CIterable%3CT%3E)%3A%20T%20%7Breturn%20undefined%3B%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20Factory%20%7B%0D%0A%09create()%3B%0D%0A%7D%0D%0Ainterface%20Iterable%3CT%3E%20%7B%7D%0D%0Afunction%20Component(a%3Aany)%3A%20Function%20%7B%20return%20null%3B%20%7D%0D%0Afunction%20Input(a%3Aany)%3A%20Function%20%7B%20return%20null%3B%20%7D).

**Comment by chuckjaz** [comment]
Closed in favor of #12398
