### ISSUE TITLE
Typo or deprecated in "Angular Cheat Sheet" docs

### ISSUE THREAD

**Issue by perrierism** [angular/angular#10514]
- **Angular version:** 2.0.0-rc.4

In the [Angular Cheat Sheet](https://angular.io/docs/ts/latest/guide/cheatsheet.html) documentation, under "**Routing and navigation**" there is an import statement listed:

```
import {provideRouter, RouteConfig, ROUTER_DIRECTIVES, ...} from '@angular/router';
```

RouteConfig is no longer in router. (But there is a Route**r**Config)

I believe the hooks mentioned in this section are also deprecated/removed (routerOnActivate, routerOnReuse, etc.) but I could be wrong about that.

**Comment by vicb** [comment]
@wardbell do you know the plan to update the CS ?

**Comment by DzmitryShylovich** [comment]
Looks like already fixed.

**Comment by vicb** [comment]
@DzmitryShylovich thanks !
