### ISSUE TITLE
If root component isn't present on page, Angular throws multiple Exceptions

### ISSUE THREAD

**Issue by emilio-martinez** [angular/angular#10515]
**I'm submitting a ...**
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When bootstrapping the application in a browser environment, if the root element isn't present on the page, Angular throws multiple exceptions. Of course it's not optimal to load Angular if it won't serve any purpose, but I'm not sure what would be the use case for erroring in that manner. 

**Expected/desired behavior**
If the entry/root component isn't present on the page, rather than erroring out, maybe a console.warn(...) would suffice. Even when catching the promise, the multiple exceptions occur.

**Reproduction of the problem**
Reproduced by bootstrapping the Angular app and not having the main element on the host page.
http://plnkr.co/edit/t0PmVkDGk0rrknJlDHT3?p=preview

**What is the motivation / use case for changing the behavior?**
I don't particularly see the use case for forcing the root app element to be on the page. If there's a legitimate reason, it would be great to know, but otherwise I almost think it's overkill.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all
 
* **Language:** TypeScript

**Comment by sod** [comment]
I don't know if this behavior will change, but you can wrap bootstrap and fetch the selector from the Component via `Reflect.getMetadata('annotations', App)`. like:

```typescript
import {ComponentMetadata} from '@angular/core';
import {bootstrap} from '@angular/platform-browser-dynamic';
import {App} from './app';

const findAnnotation = function(classType, annotationType): any {
    const annotations = Reflect.getMetadata('annotations', classType);
    if (annotations && annotations.find) {
        return annotations.find((annotation) => annotation instanceof annotationType);
    }
};

const bootstrapIfExists = (appComponentType: Type): void => {
    const component: ComponentMetadata = findAnnotation(appComponentType, ComponentMetadata);
    const elements = Array.from(document.getElementsByTagName(component.selector));
    if (elements.length) {
        return bootstrap(appComponentType);
    } else {
        return Promise.reject(`Root Component <${component.selector}> not found.`)
    }
};

bootstrapIfExists(App, [])
  .catch(err => console.error(err));
```

http://plnkr.co/edit/EC2PpCgc44fiVFo3qSzB?p=preview

**Comment by emilio-martinez** [comment]
I agree that it can be checked for, but ultimately I don't know if it's prudent for the app to exit with exceptions other than failing silently and that's it. Anyway, I just thought to put it out there.

**Comment by emilio-martinez** [comment]
Reopening. The above by @sod wouldn't quite work with NgModules unless the entry component were available in bootstrap.

**Comment by pkozlowski-opensource** [comment]
> If the entry/root component isn't present on the page, rather than erroring out, maybe a console.warn(...) would suffice. Even when catching the promise, the multiple exceptions occur.

I will respectfully disagree.... Basically when you load this JS code in a browser `platformBrowserDynamic().bootstrapModule(AppModule)` you are saying: "bootstrap my an angular application here on the element with a specific selector". Failing silently in this case could lead to a lot of head-scratching on developers side....

Thnx for the suggestion but we are going to pass on it. If you've got a situation where the root component might not exist, you can check (DOM query) its presence before bootstrapping (you know what you bootstrap so you know what the `bootstrap`  components are and what are they CSS selectors).
