### ISSUE TITLE
[Router] passing more than 1 parameter

### ISSUE THREAD

**Issue by mleonhartsberger** [angular/angular#10521]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a datatable showing car models. When choosing a model, I try to navigate to the version overview:
`this.router.navigate(['version_overview', {modelId: model.id, modelName: model.name}]);`

But all I get is this error:
_Error: Cannot match any routes: 'version_overview;modelId=1;modelName=Camaro'_

**Expected/desired behavior**
Routing to the VersionOverview component and passing both parameters.

**Reproduction of the problem**
The one path, which should be matched:
`{path: 'version_overview/:modelId/:modelName', component: VersionOverview}`
I already tried different ways to pass more than 1 parameter, but nothing works.

Passing only 1 parameter works like a charm, when doing it this way:
`this.router.navigate(['version_overview', model.id]);`
`{path: 'version_overview/:modelId', component: VersionOverview}`

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
* **Router version:** 3.0.0-beta.2
 
* **Browser:** Chrome 51
 
* **Language:** TypeScript 1.8.10, ES6

Is this supposed to work / am I doing something wrong?
Thanks in advance,
Martin

**Comment by zoechi** [comment]
Plunker to reproduce?

I think it should be

    this.router.navigate(['version_overview', model.id, model.name}]);

**Comment by mlc-mlapis** [comment]
But the meaning is st else then original:
> this.router.navigate(['version_overview', model.id, model.name}]);
It would result to: /version_overview/xxx/yyy, isn't it?

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by zoechi** [comment]
@mlc-mlapis have you tried

**Comment by mlc-mlapis** [comment]
To be precise, there are two different kind of things in this case. The first one is so called "path segments" and the second "route parameters".
* Path segments are defined as: { path:  'version_overview/:id/:sid', component: xxx }.
* Route parameters are not defined on { path: 'version_guides', component: yyy } at all.

Path segments are then addressable as:
<a [routerLink]="['version_overview', 2, 'F']">Overview of versioning</a>
and the resulted URL will be: /version_overview/2/F

Route parameters are then addressable as (could be part of any path segment):
<a [routerLink]="['version_guides', { release: 5, lang: 'EN' }]">Guides on versioning</a>
and the resulted URL will be: /version_guides;release=5;lang=EN

It is possible to combine then together of course like:
<a [routerLink]="['version_overview', 2, 'F', { release: 5, lang: 'EN' }]">Overview of versioning</a>
and the resulted URL: /version_overview/2/F;release=5;lang=EN

I did not mention 'query parameters' and 'segment' yet which are global things on URLs.

I tested these examples on NG2 RC4 (Router 3 Beta 2).

**Comment by zoechi** [comment]
> We can provide optional query parameters in an object like this:
>
> ```
> <a [routerLink]="['/crisis-center', { foo: 'foo' }]">Crisis Center</a>
> ```

https://angular.io/docs/ts/latest/guide/router.html#!#link-parameters-array

Optional query parameters are represented as query parameters on the root component and matrix parameters on child components AFAIK

If you think there is a bug, please provide a Plunker to reproduce.

**Comment by mlc-mlapis** [comment]
Thare is only terminology inconsistency in docs a bit I think, because st like { foo: 'foo' } in:
`<a [routerLink]="['/crisis-center', { foo: 'foo' }]">Crisis Center</a>`
should not be called "Optional query parameters".

**Comment by zoechi** [comment]
I think they are. Just the representation is matrix parameter form depending on where they are added.

**Comment by mlc-mlapis** [comment]
Ok, no problem. It doesn't matter if you understand what is what. The only real differerence in reality is that some of them (query params) are global (uniq on URL) and others not (specific on an each path segment).

**Comment by mleonhartsberger** [comment]
thanks for all your answers!
I did not know, that multiple path segments are not given as 1 array but as separate method params.
So, the statement from zoechi helped me out:
`this.router.navigate(['version_overview', model.id, model.name]);`

@vicb I thought it was a bug - sorry for being wrong.
