### ISSUE TITLE
After router.navigate in ngOnInit of parent component, ngOnInit of child is still called 

### ISSUE THREAD

**Issue by JohannesAtGit** [angular/angular#10526]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After router.navigate() in ngOnInit of parent component, ngOnInit of child is still called.
I try to use router.navigate() in child ngOnInit again and it fails with error:
```
TypeError: Cannot read property 'toString' of undefined
at getPath (create_url_tree.ts:135)
at createNewSegment (create_url_tree.ts:221)
at updateSegment (create_url_tree.ts:163)
at updateSegmentChildren (create_url_tree.ts:174)
at Object.createUrlTree (create_url_tree.ts:28)
at Router.createUrlTree (router.ts:221)
at Router.navigate (router.ts:263)
at SafeSubscriber.eval [as _next] (conceptversion.component.ts:48)
at SafeSubscriber.__tryOrSetError (Subscriber.ts:249)
at SafeSubscriber.next (Subscriber.ts:193)
```

The problem can be fixed by setting a boolean variable in a sharedDataService and check it in the child ngOnInit method. 
But as I said I would expect that it is not necessary.

**Expected/desired behavior**
I would expect that ngOnInit is not called, because I have already routed to another site.

**Reproduction of the problem**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome 51.0.2704.103] 
 
* **Language:** [TypeScript 1.8]

**Comment by vicb** [comment]
There is nothing we can do without a reproduction of the issue

**Comment by JohannesAtGit** [comment]
I have updated the description of the issue and added a plunker example. In my regard the behavior is unexpected.
