### ISSUE TITLE
RouterState not documented as Tree<ActivatedRoute>

### ISSUE THREAD

**Issue by tiagoroldao** [angular/angular#10522]
RouterState documentation doesn't reflect that it is a Tree<ActivatedRoute>, with all the methods that that includes - which I assume to be a very important part of the state.

Also, this is inconsistent with the `Usage` code segment, which includes usage of it as a Tree.

**Comment by vicb** [comment]
As noted by @DzmitryShylovich, this is an issue with our documentation generation that will be fixed on angular.io.
