### ISSUE TITLE
Dynamically creating a component through ComponentFactory not created as expected.

### ISSUE THREAD

**Issue by Mutmansky** [angular/angular#10523]
**I'm submitting a bug report**

**Current behavior**
Using ComponentFactory.create and passing a node where I want the component created results in the component's template only partially being inserted into the DOM.  Not all of the HTML is inserted and the text field has no functioning two-way data binding.

**Expected/desired behavior**
I expected the component to be completely inserted and function the same as if the component was created statically and/or as it works if it is created via ViewContainerRef.createComponent.

**Reproduction of the problem**
Here's a plunker based on the Angular 2 quickstart that illustrates the problem.
https://plnkr.co/edit/6x1cLKIaq9acXMVy64dB

**What is the expected behavior?**
When you click the "Create The Dynamic Component" button, it should create a DynComponent within the `<div id="dynCompDiv"> </div>`.  Note that one can experiment with this plunker and comment out the "create" call on the ComponentFactory and uncomment the "createComponent" call on the ViewContainerRef and see that components created that way work fine.  While I understand that the insertion of the div directly into the DOM is highly discouraged by Angular, I'm using a third party package (ag-grid) which is doing exactly that.  Furthermore, the Angular API seems to support this functionality, but it doesn't work as I expected it to.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4, although the same problem existed in rc2.
 
* **Browser:** Chrome '51.0.2704.103 m' on Windows 10 and Chrome '51.0.2704.63 (64-bit)' on CentOS
 
* **Language:** TypeScript 1.8.10

**Comment by Mutmansky** [comment]
There's also a little bit more explanation and discussion on SO at: http://stackoverflow.com/questions/38754121/in-angular-2-creating-a-component-through-componentfactory-does-not-seem-to-ren

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by Mutmansky** [comment]
I'm not sure I understand why you think this is a support request.  I don't believe the Component is being created correctly.  The DOM clearly does not contain the template that's in the DynComponent.  I certainly could be using this wrong or not understand the expected behavior, but if I am and this is expected behavior, can you please explain why?

**Comment by vicb** [comment]
Dynamic component creation is used internally (for ex by the router) and I doubt it does not work.

**Comment by vicb** [comment]
And on the why I've closed the issue: the expected / current behavior should be short and synthetical.

Seems like your "expected behavior" are actually the steps to reproduce. By briefly reading the issue I guess I would spend more time trying to figure out what you expect than resolving a genuine issue.

I'm sorry but we have to be agressive closing issues, we have 1000+ issues pending and can not afford to loose time going trough them. Hope you understand.

**Comment by Mutmansky** [comment]
Indeed, I stepped through the code and saw it work successfully for multiple component creations (via both the router and a ViewComponentRef.createComponent call), but in each case where I saw it work correctly, the “rootSelectorOrNode” argument was null.

When I’m calling create, I’m passing in the id of an arbitrary div element.  Perhaps that parameter is not what I think it is or what I’m doing is not supported?  The API documentation doesn’t place any restrictions on that parameter.  That’s where I’m not certain.

Thanks for replying,

Steve Mutmansky
Senior Software Engineer

(267) 535-6031
steve.mutmansky@mmodal.com<mailto:steve.mutmansky@mmodal.com>
www.mmodal.com<http://www.medquist.com/>

This electronic mail transmission contains confidential information intended only for the person(s) named. Any use, distribution, copying or disclosure by another person is strictly prohibited. If you are not the intended recipient of this e-mail, promptly delete it and all attachments.

**Comment by Mutmansky** [comment]
Note that you have 2 “Expected Behavior” fields in your submission template.  The first “Expected/desired behavior” I have a short and sweet explanation of I expect.  I expect the component to be created and it is not being created.

The second “What is the expected behavior” field is under the “Reproduction of the problem” heading; therefore, I took that Expected Behavior to be the explanation of my reproduction of the issue in Plunker.  Quite possibly I misunderstood your submission template, but if so, why have two “Expected Behavior” fields in the first place?  Seems redundant.

Steve Mutmansky
Senior Software Engineer

(267) 535-6031
steve.mutmansky@mmodal.com<mailto:steve.mutmansky@mmodal.com>
www.mmodal.com<http://www.medquist.com/>

This electronic mail transmission contains confidential information intended only for the person(s) named. Any use, distribution, copying or disclosure by another person is strictly prohibited. If you are not the intended recipient of this e-mail, promptly delete it and all attachments.

**Comment by Mutmansky** [comment]
Just to completely document the thread, here's a copy of the email I sent Victor that prompted the two responses from him (and my replies) above:

Victor,

I’m trying to understand why you’ve closed Angular2 issue #10523.  The API for ComponentFactory.create simply says:

“create(injector: Injector, projectableNodes?: any[][], rootSelectorOrNode?: string|any) : ComponentRef<C>
Creates a new component.”
However, it does not create the component (at least not correctly) if you pass it a node in the third parameter.  It seems to find the node appropriately and inserts part of the component in there.  Can you please explain if this is expected and if so, why?  I certainly can accept that I may be missing something here, but I’m not sure what I’m missing.

Thanks,


Steve Mutmansky

**Comment by zoechi** [comment]
@Mutmansky that's what the support channels mentioned in Vics first comment are for. After you consulted them you can be confident that you didn't miss anything and that it's a bug.

**Comment by Mutmansky** [comment]
@zoechi Please see previous comment with referenced SO post that you commented on.  Note that this bug in no way asks for support.  I provided a plunker where the component being loaded isn't correctly being loaded (I also edited the SO post with the Plunker link).  Asking what I'm missing in the email was simply me trying to be polite and leave open the possibility that this isn't a bug and that I'm simply using Angular2 or the ComponentFactory incorrectly.  Perhaps I should stop trying to be polite...

The Plunker is very simple and is based on the Angular2 Quickstart and the two-way data binding developer guide.  Until someone can explain why it's not a bug, I maintain that it's a bug.

**Comment by laPlacek** [comment]
@vicb by all means what @Mutmansky has reported is a bug.
In A2 documentation (https://angular.io/docs/ts/latest/guide/architecture.html#!#components)
"A component controls a patch of screen called a view."

However componentFactory's create method creates an entity, that does not have working bingings - ergo it DOES NOT fulfil A2 component definition (the enityt created by componentFactory is not able to "control a patch of screen called a view.")

**Comment by DzmitryShylovich** [comment]
@laPlacek if u think it's a valid bug pls reproduce it in plunkr and open a new issue pls

**Comment by Mutmansky** [comment]
@laPlacek and @DzmitryShylovich, I updated the plunker I previously created here:

[https://plnkr.co/edit/sD800XIb23gD7xftJha8?p=preview](url)

I don't plan to submit a bug since this bug was closed and for me it's a bit of a moot point now.  This came up for me when working with ag-grid which at that time wanted a nativeElement returned to it in certain scenarios (like creating dynamic filters).  At this point, ag-grid has been updated to the more recent version of Angular 2, so this has all likely changed.  At some point I'll revisit that and see if there are still issues around this.

As a side note, @laPlacek , if you still need to get this working, I have a similar situation elsewhere in my app.  I tackled that scenario in a different way.  I basically created a component (DynamicItemComponent) that took as an input the "name" of the component I wanted to dynamically create.  Then that DynamicItemComponent had a map of those component names to the type of the component that needed to be created for that type.  You can then use that map in the resolveComponentFactory call (using the name to look up the type) and create the component you want within the DynamicItemComponent.  I don't like the existence of that map.  It feels like a hack, but since there's no true reflection here like in Java, I didn't see any way around it.  That inner component will still be parallel to whatever reference in that DynamicItemComponent you use, but you can put the DynamicItemComponent's selector within whatever div you really want the dynamic component to "live."  BTW, a @zoechi answer on SO inspired this solution, so thanks @zoechi !

If that doesn't make sence, @laPlacek , let me know.  Maybe I can create another Plunker to illustrate.
