### ISSUE TITLE
request| feat(Router): provide ExtraOptions to turn off ANALYZE_FOR_ENTRY_COMPONENTS

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#10539]
When a developer needs more control over their `entryComponents` and `declarations` and `ANALYZE_FOR_ENTRY_COMPONENTS` forces them to be created the root module. This leads to errors in a dev's `MainModule` or `DynamicModule` created by `bootstrap` about having multiple `entryComponents` and `declarations`

**Comment by wardbell** [comment]
My instinct is that the need for this feature arises from pursuing the _monolithic router configuration_ pattern which is no longer necessary (as of `RouterModule.forChild(moduleRoutes)` and actively discouraged.

**Comment by gdi2290** [comment]
closing:
when migrating from rc4 to rc5 the developer should not use NgModule until rather they get their app working with the one NgModule within bootstrap
