### ISSUE TITLE
Location.replaceState() overrides parameters with the same name upon navigation

### ISSUE THREAD

**Issue by withjam** [angular/angular#10535]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When navigating to a route with query params that use the same name, the parameters get replaced with only the last occurrence when the route is processed.  For example:  location.replaceState('search', 'q=abc&facet=foo:bar&facet=state:PA') the url created gets replaced upon navigation to search?q=abc&facet=state:PA 

**Expected/desired behavior**
URLs would support query params with the same name and produce an array of values.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.X
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by DzmitryShylovich** [comment]
it's the default behavior of `history.replaceState`. Don't think we can do much here.

**Comment by atscott** [comment]
This appears to be fixed in Angular 9: https://stackblitz.com/edit/angular-ivy-q7buyy?file=src%2Fapp%2Fapp.component.ts
