### ISSUE TITLE
ngModel, ngIf and ngModel ref variable combination have strange behavior ..

### ISSUE THREAD

**Issue by tolemac** [angular/angular#10531]
**I'm submitting a ...**  

- [x] bug report

**Current behavior**
I have appreciated a strange behavior when you use `ngModel` referenced with a ref variable and `ngIf`, the ref variable seems not set when use `ngIf`
For example:
````
<input *ngIf="showSecond" ngModel #valueInput2 #valueModel2="ngModel" 
      required minlength="2" maxlength="5" pattern=".{3,}"/>
    <div>Errors: {{valueModel2?.errors | json}}</div>
````
`valueModel2` is null, however when you remove the `*ngIf` this works fine ...

**Expected/desired behavior**
I think `*ngIf` shouldn't affect to ngModel ref varialbe.

**Reproduction of the problem**
Here a plunkr: http://plnkr.co/edit/Dnn7LpMnCksXFwG1qgMs
Two inputs with the same attributes, the first works fine but the second don't work.

If you remove the ngIf from second input that works.

**What is the expected behavior?**
`*ngIf` shouldn't affect.

**What is the motivation / use case for changing the behavior?**
You could want to conditional show an input.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4 
* **Browser:** [all]  
* **Language:** [TypeScript]

**Comment by zoechi** [comment]
dup of #6179

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi !

**Comment by tolemac** [comment]
I agree is dup, but why the issue is closed?
