### ISSUE TITLE
Location.replaceState does not work with ActivatedRoute.params

### ISSUE THREAD

**Issue by withjam** [angular/angular#10534]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using Location.replaceState(path, queryString) to update the search part of a path, the route resolvers do not properly map the query string as route parameters.  There is no way to access the query string in the route resolver without having to parse it manually.

**Expected/desired behavior**
Navigating to a route that uses query string parameters would populate ActivatedRoute.params the same way that matrix parameters do.  It seems like ng.common and ng.router do not agree on how to pass query string parameters.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by vsavkin** [comment]
Could you provide a plunker reproducing the issue?
