### ISSUE TITLE
Server-side rendering (isomorphic JavaScript)

### ISSUE THREAD

**Issue by pensierinmusica** [angular/angular#1053]
Is Angular 2.0 going to provide server-side rendering and isomorphic JavaScript features?

My impression is that this is a pretty relevant theme, and that folks at Ember are getting it mostly right:

http://emberjs.com/blog/2014/12/22/inside-fastboot-the-road-to-server-side-rendering.html

Thoughts? Cheers  :)

**Edit**
Meteor is also providing it: https://github.com/meteorhacks/fast-render

**Comment by ladyborg** [comment]
+1

**Comment by SekibOmazic** [comment]
@pensierinmusica Some thoughts: https://docs.google.com/document/d/1q6g9UlmEZDXgrkY88AJZ6MUrUxcnwhBGS0EXbVlYicY/edit

**Comment by finfort** [comment]
Short answer: Yes
https://www.youtube.com/watch?v=2fx4F0tdvN0

**Comment by mhevery** [comment]
We have not decided yet. 

Closing since it is not an issue (but a question)

**Comment by pensierinmusica** [comment]
Shall we keep it open as a feature request instead?

**Comment by tbosch** [comment]
We are just starting an initiative to support server sider rendering. See this [design doc](https://docs.google.com/document/d/1q6g9UlmEZDXgrkY88AJZ6MUrUxcnwhBGS0EXbVlYicY/edit) (still work in progress)

**Comment by pensierinmusica** [comment]
@tbosch, cool! Shall we label this issue as a "feature request" then?

**Comment by tbosch** [comment]
@pensierinmusica Could we leave this issue closed? I don't intend to put updates here, as we already committed to serverside rendering via the public available design doc...

**Comment by pensierinmusica** [comment]
@tbosch, yep makes sense  :)  I still feel that "feature request" is a bit of a more accurate label for these issues, rather than a generic "question"... but this is an internal evaluation to make I guess.
