### ISSUE TITLE
unexpected behavior of the html object for {{ }} interpolation in IE 10.

### ISSUE THREAD

**Issue by KiranKumar1986** [angular/angular#10549]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using the html object tag to show the pdf document in the webpage.
data attribute is provided with the angular 2 interpolation. This result in a dark page, in IE 10.
It is working as expected in Chrome.

docLocation:string='abc.pdf';

<object data={{docLocation}} type='application/pdf' width='100%' height="700"> <p>This browser does not support inline PDFs. Please download the PDF to view it: <a href={{docLocation}}>Download PDF</a></p> </object>

This is working if I use plain html as below without angular in IE 10.

<object data='abc.pdf' type='application/pdf' width='100%' height="700"> <p>This browser does not support inline PDFs. Please download the PDF to view it: <a href='abc.pdf'>Download PDF</a></p> </object>

**Expected/desired behavior**

**Reproduction of the problem**
Cannot be exactly reproduced in the plunker as it requires some pdf to be added in the punker folder which is not possible.
https://plnkr.co/edit/2grz5d?p=info   --- plain html with no interpolation
https://plnkr.co/edit/ysU4mn?p=info --- using angular 2 interpolation.

**What is the expected behavior?**

webpage should be similar with angular interpolation when it is with plain html.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [| IE 10| ] 
 
* **Language:**  [ | TypeScript 1.8.10 | ]

**Comment by KiranKumar1986** [comment]
Yes I tried it same result

**Comment by mlaval** [comment]
I couldn't reproduce the black page case with the information provided.

From my tests, your template should be something like this:
```
<!DOCTYPE html>
<html>
<body>
  <div>
    <object [attr.data]="docLocation" type='application/pdf' width='100%' height="700">
      <p>This browser does not support inline PDFs.
        Please download the PDF to view it: <a [href]="docLocation">Download PDF</a>.</p>
   </object>
</div>
</body>
</html>
```
This way, it behaves as the static examples from https://pdfobject.com/static.html (tested with RC5 in Chrome and IE10).

**Comment by KiranKumar1986** [comment]
Thank you, I missed the attribute binding when I tried. This   [attr.data]="docLocation" is working.
