### ISSUE TITLE
Hammer blocking scroll

### ISSUE THREAD

**Issue by danbucholtz** [angular/angular#10541]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If I listen for a hammer.js event on an element, it blocks vertical scrolling.

**Expected/desired behavior**

I would not expect scrolling to be blocked

**Reproduction of the problem**

1.  Create new project with `ng new my-project-of-doom`
2.  Update app.component.ts to look like this:

```
import { Component } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  template: `
    <div *ngFor="let item of items" (swipe)="test()">
      Item #{{item.id}}
    </div>
  `,
  styleUrls: ['app.component.css']
})
export class AppComponent {

  private items: any;

  constructor() {
    this.items = [];
    for ( let i = 0; i < 500; i++ ) {
      this.items.push( {id:i} );
    }
  }

  test(){
    alert('scrolling yo');
  }
}
```

3.  In the src/index.html file, add a script tag for Hammer.js before the end of the `<head></head>` block.

`<script src="http://hammerjs.github.io/dist/hammer.min.js"></script>`

4.  Execute `ng serve` and open the page on a mobile device (I tested on iPhone 6S)

5.  Attempt to scroll.  Observe being unable to do so.

6.  Open `./node_modules/@angular/platform-browser/src/dom/events/hammer_gestures.js`

7.  Go to line 32, 33.  Comment them out so the section looks like this:

```
var mc = new Hammer(element);
        //mc.get('pinch').set({ enable: true });
        //mc.get('rotate').set({ enable: true });
        for (var eventName in this.overrides) {
            mc.get(eventName).set(this.overrides[eventName]);
        }
        return mc;
```

8.  Modify `app.component.ts` so it re-compiles.

9.  Refresh page on mobile device, verify that scrolling can happen.

From the [Hammer.js docs](http://hammerjs.github.io/getting-started/):
```
By default it adds a set of tap, doubletap, press, horizontal pan and swipe, and the multi-touch pinch and rotate recognizers. The pinch and rotate recognizers are disabled by default because they would make the element blocking, but you can enable them by calling:
```

Please let me know what I can do to help resolve this issue.

Thanks,
Dan

**Comment by vicb** [comment]
Add a DI provider with an instance of `HammerGestureConfig` with whatever config you like.

--

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by danbucholtz** [comment]
That will fix the issue for us, but I'm not so sure closing immediately is the best issue because every app that uses Hammer and binds to a hammer event cannot scroll with the default config.

Thanks,
Dan

**Comment by vicb** [comment]
Could you please check the doc (angular.io) and if nothing is mentioned there then create a ticket on https://github.com/angular/angular.io ?

Thanks for your help

**Comment by MrCroft** [comment]
@danbucholtz  I've looked through the Hammerjs docs. Can't figure out what/how to pass in the HammerGestureConfig in order to make vertical scrolling work. Also searched google, no luck. Even placed a small bounty on [StackOverflow](http://stackoverflow.com/questions/41017202/vertical-scroll-is-not-working-with-hammerjs-and-angular2). Still nothing.

Could you share your HammerGestureConfig that made vertical scrolling work?
This is what I've tried (after seeing an example of providing `HammerGestureConfig`):
```
import { HAMMER_GESTURE_CONFIG, HammerGestureConfig } from '@angular/platform-browser';
// ...
export class MyHammerConfig extends HammerGestureConfig {
    overrides = <any> {
        'pinch': { enabled: false },
        'rotate': { enabled: false }
    }
}

@NgModule({
    declarations: [
        // ...
    ],
    imports: [
        // ...
    ],
    providers: [
        {
            provide: HAMMER_GESTURE_CONFIG,
            useClass: MyHammerConfig
        }
    ],
    // ...
})
```
Vertical scrolling still doesn't work.

**Comment by chrillewoodz** [comment]
Can someone share a working solution that allows vertical scrolling when using swipeleft and swiperight? I cannot for the life of me figure out what the config should look like. This is what I have now:

```
import {HammerGestureConfig, HAMMER_GESTURE_CONFIG} from '@angular/platform-browser';

export class CustomHammerConfig extends HammerGestureConfig {

  public overrides = <any> {
    swipe: {
      direction: 31
    }
  };
};
```
How do you set the `touchAction` property? The app just breaks if I throw it in the same scope as `swipe`.

**Comment by MrCroft** [comment]
@chrillewoodz This is what works for me, in my `app.module.ts`:

```
import { HammerGestureConfig, HAMMER_GESTURE_CONFIG } from '@angular/platform-browser';

export class MyHammerConfig extends HammerGestureConfig  {
    overrides = <any>{
        'pinch': { enable: false },
        'rotate': { enable: false }
    }
}
@NgModule({
// ... declarations, imports,
providers: [
        // ...
        {
            provide: HAMMER_GESTURE_CONFIG,
            useClass: MyHammerConfig
        }
    ],
bootstrap: [ AppComponent ]
})
export class AppModule {
}
```

**Comment by calbear47** [comment]
@chrillewoodz Did you figure this out? I'm experiencing the same dilemma and have yet to figure out a solution.

**Comment by CSchulz** [comment]
I got the best results with following HammerGestureConfig:

```
@Injectable()
export class HammerGestureConfig {
  events: string[] = [];

  overrides: {[key: string]: Object} = {};

  buildHammer(element: HTMLElement): HammerInstance {
    return new Hammer(element, {
      cssProps: Hammer.defaults.cssProps,
      recognizers: [
        [Hammer.Swipe],
        [Hammer.Tap],
      ],
    });
  }
}
```

or you build the Hammer instance manually in your class. Then you have better control about the recognizers which needs to be registered and there is no global configuration for all manager instances.

**Comment by artuska** [comment]
+1 for this issue — I cannot scroll mobile page if I start moving the finger on Hammer container — it just prevents the page from scrolling.

For example, here is my Hammer container:

```
<div class="instagram-carousel" (panstart)="panStart()" (panleft)="panLeft($event)" (panright)="panRight($event)" (panEnd)="panEnd()">
   ...
</div>
```

**Comment by perg** [comment]
does it help with
pan {direction: 6}

**Comment by artuska** [comment]
@perg where can i get all the codes? It works with any code — if i use `6` or any other dummy code it enables vertical pan and i can scroll the page... but it breaks horizontal pan — (panleft) event is called and there is some very strange deltaX and deltaY values...

**Comment by perg** [comment]
You find the codes in the documentation section API. 6 is horizontal.
I also noticed some strange deltaX values and ended up only start panning if the panstart event had an absolute value of velocityX greater than an absolute value of velocityY.

**Comment by artuska** [comment]
@perg thank you, i did the same and it works :)

**Comment by kamalakkanni** [comment]
can you provide working example.thanks

**Comment by elron** [comment]
This works for me


1. Add this to app.module.ts
```
export class BaluHammerConfig extends HammerGestureConfig {
  overrides = {
      pan: {
          direction: 6
      },
      pinch: {
          enable: false
      },
      rotate: {
          enable: false
      }
  };
}
```

2. instead of adding HammerGestureConfig to your providers, use this:
```
{
      provide: HAMMER_GESTURE_CONFIG,
      useClass: BaluHammerConfig
},
```

**Comment by gtsopour** [comment]
Hello @perg @artuska @elron ,
I have the following configuration, vertical scrolling is ok in swipable  but I cannot slide in my MatSlider Component anymore. Any idea?

```
export class HammerConfig extends HammerGestureConfig {
  overrides: any = <any>{
    'pinch': {enable: false},
    'rotate': {enable: false}
  };
}
```

**Comment by elron** [comment]
@gtsopour a quick guess would be to add 
```
      pan: {
          direction: 6
      },
```
Try this and let us know if it worked for you
