### ISSUE TITLE
Feature request: Angular2 for C#

### ISSUE THREAD

**Issue by KalpeshChheda** [angular/angular#10544]
Currently Angular2 app can be created using Dart, Typescript, and JavaScript. 
So Angular2 for c# can also be made?

Now Xamarin, .NET and C# (Roslyn) is open source. 
So Angular2 framework will be useful for developing mobile apps using C#.

Thanks & Regards,
Kalpesh

**Comment by zoechi** [comment]
Sounds like a community task.

**Comment by pkozlowski-opensource** [comment]
> So Angular2 for c# can also be made?

Sure - we would "just" need someone to step it and do it. Sounds like a community project.
