### ISSUE TITLE
Constructor function syntax not working for non-bootstrap components

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#10545]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**

When adding a component to the NgModule declaration array, if that component's constructor is a function (`constructor: function() {}`), the component is not added to the module.

Everything is fine if the array notation for the constructor is used though (`constructor: [function() {}]`).

**Expected/desired behavior**
Using a function as a constructor should be supported.

**Reproduction of the problem**
http://plnkr.co/edit/kuz9JlBLWUXaUDWtCn0s?p=preview (edited)
The only difference between `HeroComponent` and `VillainComponent` is how the constructors are declared, but `HeroComponent` does not show.

**What is the motivation / use case for changing the behavior?**
A function was a supported way of declaring a component constructor in RC4, and it still works for bootstrap components.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Chrome 52
 
* **Language:** ES5

**Comment by wardbell** [comment]
To be clear, this is for apps written in JS using the DSL not TS, right?

**Comment by filipesilva** [comment]
@wardbell correct.

**Comment by chuckjaz** [comment]
A temporary work-around for this is to give the constructor function a name. For example, changing `hero.component.js` to:

(function(app) {
  app.HeroComponent =
    ng.core.Component({
      selector: 'my-hero',
      template: 'Harry McHeroface'
    })
    .Class({
      constructor: function HeroComponent() {}
    });
})(window.app || (window.app = {}));
```

is a work-around for this issue. The name doesn't have to match the name of the component but the generated code is easier to grok if it is.
