### ISSUE TITLE
Component lifecycle needs documentation, interfaces.

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1055]
Right now I see `onDestroy` and `onChange`, but use of `onChange` within Angular's own code base seem to be more like `onAttached` from Angular 1.0 Dart. Is that the case? If so, can that be made more clear?

Additionally, it would be useful to provide interfaces/abstract classes (DestroyAware, AttachAware) to get compile-time checking if the lifecycle methods are missing.

**Comment by vsavkin** [comment]
I updated the docs here: https://github.com/angular/angular/pull/1130.

W cannot use interfaces until we switch to TypeScript, and we cannot abstract classes because you can have only one superclass. There are a lot of places in the code where we need to introduce interfaces.

**Comment by vsavkin** [comment]
Added a separate issue to add the missing interfaces https://github.com/angular/angular/issues/1132
