### ISSUE TITLE
Enable Loader when switching between one component

### ISSUE THREAD

**Issue by simoazzo** [angular/angular#10551]
Hi guys,

Can someone give me some insight about this? I am trying to show the loader when switching between components.

I am trying to enable it using the ngIf and set boolean value in the onDestroy event, but is it not showing properly.

Can someone help me where and how can show this loader when switching component?

Thanks in advance.

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr
