### ISSUE TITLE
option selected attribute not work on UI

### ISSUE THREAD

**Issue by xwendotnet** [angular/angular#10554]
I have a select element with expression and change event(not in form and haven't ngModel) , pug codes at below

```
select(#status, (change)="updateStatus(status.value)")
  option(
    *ngFor="let s of statuses;"
    [value]="s.statusValue"
    selected="{{s.statusValue === ticket?.status}}"
  )
    | {{s.name}}
```

With chrome,  generated HTML is 

```
<select _ngcontent-xeq-5=""><!--template bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object],[object Object],[object Object],[object Object]"
}--><option _ngcontent-xeq-5="" value="-1" ng-reflect-value="-1" ng-reflect-selected="true">Cancel</option>
	<option _ngcontent-xeq-5="" value="0" ng-reflect-value="0" ng-reflect-selected="false">Closed</option>
	<option _ngcontent-xeq-5="" value="1" ng-reflect-value="1" ng-reflect-selected="false">New</option>
	<option _ngcontent-xeq-5="" value="2" ng-reflect-value="2" ng-reflect-selected="false">In Process</option>
	<option _ngcontent-xeq-5="" value="3" ng-reflect-value="3" ng-reflect-selected="false">Resolved</option>
</select>
```

Look seems that first option attribute selected is true, and should selected in select element. But in the UI it not , the last option user chooses still be selected.

And I tried change to ` [selected]="s.statusValue === ticket?.status",` still not work.

**Comment by ericmartinezr** [comment]
That is the expected behavior. The option tag is looking for the presence of the selected attribute, it isn't looking for the value you pass. You have to add the attribute to select it or remove it completely evaluating it to null.

Reference
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option

Also see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by xwendotnet** [comment]
Thank you @ericmartinezr. I change expression to  `selected="{{s.statusValue === ticket?.status ? true : null}}`. It works.
