### ISSUE TITLE
Two way binding fails silently when ([foo]) is used instead of [(foo)]

### ISSUE THREAD

**Issue by wolever** [angular/angular#10559]
**I'm submitting a ...** 
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Attempting to use two-way binding with `… ([foo])=…` instead of `… [(foo)]=… ` fails silently.

**Expected/desired behavior**

It would be fantastic if there was a warning if `([…])` was used.

* **Angular version:** 2.0.0-rc.4

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/10275
