### ISSUE TITLE
EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot set property of null

### ISSUE THREAD

**Issue by iamaritraganguly** [angular/angular#10553]
Hello, 

I have been practicing with Angular2 from the quickstart guide. Came across this problem. Please help me out.

The line : this.heroService.getHeroes().then(heroes => this.heroes = heroes); works fine. 
But the part marked in white throws an error. 

Please tell me whats wrong in the part marked in white.

![angularjs2-1](https://cloud.githubusercontent.com/assets/20454269/17462257/1e8de6f4-5cc5-11e6-8c12-06091a1ef6ce.png)
![angularjs2](https://cloud.githubusercontent.com/assets/20454269/17462258/1e916266-5cc5-11e6-97eb-61f8518ece13.png)

**Comment by qdouble** [comment]
You probably just need to use fat arrow function 
```
this.heroService.getHeroes().then((heroes) => { this heroes= heroes ])
```

**Comment by vicb** [comment]
wring repo, please reopen on https://github.com/angular/angular.io/issues

**Comment by viratpatil** [comment]
@iamaritraganguly : How did you resolve it ? can you write it here?
