### ISSUE TITLE
Router.navigate fails with unhelpful error if `undefined` is part of the path

### ISSUE THREAD

**Issue by wolever** [angular/angular#10560]
**I'm submitting a ...**

```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

An unhelpful error is thrown when `undefined` appears in a `Router.navigate([…])` path. For example, here's what happens when I call `this.router.navigate(['/foo/, undefined])`:

![example-stack-trace](https://cloud.githubusercontent.com/assets/59575/17467936/f8268b98-5cf0-11e6-8b09-c8cce83204d1.png)

The line number referenced - `SessionComponent - inline template 26` - is `<button (click)="nextStep()" />`.

**Expected/desired behavior**

It would be fantastic if the error was something along the lines of `the requested path - ['/foo', undefined] - contains an undefined component`.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4

**Comment by vsavkin** [comment]
Pushing it back until the final is out.

Just a note that the behavior changed in RC1. Instead of throwing an error, the router now generates this URL: `/foo/undefined`.
