### ISSUE TITLE
RC 4, Router. QueryParams change is triggered before component is destroyed.

### ISSUE THREAD

**Issue by kamarouski** [angular/angular#10565]
**I'm submitting a **  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Let's say we have a component that is subscribed for query params change via during ngOnInit

```
private sub: Subscription;

constructor(private router: Router) {}

ngOnInit() {
   this.sub = this.router.routerState.queryParams.subscribe(...);
}
```

The subscription is unsubscribed in ngOnDestoy. 

```
ngOnDestroy() {
  this.sub.subsubscribe();
}
```

The component is rendered for specific route only.

Problem: When route is changed queryParams subscription is triggered before component is destroyed. This create a problem as it causes unwanted reinitialization of component that is about to be destroyed and breaks application in our case. (It heavily depends on query params due to compatibility reasons).

**Expected/desired behavior**

The component is destroyed before queryParams changed event. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

* **Router Version:** 3.0.0-beta.2
 
* **Browser:** all
 
* **Language:**  TypeScript 1.8.10

**Comment by brandonroberts** [comment]
This is already fixed in master and will go out with the next release.

**Comment by pkozlowski-opensource** [comment]
Thnx @brandonroberts !
