### ISSUE TITLE
FormControl.setValidators...would like an addValidators

### ISSUE THREAD

**Issue by melegant** [angular/angular#10567]
**I'm submitting a ...**  (check one with "x")

```
[x ] feature request

**Current behavior**
When creating a FormControl via TypeScript (following a model driven approach) we have our validations coming from a 'Questions' model (using the Angular2 dynamic form cookbook as an example). We use the setValidators method however we have 7 or 8 validators we apply but not for each question. 

As an example:

   new TextboxQuestion({
        key: 'phone',
        label: 'Phone',
        value: '',
        required: true,
        minLength: 9,
        maxLength: 12,
        order: 1
      }),

   new TextboxQuestion({
        key: 'email',
        label: 'Email',
        value: '',
        required: true,
        minLength: 0,
        maxLength: 0,
        order: 1
      }),

Using setValidators though...we would have to start to write a pretty complicated if statement to look for when we want to apply certain validators since setValidators does not add, just replaces. The below code will only set the last validator.

toFormGroup(questions: QuestionBase<any>[]) {
    let group: any = {};

    questions.forEach(question => {
      group[question.key] = new FormControl(question.value);

      if (question.required)
        (<FormControl>group[question.key]).setValidators([
          Validators.required
        ]);
      if (question.minLength > 0)
        (<FormControl>group[question.key]).setValidators([
          Validators.minLength(question.minLength)
        ]);
      if (question.maxLength > 0)
        (<FormControl>group[question.key]).setValidators([
          Validators.maxLength(question.maxLength)
        ]);
    });

**What is the motivation / use case for changing the behavior?**

It would be great if you had an ADD like 

toFormGroup(questions: QuestionBase<any>[]) {
    let group: any = {};

    questions.forEach(question => {
      group[question.key] = new FormControl(question.value);

      if (question.required)
        (<FormControl>group[question.key]).**addValidators**([
          Validators.required
        ]);
      if (question.minLength > 0)
        (<FormControl>group[question.key]).**addValidators**([
          Validators.minLength(question.minLength)
        ]);
      if (question.maxLength > 0)
        (<FormControl>group[question.key]).**addValidators**([
          Validators.maxLength(question.maxLength)
        ]);
    });


* **Angular version:** 2.0.0-rc.4

* **Browser:** [all ]

* **Language:** [all] 
```

**Comment by michaelsanford** [comment]
I had a similar need (_n_ password complexity rules that needed to be retrieved from a server). I implemented this manually fairly easily. Since `FormControl`s take an array of validators, you can simply accumulate your validators into an array using `.push(ValidatorFn)` (where you have `**addValidator**`) and then pass that array to the `FormGroup` builder.

As I had to retrieve a list from a server, I also had to promisify the validator accumulation > form initialization > template activation steps.

⚠️ I will add that I had to prevent the form from being built before everything was ready by adding `*ngIf="ready"` to the `<form />`'s template, and then setting `ready=true` that at the end of the promise chain. Failing to do that got me "FormBuilder expects a FormGroup instance, please pass one in" and the hard-to-diagnose double-calling `ngOnInit()` bug.

**Comment by JaroslavSoldat** [comment]
I tried to extend the FormControl class and add the addValidators() method. It's sketch, but functional. 

```
class MyFormControl extends FormControl {

  private validators: ValidatorFn[] = [];

  constructor()...

  setValidators(val: ValidatorFn | ValidatorFn[] | null) {
    this.validators = normalizeValidators(val);
    super.setValidators(this.validators);
  }

  addValidators(val: ValidatorFn | ValidatorFn[] | null) {
    this.setValidators(
      // merge current and added validators
      [...this.validators, ...normalizeValidators(val)]
      // remove duplicity
      .filter((v, i, a) => a.indexOf(v) === i)
    );
  }

}

function normalizeValidators(val: ValidatorFn | ValidatorFn[] | null): ValidatorFn[] {
  if (val === null) return [];
  if (Array.isArray(val)) return val;
  return [val];
}

```
See https://stackblitz.com/edit/angular-my-forms?file=src%2Fmy-forms%2Fmy-form-control.ts
(This code also expands dirty value checking to detect the return to the pristine value.)

**Comment by djleonskennedy** [comment]
Angular team, this issue opened in  Aug 8, 2016, what news guys ?
It's difficult for google team add 3 methods (add, remove, replace) to class ?

**Comment by jsonod** [comment]
This would be useful.

**Comment by Ansrala** [comment]
+1

**Comment by shubhamyugtia001** [comment]
how to add validator to a form when i get the value in a for loop and then when i am setting the value with setvalidator in for loop.

can not set the particular value for particular object.

eg. array =[
{a1:10, a2:20}, {b1:10,b2:""}
]
now how to set validator for particular object in for loop

Thank you in advance  _/\_

**Comment by crikk** [comment]
My use case is that I have a standardized <app-input> that takes care of consistent formatting and accessibility concerns.  There are certain characters that we want to prevent from reaching our database (legacy requirement) so I want to add a validation to all instances of this component.  However, depending on the usage of the component, I may also have other validations (required field, minimum length) that will be custom to the individual usage.
So as a result, the validation rules are, ideally, added in two separate places.  (1) in the component and (2) when it's added to the form.  I was trying to use .addValidators() to handle case (1) but that just overwrites everything added by case (2).

My workaround: If you use a directive to add a validator, it appears that the directive is appended to the list.  I was able to use [this sample](https://angular.io/api/forms/NG_VALIDATORS) to create a directive for my case (1) and it fires in conjunction with the validators that were added to the form.

This may not work for everyone, but I thought I'd post it as a potential workaround for the issue of not being able to append validators in case it helps anyone.
Note: you can even pass an input to the validator if you need to via the usual directive name binding.  In my case, I did not want the directive to apply if the <input> was a type="password".  So in my code, I have: <input [type]="ctrlType" [appBlockCharsVal]="ctrlType ==='password'">

It would still be nice to have an appendValidator(...) method on the FormControl, but this was an only-slightly-kludgy workaround.

**Comment by mlc-mlapis** [comment]
... why ` addValidators` or `removeValidators`  is not actually here with the current state https://github.com/angular/angular/issues/13461#issuecomment-502674629

**Comment by mindaugas16** [comment]
Here is temporary solution using prototypes:
`import { AbstractControl, ValidatorFn } from '@angular/forms';

declare module '@angular/forms' {
  interface AbstractControl {
    addValidators(validators: ValidatorFn[]): void;
  }
}

AbstractControl.prototype.addValidators = function(this: AbstractControl, validators: ValidatorFn[]) {
  if (!validators || !validators.length) {
    return;
  }

  this.setValidators(this.validator ? [this.validator, ...validators] : validators);
};`

**Comment by lhenriquegomescamilo** [comment]
I created this PR https://github.com/angular/angular/pull/37263, maybe is useful 🙂

**Comment by AndrewKushnir** [comment]
Closing this issue in favor of #13461 (to support `getValidators` API), see more info in https://github.com/angular/angular/pull/37263#issuecomment-723333060. Thank you.
