### ISSUE TITLE
HashLocationStrategy back/forward doesn't work on IE Mobile 11

### ISSUE THREAD

**Issue by michael42** [angular/angular#10564]
**I'm submitting a ...**

```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
- Back navigation with HashLocationStrategy on IE Mobile 11 is broken, it jumps to the default route, and doesn't update the address bar.

**Reproduction of the problem**
- On a Windows Phone 8.1 device, use IE Mobile 11 to open http://plnkr.co/edit/MsEeN4HYcPa8ueg12X1m?p=preview (Launch preview in seperate window)
- Navigate to route 2 (#/route2), then to route 3 (#/route3)
- Press the OS/browser back button once
- You are now redirected directly to route 1, skipping route 2, but the address bar still shows #/route3

**Expected/desired behavior**
- Route 2 should have been loaded (and #/route2) shown in the address bar, as it happens on the other platforms

Back-porting #10096 (which fixed #9497) only fixes the issue on Desktop IE11, but not on mobile. 

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** IE Mobile 11

Using PathLocationStrategy would also avoid the issue, but it isn't an option for our project (ms-appx:/// URL without an HTTP server).

**Comment by michael42** [comment]
Apparently it's an IE Mobile 11 bug, as it doesn't properly handle pushState calls when only the hash changes:

    history.pushState(null, '', '#route1');
    history.pushState(null, '', '#route2');
    history.pushState(null, '', '#route3');
    history.back();
    console.log(location.hash); // -> ''

Is there a reason why the HashLocationStrategy uses HTML5 History API, when it only needs the change location.hash? I'll check how an alternative implementation using location.hash and location.replace fares...

**Comment by atscott** [comment]
Hi, is someone able to verify that this is still an issue with IE Mobile 11?

**Comment by michael42** [comment]
I no longer have access to Windows Phone devices. Since Windows Phone is long dead, it's probably pointless to fix it now, anyway.
