### ISSUE TITLE
unable to add router with @angular RC4

### ISSUE THREAD

**Issue by DeepakSinghIT** [angular/angular#10568]
**I have a component with Router dependency and i am trying to test with Mocha chai  sinon as test bundle**

	constructor(private ss:Service,private router: Router) {

```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
when ever i am adding Router in beforeEach its giving exceptions

 beforeEach(() => {
	    addProviders([ROUTER_PROVIDERS,ApplicationRef,Service,Component,HTTP_PROVIDERS]);
	  });

    EXCEPTION: Error during instantiation of Token RouterPrimaryComponent! (AppComponent -> Router -> RouteRegistry -> Token RouterPrimaryComponent).
RIGINAL EXCEPTION: unimplemented
RIGINAL STACKTRACE:
rror: unimplemented
   at new BaseException (D:\bnsf-code\Grails_New\SeniorityRosters\grails-app\assets\angular\node_modules\@angular\core\src\facade\exceptions.js:27:23)

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by vsavkin** [comment]
You can look at this spec as an example of how you can use the router in tests https://github.com/angular/angular/blob/master/modules/@angular/router/test/router.spec.ts
