### ISSUE TITLE
Router: lazy loaded module doesn't honor component's provider list

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10577]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```
A component in a lazy loaded module that has its own provider should have that provider registered in its component injector.  The provided service should be available to all children of that component.

That's how it works for eagerly loaded components. It isn't working when the component is lazy loaded.

**The Scenario:**

A router route lazy loads the Hero Module. That module has a single top component, `HeroComponent` which is the host for child routes to `HeroList` and `HeroDetail` components.

Those two components depend on a `HeroService` that belongs to the Hero management feature area.

**Preferred approach:**

The `HeroComponent` , which has a `<router-outlet>` provides the `HeroService` for itself and the child components that the router will load into that outlet, `HeroList` and `HeroDetail`.

**Current behavior**

The application throws an error in `HeroList` saying that it can't find the `HeroService` provider.  

**Workaround**

Add the provider to the lazy loaded module's `providers`.  

This should not be necessary and prevents the kind of service encapsulation that only a component can offer.

**Expected/desired behavior**

It should find it because that service is provided in its parent `HeroComponent`.

**Reproduction of the problem**

http://plnkr.co/edit/KCEYVGgcm6fD1oQodNKM?p=preview

The plunker has instructions for revealing the bug.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 candidate, 8 August 2016
 
* **Browser:** all
 
* **Language:**  all

**Comment by kylecordes** [comment]
Ward, reading your description here and also reading the rc4->5 migration instructions, the following strikes me. Pipes and directives usage metadata have been moved _out_ of each individual component _up_ to the module level. Your message here suggests the intention is for providers to remain at the specific component level. I'm sure with a few minutes thought I could come up with a good reason why these different types of formerly-component-level settings get different treatment in the new NgModule regime; but perhaps someone more right in the middle of things could add such an explanation to the documentation somewhere?

**Comment by johnpapa** [comment]
I can confirm I see the same mis-behavior.

**Comment by gerhard17** [comment]
I have also a serious problem with this design.

In an enterprise app, which has grown large, the lazy loaded modules are very wellcomed! Also the fact that components in the lazy modules can use their own 'global' providers, defined in the lazy module, is good! 

But when a component is refactored to the lazy module, suddenly it can't get the providers contained in the injector of it's parent component (a component, which is defined in the app module). So working code suddenly breaks when using lazy loaded modules.

Question: Wouldn't it possible to give every router component in a lazy loaded module an injector with 2 parents? First try the lazy module injector (like now) and then the injector inherited by the parent component (new)? This wouldn't break today's running code in a serious way. But we would gain symmetry between lazy node and eagerly loaded components.

This would help me and I think others a lot! 
Thanks!

**Comment by johnpapa** [comment]
This is where the idea of shared module and core module comes into play (as seen in the ngmodule documentation ). When we want services to be shared through the app we use core module. Take a look at that design and see if that works for you.

**Comment by gerhard17** [comment]
Thank you for your response!

My problem is not related to share a kind of data service through the application. This kind of services are already working for me in conjunction with ngModules.

I have the concrete problem of finding a special marked component in the component tree. In my case this component acts as a scroll container control (CompA) to be used with a sticky header table (CompB). The problem is that CompA can sit somewhere in the component tree, even multiple times. And CompB has to find it's nearest CompA, even across lazy loaded module borders.

At the moment I'm using some kind of hack and I'm traversing the real DOM tree. But this has some other issues, related to local DOM trees, which are not bound the the main DOM. (Caused by combination of ngIf with ng-content)

**Comment by gerhard17** [comment]
Is it possible to reopen this issue?

**Comment by gerhard17** [comment]
My Problem is already fixed in angular 2.2.0
See: #12344 router: provider not found when using lazy load mode and provide in component

Thanks to the ng2 team! :-)

Sorry for the noise, I produced.
