### ISSUE TITLE
Interpolated values not working on the datetime attribute of date element

### ISSUE THREAD

**Issue by kaeku** [angular/angular#10571]
**I'm submitting a ...**
```
[x] bug report
[x] feature request
```

**Current behavior**

The attribute `datetime` of the HTML5 `<time>` element can't be filled by an interpolated value. 

**Expected/desired behavior**

I feel like the default curly braces should work here, since it isn't a property on the native element, however this value will need to be filled by a binding for most use-cases. Not sure if this expected behaviour though.

**Reproduction of the problem**

http://plnkr.co/edit/bZD29IUZbygRFlOkj9Bu

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by pkozlowski-opensource** [comment]
The error you are getting is correct - there is no `datetime` _property_, only an attribute. Check the fix here: http://plnkr.co/edit/Sk1D0LLNWKs0jBLsS3Jl?p=preview

Ref.:https://developer.mozilla.org/en/docs/Web/HTML/Element/time

**Comment by kaeku** [comment]
Thanks! Totally forgot about the `attr` binding.
