### ISSUE TITLE
Class bindings shouldn't camelCase normalize CSS class names.

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1057]
If I have a binding:
```html
<div [class.md-radio-checked]="isChecked">...</div>
```

Then the class name added to the element should be `md-radio-checked`. Currently, it is `mdRadioChecked`.

**Comment by pkozlowski-opensource** [comment]
Oh, will fix it asap...

**Comment by pkozlowski-opensource** [comment]
@jelbourn here it is: #1059
