### ISSUE TITLE
Router: Expose errors as events instead of failed promises

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#10585]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If the router fails to match a URL, it fails with a message logged to the console. This also happens when the `canLoad` guard fails.

**Expected/desired behavior**

Emit a `NavigationError` but not a failed promise so these events can be captured and handled without console error messages.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 

cc: @vsavkin

**Comment by wardbell** [comment]
EXACTLY! It shouldn't behave differently than `canActivate` in this respect. Just stay put unless the function re-navigates.

**Comment by wardbell** [comment]
To be clear, this is a bug. Staying put without further effort is the correct behavior.

The `canLoad` should behave the same way as `canActivate`. It should not throw a promise error.

**Comment by johnpapa** [comment]
curious how we should use CanLoad .... very interested in where this lands

**Comment by vsavkin** [comment]
1. `canLoad` should behave the same as `canActivate`.
2. The inability to match a URL is treated differently because almost always this is due to a bug. We can reevaluate it.

**Comment by brandonroberts** [comment]
I agree with the assumption on #2.  If all the errors are being tracked as router events, then the user could handle a match not found on initial load for example.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/11001
