### ISSUE TITLE
upgradeAdapter.upgradeNg1Component $element

### ISSUE THREAD

**Issue by AlexKhymenko** [angular/angular#10597]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When u try to upgrade directive that uses $element service and use it in Angular2 component the element will have NO children nodes.
**Expected/desired behavior**
When u try to upgrade component that uses $element service the element will have children nodes.

**What is the expected behavior?**
When u try to upgrade component that uses $element service the element will have children nodes.

**What is the motivation / use case for changing the behavior?**
To be available to update directives that uses $element service and use them in hybrid application

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all ] 
 
* **Language:** [all | TypeScript 1.8 ]

**Comment by guojenman** [comment]
@AlexKhymenko You have to wait after the $onInit is called on your controller. Trying to access $element before that, will result in what you're seeing

```
function MyController($element) {
  console.log($element.children()) // no children here
  this.$onInit = function() {
    console.log($element.children()) // here they are
  }
}
```

**Comment by AlexKhymenko** [comment]
Thank you will try!!!

**Comment by dbpieter** [comment]
@AlexKhymenko @guojenman 

This does not work and it appears to be a bug when upgrading an ng1 component.

Whereas a pure ng1 component has $element available in $onInit. An upgraded ng1 component does not have $element available in $onInit until after sometime.

Logged #13912
