### ISSUE TITLE
Provide XSRFStrategy with randomly generated uuid

### ISSUE THREAD

**Issue by bzums** [angular/angular#10593]
**I'm submitting a ...**

```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently we have https://angular.io/docs/ts/latest/api/http/index/CookieXSRFStrategy-class.html which reads the value from a cookie. However, the cookie must be set before.

**Expected/desired behavior**
Why not providing an additional UUIDCookieXSRFStrategy which also sets the cookie to a randomly generated uuid?

**What is the motivation / use case for changing the behavior?**
I think this is the desired behaviour in almost all cases.

**Comment by alxhub** [comment]
The server needs to provide the XSRF token that is sent back with every request - otherwise there's no way the server can validate requests and the token is useless.

See: https://en.wikipedia.org/wiki/Cross-site_request_forgery#Prevention

**Comment by bzums** [comment]
@alxhub I think it is not necessary to generate the XSRF token on server-side when using a Double Submit Cookie, see: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Double_Submit_Cookie
