### ISSUE TITLE
Router `pathMatch` doesn't seem to work.

### ISSUE THREAD

**Issue by colinfang** [angular/angular#10592]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
path: 'a'
pathMatch: 'prefix'

doesn't match url 'aa' in

      <a routerLink="/aa">A</a>
      <a routerLink="/bb">B</a>
```
**Expected/desired behavior**

**Reproduction of the problem**
http://plnkr.co/edit/Txr0WcfsYzikGIciNjFt?p=preview

**What is the expected behavior?**

* **Angular version:** 2.0.0-rc.4
* **router version:** @3.0.0-beta.2
 
* **Browser:** [Chrome | Firefox] 
 
* **Language:** TypeScript

**Comment by zoechi** [comment]
Have you tried one of the support channels first?
[CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by vsavkin** [comment]
Behaves as intended. 

Please read this post to learn more about how the router does matching:
http://vsavkin.tumblr.com/post/146722301646/angular-router-empty-paths-componentless-routes

**Comment by rmnoon** [comment]
I've read the blog post a few times and I'm still struggling to understand why this plunk doesn't work:

http://plnkr.co/edit/wtMOqn4rmTlsV1UJyR0D?p=preview

I've been playing with it for a while now and I've never been able to get `pathMatch: 'prefix'` to work.  In that plunk shouldn't the "C" button match the route with `path: ''` and `pathMatch: 'prefix'` (to say nothing of the A button).

Happy to create a new issue: really loving Angular 2 so far!

**Comment by SmaugTheGreat** [comment]
@vsavkin that article doesn't give any reasons to use pathMatch: "prefix" whatsoever. In fact, in any combination that I tried (and that's a lot of combinations), "prefix" had the exact same result as "full". The documentation (and the article you linked) says that "prefix" could have unwanted side-effects, so I don't see any reason to ever use pathMatch: "prefix"; especially having it as the default.

If you want to match by a prefix you can just use the wildcard anyway (path: "**" matches all paths). The documentation doesn't give any valid reason to use "prefix" and it contains the false-information that path: "" would match any route which is obviously incorrect.

Either pathMatch is unnecessary and bugged, or the documentation is terrible at explaining it.

**Comment by SmaugTheGreat** [comment]
After a little more testing and reading I found out the only subtle difference:

`redirectTo: "main"` ignores pathMatch (prefix), `redirectTo: "/main"` works as described (i.e. as wildcard with prefix).

Redirects on all paths:

    {
        path: '',
        redirectTo: '/main',
        pathMatch: 'prefix'
    },
    {
        path: "main",
        component: OtherComponent
    }

Redirects only the / path:

    {
        path: '',
        redirectTo: 'main',
        pathMatch: 'prefix'
    },
    {
        path: "main",
        component: OtherComponent
    }

The article above routing uses `redirectTo: 'teams'` (the relative path), so it is incorrect on its assumption that pathMatch applies.

However, this looks more like a bug.

**Comment by yaroslavya** [comment]
Did anyone managed to make it work or know why this is the expected behavior?
Im trying with the following configuration:
{ path: "abou", redirectTo: "/home", pathMatch: "prefix" },
{ path: "home", component: HomeComponent },
{ path: "about", component: HomeComponent }
actually no matter if I put the first pathMatch as prefix or as full it behaves the same and does the following:
if I try "abou" - Im redirected to the home,
if I try "about", which starts with "abou" it goes to about page. So the behavior of both pathMatch:"prefix" and pathMatch:"full" is same. Interestingly it works with the empty path. Is it really as intended? Im asking as I found it extremely confusing while trying to make it work.

**Comment by canda** [comment]
@rmnoon did you figured out why your plunker links didn't work?

**Comment by rmnoon** [comment]
Nope!
