### ISSUE TITLE
Angular 2 forms Library version Documentation Issue?

### ISSUE THREAD

**Issue by robinkedia** [angular/angular#10608]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html states use npm install @angular/forms@1.0.0-rc.1 while quick start link https://angular.io/docs/ts/latest/quickstart.html says "@angular/forms": "0.3.0",

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kara** [comment]
@robinkedia  Yes, it should be forms version 0.3.0. Thanks for reporting!  I'm closing this because it's a docs issue (and should be in the angular.io repo), but I'll make sure the right people know. Thanks!

**Comment by wardbell** [comment]
We are ON it! Thanks.

**Comment by wardbell** [comment]
Fix published. Please close
