### ISSUE TITLE
Pristine status isn't altered until after statusChanges observer fires

### ISSUE THREAD

**Issue by xealot** [angular/angular#10606]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**

[`AbstractControl.pristine`](https://angular.io/docs/ts/latest/api/common/index/AbstractControl-class.html#!#pristine-anchor) is not updated prior to the [`AbstractControl.statusChanges`](https://angular.io/docs/ts/latest/api/common/index/AbstractControl-class.html#!#statusChanges-anchor) observer handler.

**Expected/desired behavior**

`AbstractControl.pristine` should be current before the `statusChanges` observer emits any values.

**Reproduction of the problem**
http://plnkr.co/edit/6xQYOKLxN0pDwpdauZpp

**What is the motivation / use case for changing the behavior?**
Within the `statusChanges` handler sometimes it's necessary to check pristine to know whether or not to display something on the page. Right now we have to defer this behavior using a `setTimeout` because the pristine value can't be trusted.

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.4
* **Browser:** all
* **Language:** all

**Comment by kara** [comment]
@xealot Thanks for reporting. This was an issue in RC.4, but it was fixed a few weeks ago. It's resolved in RC.5 / forms 0.3.0.

See updated plunker: http://plnkr.co/edit/1SkB5aXiRnBlzHExj80q?p=preview

**Comment by xealot** [comment]
And even updated the plunker! Fantastic.
