### ISSUE TITLE
Getting Unhandled Promise rejection after migrating from rc4 to rc5.

### ISSUE THREAD

**Issue by 5amfung** [angular/angular#10617]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Following the [migration](https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html), I ended up getting this:

Using angular-cli beta 10, I would get this error.
```
zone.js:461 Unhandled Promise rejection: Error: Unexpected value '[object Object]' imported by the module 'AppModule'
	    at new BaseException (http://localhost:4200/vendor/@angular/compiler/src/facade/exceptions.js:27:23)
	    at eval (http://localhost:4200/vendor/@angular/compiler/src/metadata_resolver.js:255:31)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor/@angular/compiler/src/metadata_resolver.js:239:44)
	    at RuntimeCompiler._compileComponents (http://localhost:4200/vendor/@angular/compiler/src/runtime_compiler.js:150:47)
	    at RuntimeCompiler._compileModuleAndComponents (http://localhost:4200/vendor/@angular/compiler/src/runtime_compiler.js:72:37)
	    at RuntimeCompiler.compileModuleAsync (http://localhost:4200/vendor/@angular/compiler/src/runtime_compiler.js:49:21)
	    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor/@angular/core/src/application_ref.js:368:25)
	    at PlatformRef_.bootstrapModule (http://localhost:4200/vendor/@angular/core/src/application_ref.js:361:21)
	    at Object.eval (http://localhost:4200/main.js:9:53)
	Evaluating http://localhost:4200/main.js
	Error loading http://localhost:4200/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Unexpected value '[object Object]' imported by the module 'AppModule'(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Error: Error: Unexpected value '[object Object]' imported by the module 'AppModule'(…)consoleError @ zone.js:463_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
```

Using angular-cli@webpack, I would get this error.
![image](https://cloud.githubusercontent.com/assets/371691/17537907/451edd46-5e55-11e6-85d9-d7e9a95aba6a.png)

**Expected/desired behavior**

The app should launch.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Plnkr doesn't seem to have rc5 yet.

So here's my `main.ts`:
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { environment } from './app';
import { AppModule } from './app/app.module';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule);
```

Here's the `app.component.ts`:
```
import { NgModule } from '@angular/core';
import { BrowserModule, Title } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { AppComponent } from './app.component';

@NgModule({
    declarations: [
        AppComponent
    ],
    bootstrap: [AppComponent],
    imports: [
        BrowserModule,
        FormsModule,
        Title,
    ],
})
export class AppModule { }

```

**What is the expected behavior?**

The app should launch

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5

* ** Angular cli version: ** 1.0.0-beta.10
 
* **Browser:** Version 53.0.2785.46 beta (64-bit)
 
* **Language:** TypeScript

**Comment by brandonroberts** [comment]
Services go in `providers` and not  `imports`. Only modules go in `imports`. Directives, components and pipes go in `declarations`

**Comment by 5amfung** [comment]
@brandonroberts Ah, thanks a lot.  Rookie mistakes of mine.

**Comment by MurhafSousli** [comment]
@brandonroberts where should we export  Interfaces and Modules ?

**Comment by brandonroberts** [comment]
@MurhafSousli modules are exported through the `exports` array. I don't understand your question about interfaces as it doesn't pertain to angular modules.

**Comment by MurhafSousli** [comment]
@bradlygreen never mind, I thought classes and interface should be exported into `ngModule`

**Comment by kosiakMD** [comment]
Hello!
I tried
`import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent }  from './app.component';

import { APP_ROUTER_PROVIDERS }        from './app.routes';

@NgModule({
	imports:      [ BrowserModule, APP_ROUTER_PROVIDERS ],
	declarations: [ AppComponent ],
	bootstrap:    [ AppComponent ]
})
export class AppModule { }`

and "main.ts"
`import { bootstrap } from '@angular/platform-browser-dynamic';
import { disableDeprecatedForms, provideForms } from '@angular/forms';

import { AppComponent } from './app.component';
import { APP_ROUTER_PROVIDERS } from './app.routes';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
platformBrowserDynamic().bootstrapModule(AppModule);

bootstrap(AppModule, [
	disableDeprecatedForms(),
	provideForms(),
	APP_ROUTER_PROVIDERS,
]);`

and have
`Unexpected value '[object Object]' imported by the module 'AppModule'`

**Comment by pkozlowski-opensource** [comment]
It is because you've got `APP_ROUTER_PROVIDERS` in the module's `imports`. Imports can only have other modules. Please:
* import router module instead
* don't comment on closed issues
* ask support questions using one of the support channels: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by kamalkech** [comment]
How to fixe that in Unigular Universal Cli ?
