### ISSUE TITLE
private function and private let exported as part of public API - broken links in docs

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#10615]
These show up in the API docs because they're exported, but are clearly private (and because they're private, the page 404s). 

- _createDefaultCookieXSRFStrategy was exported by @robwormald in 422effdd18487317ab4fa264a63ccf1868a4afe5 (see https://angular.io/docs/ts/latest/api/#!?apiFilter=defaultcookiexsrfstr )
- _WORKER_UI_PLATFORM_PROVIDERS was exported by @tbosch in 46b212706b9162c22fb1523032d7e37c9155015a (see https://angular.io/docs/ts/latest/api/#!?apiFilter=worker_ui_platform_providers)

**Comment by alxhub** [comment]
Both symbols are now no longer exported.
