### ISSUE TITLE
Add multiple left-hand assignment 

### ISSUE THREAD

**Issue by ibraback** [angular/angular#10611]
Hello, I noticed that **multiple left-hand assignments** can't work inside *ngFor loop, but if it's included that could be extremly helpful, here is a code sample (of course it dosen't work) :
` *ngFor="let note of notes; let i = note.ind = index;" `

**Comment by vicb** [comment]
`"let note of notes; let i = note.ind = index;"` syntax has to be simple for tools to support it.
