### ISSUE TITLE
[RC5]: possible misspelling in compiler comments

### ISSUE THREAD

**Issue by codespicelabs** [angular/angular#10619]
*I'm submitting a ...possible misspelling*
```
[x] bug report
[ ] feature request
```

AFAIK just misspelling in comments, but really valuable for that context
_@angular/core/src/linker/compiler.ts_, 86 & 94 lines: 

**Current behavior**
    Same as {@link compileModuleSync} **p**ut also creates ComponentFactories for all components.

**Expected/desired behavior**
    Same as {@link compileModuleSync} **b**ut also creates ComponentFactories for all components.

* **Angular version:** 2.0.0-rc.5

**Comment by pkozlowski-opensource** [comment]
Already fixed via dd03bf12e1c035597d2fab252e393846efca5ea1
