### ISSUE TITLE
Can't resolve all parameters for DecoratorFactory

### ISSUE THREAD

**Issue by sqlsolver** [angular/angular#10623]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I  bookmarking app at [bookmarksolver.com](http://bookmarksolver.com). I'm currently trying to create a service that pulls data from a JSON file for a view module to consumes and display. The app continually fails to load with the error: **'Can’t resolve all parameters for DecoratorFactory’**
[bookmarksolver.com-1470689932405.zip](https://github.com/angular/angular/files/410179/bookmarksolver.com-1470689932405.zip)
     After looking at decorator.ts it seems like what DecoratorFactory is doing is to create the object to be injected? I created an interface and named it in the Observable, when the app kept failing on this error I changed ‘bookmarks’ to just an Object[] and used *any* in the Observable, but the error persisted. 

**Expected/desired behavior**
For the JSON object to be loaded and displayed by the template.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

The public repo is at [github - bookmarksolver](https://github.com/sqlsolver/bookmarksolver) and also live at [bookmarksolver.com](http://bookmarksolver.com).

**What is the expected behavior?**
That the app will load.

**What is the motivation / use case for changing the behavior?**
Fix an apparent defect.

**Please tell us about your environment:**
Developing in VS2015 with .NET solution artifacts stripped out of project. Push to github from there and then pull to web host.

* **Angular version:** 2.0.0-rc.4
 2.0.0-rc.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 Chrome, Edge, Firefox and IE tested.
* **Language:** [all | **TypeScript 3.10.5** | ES6/7 | ES5]

**Comment by vicb** [comment]
Please isolate the bug and provide a repro as of today:

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
