### ISSUE TITLE
The application is lost (404) after hit F5 (Refresh) with "@angular/router": "3.0.0-rc.1"

### ISSUE THREAD

**Issue by mindarelus** [angular/angular#10627]
Basically what happens is this:
http://localhost:12285/lobby - the application is running
Then I click f5 and have the same url in the browser but the application is lost:
HTTP Error 404.0 - Not Found

I use the new routing:
 "dependencies": {
        "@angular/common": "2.0.0-rc.5",
...
"@angular/router": "3.0.0-rc.1",

With the old one it was the same, but I changed the strategy to use # 
Although, I find having normal links and query string is more natural, so the question is:

Can this be achieved, without having to modify the server?

**Comment by mindarelus** [comment]
Btw another question, somehow related, in one component on CREATE button I call this code:
this.router.navigate(["/table", -1]);
And this doesn't navigate me to http://localhost:12285/table?id=1
but to this:
http://localhost:12285/lobby?

And if this could help to resolve both issues (this and the above), my app routing.ts looks like this:

import { Routes, RouterModule } from '@angular/router';
import { PageLobby, PagePlayers, PageRankings, PageTournaments, PageGame } from './components/index';

const appRoutes: Routes = [
    { path: 'lobby', component: PageLobby },
    { path: 'table/:id', component: PageGame },
    { path: 'players', component: PagePlayers },
    { path: 'rankings', component: PageRankings },
    { path: 'tournaments', component: PageTournaments },
    { path: '', redirectTo: '/lobby', pathMatch: 'full' },
    { path: '**', redirectTo: '/lobby' },
];

export const appRoutingProviders: any[] = [];

export const routing = RouterModule.forRoot(appRoutes);

**Comment by sirajc** [comment]
Gitter is a good place for questions. And this case is trivial and have been answered a lot. Your server is not configured to serve SPA. All routes must fallback to index.html. You are getting 404 because there is no lobby.html in your app.

Please do read the Contribution docs

**Comment by mindarelus** [comment]
Thanks, I will try that.
Btw I'm not sure if here is the right place to ask these kind of questions, but I'm glad you helped :)

**Comment by pkozlowski-opensource** [comment]
> Btw I'm not sure if here is the right place to ask these kind of questions

Of course there is: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
