### ISSUE TITLE
bug: PrivateComponentLoader and PrivateComponentLocation must be listed in services to work

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1063]
Works: 

```js
@DynamicComponent({
  selector: 'dynamic-component',
  services: [PrivateComponentLoader, PrivateComponentLocation]
})
class MyDynamic {

  constructor(
    loader:PrivateComponentLoader, 
    location:PrivateComponentLocation
  ) {}
}
```

Fails with `No provider for PrivateComponentLoader! (MyDynamic -> PrivateComponentLoader)`:

```js
@DynamicComponent({
  selector: 'dynamic-component',
  // services: [PrivateComponentLoader, PrivateComponentLocation]
})
class MyDynamic {

  constructor(
    loader:PrivateComponentLoader, 
    location:PrivateComponentLocation
  ) {}
}
```

**Comment by vicb** [comment]
The `PrivateComponentLocation` [is retrieved as a "pre-built object"](https://github.com/angular/angular/blob/0e61a86763e14999be91ff4c1d5c1fc9c8c3ac0f/modules/angular2/src/core/compiler/element_injector.js#L596) from the element injectors then there is no need to add it as a service.

I think `PrivateComponentLoader` should be added to the app injector, I'll open a PR for that
