### ISSUE TITLE
(feat) NgModule: remove the need to add bootstrap-component to declarations 

### ISSUE THREAD

**Issue by choeller** [angular/angular#10631]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When defining an NgModule Angular expects the bootstrap-component to be defined in 

declarations and bootstrap:

``` ts
@NgModule({

  bootstrap: [App],
  declarations: [App, Start, Contact, About]
})
export class AppModule {
}
```

 IMO this is unneccessary boilerplat, so when a component is the boostrap component it should be clear that it is part of the module. 

**Expected/desired behavior**

this should be sufficient:

``` ts
@NgModule({

  bootstrap: [App],
  declarations: [Start, Contact, About]
})
export class AppModule {
}
```

**What is the motivation / use case for changing the behavior?**

reducing the amount of boilerplate 

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all] 
- **Language:** [all]

**Comment by pkozlowski-opensource** [comment]
Not sure we can do this as it would prevent us from being able to bootstrap components declared in non-root modules. That is, the following would be no longer possible, if I'm not mistaken: https://plnkr.co/edit/DdetgJqULjsLiCKsKHUk?p=preview

I think that everyone feels the "pain" or repeating class names in various properties of `@NgModule` but at the same time there are different use-cases....

**Comment by choeller** [comment]
@pkozlowski-opensource Hmm, ok - I see, but somehow this feels like a 1% use-case makes 99% of applications more wordy. 
So with RC.5 Angular already tells me "Warning: you are using a component that is not on the declarations list". Wouldn't it be possible to say "if the component I'm using is my bootstrap-component and it's not on the declarations-list, just add it" or something like this.
