### ISSUE TITLE
Have an access to 'formControlName' value inside a custom validation function

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular#10633]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
There is no way how to get the value of 'formControlName' inside a custom validation function to identify which control is beeing actually validated (model-driven forms) because the only parameter is (c: FormControl) and the actual API of 'FormControl' is:
```
_errors, _onChange, _parent, _pristine, _status, _statusChanges, _touched,
_value, _valueChanges, asyncValidator, dirty, errors, pending, pristine,
root, status, statusChanges, touched, untouched, valid, validator, value, valueChanges
```

**Expected/desired behavior**
Be able to get 'formControlName' value inside a custom validation and generic function and use it as the identity of the actually validated control. It allows to have a dynamic set of validation rules for each control (for example in JSON syntax) that could be maintenated outside of the app code then.

**What is the motivation / use case for changing the behavior?**
To be more flexible and minimize the code = reducing the number of custom validators.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by zoechi** [comment]
Please provide a Plunker that demonstrates what problem this would fix.
You can pass values to your validator yourself by creating stateful validators.

**Comment by mlc-mlapis** [comment]
OK, no problem, but can you describe a bit more what you mean by 'stateful validator'? I know the term 'stateful pipe' but 'validator'? The main problem if you have a generic validation function is just recognize on which control it is actually running. You can create tons of wrapped validators and their only purpose is to transfer a value of 'formControlName' that already exists in a form definition (with duplications of all name values). If you have a hundreds of controls and many of them depends on others and their values that is really a lot of work.

**Comment by zoechi** [comment]
Support questions should be discussed in one of the channels mentioned in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by mlc-mlapis** [comment]
Of course I know but still the main problem remains and there is no solutions except many and many lines of code. So that is why a feature request was created because it is evident that a validator should know on which control he is running.

**Comment by kara** [comment]
@mlc-mlapis If your control depends on sibling control(s), chances are the validator should be moved up a level to the parent, where you do have access to names.  Or as @zoechi mentioned, you can wrap the validator. If you have a use case where this won't work, please open a new issue with a detailed description and a plunker. Without these, it's hard to evaluate the necessity of this feature request.

**Comment by mlc-mlapis** [comment]
Thanks for info. I understand that my previous problem description was not enough. I still think that there are real cases (including our projects) where our vision will be beneficial.

I will return to this thema and open a new issue when I have enough free time to collect descriptions that would be good enough to explain and convince.
