### ISSUE TITLE
How to run change detection (update template) for @Input value when previous value same as current value?

### ISSUE THREAD

**Issue by sanex3339** [angular/angular#10638]
How to run change detection (update template) for @Input value when previous value same as current value?

I'm using `ngrx`.

Use case:
I want to set default value for input after blur event, if input value is empty.

Input:
```
            <input 
                id="format" 
                class="form-control" 
                type="text" 
                [value]="inputValue" 
                (keyup)="keyup$.next($event.target.value)"
                (blur)="blur$.next($event.target.value)"
            >
```

`[value]="inputValue"` - `@Input` value of dumb component, taken from `store -> format`.
I take the value from the `store` in this way:
```ts
//main component

//template
template: `<format-input [inputValue]="format$ | async" (outputValue)="updateFormat($event)"></format-input>`

this.format$ = this.store.let(getFormat());

//form-reduser.ts
export function getFormat () {
    return (state$: Observable<GeneratorFormState>) => state$
        .map(s => s.format);
}
```

Both `keyup` and `blur` run action `updateFormat`.

My problem is what after `blur` event `[value]="inputValue" `will not update if value, which was inserted in the `store` was the same as previous `store` value.

For example:
1) store value: 22 => input value: 22 => clearing (cut) input value => blur event => input is empty, setting default value (1) to the store => store value: 1 => input value: 1
2) store value: 1 => input value: 1 => clearing (cut) input value => blur event => input is empty, setting default value (1) to the store => store value: 1 => input value: '' (empty)

So, how i can fix this?

**Comment by skreborn** [comment]
Issues filed in this repository should be about Angular's functionality, not its usage. Please move this question to an [appropriate channel](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question) to receive proper support.
