### ISSUE TITLE
Dependency mismatch

### ISSUE THREAD

**Issue by readme42** [angular/angular#10632]
```
[x] bug report
```

Hey mates,
since today our app crashes with the following:

`zone.js:260 Uncaught No provider for e!`

I nailed it down to a dependency mismatch. 

In our package.json, we defined only the following:
` "@angular/upgrade": "2.0.0-rc.4"`

The Problem seems, that 

`npm install @angular/upgrade@2.0.0-rc.4`

installs the following:

@angular/common@2.0.0-**rc.5**
@angular/platform-browser-dynamic@2.0.0-**rc.5**
@angular/compiler@2.0.0-**rc.5**
@angular/core@2.0.0-**rc.5**
@angular/upgrade@2.0.0-**rc.4**
zone.js@0.6.12
rxjs@5.0.0-beta.6

The version of `@angular/upgrade` does *not* match to its dependencies which will result in the error above.

Upgrading `@angular/upgrade` to RC5 resolves this issue.

**Comment by ruffiem** [comment]
update 
```bash "@angular/upgrade": "2.0.0-rc.4" ```
to 
```bash "@angular/upgrade": "^2.0.0-rc.4" ``` 
then run 
```bash npm install ```

**Comment by pkozlowski-opensource** [comment]
It sounds like you are on the old (<3) npm version. In npm 3+ peerDependencies are not installed automatically so you would have to specify correct version and wouldn't run into this pb.

Update to newer npm as I believe that our packages are good.
