### ISSUE TITLE
How do we get angular under Visual Studio 2015 running ?????????

### ISSUE THREAD

**Issue by j-nord** [angular/angular#10637]
We really tried everything:

Web api core 1.0 runs good.

But angular is not running:

Error over Error:

- ES5 Error! ES6 run.
- The sample so can not be installed. (angular.io)
- Npm error "Can't load moduls" (also in example that we download from the internet)
- System.js error ("Key not found)

We have only one example in the internat that run (for 9 month).

But if we make only one change, it runs again on an error. And then we search and search and ....

Is it the RC or is it in the wrong library.  

We develop Javascript, C # and otherlanguage for over 30 years. This is something we have not seen all the year.

If somewhere an example of what "really" works with asp web-api core and angular2 RC5 ???

**Comment by skreborn** [comment]
This isn't a support forum. Issues filed in this repository should be about the functionality of Angular, not its usage. Please check out the [appropriate channels](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question) if and when in need of assistance.

**Comment by alnahas** [comment]
check this video it's will be helpful for you [https://www.youtube.com/watch?v=mec4_AsLKTw](url)

**Comment by amcdnl** [comment]
@j-nord please close this issue, this is not related to Angular. 

Also please see the Github Issue Etiquette before making any more posts - https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
