### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'select'. ("<select [ERROR ->][(ngModel)] = "foo" (ngModelChange) = "onChange($event)">

### ISSUE THREAD

**Issue by kam2001** [angular/angular#10634]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
adding a [(ngModel)] caused error after upgrading to rc.5 from rc.4

**Expected/desired behavior**
two way binding from <select> using ngModel

* **Angular version:** 2.0.0-rc.5
 
* **Browser:**  Chrome
 
* **Language:** TypeScript

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by pkozlowski-opensource** [comment]
`ngModel` is not ambient by default in RC5 - you need to explicitly include forms module. Check https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html for more details.

**Comment by pablocarreraest** [comment]
@pkozlowski-opensource I do every step but nothing happen. If you have some other ideas guide. thanks

**Comment by josiahmann** [comment]
I had the same issue. Per @pkozlowski-opensource s comment, importing the 'FormsModule' in my child module fixed the issue.

```import { FormsModule } from '@angular/forms';

@NgModule({
  imports: [
    FormsModule
  ],
  ...```
