### ISSUE TITLE
async pipe works different with .? operator after upgrade to RC.5

### ISSUE THREAD

**Issue by Delagen** [angular/angular#10639]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

In templates where value is Observable
```
{{(value|async)?.number}}
```

**Current behavior**
 Cannot read property 'number' of null

But when I wrote Pipe with simple value && value.number
and changed template
```
{{value|async|customPipe}}
```
All works as expected. Sad but I can't reproduce it in generic project

**Expected/desired behavior**
No error, but when data come then value updated

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Chrome 53
 
* **Language:** TypeScript 2.0

**Comment by sod** [comment]
Plunkr http://plnkr.co/edit/IpVB9ydJJdINpgsWf93E?p=preview

**Comment by vicb** [comment]
@chuckjaz could you please take a look ?

**Comment by CaselIT** [comment]
It seems that the problem is that at the beginning the async pipe emits null.
See example http://plnkr.co/edit/XBcem9ozBeSxMn0aBuOm?p=preview

**Comment by DzmitryShylovich** [comment]
@CaselIT this is exactly why he uses `?.` operator

**Comment by chuckjaz** [comment]
The issue is the assumption that generating an expression twice will generate the same expression producing the same value.  The generated code looks like:
```js
var currVal_0 = jit_interpolate7(1,'Async value: ',
  ((valUnwrapper.unwrap(self._pipe_async_0.transform(self.context.observable)) == null)? 
    null: 
    valUnwrapper.unwrap(self._pipe_async_1.transform(self.context.observable)).value),'')
```
This create observes two values coming from the pipe instead of just the first one. It checks the first for `null` then assumes the second will be non-null. The solution is to introduce a temporary storing the result of the first invocation. The would result in code like,

```js
var tmp_0;
var currVal_0 = jit_interpolate7(1,'Async value: ',
    ((tmp_0 = valUnwrapper.unwrap(self._pipe_async_0.transform(self.context.observable)) == null)?
      null: 
      tmp_0.value),'')
```

I will work on introducing the temporary variable.

**Comment by smith64fx** [comment]
Is there already a fix? Our async pipes don't work anymore =/

**Comment by ericmartinezr** [comment]
@smith64fx yes, it is fixed in rc.6.

**Comment by smith64fx** [comment]
@ericcarraway oh yeah I see.. Thanks so much!

![image](https://cloud.githubusercontent.com/assets/3246782/18291367/afc00006-7487-11e6-9cde-ece436517801.png)
