### ISSUE TITLE
router rc.1 redirects take precedence over other routes

### ISSUE THREAD

**Issue by adamcohenrose** [angular/angular#10642]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```

**Current behavior**

Routes with redirect override other component routes when calling `navigateByUrl` meaning that the desired destination is never reached.

The behaviour appears to have changed from alpha.7 to rc.1

**Expected/desired behavior**

I would like to have redirects in the routing for default behaviour, but also be able to navigate around between components using relative URLs.

**Reproduction of the problem**

See http://run.plnkr.co/plunks/YkUrvjffC3zQPCU2nE2f/ for the code running using rc.4 and the alpha.7 router. When loaded, the app redirects via the parent component to the sister component; then has working links between sister and brother components.

http://run.plnkr.co/plunks/3ZoKpI8QVAdKxMFV7Ksl/ uses identical code other than the update to rc.5 and the rc.1 router. When this app loads, it still redirects via the parent component to the sister component, but clicking the brother link briefly shows the brother URL before redirecting back to the sister component.

**What is the expected behavior?**

The redirect should not override higher priority component routes.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 with router rc.1
 
* **Browser:** Chrome 51
 
* **Language:** TypeScript 1.9.0-dev.20160409

**Comment by vsavkin** [comment]
Since you have placed the click handler on an a tag, you must return `false` to prevent the default link behavior, like this:

```
  onClick(event: any) {
    let urlTree: any = this.router.createUrlTree(
      ['../brother', { 'b': true } ], { relativeTo: this.route }
    );
    console.log('going to brother:', urlTree);
    this.router.navigateByUrl(urlTree, { relativeTo: this.route });
    return false;
  }
```

Another option would be to place the click handler on a button or any other dom element.

Closing this issue.
