### ISSUE TITLE
Router Resolve not working

### ISSUE THREAD

**Issue by otolol** [angular/angular#10649]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm trying to add resolve on my root component. This is my Resolve.
```
export class initResolver implements Resolve<Promise<any>> {
    resolve(route:ActivatedRouteSnapshot, state: RouterStateSnapshot):  Promise<any>{

        let pr = new Promise((resolve, reject) => {
           setTimeout(() => {
               resolve('val');
           }, 1000);
        }).then((val) => {
            return val;
        });
        return pr;
}
```

and this is root 

`{path: 'preMatch', component: PreMatchComponent, resolve: {init: initResolver}},
`

before pr promise resolve, prematch root is resolved.

**What is the expected behavior?**

I expected that preMatch root will be resolved after pr will be resolved. In this case after setTimeOut.

* **Angular version:** 2.0.0-rc.4
 

* **Language:** [TypeScript X.X ]

**Comment by brandonroberts** [comment]
The router doesn't access Promises for guards as of RC4. In RC5 it accepts a Promise or an Observable.

**Comment by otolol** [comment]
I check guard and  it works for RC4. But Resolve not working.

**Comment by brandonroberts** [comment]
Can you provide a plunker reproducing this issue?

**Comment by vsavkin** [comment]
Closing this issue. Please reopen it with a plunker reproducing the problem.
