### ISSUE TITLE
How to use the service in the extended class?

### ISSUE THREAD

**Issue by HVND** [angular/angular#10651]
When i try to configure like this:

    import {
       ResolvedReflectiveProvider,
       Directive,
       ComponentFactoryResolver,
       ViewContainerRef,
       Injector
    } from "@angular/core";
     import { RouterOutlet, ActivatedRoute, RouterOutletMap } from "@angular/router";
    import { LoadingService } from "../services/loading.service";

    @Directive({ selector: 'router-outlet' })
    export class LoadingRouterOutlet extends RouterOutlet {

       constructor(private _parentOutletMap: RouterOutletMap, private _location: ViewContainerRef,    private _resolver: ComponentFactoryResolver, private _name: string, private _loadingService:    LoadingService) {
           super(_parentOutletMap, _location, _resolver, _name);
           console.log(this._loadingService); // this._loadingService is undefined
       }

       activate(activatedRoute: ActivatedRoute, loadedResolver: ComponentFactoryResolver,    loadedInjector: Injector, providers: ResolvedReflectiveProvider[], outletMap: RouterOutletMap): void {
           super.activate(activatedRoute, loadedResolver, loadedInjector, providers, outletMap);
       }

       deactivate(): void {
           super.deactivate();
       }
    }

I will got this._loadingService is undefined

**LoadingService.ts**

    import { Injectable } from "@angular/core";

    @Injectable()
    export class LoadingService {
        public loading = false;

        constructor() {
        }

        start() {
            this.loading = true;
        }

        stop() {
            this.loading = false;
        }

         isRunning() {
            return this.loading;
        }
    }

**Comment by marcalj** [comment]
You should add this Service in the ```providers``` array. Since RC5 in a ```NgModule``` declaration.

**Comment by pkozlowski-opensource** [comment]
Closing as a support question, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
