### ISSUE TITLE
[upgrade-adapter-rc.4] change detection does not work sometime on a hybrid app

### ISSUE THREAD

**Issue by huyph** [angular/angular#10660]
**I'm submitting a ...**  (check one with "x")

```
[ X ] bug report
```

On a hybrid application (mixture of ng1 and ng2), change detection doesn't work sometime

**Current behavior**
In `upgrade_adapter.ts`:

``` javascript
ngZone.onMicrotaskEmpty.subscribe({
                        next: (_: any) => ngZone.runOutsideAngular(() => rootScope.$evalAsync())
                      });
```

**Expected/desired behavior**
If I change this to: 

``` javascript
ngZone.onMicrotaskEmpty.subscribe({
                        next: (_: any) => ngZone.run(() => rootScope.$evalAsync())
                      });
```

Change detection seems to work.

One drawback is: this will re-introduce the infinite `$rootScope.$digest` (https://github.com/angular/angular/issues/6385)

**Reproduction of the problem**
Unfortunately I haven't been able to replicate the issue on plunker, it only happens on a specific situation I have on one of my production servers.

But hopefully someone who is familiar with the codes above, can give me a light on what can affect this code, and I will give another go at replicating the issue on plunker.

Thanks guys! 

**What is the motivation / use case for changing the behavior?**
To make hybrid application possible
- **Angular version:** 2.0.0-rc.4
- **Browser:** Chrome 51.0.2704.106
- **Language:** TypeScript 1.8 | ES6

**Comment by jonlarsson** [comment]
We are also experiencing intermittent problems which we believe is failures to detect changes. It seems that ngIf and ngFor could be connected to the problems somehow. For example *ngIf="<condition>" does not work while [hidden]="!<condition>" does.

**Comment by petebacondarwin** [comment]
See #12318
