### ISSUE TITLE
can't find FormsModule, HttpModule, JsonpModule in rc5

### ISSUE THREAD

**Issue by CK110** [angular/angular#10665]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I upgrades to RC 5 and as soon as I tried to run the app I was hit with the follow error:
![4a6b27da-71bb-4a70-8dd5-de9bfc4b3d96](https://cloud.githubusercontent.com/assets/9956098/17577477/bb8a0792-5fb0-11e6-9e5b-3884ad20faec.png)

i find that the index.d.ts of the @angular/forms,like this
![84253af5-5433-4c63-a01b-ce58663a331f](https://cloud.githubusercontent.com/assets/9956098/17577513/3e09923c-5fb1-11e6-8db0-5a290322dd43.png)

but l  cant find FormsModule in forms.d.ts
![8f753e40-fb37-4b66-bb08-c5edf3f5c887](https://cloud.githubusercontent.com/assets/9956098/17577528/654d266a-5fb1-11e6-9e6a-53ee9ae9ef41.png)

this is my package.json
```
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "core-js": "^2.4.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12",
```

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by buiducanh** [comment]
FormsModule is provided by form_providers.ts.
forms.ts just re-export everything `export * from './form_providers.ts`

**Comment by marcalj** [comment]
Did you ```typings install``` after upgrade? You should include all packages that contains TypeScript definitions directly:

```bash
typings install npm:<pkg> --save
```

Example:

```bash
typings install npm:@angular/core --save
```

**Comment by kylecordes** [comment]
This advice above by @marcalj  seems very unusual to me. Simply installing angular itself with NPM makes the proper type things available to typescript. I have set up highly numerous Angular projects and never needed to separately ask the typings command to make typings available for angular.

**Comment by vapits** [comment]
Same here and unfortunately typings installs is not fixing the issue:
![image](https://cloud.githubusercontent.com/assets/8594758/17588644/b14c234e-5fd0-11e6-8009-fb5da8992429.png)

**Comment by inska** [comment]
@vapits please attach your installed npms via command "npm list".

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by marcalj** [comment]
@kylecordes Which TypeScript version are you using? Maybe I'm doing it because it was a requirement for an old TypeScript version.

We can use TypeScript 2.0 to use Angular2?

Thanks!

**Comment by kylecordes** [comment]
@marcalj Angular 2 itself currently declares a dependency on typescript "^1.9.0-dev.20160409", and the CLI creates projects which depend on 2.0.0. A couple of months ago you could stick with typescript 1.8.10 for Angular 1 work; I don't know whether that is still possible today, but I see little realistic reason to do so. I have found it most effective to simply follow along with what the CLI sets up, I used typescript 2.0.0 for current Angular rc.N projects.

However, pointing back toward the goal of this issue tracker which is for issues with Angular itself, I would prefer if there was a page on the angular.io site with an official statement of dependencies and required versions of various tools. I spent a few minutes searching just now and did not find anything, though I noticed the QuickStart still uses typescript 1.8.10.  Currently even the page about typescript set up does not mention any version requirements. https://angular.io/docs/ts/latest/guide/typescript-configuration.html

**Comment by marcalj** [comment]
Also for polyfills. We don't know which ones should use for each **specific** browser version (specially for IE).

Thanks :)

**Comment by marcalj** [comment]
@kylecordes I've removed all typings from npm packages and all is working perfectly. Thanks for the advice! :)

**Comment by qaisaliabbas** [comment]
### 

> [`_****_`](

- 

1. url
Duplicate of #

)
