### ISSUE TITLE
RC.5 Can't bind to 'ngModel' since it isn't a known property of 'textarea'.

### ISSUE THREAD

**Issue by huyaxiong** [angular/angular#10669]
<textarea class="message-textarea" [(ngModel)]="userInput">
</textarea>

Is [(ngModel)] doesn't support <textarea> element anymore?so how can i do this?

**Comment by kara** [comment]
It sounds like you're not including the `FormsModule`.   See the migration guide [here](https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html).

**Comment by pablocarreraest** [comment]
hi @kara, I also have error of **"Can't bind to 'ngmodel' since it isn't a known property of 'input'"**
for resolve that I read all about ngModule -> import the FormsModule but nothing happens. I really need some help pls
thanks

**Comment by kara** [comment]
It's hard for me to help you without an example plunker. Can you provide one?

**Comment by pablocarreraest** [comment]
I tested in a mini app and work alright 👍 ! it seems to be the problem when a move the angular dir to my dist/libs folder (don't know why I do that)

**Comment by pablocarreraest** [comment]
hi @kara just a tiny question... if my dir structure is like this:
<img width="205" alt="screen shot 2016-08-25 at 1 51 49 pm" src="https://cloud.githubusercontent.com/assets/4999086/17982100/13a00ab4-6acc-11e6-9f5f-9870fc46704c.png">
I think I have a problems with import the modules because it doesn't get it and I get this error. Despite that all the files load fine. Im using systemjs:

<img width="1022" alt="screen shot 2016-08-25 at 2 02 26 pm" src="https://cloud.githubusercontent.com/assets/4999086/17982227/98078d2c-6acc-11e6-8b22-33b885d04203.png">

I don't think I can can replicate this in plunker. If you have some ideas I will be very thankful.

**Comment by kara** [comment]
@pablocarreraest Can you double-check that your template has `ngModel`, not `ngmodel`?

**Comment by pablocarreraest** [comment]
thanks the html-minifier was making that! god bless u! 🙏

**Comment by jrood** [comment]
the minifier! I knew it!

**Comment by cdcooksey** [comment]
I'm on RC4 trying to upgrade to RC5.  There are a ton of things missing in the CHANGELOG for RC5 -- like how exporting `describe, it, expect` doesn't work anymore in tests.

I have this same issue:

```
Can't bind to 'ngModel' since it isn't a known property of 'input'. ("<label class="blue-text" for="quantity">QTY
	    <input [ERROR ->][(ngModel)]="inventory.quantity"
	           (change)="onChange(inventory)"
	           value="{{ inven"): UpcInventoryItem@1:11
```

`package.json`:

```son

  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "^2.4.8",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "2.0.0-rc.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",
    "@ngrx/core": "^1.0.0",
    "@ngrx/effects": "^1.0.0",
    "@ngrx/store": "^2.0.1",
    "core-js": "^2.4.0",
    "es6-promise": "^3.2.1",
    "es6-shim": "^0.35.1",
    "foundation-sites": "6.2.4",
    "reflect-metadata": "^0.1.3",
    "require": "^2.4.20",
    "rxjs": "^5.0.0-beta.9",
    "typings": "1.3.3",
    "zone.js": "0.6.13"
  },
```

`main.ts`

```typescript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app.module';
import { environment } from './environments/environment';

if (environment.production) {
    enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule);
```

`app.module.ts`

```typescript
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import {DeprecatedFormsModule} from '@angular/common';
import { FormsModule }   from '@angular/forms';

import { ProductManagement }  from './product_management/ProductManagement';

@NgModule({
    imports: [ BrowserModule, DeprecatedFormsModule, FormsModule ],       // module dependencies
    declarations: [ ProductManagement ],   // components and directives
    bootstrap: [ ProductManagement, MasterProductSearch ],     // root component
    providers: []                    // services
})
export class AppModule { }
```

The official RC4 -> RC5 page 404s now and I'm having trouble finding any guide that is actually complete.

**Comment by xzessmedia** [comment]
simple solution:
avoid angular, learn react... simple, fast and good working in production

thats advice after using angular since first version of angularjs

**Comment by jpnathan** [comment]
Import `FormsModule` in your `app.module.ts`
