### ISSUE TITLE
Authentication / authorization module

### ISSUE THREAD

**Issue by pensierinmusica** [angular/angular#1067]
Is Angular 2.0 going to provide any official authentication / authorization module out of the box?

I think this would be a pretty relevant feature. See [this thread on Quora](http://www.quora.com/What-is-better-for-a-Hybrid-app-MeteorJS-or-AngularJS) for example.

Thoughts? Cheers  :)

**Comment by mhevery** [comment]
not sure yet. Closing as not an issue.

**Comment by pensierinmusica** [comment]
Hi @mhevery, instead of closing this, is it possible to label it as a "feature request"?

As far as I understand, generally feature requests get closed in two ways:

1) The feature has been implemented
2) The team and the community behind the project, after discussing the feature, decide it should not be implemented.

Do you think this would make sense? Thanks!

**Comment by naomiblack** [comment]
Closing this issue for now -- agree that this is something that would be useful, but not a priority for the 2.0 release. This is something that could also be developed independently as a community-built module.
