### ISSUE TITLE
RC.5 Http request text() doesn't manage case of null body

### ISSUE THREAD

**Issue by damienpontifex** [angular/angular#10672]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Making a GET request with no body results in an exception of "Cannot read property 'toString' of null".

It seems in the commit e7a8e2757b06d572f614f53b648d2fd75df370d2 the text function now doesn't do the `isPresent(this._body)` https://github.com/angular/angular/commit/e7a8e2757b06d572f614f53b648d2fd75df370d2#diff-c9b22b9d241f7ed55d13b39d1ccb333bL109 check causing the failure

It now falls through to here https://github.com/angular/angular/commit/e7a8e2757b06d572f614f53b648d2fd75df370d2#diff-1239ed5b0c3fa3d870cb4005226ed5d6R56 when null causing the error.

**Expected/desired behavior**
Should be able to send a HTTP GET request with no request body.

**Reproduction of the problem**
So far, making a HTTP get request with an empty body reproduces the issue.

**What is the expected behavior?**
Should be able to send a HTTP GET request with no request body.

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Tested on [Chrome 52 | Safari 9.1 ] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by ruffiem** [comment]
Duplicate #10612 Pull request pending #10635

**Comment by damienpontifex** [comment]
Thanks @ruffiem and happy to close as duplicate
