### ISSUE TITLE
RC.5 Can't bind to 'toUser' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by huyaxiong** [angular/angular#10670]
Here's my code.
`
<i nput id="image-input" type="file" class="show-for-sr" accept="image/*" imageMessage [toUser]="lastChatFollowerId" >
`

`
@Directive({
    selector: '[imageMessage]'
})
export class ImageMessageDirective  {
    @Input('toUser')
    toUser:string;
}
`

it works fine in RC.4,but now i dont know what to do with this...

**Comment by DzmitryShylovich** [comment]
Pls provide a plunker with reproduction.

**Comment by huyaxiong** [comment]
full code is too much,this is the segment.

**Comment by pkozlowski-opensource** [comment]
> full code is too much,this is the segment.

We don't need _full_ code, just a minimal reproduce scenario in a plunker. Without it no one can help you here...

I'm suspecting that you are not including the `ImageMessageDirective` in your component / module. But this is just a stab in the dark - impossible to confirm without a reproduce scenario.

**Comment by huyaxiong** [comment]
`
@Directive({
    selector: '[imageMessage]'
})
export class ImageMessageDirective implements OnInit, OnDestroy {

    @Input('toUser')
    toUser:string;
    private el:HTMLElement;
    private reader = new FileReader();
    private image;


    constructor(el:ElementRef) {
        this.el = el.nativeElement;
    }

    ngOnInit() {

        this.reader.onload = function (e) {

            this.image.value = e.currentTarget.result;
            socket.emit('sendImageMessage', {toUser: this.toUser, image: this.image});
        }.bind(this);
    }

    ngOnDestroy() {

    }

    @HostListener('change')
    onChange() {

        let file = this.el.files[0];
        if (file.size >= (2 * 1024 * 1024)) {
            return;
        }
        // this.reader.readAsDataURL(file);
        this.reader.readAsArrayBuffer(file);
        this.image = {
            name: file.name,
            type: file.type,
        };
    }
}

@Component({
    selector: '.chat',
    template: `
                <input id="image-input" type="file" class="show-for-sr" accept="image/*" imageMessage [toUser]="lastChatFollowerId">
  `,
export class ChatComponent  {}


`

**Comment by huyaxiong** [comment]
I use ImageMessageDirective to listen file changes in ChatComponent.And when I upgraded to RC.5,it reminds an error like 'Can't bind to 'toUser' since it isn't a known property of 'input'.' I just want to ask is the directive usage changed or ...

**Comment by cristimusat** [comment]
@huyaxiong you get this error in prod environment or dev?

**Comment by gnujeremie** [comment]
Yeah, maybe related to #10618 ?

**Comment by huyaxiong** [comment]
@cristimusat I dont understand,is it matter?I do it in my local computer,and whether I added enableProdMode() or not,the same error appeared.

**Comment by cristimusat** [comment]
@huyaxiong I had the same problem as you (#10618) but only for
```bash
ng serve -prod
```
using 
```bash 
ng serve
```
no problem appeared. 

I fixed it by adding moduleId:module.id to all components and directives declared in declarations array from app.module

**Comment by huyaxiong** [comment]
@cristimusat but I didnt use angular-cli,I only use systemjs combined with gulp,but thanks for help.

**Comment by gnujeremie** [comment]
@huyaxiong do you minify your code ? if yes, check #10618 it may be the same error.

**Comment by huyaxiong** [comment]
@gabejohnson  no I didnt minify the code I wrote and also I use system.js and use the .umd.min.js files,so I think its not the same problem,but thanks anyway.

**Comment by cristimusat** [comment]
in #10618 the problem seams to be with bundling with mangle activated and not with minification.

**Comment by huyaxiong** [comment]
Thank you to everyone,its because my routes and ngModule config issue cause this.

**Comment by PedroStrabeli** [comment]
@huyaxiong, could you tell us what the error was? i have the same problem, only with other component, but would like to know your fix. Thanks

**Comment by huyaxiong** [comment]
@PedroStrabeli As I said,I checked my code of how I “import related ngModule“ then I found some module didnt import,so I correct it then I solved the problem.
