### ISSUE TITLE
How to compile directives added on the fly

### ISSUE THREAD

**Issue by dashng** [angular/angular#10678]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a directive.

```
@Component({
  selector: 'interfaces',
  template: '<p>child</p>'
})
class InterfaceList {
  doSomething() {
      alert('=========');
  }
}

```

> add drective interfaces on the fly

```
public showInterfaces(event, device){
        var $tr = $(event.target).closest('tr');
        var $td = $(`
                <tr> 
                    <td colspan='4'>sfdsdfsdf</td>
                </tr>
        `);
        $td.insertAfter($tr);
        $td.find('td').html(function(){
            return '<interfaces></interfaces>';
        });
    }
```

* questions:

> how should i compile it.

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all ] 
 
* **Language:** [all | TypeScript | ES6]

**Comment by dashng** [comment]
@all

**Comment by dashng** [comment]
I find a solution with ComponentResolver.

But it needs:

```
@ViewChild('putStuffHere', {read: ViewContainerRef}) putStuffHere;
```

and the putStuffHere tag must be added in the template. 

It does't work if I added  <div #putStuffHere ></div> on the fly.

Any suggestions on this?

**Comment by dashng** [comment]
I find a solution with ComponentResolver.

But it needs:

@ViewChild('putStuffHere', {read: ViewContainerRef}) putStuffHere;
and the putStuffHere tag must be added in the template.

It does't work if I added
&lt;div putStuffHere&gt; &lt;/div&gt;
on the fly.
Any suggestions on this?

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
