### ISSUE TITLE
Bi-directional binding (Bannana in a box) don't work out-of-the-box

### ISSUE THREAD

**Issue by davidgfolch** [angular/angular#10674]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request
```

**Current behavior**

Bi-directional binding (Bannana in a box) don't work out-of-the-box for parent/child component, with child event emitter.  Parent component property is not updated.

**Expected/desired behavior**

Avoid duplication of binding attibutes.

**Reproduction of the problem**
Parent template (DONT WORK):
```
<userEdit ([toggleEditInPlace])="toggleEditInPlace" 
      [hidden]="!toggleEditInPlace">
</userEdit>
```
Parent template (WORKS):
```
<userEdit [toggleEditInPlace]="toggleEditInPlace" (toggleEditInPlace)="toggleEditInPlace=$event" 
      [hidden]="!toggleEditInPlace">
</userEdit>
```

Child component:
```
  @Input() toggleEditInPlace:boolean=false;
  @Output('toggleEditInPlace') toggleEditInPlaceEvent=new EventEmitter<boolean>();
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by pkozlowski-opensource** [comment]
"Bannana in a box" refers to `[(foo)]` and _not_ `([foo])`. `()` is a banana and `[]` is a box :-)

**Comment by davidgfolch** [comment]
Sorry @pkozlowski-opensource  it was a copy paste error.  I know whats is bananna and also box :))
But the feature request is still valid, isn't it??

**Comment by mlaval** [comment]
The event should be named `toggleEditInPlaceChange` in order to make it work.

**Comment by davidgfolch** [comment]
Yes that works, thank you.

But, for "non angular guys" like me thats not something evident.  Even I readed before, I didn't remember it.

Thanks a lot.
