### ISSUE TITLE
RC5 - Template driven form : select field resets after change

### ISSUE THREAD

**Issue by ruffiem** [angular/angular#10675]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When select one or multiple options, the model gets updated but the select field resets.

**Expected/desired behavior**
The selected options should stay highlighted.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/P0hX4BJWFOJc2W9QfGAV?p=preview

**What is the expected behavior?**
When the user select his options, they should stay highlighted which is not the case since RC update.

**What is the motivation / use case for changing the behavior?**
UX

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome latest ] 
 
* **Language:** [TypeScript]

**Comment by obiwan007** [comment]
Remove "DeprecatedFormsModule from your bootstrap. Then the selection is preserved.
Use either FormsModule or DepricatedFormsModule. Not both at the same time.
The Migration documentation in rc5 changelog is a bit misleading in the examples.
