### ISSUE TITLE
[testing] TestBed could offer an `overrideTemplate` method

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#10685]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As of rc.5, the new TestBed designed to replace TestComponentBuilder is introduced.
But it looks like, if I'm not mistaken, that we lost the equivalent of `overrideTemplate`, forcing us to use

```
TestBed.overrideComponent(RaceComponent, { set: { template: html }})
```

**Expected/desired behavior**

Maybe we could have something like:

```
TestBed.overrideTemplate(RaceComponent, html)
```
- **Angular version:** 2.0.0-rc.5

**Comment by markpritchett** [comment]
This functionality already exists - see the first test in https://github.com/angular/angular/blob/master/modules/%40angular/forms/test/template_integration_spec.ts

Here's a super simple example:

``` typescript
import { ComponentFixture, fakeAsync, inject, TestComponentBuilder, TestBed, tick } from '@angular/core/testing';
import { Component, OnInit } from '@angular/core';
import { By }                from '@angular/platform-browser';

@Component({
  selector: 'some-component',
  template: '<h2>Hello</h2>'
})

class SomeComponent {}

describe('SomeComponent: ', () => {
  it('should allow you to override template!',
       fakeAsync(inject([TestComponentBuilder], (tcb: TestComponentBuilder) => {
        const t = `<h2>World</h2>`;

        let fixture = tcb.overrideTemplate(SomeComponent, t).createFakeAsync(SomeComponent);
        var headingText = fixture.debugElement.query(By.css('h2')).nativeElement.textContent;
        expect(headingText).toBe('World');
   })));
});
```

Here's a plunker too http://plnkr.co/edit/Ur4t5syhdXRVlEUP5zIl?p=preview :smile:

**Comment by cexbrayat** [comment]
@markpritchett Thanks for the sample, but I'm talking about the new test API in rc.5 not the old one we already use in hundred of tests we have in our ebook and various projects ;)

**Comment by markpritchett** [comment]
Oh I see what you mean @cexbrayat 

Looks like it would be fairly simple to put a pull request in for this.  Looking at source - https://github.com/angular/angular/blob/master/modules/%40angular/core/testing/test_bed.ts, maybe it would be something like:

``` typescript
static overrideTemplate(component: Type<any>, template: string):
  typeof TestBed {
    getTestBed().overrideComponent(component, { set: { template: template });
      return TestBed;
}
```
