### ISSUE TITLE
Provide a smoother way to remove a declaration from the testing module

### ISSUE THREAD

**Issue by juliemr** [angular/angular#10689]
In some cases, you'd like to set up your testing module the same as a larger module you're exporting, but want to mock out some declarations. Currently there is no way to _remove_ a declaration though, so you'd have to make a whole new module and duplicate your list.

e.g., now

``` ts
// in lib
@NgModule({
  declarations: [A, B, C, D, E]
})
class MyLibModule {};

// in test for E, we want to mock out D
TestBed.configureTestingModule({
  declarations: [A, B, C, MockD, E]
});
```

Instead it would be nice to be able to do something like:

```
// in test for E
TestBed.configureTestingModule({
  imports: [MyLibModule],
  remove: [D],
  declarations: [MockD]
});
```

**Comment by IgorMinar** [comment]
```
TestBed.configureTestingModule({
  imports: [MyLibModule],
  declarations: [MockD]
});

TestBed.overrideModule(MyLibModule: {
  declarations: {
    remove: [D]
    add: [MockD]
  });
```

also see: https://github.com/angular/angular/blob/master/modules/@angular/platform-browser/test/testing_public_spec.ts#L318

**Comment by juliemr** [comment]
Wouldn't it have to be:

```ts
TestBed.overrideModule(MyLibModule: { set: {
  declarations: [The whole list again]);
}
```
?

**Comment by IgorMinar** [comment]
if you want to avoid dealing with the whole list - which is fragile - then I'd use add/remove

**Comment by juliemr** [comment]
But I don't think that works for sub-objects? Or am I wrong? Will try it out when I have a minute.

**Comment by juliemr** [comment]
OK, you're right. It has a slightly different syntax: here is a complete, working example of using a module and just removing one of the declaration/exports.

```ts
import {
  async,
  inject,
  TestBed,
  ComponentFixture
} from '@angular/core/testing';
import { Component, NgModule } from '@angular/core';

@Component({
  selector: 'a-cmp',
  template: '<span>A</span>'
})
class AComp {}

@Component({
  selector: 'a-cmp',
  template: '<span>ADIFF</span>'
})
class ADiffComp {}

@Component({
  selector: 'b-cmp',
  template: '<span>B</span>'
})
class BComp {}

@Component({
  selector: 'b-cmp',
  template: '<span>BDIFF</span>'
})
class BDiffComp {}

@Component({
  selector: 'omega-cmp',
  template:'<a-cmp></a-cmp><b-cmp></b-cmp>'
})
class OmegaComp {}

@NgModule({
  declarations: [AComp, BComp],
  exports: [AComp, BComp]
})
class MyModule {}

fdescribe('overriding stuff', () => {
  it('maybe lets you override sub things', () => {
    TestBed.configureTestingModule({
      imports: [MyModule],
      declarations: [OmegaComp, ADiffComp]
    });

    TestBed.overrideModule(MyModule, {
      remove: {
        declarations: [AComp],
        exports: [AComp]
      }
    });

    TestBed.compileComponents().then(() => {
      let fixture = TestBed.createComponent(OmegaComp);
      console.log(fixture.nativeElement);
    });
  });
});
```

I think this is Good Enough For Now but will continue to think about whether we can add better ergonomics post v2.

**Comment by aciccarello** [comment]
The above solution was simple enough for me. Main developer pain point was the lack of documentation on how to use the `TestBed.overrideXXXX` methods. It was not immediately apparent what to put in the `get`/`set`/`add` options. Also, I had expected the `overrideComponent` method to be able to override the component implementation. Docs related issues include #16026 and #14068.

**Comment by jessicajaniuk** [comment]
Closing as this has insufficient votes and has a work around. Feel free to create a new issue if this is still a need.
