### ISSUE TITLE
RC5 Router. NavigationEnd-events are emitted when guards cancel navigation.

### ISSUE THREAD

**Issue by dagstuan** [angular/angular#10680]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a guard cancels an attempt at navigation, the router still fires a NavigationEnd-event. When subscribing to NavigationEnd-events from the router, its not possible to determine whether or not navigation actually happened.

**Expected/desired behavior**
Either cancelled navigation should not emit NavigationEnd, or the NavigationEnd-event should contain information about whether or not navigation actually occured.

**Reproduction of the problem**
Plnkr to reproduce: http://plnkr.co/edit/e9DdEGDDKU19mcaMvf2U?p=preview

Try navigating to the "away"-view and check the console for NavigationEnd-events emitted from the router.

* **Angular version:** 2.0.0-rc.5

**Comment by dagstuan** [comment]
Updated the plnkr with a "canDeactivate"-example as well. Try navigating to the "Page not found"-view and disallow navigation while checking the events emitted from the router: http://plnkr.co/edit/e9DdEGDDKU19mcaMvf2U?p=preview

**Comment by awerlang** [comment]
PR #10409 fixes this.

**Comment by vsavkin** [comment]
Fixed in master
