### ISSUE TITLE
RC5 page refresh loses current route when using angula router

### ISSUE THREAD

**Issue by redBaronNc** [angular/angular#10683]
Hello,
When I have 2 routes defined and a redirect on the root / 
navigation works properly but when refreshing the page the route is lost and the root is called triggering the redirect, whatever URL was in before the refresh
```
[ ] bug report
```

**Current behavior**
route: /
result: redirect to /#/dashboard show the SchemaListComponent

route: /#/dashboard 
result: show the SchemaListComponent

route: /#/users 
result: show the UserListComponent

route before refresh : /#/users or /#/dashboard
result on refresh: redirect to /#/dashboard show the SchemaListComponent

**Expected/desired behavior**
route before refresh : /#/dashboard
result on refresh: show the SchemaListComponent

route before refresh: /#/users 
result on refresh: show the UserListComponent

**Reproduction of the problem**
``
import { Routes, RouterModule } from '@angular/router';

import { SchemaListComponent }  from './schemalist.component';
import { UserListComponent }     from './userlist.component';

const appRoutes: Routes = [
  {
    path: '',
    redirectTo: '/dashboard',
    pathMatch: 'full'
  },
  {
    path: 'dashboard',
    component: SchemaListComponent
  },
  {
    path: 'users',
    component: UserListComponent
  }
  
];

export const routing = RouterModule.forRoot(appRoutes, { useHash: true });
``
**What is the expected behavior?**
The route currently used should be the same after a refresh

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [ Chrome 52.0.2743.116 ] 
 
* **Language:** [TypeScript X.X | ES6/7 | ES5]

**Comment by vsavkin** [comment]
Could you provide a plunker with a repro?

**Comment by redBaronNc** [comment]
I made an example in this plunker http://plnkr.co/edit/P1q2gMBJpnBn8jvILZwy?p=preview
I don't know if you can rely on plunker itself to try since I don't know how the "URL" in the plunker preview behaves.
So the behavior I expect is that if you click on the users link and refresh the page, you would still see the Users component. This does not work when I try on Chromes (as I said I am not sure we can rely on plunker to check that)

**Comment by vsavkin** [comment]
@redBaronNc Your plunker works for me. The users component remains after a refresh.

Open your plunker, and you will see a tiny blue button with arrow pointing in all directions in the top right corner. Click on it, and the plunker will open your example in a new window, so you can examine the URL. Navigate to the users component and click refresh.

Please let me know the results.

**Comment by redBaronNc** [comment]
You are right it works on plunker :-) . Thank you for your help!
