### ISSUE TITLE
Building with grunt-traceur

### ISSUE THREAD

**Issue by jpopesculian** [angular/angular#1069]
I'm attempting to build angular with grunt-traceur in my project, and these errors arise. They seem like legitimate errors, and can be easily fixed. I can submit a pull request if you'd like.

>> ERRORS:
>> assets/scripts/lib/angular2/src/change_detection/parser/ast.es6:392:5: super call is only allowed in derived constructor
>> ERRORS:
>> assets/scripts/lib/angular2/src/core/annotations/annotations.es6:73:5: 'this' is not allowed before super()
>> ERRORS:
>> assets/scripts/lib/angular2/src/directives/for.es6:11:5: super call is only allowed in derived constructor
>> ERRORS:
>> assets/scripts/lib/angular2/src/directives/foreach.es6:11:5: super call is only allowed in derived constructor
>> ERRORS:
>> assets/scripts/lib/angular2/src/forms/directives.es6:21:5: super call is only allowed in derived constructor,assets/scripts/lib/angular2/src/forms/directives.es6:44:5: super call is only allowed in derived constructor,assets/scripts/lib/angular2/src/forms/directives.es6:103:5: super call is only allowed in derived constructor
>> ERRORS:
>> assets/scripts/lib/angular2/test/forms/integration_spec.es6:297:5: super call is only allowed in derived constructor

**Comment by vicb** [comment]
see #1073, #845 

please also note that we intend to switch to TypeScript (over Traceur) shortly.

**Comment by rkirov** [comment]
Try again, both pending issues have been resolved.
