### ISSUE TITLE
Can no longer manually inject HTTP_PROVIDERS now that its Module

### ISSUE THREAD

**Issue by born2net** [angular/angular#10699]
```
[ ] bug report
[x] feature request (removed feature???)
[x ] support request => Please do not submit support request here, instead see 
```

Ad for rc.5 since now providers are modules we can no longer inject them

```
var injector = ReflectiveInjector.resolveAndCreate(
            [
                TodoService,
                TodoAction,
                HTTP_PROVIDERS, // <----- no longer injectable
                TodoStatsModel,
                {provide: CommBroker, useClass: CommBroker},
                {provide: AppStore, useValue: this.appStore}
            ]);
```

**Expected/desired behavior**
used to work so need to know if functionality is supported? available still?

**Reproduction of the problem**
see code above

**What is the expected behavior?**
hope we can get or have a workaround for this feature that used to work.

**What is the motivation / use case for changing the behavior?**
Be able to manually create injector.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.0-rc.5
 
Chrome OS latest
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
TypeScript

**Comment by shlomiassaf** [comment]
HTTP_PROVIDERS are deprecated.... so I wouldn't bet on it.

You should use the app injector to create a child injector, you can get the app injector in a NgModule you create and set it in the constructor of the module's class.

**Comment by born2net** [comment]
any chance for a plunkr, toda!!!!

**Comment by shlomiassaf** [comment]
I'll live code something here... to late for plunkers...

basically, 

```ts
@NgModule({
  imports: [HttpModule] // if its a root module, if its a feature module you might omit it.
})
export class CustomModule {
  constructor(injector: Injector) {
    let http = injector.get(Http); // this will work here, you'll get an Http instance.
    let childInjector = ReflectiveInjector.resolveAndCreate(
      [
        TodoService,
        TodoAction,
        TodoStatsModel,
        {provide: CommBroker, useClass: CommBroker},
        {provide: AppStore, useValue: this.appStore}
      ],
      injector
    )
  }
}
```

You can set the new injector on a property in the module's instance and they use `NgModuleRef` to get a hold of it.

I don't know the use case you're going towards but the above is less natural.

the best approach is to set these providers in the `providers` metadata property of the CustomModule.

Again, it depends on what you want to achieve.

If you want new injectors for every action you take factories are more suited...

**Comment by born2net** [comment]
toda raba...
but I think the above code still won't completely replace thr HTTP PROVIDERS as we are still missing the other classes such as RequestOptions etc...
all the ones that were part of the barrel?

layla tov

**Comment by zoechi** [comment]
@born2net why do you think they are not part of the `HttpModule`?

**Comment by born2net** [comment]
shlomiassaf did fix the issue so I am closing, tx!
