### ISSUE TITLE
Router - replace history instead of pushing

### ISSUE THREAD

**Issue by pleerock** [angular/angular#10691]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently there is no way to use history.replace within router.

**Expected/desired behavior**

Need to introduce option for router to replace a history instead a pushing a new.
 
**What is the motivation / use case for changing the behaviour?**

For example Im in a question list (`/questions`) opening a new modal in a new route (`/questions/add`), and after adding a new question I go to the question view (`/questions/1`). If I press back I would like to go to the `/questions` instead of `/questions/add`

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by markpritchett** [comment]
I think support for this is coming, looking at the source in master - https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts

It looks like the syntax will be 

``` typescript 
this.router.navigate(['some/url'], { replaceUrl: true }); 
```

Looks like @brandonroberts did the work on this, he might be able to confirm if the above is correct.

**Comment by vsavkin** [comment]
This has been merged into master.
