### ISSUE TITLE
Router: RouterLink treats root level secondary route as matrix params

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#10694]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If I want to deep link to a nested secondary(aux) route from the root component, the `outlets` object is treated as a matrix parameter.

**Expected/desired behavior**

The `routerLink` should generate the correct href to a nested secondary route from the root component.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/51MgOtwUy5ekQv39QfAN?p=preview

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 

cc: @vsavkin

**Comment by vsavkin** [comment]
Fixed here: https://github.com/angular/angular/commit/afcb3c0035d216ddfffe02c42d1d1d6ce2daa8b7
https://github.com/angular/angular/commit/d2d36c61f3d8376489b4f99d2cb8ee68de444009
