### ISSUE TITLE
zone.js should be included as dependency by import

### ISSUE THREAD

**Issue by jpopesculian** [angular/angular#1070]
Throws error if not included before angular
example in `angular2/src/core/zone/vm_turn_zone.es6`

**Comment by mhevery** [comment]
This must be this way because zone.js must be first thing to intercept all the calls. This requires better error/documentation.

**Comment by pkozlowski-opensource** [comment]
Right. @rkirov we also need to take this into account while preparing one-file-that-has-them-all build.

**Comment by rkirov** [comment]
A better error message is a must.

However, not sure if module import is the right solution for `zone.js`. With an import we can guarantee that zone runs before all of angular. But in fact, it might need to run before every other JS on the page and that includes 'system.js' itself.

@pkozlowski-opensource the ES5 SystemJS (or CommonJS) bundle will not have zone.js. However, the ES5 consumable self-executing bundle will be prepended with zone.js.

**Comment by pkozlowski-opensource** [comment]
With the latest bundling strategy we've got zones.js included (concatenated). We can't reference zones through an import as explained by @rkirov 

Closed by c0b04ca0bc762bc925434a8762eee74ce999e57e
