### ISSUE TITLE
RC5 lazy loaded modules don't preserve instance

### ISSUE THREAD

**Issue by voinearob** [angular/angular#10703]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
  ROUTES :
  {
    path: 'crisis-center',
    loadChildren: 'app/crisis-center/crisis-center.module#CrisisCenterModule'
  }
  NAVIGATION :
  <a [routerLink]="['/crisis-center', { step : '1' }]" routerLinkActive="active">Crisis Center Step 1</a>
  <a [routerLink]="['/crisis-center', { step : '2' }]" routerLinkActive="active">Crisis Center Step 2</a>
```
Each time you navigate through these links all the components from CrisisCenterModule get a new instance.

**Expected/desired behavior**
```
By default, the router reuses a component instance when it re-navigates to the same component type without visiting a different component first. The parameters can change between each re-use.
```

**What is the motivation / use case for changing the behavior?**
Think of a multiform in steps (previous / next). You can't save the state from step 1 when you go to step 2 and you're forced to dump the lazy loading of an entire module because of this.

Also, it would be very helpful to be able to make the routerLinkActive take into account query params. In the above example boths link will be active.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 with "@angular/router": "3.0.0-rc.1",
 
Didn't thoroughly test this, but it seems like an issue not related to the browser / language.

**Comment by vsavkin** [comment]
Could you provide a plunker with a repro?

**Comment by vsavkin** [comment]
Dup of #10702
