### ISSUE TITLE
routerLinkActive not activating if used on different tag than routerLink is used on

### ISSUE THREAD

**Issue by sharpmachine** [angular/angular#10704]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
routerLinkActive is not activating (so `.active` is not being added to element) if used on different tag than routerLink is used on when navigating with the same parent component. For example: 

This works:
```html
<ul>
    <li>
      <a routerLinkActive="active" [routerLink]="['assessments']">Page One</a>
    </li>
    <li>
      <a routerLinkActive="active" [routerLink]="['case-plans']">Page Two</a>
    </li>
  </ul>
```

But this doesn't:
```html
<ul>
    <li routerLinkActive="active">
      <a [routerLink]="['assessments']">Page One</a>
    </li>
    <li routerLinkActive="active">
      <a [routerLink]="['case-plans']">Page Two</a>
    </li>
  </ul>
```

**Expected/desired behavior**
I would expect routerLinkActive to work on `<li>` tags since frameworks like Bootstrap style the `<li>` tag when it's active, etc.

**Reproduction of the problem**
https://plnkr.co/edit/upLeYcMNctfGtvKrBeVo?p=preview

**What is the motivation / use case for changing the behavior?**
Cue the user that they are on the screen they want to be on.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5, and @angular/router 3.0.0-rc.1
 
* **Browser:** OSX El Capital, Chrome 52
 
* **Language:** [Typescript]

**Comment by vsavkin** [comment]
I'm confused. The link is highlighted in the repro.

**Comment by sharpmachine** [comment]
Are you sure? If you navigate from home to Subject One, yes, Assessments is highlighted. But if you navigated from Subject One to Subject Two, Assessments is not highlighted for Subject Two.

**Comment by vsavkin** [comment]
Navigating to Page One results in this url: `subject/1/assessments`.
Navigating to Page Two results in this url: `subject/1/case-plans`.

This is the URL of the link you are trying to highlight: `subject/1/assessments`. That is why after navigating to Page 2 the link you are trying to highlight is no longer active. It is a completely different URL.

**Comment by sharpmachine** [comment]
Thanks not what I'm seeing at all. I'm seeing:

Navigating to Page One results in this url: `subject/1/assessments`.
Navigating to Page Two results in this url: `subject/2/assessments`.

I'm so confused.

**Comment by sharpmachine** [comment]
I updated the plunker to show how `routerLinkActive` works if you put it on the same tag as `routerLink`, which I think proves there's an issue with `routerLinkActive` directive.

**Comment by sharpmachine** [comment]
@vsavkin have you had another chance to look at this? I would really appreciate it. Thanks!

**Comment by sharpmachine** [comment]
@brandonroberts I know you've dealt with the `routerLinkActive` directive issues before. Any chance you can take a look at my repro? If you can't no worries...I know you're busy. But if you can, thanks in advance.

**Comment by brandonroberts** [comment]
@sharpmachine there is a bug with the `routerLink` not being updated when on an element that's not an anchor tag. That may be the root cause in the `routerLinkActive` not added the classes correctly to the `li` tag.

**Comment by sharpmachine** [comment]
@brandonroberts thanks for getting back to me. Good to know it's def a bug. Will wait it out until a fix is released.

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/11063
