### ISSUE TITLE
Fix to #10073 (automatically stringify JSON objects in http requests) introduces hard to diagnose problem

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#10717]
Upgraded to `rc 5` and http request code that has been working since beta stopped. I've figured out why and I think you could save other devs a lot of heartache with 2 or 3 lines of code.

I have a `screenHttpRequest()` function that is run before every request. Because the API I interact with expects JSON data, this function sets header `content-type: application/json` on every request. This has never been a problem. As of `rc 5` though, probably because of [this commit](https://github.com/angular/angular/commit/83bc5c9), the application will crash with the cryptic error `this._body is null` on `GET` requests. I suspect it's because Angular sees the content-type header and tries to serialize the body, which is of course null on a `GET` request.

A clearer error message there, or an `if(this._body)` check before serialization would be great. With everything going on in a big application, it was tough to isolate the problem because the error is not thrown on the line of code that sets the header and because the message is so generic (says nothing about http or json).

More details on this [StackOverflow board](https://stackoverflow.com/questions/38908973/unable-to-make-http-request-with-angular-2-rc5/38909123#38909123)

**Comment by vicb** [comment]
Please re-open and complete the issue template if still a pb
