### ISSUE TITLE
Unable to use REACTIVE_FORM_DIRECTIVES in multiple modules

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#10716]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using reactive forms in 2 modules fails with an error

**Expected/desired behavior**
It should work

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

See http://plnkr.co/edit/2tFC6CDrcZSg3GxW5qRS?p=preview which is forked from lazy load example at https://angular.io/docs/ts/latest/guide/ngmodule.html with the minor addition that
app component and crisis detail component  each try to create a FormGroup with a FormControl. When crisis detail is loaded (click on crisis center) it fails with an error:
`EXCEPTION: Error: Uncaught (in promise): Type FormControlDirective is part of the declarations of 2 modules: AppModule and CrisisModule!`
Maybe there's some documentation that shows how to do this correctly - but I haven't found it. I have tried various combinations of including/not including things in the 2 modules and the components but haven't hit on a combination that works. Based on the documentation I've seen this looks like a bug.

**What is the expected behavior?**
It shouldn't fail

**What is the motivation / use case for changing the behavior?**
To be able to use reactive forms.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
Typescript

**Comment by robwormald** [comment]
There are two forms modules - you're looking for the `ReactiveFormsModule` (which includes the REACTIVE_FORM_DIRECTIVES and the REACTIVE_FORMS_PROVIDERS

You're getting duplicate errors because you're including REACTIVE_FORMS_DIRECTIVES in your component - this is no longer necessary w/ NgModules.

**Comment by slubowsky** [comment]
Didn't know there were 2 forms modules. All the docs I saw only talked about FormsModule. Thanks
