### ISSUE TITLE
wrongly encoding URLSearchParams when the value contains '=' 

### ISSUE THREAD

**Issue by ziggyJ** [angular/angular#10718]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
QueryEncoder encode '=' to ';'

**Expected/desired behavior**
QueryEncoder should encode '=' to '%3D'

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** all
 
* **Language:** all

**Comment by vicb** [comment]
see https://github.com/angular/angular/pull/9790. Needs review and merge
