### ISSUE TITLE
URLSearchParams with custom QueryEncoder does not work on the http.get

### ISSUE THREAD

**Issue by ziggyJ** [angular/angular#10719]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
URLSearchParams with custom QueryEncoder does not work on the http.get call. It still uses the default QueryEncoder.

It seems RequestOptions.merge function just replace the custom QueryEncoder to the default one.

**Comment by vicb** [comment]
I remember having merged a fix. If not re-open an issue with the template fully completed and a repro.
