### ISSUE TITLE
Http.get => this._body is null

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#10721]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you set header `Content-Type` to `"application/json"` and you perform GET request (which is of course non sense, but it can be done) you will get error `"this._body is null"` in Firefox and in Chrome `"Cannot read property 'toString' of null"`.

This is caused because there is method calling getBody which looks at ContentType and it is `"application/json"`. This will call method text() which tries to convert `_body` to string, but body is null in GET requests.

**Expected/desired behavior**
It should not fail, even if it is non sense, it should probably return null or empty string.

**Reproduction of the problem**
https://plnkr.co/edit/QMW7o1eVNPmxWeAwJ9vh?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by vicb** [comment]
Just merged. Will be in next release.
