### ISSUE TITLE
Feature Request : Add styleDeepUrls property to the decorator of the component.

### ISSUE THREAD

**Issue by mindarelus** [angular/angular#10722]
@Component({
    moduleId: module.id,
    selector: "chat",
    templateUrl: "chat.html" + APP_VERSION,
    styleUrls: ["chat-specific-to-host.css" + APP_VERSION],
    styleDeepUrls: ["chat-global.css" + APP_VERSION],
})

Is it possible to have another array, in which we pass the styles, that we want to inject into the children. It is very annoying to write /deep/ in every css selector of your styles. 

In the example, I just want to be able to have the styles from chat-global.css to all children of the ChatComponent.

**Comment by mindarelus** [comment]
Actually it is so likely that everyone will want his styles going into the children, that its best to use styleUrls to go deep as default, and something like styleNotDeepUrls for the host.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by mindarelus** [comment]
Actually it is a feature request. This is a new functionality, that will make working with styles into the children better.
