### ISSUE TITLE
Rename NgModule to Container

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/angular#10729]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

It seems there is a potential for friction caused by the confusion between NgModules, ES6 Modules and CommonJS modules. 

Where CommonJS and ES6 Modules fit into the same taxonomy and purpose of what a module is, NgModules are quite different. 

It seems there are two main purposes of NgModules:

1.  The ability to group components, services and pipes together to make code reuse easier.
2.  Allow dependency for those components, services and pipes to be defined in isolation without side effects on other NgModules. 

Just looking at item 1 by itself it would appear this feature fits into the concept of modules. With the two items together it appears the overall purpose is an Inversion of Control Container.  In reality 1 is a side effect of 2. 

That said, I am not sure Container is the best name for the feature, maybe Kernel -- as many other IoC containers would call this feature a Kernel. 

I understand that NgModule might be the best name for this feature. I just want to start a conversation about this. 

**What is the motivation / use case for changing the behavior?**

Reduce friction caused by confusion. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** all
* **Language:** all

**Comment by pkozlowski-opensource** [comment]
We've got a number of those unfortunate words in IT (manager, package, controller, component, module etc.). Those words can mean anything depending on the context. Any of those or similar words can easily create confusion. 

IMO "Container" is one of those confusing words and won't address the problem that you are raising here. It will merely swap one set of confusions to another one. 

Given the above I don't think that the breaking change is justified at this point so I;m going to close this one. Thnx for the suggestion though. Naming things is hard so feel free to continue the discussion in there and generate other ideas.
