### ISSUE TITLE
Don't want angular router to see path separators as separate route segments.

### ISSUE THREAD

**Issue by mustafasadikot** [angular/angular#10720]
I have a route as below:

`path: 'Foo/:Address'`

The Address parameter can contain string as below:

`boo/bar/a` or 
`boo/b`

But when my code routes to any of the above address, I get an exception that there are no matching routes. I suppose it considers `foo`, `bar` and `a` to be different route segments and hence it throws an exception. I need a single param in the route as the number of segments are random and the url should be as it is without any string replacement.

Is there any way I can let angular know that anything after `foo` is a single param?

I am using below versions:

`"@angular/core": "2.0.0-rc.4"`

`"@angular/router": "3.0.0-beta.1"`

**Comment by Nalha** [comment]
I would suggest either making the slash separated parts part of the path or make it a url parameter, allowing slashes in urls that are not part of the actual url is just confusing.

**Comment by vsavkin** [comment]
The router escapes the segments when constructing new URLs, so this is not an issue when using routerLink or router.navigate. If you construct URLs through other means, you need to escape them yourself.

**Comment by mustafasadikot** [comment]
@vsavkin below is a snippet in my project:

```
var address = 'Foo/boo/bar/a';
router.navigate(address);
```
below is the route:

`path: 'Foo/:Address'`

so how do i make it work?
