### ISSUE TITLE
API docs - missed text doesn't show up in output?

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#1072]
See doc for angular2/annotations/Viewport at https://angular-mhevery.c9.io/angular2

![screen shot 2015-03-23 at 10 53 31 pm](https://cloud.githubusercontent.com/assets/2286589/6796392/7da963fe-d1af-11e4-9520-b375c67f5742.png)

This content for that constructor exists in the doc as a comment at https://github.com/angular/angular/blob/master/modules/angular2/src/core/annotations/annotations.js#L699 but is not generated, possibly because of a TODO next to it?

@petebacondarwin is this something dgeni should be more tolerant of, or an issue in our doc comment?

**Comment by petebacondarwin** [comment]
Hmm so dgeni was taking the first of the preceding come but this was problematic so I changed it to the last. Instead it should use them all. I'll fix that.
