### ISSUE TITLE
RC5 still does not animate nested elements correctly (persistent problem)

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular#10737]
**I'm submitting a persistent problem with animations of nested elements in RC5.
```
[x] bug report
```

**Current behavior**
This problem was reported in RC2 (https://github.com/angular/angular/issues/9402 and https://github.com/angular/angular/pull/9887) and it had to be resolved by commit https://github.com/angular/angular/commit/c3bdd504d0ea1166d26df359c7bbd9d28df70c99. But it is not true. The problem still exists.

Plunker demo: There is an outermost DIV that contains another inner DIV. Buttons allow to expand and collapse them individually. Steps to show:
- Expand the outer and then inner.
- Continue with collapsing the outer.
- Finally expand the outer again.

**Expected/desired behavior**
Expanding animation of the outermost DIV should respect its full content (including inner div) which is available at the actual moment.

**Reproduction of the problem**
Plunker: http://plnkr.co/edit/58pVfEs0cJAxvQfwlIpr?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all]
 
* **Language:** [all]

**Comment by mlc-mlapis** [comment]
@matsko Any comment on this? Is the problem deeper then it was supposed?

**Comment by matsko** [comment]
Yes I will be working on this tomorrow.

**Comment by mlc-mlapis** [comment]
Something new on it?

**Comment by matsko** [comment]
It's been figured out. I just need a day to talk with @tbosch to see if there are any final issues: https://github.com/angular/angular/pull/11201

**Comment by mlc-mlapis** [comment]
Thanks. Great news. I am looking for ...

**Comment by matsko** [comment]
@mlc-mlapis unfortunately this didn't make it into RC6, but it will be there for the next version. If you want to use this now you can configure your package.json to point to the HEAD builds for core, compiler.

```
    "@angular/common": "angular/common-builds",
    "@angular/compiler": "angular/compiler-builds",
    "@angular/core": "angular/core-builds",
    "@angular/platform-browser": "angular/platform-browser-builds",
    "@angular/platform-browser-dynamic": "angular/platform-browser-dynamic-builds",
```

**Comment by mlc-mlapis** [comment]
Thank you Matias, we'll certaily do it. I'll inform you as soon as possible.

**Comment by mlc-mlapis** [comment]
I confirm that the problem was solved in RC7.

The working plunk: http://plnkr.co/edit/qEdukIeLaAVmRq3nYGAG?p=preview
