### ISSUE TITLE
Issue with either router or form module

### ISSUE THREAD

**Issue by ashokacharya** [angular/angular#10736]
**Current behavior**
when button inside form is click it goes redirected to this http://localhost:8000/? 

**Please tell us about your environment:**
   Angular Version :2.0.0-rc.5
  Browser :Chrome Latest Version
Language :TypeScript

**Comment by ashokacharya** [comment]
<form class="groupForm" [formGroup]="groupForm" (ngSubmit)="onSubmit(groupForm)" >
      <md-input
        #txtGroupName
        [dividerColor]="groupName.hasError('required')|| groupName.pristine|| groupName.hasError('invalidAlphaOnly')?'accent':'primary'"

        [formControl]="groupName"

        style="width:100%"
      >

        <md-placeholder style="color: #3e5e85;">
          Group Name
        </md-placeholder>
        <md-hint align="start" style="color:red;font-size: 13px;">{{groupName.hasError('required') &&
          groupName.dirty?'Group name is required':groupName.hasError('invalidAlphaOnly') && groupName.dirty?'Alphabets
          and space are allowed':''}}
        </md-hint>
        <span md-prefix><i class="fa fa-users"></i></span>
      </md-input>

      <md-input
        #txtGroupDescription
        [dividerColor]="groupDescription.hasError('required')|| groupDescription.pristine|| groupDescription.hasError('invalidAlphaOnly')?'accent':'primary'"

        [formControl]="groupDescription"

        style="width:100%"
      >
        <md-placeholder style="color: #3e5e85;">
          Group Description
        </md-placeholder>
        <md-hint align="start" style="color:red;font-size: 13px;">{{groupDescription.hasError('required') &&
          groupDescription.dirty?'Group name is required':groupDescription.hasError('invalidAlphaOnly') &&
          groupDescription.dirty?'Alphabets and space are allowed':''}}
        </md-hint>
        <span md-prefix><i class="fa fa-pencil"></i></span>
      </md-input>
      <br/>
      <md-input
        #txtGroupTags
        [dividerColor]="groupTags.hasError('required')|| groupTags.pristine|| groupTags.hasError('invalidAlphaOnly')?'accent':'primary'"

        [formControl]="groupTags"

        style="width:100%"
      >
        <md-placeholder style="color: #3e5e85;">
          Group Tags Eg. boys,girls,itahari etc
        </md-placeholder>
        <md-hint align="start" style="color:red;font-size: 13px;">{{groupTags.hasError('required') &&
          groupTags.dirty?'Group name is required':groupTags.hasError('invalidAlphaOnly') && groupTags.dirty?'Alphabets and space are allowed':''}}
        </md-hint>
        <span md-prefix><i class="fa fa-tags"></i></span>

      </md-input>
      <br/>
      <br/>
      <md-checkbox [checked]="true" align="end" [formControl]="isPrivate" style="color: #3e5e85;">
        Is Private ?
      </md-checkbox>
      <br/>
      <br/>
      <div class="fileUpload">
        <label for="profileInput">
          <div md-mini-fab class="btnUpload">
            <i class="fa fa-image"></i>
          </div>
          <md-input disabled class="inputUpload">
            <md-placeholder>
              Choose Profile Image
            </md-placeholder>

          </md-input>
        </label>

          <input id="profileInput" #profileInput type="file" class="upload"/>

      </div>
      <br/>
      <div class="fileUpload">
        <label for="coverInput">
          <div md-mini-fab class="btnUpload">
            <i class="fa fa-image"></i>
          </div>
          <md-input disabled class="inputUpload">
            <md-placeholder >
              Choose Cover Image
            </md-placeholder>

          </md-input>
        </label>
          <input id="coverInput" #profileInput type="file" class="upload"/>
      </div>

      <br/>
      <button style="padding: 15px;" [disableRipple]="true" md-raised-button
              [disabled]="!groupForm.valid || groupForm.pristine || createGroupStatus=='Creating'" color="primary">
        Create Group
      </button>
    </form>

**Comment by ashokacharya** [comment]
<form class="groupForm" [formGroup]="groupForm" (ngSubmit)="onSubmit(groupForm)" > <md-input #txtGroupName [dividerColor]="groupName.hasError('required')|| groupName.pristine|| groupName.hasError('invalidAlphaOnly')?'accent':'primary'" [formControl]="groupName" style="width:100%" > <md-placeholder style="color: #3e5e85;"> Group Name </md-placeholder> <md-hint align="start" style="color:red;font-size: 13px;">{{groupName.hasError('required') && groupName.dirty?'Group name is required':groupName.hasError('invalidAlphaOnly') && groupName.dirty?'Alphabets and space are allowed':''}}</md-hint> <span md-prefix><i class="fa fa-users"></i></span> </md-input> <md-input #txtGroupDescription [dividerColor]="groupDescription.hasError('required')|| groupDescription.pristine|| groupDescription.hasError('invalidAlphaOnly')?'accent':'primary'" [formControl]="groupDescription" style="width:100%" > <md-placeholder style="color: #3e5e85;"> Group Description </md-placeholder> <md-hint align="start" style="color:red;font-size: 13px;">{{groupDescription.hasError('required') && groupDescription.dirty?'Group name is required':groupDescription.hasError('invalidAlphaOnly') && groupDescription.dirty?'Alphabets and space are allowed':''}}</md-hint> <span md-prefix><i class="fa fa-pencil"></i></span> </md-input> <br/> <md-input #txtGroupTags [dividerColor]="groupTags.hasError('required')|| groupTags.pristine|| groupTags.hasError('invalidAlphaOnly')?'accent':'primary'" [formControl]="groupTags" style="width:100%" > <md-placeholder style="color: #3e5e85;"> Group Tags Eg. boys,girls,itahari etc </md-placeholder> <md-hint align="start" style="color:red;font-size: 13px;">{{groupTags.hasError('required') && groupTags.dirty?'Group name is required':groupTags.hasError('invalidAlphaOnly') && groupTags.dirty?'Alphabets and space are allowed':''}}</md-hint> <span md-prefix><i class="fa fa-tags"></i></span> </md-input> <br/> <br/> <md-checkbox [checked]="true" align="end" [formControl]="isPrivate" style="color: #3e5e85;"> Is Private ? </md-checkbox> <br/> <br/> <div class="fileUpload"> <label for="profileInput"> <div md-mini-fab class="btnUpload"> <i class="fa fa-image"></i> </div><md-input disabled class="inputUpload"> <md-placeholder> Choose Profile Image </md-placeholder> </md-input> </label> <input id="profileInput" #profileInput type="file" class="upload"/> </div><br/> <div class="fileUpload"> <label for="coverInput"> <div md-mini-fab class="btnUpload"> <i class="fa fa-image"></i> </div><md-input disabled class="inputUpload"> <md-placeholder > Choose Cover Image </md-placeholder> </md-input> </label> <input id="coverInput" #profileInput type="file" class="upload"/> </div><br/> <button style="padding: 15px;" [disableRipple]="true" md-raised-button [disabled]="!groupForm.valid || groupForm.pristine || createGroupStatus=='Creating'" color="primary"> Create Group </button> </form>

**Comment by brandonroberts** [comment]
Your `button` needs a `type="submit"` or you need to `return false;` after navigating if you're calling a function from within your component. See https://github.com/angular/angular/issues/6154
