### ISSUE TITLE
RC5 HTTP GET Content-Type JSON empty body exception

### ISSUE THREAD

**Issue by matejkramny** [angular/angular#10738]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
Sending a Http GET with headers `Content-Type: application/json` causes an exception

**Expected/desired behavior**
No exception. There is no content and content-type is set but that shouldn't cause an exception (which is very ambiguous)

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by vicb** [comment]
fix already merged. Published in the next release

**Comment by detectedstealth** [comment]
Any ETA on when the next release will be? Have been upgrading the app I'm working on for a client to RC5 and ran into this bug.

**Comment by matejkramny** [comment]
You can work around it by not setting the content type headers for get
requests

**Comment by detectedstealth** [comment]
Thanks the issue also happens with DELETE requests. But as you suggest removing the content type for both is a work around for now.
