### ISSUE TITLE
No component factory found for ... error when using ComponentFactoryResolver and NgModule

### ISSUE THREAD

**Issue by jkyoutsey** [angular/angular#10735]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```typescript
import { Component1 } from "...";
@NgModule {
    declarations: [
        Component1
    ],
    ...
}
```

```typescript
@Component({
    selector: "factory-component",
    template: ""
})
export class FactoryComponent {
    constructor(private viewContainerRef: ViewContainerRef, private resolver: ComponentFactoryResolver) { }

    public createComponent(): Promise<ComponentRef<any>> {
        let factory = this.resolver.resolveComponentFactory(Component1);
        ...
    }
}
```

The `let factory = ...` line will err with `No component factory found for Component1.`

If I add `entryComponents: [ Component1 ]` to the FactoryComponent then metadata_resolver.js@156 finds cmpMeta.entryComponents to have one element that is undefined.  This results in an error in the angular code that breaks boostraping.

** Reproduction
http://plnkr.co/edit/q20iZj?p=preview
This plunker doesn't use NgModule and has some confusing comments. (not mine).  It doesn't show how to use NgModule with ComponentFactoryResolver.  Nor does it fail.  But it's what I'm continually referenced to as the "solution".  But nothing in it solves my issue in any way.

**Expected/desired behavior**
Ability to use NgModule and ComponentFactoryResolver to create components dynamically via reflection at run-time.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome 52 | Firefox 46] 
 
* **Language:** TypeScript tsc 1.0.3.0

**Comment by rbj325** [comment]
Whatever component you are trying to use the ComponentFactoryResolver in has to declare the components you are trying to dynamically render as "entryComponents" in the @Component syntax:

@Component({
  directives: [
  ],
  providers: [],
  entryComponents: [
      MyDynamicComponent
  ]
})

**Comment by pkozlowski-opensource** [comment]
Here is a minimal plunker updated to RC5 and `@NgModule`: http://plnkr.co/edit/P0spNzu8JbQad2aKACsX

@rbj325 `entryComponents` on the `@Component` level is a deprecated API and going to be removed in RC6 - don't use it.

Closing as a support question, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by jkyoutsey** [comment]
@pkozlowski-opensource Thank you very much.  Exactly the answer I needed!

**Comment by meenie** [comment]
@pkozlowski-opensource: Can you please expand on the `read` config for `@ViewChild`? I assume it pulls a different reference from the element than the default?  I'm looking at the docs and it mentions nothing about it other than there is an option: https://angular.io/docs/ts/latest/api/core/index/ViewChildMetadata-class.html

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/b96869afd2bdd3ad8c5b7477da647af628e383aa/modules/%40angular/core/src/metadata/di.ts#L199

**Comment by meenie** [comment]
Thanks.  Suppose I should go to the source code first next time :).

**Comment by danielc-captora** [comment]
Thanks the plnkr example above was really helpful.

**Comment by demiro** [comment]
Thanks for the plunker, was very helpful!

Is it possible to have a list of allowed components (in module: entryComponents)... but get them created as needed on the fly?

What I mean is I am getting something like

```
<page-component-test></page-component-test>
<h2>Some title<h2>
<p>Lorem ipsum text</p>

```

from the API

and right now I am using something like:
`this.pageContent = API.response;
`

and then in the view:

`<div [innerHTML]="pageContent"></div>`


How would I render the response and create the components that are in there?

**Comment by nmorado** [comment]
if i were to have a dynamic template - say coming from some rules etc... how can i use this approach if i had to hard-code the templates?

is there a way to dynamically define the template of a component?

**Comment by moniuch** [comment]
What is the reason the plunker does not run anymore?
`zone.js:461 Unhandled Promise rejection: Zone.assertZonePatched is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Zone.assertZonePatched is not a function`

**Comment by ashwinirajput** [comment]
http://plnkr.co/edit/q20iZj?p=preview not working @rbj325 approach

**Comment by dovk** [comment]
It might be something trivial like a spelling mistake. I got this message:
**_ModalCmp ionViewPreLoad error: No component factory found for CalendarPage. Did you add it to @NgModule.entryComponents?_**
and after trying everything on this page, I noticed I had typed  
**_`import {CalendarPage} from '../calendar/calendar';`_**
instead of 
**_`import {CalendarPage} from '../Calendar/Calendar';`_**

**Comment by AskYous** [comment]
I had this issue when implementing a dialog using angular material. In case others come across this issue, this solved my problem:
https://material.angular.io/components/dialog/overview#configuring-dialog-content-via-code-entrycomponents-code-

**Comment by EbramTawfik** [comment]
fixed by adding this component to bootstrap: [AppComponent, newComponent] in app.module.ts
