### ISSUE TITLE
FormBuilder seems to trigger fallback message for "old" Forms lib

### ISSUE THREAD

**Issue by obiwan007** [angular/angular#10733]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you inject FormBuilder into a component, it will trigger a message
 _*It looks like you're using the old forms module. This will be opt-in in the next RC, and_

**Expected/desired behavior**
FormBuilder should not fallback to old deprecated forms library.

**Reproduction of the problem**

http://plnkr.co/edit/DrI8RcAtAPLeByilcjSy?p=preview

Look at debug console in Edge or Chrome to see the highlighted message.

**What is the motivation / use case for changing the behavior?**

Make sure all components use the new forms library-

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all  ] 
 
* **Language:** [TypeScript 1.8 ]

**Comment by ericmartinezr** [comment]
The removal of the old forms api was merged hours ago https://github.com/angular/angular/pull/10624, it's not in rc5 if I'm not wrong

**Comment by kara** [comment]
@obiwan007   Looking at your plunker, I actually don't see the deprecation message. You may want to refresh?   It was attached to the `ngFormModel` directive, so it shouldn't appear with `FormBuilder`.

Regardless, the `ngFormModel` directive (and all other deprecated form APIs) have been removed from master, so this will not be a concern.
