### ISSUE TITLE
Angular 2 Routing is not working when serving the content from Spring

### ISSUE THREAD

**Issue by mrtinkz** [angular/angular#10748]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1. Build a simple multi page angular2 application using 2.0.0-rc.5
2. Compile an bundle the application using webpack
3. Take the files under dist folder and move them into a spring boot static folder.
4. The application works fine when served user npm start but while being served as static resources from Spring, the routing seems to be not working. 

** Note this is not Spring related problem, I have an application working inside the spring but it uses 2.0.0-rc.4 and works perfectly fine. This is true for other servers like wamp where in moving the files under dist into a folder in wamp should bring up the application. I believe the way routing works is a problem. But again everything perfectly works when served using npm

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by vicb** [comment]
Without more info, there is nothing we can do !

**Comment by mrtinkz** [comment]
Thought so, I will create a working and a non working example and share it with you as soon as possible.

**Comment by pkozlowski-opensource** [comment]
Going to close for now as we haven't heard back. Happy to reopen if / when we've got a minimal reproduce scenario in a plunker or similar.
