### ISSUE TITLE
metadata contains errors when function is used in `useFactory`

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#10747]
https://raw.githubusercontent.com/angular/core-builds/master/src/application_tokens.metadata.json
contains
```
_appIdRandomProviderFactory: {
__symbolic: "function",
parameters: [ ],
value: {
__symbolic: "error",
message: "Expression form not supported",
line: 26,
character: 8
}
},
```

but that function should be allowed in the definition of APP_ID_RANDOM_PROVIDER:
```
export const APP_ID_RANDOM_PROVIDER = {
  provide: APP_ID,
  useFactory: _appIdRandomProviderFactory,
  deps: <any[]>[]
};
```

cc @mhevery

**Comment by chuckjaz** [comment]
Diagnosed off-line and determined that the error encountered was unrelated to the above metadata.
