### ISSUE TITLE
loadChildren from RouterModule.forRoot doesn't respect folder for 'app'

### ISSUE THREAD

**Issue by belapie** [angular/angular#10750]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using the NgModule and RouterModule.forRoot([...]), i need to specify the fullpath to the children module.

systemjs.config.ts:

```
[...]
const map: SystemJSLoader.PackageList<string> = {
    'app': 'scripts',
    'ts-helpers': 'https://npmcdn.com/ts-helpers@1.1.1',
    'angular2-in-memory-web-api': 'https://npmcdn.com/angular2-in-memory-web-api',
    'ng2-translate': 'https://npmcdn.com/ng2-translate@2.2.2',
    'angular2-cookie': 'https://npmcdn.com/angular2-cookie@1.2.2'
};
[...]
```

app.routes.ts

```
import { RouterModule } from '@angular/router';

export const routing = RouterModule.forRoot([
    {
        path: '',
        loadChildren: 'scripts/test/test.module',
        pathMatch: 'full'
    },
    {
        path: 'admin',
        loadChildren: 'scripts/admin/admin.module'
    }
], { useHash: true });
```

I tried `loadChildren: './test/test.module'` and `loadChildren: 'test/test.module'`

The platform is still looking at : `http://localhost:3000/test/test.module` instead of `http://localhost:3000/scripts/test/test.module`

app.routes.js (compiled js) is located inside the `scripts` directory.

**Expected/desired behavior**

Angular 2 should look directly at `http://localhost:3000/scripts/test/test.module`

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all] 
- **Language:** [all]

**Comment by hassanasad** [comment]
Shouldn't it be './scripts/test/test.module' ?

```
import { RouterModule } from '@angular/router';

export const routing = RouterModule.forRoot([
    {
        path: '',
        loadChildren: './scripts/test/test.module',
        pathMatch: 'full'
    },
    {
        path: 'admin',
        loadChildren: './scripts/admin/admin.module'
    }
], { useHash: true });
```

P.S: I am also getting issues with webpack and loadChildren property. For some reason it stops detecting saved changes.

**Comment by belapie** [comment]
All the "importable" files are located inside the scripts folder

e.g.: 

```
import { routing } from './app.routes';
import { SharedModule }   from './shared/shared.module';
```

`import { SharedModule }   from './shared/shared.module';`  not `import { SharedModule }   from './scripts/shared/shared.module';`

**Comment by DzmitryShylovich** [comment]
@belapie is this still an issue? could u provide a small repro in plunkr?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource no feedback. can be closed
