### ISSUE TITLE
[i18n] improve ngc 

### ISSUE THREAD

**Issue by vicb** [angular/angular#10766]
- `ngc --help` should print out the CLI args
- add an error message when a translation file is provided and either the file does not exist or the locale is not specified

**Comment by ocombe** [comment]
> add an error message when a translation file is provided and either the file does not exist or the locale is not specified

This is already the case. Changing the comp to compiler since the i18n part is ok

**Comment by JoostK** [comment]
Given Olivier's comment, only the `--help` part remains. Although this issue is older, there's a more extensive thread for this feature available in #15520 so I'll close this one.
