### ISSUE TITLE
Formatting pipes fail in Safari

### ISSUE THREAD

**Issue by johnchristopherjones** [angular/angular#10764]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using nearly any formatting pipe, including "percent", causes Angular 2 to fail in Safari 9.1.1 due to missing `Intl`.  Safari in iOS is also implicated.

For example, the template `<p>{{0.5 | percent:'1.1-1'}}</p>` always raises an uncaught exception in Safari.  Angular templates stop being rendered at this point.

**Expected/desired behavior**

Angular 2 formatting pipes should not raise uncaught exceptions in Safari.

**Reproduction of the problem**

This bug can be reproduced by opening the following plnkr in Safari:
http://plnkr.co/edit/ETQGYstBK8MF8YVF78Kj?p=preview

This bug can also be reproduced using the default `angular-cli` build:

1.  Install current Angular2 using `angular-cli`:
    ```bash
    $ npm uninstall -g angular-cli && npm cache clean && npm install -g angular-cli@webpack
    $ ng new intl-bug
    ```

2.  Add the following to a template in `app.component.html`:
    ```html
    <p>{{0.5 | percent:'1.1-1'}}</p>
    ```

**What is the expected behavior?**

It should go.

**What is the motivation / use case for changing the behavior?**

Going would be good.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Safari 9.1.1 | iOS 9.3.4 Safari
 
* **Language:** TypeScript 2.0.0

**Related**

This issue is related to discussion in #3333.

**Comment by vicb** [comment]
Check existing issue, you need to include Intl polyfill

**Comment by johnchristopherjones** [comment]
I'm aware of the polyfill.  Angular 2 already ships with a small bucket of polyfills.  It's irritating that Safari 9.1 does not ship with `Intl`, but it's probably not unreasonable to expect Angular 2 to not instantly crash out of the box on all iOS devices.

It is also not at all apparent how to include the Intl polyfill in the current angular-cli@webpack without using a CDN.  So, at the moment there is no method of using Angular tools to make Angular work on iOS or Safari.

**Comment by johnchristopherjones** [comment]
I'm sorry, but I'm really confused by this closure.  This breaks Angular 2 on Safari on iOS when using any built-in formatting pipes.  I mean, this closure is saying that Angular 2 as shipped officially does not support Safari on iOS.

I get not including polyfills for every ancient browser, but we're talking about the August 2016 version of Safari on the latest OS X El Capitan and iOS 9 in Angular 2.0.0-rc5.

I'll be happy to open another issue on `angular-cli` about including an `Intl` polyfill by default, because if `Intl` is required to make Angular 2 work on [55% of mobile browsers](http://appleinsider.com/articles/15/04/22/apples-safari-claims-55-of-us-mobile-browser-usage-105-desktop-share) then it's certainly a "best practice" that belongs in `angular-cli` if nowhere else.

It just seems silly to fix it in `angular-cli` when it's a problem that affects (hopefully?) target browsers.
