### ISSUE TITLE
ComponentFactoryResolver is not aware of components compiled via TestBed

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#10760]
The `ComponentFactoryResolver` [has an internal map](https://github.com/angular/angular/blob/b96869afd2bdd3ad8c5b7477da647af628e383aa/modules/%40angular/core/src/linker/component_factory_resolver.ts#L40) containing factories for components that have been compiled.

However, when TestBed compiles components declared in the `DynamicTestModule`, the factories are stored in the [TestBed's internal `_moduleWithComponentFactories`](https://github.com/angular/angular/blob/master/modules/@angular/core/testing/test_bed.ts#L141). These factories are never made known to the `ComponentFactoryResolver`, so any tests that use the resolver to create a component declared in the test module will fail with `Error: No component factory found for YourTestComponent`.

As a workaround, you can simply create a real `@NgModule` in which to declare your test components and import that into the test module.

cc @tbosch @IgorMinar

**Comment by tbosch** [comment]
Tests that rely on ComponentFactoryResolver to be filled correctly need to
declare "entryComponents" via configureTestModule (or import a module that
does so). This way you can test that your module is correct / test how
users would use your module.

The internal map in the test module should never go into the
ComponentFactoryResolver as it makes all components entryComponents, which
is not the case in actual apps.

**Comment by tbosch** [comment]
I.e. do a "configureTestingModule({declarations: ..., entryComponents:
...})"

**Comment by jelbourn** [comment]
@tbosch `configureTesitngModule` doesn't have `entryComponents`- all of its `declarations` are automatically treated as `entryComponents`.

**Comment by tbosch** [comment]
They are not treated as entryComponents, otherwise the
ComponentFactoryResolver would know them.

The ComponentFactoryResolver is only using entryComponents. The
TestBed.createComponent method is not using the ComponentFactoryResolver
nor the entryComponents of any module.

We should probably add entryComponents to configureTestingModule. Then the
workaround you mentioned above of creating a temporary NgModule would not
be needed any more...

**Comment by jelbourn** [comment]
I had meant to say that the `declarations` of the test module are _meant_ to be treated as `entryComponents`, and the fact that they're not causes this bug. @IgorMinar is that the intention with the testing module?

**Comment by ssmartin** [comment]
Having to declare the components I want to dynamically create in the @NgModule's entryComponents section is a huge regression from my point of view. 
I used the DynamicComponentLoader and then the ComponentResolver and they both worked like a charm, but this new way of doing it it's really not dynamic anymore and kind of beats the purpose if I have to "hardcode" the list of the components I want to dynamically create... this really broke our app, big way...

**Comment by allenhwkim** [comment]
I feel consused between `declarations` and `entryComponents`.
So, if I want to dynamically replace an element, I need to add `entryComponents` instead of using `declarations`?

```
@NgModule({
  imports: [ BrowserModule, FormsModule ],
  declarations: [AutoCompleteComponent, AutoCompleteDirective],
  exports:  [AutoCompleteComponent, AutoCompleteDirective],
  entryComponents: [AutoCompleteComponent],
  providers: [ AutoComplete ]
})
export class Ng2AutoCompleteModule {}
```

**Comment by ssmartin** [comment]
For dynamically creating a component with the ComponentFactoryResolver  you need to have the component declared in the _entryComponents_ section. At least that's my understanding and my tests confirmed this.

**Comment by kemsky** [comment]
Official documentation should mention `entryComponents` section, it is very important.

**Comment by ovione** [comment]
I have a problem and I saw this issue:

I have a simple component:
```
import { Component }   from '@angular/core';

@Component({
  selector: 'app-banner',
  template: '<h1>{{title}}</h1>'
})
export class BannerComponent {
  title = 'Test Tour of Heroes';
}
```

and my test is 
`import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By }              from '@angular/platform-browser';
import { DebugElement }    from '@angular/core';

import { BannerComponent } from './banner.component';

let comp:    BannerComponent;
let fixture: ComponentFixture<BannerComponent>;
let el:      DebugElement;

describe('BannerComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [ BannerComponent ], // declare the test component
      entryComponents: [BannerComponent]
    });

    fixture = TestBed.createComponent(BannerComponent);

    comp = fixture.componentInstance; // BannerComponent test instance

    // get title DebugElement by element name
    el = fixture.debugElement.query(By.css('h1'));
  });
  it('should display original title', () => {

    expect(true).toBe(true);
  });

});`

when I test it I get a 
**

> TestBed Unexpected value '' declared by the module 'DynamicTestModule'

**

I'm not sure how I can solve it. I thik this is related to this thread but is there any solution I could use if there is one ?

thanks

**Comment by devoto13** [comment]
> We should probably add entryComponents to configureTestingModule. Then the
workaround you mentioned above of creating a temporary NgModule would not
be needed any more...

Please, do. It's very inconvenient to configure `entryComponents` in tests now. I use this workaround at the moment (not sure if it's correct way, but it works at least):

    TestBed.configureTestingModule({
      declarations: [ MyDynamicComponent ],
    });

    TestBed.overrideModule(BrowserDynamicTestingModule, {
      set: {
        entryComponents: [ MyDynamicComponent ],
      },
    });

**Comment by jsgoupil** [comment]
Related: https://github.com/angular/angular/issues/12079

**Comment by LOZORD** [comment]
I ran into this issue when testing a dialog component. After trying a few strategies, writing a simple test component and test module (that has the correct `entryComponents`), worked for me. You can then use the test module as such:

```ts
TestBed.configureTestingModule({imports: [MyActualDialogModule, MyTestDialogModule]});
```

**Comment by ReneVallecillo** [comment]
@LOZORD Could you provide a code, I keep getting 

> 	Error: No provider for MdDialogRef!

**Comment by LOZORD** [comment]
I have something like this at the bottom of my __test__ file (I'm testing `Dialog`):

```ts
@Component({
  selector: 'dialog-test',
  template: '<button (click)="openDialog()">Open Dialog</button>'
})
class DialogTest {
  dialogRef: MdDialogRef<Dialog>|null;
  constructor(public dialog: MdDialog) {}

  // Tests can call `fixture.componentInstance.openDialog()` directly.
  openDialog() {
    this.dialogRef = this.dialog.open(Dialog);
    // Returning the observable here is useful for testing.
    // You can see what the close result is.
    return this.dialogRef.afterClosed();
  }
}

@NgModule({
  declarations: [DialogTest],
  imports: [DialogModule, BrowserModule, MdDialogModule],
  entryComponents: [Dialog], // <-- very important!
  exports: [DialogTest]
})
export class DialogTestModule {
}
```

Then test using a `DialogTest` component fixture. I hope this helps!

**Comment by ReneVallecillo** [comment]
@thanks for sharing. Could you share your testing spec if you don't mind.

Mine is close enough minus the fact I'm testing the dialog by itself so I don't have a open button.

`describe('ConfirmDialogComponent', () => {
  let viewContainerFixture: ComponentFixture<ConfirmDialogComponent>;
  let overlayContainerElement: HTMLElement;
  let dialog: MdDialog;



  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [MdDialogModule.forRoot(), DialogTestModule],

     // error seems not related to overlaycontainer
      providers: [
        {
          provide: OverlayContainer, useFactory: () => {
            overlayContainerElement = document.createElement('div');
            return { getContainerElement: () => overlayContainerElement };
          }
        }
      ],
    })

      .compileComponents();
  }));

 //not really using it yet.
  beforeEach(inject([MdDialog], (d: MdDialog) => {
    dialog = d;
  }));

  beforeEach(() => {
    viewContainerFixture = TestBed.createComponent(ConfirmDialogComponent);
    viewContainerFixture.detectChanges();
    // component = fixture.componentInstance;
    // fixture.detectChanges();
  });

  it('should render the dialog correctly', () => {

  });

});

@NgModule({
  imports: [MdDialogModule],
  declarations: [ConfirmDialogComponent],
  exports: [ConfirmDialogComponent],
  entryComponents: [ConfirmDialogComponent],
})
class DialogTestModule { }`

**Comment by LOZORD** [comment]
Are you still getting that MdDialogRef error? Also, remember that since the dialog is in the overlay, if you use the strategy that I used, `fixture.nativeElement` won't contain the custom dialog -- you have to query off of `document`.

**Comment by ReneVallecillo** [comment]
Yes, once it reaches **create component** it throws:

> 	Error: No provider for MdDialogRef!
	Error: DI Error
	    at NoProviderError.BaseError [as constructor] (webpack:///~/@angular/core/src/facade/errors.js:31:0 <- src/test.ts:7487:27) [angular]

**Comment by LOZORD** [comment]
Why are you not importing your (I assume) `ConfirmDialogModule`?

**Comment by ReneVallecillo** [comment]
@LOZORD Since I'm running the dialog test isolated, and I was importing MdDialogModule on TestBed.configureTestingModule I think it is not needed. Plus my dialog it's on my shared module so I would just pollute it I think.

**Comment by ReneVallecillo** [comment]
It basically works, but once it finds <md-dialog-action> or any other subsection it gives errors
https://plnkr.co/edit/zo3B0p6gJeN0LTuPDPs4?p=preview

**Comment by LOZORD** [comment]
Importing `MdDialogModule` should fix that error.

This worked for me:

```ts
@NgModule({
    declarations: [TestComponent],
    imports: [MdDialogModule], // <-- added this line
    entryComponents: [TestComponent],
    exports: [TestComponent],
})
class TestModule { }
```

**Comment by fallXone** [comment]
The recommended workarounds in here haven't worked for me. Is there any update on this issue?

**Comment by LOZORD** [comment]
Can you share any relevant information or code? A Plunker really helps!

**Comment by ReneVallecillo** [comment]
It worked in the end for me @LOZORD 

Here is a full gist of it, using a shared module pattern. 

https://gist.github.com/ReneVallecillo/24e980c2a8442d9daaf187debd2d4369

Maybe @fallXone could use it.

Ignore js extension, it should be ts but it seems gist has no support of typescript

**Comment by u12206050** [comment]
I have a very similar issue in where I need to declare a component dynamically within a featured module. 
My featured module which is loaded async when route is visited looks as follows: 
```
@NgModule({
  imports: [
    SharedModule,
    FeaturedRoutingModule,
  ],
  declarations: [
    FeaturedComponent,
    DynamicComponent
  ],
  entryComponents: [ DynamicComponent]
})
export class FeaturedModule {}
```

I have another SharedModule where I import most of my site wide components most of them are entryComponents. I then have a Builder Service that is able to dynamically create a factory for each entryComponents using the ComponentFactory which works great for all components defined in the Shared and Main module but for the DynamicComponent that is only loaded with the dynamic module I get `No component factory found for DynamicComponent. Did you add it to @NgModule.entryComponents?` even though it is obviously defined in the entryComponents. Using the component statically in the FeaturedComponent template works but not when trying to create it dynamically.

**Comment by DzmitryShylovich** [comment]
@u12206050 
> My featured module which is loaded async when route is visited looks as follows:

you need to list your entry components in none lazy loaded module.

**Comment by u12206050** [comment]
@DzmitryShylovich The problem with that approach is then that the main/shared module (which are none lazy) will most likely contain all the entryComponents creating a very large bundle file instead of have smaller bundle files for each featured part of the app.

**Comment by DzmitryShylovich** [comment]
@u12206050 you can track that issue here https://github.com/angular/angular/issues/12275#issuecomment-274185155

**Comment by u12206050** [comment]
@DzmitryShylovich thanks, just to clarify does that mean that from the next release we'll be able to use entryComponents in lazy loaded modules?

**Comment by btinoco** [comment]
Can anyone share an example of how to test the MdDialog please... I am having issues testing the mdDialog with my code.  I tried the looking into the code of Angular material 2 but I cant get it to work (maybe I am not understanding the example).

**Comment by gonzofish** [comment]
@btinoco what are you struggling with? I've been able to get some unit tests with `MdDialog` working

**Comment by vikerman** [comment]
Needs investigation and we will propose a solution here.

**Comment by goldenbearkin** [comment]
does everyone confirm the workaround mentioned above is still workable?

**Comment by imchaitanya9** [comment]
@renevall did you tried like below?

in your configureTestingModule, 

```
providers : [
        { provide : MAT_DIALOG_DATA, useValue : {} },
        { provide : MatDialogRef, useValue : {} }
]
```

**Comment by zivc** [comment]
Any updates?

**Comment by mhevery** [comment]
Ivy does not make a distinction between AOT and JIT compiled code and as a result this is fixed.
