### ISSUE TITLE
Nested Dynamic Components Break With ComponentFactoryResolver

### ISSUE THREAD

**Issue by rbj325** [angular/angular#10762]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When trying to render nested dynamic components via the ComponentFactoryResolver I receive an exception/error message:

browser_adapter.js:84Error: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: 'null'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?

**Expected/desired behavior**

It should render the nested dynamic controls.  This had worked until the introduction of the ComponentFactoryResolver.  See:  https://plnkr.co/edit/JRyqou9yC6LvSRrCR3eA?p=preview

**Reproduction of the problem**

Here is the plunkr recreating the issue:  http://plnkr.co/edit/NzT4a7GEAB7k4yqeZrs0?p=preview

**What is the expected behavior?**

I should be able to render a control via ComponentFactoryResolver which in turn also renders multiple controls via ComponentFactoryResolver.

In my use case, I am rendering a form wizard made up of several dynamic components.  In one of those dynamic components I am pulling fields defined in the database to render a set of user controlled fields.

**What is the motivation / use case for changing the behavior?**

It used to work.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [all ]

**Comment by rbj325** [comment]
Plunker repro added.

**Comment by thecritic** [comment]
@rbj325 Have you been able to solve this ?

**Comment by rbj325** [comment]
@thecritic No, the only thing I've seen is to try to manually call ChangeDetectorRef.detectChanges manually but no matter where you do that the error persists.

**Comment by jpleclerc** [comment]
I have the same problem. I dynamically create a modal window and attach it to the app component. Then I dynamically create a component in the modal window. It crashes when loading the content of the modal.

**Comment by jpleclerc** [comment]
For anyone looking for a dirty hack, wrap your code in a setTimeout():

```
    public ngAfterViewInit(): any {
        if (this.isCustomContent) {
            setTimeout(() => {
                let modalFactory = this.componentResolver.resolveComponentFactory(<any>this.modalInstance.config.content);
                this.componentInstance = this.container.createComponent(modalFactory, null, this.injector);
                this.componentInstance.instance.modal = this;
                this.componentInstance.instance.options = this.modalInstance.config.options;
            }, 1);
        }
    }
```

**Comment by rbj325** [comment]
@jpleclerc That work around does not work for me because the dynamic form requires the control to be present when it's rendering.  It did remove the change detection error though.

**Comment by gluix** [comment]
Use the "AfterContentInit" lifecycle-hook to init/update your nested dynamic-component.

`
public ngAfterContentInit() {
  let modalFactory = this.componentResolver.resolveComponentFactory(<any>this.modalInstance.config.content);
  this.componentInstance = this.container.createComponent(modalFactory, null, this.injector);
}
`
updated your plunker:
http://plnkr.co/edit/EasYKceQTBC9yA4Xsma8?p=preview

**Comment by rbj325** [comment]
@gluix Awesome, I think that's the only life cycle hook I didn't try.

**Comment by RoyiNamir** [comment]
@gluix  - I know that `ngAfterContentInit` is called before `ngAfterViewInit` but why does it work when I put it in that location ? does it automatically do another cycle check  ( later ,inside ngAfterViewInit)?

**Comment by regosnet** [comment]
public ngAfterViewInit(): any {
    setTimeout(() => {
        let modalFactory = this.componentResolver.resolveComponentFactory(<any>this.modalInstance.config.content);
        this.componentInstance = this.container.createComponent(modalFactory, null, this.injector);
    }, 1);
}


That worked!

**Comment by imben1109** [comment]
I got a similar problem. It is finally solved by change **ngAfterViewInit to ngOnInit** or **add componentRef.changeDetectorRef.detectChanges()**

https://stackoverflow.com/questions/50539133/angular-create-dynamic-component-recursively/50539250?noredirect=1#comment88090372_50539250
