### ISSUE TITLE
RequestOptionsArgs with null body causes exception

### ISSUE THREAD

**Issue by scrivy** [angular/angular#10773]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
this.http.get("/api/v1/auth/user", {
  headers: this.jwtJsonHeaders
}
```
causes this exception
```
browser_adapter.js:84TypeError: Cannot read property 'toString' of null
    at Request.Body.text (body.js:44)
    at Request.getBody (static_request.js:141)
    at Observable._subscribe (xhr_backend.js:113)
    at Observable.subscribe (Observable.js:52)
    at Observable._subscribe (Observable.js:109)
    at MapOperator.call (map.js:54)
    at Observable.subscribe (Observable.js:52)
```
if you pass in an empty string for body, it'll work
```
this.http.get("/api/v1/auth/user", {
  headers: this.jwtJsonHeaders,
  body: ""
}
```
**Expected/desired behavior**

A null body for RequestOptionsArgs shouldn't cause an exception since get requests often don't contain a body.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [chrome  52.0.2743.116] 
 
* **Language:** [TypeScript]

**Comment by ericmartinezr** [comment]
Fixes here https://github.com/angular/angular/pull/10668
