### ISSUE TITLE
Safari won't render a template because a problems in zone.js

### ISSUE THREAD

**Issue by slavaspirit** [angular/angular#10778]
Safari browser won't render a template and throw errors... It seems, something goes wrong with `zone.js`: `ORIGINAL EXCEPTION: ReferenceError: Can't find variable: Intl`. In Chrome all works fine.
Safari error log attached...
[errors_in_zone.txt](https://github.com/angular/angular/files/416471/errors_in_zone.txt)

**Comment by DzmitryShylovich** [comment]
You need Intl polyfill

**Comment by slavaspirit** [comment]
Thank you!
