### ISSUE TITLE
Service provided to AppModule not behaving as a singleton

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#10779]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using ng2-Material, the `MdIconRegistry` service is provided to the root module only; however, module that gets loaded by the router asynchronously seems not to have access to it.

**Expected/desired behavior**
A service provided to the root module only should be accessible to the whole application, in a single instance

**Reproduction of the problem**
 - Open [this plunker](http://plnkr.co/edit/yNjE0hLNSPUSul859MKs?p=preview)
 - Notice that `MdIconModule` is imported as part of `MaterialModule` into the main `AppModule`
 - Notice that `MdIconRegistry` service is in the `providers` array of the main `AppModule`
 - Open the bootstrapped `AppComponent` and notice the call to `addSvgIconSet()` to register icons
 - In the template, `<md-icon svgIcon='ic_account_box_24px'>` is used to display the icon. In the view the icon is shown successfully above the nav bar.
 - Open `app/crisis-center/crisis.list.component` and open the Crisis Center in the view. 
 - Note in the template, the same `<md-icon>` is present. However, no icon is displayed above the crisis list in the view.  The DOM inspector from browser dev tools shows that the angular parser didn't even recognize it as an angular component (in the DOM, it's left exactly as in the code)

**What is the expected behavior?**
`<md-icon svgIcon='name'></md-icon>` referring to the same icon in the same sprite should behave the same throughout the app.

**What is the motivation / use case for changing the behavior?**
Behavior does not abide by the docs.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Firefox 48
 
* **Language:** TypeScript 1.9

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/guide/ngmodule.html#!#adding-services-with-_forroot_

**Comment by RoxKilly** [comment]
@DzmitryShylovich  Thanks. I've made the change (using `.forRoot()` to import services into `AppModule`) but that hasn't made any discernible difference.

See: http://plnkr.co/edit/yNjE0hLNSPUSul859MKs?p=preview

**Comment by RoxKilly** [comment]
A bit more info:
- This bug only affects lazy-loaded modules. If all my content is loaded at app launch, there is no problem.
- If a template component (component loaded via its selector in templates) is part of an eagerly loaded module, `<md-icon svgIcon=...>` will work but only if the template component is being used within an eagerly loaded module. If I include that same component in a template that was lazy-loaded, it's a no go.

I've built a much narrower Plunkr demonstrating the problem. You'll notice that the eagerly loaded components (`AppComponent` and `HomeComponent`) are able to display the icon. However, `LazyLoadedComponent` cannot.

[Here's the plunker](http://plnkr.co/edit/eCWl2Gop6Yx1yOnjlUzl?p=preview)

**Comment by thegreenpizza** [comment]
@RoxKilly @DzmitryShylovich I am experiencing the exact same problem. The question here is: is it possible to have App Root providers percolate to lazy loaded modules? I have not seen this discussed or documented anywhere except for this issue.

**Comment by RoxKilly** [comment]
@thegreenpizza  yes it's possible and [it's even documented](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#shared-module-for-root). A service in the `providers` array of the bootstrapped `AppModule` or a service imported into `AppModule` from the result of another module's `RouterModule.forRoot()` should be a singleton available to lazy-loaded modules. I already have several services that behave this way.

The `MdIconRegistry` is misbehaving

**Comment by RoxKilly** [comment]
I think this is an `Angular 2 Material` limitation, not an `Angular 2` bug. See https://github.com/angular/material2/issues/1071
