### ISSUE TITLE
virtual scroll using DOM recycling, tombstones and scroll anchoring.

### ISSUE THREAD

**Issue by istiti** [angular/angular#10776]
**I'm submitting a...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently without "material design" we using *ngFor but this consumming a lot memory and become slow when a lot of collection have to be shown and we have to detect scrollDown and scrollUp to add  items to our collection ... DOM is very poor and website block 

**Expected/desired behavior**
It will be nice if angular2 add a new feature to implement easy an virtual scroll using DOM recycling, tombstones and scroll anchoring. Like I see in google developers article : https://developers.google.com/web/updates/2016/07/infinite-scroller

thanks

**What is the motivation / use case for changing the behavior?**
TO do a speed site like facebook or twitter ....

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** chrome last on the date
 
* **Language:** TypeScript 1.8 | ES6

**Comment by fxck** [comment]
This will be part of material2 https://github.com/angular/material2/issues/823

Give it a year or two.

**Comment by pkozlowski-opensource** [comment]
Yeh, this is something that should be tackled by widget libs first. If there are enough common points we could pull them in the core in the future.

**Comment by istiti** [comment]
thanks does someone know if there is widget lib that enhance or add this functionality easy maybe with filter in *ngFor directive?!?!

Because the link I pasted is very complex to understand/produce...

thanks
