### ISSUE TITLE
Type NgSelectOption is part of the declarations of 2 modules: InternalFormsSharedModule and SharedModule!

### ISSUE THREAD

**Issue by ersandeepranjit** [angular/angular#10784]
I am getting this error, Could not find out the actual reason for this .

**Comment by michalstepien** [comment]
Please provide plnkr or ask on gitter.

**Comment by ersandeepranjit** [comment]
Application structure is huge  so couldn't figure out the exact code it raised from , So just need some idea about what could be the cause for the error.

**Comment by kara** [comment]
This sounds like a support request. You'll want to ask on Gitter or StackOverflow. Closing, as this isn't a bug or a feature request.

**Comment by Marcelh29** [comment]
This solved it for me: 

Add: import { ReactiveFormsModule } from '@angular/forms';  and @NgModule({
  imports: [.. ReactiveFormsModule, ...in App.Module.

Remove all REACTIVE_FORM_DIRECTIVES directives in components.

**Comment by Hegde0209** [comment]
This solution didn't work for me... Can anyone help me to find the solution?

**Comment by zoechi** [comment]
@Hegde0209  GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
