### ISSUE TITLE
Testing RC5: TestBed.TestModule's {provide: ... useValue: obj} clones obj; good tests fail

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10787]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request 
```

I know it seems impossible and I'm praying that I'm doing something incredibly and obviously stupid.

But my component gets an injected deep clone of the `useValue` object as in this scenario.

```
  fixture = TestBed.configureTestingModule({
      declarations: [ WelcomeComponent ],

      // WAT !?!  Appears to deep clone fakeUserService
      providers:    [ { provide: UserService, useValue: fakeUserService } ]
    })
```

which means changes to `fakeUserService` during the test have no effect on the actually injected service.

**Reproduction of the problem**

http://plnkr.co/edit/lBaHiAYXHKpDZihzTimg?p=preview

**What is the expected behavior?**

Expect the injected `UserService` to be the value that I provided, `fakeUserService`

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all] 
- **Language:** [all]

**Comment by thelgevold** [comment]
I have observed the same behavior. Definitely presents a challenge when mocking...

**Comment by thelgevold** [comment]
Except in my experience it's not a clone of the object, but rather an instance of the original service type. It seems to ignore the `useValue` part and instead inject the original type.

I tested this by "useValue"-ing a mock object of a different shape, but instead of the mock object, the original service surfaced inside the component after DI

**Comment by thelgevold** [comment]
I believe I encountered the same behavior when using a `useValue` to inject a mock object.

I came up with the following workaround that seems to work
```
let myService;
beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [MyComponent],
      providers: [MyService]
    });
  });

 beforeEach(async(() => {
   TestBed.compileComponents();
 }));

 beforeEach(inject([Injector], (injector) => {
   myService = injector.get(MyService);
 }))

 it('should trigger open', () => {
   spyOn(myService, 'open');
   var fixture = TestBed.createComponent(MyComponent);
   fixture.componentInstance.open(); // calls myService.open()
   expect(myService.open).toHaveBeenCalled();
 });
```

Notice that I am pulling out an instance of myService along the way instead of using the DI framework to provide the mock directly in the component.

**Comment by Whipgit** [comment]
I believe this is related to #10727 

MyComponent in TestBed.configureTestingModule can not be overridden.

You must use
```
TestBed.configureTestingModule({
      imports: [FormsModule, HttpModule],
      declarations: [LoginComponent],
    }).overrideComponent(LoginComponent, {
      set: {
        providers: [
          {provide: AuthenticationService, useClass: authServiceMock},
          {provide: Router, useClass: routerStub}
        ]
      }}
      ).compileComponents();
```
Thanks to @chris-jones-pixitmedia and @AshMcConnell

**Comment by vdzundza** [comment]
Is still unfixed?

**Comment by antonovicha** [comment]
Encounter the same issue (angular 2.4.1). Found workaround similar to https://github.com/angular/angular/issues/10787#issuecomment-241135411:

```
beforeEach(async(() => {
    let myServiceMock = {
      // init mock here if required
    };
    TestBed.configureTestingModule({
      declarations: [MyComponent],
      providers: [
        { provide: MyService, useValue: myServiceMock }
     ]
    });
  }));

  let myService;
  beforeEach(inject([MyService], (_MyService) => {
    myService = _MyService;
  }))

  it('should trigger open', () => {
    // Now you can mock/spy/etc on myService here
 });
```
That way `myService` instance is the same both in test and when injected into another service/component.

**Comment by startswithaj** [comment]
There any news on this issue? Why does it clone it?

**Comment by vikerman** [comment]
This is working as expected because the compiler tried to mimic the AOT setup where useValue values are cloned.

The workaround is to use an object with a prototype or use useFactory.

**Comment by StefanKern** [comment]
@Whipgit this should be added to the documentation. Please!
