### ISSUE TITLE
request: compiled template caching between AoT and Runtime

### ISSUE THREAD

**Issue by laco0416** [angular/angular#10785]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Angular has two compilers; `OfflineCompiler` and `RuntimeCompiler`.
At AoT compilation, each component is compiled by `OfflineCompiler`. Then its template is resolved statically. If a component uses `templateUrl`, `OfflineCompiler` reads the file. Its URL resolution depends on the **file system path**.

After that, on the browser, Angular provides `RuntimeCompiler` for JIT compilation. If some components needed JIT compilation, there is a problem. If a component has `templateUrl`, `RuntimeCompiler` fetches the resource. Its URL resolution depends on the **base path**.

There is a difference of the `templateUrl` processing. Even though those are the same component, it cannot be compiled on both phases.

**Expected/desired behavior**

At AoT compilation, the templates resolved from `template` or `templateUrl` are cached and those are used at JIT compilation. 

**What is the motivation / use case for changing the behavior?**

This is for dynamic component creation with AoT. 
I want to fetch only a template from the server and create a component dynamically.

relates: 
- https://github.com/angular/angular/issues/7596
- https://github.com/angular/angular/issues/9599

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by DzmitryShylovich** [comment]
@laco0416 is this still valid? Compiler is not available after aot compilation (usually)

**Comment by laco0416** [comment]
yes, but this is too old. I'll open new one when I want this again.
