### ISSUE TITLE
Support creating new factories with different dependencies

### ISSUE THREAD

**Issue by dustyrockpyle** [angular/angular#1078]
In angular 1.3 the source for the factory provider is as follows:

```
function factory(name, factoryFn, enforce) {
  return provider(name, {
    $get: enforce !== false ? enforceReturnValue(name, factoryFn) : factoryFn
  });
}
```

enforceReturnValue shadows the factoryFn from being exposed, which prevents doing something like:

```
module.config(function($provide, $injector, myFactoryProvider) {
  $provide.factory('myNewCoexistingFactory', function(){
    var newDependencies = {oldDependency: $injector.get('newDependency')};
    return $injector.invoke(myFactoryProvider.$get, null, newDependencies);
  });
});
```

I'd like it if factory passed something like {$get: ..., $factoryFn: factoryFn} to provider. 

Is this an acceptable change? If I'd be happy to submit a pull request.

Thanks.

**Comment by vicb** [comment]
This repo is for angular2, could you please re-open on https://github.com/angular/angular.js
