### ISSUE TITLE
[BUG] ngFor on <tr> with trackBy

### ISSUE THREAD

**Issue by marcalj** [angular/angular#10796]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
The first parameter of trackBy function is the index of the array, not the element of the array.

**Expected/desired behavior**
First parameter of trackBy function is the element of the list, not the index.

**Reproduction of the problem**
http://plnkr.co/edit/pDLJSRMP6oN8Sl4DqIvS?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [TypeScript]

**Comment by DzmitryShylovich** [comment]
It's by design. Why do u think first param should be an element instead of index?

**Comment by marcalj** [comment]
Jesus, I have all my ```trackBy``` functions assuming first parameter is the item of the array, and doesn't fail because returns undefined instead of error:

![image](https://cloud.githubusercontent.com/assets/63667/17650715/eaae84e8-6254-11e6-91ec-3679d07f3072.png)

:( :( :(

Thanks...
