### ISSUE TITLE
Wrong path to source map in rtts_assert.js

### ISSUE THREAD

**Issue by SekibOmazic** [angular/angular#1079]
In alpha.14 there is:

```Javascript
//# sourceMappingURL=/Users/yjbanov/code/angular/modules/rtts_assert/rtts_assert.map
```

in `rtts_assert.js`

(pulled from npm)

**Comment by mhevery** [comment]
What do you expect it to be?

**Comment by SekibOmazic** [comment]
Well, there is an absolute path to `/Users/yjbanov/code/...` 
Better would be  `//# sourceMappingURL=rtts_assert/rtts_assert.map` but I admit it's not a real issue.

**Comment by SekibOmazic** [comment]
This is actually not an issue. Will close now.
