### ISSUE TITLE
Doc: "live example" links in "Angular Modules (NgModule)" document shown as text only in IE 11

### ISSUE THREAD

**Issue by hhubik** [angular/angular#10799]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
"Try the live example." text is shown, but is not a hyperlink.

**Expected/desired behavior**
The text should be a link to plunker.

**Reproduction of the problem**
- in IE 11, open  https://angular.io/docs/ts/latest/guide/ngmodule.html#
- search for "try the live example"
![ngmoduledocexamplelink](https://cloud.githubusercontent.com/assets/14813201/17651183/67753fba-622f-11e6-808e-5eb5d3a38f68.PNG)

**Please tell us about your environment:**
Windows 8.1 x64

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [ IE 11 ]

**Comment by hhubik** [comment]
This works fine in Firefox/Chrome.

**Comment by DzmitryShylovich** [comment]
Docs repo is here https://github.com/angular/angular.io

**Comment by hhubik** [comment]
Closed and opened new issue in https://github.com/angular/angular.io
