### ISSUE TITLE
[regression of rc.5] Http Content-Type enforces a body

### ISSUE THREAD

**Issue by r-tt** [angular/angular#10793]
**I'm submitting a** 
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When header Content-Type is set the body  can't be null

**Expected/desired behavior**

Previously (until rc.4) it was possible to set Content-Type header for any request (post, get...) with or without a request payload it was ignored. Now in Request.prototype.getBody this can't be the case anymore and fails with a `toString can't be called on null`.

**What is the motivation / use case for changing the behavior?**

Would be great to support it since it simplifies the client code and avoid to have to maintain multiple shared header sets (for request with and without body).

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** 

Only tested on Chrome but suspect it affects all ones.
 
* **Language:**

Typescript 1.8 but same note as for browsers ;)

**Comment by DzmitryShylovich** [comment]
According to https://github.com/angular/angular/blob/7cd4741fcbbea6d58281b3055d1ae7691de1662b/modules/%40angular/http/src/body.ts#L52 body can be null. Request.prototype.getBody will return empty string in this case.
