### ISSUE TITLE
AoT Compiler does not work on Windows

### ISSUE THREAD

**Issue by sarunint** [angular/angular#10792]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On Windows, the `ngc` compiler does not emit `.ngfactory.ts` file, instead, it emits `.js`, `.js.map` and `.metadata.json` files. On Ubuntu, it works as expected.

**Expected/desired behavior**
`ngc` should produce `.ngfactory.ts` file.

**Please tell us about your environment:**
Windows 10 Professional, NodeJS v6.3.1 and v6.2.0

* **Angular version:** 2.0.0-rc.5
 
* **Language:** TypeScript@next

**Comment by michalstepien** [comment]
I have the same problem

**Comment by aloker** [comment]
Likewise here.

**Comment by kamarouski** [comment]
Same behaviour here.

**Comment by fillmorejl** [comment]
I have this same problem.

**Comment by ricklove** [comment]
Same problem, now at least I can stop pulling my hair out.

**Comment by jwhite1802** [comment]
Confirmed.  Also, why does it require a typescript version greater than 1.9.0 when the officially supported typescript version is 1.8.10?

**Comment by berwyn** [comment]
As a workaround for Windows 10 users, you can use node inside LXSS (more commonly Bash on Ubuntu on Windows) and the codegen seems to work correctly.

**Comment by ashu2k6k** [comment]
Same here not generating ngFactory.ts files.

**Comment by AAAnderson7301** [comment]
Will this be resolved in RC6?

**Comment by sarunint** [comment]
The fix for this issue (#10919) has been merged into the master branch. So I think it's gonna be fixed in RC6.

**Comment by ammar91** [comment]
It still not producing ` .ngfactory.ts `in RC6.

**Comment by AAAnderson7301** [comment]
@ammar91 I am having the same issue. Are you able to run the ngc command ? I am on windows and cannot...

**Comment by ammar91** [comment]
@AAAnderson7301 Yes, I'm able to ran it by providing an absolute path

> path/to/project/node_modules/.bin/ngc

**Comment by sarunint** [comment]
To run absolute path on the command prompt, put `"` around absolute path, like this:

    C:\path_to_your_project> "node_modules/.bin/ngc" -p

PS. Will take a look on RC.6 asap

**Comment by sarunint** [comment]
@ammar91 I tested RC6 and it worked. Can you try reinstall `@angular/compiler-cli`?

**Comment by ammar91** [comment]
@sarunint Do I need to upgrade typescript to 1.9.0-dev? This is what I'm getting when trying to run ngc

![screen](https://cloud.githubusercontent.com/assets/7683970/18200814/1e5d3a94-7120-11e6-96ad-9f7ec0afb01f.PNG)

**Comment by ammar91** [comment]
@sarunint I reinstalled `"@angular/compiler-cli": "0.6.0"` along with `"typescript": "^2.0.2"` and after installation complete, following npm warnings listed

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
> npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.

Then I run `"node_modules/.bin/ngc"` but it didn't produce the `ngFactory.ts ` file. Could be because due to the above npm warnings but not sure.

**Comment by AAAnderson7301** [comment]
@ammar91  What is the exact line you are running? I am curious as to what you are adding after the -p

**Comment by kylecordes** [comment]
Does anyone have an extra-simple example project (GH repo?) that shows the precompile process working (on Linux and Mac), but failing (on Windows), with the current-latest RC6?

**Comment by ammar91** [comment]
@AAAnderson7301 I just run `"node_modules/.bin/ngc"` and not using -p flag. Because when I do, it does nothing. Command run but doesn't output anything, nothing even` .js, .js.map, .metadata.json`

![screen](https://cloud.githubusercontent.com/assets/7683970/18203782/9524f4ac-7132-11e6-84ba-0a0d65acd885.PNG)

**Comment by AAAnderson7301** [comment]
@ammar91  In order to get the files generated here is my command. "node_modules/.bin/ngc" -p app  I specify the app folder because that is where my app.module lives.

**Comment by AAAnderson7301** [comment]
@kylecordes  I can throw one together this morning.

**Comment by mobilabgit** [comment]
I am on a Windows machine and followed the quickstart.
I added the lines   

```
"angularCompilerOptions": {
    "genDir": "./ngfactory"
  }
```

to the tsconfig file and ran without any parameters

`ngc`

First there was a problem with the typescript version. So I updated this in my package.json to:

`typescript": "^1.9.0-dev"`

Running the ngc command now created a folder named 'ngfactory', containing some ngfactory files.
However, the systemjs.config.js file was not altered so I had to fix some mappings to prevent 'file not found' errors.

Now I am at the point that there are still 'file not found' errors for imports that are done, for which there aren't any ngfactory files. Just to show a few:

```
import * as import36 from '@angular/core/src/i18n/tokens';
import * as import37 from '@angular/core/src/error_handler';
import * as import38 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import39 from '@angular/platform-browser/src/dom/animation_driver';
import * as import40 from '@angular/core/src/render/api';
import * as import41 from '@angular/core/src/security';
import * as import42 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import43 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import44 from '@angular/core/src/linker/ng_module_factory_loade
```

These are all imported from my app.module.ngfactory.ts file. But I just don't have any factory files for those imports in my ngfactory folder.

**Comment by mobilabgit** [comment]
I am using RC6 btw

**Comment by AAAnderson7301** [comment]
@kylecordes  here is a basic github with AOT. https://github.com/AAAnderson7301/rc6AOT  
The only thing I changed fromt he quickstart download was the main.ts file. Also ran the following commands 
1. npm install @angular/compiler-cli typescript@next @angular/platform-server @angular/compiler
2. "node_modules/.bin/ngc" -p app

**Comment by kylecordes** [comment]
Thank you, I'm going to see if I can reproduce the problem from this issue, I have found that the more different people reproduce a problem and potentially point out a clue, the more likely it gets fixed quickly.

**Comment by ammar91** [comment]
@AAAnderson7301 Thanks, It now produce `ngFactory.ts` by running `"node_modules/.bin/ngc" - app` but getting a log of error as well. Any thoughts?

![screen2](https://cloud.githubusercontent.com/assets/7683970/18204997/217052f2-7139-11e6-9e8d-bd88290900df.PNG)

**Comment by AAAnderson7301** [comment]
@ammar91  I am working through those errors as we speak. I am even getting them on the most basic project. Clean build with JIT and once I switch to AOT I get those. I am guessing they have been there all along and the browser has been hiding them.?

**Comment by ammar91** [comment]
@AAAnderson7301 Yes. I build the quickstart in JIT mode and it works. Then switch to AOT and get those And when I run the application, I'm getting these errors

![screen3](https://cloud.githubusercontent.com/assets/7683970/18205414/47e084e6-713b-11e6-997e-37665e6fec05.PNG)

**Comment by kylecordes** [comment]
@AAAnderson7301 I captured the commands above in the scripts in the repo, see my fork:

https://github.com/kylecordes/rc6AOT

With this fork, and 'npm run aot', I get the same errors as @ammar91  above. On my Mac. I recognize some of those errors as problems that I've seen in other projects as we upgrade versions, related to the version of typescript being used. Going to tinker with that, I don't see any reason to blame Windows until we have a correct working result on non-Windows.

**Comment by AAAnderson7301** [comment]
@kylecordes  Agreed! Thank you for running on Mac. I have tried to install the version of typescript it says in the error but still nothing. It said ^2.0.2 . That must be wrong the last stable version is 1.8.10

**Comment by kylecordes** [comment]
Okay, more results. You can see what I did in the following commit.

https://github.com/kylecordes/rc6AOT/commit/8fee7d1725db8b5e272a838409d9c56bc1edd2c9

The problem here is not with Windows at all, it is that we do not have a working starting project to investigate. The command you've been running had trouble because NGC requires that if you pointed to a certain directory as the "project", that is the directory where the tsconfig must reside. I thought that a bit, and got NGC to run cleanly. The project won't run now, because this QuickStart project is set up with an unusual system config to make it "easy" to use the UMD bundles. There is probably some way to both use those bundles and load the generated factories, but I don't have an answer for that in front of me.

I'm stepping away to other things for the moment, but I think it should be possible to investigate this problem much more effectively if we get something other than the Quickstart, maybe if we started with some very minimal webpack based project. (I would not recommend trying to investigate a problem like this with a typical "starter kit" project, most of those contain a very substantial amount of configuration complexity which makes it hard to zero in on specific narrow problems.)

**Comment by kylecordes** [comment]
@AAAnderson7301 By the way, current Angular 2 requires much newer typescript than 1.8.10. I believe RC6 actually needs 2.0.2.

**Comment by jbalbes** [comment]
I got the AOT compiler to work on windows on rc6. Here is the repo with my code:

https://github.com/jbalbes/angular2-aot-webpack

**Comment by kylecordes** [comment]
Jack's thing works for me also. Seems to me this issue is correctly closed, it works on Windows.

**Comment by sarunint** [comment]
Mine also works correctly.

**Comment by gdyrrahitis** [comment]
Mine doesn't work, it does not produce the *.ngfactory.ts file, just only the metadata and .js files from the .ts
Windows 10 professional, x64.
NodeJS: 4.4.5
Typescript: 1.9.0-dev.20160627-1.0
@angular/compiler: ^2.0.0-rc.6
@angular/compiler-cli: ^0.5.0

Also, why it does complain with Typescript versions other than 1.9.0-dev?

Haven't tried yet @jbalbes repo though, will try and come back to confirm it.

**Comment by sarunint** [comment]
@gdyrrahitis upgrade `@angular/compiler-cli` to `0.6.0`

**Comment by gdyrrahitis** [comment]
Thanks @sarunint, it works

**Comment by tianyuanzhonglu** [comment]
ngc generate js files what I don't want.

ngc 0.6.0@windows 7

`.\node_modules\.bin\ngc -p tsconfig.aot.json`

```js
tsconfig.aot.json

{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": false,
    "emitDecoratorMetadata": false,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": true
  },
  "exclude": [
    "node_modules",
    "typings"
  ],
  "angularCompilerOptions" : {
    "skipMetadataEmit": true
  }
}
```


example: app.module.ts

app.module.ts =>
app.module.js
app.module.ngfactory.ts
app.module.ngfactory.js

I only want app.module.ngfactory.ts, but lots of js files also generated. When run `webpack` at next stage, webpack(ts-loader + another tsconfig.json) will choose js file first (not ts). Because of `"module": "es2015"` setting in tsconfig.aot.json, webpack not recognize ES2015 `import` syntax in generated js files.

How could I generate ngfactory.ts file only?

**Comment by byungjuJin** [comment]
I had a same problem and solved it.
So I share this.

check version of your compiler-cli & compiler
- C:\path_to_your_project\node_modules\@angular\compiler-cli\package.json
- C:\path_to_your_project\node_modules\@angular\compiler\package.json
it should be match each other.

if compiler-cli got different version, install again with specific version
`npm install @angular/compiler-cli@{your compiler version}`

**Comment by Kopleman** [comment]
Have same problem that, got comiler-cli and compiler 2.4.0

**Comment by k-paxian** [comment]
comiler-cli 2.4.1 same here.

`Error: Could not resolve module @angular/core/src/di/opaque_token relative to undefined
    at ReflectorHost.findDeclaration (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\reflector_host.js:96:23)
    at StaticReflector.initializeConversionMap (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\static_reflector.js:133:38)
    at new StaticReflector (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\static_reflector.js:34:14)
    at Function.CodeGenerator.create (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\codegen.js:134:31)
    at codegen (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\main.js:7:36)
    at Object.main (D:\Projects\ngc-test\node_modules\@angular\tsc-wrapped\src\main.js:25:16)
    at Object.<anonymous> (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\main.js:12:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
Compilation failed`

**Comment by byungjuJin** [comment]
when you do "npm install",
did you open CMD with administrator mode?
but I did not test on 2.4.x

**Comment by ardiadrianadri** [comment]
Hello:

 I've the same issue with Angular 2.4.2:
```
can't resolve module @angular/core/src/di/opaque_token from /vagrant/testGenerator/node_modules/@bankinter/development-tools/config/application/index.ts
TypeError: Cannot read property 'parse' of undefined
    at ReflectorHost.normalizeAssetUrl (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/reflector_host.js:54:43)
    at ReflectorHost.findDeclaration (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/reflector_host.js:151:33)
    at StaticReflector.initializeConversionMap (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/static_reflector.js:145:38)
    at new StaticReflector (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/static_reflector.js:42:14)
    at Function.CodeGenerator.create (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/codegen.js:92:31)
    at codegen (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/main.js:7:36)
    at Object.main (/vagrant/testGenerator/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/main.js:16:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
Compilation failed
can't resolve module @angular/core/src/di/opaque_token from /vagrant/testGenerator/node_modules/@bankinter/development-tools/config/application/index.ts
TypeError: Cannot read property 'parse' of undefined
    at ReflectorHost.normalizeAssetUrl (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/reflector_host.js:54:43)
    at ReflectorHost.findDeclaration (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/reflector_host.js:151:33)
    at StaticReflector.initializeConversionMap (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/static_reflector.js:145:38)
    at new StaticReflector (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/static_reflector.js:42:14)
    at Function.CodeGenerator.create (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/codegen.js:92:31)
    at codegen (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/main.js:7:36)
    at Object.main (/vagrant/testGenerator/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/vagrant/testGenerator/node_modules/@angular/compiler-cli/src/main.js:16:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```
Operative system Ubuntu 16.04
nodejs: 6.9.4

This is my package.json:
```
{
  "name": "my-test",
  "version": "1.0.0",
  "description": "A simple starter MyTest project",
  "dependencies": {
    "@angular/common": "~2.4.2",
    "@angular/core": "~2.4.2",
    "@angular/forms": "~2.4.2",
    "@angular/http": "~2.4.2",
    "@angular/platform-browser": "~2.4.2",
    "@angular/platform-browser-dynamic": "~2.4.2",
    "@angular/router": "~3.4.2",
    "angular2-in-memory-web-api": "0.0.21",
    "core-js": "^2.4.1",
    "ie-shim": "^0.1.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "~0.6.26"
  },
  "devDependencies": {
    "@angular/compiler": "~2.4.2",
    "@angular/compiler-cli": "~2.2.4",
    "@angular/platform-server": "~2.2.1",
    "@types/core-js": "^0.9.34",
    "@types/jasmine": "^2.5.38",
    "@types/node": "^6.0.48",
    "@types/selenium-webdriver": "^2.53.35",
    "angular2-router-loader": "^0.3.4",
    "angular2-template-loader": "^0.6.0",
    "awesome-typescript-loader": "^2.2.4",
    "codelyzer": "^1.0.0-beta.4",
    "conventional-changelog-cli": "^1.2.0",
    "css-loader": "^0.26.0",
    "del": "^2.2.2",
    "extract-text-webpack-plugin": "^2.0.0-beta.4",
    "file-loader": "^0.9.0",
    "glob": "^7.1.1",
    "gulp": "git+https://github.com/gulpjs/gulp.git#4.0",
    "gulp-pug": "^3.1.0",
    "gulp-sass": "^2.3.2",
    "gulp-sourcemaps": "^2.2.0",
    "gulp-typescript": "^3.1.3",
    "html-loader": "^0.4.4",
    "html-webpack-plugin": "^2.24.1",
    "jasmine-core": "^2.5.2",
    "karma": "^1.3.0",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.2.1",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.8.0",
    "merge2": "^1.0.2",
    "node-sass": "^3.13.0",
    "npm-check-updates": "^2.8.6",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.13",
    "postcss-cssnext": "^2.8.0",
    "postcss-loader": "^1.1.1",
    "protractor": "^4.0.11",
    "pug-html-loader": "^1.0.9",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.4",
    "run-sequence": "^1.2.2",
    "sass-loader": "^4.0.2",
    "shelljs": "^0.7.5",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.5",
    "ts-loader": "^1.2.2",
    "tslint": "^3.15.1",
    "tslint-loader": "^2.1.5",
    "tslint-stylish": "^2.1.0-beta",
    "typescript": "2.0.10",
    "undertaker-registry": "^1.0.0",
    "url-loader": "^0.5.7",
    "webpack": "2.2.0-rc.3",
    "webpack-dev-server": "2.2.0-rc.0",
    "webpack-merge": "^0.17.0",
    "webpack-node-externals": "^1.5.4"
  }
}

```

**Comment by tstankevicius** [comment]
For 'can't resolve module @angular/core/src/di/opaque_token' error check if you have "moduleResolution": "node" defined in your tsconfig.json.
It got fixed to me after adding that.

**Comment by ardiadrianadri** [comment]
Thx @tstankevicius for the answer.

The 'moduleResolution' of my tsconfig.json is already set to 'node':

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "dist",
    "rootDir": ".",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "lib": ["es5", "dom"]
  },
  "exclude": [
    "node_modules"
  ],
  "awesomeTypescriptLoaderOptions": {
    "useWebpackText": true
  },
  "angularCompilerOptions": {
    "debug": false
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
```
The problem must be in other place

**Comment by tstankevicius** [comment]
I only started receiving that error when I enabled tree shaking by setting module property to es2015. Before that when I had commonjs AoT used to work fine. But I did not have moduleResolution set at all. Though I doubt if it will help in your case...
