### ISSUE TITLE
ng-routeprovider behaviour

### ISSUE THREAD

**Issue by arunsadhasivam** [angular/angular#10798]
trying to call spring mvc from angular.
the issue is it cache the values . i.e i will ng-view and when i try to form a different view based on route it should hit spring mvc each time. since i hit db to fetch results. since it caches the view. it is not showing updated values from db. Please advice on this.
when i hit the controller using ANgular js it is triggering the spring mvc controller first time . once called when i hit for the next time it is not calling springmvc . i want to set behaviour each time i call it should hit spring mvc. 
@Controller(value="patientController")
@RequestMapping("/savePatientDetails")
	public ModelAndView savePatient(Model model,HttpServletRequest req) {
		Mainroot root= (Mainroot)req.getAttribute("root");
		int resut = patientService.insert(root);
		String message ="Uploaded Sucessfully...";
		if(resut == 0){
			message ="HL7 insertion Failed...";
		}
		req.setAttribute("message",message);
		req.getSession().setAttribute("message",message);
		ModelAndView mv = new ModelAndView();
		mv.addObject("message", message);
		mv.setViewName("/main.jsp");
		
		return mv;
	}

var contextPath = "${pageContext.request.contextPath}";
var app = angular.module("mainApp", ["ngRoute"]);
app.controller('ctrlMain',function($routeProvider) {
	
    $routeProvider
	.when("/hl7Upload", {
	       templateUrl : contextPath+"/getHL7Details.htm"
	 })
    .when("/patientDetails", {
		controller  : 'patientController',
		templateUrl :  contextPath+"/getPatientDetails.htm"
    })
    .when("/insuranceDetails", {
		controller  : 'patientController',
        templateUrl : contextPath+"/getPatientInsuranceDetails.htm"
    })
  .when("/diagnosisDetails", {
	  	controller  : 'patientController',
        action : contextPath+"/getPatientDiagnosisDetails.htm"
    })
  .when("/clientInfoDetails", {
	  	controller  : 'patientController',
        action : contextPath+"/getClientInfo.htm"
    })
  .otherwise({
		 controller  : 'patientController',
         templateUrl :  contextPath+"/getHL7Details.htm" 
    });
});

**Comment by ericmartinezr** [comment]
This repo is for ng2, you are looking for this one https://github.com/angular/angular.js. Anyway, the repo is not for this kind of issues, you should ask in stackoverflow

**Comment by arunsadhasivam** [comment]
Thanks
