### ISSUE TITLE
[Disscussion] Internationalization API issues.

### ISSUE THREAD

**Issue by laskoviymishka** [angular/angular#10809]
Per @vicb this issue is mostly to summarize issues about Intl.API.
Currently our formatting pipes (Number and Date) highly coupled to Intl.Api, and this api have some known issues. From top overview it could be aggregated in following groups:

1) Compatibility issues between browsers. Some browser have limited support for Intl.Api (IE11, Edge), some browser not support it at all (IE8-10, Safari). Most of this issue can be easily resolved by adding proper pollyphil, but this point is not well informed (possible documentation issue).

Here list of compatibility issues:
- #9524 Issue with formatting minutes and second in IE11 and Edge . Chakra implementation of Intl.API little bit strange, so by some reason not allow to developer format date as single Minute or Second, that is required, by current implementation of date Pipe. As far as i know this is cannot be fixed by simply adding polyphil
- #10764 #10509 #10345 #8585 #8116 #7612 #7598 #7396 #7008 #6736 #6009 #4445 and #3333. Issue with safari and mobile browser. Most of this issues already closed, but regulary we faced with new version of same issue again and again. Latest issue with that was created 2 days ago.

2) Missed api. Some of requested feature could not be implemented upon standard Intl.API and require some additional implementation, which could be inconsistence with Intl.Api.

Here is a list of such issues:
- #9324 - allow pass timezone as parameter. Current implementation of DatePipe allow to us implement basic time changing, but there will be some troubles with displaying name of specified time zone (current Intl.Api not allow us to do it).
- #7590 - add milliseconds support. This is not exist in Intl.Api but rather simple. If we implement just displaying it in A1 way no one harm, but we become inconsistence with Itnl.Api.
- #6724 - some symbols for currencies not exist in standard Intl.Api. It only contain most common used symbols.

3) Just few honorable mentions:
- #3429 - this one is not clearly related to Intl.Api, but still need to be mentioned. Right now we not quite flexible with our locale, from this point Intl.Api just fine. This issue is mostly aroung global locale setting for angular app and related to #9104.
- #9104 - this one is just aggregation for [i18n] component. Right now your own code internationalization and angular system internationalization is 2 big difference. They not even correlated.

So right now there is a question - should we stand for Intl.Api and be consistence with it, or abondon Intl.Api and start to work with our own implementation for internationalization, so angular [i18n] module become more consistence.

Standing on Intl.Api, will lead to feature loss, since some of them not possible to implement with that api.

Implementing our own implementation of  [i18n] is pretty much like A1 way, with main benefit - full control of Api, but yet there is an issues - we will have to think how to integrate this into current app bundles, and more over it requires some additional work. But we could implement this as part of #9104 [i18n] module, so it will fit in current A2 apps nicely.

**Comment by kylecordes** [comment]
Suggestions related to this:

* Prominently located (on angular.io), clear statement of intended browser/version compatibility / support.
* Make the first party published (i.e. on angular.io) quickstarts/examples/etc include any necessary polyfills or other accommodations, to work across the list of supported browsers.
* Make the official-endorsed CLI create projects, by default, which work across the list of supported browsers.
* Gently urge the community to do the same, to increase the chances that people who pick up initial A2 examples from places other than angular.io, also by default include any necessary accommodations to work across the list of supported browsers.

**Comment by ericmartinezr** [comment]
Fwiw a warning in the docs has been added, see the PR https://github.com/angular/angular.io/pull/1999. You can check the website in the docs for pipes 

>The Date and Currency pipes need the ECMAScript Internationalization API. Safari and other older browsers don't support it. We can add support with a polyfill.

**Comment by vicb** [comment]
@laskoviymishka thanks for initiating this issue. I'm back at work today and will take a look.

**Comment by Martin-Wegner** [comment]
Any news?

**Comment by DzmitryShylovich** [comment]
There's a lightweight alternative to moment.js - https://date-fns.org/

**Comment by pkozlowski-opensource** [comment]
After going over issues touching i18n-related pipes (mostly date / time formatting one) I'm more and more convinced that the current way of providing custom formats on top of `Intl` API is a dead end. There is a proposal that aims at addressing custom formats as part of the `Intl` API (https://github.com/zbraniecki/proposal-intl-formatToParts) and when implemented (or sth similar) would allow us to have proper solution). The current approach of parsing output of the `Intl` API is flawed and the #12632 is the best prof of this.

I'm not sure what the best approach is and open options include:
* pushing standardization of `formatToParts` and suggesting a polyfill till then
* dropping `Intl` API in favour of sth else (hand rolled solution or well-known library like moment.js)

I'm still gathering all the issues and listing open options but till this process is over and it is clear what are the next steps  we won't merge any new PRs that change API surface.

**Comment by DzmitryShylovich** [comment]
> hand rolled solution

don't think it will be better than Intl :)

**Comment by laskoviymishka** [comment]
@pkozlowski-opensource using moment js is not a good option for a common piece of framework, neither hand rolled solution would not work. `DateTimeFormat.prototype.formatToParts` looks really promising, but for now it easier to just implement you own pipe on top of moment js rather than jumping around `Intl` api and built-in date pipe. May be it worth to extract all this formatting pipes from common to something more flexible as a separate npm package, so it could update more frequently.

**Comment by ocombe** [comment]
Just a quick update, it has been decided that we will replace the intl api with our own implementation. I'm working on it right now.

**Comment by mlc-mlapis** [comment]
@ocombe What you exactly mean by that. Do you mean various intl api in browsers?

**Comment by ocombe** [comment]
Currently angular uses the intl api from the browsers to format dates / numbers / ... (most of the pipes use it). It has many issues and the browsers have different implementations, which means that it requires a polyfill. But still, a lot of features are missing.
What I'm working on: extracting the data from the [CLDR project](http://cldr.unicode.org/) and updating the pipes to use these data instead of the intl api. This will be a breaking change, because some formats might change (intl did a lot of things that we couldn't control), and it will require an extra provider to define at bootstrap. Which means that it will be in v5 if I can finish the PR in time.

**Comment by martinmcwhorter** [comment]
Another suggestion -- Number and Currency format of "Large" numbers. 

JSON and JavaScript numbers are limited to signed 32bit numbers. When precision is needed these numbers must be transmitted as strings. 

The Intl.NumberFormat(...).format(...) constructor/methods do not work with unformulated string representations of large numbers without first casting them to `number`.

Ideally whatever replacement would work with string representations of numbers without any type cast. 

Currently: 
```
    console.log(new Intl.NumberFormat('en-GB').format("1234567890123123234.324"));
    1,234,567,890,123,120,000
```

Desired:
```
   newNumberMethod("1234567890123123234.324");
   1,234,567,890,123,120,234.324
```
