### ISSUE TITLE
[RC5][bug report]"Multiple Components" Error With Nested "router-outlet"

### ISSUE THREAD

**Issue by liuxue0905** [angular/angular#10805]
**I'm submitting a ...**  (check one with "x")
```
[#] bug report
```

Use official DEMO:
https://angular.io/resources/live-examples/router/ts/plnkr.html
1.Modify /index.html:
````
<!--<script>document.write('<base href="' + document.location + '" />');</script>-->
<base href="/"/>
````
2.Add Custom Component:
custom-hero-detail.component.ts
````

import { Component, Input } from '@angular/core';

// import { Hero } from './hero';

@Component({
  selector: 'custom-hero-detail',
  template: `
    <div *ngIf="hero">
      <h2>{{hero}} details!</h2>
      <div><label>id: </label>{{hero}}</div>
      <div>
        <label>name: </label>
        <input [(ngModel)]="hero" placeholder="name"/>
      </div>
    </div>
  `
})
export class CustomHeroDetailComponent {
  @Input()
  hero: String;
}
````
3.Modify (Use custom-hero-detail)
3.1 Modify /crisis-center/crisis-detail.component.ts
````
@Component({
  template: `
  <custom-hero-detail [hero]="'abcdefg'"></custom-hero-detail>  <==HERE~
  <div *ngIf="crisis">
    <h3>"{{editName}}"</h3>
    <div>
      <label>Id: </label>{{crisis.id}}</div>
    <div>
      <label>Name: </label>
      <input [(ngModel)]="editName" placeholder="name"/>
    </div>
    <p>
      <button (click)="save()">Save</button>
      <button (click)="cancel()">Cancel</button>
    </p>
  </div>
  `,
  styles: ['input {width: 20em}']
})
````
3.2 Modify /heroes/hero-detail.component.ts
````
@Component({
  template: `
  <custom-hero-detail [hero]="'abcdefg'"></custom-hero-detail>  <==HERE~
  <h2>HEROES</h2>
  <div *ngIf="hero">
    <h3>"{{hero.name}}"</h3>
    <div>
      <label>Id: </label>{{hero.id}}</div>
    <div>
      <label>Name: </label>
      <input [(ngModel)]="hero.name" placeholder="name"/>
    </div>
    <p>
      <button (click)="gotoHeroes()">Back</button>
    </p>
  </div>
  `
})
````
4.Import & declaration
````
/app.module.ts
import { CustomHeroDetailComponent } from './custom-hero-detail.component';
declarations:[
  ...
  CustomHeroDetailComponent
  ...
]
````

**Current behavior**
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'hero' since it isn't a known property of 'custom-hero-detail'.
1. If 'my-hero-detail' is an Angular component and it has 'hero' input, then verify that it is part of this module.
2. If 'my-hero-detail' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
    <custom-hero-detail [ERROR ->][hero]="'abcdefg'"></custom-hero-detail>
    <h2>CRISIS CENTER</h2>
    <router-outlet></router-outlet>
"): CrisisCenterComponent@1:20

**Expected/desired behavior**
We know~

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome 47] 
 
* **Language:** [TypeScript 1.8.10 | ES6/7 ]

**Comment by brandonroberts** [comment]
Modules are only aware of what you have in `declarations` or what's made available from another `NgModule`'s exports. If you want to use that component.

The `Hero` module and the `CrisisCenter` module have no knowledge of the `custom-hero-detail` component just because you add it to the `AppModule`. If you wanted to share that component between the other two modules, you need to create a shared `NgModule`, add that component to its `exports` array and add that shared module to the `Hero` and `CrisisCenter` module's `imports` array

**Comment by rbj325** [comment]
@brandonroberts My real implementation has the wizard, dcl-wrapper and dynamic-fields components all in a shared module setup exactly as you described.  The problem persists.  The repro plunk is a minimal recreation of the problem.

**Comment by liuxue0905** [comment]
Did not work.
AppModule:do not import CustomHeroDetailComponent
HeroesModule&CrisisCenterModuleModule:import CustomHeroDetailComponent
````
EXCEPTION: Error: Uncaught (in promise): Type CustomHeroDetailComponent is part of the declarations of 2 modules: HeroesModule and CrisisCenterModule!
````

**Comment by brandonroberts** [comment]
Here is an example plunker that works with what you were trying to do. 

http://plnkr.co/edit/ReW2AkAVlbwToDoyBHlA?p=preview

Key files:

`app/custom-hero-detail.component.ts` - The custom hero detail component

`app/shared.module.ts` - This file declares and exports the `CustomHeroDetail` component

`app/crisis-center/crisis-center.module.ts` - Imports the `SharedModule` and adds it to `imports` so it has access to the `CustomHeroDetail` component

`app/heroes/heroes.module.ts` - Imports the `SharedModule` and adds it to `imports` so it has access to the `CustomHeroDetail` component

**Comment by liuxue0905** [comment]
It worked so well and pretty!
The Key Point is import by Module?

**Comment by brandonroberts** [comment]
Yep. Sharing components/pipes/directives across multiple modules is done through a module, and not declarations

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
