### ISSUE TITLE
Component names in ngModules

### ISSUE THREAD

**Issue by damiandennis** [angular/angular#10801]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Before ngModules each component could pick which components it wishes to use so that the component name did not matter, now that everything is mixed in together, how does ngModule isolate the component name, for example I am using two third party components, both use the same name as the component "modal", I cant isolate one from the other.

**Expected/desired behavior**
To be able to isolate ngModule component names, maybe a prefix on the used component name e.g 

```html
<ng2-bs3-modal.modal></ng2-bs3-modal.modal>
```

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
Isolation of the component names via ngModules.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by ootwch** [comment]
Is this also what you mean: "Modules MUST NOT conflict, even if the use the same selector".

I had this working without problems in RC4, failed to get it working in RC5.

Plnkr RC 4: http://plnkr.co/edit/aXQ6ZVYxVEqYPc52lWQs?p=preview
Plnkr RC 5: http://plnkr.co/edit/rL3PskSZ4TJLZUjc0BAP

Challenge: Get the RC 5 version working _without_ changing anything in the 'third party' folder...

**Comment by damiandennis** [comment]
yup exactly what I meant.

**Comment by wardbell** [comment]
Seems to me that this is working as intended. You don't _really_ want two components fighting over the same selected element.  Either `RedThing` or `GreenThing` should go into the element `<colored-thing>`, not both.

The solution is create _Feature Modules_ as discussed in the [Angular Modules](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#feature-modules) chapter.

@ootwch  Here is my [updated version of your plunker](http://plnkr.co/edit/lul0LHylFU7zaHoOFOHi?p=preview) to show you what I mean

**Comment by damiandennis** [comment]
sorry not sure I understand, if there are two third party libraries that use the same selector for their components as the other and I need to use both (weird but true in my case), what control do I have over their selectors. It would be good to be able to give them a namespace so that I can use both side by side, not sure if the above examples covers the use case I providing.

**Comment by ootwch** [comment]
Thanks wardbell - your plunker cleared some things up. Mainly to add CommonModule everywhere and to watch the exports.

As with @damiandennis ' comment above, your re-edit of the plunker did not quite cover the use case I had in mind. For me the 'green-list-module' and 'red-list-module' are the wrappers around a third party component that does not provide modules yet (or alternatively part of the third party component...).

Under these circumstances the order of import is a bit different, but it still works: http://plnkr.co/edit/WwKtgRTkW3xgfPnfnNnq?p=preview

@damiandennis : In this plunker I have two 'third-party' components that use the same selector, and it seems to work as expected. Would you agree?

**Comment by damiandennis** [comment]
Ah, get it now, its quite verbose but I can see how it works.
