### ISSUE TITLE
Getting Attempted to assign to readonly property on safari

### ISSUE THREAD

**Issue by skunheal** [angular/angular#10815]
He,

Im currently finishing an angular 2 and see some wierd behaviour on Safari I cant explain. I'm Working on El Captian, safari 9.1.

I get a fair amount of errors 

> [Error] EXCEPTION: TypeError: Attempted to assign to readonly property.
> [Error] STACKTRACE:
> 
> [Error] setProperty@http://localhost/hyposhop-staging/bundle.js:19186:79
> setElementProperty@http://localhost/hyposhop-staging/bundle.js:18424:39
> detectChangesInternal
> detectChanges@http://localhost/hyposhop-staging/bundle.js:26820:40
> detectContentChildrenChanges@http://localhost/hyposhop-staging/bundle.js:26836:51
> detectChangesInternal
> detectChanges@http://localhost/hyposhop-staging/bundle.js:26820:40
> detectContentChildrenChanges@http://localhost/hyposhop-staging/bundle.js:26836:51
> detectChangesInternal
> detectChanges@http://localhost/hyposhop-staging/bundle.js:26820:40
> detectContentChildrenChanges@http://localhost/hyposhop-staging/bundle.js:26836:51
> detectChangesInternal
> detectChanges@http://localhost/hyposhop-staging/bundle.js:26820:40
> detectContentChildrenChanges@http://localhost/hyposhop-staging/bundle.js:26836:51
> detectChangesInternal
> detectChanges@http://localhost/hyposhop-staging/bundle.js:26820:40
> detectViewChildrenChanges@http://localhost/hyposhop-staging/bundle.js:26841:48
> detectChangesInternal
> detectChanges@http://localhost/hyposhop-staging/bundle.js:26820:40
> detectViewChildrenChanges@http://localhost/hyposhop-staging/bundle.js:26841:48
> detectChangesInternal@http://localhost/hyposhop-staging/bundle.js:26832:40
> detectChanges@http://localhost/hyposhop-staging/bundle.js:26820:40
> detectChanges@http://localhost/hyposhop-staging/bundle.js:12418:79
> http://localhost/hyposhop-staging/bundle.js:10217:98
> forEach@[native code]
> tick@http://localhost/hyposhop-staging/bundle.js:10217:46
> http://localhost/hyposhop-staging/bundle.js:10123:130
> invoke@http://localhost/hyposhop-staging/node_modules/angular2/bundles/angular2-polyfills.js:349:34
> onInvoke@http://localhost/hyposhop-staging/bundle.js:10559:48
> invoke@http://localhost/hyposhop-staging/node_modules/angular2/bundles/angular2-polyfills.js:348:43
> run@http://localhost/hyposhop-staging/node_modules/angular2/bundles/angular2-polyfills.js:242:50
> runInner@http://localhost/hyposhop-staging/bundle.js:10590:75
> run@http://localhost/hyposhop-staging/bundle.js:10487:75
> http://localhost/hyposhop-staging/bundle.js:10123:105
> http://localhost/hyposhop-staging/bundle.js:8573:57
> __tryOrUnsub@http://localhost/hyposhop-staging/bundle.js:9322:21
> next@http://localhost/hyposhop-staging/bundle.js:9271:35
> _next@http://localhost/hyposhop-staging/bundle.js:9221:31
> next@http://localhost/hyposhop-staging/bundle.js:9185:24
> _finalNext@http://localhost/hyposhop-staging/bundle.js:8787:35
> _next@http://localhost/hyposhop-staging/bundle.js:8779:29
> next@http://localhost/hyposhop-staging/bundle.js:8736:20
> emit@http://localhost/hyposhop-staging/bundle.js:8562:81
> _checkStable@http://localhost/hyposhop-staging/bundle.js:10405:49
> onLeave@http://localhost/hyposhop-staging/bundle.js:10377:36
> onInvoke@http://localhost/hyposhop-staging/bundle.js:10562:39
> invoke@http://localhost/hyposhop-staging/node_modules/angular2/bundles/angular2-polyfills.js:348:43
> runGuarded@http://localhost/hyposhop-staging/node_modules/angular2/bundles/angular2-polyfills.js:256:54
> runInnerGuarded@http://localhost/hyposhop-staging/bundle.js:10592:89
> runGuarded@http://localhost/hyposhop-staging/bundle.js:10492:89
> outsideHandler@http://localhost/hyposhop-staging/bundle.js:18026:72
> invokeTask@http://localhost/hyposhop-staging/node_modules/angular2/bundles/angular2-polyfills.js:382:43
> runTask@http://localhost/hyposhop-staging/node_modules/angular2/bundles/angular2-polyfills.js:282:58
> invoke@http://localhost/hyposhop-staging/node_modules/angular2/bundles/angular2-polyfills.js:449:41
> 
> [Error] TypeError: Attempted to assign to readonly property.`

It works fine on all other browsers I have tested.

Link to my test: http://hypiq.nl/bespaar-check/

The problem start after hittin the start the check button.

**Comment by pkozlowski-opensource** [comment]
Please narrow it down and provide a reproduce scenario, otherwise it is not actionable. One thing you might check is the assignment / binding to the `style` property (search for `[style]`) - but it is just a stab in the dark without a reproduce scenario.

**Comment by skunheal** [comment]
I added a link to my test server. The problem starts after hitting the orange button saying "start nu de check"

**Comment by pkozlowski-opensource** [comment]
@skunheal link to the whole live app is _not_ what I've meant by "narrow it down and provide a reproduce scenario"....

**Comment by u12206050** [comment]
Have you been able to fixe the [Error] TypeError: Attempted to assign to readonly property. ???
I am sitting with the same problem now, works on other browsers but not on Safari.

**Comment by stuartkuentzel** [comment]
I'm having the same issue. Any solution to this?

**Comment by vicb** [comment]
The issue is closed because it's missing a repro. Open a NEW issue if you are able to come up with a "simple" repro. Thanks !
