### ISSUE TITLE
Upgrade to RC5 error: zone.js:461 Unhandled Promise rejection: No provider for ElementRef!

### ISSUE THREAD

**Issue by junjunruan** [angular/angular#10817]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
My project is built with angular2 + electron, I recently upgraded to RC5: nothing else was changed other than making all the npm modules rc5. RC5 is not a breaking change (https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html), but it breaks my app.

I already commented out all the code related to ElementRef, but still got the following error message:
![rc5error](https://cloud.githubusercontent.com/assets/13875577/17667639/b0c295ce-62d3-11e6-8a58-317c2aea5558.png)

The error happened during rendering the index.html file:
```
<html>
<head>
    <script>
        var pjson = require('./package.json');
        document.title = pjson.name;
    </script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="./node_modules/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="./node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/global.css">

    <!-- 1. Load libraries -->
    <!-- Polyfill(s) for older browsers -->
    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <!-- 2. Configure SystemJS -->
    <script src="systemjs.config.js"></script>
    <script>
        System.import('app/main/bootstrap.js').catch(function(err){ console.error(err); });
    </script>
    <script>
        var electron = require('electron');
    </script>
</head>

<body>
<app-cmp>Loading...</app-cmp>
</body>
</html>

```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chromium: 52.0.2743.82] 
 
* **Language:** [TypeScript 1.8.7 | ES6/7]

**Comment by DzmitryShylovich** [comment]
Can u provide a minimal reproduction? Otherwise it's not actionable.

**Comment by junjunruan** [comment]
I wish I could. But the project I am working on is a very big and private project, I don't which part potentially cause the bug, so I can't make a boilerplate to reproduce the bug.

**Comment by marcalj** [comment]
I have the same problem and it was my error to put modules on ```@NgModule.declarations``` instead on ```@NgModule.imports```.

**Comment by pkozlowski-opensource** [comment]
> the project I am working on is a very big and private project. I don't which part potentially cause the bug, so I can't make a boilerplate to reproduce the bug

@juleskremer I'm afraid that you will have to spend some time trying to narrow down the issue. Otherwise this one is not really actionable...

**Comment by arkon** [comment]
I had this error as well. It might have something to do with how you're initializing your router. Check out the [updated example](https://github.com/angular/angular/blob/master/modules/playground/src/routing/index.ts).

**Comment by junjunruan** [comment]
Not sure which part cause the error, after adding NgModule and reorganize my project, the error gone.
