### ISSUE TITLE
Error: addProviders can't be called after the injector has been already created for this test. This is most likely because you've already used the injector to inject a beforeEach or the current `it` function.

### ISSUE THREAD

**Issue by imriba** [angular/angular#10811]
BUG REPORT: I'm trying to create a simple unit-test in angular2 rc-4 with no luck. I took into consideration the breaking changes in rc4 but `addProviders` usage keeps throwing an exception.

Whenever I try to use `addProviders` with no `it` function I get no errors, however, when I add the `it` function into the `describe` scope I get `Error: addProviders can't be called after the injector has been already created for this test. This is most likely because you've already used the injector to inject a beforeEach or the current it function.`

This is my code:

```
class MainConfigMock {
    useMocks: boolean = true;
}

describe('Should do something', () => {
    beforeEach(() => {
        addProviders([provide(MainConfig, {useClass: MainConfigMock})]);
    });

    it('should save report', () => { // this block breaks the test

    });

});
```

Also mentioned in: http://stackoverflow.com/questions/38954449/angular2-rc4-error-addproviders-cant-be-called-after-the-injector-has-been

How can this be resolved? Thanks.

**Comment by wardbell** [comment]
Probably best if you update to RC5. 

Nonetheless, it's difficult to answer this question because your example seems incomplete. Something is very likely above the code that you show and is actually calling inject before this `describe` block, explicitly or implicitly. As the message says, you can't change the providers once something calls `inject`.

If you think otherwise, please provide a repro in plunker.

The reason that the error is triggered only by a dummy `it` is that the testrunner doesn't bother to execute the describe if there are no `it` calls.

**Comment by imriba** [comment]
Thanks for the reply. The code before is only import and declaration of variables, but here it is anyways:
```
import { provide } from '@angular/core';
import { inject, TestComponentBuilder, addProviders, beforeEach, expect, describe, it } from '@angular/core/testing';
import { AuthenticationService } from '../../../shared/login.service';
import { Router } from '@angular/router';
import { Http, HTTP_PROVIDERS, XHRBackend } from '@angular/http';
import { MockBackend } from '@angular/http/testing';
import { AuthConfig, AuthHttp }       from 'angular2-jwt';
import { ToasterService, ToasterConfig } from 'angular2-toaster/angular2-toaster';
import { Logger } from '../../../shared/logger.service';
import { MainConfig } from '../../../../main.config';
import { SaveReportComponent } from './save-report.component';
import { SaveReportService } from './save-report.service';
import { HttpInterceptor } from '../../../shared/http.interceptor';

class MainConfigMock {
    useMocks: boolean = true;
}

let builder: TestComponentBuilder;
let saveReportService: SaveReportService;
let authHttp: AuthHttp;

describe('Component: Save Report', () => {
    beforeEach(() => {
        addProviders([provide(MainConfig, {useClass: MainConfigMock})]);
    });

    it('should save report', () => {

    });
});
```

**Comment by imriba** [comment]
Also, I can't update to RC5 since I'm restricted by ionic releases. Is there a way to overcome this in RC4?

Thanks.

**Comment by vikerman** [comment]
Obsolete.
