### ISSUE TITLE
No provider for RadioControlRegistry inn new forms lib?

### ISSUE THREAD

**Issue by obiwan007** [angular/angular#10813]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a forms component which uses <Input type="radio"> elements,
Strangely I get an exception:

`4:35:27 ERROR EXCEPTION: Error in app/controls/forms/form-template.component.html:158:12
ORIGINAL EXCEPTION: No provider for RadioControlRegistry!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:3000/node_modules/@angular/core/src/facade/exceptions.js:27:23)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:3000/node_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
    at new NoProviderError (http://localhost:3000/node_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:3000/node_modules/@angular/core/src/di/reflective_injector.js:786:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:3000/node_modules/@angular/core/src/di/reflective_injector.js:814:25)
    at ReflectiveInjector_._getByKey (http://localhost:3000/node_modules/@angular/core/src/di/reflective_injector.js:777:25)
    at ReflectiveInjector_.get (http://localhost:3000/node_modules/@angular/core/src/di/reflective_injector.js:586:21)
    at NgModuleInjector.get (http://localhost:3000/node_modules/@angular/core/src/linker/ng_module_factory.js:98:52)
    at ElementInjector.get (http://localhost:3000/node_modules/@angular/core/src/linker/element_injector.js:30:48)
    at ElementInjector.get (http://localhost:3000/node_modules/@angular/core/src/linker/element_injector.js:30:48)
ERROR CONTEXT:
[object Object]`

I can't reproduce the behaviour in plunker  yet. My codebase is a bit to big to find the cause of the problem so far.

The component Hosting the form is calling a different component actually rendering the form Elements based on my data model.

`<div *ngFor="element of Elements"> <myForm [form]="myFormGroup" [mymodel]="element"></myForm>`

The Input element:
` <input class="radio"
                 [name]="template.lowerKey"
                 type="radio"
                 [attr.name]="template.value.radioGroupId"
                 [ngModel]="{checked: template.value.isChecked}"
                 (change)="radioChanged(template)">`

module init:
`  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    routing],`

Any idea what could cause the not finding of the registry provider?

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Plunker is difficult to create. So far I could not reproduce it in a more simplistic component.

**What is the expected behavior?**

RC4 forms lib is Rendering ok. So should the new Version.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5, forms: 0.3.0
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8]

**Comment by DzmitryShylovich** [comment]
Sorry, but if u cannot provide a minimal reproduction it's not actionable.

**Comment by pietie** [comment]
I got this same error after upgrading to rc5.
It seems the thing that upsets it is the binding to [ngModel].

So I changed  
```html
<input type="radio" name="grp1" [ngModel]="{ checked: radioValue == 100 }" (ngModelChange)="radioValue = 100" />
```
to the following format which fixed the problem for me

```html
<input type="radio" name="grp1" [checked]="radioValue == 100" (change)="radioValue = 100" />
```

(Don't know if it makes a difference but my component is dynamically loaded with ComponentFactoryResolver)

**Comment by zoechi** [comment]
Seems you are using a hack that I posted on SO when `<input type="radio">` wasn't yet supported directly.

Now you can use it like:

```ts
     <input type="radio" name="food" [(ngModel)]="food" value="chicken">
     <input type="radio" name="food" [(ngModel)]="food" value="fish">
```
See also https://github.com/angular/angular/blob/6f4ee6101c937e1bc396ffede969c437706554a8/modules/%40angular/forms/src/directives/radio_control_value_accessor.ts#L69

**Comment by pietie** [comment]
Yeah I got it from your SO post way back, thanks :)

I did actually try the [(ngModel)] binding yesterday but it is still not working as expected.
Have a look at this [plnkr](http://plnkr.co/edit/w7nJDuMPVSA6ghlGMVSM?p=preview)

The problem I have is that Group 1 does not initially check Option 200 as expected. This works fine on Group 2 that uses the [checked] syntax. Group 1 also does not update when I click the buttons at the bottom.

**Comment by zoechi** [comment]
If you make the default values a string it's working fine http://plnkr.co/edit/GPcpiivfe6Nq8eZeZc5M?p=preview

**Comment by pietie** [comment]
Ah thanks! Input with type=text works fine with an initial number binding though so it's all a bit confusing. If there is some reason it has to be string for radios it would be nice if the framework could throw...

**Comment by liujie20087349** [comment]
thanks  pietie and zoechi, I solve this problem using your suggestion

**Comment by gomesNazareth** [comment]
pietie after i upgraded to RC5 I got the same error with radio. Thanks your solution worked for me

**Comment by gomesNazareth** [comment]
but if i bind the radio button to a form . it throws the same error  :( and this soln wont work 

 <div class=" twenty-box">
                                        <div class="radio radio-primary">
                                            <input type="radio" name="radio2" id="radio1"
                                                   (click)="clickSelectDrivingLicense()" value="option1"
                                                   ngControl="driving_license_status_id."
                                                   #driving_license_status_id="ngForm"
                                                   name="generalInfo_form_driving_license_status_id"
                                                   [checked]="(jobSeekerGeneralInfo | async)?.driving_license">
                                            <label for="radio1">   <span>Yes </span> </label>
                                        </div>
                                    </div>

**Comment by Nalha** [comment]
I'm still having this same issue with our quite large project.

http://plnkr.co/edit/iwKw9futKEVSaD6uNIoX?p=preview

This code throws this error as soon as I have the ngModel in there.

EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./TestPage class TestPage - inline template:7:5
ORIGINAL EXCEPTION: No provider for RadioControlRegistry!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] http://localhost:8080/vendor.bundle.js:2306:24

One of the guys I'm working with might have added some hack previously but I have no idea where I could find something like that.

We're running rc5.

**Comment by pkozlowski-opensource** [comment]
@Nalha I can't reproduce with RC6, see it working here: https://plnkr.co/edit/eOXlyQXkDSJDcDAG8QcE?p=preview

My best advice: migrate to RC6 and stop using combination of deprecated and new forms (you still got `import { FORM_DIRECTIVES, CORE_DIRECTIVES } from '@angular/common'` in your plunker).

Reading through this issue there is a number of other reports about errors but the above is the only plunk where I could see the pb in action and help in a meaningful way. If anyone is still facing this / similar problem please open a new issue with a minimal plunk. Thnx!
