### ISSUE TITLE
Routing to children routes in lazy routing recreates instance of parent

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#10814]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In RC.5 and Router RC.1 if you have lazy route 

```typescript
{
    path: 'test',
    loadChildren: 'app/pages/test/test.module'
}
```

and routes imported in `test.module` are 
```typescript
{
    path: '',
    component: TestComponent,
    children: 
    [
        {
             path: 'test1',
             component: Test1Component
        },
        {
             path: 'test2',
             component: Test2Component
        }
    ]
}
```

Now when you change url from `'/test/test1'` to `'/test/test2'` each time is created new instance of `TestComponent`. If you have same thing done without lazy routing it works correctly and instance of `TestComponent` is created only first time when route starts with `'/test'` prefix and changing sufix `'test1'` or `'test2'` does not create new parent component. 

So if you remove lazy routing
```typescript
{
    path: 'test',
    loadChildren: 'app/pages/test/test.module'
}
```
and change routing of module to:
```typescript
{
    path: 'test',
    component: TestComponent,
    children: 
    [
        {
             path: 'test1',
             component: Test1Component
        },
        {
             path: 'test2',
             component: Test2Component
        }
    ]
}
```

everything is ok.

**Expected/desired behavior**
Creating of routed components should behave exactly same way independently whether you use lazy routing or not.

**Reproduction of the problem**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by brandonroberts** [comment]
This has already been fixed in master https://github.com/angular/angular/pull/10707

**Comment by kukjevov** [comment]
Thank you for info.
