### ISSUE TITLE
Safe navigation (aka Elvis) operator - not guarding against null with async @rc5

### ISSUE THREAD

**Issue by mikeybyker** [angular/angular#10810]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
In rc4, you could use the safe navigation/Elvis operator (?.) to guard against nulls in property paths when using the async pipe - don't seem to be able to in rc5.

```
// Inside a template in rc5 - Assuming Observable var data which (will have) an id property:

{{(data | async)?.id}} // throws error : TypeError: Cannot read property 'id' of null
```
**Expected/desired behavior**
As per rc4:
```
 {{(data | async)?.id}} // works as expected - id displays when data loaded
```

**Reproduction of the problem**
rc4 - working as expected:
http://plnkr.co/edit/m9UJEwB4ZSNhIb77A2aI?p=preview

rc5 - not working/throwing error:
http://plnkr.co/edit/QQlg8nKJqVR8DqB2SiTw?p=preview

**What is the expected behavior?**
Accessing properties of (currently) null values not to throw an error - the Elvis operator would ideally guard against the error...

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment]
Duplicate of #10639

**Comment by mikeybyker** [comment]
Ah yes, so it is - sorry for the duplicate...
