### ISSUE TITLE
Router is serializing fragment parts on Router.runNavigate() causing corrupted URL

### ISSUE THREAD

**Issue by jairov4** [angular/angular#10827]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Fragment is being serialized using Url Encoding on `Router.runNavigate()` and causing corrputed payload.  This is unexpected because the navigation process should occur without modification of the URL at all.

**Expected/desired behavior**

**Reproduction of the problem**
Take the https://angular.io/resources/live-examples/toh-5/ts/plnkr.html sample and run the first route http://domain/#testField=testValue you will see that parameters will be converted into http://domain/#testField%3DtestValue

**What is the expected behavior?**
URL should kept untouched during navigation bootstrap (of course redirect actions are excepted)

**What is the motivation / use case for changing the behavior?**
For example Auth0 is relying on parameters passed through hash part after auth callback request and now is not working.

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** all
 
* **Language:** all

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/11063
