### ISSUE TITLE
Router bug with child routes

### ISSUE THREAD

**Issue by tuurbo** [angular/angular#10826]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I reported a bug #10702 which was fixed with #10707 and i'm using the fix from ```router-builds-2.0.0-cc6749c``` https://github.com/angular/router-builds/releases/tag/2.0.0-cc6749c. But now multi-child routes don't seem to work completely. Child links don't always navigate.

**Reproduction of the problem**
You can see the steps to reproduce the issue inside the plunker.
http://plnkr.co/edit/85Qb5hmQhtouwjHHUsUW?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome 52]

**Comment by brandonroberts** [comment]
This is not a bug. You are using snapshot params which are not updated if the component is reused. Since the detail is a child of the list route, it will be reused when you change heroes. In order to get parameter updates when the components are reused, you need to subscribe to the params.

Here is a working example: http://plnkr.co/edit/yAa8MVxpEk9FffnWH7w9?p=preview

**Comment by tuurbo** [comment]
Thank you!

**Comment by tuurbo** [comment]
@brandonroberts Looks like the example i made wasn't the bug i was getting in my private app. Sorry!

Here is a link to the real error
http://plnkr.co/edit/LcLh4dHiWPsipl8fpHx7?p=preview

**Comment by brandonroberts** [comment]
This isn't a bug per-say as much as a misconfiguration. You can't have an component-less empty path route be the terminating route. You have to have a component to be rendered.

Here is a working example with an empty component: http://plnkr.co/edit/IJ9PW4CkUqvKNSOvoBQm?p=preview

**Comment by tuurbo** [comment]
Thanks for your help. That worked, i just feel like you shouldn't even need the empty route, it should just render ```HeroListComponent```, but i'm sure there is a reason for it that i don't understand. Thanks again
