### ISSUE TITLE
Resource interceptor is not actually an interceptor, just a function that returns what becomes result of resource promise.

### ISSUE THREAD

**Issue by KamilSzot** [angular/angular#1082]
Here you can see that behaviour of interceptor added to $httpProvider.interceptors is completely different from interceptor declared in resource methods: http://jsfiddle.net/Lzgts/269/

I think we need to update the documentation to reflect this changing the behaviour now might break apps of people who adapted to this behaviour.

That's how I found out about this bug. Behaviour of my app was different when I stopped needing the resource interceptor. After removing it app stopped working properly, but leaving it doing nothing as shown at https://docs.angularjs.org/api/ng/service/$http in section on Interceptors kept the app working properly.

**Comment by pkozlowski-opensource** [comment]
Wrong repo, I guess you are looking for https://github.com/angular/angular.js

**Comment by KamilSzot** [comment]
yup, sorry, thanks for pointing me in the right direction
