### ISSUE TITLE
Quickstart systemjs.config.js double slash problem

### ISSUE THREAD

**Issue by SoltauFintel** [angular/angular#10828]
I think there is a little mistake in systemjs.config.js seen on page https://angular.io/docs/ts/latest/quickstart.html. Look at 'bundles'.

old line:

`packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };`

new line:

`packages['@angular/'+pkgName] = { main: 'bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };`

The leading "/" results in "//" in the complete URL. That makes trouble (404) executing a fat JAR file (Sparkjava 2.3 with Jetty). It is no problem when executing in Eclipse. It is no problem when executing as WAR on a Tomcat (because the files are unzipped).

Could you please verify that there is no need for the leading slash please?

**Comment by robwormald** [comment]
this is pretty environment dependent (things like baseHref etc can impact load paths) - if your config works in your environment, go with it :)
