### ISSUE TITLE
reflective_provider.js: Uncaught Invalid provider - only instances of Provider and Type are allowed, got: undefined

### ISSUE THREAD

**Issue by nottinhill** [angular/angular#10835]
How can I debug this? It should be a cyclic dependency.

This is the way I have my folders aligned:

[Cyclic-Dependency](http://imgur.com/ZKY4SCr)

I doing in the first index.ts from top:

```
export * from './auth-server/auth-server.service';
export * from './auth-server/auth-server.mock';
export * from './auth-zero/auth-zero.service';
export * from './auth-zero/auth-zero.mock';
export * from './auth-service/auth-service';
export * from './auth-login/auth-login.directive';
```

in  the second index.ts from top:

```

export * from './shared';
export * from './auth-login/auth-login.component';
```

And the files themselves are importing from each other. Should that be done directly or via the shared folder? 

How can I debug the message? I think many would like to know. Any help is highly appreciated.

**Comment by pkozlowski-opensource** [comment]
We can't do much about cyclic dependencies but we could definitively improve the error message.

**Comment by Awk34** [comment]
I'm getting the same error on a hybrid app I'm working on, but only in production
