### ISSUE TITLE
Problem with socket.io?

### ISSUE THREAD

**Issue by BatsShadow** [angular/angular#1083]
I've been building a little test app using node, socket.io and angular2. When originally angularjs 1.3, the socket calls worked fine, but I'm now getting:

es6-shim.js:29889 Uncaught RangeError: Maximum call stack size exceeded
run @ es6-shim.js:29889
zoneBoundFn @ es6-shim.js:29866
fnNames.map.forEach.zone.(anonymous function).arguments.(anonymous function) @ es6-shim.js:29940
(anonymous function) @ es6-shim.js:29873
run @ es6-shim.js:29889
zoneBoundFn @ es6-shim.js:29866
fnNames.map.forEach.zone.(anonymous function).arguments.(anonymous function) @ es6-shim.js:29940
(anonymous function) @ es6-shim.js:29873
run @ es6-shim.js:29889
zoneBoundFn @ es6-shim.js:29866

Here's my code:

    //imports...
    let socket = io();
    
    @Component({
        selector: 'my-app'
    })
    @Template({
        url: 'my-app.html',
        directives: [...]
    })
    class MyAppComponent {
    ...
    }

Commenting out the socket definition eliminates the error, and the call stack error happens whether or not I do `socket.on()`

Is there a problem with zones and socket.io? Am I doing something wrong?

**Comment by augiwan** [comment]
Could this happen because `let socket = io();` is being executed more than once?

**Comment by BatsShadow** [comment]
That line only executes once upon module import.

**Comment by BatsShadow** [comment]
This is the same stack trace as issue #1050.

**Comment by BatsShadow** [comment]
After debugging a bit deeper, I discovered that socket.io is calling setTimeout, so this is a duplicate.

Working with the chat example from http://socket.io/get-started/chat/, I wittled the client side down to this bare minimum which causes the problem:

    <!doctype html>
    <html>
      <head>
        <title>Socket.IO chat</title>
      </head>
      <body>
        <script src="https://jspm.io/system@0.16.js"></script>
        <script src="/angular2.js"></script>
        <script src="/socket.io/socket.io.js"></script>
        <script>
          var socket = io();
        </script>
      </body>
    </html>

Notes:
- system.js is not required to repro, but including it prevents a second unrelated console error
- if you replace the angular2 bundle with zone.js and long-stack-trace-zone.js, the problem goes away

**Comment by naomiblack** [comment]
closing as dup
