### ISSUE TITLE
[router]: Lazy loading route initialize compiling multiple times 

### ISSUE THREAD

**Issue by Delagen** [angular/angular#10848]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
NgModule constructor calls two times when loading of module lazy using loadChildren (Active route is different)
But when NgModule is active route, constructor invoked single time

**Expected/desired behavior**
Single time loading and compiling

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Chrome 53
* **Language:** TypeScript 2.0

**Comment by brandonroberts** [comment]
This has already been fixed in master: https://github.com/angular/angular/pull/10707

**Comment by Delagen** [comment]
Thanks closing as duplicate

**Comment by senseiweb** [comment]
Hello before I submit this as bug, can someone confirm that there is mostly likely a regression of this particular problem.  ==> [Plunker is here](https://plnkr.co/edit/HtG1A8IdsmOPPnPIVBga?p=preview), using example built by @johnpapa, open the console and click on the vehicles link. Thanks in advance

**Comment by senseiweb** [comment]
Disregard, seems to be documented at #12869  Thanks
