### ISSUE TITLE
Can Activate child, can Activate operational order 

### ISSUE THREAD

**Issue by vespertilian** [angular/angular#10845]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The canActivate guard on the child component is called before the canActivateChild guard on the parent. 

ROUTER_CONFIG

```js 
{
		path: ':tenant',
		canActivateChild: [TenantGuard], //** This is called second **
		children: [
			{
				path: 'component-foo',
				component: EmployeeSearch,
				canActivate: [AuthGuard] //**This is called first **
			}
]
}
```

This is because canActivate is before canActivateChild in the check guards array. 

`[this.runCanActivate(s.route), this.runCanActivateChild(s.path)]`

router.ts

```js 
  checkGuards(): Observable<boolean> {
    if (this.checks.length === 0) return Observable.of(true);
    return Observable.from(this.checks)
        .map(s => {
          if (s instanceof CanActivate) {
            return andObservables(
                Observable.from([this.runCanActivate(s.route), this.runCanActivateChild(s.path)]));
          } else if (s instanceof CanDeactivate) {
            // workaround https://github.com/Microsoft/TypeScript/issues/7271
            const s2 = s as CanDeactivate;
            return this.runCanDeactivate(s2.component, s2.route);
          } else {
            throw new Error('Cannot be reached');
          }
        })
        .mergeAll()
        .every(result => result === true);
  }
```

**Expected/desired behavior**

I feel that the parent guard should be called and prevent transition before the child guard is called. 

**What is the motivation / use case for changing the behavior?**

My specific use case is that I have a parent route from which I want to, get, validate and set a tenant for use by child components and services.

Then I want to check the user is authenticate on some of the child routes. My big issue is that my AuthGuard depends on the tenant having been set by the TenantGuard on the parent route.

Generically though I feel it makes more logical sense that a parent guard is checked before the child guard is checked 

Happy to fix this and update tests (pull request) if you are happy with an order swap.

`[this.runCanActivateChild(s.path), this.runCanActivate(s.route)]`

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 * **Language:** [TypeScript 1.8.10]

**Comment by DzmitryShylovich** [comment]
See https://github.com/angular/angular/issues/7342

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/11063
