### ISSUE TITLE
Proposal: Assertion API

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1084]
#### Idea
Write assertions in components that are applied in dev mode, but stripped out in production mode. The is similar to the type assertions, but more general. 

For example, say you have a `CustomRadio` component that can either in an a `CustomRadioGroup` or be given a name attribute, but not both. The component author could write an assertion:
```js
ASSERT(this.parentGroup XOR this.name, 'CustomRadio must...');
```

This gives the component user a meaningful error in development mode, but does add extra weight to the final output.

#### Prior art
The Closure Compiler implements this concept with the Closure library's [`goog.asserts`](http://docs.closure-library.googlecode.com/git-history/15160ce901b70ac9df5e7d25ae4835835738f782/closure_goog_asserts_asserts.js.html) module.

#### Other notes
A similar approach could also be applied to logging.

**Comment by vicb** [comment]
similar to #112

**Comment by jelbourn** [comment]
I'll close this as a dupe of #112
