### ISSUE TITLE
Error: TypeError: router_1.Routes is not a function(…)

### ISSUE THREAD

**Issue by sajiddesigner** [angular/angular#10844]
Hello,

I am having following error in console 
` (index):18 Error: TypeError: router_1.Routes is not a function(…) `
If i remove from code then error vanish away.
my App.component.ts code is

`
import { Component } from '@angular/core';

import {ROUTER_DIRECTIVES, Router, Routes} from '@angular/router';

import { NavbarComponent } from './components/navbar/navbar.component';
import { JumbotronComponent } from './components/jumbotron/jumbotron.component';
import { HomeComponent } from './components/pages/home.component';
import { AboutComponent } from './components/pages/about.component';

@Component({
  selector: 'my-app',
  template: `
  			<navbar> </navbar>
  			<jumbotron> </jumbotron> 			
			​<div class="container">
​   <router-outlet> </router-outlet>
​        </div>
  			`,
  directives: [NavbarComponent, JumbotronComponent, HomeComponent, AboutComponent, ROUTER_DIRECTIVES]
})

@Routes([
	{path: "/", component: HomeComponent},
	{path: "/about", component: AboutComponent}
	])

export class AppComponent {
	constructor(private router: Router){

	}
 }

`

main.ts code

`
import { bootstrap }    from '@angular/platform-browser-dynamic';
import { AppComponent } from './app.component';
import { ROUTER_PROVIDERS } from '@angular/router';

bootstrap(AppComponent, ROUTER_PROVIDERS );

`

Any help will be appreciated.

**Comment by markpritchett** [comment]
Please take a look at https://github.com/angular/angular/blob/master/CONTRIBUTING.md for guidance on what to do when you have questions or wish to file a bug.

**Comment by brandonroberts** [comment]
The router you're using is no longer available. You need to migrate to router version `3.0.0-rc.1`

**Comment by sajiddesigner** [comment]
Helo @brandonroberts,
I am using router version 3.0.0-alpha.7, i have also tried version 3.0.0-rc.1 and then i updated router version as it was not working.
Please tell me how can i fix this issue
thanks

**Comment by ericmartinezr** [comment]
Stop trying to use the deprecated router as if it was the new RC router. Read the documentation that it is already updated afaik.

**Comment by sajiddesigner** [comment]
@brandonroberts  here is my package.json file

`
   {
  "name": "a2website",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "^3.0.0-alpha.7",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.4",
    "angular2-in-memory-web-api": "0.0.14",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings": "^1.0.4"
  }
}

`

**Comment by sajiddesigner** [comment]
@ericmartinezr  I am new to angular, i am not using any deprecated version of Router.

**Comment by sajiddesigner** [comment]
@brandonroberts  I have removed router-depcrated from package.json, i still have same issue. see error below.

![image](https://cloud.githubusercontent.com/assets/5917783/17700243/6685611a-63de-11e6-9c80-99df84fe1804.png)

**Comment by sajiddesigner** [comment]
i have deleted node_modules folder and tried npm install.. see errors below


![image](https://cloud.githubusercontent.com/assets/5917783/17700478/554c8c42-63df-11e6-9314-6e2e1760fff9.png)

**Comment by sajiddesigner** [comment]
After npm install typings -g i have these errors 


![image](https://cloud.githubusercontent.com/assets/5917783/17700737/76e4596a-63e0-11e6-82b8-c509606cea9b.png)

**Comment by ericmartinezr** [comment]
@sajiddesigner if you are new to ng2, you must start with the officiak docs

Quickstart updated to RC5
https://angular.io/docs/ts/latest/quickstart.html

Router dev guide updated to router rc1
https://angular.io/docs/ts/latest/guide/router.html

**Comment by sajiddesigner** [comment]
i am following quickstart docs. and i found this error while working with quickstart project @ericmartinezr

**Comment by sajiddesigner** [comment]
Hello @brandonroberts 
As per your instructions, i have updated NPM and run commans
npm install
npm start

following are the results now

![image](https://cloud.githubusercontent.com/assets/5917783/17702542/cca00366-63e7-11e6-896e-186eefb604b0.png)

**Comment by zoechi** [comment]
see the first comment below your initial post (from markpritchett)

**Comment by pkozlowski-opensource** [comment]
Closing as this sounds like a support question. See https://github.com/angular/angular/blob/master/CONTRIBUTING.md
