### ISSUE TITLE
Angular 2 Async validations for FormGroup

### ISSUE THREAD

**Issue by UmairYasin** [angular/angular#10842]
I'm submitting a ...

`[x] feature request`

**Current behavior**
Currently Async validations cannot be applied to FormGroups.

**Possible use case**
I found this problem when I tried to make the name field of the object to be created unique all the time. But that name field should be unique within an object. So in order to make it happen, I need to pass the parent object id and the name field's value of the child object to rest service. So I created a FormGroup with parent object and name of child object but I cannot create an Async Validator with that FormGroup. Instead I can only create an Async Validator with FormControl for name, but then cannot pass the parent object id to that validator.

**Desired behavior**
FormGroup should be able to have an Async Validator to pass multiple values of form to that validator.

**My environment:**

Angular version: 2.0.0-rc.5

**Comment by markpritchett** [comment]
It's unclear whether you are submitting a question, bug or feature request here.

Please take a look at https://github.com/angular/angular/blob/master/CONTRIBUTING.md for guidance on what you can do depending on your needs.

**Comment by UmairYasin** [comment]
@markpritchett Sorry for being unfamiliar with the pattern. I have updated my query. Thanks

**Comment by kara** [comment]
Can you create a plunker with an example of your use case?

**Comment by kara** [comment]
You can create async validators for FormGroups as well as FormControls.   Closing, as I'm having trouble replicating your problem without a plunker.   See the docs here: https://angular.io/docs/ts/latest/api/forms/index/FormGroup-class.html.
