### ISSUE TITLE
Testing: Add static class method, `TestBed.get`

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10843]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request 
```

A few `TestBed` instance methods are not covered by static methods. Almost all of them are rarely needed and justifiably excluded. But the `get` method would be handy as a static class method.

**Current behavior**

For example, when testing a service with injected stuff, I could write this:

```  
  beforeEach(() => {
    TestBed.configureTestingModule({ providers: [FancyService] });
    // inject returns a fn; don't forget to call it!
    inject([FancyService], (svc: FancyService) => service = svc) ();  // YUCK!
  });
```

... or this

```  
  beforeEach(() => {
    TestBed.configureTestingModule({ providers: [FancyService] });
    service = getTestBed().get(FancyService);  // BETTER
  });
```

... but ...

**Expected/desired behavior**

... I'd prefer to write this more obvious and discoverable code

```
  beforeEach(() => {
    TestBed.configureTestingModule({ providers: [FancyService] })
    let service =  TestBed.get(FancyService);  // BEST
  });
```

I'd like to chain a `get` method call as I can with other static methods like this:

```
  beforeEach(() => {
    let service = TestBed.configureTestingModule({ providers: [FancyService] })
                         .get(FancyService);  // DREAMY
  });
```

The `get` method has a critical advantage over `inject`: it can inject _optional_  services.
The `inject` method can't and throws an exception.

For this reason, we should (and will) teach the `get` method so that we can write tests like this:

```
  beforeEach(() => {
    TestBed.configureTestingModule({ imports: [SomeModule] })
    let service =  TestBed.get(FancyService, null); // FancyService may not be provided.
  });
```

Obviously not a critical feature at all. We can always write

```
let service =  getTestBed().get(FancyService, null); // FancyService may not be provided.
```

That's not very discoverable. It would be nice to have it where people expect it, as a static class method.

If not now, perhaps for 2.1?

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all ] 
- **Language:** [all]

**Comment by Fank** [comment]
@vsavkin done by 4648b3e5de9e67c3626dd8b9c884d9b0c1ba3eef ?

**Comment by DzmitryShylovich** [comment]
Yeah, can be closed @pkozlowski-opensource

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource there's already such method ☝️ 
can be closed
