### ISSUE TITLE
Error: Uncaught (in promise): TypeError: _this.location.isCurrentPathEqualTo is not a function

### ISSUE THREAD

**Issue by Aarti15** [angular/angular#10847]
AS per mentioned in Issue #9525 I have upgraded to RC.3 but still i am getting same error

"@angular/common": "2.0.0-rc.3",
"@angular/compiler": "2.0.0-rc.3",
"@angular/core": "2.0.0-rc.3",
"@angular/http": "2.0.0-rc.3",
"@angular/platform-browser": "2.0.0-rc.3",
"@angular/platform-browser-dynamic": "2.0.0-rc.3",
"@angular/router": "3.0.0-alpha.7",
"@angular/router-deprecated": "2.0.0-rc.3",
"@angular/upgrade": "2.0.0-rc.3",

Error: Uncaught (in promise): TypeError: _this.location.isCurrentPathEqualTo is not a function
Please let me know the solution

**Comment by DzmitryShylovich** [comment]
Upgrade to latest version (rc5).

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich !
