### ISSUE TITLE
"Tour of Heroes" quick start fails with multiple users

### ISSUE THREAD

**Issue by officialdharam** [angular/angular#10849]
I found issues with the "Tour of Heroes" Quick Start example. 

**Current Behavior**
Upon successfully running the application on my system, I shared the URL with few of my friends and to my surprise when I type a name in the search box, all my friends get to see that as well.

I am trying to point out that the Components perhaps are behaving like singletons and so the bounded variables are getting shared across. Check the below image of two side by side browsers.

![image](https://cloud.githubusercontent.com/assets/2534571/17696602/182e2dfa-63cd-11e6-81ea-6e1bb17c7968.png)

**Expected/desired behavior**
I expect that both of us should be able to search our own favorite heroes and must not see what the other user is typing.

**Reproduction of the problem**
Try running the "Tour of Heroes" application using npm start and then open two browsers (you can choose one in Incognito mode as well)

You can observe the issue.

** My environment **

```
"devDependencies": {
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.2",
    "typescript": "^1.8.10",
    "typings": "^1.3.2"
  },
  "dependencies": {
    "@angular/common": "^2.0.0-rc.5",
    "@angular/compiler": "^2.0.0-rc.5",
    "@angular/core": "^2.0.0-rc.5",
    "@angular/forms": "^0.3.0",
    "@angular/http": "^2.0.0-rc.5",
    "@angular/platform-browser": "^2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.5",
    "@angular/router": "^3.0.0-rc.1",
    "@angular/router-deprecated": "^2.0.0-rc.2",
    "@angular/upgrade": "^2.0.0-rc.5",
    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.0.0-beta.6",
    "systemjs": "^0.19.36",
    "zone.js": "^0.6.12"
  }
```
**Browser** used is Chrome, didn't try on any other browser. 
**Language** :  TypeScript

**Comment by DzmitryShylovich** [comment]
lite-server is a customized wrapper around BrowserSync. So u need to disable cross-device action mirroring functionality.

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by officialdharam** [comment]
@DzmitryShylovich  Thank you for the response. It fixed my problem. I really appreciate your efforts
