### ISSUE TITLE
When using ngModule, how can we track component-level dependencies?

### ISSUE THREAD

**Issue by xufei** [angular/angular#10840]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

We have been use [this tool](https://github.com/manekinekko/angular2-dependencies-graph) to manage our ng2 components dependencies. How ever, after upgrade to rc5, we have to use ngModule, and this lib cannot help us tracking our dependencies at component level any more.

So I wonder if I update a component / pipe / service / directive,  how could we know components that would be affected by it exactly? Or maybe we can only track module dependencies?

That would be great if ng team could provide an official tool on component-dependencies tracking.

**Comment by kylecordes** [comment]
This appears to be a somewhat vexing challenge with the new module system - at least from a source code point of view. Determining what components/directives are actually referenced, now requires parsing the template, very similar to what it would have required in AngularJS 1.x.

However, there is a relatively easy workaround, which I think could be used to fix angular2-dependencies-graph: first run ngc, the template precompiler. Then look at its output - typescript source code which references the components/directives that were used in the template.

I have no idea if the core team has in mind providing a dependency tool - in the short term it is perhaps most effective to encourage the author of angular2-dependencies-graph to use the tip above to make it work with the new NgModule system.

**Comment by damiandennis** [comment]
make your complaint heard on this issue https://github.com/angular/angular/issues/10552
A lot of people feel that dependency tracking is still needed on the component level (not wanting to remove but have it work alongside ngModules).

**Comment by xufei** [comment]
@kylecordes @damiandennis thanks for your help 💯
