### ISSUE TITLE
Router reinitialize component when params are being changed only with lazy loaded modules

### ISSUE THREAD

**Issue by pleerock** [angular/angular#10841]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**

When routes a defined lazily, when we navigate in the same component with only params/query params changed - component is being reinitialized (e.g. ngOnInit is called).

When using not lazy routes components is NOT being reinitialized when params/query params changed - this is expected behaviour.

**Expected/desired behavior**

When routes a defined lazily, when we navigate in the same component with only params/query params changed - component should not be reinitialized.

**Reproduction of the problem**

Problem with lazy routes:
1. [Open this plunker](http://plnkr.co/edit/UuLorrlwErFUM8u9Wbyh?p=preview)
2. Go to Crisis Center
3. Open console
4. Choose and open latest item in the crisis center. You see "component initialized" in the console
4. Click "change param!" button. You'll see "component initialized" in the console again. This is wrong behaviour. You should not see it again. 

No problems with non lazy routes:
1. [Open this plunker](http://plnkr.co/edit/xAmdbQGeYrd7WJJxLhcX?p=preview)
2. Open console
3. Choose latest item in the list of heros. You see "component initialized" in the console
4. Click "change param!" button. You'll NOT see "component initialized" in the console again. This is correct behaviour.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by brandonroberts** [comment]
This has already been fixed in master https://github.com/angular/angular/pull/10707

**Comment by kara** [comment]
Yep, fixed in master.  Closing!
