### ISSUE TITLE
`Can't bind to 'childProperty' since it isn't a known property of 'child-component'.` when using `TestBed.overrideComponent()`

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [angular/angular#10854]
**I'm submitting a ...**  (check one with "x")

```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am receiving the error `Can't bind to 'childProperty' since it isn't a known property of 'child-component'.`

**Expected/desired behavior**
I should receive no error.

**Reproduction of the problem**
Given I have:
- A component called `ChildComponent` with a selector of `child-component` and an `@Input` property called `childProperty`
- A component called `ParentComponent` that references `child-component` and binds to `childProperty`
- I write a unit test to create an instance of `ParentComponent` and override a provider in `ChildComponent`

I get the error `Can't bind to 'childProperty' since it isn't a known property of 'child-component'.`  If I remove the call to `overrideComponent()` then I no longer get the error.

Sample unit test code:

```
    let fixture = TestBed
      .overrideComponent(
        ChildComponent,
        {
          add: {
            providers: [
              {
                provide: SomeService,
                useValue: mockService
              }
            ]
          }
        }
      ).createComponent(ParentComponent);
```

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** Chrome 52
- **Language:** TypeScript 1.8.10

**Comment by DavidBanksNZ** [comment]
I have a similar issue. When trying to test one of our components whose template includes another component inside it, we want to override that inner component template with something more simple. But when trying to use the overrideComponent method we get the same error as above. I.e. using

```
fixture = TestBed
	.configureTestingModule({
		declarations: [CollectionComponent, CardComponent],
	})
	.overrideComponent(CardComponent, {set: {
		template: '<div></div>'
	}})
	.createComponent(CollectionComponent);
```

causes the error

```
Template parse errors:
	Can't bind to 'pondDocument' since it isn't a known property of 'pond-card'.
	1. If 'pond-card' is an Angular component and it has 'pondDocument' input, then verify that it is part of this module.
	2. If 'pond-card' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
```

**Comment by robwormald** [comment]
Yep, this was definitely a bug. It's been fixed on master at https://github.com/angular/angular/commit/87fe47737aaab9a75c0d0e5bf14d46f41a72bdff and will land in RC6.

You can use the master builds of angular (npm install angular/core-builds etc) in the interim.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource was fixed and can be closed
