### ISSUE TITLE
Support ! operator in Angular template expressions

### ISSUE THREAD

**Issue by goldibex** [angular/angular#10855]
Updated description (from @rkirov ):
Reopening the issue, but modifying the proposal. We cannot take away ? because back compat and it might be coming to JS. At the same type, we have aot users that do get strictNullChecks type errors when they do foo.bar in their templates. Their first approach is to try foo!.bar because that is what they will do if this was pure TypeScript.

To that end, I propose that we should support ! which is emitted as is in aot, and elided in jit mode.

Old description of the closed bug:
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
At present, Angular 2 provides a useful postfix property access operator in the template language called the "Elvis operator", which short-circuits the usual exception that is triggered when one attempts to access a property of a value like `null` or `undefined`.

Typescript 2 provides a new [non-null assertion operator](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#user-content-non-null-assertion-operator), which functions analogously except that the postfix operator is a !, not a ?.

**Expected/desired behavior**
To eliminate confusion between the syntax of Typescript and Angular templates, the Elvis operator in Angular templates should use a bang, not a question mark.

An alternative which could also be discussed would be to change the postfix for the non-null assertion operator in Typescript from a bang to a question mark. Obviously the Angular team is not in charge of that.

**What is the motivation / use case for changing the behavior?**
We expect Angular not to introduce too much new syntax that causes proactive interference, and in fact the team has done a fantastic job of balancing competing interests in this respect. I think this is especially true of Typescript considering the close coupling between the two projects.

I really do not want to spend the next five years explaining to junior developers that Typescript uses the bang and Angular uses the question mark for non-null property access:

![maxresdefault](https://cloud.githubusercontent.com/assets/179067/17704086/b830822a-6388-11e6-855d-a94211363793.jpg)

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** all
- **Language:** TypeScript 2.0

**Comment by sod** [comment]
The typescript `!` does something completly different. It's just to tell the compiler to ignore that fact, that a variable might be null. The `!` disappears after transpiling and does not generate additional code.

**Comment by goldibex** [comment]
Thanks @sod for clarifying that. But I don't think the difference in behavior can be put down as "completely different."

In both cases the postfix is used to assert something about the underlying value; it's true that TS2's `!.` functions at compile time and Angular's `?.` functions at run time, but they're both used to short-circuit the case where the value whose property is being accessed may not be "accessible."

There's still a very strong potential for confusion between the two, especially for developers who don't have an enormous amount of experience with type-safe programming languages and aren't necessarily accustomed to thinking about the differences in behavior between run time and compile time.

Someone might, for instance, write a component like this:

```typescript
@Component({
  template: "<div>Hello there {{ fullName() }}!</div>
})
export class GreetingComponent {
  
  @Input() user: User;

  fullName(): string {
    return this.user!.firstName + " " this.user!.lastName;
  }
}
```

expecting it to function analogously to a component like this:

```typescript
@Component({
  template: "<div>Hello there {{ user?.fullName }}!</div>
})
export class GreetingComponent {}
```

**Comment by zoechi** [comment]
See also #791

**Comment by IgorMinar** [comment]
The "non-null assertion operator" in TS2 does the opposite of "safe navigation operator" in Angular's expression language.

while `!.` tells the TS compiler that the left-handside expression can't be null or undefined in cases when compiler can't infer that, `?.` tells the parser/interpreter that the left-hand-side expression might be null or undefined.

So the two are very different and it would be confusing to everyone to try to align them.

**Comment by rkirov** [comment]
Indeed those are two very different operators with different semantics. But that should be a reason for supporting both and not attempting to align them.

It is confusing for the template language not to be a strict superset of the TypeScript language. If we don't support '!', the wrong mnemonic will be "'!' in .ts, '?' in .html", and people will assume it is a purely syntactic issue.

**Comment by rkirov** [comment]
Reopening the issue, but modifying the proposal. We cannot take away `?` because back compat and it might be coming to JS. At the same type, we have `aot` users that do get `strictNullChecks` type errors when they do `foo.bar` in their templates. Their first approach is to try `foo!.bar` because that is what they will do if this was pure TypeScript.

To that end, I propose that we should support `!` which is emitted as is in aot, and elided in jit mode. 

@chuckjaz @vicb What do you think?

**Comment by vicb** [comment]
I'm not sure about this one, the risk being that `!.` is being abused to silence TS errors and lead to runtime errors.

**Comment by DavidSouther** [comment]
AoT + StrictNull _requires_ `!`. If ! is not recognized and emitted to the AoT ngfactory, users will not be able to have strict null checks, and that is *way* worse than potential abuses of null-eliding.

**Comment by rkirov** [comment]
@vicb  I totally agree that `!` is inherently unsafe and should be used with care. That said, completely disallowing it in the template expressions is to the right way to handle this. All it does it adds extra friction where users will rewrite `{{foo.bar.buz}}` to `{{foobarbuz}}` and add `get foobarbuz() { return foo!.bar!.buz; }` in the controller.

**Comment by vicb** [comment]
@DavidSouther not sure to understand why "requires". `!` only assumes that a nullable is not null/undefined there should be no pb if the type is not nullable to start with ? Do you have use cases to share ?

@rkirov we should discuss it more this week.

**Comment by DavidSouther** [comment]
I have a library[1] (that I have no control over) which has an API like:

```typescript
interface Foo {
  getBar(): Bar|undefined;
}

interface Bar {
  getName(): string|undefined;
}
```


I can create an instance where I know my data will be good:

```typescript
class MyFoo implements Foo {
  private bar?: Bar;

  constructor(bar: Bar) {
    this.bar = bar;
  }

  getBar(): Bar|undefined {
    return this.bar; // While this is type |undefined, because of the implementation it will never be undefined. I can safely (in my template) use `foo.getBar()!`.
  }
}

class MyBar implements Bar {
  private name?: string;

  constructor(name: string) {
    this.name = name;
  }
  getName(): string|undefined {
    return this.name;
  }
}
```


Now I want a template with `foo.getBar().getName()`, which in my case I know will always be reasonable. I would do this in Typescript as `foo.getBar()!.getName()!`. If I don't use the `!`s, the ngfactory will not compile with strictNullChecks.

[1] Javascript Protobufs, https://github.com/google/protobuf/tree/master/js

**Comment by sod** [comment]
`strictNullCheck` is a tool for the programmer so we know that the program doesn't blow up at runtime because of a missing `if`. Imo `!` is only here for very tight performance related optimizations. For a typical app it's much more important to have concise runtime behavior.

My suggestion: Either provide a fallback in the constructor or assert the incoming values.

```typescript
// either 1. enforce type with fallback
constructor(bar: Bar) {
    this.bar = bar instanceof Bar ? bar : new Bar();
}

// or 2. enforce type by blowing up early and logging the incident
constructor(bar: Bar) {
    // assert(...) should log and throw if the incoming value is falsy
    assert(bar instanceof Bar);
    this.bar = bar;
}

// and then get rid of the `undefined`
getBar(): Bar {
    return this.bar;
}
```

**Comment by chuckjaz** [comment]
There are several cases where this work-around would be unnecessary gymnastics. Consider,

```ng
<div *ngIf="address">
  {{address.street}}
  {{address.city}}, {{address.state}} {{address.zip}}
</div>
```

This compiles correctly without `--strictNullCheck` but not with it. It is clear from the template that `address.street` is never evaluated when `address` is `null` but that is not communicated in the generated code a way that TypeScript would understand it. This would be much easier to convert to:

```ng
<div *ngIf="address">
  {{address!.street}}
  {{address!.city}}, {{address!.state}} {{address!.zip}}
</div>
```

which produces small and efficient code instead of introducing a slew of unnecessary temporaries and redundant checks that would be implied by:

```ng
<div *ngIf="address">
  {{address?.street}}
  {{address?.city}}, {{address?.state}} {{address?.zip}}
</div>
```
 
or require an odd query function and an unsafe cast with something like:

```ng
<div *ngIf="isAddressPresent()">
  {{address.street}}
  {{address.city}}, {{address.state}} {{address.zip}}
</div>
```

which introduces the a danger that someone would accidentally use `address` without being guarded by `isAddressPresent()` that would be uncaught by the compiler.

```ng
{{address.street}}
```

With `!` the above would be flagged as an error.
