### ISSUE TITLE
A component with a "correct" name overrules a selector

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#10850]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
A component named `SpectrumComponent` overrules a component with `selector: 'spectrum'` since rc.5

**Expected/desired behavior**
The template parser should only consider components with a selector

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**
**sigh**

**What is the motivation / use case for changing the behavior?**
**sigh**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 

In my application, I have a component with `selector: 'spectrum'` and a couple of properties that's (still) declared in the `directives` of other components. Using this component with `<spectrum [channelData]></spectrum>` in template now throws `Can't bind to 'channelData' since it isn't a known property of 'spectrum'.`. I have set a breakpoint at the throw statement in `TemplateParser.prototype.parse` and can observe the variables:

![image](https://cloud.githubusercontent.com/assets/1947968/17698698/d480886a-63bc-11e6-934b-8e769edd15f7.png)

I can fix that problem (and now things become seemingly unrelated) by removing a `SpectrumCompontent` from my router config. This component doesn't even have a `selector` declared.

Why?

**Comment by DzmitryShylovich** [comment]
Can u provide a minimal reproduction?

**Comment by pkozlowski-opensource** [comment]
Yeh, we are going to need a minimal plunker to move forward on this one.

**Comment by Tragetaschen** [comment]
I hate creating a Plunker. Slow, unhelpful editor, bad overall experience.

I tried my best: http://plnkr.co/edit/eaBFK7ALDHoJmN7iBrb0?p=preview
However, I don't get any farther than `VM3380 zone.js:323 Error: (SystemJS) Error: Unexpected value 'undefined' declared by the module 'DynamicModule'`.

**Comment by zoechi** [comment]
@Tragetaschen your Plunker uses the old bootstrap code. RC.5 requires modules.
https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

- https://angular.io/docs/ts/latest/guide/ngmodule.html
- https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html

**Comment by zoechi** [comment]
I wouldn't expect fixes for deprecated APIs.

**Comment by Tragetaschen** [comment]
So you don't know what the problem is, you assume a fix will be necessary just within deprecated APIs?

Maybe it's already time to close this then (seems like a waste of time).

FYI: I had a really shitty day due to Angular 2 failing on multiple levels due to "internal" changes. The first release candidate promised API stability, and RC.5 broke that promise badly and holistically. Please bear with me when I don't feel particularly compelled to weigh my words carefully before posting.

**Comment by Tragetaschen** [comment]
I have updated [the Plunker](http://plnkr.co/edit/eaBFK7ALDHoJmN7iBrb0?p=preview) to use a module in main.ts. The unrelated error message remains the same, though (this time in Edge):

```
"(SystemJS) Error: Unexpected value 'undefined' imported by the module 'AppModule'
	   at BaseException (eval code:5116:13)
	   at Anonymous function (eval code:13231:29)
	   at Array.prototype.forEach (native code)
	   at CompileMetadataResolver.prototype.getNgModuleMetadata (eval code:13215:21)
	   at RuntimeCompiler.prototype._compileComponents (eval code:15845:13)
	   at RuntimeCompiler.prototype._compileModuleAndComponents (eval code:15769:13)
	   at RuntimeCompiler.prototype.compileModuleAsync (eval code:15746:13)
	   at PlatformRef_.prototype._bootstrapModuleWithZone (eval code:9991:13)
	   at PlatformRef_.prototype.bootstrapModule (eval code:9984:13)
	   at execute (eval code:55:13)
	Error loading http://run.plnkr.co/eyLuFuletIIyXZNl/src/main.ts"
```

**Comment by Tragetaschen** [comment]
Ok, something is weird with the other above Plunker and I don't see it.

I have copied the code over to [a fresh one](http://plnkr.co/edit/pVocIoVwGyb8C93589z0?p=preview) and my issue reproduces with the `NgModule` infrastructure.

When you rename the class in `pages/spectrum.component.ts` to something else, the error goes away. Then an expected one appears regarding the router not being able to match the url.

**Comment by woppa684** [comment]
Also, commenting out line 8 in app-routes.ts (so the route for 'Spectrum' makes the error go away (without renaming a class). It seems that the router definitely has something to do with it.

**Comment by Tragetaschen** [comment]
Ok, the problem is rather simple.

Angular2 internally uses a string representation for all kinds of stuff (`stringify` from `facade/lang`) and both components have the same string-name, although they come from two entirely different ES6 modules. Since `rc.5` decided to just throw away any kind of scoping and merge anything automatically at the top, there are now two things named `"SpectrumComponent"` to choose from in this **global** scope. Naturally, this isn't an error in itself.

Apparently, this is what the blog entry meant with "shouldn't break", because what could possibly go wrong when you take a properly modularized application and merge everything in one giant namespace.

Good work, angular team.

**Comment by zoechi** [comment]
> So you don't know what the problem is, but you assume a fix will be necessary just within deprecated APIs?
>
Maybe it's already time to close this then (seems like a waste of time).

I just think that if you think this is a bug, you should demonstrate it with the newest Angular2 version, otherise it's not clear if there is still anything to do.

**Comment by Tragetaschen** [comment]
btw: `has: repro`

**Comment by MarkPieszak** [comment]
@pkozlowski-opensource @zoechi  The problem comes from the fact that yes, 2 Components have the same name (SpectrumComponent in this case), and when one is being used in a template `<spectrum ... />`, it's somehow calling the **other** Component.

It looks to me it's happening here when the Routes are declared. Somehow this `Component` declaration in Routes, is *overriding* the Injector perhaps? When the other template calls "SpectrumComponent" (even though it's importing it from a different location) it's getting it from THIS one here in Routes.

```
import {SpectrumComponent} from './spectrum.component.ts'; // <-- this is the one overriding
import {UsingSpectrumComponent} from './using-spectrum.component.ts';

export var AppRoutes: Routes = [
  { path: '', Component: UsingSpectrumComponent},
  //{ path: 'Spectrum', Component: SpectrumComponent}, // <-- when commented out it works fine
];
```

@Tragetaschen Also, I'm not sure how insulting an open source community of developers is going to help you in any way.

**Comment by leocaseiro** [comment]
I've just got the same issue here. I confirm this issue.

I was trying to Include a file called App.ts in my custom ngModule and I was having a generic error:

`Unexpected value 'undefined' imported by the module``

However, If I rename the file to App.ts to Appp.ts, the bug goes away and my app works fine.

**Comment by chuckjaz** [comment]
@leocaseiro Can you submit a different issue with what you are seeing?

The original issue is no longer relevant as it was regarding how the bridge code from the NgModule system worked with NgModule. Also, the issue @Tragetaschen mentioned above, using the name of the component, in certain situations, as an identity key. We now use the constructor function exclusively for identity.

**Comment by Tragetaschen** [comment]
I was able to remove the workaround in my actual application.

Thanks.
