### ISSUE TITLE
Is Style in Animation can use value for component attribute

### ISSUE THREAD

**Issue by golfapipol** [angular/angular#10859]
*_I'm submitting a *_

```
[x] feature request
```

**Expected/desired behavior**
Is Style in Animation can use value for component attribute like

```
this.offsetHeight = `-${this.el.nativeElement.offsetHeight}px`;
```

```
trigger("appear", [
  transition('* => void', [
    style({ opacity: 1 }),
    animate(100, style({top: expr('$window.offsetHeight')})) 
  ])
])
```

or it should can pass function in style for dynamic value? 

```
animate(100, style(componentMethod()) 
```

**What is the motivation / use case for changing the behavior?**
for component that have to handle like unpredictable height, animate that play with offsetHeight (or somethings else)

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all] 
- **Language:** [all]

**Comment by zoechi** [comment]
dup of #9668 ?

**Comment by matsko** [comment]
This is coming. The API is still being planned. Me and @ThomasBurleson will post updates here and in #9668 as we have more info.

**Comment by matsko** [comment]
Closing this for now. 5.x. will very much likely have this feature built-in.
