### ISSUE TITLE
Little "Tour of Heroes" mistakes

### ISSUE THREAD

**Issue by diegotascon** [angular/angular#10851]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Following the "Tour of Heroes" I have found that in some points the application crashes when it is expected to work according to the instructions. For example:

- In "6. Routing", just before "Select a Hero in the HeroesComponent" it says "Refresh the browser and select a hero from the dashboard; the app should navigate directly to that hero’s details.". When I did it the application crashed (I haven't kept the console error. Something about hero not declared in my-hero-detail). It was necessary to remove from the template de <my-hero-detail> tags and it worked again.

- In "7. Http", the first app.modules.ts sample makes reference to "HeroSearchComponent" (which, I imagine, will be declared later): "import { HeroSearchComponent } from './hero-search.component';" and in the declarations section. In the (final) version of the file, they've been removed.

- In "7. Http", the "hero.service.ts (new constructor and revised getHeroes)" sample invites to add the constructor "constructor(private http: Http) { }". But it only invites to import "import 'rxjs/add/operator/toPromise';", crashing the application ("Evaluating http://localhost:3000/app/main.js", "Error loading http://localhost:3000/app/main.js" are seen in the console). Far below I see a new version of hero.service.ts where Http is imported. Adding "import { Http } from '@angular/http';" to hero.service.ts it works.

**Expected/desired behavior**

It would be great if yo could revise chapters 6 and 7 to avoid errors that lead to an application crash. A mark or more text indicating whether the application could be tested or not would be great for newbies as me, so we are sure the any error is due to a mistake following the instructions and not a mistake provoked by the tutorial.

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

Improving the learning experience with the tutorial.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Firefox 47.0.1  ] 
 
* **Language:** [TypeScript X.X]

**Comment by brandonroberts** [comment]
These issues should be opened at https://github.com/angular/angular.io

**Comment by diegotascon** [comment]
Then there is another issue with the "Report Issues" link in the tutorial :D.

Thanks for your tip, Brandon. I'll move the issue to angular.io.

**Comment by diegotascon** [comment]
Found that these issues have been already reported at https://github.com/angular/angular.io/issues/1697. Not resolved yet as of today.
