### ISSUE TITLE
2.0.0-rc.5 selector regression

### ISSUE THREAD

**Issue by jkporter** [angular/angular#10853]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
Some selectors that worked previously in rc4 are breaking in rc5

**Expected/desired behavior**
Selectors should work as they do in CSS and previous versions and not cause errors

**Reproduction of the problem**
I have components one with a selector of 'div.feed' and another with selector of '#subscriptionList div'. In rc.5 I now get 'more than one component' error where previously it would work as expected. I updated '#subscriptionList div' and corresponding templates to '#subscriptionList div.child-subscription-listitem'. Which fixed the problem in Chrome & Firefox however still fails in Edge. The subscription list's divs are not recognized as being bound to component and fails because a non-native property is specified to be bound in the template.

More than one component: http://plnkr.co/edit/CF19y1MHroITUbUIqRWQ

**What is the expected behavior?**
No errors components bind to elements.

**What is the motivation / use case for changing the behavior?**
This is breaking change from rc.4. Selectors should work consistently and according to specs. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Chrome 52 | Firefox 47 | Edge 38 
 
* **Language:** all

**Comment by DzmitryShylovich** [comment]
Can u provide a plunker with min reproduction? I don't think it's related to css selectors.

**Comment by jkporter** [comment]
Updated with plunker

**Comment by zoechi** [comment]
AFAIK selectors like `'#subscriptionList ul'`, `'#subscriptionList div'` were never supposed to work. A selector can only target a single element and not depend on an element being a child, descendant, sibling, ... of another element (must not contain space, `>`, `+`)

**Comment by pkozlowski-opensource** [comment]
@zoechi is totally right - we should be throwing for non-simple selectors: #2589
