### ISSUE TITLE
Publish AtScript -> ES6 transpiled files with *.js suffix

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#1085]
Currently npm-published ES6 files got *.es6 extension which complicates the build process. If there are no strong technical reasons for naming those as *.es6, we should stick to *.js.

(BTW: to be correct we should use *.es2015 now :-))

This is part of the build / packaging discussion, //cc: @rkirov

**Comment by jamm** [comment]
+1

**Comment by rkirov** [comment]
My latest thinking is that .es6 output itself is of limited value and we should converge to es5 output - obviously with `.js` and pure source - with `.ts`.

**Comment by pkozlowski-opensource** [comment]
@rkirov this is very true provided that migration to TS is done. So I was referring to the current AtScript situation. Depending on the time-frame of TS migration tackling this item might or not might not make sense. At the same time this is just an extension name so I figured it is worth to make people live easier today.

**Comment by cssensei** [comment]
The `.ts` naming convention makes more sense since typescript it's here to stay in angular 2.0. @rkirov :+1:

**Comment by mhevery** [comment]
because of ts`fy closing
