### ISSUE TITLE
Improve component auto-declaration for router compiler

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#10862]
There seems to be a bug in the compiler that it is overly greedy in which Components it automatically declares.

Consider the following:
`MyAppModule` imports `MyChildModule`, and from the routes used in `MyAppModule`, I have setup a path that points to `MyChildComponent` delcared by `MyChildModule`.

When I attempt to compile this code (AOT or JIT), I get an error that the component `is part of the declarations of 2 modules: MyChildModule and MyAppModule`.

`MyChildComponent` is NOT declared by MyAppModule, and shouldn't automatically be declared by the compiler.

Reproducing plunkr: http://plnkr.co/edit/ieR9rxA7bpnuMc1hbUs0?p=preview

cc: @vsavkin

**Comment by Foxandxss** [comment]
I hear you. I had the same thing happening to me today and the error wasn't any clear, I had to start commenting stuff out until I realized it was just importing components in the router.

**Comment by wardbell** [comment]
I'm still puzzled why an `entryComponent` must be declared if it is never referenced in a component template. It might have something to do with fear of component kidnapping.

As for your use case, I wonder if it's a timing thing. What if you import `MyChildModule` before calling `RouteModule.forRoot`?

**Comment by vsavkin** [comment]
This has been fixed in master a coupe of weeks ago. Closing this issue.
