### ISSUE TITLE
application stopped working when migrated from rc4 to rc5 

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#10879]
My running application stopped working when i migrated from rc4 to rc5. I am using the following bootstrap statement :+1: 

upgradeAdapter.bootstrap(document.body, ['myATTApp'], { strictDi: true });

The error description is as below :+1: 
Error: TypeError: Cannot read property 'injector' of null
        at Object.eval (http://localhost:3000/node_modules/@angular/upgrade//bundles/upgrade.umd.js:881:75)
        at Object.i [as invoke](http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16501)
        at http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:17261
        at n (http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16251)
        at Object.i [as invoke](http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16466)
        at http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:17261
        at n (http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16251)
        at i (http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16466)
        at Object.instantiate (http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16637)
        at Object.<anonymous> (http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16893)
    Evaluating http://localhost:3000/main.js
    Error loading http://localhost:3000/main.js {originalErr: TypeError: Cannot read property 'injector' of null, stack: (...), message: "TypeError: Cannot read property 'injector' of null…n.js↵  Error loading http://localhost:3000/main.js"}message: "TypeError: Cannot read property 'injector' of null↵        at Object.eval (http://localhost:3000/node_modules/@angular/upgrade//bundles/upgrade.umd.js:881:75)↵      at Object.i [as invoke](http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16501)↵      at http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:17261↵     at n (http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16251)↵     at Object.i [as invoke](http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16466)↵      at http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:17261↵     at n (http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16251)↵     at i (http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16466)↵     at Object.instantiate (http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16637)↵        at Object.<anonymous> (http://localhost:3000/lib/internal/myatt-framework.pkg.min.js:5:16893)↵    Evaluating http://localhost:3000/main.js↵ Error loading http://localhost:3000/main.js"originalErr: TypeError: Cannot read property 'injector' of nullmessage: "Cannot read property 'injector' of null"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }**proto**: Errorstack: (...)get stack: function () { [native code] }set stack: function () { [native code] }****

**Comment by kriceTK** [comment]
Having the same issue, when looking into it we see that we now need to pass in a module to the new UpgradeAdapter({module}); but having created a new module and passed it in we still are getting that same error. Will update as we work through this.

**Comment by texel** [comment]
This looks like the same issue as #10992

**Comment by sgrinich** [comment]
@kriceTK were you able to find a solution to this error? I'm in the same boat with this problem.

**Comment by kriceTK** [comment]
@sgrinich we have not yet, we went down the path of trying to make modules for all of our Angular 2 code but we couldn't find out how to bootstrap it correctly (it looks like the issue comes from how you bootstrap a ngUpgraded application), so we decided to lock at rc4 until this is resolved or there is documentation on how to move forward.

**Comment by sgrinich** [comment]
I've solved my issue (at least for the time being!). I simply needed to init the TestBed, like so:

`beforeEach(() => { TestBed.initTestEnvironment( BrowserDynamicTestingModule, platformBrowserDynamicTesting() ).configureTestingModule({ ... ]}); });`

Don't forget to include the import: 
`import {BrowserDynamicTestingModule, platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing'; `

**Comment by kriceTK** [comment]
@sgrinich our problem is this is our production application that is running partially in angular 2 (RC4) and partially in Angular 1.5 and if I try and move to RC5 our entire app wont work.

**Comment by kevindqc** [comment]
@kriceTK Did you take a look at the workaround in #10992 ? If you have any .run block, you might need to use setTimeout and use $injector manually instead of using normal dependency injection.

Maybe RC6 fixes the problem though

**Comment by jtomaszewski** [comment]
For me it was the same problem as @kevindqc described and the same workaround helped in my case. 

RC6 didn't fix the problem (I'm using it).

**Comment by DzmitryShylovich** [comment]
@vasuneet is this still valid?

**Comment by vasuneet** [comment]
not valid as i moved to latest version.

**Comment by DzmitryShylovich** [comment]
@vasuneet then close the issue pls. thx

**Comment by vikerman** [comment]
Obsolete
