### ISSUE TITLE
Router: lazy loaded module is loaded even when route's activate guard rejects

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10877]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Even when the `CanActivateGuard` on the lazy route definition rejects the route, the router still loads the module.

**Expected/desired behavior**

Should not load module if the `CanActivate` rejects.

**Reproduction of the problem**

http://plnkr.co/edit/KCEYVGgcm6fD1oQodNKM?p=preview

Try to go to "Heroes". 

See `app/app.module.ts` for the guard and routes

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all  ] 
 
* **Language:** [all]

**Comment by johnpapa** [comment]
also reproduced here in master https://github.com/johnpapa/event-view

**Comment by DzmitryShylovich** [comment]
U should use CanLoad instead of CanActivate if u want to prevent lazy route loading.

**Comment by wardbell** [comment]
That was it, @DzmitryShylovich .  I updated my plunker to make that clear (`canActivate` might still have a role to play _after the module is loaded_).

We need to document it and I have created an issue for that:
https://github.com/angular/angular.io/issues/2129

My new problem is that returning false raises a routing exception that I do not yet know how to handle:
```
EXCEPTION: Error: Uncaught (in promise): Error: Cannot load children because the guard of the route "path: 'heroes'" returned false
```

**Comment by brandonroberts** [comment]
I've filed an issue for this one https://github.com/angular/angular/issues/10585

There is a `NavigationError` event emitted if it fails that you could handle, but ideally you would navigate somewhere else before returning false in the `canLoad` guard.

**Comment by wardbell** [comment]
To be clear, the `canLoad` should behave the same way as `canActivate`. It should not throw a promise error.

**Comment by vsavkin** [comment]
Dup of #10585
