### ISSUE TITLE
can't get right TYPE of data from the router resolve

### ISSUE THREAD

**Issue by jerry-i** [angular/angular#10874]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
service method
```js
 getMeetUpDetail(id: number): Observable <any> | Promise <any> | any {
      let detail = this.af.database.object(`/meetup/${id}`);
      console.log('detail service call------'+new Date().getTime());
      console.log(detail);
      debugger;
      return detail;
  }
```
this method  return a `FirebaseObjectObservable` type object.

<img width="751" alt="meetup events google chrome today at 11 20 24 am" src="https://cloud.githubusercontent.com/assets/11937539/17723426/a1dba65a-646c-11e6-82eb-e74f6b73105a.png">

resolve method
```js
@Injectable()
export class MeetupDetailResolve implements Resolve < Meetup > {
  constructor(private ms: MeetUpService, private router: Router) {}

  resolve(router: ActivatedRouteSnapshot): Observable < any > | Promise < any > | any {
    console.log('resolve method'+ new Date().getTime());
    let id = +router.params['id'];
    return this.ms.getMeetUpDetail(id)
    .subscribe((meetup) => {
      console.log('router resolve ------'+new Date().getTime());
      console.log(meetup);
      debugger;
      if (meetup) {
        debugger;
        return meetup;
      } else {
        this.router.navigate(['/meetup/list']);
        return false;
      }
    });
  }
}

```
here I got the right type.

<img width="772" alt="meetup events google chrome today at 11 22 29 am" src="https://cloud.githubusercontent.com/assets/11937539/17723949/ae89d314-6470-11e6-9a76-10d8c80ebbe1.png">

component init
```
ngOnInit(){
    this.route.data.forEach((data:{meetup: Meetup})=>{
      debugger;
      this.meetup = data.meetup;
      console.log('ng onInit------'+new Date().getTime());
      debugger;
    })
    console.log(this.meetup);
  }
```
here comes the problem, int the method `ngOnInit`,the `meetup` is type of `Subscriber` 

<img width="580" alt="new issue angular-angular google chrome today at 11 54 19 am" src="https://cloud.githubusercontent.com/assets/11937539/17724071/7db6c75a-6471-11e6-84ce-598788233f2e.png">

**Expected/desired behavior**
`activedRoute.data` can not return the right type of data.

**What is the expected behavior?**
In the `ngOnint` method, I should get the data `meetup` as the same as that in the  `resolve method`.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
* **Angular-router version:** 3.0.0-rc.1
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript 2.0.0]

**Comment by DzmitryShylovich** [comment]
```
return this.ms.getMeetUpDetail(id)
    .subscribe((meetup)
```
here's your mistake. As u can see in the [docs](https://github.com/ReactiveX/rxjs/blob/master/doc/subscription.md#subscription) `subscribe` method returns a subscription (Subscriber extends Subscription).
Just use `map` instead

```
return this.ms.getMeetUpDetail(id)
    .map((meetup) => ...);
```

**Comment by jerry-i** [comment]
I chage this.
```js
return this.ms.getMeetUpDetail(id)
    .map((meetup) => ...);
```
but It seams that the resolve can't success. event though I returned the Object ,  router fails.
<img width="994" alt="file transfer wechat today at 3 26 10 pm" src="https://cloud.githubusercontent.com/assets/11937539/17727935/fdcdbe9a-648e-11e6-8ba1-b90324d97013.png">

**Comment by DzmitryShylovich** [comment]
try 
```
return this.ms.getMeetUpDetail(id)
    .take(1)
    .map((meetup) => ...);
```

**Comment by jerry-i** [comment]
@DzmitryShylovich  thx! 😄 It works.But why?

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/9613#issuecomment-228748731

**Comment by sod** [comment]
If you want to learn more about Observables, the official rxjs documentation got pretty awesome in the last couple of months. See http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-take

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got answered. Thnx @DzmitryShylovich and @sod for helping out!
