### ISSUE TITLE
TypeError: _this.location.isCurrentPathEqualTo is not a function

### ISSUE THREAD

**Issue by Aarti15** [angular/angular#10876]
As mentioned in #10847 upgraded to RC.5  but I am still getting same error.
"@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-alpha.7",
    "@angular/router-deprecated": "2.0.0-rc.5",
    "@angular/upgrade": "2.0.0-rc.5",

please let me know the working solution

**Comment by ericmartinezr** [comment]
Dude, seriously... Upgrade everything, including the router. Remove the deprecated router also, nuke the node modules folder. There's an issue template you MUST follow when opening an issue...

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by pkozlowski-opensource** [comment]
@Aarti15 As mentioned in #10847 this _not_ the right forum to ask support questions. Please don't open duplicate issues like this.
