### ISSUE TITLE
Introduce a concept of DirectiveRef

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1087]
A `DirectiveRef` represents internal reference to a directive, which the application can get a hold of to interact with. The `DirectiveRef` is subclassed to `ComponentRef` and `DecoratorRef` to match the directive concepts

## API

```
class DirectiveRef {
  injector:Injector;

  /// Used for setting the public property (processes the pipes)
  setProperty(name:string, value);

  getEvents():Array<string>;
  }

class ComponentRef extends DirectiveRef {
  dispose();
}
```

All of the component/directive refs should return `DirectiveRef`. This includes `bootstrap()`, `DynamicComponent`, and `Overlay`. The API allows setting properties, events, and disposing of the reference.

## Bootstrap

Given this component
```
@Component({
  selector: 'app',
  bind: {'text': 'title'}
})
@Template(...)
class App {
  constructor(@EventEmitter('tick') onTick:Function) { ... }
}
```

We may wish to bootstrap it as an application and bind to its properties as well as bindings.

```
var appRef:ComponentRef<App>;
var appRefPromise:Promise<ComponentRef<App>> = bootstrap(App, {
  // support registering events on directive creation
  'tick': function(data) {
    // support disposing of an app
    appRef.dispose();
  }
});
appRefPromise.then((ref:ComponnentRef<App>) {
  appRef = ref;
  // support setting properties on directive references
  appRef.set('text', 'some value');
});
```

## DynamicComponent

```
@DynamicComponent({
  selector: 'dynamic-comp'
})
class DynamicComp {
  helloCmp:HelloCmp;
  constructor(loader:PrivateComponentLoader, location:PrivateComponentLocation) {
    loader.load(HelloCmp, location).then((helloCmpRef:ComponentRef<HelloCmp>) => {
      this.helloCmp = helloCmp.instance;
    });
  }
}

@Component({
  selector: 'hello-cmp'
})
@Template({
  inline: "{{greeting}}"
})
class HelloCmp {
  greeting:string;
  constructor() {
    this.greeting = "hello";
  }
}
```

### Code Generation

The code generation should create a concrete class for each Directive which would also be `DirectiveRef` The `DirectiveRef` would contain the public facing API an processing. This would include pipe processing, and event listening.

### Injection

The `DirectiveRef` should be injectable into the directive as a special object. It can than be used by other services as a form of reference. 

NOTE: The reference contains both the location (visual reference) as well as logical (location in the tree) reference. It is up to the service to chose either aspect of the ref.

**Comment by yjbanov** [comment]
@vsavkin Should we close this one and move #1152 to M7?

**Comment by vsavkin** [comment]
@yjbanov some directive ref object will still be required, but it just contain the directive's meta information and won't have `set`.

**Comment by vsavkin** [comment]
I don't know what criteria we use to move issues to M7. I am planning to do #1152, but I don't know if it should be in M7 or not.

**Comment by yjbanov** [comment]
We want overlays, router, component testbed and access to native DOM done in M7 + fix some nasty bugs. Anything that blocks those should be in M7 and considered highest priority. The rest can be bumped to M8.

**Comment by mhevery** [comment]
I think #1152 is independent from this. 

Progress update: DirectiveRef is introduced by @jelbourn, and he is working on unifying the `bootstrap`, `DynamicComponent` and `Overlay`s

**Comment by mhevery** [comment]
f45281a10afbbd6052427bd358e1d337fdb78831
