### ISSUE TITLE
angular2 rc.5 custom input, 'No value accessor for form control with unspecified name attribute'

### ISSUE THREAD

**Issue by amarewgs** [angular/angular#10878]
please the stackoverflow link which contains codes for my issue, http://stackoverflow.com/questions/38958347/angular2-rc-5-custom-input-no-value-accessor-for-form-control-with-unspecified

**Comment by ericmartinezr** [comment]
... you already opened the question in SO, there's no point on opening it here

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
