### ISSUE TITLE
Cannot find module @angular/router

### ISSUE THREAD

**Issue by gtzinos** [angular/angular#10880]
I followed this guid https://angular.io/docs/ts/latest/tutorial/toh-pt5.html but i get this error message from visual studio code Cannot find module @angular/router

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by gtzinos** [comment]
Guys, here is the solution 

npm remove @angular/router --save // will remove the RC router
npm install @angular/router@3.0.0-alpha.7 --save // will install the latest router

**Comment by ericmartinezr** [comment]
Fwiw the latest router is RC1, not alpha 7

**Comment by gtzinos** [comment]
I have already used it. Nothing..

**Comment by kaarthi84** [comment]
import {ActivatedRoute,ParamMap } from '@angular/router';

I'm getting error like has no exported member 'ParamMap'

I installed the latest router version also but still facing an issue could anyone please help on this.
