### ISSUE TITLE
Https calls that set Content-Type to application/json fail as of rc.5 after normalization is added to Header

### ISSUE THREAD

**Issue by LMFinney** [angular/angular#10885]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As of rc.5, https calls that set Content-Type to 'application/json' fail this message:
```
TypeError: Cannot read property 'toString' of null
    at Request.Body.text (https://localServer/path/main.bundle.js:176324:26)
    at Request.getBody (https://localServer/path/prep/main.bundle.js:176883:29)
    at Observable._subscribe (https://localServer/path/main.bundle.js:176187:37)
    at Observable.subscribe (https://localServer/path/main.bundle.js:139:62)
```

The error occurs in the last line of this function because this._body is null: 
```typescript
    Body.prototype.text = function () {
        if (this._body instanceof url_search_params_1.URLSearchParams) {
            return this._body.toString();
        }
        if (this._body instanceof ArrayBuffer) {
            return String.fromCharCode.apply(null, new Uint16Array(this._body));
        }
        if (http_utils_1.isJsObject(this._body)) {
            return lang_1.Json.stringify(this._body);
        }
        return this._body.toString();
    };
```

The change made for #9452 introduced this behavior by changing 'Content-Type' to 'content-type' in the header. Although the header values are supposed to be case-insensitive, this seems not to be the case in practice in this application.

The calls fail early enough that nothing appears in the Chrome Network tab.

I can work around this by changing `normalize` in node_modules/@angular/http/src/headers.js to just return the argument, but that is not a sustainable solution.

**Expected/desired behavior**
Https calls with headers succeed.

**Reproduction of the problem**
I don't know how to reproduce the problem with a plunker because a prerequisite is being able to make an https call, and I don't know how to do that in plunker.

I'm able to reproduce it locally by having the following in my AppComponent (replacing the url as needed):
```typescript
  constructor(http: Http) {
    const config:RequestOptionsArgs = {headers: new Headers()};
    config.headers.append('Content-Type', 'application/json');

    http.get('https://localServer/path/', config).toPromise()
      .then(response => console.log('response', response));
  }
```

**What is the expected behavior?**
Https calls with headers succeed.

**What is the motivation / use case for changing the behavior?**
Being able to define content-type as json on https calls.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Chrome 52.0.2743.116 m and Firefox 35.01 
 
* **Language:** TypeScript 2.0

**Comment by pkozlowski-opensource** [comment]
This is already fixed in master, will be part of RC6.

**Comment by LMFinney** [comment]
@pkozlowski-opensource Thanks for the quick response.

Could you point me to the fix? I'm curious how this was resolved.

**Comment by pkozlowski-opensource** [comment]
@LMFinney see 7cd4741fcbbea6d58281b3055d1ae7691de1662b
