### ISSUE TITLE
Traceur error when using NgModule inside Rc.5

### ISSUE THREAD

**Issue by roby2001** [angular/angular#10881]
Simply updating my application from Rc.4 to Rc.5 without changing code works. Yet when I try to change my bootstrap to use an ` NgModule` and such I recieve the following error:

![image](https://cloud.githubusercontent.com/assets/16002302/17730495/9049f892-6471-11e6-8617-d6aa37d9a47c.png)

I stripped down the project to the most basic version I could think of ( like in the 5 mins quickstart ), the error persists. 

My first guess was that `system.js` was not properly mapping traceur, yet when I went over the 5 mins quickstart / my node modules the only code references I could find to traceur were in `system.src.js` from @angular.

What is causing this error and what should I do in order to fix it? Why is it requesting : `localhost:3000\traceur` only when I'm using `NgModule` ?

**Comment by pietie** [comment]
Do you have any multi line comments? 

I had traceur related errors after upgrading to rc5. Apparently angular bugs out on the parsing of /* */ comments so after I removed those my traceur errors went away.

**Comment by roby2001** [comment]
@pietie this totally goes on my list of top 10 retarded bugs ... Thanks a bunch!

**Comment by Robert3191** [comment]
Offtopic: I can confirm. He was very frustrated that day. :))

**Comment by sweeneyrobb** [comment]
spent a fair number of cycles trying to resolve this very issue. thanks for posting this. saved me more hours hunting for what was wrong.
