### ISSUE TITLE
3rd party library and change detection

### ISSUE THREAD

**Issue by guvam** [angular/angular#10883]
[ ] bug report 
[X ] feature request
[ ] support request

**Current behavior**
change detection is triggered after every event in 3rd party library.

**Expected/desired behavior**
somehow silence 3rd party libraries/components  so that it would not trigger change detection every event.

**Reproduction of the problem**
http://plnkr.co/edit/uYfJrzJrcLzlgp7IaZoi?p=preview
zooming and moving around would triggers 100+ change detection events per second.
i will be even worse when i have to use mouseover event.

**What is the motivation / use case for changing the behavior?**
application speed.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all  ] 
 
* **Language:** [TypeScript 2.0.0]

**Comment by otodockal** [comment]
& click on a marker :)

**Comment by otodockal** [comment]
maybe this issue should be created in [Zone.js](https://github.com/angular/zone.js) repo as an interoperability problem...

**Comment by sod** [comment]
Thats an issue that can be fixed in in the library itself

he seems to register events left and right like in:
https://github.com/SebastianM/angular2-google-maps/blob/master/src/core/directives/google-map-circle.ts#L210-L244
and google maps will most likely register events also:
https://github.com/SebastianM/angular2-google-maps/blob/master/src/core/services/google-maps-api-wrapper.ts#L29

If an event should not trigger change detection, it can be executed outside angulars zone.

So instead of 
```typescript
const map = new google.maps.Map(el, mapOptions);
const myEvent = Observable.fromEvent(window, 'resize');
```

do:
```typescript
const map = this._zone.runOutsideAngular(() => {
    return new google.maps.Map(el, mapOptions);
});
const myEvent = this._zone.runOutsideAngular(() => {
    return Observable.fromEvent(window, 'resize');
});
```

**Comment by otodockal** [comment]
@sod great answer, thank you. I've tested it also with [leafletjs](http://leafletjs.com/)...

```typescript
const map = this._zone.runOutsideAngular(() => L.map(el, {
    zoomControl: false,
}).setView(latlng, zoom))

map.addLayer(streetLayer)

// outside
map.on('dragend', () => this.onMapDragend.emit())
// run CD
map.on('click', () => this._zone.run(() => this.onMapClick.emit()))
```

**Comment by kara** [comment]
Excessive change detection calls should be fixed in the third-party library itself, not in this repo.

**Comment by chrisnicola** [comment]
@kara I think there might be something here, even though I agree this example is perhaps not the best.

In (https://github.com/WealthBar/a2d3) I don't have excessive event emitting, or much at all but I have run into the same problem updating from RC.3 to RC.5. Change detection is only firing once on load and ignoring any further changes.

Specifically, in the example component here (https://github.com/WealthBar/a2d3/blob/master/src/app/app.ts) you can see it does a number of updates to properties when are then bound into the D3 chart directive's data property. Some are just done in a timer loop, another is done using a CSV data loading directive which fires and event. The event is fired after it loads the CSV and the property in the `App` component is set, I've verified all of that. However the [data property](https://github.com/WealthBar/a2d3/blob/master/src/angularD3/directives/chart.ts#L97) of `D3Chart` is never updated after the initial load when it is undefined.

Interestingly, I can kind of force it to work by triggering other change detection cycles, like putting in a superfluous text input, binding it and typing in it, then it starts to get some of the change unreliably.

This was definitely working in RC.3 but does not work with RC.5. I'd be happy to help figure out what is happening here. I have a branch updated to RC.5 which I'll push up and link here shortly.

**Comment by chrisnicola** [comment]
Here is the upgraded branch: https://github.com/WealthBar/a2d3/pull/1

Any ideas would be greatly appreciated!

**Comment by chrisnicola** [comment]
@kara I completely misread this issue and assumed that the original problem was change detection *not* firing, as it turns out it was firing too often.

I'll open a new issue with my problem if you feel it has merit. If I've just done something stupid just let me know.

**Comment by dmckinney1229** [comment]
@chrisnicola I have experienced the same behavior and found this issue for it: https://github.com/angular/angular/issues/10915

**Comment by chrisnicola** [comment]
Thanks @dmckinney1229 I'll copy my comments there.
