### ISSUE TITLE
Unable to create child injector from AppModuleInjector

### ISSUE THREAD

**Issue by benjamincombes** [angular/angular#10882]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Before rc5, when injecting an Injector instance into a service, we got a ReflectiveInjector instance, allowing to create child injector from it using resolveAndCreateChild.
After updating to rc5, when injecting an Injector, we get an AppModuleInjector instance, which doesn't allow creating a child instance as resolveAndCreateChild doesn't exist on it (didn't find documentation on it though).

**Expected/desired behavior**
Getting a subclass of ReflectiveInjector, or another way to create a child of AppModuleInjector would be great.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript 2.0.0 beta]

**Comment by sod** [comment]
You still can.

```typescript
import {ReflectiveInjector} from '@angular/core';

const childProviders = [];
const childInjector = ReflectiveInjector.resolveAndCreate(childProviders, injector);
```

and the second argument `injector` will be the parent of the new injector.

**Comment by benjamincombes** [comment]
Thanks a lot for your help @sod, it works perfectly!
