### ISSUE TITLE
In docs, Basics/Architecture/Directives should include a link to Developer Guide/Attribute Directives

### ISSUE THREAD

**Issue by colinmorris** [angular/angular#10893]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
The [Directives](https://angular.io/docs/ts/latest/guide/architecture.html#!#directives) section in Basics/Architecture describes Structural and Attribute directives, but the only examples it gives are built-ins, and it doesn't say anything about writing custom directives of those varieties. 

Fortunately, there's a nice [chapter](https://angular.io/docs/ts/latest/guide/attribute-directives.html) tucked away in a different section of the docs on implementing a custom attribute directive. I think it'd be helpful to link to in this context.

**Comment by ericmartinezr** [comment]
Hey @colinmorris would you mind suggesting it in thr website/tutorial repo https://github.com/angular/angular.io

**Comment by colinmorris** [comment]
Whoops, [done](https://github.com/angular/angular.io/issues/2134).
