### ISSUE TITLE
routerLink outside a link should have a tabindex property

### ISSUE THREAD

**Issue by Gillespie59** [angular/angular#10895]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When we use the routerLink directive on on element other than a link, the element may not be focusable

**Expected/desired behavior**

Like ngAria, we should make automatically an HTML element with routerLink focusable. We should add a tabindex if not defined already by the developer. 

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** all
- **Language:** all

**Comment by DzmitryShylovich** [comment]
@gkalpak but `tabindex` is not an aria attribute.

**Comment by gkalpak** [comment]
I was referring to things whose purpose is to make the app more accessible in general.

**Comment by simeyla** [comment]
This appears to have been done and I don't like it. How to disable this behavior! I agree routerLink should not be setting tabindex on my behalf. I tried to apply a routerLink to a mat-row in a mat-table and it just looks awful with a focussed outline. I can disable the outline with css but then it still takes focus. Not a fan of this at all.
