### ISSUE TITLE
Service for querying positional/size information

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1089]
A service which given a [`DirectiveRef`](https://github.com/angular/angular/issues/1087) can return position information about the component.

### API
```
@Componte({
  selector: 'some-component'
})
@Template(...)
class SomeComponent {
  constructor(ref:ComponentRef, ruler: Ruler) {
    ruler.measure(ref).then((rect:Rectangle) {
      rect.top/width/height/etc..
    })
  }
}
```

See: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

**Comment by jelbourn** [comment]
Does it make sense to allow the user to specify _which_ properties their querying for? We might have to check if there is a performance cost to just pulling everything.

The measurements would also have to give you scroll info (scrollTop, scrollWidth, scrollHeight)

**Comment by naomiblack** [comment]
@pkozlowski-opensource can you own this one?

**Comment by mhevery** [comment]
Just use `NgElement` until the `DirectiveRef` is ready

**Comment by pkozlowski-opensource** [comment]
@jelbourn it looks like new browsers give height / width info from the `getBoundingClientRect()` call: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect so we get this info "for free".

For the other properties you need - maybe we should have a separate methods on the Ruler, in addition to `measure`?

Here is my proposal: let's get the first version with the `measure` method and expand the API as use-cases surface. How does it sound?

**Comment by mhevery** [comment]
@pkozlowski-opensource it depends what you mean by `getBoundingClientRect()` being free. A call to that API may cause browser to relayout, which is relatively slow. But once we have a layout the call to any API which return positional information is essentially free.

**Comment by pkozlowski-opensource** [comment]
@mhevery what I meant is that we got a bunch of properties out of `getBoundingClientRect()` call, so as soon as we decide to call it we can return all it has for us. But of course querying DOM is never "free"...
