### ISSUE TITLE
Router: location.path is old URL during all component hooks. Updates after a tick.

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10909]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request 
```

**Current behavior**

The `location.path()` value remains the old URL after a component's Lifecycle Hooks have been called.

After a tick, the `location.path()` value becomes the current URL.

Have been told that this change arrived within the last few RCs.

**Expected/desired behavior**

Expect `location.path()` to become the new URL at least by `ngOnInit`. By that time, the navigation is complete and all components should be in the DOM.

**Reproduction of the problem**

http://plnkr.co/edit/WUbTMlukBIYJF3WXYVIj?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [all ]

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/11063
