### ISSUE TITLE
Review render shadow DOM code & tests

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1090]
@tbosch 

I added unit-tests for shadow DOM strategy (plus some minor fixes) in https://github.com/angular/angular/commit/7d63bbcdd39246b643b00a59af5250b8721083e7

I had to `xit` one of the tests because the code that adds the attribute to the parent is gone. I'm assuming you removed it intentionally, so let's figure out what we want to do with the test. All other tests are passing.

**Comment by tbosch** [comment]
Yes, this was by purpose.
Looks good. Added a new test that captures the content of the disabled tests.
