### ISSUE TITLE
Add support for a scoped dependency injector without lazy loading

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#10901]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As far as I understand the current situation, all `providers` of non-lazy-loaded (is there a proper term yet?) modules are hoisted to the entry `NgModule`, because "what could be wrong with that" (paraphrasing the documentation for `NgModule`). Since the injector uses the stringified class name when searching the providers, all providers in an application now must have a unique class name, otherwise they start hiding each other and resolving from that one, global scope will instantiate the wrong thing.

In my current application design, I have a component that shows both a visualization component with "live" data from a server (meaning there is a collection of services that connect to the server and provide that live data to the component) as well as a help component where the same visualization component is fed by "fake" services that contain constant data to stage several possible visualizations. These are not lazy-loaded and are shown side-by-side.

**Expected/desired behavior**
Before `rc.5`, the `providers` were part of the component tree and naturally scoped quite narrowly. I was able to declare the necessary service providers so the visualization component saw the live data or the fake data depending on where it was instantiated in the component tree.
- **Angular version:** 2.0.0-rc.5

If this issue misses the point about the changes in dependency injection, than this is a great (I hate reading that word in the documentation...) opportunity to improve the documentation.

Otherwise, the "new" way how dependency injection works won't scale to "large" applications where seemingly distinct modules all of a sudden start breaking each other because an "internal" service is now part of a combined, global scope.

**Comment by qdouble** [comment]
@Tragetaschen you can still have providers directly in a component, that isn't being deprecated.

**Comment by Tragetaschen** [comment]
Ok, that's a relief (for my app), but the namespacing issue with otherwise unrelated modules and the conceptual difference between lazy-loaded and non-lazy-loaded modules remains. In addition to needing different class names throughout the application, it's possible that a working application starts breaking at one place when a seemingly unrelated module is converted to lazy loading and the provided services in that module now become available just "below" that module.

**Comment by chandermani** [comment]
But the app documentation, especially [the migration guide](https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html) (from RC4 to RC5) is not consistent with your comment @qdouble .
At the end it clearly mentions

> 5. Cleanup
> 
> For RC5, you can leave your components, directives and pipes in the directives and pipes properties of your @Component metadata. In fact, we automatically hoist (add) them to the NgModule to which they belong.
> 
> This option is temporary for backward compatibility. It will be removed in the final release of Angular 2.0.
> 
> Get ahead of the game and start moving your component directives and pipes into module declarations as soon as possible. We intend to delete all deprecated class, methods, and properties in the next RC.
> 
Pipes and directives references in @Component in RC5 are hoisted for backward compatibility. This will be removed in future version.
This implies @Tragetaschen observation still holds good. Is Angular removing component level provider?

**Comment by qdouble** [comment]
@chandermani Components and Pipes are hoisted up, however you can still have component scoped providers. You're confusing the pipe/directive deprecation to be related to providers when it isn't. Now ngModule providers are put into the the top of the application, but not component level providers.

**Comment by pkozlowski-opensource** [comment]
Sounds like there was some misunderstanding around the `providers` field on the `@Component` decorator. Reading through this issue I don't think there is anything actionable left at this point so I'm going to close this issue.
