### ISSUE TITLE
How can i have access to component from a custom validator ?

### ISSUE THREAD

**Issue by ClementVidal** [angular/angular#10914]
_**Note:** This is a duplication of a [stackoverflow question](http://stackoverflow.com/posts/38848089/edit) i asked a few weeks ago without any answer. 
I don't know if it's related to a bug or if it's the desired behavior. 
As i did not find answer on stackoverflow, i thought it's was the only place left to find one._

---

I'm writing a **custom validator** for a **custom form component**.  
Right now, i can inject dependencies in my custom validator such as services...

But i need to have access from within the validator to informations stored in the Component...
So i'm trying to inject the component in the Validator class, but this does not work..

Maybe i'm missing something with DI ?

**Look at this plunker [here][1]**

When you open it, everything should work fine. 
Uncomment everything in the validator constructor, like this:

    constructor( private test: TestService, private component: CustomFormControlComponent ) {
      test.serviceMethod();
      component.componentMethod();
    }

And check the log output to see that DI failed to resolve the second parameter ...

Any idea why ?

Thanks a lot !

  [1]: https://plnkr.co/edit/77muDxHCw7haGjTXWBcw?p=preview

**Comment by zoechi** [comment]
You already posted it on SO therefore no need to post it here again. There are also a lot of similar questions on SO already answered.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by kara** [comment]
As @zoechi mentioned, issues in this repo are for bugs or feature requests.    If you're looking for a simple example of how to access component methods in a validator, take a look at a similar plunker here: https://github.com/angular/angular/issues/10251#issuecomment-238737954.
