### ISSUE TITLE
Why do I have to use the browser bootstrap *and* import the BrowserModule?

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#10916]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The FAQ [What should I import?](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#q-what-to-import) goes through some lengths to describe that an entry module should import `BrowserModule` and all other modules must not import `BrowserModule` while on the other hand, bootstrapping the application already says "run in browser".

**Expected/desired behavior**
Most of the stuff the `BrowserModule` does should be part of the `bootstrap` call of either `platformBrowser()` or `platformBrowserDynamic()`. I don't see why I as developer have to specify multiple times that I'm running in the browser.

Note that this shouldn't affect the need to declare the `CommonModule`. It should be removed from the `BrowserModule` imports and any component needing it needs to import it without the distinction between entry point and other components.
- **Angular version:** 2.0.0-rc.5
- **Browser:**

**Comment by alxhub** [comment]
I don't think we will address this feature request specifically, but we do plan to simplify our bootstrapping API, and will consider this redundancy when we do.
