### ISSUE TITLE
Specifying routes in a feature module through imports is weird

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#10917]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a feature module contains `routing` information, it needs to be declared in the `imports` property of `NgModule`. The [documentation of that property](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#ngmodule-properties) only mentions use cases pointing "inside" the module. Having something in there that is supposed to be used outside the component by the surrounding router feels weird is is entirely counterintuitive. Also, there is the need to decide at module level whether it's an entry-point module (`forRoot`) or not (`forChild`).

**Expected/desired behavior**
There should be a dedicated, properly typed property (`routes: Routes`) for routing information. It should also be the the router's job to correctly gather that information and setup the necessary providers at the different levels.
- **Angular version:** 2.0.0-rc.5

**Comment by robwormald** [comment]
I believe this is the same issue described in https://github.com/angular/angular/issues/10958 - yes? A specific property on a module for routes is probably not feasible (as it couples to Angular's router at the expense of others) but we agree the behavior is a bit weird and will implement something similar to what's described in 10958. 

@Tragetaschen would you close this please if they are the same root issue?

**Comment by Tragetaschen** [comment]
I think, #10958 can fix my issue, but I have a little trouble distilling what the actual proposed / discussed solution is (likely my low level of blood sugar…). If I misunderstood, the following rambling should be ignored.

If it's just renaming `forChild` to `defineRoutes` (that's what I got from your comment) while still remaining in `imports`, it's still weird. I get what happens implementation-wise with the `ModuleWithProviders` type and how the routes are put in the dependency injector to be picked up by the router. But it feels like a kludge naming something `imports` (which makes stuff available to the module itself) while at the same time it actually exports or `provides` something to the "outer" application.

I anticipated your comment about coupling and it's perfectly valid.

What about putting `RouterModule` as-is in imports (without route definitions), so the components within the module get access to the necessary directives and components.
The (result of the) `defineRoutes` call would be put in the `provides` property instead.

```
@NgModule({
    imports: [RouterModule],
    provides: [RouterModule.defineRoutes(routes)],
})
```

**Comment by jmcgoldrick** [comment]
I agree that putting stuff that can augment/modify external things in `imports` seems semantically weird, in this case putting them in `exports` would make more sense. I don't think a typed property such as `routes` is the solution though, it should be something flexible enough for library authors to hook into.

Maybe `register` or `inject` or something that implies what is happening - you could still import the relevant module(s) if/as required, maybe something like:

```
NgModule({
    ...
    imports: [
        RouterModule
    ],
    register: [
        MenuModule.forChild(menu),
        RouterModule.forChild(routes)
    ]
})
```

**Comment by jmcgoldrick** [comment]
@robwormald I think what @Tragetaschen and I agree on is that it would be nice to have a clearer distinction on when a module alters the "outside world" and be able to more easily convey intent `imports`/`provides` does this (`provides` is probably a bit close to `providers` though)

**Comment by Tragetaschen** [comment]
Actually, I meant to reuse the excusing `provid*` property and not invent something new.
