### ISSUE TITLE
FormArrayName exported from './directives/reactive_directives/form_group_name'

### ISSUE THREAD

**Issue by gerhardboer** [angular/angular#10918]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In `src/forms.d.ts` and `src/directives/` FormArrayName is exported from `form_group_name` instead of `form_array_name`, where FormArrayName actually is exported.

`export { FormArrayName } from './directives/reactive_directives/form_group_name';`

**Expected/desired behavior**
`export { FormArrayName } from './directives/reactive_directives/form_array_name';`

**What is the expected behavior?**
To have FormArrayName exported

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5, forms 0.3.0

**Comment by kara** [comment]
`FormArrayName` is actually exported from `form_group_name.ts` in RC.5: https://github.com/angular/angular/blob/2.0.0-rc.5/modules/%40angular/forms/src/directives/reactive_directives/form_group_name.ts.   They need to be in the same file to pass a circular dependency check.

**Comment by gerhardboer** [comment]
Something was wrong with my dependencies apparantly. Sorry for the  inconvenience :)
