### ISSUE TITLE
[RC5] Using FormModule gives an "old forms module" warning

### ISSUE THREAD

**Issue by gyscos** [angular/angular#10913]
I'm using  `FormModule` from `@angular/forms` version 0.3.0, just like described on [the official guide](https://angular.io/docs/ts/latest/guide/forms.html).
In RC4, I had to use a `disableDeprecatedForms()` method, but it has now disappeared in RC5. Still, I get this warning message complaining about the "old" module.

The exact warning:

```
common.umd.js:3655 
      *It looks like you're using the old forms module. This will be opt-in in the next RC, and
      will eventually be removed in favor of the new forms module. For more information, see:
      https://docs.google.com/document/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/preview
```

Using typescript.
Happens on chrome, vivaldi, firefox.

**Comment by kara** [comment]
The error you pasted is coming from @angular/common, which is where the old forms API lives.  It's likely that you're importing something from there by mistake.  Can you reproduce in a plunker?

**Comment by gyscos** [comment]
I'm using some components from `@angular2-material`, which [apparently include `CommonModule`](https://github.com/angular/material2/search?utf8=%E2%9C%93&q=common).

Is this the reason for this warning?

**Comment by kara** [comment]
Material2 uses

**Comment by gyscos** [comment]
Oh, I'm using `ng2-chart`, which hasn't been updated to angular rc5 yet and looks like a prime suspect.

**Comment by tobias74** [comment]
How can this warning ever appear even if I am not importing DeprecatedFormsModule anywhere?

**Comment by zoechi** [comment]
@tobias74 Do you import any forms related stuff from `@angular/common`?

**Comment by tobias74** [comment]
I could solve it by removing all "FORM_DIRECTIVES" from the components. See this SO-Post: [http://stackoverflow.com/questions/39040015/angular-2-rc-5-it-looks-like-youre-using-the-old-forms-module](http://stackoverflow.com/questions/39040015/angular-2-rc-5-it-looks-like-youre-using-the-old-forms-module)

**Comment by kylecordes** [comment]
In converted lots of code to RC5 over the last week, we found that the "helpful" presence of the deprecated FORM_DIRECTIVES, form stuff in common, etc caused a lot more trouble than it saved. Oddly I think rc.6, which is planned to delete all that stuff, will make it *easier* to upgrade projects rather than harder.
