### ISSUE TITLE
It doesn't detect changes after http returned and modified the variable.

### ISSUE THREAD

**Issue by sumtec** [angular/angular#10915]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It's not updating the UI after http returned and updated the variable because it doesn't invoke detectChangeInternal at all.

**Expected/desired behavior**
<del>Detech the change and update the UI.</del> Or, throws an error on startup.

**Reproduction of the problem**
Not quite able to make an example yet because I am trying to upgrade a real (experimental) project from beta 9 to rc 5.
However, by debugging for days, and comparing my project with a modified Angular2 official example(http://plnkr.co/edit/dBM2rehBMH2GCXNr9pch?p=preview), I found that:
1. There is no difference with the js lib's version, including angular2, zonejs, systemjs, reflect-metadata, rxjs.
2. The zones are different when calling _moduleDoBootstrap(...) between the official example and mine.

![image](https://cloud.githubusercontent.com/assets/668022/17765123/3328d36c-6567-11e6-9f21-aa969be07628.png) The official (slightly modified) example.

![image](https://cloud.githubusercontent.com/assets/668022/17765179/969aa812-6567-11e6-94f2-463f894f28c7.png) My project. Please NOTE that the name of the zone is `"<root>".` And the stack trace are different as well. My example shows it was called from the Zone.wrap while the official one was from scheduleTask. And my example shows a lot "system-polyfills" there.

If the app is bootstrapped in a `"<root>"` zone, it will not call the "detectChangeInternal" which is attached on the "onLeave" of the "angular" zone. And that's the reason why my project doesn't get updated.

My guess is there might be something wrong in my initializing steps. I am still hunting it down but maybe you guys knows better than me.

Anyway, I think it should throw an error if the zone is not "angular" when it tries to bootstrap the app. It cost me days to check my source code in the component, the routing, the service. Changing from subscribe to promise, from Entity[] to `Observable<Entity[]>` | async. Comparing the version of the js libs. Nothing wrong. No luck at all. And finally I have to dig it through, put break points everywhere inside angular2 and zone.js.

P.S.

**What is the expected behavior?**
<del>Make it work as official example does.</del> Or, at least throws an error to warn the developer that the initialization has something wrong.

**What is the motivation / use case for changing the behavior?**
It cost me days and frustrate me a lot.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome 52 | Edge 14 ] 
 
* **Language:** [ES5]  Compiled by Typescript(1.8.36.0) in VS2015

--------------------------------------------------------------
Update:
My project will call the "ApplicationRef.tick()" before the "_moduleDoBootstrap" under the "angular" zone but the official example doesn't. What causes it is still unclear.

Can anyone can give me any advice or tips for debugging? Big thanks.

----------
**Update 2:**

Thank you all for your information provided.

For me, it's the "es6-shim".  This thing ruins the whole thing. This library was in the official example when it was in beta. And it was left somewhere in my project.

Anyway, it is quite worthwhile to throw an exception or shows a warning when the zone becomes `<root>` when trying to startup. It is quite possible for user to leave something unexpected at the corner and didn't notice. Or, having something in the wrong order. Plus, adding this check shouldn't be hard or adding much overhead.

**Comment by sod** [comment]
You call `_moduleDoBootstrap` on the platform? Why not `bootstrapModule`.

If you have to, you need to bootstrap inside a zone, so for example:

```typescript
var ngZone = new NgZone({});
ngZone.run(function() {
    platform._moduleDoBootstrap(/*...*/);
});
```

**Comment by dmckinney1229** [comment]
I am seeing this problem too.  When subscribing to an observable returned from http.get in ngOnInit of my component, template fields bound to the object returned are not refreshed until the form is interacted with manually.  This happens when using an async pipe or subscribing to an observable.

**Comment by chrisnicola** [comment]
In (https://github.com/WealthBar/a2d3) I have run into a similar problem, though not with an HTTP response, but any updates that go through my attribute directives. This problem started occurring after upgrading the project from RC.3 to RC.5. Change detection appears to only fire once on load and ignore any further changes.

Specifically, in the example component [here](https://github.com/WealthBar/a2d3/blob/master/src/app/app.ts) you can see it does a number of updates to properties when are then bound into the D3 chart directive's data property ([see here](https://github.com/WealthBar/a2d3/blob/master/src/app/app.html#L9)). Some are just done in a timer loop, another is done using a CSV data loading directive which fires and event. The event is fired after it loads the CSV and the property in the `App` component is set, I've verified all of that. However the [data property setter](https://github.com/WealthBar/a2d3/blob/master/src/angularD3/directives/chart.ts#L97) of `D3Chart` is never updated after the initial load when it is undefined.

Interestingly, I can kind of force it to work by triggering other change detection cycles, like putting in a superfluous text input, binding it and typing in it, then it starts to get some of the change unreliably.

[The branch where I've upgraded to RC.5 is here](https://github.com/WealthBar/a2d3/pull/1)

**Comment by dmckinney1229** [comment]
We were able to fix our issue.   The cause for us was loading shim.js after zone.js in index.html.  After swapping the order, our zone name went for "<root>" to "angular" and change detection works for http calls.

**Comment by chrisnicola** [comment]
@dmckinney1229 yes that was it, thank you. Though I wonder what precipitated this change recently. Also should es6-shim still really be necessary now?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
