### ISSUE TITLE
exception when using typescript getter/setter function together with [(ngModel)] and REACTIVE_FORM_DIRECTIVE

### ISSUE THREAD

**Issue by frickt** [angular/angular#10924]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```RangeError: Maximum call stack size exceeded``` 
when binding ngModel to getter/setter functions together with REACTIVE_FORM_DIRECTIVE.

The problem does not occur when binding to FormControl.value or to a local field.

**Expected/desired behavior**
correct binding, no exception

**Reproduction of the problem**
https://embed.plnkr.co/CjDdU7tAd87xsImBiiB8/

**What is the expected behavior?**
exception ->
```
RangeError: Maximum call stack size exceeded
    at SafeSubscriber.Subscriber.unsubscribe (VM4903 Subscriber.js:121)
    at SafeSubscriber.__tryOrUnsub (VM4903 Subscriber.js:228)
    at SafeSubscriber.next (VM4903 Subscriber.js:174)
    at Subscriber._next (VM4903 Subscriber.js:124)
    at Subscriber.next (VM4903 Subscriber.js:88)
    at EventEmitter.Subject._finalNext (VM4898 Subject.js:128)
    at EventEmitter.Subject._next (VM4898 Subject.js:120)
    at EventEmitter.Subject.next (VM4898 Subject.js:77)
    at EventEmitter.emit (VM4934 async.js:77)
    at FormControlDirective.viewToModelUpdate (VM4949 form_control_directive.js:68)
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.9 & 2.0]

**Comment by mvareeth** [comment]
I am also facing similar kind of issue. I am not able to use ReactiveFormsModule and FormsModule together in my feature module. One of the components is implemented by FormsModule and the second one has validations and we used (formGroup with validations) ReactiveFormsModule instead of FormsModule. RC5 upgrade is throwing error as ''FormControlDirective is part of the declarations of 2 modules: ReactiveFormsModule and FormsModule'

**Comment by obiwan007** [comment]
You are calling the updateValue method on your formcontrol. That ill probalbly lead to the recursion...
Comment out the validator.updateValue() inside your setter method.
updateValue is called internally by the Framework and should only be called if you need to update the form value manually. The setter is not the right place here I would guess...

**Comment by frickt** [comment]
correct. Thank you!
