### ISSUE TITLE
Ng Life cycle methods are not working in production mode when i use router.navigate

### ISSUE THREAD

**Issue by manjuojal** [angular/angular#10922]
**I'm submitting a
[x] bug report => search github for a similar issue or PR before submitting   

**Current behavior**
Ng Life cycle methods are not working in production mode when i use router.navigate

**Expected/desired behavior**
Ng Life cycle methods should work in production mode when i use router.navigate

**Reproduction of the problem**
1. i have hero list page and i am navigating to add hero page
2. here i will add hero and after adding i would navigate back to hero list page using below code
this.router.navigate(['HeroList']); // HeroList is alias for herolist page
3. at this step i am getting blank page.
4. If i refresh then data is getting.

**What is the expected behavior?**
When we navigate to previous page it should load execute life cycle methods

**What is the motivation / use case for changing the behavior?**
Its common feature should work.

**Please tell us about your environment:**

* **Angular version:** 2.14.20
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX] 
 
* **Language:** [TypeScript X.X ]

**Comment by pkozlowski-opensource** [comment]
How is this one different from #10921. It might look like your are trying to follow the issue template but you are still omitting the essential part - reproduce scenario in a plunker! 

Please add a minimal, runnable reproduce scenario in #10921
