### ISSUE TITLE
SafeNavigation Operator in Event Binding - Exception: this.visit(...).isBlank is not a function

### ISSUE THREAD

**Issue by alexheim** [angular/angular#10923]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you use the safe navigation operator in an event binding expression, the compiler fails with the message "this.visit(...).isBlank is not a function"

**Expected/desired behavior**
Safe navigation operator in event expressions should be ok. Works fine in RC 4.

**Reproduction of the problem**
Use this example component:
`export class AppComponent {
  notNullValue: any = { onClick: () => console.log('clicked') };
}`

Together with a template as follows:
`<button (click)="notNullValue?.onClick()">Click</button>`

This code does not even compile. Instead, there is a stack trace in the Javascript console:

> zone.js:461 Unhandled Promise rejection: this.visit(...).isBlank is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: this.visit(...).isBlank is not a function
    at _AstToIrVisitor.convertSafeAccess (http://localhost:4200/main.bundle.js:36122:65)
    at _AstToIrVisitor.visitSafeMethodCall (http://localhost:4200/main.bundle.js:36074:21)
    at SafeMethodCall.visit (http://localhost:4200/main.bundle.js:22900:24)
    at ASTWithSource.visit (http://localhost:4200/main.bundle.js:22930:25)
    at Object.convertCdStatementToIr (http://localhost:4200/main.bundle.js:35877:28)
    at CompileEventListener.addAction (http://localhost:4200/main.bundle.js:51405:50)

**What is the expected behavior?**
Should compile. Clicking on the button should display 'clicked' in the console.

**What is the motivation / use case for changing the behavior?**
n/a

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 2.0]

**Comment by sod** [comment]
Plunkr: http://plnkr.co/edit/1JTVogCayOuxf5fDDSDx?p=preview

**Comment by meriturva** [comment]
Any solution here? will it be fixed on RC6? or do we have to avoid that approach?

**Comment by alexheim** [comment]
RC6 came out and still has the same bug. The message is slightly different now, but that doesn't make things any better:

> zone.js:461Unhandled Promise rejection: guardedExpression.isBlank is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: guardedExpression.isBlank is not a function

Isn't that a rather obvious bug that should simply be fixed in one of the next milestones? What's the plan here?

**Comment by vicb** [comment]
@chuckjaz could you please take a look ?

**Comment by segersrobbert** [comment]
still an issue in 2.0 final

**Comment by vicb** [comment]
fixed
see this 2.0.2 plunker: http://plnkr.co/edit/z5wXpjPRfUThTWorn1Vo
