### ISSUE TITLE
How to use both FormsModule and ReactiveFormsModule in a feature module

### ISSUE THREAD

**Issue by mvareeth** [angular/angular#10925]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I have one feature module with two components. One is in template-driven form style and another one is reactive form style. I am using FormsModule for template-driven and ReactiveFormsModule for reactive form style validations. Whenever I use both in my feature module I am getting an error as 'FormControlDirective is part of the declarations of 2 modules: ReactiveFormsModule and FormsModule'. How to solve this issue? As an alternative, I used REACTIVE_FORM_DIRECTIVES as part of component directive but that also throwing the similar error.

**Current behavior**
throwing error 
'FormControlDirective is part of the declarations of 2 modules: ReactiveFormsModule and FormsModule'

**Expected/desired behavior**
template-driven form style and reactive form style should work in the feature module

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**
template-driven form style and reactive form style should work in the feature module

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 2.0]

**Comment by kylecordes** [comment]
I was curious about the same question when some advice went by a few days ago elsewhere suggesting that it is fine to use both reactive and template forms together in the same program or even the same component, as long as not the same form. This issue as reported suggests that it may be necessary rather to have different modules to use the two different styles of form.

**Comment by thelgevold** [comment]
It's hard to speak to your specific problem without some source code to look at, but I don't see an issue running reactive and template forms together in the same app.

I have put together a plunker demoing the two form variations together in the same application

http://plnkr.co/edit/jsxVCGhIi7J0djSuoS4N?p=preview

**Comment by mvareeth** [comment]
This was an issue in our code. One of our control has CORE_DIRECTIVES,  FORM_DIRECTIVES ,REACTIVE_FORM_DIRECTIVES direcves as part of the custom web component. I missed to remove from this file while upgrading to RC5.
I have created plunker here.
http://plnkr.co/edit/5qzLh1JCh1EO5Ittu4Z6?p=preview

**Comment by kylecordes** [comment]
I also verified experimentally today that there is no conflict with using template and reactive forms on the same component (of course in the same module).
