### ISSUE TITLE
Ng Life cycle methods are not working in production mode when i use router.navigate

### ISSUE THREAD

**Issue by manjuojal** [angular/angular#10921]
Angular2 life cycle methods like ngOnInit,ngOnDestroy .

Steps to reproduce,
1. i have hero list page and i am navigating to add hero page
2. here i will add hero and after adding i would navigate back to hero list page using below code
   this.router.navigate(['HeroList']);  // HeroList is alias for herolist page
3. at this step i am getting blank page.
4. If i refresh then data is getting.

NPM Version
2.14.20
App Type:Typescript

**Comment by zoechi** [comment]
If you think this is a bug please fill the issue template

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
