### ISSUE TITLE
Can't set indeterminate state to HTMLInputElement from type checkbox.

### ISSUE THREAD

**Issue by Neill83** [angular/angular#10937]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Can't set indeterminate state to HTMLInputElement from type checkbox.

**Expected/desired behavior**
Want to set indeterminate state to checkbox via @ViewChild annotation.

**Reproduction of the problem**
`@ViewChild('checkbox') checkbox:HTMLInputElement;`

then somewhere in a .ts method

`this.checkbox.indeterminate = true;`

but nothing happens.

**What is the expected behavior?**
I want to get this.

![bildschirmfoto 2016-08-19 um 09 16 27](https://cloud.githubusercontent.com/assets/9987324/17801977/a46230ce-65ed-11e6-9764-478b1a36549d.png)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
OS X El Capitán

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Chrome 51.0
 
* **Language:** TypeScript X.X ES5

**Comment by sod** [comment]
`ViewChild` returns an instance of `ElementRef`, so you have to do `this.checkbox.nativeElement.inderterminate = true`

But better approach would be to:
* either set it in the template:
`<input [inderterminate]="value">`

* or in typescript use the Renderer from @angular/core: `this.renderer.setElementProperty(this.checkbox.nativeElement, 'indeterminate', true);`

to keep your code compatible with running in a webworker or prerendering via https://github.com/angular/universal.

See: http://plnkr.co/edit/qsm95evJZ3NcW0PaFlta?p=preview

**Comment by Neill83** [comment]
thanks a lot @sod !
I didn't know the `[indeterminate]` property-binding.
