### ISSUE TITLE
Component inheritance

### ISSUE THREAD

**Issue by nomack84** [angular/angular#1093]
Hi, 
It's going to be any way to do component inheritance? Polymer 0.5 currently support this, for custom and native components. This could be a nice feature IMO. 
Cheers.

**Comment by cssensei** [comment]
:+1:

**Comment by mhevery** [comment]
ES6 supports inheritance, and you can have your own inheritance hierarchies. 

Angular favor composition over inheritance. http://en.wikipedia.org/wiki/Composition_over_inheritance and does not have any base class for you to extend from.
