### ISSUE TITLE
Template render errors with Code Blocks

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular#10938]
**I'm submitting a ...**  (check one with "x")

     [ x ] bug report => search github for a similar issue or PR before submitting

**Current behaviour**
Escaping code snippets with `<pre><code>...</code></pre>` doesn't stop containing code from causing template rendering errors. 

So I want to be able to display code blocks in a template and as an example, I get this error:

```
Unexpected closing tag "code" 
(":FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
 [ERROR ->] </code></pre>
```

**Expected/desired behavior**

Rather than the error above, I would like to display that error message like this:

    <pre><code>/app/path/to/file.js:14:8: JS ERROR ReferenceError: Can't find variable: foo
    1   0xe3dc0 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
    </code></pre>

**Reproduction of the problem**
See this [Plunk](http://plnkr.co/edit/yGkJPCplMQHKkbuJJfUY?p=preview) uncomment the snippet in the **src/app.ts** file's template to break the application - error message in the console.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by pkozlowski-opensource** [comment]
You can't stick `<` or `>` into `<code>` just like this - you still need to escape HTML and use `&lt;` and `&gt;` entities.

Closing as it has nothing to do with Angular.
