### ISSUE TITLE
Router : Resolve guard throw an exception when observable emits an error rc5

### ISSUE THREAD

**Issue by gugamm** [angular/angular#10930]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Resolve guard throw an exception when observable emits an error

I wonder if this is the desired behavior... But i think it is annoying

**Expected/desired behavior**
It should block navigation, but shouldn't throw an exception

**Reproduction of the problem**
Open console
Click in "admin"
You will see that navigation didn't complete(as expected) but throw an exception

Plunker(for some reason this plunker doesn't work in IE) :
http://plnkr.co/edit/IgXUx3fBVqonWAegIdhw?p=preview

EXCEPTION: Error: Uncaught (in promise): PROBLEM HEREBrowserDomAdapter.logError @ platform-browser.umd.js:937
platform-browser.umd.js:937 STACKTRACE:BrowserDomAdapter.logError @ platform-browser.umd.js:937
platform-browser.umd.js:937 Error: Uncaught (in promise): PROBLEM HERE
    at resolvePromise (zone.js:538)
    at zone.js:515
    at ZoneDelegate.invoke (zone.js:323)
    at Object.onInvoke (core.umd.js:9245)
    at ZoneDelegate.invoke (zone.js:322)
    at Zone.run (zone.js:216)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.onInvokeTask (core.umd.js:9236)
    at ZoneDelegate.invokeTask (zone.js:355)BrowserDomAdapter.logError @ platform-browser.umd.js:937
zone.js:461 Unhandled Promise rejection: PROBLEM HERE ; Zone: angular ; Task: Promise.then ; Value: PROBLEM HEREconsoleError @ zone.js:461
zone.js:463 Error: Uncaught (in promise): PROBLEM HERE(…)consoleError @ zone.js:463
http://run.plnkr.co/9tydCUSb9GI7OyYR/style.css Failed to load resource: the server responded with a status of 404 (Not Found)

**What is the expected behavior?**
Shouldn throw an exception

**Please tell us about your environment:**
Windows
Chrome

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome ] 
 
* **Language:** [TypeScript]

**Comment by ericmartinezr** [comment]
Related https://github.com/angular/angular/issues/10585

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/11063
