### ISSUE TITLE
feat(router) Router must be case insensitive (Router 3.0.0-rc.1)

### ISSUE THREAD

**Issue by tolemac** [angular/angular#10935]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
The router is case sensitive.
If you define a route path as "Route" and you navitage to "/route" you get an error like `Error: Cannot match any routes: 'route'`

**Expected/desired behavior**
The router must be case insensitive by default and should resolve "/route" with "Route" path.

**Reproduction of the problem**
I have used the example plunkr of "Routing & Navigation" docs, I have changed `login.routing.ts` defining login route with path "Login", and the login link doesn't work:
http://plnkr.co/edit/hIBAsfLvgm75uzcMKY4D?p=preview

**What is the motivation / use case for changing the behavior?**
You defining routes for your application and normally you can write the url in lower or upper case. The applications must work with both.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 - Router: 3.0.0-rc1
 * **Browser:** [all] 
 * **Language:** [TypeScript]

**Comment by damiandennis** [comment]
why? that promotes bad coding, I think it should be case sensitive.

**Comment by tolemac** [comment]
Bad coding? where? :D
Can you ensure that your users are going to write correctly the applications urls?

It isn't code related. Every day, the users write urls and you can't ensure they write correctly, the users can write:

    myapp.com/CrisisCenter
    myapp.com/Crisiscenter
    myapp.com/crisiscenter
    MYAPP.COM/CRISISCENTER

These 4 urls are the same for too many people...

**Comment by stephanjust** [comment]
Well then these users will have a problem, because URIs are case sensitive (or at least the route that matters).

http://stackoverflow.com/a/26196170

And in reality: are your users really typing URIs instead of using links on the main website and storing them as bookmarks?

**Comment by tolemac** [comment]
Do you want to tell about W3C definitions to the users? They do not care about URI definitions.
And yes, they write urls when they remember its.

Is that feature too strange? Almost all routers are case insensitive or give you the possibility of define case insensitive routes ...

**Comment by astec** [comment]
@tolemac all the web works with case sensitive URLs and I've never heard anyone complaining regards this.

Check https://www.google.com/maps vs https://www.google.com/Maps for example.

I guess you can define wildcard pattern and handle manually if you really want it.

I really don't want to have my URLs to be case-insensitive as this for example would screw up my logging & statistics.

**Comment by martinmcwhorter** [comment]
This is easily solved by using lower-case URIs and normalizing any URIs to lowercase. I imagine this would be trivial and should not be part of the router.

**Comment by vsavkin** [comment]
You can provide your own `UrlSerializer` that is case insensitive. The easiest way to do that is to wrap DefaultUrlSerializer and lowercase both the input and output.

The default serializer should be case sensitive.

Closing this issue.

**Comment by kylecordes** [comment]
@vsavkin Case insensitivity is a very helpful feature available optionally with the Angular 1 router. For the sake of making things a bit easier for people who migrate, please consider offering that option here also, so the people who want insensitivity find it is only a switch away rather than re-implementing the ```UrlSerializer```?

**Comment by SystemDisc** [comment]
I've implemented case insensitive routes with a `matcher` function.  
https://stackoverflow.com/a/46951813/2537258

**Comment by jcpc91** [comment]
why why why?? after so many years and today angular7 this request feature have not been implemented and then bad comments like 

> And in reality: are your users really typing URIs instead of using links on the main website and storing them as bookmarks?

or 

> why? that promotes bad coding, I think it should be case sensitive.

really??
