### ISSUE TITLE
Angular templates use Dart syntax for non-null assertion operator

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#10932]
TypeScript lets you de-reference a possibly-null value safely with `!`
`video.getSnippet()!.getDescription()`

But in an Angular html template, the syntax required is a `?`
`<p>{{video.getSnippet()?.getDescription()}}</p>`

this is sad since we expect our users to know TypeScript syntax, not Dart.

cc @rkirov

**Comment by ericmartinezr** [comment]
Fwiw https://github.com/angular/angular/issues/10855#issuecomment-240449481

**Comment by alexeagle** [comment]
Thanks, I see, it's subtle. The `!` still gets a null reference error at runtime, the `?` short-circuits the evaluation.
