### ISSUE TITLE
Add support to trim the list of NgModule imports to the necessary minimum without runtime trial-and-error

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#10945]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm currently in the process of converting my app to `rc.5`. After thinking about how to do that without a big bang commit¹, I landed on first creating `NgModule`s for "leaf" components that don't reference my own components in their `directive:` declarations. I then put these in the entry `NgModule`, so all the components that are still automatically hoisted into the root module still work.
After the first level, I'm now in the position where I'm starting with the next level of conversions and I can see that some of the modules that are imported by the entry `NgModule` are now only needed by other modules and not the actual top-level module.

There is no way to figure out, which imported modules are actually needed for the members of a module. Not only for the entry module, but really any `NgModule`.

**Expected/desired behavior**
There should be a faster way than a "remove a module -> webpack -> browser refresh -> watch error window -> put back module" cycle to check which are actually needed.
- **Angular version:** 2.0.0-rc.5
#10552

¹ The documentation is of no help here at the moment, instead it just says "Your stuff won't work soon! We won't tell you when! We won't tell you how to convert. Go figure out what to do, and better be fast"

**Comment by chuckjaz** [comment]
We have no plans to implement this as part of the compiler as it is a style error not a semantic error (akin to dead code). Consider requesting this as a `tslint` feature.

/cc: @mgechev

**Comment by mgechev** [comment]
Sounds like a good rule candidate. I added an issue as a placeholder here https://github.com/mgechev/codelyzer/issues/256.
