### ISSUE TITLE
Can't I assignte to "imports" of type 'ComponentMetadataType'

### ISSUE THREAD

**Issue by chen86860** [angular/angular#10941]
Here is my `todos.component.ts`
```
import {Component, OnInit} from '@angular/core';
import  {TodoService} from '../todo.service'
import {FormsModule} from '@angular/forms';

@Component({
  moduleId: module.id,
  selector: 'app-todos',
  templateUrl: 'todos.component.html',
  styleUrls: ['todos.component.css'],
  imports: [FormsModule]
})
```
and then,when i run server,it said:
`'Argument of type '{ moduleId: string; selector: string; templateUrl: string; styleUrls: string[]; imports: typeof F...' is not assignable to parameter of type 'ComponentMetadataType'.
  Object literal may only specify known properties, and 'imports' does not exist in type 'ComponentMetadataType'.`
what can i do?

**Comment by pkozlowski-opensource** [comment]
There is no `imports` on the `@Component` level, only on the `@NgModule`.

> what can i do?

Ask support questions using an appropriate channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by chen86860** [comment]
Oops,got it,I will do this the next time,thank a lot. :D
