### ISSUE TITLE
metadata collector provides metadata for non-exported enums

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#10955]
https://github.com/angular/angular/blob/8a5eb086726640ca150cf3477b1232fc3f8cace8/modules/%40angular/compiler/src/i18n/extractor_merger.ts#L44
appears in
https://github.com/angular/compiler-builds/blob/master/src/i18n/extractor_merger.metadata.json

https://github.com/angular/angular/blob/8a5eb086726640ca150cf3477b1232fc3f8cace8/modules/@angular/compiler/src/url_resolver.ts#L237
appears in
https://github.com/angular/compiler-builds/blob/master/src/url_resolver.metadata.json

https://github.com/angular/angular/blob/8a5eb086726640ca150cf3477b1232fc3f8cace8/modules/@angular/compiler/src/view_compiler/expression_converter.ts#L63
appears in 
https://github.com/angular/compiler-builds/blob/master/src/view_compiler/expression_converter.metadata.json

Causes the error mentioned in http://b/30945581

**Comment by jelbourn** [comment]
Example where this happens with Material: https://github.com/angular/material2/blob/master/src/lib/checkbox/checkbox.ts#L33
