### ISSUE TITLE
Making CORS POST request using Angular

### ISSUE THREAD

**Issue by Sandybhai** [angular/angular#10952]
Have been scratching my head with regards to sending POST request using angular. I have a service running at localhost:8008 and I wish to send a POST request to a server service running at localhost:3002/signup with username and passwd as the params. How do I do this ? 
My server is written in golang. Also I tried packet capturing using wireshark and it didn't seem to recognise my post requests properly as http type packets and only as tcp packets. So I thought I did something wrong.

My current method:
$http({
        url: 'http://localhost:3002/signup',
        method: "POST",
        data: JSON.stringify({username:$scope.username,passwd:$scope.passwd})
    });

**Comment by sirajc** [comment]
This looks like AngularJS issue, This repo is for Angular 2

**Comment by pkozlowski-opensource** [comment]
> This looks like AngularJS issue

Nope, this sounds like a CORS issue that is browser specific and has nothing to do with any of JS frameworks: http://www.html5rocks.com/en/tutorials/cors/
