### ISSUE TITLE
A syntax for static/at-construction-time bindings

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1095]
Assume I have a directive called "Hello":

```dart
@Directive(
  selector: 'hello',
  bind: const {
    'name': 'name'
  }
)
class HelloDirective {
  String name;
}
```

It would be used something like this:

```html
<hello name="Misko"></hello>
```

The issue here is I have to add a getter/setter for something that will never change, and if I want to wait until `name` is set, I have to use a setter. What if the following was possible:

```dart
class HelloDirective {
  final String name;

  HelloDirective(@Bind('name') this.name);
}
```

At creation time, the `name` attribute would be read and passed. If it wasn't available, it could either default to null (flexible) or throw (stricter). This would make some directives lighter weight, have less code, and could possibly even be understood by the change detector in future iterations.

**Comment by pkozlowski-opensource** [comment]
It sounds a lot like https://github.com/angular/angular/issues/622 (and some other issues) for which we've got a PR already: https://github.com/angular/angular/pull/1091. Would the proposed solution work for you?

**Comment by matanlurey** [comment]
Nice catch. Thanks.
