### ISSUE TITLE
Privately-referenced classes are still being emitted in metadata

### ISSUE THREAD

**Issue by matsko** [angular/angular#10954]
Inside of angular/material2 we have a class, TransitionCheckState, that is being exported despite it being a class that is not exported nor being referenced in a public way. This may pose issues when running ngc with material2.

**Comment by matsko** [comment]
cc @jelbourn

**Comment by chuckjaz** [comment]
`TransitionCheckState` is an `enum` not a class. Closing in favor of #10955.
