### ISSUE TITLE
Angular 2 Offline Compiler Documentation

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#10959]
Since with RC 5 the Angular 2 is near to its final launch, I think its the right time to add documentation of the Offline Compiler with the best practices.

Though there seems to be the support available with CLI and there are also few blog posts about offline compilation but a post explaining the offline compilation process from Angular Team with best practices and ways to manual offline compilation would be really helpful.

**Comment by pkozlowski-opensource** [comment]
Docs are work in progress in https://github.com/angular/angular.io
