### ISSUE TITLE
[router] ActivatedRoute params acts weird with browser back/forward buttons

### ISSUE THREAD

**Issue by DavideViolante** [angular/angular#10950]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```
I really don't know how to explain this in words so I created 2 gifs to show you the problem (be careful when I press the browser buttons):
http://imgur.com/a/FWTru
(I failed creating a working plunker for this bug in particular)

The first GIF (correct behaviour) uses this **code** for the buttons:
```
private page = 0;
nextPage() {
	this.page++;
	this.router.navigate(['about/anyparamhere',{page:this.page}]);
}
// same code for prevPage() but with this.page--
```
As you can see there are buttons that changes the "page" param and you can correctly navigate back and forward via my buttons or via browser buttons.
In the second GIF you can't navigate correctly using **browser** buttons.
The second GIF (weird behaviour) uses this **code** for the buttons:
```
private page = 0;
nextPage() {
	this.page++;
	this.route.params.subscribe(params => {
		this.router.navigate(['about/anyparamhere',{page:this.page}]);
	});
}
// same code for prevPage() but with this.page--
```

where this.route is ActivatedRoute and this.router is Router.

I didn't use **params** just for this example but assume you need to use it because you have real params in the url.

* **Angular version:** 2.0.0-rc.5 + router 3.0.0-rc.1
* **Browser:** [Chrome 52] 
* **Language:** [TypeScript]

**Comment by felipedrumond** [comment]
It seems that when you call nextPage() (second implementation) you are re-creating a subscribe instead of redirecting the user, instead of navigating to the next url.

The implementation you can use is this:

`private routeListener: any;`

`ngOnInit() {

 this.routeListener = this.activatedRoute.params.subscribe(params => {
                this.routeListenerAction(params); <--- create the route params listener: everytime you activatedRoute change its params, the function routeListenerAction will be called sending the current params
            }
        })
    }`

`routeListenerAction(params) { // TODO }`

**Comment by vsavkin** [comment]
@DavideViolante you create a new subscription every time you call `nextPage`. As a result, navigate is called multiple times on every `nextPage`. What you want is the following:

```javascript
    this.page++;
    const p = this.route.snapshot.params;
    this.router.navigate(['about/anyparamhere',{page:this.page, someParam: p.someParam}]);
```

**Comment by DavideViolante** [comment]
Thank you, it works. Closing.
