### ISSUE TITLE
Location subscribe event does not fire on routing

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular#10963]
**I'm submitting a ...**  (check one with "x")

```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I subscribe to URL change events via location.subscribe. The event never fires when I navigate via router-link clicks.

**Expected/desired behavior**
The event should fire.

**Reproduction of the problem**
Below code is from the root component that contains the router-outlet.

```
import {Location} from '@angular/common';
constructor(private location: Location) {
 location.subscribe((value) => {
            console.log("Location changed");
        });
}
```

**What is the expected behavior?**
I should see "Location changed" in the console log when routing.

**What is the motivation / use case for changing the behavior?**
It is used in Angulartics: https://github.com/angulartics/angulartics2/issues/46

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.X
  2.0.0-rc.4
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
  Chrome
- **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
  TypeScript 1.8

**Comment by pkozlowski-opensource** [comment]
Could you please try to reproduce this in plunker with RC5, latest router and without any 3rd party libraries. My experience with `angulartics2` so far was rather ... well, not great... and had to do work-arounds in one of my projects for the exact scenario you are rising: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/demo/src/app/shared/angulartics2.workaround.ts 

In any case, please provide a minimal reproduce scenario in rc5 so we are sure that we are dealing with the Angular issue here.

**Comment by michalstepien** [comment]
@pkozlowski-opensource I create plnkr. http://plnkr.co/edit/WVX3gQPCZRgn52quxQay?p=preview
If click Heroes or details it doesn't work. If click back button in details it works (window.history.back();).

**Comment by rolandoldengarm** [comment]
Thanks @michalstepien , so it looks like a bug with Angular.

@pkozlowski-opensource I'm not happy with the fact that Angulartics2 does not seem to get a lot of support, but it seems to be the only 3rd party tool to use GA with Angular2.

**Comment by michalstepien** [comment]
Perhaps is related with this: https://github.com/angular/angular/issues/10909

**Comment by rolandoldengarm** [comment]
Can the label please be updated as there is a repro?

**Comment by rolandoldengarm** [comment]
Please find a smaller repro here: http://plnkr.co/edit/WBYjSLdsahoUMzmFODgj?p=preview

Based on the router-deprecated issue listed here: https://github.com/angular/angular/issues/8630

Could you please update the labels?

**Comment by JonnyBGod** [comment]
It looks like this problem persist in RC6.

It seems to work in test environment, following test works:

```
describe('router support', function() {
      var EventSpy: any;

      beforeEach(() => {
        TestBed.configureTestingModule({
          imports: [
            RouterTestingModule.withRoutes(RoutesConfig),
            TestModule
          ],
          providers: [
            { provide: Location, useClass: SpyLocation }
          ]
        });

        EventSpy = jasmine.createSpy('EventSpy');
      });

      it('should track pages on route v3 change',
        fakeAsync(inject([Router, Location],
          (router: Router, location: Location) => {
            fixture = createRootWithRouter(router, RootCmp);
            location.subscribe((x: any) => EventSpy(x.url));
            router.navigateByUrl('/abc');
            advance(fixture);
            router.navigate(['def']);
            advance(fixture);
            expect(EventSpy).toHaveBeenCalledWith('/abc');
            expect(EventSpy).toHaveBeenCalledWith('/def');
          })));
    });
```

**Comment by DzmitryShylovich** [comment]
can u provide a repro with the latest angular?

**Comment by DmitryEfimenko** [comment]
This is still an issue in latest Angular: http://plnkr.co/edit/oDpsUKlgWTe84bu2cJUY?p=preview

**Comment by alnvny** [comment]
does this issue fixed? I am still facing this.

**Comment by kaito3desuyo** [comment]
I have same issue

**Comment by samuelpetroline** [comment]
In the docs it says:

`Subscribes to the platform's popState events.`

I guess it's not a bug, but a misunderstanding. It should be more clear to what event it's subscribing
