### ISSUE TITLE
AOT compiler:  writes private field that's referenced in another class

### ISSUE THREAD

**Issue by vikerman** [angular/angular#10967]
**I'm submitting a ...**  (check one with "x")

```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When there is a ViewQuery from one component to another, the AOT compiler produces code that has private field in the child component that's referenced in the generated code for the view query. This causes Typescript compilation error when the generated code is compiled.

@ViewChildren(ChildComponent) cards: QueryList<ChildComponent>;

produces something like

this._viewQuery_ChildComponent_0.reset([this._appEl_1.mapNestedViews(_View_ParentComponent, (nestedView) => {
                        return [nestedView._appEl_2.mapNestedViews(_View_SearchVideos2, (nestedView) => {

Here nestedView._appEl_2 is private and causes a compilation error

**Expected/desired behavior**
No compilation errors.
- **Angular version:** 2.0.0-rc.6
- **Language:** TypeScript

**Comment by alexeagle** [comment]
Note, we worked around this in the short-term by commenting out the `private` on the declaration.
When @tbosch is back we can find a better fix.

**Comment by DzmitryShylovich** [comment]
@alexeagle is this still relevant? codegen has changed significantly.

**Comment by vikerman** [comment]
No longer relevant
