### ISSUE TITLE
Compiler: Cannot read property 'transform' of undefined

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#10964]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm trying to integrate [polymer component](https://github.com/Saulis/iron-data-table) into angular app. It provides a cool templating feature for table cells via [structural directives](https://github.com/Saulis/angular2-iron-data-table/blob/master/index.ts#L62-L102). Interpolation works fine, but when I try to use custom pipes I get `Cannot read property 'transform' of undefined` error. At the beginning I think it's just something wrong with directive implementation. It would be ok if all pipes doesn't work **but** common pipes work fine so I think there's bug in angular as well.

**Reproduction of the problem**
Here's a sample project https://github.com/DzmitryShylovich/expense-manager-ng2-demo#install-dependencies
[json](https://github.com/DzmitryShylovich/expense-manager-ng2-demo/blob/master/app/expense_app.component.ts#L10) pipe works fine but my [custom](https://github.com/DzmitryShylovich/expense-manager-ng2-demo/blob/master/app/expense_app.component.ts#L14) one throws the exception.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5. Haven't tested it with rc4.
 
* **Browser:** [Chrome ] 
 
* **Language:** [TypeScript]

**Comment by DzmitryShylovich** [comment]
Found the issue myself.

**Comment by zoechi** [comment]
How did you solve it?

**Comment by DzmitryShylovich** [comment]
Looks like ViewContainerRef is not fully initialized in the constructor [example](http://plnkr.co/edit/f7Uub9qJeEvPF9kCuaFc?p=preview). For some reason only common pipes work in the constructor (mb it's a bug).
So I've just moved `this.viewContainer.createEmbeddedView` call inside `ngOnInit`  [example](http://plnkr.co/edit/kEBPUnTKmQRoKRaMq3rC?p=preview)

**Comment by zoechi** [comment]
I see. Thanks for the follow up. `createComponent` can't be used in the `constructor` and it's no surprise `createEmbeddedView` can not as well.

**Comment by DzmitryShylovich** [comment]
Would be nice to see docs about all these ViewContainerRef, EmbededViewRef, ViewRef, TemplateRef etc stuff :)
