### ISSUE TITLE
Possibly incorrect example in docs for webpack component relative paths

### ISSUE THREAD

**Issue by cyberwombat** [angular/angular#10968]
In the docs https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html#!#webpack it mentions using `require` for styles/components:

````
They can load templates and styles at runtime by setting the component metadata template and style properties with require statements that reference component-relative URLS.
````

However the example given makes no use of require statements:
```
import { Component } from '@angular/core';

import '../../public/css/styles.css';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent { }
````
It looks like the example is wrong yes?

**Comment by ericmartinezr** [comment]
Hey @cyberwombat , would you mind opening this issue in the website/tutorial repo? https://github.com/angular/angular.io

**Comment by cyberwombat** [comment]
For su'
