### ISSUE TITLE
Changes are not detected on setInterval

### ISSUE THREAD

**Issue by MoxxNull** [angular/angular#10966]
[ X ] bug report => search github for a similar issue or PR before submitting

For testing reasons I have a constructor with:

```
setInterval(() => {
        this.test = new Date().getMilliseconds().toString();           
    }, 500);
```
And a template with just "<p>{{test}}</p>" .

**Current behavior**

Upon loading or reloading the page it either displays a value (but does not change on further ticks), somtimes it works as intended (updates value on every tick), and sometimes just displays the initial value and does not change at all. Seems random.

**Expected/desired behavior**

It should display and update the value upon change.

**Reproduction of the problem**
In the official Plunker-Version the problem does not occur (It seems not to ..)
So at first I thought of this issue: [10915](https://github.com/angular/angular/issues/10915),
but even removing `import "es6-shim";` from my polyfills.ts  (as i am using webpack) does not seem to help...

Anyone any idea?

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [ TypeScript 1.8 ]

**Comment by ericmartinezr** [comment]
> In the official Plunker-Version the problem does not occur (It seems not to ..)

See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by MoxxNull** [comment]
Sry, you are right... it should be more of a configuration error, so closing this.

**Comment by ericmartinezr** [comment]
@MoxxNull nothing to be sorry about. You will get help much easier and faster in SO, Gitter, etc. Don't get it wrong, it's simply that the repo is not for support questions.

Don't forget to include all your config files so people can see what's wrong.

You can ask here, a lot of people are there hungry for answering everything xP https://gitter.im/angular/angular

**Comment by MoxxNull** [comment]
Even though I cannot reproduce that in the given plunker version: My problems were caused by some Font-Awesome script. 

`<script src="https://use.fontawesome.com/f0298bc7e9.js"></script>`

Without that line, everything works. With it: The given strange behaviour. Maybe I can save someone's time with that :)

**Comment by ericmartinezr** [comment]
@MoxxNull I don't know about that lib, but if it is causing issues with change detection it may be patching promises overriding angular's patching. Can you try changing the order of the libs? Put fontawesome lib above zone.js in your polyfills. Play with the order and see which one works for you.

**Comment by MoxxNull** [comment]
It's the CDN from http://fontawesome.io/  (Icon Library).  I
It doesn't matter if I load it before everything else or after my scripts - it always messes up data binding..
