### ISSUE TITLE
Link to live example in 5 min quickstart missing in IE11

### ISSUE THREAD

**Issue by flyer1** [angular/angular#10979]
The link to the **live example** on the 5 minute quickstart [https://angular.io/docs/ts/latest/quickstart.html](https://angular.io/docs/ts/latest/quickstart.html) doesn't appear in IE11.
You see: 

```
Try it!

Try the  which loads the sample app and displays the simple message:

```

Error in console is:
> TypeError: Object doesn't support property or method 'includes'
>    at isDoc (https://angular.io/resources/js/util.js:9:9)
>    at compile (https://angular.io/resources/js/directives/live-example.js:38:7)
>    ...

We had **Angular 2 for TypeScript** selected at the top.

It seems minor, but it made us think at first that perhaps IE11 is still not supported.

**Comment by ericmartinezr** [comment]
@flyer1 would you mind reopening this issue in the website/tutorial repo? https://github.com/angular/angular.io

**Comment by flyer1** [comment]
For sure. I didn't realize there is a repo for the docs. Closing issue here.
