### ISSUE TITLE
twice import service file in ngmodule file and in  component file

### ISSUE THREAD

**Issue by webmobiles** [angular/angular#10973]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

For use a service it's needed import the .ts file in NgModule and in the .ts file Component
**Expected/desired behavior**
Injecting a service in the Component must be enough to realize that the service must took from the NgModule

**Comment by jmcgoldrick** [comment]
The issue here is that sometimes that wouldn't be what you want... for certain services you might want a *new* instance in the component not the one provided in `NgModule` - how would you differentiate? Probably with the current paradigm.

**Comment by webmobiles** [comment]
simply i have heard that providers in components will be deprecated ... I don't know about how to create a new instance, but i've realized that it's possible move component children to NgModule include the line import. 
Example I can move this two lines from heroes.component.ts  to NgModule:
import { HeroDetailComponent } from './hero-detail.component';
@Component({...
	directives: [HeroDetailComponent],

but for the service, i need keep import the service in the Component: heroes.component.ts:
import { HeroService } from './hero.service';

if i want to have just an instance on the global NgModule, why i can move import for a subcomponent but not for a service. maybe I m wrong in concepts?

**Comment by jmcgoldrick** [comment]
Ah, there is an important distinction between *providing* an instance of a service to a component (via `providers: [...]`) and importing the service to use in the component.

The former (which isn't being deprecated, AFAIK) can provide a new/configured-differently instance of the service to the component and it's children. When you are simply importing (eg. to use in the class) your just letting angular know what service you want, regardless of anything angular DI does, you need this import so you can get type information/intellisense in your class methods etc.

If you think of how you declare a component/directive in a module and how you would likely still import it to use with `@ViewChild` etc. it should make more sense.

To speak to the issue/feature request directly, by not providing the service in the module (which you can do now without issue) you would simply be getting an instance created at the component-level and for some services that don't require app/global scope this would be fine for ones that do though there is no way for the compiler to know your intentions - especially ahead of time.

Wrote this on my phone, hope it formats ok.

**Comment by webmobiles** [comment]
thanks, format is ok; i understood.

**Comment by pkozlowski-opensource** [comment]
Thnx @jmcgoldrick for helping out with support questions!
