### ISSUE TITLE
rxjs updated gives error with mapping

### ISSUE THREAD

**Issue by dntquitpls** [angular/angular#10970]
I recently updated my version of rxjs from beta.2 to beta.11 and same to other packages now my map does not work... I tried to do same as here https://github.com/ReactiveX/rxjs/issues/1888 like others did, same error: 
`Property 'map' does not exist on type 'Observable<Response>'.`
My `service.ts` looks like this:
```
import Rx from "rxjs"
import {Http} from "angular2/http";
import {Injectable} from "angular2/core";
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/from';
import 'rxjs/add/operator/map;
@Injectable()
export class ApiService {
constructor(private http: Http) { }

get(onNext: (json: any) => void) {
    this.http.get("api/random").map(response => response.json()).subscribe(onNext);
}}
```

and my package JSON looks like this (part of it):

```
"dependencies": {
"angular2": "2.0.0-beta.17",
"bootstrap": "3.3.7",
"es6-promise": "^3.2.1",
"es6-shim": "^0.35.1",
"jquery": "3.1.0",
"reflect-metadata": "0.1.8",
"rxjs": "5.0.0-beta.11",
"systemjs": "0.19.36",
"zone.js": "0.6.15",
"typescript": "1.8.10"  },
```

Also i realised when I updated my `rxjs` from beta.2 to beta.11 the bundles folder changed there were also `Rx.js` and also `Rx.umd.js`, now only `Rx.umd.js` is left... Thought might be that visual studio does not download full library... However tried with `Node.js` also, same downloaded files... But cannot find anything on rxjs changelog about these changes...

Would be very appreciated for any help.

**Comment by zoechi** [comment]
You posted this question already at SO. There is no need to post it here as well.

This looks like a support question anyway.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
