### ISSUE TITLE
Feature Request: configure dynamic base-href during bootstrap

### ISSUE THREAD

**Issue by BernhardRode** [angular/angular#10976]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
<base href="/"> in HTML Head

**Expected/desired behavior**
Set base href on bootstrap in runtime.

**What is the motivation / use case for changing the behavior?**
I had some angular 1 projects, where we had problems with not being able to change the base href bootstrap or runtime. 

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.5
* **Browser:** all
* **Language:** all

**Comment by zoechi** [comment]
What about 
```ts
providers: [{APP_BASE_HREF, useValue: 'someValue'}]
```
?

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
