### ISSUE TITLE
angular-forms: "Cannot read property 'validate' of null" on AoT compiled app

### ISSUE THREAD

**Issue by sod** [angular/angular#10975]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**

`normalizeValidator` in [normalize_validator.ts](https://github.com/sod/angular/blob/eef9512ce6b8b72f8753d2964304745d621cf0d7/modules/@angular/forms/src/directives/normalize_validator.ts#L14-L14) checks for undefined, but most default values on controls are null:

![image](https://cloud.githubusercontent.com/assets/905328/17849381/cbe8314e-6858-11e6-934b-a85830fe3542.png)

Results in Error: `Cannot read property 'validate' of null`

**Reproduction of the problem**

Error does not happen in JIT, but when app precompiled and router is used.

**Plunkr**: http://plnkr.co/edit/j4j4stKtA9dRbEwBdhXC?p=preview `app/app-precompiled.ts` is the precompiled `app/app.ts` via `ngc`. 

Versions used:

```log
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/compiler-cli": "0.5.0",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/platform-server": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Language:** [TypeScript 2.0.0]

**Comment by antonybudianto** [comment]
same issue here

**Comment by MehdiRahimiN** [comment]
same issue on 6.0.1
