### ISSUE TITLE
DatePipe doesn't format the date in safari

### ISSUE THREAD

**Issue by Sambego** [angular/angular#10974]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using safari, the DatePipe does not format the date correctly when formatting minutes or seconds. I've made a [plunker](http://plnkr.co/edit/lJp5xeJIBYivrxYYD6W4?p=preview) which recreates the bug.

This bug might be related to #9524.

Chrome (correct)
<img width="485" alt="chrome" src="https://cloud.githubusercontent.com/assets/1453781/17849917/3eab34b8-685b-11e6-9dbf-c243a21301d4.png">

Safari (wrong)
![safari](https://cloud.githubusercontent.com/assets/1453781/17849926/48659dfe-685b-11e6-8361-290e393eefa5.png)

It also throws the following exception when trying to transform a date manually in the component constructor:

```
TypeError: Cannot read property 'supports' of undefined.
```

the error can be recreated by uncommenting line `49` in the `app.ts` file in my plunker example.

**Expected/desired behavior**
Format the time correct.

**Reproduction of the problem**
The bug can be reproduced in Safari with this plunker: http://plnkr.co/edit/lJp5xeJIBYivrxYYD6W4?p=preview

**What is the expected behavior?**
The date should show only minutes or seconds when choosing them as format.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Safari 9.0.2 | iOS 9.3.4 Safari | iOS 9.3.4 UIWebView | iOS 9.3.4 WKWebView ] 
 
* **Language:** [all]

**Comment by laskoviymishka** [comment]
Looks like there is an issue in polyfill. Here is sample repo with direct Intl.Api calls:
http://plnkr.co/edit/HdVrwbvZkcqZclwPJHaN?p=preview
I opened corresponding issue in andyearnshaw/Intl.js#219

**Comment by laskoviymishka** [comment]
This issue would be fixed on Tuesday.

**Comment by vicb** [comment]
thanks @laskoviymishka !
