### ISSUE TITLE
Importing a Feature Module doesn't correctly import directives

### ISSUE THREAD

**Issue by leewinder** [angular/angular#10978]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Creating a directive and declaring it in the declarations section of a feature module doesn't make that directive available when the feature module is imported into the app module.

It only works if I remove the feature module import and add the directive to the app module's declarations directly.

**Expected/desired behavior**
If I declare a directive in a feature module and import that feature module into the app module should allow me to use that directive.

**Reproduction of the problem**
Plunker available here - https://embed.plnkr.co/mJGYnGKhyfY12oBpjTUG/

- feature.directive.ts - Contains a [directive-selector] and prints out *** FeatureDirective has been instantiated *** when the directive is instantiated.
- feature.module.ts - Feature module that adds FeatureDirective to declarations
- app.ts - Outputs some simple HTML that uses 'directive-selector'

Running the Plunker as it stands outputs nothing to the console log.  If you comment out 'FeatureDirective,' in feature.module.ts and uncomment 'FeatureDirective,' in app.ts and run it again, the directive is instantiated and *** FeatureDirective has been instantiated *** is outputted to the console log.

Note that if you leave FeatureDirective declared in both modules you do get an error about the directive being defined twice, so it is being see in the feature module.

**What is the expected behavior?**
It is expected that '*** FeatureDirective has been instantiated ***' is outputted when FeatureDirective is declared in feature.module.ts.

**What is the motivation / use case for changing the behavior?**
NA

**Please tell us about your environment:**
Plunker

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Chrome 52.0.2743.116 (64-bit)
 
* **Language:** TypeScript 1.8.10

**Comment by pkozlowski-opensource** [comment]
You are missing `exports: [FeatureDirective]` in your `FeatureModule`: https://plnkr.co/edit/mJGYnGKhyfY12oBpjTUG?p=info

You need both `declarations` and `exports`:
* `declarations` means: this directive / pipe is available to other directives _in the same module_
* `exports` means: this directive / pipe is available to _other modules_ importing a given module

**Comment by leewinder** [comment]
Of course!  Apologies for the superfluous bug report :)
