### ISSUE TITLE
angular-router: component that throws an error on creation is not removed from outlet on navigation

### ISSUE THREAD

**Issue by sod** [angular/angular#10977]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
```

**Current behavior**

When a component throws an error on creation, the router doesn't destroy it on next navigation attempt.

**Reproduction of the problem**

Plunkr: http://plnkr.co/edit/PyNB31LvMSq535jMqFWK?p=preview

After click on the link, the view looks like this:
![image](https://cloud.githubusercontent.com/assets/905328/17853967/f47ae856-686f-11e6-8efb-0d49bae666fd.png)

It should look like this:

![image](https://cloud.githubusercontent.com/assets/905328/17853975/03e3cccc-6870-11e6-9dbd-edd26687f62b.png)

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all] 
- **Language:** [TypeScript 2.0.0]

**Comment by vsavkin** [comment]
Doesn't seem to be an issue in RC6. Check after RC6 is out.

**Comment by sod** [comment]
No, same behavior in angular2@2.0.1 & router 3.0.1

http://plnkr.co/edit/XncKobipW9i0auvZbTwl?p=preview

**Comment by DzmitryShylovich** [comment]
@sod what's the expected behavior? What should we do with the error in this case?

**Comment by sod** [comment]
Either throw an error and crash or remove the old component from outlet before adding a new one. But never append a new component into the outlet, while the old one zomies around.

**Comment by DzmitryShylovich** [comment]
> Either throw an error and crash

I've tested it with webpack and it already works like this.

>  append a new component into the outlet, while the old one zomies around

it only works like this with systemjs

**Comment by sod** [comment]
I'm fine with it working with webpack, as we switched to webpack already.

**Comment by sod** [comment]
might have been fixed by https://github.com/angular/angular/pull/16426 / https://github.com/angular/angular/commit/e263e19a2ae8f7dc6457e5cefb4d27887c111f96
