### ISSUE TITLE
Router fails to reuse loaded Component when parameters change (lazy-loaded routes only)

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#10987]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When navigating to a route that uses the same component type as is currently loaded, eg: from `/users/1` to `/users/2`, the router fails to reuse the same component instance if the route was lazy-loaded. Instead, the component is destroyed and a new instance created.

**Expected/desired behavior**
The same, already loaded instance should be re-used. [According to the docs](https://angular.io/docs/ts/latest/guide/router.html):

> 
By default, the router reuses a component instance when it re-navigates to the same component type without visiting a different component first. The parameters can change between each re-use.

**Reproduction of the problem**
 - [Open this plunker](http://plnkr.co/edit/BCUlXdyUWpLMWuWO5do1?p=preview)
 - On `LazyLoadedComponent`, trigger navigation by clicking `Next ID` button. Notice that each time, the component is re-initialized.

![2](https://cloud.githubusercontent.com/assets/12346501/17863994/1c5a0f88-686a-11e6-85ac-b9237c56333e.png)

 - On `HomeComponent`, the same action does not cause the same effect

![3](https://cloud.githubusercontent.com/assets/12346501/17864002/21a95ffc-686a-11e6-8686-795d3215bb3e.png)

**What is the expected behavior?**

The same component instance should be re-used in accordance with the docs

**What is the motivation / use case for changing the behavior?**

Behavior does not comply with the docs, and it's inefficient to destroy a component only to rebuild it

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** 
 
* **Language:** TypeScript 1.9

**Comment by ericmartinezr** [comment]
If I'm not wrong this was fixed via https://github.com/angular/angular/pull/10707

**Comment by RoxKilly** [comment]
@ericmartinezr thanks for the reference. I probably missed it in my search because the issue was closed even though the problem persists in the most current version of Angular.

Speaking of which, is there any way to tell when you look at a PR, which version of the library it will be applied to?

**Comment by zoechi** [comment]
Compare the date when it was merged and if it was merged before the last release, check https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by robwormald** [comment]
yep, this is corrected on master and should be in the next release of the router.

**Comment by SaraSlm** [comment]
how can i put lazy loading in my project? please help me

**Comment by RoxKilly** [comment]
@SaraSlm https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load
