### ISSUE TITLE
Need some way for directives to react to "global" events

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1098]
There needs to be some way for directives to react to things like a `resize` event on the window or a `scroll` event on the document body.

**Comment by mhevery** [comment]
Could this be handled by event manager? By binding to events such as `window-resize` or something along those lines?

We want to make sure that we clean up these events when the component is destroyed.

```
@Decorator({
  selector: '[foo]',
  events: {
    'window-resize': 'onResize()'
  }
})
class Foo {
  onResize() {
    ...
  }
}
```

@pkozlowski-opensource would you like to take a crack on this?
