### ISSUE TITLE
Testing components in isolation

### ISSUE THREAD

**Issue by davityle** [angular/angular#10984]
**I'm submitting a ...**  (check one with "x")

```
[X ] feature request
```

**Current behavior**

In order to test components in isolation, before each test we 

```
TestBed.resetTestEnvironment();
TestBed.initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
TestBed.configureTestingModule({
    providers: providers,
     declarations: declarations,
});
TestBed.compileComponents().then(() => TestBed.createComponent(Component));
```

We do this because each of our tests is going to have individual mocked out providers and. ideally, each test would only have the declarations needed for that test. In earlier versions of Angular this was trivial with `addProviders` and with components separately listing their component/directive/pipe dependencies each test only compiled/used the necessary components. 

With the new changes to the testing framework and using the provided code our tests have become unreasonable. If we only declare the components that are needed for the test then we have to manually trace the dependency tree for each component and make sure that all components are added by hand to the test module. If we use the same list of components that are used in our module then each component is recompiled every test and it takes several seconds per test to recompile each component. Reusing all providers and all components in all tests is a global mess that is out of the question. 

**Expected/desired behavior**

The way it used to work where we could test components in isolation with only their dependencies and custom providers without manually building a dependency tree.

**Comment by alexeagle** [comment]
@vikerman has discussed some ideas for this.

**Comment by pauldraper** [comment]
@alexeagle, where?

**Comment by alexeagle** [comment]
He has written a design doc but I think it's not shared publicly yet. When Vikram comes back from vacation next week he may be able to get it to a state where it can be shared.

**Comment by stringham** [comment]
@alexeagle @vikerman any updates on this?

**Comment by alexeagle** [comment]
A design doc was started but not ready to share yet. Not high priority so it will still be ~months.

**Comment by alexeagle** [comment]
I think Angular Playground is the best option right now.
