### ISSUE TITLE
bug: Dashed class name in @PropertySetter causes error

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1099]
```
Potentially unhandled rejection [2] ReferenceError: Invalid left-hand side in assignment
```

This is from:
```js
@PropertySetter('class.aside-content') asideContent: Function,
```

As soon as I set it to non-dashed-case, it works fine.

```js
@PropertySetter('class.asidecontent') asideContent: Function,
```

**Comment by pkozlowski-opensource** [comment]
@ajoslin are you on the latest master? Isn't 58dd75a1c8abfa8396ead9b2b1c95dc6c6558668 fixing this for you?

**Comment by ajoslin** [comment]
Actually, no class binding works. `class.asidecontent` just fails when you run the setter.

**Comment by ajoslin** [comment]
Yes, I'm on the latest master.

**Comment by pkozlowski-opensource** [comment]
How do you call your setter function?

**Comment by ajoslin** [comment]
Just with a boolean. `setter(true)`

**Comment by ajoslin** [comment]
Temp fix:
```
this.asideOpenSetter = is => { ngEl.domElement.classList[is?'add':'remove']('aside-open'); }
```

**Comment by mhevery** [comment]
@pkozlowski-opensource can we add a use case to a test to demonstrate that this works as expected.

**Comment by pkozlowski-opensource** [comment]
Apparently @mlaval checked it on the latest master and things seem to work. We are going to add a test to prove it :-)

**Comment by ajoslin** [comment]
Sorry guys, bad call. I found a bug where my update script wasn't actually updating to master. 

Ill close this now and confirm later today when I get it to work. Thanks
