### ISSUE TITLE
Returning false from a HostListener does not stop propagation to event listeners in host.

### ISSUE THREAD

**Issue by shelbyd** [angular/angular#10990]
I have the following directive.
```
@Directive({
  selector: '[clickHandler]',
})
export class ClickHandler {
  @HostListener('click')
  onClick() { return false; }
}
```

And the following component.
```
@Component({
  template: `
    <div (click)="foo()">
      <h1 clickHandler>Click on Me!</h1>
    </div>
  `,
})
export class App {
  foo() {}
}
```

When the h1 inside the App component is clicked, the [clickHandler] directives triggers as expected. But, the foo method inside App triggers also.

Since I'm returning false from the HostListener, the (click) event inside App should not propagate.

If I pass in the event to the HostListener and call stopPropagation myself, the (click) event in the host does not fire as I expected.

See this Plunker (http://plnkr.co/edit/HcXVQa1lTdiowcL9YOxP).

#9587

**Comment by shelbyd** [comment]
#9587

**Comment by c4wrd** [comment]
From my understanding, returning false from a host listener decorated method will only stop the default page action from occurring. It won't stop propagation to event listeners, which I believe is intended. For example, you could have one host listener for the 'click' event that watches for form submission events and prevents the page default handler by returning false. Declared at the top level would allow you to not need to put: `event.preventDefault()` within all of your components that request this feature of preventing default page actions.

**Comment by shelbyd** [comment]
Sorry, that's me misreading. I read "preventDefault" in the documentation as "stopPropagation".

https://angular.io/docs/ts/latest/api/core/index/HostListener-var.html
