### ISSUE TITLE
Event emitter for reset on forms

### ISSUE THREAD

**Issue by cur3n4** [angular/angular#10999]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With forms, one can subscribe to ngSubmit and be able to perform actions as a result of that.
There is no equivalent when resetting a form.

**Expected/desired behavior**
It would be very handy to have an ngReset EventEmitter which could notify subscribers of the act of resetting a form.

**Reproduction of the problem**
-

**What is the expected behavior?**
-

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** all
 
* **Language:** TypeScript X.X

**Comment by zoechi** [comment]
How do you reset a form. If you reset the form imperatively you can notify yourself. If you use a reset button, this also emits an event. 
Can you please elaborate a bit more on a use case where this would be useful? Ideally a Plunker that demonstrates where not having this event is a disadvantage?

**Comment by cur3n4** [comment]
My specific use case is a directive which displays error for controls under configurable conditions (i.e. control has focus, control touched, form touched, form submitted, etc). When the form is reset I would like these directives to act accordingly (for example to not display certain errors). 
I could certainly notify myself but it feels like a useful addition, and it makes sense to me to be in the framework: in the same way we have ngSubmit for onSubmit, we would have ngReset for onReset.

**Comment by mvar** [comment]
+1 for such feature.

**Comment by kara** [comment]
Given that you can already listen to the reset event or notify yourself, I'm inclined to think this isn't necessary. ngSubmit has extra value in that it allows the form directive's "submitted" state to be updated, but reset has no parallel state to set. I'd prefer not to add to the API surface unless it's really necessary. If more use cases come up for this in the future, we may reconsider, but closing for now.

**Comment by mvar** [comment]
@kara could you give a quick example on how to catch form event (e.g., reset) myself?

**Comment by zoechi** [comment]
@mvar GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by mvar** [comment]
@zoechi this is issue related. If you are not going to implement the requested feature, please be kind enough to give an example or link to an example how to achieve that.

**Comment by zoechi** [comment]
There are quite a lot of people nice enough to provide support - on the appropriate channels.
