### ISSUE TITLE
Resolve  feature modules for dynamic loading

### ISSUE THREAD

**Issue by abidmix** [angular/angular#10993]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no way to load a feature modules on demand without using a router

**Expected/desired behavior**
When using ngmodule,  I should be able to load a module on demand like this for example
            this.moduleFactory = moduleFactoryResolver.resolveModuleFactory(HelloModule);
 similar to what can be done with a component
     this.componentFactory = componentFactoryResolver.resolveComponentFactory(HelloComponent)

**Reproduction of the problem**
In the plunker below I can dynamically load  the components, but cannot achieve the same functionality using ngmodule
https://plnkr.co/edit/xvv77s?p=preview

**What is the expected behavior?**

I expect to  be able to load the modules dynamically, or  have a way to set the required modules in the provider section 

**What is the motivation / use case for changing the behavior?**

In a large enterprise application, we have multiple components in a business entity which have dependencies. When these components are wrapped in a module we should be be able to resolve the module like we do to components so that we can lazy load the module. Before RC5, we could explicitly set the dependencies in components using the directive declaration which meant loading dynamically the parent component would ensure dependencies for that component were automatically resolved.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript 1.8 | ES6/7 | ES5]

**Comment by brandonroberts** [comment]
You can load feature modules without the router if you use the `Compiler` directly. The router just makes use of the compiler to load modules. See the source here: https://github.com/angular/angular/blob/master/modules/%40angular/core/src/linker/system_js_ng_module_factory_loader.ts

**Comment by abidmix** [comment]
@brandonroberts  thanks for pointing me in the right direction :+1. This does what I expect now... See plunker  https://plnkr.co/edit/0GAokA?p=preview. Can you review and advise if there is any design flaw in my implementation. Because I am going to use this approach in my app which will have multiple separate components in individual folders  which I have wrapped in different modules :
