### ISSUE TITLE
[2.0.0] UpgradeAdapter - Cannot read property 'injector' of null

### ISSUE THREAD

**Issue by guojenman** [angular/angular#10992]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Unhandled Promise rejection: TypeError: Cannot read property 'injector' of null

Getting above error when trying to inject a downgraded ng2 service into a ng1 service.
Except it works when,
a) inject into a controller
b) in ng1 service use $injector.get('myNg2Service') in a timeout

Error happens here
ng1Module.factory(NG2_INJECTOR, () => moduleRef.injector.get(Injector)), which runs before moduleRef gets assigned after _bootstrapModuleWithZone

**Expected/desired behavior**
downgraded ng2 service should be available for injection immediately.

**Reproduction of the problem**
https://plnkr.co/edit/dJRu9g?p=preview

**What is the expected behavior?**
prints out "Hello from ng1 and ng 2 service"
- **Angular version:** 2.0.0 final
- **Browser:** all 
- **Language:** Typescript 2.0 & ES5
- **SystemJS** for ng2
- **IIFE** for ng1

**Comment by guojenman** [comment]
Mystery solved!

I'm injecting some services in the run() method of ng1 for initial configuration. Though ng1's injector is ready at this time, ng2's injector is not. My solution is to move this code to a later execution time.

I've updated the plnkr above with the offending code

**Comment by battmanz** [comment]
I'm getting the same issue as you. Where did you move your code that was previously in the `run` block in order to make this work?

**Comment by guojenman** [comment]
I kept it in the run() block for now, but I'm manually injecting after a timeout.

```
app.run(function($injector) {
  setTimeout(function() {
    var myService = $injector.get('myService');
  },0);
});
```
Since the services are only created the first time they're requested from the injector, this delays the creation. My other idea was to put the code on the resolve for my root (abstract) route.

**Comment by battmanz** [comment]
That seems like a reasonable workaround, but I wouldn't consider that a fix for this issue. In my opinion this issue should be reopened, so that it can be fixed within the Angular 2 framework. I don't think that every consumer of the framework should be forced to workaround this issue.

**Comment by battmanz** [comment]
Thanks for reopening!

**Comment by texel** [comment]
I came up with a bit nicer of a workaround for this:
```
// run-later.ts
export function runLater(module, injectable) {
  module.run(['$injector', (injector) => {
    setTimeout(() => {
      injector.invoke(injectable);
    }, 0);
  }]);
}
```

```
import { runLater } from './run-later';

runLater(angular.module('myModule'), ['$myService', function($myService) {
  $myService.foo();
}]);
```

**Comment by guojenman** [comment]
updated plnkr with 2.0.0 final - same problem.

**Comment by amay0048** [comment]
I had the same issue, but it was a bit trickier to work around and I had to re-structure my service. IMO this is a bug as it could pose a significant issue for upgrading depending on application structure.

Uncaught TypeError: Cannot read property 'injector' of null #11632

**Comment by amay0048** [comment]
Depending on your requirements, you can also use the .ready function of your bootstrap like this:
```
import { adapter } from './upgrade-adapter';
adapter
.bootstrap(document.documentElement, ['app'])
.ready((ref) => {
ref.ng1Injector.get('serviceToRunAsSoonAsTheAppIsReady');
});
```

**Comment by vasuneet** [comment]
it is not resolved in angular final release of 2.0.0. Any update on this ?

**Comment by Ixl123** [comment]
I have the same issue.

**Comment by guojenman** [comment]
@vasuneet @Ixl123 did the workarounds presented on this thread work for you guys?

**Comment by Ixl123** [comment]
@guojenman none of the workarounds worked for me.

**Comment by readme42** [comment]
Still broken in 2.2.0 :(

**Comment by guojenman** [comment]
switched to UpgradeComponent

**Comment by Necroskillz** [comment]
How does that solve the problem with the run block? We also ran into this issue - we can't use ng2 services with ng1 dependencies from ng1 run blocks and we also can't use `$injector` from ng2 `APP_INITIALIZER`.

**Comment by guojenman** [comment]
@Necroskillz I closed this issue because I opened it in regards to UpgradeAdapter, With the release of the UpgradeComponent API (which supports AoT), I doubt much work will be done for UpgradeAdapter.

In regards to using services from and to each frameworks, I've found that strategic use of timeouts and manually getting the services from the respective injectors has worked out for me (fairly large app, 60k+ lines of code and 10 different module bundles). I'm sure there will be cases where that may not work. One framework will be to be initialized before the other, so I'm not sure it's an easy fix.

I would suggest opening a bug against UpgradeComponent instead if this is important to you.

**Comment by lokeshnagpal** [comment]
I also getting issue in while injecting($rootScope,$filter) ng1 service using UpgradeAdaater into ng2  with AOT. Though i have installed the modules which has aot compatibility but getting an "Cannot read property 'get' of null " in $rootScope. 
And also getting No provider for $filter!

**Comment by vasuneet** [comment]
Not resolved till yet.

**Comment by gkalpak** [comment]
Have you defined the dependency on injector as explained [here][1]?
Can you provide a minimal demo of the issue?

[1]: https://angular.io/docs/ts/latest/guide/upgrade.html#!#making-angularjs-dependencies-injectable-to-angular

**Comment by vasuneet** [comment]
Yes. 
The following steps i am performing.
1. I commented the service which was working in ng1.
2. Implemented the service in Angular2 way.
3. In NgModule (app module) i have included this class in provider list.
4. in main.ts i used upgradeAdapter.downgrandNg2Provider method to do the same.

**Comment by gkalpak** [comment]
@vasuneet, can you modify [this plnkr][1] (that uses the upgrade/static version) to reproduce the problem?

[1]: http://plnkr.co/edit/mjEiZScYPhfi7dloVkIX?p=preview

**Comment by eladh** [comment]
Hi , 
I got a very similar situation.
when i was trying to use angularJS component in angular 4 app by using the UpgradeComponent and still getting the Error - 'Trying to get the AngularJS injector before it being set.
```

var UpgradeComponent = (function () {
    /**
     * Create a new `UpgradeComponent` instance. You should not normally need to do this.
     * Instead you should derive a new class from this one and call the super constructor
     * from the base class.
     *
     * {@example upgrade/static/ts/module.ts region="ng1-hero-wrapper" }
     *
     * * The `name` parameter should be the name of the AngularJS directive.
     * * The `elementRef` and `injector` parameters should be acquired from Angular by dependency
     *   injection into the base class constructor.
     *
     * Note that we must manually implement lifecycle hooks that call through to the super class.
     * This is because, at the moment, the AoT compiler is not able to tell that the
     * `UpgradeComponent`
     * already implements them and so does not wire up calls to them at runtime.
     */
    function UpgradeComponent(name, elementRef, injector) {
        this.name = name;
        this.elementRef = elementRef;
        this.injector = injector;
      ---------------this.helper = new UpgradeHelper(injector, name, elementRef);---------------------
        this.$injector = this.helper.$injector;
        this.element = this.helper.element;
        this.$element = this.helper.$element;
        this.directive = this.helper.directive;
        this.bindings = this.initializeBindings(this.directive);
        // We ask for the AngularJS scope from the Angular injector, since
        // we will put the new component scope onto the new injector for each component
        var $parentScope = injector.get($SCOPE);
        // QUESTION 1: Should we create an isolated scope if the scope is only true?
        // QUESTION 2: Should we make the scope accessible through `$element.scope()/isolateScope()`?
        this.$componentScope = $parentScope.$new(!!this.directive.scope);
        this.initializeOutputs();
    }
```
```
// Classes
var UpgradeHelper = (function () {
    function UpgradeHelper(injector, name, elementRef, directive) {
        this.injector = injector;
        this.name = name;
      ------------------this.$injector = injector.get($INJECTOR);------------------------------------------
        this.$compile = this.$injector.get($COMPILE);
        this.$controller = this.$injector.get($CONTROLLER);
        this.element = elementRef.nativeElement;
        this.$element = element(this.element);
        this.directive = directive || UpgradeHelper.getDirective(this.$injector, name);
    }

```

```

function injectorFactory() {
    if (!tempInjectorRef) {
       ----------throw new Error('Trying to get the AngularJS injector before it being set.');--------------
    }
    var injector = tempInjectorRef;
    tempInjectorRef = null; // clear the value to prevent memory leaks
    return injector;
}
```
