### ISSUE TITLE
Router RC1 router.navigate fails but routerLink works

### ISSUE THREAD

**Issue by tessSnap** [angular/angular#11004]
[ x] bug report
[ ] feature request
[ ] support request 

**Current behavior**

I have a parent component with child components I load with loadChildren
-parent
   -child
       - child-child1
              - child-child1-childA

Child has a module router . When I try navigating to child-child1-childA from   child-child1  programaticaly using router.navigate I get "Error: Cannot match any routes: "  but when i use routerLink it works .

child-child1 has a module router that looks like this 

export const routing = RouterModule.forChild([
 
  {path :'' ,  component:ChildChild1Component},
  
  {path:'child_Child1_ChildA',loadChildren:'path_to_module'}

]);

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
***Angular 2 router version** 3.0.0-rc.1
* **Browser:** [Chrome ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by brandonroberts** [comment]
Can you reproduce this in a plunker?

**Comment by lucamorelli** [comment]
I have the same problem with a minimal project. Is there any angular2 ts plunker template to reproduce it?

**Comment by brandonroberts** [comment]
Sure http://plnkr.co/edit/tpl:0Qv95J?p=preview

**Comment by lucamorelli** [comment]
http://plnkr.co/edit/jO70E07Wz5nPjTHSN1re?p=preview
looks like the problem is the call to the navigate in the ngOnInit of the appComponent. If I move the code to the ngInit inside the home component it works

**Comment by brandonroberts** [comment]
This seems like a race condition. In the plunker, the navigation to `away` happens before the initial navigation to `/`. If another navigation comes in during an in-flight navigation that hasn’t completed, its cancelled. This is as designed but the `/` navigation to should happen first.

If you try to navigate within the AppComponent inside ngOnInit, the navigation is scheduled before the router's initial navigation to the current URL.

cc: @vsavkin

**Comment by vsavkin** [comment]
By default, the router sets up a location listener and then performs an initial navigation. This happens after the component has been instantiated. That is why the initial navigation overrides your navigation.

To fix it, bootstrap the router with `Router.forRoot(routes, {initialNavigation: false})`.

**Comment by lucamorelli** [comment]
ok, thanks. btw: this parameter is not present in the rc5 .d.ts and gives compilation error
