### ISSUE TITLE
Nested Dynamic Components Break With ComponentFactoryResolver and ViewChildren

### ISSUE THREAD

**Issue by frickt** [angular/angular#11007]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When trying to render nested dynamic components via the ComponentFactoryResolver I receive an exception/error message:

browser_adapter.js:84Error: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: 'null'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?

**Expected/desired behavior**
It should render the nested dynamic controls. This had worked until the introduction of the ComponentFactoryResolver.

**Reproduction of the problem**
Here is the plunkr recreating the issue: http://plnkr.co/edit/BfqEYqNqyZuJDytt1DCc?p=preview

It's a duplicate of [https://github.com/angular/angular/issues/10762](url) except that the solution provided does not work for ViewChildren, it only works for ViewChild.

**What is the expected behavior?**
I should be able to render a control via ComponentFactoryResolver which in turn also renders multiple controls via ComponentFactoryResolver.

**What is the motivation / use case for changing the behavior?**

It used to work.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by jpleclerc** [comment]
#10762

**Comment by sinedsem** [comment]
@frickt hi.
I've faced the save error as you, but even so could not understand your plunker. So, let me provide another one: [Plunker issue demo](http://plnkr.co/edit/myu7qXonmpA2hxxU3SLB?p=preview). It is also on **rc6 version**.

And for everybody, faced this issue I can suggest a **workaround**, which can be painlessly cleaned when this issue will be fixed. My suggestion is to wrap `createComponent` call into `setTimeout`:

```
setTimeout(()=> {
    elem.createComponent(this.contentFactory, 0);
}, 1);
```
[**Workaround Plunker**](http://plnkr.co/edit/mZSc40KbgBk2azpPVG3g?p=preview)

**Comment by zoechi** [comment]
Just use `ngAfterViewInit()` instead of `ngOnInit()`. Angular2 doesn't like the model getting changed in `ngOnInit()` because this is called by change detection and you get this error if change detection itself causes model changes.

**Comment by sinedsem** [comment]
@zoechi, no, this is another issue.

**Comment by zoechi** [comment]
@sinedsem I don't understand your comment. What is another issue? I changed `ngOnInit()` in the Plunker of the initial issue and the error went away.

In your Plunker it doesn't matter where you put your code because not the code in the lifecycle callback modifies the model, but the `callback passed to `this.viewContainerRef.changes.subscribe(...)`, which is executed sometimes later, when changes are detected (also invoked by Angular change detection and thus causes the exception). 
Injecting `cdRef:ChangeDetectorRef` and calling `this.cdRef.detectChanges()` after the modification might be more efficient than `setTimeout()`
http://plnkr.co/edit/3FKL627sJq3eHME04nGD?p=preview

**Comment by frickt** [comment]
@zoechi since rc.5 it's not allowed to change the model within ngAfterViewInit() there is always a "Expression has changed after it was checked" exception.

**Comment by zoechi** [comment]
@frickt Oh, didn't know that. `detectChanges()` should then be the fix for your case as well.

**Comment by frickt** [comment]
@zoechi Oh, explicit calling detectChanges() in ngAfterViewInit() resolves to issue, as you said. didn't know that. Thank you.

**Comment by matheo** [comment]
`detectChanges()` doesn't work on 4.1.1, setTimeout does tho.
