### ISSUE TITLE
Method to get current route object

### ISSUE THREAD

**Issue by rodchenkov** [angular/angular#11006]
Hi

I want to create breadcrumbs and menu using RouterConfig and current route.
I need to get current route object from RouterConfig.

`export const appRoutes:  
  RouterConfig =[
  {
    path: "",
    component: HomeComponent,
    terminal: true,
    data: {
            title: "Home"
          }
   },
   {
     path: "Users",
     component: UserListComponent,
     data: {
            title: "Users"
           }
      },
      {
        path: "Users/:id",
        component: UserEditComponent,
        data: {
              title: "Edit User"
               }
      }
 ];`

As you can see using such solution I can solve breadcrumbs and menu items, but I don't see any method in Angular 2 that can provide me current route object from RouterConfig.

Thank you and for your hard work on Angular 2

**Comment by brandonroberts** [comment]
The `ActivatedRoute` you inject provides a `routeConfig` property that exposes this information

**Comment by felipedrumond** [comment]
@brandonroberts Is it a RC5 improvement? I'm using RC4 and there is no such property.

**Comment by rodchenkov** [comment]
@brandonroberts will it work with params in path? I mean when I have path like: Users/:id

Thank you for your reply.

**Comment by felipedrumond** [comment]
@rodchenkov If you create a shared service like @brandonroberts said, you can set one of its property with your param[id] so that every consumer of that service will have access to this property.

**Comment by brandonroberts** [comment]
@rodchenkov yes. It will give you the same config used in the route configuration.

**Comment by vsavkin** [comment]
Closing this issue

**Comment by cuongle121** [comment]
Hi, thanks for the hard work.
I am using @angular/router 3.2.4 and try to get the configRoute at `this.activatedRoute.routeConfig` but it gives me `null` (I am quite sure I injected ActivatedRoute successfully). Please correct me if I am using it the wrong way. I just start using angular2 for several days.
Thanks!

**Comment by brandonroberts** [comment]
@cuongle121 you'll have to provide some more information like what your route structure looks like.

**Comment by cuongle121** [comment]
Hi @brandonroberts

My route config
```
export const rootRouterConfig: Routes = [
  {path: '', redirectTo: '/products/sign-up', pathMatch: 'full'},
  {path: 'products/sign-up', component: SignUpComponent, data: {title: 'Sign Up'}}
  {path: 'products/news', component: NewsComponent, data: {title: 'News'}}
];
```

My AppComponent
```
constructor(private router: Router, private activatedRoute: ActivatedRoute) {
  this.router.events.subscribe( (event) => {
    if (event instanceof NavigationEnd) {
      console.log('FROM APPCOMPONENT ----------');
      console.log(this.activatedRoute.routeConfig);
    }
  });
};
```

My SignUpComponent
```
constructor(private router: Router, private activatedRoute: ActivatedRoute) {
  this.router.events.subscribe( (event) => {
    if (event instanceof NavigationEnd) {
      console.log('FROM SIGNUPCOMPONENT ----------');
      console.log(this.activatedRoute.routeConfig);
    }
  });
};
```

I just put my code to log the routeConfig in SignUpComponent also and realized that the log from AppComponent is *always* null, and the log from SignUpComponent is *always* the route config of the url `products/sign-up` *even I have switched to News page*.
What I want to do is that I will take the `routeConfig.title` of the current page and use it in AppComponent. Maybe this is not the way to do it? Sorry if my angular2 skill is not good enough.

Thanks!
