### ISSUE TITLE
Angular rc5 is not working on all browsers of ipad air 2 and iphone 6

### ISSUE THREAD

**Issue by ashokacharya** [angular/angular#11000]
**Current behavior**
Is Only showing loading... but application is not open.rc4 used to work on all browsers of iphone and ipad

**Expected/desired behavior**
To work as Rc4 used to

**Please tell us about your environment:**

Angular version: 2.0.0-rc.5
Browser: iOS XX Safari 
Device:Iphone 6 and Ipad air 2

**Comment by ashokacharya** [comment]
I think loading component with barells is causing it bug

**Comment by zoechi** [comment]
Plunker to reproduce?
Please fill the entire issue template.

**Comment by ashokacharya** [comment]
@zoechi i have big project application .whole app is not working .what kind of plunker of which part is to provide in plunker.And problem is in Iphone and Ipad browser so i dont have console error to show you.But when i access direct from folder instead of barrel it is working.but without barrel my code become lengthy

**Comment by qdouble** [comment]
@ashokacharya using barrels can lead to creating circular dependencies and other unexpected behavior. Currently, I think it would be better to maximize the use of modules and many have agreed that the suggestion to use barrels should be removed from style guide after rc5. 

To fix your problem though, you could hunt down the circular dependencies other other issues the barrels are creating, but I'd advise avoiding you to avoid using them.

**Comment by ashokacharya** [comment]
Thanks @qdouble  , @zoechi
