### ISSUE TITLE
Route children redirect issue

### ISSUE THREAD

**Issue by hllink** [angular/angular#11008]
I'm submitting a ...
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
 When you have a children route that redirects to another route at same level it throws an exception:
` platform-browser.umd.js:937 EXCEPTION: Error: Uncaught (in promise): [object Object]`

**Expected/desired behavior**
Redirection the the expected children element.

**Reproduction of the problem**
Trying to redirect a children route to the same level 
```
children: [
      { path: 'enderecamento', component: EnderecamentoComponent,},
      { path: '', redirectTo: 'enderecamento', pathMatch: 'full' }
]
```
produces the error, if you change to 
```
children: [
      { path: 'enderecamento', component: EnderecamentoComponent,},
      { path: '', component: EnderecamentoComponent, }
    ]
```
the route is loaded as expected, but if you click on the router link to 'enderecamento' gonna produce the same error.

Redirection plnkr:
http://plnkr.co/edit/xRu4pS
Redirection routerLink plnkr:
http://plnkr.co/edit/d4xRtw

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
* **Angular router:** 3.0.0-rc.1
* **Browser:**  All

**Comment by brandonroberts** [comment]
You're not using the `pathMatch` property correctly here. The `pathMatch` full essentially uses an exact comparison to the path. In this case the `pecaJuridica` is an exact match and will never reach its child routes.

```ts
  {
    path: 'pecaJuridica',
    component: PecaJuridicaComponent,
    pathMatch: 'full',
    children: [
      { path: 'enderecamento', component: EnderecamentoComponent,},
      { path: '', component: EnderecamentoComponent, }
    ]
  },
```

should be

```
  {
    path: 'pecaJuridica',
    component: PecaJuridicaComponent,
    children: [
      { path: 'enderecamento', component: EnderecamentoComponent,},
      { path: '', component: EnderecamentoComponent, }
    ]
  },
```

**Comment by hllink** [comment]
@brandonroberts goddammit, my bad. I'm kinda ashamed that i reported that as a bug and didn't found that before. Can someone mark this as closed? thanks.
