### ISSUE TITLE
Forms template-driven is not validating type email

### ISSUE THREAD

**Issue by Serginho** [angular/angular#11010]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular is not considering the input's type to check the validity.

**Expected/desired behavior**
Consider type as a validation rule.

**Reproduction of the problem**

We have that input:
```
<input type="email" class="form-control" placeholder="Email"
            #email="ngModel" name="email" ngModel required>
```
There is two validation rules here, one of them is required, and the other is the type email. Angular is only considering the first one.
Example in plunkr: http://plnkr.co/edit/DnqTpa7fktLhwGMqmox8

**What is the expected behavior?**
Validate both rules

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome] 
 
* **Language:** [TypeScript 1.8]

**Comment by kara** [comment]
Angular doesn't yet have an email validator directive.  It's a feature we plan on adding eventually.  See https://github.com/angular/angular/issues/2962.

**Comment by Serginho** [comment]
Ok @kara . Then the only way to validate an email (template-driven) is using "pattern", isn't it?

**Comment by kara** [comment]
You can use pattern or you can write a custom validator, it's up to you. Hopefully, we can get some of the data type validators to be built-in soon.

**Comment by shivarajnaidu** [comment]
sad but truth..
It's annoying, not able to use/utilize built-in  validations in Angular :disappointed:
