### ISSUE TITLE
ViewChildren query in abstract base class not run when dynamically creating component

### ISSUE THREAD

**Issue by corey-waymark** [angular/angular#11011]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I have a directive I use a lot in my application. It works via a service, which is scoped to each component, and a ViewChildren query to pull all instances of the directive into the component. To make this easier, I created an abstract base class containing the service set-up on AfterViewInit, using the ViewChildren query which is also in the abstract class. 

This works fantastically, except for components which I create dynamically using the ComponentFactoryResolver and a ViewContainerRef. In these, the ViewChildren query isn't populated on AfterViewInit (remaining undefined). 

Replacing the abstract class with a direct implementation for the dynamically created components works, and the base class approach works for normally generated components, but I don't see why the base class approach doesn't work for dynamic components.

**Expected/desired behavior**

Either the ViewChildren query should always work via a base class, or it shouldn't. It should not depend on if the component comes from the router, a parent component, or is dynamically created.

**Reproduction of the problem**

It's a rather complex setup in a large-ish app, so it would take me a while to setup a plunker. I will try to if requested.

**What is the expected behavior?**

See above

**What is the motivation / use case for changing the behavior?**

Consistency

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Chrome 52
 
* **Language:** TypeScript 1.8

**Comment by pkozlowski-opensource** [comment]
> It's a rather complex setup in a large-ish app, so it would take me a while to setup a plunker. I will try to if requested.

A minimal Plunker is mandatory, yes.

**Comment by zoechi** [comment]
Sounds like #5415

**Comment by corey-waymark** [comment]
Can't reproduce in plunker (works as expected), it sounds likely that it's just some issue with my application.
