### ISSUE TITLE
Error: No XHR implementation has been provided.

### ISSUE THREAD

**Issue by jorgeunimicro** [angular/angular#11015]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behaviour**
When the compiler receives a Module or component with `templateUrl` throws the next error:
`Error: No XHR implementation has been provided.`

No error is thrown if we use `template` in the `@Component` decorator

**Expected/desired behaviuor**
The compiler should be able to compile `templateUrl` properly.

**Reproduction of the problem**
You can see this behaviour in this plunkr: http://plnkr.co/edit/qQcl0OLshukx7rnsE0M7?p=preview

**What is the expected behaviour?**
The compiler should be able to compile `templateUrl` properly.

**What is the motivation / use case for changing the behavior?**
To load components dynamically in our apps

**Please tell us about your environment:**

node version: 4.1.1
typescript version: 1.8.10

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** all
* **Language:** Typescript

**Comment by meriturva** [comment]
Same problem here,
what i see is that we have to provide a specific XHR to do that.....so:

`    providers: [
        COMPILER_PROVIDERS,
        provide(XHR, { useClass: BrowserXhr }),`

on providers module declaration....but now i get error like:

`TypeError: this._xhr.get is not a function`

Where is a correct implementation of XHR for loading dynamic component based on templateUrl?

Any help here?

**Comment by meriturva** [comment]
New update here, i have found that maybe we have to use that configuration:

`providers: [
        COMPILER_PROVIDERS,
        provide(ConnectionBackend, { useClass: XHRBackend }),
        provide(XHR, { useClass: Http }),....`

But now i get error:
`TypeError: this._fetch(...).then is not a function`
that because:
`DirectiveNormalizer.prototype.normalizeTemplateAsync = function (directiveType, template) {
            var _this = this;
            var templateUrl = this._urlResolver.resolve(directiveType.moduleUrl, template.templateUrl);
            return this._fetch(templateUrl)
                .then(function (value) { return _this.normalizeLoadedTemplate(directiveType, template, value, templateUrl); });
        };`

and `this._fetch(templateUrl)` just return an `observable` not a `promise` in this case.

**Comment by jorgeunimicro** [comment]
Now in that plunkr I am just seeing: 
![image](https://cloud.githubusercontent.com/assets/9821702/17959562/6fef530e-6aa1-11e6-9d9d-22d516a94749.png)

**Comment by meriturva** [comment]
Here error image:

![cattura](https://cloud.githubusercontent.com/assets/5664195/17961912/8d24ee18-6aae-11e6-8894-faa8ddb733ed.PNG)

**Comment by jorgeunimicro** [comment]
My solution for now is to substitu all `templateUrl` by 'template' in the build process. I think the problem relies on that I join all my ts files in one bundle and I use angular umd packages and System `module` in my `tsconfig.json`. Because of that I don't have `moduleId: module.id` in my components

That is the only difference I find with this other example I have found:
https://github.com/leewinder/ng2-dynamic-dialog

**Comment by meriturva** [comment]
@jorgeunimicro Your solution is just to replace process to load external template to inline template...and it is ok! But i have to find a fix for `templateUrl` approach.
Any help from angular team for example @tbosch ...i think you are expert of dynamic loaded component and compiler staff! Thanks

**Comment by meriturva** [comment]
Hi to all....any news here? i really need to find a fix as soon as possible.

**Comment by jorgeunimicro** [comment]
@meriturva have you seen the `ng2-dynamic-dialog`? It works there. I think you should assign a `moduleId` property to the `@Component` decorator. In SystemJS you can use `__moduleName` instead of `module.id`, so:

```
@Component({
    moduleId: __moduleName
})
```

I hope this works for you

**Comment by meriturva** [comment]
So thanks @jorgeunimicro,
actually i have found on [ng2-dynamic-dialog](https://github.com/leewinder/ng2-dynamic-dialog) a different approach based on `ComponentFactoryResolver` instead of `RuntimeCompiler` so now our project has:

```
let layoutComponentFactory = this.resolver.resolveComponentFactory(layoutType);
this.layout = this.target.createComponent(layoutComponentFactory);
```

Main question now is ...witch approach is the best one? we think here that all Dynamic/Compiler staff need more official samples and docs. We know that it is a really new and complex architecture but web app are every day more complex so.....

**Comment by meriturva** [comment]
I have also tested to load dynamically ngModule:
here a modified version: https://plnkr.co/edit/auX7Eq?p=preview

Important: 
use `compiler.compileModuleAndAllComponentsSync(MyModule)`

**Comment by cyberbobjr** [comment]
Hi,
same problem here : XHR error implementation when i want to compile runtime component ...

**Comment by meriturva** [comment]
Hi @cyberbobjr ...are you using `ComponentFactoryResolver` as:

```
let layoutComponentFactory = this.resolver.resolveComponentFactory(layoutType);
this.layout = this.target.createComponent(layoutComponentFactory);
```

?

**Comment by cyberbobjr** [comment]
Hi @Merituva, thanks for your help.
I didn't use ComponentFactoryResolver because i loaded all my component from a config file.
I need this system because we want to use a "widget store" (with more than 100+ widgets), and every user can choose widgets inside this store. The configuration is then saved inside a json file which will be loaded after the auth process inside Angular2.

Well, that why we use this code snippet for creating component :

```
    this._compiler
        .compileComponentAsync(comp, AppModule)
        .then(factory => {
          this.container.createComponent(factory, index, this.container.injector)
        });
```

where "comp" is a runtime component loaded with SystemJs (System.import(path))

But when we use compileComponentAsync function, the templateUrl is breaken (with xhr error, like the 1st post)

best regards

**Comment by meriturva** [comment]
@cyberbobjr We have also a library with few widgets (not for sure 100+ :) ). And we are using new `ngModule` and call `compiler.compileModuleAndAllComponentsSync(MyModule)`
with this approach i see that `templateUrl` works correctly plus all components are loaded from just one import of whole module (`MyModule`).

**Comment by cyberbobjr** [comment]
@meriturva : i already tested this solution :) but i can use templateUrl only if i create another empty module AND i use this module for the compileComponentAsync like this :
```
    this._compiler
        .compileComponentAsync(comp, EmptyModule)
        .then(factory => {
          this.container.createComponent(factory, index, this.container.injector)
        });
```

In this case, the templateUrl is correct, but not for the component  loaded dynamically ! it's works only for "container" :/
this is my complete code (config.json is my config file with name and path of components) :
```
import {
  Component,
  ComponentFactoryResolver,
  ViewContainerRef,
  ViewChild,
  OnInit,
  Compiler
} from '@angular/core';
import {RuntimeCompiler} from "@angular/compiler";
import {EmptyModule} from "./empty.module";

export class MyComponentLoader {
  loadComponentConfig(url) {
    return fetch(url)
      .then(res => res.json())
      .then(componentList => Promise.all(
        componentList.map(config => this.loadComponent(config))
        )
      );
  }

  loadComponent(configObject) {
    return System.import(configObject.path)
                 .then(componentModule =>
                   componentModule[configObject.component]
                 )
  }
}

@Component({
  moduleId: module.id,
  selector: 'ng-smartdesk',
  templateUrl: './smartdesk.component.html',
  providers: [MyComponentLoader],
})
export class SmartdeskComponent implements OnInit {
  @ViewChild('widgets', {read: ViewContainerRef})
  container: ViewContainerRef;

  constructor(private _loader: MyComponentLoader,
              protected _compiler: RuntimeCompiler) {
  }

  ngOnInit() {
    this._loader.loadComponentConfig('/app/config.json')
        .then(components => {
          if (components) {
            Promise.all(components.map(test => this.loadComp(test, null)));
          }
        }, error => console.log(error));
  }

  private loadComp(comp: Component, index: number) {
    this._compiler
        .compileComponentAsync(comp, EmptyModule)
        .then(factory => {
          this.container.createComponent(factory, index, this.container.injector)
        });
  }
}
```

**Comment by tbosch** [comment]
So the problem in your plunker is that you add the `COMPILER_PROVIDERS` again in one of your components, and then you try to inject `RuntimeCompiler`. This will create a new instance of the compiler without the required configuration.

Instead, inject [`Compiler`](https://github.com/angular/angular/blob/master/modules/@angular/core/src/linker/compiler.ts) from `@angular/core` without adding extra providers. This class is always available and will work if you are using runtime compilation but will error when using AoT.

Please also note that everything under `@angular/compiler` is considered private API and might change any time. So using `Compiler` from `@angular/core` keeps your app future proof.

**Comment by tbosch** [comment]
If you really need to create a new instance of the compiler, you can do the following:
```
import {CompilerFactory} from '@angular/core';

const compilerFactory: CompilerFactory = platformBrowserDynamic().injector.get(CompilerFactory);

const compiler = compilerFactory.createCompiler(options);
```

See https://github.com/angular/angular/blob/master/modules/@angular/core/src/application_ref.ts#L301

**Comment by cyberbobjr** [comment]
Hi @tbosch ,
yeak it's working !!! thank you so much :)
Now i can load all my components ("widgets") from a json file in a runtime environnement :))

best regards

**Comment by pkozlowski-opensource** [comment]
This sounds like a support request that got resolved.
