### ISSUE TITLE
bug(testing) whenStable / template driven forms not working as expected (autoDetectChanges is needed)

### ISSUE THREAD

**Issue by choeller** [angular/angular#11012]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Testing Template Driven Forms only work when using `fixture.autoDetectChanges()`
However having a template driven form like this:

``` ts
@Component({
  selector: 'app-welcome',
  template: `
  <form novalidate (ngSubmit)="saveTask(form.value)" #form="ngForm">
  <div class="form-group">
    <label>Titel*</label>
    <input type="text" class="form-control"
           name="title" [(ngModel)]="task.title"
           #title="ngModel" required/>
  </div>
  <button type="submit" class="btn btn-default"
          [disabled]="!form.valid">
    Aufgabe speichern
  </button>
</form>
  `
})
class WelcomeComponent {
  task = {};
  @ViewChild(NgForm) ngForm: NgForm;
}
```

and this test:

``` ts
describe('WelcomeComponent: ', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [FormsModule],
      declarations: [ WelcomeComponent ]
    })
  });

  describe("two way forms", () => {
  fit("create controls automatically", (done) => {

    let fixture = TestBed.createComponent(WelcomeComponent);
   // fixture.autoDetectChanges(true);
    fixture.whenStable().then(() => {
      fixture.detectChanges();
      let form = fixture.componentInstance.ngForm.form;
      expect(form.get('title').valid).toBeFalsy() //Cannot read property 'valid' of null
      done();
    })
  })
})
});
```

The test crashes with "Cannot read property 'valid' of null". So there is no chance to get this test passing without adding `fixture.autoDetectChanges(true);`. 

**Expected/desired behavior**

It should be able to make the test pass without adding autoDetectChanges(true). Also: is there a reason / situation where I don't want autoDetectChanges? So this could be default. The current behaviour almost cost me a day of trial and error and no one on the forum had any idea about the fact the autoDetectChanges is needed, so I'm quite sure people will run into this and get as frustrated as I got ;)

The test above should work. 

**Reproduction of the problem**
http://plnkr.co/edit/loeGr7y7k3uWV6i6YAif?p=preview

**What is the motivation / use case for changing the behavior?**

Being able to test components without having to add `autoDetectChanges`

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all  ] 
- **Language:** [all]

**Comment by kidshenlong** [comment]
I've just run into this myself! Took me a while to find this issue unfortunately. I wonder what's causing this...

**Comment by vikerman** [comment]
Forms initialize asynchronously. If you are doing this without autoDetectChanges you would need to do

```js
it("create controls automatically", (done) => {

    let fixture = TestBed.createComponent(WelcomeComponent);
    fixture.detectChanges(); // This will do the initial binding that will become stable after the 
                             // whenStable resolves below.
    fixture.whenStable().then(() => {
      fixture.detectChanges();
      let form = fixture.componentInstance.ngForm.form;
      expect(form.get('title').valid).toBeFalsy() //Cannot read property 'valid' of null
      done();
    })
  })
```

If you are doing it with autoDetectChanges, it will look like

```js
fit("create controls automatically", (done) => {

    let fixture = TestBed.createComponent(WelcomeComponent);
    fixture.autoDetectChanges();
    fixture.whenStable().then(() => {
      // fixture.detectChanges();  --> This is no longer needed
      let form = fixture.componentInstance.ngForm.form;
      expect(form.get('title').valid).toBeFalsy() //Cannot read property 'valid' of null
      done();
    })
  })
```

We didn't want to make autoDetectChanges the default because we felt developers might want to control precisely in their unit tests when they want to run change detection, and maybe assert something even before the initial detectChanges is run.
