### ISSUE TITLE
Angular 2 rlc5 with angular-cli errors while ng serve

### ISSUE THREAD

**Issue by akashgill1687** [angular/angular#11017]
**I'm submitting a ...**  (check one with "x")
```
ERROR in [default] sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:51:25
Cannot find name 'DateConstructor'.

ERROR in [default] sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:56:51
Cannot find name 'String'.
sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:59:54
Cannot find name 'Object'.

ERROR in [default] sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:63:49
Cannot find name 'Date'.

ERROR in [default] sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:67:58
Cannot find name 'Map'.

ERROR in [default] sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:72:36
Cannot find name 'RegExp'.

```

**Current behavior**
i am able to generate ngfactory.ts files but while doing ng  serve i get these errors
I am not sure i might be missing something

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kara** [comment]
This seems related to the angular-cli project, so please file this at the angular/angular-cli repo.
