### ISSUE TITLE
In @NgModule , how to open different component due to something like user type?

### ISSUE THREAD

**Issue by jjlgjkkl** [angular/angular#11029]
In @NgModule , how to open different component due to something like user type?

I have a NgModule ,  have two different pages, and I want to open different page due to the user type
@NgModule({
  imports: [ SharedModule ,RouterModule.forChild([
            { path: 'edit', component: EditComponent },
			{ path: 'view', component: ViewComponent }
        ])],
   
  declarations: [
    EditComponent, ViewComponent
  ],
 
})
export default  class MainModule { 
  constructor(private u:UserService){
  
  } 
}

the environment is :   RC5

Thanks!

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
