### ISSUE TITLE
Investigate `ECONNREFUSED` issues on Travis CI

### ISSUE THREAD

**Issue by juliemr** [angular/angular#1102]
These have been coming up a lot recently. It's the type of error that happens when the selenium standalone server shuts down in the middle of a run of tests.

Todo
 - [x] Update to Protractor 2.0 to get selenium standalone v 2.45 and see if that helps
 - [x] Start capturing selenium standalone server logs

**Comment by juliemr** [comment]
Here is some output with selenium logs captured: https://travis-ci.org/angular/angular/jobs/55901774

The relevant section before failure is:

```
04:28:11.177 INFO - Executing: [execute script: 1+1, []])
04:28:11.180 INFO - Done: [execute script: 1+1, []]
04:28:11.189 INFO - Executing: [fetching logs for: performance])
04:28:12.865 INFO - Done: [fetching logs for: performance]
Selenium Standalone has exited with code null
          33485.26 |              77.59 |               0.00 |            1159.35 |              24.19 |            1236.94
================== | ================== | ================== | ================== | ================== | ==================
      33485.26+-0% |          77.59+-0% |         0.00+-NaN% |        1159.35+-0% |          24.19+-0% |        1236.94+-0%
F
```

**Comment by juliemr** [comment]
This always happens on the `ng1.tree` benchmark.

**Comment by juliemr** [comment]
OK, switching from Dartium to Chromium _seems_ to resolve the issue. I'm running again to get a little more data.

**Comment by juliemr** [comment]
See https://github.com/angular/angular/pull/1129 for a potential workaround, by forcing performance tests to use a fresh instance of the browser whenever they run.

**Comment by juliemr** [comment]
The workaround commit is merged; hopefully this should be solved for the moment.

I'd like to leave this issue open since we still don't know what actually causes the problem. Tobias and I suspect some kind of memory issue having to do with fetching lots of massive performance logs.

**Comment by mhevery** [comment]
Can it be closed?

**Comment by IgorMinar** [comment]
ping?

**Comment by juliemr** [comment]
No updates from me here. Haven't seen this again, and also haven't had time to take a look at fixes for the root massive logs problem. 

Should this go in the cleanup milestone?

**Comment by IgorMinar** [comment]
I'd close this and reopen if it shows up again.
