### ISSUE TITLE
feature request: rendering nested component in a root(or any other parent) component 

### ISSUE THREAD

**Issue by fxck** [angular/angular#11020]
**What I want**
I have a `<modal-cmp>` component, it's inside a `template` of a component, which is inside couple of other components, so it looks kinda like this...

```
body > app-cmp(app entry point) > list-route-cmp > detail-route-cmp > modal-cmp(my component)
```

...and I would like `<modal-cmp>` to be placed in `app-cmp`(or body, if it's even possible) instead of `detail-route-cmp`, while still being able to pass in data from `detail-route-cmp`'s class, and handle emitted events in the same class.

The goal is to have a nice stateless modal component that doesn't have any [ug](https://github.com/angular/material2/blob/master/src/demo-app/dialog/dialog-demo.ts#L24)[ly](https://github.com/shlomiassaf/angular2-modal/blob/master/src/demo/app/home/home.ts#L22) API.

**Why do I want it**
Simply because of how css and html layers and rendering works. If I wanted my `modal-cmp` to be absolutely position, and any of the the parent components would have position set to `relative`, I would be screwed. Or if any of the parent components had `transform` on it, and I wanted my modal to be `fixed` I would again be screwed(https://github.com/angular/material2/issues/998).

**Existing solutions**
There are none. Material2's portal looks like it could do something like this, but a) that project is abandoned b) it can't quite achieve what I want(https://github.com/angular/material2/issues/1106)

- I want the experience to be as seamless for the end user as possible, I don't want him to be doing any querying shenanigans portal requires(https://gitter.im/angular/material2?at=57bca2845ffbca3e3c07cb22)
- I don't want to have to define a new host element for each of the `modal-cmp`s, I want them all to be appended to the same "host"
- instead of of providing the "host" with what to render, I want to provide the "portal" with where to render 

**How I imagine it would work**
Now, I'm not sure what the possibilities are, but I imagine it could work as a structural directive, something like 

```
<modal-cmp *parent></modal-cmp>
```

and by default it would be **appended** to the root component, or you could pass a ref to a parent component you'd want to append it to(not sure how you could get that ref, but I'm mainly interested in appending it to the root anyway).

cc @pkozlowski-opensource

**Comment by zoechi** [comment]
Might be related to #9293

**Comment by fxck** [comment]
Might be. The main difference is that everyone seems to be going with a service that dynamically loads the actual modal, opening it by calling `.open()` or whatever. I'm on the other hand perfectly fine with the component sitting in DOM, I just want it to sit on the root instead of the component I actually put it in.

**Comment by vicb** [comment]
If this is a real issue please fill out the template. thanks.

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by fxck** [comment]
@vicb it's the most definitely not a support request. And the template is bloated(for feature requests anyway), but ok, there you go.


**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Component is rendered inside a component you put it in.

**Expected/desired behavior**
I would like to be able to somehow tell it in which component to render(appended or prepended) instead. For example in the root component.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Check this http://jsbin.com/teqiseb/2/edit?html,css,output imagine `.wrapper` to be my root component, `.transformed` to be any child component with css `transform` and `.fixed` to be some component I want to have `position: fixed;` because of that `transform` on the component above, it's not gonna work. 

If there was a structural directive, or something I'd put in the decorator, that would tell my fixed component to render inside `.wrapper` instead of `.transformed`, I'd be fine.

This had got multiple uses, not only for fixed elements, but for components like modal windows etc. If I wantrd to create an angular2 of https://developer.mozilla.org/en/docs/Web/HTML/Element/dialog (that is component you put *anywhere* inside any nested component) I'd be again screwed by `position`ing of any parent component.


**What is the expected behavior?**



**What is the motivation / use case for changing the behavior?**
Simply because of how css and html layers and rendering works. If I wanted my modal-cmp to be absolutely position, and any of the the parent components would have position set to relative, I would be screwed. Or if any of the parent components had transform on it, and I wanted my modal to be fixed I would again be screwed(angular/material2#998).

See the first comment https://github.com/angular/angular/issues/11020#issue-172803879


**Please tell us about your environment:**

* **Angular version:** any above 2.0.0-rc.4
 
* **Browser:** all 
 
* **Language:** all
