### ISSUE TITLE
RC4 - Expression has changed after it was checked

### ISSUE THREAD

**Issue by Miloune** [angular/angular#11037]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Get an exception "Expression has changed after it was checked"

**Expected/desired behavior**
No exception

**Reproduction of the problem**
http://plnkr.co/edit/9ARgrZ0IDbSQYiJcyKym?p=preview
If you change the page to 2 or more and search an item (like 'item 2', you will get this error.
This is not an issue related to ng2-pagination cuz if you change the angular version to RC1 (in config.js), this error don't happen.

nb: this problem doesn't occur if you search in page 1;

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome 52] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by ericmartinezr** [comment]
> This is not an issue related to ng2-pagination cuz if you change the angular version to RC1 (in config.js), this error don't happen.

That sounds to that the lib hasn't been updated to be compatible with latest RC. This should be opened in the lib repo. You can also look for the error message in thia repo, there are a lot of issues about it.

**Comment by kara** [comment]
As @ericmartinezr mentioned, third-party library issues should be opened in their repos rather than here. Closing, but feel free to open an issue if you can reproduce an Angular bug without ng2-pagination.
