### ISSUE TITLE
ViewChildren and ViewChild are searching for child / children only

### ISSUE THREAD

**Issue by AlmogShaul** [angular/angular#11039]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ViewChildren and ViewChild are searching for child / children only,

**Expected/desired behavior**
They should search for descendents also.

**Reproduction of the problem**
steps for reproduce:
Lets say you have component1 that declare component2 inside of it, 
and component2 declare component3 inside of itself.
component1 can't use ViewChildren to get component3.

**What is the expected behavior?**
I would expect component1 to find component3 

**What is the motivation / use case for changing the behavior?**
I want to find descendents of specific type and not only children

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome 52] 
 
* **Language:** [ TypeScript 1.8]

**Comment by michaelchiche** [comment]
@ViewChildren(ExampleComponent, {descendants: true}) examples: QueryList<ExampleComponent>;

**Comment by AlmogShaul** [comment]
@michaelchiche 
The interface is:

export interface ViewChildrenMetadataFactory {
  (selector: Type<any>|Function|string, {read}?: {read?: any}): any;
  new (selector: Type<any>|Function|string, {read}?: {read?: any}): ViewChildrenMetadata;
}

**Comment by michaelchiche** [comment]
got confused with contentchildren.
Well instead of doig that, since its a viewChild(ren).
You can create a set component2 as a viewchild of component1.
And then component3 as a viewchild of component2 so that now you can access the viewchild from component1 throught component2

**Comment by AlmogShaul** [comment]
@michaelchiche 
Is there a reason not to support it? maybe I would open  a pull request for it?

**Comment by AlmogShaul** [comment]
export class ViewChildrenMetadata extends ViewQueryMetadata {
  constructor(_selector: Type<any>|string, {read = null}: {read?: any} = {}) {
    super(_selector, {descendants: true, read: read});
  }
  toString(): string { return `@ViewChildren(${stringify(this.selector)})`; }
}
I see that it passes its super {descendants: true, read: read}
so it should work.
It doesn't 
maybe the descendants parameter is for something else?

**Comment by ericmartinezr** [comment]
Probably related (note the "probably") https://github.com/angular/angular/issues/5241#issuecomment-156841935

**Comment by AlmogShaul** [comment]
It is the same issue.
Although I think we should have some mechanism to query all components of specific type.

**Comment by vicb** [comment]
duplicate

**Comment by geoff-mci** [comment]
This issue was for @ViewChildren, the linked issue was for @ContentChildren resolution of the linked issue was:
@ContentChildren(..., {descendants: true})
can we also use:
@ViewChildren(..., {descendants: true})
?

(my use case is to find all the elements that have a 'scroll-on-click' directive on them so I can auto scroll the form to ensure focussed fields are not obscured)

**Comment by bibhas2** [comment]
What is this duplicate of? Google search on this topic shows this issue only.
