### ISSUE TITLE
ComponentFactoryResolver - No component factory found for "MyComponent"

### ISSUE THREAD

**Issue by ssmartin** [angular/angular#11030]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We used the DynamicComponentLoader in order to create components dynamically based on their Type. We also needed to provide specific list of Provider for our component. All this worked like a charm. 
We have a (list) of pagePanel components that have this template:

```
 template: `
        <div role="pagepanel" class="page-pane" [ngClass]="{active: pageHandler.active}">
            <div #container></div>
        </div>
    `
....

  @ViewChild('container', { read: ViewContainerRef })
    container: ViewContainerRef;
```
And we were doing something like this:
```
this._dynaCompLoader.loadNextToLocation(
            this.pageHandler.descriptor.componentType,
            this.container,
            resolvedProviders).then((componentRef: ComponentRef<any>) => {
                this.pageHandler.initialize(componentRef);
            });

```

Then the dcl was deprecrated and I moved to the ComponentResolver. Our code became:

```
this._componentResolver.resolveComponent(this.pageHandler.descriptor.componentType)
            .then((factory: ComponentFactory<any>) => {
                let componentRef: ComponentRef<any> = this.container.createComponent(factory, 0,       this._childInjector);
                this.pageHandler.initialize(componentRef);
            });
```
So far so good. Now with the new ComponentFactoryResolver I tried to migrate by doing something like this:

```
    let factory: ComponentFactory<any> = this._componentFactoryResolver.resolveComponentFactory(this.pageHandler.descriptor.componentType);
        let componentRef: ComponentRef<any> = this.container.createComponent(factory, 0, this._childInjector);
        this.pageHandler.initialize(componentRef);

```
But now I get an exception -  _No component factory found for "MyComponent"_.  
So I read a bit more about it and surprise: seems that in order for this to work I HAVE to declare the component I want to dynamically create in the _entryComponents_ section of my module. 
Like this it works indeed, but **I consider this a regression because it kind of beats the purpose of being able to create components dynamically, without having to declare them in advance** -> the whole idea in our app was to be able to create these components just based on some metadata (including their TYPE). Because most of them are created like this and it would be really bad /hardfor me to add all of them to the _entryComponents_ section. 
I understand that I might be able to use the Compiler instead but then no chance to do AOT in production.

**Expected/desired behavior**

I would really like to be able to use the ComponentFactoryResolver similar to the ComponentResolver **without** having to declare all my components in the _entryComponents_ section. The goal is to still be able to use AoT in the future.

**Reproduction of the problem**

Check this plunker (removing the _entryComponents_ will break it) - http://plnkr.co/edit/P0spNzu8JbQad2aKACsX?p=preview. 

**What is the expected behavior?**

To have a way to dynamically create components similar to how the DynamicComponentLoader was working (e.g. without having to declare the list of the components). Ideally to still be able to use AoT but I think this might be tricky/problematic.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript  ]

**Comment by ssmartin** [comment]
I got it working with the compiler but then no way to do AoT in the future, right?

```
   this._compiler.compileComponentAsync(<any>this.pageHandler.descriptor.componentType).then(
            (factory: ComponentFactory<any>) => {
                let componentRef: ComponentRef<any> = this.container.createComponent(factory, 0, this._childInjector);
                this.pageHandler.initialize(componentRef);
            }
        );
```

**Comment by mlc-mlapis** [comment]
If you count that there will not be a compiler on a browser side then who will compile a cmp? That is the reason why entryComponents exists and AoT uses it to find out what should compile and what include to a module. When the module is loaded (directly or as lazy loaded) those compiled cmps are loaded also and you can manipulate with them dynamically. In other case you need A2 compiler in a browser and compile cmps on demand. But A2 compiler is the biggest part of A2 - nearly 60% of code.

**Comment by ssmartin** [comment]
Yes, meanwhile I kind of realized that AoT is the motivation behind the current changes (there was not AoT compilation before RC5). 
Unfortunately it seems that in our app there is no good way to use AoT considering the dynamic creation of components is currently one of the core/main features in our app. Maybe one way would be to split our app in more modules and declare in each module's _entryComponents_  the components that will be loaded dynamically. But because we don't use the router (and we don't want to compile modules dynamically with the compiler) this would mean loading all these modules at bootstrap...

**Comment by mlc-mlapis** [comment]
You described the situation exactly. The main A2 idea of all is to modularize an app to modules and you can choose then if you want to lazy load them or as one bundle.

**Comment by ssmartin** [comment]
Thank you. All clear for now. 
I guess the feature request does not make too much sense so I will close this.

**Comment by SadamChami** [comment]
I get the same error when i am pushing from one page to another.

`this.navCtrl.push( Page7 );`

I have added the Page7 to app.module.ts.

`import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';

import { Page1 } from '../pages/page1/page1';
import { Page2 } from '../pages/page2/page2';
import { Page3 } from '../pages/page3/page3';
import { Page4 } from '../pages/page4/page4';
import { Page5 } from '../pages/page5/page5';
import { Page6 } from '../pages/page6/page6';
import { Page7 } from '../pages/page7/page7';

@NgModule({
  declarations: [
    MyApp,
    Page1,
    Page2,
    Page3,
    Page4,
    Page5,
    Page6,
    Page7
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    Page1,
    Page2,
    Page3,
    Page4,
    Page5,
    Page6,
    Page7
  ],
  providers: []
})

export class AppModule {}`

This is a ionic 2 Application. It Gives this error.

`EXCEPTION: Error in ./Page6 class Page6 - inline template:21:56 caused by: No component factory found for Page7`

<img width="569" alt="screen shot 2016-10-05 at 3 38 30 pm" src="https://cloud.githubusercontent.com/assets/5139138/19109164/cf86541c-8b11-11e6-826f-94d724e022d5.png">

**Comment by mlc-mlapis** [comment]
But the error is from the inline template at Page6. You did not append it.

**Comment by lwu** [comment]
@SadamChami can you post a gist or https://plnkr.co/ ? I got the same "No component factory" trying to add a new page but was able to solve it by adding it to the app.module.ts as you did so not sure why it's not working.

**Comment by omar-faruk-sust** [comment]
hey @SadamChami , did you solve this problem? i am facing same problem. when i push another page. Can anybody help ? i am pretty new to angular and ionic.

**Comment by mlc-mlapis** [comment]
Try to separate the main problem first -> do not mix A2 & Ionic -> create a working Plunk (pimplest as possible) -> finding a problem by others without just guessing.

**Comment by omar-faruk-sust** [comment]
hey @mlc-mlapis , have you seen what i mentioned? i have told i am getting exact same error like as  @SadamChami getting. Error is not guess. He is also using a2 and ionic.

**Comment by mlc-mlapis** [comment]
Hi, yes I know but ... you do not have a solution - you do not know why it happens. So I tried to simplify the way how to find an answer if anyone wants to help icluding me and there are so many things that could influence.

**Comment by SadamChami** [comment]
I fond the solution. You have to add the page that where you are pushing to in to the parent directory. That should also be included in to the @NgModule also.

`@Component({
  selector: 'page-page6',
  templateUrl: 'page6.html',
  providers: [ ApiServices ],
  entryComponents:[ Page7 ]
})`

**Comment by mlc-mlapis** [comment]
Hmm, maybe this works but there still should be something wrong. Normally filling entryComponents property in @NgModule should be enough.

And what about when you want to switch to Page5 from Page6? You need something like:
```
@Component({ selector: 'page-page6', templateUrl: 'page6.html', providers: [ ApiServices ], entryComponents:[ Page5, Page7 ] })
```

**Comment by SadamChami** [comment]
Yes. I still don't know why is that. I agree with you that only @NgModule is the needed one. But ionic 2 worked when i do this also.

**Comment by mlc-mlapis** [comment]
That is why a plunk demo would be helpful. There could be something what you do not see and what could be just evident for me. Like case sensitive names in JavaScript - I had already a case where that was the only source of problems.

**Comment by leafdropco** [comment]
I am facing this same issue, I am using the tabs example.

Error I get is:
**error_handler.js:47 EXCEPTION: Error in ./HomePage class HomePage - inline template:8:48 caused by: No component factory found for PostDetails**

```
import { Component } from '@angular/core';
import {PostDetails} from '../post-details/post-details';
import { NavController, NavParams } from 'ionic-angular';
import {Http} from '@angular/http';
import 'rxjs/add/operator/map';

@Component({
  templateUrl: 'home.html',
})
export class HomePage {
	url: string = 'http://www.leafdrop.co/wp-json/wp/v2/posts';
	items: any;

	constructor( public navCtrl: NavController, private http: Http, private nav: NavController ) {}

	ionViewDidEnter() {
		this.http.get( this.url )
	    .map(res => res.json())
	    .subscribe(data => {
	      // we've got back the raw data, now generate the core schedule data
	      // and save the data for later reference
	      this.items = data;
	    });
	}

  itemTapped(event, item) {
		this.nav.push(PostDetails, {
		  item: item
		});
	}
}
```

**Comment by lwu** [comment]
@leafdropco did you open app.module.ts and import { PostDetails } from /* the_location */; and also add it under declarations[] and entryComponents[]?

**Comment by leafdropco** [comment]
@lwu That did it, thank you!

**Comment by omar-faruk-sust** [comment]
hi @SadamChami , i did not follow your solution. Can you tell me what i need to add exactly where? In my home page there is a button and if i click that button i want to go Signup Page. In my above comment i have shown my home.ts code . 
```
import { Component } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';

/*
  Generated class for the Signup page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Component({
  selector: 'page-signup',
  templateUrl: '../signup/signup.html'
})

export class SignupPage {
  public firstParam:any;
  public secondParam:any;

  constructor(public navCtrl: NavController,  public params: NavParams) {
    this.firstParam = params.get("firstPassed");
    this.secondParam = params.get("secondPassed");
  }

}
```

**Comment by SadamChami** [comment]
@omar-faruk-sust in you component, Add like this.

```
@Component({
  selector: 'page-signup',
  templateUrl: '../signup/signup.html,
  entryComponents:[ SignupPage ]
})
```

**Comment by Abhiramkadiri** [comment]
@lwu It did Work

Thanks

**Comment by ashwinirajput** [comment]
Not Working Can Any one provide plunker which is working I am on the same problem

**Comment by Abhiramkadiri** [comment]
Now it's working

We need to add the class name in app.component

**Comment by mlc-mlapis** [comment]
It is a bit misleading conversation. Work, does not work, work, ... and all without any concrete code that could be reviewed.

**Comment by Abhiramkadiri** [comment]
See lapis

I think u R not aware that ionic 2 is in beta so there are lot of changes
going on


So daily there are lot of changes which might work other day or they may
deprecate

Hope you understood

**Comment by ashwinirajput** [comment]
@Abhiramkadiri can you provide any plunker its totly confusing due to more update

**Comment by Abhiramkadiri** [comment]
@ashwinirajput 

I don't have Any active plunker right now.

But I can Explain it right here .

Explanation about the error **" ComponentFactoryResolver - No component factory found for "MyComponent" #11030 "**

After Creating Your page (say myclass) a class will be generated like "export **myclasspage**"

You have to declare the myclasspage class in two files that are **1."app.component.ts"** **2."app.module.ts"**
 very very important

**1.You should declare in app.component.ts like this "import {myclasspage} from '../pages/myclasspage/myclasspage**"';

**1.You should declare in app.module.ts like this "import {myclasspage} from '../pages/myclasspage/myclasspage**"'; and remeber that in **"app.module.ts"** you should also declare in another place  as below

@NgModule({
  declarations: [
    MyApp,
**myclasspage**
    AboutPage,
    ItemDetailsPage,
    ListPage,
    AddingnewionicPage,
    NavgridPage,
    QuizPage,
    MappagePage,
    GalleryPage,
    glocationPage,
    MapPage,
    PhotodisplayPage,
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
**myclasspage**
    AboutPage,
    ItemDetailsPage,
    ListPage,
    AddingnewionicPage,
    NavgridPage,
    QuizPage,
    MappagePage,
    GalleryPage,
    glocationPage,
    MapPage,
    PhotodisplayPage,
  ],

In case If you have any provider it should be declared here as providers: [ConnectivityService,LocationTracker,**myclass2provider** (say)]



And thats it the error will be resolved.


Hope this explanatio helps.

Happy coding.

**Comment by SadamChami** [comment]
Update to latest. Error is fixed in that.

**Comment by teddywest32** [comment]
I am having the same problem with my components:
```
No component factory found for AttributeFormComponent,AttributeSettingsComponent,AttributeTimelineComponent. Did you add it to @NgModule.entryComponents?
```

I have these components in different module so i have added in that module.
```
@NgModule({
    declarations : [
         AttributeFormComponent,
        AttributeSettingsComponent,
        AttributeTimelineComponent
    ],
    entryComponents: [
        AttributeFormComponent,
        AttributeSettingsComponent,
        AttributeTimelineComponent
    ],
    exports      : []
})
export class CustomModule {}
```

But still it is giving me the error of `No component factory found.`

**Comment by mlc-mlapis** [comment]
What means the sentence:
> I have these components in different module so i have added in that module.
Does it mean that AttributeFormComponent, AttributeSettingsComponent, AttributeTimelineComponent are declared in different modules?

So why you then re-declare them in CustomModule instead of "imports" that module where they are declared in CustomModule ?

**Comment by teddywest32** [comment]
@mlc-mlapis I have declared those components in `CustomModule `  and as i saw those posts above where they were saying we need to declare `entryComponents` in `AppModule`. So,  i was trying to clear the case where i was using it in `CustomModule` and not on `AppModule`. 

Also it is only declared once, and thanks for the comment.
