### ISSUE TITLE
Cannot inject @Host form group in a custom component two levels below

### ISSUE THREAD

**Issue by BrainCrumbz** [angular/angular#11031]
**I'm submitting a ...**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior**

Have a reactive form in top level *AppComponent*, add a *CustomComponent* within form, then in turn add a *NestedComponent* within the Custom one. Both *CustomComponent* and *NestedComponent* require the hosting form group to be injected as dependency (as opposed to being passed manually as input).

Console reports template parsing error just next to nested component:

```
Unhandled Promise rejection: Template parse errors:
No provider for FormGroupDirective ("p>Custom begin </p>
      <p>Host contains {{hostFormGroup.directives.length}} directives</p>
      [ERROR ->]<nested></nested>
      <p>Custom end </p>
    </div>
"): CustomComponent@4:6 ; Zone: <root> ; Task: Promise.then ; Value:
```

When adding provider to nested component, error disappears, but injected form group is not the actual hosting one, it's just a newed up form group instance. 
When adding provider to custom component or app component, error remains.
At same time, there's no error for the first-level custom component, which gets the actual hosting form group injected fine. 

**Expected/desired behavior**

Nested component should receive the hosting form group as a dependency, just like the first-level component. Passing that manually as a `@Input` should neither be required.

**Reproduction of the problem**
[Here's](http://plnkr.co/edit/0jZZkD?p=preview) a plunker illustrating the scenario. 

**NOTE**: At the moment the nested component has the provider added, so no error shows, but you can see that injected form group is not the host: it contains no directive. If you comment the line `providers: [FormGroupDirective],` in `NestedComponent`, the error shows in console.

[Here's](http://stackoverflow.com/questions/39104592/no-provider-for-formgroupdirective-in-angular-2-nested-custom-component) the same issue on stackoverflow.

**What is the expected behavior?**
See **Expected/desired behavior**

**What is the motivation / use case for changing the behavior?**
Fixing error. Allow to inject hosting form group.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by jimitndiaye** [comment]
Remove the @Host() decorators and it works.

**Comment by BrainCrumbz** [comment]
Well, thanks! Has `@Host()` been deprecated or has something changed? In case, do you know where to find more info on this? With my team I could not find any, `@Host()` reference doc is still there, and as far as I remember that was the way to access outer container.

BTW please feel free to answer on StackOverflow, to get right credits for that.
