### ISSUE TITLE
http have to read custom error message returned from backend

### ISSUE THREAD

**Issue by almothafar** [angular/angular#11033]
**I'm submitting a ...**  (check one with "x")

```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When the backend return custom error message and response type is text, the message is ignored and no way to read what backend says.
When I send a json body it can be inside `response._body` but not for text message.

**Expected/desired behavior**
I expect to get the text of response exactly as what it work in success response, and as what it was in angularjs (angular 1), when the content-type is "text/plain".

**Reproduction of the problem**

```
this._http.post(apiUrl.concat('/login'), {email: email,password: password})
     .toPromise().then((response: Response) => {
          console.log('Hello ! ', response);
     }).catch(function (response) {
          console.log('Failed ! ', response);
     });

```

response here is: 

```
{"_body":{},"status":401,"ok":false,"statusText":"Unauthorized","headers":{"null":["HTTP/1.1 401 Unauthorized"],"Access-Control-Allow-Headers":["Origin"," X-Requested-With"," Content-Type"," Accept"," Referer"," User-Agent"],"Access-Control-Allow-Met
hods":["POST"," GET"," PUT"," DELETE"," OPTIONS"],"Access-Control-Allow-Origin":["*"],"Allow":["*"],"Content-Length":["36"],"Content-Type":["text/plain; charset=utf-8"],"Date":["Tue"," 23 Aug 2016 14:53:25 GMT"]},"type":2,"url":null}
```

You an see this too: http://stackoverflow.com/questions/39104715/angular-2-how-to-read-custom-error-message-from-backend

**Plunker**: http://plnkr.co/edit/TlvUNJBJxE3thGr38pAx?p=preview

**What is the expected behavior?**

Get the error message (I returned a message from backend : "Please check your email and password" ) as a response from backend when backend send error and response content type is "text/plain"
I think the code here: https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/xhr_backend.ts#L95

need to be changed, something like: 

```
var responseOptions = new ResponseOptions({
          body: body || err,
          type: ResponseType.Error,
          status: _xhr.status,
          statusText: _xhr.statusText,
        });
```

or what ever can fix this issue.

**What is the motivation / use case for changing the behavior?**
I return a messages from backend when user login, that User entered "invalid username or password", or "user is inactive", but no way to read that.

Another real example, if I use stripe in my backend I validate the credit card, the error message return from stripe that credit card is invalid, or expired or blocked, ... etc, I need to pass that message to user.

Also, in old AngularJS it was working, no need to do big refactor for backend or this will break old applications as well.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [all ] - NativeScript to be exact.
- **Language:** [TypeScript 1.8.10]

**Comment by vicb** [comment]
Please update to the latest RC and create a plunker to show the issue.

**Comment by almothafar** [comment]
Hi @vicb 

This is a plnkr : http://plnkr.co/edit/TlvUNJBJxE3thGr38pAx?p=preview 

Please note that i'm using NativeScript, if I updated the ANgular to RC5 my app wont work and i'm getting tons of errors with routers and modules inside NativScript, but for http here i'm trying to use only Angular2 http.

**Comment by DzmitryShylovich** [comment]
Is this still relevant after final?

**Comment by almothafar** [comment]
@DzmitryShylovich this is the updated plnker : http://plnkr.co/edit/5wfVzsh1eICShfWjP779?p=preview 
But not sure 100% is this means still not working or I need to try in local project.

**Comment by DzmitryShylovich** [comment]
@almothafar have u tried locally?

**Comment by almothafar** [comment]
@DzmitryShylovich not yet, currently working in 1.5 things not got chance to try it, I'll try by tomorrow or after.

**Comment by almothafar** [comment]
@DzmitryShylovich I waste 1 paid hour of my time trying to get it work without luck, I'm facing stupid CORS issue here and I got really anger from this junk, I allowed everything from my server side, and IT IS WORKING IN ANGULAR 1.

If you can provide me with starter working with this issue I'll be thankful, otherwise I'm not going to waste more time until I work in Angular 2 again later, specially I'm already late on my task.

**Comment by DzmitryShylovich** [comment]
> I'm not going to waste more time until I work in Angular 2

and no repro. close this one? @pkozlowski-opensource

**Comment by DeonBonthuys** [comment]
I updated to latest version today (from 4.0.0) in order to make use of the HttpInterceptor, changed all my code from Http to HttpClient and upon testing my changes, the issue mentioned here is the 1st problem i noticed. 

When server side validation prevents an action from being executed, i send a string message in the body of the response. The previous implementation of my code i used (error: Response) => error.text('legacy') and this contained the validation message in question.

With 4.3 implementation i debugged and inspected every inch of the response and the body assigned to the error HttpErrorResponse is null. My custom response sent from the server is nowhere to be found.

**Comment by owlstack** [comment]
@almothafar Were you able to fix this issue? How did you solve it?
