### ISSUE TITLE
Angular 2 runtime error messages are not helpful for external developers

### ISSUE THREAD

**Issue by org4582** [angular/angular#11036]
[X ] feature request

**Current behavior**
React's error messages tell me what is wrong with my code, Angular 2's error messages tell me what is wrong in Angular's code.

If you fixed angular 2's error messages, to point developers to issues in their own code instead of pointing them to where things went wrong in the angular framework, that would change the world for developers of this great platform.

**Reproduction of the problem**
Create any issue in angular2 such as including dependencies that have issues. You will see a stack trace in the console that is completely the Angular2 stack until you get to the bottom line which will point to main.js. These issues are not in main.js they are in other components being referenced in main.js (which is just the entry point). 

The angular-cli's `ng build` has helpful error messages, this is a good example of expected behavior. Runtime errors are what I describing here.

**What is the expected behavior?**
The root cause of the issue should be displayed in the console.

**What is the motivation / use case for changing the behavior?**
I have a team of developers I want to begin using angular 2 after RTM and I see these stack traces as being a major hurdle to their productivity.

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome LASTEST] 
 
* **Language:** [TypeScript 2.0]

**Comment by vicb** [comment]
We have plan to improve error messages.
If you have any specific issue in mind please create a new ticket.
