### ISSUE TITLE
Trigger Modal using Routing 

### ISSUE THREAD

**Issue by calvinKG** [angular/angular#11038]
Hi, 

Am having this issue, I don't know if its a bug or a feature that need to the add to Angular 2 Routing. 

Am trying to trigger a modal using Routing, am on RC 4. My application those navigate to correct routing but my Modal those not appear only the background. 
Error: 

![image](https://cloud.githubusercontent.com/assets/1926014/17932068/9b6a420c-6a0e-11e6-8d3e-cb7178c8d683.png)

Code: 

**ua-add-function.component**

```
`import {Component, ViewChild} from "@angular/core";
import {MODAL_DIRECTIVES, BS_VIEW_PROVIDERS} from 'ng2-bootstrap/ng2-bootstrap';
import {Router} from "@angular/router";

@Component({
    selector: 'ua-add-function',
    templateUrl: 'src/app/pages/user-auth/components/function-admin/add/ua-add-function.html',
    directives: [MODAL_DIRECTIVES],
    viewProviders: [BS_VIEW_PROVIDERS],
    exportAs: 'child'
})

export class Add_function
{

    @ViewChild('lgModal') lgModal;

    constructor(private router: Router){}

    show(){
        this.router.navigate(['/fleet/user-auth/ua-functional-admin/add-function']);

        this.lgModal.show();
    }

}`
```

**ua-add-function.component.html**

`<div bsModal #lgModal="bs-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" [config]="{'backdrop':'static', 'keyboard': false}">
    <div class="modal-dialog modal-lg">
        <div class="modal-content" >
            <div class="modal-header modal-wrap">
                <button type="button" class="close" (click)="lgModal.hide()" aria-label="Close">
                   
                </button>
                <h4 class="modal-title">Add Function</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <label class="control-label ">System</label>
                        <input type="text" class="form-control" placeholder="System">
                    </div>

                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <label class="control-label ">Function Name</label>
                        <input type="text" class="form-control" placeholder="Function Name">
                    </div>

                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <label class="control-label ">Function description</label>
                        <input type="text" class="form-control" placeholder="Function description">
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <label class="control-label ">Function Prefix </label>
                        <input type="text" class="form-control" placeholder="Job Role Name">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button"  class="btn fnb-submit-btn " data-dismiss="modal">Submit</button>
                <button type="button"  class="btn fnb-submit-btn" (click)="lgModal.hide()" aria-label="Close" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>`

**Routing #** 

`export const fleetRoutes: RouterConfig =[

    {
        path: 'fleet',
        component: FleetComponent,
        children: [
            {
                path: 'home',
                component: HomeComponent
            },
            {
                path: 'help',
                component: HelpComponent,

            },
            {
                path: 'help',
                component: HelpComponent,
                children: [
                    { path: 'test',
                        component: TEstComponent
                    }
                ]

            },
            {
                path: 'user-auth',
                component:UAComponent,
                children: [
                    {
                        path:'ua-functional-admin',
                        component: UA_Functional_Admin
                    },

                    {
                        path:'ua-functional-admin',
                        component: UA_Functional_Admin,
                        children: [
                            {
                                path:'add-function',
                                component: Add_function
                            }
                        ]
                    },`

**# Expected output** 

![image](https://cloud.githubusercontent.com/assets/1926014/17932262/73f29bce-6a0f-11e6-9c29-21da1dc84986.png)

**Comment by pkozlowski-opensource** [comment]
You should open this issue in the project from which you've downloaded the modal widgets from. As-is your issue sounds like a support question with nothing indicating that this is bug / missing feature in the angular itself.
