### ISSUE TITLE
TestComponentBuilder.overrideDirective() behaviour change in RC.5 vs. RC.4

### ISSUE THREAD

**Issue by alantreadway** [angular/angular#11032]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In a non-trivial component hierarchy, I'm testing the root component X with children A and B, and trying to mock/stub a sub-set of its children (A).

If B has A declared as a directive, and I use `TestComponentBuilder.overrideDirective()` to use a mock/stub implementation of A for X, I'm told that the template for X has parsing errors since there are two implementations of A to choose from.

```
Error: Uncaught (in promise): Template parse errors:
More than one component: MockChildComponentA,ChildComponentA ("
    [ERROR ->]<yld-child-component-a [someText]="someTextForChild">
    </yld-child-component-a>
    <yld-child-com"): MainComponent@1:4
```

**Expected/desired behavior**
A is mocked for use by X, B uses the real implementation of A, and there are no template parse errors.

**Reproduction of the problem**

This Plnkr highlights the issue:
https://embed.plnkr.co/krHmvR4Pe039D0PuBDxN/

In our real project, I also tried switching to using `TestBed`, but ended up with exactly the same error.

**What is the expected behavior?**

Tests pass in the above Plnkr.

**What is the motivation / use case for changing the behavior?**

We should be able to selectively mock dependencies of the component under test, independent of transitive dependencies.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4 (trying to upgrade to rc.5)
 
* **Browser:** Chrome 52
 
* **Language:** Typescript 1.8

**Comment by juliemr** [comment]
As `TestComponentBuilder` is deprecated and gone in master, I'm going to close this as obsolete. 

For `TestBed`, you just need to remove the old declaration of A. See the comments in https://github.com/angular/angular/issues/10689

**Comment by alantreadway** [comment]
I've updated my Plunkr (and tweaked description above) to use only TestBed, and I am still able to recreate the issue - please re-open and advise on expected behaviour.

**Comment by pkozlowski-opensource** [comment]
@alantreadway you should migrate your code to use `@NgModule` - directives on the `@Component` and code that overrides things on a component level is not even in master anymore.

**Comment by alantreadway** [comment]
@pkozlowski-opensource: Thanks for pointing this out - I've updated my example to remove use of `@Component({directive: [...]}`, and the specific error reported is no longer present, however this highlights that **the granularity for scope of overriding has moved from `@Component` scope in RC.4 to `@NgModule` scope**?

Is my understanding correct that if `MainComponent`/X, `ChildComponentA`/A and `ChildComponentB`/B are all in the same module, I can't independently override interdependencies between them?

**Comment by pkozlowski-opensource** [comment]
> Is my understanding correct that if MainComponent/X, ChildComponentA/A and ChildComponentB/B are all in the same module, I can't independently override interdependencies between them?

I would answer YES to the question phrased like this.

**Comment by sistla001** [comment]
I have MainComponent and ChildComponentA as @ViewChild, Main Component is calling the ChildComponentA's Method. 

I want to write an unit test case mocking the ChildComponentA. How can i mock complete ChildComponentA using TestBed (RC-5)?

Before I used to use overrideDirective(MainComponentName, ChildComponentA, MockChildComponentA); Is there an equivalent to this using TestBed?
