### ISSUE TITLE
One Level Up ( ../ ) is not working for [routerLink]

### ISSUE THREAD

**Issue by atalkishore** [angular/angular#11047]
After updating to rc5 route link is not working for one level up

<a [routerLink]="['../6']" routerLinkActive="active">{{Title}}</a>

If url is **www.demo.com/something/5**
The above link redirects to  **www.demo.com/something/5/6**

**Comment by chuckjaz** [comment]
Can you provider a plunker repo?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource I think this can be closed.
