### ISSUE TITLE
Cannot upgrade ng1 component that uses multi-slot transclusion

### ISSUE THREAD

**Issue by battmanz** [angular/angular#11044]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Cannot upgrade an ng1 component that uses multi-slot transclusion. For example, if the ng1 component has the following `transclude` definition

```
transclude: {
  foo: 'myFoo',
  bar: 'myBar'
}
```

then if I try to do `upgradeAdapter.upgradeNg1Component(myComponent)`, two errors will be thrown that say:

```
"TypeError: Cannot read property 'foo' of undefined"
```

and

```
"TypeError: Cannot read property 'bar' of undefined".
```

The component works fine as long as I don't try to upgrade it.

**Expected/desired behavior**
It is expected that ng1 components that use multi-slot transclusion can be upgrade to ng2.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:** all 
- **Language:** TypeScript 1.8.10

**Comment by vicb** [comment]
see https://github.com/angular/angular/pull/9538

**Comment by battmanz** [comment]
Sorry, but it's not immediately apparent to me whether that fixes my issue or not. That issue refers to downgrading ng2 components, but I'm interested in going the other way -- upgrading ng1 components.
