### ISSUE TITLE
Remove i18n tags from compiled angular templates

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#11042]
**I'm submitting a feature request**

Currently when I build an Angular application with internationalization, I add `i18n` attributes to many of my tags. After compilation, it would be nice for these tags to be removed and not included in the rendered site.

**Comment by StephenFluin** [comment]
To clarify, this only happens when running `ngc` without an i18nFile or locale. Without those files, it leaves the attributes on all of my HTML tags.

**Comment by mlaval** [comment]
It means that the `i18n` and `i18n-*` attributes would become reserved keywords, i.e. they would be removed during compilation even if the user is not using the built-in i18n feature, or if he is using them for something else.
Are we sure that this is what we want?

**Comment by ocombe** [comment]
I don't think that's a good idea, those tags can be used as css selectors, or for custom directives. Is there really a problem in keeping them? Angular adds custom attributes all the time (just look at the dom)

**Comment by zbitname** [comment]
I think any css styles don't need to use selector `i18n-*`. I think using `i18n-*` selector for css is bad.

**Comment by jcimoch** [comment]
@jasonaden I think it shouldn't be classified as a bug. This "fix" assumes that nothing is using those attributes which might not be true.  My project had custom dynamic translations solution which was relaying on those attributes in runtime, when they are not available it can't work without some stupid workarounds. I think you should provide compiler flag which by default is set to true and i18n attributes are deleted, but when set to false they will remain in produced build.

**Comment by camueller** [comment]
I fully agree with @jcimoch : Having the attribute at runtime allows to use a different style for translated elements (e.g. a green border). This is useful to identify elements not yet translated.
A compiler switch would be sufficient.
