### ISSUE TITLE
input[type=range] not updating ngModel on IE10

### ISSUE THREAD

**Issue by TheLarkInn** [angular/angular#11041]
**I'm submitting a ...**
- [x] bug report

**Current behavior**
Using input[type=range] is not updating model values for [(ngModel)] bindings. 

**Expected/desired behavior**

**Reproduction of the problem**
![screen shot 2016-08-24 at 10 33 16 am](https://cloud.githubusercontent.com/assets/3408176/17938091/23db65f0-69ea-11e6-8497-6cccaf6e897c.png)

IE 10 is on Left, Chome is on Right.

**What is the expected behavior?**
That the slider models update the same between both browsers. 

**Please tell us about your environment:**
Windows 7 IE 10 (Emulated via Edge)
- **Angular version:** `@latest`
- **Browser:** [ IE <10 ] 
- **Language:** [all | TypeScript latest ] 

If I need to create a plunkr for reproduction I can. It was essentially just changing the slider, and then a  `{{modelValue}}` variable not updating. Let me know if I can help.

**Comment by TheLarkInn** [comment]
It appears like I was able to reproduce this on edge as well. FWIW. So atleast easier to test locally.

**Comment by mootinator** [comment]
Apparently IE doesn't fire input events for range inputs, so the resolution is likely similar to this issue: https://github.com/Polymer/polymer/issues/416

**Comment by cedvdb** [comment]
ie 11 as well

**Comment by DzmitryShylovich** [comment]
is this still an issue? we are listening for both `input` and `change` events https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/range_value_accessor.ts#L32

**Comment by PBartrina** [comment]
I confirm, still an issue

**Comment by DzmitryShylovich** [comment]
could u add a small repro in plunkr?

**Comment by PBartrina** [comment]
Sure, will edit this message

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource no repro. I think this can be closed

**Comment by govindmahecha** [comment]
this link may help you  [https://docs.angularjs.org/guide/ie](https://docs.angularjs.org/guide/ie)

**Comment by atscott** [comment]
Closing as likely obsolete and lacking a repro. 

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
