### ISSUE TITLE
Angular 2 Router can't handle refresh if base href is not / (root) in virtual directory in IIS

### ISSUE THREAD

**Issue by jkyoutsey** [angular/angular#11046]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
```

**Current behavior**
When a site is not hosted at http://localhost/ , but is hosted at http://localhost/SomeVirtualDirectory, then the router gets confused on refresh.  This is when the base href is set to something other than `/`

**Expected/desired behavior**
Router should work correctly hosted in IIS with Url Rewrite correctly configured.  It should work initially and on a refreshed request.

**Reproduction of the problem**
Host your dist folder in IIS in a virtual directory called "SiteA".  This angular 2 app should have routes, i.e. site/dashboard.
Install Url Rewite in IIS.
Configure Url Rewrite with these rules (put web.config with these contents next to index.html):
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <rewrite>
        <rules>
            <rule name="angularjs routes" stopProcessing="true">
                <match url=".*" />
                <conditions logicalGrouping="MatchAll">
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                </conditions>
                <action type="Rewrite" url="/" />
            </rule>
        </rules>
    </rewrite>
  </system.webServer>
</configuration>
```
Change index.html to set base href `<base href="/SiteA/">`
Browse to http://localhost/SiteA.
See that the site comes up correctly at the default route, say, localhost/SiteA/site/dashboard.
Click refresh in the browser.
See that it is redirected to the IIS home page.

**What is the expected behavior?**
Angular 2 and IIS should work together.  Angular should be able to route appropriately inside of IIS in something other than the root web site.

**What is the motivation / use case for changing the behavior?**
Hosting multiple, named sites on a single machine in an environment with other IIS hosted sites.  Do not want to add the overhead of an additional web server.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 
* **Browser:** all 
* **Language:** TypeScript -> ES5
* ** IIS Version:** 8.5 with Url Rewrite installed

**Comment by ThiagoT1** [comment]
Can you confirm the same setup worked with RC4?

**Comment by jkyoutsey** [comment]
@ThiagoT1 Not in a timely manner, no.  Our migration path was far too complicated getting from RC4 to RC5.  I'll see if I can find an old artifact to extract and see if it worked.  But RC4 work or fail would only say if it was a regression in router.  Wouldn't provide any guidance as to a solution.

**Comment by ThiagoT1** [comment]
I'll be able to share relevant code in a couple hours. We have a working RC4 era router with this setup .

**Comment by jkyoutsey** [comment]
Thanks, @ThiagoT1 I'll watch for it.

**Comment by ThiagoT1** [comment]
Please let me know if it helps, since we are about to migrate our app.
The URL for redirection should include the Virtual Directory alias, or else you would be redirecting to the website root path.
I also included a condition to skip redirection when the URI is already OK.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <rewrite>
        <rules>
            <rule name="angularjs routes" stopProcessing="true">
                <match url=".*" />
                <conditions logicalGrouping="MatchAll">
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    <add input="{REQUEST_URI}" pattern="^/$" negate="true"/>
                </conditions>
                <action type="Rewrite" url="/SiteA" />
            </rule>
        </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

**Comment by jkyoutsey** [comment]
@ThiagoT1 I THANKS!  That did fix it.  The Rewrite has to have the sub-path in it.  Fantastic!

**Comment by ythirion** [comment]
@ThiagoT1 Thanks man it did the job for me.

**Comment by santhanam87** [comment]
Having same Issue with my apache server any sample configuration for it to get it fixed my project is hosted inside /timetrax folder.

**Comment by SEAN-LANOUE** [comment]
Well...  If you have an existing MVC site and you need to have Angular2 be able to only exist in a sub folder part of your existing site, this is how I had to solve it...

PROBLEM:
www.MySite.com/Item/123   <= Existing MVC Route ASP.NET C#
www.MySite.com/Help          <= Existing MVC Route ASP.NET C#
www.MySite.com/a/Checkout/  <= New section that will be written in all Angular2...  Checkout, order processing, cancel orders, returns etc
www.MySite.com/a/Order/  <= New section that will be written in all Angular2...  Checkout, order 
We are using Angular-CLI

1) 
Make sure you use ng build with the baseURL parameter set when building your Angular2 code

`
ng build --base-url a
`

2)  We had to add the following to our web.config
     

    `
     &lt;compilation>

       { possible other entries }

      &lt;buildProviders >

        <add extension=".htm" type="System.Web.Compilation.PageBuildProvider"  />

        <add extension=".html" type="System.Web.Compilation.PageBuildProvider"/>

      &lt;/buildProviders>

    &lt;/compilation>
`

3) In our Routes we needed to do this..

           `routes.MapRoute(
              "PackingSlip", // Route name
              "Item/{id}/ListingSummary", // URL with parameters
              new { controller = "Item", action = "ListingSummary" });
            
             // OTHER POSSIBLE CUSTOM MVC ROUTES

            // Route for default MVC
            //  NOTE:  the new Angular2 section.   "a" is the sub folder where everything angular2 will go
            //              Your sub folder could be called differently, but you just have to replace "a" with sub folder name
            routes.MapRoute(
               "Default", // Route name 
               "{controller}/{action}/{id}", // URL with parameters 
               new { controller = "home", action = "index", id = UrlParameter.Optional }, // Parameter defaults 
               new { controller = "^(?![aA]$).*" }  // <= exclude Angular2 sub folder "a"
             );

            // Route for new Angular2 section.   "a" is the sub folder where everything angular2 will go
            routes.MapWebFormRoute("Angular2", "a/{*anything}", "~/a/index.html");`

**Comment by xgqfrms-GitHub** [comment]
https://github.com/xgqfrms007/ng2-heroes/issues/1

![ng2-refresh-bug](https://cloud.githubusercontent.com/assets/17099059/26710234/fab83444-478a-11e7-8a7c-79bde76830fd.gif)

**Comment by PendelinP** [comment]
The solution @ThiagoT1 provided works like a charm but please **ensure you have the IIS rewrite module installed**.

It can be downloaded from here: https://www.iis.net/downloads/microsoft/url-rewrite

Further information can be found here: https://blogs.msdn.microsoft.com/premier_developer/2017/06/14/tips-for-running-an-angular-app-in-iis/

**Comment by prakash-patel** [comment]
after adding below code reload URL working fine. I found it here [https://code.msdn.microsoft.com/How-to-fix-the-routing-225ac90f](https://code.msdn.microsoft.com/How-to-fix-the-routing-225ac90f). Can someone explain why?

```
app.Use(async (context, next) => 
    { 
        await next(); 
        if (context.Response.StatusCode == 404 && !Path.HasExtension(context.Request.Path.Value)) 
        { 
            context.Request.Path = "/index.html"; 
            await next(); 
        } 
    }) 
    .UseDefaultFiles(new DefaultFilesOptions { DefaultFileNames = new List<string> { "index.html" } }) 
    .UseStaticFiles() 
.UseMvc(); 
```

**Comment by odairto** [comment]
@jkyoutsey, thank you so much dude. I just publish my web site and have the exactly this problem.
I tryed localhost like u said and it worked. I applyed the web.config to my publish host and works perfect.
Thanks once.

**Comment by hozrotali** [comment]
Hi friends, i was also getting the same issues like below,

Change index.html to set base href <base href="/SiteA/">
Browse to http://localhost/SiteA.
See that the site comes up correctly at the default route, say, localhost/SiteA/site/dashboard.
Click refresh in the browser.
See that it is redirected to the IIS home page.

To solve this, use below changes in url-rewrite


<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <system.webServer> 
    <rewrite>
      <rules>
        <rule name="AngularJS Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
                 <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
		 <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
		 <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
          </conditions>
          <action type="Rewrite" url="/myApp/" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>

Changes in 
<action type="Rewrite" url="/myApp/" />
not   url="/myApp"       Change to      url="/myApp/"  end with a /(slash )

it works for me after struggle a lot..... hope it helps others
Cheers............................

**Comment by hozrotali** [comment]
Hi friends, i was also getting the same problem like below,

Change index.html to set base href <base href="/SiteA/">
Browse to http://localhost/SiteA.
See that the site comes up correctly at the default route, say, localhost/SiteA/site/dashboard.
Click refresh in the browser.
See that it is redirected to the IIS home page.

To solve this, use below changes in url-rewrite

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <system.webServer> 
    <rewrite>
      <rules>
        <rule name="AngularJS Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
                 <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
		 <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
		 <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
          </conditions>
          <action type="Rewrite" url="/SiteA/" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>`

Changes in 
<action type="Rewrite" url="/SiteA/" />

not   url="/SiteA"       Change to      url="/SiteA/"  end with a /(slash )

it works for me after struggle a lot..... hope it helps others
Cheers............................

**Comment by shanegilbert** [comment]
Anyone know how to use the url rewrite middle ware to do this? I can't quite figure out the correct regular expression so that it will load the scripts and css files correctly but still rewrite the angular path to index.html. Here is one thing that I have tried that didn't quite work. I will admit that I am terrible with regular expressions.

      var options = new RewriteOptions()
         .AddRewrite(@"^((?!(\.\w{2,4}($|\?))).)*$", "/index.html", true);
      app.UseRewriter(options);

**Comment by helzgate** [comment]
I had to do the following using IIS 10 and ang7.

## Build
`ng build --base-href /address --deploy-url /address/ --prod`
Note: --base-href is the important one here regarding routing as --deploy-url has to do with the location of  your resources like css and images, etc.

## app.module.ts
I did **NOT** set the APP_BASE_HREF as shown in the top rated answer above although I'm sure you could, I'm setting it within my build command (I assume this is the same thing anyway).

## Let Angular NOT IIS handle 404
Currently IIS is probably handling your 404 error responses but you should let Angular determine what is, and is't found and you should setup a 404 conroller/page in your angular app (angular.io help pages show how).  To let Angular handle 404 instead of IIS you need to go to your site within IIS, then to Error Pages and configure 404.  Choose "Execute a URL on this site" and set it to "/address/index.html" (in my case anyway).

## Web.config
    <?xml version="1.0" encoding="UTF-8"?>
        <configuration>
            <system.webServer>
                <directoryBrowse enabled="true" />
                    <rewrite>
                        <rules>
                            <rule name="Angular Routes" stopProcessing="true">
                                <match url=".*" />
                                <conditions logicalGrouping="MatchAll">
                                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                                </conditions>
                               <action type="Rewrite" url="/address/index.html" />
                              </rule>
                        </rules>
                    </rewrite>
            </system.webServer>
     </configuration>
