### ISSUE TITLE
Feature Request i18n: pseudo-translation

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular#11040]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Waiting on RC6.

**Expected/desired behavior**
When we are developing in an i18n environment it can sometimes become difficult to spot raw strings in the application in QA due to cognates.  It would be very useful if a non-valid localization could be used to display the keys instead of the values. (zz for example)

**What is the motivation / use case for changing the behavior?**
Ease of troubleshooting strings not yet in the translation bundle. 

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6+
- **Browser:** all 
- **Language:** all

**Comment by vicb** [comment]
not sure I understand, could you expand ?
do you mean i18n ?

**Comment by vicb** [comment]
would pseudo-translation cover this ?

**Comment by zackarychapple** [comment]
@vicb, yes, i18n, apologies for the typo. A pseudo-translation would work assuming that translation was easily identifiable. The reason I was suggesting to use the keys is that it's a pattern I saw back when I used Spring for i18n.   Also will parameters be supported for the keys, so we can inject values in the middle of the translated term.  It would allow us to do "Welcome {firstName} to our application" instead of having to split the phrase into two strings.

**Comment by vicb** [comment]
> ... that translation was easily identifiable ...

I assume that a disguised version of the original string would make more sense but replacing with something of a different length probably also makes sense.

I'll make sure that different strategies could be easily swapped anyway.

pseudo-translation will most probably happen post final. 

> Also will parameters be supported for the keys

If you are asking if the **string** could contain interpolation / tags, yes they can.

They are replaced with placeholders. You can change the position of a ph but not it's content.
1 . src = `<p i18n>a {{color}} car</p>`
2. msg = `a [ph id=interpolation] car`
3. translated = `une voiture [ph id=interpolation]`
4. dst = `<p>une voiture {{color}}</p>`

**Comment by zackarychapple** [comment]
Sounds great.

**Comment by ocombe** [comment]
@zackarychapple can we close this one now? Or is it still an issue?

**Comment by zackarychapple** [comment]
@ocombe sure, I'm fine closing it.
