### ISSUE TITLE
ngc fails to generate angular factories against symlinked node_modules

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#11053]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have noticed that ngc does not work correctly if compilation is done using a symlinked node_modules folder.

Compilation of the app code will succeed, but the compiler fails to generate the new node_modules folder containing angular specific factories like `application_module.d.ngfactory.ts`. 

**Expected/desired behavior**
I was assuming the compiler would be able to follow the symlink and generate all necessary factories. Or at the very least throw an error if the scenario isn't supported.

**Reproduction of the problem**
Here is some sample source code used in my project. To reproduce the problem it's important to symlink the node_modules. Running against a regular node_modules folder works as expected.
```
**main.ts
import { platformBrowser }    from '@angular/platform-browser';
import { AppModuleNgFactory } from './app.module.ngfactory';
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);

**app.module.ts
import { NgModule }      from '@angular/core';
import { Component } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

@Component({
  selector: 'my-app',
  template: `<h1>My First Angular 2 App</h1>`
})
export class AppComponent { 
}

@NgModule({
  imports:      [ BrowserModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }

**tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },

  "files": [
    "app.module.ts",
    "main.ts",
    "typings/index.d.ts"
  ],
//app code factories will be generated correctly under 'dist', but no new node_modules folder is created
  "angularCompilerOptions": {
    "genDir": "./dist", 
    "debug": true
 }
}

```
* **Angular version:** 2.0.0-rc.5

**Comment by thelgevold** [comment]
@chuckjaz Do you have any idea if this should be a supported scenario?

**Comment by chuckjaz** [comment]
TypeScript will resolves symlinks, 

https://github.com/Microsoft/TypeScript/blob/5bdde3b284826cb07a335012ce697327b7627fac/src/compiler/sys.ts#L545

and module resolution is sensitive to how the symlinks are organized. I would recommend not using symlink node_modules as it confuses TypeScript module resolution.

**Comment by thelgevold** [comment]
That part I am confused about is that the same code with symlinked node_modules will compile fine if we use `tsc` directly . Does `ngc` do something different when referencing the files?

**Comment by wardbell** [comment]
@chuckjaz We've been using symlink node_modules for almost a year across many versions of TS. It will not be easy for us to stop. I don't think we can blame TS for this.

**Comment by alexeagle** [comment]
After https://github.com/angular/tsc-wrapped-builds/blob/master/src/main.js#L19
can you try adding
`host_1.realpath = function (s) { return s; };`

This should turn off symlink resolution inside `ngc` and it might fix the issue.

**Comment by thelgevold** [comment]
Thanks @alexeagle It looks like that did the trick! I just added the line you suggested to main.js and it started working!

**Comment by thelgevold** [comment]
@alexeagle Is this a fix that should be PR-ed into the repo or is this just an experimental fix?

**Comment by chuckjaz** [comment]
@wardbell Didn't mean to imply what TS was doing was wrong only that it is causing us problems. Alex's change just prevents TS from calling realpath and it works better in this scenario. I should be more careful in my wording.

**Comment by alexeagle** [comment]
Thanks for verifying. I'll send a PR

**Comment by thelgevold** [comment]
This is fixed
