### ISSUE TITLE
[Question][Security] ngNonBindable elements

### ISSUE THREAD

**Issue by vicb** [angular/angular#11052]
The [template parser](https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/template_parser/template_parser.ts) uses 2 visitors:

- 1 for regular nodes,
- 1 for non bindable nodes (`NonBindableVisitor`)

Seems like security/schema checks are only used in the former one.
Could this be a vulnerability that would allow JS injections ?

I don't have time to investigate more for now

/cc @mhevery @rjamet @mprobst @IgorMinar

**Comment by IgorMinar** [comment]
the security context is supposed to check that the bindings are not introducing something dangerous to dom, in the non-bindable context there are no bindings

you can create template that will do something dangerous, but you can do that in JS code as well

it’s only the user provided input that we want to protect against

**Comment by vicb** [comment]
If not a security issue it could be fixed after RC6

**Comment by mhevery** [comment]
I am with @IgorMinar I don't see a security issue here. If you can inject a malicious template then you can also inject malicious code.

**Comment by vicb** [comment]
Ok then we can plug the schema check at some later point, no required fro RC6.

Updated the labels accordingly.

**Comment by gehlotchirag** [comment]
Hi, If this can be fixed post RC6 then we should just go ahead and release RC6 as this is the only issue pending for the release!

**Comment by triniwiz** [comment]
@gehlotchirag rc6 it out already AFAIK
