### ISSUE TITLE
Angular does not work with the templates which include '{}' braces when using the Compiler

### ISSUE THREAD

**Issue by apoterenko** [angular/angular#11056]
**Angular does not work with the templates which include '{}' braces
I did not found the similar bug.

**Current behavior**
Angular does not work with the templates which include '{}' braces

**Expected/desired behavior**
Angular should work successfully with the templates which include '{}' braces 

**Reproduction of the problem**

```typescript
 @Component({selector: 'DynamicComponent', template: '<div>It\'s work {correctly []: test</div>'})
            class stub {
                constructor() {
                }
            }

this.compiler.compileComponentAsync<TDynamicComponentType>(stub)
                .then((dynamicComponentFactory:ComponentFactory<TDynamicComponentType>) => {
                    this.componentInstance = this.viewContainer.createComponent<TDynamicComponentType>(dynamicComponentFactory);
            });

Use Case1 (It works fine):

TEST.html:
<DynamicComponent [componentTemplate]="'<div>It\'s work correctly []: test</div>'"></DynamicComponent>

DOM:
<dynamiccomponent ng-reflect-component-template="<div>It's work correctly []: test</div>"></dynamiccomponent><dynamiccomponent><div>It's work correctly []: test</div></dynamiccomponent>

Use Case2 (Empty output inside DOM):

TEST.html:
<DynamicComponent [componentTemplate]="'<div>It\'s work {correctly []: test</div>'"></DynamicComponent>

DOM:
<dynamiccomponent ng-reflect-component-template="<div>It's work {correctly []: test</div>"></dynamiccomponent>
```

**What is the motivation / use case for changing the behavior?**
I wish to use arbitrary template like '<div>It\'s work {correctly []: test</div>'

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome 44.0.2403.157] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by ericmartinezr** [comment]
What's the error? Where is the reproduction of the issue? Is your problem similar/identical to https://github.com/angular/angular/issues/10886 ?

**Comment by apoterenko** [comment]
Use Case1:

TEST.html:
<DynamicComponent [componentTemplate]="'<div>It\'s work correctly []: test</div>'"></DynamicComponent>

DOM:
<dynamiccomponent ng-reflect-component-template="<div>It's work correctly []: test</div>"></dynamiccomponent><dynamiccomponent><div>It's work correctly []: test</div></dynamiccomponent>

Use Case2:

TEST.html:
<DynamicComponent [componentTemplate]="'<div>It\'s work {correctly []: test</div>'"></DynamicComponent>

DOM:
<dynamiccomponent ng-reflect-component-template="<div>It's work {correctly []: test</div>"></dynamiccomponent>

After no one, the dynamiccomponent directive does not work. Console output is empty, no errors, no warnings

**Comment by vicb** [comment]
escape the "`{`", ie "`{{ "{" }}`"

**Comment by apoterenko** [comment]
Thank you!
