### ISSUE TITLE
RC5 upgrade service breaks angular 1 router

### ISSUE THREAD

**Issue by sohai** [angular/angular#11055]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have angular 1 app with angular2 components and I use upgrade service to bootstrap application, after upgrading to RC5 angular 1 router stop working. Somehow this line https://github.com/angular/angular.js/blob/master/src/ng/location.js#L977 is invoked before https://github.com/angular/angular.js/blob/master/src/ngRoute/route.js#L609 so handler cannot catch event on init.

**Expected/desired behavior**
Router loads defined view on init.
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all] 
- **Language:** [all]

**Comment by marcalj** [comment]
I need to add a hack after bootstrap my application: (but all navigation works as expected except for the first one)

```ts
angular.element(document).ready(function () {
    // Bootstrap application
    upgradeAdapter.bootstrap(document.body, [dashboardMain.name]);

    // HACK ngUpgrade!
    let intervalHack = window.setInterval(() => {
        if (fixBootstrapping()) {
            window.clearInterval(intervalHack);
        }
    }, 3333);
});

// HACK ngUpgrade!
function fixBootstrapping() {
    if ($('a[href="#/"]').length > 0 && $('#main[ng-view]').length === 0) {
        window.history.pushState({}, 'hack', document.location.href);
        window.history.pushState({}, 'hack', document.location.href);
        window.history.back();

        console.log('>>> Force clippings section due to NG2 bug???');

        return true;
    }

    return false;
}
```

**Comment by DzmitryShylovich** [comment]
@sohai is this still valid?

**Comment by marcalj** [comment]
Yes! It's still needed! :(
Angular 2.4.5. AngularJS 1.6.1
ngUpgrade (not static).

**Comment by sohai** [comment]
@DzmitryShylovich I cannot check it in my project whether it is valid bug or not because I've already upgraded my project to the new router but as you can see comment above someone else need it.

**Comment by gkalpak** [comment]
It is hard to tell what might be wrong and whether this is still an issue without a runnable reproduction.
Sinc this issue is quite old, the dynamic version of ngUpgrade has been deprecated and there are so many different router combinations and setups possible, I am going to close this as non-actionable.

If anyone is still running into problems with the latest static ngUpgrade, please open a new issue (providing the necessary details).
