### ISSUE TITLE
ngc codegen quotes properties, which breaks closure compiler

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#11050]
Say I configure my routes with
```
export const routes: Routes = [
  {path: 'search', redirectTo: '/'}, {path: '', component: SearchVideos},
  {path: 'upload', component: UploadVideos}
];
```

ngc produces an ngfactory.ts containing:
```
  get _ROUTES_40():any[] {
      if ((this.__ROUTES_40 == (null as any))) { (this.__ROUTES_40 = [[
        {
          'path': 'search',
          'redirectTo': '/'
        }
        ,
        {
          'path': '',
          'component': import38.SearchVideos
        }
        ,
        {
          'path': 'upload',
          'component': import39.UploadVideos
        }

      ]
    ]); }
    return this.__ROUTES_40;
  }
```

note that `redirectTo` got quoted as `'redirectTo'`

When closure compiler renames the `redirectTo` property to some short name, it won't rename the one in the ngfactory.ts because it's quoted.

**Comment by tbosch** [comment]
We should do whatever the user wrote is put into the generated code.
I.e. if the user used `{path:...}` we should use `path`, if the user used `{'path': ...}` we should use `'path'`.

**Comment by alexeagle** [comment]
I did update the metadata collector to preserve quotes: https://github.com/angular/angular/pull/11107/commits/8e87ce0222112b14572b0b1629eb0b0c5a7855fe

But @tbosch thought more about places in the expression parser that would need to change to match the semantics. Instead we'll just stop quoting properties in codegen map literals.
