### ISSUE TITLE
The AoT compiler tries to call ngOnChanges with a parameter although none is declared

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#11062]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a component implements `OnChanges` it's not an error to create a `ngOnChanges()` function without a parameter. TypeScript is fine with that and runtime JavaScript has always been fine calling a function with too many parameters.

However, the AoT compiler generates a call to the component's `ngOnChanges` function with a parameter and that is an error in TypeScript land.

**Expected/desired behavior**
I have quickly hacked that casting the component to the `OnChanges` interface and calling `ngOnChanges` on that avoids the TypeScript error.

``` ts
if ((changes !== null)) { this._MyComponent_5_4.ngOnChanges(changes); }
// becomes
if ((changes !== null)) { (<hackedimport.OnChanges>this._MyComponent_5_4).ngOnChanges(changes); }
```

But an even better solution probably is to change the code generation that leads to the call. All the `SimpleChange` objects aren't necessary in that case and not creating them means less stress for the garbage collector.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Language:** [TypeScript]

**Comment by danieleds** [comment]
Any temporary workaround?

**Comment by danieleds** [comment]
Nevermind, you can just add an empty formal parameter to ngOnChanges.

NB: when you get the error `my.component.ngfactory.ts:811:40: Supplied parameters do not match any signature of call target.`, the problem could be related to a referenced component's ngOnChanges, not to `my.component`.

**Comment by mlaval** [comment]
Same issue is happening with the `NgTemplateOutlet ` directive from core, see #11599.

Here is the issue isolated in a TS playground:
https://www.typescriptlang.org/play/#src=abstract%20class%20OnChanges%20%7B%0D%0A%20%20abstract%20ngOnChanges(changes%3A%20any)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aclass%20NgTemplateOutlet%20implements%20OnChanges%20%7B%0D%0A%09ngOnChanges()%20%7B%0D%0A%09%09%2F%2F%20Do%20something%20where%20changes%20is%20not%20needed%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Generated%20by%20ngc%0D%0Aclass%20SomeGeneratedFactory%20%7B%0D%0A%09private%20_NgTemplateOutlet%3A%20NgTemplateOutlet%3B%0D%0A%09%0D%0A%09detectChangesInternal(throwOnChange%3Aboolean)%3Avoid%20%7B%0D%0A%09%09var%20changes%3A%7B%5Bkey%3A%20string%5D%3Aany%7D%20%3D%20(null%20as%20any)%3B%0D%0A%20%20%09%09if%20((changes%20!%3D%3D%20(null%20as%20any)))%20%7B%0D%0A%09%09%09%20%20this._NgTemplateOutlet.ngOnChanges(changes)%3B%0D%0A%09%09%7D%0D%0A%09%7D%0D%0A%7D

**Comment by pkozlowski-opensource** [comment]
Obsolete / fixed: https://ng-run.com/edit/NUwMAQixg3Zlv0GhJDyc
