### ISSUE TITLE
When overriding a provider, the AoT compiler might generate invalid code

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#11066]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In my root `AppMoule`, I `{  provide: Http, useClass: FakeHttp }`. The `FakeHttp` is a very bare implementation that supports just the calls my application actually needs, so `<Http>FakeHttp` is a TypeScript error.
One of my services in the providers requires `Http` and the AoT compiler generates code that injects the member of the ngfactory of the `AppModule` into that service. However, this member is typed `FakeHttp` which is not type-compatible with `Http` constructor argument.

**Expected/desired behavior**
The generated code should support the duck typing that's possible at runtime, although the actual declared types don't match.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Language:** [TypeScript X.X] 

A workaround is to `useFactory`. In that case, the ngfactory's member for the provider has type `any`.

**Comment by chuckjaz** [comment]
Unless I am missing something, TypeScript is correct. Since `<Http>fakeHttpInstance` is a type error then allowing `FakeHttp` as a value for `Http` should not be supported.

Consider constructing an interface that describes the subset of `Http` that your service uses that is assignment compatible with both `Http` and `FakeHttp` and using that as the parameter type. This more correctly describes your intent and will also type-check.

**Comment by Tragetaschen** [comment]
The thing is, Dependency Injection doesn't work with that. When I change my constructors to use an `HttpSubset` interface, I cannot set up a provider for it. A proposed alternative regularly is "use an abstract class", but that train has gone for `Http`. So now, I'm also creating a DI token.

That's a lot of boileplate for something that works at runtime and could be solved by `<Http><any>`...
