### ISSUE TITLE
why import class of service in each child-component if we want to use it

### ISSUE THREAD

**Issue by istiti** [angular/angular#11061]
I have simple question:
Why I have to import each time I need it the service file in my sub-component while I have already did it in a root component or in bootstrap ngModule...

when in  a sub-component I put in the constructor
constructor(private dataService : DataService){}
I need also import { DataService }...

I thinked if we did it in a root component it will be available on their childs because I use the same instance 
 I need more explanation maybe :santa:

**Comment by denkomanceski** [comment]
have you ever used Java or some different language besides js ?

**Comment by istiti** [comment]
**** <= here is your answer

So my response is as stupid as your!

Your "question" or "response" (call it as you want):
Will help ME to understand? 
Or you to understand what I asked? 
Certainly NO !!! 

So stop be arrogant, stop answer me if you pretend be a programmer who understand all concept (clap clap clap)

Can someone with ethics/moral explain me this behavior. I don't know how angular-compiler or tsc work I thinked all you import in a root will be available in their childs (as components)

Thanks in advance.

**Comment by qdouble** [comment]
@istiti the issues posted in this repo are for bug reports and feature request, not support questions, people will be more than happy to answer you questions on the gitter chat https://gitter.im/angular/angular or StackOverflow. 

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by istiti** [comment]
@qdouble thanks, I accept you answer even if the content of yours answer is relative ! Because I can say here that I think it's bug:  in rc.5 all imported components class in root are available to their sub-components while services class import aren't WHY? And here maybe someone explain me this behavior and close the topic or as you send me to understand better programmation concept (but I already know the difference of instance....)

Don't worry,  I will ask this on gitter, thanks
