### ISSUE TITLE
The AoT compiler doesn't support Subject<T> as type for @Output members

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#11064]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The AoT compiler generates invalid TypeScript code when an `@Output()` member of a component is a `Subject<...>`.
The reason is that the `AppView` base class' `eventHandler` function only returns a `Function` and that's not a valid type for `Subject<...>`'s `susbcribe` method.

Compiling at runtime works fine with that.

**Expected/desired behavior**
The AoT compiler shouldn't generate invalid code.
- **Angular version:** 2.0.0-rc.5 / rxjs 5.0.0-beta.6
- **Language:** [ TypeScript X.X ] 

A workaround is to declare the `@Output()` member as `EventEmitter<...>`. This class contains a `subscribe` "overload" with an `any` parameter so the `Function` return type matches.

**Comment by DzmitryShylovich** [comment]
@Tragetaschen I've just tests and haven't got any error. `@Output` with `Subject` works fine. Can you confirm and close the issue?

**Comment by Tragetaschen** [comment]
I'm currently close to a release and don't want to upgrade Angular yet. Will do in a week or so.

**Comment by Tragetaschen** [comment]
I've migrated my application to 2.4.8 and indeed I can omit the commit for this issue from my AOT branch.

Nice!
