### ISSUE TITLE
nested ngFor lose object

### ISSUE THREAD

**Issue by Activee** [angular/angular#11068]
**I'm submitting a ...** 
```
[ X] bug report 
```

**Current behavior**
When nesting *ngFor the object is not passed accordingly. See this small plnkr (and check MyCubeComponent which is in app.component.ts)

https://plnkr.co/edit/thAs3Fwf2rkRMn4aIjbv?p=preview

**Expected/desired behavior**
It's not clear to me if it is a design decision. What I'd expect however is to be able to pass the object.

**Reproduction of the problem**

https://plnkr.co/edit/thAs3Fwf2rkRMn4aIjbv?p=preview

**What is the motivation / use case for changing the behavior?**
One simple fix is to have a component in the middle to pass the data. This component is a bit useless as it just acts like a bridge.

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript]

**Comment by Termanty** [comment]
Hi, Do you notice that in second \*ngFor you are passing Array with one cube, not just cube. If I make this change 
  ----> {{cube**[0]**.name}}
for myCubeComponent template, then it works? Am I totally lost?

**Comment by osmanm786** [comment]
try this: notice the array.

 cubeMatrice = [
    [new Cube("hi"), new Cube("hello")],
    [new Cube("bonjour"), new Cube("holla")]
  ]

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got answered. Thnx @Termanty and @osmanm786 for helping out with the issues!

**Comment by Activee** [comment]
@Termanty  You are right it works but I fail to see how I'm passing an array on the second *ngFor. On the first ngFor I'm passing the matrix

```
  cubeMatrice = [
    [[new Cube("hi")], [new Cube("hello")],
    [new Cube("bonjour")], [new Cube("holla")]]
  ]

*ngFor="let cubeArray of cubeMatrix"
```

so the variable cubeArray is sequentially equal to an array. For instance on the first iteration it's [new Cube("hi")], an array of one element.

Then I've a second `*ngFor` which should result in the cube object.

`let cube of cubeArray`

I triple checked but 'm not trusting my judgement right now as I had a couple glass of wine this evening. Obviously I'm probably misunderstanding something here because this doesn't sound right.

**Comment by Activee** [comment]
@Termanty Oh damn, my mistake, that was a typo sorry for the inconvenience ..

**Comment by Activee** [comment]
@pkozlowski-opensource While my original post contained a typo in the example there still is an issue although it's not what my original post stated. It took me some time today to figure this out.

Here is an updated version of the last plnkr. Notice that passing a value with {{}} instead of [] in a nested *ngFor doesn't pass the actual object.

https://plnkr.co/edit/thAs3Fwf2rkRMn4aIjbv?p=preview

**Comment by pkozlowski-opensource** [comment]
@Activee I don't know what you are _trying_ to do but your array is 3-dimensional but you've got only 2 ngFor. I _suspect_ that you've got too many brackets and instead trying to do https://plnkr.co/edit/6DPF9yOhRfA4aJ05D24u?p=preview but hard to say.

I don't see a bug here. If you still believe that there is one please reduce your example to the bare minimum and clearly state actual vs. expected behavior.

**Comment by osmanm786** [comment]
you have 3 nexted arrays so you need 3 *ngfor
take a look:
   <div *ngFor="let cubeArray of cubeMatrice">
    <div *ngFor="let innercubearray  of cubeArray">
    <my-cube *ngFor="let cube of innercubearray" [cube]="cube" >
    
    </my-cube>
   </div>
      </div>

**Comment by osmanm786** [comment]
here is the plunker:

https://plnkr.co/edit/LxZKmfeH533PxP23HwEF?p=preview

**Comment by Activee** [comment]
@pkozlowski-opensource @Termanty 

I'm not that familiar with plnkr yet, I think I sent the wrong code in my last reply. I did unfreeze and refreeze just now.

Just in case I'm still messing things up here is the code for the components (notice  it's not 3 level deep):

```
@Component({
  selector: 'my-app',
  template: `<h3 class="title">Basic Angular 2</h3>
  <hr />
  With square brackets to pass input
   <div *ngFor="let cubeArray of cubeMatrice">
    <my-cube *ngFor="let cube of cubeArray" [cube]="cube" >
    </my-cube>
   </div>
   
    With curly braces to pass input
   <div *ngFor="let cubeArray of cubeMatrice">
    <my-cube *ngFor="let cube of cubeArray" cube="{{cube}}" >
    </my-cube>
   </div>
   
  `
})
export class AppComponent {
  cubeMatrice = 
    [
      [new Cube("hi"),new Cube("hi")], [new Cube("hello")],
      [new Cube("bonjour")], [new Cube("holla")]
    ]
  
   
  constructor(){
   
  }
}

@Component({
  selector: 'my-cube',
  template:`
  ----> {{cube.name}}
  `
})
export class MyCubeComponent {
  @Input() cube;
  constructor(){
  }
}

export class Cube{
  name;
  constructor(name){
    this.name = name;
  }
}
```

**Comment by pkozlowski-opensource** [comment]
`cube="{{cube}}"` means "convert" to string, use `[cube]="cube"` if you want to pass objects around.

Anyway this really _is_ a support question so please move it to an appropriate channel if you need more assistance: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

There is _no_ bug in here.
