### ISSUE TITLE
Template Element Reference isn't updated when ngIf state changes

### ISSUE THREAD

**Issue by marinho** [angular/angular#11065]
**Current behavior**

I have a template element reference `#theContainer` which is used in another element (`h2`).

There's a condition (`*ngIf="theCondition"`) for the container to be rendered.

When the condition changes, the template element reference isn't updated, neither `ngOnChanges` is called.

It doesn't matter if the element reference is declared as a `ViewChild` or not.

Here is how it is implemented (`src/app.ts`):

```
@Component({
  selector: 'my-app',
  template: `
    <div>
      <h2>Here is it: {{myContainer || 'not assigned yet'}}</h2>
      
      <button type="button" (click)="theCondition = !theCondition">Switch to {{!theCondition}}</button>
      
      <div #myContainer *ngIf="theCondition">
        <p>I see the container's content!</p>
        
        <p>You should see the container reference in the header.</p>
        
        <p>Look at src/app.ts</p>
      </div>
    </div>
  `,
})
export class App {
  constructor() {
    this.name = 'Angular2 (Release Candidate!)'
  }
}
```

**Expected/desired behavior**

The element reference should update every time the referred element is changed, triggering the change detector by consequence.

**Reproduction of the problem**

http://plnkr.co/edit/VxRH7W?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Chrome 52 (but I believe it happens for all)
 
* **Language:** [TypeScript 2.0]

**Comment by Termanty** [comment]
According this https://angular.io/docs/ts/latest/guide/template-syntax.html#!#star-template DOM will look like this after **expanding *ngIf**

    <div>
      <h2>Here is it: {{myContainer || 'not assigned yet'}}</h2>

      <button type="button" (click)="theCondition = !theCondition">Switch to {{!theCondition}}</button>

      <template [ngIf]="theCondition">
        <div #myContainer *ngIf="theCondition">
          <p>I see the container's content!</p>

          <p>You should see the container reference in the header.</p>

          <p>Look at src/app.ts</p>
        </div>
      </template>
    </div>

Now we have problem because 

> We can reference a template reference variable on the same element, on a sibling element, or on any child elements.

You can find it here https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ref-vars

Please correct me if I am wrong. Still really noob with Angular.

**Comment by marinho** [comment]
True, so, we can guess it may be solved by just wrapping the `div` with `*ngIf* by a new element with the element reference, while the `*ngIf`. Which works here in this new plnkr: http://plnkr.co/edit/5EwsnQ?p=preview

Even though the "pure" interpretation of the documentation is compatible to what happens, for me that still feels like a bug, as the directive should be able to solve that problem instead of forcing the developer to write a wrapper element.

I also missed to mention that it also shows this error message:

```
ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: 'Here is it: not assigned yet'. Current value: 'Here is it: [object Object]'.
```

**Comment by Termanty** [comment]
You should check how ngOnChange() works from here https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#hook-sequence
It mentions that this hook fires when
> before ngOnInit and when a **data-bound input property value** changes.
I made highlight. So ngOnChange() reacts when @input() property changes.

**Comment by pkozlowski-opensource** [comment]
Sounds like a support request that got resolved.
