### ISSUE TITLE
@HostBinding can only set global css classes

### ISSUE THREAD

**Issue by kemsky** [angular/angular#11077]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Component:
```
...
    @HostBinding('class.small')
    private small:boolean = true;
...
```

Component style, private `styles: ['...']`:
```
.small {
    height: 100px !important;
}
```

Rendered:
```
<div class="small"></div>
```

And it does not have any effect obviously.

**Expected/desired behavior**

It should be possible to specify internal/private component class: `:host.small`

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by pkozlowski-opensource** [comment]
You can use pseudo element selector `:host` to scope styles to the host element instead of its content: https://plnkr.co/edit/EPK3KnMGiCMs2ZTIYNT6?p=preview

In the future please:
* fill inn issue template - most importantly provide a minimal plunker
* ask on a support forum if you are not sure if you are facing a bug or not, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by kemsky** [comment]
For anybody who is interested, class has to be defined twice to be used with `HostBinding` and template:
```
:host.small, .small {
}
```

**Comment by zoechi** [comment]
Should be `:host(.small) {}`

**Comment by kemsky** [comment]
@zoechi, it does not work:
```
:host(.small) {
    height: 60px !important;
}
//==> host only
[_nghost-edd-26].small {
    height: 60px !important;
}
```
vs
```
:host.small, .small {
    height: 60px !important;
}
//==> host and template
[_nghost-ykl-22].small, .small[_ngcontent-ykl-22] {
    height: 60px !important;
}
```

Personally, i don't think it was necessary to split host and template classes as long as they both belong to component:
```
.small {
    height: 60px !important;
}
//==> host and template
[_nghost-ykl-22].small, .small[_ngcontent-ykl-22] {
    height: 60px !important;
}
```

**Comment by zoechi** [comment]
Please provide a Plunker that demonstrates the actual behavior and explain what behavior you expect.
