### ISSUE TITLE
The AoT compiler should support TypeScript's noUnusedParameters setting

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#11074]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The compiler generates function parameters that might not be used. My project runs with TypeScript's `noUnusedParameters: true` and I'm getting errors for nearly all ngfactory files where `rootSelector` and `$event` are not used.

**Expected/desired behavior**
The generated code should compile with `noUnusedParameters`.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Language:** [TypeScript 2.0]

A rather quick-and-dirty fix is to prefix the variable names [with an underscore](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#user-content-flag-unused-declarations-with---nounusedparameters-and---nounusedlocals). That supresses the error.

**Comment by JamesHenry** [comment]
@tbosch will you accept a PR to add underscores as prefixes to generated TS code?

**Comment by tbosch** [comment]
@JamesHenry Can we instead generate code that does not add these parameters? Could you list the cases where we do in this issue? If we can't avoid the parameters, then we will probably have to add underscores. But only at the right places...

**Comment by CSchulz** [comment]
For example

```
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
```

**Comment by IgorMinar** [comment]
@tbosch I believe this is a bug and not a feature request. It is a reasonable expectation that we don't generate code with unused parameters. no?

**Comment by kevinphelps** [comment]
TSLint's "no-unused-variable" rule can be used in place of TypeScript's "noUnusedParameters" setting until this is fixed.

tslint.json:
```
{
  "rules": {
    ...
    "no-unused-variable": [true, "check-parameters", {"ignore-pattern": "^_"}]
    ...
  }
}
```

**Comment by tbosch** [comment]
Closing in favor of #15532

**Comment by brunolm** [comment]
`no-unused-variable` needs type information:

```
Warning: The 'no-unused-variable' rule requires type infomation.
```

It doesn't work in this scenario:

```
async logout(x = '') {
   // no code with x parameter
}
```

```
All files pass linting.
```
