### ISSUE TITLE
Form Reset doesn't work for custom ValueAccessor

### ISSUE THREAD

**Issue by rakibler** [angular/angular#11073]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When doing a form reset() on a form that contains a custom valueAccessor, the displayed value of that control isn't reset. It gets reset on the backend of the form, but not from the user's perspective. 

**Expected/desired behavior**
I expect the reset() to empty the form value and the displayed value

**Reproduction of the problem**
https://plnkr.co/edit/0iVxcXSV5ljm5o7c86DE?p=preview

**What is the expected behavior?**
I expect the reset() to empty the form value and the displayed value

**What is the motivation / use case for changing the behavior?**
I expect this is a bug, and so it should be fixed

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Chrome 52 
 
* **Language:** Typescript 1.8.10

**Comment by qdouble** [comment]
I was playing with this as well. It basically seems that any control that you create a value accessor for does not receive any update that the control has been reset until you touch it.

**Comment by qdouble** [comment]
After playing with it some more, I can get it to work if I put change detection to OnPush on my inputs... if I keep it on and try to manually trigger change detection from where the reset was called, it still does not update properly, so this should still definitely be considered a bug. The reset should trigger it's controls to update their view.

**Comment by kara** [comment]
@rakibler  The reset functionality hinges on being able to write to your component.  It looks like your custom form control's `writeValue()` method is not actually hooked up to anything.  When it's called, it sets `this.value`, but the value isn't set on the internal input element.  When you implement `writeValue()`, the reset function can clear the field.
 
https://plnkr.co/edit/2hSwZ9MuJoeG9f1SEm98?p=preview

**Comment by rakibler** [comment]
Wow, thanks so much.  Sorry for wasting time with something that was my fault

**Comment by rakibler** [comment]
Never mind!  @DzmitryShylovich pointed out in gitter that `control` should've been ElementRef, not HTMLElement.  It's working now!

**Comment by kara** [comment]
@rakibler Yes, the type should definitely be `ElementRef` - sorry for the confusion.

**Comment by rodhoward** [comment]
I like being able to use the Angular bindings ngModel rather than setting the value directly. My work around was to:

1. get the ngModel in my component control:
html:
'''
<input #inputModel="ngModel" .....
'''
js:
'''
@ViewChild('inputModel') inputModel: NgModel;
'''

2. On writeValue reset the inputModel:
this.inputModel.reset();

This seems to be working ok and it allows me to use the ng-dirty flags etc inside the control.

**Comment by avinashdasari** [comment]
Hi,

I am facing the same issue. Provided my control value accessor is implemented in a directive which can be applied on any input form control. When we reset the form, the model value changes to "null" however the view still shows the old value. I have tried to reset the control from WriteValue method and also tried to setValue from within the WriteValue method. It does not work. Suggestions please.
