### ISSUE TITLE
Children of componentless routes with named outlets are placed into the incorrect router-outlet

### ISSUE THREAD

**Issue by UnwrittenFun** [angular/angular#11082]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When a route with a specified outlet has children, the activated child is put into the main router outlet, along side the route component that is already active inside this outlet, rather than in the named outlet.

**Expected/desired behavior**
Routes whose (componentless) parents have a specified outlet, should go into said outlet.

**Reproduction of the problem**

The relevant route:
```
  {
    path: 'session',
    outlet: 'dialog',
    children: [
      {
        path: 'login',
        component: LoginComponent,
      },
      {
        path: 'register',
        component: RegisterComponent,
      }
    ]
  }
```

Plunkr reproducing the issue:
http://plnkr.co/edit/W4t6c2hFWW3x9Sf2pn8S?p=preview
Click the three different links and you can see the login and register routes are put into the main outlet alongside the already activated home route, whereas the confirmation route is correctly placed in the named outlet.

**What is the motivation / use case for changing the behavior?**
I believe this to be a bug and the use case is demonstrated in the plunkr

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** all
 
* **Language:** TypeScript 2.0.0

**Comment by mrkosima** [comment]
I met this case too.
Looks like missed error - `component is undefined`
Adding component to `{path: 'session', outlet: 'dialog'...` Route will resolve the issue

**Comment by UnwrittenFun** [comment]
The session route is a [componentless route](https://angular.io/docs/js/latest/api/router/index/Routes-type-alias.html#componentless-routes)

The routes could be expressed like so, fixing the problem
```
  {
    path: 'session/login',
    component: LoginComponent,
    outlet: 'dialog',
  },
  {
    path: 'session/register',
    component: RegisterComponent,
    outlet: 'dialog',
  },
```
But that leads to a lot of duplication, particularly when using the `resolve`/`data` properties, which componentless routes are supposed to solve

**Comment by vsavkin** [comment]
Fixed by https://github.com/angular/angular/pull/12412/commits

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781518/668e4d64-b7be-11e6-91d3-92185960dd79.png)
![Uploading 图片.png…]()

**Comment by KevinSeroux** [comment]
I was expecting this to work:

```
{
  path: 'session',
  children: [
    {
      path: 'login',
      outlet: 'dialog',
      component: LoginComponent,
    },
    {
      path: 'register',
      outlet: 'dialog',
      component: RegisterComponent,
    }
  ]
}
```

Because the problem with the above solution (merging the componentless route and the component route: session/register), is that routerLinkActive does not work for "session/register".
