### ISSUE TITLE
request| AoT prettyPrint metadata

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#11080]
compilerOptions for prettyPrint metadata

**Comment by chuckjaz** [comment]
Currently I am optimizing for space, hence the minimized output. Are you finding you are reading these files often? What are the things you are doing that prettyPrint'ed metadata would make easier?

**Comment by gdi2290** [comment]
just for reading and explain how angular 2 works

**Comment by chuckjaz** [comment]
We have no plans to implement this.
