### ISSUE TITLE
Router does not appear to support string :id

### ISSUE THREAD

**Issue by WilliamsSimonP** [angular/angular#11090]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I have the following lazy loaded routing defined

```
import { Routes, RouterModule } from '@angular/router';

import { ForumComponent }  from './forum.component';
import { ForumThreadComponent } from './forum-thread/forum-thread.component';
import { ForumThreadListComponent } from './forum-thread-list/forum-thread-list.component';

const routes: Routes = [
  {
    path: '',
    component: ForumComponent,
    children: [
      {
        path: ':id',
        component: ForumThreadComponent
      },
      {
        path: '',
        component: ForumThreadListComponent
      }
    ]
  }
];

export const routing = RouterModule.forChild(routes);
```

I am constructing the link with

```
<a *ngFor="let thread of threads" [routerLink]="['/forum', thread.id]">Thread {{thread.id}}</a>
```

This works fine when the id is a number, but when the id is a string, the link URI is constructed with the id as a query string parameter called str.  E.g.

```
/forum/3
```

for a numeric id, but

```
/forum;str=abcd
```

for a string id.  (I haven't tried a numeric id supplied from a string property)

**Expected/desired behavior**

I would expect both number and string id properties to result in the same format link URI.

**Reproduction of the problem**

See above

**What is the expected behavior?**

Number and string ids should both be passed as part of the URI path if specified as simple values in the link component array. 

**What is the motivation / use case for changing the behavior?**

It should be possible to use a name or guid (for example) as the identity of an object.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5

* **Router version:** 3.0.0-rc.1

* **Browser:** Chrome 52 on Ubuntu 16.04 
 
* **Language:** TypeScript 1.8.10

**Comment by brandonroberts** [comment]
Can you reproduce this in a plunker?

**Comment by WilliamsSimonP** [comment]
Probablly not I am pleased to say.  I woke up this morning and had one of those eureka moments!  I had forgotten that the id property I was using (a guid) had been wrapped in a Guid class.  The Guid class has a  single property called str.  This means that the behaviour, although a little odd, is at least understandable.  I can't get to the code at the moment, but I suspect that if I change the lik to use id.toString() it would work.

I still believe tha there is a minor issue as the framework is attempting to use a complex value where only a simple value makes sense and producing a strange result (understandably) as a result, but the only way to deal with it better would be toi throw an error.

**Comment by WilliamsSimonP** [comment]
Having thought further about this, it is probably very difficult to do anything about this.  It is confusing behaviour, but since the correct way to provide query string parameters is by supplying a complex value this behaviour is inevitable.

When coded as {id='abcd'}, it is clear what is happening, but when you are just passing a value it is not.  The issue is that I can't see how the difference can be detected at run time.  All the framework knows is that it has a complex value to work with.  Parsing the way the value is coded in the router-link is not practical as all we are providing is JavaScript and we wouldn't want the framework to second guess our intentions.  Short of a change to the way we supply query string parameters to router-link, I guess we'll have to live with it.  Having seen it once, I doubt I would be phased by it again, but I bet others are caught out!
