### ISSUE TITLE
Parent and children communicate via a service not working with two or more components

### ISSUE THREAD

**Issue by DarienF** [angular/angular#11099]
I find interesting example how transfer data from one component to another component using Subject/Observable in Service:
[http://plnkr.co/edit/yMBoVkxohwhPig5COgkU?p=preview]

Example working acording to: [https://angular.io/docs/ts/latest/cookbook/component-communication.html]

But I notice that subscribe to data changes can only component that inishiated data change. There is no possibility to get data changing in one component after another component changed it. This could be serios issue in case need to re-render data in component when another component chaanged it.

**Comment by mlc-mlapis** [comment]
Probably you missed something from RxJS concept and how it works. There is a simple pattern and flow of data from a producer (what is observed = observable) to a subscriber -> one direction stream. Of course you can use many operators to join streams, reduce them, transform them, ... and a subscriber can process incoming data and produce another observable that will have others subscribers and so on.

**Comment by DarienF** [comment]
My components located not in ome module. I create project structure from [https://angular.io/docs/ts/latest/guide/router.html]. I have one component in one module, another component in another module and module in module. Could this be as issue?

**Comment by mlc-mlapis** [comment]
I do not think so. The problem should be somewhere else. I do not fully undestand your cmps hierarchy just on previous short description so it is hard to guess.

**Comment by mlc-mlapis** [comment]
You have to create a plunk or a hierarchy diagram how cmps are related, where are observables and where subscribers.

**Comment by robwormald** [comment]
The linked plunker appears to work fine, so its probably specific to your code. A repro would be helpful in diagnosing if you think there's an actual bug, but otherwise please take this question to gitter.

**Comment by DarienF** [comment]
Ok. Give a fiew days to invastigate more this problem I will come this some info later.

**Comment by DarienF** [comment]
I find that problem was probably with clearing browser cache. My code working correct but befor I need to delete old *.js and  *.js.map files. I working under Visual Studio 2015 Server (not lite-server) so when I restart server on VS 2015 and new files was generated problem was solved)
