### ISSUE TITLE
Angular 2 Headers Response

### ISSUE THREAD

**Issue by bastienlemaitre** [angular/angular#11098]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
```

**Reproduction of the problem**
I send headers from my C# WEB API 2 into the response, everything is ok when I use postman, I can see them. But  when I use Angular 2 Http, they seems to be not mapped.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome (latest) ] 
 
* **Language:** [TypeScript ES6]

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
