### ISSUE TITLE
feat(di) make deps-property optional for useFactory-Tokens when using ReflectiveInjector

### ISSUE THREAD

**Issue by choeller** [angular/angular#11094]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When creating Tokens via 'useFactory' with the Reflective-Injector we currently need to provide an deps-Array, even if the factory has no dependencies:
```
  let injector = ReflectiveInjector.resolveAndCreate([
    {provide: 'random-value', useFactory: () => {
      return Math.floor(Math.random() * 101);
    }, deps: []}
  ]);
```
in this case it would be nice if the deps-array would not be needed at all

```
  let injector = ReflectiveInjector.resolveAndCreate([
    {provide: 'random-value', useFactory: () => {
      return Math.floor(Math.random() * 101);
    }}
  ]);
```

**What is the motivation / use case for changing the behavior?**

Less boilerplate-code

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [all]

**Comment by sod** [comment]
There was the commit https://github.com/angular/angular/commit/eb7d8c702cec6e4217eb47d3846e64ccf03fd271 into master two days ago that made `deps` optional.

**Comment by choeller** [comment]
@sod oops, I should do a rebase before opening issues :grimacing: thanks!
