### ISSUE TITLE
Infinitive loop for custom ControlValueAccessor in certain conditions

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#11097]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

While implementing a custom `ControlValueAccessor` which should accept non-primitive model we can easily go into infinitive loop + browser crash. The work-around exists but is non-intuitive and requires boilerplate.

This happens for the following condition: `<custom-control [ngModel]="foo()">` where `foo()` returns returns objects (non-primitive value) and can return _different_ objects for subsequent calls (equal in terms of content but not equal in terms of references).

**Expected/desired behavior**

People should be able to use functions when binding to `[ngModel]` as it was the case till recently (I believe that it used to work till RC4 or RC5 where async component was introduced into ngModel impl).

**Reproduction of the problem**

Here is a minimal plunker based on the real life scenario:  https://plnkr.co/edit/HlIgVEuZ3wfS5hFMjPFm?p=preview

In the above plunker there is a simple time-picker implementation that requires the following data structure as its input: `{hour: number, minute: number};`. It works fine when used as `<time-picker [ngModel]="{hour: 13, minute: 30}"></time-picker>`. But if a user wants to create `{hour: 13, minute: 30}` in a function call (ex. to convert internal string structure to a structure required by a date-picker) we go into infinitive loop. 

To see infinitive loop + browser crash uncomment the following line `<time-picker [ngModel]="strToTime(timeAsStr)"></time-picker>`.

**!!!WARNING!!!** IT WILL CRASH YOUR BROWSER.

**What is the expected behavior?**

People can use functions to convert model values from internal data structures in a component (ex. string in my plunker) to data structures required by a control. Conceptually we need a mechanism similar to parsers / formatters pipeline from Angular 1.x.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** all
- **Language:** all

**Additional info:**

Discuses this use case with @mhevery and was advised to ping @kara 
The issue was originally raised in the https://ng-bootstrap.github.io/ project under https://github.com/ng-bootstrap/ng-bootstrap/issues/545

**Comment by kara** [comment]
Definitely need this. Related to https://github.com/angular/angular/issues/3009.

**Comment by uber5001** [comment]
Just ran into this issue. ([stackoverflow](https://stackoverflow.com/questions/44570644/why-does-ngmodel-cause-infinite-loops-when-passing-new-objects-when-input-doesn/44571874#44571874)) Why does it seem to work fine for custom properties/@Inputs, but loops on ngModel?

**Comment by shyamal890** [comment]
+1

**Comment by dylhunn** [comment]
We discussed this in brief today. The only use case we could think of was #3009, and if we decide to implement that, we will revisit support function calls in `ngModel` bindings. Otherwise, we probably won't implement this.
