### ISSUE TITLE
ngc: enforce strict null checks

### ISSUE THREAD

**Issue by tbosch** [angular/angular#11105]
Enable strict null checks in `tsconfig.json` in the ngc integration tests, see https://github.com/angular/angular/commit/9ba8e25c14d624d5da78d27bbcb4b958726f9e67, and fix all type errors that show up.

**Comment by alexeagle** [comment]
Here's a PR that mostly works with --strictNullChecks:
https://github.com/angular/angular/pull/11106

**Comment by arlowhite** [comment]
Angular 2.0.0
TypeScript 2.0.2

In my project, when I set **"strictNullChecks":true**, I get a few errors:

> node_modules/@angular/core/src/util/decorators.d.ts(11,5): error TS2411: Property 'extends' of type 'Type<any> | undefined' is not assignable to string index type 'Function | any[] | Type<any>'.
> node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts(25,22): error TS2420: Class 'DomRenderer' incorrectly implements interface 'Renderer'.
>   Types of property 'animate' are incompatible.
>     Type '(element: any, startingStyles: AnimationStyles | undefined, keyframes: (AnimationKeyframe | undef...' is not assignable to type '(element: any, startingStyles: AnimationStyles, keyframes: AnimationKeyframe[], duration: number,...'.
>       Type 'AnimationPlayer | undefined' is not assignable to type 'AnimationPlayer'.
>         Type 'undefined' is not assignable to type 'AnimationPlayer'.

**Comment by alexeagle** [comment]
Fix is pending in https://github.com/angular/angular/pull/11294

**Comment by pgrm** [comment]
I followed the PR which was superceded by another PR which was replaced and enhanced by 2 more PRs, and those last ones were merged. Does it mean compilation with strict null checks works now? and is ist available in Angular 2.x or only 4?

**Comment by alexeagle** [comment]
No, I just checked and we don't have this at HEAD still:
https://travis-ci.org/angular/angular/jobs/191403710
We are planning to allow strictNullChecks in Angular 4. Don't know about back-porting it to 2.

**Comment by DzmitryShylovich** [comment]
@tbosch https://github.com/angular/angular/pull/11106 was merged so i believe this can be closed

**Comment by alexeagle** [comment]
thx
