### ISSUE TITLE
Dependency Injection  Fails: When Extending RouterOutlet (rc5)

### ISSUE THREAD

**Issue by origin1tech** [angular/angular#11118]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When extending RouterOutlet I am unable to inject dependencies as before. No error is thrown however the dependency is undefined. Due to this it in large part makes extended your own custom router outlet less than useful explained below.

**Expected/desired behavior**

Ideally you would inject for example an auth service or other which would allow you to validate the user before routing. If auth fails you redirect to the login for example. This is very useful as it prevents the need to calling canActivate all your components. It's more or less almost like having a global way to "resolve" before rendering as we did in Angular 1.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

I don't believe an example is needed here. create a default directive and extend with RouterOutlet. Try to inject any service into the constructor it will be undefined when using the latest router rc5 or greater.

**What is the expected behavior?**

The service should instantiated using dependency injection.

**What is the motivation / use case for changing the behavior?**

Extending RouterOutlet is largely useless if you cannot access the Router or inject custom services.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X

RC 5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 

Typescript.

**Comment by DavidBanksNZ** [comment]
I as doing the same thing when using RC1, but with RC5 you can now use the new router which has route 'guards' to accomplish the same behaviour. There is no need to extend RouterOutlet anymore :)

**Comment by origin1tech** [comment]
Thanks @DavidBanksNZ you happen to have an example anywhere. 

Man this router deal has me spinning. Every time I turn around I'm refactoring  ha ha.

**Comment by DavidBanksNZ** [comment]
There is a big chapter in the official docs, with a section on guards which shows how to use them to deny access to users who aren't authenticated https://angular.io/docs/ts/latest/guide/router.html#!#guards

**Comment by origin1tech** [comment]
Yeah just found that thx bud....closing.
