### ISSUE TITLE
Implementing a Meta class for getting and changing HTML meta tags

### ISSUE THREAD

**Issue by flauc** [angular/angular#11115]
**I'm submitting a**

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I'd like to implement a shortcut for getting and setting HTML meta values (`<meta name="description">`, <meta name="keywords">`...). 

I think that a long with changing the title it's often useful to change meta values as well.  

**Current behavior**

It's currently possible to use the `getDOM().query('meta[name=description']`)`method to grab the element and then use the`getDOM().setAttribute(el, 'content', 'something')` method to change the content. Therefore this implementation would serve only as a shortcut.

**Expected/desired behavior**

The `Meta` class would be very similar to the[ `Title` Class](https://github.com/angular/angular/blob/2.0.0-rc.5/modules/%40angular/platform-browser/src/browser/title.ts)

It would have a `getMeta()` and a `setMeta()` method. Something like this: 

``` ts
    setMeta(metaName: string, contentValue: string): void {
        const el = getDOM().query(`meta[name=${metaName}]`);
        getDOM().setAttribute(el, metaName, contentValue)
    }

    getMeta(metaName: string): HTMLElement {
        return  getDOM().query(`meta[name=${metaName}]`);
    }
```

And optionally maybe just a method for returning just the content of the meta and not the entire element: 

``` ts
    getContent(metaName: string): string {
        return getDOM().query(`meta[name=${metaName}]`)..getAttribute('content')
    }
```
- **Angular version:** 2.0.0-rc.5
- **Browser:** all
- **Language:** all

**Comment by DzmitryShylovich** [comment]
What about `@MetaBinding` decorator?
