### ISSUE TITLE
Publish closure externs with Angular

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#11119]
tsickle can generate closure externs. For example, I'm trying to use `export declare interface BrowserNodeGlobal` in lang.ts but that gets generated into core.externs.js and common.externs.js and closure compiler errors about the duplication.
I'll try to workaround.

**Comment by DzmitryShylovich** [comment]
@alexeagle facade are gone so I think it can be closed

**Comment by alexeagle** [comment]
yes! thanks for the reminder

**Comment by alexeagle** [comment]
currently required externs are in 
https://github.com/alexeagle/closure-compiler-angular-bundling/blob/master/vendor/angular_testability_externs.js
https://github.com/alexeagle/closure-compiler-angular-bundling/blob/master/vendor/angular_testability_externs.js

**Comment by alexeagle** [comment]
This was done, externs for testability are published in https://github.com/angular/core-builds/blob/master/src/testability/testability.externs.js
