### ISSUE TITLE
AOT compiler shouldn't output template path name in ngfactory files in prod mode

### ISSUE THREAD

**Issue by vikerman** [angular/angular#11117]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

AOT in prod mode produces this snippet in the ngfactory files

```js
function viewFactory_SearchVideos0(viewUtils, parentInjector, declarationEl) {
   if ((renderType_SearchVideos === ((null)))) {
       (renderType_SearchVideos = viewUtils.createRenderComponentType('path/to/template/template.html', 0, import22.ViewEncapsulation.None, styles_SearchVideos, {}));
   }
```

The output contains 'path/to/template/template.html' which ends up in the final bundle even after closure compilation.

Do we really need to output the full template path in prod mode?

**Expected/desired behavior**
No file path output in prod mode.

* **Angular version:** 2.0.0-rc.6
 
* **Language:** [TypeScript]

**Comment by tbosch** [comment]
No, we don't need to do this.
