### ISSUE TITLE
Async binding onto an async dependency should throw an error regardless of dependency resolution

### ISSUE THREAD

**Issue by vicb** [angular/angular#1111]
We have the following pattern in application.js:

```js
      bind(appViewToken).toAsyncFactory(...),

      bind(appChangeDetectorToken).toFactory((rootView) => rootView.changeDetector,
          [appViewToken]),
```

The change detector is bound with a **sync** dependency on the root view while the root view is **async**.

It works because the root view has been instantiated before the change detector is instantiated, as demonstrated with the test added in #1101:

```js
      // expect behavior, was there before 1101
      it('should throw when instantiating a sync binding with an async dependency', function () {
        var injector = new Injector([
          bind(UserList).toAsyncFactory(fetchUsers),
          UserController
        ]);

        expect(() => injector.get(UserController))
          .toThrowError('Cannot instantiate UserList synchronously. It is provided as a promise! (UserController -> UserList)');
      });

      // added in 1101
      it('should not throw when instantiating a sync binding with a resolved async dependency',
        inject([AsyncTestCompleter], (async) => {
        var injector = new Injector([
          bind(UserList).toAsyncFactory(fetchUsers),
          UserController
        ]);

        injector.asyncGet(UserList).then(() => {
          expect(() => { injector.get(UserController); }).not.toThrow();
          async.done();
        });
      }));
```

As demonstrated by the tests above, with the **same DI config**, the behavior is different according to the order in which the classes are instantiated.

While this is easy to understand in a simple example like this one, I believe it could be the source of interim and hard to debug bugs when the dependency graph gets more complex - there could be an error which gets triggered depending on a timing of an async function.

@vsavkin what about throwing an error in such a case ? It would make the behavior reproducible and avoid potential errors.

/cc @juliemr

**Comment by mhevery** [comment]
I agree with @vicb, this should be an error in both cases. The order of instantiation should not make a difference in the injector behavior.

**Comment by vsavkin** [comment]
Totally agree. We should throw an error.

**Comment by mhevery** [comment]
No longer supported. Obsolete.
