### ISSUE TITLE
https://angular.io/docs/ts/latest/tutorial/toh-pt6.html snippet links broken

### ISSUE THREAD

**Issue by VaughanJackson** [angular/angular#11127]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Documentation bug. A number of snippet links from the Angular2 tour of heroes page https://angular.io/docs/ts/latest/tutorial/toh-pt6.html are broken. For example:

app/hero.service.ts (post)

BAD FILENAME: ../../../_fragments/toh-6/ts/app/hero.service-post.ts.md   Current path: docs,ts,latest,tutorial,toh-pt6 PathToDocs: ../../../

I note an issue like this was previously opened and closed - search issues for "BAD FILENAME".

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ericmartinezr** [comment]
Hey @VaughanJackson would you mind re-opening this in https://github.com/angular/angular.io ? Where the website/tutorial lives. Note also that there seems to be a fix (https://github.com/angular/angular.io/pull/1929) for that but the issue is still there, so they will tell you what's going on :P

**Comment by VaughanJackson** [comment]
Closing this misplaced issue. Thank you @ericmartinezr. I have now opened angular.io issue https://github.com/angular/angular.io/issues/2213 to replace this one.
