### ISSUE TITLE
Advice/guidelines - optimized bundling strategies

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#11128]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] guidelines request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
This is a request for some guidelines on production bundles. I have experimented with a few approaches, but I would love to see some input from the Angular team on how to generate optimized bundles for realistic sample applications. 

One of the concerns I have is that https://github.com/angular/angular/issues/10618 seems to have been pushed to "post final". rc.5 gave us a lot of cool things, but unfortunately we can no longer mangle our code as part of minification. 

Tree shaking is awesome, but from what i can tell, the biggest, most reliable size reduction comes from minify/mangle (uglify terminology).   

I have done an experiment on my sample application where I minify and tree shake the application. My observation is that tree shaking + minify (without mangle) gets me to 333k, but with mangle added I end up at roughly 200k, which is a significant reduction. These are gzipped numbers btw.
You can see my bundle.js here: http://www.syntaxsuccess.com/angular-2-samples/#/demo/spreadsheet 
My application is not huge. Probably a medium size app, but it uses a fair amount of Angular since the point of the app is to explore the different features of Angular 2. 

Granted I am doing tree shaking without ahead of time compilation (AOT), which may reduce the effectiveness of tree shaking. AOT is one suggested workaround to get mangle to work, but I am doing this without AOT to establish a baseline since AOT is not feasible in all environments.  

One example where AOT is not supported yet is `ngUpgrade`.

I am sharing my results because I would like to compare notes with others who may have gone through similar experiments.

I know the Angular team has worked very hard and achieved amazing results wrt bundle sizes, but it seems like the mangling issue introduced in rc.5 may reduce some of the net benefit in common use cases like `ngUpgrade`.

I am asking for bundling guidelines from the Angular team since it's perfectly possible that my approach of using rollup is not optimally configured. 

My current approach is to transpile the original TypeScript to ES15 before running rollup and minify (without mangle).

Perhaps this can be optimized to shake out even more.   In that case my point is perhaps moot :-)

Otherwise I hope the mangling bug introduced in rc.5 gets prioritized for final.

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in rc.6. Function name mangling problems are resolved there.

You will however need AOT if you want to mangle properties. There is no way around that.

AOT support for ngUpgrade is being investigated and I expect it to land in one of the future releases.

**Comment by thelgevold** [comment]
Thanks @IgorMinar - Closing this issue
