### ISSUE TITLE
Feature Request: @Pipe should perform type checking

### ISSUE THREAD

**Issue by aluanhaddad** [angular/angular#11126]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The following code produces no TypeScript compile errors

``` TypeScript
import { Pipe } from '@angular/core';

@Pipe({ name: 'toLocaleUpper' }) 
export class ToLocaleUpperPipe {
    trnsform(value: string) { // typo -> runtime error
        return value.toLocaleUpperCase();
    }
}
```

**Expected/desired behavior**

The above code should produce the following error

``` powershell
error TS2345: Argument of type 'typeof ToLocaleUpperPipe' 
is not assignable to parameter of type 'new (...args: any[]) => PipeTransform'.
Type 'ToLocaleUpperPipe' is not assignable to type 'PipeTransform'.
Property 'transform' is missing in type 'ToLocaleUpperPipe'.
```

**What is the motivation / use case for changing the behavior?**
It is trivial for the decorator to check that its argument implements the `PipeTransform` interface. TypeScript excels at these kinds of structural checks and they should be leveraged to improve tooling.

Here is what a more robust Pipe DecoratorFactory's signature could look like

``` TypeScript
export declare const Pipe: (metadata: PipeMetadataType) => 
    <T extends new (...args) => PipeTransform>(target: T) => T;
```

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4/rc.5
- **Language:** TypeScript

**Comment by manumiranda** [comment]
Hi, I've been working on this feature and 
I am having problems creating the test case because I don't know what is the testing procedure for compile time errors and I have not been able to find any sample in the existing code base... 

What should I use? Should I add a new dev dependence? 

Thanks in advance.

**Comment by JoostK** [comment]
Ivy's template type checker is capable of checking pipes, if `fullTemplateTypeCheck`/`strictTemplates` is enabled.
