### ISSUE TITLE
Replace Observable with AsyncSubject in XHRConnection.response

### ISSUE THREAD

**Issue by ettoredn** [angular/angular#11122]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the current implementation each time an Observer subscribes to the Observable returned by Http methods (thus Connection.response), the HTTP request is executed again because the Observable is executed again.

**Expected/desired behavior**
Add the option to return an AsyncSubject instead so that only the last value is returned without executing the HTTP request again. If a consumer wants to execute the same request again, it can (should?) create a new Connection.

**Reproduction of the problem**
let o = http.get('url');
o.subscribe(); // makes the HTTP request and returns the Response
o.subscribe(); // makes the HTTP request and returns the Response

**What is the expected behavior?**
let o = http.get('url');
o.subscribe(); // makes the HTTP request and returns the Response
o.subscribe(); // returns the previous Response

**What is the motivation / use case for changing the behavior?**
Multiple Observers subscribing to the same Response waiting for it to Observable.complete(). They also expect to get the same value and that is not currently the case as each Subscriber may get different values.

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** all 
 
* **Language:** TypeScript 2.0.0

**Comment by DzmitryShylovich** [comment]
You can easily achieve what you want by using [.share()](http://blog.thoughtram.io/angular/2016/06/16/cold-vs-hot-observables.html#caveat-http-with-observables) operator which is much more flexible solution.

**Comment by ettoredn** [comment]
FYI even using .share() it still sends two HTTP requests instead of one (and I do some 20+ .subscribe on the returned Observable). I'm not going to investigate the issue as wrapping the whole thing with an AsyncSubject works exceptionally well and appears to be even more performant for whatever reason.

**Comment by zoechi** [comment]
@ettoredn I assume this is because the 2nd subscription is made before the response from the first one arrives. See also http://stackoverflow.com/questions/36271899/what-is-the-correct-way-to-share-the-result-of-an-angular-2-http-network-call-in

**Comment by ettoredn** [comment]
Yes, it is the second.
Your Stackoverflow solution could be improved by instantiating an AsyncSubject when a class instance is created and returning the AsyncSubject for every call made to the service. The AsyncSubject is .next()'ed and .complete()'ed when the Http observable is completed.
This is the approach I ended up using.

**Comment by zoechi** [comment]
@ettoredn you could add your own answer. I don't really know observables and never saw AsyncSubject. I use only Dart (which has streams) and TS only for SO answers. I created the answer only out of curiosity about how Angular with TS and RX works.
