### ISSUE TITLE
Router: Cannot redirect in CanActivate on app initial load

### ISSUE THREAD

**Issue by shantmarouti** [angular/angular#11131]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

**Current behavior**
```typescript
export class AuthGuard implements CanActivate {
  constructor(private router: Router) {}

  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    this.router.navigate(['/login']);
    return false;
  }
}
```

> when we navigate from one route to the one which have 'CanActivate' guard, everything works fine, but when app loads for the first time router does not redirect 

for example:
we have '/home' , '/dashboard' and '/login' routes.
dashboard route have a CanActivate guard
in the CanActivate we redirecting to '/login'

when we navigate from '/home' to '/dashboard' router redirects to '/login' route
but when directly entering '/dashboard' in the browser, router does not navigate to '/login'

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [ all ] 
 
* **Language:** [ TypeScript 2.1.0-dev.20160721 ]

**Comment by shantmarouti** [comment]
solved in rc.6

**Comment by IngenieroFiestero** [comment]
You need to define the starter route in the last position of the list of routes (or after the redirect route) because when the app is started it only search for the starter route in the list and if it´s in the last position then angular will preload all the preceding routes.

This should work:
```
const routes: Routes = [
  { path: 'login', component:  SigninComponent},//LOGIN
  { path: '**', redirectTo: '/login'},//Redirect to LOGIN
  { path: '', component:  DashboardComponent, canActivate : [AuthGuard]}
];
```
