### ISSUE TITLE
Angular 2.0.0-rc5: Changing a chained pipe's parameters doesn't invoke pipes down-chain

### ISSUE THREAD

**Issue by haemaenpaa** [angular/angular#11138]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

[Reproducing plunker](http://plnkr.co/edit/CvWZkAoUhGeRQQL5Pc12)

I have the following template

   ```
<table class="table50">
  <thead class="table_header">
    <tr>     ...
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let theUser of users | sort: [ sortField, sortAscending ] | paginate: [ pageNumber-1, pageSize ] ">
      <td>{{theUser.id}}</td>
      ...
    </tr>
  </tbody>
</table>
<form *ngIf ="users && users.length>pageSize">
  <input type="number" min="1" max="{{numPages()}}" [(ngModel)]="pageNumber" name="pg">/{{numPages()}}
</form>
```

I use `(click)` to bind clicks on the table header to a single function that changes `sortField` and/or `sortAscending`, and calls `detectChanges()` on an injected `ChangeDetectorRef`. I added a few calls to `console.log` into the two pipes' `transform`  functions, and I noticed that when I click on the header, only the `sort` pipe's `transform` gets called, and when I change the `pageNumber`, only the `paginate`'s `transform` gets called.

`sort` is a quicksort, `paginate` outputs the `pageNumber`-th block of `pageSize` objects in the input array.

**Expected/desired behavior**

Changing the parameters of `sort` should count as changing the parameters (namely input) of all pipes down-chain of it, and cause them to be re-run.

**What is the motivation / use case for changing the behavior?**

Currently, changing the parameters of a pipe in the middle of a chain does not change the output seen by the user. I find this counterintuitive, and I currently have to work around this.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** Firefox 45.3.0 (Windows 7) and 48.0 (Linux mint)
 
* **Language:** TypeScript 1.8.10

**Comment by vicb** [comment]
needs a repro case

**Comment by haemaenpaa** [comment]
Plunker here: http://plnkr.co/edit/CvWZkAoUhGeRQQL5Pc12

**Comment by vicb** [comment]
steps to reproduce ?

**Comment by haemaenpaa** [comment]
1. Click on one of the column header. Table's contents don't change, "sort" is printed to the console. Expected result is that the table's contents are sorted according to the corresponding column's value (or in reverse order if they already were), and "sort" and "paginate" are printed to the console.
2. Adjust the spinner's value up by one. The table's contents change, "paginate" is printed to the console, contents are now sorted as stated above, starting from the 21st. in order.
3. Set the spinner's value back to 1. The table's contents change, and are now sorted as per step 1. The pipes' arguments are now (at least according to my understanding) what they were after step 1.

**Comment by vicb** [comment]
So you have: `array | sort | paginate`

`sort` and `paginate` are pure.

when you click on an header, the output of `sort` does not change (it is still a reference to the same array even though the array is now sorted). `paginate` still has the same input (the ref to the array) and parameters, the output is considered the same so change detection does not run.

You can verify this by changing your `sort` code to `return tool.array.slice();` which creates a new array and trigger the change detection, everything works as expected.

Solutions:
- return a new array,
- mark the pipes as non pures,
- trigger the change detection by hand on sort / paginate.
