### ISSUE TITLE
<router-outlet></router-outlet> Duplicates HTML

### ISSUE THREAD

**Issue by drpain** [angular/angular#11132]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I created a component nav-header which is meant to contain my <header> code. And to ensure that this is maintained across my application. When I use the ``<router-outlet></router-outlet>`` it duplicates the body of my application component where called. 

For instance if I call the ``<router-outlet></router-outlet>`` in the nav-header component, it duplicates and inserts the application component in the nav-header component. 

**Expected/desired behavior**
That it doesn't duplicate the code :-)

**Reproduction of the problem**
You can have a look at my application here, in particular these files:
[Application Component](https://github.com/drpain/ThatGuy-Angie/blob/master/app/app.component.ts)
[Application Modules](https://github.com/drpain/ThatGuy-Angie/blob/master/app/app.module.ts)
[Header Navigation Component](https://github.com/drpain/ThatGuy-Angie/blob/master/app/nav-header.component.ts)

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
``3.19.0-65-generic #73~14.04.1-Ubuntu SMP`` AMD64

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome Latest | Firefox Latest ] 

* **Language:** [TypeScript 1.8.10]

**Comment by sirajc** [comment]
@drpain This happens when you mess with Routes, correcting them resolves the issue. Can you provide a plunker with repro

**Comment by drpain** [comment]
Hi @sirajc,

I tried to create a plunker, but I can't seem to get it to run. I will try again tonight after work. In the meanwhile, do you perhaps know of any tutorials on how to create a navbar in AngularJS 2, the "AngularJS 2 Way"? 

It has been quite a jump from AngularJS 1, and I wasn't able to find good documentation on the subject.

Cheers,
Rudi

**Comment by drpain** [comment]
@sirajc:

Cool I got the plunker up and running. It's using the tutorial as found on Angular.io, which I have started to modify:
[https://plnkr.co/edit/ub1dZgVUzrpLb4NU5EB4](https://plnkr.co/edit/ub1dZgVUzrpLb4NU5EB4)

**Comment by skreborn** [comment]
@drpain Your `App` component actually contains a `<my-heroes>` element (along with a `<router-outlet>`).

    <nav-header></nav-header>
    <div class="container">
      <h1>{{title}}</h1>
      <my-heroes></my-heroes>
    </div>
    <nav-footer></nav-footer>
    <router-outlet></router-outlet>

Modifying it to only have the `<router-outlet>` solves your problem, so this is indeed an issue with your code, and not the Angular framework.

    <nav-header></nav-header>
    <router-outlet></router-outlet>
    <nav-footer></nav-footer>

Here's the working plunker, too: https://plnkr.co/edit/dmdhgZ0yKHXRPSwHv0CA?p=preview

**Comment by sirajc** [comment]
@drpain I have created a navbar implementation which you can refer https://github.com/sirajc/angular2-bs4-navbar

Also, do checkt https://github.com/angular/angular/blob/master/CONTRIBUTING.md before creating an issue

**Comment by drpain** [comment]
@skreborn Thanks for looking over and confirming. The documentation didn't give a clear indication of what <router-outlet></router-outlet> does.

How does Angular know what else to print out? I am confused as hell. Should router-outlet always be at the appcomponent?

What would the correct approach be?

**Comment by drpain** [comment]
@sirajc Awesome thanks I will check it out for a reference.

**Comment by EdwinDennis** [comment]
I have the same problem , anyone know how to fix it ?

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781446/b2ad919c-b7bd-11e6-9929-e30dae22e371.png)
