### ISSUE TITLE
AOT module import with logic in setRoot call fails

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#11133]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
I think there is a bug with the aot compiler when trying to import a module in combination with a `forRoot` method with more logic than a simple return statement. 

If the `forRoot` function does anything more than the return statement of the `ModuleWithProviders` object ngc will error out with the message:

```
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
```

The use case here is to try to build the `ModuleWithProviders` object dynamically based on input to `setRoot`

**Reproduction of the problem**
Here is some sample code:
```
@NgModule({})
export class TestModule {
  static forRoot(): ModuleWithProviders {

    let providers = [];  //building providers dynamically fails

    return {
    ngModule: TestModule,
    providers: providers
    };
  }
}

@NgModule({
  imports: [TestModule.forRoot()],
  declarations: [AppComponent],
  
  bootstrap: [AppComponent]        
})
export class AppModule {
}

```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5

**Comment by Fank** [comment]
@thelgevold did you find a solution for it? or why did you close this issue?

**Comment by lexigren** [comment]
I have same problem with UIRouterModule
So, what can be done?
