### ISSUE TITLE
Tour of Heroes broken references

### ISSUE THREAD

**Issue by jzissu** [angular/angular#11148]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When going through the Tour of Heroes, everything is fine until the last section (HTTP). When looking for the code to add/change, there are multiple places where the following is being displayed in the page instead of the code snippets or files:

> BAD FILENAME: ../../../_fragments/toh-6/ts/app/hero.service-post.ts.md   Current path: docs,ts,latest,tutorial,toh-pt6 PathToDocs: ../../../

This one in particular is for the Post section of "Add, Edit, Delete" but there are instances of this all over the page from this point on. It looks like the reason for this is that the code has changed from the original and is now pointing at code that is no longer used. For example, for this Post section (and the Put and Save sections), the code that is shown in the overall file displayed later uses Create and Update methods which are never referenced in the tutorial, instead of Post/Put methods or a Save method which are all referenced there.

**Expected/desired behavior**
Code snippets and/or files are supposed to display correctly in the page so the user can follow the tutorial.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

1) Go to https://angular.io/docs/ts/latest/tutorial/toh-pt6.html in the browser.
2) Scroll down about 1/4 of the page from the top to the "Add, Edit, Delete" section of the tutorial.
3) Note the code snippet for the Post section doesn't come up as expected.

**What is the expected behavior?**
Seeing the code snippets or files so the user can follow along.

**What is the motivation / use case for changing the behavior?**
Learning Angular2 shouldn't involve troubleshooting the web pages where you are learning...

**Please tell us about your environment:**

* **Angular version:** n/a
 
* **Browser:** [all] 
 
* **Language:** n/a

**Comment by ericmartinezr** [comment]
Hey @jzissu , this issue was reported over here https://github.com/angular/angular.io/issues/2213 (angular.io is the repo for the website/tutorial)

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !

**Comment by jzissu** [comment]
Okay thanks, I'll subscribe to that issue and make comments there.
