### ISSUE TITLE
Error while generating new project - vagrant ubuntu/trusty64

### ISSUE THREAD

**Issue by Arth95** [angular/angular#11147]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I try to create new project angular-cli throws this error:
`ENOENT: no such file or directory, chmod '/vagrant/forecastify/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-sign'
Error: ENOENT: no such file or directory, chmod '/vagrant/forecastify/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-sign'
    at Error (native)`

**Expected/desired behavior**
Successfully generated project

**Please tell us about your environment:**
I use Vagrant with ubuntu/trusty64 box (Ubuntu 14.04) on Windows 8.1
This is my shell script:
`sudo apt-get install -y curl;
sudo apt-get update;
sudo apt-get install -y build-essential;
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -;
sudo apt-get install -y nodejs;
sudo apt-get install -y npm;
npm config set registry http://registry.npmjs.org/;
sudo npm install -g npm;
sudo npm install -g angular-cli;`
* **Angular version:** 2.0.0-rc.5

**Comment by ericmartinezr** [comment]
Hey @Arth95 would you mind re-opening this issue over angular-cli's repo? https://github.com/angular/angular-cli

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr !
