### ISSUE TITLE
Condition on  router-outlet not working on router 3.0.0-rc.1

### ISSUE THREAD

**Issue by lrezmeri082015** [angular/angular#11142]
**I'm submitting a Bug report  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I cannot add a condition on  router-outlet, it worked until now using the router-deprecated.
Ex:  &lt;router-outlet *ngIf="loaded"&gt;&lt;/router-outlet&gt;

**Expected/desired behavior**
The router-outlet should be activated once the condition is satisfied. Currently I'm getting an error because router-outlet cannot be found.

**Reproduction of the problem**
&lt;router-outlet *ngIf="loaded"&gt;&lt;/router-outlet&gt;

**What is the expected behavior?**
It should be backward compatible, I don't want to rewrite all the code for every release.

**What is the motivation / use case for changing the behavior?**
Load the component once all the validations passed. I don't want to move all the internal logic at the routing level.

**Please tell us about your environment:**
Windows 7, Visual Studio 2015, Web Api

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
ALL 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
TypeScript

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/11100#issuecomment-242827341

**Comment by lrezmeri082015** [comment]
Why the deprecated version worked? I'm not happy with the response, I'll use  RC4 and router-deprecated until this bug is fixed on RC5.

**Comment by brandonroberts** [comment]
If you want to perform some action before the route is loaded, use a [guard](https://angular.io/docs/ts/latest/guide/router.html#!#guards)

**Comment by MarkPieszak** [comment]
@lrezmeri082015 It might be for the same reason ngIf and ngFor can't be on the same element at the same time. Try wrapping router-outlet with a div using `[hidden]="!loaded"`, if you want to stay with the current way you're doing it.

Better yet, using Guards, is ultimately the best solution as brandon suggested.

**Comment by lrezmeri082015** [comment]
This is still creating my component, it's not rendered but it's still there. I have a security service that needs to be loaded before actually doing anything. Based on the security the user is going to be redirected to a different page.

@brandonroberts how can I use the guard? I've tried this but the data is loaded async and CanActivate is always false. Also I should define this on all the routes instead of just using a boolean.

**Comment by brandonroberts** [comment]
@lrezmeri082015 guards can handle async requests. You can return an Observable that resolves to a boolean, or a Promise that resolves to boolean, or you can just return a boolean. 

From within the guard you can inject the router and navigate somewhere else, which will effectively cancel the previous navigation. Its covered in the router guide.

**Comment by newsash** [comment]
Is there an easy way to achieve the same behavior as in the example below, which worked well in beta?
``` html
<div class="container" *ngif="!user || !user.loggedIn">
    <login-form></login-form>
</div>
<top-bar *ngif="user?.loggedIn"></top-bar>
<div class="container body-content">
    <router-outlet *ngif="user?.loggedIn"></router-outlet>
</div>
```

**Comment by brandonroberts** [comment]
@newsash use the `CanActivate` guard to protect the routes instead of a conditional outlet.

**Comment by newsash** [comment]
@brandonroberts how can I automatically ("setup once and forget") apply the guard to all routes (except login page) including all child routes in all modules (including not yet existing)?

**Comment by brandonroberts** [comment]
@newsash you can have a component-less route with a guard on it and all your routes except `login` under it.

```ts
[
  {
    path: 'login', component: LoginComponent
  },
  {
    path: '',
    canActivateChild: [AuthGuard]
    children: [
      { path: home, component: Home },
      { path: about, component: About }
    ]
  }
]
```

**Comment by vsavkin** [comment]
As @brandonroberts pointed out, a guard should be used to handle this use case. Closing this issue.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
