### ISSUE TITLE
Sanitize: Allow for custom RegExp

### ISSUE THREAD

**Issue by voliva** [angular/angular#11158]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using _vulnerable_ features like setting a url in a style attribute such as background-image, with custom values that by extension are safe, get rejected because of the Sanitizer detects them as unsafe.

**Expected/desired behavior**
We should have a way to edit the Sanitizer's RegExp, so we can use our own Sanity checks.

**What is the motivation / use case for changing the behavior?**
Although it opens a new vulnerability for non-experienced devs if they change the approved-by-everyone safe RegExp for a vulnerable one, it gives more responsability to the developer.
Imagine one simple case: for [style.background-image], we want to provide a placeholder image just in case the URL we want to show is not available / gets a load error.

The current sanitizer's RegExp is: `/^url\(([^)]+)\)$/`. This RegExp allows for a single url value, such as:
````
<div [style.background-image]="'url(' + myImage + ')'"></div>
````
But that RegExp prevents us from using:
````
<div [style.background-image]="'url(' + myImage + '), url(./path/to/placeholder.png)'"></div>
````
Although if the first one is safe, then the second one should be safe as well.

I was thinking about submiting an Issue + PR for changing that RegExp for one that fits this need, but then I thought... Maybe it'd be better if the API allowed to set custom RegExp for sanitizer checks.

**Comment by zoechi** [comment]
Not tried myself but I'm pretty sure you can provide your own sanitizer this way
```ts
{provide: DomSanitizer, useClass: CustomDomSanitizer},
```

(was recently renamed from `DomSanitizerService` AFAIR)

**Comment by vicb** [comment]
> `{provide: DomSanitizer, useClass: CustomDomSanitizer},`

Should definitely be the way to go - too easily to shot yourself in the foot with the initial request.

I have left this issue open so that multiple url support is added. /cc @mprobst

**Comment by mprobst** [comment]
+1, I think it makes more sense to contribute to the one, shared API so that everybody gets a better DOM sanitizer (that e.g. supports multiple `url()`s). Custom regular expressions are surprisingly easy to get wrong, for example by forgetting to anchor them.

You could also implement your own DOM sanitizer if you really have a very custom, specific use case, but the `url()` issue you mention here really should just be fixed in Angular itself.

**Comment by voliva** [comment]
@mbprost @vicb I see your point, and it's pretty understandable. As I said... it would create a vulnerability for unexperienced (or just distracted) developers. Also I didn't think about what would happen if the _default_ DOM sanitizer runs a check before it's set to a new one... Nasty bug-prone!

I like the provider solution by zoechi for quick custom Sanitizers. I think that's enough to resolve the use case I have presented.

Should I create a new issue for "improving" the Style DomSanitizer RegExp, or can we just reuse this one?

**Comment by vicb** [comment]
> Should I create a new issue for "improving" the Style DomSanitizer RegExp

yes, please. bonus points if you attach a plunker !

Thanks
