### ISSUE TITLE
regex in Validators.pattern breaks but works fine in html tag as attribute

### ISSUE THREAD

**Issue by istiti** [angular/angular#11159]
Hi in rc5 I'm using data-driven approach to do my form...
The problem is when I put my regex inside input as attrbiute pattern="" it works fine but when using Validators.pattern() method with string regex as param my input is never validate

This is my code
`Validators.pattern("https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)")`

Am I doing something wrong ?  I validate here an URL but with email regex it won't works too !

**Comment by istiti** [comment]
Someone say me I have to add an extra \ to my \'s as it's using a regex constructor function

Strange but works !

**Comment by jlsuarezs** [comment]
Can you show your solution? Thanks.

**Comment by tytskyi** [comment]
@jlsuarezs if you pass the string - you need to pass it escaped as for `RegExp` constructor.

Look at the implementation - https://github.com/angular/angular/blob/81925fa66d2c930f68d3b6dd084c954ea1bab6b6/packages/forms/src/validators.ts#L142-L161

**Comment by marekdano** [comment]
This pattern works for me
`Validators.pattern("https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*)")`
