### ISSUE TITLE
Zones

### ISSUE THREAD

**Issue by vicb** [angular/angular#1116]
Some questions / remarks that come from working on async tests.

### Current Angular2 setup ([vm_turn_zone.dart](https://github.com/angular/angular/blob/master/modules/angular2/src/core/zone/vm_turn_zone.dart))
- The inner zone overrides `run()`, function execution are wrapped in `_onRunBase()`
- `_onRunBase()` executes:
  - `_onTurnStart()`
  - the wrapped function
  - `_onTurnDone`

### Potential issue
~~When the wrapped function enqueues a microtask (Future, Obervable objects) the sequence will be:~~
- `_onTurnStart()`
- fn -> enqueues microtasks
- `_onTurnDone()` which triggers the change detection
- ~~drain the microtask queue **the change detection is not triggered**~~

Turns out that the current code is fine, the actual sequence is:
- `_onTurnStart()`
- fn -> enqueues microtasks
- drain the microtask queue 
- `_onTurnDone()` which triggers the change detection

_(I had overridden `scheduleMicrotask` in my test code which is why the sequence was wrong)__

### refs:
- https://www.dartlang.org/articles/zones/
- https://www.dartlang.org/articles/event-loop/

### Current Angular2 setup ([vm_turn_zone.es6](https://github.com/angular/angular/blob/master/modules/angular2/src/core/zone/vm_turn_zone.es6))

- `_onTurnStart()` is called from the `beforeTask` hook,
- `_onTurnDone()` is called from the `afterTask` hook.

### Issue

The `beforeTask` / `afterTask` hooks are called for every single function which is executed in a zone, should it be from microtask or macrotask queue.
Check https://github.com/angular/zone.js/issues/59 for more details: if there are 3 microtasks pending, the change detection will be triggered after each of those.

### Fix

We should come with a way to detect VM turns which is currently not possible with zone.js.
A VM Turn consist of **one** macrotask + 0 to many microtasks.

## resources

https://docs.google.com/document/d/1qFfHwYCOLpLuTap_l6TCEaU4I0C-pVFVbTl2o4-XbUo/edit?usp=sharing has some interesting links on the last page

I'll update the issue as I progress.

/cc @mhevery @vsavkin @btford @yjbanov - feel free to comment here, chat on hangout about this.

**Comment by mhevery** [comment]
Related to #1224

**Comment by naomiblack** [comment]
@vicb any status?

**Comment by vicb** [comment]
Closer than ever :)

I'm currently working on zone.js with the help of @IgorMinar and @btford to get v0.5.0 out. There are a few bugs that are still resists but I'm about to kill them (hopefully). 

We should have something early next week.

**Comment by vicb** [comment]
fixed via #1574
