### ISSUE TITLE
QueryEncoder encodes equal [=] as semicolon [;]

### ISSUE THREAD

**Issue by hekutoc** [angular/angular#11164]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
 
**Current behavior**
QueryEncoder replaces equals char (=) with semicolon char (;)
 
**Expected/desired behavior**
QueryEncoder replaces equals char (=) with same char (=)
 
 
**Reproduction of the problem**

let q = new QueryEncoder();
let text = q.encodeValue("a=b");

**What is the expected behavior?**
text to equal "a=b" 
 
 
**What is the motivation / use case for changing the behavior?**
 
 
 
**Please tell us about your environment:**
 
* **Angular version:** 2.0.0-rc.5 , @angular/http@2.0.0-rc.5
* **Browser:** [all]
 
* **Language:** [all]

**Comment by skreborn** [comment]
This has been fixed by [a commit](https://github.com/angular/angular/commit/75553200c00b7e4f32dc1c912a0b6b99c1eb5d3e) 4 days ago.

**Comment by vicb** [comment]
thanks @skreborn.
will be delivered in RC6 in a few days
