### ISSUE TITLE
migration RC4 -> RC5 troubleshooting

### ISSUE THREAD

**Issue by kosiakMD** [angular/angular#11162]
**main.ts:**
`import { bootstrap } from '@angular/platform-browser-dynamic';`
`import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';`
`import { AppModule } from './app.module';`
`import { disableDeprecatedForms, provideForms } from '@angular/forms';`
`platformBrowserDynamic().bootstrapModule(AppModule);`

**app.module.ts**
`

> import { NgModule }      from '@angular/core';
> import { BrowserModule } from '@angular/platform-browser';
> 
> import { RouterModule }  from '@angular/router';
> 
> import {AppComponent}    from './app.component';
> 
> import {APP_ROUTER_PROVIDERS}  from './app.routes';
> 
> import { PartiesFormComponent } from './imports/parties/parties-form.component';
> 
> @NgModule({
> 	declarations: [
> 		AppComponent,
> 		// PartiesListComponent,
> 		// PartyDetailsComponent,
> 		PartiesFormComponent
> 	],
> 	bootstrap:    [AppComponent],
> 	imports:      [
> 		BrowserModule,
> 		/* Router*/
> 		RouterModule.forRoot(APP_ROUTER_PROVIDERS),
> 	],
> 	providers:   [
> 		APP_ROUTER_PROVIDERS
> 	]
> 
> })
> export class AppModule { }

`

**app.components.ts**
`

> import { Component } from '@angular/core';
> 
> import { PartiesListComponent } from './imports/parties/parties-list.component';
> 
> import template from './app.component.html';
> 
> @Component({
> 	selector: 'app',
> 	template,
> 	directives: [
> 		PartiesListComponent,
> 	]
> })
> 
> export class AppComponent {}

`

**app.routes.ts:**
`

> import { RouterConfig, provideRouter } from '@angular/router';
> 
> import { PartiesListComponent } from './imports/parties/parties-list.component';
> import { PartiesFormComponent } from './imports/parties/parties-form.component';
> 
> const routes: RouterConfig = [
> 	{ path: '', component: PartiesListComponent},
> 	// { path: 'party/:partyId', component: PartyDetailsComponent },
> 	// { path: 'edit/:partyId', component: PartyEditComponent },
> 	{ path: 'new', component: PartiesFormComponent},
> ];
> 
> export const APP_ROUTER_PROVIDERS = [
> 	provideRouter(routes)
> ];

`

**HAVE:**
`Invalid route configuration: Array cannot be specified`

**Comment by kosiakMD** [comment]
Resolved by
add into **app.routes.ts**

> import { ModuleWithProviders }  from '@angular/core';
> import { /*RouterConfig,*/ /*provideRouter,*/ Routes, RouterModule } from '@angular/router'; 
> export const routing: ModuleWithProviders = RouterModule.forRoot(appRoutes);

**Comment by skreborn** [comment]
This isn't a support forum. GitHub issues are for bug reports and feature requests. Please consider moving this discussion to [an appropriate channel](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).

**Comment by kosiakMD** [comment]
Thx
Transfered to http://stackoverflow.com/questions/39227301/migration-rc4-rc5-troubleshooting/39227320#39227320
