### ISSUE TITLE
[feature] NgComponentOutlet

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#11168]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
None

**Expected/desired behavior**
A directive that is able to create components dynamically, the same way as `NgTemplateOutlet` created embedded view dynamically.
#### Pros
- Remove the boilerplate in a component. Developer does not need to query (`ViewChild`) and manually create the component. (`ComponentFactoryResolver`, `ViewContainerRef`)
- Expressed in the template.
- Simple
- Aligned with NgTemplateOutlet, same idea same concept
#### Cons
- Host attribute bindings are not expressed in a template. Not much of a con, as its expected and `ComponentRef` can be used to set values on the instance...
- Getting a reference to the returned `ComponentRef` is via callback only.
- more ?

**Directive**

``` ts
@Directive({
  selector: '[swapCmp]'
})
export class SwapComponentDirective {
  private component: any;

  constructor(private cfr: ComponentFactoryResolver,
              private vcRef: ViewContainerRef,
              private tRef: TemplateRef<Object>) {
  }

  @Input() swapCmpBindings: ResolvedReflectiveProvider[];
  @Input() swapCmpInjector: Injector;
  @Input() swapCmpProjectables: any[][];

  @Output() onCreate: EventEmitter<ComponentRef<any>> = new EventEmitter<ComponentRef<any>>(false);

  @Input() set swapCmp(component: any) {
    this.component = component;
    this.vcRef.clear();
    if (this.component) {
      let injector = this.swapCmpInjector || this.vcRef.parentInjector;

      if (Array.isArray(this.swapCmpBindings) && this.swapCmpBindings.length > 0) {
        injector = ReflectiveInjector.fromResolvedProviders(this.swapCmpBindings, injector);
      }

      const cmpRef = this.vcRef.createComponent(
        this.cfr.resolveComponentFactory(component),
        this.vcRef.length,
        injector,
        this.swapCmpProjectables
      );

      cmpRef.changeDetectorRef.detectChanges();

      this.onCreate.emit(cmpRef);
    }
  }
}
```

```
 <template [swapCmp]="ctx.component" [swapCmpBindings]="ctx.bindings"   [swapCmpInjector]="ctx.injector" [swapCmpProjectables]="ctx.projectableNodes"></template>
```

> The name here is SwapComponent but it just as an example, took it from my [code base](https://github.com/shlomiassaf/angular2-modal/blob/master/src/components/angular2-modal/components/swap-component.directive.ts)
- A Developer provides a component, changing the component will re-create.
- Injector is optional, if not supplied the current injector is used.
- Bindings are used to allow additional providers to the injector (something like `viewProviders`)
- In case `ng-content` is needed the developer can supply projectableNodes.

What do you think?

**Comment by shlomiassaf** [comment]
@vicb If approved I'd like to take it.
I already have the code in my project, just decide on naming and add unit tests.

I did the a PR on `NgTemplateOutlet` so it should be a simple task.

**Comment by mlc-mlapis** [comment]
Yes, it is a good proposal and should be included in the core. Everybody can write the same on his own of course but it so general and a repetitive thing that should be standardized. Also many newcomers will appreciate this way.

**Comment by mhevery** [comment]
@shlomiassaf Please don't use `facade` any more. We are in process of removing it, you will only create more work for us later.

I think this is a reasonable feature request. Please feel free to create a PR for this.

**Comment by shlomiassaf** [comment]
@mhevery Didn't know it is getting removed. Just wanted to stick with the standard in this project.

So `Array.isArray` or facade replacement?

**Comment by vicb** [comment]
`Array.isArray` thanks

**Comment by joelrich** [comment]
@shlomiassaf have you seen my feature request #9599? I think what's missing here is that you can also dynamically set properties and event listeners. It should allow to write something like this:

```html
<template
	[ngComponentOutlet]="type"
	[ngComponentProperties]="properties"
	[ngComponentEvents]="events"></template>
```

with:

```javascript
properties = {a: 1, b: 2};
events = {click: e => alert('click')};
```

What do you think?

**Comment by shlomiassaf** [comment]
@joelrich I think it's a powerful addition but it also add's complexity.

Setting the properties and listening to events is something you can achieve in the current implementation by listening to the `ngOutletCreated` event and then using the `ComponentRef.instance` to set properties or register to event streams.

This is, however, done programatically and properties are not bound, change detection will not trigger when an assigned property has change.

Using the proposed declarative syntax might cause confusion as it will **not** support change detection as well. It will be just a sugar/helper for setting those properties and events, as described above, by the `NgComponentOutlet` directive.
The confusion is caused by the developer setting the properties/events in the template which he might think are now bound but their not.

To support bindings the template must reflect properties/event explicitly on the component element so the compiler can create the appropriate component factory class (ngFactory). This is not possible since the component is not known and might change...

Since this feature is supported in the current implementation (by doing some programatic work) I think that for the first iteration of this feature we might want to keep it simple.
After it's approved we can consider adding it.

This is my opinion, I might have missed something about being able to support binding, would love to get corrected if so :)

We already have a blocker for this PR in #12121 due to the need to support sugar syntax but not being able to use `@Output` so it takes longer then I expected...

@vicb Any thoughts on this?

**Comment by joelrich** [comment]
@shlomiassaf I fully agree that change detection would have to work. As far as I understand, at least four (but maybe more) cases would have to be supported:

1. The object itself changes
2. A property value of the object changes
3. A property is added to the object
4. A property is removed from the object
5. Optional: A property getter value changes

The first case should be easy to implement with `ngOnChanges`. For 2-4 we would need a utility with similar functionality to `Object.observe`. If there is already such a utility in the Angular 2 code base, then these cases can be covered too. Otherwise, the solution would either require a lot of code or would not be ideal (copy & compare).

Do you know if there is already a utility similar to `Object.observe` in the Angular code base?

**Comment by shlomiassaf** [comment]
@joelrich It will not work, change detection in angular is managed by the component factory class (`AppView`) which is also implements the change detection. It is done the "hard" way by creating code that explicitly checks for a change. This is possible due to the `@Input` meta instruction.

There is no `Object.observe` every `@Input` property is check.
This is not all, every property can be checked by reference of by iterating child properties, this is set by the user when he select the change detection strategy for the component, each component might have a different one.

These are just some of the issues, there are more...

It doesn't make sense to do it and the angular team will not allow it anyway, it will add a lot of code, will have issues and so much more :)

I strongly recommend to deeply understand how the CD work, it will make you'r life easy doing angular 2.

Anyway, I think it's better we stick with the current proposal as adding these feature will not get approval.

**Comment by shlomiassaf** [comment]
BTW, I think binding properties is sort of an abuse since this component is not intended for such use case...

If you have a use case that requires binding use a template with a switch directive and list all components you support....

**Comment by joelrich** [comment]
@shlomiassaf I have opened #9599 for a concrete use case which is impossible to implement with switch and does require static (known at compile time) as well as dynamic properties.

I know that the normal change detection does not work like this. Since we cannot use it here, we have to find another solution. If there is no utility like `Object.observe`, then I see three options. They all require to implement a custom change detector. Is this possible today?

1. When the change detector runs for the first time, it copies the whole object. When it runs again, it compares the two objects. If there are differences, it sets the new values on the component and either creates a new object or adjusts the existing object to detect future changes.
2. When the change detector runs for the first time, it iterates all input names of the target component and copies the property values with the same name from the object into an array. This array is then used for comparisons. The array can easily be reused.
3. The component instance itself is used for the comparison.

As long as the component inputs are mapped to normal properties without getters, the third option would be the best. With getters it could be problematic. The second option is the most predictable option although it may be slower than the first option in ideal cases. Therefore, I would implement the second option.

What do you think?

**Comment by shlomiassaf** [comment]
@joelrich This is a lot of work for a specific use case.

This component is part of the `@angular/common` package, which means some general purpose components for general use.

Most of the component in this package are quite easy to implement so you'r proposal can be implemented as a third party package.

I'm 99% sure that the angular team will not accept this offer and implement a custom change detector, it's a lot of noise for a particular use case.

I do like the idea, very powerful and you might want to make it a third party package... 

That's my opinion, I don't call the shots so feel free to nag the other guys here :)

**Comment by joelrich** [comment]
@vicb @mhevery what do you think about the my suggestion above to be able to bind properties to the component outlet? I do not think that is such a special use case. In React, for example, you could easily do the same just by writing:

```javascript
<DynamicComponent {...dynamicProps} />;
```

**Comment by luigidallavalle** [comment]
@joelrich I agree with you. I think that being able to set properties and events it's not an uncommon use case. I'm developing a basic master\detail app with the ngComponentOutlet that @shlomiassaf commited  but I'm using [another way](https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#bidirectional-service) to have data passed to the dynamically created component, but I'd prefer to declare those properties in <template>

**Comment by shlomiassaf** [comment]
@luigidallavalle We all agree about that its a good feature but it's costly, a lot of work to implement.

If we want `NgComponentOutlet` to land we should first implement the basic features. Advanced features might come later.

Making it that complex will make this PR difficult to understand.

Let's start simple, later we will add that feature.

**Comment by a5hik** [comment]
How does it works with an AOT app? will it have an impact?

**Comment by mcweiss** [comment]
What about the ngOutletCreated event? How can someone get the componentRef and more importantly its instance property without this?

**Comment by gund** [comment]
Hi guys, regarding change detection on inputs to dynamic component I've done some work using angular's `Differs` for change detection. Please have a look [here](https://github.com/gund/ng-dynamic-component/blob/master/src/dynamic/dynamic.directive.ts).

That directive will basically trigger standard `ngOnChanges` on dynamic component if there are some changes on inputs.

What do you think of the implementation?

**Comment by rendmath** [comment]
Being able to select a component to instantiate based on a runtime decision is an obvious requirement for any UI framework. Not being able to bind inputs and outputs into that component makes the feature pretty much useless at the moment.

**Comment by francesconi** [comment]
@shlomiassaf Could you please post an example about 

> listening to the ngOutletCreated event and then using the ComponentRef.instance to set properties or register to event streams.
