### ISSUE TITLE
child canActivate is called before parent canActivate is resolved when using AuthGuards

### ISSUE THREAD

**Issue by fouadbhatti** [angular/angular#11161]
```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Child canActivate is called before parent canActivate is resolved. e.g
```
// RouterConfig
{
  path: 'parent',
  component: ParentComponent,
  canActivate: [ParentAuthGuard],
  children: [
    defaultPath('child'),
    {
      path: 'child',
      component: ChildComponent,
      canActivate: [ChildAuthGuard],
    }
  ]
},
```

```
// Parent AuthGuard
canActivate(activatedRouteSnapshot: ActivatedRouteSnapshot) {
  console.log('Parent Auth Guard Called');
  return this.service.get().map((response) => {
    console.log('Parent AuthGuard Resolved');
    if (response) { return false; }
    return true;
  });
}
```
```
// Child AuthGuard
canActivate(activatedRouteSnapshot: ActivatedRouteSnapshot) {
  console.log('Child AuthGuard Called')
  if (someCondition)  return true;
  return false;
}
```

Output
1. Parent Auth Guard Called
2. Child AuthGuard Called
3. Parent AuthGuard Resolved

**Expected/desired behavior**
Parent AuthGuard should be resolved before child AuthGuard is called
Output
1. Parent Auth Guard Called
2. Parent AuthGuard Resolved
3. Child AuthGuard Called

**What is the motivation / use case for changing the behavior?**
In my opinion shouldn't child canActivate hold until parent is resolved. What do you guys say and whats the motivation behind not waiting for parent to resolve.

* **Angular version:** 2.0.0-rc.4
* **Browser:** [all]  
* **Language:** [TypeScript | ES6/7]

**Comment by ericmartinezr** [comment]
Fixed via https://github.com/angular/angular/pull/11063

**Comment by vicb** [comment]
thanks @ericmartinezr

**Comment by tiagoroldao** [comment]
This seems to be a problem when loading a page with a direct url.

A use case for this would be using Router to ensure loading of dependencies (say, serverside configuration), and then using that configuration in a child route's guard.

**Comment by brandoncollins** [comment]
Also experiencing this issue using a direct URL. Both guards are called before Guard1 has been resolved.

**Comment by elwaxoro** [comment]
Also running into this issue with direct URL.

**Comment by ievgeniiVlasyuk** [comment]
Direct URL bring this problem for me too. Are there any ticket for it?

**Comment by WiseBird** [comment]
[plunker](https://plnkr.co/edit/ewf4eFdTsl98OiYD4xS1?p=preview)

**Comment by jrgleason** [comment]
I had a similar issue [here](https://plnkr.co/edit/yK0eGoUGIVvKZu45jSBs?p=preview)

**Comment by lppedd** [comment]
@tiagoroldao Hi! Did you come up with a workaround?

**Comment by johaven** [comment]
+1
