### ISSUE TITLE
FormArray.removeAt doesn't throw Error if Element not found

### ISSUE THREAD

**Issue by BoxOfPandora** [angular/angular#11160]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When trying to remove an Element from an FormArray, no error will be thrown, if the Element was not found with removAt(index).

**Expected/desired behavior**
Kind of feedback when the operation failed. 

**Reproduction of the problem**
`formArray: FormArray;
......
for(let i = 0; i < 1000000000; i++)
    this.formArray.removeAt(1000000000);`

**What is the motivation / use case for changing the behavior?**
We were trying to clean up our Form at specific timepoints and recreate it with the new structure and wondered, why the FormArray still had some controls.

**Please tell us about your environment:**
Visual Studio Code, VS2015 Update 3 with Node js Tools, Latest Chrome etc...

* **Angular version:** 2.0.0-rc.5

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
TypeScript 1.8.10

**Comment by Fank** [comment]
@vicb @kara by added a `throw` to the method/s will cause in a breaking change. The current API is stable and this means changes like this can only be done in angular@^3.0.0 or?

**Comment by vicb** [comment]
`[].splice(8, 1)` doesn't throw either...

I have no strong opinion whether we should throw or not. @kara ?

If the change is considered a fix then we can merge it before a major release.

On a side there should be an early return when `!this.control[index]` - currently 1 out of 4 LOC is protected.

**Comment by kara** [comment]
@vicb That's a good point. I'm inclined to keep it as it is for now. If we hear from more users that this is painful, we may reconsider down the line.
