### ISSUE TITLE
No provider for ControlContainer when a child component has a ngModelGroup

### ISSUE THREAD

**Issue by xe4me** [angular/angular#11174]
[* ] bug report => search github for a similar issue or PR before submitting

This is the original [plunker](http://embed.plnkr.co/LLf7Il/) which is written by @Paskal Prekht , which is an explanation on template driven forms:

And here is my [fork](https://embed.plnkr.co/Q8pjSIVJHhfubILtvqWw/) ,
which is exactly the same thing , except I'm trying to load one of the fieldsets as a separate child component.

Here is the code : 

```
@Component({
  selector:'form-group-component',
  template:`
    <fieldset ngModelGroup="anotherAddress">
      <div>
        <label>Street2:</label>
        <input type="text" name="street2" ngModel>
      </div>

    </fieldset>

  `
})
export class FormGroupComponent{

}

@Component({
  selector: 'form-component',
  directives:[FormGroupComponent],
  template: `
    <form #form="ngForm">

      <form-group-component></form-group-component>  

      <fieldset ngModelGroup="address">
        <div>
          <label>Street:</label>
          <input type="text" name="street" ngModel>
        </div>
        <div>
          <label>Zip:</label>
          <input type="text" name="zip" ngModel>
        </div>
        <div>
          <label>City:</label>
          <input type="text" name="city" ngModel>
        </div>
      </fieldset>

    </form>
  `
})
export class FormComponent {


}

```

So after cutting one of the feildsets and loading it inside a seperate directive , it won't work anymore!,

There are couple of closed issues , but non of them is working.

[This](https://github.com/mgechev/angular2-seed/issues/399) and [This](https://github.com/angular/angular/issues/6374)

**Comment by kara** [comment]
@xe4me  If you want to create a custom form component, you'll need to implement `ControlValueAccessor`.  See my comment [here](https://github.com/angular/angular/issues/9281#issuecomment-238610807) for some examples or read [Pascal Precht's blog post on it](http://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html).

**Comment by bob-lee** [comment]
I had a similar problem, managed to write a custom form component that has multiple input fields and implements ControlValueAccessor to make it work like a single control in a parent form. Look for bank-account-group.component in [this plunker](http://plnkr.co/edit/SHzjAgtD4c6RS5KWOFyn)

**Comment by CSchulz** [comment]
@bob-lee Your plunker isn't available. Can you reupload it?

**Comment by bob-lee** [comment]
Here we go: [plunker](http://plnkr.co/edit/JatWOQDzCfX9AUWbUZGU?p=info)
Also this [article](http://www.codeproject.com/Articles/1121101/Angular-custom-component-with-validation-for-ban)

**Comment by CSchulz** [comment]
@kara Please have a look on the example from bob-lee. The template driven variant does need another form element, which seems not correct at all. Imho I want to place the ngModelGroup in the component itself and not in the root.

**Comment by bob-lee** [comment]
@CSchulz I am with you. It took a while for me to make template-driven way to work, still feels like hack.. Hopefully I maybe missing something or better support on template-driven way comes up. Meanwhile I would choose model-driven way.

**Comment by CSchulz** [comment]
Here is my interpretation as template-driven way working with splitted components:

http://plnkr.co/edit/xJr1ZZBkSz3TuT43Tpwm?p=preview

**Comment by k-schneider** [comment]
Has anyone come up with a cleaner template-driven approach for this yet or is the only sane way to build forms with complex child components/forms to use the reactive model?  Thanks.

**Comment by nitz88** [comment]
@CSchulz thanks for example. But in child component when i put required field for input then if i check form valid or not then i find always form as valid which is wrong if required field is empty.

Did you find any solution for that ?

**Comment by CSchulz** [comment]
You have to execute manually the validation check for the group f.e.

`this._group.control.updateValueAndValidity()`

**Comment by squadwuschel** [comment]
@CSchulz that sounds hacky

@kara at the moment I think the template driven forms are over engineered and you have to do a lot of hacky thinks to get it "work" a bit. Its cool on the standard "forms" but who the hell has standard forms in  buisness application expect the contact formular. I am searching since 3 days now for a "easy" method for template driven forms validation with custom components with multiple inputs in it there seems to be NO solution on such a simple use case, only soultion you find are one control in one component - crap.

**Comment by preto89** [comment]
ive faced the same problem, read angular documentation, **you cant import FormsModule only**, u also **need ReactiveFormsModule**, add it to your imports in app.module.ts

`import {FormsModule, ReactiveFormsModule} from '@angular/forms';`
