### ISSUE TITLE
CanActivateChild guard on root does not have any effect

### ISSUE THREAD

**Issue by crtag** [angular/angular#11177]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Implemented simple guard on the app root level, which does redirect to one of its submodule routes. It has no effect in any navigation way presuming the guard returns "false" all the time. Having it logging into console reveals no guard instance is created at all.

**Expected/desired behavior**
When CanActivateChild guard is set on app root level it is expected any navigation at least between its submodules routes are guarded, including explicit redirects. Ie having app root route "/" configured with this guard and having its submodules routes "/a" and "/b", initial redirect (if configured) from "/" -> "/b" or navigation between "/a" -> "/b" would trigger root level CanActivateChild guard.

**Reproduction of the problem**
I have modified router live app example to demonstrate the problem I'm having by adding "CanActivateChild-guard" into root routing.
http://plnkr.co/edit/9B8nf4kpcXvB1pLJHHme?p=preview

**What is the expected behavior?**
Plunker example would have any navigation between child siblings blocked with respective console message.

**What is the motivation / use case for changing the behavior?**
I'd expect this is to work as documented.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 / Router 3.0.0-rc.1
 
* **Browser:** [Chrome XX] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by brandonroberts** [comment]
Your guard is on a redirect that has no children ...

**Comment by crtag** [comment]
@brandonroberts it does have children attached in submodules routing via `RouterModule.forChild()`. Otherwise entire modules concept is a failure then in respect to the router when you can't have "global" guard on your app level routes.

**Comment by crtag** [comment]
Also, removing redirect and having there app level component configured does not make any difference to guard on navigation.

**Comment by brandonroberts** [comment]
@crtag `RouterModule.forChild` in itself does not create child routes. See https://github.com/angular/angular/issues/10958 for more context. Modules do not create a hierarchy when imported and share the same injector. So your routes from the app module, and hero module are flattened together and the hero routes aren't children of the top level configuration.
