### ISSUE TITLE
Can't access values from KVChangeRecord

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#1118]
I'm working on the binding to the classList (#876) and shaping my directive as follows:

```javascript
@Decorator({
  selector: '[class]',
  bind: {
    iterableChanges: 'class | keyValDiff'
  }
})
export class CSSClass {
  set iterableChanges(changes) {
    changes.forEachItem((record) => {
      if (record._currentValue) {
        DOM.addClass(this._domEl, record.key);
      } else {
        DOM.removeClass(this._domEl, record.key);
      }
    });
  }
}
```

This works fine in JS but it looks like I'm accessing "private" variable `record._currentValue`. It seems to me that both `_previousValue` and `_currentValue` should be public - otherwise we can't really access values of the individual change records.

@vicb it seems like you've written this part - does my request make sense to you, or am I doing sth wrong?

**Comment by vicb** [comment]
Yep, the leading "_" should be removed if we want to be able to access the values in Dart

**Comment by pkozlowski-opensource** [comment]
OK, thnx - will send a PR
