### ISSUE TITLE
"localhost:3000/dashboard/dashboard" duplicated sub URL in Angular Sample while navigating

### ISSUE THREAD

**Issue by myguddy** [angular/angular#11184]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In navigating and refresh the angular2 sample with typescript, "dashboard" subURL is duplicated
like "localhost:3000/dashboard/dasboard"

**Expected/desired behavior**

It should be routing to simple URL ""localhost:3000/dashboard"

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome XX ] 
 
* **Language:** [TypeScript X.X ]

**Comment by qdouble** [comment]
@myguddy your base href is probably incorrect...reproduce in plunker otherwise.

**Comment by mhevery** [comment]
We need a plunker. Investigating without plunker is too time intensive and we will not look at it otherwise.

I am closing, please open new issue once you have a plunker.
