### ISSUE TITLE
Structural directives using '*' shorthand does not exportAs

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#11189]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using `exportAs` in a structural directive the export works if the template is declared using a `template` element. 
```
 <template myDirective ref-myDirective="myDirective"></template>
```

When using a "syntactic sugar" asterisk syntax:

```
<div *myDirective ref-myDirective="myDirective"></div>
```

 the export fails with the following error: 
```
There is no directive with "exportAs" set to "myDirective"
```

**Expected/desired behavior**
`exportAs` should be consistent regardless of the syntax used.

**Reproduction of the problem**
see [this plunker](http://plnkr.co/edit/2gFCICDnDMflwSd2kyQK?p=preview)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5

**Comment by shlomiassaf** [comment]
Looking at the [TemplateParser. _createDirectiveAsts()](https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/template_parser/template_parser.ts#L716) line 710 - After stopping at 711, it seems that `directives` are empty when using `*` syntax but populated with the directive when using `<template>` syntax.

From what I understand reading the code, `*` syntax directives require a 2-pass parsing.
In the first parse step the element is treated as raw element, having the `*modal` as a raw property with the same name (`*modal`) and also no `modal` directive (yet...), the parser detects that it needs to **de-sugar** to a full template syntax so it will transform the template and send it again (2nd step)

The problem is that on the 1st step there is a validity check for references, see lines 729-735
```ts
      elementOrDirectiveRefs.forEach((elOrDirRef) => {
        if ((elOrDirRef.value.length === 0 && directive.isComponent) ||
            (directive.exportAs == elOrDirRef.value)) {
          targetReferences.push(new ReferenceAst(
              elOrDirRef.name, identifierToken(directive.type), elOrDirRef.sourceSpan));
          matchedReferences.add(elOrDirRef.name);
        }
      });
```


This check runs in each step but in step 1 we still don't have a directive but we do have a reference, which means there is no directive that **exports** the reference.

This test should run on complete/**de-sugared** templates and not on **sugared** templates.

**Comment by mhevery** [comment]
@tbosch can you have a look if this is a valid issue?

**Comment by tbosch** [comment]
This works as intended: 
```
<div *myDirective ref-myDirective="myDirective"></div>```
desugars into this:
```
<template myDirective><div ref-myDirective="myDirective"></div></template>
```

I.e. `myDirective` and `ref-myDirective` are on _separate_ elements.

Regarding the code in TemplateParser:
`createDirectiveAsts` is called 2 times in the parser in case of `*` syntax, one time with the directives of the contained element (`ref-myDirective` here) and one time with the directives of the `*` (`myDirective` here).

**Comment by shlomiassaf** [comment]
@mhevery @tbosch I'm sorry but I don't understand.

The code in [the plunker](http://plnkr.co/edit/2gFCICDnDMflwSd2kyQK?p=preview) I have attached does not work. 

```
      <div *myDirective ref-myDirective="myDirective">
        <h2>Data: {{myDirective.data}}</h2>
      </div>
```

throws an error.

I understand the logic and how the template works, it's also documented. 

The problem is that currently `exportAs` does not work with `*` syntax structural directive.
Unless I'm missing something in my plunker example.

Thanks.

**Comment by tbosch** [comment]
exportAs variables is only accessible on the same Element. As the * syntax
desugars into 2 elements, separating the directive that does exportAs from
the data binding consuming the exportAs variable it does not work

**Comment by shlomiassaf** [comment]
@mhevery  @tbosch OK, official answer now :)

I guess it should be documented https://angular.io/docs/ts/latest/api/core/index/DirectiveMetadata-class.html#!#exportAs-anchor
@wardbell  ?

This also means:
You can't **exportAs** a structural directive just like that, if you need this functionality you must enforce a `template` tag in the selector.

This creates different behaviours for structural directives because of the syntax sugar support.
I can't imagine the ES6 `class` syntax sugar behaves differently due to the de-sugaring process

**Comment by thekalinga** [comment]
I'm posting explanation here so that it might be of some use to any one in the future

If one wants to use custom structural directive as a reference in the template like `#myDirective`/`ref-myDirective` (or) within component as `@ViewChild('myDirective')`, he needs to use de-sugered version in the template.

This is because, angular compiler converts this
```html
<div *myDirective #myDirective="myDirective">
  <h2>Data: {{myDirective.data}}</h2>
</div>
```

into this

```html
<ng-template myDirective>
  <div #myDirective="myDirective">
    <h2>Data: {{myDirective.data}}</h2>
  </div>
</ng-template>
```

Which will not be able to grab any value for `#myDirective="myDirective"` as, in the de-sugered version, we have `#`(or `ref`) placed on the child `div`, not on the parent `ng-template` that has the real access to  `myDirective`.

Since the div became a child of the above directive after de-sugering, this will fail.

In order to make this work, we have use the de-sugered version directly

```html
<ng-template myDirective ref-myDirective="myDirective">
  <div>
    <h2>Data: {{myDirective.data}}</h2>
  </div>
</ng-template>
```

This way we are telling angular to pick `myDirective` reference from `myDirective` directive & the place where this reference is placed is proper.

I have modified the original plunkr to show this as an example

https://plnkr.co/edit/PepRI12yZDuI4xEqtyEw?p=preview
