### ISSUE TITLE
DI exception in AOT mode and packUmd caused by NgZone difference in core.umd.js and ng_zone.js

### ISSUE THREAD

**Issue by Zhuoqing** [angular/angular#11183]
**I'm submitting a bug report  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
in Angular RC5, NgZone in node_modules\@angular\core\src\zone\ng_zone.js and node_modules\@angular\core\bundles\core.umd.js is slightly different 

for example, 
in ng_zone.js line 97      it is "this._onUnstable = new async_1.EventEmitter(false);"
in core.umd.js line 9222 it is "this._onUnstable = new EventEmitter(false);"

This cause DI exception in AOT mode with packUmd . becaused the compiler generated app.module.ngfactory.ts has 
"import \* as import24 from '@angular/core/src/zone/ng_zone';"
"this.parent.get(import24.NgZone)"
while in packUmd systemjs mode, DI provider is keyed by NgZone from core.umd.js and it doesn't match, so endup with DI exception.

packIndex works as expected.

**Expected/desired behavior**
should be same

**Reproduction of the problem**
1. clone https://github.com/angular/quickstart
2. add compiler-cli to it
3. change main.ts to use aot bootstrapModuleFactory
4. run ngc to compile
5. load the page

**What is the expected behavior?**
page loaded with no exception.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** all 
- **Language:** all | TypeScript X.X | ES6/7 | ES5]

**Comment by mhevery** [comment]
What is `packUmd`?
In AOT mode one should not be using UMD bundles at all, instead one should be using module code in the NPM module. 

I don't think it is valid to just take a JIT example and convert it into AOT. If you want to use AOT you should use angula-cli

**Comment by Zhuoqing** [comment]
packUmd is the function in the quickstart example. var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;

Good to know that for AOT should not use UMD bundles, and should use angular-cli. Hope those info would later make it into the documents for AOT.

I cannot find a good and simple quickstart AOT example, so I take the JIT example and convert it to AOT and meet the issue, and thought you guys or someone else trying same thing may want to know.

**Comment by Sukh9212** [comment]
I agree that there is just not any documentation at all about what to do to get the app run in AOT mode.
Please have a section on the angular.io website that clearly explains the best practices on how to run the app in AOT mode for people who are so used to JIT.

**Comment by xealot** [comment]
The answer here helped me get over the error:
`(SystemJS) No provider for NgZone!` when attempting to do AoT compilation.

**Comment by bnormoyle** [comment]
This is an incredibly frustrating error to debug, and it's frustrating that there is this distinction between the AoT and JIT building processes that is not clearly explained. Can more effort be put into documenting how to convert from a JIT build to an AoT build?

**Comment by DzmitryShylovich** [comment]
There's already a section about aot on angular.io https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Comment by DzmitryShylovich** [comment]
@Zhuoqing is this still valid in angular 4?

**Comment by wardbell** [comment]
Closing as old and probably not longer relevant. It's also not clearly actionable.
