### ISSUE TITLE
ngModel not updated

### ISSUE THREAD

**Issue by hanjia2014** [angular/angular#11182]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
the issue found from the version RC5
when value changes in model.property, it doesn't change the value in template {{model.property}}, it changes after mouse click.

**Expected/desired behavior**
as soon as model.property changes in component, it reflects the new value in template {{model.property}}

**Reproduction of the problem**
you can reproduce the issue by downloading my application
https://github.com/hanjia2014/OrderPaper
need to install npm before running it.
the issue is in orderpaper.component.ts, after drag and drop item, the sequence number should change, and the new sequence number should appears at {{updatedSection.Sequence}}, but it doesn't, you have to manually mouse click the any item header to trigger the value update (either click blue or pink header)

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
you can reproduce the issue by downloading my application
https://github.com/hanjia2014/OrderPaper

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by zoechi** [comment]
> you can reproduce the issue by downloading my application

I wouldn't expect anyone to download and execute random code from the internet.

For a bug report report a Plunker with the minimal amount of code that allows to reproduce the issue is required.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by vicb** [comment]
@zoechi is right, sounds like a support request.

If you think this is a real bug, please re-open with a minimal plunker. Thanks.
