### ISSUE TITLE
[feature request] Possibility to insert js logic in class helper

### ISSUE THREAD

**Issue by vadimzham** [angular/angular#11193]
**I'm submitting a ...**  
[x] feature request

**Current behavior**
Now expressions like `[class.hidden]='a || b'` are impossible to be used. I suggesting possibility to use this and expressions like `[class.hidden]='a == 5'`. 

**What is the motivation / use case for changing the behavior?**
This functional will help to write less code.

**Comment by pkozlowski-opensource** [comment]
> Now expressions like [class.hidden]='a || b' are impossible to be used.

Why are you saying so? Both are supported today: https://plnkr.co/edit/drG6SsfxAzOT7net9vKO?p=preview

Please provide a plunker with a reproduce scenario - otherwise it is not actionable.

**Comment by vadimzham** [comment]
https://plnkr.co/edit/bun3ZUlw80lg9DjgFCyl?p=preview
Then this should be bug.

**Comment by pkozlowski-opensource** [comment]
You had a bug in your "non working" plunker: https://plnkr.co/edit/rOFT4z1tojQD4s3Cs797?p=preview
If you use object (`test`) use it in the expression as well (`test.a` etc.).

Closing as I don't think there is a bug to be solved here on our side.
