### ISSUE TITLE
Angular 2 RC5 apps have issues loading on iOS device

### ISSUE THREAD

**Issue by timothyBrake** [angular/angular#11190]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have lots of issues loading an Angular 2 RC5 application. It works perfectly on all browsers on a Windows and Macbook Pro but the same application does not load properly on iOS Safari browser. After investigation it seems that on iOS devices some requests return a 404 on framework javascript files that are indeed not on that location. After refreshing the browser couple of times, clearing the caches and website data, the application has everything loaded correctly and works fine. Sometimes it takes a lot of refreshes and clearing data so it seems to be linked HOW and in what order the application javascript files are loaded. The files being loaded are NOT files that I have created but deep Angular framework files.

To be clear: same application works perfectly on MAcOSX and Windows using Safari, Chrome and IE but the same application does not work on iOS 9.3.5 Safari OR Chrome.

Additionally: the "tour of heroes" application does not load up on an iOS device as well.

**Expected/desired behavior**
The same application should load correctly on an iOS device that on a desktop browser. 

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
It seems random as on some devices, it loads ok but on other devices it does not. 

**What is the expected behavior?**
The same application should startup on all browsers including

**What is the motivation / use case for changing the behavior?**
Users should not be forced to refresh the browser or clear the cache.

**Please tell us about your environment:**

Dependencies in package.json
```
"dependencies": {
    "@angular/common": "^2.0.0-rc.5",
    "@angular/compiler": "^2.0.0-rc.5",
    "@angular/core": "^2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "^2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "@angular/upgrade": "2.0.0-rc.5",
    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "^3.3.6",
    "bootstrap-datepicker": "^1.6.4",
    "bootstrap-timepicker": "^0.5.2",
    "chart.js": "^2.2.1",
    "core-js": "^2.4.0",
    "ng2-charts": "^1.1.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings": "^1.0.4"
  }

Systemjs config

(function(global) {
    // map tells the System loader where to look for things
    var map = {
        'app':                        'app', // 'dist',
        '@angular':                   'node_modules/@angular',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        'rxjs':                       'node_modules/rxjs',
        'ng2-charts':                 'node_modules/ng2-charts',
    };
    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app':                        { main: 'main.js',  defaultExtension: 'js' },
        'rxjs':                       { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
        'ng2-charts': { main: 'ng2-charts.js', defaultExtension: 'js' },
    };
    var ngPackageNames = [
        'common',
        'compiler',
        'core',
        'forms',
        'http',
        'platform-browser',
        'platform-browser-dynamic',
        'router',
        'router-deprecated',
        'upgrade',
    ];
    // Individual files (~300 requests):
    function packIndex(pkgName) {
        packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
    }
    // Bundled (~40 requests):
    function packUmd(pkgName) {
        packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
    }
    // Most environments should use UMD; some (Karma) need the individual index files
    var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
    // Add package entries for angular packages
    ngPackageNames.forEach(setPackageConfig);
    var config = {
        map: map,
        packages: packages
    };
    System.config(config);
})(this);
```

* **Angular version:** 2.0.0-rc.5

* **Browser:** iOS 9.3.5 Safari ] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by mhevery** [comment]
Can you add some the the errors here? It looks like you are using UMD bundles so there should only be one request per bundle.

**Comment by timothyBrake** [comment]
HI,

The errors sometimes switch depending on what is loaded and what not. I have just received an error on iphone device. I will try and be as specific as I can.

* error object received is err
```
column: 87
line: 123
message: "eval@[native code]↵	↵	↵	eval code↵	eval@[native code]↵	↵	↵	eval code↵	eval@[native code]↵	↵	↵	eval code↵	eval@[native code]↵	↵	↵	eval code…"
originalErr: SyntaxError: Unexpected token '<'
sourceURL: "http://123.12.12.123:8080/app-name/node_modules/systemjs/dist/system.src.js"
stack: null
```

Console command

```
> console.error(err)
>
[Error] Error: eval@[native code]
	
	
	eval code
	eval@[native code]
	
	
	eval code
	eval@[native code]
	
	
	eval code
	eval@[native code]
	
	
	eval code
	eval@[native code]
	invoke@http://123.12.12.123:8080/app-name/node_modules/zone.js/dist/zone.min.js:1:7363
	run@http://123.12.12.123:8080/app-name/node_modules/zone.js/dist/zone.min.js:1:4751
	http://123.12.12.123:8080/app-name/node_modules/zone.js/dist/zone.min.js:1:3344
	invokeTask@http://123.12.12.123:8080/app-name/node_modules/zone.js/dist/zone.min.js:1:7992
	runTask@http://123.12.12.123:8080/app-name/node_modules/zone.js/dist/zone.min.js:1:5357
	a@http://123.12.12.123:8080/app-name/node_modules/zone.js/dist/zone.min.js:1:2460
	g@http://123.12.12.123:8080/app-name/node_modules/core-js/client/shim.min.js:8:10017
	http://123.12.12.123:8080/app-name/node_modules/core-js/client/shim.min.js:8:10139
	k@http://123.12.12.123:8080/app-name/node_modules/core-js/client/shim.min.js:8:14294
	Evaluatinghttp://123.12.12.123:8080/app-name/node_modules/rxjs/add/operator/debounceTime.js
	Evaluating http://123.12.12.123:8080/app-name/app/rxjs-operators.js
	Evaluating http://123.12.12.123:8080/app-name/app/app.component.js
	Evaluating http://123.12.12.123:8080/app-name/app/app.module.js
	Evaluating http://123.12.12.123:8080/app-name/app/main.js
	Error loading http://123.12.12.123:8080/app-name/app/main.js

	eval code
	eval
	(anonymous function)
	(anonymous function)
	_evaluateOn
	_evaluateAndWrap
	evaluateOnCallFrame
	(anonymous function) (login:216)
	invoke (zone.min.js:1:7364)
	run (zone.min.js:1:4752)
	(anonymous function) (zone.min.js:1:3345)
	invokeTask (zone.min.js:1:7993)
	runTask (zone.min.js:1:5358)
	a (zone.min.js:1:2461)
	g (shim.min.js:8:10018)
	(anonymous function) (shim.min.js:8:10140)
	k (shim.min.js:8:14295)
< undefined

```

Seems to be related to something that cannot be loaded. The message in err.originalErr is "Unexpected token '<'" when a 404 occured somewhere along the road but this time all was loaded fine if I look at the Network traffic. There is no 404!

```
err.originalErr
	column: 18
	line: 1510
	message: "Unexpected token '<'"
	sourceURL: "http://123.12.12.123:8080/qcr-ui-web/node_modules/systemjs/dist/system.src.js"

```	

Console command
```
> console.error(err.originalErr)
> SyntaxError: Unexpected token '<' — system.src.js:1510

```

The (anonymous function) (login:216) is I guess something of ours but the breakpoint is at the index page script at the line 216 (where the breakpoint is to debug the issue)

No idea how to solve this but a clear browser data and hope for the best. Once again the application runs fine on a desktop browser accessing the SAME application.


Kind regards,
Timothy

**Comment by timothyBrake** [comment]
There are multiple issues rising on iOS Safari depending on what gets loaded and what not.

if I check the actual requests on iPhone/iPad using my MacbookPro Safari linking inspector, you can actually see the requests being fired. Some errors seem to be linked to how the loading of js files is done. E.g.:
`
...
import {SomeService} from "../../../service/something.service";
...
`
When starting the application, you see in the inspector that the wrong URL is taken to get teh actual js file like 
"https://something/this-iswrong/service/something.service.js"
instead of
"https://something/therightone/service/something.service.js"

Once again EVERYTHING works fine on MacbookPro Safari and Chrome it is just not on iOS devices which is a real pain. Once everything IS loaded correctly, it also works on iOS but I cannot tell the users to keep clearing the browser data and hope for the best.

Maybe I should try using webpack instead of systemJS?

Anyone having same issues here? Any help is more than welcome!


Kind regards,
Timothy

**Comment by vicb** [comment]
Could you please try to as a small project that reproduces the error. Something like the plunker given in the issue template.

Then we need the exact steps to reproduce the issue on our side.

Without that there is no way we can help.

Thanks

**Comment by sachinksana** [comment]
I am having problem to load angular 2 app in safari only, it is working fine in chrome,mozila.

Please help me.
![erroronsafari](https://cloud.githubusercontent.com/assets/6177545/20913434/e04ce8bc-bb9d-11e6-8861-777d58ba02ec.PNG)

**Comment by AlekseyChuyan** [comment]
+1
