### ISSUE TITLE
Checkbox and radio buttons not working in child routes (Bug in child routing)

### ISSUE THREAD

**Issue by dlinx** [angular/angular#11194]
Checkbox and radio buttons not working in child routes. They are not changing their states on click. If the named router outlet is inside the dom which has routerLink. Here is plunkr link **http://plnkr.co/edit/0Hcu7E3rY1SoKnetpAjG?p=preview**

Here is the exact issue:

```
<div>
  <span [routerLink]='[{outlets:{firstSection:"firstSection"}}]'>First Section
    <router-outlet name='firstSection'></router-outlet>
  </span>
</div>
```

If we put this `router-outlet` outside the routerLink dom, then it works perfectly.

**Comment by zoechi** [comment]
Without deeper investigation it looks like `[routerLink]` causes `preventDefault` on the `<span>` element. which breaks the radio buttons. Perhaps [routerLink] should do this only when applied to an `<a>` tag.

You can also reproduce the same behavior when you move the `<router-outlet>` outside the `[routerLink]` and wrap it in another `<span>` like

```html
  <span (click)="false">
    <router-outlet name='firstSection'></router-outlet>
  </span>
```

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/pull/12647
