### ISSUE TITLE
RedirectTo for child Route not working

### ISSUE THREAD

**Issue by kosstianmailru** [angular/angular#11199]
RedirectTo for child Route not working.
const heroesRoutes: Routes = [
  { path: 'heroes',  component: HeroListComponent,
    children: [
                    { path: '', redirectTo: 'test', pathMatch: 'full' },
                    { path: 'test', component: TestComponent }
                ]
  },
  { path: 'hero/:id', component: HeroDetailComponent }
];

Error: Cannot match any routes: 'heroes'

Here is plunkr link http://plnkr.co/edit/R8GyE7a68goR46bS0U9E?p=preview

**Comment by brandonroberts** [comment]
Redirecting with a leading slash `/heroes` in the path is considered _absolute_ and is only handled once. If you use a relative redirect to `heroes`, it will work correctly when it gets to the child routes.

http://plnkr.co/edit/P57XpSdkp97VR2446t5U?p=preview

**Comment by kosstianmailru** [comment]
Ок, thank you!
