### ISSUE TITLE
Plunker Typescript demo not working?

### ISSUE THREAD

**Issue by pauldevilliers** [angular/angular#11196]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The Plunker Typescript demo was working until this morning - when I noticed that it stopped with the following error in the browser:

XMLHttpRequest cannot load https://npmcdn.com/plugin-typescript@4.0.10/lib/plugin.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.

I then noticed that my Node system on windows was generating the same error - so this is basically stopping the demo/online code from running as well as the offline development environment...

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.9.0 ]

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/11191

**Comment by mhevery** [comment]
closing as dup
