### ISSUE TITLE
Quickstart plnkr not working

### ISSUE THREAD

**Issue by Svrkota-S** [angular/angular#11191]
Your quickstart plnkr seems to be broken:

https://angular.io/resources/live-examples/quickstart/ts/plnkr.html

Console displays following error:

XMLHttpRequest cannot load https://npmcdn.com/plugin-typescript@4.0.10/lib/plugin.js.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://run.plnkr.co' is therefore not allowed access.

**Comment by pkozlowski-opensource** [comment]
Here is a created plunker for which I can't see the described problem: http://plnkr.co/edit/doILju3hXqxdMNQIvz1Y?p=preview 

Maybe this is sth specific to your env? In any case this issue doesn't belong here, please open at https://github.com/angular/angular.io if you still believe this is a pb on our end.

**Comment by PauloSalazarB** [comment]
I have the same problema, i am working with webstorm, nodejs, and angular2 rc5...
the most strange thing is the error happens yesterday and it disappear (i dont know how) now is back again...

**Comment by clever122** [comment]
Same problem today with me. Came in this morning and nothing works. Looks like the server for NPM has been changed.

**Comment by clever122** [comment]
Just an update, All my links in my angular code were pointing to https://npmcdn.com/... but when I go to that site, it now redirects to: https://unpkg.com/ I changed my links to that domain instead and everything works great again. Seems like they made a change.

**Comment by ericmartinezr** [comment]
The issue is fixed and explained here https://github.com/angular/angular.io/issues/2230
