### ISSUE TITLE
RFC: Add support for "assert()"

### ISSUE THREAD

**Issue by vicb** [angular/angular#112]
Dart has built-in `assert(cond)` where `cond` is either a bool or a function returning a bool.

What do you think of adding support for it to the transpiler ?

This could be linked with type assertions:
- When type assertions are enabled, assert would throw on false,
- When type assertions are disabled, assert would be removed from the code.

**Comment by jelbourn** [comment]
_copied from my duplicate issue_

#### Idea
Write assertions in components that are applied in dev mode, but stripped out in production mode. The is similar to the type assertions, but more general. 

For example, say you have a `CustomRadio` component that can either in an a `CustomRadioGroup` or be given a name attribute, but not both. The component author could write an assertion:
```js
ASSERT(this.parentGroup XOR this.name, 'CustomRadio must...');
```

This gives the component user a meaningful error in development mode, but does add extra weight to the final output.

#### Prior art
The Closure Compiler implements this concept with the Closure library's [`goog.asserts`](http://docs.closure-library.googlecode.com/git-history/15160ce901b70ac9df5e7d25ae4835835738f782/closure_goog_asserts_asserts.js.html) module.

#### Other notes
A similar approach could also be applied to logging.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
