### ISSUE TITLE
Can't reset a nested form

### ISSUE THREAD

**Issue by sspringer** [angular/angular#11202]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request
```

**Current behavior**

I've created a control that extends FormGroup and that I'm using as a nested form.  It's generating properly, handles validation correctly, and I can send my nested form values back to the containing form group.  The one thing that I can't figure out how to do is to reset the darn thing.

So, what I have is this.  First, here's my child form component.
(I've stripped out most of the code here - I'm just showing the relevant parts).  
```
@Component({
  selector: "nested-form",
  templateUrl: "Content/templates/shared/nestedForm.htm"
})
export class NestedFormComponent extends FormGroup implements OnInit {
  // Implementation omitted
}
```

And here's my parent component with the parent form that instantiates the nested form:
```
@Component({
  selector: "main-form",
  templateUrl: "Content/templates/core/mainForm.htm",
  directives: [NestedFormComponent]
})
export class MainFormComponent implements OnInit {

  public formObj: FormGroup;

  constructor(
    private fb:FormBuilder
  ) { }

  ngOnInit() {
    // Create our form group
    this.formObj= this.fb.group({
        myNested: this.fb.array([new NestedFormComponent()])
    });        
  }

  // Rest of implementation omitted
}
```

The problem is that I have a requirement that the user be able to reset the form back to a pristine state.  However, no matter what I try do to, I can't figure out a way to reset the controls in the nested form back to pristine.

I have even gone as far as trying to implement my own "reset" method on the nested form control and then calling it like this:
```
private resetNestedForm() {
    let nested = <NestedFormComponent>(
      <FormArray>this.formObj.controls["myNested"])
      .controls[0];
    nested.myReset();
  }
```

The problem with this approach is that when I get back that reference to the nested form and get into that ```myReset()``` method, I find that the references to the nested form's controls are gone.  I've got public properties for each of the nested form's controls that I set in the ```ngOnInit``` method of the NestedFormComponent class:
```
this.dropDownControl1Id = new FormControl(this.formDefaults.dropDownControl1IdValue, Validators.required);
this.addControl("dropDownControl1Id ", this.dropDownControl1Id );
this.dropDownControl2Id = new FormControl(this.formDefaults.dropDownControl2IdValue, Validators.required);
this.addControl("dropDownControl2Id ", this.dropDownControl2Id );
this.dropDownControl3Id = new FormControl(this.formDefaults.dropDownControl3IdValue, Validators.required);
 this.addControl("dropDownControl3Id ", this.dropDownControl3Id );
```

When I get into ```myReset()```, the properties ```dropDownControl1Id```, ```dropDownControl2Id```, and ```dropDownControl3Id``` are all ```null```, and  ```this.controls``` is empty - yet the subform is working as you would expect it to in every other way.

**Expected/desired behavior**
 I should be able to either call a reset method on **something**, whether it's the parent form or the child form, and have it reset to a pristine state.  Even if that's not possible, I should, at the very least, be able to get a reference to the child form and reset the individual controls.

**What is the expected behavior?**
I should end up with a nested form reset to it's initial state.  If I have drop downs that have default values, those drop downs should be reset to those default values.  If I have text boxes with prompts, those text boxes should be reset to empty values and the prompts should appear.  If I have any controls that don't display an initial state, like a radio button, then those controls should be set back to that "unset" state.  Also, the underlying state of the nested form should be "pristine".

I _should_ also be able to get a reference to the nested form containing the controls through the parent form.  I even went as far as setting a reference to the nested form first in the parent control, passing that reference to the FormBuilder call that creates the parent form, and trying to access the nested form through that reference.

**What is the motivation / use case for changing the behavior?**
This is a fairly common use case. User's are filling out a form, realize they've screwed it up beyond any possibility of fixing it, and hit the "Reset" button option to start over.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
* **Browser:** all
* **Language:** TypeScript 1.8.10

**Comment by zoechi** [comment]
Please provide a Plunker that allows to reproduce.

**Comment by kara** [comment]
@sspringer You should be able to call `this.form.reset()` to do so. Are you implementing `ControlValueAccessor` in your nested form component?    As long as you do that correctly, resetting should work fine.  A minimal reproduction on plunker would be helpful to define your use case more clearly.

**Comment by sspringer** [comment]
I ended up refactoring the code and eliminated the issue through the refactor, but when I get a free moment I'll attempt to put a plunker together with a scaled-down version of the form.

**Comment by pkozlowski-opensource** [comment]
> when I get a free moment I'll attempt to put a plunker together with a scaled-down version of the original form for you to take a look at.

Awesome! Please share a plunker when you've got one. I will close this issue for now but will re-open it as soon as you've got a reproduce scenario.
