### ISSUE TITLE
Router, lazy-loaded module: loading children into named outlet throws NoMatch error

### ISSUE THREAD

**Issue by mrkosima** [angular/angular#11208]
**I'm submitting a [x] bug report**

**Current behavior**
Error when navigating to lazy loaded route with lazy loaded children into named outlet:
_Error: Uncaught (in promise): Error: Cannot match any routes: ..._

**Expected/desired behavior**
Navigating to lazy loaded route with lazy loaded children in named outlet without errors

**Reproduction of the problem**
https://embed.plnkr.co/HgZjNRdrYSvnmdzE01zO/
Click Primary->Level1 - works ok.
Click OutletA->Level2 - got error.
Click OutletB->Level1 - got error

**Notes**
Additional experimental cases with modules and routes you can find in repo:
https://github.com/mrkosima/angular-rc5-router-lazy-in-lazy

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5/2.0.0-rc.6

* **Router version:** 3.0.0-rc.1/3.0.0-rc.2
 
* **Browser:** [Chrome 52] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by mrkosima** [comment]
reproduced with `angular:2.0.0-rc.6` and `router:3.0.0-rc.2`

**Comment by vijayantkatyal** [comment]
i'm having the same issue.

**Comment by michaelchiche** [comment]
we have the same problem in our app :(

**Comment by ivanStraltsou** [comment]
same issue

**Comment by srenaudon** [comment]
Same kind of issue ...
Routes defined in named outlet in a lazy-loaded module are not matched .

**Comment by peripraveen** [comment]
Same problem here! Hoping for a fix/workaround asap.

**Comment by Igor-Baimastruc-Technosoft** [comment]
we have similar issue.

**Comment by molcik** [comment]
Is it going to work some day? Or "Componentless route cannot have a named outlet set" and, it should be feature request?

**Comment by mrkosima** [comment]
@molcik, good question
tnx for opening #12842

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781520/69f2dbb4-b7be-11e6-9226-26136df19134.png)
![Uploading 图片.png…]()
