### ISSUE TITLE
Async templates variables rendering doesn't work in IE9

### ISSUE THREAD

**Issue by e-oz** [angular/angular#11204]
```
[x] bug report
```

Try to load some data using XHR request and fulfill some template with received data. XHR will be executed successfully, but template will not be changed after that.

Sorry, I can't provide plnkr to reproduce, because plnkr doesn't work in IE9.

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [IE 9] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by vicb** [comment]
- Provide a plunker, we'll figure out how to run the code on IE9,
- Even better a PR with a failing integration test.

Thanks.

**Comment by vicb** [comment]
Actually please re-open an issue when the repro is ready. Thanks.

**Comment by e-oz** [comment]
Ok, as soon as https://saucelabs.com/u/angular2-ci will be green for IE 9 ;)

**Comment by e-oz** [comment]
Sorry for necro-posting, but this bug is fixed in 2.1.0.
