### ISSUE TITLE
NgIf directive throws in ProtoView instantiation

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1120]
```html
<style>@import "material_button.scss.css";</style>
<div class="wrapper"
     [class.raised]="raised"
     [class.disabled]="disabled">
  <material-shadow *if="raised"><span></span></material-shadow>
  <span class="content"><content></content></span>
</div>
```

Where `material-shadow` is a component, and `raised` is a boolean in `material_button`, on:

```dart
if (isPresent(binder.parent) && identical(binder.distanceToParent, 1)) {
  // Exception: Uncaught Error: RangeError: index (1) must be in the range [0..1)
  destLightDom = lightDoms[binder.parent.index];
}
```

This is using `NativeShadowDomStrategy` and Dart, if it's not clear.

**Comment by rkirov** [comment]
I have encountered this before, the one liner in `modules/angular2/src/core/compiler/pipeline/element_binder_builder.js` in #996 might fix it. Needs a proper integration test in `shadow_dom_integration_spec`.

**Comment by naomiblack** [comment]
@rkirov do you have bandwidth to close this one?

**Comment by yjbanov** [comment]
Reassigned to @tbosch because this looks like a shadow DOM emulation problem (our `lightDoms` are messed up).

**Comment by matanlurey** [comment]
This was verified as fixed. Thanks!
