### ISSUE TITLE
How do I prevent code from being evaluated in templates?

### ISSUE THREAD

**Issue by ericjim** [angular/angular#11203]
```
[X] bug
```

**Current behavior**
Consider the following angular 2 template. (In both JIT and AOT)
```
Evaluate: <code> {{ 2 + 2 }} </code>
Do not evaluate: <code ng-non-bindable> {{ 2 + 2 }} </code> 
```

The HTML output of this template is
```
Evaluate: 4
Do not evaluate: 4
```

**Expected/desired behavior**
I would've expected that using `ng-non-bindable` on `code` would've prevented the evaluation of the template

**What is the motivation / use case for changing the behavior?**
I would like to create code examples on a documentation website, and I would like an angular 2 component to be able to display angular 2 code.

* **Angular version:** 2.0.0-ef0f29c
 
* **Browser:** Chrome 52 on macOS El Capitan
 
* **Language:** TypeScript 2.0

**Comment by pkozlowski-opensource** [comment]
It is `ngNonBindable`

**Comment by ericjim** [comment]
Thanks @pkozlowski-opensource I had a hard time finding any documentation on this https://angular.io/docs/ts/latest/api/#!?apiFilter=ngnonbindable

**Comment by vicb** [comment]
@ericjim could you open an issue on our doc repo https://github.com/angular/angular.io 

thanks

**Comment by ericjim** [comment]
https://github.com/angular/angular.io/issues/2236
