### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sstriano** [angular/angular#11205]
RC5, Forms 0.3.0

**Current behavior**
Given the following form:

     this.form = this.formBuilder.group({
            merchantOrderId: this.return.merchantOrderId,
            agreeToReturnCharge: [true, Validators.required],
            returnChargeFeedback: [null],
            items: this.formBuilder.array(this.configureFormItems(this.return))
        });
`

When an item changes in the `items` `FormArray`:

    let itemsArray = <FormArray>this.form.controls['items'];
    this.subscriptions.push(itemsArray.valueChanges.subscribe(value => {
            let items: models.JetReturnItem[] = (<models.JetReturnItem[]>value);

            items.forEach((item: models.JetReturnItem, index: number) => {
                let control = itemsArray.controls[index];
                let refundFeedback = control.get('refundFeedback');

                refundFeedback.clearValidators();
                if (item.refundAmount.principal < item.requestedRefundAmount.principal) {
                    refundFeedback.setValidators(Validators.required);
                }
                refundFeedback.updateValueAndValidity();
            });
        }));`

Calling the `refundFeedback.updateValueAndValidity();` causes this error.

How do you add/remove validators and force validation to run with out this error?

* **Angular version:** 2.0.0-rc.5

**Comment by vicb** [comment]
When creating an issue, please fill out the templates and provide a plunker.

We have too many incoming issue to afford spending time doing it.

**Comment by sstriano** [comment]
Could you please provide some examples of more advanced form usage in the documentation?

**Comment by zoechi** [comment]
@sstriano documentation issues should be reported in https://github.com/angular/angular.io/issues

**Comment by martinpalmieri** [comment]
One thing you can try is to set the emitEvent on false for that formControl updateValueAndValidity method.

for example something like this:

`refundFeedback.updateValueAndValidity({emitEvent : false});`

**from Angular docs**:

> If emitEvent is true, this change will cause a valueChanges event on the FormControl to be emitted. This defaults to true (as it falls through to updateValueAndValidity).

Also you have the possibility to onlySelf to false (is true by default) like this:

`refundFeedback.updateValueAndValidity({onlySelf : true});`

**from Angular docs**:

> If onlySelf is true, this change will only affect the validation of this FormControl and not its parent component. This defaults to false.

I was having a similar problem with a tricky and big form. emitEvent saves me.

Hope it helps you.

Learn more about formControls here: [](https://angular.io/docs/ts/latest/api/forms/index/FormControl-class.html)
