### ISSUE TITLE
events does not work if content is positioned absolute

### ISSUE THREAD

**Issue by dylanb** [angular/angular#1121]
Given the following code:

```
import {Component, Template, bootstrap, NgElement} from 'angular2/angular2';

@Component({
    selector: 'event-element',
    events: {
        'click': 'onClick($event)'
    }
})
@Template({
    inline: `
        <span style="position:absolute;"><content></content></span>
    `
})
class EventElement {
    constructor(el:NgElement) {
        el.domElement.addEventListener('click', function (e) {
            console.log('native click');
        }, false);
    }
    onClick(e) {
        console.log('Angular2 events click');
    }
}
@Component({
    selector:'event-app'
})
@Template({
  inline: `
    <event-element>Content</event-element>
    `,
    directives:[EventElement]
})
class MyApp {
}
bootstrap(MyApp);
```

and the following HTML file

```
<!doctype html>
<html>
  <head>
    <title>Event Binding</title>
    <script src="/quickstart/dist/es6-shim.js"></script>
  </head>
  <body>
  	<event-app>Loading...</event-app>
	<script>
	// Rewrite the paths to load the files
	System.paths = {
		'angular2/*':'/quickstart/angular2/*.js', // Angular
		'rtts_assert/*': '/quickstart/rtts_assert/*.js', //Runtime assertions
		'event-app': 'eventapp.es6'
	};

	// Kick off the application
	System.import('event-app');
	</script>
  </body>
</html>
```

If the `position:absolute;` is removed from the style on the template then the event handlers for the native and the Angular 2 events attribute will be called. If it remains there, only the native event handler is called.

Both event handlers should be called regardless of the positioning

**Comment by jelbourn** [comment]
Does it work if you change `'click': 'onClick($event)'` to `'^click': 'onClick($event)'` ?

**Comment by dylanb** [comment]
yes

**Comment by jelbourn** [comment]
Are you sure your click is actually on the element with the click handler and not some child?

**Comment by dylanb** [comment]
In both instances, I am clicking the same element. In both instances the native handler always gets called once. Only with the Angular 2 events attribute does the component callback not get called when position:absolute styling is applied to the child. This makes no sense.

Yes, the actual element getting click is inside the child but if that is not correct behavior, then the bug is that it gets called when position:absolute is not applied. Either way there is a bug here.

**Comment by dylanb** [comment]
wait a minute, my bad, looks like I was mixing up two changes here and this does in fact look like its working properly - apologoies

**Comment by nviv77** [comment]
I am trying to build autosuggest component. The result list should be absolute to the input textfield. 
I am facing the same issue, below is code sample. I have given absolute position to "autosuggestlist" id.


<div class="input-group">
    <input #searchBox id="search-box" type="text"  [placeholder]="holder" class="form-control" (keyup)="search(searchBox.value)">
    <div class="input-group-addon">
        <span class="glyphicon glyphicon-search"></span>
    </div>
    <div id="autosuggestlist">
      <div *ngFor="let hero of heroes | async"
          (click)="gotoDetail(hero)" class="search-result" >
          {{hero}}
      </div>
  </div>
</div>


.input-group{
position: relative;
top:0px;
left:0px;
}
#autosuggestlist{
position: absolute;
top: 17px;
left:0px;
}
