### ISSUE TITLE
bug(DomSchema): `<time>`, `<summary>` els aren't allowed

### ISSUE THREAD

**Issue by laco0416** [angular/angular#11219]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`<time>`, `<summary>` element isn't allowed.

**Expected/desired behavior**
The tag is a standard HTML5 tag.
https://www.w3.org/TR/html5/text-level-semantics.html#the-time-element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time
It should be recognized correctly.

**Reproduction of the problem**
http://plnkr.co/edit/SZJms0

**What is the expected behavior?**
broken. (please see console log)

```
'time' is not a known element:
1. If 'time' is an Angular component, then verify that it is part of this module.
2. If 'time' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("
    <div>
      <h2>Hello {{name}}</h2>
      [ERROR ->]<time>20:00</time>
    </div>
  "): App@3:6 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by laco0416** [comment]
cc/ @vicb @mprobst 
https://github.com/angular/angular/issues/11079#issuecomment-243965889

**Comment by vicb** [comment]
Good catch !
PR appreciated (please follow the guidelines in #11221, ie modify the generator instead of the generated code). Thanks.

**Comment by laco0416** [comment]
@vicb Unexpectedly, `HTMLTimeElement` is not implemented on Chrome.

**Comment by vicb** [comment]
yep
```
t = document.createElement('time')
t.constructor
HTMLUnknownElement() { [native code] }

p = document.createElement('p')
p.constructor
HTMLParagraphElement() { [native code] }
```

**Comment by vicb** [comment]
Could you submit a PR to manually add `time` to the extractor + regenerate the file.

Then [the idea](https://github.com/angular/angular/blob/96697029c9993ac8e99e61e222547fb58b472f8a/modules/%40angular/compiler/test/schema/schema_extractor.ts#L160) is to generate the map (switch/case) dynamically by using all the els listed in the html5 specs - this is more work and longer term .

**Comment by SamVerschueren** [comment]
For people bumping into this, adding this component as a temporary fix prevents you from replacing all the `time` tags in your project.

```ts
import { Component } from '@angular/core';

@Component({
	selector: 'time',
	template: '<ng-content></ng-content>'
})
export class TimeComponent {}
```

**Comment by laco0416** [comment]
@vicb submitted. https://github.com/angular/angular/pull/11232

**Comment by vicb** [comment]
@SamVerschueren 

```
import { Directive } from '@angular/core';
@Directive({ selector: 'time'})
export class TimeDirective {}
```

**Comment by SamVerschueren** [comment]
@vicb Ow sweat! :)

**Comment by nertzy** [comment]
`<summary>` has the same issue. Should this issue cover all missing HTML5 elements or should I open another one?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

**Comment by laco0416** [comment]
`<data>` seems same

**Comment by mprobst** [comment]
@rjamet FYI and for security sanity check.

**Comment by vicb** [comment]
@mprobst I'm working on a PR, will submit and cc the security squad
