### ISSUE TITLE
parent component fetch/modify instance data from a viewContainerRef index element after the instance data has originally been defined

### ISSUE THREAD

**Issue by mcferren** [angular/angular#11223]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

How does a parent component fetch/modify instance data from an index element of this.viewContainerRef after it has originally been defined? ie http://stackoverflow.com/questions/39243748/angular-2-passing-data-to-component-when-dynamically-adding-the-component   Inside each ViewRef of the ViewContainerRef this.viewContainerRef. object, I can see there is a nested private property called view: _view:_View_Node_Host0 Why is that property private and are there any plans in the future to offer a ViewRef accessor/modifier function to fetch/mutate that property and its nested values? As of now, I have had to store the cmpRef variable in a separate array in order to gain access to the instance data.

**Expected/desired behavior**

this.viewContainerRef.get(0).instance...

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

so parent can access / modify child ViewRef's

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by vicb** [comment]
Please fill update the content for the following sections:

- Current behavior
- Expected/desired behavior
- Reproduction of the problem

There are too many incoming issues/fr for us to spend time trying to decrypt them.

Thanks.

**Comment by pkozlowski-opensource** [comment]
Closing as we haven't heard back from the opener.
