### ISSUE TITLE
RC.6 Bundled emit with --out is not supported 

### ISSUE THREAD

**Issue by huyaxiong** [angular/angular#11224]
Hey,I am trying to use AoT compilation,And I am sure my code doesn't have any error.And when i type command "./node_modules/.bin/ngc".It shows "Bundled emit with --out is not supported ".

And I am using System.js with umd bundles,I don't know what is it means.Is there something like a "AoT compilation document" at somewhere so I can see how to use it.

**Comment by vicb** [comment]
Docs live at angular.io 

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
