### ISSUE TITLE
Routing with hash and simple href

### ISSUE THREAD

**Issue by xaviergxf** [angular/angular#11225]
**I'm submitting a routing problem **  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**I'm using angular 2 routing and implementing a bootstrap 4 tab system. When the user clicks on the tab it should not navigate to any existing route, it should stay in the same page and access the tab's content.
Here's how the component and route are currently implemented:

```
const appRoutes: Routes = [
    { path: '**', component: DPMMasterDetailComponent, resolve: { application: DPMApplicationService, user: DPMUserService, applicationView: DPMApplicationViewService, modelMetadata: DPMModelMetadataService } }
];
```

```
<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#main" role="tab">Main</a>
    </li>
    <li class="nav-item" *ngFor="let metadataField of complexMetadataFields">
        <a class="nav-link" data-toggle="tab" [href]="'#'+GetNormalizedMetadataName(metadataField)" role="tab">{{metadataField.ModelField.Label | dpmEEFS}}</a>
    </li>
</ul>
```

**

**Expected behavior: The routing system does nothing and the user stays in the same page.**

**Current behavior: The routing system redirects to the new page http://localhost:64384/#tabpage **

**Windows and Chrome 52**

* **Angular version:** 2.0.0-rc.5
 
* **Language:** TypeScript

**Comment by vicb** [comment]
> [X ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

:)
