### ISSUE TITLE
ViewEncapsulation.Default results different then .Native (Was consistent before rc6)

### ISSUE THREAD

**Issue by deebloo** [angular/angular#11220]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using Native shadow dom, element inserted using ng-content will be styled based on the parent component.

When using Emulated the inserted element is NOT styled based on the parent.

**Expected/desired behavior**
I would expect the Emulated shadow dom to behave as the Native one does.

**What is the motivation / use case for changing the behavior?**

I am not sure if this is exactly a bug or not. However since this seems to have changed from RC5 to RC6 and didn't see a note about it I will assume it is a bug.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 2.0]

**Comment by zoechi** [comment]
Plunker to reproduce?

**Comment by vicb** [comment]
> I will assume it is a bug.

That's funny, I assume it is not on my side ;)

https://github.com/angular/angular/pull/10997 might explain the diff.

If it is a real bug, please open a real issue with a plunker: Thanks.
