### ISSUE TITLE
Request to update quickstart to RC6

### ISSUE THREAD

**Issue by sanket360** [angular/angular#11222]
As per CHANGELOG.md, RC6 is released yesterday. However, quick-start guide is not updated. Still referring to RC5. Could anyone please update quick-start article for RC6?

https://angular.io/docs/ts/latest/quickstart.html

![capture1](https://cloud.githubusercontent.com/assets/16756121/18154679/7312c150-7024-11e6-8810-e0a3a2320b89.PNG)

**Comment by zoechi** [comment]
should be reported in https://github.com/angular/angular.io/issues

**Comment by sanket360** [comment]
Thanks @zoechi 
https://github.com/angular/angular.io/issues/2240
