### ISSUE TITLE
Why is the query after hash broken?

### ISSUE THREAD

**Issue by Jenan** [angular/angular#11236]
**Current behavior**

I have used the angular 2 and Auth0 for the authentication. 

If I loggin with Auth0 form then I will be redirect back to my site with the access token in the hash fragment.

I have a problem with the format of value after hash like this:

http://localhost:3000/#access_token**%**3DfpPj0UmvgLIAnbZr......**%**26id_token**%**3DeyJ0e......%26token_type%3DBearer

Equals is replaced percent etc.

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** IE 11, Chrome 52.0.2743.116
 
* **Language:** TypeScript

**Comment by vicb** [comment]
Should be fixed in RC6, if not re-open an issue and attach a plunker

**Comment by BenDevelopment** [comment]
@Jenan I'm in the same case but I can't extract the access token. When this url is loader, the part after '#' is automatically removed. How did you do to extract the access_token?

**Comment by BenDevelopment** [comment]
I've found the solution here:
http://stackoverflow.com/questions/39668916/angular2-get-url-query-parameters/40058721#40058721

Imports:

```
import { Router, NavigationCancel } from '@angular/router';
import { URLSearchParams, } from '@angular/http';
```
Constructor:

```
 constructor(public router: Router) {
    router.events.subscribe(s => {
      if (s instanceof NavigationCancel) {
        let params = new URLSearchParams(s.url.split('#')[1]);
        let access_token = params.get('access_token');
        let code = params.get('code');
      }
    });
  }
```
