### ISSUE TITLE
Getting build error unable to import provide from @angular/core RC6

### ISSUE THREAD

**Issue by haseeb200** [angular/angular#11241]
I created an app.config.ts file in which I create application config variables. For, this I import OpaqueToken and provide. It was working fine till RC5 but after updating to RC6 I am unable to import provide from @angular/core

```
import { OpaqueToken, provide } from '@angular/core';

export const APP_CONFIG = new OpaqueToken('config');

const dictionary = {
    apiUrl: 'dummy/api',
};

export const APPCONFIG_PROVIDERS = [
    provide(APP_CONFIG, { useValue: dictionary })
]
```

**Build Error:**

Severity	Code
Error	TS2305	Module '"/node_modules/@angular/core/index"' has no exported member 'provide'.

**Comment by neilhem** [comment]
Looks like it was deprecated in RC.5 & fully removed in RC.6
``` js
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [...],
  providers: [
    appRoutingProviders,
    {provide: APP_CONFIG, useValue: dictionary},
  ],
})

**Comment by ericmartinezr** [comment]
Exactly, just like the breaking changes for RC6 mentions https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

**Comment by pkozlowski-opensource** [comment]
Thnx @neilhem and @ericmartinezr !

**Comment by haseeb200** [comment]
thanks
