### ISSUE TITLE
@angular/upgrade package.json points to the wrong UMD bundle entry point

### ISSUE THREAD

**Issue by justinrassier** [angular/angular#11249]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
@angular/upgrade for rc.6 module's package.json does not point to the correct `bundles/upgrade.umd.js` entry point, which causes webpack builds to break. It currently points to `bundles/core.umd.js`

**Expected/desired behavior**
The "main" entry point in the package.json should point to the upgrade modules `bundles/upgrade.umd.js`

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

1. `npm install @angular/upgrade@2.0.0-rc.6`
2. Import the `UpgradeAdapter` from @angular/upgrade and use the constructor.
3. In a normal webpack build, I receive a 

> Uncaught SyntaxError: Unexpected token export

It appears that since it isn't pointing to the umd entry point, webpack is  bundles the ES2015 export statement directly into the bundle. Therefore the source that causes the browser exception looks like this:

```
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
/**
 * @module
 * @description
 * Entry point for all public APIs of the upgrade package.
 */
export * from './src/upgrade';
//# sourceMappingURL=index.js.map


/*****************
 ** WEBPACK FOOTER
 ** ./~/@angular/upgrade/index.js
 ** module id = 107
 ** module chunks = 0
 **/
```

If you change the package.json entry point to the correct UMD bundle, the webpack build behaves as expected

**What is the expected behavior?**
The expected behavior is a working webpack bundle that follows the package.json import

**What is the motivation / use case for changing the behavior?**
Utilizing the @angular/upgrade module

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [TypeScript X.X ]

**Comment by Colorfulstan** [comment]
For search-reference:

> In a normal webpack build, I receive a
>>Uncaught SyntaxError: Unexpected token export

In a Browserify-tsify-babelify build this issue manifests as the following Error within the babelify step
```
[...]\node_modules\@angular\upgrade\index.js:13
export * from './src/upgrade';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```
if babelify is not set as a global transform.
Changing it to the right UMD bundle ```upgrade.umd.js``` or using babelify with ```{ global: true }``` fixes this for the moment.

**Comment by steffi501** [comment]
+1
