### ISSUE TITLE
How to boot an angular root app component twice on one page

### ISSUE THREAD

**Issue by manishgarg1** [angular/angular#11244]
I have a scenario in which I want to boot the same root AppComponent twice on one page. I can provide different selectors for the component. Can that be done in Angular2 ? If yes, what is the prescribed way of doing that?

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by zoechi** [comment]
dup of #7136
