### ISSUE TITLE
If child component has FormGroup and FormControl, to delete one item from children will throw exception in Chrome  

### ISSUE THREAD

**Issue by chengbiny** [angular/angular#11245]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have ClaimItem class, it has description, cost and refund properties. I created a component to edit single ClaimItem, call it ExpenseItemComponent. Because I need to do validation, so I put it inside a FormGroup. then I create a parent component ExpenseItemsComponent to loop on a collection of  ClaimItem object to hold a list of  ExpenseItemComponent. I have no issue to insert or update child component. But if I try to delete one item, an exception is throw in Chrome. Following is error message I got:

"TypeError: Method Number.prototype.toFixed called on incompatible receiver #<Object>↵    at Object.toFixed (native)↵    at https://localhost:44353/dist/lib/node_modules/core-js/client/shim.min.js:7:20112↵    at a.exports (https://localhost:44353/dist/lib/node_modules/core-js/client/shim.min.js:7:5252)↵    at Object.<anonymous> (https://localhost:44353/dist/lib/node_modules/core-js/client/shim.min.js:7:20098)↵    at __webpack_require__ (https://localhost:44353/dist/lib/node_modules/core-js/client/shim.min.js:7:155)↵    at Object.<anonymous> (https://localhost:44353/dist/lib/node_modules/core-js/client/shim.min.js:7:486)↵    at __webpack_require__ (https://localhost:44353/dist/lib/node_modules/core-js/client/shim.min.js:7:155)↵    at https://localhost:44353/dist/lib/node_modules/core-js/client/shim.min.js:7:314↵    at https://localhost:44353/dist/lib/node_modules/core-js/client/shim.min.js:7:337↵    at https://localhost:44353/dist/lib/node_modules/core-js/client/shim.min.js:9:14829"

I tested IE and Firefox, they have no issue. Only Chrome throw the exception. If I remove FormGroup and FormControl from ExpenseItemComponent, it has no issue. So it is when I have FormGroup in child component and I need to delete one item, Chrome has issue. I am using Angular 2 RC5.

[issue.zip](https://github.com/angular/angular/files/450287/issue.zip)

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?** It shouldn't throw exception.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X  it is 2.0.0-rc.5
 
* **Browser:** [ Chrome XX ] 
 
* **Language:** [ TypeScript X.X]

**Comment by kara** [comment]
@chengbiny Can you link to a minimal reproduction on plunker?

**Comment by kara** [comment]
Closing, as we haven't been able to reproduce. Please feel free to open a new issue with a plunker that demonstrates the problem.
