### ISSUE TITLE
Feature Request: 'templateId' selection of a <script name="aTemplate" type="text/template"> template text

### ISSUE THREAD

**Issue by AaronNGray** [angular/angular#11247]
I am submitting a feature request for an extra Component directive 'templateId'

given an index.html with

    <script id="aScriptTemplate" type="text/template">
        <h1>My First Angular 2 App with script templates</h1>
    </script>

with 

    @Component({
        selector: 'my-app',
        templateId: 'aScriptTemplate'
    })

equivalent to the following :-

    @Component({
        selector: 'my-app',
        template: document.getElementById('aScriptTemplate').innerText
    })

Is it too late to request this now ?

**Comment by vicb** [comment]
> Is it too late to request this now ?

For angular2 final yes but we'll consider it for a later release. Could you please merge with your other FR ?

**Comment by AaronNGray** [comment]
AFAICS they are different functionality as this one is very simple to implement compared to https://github.com/angular/angular/issues/11248
