### ISSUE TITLE
Caching/code-gen story for CSS needed

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1124]
Spoke briefly with @jelbourn, but it looks like the Angular 2 "way" to use CSS in a component is:

```html
<style>@import "style.css";</style>
<div>
  ...
</div>
```

For templates, we use the `Template` annotation:

```dart
@Template(
  url: "my_component.html"
)
```

The advantage of this is a pre-compile step can do static analysis, and convert URLs into an inline of the HTML, reducing the number of HTTP requests and files needed for a statically generated application. In angular 1, this was called `"template_cache"`.

If the official stance of Angular 2 is using `<style>@import</style>`, will this be something that is also scanned and in-lined in applications that use static analysis? 

++ @kegluneq, @mhevery, @yjbanov

**Comment by yjbanov** [comment]
Yes. We want to inline templates and styles for production deployment.

**Comment by yjbanov** [comment]
As for story, the templates are processed by compiler, which can run in the browser as well as outside in the transformer. For production deployment the compiler runs as part of the pub transformer and inlines everything, as well as turns expressions in the templates into plain Dart code, links to directives, etc. Very little of template interpretation will be done at runtime.

**Comment by matanlurey** [comment]
Thanks. I'll make a note of this and continue using <style>@import</style> then.

Feel free to close if tracked elsewhere.

**Comment by matanlurey** [comment]
I have an additional complexity: in current applications, we have some components that optimize:

```dart
@Component(
  selector: 'button',
  templateUrl: 'button.html',
  cssUrl: 'button.css'
)
@Component(
  selector: 'button[flat]'
  templateUrl: 'button.html',
  cssUrl: 'flat_button.css'
)
class ButtonComponent {}
```

Unless the `<style>` tag supports some sort of custom property, we lose this ability. 

Strawman:

```html
<style if="$selector == 'button'">@import "button.css"</style>
<style if="$selector == 'button[flat]'>@import "flat.css"</style>
```

++ @jbdeboer.

**Comment by yjbanov** [comment]
What if we also support importing HTML into the template, e.g.:

button.html:
```
<style>@import "button.css"</style>
@import "button_common.html"
```

button_flat.html:
```
<style>@import "button_flat.css"</style>
@import "button_common.html"
```

**Comment by naomiblack** [comment]
Need a preliminary decision on the syntax to use here in M7. Actual implementation can defer to M8.

**Comment by matanlurey** [comment]
I've been dragging my feet on this, but I'll have something by early next week.

**Comment by jbdeboer** [comment]
@naomiblack @yjbanov Please up the priority on this issue.

We are starting to write [a lot of] templates using the format
```
<style>import xx.css</style>
...
```
in the template file. If you are changing the format, please do it soon to avoid rework.

**Comment by vicb** [comment]
@jbdeboer the plan is to support both `@import` & `cssUrl`. (as we need to support `@import` for `cssUrl` imported stylesheets anyway) /ref #1239

**Comment by yjbanov** [comment]
After some offline discussion we seemed to agree that the premise behind this issue is no longer relevant. We intend to support neither multiple `@Comopnent` annotations nor multiple stylesheets. So I'm closing this issue. Let's discuss `@import` vs `cssUrl` on #1239
