### ISSUE TITLE
Angular Documentation 

### ISSUE THREAD

**Issue by samdevx1029** [angular/angular#11242]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
[Documentation on upgrading angular2 from RC4 to RC5](https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html) provides instructions. The very first instruction is as follows.
npm install @angular/{core,common,compiler,platform-browser,platform-browser-dynamic} --save
On Windows 10, this command does not work. I get this error

npm ERR! addLocal Could not install C:\Users\sfbow\Source\Repos\newapp\@angular\{core,common,compiler,platform-browser,platform-browser-dynamic}
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sfbow\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@angular/{core,common,compiler,platform-browser,platform-browser-dynamic}" "--save"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! path C:\Users\sfbow\Source\Repos\newapp\@angular\{core,common,compiler,platform-browser,platform-browser-dynamic}
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\sfbow\Source\Repos\newapp\@angular\{core,common,compiler,platform-browser,platform-browser-dynamic}'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\sfbow\Source\Repos\newapp\@angular\{core,common,compiler,platform-browser,platform-browser-dynamic}'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sfbow\Source\Repos\newapp\npm-debug.log

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by vicb** [comment]
docs repo is https://github.com/angular/angular.io, please re-open there
