### ISSUE TITLE
Feature Request: templateUrl multiple named template script selection

### ISSUE THREAD

**Issue by AaronNGray** [angular/angular#11248]
I am submitting a feature request for an Component directive 'templateUrl' #name extension

given an templates.html with

    <script name="aScriptTemplate" type="text/template">
        <h1>Angular 2 App with script templates</h1>
    </script>
    <script name="anotherScriptTemplate" type="text/template">
        <h1>Angular 2 App with multiple script templates</h1>
    </script>

and 

    @Component({
        selector: 'my-app',
        templateUrl: 'templates.html#aScriptTemplate'
    })
    ....

    @Component({
        selector: 'my-template,
        templateUrl: 'templates.html#anotherScriptTemplate'
    })
    ....

**Comment by AaronNGray** [comment]
My other feature request https://github.com/angular/angular/issues/11247 that is easy to implement compared to this one

**Comment by shlomiassaf** [comment]
@AaronNGray what's the motivation behind this?

**Comment by AaronNGray** [comment]
To be able to have a group of templates in a single file for efficient loading of a group templates for a module / subpage.

Also my other feature request https://github.com/angular/angular/issues/11247 would allow the main ones to be bundled with the index.html page.

**Comment by vicb** [comment]
> To be able to have a group of templates in a single file for efficient loading for a module / subpage. Reducing the number of HTTP GET's

With AoT, templates are compiled to js and not fetched - fetching would only be used in dev mode

**Comment by AaronNGray** [comment]
Does AoT give separation of concerns between HTML markup and JavaScript code ?

**Comment by vicb** [comment]
AoT is only a compilation step.

You write your Angular2 code as you always have loved to do and then you `ngc` to create js code.

**Comment by d3lm** [comment]
I actually like this feature request. My motivation behind this that I could fetch for example the template for a container component via HTTP. When using an ASP.NET backend, if you request a `.cshtml` file, that template gets rendered on the server side. I could then include script tags for other templates inside there, which will also be rendered on the server side. So I reduce the amount of HTTP calls tremendously. Only the template for the container is fetched and all sub-templates for inner dumb components is "inlined" via script tags. AoT does not work for server side rendering in combination with a C# backend, does it?

**Comment by pkozlowski-opensource** [comment]
@AaronNGray AoT is a proper answer here.

**Comment by AaronNGray** [comment]
not perfect would have preferred something like separate XML like templates
possibly along the lines of XAML.

**Comment by Kriskit** [comment]
Like @d3lm we have need for bundling my templates into a single URL to reduce the number of template requests. We cannot support AoT as our underlying ASP.NET MVC site is using a proprietary CMS which enables us to edit content in the templates, these can be multi-language and vary depending on client type (desktop/mobile) using a custom [UrlResolver](https://github.com/angular/angular/blob/59d2b4c8312580add5717dd20ea0a6cde79738f7/modules/%40angular/compiler/src/url_resolver.ts). 

I don't think some sort of crazy online process that compiles the templates every time someone updates the content in the CMS would be appropriate. However, being able to specify multiple component templates in a single file would be useful.
