### ISSUE TITLE
ng-content does not work for elements selected by element name in RC6

### ISSUE THREAD

**Issue by Eduardo-M-Cavalcanti** [angular/angular#11261]
```
[X] bug report
```
**Current behavior**
Error in RC6.

**Expected/desired behavior**
To work as in RC5.

**Reproduction of the problem**
Does not work in RC6:
http://plnkr.co/edit/HvUWDOYm5LjRvzd6uNZO?p=preview
Works fine in RC5:
https://plnkr.co/edit/EAfHdO?p=preview

**What is the expected behavior?**
**What is the motivation / use case for changing the behavior?**
**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.6
 * **Browser:** [Chrome 53 | Firefox 48] 
 * **Language:** [TypeScript] 

![ng-content error rc6](https://cloud.githubusercontent.com/assets/1670984/18189347/7a40b9fc-7090-11e6-991c-c35847e4eb23.jpg)

**Comment by AnimaMundi** [comment]
#11251 See the comments here on your original issue.
It seems that this is intended and it will improve in the future.

**Comment by Eduardo-M-Cavalcanti** [comment]
Thank you, @AnimaMundi and @vicb.
