### ISSUE TITLE
when update rc5 to rc6, the lazy-load module throw a error

### ISSUE THREAD

**Issue by lhtin** [angular/angular#11266]
the lazy load module BoardModule need NgIf directives, so I import CommonModule, the AppModule aslo import BrowserModule. then throw below error:

`Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead`

It is a bug or use fail? thx

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** Chrome 52
 
* **Language:** TypeScript 1.8.10

**Comment by zoechi** [comment]
Please provide a Plunker that allows to reproduce the issue.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by doxiaodong** [comment]
use `BrowserModule` in rootModule and others use `CommonModule` from '@angular/common'

**Comment by lhtin** [comment]
@zoechi Plunker did not have angular rc6 library. 

So I look at the source, here is I find the different between them about the error:

file path: *@angular/platform-browser/src/browser.d.ts*

**rc6**

```js
/**
 * The ng module for the browser.
 *
 * @stable
 */
export declare class BrowserModule {
    constructor(parentModule: BrowserModule);
}
```

**rc5**
```js
/**
 * The ng module for the browser.
 *
 * @experimental
 */
export declare class BrowserModule {
}
```

and the error throw file: https://github.com/angular/angular/blob/979657989bab4fb93faf6a207d30760faa9bd696/modules/%40angular/platform-browser/src/browser.ts
```ts
export class BrowserModule {
  constructor(@Optional() @SkipSelf() parentModule: BrowserModule) {
    if (parentModule) {
      throw new Error(
          `BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`);
    }
  }
}
```

**Comment by lhtin** [comment]
@doxiaodong I just do like you say.

**Comment by lhtin** [comment]
I am very sorry, it is my misuse. I forget the `BoardModule` import a `MyCommonModule`, and The `MyCommonModule` import `BrowserModule`.
