### ISSUE TITLE
Link to "Clone the entire Quickstart Application" for TS is broken

### ISSUE THREAD

**Issue by shyamseshadri** [angular/angular#11267]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

On the live quickstart page for TS (https://angular.io/docs/ts/latest/quickstart.html), the link to "clone the entire QuickStart application" is incorrect, and has a space after github and before .com. It is currently linked to https://github%20.com/angular/quickstart/blob/master/README.md

**Expected/desired behavior**

It should link to https://github.com/angular/quickstart/blob/master/README.md

**Reproduction of the problem**

1. Go to https://angular.io/docs/ts/latest/quickstart.html
2. Click on "clone the entire QuickStart application"

**What is the motivation / use case for changing the behavior?**

- New Users cannot get started with AngularJS 2 in TypeScript

**Please tell us about your environment:**

* **Angular version:** Live
 
* **Browser:** [all  ] 
 
* **Language:** [TypeScript ]

**Comment by wesleycho** [comment]
This should have been filed in the https://github.com/angular/angular.io repository, not here.

The culprit appears to be https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/quickstart.jade#L43
