### ISSUE TITLE
Tag like <center>, <big> causes template parsing error

### ISSUE THREAD

**Issue by elaijuh** [angular/angular#11270]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
DOM markup tag like `<center>`, `<big>` will cause error like this
```
Template parse errors:
'center' is not a known element:
1. If 'center' is an Angular component, then verify that it is part of this module.
2. If 'center' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("[ERROR ->]<center> My First Angular 2 App</center>"): AppComponent@0:0 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
'center' is not a known element:
1. If 'center' is an Angular component, then verify that it is part of this module.
2. If 'center' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("[ERROR ->]<center> My First Angular 2 App</center>"): AppComponent@0:0
```

**Expected/desired behavior**
It should parse the template normal, but it acts like not recognizing HTML4 tags

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** Chrome
 
* **Language:** TypeScript 2.0.0

**Comment by pkozlowski-opensource** [comment]
Both `<center>` and `<big>` are deprecated and come with a big red warning, check:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/big
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

> This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Do not use it in old or new projects. Pages or Web apps using it may break at any time.

> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

As you can see it has very explicit warning saying "could be removed at any time" and "Pages or Web apps using it may break at any time". As such I don't think we want to encourage usage of those tags in Angular.

**Comment by elaijuh** [comment]
got it thanks, i just change the tag to style.

**Comment by mmesko** [comment]
I have the same problem with <menuitem> tag. This tag isn't deprecated. Can someone suggest how to solve it? This didn't happen in RC4.

**Comment by richardsengers** [comment]
In some cases people still want to make use of those tags.
For example I'm including an email html into my app where center is still an important tag.

**Comment by DzmitryShylovich** [comment]
add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component

**Comment by richardsengers** [comment]
Yeah I've read it and tried it but that doesn't work either. Thanks for the reply

**Comment by DzmitryShylovich** [comment]
@richardsengers wrong schema :) You need `NO_ERRORS_SCHEMA`
https://plnkr.co/edit/4SAVXRjvYOLE270KbkHk?p=preview

**Comment by richardsengers** [comment]
@DzmitryShylovich thank you very much. It solves the problem. Strange that CUSTOM_ELEMENTS_SCHEMA is all over the internet as a solution

**Comment by DzmitryShylovich** [comment]
@richardsengers we will improve the error message
