### ISSUE TITLE
Pipes ignore user culture and use only default en-US

### ISSUE THREAD

**Issue by matteo-mosca** [angular/angular#11274]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Pipes clearly state in the documentation that they use INTL to display numbers, dates, etc in the user culture. INTL is indeed used, but there is a hardcoded 'defaultLocale = "en-US"' in the various pipe sources and it is used like that, so the user cultuer is ignored.

**Expected/desired behavior**
Instead of using a hardcoded culture value let INTL infer the culture to use from the user settings, as it should be and as the documentation already explains.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**
As described above

**What is the motivation / use case for changing the behavior?**
It is not working as it should

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by mattlewis92** [comment]
As of RC6 I think this is now possible by using the `LOCALE_ID` token: https://github.com/angular/angular/blob/master/modules/%40angular/common/src/pipes/date_pipe.ts#L98

```
import {LOCALE_ID} from '@angular/core';

// in your component / module providers definition
{provide: LOCALE_ID, useValue: 'de'}
```

**Comment by DaSchTour** [comment]
So as of RC6 every application needs the following two lines in every module and/or component?

```typescript
import {LOCALE_ID} from '@angular/core';
// in your component / module providers definition
{provide: LOCALE_ID, useValue: window.navigator.language}
```

Just to get the expected behaviour for the other 95% of world population that doesn't live in the USA?

**Comment by mattlewis92** [comment]
Well you only need it in your root module and it should propagate all the way down to the rest of your application 😀

**Comment by DzmitryShylovich** [comment]
@DaSchTour https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-module-provider-visibility

**Comment by vicb** [comment]
@DaSchTour you only need to provide one LOCALE_ID at the application level. It will propagate down the DI tree.

**Comment by DaSchTour** [comment]
Did anybody though about not defaulting the world to en-US?

**Comment by vicb** [comment]
> Did anybody thought about not defaulting the world to en-US?

useless debate.

**Comment by matteo-mosca** [comment]
In Angular Final 2.0.0 the problem still persists. In core.umd.js at line 7930:

`{ provide: LOCALE_ID, useValue: 'en-US' },`

The only way to localize my app is to edit the source and change the culture, but still no dynamic culture based on the user settings.

This is the "Final" release of Angular2 not an RC anymore, this was supposed to be fixed.
