### ISSUE TITLE
RC 5: Service instances are not shared between modules

### ISSUE THREAD

**Issue by DirkWillem** [angular/angular#11273]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have 2 `@NgModule`s, and a third module containing all services. The services module contains a service with a RxJS Subject, which should be shared by all other components using that service. However, the 2 `NgModule`s don't share the same instance so this service won't work anymore.

I could solve this using a singleton, but probably there are many more cases which are affected by this behaviour.

**Expected/desired behavior**

Instances of the `providers` of `@NgModule`s should be shared between all modules, or there should be an option to explicitly share them

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome 52 ] 
 
* **Language:** [TypeScript]

**Comment by pdelorme** [comment]
Not An Issue : This works as long as your service is not declared in your NgModule.providers. Doing so declares the Service twice. see [NgModule-FAQ](https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-module-provider-visibility)

**Comment by pkozlowski-opensource** [comment]
Yep, proper patterns to have only one instance of a service are documented properly already: https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-for-root
