### ISSUE TITLE
Query string being is being treated as a path segment for route matching

### ISSUE THREAD

**Issue by pcroc** [angular/angular#11275]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Query string being is being treated as a path segment for route matching

``` typescript
RouterModule.forRoot([
  { path: 'items/all', component: AllItemsComponent }
  { path: 'items/:id/:alias', component: SingleItemComponent }
]);
```
- Navigating to `/items/all?param=x` shows AllItemsComponent
- Navigating to `/items/all/?param=x` shows SingleItemComponent
- Navigating to `/items/all/` redirects to `/items/all`

**Expected/desired behavior**
- Navigating to `/items/all?param=x` shows AllItemsComponent
- Navigating to `/items/all/?param=x` shows AllItemsComponent or redirects to `/items/all?param=x`

It would be nice if we could provide a regex for matching routes, rather than just a simple path. This could be solved in the back-end but that is very annoying to have to do.

**Reproduction of the problem**

See above - sorry I don't know how to demonstrate this using plnkr since it requires navigating directly to a page.

**What is the expected behavior?**

See above

**What is the motivation / use case for changing the behavior?**
If `/path/` behaves the same as `/path`, then `/path/?query` should behave the same as `/path?query`

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** all
- **Language:** TypeScript 1.8

**Comment by zoechi** [comment]
Plunker would still be a complete runnable example that shows how you configured and connected stuff  even when it doesn't allow to reproduce the issue.

**Comment by daveriedstra** [comment]
I have this problem on a live site using angular@2.1.0. Linking to `/someroute/?foo` doesn't match `/someroute`, but `/someroute?foo` does.

I also suggest that the severity should be increased. It's inconvenient but usable to add `/:qs?` to all routes which don't already use a route parameter, but for routes which do it might be breaking.

**Comment by DzmitryShylovich** [comment]
@pcroc pls add a small repro in plunkr using the latest angular

**Comment by peterfoeng** [comment]
any update to this issue? or any temporary solution? we experience the same issue on prod handling a redirect url from desktop site :(

**Comment by Urchinstripe** [comment]
yes, I also wonder if there's any update?

**Comment by DzmitryShylovich** [comment]
@Urchinstripe @peterfoeng @pcroc pls add a plunkr with repro otherwise it;s not actionable

**Comment by pcroc** [comment]
@DzmitryShylovich As requested in the bug template I have provided *STEPS TO REPRODUCE*. The problem is only evident when navigating directly to specific URLs - if this is at all possible with plunkr it is not obvious how.

**Comment by DzmitryShylovich** [comment]
> if this is at all possible with plunkr it is not obvious how.

open a plunkr in a new window http://prntscr.com/e9km08
copy paste url into a new tab

**Comment by pcroc** [comment]
Thanks. This is about as close as I could get, I'm pretty sure this would demonstrate the problem if plunkr allowed us to append to URL and still show the app. As soon as you click on the links you'll get a 404 rather than the Angular app.

http://plnkr.co/edit/bfgvnHAGoBU73IRdRaDE?p=preview

Although it doesn't work, hopefully you get the idea of the problem.

**Comment by atscott** [comment]
This appears to be working in Angular v9: https://stackblitz.com/edit/angular-ivy-router-base-6skym8?file=src%2Fapp%2Fapp.component.html
All listed scenarios correctly route to `AllItemsComponent`
