### ISSUE TITLE
FormGroup.get should use generics

### ISSUE THREAD

**Issue by Fank** [angular/angular#11279]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

By accessing `FormGroup.get` it should be possible to use genereics: `FormControl` | `FormGroup` | `FormArray` to access propertie/methods easier.

**Current behavior**
```ts
let form = new FormGroup({ // NOT A LEAGAL SYNTAX ONLY SHOWCASE
   'normal': new FormControl('asd'),
   'nested': {
       'a': new FormControl('foo'),
       'b': new FormControl('bar')
   }
});

// accessing 'normal'
(form.get('normal') as FormControl).value;

// accessing 'nested'
(form.get('nested') as FormGroup).getRawValue();
```

**Expected/desired behavior**
```ts
let form = new FormGroup({ // NOT A LEAGAL SYNTAX ONLY SHOWCASE
   'normal': new FormControl('asd'),
   'nested': {
       'a': new FormControl('foo'),
       'b': new FormControl('bar')
   }
});

// accessing 'normal'
form.get<FormControl>('nested').value;

// accessing 'nested'
form.get<FormGroup>('normal').getRawValue();
```

**What is the motivation / use case for changing the behavior?**
We want easily readable code, and using casts (as or <>) does not fulfill that requirement

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript 1.8]

**Comment by kara** [comment]
Hmm you shouldn't need to coerce the type when accessing the `value` property, as it lives on `AbstractControl` itself.   You should simply be able to do `this.form.get('normal').value`.

Most properties and methods are like `value` and live on `AbstractControl`, but we do have a few methods like `getRawValue()` that only exist on the group level.  For those, I'd be curious why you're not using the shorter syntax: 

```ts
(<FormGroup>this.form).get('nested').getRawValue();
```
 It doesn't seem to be much different from what you're suggesting (`this.form.get<FormGroup('nested').getRawValue()`).

**Comment by rkirov** [comment]
IMHO, this is not worth pursuing.

The cast syntax is there to remind you, that you are performing an type unsafe operation. In this case the runtime behavior is completely determined by the string passed to `form.get`, and the cast is an unsafe convenience on top.

In my experience, generics are more often used for abstraction, not for this type of downcasting. For example, in TS we don't have `document.getElementById<CanvasElement>('canvas')`.

Finally, the implementation of get will also necessarily have to lose type safety, in order to cast some object to the unbound type parameter `T`.

```ts
type AbstractBase = {
  a: string
};

function get<T extends AbstractBase>(x: string): T {
  return {a: 'foo'} as any;
}
```

**Comment by kara** [comment]
Given the type safety concerns and how similar the existing syntax is, I'm inclined to agree with Rado.

**Comment by alxhub** [comment]
Just a note - although this particular issue is locked due to inactivity, Typed Reactive Forms remain on the [team's roadmap](https://angular.io/guide/roadmap#better-developer-ergonomics-with-strict-typing-for-angularforms).
