### ISSUE TITLE
ngOnchanges not detect changes

### ISSUE THREAD

**Issue by abhishek11210646** [angular/angular#11272]
this is code. it gives expected result on first time load. but when something changed in model  it do not detect and not run.

 `ngOnChanges(changes: { [propName: string]: SimpleChange }) {
      for(let change in changes)
        { console.log("changes..",change);}
    }`
what can be the problem????

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by pkozlowski-opensource** [comment]
> what can be the problem????

No idea based on the description provided. Please use the issue template and provide a minimal reproduce scenario with plunker if you believe that there is a bug in Angular. Also try with the latest version (rc.6).

**Comment by abhishek11210646** [comment]
ohhka.. that may be problem, I am using rc.3
