### ISSUE TITLE
Getting template parsing issue in RC4

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#11283]
I am getting template parsing issue if i used the following kind of expression where json object key name starts with numeric value:

{{content.6STAR_Mobile_Overview.MyPlansandFeatures.FieldLabels.BillingandPayText1.Label}}
but if i remove 6 from 6STAR_Mobile_Overview no parsing issue.

Error log is as below :+1: 
Unhandled Promise rejection: Template parse errors:
Parser Error: Unexpected token 6, expected identifier or keyword at column 10 in [{{content?.6STAR_Mobile_Overview?.MyPlansandFeatures?.FieldLabels?.BillingandPayText1?.Label}}>] in preExistingWirelessConvertSection@2:36 ("versionNote">
    <div role="alert" class="alert padSection">
        <h3 class="marBot0"><strong>[ERROR ->]{{content?.6STAR_Mobile_Overview?.MyPlansandFeatures?.FieldLabels?.BillingandPayText1?.Label}}></stro"): preExistingWirelessConvertSection@2:36 ; Zone: <root> ; Task: Promise.then ; Value: BaseException$1 {message: "Template parse errors:↵Parser Error: Unexpected to…></stro"): preExistingWirelessConvertSection@2:36", stack: "Error: Template parse errors:↵Parser Error: Unexpe…st:3000/node_modules/zone.js/dist/zone.js:356:38)", constructor: function, toString: function}message: "Template parse errors:↵Parser Error: Unexpected token 6, expected identifier or keyword at column 10 in [{{content?.6STAR_Mobile_Overview?.MyPlansandFeatures?.FieldLabels?.BillingandPayText1?.Label}}>] in preExistingWirelessConvertSection@2:36 ("versionNote">
↵    <div role="alert" class="alert padSection">
↵        <h3 class="marBot0"><strong>[ERROR ->]{{content?.6STAR_Mobile_Overview?.MyPlansandFeatures?.FieldLabels?.BillingandPayText1?.Label}}></stro"): preExistingWirelessConvertSection@2:36"stack: "Error: Template parse errors:↵Parser Error: Unexpected token 6, expected identifier or keyword at column 10 in [{{content?.6STAR_Mobile_Overview?.MyPlansandFeatures?.FieldLabels?.BillingandPayText1?.Label}}>] in preExistingWirelessConvertSection@2:36 ("versionNote">
↵    <div role="alert" class="alert padSection">
↵        <h3 class="marBot0"><strong>[ERROR ->]{{content?.6STAR_Mobile_Overview?.MyPlansandFeatures?.FieldLabels?.BillingandPayText1?.Label}}></stro"): preExistingWirelessConvertSection@2:36↵    at new BaseException$1 (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:971:27)↵    at TemplateParser.parse (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:6274:23)↵    at RuntimeCompiler._compileTemplate (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:14656:55)↵    at eval (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:14571:63)↵    at Set.forEach (native)↵    at eval (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:14571:27)↵    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:323:29)↵    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:216:44)↵    at http://localhost:3000/node_modules/zone.js/dist/zone.js:571:58↵    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:356:38)"__proto__: __

**Comment by pkozlowski-opensource** [comment]
in JS identifiers can't start with a number: https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Grammar_and_types

Allowing numbers in front of var names would prevent us from doing code generation.

Closing as invalid. Please follow the issue template in the future (please don't dump your stack trace issue, provide a plunker insted).

**Comment by vasuneet** [comment]
But it was working in AngularJS 1.x

**Comment by zoechi** [comment]
Angular1 depends on the browser and they are often forgiving. Angular2 throws on invalid HTML.
