### ISSUE TITLE
NgModule should be able to declare providers/service they need.

### ISSUE THREAD

**Issue by pdelorme** [angular/angular#11281]
**I'm submitting a ...**  

```
[ ] bug report 
[x] feature request
[ ] support request
```

**Current behavior**
NgModule cannot declare providers/service they need. It can only provide a service for global instanciation.
I see only two options :
1. The provider/service is defined above the NgModule, and it can be used in the NgModule. The service is shared according to scope, but this requiers the service to be instanciated even though it is never going to be used. I find this in contradiction with the goal of dynamic/lazy loading. Also An application must be aware of what service are needed by its underneath NgModules.
2. The provider/service is provided to the application with NgModule.providers and it is instanciated globally... If another NgModule provides the same Service, the service will be reinstanciated caussing possibly two instances. Also if the NgModule is loaded dynamically by route, the service is reinstanciated each time the route is activated. I find this option in contradiction with the idea of sharing a Service for multiple usage.

As a result, `NgModule.providers` is not really usable except to instanciate global service the NgModule defines or to instanciate local service when loaded dynamically. 

**Expected/desired behavior**
Wouldn't it be great if an NgModule could just use existing service or create a new global instance if not yet created ? what do you think ?
I sugest :
1. The addition of a new descriptor (`NgModule.uses` or `NgModules.services` or `NgModule.injects`) to list all Services that are requiered by the NgModule to work. Implementation would inject a new Service of that class or inject yet created instance. This would allow for late loading/instantiation of Services and save boot time.
2. The renaming of `providers` into `provides` to make it clearer what this is.

**What is the motivation / use case for changing the behavior?**
Benefits :
1. No need to declare service before they are actually needed. 
   - main.module.ts is easier to read because there are only the providers/services necessary at bootime.
   - developpers don't need to check services needed by NgModules they don't know. 
2. NgModules can declare providers they need without conflicts.
   - module make it cleat what providers they need.
   - module make it clear what service they provide.
3. Service can be loaded and reused dynamically.
   - Modules loaded dynamically can declare a local service they can latter reuse.
   - Service is instanciated only when it is actually needed (by the first dynamically loaded NgModule)
4. Better distribution of code.
   - say Two NgModule XModule1 and XModule2 share data through a service XService that is of no use to the rest of the application. XModule1, XModule2 and Xservice can be better distributed in one bundle and XService don't need to be statically referenced in application code.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5

**Comment by DaSchTour** [comment]
Well, I thought that the current implementation is exactly as this request suggests. I hope that this can be changed very soon. At the moment RC5 and later feel a lot like a alpha version. The breaking changes are gigantic and there is so much to improve. I'm currently putting all Angular 2 development on hold. The direction Angular is heading to is hard to determine.

I really would love to see this feature in RC7 together with a stable and easy usable module/component system so I can go on with my Angular 2 projects.

**Comment by qdouble** [comment]
@DaSchTour there's currently an api freeze according to staff...I'm assuming "final" will be released soon.

**Comment by DaSchTour** [comment]
@qdouble oh, till RC5 you couldn't await the final release. Currently I've the impression that it's far away from being stable and ready for a release. With the new module system to many traps had been added that will lead to a lot of bugs.

**Comment by zoechi** [comment]
@DaSchTour but that's the last feature added before release it seems. Therefore after this stabilizes final is due.

**Comment by qdouble** [comment]
@DaSchTour well there are indeed bugs that need to be patched before release, but the API is stable now. New features will come after release.

**Comment by DaSchTour** [comment]
@zoechi @qdouble I already understood what stable API means. The point is. This feature requests clearly shows a huge issue with the current handling of services. And I'm convinced, that a lot of projects will suffer from mixed instances of services. I also don't see how dependencies can be handled correctly. But I'm only repeating what was repeatedly stated in #10552 and ignored by the angular team. I'm really disappointed about myself having wasted so much time with angular.

**Comment by qdouble** [comment]
@DaSchTour well everything isn't for everyone. There are still a lot of issues with angular, but it's only so much you can expect from a framework that hasn't even been officially released yet. I've been able to work out most of the big issues that I've encountered for now and I think it's possible to build production apps with it now, but of course there is room for improvement.

**Comment by DaSchTour** [comment]
@qdouble already with RC4 it was possible to build production apps. The point is, that the way how services are handled with NgModules is full of traps, makes dependencies intransparent and I bet a lot of errors that are hard to debug will be caused because of multiple instances of services.

**Comment by qdouble** [comment]
@DaSchTour it's workable for me as being a one man band, but I do imagine it could be problematic in a team environment.

**Comment by jelbourn** [comment]
StackBlitz from issue #36720 (marked as duplicate):
https://stackblitz.com/edit/angular-4ckgm4?file=src%2Fapp%2Fshared-module%2Fshared.module.ts
