### ISSUE TITLE
ViewChild does not return a ComponentRef

### ISSUE THREAD

**Issue by badger2013** [angular/angular#11288]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using ViewChild does not allow you to retrieve a ComponentRef for static components (i.e. components that were not created with a component factory).

Note:  I've marked this as a feature request as I'm unsure if this functionality simply doesn't exist or if there is a bug preventing it from working.

**Expected/desired behavior**

ViewChild will return a ComponentRef pointing to the component.

**Reproduction of the problem**

I've demonstrated the current behavior here:  ~~http://plnkr.co/edit/AVOuMdu2buHuHhD1CCy4?p=preview~~ http://plnkr.co/edit/rFZj6VmVyAWYSxyGUSJz?p=preview

**What is the expected behavior?**

ViewChild will return a ComponentRef pointing to the component.

**What is the motivation / use case for changing the behavior?**

I would like to fully remove statically created components using the [destroy method](https://angular.io/docs/ts/latest/api/core/index/ComponentRef-class.html#!#destroy).

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all] 
- **Language:** [TypeScript 1.8.34]

**Comment by DzmitryShylovich** [comment]
@badger2013 is this still relevant after final? (plunkr doesn't work)

**Comment by badger2013** [comment]
@DzmitryShylovich Yes, the same issue still exists.  I've created a new Plunker (http://plnkr.co/edit/rFZj6VmVyAWYSxyGUSJz?p=preview) that works which shows the problem.  I'm guessing the old one stopped functioning due to Angular framework updates.

**Comment by pkozlowski-opensource** [comment]
> I would like to fully remove statically created components using the destroy method.

This is not the philosophy of the current Angular - if a component is placed in a template statically it will always be there - exactly as any other element! Components are not much more special than regular HTML elements with a directive attached.  So if we would allow "components to be destroyed" we would have to remove the associated host element (in other words, I guess you are after _both_ destroying component instance _and_ removing an associated DOM element that acts as a host for this component). But taking this logic further we would have to allow a way of querying for `ElementRef` and calling "destroy" on it which becomes DOM manipulation.

Once of the biggest advantages of Angular is that it creates UI from a template and in a template we know which parts are static (elements always there) and which parts are dynamic (views being inserted / removed). This is pretty fundamental and allows us to do all sort of perf optimizations.

I'm going to close this issue given all the above. Still, we should update docs to precisely communicate what can be read from queries and what not. We are going to do the doc update in #20927
