### ISSUE TITLE
angular2-quickstart@1.0.0 tsc:w: `tsc -w`

### ISSUE THREAD

**Issue by mrp100461** [angular/angular#11285]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
npm ERR! node v4.5.0
[0] npm ERR! npm  v3.10.6
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! angular2-quickstart@1.0.0 tsc:w: `tsc -w`

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc. 
[npm-debug.txt](https://github.com/angular/angular/files/452207/npm-debug.txt)

 windows 10
* **Browser:** IE XX  
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by IgorMinar** [comment]
I can't reproduce this. try recloning the repo, reinstalling node_modules. if problem persists please provide reproduction on https://github.com/angular/quickstart's issue tracker.

**Comment by mrp100461** [comment]
mr @IgorMinar  are you always this helpful with people who are trying to learn  angular 2 but because you have no proper support and have unhelpful people like yourself god help people trying to solve these problems, so you can take your close and shove it where the sun does not shine

**Comment by IgorMinar** [comment]
@mrp100461 your response is in violation with our code of conduct: https://github.com/angular/code-of-conduct

I'm sorry but the issue tracker should not work as a support channel. If an issue can't be reproduced given the provided information then the issue should be closed.
