### ISSUE TITLE
Http request's with no body(GET && DELETE) but 'application/json' type fails

### ISSUE THREAD

**Issue by BrianCraig** [angular/angular#11299]
**[x] bug report**

@angular/http Http Service causes an exception before sending xhr GET && DELETE request with 'content-type':'application/json' header due to unnescesary intent of parsing the request body.  

**Current behavior**
```
Http.get("someUrl", {headers: new Headers({"content-type": "application/json"})})
// error before sending xhr request

Http.delete("someUrl", {headers: new Headers({"content-type": "application/json"})})
// error before sending xhr request
```

**Expected/desired behavior**
```
Http.get("someUrl", {headers: new Headers({"content-type": "application/json"})})
// sends the request fine

Http.delete("someUrl", {headers: new Headers({"content-type": "application/json"})})
// sends the request fine
```

**Similar code that works**
```
http.get("someUrl", {headers: new Headers({"other-random-header": "withSomething"})})
// not using content-type header works fine 


http.get("someUrl")
// just gets it normally
```

**What is the expected behavior?**
I expect that whatever the content-type header i send, if it's a GET, or a DELETE, it should skip parsing the body, and send a null body.

**Where it BOOM's?**
[Right here](https://github.com/angular/angular/blob/40e160c22caaa9c7c65da373d1975706495c329e/modules/%40angular/http/src/backends/xhr_backend.ts#L135)  
then, the parser after determining it's json calls to [this._body.toString()](https://github.com/angular/angular/blob/40e160c22caaa9c7c65da373d1975706495c329e/modules/%40angular/http/src/body.ts#L60), and the body is null, so toString method doesn't exists.

* **Angular version:** 2.0.0-rc.5 && 2.0.0-rc.4
 
* **Browser:** [Chrome 51 ] 
 
* **Language:** [all] 
I didn't try the methods HEAD and OPTIONS, but i assume that they will also fail.  
  
A big hug to the Angular Team, Brian

**Comment by frederikschubert** [comment]
This has already been fixed in master and is in the RC 6 release.

**Comment by BrianCraig** [comment]
Thanks ! i didn't saw #10668
