### ISSUE TITLE
[RC6] _ngcontent seem to have wrong attribute names

### ISSUE THREAD

**Issue by christiandreher** [angular/angular#11302]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior (RC6)**

I have a `RowLayoutComponent`, whose template looks like this:

```html
<div style="display: flex; flex-direction: row;">
    <ng-content></ng-content>
</div>
```

And CSS like this:

```css
:host > div > * + * {
    margin-left: 8px;
}
```

So I could do the following to create a row layout:

```html
<row-layout>
    <some-cell style="flex: 0 1 33.34%;"></some-cell>
    <some-cell style="flex: 0 1 33.34%;"></some-cell>
    <some-cell style="flex: 0 1 33.34%;"></some-cell>
</row-layout>
```

The output is a row with 3 elements, but the margin in between them is not honored. Taking a look at the generated output, I saw that the naming of the attributes did not work properly, as it was in RC5.

Here is the generated `<style>`:

```html
<style>
[_nghost-lfm-10]    > div[_ngcontent-lfm-10]    > *[_ngcontent-lfm-10]    + *[_ngcontent-lfm-10] {
    margin-left: 8px;
}
</style>
```

But the generated HTML is the following:

```html
<row-layout _ngcontent-lfm-9="" _nghost-lfm-10="">
	<div _ngcontent-lfm-10="" style="display: flex; flex-direction: row;">
		<some-cell _ngcontent-lfm-9="" _nghost-lfm-14="" style="flex: 0 1 33.34%;"></some-cell>
		<some-cell _ngcontent-lfm-9="" _nghost-lfm-14="" style="flex: 0 1 33.34%;"></some-cell>
		<some-cell _ngcontent-lfm-9="" _nghost-lfm-14="" style="flex: 0 1 33.34%;"></some-cell>
	</div>
</row-layout>
```

Note that it says `_ngcontent-lfm-9` everywhere, instead of `_ngcontent-lfm-10` like it did on RC5

**Expected/desired behavior (RC5)**

Like I said, in the above example it says `_ngcontent-lfm-9` everywhere, instead of `_ngcontent-lfm-10` like it did on RC5. The code worked perfectly on RC5

**Reproduction of the problem**

See *Current behavior (RC6)* and *Expected/desired behavior (RC5)*

**What is the expected behavior?**

See *Expected/desired behavior (RC5)*

**What is the motivation / use case for changing the behavior?**

Well, fixing a bug. The use case is that I want to have a RowLayoutComponent, which takes a bunch of elements that should be aligned in a row. But they shouldn't glue together, thats why I want to have a margin in between the elements. This worked perfectly in RC5 by applying a CSS rule for `:host > div > * + *` in `row-layout.component.css` (to exclude the first element from having a margin), but this behaviour is broken now with RC6.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6 now, 2.0.0-rc.5 before
 
* **Browser:** Chrome 52.0.2743.116 (Official Build) (64-bit) (at least I tested it there)
 
* **Language:** TypeScript 2.0.0

**Comment by vicb** [comment]
We have fixed CSS encapsulation in rc6. I believe the behavior you describe is correct and expected.

You can use /deep/ (or no encapsulation) of you want the styles to apply across components.

**Comment by christiandreher** [comment]
Could you ellaborate what you mean by `/deep/`? I just find stuff related to deep copies googling it

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

- https://angular.io/docs/ts/latest/guide/component-styles.html
- http://stackoverflow.com/questions/34542143/load-external-css-style-into-angular-2-component/34963135#34963135
