### ISSUE TITLE
Http post - body param not included in request, when passing  RequestOptionsArgs.body

### ISSUE THREAD

**Issue by Qszer94** [angular/angular#11306]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
this.headers = new Headers(
     { 'Content-Type': 'application/json' }
);
this.options = new RequestOptions({
     headers: this.headers,
     body: {
          default_param: "default_val",
      }
});

action(customBodyParams ): Observable<MyModel> {
        return this.http.post(this.myUrl, customBodyParams, this.options)
            .map(data => data.json().data || {})
            .catch(this.handleError);
    }
```

When I passed third param to post function (RequestOptions) containing body property my customBodyParams have been omitted in request.

**Expected/desired behavior**
I expect to see merged parameters from customBodyParams and this.options.body.
IMHO Request Options should be treated as default request options and shouldn't override value of the second post parameter (body: any)

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6
- **Browser:** [all] 
- **Language:** [ TypeScript 2.0 ]

**Comment by alamgird** [comment]
i'd like to work on it. can i get this assigned? @vicb

**Comment by vicb** [comment]
@alamgird GH does not allow assigning arbitrary accounts but yep please go ahead - much appreciated

**Comment by alxhub** [comment]
I don't think merging is the correct behavior here - HTTP should throw an error if both of these `body` values are provided.

**Comment by alxhub** [comment]
Closing as this is not the behavior we intend to support.
