### ISSUE TITLE
Can't extend IterableDiffers

### ISSUE THREAD

**Issue by barbatus** [angular/angular#11309]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Not sure If I am missing something or it's a bug. 
But if you do as follows I get "Cannot extend IterableDiffers without a parent injector" exception.

``` js
@NgModule({
  imports: [BrowserModule],
  providers: [IterableDiffers.extend([new FooIterableDifferFactory()])]
  bootstrap: [Foo]
});
export class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);
```

**Expected/desired behavior**

It's possible to extend default iterable differs in the application module.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6
- **Browser:** [all] 
- **Language:** [all]

**Comment by vicb** [comment]
> Expected/desired behavior

Pls expand on what you're trying to do

**Comment by Urigo** [comment]
@vicb we are using it in `angular2-meteor` in order to provide new iterable for Mongo Cursor changes (you can see [this file](https://github.com/Urigo/angular2-meteor/blob/master/modules/mongo_cursor_differ.ts#L46)).

As the example [here](https://github.com/angular/angular/blob/7c07bfff97f58bbcd070c19bd1486858c7fd3136/modules/%40angular/core/src/change_detection/differs/iterable_differs.ts#L76).

It worked since last September and only broke in the latest version.

As @barbatus said, it's suppose to be possible to extend default iterable differs in the application module, but now it's not anymore.

Thanks!

**Comment by vicb** [comment]
Could you please craft a before/after plunker - is this broken in RC6 ?

It's true that deep imports are not allowed any more, might be the issue.

Thanks

**Comment by barbatus** [comment]
@vicb Here is a plunker where a custom differ factory is supposed to be used but it throws "Cannot extend IterableDiffers without a parent injector" when I am trying to use `IterableDiffers.extend`. 
https://plnkr.co/edit/YVRZ6gNq7LMr2DAJvRAf?p=preview

As before, we extended standard differs by providing new instance of `IterableDiffers` with all differ factories added plus our custom differ factory. In order to get all available differ factories to pass them into `IterableDiffers` constructor, we relied on some internal code, i.e. https://github.com/Urigo/angular2-meteor/blob/master/modules/providers.ts#L6

**Comment by htafolla** [comment]
@vicb is this scheduled to be resolved in the next maintenance release? There is a growing community looking to use Angular 2.0.0 with Meteor. Based on the latest posts on the corresponding thread item is the only one remaining to make the jump.

**Comment by vicb** [comment]
@htafolla I'm going to take a look asap.

**Comment by vicb** [comment]
just discussed with @vsavkin, we should have a solution by the next release (probably 2.0.1)

**Comment by vicb** [comment]
for now a workaround would be not to add the providers in the app module but in a child module.

**Comment by barbatus** [comment]
@vicb I added it to a module https://plnkr.co/edit/UCKeZGwKfENQY76RHgiy?p=preview, still same exception. I also tried as ModuleWithProviders, also doesn't help.

**Comment by chrisse27** [comment]
@barbatus Adding it as provider to the child component works for me: https://plnkr.co/edit/IZcErDswbe6CLSZOwVve

That's also what I did  with the METEOR_PROVIDERs to get rid of the exception in my angular2 meteor project.

**Comment by barbatus** [comment]
@chrisse27 yes, but providers like IterableDiffers make sense to set globally for all components not for every one.

**Comment by chrisse27** [comment]
@barbatus I agree, but if I set the provider on my app component then it will be available in all injectors of child components as well.

**Comment by barbatus** [comment]
@chrisse27 hm, this is how it was before.  I thought for some reason they got (or gonna get) rid of providers in components. Anyways makes sense to fix it for modules as well.

**Comment by barbatus** [comment]
@chrisse27 this also https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-component-or-module. For the apps with routes, there is no one root component as well.

**Comment by DzmitryShylovich** [comment]
@barbatus did your solve the issue?

**Comment by barbatus** [comment]
@DzmitryShylovich I could only work around it. Status of this issue clear states it's not fixed yet.
So either a fix is needed or docs update to note that `IterableDiffers` is not extendable in `@NgModule`.

**Comment by DzmitryShylovich** [comment]
@barbatus could u add a small repro in plunkr?

**Comment by barbatus** [comment]
@DzmitryShylovich ok, there was one above which seems to be broken now.
Here is new one https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview

**Comment by DzmitryShylovich** [comment]
thx

**Comment by DzmitryShylovich** [comment]
@barbatus u didn't save changes :)

**Comment by staeke** [comment]
Ping! What's the status of this @DzmitrySchylovic?
