### ISSUE TITLE
There is a space in your hyperlink in quickstart

### ISSUE THREAD

**Issue by RedPepperPixelsMike** [angular/angular#11308]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

link to github quickstart for angular 2 has a space in it 
https://github%20.com/angular/quickstart/blob/master/README.md

**Expected/desired behavior**
i'm guessing it should be this
https://github.com/angular/quickstart/blob/master/README.md.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [Chrome XX ] 
 
* **Language:** [all]

**Comment by skreborn** [comment]
This is the repository for the Angular framework. The documentation resides in the [angular.io](https://github.com/angular/angular.io) one. Please move this issue there.

**Comment by skreborn** [comment]
Actually, you can just close it as this has already been [fixed](https://github.com/skreborn/angular.io/commit/94a40a1852b1ef1ccddb890a8e62be885cdd505d).

**Comment by RedPepperPixelsMike** [comment]
Ok. Thank you. Next time I will put my issue in the right place. :) Have a nice day.
