### ISSUE TITLE
Testing: misleading error message when don't call `compileComponents`

### ISSUE THREAD

**Issue by wardbell** [angular/angular#11301]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**

Component doesn't have a templateUrl but DOES have styleUrls.

```
@Component({
  selector: 'dashboard-hero',
  template: '<div class="hero" (click)="click()">{{hero.name | uppercase}}</div>',
  styleUrls: ['app/dashboard/dashboard-hero.component.css']
})
```

When don't call `TestBed.compileComponents` the error message is

```
Error: This test module uses the component DashboardHeroComponent which is using a "templateUrl", but they were never compiled. Please call "TestBed.compileComponents" before your test.
```

This is ALMOST correct. The problem is that it is the styleUrls that cause the problem, not the (non-existent) templateUrl

**Expected/desired behavior**

Could say 

> which is using a "templateUrl" or "stylerUrls"

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6
- **Browser:** [all ] 
- **Language:** [all]

**Comment by asadsahi** [comment]
@wardbell @tbosch I am having same misleading error with template urls and stylesUrl set with webpack. Even tutorials say, I don't have to call compile components because webpack compiles it. But it doesn't make any difference. If I change to inline templates and styles, it works ok though.
