### ISSUE TITLE
Ask for hints how to test now - RC-6

### ISSUE THREAD

**Issue by ElectricMaxxx** [angular/angular#11303]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In RC-5 i wrote tests like that:
```
        beforeEach(() => {
            TestBed.configureTestingModule({
                declarations: [LoginPageComponent],
                imports: [ FormsModule ],
                providers: [
                    UserService,
                    provide(Router, { useClass: MockRouter}),
                    RouteRepository,
                    provide(Http, { useClass: MockingHttp })
                ]
            });
        });
```
Doing so i can work with mocked providers. That works fine with classes i created on the fly - not for those generated by some jasmine spy methods. Now the provide() method is gone. It was deprecated in RC-5, but with no hints.

**What is the motivation / use case for changing the behavior?**
One point why i loved angular 1 had been the examples including the tests. Cause tests and they way they work explain a framework from an other point of view. And testing is so much important!

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all | Chrome XX] 
 
* **Language:** [all] .

**Comment by ElectricMaxxx** [comment]
```
providers: [
  { provide: LocationStrategy, useClass: HashLocationStrategy }
]
```
can that be the answer? Found it in the dependency injection section.

**Comment by qdouble** [comment]
@ElectricMaxxx yes, the format you just posted is the correct format for provide. Here's a good source for test examples and you can check the commit history: https://github.com/juliemr/ng2-test-seed/commits/master

The box you checked says "Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question"

**Comment by ElectricMaxxx** [comment]
@qdouble sorry for that, didn't read until the endly. But mostly i would suggest to also maintain the testing documentation or even provide that much information, that a person like me is able to contribute.
