### ISSUE TITLE
The <strike> HTML tag is not recognized as a standard HTML tag

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#11305]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a template contains the <strike></strike> tag angular wants to handle it as a component

**Expected/desired behavior**
It's an HTML tag, so it does not needs to try to handle as a component.

**Reproduction of the problem**
```
zone.js:484 Unhandled Promise rejection: Template parse errors:
'strike' is not a known element:
1. If 'strike' is an Angular component, then verify that it is part of this module.
2. If 'strike' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("
<h4 class="price">
Lista ár
[ERROR ->]<strike>
<i>$</i>150
</strike>
</h4>
```

**What is the expected behavior?**
Do not report any error just render the markup. It's a normal HTML tag.

* **Angular version:** 2.0.0-rc.6

**Comment by bcabanes** [comment]
Hi,
Just to add some information, the `<strike>` tag is obsolete/deprecated. It is not recommended to use it anymore.

More information here: 
- https://developer.mozilla.org/en/docs/Web/HTML/Element/strike
- http://caniuse.com/#search=strike

Should Angular2 still support a deprecated W3C tag?

**Comment by Pablo-Ivan** [comment]
@bcabanes is right, you should probably use the <s></s> tag.

**Comment by ericmartinezr** [comment]
According to Pawel's comment https://github.com/angular/angular/issues/11270#issuecomment-244326630 it's unlikely they will support an obsolete tag.

**Comment by vicb** [comment]
By default angular validates against valid tags.

As you can see in the error message, you can still override this default behavior. The doc team is working on a cookbook.

**Comment by ketan9605** [comment]
if` <strick></strick>` not supoort in angular 2/4 then use `<s></s>` tag. 
like before you used `<strick>Test</strick>` use instead of `<s>Test</s>`
