### ISSUE TITLE
Page Transitions: Make transition dependent on next route

### ISSUE THREAD

**Issue by smith64fx** [angular/angular#11304]
Hey Angular 2 Team. I love your work so much! ng2 changes the world :)

Right now, I play around with the page transitions and I want to achieve something like this:

Let's say we have Page A, B and C.

I want following transitions:

When i go from A to B, I want A to fade out to the left and B come from the right. And the same for A and C, B and C.

But when I go vice versa (from C to A) I want C to fade out right and A come from the left.

Something like a "horizontal navigation", dependent on where you are right now and where you go.

Is this possible in Angular 2? I want to tell my component "Hey component B, when you get loaded and the user is coming from component C, I want you to animate this way. But when the user comes from component A, I want you to animate this way.

Is this possible?

Thanks Angular2 Team!!!!

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/9845, the conditons will be up to you. See also https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
