### ISSUE TITLE
Edge Error with Authentication

### ISSUE THREAD

**Issue by CrohnsAndMe** [angular/angular#11318]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
So on Firefox and chrome the passport authentication works and once logged in it saves you until you logout

on Edge when i try to log in it just brings me constantly back to login so im guessing the problem is with the following section

AuthService.getUserStatus()
.then(function(user)
{`
.......

}

**Expected/desired behavior**

Im expecting Edge to work like Chrome and Firefox and when the user logs in for the session to be kept rather than always say the user is not logged in

**Reproduction of the problem**

AuthService.getUserStatus()
.then(function(user)
{`
.......
}

function getUserStatus() {
  //return user;
  var result = {
    user: false,
    name: "NA",
    type: ""
  };
  var deferred = $q.defer();
  $http.get('/user/status')
  .success(function(data)
  {
   // console.log("SUCCESS" + data.status);
    deferred.resolve(data);
  })
   .error(function(data)
    {
      // console.log("ERROR HERE");
       deferred.reject();
    });
 // return promise object
  return deferred.promise;
};

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 Angular scripts are 
 <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
     <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.min.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-aria.min.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-messages.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.28/angular-route.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.js"></script>

* **Browser:** [all | Chrome latest this week | Firefox latest this week| IE latest this week|] 
 
* **Language:** []

**Comment by ericmartinezr** [comment]
This repo is for ng2, and you also need to read this https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
