### ISSUE TITLE
Transition group not running animations in parallel

### ISSUE THREAD

**Issue by Cammisuli** [angular/angular#11312]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
Transition groups do not run animations in parallel. Instead they run one at a time, waiting for the previous one to complete.

**Expected/desired behavior**
Transition groups should run animations in parallel

**Reproduction of the problem**
http://plnkr.co/edit/Ub4IpJRwmGeqDNHBdKZm?p=preview

**What is the expected behavior?**
Animations should run in parallel.

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [ Chrome 52 ] 
 
* **Language:** [Typescript]

**Comment by matsko** [comment]
So from what I understand with code, the element should animate the scale style right away and then from a black to blue color after 1000ms have passed? It looks like the transform style is being delayed for some reason. I'll look into it.

**Comment by Cammisuli** [comment]
@matsko yea, it looks like the group function doesn't actually do the styles in parallel. It's like the group call isn't even there and just does everything in steps.

**Comment by matsko** [comment]
Alright so there definitely was a bug within the animation parser. this fix should do it: https://github.com/angular/angular/pull/11419
