### ISSUE TITLE
Form API should allow simple binding to a single control

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1131]
In the simplest case, a component author may want to bind to single input, and not create a control group. Something equivalent to this is desired:

```dart
class MyComponent {
  final Control inputControl;

  MyComponent()
    : this.inputControl = Control(initialValue: 'Hello world') {
    inputControl.onChanged.listen((newValue) {
      print('Hello $newValue');
    });
  }
}
```

```html
<input [control]="inputControl" />
```

(API above is just a suggestion)

As a freebie, this will vastly ease migration off of `ng-model`.

**Comment by vsavkin** [comment]
Closed via https://github.com/angular/angular/commit/b02bd65871c6d5a004efd661267a0d7304da7b7f
