### ISSUE TITLE
ng-content select not working anymore

### ISSUE THREAD

**Issue by Hippocrate** [angular/angular#11326]
Hi there,
I upgraded my project from RC5 to RC6 and i got this error message  

> Error: Template parse errors:
'card-header' is not a known element: ...

The ```card-header``` component is not a real one, but a ng-content selector 
```javascript
@Component({
    selector: 'card',
    template: `<div class="card" [ngClass]="{padded: !noPadding, marged: !noMargin}">
        <ng-content select="[card-header]" class="card-header"></ng-content>
        <ng-content></ng-content>
    </div>`,
})
...
```
 I read the changelog but nothing about a breaking change on ng-content.

Is this a real bug or did i miss something ?

Thank you !

**Comment by vicb** [comment]
See https://github.com/angular/angular/search?o=desc&q=schema&s=created&type=Issues&utf8=%E2%9C%93

**Comment by Hippocrate** [comment]
Ok thank's

**Comment by navstev0** [comment]
Wow, might as well have said, "I don't know go look for yourself." Wasn't going to reply to this but that was bad, and needed to get called out.
