### ISSUE TITLE
System.import('@angular/core/testing') return undefined

### ISSUE THREAD

**Issue by BjornMelgaard** [angular/angular#11322]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```
'@angular/core/testing' is only package which I can't import in [karma-test-shim.js](https://github.com/BjornMelgaard/angular2-tiddle/blob/master/karma-test-shim.js#L66)
**Current behavior**
```
var packageNames = [
  '@angular/core/testing',
  '@angular/core',
  '@angular/compiler/testing',
  '@angular/compiler',
  '@angular/common/testing',
  '@angular/common',
  '@angular/http/testing',
  '@angular/http',
  '@angular/platform-browser/testing',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic/testing',
  '@angular/platform-browser-dynamic',
]
packageNames.map(function(name) {
  System.import(name).then(function(package) {
    if (!!package == false)
      console.log("can't import " + name);
  })
})
```
**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 

[This question on StackOverflow](http://stackoverflow.com/questions/39316148/cant-import-testbed-in-karma-config)

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
