### ISSUE TITLE
Testing in RC.6 is incompatible with Jasmine 2.5

### ISSUE THREAD

**Issue by yfain** [angular/angular#11323]
While upgrading to rc.6 my browser-based tests (without karma) started failing with the following error:

zone.js:486 TypeError: Cannot read property 'spies' of undefined(…)consoleError @ zone.js:486drainMicroTaskQueue @ zone.js:500ZoneTask.invoke @ zone.js:437

Jasmine 2.5 was released on August 31,2016. Downgrading Jasmine to 2.4.1 helped.

**Comment by mhevery** [comment]
I am unable to reproduce this issue. I have upgraded angular's jasmine to v2.5.0 and all tests run fine.

**Comment by yfain** [comment]
I was writing about HTML-based runner. With Karma runner I didn't have issues either.

**Comment by QHQuach** [comment]
I am getting the same issue too with our jasmine-html-based unit test runner (following dev guide from angular io for the jasmine test html and serving through asp.net core controller/action/view - e.g. mysite.com/UnitTests/Index). 

@mhevery, can you provide us a sample code especially your package.json for version specified on things like zone.js, jasmine-core...?

Also, tried to go back and use below package version 

zone.js: 0.6.17
jasmine-core: 2.4.1

would cause this failure when TestBed.compileComponents() get executed instead. Can't find anything out there on this error.

Failed: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at TestBed._createCompilerAndModule (XXXXXXX/js/angular/core/bundles/core-testing.umd.js:1091:57)
    at TestBed.compileComponents (XXXXXXX/js/angular/core/bundles/core-testing.umd.js:1045:35)
    at Function.TestBed.compileComponents (XXXXXXX/js/angular/core/bundles/core-testing.umd.js:950:71)
    at eval (XXXXXXX/app/components/message.component.spec.js:55:27)
    at ZoneDelegate.invoke (XXXXXXX/js/angular/zone.js:332:29)
    at AsyncTestZoneSpec.onInvoke (XXXXXXX/js/unit-tests/async-test.js:76:44)
    at e.onInvoke (XXXXXXX/js/unit-tests/proxy.min.js:1:1560)
    at ZoneDelegate.invoke (XXXXXXX/js/angular/zone.js:331:35)
    at Zone.runGuarded (XXXXXXX/js/angular/zone.js:239:48)
    at runInTestZone (XXXXXXX/js/angular/core/bundles/core-testing.umd.js:105:29)

Please help. Thanks

**Comment by QHQuach** [comment]
This is what I have setup in the Index.cshtml (after puting bits and pieces of different ng2 RC6 unit testing example out there)

    
    
    <script src="~/js/angular/shim.min.js"></script>

    <script src="~/js/angular/zone.js"></script>
    <script src="~/js/angular/Reflect.js"></script>
    <script src="~/js/angular/system.src.js"></script>
    
    
    <script src="~/js/unit-tests/long-stack-trace-zone.min.js"></script>
    
    <script src="~/js/unit-tests/async-test.js"></script>
    <script src="~/js/unit-tests/fake-async-test.js"></script>
    <script src="~/js/unit-tests/sync-test.js"></script>
    <script src="~/js/unit-tests/proxy.min.js"></script>
    <script src="~/js/unit-tests/jasmine-patch.min.js"></script>

    <script src="~/systemjs.unit-test.config.js"></script>
    <script src="~/unit-tests.imports.js"></script>

with following package version

        "core-js": "^2.4.1",
        "reflect-metadata": "^0.1.3",
        "rxjs": "5.0.0-beta.11",
        "systemjs": "0.19.27",
        "zone.js": "^0.6.17",

        "jasmine-core": "2.4.1"
