### ISSUE TITLE
Tutorial missing create() function on AngularJS 2 Typescript tutorial

### ISSUE THREAD

**Issue by qazqwezxc** [angular/angular#11329]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

MISSING

**Expected/desired behavior**

Hi, 
I'm a little new to contributing and was working through the AngularJS tutorial. I noticed that in the HTTP section, there is a missing function for create(), although provided at the end of the section, it was not documented in the tutorial. Can someone please add it and fix it so that other newcomers like me can learn and not worry about missing functions?

Thanks,
Andrew H

**Comment by ericmartinezr** [comment]
Hey Andrew, would you mind re-opening this issue in the website/tutorial's repo https://github.com/angular/angular.io ?

**Comment by qazqwezxc** [comment]
Sure thing, I thought this was the place to submit the issue.

Opened issue on angular.io

Regards,
Andrew H
