### ISSUE TITLE
Refresh on nested component

### ISSUE THREAD

**Issue by Marco105** [angular/angular#11330]
I guess there is known issue of it, but would like speak myself about it.

When you put a component inside another one and you  have css, html file separate for them, you can't refresh the nested as you want. Problem of memory encapsulated, of browser, I don't know but very inconvenient issue and would like have answer about that, please.
```
@Component({
    selector: 'my-races',
    templateUrl: 'app/races.component.html',
    styleUrls: ['app/races.component.css']
})
```

**Comment by vicb** [comment]
?
If needed please re-open filling out the issue template
