### ISSUE TITLE
Router loses parameters

### ISSUE THREAD

**Issue by weini01** [angular/angular#11335]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
By clicking on an RouterLink the URL will be updated but the params of ActivatedRoute.params stay empty.

Example:
`this.route.params.subscribe(params => { 
  params are empty even if the url contains params
});`

**Expected/desired behavior**
The ActivatedRoute Observer should submit all params from the url.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
* **Router version:** 3.0.0-rc.2
 
* **Browser:** [Chrome52] 
 
* **Language:** [TypeScript]

**Comment by weini01** [comment]
I think it was my fault i put the ActivatedRoute into a Service and tried call the same ActivatedRoute from multiple components. That´s weird beause it worked with rc5 and all other prev releases...

```
export class RouterService{
  constructor(_route: ActivatedRoute) {
  }
  getParams() {
    return this._route.params;
  }
}

export class OverviewComponent implements OnInit {
  public paramsSub: any;
  constructor(private _router: RouterService) { }
  ngOnInit() {
    this.paramsSub = this._router.getParams().subscribe(params => {
      params always empty!
    }
  }
  ngOnDestroy() {
     this.paramsSub.unsubscribe();
  }
}
export class DetailComponent implements OnInit {
  public paramsSub: any;
  constructor(private _router: RouterService) { }
  ngOnInit() {
    this.paramsSub = this._router.getParams().subscribe(params => {
      params not empty!
    }
  }
  ngOnDestroy() {
     this.paramsSub.unsubscribe();
  }
}
```

**Comment by brandonroberts** [comment]
Most likely, you provided your service at the module level which is the root injectror. Providing the service to your components with the `ActivatedRoute` injected will give you the root `ActivatedRoute` which is at the top of the route tree.

The `ActivatedRoute` is provided per component to get the specific params.

**Comment by jneveux** [comment]
Hi,

I've the same issue with version 2.0.0. It only works for the component the router is updating.  I would imagine ActivedRoute.params.subscribe is called when parameters are changing.

plunker:  [https://plnkr.co/edit/Xxx21ImeKwz90YKsBm8l?p=preview](url)

app.ts and viewone.component contains subscribers.

Thanks,

Jean

**Comment by tscislo** [comment]
@jneveux I guess this is the whole idea behind it, to provide route params only in active component.
I do not get the concept yet and it bothers me as well, having anuglar-ui router experience. Maybe someone can elaborate?

**Comment by vsavkin** [comment]
One of the design constraints we used to build the router is that multiple teams should be able to build "application sections" independently. And these sections should be encapsulated: introducing a new parameter in one of them should not affect any other one. That's why ActivatedRoute should not be global.

When you need something like this, you can traverse a RouterState object. This, however, should be used very carefully (it is discouraged).

**Comment by vugar005** [comment]
Had this issue before. You can still access the params from other component which is not a direct child component by below method:
 `this.route.pathFromRoot.forEach((route) => route.params.subscribe((params) => console.log(params));`
