### ISSUE TITLE
Transclusion for root component

### ISSUE THREAD

**Issue by olostan** [angular/angular#11336]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Root component (that is bootstrapped) does not get any content transcluded with `ng-content`.

**Expected/desired behavior**

There should be a possibility to transclude root component's content into component's view.

**Reproduction of the problem**

Plunker: https://plnkr.co/edit/WozwzyMhajp6mIHoKcZA?p=preview
Observed: `Component content: `

**What is the expected behavior?**
`Component content: loading...`

**What is the motivation / use case for changing the behavior?**

There should be a consistent behaviour on `ng-content` no matter is it root component or any other that is used in view component.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by ericmartinezr** [comment]
Here's explained why this is not possible (yet) https://github.com/angular/angular/issues/1858

**Comment by olostan** [comment]
Seems it is a old well-known issue... But I think the title of that issue ("Can't retrieve attributes...") does not reflect the problem with content, that is why many other issues like this is created. 

I know that this issue will be closed, but I propose to create some generic issue that will reflect problem both for accessing attributes and content for root components so people wont be confused.

**Comment by ericmartinezr** [comment]
>but I propose to create some generic issue that will reflect problem both for accessing attributes and content for root components so people wont be confused.

Sounds cool. By the way, the reason is in this comment from @tbosch (https://github.com/angular/angular/issues/1858#issuecomment-151326461)

>The reason why this is not working [...] is not an angular component. Because of this Angular won't compile this element

PS: https://github.com/angular/angular/issues/6143

**Comment by vicb** [comment]
Closing as duplicate
