### ISSUE TITLE
md-data-table hangs when data more then 100 rows

### ISSUE THREAD

**Issue by kuldeeppoonia** [angular/angular#11331]
**Current behavior**
md-data-table  hangs when there is more then 100 records.

**Expected/desired behavior**
It should not be hanged because I have 1000 records and have editable rows.

**Reproduction of the problem**
I declare first column as checkbox. if I click on this check button and have more then 100 row then it takes long time. Also If I remove ngModel then also it takes long time. I have near by  1000 rows then in this case it totally hangs. I didn't want paging.

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [Chrome XX ] 
 
* **Language:** [TypeScript]

**Comment by michalstepien** [comment]
Hi, perhaps you have to change strategy to onpush.

**Comment by kuldeeppoonia** [comment]
Hi,

There is no problem in showing data. It's show me all 1000 rows properly But If I want to select a single row by selecting checkbox then it hangs whole page.

**Comment by vicb** [comment]
md-data-table is not angular core
