### ISSUE TITLE
After update RC6,application load slow!

### ISSUE THREAD

**Issue by sunnylearn** [angular/angular#11334]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I find my application load multiple complex modules，RC6 load home page very slow，but RC5 is load ok 。

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all | Chrome  53.0.2785.89 | Firefox 47 ] 
 
* **Language:** [ TypeScript 2.0.2]

**Comment by qdouble** [comment]
@sunnylearn you'd have to provide a reproduction...but if there is any significant difference, it's probably a bug in your app, not r6c itself.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by sunnylearn** [comment]
@qdouble ,I reduce module,run application speed faster,
but i don't know my application have bug,because angular2 throws no exceptions.

**Comment by tobias74** [comment]
I am having the same issue. With rc5 my application loads within 1 second, but after upgrading to rc6 it takes about 30 seconds for the app to start responding.

I am using this issue tracker, because to me this is an (wait for it) 
...issue. :-)

**Comment by sunnylearn** [comment]
@tobias74 thank you!

**Comment by qdouble** [comment]
@sunnylearn @tobias74 you might want to use the nightly builds to see if this commit fixes your performance problems: https://github.com/angular/angular/commit/78ad9adc1a0c39a642a9a012d692ac24c825afda

**Comment by sod** [comment]
@tobias74 yes, was my observation, too. Previously everything was lazy evaluated. Now the compiler goes through everything on startup. I guess the JIT now effectively does the same as the AoT, just in the browser upfront.
