### ISSUE TITLE
Calling asObservable() on EventEmitter<string> causes Resharper analysis to hang

### ISSUE THREAD

**Issue by paviad** [angular/angular#11347]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Calling `asObservable()` on a class member of type `EventEmitter<string>` or `EventEmitter<number>` causes Resharper analysis for that file to hang, and no Typescript context menu items appear when pressing Alt-Enter. As soon as the type is changed to `EventEmitter<any>` everything is ok again.

**Expected/desired behavior**
There should either be an error message of some kind, indicating the wrong usage -or- Resharper activity should not be degraded due to the call to `asObservable()`

**Reproduction of the problem**
I am not sure how to provide reproduction instructions, I'm working on it...

**Please tell us about your environment:**

Using:
* vs2013 ultimate
* JetBrains ReSharper Ultimate 2016.2  Build 106.0.20160818.163633
* **Angular version:** 2.0.0-rc.6
* **Browser:** Chrome 53.0.2785.89 m
* **Language:** TypeScript 1.8.10

**Comment by vicb** [comment]
> Resharper

Then I think you should create a ticket on their bug tracker and not on Angular.
