### ISSUE TITLE
gulp build.dart errors

### ISSUE THREAD

**Issue by vicb** [angular/angular#1134]
On my local machine
- master branch (9d21a6f40d4c5abb7aae3dab87867e64360fdc5a)
- fresh `npm install`
- `gulp clean`

`gulp build.dart` generates errors:

ie 
```
Could not format because the source could not be parsed:

line 12, column 1604 of dist/dart.ts2dart/angular2/src/forms/model.dart: Cannot have multiple groups of positional parameters in a single parameter list
```

For some reason it works on the CI.

/cc @mprobst @alexeagle

**Comment by vicb** [comment]
Seems like `/dist/dart.ts2dart` is not `gulp clean`ed but it does not solve the errors

**Comment by vicb** [comment]
@alexeagle points me to the answer, `ts2dart@0.1.5+`  is required, might need an `npm update` to get the latest version, check with `npm ls | grep ts2dart`

**Comment by tbosch** [comment]
Yes, I had a similar problem...

**Comment by tbosch** [comment]
With the same way how to solve it
