### ISSUE TITLE
Not found all cdns required for ng2 application based on rc4

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#11351]
Hi ,

I need all cdns required for ng2 application based on rc4. I have not found it anywhere.

Regards
Vasuneet Arya

**Comment by vicb** [comment]
not related to angular

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
