### ISSUE TITLE
compileModuleAndAllComponentsAsync View encapsulation

### ISSUE THREAD

**Issue by leobispo** [angular/angular#11357]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using compileModuleAndAllComponentsAsync together with ViewContainerRef.create

The component created inside the container is not receiving any encapsulation information.

IMO the created component should inherit the _ngcontent-* from the vcRef.

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [al] 
 
* **Language:** [all]

**Comment by vicb** [comment]
Please add plunker / details.

**Comment by leobispo** [comment]
I solved it using another approach but IMO this goes completely against the css (cascading style sheet) nature!!

**Comment by mbrookson** [comment]
I believe this is actually a valid issue and could be reopened. If you use compileModuleAndAllComponentsAsync to dynamically build a component, it's parent component's styles are not added to the dynamic one since the _ng... attributes are not added
