### ISSUE TITLE
CSS view encapsulation error when using ng-content

### ISSUE THREAD

**Issue by leobispo** [angular/angular#11356]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

CSS view encapsulation not working with `<ng-content></ng-content>`.

When you add a new content inside a tag it is getting the `<element _ngcontent-*>` from the parent of the parent.

For example:

```Typescript
@Component({
    selector: 'my-inner-component',
    template: `<div>INNER</div>`
})
export class MyInnerComponent {
}

@Component({
   selector: 'my-component',
    styleUrls: ['style.scss'],
    template: `
      <div>
        <ng-content select="my-inner-component"></ng-content>
      </div>
    `
})
export class MyComponent {
}
```

Is generating:

```XML
<my-component _ngcontent-ije-8 _nghost-ije-14>
  <div _ngcontent-ije-14>
    <my-inner-component  _ngcontent-ije-8></my-inner-component>
  </div>
</my-component>
```

but it should generate:

```XML
<my-component _ngcontent-ije-8 _nghost-ije-14>
  <div _ngcontent-ije-14>
    <my-inner-component  _ngcontent-ije-14></my-inner-component>
  </div>
</my-component>
```

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by vicb** [comment]
Please add a plunker showing the bug (not in term of impl but actual result) ?

**Comment by Prepd-Root** [comment]
We have experienced the same issue. 
Here's a [plunkr](https://plnkr.co/edit/y1p69BPnikTwA9LGD1tk) with an example.

With angular 2.0.0-rc6 there's no margin around the form inputs. With angular 2.0.0-rc5 there is. 

In systemjs.config.js you can toggle between 2.0.0-rc6 and 2.0.0-rc5. 
PS: might have to start-stop a few times for plunkr to reload libs.

**Comment by vicb** [comment]
@leobispo the behavior is right. The project content uses styles at its initial location as with native shadow DOM.

@Prepd-Root your plunker is not related to ng-content. Check the changelog to understand why the behavior has changed - it is actually a fix.

**Comment by leobispo** [comment]
@vicb: so that means I cannot style components based on the parent?

I would like to style components based on their parents.

If I have a tab view, I would like to have flat buttons

If I have a tab bar I would like to have round buttons.


 this is it possible with the encapsulation.

**Comment by zoechi** [comment]
@leobispo you can use

    :host-context(.some-class-on-an-ancestor) some-element {
      ...
    }

**Comment by leobispo** [comment]
@zoechi I solved it using a different approach... But IMO this behavior goes against the CSS nature where you can cascade styles
