### ISSUE TITLE
config.js:15 Uncaught TypeError: Cannot read property 'Emulated' of undefined

### ISSUE THREAD

**Issue by churchilllake** [angular/angular#11359]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
config.js:15 Uncaught TypeError: Cannot read property 'Emulated' of undefined
 @ config.js:15(anonymous function) @ compiler.js:75__webpack_require__ @ bootstrap e6867a8…:52(anonymous function) @ main.bundle.js:50230__webpack_require__ @ bootstrap e6867a8…:52(anonymous function) @ main.bundle.js:13600__webpack_require__ @ bootstrap e6867a8…:52(anonymous function) @ main.bundle.js:56647__webpack_require__ @ bootstrap e6867a8…:52(anonymous function) @ main.bundle.js:56625__webpack_require__ @ bootstrap e6867a8…:52(anonymous function) @ version.js:1__webpack_require__ @ bootstrap e6867a8…:52(anonymous function) @ main.bundle.js:67287__webpack_require__ @ bootstrap e6867a8…:52webpackJsonpCallback @ bootstrap e6867a8…:23(anonymous function) @ main.bundle.js:1

**Expected/desired behavior**
smooth sailing, no errors

**Reproduction of the problem**
Getting it from a newly "ng new" created project

**What is the expected behavior?**
smooth sailing, no errors

**What is the motivation / use case for changing the behavior?**
I believe line 80 calls ConfigCompiler() and the error is caused because an argument is expected

Line 80 = "{ provide: CompilerConfig, useValue: new CompilerConfig() },"

Also CompilerConfig is imported twice.

The line 75 of compiler.js in the traceback above is now line 80 in github.

**Please tell us about your environment:**
osx 10.11.6

* **Angular version:** 2.0.0-rc.X
angular 2.0.0-rc6
 
* **Browser:** 
Chrome  53.0.2785.89 (64-bit) 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
all

**Comment by ericmartinezr** [comment]
>Getting it from a newly "ng new" created project

That's an issue with angular-cli already reported over here https://github.com/angular/angular-cli/issues/1948
