### ISSUE TITLE
Dealing with ngStyle and vendor prefixes

### ISSUE THREAD

**Issue by Udgin** [angular/angular#11362]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently I am not able to add vendor prefixes using ngStyle:

    background: -webkit-linear-gradient(left, black 15%, white 1%);
    background: -moz-linear-gradient(left, black 15%, white 1%);
    background: -ms-linear-gradient(left, black 15%, white 1%);
    background: linear-gradient(left, black 15%, white 1%);

**Expected/desired behavior**
This looks reasonable - [Dealing with ng-style and vendor prefixes](https://josee.me/2014/09/11/dealing-with-ng-style-and-vendor-prefixes/). Basically this code looks good for me:
````
        let styles = {
        'background' : ['-webkit-linear-gradient(left, black 15%, white 1%)',
            '-ms-linear-gradient(left, black 15%, white 1%)',
            '-moz-linear-gradient(left, black 15%, white 1%)',
            'linear-gradient(left, black 15%, white 1%)']
        };
        return styles;
```
* **Angular version:** 2.0.0-rc.6

**Comment by gdi2290** [comment]
you're looking for this
https://github.com/rofrischmann/inline-style-prefix-all
or this
https://github.com/ajoslin/ng-style
either way, this is a support question rather than an issue with the repo

**Comment by Udgin** [comment]
Thanks for replay and sorry for wrong way to asking/suggesting issues. Looks like it is better to close this issue if there is workaround.
