### ISSUE TITLE
Using HTML5 <time> tag leads to an template parse error

### ISSUE THREAD

**Issue by ManuelRauber** [angular/angular#11361]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm using the HTML5 `<time>`-tag like here ([MDN](https://developer.mozilla.org/en/docs/Web/HTML/Element/time), [HTML5 Spec](https://www.w3.org/TR/html5/text-level-semantics.html#the-time-element)):

```
<time [attr.datetime]="model.startDate" *ngIf="model.startDate">
            <strong>{{ model.startDate | date:'d' }}</strong>
            {{ model.startDate | date:'MMM' }}
</time>
```

And I'm getting 

```
VM493 zone.js:461 Unhandled Promise rejection: Template parse errors:
'time' is not a known element:
1. If 'time' is an Angular component, then verify that it is part of this module.
2. If 'time' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
```

**Expected/desired behavior**

I expect no error to be thrown by the Angular 2 Framework. I don't expect to add this tag to the `CUSTOM_ELEMENTS_SCHEMA`. 

**Reproduction of the problem**

Take a look at this plunkr: https://plnkr.co/edit/UvQ731i8QUHISTePD7my. I just added `<time></time>` to the `src/app.ts`.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** Chrome 52
 
* **Language:** TypeScript 1.8.10

**Comment by ericmartinezr** [comment]
This PR fixes it https://github.com/angular/angular/pull/11232

**Comment by ManuelRauber** [comment]
@ericmartinezr Thanks for mentioning. I close this one here. I just searched the issues. :/
