### ISSUE TITLE
Input components inside form are not bound to the form

### ISSUE THREAD

**Issue by ArielAleksandrus** [angular/angular#11360]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The detailed problem was posted on StackOverflow by me [here](http://stackoverflow.com/questions/39323179/angular2-custom-directives-inside-form-misbehavior)

Suppose we have a template-driven form, 1 input element and 1 component:

```
<form #f="ngForm" (ngSubmit)="submit()" ...>
  <input type="text" name="example1" [(ngModel)]="example1" ... />
  <my-custom-input [attr]="example2"></my-custom-input>
</form>
```

and _my-custom-input_'s template is:

`<input type="text" name="example2" [(ngModel)]="attr" ... />`

If we change _example1_'s input, the form will also be updated. `f.form.pristine` will be **false**, as expected.

If we change _example2_'s input, the form will **NOT** be update. `f.form.pristine` will be **true**

**Expected/desired behavior**

It is expected that inputs that are declared in a component inside a form to be bound to the form. I.e., that for the example above, changing _example2_'s input would alter the form's state, like the "pristine" state to be changed to false.

**Reproduction of the problem**

Couldn't get it plunkr to work, but here it is anyways, so you can see the code that reproduces the problem:

http://plnkr.co/edit/bwgHcO5lgcvqnX1FepEF?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome Version 52.0.2743.116 (64-bit) ] 
 
* **Language:** [Typescript 2.0.0]

**Comment by kara** [comment]
@ArielAleksandrus It looks like your plunker was just missing the `FormsModule` import and the `InputComponent` declaration :)  From looking at the code, it seems like your `ngModel` was living only on the nested component level. If you want your custom component to be recognized as a form control, you'll want to implement the `ControlValueAccessor` interface and put the `ngModel` on the form's top level.  You can see an explanation of how to implement a custom form component with some example code [here](https://github.com/angular/angular/issues/9281#issuecomment-238610807).

**Comment by ArielAleksandrus** [comment]
@kara [THIS](http://plnkr.co/edit/7Fomb1S8NazKgUMGy6m4?p=preview) plunkr is really awesome, but there is a little **problem**. With this solution, the page is loaded and the form's pristine value is **false**, as you can see in [THIS](http://plnkr.co/edit/U9f4oRgI0EIiqGHud2wB?p=preview) little modification I've made of your plunkr. I wonder why that happens...

**Comment by kara** [comment]
@ArielAleksandrus  Good questions! To answer:

In your plunker, you're adding the `required` validator to your nested component, which is a level too deep.  If you want to add a validator to a custom form control using a template-driven approach, you have two options:  

1. You can add the `required` validator to the top-level form. This is something that the consumer of your custom component would do if they wanted to add that validation for their own purposes.

```ts
<my-child name="username" [ngModel]="person.username" required>
```
Example: http://plnkr.co/edit/8UWEuDOBdOCzmHgKjHQe?p=preview

2.  Or, if you want your component to always provide the required validator, you have to add it to your component's providers list:

```
providers: [
  {provide: NG_VALUE_ACCESSOR, useExisting: Child, multi: true},
  {provide: NG_VALIDATORS, useValue: Validators.required, multi: true}
]
```

Example: http://plnkr.co/edit/BBaTLk8aoh8GZDAFi6jl?p=preview

Regarding the pristine property, this has to do with how I wrote the sample component. To make it easier to understand, I was simply listening to the `valueChanges` event emitter. This fires every time the value changes regardless of user input.  If you care about pristine state, that implementation is too simplistic. Instead you'll want to listen to the `input` event and pass through the value.

Example: http://plnkr.co/edit/NXurYlUBnStK90SXAJUe?p=preview

Sorry for the confusion there. I think by oversimplifying I actually made it more confusing. Updated the original plunker as well.
