### ISSUE TITLE
DatePipe define global default pattern

### ISSUE THREAD

**Issue by Fank** [angular/angular#11376]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Currently the default pattern is `mediumDate` but in a other language like german the default pattern should be `ddMMyy`

**Current behavior**
Overwrite pattern on every pipe:

``` html
<p>{{ myDate | date:'ddMMyy' }}</p>
<p>{{ myOtherDate | date:'ddMMyy' }}</p>
<p>{{ otherVar }}</p>
<p>{{ myOtherOtherDate | date:'MMyyDD' }}</p>
```

**Expected/desired behavior**
There should be a variable like `LOCAL_ID` shich can be overwritten:

``` ts
@NgModule({
    providers: [
        {provide: LOCAL_PIPE_DATE_PATTERN, useValue: 'ddMMyy'},
    ],
})
export class AppModule {}
```

So we can use:

``` html
<p>{{ myDate | date }}</p>
<p>{{ myOtherDate | date }}</p>
<p>{{ otherVar }}</p>
<p>{{ myOtherOtherDate | date:'MMyyDD' }}</p>
```

**What is the motivation / use case for changing the behavior?**
In some languages like german we want dates like '2016-02-01' written '01.02.2016' so, it would be much better to define a default pattern per "language" instead of set the pattern on every pipe.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6
- **Browser:** [all] 
- **Language:** [all]

**Comment by kemsky** [comment]
And this token already exists in RC.6 `LOCALE_ID`: `{provide: LOCALE_ID, useValue: 'de-DE'}`.

**Comment by Fank** [comment]
@kemsky not for the language 'de-DE' or 'en-EN' it's for the default date formating

**Comment by kemsky** [comment]
Indeed it is not that flexible. 
As a temporary solution you could implement custom date pipe via extending built-in one. It was possible to override built-in pipes using `PLATFORM_PIPES` which is deprecated now, guess you will need to put it into module's providers.

**Comment by Fank** [comment]
I would prefer the default output from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat if no formatings are given.
