### ISSUE TITLE
Lazy-Loading route configuration doesn't work with webpack

### ISSUE THREAD

**Issue by lwensveen** [angular/angular#11372]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using loadChildren throws `TypeError: lang_1.global.System.import is not a function`

**Expected/desired behavior**
Expect it to work without any problems.

**Reproduction of the problem**
Use webpack and implement loadChildren in routes. I think the problem lies in the point hansl makes in this PR: https://github.com/angular/angular/pull/11049

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Chrome 53
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
Typescript 2.0.0

**Comment by vicb** [comment]
not actionable

**Comment by gnujeremie** [comment]
What do you mean by "not actionable" ? (Sorry I'm french, I'm not sure to I understand correctly).

The documentation says :
```Angular provides a built-in module loader that supports SystemJS to load modules asynchronously. If we were using another bundling tool, such as Webpack, we would use the Webpack mechanism for asynchronously loading modules.```, but there is no information on how to achieve this using webpack and angular.

**Comment by hunterleaman** [comment]
This discussion may be helpful: https://github.com/AngularClass/angular2-webpack-starter/issues/829

**Comment by gnujeremie** [comment]
@hunterleaman thanks i'll check it out.
