### ISSUE TITLE
Router events API could be more convinient

### ISSUE THREAD

**Issue by kemsky** [angular/angular#11375]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Sometimes it is necessary to handle successful route changes (in my case it is custom navigation control), however it is difficult to implement using current router API:
```
var cancelled = {};
this.router.events.subscribe((e:Event) =>{
      if(e instanceof NavigationCancel || e instanceof NavigationError){
            cancelled[e.id] = true;
      }
      if(e instanceof NavigationEnd){
             if(!cancelled[e.id]){
                   //success!
             } else {
                  delete cancelled[e.id];
             }
      }
});
```
I'm not sure if it is even correct.

**Expected/desired behavior**

1. Should be able to use string identifier/enum to filter events instead of `instanceof`.
2. Should be additional event for successful(and i think failed as well) navigation or `NavigationEnd` could expose status flags.
3. Assuming 1 and 2 implemented there should be only one event class, no need to have 4 slightly different classes and import them.
4. Creating type with name `Event` is bad idea because of name clashes. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript 1.8.11]

**Comment by zoechi** [comment]
4) You can disambiguate using import prefixes.

**Comment by brandonroberts** [comment]
You can also just create a service that provides filtered navigation event streams and subscribe to those where needed.

**Comment by kemsky** [comment]
The point here is that API is not friendly and anyone who wants to listen for successful route changes will have to deal with it. It is still possible to improve before final release. 

By the way: Is new router singleton?

**Comment by brandonroberts** [comment]
No new API changes will be done before release, so that's where it is now. And yes the new router is a singleton.

**Comment by vsavkin** [comment]
Doing this will be a breaking change. I think that the benefits won't justify the cost. Closing this issue.
