### ISSUE TITLE
Router not working with multiple query parameters with the same name.

### ISSUE THREAD

**Issue by spacebeers** [angular/angular#11374]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently when going to a url with multiple query parameters with the same key the DefaultUrlSerializer is removing all but the last one from the url.

`/something/route?room=a1&room=a4&room=a6`

This link will be rewritten to:

`/something/route?room=a6`

**Expected/desired behavior**

The url should remain the same and keep all parameters.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6
- **Browser:** all
- **Language:** Typescript

This pull request fixes the issue but it's my first one - https://github.com/angular/angular/pull/11373

**Comment by marcalj** [comment]
This is a controversial decision. This is a query **string**, so ```{[key:string]:string}```.
For some "backends" (like SOLr) multiple query string parameters means an array, for others they ignore all except the first one, etc.

When we need a non-string complex value we store the stringified version of a JSON. I think there's no standard about it and each company do whatever they want or the backend programming language accepts (PHP use ```?foo[]=a&foo[]=b``` for arrays).

Interesting decision to make...

**Comment by spacebeers** [comment]
True but I don't see any reason to remove the multiple values from the url. Handling them seems like something Angular should be able to do but I agree a standard would be nice. I fear controversy though.

**Comment by marcalj** [comment]
How you expect to access this data, as array? For me it make sense to ignore all except first, or all except last. Super controversial.

I think we should define a mode to read/write query string, and a way to create a custom parser.

**Comment by spacebeers** [comment]
I would expect an array back.

**Comment by TeeeJay** [comment]
I would at least expect some way of handling the use case of when we need to send an array as parameter (e.g. in faceted search), instead of having to deal with parsing the string yourself. +1 for the bug report and pull request.

**Comment by jtomaszewski** [comment]
jQuery, angular1, PHP, Ruby on Rails, they all support arrays, by serializing it to f.e. `?foo[]=bar&foo[]bar`. Why should we do it differently?

**Comment by tinchou** [comment]
My two cents: I'm using ASP.NET Core and I use `?foo=bar&foo=baz`. Don't know if `?foo[]=bar&foo[]=baz` also works.

**Comment by xealot** [comment]
Why is this decision controversial? While different backends interpret the query string part of the URL differently, I don't see a disadvantage for Angular to parse the query string in a way that maintains as much information as possible.

If the query string is parsed and interpreted as a `map[string]string[]` then any simpler scenario could be expressed. There is a lot of precedent for interpreting query strings and HTTP headers in this way.

**Comment by spacebeers** [comment]
At the least I'd expect it to not remove it from the URL

**Comment by DzmitryShylovich** [comment]
Should be fixed here https://github.com/angular/angular/pull/11373

**Comment by DzmitryShylovich** [comment]
@vicb can be closed

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed
