### ISSUE TITLE
Injecting a service in a lazy-loaded module trows an unknown provider error

### ISSUE THREAD

**Issue by diestrin** [angular/angular#11388]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Injecting a service in a lazy-loaded module throws an unknown provider error

**Expected/desired behavior**
Injecting a service in a lazy-loaded module injects the service

**Reproduction of the problem**
I have created a code to dynamically bootstrap modules in my page (we have a custom set up that lazy load the components as they apear in the screen).

This code works fine and do the task, but I have a problem, when I include an NgModule in the `imports` of one of the bootstrapped modules, the injector doesn't recognize the services declared in the imported module. Only if I include the NgModule (the one with a service) in the root module, it gets injected correctly.

Here's a summary of the code that bootstraps with custom selector
```
@NgModule({
  providers: [SystemJsNgModuleLoader],
  imports: [BrowserModule]
})
class AppModule {
  ngDoBootstrap() {}
}

const modulePath = './src/test#TestModule';
const moduleSelector = '#testId';

platformBrowserDynamic()
.bootstrapModule(AppModule)
.then(appModule => {
  const ngModuleLoader = appModule.injector.get(SystemJsNgModuleLoader);
  return ngModuleLoader.loadAndCompile(modulePath)
  .then(moduleFactory => ({moduleFactory, appModule}));
})
.then(({moduleFactory, appModule}) => {
  let injector = appModule.injector;
  const ngModule = moduleFactory.create(injector);
  const app = ngModule.injector.get(ApplicationRef);

  ngModule.bootstrapFactories.forEach(comp => {
    comp.selector = moduleSelector;
    app.bootstrap(comp);
  });
});
```

Here's a [plnkr](http://plnkr.co/edit/Ylv04QMyzeeNrQQh7yrE?p=preview) with the example working (NgModule imported in the root module)
Here's a [plnkr](http://plnkr.co/edit/nBuVVY?p=preview) with the example failing because a missing provider (NgModule imported in the dynamically bootstrapped modules)
Here's a [plnkr](http://plnkr.co/edit/o9hTH29vjp6BPBda6QwO?p=preview) working correctly without lazy-load with custom selector

**What is the expected behavior?**
The Service imported in a lazy loaded module should be injected in that lazy loaded module.
Right now, only moving the import declaration to the root module gets the Service to be injected

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6

* **Browser:** [all]

* **Language:** [TypeScript 1.8]

**Comment by diestrin** [comment]
[Comment by](https://github.com/angular/angular/issues/9726#issuecomment-245031952) @tbosch

Could you create a separate issue for this? This is in general just related to module loading, and not to bootstrap of a component with a custom selector.

Your problem is that a service in a root module can not inject a service that is declared in a lazy loaded module, only the other way around. And this makes sense, as loading of modules is intended for code loading, i.e. your root module cannot refer to the service of the lazy loaded module as that code has not been loaded on bootstrap.

**Comment by diestrin** [comment]
My problem is not a root module service injecting a lazy-loaded service.
My problem is a lazy loaded Module cannot inject the service it declared on its own.

In the provided example
```
@NgModule({
  imports: [ServiceModule],
  declarations: [Test],
  bootstrap: [Test]
})
export class TestModule {}
```

That modules is being lazy loaded, but the Service (declared as in injectable in ServiceModule) is not being injected.

**Comment by kemsky** [comment]
I think this issue is exactly the same as described in FAQ: [Why is a service provided in a lazy loaded module visible only to that module?](https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-lazy-loaded-module-provider-visibility)

**Comment by diestrin** [comment]
Actually no, the service is not even being visible in the lazy loaded module

**Comment by kemsky** [comment]
If my understanding is correct, you are loading two modules: Test and Test2, which have dependency on ServiceModule, but in fact you are lazy loading three modules: Test, Test2 and their dependency - ServiceModule. Thats it, all three were lazy loaded.

**Comment by diestrin** [comment]
I think... your're right :( Closing...

**Comment by kemsky** [comment]
It is still valid issue i think, because it is not covered in documentation or in FAQ. It should state explicitly that imports do not work for lazy loaded modules, otherwise it might be a bug.

**Comment by diestrin** [comment]
Actually reopening, this is happening with services inside the same Module. http://plnkr.co/edit/nBuVVY?p=preview

This is a single module being lazy loaded with a service declared in the same file, declared in the injectable of the module, still getting the same unknown provider error.

**Comment by RobertBroersma** [comment]
@diestrin I realise it's a while ago, but did you find a solution for this? I have a lazy loaded module with a few services listed in `providers` and get the No provider error.

**Comment by diestrin** [comment]
@RobertBroersma my issue was because I was doing a custom bootstrap logic, and forgot to use the correct injector to bootstrap. If you're bootstrapping your application with the normal process, your issue should be something else.
