### ISSUE TITLE
Angular 2 documentation code for Dev Guide/Routing & Nav not working in Chrome v52 but fixed in v53

### ISSUE THREAD

**Issue by SN2014J** [angular/angular#11381]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This problem is with the browser, not with Angular, and has already been resolved by a browser update. However, I report it here because it presents itself as a buggy version of Angular, and this report may help others identify the source of the problem and fix it (by updating their browser). It may also give the Angular team some insight into an edge case that needs investigation.

This problem only occurs with Mac Chrome version 52 (i.e. 52.0.2743.116 64-bit) and is fixed when it is updated to version 53 (i.e. 53.0.2785.89 64-bit). The problem does not occur for Mac Firefox 48.0, Mac Safari 9.1.3, Mac Opera 36.0.2130.46, Windows Firefox 48.0.2, Windows Chrome 51.0.2704.103m and Windows Opera 39.0.2256.48. I am not currently able to upgrade Windows Chrome to either version 52 or 53 so I am currently unsure if this problem also occurs for Windows Chrome version 52 but not 53.

The problem: The Angular 2 (2.0.0-rc.6) documentation in the Developers' Guide for Routing and Navigation provides a live example that runs in Plunkr. The 'Heroes' and 'Login' routes work properly. However, the 'Crisis Center' and 'Crisis Admin' routes are non-functional, i.e. nothing happens when you click their respective links. Upon clicking these links a 404 error appears. (I can't recall which file couldn't be found, as the browser update has made it impossible to reproduce the error.)

**Expected/desired behavior**

The 'Crisis Center' and 'Crisis Admin' links in the Angular 2 tutorial should work.

* **Angular version:** 2.0.0-rc.6
 
* **Browser:**
(see above description)

**Comment by vicb** [comment]
https://github.com/angular/angular.io is the repo for docs. Please report issue there.

**Comment by SN2014J** [comment]
Thank you for the redirection.
