### ISSUE TITLE
Angular RC5 - Big Binding Bug

### ISSUE THREAD

**Issue by Ivandolchevic** [angular/angular#11383]
Hello,

* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
A binded component with a simple `*ngFor` doesn't react to non-human events. 

### Here is the binded component _List_
```
@Component({
    selector:'list',
    template:`
        <div>
             <div *ngFor="let element of elements; let i=index">{{element}}</div>
        </div>
    `
})

export class List{
    @Input() list;
}
```
### HTML
```
<div>
<list [elements]="elements"></list>
</div>

### Typescript
export class Stats {
    likeServices;
    likesServicesSubscriptionGet;
    elements;

    constructor(@Inject(LikeServices) _likeServices:LikeServices){
        this.likeServices = _likeServices;
    }

    ngOnInit(){
        this.likesServicesSubscriptionGet = this.likeServices.data_ready
            .subscribe(
                data => {
                    this.update();
                });
    }

    update(){
        console.debug("updating");
        this.elements= this.likeServices.getAll();
        console.debug(this.elements);
    }
}
```

When I execute, I can view "updating" and I can see all the elements of my collection in the console log. BUT nothing is displayed. 

And now, if I do the following thing in my HTML
```
<div (click)="update()">
<list [elements]="elements"></list>
</div>
```
My elements are displayed if I click. 
That's work only with a human action ! :/

- Angular version: 2 RC5
- Browser: [all ]

**Comment by Ivandolchevic** [comment]
Angular doesn't detect that my variable `elements` has changed if I change its value on event raising.

**Comment by vicb** [comment]
Please re-open with a plunker demonstrating the issue.

could probably be "fixed" with:
```ts
    update(){
        this.ngZone.run(() => this.elements= this.likeServices.getAll());
    }
```

**Comment by Ivandolchevic** [comment]
Excellent ! That's work. Something has changed from Angular beta 47 because I never had that problem before. odd ...
