### ISSUE TITLE
Angular2 outlet route not working!

### ISSUE THREAD

**Issue by LiorKooz** [angular/angular#11382]
Hi,

I'm try to add name at outlet but I got an exception.
My goal is to load two child's components into MainComponent. (I dont need a route for the other modules).

```
const routes: Routes = [
    {
        path: '',
        component: MainComponent,
        children: [
            { path: '', loadChildren: 'modules/componentA/componentA.module' },
            { path: '', loadChildren: 'modules/componentB/componentB.module', outlet: 'compB' }
        ]
    }
];

export const routing = RouterModule.forChild(routes);
```

MainComponent: 
```
@Component({
    selector: 'my-component',
    template: `<router-outlet></router-outlet>
                <router-outlet name='compB'></router-outlet>`,
})
```

But I got this error: 
TypeError: Cannot read property 'routes' of undefined
at getChildConfig (http://localhost:30814/lib/@angular/router/bundles/router.umd.js:1794:39)

When I try to debug inside angular2-router file, it seems that _loadedConfig is missing from the route object.

Any ideas?

**Comment by mrkosima** [comment]
Could you please add your module code?
I also have trouble with loading children into named outlet #11208

**Comment by vicb** [comment]
Please fill out the template when creating issue.

This one misses:
- angular version,
- a repro.

**Comment by molcik** [comment]
Anyone found work around?

**Comment by zoechi** [comment]
Work around about what? 
If you think there is an issue, then please create a new issue and provide the information that allows to reproduce (fill the issue template).

**Comment by molcik** [comment]
I did already #12842

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
