### ISSUE TITLE
RC6 Forms: Disabled empty FormArray enable itself

### ISSUE THREAD

**Issue by CaselIT** [angular/angular#11386]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
An empty form array enable itself after an `updateValueAndValidity`

**Expected/desired behavior**
The form array should stay disabled.

**Reproduction of the problem**
[If the current behavior is a bug or you can illustrate your feature request better with an example](http://plnkr.co/edit/yIu2axqSzXWVJPhF6Hw6)

I think that the form array is re enabled by this [line](https://github.com/angular/angular/blob/70b0ab457bf7942b74a3f2b659684d0328e9d2dc/modules/%40angular/forms/src/model.ts#L914)

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all]  
* **Language:** [all]

**Comment by kara** [comment]
Thanks for reporting! On it.

**Comment by CaselIT** [comment]
Thanks @kara for fixing it
