### ISSUE TITLE
Perf: Direct Dom Rendering

### ISSUE THREAD

**Issue by tbosch** [angular/angular#11394]
Right now, Angular always uses the `Renderer` to stamp out elements. If we know we run in the browser without web workers, we can do better:
- Generate plain `document.createElement` / `element.setAttribute` / `element.style.... = ...` / `element.someProp = ...` calls
- Add a flag `directDom` to `CompilerOptions` and `tsconfig.json` to opt into this behavior
- Don't store `allNodes` in prod mode any more

Can be implemented with or without #11673. If without: still have a helper function for `createElement` that automatically adds the right css classes

Add a plugin mechanism to support other kinds of rendering, e.g. for serverside rendering or webworkers or nativescript.

Also support typing the properties in which we store the elements correctly. E.g. with an `HTMLDivElement`, ...

**Comment by tbosch** [comment]
This is done via https://github.com/angular/angular/pull/12692

**Comment by laco0416** [comment]
As a result, direct rendering will be an optional feature? or a default behavior?

**Comment by tbosch** [comment]
On by default. Only off in debug mode or when using web workers.

**Comment by laco0416** [comment]
Thanks. I really hope this change will not break next release.

**Comment by tbosch** [comment]
We need to do more in this regard, i.e. inline more from the renderer into the generated code to speed up things. The changes I did in #12692 didn't speed up ng too much ...

**Comment by tbosch** [comment]
With Angular 4 we have a very shallow `Renderer` implementation that experiments have shown that more inlining does not help.
