### ISSUE TITLE
Even with disabling security, in rc-4 I cannot bind to style.background-image

### ISSUE THREAD

**Issue by bytenik** [angular/angular#11399]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I bind to [style.background-image] or [ngStyle] with a background-image, and no CSS binding occurs.

**Expected/desired behavior**

The image should be bound as the background-image CSS.

**Reproduction of the problem**

https://plnkr.co/edit/UAwx87?p=preview

In the above link, the div inside of logo-stack has a background-color bound, but no background-image.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by bytenik** [comment]
How is this not a bug? The background-image binding does not work on rc.4. I even included a repro.

**Comment by vicb** [comment]
The current release is rc6, your repro is buggy.

**Comment by bytenik** [comment]
Ok then. I updated the repro to rc6, where this _still_ doesn't work.

https://plnkr.co/edit/UAwx87?p=preview

**Comment by vicb** [comment]
this is **still** a support request...

but because you insist: `[style.background-image]="'url(https://angular.io/resources/images/logos/standard/logo-nav.png)'"`
