### ISSUE TITLE
AoT Compiler unable to resolve module with "export default class"

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#11402]
**I'm submitting a ...** 

```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
To allow a module to be loaded lazily, I define its route like so:

```
{
    path: 'report',
    loadChildren: '/app/report/report.module'
}
```

And I declare it as the default class in _report.module.ts_ so the router will know what to load:  

```
export default class ReportModule {}
```

Using `export default class ReportModule {}` instead of `export class ReportModule {}` when declaring modules breaks `ngc`.  During compilation I get error:

```
can't resolve module C:/path/to/report.module.ts from C:/path/to/report.module.ts
Error: can't find symbol ReportModule exported from module C:/path/to/report.module.ts
    at ReflectorHost.findDeclaration (C:\path\to\@angular\compiler-cli\src\reflector_host.js:174:23)
    at _loop_1 (C:\path\to\@angular\compiler-cli\src\codegen.js:52:51)
    ...
Compilation failed
```

I left the orientation of the slashes (forward `/` and back `\`) as they appear in the console

**Expected/desired behavior**

An earlier version of [the docs](https://angular.io/docs/ts/latest/guide/ngmodule.html) on `ngModule` suggested using `export default` to expose lazy-loaded modules. This works well with Just-in-Time compilation. So I expected the AoT compiler to be able to parse them as well

**Reproduction of the problem**

Try compiling an application with a module declared with `export default`

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6
- **Browser:** [all] 
- **Language:** [TypeScript 2]

**Comment by vicb** [comment]
@mhevery @alexeagle Chuck says this is related to your module resolution changes.

**Comment by mhevery** [comment]
@vsavkin it seems like the Router does not understand default exports?

**Comment by alexeagle** [comment]
No, this is in ReflectorHost so I don't think it's router-specific.

**Comment by robwormald** [comment]
I think the compiler / codgen pipeline in general doesn't handle default exports (yet)

**Comment by drager** [comment]
What's the current status of supporting default exports?

**Comment by CumpsD** [comment]
What is the suggested approach to AoT lazy loaded modules, if `export default class` doesnt work?

**Comment by Ks89** [comment]
Any updates?
I have the same problem with Angular 2.1.0 and typescript 2.0.3.
Can we use "export default class" or not? It is useful to know if we must remove all default exports or not.

Thank u.

**Comment by petercn** [comment]
Same question here, any updates on when default exports will be supported by the AoT compiler?

**Comment by andershagebakken** [comment]
Hi. Because of this, my project stops at 70% while building modules. Is there any way I can disable aot when running "ng serve" now? Thanks.

**Comment by entitycs** [comment]
Take the 'rollup' command from your aot script.  You are trying to lazy
load, but rollup creates a single file, loaded once the site is navigated
to.

**Comment by joebri** [comment]
Also getting exactly the same issue when using an external component. There's really no solution to this?

**Comment by DzmitryShylovich** [comment]
@joebri nope, you can't use default exports

**Comment by pgrm** [comment]
Hi, 4 months ago @robwormald wrote in https://github.com/angular/angular/issues/11975#issuecomment-250427362 

> ... we do plan to support this.

Is there any chance that this would get supported with the upcoming version 4?

**Comment by mhevery** [comment]
Sorry, this is not priority, but we would accept a PR.

**Comment by Draccoz** [comment]
Similar issue here. Build breaks with default exports. Issue disappears when using normal (non-default) exports.

**Comment by frankforward** [comment]
@mhevery is there any work around in the mean time?

**Comment by DzmitryShylovich** [comment]
@frankforward don't use default exports :)

**Comment by kamalbabu57** [comment]
Will  default exports will be supported by the AoT compiler  in version 5 ?

**Comment by pavel-agarkov** [comment]
Just place both export types and it works:
`@NgModule({})`
`export class MyModule { }`
`export default MyModule;`

**Comment by manugarciac** [comment]
@pavel-agarkov When I place both exports, AOT compiles, but I get the following error in production:

`
ERROR Error: Uncaught (in promise): Error: Cannot find 'default' in './registration/registration.module'
Error: Cannot find 'default' in './registration/registration.module'
`

**Comment by pavel-agarkov** [comment]
I think it depends on what is your module target and bundle tooling. I use webpack to produce commonjs modules.
So in my case I could instead write something like this:
```typescript
@NgModule({})
export class MyModule { }
export const default = MyModule;
```
Try to play with this idea.

**Comment by avatsaev** [comment]
What if I'm building an Angular component library, and have an embedded third party lib that uses default exports, I have no control over it, and my lib doesn't build because of this.

**Comment by trotyl** [comment]
> Sorry, this is not priority, but we would accept a PR.

Why not just making a PR if you really need that, rather than waiting for years...

**Comment by fr0** [comment]
I spent two hours tracing this down in my app. Googling the error message didn't lead anywhere. Once I discovered it (by accident), I finally found this issue.

*Please* make this a priority so other devs won't waste time like I did.

**Comment by mlc-mlapis** [comment]
@fr0 ... lol, I met the same case about 1 year ago. 😄

**Comment by robwormald** [comment]
I believe this just works by default in Ivy.

**Comment by bvkeersop** [comment]
This is still a thing, error message could be better: 
'ERROR in : Unexpected value 'null' imported by the module' when you export a routing module as default.

If I hadn't found a thread referencing the same error this would've been a pain to solve.

**Comment by SchnWalter** [comment]
Haven't checked, but I just saw commint two commits that landed into Angular v9 and I think they might also solve this issue, see: https://github.com/angular/angular/commit/373e133 and https://github.com/angular/angular/commit/c4e039a

**Comment by Ni55aN** [comment]
Wow, 2019 is coming to an end, the problem still exist

**Comment by montella1507** [comment]
> Wow, 2019 is coming to an end, the problem still exist

same for i18n and working solution

**Comment by niklaas** [comment]
This can be fixed by providing the exported class through a factory provider. The following is an example providing `MarkerClusterer` from `@google/markerclustererplus`:

```ts
import MarkerClusterer from '@google/markerclustererplus';

export const MARKER_CLUSTERER_CLASS = new InjectionToken<new (...args: any) => MarkerClusterer>(
  'MarkerClustererPlus class from @google/markerclustererplus',
);

export function markerClustererClassFactory(): new (...args: any) => MarkerClusterer {
  return MarkerClusterer;
}

@NgModule({
  providers: [
    { provide: MARKER_CLUSTERER_CLASS, useFactory: markerClustererClassFactory },
  ],
})
export class SomeModule {}
```

**Comment by JoostK** [comment]
Hey folks,

default exports are now working in the Ivy compiler!
