### ISSUE TITLE
AOT bug when importing compiled css from same directory

### ISSUE THREAD

**Issue by qdouble** [angular/angular#11408]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
If you generate ngc in the same directory as the compiled files, upon creating a build, it will pull the css file, instead of the css.ts file. For example, if I import './app.css', upon compiling it will generate './app.css.ts'. Upon building, if these files remain in the same directory, './app.css' will be used instead of './app.css.ts' this will create the following error.

> error_handler.js:52TypeError: Cannot read property 'replace' of undefined
>     at Function.StringWrapper.replaceAll (lang.js:154)
>     at _flattenStyles (dom_renderer.js:287)
>     at new DomRenderer (dom_renderer.js:82)
>     at DomRootRenderer_.DomRootRenderer.renderComponent (dom_renderer.js:53)
>     at DebugDomRootRenderer.renderComponent (debug_renderer.js:18)
>     at ViewUtils.renderComponent (view_utils.js:48)
>     at _View_App0.AppView (view.js:67)
>     at _View_App0.DebugAppView [as constructor](view.js:347)
>     at new _View_App0 (app.ngfactory.ts:126)
>     at viewFactory_App0 (app.ngfactory.ts:512)

**Expected/desired behavior**

It should prefix or change the filename of the generated css in some way where it could determine the difference between the original css and the generated file. For example, if you change the name of the file to './app.ngfactory.css' and change the import on './app.ngfactory.ts' to something like `import * as import13 from './app.ngfactory.css';` it will build without any naming conflict. 

**What is the expected behavior?**
Should be able to generate compiled css in same directory without naming conflict causing import errors. 
- **Angular version:** 2.0.0-angular-builds (most recent build)
- **Language:** [TypeScript 2.0.2]

**Comment by mhamel06** [comment]
I was running into the same issue and noticed that it seems to be isolated to components with `encapsulation: ViewEncapsulation.None`. Ngc adds `.shim.ts` to generated css modules for components that use ViewEncapsulation. 

``` 
// With ViewEncapsulation
button.component.css
button.component.css.shim.ts
```

I agree that this is a bug, but wanted to mention this since the proposed name change solution appears to work in other cases.

**Comment by e-oz** [comment]
If somebody knows workaround - please let me know. Very awful bug.

**Comment by DzmitryShylovich** [comment]
Ok I found out how to fix this. Will send a pr soon.

**Comment by simonh1000** [comment]
Has this been corrected now - it's been sending me crazy

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/pull/12203#issuecomment-252980372

**Comment by aaronleeucla** [comment]
Discovered a workaround; replace ViewEncapsulation.None with using /deep/ { ... } in the scss files, per component styles guide in the angular2 docs. 

/deep/ basically inject styles into the header, but with emulated shadow DOM (I presume it's those [_ngcontent-abc-123] being added). The significant downside is that performance seems terrible with the emulated shadow DOM. Some of my css animation are noticeably choppier.

: /  This is indeed a very awful bug.

**Comment by vthinkxie** [comment]
I got the same error when try to use angular-cli version beta.22

**Comment by Krisa** [comment]
> Discovered a workaround; replace ViewEncapsulation.None with using /deep/ { ... } in the scss files, per component styles guide in the angular2 docs. That will inject the styles into global.

It may work by some, but in my project, I've replaced all `ViewEncapsulation.None` and still AOT throws the same error at the runtime... It looks like this error is not only caused by this (I'm using the angular-cli)

**Comment by istiti** [comment]
my project is green I just use encapsulation:ViewEncapsulation.None and my app don't work on browser with --aot option... and only browser get me this error... my console compile without error! helps!

**Comment by CarmenPopoviciu** [comment]
Had the same issue on a webpack project (not using angular-cli), with angular `v2.1.1`, @ngtools/webpack `v1.1.5` and `ViewEncapsulation.None`. Removing `ViewEncapsulation.None` did indeed work, however all the styles were messed up afterwards obviously. Today I tried upgrading angular to `v2.3.1` and @ngtools/webpack to `v1.2.3`, while keeping `ViewEncapsulation.None` and everything worked!

**Comment by fobo66** [comment]
Is it still reproducible?

**Comment by pkozlowski-opensource** [comment]
I believe that this one is now obsolete with all the ivy compiler changes. If anyone is still facing similar issues with Angular v9 + ivy please open a new issue and include a minimal reproduce scenario.

**Comment by e-oz** [comment]
@pkozlowski-opensource I can confirm this bug is not reproducible in Angular 9.
