### ISSUE TITLE
Support binding to the attribute map (similar to [class.foo])

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1140]
Some web components style or react based on the existence of an attribute, for example:

```html
<material-button disabled></material-button>
```

Make the following possible:

```html
<material-button [attributes.disabled]="disableButtonIfTrue"></material-button>
```

This should work similar to the [class.] syntax.

**Comment by pkozlowski-opensource** [comment]
@matanlurey isn't 58dd75a1c8abfa8396ead9b2b1c95dc6c6558668 implementing what you are looking for? The syntax is `[attributes.disabled]="disableButtonIfTrue"`

**Comment by pkozlowski-opensource** [comment]
Having said this it would be cool if those web components got properties as well :-)

**Comment by matanlurey** [comment]
Let me verify, I wasn't aware this already was completed.

**Comment by yjbanov** [comment]
@pkozlowski-opensource attributes are used to match CSS selectors. CSS does not support matching on properties. BTW, we should also support binding maps to attributes `[attributes]="myAttrMap"`.

**Comment by pkozlowski-opensource** [comment]
@yjbanov not sure I got your comment. We've got currently special-casing in the compiler that allows you to bind to attributes (on top of standard binding to properties) using special syntax, see: https://github.com/angular/angular/blob/3afb744e7765cfe99fbb14974827cbc5617cc84b/modules/angular2/src/core/compiler/property_setter_factory.js#L13

Not sure how CSS selectors are coming into play here...

@yjbanov could you please elaborate?

**Comment by yjbanov** [comment]
@pkozlowski-opensource Here's an example where I'm using attribute `raised` to drive CSS style:

```html
<style>
  material-button {
    ...
  }

  material-button[raised] {
    ..
  }
</style>

<material-button>Ok</material-button>
<material-button raised>Cancel</material-button>
```

Supporting _only_ properties is not sufficient to express the above.

**Comment by mhevery** [comment]
@yjbanov  this works per @pkazlowski-opensource comment. See: http://plnkr.co/edit/9tOQaAzjYqGNELA4OKt2?p=preview

I am going to close it, please reopen if you think it is not resolved.
