### ISSUE TITLE
RouterLink isn't available in child components

### ISSUE THREAD

**Issue by vaseker** [angular/angular#11404]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
routerLink directive is not available under subcomponents of modules
`<a routerLink='path/to/foo'>` => nothing
`<a [routerLink]="'path/to/foo">` => Error(`Can't bind to 'routerLink' since it isn't a known property of 'a'`)

**Expected/desired behavior**
Expecting to render proper `<a href="path/to/foo">`

**Reproduction of the problem**
Fail structure:
Root module with router => Child view component => Any other child component => `a [routerLink]`

[Plunker](http://plnkr.co/edit/bgd0OtA5CgjjAYDf3XPa?p=preview) (`app/shared/link.component.ts`)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [ all ] 
 
* **Language:** [ TypeScript 2.0.2 ]

**Comment by vaseker** [comment]
Faced this problem while migrating rc4 => rc6 and moving to `@angular/router`.
Before that it works fine [Source](https://github.com/survarium/survarium-front-ng2/tree/master/app/components.common/nickname) [Working example](https://survarium.pro/info/bans).
[Migration diff](https://github.com/survarium/survarium-front-ng2/pull/20)

**Comment by zoechi** [comment]
I'm not able to reproduce an error in the console with your Plunker.
Can you please check the repo instructions and the Plunker?

**Comment by vaseker** [comment]
Updated plunker code.

**Comment by zoechi** [comment]
You need to import `RouterModule` in modules where you want to use it http://plnkr.co/edit/RdBR8WE3SvGCLSs2Ex1z?p=preview

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi

**Comment by vaseker** [comment]
@zoechi thanks. 
It seemed to me that this is a bug.

**Comment by zoechi** [comment]
@vaseker no prob. Just try one of the support channels first next time. If no one can point out a solution there, you can still create a bug report.

**Comment by ORESoftware** [comment]
I have 3 modules in my app, all 3 import RouterModule, yet I still have this problem. What gives?

**Comment by ORESoftware** [comment]
I guess router-link became routerLink:
https://coursetro.com/posts/code/111/Using-the-Angular-5-Router-%28Tutorial

**Comment by ccjeevak** [comment]
Current behavior
routerLink directive is not available under subcomponents of modules
<a routerLink='path/to/foo'> => nothing
<a [routerLink]="'path/to/foo"> => Error(Can't bind to 'routerLink' since it isn't a known property of 'a')


Answer - you can use this 
<a routerLink="/path/to/foo"> 
<a [routerLink]="'/path/to/foo'"> or use <a [routerLink]="['/path/to/foo']">

**Comment by mikeciote** [comment]
I have exactly the same issue:

"
Current behavior
routerLink directive is not available under subcomponents of modules
=> nothing
<a [routerLink]="'path/to/foo"> => Error(Can't bind to 'routerLink' since it isn't a known property of 'a')
"

import RouterModule in parent component or app.module
```
import { Routes, RouterModule } from '@angular/router';
const routes: Routes = [

  { path: "", component: NavbarComponent, children: [

      { path: "", component: IndexComponent},
      { path: "shopdetail", component: ShopdetailComponent}
  ]
}]

imports: [
    BrowserModule,
    RouterModule.forRoot(routes),
    MaterialModule,
```
