### ISSUE TITLE
[i18n] replace default hardcoded locale to auto detect locale.

### ISSUE THREAD

**Issue by laskoviymishka** [angular/angular#11400]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

replace default hardcoded locale to auto detect locale.

**Current behavior**
`LOCALE_ID` token hardcoded to `en-US` locale.

**Expected/desired behavior**
`LOCALE_ID` detected from current browser locale.

**What is the expected behavior?**
`LOCALE_ID` setted to current browser locale.

**What is the motivation / use case for changing the behavior?**
Right now end developer should provide `LOCALE_ID` somehow to override default `en-US`, it might be easier for developer to have a correctly populated locale.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all] 
- **Language:** [all] 
- NOTE
  May require angular universal code change (providing `LOCALE_ID` prior to user agent, i.e. different locale id factory).

see b9647b734741346bf044c3c2c7c3ae3fe538fb46
CC @vicb

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/pull/11806#issuecomment-248749855 so close this one?

**Comment by meriturva** [comment]
I think it is fixed. Just see LOCALE_ID: https://github.com/angular/angular/blob/master/modules/%40angular/common/src/pipes/date_pipe.ts

**Comment by laskoviymishka** [comment]
No,  it's not. This feature about injection auto detection locale instead of 'EN_US'

**Comment by meriturva** [comment]
@laskoviymishka you are right! sorry.
Anyway it is quite easy to get locale from browser, set locale and then bootstrap app.

**Comment by laskoviymishka** [comment]
@meriturva well from first sight yes, but you need to keep in mind that ng2 app could be executed from server side (which is not so straight forward) and this locale detection mechanism should be browser agnostic and works even in Safari (worst browser so far). And one more thing - locale id format is not exact same as locale that could be grabbed standard vanilla js ways. Like `navigator.language` will return `ru` locale instead of `ru-BY` as i except on my local machine.

**Comment by intellix** [comment]
Another thing to note. How will it handle locales that aren't supported by your application?
We have 5 locales currently: `en`, `de`, `fi`, `sv`, `nb` and if they come from somewhere like Japan, we'd like to fallback to `en`

**Comment by ocombe** [comment]
I don't see us doing that: angular doesn't depend on the platform, it can be executed in browsers/server/web workers/electron/nativescript/... and many of those platforms have no mechanism to define the locale.
And it's easy to find a method that does that. Here is one if you need it: https://github.com/ngx-translate/core/blob/master/src/translate.service.ts#L486-L503

**Comment by ocombe** [comment]
Closing this as it is no longer possible: we provide locale data for en-US by default and this cannot be changed at runtime since it is part of the common library.

**Comment by lazarljubenovic** [comment]
I'm not sure I understand the point of "locale" now -- isn't the whole idea for this to be done runtime, so the user is presented with a format that she's used to? If we choose a locale at build-time, it's not much of a locale.

The way I imagine it working is:

1. We register which locales we want to bundle
2. During bootstrap, Angular goes through `navigator.languages` and looks for the first match
3. If none is found, use the provided `LOCALE_ID` (which defaults to `en-US`).

> Also for AOT we need the locale to be defined at build time, which would not be the case with browser detection.

I'm not sure I get this. The functions for (for example) date pipe are used at runtime. Why does AOT need it? Why can Angular not determine the locale runtime?

> many of those platforms have no mechanism to define the locale.

That's why `LOCALE_ID` should act as a fallback if the platform cannot tell Angular the locale to be used.

**Comment by mlc-mlapis** [comment]
... as related to AOT ... it needs to know which locales should be supported = available for run-time later + which one should be default one if none is specified in run-time.

**Comment by ocombe** [comment]
You can choose which locale you want to use at runtime (using a function for your provider), but you will need to bundle multiple locale data in your application. Angular only provides "en-US" data, if you want something else to be available then you will need to import it as well. If you need 10 locales then you'll have 10 locales bundled in your app even if you only use 1.
Each locale is around 1kb minified, that's not a lot, but it's up to you to decide if you need it.

And Angular will never decide for you which method you want to use to determine the locale. It can be the browser's language, but you could also use cookies, geo ip localization, url parameters, ...

**Comment by pwhissell** [comment]
I completely agree with the idea that Angular should never force the implementation in choosing how the application's language is defined. That being said, the awesomeness behind Angular lies behind the fact that the framework facilitates so many aspects of development and it would be that much more awesome if Angular would facilitate the lazy loading of specific locales.

To be honest, I haven't dug into the implementation of Angular's I18n feature. Howerever, I have read the documentation. First off, I find the documentation found at https://angular.io/guide/i18n a little awkward to read compared to the fluidity found in every other angular.io sections. However I believe the problem discussed in this thread is easy to see in this section: https://angular.io/guide/i18n#merge-the-completed-translation-file-into-the-app. If I understand correctly. using the aot compiler requires me to define (ahead of time) the language used to serve my angular app like so:

> ng serve --aot --i18nFile=src/locale/messages.fr.xlf --i18nFormat=xlf --locale=fr

So if I translate my app in 10 different languages, I would have to serve my app that many times thus using 10 times the resources on my physical server?

Did I understand correctly if you propose to implement some sort of locale routing during the bootstrapping of everyone of my angular apps? It could look something like so:

````
const translations = routeLocale();
function routeLocale(){
    currentLocale = (Navigator.language || Navigator.userLanguage || 'en_US'); // or whichever logic i see fit
    return 'raw-loader!./locale/messages.' + currentLocale + '.xlf';
}
platformBrowserDynamic().bootstrapModule(AppModule, {
  providers: [
    {provide: TRANSLATIONS, useValue: translations},
    {provide: TRANSLATIONS_FORMAT, useValue: 'xlf'}
  ]
});
````

it would have been awesome if a developper could have simply configured the aot compiler to use angular-offered locale-routers and the configurationg could look something like:

> ng serve --aot --i18nRouter=httpHeaderLocaleRouter --i18nFormat=xlf

**Comment by ocombe** [comment]
This is what we are aiming for, it requires major changes that's why it's taking so long.
As for the language detection, we will provide methods in the different platforms for that, you can decide to use them or not. It's on the roadmap.

**Comment by pwhissell** [comment]
You guys are awesome, I love you.
