### ISSUE TITLE
AOT input selector compile error

### ISSUE THREAD

**Issue by Prepd-Root** [angular/angular#11407]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
AOT compilation error for component selector input in the template( check plunkr example ).

Error encountered : Void elements do not have end tags "input"

NOTE : this works if we remove 'input' from the selector of the component( check plunkr example )

**Expected/desired behavior**
Compilation without error. 

**Reproduction of the problem**
[Plunkr Example](https://plnkr.co/edit/2MXAz1SteIdbtqfy6wmu)

**Please tell us about your environment:**
Windows 

* **Angular version:** 2.0.0-rc.X
 2.0.0-rc6

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
TypeScript 2.0.2

**Comment by vicb** [comment]
> Void elements do not have end tags "input"

means that you have an `</input>` in your code.

Closing as ccan not reproduce

**Comment by Prepd-Root** [comment]
Hey @vicb 

There is no </input> in the code. I made a repo with an example showing the problem. [ since you can't run ngc on plunkr ]

[AOT problem example](https://github.com/Prepd-Root/aot-angular-compile-error-example)
To check the issue, you need to run ,like in the readme : npm i , npm run ngc

PS : i've also added in there the issue you closed [11406](https://github.com/angular/angular/issues/11406) since it is NOT related to minifying or anything like that.

Thanks in advance for taking a look.

**Comment by qdouble** [comment]
Using form.controls is not static analysis safe, the proper method is form.get()... not sure if the selector is valid, but I will track, adding it to a list in the to repo in my profile, but hopefully Angular will document this in the future.

**Comment by vicb** [comment]
@Prepd-Root thanks for the repro ir helped. See the linked PR.
