### ISSUE TITLE
Ability to set output location for ng-xi18n

### ISSUE THREAD

**Issue by christiandreher** [angular/angular#11416]
**I'm submitting a feature request**

As suggested by @vicb in https://github.com/angular/angular/issues/9104#issuecomment-245338445, I hereby want to request a feature to be able to set the output location of `ng-xi18n` by a command line parameter. The **current behavior** does not allow this, so the **desired behavior** for me would be to be able to set it with a `--out` parameter. You would then be able to create a `translations/` folder where all files would be located. Otherwise, the `src/` directory would eventually be too overcrowded with `x` translation files.

**What is the motivation / use case for changing the behavior?**
- Costumizeability
- One place for translator teams to work in (who are potentially unfamiliar with developing)
- Otherwise too overcrowded `src/` folder for large apps or...
- ... inconvenient relocation of `.xlf` files after extraction

**Comment by ocombe** [comment]
You can use the genDir option in tsconfig.json (from the `ngc` compiler), but a separate option would be nice, also it would be better if it could be defined both in tsconfig.json AND as a cli parameter (genDir only works in tsconfig.json right now)

**Comment by christiandreher** [comment]
I can't change the `tsconfig.json` as I am an `angular-cli` user, which would probably break its functionality

**Comment by ocombe** [comment]
It's only ngc options, I think that you can change it if you don't use ngc, just add this at the end
```
"angularCompilerOptions": {
  "genDir": "./src/i18n"
}
```

**Comment by christiandreher** [comment]
Oh now I understand what you meant! Thats helpful, thank you for that tip :)

**Comment by vicb** [comment]
thanks @ocombe

**Comment by mprobst** [comment]
@vib It'd be helpful for my use case, too, to be able to specify the output file (not just the directory).
