### ISSUE TITLE
Migrating from RC5 to RC6 issue with no exported member

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#11417]
I have angular 2 code in RC 5 version, I change package.json and updated to RC 6 and after I do that I am getting below errrors:

![image](https://cloud.githubusercontent.com/assets/12258728/18326503/06d5234e-7514-11e6-8457-74a86648a155.png)

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by omeryounus** [comment]
@vijender1256 
Change to Forms and Http to FormsModule and HttpModule that will fix the import issue.
