### ISSUE TITLE
Errors after migration from RC4 to RC6 - length of null in component

### ISSUE THREAD

**Issue by bruno-serfe** [angular/angular#11414]
* **I'm submitting a ...**
[x] issue report (I don't know if this is a bug, I'm not sure)

* **What is the current behavior?**
With my current created components using previous version of angular2 webpack with angualr2 rc.4
This issue wasn't arise:

![error_angualr2_rc6](https://cloud.githubusercontent.com/assets/11821195/18315059/f1d4be5a-74eb-11e6-9ddf-6afa5b890791.png)

I'm receiving an error in the flatten function of this file: flatten (http://192.168.33.10:3000/vendor.bundle.js:8198:33)

Removing the html from the sidebar.component.html the component error disappear but the vendor.bundle.js error ORIGINAL EXCEPTION: Cannot read property 'length' of 'null' is still there.

Here is the function that throw the error on exaclty "a[i].length" part.

function flatten(a) {
	    var target = [];
	    for (var i = 0; i < a.length; ++i) {
	        for (var j = 0; j < a[i].length; ++j) {
	            target.push(a[i][j]);
	        }
	    }
	    return target;
	}

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.6
- Browser: [ Chrome 49 | Firefox 48 ]
- OS: Ubuntu 14.04

**Comment by vicb** [comment]
This is probably a bug in your component and anyway there is nothing we can do w/o a repro
