### ISSUE TITLE
i18nSelect could fallback to given value

### ISSUE THREAD

**Issue by mvar** [angular/angular#11413]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
// emptyMap = {};
{{'foo' | i18nSelect:emptyMap}}
```

This prints nothing (empty string).

**Expected/desired behavior**

It would be nice to see `foo` instead. At least in my case it's better to show raw value than nothing.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all] 
 
* **Language:** [TypeScript]

**Comment by vicb** [comment]
`foo` would be a selector here, I don't see a reason why it should be used as the message value.

```
 *  <div>
 *    {{ gender | i18nSelect: inviteMap }}
 *  </div>
 *
 *  class MyApp {
 *    gender: string = 'male';
 *    inviteMap: any = {
 *      'male': 'Invite him.',
 *      'female': 'Invite her.',
 *      'other': 'Invite them.'
 *    }
 *    ...
 *  }
```
