### ISSUE TITLE
AoT compiler unable to parse valid typescript: "import Module" instead of "import {Module}"

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#11412]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

While doing Ahead-of-Time compilation, the compiler has no problem resolving this import statement:
```
import {SharedModule} from '../shared/shared.module'
```

However, if the brackets are missing, it will crash:
```
import SharedModule from '../shared/shared.module'
```
This generates the following compilation error:
```
can't resolve module ../shared/shared.module from C:/path/to/report.module.ts
Error: can't find symbol undefined exported from module C:/path/to/shared.module.ts, resolving symbol ReportModule in C:/path/to/report.module.ts, resolving symbol ReportModule in C:/path/to/report.module.ts
    at simplifyInContext (C:\path\to\@angular\compiler-cli\src\static_reflector.js:473:23)
    at StaticReflector.simplify (C:\path\to\@angular\compiler-cli\src\static_reflector.js:476:22)
    ...
Compilation failed
```

**Expected/desired behavior**

Since the Typescript compiler itself has no trouble resolving the no-bracket syntax, and since Just-in-Time compilation works well without brackets, I expected the AoT compiler to work.

**Reproduction of the problem**

Use an import statement as above and try to AoT compile

**What is the motivation / use case for changing the behavior?**

`ngc` should not throw errors on valid Typescript syntax

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by qdouble** [comment]
AOT currently doesn't work with default exports. Not sure if that's something that can be fixed or a static analysis issue.

**Comment by RoxKilly** [comment]
@qdouble I don't understand why you mentioned that. Is this issue related to default exports?

**Comment by qdouble** [comment]
doing `import SharedModule from '../shared/shared.module'` is not valid typescript unless SharedModule is a default export.

**Comment by RoxKilly** [comment]
@qdouble Didn't know. Thank you.
