### ISSUE TITLE
[Compiler] need a benchmark to detect perf/size regression

### ISSUE THREAD

**Issue by vicb** [angular/angular#11421]
As reported in #11371 we have introduced a major perf regression in RC6.

It could have been detected with a simple compiler test.

Step 1: create s simple compiler test (ie `ngc`ing periscope), report time and output size

Step 2: execute the script as parts of the `-build` repo post update hooks, alert when a regression is detected

/cc @tbosch

**Comment by tbosch** [comment]
Closes in favor of #11651 as a more generic issue.
