### ISSUE TITLE
Improve how AoT compiler casts to boolean

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#11425]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

During `ngc` compilation, I get several errors of the type:
```
Type 'IDrillActive' is not assignable to type 'boolean'.
```

As the compiler parses auto-generated code:
```
const currVal_0:boolean = (!this.context.store.appState.loading && this.context.drill);
```

These errors from `.ngfactory.ts` files clutter the IDE and make it tougher to spot errors in my own code.

**Expected behavior**

I think it would be better to properly cast expressions to booleans.  For instance the line above could be re-factored to:
```
const currVal_0:boolean = !!(!this.context.store.appState.loading && this.context.drill);
```

**What is the motivation / use case for changing the behavior?**

To reduce compiler errors generated by `.ngfactory.ts` files

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 2.0.2]
 
* **Node (for AoT issues):** `node --version` =   4.5.0

**Comment by vicb** [comment]
Could you please try to come up with a small repro case (plunker/GH repo).

**Comment by vicb** [comment]
Probably this should be a warning and you should fix your code ?

**Comment by RoxKilly** [comment]
@vicb  I'll look into it. My own code doesn't throw any error during transpilation (for Just-in-Time compilation) but maybe I just missed it

**Comment by RoxKilly** [comment]
@vicb You were right. the reason no error showed up until I tried to switch to AoT is that the expressions causing these errors are from `*ngIf` statements in my html templates, so the typescript compiler `tsc` didn't scan them at all.  Since `ngc` turned the html template into a `.ts` class, the compiler became aware of these expressions.

**Comment by vvakame** [comment]
Hi, I'm getting same issue.
I want to get useful error message or generate more smart code by ngc.

My issue is solved by above change.
```
- <a md-list-item *ngIf="!loggedIn && loginURL" href="{{loginURL}}">
+ <a md-list-item *ngIf="!loggedIn && !!loginURL" href="{{loginURL}}">
```

old pattern generated above code.
`const currVal_9:boolean = (!this.context.loggedIn && this.context.loginURL);`
from
```
export class AppComponent implements OnInit {
...
    loggedIn: boolean;
    loginURL: string;
...
}
```

My code base is here https://github.com/vvakame/ucon-todo/tree/550a71b0b9794a0a4784f18e3bce1d271113a096/front

@RoxKilly @vicb please reopen this issue. 😉

**Comment by RoxKilly** [comment]
@vvakame  the problem is with our code, not Angular.
```
!loggedIn && loginURL
```
This resolves to a string because the 2nd operand is a string.  If you don't want to see these errors, you need to adjust your conditional statements to return booleans, not just truthey values.  For instance you could do:
```
loginURL && !loggedIn
```
Typescript resolves this to a boolean (the type of the last operand) so you won't see the error.

Alternatively, you could force your non-booleans into booleans with the `!!` prefix:
```
!loggedIn && !!loginURL
```

**Comment by mdudek** [comment]
@RoxKilly none of your suggestion works in ng4 final. It throws "Type '{type}' is not assignable to type 'boolean'" in both cases.
