### ISSUE TITLE
The directives property is not present in the @Component (RC6)

### ISSUE THREAD

**Issue by StefH** [angular/angular#11428]
**I'm submitting a**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

The **directives** property is not present in the @Component (RC6) ?
This code
```ts
@Component({
    selector: 'my-app',
    directives: [FriendComponent],
    styles: [`
        h1 {
            color:#545454;
    background:#02A8F4;
    padding:15px;
    box-shadow:2px 2px 2px 0 rgba(0, 0, 0, 0.3);
        }
    `]
    template: `
    <div>
        <h1>Hello from the {{ componentName }}.</h1>
        <my-friends></my-friends>
    </div>
    `
})
```
Gives compiler error message:
```
C:\Github\_forks\angular2-webpack-starter\src\app\x\x.component.ts:11:5
    Argument of type '{ template: any; directives: (typeof FriendComponent' is not assignable to parameter of type 'ComponentMetadataType'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'ComponentMetadataType'.
[default] Checking finished with 1 errors
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [Chrome] 
 
* **Language:** [TypeScript]

**Comment by dcg** [comment]
>Changelog.md:  core: previously deprecated @Component.directives and @Component.pipes support was removed.

directives got deprecated in RC5 in favour of the new @NgModule

**Comment by StefH** [comment]
@dcg Can you please elaborate on that or post a link how the old code should be rewritten to new code ?

**Comment by pkozlowski-opensource** [comment]
@StefH https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html

**Comment by bhawin-bigstep** [comment]
Hi @pkozlowski-opensource  The above link is empty , Can You Please post something convincing

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/guide/ngmodule.html

**Comment by sjatkins** [comment]
So if I have a directive only useful in the template of one other then I need to push it up to the nearest module although most things in the module don't care about it?  I always seek the least files and/or typing possible.  It would break that goal even more to add a module for said using component.
