### ISSUE TITLE
How about change from `ViewEncasulation.Native` to `ViewEncasulation.Emulated` implicitly at FF, Safari?

### ISSUE THREAD

**Issue by sculove** [angular/angular#11429]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I use ViewEncapsulation.Native on Firefox or Safari. [demo](https://run.plnkr.co/plunks/zp0PXxJHiUkFIsC09ZPi/)
I face a problem following message
```
EXCEPTION: Error in ./App class App - inline template:5:6 caused by: el.createShadowRoot is not a function core.umd.js:5995:1
ErrorHandler</ErrorHandler.prototype.handleError() core.umd.js:5995
_callAndReportToErrorHandler/<() core.umd.js:9394
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke() zone.js:323
NgZoneImpl/this.inner<.onInvoke() core.umd.js:8772
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke() zone.js:322
Zone</Zone</Zone.prototype.run() zone.js:216
scheduleResolveOrReject/<() zone.js:571
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask() zone.js:356
NgZoneImpl/this.inner<.onInvokeTask() core.umd.js:8763
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask() zone.js:355
Zone</Zone</Zone.prototype.runTask() zone.js:256
drainMicroTaskQueue() zone.js:474
ZoneTask/this.invoke() zone.js:426
```

I found out Firefox and Safari don't support ShadowDOM.

**Expected behavior**
No exception.

**What is the motivation / use case for changing the behavior?**
I want to use web components on Angular2
I wish Angular2 covers this feature.
If a browser doesn't support ShadowDOM, Angular2 changes from `ViewEncasulation.Native` to `ViewEncasulation.Emulated` implicitly.

**Please tell us about your environment:**
OSX El Capitan

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Firefox XX | Safari XX] 
 
* **Language:** [TypeScript 2.0]
 
* **Node (for AoT issues):** `node --version` =   6.5.0

**Comment by vicb** [comment]
The "Emulated" mode emulates style scoping but yet is not perfect.

Then there could be subtle differences and nobody would want the mode to be changed by the framework.

**Comment by sculove** [comment]
@vicb ok. I got it. I will try to a slightly different approach.
Thanks
