### ISSUE TITLE
Template Parser: Not a known element is being thrown on data, menuitem, summary and time elements

### ISSUE THREAD

**Issue by jschwarty** [angular/angular#11426]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using any of the following native HTML elements in a component template:
```
data
menuitem
summary
time
```
causes the template parser to throw an error:
```
Promise rejection: Template parse errors:
'data' is not a known element:

Promise rejection: Template parse errors:
'menuitem' is not a known element:

Promise rejection: Template parse errors:
'summary' is not a known element:

Promise rejection: Template parse errors:
'time' is not a known element:
```

It looks like the array constant for `SCHEMA` in the [dom_element_schema_registry.ts](https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/schema/dom_element_schema_registry.ts#L224) has a bunch of `:svg:` entries followed by the ones listed above (data, menuitem, summary and time). The `video` element entry that comes before that set of `:svg:` ones works without an error, and the final 4 in the array throw an error.

**Expected behavior**

These should correctly pass schema validation and not throw an error.

**Reproduction of the problem**

See this [plunker](http://plnkr.co/edit/Qh4Fgd?p=preview) that has the following HTML elements in the `app/app.component.html` template:
http://plnkr.co/edit/Qh4Fgd?p=preview
```html
<video></video>
<data></data>
<menuitem></menuitem>
<summary></summary>
<time></time>
```

**What is the motivation / use case for changing the behavior?**

To be able to use these native HTML elements :)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** all
 
* **Language:** all
 
* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
fixed, coming in the next release

**Comment by jschwarty** [comment]
Sweet!
