### ISSUE TITLE
Router.resetConfig doesn't make child routes navigable

### ISSUE THREAD

**Issue by Jonymul** [angular/angular#11437]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Calling `router.resetConfig(newConfig)` makes new routes available **if** they are top-level routes. If the new routes are children of an existing route, they are not navigable, despite being visible in `router.config`.

**Expected behavior**

Calling `router.resetConfig(newConfig)` should make all new routes available, including children of an existing route.

**Reproduction of the problem**

From within a component, call `this.router.resetConfig()` with an updated route config -- the new routes should be children of an existing route. E.g:
```
let routerConfig = this.router['config'];
routerConfig[0]._loadedConfig.routes[0].children.push({
  path: `lazy-loaded-module-1`,
  loadChildren: `/lazy-loaded-module-1/app.module.js#ModuleOne`
});
this.router.resetConfig(routerConfig);
```
(I understand that the above is not strictly standard but conceptually, should still work.)

**What is the motivation / use case for changing the behavior?**

My Application needs to download additional modules after logging in. These should all be registered as child routes of an '/app' route. 

* `/login`
* `/app`
* `/app/home`
* `/app/lazy-loaded-module-1 // Added at runtime`
* `/app/lazy-loaded-module-2 // Added at runtime`

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:**  all  (Tested in Chrome 52)
 
* **Language:** TypeScript 1.8.9

**Comment by brandonroberts** [comment]
@Jonymul you don't modify the `_loadedConfig` to add additional routes. You modify the route map and if the router needs to lazy load the module it will update that property.

Here is an example: http://plnkr.co/edit/FDaiDvklexT68BTaNqvE?p=preview

**Comment by brandonroberts** [comment]
Are you modifying the route config of an already lazy loaded module? Here is a working example

http://plnkr.co/edit/FDaiDvklexT68BTaNqvE?p=preview

**Comment by Jonymul** [comment]
Thanks for the reply, @brandonroberts. 

Yep, my project was appending to the route config of an already lazy-loaded module. I've modified your Plunkr (see below) to match my scenario and it seems to be working correctly 😅🤔. 
Root => Lazy loaded portal => Lazy loaded apps
Given this was user-error on my part (sorry about that), I'll close the issue. 

http://plnkr.co/edit/gn32VLexZYDWDkC8hh6c?p=preview

I appreciate this is somewhat non-standard requirement of the router (we have to access and mutate the private `router.config` property), but a public way to get `router.config` might be useful? 

Thanks! 😊

**Comment by brandonroberts** [comment]
@Jonymul as of RC6 the `router.config` property is no longer private, so you don't have to access it as `router['config']` anymore.

**Comment by Jonymul** [comment]
@brandonroberts Great stuff. I'm upgrading to RC6 later this week so that's good news. :+1:

**Comment by brandonroberts** [comment]
@Jonymul there is also a slightly cleaner way to modify the routeConfig inside a lazy loaded module. Each component is provided its route config with the `ActivatedRoute.routeConfig` property. You can modify that instead of relying on the `_loadedConfig`

http://plnkr.co/edit/fBqrEpqafiVSB2Vvapzb?p=preview

**Comment by m-sawicki** [comment]
@brandonroberts I have a question about your solution. It seems to work well when you load lazy routes on demand, but I want them loaded automatically. I can achieve that simply by adding (in app.ts):
```
ngOnInit(){
    this.addRoutes();
}
```
This works, but breaks when I refresh lazy loaded page. Is there another way to provide refresh functionality on lazy loaded pages, or am I doing something wrong?

**Comment by brandonroberts** [comment]
@m-sawicki Your other option would be to put a guard on the route that loads the routes before the navigation continues. You'd only need to do the first time the route is loaded though.

**Comment by Jonymul** [comment]
A route guard is the solution I used in my project. Works well. 👍
(It makes a synchronous API call first, rather that add the route on init).

**Comment by m-sawicki** [comment]
Thank you both for your help. I think I'm almost there with guards solution, but I still need one more step. This is my guard:
``` javascript
 canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
        if (!this.isLoaded) {
            this.http.get('/api/Home')
                .subscribe(menuGroups => {
                    //use json data to push more routes to appRoutes 
                    //(each has a path to respective module as loadChildren)
                    
                    this.isLoaded = true;
                    this.router.resetConfig(appRoutes); 
                    //after reset the route is added to config
                });            
        }
        return true;
    }
```
I attached it to my main component, which works great when I navigate through it. Regardless, I still need a way to activate this guard when I'm navigating directly to my lazy loaded component. I can use a wildcard route, but then it will not navigate to my newly added lazy components. Do you have any suggestions?

**Comment by Jonymul** [comment]
@m-sawicki  `canActivate()` doesn't have to synchronously return a boolean. Instead, you can return a Promise or an Observable. Below, the Promise always resolves with `true`, but only after the routes have been added. The HTTP request should probably handle the error case, but I'll leave that to you. 

Hope this helps.

``` typescript
public canActivate (): Promise<boolean> {
  return new Promise(resolve => {
    if (this.isLoaded) {
      // The routes have already been added. Resolve and return to exit out of the function
      resolve(true);
      return;
    }

    this.http.get('/api/home')
      .subscribe(menuGroups => {
        // Reset the config using a newly created route config
        this.router.resetConfig(this.constructAppRoutes(menuGroups));

        // Set isLoaded to true and resolve
        this.isLoaded = true;
        resolve(true);
      });
  });
}

private constructAppRoutes (menuGroups: any): Routes {
  // ...
}
```

**Comment by m-sawicki** [comment]
@Jonymul Your example does indeed help, it looks better than mine. I had an alternative solution with Promises as well, and while it is better in terms of design, it does not solve my core problem. Perhaps I should have worded myself better, sorry for that.
My problem comes from the fact that I need to activate my guard somehow. When I navigate directly to my lazy loaded component (e.g. after refresh) router looks through my default paths to match and only **after** it matches anything, it tries to activate component and loads my lazy routes. Since none of my default routes matches the lazy one, it breaks and never loads. 
I can avoid that by adding wildcard route ('**'), which will match and lazy load my routes. The problem is that it will continue to navigate that initial wildcard route, even though my lazy routes are already loaded. Wildcard route needs to have something to navigate to, so I can't have it as an empty placeholder just to use a guard.
Funny thing is that this only became a problem for me when I upgraded to the new router from the deprecated one. I used to load those routes as a part of rendering my menu with the old router and it worked just liked that, I didn't even have to think about that ;).

**Comment by brandonroberts** [comment]
@m-sawicki if you could reproduce what you're trying to achieve in a plunker, it would be more helpful. If setup correctly, your guard will be handled by the router if you provide it an Observable<boolean> or a Promise<boolean> and will wait until that is resolved before continuing.

**Comment by mdzzaman** [comment]
How I can push new Child route for current route from route_resolve

**Comment by Jonymul** [comment]
@m-sawicki: Ah, I think I know the problem that you've encountered. The route guard needs to be attached to a route, but if the route doesn't exist yet, it's impossible to load. In this case, you must have a route to handle the request -- indeed, this may be a wildcard (`**`) route. 

To adjust the earlier example, after you set `isLoaded` to `true`, instead of calling `resolve(true)`, you'll actually call `resolve(false)`. This will stop the wildcard route from loading. Instead, you'll retry the original request. 

```typescript
// Now on the wildcard route (**)
public canActivate (_, state: RouterStateSnapshot): Promise<boolean> {
  return new Promise(resolve => {
    if (this.isLoaded) {
      // The routes have already been added. If we've hit this again, the route definitely doesn't exist.
      resolve(true);
      return;
    }

    this.http.get('/api/home')
      .subscribe(menuGroups => {
        this.router.resetConfig(this.constructAppRoutes(menuGroups));

        // Set isLoaded to true, stop the original navigation request
        this.isLoaded = true;
        resolve(false);

        // Retry the original navigation request
        this.router.navigateByUrl(state.url);
      });
  });
}
```

**Comment by mdzzaman** [comment]
Thanks for your reply, For RouterModule.forRoot, I use "loadChildren" for path home, when I want to go home path then I want to add some "children" for this path.

**Comment by m-sawicki** [comment]
@Jonymul Sorry for the delayed response. I tried returning false previosuly and it stopped routing alltogether - I haven't thought about manually resuming routing. Simple and works great! Thank you very much for your help.

**Comment by Jonymul** [comment]
@m-sawicki No worries at all. I ran into exactly the same scenario as yourself -- glad it works for you too. 👍

It looks like the router will always try to resolve the entire route. If a guard stops navigation to a child route, the parent routes will also not render. This matches your observation that "It stopped routing altogether".

**Comment by kevindqc** [comment]
I used @Jonymul 's code but I had a small problem - my browser history had a useless entry with the URL of the root of my app. That means go to the actual previous page I had to click Back twice.

I used `this.router.navigateByUrl(state.url, { replaceUrl: true });` instead, where `{ replaceUrl: true }` is the fix for this.
