### ISSUE TITLE
Feature Request [i18n]: Support providing TRANSLATIONS at NgModule level

### ISSUE THREAD

**Issue by paumayr** [angular/angular#11431]
**Current behavior**
Currently translations can only be provided at bootstrap using TRANSLATIONS. This makes it difficult for feature / component modules to ship translations xlf files along with the npm module: All xlf files from all feature modules (for a specific locale) will have to be merged before bootstrap into a single value for TRANSLATIONS.

**Expected behavior**
Ideally we could provide a TRANSLATIONS value for every NgModule. This would have to be per locale, possibly as an Url pattern, something like 
`
@NgModule({
  // ... omitted 
  translationUrl: './messages.{locale}.xlf',
  // ... omitted 
})
export class MyFeatureComponent { }
`
but I'm not familiar enough with the compiler to understand all implications of this.

**Reproduction of the problem**
Package an component with localization and corresponding messages.xlf into an npm module.

**What is the motivation / use case for changing the behavior?**
Larger codebases like to reuse common, localized components in multiple applications to provide base components with a common style, etc. Having to merge the localization data from all modules in a pre-build step is possible, but figuring out which components are actually used and resolving the corresponding paths is tricky.

**Please tell us about your environment:**
Win10, corporate (with proxy..)
- **Angular version:** ^2.0.0-rc.6
- **Browser:** [all] 
- **Language:** [all]

**Comment by paumayr** [comment]
Related, but not as important would be the ability to run ng-xi18n per NgModule. For us this is not really a problem as we have sample / test applications for developing components which we can use to extract the i18n localizations.

**Comment by ocombe** [comment]
This is something that we are looking into adding when we fix #11405 (using translations in code). It might not be exactly like you requested though

**Comment by ChBernat** [comment]
@ocombe This was fixed quite some time ago. 

Is this feature going any further?

**Comment by ocombe** [comment]
No I don't think so, I'm not working for Google anymore though, so I'm not sure

**Comment by ChBernat** [comment]
Damn, that's a shame.

@petebacondarwin Any news?

**Comment by alxhub** [comment]
I'm going to go ahead and close this issue, as with the introduction of `standalone`, NgModules don't make much sense anymore as a reasonable subdivision of an Angular application for the purposes of i18n.
