### ISSUE TITLE
Setting a default value to an attribute or property is painful

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1143]
Say I have a component that should be focus-able, like a radio-button. Since it's not a real input, we've got to set the `tabindex` manually. The default should be `0` (in the normal document flow). However, if the user set a tabindex, we don't want to overwrite it. Let's take a look at the amount of code **just** this takes:

```js
@Component({
  selector: 'md-radio',
  lifecycle: [onChange],
  bind: {tabindex: 'tabindex'}
})
@Template(...)
class MdRadio {
  tabindex: number;
  tabindexSetter: Function;

  constructor(@Attribute('tabindex') staticTabindex, @PropertySetter('tabindex') tabindexSetter) {
    this.tabindexSetter = tabindexSetter;
    if (!staticTabIndex) {
      tabindexSetter('0');
    }
  }

  onChange() {
    if (!this.tabindex) {
      tabindexSetter('0');
    }
  }  
}
```

We have to check and set the tabindex in two places because `onChange` isn't called for instances without bindings and because bindings aren't resolved yet in the constructor. Doing this requires two class properties, a binding, two injections, and one method.

It's also not clear how one could encapsulate this behavior and compose it into multiple Components.

**Comment by ThomasBurleson** [comment]
Is this not possible:

```js
constructor(@Attribute('tabindex') staticTabindex, @PropertySetter('tabindex') tabindexSetter) {
    this.tabindexSetter = tabindexSetter;
    this.tabIndex = staticTabindex;

    onChange();
  }

  onChange() {
    if (!this.tabindex) {
      tabindexSetter('0');
    }
  }  
```

**Comment by ThomasBurleson** [comment]
Essentially what you want is to prepare a default value for a property and use that if **undefined || null**?

@Template(...)
class MdRadio {
  @defaultValue('0')  // fires check after construction and before onChange()
  tabindex: number;
  tabindexSetter: Function;

  constructor(@Attribute('tabindex') staticTabindex, @PropertySetter('tabindex') tabindexSetter) {
    this.tabindex = staticTabindex;
    this.tabindexSetter = tabindexSetter;
  }

}

**Comment by ThomasBurleson** [comment]
With the use of of `@DefaultValue('0'), it would also be great if a **tail-hook** intercepter is also prepared for the `tabIndex` setter function. If the value is set to `undefined || null`, then the default value would auto override again.

**Comment by johnlindquist** [comment]
@jelbourn @ThomasBurleson What's the es5 story for this?
