### ISSUE TITLE
Change detection does not update component’s host bindings

### ISSUE THREAD

**Issue by poke** [angular/angular#11442]
When using [host property bindings](https://angular.io/docs/ts/latest/api/core/index/DirectiveMetadata-class.html#!#host-property-bindings) for a component, it seems that explicitly triggering the change detection does not update those bindings.

In order to see that effect, consider the following component:

```typescript
@Component({
  selector: 'my-component',
  host: {
    '[class.foo]': 'value == "foo"',
    '[class.bar]': 'value == "bar"',
  },
  styles: [`
    :host.foo { background: #F99; }
    :host.bar { background: #99F; }
  `],
  template: 'Value: {{value}}'
})
class MyComponent {
  value: string;
  
  constructor(ref: ChangeDetectorRef) {
    (<any>window).test = (v: string) => {
      this.value = v;
      ref.detectChanges();
    };
  }
}
```

As you can see, there are two host property bindings, each on the `value` member of the component. In addition, the same `value` member is also rendered inside the component’s template.

In the constructor, a function is defined on `window` as a way to set the value from outside of a zone (so we don’t get the side effects of a zone triggering change detection here). Instead, we explicitly run the change detection using `detectChanges()`.

Now, when changing the value using that function on `window`, the explicit change detection trigger forces the component to update, so the new value *is* being displayed properly. However, the change is not carried over to the host property bindings. When setting the values to `'foo'` or `'bar'`, then the host’s class name is *not* being updated.

So the triggering the change detector of the component does affect the component’s content, but not the component itself and its host element. This appears to be an inconsistency in the change detector.

---

You can see above example in [this plunker](http://plnkr.co/edit/qfKI3BaSa2TSfoNUbPTC?p=preview). In order to be able to call the `test` function on `window`, you need to change the active frame in the browser console to the preview frame (in Chrome, there is a drop down above the console window, next to the filter buttons, select “plunkerPreviewTarget” there); in Firefox, you can use the iframe selector toolbar button that can be enabled in the dev tools, select the iframe on the run.plnkr.co domain there).

Then, calling `test('foo')` will update the displayed text, but will not update the background color from the host binding. Clicking the button—which triggers a zone event and as such the full change detection—will update the host binding.

**Comment by vicb** [comment]
`ref.detectChanges();` runs the CD for this component downwards. The observed behavior is expected.

One way to achieve what you want is:
```

import {Component, NgModule, ChangeDetectorRef, NgZone} from '@angular/core'

// ...

@Component(...)
class MyComponent {
  value: string;
  
  constructor(ref: ChangeDetectorRef, zone: NgZone) {
    (<any>window).test = (v: string) => {
      zone.run(() => this.value = v);
    };
  }
}
```

**Comment by swpalmer** [comment]
> `ref.detectChanges();` runs the CD for this component downwards.

How is the binding declared in `@Component` NOT part of "this component" ???

**Comment by simeyla** [comment]
@swpalmer Apparently not. I think some improved functionality with this is desperately needed. The number one reason I use HostBinding is to avoid adding another DIV, but it adds tonnes of headaches in super confusing ways. One problem is that the 'parent' may be declared in a different module (often probably is) and this complicates things.

From miscellaneous posts I've seen I believe some changes may be coming to this in future - but they're not going to happen until the IVY renderer where I'm hoping they'll be addressed conclusively.

I'm really hoping that there will be a way 1) to have the component 'own' the properties (with some kind of isolated shadow dom type behavior) and 2) there will be a way to link an observable to a hostbinding in a simple way.
