### ISSUE TITLE
(AOT bug) Template containing a lot of form controls and compiled with ngc causes webpack builds that are either slow or hang forever

### ISSUE THREAD

**Issue by qdouble** [angular/angular#11458]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

If you have a lot of form controls in template and compile with AOT, webpack build will hang for a long time or seemingly never complete.

In the below demo of the bug, I have 20 form controls on a template, it will take about 2 minutes to build after compile. If you delete 5 of them, it only take 12 seconds to compile. 
If you have 30 controls in total, it will hang for an extremely long time or never complete.

**Expected behavior**

It should be able to compile in a reasonable amount of time regardless of how many form controls used.

**Reproduction of the problem**

As this is something that can't be reproduced on plunker, I've created a minimal repo that demonstrates the bug: 

https://github.com/qdouble/aot-form-controls-build-bug

To demo the bug, just clone the github repo and run `npm i` to install. 
To compile and build files, run `npm run compile`. 
To create a normal build without ngc, just use `npm run build`. 
To start server, use `npm run prodserver`.
 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-angular-builds
 
* **Language:** [TypeScript X.X]
 
* **Node (for AoT issues):** `node --version` =   6.5.0

**Comment by vicb** [comment]
Don't you think the bug should be reported @ webpack ?

**Comment by qdouble** [comment]
@vicb I'm not sure that the bug is specific to webpack. The crash is specifically based around how many form controls I have in the the template, that seems more like an Angular bug.

**Comment by vicb** [comment]
Simple check is to create a plunker, you'll see very quick.

**Comment by qdouble** [comment]
@vicb The error occurs with with files compiled with ngc how could I recreate that in a plunker? It doesn't seem possible.

**Comment by qdouble** [comment]
@vicb you could see even trying it would result in 49 unresolved errors: http://plnkr.co/edit/BFV9gHieocxYdTCtr3RZ?p=preview . Not sure how we are supposed to show ngc bugs without pointing to a repo.

**Comment by vicb** [comment]
What I mean is that JIT / AoT compilation is basically the same thing and speed should be comparable.

Reading again your description, it's not clear to me if your speed issue is with `ngc -p` ?

- If it is, might be an angular issue, plunker should have the same issue.
- If it is not, most probably wp. You can diff the generated file and try to come with a repro and submit a ticket there.

**Comment by vicb** [comment]
could you please come up with a minimal repro ?

I want to check out your project do a `ngc -p` and see the issue. Remove anything that is not strictly related to `ngc -p`, ie webpack, ...

**Comment by qdouble** [comment]
Forgot to post the link, here you go: https://github.com/qdouble/aot-bug-form-controls

**Comment by vicb** [comment]
> Remember, the issue is not with the ngc compile speed, but being able to build it afterwards

Then we agree, it's not angular, right ?

**Comment by qdouble** [comment]
@vicb Did you compile and try to create a build using your own build system? If we can't actually use the files that ngc generates, it is an angular issue. This issue shouldn't be closed yet. I've already had rob look at it and he says that it doesn't seem like a webpack issue at all.

**Comment by vicb** [comment]
> your own build system

what BS ?

**Comment by vicb** [comment]
Oh I think I understand, you might want to re-open your bug on the cli repo https://github.com/angular/angular-cli

Sorry for the confusion. I should have thought about it earlier.

**Comment by qdouble** [comment]
@vicb I mean could you see if you can use the files that are generated from the ngc compilation of those files in System JS, rollup, webpack or whatever you guys use internally? I mean, if you can see that it works without issue in any of those, then we know it's just a webpack issue. However, if it hangs then we'll know if it's a problem with the files that are spit out.

I'm not using CLI.

**Comment by qdouble** [comment]
@vicb  That angular generates the files is not proof that the files themselves are valid. If you can't actually build and use them afterwards without it taking 30 minutes, then there may be an issue with the output. Please test it.

**Comment by vicb** [comment]
> Please test it.

Nope sorry, this is not how it works.

I tell you this is a webpack bug. Prove me wrong, show me the bug in angular and then I'll test it.

I'm not saying I'm right and you're wrong. I am only saying that we don't have time to verify every single issue where people claim Angular is wrong.

When a "real" bug is reported we pay attention.

**Comment by qdouble** [comment]
@vicb I only told you that your own staff members @robwormald said that it appears to be a typescript bug and they are debugging this issue.

To quote him exactly
>@qdouble we dont think its a webpack problem exactly
>we're reasonably sure at this point its a typescript issue.
> still debugging it.

Now I definitely understand that you guys do not have the time to play tech support for every little issue that is presented here. However, you are presenting me with an impossible situation. 

I'm confident that you guys are going to eventually address this issue, because it's only a matter of time before more people start using AOT and run into the same bug. I'm only seeking to get the framework running right, not to ask for tech support. 

I'm quite sure you've spent 10x longer avoiding testing something that can be beneficial to a lot of people than it would have taken you to do so. Definitely not the most encouraging way to push the framework forward, but that's on you.

**Comment by vicb** [comment]
>  I already told you that your own staff member @robwormald said...

Sorry missed that... where ?

> I'm quite sure you've spent 10x longer avoiding testing something...

1100+ open issues * " [time is takes] you to do so" = a lot a features / fixes we could not have worked on for ng2.

> but that's on you.

We try to do the best choices. Probably we are not always right.

**Comment by qdouble** [comment]
> Sorry missed that... where ?

About 3 comments prior I said that I had rob look at it, I frequently help people out in the the gitter channel and chat with him there in the channel. His last statement on the issue, which you can see right on gitter is:  `@qdouble definitely a TS bug. Isolated it, will talk to TS team tomorrow` - https://gitter.im/angular/angular?at=57d2163a77c1b70d7ff7f675

I spent considerable amount of time creating the simplest example of it so you could test the bug in a few minutes and your own team member has clearly stated that it is not a webpack bug and they have found the issue, so there is no reason to insist further insist that this is a just a webpack thing.

I understand that you guys don't have the time to deep dive every single issue that is posted here and we should do our best to provide plunker. However, given that it's impossible for me to provide a plunker of ngc generated files, you should try to meet me half way. At the very least, you could keep the issue open for a while so others can test it or be aware of it.

**Comment by qdouble** [comment]
@vicb beyond this particular bug, I think you guys I think you guys should provide clear guidance for how we are to present bugs that only come up while using AOT. The assumption that any code that works well in JIT mode will also work well in AOT mode is false. So if the only currently acceptable way for users to provide a reproduction of the problem is to present a JIT example in plunker, it appears to me that it means reporting AOT related issues here may be a waste of time.

**Comment by kemsky** [comment]
You can reproduce it using `tsc` only. Generated files lack type information (a lot of `any`), it makes typescript compiler to do a lot of work to infer or narrow types and it likely to have bug(s) but it is not the case.  

You can leave only one file `app.ngfactory.ts`  to make typescript compiler stop. Looks like `_View_App0.injectorGetInternal` which contains many `if` statements heavily abuses typescript internal mechanics (too many return points i guess). However solved it refactoring out duplicated conditions like:
```
token === import15.NG_VALUE_ACCESSOR
token === import16.FormControlName
...
```

**Comment by kylecordes** [comment]
I appreciate very much the need to provide a reproduction case to start any bug report. But...

We should all at least acknowledge that it is **possible** that the highly idiosyncratic code emitted by NGC could send lead to surprisingly speed, size, or other characteristics from downstream tools (TSC, bundlers). Further, if this is the case, the shortest path to a fix might be to emit different code, rather than to persuade the downstream tools to tolerate the code.

A couple months ago I wrote an A2 app generator (angular2-stress-test on NPM) to help look for challenges triggered by projects that have a lot of components. I am thinking about to algorithmically generate large components, to stress things in that direction.

Before I try that though: @qdouble your repo linked at the top is especially weird, because it contains a pile of form controls all with the same formControlName of displayName. Do you also experience a weird result without that unusual characteristic? I'm mostly interested in auto-generating large but correct programs.

**Comment by qdouble** [comment]
@kylecordes I only repeated the same control in the example as it doesn't make a difference in the build time ( as this appears to be a template bug and not a class bug). In my real project, they are different controls and different types of inputs.

How I discovered it is, I only had one component that was making my project crash (or at least never finish building), when I commented out some controls, the bug would go away, but then if I put some other controls in it's place the bug would come back. Then after reducing it down to the bare minimum, I figured out the sole factor was the amount of form controls my template contained. Less than 15 fine, 20 controls, then it took 2 minutes extra to compile... 30 controls, it will seemingly never complete.

**Comment by kemsky** [comment]
@kylecordes, in this case it does not matter if controls have the same name or not. It is caused by the code generated by `ngc` for `_View_App0.injectorGetInternal` method.

**Comment by qdouble** [comment]
@kylecordes in general, I like your idea of applying stress tests to angular and I hope the internal team starts to do so as well. This bug has shown things can completely fall apart in a real world scenarios where you may have dozens or even hundreds of elements.

**Comment by vicb** [comment]
I think we would **all** benefit if we **all** put more facts and less affect in this issue tracker.
If we feel the need to express anger, frustratio, joy, thankfulness or love (who knows), there are [more appropriate channels](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).

Thanks
