### ISSUE TITLE
[Proposal] Rename facades to be shorter

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1145]
Proposal: rename `ListWrapper`, `MapWrapper`, `StringWrapper`, etc. to just `Lists`, `Maps`, `Strings`, etc. The naming idea comes from Guava. 

Thoughts?

NOTE: This only affects the angular2 codebase itself; these are not exposed to framework consumers.

**Comment by pkozlowski-opensource** [comment]
Yes! Shorter names would be sweet.

**Comment by SekibOmazic** [comment]
+1

**Comment by mhevery** [comment]
There is a separate proposal by @mprobst to completely get rid of the basic wrappers and have ts2dart generate the right code on the Dart side.

Closing this as it is not needed.
