### ISSUE TITLE
cannot find module

### ISSUE THREAD

**Issue by Chen-Michael** [angular/angular#11457]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

i need use the socket.io

so, i setting systemjs.config.js like this

`System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      'socket': 'https://cdn.socket.io/socket.io-1.4.5.js'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      
      socket: {
        defaultExtension: 'js'
      }
    }
  });

next i use npm start, display error message is 

`app/app.component.ts(2,21): error TS2307: Cannot find module 'socket'.`

so, i comment out the code like this

`//import * as io from 'socket';`

try again, is working!!

next, npm not stop but i cancel comment out import

refresh page, the socket working normally

so, how  to solve this problem

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question (your question is not related to ng2 but to typescript anyway)
