### ISSUE TITLE
[test] cleanup testing_public_spec

### ISSUE THREAD

**Issue by vicb** [angular/angular#11452]
ref https://github.com/angular/angular/blob/f78e184822c865dfb9ccb6fa7498539f2adbb9c4/modules/%40angular/platform-browser/test/testing_public_spec.ts

Some cleanup would help with readability:
- address `/** TODO #9100 */`
- remove unused vars / class / fn params / fns,
- remove `var` and use `let/const`,

``` ts
       var itPromise = patchJasmineIt();
        itPromise.then();
        restoreJasmineIt();
```

=> `ExecutePatchJasmineIt((itPromise) => {...});` (needs a better name) ?

**Comment by vikerman** [comment]
Fixed.
