### ISSUE TITLE
routing guards not triggered when navigating between children routes with path='**'

### ISSUE THREAD

**Issue by Creiger** [angular/angular#11455]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When navigating between children routes with path='**', canDeactivate guard is not triggered. Also canActivateChildren gaurd on parent route is not triggered.

**Expected behavior**

It should trigger guard on every url change when path is set to **.

**Reproduction of the problem**
This is the route configuration:
```
{ 
    path: 'somepath', 
    component: SomeComponent, 
    canActivateChildren: [
        ConfirmActivateChildrenGuard,
    ],
    children: [
        {
            path: '**',
            component: SomeComponent2,
            canDeactivate: [
                 ConfirmDeactivateGuard,
            ]
        }
    ]
}
```

**What is the motivation / use case for changing the behavior?**

Children with this path can be used for dynamic routing processed inside the SomeComponent2, but without working gaurds it is not perfect.

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [all]

**Comment by vsavkin** [comment]
Could you provide a plunkr reproducing the issue?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
