### ISSUE TITLE
:host-context with html selectors create broken css

### ISSUE THREAD

**Issue by brianmtreese** [angular/angular#11466]
**I'm submitting a...** 
```
[x] bug report 
```

**Current behavior**
When using the following...

```  
styles: [`
  :host-context(body) {
    background: red;
  }
`]
```
Angular converts this to...
```
[_nghost-ytw-1]body, body [_nghost-ytw-1] {
  background: red;
}
```
the problem here is this...
```
[_nghost-ytw-1]body
```
it's causing the whole rule to fail so even `body [_nghost-ytw-1]` will not receive the red background.

**Expected behavior**
If angular instead wrote the first selector out like the following swapping the order of "body" and "[_nghost-ytw-1]"...
```
body[_nghost-ytw-1]
```
the CSS would no longer fail and would be properly applied. 

So if, the final CSS looked like this...
```
body[_nghost-ytw-1], body [_nghost-ytw-1] {
  background: red;
}
```
the issue would be resolved.

**Reproduction of the problem**
Here is a working example of the issue: https://plnkr.co/edit/JTFhSPxZDt869RMwkNuC?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all]

**Comment by vicb** [comment]
@brianmtreese I think this has already been reported, could you pleaselook for a duplicate ?

Thanks.

**Comment by brianmtreese** [comment]
Hey Victor I had actually reported on this back in May here but the example was no longer very clear so I thought it would be best to re-report it and make everything more clear (https://github.com/angular/angular/issues/8882). Maybe I should close the old issue? Also, do you happen know if there's anything in the works for this? Thanks!

**Comment by vicb** [comment]
Yes please start by closing the old issue. Then look for an other issue.

**Comment by zoechi** [comment]
#5239 looks similar

**Comment by vicb** [comment]
thanks @zoechi for finding the issue, closing this one as duplicate
