### ISSUE TITLE
docs: Confusion about importing Routed Feature Modules

### ISSUE THREAD

**Issue by shairez** [angular/angular#11461]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] Docs clarification
```
Following our conversation @wardbell -

In the [ngmodule-faq](https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html) doc, there is a line which states - 
"Routed Feature Modules are never imported."

But in the [ngmodule guide]() itself, the ContactModule looks like a Routed Feature Module.

If contains a `contact.routing.ts` file, and from the `app.routing.ts` you have a redirection to the contact path.

It can be found both in examples and in the final plunker at the end of the doc.

So, I'm trying to understand what am I missing, is there a reason the `ContactModule` is imported in the `app.module.ts` when it isn't suppose to be?

Thanks!

**Comment by brandonroberts** [comment]
This should be filed over at https://github.com/angular/angular.io

**Comment by shairez** [comment]
You right @brandonroberts , moved it there - 
https://github.com/angular/angular.io/issues/2298
Thanks!
