### ISSUE TITLE
NG2 Router RC5 compile error: Type 'Type' is not generic

### ISSUE THREAD

**Issue by Toadskin** [angular/angular#11464]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using "ng serve" to serve up the angular-cli@webpack application, but getting errors.  The actual build and serve does run (the app works) but the console also has these compile errors.  

A dozen or so compile errors in my NG2 application, all claiming Type "Type" is not generic, all of the errors in the node_modules folder: 

ERROR in [default] ....node_modules\@angular\router\src\config.d.ts:252:49

Here's that line for example (there are a bunch of these, all the same symptoms): 

`export declare type LoadChildrenCallback = () => Type<any> | Promise<Type<any>> | Observable<Type<any>>`;

The good news is 
**Expected behavior**

Compiles without error. 

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

This is an Angular 2.0 RC5 build with Typescript 2.0.0 generated from angular-cli@webpack.  Everything worked until I wiped out node_modules and did another npm install (with or without --no-optional). 

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript 2.0.0 | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
@Toadskin usually this types of errors come from a mixed up versions of angular packages. Check your package.json and if you didn't modify it yourself please re-open this issue in https://github.com/angular/angular-cli where the CLI lives. Thnx!
