### ISSUE TITLE
Angular 2 rc6 http interceptors

### ISSUE THREAD

**Issue by karthikkavin** [angular/angular#11478]
I am early used rc4 and i implement auth interceptors service and included to main.ts bootstrap module.
This used as http header to bind token in every request.
But How to use rc6. I have used same interceptors on used rc6, But we get an error as below.

zone.js:484 Unhandled Promise rejection: newOptions.merge is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: newOptions.merge is not a function.

Does any one know help me.

**Comment by xcuben** [comment]
@karthikkavin :
Could you post some code of your rc4 version and your rc6 version to compare both of them ?

**Comment by pkozlowski-opensource** [comment]
This sounds like a support question and as such should be first asked using an appropriate support channel, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

If you still believe that this is a bug in Angular itself please feel in the issue template - most importantly - provide a minimal reproduce scenario in a plunker or similar. Closing till we've got a reproduce scenario.
