### ISSUE TITLE
Routing in combination with a form tag make trouble in Chrome

### ISSUE THREAD

**Issue by lexon0011** [angular/angular#11475]
**Problem description**

I create a form which contains some input fields an two buttons:

- The submit button: Call in the real world application a method which save the data
- A cancel button: Call a method, which navigate the user to another component

Now I have problems with the cancel button. If I enter a text into some of the input fields and then click the cancel button, the routing fails, because Chrome creates a wrong request. If I leave the fields empty, the navigation works.

**Reproduction of the problem**

1. Open [live example](http://plnkr.co/edit/PZ8OYO?p=preview)
2. Click the button "navigate to form"
3. Click the button "cancel":  everythink works well, the application routes to the home component
4. Click again the button "navigate to form" and enter some text into the input field
5. Click the button "cancel": Now the browser (Chrome) create the following request **URL/home?sampleText=asdf**. This creates a routing problem.

I also test it in IE, but there the navigation works as expected. 

**My environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** Chrome 52

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by lexon0011** [comment]
A colleague found a solution: It is necessary to call `event.preventDefault();`

I change the following code:

```
private navigateToHome(event: any)  {
      event.preventDefault();   // this line is important to solve my problem
      this.router.navigate(["/home", {}]);
}

// template
<button (click)="navigateToHome($event)">Cancel</button>
```

In my eye this is not really beautiful, maybe is it possible to improve it in the the next release candidates.

**Comment by brandonroberts** [comment]
You can also just `return false;` after the `router.navigate` which does the same thing.

```ts
private navigateToHome()  {
      this.router.navigate(["/home", {}]);
      return false;
}
```

**Comment by lexon0011** [comment]
Yes this is correct, but in my opinion this is not clean code. E.g. I write the following code:

```
private saveAndNavigateBack() : boolean {
   // save data
   // ...

   this.router.navigate(["/home", {}]);
   return false;
}
```
This could be confusing for the caller, because he thinks that the save operation went wrong if the method returns false as result.

**Comment by zoechi** [comment]
@lexon0011 you can still use `event.preventDefault()` or

    <button (click)="navigateToForm();false">navigate to form</button>

to not have `false` as return value if the method is not only called from declarative event handlers

**Comment by lexon0011** [comment]
Thanks, it seems that this is the best approach for me.
