### ISSUE TITLE
ngFormModel feature request

### ISSUE THREAD

**Issue by Lcng** [angular/angular#11474]
I'm submitting a feature request
When using ngFormModel, we need a FormBuilder to build a form model like this:
`fb.group({
    title: ['', Validators.required],
    author: ['', Validators.required]
})`
We built a form model by a literal object. It prevent us using a 'model type' or 'entity type'. 
So is adding a support for model/entity types possible?
Just as we do with some ORM frameworks, we can define an Article type like this:
`export class Article{
    public title: string;
    public author: string;
}`
And then add some necessary decorators(validators):
`export class Article{
    @required()
    public title: string;
    @required({message: 'please enter an author name.'})
    public author: string;
}`
And in our component, we just need to new an Article object:
`@Component()
export class ArticleComponent{
    article: Article;
    constructor(){
        this.article = new Article();
    }
}`
With this support, our components can be more simple and the model validation logic can be reuse.
Thank you.

**Comment by pkozlowski-opensource** [comment]
This is the same / similar to #1047. Let's centralize the discussion in there.
