### ISSUE TITLE
Docs: explain properties vs attributes and how to bind to them

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1147]
Angular 2 supports property bindings:

```
<blah [foo]="expression"></blah>
```

You can use property binding to bind to attributes too:

```
<blah [attr.foo]="expression"></blah>
```

You can also have literal attributes:

```
<blah foo="bar"></blah>
```

However, if `blah` has property `foo`, the above actually passes the value to the setter but also retains the attribute in the HTML.

Our docs should be very clear about these nuances in our syntax.

**Comment by jbdeboer** [comment]
Specifically, I want documentation for the lifecycle of these attributes: how and when they are set on a component controller.

**Comment by naomiblack** [comment]
This will be covered in the Guide that @davideast and @kwalrath are working on.

**Comment by jbdeboer** [comment]
Please link to the issue that is being worked on.
