### ISSUE TITLE
locationStrategy.getBaseHref() returns an empty value since RC6

### ISSUE THREAD

**Issue by lexon0011** [angular/angular#11477]
**Description of the problem**

In my real world applicatin I add the following html tag to my index.html
`<base href="/" />`

In the previous angular version (RC4) I could determine the base href with the following command: 
`locationStrategy.getBaseHref();`

Is there a problem with registering the provider? 
`{ provide: LocationStrategy, useClass: HashLocationStrategy }`

Or what is now the best way to determine the base href?

**Reproduction of the problem**

1. Open the [live example]( http://plnkr.co/edit/8gWamy?p=preview)
2. You can see that the methode getBaseHref() returns an empty vaule, although a base href will be set in the `index.html`

**My environment:**

* **Angular version:** 2.0.0-rc.6 
* **Browser:** all

**Comment by lexon0011** [comment]
I found already the problem. Using the following provider registration solve the problem:

`{ provide: LocationStrategy, useClass: PathLocationStrategy }`

instead of

`{ provide: LocationStrategy, useClass: HashLocationStrategy }`

**Comment by zoechi** [comment]
`{ provide: LocationStrategy, useClass: PathLocationStrategy }` is the default anyway and you can as well remove it entirely
