### ISSUE TITLE
SVG attribute are case sensitive in NG2 templates

### ISSUE THREAD

**Issue by alexanderwiebe** [angular/angular#11470]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently when I have and SVG in the HTML of an Angular 2 page it does not render responsively (Width of container and resize with container).

**Expected behavior**

When I add an SVG to the HTML using ngOnInit it behaves correctly.  The SVG is full width and resizes with the window.

**Reproduction of the problem**
I created the following plunkr that displays the non responsive SVG as well as the dynamically added SVG that is responsive.
https://plnkr.co/edit/yvcO7C6O3nRGNowQPmAA?p=preview

**What is the motivation / use case for changing the behavior?**
I would like to be able to have the SVG in the HTML so I can have a declarative way for binding information in the SVG to the Angular Module.  This was possible in Angular 1.

**Please tell us about your environment:**
I first experienced this issue in an Ionic 2 application but have been able to duplicate it in a plnkr.

* **Angular version:** 2.0.0-beta.17
 
* **Browser:** 
Chrome Version 52.0.2743.116 (64-bit), 53.0.2785.101 (64-bit) | Firefox 36.0.1, 47.0, 48.0.2 | Safari Version 9.1.3 (11601.7.8) | 

* **Language:**
TypeScript

**Comment by mxii** [comment]
You are using 2.0.0-beta.17, thats quite old!
Please update it to current RC6.

**Comment by vicb** [comment]
Angular template should be `<svg viewBox="0,0,100,100">`

Note `viewBox` vs `viewbox`

This is a bug in Angular, please use this workaround in the meantime.

**Comment by elesueur** [comment]
Hi, I am also having a similar issue. 

SVG is in an Angular component's template, and has viewBox set with the correct case. The DOM that Angular produces has viewbox all lower case.

This is Angular 2.1.0.

**Comment by vicb** [comment]
@elesueur that's a different issue, could you please open a separate issue with a repro ? Thanks

**Comment by elesueur** [comment]
@vicb I can't seem to reproduce this outside my app. Any ideas what might lead to this issue occurring?
