### ISSUE TITLE
Form with ng-if not registered in $scope

### ISSUE THREAD

**Issue by thany** [angular/angular#11482]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

A `<form>` that has any `ng-if` directive attached will not register itself in the controller $scope. Even if the ng-if _always_ resolves to true. In other words, `ng-if=true` triggers the bug as well.

I suspect this bug may also be triggered with other directives like `ng-switch`. But, I haven't tested this.

**Expected behavior**

The opposite: A form should register itself with the $scope regardless of whether it has an `ng-if`, or otherwise, or not. Especially if that `ng-if` causes the form to be rendered.

**Reproduction of the problem**

[See this plunk](http://plnkr.co/edit/1qcuLqJpkauX6gfWRIjN?p=preview)
Click the "test me" button and keep an eye on your console. It'll display `$scope.form`, which is undefined. Take away the `ng-if=true` from the form tag, and it'll print out the form object just fine.

**What is the motivation / use case for changing the behavior?**

It's useful to stop displaying a form when it's successfully sent or otherwise handled, so we can display a message (for instance, to say "thanks!") instead of redisplaying the form or having to redirect to a new page.

**Please tell us about your environment:**

* **Angular version:** 1.5.8
* **Browser:** all, as far as I can tell
* **Language:** javascript, take a pick

**Comment by pkozlowski-opensource** [comment]
Wrong repo. This belongs to https://github.com/angular/angular.js

**Comment by thany** [comment]
Can you move it there please?

**Comment by thany** [comment]
I guess that's a no :(

**Comment by DzmitryShylovich** [comment]
it's angular 2 repo
