### ISSUE TITLE
Router uses console.group() and console.groupEnd() without checking if they exist

### ISSUE THREAD

**Issue by steveschmitt** [angular/angular#11487]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

In [angular/modules/@angular/router/src/router_module.ts](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router_module.ts), line 173-176, `console.group()` and `console.groupEnd()` are used without checking if they exist.  This checking _should be_ performed (as it is elsewhere):

```
if (console.group) { console.group("..."); }
...
if (console.groupEnd) { console.groupEnd("..."); }
```

**Current behavior** 
Router throws error on browsers that don't have `console.group` and `console.groupEnd`

**Expected behavior**
No attempt is made to group() or groupEnd() on browsers that don't support it.

**Reproduction of the problem**
Try on IE 10

**What is the motivation / use case for changing the behavior?**
Client wants to run application on IE 10.  It works fine except for this problem and some internationalization stuff.

**Please tell us about your environment:**
Windows 7, IE 10
- **Angular version:** 2.0.0-rc.6
  Still an issue in rc6
- **Browser:** IE 10
- **Language:** TypeScript 1.8
- **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
@vsavkin should you use the `console` service here ?
