### ISSUE TITLE
Router doesnt load template

### ISSUE THREAD

**Issue by ThomasP1988** [angular/angular#11483]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
While upgrading to RC6, i made some changes and got some bugs, but I can not get rid of this one. I apologize if I did something wrong but I'm running out of solution
I have a layout in my AppComponent which is correctly loaded, but when I use the router it loads my Class but doesnt display my template

Describe how the bug manifests. 

I don't have any error message, and the <router-outlet></router-outlet> is in the page but empty

**Expected behavior**

I would like the template to  be displayed

Describe what the behavior would be without bug.

When joining '/create-topic', it would display the template 

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
Router version 2.0.0-rc.2

* **Browser:** [all ] 
 
* **Language:** [all | typescript@2.0.2 | ES6/7 ]
 
* **Node (for AoT issues):** `node --version` =   v6.4.0

Package.json
`{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "webpack-dev-server --inline --progress --port 8880",
    "test": "karma start",
    "build": "rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail",
    "postinstall": "typings install"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.11",
    "zone.js": "^0.6.17",
    "font-awesome": "^4.6.3",
    "mydatepicker": "0.0.17",
    "ng2-click-outside": "^0.5.1",
    "raw-loader": "^0.5.1"
  },
  "devDependencies": {
    "angular2-template-loader": "^0.4.0",
    "concurrently": "^2.2.0",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-jasmine": "^0.3.8",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "node-sass": "^3.8.0",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "postcss-loader": "^0.10.1",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "sass-loader": "^4.0.0",
    "style-loader": "^0.13.1",
    "ts-loader": "^0.8.1",
    "typings": "^1.3.2",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.14.0"
  }
}
`

Main.ts
`
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';

const platform = platformBrowserDynamic();
platform.bootstrapModule(AppModule);

if (process.env.ENV === 'production') {
    enableProdMode();
}`

app.module.ts 
`@NgModule({
    declarations: [AppComponent, CreateTopicComponent],
    imports: [AppRouting, BrowserModule, ReactiveFormsModule, CommonModule, FormsModule, HttpModule],
    providers: [
        {provide: Http, useFactory: (backend: XHRBackend, defaultOptions: RequestOptions) => new HttpInterceptor(backend, defaultOptions), deps: [XHRBackend, RequestOptions]},
        FormatInSearchDefinition, SearchService, appRoutingProviders
    ],
    bootstrap : [AppComponent]
})
export class AppModule {
    constructor(appRef: ApplicationRef) {
        appRef.bootstrap(AppComponent);
    }
}`

app.routes.ts
`import { Routes, RouterModule } from '@angular/router';
import { CreateTopicComponent }   from './search/components/create-topic.component';
import { ResultsComponent } from './search-results/components/results.component';
import { createTopicRoutes } from './search/components/routing/create-topic.routing';
import { topicRoutes } from './topics/components/routing/topic.routing';
import { ModuleWithProviders } from '@angular/core';

export const routes: Routes = [
    {
        path: 'create-topic', component: CreateTopicComponent
    }
];

export const appRoutingProviders: any[] = [

];

export const AppRouting : ModuleWithProviders  = RouterModule.forRoot(routes);`

app.component.ts

`import { Component } from '@angular/core';

@Component({
    selector: 'my-app',
    template:  require('./layouts/index.html')
})

export class AppComponent {
    constructor() {}
}`

./layouts/index.html
`<div>
        <router-outlet></router-outlet>
</div>`

create-topic.component.ts
'import { Component, OnInit } from '@angular/core';
import { AdvancedSearchComponent } from './advanced-search.component';
import { SearchService } from '../services/search';

@Component({
    selector: 'create-topic',
    template:  require('./templates/create-topic.component.html'),
    providers : [SearchService]
})

export class CreateTopicComponent implements OnInit {
    constructor(public searchService : SearchService) {

    }

    ngOnInit() {
        console.log('le create topic');
    }
}'

create-topic.component.html

`test`

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
