### ISSUE TITLE
NgModule Api 

### ISSUE THREAD

**Issue by SergeyBarskiy** [angular/angular#11481]
**I'm submitting a feature request
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently a component can only be declared in one module. I think this limitation should be removed because it will force people to maintain one giant common component module.  On a related note, entry component property in module should be removed in favor if putting all components into declarations.  Here is the motivation for this.  Customer search screen in customer module could be both entry component and declaration, depending on a use.  For example, when I want to edit a customer, I need to start with a search screen and when I want to pick a 'child' customer for a customer, I want to start with a search screen.  On top of that, I may want to use the same customer search component in orders module.

**Expected behavior**

I should be able to declare one component in as many modules as I want and not worry about whether it is a top level component or not because it could be both.

**Reproduction of the problem**
See description

**What is the motivation / use case for changing the behavior?**
Simplify coding

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all]
 
* **Language:** [all | TypeScript 1.8
 
* **Node (for AoT issues):** `node --version` =   latest

**Comment by robwormald** [comment]
There's nothing inherent in NgModules that forces you to have a monolithic shared module - that would be bad program design regardless of the framework you're using. Components can be used both as entryModules and statically referenced in templates.

I discussed some of this in here https://github.com/angular/angular/issues/10552#issuecomment-241575593

See also how angular material sets things up https://github.com/angular/material2/tree/master/src/lib/card

**Comment by SergeyBarskiy** [comment]
@robwormald
So, how do I declare the same component in two modules?  If I do I get an exception, stating this cannot be done.
Thanks.

**Comment by SergeyBarskiy** [comment]
@robwormald
Let me  explain myself better.  If I have three shared components a, b, c and two module x and y.  Module X needs A and B, module Y needs A and C.  Now I am forced to create three shared modules, one with each component or one shared module with all three.  I feel this is awkward.   What I really want to is to be able to declare one component in multiple modules, which provides for much more flexible sharing.  
Thanks.

**Comment by SergeyBarskiy** [comment]
Incidentally, the idea of sharing classes across assemblies is not unique.  There is a feature in .NET called shared projects which does exactly this http://www.c-sharpcorner.com/uploadfile/7ca517/shared-project-an-impressive-features-of-visual-studio-201/.  There is also a feature of linked files, which allows to include the same file in multiple assemblies.  Both allow for a lot more flexibility when it comes to sharing components aka classes that NgModule does.  Just an FYI.

**Comment by zoechi** [comment]
@SergeyBarskiy 

> Let me explain myself better. If I have three shared components a, b, c and two module x and y. Module X needs A and B, module Y needs A and C. Now I am forced to create three shared modules, one with each 

I can't make sense of this sentence.

You can combine components to modules as you please. I don't get why you think you need to create a shared module for each component.

There are only 2 requirements
- one component can only be assigned to one module
- when a component is used in the current module the module that contains that component needs to be imported.

Just combine components to modules as you think they fit together.

**Comment by SergeyBarskiy** [comment]
@zoechi 
That is precisely what I cannot do - combine the components into modules as I want because one component can only belong to one module.  Personally, I wold like to have this restriction removed.  This was the initial point I was trying to make, I just did not make myself clear.  This restriction does not exist in a popular language, such as .NET.  It was explicitly removed from it due to developer requests (see my additional links above).

**Comment by zoechi** [comment]
I get that you want this restriction removed but I don't understand how this forces you to create more modules than you want.

You can export components in module A imported from module B, C, D, to get all at once with an import of A in E. I don't see much limitation here.

**Comment by SergeyBarskiy** [comment]
Thanks, @zoechi 
It is a valid point, I just feel that I am forced to follow this pattern and import component into a module for the sole purpose of just exporting them,  This seems unnecessary in my opinion.  Thanks for taking time to explain.

**Comment by mhevery** [comment]
When you make a component part of a module you impart on it a set of rules when it is compiled. Having a component without belonging to a NgModule is meaningless as the compiler can't compile it. Having a component be part of more then one module is also weird as you are saying that depending which module you chose the rules for compiling are different. And when you dynamically load such a component it would be ambiguous which set of compilation rules you wanted. 

The idea of removing that each component belongs to exactly one module is a no-go for the reasons stated above.

I am sorry that you don't enjoy our decisions, but there are technical reasons why it is done this way.
