### ISSUE TITLE
Angular 2 RC 5 router won't work in hybrid app

### ISSUE THREAD

**Issue by RajicA** [angular/angular#11480]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm trying to build a hybrid angular 1 / angular 2 RC 5 app. Hybrid app successfully bootstraps, but when I try to use router in my app component I get an error:

> Bootstrap at least one component before injecting Router

**Reproduction of the problem**

This is the app.routing.ts file:

```
import { ModuleWithProviders }  from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { ForumComponent }   from './forum/forum.component';

const appRoutes: Routes = [
  {
    path: '',
    redirectTo: '/forum',
    pathMatch: 'full'
  },
  {
    path: 'forum',
    component: ForumComponent
  }
];

export const routing: ModuleWithProviders = RouterModule.forRoot(appRoutes);
```

This is the main.ts file (app module definition is in this file as well, because if I instantiate the upgrade adapter somewhere other then the main.ts, the bootstrap fails): 

```
import { platformBrowserDynamic }    from '@angular/platform-browser-dynamic';
import { UpgradeAdapter } from '@angular/upgrade';
import { forwardRef, NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { BrowserModule } from '@angular/platform-browser';
import 'rxjs/add/operator/map';
import { routing } from './app.routing';
import { ForumComponent }   from './forum/forum.component';

declare var angular: any;
const APPNAME = 'myApp';

const adapter = new UpgradeAdapter(forwardRef(() => AppModule));
angular.module(APPNAME).directive('ng2App', adapter.downgradeNg2Component(AppComponent));
const userPhoto = adapter.upgradeNg1Component('userphoto');
adapter.upgradeNg1Provider('User');
adapter.upgradeNg1Provider('ImageEditService');
adapter.bootstrap(document.documentElement, [APPNAME], {strictDi: true});

@NgModule({
  imports:      [ BrowserModule, routing ],
  providers:    [],
  declarations: [ AppComponent, userPhoto, ForumComponent ] 
  bootstrap:    [ AppComponent ]

})
export class AppModule { }
```

This is the app.component.html template:

```

<nav>
    <a routerLink="/forum" routerLinkActive="active">Forum</a>
</nav>
<router-outlet></router-outlet>
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by vicb** [comment]
Your report is missing a plunker.
Please use RC6 which is the last release.

Also:
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by RajicA** [comment]
I can't use RC 6 because of this  issue https://github.com/angular/angular/issues/11249, I will provide you with the plunker as soon as I figure out how to make it .

Please, don't close this issue. Thank you.

**Comment by pkozlowski-opensource** [comment]
> Please, don't close this issue

We will re-open when you've got a minimal reproduction scenario in a plunker.

**Comment by jgf5013** [comment]
I'd really like to see this feature in rc.5 as well.

**Comment by pdhar-tibco** [comment]
I have a similar situation where the main app is a Ng1 app which loads a cross origin Ng2 app SystemJS loader.
Ng1 App - phone-upgrade example : https://github.com/pdhar-tibco/phone-upgrade/tree/remote-modules
Ng2 App - stocks : https://github.com/pdhar-tibco/stocks

I am able to bring the top level directives from the ng2app to ng1app using the upgrade adapter. However after the ng2app shows up the <router-outlet></router-outlet> section is not getting populated and I am missing some key information as to why. Based on the discussion above this seems to be a bug and I have a working example to see it.

Build & Run instructions:
phone-upgrade : tsc && npm start
stocks : gulp build && npm start
