### ISSUE TITLE
Broken link on README.md

### ISSUE THREAD

**Issue by papaponmx** [angular/angular#11499]
**I'm submitting a ...
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
There is a broken link for two images on the README.md file

**Expected behavior**
The image should look something similar to the ones generated from lines 1 and 2.

**Reproduction of the problem**
Just check the repo[] and lines 4-6. Here is an image
![image](https://cloud.githubusercontent.com/assets/13476631/18407618/784d38a4-76db-11e6-9a5e-01cfd85b4303.png)

**What is the motivation / use case for changing the behavior?**
Broken links

**Please tell us about your environment:**
I'm using google chrome.

* **Angular version:** 2.0.0-rc.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
Those badges come from an external site (http://issuestats.com/github/angular/angular) and sometimes it is slow to respond hence the "broken" images. Just checked on my side right now and those 2 look fine.

I'm going to close this for now but we might consider removing those links if issuestats.com misbehaves in the future.
