### ISSUE TITLE
`null === undefined` and similar expressions evaluate to true in the template compiler.

### ISSUE THREAD

**Issue by xorgy** [angular/angular#11493]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
`variable === undefined` is true when `variable` is `null`, and `null === undefined` is true in templates.
`variable === null` is false (as expected) when `variable` is `undefined`, but `undefined === null` is true.

**Expected behavior**
`variable === undefined` should evaluate to false when `variable` is `null`, and `null === undefined` should evaluate to false.
`variable === null` should evaluate to false (as it does) when `variable` is `undefined`, and `undefined === null` should evaluate to false.
**Reproduction of the problem**
http://plnkr.co/edit/4QQdILnqyswJAXMIPyHK?p=preview

**What is the motivation / use case for changing the behavior?**
It violates common sense in JavaScript and TypeScript to an offensive degree.
- **Angular version:** 2.0.0-rc.6
- **Browser:** all 
- **Language:** all

**Comment by vicb** [comment]
/cc @tbosch 

probably in the codegen, the parser was updated to support `undefined`

**Comment by vicb** [comment]
It is indeed in codegen `visitLiteralExpr()`
