### ISSUE TITLE
Http Post with empty body throws NPE

### ISSUE THREAD

**Issue by kemsky** [angular/angular#11495]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Post request with empty body will fail with NPE (regression)

[body.ts:L60](https://github.com/angular/angular/blob/436af15d63489e3e91960d30f45f7c3c2292c125/modules/%40angular/http/src/body.ts#L60)

**Expected behavior**
Empty post should work.

* **Angular version:** 2.0.0-rc.5

* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.11]

**Comment by ericmartinezr** [comment]
See if your issue is the same as this one https://github.com/angular/angular/issues/10612, this is already fixed in RC6. In fact the link you referenced already contains that fix, you should provide a reproduction using latest RC.
