### ISSUE TITLE
@angular/router NPM package contradicts VCS peer-dependency for RXJS

### ISSUE THREAD

**Issue by akomm** [angular/angular#11502]
I'm submitting a
```
[x] bug report
```

**Current behavior** 
I install **@angular/router:3.0.0-rc.1**, which has peer dependency **rxjs:5.0.0-beta.11** ([link](https://github.com/angular/angular/blob/2.0.0-rc.6/modules/%40angular/router/package.json#L27)) using NPM. 
I confirm checking installed **node_modules**, that the installed version of router module is **3.0.0-rc.1** in its package.json. Its peer dependencies are:

```json
  "peerDependencies": {
    "@angular/common": "^2.0.0-rc.5",
    "@angular/compiler": "^2.0.0-rc.5",
    "@angular/core": "^2.0.0-rc.5",
    "@angular/platform-browser": "^2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.5",
    "rxjs": "5.0.0-beta.6"
  }
``` 

**Expected behavior**
At least the rxjs peer-dependency should be as stated [here](https://github.com/angular/angular/blob/2.0.0-rc.6/modules/%40angular/router/package.json#L27) (5.0.0-beta.11). Additionally, when built under **2.0.0-rc.6** tagged commit, should it not depend on peers **@angular/*:2.0.0-rc.6** and not **rc.5**?

**Please tell us about your environment:**
linux, npm (3.10.3), node (6.5.0)
* **Angular version:** 2.0.0-rc.6
* **Browser:** all
* **Language:** all

**Comment by DzmitryShylovich** [comment]
`@angular/router:3.0.0-rc.1` - `"rxjs": "5.0.0-beta.6"`
`@angular/router:3.0.0-rc.2` - `"rxjs": "5.0.0-beta.11"`

**Comment by akomm** [comment]
I can see that myself via `npm view @angular/router@3.0.0-rc.1` and `npm view @angular/router@3.0.0-rc.2`.

**Comment by robwormald** [comment]
Router 3.0.0 RC2 uses Rx beta.11, as expected. Not sure what the issue is here yet?
