### ISSUE TITLE
No way to disable a form input in the model-driven mode with forms ?

### ISSUE THREAD

**Issue by samfrach** [angular/angular#11505]
Hello,

I would like to use the model-driven mode but it seems it is not possible to enable/disable an input field after it has been created.

With RC6, once the formControlName attribute is set on an input. The disabled property is controlled by the FormControl element which can be set to enabled or disabled... but only in the constructor. 

 <input type="text" formControlName="firstName">

why is this feature missing ? It's very useful to disable a field (and not hide it) after another field has been filled...

thanks for your help and I hope I am wrong...

**Comment by pkozlowski-opensource** [comment]
You can call `disable()` / `enable()` methods on a form control to disable / enable it programatically.
