### ISSUE TITLE
Angular 2 Router Documentation skips import of ModuleWithProviders causing typescript error

### ISSUE THREAD

**Issue by goelinsights** [angular/angular#11509]
Minor error with simple fix.  Just trying to save someone else the 15 minutes I spent troubleshooting.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
ERROR in [default] /my-app/src/app/app.routing.ts:14:22
Cannot find name 'ModuleWithProviders'

FIX: (just needs to be added to the docs): https://angular.io/docs/ts/latest/guide/router.html
import { ModuleWithProviders } from '@angular/core'; in app.routing.ts

**Expected behavior**
No error

**Reproduction of the problem**
typescript underlines ModuleWithProviders in a copy/ paste of the configuration setting of the Router documentation https://angular.io/docs/ts/latest/guide/router.html

**What is the motivation / use case for changing the behavior?**
Remove error

**Please tell us about your environment:**
Mac OS X

* **Angular version:** 2.0.0-rc.6

* **Browser:** [Chrome XX ] 

 
* **Language:** [all | TypeScript 2.02 ]
 
* **Node (for AoT issues):** `node --version` =

**Comment by goelinsights** [comment]
@wardbell is there a better way to submit these for documentation bugs?

**Comment by robwormald** [comment]
Docs bugs go to https://github.com/angular/angular.io - would you re-open over there? thanks for the report!

**Comment by slatteryja** [comment]
Thanks for saving me 15 mins!
