### ISSUE TITLE
"Unexpected token import" in facade/collection.js

### ISSUE THREAD

**Issue by VladimirAmiorkov** [angular/angular#11501]
**I'm submitting a

[X] bug report
[ ] feature request
[ ] support request

**Current behavior** 
An "**Unexpected token import**" error is thrown when importing the `isListLikeIterable` from `@angular/common/src/facade/collection` in the RC6. Shorthanded StackTrace:

> SyntaxError: Unexpected token import
> File: ".../@angular/common/src/facade/collection.js, line8, column: 0"

**Expected behavior**
No error thrown like it was in RC5.

**Reproduction of the problem**
Simply import the isListLikeIterable from @angular/common/src/facade/collection and use it somewhere:

```
import { isListLikeIterable } from '@angular/common/src/facade/collection';

set eventSource(value: any) {
    console.log(isListLikeIterable(value));
}
```

**What is the motivation / use case for changing the behavior?**
Upgrading my current project from RC5 to RC6

**Please tell us about your environment:**
I am currently working with Angular 2 RC6, here are the dependencies of my project:

```
"dependencies": {
		"@angular/common": "2.0.0-rc.6",
		"@angular/compiler": "2.0.0-rc.6",
		"@angular/core": "2.0.0-rc.6",
		"@angular/platform-browser": "2.0.0-rc.6",
		"@angular/platform-browser-dynamic": "2.0.0-rc.6",
		"@angular/platform-server": "2.0.0-rc.6",
		"@angular/router": "3.0.0-rc.2",
		"rxjs": "5.0.0-beta.11",
		"zone.js": "^0.6.17",
		"parse5": "1.4.2",
		"punycode": "1.3.2",
		"querystring": "0.2.0",
		"reflect-metadata": "^0.1.3",
		"url": "0.10.3"
	},
```

* **Angular version:** 2.0.0-rc.6

* **Browser:** [all] 
 
* **Language:** [all | TypeScript 1.8.10
 
* **Node (for AoT issues):** 4.4.1

**Comment by pkozlowski-opensource** [comment]
See #11197

Your code (or one of your dependencies) is importing from a private path, which is not allowed.

**Comment by VladimirAmiorkov** [comment]
Hi @pkozlowski-opensource ,

Thank you for the lightning speed replay/close. So what you are saying is that the `isListLikeIterable` should not be used by the users, strange that it is added as exported in the d.ts. Was this mentioned in the release notes of your RC6 as I did not find any information about this and it was working fine one release earlier?

**Comment by pkozlowski-opensource** [comment]
> So what you are saying is that the isListLikeIterable should not be used by the users

Exactly. You should be importing from the top-level packages (`@angular/[...]`) only. Anything that has `src` in the path is for sure private.

> Was this mentioned in the release notes of your RC6 as I did not find any information about this and it was working fine one release earlier?

Not sure if this was mentioned explicitly in RC6 but those `.../src/...` imports were meant to and advertised as private from the very beginning. A PR with update to the changelog would be great if you think it requires a more explicit note.

**Comment by VladimirAmiorkov** [comment]
@pkozlowski-opensource Thank you for the help. It looks like the `src` nite slipped by me some time ago.

**Comment by zoechi** [comment]
@VladimirAmiorkov See angular/angular.io#1617
Seems importing from `src` is prevented effectively in recent versions (not sure what tools is responsible to prevent it)
