### ISSUE TITLE
text input show undefined on undefined value instead of empty string

### ISSUE THREAD

**Issue by AlmogShaul** [angular/angular#11517]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

       <input [value]="val" type="text" >
       <input [(ngModel)]="val" type="text" >

on the frist case: when val = undefined the input will show on the screen "undefined"

on the second case: when val = undefined the input will show on the screen ""

**Expected behavior**
        <input [value]="val" type="text" >
when val = undefined the input will show on the screen ""

**What is the motivation / use case for changing the behavior?**
The behavior should be the same for value and ngModel

**Please tell us about your environment:**
Chrome latest version

* **Angular version:** 2.0.0-rc.6

* **Browser:** :all
 
* **Language:** TS 1.8

**Comment by vicb** [comment]
The first case means set the 'value' property of the node to 'val'

How this property is interpreted is defined by the spec.

The behavior you describe could be achieved via a directive but it would be weird to have different behavior out of the box
