### ISSUE TITLE
g

### ISSUE THREAD

**Issue by okcxl3** [angular/angular#11511]
* **Angular version:** 2.0.0-rc.6

I tried to assign "ngModel" to #firstname, but when I ran the app, it crashed and the error message was: There is no directive with "exportAs" set to "ngModel". Please help

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by okcxl3** [comment]
`
    <fieldset class="form-group" >
                        <div class="alert alert-danger" >Your full name is required</div>
                        <label class="c form_label">Full Name*</label>
                        <h6 class="d" style="font-size:0.86rem">I would like to know who I am speaking with</h6>
                        <div class="row">
                            <div class="col-md-6">
                                <input  name="firstname" required class="form-control" #firstname="ngModel"/>
                                <h6 class="a" style="font-size:0.82rem">First Name</h6>
                            </div>
                            <div class="col-md-6">
                                <input name="lastname" required class="form-control"  #lastname="ngModel"/>
                                <h6 class="a" style="font-size:0.82rem">Last Name</h6>
                            </div>

                        </div>
                    </fieldset>
`

**Comment by okcxl3** [comment]
<fieldset class="form-group" >
                        <div class="alert alert-danger" >Your full name is required</div>
                        <label class="c form_label">Full Name*</label>
                        <h6 class="d" style="font-size:0.86rem">I would like to know who I am speaking with</h6>
                        <div class="row">
                            <div class="col-md-6">
                                <input  name="firstname" required class="form-control" #firstname="ngModel"/>
                                <h6 class="a" style="font-size:0.82rem">First Name</h6>
                            </div>
                            <div class="col-md-6">
                                <input name="lastname" required class="form-control"  #lastname="ngModel"/>
                                <h6 class="a" style="font-size:0.82rem">Last Name</h6>
                            </div>

                        </div>
                    </fieldset>

**Comment by okcxl3** [comment]
<fieldset class="form-group" >
                        <div class="alert alert-danger" >Your full name is required</div>
                        <label class="c form_label">Full Name*</label>
                        <h6 class="d" style="font-size:0.86rem">I would like to know who I am speaking with</h6>
                        <div class="row">
                            <div class="col-md-6">
                                <input  name="firstname" required class="form-control" #firstname="ngModel"/>
                                <h6 class="a" style="font-size:0.82rem">First Name</h6>
                            </div>
                            <div class="col-md-6">
                                <input name="lastname" required class="form-control"  #lastname="ngModel"/>
                                <h6 class="a" style="font-size:0.82rem">Last Name</h6>
                            </div>

                        </div>
                    </fieldset>
This is my code

**Comment by mhevery** [comment]
Closing. Please open new bug with a plunker demonstrating the problem.
