### ISSUE TITLE
API doc convention

### ISSUE THREAD

**Issue by vicb** [angular/angular#11513]
@IgorMinar what are the doc tags and in what order should we use them ?

Some PR use the `@selector` tag, hopefully this is automatically extracted. Otherwise it'll get out of sync sooner or later.

We must come up with that **before** merging the PR IMO.

**Comment by vicb** [comment]
Best would be to enforce the tag presence & order in the doc build tools

**Comment by vicb** [comment]
We need convetions for:
- filenames: `thing/thing_example.ts` could be `thing/example.ts`
- component naming,
- `NgModule` location (exported from the app),
- `#docregion` naming - a lot of them are currently "Component"

**Comment by wardbell** [comment]
Closing as old.
