### ISSUE TITLE
FormGroup reset method doesn't work properly for radio control type

### ISSUE THREAD

**Issue by tscislo** [angular/angular#11516]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Reseting a radio button using FormGroup resets value but does not unselect one of the radio buttons  

**Expected behavior**
When we use FormGroup reset method not only the value of radio should reset but also the radio button in the template

**Reproduction of the problem**
http://plnkr.co/edit/VDfq8N

**What is the motivation / use case for changing the behavior?**
This behavior is inconsistent, because reset for input type text works properly, because it clears the input box

* **Angular version:** 2.0.0-rc.X
2.0.0-RC6

* **Browser:** 
all
 
* **Language:**
all

**Comment by kara** [comment]
@tscislo  Hmm, this seems weird. I'll look into it

**Comment by tscislo** [comment]
@kara thanks! When this fix will be released?

**Comment by pkozlowski-opensource** [comment]
> When this fix will be released? 

With a next release :-)
