### ISSUE TITLE
Update the browser compatibility graph in README.md

### ISSUE THREAD

**Issue by asnowwolf** [angular/angular#11523]
**I'm submitting a ...**  (check one with "x")

- [x] bug report => search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior** 

IE 9 and Android 4.3 is still RED.

**Expected behavior**

in the latest CI log, they are green. please update it to the latest status and keep-alive.

**Comment by mlaval** [comment]
The badge is correctly updated when CI is run after pushing to master.
Here is the direct link to it: https://saucelabs.com/browser-matrix/angular2-ci.svg

Then there might be some caching issue on the image also.

**Comment by asnowwolf** [comment]
@vicb 
It's backed!
I think it's better to disable the image cache. or we should remove it from readme.md.
It will mislead the developers,  make they think the final release is not stable or not compatible.

**Comment by asnowwolf** [comment]
@vicb 
o, It's not caused by the cache, but the latest version is failed on IE9. 
But i still think it will mislead the developers. @naomiblack what do you think about this?
