### ISSUE TITLE
Compiler should detect invalid property binding

### ISSUE THREAD

**Issue by hhubik** [angular/angular#11521]
**I'm submitting a ...**  `[X ] feature request`

If possible, Angular2 compiler should detect and flag the following as an error:

Component A has an input property defined as follows:
`@Input() rows: number;`

The template of a parent component (hosting Component A) references the property `rows` as an attribute like this:
`<comp-a ... rows="5">`
instead of 
`<comp-a ... [rows]="5">`

In Angular RC6/Typescript 2.0.2, this compiles, but the value of `this.rows` in Component A is the string `"5"` as opposed to the number `5`.

**What is the motivation / use case for changing the behavior?**
Developer productivity.

**Please tell us about your environment:**
Windows 8.1 x64, Visual Studio Code

* **Angular version:** 2.0.0-rc.6

* **Language:** TypeScript 2.0.2

**Comment by ericmartinezr** [comment]
This may help https://github.com/angular/angular/issues/6919

**Comment by vicb** [comment]
It is not an error.

think `<p title="...">` it makes sense for directive to get the content of the title
