### ISSUE TITLE
Codegen: DI should not import JS types

### ISSUE THREAD

**Issue by sod** [angular/angular#11528]
**I'm submitting a ...**  (check one with "x")

```
[x] feature request
```

**Current behavior** 
`constructor(@Optional() foo: number = 2) {}` as in:

``` typescript
@Component({
    selector: 'my-app',
    template: `<h1>My App</h1>`
})
export class MyAppComponent {
    constructor(@Optional() foo: number = 2) {}
}
```

works without complaining: http://plnkr.co/edit/2A0cQLXebthySz3GIuVd?p=preview
And AoT runs without complaining and produces: https://gist.github.com/sod/f3e142c0d9ee0c67939521545b28da86

But the AoT result doesn't run, as the ngfactory tries to import `number` to inject it. But `number` isn't exported.

**Expected behavior**

Throw an error if the import doesn't exist. Or don't try to import native types. And maybe throw an error if the constructor contains default value syntax as it isn't supported by the dependency injector anyway :)
- **Angular version:** 2.0.0-rc.6
- **Language:** TypeScript
- **Node (for AoT issues):** `node --version` = v4.5.0

**Comment by vicb** [comment]
Do you bind `number` ?

**Comment by vicb** [comment]
Ok, got it.
Use `@Inject('...')` if you need a workaround.

**Comment by DzmitryShylovich** [comment]
@sod 
> And AoT runs without complaining

I got the following error: `Error at D:/Workspace/bug/src/compiled/src/app/app.module.ngfactory.ts:255:62: Property 'number' does not exist on type 'typeof "D:/Workspace/bug/src/app/app.module"'.`

**Comment by sod** [comment]
For me it's still reproducable on `angular 2.4.6`. `ngc` tries to import `number` and inject it. The workaround provided by @vicb - to use `@Inject('...')` in front of `@Optional()` - works.

**Comment by sod** [comment]
The code was intended to inject a simple string in a test and access window otherwise. 

In retrospective my feature request doesn't make sense. I should use the dependecy injector and provide the value. And if the type is a basic type, use `@Inject('providerName')` together with `@Optional()`.
