### ISSUE TITLE
load children have problem when its parent also use loadchildren

### ISSUE THREAD

**Issue by sadydai** [angular/angular#11527]
`{
        path: 'base',
        component: BaseComponent,
        children: [
            {
                path: 'customer',
                loadChildren: 'app/src/customer/customer.module#Custmodule',
            },
            {
                path: 'market',
                loadChildren: 'app/src/Market/market.module#MarketModule',
            },
            {
                path: '',
           loadChildren: 'app/src/customer/customer.module#Custmodule'}
        ]},`
the children routing:
`{path:'', component:CustComponent,
children:[{path:'cus1', loadChildren: 'app/src/customer/Cust1.module#Cust1module',},     {path:'cus2',loadChildren: 'app/src/customer/Cust2.module#Cust2module',},
{path:'',loadChildren: 'app/src/customer/Cust1.module#Cust1module',}]}`

but it's getting wrong when  children also use load children   .the error is : stack size exceeded

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
