### ISSUE TITLE
Remove pipes from bindings

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1152]
It looks like there is some consensus that pipes in bindings do more harm than good (see [proposed design](https://docs.google.com/document/d/1c6lAsvlCvhkbiEXsPBraWVIw8e_zr5Bgjy5j10T1I1M/edit#heading=h.hekddrfd1aqc)).

**Comment by mohsen1** [comment]
could you please make the document public?

**Comment by pkozlowski-opensource** [comment]
Same here, can't access this doc. @yjbanov @vsavkin  would you mind summarising, in like 2 sentences, what is the harm done by pipes in bindings? What will be an alternative mechanism for directives like `for` (or a new `class` that I've just opened a PR for)?

**Comment by naomiblack** [comment]
Moving to M8. If a private component has a pipe in its binding, there's no way to get to that pipe. But this is not blocking M7.

**Comment by yjbanov** [comment]
@vsavkin Could you share the proposal pls?

@pkozlowski-opensource @mohsen1 

In short, we already can do what pipes do in plain JS/Dart. If you want to post-process an incoming value, do it in the setter. If you want to customize the post-processing, inject something from outside and use that in the setter.

Pipes require a lot more plumbing in the core and more concepts for developers to learn (and for us to document), such as https://github.com/angular/angular/issues/1087. The whole concept of `DirectiveRef` seems to exist only to support binding pipes.

**Comment by vsavkin** [comment]
Had to create a new doc: https://docs.google.com/document/d/1WzTzrRxHPOZ2ycYEhnH4PAonpzoFjlONwUF6SR-9TrE/edit#heading=h.hekddrfd1aqc

**Comment by mhevery** [comment]
I am still not sold on this. Needs more discussion before we make a decision.

**Comment by yjbanov** [comment]
@mhevery Have you discussed this with @vsavkin yet? If not, could you document your concerns here?

**Comment by mhevery** [comment]
Current state is that we will remove pipes from the annotation, this will align the Component Controller API with the public API of the element. I believe we should all be in alignment here.

**Comment by mhevery** [comment]
Resolved
