### ISSUE TITLE
Resolve guard called twice on back button with HashLocationStrategy enabled

### ISSUE THREAD

**Issue by mikesnare** [angular/angular#11520]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

Using the browser back/forward buttons causes a Resolve Guard to run twice in the following situation:

1. The resolve guard returns an Observable that resolves asynchronously.
2. The `LocationStrategy` is set to the `HashLocationStrategy`

**Expected behavior**

The Resolve guard should only run once.

**Reproduction of the problem**

1. Set your `LocationStrategy` to `HashLocationStrategy`
2. Create a routed component, and add a resolve guard to it.  
3. In the resolve function, return an observable, and supply a value to the observer in a timeout.  (add a console.log so you can see that the resolve is getting called).
4. Navigate to this component.
5. Navigate somewhere else in your app.
6. Hit the back button in your browser.

You'll see the console log print twice when you click the back button.

http://plnkr.co/edit/NxR1gkk0HHX8M4VTHTrn

**What is the motivation / use case for changing the behavior?**

Resolve guard shouldn't be called twice.

**Please tell us about your environment:**

Mac (Yosemite)
IntelliJ
NPM
Node

* **Angular version:** 2.0.0-rc.X

2.0.0-rc.6

* **Browser:**

Chrome 52.0.2743.116 (64-bit)
Safari 9.1.3 (10601.7.8)

(Could not reproduce in Firefox)
 
* **Language:**

TypeScript 2.0.2
 
* **Node (for AoT issues):** `node --version` =  v4.4.5

**Comment by zoechi** [comment]
Seems to be similar to #7605

**Comment by mikesnare** [comment]
Not sure why you got downthumbed, @zoechi.  I think you might be right.  They're not *exactly* the same, but they're close.

If you manually change the URL of mine from `/two` to `/one` you get the double call (can't test that in plunkr, though), which is what is described in #7605 and that one also uses the `HashLocationStrategy`.

However, my guard has to return an Observable that emits its item asynchronously to trigger the bug, whereas his bug doesn't have that trait.  I commented on his about a week and a half ago, but thought mine might be just different enough to warrant its own bug.

**Comment by zoechi** [comment]
@mikesnare No prob. I just thought they seem related enough to link them.

**Comment by xealot** [comment]
I am seeing a resolve guard invoked twice on navigation to a component that has a resolve guard . 

Angular 2.0.0 final.

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/commit/091c390032130c7a281cf051fc8c134225df7be9

**Comment by skgyan** [comment]
Requesting for pointing me to the solution of this issue, spent couple of hours but couldn't reach to any example or code which clearly states implementation.
