### ISSUE TITLE
NgModule recursive bug. Unexpected value 'undefined' imported by the module

### ISSUE THREAD

**Issue by TheSaturn** [angular/angular#11522]
**I'm submitting a ...**  (check one with "x")

```
[ x] bug report => search github for a similar issue or PR before submitting
```

**Reproduction of the problem**
http://plnkr.co/edit/JbBkux3jxBHNxdr9uvNV?p=preview

I created two components, wrap them as modules, and add each other to imports.
It is not working also without even add their selectors to template.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6
- **Browser:** [all ] 
- **Language:** [ TypeScript ]

**Comment by zoechi** [comment]
You have a cycle `Component1Module` imports `Component2Module` imports `Component1Module`

- https://angular.io/docs/ts/latest/guide/ngmodule.html
- https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html
- https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html

**Comment by TheSaturn** [comment]
@zoechi and what is bad? I want to use component1 as root, which can include component2 and component2 have some component1. And I also can use component2 without component1 as root. This is what I need.

Why do you send me thouse links? Nothing usefull on them (search by keywords 'cycle', 'recurs')

**Comment by zoechi** [comment]
@TheSaturn the links were for @vicb s question about if there are docs.
Sorry, for not being more clear.

**Comment by tdinar** [comment]
I am having the same error, and it happens when I add new files to my source directory.

**Comment by DzmitryShylovich** [comment]
@tdinar did u restart your dev server? do u use index.ts files?

**Comment by DzmitryShylovich** [comment]
@vicb I think this can be closed

**Comment by tdinar** [comment]
no, I am not using index.ts, cause originally it did not work for me with Angular2 and ngModule. This error was very persistent. I reckoned to importing classes directly from hosts (ts files) and then declaring them with ngModule. I have read that it has something to do with cyclic inheritance. I have removed the import of the newly added file from the app.module and ngModule declarations, now it works when I import it somewhere else. Would you explain why cyclic inheritance would not work with webpack if you are aware of the issue. Your feedback is appreciated. thanks.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource close this one?
