### ISSUE TITLE
templateCache bug

### ISSUE THREAD

**Issue by chrismagri** [angular/angular#11526]
**I'm submitting a bug with regards to the `RESOURCE_CACHE_PROVIDER`  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I am currently having an issue with unit testing template url in RC6.

I have my karma setup as following. 
Note: I am also using karma-ng-html2js-preprocessor to load templateCache

```
TestBed.initTestEnvironment(
	BrowserDynamicTestingModule,
	platformBrowserDynamicTesting(RESOURCE_CACHE_PROVIDER)
);
```
When i try to test a component that has a template url inside.. example:

```
	TestBed.compileComponents().then(() => {
				let component = TestBed.createComponent(SkeletonComponent);
				component.detectChanges();
				let element = component.debugElement.nativeElement.querySelector("h1");
				expect(element.outerText).toContain("Sample");
			});
```
I get: `Failed to load sample.component.html`. I also checked angular code and it seems that `CachedResourceLoader` is never hit but it's using the `ResourceLoaderImpl`

**Expected behavior**
The expected behavior is that the CachedResourceLoader is triggered since i'm providing the `RESOURCE_CACHE_PROVIDER` as part of the initial setup

**Please tell us about your environment:**
Packages i'm using:
- karma
- jasmine
- system js
- karma-typescript-preprocessor
- karma-ng-html2js-preprocessor

**Angular version:** 2.0.0-rc.6

**Browser:** all
 
**Language:** Typescript

**Comment by IgorMinar** [comment]
RESOURCE_CACHE_PROVIDER should be provided to `TestBed.configureCompiler` and not to `initTestEnvironment`

**Comment by chrismagri** [comment]
you mean part of the `initTestEnvironment`? if so how it should be specified?

**Comment by chrismagri** [comment]
working thanks!
