### ISSUE TITLE
Error while using HTTP Post request

### ISSUE THREAD

**Issue by muthyas** [angular/angular#11536]
**Below is a service I've created in Angular2.**

@Injectable()
export class PresenceService {    
    private zoomListUrl = 'https://api.zoom.us/v1/group/list';
    private headers = new Headers({'Content-Type': 'application/json'});
    private body = 'api_key=odfdKAJDFDkskdfjdfk&api_secret=sdlkfdsjfALDFKDJFckdfkdfjdkslakjslaskfjd&data_type=JSON';

    constructor(private http: Http) { }

    list(): Promise<Users[]> {
        return this.http
            .post(this.zoomListUrl, JSON.stringify({ body: this.body }), { headers: this.headers })
            .toPromise()
            .then(res => res.json().data as Users[])
            .catch(this.handleError);
    }

**Here's the error I get while inspection in Safari/Mac**

EXCEPTION: Error in app/details/app.component.html:24:64
ORIGINAL EXCEPTION: TypeError: undefined is not an object (evaluating 'collection')
ORIGINAL STACKTRACE:
parseId
handleRequest
createConnection
httpRequest
list
onClick
_handle_click_19_0
[native code]

invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:332:34
onInvoke
invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:331:43
runGuarded@http://localhost:3000/node_modules/zone.js/dist/zone.js:239:54
invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:365:43
runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:265:58
invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:433:41
ERROR CONTEXT:
[object Object]

Appreciate any pointers in using above HTTP Post request and parsing the received data using JSON object.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
