### ISSUE TITLE
[Proposal] Support style binding

### ISSUE THREAD

**Issue by wesleycho** [angular/angular#1153]
Sometimes absolute positioning must be used to accomplish building some UI components, or color theming is necessary.

It would be hugely convenient for some of these cases to support binding via `[style]` to bind to the style attribute in a similar fashion as implemented in #1148 for classes, i.e.
<pre>
&lt;div [style]="{color: color.primary}"&gt;...&lt;/div&gt;
</pre>

**Comment by pkozlowski-opensource** [comment]
@wesleycho yes, this will happen. I'm just waiting for the review of #1148.
