### ISSUE TITLE
HTML5 Datalist `number` is not a known property

### ISSUE THREAD

**Issue by amcdnl** [angular/angular#11539]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When implementing a datalist on a range input that should represent this in vanilla html:

```
<input type="range" value="0" min="0" max="100" list="number" />
<datalist id="number">
  <option>10</option> 
  <option>15</option> 
  <option>30</option> 
  <option>50</option> 
  <option>90</option> 
</datalist>
```

in my template I do the following:

```
<div>
      <input
        type="range"
        [id]="id"
        [list]="id + '-list'"
        [(ngModel)]="value"
        [min]="min"
        [max]="max"
        [step]="step"
        (input)="changed($event)"
        (change)="changed($event)"
      />
      <datalist [id]="id + '-list'">
      	<option>0</option>
      	<option>20</option>
      	<option>40</option>
      	<option>60</option>
      	<option>80</option>
      	<option>100</option>
      </datalist>

    </div>
```

I get the following error:

```
Can't bind to 'list' since it isn't a known property of 'input'. ("
        type="range"
        [id]="id"
        [ERROR ->][list]="id + '-list'"
        [(ngModel)]="value"
        [min]="min"
```

I realize that `datalist` is not fully implemented in all browsers ( aka not safari ) - http://caniuse.com/#search=datalist but in the browsers that it is present I would expect it to minimally just work and not error. Additionally `orient` does not work either.

**Please tell us about your environment:**
OSX, Chrome, Webpack

* **Angular version:** 2.0.0-rc.6
* **Browser:** Chrome
* **Language:** ALL

**Comment by ericmartinezr** [comment]
Have you tried with `[attr.list]` instead? Your error message points to the input element, not datalist.

**Comment by vicb** [comment]
I believe both `input` and `orient` are attributes... oops @ericmartinezr was faster !

**Comment by amcdnl** [comment]
Using `attr` was the trick! Thanks @ericcarraway !!
