### ISSUE TITLE
RC6 migration issue : main.t not compile.

### ISSUE THREAD

**Issue by Podkekette** [angular/angular#11537]
[x] bug report => search github for a similar issue or PR before submitting

**Current behavior** 
I did the RC6 migration and crash

**Expected behavior**
 The app should run normaly.
*Please tell us about your environment:**
Windows 10, VS2015, TS2.0, Angular2 Rc6

Angular version:** 2.0.0-rc.6

Bug on chrome, Edge...
 
* **Language:** [all | TypeScript2.0 | ES5]
 
* **Node (for AoT issues):** `node --version` = 6.2.2   

Hi guys,

I did the migration from rc5 to rc6. After a cache cleaning and a rebuild, the app doesn't run. I didn't change anything, just the RC6 changes...

I don't know why but all my JS files are compiled expect one : main.ts

Thx !

![xhrerror](https://cloud.githubusercontent.com/assets/12861710/18440436/6834675a-7909-11e6-8999-bafd1a247091.PNG)

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
