### ISSUE TITLE
Option for the compiler to ignore Whitespace

### ISSUE THREAD

**Issue by SmaugTheGreat** [angular/angular#11533]
```
[ ] bug report
[x] feature request
[ ] support request
```

When working with Angular 2, it's a good idea to minify your templates. Using seperate files for templates, this usually isn't such a big issue, since you can minify them in your build tool. However, if you decide to use inline-templates instead (which are very useful especially for smaller components), this task becomes very difficult, as you'd need to write a custom build tool that detects template strings etc.

The problem is that this code: 

```
@Component({
    template: `
<div>
    <ul>
        <li>This is some Component.</li>
    </ul>
</div>`
})
export class OtherComponent {

}
```

gets compiled into something like this:
```
  var parentRenderNode = self.renderer.createViewRoot(self.declarationAppElement.nativeElement);
  self._text_0 = self.renderer.createText(parentRenderNode,'\n',self.debug(0,0,0));
  self._el_1 = self.renderer.createElement(parentRenderNode,'div',self.debug(1,1,0));
  self._text_2 = self.renderer.createText(self._el_1,'\n    ',self.debug(2,1,5));
  self._el_3 = self.renderer.createElement(self._el_1,'ul',self.debug(3,2,4));
  self._text_4 = self.renderer.createText(self._el_3,'\n        ',self.debug(4,2,8));
  self._el_5 = self.renderer.createElement(self._el_3,'li',self.debug(5,3,8));
  self._text_6 = self.renderer.createText(self._el_5,'This is some Component.',self.debug(6,3,12));
  self._text_7 = self.renderer.createText(self._el_3,'\n    ',self.debug(7,3,40));
  self._text_8 = self.renderer.createText(self._el_1,'\n',self.debug(8,4,9));
```

As you can see, it creates a lot of unwanted text-nodes.

An option for the compiler to ignore these whitespace text nodes would be a great thing I believe.

**Comment by vicb** [comment]
Templates are html.
This is how ws should be handled.

**Comment by pkozlowski-opensource** [comment]
I think that @tbosch had some ideas on stripping ws from generated code but for now HTML minify is the best we can get.

**Comment by SmaugTheGreat** [comment]
@vicb no, templates are definitely not HTML, and they are not compatible with most HTML minfiers without a lot of custom options. The templates are embedded in a Javascript string, and this gives it a disadvantage over JSX/TSX where they are actual objects instead of strings.

**Comment by vicb** [comment]
> templates are definitely not HTML

the only difference should be case, right ?

> The templates are embedded in a Javascript string, and this gives it a disadvantage over JSX/TSX where they are actual objects instead of strings.

IMO "disadvantage" depends on your POV. I know close to nothing about JSX but I was under the impression that JSX gets transpiled to javascript. There is no reason why you could not use JSX in angular and transpile it (that would be a different transpiler).
