### ISSUE TITLE
Forms: combining reactive and declarative approaches

### ISSUE THREAD

**Issue by kemsky** [angular/angular#11531]
**I'm submitting a ...**  (check one with "x")

```
[x] feature request
```

**Current behavior** 
Currently we have two ways to work with forms: 

1) Declarative with `ngModel`:

```
//user.component.html:
<form>
   <input name="name" type="text" [ngModel]="user?.name" (ngModelChange)="user==null || user.name=$event" required/>
</form>

//user.component.ts:
this.user = user;
```

You can clearly see that it can be quite verbose. Name has to be specified two or three times, elvis operator does not work with assignments. This example is simplified, see how ugly it could be:

```
<div class="input" label="La Carte Attorney Confirmed Claim Task Set: " name="laCarteAttorneyConfirmedClaimTaskSet" type="search" [ngModel]="department?.laCarteAttorneyConfirmedClaimTaskSet" (ngModelChange)="department==null || department.laCarteAttorneyConfirmedClaimTaskSet=$event" [dataProvider]="claim" labelField="name" trackBy="id"></div>
```

2) Reactive, manually building `FormGroup`:

```
//user.component.html:
<form [formGroup]="group">
   <input formControlName="name" type="text" />
</form>

//user.component.ts:
public group:FormGroup;

this.group = this.createFormGroup();

createFormGroup() {
    let group: any = {};
    group['name'] = new FormControl('', Validators.required);
    return new FormGroup(group);
}

group.updateValue(user);
```

It is even more verbose - name has to be specified twice, most of time in two separate files, `FormGroup` is created manually. This is particularly annoying  when form has many inputs.

**Expected behavior**

Can't we take best from both? We already have all necessary information to create `FormGroup` from markup.

```
//user.component.html:
<form>
   <input formControlName="name" type="text" required/>
</form>

//user.component.ts:
ViewChild(FormGroupDirective)
private group:FormGroupDirective;

group.updateValue(user);
```

This is much cleaner, shorter, less error prone.

**Comment by jmcclanahan** [comment]
Have you tried using FormBuilder? It's pretty succinct.
```
// user.component.html
<form [formGroup]="form">
   <input formControlName="firstName" type="text" required/>
   <input formControlName="lastName" type="text" />
</form>

// user.component.ts
form: FormGroup;

constructor(fb: FormBuilder) {
  this.form = fb.group({
    firstName: ['', Validators.required],
    lastName: ''
  });
}
```
[FormBuilder Docs](https://angular.io/docs/ts/latest/api/forms/index/FormBuilder-class.html)

**Comment by kemsky** [comment]
You can see that `FormBuilder` still requires property names to be specified twice, so it does not make big difference how you build `FormGroup`. It is acceptable if you have few fields, but there are cases with 20-30 inputs.

**Comment by aluanhaddad** [comment]
Nether API is intuitive. Model driven style many things have to be specified in both TypeScript and markup. Even worse, the APIs are abysmally typed, with `any` and `any[]` all over the place, you don't even get good tooling.

Angular 1.x had amazing libraries like angular-formly which were elegant, powerful, simple, and DRY. Why not use the proven ideas from libraries that we know do this job exceptionally well

**Comment by mohammedzamakhan** [comment]
Angular 2 has amazing libraries too 😄 

Try [ng2-formly](https://github.com/formly-js/ng2-formly/) ❇️ 🌟 😎

**Comment by kara** [comment]
There seem to be a few issues brought up here: 

1) Two-way binding doesn't support elvis operators

Two-way binding is something that is controlled on the compiler level. There is an existing issue here to track this request: https://github.com/angular/angular/issues/7697 

2)  Combination of reactive/template-driven approaches

At this point, it's not likely that we will change the forms API syntax quite this drastically because it would break a lot of applications and probably confuse a lot of people to combine the two existing modules in a different way.

That said, from your example code in "expected behavior", it looks like you want the utility of reactive forms, but would rather create your `FormGroup` declaratively in the template?  You can achieve something similar by creating a template-driven form, then just injecting the `NgForm` directive. From there, you have access to the `FormGroup` and can call all the same methods as you can with reactive.

**Comment by kemsky** [comment]
I do realize that it is impossible to improve forms module without breaking all existing apps, but I hope that this will be taken into consideration when new forms module will be created.

@kara, regarding #7697, it is 1,5 years old, do you have any plans or estimations?

**Comment by aluanhaddad** [comment]
@kemsky despite @mohammedzamakhan odd behavior of upvoting his own posts 🐙, ng2-formly was far beyond either model or template driven forms the last time I looked. I would check it out.
