### ISSUE TITLE
Programatically setting ([ngModel]) property assigned to a <select> tag does not set the selected attribute on the proper <option> tag

### ISSUE THREAD

**Issue by jbanass** [angular/angular#11545]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

With <select> tags using [(ngModel)] and <option>'s within using [ngValue] to store objects, updating the ([ngModel]) property by assigning it from a global service does not apply the ng-reflect-selected attribute to the proper <option> tag, leaving a blank <select> dropdown in Chrome, or the first <option> in the <select> selected in Firefox/IE/Edge.

**Expected behavior**

The <select> tag would utilize the [(ngModel)] property's current value to apply the ng-reflect-selected attribute to the corresponding <option>, or to the first <option> in the list if undefined/null.

**Reproduction of the problem**
http://plnkr.co/edit/gas8ILDqex5pHNznZWmS?p=info

**What is the motivation / use case for changing the behavior?**
We have a default owner dropdown that users access between them logging in and gaining access to the system. Throughout a typical usage scenario in our app, a user can change their default owner, going back to the same popup they were at during logging in.

We have a global service that keeps track of the user's current owner. For the sake of usability, when the component is re-initialized, we basically say "make the property assigned to the <select>'s [(ngModel)] attribute be what our global service currently has". Unfortunately, Chrome leaves a blank <select>, and FireFox/IE/Edge have the first option in the select selected by default.

We find that the current behavior is not only inconsistent between browsers, but lacking in usability for our current use case, and very likely many more to come.

**Please tell us about your environment:**

OS: Windows 10 Enterprise
Package manager: NPM 3.10.3
Server: IIS Express

* **Angular version:** 2.0.0-rc.6

* **Browser:** [Chrome 53.0.2785.101 m | Firefox 43.0.1 | Edge 25.10586.0.0 ]

 
* **Language:** TypeScript 1.8.10

**Comment by zoechi** [comment]
Setting attributes means modifying the DOM which has usually a performance penalty and should be avoided. 

If you really need it you can set it yourself
```html
<option *ngFor="let owner of ownersArr" [ngValue]="owner" [attr.selected]="owner == selectedOwner ? true : null">{{owner?.name}}</option>
```

**Comment by jbanass** [comment]
When that is done, however, the problem still persists on both Chrome and Firefox. There is no option selected, nor is the previous value chosen the default selected option.

See the modifed Plunker here: http://plnkr.co/edit/gas8ILDqex5pHNznZWmS?p=preview

**Comment by zoechi** [comment]
The Plunker doesn't work for me 
```
zone.js:461 Unhandled Promise rejection: Zone.assertZonePatched is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Zone.assertZonePatched is not a function(…)consoleError @ zone.js:461
zone.js:463 Error: Uncaught (in promise): TypeError: Zone.assertZonePatched is not a function(…)
```

**Comment by jbanass** [comment]
Looks like peer dependency updates broke the Plunker since Angular is at RC7. Updated the Plunker.

http://plnkr.co/edit/gas8ILDqex5pHNznZWmS?p=preview

**Comment by vicb** [comment]
```
zone.js:461 Unhandled Promise rejection: Zone.assertZonePatched is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Zone.assertZonePatched is not a function(…)consoleError @ zone.js:461
zone.js:463 Error: Uncaught (in promise): TypeError: Zone.assertZonePatched is not a function(…)
```

was a typo in our plunker (zone should be 0.6.21 instead of 0.6.12) easily fixed. sorry for the inconvenience.

**Comment by zoechi** [comment]
You didn't use the code I posted. If you set `attr.selected` to `false` it still has the `selected` attribute. It needs to be set to `null` to get removed. If you want a value to be selected by default, assign the value to `selectedOwner` and `ngModel` takes care.

**Comment by jbanass** [comment]
Apologies. Plunk was updated to include the full expression you listed. The behavior is still occurring. It does indeed mark which option is selected when you click the dropdown and select an option, but once you click "Accept", then "Hide Dropdown", and finally "Show Dropdown", the previously selected option does not have the ```selected``` attribute, despite us setting ```selectedOwner``` to the previous owner.

**Comment by zoechi** [comment]
I still have troubles to understand what the problem is. If you hide and unhide it you effectively destroy and re-create your `dropdown` component and `selectedOwner` that stores the value you selected previously is reset to `null`. Therefore it's expected that the dropdown doesn't show a value.

If you change the constructor to
```
  constructor(private _ownerService: OwnerService) {
    this.ownersArr = this._ownerService.getOwners();
    this.selectedOwner = this.ownersArr[0];
  }
```
then you should get what you want and you don't need to bother about the `selected` attribute at all (except you need it for other purposes which is what I assumed)

**Comment by jbanass** [comment]
Correct, since the ```dropdown``` component is destroyed, ```selectedOwner``` is set to null.

However, in the Plunker, we have the following service provided in ```AppModule```

```
import {Owner} from './owner';

export class OwnerService {
  owners: Array<Owner> = new Array<Owner>();
  currentOwner: Owner = null;
  
  getOwners() : Array<Owner> {
    this.owners = new Array<Owner>();
    
    var ownerA: Owner = new Owner();
    
    var ownerB: Owner = new Owner();
    
    ownerA.code = 'A';
    ownerA.name = 'Owner A';
    ownerB.code = 'B';
    ownerB.name = 'Owner B';
    
    this.owners.push(ownerA);
    this.owners.push(ownerB);
    
    return this.owners;
  }
  
  setCurrentOwner(owner: Owner){
    this.currentOwner = owner;
  }
  
  getCurrentOwner() : Owner {
    return this.currentOwner;
  }
}
```

Since this service is provided by ```AppModule```, it retains what the last chosen owner was. When we show our ```dropdown``` component again, it is reconstructed, and we assign ```selectedOwner``` as follows:

```
export class Dropdown {
  ownersArr: Array<Owner> = new Array<Owner>();
  selectedOwner: Owner;
  @Output() event: EventEmitter<Owner> = new EventEmitter<Owner>();
  
  constructor(private _ownerService: OwnerService) {
    this.ownersArr = this._ownerService.getOwners();
    
  }
  
  ngAfterContentInit() {
    this.selectedOwner = this._ownerService.getCurrentOwner();
    console.log("Previously selected owner: ", this.selectedOwner)
  }
  
  OwnerSubmit() {
    console.log("sending new owner", this.selectedOwner);
    this.event.emit(this.selectedOwner);
  }
}
```

We obtain the previously chosen owner and assign it to ```selectedOwner```. From what you're saying, ```ngModule``` should pick up on this change and apply the ```selected``` attribute to the proper ```option```, but it is not doing so. When the user selects an owner from the options and clicks "Accept", we call ```OwnerSubmit()```, which emits the owner back to ```App```. The function ```OwnerSelected(event: Owner)``` captures the emitted event.

```
OwnerSelected(event: Owner) {
    this.owner = event;
    this._ownerService.setCurrentOwner(this.owner);
  }
```

So essentially:

1. User is shown ```dropdown```
2. User selects an owner, and clicks "Accept"
3. User then clicks "Hide Dropdown", destroying ```dropdown```, however, ```App``` and ```OwnerService``` maintains the previously chosen owner
4. User clicks "Show Dropdown", reconstructing ```dropdown```
5. in ```ngAfterContentInit()```, we assign ```selectedOwner``` to the previous owner via injected ```OwnerService```
6. The ```select``` should show the previously chosen owner by default, but it doesn't.

**Comment by jbanass** [comment]
Yes, once I update ```OwnerService``` to return the array if it is already populated, it properly selects the previously chosen owner.

```OwnerService.getOwners()``` now looks like this:

```
getOwners() : Array<Owner> {
    
    if (this.owners.length > 0) return  this.owners;
    
    this.owners = new Array<Owner>();
    
    var ownerA: Owner = new Owner();
    
    var ownerB: Owner = new Owner();
    
    ownerA.code = 'A';
    ownerA.name = 'Owner A';
    ownerB.code = 'B';
    ownerB.name = 'Owner B';
    
    this.owners.push(ownerA);
    this.owners.push(ownerB);
    
    return this.owners;
  }
```
