### ISSUE TITLE
JIT compiler does not complain if a non existent Output (EventEmitter) is bound to from template

### ISSUE THREAD

**Issue by born2net** [angular/angular#11540]
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
<MyComp (myNonExistentEvent)="foo($event)"/>
no error is generated

**Expected behavior**
expect JIT or AOT compiler to through an error as no EventEmitetr / output exist named myNonExistentEvent on ```<MyComp/>```

Regards,

Sean
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate

**Comment by vicb** [comment]
We currently do not validate event names (ie to discriminate DOM events vs ng events).
That something we have in our backlog

**Comment by born2net** [comment]
got it, tx!
as long as it is in the todo list :)
regards
