### ISSUE TITLE
404: /base/jspm_packages/npm/@angular/platform-browser-dynamic@2.0.0-rc.6/testing.js

### ISSUE THREAD

**Issue by chendachao** [angular/angular#11558]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

It always throws 404 error of UT after I upgrade to rc 6 from rc 4. I use `angular rc 4 + jspm + karma`

**Expected behavior**

Except it could run the test as with rc 4

**Reproduction of the problem**

Here is the [Demo](https://github.com/chendachao/yeoman/tree/dev-angular-rc6/hello)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

win10, webstorm, npm + jspm,

* **Angular version:** 2.0.0-rc.X

rc 6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 
 
* **Node (for AoT issues):** `node --version` =

**Comment by chendachao** [comment]
I just got another similar issue which I think may caused by a same block. 
[another demo](https://github.com/chendachao/angular2/tree/rc6-jspm/quickstart/angular2-quickstart)

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
