### ISSUE TITLE
rc.7 UMDs labelled "v0.0.0-placeholder"

### ISSUE THREAD

**Issue by kylecordes** [angular/angular#11557]
Here is the diff of the first few lines of the RC7 UMDs:

```
 /**
- * @license Angular v2.0.0-rc.6
+ * @license AngularJS v0.0.0-PLACEHOLDER
  * (c) 2010-2016 Google, Inc. https://angular.io/
  * License: MIT
  */
```

Looks like something broke in the release labelled automation.

**Comment by vicb** [comment]
Something... or someone.
I indeed tried to fix something in your publishing script.
Will take a look. Thanks for reporting.

**Comment by IgorMinar** [comment]
whoops. my bad.

**Comment by ribizli** [comment]
Also check please on [npmjs.com](https://www.npmjs.com/~angular). `core`, `common` and `compiler` are still shown to be RC6 as the latest.

**Comment by vicb** [comment]
@IgorMinar could this be closed ?

**Comment by IgorMinar** [comment]
yes.
