### ISSUE TITLE
Routing to the current route with a different route parameter doesn't work as expected.

### ISSUE THREAD

**Issue by ghostofcain** [angular/angular#11550]
[x ] bug report => search github for a similar issue or PR before submitting

Imagine this route:
{ path: 'content/:id', component: ContentComponent },

An external component navigates to this route using:
this.router.navigate(['/content', contentId]);

which works fine.

Within the ContentComponent, I would like to be able to navigate to other ContentComponents (next/previous behaviour) so within this component, I call

this.router.navigate(['/content', nextContentId]);

The URL correctly changes and the router returns true as part of the routing response promise but the component is still the same component, i.e. the ngOnInit() isn't called after the route changes and all the existing controls and variables within the ContentComponent remain the same.

Is there a way to 'force; the router to navigate to the ContentComponent, causing the component to be 
reinitialized from scratch?

Thanks,

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

dup of #9811
