### ISSUE TITLE
templateUrl and styleURL resolution inconsistent between JiT and AoT  

### ISSUE THREAD

**Issue by prkcorp** [angular/angular#11554]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
JiT compiler resolve relative templateUrl/styleURL from project root (probably index.html) while AoT resolve relative paths from Component declaration. This is a known problem according to rc7 source, directives.d.ts:

    /**
     * Specifies a template URL for an Angular component.
     *
     * NOTE: Only one of `templateUrl` or `template` can be defined per View.
     *
     * 
     */
    templateUrl?: string;

**Expected behavior**
AoT and JiT should be able to run with the same Component declaration, maybe using a bootstrap or compiler flag.

**Reproduction of the problem**

With this component and login.html file in app/ subdirectory:

    @Component({
        selector: 'my-login',
        // For AoT:
        templateUrl: './login.html'
        // For JiT: 
        templateUrl: './app/login.html'
    })

**What is the motivation / use case for changing the behavior?**
It's currently impossible to use the same source code for both JiT and AoT testing.

**Please tell us about your environment:**
Debian x64, IntelliJ, npm, npm lite / apache

* **Angular version:** 2.0.0-rc.7

* **Browser:** Chrome, Firefox
 
* **Language:** TypeScript 2.0.2 / ES5
 
* **Node (for AoT issues):** `node --version` =   4.4.7 (4.4.7~dfsg-2+b1 current debian sid version)

**Comment by imcotton** [comment]
You should read [component-relative-paths](https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html) chapter from Doc which gives you solution with `moduleId` by using **CommonJS** module, or `angular2-template-loader` with **Webpack**.

Also you could try `gulp-inline-ng2-template` with **Gulp**.

**Comment by darincardin** [comment]
What is the solution for this? We have designed a fairly large app, and in many of our components use a generic template stored in a common location. This works fine in JIT, but breaks in AOT. We will have to redesign our entire app to use AOT. I don't understand why AOT cannot behave the same as JIT.

**Comment by jasedwards** [comment]
I would also like to know the solution.  The link for component-relative-paths no longer exists.

**Comment by tytskyi** [comment]
@darincardin @jasedwards if you use `@angular/cli` then 

```typescript
@Component({
  selector: 'app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
```

see CHANGELOG: https://angular.io/guide/change-log#all-mention-of-moduleid-removed-component-relative-paths-guide-deleted-2017-03-13

Otherwise consult to the repo which you used as a starter template
