### ISSUE TITLE
ReactiveForms: Creating/Modifying FormGroup at runtime

### ISSUE THREAD

**Issue by smith64fx** [angular/angular#11559]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I want to create a form group dynamically.

So right now I define the form like this:

test.component.ts
```
      this.attributesGroup = this.formBuilder.group({
                '1': [''],
                '2': [''],
                '3': ['']
      });
```

This is my template

template.pug
```
            .form-group([formGroup]="attributesGroup", *ngFor="let attribute of (categorySelected | async)?.attributes")
              select.form-control(formControlName="{{attribute.id}}")
                option(value="{{ value.id }}", *ngFor="let value of attribute.values")
                  | {{ value.name }}
```

I want to build/change the group at runtime/async.
From the categorySelected Observable I get the attributes asynchronously, which I want to integrate into the existing formGroup. The select fields are then also updated asynchronously (already working)

So I want to create my formGroup like this.

test.component.ts
```
let attributeFilters = [];
this.categorySelected.subscribe(cat => {
      cat['attributes'].forEach(attr => {
           attributeFilters[attr['id']] = [''];
      });

      this.attributesGroup = this.formBuilder.group(attributeFilters);
});
```

Problem:
When I'm subscribing to my formModel right now, I get no updates about the changes.

```
      this.attributesGroup.valueChanges.subscribe(form => {
          console.log(form)
      });
```
This only works if I define the formGroups statically inside the code.

**Expected behavior**
I should get notified about my dynamically modified formGroup.

Is this possible?

**What is the motivation / use case for changing the behavior?**
I have attributes which are coming from the database, so I cannot set the formGroup directly in the code. I get the attributes at runtime.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by smith64fx** [comment]
Hey Guys,
I found a solution!

Using reset() and addControl()

Let's say this code here is executed async:
```
        let test = new FormControl('');
        let test2 = new FormControl('');
        this.attributesGroup.reset();
        this.attributesGroup.addControl('1', test);
        this.attributesGroup.addControl('2', test2);
```

The formGroup which I created is now not "overwritten" (Which causes loss of binding) but I just reset it and add the controls again. Works fine.

If you know a better solution (best practise), please let me know.


Greetz,
Smith

**Comment by smith64fx** [comment]
OK, 
The problem is not yet soluted 100%.

The problem is, that the old form controls, which are not used anymore, are not deleted fully.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by smith64fx** [comment]
@vicb thanks for your information.

I don't really know if this is a support or a feature request, because I could not figure out yet how to re-bind a new form group to an existing *ngFor array.

**Comment by vicb** [comment]
> I don't really know if this is a support or a feature request

Not sure either (I would have closed the issue otherwise). However you might try to solve your pb by requesting help on the mailing list. 

@kara is in charge of the form component, she'll take a deeper look at the issue when she has time for it.

**Comment by kara** [comment]
This looks like a support request. @smith64fx It looks like you need a FormArray with nested FormGroups rather than just a FormGroup (you won't be able to pass it an array). For the specifics of how to achieve this, please ask on gitter or StackOverflow, as @vicb mentioned.
