### ISSUE TITLE
DevMode vs ProdMode documentation for logging

### ISSUE THREAD

**Issue by n614cd** [angular/angular#11561]
I'm submitting a feature request for documentation

**Current behavior** 
The current cookbook and website do not provide examples or information for "production" code quality/style. Therefore I would suggest a new section under Cookbook or preferably under Developer Guide. 
First item would be to copy the suggested project structure which is mentioned in other locations but in a scattered way.
The second item I would add is how to perform client side logging in the console or remotely to a server. For console logging, after digging around, I found the isDevMode function which allows me to guard the console messages. 

If you give me a writing assignment I can provide drafts.

**What is the motivation / use case for changing the behavior?**
Save future developers time. 

* **Angular version:** 2.0.0-rc.6

* **Language:** [TypeScript]

**Comment by ericmartinezr** [comment]
The repo for the tutorials/cookbooks/dev guide is over here https://github.com/angular/angular.io

**Comment by n614cd** [comment]
Created issue in angular.io
