### ISSUE TITLE
Annotations fails with abstract error when using Traceur and forgoing Zone and System.

### ISSUE THREAD

**Issue by jrgleason** [angular/angular#1156]
I am trying to create an angular project using Traceur. Everything seems to load ok but when I add the @Component it blows up with...

Unexpected token @ (WARNING: non-Error used)

    //Loading JADE!!!!
    ....
    greeter-app
    script(src="//google.github.io/traceur-compiler/bin/traceur.js")
    script(src="//google.github.io/traceur-compiler/src/bootstrap.js")
    script(src="javascripts/es6-module-loader.src.js")
    script.
      System.paths['greeter'] = 'components/greeter/greeter.js';
      System.paths['angular2/*'] = 'angular2/*.es6'; // Angular
      System.paths['rtts_assert/*'] = 'rtts_assert/*.js'; //Runtime assertions
      System.import('greeter');

    //Component
    import {MathWiz} from 'components/math-wiz/math-wiz'
    import {Component, Template, bootstrap, Foreach} from 'angular2/angular2';
    import {bind} from 'angular2/di';
    @Component({
       selector: 'greeter-app'
    });
    class Greeter {
      constructor(message) {
        this.wiz = new MathWiz();
      }
      greet() {
        var element = document.querySelector('#message');
        element.innerHTML = this.wiz.welcomeText;
      }
    };
    bootstrap(Greeter);

**Comment by jrgleason** [comment]
Looks like in the example it is not using AtScript either...

    Object.defineProperty(HelloCmp, "annotations", {get: function() {
      return [new Component({
        selector: 'hello-app',
        services: [GreetingService]
      }), new Template({
        inline: `<div class="greeting">{{greeting}} <span red>world</span>!</div>
           <button class="changeButton" (click)="changeGreeting()">change greeting</button>`,
        directives: [RedDec]
      })];
    }});

**Comment by robwormald** [comment]
if you're dynamically loading AtScript/non-standard JS, you need to set the configuration:

```js
System.config({
  traceurOptions: {
    annotations: true,
    types: true,
    memberVariables: true
  }
});
System.import('whatever').then(....

```

**Comment by jrgleason** [comment]
Thanks tried that now getting...

    Potentially unhandled rejection [3] Error loading "greeter" at http://localhost:3000/components/greeter/greeter.js
    http://localhost:3000/components/greeter/greeter.js:10:1: Unsupported annotated expression (WARNING: non-Error used)

**Comment by robwormald** [comment]
@jrgleason so thoughts:

any component needs to have an @Template and an @Component annotation, which is probably why yours is complaining. 

Looking at your paste, I'm not sure what you're trying to accomplish exactly. You've got the <greeter-app> element in your index.html, but no template to 'replace' it with. 

Check out http://plnkr.co/edit/OskdcxNsgBa2NKWQGloH?p=preview for a basic demo. 

In the future, you might try asking in the gitter room : https://gitter.im/angular/angular - we can help you review and figure out what you're doing before opening up an issue.

**Comment by jrgleason** [comment]
I will take a look, I did actually put a Template in (with inline) I just didn't add it to the code because I got the same error either way. I added here since I was on the main branch and having issues I assumed it was something to track. Figured worst case scenario someone closes it.

As for my demo code I am currently using ng2do but that uses es6-shim instead of traceur. I will take a look at the plunker and see what I might have missed.

**Comment by jrgleason** [comment]
Ah ha I did miss something in my original post I will update.

My actual code looked like this....

    @Component({
      selector: 'greeter-app'
    }) 
   @Template({
     inline: '<h1>Test</h1>'
   }); //This is the issue

Apparently that is what happens when you accidently include a semi at the end. Very misleading message.

That mixed with adding Zone.js makes it work! Thanks for your help now I can convey this information to the masses! I am still curious as to how in the plunker you created the single JS file. Is there a gulp option?
