### ISSUE TITLE
[Bug] Animation not triggered on window.resize

### ISSUE THREAD

**Issue by Luchillo** [angular/angular#11565]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 
I have a page with a side menu, which has an animation on it's width, the item does work when i change the state variable from a click to a button that calls a function that sets the value for the state of animation, however it doesn't happen when calling the same function from an Rxjs observable triggered from an event `onresize`.

Basically i want to always close the menu when a resize event happens, may it have to be with the Observable or the resize event?

Also worth nothing i have some primeng animations in the menu that when triggered it triggers the menu closing animation held back when resizing, which makes me think that the state binding is being held due to binding to the Observable or to a window event, then when other animation happens the change detection kicks again and the animation triggers.

Here's my observable code in the constructor:
```ts
@Component({
  selector: 'app',
  encapsulation: ViewEncapsulation.None,
  styleUrls: [
    './app.style.scss'
  ],
  animations: [
    animMenuRight
  ],
  templateUrl: './app.template.html'
})
export class App {
private resizeSub:  Subscription;
  private isMenuOpen: boolean = false;

  constructor(
    public appState: AppState
  ) {
    // this.resizeSub = Observable.fromEvent(document, 'onresize')
    // .debounceTime(250)
    // .subscribe((event) => {
    //   console.log('event: ', event);
    //   this.toggleMenu(this.isMenuOpen);
    // });

    this.resizeSub = Observable.create((observer) => {
      window.onresize = (event) => observer.next(event);
    })
    .debounceTime(250)
    .subscribe((event) => {
      this.toggleMenu(true);
    });
  }
  toggleMenu(isOpen) {
    console.log('toggleMenu: ', isOpen, window.innerWidth);

    if (window.innerWidth >= 1024) {
      return this.isMenuOpen = false;
    }
    this.isMenuOpen = isOpen;
  }
}
```

Here's the template animation binding:
```html
<l-toolbar [toggleMenuValue]="isMenuOpen" (toggleMenuEvent)="toggleMenu($event)"></l-toolbar>

<div class="app-container">

  <div [@animMenuRight]='isMenuOpen' class="sidemenu">
    <p-slideMenu [model]="routes"></p-slideMenu>
  </div>
  <div class="main-content">


    <router-outlet></router-outlet>

    <!--<l-menu-overlay></l-menu-overlay>-->

  </div>
</div>
```

And here's the animation itself:
```ts
import {
  Component,
  Input,
  trigger,
  state,
  style,
  transition,
  animate
} from '@angular/core';

export var animMenuRight = trigger('animMenuRight', [
  state('true', style({
    flex: '0 1 0px'
  })),
  state('false', style({
    flex: '0 0 150px'
  })),
  transition('* => *', animate('250ms ease'))
]);
```

**Expected behavior**
I expect to click a button and the menu should toggle between open-close, which does work ok,
i expect the resize of the window to trigger the same behaviour but it doesn't.

**Reproduction of the problem**
This is my repo, it's a public repo so it should be easy to clone and run:
https://github.com/Luchillo/Luchillo-tech-showcase

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6

* **Browser:** [all | Chrome 53 | Safari 9.1.1] 
I've tested in chrome 53 and Safari 9.1.1 both up to date, most likely this issue happens in all browsers
 
* **Language:** [all]

**Comment by kemsky** [comment]
I'm not sure but onresize events are running out of zone, so you should use `NgZone` directly to run toggle method within zone.

**Comment by ericmartinezr** [comment]
Try with pure ng2

```ts
@HostListener('window:resize') myFunc() {
   myObservable.next(true);
}
// Same as
@Component({
   host : {
      'window:resize' : 'myFunc()'
   }
})
```
As @kemsky mentioned your observable/window resize event is most likely running outside angular's zone

**Comment by Luchillo** [comment]
Then i should need to convert my observable into a Subject in order to be able to emit without being inside the `create` function?

**Comment by Luchillo** [comment]
OMG it works!! after changing to the Subject it works as expected, thanks.

Now i will look in to the style guide to see where should i put this host listener, is a property? a function? should it go right under Outputs and inputs in the top?

**Comment by vicb** [comment]
if you look at @ericmartinezr comment above, you will see that it is a decorator. As such put it right above your method:

```ts
@HostListener('window:resize') myFunc() {
   myObservable.next(true);
}
```

**Comment by Luchillo** [comment]
I can tell that much, what i ask is that, for example, the style guide says Inputs and Outputs should be declared on top of your Class, thus is easier to spot the Class's Inputs and Outputs.

However since this one is a decorated function idk if it should be put under the constructor, above it or right below the Inputs and Outputs section inside the class.

**Comment by vicb** [comment]
??

https://angular.io/docs/ts/latest/guide/style-guide.html#!#05-12

**Comment by Luchillo** [comment]
I already scanned the style guide, but didn't saw nothing about `Host Listeners` nor `Anotated Functions`.

**Comment by zoechi** [comment]
> Do use `@Input` and `@Output` instead of the `inputs` and `outputs`

I guess it's the same for `@HostBinding()` `@HostListener()`

**Comment by Luchillo** [comment]
Then i should put it in the top of the class above the constructor and any of the not annotated properties?
