### ISSUE TITLE
bootstrapping several elements with same selector

### ISSUE THREAD

**Issue by ArnaudBertrand** [angular/angular#11564]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior** 
Having several times an element in the DOM tree with the selector associated to a component will only bootstrap the first DOM node found in the tree.

**Expected behavior**
All nodes matching the correct selector should be bootstrapped not only the first appearance in the tree.

**Reproduction of the problem**
[http://plnkr.co/edit/bLCsmIRG7pkMu6GohOxS?p=preview](http://plnkr.co/edit/bLCsmIRG7pkMu6GohOxS?p=preview)

**What is the motivation / use case for changing the behavior?**
I need to bootstrap several time the same component on my page.
(For my special case I am bootstrapping 2 time the same ui-element that are at 2 different places in the DOM tree)

* **Angular version:** 2.0.0-rc.6
* **Browser:** Chrome  
* **Language:** TypeScript

**Comment by vicb** [comment]
Duplicate.
