### ISSUE TITLE
[RfC] Stop with Release Candidates and breaking changes

### ISSUE THREAD

**Issue by unsafecode** [angular/angular#11569]
**I'm submitting a ...**
```
[ ] bug report
[X] feature request
[ ] support request
```

**Current behavior** 
Definitely not wanting to be critical, but latest RCs are coming out at high rate, always featuring several breaking changes.

**Expected behavior**
Whilst I do know very well all the efforts to reach a final, stable release, changes required to update should really be minimal, and well documented. Most of us are still struggling to apply fixes from RC5 to RC6 (see issues below), as there were more than minimal changes, and today RC7 comes out - which wasn't even in this repo's milestones. This also makes it hard to plan for next releases and subsequent updates.

**Reproduction of the problem**
For instance #11567, #11379, #11271 

**What is the motivation / use case for changing the behavior?**
Most people are already building apps with Angular2, and code samples/SO Questions/blog posts get obsolete **really fast** - matter of days lately. This ultimately makes developing a lot harder, since you are never sure of which version the content/solution/answer refers to.

**In the end, this my personal viewpoint, but I'd like to request comments on this topic.**

**Comment by kukicado** [comment]
I can understand the pain of trying to keep up with the latest changes. I don't see a problem with the RC releases as they come out every 2-3 weeks and as the team is getting closer to shipping 2.0 final these types of changes are common. Better to break things before final release than introduce a bunch of breaking changes post 2.0. 

I would suggest sticking to whatever RC you are currently on unless you absolutely need the subsequent RC's until the final release is out. Then when 2.0 final is out, upgrade everything once.

**Comment by mdonato7** [comment]
Looking at recent RC's, specifically NgModule which was a change in **core design paradigms** this late into the game, it's clear that angular 2 was rushed into RC. My team still hasn't recovered from this change beyond having a 600 line EverythingModule in the root of the application.

I recommend you follow @kukicado 's suggestion and just stop updating until angular is more stable, or plan on allocating about 50% of you time to keeping angular working and up to date.

I know I sound really critical - I like angular 2 a lot and the team has created a wonderful framework. It's just frustrating to have your application break on a weekly basis this late into the "RC" cycle.

**Comment by CaptainCodeman** [comment]
I rode the train from mid Alpha to RC4 but got tired of the endless churn and fragile functionality. It's not like it was helping me build a cutting edge, fast loading app to make it worthwhile so I bit the "sunk cost" bullet and found a better framework to use and am now spending more time on my app. The other choices are either stagnate on a dead version or sink even more time on endless upgrades for zero benefit.

I've completely lost trust in Angular.

> **What does 'beta' mean?**

> Beta means we're now confident that most developers can be successful building large applications using Angular 2. 

> Through developer preview and alpha we've worked closely with several large projects here at Google including AdWords, GreenTea (Google's internal CRM system), and Google Fiber.  In fact, just a few weeks ago we saw Google Fiber launch on their new Angular 2 code base.

> Externally, we've worked closely with several other teams integrating with Angular 2 including Ionic Framework on Ionic 2, Telerik on NativeScript, Rangle.io on Batarangle, and many others.

> **_We've incorporated the majority of feedback from these teams that would create breaking changes._**  Given this, we're looking forward to other teams developing in earnest and telling us how we can help.

15 December, 2015
http://angularjs.blogspot.ca/2015/12/angular-2-beta.html

9 Months ago.

**Comment by naomiblack** [comment]
Hey all -- thanks for the comments. I appreciate and understand your concerns regarding the many RCs we've needed to prepare for Angular 2.0 final. 

We agree that it's important for developers to have a stable, validated, reliable release to depend on: this is our intent for final.

I'm locking and closing this issue, not because it isn't important, but because we are already working to deliver 2.0 final ASAP.
