### ISSUE TITLE
TypeError: optionElement[0].hasAttribute is not a function when trying to remove an option of a select

### ISSUE THREAD

**Issue by pablomarti** [angular/angular#11571]
In a **select** I need to avoid displaying one option; for that, I do:

`angular.element('[ng-model="vm.relationship.related_person_id"] option[value="' + vm.person.id + '"]').remove();
` 
That works, and there is no problem at all, but an error message appears in the console:

> angular.self.js?body=1:13709 TypeError: optionElement[0].hasAttribute is not a function
>    at chromeHack (http://localhost:3000/dev-assets/angular/angular.self.js?body=1:30476:24)
>    at self.addOption (http://localhost:3000/dev-assets/angular/angular.self.js?body=1:30560:5)
>    at self.registerOption (http://localhost:3000/dev-assets/angular/angular.self.js?body=1:30607:12)
>    at Object.<anonymous> (http://localhost:3000/dev-assets/angular/angular.self.js?body=1:30946:22)
>    at http://localhost:3000/dev-assets/angular/angular.self.js?body=1:1241:18
>    at invokeLinkFn (http://localhost:3000/dev-assets/angular/angular.self.js?body=1:9815:9)
>    at nodeLinkFn (http://localhost:3000/dev-assets/angular/angular.self.js?body=1:9216:11)
>    at compositeLinkFn (http://localhost:3000/dev-assets/angular/angular.self.js?body=1:8511:13)
>    at nodeLinkFn (http://localhost:3000/dev-assets/angular/angular.self.js?body=1:9211:24)
>    at compositeLinkFn (http://localhost:3000/dev-assets/angular/angular.self.js?body=1:8511:13)

What may be the problem?

* **Operating system:** ODX El Capitan 10.11.4
* **Angular version:** 1.5.7
* **Browser:** Chrome 52

**Comment by Fank** [comment]
this looks like a angular1 issue, but this is the repo for angular2
