### ISSUE TITLE
[upgradeAdapter] Too many template parsing errors freezes Chrome developer tools

### ISSUE THREAD

**Issue by kevindqc** [angular/angular#11575]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
We are currently migrating an angular1 app to angular2. We are using upgradeAdapter for this. We migrated our services without any problem. I started migrating an angular 1 directive to angular2 component. However, after trying to migrate one component and loading the website in Chrome, I see that the website doesn't load properly. I probably made a mistake somewhere. When I try to use the developer tools to see what is wrong, the devtool is completely frozen.

I added breakpoints to zone.js to log all task callbacks that are called. The last one that gets logged is this:

```
 function onError(e) {
        // TODO: (misko): We seem to not have a stack trace here!
        console.log(e, e.stack);
        throw e;
    }
```

This comes from upgrade.umd.js.

I added a breakpoint there to look what is in `e`. It is a parser error from my template, which is expected because it's a big-ish template (~300 lines) so I probably forgot to change some things to be compatible with angular2. 

Now the problem seems to be with this `e` exception.
If, in the console, I type:
`e.message.length`, it returns me `2353665`

If I type:
`e.stack.length`
I get
`2354890`

This is one big error!

Now, if I type this:
`e.toString()`

The developer tools are completely frozen. I imagine the freeze when I'm not manually typing in the console therefor comes from the `console.log(e, e.stack);` line.

Looking at the message property of this exception, it contains around 6500 instances of "Parser Error:".
I think maybe setting an upper bound to the number of parser errors would help? When it reaches something like 100 parser errors, the parser would just stop with a final error `Too many parsing errors, aborting` ?

**Expected behavior**

The developer tools don't freeze, making it easy to see what is the error in the template.

**Reproduction of the problem**

I can't share the code, sorry.
I was looking for an up-to-date hybrid application on plunkr so that I could just modify the template to create a bunch of errors, but I couldn't find one. If this is really needed I can try to make one if I have some time.
I added the template that gave me problems in the comment, hopefully this is enough?

**What is the motivation / use case for changing the behavior?**

This freezing makes it really hard to migrate our angular1 to angular2 templates
For now, I changed the function to this:

```
function onError(e) {
        var msg = e.message;
        // TODO: (misko): We seem to not have a stack trace here!
        console.log(msg);
        throw msg;
    }
```

So that we can use the developer tools. It freezes for 1-2 seconds because it needs to log a big string, but it's much better than unlimited freezing :)

**Please tell us about your environment:** Windows, Chrome 

- **Angular version:** 2.0.0-rc.7
  
  
- **Browser:** Chrome
  
  
- **Language:** Typescript
- **Node (for AoT issues):** `node --version` =

**Comment by kevindqc** [comment]
Also, changing 7-8 places where I had things like:
`[title]="{{translations.DrawLineTitle}}"`
to:
`[title]="translations.DrawLineTitle"`

This changed the number of lines logged from the exception.message from 24k to 300. Maybe the parser is too verbose?

I will add the template before/after my change, as well as what errors get logged

**Comment by gkalpak** [comment]
This is not really ngUpgrade-specific. Things should have improved in core since this was reported, but you are still having similar problems, please open a new issue.
