### ISSUE TITLE
Webpack warning in shadow_css.js

### ISSUE THREAD

**Issue by Simon-Briggs** [angular/angular#11584]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

See this warning in both RC6 and RC7 during my build.
Downgrading to RC5 makes the warning disappear.
Everything seems to work fine, I just have this warning.

```
WARNING in ./~/@angular/compiler/src/shadow_css.js
Cannot find SourceMap '...': Error: Can't resolve './...' in '/Users/simon/workspace/project/front/node_modules/@angular/compiler/src'
 @ ./~/@angular/compiler/src/style_compiler.js 11:0-41
 @ ./~/@angular/compiler/src/compiler.js
 @ ./~/@angular/compiler/src/index.js
 @ ./~/@angular/compiler/index.js
 @ ./~/@angular/platform-browser-dynamic/src/platform-browser-dynamic.js
 @ ./~/@angular/platform-browser-dynamic/index.js
 @ ./src/main.browser.ts
 @ multi main
```

**Expected behavior**

No warning

**Reproduction of the problem**
I have no idea what causes this. I couldn't find any references to '...' in my project. 
If you have any suggestions, I'll try and reproduce it.

**Please tell us about your environment:**
OSX

* **Angular version:** 2.0.0-rc.6 and 7 not 5

* **Browser:** all
 
* **Language:** TypeScript 2.0
 
* **Node (for AoT issues):** `node --version` =   
node: 4.4.7,
webpack: "2.1.0-beta.21",
webpack-dev-server: "2.1.0-beta.2",

**Comment by vicb** [comment]
ok, got it, due to a comment in the source code `// all comments except inline source mapping ("/* #sourceMappingURL= ... */")`

will submit a PR asap
