### ISSUE TITLE
input inside a form disabled or not should not affect the form value.

### ISSUE THREAD

**Issue by huyaxiong** [angular/angular#11591]
```
this.passwordResetForm = this.formBuilder.group({
            email: ['', [Validators.required, Validators.minLength(6), Validators.maxLength(18), Validators.pattern(this.authService.emailReg)]],
            password: ['', [Validators.required, Validators.minLength(6), Validators.maxLength(18)]],
            captcha: ['', [Validators.required, Validators.pattern(this.authService.captchaReg)]]
        });

// should be {email: 'xx',password'xx',captcha:'xxx'}
this.passwordResetForm.value

// but if i add this, passwordResetForm.value would not contain email property
this.passwordResetForm.controls['email'].disable(true);
```

Is it a bug?Or Is there another way to disable an input and even though I can still get this input value?

**Comment by pkozlowski-opensource** [comment]
> Is it a bug?

I don't think so. At least not if we want to be consistent with HTML5 forms where disabled forms are not submitted. 

> Or Is there another way to disable an input and even though I can still get this input value?

Did you try `readonly` instead of `disabled`?

**Comment by kemsky** [comment]
Sometimes forms can have switch that enables or disables part of the form and you clearly do not want to loose user input after switching twice. It means that data is not used but it is still there. This is how it works in my application. In general disabled/readonly are UI states which should not change data.

I was thinking about it recently, there two completely different use cases: forms that are used to submit data and forms that are used to show and edit data (you have to use the same controls). You can't just lock it in one way. The same applies to validation.

**Comment by pkozlowski-opensource** [comment]
> Sometimes forms can have switch that enables or disables part of the form and you clearly do not want to loose user input after switching twice. It means that data is not used but it is still there. This is how it works in my application. In general disabled/readonly are UI states which should not change data.

I don't think anyone suggests that UI state should change data. It is more of a question: should those data be retrieved by default as part of the form.

**Comment by kemsky** [comment]
If you are saving data using `group.value` it will be lost, right? The same scenario applies: switch, edit, switch, save. Not critical, but may be unexpected.

Thanks to this issue though, now i know that there is optional method `setDisabledState` :)

**Comment by kara** [comment]
@huyaxiong As @pkozlowski-opensource mentioned, disabled form controls are deliberately excluded from the aggregate value of the form to match how native forms work in the HTML5 form spec.  If you'd like to include the value of the disabled control but keep it un-editable in the UI, you have two options: 

1)  Use the `readonly` property instead

2)  Use the `getRawValue()` method. This includes disabled controls when reducing.

@kemsky When you disable a form control, you don't lose any data.  The individual form control value doesn't change. It's only omitted when the group value is reduced.  As soon as you re-enable the control, the group will re-calculate its value and include the form control once again.

See example here: http://plnkr.co/edit/M9fNdegUmeY77wJLPBsc?p=preview

**Comment by kemsky** [comment]
I was trying to say that if you are saving data using `value` then disabled fields will not be saved (i.e. json) and eventually will be lost when you leave the page.

**Comment by kara** [comment]
In that case, you should save data using `getRawValue()`.
