### ISSUE TITLE
ROUTE w/ optional params link not working

### ISSUE THREAD

**Issue by kchojhu** [angular/angular#11598]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

I'm using a routerlink with optional parameters as below
`<a [routerLink]="['route1',{paramA:'a'}]">link</a>`

This works when I actually click on the browser but the URL looks a bit weird
https://localhost/#/route1**;**paramA=a
There's a 'semicolon' instead of the '?'.

Then, I did a browser refresh to test out the deep link and I get an error
Cannot match any route: route1;paramA=a

if I change the link to 
https://localhost/#/route1?paramA=a

then it works fine.  I'm wondering if semicolon has been misplaced instead of question mark.

* **Angular version:** 2.0.0-rc.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by vicb** [comment]
It's called matrix parameters in the spec. It means that the parameters are specific to a given route segment. So ; is perfectly valid here.

Imagine you have route2 as a child of your route. They both can have a parameter with the same name. If parameters were global (after a ?) This would nor be possible.

**Comment by kchojhu** [comment]
I get what you're saying but when I refresh with below URL
https://localhost/#/route1;paramA=a

I'm getting the following error
Cannot match any route: route1;paramA=a

It's not recognizing that 'paramA=a' is parameters and not the route url

**Comment by RonNewcomb** [comment]
I'm having this issue as well.  Routes with semicolons only work once.
