### ISSUE TITLE
Disabled input seems to be re-enabled because of Validator (?)

### ISSUE THREAD

**Issue by samfrach** [angular/angular#11594]
I'm using the model driven mode for Forms.
I create my form using the FormBuilder....

    this.illnessRemarkCtrl = fb.control('', Validators.required);
    this.illnessRemarkCtrl.disable();
console.log("illnessRemarkCtrl: enabled=" + this.illnessRemarkCtrl.enabled);
This is correct, it is false ...

BUT in my component, where I use it in an *ngIf to display something (or simply display the value with {{ illnessRemarkCtrl.enabled }}), it is TRUE whereas it should be FALSE

If later on, I call programatically  this.illnessRemarkCtrl.disable(); the value displayed is FALSE, it is ok ! It's only at initialization.

What I have noticed is : if I create the control without the required validator, then it's working fine.

Very easy to reproduce...

thank you

**Comment by pkozlowski-opensource** [comment]
@samfrach could please provide a minimal plunker demonstrating the issue? We can't progress on this one without a minimal reproduce scenario as requested in the issue template.

**Comment by samfrach** [comment]
yes sorry, I was minimalist....

I've created the plunk but it works in the plunk (on my computer, comp1 is enabled).

I will upgrade to RC7 first (I'm using the angular2-webpack-starter project).

https://plnkr.co/kGwCoDylIhj3UokaLOgh

**Comment by kara** [comment]
@samfrach This sounds like a bug with disabled form controls that was fixed after RC.6. This is probably why the plunker works, but your project doesn't. If you upgrade to RC.7, it should behave as you expect. If not, please feel free to open a new issue with a repro in RC.7.

**Comment by samfrach** [comment]
yes I confirm. It's working with 2.0.0 !

thank you :)
