### ISSUE TITLE
how to stay on page when click save button

### ISSUE THREAD

**Issue by yiji** [angular/angular#11592]
**I'm submitting a ...**  (check one with "x")
```
service.ts:
  updateItem(item: Item): Promise<Item> {
    let url = `${this.itemUpdateUrl}/${item.ItemId}`;
    return this.http
      .post(url, JSON.stringify(item), {headers: this.headers})
      .toPromise()
      .then(response=>response.json() as Item)
      .catch(this.handleErrors);
}

detail.ts:
  goBack(): void {
    window.history.back();
  }

  saveItem(): void {
    this.itemservice.updateItem(this.item).then(item=> {
        console.log('test');
        alert('test');
        this.item = item;
      }
      //this.goBack();  // if comment this line will redirect to index
    );
```

**Current behavior** 

![qq 20160914155454](https://cloud.githubusercontent.com/assets/6138770/18504185/a20d394e-7a93-11e6-955e-330a7a9e70b7.png)
when i click save button if comment this.goBack() in detail.ts will redirect to index

**Expected behavior**

i want after click save button can stay on this page, have other actions

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by spock123** [comment]
@yiji  don't use window.location, instead use the Location service: 

`Location.back()`

**Comment by pkozlowski-opensource** [comment]
As @vicb pointed out this is a support request and as such doesn't belong here.
