### ISSUE TITLE
ngc should throw an error on provider like `useValue: window.foo`

### ISSUE THREAD

**Issue by sod** [angular/angular#11597]
**I'm submitting a ...**  (check one with "x")

```
[x] feature request
```

**Current behavior** 
In runtime mode, you can provide from global objects like `window` or `document` via `{provide: 'foo', useValue: window.foo}`. 

`ngc` on the other hand tries to import it. So

``` typescript
// file foo-component.ts
@Component({
    providers: [{provide: 'foo', useValue: window.foo}]
})
```

becomes:

``` typescript
// file foo-component.ngfactory.ts
/* ... */
import * as import3 from './foo-component';
/* ... */
createInternal(rootSelector:string):import2.AppElement {
    /* ... */
    this._foo_0_4 = import3.window.foo;
    /* ... */
}
```

But `window` is not exported by `foo-component.ts`. And thus this fails on execution.

**Expected behavior**

Throw an error if trying to access `window` or `document` from ngfactory, but wasn't exported. Or support `window` to be used in useValue without exporting it.

**What is the motivation / use case for changing the behavior?**

Earlier feedback that your code will fail in production.
- **Angular version:** 2.0.0-rc.6
- **Language:** [TypeScript 2.0.2]
- **Node (for AoT issues):** `node --version` = v4.5.0

**Comment by DzmitryShylovich** [comment]
@sod I got the following error during compilation
`Error at D:/Workspace/bug/src/compiled/src/app/app.module.ngfactory.ts:256:29: Property 'window' does not exist on type 'typeof "D:/Workspace/bug/src/app/app.module"'.`
can you confirm?

**Comment by sod** [comment]
I get `Error: Error encountered resolving symbol values statically. Expression form not supported` with `angular 2.4.5`. Thanks for checking, it is indeed fixed 👍
