### ISSUE TITLE
addProviders missing from rc.6/rc.7

### ISSUE THREAD

**Issue by jwerts** [angular/angular#11608]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
tsc output:
```
error TS2305: Module '"c:/project/node_modules/@angular/core/testing/index"' has no exported member 'addProviders'.
```

**Expected behavior**
This worked fine at rc.5 - I don't see any notice that addProviders has been deprecated, so I'm not sure if this is a bug or if there's a new method for use.

**Reproduction of the problem**
Just trying to import in test.
```
import {
  addProviders
} from '@angular/core/testing';
```

**Please tell us about your environment:**
Windows 7 / tsc 1.8.10

* **Angular version:** 2.0.0-rc.6 and 2.0.0-rc.7  (was not an issue at rc.5)
 
* **Language:** Typescript 1.8.10

**Comment by vicb** [comment]
see https://github.com/angular/angular/blob/master/CHANGELOG.md
