### ISSUE TITLE
Router resolver 

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular#11607]
Error reproduction - [try it](http://plnkr.co/edit/XMDBkcOPO6fczXbFPLUG?p=preview)

If we use BehaviorSubject as Observable in implemented resolve method then resolving do not work.
I expected it to be worked.
 
```
resolve():Observable<any> | Promise<any> | any {
        let subject = new BehaviorSubject<number>(777);

        return subject.asObservable(); //do not work
}
```

**Maybe I'm submitting a ...**
```
[x ] bug report 
```

**Comment by vicb** [comment]
Please add more info, "do not work" is too vague.

Until then your issue will be assigned a low priority

**Comment by olegdunkan** [comment]
If you see plunker example and edit it (uncomment //return subject.asObservable(); //Do not work!!!  in routing.ts ) you have to expect 777 showed in Store component template. But it will not. 

 BehaviorSubject must work as observable and I expected it. If we return simply Observable.of(777) it will work.

**Comment by ericmartinezr** [comment]
I think this is one of those cases where the Observable must be "completed". You can add `first()` operator, for example, to complete your observable like `return subject.asObservable().first();`. This is not a bug, but something that must be documented somewhere. There are issues where this is discussed, I'm sure of that, but I don't remember which ones exactly.

**Comment by olegdunkan** [comment]
@ericcarraway thanks, agree with you it must be documented. I think only completed observables resolves data to router. But it's very tricky case. 
@vicb maybe it have to be expressed in documentation?

**Comment by vicb** [comment]
@olegdunkan the doc repo is https://github.com/angular/angular.io could you please create an issue there and link to this one ?

Thanks

**Comment by olegdunkan** [comment]
@vicb Ok.

**Comment by smitalm** [comment]
If i havent found this issue, i would have wasted couple of hours wondering why my resolver is not working. 

I just want to add that it is confusing to me, that i "subscribe" to resolved data, but it doesnt work with non-completed observables...

```
export class MyComponent {
  data: any;

  constructor(private route: ActivatedRoute) {
    route.data.subscribe((resolve) => {
      this.data = resolve[ 'data' ];
    });
  }
}
```

**Comment by manofearth** [comment]
have spent a few hours trying to understand what's wrong with my code
```
return subject.asObservable().first();
```
helped me, thanks

Please, document it somewhere. May be even [here](https://angular.io/docs/ts/latest/guide/router.html#!#resolve-guard)

**Comment by vicb** [comment]
@manofearth could you please open an issue on https://github.com/angular/angular.io and link this issue there ?
Thanks

**Comment by manofearth** [comment]
@vicb **olegdunkan** already opened same issue on https://github.com/angular/angular.io 
I'v opened another: https://github.com/angular/angular.io/issues/2503
