### ISSUE TITLE
TitleService is not export in RC.6 

### ISSUE THREAD

**Issue by m4mbart** [angular/angular#11600]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
In a shared module (SharedModule) I import and export BrowserModule. But other modules that use this shared module cannot find the provider for Title. If I add Title to SharedModule providers it does work in other modules.

**Expected behavior**
If I understand correctly I would expect that BrowserModule to export 'Title' for us.

**Please tell us about your environment:**
Mac OS X 10.11.6, angular-cli, ng serve

* **Angular version:** 2.0.0-rc.6
Does not appear in the fixed list for rc.7

* **Language:** Typescript 2.0

**Comment by pkozlowski-opensource** [comment]
Woops, seems like we've failed to properly include the `Title` service as part of the `BrowserModule`. Preparing a PR right now.
