### ISSUE TITLE
Route navigation is not working for LazyLoading modules dynamically

### ISSUE THREAD

**Issue by moduga** [angular/angular#11602]
I have two modules say Contact and About.
I configured these two are lazy modules.
Based on the configuration of the tab(either "contact" or "about", it will navigate to either Contact tab or About tab.
I'm unable to navigate to Contact tab if the configuration route is "contact" dynamically.

Plunker : https://plnkr.co/edit/Ri0jvXVfY3qaZaapFFe1?p=preview.

Please help me for dynamic navigation for lazy modules.

**Comment by vicb** [comment]
Please provide the info requested in the template.
Your issue will be assigned a low priority until them.

**Comment by moduga** [comment]
thank your the quick replay.
In the template, i just added simple text "Contact Module" for Contact tab and "About Module" for About tab.
My requirement is, while loading the application initially it will go either "Contact" or "About" tab based on the configured route("contact" or "about") .

**Comment by michalstepien** [comment]
@moduga You have to setup default route: https://plnkr.co/edit/YeMl1nL18lnIkU5VNeQy?p=preview

**Comment by moduga** [comment]
@michaelchiche  thank your for your response
In my scenario, i don't have any default route. Based on the configuration it should navigate to particular tab dynamically. Can you please help me in this scenario ?

**Comment by zoechi** [comment]
@moduga GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by moduga** [comment]
@zoechi  thank you. I will use what you mentioned.
