### ISSUE TITLE
AoT: remove @Component metadata from gen'd code (esp. moduleId)

### ISSUE THREAD

**Issue by wardbell** [angular/angular#11613]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report 
[x] feature request
[ ] support request
```

**Summary**
Suggest that we stop generating `@Component`  metadata into the output.

**Current behavior** 
`templateUrl` and `styleUrls` must be written as module-relative URLs for AoT compilation. For such code to work with JiT as well (no web pack), the dev must specify `@Component.moduleId` (typically with `module.id`).

But after AoT compilation this leads to a runtime error "module undefined". Which is true. It has no runtime value. 

There is a hack to get around it. The actual value doesn't matter. So the following addition to `index.html` works:

```
<script>module = { id: 'aot' };</script>
```

Clearly undesireable. But we have to teach it.

In fact, the code has no need for `@Component.moduleId` or any of the `@Component` metadata.
The problem goes away if we stop generating it.

**Expected behavior**
No error. Not hacky workaround.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.7
- **Browser:** [all ] 
- **Language:** [ TypeScript ]

**Comment by IgorMinar** [comment]
moduleId, template, templateUrl, styles and styleUrls can all be safely removed via the tsickle pass.

@vicb this is not a feature as it doesn't add new functionality

**Comment by IgorMinar** [comment]
I'm marking this as critical since it affects every app that we want to AOT compile, which is almost every app.

**Comment by IgorMinar** [comment]
I was wrong. Only people that want to use JIT with systemjs + AOT side by side are affected. e.g. CLI is not because it inlines all external templates in the JIT mode, so moduleId is not needed there.

**Comment by Richie765** [comment]
This issue has consequences not described above. When including a 3rd party package, its templates will be included in the resulting compiled code. It makes the code bigger and exposes internals of the application.

To clarify I made a simple repo:
```bash
# simple app that includes ng2-slim-loading-bar 3rd party package

git clone https://github.com/Richie765/ng2-aot-template-bug
cd ng2-aot-template-bug/
npm install

# Build with AoT
ng build --prod

# Search for templates
cd dist
grep -ohP "template:'.*?'" *
```

You will see the template from the included 3rd party module:
```
template:'\n<div class="slim-loading-bar">\n    <div class="slim-loading-bar-progress" [style.width]="progress + \'
```

I tried several other 3rd party packages, including Ionic, with similar results.

**Comment by fkolar** [comment]
What about application that are using _Metadata_  to generate dynamic code?
 
e.g. while generating code on the fly you might need to have access to a `Component` that gives you all Inputs[], Outputs[], etcs.  so you can dynamically set bindings and other things.

For this you normally use `DirectiveResolve` to resolve a `Type` to `Component` and if you would remove it then application will be pretty limited or even angular capability of what application can use. 

I guess in AOT you dont include compiler module but still you should be able to use _Reflect_ to retrieve some annotations and do some processing.

If you are going to remove it then there will be no information around to do such things ;-(

**Comment by trotyl** [comment]
Should have been solved by [build-optimizer](https://github.com/angular/devkit/tree/master/packages/angular_devkit/build_optimizer)?

**Comment by IgorMinar** [comment]
@trotyl yup. thanks for pointing this out. @angular/cli and @angular-devkit/build-optimizer already strip this stuff by default when creating production builds.
