### ISSUE TITLE
rxjs/BehaviorSubject with rxjs/Subscription not working between two components unless its a child component

### ISSUE THREAD

**Issue by Motassem-MK** [angular/angular#11618]
using rxjs/BehaviorSubject and rxjs/Subscription to communicate two components through a service like this:

Service (code related to the problem): 

    import { BehaviorSubject } from 'rxjs/BehaviorSubject'
    
    private _clientModalActionSource = new BehaviorSubject<string>('')
    modalAction$ = this._clientModalActionSource.asObservable()
    public updateClientModalAction(action) {
       this._clientModalActionSource.next(action)
       console.log('sent')
    }

Component A :

    this._api.updateClientModalAction(id)

Component B : 

    import { Subscription } from 'rxjs/subscription'
    
    private _subscription: Subscription
    ngOnInit() { this._subscription = this._api.modalAction$.subscribe(res => {
       this.refreshModal(res)
       console.log('received')
    })}

This is working perfectly if Component B is child of Component A, but if A is the root component and B is inside its `<router-outlet>` (or the opposite) nothing is being received to the subscription, I only get `sent` in the console. (without 'received')

[Plunker] (https://embed.plnkr.co/PbLHwnCHNsbKPK0pgqgI/)

so unless I'm doing something wrong..

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 
```

**Comment by vicb** [comment]
Please add a plunker with a minimal repro. Thanks.

**Comment by Motassem-MK** [comment]
Sorry, updated the post with a plunker
well, it didn't work with child components either.

**Comment by brandonroberts** [comment]
In order two share a service between multiple components, you should provide the service at a level higher and not add the service to the `providers` of both components.

https://plnkr.co/edit/aX8HTN3F7LJHLjYo5YiK?p=preview

**Comment by Motassem-MK** [comment]
oh this explains it all! thank you a lot :)

**Comment by sannies** [comment]
I wasted literally 2 days on that thing. It's absolutely _not_ clear for anyone starting with Angular2 that a service registered at a child component will shadow the rest of the app from the events emitted there. 
The quickstart registers the HeroService at the HeroComponent. That put me on the wrong track. I simply changed the app and added the HeroService in the root module while experimenting. That's where the mess started. 
A sentence like "Do not register any provider twice as this will create two independent instances." might have helped me in the quickstart chapter "When to use the NgModule and when an application component?"

**Comment by DzmitryShylovich** [comment]
@sannies https://github.com/angular/angular.io/issues

**Comment by kooldandy** [comment]
@brandonroberts Thanks a lot buddy

**Comment by duarte171183** [comment]
@brandonroberts  Thanks

**Comment by danieldiazastudillo** [comment]
5 hours banging my head against the wall with this (it even made me miss $rootScope)... the solution as pointed out by @brandonroberts took 30 seconds...

**Comment by ivanlopezmolina** [comment]
@danieldiazastudillo while debugging I found that the more I navigate to the component where I'm subscribing the element the more times enter to the subscribe method, so I ended using just a simple public variable to interchange the value that I needed between 2 components, and yes, declaring the service at the app.module level.

**Comment by kurt-patrick** [comment]
you the man. so glad i read your comment, i had 2 components and the messages were not being sent between each. i had added the line "providers: [ DataService ]" to both of my components and to app.module.ts
removing the line "providers: [ DataService ]" from both components did the job as there was now only 1 instance of my service loaded from the app module

**Comment by piyush-ampersand** [comment]
Hi I am also trying to send data between two components and these two components are siblings but I am not able to send the data. These two components are part of a different module than the app.module. I have imported the second module in the app.module and then trying to send data between the components. I am new to angular and I don't know what I am doing wrong. Please help

**Comment by mlc-mlapis** [comment]
@piyush-ampersand ... simply you are using the different instance of observable. This is not the problem for this issue channel. Prepare a simple online demo on https://stackblitz.com and then ask on Gitter https://gitter.im/angular/angular.

**Comment by shivekundefined** [comment]
> In order two share a service between multiple components, you should provide the service at a level higher and not add the service to the `providers` of both components.
> 
> https://plnkr.co/edit/aX8HTN3F7LJHLjYo5YiK?p=preview

Life Savior.

**Comment by ayushee-kiet** [comment]
> In order two share a service between multiple components, you should provide the service at a level higher and not add the service to the `providers` of both components.
> 
> https://plnkr.co/edit/aX8HTN3F7LJHLjYo5YiK?p=preview
