### ISSUE TITLE
Zone.js error after updating to RC 7 and  "zone.js": "^0.6.22"

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#11610]
I updated Angular 2 Code from RC 6 to RC 7 with zone version 0.6.22, in Developer tools after i run my application i get below error :

![image](https://cloud.githubusercontent.com/assets/12258728/18529677/1e003daa-7a9c-11e6-8f9e-29f092b281d9.png)

**Comment by ericmartinezr** [comment]
Already reported here https://github.com/angular/zone.js/issues/444

**Comment by vicb** [comment]
Please update to the latest release: npm install zone.js@0.6.23
