### ISSUE TITLE
benchpress: auto wait until end of rendering after every iteration

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1161]
Benchpress has the `render` metric. However, we need to make sure that the browser really finished rendering before we continue with the next iteration. Otherwise the browser might squash multiple changes into one and our metric would report the wrong value.

Note: Just waiting for the next turn (i.e. `setTimeout(fn, 0)`) is probably not good enough...

Implementation idea:
- also read out `frameId / frameTimestamp` from the browser perf log and poll until we have a new frame. We need this also for creating a frames per second metric.
- if this does not work: wait via `requestAnimationFrame` in the browser

**Comment by tbosch** [comment]
Also investigate auto waiting for asynchronous script execution.

**Comment by tbosch** [comment]
Same for micro metrics.

**Comment by tbosch** [comment]
Think about animations as well for rendering, as there might be multiple paints, ... to be measured!

At least provide an easy way to tell benchpress that script execution / animation is done (maybe via a special call to `console.log`, ...)

**Comment by tbosch** [comment]
Needed for benchmarks in Greentea!

**Comment by splincode** [comment]
@tbosch Is the issue relevant?
