### ISSUE TITLE
[ngc] Cannot use `NgModule` type for a constructor param

### ISSUE THREAD

**Issue by laco0416** [angular/angular#11621]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In a class constructor arguments, `foo: ngModule` is not allowed.

```
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule
```

**Expected behavior**

**Reproduction of the problem**
This is an AoT issue, so there aren't any plunkers.

**What is the motivation / use case for changing the behavior?**

I'd like to an interface of `NgModule` metadata in my library.

https://github.com/laco0416/angular2-component-outlet/pull/19/files#diff-00acd7627cec586437fb8e04e64b2361R65

but these are gone in RC.7...

**Please tell us about your environment:**

* **Angular version:** 2.0.0
 
"@angular/compiler-cli": "0.6.2",

* **Language:** TypeScript 2.0.2
 
* **Node (for AoT issues):** `node --version` =   5.12.0

**Comment by laco0416** [comment]
`NgModule` has 2 faces: `interface ngModule` and `const NgModule`.

**Comment by vicb** [comment]
The module type should be `AppModule `

**Comment by laco0416** [comment]
@vicb No, this is a **library**. `AppModule` is just an application-side thing. 

I don't understand why `...Metadata` classes were removed...

**Comment by vicb** [comment]
> I don't understand why `...Metadata` classes were removed

use `...` instead

**Comment by vicb** [comment]
please also describe what you are trying to do in your project.

**Comment by laco0416** [comment]
so, when `NgModule` is in the constructor params, ngc causes error.

My library repo is a repro.

https://github.com/laco0416/angular2-component-outlet

1. git clone
2. npm i (then npm test autorun)-> passed
4. modify https://github.com/laco0416/angular2-component-outlet/blob/master/src/component-outlet.ts#L65: `any` to `NgModule`
5. npm test -> Compilation failed

**Comment by laco0416** [comment]
This error happens only **in application**. Library compilation seems working well, but an app cannot use the generated metadata.

**Comment by vicb** [comment]
what are you trying to inject ? why ?

**Comment by laco0416** [comment]
This library's goal is emulation of `$compile`

**Comment by laco0416** [comment]
In Angular 2, Dynamic component compilation needs NgModule.

**Comment by laco0416** [comment]
In other words, this is a way for online compilation for user-created template.

**Comment by vicb** [comment]
my first comment means that when you inject a component (`@Component`) the type is `MyCmpClass`, not `Component`

**Comment by laco0416** [comment]
Sorry, my words was less.

**Comment by laco0416** [comment]
update the top description (repro section).
