### ISSUE TITLE
Use NODE_ENV=production instead of enableProdMode

### ISSUE THREAD

**Issue by nopantsmonkey** [angular/angular#11623]
**I'm submitting a**  

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Need to use enableProdMode when deploying to production

**Expected behavior**
should use NODE_ENV=production for disabling assertions, removing long errors from code, removing dev mode code etc

**What is the motivation / use case for changing the behavior?**
REACT usage of NODE_ENV=production to remove dev mode code, long error messages etc
- **Angular version:**
  Angular 2.0

**Comment by tojocky** [comment]
Hi,

why not to use webpack global constant into the code by using [webpack.DefinePlugin](https://webpack.github.io/docs/list-of-plugins.html#defineplugin) and call `enableProdMode()` for PROD at compilation? You can use whatever env variable, even `NODE_ENV`.

**Comment by wesleycho** [comment]
It should be noted that this would be a breaking change

**Comment by nopantsmonkey** [comment]
@tojocky currently, we all do that when using angular in production.
That is why the most obvious thing is to do that automatically when NODE_ENV=production

In my opinion it would be better if we don't have to write two more lines for enabling production mode

**Comment by tojocky** [comment]
@nopantsmonkey you have a good point by removing unused code from amgular during compilation.

**Comment by trotyl** [comment]
Superseded by https://github.com/angular/angular/issues/12200, fixed by Ivy.

**Comment by pkozlowski-opensource** [comment]
Thnx @trotyl - you are right on both fronts!
