### ISSUE TITLE
Lazy loading modules with the Router with webpack 2 still not work

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular#11625]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
A webpack 2 project as described here:
https://angular.io/docs/ts/latest/guide/webpack.html

A lazy loading configuration as described here:
https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load

When clicking an anchor which leads to an lazy loaded module I get this error:

> EXCEPTION: Uncaught (in promise): Error: Cannot find module 'app/configuration/configuration.module'.

> Error: Uncaught (in promise): Error: Cannot find module 'app/configuration/configuration.module'.

> zone.js?fad3:344 Unhandled Promise rejection: Cannot find module 'app/configuration/configuration.module'. ; Zone: angular ; Task: Promise.then ; Value: Error: Cannot find module 'app/configuration/configuration.module'.(…) Error: Cannot find module 'app/configuration/configuration.module'.

I also see this warnings when the app is launching:

> ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
> 45:15 Critical dependency: the request of a dependency is an expression
> CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression

> ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
> 57:15 Critical dependency: the request of a dependency is an expression
> CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression

**Expected behavior**
That lazy loading modules works as described in the documentation in a webpack 2 infrastructure also described in the documentation.

**Reproduction of the problem**
Follow the documentation.

A webpack 2 project as described here:
https://angular.io/docs/ts/latest/guide/webpack.html

A lazy loading configuration as described here:
https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load

**What is the motivation / use case for changing the behavior?**
As a user I want to follow the documentation with the result of a working application.

**Please tell us about your environment:**
Linux

* **Angular version:** 2.0.0 and webpack 2.1.0-beta.22

* **Browser:** Chrome Version 53.0.2785.116 (64-bit)
 
* **Language:** TypeScript 2.0.2

* **Node (for AoT issues):** `node --version` =   6.5.0

**Comment by ifaouibadi** [comment]
1) update your cli to the latest
https://github.com/angular/angular-cli#working-with-master

2) for your lazy route
`
{
        path: 'route_name', loadChildren: () => new Promise(resolve => {
            (require as any).ensure([], require => {
                resolve(require('./path/to/yourmodule').ModuleName);
            })
        })
    },
`

**Comment by Martin-Wegner** [comment]
I do not use angular-cli...

**Comment by DzmitryShylovich** [comment]
You need https://github.com/brandonroberts/angular2-router-loader
[Here](https://github.com/qdouble/angular2webpack2-starter) you can find usage example.

**Comment by haseeb200** [comment]
angular 2 router loader not working either

**Comment by DzmitryShylovich** [comment]
@haseeb200 do u have a reproduction?

**Comment by haseeb200** [comment]
Yes I am seeing the same error module not found. How ever this code solve the issue.

`path: 'route_name', loadChildren: () => new Promise(resolve => {
            (require as any).ensure([], require => {
                resolve(require('./path/to/yourmodule').ModuleName);
            })
        })
`

but i dont think its the perfect solution. Its just the workaround with webpack

**Comment by DzmitryShylovich** [comment]
angular 2 router loader works fine and people have already use it in their prod apps. If u have some issues create a repo with reproduction so we can help u to setup it correctly.

**Comment by haseeb200** [comment]
Let me check again maybe I am missing something.

Is it just download the loader and configure it. correct?

**Comment by Martin-Wegner** [comment]
@ifaouibadi your code works!
@DzmitryShylovich also works. But it produces code which throws an error:

> ERROR in [default] /work/zst/client/src/app/app.routing.ts:12:40 
> Parameter 'require' implicitly has an 'any' type.

**Comment by haseeb200** [comment]
@DzmitryShylovich Angular 2 router loader working fine now. Mistake was mine.
@Martin-Wegner check your code in app.routing maybe you are missing something. I am not seeing any warning.

**Comment by DzmitryShylovich** [comment]
@Martin-Wegner u don't need require in your routing config. Example: https://github.com/qdouble/angular2webpack2-starter/blob/master/src/app/app.routes.ts

**Comment by Martin-Wegner** [comment]
@DzmitryShylovich the error comes from the compiled code. You can read about the code replacement here: https://github.com/brandonroberts/angular2-router-loader

**Comment by DzmitryShylovich** [comment]
You are right. So it's probably codelyzer or tslint error.

**Comment by Martin-Wegner** [comment]
Yes it is and it should be fixed in the angular2-router-loader project.

**Comment by DzmitryShylovich** [comment]
You should exclude all generated files. Btw ng factory files already have ` /* tslint:disable */` at the top.

**Comment by Martin-Wegner** [comment]
It is not a tslint option! It is a tsconfig option: `"noImplicitAny": true,`

**Comment by brandonroberts** [comment]
@Martin-Wegner if you're using Webpack 2 you can use `system` as the loader instead of the default. Since special typings are required for `require.ensure`, I can add some instructions on how to use that

**Comment by brandonroberts** [comment]
@Martin-Wegner Ok. That's in the context of the angular-cli though. Have you tried using a relative path with `loadChildren` instead of `app/path/something.module`?

**Comment by Martin-Wegner** [comment]
Yes I tried everything :( The code from @haseeb200 works and the angular2-router-loader project mentioned by @DzmitryShylovich also works.

**Comment by brandonroberts** [comment]
@Martin-Wegner come into the chatroom and we'll help you there https://gitter.im/angular/angular

**Comment by gdi2290** [comment]
if you're using webpack 2 you can just use System.import
```js
    {
        path: 'route_name', loadChildren: () => System.import('./path/to/yourmodule').then(mod => mod.ModuleName)
    },
```

**Comment by vicb** [comment]
@brandonroberts @gdi2290 @DzmitryShylovich and others thanks for helping !

**Comment by DzmitryShylovich** [comment]
@vicb I think this can be closed.

**Comment by vicb** [comment]
@DzmitryShylovich thanks !

**Comment by moparlakci** [comment]
everytime you create a module, kill ng serve and restart again ;)

**Comment by Blackbaud-SteveBrush** [comment]
For anyone that couldn't get [angular2-router-loader](https://github.com/brandonroberts/angular2-router-loader) to work, I had to upgrade `angular2-template-loader` from version `1.1.1` to version `2.2.4`. After that, everything ran smoothly.

**package.json**
```
{
    "devDependencies": {
        "angular2-router-loader": "^0.3.3",
        "angular2-template-loader": "^0.6.0",
        "awesome-typescript-loader": "^2.2.4"
    }
}
```

**webpack.config.js**
```
module.exports = {
    module: {
        loaders: [
            {
                test: /\.ts$/,
                loaders: [
                    'awesome-typescript-loader',
                    'angular2-template-loader',
                    'angular2-router-loader'
                ]
            }
        ]
    }
} 
```

**Comment by shafaqkazmi** [comment]
I am also facing this issue. can any one please suggest? https://github.com/brandonroberts/angular-router-loader/issues/78
