### ISSUE TITLE
2.0.0 released but milestone plan says 30 open issues?

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular#11622]
Today you released 2.0.0 but your milestone plan (https://github.com/angular/angular/milestones/) has over 30 open issues.

Is the milestone plan outdated and Angular 2 is final and ready for rumble?

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

It's entirely up to you. 
Some started using it in production in alpha versions others won't use it before several post-release bug-fix updates.

**Comment by Martin-Wegner** [comment]
Gitter:

> Rob Wormald @robwormald 09:30
> @Martin-Wegner honestly, we're really shit at tracking milestones, or at least have been in the pre-release period. definitely on our list of things to improve now

http://angularjs.blogspot.de/2016/09/angular2-final.html
