### ISSUE TITLE
Do not alter headers cases

### ISSUE THREAD

**Issue by cyrilhamidechi** [angular/angular#11624]
Hi all,

In the latest RC7, there is a surprising update regarding the header: https://github.com/angular/angular/commit/7f647822bdddaad6a96c4f368a9874ce7ae3775c#diff-9568639931339e95e9537c0972bec9efR59
All headers are now lowercased.
Argument for this modification is IEFTF's HTTP/1.1 specifications.

As far I understand, header case-insensitive support is a server side concerns, not client side.
It is stated "Field names are case-insensitive.", making server more tolerant.
It is not stated "headers sent by the client should be lowercased", making client library deciding what to do with your header.

This change is a breaking one.
Consequence are immediate by broken server-side compatibility.
For exemple, a server-side expected "Authorization" header, which is now lowercased by client in "authorization", is not recognised anymore by the server.

Thank you for your support.

**Comment by vicb** [comment]
What is your server ?

**Comment by cyrilhamidechi** [comment]
Apache / PHP.
And there is a known behaviour about string comparison which is case-sensitive especially with the [apache_request_headers]( http://php.net/manual/fr/function.apache-request-headers.php) method.
Full discussion is [here](http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive).

In anyway, this is not the concern of the client.
I hope you get the point @vicb .

**Comment by vicb** [comment]
The point I get is that this is a bug in Apache and you should create a ticket there.
We conform to the spec they don't. And that's exactly what your link is about, nothing else.

That being said I'll check what we can do on our side to mitigate the Apache bug.

It would help if you can find a precise description of the Apache bug. Thanks.

**Comment by pkozlowski-opensource** [comment]
I agree with @vicb that the root cause is in the server if it doesn't follow spec. Having said this I'm not sure we need / should be touching headers for the outgoing requests. We should retrieve _response_ headers in the case-insensitive way but I don't think we've got much business in touching casing of request headers.

This is all grey area of course but we might be on a slightly safer side if we don't mess with request headers.

**Comment by vicb** [comment]
@pkozlowski-opensource not touching the header is not possible.

```
headers.set('content-type', v1);
headers.set('Content-Type', v2);
```

what do we send then ?

which is why the Apache bug might be helpful.

_My first guess is that We-Should-Normalize-Like-That but I want to check how popular libs do before touching the code_

**Comment by cyrilhamidechi** [comment]
**The fact**
Specifications are "case-insensitive".

**My understanding**
It does not mean "normalize".
It does mean "accept any case".

**The use-case**
If client wants to send "Authentication", "aUtHeNtICaTiOn", "AUTHENTICATION", ... he must be able to send it as he wants.
A bug-free server will basically consider all of it as equivalent to "authentication".

**The conclusion**
This is not to a third-part client to decide that.

**Comment by JanStureNielsen** [comment]
@vicb with
```
headers.set('content-type', v1);
headers.set('Content-Type', v2);
```
the result should be:
```
headers.get('CONTENT-TYPE') == v2
```
Client frameworks should never change the case of headers.

**Comment by vicb** [comment]
Yes... in an ideal world where everybody follows the spec and devs never make typo this would be really easy. Unfortunately that's not the world we live in - that wouldn't be fun anyway.

I have looked at different libs, some preserve the casing of the last header:

```ts
// sends Content-Type: v2
headers.set('content-type', v1);
headers.set('Content-Type', v2);

// sends content-type: v2
headers.set('Content-Type', v1);
headers.set('content-type', v2);
```

I don't think this is acceptable !

I like what node http is doing:
```js
var http = require('http');

var options = {
  host: 'requestb.in',
  path: '/p3617np3',
  method: 'GET',
  headers: {
    'CONtent-Type': 'application/JSON',
    'Content-type': 'application/custom',
  }
};

var req = http.request(options, function(res) {
  res.setEncoding('utf8');
});

// sends Content-Type: application/custom
req.end();
```

I need to look more at the impl but I would like to do something similar.

**Comment by vicb** [comment]
It seems like normalization is done by requestb.in !

node sends: `'GET /p3617np3 HTTP/1.1\r\nContent-type: application/custom\r\nx-vicTor: abc\r\nbla-blou-ble: bcd\r\nHost: requestb.in\r\nConnection: close\r\n\r\n'`

**Comment by benneq** [comment]
I just had a look the `HttpHeaders` implementation of Spring Framework.

It's got basically 3 methods: `add`, `set` and `get`:
* `set` enforces that there's only a single value. It is **case insensitive**
* `add` appends the given value (see examples). You can call this after `set` to add another value. Also **case insensitive**
* `get` always returns a `List` and is **case insensitive**

Example 1:
```
headers.set("x", "foo")
headers.set("X", "bar")
// headers = {"X":["bar"]}
// headers["x"] = ["bar"]
// headers["X"] = ["bar"]
```

Example 2:
```
headers.set("X", "foo")
headers.set("x", "bar")
// headers = {"x":["bar"]}
// headers["x"] = ["bar"]
// headers["X"] = ["bar"]
```

Example 3:
```
headers.add("X", "foo")
headers.add("x", "bar")
// headers = {"X":["foo", "bar"]}
// headers["x"] = ["foo", "bar"]
// headers["X"] = ["foo", "bar"]
```

Example 4:
```
headers.add("x", "foo")
headers.add("X", "bar")
// headers = {"x":["foo", "bar"]}
// headers["x"] = ["foo", "bar"]
// headers["X"] = ["foo", "bar"]
```

I think this is a pretty nice solution.
