### ISSUE TITLE
Error using [(ngModel)] with a reactive form model on a nested custom (ControlValueAccessor) input component

### ISSUE THREAD

**Issue by medeirosrich** [angular/angular#11629]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I've recreated a plunk of a situation I've encountered.
https://plnkr.co/edit/hyHieinxKfg1E1vVx3vz

In Forms 0.3.0 this worked. In RC7 it does not. 

I'm receiving the following error when trying to bind [(ngModel)] to a custom form component:
EXCEPTION: "Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'."

**Expected behavior**
input.value should have two-way binding with the custom-input component with no errors. 

**Please tell us about your environment:**

- **Angular version:** 
  2.0.0-RC.7
- **Browser:**
  Chrome
- **Language:** 
  TypeScript
- **Node (for AoT issues):** `node --version` =

**Comment by mierzej** [comment]
Have same problem ;/ cant find a way too fix this error

**Comment by manklu** [comment]
The primary problem is, that you modify the FormGroup inside HierarchyData

**Comment by medeirosrich** [comment]
Is it a feature or a bug that FormGroup cannot be modified inside a child component?

HierarchyData is a recursive component, I cant figure out how to add inputs to a parent components FormControl. Or how to make recursive template loops.

**Comment by manklu** [comment]
AFAIK a feature

You can implement a ControlValueAccessor in HierarchyData. From outside this looks like one control which returs complex objects.

See #10251 for details and inspiration

**Comment by AndrewKushnir** [comment]
Hi @medeirosrich, thanks for reporting the problem. It looks like in your repro you combined template-driven and reactive approaches, specifically `ngModel` and `formControlName` directives on the same element. This pattern was deprecated and will not be allowed in the future versions of Angular, see more information on this here: https://angular.io/guide/deprecations#ngmodel-with-reactive-forms. I believe a possible solution would be to switch to the reactive approach completely and avoid using `ngModel` in your use-case. Thank you.
