### ISSUE TITLE
Form not working correctly after reloading with a new one

### ISSUE THREAD

**Issue by Mc128k** [angular/angular#11627]
Hi all, I am working with forms and I just encountered a weird behaviour. I can create a form and display it like this:

```
              this.form = this.formBuilder.group({
			_test__client_name: [ticket._test__client_name],
			_test__contents: [ticket._test__contents]
		});

		// VALIDATORS
		this.form.controls['_test__client_name'].setValidators(
			Validators.compose([
				//Validators.minLength(3),
				//Validators.maxLength(10),
				//Validators.pattern('....'),
				Validators.required, 
				skuValidator
				])
			)

		// OBSERVABLES
		this.form.controls['_test__client_name'].valueChanges.subscribe(
			(value: string) => {
				console.log("change detected: ", value)
			})
```

The template starts with:
```
<div *ngIf="loadedTicket">
      <form (ngSubmit)="onSubmitForm(form.value)" [formGroup]="form">

        <table style="width: 100%" cellspacing="0">
          <tr>
            <td>
              <md-input 
              placeholder="Name" 
              formControlName="_test__client_name"
              autocomplete="off"
              ></md-input>
              <div *ngIf="form.controls['_test__client_name'].hasError('invalidSku')">Must begin with <span>123</span></div>
          
            </td>
            {{form.value._test__client_name}}
            {{form.dirty}}
```

And it works fine initially. But if I load another record (so a new form is created and saved in the same variable) all validation and form control does not work. So if I edit a field the form is not marked as dirty and validation errors are not evaluated. It works the first time, but then it doesn't.

I already checked that from the template the variable is referenced correctly

Is this a bug or an implementation error?
Thanks a lot

**Comment by zoechi** [comment]
If you are not sure it's a bug, please use one of the channels listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
@zoechi is totally right! Thnx!

**Comment by Mc128k** [comment]
Yay! Solved with the latest release! Sorry for the useless post, please remove it if necessary.
