### ISSUE TITLE
Issue with checking radio button which have boolean values

### ISSUE THREAD

**Issue by bezigon** [angular/angular#11634]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

First case:
1. select the "false" radio control – nope
2. click on button that's selects "false" radio control – nope

Second case:
1. click on button that's selects "false" radio control – checked
2. select the "true" radio control – checked
3. select the "false" radio control – nope

**Expected behavior**

In two cases "false" radio control – should be checked.

**Reproduction of the problem**

http://plnkr.co/edit/tJI9tI5cg5rBw9CWhJ5Q?p=preview

**What is the motivation / use case for changing the behavior?**

Usage of boolean values in arrays/dictionaries.

**Please tell us about your environment:**

* **Angular version:** 2.0.0

* **Browser:** Chrome 52.0.2743.116 (64-bit)

 
* **Language:** TypeScript 2.0.2
 
* **Node (for AoT issues):** `node --version` =   v6.5.0

**Comment by pkozlowski-opensource** [comment]
By using the `(click)` event you are assuming certain order of events (that is - that the internal state of the radio control changed already). But you don't have such guarantees so to be on the safe side use the `(change)` event instead: http://plnkr.co/edit/W0B2omrOzeuPCPq2Cl3r?p=preview
