### ISSUE TITLE
npm link doesn't work with angular2 packages

### ISSUE THREAD

**Issue by vlodko** [angular/angular#11639]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I have module A. I run `npm link` in that folder.
I have module B. I run 'npm link A` in that folder.
I import module A into module B.
Webpack build runs without errors.
But I get error in the Chrome:
compiler.umd.js?9df7:14126 
Uncaught Error: Unexpected value 'A' imported by the module 'B'

**Expected behavior**
It should import module without errors.

**Please tell us about your environment:**
Windows 10, Chrome 52, Webstorm 2016.2.3

* **Angular version:** 2.0.0
 
* **Language:** TypeScript 1.8.10
 
* **Node (for AoT issues):** `node --version` =  6.5.0

NOTE: I'm using nvm for Windows.

**Comment by vicb** [comment]
Please add the exact steps to reproduce

**Comment by vitvad** [comment]
@vicb , @vlodko 
I guess, this is because angular team didn't release 2.0.0 in npm.

latest release https://www.npmjs.com/package/angular2 ```2.0.0-beta.17 is the latest of 68 releases```

**Comment by vicb** [comment]
`@angular/angular` is the right repo

**Comment by Avien** [comment]
I'm also getting this error when working with npm link
Is there anything to be done to fix this?

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by Avien** [comment]
Didn't  @vlodko reported this as a bug in this thread?

**Comment by Avien** [comment]
@vlodko Did you manage to solve the problem somehow? Thanks

**Comment by vlodko** [comment]
@Avien , no I dropped that approach.
For now we define all our internal dependencies in index.ts file in the root of component folder and import it into main module. But in this case we need to compile ts to js for our internal modules :(
I've also posted issue on npm page, but any response for now...

**Comment by Avien** [comment]
Thanks,
I'm still waiting for a solution somehow

**Comment by JonnyHeavey** [comment]
I'm seeing the same issue using npm link between 2 modules

**Comment by vlodko** [comment]
So the issue was not caused by npm link.

**Comment by oferh** [comment]
Getting this issue when using npm link for my module

**Comment by vlodko** [comment]
Everything works fine when I delete **node_modules** and **typings** folders from the linked module's folder that I want to import.

**Comment by Avien** [comment]
Just tried it, still not working

**Comment by darkedges** [comment]
@vlodko That does not work for me either.
```
ERROR in ../ng2-totp/dist/index.js
Module build failed: Error: ENOENT: no such file or directory, open 'C:\development\angular2\ng2-totp\dist\index.js'
    at Error (native)
 @ ./src/app/app.module.ts 14:0-38
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in [default] C:\development\angular2\ng2-totp\dist\totp.directive.d.ts:1:2
7
Cannot find module '@angular/core'.
```

**Comment by vlodko** [comment]
@darkedges , please see this one: https://github.com/angular/angular/issues/11834

My work around was to 
1. remove node_modules, typings folders from a linked module folder
2. move my linked module folder to node_modules folder of parent module
3. start webpack 

Also we had some issues with tslint config file so I re-named it to tslint.conf.json in the linked module.

**Comment by vicb** [comment]
I closed the issue because the description was not clear.

We do not actively monitor closed issues.

If someone has a clear description for the issue please open a new issue.

**Comment by vlodko** [comment]
@vicb , I've already opened a new one: https://github.com/angular/angular/issues/11834
