### ISSUE TITLE
Test fail if there is routerLink in the template

### ISSUE THREAD

**Issue by alaruss** [angular/angular#11633]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Tests fail with:

> Error: Error in ./AppComponent class AppComponent - inline template:3:0 caused by: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document. in src/test.ts (line 25485)

or

> Error: Error in ./AppComponent class AppComponent - inline template:3:0 caused by: Bootstrap at least one component before injecting Router. in src/test.ts (line 25489)

**Expected behavior**
Tests passed.

**Reproduction of the problem**
Create new project with angular-cli@1.0.0-beta.14 and an empty component FirstComponent.

app.component.html

```
<h1>
  {{title}}
</h1>
<a class="navbar-brand" routerLink="/first">First</a>
<router-outlet></router-outlet>
```

app.routes.ts:

```
import {Routes, RouterModule} from '@angular/router';
import {FirstComponent} from './first/first.component';

let routes: Routes = [{
        path: 'first',
        component: FirstComponent,
    }];
export const appRouting = RouterModule.forRoot(routes);
```

app.component.spec.ts

```
import {TestBed} from '@angular/core/testing';
import {AppComponent} from './app.component';
import {appRouting} from './app.routes';
import {FirstComponent} from './first/first.component';
import {APP_BASE_HREF} from '@angular/common';

describe('App: Front2', () => {
    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [appRouting],
            declarations: [
                AppComponent,
                FirstComponent,
            ]
            }); });

    it('should create the app', () => {
        let fixture = TestBed.createComponent(AppComponent);
        let app = fixture.debugElement.componentInstance;
        expect(app).toBeTruthy();
    });});
```

Run ng test in the console - test fails with "Please provide value for APP_BASE_HREF...".
Add to test module:

```
 providers: [
                {provide: APP_BASE_HREF, useValue: '/'}
            ]`
```

test fails with "Bootstrap at least one component before injecting Router".

Remove routerLink from component template - test is passed without any problem

**Please tell us about your environment:**
- **Angular version:** 2.0.0
- **Browser:**  Chrome 53.0.2785.101, PhantomJS 2.1.1
- **Language:** Typescript 2.0.2
- **Node (for AoT issues):** `node --version` =   6.5.0

**Comment by beakid** [comment]
+1

**Comment by brayden-gramse** [comment]
I received this same error and it started working for me after I removed a few things from my spec file. I had to remove any imports that came from my app.routes.ts file and I also removed APP_BASE_HREF from my providers. Not sure if this will work for anyone else.

**Comment by 3du4** [comment]
I am having exactly the same issue using the UpgradeAdapter and Angular version 2.0.1.

**Comment by 3du4** [comment]
Updating Angular to 2.1.0 and Routes to 3.1.0 solved it in my case.

**Comment by Bulan** [comment]
Works with Angular 2.1.0 and Router 3.1.0 here as well.
(I use Angular CLI, and with beta.18 it uses those versions.)

Close?

**Comment by veliancreate** [comment]
Im still getting this problem with Angular 2.1.0, Router 3.1.0 and angular-cli@1.0.0-beta.18

**Comment by DzmitryShylovich** [comment]
@veliancreate pls add a small demo in plunkr

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource no repro, no feedback. I think can be closed
