### ISSUE TITLE
Listening 2 times to the same output on one element leads to unexpected results

### ISSUE THREAD

**Issue by ocombe** [angular/angular#11631]
**I'm submitting a:**

```
[x ] bug report
```

**Current behavior** 
If you have an element or directive with an `@Output()`, and you listen to this output on the element with 2 event listener attributes, they are both called, but the change detection only works for the second one.

For example:

``` html
<custom (onTimeout)="someFunction()" (onTimeout)="anotherFunction()"></custom>
```

Both `someFunction` and `anotherFunction` are called, but any view binding in `someFunction` will not work

**Expected behavior**
The parser should throw an error because you have 2 times the same event listener attribute on the element (and this is _most likely_ an error), and only one of them should be called.

If you decide that it's ok to have 2 times the same listener then if they are both called they should both work the same way.

**Reproduction of the problem**
See this plunkr: http://plnkr.co/edit/hqjl2PAvjY6ucmcZzMkq?p=preview
After 2 seconds the `<custom>` element will trigger its output, and both `(onTimeout)` listeners will be called (check the console.log, you will see that both functions are called), but only one of the 2 bindings changed in each function will be updated on the view.

**Please tell us about your environment:**
Any
- **Angular version:** 2.0.0
- **Browser:** only tested on chrome and firefox, but probably all
- **Language:** only tested TypeScript 2.0.2

**Comment by tbosch** [comment]
Sorry, but there was a typo in your example: In the code you update the property `anotherFunction`, but in the template you use `anotherFunctionCalled`.

Once that is fixed, it works, see http://plnkr.co/edit/W9G7OPCOOhveTq232xla?p=preview.
