### ISSUE TITLE
Perf: Make platforms not use the `ReflectiveInjector`

### ISSUE THREAD

**Issue by tbosch** [angular/angular#11646]
The platforms only provide a handful of services, which can be newed up directly.
This allows in small apps to tree shake the reflective injector.

Revisit router, whether it really needs the `ReflectiveInjector`.

**Comment by trotyl** [comment]
Platforms no longer uses `ReflectiveInjector` from v5 in https://github.com/angular/angular/pull/18496, which has been changed to static `Injector`: https://github.com/angular/angular/commit/fcadbf4#diff-0ef0b3df44ffd7a42aab5233a1a3defcR113

**Comment by pkozlowski-opensource** [comment]
Closing based on https://github.com/angular/angular/issues/11646#issuecomment-406812522
