### ISSUE TITLE
[Bug] UpgradeAdapter not bootstraping

### ISSUE THREAD

**Issue by Luchillo** [angular/angular#11649]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 
White screen, no error in console nor in webpack's terminal output.

**Expected behavior**
At least a few text words in screen, it's basically a simple hello world, shouldn't fail without errors, it shouldn't even fail to begin with.

**Reproduction of the problem**
I used this simple code, first `main.ts`:
```ts
// main.ts
import 'angular';
import {adapter} from './app';
import {App} from './app';

console.log(angular);

angular.module('ng1App', [])
.directive('myApp', function() {
  return {
    template: '<ng2></ng2>'
  }
})
.directive('ng2', adapter.downgradeNg2Component(App));

adapter.bootstrap(document.body, ['ng1App']).ready(function(){
  console.log('bootstrapped!');
});
```
Next adapter import from `app/adapter.ts` through a barrel in `app`:
```ts
import {forwardRef} from '@angular/core';
import {UpgradeAdapter} from '@angular/upgrade';
import {AppModule} from './app.module';

export const adapter = new UpgradeAdapter(AppModule);
```
Next app module in `app/app.module.ts`:
```ts
import {NgModule, ApplicationRef} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {RouterModule} from '@angular/router';

import {App} from './';
import {Home} from './home';

@NgModule({
  imports: [
    BrowserModule
  ],
  declarations: [
    App,
    Home
  ]
})
export class AppModule {}
```
Next app component in `app/app.component.ts`:
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'ng2',
  template: `
    <home></home>
  `
})
export class App {
}
```
Last home component which should be like a simple directive in `app/home.ts`:
```ts
import {Component} from '@angular/core';
import {adapter} from './adapter';

@Component({
  selector: 'home',
  template: `
    Welcome Home
  `
})
export class Home{ }
```

**Please tell us about your environment:**
OSX El Capitan, VSCode, NPM, http server -> `gulp-connect`

* **Angular version:** 2.0.0

* **Browser:** [all | Chrome 53 ] 
 
* **Language:** [TypeScript 2.0]

**Comment by vicb** [comment]
duplicate ?

**Comment by Luchillo** [comment]
@vicb Duplicate of which one? can you link the issue please?

**Comment by vicb** [comment]
It was a question. Have you look for similar issue, this one reminds me of something but not sure..
try https://github.com/angular/angular/search?q=UpgradeAdapter&type=Issues&utf8=%E2%9C%93

**Comment by Luchillo** [comment]
I've look at the first 3 pages but most of them are not duplicated or directly related, idk if any of them are related.

The biggest issue here is that no console log nor terminal log shows error, no error means nowhere to look, thus i don't know how to debug this issue.

**Comment by chrisnicola** [comment]
It seems unclear how the upgrade adapter is actually meant to work now with existing Angular 1 apps, particularly after the NgModule changes. As I understand it the root module would have a `bootstrap` attribute declaring one (or more?) root component(s?). However this doesn't really make sense if this module is being used as part of an existing Angular 1 app.

Another oversight seems to be that there is no way to bootstrap Angular 2 components into an existing HTML page, as could be done with Angular 1.

Right now I'm not confident that the upgrade path has been very well thought out and I'm questioning whether or not this is just a total rewrite situation.

**Comment by Luchillo** [comment]
@chrisnicola You got my fear into consideration, the NgModule change was huge, i think it's a good change, however i have 2 projects in charge and 1 of them is Angular 1 which seems that i'll have to re-write from the ground up, while the other is Ionic 2 which is pending the next release in sync with Angular 2.0.

If i'm unable to even work it out with an almost "Hello world" example app, much less with the project i'm supposed to take care of.

**Comment by Luchillo** [comment]
At the end i made it work (somehow), i downgraded the `AppComponent`, then used projection|transclution to show the ng1 content that i had in index.html, then i just have to downgrade each component not called directly from an Ng2 component's template.

Also worth mentioning that the way directives are declared and used in Ng1 is different, you say your directive is called like:
```ts
const app = angular.module('taoApp');

app.directive('ng2', adapter.downgradeNg2Component(AppComponent))
app.directive('taoNg2Dashboard', adapter.downgradeNg2Component(DashBoardComponent));
```

But you would actually use it like this:
```html
<tao-ng2-dashboard>Loading...</tao-ng2-dashboard>
```
Since it has been some time since i touched Ng1 code (aprox. 1 year), i forgot that in Ng1 you declare directives in `cammelCase` but you use `kebab-case` when using the directive itself, and that may as well be the cause of my issue.

**Comment by hg-eric** [comment]
Should this issue really be closed? I've got the same issue and at least I would like to find out why this is happening. Luchillo's solution seems not to be appropriate and fails as soon as you have an angular 1 that wraps an angular 2 module.

**Comment by Luchillo** [comment]
@hg-eric My issue i think was most likely because the way the Ng1 directives are declared but used different, i've gone up and search for any explanation on your issue but saw nothing, can you explain your case to see where it goes wrong?

**Comment by chrisnicola** [comment]
@hg-eric I'm going to open a new issue after creating a clean `angular-cli` app to demonstrate the problems.

**Comment by hg-eric** [comment]
@Luchillo Indeed... It seems that it really was a wrong declaration of the downgraded Angular2 component. When I first read your post, I thought the solution to make it work was the transclution stuff and so I did not realize the important part anymore. :)

@chrisnicola Cheers mate. Anyway I think it is actually a problem that exists between the chair and the computer. The upgrade adapter and both frameworks are working as expected.
