### ISSUE TITLE
Swap out the widget gallery router for Angular 2 router

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#1164]
First test run of the new router. @matanlurey please spec out what's possible + blockers.

**Comment by mhevery** [comment]
Blocked on #618

**Comment by matanlurey** [comment]
Depending on your optimism, I'm OK with pushing this to M8

It may be possible to continue using https://github.com/angular/route.dart with DynamicComponentLoader instead of a dynamic view/template. Let me know your thoughts.

**Comment by mhevery** [comment]
@matanlurey you should be unblocked now. Can you give update?
