### ISSUE TITLE
NumberValueAccessor does not provide invalid input

### ISSUE THREAD

**Issue by fredgate** [angular/angular#11644]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When the user enters a non numeric string in a input having the NumberValueAccessor directive , the value of the ng control is null.

**Expected behavior**
The value of a ng control attached to an input having the NumberValueAccessor directive should be :
- a javascript number when the user entered a string representing a number
- null if the user has not entered anything
- **NaN if the user entered a string that not represents a number**

The first two cases are just, but the latter is false. In the latter two cases the value is always null.

**Reproduction of the problem**
The NumberValueAccessor being associated with a selector like input[type=number], simply declare a such input.
`<input type="number" [(ngModel)]="model.intValue" />`
Then get the value of the ng control after have entered a non numeric string in the input.

**What is the motivation / use case for changing the behavior?**
We need to distinguish between a lack of input and an input error. A lack of input can be valid if the field is optional, while a input error should be notified to the user to allow him to correct its input.

**Please tell us about your environment:**
Windows 7, Visual Studio 2015, Npm

* **Angular version:** 2.0.0-rc.X

* **Browser:** Firefox 48, but surely all browsers 
 
* **Language:** TypeScript 2.0

**Comment by fredgate** [comment]
I analyzed the problem, also I see where it comes from.

The code in the NumberValueAccessor directive seems good :
`this.onChange = (value) => { fn(value == '' ? null : parseFloat(value)); };`
as parseFloat return NaN if the string parameter does not represent a number.

However the problem is on this line.
Remember that the NumberValueAccessor directive is associated to selectors like input[type=number]. And the browser applies some rules to this element according to the WHATWG. In the [specifications](https://html.spec.whatwg.org/multipage/forms.html#number-state-(type=number)), there is a sanitization algorithm saying that for input number field's the browser is supposed to set the value to an empty string if the input isn't a valid floating point number :

> The value sanitization algorithm is as follows: If the value of the element is not a valid floating-point number, then set it to the empty string instead.

So the value of an number input field is null when the user enters nothing, or when he enters a non numeric string. So the NumberValueAccessor always calls parseFloat with a numeric string so it never produce the NaN value.

**Comment by fredgate** [comment]
So how to fix this ?

1. We can stop to use type=number, but rather type=text, and change/add selector of NumberValueAccessor. This does not seem like a great idea...

2. The registerOnChange method of NumberValueAccessor should detect invalid input, and in this case produces a NaN value to the control. This can be achieved by getting the validity property of the native input element. By testing this value, we could distinguish the three cases : no value, valid value, invalid value.

This latter solution seems good. What do you think ? Any remarks / suggestions ?

**Comment by pkozlowski-opensource** [comment]
> NaN if the user entered a string that not represents a number

So the convention is that if the invalid value is entered by a user we propagate `null` to the model. What you are really after is proper validation (I mean - you would like to distinguish control validity by it's `valid` state and not by the model value bound). The proper validation of number fields is going to be tackled in #2962 so I'm going to close this as a duplicate.

But your investigation / input is very valuable so I'm going to move it over to #2962. Thnx for this!
