### ISSUE TITLE
Perf: Cleanup generated code

### ISSUE THREAD

**Issue by vicb** [angular/angular#11647]
## Meta issue for possible cleanups
- Changes can be just emitting the same code differently, or introducing helper functions that the generate code uses. 
- This issue does not debate semantical changes
- Maybe have a look at the code produces for https://github.com/StephenFluin/ames
### Providers for `useValue: null`

``` ts
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
// ...
  get _LOCALE_ID_4():any {
    if ((this.__LOCALE_ID_4 == (null as any))) { (this.__LOCALE_ID_4 = (null as any)); }
    return this.__LOCALE_ID_4;
  }
// ..
```

Should be `return null;`
### Remove view factories, use view constructors directly

``` ts
function AppComp_View0Factory()... {
  ... 
  new AppComp_View0();
}
```

Should just pass around the constructor functions, no need for factories
## Use `switch` where possible

``` ts
class CompView {
  injectInternal(token, index) {
    if (token === SomeToken && ...) {}
    if (token === SomeToken && ...) {}
   ...
  }
}

// edit- vicb - based on a gist in 10812
// -> first level = index boundary check
// -> second level = switch
  if (((token === import19.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import17.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import22.FancyInputComponent) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._FancyInputComponent_8_4; }
    if (((token === import34.NG_VALUE_ACCESSOR) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NG_VALUE_ACCESSOR_8_5; }
    if (((token === import23.FormControlName) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._FormControlName_8_6; }
    if (((token === import35.NgControl) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NgControl_8_7; }
    if (((token === import24.NgControlStatus) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NgControlStatus_8_8; }
```

Should use a `switch` over the tokens. Analyze other places as well.

This might be a lot less problematic once we solve https://github.com/angular/angular/issues/11879
### Create a single module in `@angular/core` that reexports all helper functions used for codegen

Produces less `import` statements!
### Initialize fields directly in their declaration, and don't wait until the constructor.

This produces less code for TypeScript. Does not really impact production but
makes the generated code easier to read.
### Only create fields for HTMLElements / text nodes that are used in a property binding / used in an ElementRef.

Otherwise use local variables in the `createInternal` method.

**Comment by tbosch** [comment]
Done: Remove view factories, use view constructors directly

**Comment by vicb** [comment]
Generated code has changed and does not match what's described here any more
