### ISSUE TITLE
content projection with ng-content doesn't work in FINAL

### ISSUE THREAD

**Issue by david-bulte** [angular/angular#11659]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

I have a component, InboxCardComponent, into which other components can project content, i.e. like so:
InboxCardComponent : 
`<ng-content select="inbox-card-header"></ng-content>`

ConversationCardComponent:

```  
<inbox-card-header>
     <i class="fa fa-comment-o" aria-hidden="true"></i> {{conversatie.onderwerp}}
    <div class="pull-right">
      <span *ngIf="!expanded">{{conversatie.inboxDate | date:'dd/MM/yyyy'}}</span>
    </div>
  </inbox-card-header>
```
When loading the page, I get errors like 

> 'inbox-card-header' is not a known element

Note that I **have** declared InboxCardComponent, but obviously **not** inbox-card-header, as this merely specifies the ng-content [select] attribute.

**Expected behavior**

The expected behavior is that the content of the <inbox-card-header> tag is inserted in the <ng-content> point. This worked up till RC5. When migrating to FINAL, it doesn't work anymore.

* **Angular version:** 2.0.0-FINAL

**Comment by pkozlowski-opensource** [comment]
This is a documented breaking change in RC5: https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-2

> By default, Angular will error during parsing on unknown properties, even if they are on elements with a - in their name (aka custom elements). If you application is using custom elements, fill the new parameter @NgModule.schemas with the value [CUSTOM_ELEMENTS_SCHEMA]

You've got several options for your specific use case:
* add the schema info for `inbox-card-header`
* use CSS class or an attribute to mark header element to be projected.
