### ISSUE TITLE
[Suggestion] Use GitHub Projects instead of "Tracking:" issues

### ISSUE THREAD

**Issue by laco0416** [angular/angular#11655]
There are many "Tracking" issues in this repo. 
If we, contributors, can see current conditions of WIP projects easily, we can help shorthanded place effectively.
I think GitHub Projects is a very good tool to share that. How do you think it?

**Comment by vicb** [comment]
Might be a good idea.

We need to evaluate and discuss in the team.

Thanks for the tip.

**Comment by vicb** [comment]
we will probably use it. thanks.
