### ISSUE TITLE
Zone.js has detected that ZoneAwarePromise has been overwritten

### ISSUE THREAD

**Issue by BenDevelopment** [angular/angular#11650]
I've updated my project to rc7 and I have this error now :
`Unhandled promise rejection Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.`

Am I the only one ?

**Comment by vicb** [comment]
please try to update the zone package and use angular 2.0.0

**Comment by BenDevelopment** [comment]
I have updated the zone package and changed angular from cr7 to 2.0.0 and I still have the problem.
Here is my package.json maybe it can helps:
```
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "docker-build": "docker build -t ng2-quickstart .",
    "docker": "npm run docker-build && docker run -it --rm -p 3000:3000 -p 3001:3001 ng2-quickstart",
    "pree2e": "npm run webdriver:update",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "postinstall": "typings install",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings",
    "webdriver:update": "webdriver-manager update"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/router": "3.0.0-rc.2",
    "@angular/upgrade": "^2.0.0",
    "angular2-in-memory-web-api": "0.0.18",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.27",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings": "^1.0.4",
    "canonical-path": "0.0.2",
    "http-server": "^0.9.0",
    "tslint": "^3.7.4",
    "lodash": "^4.11.1",
    "jasmine-core": "~2.4.1",
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^0.2.3",
    "karma-cli": "^0.1.2",
    "karma-htmlfile-reporter": "^0.2.2",
    "karma-jasmine": "^0.3.8",
    "protractor": "^3.3.0",
    "rimraf": "^2.5.2"
  },
  "repository": {}
}
```

**Comment by BenDevelopment** [comment]
The problem comes from a conflict with awesome-font import :
`<script src="https://use.fontawesome.com/5eec53e034.js"></script>`
Sorry for the useless noob issue (but maybe it can help another noob :) ).

**Comment by jvendryes** [comment]
I'm getting the same error going from RC.6 to 2.0.0 (not using fontawesome^), my zoneJS version 0.6.23 as well (as Quickstart Guide shows), not 0.6.21 as RC.7 upgrade shows...

**Comment by vicb** [comment]
When reporting issue please fill out the template. There is no way we can help if we don't have a repro and details about your env. Thanks.

**Comment by AntJanus** [comment]
Hey everyone,

I may have an idea of what's happening. I had the same issue and all I needed to do was switch the order of imports for `zone.js` and `core-js/shim`. I had a feeling the core-js shim was overwriting the zone.js promise and it, in fact, was.

So instead of doing:

```
require('zone.js');
require('core-js/shim`);
```

I did:

```
require('core-js/shim');
require('zone.js');
```

And that fixed the problem. Hope that helps!

**Comment by JohnnyClutch** [comment]
Anyone know how to get webpack to load core-js first in development server mode?  All the imports and requires I've tried for the last 2 days haven't had any effect.  It's funny, I break in Chrome where zone.js throws the error, and the global window in the debug window has ZoneAwarePromise as its promise implementation.

**Comment by AntJanus** [comment]
@JohnnyClutch that's what I did. I simply did:

```
require('core-js/shim');
require('zone.js');
```

and then the rest of the imports. I'm using it [on a pet project](https://github.com/AntJanus/omen)

Checkout my [main.ts](https://github.com/AntJanus/omen/blob/master/app/scripts/main.ts)
