### ISSUE TITLE
angular2 forms, selected item in <select> element

### ISSUE THREAD

**Issue by hanijizan** [angular/angular#11669]
Here's the `FormBuilder`:

    let valuesArray = fb.array([
            fb.group({ name: 'one' }),
            fb.group({ name: 'two' }),
            fb.group({ name: 'three' }),
            fb.group({ name: 'four' })
        ]);

    this.form = fb.group({
        values: valuesArray,
        selectedValue: valuesArray[0]
    })

The template:

    <select formControlName="selectedValue">
       <option *ngFor="let controlGroup of form.controls.values.controls">
         {{ controlGroup.controls.name.value }}
       </option>
    </select>

This throws error `control.registerOnChange is not a function` which is fixed by removing the `formControlName` from `<select>` element, but how else would you keep track of selected items in the list?

**Comment by kara** [comment]
@hanijizan It looks like you're trying to hook a select control up to a parent form. If that's all you're trying to do, creating a FormArray with nested FormGroups won't do what you want.  Try binding to the option values instead. See example here: http://plnkr.co/edit/SlyZNVOA2tHTpJ4V9NrJ?p=preview.
