### ISSUE TITLE
Angular 2.0.0 build errors - "Duplicate identifier"

### ISSUE THREAD

**Issue by ssashok10** [angular/angular#11665]
I'm submitting a bug report.

Error :
   So many build errors like the below,

`` Error		Build:Duplicate identifier 'backdrop'.	..\typings\browser\ambient\bootstrap\index.d.ts	11`	`

Below are the package configuration. I am using Visual Studio Enterprise Edition with update 3.

package.json

```
{
  "name": "xxx",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "postinstall": "typings install",
    "typings": "typings"
  },
  "license": "ISC",
  "devDependencies": {
    "typescript": "^1.8.10",
    "typings": "^1.0.4"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",

    "systemjs": "0.19.27",
    "core-js": "^2.4.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.12",

    "bootstrap": "^3.3.6",
    "jquery": "^3.0.0",

    "angular2-in-memory-web-api": "0.0.9",
    "ag-grid": "6.0.1",
    "ag-grid-ng2": "6.0.2"
  }
}

```

**typings.json**

{
  "ambientDependencies": {
    "bootstrap": "github:DefinitelyTyped/DefinitelyTyped/bootstrap/bootstrap.d.ts#56295f5058cac7ae458540423c50ac2dcf9fc711",
    "jquery": "github:DefinitelyTyped/DefinitelyTyped/jquery/jquery.d.ts#56295f5058cac7ae458540423c50ac2dcf9fc711",
    "TypeLite": "file:scripts/TypeLite.Net4.d.ts",
    "core-js": "registry:dt/core-js#0.0.0+20160602141332"
  }
}

**tsconfig.json**

{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts",
    "Scripts/TypeLite.Net4.d.ts"
  ]
}

**Comment by pkozlowski-opensource** [comment]
It looks like those errors are coming from typings for bootstrap or our project setup so nothing directly related to Angular itself. Please use one of the support channels where there are many good folks offering help: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
