### ISSUE TITLE
Inputs and Outputs shadowing not consistent

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#11666]
Currently having an `@Input` on a directive / component with the same as a native property name will shadow input binding (that it, a directive will get the bound value, not the native element). Apparently different rules apply to `@Output`s.

In this plunker https://plnkr.co/edit/TDCsPTWeRvgALildXmkt?p=preview there is a component with the `change` output. It turns out that adding `(change)` event handler to this component will pick up bubbling `chnage` events which I find surprising / inconsistent with rules in place for `@Input`s.

I wonder if the the current behavior is correct and steams from the conscious design decision? Or rather a side effect of the existing implementation?

**Comment by zoechi** [comment]
#4059 seems related

**Comment by pkozlowski-opensource** [comment]
Yes, this is the same as #4059, closing as a duplicate.
