### ISSUE TITLE
How do I set non-standard attributes on the DOM Element

### ISSUE THREAD

**Issue by dylanb** [angular/angular#1167]
I know that I can inject a property setter into the constructor and use this to update a property, I have not been able to get this property to propagate to the DOM for non-standard properties such as:

1. role
2. all the aria-* properties

I may be missing something, please point me in the correct direction

**Comment by mlaval** [comment]
You can use property setters to set attributes, classes and styles with the same syntax as in square brackets in templates. See the spec here:
https://github.com/angular/angular/blob/master/modules/angular2/test/core/compiler/element_injector_spec.js#L78-L110

**Comment by pkozlowski-opensource** [comment]
Yep, `role` and `aria-*` are not properties but attributes and as such can be set as any other attribute:
* in HTML: `<div [attr.role]="roleExp"`
* in a prop setter: `@PropertySetter('attr.role') roleSetter`

Now, maybe we should rename `@PropertySetter` to sth else?
