### ISSUE TITLE
Perf: Fully encapsulate styles during compile / stamp out stylesheets only once

### ISSUE THREAD

**Issue by tbosch** [angular/angular#11673]
Right now, stylesheets are compiled into strings that contain replacement markers. During runtime, each component that uses the stylesheet replaces these markers with the component id and creates a `<style>` tag with its version of the styles.

This has several downsides:
- shared stylesheets are only transferred once, but stamped out multiple times for each component using the shared style sheet
- we need an own `Renderer` instance per component type that knows how to automatically add the corresponding `<style>` tags on the first user of the component and that has a special version of `createElement` that will add the encapsulation attributes. This indirection slows down rendering.

How to do this:
- create a unique id per stylesheet (maybe a hash of the file name)
- a component needs to encapsulate its elements with attribute markers for all stylesheets that should apply.

**Comment by tbosch** [comment]
Note: shared stylesheets might not be so important when using sass, as sass already inlines things.

**Comment by tbosch** [comment]
Note: won't work with multi apps as there can be the same component in different versions.

**Comment by tbosch** [comment]
Broader idea: maybe calculate which styles apply on each element and then either inline the styles to the element, or have a hash per css class.

**Comment by vicb** [comment]
inlining the styles might change the specificity, no ? (I am not a specialist - @matsko ?)

**Comment by tbosch** [comment]
Closed in favor of #https://github.com/angular/angular/issues/11682

**Comment by tbosch** [comment]
@vicb yes. This would need to be opt in, and even separate by a file extension...
