### ISSUE TITLE
`provide: X, useClass: X` is not equivalent to `X`

### ISSUE THREAD

**Issue by tbosch** [angular/angular#11675]
Replacing `{provide: X, useClass: X}` with `X` should be equivalent.

However, right now, the instantiation order is different if the class as an `ngOnDestroy` hook which triggers eager instantiation: `useClass` keeps lazy instantiation, a type provider uses eager instantiation in this case.

Investigate: Is the `ngOnDestroy` method not called at all for non type providers?

Regarding eager instantiation: See https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/provider_analyzer.ts#L483

**Comment by matjanos** [comment]
I have the same problem ;( 
After transpilation code works like this:
![di_bug1](https://cloud.githubusercontent.com/assets/2236369/19429290/2a541050-944f-11e6-9d2d-01f5b29f5498.png)
![di_bug2](https://cloud.githubusercontent.com/assets/2236369/19429293/2c43f13c-944f-11e6-88a8-83f11a546b14.png)

But result is:
![di_bug3](https://cloud.githubusercontent.com/assets/2236369/19429297/2fbec800-944f-11e6-8ebd-e565fb561a1a.png)

**Comment by DzmitryShylovich** [comment]
@tbosch appears to be fixed

> if the class as an ngOnDestroy hook which triggers eager instantiation: useClass keeps lazy instantiation, a type provider uses eager instantiation in this case.

can't reproduce it. both providers instantiated eagerly as expected

> Investigate: Is the ngOnDestroy method not called at all for non type providers?

yes, it's called

https://plnkr.co/edit/wsEJWaJ2hYTEqdoA7Ab1?p=preview

**Comment by DzmitryShylovich** [comment]
@tbosch I believe this can be closed

**Comment by DzmitryShylovich** [comment]
@tbosch after https://github.com/angular/angular/pull/15070 I think this's not relevant anymore
