### ISSUE TITLE
Http shorthand methods should call this.request

### ISSUE THREAD

**Issue by felixfbecker** [angular/angular#11670]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Since HTTP interceptors are no longer a thing in Angular 2, to get something similar, it is best to override the `Http` service to introduce something like an `APIService` (which is nicer anyway). Now let's say the APIService should always set an API token to be send as an `Authorization` header. This could be as simple as as only overriding the `request` method, if all other shorthand methods simply delegated to `request()` with `return this.request()`. But instead, they call the internal function `httpRequest`, which cannot be overridden. This means a lot of boilerplate, because we have to override every single shorthand method. It would be a non-breaking change to change this.

You can see it in this example (first google result for "angular2 http interceptor"): https://www.illucit.com/blog/2016/03/angular2-http-authentication-interceptor/

That example also uses a `getRequestOptionArgs` method to normalize the options before modifying (because you can pass a hash, `Request` object etc). It would be nice to have this as a method aswell, so we don't have to reimplement it.

Source: https://github.com/angular/angular/blob/master/modules/%40angular/http/src/http.ts#L136-L138

**Comment by JimmyBoh** [comment]
Hey there, I am implementing similar functionality to what was described above, so this feature is very much appreciated!

Is there any way to tell when (semver-wise, not calendar-wise) changes in a commit will be published? I just want to know which bump (`major`, `minor` `patch`) this will be released as (i would think `minor`).

What is the best way to find out if a change is going to be in an upcoming release? (preview builds, milestones, etc.)
