### ISSUE TITLE
Perf: Trim whitespace

### ISSUE THREAD

**Issue by tbosch** [angular/angular#11679]
Collapse spaces to at least one space.
Need to handle corner cases like
- `<pre>`
- css `white-space`
- in general, allow users to force to keep spaces either for the whole component or for a certain part of the template

**Comment by vicb** [comment]
If you mean in the template, don't think it's possible (what about `<pre>` or CSS `white-space` - I don't think is possible to handle those at compile time)

**Comment by SmaugTheGreat** [comment]
Wasn't this already rejected [here](https://github.com/angular/angular/issues/11533)?

**Comment by robwormald** [comment]
I've been using https://github.com/kangax/html-minifier whilst testing locally, and with a couple of options tweaked (namely retaining case sensitivity) it makes a nice little difference.

**Comment by SmaugTheGreat** [comment]
Yes, true, but the html-minifier only works if you put the HTML into seperate template files. If you use inline templates then the html minifier doesn't do the job unfortunately. I prefer inline templates over seperate files because I like to have the code that belongs together in one place. It's tiresome having to switch between files every time I change something in the template.

**Comment by tbosch** [comment]
To summarize:
- Removing whitespace altogether changes the way browsers do layout, as they will add a separator. 
- Collapsing multiple whitespaces into one is usually safe, but also breaks the layout for same elements (e.g. <pre>, or any element with a specific style that tells the browser to render all whitespaces).
- we could have a special encoding in the template, something like `ws(20)` to indicate 20 whitespaces. This could reduce the code size before gzip. However, I am not sure what the impact after gzip is.

**Comment by pkozlowski-opensource** [comment]
@tbosch on my "test" application I'm seeing ~5% code reduction (after gzip) with whitespace removal. Can share a repo if needed.

Could we add this as an option maybe so people can turn it on and decide if the risk of breaking layout is worth this few %?

**Comment by SmaugTheGreat** [comment]
I personally want it to break the layout, that's one of the reasons I'm using minification. Because I want to indentate my elements without the spaces being visible inside some of my elements.

**Comment by Megamind2301** [comment]
@robwormald Can you share how you did that? I will have go with it till this feature is added.

**Comment by vicb** [comment]
This has been implemented.

You can set `preserveWhitespaces` to `false` to optimize the whitespaces. The default is `true` in 4.x and 5.x and will be changed to `false` in 6.x.

You can also set this at a component level.

**Comment by newsash** [comment]
Just for someone, who wants to preserve certain whitespaces: `ngPreserveWhitespaces`(preserves all whitespaces in the element) and `&ngsp;` (places one whitespace). It's uneasy to find in the documentation, this issue was the first I found on the topic.
