### ISSUE TITLE
Perf: Create individual text nodes for the interpolated expressions

### ISSUE THREAD

**Issue by tbosch** [angular/angular#11674]
- allows us to get rid of string concatenation in JavaScript, see [`view_utils#interpolate`](https://github.com/angular/angular/blob/master/modules/@angular/core/src/linker/view_utils.ts#L92).
- allows to check the individual parts of the interpolation instead of the concatenated result.

This needs to be measured, especially regarding costs for creating views.. Maybe instead
- create `interpolate1`, `interpolate2`, ... and use `pureFnProxy` to prevent calculating the string concatenation (similar to pipes). Needs to be measures as well.

**Comment by tbosch** [comment]
But only check the parts of the interpolation instead of the final string

**Comment by DzmitryShylovich** [comment]
@tbosch is this still valid in new view engine?

**Comment by tbosch** [comment]
With the new view engine, we already check each part of the interpolation individually. However, we could still benchmark creating just one text node vs creating multiple text nodes.

This might especially trade creation time for update time, and needs to be measured carefully...

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one for now as we don't have any immediate plans to change the way we generate text nodes.
