### ISSUE TITLE
debugger don't tell if you have problem in your html spec

### ISSUE THREAD

**Issue by tmleeek** [angular/angular#11687]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

when i have ul element inside p element the app will not work and will not report that the app have html spec problem
**Expected behavior**

the debugger should inform me that i have problem with my html and its violate html spec instead of making me lost my way to fix the problem . 

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

all apps thats have this tiny problem will not work and the developers will lost their way to fix . 

**Please tell us about your environment:**

OSX , WEBSTORM , nonr , nodejs
* **Angular version:** 2.0.0-rc.X

2.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 all
* **Node (for AoT issues):** `node --version` =   
5.x

**Comment by ericmartinezr** [comment]
This [plnkr](http://plnkr.co/edit/2U5nuYiWIjKXeRMsUM3s?p=preview) throws

```
 Template parse errors:
	Unexpected closing tag "p" ("
	    <p>
	      <ul></ul>
	    [ERROR ->]</p>
```
Is that what you mean?

**Comment by tmleeek** [comment]
i couldnt see that in browser inspector , how did you see that error ?
 *Unexpected
closing tag "p" *

yes , i meant it should tell that its violate html5 spec or something like
that it should not compile if it not work , but i will maybe satisfy if i
saw how did saw the error ?

**Comment by ericmartinezr** [comment]
When loading the plnkr go to the console and you'll see this at first

```
VM317 zone.js:192 Error: (SystemJS) Error: Template parse errors:(…)
```
Note the three dots `(...)`, click on that and it will expand the error message. The little arrow at the left doesn't expand the full error message just in case.

I'm not sure if it is possible at all, but imho a better error message specifying that's not valid HTML would be better just like you said.

@pkozlowski-opensource what do you think?

**Comment by tmleeek** [comment]
ok i was able to see this now , but in my localhost i dont see any template
parse error
only errors that i do not know about

**Comment by tmleeek** [comment]
i am very sorry to take of your time
 i have just saw it very clear , i just install the latest angular with npm
and now its very clear , i also used atom ide with W3C Markup Validation
Service Report
