### ISSUE TITLE
@Host Decorator not working for regular providers (viewProviders are working)

### ISSUE THREAD

**Issue by choeller** [angular/angular#11681]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

Currently it's not possible to use the @Host decorator to inject regular providers. Recreating the example from the docs (https://angular.io/docs/ts/latest/api/core/index/Host-decorator.html) shows that although the provider is present it is not injected when @Host decorator is added.
This plnkr contains the exact code from the docs and prints:
```
os is null null
hs is NOT null null // this is wrong / buggy!
```
http://plnkr.co/edit/cSE4vNtty72q5UuEF250?p=preview

**Expected behavior**
@Host decorator should work when used with providers property

**Reproduction of the problem**

Here is the plnkr

http://plnkr.co/edit/cSE4vNtty72q5UuEF250?p=preview

**What is the motivation / use case for changing the behavior?**

Being able to use the @Host decorator to stop lookup of providers at the next host element

**Please tell us about your environment:**

* **Angular version:** 2.0.0

* **Browser:** [all  

 
* **Language:** [TS 2]

**Comment by choeller** [comment]
@vicb Here is the new ticket

**Comment by vicb** [comment]
Many thanks for your report, the PR is pending, ready to be merged.

The problem was that `viewProviders` should be used (there is no content in the example) so doc only.
