### ISSUE TITLE
AOT Compiler Producing simple js files and not Outputting ngfactory files

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#11689]
I am following the below tutorial:

https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**I have below tsconfig-aot.json placed in my App directory**
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules",
    "typings"
  ],
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit": true
  }
}
```

**My main.ts is below:**

```
/// <reference path="../typings/browser/ambient/es6-shim/index.d.ts" />
/// <reference path="../typings/typings.d.ts" />

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule }              from './app.module';
import { enableProdMode } from '@angular/core';

enableProdMode();

platformBrowserDynamic().bootstrapModule(AppModule);
```

**My am compiling using the below command:**

D:\MyProject\node_modules\.bin\ngc -p D:\MyProject\app\tsconfig-aot.json

When I run above command, it creates a new folder in **App** directory with name **aot** that only contains node_modules folder inside which there are two more folders @angular and @angular2-material which have the ngfactory files for @angular and angular2-material.

Running above command doesn't generate ngfactory for my app but instead it generates the js files for the components and modules in the app folder (i.e. the folder containing the ts files of my app).

Can anyone please guide?

**Comment by vicb** [comment]
I am not sure of Windows is fully supported as of today. Please use our support channel below to get more help

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by yuanfeiz** [comment]
I ran into the similar issue in OSX, after 3 hours late night debugging.. The issued with my settings is caused by the typescript 2.1.0-dev. When I downgraded to 2.0.2, it works.

**Comment by vicb** [comment]
@yuanfeiz thanks for reporting

**Comment by arandehkharghani** [comment]
I ran into the same problem and downgrading typescript didn't work as I ran into the previous issue I had with typescript which was 

> function calls are not supported. consider replacing the function or lambda with a reference to an exported function

**Comment by InfinityOne** [comment]
> but also generates .js and .map files in the source folder...
somehow to avoid this?

**Comment by spock123** [comment]
Hey guys, I managed to solve id.
What you need to do, is add "genDir" to angularCompilerOptions.

Example:

```
 "angularCompilerOptions": {
    "genDir": "./compiled",
    "skipMetadataEmit" : true
    },
```

Also, add "outDir" to the compilerOptions:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "./compiled",
   .... and so on

```

**Comment by InfinityOne** [comment]
@spock123 omg, can't believe that was so simple. THX!

**Comment by spock123** [comment]
@InfinityOne  had the same feeling after googling my ass off... you're welcome, glad to help

**Comment by jkobylec** [comment]
I got this error using a pre-release build of TypeScript 2.1 ( 2.1.0-dev.20161014, via typescript@next) using @angular/compiler@2.1.0. Not filing a new issue (unless you want me to...) as I acknowledge it's somewhat of a long shot to expect this setup to work in the first place, but nonetheless wondering if anyone has gotten it to work with a pre-release build of TypeScript 2.1?

**Comment by maburdi94** [comment]
@yuanfeiz Way to go!

**Comment by gruppjo** [comment]
@vicb, please consider reopening this issue. To me this does seem like a bug or at least it's silently failing.

Just as @naveedahmed1 described the `aot/` folder gets created and the `aot/node_module` folder contains the necessary `*.ngfactory.js` files but **no other files** are created. **At all**. Especially the `*.ngfactory.js` files for the files in `app/`.

I tried many configurations starting with the one over at https://angular.io/docs/ts/latest/cookbook/aot-compiler.html but couldn't get it to run. Different typescript versions, different compiler versions and with typings or @types. I also tried @spock123 and @InfinityOne's solutions but they just output the regular `*.js` and `*.js.map` files to `aot/` still no `*.ngfactory.js` files.

In any case following runs without errors, but fails to create the `*.ngfactory.js` files other than in `aot/node_modules/`:
```sh
"node_modules/.bin/ngc" -p tsconfig-aot.json
```
```js
// tsconfig-aot.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "types": []
  },

  "files": [
    "app/app.module.ts",
    "./typings/index.d.ts"
  ],

  "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : true
 }
}
```

### Example1: 
with `@angular/compiler-cli@0.6.1` and typings: https://github.com/gruppjo/angular-quickstart/tree/aot-typings
To reproduce:
```sh
git clone
git checkout aot-typings
npm i
npm run aot
```
### Example2:
with `@angular/compiler-cli@2.1.2` and @types: https://github.com/gruppjo/angular-quickstart/tree/914c4f679848633e9ce5fd7afbf71d4e31d09d88
To repdocue:
```sh
git clone
git checkout 914c4f679848633e9ce5fd7afbf71d4e31d09d88
npm i
npm run aot
```

Hope this helps

**Comment by kesarion** [comment]
@gruppjo @vicb  I fully agree with Jonathan, this is a real issue with Typescript 2.1, now in [RC](https://blogs.msdn.microsoft.com/typescript/2016/11/08/typescript-2-1-rc-better-inference-async-functions-and-more/). Is no angular dev going to look into this until it comes out and the flood of issues comes? I had opened issue #2600 with this issue, but that was also ignored, it would be best to solve this before 2.1 comes out. I've looked into it myself in the compiler src, but I couldn't get to the bottom of it; an angular compiler dev would surely be able to fix this much faster.

**Comment by arsenys** [comment]
I have same problem. No ngfactory files output by ngc

**Comment by pdavin** [comment]
+1, experiencing the same problem.

**Comment by vladbrk** [comment]
I follow the example on https://angular.io/docs/ts/latest/cookbook/aot-compiler.html and It does not work for me too. No ngfactory files in my dir.
angular - 2.2.4, 2.3.0
typescript - 2.0.2, 2.1.4

But if you switch to angular 2.0.0 and ngc 0.6.0, ngfactory files will be generated.

**Comment by lecogiteur** [comment]
Same problem with node JS 7.2.1, Typescript 2.1.4 and angular (and angular cli) 2.3.0 .

When I have downgraded Typescript to 2.0.10, it works fine.

**Comment by petermezei** [comment]
Hi guys,
I have been trying to solve this issue for 64 hours and nothing. I am a bit tired. Could you help me please?

Here is the project: https://github.com/slamby/slamby-website

Right now I do not use the aot compilation for production, everything is ready to start it, but I have the same issue, generating ngFactory fiels: there are no ngFactory files generated, just js files.

My tsconfig.aot.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "./aot",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [ "./node_modules/@types" ],
    "types": [
      "node"
    ]
  },
  "files": [
    "./src/app/app.module.ts"
  ],
  "angularCompilerOptions": {
   "genDir": "./aot",
   "skipMetadataEmit" : true
 }
}
```

Command to execute ngc:
> node_modules/.bin/ngc -p tsconfig.aot.json

Output files print screen:

![image](https://cloud.githubusercontent.com/assets/18461114/21105702/801c0868-c08b-11e6-85fb-3cbdd99c5f61.png)

Angular pacakages:

```json
    "@angular/common": "~2.3.0",
    "@angular/compiler": "~2.3.0",
    "@angular/compiler-cli": "^2.3.0",
    "@angular/core": "~2.3.0",
    "@angular/forms": "~2.3.0",
    "@angular/http": "~2.3.0",
    "@angular/platform-browser": "~2.3.0",
    "@angular/platform-browser-dynamic": "~2.3.0",
    "@angular/platform-server": "^2.3.0",
    "@angular/router": "~3.3.0",
```
Typescript:
```json
"typescript": "^2.0.2",
```

Could you please help me?

**Comment by maburdi94** [comment]
You might try angular 2.2.4 as well, instead of 2.3.0. Also, type "npm  list --depth=0" to be sure that the installed packages are accurate to your json file and that there are no peer dependency problems.

**Comment by DOMZE** [comment]
Using Angular 2.3.1, i couldn't get the ngfactory files with typescript 2.1.4, downgrading to 2.0.10, i was able to generate them.

**Comment by petermezei** [comment]
Hi, i solved it. You can check witch typescript an angular versions I used. [https://github.com/slamby/slamby-website](https://github.com/slamby/slamby-website)

**Comment by Alberto2686** [comment]
Angular 2.4.0 and TS 2.4.1 doesn't work. I had to downgrade to TS 2.0.10 as well in order to generate the correct files

**Comment by kamarouski** [comment]
Angular 2.4.x doesn't work on windows. Tried typescript versions 2.0.10, 2.1.1 and 2.1.4

Only got it working with Angular 2.3.1 and Typescript 2.0.10 

It looks like the issue can be reopened.

**Comment by Kopleman** [comment]
Got it working after downgrading Typescript version to 2.0.10. Angular is 2.4.0

**Comment by MarkPerryBV** [comment]
Working for me on Windows using NG 2.4.1, TS 2.0.2 (tsc --v = 2.0.3)

**Comment by piq9117** [comment]
i tried what has been said here: angular 2.4.1 and typescript 2.1.4. its not working for me
Heres my tsconfig. i took out the `libs: ["es2015", "dom"]` because it conflicts with core-js
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "./dist/out-tsc",
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
        "node_modules/@types"
    ]
  },
  "exclude": ["node_modules", "node_modules/@types"],
  "files": [
    "src/app/app.module.ts",
    "src/main.ts"
  ],
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit": true
  }
}
```
its not producing any ngFactory files, just the `node_modules`

**Comment by mlc-mlapis** [comment]
@MarkPerryBV How is it possible?

**Comment by sckorrapati** [comment]
Same issue. On MAC. TS 2.1.4 and NG 2.1.4

**Comment by dimpu** [comment]
Same issue. On MAC. TS 2.1.4 and NG 2.1.4

**Comment by DzmitryShylovich** [comment]
Angular doesn't support ts 2.1+. The latest supported version is 2.0.10

**Comment by hermankan** [comment]
@vicb, since many people are still experiencing the issue, not only on Windows, does it make sense to reopen it?

**Comment by BadariKavali** [comment]
In Angular 2, I am trying to implement AOT functionality, but unable to generate the *.ngfactory files from AOT compiler in Windows machine and able to get *.js & *.js.map files.

Could you please do the needful at the earliest.

Thank you in advance.

**Using below dependencies:**
"dependencies": {
    "@angular/common": "~2.2.0",
    "@angular/compiler": "~2.2.0",
    "@angular/core": "~2.2.0",
    "@angular/forms": "~2.2.0",
    "@angular/http": "~2.2.0",
    "@angular/material": "^2.0.0-beta.1",
    "@angular/platform-browser": "~2.2.0",
    "@angular/platform-browser-dynamic": "~2.2.0",
    "@angular/platform-server": "~2.2.0",
    "@angular/router": "~3.2.0",
    "@angularclass/conventions-loader": "^1.0.2",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",

    "angular-in-memory-web-api": "~0.1.15",
    "systemjs": "0.19.40",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.26",
    "jquery": "3.1.1",
    "jquery-sortable": "^0.9.13",
    "bootstrap": "3.3.7",
    "font-awesome": "4.7.0",
    "ng2-dragula": "^1.2.2",
    "ng2-toastr": "1.3.6",
    "dragula": "3.7.2",
    "d3": "4.7.1",
    "types.d3": "0.1.1"

  },
  "devDependencies": {
    "@angular/compiler-cli": "~2.2.0",
    "concurrently": "^3.1.0",
    "lite-server": "^2.2.2",
    "typescript": "~2.1.5",
    "canonical-path": "0.0.2",
    "http-server": "^0.9.0",
    "tslint": "^4.3.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-htmlfile-reporter": "^0.3.4",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "4.0.14",
    "webdriver-manager": "10.2.5",
    "rimraf": "^2.5.4",
    "@types/node": "^6.0.46",
    "@types/jasmine": "^2.5.36",
    "@types/selenium-webdriver": "^2.53.33",
    "systemjs-builder": "^0.15.34",
    "gulp": "3.9.1",
    "gulp-concat": "2.6.1",
    "gulp-cssmin": "0.1.7",
    "gulp-uglify": "2.0.0",
    "gulp-sourcemaps": "^1.9.1",
    "gulp-tslint": "^7.0.1",
    "gulp-typescript": "^3.1.3",
    "del": "2.2.2",
    "d3": "4.7.1",
    "types.d3": "0.1.1"
  },

**Comment by darin-cardin** [comment]
Thank you so much!! Adding "outDir" to the compilerOptions fixes the generated js and map files in my src folders. Funny, it makes no mention of this in the AOT cookbook docs. The documentation on angular2 AOT is extremely poor.
