### ISSUE TITLE
npm install error (fsevents package)

### ISSUE THREAD

**Issue by callenmas** [angular/angular#11685]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Trying to install npm modules for Angular on my Mac.

**Expected behavior**
Successful run of 'npm install' command.

**Reproduction of the problem**
Downloaded latest Angular source code.
Installed node and npm per this pre-requisite - https://github.com/angular/angular/blob/master/DEVELOPER.md
Changed directory to angular.

Ran 'npm install' from angular directory.  Getting this error:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! fsevents@1.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@1.0.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/callenm/workspace/angular/npm-debug.log

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Mac OSX El Capitan - 10.11.6
Darwin 15.6.0
node v6.5.0
npm  v3.10.3

**Comment by vicb** [comment]
Same setup & same error for me with node 6.5.0

`npm i fsevents@1.0.14` seems to work though

**Comment by callenmas** [comment]
I did a git pull --rebase and ran npm install again.  It succeeded.  Onto the next step.

Thanks vicb@.

**Comment by comfroels** [comment]
I'm on Windows 10 and got that same error until I updated to node 6.8. Now I get pretty much the same message, just formatted differently:
```
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

**Comment by DzmitryShylovich** [comment]
`fsevents` is an OSX-only module and you cannot install it on Windows.

**Comment by comfroels** [comment]
Yeah, my bad, the problem _really_ was me having node 6.8, after reading `DEVELOPER.md` you need node < 6

**Comment by obendesmond** [comment]
Try 
"npm install -f"
