### ISSUE TITLE
app.component.css path error

### ISSUE THREAD

**Issue by zoulincheng** [angular/angular#11697]
**I'm submitting a ...**  (check one with "x")
app.component.css and app.component.ts are in the same dir "app", when use this cfg 
@Component({
    moduleId: module.id,
    selector: 'my-app',
    template: `<h1>{{title}}</h1>
               <nav>
                 <a routerLink="/dashboard">Dashboard</a>
                 <a routerLink="/heroes">Heroes</a>
               </nav>
               <router-outlet></router-outlet>
               `,
    styleUrls:['app/app.component.css'],               
})
error, can't find app.component.css, path error "404 GET /app/app/app.component.css"
use this cfg 
@Component({
    moduleId: module.id,
    selector: 'my-app',
    template: `<h1>{{title}}</h1>
               <nav>
                 <a routerLink="/dashboard">Dashboard</a>
                 <a routerLink="/heroes">Heroes</a>
               </nav>
               <router-outlet></router-outlet>
               `,
    styleUrls:['app.component.css'],               
})
work rite

**Comment by christiandreher** [comment]
Thats expected behaviour. `styleUrls` is relative to the component typescript file

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by pkozlowski-opensource** [comment]
Sound like a support question so going to close this one.
