### ISSUE TITLE
Two ways binding and an array

### ISSUE THREAD

**Issue by ranb2002** [angular/angular#11693]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
With a two ways binding and an array, when we type something into a input field, the next field is filled with the same text if that field had the same value. By exemple, imagine there are input fields (or see the plunker below):

* [**1**, 2, 3, 3] -> [**2**, 2, 3, 4] - I change the first input and only the first value is updated. OK
* [**2**, 2, 3, 4] -> [**3**, **3**, 3, 4] - I change the first input and the first and the second value are updated. Not OK

**Expected behavior**
The next input field shouldn't change.

* [**1**, 2, 3, 3] -> [**2**, 2, 3, 4]
* [**2**, 2, 3, 4] -> [**3**, 2, 3, 4]

**Reproduction of the problem**
See this plunker (app.ts): [https://plnkr.co/edit/u9AnLtDfO2HUP4szHP4K?p=info](https://plnkr.co/edit/u9AnLtDfO2HUP4szHP4K?p=info)

* **Angular version:** 2.0.0

* **Browser:** [ all ] 
 
* **Language:** [ TypeScript 1.8.10 ]

**Comment by pkozlowski-opensource** [comment]
You need to use `trackBy` for those situations: https://plnkr.co/edit/wOhwK49beUdhIRlC5y5A?p=preview

* https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html
* http://angularjs.blogspot.fr/2016/04/5-rookie-mistakes-to-avoid-with-angular.html

**Comment by ranb2002** [comment]
Thank you!
