### ISSUE TITLE
Rename HostBinding or add a different decorator for global bindings

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#11699]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

We use `@HostBindnig` and `@HostListener` decorators to bind to the host element. We also use the same decorator to bind to `window` using the `:` syntax, and **window is not the host element**, leading to confusing syntax.

**Suggested behavior**

After a short discussion with @DzmitryShylovic [on Gitter](https://gitter.im/angular/angular?at=57de95b5df21a75730089487) here are some alternatives:
- Add a  `@WindowListener` decorator specifically to replace current syntax `window:`
- Add a `@GlobalListener` decorator for general global stuff (including `window:`, `body:` and potentially `title:`, see #11698).
- Deprecate `@HostListener` and use `@Binding` for all of these, where leading `host:` would be optional since that's the most common use-case

IMO the last alternative makes the most sense.

**What is the motivation / use case for changing the behavior?**

Easier to understand and consistent syntax.
- **Angular version:** 2.0.0
- **Browser:** all
- **Language:** TypeScript

**Comment by DzmitryShylovich** [comment]
Related to https://github.com/angular/angular/pull/10596#issuecomment-239363235

**Comment by kemsky** [comment]
Indeed, it was strange decision to add global listeners via `HostListener` and it is still not properly documented. Also don't forget that the same applies to `Component.host` metadata. I believe that `HostListener` and `HostBinding` should remain, but `:` syntax should be removed (after some deprecation period with a warning).

**Comment by michaeljota** [comment]
I know this was added in 2016, and that we have Angular 6, waiting for the 7. Though the original proposal request to deprecate `@HostListener`, I don't see this factible any more. Still, a decorator that allows directives, and services to listen global events should be useful in many cases. 

- [Case 1](https://stackoverflow.com/questions/47944149/is-it-possible-to-have-angular-hostlistenerwindowscroll-in-simple-service)*
- [Case 2](https://stackoverflow.com/questions/39592972/is-it-possible-to-use-hostlistener-in-a-service)*
- [Case 3](14191)

* The provided workaround was to use directly `window.addEventListener`. This just does not feel safe.
