### ISSUE TITLE
Add a decorator for setting document title

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#11698]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
We need a Title Service as described in the [Set Document Title Cookbook](https://angular.io/docs/ts/latest/cookbook/set-document-title.html).

**Suggested behavior**
Using a decorator to bind the title, along the lines of `@HostBinding(title:text)` or `@HostBinding(title:innerHTML)`, or maybe even entirely new decorator such as `@TitleBinding`.

**What is the motivation / use case for changing the behavior?**

It's a bit weird that binding to `window` is so easy and setting the title so hard.
We can already access `window` with a decorator so why not access `title` the same way?
- **Angular version:** 2.0.0
- **Browser:** all
- **Language:** TypeScript

**Comment by laco0416** [comment]
`BrowserModule` provides `Title` service. 
https://angular.io/docs/ts/latest/api/platform-browser/index/Title-class.html

**Comment by DzmitryShylovich** [comment]
thx :)
> Current behavior 
We need a Title Service as described in the Set Document Title Cookbook.

**Comment by DzmitryShylovich** [comment]
Close in favor of https://github.com/angular/angular/issues/11115?

**Comment by trotyl** [comment]
This could also be covered by https://github.com/angular/angular/issues/14815, `title` is a property of `document` and can be bound if `@HostBinding` accept `document` as a target.

**Comment by alxhub** [comment]
(`Title` service does exist: https://angular.io/guide/set-document-title)
