### ISSUE TITLE
I18n: remove TRANSLATIONS_FORMAT

### ISSUE THREAD

**Issue by ghost** [angular/angular#11695]
**I'm submitting a feature request**

**Currently** we have to provide the _TRANSLATIONS_FORMAT_ at bootstrap time. I would **expect** Angular to identify the format by itself, since the format is passed via the file itself (for example `xlf`: `<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">`). I think that this is not needed and redundant, which is also my **motivation** for opening this issue.

By the way: Even the _LOCALE_ID_ could be read from at least the `xlf` file (not sure what it looks like in `xmb` files). If it is not explicitely set, it could be read from the `xlf` file as default behaviour (from the `<file>` property `target-language`)

**Comment by vicb** [comment]
Definitely something we can improve. Xtb files don't contain the target languages but other heuristics could work (extract from file name)

**Comment by christiandreher** [comment]
Well yes, that for the latter, but the *TRANSLATIONS_FORMAT* can definetly be extracted from the filename or the header, like in the example above

**Comment by petebacondarwin** [comment]
Closing as this is now obsolete.
