### ISSUE TITLE
@angular/http/index has no exported member 'HTTP_PROVIDERS'

### ISSUE THREAD

**Issue by LeeHyungGeun** [angular/angular#11694]
**I'm submitting a ...
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

@angular/http/index has no exported member 'HTTP_PROVIDERS' on Typescript by Webpack

**Expected behavior**

'HTTP_PROVIDERS' is exported as a member on '@angular/http'

**Please tell us about your environment:**

OS: Windows 7
IDE: VS Code
Package Manager: NPM 3.10.6
Angular Version: @angular/http: "^2.0.0"

* **Angular version:** 2.0.0

"@angular/http": "^2.0.0"

* **Language:** [TypeScript]

**Comment by LeeHyungGeun** [comment]
I have checked that HTTP_PROVIDERS is removed on 2.0.0-rc.6
Thus, it was my mistake.

I've insert it as the way
import { HttpModule } from '@angular/http';
@NgModule({
    imports: [
        HttpModule
    ]
})

**Comment by gencebay** [comment]
API References and also code examples updates would be nice. [base_request_options.ts](https://github.com/angular/angular/blob/e7a8e2757b06d572f614f53b648d2fd75df370d2/modules/%40angular/http/src/base_request_options.ts#L152)

**Comment by NShulzhenko** [comment]
You've saved my time. thanks)

**Comment by JVTT** [comment]
6 months have passed, yet the documentation still has not been updated.

**Comment by huanghaiyang** [comment]
please update the documentation

**Comment by saravanans-arch** [comment]
please update the documentation, 3 days i wasted my time in this issue

**Comment by mah14** [comment]
@LeeHyungGeun thanks a lot.

**Comment by huanghaiyang** [comment]
tks

**Comment by mah14** [comment]
your wellcome
