### ISSUE TITLE
Router: Listening to activated child observables from parent doesn't emit changes

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#11692]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When listening to child params from the parent route component, the observable doesn't emit new values

**Expected behavior**
Parent should be able to listening to the child's activated route observables.

**Reproduction of the problem**

https://plnkr.co/edit/flPApGykkoWgK6lzi72C?p=preview

Load the above plunker
Bring up the developer console
Click on 1 in the list of crises
Notice no value is emitted in the console
Click on 2 in the list of crises

The `app/crisis-center/crisis-list.component.ts` is listening for the child route with the following:

`this.route.firstChild.url.subscribe(x=> console.log('CrisisList',x));`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =   

cc: @MarkPerryBV

**Comment by vsavkin** [comment]
Any time we create a new route (and a new component), the router creates new observables for it. Consequently, you cannot just subscribe to the first child of a route and expect the observable to emit all the changes when changing that child.

To get what you want, you should something like that:

```
export class CrisisListComponent implements OnInit {
  crises: Crisis[];
  public selectedId: number;
  private subscription: any;
  private child: any;

  constructor(
    private service: CrisisService,
    private route: ActivatedRoute,
    private router: Router
  ) { }

  isSelected(crisis: Crisis) {
    return crisis.id === this.selectedId;
  }

  ngOnInit() {
    this.route.params.forEach((params: Params) => {
      this.selectedId = params['id'];
      this.service.getCrises()
        .then(crises => this.crises = crises);
    });
    
    this.router.events.subscribe(e => {
      if (e instanceof NavigationEnd && this.child !== this.route.firstChild) {
        if (this.subscription) { this.subscription.unsubscribe(); }
        this.child = this.route.firstChild;
        this.subscription = this.route.firstChild.url.subscribe(x=> console.log('CrisisList',x));
      }
    });
  }

 //...
}
```

If you think this is a common pattern, could you open a feature request outlining the use case?

**Comment by Millen31** [comment]
Is there already a fix/feature for this?

**Comment by michaeljota** [comment]
Surprisingly no. However, I think this is a proper workaround. 

An updated version using rxjs pipable operators:
```ts
    this._router.events
      .pipe(
        filter(event => event instanceof NavigationEnd),
        switchMap(
          () =>
            (this._route.firstChild && this._route.firstChild.params) ||
            observableOf({}),
        ),
      )
      .subscribe(params => console.log(params));
```

**Comment by Yura13** [comment]
@michaeljota perfect workaround!

**Comment by stupidly-logical** [comment]
> Any time we create a new route (and a new component), the router creates new observables for it. Consequently, you cannot just subscribe to the first child of a route and expect the observable to emit all the changes when changing that child.
> 
> To get what you want, you should something like that:
> 
> ```
> export class CrisisListComponent implements OnInit {
>   crises: Crisis[];
>   public selectedId: number;
>   private subscription: any;
>   private child: any;
> 
>   constructor(
>     private service: CrisisService,
>     private route: ActivatedRoute,
>     private router: Router
>   ) { }
> 
>   isSelected(crisis: Crisis) {
>     return crisis.id === this.selectedId;
>   }
> 
>   ngOnInit() {
>     this.route.params.forEach((params: Params) => {
>       this.selectedId = params['id'];
>       this.service.getCrises()
>         .then(crises => this.crises = crises);
>     });
> 
>     this.router.events.subscribe(e => {
>       if (e instanceof NavigationEnd && this.child !== this.route.firstChild) {
>         if (this.subscription) { this.subscription.unsubscribe(); }
>         this.child = this.route.firstChild;
>         this.subscription = this.route.firstChild.url.subscribe(x=> console.log('CrisisList',x));
>       }
>     });
>   }
> 
>  //...
> }
> ```
> 
> If you think this is a common pattern, could you open a feature request outlining the use case?

@vsavkin this worked for me. Thanks.
