### ISSUE TITLE
Forms: stringifying the form provides old value when an element changes of reference

### ISSUE THREAD

**Issue by Krisa** [angular/angular#11701]
**I'm submitting a bug**  (check one with "x")

```
[ x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 

This is now possible to rebind a group directive according to https://github.com/angular/angular/pull/11051. While it seems to work partially, it fails however when we try to stringify a form for which an element of it has been rebinded.

**Expected behavior**

**Reproduction of the problem**
http://plnkr.co/edit/COioNPKzQXjAHcXp3xPd
1- change the value of "child - updated" to anything else
2- click on save
3- you will see in the console a discrepancy between `this.form.value` and `this.form.controls.mygroup.value`. `this.form.value` has the original value, which is wrong, while `this.form.controls.mygroup.value` has the correct updated value

**What is the motivation / use case for changing the behavior?**
inconsistent, and wrong.

**Please tell us about your environment:**
- **Angular version:** 2.0.0
- **Browser:** [ Chrome ] 
- **Language:** [TypeScript 2.0.2]

**Comment by manklu** [comment]
Change the constructor to

```javascript
constructor() {
  this.form.removeControl('mygroup');
  this.form.addControl('mygroup', new FormGroup({
    name: new FormControl('child - updated')
  }));
}
```

**Comment by Krisa** [comment]
thanks @manklu, that's probably the most elegant working workaround, but is nonetheless a workaround.

**Comment by DzmitryShylovich** [comment]
It's not a workaround. If u want to add new controls u should use `addControl` method. 

There's no efficient way how angular can intercept when u directly modify `controls` property to properly initialize a control. So in this case it's your responsibility to initialize a control:
```
constructor() {
    this.form.controls.mygroup = new FormGroup({
      name: new FormControl('child - updated');
    })
    this.form.controls.mygroup.setParent(this.form);
  }
```

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed

**Comment by kara** [comment]
Yeah, it's not going to work if you just directly re-assign the control because there's more work that Angular needs to do to set up the parent-child relationship. When you call `addControl` or `setControl`, the parent relationship is updated so when you change the child value, the parent value is changed as well. 

See example of using `setControl` here: http://plnkr.co/edit/HWxA8LofchjDLXzF5GNV?p=preview. Working as expected, so closing this issue.
