### ISSUE TITLE
Feature Request: Better Core Module Story

### ISSUE THREAD

**Issue by hannahhoward** [angular/angular#11702]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, services instances in a module are not shared if they are imported between two modules. I get the reasons for this. However, this is a major difference between Angular 1 and Angular 2, and it's not spelled out till 2/3's of a way down a section that's in the "Advanced Documentation". My concern is this is a huge waiting gotcha for new devs, especially those who are coming from Angular 1 and expecting a different behavior (especially since with the introduction of NgModules, the organization of Angular 2 apps in general is starting to look more similar to Angular 1 than it used to).

The general remedy suggested is the so called "Core Module" which is imported once at the root module only. And a 'good developer' just remembers not to import it multiple times. Interestingly, farther into the documentation code is given for preventing a module from being imported multiple times. I guess I'm wondering if that code (which is fairly non-obvious to someone without a deep understanding of Angular injection) could instead be wrapped into a decorator that abstracted it? Say @SingletonNgModule -- without it being a breaking change (now that 2.0.0 is out).

Anyway, I fear like the not-shared-instance of providers is gonna become a gotcha of Angular 2, like 5 ways to declare a service with one of them called service or the filter-filter were for Angular 1, if there's not a better workaround.

n/a
**Expected behavior**

see previous discussions of this

**Reproduction of the problem**

n/a
**What is the motivation / use case for changing the behavior?**

see above
**Please tell us about your environment:**

n/a
- **Angular version:** 2.0.0-rc.X
  
  yes
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
  
  n/a
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  n/a
- **Node (for AoT issues):** `node --version` =  
  n/a

**Comment by DzmitryShylovich** [comment]
@hannahhoward isn't it a documentation issue?

**Comment by alxhub** [comment]
I think `@Injectable({providedIn: 'root'})` is the right solution here.
