### ISSUE TITLE
AoT should output factories with eofline

### ISSUE THREAD

**Issue by antonybudianto7** [angular/angular#11706]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
The factories have tslint disable mark, but not works with eofline, it still warns 

**Expected behavior**
AoT should add eofline in their generated factories

**Reproduction of the problem**
https://github.com/antonybudianto/angular-webpack-starter

```sh
npm i

npm run ngc
```

look into `src/compiled` for example, it should have a warning in end of file when doing `npm run build`

```

WARNING in ./src/compiled/src/app/shared/navbar/navbar.component.ngfactory.ts
[281, 2]: file should end with a newline

 @ ./src/compiled/src/app/app.component.ngfactory.ts 22:15-68
 @ ./src/compiled/src/app/app.module.ngfactory.ts
 @ ./src/app/main-ngc.ts
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Ubuntu, VsCode

* **Angular version:** 2.0.0-

* **Browser:** [all ] 
 
* **Language:** [TypeScript 2.0.2]
 
* **Node (for AoT issues):** `node --version` =   6.5.0

**Comment by vicb** [comment]
Shouldn't it be a bug against tslint ?

**Comment by antonybudianto** [comment]
I thought so, but I think it's not bad to have eofline for the factories
