### ISSUE TITLE
Correction in HTTP documentation

### ISSUE THREAD

**Issue by timofeysie** [angular/angular#11705]
I'm submitting a correction for the HTTP page of the [Tour of Heroes tutorial](https://angular.io/docs/ts/latest/tutorial/toh-pt6.html)
```
"For now we get back on familiar ground by immediately by converting that Observable to a Promise using the toPromise operator."
```
Should be:
```
"For now we get back on familiar ground by immediately converting that Observable to a Promise using the toPromise operator." (remove second occurrence of 'by'.
```

**Comment by micronyks** [comment]
Please submit **docs related** issues at https://github.com/angular/angular.io/issues and close this issue here. Thanks.

**Comment by pkozlowski-opensource** [comment]
@micronyks is right, thnx.

@timofeysie would you mind re-opening in https://github.com/angular/angular.io/issues (or better yet - submitting a PR!). Thnx!

**Comment by timofeysie** [comment]
@pkozlowski-opensource, I would love to submit a PR.  However, I've had some problems doing that.  Following [the directions here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-pr), I am trying to make a PR as you suggested.  When I try and push the changes to then create the PR, I get this message:
```
$ git push origin grammar-correction
remote: Permission to angular/angular.io.git denied to timofeysie.
fatal: unable to access 'https://github.com/angular/angular.io.git/': The requested URL returned error: 403
```
Then, following [these instructions](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/) to add a new key to my GitHub account, I still get the same message when trying to push the branch.  Can you point me in the right direction here?  Thanks in advance.
