### ISSUE TITLE
CanActivate doesnt have access to routes data property

### ISSUE THREAD

**Issue by yaroslavya** [angular/angular#11708]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I need to be able to provide the roles so that they are checked in CanActivate method.
I use data parameters to provide the roles on my list of Routes, but in the CanActivate method data is always empty. I feel its a common problem, see these so issues: http://stackoverflow.com/questions/38402776/angular2-routing-canactivate-and-authguard-jwt-with-user-role-parameter?rq=1
http://stackoverflow.com/questions/39020453/angular2-router-canactivate-with-parameters/39097563

**Expected behavior**
data property should be available in the CanActivate method.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
I need to make a route based checks if component is allowed for the user. So I need to attach the data on what roles need to be allowed to the route and be bale to retrieve it in the AuthGuards CanActivate method.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 Angular router 3.0.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kemsky** [comment]
It is available through `ActivatedRouteSnapshot`: `route.children[i].data`, it might be tricky if you have many router outlets. `RouterStateSnapshot` also contains `data` but has different structure.

**Comment by yaroslavya** [comment]
I tried to access it, heres my plunker: http://plnkr.co/edit/6X14ChfewNDrBs9BjcGV?p=preview
Check the app.activate-guard for the code.
It seems when I use ActivatedRouteSnapshot it cant be resolved by the DI. If I try to use ActivatedRoute the data is empty. @kemsky can you, kindly, show me how to actually access this, in the plunker provided? Im really strugling with it for some time and it seems Im missing something.

**Comment by kemsky** [comment]
See `canActivate` method signature [CanActivate](https://angular.io/docs/ts/latest/api/router/index/CanActivate-interface.html)
```
  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    console.log(route.data);
    console.log('ActivateGuard#canActivate called, can: ', this.can);
    if (!this.can) {
      alert('Activation blocked');
      return false;
    }
    return true;
  }
```

**Comment by yaroslavya** [comment]
Thanks for the quick reply. It worked! I can close it now :+1:
