### ISSUE TITLE
AOT issue compiling with form controls

### ISSUE THREAD

**Issue by peteboere** [angular/angular#11709]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Cannot compile with AOT with errors in this format:
```
x.component.ngfactory.ts:xxx:xx:` Property 'name' does not exist on type '{ [key: string]: AbstractControl; }'
```

**Expected behavior**
Should be compiling without errors.

**Reproduction of the problem**
Have tried the various means of constructing form controls with the same result:
```js
this.form = new FormGroup({
     name: new FormControl('', Validators.compose([Validators.required])),
});

this.form = new FormGroup({});
this.form.addControl('name', new FormControl('', Validators.compose([Validators.required])));

this.form = this.formBuilder.group(<any>{
     name: ['', Validators.compose([Validators.required])],
});
```

**Please tell us about your environment:**
MAC

* **Angular version:** 2.0.0 (final)
 
* **Language:** TypeScript 2.0.2
 
* **Node (for AoT issues):** `node --version` =  v6.5.0

**Comment by vicb** [comment]
I guess we are accessing `.name` instead of `['name']` somewhere

/cc @kara @alexeagle

**Comment by vicb** [comment]
@peteboere could you add the smallest / simplest repro you come with ? (gist, github repo).
thanks

**Comment by peteboere** [comment]
Errors are being thrown from `detectChangesInternal` method from the generated factory class.

```js
class _View_ConnectComponent0 extends import1.AppView<import3.ConnectComponent> {
  ...
  detectChangesInternal(throwOnChange:boolean):void {
    ...
    if ((changes !== (null as any))) { this._FormControlDirective_21_7.ngOnChanges(changes); }
    // Accessing 'name' throws error...
    const currVal_34:any = this.context.form.controls.name.touched;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._NgIf_23_6.ngIf = currVal_34;
      this._expr_34 = currVal_34;
    }
    ...
  }
  ...
}
```

**Comment by kara** [comment]
Are you accessing `this.form.controls.name.touched` anywhere in your code? We'll need a more complete idea of what you have written. A plunker would help to see your setup (even if it won't be AOT).

**Comment by peteboere** [comment]
The component template is using dot notation and not `['name']` notation in some places and with non-aot compilation has been compiling fine.  So this might well be the issue...

I'm done for today but will verify this in the morning (London time :)).

**Comment by kara** [comment]
@peteboere You're going to want to switch to bracket notation because that will break the type checking.  You might also try switching to the `get()` method, as it won't give you that problem (ex: `this.form.get('name').touched`). I'm going to close this for now, but please feel free to open a new issue if you think there is still an AOT problem with something else.

**Comment by peteboere** [comment]
To clarify it was using the dot notation, as below, in my template that was causing the compile errors.  This works fine in JIT compilation and runtime, so I'm guessing there should probably be some AOT compiler warning or normalization (if such thing is possible) when generating the factory files.

```html
<div class="form-row">
    <input type="text" [formControl]="form.controls['name']" required class="form-control" placeholder="Your name" />
    <div *ngIf="form.controls.name.touched" class="errors">
        <p *ngIf="form.controls.name.errors?.required">Name is required.</p>
    </div>
</div>
```

**Comment by alexeagle** [comment]
There are a number of cases where AoT requires stricter code to pass the type-checker. The classic example is a private property of the component class used in the template. Right now we rely on TS type-checker to report these, but as you say this is confusing.
@wardbell and I discussed writing some static analyzers to help track this down. @mgechev wrote one already, see https://twitter.com/mgechev/status/777887201258381312
But so far this is not in scope for the AoT compiler. If you violate the type signature in an expression
(https://github.com/angular/angular/blob/671f73448cea4736e44a1949246fdb37c81db277/modules/%40angular/forms/src/model.ts#L852 says that controls is a `{[key: string]: AbstractControl}` ) then it's the type-checker's job to tell you about it.

**Comment by mgechev** [comment]
FYI, the rule for assuring access to only public fields is already in [master](https://github.com/mgechev/codelyzer/blob/master/src/templatesUsePublicRule.ts) and soon will be published on npm. The current limitations at this point (which will be solved in future) are:

- Only supports inline templates.
- Does not check nested properties.

**Comment by heatmonkey** [comment]
You might want to update the information on the documentation. Just spent way too much time on finding this. https://angular.io/docs/ts/latest/api/forms/index/FormBuilder-class.html

If the documentation doesn't apply to AoT, it should say so
