### ISSUE TITLE
Angular2 "Final" Unit Test Override Directive

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#11711]
I am using Angular 2 Final, and using the TestBed for Unit tests

I have an issue when when using "**overrideDirective**" it seems that the actual directive is being called, as I am getting an error "**No provider for Config!**" which MyDirective that was replaced is dependent on.

 **Component View**

```
  <div>
       <input myDirective>
       // some more logic etc...
  </div>
```

**Directive to Replace**

```
@Directive({
    selector: "myDirective"
})
class MyDirective{
    constructor(
        private config: Config
    ) {
    }
}
```

**Spec File**

```
@Component({
    template: "<my-component></my-component>"
})
class TestComponent{

}

@Directive({
    selector: "fake"
})
class FakeDirective {

}

beforeEach(() => {
    TestBed.configureTestingModule({
        declarations: [
            MyComponent,
            MyDirective,
            TestComponent,
            FakeDirective
        ]
    });
});

beforeEach(async(() => {
    TestBed
        .overrideDirective(MyDirective, FakeDirective)
        .compileComponents();
    fixture = TestBed.createComponent(TestComponent);
}));
```

Any one encountered the issue and managed to fix it please?

Thanks
- **Angular version:** 2.0.0 final

**Comment by juliemr** [comment]
First, your FakeDirective needs the same selector as the one it's replacing, so it should be `myDirective`. Second, `overrideDirective` lets you change the directive itself - to change the list of declarations, you want to use `overrideModule` like so: https://github.com/angular/angular/blob/8f5dd1f11e6ca1888fdbd3231c06d6df00aba5cc/modules/%40angular/platform-browser/test/testing_public_spec.ts#L311
