### ISSUE TITLE
[i18n]: add support for json translation file

### ISSUE THREAD

**Issue by jaumard** [angular/angular#11714]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Only xlf file are supported

**Expected behavior**
Having a simple JSON file support 

**What is the motivation / use case for changing the behavior?**
I generally don't use extract / merge capabilities for i18n and having to manually right xml in a JS world is painful ^^. I'm use to have my JSON file with key/translation and go for it :) 

Something like `ng2-translate` would be awesome (talking about file definitions only because the way they do it is very resourceful).

**Comment by vicb** [comment]
I guess most translators use tools to translate apps.

However there is no reason why we could not add JSON. Do you know about common schemas / tools used for JSON. (i.e. you don't want to manually diff a new version of your translation files, there must be a tool for that)

**Comment by jaumard** [comment]
For project where you want 2 langages (English and your native one, French for me) you don't need to use a translations services, you just do it ^^ but I see your point !

Platform like [crowdin](https://crowdin.com) use very basic JSON file key/value with no nested values, I use it but for Android application only. 
Platform like [pootle](http://pootle.translatehouse.org) use more complexe JSON file and offer some tools called [translate-toolkit](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/json.html) witch support complexe JSON and other formats (XLIFF included) but never use it but look like it have some merge tools!

**Comment by vicb** [comment]
If the JSON format does not support placeholders, pluralization (ICU messages in general), tooling then there is little chance we will implement it.

As the i18n becomes more stable we will most probably open the `Serializer` so that you can implement you own format.

**Comment by jaumard** [comment]
@vicb thanks! I didn't know it's called ICU messages, just quick research pop me to https://github.com/messageformat/messageformat.js ^^ 

I'll wait a little more and see how i18n evolve :) I'll give it a try to the current format too but for now it crash for me ^^

**Comment by vicb** [comment]
> I'll give it a try to the current format too but for now it crash for me

how ?

**Comment by jaumard** [comment]
@vicb I have this error : 
```
ng-xi18n

Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 79:17 in the original .ts file), resolving symbol AppModule in /Users/jaumard/LisaProjects/lisa-ui/src/app/app.module.ts
    at simplifyInContext (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/static_reflector.js:469:23)
    at StaticReflector.simplify (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/static_reflector.js:472:22)
    at StaticReflector.annotations (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/static_reflector.js:61:36)
    at _loop_1 (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/extract_i18n.js:67:54)
    at Extractor.readFileMetadata (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/extract_i18n.js:80:13)
    at /Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/extract_i18n.js:87:74
    at Array.map (native)
    at Extractor.extract (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/extract_i18n.js:87:35)
    at extract (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/extract_i18n.js:16:35)
    at Object.main (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
Extraction failed
```
I just added `"extract": "ng-xi18n",` to my package.json and run `npm run extract`

**Comment by vicb** [comment]
This is a pb with your code, try

```ts
    useFactory: (http: Http) => {
      const config: AuthConfig = new AuthConfig({
        noJwtError: true,
        tokenName: Globals.tokenKey,
        headerPrefix: 'JWT ',
        globalHeaders: [contentHeaders.toJSON()]
      });
      return new AuthHttp(config, http);
    },

// ->

useFactory: (http: Http) => createAuthHttp(http)

export function createAuthHttp(http: Http) {
// ...
}
```

your code does not ngc as is.

**Comment by jaumard** [comment]
@vicb same error :( I also try to remove it from providers and I have a new error : 
```
ng-xi18n

Error: Unexpected value 'AlertModule' imported by the module 'AppModule'
    at /Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler/bundles/compiler.umd.js:14126:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
    at /Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler/bundles/compiler.umd.js:12952:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler/bundles/compiler.umd.js:12951:21)
    at Extractor.extract (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/extract_i18n.js:92:47)
    at extract (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/extract_i18n.js:16:35)
    at Object.main (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/Users/jaumard/LisaProjects/lisa-ui/node_modules/@angular/compiler-cli/src/extract_i18n.js:160:9)
Extraction failed
```

**Comment by jaumard** [comment]
Ok @vicb I fix the first error with : 
```
export function createAuthHttp(http: Http) {
  const config: AuthConfig = new AuthConfig({
    noJwtError: true,
    tokenName: Globals.tokenKey,
    headerPrefix: 'JWT ',
    globalHeaders: [contentHeaders.toJSON()]
  });
  return new AuthHttp(config, http);
}
export const provideAuthGuard = {
  provide: AuthHttp,
  useFactory: createAuthHttp,
  deps: [Http]
}
```

But the second one appear :/ maybe a problem with `ng2-bootstrap` ? cc @valorkin

**Comment by vicb** [comment]
Could you please move the discussion to the supports channel (gitter/SO). Thanks.

**Comment by fndmiranda** [comment]
@jaumard, do you know if it is already possible to use json format for translations, have you ever used the native module or some third-party module?

**Comment by ocombe** [comment]
It is not possible right now, there is no Json serializer

**Comment by jaumard** [comment]
@fndmiranda no solution yet but didn't search a lot to be honest ^^

**Comment by rhanb** [comment]
is there any news on the exposition of the `Serializer` api ?

**Comment by ocombe** [comment]
Nothing official yet, no.

**Comment by rhanb** [comment]
thanks for the quick answer @ocombe

**Comment by spock123** [comment]
Anyone knows a free tool to generate xliff from json for example? 
Or even half decent free xliff editors?
If not, what in the world was the team thinking when not also supporting nested json? I mean,  we use phrase.com for translating at work, but for a developer playing with translation it's absurd to having to have to edit xml files because no decent xliff editor seems to exist.

Mind blowing

**Comment by luchillo17** [comment]
#36644 was recently open by @spock123 probably to push this feature open, but to me, it looks like a duplicate.

**Comment by petebacondarwin** [comment]
Yes it is a duplicate. But let's continue the discussion there.
Closing in favour of #36644

**Comment by glen-84** [comment]
@petebacondarwin Why close an older issue with 15 votes in favour of a newer issue with 1 vote?
