### ISSUE TITLE
Can't install angular 2.0.0 through npm

### ISSUE THREAD

**Issue by pedropapa** [angular/angular#11713]
How do I install the latest stable version of 2.0 branch on npm? 

angular/angular says that 1.5.8 is the latest of 120 releases.
angular/angular2 says that 2.0.0-beta.17 is the latest of 68 releases.

2.0.0 has not being published yet?

**Comment by mxii** [comment]
Here to get an overview: https://www.npmjs.com/~angular

And for example the core: https://www.npmjs.com/package/@angular/core

> 2.0.0 is the latest of 17 releases

**Comment by kylecordes** [comment]
It is true that the right answer is in the documentation and so on, but it is also true that the abandoned NPM angular2 package (still sitting there as if it works, but it actually stopped being updated at the end of the beta sequence) is not helpful at all for people picking up Angular 2.

I imagine it would be too disruptive to just delete it, but maybe someone at the Angular team could ship a placeholder that goes after the end of the current sequence which just reminds developers to go look at the documentation and use the new stuff underneath the scoped packages.
