### ISSUE TITLE
docs: NgFor API doc should hint `trackBy` for Arrays

### ISSUE THREAD

**Issue by vicb** [angular/angular#11727]
We should document that users probably want to use `trackBy` when iterating over an Array (/Iterable).

/ref https://github.com/angular/angular/issues/11723

/cc @matsko

**Comment by sky-coding** [comment]
+1, trying to use immutable arrays resulted in constantly re-rendering `*ngFor` templates, making them unusable for input. `trackBy` solves this problem but is not documented anywhere!

**Comment by tomwanzek** [comment]
@sky-coding thanks! Your comment just made my day. I should have known better, but...:smile:

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource it's already documented https://github.com/angular/angular/blob/master/modules/%40angular/common/src/directives/ng_for_of.ts#L64

can be closed I think

**Comment by kapunahelewong** [comment]
Hey @vicb I'm happy to document this if we still need to, but other than saying "use `trackBy` when iterating over an array", I don't know how else to qualify/expound/explain. Should we document it still and if so, do you think we need an explicit working example? 

Also, would this be the place to put it: [Template Syntax, ngForOf with trackBy](https://angular.io/guide/template-syntax#ngfor-with-trackby)?
