### ISSUE TITLE
Using *ngFor inside a form breaks two way binding

### ISSUE THREAD

**Issue by shaun-mason** [angular/angular#11723]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When using *ngFor inside a form, two way binding breaks if you change the bound collection.

**Expected behavior**
When you modify the bound collection, the valid existing bindings should display the correct value.

**Reproduction of the problem**
https://plnkr.co/edit/wfHOd0

**What is the motivation / use case for changing the behavior?**
I ran across this bug while testing a production release.  I worked around the issue, but I'm afraid it will crop up again.

* **Angular version:** 2.0.0
* **Browser:** 53.0.2785.116 m (64-bit)
* **Language:** TypeScript 2.0

**Comment by vicb** [comment]
You should use `trackBy`, see other (closed) issues on this repo

**Comment by shaun-mason** [comment]
A couple of comments:

1. That is not very intuitive.
2. There is NO mention of `trackBy` in the [Forms Guide](https://angular.io/docs/ts/latest/guide/forms.html).
3. It seems you must use `ngModelOptions` on your input element, instead of `name` even though it is a suggested alternative in the error messages.  See updated Plunkr: https://plnkr.co/edit/wfHOd0

Regardless, thanks for getting me on the right path.

**Comment by vicb** [comment]
`trackBy` is required because you iterate an array with `NgFor` nothing specific to forms here.

I'll create an issue to improve the NgFor doc

**Comment by shaun-mason** [comment]
Did you look at my plunker?  It works fine without `trackBy` until it is in a `<form>` tag.

**Comment by anantkamath** [comment]
The bug is with using *ngFor inside a form (template driven). `trackBy` makes no difference. 
The solution as @shaunlmason said, is to use `ngModelOptions` instead of `name`.

This issue still exists.

Also this thankfully doesn't affect `<input="file">` inputs (where you cannot use `ngModelOptions` anyway)

**Comment by Miced** [comment]
This issue still exists as of 5.1.2. The underlying model is updated (track function or no track function), but the displayed values are wrong. Inspecting the element's ng-reflect-model also has a correct value. The only solution is to use {standalone: true}, but that might break form validations.

It seems the only real solution is to use reactive forms.

**Comment by Jonatino** [comment]
This is still an issue as of 6.0.7
