### ISSUE TITLE
Custom URL encoding and decoding when navigating via Router

### ISSUE THREAD

**Issue by noahmulfinger** [angular/angular#11729]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Passing in search values as query parameters when using `router.navigate()` encodes the query parameters with the standard `encodeURIComponent()` function (used in the DefaultUrlSerializer class in url_tree.ts).

**Expected/requested behavior**
Allow custom encoding of the url query parameters, possibly through allowing the use of an alternate implementation of DefaultUrlSerializer.

**What is the motivation / use case for changing the behavior?**
It is common to use + signs to represent spaces in a url search query (ex: displaying `?q=one+two` instead of `?q=one%20two`) but as the UrlTree is currently implemented, you can only use the standard url encoding.

**Please tell us about your environment:**

* **Angular version:** 2.0.0

* **Browser:** [all] 

 
* **Language:** [TypeScript]

**Comment by brandonroberts** [comment]
You can implement your own [UrlSerializer](https://angular.io/docs/ts/latest/api/router/index/UrlSerializer-class.html) and do this currently.
