### ISSUE TITLE
Lazy Loaded components don't detect changes of observables without an initial value

### ISSUE THREAD

**Issue by diestrin** [angular/angular#11738]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Lazy loaded components do not detect the first change produced by a ReplaySubject

**Expected behavior**
All the changes should be reflected in the page

**Reproduction of the problem**
I have a custom lazy load logic in place for my site to load the components only visible in the screen. As the user scrolls down, new components are loaded.

So I have a working logic doing the lazy load bootstrap as follows:
```
function bootstrapWithCustomSelector(moduleFactory, selector, appModule) {
  const injector = ReflectiveInjector.resolveAndCreate([], appModule.injector);
  const ngModule = moduleFactory.create(injector);
  const initStatus = ngModule.injector.get(ApplicationInitStatus);
  const appRef = ngModule.injector.get(ApplicationRef);
  const comp = ngModule.injector.get(LazyLoadConfig).component;
  const inj = ngModule.injector.get(Injector);
  const compFactory = ngModule.componentFactoryResolver.resolveComponentFactory(comp);
  
  initStatus.donePromise.then(() => {
    const compRef = compFactory.create(inj, [], selector);
    appRef.registerChangeDetector(compRef.changeDetectorRef);
    appRef.tick();
  });
}
```
`LazyLoadConfig` is just a symbol of the component I want to bootstrap, no worries about it.

And here's the issue I'm having, when a component uses an Observable that does not get an initial value at the application start, Angular will just ignore the produced values of that Observable, untill a call to `detectChanges()` is performed.

http://plnkr.co/edit/nBuVVY?p=preview

* **Angular version:** 2.0.0

* **Browser:** all
 
* **Language:** all

**Comment by vicb** [comment]
Please describe how to reproduce/see the issue with your plunker. thanks.

**Comment by diestrin** [comment]
Both of them should start with a 0 count, as you click, they'll increase by one (with a delay of 500ms between the click and the count increase)

The first example shows how nothing is rendered until you click in any of the buttons, and that triggers the change detector.

**Comment by vicb** [comment]
seems to work in Chrome unless I don't understand what you just said ?

**Comment by diestrin** [comment]
Both of them show a `0` as the initial value without any user interaction?

**Comment by diestrin** [comment]
BTW, why the `comp: router` tag? I know currently the router is the only one doing lazy loading, but my use case does not use the router at all.

**Comment by vicb** [comment]
@diestrin fixed the label, thanks for noticing.

/cc @robwormald any idea ?

**Comment by kemsky** [comment]
Looks interesting,  constructor is executed in `<root>` zone and `setTimeout(() => service.init(), 0);`
 is executed in inherited zone `<root>`, but should be in `angular` zone i guess.

**Comment by diestrin** [comment]
@kemsky I've seen this logic in the [ApplicationRef](https://github.com/angular/angular/blob/master/modules/%40angular/core/src/application_ref.ts#L271):
```
if (!ngZone) ngZone = new NgZone({enableLongStackTrace: isDevMode()});

return ngZone.run(() => {
  const ngZoneInjector =
    ReflectiveInjector.resolveAndCreate([{provide: NgZone, useValue: ngZone}], this.injector);
  ...
});
```
Do you think that's the missing part for my custom lazy loader?
Right now I'm just creating an injector without any NgZone providers, just inheriting the parent providers.

**Comment by diestrin** [comment]
AWESOME :) That was the missing piece! Thanks guys. I'll probably contribute back to the community with this scroll loader (lazy load components as you scroll down the page) once I have the code mature enough.

**Comment by vicb** [comment]
thanks for reporting !

**Comment by tkssharma** [comment]
trying to get this running on angular 8 for lazy load 
I am getting Property 'registerChangeDetector' does not exist on type 'ApplicationRef'.ts(2339)

`  public bootstrapWithCustomSelector(moduleFactory: NgModuleFactory<any>, selector: string, ngClassName: string): void {
    const ngZone = this.appModule.injector.get(NgZone);

    ngZone.run(() => {
      // Get the parent injector and create the module
      const parentInjector = ReflectiveInjector.resolveAndCreate([], this.appModule.injector);
      const ngModule = moduleFactory.create(parentInjector);

      // Some dependencies from this module
      const appRef = ngModule.injector.get(ApplicationRef);
      const inj = ngModule.injector.get(Injector);
      const initStatus = ngModule.injector.get(ApplicationInitStatus);
      const lazyLoad = ngModule.injector.get(LazyLoadComponent);

      if (!lazyLoad) {
        throw(`${ngClassName} is not using the LazyLoadComponent. This is
          necessary to bootstrap the component. Check the docs.`);
      }

      initStatus.donePromise.then(() => {
        // Get the component factory and create it
        const compFactory = ngModule.componentFactoryResolver
            .resolveComponentFactory(lazyLoad);
        const compRef = compFactory.create(inj, [], selector);

        // Register the change detector to the app and trigger the first detection
        compRef.changeDetectorRef.detectChanges();
        appRef.registerChangeDetector(compRef.changeDetectorRef);
      });
    });
  }`
