### ISSUE TITLE
Aot Error, Consider making ngOnChanges argument optional

### ISSUE THREAD

**Issue by xealot** [angular/angular#11733]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior** 
AoT compilation fails when using `NgTemplateOutlet`.

**Reproduction of the problem**

```html
<template
  [ngTemplateOutlet]="template || embeddedTemplate || defaultTemplate"
  [ngOutletContext]="{ $implicit: result, index: i }">
</template>
```

Code that uses `<template>` tags seem to cause this because it invokes the type `NgTemplateOutlet`. Here is an abbreviated Typescript type of the `NgTemplateOutlet` interface:

```typescript
export declare class NgTemplateOutlet implements OnChanges {
    ngOnChanges(): void;
}
```

This is not a valid implementation of `OnChanges`. The `OnChanges.ngOnChanges` argument should be optional, or this interface should define the proper arguments.

```typescript
export declare abstract class OnChanges {
    abstract ngOnChanges(changes: SimpleChanges): void;
}
```
**What is the motivation / use case for changing the behavior?**

`ngOnChanges` is often used as a notification mechanism for components. This is made obvious by the fact that often the `SimpleChanges` argument is omitted from the function.

I feel like setting the `OnChanges.ngOnChanges` function argument to optional wouldn't harm anything.

* **Angular version:** 2.0.0
* **Browser:** all
* **Language:** TypeScript 2.0

**Comment by vicb** [comment]
fixed in master https://github.com/angular/angular/commit/14ee75924b6ae770115f7f260d720efa8bfb576a
