### ISSUE TITLE
[i18n]: add support for XLIFF 2.0 serializer

### ISSUE THREAD

**Issue by panuruj** [angular/angular#11735]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
The ng-xi18n and ngc are currently supporting XLIFF v.1.2. 

**Expected behavior**
There should be an option to also generate/consume XLIFF v.2.0.

**What is the motivation / use case for changing the behavior?**
XLIFF v.2.0 became a standard in 2014, and the schema is very similar to v.1.2. Many of our localization vendors are accepting XLIFF 2.0, so it is desirable to be able to extract and consume XLIFF 2.0 directly. Today, we have to script the conversion from v.1.2 to/from v.2.0.

**Comment by vicb** [comment]
Do you know what the diffs are in 2.0 vs 1.2 ?

**Comment by panuruj** [comment]
I have attached a manual conversion of v1.2 to v2.0.

Here are the differences:
* No <body>
* <trans-unit> becomes <unit>
* <segment> element under <unit>
* <note> must be a child of <notes> within <unit>
* Instead of <x>, the placeholders are represented as <pc> or <ph>
* There are a few other minor changes to the attribute names.

[messages.v1.2.xlf.txt](https://github.com/angular/angular/files/481315/messages.v1.2.xlf.txt)
[messages.v2.xlf.txt](https://github.com/angular/angular/files/481316/messages.v2.xlf.txt)

**Comment by vicb** [comment]
thanks for the details. We will consider this for a future release (PR welcome, however the xliff 1.2 impl probably need some love before it can be used as a starting point)

**Comment by shbhar** [comment]
@tbosch, any idea when this is going to make it into a beta? I also need this if possible
