### ISSUE TITLE
Loading splash removed from UI while zone.js still serving files.

### ISSUE THREAD

**Issue by rpaschoal** [angular/angular#11739]
**I'm submitting a ...**  
```
[x] bug report => Loading splash removed from UI while zone.js still serving files.
```

**Current behavior** 
I am porting an Angular2 RC4 application to the final release (2.0.0) and I realized that my loading splash screen is being removed from the browser before Zone.JS file finishes serving all necessary resources for the current route.

I am using the lazy loading feature of the new router (3.0.0).

**Expected behavior**
The loading splash should be removed from the UI after all necessary files (HTMLs, JS and CSS) are served.

**Reproduction of the problem**

1. Create an Angular 2.0.0 application;
2. Configure any splash screen wrapped by the angular app directive;
3. Configure a nested path on routing (using lazy loading);
4. Navigate to the full path on the browser;
5. Refresh the browser's page (Inspect the console on the browser, splash screen will be removed before all component files are served by Zone.JS).

Following you can see an example of one of my modules. Each of our route path composes a blade. A blade in our scenario is something similar to the blade concept of the Azure Portal. Each blade is an Angular Module, and a user may see one to many blades on the UI at the same time, and the URL path reflects each blade state and it is dynamically composable (This is why lazy loading of the modules is so important).

```
const bladeRoutes: Routes = [
    {
        path: '', component: EmptyComponent
    },
    {
        path: 'overview/:id',
        component: TripOverviewBladeComponent,
        loadChildren: 'app/modules/blades/legs/leg-overview-blade/leg-overview-blade.module#LegOverviewBladeModule'
    }
];

export const currentBladeRouting = RouterModule.forChild(bladeRoutes);

@NgModule({
    imports: [
        currentBladeRouting,
        CommonModule,
        FormsModule,
        GlobalDirectivesModule
    ],
    declarations: [
        TripOverviewBladeComponent,
        TripOverviewComponent,
        LegDetailsComponent,
        DepartmentComponent
    ]
})
export class TripOverviewBladeModule {
}
```

**What is the motivation / use case for changing the behavior?**
Different behavior from RC4 version.

* **Angular version:** 
2.0.0

* **Browser:** 
Chrome 53.0.2785.116

**Comment by vsavkin** [comment]
Please provide a plunkr reproducing the issue?

**Comment by vsavkin** [comment]
Closing this issue. Please reopen it with a repro.

**Comment by rpaschoal** [comment]
Hi @vsavkin,

I will create a plunker reproducing this issue as soon as I get some spare time here at work (Probably by the end of this week).

Thanks!

**Comment by rpaschoal** [comment]
Hello @vsavkin, 

As requested here is the plunker that reproduces the reported issue: http://plnkr.co/edit/Li8bQNzeTwBRkgRLuGxi?p=preview

To see the issue happening you need to open this link directly:
http://run.plnkr.co/Sw3q9sRQGk4aPnEt/#/m2/m1/m2

You will realize that the first module and its related components are loaded (Removing the loading splash) and then the rest of the lazy loaded route (m2/m1/m2) components gets attached to the DOM. 

The problem is that this may take a long time depending of how deep the user has gone so far in the URL and how fast is his current network. Even if his network is fast enough to reduce RTT, there may be plenty of files that need to be served and the user does not know what is going on.

Appreciate the help on this.

Thanks!

**Comment by rpaschoal** [comment]
Reopened the issue under #12290
