### ISSUE TITLE
compiler-cli sass import file resource not found

### ISSUE THREAD

**Issue by kmcs** [angular/angular#11747]
**I'm submitting a ...**  (check one with "x")

[x] bug report => search github for a similar issue or PR before submitting

**Current behavior** 
In my project I include bootstrap-sass.
All import statements with an underscore are not found by the compiler-cli.

Example sass file with the following content:

`@import "component/bootstrap-variables";`

produce the following error:
```
    [timo@machine angular2-webpack-starter]$ ./node_modules/.bin/ngc Error: Compilation failed. Resource file not found: /var/www/angular2-webpack-starter/src/assets/styles/component/bootstrap-variables
        at Object.resourceLoader.get (/var/www/angular2-webpack-starter/node_modules/@angular/compiler-cli/src/codegen.js:123:27)
        at DirectiveNormalizer._fetch (/var/www/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:13455:45)
        at /var/www/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:13557:55
        at Array.map (native)
        at DirectiveNormalizer._loadMissingExternalStylesheets (/var/www/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:13557:16)
        at /var/www/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:13560:28
        at process._tickCallback (node.js:369:9)
        at Function.Module.runMain (module.js:443:11)
        at startup (node.js:139:18)
        at node.js:968:3 Compilation failed
```

**Expected behavior**
the above error ist correct. the file `/var/www/angular2-webpack-starter/src/assets/styles/component/bootstrap-variables` does not exists, because the normal sass compiler looks also with the file suffix".scss" and prefix "_". 
the compiler should also take care of that and should find the file `/var/www/angular2-webpack-starter/src/assets/styles/component/_bootstrap-variables.scss`

**What is the motivation / use case for changing the behavior?**

* **Angular version:** 2.0.0

 
* **Language:** TypeScript 2.0.2
 
* **Node (for AoT issues):** `node --version` =   v4.4.4

**Comment by pkozlowski-opensource** [comment]
Sounds like the CLI-specific setup issue / question. Please re-open in https://github.com/angular/angular-cli. Thnx!

**Comment by wuzhouyang** [comment]
hi,i have the same problem,do you resolve?

**Comment by kmcs** [comment]
hi 
see #11897 it's not supposed to use aot and scss. 
css files with font path reference also not working.
:-( my work around is to add the styles manually.

**Comment by targunp** [comment]
here is a fix, put this in your .angular-cli.json:

`        "stylePreprocessorOptions": {
            "includePaths": [
                "../node_modules"
            ]
        },`
