### ISSUE TITLE
Pipes ignore user culture and use only default en-US (beating a dead horse)

### ISSUE THREAD

**Issue by matteo-mosca** [angular/angular#11744]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
As already stated in #11274 and #11710 Angular2 does not utilize Intl library in i18n sensitive components, such as pipes, as it is instead stated in the documentation:

From decimalpipe docs: 

> Formats a number as text. Group sizing and separator and other locale-specific configurations are based on the active locale.

In #11710 we were told to override "LOCALE_ID" after I personally found out about its existence and meaning navigating the source code, and I should not have had the need to do that. Noone bothered to explain how to do this override, and the documentation is lacking.

Since i18n is not a minor feature but a critical feature for anyone developing for non-US customers it is only natural to have a clear and documented way to achieve it.

I did not want to open a third issue but the previous 2 were closed without a clear way to achieve the expected behaviour and I could not reopen them.

**Expected behavior**
Angular2 should provide a CLEAR and DOCUMENTED way to use i18n.

**Reproduction of the problem**
Try to localize an Angular2 app without editing the source

**What is the motivation / use case for changing the behavior?**
i18n is critical for a production ready framework such as Angular2 and it makes no sense that it is not clearly documented how to achieve it. It's not beta or RC anymore.

**Please tell us about your environment:**
Not relevant

* **Angular version:** 2.0.0-rc.X
2.0.0 Final

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 All
* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
Doc is in the flux at https://github.com/angular/angular.io/pull/2340

Please add your comments there
