### ISSUE TITLE
router.navigate failing silently on OnInit of component

### ISSUE THREAD

**Issue by aman05** [angular/angular#11748]
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior** 
`router.navigate `fails silently on component's `OnInit` or `constructor`.It resolves to `true`.

**Expected behavior**
Either it should throw an error or navigate to the url.

**What is the motivation / use case for changing the behavior?**
I am building a testportal where students can give test,so on OnInit of TestComponent.I get the complete test from a service and then route to the questions or the instruction component depending upon the state of test(paused or starting for the first time). 

**Please tell us about your environment:**
You can check this using the plunkr here.
http://plnkr.co/edit/RjSM1PwlshIAbwjbcpZR?p=preview
Ive just added a `navigate` call in `AppComponent`.

This code is from the documentation of router .
  angular/router: 3.0.0

  Angular version: 2.0.0

**Comment by brandonroberts** [comment]
You need to disable initial navigation with the router if you're going to navigate from within the `AppComponent` using `ngOnInit`

In your `app.routing.ts`

```ts
  RouterModule.forRoot(appRoutes, { initialNavigation: false });
```
