### ISSUE TITLE
Importing from files is case sensitive - errors out if imported reference case doesn't match 

### ISSUE THREAD

**Issue by AndrejKikelj** [angular/angular#11745]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 
Given a module that has a ModuleComponent in its declarations, and a module.routing.ts file that imports the ModuleComponent with different casing to use for a route - when routed to, the ModuleComponent will not be recognized as registered in the declarations array due to different casing.

**Expected behavior**
Option 1: Documentation states the path to file is case sensitive, and optionally return a meaningful development warning when a component is loaded with two different casings, so that it is easier to find the error, instead of returning component not declared in any module.
Option 2: Imports work without being case sensitive, and angular2 doesn't error out.

**What is the motivation / use case for changing the behavior?**
Easier to find bugs and port larger chunks of code.

* **Angular version:** 2.0.0

* **Browser:** [all]

**Comment by vicb** [comment]
Please add a repro of the issue

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
