### ISSUE TITLE
AOT error with APP_BASE_HREF provider

### ISSUE THREAD

**Issue by peteboere** [angular/angular#11749]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
App will not load using AOT/rollup bundle with the following error:

```
bundle.aot.js:xxxx Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
    at new PathLocationStrategy (bundle.aot.js:xxxx)
```

**Expected behavior**
App should load. The APP_BASE_HREF token is available when using JIT runtime.

**Reproduction of the problem**
Using the standard provider method for APP_BASE_HREF token:

``` js
// ./routes.ts
import {APP_BASE_HREF} from '@angular/common';
import {baseUrl} from './config';
...
export const routesProviders: any[] = [{
    provide: APP_BASE_HREF,
    useValue: baseUrl
}];
console.log(baseUrl); // Is available
```

``` js
// ./app.module.ts
import {routes, routesProviders} from './routes';
...
@NgModule({
    declarations: [
        AppComponent,
        ...
    ],
    imports: [
        BrowserModule,
        routes,
        ...
    ],
    providers: [
        ...routesProviders,
        ...
    ],
    bootstrap: [
        AppComponent
    ],
})
```
- **Angular version:** 2.0.0 (final)
- **Browser:** Chrome XX && Firefox XX
- **Language:** TypeScript 2.0.2, Rollup bundle
- **Node (for AoT issues):** `node --version` =  v6.5.0

**Comment by vicb** [comment]
Please add a repro (ie plunker or github repro)

**Comment by peteboere** [comment]
It seems the problem is that our value for APP_BASE_HREF is pulled from the window object, which is definitely available at runtime, being defined at the top of the page, but still returns null inside the app:

```js
// Inside the module providers.
{
    provide: APP_BASE_HREF,
    useValue: window.baseUrl
}
```

If we hardcode a value it works:
```js
// Inside the module providers.
{
    provide: APP_BASE_HREF,
    useValue: '/test'
}
```
Is this by design?  Any ideas for a workaround would be appreciated.

**Comment by peteboere** [comment]
I have found a workaround by using an exported factory function in the provider definition:

```js
export function appBaseHrefFactory() {
    return window['baseUrl'];
}

// app.module.ts
{
    provide: APP_BASE_HREF,
    useFactory: appBaseHrefFactory
}
```

I'm guessing this is due to the way the module file is handled statically. Seems like a bug to me, or at the least warranting some documentation or compiler/runtime warning.

**Comment by vicb** [comment]
@peteboere your last message is what you should do (sorry for the late feedback).
