### ISSUE TITLE
Use the Router in fully offline mode (using file:///..)

### ISSUE THREAD

**Issue by niklas-dahl** [angular/angular#11751]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**So here is my use-case:**
I'm building my angular application using webpack and after that I'm inlining all the js/styles/etc into a single app.html file using [inliner](https://www.npmjs.com/package/inliner).

Now my complete app is in one file and just opening it with a browser without a server (file:///C:/app.html) actually works and angular runs, quite amazing :)

The only problem is with the router, I'm not expecting `location.pushstate` to work but I think using the HashLocationStrategy should be able to work, when using `file:///`.

**Current behavior** 

Current Error message:
`index.html:1 EXCEPTION: Uncaught (in promise): SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///C:/#/' cannot be created in a document with origin 'null' and URL 'file:///C./..'`

**Expected behavior**

It just works :)

**Reproduction of the problem**

using the angular-cli:
1. create a project
2. create a route
3. build the project `ng build -prod`
4. inline it all `inliner dist/index.html > app.html`
5. open the app.html file in your browser

**What is the motivation / use case for changing the behavior?**

A report that works online with live data but additionally works fully offline as a single file with static data.

**Please tell us about your environment:**

Windows 7, VS Code, npm, angular-cli

* **Angular version:** 2.0.0-rc.X

2.0.0 :tada: 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

Chrome 53.0.2785.116, Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 TypeScript 2.0

Thanks.

**Comment by vsavkin** [comment]
I'm not sure how common this use case is. What I would recommend you to do is to provide a custom Url strategy that does not use the history API:

```
class MyUrlStrategy implements UrlStrategy {}

@Component({
  imports: [RouterModule.forRoot(ROUTES)],
  providers: [
    {provide: UrlStrategy, useClass: MyUrlStrategy}
  ]
})
class MyApp {
}
```

Closing this issue.
