### ISSUE TITLE
All guards are called twice if you provide manually the url to the last child component.

### ISSUE THREAD

**Issue by mwassil** [angular/angular#11758]
**I'm submitting a ...**
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
If you type manually the url in the browser all guards are called twice. By navigating using router the same guards are called once.

**Expected behavior**
By entering manually the url in the browser all guards should be called only once.

**Reproduction of the problem**
Enter manually the url in the browser to the last component.

**What is the motivation / use case for changing the behavior?**
The behavior is inconsistent.

* **Angular version:** 2.0.0-rc.5

* **Browser:** [Chrome 52 | Firefox 38]

**Comment by vicb** [comment]
Please use the latest release (2.0.0)
