### ISSUE TITLE
`on*` event convention is overly greedy

### ISSUE THREAD

**Issue by zakhenry** [angular/angular#11756]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When defining an attribute of a component template, the [template parser](https://github.com/angular/angular/blob/2300c23332fe8a61427562770fb4e1911aad6e2e/modules/%40angular/compiler/src/template_parser/template_parser.ts#L905-L912) checks if a field name `startsWith` 'on', however this convention is overly greedy due to attribute fields potentially starting with 'on', yet not being event handlers. For example, `onlyCurrentMonth` or `once`, `onionsHaveLayers`, etc.

**Expected behavior**
Checker should interpret the camelcasing to only throw when field name starts with 'on' _followed by_ capital letters. (suggested regex `/^on[^a-z]/`)

* **Angular version:** 2.0.0

* **Browser:** [all ] 

* **Language:** [TypeScript 2.0.2]

**Comment by vicb** [comment]
Then HTML `(onclick)` would not work any more...

That's something we should be able to solve once we implement the schema for custom elements in a future release (you'll be able to declare properties and events name)

**Comment by zakhenry** [comment]
Ah, yes good point - it's not just the camelcased on* property bindings that are being checked against. Hmm, in that case the dom element really should be inspected to see if the binding is being attempted exists natively and only then reject. That would be an expensive check however..

**Comment by vicb** [comment]
As I mentioned before schemas will solve this. Meanwhile the workaround is not to have properties starting with "on"

**Comment by zakhenry** [comment]
OK, given that schemas will take some time, should the error message be modified to be more descriptive? Currently if I have a `onlyCurrentMonth` attribute, the error message I get is 

```
Binding to event attribute 'onlyCurrentMonth' is disallowed for security reasons, please use (lyCurrentMonth)=... ("ustomClass]="customClass"
[dateDisabled]="dateDisabled"
[ERROR ->][onlyCurrentMonth]="onlyCurrentMonth"
[shortcutPropagation]="shortcutPropagatio"):
```

Which is not so helpful

**Comment by DaSchTour** [comment]
I think this should be mentioned somewhere in the documentation. I already see my team members standing in line because they have stumbled over this trap. I really fear introducing Angular 2 in bigger teams, as there are so much traps that may heavily crash productivity 😞

**Comment by arciisine** [comment]
I think this may be a bigger problem if you are porting existing code over that used 'on' as an attribute prefix, versus creating the component from scratch (as you will get the error immediately when creating). Looking at the HTML spec, there seem to be less than 20 different 'on*' attributes provided by html. It may be helpful to only look for the specific 'on' attributes versus wildcarding the entire 'on*' space.

**Comment by kylecordes** [comment]
This sounds like a somewhat tricky technical situation for the moment. How about easing the strain at least temporarily with something in the documentation? Where in the documentation could this reasonably be referenced? (Related to this, I have noticed that certain method names "don't work". For example, you name one of your methods "select" and then try to call it from an event handler in the template, nothing happens. I imagine there is a similar reason behind the scenes, it will be nice to have a list of reserved names documented somewhere.)

**Comment by vicb** [comment]
I'll double check the code here.

Wet to "select" do you have a repro ?

**Comment by kylecordes** [comment]
@vicb I am thrilled to report that the select thing is no longer a problem. It was at least a few RCs back that I last saw it - so moot now. I'll keep an eye out for anything similar in the future.

**Comment by vicb** [comment]
@zakhenry please provide a repro (plunker), I can not reproduce the p

**Comment by vicb** [comment]
or @DaSchTour if you can have someone working on repro, would be more helpful than standing in line ;)

**Comment by zakhenry** [comment]
@vicb here is a (utterly contrived) plunkr http://plnkr.co/edit/o16GKBJXQIidTZfo01z4?p=preview

**Comment by vicb** [comment]
@zakhenry when you remove the typo `[onionsHaveLayer]`, the example works just fine.

I'll submit a PR to display a clearer error message

**Comment by zakhenry** [comment]
@vicb ah whoops! It looks like I found more of an edge case then. Thanks for the PR that clarifies the error messaging

**Comment by vicb** [comment]
No problem.

I think this highlight how important it is for issue report to have a minimal reproduction attached. 

I'll probably end up doing a talk about OSS / debugging / reporting errors some day. I'll include this issue as an example I think !
1. an issue is reported, we can not really help because the ticket is missing a reproduction
2 .blabla blabla we both loose time because the initial issue wasn't clear
3. angular2 ruins my team productivity
4. the angular team should do x, y, z
5. may be improving the doc is enough for now. btw this unrelated feature is not working
6. how "this unrelated feature is not working" ?
7. oops it's actually working
8. can we have a repro
9. here it is
10. oh it's only a typo
11. let's improve Angular error message

I would really love that we can skip steps 2-9 here !

_(I'm not trying to say than anyone in this thread is a pain. Only thinking about how we could improve the way we work with the community to be more efficient)_

**Comment by zakhenry** [comment]
@vicb yea I'm with you on that, it was a tricky issue to uncover in the first place as the error was thrown out of a third party library (ng2-bootstrap).

I think when an unrelated error is thrown there will always be a complex back and forth actually getting to the problem, but I agree this could have been shortcutted by having a repro to start with
