### ISSUE TITLE
Browser's back button go to the desired component, but does not change the browser's url

### ISSUE THREAD

**Issue by felipedrumond** [angular/angular#11755]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When I navigate back by clicking the browser's back button, the app goes to the previous route, creates the component and displays it. However, the browser's url does not go back as well.

Example: open the app in /home, click on any link that redirects to /company. The route will change to /company and the CompanyComponent will be created and displayed. Everything is fine so far. When clicking on browser's back button the route will go back to /home, HomeComponent will be created and displayed, but the browser's URL bar will keep displaying "/company", which impacts activatedRoute instance and causes the history to be outdated.

**Expected behavior**
It is expected that when activating a route via the back button, its URL will be set at the URL bar.

**Reproduction of the problem**
I could not reproduce it using a Plunker (I'm actually using angular-universal). However, the problem occurs at the client, and I could identify that when navigating back Angular moves the router back, but at some point, it cancels the navigation, which I believe is the reason why Angular is not updating the URL string at the browser's URL bar.

` this.router.events.subscribe((event: NavigationStart) => {
            if (event instanceof NavigationStart) {
                //this.saveScroll = false;
            }
        }`

Debugging the code above, I saw that the event at some point was:

**event = NavigationCancel { 
   id: 1,
   url: "/",
   reason: "Navigation ID 1 is not equal to the current navigation id 2"
}**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10, VS 2015, webpack, node server

* **Angular version:** 2.0.0 final release

* **Browser:** [all] 
 
* **Language:** [ TypeScript1.8.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by felipedrumond** [comment]
The problem was caused by injecting the app.routes not only in app.module but also in main.browser.ts.

**Comment by tvblomberg** [comment]
Hello @felipedrumond I am seeing this same behavior. I am injecting my routing in my main app module and then any module that needs routing. I was wondering how you debugged this. I feel like I am doing something like your were doing somewhere in my app. The routing was working find prior to updating to using ngmodule.

**Comment by felipedrumond** [comment]
Hello @tvblomberg. I found my mistake because in the code below, the line marked as bold was running more times than expected and, one of the events was NavigationCancel.

app.component.ts
`constructor(private router: Router, private seoService: SeoService) {
    }

    ngOnInit() {
       
        this.router.events.subscribe((event: NavigationStart) => {
            **if (event instanceof NavigationStart) {**
                
            }
        },  error => console.error(error));
    }`

Wondering the reason why that it was happening, I realized that I was importing my routes twice, in app.modules and another module.
`@NgModule({

    imports: [
        UniversalModule,
        FormsModule,
        ReactiveFormsModule,
        **routing**
    ],

Check if you imported you routes more than once and let me know.

**Comment by tvblomberg** [comment]
@felipedrumond I appreciate the quick response. I am importing the main routing in other modules since I need to use routerLink. If I do not I get an error. I know this is not support, but I am just curious how were you able to provide routing to the other modules without importing into that module?

**Comment by tvblomberg** [comment]
So I removed all the additional imports and the back button started working again. Granted now my routerLinks are broken. My guess is I am missing something trivial. I really appreciate your help you pushed me in the right direction. I spent way too much time on this last night.

**Comment by felipedrumond** [comment]
@tvblomberg, my structure is the following:

**app.routes.ts:**
`// Angular
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [
    { path: '', component: HomeComponent },
    _(other paths removed for brevity)_
];
export const routing = RouterModule.forRoot(routes);`

**app.module.ts**
`
import { NgModule, NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule, ReactiveFormsModule }   from '@angular/forms';
import { UniversalModule } from 'angular2-universal';
import { Title } from '@angular/platform-browser';

// Application & Services
import { App }  from './app.component';
import { AuthGuard } from './shared/auth-guard.service';
import { routing }  from './app.routes';

@NgModule({
    imports: [
        UniversalModule,
        FormsModule,
        ReactiveFormsModule,
        _**routing**_
    ],

    // components and directives
    declarations: [
        App,
        HomeComponent,
    ],

    // services
    providers: [
        AuthGuard,
        CloudSearchService,
        SeoService,
        Title,
        Settings
    ]
})
export class AppModule { }
`

I imported my _'routing'_ **only** in AppModule. I can use this AppModule anywhere, and I can import other modules as well, but you cannot import your 'routing' in other modules. If your routerLinks are broken, you probably need to add this code in your modules or components:

`import { RouterModule } from '@angular/router';`

**Comment by tvblomberg** [comment]
Wow @felipedrumond you are awesome! Importint RouterModule was exactly what I was missing :) ! If you are ever in Minnesota I owe you a pint!
