### ISSUE TITLE
ejs local variable in angular 2

### ISSUE THREAD

**Issue by rattrap19** [angular/angular#11753]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```
So here is my use-case:
How can I use <%= my_var %> (ejs template engine in sails.js) in angular 2, for example in this context:
  import {Component} from '@angular/core';
  @Component({
      selector: 'my-app',
      template: '[span]<%= my_var %>[/span]'
  })
  export class AppComponent {
      title = 'title';
  }

**Current behavior** 
Shows up <%= my_var %>

**Expected behavior**
Value of my_var

**Please tell us about your environment:**
Linux ubuntu 15.10, node.js, sails.js, ejs

* **Angular version:** 2.0.0-rc.X
2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
Chrome 53.0.2785.116, Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0
 
* **Node (for AoT issues):** `node --version` =   6.3.1

**Comment by pkozlowski-opensource** [comment]
Please use an appropriate support channel for the general framework usage questions: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
