### ISSUE TITLE
Localization formatters  performance

### ISSUE THREAD

**Issue by vicb** [angular/angular#11760]
L10N pipes use the Intl API: `Intl.NumberFormat(...)`.

This API is known to be slow.

We should do some benchmarks and if really proves to be slow then cache & re-use those formatters

**Comment by pkozlowski-opensource** [comment]
> This API is known to be slow.

@vicb do you have any "hard" data on this / more info?

**Comment by vicb** [comment]
Nope, would need a benchpress test.

**Comment by ocombe** [comment]
This is not really needed if we're removing intl

**Comment by DzmitryShylovich** [comment]
>  we're removing intl

in favor of?

**Comment by ocombe** [comment]
*if* :-)

We are still talking about what our options are, but intl has a lot of issues right now... we need to find an alternative solution

**Comment by DzmitryShylovich** [comment]
I already suggested date-fns https://github.com/angular/angular/issues/10809#issuecomment-264664280

**Comment by ocombe** [comment]
That's not the subject here, but thank you for your suggestion, the other issue that you linked is used for the internal debate. Once we have something interesting to propose there will be a public design doc where you will be able to add comments/suggestions.

**Comment by ocombe** [comment]
We no longer use intl, closing this.
