### ISSUE TITLE
Where are the static files?

### ISSUE THREAD

**Issue by dl748** [angular/angular#11764]
Where are the static prebuilt files for angular 2? https://code.angularjs.org/ has nothing new since April and although I can use NodeJS, I can't seem to use it to build Angular 2 anymore as it tries to use all the ram of my pc as well as all the swap and still fails. I guess 8 Gigs of ram and 8 gigs of swap are not enough to "compile" Angular 2 and all its dependencies (some Gulp program is using all the ram)

**Comment by pkozlowski-opensource** [comment]
We are no longer publishing pre-build bundles on code.angularjs.org. Those are re-distributed as part of the npm packages and you can easily target those from a browser by using https://unpkg.com/#/

Check the `config.js` files of a sample plunk for the exact links: https://plnkr.co/edit/J5pdkE68MKLDAUknH2lP

**Comment by dl748** [comment]
But I can't because the end user does not have access to the internet, so if i target that, nothing would load for them.

**Comment by dl748** [comment]
Ok, then why does the quick tutorial download and compile the source? instead of using the npm redist packages?  I can't even get the quick tutorial to work because it uses >16gigs of ram
