### ISSUE TITLE
2.0 final generated js files contain import/export statements even with commonjs and es5 specified in the tsconfig.json

### ISSUE THREAD

**Issue by DanielJoyce** [angular/angular#11771]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

I am trying to use the angular2 DI component on Nashorn/Vertx3. This working fine under the Angular2 RC, but upgrading to release has caused it to barf. We're doing this to leverage code written for the front end on the backend as well. The front end code makes use of di to compose services to talk to several front end services written against HTML5 and cordova plugin apis. On the back end we were planning to reuse some of this middle layer code. Since it uses angular DI, I got Angular DI working on the server as well through judicious imports of js files as angular 'core' as a bundle assumed the existence of Ajax and Event.

**Expected behavior**

Service successfully starts

**Reproduction of the problem**

Upgraded to angular2 release, it breaks.

The stacktrace is this, it breaks on trying to import OpaqueToken

[0] Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>#88:17<eval>:8:0 Expected an operand but found import
[0] import { Injectable } from './metadata';

Specifically its barfing on the import keyword which does not exist in es5.

The angular projects tsconfig.json says should be spitting out es5.

https://github.com/angular/angular/blob/master/modules/tsconfig.json

Specifically the combination of "module" : "commonjs" and "target":"es5" should mean no import keywords in generated source code.

``` json
{
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "../dist/all/",
    "noImplicitAny": true,
    "noFallthroughCasesInSwitch": true,
    "paths": {
      "selenium-webdriver": ["../node_modules/@types/selenium-webdriver/index.d.ts"],
      "rxjs/*": ["../node_modules/rxjs/*"],
      "@angular/*": ["./@angular/*"],
      "@angular/tsc-wrapped": ["../dist/tools/@angular/tsc-wrapped"]
    },
    "rootDir": ".",
    "inlineSourceMap": true,
    "lib": ["es5", "dom", "es2015.promise", "es2015.collection", "es2015.iterable"],
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "target": "es5"
  },
  "exclude": [
    "angular1_router",
    "angular2",
    "benchmarks/e2e_test/old",
    "benchmarks/src/old",
    "benchmarks_external",
    "payload_tests",
    "rollup-test",
    "@angular/compiler-cli/integrationtest"
  ]
}
```

**Here is an example of the change in generated code from the RC to the release**

**OpaqueToken in Angular 2.0.0-rc.5:**

```javascript
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
"use strict";
var decorators_1 = require('./decorators'); // so that metadata is gathered for this class
var OpaqueToken = (function () {
    function OpaqueToken(_desc) {
        this._desc = _desc;
    }
    OpaqueToken.prototype.toString = function () { return "Token " + this._desc; };
    /** @nocollapse */
    OpaqueToken.decorators = [
        { type: decorators_1.Injectable },
    ];
    /** @nocollapse */
    OpaqueToken.ctorParameters = [
        null,
    ];
    return OpaqueToken;
}());
exports.OpaqueToken = OpaqueToken;
//# sourceMappingURL=opaque_token.js.map


```

**OpaqueToken in 2.0.0 final:**

``` javascript
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
import { Injectable } from './metadata';
/**
 * Creates a token that can be used in a DI Provider.
 *
 * ### Example ([live demo](http://plnkr.co/edit/Ys9ezXpj2Mnoy3Uc8KBp?p=preview))
 *
 * ```typescript
 * var t = new OpaqueToken("value");
 *
 * var injector = Injector.resolveAndCreate([
 *   {provide: t, useValue: "bindingValue"}
 * ]);
 *
 * expect(injector.get(t)).toEqual("bindingValue");
 * ```
 *
 * Using an `OpaqueToken` is preferable to using strings as tokens because of possible collisions
 * caused by multiple providers using the same string as two different tokens.
 *
 * Using an `OpaqueToken` is preferable to using an `Object` as tokens because it provides better
 * error messages.
 * @stable
 */
// so that metadata is gathered for this class
export var OpaqueToken = (function () {
    function OpaqueToken(_desc) {
        this._desc = _desc;
    }
    OpaqueToken.prototype.toString = function () { return "Token " + this._desc; };
    OpaqueToken.decorators = [
        { type: Injectable },
    ];
    /** @nocollapse */
    OpaqueToken.ctorParameters = [
        null,
    ];
    return OpaqueToken;
}());
//# sourceMappingURL=opaque_token.js.map
```

Due to other limitations I was pulling in the JS files directly, as the bundled core file in the RC had dependencies on Ajax and Event, something that doesn't exist in the server environment.

**Comment by DanielJoyce** [comment]
Okay, looks like I will just do a custom build as it seems there is no info anywhere as to what 'kind' of js a npm package installs. CommonJS? es5? es6? UMD? Who knows? Npm will just install whatever. package.json won't tell you. Its whatever the package authors decide to do. Stuff that works a week ago suddenly breaks because build options change.

**Comment by DanielJoyce** [comment]
yeah, at some point the artifact generation ( before bundling ) was changed so its no longer plain es5. Why was it changed?

**Comment by pkozlowski-opensource** [comment]
> yeah, at some point the artifact generation ( before bundling ) was changed so its no longer plain es5. Why was it changed?

es2015 module output is mandatory to support proper tree-shaking with tools like Rollup / WebPack 2 (which uses Rollup behind the scenes). @robwormald might have more info.

**Comment by DanielJoyce** [comment]
Well the problem then is DI still hasn't been split out into a proper module. So if you use the core bundle it brings in a whole bunch of stuff that doesn't exist server side like dom events and animations. 

Angular2 used to have a blurb about using their DI without angular. And it works, but now its even more difficult to tear stuff out.

And this shows the undocumented dependency mess that is node packages. One package is installed is es5. Another is installed as es2015 because another build step might want to browserify/treeshake it, and there is no documentation anywhere on any of this. 

Its a complete mess. :-1:

**Comment by robwormald** [comment]
We switched bundling strategies to enable smaller package sizes for end user applications. Each package has both ESM code and a UMD bundle you can use in any enviroment.

Each package's `"main"` field points at the UMD bundle, so it should work seamlessly in most environments - the only way to ingest the ES module source code is by doing *deep* imports into code, which involves you using private APIs that may break without warning - we strongly suggest you don't do this.

Core is purposely not dependent on any actual Browser APIs (that's what the platform-____ ) are for, so there should be no reason you can't use it in Node or Nashhorn or basically any modern VM. If you're running into issues here, please let us know.

You are of course, more than welcome to build your own bundle that just contains DI, and us shipping ES module code allows you to do that even more efficiently: here's simple rollup script that will build you a UMD bundle from the ESM code, containing only DI
```ts
//build.js
var rollup = require('rollup');

rollup.rollup({
  entry: 'node_modules/@angular/core/src/di.js'
}).then(bundle => {
  return bundle.write({
    dest: './ng2-di.js',
    format: 'umd',
    moduleName: 'ng.di'
  })
}).catch(err => console.log(err))

```
`npm install rollup`
`node build.js`

See https://plnkr.co/edit/fPnbsCgXq5PbVceKcaqm?p=preview for an example of using it.

**Comment by tbosch** [comment]
Closing as all questions have been addressed.
