### ISSUE TITLE
$setViewValue not working since Angular update 1.4.9

### ISSUE THREAD

**Issue by xtoff** [angular/angular#11783]
I created a directive that clears my ngModel value when the element is destroyed (removed from DOM). I used "ngModel.$setViewValue(undefined)" to clear the model value.

This worked in Angular versions lower than 1.4.9. I checked the update changes from version 1.4.8 -> 1.4.9, but found nothing that can relate to this issue.

Here is my directive code:
`(function() {
    'use strict';

    // MODULE
    angular.module('portal.generic.directives').directive('destroyModel', destroyModel);

    // DEPENDENCY INJECTION
    destroyModel.$inject = [];

    // DIRECTIVE
    function destroyModel() {
        return {
            restrict: "A",
            require: '?ngModel',
            link: function(scope, elem, attrs, ngModel) {

                if(elem.attr('type') !== 'radio'  && attrs.value) ngModel.$setViewValue(attrs.value);

                elem.on('$destroy', function(event){
                    // check if the element is destroyed when navigating to the summary page or by hiding the element
                    var navigateToSummaryPage = scope.$eval(attrs.navigateToSummaryPage);

                    // delete the ng-model value when the element is removed from the DOM
                    if(!navigateToSummaryPage) {
                        ngModel.$setViewValue(undefined);
                    }
                })
            }
        };
    }})();`

Anyone know how to fix this or maybe use a different aproach to clear my ngModel?

Thanks

**Comment by pkozlowski-opensource** [comment]
Wrong repo. Guess you are looking for https://github.com/angular/angular.js
