### ISSUE TITLE
global.Promise overwritten error

### ISSUE THREAD

**Issue by RaleS** [angular/angular#11788]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
After upgrade from RC4 to 2.0.0 the _global.Promise_ gets overwritten by Bing Maps script bringing the app to halt. This has not been the case with RC-versions.

**Reproduction of the problem**
http://plnkr.co/edit/vZGA1LLlVd6AF1l7rnJ5?p=preview

**Please tell us about your environment:**
Win10, VS2015

* **Angular version:** 2.0.0-rc.X
^2.0.0 (zone.js 0.6.23)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
Chrome 53 | Firefox 48 | Edge 25
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS1.8
 
* **Node (for AoT issues):** `node --version` =   
6.6.0

**Comment by vicb** [comment]
Could you please try to reproduce the problem with only zone.js (ie outside of Angular) and submit the bur report to the angular/zone.js repo?

**Comment by mhevery** [comment]
The error is telling you that `Bing Maps` is overwriting the global Promise and hence breaking zone. Before we would just use the overwritten `Promise` and fail in strange ways. Now we fail a early to let you know. 

BTW, your plunker does not reproduce.

Fix may be to simple move the bind script file in front of the Zone.

**Comment by RaleS** [comment]
Yes, the app loads once `Bing Maps` script is removed.

The plunker reproduces the error. You will have to either set a break point in zonejs@0.6.23 line 16 to see that error is thrown, use "Pause On Caught Exceptions" in Chrome, or "Break on all exceptions" in Edge. The error never makes into console log as it is handled by `Bing Maps` `fc288a87.js`

Loading the bind script before Zone does not solve the problem, as you may try in the above plunker.

**Comment by RaleS** [comment]
I have made a new plunker using only Zone.js and `Bing Maps`, and created an issue on zone.js
https://github.com/angular/zone.js/issues/465
