### ISSUE TITLE
How to set up angular 2 App for php server. I am using php as back end  i am not familer with Node and in angular 1 their is only one angular js file need for run a basic app but angular 2 have too many files its hard to understand.

### ISSUE THREAD

**Issue by arunreghu** [angular/angular#11787]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
