### ISSUE TITLE
Angular 1 Directive is not upgradable in Angular 2.0.0

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#11785]
The code snippet is as below : 

1. Angular 1 directive
angular.module('my.module.common.directives.personalization').directive('myRecommendations', [
  ' ',.....dependencylist
    function (dependencyList) {

        return {
            templateUrl:function(tElement, tAttrs) {
                var templateType=angular.safeEval(tAttrs,"templateType");
                console.log("templateType:::::" + templateType);
                return RecommendationHelper.getRecommendationTemplateByType(templateType);
            },
            requires: '^attPersonalization',
            restrict: 'EA',
            scope: {
                //pageId: "@",                
                //templateType: "@",                
                //slotId : "@",              
                // promoId : "@",
                 //returnUrl: "@",
                 hideRecommendations : "@",               
                 show_loading_image:"@",               
                 carousal_heading:"@",
                 
                 //angular 2
                 pageId: '@pageId',
                 templateType:"@templateType",
                 slotId:"@slotId",
                 promoId : "@promoId",
                 returnUrl: "@returnUrl",
                 showLoadingImage : "@showLoadingImage",
                 carousalHeading: "@carousalHeading"
            },
           
//            controller: function ($scope, $element, $attrs, $transclude, $rootScope) {
              //$attr and $transclude not supported in angular 2
              controller: function ($scope,$rootScope) {
                $log.info("In attRecommendations Directive ");
                //var pageId = angular.safeEval($attrs,'pageId');
                //var slotId = angular.safeEval($attrs,"slotId");
                var pageId = $scope.pageId;
                var slotId = $scope.slotId;
                var promoId =  $scope.promoId //angular.safeEval($attrs,"promoId");
                var hideRecommendations = angular.evalBoolean($scope.hideRecommendations);

                var returnUrl = $scope.returnUrl;
                if (angular.isBlank(returnUrl)) {
                    returnUrl = $location.absUrl();
                }

                $log.log("In attRecommendations Directive pageId[" + pageId + "] slotId["+slotId+"] hideRecommendations["+hideRecommendations+"]");
                if (angular.isNotBlank(pageId) && !hideRecommendations) {
                    RecommendationHelper.registerRecommendationsImpressionEvent();
                    $rootScope.recommendationPageId=pageId;
                    RecommendationHelper.incrementNumberOfPromoSlotRegistered();
                    var decFun = $rootScope.$on('showPromoRecommendations', function (event, apiResponse, apiExecutionTime) {
                        RecommendationHelper.decrementNumberOfPromoSlotRegistered();
                        var startTime = new Date().getTime();
                        
                        $rootScope.recommendationPageId=null;
                        $log.info("in attRecommendations after broadcast area");
                        if (angular.isNotBlank(apiResponse)) {
                            var transactionId = angular.safeEval(apiResponse, "status.transactionId");
                            var apiRecommendations = angular.safeEval(apiResponse, "recommendations");
                            var filteredRecommendations = RecommendationHelper.filterRecommendationsBySlotId(apiRecommendations,slotId);
                            filteredRecommendations =RecommendationHelper.addRotationPositionToRecommendations(filteredRecommendations);
                            var showFiltersOnMIP = false;
                            var keySetFromRecom = RecommendationHelper.addKeywordsFromRecommendations(apiRecommendations);
                            if(keySetFromRecom.length>0){
                                showFiltersOnMIP = true;
                            }
                           // $scope.carousalHeading="My Heading"
                          
                            $rootScope.recommendations=apiRecommendations;
                            $scope.recommendations = filteredRecommendations;
                            $scope.recommendationFilterKeys =keySetFromRecom;
                            $scope.showFiltersOnMIP = showFiltersOnMIP;
                            $scope.recFilter ={};
                            $scope.showLoadingImage=false;
                            $scope.handleRecommendationClick = function (recommendation) {
                                if (angular.isNotBlank(recommendation)) {
                                    /* Reporting */
                                    RecommendationHelper.reportRecommendationClick(pageId,recommendation);
                                    if (personalizationConfig.recommendationTrackingEnable) {
                                        /*Handle Recommendation click with internal Tracking*/
                                        var trackingPromise = RecommendationHelper.reportRecommendationToPersonalizationService($scope,recommendationService,pageId,slotId,transactionId,recommendation,returnUrl);
                                        if(angular.isNotBlank(trackingPromise)){
                                            trackingPromise.then(function (data) {
                                                $log.info("Broadcasting recommendations after getting api response");
                                                RecommendationHelper.handleRecommendationClick($scope, recommendation, returnUrl);
                                            }, function (e) {
                                                $log.error("Error while reporting recommendations to personalization services" + e);
                                                RecommendationHelper.handleRecommendationClick($scope, recommendation, returnUrl);
                                            });
                                        }
                                    } else {
                                        RecommendationHelper.handleRecommendationClick($scope,recommendation,returnUrl);
                                    }
                                }
                            };
                            
                            //This function is called on click of the filter Keys from MIP Page
                            $scope.handleKeywordsClick = RecommendationHelper.getKeywordClickHandler($scope);
                            
                            //RecommendationHelper.reportRecommendationImpression(filteredRecommendations,pageId);
                            RecommendationHelper.reportPromotionRecommendationImpression(filteredRecommendations);
                            if(angular.isNotBlank(filteredRecommendations)){
                                RecommendationHelper.reportSlotEvent($scope, pageId,true);
                            }else{
                                RecommendationHelper.reportSlotEvent($scope, pageId,false);
                            }

                            if (personalizationConfig.recommendationTrackingEnable) {
                                $log.info("Reporting recommendations to PersonalizationService");
                                var endTime = new Date().getTime();
                                var feExecutionTime = endTime - startTime;
                                RecommendationHelper.cacheRecommendationImprReportingForSlot(slotId,filteredRecommendations,feExecutionTime);
                                var numberOfSlotLeft = RecommendationHelper.getNumberOfPromoSlotRegistered();
                                if(numberOfSlotLeft==0){
                                    var slotWiseReportingData = RecommendationHelper.getRecommendationImprReportingForSlotFromCache();
                                    if(angular.isNotBlank(slotWiseReportingData)){
                                        var reportingRequest = RecommendationHelper.createRecommendationReportingImprRequest(pageId, apiResponse, slotWiseReportingData, apiExecutionTime);
                                        if (angular.isNotBlank(reportingRequest)) {
                                            recommendationService.reportRecommendations(reportingRequest);
                                            RecommendationHelper.clearCacheRecommendationImprReportingForSlot();
                                        }
                                    }
                                }
                            }
                        } else {
                            $log.error("In attRecommendations Directive: Recommendation Service Response is blank");
                        }
                    });

                    $scope.$on('$destroy', function() {
                        decFun();
                    });
                    /**US635798 : To Show Customized disclaimer for promotion
                    *  This function will trigger custom Disclaimer modal, finds the recommendation from recommendations and puts the disclaimer in the root
                    *  Input recommendationId */
                    $scope.trigerCustomDisclaimer = function(recommendationId){
                        var recommendations = $scope.recommendations;
                        if(angular.isNotBlank(recommendations)){
                            for(var j=0; j< recommendations.length; j++){
                                if(recommendations[j].recommendationId === recommendationId){
                                    $rootScope.recommedationDisclaimer = recommendations[j].promoDisclaimer;
                                    angular.element('#tncModal').modal('show');
                                    break;
                                }
                            }
                        }else{
                            $log.error("In attRecommendations Directive:trigerCustomDisclaimer: Recommendation Service Response is blank");
                            angular.element('#tncModal').modal('show');
                        }

                    };
                    RecommendationHelper.registerRecommendationsEvent($scope,pageId,slotId,promoId,recommendationService);

                }

            }
        };

    }]);

2. NG2 app module
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }   from './app.component';

@NgModule({
    imports: [BrowserModule,FormsModule],
    declarations: [
        AppComponent
    ],
    providers        : [All required provider list    ]

})
export class AppModule { }

3. App Component
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: '<div *ngIf="WlsPromoLinksSection.isWirelessLifeCycle">
    <my-recommendations pageId="WIRELESS-DASHBOARD" slotId="DASHBOARD-CAROUSEL-SLOT" showLoadingImage="true"></my-recommendations>
</div>'
})
export class AppComponent { }

4. upgrade apapter
import { NgModule}      from '@angular/core';
import {AppModule} from './app.module';
export const upgradeAdapter = new UpgradeAdapter(AppModule);

5. main.ts
upgradeAdapter.upgradeNg1Component('attRecommendations');

upgradeAdapter.bootstrap(document.body, ['myApp'], { strictDi: true }).ready(function() {
    console.log("Hybrid Bootstrapped");
});

Error comes : 
Unhandled Promise rejection: Template parse errors:
'my-recommendations' is not a known element:
1. If 'my-recommendations' is an Angular component, then verify that it is part of this module.

**Comment by vasuneet** [comment]
Hi . Even i tried a simples version of directive which just contain a template and that's it. That also giving same error.

**Comment by guojenman** [comment]
@vasuneet Not all of ng1's features are supported by UpgradeAdapter. I see in your sample that you're using 'restrict': 'EA', which is not supported.

see https://angular.io/docs/ts/latest/api/upgrade/index/UpgradeAdapter-class.html#!#upgradeNg1Component-anchor for list of supported features.

Generally, your angular directives should be written using angular.component() to increase the likelihood of meeting upgrade requirements.

I've been slowly upgrading an app which has more 50k lines of code and I find it easier and less painful to start from top leafs to bottom, write NG2 components and downgrade them to NG1 (I've experienced little to no problem with this route). Most NG1 components that I need to upgrade, I usually just rewrite in NG2 and downgrade back to NG1 so I can share with my existing views.

I hope that help.

**Comment by vasuneet** [comment]
even the following directive , i am not able to upgrade using upgradeAdapter:
myApp.directive('isRecommendationAvailable', [
    '$log',
    '$rootScope',
   
    function ($log,$rootScope) {
        return {
           
            template:'Hello World!',
            scope:{
                  slotId:"@slotId",
                  attributeName:"@attributeName"                  
            },
//       
              controller: function ($scope) {
                
                console.log("testing purpose only");
            }
        };
    }]);

**Comment by guojenman** [comment]
@vasuneet if you look at the docs, in NG1, the default value for restrict is 'AE' - this is **NOT** supported. Only E is supported.

https://docs.angularjs.org/guide/directive#restrict

Again, your best bet is refactor your directives to use the angular.component syntax. If you do that, you've resolve 90% of your issues, otherwise, you'll need to be more careful on what is and what is not supported. It's pretty well documented.

I've created a plnkr for you which illustrating using both component & directive methods
https://plnkr.co/edit/VkXvwL?p=preview

You can fork this plnkr and test. Also, for future request for help, it's nice if you use plnkr and create a reproducible project which illustrate what you're asking for.

**Comment by vicb** [comment]
Closing as not an issue.
