### ISSUE TITLE
Priority for UpgradeAdapter bugs

### ISSUE THREAD

**Issue by palmanis** [angular/angular#11784]
**I'm submitting a ...**  (check one with "x")

```
[x ] Discussion around Angular team's priorities. 
```

Currently there are [28 issues](https://github.com/angular/angular/issues?q=is%3Aissue+is%3Aopen+label%3A%22comp%3A+upgrade%22) annotated as related to upgrade adapter.

In addition there are few more for e.g. #8856, which i had raised, which has not yet been annotated.
I would assume, most, if not all, the folks, who have already invested a lot in Angular 1.x, and have built large scale libraries or applications using Angular 1.x, they would want to go ahead with the Upgrade route, rather than doing a big bang re-write. And i am hoping that was the idea behind creating the Upgrade Adapter right ?

So we are pretty much not able to start that process of upgrade, because of these bugs. A long delay in solving these issues would mean, lot of people like us would either consider dropping the upgrade plan or exploring other alternatives. 

Can we please get an idea around, where these issues feature in your priority list ? By when can we expect these to get resolved, so that we can also join in the journey towards Angular 2.0 ?

Thank You

**Comment by hg-eric** [comment]
I would also like to mention that the UpgradeAdapter documentation is still in Pre-RC5 state. If it is still desired that people use the upgrade option to adapt to angular 2, the documentation should be updated ASAP.

**Comment by petebacondarwin** [comment]
@palmanis - there are members of the Angular 1 team now also working on the `upgrade` and `upgrade/static` libraries. We are working our way through the issues and PRs. Hopefully you have seen more activity in the last month or so.

@hg-eric - we now have a pretty decent guide for `upgrade/static` - https://angular.io/docs/ts/latest/guide/upgrade.html - please help us make this and the API docs better by reporting problems with them.

**Comment by hg-eric** [comment]
Cheers pete, already saw the new guide. It just took a while until it was online. I'll have a look and report any issues I can find.
