### ISSUE TITLE
Angular2 (2.0.0) internal run time error from a Component

### ISSUE THREAD

**Issue by ssashok10** [angular/angular#11790]
I am working on a application which uses Angular2 2.0.0. One of the component from my application is throwing an internal error during application execution. The same exact component works fine with Angular2 RC5. I just migrated the application from RC5 to 2.0.0. Is that a expected error message in any scenario? I feel that its a bug as the message is coming from Angular2 framework instead of a user friendly error which points to line of the code where the exact error occurs.

Error:
  core.umd.js:3462 EXCEPTION: Uncaught (in promise): Error: Error in ./SearchComponent class SearchComponent_Host - inline template:0:0 caused by: No provider for RuntimeCompiler!

**Comment by vicb** [comment]
Are you trying to inject the compiler ?

**Comment by vicb** [comment]
Please add a minimal repro in a plunker.

**Comment by felipedrumond** [comment]
Have you added your SearchComponent in your declarations in your @module?

**Comment by ssashok10** [comment]
Sorry for the late update. This error vanished after i cleared up the "node_modules" folder and downloaded all the files again.
