### ISSUE TITLE
SCSS - components can't work with my global scss

### ISSUE THREAD

**Issue by itayJoseph** [angular/angular#11791]
So I have styles.scss that import list of style from my scss folder.
The Issue happens when I try to use variables or mixins  that are defined and Imported inside my styles.scss.
`// GLOBALS

@import 'scss/index';`

I get this error 

> 
ERROR in ./src/app/navigation/navigation.component.scss
Module build failed:
    @include shadow-1;
            ^
      No mixin named shadow-1

I can solve this only If import the styles.scss directly to the component.scss.
Importing the global scss to all components every time is weird. 

please help.

**Comment by pkozlowski-opensource** [comment]
This doesn't sound like something directly related to Angular. Please use a dedicated support channel for those types of questions: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
