### ISSUE TITLE
Webpack: An Introduction guide --> Failed to load resource

### ISSUE THREAD

**Issue by doubleUTF** [angular/angular#11807]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I followed the steps to the T on this page [https://angular.io/docs/ts/latest/guide/webpack.html](url) on two separate machines but on both instances I get the following errors in the Chrome F12 console: 

> Failed to load resource: the server responded with a status of 404 (Not Found)
(program):355 Unhandled Promise rejection: Failed to load app.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load app.component.html undefinedconsoleError @ (program):355
(program):357 Error: Uncaught (in promise): Failed to load app.component.html(…)consoleError @ (program):357
http://localhost:8080/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

Webpack bundle appears to be valid on the console:

> C:\App_projects\angular2-webpack  (angular2-webpack@1.0.0)
λ npm start

> angular2-webpack@1.0.0 start C:\App_projects\angular2-webpack
> webpack-dev-server --inline --progress --port 8080
> 70% 3/3 build modules http://localhost:8080/
> webpack result is served from http://localhost:8080/
> content is served from C:\App_projects\angular2-webpack
> 404s will fallback to /index.html
> chunk    {0} app.js, app.css (app) 3.21 kB {2} [rendered]
> chunk    {1} polyfills.js (polyfills) 462 kB [rendered]
> chunk    {2} vendor.js (vendor) 2.37 MB {1} [rendered]
> Child html-webpack-plugin for "index.html":
>     chunk    {0} index.html 325 bytes [rendered]
> Child extract-text-webpack-plugin:
>     chunk    {0} extract-text-webpack-plugin-output-filename 1.97 kB [rendered]
> webpack: bundle is now VALID.

**Expected behavior**
There should be a page with the Angular logo but all I get is a 'Loading...' message.

**Reproduction of the problem**
All the files are named correctly and in their correct locations per the instruction guide. In 'app.component.ts', I replaced the templateUrl and styleUrls with inline code and the text renders fine but still doesn't find '../../public/images/angular.png' properly. There is something wrong with Angular resolving files involving pathnames.

**Please tell us about your environment:**
Win7, Atom IDE, Cmder console, Chrome browser.

* **Angular version:** 2.0.0-rc.X
 
* **Language:** All
 
* **Node (for AoT issues):** `node --version` =   6.3.1

**Comment by pkozlowski-opensource** [comment]
Please try a support forum (https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question) and if you believe that there is a problem with a guide please open an issue in https://github.com/angular/angular.io where the guide in question is located.

cc @Foxandxss
