### ISSUE TITLE
sanitizing unsafe URL value javascript:;

### ISSUE THREAD

**Issue by faisalloe** [angular/angular#11805]
Angular 2 final release.

I have my link as following with refers to the href="javascript:;" 
<a href="javascript:;"> my link<a/>

and i am getting following warning

`    WARNING: sanitizing unsafe URL value javascript:; (see http://g.co/ng/security#xss)
`
I need my link to be javascript:; because if i make it '#' or '' it refreshes the page.

i am generating elements dynamically. they can have direct links or drop downs. if they link i use url to populate in href. if they drop down i make href as void(0); so clicking on it should not refresh the page.

I have read couple of posts where people report this issue to angular folks and they will fix it.. any help is appreciated.

**Comment by pkozlowski-opensource** [comment]
I don't think you want to trick sanitization here. If you are using a link that has a click event and it shouldn't trigger navigation just prevent default action on the event, ex.:
* `<a (click)="$event.preventDefault(); doSth()">` or even shorter
* `<a (click)="!!doSth()">`

**Comment by faisalloe** [comment]
awesome. worked.

**Comment by rodhoward** [comment]
What about if you're trying to download a csv file from the client. something like:

.html:
`<a #csvDownloadLink [attr.href]="csvFile" [attr.download]="csvFileName" target="_blank"></a>`

.ts:
```
this.csvFile = encodeURI('data:text/csv;charset=utf-8,' + this.convertReportDataToCSV());
this.csvFileName = this.reportDef.name + '.csv';
this.csvDownloadLink.nativeElement.click();
```
In that case I think I want the link to do the default stuff.

**Comment by rodhoward** [comment]
Never mind I worked it out you need to use:
`import { DomSanitizer } from '@angular/platform-browser';`

then this line becomes:

`this.csvFile = this.sanitizer.bypassSecurityTrustResourceUrl(encodeURI('data:text/csv;charset=utf-8,' + this.convertReportDataToCSV()));`

Then it all seems to work except click call seems to need to happen on a setTimeout out which sucks.

**Comment by jsgoupil** [comment]
A link without a `href` tag is not considered clickable.

> If the href attribute is absent, then the element does not define a link.

Firefox will be happy to not put the right cursor for &lt;a> tags missing a href.
