### ISSUE TITLE
Argument of type 'Http' is not assignable to parameter of type 'Http'

### ISSUE THREAD

**Issue by kurapatijayaram** [angular/angular#11801]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
```javascript
class RESTClient {
   constructor(@Inject(Http) protected http: Http){
   }
   //Some code
}

@Injectable()
@BaseUrl("https://api.github.com/")
export class ReposService extends RESTClient{
  apiUrl: string = "https://api.github.com/";

  constructor(private _http: Http){
    super(_http)
  }

  @GET("orgs/angular/repos")
  list(){
    return null;
  }
}
```
Above code is throwing following error:
```shell
error TS2345: Argument of type 'Http' is not assignable to parameter of type 'Http'.
  Property '_backend' is protected but type 'Http' is not a class derived from 'Http'.
```
**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

macOS Sierra, atom, npm

* **Angular version:** 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** TypeScript 1.8.10
 
* **Node (for AoT issues):** `node --version` =   6.3.0

**Comment by vicb** [comment]
probably HTTP is imported from different location ?

btw you don't need `@Inject(Http)` and your class should be `@Injectable`

**Comment by kurapatijayaram** [comment]
Got it, I am using the mentioned code package with npm link, If I do npm install or copy the package to node_modules then its working fine. I think there is some bug in "npm link".

**Comment by st3h3n** [comment]
> Got it, I am using the mentioned code package with npm link, If I do npm install or copy the package to node_modules then its working fine.

I can confirm this. Here is my case:

```Typescript
import { Http } from '@angular/http';
import { SomeService } from 'myModule';
import { Config, CONFIG } from 'path/to/config/';

let someServiceFactory = (http: Http, config: Config) => {
  return new SomeService(http, config.someVariable);
}
export let someServiceProvider = {
  provide: SomeService,
  useFactory: someServiceFactory,
  deps: [Http, CONFIG]
};
```

Same error, but works when myModule is installed rather than "npm link"ed.

**Comment by st3h3n** [comment]
> probably HTTP is imported from different location ?

Indeed, when using npm link your dependency tree looks like this:

```
Project
+-- @angular/http@2.1.1
`-- myModule
  `-- @angular/http@2.1.1  extraneous
```

A solution would be to add @angular/http as peerDependency in myModule. But then when developing myModule IntelliSense would complain about not finding @angular/http.

**Comment by aniruddhadas9** [comment]
I am facing the same issue. i publish my module in private npm package manager using sinopia and after installing the module in another module, it shows the error

**Comment by iXHensel** [comment]
@vicb This is still an issue. As you wrote above Http **is** imported from a different location:

>>probably HTTP is imported from different location ?

>Indeed, when using npm link your dependency tree looks like this:
>```
>Project
>+-- @angular/http@2.1.1
>`-- myModule
>  `-- @angular/http@2.1.1  extraneous
>```
>A solution would be to add @angular/http as peerDependency in myModule. But then when developing myModule IntelliSense would complain about not finding @angular/http.

Is there no workaround for this? I have created [this](https://github.com/iXHensel/npm-link-angular-test-base) for reproduction

**Comment by lpalli** [comment]
I've the same issue, if I remove the `@angular/http` folder from "library" `node_modules` the using project work fine but in the "library" IntelliSense don't find it!
