### ISSUE TITLE
Document use of Mock http backend for testing

### ISSUE THREAD

**Issue by wolfgangmeyers** [angular/angular#11803]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

Documentation is missing from https://angular.io/docs/ts/latest/guide/testing.html

**Expected behavior**

Documentation should provide concrete examples of how to properly use the mock http backend in jasmine tests. I've found varying examples on the internet (like http://chariotsolutions.com/blog/post/testing-http-services-angular-2-jasmine/) but it would be nice to have an official example in the angular docs.

**Comment by pkozlowski-opensource** [comment]
Could you please open it in https://github.com/angular/angular.io where the documentation lives? Thnx!
