### ISSUE TITLE
refactor(dart/transform): Rename setupReflection => reflectorInit

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#1180]
Per discussion in the [Code Lazy Loading Design Doc][1].

This should be a 1-line change in `src/transform/common/names.dart`.

[1]: https://docs.google.com/document/d/184KvGL9Kz5ycIRlvo490dDaa876VSvv9YRDdQvgGYNs/edit#

**Comment by pkozlowski-opensource** [comment]
@kegluneq do we want to keep references to forks in commit messages? It was slightly confusing for me.

**Comment by kegluneq** [comment]
Nope, I was planning on removing that msg prior to committing to master. Should I avoid those references in the future? I'm still learning how to be a good git neighbor.

**Comment by pkozlowski-opensource** [comment]
At the end of the day it is about communicating important bits to someone who will be reading the commit history in the distant future. I guess what is relevant is an issue id it fixes and PR it closes. If you didn't open an issue in the main repo I guess just having `Closes #1180` would be enough.
