### ISSUE TITLE
Angular 2.0.0 generates invalid Content-Type header for multipart/form-data requests if a default Content-Type header is configured

### ISSUE THREAD

**Issue by Nick-Triller** [angular/angular#11819]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
If defaultOptions with header Content-Type is set for http, firing a post request with a FormData body and with header Content-Type null or "" leads to the generation of a corrupt Content-Type header.
The Content-Header includes a comma: `content-type:, multipart/form-data; boundary=----WebKitFormBoundarylBX4sMHGfDQcsyPM`.

**Expected behavior**
Passing an empty Content-Type header triggers angular's multipart/form-data routines if the body is a FormData object. Without the defaultOptions, the Content-Type header generation works correctly. The Content-Type header generation should not insert a comma if the header Content-Type is set in the http defaultOptions.

**Reproduction of the problem**
See https://github.com/Nick-Triller/angular2-typescript-webpack

Relevant files:
- app/app.component.ts
- app/app.module.ts
- app/http-interceptor.ts

app.module.ts:
```typescript
import {NgModule}      from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {HttpModule, RequestOptions, XHRBackend, Http} from '@angular/http';

import {AppComponent}  from './app.component';
import {HttpInterceptor} from "./http-interceptor";

@NgModule({
    imports: [
        BrowserModule,
        HttpModule
    ],
    declarations: [
        AppComponent
    ],
    providers: [
        // HttpInterceptor
        {
            provide: Http,
            useFactory:
                (xhrBackend: XHRBackend, requestOptions: RequestOptions) =>
                    new HttpInterceptor(xhrBackend, requestOptions),
            deps: [XHRBackend, RequestOptions]
        }
    ],
    bootstrap: [
        AppComponent
    ]
})

export class AppModule {}
```

app.component.ts:
```typescript
/// <reference path="../typings/index.d.ts" />

import {Component} from '@angular/core';
import {Http, RequestOptionsArgs, RequestOptions, Headers} from "@angular/http";

@Component({
    selector: 'my-app',
    template: `
<input type="file" (change)="filePicked($event)" style="width: 100%">
<button (click)="reproduceBug()">Reproduce bug</button>
`
})

export class AppComponent {
    file: File;

    constructor(private http: Http) {
    }

    reproduceBug() {
        const url = "url";

        let fileReader: FileReader = new FileReader();
        let body = new FormData();

        fileReader.addEventListener("load", $event => {
            body.append("file", fileReader.result);
            let options: RequestOptionsArgs = new RequestOptions();
            options.headers = new Headers();
            options.headers.append("Content-Type", "");

            return this.http.post(url, body, options)
                .toPromise();
        });

        // async
        fileReader.readAsBinaryString(this.file);
    }

    filePicked($event) {
        this.file = $event.target.files[0];
    }
}
```

http-interceptor.ts
```typescript
import {ConnectionBackend, Http, Request, RequestOptionsArgs, Response, RequestOptions, Headers} from "@angular/http";
import {Injectable} from "@angular/core";

import "./rxjs-extensions";
import {Observable} from "rxjs/Observable";

/**
 * Sets RequestOptions
 */
@Injectable()
export class HttpInterceptor extends Http {

    constructor(backend: ConnectionBackend, defaultOptions: RequestOptions) {
        super(backend, defaultOptions);
        // defaultOptions get merged into other options that are passed into request functions
        defaultOptions.headers = new Headers();
        defaultOptions.headers.append('Content-Type', 'application/json');
    }
}
```

**What is the motivation / use case for changing the behavior?**
It should be possible to set default Content-Type header and still send multipart/form-data requests.

**Please tell us about your environment:**
Windows 7, Webstorm IDE

**Angular version:**
Angular 2.0.0

**Browser:**
Tested with Firefox 43.0.1 (NO corrupt header) and with Chrome 53.0.2785.116 m (64-bit) with disabled extensions and plugins (corrupt header).
 
**Language:**
Typescript 1.8.10

**Node (for AoT issues):** 
No AoT compilation

**Comment by vicb** [comment]
Could you please try to reproduce in a simple plunker

**Comment by Nick-Triller** [comment]
Sure, I will try to create a plunker tomorrow.

**Comment by Nick-Triller** [comment]
Plunker: https://plnkr.co/edit/vMzTZfA4FwbPpdM19OpB?p=preview

As stated before, the Bug occurs with Chrome 53.0.2785.116 m (64-bit), but not with Firefox 47.0.1. Other browsers or browser versions were not tested.

To reproduce the bug, open the chrome dev tools network tab, pick a file and click the "reproduce bug" button. Check the content-type header for the mutlipart/form-data request.

**Comment by vicb** [comment]
Your plunker doesn't run in Chrome but I guess the issue is that you use `headers.append()` instead of `headers.set`

**Comment by ljieyao** [comment]
is this issue solved? I have encountered the same issue!

**Comment by DzmitryShylovich** [comment]
@ljieyao pls provide a plunkr with repro

**Comment by Nick-Triller** [comment]
I can still reproduce the issue with the previously posted plunkr, not sure why vicb couldn't run it. More information about the reason it could not be run would be helpful. The errors in the browser console are irrelevant as they appear because I perform a POST request against a nonexistent url.

Using `headers.set()` instead of `headers.append()` makes no difference. 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/6010357/22330910/dca37e80-e3c8-11e6-839c-45689e71fb31.png)

**Comment by DzmitryShylovich** [comment]
why do you set an empty content type `options.headers.append("Content-Type", "");`?

**Comment by Nick-Triller** [comment]
A default content type header is applied automatically ('application/json' in this case). The default header is applied because I create http with defaultOptions.

Angular's http needs to generate a content type with boundary when the payload is a FormData object (multipart form). Angular won't generate the content type if the content type is already set. This is the reason I set an empty content type.

**Comment by DzmitryShylovich** [comment]
without `options.headers.append("Content-Type", "");` works as expected https://plnkr.co/edit/ViTp47ecIN9kiBw23VfL?p=preview

**Comment by ljieyao** [comment]
@DzmitryShylovich thx!!!

**Comment by darincardin** [comment]
I had the same problem! you MUST delete the content type, like this: request.headers.delete("Content-Type");

**Comment by michael-letcher** [comment]
@DzmitryShylovich How can you add to the header e.g. adding 'reportProgress: true' without breaking the content-type header?

Or is this not possible atm?
