### ISSUE TITLE
Broken link in docs - Pipe guide

### ISSUE THREAD

**Issue by jkjustjoshing** [angular/angular#11810]
I tried finding the file where this page is defined to submit a PR but I couldn't find it.

The page is https://angular.io/docs/ts/latest/guide/pipes.html

Under the "Using Pipes" section below the 1st code example is the following: 
> Inside the interpolation expression we flow the component's birthday value through the pipe operator ( | ) to the *Date pipe* function on the right. All pipes work this way.

The "Date pipe" is a link to https://angular.io/docs/ts/latest/api/common/index/DatePipe-class.html which is a broken link. It should be https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html ("pipe" not "class" at the end of the URL).

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Comment by Hongbo-Miao** [comment]
thanks for reporting, I guess need be at https://github.com/angular/angular.io/issues

**Comment by pkozlowski-opensource** [comment]
@Hongbo-Miao is right, it should be reported at https://github.com/angular/angular.io/issues
