### ISSUE TITLE
Question: Post release of 2.0 will the team still support 1.x in future?

### ISSUE THREAD

**Issue by appplumbr** [angular/angular#11817]
We are building a product in Angular 1.x we need input whether to start with 2.0 or 1.x, we do not have 2.0 expertise?

What about 1.x support and releases in future?

May be this would not be the correct forum for this question I added cos the core team can read my issue.

**Comment by pkozlowski-opensource** [comment]
Support policy for Angular 1.x was clearly detailed here:  https://www.youtube.com/watch?v=QHulaj5ZxbI&feature=youtu.be&list=PLOETEcp3DkCoNnlhE-7fovYvqwVPrRiY7&t=680
Nothing changed in this policy / plans - those still hold.

**Comment by appplumbr** [comment]
Thanks!
