### ISSUE TITLE
Add a 'routings' property to the @NgModule()'s parameter

### ISSUE THREAD

**Issue by Lcng** [angular/angular#11814]
**I'm submitting a feature request**

@NgModule can import feature modules and routing modules just like the [router guid](url) descripts:

`@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    routing,
    HeroesModule
  ]
})
export class AppModule {
}`

Then the routes defined in the imported routing module works. It is great, concerns are separated.
But something is confused. BrowserModule and FormsModule in the imports array are 'Framework modules', and HerosModule is a 'feature module'. But the routing module is about routing. Maybe routing  modules need a standalone section like:

`@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    HeroesModule
  ],
  routings:[    
    routing
  ]
})
export class AppModule {
}`

Maybe this makes conceptions more clear.

**Comment by Hongbo-Miao** [comment]
Right now everything is at same place. There are actually more type of things, it will become more complex if separate everything.

For example:

```ts
imports: [
  FormsModule,
  ReactiveFormsModule,
  UniversalModule,

  NgbModule,
  InfiniteScrollModule,
  ChartsModule,

  /**
   * store
   */
  RouterStoreModule.connectRouter(),
  StoreDevtoolsModule.instrumentStore({
    maxAge: 5,
    monitor: useLogMonitor({
      visible: false,
      position: 'right'
    })
  }),
  StoreLogMonitorModule,

  /**
   * router
   */
  RouterModule.forRoot(router),

  /**
   * effects
   */
  EffectsModule.run(AlertEffects),
  EffectsModule.run(CallEffects),
  EffectsModule.run(ChatEffects),
  EffectsModule.run(FeedbackEffects),
  EffectsModule.run(PrepareEffects),
  EffectsModule.run(RouterEffects),
  EffectsModule.run(TopUsersEffects),
  EffectsModule.run(UserEffects)
];
```

**Comment by trotyl** [comment]
@Hongbo-Miao 

Actually you could just write:

```typescript
const FOO = [AaaModule, BbbModule];
const BAR = [CccModule];

imports: [FOO, BAR]
```

There is no need for a spread operator since angular will flatten it automatically.

**Comment by vsavkin** [comment]
Since there are many meaningful ways to partition a list of imports (similarly there are many meaningful ways to partition a list of providers), Angular doesn't prescribe one. As was pointed out, you can do the partitioning more explicit by grouping imports into array.
