### ISSUE TITLE
Cannot install typings

### ISSUE THREAD

**Issue by NGeodakov** [angular/angular#11827]
I tried to follow the instructions on the page:
https://angular.io/docs/ts/latest/quickstart.html#!#create-the-project-folder
However I was advised to get four json files from GITHUB:
https://github.com/angular/quickstart 
which I did. I made sure there is no node_modules sub-directory in the Angular 2 project directory.
Then I ran the command:
npm install
I did not get the typings sub-directory in the project directory.
After that I ran the command:
npm run typings install
and got the following npm-debug.log file:
------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'typings',
1 verbose cli   'install' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose run-script [ 'pretypings', 'typings', 'posttypings' ]
5 info lifecycle angular-quickstart@1.0.0~pretypings: angular-quickstart@1.0.0
6 silly lifecycle angular-quickstart@1.0.0~pretypings: no script for pretypings, continuing
7 info lifecycle angular-quickstart@1.0.0~typings: angular-quickstart@1.0.0
8 verbose lifecycle angular-quickstart@1.0.0~typings: unsafe-perm in lifecycle true
9 verbose lifecycle angular-quickstart@1.0.0~typings: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;c:\Angular2\angular-quickstart\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Users\NGeodakov\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\nodejs\;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\NGeodakov\AppData\Roaming\npm
10 verbose lifecycle angular-quickstart@1.0.0~typings: CWD: c:\Angular2\angular-quickstart
11 silly lifecycle angular-quickstart@1.0.0~typings: Args: [ '/d /s /c', 'typings "install"' ]
12 silly lifecycle angular-quickstart@1.0.0~typings: Returned: code: 1  signal: null
13 info lifecycle angular-quickstart@1.0.0~typings: Failed to exec typings script
14 verbose stack Error: angular-quickstart@1.0.0 typings: `typings "install"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-quickstart@1.0.0
16 verbose cwd c:\Angular2\angular-quickstart
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "typings" "install"
19 error node v6.6.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error angular-quickstart@1.0.0 typings: `typings "install"`
22 error Exit status 1
23 error Failed at the angular-quickstart@1.0.0 typings script 'typings "install"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     typings "install"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Please advise.
Thank you
Nuren Geodakov

**Comment by vicb** [comment]
docs issue should be reported at https://github.com/angular/angular.io thanks
