### ISSUE TITLE
HTTP_BINDINGS in Angular2.0.0 final version

### ISSUE THREAD

**Issue by raghuSanapathi** [angular/angular#11825]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =   
Hi,
Iam working with HTTP_BINDINGS provider in my angular2rc5 project to call aspnet5 webapi controller in Visual studio2015.,
 with the release of Angular2.0.0 final version i migrated to final version.But in Final version of angular2.0.0 iam not able to get HTTP_BINDINGS, the error coming like there is no exported member for 'HTTP_BINDINGS in '@angular/http' .Because of this error iam not able to call my api in this finalversion of angular2.0.0 which is working fine with angular2rc5.Can anyone please help me to solve this issue

Thanks&Rds,
Raghu S.

**Comment by pkozlowski-opensource** [comment]
Use `HttpModule` instead of `HTTP_BINDINGS`. Also check:
* https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html
* https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html
