### ISSUE TITLE
Use of styles and styleUrls at the same time in a Component declaration

### ISSUE THREAD

**Issue by maxailloud** [angular/angular#11822]
**I'm submitting a ...**

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

Here is the code I have for a component:

``` javascript
@Component({
    selector: 'myComponent',
    templateUrl: 'mycomponent.component.html',
    styles: [`
        chart {
            display: block;
        }
    `],
    styleUrls: ['mycomponent.component.scss'],
})
```

And here is the Typescript error I have:

```
ERROR in [default] /Users/max/Documents/workspace/admin/src/app/spots/spots-debug-graph.component.ts:19:4 
An object literal cannot have multiple properties with the same name in strict mode.

ERROR in [default] /Users/max/Documents/workspace/admin/src/app/spots/spots-debug-graph.component.ts:19:4 
Duplicate identifier 'styles'.
```

If I remove one of the two `styles`or `styleUrls`declarations I have no error.

**Expected behavior**
There should be no error as in the typing definition of the `Component`decorator there is those two attributes.

**Reproduction of the problem**
I don't seem to be able to create a plunkr to reproduct this error.
Maybe because I'm using angular-cli to build my project, so with Webpack and not SystemJs.

**What is the motivation / use case for changing the behavior?**
I need to change the style of the chart block to make it take all the place of its parent container.

**Please tell us about your environment:**

OS X El Captain 10.11.6
angular-cli: 1.0.0-beta.15
node: 6.1.0
os: darwin x64
- **Angular version:** 2.0.0-rc.X
  Last version, Angular 2.0.0.
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
  I just checked in Chrome but I don't think this is related to the browser as I have the error in the CLI when using `ng serve`.
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  Typescript 2.0.2
- **Node (for AoT issues):** `node --version` =  6.1.0

**Comment by tbosch** [comment]
Could you create a demo project with a branch for this issue on Github? Otherwise it is hard to reproduce this...

**Comment by mitchellmorris** [comment]
I am having the same experience with Webpack(not angular-cli) too.  I think you can reproduce with this issue by using the code from the advanced animations tutorial using webpack: https://angular.io/resources/live-examples/animations/ts/plnkr.html

```
client?3961:75[default] /.../hero-list-groups.component.ts:25:4 
An object literal cannot have multiple properties with the same name in strict mode.errors @ client?3961:75sock.onmessage @ socket.js?b01c:37EventTarget.dispatchEvent @ eventtarget.js?f164:51(anonymous function) @ main.js?d142:274SockJS._transportMessage @ main.js?d142:272EventEmitter.emit @ emitter.js?586c:50WebSocketTransport.ws.onmessage @ websocket.js?cccd:35wrapFn @ zone.js?fad3:698ZoneDelegate.invokeTask @ zone.js?fad3:265Zone.runTask @ zone.js?fad3:154ZoneTask.invoke @ zone.js?fad3:335
client?3961:75[default] /.../hero-list-groups.component.ts:25:4 
Duplicate identifier 'styles'.
```

**Comment by DzmitryShylovich** [comment]
Cannot reproduce http://plnkr.co/edit/J0N954a9PP7Hq3XMNiy5?p=preview

**Comment by vicb** [comment]
Sounds like an issue with the webpack plugin, could you open an issue there ? (and link it here)

**Comment by vicb** [comment]
The error is due to https://github.com/TheLarkInn/angular2-template-loader please reopen there.

However please note that you could only provide either one with angular.

**Comment by meoblast001** [comment]
I couldn't find an issue for this in the plugin repo. Has one been opened?
