### ISSUE TITLE
How to display the currency symbol to the right in Angular 2

### ISSUE THREAD

**Issue by ekaitzht** [angular/angular#11820]
**I'm submitting a feature request**  

I have to display Euro currency like this '583 €' but with this code:

    {{price | currency:'EUR':true}}

I get '€583', is there any option in Angular 2 core to move the symbol to right? A lot of european countries they use the symbol at the right (France, Germany, Spain, Italy).

**Comment by pkozlowski-opensource** [comment]
I don't think so. The `currency` pipe is using https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat behind the scenes and I don't see an option for symbol position in there.

Probably the best way for now is to use the `number`  pipe and add symbol "by hand" (or create a custom pipe).

**Comment by woppa684** [comment]
It depends on the locale used in the number format, try these 2 examples:

```
new Intl.NumberFormat('es-ES', {style: 'currency', currency: 'EUR'}).format(123.567)
> "123,57 €"
new Intl.NumberFormat('nl-NL', {style: 'currency', currency: 'EUR'}).format(123.567)
> "€ 123,57"
```

**Comment by woppa684** [comment]
The currency pipe injects the LOCALE_ID symbol, so changing the locale should result in the desired behavior.

**Comment by pkozlowski-opensource** [comment]
Thnx @woppa684
