### ISSUE TITLE
ComponentFactoryResolver is not aware of components declared in submodule

### ISSUE THREAD

**Issue by nbuso** [angular/angular#11829]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

I have a submodule with few components declared. One of the component need to dynamically instantiate one of the other components. To do it it's using ComponentFactoryResolver, but this can only instantiate one of the route components or the root module; it's not aware of the any other component. Example code on Cmp3Component of the attached archive
[cmptests.tar.gz](https://github.com/angular/angular/files/487480/cmptests.tar.gz)

**Expected behavior**

The ComponentFactoryResolver should be able to see any component of the same module

**Reproduction of the problem**

The attached archive is a angular-cli project, launch it and navigating to route2 you will have an exception in the console

**What is the motivation / use case for changing the behavior?**

This feature is needed to dynamically instantiate components and still be able to organize them in submodules

**Please tell us about your environment:**

angular-cli, linux, ng serve

* **Angular version:** 2.0.0-rc.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

tested on Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 Typescript

* **Node (for AoT issues):** `node --version` =   
6.5.0

**Comment by pkozlowski-opensource** [comment]
You need to list those components in `entryComponents`, see http://stackoverflow.com/a/39376857/1418796

I'm going to close this one for now but if you still think there is a bug / sth missing here please provide a minimal plunker with a reproduce scenario (sorry, no one is going to download / install zip of your app, you need to provide a minimal, live reproduce scenario).

**Comment by nbuso** [comment]
Fantastic, thanks!
