### ISSUE TITLE
http: ArrayBuffer is undefined in IE 9

### ISSUE THREAD

**Issue by ldellorto** [angular/angular#11831]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
The angular/http code does not account for IE 9's lack of ArrayBuffer when using 'instanceof' on Line 37 of 'body.js' when calling .text() on the response. Simply calling instanceof on it is not good enough as it throws an undefined error. It works okay if you workaround this by using calling the '_body' property instead.

**Expected behavior**
Should be able to return the text of the response body in IE 9. Maybe just needs an existence check for ArrayBuffer.

**Reproduction of the problem**
I can't get plunker or similar sites to work in IE 9, but all you need to do to reproduce once angular 2 is running in an IE 9 environment, issue an XHR like so:
```javascript 
http.get('./data.txt').map(function(res) { 
    return res.text(); // error occurs in this function in IE 9!
}).subscribe(function(result) {
    self.resp = result;
}); 
```

**What is the motivation / use case for changing the behavior?**
To not crash the app when just trying to get the .text() of an XHR result

**Please tell us about your environment:**
IE 9 on Windows 7 x64

* **Angular version:** 2.0.0
It is an issue in the latest version (2.0.0 official)

* **Browser:**
IE 9 (no issue that I could tell on later IEs or chrome/firefox)
 
* **Language:**
All as far as I know

**Comment by nathan059** [comment]
Try adding `import 'core-js/es6/typed';` inside `polyfills.ts`

It includes the list below though it might only need `es6.typed.array-buffer`
```
require('../modules/es6.typed.array-buffer');
require('../modules/es6.typed.data-view');
require('../modules/es6.typed.int8-array');
require('../modules/es6.typed.uint8-array');
require('../modules/es6.typed.uint8-clamped-array');
require('../modules/es6.typed.int16-array');
require('../modules/es6.typed.uint16-array');
require('../modules/es6.typed.int32-array');
require('../modules/es6.typed.uint32-array');
require('../modules/es6.typed.float32-array');
require('../modules/es6.typed.float64-array');
require('../modules/es6.object.to-string');
```

After fixing this problem I also started getting and error about a missing add method.
So I added the second pollyfill and it's now working properly.
[https://github.com/eligrey/classList.js](https://github.com/eligrey/classList.js)

These appear to be 2 additional poly-fill dependencies introduces around RTM

**Comment by sumitramteke** [comment]
In latest core-js it is `import 'core-js/es/array-buffer';`
