### ISSUE TITLE
ngOnInit hook not triggered on component reload

### ISSUE THREAD

**Issue by fyamada** [angular/angular#11835]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
The first time a component implementing OnInit is loaded, the ngOnInit() function is called as expected. Subsequent navigation to the same component, without visiting a different one, don't trigger the ngOnInit() function.

**Expected behavior**
Subsequent navigation to the same component, without visiting a different one, should trigger the ngOnInit() function.

**Reproduction of the problem**
Use the final Tour of Heroes code, navigate to the HeroesComponent, place a break point in the ngOnInit function and then click the Heroes routerLink again.

**What is the motivation / use case for changing the behavior?**

Whenever the same action is triggered by the user, it is expected that the application perform all the required actions. 

Take the Gmail as an example. If I'm in the inbox folder and I click again in the inbox folder link I expect the application to fetch for new messages.

**Please tell us about your environment:**
Windows 10, Visual Studio Code, npm@3.10.8, node@v6.3.1

* **Angular version:** 2.0.0

* **Browser:** Tested only on Chrome Version 53.0.2785.116 m (64-bit)
 
* **Language:** typescript: 2.0.2

* **Node (for AoT issues):** node@v6.3.1

**Similar issue:** [https://github.com/angular/angular/issues/8012]

**Comment by vicb** [comment]
Please add a repro

**Comment by manklu** [comment]
From your description it sounds like expected behaviour.
Have a look at the [doku](https://angular.io/docs/ts/latest/guide/router.html#!#route-parameters)

**Comment by fyamada** [comment]
Hi @manklu your are right. I did a [plunker](http://plnkr.co/edit/GnWCXS?p=preview) confirming that the observable approach is working as described.

I was migrating an application from RC2 and the parameters were decoded in the traditional query string parameters notation i.e: http://domain.com/app?param1=value1&param2=value2

with current release it works only with semicolon separation i.e: http://domain.com/app;param1=value1;param2=value2

IMO it would be better to comply with the [URI Generic Syntax](https://tools.ietf.org/html/rfc3986#section-3) query string notation.

**Comment by Andrey-Pavlov** [comment]
NgOnInit triggered only once when you click on different Crisis list items. 

It is normal behaviour?

crisis-detail.component.ts
http://plnkr.co/edit/3Er9UIj32yibkYoYwqV9?p=preview
```
  ngOnInit() {
    debugger;
    this.route.data.forEach((data: { crisis: Crisis }) => {
          debugger;
      this.editName = data.crisis.name;
      this.crisis = data.crisis;
    });
```

**Comment by fyamada** [comment]
The ngOnInit is called once per component instantiation. The reason you note debugger call only when clicking in a different Crisis item is due the nature of the observable parameters approach you are using.

While [reusing](https://angular.io/docs/ts/latest/guide/router.html#!#reuse) the same component, if you click on the same item, no parameter is changed, so your neither debugger statement is called. Once you change the item the parameters change and call your debugger within the observable list. Note that the outer debugger statement will be called again only in case you visit another component and get back.
