### ISSUE TITLE
Multiple radio button groups without a way to generate an unique name messes with the view

### ISSUE THREAD

**Issue by PEsteves8** [angular/angular#11832]
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request

```

**Current behavior** 
I have a component that may create inside it several other components that may have Radio Button Groups inside them. I want the nested components to not have to receive any reference of their index in the array since they may be used in other situations. The problem is that each group seems to need an unique 'name'. By having several groups generated with the same name, the view only shows the selected circles for one (although the value bindings work well)

**Expected behavior**
I would like to be able to generate a unique random name for each radio button group inputs or some other thing that would allow each button group to be isolated from the other

**Reproduction of the problem**
Here's a plunker in which it doesn't seem possible to have unique names for each groups (without sending inside the reference of the array index which I wanted to avoid, since the radioButton component is used in another part of the app that doesn't really need any index. Apart from that reason I wanted to pass in only the relevant data to that component. The real case is a little bit more complex.

https://plnkr.co/edit/3gNOgRT9TYwJmwuebJGB?p=preview

Thanks

* **Angular version:** 2.0.0 final

* **Language:** [all | TypeScript 2 beta ]

**Comment by manklu** [comment]
To recite @vicb

>Your question sounds like a support request.
>
>Please use the issue tracker only for bugs and feature requests.
>
>Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

Nevertheless. All you need is a static variable, which you increment in the constructor and save the value in an instance variable. Use this value as group name.

**Comment by vicb** [comment]
thanks @manklu - you should do more of it so that I can have more vacations !

**Comment by manklu** [comment]
:laughing:

**Comment by PEsteves8** [comment]
Thanks. I actually didn't think it was a support request. (although I did try out gitter first with no success).
I definitely should have known better.
I guess I was just blinded by ignorance, given the straightforwardness of the solution.  xD
My apologies. Thanks again 😆

**Comment by sky-coding** [comment]
@manklu what if I didn't want a unique `name`?

Looking at [this plunker](http://plnkr.co/edit/vjfqMl?p=preview), is there any way I could use non-unique names with the radio buttons? It works for text inputs when there is a `ngModelGroup` separating the duplicates, I expected similar behavior out of the radio buttons.
