### ISSUE TITLE
Cannot navigate to sibling Route with Resolve

### ISSUE THREAD

**Issue by nosideeffects** [angular/angular#11837]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Navigating via `Router.navigate` or `[routerLink]` to a sibling route with an asynchronous resolve does not change the url or route. Resolves complete successfully, but the view does not change.

Navigating in the browser directly to either sibling route completes and transitions successfully.

**Expected behavior**

`Router.navigate` and `[routerLink]` should initiate the resolver and transition to the new view/url when the asynchronous logic completes.

**Reproduction of the problem**

```
const _routes: Routes = [
  { path: 'view1',
    component: View1Component,
    resolve: {
      widgets: View1Resolver,
    }
  },
  { path: 'view2/:param',
    component: View2Component,
    resolve: {
      widgets: View2Resolver
    },
    children: [
      { path: '' },
      { path: 'child', component: ChildComponent }
    ]
  }
];

@Injectable()
export class View1Resolver implements Resolve<any> {

  constructor(private http: Http) {
  }

  resolve(route: ActivatedRouteSnapshot): Observable<any> {
    return this.http.get(widgetUrl)
      .map((response: Response) => {
        let body = response.json();
        return body.data;
      });
  }
}

@Injectable()
export class View2Resolver implements Resolve<any> {

  constructor(private http: Http) {
  }

  resolve(route: ActivatedRouteSnapshot): Observable<any> {
    return this.http.get(widgetUrl + route.params['param'])
      .map((response: Response) => {
        let body = response.json();
        return body.data;
      });
  }
}
```

Can go directly to `view1` or `view2`, but cannot transition to `view2` from `view1` or vice versa. The resolve completes, but the route does not change. If you swap the `Observable` returns with `Promise.resolve(whatever)` or `{}`, everything works as expected.

**Please tell us about your environment:**
Mac OS X
- **Angular version:**
  2.0.0 final
- **Browser:** 
  all
- **Language:** 
  Typescript 1.8 +

**Comment by vsavkin** [comment]
Could you provide a plunkr reproducing the problem?

**Comment by nosideeffects** [comment]
I'm having issues creating a plunkr that reproduces the problem. I have narrowed it down to Observables not changing the route even after they complete. Things appear to be functioning normally plunkr.

**Comment by nosideeffects** [comment]
Okay, I figured out the issue and I am pretty sure this is a bug and not intended behavior.

If you change an auxiliary route while the main route's resolve hasn't completed yet, it simply reroutes back to the current route, effectively canceling the in-progress route.

**Comment by vsavkin** [comment]
@nosideeffects Please provide a plunkr reproducing the issue

**Comment by vsavkin** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue with a plunkr reproducing the problem.
