### ISSUE TITLE
Animation output execution should be code-gen'd

### ISSUE THREAD

**Issue by matsko** [angular/angular#11838]
When an animation completes, it will always look at the view's animation data to see if an animation output handler should be invoked. This should be code gen'd to clean up the code.

**Comment by tbosch** [comment]
Related to https://github.com/angular/angular/issues/11707

**Comment by tbosch** [comment]
I.e. remove `AnimationOutput` from `AppView` and generate code that calls `player.onDone` / `player.onStart` directly with the callback.

**Comment by tbosch** [comment]
Also check all the other animation related fields in `AppView`. We should only have one field regarding to animations that stores all the context for them, so we don't slow down all the other views that don't use animations.
