### ISSUE TITLE
quickstart project/tutorial not explained deeply enough...doesn't work

### ISSUE THREAD

**Issue by razorree** [angular/angular#11833]
I've used files from quickstart project, i've copied them to:
mypro\src\main\resources\public  (as this is place for public files)

also i've run npm install in that project (there is node_modules folder within public now - not sure if it's a good idea to store 90MB of data in a public folder....)

Where should i place tsconfig.json ? in mypro\src\main\resources\public together with other files ?
However typescript plugin from Eclipse doesn't want to pickup app\*.ts files.... (plugin works with simple typescript examples).

Quickstart tutorial lacks explanation of project structure and configuration and i guess that keeping node_modules (sources, configuration etc.) in a public folder is a bad habit.
In AngularJS1.4 it was enough to 'import' files with a < script > tag in index.html

**Comment by vicb** [comment]
docs issues should be reported on https://github.com/angular/angular.io
Thanks
