### ISSUE TITLE
Can't import module from a sibling folder.

### ISSUE THREAD

**Issue by vlodko** [angular/angular#11834]
**I'm submitting a bug report**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I have moduleA in folder C:\dev\moduleA
I have moduleB in folder C:\dev\moduleB.
tsconfig, webpack configs and etc are located in each folder (C:\dev\moduleA and C:\dev\moduleB).
I run webpack build scripts in C:\dev\moduleB

I import moduleA into moduleB like:
```
import { moduleA } from '../../../../moduleA/src/components/moduleA/moduleA.ts';
```

Webpack build runs without errors.
But I get error in the Chrome:
*compiler.umd.js?9df7:14126 
Uncaught Error: Unexpected value 'moduleA ' imported by the module 'moduleB'*

**Note**: previously I've posted similar issue regarding npm link. But it was a false one: https://github.com/angular/angular/issues/11639
This one is a root of problem.

**Expected behavior**
It should import module without errors.

**Environment:**

Windows 10, Webstorm 2016.2.3, npm, static server.

* **Angular version:** 2.0.0
 
* **Language:** TypeScript 1.8.10
 
* **Node (for AoT issues):** `node --version` =  6.5.0

**Comment by vlodko** [comment]
Everything works fine when I delete **node_modules** and **typings** folders from the sibling module's folder that I want to import.

**Comment by vicb** [comment]
Are you sure that the issue is related to Angular ? Could it be a pb with webpack ?

**Comment by vlodko** [comment]
@vicb , it could be related. I was following webpack usage guide on angular.io, so I hoped that it should work

**Comment by vicb** [comment]
So please report you issue on https://github.com/angular/angular.io/issues.

Please include versions for all used packages (ie webpack, ...)

**Comment by vlodko** [comment]
@vicb , but it's not an issue of angular web site.
