### ISSUE TITLE
Can't style content added with `ng-content` directive

### ISSUE THREAD

**Issue by chrisnicola** [angular/angular#11841]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 

Currently it appears that content inside of a content block using `<ng-content>` does not work with Angular 2's component styling. It does not receive any of the component namespace attributes the rest of the component receives but any styling meant for that content is namespaced.

So for example this template

```
<div class="my-component">
  <ng-content></ng-content>
</div>
```

With this style:

```
.my-component > * { margin-top: 10px; }
```

Will not apply the style to any of the child elements loaded by `<ng-content>`

**Expected behavior**

I would expect these styles to be applied.

**Reproduction of the problem**
http://plnkr.co/edit/MsNXmn90arPXmY4x1mD0?p=preview

**What is the motivation / use case for changing the behavior?**
That the stylesheet does not apply styles to the injected content is unexpected and I suspect will be surprising to a large number of people. I also think it is a difficult limitation to cleanly work around.

* **Angular version:** 2.0.0

* **Language:** [TypeScript 2.0.2]

**Comment by vicb** [comment]
> That the stylesheet does not apply styles to the injected content is unexpected

That's how it is supposed to work, see the shadow dom spec.

Having said that `:slotted` is not yet supported. A workaround for now is to use `/deep`, see https://github.com/angular/angular/issues/11595

**Comment by chrisnicola** [comment]
Ah thanks for the workaround.
