### ISSUE TITLE
dot routing doesn't work

### ISSUE THREAD

**Issue by gyuho** [angular/angular#11842]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

I have this simple routes

```typescript
import { Routes, RouterModule } from '@angular/router';

import { DocComponent }  from './doc/v3.1/doc.component';

const appRoutes: Routes = [
    { path: 'doc', redirectTo: '/doc/v3.1', pathMatch: 'full' },
    { path: 'doc/v3.1', component: DocComponent }
];

export const routing = RouterModule.forRoot(appRoutes);

export const routedComponents = [
    DocComponent
];
```

And when I reload with `/doc/v3.1`, I get

```
Cannot GET /doc/v3.1
```

**Expected behavior**

No error.

**Reproduction of the problem**

When I remove dot (e.g. `/doc/v31`), it works.

**What is the motivation / use case for changing the behavior?**

I just want dot routing for documents with semantic version names.

**Please tell us about your environment:**

Ubuntu 16.04

* **Angular version:** 2.0.0

* **Browser:** [Chrome 53.0.2785.89] 

 
* **Language:** [TypeScript 2.0]
 
* **Node (for AoT issues):** `node --version` =   `v6.6.0`

**Comment by ericmartinezr** [comment]
Related/dup https://github.com/angular/angular/issues/8249

**Comment by vsavkin** [comment]
Dup of https://github.com/angular/angular/issues/8249
