### ISSUE TITLE
HostBindingDecorator example throws a typescript error

### ISSUE THREAD

**Issue by amay0048** [angular/angular#11847]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I've copying and pasting [the example from directives.d.ts](https://github.com/angular/angular/blob/136621ebc9a897f560390ab3a681cee9a6c67e9b/modules/%40angular/core/src/metadata/directives.ts#L921-L932) and it throws a typescript error: [ts] Argument of type '{ selector: string; template: string; directives: typeof NgModelStatus[]; }' is not assignable to parameter of type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.

**Expected behavior**
The example should not throw a typescript error

**Reproduction of the problem**
Copy and past the example into a .ts file

**What is the motivation / use case for changing the behavior?**
The examples should work

**Please tell us about your environment:**
Visual Studio Code, OSX

* **Angular version:** 2.0.0 
 
* **Language:** [TypeScript 2.0]

**Comment by pkozlowski-opensource** [comment]
It is not clear what you mean by " it throws a typescript error". Are you saying that the compilation fails? Or that your editor highlights this syntax as invalid? What is your TS tranpilation setup? Did you configure TS properly as described in https://angular.io/docs/ts/latest/quickstart.html ? (most importantly you need to have `emitDecoratorMetadata` and `experimentalDecorators` set in your `tsconfig.json`).

**Comment by Dzenad** [comment]
Same issue - my code is set up exactly as described in the quickstart.html and when created a new component it shows TS2345 error (see the screenshot).

![image](https://cloud.githubusercontent.com/assets/7174878/18803272/2d9c0996-81b4-11e6-876b-171d9a069f03.png)

**Comment by ericmartinezr** [comment]
@Dzenad that's because your using `directives` which was removed in RC6.

**Comment by Dzenad** [comment]
Thank you... just started learning ng2 and ts :)

**Comment by vicb** [comment]
no problem, we've just merged a PR removing deprecated docs.

we are in the process of improving the docs.

**Comment by amay0048** [comment]
Great, this can be closed when the docs are updated

**Comment by govind07oct** [comment]
Hi,
I am also getting an error like this.
Please refer image and let me know.
![image](https://user-images.githubusercontent.com/11593610/32533215-66d72a92-c475-11e7-811c-de4e7260230d.png)
