### ISSUE TITLE
Docs: Form Validation reactive example component doesnt declare `active` property.

### ISSUE THREAD

**Issue by PoppinTags** [angular/angular#11840]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
In the (Form Validation)[https://angular.io/docs/ts/latest/cookbook/form-validation.html] cookbook, the reactive form component example code (*"reactive/hero-form-reactive.component.ts (#3)"*) doesn't declare the `active` class property, but does reference it on lines 28 and 29.

`active = true;` is declared in the accompanying Plunker code on line 30.

**Expected behavior**
The code displayed in the cookbook includes the `active` property, matching the Plunker.

**What is the motivation / use case for changing the behavior?**
The motivation is to have the documentation match the executed code, and be more accurate.

**Comment by vicb** [comment]
pleasere-open on the docs repo https://github.com/angular/angular.io
thanks
