### ISSUE TITLE
Drag event in FF does not fire

### ISSUE THREAD

**Issue by offnertho** [angular/angular#11849]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I have an simple component which listens on two events (drag) and (dragstart). In Chrome this works perfectly, and the events get triggerd, however in firefox only the dragstart event gets fired. 

The code: 

```
home.component.html: 
<div class="home" (drag)="sayDrag($event)" (dragstart)="sayStartDrag($event)" draggable="true">
    <h1>Hello Demo</h1>
</div>

home.component.ts:
import {Component} from "@angular/core";

@Component({
    selector: 'home',
    template: require('./home.component.html')]
})
export class HomeComponent {

    sayDrag(ev) {
        console.log('drag')
    }

    sayStartDrag(ev) {
        console.log('startDrag')
    }
}
```

**Expected behavior**
The sayDrag(ev) method should be called in FF as well. 

**Please tell us about your environment:**
Windows 7
FF 43.0.1
Chrome 53.0.2785.116

* **Angular version:** 2.0.0

**Comment by vicb** [comment]
- please add a repro
- please add a repro without angular (ie is this angular related at all ?)
