### ISSUE TITLE
Use the spread operator in template

### ISSUE THREAD

**Issue by gnujeremie** [angular/angular#11850]
**I'm submitting a ...**  (check one with "x")

```
[x] feature request
```

It would be great to be able to use the spread operator in a template : 

```
<li (click)="myOnClick([el.id, ...el.childrenIds])">Clickiclick</li>
```

**Comment by gangsthub** [comment]
[arrayProp]="[{lorem: 'lorem'}, ...otherObjects]" 🙏

**Comment by hiepxanh** [comment]
it 2021, please add this feature please....

**Comment by jessicajaniuk** [comment]
Closing this as we are using #43485 as our central issue for tracking template feature requests and functionality.
