### ISSUE TITLE
Following AoT compiler instructions breaks my application

### ISSUE THREAD

**Issue by mip1983** [angular/angular#11854]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Current behavior** 
I'm struggling to follow the AoT instructions (https://angular.io/docs/ts/latest/cookbook/aot-compiler.html), I can make it work with the example single component app, but my ever so slightly larger app (which is really just some nested modules and routing) gives me non-descript traceur errors:

e.g.  zone.js:1263 GET http://localhost:3000/traceur 404 (Not Found)scheduleTask @ zone.js:1263ZoneDelegate.scheduleTask @ zone.js:205Zone.scheduleMacroTask @ zone.js:142(anonymous function) @ zone.js:1293send @ VM382:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:467(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:192Zone.run @ zone.js:85(anonymous function) @ zone.js:451ZoneDelegate.invokeTask @ zone.js:225Zone.runTask @ zone.js:125drainMicroTaskQueue @ zone.js:357ZoneTask.invoke @ zone.js:297

I'm not getting as far as the 'tree shaking section', I'm simply trying to bootstrap the app with the pre-compiled version. I think my problems can be summarized as:

- Where the instructions say to execute a command e.g. "node_modules/.bin/ngc -p tsconfig-aot.json", this doesn't work with the windows command prompt. I've done it by navigating to the bin folder and executing the command from there with a relative path, e.g. 'ngc -p ../../tsconfig-aot.json'. Can these instructions be made more windows friendly?

- It's not clear from this guide what files need to be listed in the 'tsconfig-aot.json'? Is this just the three mentioned as an entry point into the application, or do you need to list out all ts files in the app?

- Once I've updated 'main.ts' to use 'platformBrowser().bootstrapModuleFactory(AppModuleNgFactory)', and run ngc (which produces files in the aot folder), and started up the app (npm run lite), I simply get the traceur error above. Perplexingly, even at this point if I manually change main.ts back, and try and run tsc, I'm now stuck with the traceur error until I completely back out my changes with git.

**Expected behavior**
That I can get AoT working without impenetrable errors and without getting a seemingly broken application who's code I need to completely revert.

**Reproduction of the problem**
The exception from traceur is non-descript and I have no idea what's causing this or how to reproduce. It's like the up-down roller coaster experience of learning angular1 again, just hitting an impenetrable wall.

**What is the motivation / use case for changing the behavior?**
Want to apply AoT to my app for small payload size.

**Please tell us about your environment:**
Windows 7 Enterprise, Visual Studio Code (latest)

* **Angular version:** 2.0.0

* **Browser:** All
 
* **Language:** TypeScript 2.0.2
 
* **Node (for AoT issues):** `node --version` =   6.5.0

**Comment by vicb** [comment]
please add a repro

**Comment by thelgevold** [comment]
I think the issue is that you are trying to run the application after only completing the `aot` step. In this example `ngc` is compiling to es2015 modules to support tree shaking in the rollup section. This means your browser will have to support es2015 modules if you try to run the app after only completing the ngc part. If you continue with the rollup part the es2015 imports will be collapsed leaving you with a runnable es5 application.

**Comment by pehu71** [comment]
> Where the instructions say to execute a command e.g. "node_modules/.bin/ngc -p tsconfig-aot.json", this doesn't work with the windows command prompt.

Just switch the slashes to backslashes and it's gonna work.

**Comment by mip1983** [comment]
I'll give the above suggestions a try when I can, however something has changed and the:

'npm install @angular/compiler-cli @angular/platform-server --save'

It now seems to want '2.0.1' dependencies so this step fails.

I'm not sure why the 'can be closed?' flag has been added, my issue isn't resolved and no changes have been made to the documentation to help.

I'm still not clear on this part:

"It's not clear from this guide what files need to be listed in the 'tsconfig-aot.json'? Is this just the three mentioned as an entry point into the application, or do you need to list out all ts files in the app?"

**Comment by vicb** [comment]
- You need to provide a repro, we can not help without,
- If you want the doc to be improved, the repo is https://github.com/angular/angular.io

**Comment by ziibibi** [comment]
Actually I saw this error "zone.js:205Zone.scheduleMacroTas" as I moved to final version of Angular and I think it might be connected with wrong package version of zone.js - just make sure you have version 0.6.21 installed.

**Comment by jlcjensen** [comment]
> I'm still not clear on this part:

>"It's not clear from this guide what files need to be listed in the 'tsconfig-aot.json'? Is this just the three mentioned as an entry point into the application, or do you need to list out all ts files in the app?"

Seconded, please clarify.

**Comment by thelgevold** [comment]
@jlcjensen The mentioned files are enough. No need to list additional files since the compiler will find the rest of the file by following the the trail of import statements.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
