### ISSUE TITLE
How to use a Component in itself after RC5.

### ISSUE THREAD

**Issue by harunurhan** [angular/angular#11865]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

I am using `SomeComponent` that is using itself, in another component. Both of them are in `declarations` of root `NgModule`.

from the parent component of `SomeComponent` I have this error:
```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'someProperty' since it isn't a known property of 'some-component'.
1. If 'some-component' is an Angular component and it has 'someProperty' input, then verify that it is part of this module.
2. If 'some-component' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
```

**Expected behavior**

It shouldn't throw errors

**Reproduction of the problem**

Using a component in itself.

**What is the motivation / use case for changing the behavior?**

We should be able to use a component in itself. Before `RC5`, it was possible with `forwardRef`, in `@Component` of `SomeComponent`, you could do `directives: [forwardRef(() => SomeComponent)]` . I have tried using `forwardRef(() => SomeComponent)` in `declarations` but it didn't work.

**Please tell us about your environment:**

* **Angular version:** 2.0.0

* **Browser:** all

* **Language:** TypeScript 2.0

* **Node (for AoT issues):** `node --version` =  v5.12.0

**Comment by manklu** [comment]
Could you provide a small Plunker? Currently, your description is somewhat abstract.

**Comment by vicb** [comment]
Please re-open once the plunker is ready.
