### ISSUE TITLE
node_modules/@angular/router/index has no exported member 'ROUTER_PROVIDERS' in angular 2.0.0 release 

### ISSUE THREAD

**Issue by deepikabhandari2592** [angular/angular#11862]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by deepikabhandari2592** [comment]
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
import {ROUTER_PROVIDERS } from '@angular/router';


const platform = platformBrowserDynamic();
platform.bootstrapModule(AppModule);

Error : node_modules/@angular/router/index has no exported member 'ROUTER_PROVIDERS'

**Comment by DzmitryShylovich** [comment]
ROUTER_PROVIDERS were deprecated and removed in rc6. Use `RouterModule.forRoot()` instead.

**Comment by cwebster2** [comment]
in your router setup (e.g. "app.router.ts":

import { Routes, RouterModule} from "@angular/router";
const routes: Routes = [ {path: "something", component: SomeComponent} ];
export const appRoutingProviders: any[] = [];
export const routing = RouterModule.forRoot(routes);

in your module setup:

import { routing, appRoutingProviders } from "./app.router";

and stick routing in your ngModule imports and appRoutingProviders in your ngModule providers.

This changed in rc6 when all the deprecated things were turned off.  See the current version of the quickstart to see how the basic stuff like this has changed.

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich and @cwebster2 !

@deepikabhandari2592 please direct those kind of support requests to a dedicated support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by deepikabhandari2592** [comment]
@DzmitryShylovich : Ok sure....Thank you for the quick response
