### ISSUE TITLE
Clarify route definitions

### ISSUE THREAD

**Issue by Brocco** [angular/angular#11868]
**I'm submitting a ...**  (check one with "x")

```
[x] feature request
```

**Current behavior** 
Route definitions within child/feature modules differ based upon whether they are loaded eagerly or lazily. This alone is problematic and it should not be the responsibility of an NgModule to define how it will be loaded or routed to. For example:

```
//Eager
/*root*/ { path: 'foo', redirectTo: '/foo' }
/*foo*/ { path: 'foo', component: FooComponent }

//Lazy
/*root*/ { path: 'foo', loadChildren: '[path to foo module]' }
/*foo*/ {path: '', component: FooComponent }
```

**Expected behavior**
What I would like to see if the ability to specify on a new configuration option named `module` for eager routes which would provide parity with the `loadChildren` option for lazy routes...

```
//Eager
import { FooModule } from './[somewhere]';
/*root*/ { path: 'foo', module: FooModule }
/*foo*/ { path: '', component: FooComponent }
```

Also, to improve clarity and to provide a consistent naming convention adding `loadModule` which would provide the same functionality as `loadChildren` but provide a simpler mental model for developers.

So the end goal would be to allow developers to specify routes like this:

```
//Eager
import { FooModule } from './[somewhere]';
/*root*/ { path: 'foo', module: FooModule }
/*foo*/ { path: '', component: FooComponent }

//Lazy
/*root*/ { path: 'foo', loadModule: '[path to foo module]' }
/*foo*/ {path: '', component: FooComponent }
```

Another goal of eagerly routing to a module would be to utilize the same root injector.

**What is the motivation / use case for changing the behavior?**
Consistency with route definitions within feature modules.

Also, to clarify, I am not proposing changing any existing functionality initially, just to provide more consistent configuration options.

//CC @robwormald @vsavkin @brandonroberts

**Comment by alxhub** [comment]
I think this feature request has been answered in spirit - `loadChildren` can now resolve to an NgModule without necessarily lazily loading it. This still requires the creation of the child injector, but that part is fundamental to how the router works.
