### ISSUE TITLE
No 'directive' option found for @Component annotation in angular2.0.0 release

### ISSUE THREAD

**Issue by deepikabhandari2592** [angular/angular#11861]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Description/reproduction?

**Comment by deepikabhandari2592** [comment]
import { Component } from '@angular/core';
@Component({
  selector: 'my-app',
  template: `                 
             <header>
                 <nav>
                <a  [routerLink]="Contacts">Contact</a>
                  </nav>
                   </header>
 `
              ,
           directives:
                  
   styleUrls: ["./app/css/style.css"]
})

    
export class AppComponent { 
    

}

Error : Argument of type '{selector : string ;template:string;directive:any is not applicable to the paraamter of type 'Component'

**Comment by tiagoroldao** [comment]
The directives option was deprecated in RC5 and removed in RC6. You need to use NgModule instead.

**Comment by pkozlowski-opensource** [comment]
Thnx so much @DzmitryShylovich and @tiagoroldao for helping out with the issues!
@deepikabhandari2592 please direct those kind of support requests to a dedicated support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by deepikabhandari2592** [comment]
@DzmitryShylovich @tiagoroldao : Thank you !
