### ISSUE TITLE
outlet:'name' signature is not working when path is provided.

### ISSUE THREAD

**Issue by micronyks** [angular/angular#11866]
**NOTE: I'm using Angular2.0.0.**

I have following routes.

```
{ path: '', redirectTo: 'home', pathMatch: 'full'},
{ path: 'home', component: HomeComponent},
{path: '', component: DetailComponent, outlet: 'details'}


@Component({
  selector:"my-app",
  template:`
    <h3>Normal router-outlet</h3>
         <router-outlet></router-outlet>
    <hr>
     
     <h3> named-router-outlet</h3>
        <router-outlet name='details'></router-outlet>  //<<<<======works as expected
  `
})
```
**Working DEMO:  https://plnkr.co/edit/5Cv8TewVDPNtpn56f6gS?p=preview**
<hr>
But When I change it to following paths,

```
{ path: '', redirectTo: 'home', pathMatch: 'full'},
{ path: 'home', component: HomeComponent},
{path: 'details', component: DetailComponent, outlet: 'details'} 

    <h3>Normal router-outlet</h3>
          <a routerLink="details">Detail</a>          //<<<<<<======added this here...
        <router-outlet></router-outlet>
    <hr>
    <h3> named-router-outlet</h3>
         <router-outlet name='details'></router-outlet>
```

> Cannot match any routes: 'details' ; Zone: angular ; Task: Promise.then ; Value: Error: Cannot match any routes: 'details'(…) Error: Cannot match any routes: 'details'

**DEMO with problem : https://plnkr.co/edit/Lrjff4xZULPISc5eqGxl?p=preview**

**Comment by mucer** [comment]
The correct router link would be
```javascript
<a [routerLink]="[{outlets: {details:'details'}}]">Detail</a>
```

The current router link searches for primary route "details" which does not exist.

**Comment by micronyks** [comment]
@mucer @vicb what is an alternate ? Why did you close it?

**Comment by mucer** [comment]
@micronyks alternative for what? I've cloned your plunker and added my suggested changes:
https://plnkr.co/edit/k3MPCCiiwa004oTkUHRB?p=preview
Doesn't this solve your described problem?

**Comment by micronyks** [comment]
@mucer I misunderstood your statement first so asked for an alternative but thanks for showing it practically.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
