### ISSUE TITLE
Component style cannot import css from node_modules with "@" on node module names

### ISSUE THREAD

**Issue by nklt** [angular/angular#11874]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 

```

**Current behavior** 
CSS files cannot loaded in Component Style from node_modules where module name has a "@" character.

**Expected behavior**
TSC shall compile and load the css file requested from node_module, even if the name has "@" character.

**Reproduction of the problem**
An example will be used from Telerik's Angular 2 demo page (where the bug is identified).

Their sample can be found here:
http://www.telerik.com/kendo-angular-ui/getting-started

Telerik, like many other vendors, deliver their Angular 2 components, bindings and style files through npm. It is recommended to load style files from node_modules to control versioning during development.

The Component code for loading the style will look like this:

```ts
import { Component } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { ButtonsModule } from '@progress/kendo-angular-buttons';

@Component({
    selector: 'counter',
    styles: [require('@progress/kendo-angular-buttons/dist/npm/css/main.css')], // load the button theme
    template: require('./counter.component.html')
})
```
when the path is added the TSC generates the following error.
```
ERROR in ./ClientApp/app/components/app/app.component.css
Module parse failed: C:\workspace9\Angular2Spa\ClientApp\app\components\app\app.component.css Unexpected character '@' (1:0)
```
When the @ is removed, the TSC only complains the path cannot be found.

**What is the motivation / use case for changing the behavior?**
There are a large number of Angular products based with third party vendors like Telerik, Component One, Infragistics etc and support @module path is critical to enterprise UI development.

**Please tell us about your environment:**
Windows 7, 2012 server, Visual Studio 2015 update 3, .Net Core 1.0.1.,  npm 3.10.6, IIS 8.0

* **Angular version:** 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX  ] 
we believe this affects all browsers

 
* **Language:** [ TypeScript 2.0 ]
 
* **Node (for AoT issues):** `node --version` =   4.4.3

**Comment by tbosch** [comment]
The problem in your example is this: `require('@progress/kendo-angular-buttons/dist/npm/css/main.css')`. A `require` call can only load JavaScript or JSON files, but no css files.

In Angular, you would use a relative url via `styleUrls` / `templateUrl` relative to your component class. See https://angular.io/docs/ts/latest/guide/component-styles.html
