### ISSUE TITLE
ErrorHandler documentation example seems incorrect

### ISSUE THREAD

**Issue by BrandesEric** [angular/angular#11876]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

The current docs list the following example for using the [error handler](https://angular.io/docs/ts/latest/api/core/index/ErrorHandler-class.html):
```
class MyErrorHandler implements ErrorHandler {
  call(error, stackTrace = null, reason = null) {
    // do something with the exception
  }
}
```
This is no longer valid as of Angular 2.0, as far as I can tell.   Seems like probably a minor miss in the docs.

**Expected behavior**

In order to get it to work, I believe something more like this is necessary:
```
class MyErrorHandler implements ErrorHandler {
  handleError(error: any) {
    // do something with the exception
  }
}
```

 Also, is `error` ever NOT a `WrappedError`?  It would be more beneficial for TS aware IDEs to do something like:
```

class MyErrorHandler implements ErrorHandler {
  handleError(error: WrappedError) {
    // do something with the exception
  }
}
```

**I'm happy to submit a PR for this but wasn't sure where the docs code lives.  If there's another spot I should submit this (a quick Google revealed no better options) please let me know!**

* **Angular version:** 2.0.X 

 
* **Language:** [TypeScript 2.0]
 
* **Node (for AoT issues):** `node --version` =   
NA

**Comment by vicb** [comment]
Thanks for the report.

The fix has already been merged into the master branch https://github.com/angular/angular/commit/9be895b6da3b6442b03eac7845904e86ed63c26d

Will be part of the next release.
