### ISSUE TITLE
Angular 2 multiple outlets

### ISSUE THREAD

**Issue by hahmadicorp** [angular/angular#11883]
I used angular 2 in my project. my project have 3 modules. App Module(root module), Auth Module and the Dashboard Module. I want to have 2 router-outlet's one for root and auth module and one another for dashboard module to keep the dashboard template in all pages. but my problem is when I click any of components of dashboard module the angular says that cannot match any routes error. note that all modules have lazy loading to attach to the root module. this is my app.component.ts template:

`    <a routerLink="/auth" *ngIf="!auth.isLoggedIn()">Login</a>
    <a *ngIf="auth.isLoggedIn()" (click)="logout()">Logout</a>
    <router-outlet></router-outlet>
    <router-outlet name="admin"></router-outlet>`
 
this is my app.routing.ts file:

` const appRoutes:Routes = [
    {
        path:'',
        redirectTo:'/auth',
        pathMatch:'full'
    },
    {
        path:'auth',
        loadChildren:'/dpm/app/modules/Auth/auth.module'
    },
    {
        path:'dashboard',
        loadChildren:'/dpm/app/modules/Dashboard/dashboard.module',
        canActivate:[AuthGuard]
    }
];`

and this is my dashboard.routing.ts file:

`  cnst routes:Routes = [
    {
        path:'',
        component:DashboardComponent,
        canActivate:[AuthGuard]
    },
    {
        path:'users',
        component:UsersComponent,
        canActivate:[AuthGuard],
        outlet:'admin'
    },
    {
        path:'candidates',
        component:CandidatesComponent,
        canActivate:[AuthGuard],
        outlet:'admin'
    },
    {
        path:'permissions',
        component:PermissionsComponent,
        canActivate:[AuthGuard],
        outlet:'admin'
    },
    {
        path:'holidays',
        component:HolidaysComponent,
        canActivate:[AuthGuard],
        outlet:'admin'
    }
];`

**Comment by DzmitryShylovich** [comment]
Sounds like a support question. Please direct those kind of support requests to a dedicated support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

If you think you found a bug please fill the bug form and provide reproduction.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
