### ISSUE TITLE
How to run angular 2 application on apache hosting server

### ISSUE THREAD

**Issue by nikvarma** [angular/angular#11884]
Hi Guys,

I have hosting plan and i want to host my angular 2 application on the hosting server which have apache server.

The hosting server don't have a npm install.

after below command and getting a like the strc

file strc

![image](https://cloud.githubusercontent.com/assets/3116497/18807855/7574741c-8207-11e6-82e2-a41e69d04084.png)

![image](https://cloud.githubusercontent.com/assets/3116497/18807842/af53f5dc-8206-11e6-9f79-0e55ca3cb8b7.png)

ng build --prod

and uploading to my hosting server, when i am accessing the my url

http://www.exmaple.com/ -- it's working properly
http://www.exmaple.com/home -- it's giving a error, the file is no found on the server - 404 

but the same thing working on my machine, when i am trying using a cmd
ng serve - command

**Comment by samfrach** [comment]
Hello,

I guess Apache is looking for a /home directory in your root server

By googling 10 seconds, this link solves your problem : https://github.com/mgechev/angular2-seed/wiki/Deploying-prod-build-to-Apache-2

**Comment by manklu** [comment]
To recite @vicb

>Your question sounds like a support request.
>
>Please use the issue tracker only for bugs and feature requests.
>
>Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by MrCroft** [comment]
Sorry to rock the boat, I hope this doesn't attract more questions. I'm only going to comment once :)

@nikvarma for more details/questions, use gitter or stackoverflow like @manklu mentioned above.
Now... For Apache, to redirect any request to index.html, you need a `.htaccess` file in the root.
Just create a `.htaccess` in your `dist` folder (same level as index.html), I assume that's the public root of your app, and paste this in the `.htaccess` file:

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# not rewrite css, js and images
RewriteCond %{REQUEST_URI} !\.(?:css|js|map|jpe?g|gif|png)$ [NC]
RewriteRule ^(.*)$ /index.html?path=$1 [NC,L,QSA]
```
Now, no matter what path you're requesting, Apache will always serve your `index.html` file.
Also, the Apache's mod_rewrite extension needs to be enabled for this to work. Most often, it is enabled. If not, ask your hosting provider.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by killrazor** [comment]
@MrCroft the link that @samfrach provides does it little differently. Care to expand upon the differences?

``` apache
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```

**Comment by MrCroft** [comment]
@killrazor
I don't have much experience in configuring Apache. I've just found an .htaccess file that does what I need (many years ago, and I still use it). As long as everything - except assets (images, js, css) - is routed to index.html, you should be fine. It seems that @samfrach's sample does a little more. In my case, the only requests it doesn't reroute to index.html for, are images, css and js (you wouldn't want to request style.css and be served index.html, of course). In @samfrach's sample, it makes exception for ANY existing file and path. Meaning: if the file exists, then actually serve it to the client, don't route to index.html. For example, accessing http://my-app/some/path/some-file.txt would serve the contents of that file, if it exists, otherwise it serves index.html.

**Comment by RathodGirish** [comment]
@samfrach thanks for link
I have followed steps available in this link : https://github.com/mgechev/angular-seed/wiki/Deploying-prod-build-to-Apache-2

I am still getting problem.
Will please suggest?

**Comment by Sathishchary** [comment]
I have followed above methods. but I am getting the same 404 problem for urls except 
`https://example.com/dist`. I have added the `.htaccess `file in apache2  server tomcat location (project deployed location) `opt/tomcat/webapps/dist`
**.htaccess file:**
```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```
And I have added the below code in ` /etc/apache2/sites-enabled/000-default.conf` file
```
    DocumentRoot /opt/tomcat/webapps/dist
    <Directory /opt/tomcat/webapps/dist>
         AllowOverride All
    </Directory>
```
and my Apache's mod_rewrite extension also enabled. And i have given base url path in index.html like this
`<script>document.write('<base href="' + document.location + '" />');</script>`
what i am missing in this? do i need to add anything ?

**Comment by nicholaelaw** [comment]
As of 7/10, I can upload and serve the angular tutorial app without any tweak to my apache server config. Just remember to change the `base href` to whatever path you are putting it on the web.

Eg. if your app's `index.html` is at `example.com/test/myapp`, then you should have

    <base href="/test/myapp/">

in the header of `index.html`, before the `<script ...>` lines.

**Comment by Sathishchary** [comment]
@nicholaelaw Thanks for the reply. I have tried whatever you suggested. but its still showing the same 404 error.I changed the base href as you said.
<base href="/dist/">

**Comment by ArtemiyFirsov** [comment]
@Sathishchary yes, same for me.

**Comment by polyglotinc** [comment]
As of Angular 4.3.1, I find I still have to modify the .htaccess on the target deployment folders on GoDaddy, otherwise the browser reload problem occurs if the Angular app uses routing.

When I try the simplistic approach of always serving index.html if a 404 occurs, I no longer get the proper file-missing error that ought to occur if my app attempts to load a .json file that doesn't exist.
SO, an approach like @MrCroft is needed to stop that.
NOTE: I found that I needed to replace "/index" in his last line with "./index".

**Comment by dhrupal-ample** [comment]
hello 

- i am try to deploy my angular app . i run this command **ng build** and **ng build --prod**.
- it's generate dist folder and file but when i open **index.html** file in my browse it's a **blank page** 

![ang](https://user-images.githubusercontent.com/33922590/33161854-3c7af3ae-d04c-11e7-92f1-8a723b1d636b.png)

**Comment by iBaff** [comment]
https://angular.io/guide/deployment#production-servers

@dhrupal-ample You need a webserver to run (like ng serve), just opening in Browser will always be blank page.

**Comment by phil123456** [comment]
just to mention that one must definetely use the .htaccess file when possible
way to ricky to be hacked...cant believe people suggest these kind of answers in 2017/2018

**Comment by mishoo78** [comment]
not every project is going to production @phil123456, many of us, who search the web are learning. if some tool or hack, solves a temporary problem for a learning project, so be it, happy to use it.

**Comment by iBaff** [comment]
@phil123456 could you link some article or discussion why not to use .htaccess? I couldn't find anything suitable.

**Comment by phil123456** [comment]
@iBaff indeed, hard to find relevant articles

1 https://security.stackexchange.com/questions/36641/does-disabling-htaccess-improve-security
   but apparently they say it's more a performance issue

2 we been hacked, recently, and security specialists (and our security team) disabled all htaccess, strongly suggesting us to leave vhosts configs on apache conf levels

3 personaly I rather not put .htacess files knowing that they contain permisions/rules, just asside of public directories that might be retreived one day or tempered for one reason or another...

4 then we put apache itself in a chroot , not only the ftp, but the whole web server

**Comment by iBaff** [comment]
@phil123456 thanks for your answer! Sad to hear that you have been hacked.
I agree, it is better to put the config in httpd.conf. But my small hosting only let's me change .htaccess... So in my case I cannot choose. : )

**Comment by ishan123456789** [comment]
[Click this link for a working htaccess configuration](https://stackoverflow.com/questions/50202625/not-able-to-deploy-angular-4-in-production-on-live-server/50239114#50239114). I was able to get it working after trying a lot of configurations

**Comment by gthomas2** [comment]
This .htaccess worked for me:

RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]

    RewriteRule ^(.*) index.html [NC,L]

**Comment by siwei0729** [comment]
@Sathishchary 
I found the solution as .htaccess needs to be enabled with AllowOverride. Change the file /etc/apache2/apache2.conf, edit AllowOverride from None to ALL. It works for me.

**Comment by lluz** [comment]
@gthomas2 
The angular team picked up the issue I created referencing to your comment.
It works for me also on a very common shared Apache hosting.
They offered me the opportunity to submit a pull request.
I am no expert on Apache so I am unable to describe (comment) the solution.
Are you interested in doing the pull request yourself?
