### ISSUE TITLE
Sub directives of an directive in angularJs2

### ISSUE THREAD

**Issue by malikfaizanhaider** [angular/angular#11886]
**It is possible to make sub directives of directive in angularjs 2 **

**Comment by malikfaizanhaider** [comment]
Why close?

**Comment by malikfaizanhaider** [comment]
i'm just trying to nested directives in Angular2.

**Comment by ericmartinezr** [comment]
You have to ask in the proper support channels, see here https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
