### ISSUE TITLE
Problems with IE

### ISSUE THREAD

**Issue by goriunov** [angular/angular#11880]
I have problem with all IE. It works well when i open dev tools in IE but has some bugs wen i close that dev tools (like do not update Information Arrays Http calls).  So i was trying to find solution , and i came to two different answers . First Delete all console..log(). second disable cache hen you do http call . I checked first one and it did not help so how can i disable cache in angular 2 HTTP calls. (All polyfills added for old browsers as in Official Guide)

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
