### ISSUE TITLE
Animation callbacks are run in the root zone rather than the zone angular creates.

### ISSUE THREAD

**Issue by josephperrott** [angular/angular#11881]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Animation callbacks, done and start, are called in the root zone rather than being called back with the zone created by angular.

**Expected behavior**
Animation callbacks are run inside of the zone created by angular. 

**Reproduction of the problem**
http://plnkr.co/edit/kgh5fFSWIaNr2ra9hvX0?p=preview
The zone of the callback is logged in the console.

**What is the motivation / use case for changing the behavior?**
Since the callbacks are meant to be back inside of the Angular application it seems to make sense that the callback should be run inside of NgZone.

**Please tell us about your environment:**
Not platform specific
- **Angular version:** 2.0.X 
  
  
- **Browser:** [all ] 
  
  
- **Language:** [all]
- **Node (for AoT issues):** `node --version` =

**Comment by matsko** [comment]
This is something that needs to be fixed with `zone.js`. We're working on it.

**Comment by nikoTM** [comment]
Is the same issue causing isAnimating not to update in view [here](http://plnkr.co/edit/cBpPoRTQY8QJsU2gbvXP?p=preview)?

**Comment by serhiisol** [comment]
try to use zone inside of your onDone callback:
```
constructor(private zone: NgZone) {}

..

onDone() {
  this.zone.run(() => {
    //your logic here
  });
}
```

**Comment by nikoTM** [comment]
Running changeDetector.detectChanges() works for now.
