### ISSUE TITLE
routerLinkActive - problem with child routes

### ISSUE THREAD

**Issue by Qszer94** [angular/angular#11887]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[   ] feature request
[   ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

My routing configuration:
```
const appRoutes: Routes = [
    {
        path: '',
        component: ProjectComponent
    },
    {
        path: ':id',
        component: ProjectProfileComponent,
        children: [
            {
                path: '',
                component: ProjectOverviewComponent,
                data: {
                    //allowedRoles: ["Zarząd", "Scrum Master"]
                }
            },
            {
                path: 'statistics',
                component: ProjectStatisticsComponent,
                data: {
                    //allowedRoles: ["Zarząd", "Scrum Master"]
                }
            }
        ]
    }
];
export const routing: ModuleWithProviders = RouterModule.forChild(appRoutes);
```
ProjectProfileComponent template:
```
<div class="page-header">
    <h1>Custom project</h1>
</div>
<nav id="project-menu">
    <ul>
        <li><a [routerLink]="['/dashboard/project/1']" [routerLinkActive]="['active']">Overview</a></li>
        <li><a [routerLink]="['/dashboard/project/1/statistics']" [routerLinkActive]="['active']">Stats</a></li>
    </ul>
    <router-outlet></router-outlet>
</nav>
```
When I navigate to `"/dashboard/project/1"` ProjectProfileComponent is loaded and also ProjectOverviewComponent inside ProjectProfileComponent router-outlet. In this route all is fine - my first link is activated:

```
<li><a [routerLink]="['/dashboard/project/1']" [routerLinkActive]="['active']">Overview</a></li>
```

but when i navigate to `"/dashboard/project/1/statistics"` both links are shown as active.

**Expected behavior**
When I'm in `"/dashboard/project/1/statistics"` ProjectOverviewComponent is replaced by ProjectStatisticsComponent and it shouldn't be active. I understand that url `"/dashboard/project/1"` also match to ProjectProfileComponent which is still active, but I want to check in this case only if child ProjectOverviewComponent is active.

I think that when route have children with `path: ''` only that child should be considered by routerLinkActive.

* **Angular version:** 2.0.1
* **Browser:** [all ] 
* **Language:** [TypeScript ]

**Comment by DzmitryShylovich** [comment]
`<a [routerLink]="['/dashboard/project/1']" [routerLinkActive]="['active']" [routerLinkActiveOptions]="{exact: true}">`

**Comment by Qszer94** [comment]
That's what I'm looking for. 
I missed that in api. Thanks a lot.

**Comment by suresh2018** [comment]
hi , 
Parent router working fine .but i changed the URl for child .that time active link not wokring .
How to handle this .

**Comment by keitsi** [comment]
> 
> 
> hi ,
> Parent router working fine .but i changed the URl for child .that time active link not wokring .
> How to handle this .

In my case, fix this by set the child link a full path. eg. parent link:"/dashboard" and child should be: "/dashboard/child"
