### ISSUE TITLE
Babeljs and annotations and types. 

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#1188]
I have been checking out [babeljs](https://babeljs.io/), and have been very impressed with it.  Of coarse I followed some discussions about types and annotations in babel. The main maintainer is not against adding this stuff, but as babeljs is still very much an [one-man show](https://github.com/babel/babel/graphs/contributors) by [@sebmck](https://github.com/sebmck) I suspect that he might appreciate some help with implementing this. Perhaps there are some developers over here with experience in those matters, that can lend him a hand in this?

**Comment by pkozlowski-opensource** [comment]
@SanderElias AFAIK there is collaboration going on the topic already:
https://twitter.com/bradlygreen/status/582695453424144384

Closing as it is not a real issue :-)

**Comment by SanderElias** [comment]
@pkozlowski-opensource I know its not a real issue, I just hoped to speed things up a bit.  I suspect Babel might be ready sooner then TS, and I'm kind of impatient :-)

**Comment by pkozlowski-opensource** [comment]
@SanderElias everyone is impatient :-)

**Comment by bradlygreen** [comment]
I want this to happen.  I think the TypeScript team does too.  We would happily support community folks doing this with the new user-land modules in Babel, but can't do it ourselves.  Know anyone who can start this work?

**Comment by EisenbergEffect** [comment]
Babel has experimental support for Decorators already. It's coming in v5.0.0 in the next few days.

**Comment by SanderElias** [comment]
@EisenbergEffect wow, they are quick, they must be running their systems in the [actual cloud platform](https://cloud.google.com/actual-cloud/)!

**Comment by bradlygreen** [comment]
Saw this yes!

**Comment by SanderElias** [comment]
[YES!](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&playground=false&code=%0D%0Afunction%20threeStrikes%20(req%3ARequest%7Cstring)%20%7B%0D%0A%20%20return%20this.http(req).retry(3)%3B%0D%0A%7D%0D%0A%0D%0A%40Inject(threeStrikes)%0D%0Aclass%20MyComponent%20%7B%0D%0A%20%20constructor(threeStrikes)%20%7B%0D%0A%20%20%20%20threeStrikes('http%3A%2F%2Ffoo.bar').subscribe(onNext%2C%20onError)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A)
