### ISSUE TITLE
Id selector is not working (select: '#my-id')

### ISSUE THREAD

**Issue by MrCroft** [angular/angular#11885]
**I'm submitting a:**
```
[x] bug report
```

**Current behavior** 
`select: '#my-component'` doesn't work.

**Expected behavior**
Given `<div id="my-component"></div>` in a template, `select: '#my-component'` should work the same, as the following combinations work:
`select: 'my-component'` works for `<my-component></my-component>`
`select: [my-component]` works for `<div my-component></div>`
`select: '.my-component'` works for `<div class="my-component"></div>`

**Reproduction of the problem**
https://plnkr.co/edit/rbMDTr15R51CVvWHC1V5?p=preview

* **Angular version:** 2.0.1 

* **Browser:** [ only tested in Chrome and Firefox ] 
 
* **Language:** [ TypeScript ]

**Comment by vicb** [comment]
the correct css selector is `'[id=page-overlay]'`

**Comment by MrCroft** [comment]
Thanks!
I know that writing it in that form works (because the attribute selector works). I just thought that the same we have the class selector `.my-component`, we had the `#id` selector, therefore I thought it was a bug... Specially because I think it did work a while back, beta/RC can't remember exactly. Don't know when it changed.
Anyway, so it's not a bug... This is how it is intended, the id selector was dropped. I can understand why the class selector is still kept, an element being able to have multiple classes.
