### ISSUE TITLE
Safari does not evaluate [srcset] attribute

### ISSUE THREAD

**Issue by sime** [angular/angular#11892]
**I'm submitting a ...**
```
[*] bug report
```

**Current behavior** 
When using the source element with a `[srcset]` attribute, Angular in Safari will not evaluate it, and thus the browser will default to the img `src`.

**Expected behavior**
`[srcset]` to be evaluated.

**Reproduction of the problem**
Browsers where srcset is being evaluated will see either red or black (for retina screens) Angular logo.
Safari will see the white Angular logo.
http://plnkr.co/edit/NvW7gVhf6ZeZAuM5NIlI?p=preview

**What is the motivation / use case for changing the behavior?**
Using the source to handle retina images.

* **Angular version:** 2.0.0

* **Browser:** Desktop Safari 9.1.2 and iOS Safari 9.3
 
* **Language:** TypeScript 1.8

**Comment by vicb** [comment]
Could you please add a plunker that shows that it works in Safari outside of the context of angular ?

**Comment by vicb** [comment]
Seems like the support is minimal in Safari, see https://developer.mozilla.org/en-US/docs/Web/API/HTMLSourceElement
If you can make it works outside of Angular, please re-open the issue.

**Comment by sime** [comment]
@vicb Outside of Angular repro: http://plnkr.co/edit/b4RVHEIqz1tW9XhPiwlX?p=preview

Works as expected in Safari.

Dumb question, how can I re-open ?

**Comment by vicb** [comment]
use `<source [attr.srcset]="srcset">`. It works with Safari (ie binding to the attribute, not the property)

**Comment by sime** [comment]
@vicb Thanks for you support. I need to get busy in understanding the difference between an elements attribute and propertie.

**Comment by vicb** [comment]
Google for that, you should be able to find plenty of resources.
