### ISSUE TITLE
Zone JS problem

### ISSUE THREAD

**Issue by TeodorKolev** [angular/angular#11890]
I have follow the steps from [webpack](https://angular.io/docs/ts/latest/guide/webpack.html) and I got error in Zone Js. I see others [websites ](http://valor-software.com/ng2-table/)that updated to 2.0 has same issue...

**Comment by TeodorKolev** [comment]
Nice

**Comment by manklu** [comment]
To recite the normal answer of @vicb

>Your question sounds like a support request.
>
>Please use the issue tracker only for bugs and feature requests.
>
>Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by TeodorKolev** [comment]
[This](http://valor-software.com/ng2-table/) page is not min, but it has same problem like mine. You can check at console. I do not ask for support.

**Comment by manklu** [comment]
>Failed to load resource: the server responded with a status of 404 (Not Found)
>zone.js:484Unhandled Promise rejection: **Failed to load demo/components/table-section.html**

Looks not like an Angular Problem in the first place.

**Comment by TeodorKolev** [comment]
My problem is same. It cannot load app.component.html

**Comment by vicb** [comment]
When submitting in issue please fill out the template. Our role is not to debug YOUR code. Thanks.
