### ISSUE TITLE
Subscribe to non-observable inputs inside components  

### ISSUE THREAD

**Issue by pleerock** [angular/angular#11899]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I would like to have something like this

```typescript
@Component(/* */)
export class TextComponent implements OnInit {

    @Input()
    text: string;

    @SomeDecorator()
    onTextChange = new EventEmitter();

    ngOnInit() {
        this.onTextChange.subscribe(text => {
            console.log("do something");
        });
    }
}
```

Then current model of listening to changed inputs:

```typescript
@Component(/* */)
export class PageComponent implements OnInit {

    @Input()
    text: string;

    ngOnChanges(changes: any) {
        if (changes["text"]) {
            console.log("do something");
        }
    }

}
```

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#parent-to-child-setter

Please direct those kind of support requests to a dedicated support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by pleerock** [comment]
observables can provide more opportunities. Setters also looks good, but personally I faced few problems with them, like for example, when we change some property in a process of change detection, change detection mechanizm gives an error.

**Comment by vicb** [comment]
That's something we have been thinking about.
Closing as non actionable for now.

**Comment by pleerock** [comment]
any further considerations on this issue? Its brings quite lot of problems because of inconsistency with framework philosophy when everything but this part is tight to observables.

**Comment by DzmitryShylovich** [comment]
@pleerock https://github.com/angular/angular/issues/13248
