### ISSUE TITLE
Wrong declaration at tutorial code

### ISSUE THREAD

**Issue by montassarelbehi** [angular/angular#11894]
Hello,

There is declaring array of Heroes in hero.service.ts like 
`heroes = Heroes[];`
Please replace the '=' with ':'

Thank you.

**Comment by DzmitryShylovich** [comment]
Docs repo is here https://github.com/angular/angular.io

**Comment by vicb** [comment]
@DzmitryShylovich is right. Docs issue should be reported there.

However `heroes = Heroes[]` is valid.

**Comment by montassarelbehi** [comment]
It doesn't work. So why in the live example it's made with ':' ? :)

**Comment by aluanhaddad** [comment]
@vicb It is **not** valid. 
  1. If `Heroes` is in value position value it is a syntax error as there is no key between `[` and `]`.
  2. If `Heroes` is in type position, then either the left hand side must be a type alias or it is a syntax error as `Heroes[]` is a `type` not a value.
  3. The correct forms are
    a. `heroes: Hero[];` a property which is typed as an array of `Hero` but is not initialized.
    b. `heroes: Hero[] = [];` as above except with an initial value.
    c. `heroes = [] as Hero[];` as above
    d. `heroes = <Hero[]>[]`;

`heroes = Heroes[]` is nonsense unless you are declaring a type alias for an array of instances of a terribly named type, `Heroes`.
