### ISSUE TITLE
AOT Report Error on @import of scss file

### ISSUE THREAD

**Issue by teeSee** [angular/angular#11897]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I have component.scss that has @import '../style/base/color'. 
When I am running ngc -p tsconfig.aot.json, I get an error: 
Error: Compilation failed. Resource file not found:   ..src/style/base/color

**Expected behavior**
It should handle scss @import. 

**Reproduction of the problem**
n/a

**What is the motivation / use case for changing the behavior?**
Any workaround to @import in scss?

**Please tell us about your environment:**
Mac 10.11
Angular version:  2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 Typescript: 2.0.2

* **Node (for AoT issues):** `node --version` =   
Node: 5.11.1

**Comment by vicb** [comment]
you are not supposed to compile scss files.

**Comment by aaronleeucla** [comment]
@vicb can you shed light on why not?

How should one go about creating component libraries with specific styles?

**Comment by DzmitryShylovich** [comment]
Angular doesn't know anything about sass. You need to precompile it into css.
material2/ng-bootstrap are good examples of component libs.
