### ISSUE TITLE
Uncaught TypeError 

### ISSUE THREAD

**Issue by iamkallolpratim** [angular/angular#11909]
**Cannot read property 'getContext' of undefined on ZONE JS**

this error occured whene implement a theme made using angular 1 on a existing angular 2 app. The structure of the `index.html` file given below:

`
<!DOCTYPE html>
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400italic,600,700%7COpen+Sans:300,400,400italic,600,700">

    
    <link rel="stylesheet" href="assets/theme/js/plugins/slick/slick.min.css">
    <link rel="stylesheet" href="assets/theme/js/plugins/slick/slick-theme.min.css">
    
    <link rel="stylesheet" id="css-bootstrap" href="assets/theme/css/bootstrap.min.css">
    
    <link rel="stylesheet" id="css-main" href="assets/theme/css/oneui.css">

    
    
    <script src="node_modules/core-js/client/shim.min.js"></script>

    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    
    <script src="systemjs.config.js"></script>
    <script>
        System.import('app').catch(function(err) {
            console.error(err);
        });
    </script>
</head>

<body>
    <master></master>

    
    <script src="assets/theme/js/core/jquery.min.js"></script>
    <script src="assets/theme/js/core/bootstrap.min.js"></script>
    <script src="assets/theme/js/core/jquery.slimscroll.min.js"></script>
    <script src="assets/theme/js/core/jquery.scrollLock.min.js"></script>
    <script src="assets/theme/js/core/jquery.appear.min.js"></script>
    <script src="assets/theme/js/core/jquery.countTo.min.js"></script>
    <script src="assets/theme/js/core/jquery.placeholder.min.js"></script>
    <script src="assets/theme/js/core/js.cookie.min.js"></script>
    <script src="assets/theme/js/app.js"></script>

    
    <script src="assets/theme/js/plugins/slick/slick.min.js"></script>
    <script src="assets/theme/js/plugins/chartjs/Chart.min.js"></script>

    
    <script src="assets/theme/js/pages/base_pages_dashboard.js"></script>
    <script>
        jQuery(function() {
            // Init page helpers (Slick Slider plugin)
            App.initHelpers('slick');
        });
    </script>

</body>

</html>
`

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by iamkallolpratim** [comment]
I dont get a perfect answer till now?
