### ISSUE TITLE
feature request: Distinguish between strict and non-strict mode for DomSanitizer

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#11905]
```
[x] feature request
```

**Current behavior** 

Now, `DomSanitizer` removes all HTML-unsafe attributes, **without validate them** (such as id, name...), even if they are empty value.

**Expected behavior**

Allow the developers to choose between strict and non-strict mode for DomSanitizer validations. Or, just check HTML-unsafe attributes on safety.

**Reproduction of the problem**
[See plunker](http://plnkr.co/edit/noTI3NKSBlq3W1CwrZkt?p=preview) 

Before to create this issue, I asked on stackoverflow: [Angular 2: sanitizing HTML stripped some content with div id - this is bug or feature?](http://stackoverflow.com/q/39681163/1716560).

As explained to me, this behavior is due to the [known safety rules](https://www.owasp.org/index.php/XSS_%28Cross_Site_Scripting%29_Prevention_Cheat_Sheet#XSS_Prevention_Rules_Summary):

> Strictly validate unsafe attributes such as background, id and name.

But in my example on plunker, HTML-unsafe attributes not check **any validation**. They just removed! In my example removes empty `id`:

``` html
<div id="">This is div with id attribute</div>
```

Maybe this is bug?
- **Angular version:** 2.0.0

**Comment by zoechi** [comment]
AFAIK you can provide your custom `DomSanitizer` implementation.

**Comment by KostyaTretyak** [comment]
@zoechi, you say that the problems described in this feature request is too complicated? I'm not much good to know Angular 2 to make PR to correct this problem, but I think it's not difficult to fix. Do you believe that the removal of all HTML-unsafe attributes, without validating them, it is normal practice?

**Comment by zoechi** [comment]
Actually, I don't want to say anything about that ;-)
I just want to mention that there might be ways to work around, independent of how the Angular team will proceed with this issue.

**Comment by KostyaTretyak** [comment]
@zoechi, my problem occurs when I try to implement translation from Markdown to HTML, and resul to insert into `<div [innerHTML]="body"></div>`. I do not see how I can get around this problem. If you do a prompt, I will be grateful.

**Comment by IgorMinar** [comment]
@KostyaTretyak can you explain why you want the id without a value to be preserved?

I'm having hard time understanding what you are actually asking for. Can you please explain what you mean by "not check any validation"?

**Comment by KostyaTretyak** [comment]
@IgorMinar, yes I can, - just for the clarity of the experiment. If there substitute any value, nothing will change - id will be deleted.

**Comment by t1bb4r** [comment]
I'm also a bit unsure of what is going on in this post, but I had an issue with `innerHTML` which was extremely frustrating. Basically the following html just stopped working for me after upgrading Angular:
```<div [innerHTML]="body"></div>```

With 0 errors in the console I was lost, but after finding this issue I remembered I had to sanitise my iframe url a few days ago. Long story short I found this SO post http://stackoverflow.com/questions/34467000/sanitize-input-in-angular2
and only after adding a `sanitizeHtml` pipe I was able to get the `innerHTML` working again.

My solution looked like `<div [innerHTML]="body | sanitizeHtml"></div>`

@KostyaTretyak I hope this helps, or explains the issue more clearly to the rest.

I for one like the strict sanitizer, was just surprised that the iframe gave an error and the innerHTML didn't.

**Comment by KostyaTretyak** [comment]
@t1bb4r, thank you. That `sanitizeHtml` - it's your own pipe?

I want it done through `DomSanitizer`, but without deleting attributes `id`, `name`.

**Comment by t1bb4r** [comment]
Yes I got it from the link I posted
```
@Pipe({
    name: 'sanitizeHtml'
})
class SanitizeHtml implements PipeTransform  {

   constructor(private _sanitizer: DomSanitizer){}  

   transform(v: string) : SafeHtml {
      return this._sanitizer.bypassSecurityTrustHtml(v); 
   } 
}
```
All the pipe does is trusts the html using DomSanitizer. I'm not sure what you mean by `id` and `name` fields disappearing, I've only had the issue with innerHTML. Maybe an empty string is unsafe so you need to pass that through the pipe too?

**Comment by alxhub** [comment]
Closing as this issue has been inactive for several years, and it's a bit unclear what the feature/functionality being requested is. If you have a use case that could be served by changes to `DomSanitizer` behavior, feel free to open a separate feature request.
