### ISSUE TITLE
Dynamic disabled in model-driven forms is way too complex/verbose

### ISSUE THREAD

**Issue by natcohen** [angular/angular#11900]
In model-driven forms (`formBuilder`), the only way to dynamically disable an input is to define controls outside of the main `formBuilder` and then to subscribe the control that will influence the disable:
```

let val1Control = this.formBuilder.control('', Validators.required);
let val2Control = this.formBuilder.control({value:'', disabled: !val1Control.valid});
this.form = this.formBuilder.group({
  val1: val1Control,
  val2: val2Control
})

val1Control.statusChanges.subscribe((newStatus) => {
  if (val1Control.valid) {
    val2Control.enable();
  } else {
    val2Control.disable();
  }
});
```
This solution is extremely verbose and adds an extreme complexity when `inputs` are disabled depending on each others (imagine a cascade of disabled, we would need to register each variable!)

While a much simpler way would be to add `[disabled]="this.form.controls.val1.valid"` inside the template, Angular doesn't allow to do that and throws a warning...

I understand that model-driven forms are great for testing and that this way we can test the disable. However, I think that disable is mostly used as a visual indication for the user (not like validators) and in most cases it doesn't need to be tested!

What blocks us to use `disabled` in the template?

**Comment by manklu** [comment]
>the only way to dynamically disable an input is to define controls outside of the main formBuilder

Not the only way

```javascript
this.form.controls['val1'].statusChanges.subscribe((newStatus) => {
  let val2 = this.form.controls['val2'];

  if (newStatus === VALID) {
    val2.enable();
  } else {
    val2.disable();
  }
}
```

And to recite @vicb

>Your question sounds like a support request.
>
>Please use the issue tracker only for bugs and feature requests.
>
>Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by natcohen** [comment]
@manklu I think you got my point that this is too verbose for a simple `disabled`... And when I say "the only way" it is to emphasize the fact that it is not possible to do it through the template (of course you can imagine many variants but they are all verbose and not simple)

So please be smart and try to understand the problem rather than focusing on details! (BTW your proposed solution doesn't even initialize the disable!)

In addition,it is a support request. I'm not asking for support, I'm asking for a feature (being able to use `[disabled]` inside the template)! As I don't know if it's possible (maybe ractiveforms implementation doesn't allow it for whatever reason), I've expressed a question rather than a request.

**Comment by manklu** [comment]
>And when I say "the only way" it is to emphasize the fact that it is not possible to do it through the template

Sorry, but then you should not say
>is to define controls outside of the main formBuilder

This statement is definitely false, and lead me in the wrong direction.

> I'm asking for a feature (being able to use [disabled] inside the template)!

Then you should simply fill out the template to avoid any misunderstanding.

> As I don't know if it's possible (maybe ractiveforms implementation doesn't allow it for whatever reason),

Have a look at #11271.

>  BTW your proposed solution doesn't even initialize the disable!

I thougth the rest is obvious

**Comment by natcohen** [comment]
Thanks for the reference...for the rest, I won't argue, the goal of this is not to debate but to point problems and find solutions...
