### ISSUE TITLE
Typescript Json Mapper with custom Annotations produces "Uncaught Error: Unexpected value 'AppComponent' declared by the module 'AppModule'" Error

### ISSUE THREAD

**Issue by pmig** [angular/angular#11903]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I want to include https://github.com/jf3096/json-typescript-mapper in my angular (angular-cli) project.

But i receive following error:

```
Uncaught Error: Unexpected value 'AppComponent' declared by the module 'AppModule'

(anonymous function)	@	metadata_resolver.js:278
CompileMetadataResolver.getNgModuleMetadata	@	metadata_resolver.js:265
RuntimeCompiler._compileComponents	@	runtime_compiler.js:126
RuntimeCompiler._compileModuleAndComponents	@	runtime_compiler.js:64
RuntimeCompiler.compileModuleAsync	@	runtime_compiler.js:55
PlatformRef_._bootstrapModuleWithZone	@	application_ref.js:303
PlatformRef_.bootstrapModule	@	application_ref.js:285
(anonymous function)	@	main.ts:12
__webpack_require__	@	bootstrap a22483b…:52
(anonymous function)	@	zone.js:1327
__webpack_require__	@	bootstrap a22483b…:52
webpackJsonpCallback	@	bootstrap a22483b…:23
(anonymous function)	@	main.bundle.js:1
```

Further information can be found in the package issue: https://github.com/jf3096/json-typescript-mapper/issues/2 

**Expected behavior**
It should just work like outside the angular context

**What is the motivation / use case for changing the behavior?**
package author claims angular error

**Please tell us about your environment:** linux, angular-cli
* **Angular version:** 2.0.0 
* **Browser:** [all] 
* **Language:** [TypeScript 1.8]

**Comment by manklu** [comment]
[Plunker](http://plnkr.co/)?

**Comment by vicb** [comment]
This issue tracker is about bug in Angular code but:
- your issue does not seem to be related to Angular,
- we don't know what you are trying to do.

If you really suspect an Angular bug please re-open an issue with a minimal reproduction and explain why you think this might be a bug in Angular.
