### ISSUE TITLE
Compling to ES6 and using factory provider fails

### ISSUE THREAD

**Issue by fiatkongen** [angular/angular#11901]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When injecting a service using a factory provider. This error is written to console:
Error: ReferenceError: HeroService is not defined

**Expected behavior**
The service would be created

**Reproduction of the problem**
add these lines to angular 2 gettings started:

providers:[{provide: HeroService, useFactory: () => heroServiceFactory}]

let heroServiceFactory = () => {
    return new HeroService();
};

export let heroServiceProvider =
    {
        provide: HeroService,
        useFactory: heroServiceFactory
    };

Set compile taget to ES6. When running the app a  "ReferenceError: HeroService is not defined" occurs and the application is not loaded. This ONLY happens if the compile target is set to ES6. ES5 works fine

**What is the motivation / use case for changing the behavior?**
Wanting to compile to ES6

**Please tell us about your environment:**
Windows 10
VS Code

* **Angular version:** 2.0 (final) 

* **Browser:** [Chrome] ] 
Chrome 53.0.2785.116 m (64-bit) (probably all, but have not tested)
 
* **Language:** [TypeScript 2.0.3]

**Comment by DzmitryShylovich** [comment]
`{provide: HeroService, useFactory: () => heroServiceFactory()}` or
`{provide: HeroService, useFactory: heroServiceFactory}`

Please direct those kind of support requests to a dedicated support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by manklu** [comment]
Could you provide a simple [plunker](http://plnkr.co/)? Sometimes the sequence of instructions is relevant in ES6, and currently I could only guess.

**Comment by vicb** [comment]
try https://angular.io/docs/ts/latest/api/core/index/forwardRef-function.html

--

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
