### ISSUE TITLE
How can I detect/watch “dirty-status” of an angular2-form in the right way?

### ISSUE THREAD

**Issue by webia1** [angular/angular#11912]
I could not find a solution in the official documentation, therefore I would like to ask the question here and thank you for your understanding in advance,.. 

I have a form in Angular2 (e.g)

    <form id="myLovelyForm" name="myLovelyForm" #myLovelyForm="ngForm">
        <label [attr.for]="myLovelyCheckbox">
          <input [attr.id]="myLovelyCheckbox" type="checkbox"
                 [(ngModel)]="myLovelyCheckbox">
          <span class="myLovelyCheckbox">myLovelyCheckbox</span>
        </label>
    </form>

and an animation, which should start, if the form is dirty:

    <div 
        id="myLovelyNotification" 
        class="myLovelyNotification" 
        [@notification]="myLovelyForm.form.dirty">
    .....
    .....
    </div>

The animation works properly if I set [@notification] = true, but my `myLovelyForm.form.dirty` does not fire, if I touch the form and change an element.

If the @notification is false, the animation stops, i.e. if the checkbox was selected before and I unselect it mistakenly and select it again, the form is not pristine (touched) but not dirty anymore, therefore the animation should stop. If I set the @notification = false manually, it works properly.

The big question is: How can I detect/watch "dirty-status" of an angular2-form in the right way? Could you please help me? Many thanks,..

**Comment by JiriBalcar** [comment]
@webia1 try `[@notification]="myLovelyForm.form.dirty"`

**Comment by webia1** [comment]
Thank you @JiriBalcar , I've already tried that, it does not fire the animation, I'dont know why,.. If I set a variable instead of `myLovelyForm.form.dirty` in the component manually, it works. It works also on form change, but however it does not work with `dirty`; I am using RC5.

**Comment by JiriBalcar** [comment]
@webia1 If you try to print the value of {{myLovelyForm.form.dirty}} does it changing?

**Comment by webia1** [comment]
yes

**Comment by webia1** [comment]
That's what I get, if I print `myLovelyForm.form`

`{ "validator": null, "asyncValidator": null, "_pristine": true, "_touched": false, "controls": {}, "_optionals": {}, "_valueChanges": { "_isScalar": false, "observers": [], "isUnsubscribed": false, "isStopped": false, "hasErrored": false, "dispatching": false, "hasCompleted": false, "__isAsync": false }, "_statusChanges": { "_isScalar": false, "observers": [], "isUnsubscribed": false, "isStopped": false, "hasErrored": false, "dispatching": false, "hasCompleted": false, "__isAsync": false }, "_value": {}, "_errors": null, "_status": "VALID" }`

**Comment by JiriBalcar** [comment]
@webia1 can you create plunker?

**Comment by webia1** [comment]
yes, but tomorrow I think,..

**Comment by JiriBalcar** [comment]
i will look at it tommorow after you will have plunker.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L212

**Comment by manklu** [comment]
This observable is only for changes in validity.

**Comment by kemsky** [comment]
input name attribute is missing

**Comment by gnujeremie** [comment]
@kemsky I don't think angular forms are using name attributes.

**Comment by slmyers** [comment]
If you look above the highlighted line there is a function that returns an observable value change... seems useful for detecting a dirty status in form.

**Comment by webia1** [comment]
I'm just doing a plunkr example and I'll give you the link here, please give me some more time. Tt currently looks like, as if the libraries not compatible with each other, maybe I've a version-related problem and it is not about angular.

**Comment by webia1** [comment]
I'm just doing a plunkr example and I'll give you the link here, please give me some more time. Tt currently looks like, as if the libraries not compatible with each other, maybe I've a version-related problem and it is not about angular.

**Comment by vicb** [comment]
@webia1 please open a new issue when you have the plunker available.

**Comment by webia1** [comment]
Here is the plunkr: https://plnkr.co/edit/nqS9YJwnWAFF02qAyihc?p=preview

it works with: `myLovelyForm.form._pristine`

there is no more dirty property existing,..

**Comment by vicb** [comment]
you should use `myLovelyForm.form.pristine` or `myLovelyForm.form.dirty` - `_pristine` is private (implementation might change at some point & AoT will complain while type checking)

**Comment by webia1** [comment]
I don't know why but suddenly all of them works, I've updated plunkr. Thank you!

**Comment by shahrukhhan** [comment]
first of all use "NgForm".<br>
`<form #myForm="ngForm" (ngSubmit)="onSubmit(myForm)">`<br>
Then on the "onSubmit()" function do this - <br>

    onSubmit(myForm: NgForm): void {
      let formControls = myForm.controls;
      if(formControls.firstName.dirty) {
        console.log("It's dirty");
      }
      else {
        console.log("not dirty");
      }
    } 
It will definitely work. You can print the whole "myForm" and see for yourselves what all options are available to use.
