### ISSUE TITLE
Wrong error reporting with async pipe

### ISSUE THREAD

**Issue by yfain** [angular/angular#11918]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 
It reports my custom error message, but also prints a stack trace of an exception on the console

**Expected behavior**
Just report my custom error message

**Reproduction of the problem**
Here's my code:

```
@Component({
  selector: 'http-client',
  template: `<h1>All Products</h1>
  <ul>
    <li *ngFor="let product of products | async">
       {{product.title}}
    </li>
  </ul>
  `})
class AppComponent {
  products: Observable<Array<string>>;

  constructor(private http: Http) {

   this.products = this.http.get('/products111')
        .map(res => res.json())
       .catch( err => {console.log("Can't get product details.")}) ;
  }
}
```

There is no endpoint products111 on my server, and this is what I'm getting on the browser's console:

zone.js:1241 GET http://localhost:8000/products111 404 (Not Found)scheduleTask @ zone.js:1241ZoneDelegate.scheduleTask @ zone.js:205Zone.scheduleMacroTask @ zone.js:142(anonymous function) @ zone.js:1271send @ VM832:3(anonymous function) @ http.umd.min.js:13Observable.subscribe @ Observable.ts:95Observable._subscribe @ Observable.ts:155MapOperator.call @ map.ts:54Observable.subscribe @ Observable.ts:93Observable._subscribe @ Observable.ts:155CatchOperator.call @ catch.ts:35Observable.subscribe @ Observable.ts:93ObservableStrategy.createSubscription @ common.umd.min.js:14AsyncPipe._subscribe @ common.umd.min.js:14AsyncPipe.transform @ common.umd.min.js:14_View_AppComponent0.detectChangesInternal @ AppComponent.ngfactory.js:69AppView.detectChanges @ core.umd.min.js:31DebugAppView.detectChanges @ core.umd.min.js:31AppView.detectViewChildrenChanges @ core.umd.min.js:31AppView.detectChangesInternal @ core.umd.min.js:31AppView.detectChanges @ core.umd.min.js:31DebugAppView.detectChanges @ core.umd.min.js:31ViewRef_.detectChanges @ core.umd.min.js:30(anonymous function) @ core.umd.min.js:29ApplicationRef_.tick @ core.umd.min.js:29ApplicationRef_._loadComponent @ core.umd.min.js:29ApplicationRef_.bootstrap @ core.umd.min.js:29(anonymous function) @ core.umd.min.js:29PlatformRef_._moduleDoBootstrap @ core.umd.min.js:29(anonymous function) @ core.umd.min.js:29ZoneDelegate.invoke @ zone.js:192onInvoke @ core.umd.min.js:29ZoneDelegate.invoke @ zone.js:191Zone.run @ zone.js:85(anonymous function) @ zone.js:451ZoneDelegate.invokeTask @ zone.js:225onInvokeTask @ core.umd.min.js:29ZoneDelegate.invokeTask @ zone.js:224Zone.runTask @ zone.js:125drainMicroTaskQueue @ zone.js:357ZoneTask.invoke @ zone.js:297
main-asyncpipe.ts:27 Can't get product details.
core.umd.min.js:21 EXCEPTION: Cannot read property 'Symbol(Symbol.iterator)' of undefinedErrorHandler.handleError @ core.umd.min.js:21next @ core.umd.min.js:29generatorOrNext.object.schedulerFn @ core.umd.min.js:29SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238SafeSubscriber.next @ Subscriber.ts:190Subscriber._next @ Subscriber.ts:135Subscriber.next @ Subscriber.ts:95Subject.next @ Subject.ts:61EventEmitter.emit @ core.umd.min.js:29onError @ core.umd.min.js:29onHandleError @ core.umd.min.js:29ZoneDelegate.handleError @ zone.js:196Zone.runTask @ zone.js:128ZoneTask.invoke @ zone.js:293
core.umd.min.js:21 ORIGINAL STACKTRACE:ErrorHandler.handleError @ core.umd.min.js:21next @ core.umd.min.js:29generatorOrNext.object.schedulerFn @ core.umd.min.js:29SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238SafeSubscriber.next @ Subscriber.ts:190Subscriber._next @ Subscriber.ts:135Subscriber.next @ Subscriber.ts:95Subject.next @ Subject.ts:61EventEmitter.emit @ core.umd.min.js:29onError @ core.umd.min.js:29onHandleError @ core.umd.min.js:29ZoneDelegate.handleError @ zone.js:196Zone.runTask @ zone.js:128ZoneTask.invoke @ zone.js:293
core.umd.min.js:21 TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.subscribeToResult (subscribeToResult.ts:58)
    at CatchSubscriber.error (catch.ts:66)
    at MapSubscriber.Subscriber._error (Subscriber.ts:139)
    at MapSubscriber.Subscriber.error (Subscriber.ts:109)
    at XMLHttpRequest.onLoad (http.umd.min.js:13)
    at ZoneDelegate.invokeTask (zone.js:225)
    at Object.onInvokeTask (core.umd.min.js:29)
    at ZoneDelegate.invokeTask (zone.js:224)
    at Zone.runTask (zone.js:125)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:293)ErrorHandler.handleError @ core.umd.min.js:21next @ core.umd.min.js:29generatorOrNext.object.schedulerFn @ core.umd.min.js:29SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238SafeSubscriber.next @ Subscriber.ts:190Subscriber._next @ Subscriber.ts:135Subscriber.next @ Subscriber.ts:95Subject.next @ Subject.ts:61EventEmitter.emit @ core.umd.min.js:29onError @ core.umd.min.js:29onHandleError @ core.umd.min.js:29ZoneDelegate.handleError @ zone.js:196Zone.runTask @ zone.js:128ZoneTask.invoke @ zone.js:293
Subscriber.ts:241 Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefinedsubscribeToResult @ subscribeToResult.ts:58CatchSubscriber.error @ catch.ts:66Subscriber._error @ Subscriber.ts:139Subscriber.error @ Subscriber.ts:109onLoad @ http.umd.min.js:13ZoneDelegate.invokeTask @ zone.js:225onInvokeTask @ core.umd.min.js:29ZoneDelegate.invokeTask @ zone.js:224Zone.runTask @ zone.js:125ZoneTask.invoke @ zone.js:293

* **Angular version:** 2.0.0 Final 

* **Language:** [TypeScript 2.0]

**Comment by DzmitryShylovich** [comment]
You have to return an Observable from `.catch` for example
```
.catch( err => {
    console.log("Can't get product details.");
    return Observable.empty();
})
```

**Comment by yfain** [comment]
Thanks, I tried this but getting 

Can't get product details. Error code: 404, URL: http://localhost:8000/products111 
core.umd.min.js:21 EXCEPTION: Observable_1.Observable.empty is not a function

**Comment by DzmitryShylovich** [comment]
Probably you need to import it `import 'rxjs/add/observable/empty';`

**Comment by yfain** [comment]
@DzmitryShylovich Yes, that was it. Thanks!
