### ISSUE TITLE
Is it possible to have a module to have a self-contained route config?

### ISSUE THREAD

**Issue by goldenbearkin** [angular/angular#11913]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I would like to borrow the example from angular.io https://angular.io/docs/ts/latest/guide/router.html#!#child-routing-component. The crisis-center.module is a feature module. The CrisisCenterComponent is like a shell with router-outlet defined in its template and it has its own route definition as below.

```javascript
const crisisCenterRoutes: Routes = [
  {
    path: 'crisis-center',
    component: CrisisCenterComponent,
    children: [
      {
        path: '',
        component: CrisisListComponent,
        children: [
          {
            path: ':id',
            component: CrisisDetailComponent
          },
          {
            path: '',
            component: CrisisCenterHomeComponent
          }
        ]
      }
    ]
  }
];
````
Based on the above setup, the crisis-center.module knows about the CrisisListComonent, CrisisDetailComponent and CrisisCenterHomeComponent, because all the route definations are declared in the crisis-center.routing.ts. Let say if I want to 'moduleize' CrisisListComponent to be CrisisListModule. The CrisisListModule would have its own route definations as below:

```javascript
const crisisListRoutes: Routes = [
  {
    path: 'crisis-list',
    component: CrisisListComponent,
    children: [
      {
        path: ':id',
        component: CrisisDetailComponent
      },
      {
        path: '',
        component: CrisisCenterHomeComponent
      }
    ]
  }
];
````
Is it possible to have the above route definitions automatically append to its parent path (crisis-center.routing.ts for this case) so that the parent route definition doesn't need to involve the information of its child route definition and as a result, the CrisisListModule is truly self-contained and isolated from its parent.

I would like to clarify the rationale by introducing a use case. Let say I have a AuthPageModule which is responsible for the user authentication for a web app. The AuthPageModule would have a shell component call AuthPageComponent and the AuthPageComponent has a route-outlet in its template. Because different application may have different authentication flow, it would be natural to have a 'pluggable' module like 'PhoneNumberAuthModule' or 'SocialMediaAuthModule' so that I don't need to re-config the parent routes definition files when the application evolves to support other authentication flow.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/10958#issuecomment-241171933

**Comment by goldenbearkin** [comment]
Thanks. My question did answer at #10958.
