### ISSUE TITLE
Router: Lazy loading aux-routes throws 'Cannot find primary outlet' error

### ISSUE THREAD

**Issue by douglasward** [angular/angular#11914]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When a aux-route is lazy loaded, an error is thrown saying that the primary outlet to load that component cannot be found. Whereas if the component is not lazy loaded, it works fine.

```
Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'LazyTestComponent'
```

**Expected behavior**
Lazy loading aux-routes should work exactly how non-lazy loaded aux-routes work.

**Reproduction of the problem**
I have created a plunker to reproduce the problem: 
http://plnkr.co/edit/3nVNeMmNtFinhoEAXGjJ?p=preview

Clicking on `home aux-lazy` produces the error. 

`home aux-lazy` loads the lazy-test component lazily in the aux router outlet
`home-aux` loads the test component in the aux router outlet without lazy loading.

`lazy-test component` loads the lazy-test component lazily in the main router outlet.
`test component` loads the test component in the main router outlet.

**What is the motivation / use case for changing the behavior?**
To only load modules in aux router outlets if they are needed.

* **Angular version:** 2.0.1 
* **Router version**: 3.0.1

* **Browser:** [all  ] 

 
* **Language:** [all]
 
* **Node (for AoT issues):** `node --version` =   6

**Comment by brandonroberts** [comment]
Aux router-outlets require a primary outlet. You need `<router-outlet></router-outlet>` in your `home.component.ts`

**Comment by michalstepien** [comment]
No you can't do this. Look at http://plnkr.co/edit/WwBS5HtFEiT2DSOUUyL9?p=preview 
Aux router not correct insert in template.
![image](https://cloud.githubusercontent.com/assets/5837826/18844257/dd23bae8-841c-11e6-8000-2cdd125b3540.png)

**Comment by michalstepien** [comment]
Why do you closed this? For me it is Bug. When you insert router-outlet component will be in primary outlet, not in named.

**Comment by douglasward** [comment]
Yes, why is it closed? As michalstepien pointed out, if you put in a primary router-outlet, the lazy-loaded component appears in the primary router-outlet and not in the named as stated here:
```
{
   path: 'lazy',
   outlet: 'section1',
   loadChildren: 'app/lazy-test/lazy-test.module#LazyTestModule'
}
```

And @brandonroberts, if aux router-outlets require a primary outlet, why does the test component in the named outlet work without one?

**Comment by michalstepien** [comment]
@vicb @vsavkin ?

**Comment by charliebrink** [comment]
Did you ever find a solution for this?
I'm having the same issue.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
