### ISSUE TITLE
Angular docs are not updated to demonstrate the form.reset() method.

### ISSUE THREAD

**Issue by paragpkulkarni** [angular/angular#11928]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Angular docs are not updated to demonstrate the form.reset() method. It still shows the old way using *ngIf="active" to reset the form.

**Expected behavior**
Docs should be updated to demonstrate form.reset() method instead of showing temporary workaround.

**Reproduction of the problem**
Go to angular docs and navigate to forms documentation using URL.https://angular.io/docs/ts/latest/guide/forms.html.
Use browser search functionality to locate the "Add a hero and reset the form" section. It still shows the old way using *ngIf="active to reset the form. form.reset() method is added in angular RC5/RC6. However docs are not updated to demonstrate form.reset() method to reset the form. Also docs clearly mentions that "This is a temporary workaround while we await a proper form reset feature."

**What is the motivation / use case for changing the behavior?**
Docs should be updated to show correct way to reset the form instead of temporary workaround.

**Please tell us about your environment:**
Angular 2.0 on windows

* **Angular version:** 2.0.X 

* **Browser:** [all ] 

 
* **Language:** [all | Typescript X.X | ES6/7 | ES5]
 
* **Node  =   NAa

**Comment by DzmitryShylovich** [comment]
Docs repo is here https://github.com/angular/angular.io

**Comment by paragpkulkarni** [comment]
Moving the issue to docs repo. Hence closing this one.
