### ISSUE TITLE
[http] Response url field is null in IE 9

### ISSUE THREAD

**Issue by Delagen** [angular/angular#11929]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Response.url field is null

**Expected behavior**
Response.url field is URL of request

**Reproduction of the problem**
Any request without specified X-Request-URL header

**What is the motivation / use case for changing the behavior?**
I think related
https://github.com/angular/angular/blob/979657989bab4fb93faf6a207d30760faa9bd696/modules/%40angular/http/src/http_utils.ts#L29
I know that IE 9 does not provide the way to get URL of response that worked in IE 11 for example.
But may be at least fill field with the url from request?

**Please tell us about your environment:**
Windows 10 x64
- **Angular version:** 2.0.1
- **Browser:**  IE 9
- **Language:** TypeScript 2.0.3

**Comment by vicb** [comment]
please add a repro

**Comment by Delagen** [comment]
Repro: http://plnkr.co/edit/64Ymk6RX67mljvY9aLzM?p=preview

**Comment by Delagen** [comment]
@IgorMinar reproduction already 2 weeks as provided. Any progress?

**Comment by debben** [comment]
I'm getting the exact same behavior in IE 11.  I have an http POST which may end up following redirects from the server. I need to be able to determine what url the actual response came from:

```
     this.http.post('/myUrl', body, options)
                .map(function(res: Response){
                  if (res.url &&
                      res.url.startsWith(`${location.protocol}//${location.host}/some/url`)) {
                        doSomething(res);
                      }
                 });
```

On chrome and firefox url comes in as populated but in IE variants the url field is null.

**Comment by Delagen** [comment]
@debben for a workaround you can write a wrapper on Http with RxJS to store request url and place it in response, or override HttpBackend

**Comment by DzmitryShylovich** [comment]
Was "fixed" here https://github.com/angular/angular/pull/12837
