### ISSUE TITLE
Strict equality checks for undefined values incorrectly return true in templates

### ISSUE THREAD

**Issue by garkbit** [angular/angular#11922]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Expressions testing for strict (in)equality with `undefined` evaluate incorrectly, e.g.:
```
{{ undefinedVariable === undefined }}
```
^ "false" output to DOM
```
<p *ngIf="undefinedVariable !== undefined">Should not display</p>
```
^ "Should not display" output to DOM

**Expected behavior**
Expressions testing for strict (in)equality with `undefined` evaluate correctly

**Reproduction of the problem**
http://plnkr.co/edit/SdxObL

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/11493

**Comment by vicb** [comment]
duplicate
