### ISSUE TITLE
NgModule should allow imports filtering (explicitly ignore directives etc...)

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#11935]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Hi!

I'm really happy to replace all my explicit `directives: [HelloWorldDirective, ...]` with a simple `imports: [HelloWorldModule]` but I was thinking about big companies with hundreds of developers on the same app or big apps with hundreds of dependencies.

Isn't this some kind of anti-pattern even though it's makes us code less.

With `imports`, our module is losing the control of the components/directives/filters/etc... it's importing. We leave our dependency control the available components/directives/filters/...

For me, it sounds a bit like wildcards in java/python imports:
```
import java.lang.reflect.*
```
or
```
from django import *
```

Suppose, one of our apps' dependencies exports some nasty Directive.

The only way right now is to wrap the module with a custom module that only exports the desired features.

What about adding some optional way to explicitly select the desired components/directives/filters or/and exclude undesired ones?

**Comment by vicb** [comment]
> What about adding some optional way to explicitly select the desired components/directives/filters or/and exclude undesired ones?

You have to create a module with what you need/want.
