### ISSUE TITLE
How can reinitilize component every time with same url requiest

### ISSUE THREAD

**Issue by gajeravijayb** [angular/angular#11932]
**I am using angular 2 release version In my project i put one search functionality and after search will result show me on tabs base information** 

 My issue is that like i had used some many child linked component with main which is display search result. But when i am going to search again another result then my main component is not repaint again. I want to to re init every time when my routing map with same component second time or third time
How can i achieve this behaviour in angular 2

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
