### ISSUE TITLE
ngSwitchDefault does not error if surrounded by ngIf

### ISSUE THREAD

**Issue by Fank** [angular/angular#11938]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
This issue only appears on initial view creation.
If a `ngSwitchDefault` is surrounded by a `ngIf` like:

``` html
<div [ngSwitch]="switchVar">
    <template [ngIf]="1">
        <span *ngSwitchCase="0">0</span>
        <span *ngSwitchDefault>A</span>
    </template>
</div>
```

the `ngSwitchDefault` element will not be shown.

If you remove the `ngIf` it works fine like:

``` html
<div [ngSwitch]="switchVar">
    <span *ngSwitchCase="0">0</span>
    <span *ngSwitchDefault>A</span>
</div>
```

**Expected behavior**
It should show ngSwitchDefault on view creation, if surrounded by ngif.

**Reproduction of the problem**
http://plnkr.co/edit/vy4KguXbPxnBxeMgqAWd?p=preview

**What is the motivation / use case for changing the behavior?**
Fine working framework

**Please tell us about your environment:**
- **Angular version:** 2.0.1 
- **Browser:** [all] 
  
  
- **Language:** [all]
- **Node (for AoT issues):** `node --version` =   6.6.0

**Comment by Fank** [comment]
Ok i did some research, the `ngSwitchDefault` will be visible if `ngSwitch` condition change, if `ngSwitchDefault` is surrounded by `ngIf`

**Comment by tbosch** [comment]
`ngSwitchCase` / `ngSwitchDefault` are meant to be direct children of `ngSwitch`. We should probably report an error though in this situation.

**Comment by tbosch** [comment]
Updated the bug description as well.

**Comment by pkozlowski-opensource** [comment]
This works as expected in Angular 9 running ivy: https://ng-run.com/edit/NW1zpXstjIdeba0dKmL3?open=app%2Fapp.component.ts
