### ISSUE TITLE
Angular2 animation exception

### ISSUE THREAD

**Issue by silvanaacc** [angular/angular#11933]
The animation system throws an exception, apparently when it cannot immediately find its key in the html code, that means before rendering the age with Angular2 itself. Actually, a list is created dynamically and in the item list there is the key of the animation `@fadeItem`..

**Current behavior** 
An exception occurs and the page is not loaded. The browser console reports:
**EXCEPTION: Error: Uncaught (in promise): Internal Error: couldn't find an animation entry for fadeItem**

**Expected behavior**
It should wait the end of the rendering of the page, or manage the exception without blocking the page from loading. 

**Please tell us about your environment:**
Windows7  

* **Angular version:** 2.0.X 
Ionic 2.0.0-beta.11 and Angular 2.0.0-rc.4 

* **Browser:**
Chrome

 
* **Language:**  TypeScript 1.8.10
 
* **Node (for AoT issues):** `node --version` =   v4.3.1

**Comment by Allsimon** [comment]
I used to have this error when I mistype the animation entry... For example:
```
<li *ngFor="let item of items" [@fade]="item.fade" 
```
```
@Component({
    animations: [
        trigger('fadeItem', [ 
```
Notice that `[@fade]=` should be `[@fadeItem]=`
