### ISSUE TITLE
After Angular RC5 Http Response.text() returns _body.toString() not the body as a string

### ISSUE THREAD

**Issue by ptulokas** [angular/angular#11936]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When I create e.g. new HTTP Response with new ResponseOptions({ body: 'my data as string', status: 200 }) and call response.text(), I get 'Response with status: 200 null for URL: null' instead of 'my data as string'.

**Expected behavior**
I expect to get the response body as a string. In example case 'my data as string'.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
I have created a service to transform XDomainRequest response to an Angular2 HTTP response to support IE9 CORS and it was working fine until RC5. However I can fix this now that I know what the issue is, I think the .toString() on line 60 of https://github.com/angular/angular/blob/master/modules/%40angular/http/src/body.ts should be removed.

**Please tell us about your environment:**
OS X 10.11.4, Atom

* **Angular version:**
2.0.0 RC6 - still same behaviour in current code base

* **Browser:**
all but noticed in IE9
 
* **Language:**
 Typescript 1.8.9

**Comment by vicb** [comment]
Please add a minimal repro on the latest release.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
