### ISSUE TITLE
Testing docs, testQuote is not declared

### ISSUE THREAD

**Issue by advgal** [angular/angular#11930]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
in the testing-docs:
https://angular.io/docs/ts/latest/guide/testing.html#!#component-with-async-service
in the file
app/shared/twain.component.spec.ts (setup)
the variable testQuote is not declared.

**Expected behavior**
the variable testQuote shoud be declared, e.g.
let testQuote = "this is a test quote";

**Comment by DzmitryShylovich** [comment]
Docs repo is here https://github.com/angular/angular.io
