### ISSUE TITLE
DOM doesn't change when my variables on the components

### ISSUE THREAD

**Issue by RaulGarafulic** [angular/angular#11941]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
The DOM doesn't change when a new variable changes. Let me explain better by code:

on app.component.ts

```
userState: boolean = false;
constructor (private authService: AuthService) {    
    this.authService.isAuthenticated().subscribe (      
        authStatus => this.userState = authStatus    
    );  
}

```
The auth.service.ts

```
isAuthenticated(): Observable<boolean> {
        const state = new Subject<boolean>();
        firebase.auth().onAuthStateChanged(function (user) {
            if (user) {
                console.log (user.email);
                state.next(true);
            } else {
              console.log ('No user.email');
                state.next(false);
            }
        });
        return state.asObservable();
    }
```
On app.component.html

```
<div>
  <app-header *ngIf = "userState"></app-header>
</div>

```
This should change when the user is authenticated. And if I make this change in my app.component.ts, the userState  is actually true.

```
userState: boolean = false;
constructor (private authService: AuthService) {    
    this.authService.isAuthenticated().subscribe (      
        authStatus => {
        this.userState = authStatus;
        console.log (this.userState); // THIS RETURNS TRUE
      }    
    );  
}

```
But it doesn't make the changes in the DOM.

**Expected behavior**
The DOM should change when the variable changes.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by zoechi** [comment]
Bug reports require a Plunker that allows to reproduce.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by vicb** [comment]
> Bug reports require a Plunker that allows to reproduce.

:+1:
