### ISSUE TITLE
Documentation: angular2-in-memory-web-api VS angular-in-memory-web-api

### ISSUE THREAD

**Issue by sickmartian** [angular/angular#11944]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
On the latests documentation, in the HTTP section of the tutorial (https://angular.io/docs/ts/latest/tutorial/toh-pt6.html) there are places where the import references angular-in-memory-web-api instead of angular2-in-memory-web-api
On the quickstart (https://angular.io/docs/ts/latest/quickstart.html) package.json refers to angular2-in-memory-web-api while systemjs.config.js refers to angular-in-memory-web-api

**Expected behavior**
I made the examples work using angular2-in-memory-web-api everywhere, I think that's what the docs should say.
Hope this isn't wrong because of some aliasing I didn't find or follow...

**Reproduction of the problem**
NA

**What is the motivation / use case for changing the behavior?**
People that copy&paste like me

**Please tell us about your environment:**
* **Angular version:** 2.0.X 
NA

* **Browser:** all
 
* **Language:** TypeScript
 
* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
Please re-open on the docs repo https://github.com/angular/angular.io
