### ISSUE TITLE
Creating FormControl using formstate fills value with "[object Object]"

### ISSUE THREAD

**Issue by Fank** [angular/angular#11940]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
If you create a FormControl using following `value`, will show "[object Object]" in view:
```ts
this.form = this._formBuilder.group({
  MyControl: [{ value: '' }],
});
```

But if you use `''` as `value` everything the control value is empty in view:
```ts
this.form = this._formBuilder.group({
  MyControl: [''],
});
```

**Expected behavior**
Both above listed method to set the value on creation, should set an empty string as value.

**Reproduction of the problem**
http://plnkr.co/edit/4GBpAPxqp7mlgFtht8lm?p=preview

**What is the motivation / use case for changing the behavior?**
Thats crazy, and it shouldn't do that.

* **Angular version:** 2.0.1

* **Browser:** [all] 
 
* **Language:** [all]
 
* **Node (for AoT issues):** `node --version` =   6.6.0

**Comment by kara** [comment]
@Fank When you pass in a form state, you need to include both properties, value and disabled. The check is deliberately strict about that because it's reasonable that you might have a value contains an object with a value property.   If you add the disabled info, works as expected.

http://plnkr.co/edit/UsArY2GAkCJjycH6CTU5?p=preview

**Comment by Fank** [comment]
I total agree with it, but i think its important to add such information to the docs https://angular.io/docs/ts/latest/api/forms/index/FormControl-class.html currently it only contains information about what you need to change that you can add "disabled" info.

**Comment by vicb** [comment]
@Fank would you mind opening a PR to improve the doc ?

**Comment by Fank** [comment]
@vicb sure

**Comment by kara** [comment]
@Fank Totally fair. We should have documented that better. Thanks for the PR!  Just reviewed.
