### ISSUE TITLE
APP_INITIALIZER raises "Cannot instantiate cyclic dependency! ApplicationRef_" when used with CustomHttp that is redirecting

### ISSUE THREAD

**Issue by haia212** [angular/angular#11943]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

I am using a CustomHttp provider for Http to handle API authentication error. In CustomHttp, I need to redirect the user to the login page when a 401 status error is emitted by the API. That works fine!

app.module.ts
   ```

export function loadCustomHttp(backend: XHRBackend, defaultOptions: AppRequestOptions,
  router: Router, dataHelper: DataHelperService) {
  return new CustomHttp(backend, defaultOptions, router, dataHelper);
}

@NgModule({
// some declarations, imports, ...
providers: [
// some services ...
 {
      provide: Http,
      useFactory: loadCustomHttp,
      deps: [XHRBackend, RequestOptions, Router, DataHelperService] 
    }
});
```

custom-http.ts
```
import { Injectable } from '@angular/core';
import { Http, RequestOptions, RequestOptionsArgs, ConnectionBackend, Request, Response } from '@angular/http';
import { Router } from '@angular/router';
import { Observable } from 'rxjs/Observable';

import { DataHelperService } from '../helpers/data-helper.service';
import { AuthStorage } from '../services/auth/auth-storage';

import 'rxjs/add/observable/throw';
import 'rxjs/add/observable/empty';

@Injectable()
export class CustomHttp extends Http {
  constructor(backend: ConnectionBackend, defaultOptions: RequestOptions,
    private router: Router, private dataHelper: DataHelperService) {
    super(backend, defaultOptions);
  }


  request(url: string | Request, options?: RequestOptionsArgs): Observable<Response> {
    return this.intercept(super.request(url, options));
  }

  get(url: string, options?: RequestOptionsArgs): Observable<Response> {
    return this.intercept(super.get(url, options));
  }

  post(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> {
    return this.intercept(super.post(url, body, options));
  }

  put(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> {
    return this.intercept(super.put(url, body, options));
  }

  delete(url: string, options?: RequestOptionsArgs): Observable<Response> {
    return this.intercept(super.delete(url, options));
  }



  intercept(observable: Observable<Response>): Observable<Response> {
    return observable.catch((err, source) => {
      let token = AuthStorage.getToken();

      if (err.status === 401 && token && AuthStorage.isTokenExpired()) { 
        // token has expired -> redirecting user to login
        AuthStorage.clearAll();
        this.router.navigate(['auth/login']);
      }
      return Observable.throw(err);
    });
  }
}

```

Then, I tried to use the APP_INITIALIZER opaque token to get the required settings to initialize my app.

app.module.ts

```
@NgModule({
// some declarations, imports, ...
providers: [
// some services ...
    ConfigService,
    { 
      provide: APP_INITIALIZER, 
      useFactory: (config: ConfigService) => () => config.load(), 
      deps:[ConfigService, Http],
      multi: true
    }
});
```

config.service.ts
```
import { Injectable } from '@angular/core';
import { Http, Response } from '@angular/http';
import { AppSettings } from '../../environments/app-settings';
import { Observable } from 'rxjs/Observable';

import 'rxjs/add/operator/toPromise';

@Injectable()
export class ConfigService {

  public settings:AppSettings;

  constructor(private http:Http) { }

  load() : Promise<AppSettings> {
    let url = '/settings/static_lists/';

    var observable= this.http.get(url)
            .map(res => res.json());

    observable.subscribe(config => this.settings = config);
    return observable.toPromise();
  }

}
```

This creates an error :

```
Uncaught Error: Provider parse errors:
Cannot instantiate cyclic dependency! ApplicationRef_: in NgModule AppModuleNgModuleProviderAnalyzer.parse @ provider_analyzer.js:291NgModuleCompiler.compile @ ng_module_compiler.js:54RuntimeCompiler._compileModule @ runtime_compiler.js:102RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:65RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:55PlatformRef_._bootstrapModuleWithZone @ application_ref.js:303PlatformRef_.bootstrapModule @ application_ref.js:285(anonymous function) @ main.ts:18__webpack_require__ @ bootstrap 0e2b412…:52(anonymous function) @ main.bundle.js:86665__webpack_require__ @ bootstrap 0e2b412…:52webpackJsonpCallback @ bootstrap 0e2b412…:23(anonymous function) @ main.bundle.js:1
```

If I comment out the CustomHttp provider, the error is not show and the APP_INITIALIZER works as expected.
If I comment out the redirection in custom-http.ts (and remove all remaining reference to it in app.module.ts and CustomHttp constructor), the error does not appear but the APP_INITIALIZER does not wait for the promise to be resolved before displaying the application (resulting in settings to be undefined)

**Expected behavior**
I expect no cyclic dependency error when using APP_INITIALIZER and a CustomHttp which redirect to a specific route.
I also expect the APP_INITIALIZER to wait for the promise to resolve before displaying the application even if I use a CustomHttp.

**Reproduction of the problem**

**Please tell us about your environment:**

OSX El Capitan 10.11.6
npm 3.10.3
angular-cli 1.0.0-beta.15

* **Angular version:** 2.0.X 

Angular 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
Google Chrome Version 53.0.2785.116 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 Typescript

* **Node (for AoT issues):** `node --version` =   
node 6.4.0

**Comment by vicb** [comment]
When submitting an issue, please attach a plunker (or any other repro).

You have to attach the minimal amount of code to reproduce the pb (strip all that isn't related).

**Comment by haia212** [comment]
Here is a repository representing the error discuss above : https://github.com/haia212/AngularErrorTestProject
In the last 3 commits you will find the 3 states I am talking about :
- No customHttp : no error
- No router in custom Http : no cyclic dependency error but a double call to the api setting endpoint
- customHttp with router : cyclic dependency error

Thanks for your help !

**Comment by zoechi** [comment]
@haia212 A repository link is no replacement for a Plunker.

**Comment by haia212** [comment]
https://plnkr.co/edit/Irt7PfiL18XRn9bDdRhc

Not sure the Plunkr behaves correctly because I can't find a way to make it work on my browser. If you have any questions please refer to the repository provided above. The repository contains only and exactly what is needed to reproduce the issue. I have created it ONLY for this issue purpose as it is really blocking me and my team.

**Comment by zoechi** [comment]
What do you mean by " I can't find a way to make it work on my browser".
There is a Plunker template link provided in the "new issue" template here. You can also use the "new" button in the Plunker editor to get a ready-to-run Angular2 TS template.
The Plunker needs to exactly reproduce the issue you reported with all code that is not necessary to reproduce the bug removed.

**Comment by haia212** [comment]
What it means is that, I have copied the necessary files to Plunkr (forking from the link provided in the "new issue").
I can't debug any of it because the error there are not explicit (I currently have a "(SystemJS) Error: Provider parse errors" that I can't figure out). Also, I run using angular-cli and webpack (not SystemJS as Plunker does) which might have an incidence on what's happening here.

It is really frustrating that I can't report an issue just because you want a Plunker instead of some sources files that I have already provided.
Is it possible to provide my source code to you WITHOUT Plunker as it is really a nightmare to set up for me ?

**Comment by derekshi** [comment]
@haia212 I got similar `cycle dependency` issue when working with custom ErrorHandler. do you find any solutions so far?

**Comment by zoechi** [comment]
inject `Injector` and get your dependeny using `injector.get()`

**Comment by haia212** [comment]
Yes I manage to find a solution (that I don't really understand) by removing the Router from the dependency declaration. In my app.module.ts, I now have :

`export function loadCustomHttp(backend: XHRBackend, defaultOptions: AppRequestOptions,
  router: Router, dataHelper: DataHelperService) {
  return new CustomHttp(backend, defaultOptions, router, dataHelper);
}

@NgModule({
// some declarations, imports, ...
providers: [
// some services ...
 {
      provide: Http,
      useFactory: loadCustomHttp,
      deps: [XHRBackend, RequestOptions, DataHelperService] 
    }
});`

Hope it helps :)
