### ISSUE TITLE
router-outlet does not render content, when it was directly accessed.

### ISSUE THREAD

**Issue by akirasosa** [angular/angular#11957]
**I'm submitting a bug about  router-outlet. Or it may be my mistake.**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I have some routes. For example, ```/help```.
```
  {path: 'help', component: HelpComponent},
  {path: '', component: HomeComponent},
```

When I directly access to https://xxxx/help , it does not show content for HelpComponent. But If I once go to https://xxxx/ and move to https://xxxx/help, it can be shown.

I don't use hash strategy. It looks that HelpComponent#ngOnInit is called, even when content is not shown.

**Expected behavior**

Direct access to https://xxxx/help is expected to show content.

**Reproduction of the problem**

Sorry, but plnkr is difficult to represent it. Instead, I have a site to reproduce it.
https://micropost.hana053.com/help

Code is available at https://github.com/springboot-angular2-tutorial/angular2-app .

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X 

I checked angular 2.0.0 and 2.0.1. It can be reproduced by using both of them.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X 

Chrome Version 53.0.2785.116 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.0.3
 
* **Node (for AoT issues):** `node --version` =   

v6.3.1

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
