### ISSUE TITLE
Angular 2 app With asp.net core Not working in Firefox and IE

### ISSUE THREAD

**Issue by nitinscorpion** [angular/angular#11956]
My app is working fine in chrome and Edge,but not working in Firefox and IE,

Firefox error:
Error: (SystemJS) missing = in const declaration
	@http://localhost:50135/scripts/app.module.js:13:25
	@http://localhost:50135/scripts/app.module.js:1:31
	@http://localhost:50135/scripts/app.module.js:1:2
	@http://localhost:50135/scripts/boot.js:3:22
	@http://localhost:50135/scripts/boot.js:1:31
	@http://localhost:50135/scripts/boot.js:1:2
	ZoneDelegate.prototype.invoke@http://localhost:50135/libs/zone.js/dist/zone.js:192:19
	Zone.prototype.run@http://localhost:50135/libs/zone.js/dist/zone.js:85:24
	scheduleResolveOrReject/<@http://localhost:50135/libs/zone.js/dist/zone.js:451:52
	ZoneDelegate.prototype.invokeTask@http://localhost:50135/libs/zone.js/dist/zone.js:225:23
	Zone.prototype.runTask@http://localhost:50135/libs/zone.js/dist/zone.js:125:28
	drainMicroTaskQueue@http://localhost:50135/libs/zone.js/dist/zone.js:357:25
	ZoneTask/this.invoke@http://localhost:50135/libs/zone.js/dist/zone.js:297:25
	
	Evaluating http://localhost:50135/scripts/app.component.js
	Evaluating http://localhost:50135/scripts/app.module.js
	Evaluating http://localhost:50135/scripts/boot.js
	Error loading http://localhost:50135/scripts/boot.js

**this is my tsconfig**
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitOnError": true,
    "noImplicitAny": false,
    "outDir": "../wwwroot/scripts/",
    "removeComments": false
 

  },
  "exclude": [
    "node_modules",
    "typings/index",
    "typings/index.d.ts"
  ]
}

     **this is my package.json**

{
  "version": "1.0.0",
  "name": "ngcorecontacts",
  "scripts": {
    "postinstall": "typings install",
    "typings": "typings"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.0.0-beta.12",
    "es6-shim": "0.35.1",
    "systemjs": "0.19.38",
    "zone.js": "^0.6.23",
    "jquery": "3.1.0",

    "angular2-in-memory-web-api": "0.0.20",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "typescript": "^2.0.2",
    "gulp": "3.9.1",
    "path": "0.12.7",
    "gulp-clean": "0.3.2",
    "gulp-concat": "^2.6.0",
    "gulp-typescript": "^2.13.6",
    "typings": "^1.3.1",
    "gulp-tsc": "^1.2.0"
  }
}

**this is my systemjs.config **

/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    // map tells the System loader where to look for things

    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        app: { main: 'boot.js', defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
        '@angular/core': { main: 'core.umd.min.js' },
        '@angular/common': { main: 'common.umd.min.js' },
        '@angular/compiler': { main: 'compiler.umd.min.js' },
        '@angular/platform-browser': { main: 'platform-browser.umd.min.js' },
        '@angular/platform-browser-dynamic': { main: 'platform-browser-dynamic.umd.min.js' },

    };
    var map = {
        'app': 'scripts', // 'dist',
        '@angular': 'libs/@angular',
        'angular2-in-memory-web-api': 'libs/angular2-in-memory-web-api',
        'rxjs': 'libs/rxjs'
    };
    var ngPackageNames = [
      'common',
      'compiler',
      'core',
      'forms',
      'http',
      'platform-browser',
      'platform-browser-dynamic',
      'router',
      'router-deprecated',
      'upgrade',
    ];
    // Individual files (~300 requests):
    function packIndex(pkgName) {
        packages['@angular/' + pkgName] = { main: 'index.js', defaultExtension: 'js' };
    }
    // Bundled (~40 requests):
    function packUmd(pkgName) {
        packages['@angular/' + pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
    }
    // Most environments should use UMD; some (Karma) need the individual index files
    var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
    // Add package entries for angular packages
    ngPackageNames.forEach(setPackageConfig);
    var config = {
        defaultJSExtensions: true,
        map: map,
        packages: packages
    };
    System.config(config);
})(this);
 

i tried alot to solve this issue but still not working , pls guide me to solve the same.....

**Comment by zoechi** [comment]
This sounds like a support question.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by nitinscorpion** [comment]
@zoechi  No, its not a support question , its an issue....

**Comment by zoechi** [comment]
If you think it's an issue it requires a Plunker that allows to reproduce.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
