### ISSUE TITLE
Animation callback component binding

### ISSUE THREAD

**Issue by verenion** [angular/angular#11964]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Animation callback event, not triggering changes correctly, causing any changes to not be detected. With the only exception of calling "setInterval".

**Expected behavior**
Changes to the 'this' object should be correctly interpreted and changes should be detected. setInterval should not be required to make this solution work.

**Reproduction of the problem**
I have a Plunkr of the problem here: http://plnkr.co/edit/FCdAgLgiByw1h5fD53eM?p=preview

We have a simple component, with some animations that fade the item out for 250ms. When faded out, we want to set the local variable 'remove' to false. This will use ngIf to remove the div from the DOM and any components in it. If you do a setTimeout at say, 5 seconds, and set remove to true, it will be removed. If you set remove to true inside the animation callback, the element will not be removed after the animation. Another interesting thing i noticed, if you create a 'setInterval' on ngOnInit for every 200ms - when remove gets set to true, it's as if the interval is 'refreshing' the component, and it gets removed.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows, Chrome, Angular 2.0.1.

* **Angular version:** 2.0.1 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

Chrome 53, Firefox
 
* **Language:** TypeScript
 

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
dup of #11881
