### ISSUE TITLE
Router url's get overwritten in a featuremodule

### ISSUE THREAD

**Issue by nicohabets** [angular/angular#11961]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
It's not possible to import two featuremodules as the routes of the featuremodule get overwritten.
https://plnkr.co/edit/PjtIuRT77XfhIjCJuQgk?p=preview

**Expected behavior**
In my plunkr example the expected route would be
/moduleA -> show module A
/moduleB -> show module B
ditto with lazy loaded modules.

**Reproduction of the problem**
https://plnkr.co/edit/PjtIuRT77XfhIjCJuQgk?p=preview

* **Angular version:** 2.0.X 

* **Browser:** all
 
* **Language:** all

**Comment by DzmitryShylovich** [comment]
I would say it works as expected. Both modules a and b have the same config. How do you expect router will distinguish between them?

**Comment by nicohabets** [comment]
so, what you're saying is that this isn't a valid list of routes?
/moduleA/
/moduleA/list
/moduleA/:id
/moduleB/
/moduleB/list
/moduleB/:id
So, do I then need to make 2 exactly the same feature modules, one with routes and one without?

**Comment by vsavkin** [comment]
The router takes the routes defined in all the imported modules and concats them. It doesn't prepend 'moduleA' or 'moduleB'. So the set of routes the router receives isn't what you expect, but rather:

```
/list
/:id
/
/list
/:id
```


If you change your route definitions to, it will work as expected:

```
const modulearoutes: Routes = [{
  path: 'modulea',
  component: ModuleAComponent,
  children: [
    { path: ':id', component: ModuleAComponent }
  ]
}];
```

Closing this issue.
