### ISSUE TITLE
Lazy loading without using the router

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#11967]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Currently the only way to load ng-modules "lazily" is via the router. I would like to get your thoughts on whether it would be possible to decouple lazy loading from the router and support it it via a more generic mechanism. 

Granted, I understand most people would use the router for lazy loading, but I think there are valid lazy loading use cases outside routing. 

One that comes to mind is lazy loading via permission checking. Potentially the app could be doing a runtime permission check on load and only include relevant modules matching the user's permissions.   

Not sure if this is something that has been considered, but I was thinking it could work based on an event driven model. The app could trigger events to trigger lazy loading. Perhaps the same event driven model could be used by the existing router based lazy loading as well. 

Anyway, would appreciate some feedback on the feasibility of this. 

One of the downsides to limiting lazy loading to the router is that it excludes apps where the router is not feasible. 

NgUpgrade is an example where it would be desirable to support lazy loading, but there is currently now way since the A2 router does not have a counterpart in A1.

**Comment by DzmitryShylovich** [comment]
Take a look at mechanism used inside router?

**Comment by vicb** [comment]
> One that comes to mind is lazy loading via permission checking. Potentially the app could be doing a runtime permission check on load and only include relevant modules matching the user's permissions.

Please check @vsavkin talk at Angular connect, this might answer your questions.
