### ISSUE TITLE
Route for parent component not matched if no child is mapped to primary outlet

### ISSUE THREAD

**Issue by nibbleswap** [angular/angular#11965]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

When a component contains child components it is only found by the router if one of the child components is mapped to the primary outlet. If e.g. a component contains two router outlets named "primary2" and "secondary" it results in the router failing to find the containing component (route to container called here: "nokcontainer") and throws an exception: core.umd.js:3427 EXCEPTION: Uncaught (in promise): Error: Cannot match any routes: 'nokcontainer'.

I traced the issue down to the place where the remainder of the path is matched against the child routes but did not get further. The matching for the "nokcontainer" triggers but then the code starting here attempting to match the children throws somewhere deep down the exception.
```
                var rawSlicedSegments_1 = segments.slice(lastChild);
                var childConfig$ = this.getChildConfig(injector, route);
                return rxjs_operator_mergeMap.mergeMap.call(childConfig$, function (routerConfig) {
```

**Expected behavior**

As a naive user I assume router-outlets are behaving the same whether they are primary outlets or not. I also assume as a naive user that adding children to a route should not cause the parent route not to be found anymore as such an exception is misleading.

I could not find any documentation that there must be always a primary child outlet. On the other hand I saw several examples on Stackoverflow with not accepted answers where a list of named child routes were given as suggestion that did not not include the "primary" route.

I also suspect the issue here may be the causing the issue here: https://github.com/angular/angular/issues/11208

**Reproduction of the problem**

http://plnkr.co/edit/f2pD1oQx9A6o7Tq3gAfm?p=preview

Home component: obvious
OK  container: child1 child2 in outlets named primary and secondary
NOK container: child 1 child2 in outlets named primary**2** and secondary -> exception

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OSX 10.11.6

* **Angular version:** 2.0.X 

      "from": "@angular/core@2.0.0",
      "from": "@angular/router@3.0.0",
      "from": "typescript@2.0.2",

* **Browser:** [Chrome 53.0.2785.116 (64-bit) ] 

 
* **Language:** [ TypeScript 2.0]
 
* **Node (for AoT issues):** `node --version` =   v6.4.0

**Comment by vsavkin** [comment]
The solution for this problem requires a breaking change ( https://github.com/angular/angular/issues/12133).

I improved the error message in this PR: https://github.com/angular/angular/pull/12102.

Closing this issue.
