### ISSUE TITLE
@component styles don't apply to selector itself

### ISSUE THREAD

**Issue by dicbrus** [angular/angular#11960]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 

Styles described in styles not applied to my-app selector.

```
  selector: 'my-app',
  template: '<h1>My First Angular App</h1>',
  styles: ['my-app {color:red}']
```

**Expected behavior**

Styles should be applied to it.

**Reproduction of the problem**

[http://plnkr.co/edit/bvqgGnU2ursyx0OssYjQ?p=preview](http://plnkr.co/edit/bvqgGnU2ursyx0OssYjQ?p=preview)
file 'app/app.component.ts'

**Please tell us about your environment:**

NodeJS, expressjs

* **Angular version:** 2.0.X 

* **Browser:** [ Chrome XX | Firefox XX ] 
* **Language:**  TypeScript 2.0.3

**Comment by zoechi** [comment]
Use `:host` instead of the component selector and use valid CSS ;-) (missing `;`)
```
 styles: [':host {color:red;}']
```

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by dicbrus** [comment]
Thank you, didn't see it in doc but works as it should.
