### ISSUE TITLE
Documentation: QUICKSTART Javascript / decorators not explained

### ISSUE THREAD

**Issue by lord-saumagen** [angular/angular#11969]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
On the "Qickstart Javascript" page at: 
[QUICKSTART Javascript](https://angular.io/docs/ts/latest/guide/style-guide.html)   
Appendix: NgModule

![ngmoduledecorator](https://cloud.githubusercontent.com/assets/9468599/18935222/f3f9a408-85de-11e6-8c72-53d96de04698.png)

You mention a NgModule decorator but there is no decorator used in the plain javascript examples.
So I guess the part is either a classical copy and past error, (copied from another example which uses decorators) or you forgot to explain what's the meaning of a "decorator" in this context.

**Expected behavior**
Should at least explain what a decorator is an how a decorator is used in the specified context.

**Reproduction of the problem**
See at: [QUICKSTART Javascript](https://angular.io/docs/ts/latest/guide/style-guide.html)   
Appendix: NgModule

Kind regards, Lord Saumagen

**Comment by DzmitryShylovich** [comment]
Please reopen in the docs repo https://github.com/angular/angular.io
Thx.

**Comment by vicb** [comment]
Thanks !
