### ISSUE TITLE
Support for a composite SPA?

### ISSUE THREAD

**Issue by lnaie** [angular/angular#11962]
Hi,
I was wondering if there's support to load the components via the RouterModule from a different host, so load them dynamically but not from the same host.
If not, how hard would be to achieve that? Some recommendations where to start from would be greatly appreciated.

Thanks

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
