### ISSUE TITLE
Tutorial issue

### ISSUE THREAD

**Issue by govorov** [angular/angular#11971]
Hi.
I got a error while going through official tutorial (https://angular.io/docs/ts/latest/tutorial/toh-pt5.html)
Paragraph "Move content out of the component file", where refactoring for `HeroDetailComponent` is described.
Tutorial says:
"Set the `moduleId` property to `module.id` so that `templateUrl` and `styleUrls` are relative to the component."
When I add `moduleId: module.Id` to component file, I receive a error "uri.match is not a function".
Exception thrown from this method:
```
	  /**
	   * Splits a URI into its component parts.
	   *
	   * Each component can be accessed via the component indices; for example:
	   * <pre>
	   * goog.uri.utils.split(someStr)[goog.uri.utils.CompontentIndex.QUERY_DATA];
	   * </pre>
	   *
	   * @param uri The URI string to examine.
	   * @return Each component still URI-encoded.
	   *     Each component that is present will contain the encoded value, whereas
	   *     components that are not present will be undefined or empty, depending
	   *     on the browser's regular expression implementation.  Never null, since
	   *     arbitrary strings may still look like path names.
	   */
	  function _split(uri) {
	      return uri.match(_splitRe);
	  }
```

Error thrown because module.Id is a number, hence there is no `match` method.

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/10626 and https://github.com/angular/angular/issues/11590, if the tutorial must be improved it should be opened here https://github.com/angular/angular.io

**Comment by govorov** [comment]
Thanks!
