### ISSUE TITLE
Unable to use pipes and directives in multiple modules.

### ISSUE THREAD

**Issue by unbeatableDeepak** [angular/angular#11973]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I have created a pipe for search filter and i want to use it in all of my modules. When i add it to the declarations array of app.module.ts, it is not accessible to the component which is in another module for example: hero.module.ts. Same issue occurs with the directives.

**Expected behavior**
As per the documentation of pipes and directives, if we import the pipe or directive inside the 
app.module.ts it'll work globally.

**What is the motivation / use case for changing the behavior?**
Since I want to use the "search filter" pipe everywhere in the application, so why should I repeat the code for every module. Right now I'm using it with repeating the code with different file names.

**Comment by zoechi** [comment]
Not sure what you mean with "repeat the code". All you have to do is add the module that contains the pipes and directives to `imports: [...]` of the module where you want to use them.

**Comment by robwormald** [comment]
```ts
//my-pipes.ts
@NgModule({
  declarations: [ MyPipe ],
  exports: [ MyPipe ]
})
export class MyPipesModule {}
```
```ts
//some-module.ts
@NgModule({
  imports: [ MyPipesModule ]
})
```
```ts
//some-other-module.ts
@NgModule({
  imports: [ MyPipesModule ]
})
```

Importing a module does not make it available "globally" - it only makes the *exported* items from that module available *inside* of the containing module.
