### ISSUE TITLE
Expanding directives without asterisk

### ISSUE THREAD

**Issue by kemsky** [angular/angular#11979]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior** 

**Expected behavior**

From docs:
The * is a bit of syntactic sugar that makes it easier to read and write directives that modify HTML layout with the help of templates. NgFor, NgIf, and NgSwitch all add and remove element subtrees that are wrapped in <template> tags.

**What is the motivation / use case for changing the behavior?**
This syntax does not allow to create autoexpanded directive like:
`<expanded></expanded>`
We must write:
`<expanded *expanded></expanded>`

It would be nice to specify this behavior directly at directive declaration:
```
@Directive({
selector: 'expanded',
expand: true
})

<expanded></expanded>
```

**Comment by vicb** [comment]
We have preferred to be explicit while design A2.
