### ISSUE TITLE
looks like a bug with Typescript + Angular2.0.0 + DI

### ISSUE THREAD

**Issue by squarewave24** [angular/angular#11970]
I posted this issue because I could not get dependency injection to work even though I did it by following every example from Angular Tutorials and Tour Of Heros. 

http://stackoverflow.com/questions/39693137/angular2-final-no-provider-for-connectionbackend?noredirect=1#comment66789394_39693137

"No provider for ConnectionBackend”

in the end after days of trial and error I got it to work by adding this property in tsconfig.json: 

    "emitDecoratorMetadata": true,

without that the DI error comes back. 

plunker here: http://plnkr.co/edit/MdMNuSVmcVqvo0Zyu4Ca?p=preview
just change the property to false to see the injection stop working 

Is it a bug or working as expected? if expected i'd love to learn more about why it is happening, because i wasted days finding it and it still seems random. can't really afford that kind of time

**Comment by vicb** [comment]
> `"emitDecoratorMetadata": true,` 

tells Typescript to turn decorators (`@...`) into actual JS code. Setting it to false has the same effect has removing all decorators.

Hope this make sense.

You should check the docs on angular.io, it contains a lot of helpful resources.

**Comment by squarewave24** [comment]
There is no mention of this under Tutorials/Services which is what I read after not begin able to fix this. 
https://angular.io/docs/ts/latest/tutorial/toh-pt4.html

seems like for such a random required property this should be emphasized for new users. Quick start did not have this property initially which is why I didn't have it after upgrading from RC to final.

**Comment by vicb** [comment]
That's step1 of the quickstart.

If you have idea on how to improve the docs, please talk to the docs at angular/angular.io. 
They love hearing feedback on how to improve the docs.

**Comment by squarewave24** [comment]
thanks. yeah it is now, but since i created mine earlier it didn't have that property.. not sure why it would be off by default :( 

i'll keep them posted on my findings thanks again
