### ISSUE TITLE
Allow to use custom tag name instead of template

### ISSUE THREAD

**Issue by kemsky** [angular/angular#11981]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior** 
```
<template [ngIf]="condition"><div>...</div></template>
```
It renders `<div>...</div>`

`ngIf` is used just for example.

**Expected behavior**

```
<ngIf [condition]="condition"><div>...</div></ngIf>
```
It renders `<div>...</div>`

This can specified at Directive decorator.

**Comment by woppa684** [comment]
So, you mean, something like
```
<div *ngIf="condition">...</div>
```
?

**Comment by kemsky** [comment]
`<div *ngIf="condition">...</div>` renders as `<div>...</div>`
while `<ngIf [condition]="condition">...</ngIf>` renders as `...`

**Comment by vicb** [comment]
It would work if you have a directive which selector is `[condition]`

closing as work as expected

**Comment by kemsky** [comment]
@vicb, actually, it would not.

`@Directive({selector: 'custom[condition]'})`
 `<custom [condition]="true"><b>test</b></custom>` will produce: No provider for TemplateRef!

`@Directive({selector: '[condition]'})`
 `<custom [condition]="true"><b>test</b></custom>` will produce: Template parse errors: 'custom' is not a known element.

Tested using `ngIf` source code.

**Comment by vicb** [comment]
`<custom *condition="true">` should work in your first example

**Comment by kemsky** [comment]
My last attempt to explain the difference.

Current behavior:
`<custom *condition="true">value</custom>`  => `<custom>value</custom>`,  same as `<template [ngif]="true"><custom></custom></template>`, and in fact it is the same as in the first comment.

Feature request:
`<custom [condition]="true">value</custom>`  => `value`,  `custom` tag is not rendered, it is alias for `template`.

**Comment by vicb** [comment]
I don't really understand your question, maybe you're looking for `<ng-container>` ?

`<ng-container *ngIf="true">value</ng-contaier>` => `value` (`ng-container`is a logical container, not rendered in the DOM)

**Comment by zoechi** [comment]
@kemsky what's the use case?

**Comment by kemsky** [comment]
`*` asterisk syntax is good only for small pieces in place, because condition(logic) and component(renderer) should be separated, the only way to do that is to use `<template directive></template>` so that condition itself does not render additional tags. 

Example:
```
<authenticated>
    <button>logout</button>
</authenticated>
``` 
Currently it can not be implemented without additional tag (and `ng-content` projection) or use of `template` like `<template authenticated></template>`. So i wish could define my own logical container like `ng-container` to make code clear and short.

**Comment by zoechi** [comment]
Then you would also have to define somewhere that `<authenticated>` is a special tag that mimicks the `<template>` or `<ng-container>` tag. How would that be different from your current workaround (`<authenticated>` component)?

**Comment by kemsky** [comment]
Yes, it has to be defined somehow.

Consider another example, declarative column configuration:
```
<table [dataProvider]="collection">
     <column data="name" [label]="toUpperCase">Name</column>
     <column data="department.name">Department</column>
</table>
```
This template then renders as:
```
<table>
    <thead>
         <tr>
               <th>Name</th>
               <th>Department</th>
         </tr>
    </thead>
    <tbody>
            ....
    </tbody>
</table>
```
