### ISSUE TITLE
Need to report template transpiling bugs

### ISSUE THREAD

**Issue by born2net** [angular/angular#11987]
with latest ng2.0 I got no error reported on the following misconfigured template error:

using Angular 2.0 release
in Windows 10 64bit
typescript 2.0
node 6.5.0

no need for plunkr as just look at the image, if you add an extra ```>``` you will not get an error

![capture](https://cloud.githubusercontent.com/assets/5090936/18964847/80e1b4aa-862f-11e6-8463-fa6c758e242c.PNG)

**Comment by vicb** [comment]
Please descrive youe environment and add a plunker to reproduce the issue if possible.

**Comment by born2net** [comment]
updated above,
regards

**Comment by vicb** [comment]
Sorry but that's not clear. Please open a new issue when you have a reproduction case. Thanks.
