### ISSUE TITLE
label's for is not know attribute for angular

### ISSUE THREAD

**Issue by piernik** [angular/angular#11983]
I've tried to make dynamic `for` attribute in `label` tag but I got error.
```
<label [for]="field.id"></label>
```

**Comment by DzmitryShylovich** [comment]
try `<label [attr.for]="field.id"></label>`

For support questions see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by piernik** [comment]
Works - thanks

**Comment by pkozlowski-opensource** [comment]
@mhevery  @vicb this one os another instance of a pb that wouldn't surface if we decide to merge #10546. User ergonomics matter so I would like to go back to the discussion on #10546.
