### ISSUE TITLE
Bug in Windows: rollup.js config file.

### ISSUE THREAD

**Issue by kaplan81** [angular/angular#11982]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Following this cookbook:
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

And executing this command:
node_modules/.bin/rollup -c rollup.js 

It turns out that, at least on Windows environment, it just opens the file rollup.js in your default code editor.

**Expected behavior**
It should package the Angular 2 application into the file ./dist/build.js

**Reproduction of the problem**
n/a

**What is the motivation / use case for changing the behavior?**
The config file cannot be called rollup.js, I do not know why.
I changed it providing a random name: rollup-config.js
Then it worked perfectly :)

**Please tell us about your environment:**
Windows 8 64bit
Visual Studio Code 1.5.3
npm 3.10.3

* **Angular version:** 2.0.0

* **Browser:** all

 
* **Language:** Typescript 2.0.3
 
* **Node (for AoT issues):** `node --version` =   6.4.0

**Comment by DzmitryShylovich** [comment]
Please reopen in the docs repo https://github.com/angular/angular.io
Thx.
