### ISSUE TITLE
http.get().toPromise() + MockBackend leads to "Error: Expression has changed after it was checked" error

### ISSUE THREAD

**Issue by fedotxxl** [angular/angular#11986]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
I use promise instead of Observable and mock http backend. Now I'm getting pretty random "Error: Expression has changed after it was checked" error message when `promise.then` changes model. Changing `promise` to `Observable` fixes the problem

**Expected behavior**
Using promise should not lead to "Error: Expression has changed after it was checked" error

* **Angular version:** 2.0.0-rc.6

* **Language:** TypeScript

**Comment by DzmitryShylovich** [comment]
> Angular version: 2.0.0-rc.6

upgrade to the latest angular and provide reproduction.

**Comment by vicb** [comment]
And add a plunker to reproduce the issue (open a new issue when ready)
