### ISSUE TITLE
misconfiguring a template with an extra closing tag > does not result in an error

### ISSUE THREAD

**Issue by born2net** [angular/angular#11988]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Adding a small ```>``` can create some REALLY hard bug to track down and yet no error is generated by JIT ng2 engine.

**Expected behavior**
Would like to see an error at JIT or even better during dev

**Reproduction of the problem**
Plunkr: 
https://plnkr.co/edit/jMe3fQEe4vABXv3hkDuR?p=preview
see ```app/app.component.html``` file

**What is the motivation / use case for changing the behavior?**
make it VERY hard to debug as you don't know you are missing inputs for example

**Please tell us about your environment:**
Windows 10 x86 64 

* **Angular version:** 2.0.X 
Angular 2.0 release

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web  
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Chrome laest
 
* **Node (for AoT issues):** `node --version` =   
6.5.0

see issue:
![capture](https://cloud.githubusercontent.com/assets/5090936/18966018/765045f6-8634-11e6-99bf-f99a62f0a3ff.PNG)

**Comment by lazarljubenovic** [comment]
Angular can't (and shouldn't) help here at all; the HTML is valid. There's no way for angular to know that the "extra" tag is "extra"; it just parses the stuff after it until the corresponding closing tag and takes that as content.

`[(visible)]="showDialog"><h1>..</h1><button>...</button>` is valid content of an element.

**Comment by born2net** [comment]
IMHO it can determin no closing tag was put in place, will be trivial to do and make ng2 that mush more powerful as I know the team already said they will be working on better transpiling of templates...
regards

**Comment by pkozlowski-opensource** [comment]
> IMHO it can determined no closing tag was put in place, will be trivial to do 

@born2net I would exercise caution with statements like above, unless you can prove it with a PR (if it is trivial a PR should be easy to put together, right?)

**Comment by born2net** [comment]
I will close this PR as I don't think its being liked
