### ISSUE TITLE
[http testing] Outdated MockBackend documentation, missing http testing examples

### ISSUE THREAD

**Issue by alexbyk** [angular/angular#11984]
```
[ x] bug report => search github for a similar issue or PR before submitting
[ x] feature request
```

I tried to write a test with mocking 'http' service and faced a problem: all internet "howtos" are outdated, there is no official example in the "Advanced/Testing", and the API reference for the MockBackend is outdated(or contains bugs?).

I would be great to have an official example how to deal with http in tests

**Comment by DzmitryShylovich** [comment]
Please re-open in the docs repo https://github.com/angular/angular.io
Thx.

**Comment by alexbyk** [comment]
done https://github.com/angular/angular.io/issues/2505
