### ISSUE TITLE
Angular2 $compile directive as AngularJS 1?

### ISSUE THREAD

**Issue by ANGULAR-X** [angular/angular#11998]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
?

**Comment by ANGULAR-X** [comment]
@vicb In angular2, are there any methods just like $compile() ?
