### ISSUE TITLE
[RFC] Drop `<template>` and `<tag template="...">` special meaning for Ng

### ISSUE THREAD

**Issue by vicb** [angular/angular#11994]
@chuckjaz raised the point that `<tag template="...">` could be dropped now that Angular uses its own html parser. It was only introduce because IE does not support `<template>`.

I think this is a valid point and we should drop this special syntax now.

Thinking more about this (thanks @zoechi for #7974) we should also drop `<template>` because it is used by WC and we don't want to interfer. Let's look at a Polymer example:

``` html
<iron-list>
  <template>
    <div>{{item}}</div>
  </template>
</iron-list>

<!-- for now you have to -->

<iron-list>
  <ng-container ngNonBindable>
    <template>
      <div>{{item}}</div>
    </template>
  </ng-container ngNonBindable>
</iron-list>
```

We have chosen to document `<ng-container *ngIf>` instead of `<template [ngIf]>` so that users have only one way to do things even when there are multiple root nodes.

The idea would be to deprecate `<template>` and `<tag template="...">` ASAP and drop them as of v4.0.0. `<ng-container>` would be used in all cases.

Things to consider:
- HTML editor: they are not aware of `<ng-container>` - is `<template>` any better ?
- Can we create a template reference with `<ng-container>` (ie when passing a template to `ngFor`).

/cc @IgorMinar @mhevery

**Comment by tbosch** [comment]
We need to figure out how a user can bind to `@Output`s of a directive that is used via `*...`. See https://github.com/angular/angular/issues/12121.

**Comment by laco0416** [comment]
I agree this. It's very important to keep interoperability to web standards for collaborations with other libraries and technologies.

**Comment by IgorMinar** [comment]
I agree that it is confusing that we have 3 ways of doing the same thing (`<template directive>`, `<foo template=...`, `<ng-container *directive>`), but we do need to preserve `*` which needs to desugar to something. What does it desugar to if we drop `<template>`?

I think this RFC should be augmented to propose deprecation of `<foo template=...` - template as an attribute as that style is not useful for anything.

An alternative is drop all of the desugaring: `bind-`, `on-`, `template`, and keep just the sugar form. I'd be happy to consider that, but we need to make sure that there are no usecases where the desugared form is required.

**Comment by laco0416** [comment]
In other words, desugaring forms is _valid HTML forms_.  For example, html-loader needs special configurations to minify Angular templates because it cannot parse case-sensitive and some symbols in the template. Being valid HTML can bring benefits for tooling and interop.
I think it's not bad to have only **two** forms. One is an easy-and-special way. Another is a raw-and-standard way.

**Comment by IgorMinar** [comment]
The sugar form is also valid html. Angular templates are valid html even if
the content is case sensitive. Some tools however diverge from the spec and
don't have a spec-compliant parser.

**Comment by vicb** [comment]
1) We need to keep an "expanded" version because we do not enforce input naming

ie if someone comes with `<template myFor [of]="" let-i>`, there is no way the *-syntax can be used here (`of` should have been `myForOf`)

2) We should drop the `<template>`

It has special meaning for html. We do not need this special meaning now that we use our own parser and it hurt inter-operability. 

--

Proposition

- `<ng-container *ngFor="let i of items >`
- `<ng-container ngFor bind-ngForOf="items" let-i>`

what would be wrong here ?

**Comment by mhevery** [comment]
the `<div template="ngFor"` is there for consistency with `on-`, `bind-`, etc.. in case people don't want to use special characters such as `*` with their HTML. Just explaining the reasoning, not arguing for anything.

I think `ng-container` and `template` have different meanings to me. 'ng-container` groups whereas `template` defines a template which could be used someplace else. If we don't want to collide with `template` then maybe we should have `ng-template`

**Comment by IgorMinar** [comment]
I'm fine with ng-template.

The original reason for using the template element was to have an inert
piece of DOM that didn't trigger image downloads or script execution.
That's no longer the problem now that we have our own parser.

**Comment by vicb** [comment]
What about:

**Preferred**

1. `<ng-container *ngFor="let i of items" >` for 1+ root element
2. `<ng-container ngFor bind-ngForOf="items" let-i >`
3. `<ng-template>` used only when you need to get an explicit template ref (ie to stamp out rows in `ngFor`)

**Also works - not advertised**

1. `<ng-template ngFor bind-ngForOf="items" let-i >`
1. <template> works as today but **deprecated & removed in 4.0**
2. <tag template=""> works as today but **deprecated & removed in 4.0**

@mhevery your "the `<div template="ngFor"` is there for consistency with `on-`, `bind-`, etc.." should be addressed by P1 above ??

**Comment by mhevery** [comment]
Actually can we revisit the original premise? Why do we think that `template` is a problem? Yes `template` may be used by WC, but a given template will never be interpreted by both Polymer and Angular? (Or am I mistaken on that?) Could you come up with an example where the collision could happen?

**Comment by zoechi** [comment]
Of course Polymer interprets the `<template>` element. In the initial example it uses it as a template for list items and stamps them once for each data item (like `*ngFor`). Angular2 prevents adding `<template>` tag to the DOM, therefore there is no way to pass one from an Angular2 component template to a Polymer element in the same components template (like demonstrated in the initial comment).

**Comment by vicb** [comment]
@mhevery see the initial report on top
