### ISSUE TITLE
[RFC] Create a Log service

### ISSUE THREAD

**Issue by vicb** [angular/angular#11995]
Currently there is a mix of [`Console`](https://github.com/angular/angular/blob/42b4b6d21b5c629bf938a19afc4196cfb0ea4813/modules/%40angular/core/src/console.ts#L12-L17) service and [`getDom().log()`](https://github.com/angular/angular/blob/42b4b6d21b5c629bf938a19afc4196cfb0ea4813/modules/@angular/platform-browser/src/dom/dom_adapter.ts#L43-L46)

We should unify the log reporting in a Log service.

**Comment by zoechi** [comment]
Sounds like #5458

**Comment by vicb** [comment]
closing as duplicate
thanks @zoechi
