### ISSUE TITLE
Port Angular Dart optimizations

### ISSUE THREAD

**Issue by vicb** [angular/angular#11997]
## Non breaking changes
- [ ] Move all unbound textnodes out of component class members [commit](https://github.com/dart-lang/angular2/commit/f84eb1fd10d3a1d6b124d0c16e1d74e4e5070b11)
## Breaking changes
- [ ] `setAttribute` / `setAttributeNS` at compile time [commit](https://github.com/dart-lang/angular2/commit/7f1e1c085f00b525c366a3f895b3d4e966f9124c)
## Need evaluation
- [ ] Deprecate DOMRenderer projectNodes [commit](https://github.com/dart-lang/angular2/commit/4c627454ec1f2b0abf0e649461491908b217f41a)
- [ ] Improve change detection performance by reducing cdMode checks [commit](https://github.com/dart-lang/angular2/commit/c1e9c9a5bc335a6bf8095214c78596f3c47518d3)
- [ ] Optimize StaticNodeDebugInfo(const [],null,const <String, dynamic>{}) [commit](https://github.com/dart-lang/angular2/commit/4e53d96aa5cf3ad5066158686d34f2aa16623ac9)
## 

Sync on Sep 26, 2016

**Comment by b-strauss** [comment]
Will this include ChangeDetectionStrategy.Stateful? [commit](https://github.com/dart-lang/angular2/commit/8cd7f35d74a9a8e323d6f0cf73ddda5acb079fe3)

```dart
/// Schedules a microtask to notify listeners of state change.
///
/// Usage:
@Input()
set title(String newValue) {
  setState(() => _title = newValue);
}
```

**Comment by DzmitryShylovich** [comment]
@vicb there's a new view engine. is this still relevant?
