### ISSUE TITLE
[RFC] Create a Deprecation service

### ISSUE THREAD

**Issue by vicb** [angular/angular#11996]
To allow logging the deprecated APIs.

ideas:
- by default log messages only once (make this configurable),
- allow message to have parameters (to print them only once) - use template literals ?
- should take a message, a reason and a from version,

/relates to #11995

**Comment by robwormald** [comment]
i like the core-decorators way of handling this https://www.npmjs.com/package/core-decorators#deprecate-alias-deprecated

**Comment by vicb** [comment]
yep definitely, something we discussed with @tbosch this morning.

I think it would be overkill to do it before TS deliver their transformer branch - not sure about the status ?

**Comment by JoostK** [comment]
Closing as the need for this hasn't come up much over the past few years. If this ends up being useful for future deprecations we can always consider having some logic in place for this, but even then it will likely not be exposed as public API.
