### ISSUE TITLE
enableDebugTools clobbers ng and removes ng.probe

### ISSUE THREAD

**Issue by danielcrisp** [angular/angular#12002]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
If I enable Angular's built-in debug tools `enableDebugTools`, like this:

``` javascript
import { enableProdMode, ComponentRef } from '@angular/core';
import { enableDebugTools } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';

platformBrowserDynamic().bootstrapModule(AppModule).then((ref: ComponentRef) => {
    enableDebugTools(ref);
});
```

Then `ng.probe` is no longer available for debugging because `ng` is overwritten with the `AngularTools` class. This results in an error if I try to use Augury, see: https://github.com/rangle/augury/issues/714

**Expected behavior**
I would expect `enableDebugTools` to _extend_ `ng` with additional methods, e.g. `ng.profiler`, rather than clobbering it. This would allow me to continue to use `ng.probe` and extensions like Augury when Angular's debug tools are enabled.

**Reproduction of the problem**
http://plnkr.co/edit/c8BKDIqtcScfKPooIy1n?p=preview

**What is the motivation / use case for changing the behavior?**
Allows developers to continue using Augury when `enableDebugTools` is in use.

**Please tell us about your environment:**
OSX, Sublime, npm
- **Angular version:** 
  2.0.0 
- **Browser:** 
  all
- **Language:** 
  all

**Comment by danielcrisp** [comment]
It also seems to remove `ng.coreTokens`

**Comment by gdi2290** [comment]
As a workaround you have to hold on to a reference to `probe` and `coreTokens` before turning it on. For example,
https://github.com/AngularClass/angular2-webpack-starter/blob/dbb7d10e6e84b8e88116d957f0047b422ab807c1/src/app/environment.ts#L28...L36
