### ISSUE TITLE
i18n: extracted xliff file is not valid, ctype attribute is wrong

### ISSUE THREAD

**Issue by kmcs** [angular/angular#12000]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting

```

**Current behavior** 
The extracted xliff file is not valid. If you have a translation text in your html file like that:
```
<p i18n>
My Text has a<br>
line break.
</p>
```
It creates in your xliff file the following trans-unit tag:

```
<trans-unit id="23452345abc" datatype="html">
 <source>
  My Text has a<x id="LINE_BREAK" ctype="br" />
  line break.
 </source>
</trans-unit>
```

**Expected output according to xliff spec 1.2 should be**

```
<trans-unit id="23452345abc" datatype="html">
 <source>
  My Text has a<x id="LINE_BREAK" ctype="lb" />
  line break.
 </source>
</trans-unit>
```

I think there should be a mapping for all predefined ctype: http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#ctype

something like that:

```
let ctype;
switch(ph.tag) {
  case 'br':
    ctype = 'lb';
    break;
  case 'b':
  case 'strong':
    ctype = 'bold';
    break;
  case 'i':
  case 'em':
    ctype = 'italic';
    break;
  case 'u':
    ctype = 'underline';
    break;
  case 'a':
    ctype = 'link';
    break;
  default:
    ctype = 'x-' + ph.tag;
}
```

is needed instead of ph.ctype around that lines here:
https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/i18n/serializers/xliff.ts#L140

* **Angular version:** 2.0 

* **Language:** TypeScript 2.0.2
 
* **Node (for AoT issues):** `node --version` =   v4.4.4

**Comment by vicb** [comment]
Seems like only `lb`, `pb` and `image` are well known values for `x`/`ph`, right?
