### ISSUE TITLE
Perf: Profile benchmark from stefankrause.net/wp/

### ISSUE THREAD

**Issue by tbosch** [angular/angular#12011]
See http://www.stefankrause.net/wp/

Why are we not faster in this case?
Was it measured correctly? Maybe create a PR to use benchpress?

**Comment by robwormald** [comment]
note I recently sent PRs to update to 2.0.0 and AoT (which is not reflected in the latest post (round 4)) 

https://github.com/krausest/js-framework-benchmark/pull/54 and https://github.com/krausest/js-framework-benchmark/pull/56

**Comment by tbosch** [comment]
There are probably more benchmarks that we want to track... closing for now.
