### ISSUE TITLE
Angular 2 getting error while adding custom decorator with the line “import 'reflect-metadata'”

### ISSUE THREAD

**Issue by Lemmy4555** [angular/angular#12010]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 
Importing reflect-metadata on a Accessor Decorator cause this error:
`Unexpected value 'AppComponent' declared by the module 'AppModule'`.

**Expected behavior**

**Reproduction of the problem**
I've downloaded the tour-of-heroes project from github and i've added this file:
```
//Validate.ts
import "reflect-metadata";

export function Validate<T>(target: any, propertyKey: string, descriptor: TypedPropertyDescriptor<T>) {
  let set = descriptor.set;
  descriptor.set = function (value: T) {

  }
};
```
Then i've edited the hero-detail.component.ts file like this:
```
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';

import { Hero } from './hero';
import { HeroService } from './hero.service';
import { Validate } from './Validate'; // Added

@Component({
  moduleId: module.id,
  selector: 'my-hero-detail',
  templateUrl: 'hero-detail.component.html',
  styleUrls: ['hero-detail.component.css']
})
export class HeroDetailComponent implements OnInit {
  @Input() hero: Hero;
  @Output() close = new EventEmitter();
  error: any;
  navigated = false; // true if navigated here
  private _test: string; // Addedd

  constructor(
    private heroService: HeroService,
    private route: ActivatedRoute) {
  }

  ngOnInit(): void {
    this.route.params.forEach((params: Params) => {
      if (params['id'] !== undefined) {
        let id = +params['id'];
        this.navigated = true;
        this.heroService.getHero(id)
            .then(hero => this.hero = hero);
      } else {
        this.navigated = false;
        this.hero = new Hero();
      }
    });
  }

  @Validate               // Addedd
  set test(test: string){ // Addedd
    this._test = test;    // Addedd
  }                       // Addedd

  save(): void {
    this.heroService
        .save(this.hero)
        .then(hero => {
          this.hero = hero; // saved hero, w/ id if new
          this.goBack(hero);
        })
        .catch(error => this.error = error); // TODO: Display error message
  }

  goBack(savedHero: Hero = null): void {
    this.close.emit(savedHero);
    if (this.navigated) { window.history.back(); }
  }
}

```
I've also edited the system-config.ts by adding this line:
```
const map: any = {
  'app' : 'app',

  'main': 'app/main.js',
  '@angular' : 'node_modules/@angular',
  'angular2-in-memory-web-api' : 'node_modules/angular2-in-memory-web-api',
  'rxjs' : 'node_modules/rxjs',
  'reflect-metadata': 'node_modules/reflect-metadata/Reflect.js' // Added
};
```

**What is the motivation / use case for changing the behavior?**
Use of Accessors Decorators

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.0

* **Browser:** all
 
* **Language:** Typescript 2.0.2
 
* **Node (for AoT issues):** `node --version` =   4.6.0

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by Lemmy4555** [comment]
I insist for a checking of this issue, i passed the entire day debugging angular to find the issue and i found out that in some cases like the one i've described the constructor of the class Reflect.ts is called twice, this cause a lose of the informations stored in the WeakMap Metadata are lost and this cause the issue i've described in my post.

For clearity this is the behaviour i'm talking about.

1. Angular start and try to map all decorators for the components in my app.
2. Angular map decorators for Component1, Component2, Component3.
3. Angular try to map decorators of Component4 but at this point the constructor of Reflect is called and informations stored in map (Component1, Component2, Component3) are lost.
4. Angular continue to Map the decorators and finishes, now we have mapped Component4 and 5, but not 1,2,3.
5. Angular try to check Decorators in Component 4 and it is OK,
6. Angular try to check Decorators in Component 5 and it is OK,
7. Angular try to check Decorators in Component 1 and it is KO because Angular cannot find the mapping,
8. Rejection **"Unexpected value 'Component1' declared by the module 'AppModule'."** is raised

I'm still debugging angular to find out why the constructor is called twice...

**Comment by Lemmy4555** [comment]
I've added the [Plunker example](http://plnkr.co/edit/cE15NUZbuuLwnSdyy0Uq?p=preview) of tour-of-heroes-

**Comment by Lemmy4555** [comment]
I've solved the issue by adding line 
`import 'reflect-metadata` to all Components that has raised the errors:
[Here is the fixed version of the Plunker example](http://plnkr.co/edit/O6IQvhJQeZccfBrMkB8o?p=preview)
