### ISSUE TITLE
router is not being disposed when destyoing an app (NgModuleRef)

### ISSUE THREAD

**Issue by talsi** [angular/angular#12014]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
router is not being disposed after destyoing an app (NgModuleRef). it keeps intercepting routing events.

**Expected behavior**
router should be disposed after app gets destroyed and stop handle navigation events

**Reproduction of the problem**
plunker (BUG1 - README.md): http://plnkr.co/edit/1qK9m8WrkXejzoM20glQ?p=preview
git repo (BUG1 - README.md): https://github.com/talsi/ng2-bug-reproduce-destroy
1. reload app
2. wait for angular app to load.
3. click on button "destroy app" (from destruction panel).
4. click on button "navigate to some non angular route (1) / (2)" (from outter app navigation)

**What is the motivation / use case for changing the behavior?**
NgModuleRef.destroy definition is "to destroy the module instance and all of the data structures associated with it". it should also dispose the router if one is being used by the module.

**Please tell us about your environment:**

Windows10, WebStorm, NPM 3.10.3, NodeJs 6.5.0, Angular-CLI 1.0.0-beta.16
- **Angular version:** 2.0.0
  
  
  
  "dependencies": {
  "@angular/common": "2.0.0",
  "@angular/compiler": "2.0.0",
  "@angular/core": "2.0.0",
  "@angular/forms": "2.0.0",
  "@angular/http": "2.0.0",
  "@angular/platform-browser": "2.0.0",
  "@angular/platform-browser-dynamic": "2.0.0",
  "@angular/router": "3.0.0",
  "core-js": "^2.4.1",
  "rxjs": "5.0.0-beta.12",
  "ts-helpers": "^1.1.1",
  "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.16",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
- **Browser:** Chrome 53.0.2785.116 m
  
  
- **Language:** TypeScript 2.0.2
- **Node (for AoT issues):** `node --version` =   6.5.0

**Comment by vsavkin** [comment]
This is an issue with DI. It doesn't handle the lifecycle events of the providers created using 'useFactory'.

**Comment by mirikle** [comment]
One solution that may or may not apply to you is just ditch the routing system completely and use your own routing logic.

**Comment by mcgraphix** [comment]
Any progress on this? I'm glad it's been assigned to someone. If you need anyone to help I'm be happy to lend a hand. This is super urgent for us at ADP as we need this working ASAP.

**Comment by trotyl** [comment]
Has been fixed by https://github.com/angular/angular/pull/23755.

**Comment by atscott** [comment]
This appears to be fixed in v9, likely by the issue @trotyl mentioned.
Demo: https://stackblitz.com/edit/angular-ivy-router-base-vrb8oh?file=src%2Fapp%2F_routing.module.ts
