### ISSUE TITLE
why are Control and ControlGroup API missing

### ISSUE THREAD

**Issue by slashhuang** [angular/angular#12028]
**I'm submitting a feature request**  (check one with "x")

**Current behavior**
```import {AbstractControl, ControlGroup, Control} from "@angular/forms";```
tsc loader compilation bugs when parsing Control and ControlGroup 

**My problem**
I am an early bird user of angular2 rc, when I want to migrate to angular2.0.0.
APIs like Control and ControlGroup are missing,
which leads to a big problem for customize formControl validators.

**My request**
I desperately want Control and ControlGroup back 

**IDE**
my IDE is webstorm ,using Angular version:2.0.1 with typescript

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by slashhuang** [comment]
@vicb  I just checked the angular docs one more time, finally got to find that API names seemed have been changed to FormGroup and FormControl,
thank u anyway
