### ISSUE TITLE
Unable to use external javascript file inside angular2 applications

### ISSUE THREAD

**Issue by rvdabhi** [angular/angular#12038]
**I'm submitting a ...**  (check one with "x")
```
[ ] external javscript file not working
```

**Current behavior**
I am trying to use html5 theme into my angular2 app, but somehow theme javascript file not working inside the application

**Expected behavior**
angular2 able to execute and load external js files

**Minimal reproduction of the problem with instructions**
none

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] TypeScript

* **Node (for AoT issues):** `node --version` =   v5.12.0

**Comment by DzmitryShylovich** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use gitter and StackOverflow for support request.

**Comment by rvdabhi** [comment]
Thanks for your suggestion started gitter

**Comment by pkozlowski-opensource** [comment]
As @DzmitryShylovich pointed out this is _not_ the right forum for those types of questions, please use one of the mentioned support channels.
