### ISSUE TITLE
ngUpgrade executes digest outside "angular" zone causing issues

### ISSUE THREAD

**Issue by dtabuenc** [angular/angular#12034]
**I'm submitting a ...**  

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
    When running a hybrid ng1/ng2 application ngUpgrade subscribes to the `onMicrotaskEmpty` and then executes the angular1 digest within an `ngZone.runOutsideAngular()`.

This was behavior was introduced by this pull request in order to try to fix the problem of infinite digests:

https://github.com/angular/angular/pull/6386 (issue https://github.com/angular/angular/issues/8004)

**Expected behavior**

All angular 1 digests must happen inside the angular zone. Digest could potentially setup timeouts, intervals, oveservables etc... that should then cause change detection to trigger. If the digest cycle is running outside of the angular zone, these things will forever leak into the root zone and never trigger future change detections.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/JH2NNHxIscInf4S1Dtg4?p=preview

**What is the motivation / use case for changing the behavior?**

This will cause a lot of subtle bugs and weird behaviors due to change detection not triggering.

**Please tell us about your environment:**

- **Angular version:** 2.0.1
  
  
- **Browser:** all
  
  
- **Language:** all

**Comment by dtabuenc** [comment]
I think we just need a different solution for preventing an infinite loop of digest cycles that doesn't involve  `runOutsideAngular()`. I currently have a naive solution implemented in my project by just setting up a guard variable before the `evalAsync()` and resetting it to false/returning if the digest is already run once. That might be good enough, but I'm not sure if there are edge-cases I'm not thinking about. 

Probably a more robust solution would have a way to tell if the last run of the digest triggered any micro-tasks that will cause the `onMicrotaskEmpty` to fire again. If it's guaranteed that the digest will cause the `onMicrotaskEmpty` to fire again, then my naive solution will work just fine. 

My only concern with the naive case is if the digest cycle does not queue any microtasks and the `onMicrotaskEmpty` does not fire again as a result, then the flag will stay true, and some other unrelated digest cycle in the future might be unnecessarily skipped.

If someone can comment on these or other possible fixes, I can submit a pull request pretty quickly.

**Comment by petebacondarwin** [comment]
See #12318
