### ISSUE TITLE
(feat) Official List of Angular Modules

### ISSUE THREAD

**Issue by Larisho** [angular/angular#12036]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

There is no official list of all the different modules provided in the Angular API. There should be an official list in the Angular Documentation to reference when trying to figure out which modules one needs to import for which functions.

**Comment by vicb** [comment]
https://angular.io/docs/ts/latest/api/ seems to be what you want.

If not please re-open an issue on the doc repo at https://github.com/angular/angular.io
