### ISSUE TITLE
Error with importing ComponentResolver in component 

### ISSUE THREAD

**Issue by maxkarpovets** [angular/angular#12039]
I am trying to import "ComponentResolver": 

`import { Component, HostListener, ViewContainerRef, ViewChild, ComponentResolver } from '@angular/core';`

And I have error:

`Module '"/home/maksym/untill/trunk/unTill.Modern/Code/AppRc6/node_modules/@angular/core/index"' has no exported member 'ComponentResolver'.`

How i can fix it?

**Comment by DzmitryShylovich** [comment]
`ComponentResolver` was deprecated and removed. Use `ComponentFactoryResolver` instead.

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://gitter.im/angular/angular) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular2) for support request.

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich !
