### ISSUE TITLE
Compiler generates duplicate entry for router guard, if it is declared in sub-module via static field of component

### ISSUE THREAD

**Issue by davydkov** [angular/angular#12033]
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Let's suppose we have to following modules:

```
AppModule
  -> imports FeatureModule
     -> import SubFeatureModule
```

`FeatureModule` has routes definitions

`SubFeatureModule` has component and router guard (resolve). Component declares its resolves via static field (to keep it in one place)

So `FeatureModule` declares a route, that lands to the component from `SubFeatureModule` and resolves given guard.

In runtime (browser-dynamic) everything works as expected. But when we compile with angular-compiler, among imports a duplicate entry appears for resolver, and it has wrong path.

Although, resolution via static fields in AoT in other cases works fine, I could not figure out why it fails in this case.

**Minimal reproduction of the problem with instructions**
I've created a repository with minimal code to reproduce:
[Source code to reproduce](https://github.com/beenokle/angular-compiler-bug)

**Please tell us about your environment:**
- **Angular version:**
  2.0.1
- **Language:**
  `typescript@2.0.3`
- **Node (for AoT issues):**
  `node version 6.5.0`

**Comment by tbosch** [comment]
This might be fixed via https://github.com/angular/angular/pull/13133, but needs to be double checked.

**Comment by DzmitryShylovich** [comment]
@beenokle can you pls confirm that this is still doesn't work?

**Comment by DzmitryShylovich** [comment]
@beenokle is this still valid in angular 4? can you please update your example? thanks

**Comment by JoostK** [comment]
I can no longer reproduce in Angular 9, neither using ViewEngine nor Ivy.
