### ISSUE TITLE
Resolve data of a parent Componentless route doesn't get merged into child in case of Promise

### ISSUE THREAD

**Issue by mdkholy** [angular/angular#12032]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Resolve data of a parent Componentless route doesn't get merged into child route data if the resolve function returned a ``Promise``. This might be related to #10494.

**Expected behavior**
The router should  merge the resolve data of a componentless parent into the data of the children routes.

**Minimal reproduction of the problem with instructions**
Open the plunk https://plnkr.co/edit/TObpPAgok78iAoqFpYE5?p=preview and click on the four links shown, you will notice that the fourth link doesn't display the resolve data correctly.

**What is the motivation / use case for changing the behavior?**
Fix bug.

**Please tell us about your environment:**
* **OS:** Ubuntu 16.04.1, **Node:** 6.7.0. **NPM:** 3.10.3

* **Angular version:** 2.0.1
* **Browser:** all

 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =

**Comment by zoechi** [comment]
Seems related to #10494
