### ISSUE TITLE
no way to bind to html properties from children elements

### ISSUE THREAD

**Issue by lqbweb** [angular/angular#12030]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I have something like:

```
<div myDirective>
  <input/>
</div>
```

where myDirective is something like this:

```
@Directive({
    selector: '[myDirective]',
    host: {
        '[readonly]': 'myFunc()'
    }
})
export class MyDirective{ myFunc() {....} }
```

this fails because div does not have such `readonly` property, but `<input/>` does have.

I do not have control over the `<input/>` because it is generated by an external JQuery library (which I also cannot modify), otherwise I would have just put my annotation over the <input/> element.

**Expected behavior**

There should be a way to bind to html properties from children elements. Or in any case, at least a way to tell Angular2 to apply the property to the first child that has such property at runtime.

As Angular2 works right now, I find very difficult to integrate with existing JQuery libraries that modify the Dom, mainly because of dynamic project not yet available [here ](https://github.com/angular/angular/issues/8563)issue is on going)

**Comment by vicb** [comment]
Not actionable.
You can get hold of the div element, then navigate to the children, ...

**Comment by lqbweb** [comment]
I am not sure if you understood me. Perhaps I was not clear either.

Of course I can always inject the ElementRef from the <div> and then browse to children with JQuery and apply the properties myself by subscribing to the ChangeDetector of my current component somehow. You could even do this for everything and then no need for @HostBinding and @HostListener, but I think it is a way too low level right?

I was proposing that @HostBinding could bind some method from my current component to a child element attribute of my component and the same with @HostListener. If somehow this goes against any principle or does not make sense, I would like to learn why.

In reality I would not have such a need if #6970 was implemented or if there were some sort of support for dynamically setup a binding in my current component, as I think #9055 is trying to explain.

In my experience with angular2, I learnt that you want components to be isolated and not to depend or mess with other things components, this is right within the context of Angular2 and assuming that the inner html of a component will always be generated with Angular2 projection, but it can also be generated at anytime from an external source with JQuery. I find very difficult to make ng2 to play nicely with external tools and libraries, as I cannot apply directives dynamically, or bind dynamically, or do anything dynamically.

Sorry if I was not clear enough at the beginning. If it is still not clear I can make a plunkr with the real case.
