### ISSUE TITLE
Conflict in Style Guide between app structure and demo code

### ISSUE THREAD

**Issue by pthalacker** [angular/angular#12049]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In the Style Guide the file and folder structure shows the app.component.ts file in src/app
But the demo code for app.module.ts, which resides in the root of src has this line of code
`import { AppComponent }   from './app.component';`

**Expected behavior**

The above line of code would say
`import { AppComponent }   from './app/app.component';`

**Minimal reproduction of the problem with instructions**
Navigate to https://angular.io/docs/ts/latest/guide/style-guide.html#!#app-structure-and-angular-modules and scroll down to the app.module.ts file code

**What is the motivation / use case for changing the behavior?**

To prevent new developers who use the awesome copy code feature in the docs from experiencing unnecessary errors

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
please reopen angular/angular.io
