### ISSUE TITLE
 Control class in angular/common ? Removed ?

### ISSUE THREAD

**Issue by jcamus** [angular/angular#12041]
Hello,
I am was using version "angular/common": "2.0.0-rc.5 version, now I've just tried  "@angular/common": "2.0.1" but Control class is gone! 
Here a sample of my code :

_import { Control } from '@angular/common';
static isPositiveIntegerControl(control : Control) {
		if (/^\+?(0|[1-9]\d*)$/.test(control.value)) {
			return null;
		}
		else {
			return { isPositiveInteger: false };
		}
	}_

Where can I find this class or how to fix this problem?

Regards.

**Comment by pkozlowski-opensource** [comment]
It was renamed to `FormControl`

**Comment by DzmitryShylovich** [comment]
Migration guide https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub#h.uk9x84gkes4t#h.uk9x84gkes4t

**Comment by jcamus** [comment]
Ok many thanks.
