### ISSUE TITLE
onSubmit submits form if handler function has error

### ISSUE THREAD

**Issue by gooor** [angular/angular#12048]
I have `<form #signInForm="ngForm" (ngSubmit)="onSubmit($event)">` whish is just basic sign in form, when error occurs in `onSubmit` method it just submits the form. There's no possibility of preventing default action at first as `$event` is just `null`

**Comment by DzmitryShylovich** [comment]
http://prntscr.com/cpg2tl

**Comment by vicb** [comment]
Please complete the issue template if you want to report a bug

**Comment by kemsky** [comment]
This issue is pretty clear as it is:
http://plnkr.co/edit/00mbcC75QBa0Yab2x97p?p=preview

**Comment by zoechi** [comment]
@kemsky I don't think it's too clear. Your Plunker doesn't even contain the code from the initial comment.
There are also no instructions how to reproduce.
The Plunker also contains too much code. That's not a minimal example.

**Comment by kemsky** [comment]
@zoechi, just press Submit and you will see reload and `null` in console.
There are two problems:
1. `$event` is null even if it was triggered by submit button.
2. If `ngSubmit` listener throws error form is submitted, it can be wrapped in `try`/`catch` but in general this behavior is wrong.
