### ISSUE TITLE
Docs Error: Module Providers Scope

### ISSUE THREAD

**Issue by alindsay55661** [angular/angular#12047]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The docs are inconsistent with regards to providers and module scope. Here are two contradictory explanations:

From https://angular.io/docs/ts/latest/guide/ngmodule.html#!#providers

"The ContactService provider is application-scoped because Angular registers a module's providers with the application's root injector... ...We might expect Angular to offer a module-scoping mechanism to enforce this design. It doesn't. Angular module instances, unlike components, do not have their own injectors so they can't have their own provider scopes."

From https://angular.io/docs/ts/latest/guide/router.html#!#child-routing-component

"The CrisisService is neither needed nor wanted outside the Crisis Center domain. Instead of registering it with the AppModule's providers — which makes it visible everywhere — we register the CrisisService in the CrisisCenterModule providers array... ...This limits the scope of the CrisisService to the Crisis Center routes. No module outside of the Crisis Center can access it."

**Expected behavior**
Either the provider scope is limited to the module its declared in or not. I expect the docs to reflect the correct behavior everywhere. Which one of these paradigms is the real McCoy?

* **Angular version:** 2.0.X
2.0.0

**Comment by DzmitryShylovich** [comment]
Pls re-open in the docs repo https://github.com/angular/angular.io

**Comment by alindsay55661** [comment]
Migrated to https://github.com/angular/angular.io/issues/2532
