### ISSUE TITLE
module is not defined error in browser when using a bundled js file produced by AOT and rollup

### ISSUE THREAD

**Issue by Sukh9212** [angular/angular#12046]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

While there has already been lot of talk and issues on module.id, This issues arises specifically after AOT and rollup. Following the AOT tutorial from angular.io website, after all the steps are successfully completed, and the whole application is in one build.js file, then running the application in browser throws error that "Uncaught ReferenceError: module is not defined".
I'm aware that obviously this is happening because plain JavaScript doesn't know what "module" is.

**Expected behavior**

Should't ngc or rollup take care of this during the build process so that browser doesn't complain?

I've seen similar [question](http://stackoverflow.com/questions/39662863/angular2-aot-module-id-is-not-defined-while-setting-module-id-in-component) on StackOverflow which is unanswered and a [question](https://groups.google.com/forum/embed/#!topic/angular/_iSj-d1nPiI) in Google groups.

Can't seem to find a solution

**Please tell us about your environment:**

* **Angular version:** 2.0.1

* **Browser:** [Chrome 53, haven't tested elsewhere ]

 
* **Language:** [all | TypeScript 2.0.3 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   4.6.0

**Comment by Sukh9212** [comment]
**my tsconfig-aot.json is**

`{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true
  },

  "files": [
    "app/app.module.ts",
    "app/main.ts"    
  ],

  "typeRoots": [
    "node_modules/@types"
  ],
  "types": [
    "core-js",
    "jasmine",
    "node",
    "fb",
    "jquery",
    "materialize-css",
    "nouislider"
  ],
  "include": [
    "app/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "aot",
    "dist"    
  ],

  "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : true
 }
}`

**and my rollup.js is** 

`import rollup      from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify'

export default {
  entry: 'app/main.js',
  dest: 'dist/build.js', // output a single application bundle
  sourceMap: false,
  format: 'iife',
  plugins: [
      nodeResolve({jsnext: true, module: true, main: true}),
      commonjs({
        include: 'node_modules/**',
        namedExports : {
          'node_modules/ng2-cookies/ng2-cookies.js': [ 'Cookie' ]
        }
      }),
      uglify()
  ]
}
`

**Comment by robwormald** [comment]
are you using `moduleId` in your components?

**Comment by Sukh9212** [comment]
Yes all the components in my application are similarly defined

`@Component({
    moduleId: module.id,
    selector: 'activity',
    templateUrl: 'activity.component.html'
})`

I don't have any problems in JIT mode

**Comment by robwormald** [comment]
`module` is purely for commonJS, and thus doesn't work in a rollup bundle (not using commonJS)

If you're using webpack (probably?) for JiT mode, why not use the same for AoT?

**Comment by Sukh9212** [comment]
@robwormald I'm aware that `module `is purely commonJS.

For JIT mode I'm using SystemJS.

While development I need to run application in JIT mode.
But my question is how can I generate a rollup bundle with the same code?


Do I need to make changes in my components each time I need to generate a rollup build?

Thanks for you help

**Comment by bmurali31** [comment]
Same issue here
I use SystemJS for JIT and I am trying to generate the rollup bundle.

**Comment by bmurali31** [comment]
Okay here is what I did

```
export default {
  entry: 'app/boot.js',
  dest: 'dist/build.js', // output a single application bundle
  sourceMap: false,
  format: '**cjs**',
```

And then in my systemjsconfig.js 
```
  var map = {
    'app-build': 'dist',
```
And in my html I am importing app-build if it is a production deployment
```
        <script>
            System.import('app-build')
                    .then(null, console.error.bind(console));
        </script>
```

**Comment by Craig-Cooke** [comment]
If your error is module is not defined after bundling using AOT just add the following to the head of your production index.html file:
 <script>window.module = "freeozgames";</script>

module is a global variable.

You don't need this in JIT mode with systemjs.

**Comment by diegodfsd** [comment]
@Craig-Cooke I'm with the same problem and even after I follow your suggestion the problem persist.

`Cannot create property 'exports' on string 'app'`

Do you have another suggestion?

This is my index.html

`<html>
  <head>
    <base href="/">
    <title>Angular 2</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="main.css">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    
     
</script>
    
    <script>window.module = "aot";</script>

    <script src="js/core-js/client/shim.min.js"></script>
    <script src="js/zone.js/dist/zone.js"></script>
    <script src="js/reflect-metadata/Reflect.js"></script>
  </head>
  
  <body>
    <app>
      <div class="loading-container">
        <i class="glyphicon glyphicon-refresh spin"></i>
        Loading ...
      </div>
    </app>
  </body>
    
    <script src="js/bundle.es2015.js"></script>
</html>
`

**Comment by SinghSukhdeep** [comment]
@diegodfsd you probably have a problem in your rollup bundle. It contains code that is written using ES6 style syntax that's why you're getting that error.

**Comment by ashwinirajput** [comment]
@SinghSukhdeep I am haveing the same problem how you fixed it can you suggest me what need to be changed.
