### ISSUE TITLE
DOM7011: The code on this page disabled back and forward caching

### ISSUE THREAD

**Issue by rahul0923** [angular/angular#12052]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On IE 11, windows 7 OS, for a child component i see this information

![image](https://cloud.githubusercontent.com/assets/19897523/19056876/ad050b96-8980-11e6-9dc4-b24c65224fb9.png)

![image](https://cloud.githubusercontent.com/assets/19897523/19056887/bd3d6d5a-8980-11e6-9ace-9a52b4e88753.png)

And i see this error message when i click the back button when navigating back from the child component

![image](https://cloud.githubusercontent.com/assets/19897523/19056911/f4b8b44c-8980-11e6-8696-009f34f0ab4c.png)

**Expected behavior**
Back / Forward buttons should work for Child Routes.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Win OS 7 Enterprise
* **Angular version:** 2.0.0

* **Browser:** [ IE 11 / Edge | Safari (latest)  ]

 
* **Language:** [all | TypeScript 2.0.2 | | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Minimal reproduction in plunkr?

**Comment by vicb** [comment]
please re-open once you have a repro available.

**Comment by ChetnaGupta** [comment]
@rahul0923 Did you find solution for this issue ?

**Comment by kanths49** [comment]
@rahul0923  did you find solution for this issue ?
