### ISSUE TITLE
AoT compiler creating ngFactory files for non-project files and linking to non-existent paths

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#12053]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report (I think)
```

**Current behavior**
The AoT compiler is processing and creating `.ngfactory.ts` files in `@angular/material` when I use `platformBrowser().bootstrapModuleFactory`. I have to include this directory in `rootDirs` for compilation to succeed.

**Expected behavior**
I may be wrong here, but I expected only my own project components, styles and templates to be processed.

**Minimal reproduction of the problem with instructions**
 In fact, the AoT compiler will fail if it doesn't have access to `Material` files.  For instance, if I edit `tsconfig.json` and change:
```
"rootDirs":["./dev","./node_modules/@angular/material"]
```
to:
```
"rootDirs":["./dev"],
```
I get 20 or 30 errors of this kind during compilation:
```
Error File 'C:/.../node_modules/@angular/material/button-toggle/button-toggle.ngfactory.ts' is not under 'rootDir' 
```
If I include `Material` dir in `rootDirs`, after compilation, the resulting directory structure (in output folder) is badly structured. [See details here along with tsconfig](http://stackoverflow.com/questions/39837618/why-does-angular-2-compiler-change-file-structure-when-i-switch-to-ahead-of-time).

Even if I include the `@angular/material` dir in `rootDirs` and allow the compilation to run (it completes without error), the app fails in the browser with `404 not found` when trying to load files such as:

> /@angular/core/bundles/core.umd.js/src/linker/ng_module_factory.js
> /@angular/common/bundles/common.umd.js/src/common_module.js
> ...

Here are some suspicious-looking imports in `app.module.ngfactory.ts`

> import * as import87 from '../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
> import * as import90 from '../../node_modules/@angular/material/tooltip/tooltip.ngfactory';

**What is the motivation / use case for changing the behavior?**
To get AoT to work

**Please tell us about your environment:**
Windows 7, PhpStorm.

* **Angular version:** 2.0.1
* **Language:** TypeScript 2.0.1

* **Node (for AoT issues):** `node --version` =   4.5.0

**Comment by vicb** [comment]
@tbosch is this the issue you've been working on ?
/cc @chuckjaz

**Comment by tbosch** [comment]
Yes. I have a test and the implementation almost ready...

**Comment by RoxKilly** [comment]
@tbosch  Is it accurate to say that the AoT compiler should not be generating `.ngfactory.ts` files in dependency folders like `@angular/core` and `@angular/material`? ie. is what I experienced above a bug? If you need more info, let me know.

**Comment by tbosch** [comment]
@RoxKilly AoT has to process `@angular/material` as `@angular/material` does not ship the `*.ngfactory.ts` files. We are not doing this so we can optimize the compiler without component authors needing to redistribute their components.

The other problem that you are seeing is described in https://github.com/angular/angular/issues/11889 which I am working.

Closing as duplicate.
