### ISSUE TITLE
Documentation is incorrect

### ISSUE THREAD

**Issue by falconmick** [angular/angular#12050]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://angular.io/docs/ts/latest/guide/router.html#!#service-isolation 
Under the header "Service Isolation" it states that we don't need or want a domain specific service used outside of our feature module. So it recommends providing it via the feature module rather than app module. 

**Expected behavior**
I would expect it to recommend placing the provides inside of the feature's highest up the chain component as I believed that provides worked in such a way that if it's on ANY module it will be global, so the only way to make a scoped service would be via a definition in a root level component of the feature.

I'm still learning so I could be wrong, but I was sure that this was the case. Cheers. I would include a PR but I have 0 idea how to contrib to doco as the module/@angular/docs doesn't have the page I am looking at

Cheers.

**Comment by vicb** [comment]
Please report docs issue on https://github.com/angular/angular.io/issues
