### ISSUE TITLE
"DOM stable" event

### ISSUE THREAD

**Issue by laurentgoudet** [angular/angular#1205]
This may or may not belong here but a recurrent pain point with client side view rendering is to now when the initial view has been rendered. Use cases include testability (e.g., Angular 1.x getTestability() used by Protractor), Synthetic/Real User monitoring (e.g., GA page speed stats not telling the whole story), or  server-side rendering. Ideally, as a developer, I'd love to have a "DOMStable" event similar to the DOMContentLoaded & Load events to monitor & improve the DOMStable time whether with the DevTools or on online service like WebPageTest.

Standardization on such event would allow test frameworks creators (Protractor, Robot..) and Synthetic/Real user monitoring providers (Google Analytics, WebPageTest, New Relic..) to provide better support for client side applications & encourage developers to care and improve the performances of such apps (#perfmatters as Google would say). 

The reason I realized it may or may not belong here is that in a Web Components-based scenario with Native, Ember, Polymer, and Angular components, no single framework as the knowledge about that "DOM stable" state, or at least not for the entire DOM. Thoughts?

**Comment by juliemr** [comment]
FYI: I'm currently working on Testability for Angular2 - see https://github.com/angular/angular/issues/525

**Comment by mhevery** [comment]
We already have this. See: https://github.com/angular/angular/blob/master/modules/angular2/src/core/annotations/annotations.js#L1028
