### ISSUE TITLE
NG Upgrade silently fails to bootstrap hybrid application

### ISSUE THREAD

**Issue by andrei-ivanovici** [angular/angular#12062]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The  upgrade adapter silently fails  to bootstrap a hybrid application in the following cases:

- Invalid dependency  in angular2 components . See reproduction plunk bellow
- Template errors in  angular 2 component. See reproduction plunk bellow

**Expected behavior**
 Errors  should be reported by the upgrade adapter

**Minimal reproduction of the problem with instructions**
   

- This first plunk illustrates the  scenario with an invalid dependency being requested by a component:

    https://plnkr.co/edit/am6Ggf61dVG7WLvT7aa3?p=preview

   Open the  browser's developer tools when you open the plunk and you should see  just a message
```

   bootstrapping ...
```
   To fix the bootstrapping issue,  comment lines 21 and 22 in src/app.ts
   ```

   // COMMENT ME TO FIX BOOTSTRAPPING ISSUE
  constructor(foo:bar){
  }
  ``` 

- This second plunk illustrates the scenario with an invalid template being used in an angular 2 component:

 https://plnkr.co/edit/pomPcakWVjWLfjVw8qSq?p=preview

 Open the  browser's developer tools when you open the plunk and you should see  just a message
```

   bootstrapping ...
```
   To fix the bootstrapping issue,  comment line  14 in src/app.ts
   ```

    <!-- COMMENT ME TO FIX BOOTSTRAPPING ERROR -->
      <BAD TEMPLATE div></div>
  ``` 
 

**What is the motivation / use case for changing the behavior?**
  
 Improve development experience

**Please tell us about your environment:**

* **Angular version:** 2.0.1

* **Browser:** all 

 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` = N/A

**Comment by btrigueiro** [comment]
+1

**Comment by btrigueiro** [comment]
Looks like it's the same as @angular/zone.js#446

**Comment by andrei-ivanovici** [comment]
Could be, but  the issue is still present in firefox, with the  exact same behaviour. If this were a chrome devtools problem, I'd expect firefox to work fine ... . I think this issue was introduced  with RC5, when ngModule was added. So,I'm not really sure ...  Also, the same problems are reported correctly  in a pure angular 2 app

**Comment by btrigueiro** [comment]
You're right, @andrei-ivanovici... that wasn't the real issue...
There was a `reject` missing. I'll submit a pull request later tonight.

**Comment by andrei-ivanovici** [comment]
Awesome, @btrigueiro . Thanks! :)

**Comment by andreialecu** [comment]
This bug should be a big priority. It makes upgrading angular1 apps close to impossible. 

I've had this happen from things like a `&dash;` being somewhere in a template, which in an angular2 bootstrapped app apparently errors out with this:

```
Error: Template parse errors:
	Unknown entity "dash" - use the "&#<decimal>;" or  "&#x<hex>;" syntax ("
	    <div>
	      <h2>Hello [ERROR ->]&dash; {{name}}</h2>
	    </div>
	  "): App@2:16
```

**But an `@angular/upgrade` app instead produces no error, it just fails to load altogether.**

This makes debugging pretty much impossible.

**Comment by andrei-ivanovici** [comment]
@andreialecu , in the meantime you can apply the patch  manually to your local installation. It's just one line of code (see changes in the associated pull request). I'm also surprised it's taking so long  to accept that pull request

**Comment by andreialecu** [comment]
@andrei-ivanovici Thanks, however it seems like this fix isn't complete. See my comment in https://github.com/angular/angular/pull/12232#issuecomment-255583738

**Comment by andrei-ivanovici** [comment]
just tried it out, it looks like the simplification to set  the reject util as the second argument doesn't fix the error. The original solution with the catch works. Give it a try  and let me know
here is the change :

```
             ngZone.onMicrotaskEmpty.subscribe({
                                    next: function (_) { return ngZone.runOutsideAngular(function () { return rootScope.$evalAsync(); }); }
                                });
                            })
                                .then(resolve, reject);
                        }).catch(reject);
```

**Comment by andreialecu** [comment]
Interesting, that does seems to work when not simplified. I wonder why, since they seem equivalent.

So I get an error logged for `&dash;` now with the change from @andrei-ivanovici, but the errors are logged several times. 

I had some errors that were filling the console up so much that it would crash it every single time I tried to load it.

Example from just the `&dash` case:

![image](https://cloud.githubusercontent.com/assets/697707/19626210/fcfd98d4-9934-11e6-8cee-eff6a9699d3f.png)

In an angular2 non-upgrade bootstrapped app, the error is much more concise.

**Comment by andrei-ivanovici** [comment]
maybe the error is thrown in the resolve handler, and  I suppose the  second argument  misses those errors. The catch will use the error handler on the resulting promise and that is why  I think these errors are caught. As for the stack,  It looks like there are log handlers in different points on the promise chain and  each will print its own contextual stack trace

**Comment by christopherthielen** [comment]
#11977 appears to be a duplicate

**Comment by chenbojian** [comment]
I am having this issue in angular 8. I am using version 8.1.2. Only a blank page when something wrong happened for angular 8 component.
