### ISSUE TITLE
package.json in 2.0.x branch is for the wrong version

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#12066]
If you generate Angular's API docs against a local copy of angular/angular that is pinned to the 2.0.x branch, the footer in the docs has the wrong version because 2.0.x has its package.json set to 2.1.0-beta.0, and we use the version from the package.json to construct the URL.

This should be fixed in the 2.0.x branch.

See https://github.com/angular/angular.io/issues/2536 for more context.

Note: this is not apparent in the live docs because I am manually changing the package.json -- this issue is a request to fix the part of our release process that sets the version in the package.json on the 2.0.x branch in this repository.

**Comment by vicb** [comment]
@naomiblack please add labels when creating an issue.

**Comment by IgorMinar** [comment]
obsolete
