### ISSUE TITLE
Angularfire 2 with angular2 problem

### ISSUE THREAD

**Issue by satyabratasenapati** [angular/angular#12065]
I have  a problem with npm installation of angularfire in angular2 released version.I have a attached snap of package.json and npm installation cmd mode
![npm angularfire 2](https://cloud.githubusercontent.com/assets/8910172/19073401/7d4829aa-8a58-11e6-9c13-8fc162c1d12c.jpg)

here is the package.json
![packagejson](https://cloud.githubusercontent.com/assets/8910172/19073419/96642772-8a58-11e6-9aaf-95c8513ee284.jpg)

Kindly give me the solution

**Comment by DzmitryShylovich** [comment]
Your question sounds like a support request.
Please use the issue tracker only for bugs and feature requests.
Use [gitter](https://gitter.im/angular/angular) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular2) for support request.

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich
