### ISSUE TITLE
canDeactivate executes while routing to routes guarded with canActivateChild

### ISSUE THREAD

**Issue by niyazhussain** [angular/angular#12069]
Hi ,below is my route

`export const ROUTES: Routes = [ { path: '', redirectTo:'signin' ,pathMatch: 'full' }, { path: 'signin', component: SigninComponent ,canDeactivate: [AuthGuard] }, { path: 'dashboard', canActivateChild: [AuthGuard], component: DashboardComponent, children: [ { path: 'category/:id', component: CategoryViewComponent }, { path: 'category', component: CategoryListComponent }, { path: '',redirectTo:'category', component: CategoryListComponent } ] } ];`

whenever i navigate to /dashboard the canDeactivate executes  , it should not execute right ? because i am navigating to different route unrelated to signin

**Comment by DzmitryShylovich** [comment]
Your question sounds like a support request.
Please use the issue tracker only for bugs and feature requests.
Use [gitter](https://gitter.im/angular/angular) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular2) for support request.

If you think it's a bug please fill the issue template and provide reproduction.

And pls format your code.

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich
