### ISSUE TITLE
Router animations events without $event

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#12068]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If i have component that is displayed by router and i want to use animations for this component i can do it by:

```typescript
@HostBinding("@flyInOut")
private get _pageAnimation(): boolean
{
    return true;
}
```

If i move this code to "base" class which is extended by my component it stops working. Im not sure if this is only problem of router animations, or `HostBinding`.

Also if use `HostListener` for listening to animation start event no event parameter is passed to this callback. 
```typescript
@HostListener("@flyInOut.start")
private _startAnimation(event: AnimationTransitionEvent)
{
    //event is undefined
}
```
**Expected behavior**
Both scenarios should work.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Win 10, VSCode, NPM, SystemJS, Asp.Net.Core

* **Angular version:** 2.0.1

* **Browser:** [all]

 
* **Language:** [TypeScript 2.0.3]

**Comment by DzmitryShylovich** [comment]
You should avoid component inheritance until https://github.com/angular/angular/issues/11606 will be resolved.

**Comment by pkozlowski-opensource** [comment]
Yeh, proper inheritance support needs to be designed and #11606 is tracking this. Closing as a duplicate. Thnx @DzmitryShylovich
