### ISSUE TITLE
Example links in directive.ts is outdated

### ISSUE THREAD

**Issue by fkolar** [angular/angular#12077]
In the angular-master/modules/@angular/core/src/metadata/directives.ts 

I just came to across to this:
```
### Example ([live demo](http://plnkr.co/edit/ivhfXY?p=preview))
```
Which is not valid for a while

Angular version the latest pull:

```
"name": "angular-srcs",
  "version": "2.1.0-beta.0",
  "private": true,
  "branchPattern": "2.0.*",
```

thanks, 
-FK

**Comment by vicb** [comment]
We are in the process of improving the docs. 

We track that internally.
