### ISSUE TITLE
<select multiple> in reactive forms

### ISSUE THREAD

**Issue by hanijizan** [angular/angular#12074]
Support for `<select multiple>` in reactive forms. 

**Current Behavior**
Following template of a standard App component:

```
<form [formGroup]="form">
    <select multiple formControlName="multiSelect">
        <option value="">Select Item</option>
        <option *ngFor="let item of items" [value]="item.value">{{item.name}}</option>
     </select>
</form>
```

Throws:

`zone.js:355 Unhandled Promise rejection: Error in ./App class App - inline template:3:23 caused by: values.map is not a function ; Zone: <root> ; Task: Promise.then ; ...`

Additionally, the control is never marked as invalid if `Validators.required` is added while creating the form. The following plunkr shows both issues: http://plnkr.co/edit/BXnhholfKnfMCAvT0j7q?p=info 

**Expected behavior**

1. The value of the associated form control should hold an array of items that are selected in the list or an alternate way of tracking selected items.
2. Applying validations to the element.

**What is the motivation / use case for changing the behavior?**
`<select multiple>` is a common HTML element, does angular2 team plan on supporting this element in reactive forms or is it supported already? If so, what's the correct implementation of this element in reactive forms?

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/12059#issuecomment-251375529

**Comment by pkozlowski-opensource** [comment]
And a fixed plunk: http://plnkr.co/edit/gZQSIvExZVz6OVsCkgA3?p=preview

@ericmartinezr was faster about 17 seconds :-)  @ericmartinezr I don't even know how to say "thank you" for all the hard work you do helping out with the issues! Great stuff.

**Comment by hanijizan** [comment]
Thanks for clarification, but still don't see the control being marked with `ng-invalid` although first item's value is an empty string. I removed the `value` attribute for that first option but it's still not marked as invalid. What's missing?
