### ISSUE TITLE
@angular/core/index"' has no exported member 'query'. Implementation of 'query()' Experimental API under development

### ISSUE THREAD

**Issue by NilsHolger** [angular/angular#12078]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The bug manifests itself in the developer tools and in the angular cli.
the developer tools say:
1. technology.component.ts:33Uncaught TypeError: __webpack_require__.i(...) is not a function
2. [WDS] Errors while compiling.
3. client?687b:76 [default] c:\Dev\angular2showcaseapp\src\app\technology\technology.component.ts:11:4 
Module '"c:/Dev/node_modules/@angular/core/index"' has no exported member 'query'

**Expected behavior**

This is a reporduction of the demo app on animations from angular connect.
I have searched for the query() function on the internet and in @angular and then copied those bits into my project.
It seems that http-lite server renders the web application but that angular-cli aot compilation also
complains that he cannot find the member 'query'.  In the @Component decorator the property animations the trigger then transition is invoking the query function passing in the #element and the style to apply to that element.. 

**Minimal reproduction of the problem with instructions**
Is it a bug or a feature request or just an implementation of the query() function in @angular?
import { query } from @angular/core
he can't find query

https://github.com/NilsHolger/angular2showcaseapp

**What is the motivation / use case for changing the behavior?**

The use case for changing this behavior is to have a richer animation experience in Angular.

**Please tell us about your environment:**

angular 2.0
angular-cli: 1.0.0-beta.16
node: 6.5.0
os: win32 x64

* **Angular version:** 2.0.X

Angular 2.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 53.0.2785.143 m
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0 ES6 Features
* **Node (for AoT issues):** `node --version` =   
NODE v6.5.0 on V8

**Comment by vicb** [comment]
IIUC this is an experimental feature by @matsko that has not been delivered not merged yet
