### ISSUE TITLE
The router fails to load child component in a specified named outlet

### ISSUE THREAD

**Issue by akorchev** [angular/angular#12072]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The router fails to load a child component in the specified outlet. The error is
`Cannot find the outlet secondary to load 'Child2Component'`. The configuration is as follows:

```JavaScript
  {
    path: 'nokcontainer', 
    component: OkcontainerComponent,
    children: [
      { path: 'foo', component: Child2Component, outlet: 'secondary' }
    ]
  }
```

The link that navigates to that route is 

```html
<a [routerLink]="['nokcontainer', { outlets: { secondary: 'foo'} }]">NOT OK</a>
```

**Expected behavior**

I expect the component to load in the specified outlet without an error.

**Minimal reproduction of the problem with instructions**

1. Go to http://plnkr.co/edit/2xOEn2nGMvnm5Rcbl4y1?p=preview
2. Click the "NOT OK" link. The component fails to load.

**What is the motivation / use case for changing the behavior?**

I want to load a component in an aux outlet. There isn't any obvious reason for this configuration to fail. The named outlet exists right next to the primary one. 

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by vsavkin** [comment]
The configuration tells the router to load `Child2Component` into `OkcontainerComponent`. The container component doesn't have any outlets, so the router throws.

If you change the template of the container component to be like that:

```
@Component({
  template: `OK Container component here!
  <hr>
  <router-outlet name="secondary"></router-outlet>
  `
})
```

everything will work. 

If your intent was for them to be siblings, you can do the following:

```
<a [routerLink]="[{ outlets: { primary: 'nokcontainer', secondary: 'foo'} }]">
```

```

const routes: Routes = [
  { path: 'nokcontainer', component: OkcontainerComponent },
  { path: 'foo', component: Child2Component, outlet: 'secondary' }
];
```

Closing this issue.

**Comment by akorchev** [comment]
Aha! @vsavkin does this mean that the router looks for named outlets only in the parent component (and not higher)? Does it apply for primary outlets too? I must have missed that in the documentation.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
