### ISSUE TITLE
Angular2 Tutorial HTTP Page 

### ISSUE THREAD

**Issue by joeyjgarcia** [angular/angular#12084]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Bug in the documentation of the Tour of Heroes Tutorial

**Expected behavior**

Tutorial should work on the HTTP page

**Minimal reproduction of the problem with instructions**

Copy the code on the HTTP page of the Tutorial page

**What is the motivation / use case for changing the behavior?**

Finishing the tutorial

**Please tell us about your environment:**

MacBook Pro El Capitan

* **Angular version:** 2.0.X

Yes

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome, all browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
5.11

On this page of the Tour of Heroes Tutorial
https://angular.io/docs/ts/latest/tutorial/toh-pt6.html

There is mention of an import in the app/app.module.ts (v2) file: 
import { InMemoryWebApiModule } from 'angular-in-memory-web-api';

It should be:
import { InMemoryWebApiModule } from 'angular2-in-memory-web-api';

per the package.json that has this dependency.
    "angular2-in-memory-web-api": "0.0.18",

Sorry if this comment is in the wrong page, but there is no other area that I could find easily.

**Comment by laco0416** [comment]
you should reopen this at https://github.com/angular/angular.io

**Comment by joeyjgarcia** [comment]
Done.  https://github.com/angular/angular.io/issues/2540
