### ISSUE TITLE
Dynamic component angular2 final

### ISSUE THREAD

**Issue by h2qutc** [angular/angular#12087]
Hi, 
I tried to create a component dynamic like that: 

<dynamic-html-outlet [src]="post.text"></dynamic-html-outlet>

Here is my file dynamicComponent.ts: 

import {Directive, Input, ViewContainerRef, Component, ReflectiveInjector, ComponentFactory, ComponentFactoryResolver} from '@angular/core';
export function createComponentFactory(resolver: ComponentFactoryResolver, metadata: Component): Promise<ComponentFactory<any>> {
    const cmpClass = class DynamicComponent {
    };
    const decoratedCmp = Component(metadata)(cmpClass);
    return new Promise((resolve) => {
        resolve(resolver.resolveComponentFactory(decoratedCmp)); 
    });
}
@Directive({
    selector: 'dynamic-html-outlet',
})
export class DynamicComponent {
    @Input() src: string;
    constructor(public vcRef: ViewContainerRef, public resolver: ComponentFactoryResolver) {
    }
    
    ngOnChanges() {
        if (!this.src) return;

        const metadata = new Component({
            selector: 'dynamic-component',
            template: this.src
        });
        createComponentFactory(this.resolver, metadata)
            .then(factory => {
                const injector = ReflectiveInjector.fromResolvedProviders([], this.vcRef.parentInjector);
                this.vcRef.createComponent(factory, 0, injector, []).changeDetectorRef.detectChanges();
            });
    }
}

If I declare this component in 'declarations' in the file app.module.ts, then I got this error: 
**EXCEPTION: Uncaught (in promise): Error: No component factory found for DynamicComponent**
If I declare in 'entryComponents' in the file app.module.ts, then I got an another error: 
**Uncaught Error: Could not compile 'DynamicComponent' because it is not a component.**
So, then I tried to change the annotation @Directive by @Component like: 
@Component({
    selector: 'dynamic-html-outlet',
Template: "<div></div>"
})

but I got this error: 

polyfills.js:3 Unhandled Promise rejection: Template parse errors:
Can't bind to 'src' since it isn't a known property of 'dynamic-html-outlet'.
1. If 'dynamic-html-outlet' is an Angular component and it has 'src' input, then verify that it is part of this module.
2. If 'dynamic-html-outlet' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

Can anyone help me or give me a tuto that explain how to create a dynamic component using Angular2 finale please?

**Comment by pkozlowski-opensource** [comment]
> Can anyone help me or give me a tuto that explain how to create a dynamic component using Angular2 finale please?

Sure, just turn for help to one of the existing support channels: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

GitHub issues are for bug reports and feature requests only, support requests are not answered here.

**Comment by DzmitryShylovich** [comment]
Please use the issue tracker only for bugs and feature requests.
Use [gitter](https://gitter.im/angular/angular) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular2) for support request.

If you think it's a bug pls fill the issue template and provide working reproduction in plunkr.

**Comment by h2qutc** [comment]
Finally, it worked fine for me thanks to this example: 
http://stackoverflow.com/questions/38888008/how-can-i-use-create-dynamic-template-to-compile-dynamic-component-with-angular/39912752#39912752

**Comment by h2qutc** [comment]
Finally, it worked fine for me thanks to this example: 
http://stackoverflow.com/questions/38888008/how-can-i-use-create-dynamic-template-to-compile-dynamic-component-with-angular/39912752#39912752
