### ISSUE TITLE
Use `Symbol` rather than `OpaqueToken`

### ISSUE THREAD

**Issue by blesh** [angular/angular#12082]
Given the use case for `OpaqueToken` it seems like you could do away with that type and use `Symbol` instead.  Symbols are immutable and unique, and the polyfills for Symbol are generally lightweight.

[More information on Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)

**Comment by blesh** [comment]
As mentioned in Slack:

Advantages to using Symbol:

- Symbols are completely unique and immutable, no one else's module can collide with your symbol.
- Symbols can be used directly as keys to hash tables (might improve your DI perf, depending on your impl)
- You'll be reusing a type that already exists in the language
- You can optionally provide symbols that can be shared globally with `Symbol.for`.

**Comment by laco0416** [comment]
Totally I agree on this. When I teach Angular to beginners, they ask me that many many times:

- "To create the key of provider, you should use `OpaqueToken`, instead of a string."
- beginner: "What's `OpaqueToken`?"
- "It's an Angular's API like ES6 `Symbol`."
- beginner: "Why don't we use `Symbol`?"

 I don't have any right answer. Why was it introduced? ES5 compatibility?

**Comment by HerringtonDarkholme** [comment]
I think the reason may be Dart compatibility. Dart has a [symbol](https://api.dartlang.org/stable/1.19.1/dart-core/Symbol-class.html) for minimizing string literal. (a `symbol` more like Lisp/Ruby's one than JS one)

And `operator ==` for Dart `Symbol` is comparing string content, not comparing identity. It's not `OpaqueToken` and ES6 `Symbol` do.

**Comment by tbosch** [comment]
We are planning to add a type to `OpaqueToken` so that we can type `Injector.get(myToken)` to not just return `any` but the right `type`. E.g.
```
const myTypedToken = new OpaqueToken<MyCar>('someName');

// variable myCar should be of type `MyCar` and not `any`
const myCar = injector.get(myTypedToken);

```

**Comment by blesh** [comment]
@tbosch so this runtime class exists to support build-time typing ergonomics? That doesn't seem good.

Why not just allow generics on the get method?

```ts
const symbol = Symbol.for('foo');
const thing = Injector.get<SomeType>(symbol);
```
vs

```ts
const token = new OpaqueToken<SomeType>('foo');
const thing = Injector.get(token);
```

**Comment by blesh** [comment]
I just think Symbol has a lot more advantages, and OpaqueToken didn't seem to add value over what symbol provides
