### ISSUE TITLE
IntelliSense errors while rebuilding application in Angular 2.0.0 version

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#12089]
I am trying to rebuild application with latest Angular 2.0.0 version and everything works fine except that there are some intellisense errors in observables. Is this an issue with rxjs module where the error is throwing. How can i get rid of these error:

For some reason i cannot paste image here so getting somethign went wrong while uploading so providing link to stackoverflow: 

http://stackoverflow.com/questions/39874609/intellisense-errors-while-rebuilding-application-in-angular-2-0-0-version

**Comment by DzmitryShylovich** [comment]
How is this related to angular?

**Comment by pkozlowski-opensource** [comment]
This is a support question that was already asked on SO so no need to duplicate it here. On top of this it doesn't seem to be related to Angular itself as pointed out by @DzmitryShylovich
