### ISSUE TITLE
Template Parsing error: binding data to data- attribute for JS plugin fails

### ISSUE THREAD

**Issue by tom10271** [angular/angular#12085]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I use ngFor to render images and bind image src to data- attribute like:
`data-flickity-bg-lazyload="{{ img | asset }}"`

The whole application fails to bootstrap with the following error messages:

```
Can't bind to 'flickity-bg-lazyload' since it isn't a known property of 'div'. ("         <div class="carousel-cell cover-container background-contain"
                             [ERROR ->]data-flickity-bg-lazyload="{{ img | asset }}"
                             *ngFor="let img of collect"): IdvComponent@49:29 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'flickity-bg-lazyload' since it isn't a known property of 'div'. ("         <div class="carousel-cell cover-container background-contain"
                             [ERROR ->]data-flickity-bg-lazyload="{{ img | asset }}"
                             *ngFor="let img of collect"): IdvComponent@49:29
```

**Expected behavior**
Angular 2 should still bind it if corresponding directive is not found.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/OB1GkanLO4Jh1XkN3Q1C?p=preview

**What is the motivation / use case for changing the behavior?**
To bind data to data- attribute for JS plugins

**Please tell us about your environment:**
MacOS X

* **Angular version:** 2.0.1

* **Browser:** [all]
 
* **Language:** [TypeScript 1.7.3]

* **Node (for AoT issues):** `node --version` =   v5.7.0

Thanks for investigating

**Comment by vicb** [comment]
The reason is `Can't bind to 'flickity-bg-lazyload' since it isn't a known property of 'div'`

What this means is that this property does not exist on your `div`

what you want to do is `<div [attr.data-flickity-bg-lazyload]="img | asset">`
