### ISSUE TITLE
Unable to use ContentChildren with ngForTemplate

### ISSUE THREAD

**Issue by colinkahn** [angular/angular#12094]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Getting directives with `@ContentChildren` does not work when the directives were created using `ngForTemplate`.

**Expected behavior**
Directives inside repeated templates using `ngForTemplate` should be picked up by `@ContentChildren` like they would if you were using `ng-content`.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/pt3fgjvL7yREdHKWl8IZ?p=preview

Check `src/app.ts`. You'll see that the `Marker` directive is being repeated by the template passed to `Repeater`, but `Repeater` cannot use `@ContentChildren` to query for `Marker`s.

**What is the motivation / use case for changing the behavior?**
In general, this seems like it should work. My specific use case is making a pair of components, each that use `ngForTemplate` with one used inside the others template. Together they allow filtering of a collection whose items have sub-items. One feature is that if all items have been filtered out (IE, no matching results) a message should be shown. I would assume the way to do this would be to query for items from the parent and subscribe to changes.

**Please tell us about your environment:**
Reproducible in Plunker.
- **Angular version:** 2.0.X
  2.0.1
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  Tested in Chrome
- **Language:** TypeScript 2
- **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
If you want to observe changes to directives rolled out by `ngFor` in your example, you would like to query for `ViewChildren` and not `ContentChildren`. In your plunker content is:

```
<template let-n>
    <marker>{{n}}</marker>
  </template>
```

while view:

```
<h2>Found {{markers?.length}} Marker Content Children</h2>
<template
  ngFor
  [ngForOf]="items"
  [ngForTemplate]="tmpl"></template>
```

**Comment by colinkahn** [comment]
@pkozlowski-opensource I suspected that, but tried that as well (see updated plunker: https://plnkr.co/edit/pt3fgjvL7yREdHKWl8IZ?p=preview).

If this is an issue with `ViewChildren` I'll update the issue to reflect that.

**Comment by timblakely** [comment]
I think I ran into this while exploring using `ViewChildren`/`ContentChildren` within custom structural directives. It appears `ViewChildren` and `ContentChildren` can't see into views created by `createEmbeddedView`. 

[Plunker here](https://plnkr.co/edit/FxmvTleSAsugxPVMznzD).

**Comment by Dunos** [comment]
So, there is still no way to use "ContentChildren" with views created using "createEmbeddedView"? @timblakely
