### ISSUE TITLE
search docs on quickstart page does not work

### ISSUE THREAD

**Issue by bastienJS** [angular/angular#12093]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
 
```

**Current behavior**
Go to: https://angular.io/docs/ts/latest/quickstart.html

**Expected behavior**

1. Enter any angular 2 term in the top left search docs text field
2. Nothing is found/triggered
3. seems the search is broken

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I want a working search...

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
I tried the search in latest FF and Chroem.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls re-open in https://github.com/angular/angular.io

**Comment by pkozlowski-opensource** [comment]
@bastienJS could you please open it at https://github.com/angular/angular.io where the documentation site lives? Thnx!
