### ISSUE TITLE
hgroup is not a known element

### ISSUE THREAD

**Issue by alsoicode** [angular/angular#12096]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When attempting to group header tags using an hgroup tag, the template parser returns an error: 'hgroup' is not a known element

**Expected behavior**

The hgroup tag should be a recognized HTML5 element by the template compiler.

**Minimal reproduction of the problem with instructions**

Just create a template and add:

    <hgroup><h1>foo</h1></hgroup>

**What is the motivation / use case for changing the behavior?**

I'd like to leverage the semantics of the hgroup tag.

**Please tell us about your environment:**

Windows 10, Visual Studio Code, TypeScript 2.0.3, WebPack 2

* **Angular version:** 2.0.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =

**Comment by manklu** [comment]
According to the standard hgroup is an obsolete feature and must not be used by authors.

https://www.w3.org/TR/html5/obsolete.html#non-conforming-features

**Comment by alsoicode** [comment]
How on Earth did I miss that! Blargh!

**Comment by manklu** [comment]
AFAIK It was initially part of HTML5 and was later removed ;-)

**Comment by alsoicode** [comment]
Obviously I need to do a better job of reading release notes. Thanks for the link though :)
