### ISSUE TITLE
Angular2 form template variable gets updated after click function gets triggered not before

### ISSUE THREAD

**Issue by vandanagopal** [angular/angular#12092]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In Angular2 the template variable that points to ngForm gets updated with my user action only after the angular event is triggered. Eg: If I uncheck a checkbox and I have a click event handler for it. When the event handler is called, the template variable that points to ngForm still has the stale value for the checkbox, i.e it says the checkbox is checked.

**Expected behavior**

The template variable that points to ngForm should get updated before the event handler is triggered.

**Minimal reproduction of the problem with instructions**
I have plunkr set up here: https://plnkr.co/edit/zUJmO3PTxsuJtxYikXKw?p=preview

**What is the motivation / use case for changing the behavior?**
When there is any change on the page by the user, I want to submit all form fields to the backend not as json but as request parameters, so that my legacy code can process the request as normal separate request parameters. The page is very dynamic, all fields are driven by metadata. It is not known upfront which fields are on the page so I want to submit all form fields  - I use UrlSearchParams to submit it as request parameters, but the value is stale as shown in the plunkr.

**Please tell us about your environment:**

OS: windows
IDE: Visual code
package manager: npm
Http server: lite server
* **Angular version:** 2.0.X
2.0.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, Edge, Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript. Have not tried others.
* **Node (for AoT issues):** `node --version` =   
4.6.0

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/Op6QiPo4mgp2IAY2Jmfg?p=preview

**Comment by kara** [comment]
@vandanagopal Thanks for the detailed issue. To clarify, in template-driven forms, the value is always updated asynchronously. This is necessary to avoid "changed after checked" errors in the template. Unfortunately, for that reason, the order can't be changed.  If you check the value next tick, it should work as expected (see [here](https://plnkr.co/edit/j8fzACfExvQ3czA16pLU?p=preview)). You also might consider switching to reactive forms, where the value is updated synchronously.
