### ISSUE TITLE
Angular 2 : Defer templateUrl loading until route activated

### ISSUE THREAD

**Issue by Exgaves** [angular/angular#12108]
**Current behavior**

When my application initially loads, all components in the routes have their templateUrl's resolved and loaded from the server. This means when a client comes to my server the async request cap is reached waiting for views that aren't being used instead of loading assets for the view that is currently activated.

**Expected behavior**

A components templateUrl loading is deferred until the route is first activated.  How can this be done? (Should this be done?)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

A browser has a limit on how many async requests can be pending. If the budget for this is used up loading views that aren't being shown instead of loading assets on the view that IS being shown then page loading speed is slowed.

**Please tell us about your environment:**

Angular 2 compiled with Typescript 2, running on NodeJS.
Components use templateUrl property which requests NodeJS server to render Jade templates

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> A components templateUrl loading is deferred until the route is first activated. How can this be done? 

https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load

**Comment by vsavkin** [comment]
The recommended way of shipping Angular 2 applications is using the AoT mode. When using this mode, we compile templates into JavaScript and bundle them up with the rest of the code. So templateUrl and template work the same way.

You should use lazy loading instead.

Closing this issue.
