### ISSUE TITLE
deep link feature promised but not implemented in tutorial

### ISSUE THREAD

**Issue by martyychang** [angular/angular#12107]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The [Routing Around the App](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html) chapter in the tutorial talks about a new requirement for deep linking.

> Clicking a _deep link_ in an email opens the detail view for a particular hero.

However, the sample code in the tutorial does not seem to be enough to actually implement this feature. Reaching the end of the chapter leaves me with an app that does _not_ support deep linking.

**Expected behavior**
Pasting a deep link like http://localhost:3000/detail/11 should take me to the hero detail view, but instead I get an HTTP 404 error.

**Minimal reproduction of the problem with instructions**
The [live example](https://angular.io/resources/live-examples/toh-5/ts/plnkr.html) linked from the chapter actually exhibits the same problem.

1. Open the [Routing Around the App](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html) chapter
2. Click the link in this sentence, "Run the [live example](https://angular.io/resources/live-examples/toh-5/ts/plnkr.html) for this part."
3. Click the button in the top-right corner of the preview frame to open the preview in its own window. You should see a URL like this: http://run.plnkr.co/qRrUMG91xG1WZaDA/dashboard
4. Reload the page (in Chrome, by right-clicking the page and clicking **Reload**). At this point you would expect the dashboard to appear but instead you will get an HTTP 404.

![image](https://cloud.githubusercontent.com/assets/6706834/19141747/a31c5650-8b5d-11e6-928e-5d6df050c70b.png)

**What is the motivation / use case for changing the behavior?**
I was excited to see deep linking included as part of the new Angular tutorial, since this is an expected feature of any web app. I believe this _should_ be included in the tutorial and would love to see the tutorial updated, so others learning Angular 2 can _really_ get a head start on building usable web apps.

**Please tell us about your environment:**

```bash
# Mac OS X El Capitan 10.11.6
node --version  # 5.6.0
npm --version  # 3.6.0
```

* **Angular version:** 2.0.0-beta.17
I assume this is still a problem since the "live example" exhibits the same issue.

* **Browser:** Chrome 53.0.2785.116 (64-bit)
 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =   5.6.0

**Comment by zoechi** [comment]
Documentations issues should be opened in https://github.com/angular/angular.io/issues

**Comment by pkozlowski-opensource** [comment]
Yup, this belongs to https://github.com/angular/angular.io/issues, please re-open in there.

**Comment by martyychang** [comment]
Thanks for the tip @zoechi @pkozlowski-opensource I've created the issue https://github.com/angular/angular.io/issues/2555 now in the correct repo.
