### ISSUE TITLE
Function in route generation causes lazy module to be unreachable

### ISSUE THREAD

**Issue by j3ddesign** [angular/angular#12113]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using a function to tidy route generation, eg:
```
const LazyRoute = (path: string, moduleName: string, dir?: string) => ({
  path: path,
  loadChildren: `app/core/+${dir ? dir : path}/${dir ? dir : path}.module#${moduleName}`
});
const LAZY_ROUTES = [
  LazyRoute('moderators', 'ModeratorModule'),
  LazyRoute('settings', 'SettingsModule'),
  LazyRoute('blog', 'BlogModule'),
  LazyRoute('help', 'HelpModule'),
  LazyRoute('wishlist', 'WishlistModule'),
  LazyRoute(':name', 'DashboardModule', 'dashboard')
];
```
The above setup logs out correctly, and should be functional, however routing to the module causes 'module cannot be found' errors (while giving the correct path in the error log)
eg: `Error: Cannot find module 'app/core/+settings/settings.module'.`

I have copied the outputs from these functions and used them directly in the route configs, instead of abstracting to functions, and the app successfully loads and runs perfectly.

**Expected behavior**
I would expect to be able to abstract repetitive route definitions to a function, to allow for a better, cleaner DX.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

To provide a better DX when creating many routes. It's much nicer to be able to generate these with a custom function, than having the complete route definition boilerplate repeated.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular 2.0.0
Angular CLI: 1.0.0-beta.16

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 55.0.2880.4 canary
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Can you reproduce in plunkr? Issue might be related to cli.

**Comment by j3ddesign** [comment]
I'll see what I can do, I'm actually pretty sure it'll be CLI related, so not sure how successful a plunkr will be, but we'll see :)

**Comment by DzmitryShylovich** [comment]
So pls re-open in cli repo https://github.com/angular/angular-cli/issues

**Comment by j3ddesign** [comment]
Moved to angular/angular-cli#2546
