### ISSUE TITLE
Input testing issue: `triggerEventHandler('input')` doesn't trigger `ngModelChange` when an input is inside a form

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#12112]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Hi, when testing components with forms, I am able to trigger input changes if the input is inside a form otherwise (if the input is inside a form), the input event doesn't trigger ngModelChange.

Here's a plunker with Angular 2.0.1 reproducing the error:
https://run.plnkr.co/plunks/jXLF2H/

**Comment by kara** [comment]
@yjaaidi When you're using ngModel in a form, its initial registration occurs asynchronously (to preserve unidirectional data flow). As such, you'll have to call "tick()" in your fakeAsync zone to ensure that the form control and its events are set up before you change the value.

See updated plunker example here: http://plnkr.co/edit/Pk7Ic6YRJm82kgMEo5T9?p=preview

**Comment by yjaaidi** [comment]
Sorry for responding so late but thanks for the trick @kara !

Shouldn't we add this to the testing documentation?
