### ISSUE TITLE
Pristine state and class not removed when value changed via ngMode on input

### ISSUE THREAD

**Issue by apavillet** [angular/angular#12116]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I Hope it was not yet mentionned, I could not find it in the issues.
When the value of an input is changed via ngModel, pristine state is not removed

**Expected behavior**

Since the doc says pristine is "Control's value has changed" I'd expect pristine to be removed

**Minimal reproduction of the problem with instructions**

See Plunkr below, click on setName, pristine is not changed, but if you type anything in the box the pristine state is removed

http://plnkr.co/edit/Y0NVt53PxuS9wP24RnpI?p=preview

**What is the motivation / use case for changing the behavior?**

In my case pristine is used for css and informational purpose on the ux side

**Please tell us about your environment:**
Max OS X, Chrome latest

* **Angular version:** 2.0.X

* **Browser:** Tested in Chrome only, I do not expect the browser to change anything on this but could test more if needed
 
* **Language:** Typescript

**Comment by pkozlowski-opensource** [comment]
> See Plunkr below, click on setName, pristine is not changed, but if you type anything in the box the pristine state is removed

This works like intended. `pristine` flag is here to reflect _user interaction_ and not model mutation. Since you are mutating model programatically you can already set any arbitrary flag and use it to set appropriate classes.

**Comment by apavillet** [comment]
Ok thanks @pkozlowski-opensource, should I close this then ?

I'd expect the model mutation to be reflected but I guess it's a decision already made, maybe then the small change would be to change "Control's value has changed	" to "Control's value has changed	via user interaction"  in https://angular.io/docs/ts/latest/guide/forms.html

Thanks

**Comment by DzmitryShylovich** [comment]
> should I close this then ?

yeap
