### ISSUE TITLE
Using template strings in templateUrl-property of component

### ISSUE THREAD

**Issue by yoerlemans** [angular/angular#12111]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using template strings ( `` or backticks) to fill out a component's template url, it just uses the string as the template.

**Expected behavior**
When filling out the template url with any kind of string, I would suppose it uses that string as url.

**Minimal reproduction of the problem with instructions**
Make a component like this:
~~~~
import { Component } from '@angular/core';

@Component({
    templateUrl: `my.component.html`
})
export class MyComponent {
}
~~~~
The content of the component shall be the literal string _my.component.html_

**What is the motivation / use case for changing the behavior?**
Maybe using a variable to base your template url on, I didn't really need it but to me it seems logical to be able to use any kind of string as templateUrl.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Only tested Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/Oy1PwY3XghsuhJKYocIw?p=preview
works as intended.

**Comment by pkozlowski-opensource** [comment]
Can't reproduce: https://plnkr.co/edit/8r8AwdJRFbnRDXY88Zhh?p=preview

Please add reproduce scenario in a plunker as requested in the issue template.

**Comment by yoerlemans** [comment]
Weird, I tried it with a couple of components in my application, all the same outcome. I'm using angular-cli to build the application. Could that cause it?

**Comment by pkozlowski-opensource** [comment]
>  I'm using angular-cli to build the application. Could that cause it?

Maybe. You will have to investigate more, narrow it down and eventually open an issue at https://github.com/angular/angular-cli/issues
