### ISSUE TITLE
low priority- (sp) "prolyfill"

### ISSUE THREAD

**Issue by kgentes** [angular/angular#12119]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Error should say "**polyfill**", not **prolyfill**"
	               ` throw new Error('Angular requires Zone.js prolyfill.');`

**Expected behavior**
Angular app builds fine (with webpack etc)
When it is run, it should produce error such as : 
	               ` throw new Error('Angular requires Zone.js polyfill.');`
 
**Minimal reproduction of the problem with instructions**

1. Build an Angular 2 application
2. Don't use NgZone in any constructors
3. Remove import 'zone.js/dist/zone'; from the main.ts

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7 SP1, Webstorm, 

* **Angular version:** 2.0.1
latest

* **Browser:** [Chrome]

 
* **Language:** [TypeScript 2.0]

* **Node (for AoT issues):** `node --version` =   6.7.0

**Comment by vicb** [comment]
prollyfill = probably a polyfill ie you can not polyfill something that is not a standard yet

**Comment by johnpapa** [comment]
LOL
