### ISSUE TITLE
docs for @angular/common directive ng-container

### ISSUE THREAD

**Issue by Koslun** [angular/angular#12114]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

No docs for ng-container. It is however used in the API documentation for:
* [NgPluralCase](https://angular.io/docs/ts/latest/api/common/index/NgPluralCase-directive.html)
* [NgPlural](https://angular.io/docs/ts/latest/api/common/index/NgPlural-directive.html)
* [NgSwitch](https://angular.io/docs/ts/latest/api/common/index/NgSwitch-directive.html) - where it is mentioned "use a ng-container to group multiple root nodes", as referenced in this [stackoverflow answer](http://stackoverflow.com/a/39743458/1825329).

**Expected behavior**

There should be a separate entry in the angular docs, presumably under the section @angular/common, where it is listed as a directive along with whether it is stable or experimental.

**Minimal reproduction of the problem with instructions**

Search or look through the [docs site](https://angular.io/docs/ts/latest/api/).

**What is the motivation / use case for changing the behavior?**

Given that it is presumably a public directive it would be good to know its usage as well as its stability.

**Please tell us about your environment:**

* **Angular version:** 2.0.1

* **Browser:** [all ]

 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls re-open it at https://github.com/angular/angular.io where the documentation site lives. Thx.

**Comment by Koslun** [comment]
@DzmitryShylovich Will do.
