### ISSUE TITLE
Improve template directives' ability to handle no attribute-value

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1213]
If I type `*for`, or any template directive, without an attribute value, it will error with `Cannot read property 'split' of null`.

It should give me a proper error.

You might ask, "But Andrew, how can you forget to provide an attribute value?"

Well, I forgot my leading quote: `<div *for=#item of items"></div>`

**Comment by naomiblack** [comment]
closing as a duplicate of #2014
