### ISSUE TITLE
Enable resolving data into loadChildren — dynamically loaded modules.

### ISSUE THREAD

**Issue by nikkwong** [angular/angular#12144]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

It seems that data can not be resolved into dynamically loaded modules.

```
@Injectable()
export class ResolveFn implements Resolve<any> {

  constructor() {}

  resolve() {

    return new Promise((resolve, reject) => resolve('string'));

  }

}

const routes: Routes = [
  {
    path: '',
    component: SomeComponent,
    children: [
      {
        path: '',
        component: Component
      },
      {
        path: 'somePath',
        resolve: {
           data: ResolveFn
        },
        loadChildren: 'some.dynamicModule#dynamicModule'
      }
    ]
  }
]
```

dynamicModule Component: 

```
ngOnInit() {
 this.activatedRoute.data.value; // undefined
```

Is there support planned for this?

**Comment by DzmitryShylovich** [comment]
`this.activatedRoute.data` is an observable.

**Comment by nikkwong** [comment]
It is an observable yes, but they've plucked data off it directly in the docs—and I've done so with inter-module routing. It's when we try to resolve data between modules that the value is lost.

**Comment by DzmitryShylovich** [comment]
Can you provide reproduction in plunkr?

**Comment by nikkwong** [comment]
Not having much luck with the plnk, but this should hopefully illustrate the problem:

https://plnkr.co/edit/lTJtyTgYGYAvMCoXtvSk?p=preview

Thanks.

**Comment by DzmitryShylovich** [comment]
@nikkwong pls add steps to reproduce and expected behavior (plus looks like you have an infinite loop)

**Comment by DzmitryShylovich** [comment]
@nikkwong you have a lot of errors in your code https://plnkr.co/edit/znBxTOoDfZCiyn0aTcZq?p=preview

@pkozlowski-opensource can be closed

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich
