### ISSUE TITLE
bug(AOT) No provider for PreloadAllModules! in AOT mode only

### ISSUE THREAD

**Issue by qdouble** [angular/angular#12141]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
If you use PreloadAllModules in your RouterModule config, it will create an `No provider for PreloadAllModules!` after compiling and building with AOT, works perfectly fine in JIT mode.
https://github.com/qdouble/angular2webpack2-starter/blob/bare-minimum/src/app/app.imports.ts#L8

**Expected behavior**
Should work without error in AOT and JIT mode.

**Minimal reproduction of the problem with instructions**
I tried to create a minimal branch to reproduce the error here: https://github.com/qdouble/angular2webpack2-starter/tree/bare-minimum

Just use git `clone -b bare-minimum https://github.com/qdouble/angular2webpack2-starter.git` to clone branch.
After install, you can use `npm run compile:dev` to reproduce the error. Then you can start the server with `npm run prodserver` to see the error in the browser.

To create JIT build, you can just use `npm start` for dev server or `npm run build && npm run prodserver ` to see it work fine without any errors in JIT mode.

If you remove PreloadAllModules here https://github.com/qdouble/angular2webpack2-starter/blob/bare-minimum/src/app/app.imports.ts#L8 AOT mode will compile and boot fine.

**Please tell us about your environment:**
OSX

* **Angular version:**  2.1.0-rc.0
Router: 3.1.0-rc.0

* **Browser:** [all]
 
* **Language:** [TypeScript 2.0.3]

* **Node (for AoT issues):** `node --version` =   6.6.0

**Comment by DzmitryShylovich** [comment]
> Angular version: 2.1.0-rc.0
Router: 3.1.0-rc.0

Can also reproduce with the latest changes from master.

**Comment by qdouble** [comment]
This appears to be fixed in the latest release.
