### ISSUE TITLE
can't populate ViewChildren QueryList with children directives on init

### ISSUE THREAD

**Issue by valentin78** [angular/angular#12142]
Here you can see the problem, the event does not fired on init (see console)
but if child change visibility status, event fired

http://plnkr.co/edit/ObE3ar?p=preview

and, in RC4 I have constructor parameter
@ViewQuery(TemplateSectionItem) childrenSections: QueryList<TemplateSectionItem>
and list success populated, now  childrenSections instantiated, but never populated

**Comment by woppa684** [comment]
The list IS populated! You subscribe to changes so you only get a notification when the list changes ... If you would for example put a 

```
console.log(this._vChildren);
```

in your ngAfterViewInit method you would see that the list contains 3 items already ...

**Comment by pkozlowski-opensource** [comment]
@woppa684 is right - you are subscribing to changes after the initial change was done. Closing as it works as expected.

**Comment by valentin78** [comment]
but what about get list in constructor? as it was before in RC4?
how can I subscribe on event, if instance exist after list already populated?

**Comment by pkozlowski-opensource** [comment]
> but what about get list in constructor? 

Nope, that won't work as at this point children of a component were not processed, change detection didn't run etc.

> how can I subscribe on event, if instance exist after list already populated?

In the `ngAfterViewInit` you've got access to the initialized list and can subscribe to changes. Which means that you've got bot state on component initialization and access to subsequent mutations. What is the other part that you are missing?

Maybe you should describe your functional use-case?

**Comment by valentin78** [comment]
> Maybe you should describe your functional use-case?
agree
I have some component with children directives, that I should get to render other dynamic components, otherwise I should get ElementRef[] for these children components
BUT! In constructor i replace Component.instance via return someObject; 
So in this way I before in RC4 get instance in constructor, subscribe on change event and when list populated I render dynamic components in these children directives

**Comment by valentin78** [comment]
to clarify, i replace component instance because i need replace component data context singleton for many components on page

**Comment by valentin78** [comment]
now i made so
class SectionComponent {
            @ViewChildren(SectionLoader)
            private viewChildren: QueryList<SectionLoader>;

            constructor(    ) {
                componentInstance.__proto__ = this;
                return componentInstance;
            }
            ngAfterViewInit() {
                onChildSectionsLoaded(this.viewChildren);
            }
        };
but i think is not correct because componentInstance one object for many components on page
I'm afraid the behavior will be unpredictable

**Comment by valentin78** [comment]
I hope for your help on the current problem?

**Comment by zoechi** [comment]
For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
