### ISSUE TITLE
Proposal: Rename `@Host` decorator to appropriate name

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#12140]
**Summary**:  `@Host` is not intuitive name. It should have a name that can tell its actual behavior.
## Problem

Currently, Angular has many decorators for dependency injection. Most of them are named nicely to explain its own job.
- `@Optional()`: Marks a dependency as optional.
- `@SkipSelf()`: Dependency resolution should start from the parent injector.
- `@Self()`: Retrieve a dependency only from itself.

They are very intuitive. But `@Host` is very complex against its name.
- `@Host()`: Retrieve a dependency from any injector until reaching the host element of the current component.

There are two problems at least.
1. The name doesn't tell us that it doesn't work for regular providers. (only for`viewProviders`)
2. The name, `host`, is used in `@Directive.host`.
## Proposal

I'm not sure what name is the most appropriate. My ideas:
- `@ViewInject()`: `providers <--> @Inject` and `viewProviders <--> @ViewInject` 
- `@HostViewInject()` 
- `@UntilHost()`

**Comment by vicb** [comment]
`@Self` -> `@LocalScope`
`@Host` -> `@ComponentScope`

**Comment by laco0416** [comment]
`Scope` is not a good name, I think. It has much meaning in Angular context.

**Comment by tbosch** [comment]
Too much meaning...
