### ISSUE TITLE
Testing a service with TestBed and angular 2.0.1

### ISSUE THREAD

**Issue by jcamus** [angular/angular#12149]
Hello,
I am still fighting with testbed to test my service. Here I have no component to test but just a service with mocks (because this service needs other service via injection). 
I have during inject : services are null...

Here a sample of my non working test :

```
describe('LoginService tests', () => {
		let service: LoginService;
		let tokenHandler: HTML5StorageService;	

		beforeEach(() => {		

			console.log('*** before each !!');			

			TestBed.configureTestingModule({
				providers : [
					{provide : LoginService, userValue : LoginService },					
					{provide : XHRBackend, userValue : MockBackend}					
				]
			});		
           });   
it('test1....', async(() => {
			TestBed.compileComponents().then(inject([LoginService, XHRBackend], (service : LoginService, mockBackend: MockBackend) => {
			console.log('**** inject it1 mockBackEnd =' + mockBackend);
			console.log('**** inject it1 service =' + service);
}));
		}));

I have following output :

LOG: '**** inject it1 mockBackEnd =null'
LOG: '**** inject it1 service =null'

Please help! Why injection is not working?



```

**Comment by gund** [comment]
Hi,

Problem probably in your object passed to `TestBed.configureTestingModule()`, and particularly in property `userValue`.  
I think you want `useValue` or even `useClass` in this case will be best match.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
