### ISSUE TITLE
Cannot have custom UrlResolver with latest version

### ISSUE THREAD

**Issue by rsambathkumar** [angular/angular#12155]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

We have CustomUrlResolver in our project where we do manipulation to templateURL and it was working before with RC. Something similar to https://github.com/angular/angular/blob/f7ff6c5a129f56723a8ef564de2b1e166d264554/modules/%40angular/examples/compiler/ts/url_resolver/url_resolver.ts

**Expected behavior**

This should replace the URL with logic mentioned in Custom code

* **Angular version:** 2.0.1

**Comment by DzmitryShylovich** [comment]
Can you provide a minimal reproduction in plunkr?

> with RC

rc5 and lower?

**Comment by rsambathkumar** [comment]
Here is the Plunker https://plnkr.co/edit/aYpdEugeSryZVEu96DwT?p=preview

You can see the templateUrl is defined as "hello.html" in main.ts and is manipulated dynamically in customUrlResolver.ts

**Comment by vicb** [comment]
Because the `UrlResolver` is used by the compiler, you have to provide them earlier than in your module, at bootstrap time.

In your app.ts:
```typescript
platformBrowserDynamic().bootstrapModule(AppModule, {providers:   
  [
    { provide: UrlResolver, useClass: CustomUrlResolver }
  ]});
```

**Comment by silentFred** [comment]
@vicb for the life of me I cannot get this to work in the latest version (4.2.4). So you perhaps know if anything changed regarding providing your own implementation for overloading component asset urls?

Regards
