### ISSUE TITLE
Problems using angular router 3.0.0-rc.1 with angular 2 v2.0.1

### ISSUE THREAD

**Issue by johlize** [angular/angular#12159]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using npm to install angular/routing 3.0.0-rc.5, our local router.d.ts has the following import statement:
import { ComponentResolver, Injector, NgModuleFactoryLoader, Type } from '@angular/core';

The file in the latest angular router.ts has the following import statement:
import {Compiler, ComponentFactoryResolver, Injector, NgModuleFactoryLoader, ReflectiveInjector, Type} from '@angular/core';

This causes problems when we try to run angular 2 v2.0.1. To solve the problem we reverted to angular 2 v2.0.0-rc.5

**Expected behavior**

The import statements would match.
**Minimal reproduction of the problem with instructions**
download the following dependencies 
"@angular/common": "2.0.1",
"@angular/compiler": "2.0.1",
"@angular/core": "2.0.1",
"@angular/forms": "1.0.1",
"@angular/http": "2.0.1",
"@angular/platform-browser": "2.0.1",
"@angular/platform-browser-dynamic": "2.0.1",
"@angular/router": "3.0.0-rc.1"

**What is the motivation / use case for changing the behavior?**

to use that latest angular v2.0.1 with the router 
**Please tell us about your environment:**

Windows, IntelliJ, npm
* **Angular version:** 2.0.X

2.0.1
* **Browser:** [Chrome ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> angular/routing 3.0.0-rc.5

there's no such module.

**Comment by johlize** [comment]
sorry,angular/router 3.0.0-rc.1

**Comment by pkozlowski-opensource** [comment]
> sorry,angular/router 3.0.0-rc.1

Why would you like to stick to 3.0.0-rc.1? If you are on the angular 2.0.1 just use stable release (3.0.1). 

We are not going to patch 3.0.0-rc.1 so I'm going to close this issue. Migrate to the stable version of the router.
