### ISSUE TITLE
console.log breaks sites on older IEs

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#12169]
Angular has references to `console` in 2 places:
-  [facade/src/lang.ts](https://github.com/angular/angular/blob/f5b0e22d352fd00cee1dc9016e85bdef94256e62/modules/%40angular/facade/src/lang.ts#L220-L226)
- [src/browser/browser_adapter.ts](https://github.com/angular/angular/blob/master/modules/@angular/platform-browser/src/browser/browser_adapter.ts#L79-L89) 

Presence of `console` in those places breaks sites on IE9. There are several things that we can / need to do here:
- decide if we need / want to have references to `console` in 2 different places (a comment in `browser_adapter.ts` would suggest that not
- do we want to work-around this in Angular or not. If we decide that people "just should use a polyffill" we should change / open an issue to change https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by trotyl** [comment]
Has been fixed by https://github.com/angular/angular/pull/12348. (facade being removed already)
