### ISSUE TITLE
Using Chrome visite (https://angular.io/ ), occurred some Error!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [angular/angular#12163]
just like this, what's wrong with that?

> Chrome 53.0.2785.143 m (64-bit) Windows10 x64

![bug](https://cloud.githubusercontent.com/assets/18028768/19208267/c621a1ea-8d2a-11e6-95c3-a03f181a4f7e.PNG)

**Comment by xgqfrms-GitHub** [comment]
中文  translate version is not native！

**Comment by IgorMinar** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

https://angular.io/docs/ts/latest/quickstart.html works just fine for me. If the problem persists please open a new issue and provide steps to reproduce and version number of your browser. thanks
