### ISSUE TITLE
bug(router): do not update primary route if only secondary outlet is changed

### ISSUE THREAD

**Issue by mucer** [angular/angular#12168]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If I change the secondary route, the primary route is cleared in some cases:
The ParentComponent holds 2 outlets, "primary" and "aux":

URL /parent/child
primary: child
aux: empty

Navigate "aux" to "child2"
--> URL /parent/(aux:child2)
 
The problem is, that the primary route is one big SegmentGroup. If the primary route is split into 2 SegmentGroups ("/parent/(child)", see Plunkr), everything works as expected.

**Expected behavior**

Only the secondary route should change.

Navigate "aux" to "child2"
--> URL /parent/(child//aux:childs)

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/ZOwJcEzJtb6iHMcUHfrz?p=preview

**What is the motivation / use case for changing the behavior?**

I have a outlet called "modal" which I use to show modals. If a add content to the modal outlet, the current primary route should not change.

**Please tell us about your environment:**

OSX, Chrome + Safari
Windows 10, Chrome + Firefox

* **Angular version:** 2.0.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by laco0416** [comment]
is this solved?

**Comment by mucer** [comment]
Yes, the PR was merged and the plunk is working.
