### ISSUE TITLE
Problem with @ContentChildren and injection of parent directive to child directive

### ISSUE THREAD

**Issue by fshchudlo** [angular/angular#12167]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

This is the sample code from [ContentChildren documentation](https://angular.io/docs/ts/latest/api/core/index/ContentChildren-decorator.html) with one modification - child directive injects `SomeDir` via constructor:
```javascript
import { AfterContentInit, ContentChildren, Directive, QueryList } from '@angular/core';

@Directive({selector: 'child-directive'})
export class ChildDirective {
    constructor(private someDir: SomeDir)
    {}
}
@Directive({selector: 'someDir'})
export class SomeDir implements AfterContentInit {
  @ContentChildren(ChildDirective) contentChildren: QueryList<ChildDirective>;
  ngAfterContentInit() {
    // contentChildren is set
  }
}
```

If you run this, you will get:

`metadata_resolver.js:508Uncaught Error: Can't resolve all parameters for ChildDirective: (?).`

If you swap directives declarations you will get:
`metadata_resolver.js:639Uncaught Error: Can't construct a query for the property "contentChildren" of "SomeDir" since the query selector wasn't defined.`

**Expected behavior**

Not fail

**Minimal reproduction of the problem with instructions**

Use the code above with:

- angular 2.0.0
- angular-cli 1.0.0-beta.16

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0

Did not find any similar issue

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3
* **Node (for AoT issues):** `node --version` =   6.7.0

**Comment by ericmartinezr** [comment]
This part 

```
constructor(private someDir: SomeDir)
    {}
```
It's not part of the example. Anyway the problem is explained in this article http://blog.thoughtram.io/angular/2015/09/03/forward-references-in-angular-2.html

For more info about asking https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by fshchudlo** [comment]
Ok, I'll close this issue.
Thanks for a quick response.
