### ISSUE TITLE
:host:before doesn't work

### ISSUE THREAD

**Issue by Michael77** [angular/angular#12165]
**I'm submitting a
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
using the css selectors :before and :after (and the :: versions) doesn't work on :host. I have also tried applying them with `:host(:before)` or `:host(::before)`

**Expected behavior**
:host(:before) or :host:before should add the ::before element into the DOM

**Minimal reproduction of the problem with instructions**

1. create component with stylesheet
2. add :before or :after styles with :host:before or :host::before
3. don't see those styles show up

**What is the motivation / use case for changing the behavior?**
It is undocumented, so perhaps it is a bug

**Please tell us about your environment:**

* **Angular version:** 2.0.2

* **Browser:** Chromium 53
 
* **Language:** TypeScript 2.0.2

* **Node (for AoT issues):** `node --version` =  v6.7.0

**Comment by micronyks** [comment]
It would be great if you can provide plunker or something which demonstrates your issue?

**Comment by skreborn** [comment]
This happens because Angular translates `:host:before` to `:before[_nghost-emt-x]`, while the correct order would be `[_nghost-emt-x]:before`. As far as I can tell, this happens with any pseudo-selectors used together with `:host`. See [plunker](http://plnkr.co/edit/89ckPp3XXVKrIEJxdmYB?p=preview).

**Comment by vicb** [comment]
Probably linked to a change I made recently to have tag selectors appear before the shim attribute selector

**Comment by krassx** [comment]
Seems like a problem still exists. Here is a plunker: https://plnkr.co/edit/OmQjUQALRjZWvULAr1nz?p=preview

:before pseudo element is not handled properly there.
