### ISSUE TITLE
(feature) i18n : text formatting as reference cause translation to crash when mangled

### ISSUE THREAD

**Issue by ruffiem** [angular/angular#12177]
**I'm submitting a ...**  (check one with "x")
feature request

**Current behavior**
When using dev and prod environments, the minification / uglification / mangling w/e to generate a performance wise bundle causes the translation to crash.

**Expected behavior**
Refering to the string in a case-sentitive manner instead of the formatting

**Minimal reproduction of the problem with instructions**
https://github.com/ruffiem/angular2-seed

**What is the motivation / use case for changing the behavior?**
When developing, mangling is to avoid in order to keep bug tracking simple. On prod, everything must be done to engage performance wise practices. If the translation id is based on the formatting of the textnode, then we must bypass minification/uglification which is a must have.
- **Angular version:** 2.0.X
  2.0.2
- **Language:** all

**Comment by vicb** [comment]
relates to https://github.com/angular/angular/issues/11679 (ie Angular would trim WS making minification useless)

**Comment by ocombe** [comment]
I believe that this is no longer an issue. Let me know if we need to reopen the bug.
