### ISSUE TITLE
Equivalent to 'AttachAware' in Dart Ng1?

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1217]
In Angular 1, `AttachAware` is used to be notified when the first stabilization has happened, and on all setters _can_ have been called at least once (if non-nulls values are ready), e.g.:

```dart
@Component(
  map: const {
    'model': '=>!model'
  }
)
class MyComponent implements AttachAware {
  Model model;

  @override
  void attach() {
    assert(model != null);
    doSomethingWithModel(model);  
  }
}
```

Is there a migration path off of this? As of now, there would have to be semi-complex setter logic:

```dart
@Component(
  bind: const {
    'field1': 'field-1',
    'field2': 'field-2'
  }
)
class MyComponent {
  var _field1;
  var _field2;

  void set field1(value) {
    _field1 = value;
    if (_field1 != null && _field2 != null) {
      doSomethingRequiringBothFields();
    }
  }

  void set field2(value) {
    _field2 = value;
    if (_field1 != null && _field2 != null) {
      doSomethingRequiringBothFields();
    }
  }
}
```

++ @yjbanov

**Comment by yjbanov** [comment]
The replacement is the `onChange()` method, which guarantees that all bindings were passed and will not be called again until new values are passed to the component. This happens at most once per browser event (due to single-flush cycle restriction):

```dart
@Component(
  bind: const {
    'model': 'model'
  }
)
class MyComponent {
  Model model;

  void onChange() {
    assert(model != null);
    doSomethingWithModel(model);  
  }
}
```

NOTE: it is currently a convention; there's no interface you have to implement; in the future, we will introduce an interface for soundness.

**Comment by matanlurey** [comment]
:+1: Thanks!

**Comment by matanlurey** [comment]
Re-opening: `onChange` can happen more than one time, right?

**Comment by yjbanov** [comment]
Correct, but only once per browser event and only if anything _new_ is passed.
