### ISSUE TITLE
Angular-Cli using wrong path

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular#12176]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When trying to perform an AOT compilation, I get an error:

> Error: Compilation failed. Resource file not found: C:/Users/George/Source/Repos/docs/client/components/home/client/components/home/home.html

when the home.html file is at `C:/Users/George/Source/Repos/docs/client/components/home/home.html`, so the compiler is getting the paths wrong, despite tsc working fine...

**Expected behavior**
ngc would work as advertised/described in the docs

**Minimal reproduction of the problem with instructions**

I haven't successfully use the compiler yet, so not sure where the issue is, but clone my repo at http://github.com/georgeedwards/docs and then run ngc in the client directory. 

**What is the motivation / use case for changing the behavior?**
Getting ngc to work

**Please tell us about your environment:**

Windows 10 Pro

* **Angular version:** 2.0.X
2.0.2

* **Browser:** all

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.7.0

here's my tsconfig-aot.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "types": []
  },
    "exclude": [
        "../node_modules"
    ],

  "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : true
 }
}
```

**Comment by DzmitryShylovich** [comment]
Pls re-open in the cli repo https://github.com/angular/angular-cli/issues
