### ISSUE TITLE
AOT: Inherited lifecycle callbacks are not called

### ISSUE THREAD

**Issue by kemsky** [angular/angular#12175]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Lifecycle callbacks do not depend on metadata, thus it is separate issue.
See [comment](https://github.com/angular/angular/issues/11060#issuecomment-242507385).

**Expected behavior**
Inherited lifecycle callbacks should be called.

**What is the motivation / use case for changing the behavior?**
There are several reasons to use inheritance:
1. automatic clearing of rxjs subscriptions
2. automatic removal of listeners
3. adding common initialization code
4. ... and others

* **Angular version:** 2.0.1

* **Language:** [all]

**Comment by kemsky** [comment]
Looks like i was wrong.

**Comment by kemsky** [comment]
SO many pitfalls, issue is valid :)

**Comment by zoechi** [comment]
Dup of https://github.com/angular/angular/issues/11606

**Comment by kemsky** [comment]
@vicb, did you read description of this issue and #11606?

**Comment by zoechi** [comment]
It's an inheritance issue and they are tackled together at 11606 so I don't see a problem with closing this issue.
Your issue also doesn't contain a Plunker and not even code that demonstrates the problem.

**Comment by kemsky** [comment]
While decorators and metadata *may* need special rules for inheritance, i believe that rules for method inheritance are already well defined and can not be altered. 
This is also reflected in ticket title: Proposal: Support well-defined rules of inheritance for Angular decorators.
