### ISSUE TITLE
Debugging improvement: Add `ng.tick()` and a way to access entry components via `ng.` 

### ISSUE THREAD

**Issue by d-ph** [angular/angular#12188]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is an `ng` symbol in the global namespace, when not running in production mode. It doesn't offer triggering change detection and accessing entry components.

**Expected behavior**
To improve debugging experience, there should be:
a) `ng.tick()` method, that would trigger change detection on all entry components.
b) `ng.entryComponents` array of components, which contains all registered entry components.

**Minimal reproduction of the problem with instructions**
1. Create an Angular project with 2 bootstrap components. I.e. the NgModule would look like the following:

```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { ComponentOneComponent } from './component-one';
import { ComponentTwoComponent } from './component-two';

@NgModule({
    imports: [
        BrowserModule,
    ],
    declarations: [
        ComponentOneComponent,
        ComponentTwoComponent,
    ],
    bootstrap: [ 
        ComponentOneComponent, 
        ComponentTwoComponent, 
    ]
})
export class EasierDebuggingExampleModule { }
```

**What is the motivation / use case for changing the behavior?**
Debugging is easier this way. [This article](http://juristr.com/blog/2016/02/debugging-angular2-console/) recommends doing the following:

a) Obtaining a component: `ng.probe($0).componentInstance`. This is useful, but requires selecting a component in the Elements tab in Chrome beforehand. It'd be easier to do `ng.entryComponents[0]` instead, to always be able to access the first entry component in Angular. Also, having a list of entry components known to Angular at any point of time is super useful.

b) Triggering change detection: `ng.probe($0)._debugInfo._view.changeDetectorRef.detectChanges()`. Too much typing and I struggle to remember how to do it. Also, it triggers change detection only on the selected component. `ng.tick()` would trigger change detection on every entry component, effectively redrawing the whole page.

**Please tell us about your environment:**
All

**Angular version:** 
2.0.0

**Browser:** 
All

**Language:**
All

**Node (for AoT issues):** 
n/a  

Thanks.

**Comment by pkozlowski-opensource** [comment]
In Angular v9 on ivy we've got a new set of debug tools: https://angular.io/api/core/global
While this is not _exactly_ what you are asking for, it should cover your use-cases.

If there are still parts that are not covered please open a new issue with the concrete use-case. Thnx!
