### ISSUE TITLE
Exception using dynamic module in wildcard route (**)

### ISSUE THREAD

**Issue by MasDevProject** [angular/angular#12183]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If I try to load a dynamic Module as wildcard, I get a null pointer exception:
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';

import { AppComponent } from './app.component';

@NgModule({
	imports: [
		BrowserModule,
		RouterModule.forRoot([
                        { path: '', redirectTo: 'login', pathMatch: 'full' },
			{ path: 'login', loadChildren: 'app/login/login.module#LoginModule' },
			{ path: 'not-found', loadChildren: 'app/not-found/not-found.module#NotFoundModule' },
			{ path: '**', redirectTo: 'not-found', pathMatch: 'full' }
		])
	],
	declarations: [
		AppComponent
	],
	bootstrap: [AppComponent]
})
export class AppModule { }
```

This is the error I get:
```handleError — core.umd.js:3370EXCEPTION: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'route._loadedConfig.routes')```

**Minimal reproduction of the problem with instructions**
[Here](https://www.dropbox.com/s/faqx6qvpzrhwwif/Example.zip?dl=0) you can find a ready project

* **Angular version:** 2.0.1

* **Browser:** [all]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   6.6

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. Luckily it has already been fixed https://github.com/angular/angular/issues/12024

**Comment by MasDevProject** [comment]
Thank you @DzmitryShylovich!
I will check it again when you will release v2.0.3

**Comment by DzmitryShylovich** [comment]
try `"@angular/router": "3.1.0-rc.0",`

**Comment by MasDevProject** [comment]
Just tried with:

`        "@angular/common": "2.1.0-rc.0",
        "@angular/compiler": "~2.0.2",
        "@angular/core": "2.1.0-rc.0",
        "@angular/forms": "~2.0.2",
        "@angular/http": "~2.0.2",
        "@angular/platform-browser": "2.1.0-rc.0",
        "@angular/platform-browser-dynamic": "~2.0.2",
        "@angular/router": "3.1.0-rc.0",`

But unfortunately the problem persists

**Comment by DzmitryShylovich** [comment]
so it's not released yet.
You have 2 options:
1. `"@angular/router": "github:angular/router-builds",`
2. wait for the next release.

**Comment by MasDevProject** [comment]
I tried with the first solution but the problem remains.
maybe this is a different problem

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource 
I can confirm. This is still an issue with the latest router. Error: http://prntscr.com/crr34m
Also I can reproduce https://github.com/angular/angular/issues/12024 . Works fine when navigating using routerLink but fails when entering url directly into browser url bar. Error: http://prnt.sc/crr27k

Router version: `"@angular/router": "github:angular/router-builds",`

**Comment by tskweres** [comment]
I am still unable to lazyload wildcard "**" routes in Angular 4.x, is this fixed somewhere?
