### ISSUE TITLE
Angular 2 AoT  Heep Errors

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#12184]
AoT compilation resulting in " JavaScript heap out of memory" error

I am trying to compile my project by following the AoT guide available on angular.io

Below is my typesccript configuration file for aot

```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "noEmitOnError": true,
    "removeComments": true,
    "sourceMap": false,
    "target": "es5",
    "outDir": "../content/app/"
  },
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit": true
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}
```

I am compiling using below command: 

`D:\MyProject\node_modules\.bin>ngc -p ../../app/tsconfig-aot.json`

It takes times in compilation and ends up with below errors:

```
<--- Last few GCs --->

  215225 ms: Mark-sweep 1327.9 (1434.3) -> 1316.1 (1434.3) MB, 1233.5 / 0.0 ms [allocation failure] [GC in old space requested].
  216639 ms: Mark-sweep 1316.1 (1434.3) -> 1316.1 (1434.3) MB, 1413.5 / 0.0 ms [allocation failure] [GC in old space requested].
  217985 ms: Mark-sweep 1316.1 (1434.3) -> 1320.4 (1403.3) MB, 1346.7 / 0.0 ms [last resort gc].
  219337 ms: Mark-sweep 1320.4 (1403.3) -> 1324.6 (1403.3) MB, 1351.5 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000023CEBCFB61 <JS Object>
    1: copyProperties [D:\MyProject\node_modules\typescript\lib\typescript.js:1462] [pc=000001870A3EC95C] (this=000000AAE12C6A41 <an Object with map 00000279F6259FA1>,source=000002E70921E389 <an Object with map 00000279F62D8539>,target=000002ED3C5C7691 <an Object with map 000000D6F40CD1C9>)
    2: objectTypeRelatedTo [D:\MyProject\node_modules\typescript\lib\typescript.js:...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

D:\MyProject\node_modules\.bin>
```

The project I am trying to compile has 467 files.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by naveedahmed1** [comment]
Are you sure its not a bug in AoT compiler?

**Comment by lazarljubenovic** [comment]
Even if it really was a bug, you still have to **fill out the [template](https://github.com/angular/angular/blob/master/.github/ISSUE_TEMPLATE.md)** which was presented to you while opening this issue (which you apparently just deleted).

**Comment by Sukh9212** [comment]
Anyone found any solution to this?
ngc runs fine for the first time when things are in JIT mode in main.ts, after first run, I change main,ts to AoT mode.
Then ngc takes a while to compile and the process ends up out of memory.

I couldn't find a solution anywhere
[Questions](http://stackoverflow.com/questions/39945756/angular-2-aot-heep-errors) on StackOverflow are unanswered.
I've tried compiling on both Windows and Mac and the process runs out of memory between 1400MB - 1460MB.

It's been over a month for me and there is still no solution to this problem.
Any help will be appreciated thanks..

**Comment by alexeagle** [comment]
How about giving node more memory by setting ` --max_old_space_size` ?

**Comment by Sukh9212** [comment]
how can I do that along with ngc?
I've tried `node --max-old-space-size=2048 ./node_modules/.bin/ngc -p tsconfig.json`
It doesn't work

**Comment by alexeagle** [comment]
Hmm, you could give it more memory than that, but perhaps there's something about the application you're building that causes ngc to leak memory or consume a great amount of memory.
We build angular itself and haven't seen this, but we don't have any project that compiles a very large number of components in a single pass.

Any idea how we can reproduce the issue?

**Comment by Sukh9212** [comment]
@alexeagle thanks for helping me out here.
In my previous comment I meant I'm unable to assign more memory to node. I'm probably not doing it correctly on command line.

here is my script in package.json 

`"scripts": {    
    "ngc": "node --max-old-space-size=2048 ./node_modules/.bin/ngc -p tsconfig.json"
  },`

when I do npm run ngc its gives syntax error as following:
`C:\Users\sukhdeep\Documents\Angular\gd_dev_server\node_modules\.bin\ngc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
`

I'm probably not doing it right.

About the project size, Yes I'll consider my project large as there is lot of HTML in the DOM and there is lot of two way data binding. My aot folder after first ngc compile comes at 15.8MB in size.

@naveedahmed1 you have any input on your project size?

I have another project which is written in exactly the same way, (I've followed proper typescript syntaxes and Angular best practices in both) but has far fewer modules and the aot folder size in that project is just 1.80MB. I don't have any heap issues in that project.

To reproduce, I guess projects that have lot of HTML and data binding are all having this issue.
My repo is private otherwise I would've just given it

**Comment by naveedahmed1** [comment]
@Sukh9212 after seeing activity on this issue, I just recompiled my project by following the official AoT guide:

https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

I have exact same tsconfig-aot.json file as in above guide except "noImplicitAny": false,.

My App folder has 487 files including components, modules, directive, guards, services and templates.

After compilation aot folder has 344 files and its size is 17.2MB.

After updating main.ts to:

```
import { platformBrowser } from '@angular/platform-browser';
import { AppModuleNgFactory } from './aot/app.module.ngfactory';
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

I get the same error which you have mentioned above. One more thing my app is using Lazyloading.

@alexeagle I can email you my app folder, which you would be able to compile. But since it has a dependence on backend in asp.net (which I cann't share) you wont be able to run the project.

**Comment by Sukh9212** [comment]
I'm not using lazy loading since I figured that if I do, ngc just ignores all the lazy loaded modules and doesn't generate AoT code for them. I'm not sure if it's supposed to do that or not.
So not doing that and importing all the modules in my app.module file.

My project isn't Angular CLI based so I won't be able to do that.
It's actually not even a problem of which tool we are using. At the end of it, it's the same ngc compiler and doesn't matter how we invoke it, the process is gonna run out of memory

**Comment by naveedahmed1** [comment]
Please have a look at below repository:

https://github.com/steveblue/angular2-rollup

and check the **Production** notes:

https://github.com/steveblue/angular2-rollup#production

It also suggests that there are some issues with ngc when using for large projects and it recommends using Closure Compiler after compiling with ngc.

**Comment by Sukh9212** [comment]
I think closure compiler isn't ready yet for Angular 2 see issue #8550 and this [link](http://blog.mgechev.com/2016/07/21/even-smaller-angular2-applications-closure-tree-shaking/)
Even if closure compiler works, still I would like ngc to do the entire job that it is supposed to do as it is demonstrated in the official tutorials. 
Angular 2 isn't in beta or RC anymore, but we still can't generate a production build out of it.
Waiting for it for over a month and half now.

**Comment by Sukh9212** [comment]
OK folks here is how I FINALLY compiled my project with ngc

This doesn't work on windows for some reason, but it worked on a mac machine

//first compile with main.ts in JIT mode
`./node_modules/.bin/ngc -p tsconfig-aot.json`

//then change main.ts to AoT mode and run
`node --max-old-space-size=8192 ./node_modules/.bin/ngc -p tsconfig-aot.json`

I literally had to go as far as 8192 (8GB) to not run out of memory (it goes as far as 5-6GB for my project)

//then build the rollup bundle
`node --max-old-space-size=8192 node_modules/.bin/rollup -c rollup.js`

if everything went well, now you should have a production bundle.

I'm not using lazy loading as if I do, ngc just ignores all the lazy loaded modules and does not generate AoT files for them.

My machine is 

![screen shot 2016-11-03 at 10 29 06 am](https://cloud.githubusercontent.com/assets/3210920/19969861/7dbfbf28-a1b0-11e6-9877-c249a62f65d2.png)

**Comment by naveedahmed1** [comment]
That's great, but it does indicate that NGC has issues and needs to be optimized for memory usage.

In Windows, does this mean that node just ignores max-old-space-size?

BTW what is the size of the final bundle? and how long does it now takes to run the app in browser?

**Comment by Sukh9212** [comment]
Yes, I believe that ngc does have some memory management issues as I don't think my project is that huge for a compiler to take up 5-6GB of RAM.

In windows there are probably some path issues on the command line and the command just errors out as following:

`$ node --max-old-space-size=8192 ./node_modules/.bin/ngc -p tsconfig-aot.json
C:\Users\sukhdeep\Documents\Angular\gd_dev_server\node_modules\.bin\ngc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
`

I don't think it's a problem with `max-old-space-size`, it's just windows command line problem I guess.

the size of the final bundle for me is 8.2MB, which isn't small

![buildsize](https://cloud.githubusercontent.com/assets/3210920/19970958/0387b7a2-a1b4-11e6-83c6-d0458caa07f6.PNG)


I'm okay with the build size for now, but obviously I would like it to be smaller than that

**Comment by naveedahmed1** [comment]
Both 8.2 Mb bundle size and 3 seconds load time is very large for a live web app. Maybe AoT with support of Lazy loading could give a better bundle and improve load time.

**Comment by alexeagle** [comment]
8.2 MB seems wrong. Can you use the source-map-explorer package to
determine where the size is coming from?

**Comment by Sukh9212** [comment]
After using the source-map-explorer here is what I get 

![screen shot 2016-11-03 at 2 28 21 pm](https://cloud.githubusercontent.com/assets/3210920/19979725/e136cc4c-a1d1-11e6-964b-812b1dcefe18.png)


and strangely, if you look at the top of the tree, the size is 927KB which I think should truely be the size of the bundle. But the actual size is 8.2 MB.

No idea how.

here is my rollup.js file

```
import rollup from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify'

export default {
  entry: 'app/main.js',
  dest: 'dist/build.js', // output a single application bundle
  sourceMap: true,
  sourceMapFile: 'dist/build.js.map',
  format: 'iife',
  plugins: [
    nodeResolve({ jsnext: true, module: true }),
    commonjs({
      include: [
        'node_modules/rxjs/**',
        'node_modules/ng2-cookies/**',
        'node_modules/angular2-highcharts/**'
      ],
      namedExports: {
        'node_modules/ng2-cookies/ng2-cookies.js': ['Cookie'],
        'node_modules/angular2-highcharts/index.js': ['ChartModule']
      }
    }),
    uglify()
  ]
}
```

**Comment by Sukh9212** [comment]
@naveedahmed1 about lazy loading

How do you propose that lazy loading will give better bundle and improve loading time?
The whole concept of lazy loading is to load JS,HTML,CSS files for lazy loaded modules in the background or on demand.

And since the entire idea of generating a rollup bundle is to pack everything in one JS file, how would the router lazy load modules when everything is in one file?

Correct me if I'm wrong but the lazy loading is only going to work if you are using a module loader like SystemJS or WebPack. I don't think it is anyway possible to achieve in a rollup bundle

**Comment by alexeagle** [comment]
The concept is, first you split code into lazy loadable units, then use
some tooling to create one bundle for each unit. Then you XHR to fetch the
next bundle when needed.
We have more work to do to make this convenient.

For the discrepancy between file size and reported sourcemap size, try
manually inspecting the JS file to see where the size comes from?

**Comment by Sukh9212** [comment]
Looking at the JS bundle doesn't seem to help. It is one enormous minified file.
I'm not sure how would I inspect it, and where/what to look for to know where the size is coming from

**Comment by naveedahmed1** [comment]
@SinghSukhdeep did you find any solution for Windows?

**Comment by SinghSukhdeep** [comment]
I haven't tried on Windows since then. I'll let you know if I figure it out.

**Comment by naveedahmed1** [comment]
One thing I noticed is that the correct option to specify memory limit is **max_old_space_size** and not **max-old-space-size** most of the posts I see on internet mention it with hyphens its actually with underscores. I verified it by runing the command **node --v8-options**.

**Comment by steverob2k** [comment]
On windows you can use this:

node --max-old-space-size=8192 node_modules/@angular/compiler-cli/src/main.js -p tsconfig-aot.json

**Comment by VladimirAmiorkov** [comment]
Also getting this error in my project, yes the project does have a lot of directives but are there really such limitations with ngc? Pushing the --max-old-space-size 16000 does not work for me and that is the max of my Mac.

**Comment by alexeagle** [comment]
ngc ought to use less memory. It may take some time before we can address
this.
In the meantime, one approach to try is to compile smaller chunks of the
application at a time. As the application scales, even tsc by itself can
take many seconds, which slows down your development roundtrip. The idea is
to tell your build system about several "libraries", each one lists its
dependent libraries. Then you run both ngc only on one library at a time,
giving it .d.ts and .metadata.json (or now ngsummary.json) files as inputs,
and only generating code for the .ts inputs.

**Comment by VladimirAmiorkov** [comment]
Hi @alexeagle ,

Thank you for the prompt response. 

This is what I was considering to try out but it will not be pretty as I am building a plugin that already has its structure implemented and working without issues and now all I am trying is to make it possible to ship it to npm with the necessary AoT files. I will try to think of something but it would be great if the OOM issues of ngc are resolved as I do see many people  facing this.

**Comment by VladimirAmiorkov** [comment]
@alexeagle 

A quick followup, I was running nodejs version 6.8.1 and updated to the latest 6.9.2. After that I ran the following script:

```
"scripts": {
    "ngc": "node --max-old-space-size=8192 ./node_modules/.bin/ngc -p tsconfig.json",
    "tsc": "tsc -p tsconfig.json",
    "prepublish": "npm run tsc && npm run ngc"
  }
```

and was able to run ngc correctly on my entire project. Previously I did try with `--max-old-space-size=16000` and was getting the OOM error, it looks like the **nodejs 6.8.1 was the cause**.

**Comment by alexeagle** [comment]
Great, thanks for that note.

**Comment by ritzm21** [comment]
Hi all,
I am also facing same heap error in my ionic 2 project as a result of adding many new components, directives in it. Here is the build script for ionic 2 project in package.json:
_"scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },_ 

And I modified it based on above discussion as below:
_"scripts": {
    "ionic:build": "node --max-old-space-size=8192 ./node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js build",
    "ionic:serve": "ionic-app-scripts serve"
  }_,

But I am still facing javascript heap error. Can anybody help me to understand that above modified script is a right approach to increase the heap size for node?
I am using Windows Command Line(cmd) tool to build the ionic 2 app.

**Comment by ValterSantosMatos** [comment]
@ritzm21 actually that worked for my Ionic2 project.

**Comment by tbosch** [comment]
So we need to do 2 things:

- allow build tools to compile big applications as multiple compilation units (i.e. multiple invocations of `ngc`). We already do this internally at Google, and we need to find a way to make this work nicely externally as well
- change ngc's memory consumption to be independent of the project size

**Comment by Neltherion** [comment]
any update on this? I used 8 GBs for a simple Bootstrap project and even 8 GBs couldn't do it!
the command that worked for me is :
`node --max-old-space-size=8192 node_modules/rollup/bin/rollup -c rollup-config.js`

**Comment by damiandennis** [comment]
I need to allocate 5GB just to compile a medium sized app.

**Comment by Koslun** [comment]
For everyone posting their results I think a more detailed build configuration and project information is needed to get any real insight.

Rollup, Webpack and other bundlers each have their own overhead, changing also vastly depending on version and configuration, including for instance which webpack plugins are used and how they are configured. Angular version is also important to understand what angular compiler is used. Where both the bundler and the angular compiler can consume a great amount of RAM. See an example breakdown here for meeting `2017-11-21`: https://docs.google.com/document/d/1wMHjLdXrcGw-8N50mJqqiyFA_upkc6_fTd2vEhOM0-k/pub

Following a larger regression for angular-cli 1.5, in terms of memory usage, reducing the memory usage is being actively worked on, see: https://github.com/angular/angular-cli/issues/5618. Though this largely does not cover optimizing the angular compiler.

This has partly added to `Webpacks ModuleConcatenationPlugin` being heavily optimized in terms of RAM usage. See https://github.com/webpack/webpack/issues/5992 and https://github.com/webpack/webpack-sources/issues/30.

**Comment by IgorMinar** [comment]
It seems that this bug ended up being the catch all place for all kinds of memory related issues. We fixed a whole bunch of them in v4 and then again just after v5.0 was released. Please help us sort these issues out by open new issues with reproductions if you still have memory related problems. Thank you.
