### ISSUE TITLE
AOT doesn't work with rxjs map on Windows?

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular#12189]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Rather than a successful compile, I get the terminal output:

```
> ngc -p client/tsconfig-aot.json

Error: Error at C:/Users/George/Source/Repos/docs/client/components/plugins/plugins.component.ts:77:8: Property 'map' does not exist on type 'Observable<Response>'.
Error at C:/Users/George/Source/Repos/docs/client/components/plugins/plugins.component.ts:77:12: Parameter 'res' implicitly has an 'any' type.
Error at C:/Users/George/Source/Repos/docs/client/components/plugins/plugins.component.ts:79:7: Parameter 'data' implicitly has an 'any' type.
Error at C:/Users/George/Source/Repos/docs/client/components/plugins/plugins.component.ts:80:7: Parameter 'error' implicitly has an 'any' type.
    at check (C:\Users\George\Source\Repos\docs\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Tsc.typeCheck (C:\Users\George\Source\Repos\docs\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)
    at C:\Users\George\Source\Repos\docs\node_modules\@angular\tsc-wrapped\src\main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Compilation failed
```

**Expected behavior**
For ngc to work successfully as it does on my mac and on travis linux builds with the exact same repo. 

**Minimal reproduction of the problem with instructions**

1. `git clone https://github.com/georgeedwards/docs`
2. `git checkout performance`
3. `npm i`
4. `npm run ngc`

you can see this successfully build [here](https://travis-ci.org/georgeedwards/docs/builds/166269573), it only seems to be a Windows thing...

**What is the motivation / use case for changing the behaviour?**
Bug Fix

**Please tell us about your environment:**
Windows 10 Pro, npm: 3.10.8

* **Angular version:** 2.0.3

 
* **Language:** [all | TypeScript 2.0.3 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.7.0

**Comment by vicb** [comment]
You are not using the same config in AoT vs JiT (`"noImplicitAny": true,`)

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by georgeedwards** [comment]
@vicb not sure why you are talking about JIT? My AOT works fine on Linux but not on Windows... with exactly the same **tsconfig-aot.json** (and every other file). How is that not a bug? 

Here is my **tsconfig-aot.json** for reference:

```
{
  "compilerOptions": {
    "target": "es6",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true
  },
    "exclude": [
        "../node_modules"
    ],

  "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : true
 }
}
```
