### ISSUE TITLE
 how to  lazy load a module from a package ?

### ISSUE THREAD

**Issue by jjlgjkkl** [angular/angular#12180]
we have some modules published as package, and in this project we need to lazy load the module

if the module in the target project, it's ok , like :

export const routes: Routes = [ 
    { path: '', redirectTo: 'test01', pathMatch: 'full'},
    { path: 'test01', loadChildren: 'app/testing01/test01.module' },
]

but, how can i load modules from package , like this:
  { path: 'test01', loadChildren: '@xxx/testing01/test01.module' },

i am using   
 "angular-cli": "1.0.0-beta.15",
  @angular   2.0.0

thank you and being in touch

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by zoechi** [comment]
Haven't found an `angular` tag on SO. It's either `angular2` (or `angularjs` for Angularjs 1.x).
