### ISSUE TITLE
one component different templateUrl

### ISSUE THREAD

**Issue by Gunasekaranv** [angular/angular#12182]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
@Component({
  selector: 'login',
  templateUrl: ./login.html 
})

**Expected behavior**

@Component({
  selector: 'login',
  templateUrl: function(route: ActivatedRoute){
	return route.snapshot.name + '.html'
	} 
})

this function should execute before executing a component.
  
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Angular doesn't work like this. You cannot change component template in runtime.

**Comment by vicb** [comment]
Template have to be know at compile time.
