### ISSUE TITLE
Property … does not exist on type ‘{ [key: string]: AbstractControl; }’

### ISSUE THREAD

**Issue by basvdijk** [angular/angular#12181]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When compiling a form with AoT I'll get:

`Property 'email' does not exist on type '{ [key: string]: AbstractControl; }'.`

First I thought it was a bug in Ionic which reported. They stated that it was a code issue: https://github.com/driftyco/ionic-app-scripts/issues/100#issuecomment-251790964, but it looks like it has something to do with AoT. 

More people reported this error see:
https://forum.ionicframework.com/t/property-does-not-exist-on-type-key-string-abstractcontrol/65783
and https://forum.ionicframework.com/t/deploy-to-android-phone-show-white-page-after-upgrade-to-2-0-0-rc-0/66283/5

**Expected behavior**
When you create a variable to store a `FormGroup` with the type `FormGroup` there shouldn't be an error:

**Minimal reproduction of the problem with instructions**

```
recoverPasswordForm: FormGroup;

constructor(

    fb: FormBuilder) {

    this.recoverPasswordForm = new FormGroup({
        email: new FormControl([navParams.get('username') || '', Validators.compose([Validators.required, ValidatorService.email])),
    });

}

```

changing `recoverPasswordForm: FormGroup;` into `recoverPasswordForm = null;` solves the problem

**What is the motivation / use case for changing the behavior?**
This is used for forms

**Please tell us about your environment:**
OSX, Vscode, npm, Ionic2 RC0

* **Angular version:** 2.0.X

* **Browser:** Chrome / All
 
* **Language:** Typescript

* **Node (for AoT issues):** `node --version` =  v6.7.0

**Comment by DzmitryShylovich** [comment]
Can you paste the full component and template?
I would assume you somewhere (probably template) access control like `recoverPasswordForm.controls.email`.

**Comment by basvdijk** [comment]
I've tried five different ways to access the component value:

```
        console.log('1', this.recoverPasswordForm.value['email']);
        console.log('2', this.recoverPasswordForm.get('email').value);
        console.log('3', this.recoverPasswordForm.value.email);
        console.log('4', (<FormControl>this.recoverPasswordForm.get('email')).value);
        console.log('5', this.recoverPasswordForm.controls['email']);
```

Unfortunately all raised the error:

`Property 'email' does not exist on type '{ [key: string]: AbstractControl; }'`

Here is the code of my component and template:

**The component**

```
import {NavController, NavParams} from 'ionic-angular';

import {Component} from '@angular/core';
import {FormGroup, FormBuilder, Validators} from '@angular/forms';

@Component({
    templateUrl: 'RecoverPassword.html'
})

export class RecoverPassword {

    // recoverPasswordForm = null;
    recoverPasswordForm: FormGroup;

    constructor(
        public nav: NavController,
        public navParams: NavParams,
        public fb: FormBuilder) {

        this.recoverPasswordForm = fb.group({
            'email': [navParams.get('username') || '', Validators.compose([Validators.required, ValidatorService.email])]
        });

    }

    recoverPassword(): void {

        this.account.recoverPassword(this.recoverPasswordForm.value['email']).subscribe(res => {
            console.log(res);
        }

        }, error => {

            this.busy = false;

        });
    }

}
```

**The template**

```
<ion-header>
    <ion-navbar>

        <ion-title>{{ 'account.passwordRecover' | translate }}</ion-title>
    </ion-navbar>

</ion-header>

<ion-content class="wallpaper__photo">

    <ion-card padding-bottom>

        <form [formGroup]="recoverPasswordForm">

            <ion-list>

                <ion-item>
                    <ion-label stacked>{{ 'account.email' | translate }}</ion-label>
                    <ion-input type="email" formControlName="email"></ion-input>
                </ion-item>

                <form-error [control]="recoverPasswordForm.controls.email" error="required">{{ 'errors.fieldRequired' | translate }}</form-error>

            </ion-list>

            <div>

                <oxy-smart-button label="{{ 'account.passwordRecover' | translate }}" [busy]="busy" style="secondary" icon="check" [disabled]="!recoverPasswordForm.valid" (click)="recoverPassword()"></oxy-smart-button>

            </div>

        </form>

    </ion-card>

</ion-content>
```

**Comment by DzmitryShylovich** [comment]
Replace 
`<form-error [control]="recoverPasswordForm.controls.email" error="required">{{ 'errors.fieldRequired' | translate }}</form-error>`
with
`<form-error [control]="recoverPasswordForm.get('email')" error="required">{{ 'errors.fieldRequired' | translate }}</form-error>
`

Also see https://github.com/qdouble/angular-webpack2-starter#aot--donts

**Comment by basvdijk** [comment]
Thanks, also for the link with aot dont's. I will communicate this solution on the Ionic forum. 👍

**Comment by alejamoreno94** [comment]
Thank you very much, This response I help me a lot of
