### ISSUE TITLE
detectChanges() is not executed after animationDone($event)

### ISSUE THREAD

**Issue by theunreal** [angular/angular#12186]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
detectChanges() is not executed after animationDone($event).

**Expected behavior**
detectChanges() to be executed after animationDone()

**Minimal reproduction of the problem with instructions**
http://stackoverflow.com/questions/39946822/angular-2-animationdone?noredirect=1#comment67174105_39946822

**What is the motivation / use case for changing the behavior?**
Make animations callbacks works well without adding extra linese of code

**Please tell us about your environment:**
Windows XAMPP

* **Angular version:** 2.0.X
2.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0

* **Node (for AoT issues):** `node --version` =   
2.6.5

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/11881
