### ISSUE TITLE
How can I do synchronous test or not sharing a stub service?

### ISSUE THREAD

**Issue by xxxtonixxx** [angular/angular#12198]
I have a few tests that needs a service. I am using a stub service named `UserServiceStub` that I inject in my `SettingsComponent`, which I am testing. I reset the UserServiceStub in each test, but, tests are executed asynchronous so when I reset my UserServiceStub (which is an injectable and singleton class) other test has already initialized it. My tests are weak and asserts are wrong :-(

I would like to do synchronous test or a different UserServiceStub instance for each test, but I don't know how to do it...

I tried to define a method in UserServiceStub called `reset()` that resets stub service, but because it's asynchronous it doesn't work. Also, I executed in `afterEach()` method,  the `TestBed.resetTestEnvironment()` method but it does not work either.

- `reset()` method:
```typescript
reset() {
    this.user = { IBAN: '', SWIFT: '', paypal: '', app_idioma: '' };
  }
```
- The property I am using is called `user` and it has being overwritten by other tests

- My `beforeEach()` method is this ONE
```typescript

 let fixture: ComponentFixture<SettingsComponent>;
 let settingsComponent: SettingsComponent;
 beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [SettingsComponent],
      imports: [],
      providers: [
        TranslateService,
        AppService,
        { provide: MockBackend, useClass: MockBackend },
        { provide: HttpToolsService, useValue: HttpToolsServiceStub },
        { provide: BaseRequestOptions, useClass: BaseRequestOptions },
        { provide: UserService, useClass: UserServiceStub } // My stub UserService
      ]
    });

    fixture = TestBed.createComponent(SettingsComponent);
    settingsComponent = fixture.componentInstance;

  });
```

- A test:
```typescript
 it('#updateSettings should  doesn\'t update the user\'s settings when is wrong', fakeAsync(
    inject([UserService, HttpToolsService, MockBackend],
      (userService: UserServiceStub, httpToolsService: HttpToolsService, mockBackend: MockBackend) => {
        userService.reset(); // It does not work...
        userService.isError = true;
// However, I have reseted my user in UserServiceStub,
// this returns false because settingsComponent.getSettings().IBAN is actually 'XXX' 
// instead of '' (empty) how it has to be
        expect(settingsComponent.getSettings().IBAN).toBe(''); 
      }))
  );
```

I hope your answers, if you got any question just ask. 

Thanks :smile:

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
