### ISSUE TITLE
Fragment is not working

### ISSUE THREAD

**Issue by micronyks** [angular/angular#12197]
**DEMO** :  https://plnkr.co/edit/xAGjXqpmkLbCokvCt9qQ?p=preview

**AppComponent.ts**
```
      <a routerLink="frag" fragment="anchor"> Fragment Component </a>   //<<<===fragment="anchor"
      <router-outlet></router-outlet>
```
**FragmentComponent.ts**
```

@Component({
    
    template: `
    <div>
      <h2>Fragment Component</h2>
      
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      
      
      <div id="anchor">should scroll automatically till here</div>      //<<<===I believe it should scroll automatically till here. But its not working.
    </div>
    
  `,
})
```

**Comment by DzmitryShylovich** [comment]
Pls fill out the issue template http://prntscr.com/cs3yal
Thx.

**Comment by micronyks** [comment]
@DzmitryShylovich I just wanted a confirmation that this is a bug. I'll do it now.

**Comment by micronyks** [comment]
@vicb  isn't it a bug?

**Comment by DzmitryShylovich** [comment]
I would say it's miss configuration.

**Comment by micronyks** [comment]
@DzmitryShylovich Could you please help to resolve it? which configuration you are talking about?

**Comment by vlavellauruit** [comment]
Im having troubles with this too... and seems that here https://angular.io/resources/live-examples/router/ts/eplnkr.html is not working too.
Can you confirm that this is a bug?
