### ISSUE TITLE
Possible typo in NgModule tutorial docs

### ISSUE THREAD

**Issue by togakangaroo** [angular/angular#12191]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

[In the NgModule tutorial/docs](https://angular.io/docs/ts/latest/guide/ngmodule.html) I see the following line

> We export the ContactComponent so other modules that import the ContactModule can include it in their component templates.

This makes no sense...the thing being exported in the related code is `ContactModule` not `ContactComponent`. Seems like it should read something like

> We export the module so that others that import the `ContactModule` can include it's contents.

Also note that the way it is currently phrased is specifically about components since the contents of a module might be included in many places, *not* just in templates.

**Comment by DzmitryShylovich** [comment]
> In the NgModule tutorial/docs I see the following line

404

Pls re-open in the docs repo https://github.com/angular/angular.io
