### ISSUE TITLE
Simplify microsyntax variable assignment

### ISSUE THREAD

**Issue by timblakely** [angular/angular#12194]
**I'm submitting a ...** 

```
[X] bug report 
[ ] feature request
[ ] support  request
```

**Current behavior**
Two oddities when using microsyntax to set variables on structural directives:

1) An unused @Input named exactly like the selector is required on structural directives.

```
@Directive({
  selector: '[aDirective][aDirectiveFoo]',
  ...
})
export class ADirective {
  @Input() aDirective: any;  // Required, but explicitly set to "undefined".
  @Input() aDirectiveFoo: string;
}
```

2) An extraneous character followed by a space is required at the beginning for it to work.

Doesn't work:

```
<a-component *aDirective="foo:'bar'">
<a-component *aDirective=" foo:'bar'">
```

Works:

```
<a-component *aDirective="z foo:'bar'">
<a-component *aDirective="config; foo:'bar'">
```

**Expected behavior**
1) Don't require or automatically insert the extraneous @Input.
2) Allow variable assignment without the required character and space.

**Minimal reproduction of the problem with instructions**

[Plunker example here](https://plnkr.co/edit/aBT256OKZH4ayZT3J0sT)

**What is the motivation / use case for changing the behavior?**
Allow richer initialization and use of structural directives.

**Comment by alexzuza** [comment]
I would leverage the following solution:

```
@Directive({
  selector: '[aDirective]'
})
export class ADirective {
  @Input() aDirective: any;
  ngOnInit() {
    console.log(this.aDirective);
  }
}
```
`<a-component *aDirective="{foo:'bar'}">`

**Comment by vicb** [comment]
relates to https://github.com/angular/angular/issues/5894

**Comment by trotyl** [comment]
@tbosch As per https://github.com/angular/angular/pull/12841#issuecomment-306542304, would it better to remove the `hotlist: community-help` label here?

**Comment by AndrewKushnir** [comment]
Closing as a duplicate of #5894.
