### ISSUE TITLE
Invalid dependency in Angular 2.0.2 Quick Start guide

### ISSUE THREAD

**Issue by Shakyamuni177te** [angular/angular#12195]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

"angular-in-memory-web-api": "~0.1.5", listed in Quick Start guide: https://angular.io/docs/ts/latest/quickstart.html is not a valid version. `Npm install` error lists 0.0.21 as latest version.
 
**Expected behavior**

Version 0.1.5 of angular-in-memory-web-api would install when running `npm install`.

**Minimal reproduction of the problem with instructions**

Try to install dependencies using latest version of Angular2 Quick Start guide.

**What is the motivation / use case for changing the behavior?**

So the Quick Start is easy to follow for beginners.

**Please tell us about your environment:**

Ubuntu 16:04 Server; Vim; node; lite-server.

* **Angular version:** 2.0.X

Introduced as of 2.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
Not browser issue.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

n/a

* **Node (for AoT issues):** `node --version` =   

6.7.0

**Comment by DzmitryShylovich** [comment]
Pls re-open in the docs repo https://github.com/angular/angular.io

**Comment by Shakyamuni177te** [comment]
Will do.
