### ISSUE TITLE
ActivatedRoute is dropping off params?

### ISSUE THREAD

**Issue by nmorado** [angular/angular#12202]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

URL: http://localhost:4200/#/app/%2Fsample%2F%23%2Freservation

I have a route defintion for app/:path.

Inside the component's ngOnInit, i am retrieving the path through the ActivatedRoute:

let path: string = params['path'];

path is undefined. I am expecting: sample/#/reservation

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Firefox 38.2.0
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls provide a working reproduction in plunkr.

**Comment by ogix** [comment]
You should use snapshot: this.route.snapshot.params['path']

**Comment by felipedrumond** [comment]
@ogix, an instance of Route does not have _snapshop_ property.
The following code will read the parameter:

```
// queryParameters( ?path= )
this.activatedRoute.**queryParams**.subscribe(params => {
            this.path = params['path'];
        });

// matrix parameters ( ;path= ) or route parameters 
this.activatedRoute.**params**.subscribe(params => {
            this.path = params['path'];
        });
```

**Comment by ogix** [comment]
In my case '`route`' variable is instance of `ActivatedRoute`.
Most of the time you don't need to subscribe for params observable. You could use cached value from the `snapshot `property.
I suspect the author is trying to directly access `params `property from the `ActivatedRoute` instance

**Comment by vsavkin** [comment]
To get the latest value of the parameter do the following: `route.snapshot.params['myParam']`. Closing this issue.
