### ISSUE TITLE
Line and column numbers in template compilation errors are one off

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#12204]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

Line and column numbers in errors are 0-based.

**Expected behavior**

Line and column numbers should be 1-based.

**Minimal reproduction of the problem with instructions**

Error:

```
Error: Template parse errors:
'made-up' is not a known element:
1. If 'made-up' is an Angular component, then verify that it is part of this module.
2. If 'made-up' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
("[ERROR ->]<made-up>Hello {{name}}</made-up>"): App@0:0
```

Notice `App@0:0`. It should be `App@1:1`.

http://plnkr.co/edit/zI6dHwvyoefsDiklNIlu?p=preview

**Please tell us about your environment:**
- **Angular version:** 2.0.3
- **Browser:** [all]
- **Language:** [all]

**Comment by pkozlowski-opensource** [comment]
Angular v9 with icy reports correct line / column number: https://ng-run.com/edit/qypRGX7hPETMcNQnXOqQ
