### ISSUE TITLE
Dart analyzer plugin for Angular 2 MVP

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1220]
The plugin would perform static checks in Angular 2 templates and feed them to Dart analyzer and from there to any Dart-aware IDE, linters, etc.

Let's put it in a new folder `modules/angular2/src/dart_analyzer`

**Comment by yjbanov** [comment]
@keertip please self-assign when you accept collaborator invitation.

**Comment by mhevery** [comment]
This is being taken on by the dart team. Closing.
