### ISSUE TITLE
Using module.id with component makes it not load

### ISSUE THREAD

**Issue by viennv1709** [angular/angular#12214]
I'm trying to follow Angular 2 Tutorial, but I used **Webpack** instead of **SystemJS** and an error occurred with my app.

This is my HeroComponent code:
```typescript
import {Component, OnInit} from '@angular/core';

import {Hero} from './shared/hero';
import {HeroService} from './hero.service';

@Component({
    moduleId: module.id,
    selector: 'qs-heroes',
    templateUrl: 'hero.html'
})
export class HeroComponent implements OnInit {
    title = 'My Heroes';
    heroes: Hero[];
    selectedHero: Hero;

    constructor(private heroService: HeroService) {
    }

    private getHeroes(): void {
        this.heroService.getHeroesSlowly()
            .then(heroes => {this.heroes = heroes; console.log(heroes);});
    }

    ngOnInit(): void {
        this.getHeroes();
    }

    onSelect(hero: Hero): void {
        this.selectedHero = hero;
        console.log(hero);
    }
}
```

This is my webpack config:
```javascript
'use strict';

let webpack = require('webpack');
let HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: __dirname.concat('/src/app/main.ts'),
    cache: false,
    devtool: 'source-map',
    output: {
        path: __dirname,
        sourceMapFilename: '[name].map',
        chunkFilename: '[id].chunk.js',
        filename: '[name].js'
    },
    resolve: {
        extensions: ['', '.js', '.ts']
    },
    module: {
        loaders: [
            {
                test: /\.ts$/,
                loaders: ['awesome-typescript-loader', 'angular2-template-loader']
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: 'index.html'
        })
    ]
};
```

Typescript config:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules"
  ]
}
```

Finally screenshots:
<img width="1440" alt="screen shot 2016-10-11 at 4 52 14 pm" src="https://cloud.githubusercontent.com/assets/5088270/19266615/83800ee2-8fd4-11e6-96e2-78cc25f4347c.png">

**Comment by DzmitryShylovich** [comment]
moduleId is required for systemjs so you can remove it.

This issue tracker is not suitable for support requests, please next time file your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

**Comment by viennv1709** [comment]
I removed moduleId, but still arise error.
<img width="1440" alt="screen shot 2016-10-11 at 5 14 23 pm" src="https://cloud.githubusercontent.com/assets/5088270/19266946/2c8cef7c-8fd6-11e6-97de-adfa3abbdf7f.png">

**Comment by tbosch** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
