### ISSUE TITLE
External links with fragment identifiers don’t work

### ISSUE THREAD

**Issue by jostschmithals** [angular/angular#12212]
**I'm submitting a ...**

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Browsers don't jump directly to the id given in the fragment of a link from outside (details see below).

**Expected behavior**
Browsers should jump directly to the id given in the fragment of the URL.

**Minimal reproduction of the problem with instructions**
I took the „5 min Quickstart“ and replaced the code in app.component by 2 simple divs with ids „section1“ and „section2“:

```
import { Component } from '@angular/core'; 

@Component({  
    selector: 'my-app',  
    template:   
    `<div id="section1" style="height: 1500px; background: yellow">Section 1</div>  
     <div id="section2" style="height: 1500px; background: orange">Section 2</div>`  
})  
export class AppComponent {}
```

When I paste `localhost:3000/#section2` in the address bar: 
- Firefox stays at the top of the page until the user hits „Enter“ (after deselecting), 
- Chrome stays in each case on the top of the page, 
- Edge seems to go randomly to section1 or section2.

**What is the motivation / use case for changing the behavior?**
Links from outside should work without special handling in the code, because one doesn't know in advance, which element of a page a user will pick to set a deep link to this element. Therefore there should be no difference, whether the 2 divs are placed in index.html (which would work, of course) or in app.component.ts (which is not working).

**Please tell us about your environment:**

Windows 10 (1607),
Visual Studio Code, 
npm, 
default Quickstart configuration without any changes (besides the 2 mentioned divs)

(I heared that the same app.component file behaves correctly when part of an angular-cli project(?))
- **Angular version:**
  2.0.2
- **Browser:**
  see above ("reproduction")
- **Language:** 
  TypeScript
- **Node (for AoT issues):**
  6.7.0

**Comment by jostschmithals** [comment]
This is no duplicate of https://github.com/angular/angular/issues/12197.


#12197 relates to routerLinks. Such Internal links you can easily handle in code, so there is a workaround available.

But deep links from outside can’t be handled in code, because you don’t know them in advance.

**Comment by jostschmithals** [comment]
@pkozlowski-opensource : Just for interest's sake - why did you add the router label? - There is no router involved in my example (at least not visually).

**Comment by tbosch** [comment]
@jostschmithals Are you including the `RouterModule` in your application? If so, the router takes over the url handling and therefore there is no scrolling happening.

**Comment by jostschmithals** [comment]
No, there was definitely no RouterModule imported. 

Starting from the (freshly copied) quickstart code from https://angular.io/docs/ts/latest/quickstart.html I changed absolutely nothing besides the two lines of the template in app.component.ts (as specified above).

**Comment by alxhub** [comment]
I'm going to close this issue, as I can no longer reproduce it as of Angular v17 (using Chrome + the template from above). I suspect that Chrome behavior might've changed in a way that better handles cases where the anchor element is not present during the initial pageload, and only appears later.
