### ISSUE TITLE
Add opt-in change tracking for form

### ISSUE THREAD

**Issue by drauch** [angular/angular#12213]
**I'm submitting a feature request**

I'd like to see an opt-in change tracking mechanism for forms, i.e., an improved version of ng-dirty/ng-pristine which is based upon the initial value instead of a boolean flag.

Example:

```
Initial Value = "Hello"
User presses 'a' => new value = "Helloa", field marked as ng-dirty
User presses backspace => new value = "Hello" == initial value, field reset to ng-pristine
```

Maybe there is also a nice way to implement this myself, without having to write cumbersome logic in my components? E.g. some sort of interceptor which one could apply?

**Comment by skreborn** [comment]
It would be easy for Angular to store the initial value, but this would result in increased memory and CPU consumption, especially for `<textarea>` elements, as the initial value needs to be saved **and** compared to the current value *every single time* the latter changes.

Another method to solve this might be to save hashes of the initial values, and compare the hashes of the new ones to those instead, but this would mostly result in even more memory and CPU consumption, as a hash will usually be longer than the value itself (except for rare cases and most `<textarea>`s), and hashing itself is a CPU intensive task.

A middle ground would be to store values for everything but `<textarea>`s, for which we would store hashes instead.

I still believe that the price outweighs the value in this case, so I wouldn't recommend going with any of these, but it also sounds useful, and if this were to actually become an opt-in solution, we could just document the downsides, and people could choose to live with them, or keep using the default change detection.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please re-post your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

If you think it's a feature requires then fill out the issue template.

**Comment by drauch** [comment]
@skreborn : Yes, you're absolutely right, it shouldn't be the default behavior due to increased memory and CPU consumption. Still, I believe it would be a very nice feature and would be a nice candidate for an opt-in approach (as an additional middleground, users could also opt-in to use this system on a field-blur basis instead of evaluating the state on each keypress).

@DzmitryShylovich : I cannot see how this should not be a feature request. Is this some kind of bot reply?

**Comment by skreborn** [comment]
@drauch I think @DzmitryShylovich simply wants you to use the issue template as provided when you create one.

> If you think it's a feature requires then fill out the issue template.

**Comment by zoechi** [comment]
Isn't it easy enough to get the data from the whole form with a single call after it's initialized, and then assign the data back when the developer does want it to be restored?

**Comment by drauch** [comment]
@zoechi : I don't want to restore form data, I want to restore change-tracking after the initial value is typed in again.

**Comment by jurisv** [comment]
4 years later.. still in backlog. Any chance to get this feature?

**Comment by dylhunn** [comment]
If you want to compare against some specific value, you should attach your own directive which tracks changes in the input field.
