### ISSUE TITLE
ngDisable delay

### ISSUE THREAD

**Issue by jacobscarter** [angular/angular#1221]
I have a function that flips a boolean which removes the ngDisaled, i.e.

    //js
    $scope.removeDisabled = function(){
        $scope.disabledBoolean = false;
        angular.element('#myInput').focus()
    };

    //html
    <button ng-click="removeDisabled()">Click Me</button>
    <input ng-disabled="disabledBoolean" id="myInput">

The function also puts the input in focus

The problem that I run into is that the input will only go into focus if I wrap the function in a $timeout, even if the delay on that timeout is 0.  My conclusion was that the disabled is not removed quick enough for the input to be allowed to be put in focus.  Is there any documentation on this sort of issue?

My solution feels hacky and I figured someone smarter than me has solved this already.  Also perhaps this is a JavaScript question not an Angular one so I apologize in advance if I shouldn't be posting this here.

**Comment by jelbourn** [comment]
The repo you're looking for is https://github.com/angular/angular.js
