### ISSUE TITLE
Using RouterModule with multiple bootstrapped components gives weird navigation

### ISSUE THREAD

**Issue by pjordaan** [angular/angular#12218]
```
[X ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I am working on my Angular2 component where I have a component that displays a login status that has no dependency on which routing is picked. I have also a component that displays the proper page with <router-outlet></router-outlet>. Both are defined in the same @NgModule annotation and both need to be bootstrapped as they are part of a static html page.

```
@NgModule({
    declarations: [DisplayPageComponent, LoginStatusComponent],
    imports: [RouterModule.forRoot(routes)],
    bootstrap: [DisplayPageComponent, LoginStatusComponent]
})
```

When I press the next button to go a different page, I go to the other page for a split second and then go back to the previous step.

If I subscribe to router.events I see I navigate to the page and then the page is disabled again as the id has changed on this line:
```
this.routerEvents.next(new NavigationCancel(id, this.serializeUrl(url), "Navigation ID " + id + " is not equal to the current navigation id " + this.navigationId));
```
 It seems the login status component also listens to the routing and disables the page and you receive no feedback if you do not subscribe to router events.

**Expected behavior**
I expect the routing navigation is only handled once and not the number of components that are bootstrapped.

**Minimal reproduction of the problem with instructions**
I can create a plunkr if required

**What is the motivation / use case for changing the behavior?**
Even if the way I use modules is incorrect I would expect to get at least some feedback why the navigation was blocked/failed

* **Angular version:** 2.0.1

* **Browser:** all
 
* **Language:** all

**Comment by DzmitryShylovich** [comment]
> I can create a plunkr if required

yeah, pls

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by mseemann** [comment]
@pkozlowski-opensource this is a duplicate of this one: https://github.com/angular/angular/issues/12282. The router registered a listener for bootstrapped components. If there are more then one bootstrap component all router events are fireing multiple times. The mentioned issue describes the technical problem + solution in more detail.

**Comment by pkozlowski-opensource** [comment]
Thnx @mseemann
