### ISSUE TITLE
Output EventEmitter not working properly

### ISSUE THREAD

**Issue by pjaymagat** [angular/angular#12216]
Im following the angular2 tutorial on the Output for Child component to Parent component communication.

The sample on this link https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#child-to-parent tutorial not working properly the first button does not call the parent function.

Here is my code:
```javascript
import { Component }      from '@angular/core';
import { VoterComponent } from './VoterComponent.component';
@Component({
    selector: 'vote-taker',
    template: `
    <h2>Should mankind colonize the Universe?</h2>
    <h3>Agree: {{agreed}}, Disagree: {{disagreed}}</h3>
    <my-voter (onVoted)="onVoted($event) ">      
   
    </my-voter>
  `
})
export class VoteTakerComponent {
    agreed = 0;
    disagreed = 0;
  
    onVoted(agreed: boolean) {
        console.log('emit from parent');
        agreed ? this.agreed++ : this.disagreed++;
    }
}
```

```javascript
import { Component, EventEmitter, Input, Output } from '@angular/core';
@Component({
    selector: 'my-voter',
    template: `
    <h4>{{name}}</h4>
    <button (click)="vote(true)"  >Agree</button>
    <button (click)="vote(false)" >Disagree</button>
  `
    
})
export class VoterComponent {
    @Input() name: string;
    @Output() onVoted = new EventEmitter<boolean>(false);
    voted = false;
    vote(agreed: boolean) {
        console.log('emit from child');
        this.onVoted.emit(agreed);
        this.voted = true;
    }
}
```

from the code above only the child is working but the parent not triggered.

**Comment by DzmitryShylovich** [comment]
Pls provide working reproduction in plunkr.

**Comment by skreborn** [comment]
@pjaymagat @DzmitryShylovich [Here](http://plnkr.co/edit/Ia9bg4IhScRvGTXj3dRa?p=preview)'s the reproduction. This plunker uses *nearly* the same code as the one found in the docs (the only change is the selector from `vote-taker` to `my-app`), and it works as expected.

**Comment by DzmitryShylovich** [comment]
This issue tracker is not suitable for support requests, next time, please, post your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
Thnx @skreborn and @DzmitryShylovich for helping out with the issues!

**Comment by pjaymagat** [comment]
Hi,
I've tried it using VS Code as well, its the same code no changes at all but the first "Vote" is really not working in my local only the 2nd/3rd vote is working, if i do it using the plunkr it is working, i think if you have time you can revisit it and try to use it using local and not plunkr. 

For now i'm trying to use service to communicate the child > parent component.
