### ISSUE TITLE
Issue #12216 Eventemitter is only working in plunkr and not using local copy

### ISSUE THREAD

**Issue by pjaymagat** [angular/angular#12228]
[AngularEventEmitterTest.zip](https://github.com/angular/angular/files/523574/AngularEventEmitterTest.zip)

Hi,
I think i need to reopen the #12216 as i tried multiple machine and with the same code but the event emitter is not really working properly but if you write the same code in plunkr yes it is working fine.

I have attached the sample code and excluded the node_modules folder instead i modified the systemjs to point to "https://unpkg.com/", regardless on using the local copy of node_modules still not working.

**Comment by manklu** [comment]
To recite @vicb

>Your question sounds like a support request.
>
>Please use the issue tracker only for bugs and feature requests.
>
>Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

The bootstrap part of your module definition is invalid.

**Comment by pjaymagat** [comment]
Hi @manklu thank you, my bad.
