### ISSUE TITLE
Secondary routes/segments don't map to browser buttons when lazy loading a module that defines routes

### ISSUE THREAD

**Issue by suchk** [angular/angular#12226]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Scenario: You have a lazy loaded module that defines its own secondary route/segment.
When the secondary route is triggered, pressing the Back button on the browser reflects a URL change, but the content from the secondary route stays on the page. Pressing Forward afterwards does not replace the current content, but instead adds a copy of the content to the page.

**Expected behavior**
Pressing the Back button should remove the content that was loaded from the lazy loaded module.

**Minimal reproduction of the problem with instructions**
1. See the plnkr: [http://plnkr.co/edit/mYrqjW?p=preview](http://plnkr.co/edit/mYrqjW?p=preview)
2. Click the blue button on the top-right of the preview section to launch the preview in a separate window (this will allow you to go forward and back in the browser). 
3. Click the "About (lazy)" link to lazy load the About module. The About heading should display on the page and the url should be "/home(lazy:about)"
4. Press backspace or Alt-Left (depending on your browser) to go to the previous page. The url should be "/home". The content from the About module remains on the page.
- **Angular version:** 2.0.2
  
  
- **Language:** [all]
- **Node (for AoT issues):** `node --version` = 4.5.0

**Comment by DzmitryShylovich** [comment]
@suchk can u pls update your plunkr? looks like u had an error in your configuration.

**Comment by suchk** [comment]
From reading through #11208, commit 2c30365 apparently seems to have broken (intentionally disabled?) lazy loading modules in named router outlets. #12842 is now monitoring a similar issue.

**Comment by DzmitryShylovich** [comment]
@suchk can you close this in favor of https://github.com/angular/angular/issues/12842 pls? thx
