### ISSUE TITLE
dgeni output for change_detection vars creates unclickable link

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#1222]
The var links in the change_detection module produce a blank page. Other vars elsewhere in the docs do work, so I think this is something we're doing wrong in the change_detection doc

![screen shot 2015-04-02 at 5 59 02 pm](https://cloud.githubusercontent.com/assets/2286589/6976706/4b38236e-d962-11e4-93bd-b1d86bd87521.png)

**Comment by naomiblack** [comment]
@mhevery can you have a look and see if this is something obvious in our code?

**Comment by petebacondarwin** [comment]
These variables are not being displayed correctly as they are defined directly inside the public module and do not contain description nor the `@publicModule` tag.

For example the `dynamicChangeDetection` variable: https://github.com/angular/angular/blob/master/modules/angular2/change_detection.js#L77

We can get some documentation working by adding an appropriate comment:

```js
/**
 * This is the singleton instance of DynamicChangeDetection
 * @publicModule angular2/change_detection
 */
export var dynamicChangeDetection = new DynamicChangeDetection(_registry);
```

**Comment by petebacondarwin** [comment]
We should probably make it so that we don't need to add the `@publicModule` tag if the export is already inside the public module.

**Comment by petebacondarwin** [comment]
Also, the generated content doesn't look right, which I need to look into...
![screen shot 2015-04-03 at 06 35 39](https://cloud.githubusercontent.com/assets/15655/6978488/bce769a2-d9cb-11e4-8089-e11d2f503c88.png)

**Comment by naomiblack** [comment]
@petebacondarwin can you look into this as part of the M7 milestone (i.e. before our internal release?)
