### ISSUE TITLE
Children routes does NOT work in Firefox

### ISSUE THREAD

**Issue by ayeo** [angular/angular#12236]
```
[x] bug report
[ ] feature request
[ ] support request 
```

Problem 
--------

Firefox does not load component content to router-outlet for children routes. Page is empty (except static main template elements). Everything works perfect using Chrome and Safari. Sample of my routing config file:

```
[
    {
        path: 'chat',
        component: ChatComponent
    },
    {
        path: '',
        component: BaseComponent,
        children: [
            {
                path: 'landing',
                component: LandingComponent
            },
            {
                path: '',
                component: WallComponent
            }
        ]
    }
]
```

Chat component content is loaded just fine. Other component's content is not loaded.

Environment
-------------

OSX 10.12
Angular 2.0.2
Router 3.0.2
Firefox 49
Node 4.4.7

**Comment by skreborn** [comment]
Please provide a [Plunker](https://plnkr.co/) that reproduces your problem. I would also recommend to follow the issue template as closely as possible to make it easier to process for the development team.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by ayeo** [comment]
It turns out it's all my falut. In BaseComponent I have used different selector name (not my-app). Now all works fine. I wonder why it was working in Safari and Chrome berfore? :)
