### ISSUE TITLE
binary download 

### ISSUE THREAD

**Issue by lucamorelli** [angular/angular#12234]
Hi,
  before opening an issue here, I asked in gitter for 2 days without any answer.
  I need to download a binary file from a asp.net core api and start the download from an angular 2 app.
  I have looked around for samples on how to this and I found a few samples stating that at the time the support wasn't ready, but none of these examples works, so I don't know if I'm doing something wrong or the samples are not valid anymore.
  Where can I find more infos?

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
