### ISSUE TITLE
Angular 2 *ngFor only supports to add 10 elements at a time in inline template

### ISSUE THREAD

**Issue by pankajparkar** [angular/angular#12233]
**I'm submitting a **bug**.

```
[x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

I wanted to repeat particular element several amount of time, so I'm using `*ngFor` directive with hard-coded array like `[1,2,3,4,5,6,7,8,9,10]` and that got worked awesome. I achieved what I wanted to do.

**Code**

```
@Component({
  selector: 'my-app',
  template: `<h1>My First Angular App</h1>
      <div *ngFor="let item of [1,2,3,4,5,6,7,8,9,10]">
          {{item}}: My Element 
      </div>`
})
```

[Demo Plunkr][1]

But as soon as I increased the array size more than 10, I start getting below error. Which is really annoying.

> zone.js@0.6.25?main=browser:355 Unhandled Promise rejection:
> Unsupported number of argument for pure functions: 11 ; Zone: <root> ;
> Task: Promise.then ; Value: Error: Unsupported number of argument for
> pure functions: 11(…) Error: Unsupported number of argument for pure
> functions: 11

**Template**

```
<div *ngFor="let item of [1,2,3,4,5,6,7,8,9,10,11]">
  {{item}}
</div>`
```

**Expected behavior**

I'm curious to know why that error is happening as soon as array size increase more than 10? But another interesting thing is when I put the same array in component inside variable `items= [1,2,3,4,5,6,7,8,9,10,11]` and used `items` in `*ngFor` and it got worked.
- **Angular version:** 2.0.1
  
  
- **Browser:** all
- **Language:** TypeScript

**Comment by mxii** [comment]
I don't know why, but its caused by this function: `createPureProxy`
https://github.com/angular/angular/blob/d972d8235458a6e65819f96ee56da059ec76321b/modules/%40angular/compiler/src/view_compiler/util.ts#L82-L93

Which checks this array: `pureProxies`
https://github.com/angular/angular/blob/d972d8235458a6e65819f96ee56da059ec76321b/modules/%40angular/compiler/src/identifiers.ts#L191-L203

**Comment by pankajparkar** [comment]
@mxii I already saw that code(forgot to mention in description), but there I can't find a reason why it allow array with 10 size.

**Comment by skreborn** [comment]
`Identifiers.pureProxies` is defined [here](https://github.com/angular/angular/blob/745e10e6d2ea9097b7ec650ae54cea91e3d193f2/modules/%40angular/compiler/src/identifiers.ts#L191). There have been numerous discussions regarding this in the past, most notably [here](http://www.gitterforum.com/discussion/angular-angular?page=7118).

> **joeherold**: i get an error, if my NgClass object has more than 11 items
> [...]
> **robwormald**: i think there's a hard limit of 10, mostly for performance reasons

Based on this, I'd say that this is by design, and should not be considered a bug. Hope this helps.

**Comment by manklu** [comment]
And the workaround is easy in this case.

```typescript
@Component({
  selector: 'my-app',
  template: `
    <div>
      <h2>Hello {{name}}</h2>
      <div *ngFor="let item of items">
        {{item}}
      </div>
    </div>
  `
})
export class App {
  name:string;
  constructor() {
    this.name = 'Angular2'
  }

  items = [1,2,3,4,5,6,7,8,9,10,11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
}
```

**Comment by pankajparkar** [comment]
@manklu Thanks. I already knew and same thing I mentioned in my answer.

**Comment by DzmitryShylovich** [comment]
I believe it was fixed here https://github.com/angular/angular/pull/12710

**Comment by vicb** [comment]
@DzmitryShylovich 12710 is only about interpolations. The root cause is different here.

**Comment by devAmit14** [comment]
any updates on this issue? I'm also stuck.

**Comment by pankajparkar** [comment]
@devAmit14 You can easily shift your `declaration/assignment` logic from html to component directly as shown in @manklu [comment](https://github.com/angular/angular/issues/12233#issuecomment-253266604).

**Comment by devAmit14** [comment]
I have a situation like -

`<table class="table">
            <thead>
                <tr>
                    <th *ngFor="let name of columns">{{ name }}</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let row of rows">
                    <td *ngFor="let name of columns">
                        {{ row[name] }}
                    </td>
                </tr>
            </tbody>
        </table>`

for static data the table is rendered, but when I get those from an ajax GET, the table isn't bound. no errors at console as well. Any directions?

**Comment by pankajparkar** [comment]
@devAmit14 add plunkr with reproducible problem in it, that way I could help you to solve your issue, Thanks :)

**Comment by alexis-globant** [comment]
Any news about this issue?, I've tried with Angular 2.4.5 and got the same result.

**Comment by DzmitryShylovich** [comment]
@alexis-globant it's done for performance reasons. what's the use case to have such arrays in a template?

**Comment by alexis-globant** [comment]
For example I want to fill a select with the months of year. I know that I can do it using a variable in ts (and already I do it) but I want to know why this option is worst that the other in performance.

**Comment by DzmitryShylovich** [comment]
@alexis-globant it allows to inline code. see `https://www.youtube.com/watch?v=kW9cJsvcsGo`

**Comment by alexis-globant** [comment]
@DzmitryShylovich thank you for the video and the explanation.

**Comment by tbosch** [comment]
This is working now in Angular 4.
