### ISSUE TITLE
Using custom pipes in lazy modules

### ISSUE THREAD

**Issue by homofortis** [angular/angular#12231]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Custom pipes declared in the main app module are not seen in the lazy module components - "Pipe xxx could not be found..." error.  If the pipes are declared in the lazy module instead angular behaves as expected.
**Expected behavior**

Declarations of top level modules should propagate to all components.
**Please tell us about your environment:**

os x
* **Angular version:** 2.0.X

2.01
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 any
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
2.0
* **Node (for AoT issues):** `node --version` =   
6.7

**Comment by RoxKilly** [comment]
This is expected behavior.  The template parser will recognize a directive, component or pipe if and only if it was listed in the `declarations` array of the current `NgModule` or exported by module that the current `NgModule` imports.

If you wish for your pipe to be accessible from multiple modules, declare it in a module that will be imported by the others.  For instance, you could have a `SharedModule` that exports all directives, components and pipes that you want to share.
```
@NgModule({
	imports: [CommonModule],
	exports: [SharedPipe, SharedDirective, SharedComponent]
})
export class SharedModule{
	static forRoot() {
		return {
			ngModule: SharedModule,
			providers: [ //services that you want to share across modules
				SharedService,
				SharedService2
			]
		}
	}
}
```
Your root `AppModule` would list `SharedModule.forRoot()` in its `imports` array.  Your other modules (including lazy-loaded modules) would list `SharedModule` in their `imports` arrays.

**Comment by homofortis** [comment]
@RoxKilly if this is indeed the expected behaviour and the module declarations are separate:
> The template parser will recognize a directive, component or pipe if and only if it was listed in the declarations array of the current NgModule or exported by a module that the current NgModule imports.

then why when I put pipe declaration in the lazy child module Angular is complaining 

`Type` XXX is part of the declarations of 2 modules: AppModule and OrdersModule! Please consider moving XXX to a higher module that imports AppModule and OrdersModule...`

**Comment by gnujeremie** [comment]
It's because it is supposed to be declared only one time. You'll have to use a shared module.

**Comment by homofortis** [comment]
Pardon me but I find this a bit inconsistent. On one hand, to reuse module declarations you have to define modules as shared, on other hand they seem to be interdependent and overlap their declarations. Could please elaborate.

**Comment by gnujeremie** [comment]
You may find more informations https://angular.io/docs/ts/latest/guide/ngmodule.html#!#shared-module here :)

**Comment by homofortis** [comment]
Oh man, this framework is really becoming over-complicated for a web frontend. If this keeps on going it may die of sophistication fatigue :P

**Comment by RoxKilly** [comment]
@homofortis  [The docs state](https://angular.io/docs/ts/latest/guide/ngmodule.html):

> Components, directives and pipes belong to one module — and one module only.

**Comment by homofortis** [comment]
@RoxKilly so then all non-shared declarations should be private and there should be no errors as "Type XXX is part of the declarations of N modules..."

**Comment by RoxKilly** [comment]
@homofortis I bet the designers discussed the pros and cons before coming to the current architecture.  I've never built a framework and I'm not an advanced coder so I won't pretend to have a strong understanding of the issue. I was just trying to help you get past your original error.

**Comment by homofortis** [comment]
@RoxKilly Thanks for your efforts but I believe, this is a place to identify issues and to rectify them, not a place to help someone "get past your original error". Building frameworks experience is irrelevant if it's not helping the process.

**Comment by edoardoo** [comment]
> If you wish for your pipe to be accessible from multiple modules, declare it in a module that will be imported by the others. For instance, you could have a `SharedModule` that exports all directives, components and pipes that you want to share.
> 
> ```
> @NgModule({
>     imports: [CommonModule],
>     exports: [SharedPipe, SharedDirective, SharedComponent]
> })
> export class SharedModule{
>     static forRoot() {
>         return {
>             ngModule: SharedModule,
>             providers: [ //services that you want to share across modules
>                 SharedService,
>                 SharedService2
>             ]
>         }
>     }
> }
> ```
> Your root `AppModule` should list `SharedModule.forRoot()` in its `imports` array. Your other modules (including lazy-loaded modules) should list `SharedModule` in their `imports` arrays.

My two cents: this is not how I expected it to work.

**Comment by edoardoo** [comment]
> This is expected behavior. The template parser will recognize a directive, component or pipe if and only if it was listed in the `declarations` array of the current `NgModule` or exported by a module that the current `NgModule` imports.
> 
> If you wish for your pipe to be accessible from multiple modules, declare it in a module that will be imported by the others. For instance, you could have a `SharedModule` that exports all directives, components and pipes that you want to share.
> 
> ```
> @NgModule({
>     imports: [CommonModule],
>     exports: [SharedPipe, SharedDirective, SharedComponent]
> })
> export class SharedModule{
>     static forRoot() {
>         return {
>             ngModule: SharedModule,
>             providers: [ //services that you want to share across modules
>                 SharedService,
>                 SharedService2
>             ]
>         }
>     }
> }
> ```
> 
> Your root `AppModule` should list `SharedModule.forRoot()` in its `imports` array. Your other modules (including lazy-loaded modules) should list `SharedModule` in their `imports` arrays.

This explanation should be quoted in the docs. Many thanks.

**Comment by sergiy-talashko** [comment]
Also don't understand this mechanic. Here quote from Angular documentation:

> When the Angular router lazy-loads a module, it creates a new injector. This injector is a child of the root application injector. Imagine a tree of injectors; there is a single root injector and then a child injector for each lazy loaded module. The router adds all of the providers from the root injector to the child injector. When the router creates a component within the lazy-loaded context, Angular prefers service instances created from these providers to the service instances of the application root injector.

Main part for me: 

> The router adds all of the providers from the root injector to the child injector.

But in real life lazy loaded module didn't see components and pipes which was declarative in root module.
By all this importing same shared modules into lazy-loaded modules each of them will grow in arithmetic progression.
And as a result, if user visit all pages he will get files which in multiple time bigger that without lazy-loaded modules.

With high-speed internet this lazy-loading looks like bullshit and  wasting of time.

**Comment by mlc-mlapis** [comment]
@sergiy-talashko ... you have to place the modules into the `imports: [...]` section of a lazily-loaded module ... as you need to do the same even in the eagerly loaded modules, but it doesn't mean that those modules are loaded repeatedly from a server ... they are already in the memory, so it's no performance hit at all.

**Comment by sergiy-talashko** [comment]
@mlc-mlapis 
About 1 part: 
I tested this - compare module size in Network tab with/without Shared module in **import** section - it has differ in 0.3Kb even if Shared module was used in previous page. So it will HIT performance.

About 2 part:
I mean that it's strange that lazy-loaded module don't have access to pipe's and component's which was declarated in root module. 
Each lazy loaded module it's a small site which load same module as root app  instead of using already loaded.

I don't know, maybe I am doing something wrong or it will be good in long term use of using lazy-loading when app if REALLY big. But I am not building facebook-size app on each project.

**Comment by mlc-mlapis** [comment]
@sergiy-talashko ...

1) You should check if the shared module isn't bundled with that lazily-loaded module by some mistake. It shouldn't, so if that shared module is a part of the main module (as an eager dependency), it loaded into the memory when the app is starting. Later, when loading a lazily-loaded module, only code for that module should be loaded. The rest is taken from memory.

2) There is a hierarchical tree of injectors: root injector -> child injector (of a lazily-loaded module) and it's true that you can inject anything from a higher injector, but not opposite, so you should be able to use components, pipes, ... from the root (core/main module) ... that's how DI works in general.
