### ISSUE TITLE
Improve async pipe for single object observables

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular#12237]
**I'm submitting a ...**

```
[x] feature request
```

**Current behavior**
_Main motivation:_ print multiple object properties by using the async pipe with **1** network request

For array observables `myObjects$: MyObject[]` you can use the async pipe in the following way:

```
<div *ngFor="let myObject of myObjects$ | async">
  <div>{{myObject.property1}}</div>
  <div>{{myObject.property2}}</div>
  <div>{{myObject.property3}}</div>
</div>
```

The code above will end in **1** network request.

For single object observables `myObjects$: MyObject` you can use the async pipe in the following way:

```
<div>
  <div>{{(myObjects$ | async)?.property1}}</div>
  <div>{{(myObjects$ | async)?.property2}}</div>
  <div>{{(myObjects$ | async)?.property3}}</div>
</div>
```

The code above will end in **3** network requests :(

For sure you could cache the observable `.publishReplay(1).refCount()` (only **1** network request) but all together it looks odd.

**Expected behavior**
Add support for a local template variable e.g.:

```
<div *ngIf="let myObject = myObjects$ | async">
  <div>{{myObject.property1}}</div>
  <div>{{myObject.property2}}</div>
  <div>{{myObject.property3}}</div>
</div>
```

**What is the motivation / use case for changing the behavior?**
Beautiful code for printing multiple object properties by using the async pipe with **1** network request.

**Please tell us about your environment:**
Linux
- **Angular version:** 2.0.2
- **Browser:** All
- **Language:** TypeScript 2.0.3
- **Node (for AoT issues):** 6.7.0

**Comment by pkozlowski-opensource** [comment]
AFAIK @robwormald was thinking about it, good to have an issue tracking this. Thnx for opening.

**Comment by DzmitryShylovich** [comment]
> For sure you could cache the observable .publishReplay(1).refCount()

there's a shortcut - `share()`. But I agree it would be very very useful.

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/2451

**Comment by pkozlowski-opensource** [comment]
@DzmitryShylovich I don't think it is direct duplicate. #2451 _could_ be a solution for the issue at hand but:
* #2451 could be useful regardless of the `async` pipe
* we could think of different solutions for the async pipe issues described here.

As such I'm going to keep both issues opened. But it is good to have them linked, thnx!

**Comment by olegdunkan** [comment]
It will be very useful feature!!!
Now I do this 
````
<div>
  <div>{{(myObjects$.pluck('property1') | async}}</div>
  <div>{{(myObjects$.pluck('property2') | async}}</div>
  <div>{{(myObjects$.pluck('property3') | async}}</div>
</div>
````
or 

````
<div *ngIf="myObject">
  <div>{{myObject.property1}}</div>
  <div>{{myObject.property2}}</div>
  <div>{{myObject.property3}}</div>
</div>
ngOnInit() {
    this.subscribtion = myObjectsObservable.subscribe(object=>this.myObjects=object); 
}
ngOnDestroy() {
    this.subscribtion.unsubscribe();
}
````

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/Sunu2LPQVAaWZvZRcWXb?p=preview

**Comment by DzmitryShylovich** [comment]
@Martin-Wegner it's now possible with the new syntax https://github.com/angular/angular/issues/15020
close the issue please, thanks.

**Comment by Martin-Wegner** [comment]
@DzmitryShylovich thanks for informing me, sounds very good :)
