### ISSUE TITLE
did Angular2 have $compile directive as AngularJS 1?

### ISSUE THREAD

**Issue by sadydai** [angular/angular#12235]
DynamicComponentLoader ? but no use in  2.0.0

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
