### ISSUE TITLE
2.0.0  Can't bind to 'ngClass' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by yaotaiyang** [angular/angular#12240]
```
import {Component} from '@angular/core';
@Component({
    selector: 'left-nav',
    template:`
    <div [ngClass]="'first second'">aaaaabbbbbcccc</div>
    `
})
export class LeftNav {
    constructor(){}
}
```
```
Can't bind to 'ngClass' since it isn't a known property of 'div'. ("
    <div [ERROR ->][ngClass]="">aaaaabbbbbcccc</div>
    "): LeftNav@1:9
```

If I remove `[ngClass]="'first second'"` it works ok.

window 10
Angular version: 2.0.0
Browser: chrome
Language: TypeScript 2.0.2
Node (for AoT issues): 5.7.0

**Comment by DzmitryShylovich** [comment]
Import CommonModule.

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich

**Comment by yaotaiyang** [comment]
@DzmitryShylovich  thank you!

**Comment by Yugloocamai** [comment]
Importing CommonModule doesn't seem to change anything for me.  Could there be another reason for this error?

**Comment by tytskyi** [comment]
@Yugloocamai do you import CommonModule in the same NgModule where your component is in `declarations`

**Comment by dpac4u** [comment]
yes

**Comment by kenstime** [comment]
even follow the fixing suggestion, I still have such issue

**Comment by regosnet** [comment]
I imported the commonModule and it works pretty good for me

**Comment by ahuetWL** [comment]
Same for me, still facing the error after importing CommonModule in the module.ts where my component is declared
