### ISSUE TITLE
Generated ngfactory files can sometimes use an incorrect import path

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#12249]
### What's happening

Attempting to AoT compile an application that consumes the `@angular/material` components. The ngfactory files are generated from the `.ts` sources for the app and from the `.d.ts` and `.metadata.json` files in the material package.

The problem is that the ngfactories generated from the `.ts` sources are attempting to import the ngfactories for the material components from **where the `.d.ts` files live** and not from where the tool itself outputted the ngfactories for the material components (inside the specified `genDir`).
### Steps to reproduce:
- Clone https://github.com/jelbourn/material2/tree/aot-cli
- `npm install`
- `gulp build:release` (creates the `@angular/material` release output in `dist/`)
- `./node_modules/.bin/ngc -p ./src/e2e-app/` (runs `ngc` on the e2e test app)
- `./node_modules/.bin/tsc -p ./src/e2e-app/`

Errors you should see:

```
src/e2e-app/aot/button/button-e2e.ngfactory.ts(20,27): error TS2307: Cannot find module '../../../../dist/@angular/material/button/button.ngfactory'.
src/e2e-app/aot/button/button-e2e.ngfactory.ts(22,27): error TS2307: Cannot find module '../../../../dist/@angular/material/icon/icon.ngfactory'.
src/e2e-app/aot/dist/@angular/material/button-toggle/button-toggle.ngfactory.ts(8,26): error TS2307: Cannot find module './button-toggle'.
src/e2e-app/aot/dist/@angular/material/button-toggle/button-toggle.ngfactory.ts(20,27): error TS2307: Cannot find module '../core/coordination/unique-selection-dispatcher'.
src/e2e-app/aot/dist/@angular/material/button/button.ngfactory.ts(8,26): error TS2307: Cannot find module './button'.
...
```

Node version is 6.3.1, compiler-cli version is 0.6.4

**Comment by alexeagle** [comment]
Related to a long-running issue @mhevery and I were working on.
Since you don't use `rootDirs` in your tsconfig.json, you get the version of `ReflectorHost` that re-writes paths based on having `node_modules` directory.
Here is where it would fix those paths to be relative:
https://github.com/angular/angular/blob/master/modules/@angular/compiler-cli/src/reflector_host.ts#L151
but you fall through because the imported location in dist/ doesn't have a node_modules in the path, nor is it beneath the `basePath` which is the directory containing `tsconfig.json`

**Comment by e-cloud** [comment]
any progress on this? It makes material2 do some hacks about it, and after some update on v4.3, material2's hack breaks compatibility with angular-cli in turn.

**Comment by tbosch** [comment]
This shouldn't be a problem with Angular 5 anymore.
@jelbourn is this still a problem for you in Angular 4?

**Comment by jelbourn** [comment]
@DevVersion can you do a quick check to see if this is still an issue?
