### ISSUE TITLE
Bootstraping of multiple component instances is not possible

### ISSUE THREAD

**Issue by DaSchTour** [angular/angular#12246]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using a component selector multiple time only the first one is bootstraped and event this one is not initialized correctly

**Expected behavior**
All occurrences of the component are fully bootstraped and read their input data

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/4de2kX8myPjR6f6iH8uh?p=preview

**What is the motivation / use case for changing the behavior?**
While migrating to a Single Page Applications multiple components may live independent in a bigger older application. They may dispatch Events and get input from outside and work together with the outside jQuery environment.

**Please tell us about your environment:**
Nothing special

* **Angular version:** 2.0.X (From given base plnkr)

* **Browser:** all
 
* **Language:** TypeScript 2.0.2

**Comment by DzmitryShylovich** [comment]
1. You cannot have multiple root elements with the same selector. It would only work like this http://plnkr.co/edit/gd8ZthFVtUOxWCMk56ek?p=preview
2. Root component cannot have inputs.

**Comment by DaSchTour** [comment]
So angular2 is worthless to create web components for an non-SPA. That's insane. What a giant backstep from angular 1 😞 
It's strange that Angular 1.5 with ng-metadata works so much better than angular2 itself. It looks like angular2 was developed for utopia and not the real world.

**Comment by DaSchTour** [comment]
Is it possible, that even using `<ng-content>` to make a body wrapper while preserving the content of a page doesn't work, because ng-content removes other components? It's a total mess. I'm really curious if angular 2 was developed for other apps than the hero turorial 😕

**Comment by alxhub** [comment]
@DaSchTour, I've been able to turn Angular2 components into web components using dynamic component creation via the factory APIs: http://plnkr.co/edit/IdrboIPrDL69laBX1bXZ

As @DzmitryShylovich said though, you cannot match multiple elements in bootstrap, nor can you pass properties to root components. So I'm going to close this issue as this is WAI as far as Angular is concerned.

**Comment by DaSchTour** [comment]
Way to complicated. Looks like angular 1.5 + ng-metadata is the better "angular 2" than angular 2 itself 😆
