### ISSUE TITLE
DynamicComponentLoader Migration Notes missing

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#12244]
ChangeLog says : 

core: deprecated DynamicComponentLoader was removed; see deprecation notice for migration instructions.

But where is Migration notes ?

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by DzmitryShylovich** [comment]
Use ComponentFactoryResolver instead of DCL. Example http://plnkr.co/edit/kkM1aR4yPcIqeBhamoDW?p=preview

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich

**Comment by vasuneet** [comment]
THANKS.

**Comment by DzmitryShylovich** [comment]
@vasuneet works fine http://prntscr.com/ctfery
try to reload several times
