### ISSUE TITLE
Unit test for Component - template not updating on click in test (Angular final)

### ISSUE THREAD

**Issue by gituser7878-Ultralinq** [angular/angular#12242]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am not able to click something in the template, and have that change registered in either the template, or variables associated with the component (for example neither {{_aVar}} binding in the template, nor fixture.componentInstance._aVar show any changes)

**Expected behavior**

The component's variable and its template binding would change, when something is clicked in the component's template during the test.

**Minimal reproduction of the problem with instructions**

In a "describe" statement, use TestBed's configureTestingModule to declare a component in a beforeEach. Then in an "it" async statement, do TestBed.compileComponents, then create the component (assume the component's actual template will be loaded). Grab an HTML element with querySelector or something similar, and then click it (using nativeElement.click() ). Use querySelector or something similar to grab that div or HTML element, and see if it has changed due to the click (for example, if a variable in the HTML element changed). In the bug, nothing changes.

**Easy code snippet start:**

    describe('TestMeCmp unit tests', () => { 
      beforeEach(() => {

            TestBed.configureTestingModule({
                declarations: [TestMeCmp]
            });
        });

    it('Unit tests', async(() => {
    TestBed.compileComponents().then(() => {
    let fixture: any = TestBed.createComponent(TestMeCmp);

    const elWithVar = el.queryAll(By.css("td"));
    elWithVar[0].nativeElement.click();
    expect(elWithVar[0].nativeElement.textContent).toBe("My variable binding should have changed!");

    });
    });

    });

**Easy Code Snippet end**

**What is the motivation / use case for changing the behavior?**
I imagine that the Angular 2 team, expects direct template interaction and updates to be a working unit test feature?

**Please tell us about your environment:**
Mac OSX, PhpStorm, NPM and using SystemJS module loader.

* **Angular version:** 2.0.0 final

* **Browser:** 
Chrome browser running tests with Karma test runner, or Electron browser running tests with Karma test runner
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
The tests are run as their spec.js files (hence ES5), but originally written in Typescript 1.8.10.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gituser7878-Ultralinq** [comment]
@pkozlowski-opensource, I believe this is a bug. I cloned the official angular2-quickstart which the Angular testing guide refers to and tried doing real template updates in its tests, and they didn't work.

**Comment by DzmitryShylovich** [comment]
See https://github.com/juliemr/ng2-test-seed

**Comment by gituser7878-Ultralinq** [comment]
@DzmitryShylovich, I have seen @juliemr's ng2-test-seed repo several times and it has been very helpful with Angular changes. But the greeting-component_test.ts file doesn't work (I believe it is skipped, because I wrote something to make it fail and still didn't see a failure in my terminal window), and it does have examples of clicks needing to update the template.

**Comment by pkozlowski-opensource** [comment]
@gituser7878-Ultralinq you need to call `fixture.detectChanges();` after `click()`. Here is a real-life example: https://github.com/ng-bootstrap/ng-bootstrap/blob/b8230e5cb39b262c61c118e50e1cc5e33a334f96/src/collapse/collapse.spec.ts#L62-L81

I still believe that this is a support question. You didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by gituser7878-Ultralinq** [comment]
@pkozlowski-opensource, your Github example uses overrideComponent and sets the template.

I am using an unaltered template for the component. I will post a Plunkr shortly.

**Comment by gituser7878-Ultralinq** [comment]
I have spent a little time trying to create a Plunkr with SystemJS and the latest Angular 2 to run tests, no success so far. Will try to post it sometime. If anyone else has such a readymade Plunkr environment or link to it, please let me know.

**Comment by gituser7878-Ultralinq** [comment]
The ng2-test-seed's github repo does run the template change in its test.
