### ISSUE TITLE
Paths of imports from outside of root directory are not updated to target compiled files

### ISSUE THREAD

**Issue by mug3n** [angular/angular#12245]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When compiling the project that has imports from outside of the root directory (shared/components/*), the path in the ngfactory file is targeting the generated ngfactory of the import in the source directory of the import, instead of the directory it's been compiled to.

**Expected behavior**
The import paths should be adjusted in order to properly target the compiled files.

**Minimal reproduction of the problem with instructions**
https://github.com/mug3n/bug-report-ngc

**What is the motivation / use case for changing the behavior?**
It's not working as intended, as the files are being compiled, but being looked for in wrong locations.

**Please tell us about your environment:**
Fedora release 23 (Twenty Three), WebStorm.
The same can be reproduced on OS X

* **Angular version:** 2.0.1

* **Browser:** [all]
 
* **Language:** [TypeScript X.X]

* **Node (for AoT issues):** v5.10.1

**Comment by mug3n** [comment]
Seems to be the same as #12249

**Comment by tbosch** [comment]
Closing as a duplicate.
