### ISSUE TITLE
Drag'n'drop

### ISSUE THREAD

**Issue by AOlefirenko** [angular/angular#1225]
Is/will there a pain-free way to drag'n'drop items between lists without the DOM modifications?  I think It's important as well as Overlay Service. It would be nice to have clear API that allows customize drag-helper(include animations), receive events, use any engine (mouse/touch events, html5 drag'n'drop).  It's just a proposal and need some investigation.

**Comment by oliverjanik** [comment]
Good question. Having recently implemented Drag&drop using HTML5 API for ng-repeats. I had to do DOM manipulation myself then modify the scope and let angular rerender everything. All this just to prevent flicker.

**Comment by mhevery** [comment]
This is a generic question, not an issue, Closing.

It should be possible to write drag and drop directives for angular. We are not planning on including it in core for now.
