### ISSUE TITLE
Timeout operator doesn't work on extended Http

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular#12258]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

When I extend `Http` class to add a timeout setter using rxjs, the `timeout` operator doesn't work when I import it like this ` import 'rxjs/add/operator/timeout'`

`Error: Uncaught (in promise): TypeError: _super.prototype.get.call(...).timeout(...).catch is not a function(…)
`

It only works when I load the entire rxjs library, [live plnkr](https://plnkr.co/edit/kQTFLWjZ8lEtlN3Oe1wu?p=preview)

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by MurhafSousli** [comment]
No problem
