### ISSUE TITLE
Integration Chrome Lighthouse metrics into Benchpress

### ISSUE THREAD

**Issue by tbosch** [angular/angular#12252]
See https://github.com/GoogleChrome/lighthouse/

**Comment by manekinekko** [comment]
@tbosch is this feature still relevant?

**Comment by tbosch** [comment]
Yes

**Comment by manekinekko** [comment]
Do we have a list about what metrics we want into benchpress?

**Comment by tbosch** [comment]
@manekinekko mostly TTI, which we could also measure without lighthouse...

**Comment by manekinekko** [comment]
Gotcha. Will look at this tomorrow and keep you updated.

BTW, I'm working on a UI for benchpress https://github.com/manekinekko/perfy
Would love to have your feedback on this.

**Comment by tbosch** [comment]
@manekinekko Oh, before you do this, it would amazing if you could take a stab at https://github.com/angular/angular/issues/15623, as this will probably change the way you implement the new metric...

**Comment by tbosch** [comment]
Regarding perfy: looks nice!
