### ISSUE TITLE
AoT uses a lot more resources in browser than JiT

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#12253]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report (maybe)
```

**Current behavior**
When I use the Ahead-of-Time compiler -- `ngc` -- along with `rollup.js` to build my app, it consumes a lot more CPU cycles in the browser than Just-in-Time.  The resulting bundle is also significantly larger.

**Expected behavior**
AoT with tree-shaking to result in a smaller, less resource-hungry application. I was so shocked by my observation that I've re-run the tests below over a dozen times now.

**Minimal reproduction of the problem with instructions**
1. I started the browser (`Firefox 49 32bit` on `Windows 7 x64`), 
2. let it sit idle for a couple of minutes, 
3. loaded the app in the only open tab
4. let the app sit idle for a minute, recording CPU/IO activity using Windows' Performance Monitor

The AoT build is more resource hungry. In addition, its JS bundle (which has been minified and tree-shaken with `rollup`) is about 500KB _larger_ than its JiT compiled counterpart.

AoT compiled bundle + `vendor.js` (made up of `core-js`, `reflect-metadata` and `zone.js`):

![aot_size](https://cloud.githubusercontent.com/assets/12346501/19327754/7e05af10-909e-11e6-94f5-06a39b2c5824.png)

AoT CPU and IO operations starting 5 seconds before I load the app, extending for 1 minute:

![aot_perf](https://cloud.githubusercontent.com/assets/12346501/19327782/9fe1d2ee-909e-11e6-8b1b-abb8370159bf.png)

The app was optimized following the [directions from the docs](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#compile). I've also tried bundling the AoT build with `SystemJS-builder`, and avoid `Rollup.js` altogether, but the performance differential remained.

Now checkout the same exact app using in-browser, Just-in-Time compilation. The templates and styles have been inlined and all the JS bundled into one minified file using `SystemJS-builder`'s [`buildStatic`](https://github.com/systemjs/builder#self-executing-sfx-bundles)

JiT compiled bundle is about 500KB _lighter_ than the AoT tree-shaken minified bundle, even though the former includes `core-js`, `reflect-metadata` and `zone.js`!

![5](https://cloud.githubusercontent.com/assets/12346501/19327821/e1a5067e-909e-11e6-83f3-9e318b4a70fe.png)

JiT CPU and IO operations starting 5 seconds before I load the app, extending for 1 minute:

![jit_perf](https://cloud.githubusercontent.com/assets/12346501/19327848/fac3eff8-909e-11e6-836b-c24c1709e06f.png)

Can anyone replicate this? If not, how can I find out why it's happening to my app?

**What is the motivation / use case for changing the behavior?**
I'd like to use AoT builds, and although they load faster, their latent power consumption makes them a non-starter.

**Please tell us about your environment:**
`Firefox 49 32bit`, `Angular 2.0.1`, `ng2 compiler-cli 0.6.3`, `node 4.5.0`, `Windows 7 x64`

**Comment by DzmitryShylovich** [comment]
You can reduce the size of the bundle:
1. lazy loading.
2. gziping.

**Comment by RoxKilly** [comment]
@DzmitryShylovich  Thanks. I don't think I could make the app public. If you tell me how you would measure app size I'd be happy to provide a metric.

```
  "dependencies": {
    "@angular/common": "~2.0.1",
    "@angular/compiler": "~2.0.1",
    "@angular/compiler-cli": "~0.6.3",
    "@angular/core": "~2.0.1",
    "@angular/forms": "~2.0.1",
    "@angular/http": "~2.0.1",
    "@angular/platform-browser": "~2.0.1",
    "@angular/platform-browser-dynamic": "~2.0.1",
    "@angular/platform-server": "~2.0.1",
    "@angular/router": "~3.0.1",
    "@angular/material": "2.0.0-alpha.9-3",

    "chart.js": "^2.2.2",
    "core-js": "^2.4.1",
    "crypto-js": "^3.1.6",
    "hammerjs": "^2.0.8",
    "intl": "1.2.5",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25",
  }
```

**Comment by DzmitryShylovich** [comment]
Have a look at https://github.com/qdouble/angular-webpack2-starter
It has the same dependencies as you + ngrx and after aot build the final bundle size is 209kb (minified and gziped).

**Comment by ericmartinezr** [comment]
side note : with AoT you don't need reflect-metadata nor core-js implementation of it

**Comment by RoxKilly** [comment]
@ericmartinezr interesting; why is that?
@DzmitryShylovich thanks for the tip

**Comment by manklu** [comment]
>  In addition, its JS bundle (which has been minified and tree-shaken with rollup) is about 500KB larger than its JiT compiled counterpart.

The AOT bundle contains all the code generated by the JIT. So I would expect that the AOT build is larger than the JIT, if the Application is large enough.

But without your application, it's hard to tell if I would expect 500KB in your case.

**Comment by robwormald** [comment]
Using Windows CPU profiler is a pretty poor metric for anything related to JS, as you're measuring what the browser itself is doing, not what code running within it is doing.

I'd suggest doing some tracing with Chrome's developer tools - https://developers.google.com/web/tools/chrome-devtools/rendering-tools/js-execution - this would give us all a much better picture of what's actually occurring in your application. You can export and share the trace from devtools, and link it here.

**Comment by thelgevold** [comment]
Did you take a peek into the bundle to make sure it only contains expected modules?
I have often found it useful to inspect the bundle using `source-map-explorer` to ensure the bundle only contain the intended bits. 

There is a section in the AoT article about this.

**Comment by RoxKilly** [comment]
@thelgevold I mentioned in the OP that the AoT and JiT are the exact same app, just built differently.

@robwormald Thanks for the tip. Hopefully the info below will help guide the discussion.

I've been running more tests. The issue (AoT app requiring much more CPU work than JiT) occurs both on `Firefox 49` and `Chrome 54`.

How I collected the data:
 
 - fresh install of both browsers, with default settings and no add-ons or plugins
 - restart the browser between tests, and load only one tab, which contains the app
 - let browser sit idle for at least 30 seconds
 - record performance for 20 seconds with [Chrome CPU profiler](https://developers.google.com/web/tools/chrome-devtools/rendering-tools/js-execution) and with [Firefox performance profiler](https://developer.mozilla.org/en-US/docs/Tools/Performance/How_to) 
 
`JiT` idle app: waterfall chart (firefox)
![jit_waterfall_firefox](https://cloud.githubusercontent.com/assets/12346501/19429257/ae87a6ee-941c-11e6-98ac-7d897294b8c1.png)

`AoT` idle app: waterfall chart (firefox): `requestAnimationFrame` from `ZoneTask` is called infinitely but not sequentially (timelines overlap)
![aot_waterfall_firefox](https://cloud.githubusercontent.com/assets/12346501/19429437/b4ee91ae-941d-11e6-928f-6f7c164dca03.png)

`JiT` idle app: call tree (firefox)
![jit_calltree_firefox](https://cloud.githubusercontent.com/assets/12346501/19429277/c4e7dd96-941c-11e6-9833-d51306af5f9d.png)

`AoT` idle app: call tree (firefox)
![aot_calltree_firefox](https://cloud.githubusercontent.com/assets/12346501/19429283/d217f140-941c-11e6-9c0d-d56d660ce3bf.png)

`JiT` idle app: flame chart (firefox)
![jit_flamechart_firefox](https://cloud.githubusercontent.com/assets/12346501/19429289/dfb3f09c-941c-11e6-911e-f44d966b6038.png)

`AoT` idle app: flame chart (firefox)
![aot_flamechart_firefox](https://cloud.githubusercontent.com/assets/12346501/19429298/e6b1d21a-941c-11e6-869c-fca2dc16d67d.png)

 I'm attaching a zip file with four files:
 - `jit_perf_chrome` JiT cpu profile recorded by Chrome
 - `aot_perf_chrome` matching AoT profile
 - `jit_perf_firefox` JiT performance profile recorded by Firefox
 - `aot_perf_firefox` matching AoT profile

[performance_profiles.zip](https://github.com/angular/angular/files/532650/performance_profiles.zip)

Both browsers allow you to import the files from within dev tools and take a closer look: from the `Profile` tool in Chrome, or the `Performance` tool in Firefox.

Interestingly, as soon as I minimize the browser window, CPU usage goes back down to JiT-compiled levels. Once I return focus to the window, usage goes up again.

**Comment by RoxKilly** [comment]
This has to do with `Angular Material` [`MdSpinner` component](https://github.com/angular/material2/issues/1570). For some reason, AoT compilation consumes tons of CPU when my template includes this component, but JiT compilation does not.

**Comment by RoxKilly** [comment]
Closing: [See this issue](https://github.com/angular/material2/issues/1570#issuecomment-258949029)
