### ISSUE TITLE
NgModule dynamically loaded - check if already present/loaded

### ISSUE THREAD

**Issue by meriturva** [angular/angular#12264]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We load a lot of modules by SystemJs and Angular 2 compiler...for example:
```
System.import(modulePath)
       .then((module: any) => {
            moduleType = module[moduleTypeName];
            componentType = module[componentTypeName];
                            return this.compiler.compileModuleAndAllComponentsAsync(<any>moduleType);
                        })......
```

Now i just would like to know, next cycle for example, if module is already loaded and compiled by angular 2.... so how i could get directly right componentFactory and create a new one without load again and again same modules?
What do you think @tbosch ? is it already implemented?

**What is the motivation / use case for changing the behavior?**
Just to have more control on compiler.

**Comment by b-strauss** [comment]
Doesn't `compileModuleAndAllComponentsAsync` return a Promise? Can't you listen to that?

**Comment by meriturva** [comment]
@b-strauss Your reply is not regarding feature request. I mean...if i have to call again `compileModuleAndAllComponentsAsync` because user wants to add a new widget why do i have to compile again the same module?

**Comment by tbosch** [comment]
The only way to recompile a component is to recompile the module that contains it.
So if nothing changed, use the existing moduleRef. And if something changed, recompile the module.

**Comment by meriturva** [comment]
@tbosch I don't want to recompile module i just would like to know if module is already compiled and get it to load dynamically another component. The only way is to save module ref? no way to as to compiler if already present?

**Comment by michaels7** [comment]
@meriturva Could you please give a short and complete example of your code that loads a module and its components by using System.import and compileModuleAndAllComponentsAsync? If yes, please add an example of a module that then can be loaeded as well.

> System.import(modulePath)
       .then((module: any) => {
            moduleType = module[moduleTypeName];
            componentType = module[componentTypeName];
                            return this.compiler.compileModuleAndAllComponentsAsync(<any>moduleType);
                        })......
