### ISSUE TITLE
Unbind a global listener (Renderer.listenGlobal())

### ISSUE THREAD

**Issue by brunsten** [angular/angular#12269]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
You cannot unlisten to a rendered.listenGlobal()
**Expected behavior**

You should be able to unlisten
**Minimal reproduction of the problem with instructions**

In a component with a ``private renderer: Renderer``

      this.renderer.listenGlobal('document', 'click', (event) => {
           // Something happens
       });
**What is the motivation / use case for changing the behavior?**

you may want to be able to kill this listener. 

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Cannot find any documention that this feature is in a later Angular version that 2.0.0 which I am using. 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.2
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
```
this.listener = this.renderer.listenGlobal('document', 'click', (event) => {
       // Something happens
});

 ngOnDestroy() {
        if(this.listener) {
            this.listener();
        }
    }
````

**Comment by brunsten** [comment]
@DzmitryShylovich I dont know what you are trying to point out, 
but you may want to remove the listener before the component is destroyed.

**Comment by msegers** [comment]
@brunsten this.listener() <- unsubscribes

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
