### ISSUE TITLE
Named router outlet not working

### ISSUE THREAD

**Issue by doorman02** [angular/angular#12265]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Named router outlet does not show the component specified in the named router path.

**Expected behavior**

Named router outlet should show the component specified in the named router path.

**Minimal reproduction of the problem with instructions**
I am trying to use named outlets. In app.routes I have the following path.
`{ path: 'home', component: HomeComponent, outlet: 'home' }`

app.component.html contains
```
 <router-outlet name="home"></router-outlet>
 <router-outlet></router-outlet>
```
The home outlet never displays the home component. If I remove the outlet name from the router path the unnamed outlet will show the HomeComponent. I am using the latest Angular 2. Any idea why the named outlet doesn't work?

https://plnkr.co/edit/l2Li0sLbbEIRZCppRlvF?p=preview
Here is working plunkr, you only need to look into app.comoponent.ts . If you click the links to Crisis Center or Hereos I would expect the navigated components to appear inside the red named outlet zone. I forked this plunkr and it is using Angular2 .Beta.

**What is the motivation / use case for changing the behavior?**

I was trying to find a concrete example or plunkr were named outlet are being used with the latest  Angular 2.0. Is named router outlet yet available in Angular 2.0?

**Please tell us about your environment:**

Windows 10, Visual Code, npm

* **Angular version:** 2.0.X

Angular 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome latest
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.2

* **Node (for AoT issues):** `node --version` =

**Comment by nibbleswap** [comment]
It may be related to the fact that at the moment one of the outlets need to be the default/primary outlet. See my issue and discussion here: https://github.com/angular/angular/issues/11965 . As there is no fix coming in 2.x (as they claim it would be breaking) you may want to work around it.

**Comment by brandonroberts** [comment]
@doorman02 that v2 router is long gone and has been replaced with the v3 router. If you want to see how to use named outlets, see here: http://vsavkin.tumblr.com/post/146722301646/angular-router-empty-paths-componentless-routes

**Comment by doorman02** [comment]
Thanks for your feedback the problem was that I had to leave the path property empty like this

`{ path: '', component: HomeComponent, outlet: 'home' }`

**Comment by pkozlowski-opensource** [comment]
Sound like a support request that got resolved, thnx @brandonroberts !

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781522/6acc29e6-b7be-11e6-9544-b45c558840be.png)
![Uploading 图片.png…]()

**Comment by dmitrysteblyuk** [comment]
{ path: '', component: HomeComponent, outlet: 'home' }

Wow that's a perfect solution. With an empty path it's like not using router at all.

Only it doesn't solve the issue because named outlets with a non-empty path still not working..

**Comment by diegocurbelo12** [comment]
Hi all, after a few hours trying to solve, this post solve my issue...
https://www.bennadel.com/blog/3346-named-outlets-require-non-empty-parent-route-segment-paths-in-angular-4-4-4.htm

Regards,
Diego
