### ISSUE TITLE
undefined access in the custom validator for class properties

### ISSUE THREAD

**Issue by slyerrr** [angular/angular#12261]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 
```

**Current behavior**
When i create custom validator and i want to have access for instance for this.someVariable then it is undefined  in customValidator function.

Then inside streetValidator function we dont have access to class variables. Why ?

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
If you want to have extended/collapse forms where user can choose extended form or basic form then you need to create FormGroup with all input fields and you don't want to have validators.required set for input field that is hidden because user choose basic not extended form.
Our form will not be valid if we set Validators.required for input field that is shown only in extended form version.

**Please tell us about your environment:**
Windows 7

* **Angular version:** 2.0.X
Angular final 2.0

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls provide working reproduction in plunkr.

**Comment by kara** [comment]
@slyerrr It's difficult to determine exactly what you're reporting, given no demo code. I'm closing for now for insufficient info.  Feel free to open a new issue with a minimal repro on plunker.
