### ISSUE TITLE
Router: canActivateChild can't find guard provided in own module

### ISSUE THREAD

**Issue by pesimeao** [angular/angular#12275]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When trying to use a children guard (canActivateChild) in the same module where the guard is provided, the guard fails to be injected.

`Error: No provider for ChildGuard!`

If we provide the guard in a parent module, it works.
If we provide the a canActivate guard in the same module where it is used, it works.

**Expected behavior**

The guard should be injected and work like the canActivate guard.

**Minimal reproduction of the problem with instructions**

Demo can be found here: ~~http://plnkr.co/edit/JeLBnEgkoaHh4wDe9MAd?p=preview~~ http://plnkr.co/edit/vc35AC1UIbZtlp0IjekX?p=preview
1. Click on "Go to route with child guard" button.
2. See error in console: Error: No provider for ChildGuard!

What happens:
- when click on the button, router navigates to /admin
- AdminModule provides ChildGuard service
- Default route in AdminModule (empty) uses ChildGuard `canActivateChild: [ChildGuard]`

**What is the motivation / use case for changing the behavior?**

I have to protect all the child routes using a guard that is only known by that module, loaded by lazy-mode.

**Please tell us about your environment:**

Windows 10 Enterprise
Chrome 53.0.2785.116 m (64-bit)
IIS
- **Angular version:** 2.1.0
- **Angular version (router):** 3.1.0
  
  
- **Browser:** Chrome 53.0.2785.116 m (64-bit)
  
  
- **Language:** TypeScript 2.1.0-dev.20160811
- **Node (for AoT issues):** `node --version` =  v5.9.1

**Comment by DzmitryShylovich** [comment]
Can u pls simplify plunkr and remove all unnecessary components/services?

**Comment by pesimeao** [comment]
@DzmitryShylovich The plunkr is a fork of the official demo with minimal changes (only 4 changes - see first message) in order to reproduce the problem

**Comment by vicb** [comment]
Can you please keep only what's needed to demonstrate the issue ?

**Comment by pesimeao** [comment]
Hi,

Here's a new plnk that contains only the necessary information.
http://plnkr.co/edit/vc35AC1UIbZtlp0IjekX?p=preview

When you access to /admin (click on button "Go to route..."), there's an error in the console `No provider for ChildGuard!`.

This guard is provided in the AdminModule and used only in AdminModule.

**Comment by pesimeao** [comment]
I've also updated the first post ;)

**Comment by DzmitryShylovich** [comment]
@vicb isn't it the same as https://github.com/angular/angular/issues/12995?

**Comment by marvinscharle** [comment]
This also affects `entryComponents`. They cannot be used outside the lazy loaded module.

**Comment by DzmitryShylovich** [comment]
@marvinscharle pls provide a small demo on Plunkr

**Comment by marvinscharle** [comment]
@DzmitryShylovich here you go: http://plnkr.co/edit/9euisYeSNbEFrfzOhhzf?p=preview

I created a simple setup, similar to what we use internally today. `Main` component provides a method to render a `Type`. `EntryComponent` is declared as `entryComponent` in `Page1Module`. However, when trying to render `EntryComponent` via `ComponentFactoryResolver`,  `No component factory found for EntryComponent` is thrown.

Use-cases for this approach are: 

- Modals that shall be rendered in the root component
- Notifications
- etc.

**Comment by DzmitryShylovich** [comment]
@marvinscharle the original issue was fixed. can you pls check out your issue with entry components after the next release and file a new bug if it wasn't fixed?
