### ISSUE TITLE
url is not updating when using browsers's navigation

### ISSUE THREAD

**Issue by jorawarsingh** [angular/angular#12272]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
using navigation arrows is not updating url.

**Expected behavior**
when i navigate to a different page through a link button and later click back button from browser should also change the url, it is taking me back but without refreshing the url. IT remain same

**Minimal reproduction of the problem with instructions**
I have this https://github.com/blinfo/AnnualReportWeb. Just clone don npm i and npm start and then try to navigate to another page by clicking signin and hen go back with browser button and see url is not updateing.

**What is the motivation / use case for changing the behavior?**

if user wish to navigate through the browser navigation buttons then it also should update the url.
**Please tell us about your environment:**
Window10.

* **Angular version:** 2.0.X
2.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.6.0
Thanks for the help in advance!

**Comment by DzmitryShylovich** [comment]
Pls update all angular dependencies. Does the issue still persist?

**Comment by jorawarsingh** [comment]
Yes i have all the latest dependencies. the issue still persist
```
 "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "rxjs": "5.0.0-beta.12"
```

**Comment by DzmitryShylovich** [comment]
You have error in your app http://prntscr.com/ctb343

**Comment by jorawarsingh** [comment]
sorry for this. i never pushed the latest code yet, but now it is pushed. again sorry for this happened.

**Comment by DzmitryShylovich** [comment]
I can reproduce your issue but you have a lot of errors in your code (your should import BrowserModule only once in AppModule, RouterModule.forRoot should be called once etc). Pls read router docs https://angular.io/docs/ts/latest/guide/router.html

**Comment by DzmitryShylovich** [comment]
Fixed config and everything works as expected so the issue can be closed.

**Comment by jorawarsingh** [comment]
Ok i will check and close this issue. Thanks a lot for helping
