### ISSUE TITLE
Router - parent params in children

### ISSUE THREAD

**Issue by smilovanovic** [angular/angular#12273]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Route parent params is an empty object when child route is lazy loaded module

**Expected behavior**
Should have all parent params

**Minimal reproduction of the problem with instructions**

Parent module routes:
```
const parentRoutes: Routes = [
    {
        path: ':parentId',
        component: ParentComponent,
        children: [
            {path: '', pathMatch: 'full', redirectTo: 'child'},
            {path: 'child', loadChildren: 'app/modules/child/child.module#ChildModule'}
        ]
    }
];
```

Child component constructor:
```
constructor(private route: ActivatedRoute) {
    this.route.parent.params.forEach((params: Params) => {
        console.log(params);
    });
}
```

console.log is logging empty object

**Please tell us about your environment:**

* **Angular version:** 2.1.0

* **Browser:** all

 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =  6.7.0

**Comment by DzmitryShylovich** [comment]
Pls provide working reproduction in plunkr.

**Comment by smilovanovic** [comment]
Ok, sorry about this, everything works fine it was a mistake on my part. Close/delete this
