### ISSUE TITLE
Ng-Disabled wont prevent Ng-click if it's not a button

### ISSUE THREAD

**Issue by camjocotem** [angular/angular#12271]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently ng-disabled only affects ng-clicks on inputs and buttons

**Expected behavior**

It would be nice if this could apply to other elements regardless of if it's a button or not

**Minimal reproduction of the problem with instructions**

I have personally used ng-click on an 'a' tag while also including ng-disabled,
an example of this is [here](http://plnkr.co/edit/BMbj71giAoUKQ6CHePRl?p=preview)

**What is the motivation / use case for changing the behavior?**

Received custom designed buttons using 'a' tags in the design.

**Please tell us about your environment:**

OS: Windows 7,
IDE: Brackets,

* **Angular version:** Angular 1.5.5

* **Browser:** All

* **Language:** All

**Comment by DzmitryShylovich** [comment]
Wrong repo. Pls re-open https://github.com/angular/angular.js/issues

**Comment by camjocotem** [comment]
Apologies, I'll do that now
