### ISSUE TITLE
Router issue in encoding characters when refreshing same page multiple time.

### ISSUE THREAD

**Issue by onkark** [angular/angular#12276]
**Current behavior**
Issue in angular: 2.0.2,

I have a space in url  
Initially URL look like  #/due-diligence/Corporate%20RAP/17300
After first refresh URL get changed to due-diligence/Corporate%2520RAP/17300
After next refresh URL get changed to due-diligence/Corporate%252520RAP/17300
and so on.

**Expected behavior**
URL always should look like #/due-diligence/Corporate%20RAP/17300 regard less of how many time I refresh page.

I am using same code auth-guard.service as provided in https://angular.io/docs/ts/latest/guide/router.html

`canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
        let url: string = state.url;
        return this.checkLogin(url);
 }`

Here state.url giving double encoded value

**Comment by DzmitryShylovich** [comment]
Pls provide a working reproduction.

**Comment by vsavkin** [comment]
@onkark please provide a plunkr with a repro

**Comment by onkark** [comment]
I am working on sample, should have it out there in a day or two.

**Comment by vsavkin** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue with a plunkr reproducing the problem.
