### ISSUE TITLE
Bootstrapping (applicationRef.bootstrap) additional Components breaks Router-Back-Navigation

### ISSUE THREAD

**Issue by mseemann** [angular/angular#12282]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Bootstrapping (applicationRef.bootstrap) additional Components breaks Router-Back-Navigation

**Expected behavior**
Router-Back-Navigation works even if an additional Component is bootstrapped.

**Minimal reproduction of the problem with instructions**
Plunker that reproduces the issue: http://plnkr.co/edit/8Bd7mLtKKxTeyWVUHZ2u?p=preview
- you need to open the plnkr in a new window to see the url.
- please open the console. trace for router is activated 

Steps:
- you see the Home-Route: ok.
- click "Themes": ok.
- navigate Back (Browser Back button): you see "Home": ok.
- click "Themes": ok.
- click "Badges":  not ok. you see that all router events fires twice (at this moment the additional component is bootstrapped via applicationRef.bootstrap)
- navigate Back (Browser Back button): not ok. you see the "Theme" content but the window url is still "badge". also the console logs NavigationCancel events  (for example: Navigation ID 28 is not equal to the current navigation id 30)
- navigate Back (Browser Back button): not ok. you still see the "Themes" content with window url theme. But this has been the router state in the step before. 

**What is the motivation / use case for changing the behavior?**
I need to bootstrap an additional component that is somewhere in the html.

**Please tell us about your environment:**

- mac, node 5.10, webpack 2, plnkr is systemjs
- **Angular version:** 2.1.0, 2.0.2
  
  
- **Browser:** [all ]
  
  
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  TypeScript 2.0.3

**Comment by DzmitryShylovich** [comment]
If you want to dynamically create component you should use ComponentFactoryResolver

**Comment by mseemann** [comment]
@DzmitryShylovich as far as i know this is only true for components that are part of the app - e.g. are childs of the root app element. as stated what i want is: "I need to bootstrap an additional component that is somewhere in the html."

**Comment by DzmitryShylovich** [comment]
Repro doesn't work http://prntscr.com/cthsbk

**Comment by mseemann** [comment]
the router needs a base-href obviously the url changes in the plnkr. please correct this in the index.html: it is now `<base href="/Fghm3qeVYXbHB05W/">` and needs to be adjusted with your dynamic path.

**Comment by JohannesAtGit** [comment]
I have a similar problem.
The url is not changed correctly and the history becomes corrupt.
On browser button back, location.back() and window.history.back().

**Comment by DzmitryShylovich** [comment]
@JohannesAtGit do u also bootstrap cmp outside angular?

**Comment by JohannesAtGit** [comment]
I use angular-cli and my main.ts looks:
```
import './polyfills.ts';

import {platformBrowserDynamic}    from '@angular/platform-browser-dynamic';

import {enableProdMode} from "@angular/core";
import {environment} from "./app/environment";
import {AppModule} from "./app/app.module";

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule);
```

app.module.ts

```

@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    routing,

    RequirementModule,
    ImageUploadModule,
    AuthenticationModule,
    ConceptModule,
    ConceptVersionModule,
    SolutionModule,

    SharedModule.forRoot()
  ],
  declarations: [
    AppComponent,
    AboutComponent
  ],
  providers: [
    AuthenticationService,
    AuthGuard,
    BaseRequestOptions,
    {provide: 'Window', useValue: window}
  ],
  bootstrap: [AppComponent]
})

export class AppModule {
}
```

**Comment by DzmitryShylovich** [comment]
> The url is not changed correctly and the history becomes corrupt.

I've seen such behaviour when people call `RouterModule.forRoot` more than 1 time.

**Comment by JohannesAtGit** [comment]
@DzmitryShylovich  Thanks I will look into it.

**Comment by JohannesAtGit** [comment]
Thank You very much. You are my hero! All my best wishes.
Works fine now.

**Comment by DzmitryShylovich** [comment]
welcome 👍

**Comment by mseemann** [comment]
@vsavkin I have found the reason for this issue. In `router_module.ts` a factory is created (`initialRouterNavigation`) that is used as a listener for `APP_BOOTSTRAP_LISTENER`. Here is the current code:

```
export function initialRouterNavigation(
    router: Router, ref: ApplicationRef, preloader: RouterPreloader, opts: ExtraOptions) {
  return () => {
    router.resetRootComponentType(ref.componentTypes[0]);
    preloader.setUpPreloading();
    if (opts.initialNavigation === false) {
      router.setUpLocationChangeListener();
    } else {
      router.initialNavigation();
    }
  };
}
```

In fact the Listener will be called with the ComponentRef that is bootstrapped. This ComponentRef must not be the same as the ComponentRef of the apps root component. I think what is missing here is a check that the bootstrapped component is the app component where the router has been initialized for. The code might be:

```
export function initialRouterNavigation(
    router: Router, ref: ApplicationRef, preloader: RouterPreloader, opts: ExtraOptions) {
  return (bootstrappedComponentRef: ComponentRef) => {
    
    if ( bootstrappedComponentRef !== ref.components[0]) {
      return;
    }
    
    router.resetRootComponentType(ref.componentTypes[0]);
    preloader.setUpPreloading();
    if (opts.initialNavigation === false) {
      router.setUpLocationChangeListener();
    } else {
      router.initialNavigation();
    }
  };
}
```

Is it worth creating a pr for this?

**Comment by DzmitryShylovich** [comment]
close?

**Comment by mseemann** [comment]
the fix is in the master but not yet released. so i would say it depends on the project rules when to close an issue: if it's fixed or if the fix is released... ?

**Comment by DzmitryShylovich** [comment]
usually they close issues after merge
