### ISSUE TITLE
CORR Issue

### ISSUE THREAD

**Issue by suresh191** [angular/angular#12285]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I access remote REST service (different domain but local only) via HTTP POST I am getting the following error:
"Response to pre-flight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource'

I am aware thsi is CORR Issue. But teh REST service that I am calling is adding required HTTP headers as Access-Control-Allow-Origin as * and ALLOW-METHODS as "GET, PUT, POST DELETE"

and also I am passing required HTTP headers thru my angular2 http headers as well via hTTP POST. But still I am getting this CORR error.

Any help is appreciated. 
**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular 2.0.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =   
Node 4.2.3

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
