### ISSUE TITLE
ViewChildren's QueryList.changes doesn't detect changes

### ISSUE THREAD

**Issue by timblakely** [angular/angular#12283]
**I'm submitting a ...**  

```
[x ] bug report 
[ ] feature request
[ ] support request
```

**Current behavior**
When subscribing to QueryList.changes created by a ViewChild, any changes to bound variables are not detected.

**Expected behavior**
1) Template to be updated
2) If this is WAI, the debug change detector should detect that a bound variable was changed and throw, similar to updating bound variables in ngAfterViewChecked.

**Minimal reproduction of the problem with instructions**
[Plunker](https://plnkr.co/edit/l67Nu2ncerHduOXbBgow)

**Comment by DzmitryShylovich** [comment]
This is how change detection works in angular. See explanation http://stackoverflow.com/a/35243106

**Comment by timblakely** [comment]
@DzmitryShylovich I'm well aware of how change detection works. In this case Angular fills out ViewChildren after the view is checked - in which case updating the template is forbidden - but a template modification doesn't result in the appropriate debug warning. In addition, the compiler might be able to batch these calls and launch the change handlers via Zone.scheduleMicroTask, though I'm not sure about the any guarantees QueryList.changes makes in terms of when or where the observable is emitted, as [it's undocumented](https://angular.io/docs/ts/latest/api/core/index/QueryList-class.html#!#changes-anchor).

**Comment by vicb** [comment]
Thanks for attaching a plunker.

Can you describe:
- what is the expected behavior of it,
- what is the actual behavior.

**Comment by timblakely** [comment]
Sure! 

**Expected:** 
Clicking the "Populate!" button adds a child component Foo, gated by an *ngIf directive. A ViewChildren-generated QueryList.changes observable is subscribed to that should add a message to the template an array when an event arrives. The message says "A '<foo>' element was added"

**Actual:**
When the button is clicked, the Foo component appears. The .changes event is fired, and the message is added to the template. However, the change detection is not run, causing a disconnect between the model and the template. The disconnect can be rectified by clicking the other button to force change detection via ChangeDetectorRef.markForCheck. No warning message about changing after it was checked is shown.

**Desired:**
Any other observable I've ever used that changes the template in the .subscribe function correctly causes change detection to occur. A QueryList generated via ContentChildren works just fine ([new plunker](https://plnkr.co/edit/wnO09Hq1kMx51n838FtW)), so I suspect this has to do with the timing of the ViewChildren's query firing after content checking as opposed to in a new microTask.

**Comment by DzmitryShylovich** [comment]
> The disconnect can be rectified by clicking the other button to force change detection via ChangeDetectorRef.markForCheck.

it's not mandatory to call `markForCheck`.

**Comment by lqbweb** [comment]
I am experiencing similar problems. Sounds pretty serious to me (and similar to #10962 ?)

Real case scenario for me:

```
<tabs-panel #tab>
     <template newTab>
         <tab title="TabTitle {{ tab.numberTabs() }}">
               content for new tabs
         </tab>
    </template>
</tabs-panel>
```
When the template gets projected at any time with `createEmbeddedView(...)`, the `@ViewChildren(Tab)` query that I have at TabsPanel does not get notified with the new tab.

**Comment by tbosch** [comment]
This is actually legit, as we can determine the content of `@ViewChildren` earlier so that you can still change content in the view.

**Comment by tbosch** [comment]
@lqbweb See #12712, although you would need a `@ContentChildren` to get the tabs...
