### ISSUE TITLE
ViewChildren QueryList population declaration-order-dependent

### ISSUE THREAD

**Issue by timblakely** [angular/angular#12284]
**I'm submitting a ...**  
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
It appears that QueryLists generated by the @ViewChildren decorator are populated based on the order they're listed in the class definition, and independent of DOM/View order and ViewChildren class. 

**Expected behavior**
I would think that all the declared ViewChildren would be populated before firing any of their change detection. I discovered this while filing angular/issues#12283, so it could be related.

**Minimal reproduction of the problem with instructions**
[Plunker](https://plnkr.co/edit/IZJnGXDM2lPnJvgUZHbx)

**Comment by tbosch** [comment]
Sorry, this is work as intended. Queries are calculated during compilation time, i.e. they will only contain elements that were present in the template during compilation.

This excludes:

- elements that are projected via `ng-content`
- components that are dynamically created via `ComponentFactory.create`
- views created via `TemplateRef.create` that are from a different place.

**Comment by timblakely** [comment]
Sorry, just to clarify: the queries are expected to be executed in the order they're _declared_? As in:

`class Foo {
  @ViewChildren(A) aChildren;
  @ViewChildren(B) bChildren;
}`

aChildren is expected to be populated before bChildren, and:

`class Foo {
  @ViewChildren(B) bChildren;
  @ViewChildren(A) aChildren;
}`

bChildren is expected to be populated before aChildren?
