### ISSUE TITLE
AoT with Upgrade Adapter?

### ISSUE THREAD

**Issue by buu700** [angular/angular#12292]
Is it possible to use AoT and the Upgrade Adapter at the same time?

I configured our build process with `ngc` to work around our breakage caused by our CSP (no `unsafe-eval`), but that doesn't seem to have made any difference; the application still just stalls indefinitely. This is a blocker for us since we'll be stuck with the Upgrade Adapter at least until Angular Material 2 supports everything we currently use from Material 1, so any kind of workaround to avoid reverting to the pure ng1 implementation would be really appreciated.

**Comment by ericmartinezr** [comment]
Still WIP, see https://github.com/angular/angular/pull/12239

**Comment by buu700** [comment]
Ah nice, perfect timing. Thanks!
