### ISSUE TITLE
@angular/router with a 2.X.X semver

### ISSUE THREAD

**Issue by paulcayon** [angular/angular#12296]
**I'm submitting a ...**
```
[ ] bug report 
[x] feature request
[ ] support request 
```
@angular/router have a version with a 3.X.X semver. It is the only one @angular package like this.

I know you makes a big breaking change when you are on the RC series that require a increment of the major version. 
But, It is not important know. Have the same semver for all the @angular package is more important.

Can you come back to a 2.X.X semver on the router package ?

Earlier you come back to a semver on 2.X.X, easier it will be accepted by the community.

* **Angular version:** 2.1.0 (router 3.1.0  ;-) )

**Comment by castamir** [comment]
First, it may seem like a good idea to keep all subpackages on the same semver, but sooner o later, some of those subpackages will changed more (and more often) than others. 

Let's say we have a Router package that is developed much more than e.g. Forms package, then you can release a lots of new versions of Router and Forms even if there are not any changes in Forms at all (just to have same version number), or you can slow down release process of Router. Or, you can drop the rule of same version number and release packages as you need to. Unfortunately, you will lost track of which packages belongs together and are compatible...

**Comment by DzmitryShylovich** [comment]
But we can be 100% sure that angular 2.2.0 plays well with router 2.2.0 and forms 2.2.0 for example

**Comment by paulcayon** [comment]
@castamir actually, all versions of angular move together except the router that have 1 major version upper. With the release of the 2.1.0 version, a module likes compiler-cli comes from 0.6.4 to 2.1.0 to be the same as the others modules. Angular 2 want to be a ** platform **, so on a platform,  commons best practices said to have all versions of platform's modules with the same semver. (e.g spring ... ). I just say that I will be very sad to have only one module that have different version number. So I think that angular team have to forget that they have made a router on 3.X.X semver and come back to the same that others modules.

**Comment by castamir** [comment]
@paulcayon downgrade is a bad idea... in ~6 months a new major version (3.x.x) will be introduced and end users will be very confused about already existing Router v3.*. So, if the ** platform ** semver is what angular team wants, then I suggest skipping major version 3 as the cleanest solution.

**Comment by vicb** [comment]
What @castamir said
