### ISSUE TITLE
The web is full of misleading content regarding Angular2 learning.

### ISSUE THREAD

**Issue by SebastienCaunes** [angular/angular#12299]
Could you please rename it as Angular 3 ? Or give it a new codename ?

Seems stupid, but I'm learning it and the web is polluted with posts, tutorials and stackoverflow questions that all relate to the various betas and are not compatible with production version 2. This without talking about the webpages regarding Angular 1 that shows up even when you seek for "Angular 2 -my issue-" help. The version number 1, 2 used as keyword is not powerfull enough to make a difference.
I already lost lot of time struggling with these outdated documentation, and notice that my friends and work mates have the same problem. Just wanted to give you this feedback. Sorry if it's not the place to do it.

First time I realize that it's a very bad Idea to give a public beta the same name as the final version.

By the way, thank you for this framework.

**Comment by DzmitryShylovich** [comment]
Angular 3 is coming in ~6 months. https://angularjs.blogspot.com.by/2016/10/versioning-and-releasing-angular.html

**Comment by pkozlowski-opensource** [comment]
@SebastienCaunes check our plans for the versioning and releasing strategy here: http://angularjs.blogspot.fr/2016/10/versioning-and-releasing-angular.html

As @DzmitryShylovich pointed out you are going to see Angular 3 in 6 months, Angular 4 in a year etc.

**Comment by SebastienCaunes** [comment]
Thank you for your answers, could it be possible to put an explicit convention on the name, for example "Angular3" without space. Or give it version codename like android (gingerbread, jellybean...).

So this way it will result in better search result and help find relevent content on the web.
