### ISSUE TITLE
 Bootstrap at least one component before injecting Router

### ISSUE THREAD

**Issue by basherr** [angular/angular#12298]
Unable to require dependencies on the constructor of a service.

Angular `@angular/core : 2.0.0`
`"angular-cli": "1.0.0-beta.16"`
`"typescript": "2.0.2"`

**Note :** If I just clear the constructor dependencies defined in the `CustomerService class` then it works like a charm.

`@Injectable()
export class CustomerService
constructor(private authService: AuthService, private siteService: SiteService) { } `

`AuthService and Site Service Class` and It's dependencies are loaded with no problem. Just some sudo facade of AuthService and SiteService Class

```
@Injectable()
export class AuthService 
constructor(private http: Http, private storageService: StorageService, 
            private siteService: SiteService, private router: Router) {}


@Injectable()
export class SiteService {
constructor(private http: Http, private storageService: StorageService) {}
And also App Module @ngModule decorator.
```

```
@NgModule({
  declarations: [
    AppComponent,
    AuthComponent,
    LoginComponent,
    HeaderComponent,
    SignupComponent,
    CompanyComponent,
    Step2Component
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AngularAppRoutingModule
  ],
  providers: [ AuthGuard, AuthService, StorageService, StepsNavigatorGuard, SiteService, CustomerService],
  bootstrap: [AppComponent]
})
```

**Comment by DzmitryShylovich** [comment]
Update router version

**Comment by basherr** [comment]
`"@angular/router": "3.0.0"`

**Comment by DzmitryShylovich** [comment]
`"@angular/router": "3.1.0"`

**Comment by basherr** [comment]
thanks for the update :)
