### ISSUE TITLE
ng-xi18n tool compiles TypeScript files

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular#12305]
**I'm submitting a ...**

```
[x] bug report
```

**Current behavior**
Having a Webpack 2 project (https://angular.io/docs/ts/latest/guide/webpack.html -> no Angular CLI) and running the `ng-xi18n` tool will compile all TypeScript files. The result is a `src` directory full with `.js`, `.js.map` and `.json` files.

**Expected behavior**
The `ng-xi18n` tool should only generate the messages file.

**What is the motivation / use case for changing the behavior?**
A `src` directory without `.js`, `.js.map` and `.json` files.

**Please tell us about your environment:**
Linux
- **Angular version:** 2.1.0
- **Browser:** All
- **Language:** TypeScript 2.0.3
- **Node (for AoT issues):** 6.7.0

**Comment by panuruj** [comment]
You can set the "outDir" field on tsconfig.json to dump the files somewhere else.

**Comment by Martin-Wegner** [comment]
Thanks for your reply. Setting the `outDir` property in the `compilerOptions` of the `tsconfig.json` works but this is a very odd workaround/hack and not an acceptable solution.

**Comment by kschio** [comment]
@Martin-Wegner Did you find a cleaner solution yet? This is not really an acceptable workaround 👎

**Comment by Martin-Wegner** [comment]
@kschio my workaround is:

```
"prei18n": "rimraf ./temp && shx mv ./tsconfig.json ./tsconfig.bak.json && shx mv ./tsconfig.i18n.json ./tsconfig.json",
"i18n": "ng-xi18n && shx mv ./messages.xlf ./src/app/locale",
"posti18n": "shx mv ./tsconfig.json ./tsconfig.i18n.json && shx mv ./tsconfig.bak.json ./tsconfig.json && rimraf ./temp"
```

**Comment by vicb** [comment]
It is no more the case since 2.1.2 / 2.2.0

`compiler: walk third party modules (#12453) (a838aba), closes #11889 #12428`

**Comment by Martin-Wegner** [comment]
@vicb this is not true! Running ` ./node_modules/.bin/ng-xi18n` with `2.2.4` still produces `.js`, `.js.map` and `.json files`. Please reopen this issue!

**Comment by Martin-Wegner** [comment]
@vicb please reopen...
