### ISSUE TITLE
Order of CSS classes applied with ngClass to be complementary

### ISSUE THREAD

**Issue by leewinder** [angular/angular#12308]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you have two CSS classes containing the same attribute (e.g. color) and apply them both to the same element with ngClass, the attribute value selected seems indeterministic.

**Expected behavior**
Applying CSS classes with the same attribute to an element with ngClass should use the duplicated elements in a known order.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/OOMWOL

In the above Plnkr, I have two CSS styles, one red (colour: red) and one green (colour: green).  Applying these styles to the same element, what colour should the text be?

When red is used first, followed by green, the text is red.  When green is first, followed by red, the test is still green.

The expectations is that one style will take priority over another based on the order it is applied using ngClass.

**What is the motivation / use case for changing the behavior?**
Applying event based styles which override previous styles within an element.

**Please tell us about your environment:**
MacOS, Chrome, Opera

* **Angular version:** 2.0.0

* **Browser:** [all]

**Comment by npx** [comment]
A quick observation: the priority seems to be deterministic by lexicographical order.
Angular applies the classes for me in the order given, but a class with lower lexicographical order takes precedence for me in Chrome.

**Comment by manklu** [comment]
>the priority seems to be deterministic by lexicographical order.

And this is CSS standard behaviour. Nothing that Angular could change.

**Comment by npx** [comment]
A quick observation:
Angular applies the classes in the given order, but the order of occurrence in your css determines the outcome, with is default behaviour. I doubt Angular can handle this easily.

**Comment by pkozlowski-opensource** [comment]
> Angular applies the classes in the given order, but the order of occurrence in your css determines the outcome, which is default behaviour. I doubt Angular can handle this easily.

Yes, CSS classes seem to be applied _exactly_ in the order supplied by a user. While it great that it works like this (at least in Chrome) IMO we can't guarantee this as AFAIK you can't guarantee order of iteration in an object.  

In any case this seem to be CSS specific and not something that could be handled by Angular. Thnx @manklu and @npx for looking into this one.
