### ISSUE TITLE
Systemjs dependency error (http request at /buffer)

### ISSUE THREAD

**Issue by guidefreitas** [angular/angular#12301]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

After upgrade for Angular 2.1.0 the application tries to do a HTTP GET request in /buffer for no reason.

GET http://localhost:3000/buffer 500 (Internal Server Error)

This resource doesn't exist in the server (its a systemjs dependency) 

Do I need to change anything in the systemjs.config.js to redirect to this resource?

This are my package.json and systemjs.config.js files:

[package.json.txt](https://github.com/angular/angular/files/529733/package.json.txt)

[systemjs.config.js.txt](https://github.com/angular/angular/files/529728/systemjs.config.js.txt)

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
