### ISSUE TITLE
Extend the ng-xi18n tool with a sourceLanguage argument and a targetLanguages argument

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular#12303]
**I'm submitting a ...**

```
[x] feature request
```

**Current behavior**
Running the `ng-xi18n` tool will create a `messages.xlf` file with `source-language="en"` attribute and no `target-language="..."` attribute (https://en.wikipedia.org/wiki/XLIFF).

**Expected behavior**
Please extend the ng-xi18n tool with a `sourceLanguage` argument and a `targetLanguages` argument.
The `sourceLanguage` argument will control the `source-language=` attribute.
For every language provided by `targetLanguages` a `messages.XX.xlf` will be created and for each created file the `target-language="..."` attribute will be set.

**What is the motivation / use case for changing the behavior?**
Create multiple `messages.XX.xlf` files with correct `source-language=` attribute and correct `target-language="..."` attribute.

**Please tell us about your environment:**
Linux
- **Angular version:** 2.1.0
- **Browser:** All
- **Language:** TypeScript 2.0.3
- **Node (for AoT issues):** 6.7.0

**Comment by panuruj** [comment]
ng-xi18n is an extraction tool, and I think it should only produce one file. Your localization system should be the one who produces a file for each language and sets the target-language.

**Comment by Martin-Wegner** [comment]
But an extraction tool should not assume that the `sourceLanguage` is English! Can you name a localization system for Angular 2, please?
