### ISSUE TITLE
View does not refresh with Redux in Internet Explorer 10/11

### ISSUE THREAD

**Issue by gnujeremie** [angular/angular#12307]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using redux/ng2-redux (https://github.com/angular-redux/ng2-redux) to save my application state. Some of the informations displayed in the application come from my redux state.
I have a weird behavior with IE 11 (and IE 10), and I don't know if it's a bug from angular, from redux, or from myself.

I use the async pipe to display the data from the state (because they are observables in my components) : 
```
export class MyComponent {
    @select('title') title$: Observable<any>;
}
```
and the html :
```
<h1>{{ title$ | async }}</h1>
```

When the title is update in my redux state, the view is not updated until I click anywhere in the page (in case you're wondering, the change detection strategy is the default one, not push).

I can force the update of the view when I run : 

```
this.ngRedux.subscribe(() => {
    this.zone.run(() => {
    });
});
```

**Expected behavior**
The view should be updated

**Please tell us about your environment:**
Virtual machines, windows 7 / 10

* **Angular version:** 2.1.0

* **Browser:** internet explorer 10/11
 
* **Language:** Typescript

**Comment by manklu** [comment]
A minimal [Plunker](http://plnkr.co/) to reproduce the problem would be helpful.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by san4ezz87** [comment]
Hellow I have the same issue and I think it's may be your mistake because async pipe doesen't work only with your selector in ie 10-11. When I work with async pipe without your selectors it's work well. Can you help me? I didn't see anything on stackOverflow about this issue.
