### ISSUE TITLE
AoT: No Provider NgZone! error for AoT-compiled scripts

### ISSUE THREAD

**Issue by jetlogs** [angular/angular#12312]
**I'm submitting a ...** 
```
[x] bug report
```

**Current behavior**
I followed the recipes for AOT and webpack from the official docs:
https://angular.io/docs/ts/latest/guide/webpack.html
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

this is the original ticket that I opened
https://github.com/angular/angular/issues/12220

then with help from the community, was able to fix the ES6 transpilation issues.
now I'm experiencing a new issue:

Angular AoT + webpack produces output files that have the error:  
`Uncaught Error: No provider for NgZone!`

I got redirected back here, and according to this thread:
https://github.com/angular/angular.io/issues/2593#issuecomment-253664209
its related to AoT compilation constraints

**Expected behavior**
AOT-compiled scripts should behave functionally the same as their non-AOT counterparts

**Minimal reproduction of the problem with instructions**
* clone repo: https://github.com/jetlogs/Angular2-AOT-Localization
* npm install
* npm postinstall
* npm run build
* open non-aot.html -> works
* open aot.html -> `Uncaught Error: No provider for NgZone!`

**Please tell us about your environment:**

```
"dependencies": {
    "@angular/common": "^2.1.0",
    "@angular/compiler": "^2.1.0",
    "@angular/compiler-cli": "^2.1.0",
    "@angular/core": "^2.1.0",
    "@angular/forms": "^2.1.0",
    "@angular/http": "^2.1.0",
    "@angular/platform-browser": "^2.1.0",
    "@angular/platform-browser-dynamic": "^2.1.0",
    "@angular/platform-server": "^2.1.0",
    "@angular/router": "^3.1.0",
    "@angular/upgrade": "^2.1.0",
```

* **Angular version:** 2.0.1

* **Browser:** all

 
* **Language:** TS 2.0.2

* **Node (for AoT issues):** `node --version` =   6.7

**Comment by frederikschubert** [comment]
You probably have mixed the angular UMD bundle with the ES5/ ES6 module format code.
Make sure that your imports are resolved to`@angular/core/index.js` and not to `@angular/core/bundles/core-umd.js`.

**Comment by jetlogs** [comment]
am I interpreting this correctly?

* JIT compiler uses @angular/core/bundles/core.umd.js based on the package definition on @angular/core/package.json
* AOT compiler expects @angular/core/index.js for ES6 modules instead

so does this mean I just have to do a search and replace of:
`from "@angular/core"`
to
`from "@angular/core/index"`

is there an alternative way for the compiler to use the EC6 src files instead of being pointed to use the umd bundles?

**Comment by manklu** [comment]
>so does this mean I just have to do a search and replace of:

No. You must configure your loader correctly.

**Comment by vicb** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
