### ISSUE TITLE
ngModel change binding on Input type="number" not working 

### ISSUE THREAD

**Issue by Robmbackus** [angular/angular#12316]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://embed.plnkr.co/CQHFQB4p71q2mtlZJ5u0/

In a Component, the following does not reflect the change in the UI.

`<input
    type="number"
    [(ngModel)]="element.value" 
    (change)="onChange($event)"
                        >`

`export class EZNumFieldComponent {
    @Input() index;
    @Input() element; //element.value = 0

    onChange($event){

        var c = confirm("Are you sure about this?")

        if(c){
            //True, accept the value
        } else {
            this.element.value = 0;
            //Failed, set the input back to 0
        }

        this._event.dispatchEvent('elementChange',{data:this.element})
    }
}

`

**Expected behavior**

When the use clicks cancel on the confirm(), the elemenet.value is changed back to 0, but the UI still shows the number I changed it to.

Now, if you change the inout type to type="text" it works fine.

AND if we keep it type="number" and change the class to force change detection like this it works

`export class NumFieldComponent {
    @Input() index;
    @Input() element;

    constructor(private cdRef:ChangeDetectorRef) {}

    onChange($event){

        var c = confirm("Are you sure about this?")

        if(c){
            //True, accept the value
        } else {
            this.element.value = 0;
            //Failed, set the input back to 0
            this.cdRef.detectChanges();
        }
    }
}
`

I believe the same issue exists for type checkbox

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Consistency across input types

**Please tell us about your environment:**

OSX, Web Storm 2016, NPM 3.10.3 and node 6.3.1

* **Angular version:** 2.0.X

I am using 2.0.0 Quick Start
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 53.0.2785.143

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
<input type="number" [(ngModel)]="element.value" (ngModelChange)="onChange($event)" >

**Comment by Robmbackus** [comment]
@DzmitryShylovich I tried that, but the event fires on keypress where change fired on blur. Going back to what seems to me like a bug is that it works fine with type="text" and doesnt with type="number". It did work when I forced ` this.cdRef.detectChanges();`

**Comment by Robmbackus** [comment]
fyi - http://stackoverflow.com/questions/40031597/angular2-ngmodel-change-binding-on-input-type-number/40035792?noredirect=1#comment67365639_40035792

**Comment by DzmitryShylovich** [comment]
Pls provide working reproduction in plunkr.

**Comment by Robmbackus** [comment]
https://embed.plnkr.co/CQHFQB4p71q2mtlZJ5u0/

Run these actions to demonstrate:

- Run as is, notice that the value in the input populates to 1 showing that initial binding is working.
- Change value to 2, confirm dialog will come up, hit cancel. The change function sets `element = 0` but the UI will not update.
- Change inout to type="text" and run the same test. It works
- Change the type back to type="number" and uncomment `//this.cdRef.detectChanges();` and change value to 2 and say cancel. It will be updated.

**Comment by kemsky** [comment]
`NumberValueAccessor` adds `change` event listener, which is invoked after your `onChange` method (they are executed within the same stack). Your `element` value is not getting detected, because change detection does not have a chance to run yet, instead `element` is overwritten by current input value in `ngModelChange` listener. That is why manual change detection works.

```
_View_App0.prototype._handle_change_1_1 = function($event) {
  var self = this;
  self.markPathToRootAsCheckOnce();
  self.debug(1,4,4);
  var pd_0 = (self.context.onChange($event) !== false);
  self.debug(1,1,3);
  var pd_1 = (self._NumberValueAccessor_1_4.onChange($event.target.value) !== false);
  return ((true && pd_0) && pd_1);
};
```
Slightly better option is to use `(blur)="onChange($event)"`

It seems, that it is not possible to intercept event if listener is added in directive, while this makes sense (by default) it would be better to have control over this. There is similar bug about event listener execution order and preventDefault.

**Comment by Robmbackus** [comment]
Thanks for the detailed explanation. I guess ill run with `blur` over change :/ .

**Comment by MattHirdler** [comment]
This still seems to be an issue. Is there a reason this was closed? blur is not a replacement, or even a workaround.

**Comment by blu3printchris** [comment]
This is still an issue. I have had to resort to using blur, but it isn't ideal.

**Comment by ChBernat** [comment]
Still an issue, even with `type` equals to `text`.

**Comment by theCrius** [comment]
Based on my test, in the `<input type="number" [(ngModel)]="value" (ngModelChange)="func($event)">` the $event passed is the old value rather than the new value.

I'm working on an angular 5.2.9 right now. Is this been fixed in the next releases?
