### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forRoot' of undefined

### ISSUE THREAD

**Issue by theunreal** [angular/angular#12314]
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
App runtime error: `Uncaught TypeError: Cannot read property 'forRoot' of undefined`

**Expected behavior**
No bug

**Minimal reproduction of the problem with instructions**
Installing angular 2 material using npm command in the documentation, 
Imported `import { MaterialModule } from '@angular/material';`

placed this expression in my module imports:

`MaterialModule.forRoot(),`

and received this error in my app runtime: 

`app.module.ts:46Uncaught TypeError: Cannot read property 'forRoot' of undefined`

refers to:

`MaterialModule.forRoot(),`

**Please tell us about your environment:**

XAMPP APACHE WINDOWS

* **Angular version:** 2.0.X
2.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Type script 2.0.2

* **Node (for AoT issues):** `node --version` =   
6.5

**Comment by DzmitryShylovich** [comment]
Wrong repo. Pls re-open in https://github.com/angular/material

**Comment by theunreal** [comment]
Sorry. Was sure I'm in the material repo.
