### ISSUE TITLE
angular2/src/core/exception_handler.js uses wrong log level for exceptions

### ISSUE THREAD

**Issue by goderbauer** [angular/angular#1231]
I just filed https://github.com/angular/angular.dart/issues/1706 for AngularDart and noticed that Angular2 has the same issue: exception_handler.js uses print to log an exception. The log entry generated by this print in the browser's console will have log level "INFO", which is not appropriate for an exception (should be "ERROR") and therefore makes it hard to detect this exception. See issue linked above for details.

**Comment by naomiblack** [comment]
marking as M7 because this affects our ability to run internal benchmarks. Rado, can you investigate?

**Comment by rkirov** [comment]
@goderbauer the exception is rethrown at the end https://github.com/angular/angular/blob/86dc3e5b07a41d9e5fe19d29b80db19aaecab006/modules/angular2/src/core/life_cycle/life_cycle.js#L19 

so there should be also a corresponding ERROR: log

**Comment by goderbauer** [comment]
OK, cool. In that case, angular2 doesn't show this issue. Can something similar be added to angular.dart because there I am definitely not getting an error and that's where I am having problems right now: https://github.com/angular/angular.dart/issues/1706

**Comment by goderbauer** [comment]
Can this be re-opened? It looks like currently ng2 is again not using the right log level for exceptions. That makes it very hard to catch exceptions after an automated test because they just look like regular exceptions.
