### ISSUE TITLE
Error running Angular 2 in cordova in iPad, Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by vincentdu101** [angular/angular#12315]
Hey guys,

I'm getting this error when I try to run Angular 2 v2.0.1 in Cordova v4.2 on the iOS 9.3 iPad. I can run the app in the Xcode simulator, but not on the iPad. Thanks!

Unhandled Promise rejection: (7)
"(SystemJS) Attempted to assign to readonly property.
__

execute
invoke@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:323:34
run@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:216:50
file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:571:61
invokeTask@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/Reading%20Asst.app/www/node_modules/zone.js/dist/zone.js:356:43
runTask@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:256:58
drainMicroTaskQueue@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:474:43
g@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/core-js/client/shim.min.js:8:10017
file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/core-js/client/shim.min.js:8:10139
k@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/core-js/client/shim.min.js:8:14294
Error loading file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/app/boot.js"
"; Zone:"
""
"; Task:"
"Promise.then"
"; Value:"
Error: (SystemJS) Attempted to assign to readonly property. __ execute invoke@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:323:34 run@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:216:50 file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:571:61 invokeTask@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:356:43 runTask@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:256:58 drainMicroTaskQueue@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/zone.js/dist/zone.js:474:43 g@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/core-js/client/shim.min.js:8:10017 file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/core-js/client/shim.min.js:8:10139 k@file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/node_modules/core-js/client/shim.min.js:8:14294 Error loading file:///var/containers/Bundle/Application/9D1D5DCD-CB77-4AAA-BCB3-8755D9B63DF6/app/www/app/boot.js
(SystemJS) Attempted to assign to readonly property.
__

execute
invoke — zone.js:323
run — zone.js:216
invokeTask — zone.js:356
runTask — zone.js:256
drainMicroTaskQueue — zone.js:474
g — shim.js:4005
k — shim.js:4373
(anonymous function) — console-via-logger.js:173
consoleError — zone.js:461
_loop_1 — zone.js:490
drainMicroTaskQueue — zone.js:494
g — shim.js:4005
(anonymous function) — shim.js:4018
k — shim.js:4373

// here is my package.json
{
"name": "client-app",
"version": "1.1.0",
"description": "Client",
"author": "Scientific Learning",
"license": "UNLICENSED",
"private": true,
"scripts": {
"tsc": "tsc",
"tsc:w": "tsc -w",
"clean": "gulp clean",
"compile": "gulp compile",
"test": "gulp test",
"junit-test": "gulp junit-test",
"start": "concurrent \"npm run tsc:w\" \"gulp connect\" ",
"postinstall": "typings install"
},
"dependencies": {
"@angular/common": "~2.1.0",
"@angular/compiler": "~2.1.0",
"@angular/core": "~2.1.0",
"@angular/forms": "~2.1.0",
"@angular/http": "~2.1.0",
"@angular/platform-browser": "~2.1.0",
"@angular/platform-browser-dynamic": "~2.1.0",
"@angular/router": "~3.1.0",
"bootstrap": "4.0.0-alpha.4",
"bootstrap-sass": "3.3.7",
"core-js": "2.4.1",
"countup.js": "1.7.1",
"jquery": "2.2.4",
"ng2-bootstrap": "1.1.9",
"ng2-translate": "2.5.0",
"odometer": "0.4.7",
"reflect-metadata": "^0.1.8",
"rxjs": "5.0.0-beta.12",
"systemjs": "0.19.39",

"shelljs": "0.7.4",
"tether": "1.3.7",
"typescript": "2.0.3",
"zone.js": "^0.6.25"
},
"devDependencies": {
"concurrently": "3.0.0",
"del": "2.2.2",
"devbridge-styleguide": "^0.4.17",
"gulp": "3.9.1",
"gulp-clean": "^0.3.2",
"gulp-autoprefixer": "3.1.1",
"gulp-connect": "5.0.0",
"gulp-log-capture": "0.0.6",
"gulp-sass": "2.3.2",
"gulp-sourcemaps": "1.6.0",
"gulp-tslint": "6.1.2",
"gulp-typescript": "3.0.1",
"gulp-war": "0.1.4",
"gulp-zip": "3.2.0",
"jasmine-core": "2.5.2",
"jasmine-jquery": "2.1.1",
"karma": "1.3.0",
"karma-chrome-launcher": "2.0.0",
"karma-cli": "1.0.1",
"karma-jasmine": "1.0.2",
"karma-junit-reporter": "1.1.0",
"rav2-data-api": "git+ssh://git@bitbucket.org/scilearn/rav2-data-api.git",
"run-sequence": "1.2.2",
"tslint": "3.15.1",
"typescript": "2.0.3",
"typings": "1.4.0"
}
}

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
