### ISSUE TITLE
DataURI pdf not always displaying in object tag

### ISSUE THREAD

**Issue by natcohen** [angular/angular#12328]
```
[ x ] bug report => search github for a similar issue or PR before submitting
[   ] feature request
[   ] support request
```

**Current behavior**
When trying to display pdf through the object tag, the pdf doesn't always display

**Expected behavior**
Always display pdf

**Minimal reproduction of the problem with instructions**
I have created a [plunker](http://plnkr.co/edit/ge2BbSV0xJlFuBcquSOZ?p=preview) but the behavior is very strange... sometimes the pdf will be displayed sometimes it won't so you need to upload many pdf files one after the other until you will see that it doesn't get displayed (I've tried with different versions of pdf). Even stranger, there is no particular error and I didn't find a way to consistently reproduce the issue (but I always get the problem at some point...). With my computer the pdf starts NOT being displayed pretty quickly (after the fifth or senventh).
To be honest I'm not sure if it's an Angular issue or a Chrome issue...

* **Angular version:** 
2.0.2, 2.1.0

* **Browser:** 
Chrome 54

**Comment by vicb** [comment]
> To be honest I'm not sure if it's an Angular issue or a Chrome issue...

Could you add a plunker not based on Angular ?
What is the behavior with other browsers ?

**Comment by natcohen** [comment]
Seems to be a Chrome issue... I've tried with [JQuery](http://plnkr.co/edit/9vqf0Q77UBo2V4htjBCb?p=preview) and got the same problem...
