### ISSUE TITLE
Angular2-http.get requestoptioins not working

### ISSUE THREAD

**Issue by FourLeafClover** [angular/angular#12329]
I will visit one api with auto2.0. Use Angular 2 http.get can not visite the api successfully, but successfully   using jquery $.ajax visit the api . What's up?
`   let url = 'xxxx';
     let authToken = 'xxxxx';
     let headers = new Headers();
     headers.append('Authorization', `Bearer ${authToken}`);
     let options = new RequestOptions();
     options.headers = headers;     
     this.http.get(url,{
         headers:headers
     }).subscribe((result:any)=>{
         console.log(result);
     })`

`$.ajax({
            type:"GET",
            beforeSend: function (request)
            {
                request.setRequestHeader("Authorization", 'Bearer xxxxxxx....');
            },
            url: "xxxxx",
            processData: false,
            success: function(msg) {
                console.log(msg);
            }
    });`

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
