### ISSUE TITLE
Router Ambiguity with Empty Path Child Routes and Multiple Outlets

### ISSUE THREAD

**Issue by colinmorelli** [angular/angular#12320]
**I'm submitting a ...** 

```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Given the following declared routes:

```
{ 
    path: 'user/:id', 
    children: [
      { path: '', component: UserDetailComponent },
      { path: '', component: UserSidebarComponent, outlet: 'sidebar' }  
    ] 
  },
  {
    path: 'user/:id',
    component: UserSidebarComponent,
    outlet: 'sidebar'
  }
```

Going to the path `/app/user/123` correctly loads the components in both of the outlets. However, navigating to `/app/user/123(sidebar:user/456)` renders two components in the sidebar outlet.

**Expected behavior**
I would expect a router-outlet to (barring animations) only ever have a single component rendered at any given time. I would also expect the outlet to render the best matching (read: most explicit match) based on the provided URL. Though I understand this may be up for interpretation, an explicitly provided outlet route should override the pathless child of the active route.

**Minimal reproduction of the problem with instructions**
See the plunker:
http://plnkr.co/edit/kus0dWmgIk7SKTGrSrKd?p=preview

**What is the motivation / use case for changing the behavior?**
I'm trying to have a sidebar which, when navigating to a page, renders default content for that page. However, inside the sidebar there are links which can be clicked that will change the content that appears in the sidebar, and override the URL to include the sidebar's specific path. Currently, there doesn't appear to be a reasonable way to do this given the current router limitation/bug.

**Please tell us about your environment:**
- **Angular version:** Angular v2.1.0 / Router v3.1.0
- **Browser:**  Appears to be all
- **Language:** All

**Comment by vsavkin** [comment]
The router does not have the notion of "the best match". It traverses the router configuration in depth first order trying to consume the whole URL.

In your case the router deals with two URL segment groups: "/app/user/123" and "sidebar:user/456". Both of these segment groups place components into the sidebar outlet, hence the error.

To achieve what you want use the following configurations:

{ 
  path: 'user/:id', 
  children: [
    { path: '', component: UserDetailComponent },
    { path: '', component: UserSidebarComponent, outlet: 'sidebar' },
    { path: ':extra', component: UserSidebarComponent, outlet: 'sidebar' }  
  ] 
}

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
