### ISSUE TITLE
Double compiling

### ISSUE THREAD

**Issue by Miqueliu** [angular/angular#12339]
I want that any element with `title` attribute behaves like an `uibTooltip` atribute (from UI Bootstrap module). So, I created a simple directive that automatically puts this atribute and removes that other one, like this:

> ```javascript
angular.module( 'ui.bootstrap.tooltip' )
  .directive( 'title', function( $compile ) {
    return {
      restrict: 'A',
      link: function( scope, elem, attrs ) {
        attrs.$set( 'uibTooltip', attrs.title );
        $compile( elem.removeAttr( 'title' ) )( scope );
      }
    };
  } );
```

It converts the attributes and then it compiles again.

The problem appears, for example, in this element (in Bootstrap design):

> ```html
<div ng-controller="ButtonController as vm">
  <button type="button" class="btn btn-default" title="Add" ng-click="vm.add()"><span class="glyphicon glyphicon-plus"></span></button>
</div>
> ```

With appropriate controller:

> ```javascript
angular.module( 'app' ) // Whatever name
  .controller( 'ButtonController', function() {
    var vm = this;
    vm.add = function() {
      console.log( 'Added!' );
    }
  } );
```

Since it recompiles, `ngClick` function executes twice on click.

Which is the way for change element's attributes before compilation?

**Comment by DzmitryShylovich** [comment]
Wrong repo. https://github.com/angular/angular.js

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich 
@Miqueliu this repository is for Angular 2.x, Angular 1.x lives in https://github.com/angular/angular.js
