### ISSUE TITLE
[dart transformers][phase 2] pass e2e tests on all example apps and benchmarks

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1233]
This is phase 2 of a 3-phase project to productionize Dart transformers. The project does not include any optimizations, only feature-completeness. Optimizations will be planned separately.

# Phase 2 Goals
During this phase we want to make sure the transformer is feature-complete enough that in addition to https://github.com/angular/angular/issues/1232 the generated code:

- passes all e2e tests in examples and benchmarks
- runs as e2e tests in Travis CI

# Non-goals

- it is not required that transformer can transform unit-test code

**Comment by mhevery** [comment]
I believe this is obsolete. Closing, reopen if you feel otherwise.
