### ISSUE TITLE
[Safari only] Invalid argument for pipe 'DatePipe' - Safari cannot parse Date offsets

### ISSUE THREAD

**Issue by dolanmiu** [angular/angular#12334]
**I'm submitting a ...**

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Error shows up, only on **Safari** `(Version 10.0 (11602.1.50.0.10))`
![screen shot 2016-10-17 at 01 10 54](https://cloud.githubusercontent.com/assets/2917613/19422116/f3d2bfce-9406-11e6-8cc9-3c3e151da77e.png)

**Expected behavior**

Expected no error to show up. **Google Chrome** works fine

**Minimal reproduction of the problem with instructions**

Go to the following Plunkr with **Safari** and **Google Chrome**. **Chrome** works perfectly.

Plunkr: https://plnkr.co/edit/8ieBbla6Pk3jFQKkHsNc?p=preview

**What is the motivation / use case for changing the behaviour?**

So it works on Safari as well as Chrome

**Please tell us about your environment:**

Max OS X El Capitan 10.11.6
- **Angular version:** 2.0.0
  
  
- **Browser:**  Chrome Latest, Safari 10.0 (11602.1.50.0.10), iOS Safari 
  
  
- **Language:** TypeScript 2.0.2

**Comment by vicb** [comment]
Please provide the repro as a plunker and make sure the issue is not already reported.

**Comment by dolanmiu** [comment]
https://plnkr.co/edit/8ieBbla6Pk3jFQKkHsNc?p=preview

Here is the plunk

Try this on **Google Chrome** and then try this on **Safari**

Mac OS X El Capitan

**Comment by dolanmiu** [comment]
I have found out the cause:

```
// Does not work
date: string = '2016-01-20T19:00:00+0000';

// Works
date: string = '2016-01-20T19:00:00';
```

**Comment by dolanmiu** [comment]
I have a strong feeling it is somewhat related to this:

http://stackoverflow.com/questions/6427204/date-parsing-in-javascript-is-different-between-safari-and-chrome

**Comment by hypery2k** [comment]
any plans to fix this?

**Comment by jburtondev** [comment]
This will work as a temporary solution. Of course, you can replace the replaced string value with what you require, e.g. hyphen instead of comma. 
`    // Used due to issue for Safari in formatting date. 
    formatDate(obj) {
        return obj.toString().replace(/,/g, "/");
    }
`

**Comment by michaell94** [comment]
It's still a bug when you have date like that: 2017-11-02 00:00:00.000

**Comment by abhishekdgeek** [comment]
Sadly this is still there for spaces. Easier if you are working with mongodb where date is stored in ISO 8601 format.

**Comment by artuska** [comment]
@michaell94 well, event if i have `2017-11-02 00:00:00` date i get an error:

```
ERROR: ERROR Error: InvalidPipeArgument: '2018-02-28 00:00:00' for pipe 't'
```

**Comment by abhishekdgeek** [comment]
Yes, use following format - 2017-11-02T00:00:00Z

NOTE Z at the end, else you will have timezone issue in Safari and Chrome. :)

**Comment by LeonardoMinatiCrispyBacon** [comment]
This issue is still here

**Comment by sebastian-heinz** [comment]
I also run into this

**Comment by ivanpadavan** [comment]
Yeah, Angular's DatePipe is not cross browser compable. Whatashame

**Comment by renatop7** [comment]
Any fix for this?

**Comment by sebastian-heinz** [comment]
I ended up using a getDate() function that I run once when I get a response from my API, which proves me with a new Date-object that is compatible.
This code makes certain assumptions, so you should modify it to your needs. (additional null check / change input parameter type)

`  protected getDate(value: any): Date {
    // https://github.com/angular/angular/issues/12334
    return value ? new Date(value.date.replace(/\s/g, 'T')) : undefined;
  }`

This is a very subtle bug that is not easy to find, hope for progress on this one.

**Comment by abhishekdgeek** [comment]
@sebastian-heinz take a note about Z present else you will mess up the timezone for safari.
