### ISSUE TITLE
Router resolve should provide a way to handle errors from Obsevables/Promises

### ISSUE THREAD

**Issue by michaelchiche** [angular/angular#12343]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The application breaks if observer.error is called.

**Expected behavior**
We should be able to handle errors from observers/promises

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/ox16J4?p=preview

**What is the motivation / use case for changing the behavior?**
The application needs to load data from an API for a component. The service used to call the API calls observer.error if the resource is not found. And breaks the entire application.
The app should be able to "survive" an API call error when using data resolver in the router

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by vsavkin** [comment]
There are multiple ways to handle errors during data resolution.



### You can catch errors in a resolver 

You can catch error in a resolver. For instance, you can navigate to an error page or show a dialog with the error message. Something like this:

```
class UserResolver implements Resolve<User> {
  constructor(private router: Router, private backend: Backend) {}

  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Promise<any> {
    return this.backend.fetchUser(route.params.id).catch(e => {
      this.router.navigateByUrl('/error');
    });
  } 
}
```



### You can catch errors when invoking a navigation

If a resolver returns a rejected promise, the corresponding navigation fails. As with any other navigation failure you can catch it as follows:  

```
router.navigateByUrl("/someurl").catch(e => {
  // custom logic
});
```

If you don't want this promise to be rejected, you can pass a custom error handler to RouterModule.forRoot. 



### Listening to NavigationError events

As with all navigation failures, you can listen to NavigationError events.

```
router.events.filter(e => e instanceof NavigationError).subscribe(e => {

});
```

So the default error handling behavior is simple--fail navigations. But the router provides multiple ways to change it.

**Comment by michaelchiche** [comment]
@vsavkin thanks for this clarification!
