### ISSUE TITLE
Component style apply but not display

### ISSUE THREAD

**Issue by scandinave** [angular/angular#12340]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I adds background style to my component by adding a css class on it. The browser inspector shows me that the class is applied. But the style don't appeared on the screen. The only way to make it work is to set display:block. For me it's a bug. Tell me if i'm wrong

**Expected behavior**
I want to have the same comportement with a component tag than with all html elements.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/IdNEJNESamVYBckCArY0

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

MacOS, Visual Studio Code, Angular-cli, 
* **Angular version:** 2.0.X
Angular 2.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Test in Safari and Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by ericmartinezr** [comment]
Here's a discussion (closed) about it https://github.com/angular/angular/issues/5960, there you can see what was their decision.

**Comment by scandinave** [comment]
Thx for the link. It is says : 

> obsolete (would be a breaking change)

Why breaking change means obsolete? i can understand that this modification can impact in lots of existing code. But this is something that should be place in queue

**Comment by vicb** [comment]
There is no special behavior, you only have to add css for you tag.

**Comment by scandinave** [comment]
Maybe update the documentation to prevent other person lose time on that would be interesting

**Comment by vicb** [comment]
feel free to open am issue/PR on angular/angular.io - but I don't see anything angular specific here ??
