### ISSUE TITLE
router: provider not found when using lazy load mode and provide in component

### ISSUE THREAD

**Issue by pesimeao** [angular/angular#12344]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm trying to provide a service configured in a component declaration (not module), and then use it in its children loaded by the router module.
When the child module/component is instantiated, it fails because the service (provided by the parent component) wasn't found.

**Expected behavior**

It should be possible to inherit all the providers by parent modules and/or components. 

**Minimal reproduction of the problem with instructions**

See this plunkr (and open console to see the error): http://plnkr.co/edit/zHqNZUbZ5faqpNVcdIGd
I'm trying to load an App, with a Parent module/component and a Service provided. Then, there's a route to Child module that is placed on Parent template.

**What is the motivation / use case for changing the behavior?**

Use of the same component with a scoped service to it's children, loaded by router module.

**Please tell us about your environment:**

Windows, NodeJS
- **Angular version:** 2.1.0
  
  
- **Browser:** Chrome 54.0.2840.59 m
  
  
- **Language:** TypeScript  2.1.0-dev.20160811
- **Node (for AoT issues):** `node --version` =   v5.9.1

**Comment by manklu** [comment]
To recite @vicb

>Your question sounds like a support request.
>
>Please use the issue tracker only for bugs and feature requests.
>
>Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

Since RC6 you must add the providers to the module.

```javascript
@Component({
  selector: 'my-parent',
  template: `
    <div>
      <span>Parent: service.value={{value}}</span>
      <ng-content></ng-content>
    </div>
  `
})
export class Parent {
  value: string;
  constructor(private service : Service) { 
    this.value = service.value;
  }
}

@NgModule({
  imports: [CommonModule],
  declarations: [Parent],
  exports: [Parent],
  providers: [Service]
})
```

**Comment by pesimeao** [comment]
@manklu this works well on eager-load mode. I need component scoped provider, not module scope. I can't find any reference that provide an injectable in component declaration is deprecated.
