### ISSUE TITLE
canDeactivate changes URL even when rejected

### ISSUE THREAD

**Issue by AmirTugi** [angular/angular#12342]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, even with the official example, when canDeactivateGuard is triggered the URL instantly changes, even if I reject whatever promise I attached to the guard.

**Expected behavior**
The URL should only change if the promise is resolved.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
It can be very confusing, and maybe even (didn't check this) could mess up with relative links.

**Please tell us about your environment:**
Using Windows 10 with NPM and lite-server (from the official quickstart guide.

* **Angular version:** 2.0.1

* **Browser:** [Chrome 53.0.2785.143 m ]

 
* **Language:** [TypeScript 2.0.3]

**Comment by ericmartinezr** [comment]
Is your issue the same as https://github.com/angular/angular/issues/10321 ?

**Comment by AmirTugi** [comment]
Yes, my bad. I thought I searched thoroughly for an existing issue.
