### ISSUE TITLE
Can't use css class "constructor"

### ISSUE THREAD

**Issue by Freak613** [angular/angular#12351]
If I have css class "constructor" defined in my template alike
```
<div class="constructor"></div>
```
I got an error
```
Unhandled Promise rejection: Cannot read property 'finalize' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'finalize' of undefined(…) TypeError: Cannot read property 'finalize' of undefined
    at SelectorMatcher._matchTerminal
    at SelectorMatcher.match
```

It's because of that line
https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/selector.ts#L300

Empty map object still IS an object, hence it has constructor and it's successfully matched via selector `map["constructor"]`

To fix this issue I need to rename css class to other name.

Tested with angular 2.0.2 and from source it seems still actual in 2.1.0

-
I'm too lazy to fill up your forms and etc, you might close my issue without investigating.
It's just a notice of unobvious side-effect that takes some time with debugging ng2 code.

**Comment by chrisnicola** [comment]
Seems like one way to tackle this would be to use an ES6 `Map` object instead and use `set` and `has`.

**Comment by chrisnicola** [comment]
Someone also suggested that `hasOwnProperty` could help here. It may be a simpler more backwards compatible solution, but I would still argue that using `Map` is the safer choice in the long term. Either way I thought I would mention it.

**Comment by laco0416** [comment]
Probably this was solved by https://github.com/angular/angular/commit/d321b0e .

**Comment by vicb** [comment]
yep it was, thanks @laco0416
