### ISSUE TITLE
Could not reset the animation state in animations callbacks

### ISSUE THREAD

**Issue by DanielYKPan** [angular/angular#12355]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I set a button to initiate a animation instance value and trigger the animation. And I created a animationDone() function to reset the instant return to initial state. I clicked the button first time, the animation was triggered. But I clicked the button second time, the animation was NOT triggered. Obviously, the animation state was not reset back to the initial state in the animationDone() function. I am not sure if the issue is related to this #11881

**Expected behavior**
In the animationDone() function, the animation state should be reset back to initial state. In this case, we will be able to run the animation several times.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/HYkFUaE6tQUIKITuVmzm?p=preview

**What is the motivation / use case for changing the behavior?**
Instant return to initial state after Angular2 Animate based animation to be able to run the animation several times

**Please tell us about your environment:**

- **Angular version:** 2.0.0
  
  
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
- **Node (for AoT issues):** `node --version` =

**Comment by jordic** [comment]
Sure its related to #11881 
I forked your plnkr: http://plnkr.co/edit/Oxq1X13Zb0c2t0sS4UVW?p=preview

Running the animation callback on the zone, and works.

PD: If you look at the output, the animation callback runs, but as it does outside the zone, the change detector doesn't see it.
