### ISSUE TITLE
ngModel control registration for template driven forms is not working with custom components

### ISSUE THREAD

**Issue by westor21** [angular/angular#12357]
**I'm submitting a ...**  (check one with "x")
[x ] bug report => search github for a similar issue or PR before submitting

**Current behavior**
When you use a custom component in a template driven form, the ngModel control registration on that form does not work.

**Expected behavior**
Custom components with ngModel are working like native inputs in template driven forms.

**Minimal reproduction of the problem with instructions**
In this plnkr you see two controls, the first one is a native input, the second is created by a component. I would expect both controls under control of the surrounding form. Only input1 is covered.
https://plnkr.co/edit/158SO2UhJV0drUMFJjXr?p=preview

* **Angular version:** 2.0.X
Angular 2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by raymonschouwenaar** [comment]
Same problem for me! How can we fix this :+1:

**Comment by kara** [comment]
@westor21 If you want a custom form control to be recognized by ngModel, you'll have to implement ControlValueAccessor. Otherwise, the form won't know how to interact with your custom control.  See [this issue](https://github.com/angular/angular/issues/9281#issuecomment-238610807) for an example.

**Comment by westor21** [comment]
@kara Thank you for your fast answer.

May be I misundeerstood the concepts, but I have some arguments against your statement, or at least questions, which are unclear to me:

- We don't talk only about a custom form control. We talk about a custom control in general, which is placed inside a form. Such a control may have nothing to do by itself with model and data, it may only perform structuring tasks or group more then one input elements for a special purpose.
Why would I need a control value accessor for the component, if the the component itself is not dealing with data? And how can a control value accessor help, if I have more then one input element in the component?

- I thought, the proposal was, to bring full ng1 functionality to forms, when using template driven forms and ngModel. Our exiting ng1 applications do not need something like a control value accessor - a migration seems not to be as easy as expected.

**Comment by raymonschouwenaar** [comment]
@kara thanks for your response! This example: http://plnkr.co/edit/YKVGSleeFQscua1JuVpf?p=preview did do the trick for me! I was already frustrated after spending 4 days to get it done ;-)

**Comment by westor21** [comment]
@kara it would be so great, if you could answer my last question.

**Comment by zoechi** [comment]
Why would you want to use `ngModel` if the control doesn't deal with data?

**Comment by westor21** [comment]
There may be some reasons for creating a custom control, whichs main purpose has nothing to do with data. Imagine, you want to group one or more controls, or you want to do something with the DOM etc. But inside of such a custom control you may place one or more input elements. Why should I need a control value accessor for that?
IMHO it should work like in ng1 - it should take all controles inside a component (directive) and register them at their corresponding form.
