### ISSUE TITLE
Lazy loading with Aux routes

### ISSUE THREAD

**Issue by intellix** [angular/angular#12360]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I've created a perfectly working example of aux routing. As soon as I transform an item on the primary outlet to be lazily loaded then it throws errors. 
If you open an aux route and navigate away from a lazy-loaded route. The aux route disappears and throws the following error:

```
core.umd.js:3263 - Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'AccountSummaryComponent'
```

**Expected behavior**

Having a lazily loaded `primary` state and opening an aux route inside `right` outlet, then navigating `primary` away should keep the `right` outlet visible without errors being thrown.

**Minimal reproduction of the problem with instructions**

1) Go to http://plnkr.co/edit/4s09t9hFqu5XMSnhmbXE?p=preview (you will land on a Lazily loaded module/component (`HomeModule + HomeComponent`).
2) Click `A-Summary` on the right **right outlet**
3) Click `Content` on the left to navigate away the lazily loaded item - **primary outlet**

**What is the motivation / use case for changing the behavior?**

I want to navigate around the site with multiple outlets loading different items and have them always visible unless I navigate away from them.

**Please tell us about your environment:**

**OS:** OSX Sierra
- **Angular version:** 2.0.X
  
  
  
  **Angular:** 2.1.0
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
  
  **Chrome:** Version 54.0.2840.59 (64-bit)
  **Firefox:** 49.0.1
  **Safari:** Version 10.0 (12602.1.50.0.10)
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  **TypeScript:** 2.0.2
- **Node (for AoT issues):** `node --version` =   

If you disable lazy-loading by commenting out/in items inside app.module.ts, you'll see that it works perfectly when there's no lazy loading at all. I'm getting a different behaviour locally where my whole application has other lazy loaded items but haven't been able to reproduce that inside the plnkr yet. 
Locally, the `right` outlet disappears and the previous navigating away item from `primary` remains with the new item being loaded in `primary`at the same time

**Comment by vsavkin** [comment]
The issue has been fixed in master.
