### ISSUE TITLE
404 Page Not Found.... on F5 .....VS 2015 & Angular2

### ISSUE THREAD

**Issue by SrinivasKothapalli** [angular/angular#12365]
When i Click F5 ... on navigation and refreshing the page, getting 404 Error.
 
**Current behavior**
 Getting 404 Error of F5 in VS2015 & Angular2

**Expected behavior**
Should Refresh the page (or) atleast navigate to the URL

**Minimal reproduction of the problem with instructions**
 
![image](https://cloud.githubusercontent.com/assets/22912906/19479347/e13c0632-9563-11e6-9344-33d391e8d9cb.png)

**What is the motivation / use case for changing the behavior?**
We should get the same page by maintaining the state.
 
* **Angular version:** 2.0.X
version :  "@angular/common": "~2.0.2",
 
* **Language:**  :  ES5/VS2015/SPA/

* **Node (for AoT issues):** `node --version` =   6.0

**Comment by DzmitryShylovich** [comment]
Can u provide a working reproduction?

**Comment by SrinivasKothapalli** [comment]
Added sample application to the repository, Please download it from the url.
**Application** : routing.rar

**Repository URL :**   [](https://github.com/SrinivasKothapalli/SrinivasKothapalli)

**Versions**: 
   - VS 2015(update 3)
   - Angular 2.0.2  (stable version latest)

**Note** : i have not included files in "node_modules" folder. please restore them using package.json configuration file.

**Comment by anishreddy202** [comment]
if you use hash strategy, your page refresh will work,
if you want to go with Path Strategy which supports html5Mode , (In demos they use lite-server which supports historyAPIFallback.. so refresh works)

In your case with IIS you should do something like  this  in your webconfig

    <rewrite>
      <rules>
        <rule name="AngularJS Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>

Info at  http://www.iis.net/downloads/microsoft/url-rewrite

**Comment by SrinivasKothapalli** [comment]
@anishreddy202 & @DzmitryShylovich
WOW its working ... thanks for the quick fix.

**Comment by SrinivasKothapalli** [comment]
@anishreddy202 
 i have small doubt here , If my application path is **https://192.168.3.11/MyApplication**  (Domain)
Page1 Path : https://192.168.3.11/MyApplication/Site/profile
Page Path : https://192.168.3.11/MyApplication/Site/Users

So in this case my Site is not working on f5. but its working in my local vs2015.
Vs2015 working path : Page Path : **https://localhost:5050/Site/profile**

difference between my local and server path is : MyApplication. so when i add  <action type="Rewrite" url="/MyApplication" />  its always redirecting to login page. So suggestion.

**Comment by zoechi** [comment]
I guess you need

```
<head>
  <base href="/MyApplication/">
 ...
</head>
```

**Comment by heliegesio** [comment]
@anishreddy202 tanks
