### ISSUE TITLE
英雄指南路由翻译bug

### ISSUE THREAD

**Issue by mannyzhuo** [angular/angular#12361]
![image](https://cloud.githubusercontent.com/assets/13795608/19474875/3642f794-9564-11e6-8327-0398edb40e00.png)

Routes==>RouteConfig

**Comment by DzmitryShylovich** [comment]
Pls re-open in the docs repo https://github.com/angular/angular.io

**Comment by alxhub** [comment]
@DzmitryShylovich has it right - please file this bug in the docs repo. Thanks!
