### ISSUE TITLE
CSS for HTML supplied by external source (i.e. Firebase) not applying

### ISSUE THREAD

**Issue by jacobtshirt** [angular/angular#12367]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```

**Current behavior**
->CSS is not compiled into styles.bundle.js
-------User Sees--------
hello world

**Expected behavior**
->CSS is compiled into styles.bundle.js
-------User Sees--------
_hello world_

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/i72xJaQlXytKIjQCldco?p=preview

1. Store HTML content in external CMS/CDN
2. Retrieve HTML

-----script------- MyComponent.component.ts

export class MyComponent {
myHTML = "`<div class='foo'>hello world</div>`"; // hypothetical html returned from cdn.example.com/html. I'm using Firebase in my use case.
}

------CSS-------- MyComponent.component.css
.foo {
 font-style: italic;
}

------HTML------- MyComponent.component.html

`<div [innerHTML]="myHTML"></div>`

-------Rendered HTML (less ng-reflect attr)-------
```
<div>
<div class='foo'>hello world</div>
</div>

```
**What is the motivation / use case for changing the behavior?**
CSS for dynamic HTML should be applied whether the HTML is compiled in a component template or retrieved from an external source.

**Please tell us about your environment:**

OS: OS X El Capitan v10.11.6, darwin x64
IDE: Atom v1.11.1
Typings v1.0.4
NPM v3.10.3

HTTP server is default dev server contained in angular-cli

* **Angular version:** 2.0.X
Ng Cli v1.0.0-beta.17

* **Browser:**
all browsers
 
* **Language:**
TSC v2.0.3
ES6
* **Node (for AoT issues):** `node --version` =   v6.6.0

In the attached screenshot, you can see my use case with an unordered list that's not receiving its CSS. This HTML content is being retrieved from a Firebase DB.
My component's css file contains the rule (reset css is applying 'ol,ul { list-style-type: none; }' on initial page load):
ul.requirements {
 list-style-type: disc;
}
![rendered html](https://cloud.githubusercontent.com/assets/12074656/19482630/4cf3f166-9517-11e6-9737-3e74f8be9708.png)

![incorrectly rendered list](https://cloud.githubusercontent.com/assets/12074656/19482494/e32fcb38-9516-11e6-9b6a-55e9feed6374.png)

Edit: added plunkr example

**Comment by manklu** [comment]
Please provide a small reproduction of the problem. e.g. a [Plunker](http://plnkr.co/)

**Comment by jacobtshirt** [comment]
@manklu a plunkr example has been provided.

**Comment by manklu** [comment]
Sorry, overlooked.

**Comment by alxhub** [comment]
What you are seeing is Angular's view encapsulation (emulated shadow DOM). The component's CSS is scoped so it only matches those elements which are included in the component's template. Elements added via `innerHTML` are outside the scope of Angular, and thus don't match the shimmed selectors generated from the component CSS.

If you want component CSS to apply, either turn off view encapsulation for the component, or use `/deep/` to disable shimming. For example:

```
:host /deep/ .foo {...}
```

**Comment by jacobtshirt** [comment]
I do believe you're avoiding the problem. A template defines a structure that content should fit inside, regardless of what that content is.

If the behavior you're referring too is "working as expected":

-  you're putting a hinderance on every single enterprise who uses some type of CMS or CDN to pull in dynamic content.

- In AngularJS 1.x, `ngBindHtml` provides the behavior being expected.
If what you're saying is correct, `ngBindHtml` is not working properly.

- If `innerHTML` causes component scope issues, it sounds like `innerHTML` may not be working as expected or rather another solution should be implemented.


As far as Augury is concerned, the interpolated HTML is NOT out of scope of the component.

Using :host is bad practice and if it is used, it's because some sort of 'hack' is required for a styling fix.
/deep/ is also a hack.
Disabling view encapsulation defeats the purpose of Angular 2 components and their styles being plug and play.

**Comment by jacobtshirt** [comment]
With your logic, @alxhub CSS should never be applied to the shadow DOM unless `:host` or `/deep/`. So wouldn't that mean CSS should never be applied to HTML in the shadow DOM?
Last I checked, both Angular 1 and 2 rely heavily on the shadow DOM for templates and rendering.
Yet EVERY angular app somehow doesn't look like [this](http://loripsum.net/api/plaintext) plain text web page.
