### ISSUE TITLE
feat(CurrencyPipe): injectable default formatting code

### ISSUE THREAD

**Issue by laskoviymishka** [angular/angular#12364]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no default formatting code

**Expected behavior**
There is default formatting code that could be overrided with DI.

**What is the motivation / use case for changing the behavior?**
As a developer from some not USA country (which have good enough economy system to not use USD as common currency) i wanna to setup my local currency code.

**Please tell us about your environment:**
All
- **Angular version:** 2.0.X
  All
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
- **Node (for AoT issues):** `node --version` =   

Related #12332

**Comment by vicb** [comment]
Closing as this can easily be done by extending the pipe class.
