### ISSUE TITLE
How can I pass custom data to EventEmitter functions?

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1237]
When building a component that emits events, we use the `@EventEmitter` annotation to add this functionality. E.g. having a `<zippy>` component that fires `open` and `close` could be used like this:

```html
<zippy (close)="doSomethingOnClose()" (open)="doSomethingOnOpen()"></zippy>
```

Inside the component's constructor, we'd use `@EventEmitter` annotations like this:

```js
class Zippy {
  constructor(@EventEmitter('open') openHandler:Function, @EventEmitter('close') closeHandler:Function) {
    this.openHandler = openHandler;
    this.closeHandler = closeHandler;
  }

  functionThatCallsEventEmitters() {
    this.closeHandler();
  }
}
```

Now, my question is, how can I pass data to that EventEmitter call, so that the outside world can use it?
I want to do something like this:

```html
<tabs (select)="doSomethingWithSelectedTab()">
  <tab></tab>
  <tab></tab>
</tabs>
```

Inside `Tabs` component:

```js
class Tab {
  constructor(@EventEmitter('select') selectHandler: Function) {
    this.selectHandler = selectHandler;
  }

  selectTab(tab) {
    // .. logic to select tab

    this.selectHandler(tab); // calls select handler with tab that has been selected
  }
}
```

And in my application:

```javascript
class App {
  doSomethingWithSelectedTab(tab) {
    // now I have access to event data (in this case `tab`)
  }
}
```

**Comment by pkozlowski-opensource** [comment]
@PascalPrecht you can pass whatever payload you want to a function injected by `@EventEmmiter` and then have those exposed under `$event` in your even handler, see: http://plnkr.co/edit/mR1S1A52ew7RUFt5HvVl?p=preview

**Comment by pkozlowski-opensource** [comment]
@PascalPrecht I guess it is better to move those types of questions to gitter so other people can see / help out. WDYT?

**Comment by PascalPrecht** [comment]
@pkozlowski-opensource thanks for answering this! Sure, I can post those questions there. Just thought that it might be useful to flag issues with clear questions as FAQ which can be used later.
