### ISSUE TITLE
Router: Guards fired out of order for reused-but-changed nodes 

### ISSUE THREAD

**Issue by tdsmithATabc** [angular/angular#12377]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When navigating between routes that reuse nodes (i.e. different URLs triggering the same route config branches), the guards are fired out of order. Specifically, the guards for the reused node are called before _any_ other guards are checked.

**Expected behavior**
The guard order should universally be deactivations from leaf to root and then activations from root to leaf.

**Minimal reproduction of the problem with instructions**
See http://plnkr.co/edit/TQjNmR?p=preview

When changing both nodes in a navigation (i.e. from /A/A to /B/B), the guards are called in the order:
- DEACTIVATE: branch
- ACTIVATE: branch
- DEACTIVATE: leaf
- ACTIVATE: leaf

The order should be:
- DEACTIVATE: leaf
- DEACTIVATE: branch
- ACTIVATE: branch
- ACTIVATE: leaf

**What is the motivation / use case for changing the behavior?**
Maintaining a consistent ordering of guards. Deactivating a service tied to a parent route before the service tied to the child could break programmers expectations about flow.

**Please tell us about your environment:**
Mac OSX, Atom, npm, webpack, served via webpack-dev-server (dev) & nginx (prod).
- **Angular version:** 2.0.X, 2.1.X (plunker demonstrates 2.1.0)
- **Browser:** Only tested in Chrome 53, but should be relevant to all
- **Language:** TypeScript 2.0.3, but should be relevant to all

**Comment by tdsmithATabc** [comment]
The underlying issue seems to be the placement of [this line (router#L730)](https://github.com/angular/angular/blob/2.1.0/modules/%40angular/router/src/router.ts#L730), which pushes the guards onto the check stack *before* traversing that node's children.

I can submit a PR sometime this evening (CST).

**Comment by tdsmithATabc** [comment]
Is there any guide to what the repo's test tools are supposed to do? I get 2 browser windows that say **Karma v0.13.20 - connected** but the command line is just halted at `Errors found.... (response not triggered)`. If I try to click the debug button, I just get a blank page -- the inspector indicates it can't find `http://localhost:9876/base/dist/all/@angular/core/testing/index.js `.

The terminal also shows a bunch of TS warnings (that I also saw during build), but they seem to just be a complaint about duplicate identifiers between `@types/selenium-webdriver` and `@types/protractor/node-modules/@types/selenium-webdriver`.

Note that all this is from the current master _before_ I make any changes.

**Comment by vsavkin** [comment]
@tdsmithATabc try to do the following:

``` 
cd ~/dir_with_angular
npm i
./build.sh
cd modules/@angular/router
./scripts/build.sh

// open a new terminal

./scripts/karma.sh
```

**Comment by jasonaden** [comment]
@tdhsmith Is this still an issue or can we close this? If it's still an issue, it would be great to get the PR rebased and merged.

**Comment by atscott** [comment]
This appears to work as expected in Angular v9: https://stackblitz.com/edit/angular-lbhffu?file=src%2Fapp%2Fapp.module.ts
