### ISSUE TITLE
Testability remains unstable when using requestAnimationFrame - ngZone will always have pending macro tasks

### ISSUE THREAD

**Issue by jcapozzi** [angular/angular#12372]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The testability service will remain unstable when using requestAnimationFrame.  The zone will always have pending macro tasks which leaves testability in an unstable state.

**Expected behavior**

The testability service should return stable when using RAF.

**Minimal reproduction of the problem with instructions**

clone:https://github.com/jcapozzi/protractor.git 
branch:testability-angular2 - contains an example using three.js.

Run npm install, run the ng2 test application and run the angular2Conf.js protractor configuration.  All tests will timeout from ng2 testability returning unstable.

**What is the motivation / use case for changing the behavior?**

Angular1 testability returns stable when using RAF.  Running e2e protractor test while upgrading applications to angular2 is crucial.

**Please tell us about your environment:**

Windows 7, Atom, npm, node express
- **Angular version:** 2.0.X
  
  
  
  2.1.0
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
  
  all

**Comment by e-cloud** [comment]
Is there no plan to fix/clarify this? And there is no bug label tagged. @jcapozzi do you still have the problem?

**Comment by jcapozzi** [comment]
@e-could yes this appears to still be an issue.  I updated my fork of protractor, updated to newest release  versions of angular2 and zone.js.  Then reran the angular2Conf tests which the test app has been modified to include a threejs scene and I'm still seeing all the tests timeout.

**Comment by DzmitryShylovich** [comment]
@jcapozzi is this still broken with the latest zone.js and ng4?

**Comment by jcapozzi** [comment]
@DzmitryShylovich I just updated my fork of protractor to use ng 4.0.2 and zone.js 0.8.5 and the tests are still timing out with the threejs scene while the original version runs fine.

**Comment by RemiTorracinta** [comment]
I am also seeing this problem

**Comment by sharikovvladislav** [comment]
Any info on this? 

What is workaround for this? Any ideas except `setTimeout(fn, 1000)` ? :)

**Comment by JiaLiPassion** [comment]
I would like to check this one, I will try to reproduce with the repo.

**Comment by spacegospod** [comment]
Is anyone planning to work on this problem?
We're reproducing it in our app using selenium and angular 5.2

**Comment by JiaLiPassion** [comment]
@spacegospod , @sharikovvladislav , could you provide a reproduce repo ?

**Comment by spacegospod** [comment]
Sure

https://stackblitz.com/edit/clarity-light-theme-v11-2nnlcv?file=app/entry-point.component.ts

Run this in Chrome, open dev tools and start the performance monitor. Stop it after a few seconds and observe the stacktraces on each animation frame

**Comment by JiaLiPassion** [comment]
@spacegospod , thanks, could you explain a little more about which part is wrong? or maybe a screenshot?

**Comment by jcapozzi** [comment]
@JiaLiPassion I think he's referring to the animation frame callback stack which includes scheduling a macro task on each frame.  This is causing protractor to always timeout since it waits for testability to return stable.

![raf-stack](https://user-images.githubusercontent.com/15760696/41552503-8aea1ee8-72f4-11e8-8d3e-f200d3d93d5d.PNG)

An example displaying NgZone properties that shows pending macro tasks:
[stackblitz project](https://stackblitz.com/edit/angular-playground-asmmis)
[stackblitz app](https://angular-playground-asmmis.stackblitz.io)

**Comment by cod-e-ash** [comment]
Was this fixed? I am still having this problem

**Comment by MartinKei** [comment]
Yep, that's still not fixed.

**Comment by JiaLiPassion** [comment]
@jcapozzi, I updated your sample with the following code, it should work

```
 ngOnInit() {
    this.ngZone.runOutsideAngular(() => {
      requestAnimationFrame(this.onFrame);
      setTimeout(() => this.cd.detectChanges(), 500);
    });
  }

  onFrame = () => {
    requestAnimationFrame(this.onFrame);
  };
```

And @cod-e-ash and @MartinKei , could you provide a reproduce repo to me, thanks.

**Comment by petebacondarwin** [comment]
Closed due to lack of reproduction.
