### ISSUE TITLE
forms: async validators and change detection on component using OnPush

### ISSUE THREAD

**Issue by fxck** [angular/angular#12378]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have an async validator http://plnkr.co/edit/9RlRRJjZBXefqP0bUahz?p=preview which does http request and return observable which completes(using `take`), it correctly changes `pending` to `true`, but it doesn't show the actual error when the observable completes and stays stuck on `pending`.. that is until you blur the input

It does however work when I remove `OnPush` from the component http://plnkr.co/edit/VIYu1qn0p1lJ1PnY21m0?p=preview

also apart from the problem above, there's a need for `setTimeout` before `next`ing on the validation observable, which is confusing http://plnkr.co/edit/84ak1dIh4i0uyuqLIHpW?p=preview (line 20)

**Expected behavior**
CD working properly
- **Angular version:** 2.1.0
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  All
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  TS

**Comment by Toxicable** [comment]
Related
#10816

**Comment by cbejensen** [comment]
Something similar to this works for me:

**Comment by cbejensen** [comment]
[This](https://github.com/angular/angular/issues/10816#issuecomment-268012143) works for me.

Although the way I did it was:
```typescript
this.form.statusChanges.subscribe(status => {
  if (status === 'PENDING') {
    this.pendingValidation = true;
  } else if (this.pendingValidation) {
    this.pendingValidation = false;
    this.cd.markForCheck();
  }
});
```

**Comment by keatkeat87** [comment]
first time use async validator then face this issue.
very surprised, it’s another 2016 issue.
as a workaround, i prefer just write the markForCheck inside async validator function.

**Comment by bhanna1693** [comment]
this worked for me in my asyncValidator (although I do think this should be handled by angular...)
```
.pipe(
   finalize(() => this.changeDetectorRef.markForCheck())
)
```

**Comment by mackelito** [comment]
@bhanna1693 thx.. you solution now found it's way into my codebase ;)

**Comment by zangguodong** [comment]
this problem may cause from angular form's FormGroup.addControl(),it will trigger updateValueAndValidity with emitEvent:false, which may override the raw updateValueAndValidity with {emitEvent: !!asyncValidator} triggered by FormControl constructor (consider with asyncValidator). New one will cancel first subscription(with {emitEvent: asyncValidator}) and create new subscription  with {emitEvent: false}.So the last statusChange will not emit.

**Comment by AndrewKushnir** [comment]
Closing this ticket in favor of #10816.
