### ISSUE TITLE
AOT Compilation fails with requirejs in webpack module bundler

### ISSUE THREAD

**Issue by yasemincidem** [angular/angular#12376]
I added to aot compilation  webpack project.We are using require js as template and stylesheet files added to bundle file in this webpack project .After that add to aot compilation ,there is an error require.js used in places.
 `Error encountered resolving symbol values statically. Calling function 'require', function calls are not supported. `
We want to both reqirejs and aot compilation . How can we use both of which reqirejs and aot compilation in same time ?

**Comment by alxhub** [comment]
Use `styleUrls` and `templateUrl` instead of `require` to feed CSS and templates into the AOT compiler. After AOT runs, you will not need to load HTML or CSS files in the browser, and thus don't need requirejs for this purpose.
