### ISSUE TITLE
ng-select/ng-options not selecting ng-model if data type number

### ISSUE THREAD

**Issue by GitzJoey** [angular/angular#12385]
Bug report

**Current behavior**
I have a ng-options(with track by) with data type number, and i have a ng-model with data type number. 
every time the select/dropdown initialized, the dropdown created not set to the default value of ng-model. Understand this might because the key in option is already converted to string.

some workaround is by removing the track by but it leaves the option value with data type

**Expected behavior**
Since both id having the same data type (number), angular should be able to pick up the ng-model
as default value

**Minimal reproduction of the problem with instructions**
`  <select ng-model="model1.id"
  ng-options="d.id as d.name for d in bankDDL track by d.id">
</select>`

`$rootScope.model1 = { id: 2 };
    
    $rootScope.bankDDL = JSON.parse('[{"name":"1","short_name":"1","id":1},{"name":"2","short_name":"2","id":2},{"name":"3","short_name":"3","id":3}]');
    `

**What is the motivation / use case for changing the behavior?**
i have a legacy system that really hard to change the data type to string, since this behavior changes
in angular, all the drop down unable to select the default value and if i change without track by
i need to change the core system to filter/remove the data type.

**Please tell us about your environment:**
Linux centOS 6

* **Angular version:** 2.0.X
Angular 1.5.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web 
all

**Comment by DzmitryShylovich** [comment]
Wrong repo. Pls re-open in https://github.com/angular/angular.js
