### ISSUE TITLE
Feature Request: Make Angular safe to use in Firefox Addon

### ISSUE THREAD

**Issue by SebastianMetzger** [angular/angular#12388]
We are developing a quite large Browser Extension/Addon for Chrome, Firefox and Outlook based on AngularJS.

For our last release we got this feedback from the Firefox Addon Reviewers:

> As stated in previous reviews, Angular 1.x is no longer approved. I will not reject this version as it will disable your entire listing. Please retract this submission on your own, this will avoid disabling the entire listing, and your old version will work.
> 
> Please use another library (like ReactJS) for your next submission.

Does anybody have information on this? I was not able to get more infofmation about what exactally the problem is.
https://docs.angularjs.org/api/ng/directive/ngCsp seems not to be enough.

We love Angular and moving to another framework would not make sense as we already put in 2 - 3 years developer man years into our application

**Comment by SebastianMetzger** [comment]
-> Angular 1 issue, sry

**Comment by mhevery** [comment]
This is purely speculation, but I think `CSP` or `eval` may be the issue. If that is the case writing it in Angular 2 with Ahead of Time compilation  should solve that.

**Comment by SebastianMetzger** [comment]
It goes into that direction.
Their concerns are based on the following slidedeck:
http://www.slideshare.net/x00mario/an-abusive-relationship-with-angularjs

Pete engaged Mozilla about this, so lets see what happens.

We already looked at Angular 2 and like it a lot :) But we obviously have to support and update our current application in the near future
