### ISSUE TITLE
(docs) doc pages should link to tests/spec files

### ISSUE THREAD

**Issue by esinek** [angular/angular#12384]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, the docs link to the code via "exported from ..., Defined in ..."
e.g. `exported from @angular/common/index, defined in @angular/common/src/directives/ng_switch.ts`

**Expected behavior**

It would be really useful to include a link to the test/spec file as well since that is often the best way to see how the code should work.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

better docs!

**Please tell us about your environment:**

VS Code, Win7, Angular CLI, NgMat2

* **Angular version:** 2.0.X

Latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls re-open in the docs repo https://github.com/angular/angular.io

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich
