### ISSUE TITLE
autocomplete doesn't trigger updates using safari

### ISSUE THREAD

**Issue by strictd** [angular/angular#12395]
**I'm submitting a ...**  (check one with "x")

```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
autocomplete on a form field using safari

**Expected behavior**
to update the ngModel variables when autocomplete fires

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/ussKHaO0nn4rICOMzw0e?p=preview

**What is the motivation / use case for changing the behavior?**
this works in chrome and firefox

**Please tell us about your environment:**
macos el captian
- **Angular version:**
  2.0.1
- **Browser:**
  Safari 9.1.3

**Comment by strictd** [comment]
https://files.gitter.im/angular/angular/61gk/safari_issue.mov screen capture video of what i'm experiencing.

**Comment by rcoryjohnson** [comment]
The same issue exists in Chrome on iOS if you choose one of the autocomplete options that show up at the top of the keyboard.

**Comment by DzmitryShylovich** [comment]
Related discussions:
React - https://github.com/facebook/react/issues/1159
Stackoverflow - http://stackoverflow.com/questions/11708092/detecting-browser-autofill/11710295#11710295
Angular1 - https://github.com/angular/angular.js/issues/1460

**Comment by tbnovaes** [comment]
any updates on this one? It is very frustrating when login with autofill fails on mobile. Also it mislead users to believe their credentials are wrong, and therefore it makes then reset their password without any need.

**Comment by AndrewKushnir** [comment]
Hi @strictd, thanks for creating a ticket and providing a repro. I've re-created a repro using Stackblitz ([see test page here](https://stackblitz.com/edit/angular-ivy-vgeksa)) and it seems to be working correctly in Chrome and Safari on my local machine. Could you please test it again and let us know if the problem still exists? Thank you.

**Comment by petebacondarwin** [comment]
Closing as it appears to now be working according to https://github.com/angular/angular/issues/12395#issuecomment-636204132
