### ISSUE TITLE
Exception is thrown for 204 HTTP response

### ISSUE THREAD

**Issue by MaciejGit** [angular/angular#12393]
**Current behavior**
Exception is thrown for 204 HTTP response in case request contains responseType: ResponseContentType.Json

Error: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').

The exception is thrown from XHRConnection, see: 
var body = isPresent(_xhr.response) ? _xhr.response : _xhr.responseText; in xhr_backend.ts

In this case, _xhr.response is null, and _xhr.responseText does not even exist for 204.

**Expected behavior**
Response should not be attempted to be parsed in case of 204 despite invalid ResponseContentType.
- **Angular version:** 2.0.0
- **Language:** [TypeScript 2.0.2]

**Comment by sebastianhaas** [comment]
I can confirm this, it is currently _not_ possible to access resources returning with `204` using the `Http` class.

The exception arises at https://github.com/angular/angular/blob/2b5c983c13c892d59f8e1bf223c291cbc3a40d8a/modules/%40angular/http/src/backends/xhr_backend.ts#L58

Here, `responseText` is accessed in case `response` is undefined, which I believe is done to achieve IE8/9 compatibility, but it breaks the entire process. `204` is not supposed to have any response body so it should be just ignored.
