### ISSUE TITLE
Flow type information across *ngFor-like directives

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#12398]
This issues supersedes and replaces the proposals in #10510 and #4850.
# The problem

Assume the following code example:

``` ts
@Component({
  template: `
  <ul>
    <li *ngFor="let person of people; let i = index">{{i + 0}}: {{person.last}}, {{person.first}}<li>
  <ul>
`
})
class MyExample {
  people: Person[] = [];
}

class Person {
  first: string;
  last: string;
}
```

In Angular 2.1, the generated code for `person.first` is not type checked because the type of `person` is generated as `any`.  The type of `person` should be `Person`. This would also allow the Angular language service to supply `first` and `last` as completions for the expression `person.` in the interpolations.
# Solution
1. Change type of `NgFor` and `NgForRow` to take a type parameter `T`.
2. Change type of `ngForOf` to be `T[] | Iterable<T>`. 
3. Change `$implicit` in `NgForRow` to be of type `T`.
4. Modify the code generation to flow the type from the input bindings to the type parameters.

The modified `NgFor` and `NgForRow` would look like:

``` ts
export class NgForRow<T> {
  constructor(public $implicit: T, public index: number, public count: number) {}
  ...
}

@Directive({selector: '[ngFor][ngForOf]'})
export class NgFor<T> implements DoCheck, OnChanges {
  @Input() ngForOf: T[] ;
  @Input() ngForTrackBy: TrackByFn;

  private _differ: IterableDiffer = null;

  constructor(
      private _viewContainer: ViewContainerRef, private _template: TemplateRef<NgForRow<T>>,
      private _differs: IterableDiffers, private _cdr: ChangeDetectorRef) {}

  @Input()
  set ngForTemplate(value: TemplateRef<NgForRow<T>>) {
    if (value) {
      this._template = value;
    }
  }

 ...
}
```

Here is now a similar example from the above could be generated that flows the types from the input properties to the type parameters:

``` ts
// User Provided types
class Person {
    first: string;
    last:string;
}

class MyComp {
    items: string[];
    people: Person[];
}


// Types representing relavant parts of the corresponding types in Angular
class AppView<T> {
    context: T;
}

interface TemplateRef<T> { create(context: T): ViewRef<T>; contextType: T }
interface ViewRef<T> { context: T }


class NgForRow<T> {
    $implicit: T;
    index: number;
}

class NgFor<T>{
    of: T[];
    constructor(template: TemplateRef<NgForRow<T>>) { }
}

/**
 * Assume we have template such as this:
 * <div *ngFor="let person of people; let index = index">
 *   {{index}}: {{person.first}}
 * </div>
 */

// We can auto generate the following function which captures the
// type relation between `of` property and `template`.

function NgFor_Template<T>(of: T[]): TemplateRef<NgForRow<T>> { return undefined as any; }
function NgFor_T<T>(of: T[]): T { return undefined as any; }

// These global variables are here only to flow the type information.
var _comp: MyComp;

// The template row can be constructed as:
var template = NgFor_Template(_comp && _comp.people);
var row: typeof template.contextType;

class RowView extends AppView<typeof row> {
}
var rowView = new RowView();

// Note the type of person is People
var person = rowView.context.$implicit;

// The correct NgFor can be constructed as:
var p1 = NgFor_T(_comp && _comp.people);
var ngFor = new NgFor<typeof p1>(template);
```

Try it in the [TypeScript playground](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20User%20Provided%20types%0D%0Aclass%20Person%20%7B%0D%0A%09first%3A%20string%3B%0D%0A%09last%3Astring%3B%0D%0A%7D%0D%0A%0D%0Aclass%20MyComp%20%7B%0D%0A%09items%3A%20string%5B%5D%3B%0D%0A%09people%3A%20Person%5B%5D%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F%2F%20Types%20representing%20relavant%20parts%20of%20the%20corresponding%20types%20in%20Angular%0D%0Aclass%20AppView%3CT%3E%20%7B%0D%0A%09context%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20TemplateRef%3CT%3E%20%7B%20create%28context%3A%20T%29%3A%20ViewRef%3CT%3E%3B%20contextType%3A%20T%20%7D%0D%0Ainterface%20ViewRef%3CT%3E%20%7B%20context%3A%20T%20%7D%0D%0A%0D%0A%0D%0Aclass%20NgForRow%3CT%3E%20%7B%0D%0A%09%24implicit%3A%20T%3B%0D%0A%09index%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20NgFor%3CT%3E%7B%0D%0A%09of%3A%20T%5B%5D%3B%0D%0A%09constructor%28template%3A%20TemplateRef%3CNgForRow%3CT%3E%3E%29%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Assume%20we%20have%20template%20such%20as%20this%3A%0D%0A%20*%20%3Cdiv%20*ngFor%3D%22let%20person%20of%20people%3B%20let%20index%20%3D%20index%22%3E%0D%0A%20*%20%20%20%7B%7Bindex%7D%7D%3A%20%7B%7Bperson.first%7D%7D%0D%0A%20*%20%3C%2Fdiv%3E%0D%0A%20*%2F%0D%0A%0D%0A%2F%2F%20We%20can%20auto%20generate%20the%20following%20funciton%20which%20captures%20the%0D%0A%2F%2F%20type%20relation%20between%20%60of%60%20property%20and%20%60template%60.%0D%0A%0D%0Afunction%20NgFor_Template%3CT%3E%28of%3A%20T%5B%5D%29%3A%20TemplateRef%3CNgForRow%3CT%3E%3E%20%7B%20return%20undefined%20as%20any%3B%20%7D%0D%0Afunction%20NgFor_T%3CT%3E%28of%3A%20T%5B%5D%29%3A%20T%20%7B%20return%20undefined%20as%20any%3B%20%7D%0D%0A%0D%0A%2F%2F%20These%20global%20variables%20are%20here%20only%20to%20flow%20the%20type%20information.%0D%0Avar%20_comp%3A%20MyComp%3B%0D%0A%0D%0A%2F%2F%20The%20template%20row%20can%20be%20constructed%20as%3A%0D%0Avar%20template%20%3D%20NgFor_Template%28_comp%20%26%26%20_comp.people%29%3B%0D%0Avar%20row%3A%20typeof%20template.contextType%3B%0D%0A%0D%0Aclass%20RowView%20extends%20AppView%3Ctypeof%20row%3E%20%7B%0D%0A%7D%0D%0Avar%20rowView%20%3D%20new%20RowView%28%29%3B%0D%0A%0D%0A%2F%2F%20Note%20the%20type%20of%20person%20is%20People%0D%0Avar%20person%20%3D%20rowView.context.%24implicit%3B%0D%0A%0D%0A%2F%2F%20The%20correct%20NgFor%20can%20be%20constructed%20as%3A%0D%0Avar%20p1%20%3D%20NgFor_T%28_comp%20%26%26%20_comp.people%29%3B%0D%0Avar%20ngFor%20%3D%20new%20NgFor%3Ctypeof%20p1%3E%28template%29%3B%0D%0A).

**Comment by DzmitryShylovich** [comment]
Related to https://github.com/angular/angular/issues/11126

**Comment by DzmitryShylovich** [comment]
@chuckjaz has been already fixed so I think it can be close.

**Comment by chuckjaz** [comment]
Not yet. This is used to track the overall feature. I have added the type parameters in 4.0.0 but have yet to add the checking. Now that we have the type parameters, flowing the types is not a breaking change (as long as it is a compiler option) so it is now slated for 4.1 or 4.2.

**Comment by sgwatgit** [comment]
I'm wondering what is the current status of this feature?

I'm using the following versions
```
Angular CLI: 1.5.0-rc.3                                     
Node: 8.6.0                                                 
OS: win32 x64                                               
Angular: 5.0.0-rc.5                                         
... animations, common, compiler, compiler-cli, core, forms 
... http, language-service, platform-browser                
... platform-browser-dynamic, router                        
                                                            
@angular/cdk: 2.0.0-beta.12                                 
@angular/cli: 1.5.0-rc.3                                    
@angular/material: 2.0.0-beta.12                            
@angular-devkit/build-optimizer: 0.0.31                     
@angular-devkit/core: 0.0.20                                
@angular-devkit/schematics: 0.0.34                          
@ngtools/json-schema: 1.1.0                                 
@ngtools/webpack: 1.8.0-rc.3                                
@schematics/angular: 0.0.48                                 
typescript: 2.5.3                                           
webpack: 3.8.1                                              
```

In my template I'm using `async` and a template variable but I lose typing support with the template variable.
```
<div *ngIf="(notes | async)?.length > 0; let unwrappedNotes; else emptyList">
  <mat-list-item *ngFor="let note of unwrappedNotes">
    <div class="date">
      <div class="month-day">{{note.dateCreated | date: 'MM/dd'}}</div>
    </div>
    <div class="content">
      <h4 mat-line>{{note.title}}</h4>
      <p mat-line>{{note.content}}</p>
    </div>
  </mat-list-item>
</div>
<ng-template #emptyList>
  <mat-list-item>
    <div *ngIf="!isLoading" class="content">No notes were found</div>
  </mat-list-item>
</ng-template>
```

Here `unwrappedNotes` has type any and therefore `note` has type any. If I rename `unwrappedNotes` to `notes`, the compiler is ok but I then lose typing support on `(notes | async)`.

It would be great to leverage all this great template syntax but if the typing support isn't there I'm more likely to not use the `async` pipe and instead manage my subscriptions within my component.

**Comment by mmatthews06** [comment]
Has there been any movement on this? I understand the benefits of TypeScript, are they really being tossed out the window in half the framework's code? Is there a sort of workaround for this?

**Comment by simeyla** [comment]
@mmatthews06 Looks like [this is a similar issue ](https://github.com/angular/angular/issues/31556)- which I about understand 50%!

PS. I'm trying to do this with `[ngTemplateOutletContext]` where I seem to [need a function to coerce the type] :-((https://stackoverflow.com/questions/55458421/ng-template-typed-variable/57438839#57438839).

**Comment by pauldraper** [comment]
@mmatthews06 workaround is to either migrate to React or other JSX-based system (which has had excellent TS support for years), or to migrate to Angular Ivy, which looks at the types of special static properties.

**Comment by amitport** [comment]
@pauldraper Angular Ivy still suffers from the same issue

**Comment by shackijj** [comment]
I tested Angular Ivy yesterday. The problem is solved for ngFor and ngForOf.

package.json
```
{
  ...
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "rxjs": "~6.4.0",
    "semantic-ui-css": "^2.4.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.23",
    "@angular/cli": "~8.3.23",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}
```

**Comment by JoostK** [comment]
Support for strict checking of `ngFor` is fully working using Ivy, if `strictTemplates` (with at least `strictInputTypes`) is enabled.
