### ISSUE TITLE
documentation: describe relation of inject() and async() functions in testing

### ISSUE THREAD

**Issue by JohannesRudolph** [angular/angular#12407]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The documentation describes the use of `inject()` and `async()` separately, but not how (or if) they interact or which is the one that users should be using. 

https://angular.io/docs/ts/latest/guide/testing.html
https://angular.io/docs/ts/latest/guide/testing.html#!#inject
https://angular.io/docs/ts/latest/guide/testing.html#!#async

I only found this thread about this topic, but am unsure if the information is even up to date: https://github.com/angular/angular/issues/5570

Apparently one can use inject() instead of async()? works in my tests at least, but that may be me....

**Expected behavior**
Document the relationship between the two. 
 
**What is the motivation / use case for changing the behavior?**
I have async tests but need to get injected services. There's too many ways to do the same thing right now (`inject`, vs. `TestBed.get` vs. the slightly different `DebugElement.injector.get`)

**Comment by DzmitryShylovich** [comment]
Pls re-open in the docs repo https://github.com/angular/angular.io

**Comment by vicb** [comment]
Please report docs issue on https://github.com/angular/angular.io/issues
