### ISSUE TITLE
Is there a way to load different javascript for different component?

### ISSUE THREAD

**Issue by basherr** [angular/angular#12406]
Can we get a way to also load Javascript files such like css file in the component section though I am oon Typescript Angular.

` @Component({ 
          selector: 'app-company', 
          templateUrl: './company.component.html', 
          jsUrl: ['toSomeLibrary.js'] 
})`

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
