### ISSUE TITLE
Combination of :host and sibling selectors is broken in emulated encapsulation

### ISSUE THREAD

**Issue by ukyo** [angular/angular#12402]
**I'm submitting a ...**  (check one with "x")

```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Behavior of the combination of :host and sibling selectors (e.g. `* + :host`, `* ~ host`) is different between `ViewEncapsulation.Emulated` and  `ViewEncapsulation.Native`.

**Expected behavior**
The behavior of emulated encapsulation and shadow DOM encapsulation should be same.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/3xdJGV?p=preview
- **Angular version:** 2.0.X
  
  
- **Browser:** [ Chrome 54 ]

**Comment by tbosch** [comment]
Please note: Our goal is not to have the exact same semantics as shadow DOM as we need to stay fast. 

But this case is probably doable... @vicb what do you think?

**Comment by DzmitryShylovich** [comment]
@ukyo looks like it was fixed. can u confirm pls ?

**Comment by tbosch** [comment]
Closing to keep our bug tracker under control. Please reopen if the problem still exists.

**Comment by woble** [comment]
Does not work for `:host + *` or `:host ~ *`, specificity of `*` is bumped which makes no sense.
