### ISSUE TITLE
Default Inputs values on structural directives are reset to null

### ISSUE THREAD

**Issue by NetanelBasal** [angular/angular#12404]
**Current behavior**
Default Input values on structural directives are reset to null.

When I am trying to set the default value on Input in my structural directive the value is reset to null.

For example:
```js
export class showTemplateDirective {
  @Input() showTemplate = true;
  constructor(
    private templateRef: TemplateRef<any>,
    private viewContainer: ViewContainerRef
    ) { }
    
  ngOnInit() {
   console.log(this.showTemplate);
   
   if(this.showTemplate) {
      this.viewContainer.createEmbeddedView(this.templateRef)
    } else {
     this.viewContainer.clear();
    }
  }  
  
}
```
 In this case showTemplate variable is null and not true
```html
<h2 *showTemplate>True</h2>
```

**Expected behavior** 
The `showTemplate` variable needs to be set to the default value if not value supplied.

**Minimal reproduction of the problem with instructions**
[Plunker](https://plnkr.co/edit/1OxxY1alZU6uA4BgtA4t?p=preview)

**Comment by DzmitryShylovich** [comment]
Workaround with setter https://plnkr.co/edit/IZn533jzlXRydwkIZNZB?p=preview

**Comment by alex-barberi** [comment]
@DzmitryShylovich Agreed. I had a situation yesterday where I needed to pass null as input.

However, I do also find the behavior the OP described to be confusing. You would think if I instantiated the value to `true`, it would be true.

**Comment by DzmitryShylovich** [comment]
How can compiler distinguish between 
```
<h2 *showTemplate></h2>
<h2 *showTemplate="null">False</h2>
```
?

**Comment by tbosch** [comment]
`@Input`s will always be written at least once, that's by design.
