### ISSUE TITLE
Unit test error with ngForm

### ISSUE THREAD

**Issue by saranyapm** [angular/angular#12403]
There is no directive "exportAs" set to "ngForm" ..
I am using 2.0.0 version
Done the template and component as per lastet form. 
My app is working fine. But in unit testing I am getting error.
I have already  included FormsModule in @NgModule.
I haven't added anything specific to form in spec. Anything extra I have to include in the spec files? 
Looking for solution..

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
