### ISSUE TITLE
Cannot bind rowspan on TD

### ISSUE THREAD

**Issue by erik777** [angular/angular#12419]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
			<td rowspan="{{myvalue}}">Spread</td>
Produces this error:

Unhandled Promise rejection: Template parse errors:
Can't bind to 'rowspan' since it isn't a known property of 'td'. 

**Expected behavior**

It is a valid property of HTML:

http://www.w3schools.com/tags/att_td_rowspan.asp

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Data has parent/child relationship.  When there are children, need the rowspan to equal the number of children plus 1.  Sometimes the children have their own TD, other times, it is one cell combined for the parent and its children.  With this bug, I have no way I know of to present it since I'm using Angular to bind the data to the table.  

**Please tell us about your environment:**

* **Angular version:** 2.0.6

* **Browser:** [all ]
 
* **Language:** [TypeScript X.X]

* **Node (for AoT issues):** `node --version` =

**Comment by mattdistefano** [comment]
Try `<td [rowSpan]="spanValue"></td>` or `<td [attr.rowspan]="spanValue"></td>`.

**Comment by DzmitryShylovich** [comment]
> Angular version: 2.0.6

pls update to the latest angular and provide working reproduction in plinkr

**Comment by robwormald** [comment]
Per your link, it is an *attribute*, which is used with the syntax `[attr.rowspan]` - HTML attributes and properties are very different things.

In the future, please include a reproduction in a plunker, as the instructions you deleted specified.
