### ISSUE TITLE
NG2 Router Enhancement: Support lazy component loading for each path defined in route config

### ISSUE THREAD

**Issue by mkrishna4u** [angular/angular#12415]
This is very good feature to support lazy loading of the component in router. I try to use the angular router for my application. my application is very big so i want to support lazy loading of the component for each path that are defined in routes. So that the application boots up quickly on the browser. To do so i came up with the approach how we can support it.

Currently we define the route like the way given below:

```
SAMPLE_ROUTES: Routes = [  
  { path: 'home',  component: Home },
  { path: 'search', component: Admin }
];
```

Now if we can change component property to support string value also (as given below) and load when the user accesses the particular path (if not already loaded), that way we can support lazy loading of the component:

```
SAMPLE_ROUTES: Routes = [  
  { path: 'home',  component: 'app/home/Home#Home' },
  { path: 'search', component: 'app/admin/Admin#Admin' }
];
```

"loadChildren" has its own meaning that is good for loading children but not the component of the children.

if you need more information or support please get back to me. Thanks.

**Comment by DzmitryShylovich** [comment]
You cannot lazy load components only modules https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load

**Comment by vicb** [comment]
> if you need more information or support please get back to me. Thanks.

Please provide the info requested in the issue template.

**Comment by Delagen** [comment]
@mkrishna4u You can make child module with route like
```
{
		path:       "",
		pathMatch:  "full",
		component: 
}
```

**Comment by mkrishna4u** [comment]
@DzmitryShylovich - I understand that we can only lazy load module. But if we want all components should be loaded lazily then for each component we have to write module. What i think that will be an overhead and not that clean. In real world scenario, all components should be loaded lazily so that application can be loaded quickly on the web browser and also this will help in reducing network traffic.

@Delagen - I understood your solution (I also thought this solution), that will perfectly work. But this solution does not look so clean due to overhead of creating additional @NgModule class and adding the required dependencies.

I also thought that if the @Component class should also be annotated with @NgModule so same class can work as Component and NgModule class. But i do not know what will be the side impact of doing this, how NG2 engine will handle this ? I tried this it was not giving any error for adding both annotations on the same class.

**Comment by robwormald** [comment]
In general, lazy loading only a component doesn't conceptually work, as it's unlikely in a real app you're ever going to have a standalone component without any child components and/or associated services and directives - restricting lazy loading to NgModules means you get all the necessary functionality in a single shot.

The runtime cost to creating modules is minimal, so we consider creating a module is a reasonable tradeoff here.

**Comment by mkrishna4u** [comment]
@robwormald I know on a high level module concept is very good but if we want to create a module that has many components then it will take long time to load on web browser. I just wanna reduce the network traffic along with fast module loading. So if we can add the flexibility of lazy component loading then this router will become  awesome. No other router can beat this router.

**Comment by vsavkin** [comment]
Loading individual components cannot work in the AoT mode. Closing this issue.
