### ISSUE TITLE
Unexpected behavior with custom validator class

### ISSUE THREAD

**Issue by govorov** [angular/angular#12423]
Hi.
**I'm submitting a ...**

```
[x] bug report
```

**Current behavior**
Here is the registration form, created with standard angular 2 form builder:

```
    this.form = this.formBuilder.group({
        login : [
            this.formValue.login,
            [
                Validators.required,
                Validators.minLength(loginLength.min),
                Validators.maxLength(loginLength.max),
                regexpValidator(loginPattern),
            ],
            //my custom validator class to check if login already exists
            LoginExistenceValidator,
        ],
        password : [
            this.formValue.password,
            [
                Validators.required,
                Validators.minLength(passwordLength.min),
                Validators.maxLength(passwordLength.max),
            ],
        ],
    });
```

As mentioned here - http://blog.thoughtram.io/angular/2016/03/14/custom-validators-in-angular-2.html#custom-validators-with-dependencies :

> It turns out that **a validator can also be a class** as long as it implements a validate(c: FormControl) method.

Hence it is possible to inject service to acess remote data from validator.

So I created such validator:

```
    import { Injectable, Inject, forwardRef } from '@angular/core';
    import { Validator, FormControl }         from '@angular/forms';

    import { UsersAdapter } from 'common/adapters/users';

    @Injectable()
    export class LoginExistenceValidator implements Validator {

        private adapter;

        constructor(@Inject(forwardRef(()=>UsersAdapter)) adapter) {
            debugger
        }

        validate(control: FormControl) {
            console.log("yep i'm called");
            return function(control: FormControl){

                //validation logic

                let validator = new Promise((resolve)=>{
                    //mock random success/fail for a while
                    setTimeout(()=>{
                        let random = Math.round(Math.random());
                        let value = random ? null : { reserved: true };
                        console.log(resolve);
                        resolve(value);
                    },2000);

                });

                return validator;

            }
        }
    }
```

UserAdapter is a wrapper around Angular Http, which retrieves data. Now I'm not using it and every validation call should return random success/fail result.

This code throws such error in browser:

```
EXCEPTION: Cannot read property 'subscribe' of undefined
```

Error occured because Angular do not actually calls `validate()`, and form control passed to constructor instead of provided UserAdapter service.

When I try to use function instead of class, everything works fine.
How can I tell angular to use my validation class properly? Thanks in advance.

**Expected behavior**
I expect Angular to call `validate()` method on my custom class and use function returned by this method for form validation.
- **Angular version:** 2.0.0

Thanks in advance.

**Comment by DzmitryShylovich** [comment]
Validator has to be a function (impl of the interface ValidatorFn/AsyncValidatorFn).

**Comment by govorov** [comment]
So what is the proper way to inject service to custom validator?

**Comment by DzmitryShylovich** [comment]
http://blog.thoughtram.io/angular/2016/03/14/custom-validators-in-angular-2.html#custom-validators-with-dependencies

**Comment by govorov** [comment]
Thank you for reply. This example uses `@Directive`. Is it possible to use it not in template-driven way?

**Comment by DzmitryShylovich** [comment]
Yes, just pass `EmailValidator.validate`

**Comment by pablolazaro** [comment]
I have a similar problem. 

I'm trying to build a validator to use it with DNI values (Spanish acronym for National Document Identification).

I want to validate DNI values with a service. Also, I want to reuse this service in the form control validator, so I follow these steps:

First I implemented the `ValidationService` service to hold all the validation logic:

```javascript
@Injectable()
export class ValidationService {
  isValidDNI (dni: string): boolean {
    // validation logic
  }
}
```

Then, I wrote the `CustomValidators` class to use it in the validator directive as well as in the `FormControl` constructor for Reactive Forms (`new FormControl('', [this.customValidators.dni])`):

```javascript
@Injectable()
export class CustomValidators {
  constructor (private service: ValidationService) { }

  dni (control: AbstractControl): {[key: string]: boolean} {
    return this.service.isValidDNI(control.value) ? null : { dni: true };
  }
}
```

Finally, I implemented the `DniValidator` directive.

```javascript
export const DNI_VALIDATOR: any = {
  provide: NG_VALIDATORS,
  useExisting: forwardRef(() => DniValidator),
  multi: true
};

@Directive({
  selector: '[dni][formControlName],[dni][formControl],[dni][ngModel]',
  providers: [ DNI_VALIDATOR ]
})
export class DniValidator implements Validator {
  constructor (private validators: CustomValidators) { }

  validate (control: AbstractControl) {
    return control.value ? this.validators.dni(control) : null;
  }
}
```

It works perfectly with template-driven forms but when I try to use it with Reactive Forms like this:

```javascript
...
constructor (
  private customValidators: CustomValidators,
  private builder: FormBuilder
) { } 
...

ngOnInit () {
  this.form = this.builder.group({
   'dni': ['', this.customValidators.dni]
  });
}
 ```

The framework returns the following error:

`EXCEPTION: Cannot read property 'isValidDNI' of undefined`

Is this working as expected?

You can see it in [this plunker](https://plnkr.co/edit/2kSVjvXAzyZm5lLg0eLG?p=preview).

Thank you very much.

**Comment by DzmitryShylovich** [comment]
@pablolazaro it has nothing to do with validators or angular. 
You need to read about `this` keyword in js.
Here's a working example https://plnkr.co/edit/17JnDvhjTrgTTbE90TtC?p=preview

**Comment by DzmitryShylovich** [comment]
@vicb can be closed

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource close?

**Comment by songkl** [comment]
`Validators.compose([Validators.required, Validators.minLength(passwordLength.min), Validators.maxLength(passwordLength.max)])`
