### ISSUE TITLE
网站的中文版有个很小的词语错误

### ISSUE THREAD

**Issue by frontzhm** [angular/angular#12426]
网址:https://angular.cn/docs/ts/latest/tutorial/toh-pt4.html
错误:网站中的"添加一个名叫 getHeros 的桩方法。"
建议修正为:"添加一个名叫 getHeroes 的桩方法。"
(*^__^*) 嘻嘻……       s->es

**Comment by michalstepien** [comment]
I think wrong repo.

**Comment by vicb** [comment]
Please report docs issue on https://github.com/angular/angular.io/issues
