### ISSUE TITLE
Error on "loadChildren" routing on webpack build

### ISSUE THREAD

**Issue by DarienF** [angular/angular#12432]
I have a problem with routing on Angular 2.1.0 using Webpack build.

Core versions:
```
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/compiler-cli": "0.6.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/platform-server": "2.1.0",
    "@angular/router": "3.1.0",
    "@angular/upgrade": "2.1.0",
    "angular-in-memory-web-api": "0.1.5",

    "webpack": "^1.13.0",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.14.0"

```
When I try to use Webpack core versions ^1.13.0 on Lazy-Loading route configuration -> Error: System in not defined. All configure-webpack files I use from: https://angular.io/docs/ts/latest/guide/webpack.html#!#configure-webpack

I try to use  Webpack core versions 2.1.0-beta.22 or 2.1.0-beta.25 (such versions of Webpack already available):
   ```
    "webpack": "2.1.0-beta.22",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": "^2.1.0-beta.2",
    "webpack-md5-hash": "^0.0.5",
    "webpack-merge": "^0.14.1"
```
Error: Cannot load module.
I fix this error by using such lazy-loading as: https://github.com/Quramy/angular2-load-children-loader
But unit-testing of components not working.

I asume issue in all cases with "loadChildren"  Lazy-Loading route configuration. I am not shure (only my suggestions) this error is common. There is some fix for this error? or this is something wrong with Webpack?

**Comment by DzmitryShylovich** [comment]
You should use https://github.com/brandonroberts/angular2-router-loader
Usage example https://github.com/qdouble/angular-webpack2-starter

This issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by DarienF** [comment]
Ok, I will try. Will report with my results later.

**Comment by DarienF** [comment]
There is no any notice of 'angular2-router-loader' on https://angular.io/docs/ts/latest/guide/webpack.html#!#configure-webpack or https://angular.io/docs/ts/latest/guide/router.html. It would be nice to add some info about it.

**Comment by DzmitryShylovich** [comment]
Feel free to file an issue in the docs repo https://github.com/angular/angular.io

**Comment by DarienF** [comment]
All working fine) thanks.
