### ISSUE TITLE
Matrix url bug when you use bracket in param value

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular#12436]
The example url:
`http://localhost:8080/#/search;param=value(value)value`

If I want to use bracket in my search query angular not encode bracket and parse like auxiliary route and it does not found any router-outlet with name of "value".

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by tamascsaba** [comment]
I think, it is a bug, how can you handle a user input which contains brackets in query string.

**Comment by DzmitryShylovich** [comment]
If u think it's a bug pls fill out the issue template and provide working reproduction in plunkr.

**Comment by tamascsaba** [comment]
I solve my problem with this snippet:
```typescript
this.router.navigate([], {
  queryParams: this.query ? {'query': this.query} : {},
  relativeTo: this.route
});
```
