### ISSUE TITLE
Error with lazy loading 

### ISSUE THREAD

**Issue by calvinKG** [angular/angular#12433]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Am on Angular 2.0 and implementing lazy loading with 3 modules (Root, Parent and Child) and I get the 404 (Not Found) for the child module am calling for lazy loading. 

**Root(app.routes.ts)**

`export const appRoutes: Routes  = [

    ...loginRoutes,
    {
        path: '**',
        redirectTo: 'login'
    },

];
`
**Parent (Fleet)**
`@NgModule({

    imports: [CommonModule,
        RouterModule.forChild(fleetRouteConfig)],
    declarations: [FleetComponent,
                   TopMenu],})
export default class FleetModule{}`

**Parent Routes** 

`export const fleetRouteConfig: Routes  = [
    {
        path: 'fleet',
        //component: FleetComponent, canActivate: [AuthGuard],
       component: FleetComponent,
        children: [
            {
                path: 'home',
                component: HomeComponent
            },
            {
                path: 'help',
                component: HelpComponent,
            },
            {
                path: 'user-auth',
                loadChildren: 'src/app/pages/user-auth/ua.module#UAModule'
            },
}
];`

**Child Module** 
`const uaRouterConfig = [
    {
        path: '',
        component: UAComponent,
        children: [
            {
                path: 'ua-functional-admin',
                component: UAFunctionalAdmin
            },
            {
                path: 'ua-job-role-admin',
                component: UAJobRoleAdmin
            },
        ]
    }
];

@NgModule({
   imports: [CommonModule,
            RouterModule.forChild(uaRouterConfig)],

   declarations: [UAComponent, UAFunctionalAdmin, UAJobRoleAdmin],
   providers: []
})
export class UAModule{}`

![image](https://cloud.githubusercontent.com/assets/1926014/19595172/e8480f44-9788-11e6-8489-9a26042a5ac8.png)

**Expected behavior**

To  implement lazy loading. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls provide a minimal **working** reproduction in plunkr.

**Comment by vicb** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
