### ISSUE TITLE
Reduced visibility on template variables

### ISSUE THREAD

**Issue by lqbweb** [angular/angular#12434]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Right now, template variables are visible for the whole template, so we cannot have two template variables, on sibling elements named in the same way. If you do so you get:

`Reference "#xxxx" is defined several times `

**Expected behavior**

Without changing the current behavior, we could have a modifier, or an argument, that adjust the scope of the template variable.

I am not sure what syntactically would make more sense, but here it is an idea:

```
<my-app>
    <my-dir local:#var>
        <span>var: {{ var.getValue() }}</span>
    </my-dir>
    <my-dir local:#var>
        <span>var: {{ var.getValue() }}</span>
    </my-dir>
</my-app>
```

Also, with that syntax, as "local" is a namespace we could default it somehow:
https://www.w3.org/TR/REC-xml-names/#defaulting

But again, I think you guys should decide on how. I am far to be experienced with angular2.

**Minimal reproduction of the problem with instructions**

This fails to compile:
http://plnkr.co/edit/Bn9TMqHnQWFRUtolI4rl

**What is the motivation / use case for changing the behavior?**
I know that you could just name differently the variables, but it is not that clean, specially when they kind of represent the same thing.

I am attempting to write some sort of business templates that more people could use. The more functional the language is, the clearer and easier to understand what it does by normal people.

Besides, that I could expect collisions on the names of variables on big templates, and people wondering why a variable is named "myComponent23". Even refactoring templates could cause unexpected results because of picking another component variable than the one expected.

I think it kind of makes sense.

**Comment by lqbweb** [comment]
I hope that this is clear now. As #12394 was closed because of missing information.

**Comment by vicb** [comment]
Introducing a new "local" keyword to change the scope would be both confusing and not really useful.

Only use a different name.

You might want to export your div and do

`<tag #var1="myDir">` if you think it makes things clearer.
