### ISSUE TITLE
Missing steps to build angular

### ISSUE THREAD

**Issue by gary-b** [angular/angular#12443]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
There are additional steps required to build angular not included in the developer guide, some of which could be scripted.

a) On Windows / Linux npm install will fail because fsevents requires a mac.

b) On Windows build.sh fails because it tries to create a symlink to the polymer directory and it doesn't exist. This is because the dependency is managed by bower, and _bower install_ is never ran. (The script does not fail on Linux when the directory is missing.)

**Expected behavior**
I'm planning to submit a PR to:
1. Provide a script to remove the fsevents dependency when not on a mac and update dev guide to advise running it. (Better solutions welcome...)
2. Have _bower install_ run automatically when _npm install_ is ran (using the packages.json postinstall step).

**Minimal reproduction of the problem with instructions**
Install and build on Windows following guide

**What is the motivation / use case for changing the behavior?**
Make life easier for us noobs.

**Please tell us about your environment:**
Windows 10, Node v5.12.0, NPM v3.10.8, Bower v1.7.9
LUbuntu 16, Node v5.12.0, NPM 3.10.9
- **Angular version:** 2.0.X
  Angular master
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  N/A
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  N/A
- **Node (for AoT issues):** `node --version` =  
  v5.12.0

**Comment by e-cloud** [comment]
it's not necessary to have a script to change the `npm-shrinkwrap.json`.

You can run `npm i -f` to force installation.

Nevertheless, the bower part is worthy. But you dont have to refer the bin path, because [npm run script automatically add the bin path to PATH](https://docs.npmjs.com/cli/run-script)

**Comment by gkalpak** [comment]
This is now obsolete, as we have moved to a different build toolchaon.
(There might still be issues with building on Windows, which we are working on, but the problems mentioned here should not be relevant any more.)
