### ISSUE TITLE
Router, canActivate as Directive

### ISSUE THREAD

**Issue by morriq** [angular/angular#12444]
Hello.

I need to have next to routerLink directive, new one directive: routerLinkCanActivate. I wonder how to do it correctly, could you help me, please?

What's important - I dont want to pass any argument to directive. It should get info from defined routing, from module file.

**Comment by ericmartinezr** [comment]
You'll get more chances of a good answer by following this link https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
