### ISSUE TITLE
Emulated ViewEncapsulation issue with CSS pseudo classes on :host

### ISSUE THREAD

**Issue by mrshaq** [angular/angular#12451]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When Encapsulation is enabled for a component, CSS pseudo class `:host::-webkit-input-placeholder` and perhaps every pseudo class applied to :host is encapsulated incorrectly.

**Expected behavior**

`:host::-webkit-input-placeholder { ... }` is expected to be compiled into `[_nghost-any-id]::-webkit-input-placeholder { ... }` but instead it's being compiled into `::-webkit-input-placeholder[_nghost-any-id] {...}`

**Minimal reproduction of the problem with instructions**

To reproduce create a component with an attribute selector like
`@Component({ selector: '[comp]', encapsulation: ViewEncapsulation.Emulated, ...` and then apply it to an input element like `<input comp type="text" placeholder="Username">` and in the CSS definition for the component have something like `:host::-webkit-input-placeholder { color: red; }` which should turn the placeholder red on Webkit browsers and then check the style generated by Angular for the input element.

**What is the motivation / use case for changing the behavior?**

Anywhere that CSS pseudo classes should be applied to the host

**Please tell us about your environment:**

macOS Sierra (10.12), VSCode 1.6.1, NPM 3.10.3, NG Live Development Server (Part of angular-cli: 1.0.0-beta.17)
- **Angular version:** 2.0.X
  
  
  
  Angular 2.0.0
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
  
  Chrome 53.0.2785.143
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  TypeScript 2.0.2
- **Node (for AoT issues):** `node --version` =
  Node 6.5.0

**Comment by krassx** [comment]
I noticed similar problems with before/after pseudo elements. Below is the CSS generated by compiler:

```
<style>[_nghost-pwc-11] {
  position: relative;
  display: inline-block;
  vertical-align: middle; }
  [_nghost-pwc-11]   .wrap[_ngcontent-pwc-11] {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ffffff;
    overflow: hidden;
    -webkit-clip-path: url(#appIconClipPath);
            clip-path: url(#appIconClipPath);
    z-index: 2; }
    [_nghost-pwc-11]   .wrap[_ngcontent-pwc-11]    > i[_ngcontent-pwc-11] {
      position: absolute;
      display: block;
      top: 2px;
      left: 2px;
      width: calc(100% - 4px);
      height: calc(100% - 4px);
      background: 50% 50% no-repeat;
      background-size: contain;
      z-index: 2;
      -webkit-clip-path: inherit;
              clip-path: inherit; }
  .raised:before[_nghost-pwc-11] {
    display: block;
    content: "";
    position: absolute;
    top: 3px;
    left: 3px;
    right: 3px;
    bottom: 3px;
    border-radius: 30%;
    box-shadow: 0 0 13px 0 rgba(0, 0, 0, 0.3);
    z-index: 1; }
  .fallback[_nghost-pwc-11]   .wrap[_ngcontent-pwc-11]    > i[_ngcontent-pwc-11] {
    top: 25%;
    left: 25%;
    width: 50%;
    height: 50%;
    -webkit-clip-path: none;
            clip-path: none; }</style>
```
Notice ```.raised:before[_nghost-pwc-11]```, which must be either ```[_nghost-pwc-11].raised:before``` or ```.raised[_nghost-pwc-11]:before```

**Comment by skreborn** [comment]
This has been fixed in the [2.1.0 incremental update](https://github.com/angular/angular/blob/master/CHANGELOG.md#210-incremental-metamorphosis-2016-10-12). See the issue [here](https://github.com/angular/angular/issues/12165) and the fix [here](https://github.com/angular/angular/pull/12171).

**Comment by krassx** [comment]
I am using Angular 2.1.1 and still get into that issue. Had to switch to nested elements to fix it.

**Comment by krassx** [comment]
Here is a plunker: https://plnkr.co/edit/OmQjUQALRjZWvULAr1nz?p=preview

Take a look at how <style> with :before pseudo element.

**Comment by holiber** [comment]
I've got same problem after updating project from 2.0.0 to 2.1.1

**Comment by mrshaq** [comment]
I just upgraded to 2.1.1 and the problem is solved for me. 

To clarify this is the problem I had with 2.0.0 and no longer have with 2.1.1: `:host::-webkit-input-placeholder { ... }` would compile into `::-webkit-input-placeholder[_nghost-unq-id] { ... }` instead of `[_nghost-unq-id]::-webkit-input-placeholder { ... }`.

I haven't tested other pseudo classes. Would you guys kindly upgrade to 2.1.1 and confirm that it's fixed for you as well?

**Comment by holiber** [comment]
I still have this problem on 2.1.1. Here is simple example:
http://plnkr.co/edit/1ZzuPXPKmj0C5UQjIfyr?p=preview

`app.component` has `active` class on `:host` and next css:
```css

:host:after {
  content: 'Component has no classes';
  color: red;
}

:host.active:after {
  content: 'Component has "active" class';
}

```
That compiled to:

```css

[_nghost-wpn-1]:after {
  content: 'Component has no classes';
  color: red;
}

.active:after[_nghost-wpn-1] {
  content: 'Component has "active" class';
}
```


Where `.active:after[_nghost-wpn-1] ` is invalid selector

**Comment by holiber** [comment]
@mrshaq, try to add any class to `:host` in your code, like `:host.some-class-on-host::-webkit-input-placeholder`, I think it will broke it.

**Comment by skreborn** [comment]
I'm not sure `:host.class:after` is actually valid CSS. See the specifications [here](https://drafts.csswg.org/css-scoping/#host-selector). The correct syntax seems to be `:host(.class):after`, but it still generates the same output. See updated Plunker [here](http://plnkr.co/edit/gXQeMlelCwCMwOae4ZG9?p=preview).

**Comment by holiber** [comment]
@skreborn, in your Plunker  `:host(.active):after` also compiles to `.active:after[_nghost-wpn-1]`. It's still a problem.

**Comment by skreborn** [comment]
That's exactly what I said - it still produces the wrong output, even if the selector is valid by specifications.

**Comment by vicb** [comment]
related issues #12402 #12354

**Comment by mrshaq** [comment]
@holiber I tested what you said and you're right. The issue still exists if `:host` is mixed with any other selector. For example:

`:host(.active)::-webkit-input-placeholder` or `:host.active::-webkit-input-placeholder` both compile into the incorrect: `.active::-webkit-input-placeholder[_nghost-unq-id]` instead of `[_nghost-unq-id].active::-webkit-input-placeholder`.

The only scenario in which the issue is fixed by upgrading to 2.1.1 version is when the only selector before the pseudo class is `:host` and only `:host`. Any other combination will result in the same bug.

**Comment by vicb** [comment]
@mrshaq your original issue has been fixed, angular now generates `<style>[_nghost-gyk-1]::-webkit-input-placeholder { color: green; }</style>`.

Please open further issues for other pbs (ie I don't browse all the stuff in this thread, only the original issue)

**Comment by vicb** [comment]
what would that mean `:host(.active:after)` ?
