### ISSUE TITLE
Initial Page Loading taking time in Angular2

### ISSUE THREAD

**Issue by Gchandru** [angular/angular#12459]
**Current behavior**
Page Rendering is taking time in initial load in Angular2.page loading time taking 4 to 6 sec for rendering UI elements in every page load.

**Expected behavior**
Our requirement will be load the page with in 2 seconds

**What is the motivation / use case for changing the behavior?**
I am trying to open a another page from parent page. but UI rendering taking time in initial load. its taking 4 to 6 sec for rendering UI element for every refresh.
Script execution for creating UI element is taking time in build copy 
we are using angular 2.0.1 and for build we are using gulp with systemjs build file

* **Angular version:** 2.0.X
we are using  latest version (Angular,Node ,Npm,Typescripts)

Please share your ideas & suggestion for reducing loading time in Angular 2. 

Thank you in advance.

**Comment by DzmitryShylovich** [comment]
To reduce start up u have several options:
1. Server side rendering (universal).
2. aot compilation.
3.  lazy loading.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich
