### ISSUE TITLE
No recommended selector for multiple content projection slots in the styleguide

### ISSUE THREAD

**Issue by joeeames** [angular/angular#12450]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

The documentation & styleguide has no guidance for how to do a selector for multiple content projection slots. What is the "best practice" for selectors for multiple content projection?

Given the following:
 <projected-component>
  <div my-title>
    ...
  </>
  <div my-body>
    ...
  </>
</projected-component>

and then in the projected component I would have:
<ng-content select="[my-title]" ...
<ng-content select="[my-body]" ....

But any selector can work. i.e. class selectors, given the right change to the HTML.
<ng-content select=".my-title" ...
<ng-content select=".my-body" ....

Or something else?

The styleguide should recommend a best practice.

**Comment by joeeames** [comment]
@johnpapa @IgorMinar @wardbell

**Comment by DzmitryShylovich** [comment]
Please report docs issue/questions on https://github.com/angular/angular.io/issues
