### ISSUE TITLE
move static upgrade code to @angular/upgrade/static

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#12452]
**I'm submitting a ...**  (check one with "x")

```
[x] feature request
```

All static upgrade code (currently in upgrade/src/aot) should be publicly exported from `@angular/upgrade/static` so that we can treeshake the compiler.

Currently these symbols are exported via `@angular/upgrade` which brings in the compiler code. These reexports should be removed.

Additionally we should create a separate bundle for the static upgrade published as `@angular/upgrade/bundles/upgrade-static.umd.js`. 

Summary:
- [x] export static upgrade code via `@angular/upgrade/static`
- [x] remove reexports from `@angular/upgrade` - document this as a breaking change since the last beta
- [x] create new umb bundle
- [x] add the new entry point to api guardian
- [ ] add the new entry point to angular.io dgeni entry point list 
- [ ] move the source code from `@angular/upgrade/src/` to `@angular/upgrade/static/` or `@angular/upgrade/static/src`

// this design was discussed in person with @mhevery and @alexeagle

**Comment by IgorMinar** [comment]
PR that partially solves this: #12425

**Comment by thelgevold** [comment]
Based on feedback from @alexeagle I tried deep importing the ng-upgrade dependencies in hopes that it would enable the Tree shaker to shake out the compiler completely. 

After adding deep imports, it does appear to include less of the compiler than before, but the compiler still makes up abut 20% of my rollup bundle. This is down from 50% which was the pre-deep import result. 

I have peeked into the generated bundle using source-map-explorer. Here is the result. As you can tell the compiler is still in there. It accounts for 20% of the size
http://www.syntaxsuccess.com/img/deps-aot-ng-upgrade.png

The relevant code can be found in my repo https://github.com/thelgevold/angular-2-samples, but here is the relevant code.

```
//upgrade-module.ts
import {Component, NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {ReactiveFormsModule} from '@angular/forms';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import {UpgradeModule} from '@angular/upgrade/src/aot/upgrade_module';
import {downgradeComponent} from '@angular/upgrade/src/aot/downgrade_component';

import {TextEditor} from './components/text-editor/text-editor';
import {Algorithms} from './components/algorithms/algorithms';
import {SurveyDemo} from './components/survey/survey-demo';
import {Survey} from './components/survey/survey';
import {InsertionSort} from './components/insertion-sort/insertion-sort';

declare var angular:any;

@NgModule({
  declarations: [Algorithms, InsertionSort, SurveyDemo, Survey, TextEditor],
  entryComponents: [Algorithms, InsertionSort, SurveyDemo, Survey, TextEditor],  
  imports: [BrowserModule, UpgradeModule, ReactiveFormsModule]
})
export class AngularModule {
  ngDoBootstrap() {}
}

// upgrade.ts
import {Component, NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {ReactiveFormsModule} from '@angular/forms';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

import {UpgradeModule} from '@angular/upgrade/src/aot/upgrade_module';
import {downgradeComponent} from '@angular/upgrade/src/aot/downgrade_component';

import {TextEditor} from './components/text-editor/text-editor';
import {Algorithms} from './components/algorithms/algorithms';
import {SurveyDemo} from './components/survey/survey-demo';
import {Survey} from './components/survey/survey';
import {InsertionSort} from './components/insertion-sort/insertion-sort';

import {AngularModuleNgFactory} from './upgrade-aot/upgrade-module.ngfactory';

declare var angular:any;

angular.module('angular-legacy').directive('algorithms', downgradeComponent({component: Algorithms}));
angular.module('angular-legacy').directive('survey', downgradeComponent({component: SurveyDemo}));
angular.module('angular-legacy').directive('editor', downgradeComponent({component: TextEditor}));

platformBrowserDynamic().bootstrapModuleFactory(AngularModuleNgFactory).then((ref) => {
  const adapter = ref.injector.get(UpgradeModule) as UpgradeModule;
  console.log('bootstrapping');
  adapter.bootstrap(document.body, ['angular-legacy']);
});

//rollup
import rollup      from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify';
import closure     from 'google-closure-compiler-js';

export default {
  entry: 'upgrade.js',
  dest: './dist/upgrade-build.js',
  sourceMap: true,
  sourceMapFile: './dist/upgrade-build.js.map',
  format: 'iife',
  plugins: [
      nodeResolve({jsnext: true, module: true}),
      commonjs({
        include: 'node_modules/rxjs/**',
      }),
      uglify()
  ]
}
````

That said... I suspect you're going to want a smaller repro :-) I don't have one at the moment, but can maybe provide one later. Including this as an FYI for now since I believe my setup is correct with all upgrade refs updated to deep import

cc: @robwormald @mhevery @petebacondarwin 

In any event your progress on this has been great! My app is otherwise working with relatively complex components here: http://www.syntaxsuccess.com/angular-2-samples/upgrade.html

Version 2.2.0-beta.0

**Comment by alexeagle** [comment]
You still have an import from platform-browser-dynamic, which depends on
compiler. You should remove that.

**Comment by thelgevold** [comment]
Doh, that makes sense. I am importing from the wrong platform browser object...

Curious what is the need for a public bootstrapModuleFactory method on platformBrowserDynamic? 

Shouldn't we always be using `bootstrapModule` in JiT scenarios. 

I thought the bootstrapModuleFactory method only makes sense for AoT. Here I've made the mistake of calling the method on the wrong object.  Could this method be removed from platformBrowserDynamic to guarantee that we won't make this mistake? Or is there a valid use case that I'm missing?

**Comment by alexeagle** [comment]
I imagine this is because you could have a mixed-mode application where you bootstrap some entry points that were compiled with AoT and others that were not?
@mhevery could confirm

**Comment by thelgevold** [comment]
Thanks for your help here @alexeagle 
It totally works now in 2.2 beta.1. There is no trace of the compiler in my bundle.

**Comment by alexeagle** [comment]
I'm curious, what size app are you getting (after compression)?

**Comment by petebacondarwin** [comment]
I think we can close this one now?
