### ISSUE TITLE
Build.sh hangs on MINGW64 Bash Shell

### ISSUE THREAD

**Issue by gary-b** [angular/angular#12454]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Execution of build.sh hangs on the MINGW64 bash shell provided with Git for Windows. The script loops over packages in the @angular directory building each in turn. The hang occurs when uglify is called against the first package - I see the warnings about unreachable code then nothing but a cursor. Running the script in bash's debug mode confirms the call to uglify is the last to be made. Node.exe memory usage stays very low and does not fluctuate. 

_This is where the issue gets weird:_
1.  I got the build to complete yesterday
2.  I can resolve the issue by changing line 160 from

``` shell
    ) 2>&1 | grep -v "as external dependency"
```

to

``` shell
    ) 2>&1
```

The downside of this is you get more noise in the terminal - but it hasn't hung a single time. The tests seem to all pass afterward as well. As soon as I change the line back - the script hangs every time.

**Expected behavior**
New devs can get build.sh to reliably complete. If a change isn't committed then maybe a note should be added to the dev guide. 

**Minimal reproduction of the problem with instructions**
Build on windows using the Git for Windows bash shell. (You will need the fixes from my other 2 PRs to get past other problems)

**What is the motivation / use case for changing the behavior?**
Removing obstacles in the way of new contributors building the project is good.

**Please tell us about your environment:**
Windows 10, Git for Windows 2.8.1.windows., Node v5.12.0, NPM v3.10.8
- **Angular version:** 2.0.X
  Angular Master from 2 days ago.
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  N/A
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  N/A
- **Node (for AoT issues):** `node --version` =  
  Node v5.12.0

**Comment by thorn0** [comment]
Having this issue too.

* Windows 7 x64, git version 2.10.0.windows.1, Node v6.9.1, NPM v3.10.8
* Angular: `master` (77cbf7f2bb9)

The workaround with removing `| grep -v "as external dependency"` worked fine.

**Comment by DzmitryShylovich** [comment]
@gary-b is this still valid?

**Comment by snerks** [comment]
I just tried this (see #17894).

The change proposed by @gary-b, above, makes the difference, such that the build completes on Windows 7 SP1 x64. Thanks @gary-b!

**Comment by IgorMinar** [comment]
I believe that #19608 fixed this. if not, can you please open up a new issue and provide more details?
