### ISSUE TITLE
Renderer.animate(...).play() resets animation to its initial state on finish

### ISSUE THREAD

**Issue by alobakov** [angular/angular#12456]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When Renderer.animate(...).play() is called, the animation is played back correctly, but immediately jumps to the initial state once finished. The default `'fill' : 'both'` option passed into the constructor of WebAnimationsPlayer by WebAnimationsDriver has no effect due to an explicit call to `this._player.reset()` being performed from within WebAnimationsPlayer.destroy().

**Expected behavior**
Finished animations should not be reset by the destructor of WebAnimationsPlayer.

**Minimal reproduction of the problem with instructions**

At the end of the animation, the element jumps right back to its initial position:
`this._renderer.animate(
                element.nativeElement,
                {
                    styles: [{transform : 'translate(0, 0)'}]
                },
                [
                    {
                        offset: 1,
                        styles: {
                            styles: [{transform : 'translate(100px, 200px)'}]
                        }
                    }
                ],
                5000,
                0,
                'ease'
            ).play();
`

**What is the motivation / use case for changing the behavior?**
Since 'fill':'both' is used by WebAnimationsDriver as the default animation-fill-mode, when animation completes the target element must have its styles set to those specified in the respective end keyframe.

**Please tell us about your environment:**
Win10
VS Code 1.6.1
npm 3.10.3
node 6.3.1
@angular 2.1.0
AspNet.Core 1.0.1
- **Angular version:** 2.1.0
- **Browser:** [Chrome 53 | Opera 40.0]
- **Language:** [TypeScript 2.0 | ES6]

**Comment by matsko** [comment]
Turns out that this needs to be changed anyway to make web workers work with animations!
