### ISSUE TITLE
window.location.href does not works with schemas: [CUSTOM_ELEMENTS_SCHEMA]

### ISSUE THREAD

**Issue by RamitAnandSharma** [angular/angular#12457]
[ ] bug report => 
 
To resolve #11251 
Added schema configuration in @NgModule

```
@NgModule({
schemas: [CUSTOM_ELEMENTS_SCHEMA]
......
})
```

**Current behavior**
Changing the value of the property does not redirects the page.

`window.location.href = "https://jqueryui.com/"; `

**Expected behavior**
Changing the value of the property should redirect the page.

 
**Please tell us about your environment:**
Windows 10, Angular Cli

* **Angular version:** 2.0.X
Angular 2.0.0 Final

* **Browser:** 
Chrome XX  Firefox XX  

 
* **Language: 
TypeScript 

 `node --version` =   6.7.0

**Comment by DzmitryShylovich** [comment]
Pls provide a working reproduction in plunkr.

**Comment by RamitAnandSharma** [comment]
Working reproduction in plunkr.

http://plnkr.co/edit/YP2iqEBJPsDrPYbaaZ6f?p=preview

**Comment by fxck** [comment]
http://plnkr.co/edit/VNbfLP8ikWg5InnmcuiW?p=preview there you go, fixed
