### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by phanivaranasi** [angular/angular#12458]
Hi,
I'm trying to build an small small taking 2 templates 
#1. Anonymouse Template #2. AuthUser Template

How can i design routing table that certain views can use anonymous templates and and some views can use authuser template 

Can any I assist me in this regard.

Thanks
Phani

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
