### ISSUE TITLE
Clarify dependencies & polyfills

### ISSUE THREAD

**Issue by code-tree** [angular/angular#12468]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
It is not clear what dependencies Angular requires, and why.

Some dependencies are vaguely mentioned in the Docs' Quickstart, and while the page on Browser Support helps, it also adds some confusion. It is not clear what are actually dependencies and what are just polyfills. Nor is it clear which ones are really required.

**Expected behavior**
State clearly what is required, and why.

AFAIK: Almost all Angular's dependencies are really polyfills, as most are being proposed to be added to browsers in future. The only real dependency seems to be `rxjs`.

As for the polyfills, `core-js` is recommended for ES6, but really it covers some of ES7 and `reflect-metadata`. So if people include `core-js` then they don't need `reflect-metadata`. It is also not clear what other (if any) ES7 features are required.

Clarifying this kind of stuff would be very helpful, and preferably on the one page. I had to flick between the Quickstart and Browser Support pages until I finally figured out what I actually needed to include.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
Help new developers

**Please tell us about your environment:**

* **Angular version:** 2.1.0

* **Browser:** Chrome 55
 
* **Language:** N/A

* **Node (for AoT issues):** N/A

**Comment by pkozlowski-opensource** [comment]
Most of this info is already covered in https://angular.io/docs/ts/latest/guide/browser-support.html

If you think that this info needs to be expanded upon, please open a separate issue in  https://github.com/angular/angular.io where all documentation is located. Thnx!

**Comment by code-tree** [comment]
ok, thanks
