### ISSUE TITLE
Angular 2 router when navigate to another url not reseting the outlet

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#12469]
I have route with different outlet called compose, for example:

`<a [routerLink]="[{outlets: {primary: 'about', compose: 'new-message'}}]">About with compose</a>`

When I clicking on the link the URL is:
`http://localhost:4200/about(compose:new-message)`

That's fine, but when I clicking on this:
`
<a routerLinkActive="active" [routerLink]="['/home']">Home</a>`

The URL is still with the outlet:
`http://localhost:4200/home(compose:new-message)`

What I am expecting is:
`http://localhost:4200/home`

The solution I found is to reset the outlet like this:
` <a [routerLink]="[{outlets: {primary: 'home', compose: null}}]">Home</a>`
But this is so verbose and annoying, because I will need do this in every link, There is a better way?

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
