### ISSUE TITLE
Extending directives (code reuse feature request)?

### ISSUE THREAD

**Issue by alexbyk** [angular/angular#12460]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see 
```

I'm trying to extend a RouterLink directive to append a prefix to each link. `<a myLink="/photos">` -> `/myregion/photos`, where `myregion` is a state value, shared by service. Right now the only simple way I see is to copy-paste existing code and change it for my needs, because I tried several obvious solutions and they didn't work

It would be great to have an official way to reuse a code.

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/11606

**Comment by alexbyk** [comment]
Not a 100% duplicate, but related. I'm moving to that thread and closing this one
