### ISSUE TITLE
Sugestion - new decorator to use NgModel

### ISSUE THREAD

**Issue by piernik** [angular/angular#12479]
I needed to make my own input directive that uses `NgModel`. I found this solution: http://almerosteyn.com/2016/04/linkup-custom-control-to-ngcontrol-ngmodel.
It is way too complicated.
And tharefor I have suggestion. Why not add param to `@Component` decorator like: `useNgModel: true` and all will be easy and clean.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by piernik** [comment]
It's not an issue or bug - it's only sugestion to make angular more user friendly.
If You read article You get what I want.
