### ISSUE TITLE
Allow child components of a `changeDetection: OnPush` host to have `Default` change detection

### ISSUE THREAD

**Issue by sod** [angular/angular#12480]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Child components of a `changeDetection: ChangeDetectionStrategy.OnPush` can't go back to `ChangeDetectionStrategy.Default`.

Plunkr: http://plnkr.co/edit/d2TKvyzVWNckdVYPqEgM?p=preview

![image](https://cloud.githubusercontent.com/assets/905328/19641800/aa1b3e38-99e2-11e6-8180-f4dba57b8e04.png)

One root component with `ChangeDetectionStrategy.OnPush` + three child components that have an asynchronous interval that changes its variable `innerValue`. 
* `<component-1>` updates every 1500ms with offset of 0ms - doesn't update the view
* `<component-2>` updates every 1500ms with offset of 500ms - doesn't update the view (with `ChangeDetectionStrategy.Default`, but has no effect)
* `<component-3>` updates every 1500ms with offset of 1000ms - updates everything (with `this.changeDetectorRef.markForCheck()`)

**What is the motivation / use case for changing the behavior?**
Be able to have a child of a OnPush component, that updates automatically on asynchronous tasks.

* **Angular version:** 2.1.1
* **Browser:** all
* **Language:** TypeScript 2.0.3

**Comment by DzmitryShylovich** [comment]
It doesn't make sense. It will kill the whole idea. 
Don't use it on parent component/use `hangeDetectorRef.markForCheck()` manually.

**Comment by sod** [comment]
I thought this was the magic about zone.js? Detecting when async tasks finish and update the requester component and all its children. Don't know why a child should inherit change detection behavior from its parent. This behavior currently prevents any async method from working in the template (https://github.com/angular/angular/issues/12378, https://github.com/angular/angular/issues/10816)

**Comment by sod** [comment]
As it's a feature request and this is by design, I'll just close it. Maybe we should add to https://angular.io/docs/ts/latest/api/core/index/ChangeDetectionStrategy-enum.html that `OnPush` hands down to all children.

**Comment by DzmitryShylovich** [comment]
I agree docs should be updated.
http://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html good article about change detection.

**Comment by paramsingh88** [comment]
I don't understand the idea of `ChangeDetectionStrategy.OnPush`. If we have to use `cdRef.markForCheck()` in the children component to shatter the `ChangeDetectionStrategy.OnPush` thing for all it's ancestors, there's no use of even using it. And those are local variables of Child components for which `markForCheck()` or `detectChanges()` is to be used every time or else they don't update the child view.

**Comment by ali-mahmoodvand** [comment]
import this
```import {ChangeDetectorRef} from '@angular/core';```
and usee in class
```               constructor(  private cd: ChangeDetectorRef){}```
and setInterval like this
```  ngOnInit() {
    setInterval(()=>{
      this.cd.markForCheck();
    },200)}```

**Comment by cassianomon** [comment]
@ali-mahmoodvand thanks, it worked for me.

**Comment by bentaly** [comment]
This may work but you're making a loop to check changes, which is the same as the Default strategy, just probably not implemented as efficiently

**Comment by mlc-mlapis** [comment]
... hmm, are we still taking about the principal of `OnPush`? Because it is really simple:

* a parent component passes an object through `@Input()` to its child,
* the child has `ChangeDetectionStrategy.OnPush` set,
* the object is passed via a reference so `ngOnChanges()` hook is able to recognize if the reference has been changed or not (in comparison to the previous) = a new immutable object was passed or not from its parent,
* if it is a new reference ... CD is run on that child, if not then CD is not run on that child.

And that's all.

**Comment by larssn** [comment]
@mlc-mlapis Thanks, but I'm mostly curious as how child components behave if a parent component is set to OnPush. As DzmitryShylovich hinted at back in 2016 (Angular 2), the child components would inherit the OnPush state from the parent. Wondering if that's still the case?

**Comment by mlc-mlapis** [comment]
@larssn .. hmm, long time. I don't think that children components of a parent which itself is set to `OnPush` should inherit the same configuration.

It is necessary to mention that `ngDoCheck()` hook in that parent component (which is `OnPush`) is invoked by its grand-parent component. But it is a general design which is valid for all components and it is not anything extra only just for `OnPush` components. More discussions about it here https://github.com/angular/angular/issues/7055

So the main effect is still related to the fact if an immutable reference is passed or not through `@Input()`. And it is enough because it also means whether CD flows down the children components or not.

**Comment by sod** [comment]
OnPush still inherits to children and can't be revert back to Default. The module where we hit the issue is still a major pain point in the team. Every once in a while someone wonders why his new component doesn't update automatically until someone else helps him/her.

The root cause why we hit this issue at all is because we inject state machines via dependency injection. So values are not passed around via input/output. OnPush can't really detect anything at all with this code style.

If I had time to refactor it I may extend the state machines to trigger change detection if a value changes.

I guess the recommendation is to either pass values via `[inputs]` only, or in case of state machines, use a library like `@ngrx` (but haven't tried that yet).

**Comment by mlc-mlapis** [comment]
@sod ... but **pure dependency on a change through `@Input()`** is and always was the main idea of `OnPush` strategy = its real simplicity. With other combinations as making a change from inside that component, using DI, observable / subscribe patterns ... you have to count also with them and this creates more complex scenarios.

What do you mean by `OnPush still pass on to children and can't revert back to Default.`? That `OnPush` setting on some component is inherited also by any of its children?

**Comment by pwpatton** [comment]
It's just hard finding information that the child inherits the CDS of it's parent when the parent is OnPush. Would be really nice that were clearly stated in documentation.

**Comment by vthinkxie** [comment]
this link maybe useful https://danielwiehl.github.io/edu-angular-change-detection/

**Comment by zapper142** [comment]
ChangeDetectionStrategy.Isolated

Usage:
Prevent change detection from noisy parents while retaining normal functionality inside component (not having to manually markForCheck())
Changes in @Input() will also trigger CD (+ the other OnPush things)

Reason:
Performance for child components that do not rely on parent componentstate.


Wondering and contemplating any design philosphic reason not to?

**Comment by simeyla** [comment]
> Maybe we should add to https://angular.io/docs/ts/latest/api/core/index/ChangeDetectionStrategy-enum.html that OnPush hands down to all child Components and Directives.

@sod Absolutely yes! I guess I've only ever used `Push` with one or maybe two 'levels' of component and to be honest never even thought about this. Would be very helpful to update it. Also need to be made clear if my 'middle' component marks itself for change detection if that still affects its child in case where the 'middle' component is a `Push` component.
