### ISSUE TITLE
Animations of border-color are not persisted on ios/safari

### ISSUE THREAD

**Issue by jordic** [angular/angular#12481]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Animation of border-color starts but returns to previous state.

**Expected behavior**
Animation should be consistent on the rest of platforms, and apply the end state.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/n2Dw8g?p=preview

**Please tell us about your environment:**
IOS/Safari 10.0 Mobile/14A456 Safari/602.1
- **Angular version:** 2.1.1
- **Browser:** [iOS 10.0 Safari]
  
  
- **Language:** [ TypeScript 2]

**Comment by matsko** [comment]
@vicb @tbosch setting styles as hyphenated styleName values (e.g. `element.style['border-radius']='...'` is problematic. `element.style.setProperty(styleName, value)` is a better option here. Do you think we can update the renderer to do this?

**Comment by matsko** [comment]
It turns out that this is a bug with the `web-animations-polyfill`. I've created an issue that addresses what's going on: https://github.com/web-animations/web-animations-js/issues/92.

The workaround for now is to not use `borderColor` instead of `border-color`:
http://plnkr.co/edit/McrUCL?p=preview

Hopefully those guys fix this soon.

**Comment by matsko** [comment]
@jordic just so you know that this bug is now fully fixed in master. No need to change anything.
