### ISSUE TITLE
Angular 2, adding active class to router link [Best practice]

### ISSUE THREAD

**Issue by radonirinamaminiaina** [angular/angular#12487]
I'm using the InputrouterLinkActive to add active class to some specific url. But I want that specific link is always active if it detect a chunck of word. Let I explain: if my defined route is `/rent/page/:id`, and into my template, I do this:

 `<a [routerLinkActive]="['active']" [routerLink]="['/rent/page/1']" title="">rent</a>`

It works if the url in the adress bar match the defined route, and it adds active class. My main navigation which contains rent link will be active.

But I want more, if my routed has this definition `/rent/:property/:name/:id`, and I tap the url, it doesn't add the active link to my main navigation.

I found the following solution:

   ```
// ...
   this._router.events.subscribe(
        (urlObj) => {
            if(urlObj.url.match(/^(\/rent).*$/)) {
                this.active["rent"] = true;
            }
        }
    )
    // ...
```
Every time I match rent into the current url, I set property rent to the object active and it adds active to my rent navigation. And the template mentionned before, I change it as follow:

`<a [class.active]="active['rent']" [routerLink]="['/rent/page/1']" title="">rent</a>`
And it works, but I'm not sure, if this is a good practice or not.

My question is: **How to routerLinkActive if I want to keep specific link active, even if user changes the page? Is there an alternative way to do this using `[routerLinkActive]` ?**

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
