### ISSUE TITLE
Button's disabled state not reflecting the underlying variable in IE

### ISSUE THREAD

**Issue by ahmadqarshi** [angular/angular#12484]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have written a SignalR client app in Angular 2. Client implements a function `connected` which is invoked from the SignalR Hub. This function simply sets a boolean variable `connected` to `true` when invoked from the Hub. I am using this `connected` variable to control the enable\disable state of a button. It works fine in Firefox and Chrome but in IE button's enable\disable state does not reflect the value of `connected` variable. 

**Expected behavior**
Button's enable\disable state should reflect the value of `connected` variable in all browsers.

**Minimal reproduction of the problem with instructions**
Below is a function in my SignalR Hub class in ASP.NET web api

`public void Connect()
{
    Clients.Caller.connected();
}`

In my Angular2 app I have following service.
**signalr-test.service.ts**

    import { Injectable } from '@angular/core';

    export class SignalrWindow extends Window {
      $: any;
    }

    @Injectable()
    export class SiglalrTestService {

      private hubProxy: any;
      private hubConnection: any;
      private connected = false;

      constructor(private window: SignalrWindow) {
        if (this.window.$ === undefined || this.window.$.hubConnection === undefined) {
          throw new Error("The variable '$' or the .hubConnection() function are not defined...please check the SignalR scripts have been loaded properly");
        }
        this.hubConnection = this.window.$.hubConnection();
        this.hubConnection.url = 'http://localhost:18117/signalr';
        this.hubProxy = this.hubConnection.createHubProxy('MyHub');

        this.hubProxy.on("connected", () => {
          this.connected = true;
          console.log('Connected successfully....');
        });
      }

      start(): void {
        this.hubConnection.start()
          .done(() => {
            this.hubProxy.invoke('Connect');
          })
          .fail((error: any) => {
            throw new Error("Failed to start connection" + error);
          });
      }

      stop(): void {
        this.hubConnection.stop();
        this.connected = false;
      }

      get isConnected(): boolean {return this.connected;}
    }

**app.component.ts**

    import {Component, OnInit} from '@angular/core';
    import { SiglalrTestService } from './signalr-test.service';

    @Component({
        moduleId: module.id,
        selector: 'my-app',
        templateUrl: 'app.component.html'
    })
    export class AppComponent implements OnInit{

      constructor(private signalrTest : SiglalrTestService){}

      ngOnInit(): void {
      }
      startSignalR(){
        this.signalrTest.start();
      }
      stopSignalR(){
        this.signalrTest.stop();
      }
      get connectedToServer() : boolean{ return this.signalrTest.isConnected;  }

    }
and the template file is
**app.component.html**
    `<div>
      <h1>SignalR Test</h1>
      <input type="button" [disabled]="connectedToServer" (click)="startSignalR()" value="Start" >
      <input type="button" [disabled]="!connectedToServer" (click)="stopSignalR()" value="Stop" >
    </div>`

**Please tell us about your environment:**
AngularJS 2.0.1
SignalR 2.2.1
ASP.NET Web API (.NET framework 4.6.1)
Windows 10
IE 11

**Comment by vicb** [comment]
`[attr.disabled]="connectedToServer?true:null"`

**Comment by ahmadqarshi** [comment]
@vicb 
Thanks for suggesting the alternate way to change the state. However, I still believe there is something wrong under the hood.

After replacing `[disabled]="connectedToServer" ` with `[attr.disabled]="connectedToServer?true:null"` I observed that I need to click the Start button twice to make it work. 

I also modified the Hub class and added another function given below:

    public void GreetMe(UserInfo userInfo)
    {
        var message = $"Hello {userInfo.Title} {userInfo.UserName}";
        Clients.Caller.greeting(message);
    }

and on the client side I modified the code like below:

    @Injectable()
    export class SiglalrTestService {

      //Omitted the already posted code in previous post for bravity    
      greetings: string[] = [];

      constructor(private window: SignalrWindow) {
        //Omitted the already posted code in previous post for bravity        
        this.hubProxy.on("greeting", (greetMessage: string) => {
          this.greetings.push(greetMessage)
        });
      }

      //Omitted the already posted code in previous post for bravity        
      getGreeting(): void{
        this.hubProxy.invoke('GreetMe', {'title': 'Mr.', 'userName': 'Ahmad'});
      }

    }

then in **app.component.ts**

    getGreeting(){
      this.signalrTest.getGreeting();
    }

finally in the template I added the below lines:

    <input type="button" [attr.disabled]="!connectedToServer?true:null" (click)="getGreeting()" value="Get Greeting" >
    <br>
    <div *ngFor="let msg of signalrTest.greetings">
      <span>{{msg}}</span>
    </div>

I need to click "Get Greeting" button twice to get the message displayed. However, I don't see this behavior in Firefox or Chrome. Please note that this is a sample application I have created to post the issue here.  However, in my actual application I need to resize the IE window to make the messages appear.

I can post the complete sample Hub and Angular application code if needed.

**Comment by zoechi** [comment]
A complete example is required. It should be a Plunker with minimal amount of code that allows to reproduce the issue.
What is `hubProxy`? It sounds like some code runs outside Angulars zone. Use `zone.run(...)` to ensure the code called from (signalr, hubProxy, ..., ?) runs inside Angulars zone.

To me it looks like a support question that should be asked in one of these channels instead [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
