### ISSUE TITLE
animations' states change but transition doesn't run

### ISSUE THREAD

**Issue by cortopy** [angular/angular#12482]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a component with the following animations 

``` javascript
@Component({
  animations: [
    trigger("questionState", [
      state("active", style({
        opacity: 1,
        "margin-top": "1rem",
        "margin-bottom": "1rem",
        transform: "scale(1, 1)",
        "transform-origin": "top left"
      })),
      state("inactive", style({
        opacity: 0.5,
        "margin-top": 0,
        "margin-bottom": "1rem",
        transform: "scale(.8, .8)",
        "transform-origin": "top left"
      })),
      state("hidden", style({
        opacity: 0,
        transform: "translate3d(0, 100%, 0)"
      })),
      transition("active => inactive", animate("1000ms ease-in")),
      transition("inactive => active", animate("1000ms ease-out")),
    ])],
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: "mc-form-generator",
  styles: [require("./form-generator.component.sass")],
  template: require("./form-generator.component.html"),
  providers: [FormService]
})
```

This configuration works fine and is used in the rendering process correctly. When the state name changes for a question, it is styled accordingly too.

However, only the styles of the final state are applied. That is, no transition animation runs. The styles of each question jump from one state to the next.

This is difficult to debug for me because the styles are applied (no issue with the html properties), but transitions do not run. For example, if a question goes from "inactive" to "active", it immediately receives the styles of "active" without any animation.

**Expected behavior**
It should animate and apply styles to a list of questions depending on whether they are active, inactive or not shown yet. Styles should be applied and transitions should run

**Minimal reproduction of the problem with instructions**
I'm using a redux pattern to store the list of question states. I subscribe to the active question (a number) and when new data is received, amongst other things, the list of states which is referred in the view (`[@questionState]="state.get('stackStates')[i]"`) is updated:

``` javascript
this.state.activeQuestion$
      .subscribe(n => {
        if (n != null) {
           //...
           this.state.set("stackStates", this.setQuestionStates(n));
           //...
        }
      });
```

**What is the motivation / use case for changing the behavior?**
Since each state final styles are applied successfully to each question, I would like to know why the transition effects are not being shown.

**Please tell us about your environment:**
Fedora 24
Webpack 2.1.0-beta.22
- **Angular version:** 2.0.X
  2.1.1
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  Chrome 54
  Firefox 49
- **Language:**
  Typescript 2.0.3
- **Node (for AoT issues):** `node --version` =  
  6.7

**Comment by matsko** [comment]
Let's see if this PR takes care of the issue https://github.com/angular/angular/pull/13334

**Comment by matsko** [comment]
This should be fixed with https://github.com/angular/angular/releases/tag/2.3.1 with the https://github.com/angular/angular/pull/13334 patch. Please try it out and reopen if it is still broken
