### ISSUE TITLE
ngModel prevent rendering of name attribute

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#12491]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Adding **ngModel** to an input element prevents rendering of **name** attribute only **ng-reflect-name** is rendered.

**Expected behavior**
Expecting a rendered **name** attribute using **ngModel**.

**Minimal reproduction of the problem with instructions**
There are four input fields. The first row uses ngModel and the second row not.

http://plnkr.co/edit/noqe3MwMp7WxqWLvJqu9

**What is the motivation / use case for changing the behavior?**
Selecting elements via name attribute is possible f.e. in tests.

**Please tell us about your environment:**

* **Angular version:** 2.0.2 and 2.1.1

* **Browser:** Chrome 53
 
* **Language:** TypeScript 2

**Comment by DzmitryShylovich** [comment]
`[attr.name]="inputName"`
http://plnkr.co/edit/MDc1IVyAULERkHdq1VlI?p=preview

**Comment by CSchulz** [comment]
Is there any documentation about it?

**Comment by gunjankhanwilkar** [comment]
For me [attr.name] serves the purpose thanks @DzmitryShylovich .

**Comment by yankee42** [comment]
Looks like this is the same as https://github.com/angular/angular/issues/18725
