### ISSUE TITLE
Missing / wrong API links

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#12497]
We (angular.io) got some report on missing / wrong API links.

Let's take an example:

[Compiler-class](https://angular.io/docs/ts/latest/api/core/index/Compiler-class.html)

It shows you the class methods and there are links pointing to concrete methods.

So:

``` typescript
class Compiler {
  compileModuleSync(moduleType: Type<T>) : NgModuleFactory<T>
  compileModuleAsync(moduleType: Type<T>) : Promise<NgModuleFactory<T>>
  compileModuleAndAllComponentsSync(moduleType: Type<T>) :       ModuleWithComponentFactories<T>
  compileModuleAndAllComponentsAsync(moduleType: Type<T>) :   Promise<ModuleWithComponentFactories<T>>
  clearCache() : void
  clearCacheFor(type: Type<any>)
}
```

Then you can read something like:

```
compileModuleAndAllComponentsSync(moduleType: Type<T>) : ModuleWithComponentFactories<T>
Same as compileModuleSync but also creates ComponentFactories for all components.
```

The `compileModuleSync` is a link (https://angular.io/docs/ts/latest/api/core/index/compileModuleSync) and I don't remember having API pages with internal links like that. That gives you 404.

On the other hand there is a [ComponentStillLoadingError](https://angular.io/docs/ts/latest/api/core/index/ComponentStillLoadingError) that gives a 404 and it probably should point [here](https://github.com/angular/angular/blob/master/modules/@angular/core/src/linker/compiler.ts#L20-L29)

Same case at [injectable](https://angular.io/docs/ts/latest/api/core/index/Injectable-decorator.html) with a 404 link to [NoAnnotationError](https://angular.io/docs/ts/latest/api/core/index/NoAnnotationError) (Double check the link, it is not having a -foo.html, it is like a wrong generated link but in any case no documentation for `NoAnnotationError` is generated at all). It should point to [here](https://github.com/angular/angular/blob/master/modules/%40angular/core/src/di/reflective_errors.ts#L193-L221).

There are probably more and we will discover them as soon as we update our internal link checker, but there is a bug not sure if here or in our side (io).

**Comment by wardbell** [comment]
Closing because believe this has been corrected. Please reopen w/r/t to new documentation infrastructure if necessary.
