### ISSUE TITLE
issue with period when passing object in child routes

### ISSUE THREAD

**Issue by edenn** [angular/angular#12498]
**I'm submitting a ...**
[X ] bug report 

**Current behavior**
When passing object to child route the initial navigation works, but an error occurs if the page is refreshed.

I.E.

you are component A and you want to navigate to _/route/display_ and pass an object such as {type:'car', price: 100.50} 

by doing:

`this.router.navigate(['/route/display', {type:'car', price:100.50}])`

the component will load fine, the url will be in Matrix URL notation, and you will have something similar to _host.com/route/display/type=car;price=100.50;_ but if you refresh the page it will say invalid request.

I believe the issue has to do when there is a period in the query parameters. If there are no periods in the query parameters the refresh works as expected.

**Expected behavior**
On page refresh the request should work like it did initially. All values should be passed to component.

**Minimal reproduction of the problem with instructions**
You can reproduce this issue by going to the following plunker:

http://plnkr.co/edit/M7dWWkkm7n23CM4k4MVf

here you will notice the initial page has a button that when clicked navigates to different child route and passes object. The first request works, then if you press enter again it will break.

**What is the motivation / use case for changing the behavior?**
It is not working properly

**Please tell us about your environment:**
Operating System: OSX El Capitan
IDE: Visual Code Studio
Package Manager: NPM
- **Angular version:** 2.0.0
- **Browser:** 
  Chrome
- **Language:** 
  ES6
- **Node (for AoT issues):** `node --version` =  
  NODE version = v6.7.0

**Comment by DzmitryShylovich** [comment]
The [second arg](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L519) of `router.navigate` method is not data. It's extra options https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L45

**Comment by edenn** [comment]
@DzmitryShylovich  it works as expected, and there is this:   

> relativeTo?: ActivatedRoute;
> 
>   /**
>   * Sets query parameters to the URL.
>   *
>   * ```
>   * // Navigate to /results?page=1
>   * this.router.navigate(['/results'], { queryParams: { page: 1 } });
>   * ```
>   */

**Comment by DzmitryShylovich** [comment]
@edenn it's not a router issue. Router uses `PathLoacationStrategy` by default. And it required specific server configuration (to return `index.html` for all routes). Plunker is not configured like this this is why u get
> but if you refresh the page it will say invalid request.

If u change location strategy to `HashLoacationStrategy` it works as expected. Here's demo http://plnkr.co/edit/SFVVuWimYQQeutufze4j?p=preview

So I think the issue can be closed

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed
