### ISSUE TITLE
CanRender Feature - Not to render a router link in the first place - Automatically

### ISSUE THREAD

**Issue by un33k** [angular/angular#12499]
**I'm submitting a ...**

```
[ ] bug report => search GitHub for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

A router is mostly self-aware and can also guard itself via one or more helper services.   What if the route never renders itself via `routerLink`.  This is to avoid creating some non-standard, one-off utility or a service.

**Expected behavior**

A router also takes a `canRender: []` option.  If none is provided, it defaults to `always` render, to ensure backward compatibility.

``` typescript
// app-routing.module.ts
import { Routes } from '@angular/router';
const routes: Routes = [
  {
    path: '',
    component: HomeComponent,
  },
  {
    path: 'account/profile',
    component: AccountComponent,
    canActivate: [AuthGuardService],
  },
  {
    path: 'account/profile/employee',
    component: EmployeeAccountComponent,
    canActivate: [AuthGuardService],
    canRender: [SupervisorRenderService],
  },
  {
    path: 'login',
    component: LoginComponent,
    canRender: [UnauthenticatedRenderService],
  },
  {
    path: 'logout',
    component: LogoutComponent,
    canRender: [AuthenticatedRenderService],
  },
  {
    path: '**',
    component: NotfoundComponent,
  }
];
```

**Minimal reproduction of the problem with instructions**
Example for CanRender for `AuthenticatedRenderService`.

``` typescript
//app/auth/render-guard-service
import { Injectable } from '@angular/core';
import { CanRender, Router } from '@angular/router';
import { AuthService } from './auth.service';

@Injectable()
export class AuthenticatedRenderService implements CanRender {

  constructor(private router: Router,
    private authService: AuthService) {
  }

  CanRender(options: any): boolean {
    //...
    return this.authService.isAuthenticated;
  }
}
```

``` html
<!-- app/login/login.component.html -->
<a class="" [routerLink]="[/login]">Login</a>  <!-- Render if unauthenticated -->
<a class="" [routerLink]="[/logout]">Logout</a> <!-- Render if authenticated -->
<!-- all logic in one place, less logic in tempate, cleaner template -->
```

**What is the motivation / use case for changing the behavior?**

It would be great to put all the route validation/information/title/data in one place. Not showing a sensitive link `sometimes` may be as important as guarding it. (security via obscurity).  It also can help with allowing most of the logic to live in one place.  This may result in less code as well as helping with DRY. 

**Please tell us about your environment:**

macOS Sierra, Node v6.6.0, Angular-CLI beta.18, @Angular=2.1.0, @Router=3.1.0

**Comment by un33k** [comment]
Adding a [link](https://github.com/un33k/django-menuware) to a similar app as a **reference**.  Not Javascript, but it may be beneficial to have a look at it as a reference.

**Comment by laco0416** [comment]
I think it can be solved by a directive on links. you can make your ngIf-like directives. 

```
<a class="" *renderIfUnauth [routerLink]="[/login]">Login</a>
<a class="" *renderIfAuth [routerLink]="[/logout]">Logout</a>
```

**Comment by DzmitryShylovich** [comment]
@un33k what do you think about https://github.com/angular/angular/issues/14515 ? will it help to resolve your issue?

**Comment by un33k** [comment]
@DzmitryShylovich #14515 the same or a very similar feature requests.

**Comment by itrethan** [comment]
LGTM

**Comment by itrethan** [comment]
LGTM, Approval
