### ISSUE TITLE
Problems after upgrade to new Angular 2.1.1 and Router 3.1.1

### ISSUE THREAD

**Issue by prsolucoes** [angular/angular#12492]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When i start my project with npm start, im getting after upgrade the following error:
<img width="1255" alt="screenshot 2016-10-24 14 09 01" src="https://cloud.githubusercontent.com/assets/395096/19654752/6c00317e-99f8-11e6-83a4-4d5b39f79af5.png">

**Please tell us about your environment:**
My repository:
https://github.com/prsolucoes/angular2-webpack2-starter

* **Angular version:** 2.1.1

* **Browser:** all
 
* **Language:** TypeScript 2.0.3 ES5

* **Node (for AoT issues):** v6.6.0

**Comment by DzmitryShylovich** [comment]
See https://github.com/qdouble/angular-webpack2-starter#aot--donts

**Comment by vicb** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Quramy** [comment]
@prsolucoes  I had the same issue, but it's not angular's bug. The webpack.config.prod.js is wrong. To fix it, you can remove `exclude: /node_modules/` from the webpack configuration:

```javascript
			{
				loaders: ['awesome-typescript-loader?tsconfig=tsconfig.json', 'angular2-template-loader'],
				test: /\.ts$/,
				// exclude: /node_modules/
			},
```

With angular-cli 2.1.1 or later, typescript loader **should not have**  `exclude: /node_modules/` because `ngc` outputs some .ngfactroy.ts of directives under `node_modules/@angular/src/`.

**Comment by prsolucoes** [comment]
Hi man,

Thanks. It is working now.

The hot replace module is not working too. The contents are not replaced and the running version still the same after change, after reload page. See the error:

![problem-webpack-error](https://cloud.githubusercontent.com/assets/395096/19689176/3eb84194-9aab-11e6-9ade-178c97de2c43.png)


Ty.
