### ISSUE TITLE
angular Router(V3)

### ISSUE THREAD

**Issue by nssidhu** [angular/angular#12494]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The router outlet has to be a child element for it to be loaded on click of hyperlink

**Expected behavior**

 Be able to trigger the load of content into any of the router-outlet by name

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Angular version:** 2.0.X
  
  
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
- **Node (for AoT issues):** `node --version` =

**Comment by vsavkin** [comment]
Your mental model of what router links do is not right. They do not load components into outlets--they transition the application into a new state (read more here https://vsavkin.com/angular-2-router-d9e30599f9ea#.uf1f5x557).

Clicking on a link can affect other outlets, not just the child ones (e.g., absolute links).
