### ISSUE TITLE
Create Emitter (as replacement for EventEmitter)

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1250]
Current `@EventEmitter` has fallowing issues:

* It pollutes the constructor.
* It makes it difficult to unit test the code because it requires a lot of mock code.

## Replacement

Use inline `Emitter` class which reverses the dependency. 

```
class Emitter {
  listener; // we only support one
  constructor() {
    this.listener = null;
  }
  emit(data) {
    return if (this.listener) this.listener(data);
  }
}
```

Here is what the code would look like.

```
@Component({
  selector: 'my-component',
  events: ['open', 'close']
})
@View(...)
class MyComponent {
  open:Emitter;
  close:Emitter;

  constructor() {
    this.open = new Emitter();
    this.close = new Emitter();
  }
}
```

previous code:

```
@Component({
  selector: 'my-component'
  // events not listed here.
})
@View(...)
class MyComponent {
  open:Function;
  close:Function;

  constructor(@EventEmitter('open') open:Function, @EventEmitter('close') close:Function) {
    this.open = open;
    this.close = close;
  }
}
```

## Rx and Streams

Angular should be able to consume not only `Emitter` but also `Rx` and `Streams`. (We prefer `Emitter` because it is much more light weight and synchronous)

**Comment by PascalPrecht** [comment]
@mhevery How is the relation ship between the emitter and the emitter name set up then?

Having this code:

```js
  constructor(@EventEmitter('open') open:Function, @EventEmitter('close') close:Function) {
    this.open = open;
    this.close = close;
  }
```

We know, that `open:Function` belongs to `@EventEmitter('open')` because it is it's annotation. But in your proposed code:
```js
@Component({
  selector: 'my-component',
  events: ['open', 'close']
})
@View(...)
class MyComponent {
  open:Emitter;
  close:Emitter;

  constructor() {
    this.open = new Emitter();
    this.close = new Emitter();
  }
}
```
How do we for which event `this.open` and `this.close` is an emitter? There's no direct relation, or would this be a name to name mapping?

**Comment by tbosch** [comment]
Could we have the same for @PropertySetter?

Eg
@Decorator(
setters: ['value']
)
Class MyDecirator {
Constructor() { this.value = new PropertySetter(); }
}

Setting properties via PropertySetter and emitting events is very similar!

**Comment by pkozlowski-opensource** [comment]
@tbosch @mhevery I must say that I'm as puzzled as @PascalPrecht ... 2 questions:
* doesn't this change mess up with testing? Isn't it like "hard-coding" a dependency in a constructor?
* how a given EventEmiter / PropertySetter "knows" which event to emit / property to set?

**Comment by mhevery** [comment]
@pkozlowski-opensource this should make testing easier, since the you don't have to inject anything and default implementations (`new Emitter()`) will allow easy listening in tests, but will be ignored if not needed.

```
class MyComponent {
  play:Emitter = new Emitter();
  doSomething() { play.emit(); }
}

it('should test', () => {
  var c = new MyComponent();
  c.play.listener = createSpy();
  c.doSomething();
  expect(c.play.listener).toBeCalledWith([]); 
}); 
```

**Comment by mhevery** [comment]
@tbosch I like the idea will update the issue.

**Comment by PascalPrecht** [comment]
@mhevery the "default" `Emitter` implementation is that something that the framework would provide?

**Comment by mhevery** [comment]
@PascalPrecht yes framework would provide it.

**Comment by vsavkin** [comment]
Closed via https://github.com/angular/angular/commit/233cb0f96a04b40863b592bd78ec1a7de6854834
