### ISSUE TITLE
how to check broken image url and set to default if broken slimier in angluar 1?

### ISSUE THREAD

**Issue by nikvarma** [angular/angular#12503]

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by nikvarma** [comment]
no i am not sure it's a issue or bug

In anglure 1 thir is option to check if the img url broken

thanks

**Comment by zoechi** [comment]
http://stackoverflow.com/questions/36429903/angular-2-check-if-image-url-is-valid-or-broken/36430121#36430121

See also [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource :)
