### ISSUE TITLE
register ngModel inputs to form in custom components

### ISSUE THREAD

**Issue by westor21** [angular/angular#12504]
**I'm submitting a ...**  (check one with "x")
[x ] bug report => search github for a similar issue or PR before submitting
[x] feature request

I intentionally create a duplicate from my issue https://github.com/angular/angular/issues/12357 , because that one was closed and I didn't get any answer to urgend questions.

The problem is, that an input with ngControl in a custom component in a template driven form is not registered to the form.
As Kara adviced, we have to implement ControlValueAccessor interface in the custom component.

May be I misundeerstood the concepts, but I have arguments against Karas statement, or at least questions, which are unclear to me:
- We don't talk only about a custom form control. We talk about a custom component in general, which is placed inside a form. Such a component may have nothing to do by itself with model and data, it may only perform structuring tasks or group more then one input elements for a special purpose. Why would I need a controlValueAccessor interface for such a component, if the the component itself is not dealing with data? And how could a controlValueAccessor manage more then one input element in the component?
- I thought, the proposal was, to bring full ng1 functionality to forms, when using template driven forms and ngModel. Exiting ng1 applications do not need something like a controlValueAccessor interface - a migration seems to be more complicated as it should be in this point.

**Comment by westor21** [comment]
Let me complement: In angular1 we can build a directive (aka a component) without creating a new scope. In that case the model binding can be done direct with the directives parent, because they share scope. If we build components with isolated scope, we have to forward the bindings, if we need them in the component. The form is validated for all controls, independent where they are.

The concept of "shared scope" in ng1 may be no longer available in ng2. But I expected to have the possibility to forward arbitrary bindings to the component, using them in inputs there and find them handled by the parent form.

**Comment by rusev** [comment]
I also would like to hear someone from Angular team on this. 

If you have a "dummy" component with form elements inside it, think of it as a reusable block, the form elements should be registered without need of implementing ControlValueAccessor.

Example - https://plnkr.co/edit/De4PgikYkgkIe30AUJds?p=preview

Another strange thing is that dynamically loaded template in the custom component will be able to register in the form. Above example modified a bit - https://plnkr.co/edit/WhRudMADPB0ksoLXktCa?p=preview

**Comment by rusev** [comment]
Any comment on this?!

**Comment by zoechi** [comment]
This sounds like a support question and should be asked in one of the channels mentioned in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by westor21** [comment]
I see this as a critical issue in handling forms like angular.js. And I wonder if there are not many other people out there, trying to migrate to ng2, use forms and ngModel.

**Comment by kara** [comment]
Again, it's unlikely that we will remove the encapsulation that separates parent forms from form directives in child components. This is necessary to prevent things like third-party components registering unrelated controls onto parent forms and to support important features like aggregate ControlValueAccessors (e.g. an address component that contains many controls inside it, but presents as a single form control value at the top level). 

If you want to create a sub-form component that is not a ControlValueAccessor, this is possible simply by providing the existing NgForm as a ControlContainer (a one-liner). See https://plnkr.co/edit/8V3gtXsSg2d3ohUQGlyE?p=preview.  

In the future, though, please keep support questions to StackOverflow and Gitter, etc.
