### ISSUE TITLE
Throw an error message with a package doesn't use Angular as a peer dep

### ISSUE THREAD

**Issue by vicb** [angular/angular#12501]
/ref https://github.com/angular/angular/issues/11889

When a npm package uses (by mistake) its own version of angular instead of using the angular as a peer dependency,
the AOT reflector is not able to identify the decorator and will result in an error.

For example

```
StaticSymbol {
  filePath: '/Users/berchet/Code/angular2-compiler-bug/node_modules/mwl-example-ng2-module/node_modules/@angular/core/src/metadata/ng_module.d.ts',
  name: 'NgModule',
  members: undefined }
```

See how `NgModule` is located inside the npm package (`mwl-example-ng2-module`)

We should throw when angular symbols are **not located** at the top level

**Comment by JoostK** [comment]
This is obsolete as of Ivy, given that compilation of libraries occurs separate of the application compilation.
