### ISSUE TITLE
Can't run AoT without "file or directory does not exist" error.

### ISSUE THREAD

**Issue by NightkingCH** [angular/angular#12505]
**I'm submitting a ...**  (check one with "x")

```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Running ngc -p tsconfig-build.json with a minimal example create with the aot cookbook outputs following error:

Error: ENOENT: no such file or directory, open 'C:\Projects\aot_test\aot\components\calc\calc.metadata.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at MetadataWriterHost.writeMetadata (C:\Projects\aot_test\node_modules\@angular\tsc-wrapped\src\compiler_host.js:114:22)
    at MetadataWriterHost.writeFile (C:\Projects\aot_test\node_modules\@angular\tsc-wrapped\src\compiler_host.js:103:19)
    at Object.writeFile (C:\Projects\aot_test\node_modules\typescript\lib\typescript.js:45203:132)
    at Object.writeFile (C:\Projects\aot_test\node_modules\typescript\lib\typescript.js:7502:14)
    at writeEmittedFiles (C:\Projects\aot_test\node_modules\typescript\lib\typescript.js:37150:20)
    at doEmit (C:\Projects\aot_test\node_modules\typescript\lib\typescript.js:37010:17)
    at emitFile (C:\Projects\aot_test\node_modules\typescript\lib\typescript.js:43948:17)
Compilation failed

This occurs when typescript.js calls "host.writeFile" on line 7502. It provides my component, then the "compiler_host.ts" checks on line 94 if it's a definition file, skips writing my transpiled js-component and starts to write the metadata file on line 116. Then on line 86 it tries to write without any path checks, which is bad in my opinion, the file. Which doesn't exists because it was skipped within the writeFile-Function on line 91.

**Expected behavior**
1. Check if the directory exists without any assumption, and create it if it doesn`t.
2. Remove if-statement within the file "compiler_host.ts". The issue "8412" from typescript is already solved and merged.
3. The "compiler_host.ts" swallows the output from a .js file. I expect that this is written regardless which choices are made from the ngc-compiler.

If I remove the described if-block and and move the line 96, this.delegate.writeFile, down and call it before the current line 116 "writeMetadata[...]" it works like a charm. It also looks for me like a race condition. The definition file is written later than the js-file, but the metadata file is written before.

**Minimal reproduction of the problem with instructions**
I just followed the instruction of the aot-cookbook "https://angular.io/docs/ts/latest/cookbook/aot-compiler.html". In my case I want to write an external angular2 component libary. It also seems only to occur if I want to write the declaration files and the aot-metadata.json-files.

_MINIMAL DEMO_
Just download the plunkr-zip here: http://plnkr.co/edit/8pmJ7LNChtRfbYQzvq4V. And do following:
1. unzip it
2. run "npm install"
3. run "npm run aot"

_STEPS TO REPRODUCE_
If you want to reproduce it by hand:
1. create a new directory.
2. Add a package.json with minimal config for angular2-aot (typescript + angular2-packages)
3. Add a tsconfig with following flags
4. "declaration": true
5. "angularCompilerOptions: { skipMetadataEmit: false }
6. run "npm install"
7. create the smallest module structure with at least 1 component as shown in the plunkr-demo.
8. run ngc.

_SIDE NOTES_
I also reproduced this behavior on another machine! So this bug shouldn't be related to my machine or any file system rights. I also ran ngc as local admin on my system.

**What is the motivation / use case for changing the behavior?**
1. AoT doesn't work out of the box when writing an external module library. 
2. It's just bad coding to assume that the path already exists. And "because performance" should not be the answer. Typescript already provides functions to ensure that a specific directory exists.

**Please tell us about your environment:**
- Windows 10 Enterprise
- Visual Studio Code 1.6.1
- NodeJS 6.9.1 LTS
- NPM 3.10.9
- TypeScript 2.0.3
- Angular: 2.2.0-beta.0
- **Browser:**
  Not browser related
- **Language:**
  Typescript
- **Node (for AoT issues):** `node --version` = 6.9.1

**Comment by NightkingCH** [comment]
Cause nobody seems to care about this issue i gonna close it.

**Comment by arangelp** [comment]
I am having the same problem

**Comment by matthewdenobrega** [comment]
I am having the same issue, but with extraction for translations. The @NightkingCH fix works for me as well. Can we re-open this please?

**Comment by Tuupertunut** [comment]
An open issue about this can be found here: #13359
