### ISSUE TITLE
Router support to split url segments/parameters with slash, hyphen or period

### ISSUE THREAD

**Issue by viperguynaz** [angular/angular#12502]
**I'm submitting a ...

```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Router only supports url segments/parameters with a slash "/"

**Expected behavior**
To mimic server-side behavior, for example when using Universal and the Express Router, I'd like to be able to also split segments/parameters with a hyphen "-" or a period ".".  

**Minimal reproduction of the problem with instructions**
This would allow for routes like:

```
/vehicle/:region/:make/:model
/vehicle-:region-:make-:model
/vehicle.:region.:make.:model
```

**What is the motivation / use case for changing the behavior?**
Add additional options to match existing SEO routes and create new combinations.

**Comment by robwormald** [comment]
This should already be possible - you can provide your own implementation of the URL serializer - its job is to transform a URL string into a URL Tree strucutre, which is what the router works with.

See https://github.com/angular/angular/blob/master/modules/%40angular/router/src/url_tree.ts#L225-L275 for a starting point - this is the default implementation.
