### ISSUE TITLE
Allow embedding a link to original source files into the generated messages

### ISSUE THREAD

**Issue by mprobst** [angular/angular#12513]
We should generate something like:

``` xml
<msg id="..." meaning="..."><source>path/to/file.ts:123</source>This is a message</msg>
```

`extractor.ts` should take a callback to generated the exact file path from e.g. a `ts.SourceFile` object or similar, so users can adjust the path to their particular repository format.

**Comment by gnoack** [comment]
You can also specify line number ranges like `path/to/file:123,125`.  (yes, comma-separated)
Line numbers are one-based (as in grep).

**Comment by vicb** [comment]
@gnoack could you please confirm that we can list multiple `<source>`s ?

**Comment by gnoack** [comment]
Yes, multiple `<source>` tags are supported.

**Comment by ocombe** [comment]
Isn't this a duplicate of #14190 ?

**Comment by gnoack** [comment]
Almost.  The other bug forgets to mention that we also would like line numbers for each message.

**Comment by ocombe** [comment]
Ok, the feature request contains line numbers anyway: https://github.com/angular/angular/pull/14705

**Comment by gnoack** [comment]
It's almost the same, yes.  The line number format that we need is ":123,125" where 123 is the first and 125 the last line where the message appears, 1-based indexing.  I'm sorry to notice this so late, and I hope that our XMB-reading tools are somewhat compatible in that respect. :-/

**Comment by ocombe** [comment]
This is the format that we're adding (":123,125").

**Comment by gnoack** [comment]
Awesome, thanks!

**Comment by ocombe** [comment]
This has been fixed and merged in master
