### ISSUE TITLE
Binding required inside component implementing ControlValueAccessor, Validator

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular#12516]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I've been trying to follow the pattern laid out by @kara in #10251 and #9281 but have run into problems with a fairly specific but probably not uncommon scenario where I have a reusable form control that implements both `ControlValueAccessor` and `Validator`, binds a validation directive to one of the control values, and is wired up in a parent form via `NgModel`. In this scenario, as soon as I type in the field whose value is bound to the validator, I get a `Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.` error. 

**Expected behavior**

Seems like it should just work.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/qr5cMofR9VvxYaF4nJCz?p=preview

Just type in the first field and check the console.

**Please tell us about your environment:**
- **Angular version:** 2.1.0
- **Browser:** all
- **Language:** TypeScript 2.0.2

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
