### ISSUE TITLE
Directive inputs set to empty string when matching attribute present without a value

### ISSUE THREAD

**Issue by gary-b** [angular/angular#12524]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If you have an attribute directive which also has an optional input aliased to its name, eg ngModel has @Input('ngModel') model in its definition, then when users decide to use the directive without setting the input, eg `<select name="myname" ngModel>`, the value of the input is set to an empty string. 

**Expected behavior**

Since other inputs stay at undefined until explicitly set, when the user doesn't provide a value for an attribute on the template, one time string initialization should be skipped. Im not sure if there would need to be a distinction made between skipping it for directive inputs and other scenarios with which i'm not familiar.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/SDOPJpeV4YAXXqwObOoh?p=preview

**What is the motivation / use case for changing the behavior?**
I think the expected behavior is more intuitive, interested in your thoughts.

**Please tell us about your environment:**
Windows 10, chrome.

* **Angular version:** 2.0.X
2.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested on chrome.

**Comment by vicb** [comment]
IMO both options are debatable but at this point changing would be a breaking change.
