### ISSUE TITLE
Adding children to a `forChild` route breaks redirects for the root

### ISSUE THREAD

**Issue by chrisnicola** [angular/angular#12529]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If you have a set of nested routers where there is a root router that defers to another module with a `forChild` declared route, the root router will not be able to resolve that child's route if it has children and is not lazy loaded. This can be fixed by adding the route redundantly to the root router module with the same component referenced. See the examples below.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

You can see in this Plunker where I've edited the Hero's route just slightly to add a redirecting child route. By doing so the app is no longer able to resolve the `/heros` root redirect.

http://plnkr.co/edit/e3bcyyDbXiAuBnUrBj2s?p=preview

```
  // app/heros/heroes-routing.module.ts
  { path: 'heroes',  component: HeroListComponent, children: [{ path: 'test', redirectTo: '' }] },
```

This can be corrected again by adding a redundant route to the root router as you can see here:

http://plnkr.co/edit/SPdNWcrplTSwob6j16wn?p=preview

```
  // app/app-routing.module.ts 
  { path: 'heroes',  component: HeroListComponent },
```

**What is the motivation / use case for changing the behavior?**

I am assuming this behaviour is unintentional, if it is not it is incredibly confusing as to why the redundant root route is required here.
- **Angular version:** 2.1.1 (Router 3.1.1)
- **Language:** [ TypeScript 2.0.3 ]

**Comment by chrisnicola** [comment]
Ok so I finally figured out what is happening here. In the list of children paths you also need to provide a "root" i.e., `''` route for the sub-routes or it no longer works. This design and behaviour does seem a bit confusing however. At the very least a clear error message here would help immensely. A note on this in the docs might be a good short term solution.

**Comment by vsavkin** [comment]
Thank you for submitting this issue. 

This is an issue talking about what you asking for: https://github.com/angular/angular/issues/12133
