### ISSUE TITLE
NgModel on select[multiple] doesn't detect when options in bound array change

### ISSUE THREAD

**Issue by gary-b** [angular/angular#12521]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ngModel on select[multiple] expects an array to store selected values. When you switch out this array for a different one, the UI is updated to reflect the values within the new array. If you add or remove values in the currently bound array however, the UI does not update.

I believe this is down to the use of ngOnChanges within ngModel to detect changes - it looks at reference equality of the array only. Looking at the documentation perhaps ngDoCheck needs implemented. The docs warn of a performance impact though...

**Expected behavior**

UI updates to reflect the model.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/HsAhSBYxSpJ8HCr3Xjqg?p=preview

**What is the motivation / use case for changing the behavior?**
Broken

**Please tell us about your environment:**
Windows 10
- **Angular version:** 2.0.X
  v2.1.1
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  I've repro'd it on Chrome and Edge.

**Comment by DzmitryShylovich** [comment]
> I believe this is down to the use of ngOnChanges within ngModel to detect changes - it looks at reference equality of the array only. Looking at the documentation perhaps ngDoCheck needs implemented. The docs warn of a performance impact though

@gary-b yeah, you are right. This situation is described in the [docs](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#onchanges):
> Angular only calls the hook when the value of the input property changes. The value of the hero property is the reference to the hero object. Angular doesn't care that the hero's own name property changed. The hero object reference didn't change so, from Angular's perspective, there is no change to report!

Do we want to support array mutation here?

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
