### ISSUE TITLE
Testing: DOM created with innerHTML cannot be found during testing with query()

### ISSUE THREAD

**Issue by intellix** [angular/angular#12520]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

- Create a component that alters it's innerHTML inside ngOnInit.
- Fetching that element during testing with: `fixture.debugElement.query(By.css(`#injected`))` gives NULL

**Expected behavior**

I should be able to query/retrieve that DOM element during testing when it's injected with innerHTML

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/kllZ1JXYLuFbenQtoCOc?p=preview

**What is the motivation / use case for changing the behavior?**

I'm wrapping a third-party library into a component. That third-party library accepts a DOM element target to replace: `<div id="thirdparty-replace-me"></div>`
Once the library has been instantiated once, you no longer have an element to replace if you want to run it again should you need to (router param change).
I need to be able to set innerHTML using `ngOnChanges` so there's an element for the third-party to replace again.

**Please tell us about your environment:**

**OS:** OSX

* **Angular version:** 2.0.X

**OS:** 2.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Browser:** Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by vicb** [comment]
Nodes created with `innerHTML` are not known by angular.
