### ISSUE TITLE
Support bindings to SVG element sub-element attributes

### ISSUE THREAD

**Issue by cstad** [angular/angular#1252]
Please see plunk: http://plnkr.co/edit/z5ELuZILKr9wMwlm4zcq

Description: Shown here in this plunk is a model with a string field named 'path' that is bound to the path element 'd' attribute. The field is set in the constructor and changed with a timeout; neither the initial nor the changed model value is reflected in the view path element.

Expected Results: The bound attribute to be updated like any other HTML element attribute
Actual Results: The attribute never seems to update thus the view is never updated to reflect the model's changed value.

Additional testing: Calling a method to get the model value, instead of accessing the field directly, yields the same results; though console logging in the getter reveals that the getter method is indeed called as expected.

**Comment by pkozlowski-opensource** [comment]
@cstad by default Angular2 binds to element's _properties_ and not attributes. Looking at the [SVGPathElement docs](https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement#Properties) there is no `d` property but there is `d` attribute: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path#Specific_attributes

If you want to bind to element's attribute, you need to prefix its name with `attr.`, ex.: `<path [attr.d]="getPath()"></path>`.

Here is a working plunk: http://plnkr.co/edit/Wr9PAtuSUVaNUdxgTCtz?p=preview

Closing as it works as expected.

**Comment by cstad** [comment]
RTFM... I am sorry for wasting timie

**Comment by pkozlowski-opensource** [comment]
@cstad I don't think there is any manual for this yet, so no worries :-)
