### ISSUE TITLE
Touch event is not propagated to parent with more than one level nesting

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#12526]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`control.markAsTouched()` works only for one nesting level. You can see it in the console log, there is only _onTouched TestComponent_.

Touch callback methods are registered for all levels, but they aren't called.

I have already looked into the source, but I don't know what is wrong, it looks good.
https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L250

**Expected behavior**
`control.markAsTouched()` should not have any limitation or should log it.

**Minimal reproduction of the problem with instructions**
Two level: http://plnkr.co/edit/aiAXyBy5TcicRt7wLzPo?p=preview
Three level: http://plnkr.co/edit/5603FRn2OrsZJwleXpOv?p=preview

**What is the motivation / use case for changing the behavior?**
For better encapsulation of components it is required to get a working touched event propagation.

**Please tell us about your environment:**

- **Angular version:** 2.1.1
  
  
- **Browser:** Chrome 53, Firefox 47
- **Language:** TypeScript 2

**Comment by CSchulz** [comment]
Could be related to #12560

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
