### ISSUE TITLE
Update angular2 on npm with deprecation warnings

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#12532]
This is about the legacy `angular2` package on npm on not `@angular/core` packages.

https://www.npmjs.com/package/angular2 currently shows up prominently in the search results for "npm angular2" which makes new people confused.

In the past we deprecated the package using `npm deprecate` but that deprecation warning doesn't show up on the npmjs.com site.

We should do the following:
- [ ] update the readme.md that shows up on npmjs.com with deprecation warning and point people to our quickstart doc. (remove all the other text)
- [ ] ensure that all versions of `angular2` package are deprecated with a warning message pointing people to our quickstart

To update the readme we'll need to cut a new release of the `angular2` package. The easiest way to do that is to npm install `angular2`, change the readme.md, and then deploy the package as beta.18.

Afterwards reissue the `npm deprecate` command on the `angular2` package.

**Comment by vsavkin** [comment]
I pushed a new version of angular2 with an updated readme. I also deprecated the package.
