### ISSUE TITLE
Error: Uncaught (in promise)

### ISSUE THREAD

**Issue by 2n2n** [angular/angular#12535]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
I've tried to test angular 2 for a week for now.

**Current behavior**
The catalog app is not working because of the error 
`` zone.js:390Error: Uncaught (in promise): Error: Error in ./CatalogComponent class CatalogComponent - inline template:3:32 caused by: Cannot read property 'name' of undefined(…)
``

**Expected behavior**
I'm trying to get data from services. from my catalog.component module.

**Minimal reproduction of the problem with instructions**
***Component calling the Service***
```
import { Component, OnInit, Input } from '@angular/core';
import { StockService } from '../stock.service';
import { Item } from '../Item';
@Component({
  selector: 'shop-catalog',
  templateUrl: './catalog.component.html',
  styleUrls: ['./catalog.component.css'],
  providers: [StockService]
})

export class CatalogComponent implements OnInit {
  stocks: Item[];
  constructor(private stockService : StockService) { }
  
  getStocks(): void {
    this.stockService.getStocks().then(items => { this.stocks = items; });
  }
  
  ngOnInit(): void {
    this.getStocks();
  }
  
}
```

***The Service***
```
import { Injectable } from '@angular/core';
import { ITEMS } from './mock-stocks.ts';
import { Item } from './Item';

@Injectable()
export class StockService {

  constructor() { }
  
  getStocks(): Promise<Item[]> {
      return Promise.resolve(ITEMS);
  }

}
```
Item.ts
```
export class Item {
   name: string;
   description: string;
   imgUrl: string;
}
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
currently developing with c9.io
angular-cli: 1.0.0-beta.18
node: 4.5.0
os: linux x64

* **Angular version:** 2.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v4.5.0

**Comment by ericmartinezr** [comment]
>[x] support request => **Please do not submit support request here**, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

You'll get more chances of a good answer if you follow and read that link

**Comment by 2n2n** [comment]
yes sorry.. I didnt really know how to do it. and it's my first time posting here. I'd like to delete this post.
