### ISSUE TITLE
[improvement]About ViewContainerRef.createComponent

### ISSUE THREAD

**Issue by keyiis** [angular/angular#12537]
If i want dynamic insert some compoent in other compoent then i must add a mrak in host compont's templete,ex:
`<templete #insertcomponent></templete>`  or `<div #insertcomponent></div>`
if i am not add this,it will be created as sibling.
**So,i want say "It's very not smart!"**
ex:`hostViewContainerRef.createComponent(componentFactory)`
hostViewContainerRef already tell angular2 who is host view, the normal thinking is insert into the hostViewContainerRef or can add a method in ViewContainerRef like 'insertComponent'.

**Comment by keyiis** [comment]
@vicb Why close?can give me a reason?

**Comment by intellix** [comment]
@keyiis you removed all of the issue template. When you create an issue it begins with this message:

`IF YOU DON'T FILL OUT THE FOLLOWING INFORMATION WE MIGHT CLOSE YOUR ISSUE WITHOUT INVESTIGATING`
