### ISSUE TITLE
Animation callback throw change detection error after property change

### ISSUE THREAD

**Issue by k3nsei** [angular/angular#12546]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
NG2 animation callback throw change detection error if something changes

**Expected behavior**
NG2 animation callback can change properties without an error

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/TL4xfVCss92xaIMRd1WA?p=preview

**What is the motivation / use case for changing the behavior?**
Wants to set `animated` class durring animation

**Please tell us about your environment:**
Windows 10 x64, InteliJ, node/NPM, angular-cli server
- **Angular version:** 2.1.1
- **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
- **Language:** TypeScript
- **Node (for AoT issues):** 6.3.0

**Comment by souldreamer** [comment]
The fix is pretty easy, just set the changes to happen in the next event loop (for the @trigger.start) or run in Angular's zone (for the @trigger.end). As your function combines the two, a possible solution would be:

```typescript
  onAnimation(event: AnimationTransitionEvent){
    setTimeout(() =>
      this.zone.run(() => {
        switch (event.phaseName) {
          case 'start':
            this.animated = true;
            break;
          case 'done':
            this.animated = false;
            break;
        }
      }
    ), 0);
  }
```

See it working [here](http://plnkr.co/edit/jHGfouXpqWYEZM0f2MrT?p=preview)

**Comment by k3nsei** [comment]
@souldreamer Yeah I know that. But it isn't a issue fix but workaround.

**Comment by souldreamer** [comment]
Okay, experimented a bit more, and found out that you need `setTimeout` only for the `@trigger.start` and `zone.run()` only for the `@trigger.done`.

On the one hand, it makes sense that the `@trigger.start` is called during change detection, as it's a direct response to a change, but I really can't understand why `@trigger.done` is run outside of Angular.

**Comment by ericmartinezr** [comment]
See this related issue https://github.com/angular/angular/issues/11881
