### ISSUE TITLE
How to get the bootstraped component instance with the new NgModule pattern

### ISSUE THREAD

**Issue by epieddy** [angular/angular#12547]
Hi,

In the previous versions of angular2, I was able to do something like this to allow the parent website to obtain the root component instance and call method on it.

```
bootstrap(AppComponent, [
    disableDeprecatedForms(),
    provideForms(),
  ]).then(function (ref: ComponentRef<AppComponent>) {

    if (window.callbackReady) {
      window.callbackReady(ref.instance);
    }
  })
```

Now, with the new NgModule pattern, I get a NgModuleRef with the module instance instead of a ComponentRef with the component instance.

Can you tell me how I can expose the root component instance to the parent website now ?

**Comment by DzmitryShylovich** [comment]
Hi, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by epieddy** [comment]
My bad. Sorry
