### ISSUE TITLE
NumberValueAccessor not exported from @angular/forms

### ISSUE THREAD

**Issue by wulfsberg** [angular/angular#12544]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Having a `<input type="number">` field in your template causes AoT compilation to fail with a

```
40% building modules 251/311 modules 60 active ...es/@angular/core/src/linker/errors.jsresolve '../../../node_modules/@angular/forms/src/directives/number_value_accessor.ngfactory' in '/Volumes/LB1731.2/course/examples/src/app/form/person-form-1'
  using description file: /Volumes/LB1731.2/course/examples/package.json (relative path: ./src/app/form/person-form-1)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Volumes/LB1731.2/course/examples/package.json (relative path: ./src/app/form/person-form-1)
    using description file: /Volumes/LB1731.2/course/examples/package.json (relative path: ./src/node_modules/@angular/forms/src/directives/number_value_accessor.ngfactory)
      as directory
        /Volumes/LB1731.2/course/examples/src/node_modules/@angular/forms/src/directives/number_value_accessor.ngfactory doesn't exist
      no extension
```

The issue is described and discussed in angular/angular-cli#2845

**Expected behavior**

AoT should handle the `type="number"` attribute.

**Minimal reproduction of the problem with instructions**

See angular/angular-cli#2845

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Angular version:** 2.1.1
  
  
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
  
  N/A (AoT)
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  TypeScript 2.0.3
- **Node (for AoT issues):** `node --version` =  
  v6.0.9

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/12428, is that the same case (seems to be a fix already for it)?

**Comment by DzmitryShylovich** [comment]
yeah, try forms-builds module

**Comment by wulfsberg** [comment]
@ericmartinezr According to https://github.com/angular/angular-cli/issues/2845#issuecomment-256336660, no, it is not the same issue, but I must admit I am at the edge of my understanding here.

**Comment by DzmitryShylovich** [comment]
Sorry I'm dumb but how is this not https://github.com/angular/angular/issues/12428 issue?

**Comment by clydin** [comment]
While the latest build solves the problem, there is still the issue of inconsistent exports in the forms module.  Most of the value accessor are exported but not all.  From a cursory examination, NumberValueAccessor and RangeValueAccessor appear to be the outliers.
See: https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/forms.ts

**Comment by DzmitryShylovich** [comment]
@clydin I agree but that's the different issue :)

**Comment by clydin** [comment]
Different but the same, exporting it should have also fixed the original issue.

**Comment by wulfsberg** [comment]
I'm a little unclear on the consequences here.
Publishing what you want people to use seems like a reasonable thing for modules to do, but it sounds like that'll essentially be redundant after the fix for #12428?

**Comment by DzmitryShylovich** [comment]
is this still an issue?

**Comment by clydin** [comment]
The accessors are still not exported consistently.

**Comment by MrWolfZ** [comment]
+1 The `NumberValueAccessor` is still not export by the `@angular/forms` module. I am currently writing a library that tries to re-use the existing `ControlValueAccessor`s by inheriting them and declaring them as new directives. That is not possible for the `NumberValueAccessor` currently which forces me to copy its source code.

**Comment by Airblader** [comment]
I'm basically running into the same issue as @MrWolfZ in that I would like to use the existing ControlValueAccessor infrastructure, but I can't add `ngModel` to those elements because it interferes with my library.

@MrWolfZ I see that you ended up re-implementing *all* accessors as adapters. Is there a particular reason why you didn't do something like this?

```
@Directive({
  selector: "[myDirective]:not([ngModel])",
  providers: […],
})
export class MyDirectiveControlValueAccessor extends DefaultValueAccessor {}
```

for all accessors to reuse the implementation?

**Comment by MrWolfZ** [comment]
@Airblader I don't really remember, but I believe there were some things in the default implementations that I didn't like. Also I wanted to make the dependency of my library on @angular/forms as small as possible.

**Comment by Airblader** [comment]
@MrWolfZ Thanks. Yeah, I quickly tried this approach and it isn't pretty anyway, so I too decided to implement my own accessors for now. Looking at your code I think another reason you did it is because you have this "native ID" stuff going on, i.e., your accessors are actually a bit different anyway.

**Comment by kara** [comment]
`NumberValueAccessor` is exported now in master.  Should be out with the next minor/major release.
