### ISSUE TITLE
bug(EventEmitter): emitted events don't bubble up the dom properly

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1254]
http://plnkr.co/edit/CeaQYgE8XTwmP3uRX97S?p=preview

As you can see, I tried several different syntaxes, even a timeout, to get my App component to catch events from the child component. Nothing worked.

The events just aren't bubbling.

**Comment by ajoslin** [comment]
Having to use addEventListener and CustomEvent for now.

**Comment by mhevery** [comment]
This is by design. Can you tell me more about why you would like to do this?

**Comment by mhevery** [comment]
ping

**Comment by urish** [comment]
@mhevery I also find this behavior really confusing. Any chance this can be revisited?

I spent an hour trying to understand why my clicks where not intercepted by the event handler, just to figure out that click events don't bubble unless I explicitly tell them to...

Thanks!

**Comment by PascalPrecht** [comment]
@urish this will be better once https://github.com/angular/angular/pull/3864 is landed

**Comment by urish** [comment]
@PascalPrecht great, thanks!
