### ISSUE TITLE
Proposal: optional namespaces for inputs bindings

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#12557]
**I'm submitting a ...**
- [ ] bug report => search github for a similar issue or PR before submitting
- [x] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
## Problem

Technically, it's totally possible that there are multiple directives on the same element that bind to the same property (name). Currently there's no way to explicitly tell Angular which directive property we want to bind to. 

_This is especially problematic if the consumer doesn't have control over the directive (e.g. 3rd party directives)_

Example:

```
@Directive({
  selector: '[one]'
})
class One {
  @Input() foo;
}

@Directive({
  selector: '[two]'
})
class Two {
  @Input() foo;
}
```

Those two directives can be used like this:

```
<ANY one two [foo]="someExpr"></ANY>
```

By looking at the template we don't know which directive we're actually binding to + we can't be explicit about it either.
### Current behaviour

The code above binds `someExpr` to both directive `foo` properties.
## Proposals

I discussed this with @cburgdorf and we came up with the following **possible** solutions, both with their up and downsides.
### 1. Directive-Attribute/Property order defines binding receivers

The directive-attribute and property order on the host element defines which expression is bound to which directive prop. Example:

```
<div one [foo]="boundToOne" two [foo]="boundToTwo"></div>
```

Same for

```
<div one two [foo]="boundToOne" [foo]="boundToTwo"></div>
```

^ This works, because Angular has its own HTML parser and can actually identify the order of attributes (which browsers can’t guarantee AFAIK)
#### Upsides
- Easy to grok
- Kinda intuitive
#### Downsides
- Gets hairy the more directives are applied to one host element (Chances might be rather low, that this happens with many directives tho)
### 2. Introduce optional namespace for property bindings

Another option would be to introduce some explicit namespaces (maybe by taking advantage of `exportAs`?)

Assuming:

```
@Directive({
  selector: '[one]',
  exportAs: 'one'
})
class One {
  @Input() foo;
}

@Directive({
  selector: '[two]',
  exportAs: 'two'
})
class Two {
  @Input() foo;
}
```

^ Notice how both directives use `exportAs`. That name could be used by the consumer as well:

```
<div one [one.foo]="boundToOne" two [two.foo]="boundToTwo"></div>
```

This would work in any order:

```
<div [one.foo]="…" two one [two.foo]="…">
```

Another possible syntax would be

```
<div [one#foo]="…">
```

Canonical version:

```
<div bind-one-foo="…"
```

This works for events too.
#### Possible problems with this approach

One problem it would introduce though (if we’d rely on `exportAs`), the consumer also doesn’t have control over `exportAs` values of 3rd party directives either. So if we have:

```
@Directive({
  selector: '[one]',
  exportAs: 'one'
})
export class One {…}

@Directive({
  selector: '[two]',
  exportAs: 'one'
})
export class Two {…}
```

^ Notice how both directives `exportAs: 'one'`

This would kind of result in the same problem, as both directives are exported as `one`. However, OTOH this exact same problem exists already when getting directive instance references in the template:

```
<div one two #foo="one"></div>
```

^ here, we can’t say if `foo` is `One` or `Two`. In fact, Angular throws in that case

```
zone.js:344Unhandled Promise rejection: Template parse errors:
Reference "#foo" is defined several times ("<div one two [ERROR ->]#foo="one"></div>
"):
```
### Final thought

So then, I’d say this boils down to always prefixing the `exportAs` value, then this might work. E.g. forms directives do the exactly the same (`ngModel`, `ngForm`, ...)

**Comment by SanderElias** [comment]
@PascalPrecht, We should make sure, that in this case, all directives are 100% sure of getting a copy/clone/reference. That is a default behaviour that really makes sense. And I actually expect/hope that is what currently happens.
And actually, that is what I would expect if I put 2 directives on 1 element.

It's the same as in std HTML. for example, if you have an input element, the attributes: min, max, required, ... all work on the value property of that element. You compose them to achieve different behaviour on the element you attach those directives too.

When those directives conflict, that is actually a developers error, and not something angular can or should fix. I understand that bad naming is a real problem. However, that has nothing to do with angular. 
If you are a 3rth party provider you should be aware of this issue, and comply to what the 'real DOM' is doing.. (all access the same property).  If you really need an exclusive access to a property, make sure to prefix it.

The use case for directive @inputs are mostly twofold:
   1.  You use directives to add/modify behaviours to an existing property. This is like the min, max, require, etc.. all influence value property on an input tag
   2. You just need an exclusive property. Usually to put in extra options for a directive. think: `<someElement  mySearch [mySeachExecption]='some expression'>...`

I really can't come up with a scenario that warrants for a shared common/generic property name, but then demands exclusivity.
I'm open to suggestions, though! Perhaps there is some use case that I'm currently now aware off.

**Comment by laco0416** [comment]
how can we distinguish it and `@Inpit('one.foo')`?

**Comment by alxhub** [comment]
We have no plans to make major changes to Angular template syntax at this time.
