### ISSUE TITLE
Unicode mangling caused by AoT compilation?

### ISSUE THREAD

**Issue by coreyog** [angular/angular#12552]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have the word Pokédex on my site. It's appearing on the site as PokÃ©dex regardless of I use the unicode character é or convert it to an escape sequence of &#233;. The characters look correct when viewed in text editors. And in the view-source of the html.

![image](https://cloud.githubusercontent.com/assets/2836207/19740215/158b89a4-9b7b-11e6-9e87-52f08445a48b.png)

**Expected behavior**
I should see Pokédex and not PokÃ©dex

**Minimal reproduction of the problem with instructions**
It seems to work fine in plunker or when using the JIT platform-browser-dynamic. Ahead of Time compilation of a view featuring either of the above strings seem to be the cause.

If I view the component.ngfactory.js that's generated, it converts &#233; to the é accurately. It seems that the renderer mangles it between then and actually putting it on the screen.

**What is the motivation / use case for changing the behavior?**
Unicode support is a strong feature in today's web.

**Please tell us about your environment:**
Dev environment is Win10 x64, Visual Studio Code, npm, ngc, rollup, live-server. It all works there.
Environment where I notice the issue is hosted by godaddy (currently https://materialpokedex.com/beta/, subject to change)

* **Angular version:** 2.1.1

* **Browser:** All
 
* **Language:** Typescript 2.0.2 all the way through to the javascript that's generated after AOT compilation show the &#233; or é correctly. Doesn't matter which I use, the browser chews it up.

* **Node (for AoT issues):** `node --version` =   6.7.0

**Comment by coreyog** [comment]
It seems to only garble text that's hardcoded in the view.

![renderer](https://cloud.githubusercontent.com/assets/2836207/19741201/042b760e-9b7d-11e6-8c3e-7c4830367c97.png)

The upper left garbled Pokedex is hard coded in the view. The lower right text was fetched from an ajax request and bound from the controller.

**Comment by vicb** [comment]
Please:
- Create a minimal repro so that we can investigate,
- send us the ngfactory generated for this component by ngc.

This will help us investigate and fix the issue

**Comment by coreyog** [comment]
I hate to be the person to not fully research the problem before submitting a bug but that's exactly what happened here. GoDaddy wasn't serving my js files as UTF-8. A simple .htaccess rule fixed this.

Your library and compiler are working exactly as it should. Thank you for all the hard work you do.

**Comment by vicb** [comment]
I love not to always be the person closing issues :)
