### ISSUE TITLE
ngc complains about an optional number parameter on a component constructor

### ISSUE THREAD

**Issue by masimakopoulos** [angular/angular#12551]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have this constructor of a component:
```
  constructor(private _nav:NavController,
              ...other dependencies
              @Optional() private _sampleTime:number = 500) {
```
I am using the last parameter to pass in a number (mostly for testing purposes). The app works fine and tests pass, but ngc gives an error that 
```
Property 'number' does not exist on type 'typeof
            "/path/pages/contact-list/contact-list.page"'.
[21:29:42]  ngc failed
```

**Expected behavior**
compile passes or a more meaningful error message is given

**Minimal reproduction of the problem with instructions**
have an injectable constructor that takes an optional parameter of any type

**What is the motivation / use case for changing the behavior?**
We should be able to pass optional parameters to constructors that the DI will ignore.

**Please tell us about your environment:**
Ionic Framework Version: 2.0.0-rc.1
Ionic App Scripts Version: 0.0.37
OS: Mac OS X Sierra
Node Version: v6.9.1

* **Angular version:** 2.0.X
"@angular/core": "2.0.0",
"@angular/compiler": "2.0.0",
"@angular/compiler-cli": "0.6.2",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Command line compiling
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.3

* **Node (for AoT issues):** `node --version` =   
Node Version: v6.9.1

**Comment by DzmitryShylovich** [comment]
Hi, can u pls provide a minimal repository with reproduction?

**Comment by pkozlowski-opensource** [comment]
I guess that sth like this will fail under AoT: http://plnkr.co/edit/KEUwIB1xfr9HLkAjrPDW

If so I agree that we might have a better error message here but this is _super_ wired usage pattern... Why would you do this? If you want DI to ignore this param why not have a const in a class? Would you mind on elaborating?

In any case I agree that we should at least have a descriptive err message here.

**Comment by thelgevold** [comment]
I have not tried `@Optional` with AoT, but it will let you pass optional parameters to functions in general. 
This scenario might be a workaround: https://github.com/angular/in-memory-web-api/blob/master/src/in-memory-web-api.module.ts

The idea is that you pass in the value somehow. In this example it's an optional input to a forRoot method. Then a provider is registered to use the value you passed (or didn't pass)... This creates another layer, but might work here...

**Comment by vicb** [comment]
IIRC native types are not supported by the DI and there is already an issue opened for that so I will close this one.

The solution is: `@Optional() @Inject(token) private _sampleTime:number = 500`

the `token` in `@Inject(token)` is usually an instance of `OpaqueToken`

**Comment by masimakopoulos** [comment]
@DzmitryShylovich @pkozlowski-opensource the reason for this optional parameter is primarily for testability purposes. It is a class configuration value that on normal bootstrapping gets the default value and on testing it gets another value (imaging a 2 sec delay getting down to 2ms delay). 
This is the same as passing a config object with production vs testing values, but for a single value. I can workaround the issue by actually passing an object rather than a primitive, but it adds a bit of overhead and I do not see why this shouldn't work (which it does on run time, but fails on compilation).

Preferably I would want the DI to completely ignore this param, so wouldn't want to specify it at all (other than having the default value specified on the providers declaration which might be nicer).
