### ISSUE TITLE
Error: No provider for e!  - No error description

### ISSUE THREAD

**Issue by mariohmol** [angular/angular#12554]
<img width="747" alt="errorcompleto" src="https://cloud.githubusercontent.com/assets/5495763/19749437/aef8a06c-9bc7-11e6-868c-53115628509a.png">
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

I'm doing a ionic2 app and it works good in desktop. But when to try to run in a mobile (4.x version), i get this error in the console

```
e {_nativeError: Error: No provider for e!
    at e.Error (native)
    at e [as constructor] (file:///android_asset/w…, keys: Array[1], injectors: Array[1]}
```

System information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.4.0
ios-sim version: 3.1.1
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by ericmartinezr** [comment]
Run your app without minifying and you'll see the full error message

**Comment by mariohmol** [comment]
Tryied to find how to make it.. can u say how to disable that in a command line? (ionic2)

**Comment by vicb** [comment]
> (ionic2)

Then you ask ionic for support
