### ISSUE TITLE
INTERNATIONALIZATION (I18N) plural rules

### ISSUE THREAD

**Issue by probadb** [angular/angular#12563]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The INTERNATIONALIZATION (I18N) does not support plural forms.

**Expected behavior**
The INTERNATIONALIZATION (I18N) should support natively plural form just like GNU gettext.

**Minimal reproduction of the problem with instructions**
Use a sentence like "There are %d items in your selection".
In english you would just have 2 plural forms:
- "There is %d item in your selection" if %d = 1;
- "There are %d items in your selection" if %d <> 1;

Some other language will have 3 sentences with a different formula.
Russian example would be 
- numbers ending in 1
- numbers ending in 2,3,4
- numbers ending in 5,6,7,8,9,0

and so on just check rules here: http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html#sl

**What is the motivation / use case for changing the behavior?**
You cannot know in what language you are going to translate, and you cannot handle all the formulas in code, you should always rely on the translation engine. Just look on GNU gettext way to handle it (eg. `"Plural-Forms: nplurals=2; plural=n!=1;\n"`) Something is mentioned here: http://docs.oasis-open.org/xliff/v1.2/xliff-profile-po/xliff-profile-po-1.2-cd02.html#s.detailed_mapping

**Please tell us about your environment:**
Ubuntu 16.04

* **Angular version:** 2.0.X
2.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 54
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0

* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by vicb** [comment]
It does using the ICU format `{var, plural, =1 {...} other {...} }`

However those strings are only extracted to xmb for now. The xliff implementation does not support that yet.

If you have any idea / pointer to how those should be serialized in xliff, that could help.

**Comment by probadb** [comment]
I gave an idea how to serialize it in the link provided: http://docs.oasis-open.org/xliff/v1.2/xliff-profile-po/xliff-profile-po-1.2-cd02.html#s.detailed_mapping
it does map the formula and the array of sentences.
