### ISSUE TITLE
ngModel doesn't seem to work with IE9

### ISSUE THREAD

**Issue by thomasmerieux** [angular/angular#12568]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Current behavior**
ngModel doesn't work with IE9.

**Minimal reproduction of the problem with instructions**
* Clone the [quickstart repository](https://github.com/angular/quickstart) and follow the instructions
* Add the FormsModule in the app.module.ts file :
```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';

import { AppComponent }  from './app.component';

@NgModule({
  imports: [ BrowserModule, FormsModule ],
  declarations: [ AppComponent ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

* Modify the app.component.ts file like this :
```
import { Component } from '@angular/core';

@Component({
    selector: 'my-app',
    template: '<h1>My First Angular App</h1><input type="text" [(ngModel)]="foo"/>{{foo}}'
})
export class AppComponent { }
```

* Run the app on IE9 and it displays the following error :
![unnamed](https://cloud.githubusercontent.com/assets/4394701/19777288/cad0b5da-9c77-11e6-91cd-fac3dac6734d.png)

**Environment:**
IE9 on a Windows 7 Virtual Machine (from www.modern.ie). The same behaviour occurs with IE11 using the IE9 compatibility mode.

* **Angular version:** 2.1.1

* **Browser:** IE9

* **Language:** Typescript

* **Node (for AoT issues):** `node --version` = v6.9.1

**Comment by DzmitryShylovich** [comment]
Pls provide a working reproduction in plnkr.

**Comment by pkozlowski-opensource** [comment]
You are, most probably, missing `classList` polyfill. Make sure to check https://angular.io/docs/ts/latest/guide/browser-support.html and open an issue in https://github.com/angular/quickstart so the mentioned polyffil is added to the setup.

**Comment by thomasmerieux** [comment]
The classList polyfill was indeed missing. It works fine when I add it.

Thanks for the help
