### ISSUE TITLE
How to redirect to an external URL from route without using component?

### ISSUE THREAD

**Issue by yarikmlb** [angular/angular#12562]
I would like to create external redirect, but to make all routes consistent I think it would be nice to do under Router States.

my routes:

```
const appRoutes: Routes = [
  {path: 'login', component: null, resolve: {loginPage: LoginService}},
  {path: '', component: HomeComponent,
  canActivate: [AuthGuardService],
  children: [
    {path: '', redirectTo: 'first', pathMatch: 'full'},
    {path: 'first', component: FirstComponent},
    {path: 'second', component: SecondComponent}
  ]}
];
```
```
import { Injectable } from '@angular/core';
import {Resolve} from '@angular/router';

@Injectable()
export class LoginService implements Resolve<any> {

  resolve(){
    window.location.href = 'https://login.com';
    return false;
  }
}
```

[http://stackoverflow.com/questions/40150393/how-to-redirect-to-an-external-url-from-angular2-route-without-using-component](url)

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
