### ISSUE TITLE
Nesting ngModel with custom components implementing ControlValueAccessor doesn't register parent

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#12560]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Nested components doesn't register _parent and does not build tree correctly.

**Expected behavior**
Nested components have _parent set.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/8Tl0dhojWTaaOjNtNwix?p=preview

**What is the motivation / use case for changing the behavior?**
I want to use validators like required and similar on native elements like input and the parent component (control) should propagate the touched state to its child (see the validate method)

Another way would be iterating over the children but it isn't possible no children method.

Perhaps it is a misunderstanding of the forms concept. I am missing a detailed example how to ngModel over multiple levels over components correctly (if it is possible).

It could be realated to #12516 and #12504.

**Please tell us about your environment:**

- **Angular version:** 2.1.1
  
  
- **Browser:** Chrome 53, Firefox 47
- **Language:** TypeScript 2

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
