### ISSUE TITLE
List attribute setters in the @Component annotation

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1256]
Allow Directives to write properties on their current element. Currently this is handled with `@ProportySetter('name')` but will be move to this style for easier test ability/consistency.

Currently:
```javascript
@Component({
  selector: 'my-component'
})
class MyComponent {
  constructor(
      @PropertySetter('class.my-class)' myClass,
      @PropertySetter('hidden')
  ) {
    myClass.set(true);
  }
}
```

Proposed:
```javascript
@Component({
  selector: 'my-component',
  setters: ['hidden', 'classMyClass: class.my-class']
})
class MyComponent {
  myClass:Emitter;
  hidden:Emitter

  constructor() {
    myClass = new Emitter();
    hidden = new Emitter();
  }
}
```

* [ ] setter name uses the same path as the property setter. So we intercept `attr.foo`, 'class.bar`, and so on. (But it does not set values on other Directives/Components)  
* [ ] `Emitter` can be replaced with `Observable`s for now.

**Comment by vsavkin** [comment]
Merged via https://github.com/angular/angular/commit/8ccafb0524e3ac4c51af34ef88e0fe27482336a6
