### ISSUE TITLE
Need a tool to migrate the code by the 3.0.0 release

### ISSUE THREAD

**Issue by vicb** [angular/angular#12579]
Most of the breaking changes in future major releases will be announced in advance and users will still be able to use the former (deprecated) API giving them time to adapt their code before the next major release when the deprecated APIs will be removed.

However in some cases this is not possible and we should provide a tool to migrate user apps for those.

See most of the PR in https://github.com/angular/angular/pulls?q=is%3Aopen+is%3Apr+label%3A%22flag%3A+breaking+change%22

For example narrowing down return types (from any to something, by adding generics, ...)

**Comment by alexeagle** [comment]
We do have a tool, tslint -f applyFixes.
However, I doubt that it is expressive enough to accomplish all the needed
refactorings, and also we want to package it differently (ng update 3.0.1
or something).

I recommend that we start by merging the breaking changes into google3,
using a tslint refactoring, then we just need to package the tslint command
for external users when we cut the first ng3 release.

**Comment by DzmitryShylovich** [comment]
@vicb there's no breaking changes in v4 so I think it's not relevant anymore
