### ISSUE TITLE
Named router-outlets not being populated

### ISSUE THREAD

**Issue by conorlauer** [angular/angular#12577]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Given

```
// app.component.ts template
<router-outlet name='one'></router-outlet>
<router-outlet name='two'></router-outlet>

// Route definition
const route: Route[] = [
  {path:':moduleId', children:[
     { path: '', component: DynamicModule, outlet: 'one'},
     { path: ':viewId', component: DynamicView, outlet: 'two'}
  ]
]

// RouterLinks
<a routerLink='["test0"]' >Test One</a>
<a routerLink='["test1","test2"]' >Test Two</a>

```

Throws "Cannot match any routes. URL Segment: 'test0'

**Expected behavior**

What would be ideal would be that clicking the "Test One" anchor tag would populate RouterOutletMap["one"], and clicking "Test Two" anchor tag would populate the RouterOutletMap["two"].

**Minimal reproduction of the problem with instructions**

See current behavior

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Angular version:** 2.0.X
  
  
  
  Angular 2.1.0
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
  
  Windows all
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  TypeScript 
- **Node (for AoT issues):** `node --version` =  
  6.2.1

**Comment by vsavkin** [comment]
You can do it as follows:

```
<a routerLink='['test0', {outlets: {one: []}]' >Test One</a>
<a routerLink='['test1', {outlets: {two: ['test2']}]' >Test Two</a>
```

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
