### ISSUE TITLE
i18n does not translate input box placeholders in Angular2 Material

### ISSUE THREAD

**Issue by mLaird** [angular/angular#12576]
**I'm submitting a ...**  (check one with "x")
```
[x, I think ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am using Angular2.1.2 and @angular/material2.0.0-alpha.9-3, which is their latest release, as best I can tell.  The documented i18n code and process works great, thank you, except the placeholders for the MD input boxes do not translate.  The original en-US text shows instead.

**Expected behavior**

Since Angular2 MD input boxes have no label, the placeholder should translate.

**Minimal reproduction of the problem with instructions**
Its not clear whether the issue is in Angular2, Angular Material2, or the i18n docs for Angular2.  
An example of the input box code is:

```html
    <md-input id="country" name="country" class="required" aria-labelledby="country"
    i18n="select country placeholder" placeholder="Country" type="text">
    </md-input>
```

The ng-xi18n process does not create an entry for some input elements like this, and in some cases, it seems to create an 'empty' trans-unit.  Here is 
an example:

```xml
      <trans-unit id="b17eed820e54bfa923df55605c57a4e4bb470be0" datatype="html">
        <source>
    </source>
        <target/>
```

Text in p elements in between input boxes translates correctly.

**What is the motivation / use case for changing the behavior?**

Since Angular2 MD input boxes have no label, the placeholder should translate.

**Please tell us about your environment:**

Windows10, Angular2.1.2, Angular2 material.alpha.9-3, Atom, Node & npm, 
* **Angular version:** 2.1.2
yes

* **Browser:** [all | Chrome current | Firefox current |]

 
* **Language:** [ | TypeScript 2.0.6 | ]

* **Node (for AoT issues):** `node --version` =

**Comment by mLaird** [comment]
The input box code was truncated when submitted, so here it is without tag marks >
    md-input id="country" name="country" class="required" aria-labelledby="country"
    i18n="select country placeholder" placeholder="Country" type="text"
    /md-input

**Comment by vicb** [comment]
I fixed that in your original message (see source to learn the syntax)

What you are looking for is:

```html
<md-input id="country" name="country" class="required" aria-labelledby="country"
    i18n-placeholder="select country placeholder" placeholder="Country" type="text">
</md-input>
```

What you meant with your markup is to translate the content of `<md-input>`

**Comment by mLaird** [comment]
@vicb Thanks, I added i18n-placeholder to the md-input boxes.  But things are puzzling.  Did something in i18n change in 2.1.2?   
The prior code, without i18n-placeholder, used to translate the available items, but no longer translates anything, and gives console errors that i18n-placeholders are missing.  Ok, I get that, but it used to translate available items.

The new code, with i18n-placeholders, gives related errors about the ending of the es-MS.xlf file.

The error message says MdButton,  but my code near those lines is md-radio-group  and 4 md-radio-button elements,  not md-button.
The last few lines of the file end with </trans-unit> </body> </file> </xliff> and pair with similar starting tags.  Here's the console errors:

zone.js:388 Unhandled Promise rejection: xtb parse errors:
Unexpected closing tag "body" ("  <note priority="1" from="description">status-On hold, future use</note>
      </trans-unit>
    [ERROR ->]</body>
  </file>
</xliff>
"): MdButton@679:4
Unexpected closing tag "file" ("
      </trans-unit>
    </body>
  [ERROR ->]</file>
</xliff>
"): MdButton@680:2
Unexpected closing tag "xliff" ("
    </body>
  </file>
[ERROR ->]</xliff>
"): MdButton@681:0 ; Zone: <root> ; Task: Promise.then ; Value: Error: xtb parse errors:(…) Error: xtb parse errors:

I can provide more info, or post this as a new bug. Let me know.

**Comment by vicb** [comment]
Please express your issues more clearly.

**Comment by mLaird** [comment]
Thanks, Vic ,
As best I can tell from the Console errors (posted above), the translation process encounters some error at lines 679, 680, 681.  These are the only Console errors. Here are lines starting at 675 at the end of the messages.es-MX.xlf file:

      <trans-unit id="b2ad3ab02d1a01f832f8dd46cca66e65e0b68717" datatype="html">
        <source>On hold, future use</source>
        <target>En espera, el uso futuro</target>
        <note priority="1" from="description">status-On hold, future use</note>
      </trans-unit>
    </body>
    </file>
    </xliff> 

The HTML for this translation is towards the end of the following chunk at the end of the html file:

      <p id="postStatus" class="bold" aria-labelledby="postStatus"
    i18n="section heading for post status ">STATUS OF POST</p>
      <md-radio-group>
        <md-radio-button i18n="status-Initially, being prepared" value="beingPrepared" checked="checked">Initially, being prepared</md-radio-button>
        <md-radio-button i18n="status-Emailed, not activated" value="notActivated">Emailed, not activated</md-radio-button>
        <md-radio-button i18n="status-Actively displaying" value="active">Actively displaying</md-radio-button>
        <md-radio-button i18n="status-On hold, future use" value="onHold">On hold, future use</md-radio-button>
      </md-radio-group>
      </form>
      </div>

The form page displays when  document.locale = 'en-US';  but not for 'es-MX'.  All I get in the translated loading is the Console errors above. All my i18n code is copied out of the Cookbook tutorial.  Note that the Console error says MdButton@679,  but I only use md-radio-button in this section of code.

I know this is not a support forum, but the es-MX translation loaded last Friday. It just did not translate the placeholders. Now with i18n-placeholder in the md-inputs, the page does not load. I get errors, as best I can tell, when i18n processes the end tags in the xlf file.

**Comment by mLaird** [comment]
I noticed the Console error text above is not complete.  Here is all the error text:

    zone.js:388 Unhandled Promise rejection: xtb parse errors:
    Unexpected closing tag "body" ("  <note priority="1" from="description">status-On hold, future use</note>
      </trans-unit>
    [ERROR ->]</body>
    </file>
    </xliff>
    "): MdButton@679:4
    Unexpected closing tag "file" ("
      </trans-unit>
    </body>
    [ERROR ->]</file>
    </xliff>
    "): MdButton@680:2
    Unexpected closing tag "xliff" ("
    </body>
    </file>
    [ERROR ->]</xliff>
    "): MdButton@681:0 ; Zone: <root> ; Task: Promise.then ; Value: Error: xtb parse errors:(…) Error: xtb parse errors:

**Comment by mLaird** [comment]
@vicb 
I removed all the i18n-placeholder references from my HTML, and got the same error as above about closing tags.  I haven't figured out the problem yet, but it is not an i18n-placeholder problem.

**Comment by vicb** [comment]
The error seems to indicate that `</body>` is unexpected where it is. Either there is some unclosed els or no opening `<body>`

**Comment by mLaird** [comment]
@vicb  I re-worked the entire thing, and found a trans-unit close
   
         </trans-unit>  
 that was mistakenly copied over with a target translation. Hence, double targets and no trans-unit close.  The error was around line 100.  I was mis-led by the Console errors talking about errors in lines 679 - 681, which are the ending 4 lines.  Everything works when the trans-units are well formed.  Thanks. This is very cool.
