### ISSUE TITLE
call a method in ngfor

### ISSUE THREAD

**Issue by IoanStoianov** [angular/angular#12572]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**
Angular2
Hello guys,

I try to call a method inside ngfor

*ngFor=" let day of Days()" >{{day}}

////////
```

Days(){
	console.log("check");
        return [1,2,3,4,5,6,7];
}

```

It executes the template once, but the problem is that it logs in console 3 times "check".
Why it calls this function 3 times?

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
