### ISSUE TITLE
[2.2.0-beta.0] AoT ngUpgrade breaks angular style guide

### ISSUE THREAD

**Issue by guojenman** [angular/angular#12571]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Current code to upgrade a ng1 component in an AoT fashion breaks with angular2 style guide

```
@Directive({selector: 'ng1'})
class Ng1ComponentFacade extends UpgradeComponent {
  constructor(elementRef: ElementRef, injector: Injector) {
    super('ng1', elementRef, injector);
  }
}
```
https://angular.io/styleguide#!#directives

Selector should be attributes for directives. Unfortunately, component decorators require templates, so I don't know what the right answer is.

**Expected behavior**

Should be able to upgrade a ng1 component which can be AoT compiled AND follow angular2 style guide.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

If this doesn't follow the angular2 style guide, then we can't properly lint our code. We'll need to disable this part of linting and risk variation in code.

**Please tell us about your environment:**

* **Angular version:** 2.2.0-beta.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
Please open an issue on angular/angular.io if you feel this is important. Thanks.
