### ISSUE TITLE
dgeni output: angle-brackets in constructor declaration should be escaped in doc output

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#1257]
`annotations/Template` shows this constructor syntax in the docs output: 
![image](https://cloud.githubusercontent.com/assets/2286589/7029835/1aae2cd2-dd15-11e4-9fd6-aa7fc8db4f85.png)

However this is truncated. The full constructor declaration is actually:

```
constructor({
      url,
      inline,
      directives,
      formatters,
      source,
      locale,
      device
    }: {
      url: string,
      inline: string,
      directives: List<Type>,
      formatters: List<Type>,
      source: List<Template>,
      locale: string,
      device: string
    })
  {
    this.url = url;
    this.inline = inline;
    this.directives = directives;
    this.formatters = formatters;
    this.source = source;
    this.locale = locale;
    this.device = device;
  }
```

**Comment by petebacondarwin** [comment]
Have you checked if it just the styling that is clipping it or is it actually missing the content?

**Comment by naomiblack** [comment]
Ah! The content is in the source but the angle brackets for <Type> in the constructor declaration aren't escaped as they are output to the docs, so my browser thinks they're HTML. Changing the title to reflect the actual issue.
