### ISSUE TITLE
Custom Value Accessor in @angular/forms

### ISSUE THREAD

**Issue by mariolenis** [angular/angular#12581]
Hope it helps...

```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Implementing ControlValueAccessor function 

```
writeValue(value: any) {
    this._model = value;
}
```

"value" is not a cloned object which by default makes the accessor behave like 2-way binding using 1-way binding syntax like this:  
`<custom-as name="myFieldName" [ngModel]="myModelVar"></custom-as>`

**Plunker:**
[http://plnkr.co/edit/ydUDzkHt7r1cjWkGGUhy?p=preview](http://plnkr.co/edit/ydUDzkHt7r1cjWkGGUhy?p=preview)

**Expected behavior**
`writeValue(obj: any): void;` "obj" should be a cloned object.

**What is the motivation / use case for changing the behavior?**
I was trying to initialize the component but found that any change at form value produces a change on model

**Please tell us about your environment:**
Windows 10, Netbeans, NodeJS
- **Angular version:** 2.1.1
  
  
- **Browser:** [all]
- **Language:** TypeScript 2.0

**Comment by ClementVidal** [comment]
I'd be glad to know if this is a bug or the expected behavior ... 
+1

**Comment by michaelchiche** [comment]
You are using ngModel which is part of FormsModule in your template.
But you are also implementing a control value accessor, which is part of ReactiveFormsModule.

Then, the writeValue function is only called when the control value is changed. So the writeValue function is in fact never called.

**Comment by mariolenis** [comment]
@michaelchiche, not sure about the mix, I think control value accessor are made to be used with any of the two models and definetly writeValue is called twice, 1st time when the control is registered and 2nd time when it receives de [ngModel] initial value, check the plunker again, I added a console.log witness.

**Comment by mattdistefano** [comment]
IMO this is the correct and expected behavior. Any object binding in angular will pass a reference rather than a clone.

**Comment by mariolenis** [comment]
@mattdistefano, I though the same at first... then I realized the syntax is [ngModel] which means is 1-way binding.

**Comment by mattdistefano** [comment]
Right, but that's how one-way bindings work with objects - you're passing a reference to the object. See the note toward the end of https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#onchanges

**Comment by mariolenis** [comment]
@mattdistefano, true, but if so, at the plunker code why the whole object "user" doesn't change? I understand your point, it's just that we are discussing the forms module behavior using ControlValueAccesors, not how javascript makes reference for objects.

**Comment by zoechi** [comment]
I don't think you can split how JS treats object references and how `ngModel` works. If you want a clone of the object, make one. Why should `ControlValueAccessor` or `ngModel` do that. What if someone doen't want that behavior?

**Comment by mariolenis** [comment]
It wouldn't make sense use `[ngModel]` or `[(ngModel)]`, in both cases will work as 2 way binding.

**Comment by zoechi** [comment]
With `[ngModel]` you do **not** get 2-way binding. `[ngModel]="xxx"` just assigns the value of `xxx` to the control. If you change a property of that object and you see the change on other places that reference the same object is not related to binding at all.

**Comment by mariolenis** [comment]
@zoechi check out the plunker, specifically at `app.html` line 3, using `[ngModel]="user.name"`; at run time the `user.name` at model doesn't change, it only changes on form properties value, which is an expected behavior.

[http://plnkr.co/edit/ydUDzkHt7r1cjWkGGUhy?p=preview](http://plnkr.co/edit/ydUDzkHt7r1cjWkGGUhy?p=preview)

The thing i'm trying to point is that using the same syntax for the value accessor `<custom-accesor name="data" [ngModel]="user.data"></custom-accesor>`, it changes the model value. From my point of view CVA are available to create custom inputs, so it should behave as the standard inputs... just saying.

**Comment by zoechi** [comment]
Then create a property `data` assign `user.data` to it and use `[ngModel]="data"` instead and you'll get the expected behavior.

**Comment by tytskyi** [comment]
hi @mariolenis `writeValue` is called too often. Which means that on every CD check it will create copy of object which may be too expensive with big number of bindings. What i suggest you is to take value as is an then - work on modified copy. 

Pseudo code:

```
public model: User;

private _model: User;

public  writeValue(value: User): void {
    this._model = value;
}

public onChangeUserName(name: string): void {
    if (this.model) {
        this.model = _.cloneDeep(this._model);
    }

    this.model.name = name;
    // ...
}

public onChangeUserAddress(address: string): void {
    if (this.model) {
        this.model = _.cloneDeep(this._model);
    }

    this.model.address = address;
    // ...
}
```

And then you pass clone of your clone to `change` callback, like `this.onChangeCallback({...this.model});`

So that you input and output are unreferenced.

What do you think, @zoechi?

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
