### ISSUE TITLE
Lazy loading modules with the Router's live example and path repeatedly when refresh page.

### ISSUE THREAD

**Issue by sdhhqb** [angular/angular#12588]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I follow ADVANCED DOCUMENTATION [Lazy loading modules with the Router](https://angular.io/docs/ts/latest/guide/ngmodule.html)  chapter, download [live example](https://angular.io/resources/live-examples/ngmodule/ts/pre-shared.3.plnkr.html) code and run it locally. Open browser visit `http://localhost:3000` can successfully redirect to `http://localhost:3000/contact`, but when refresh page an additional `/contact` will add to url, it become `http://localhost:3000/contact/contact`.  Now, if refresh page again, some errors show in the console. 

**Expected behavior**
Shouldn't and `/contact` to url if already have one.

**Minimal reproduction of the problem with instructions**
Exactly the same code from [live example](https://angular.io/resources/live-examples/ngmodule/ts/pre-shared.3.plnkr.html).

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
win7 node 6.7.0

* **Angular version:** 2.0.X
angular 2.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Hi, pls report documentation issues on https://github.com/angular/angular.io/issues

**Comment by sdhhqb** [comment]
OK, sorry for the trouble.
