### ISSUE TITLE
Using `[attr.disabled]` with no value errors in 2.1.1

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#12583]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using `[attr.disabled]` with no value causes a runtime error on 2.1.2, whereas it did not on 2.1.1

For instance, `<h2 [attr.disabled]>Hello {{name}}</h2>` results in:

```
Unhandled Promise rejection: Cannot read property 'currValExpr' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'currValExpr' of null(…) TypeError: Cannot read property 'currValExpr' of null
```

**Expected behavior**
Did not expect runtime error on a patch version update where there was no runtime error before.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/hWsxGPBSGF0z58R1A5Uy?p=preview

**Please tell us about your environment:**
Plunker
- **Angular version:** 2.1.2
- **Browser:** [Chrome 54]
- **Language:** [TypeScript 2.0.3]

/cc @vicb

**Comment by vicb** [comment]
@tbosch 

We have a clear error message when events are bound to undefined:

```
Empty expressions are not allowed ("
    <div>
      <h2 [ERROR ->](click)>Hello {{name}}</h2>
    </div>
  "): App@2:10 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Empty expressions are not allowed ("
    <div>
      <h2 [ERROR ->](click)>Hello {{name}}</h2>
    </div>
  "): App@2:10
```

Do we want to do the same here or assume null/undefined ?

**Comment by tbosch** [comment]
Let's do this later. For now I will just fall back to the old behavior of ignoring these cases.
