### ISSUE TITLE
How to config Uncompleted Route

### ISSUE THREAD

**Issue by PoppyPham** [angular/angular#12587]
Hi 

I have url like this :: localhost:3000/login?returnUrl=anyUrl
How can I config this route to return my login component??
I tried with this one, but it doesn't  works.
 { path: 'login?returnUrl=*', component: LoginComponent }, 

Thanks,

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by PoppyPham** [comment]
Thanks for quick responding, It works now, it's my mistake.
