### ISSUE TITLE
CanDeactivate guard receives an incorrect component

### ISSUE THREAD

**Issue by alexeikostevich** [angular/angular#12592]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
[CanDeactivate](https://angular.io/docs/ts/latest/api/router/index/CanDeactivate-interface.html) guard receives a component related to the first deactivated segment instead of a component that a guard is attached to.

```
[
    {
        path: '',
        redirectTo: '/hero-center/heroes',
        pathMatch: 'full'
    },
    {
        path: 'hero-center',
        children: [
            { 
                path: 'heroes',  
                component: HeroListComponent 
            },
            { 
                path: 'hero/:id', 
                component: HeroDetailComponent,
                canDeactivate: [CanDeactivateGuard]
             }
        ]
    },
    {
        path: 'crisis-center',
        component: CrisisCenterHomeComponent
    }
]
```

So, in the case of navigation from _/hero-center/hero/1/_ to _/crisis-center_, `CanDeactivateGuard` is called with `null` (component-less component) instead of `HeroDetailComponent`.

The issue is not reproducible with Angular 2.0.1.

**Expected behavior**
[CanDeactivate](https://angular.io/docs/ts/latest/api/router/index/CanDeactivate-interface.html) guard should receive a component that a guard is attached to for the `component` parameter.

**Minimal reproduction of the problem with instructions**
Here is a minimal [plunker ](http://plnkr.co/edit/iqwnxKlB5Z6MJ5afyUj4?p=preview) demonstrating the issue based on [Routing & Navigation](https://angular.io/docs/ts/latest/guide/router.html#!#can-deactivate-guard) live example.

Steps to reproduce:
1. Go to any hero
2. Go to "Crisis Center"

Actual result: Cannot read property 'canDeactivate' of null.
Expected result: A confirmation dialog is shown.

**What is the motivation / use case for changing the behavior?**
There are no ways to prevent navigation from a child component in the case of unsaved changes, etc.

**Please tell us about your environment:**
Windows 10, VS Code 1.6, npm 3.9.5
- **Angular version:** 2.1.2
- **Browser:** [Chrome 54 | Firefox 49]
  
  
- **Language:** [TypeScript 2.0]

**Comment by dimrun** [comment]
Have the same issue. Guys, please take a look.

**Comment by pjir** [comment]
The same on beta version.

**Please tell us about your environment:**
Windows 10, npm 3.10.8

- Angular version: 2.2.0-beta.1
- Language: [Typescript 2.0]

**Comment by feloy** [comment]
Same issue since angular 2.1.2 router 3.1.2.

That works correctly with angular 2.1.2 and router 3.1.1

**Comment by DanWahlin** [comment]
Just hit this as well with angular 2.1.2 and router 3.1.2.

**Comment by slubowsky** [comment]
And if using componentless routes, null is passed in!

**Comment by amamut** [comment]
+1

**Comment by vanrado** [comment]
Hello, I had similar problem. canDeactivate method was always recieving null as component parameter value. I tested it in v2.2.0-rc.0/router v3.2.0-rc.0 and it is fixed and works. Thanks

**Comment by aivou** [comment]
is there a fix for this issue yet ?

**Comment by ericmartinezr** [comment]
Yes, it's in the changelog.
