### ISSUE TITLE
Child component @Input update timing problem

### ISSUE THREAD

**Issue by Skuriles** [angular/angular#12590]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you update an input binding of a child component in parent comp and directly afterwards call a function in child comp, the values are not updated. You need to add a setTimeout to "wait" for the internal update. 
This occurs if using a ViewChild and a template reference variable to call a function in the child component

**Expected behavior**
After updating the parent comp the input bindings should be updated in child component immediately

**Minimal reproduction of the problem with instructions**
See plunker to test (check console.log output)
http://plnkr.co/edit/nNhaPbNZClWXbWqg7G58?p=preview
- **Angular version:** 2.1.2 
- **Browser:** [all]
- **Language:** [all | TypeScript 2.06 ]

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/6PY74dd1BW2QFnOGmWsl?p=preview works as expected without timeout

**Comment by Skuriles** [comment]
![image](https://cloud.githubusercontent.com/assets/7985622/19805634/f5bd04c6-9d15-11e6-9811-0901d158742c.png)

Won't say this is working as expected, or?

**Comment by guojenman** [comment]
I think this is working as designed. @Skuriles Your Child component should be implementing the OnChanges interface instead.

http://plnkr.co/edit/ZdbV3UfpTQa6th03fZYo?p=preview

If you want to call a method directly for some reason, you'll need to use a timeout like you pointed out.

**Comment by kemsky** [comment]
Such behavior is expected, because there is change detection process. You have 2 options: run change detector manually after change or directly use component methods instead of template binding. 

I think that angular strategy in change detection is fine when you are dealing with JIT and dynamic templates, however AOT mode could be reactive.

**Comment by tbosch** [comment]
Sorry, but this is really works as designed. We don't want to have a different behavior between JIT and AoT.
