### ISSUE TITLE
Reflect.getMetadata is not a function

### ISSUE THREAD

**Issue by Davy-F** [angular/angular#12591]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
![image](https://cloud.githubusercontent.com/assets/19592376/19806536/88c2a724-9d13-11e6-836e-d3c6874519f9.png)

I'm trying to run testing in AngularJS. To do this I've had to change my module to commonJS, but with this I then get a 'Reflect.getMetadata is not a function' error. Some people have had a similar issue, but this was with polyfills and angular-chi. I'm using neither of these. 

**Expected behavior**
Run Angular tests on ES6 without errors.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/V7JcmOPfPWqPpRfL4ipc?p=preview

Steps:
1) Open command and cd to the root.
2) Call 'gulp test'
(This is configured in the gulpfile config)
3) Returns 'Reflect.getMetadata is not a function' error as shown above. I do not get this error at runtime and the program compiles fine. 

The program I am running is quite comprehensive, and I am not too familiar with plunker, but I have tried to minimally reproduce this as best to my ability. 

Note: I have commented out some local resources in the index.html. 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7

* **Angular version:** v2.1.1

* **Browser:** [All/Chrome]
 
* **Language:** [Typescript v2.0.3, ES6]

* **Node (for AoT issues):** `node --version` =   v6.5.0 (w/ CommonJS)

**Comment by Davy-F** [comment]
@ericmartinezr Why the thumb down? Some constructive criticism is always welcome...

**Comment by DzmitryShylovich** [comment]
Pls provide a minimal reproduction of the problem.

**Comment by Davy-F** [comment]
Added a more complete minimal reproduction of the problem.

**Comment by vicb** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

--

you are probably not loading the metadata package in your test env.

**Comment by Davy-F** [comment]
Thanks for your help anyway.
I discovered that even though I was including reflect-metadata in my project, I still had to call require("reflect-metadata") in the gulpfile. 

Hopefully this will help someone else out down the line.

**Comment by markmakes** [comment]
I recently got this error on one angular 7 project and not another. There are essentially identical when it comes to packages and config. Here are the two QA projects:

https://uiadminas-qa.azurewebsites.net/
https://qauithefrontrowas.azurewebsites.net/

Reflect.getMetaData is being called in the same location on both AOT builds. Yet one application will run fine and the other throws "Reflect.getMetaData is not a function".

**Comment by markmakes** [comment]
Didn't figure out the discrepancy... but in Angular 7 they removed reflect-metadata from polyfills, but sometimes it's required in prod.

Adding this to my polyfills.ts solves it:

import 'core-js/es7/reflect';
