### ISSUE TITLE
Allow route to load a module in loadChildren property

### ISSUE THREAD

**Issue by stochris** [angular/angular#12594]
**I'm submitting a ...**  (check one with "x")

```
[ ]  bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**What is the motivation / use case for changing the behavior?**

Given that it's much easier to configure the routes when you just provide a module ( that in turn has it's own nested routes ), vs giving children manually, I'd say the approach works nice even when not lazy loading

An example would be :

```
import { AnswersModule } from './answers/answers.module';


const appRoutes: [
{
        path: 'answers',
        loadChildren: AnswersModule
    }
]
```

Currently, the only way is to pass a function that returns a function.
`() => AnswersModule`, which feels a bit hackish
- **Angular version:** 2.1.0

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/10958

**Comment by vsavkin** [comment]
Dup of #10958
