### ISSUE TITLE
Using backticks when declaring a string during import produces an Error: (SystemJS)

### ISSUE THREAD

**Issue by windsinger** [angular/angular#12595]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using backticks when declaring a string in the first line produces an Error: (SystemJS)

For example, this is the first line in my declaration:
`import { Component } from '@angular/core';`
`import { Component } from "@angular/core";`

The variation with the single and double quotes work but if you use backticks instead of single or double quotes, like this:

``import { Component } from `@angular/core`;``

you get an error
`Error: (SystemJS) SyntaxError: Invalid or unexpected token(…)`

**Expected behavior**
This declaration should work just like the others.
``import { Component } from `@angular/core`;``

**Minimal reproduction of the problem with instructions**
Here is a minimal [plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Steps to Reproduce:
1. Go to src/app.ts
2. Change
 `import { Component } from '@angular/core';` to 
``import { Component } from `@angular/core`;``
3. Angular app will not load.

**What is the motivation / use case for changing the behavior?**
Shouldn't it be that since
```foo` === 'foo' === "foo"``
It should follow that you can also use back ticks in when declaring string during import? I'm not sure if this is an accepted use case. I am still trying to learn Angular and encountered this issue.

**Please tell us about your environment:**
Platform 53.1.6 (Developer Build - neverware) developer-build chromeover64 , http://plnkr.co/

* **Angular version:** 2.0.X
2.0.1

* **Browser:** Chrome 53
 
* **Language:** TypeScript 2.0

**Comment by vicb** [comment]
> Error: (SystemJS) SyntaxError: Invalid or unexpected token(…)

Please report this error to SystemJS. Thanks
