### ISSUE TITLE
Introduce render layer

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1260]
Separate DOM access from injector/change detection into an own layer.

**Comment by tbosch** [comment]
Merged the major changes via 50098767fc188426adc7c2f696df00b659b4799f. Need to do some cleanup PRs that add unit tests, ... but no one should be blocked any more.

**Comment by tbosch** [comment]
Open TODOs:

Missing (smaller) refactorings:
- [ ] remove `ProtoView.bind*` methods and move the logic into `ProtoViewFactory`

Missing unit tests:
- [ ] render/view/*
- [ ] core/compiler/proto_view_factory
- [ ] core/compiler/view_factory
- [ ] core/compiler/view (ProtoView and View)
- [ ] core/compiler/view_container

Docs:
- [ ] more inline docs and mark public entries via `@publicModule`

**Comment by mhevery** [comment]
#1480
