### ISSUE TITLE
Dependency Injection to constructor for provider overrides of RequestOptions doesn't work

### ISSUE THREAD

**Issue by dozer75** [angular/angular#12608]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I want to override the RequestOptions class with my own and have followed instructions found on the net on how to do this.

My override is in need of acquiring reference to services to make it work, so I have in the constructor of my class added a reference to the service in quest, but when I try to execute the code, it doesn't get injected.

When I try to override other providers it works as expected.

**Expected behavior**
Dependency injection should be honored whenever the framework initializes an provider override.

**Minimal reproduction of the problem with instructions**
The RequestOptions overrided provider class:

```
import { Injectable } from "@angular/core";
import { BaseRequestOptions, Headers } from "@angular/http";
import { NonHttpService } from "../services/nonhttp.service";

@Injectable()
export class DefaultRequestOptions extends BaseRequestOptions {
    headers: Headers = new Headers({
        "Content-Type": "application/json"
    });

    constructor(private nonHttpService: NonHttpService) { //nonHttpService is here undefined on execution
        super();
    }
}
```

`

The injectable service class:

```
import { Injectable } from "@angular/core";

@Injectable()
export class NonHttpService {
    constructor() {

    }
}
```

A service class using Http:

```
import { Injectable } from "@angular/core";    
import { Http, Response } from "@angular/http";

import { Observable } from "rxjs/Observable";
import "rxjs/add/operator/map";
import "rxjs/add/operator/catch";

@Injectable()
export class LogService {
    constructor(private http: Http) { //This injects the DefaultRequestOptions into the RequestOptions parameter of Http
    }
}
```

The Module definition:

```
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { HttpModule, RequestOptions } from "@angular/http";

import { AppComponent } from "./app.component";
import { appRouting } from "./app.routing";

import { LogService } from "./shared/services/log.service";
import { DefaultRequestOptions } from "./shared/overrides/defaultrequest.options";
import { NonHttpService } from "./shared/services/nonhttp.service";

@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        appRouting
    ],
    declarations: [
        AppComponent
    ],
    bootstrap: [
        AppComponent
    ],
    providers: [
        NonHttpService,
        { provide: RequestOptions, useClass: DefaultRequestOptions },
        LogService
    ]
})
export class AppModule {
}
```

**What is the motivation / use case for changing the behavior?**
Dependency injection providers should always be honored, no matter what the provider override is based on.

**Please tell us about your environment:**
Windows 10
.NET Core ASP.NET project using IIS Express
Node.js version 6.5.0
NPM version 3.10.3
- **Angular version:** 2.1.2
- **Browser:** 
  Tested on:
  Google Chrome Version 54.0.2840.71 m
  Microsoft Edge 38.14393.0.0
- **Language:** 
  TypeScript 2.0.6 compiled to es5
- **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls provide a minimal working reproduction in plunkr.

**Comment by vicb** [comment]
- Add repro,
- Have you searched for a similar issue in the tracker ?

**Comment by dozer75** [comment]
Hi,

@DzmitryShylovich and @vicb here are repro: http://plnkr.co/edit/kAE0JoMLAR3zDK09HTJS?p=preview

Shortly explained:
- Added InjectService class that is marked as Injectable and added this to the module's Providers.
- Added DefaultRequestOptions class that extends BaseRequestOptions with a constuctor that has InjectService as parameter
- Modified App class to have the InjectService as parameter in it's constructor to show that the DI works other places

If executed, the DefaultRequestOptions class will log an error to console if injectService parameter in constructor is null. 

@vicb I have tried to search for it, but couldn't find any recording of similar issue

Best Regards,
--Rune

**Comment by DzmitryShylovich** [comment]
I don't see any errors.

**Comment by red-0ne** [comment]
Extending `RequestOptions` instead of `BaseRequestOptions` should solve the issue. Note that in the repro you are not decorating the `DefaultRequestOptions` class. Also you are not calling `super()` but it doesn't seem to make a difference.

Code with the desired behaviour: http://plnkr.co/edit/FsTrb5BNFUcxJmC3prll?p=preview

**Comment by dozer75** [comment]
@red-0ne Thanks for answer. 

It seems to work when you do that. However, the documentation states that it is `BaseRequestOptions` that should be used since it has the typical defaults (ref: https://angular.io/docs/ts/latest/api/http/index/RequestOptions-class.html). The documentation also shows overriding only by using `BaseRequestOptions ` (ref: https://angular.io/docs/ts/latest/api/http/index/BaseRequestOptions-class.html). The super was my mistake. I have that in my real world code, but not in this example. It is updated now.

I have checked the source code for `BaseRequestOptions` and it doesn't really have anything I want, so I think it is ok for me to extend the base class `RequestOptions` instead. 

However, I still think that it is a bug that you can't extend a class that extends a another one and use this? Or do you have an explanation why it isn't supposed to work? If this is intended to be like this, there should be some sanity check in the framework to avoid things like this to happen.

**Comment by mrgoos** [comment]
Thanks for this thread, had the same issue.
BTW, I see the added header only on GET and not on POST/PUT. Trying to figure out why it happens now.

**Comment by DzmitryShylovich** [comment]
@dozer75 the issue was fixed. http://plnkr.co/edit/rN7HLgZhKHZQ3cOLYZkV?p=preview as u can see u can extend `BaseRequestOptions`

**Comment by dozer75** [comment]
Yes, it seems to work now in the plunker example
