### ISSUE TITLE
routerLinkActive is not working when navigation imperatively

### ISSUE THREAD

**Issue by Saul-Simhon** [angular/angular#12616]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
routerLinkActive is not working when navigation imperatively e.g.  this.router.navigate(['/hero', hero.id]); 

Navigating to components using this.router.navigate does not seem to set the active class for elements that are bound to the routerLinkActive, even when using {exact = true}.  The identical setup seems to work on when using the routerLink attribute in the html (then, the routerLinkActive behaves as expected)

**Expected behavior**

The active class should be bound to the element that has  the routerLinkActive

**Minimal reproduction of the problem with instructions**
Can re reproduced by simply excecuting a router navigation imperatively.  

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

ALL
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls provide a plunker with reproduction.

**Comment by Saul-Simhon** [comment]
Darn, please disregard! It is working as expected. The issue had to do with {exact: true} when using optional parameters!

**Comment by istibekesi** [comment]
I have similar problem. Check this [plunker](https://embed.plnkr.co/cwXf7NcVUdoNbipK1zD7/) forked from the official angular example. How to "fix" the second example?

**Comment by tytskyi** [comment]
@istibekesi 

```html
    <h3>2. router.navigate(): routerLinkActive does NOT work</h3>
    <nav>
      <button type="button" (click)="navTo('/crisis-center')" routerLink="/crisis-center" routerLinkActive="active">Crisis Center</button>
      <button type="button" (click)="navTo('/heroes')" routerLink="/heroes" routerLinkActive="active">Heroes</button>
    </nav>
```

```css
nav button.active {
  color: #039be5;
}
```

**Comment by istibekesi** [comment]
@tytskyi Awesome, thanks! Can you explain shortly, why is it okay for a button but does not work on `<a>` tag?

**Comment by tytskyi** [comment]
@istibekesi my bad, actually it does not work, it will redirect regardless if you have `(click)` listener or not. 

Here: https://github.com/angular/angular/blob/master/packages/router/src/directives/router_link_active.ts#L142 
you can see that `[routerLinkActive]` is supposed to work in pair with `RouterLinkWithHref` or `RouterLink` directives. 

I am sorry for confusion.

So as for now you need to manipulate class imperatively / write your own directive / open proposal.

For me it seems like the original ticket is valid, but should be clarified = `routerLinkActive is not working when navigating imperatively when used without routerLink directive`

**Comment by istibekesi** [comment]
@tytskyi Indeed, we had some confusion, but it is clear now. 
I also missed it, your fix was working because of  the `routerLink`, not the `button`.

**Comment by alxpsr** [comment]
same problem :(
this bug or feature?
