### ISSUE TITLE
bootstrapped Component's default design issue with primary-outlet and named-outlet

### ISSUE THREAD

**Issue by micronyks** [angular/angular#12613]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**`Angular2`** is not parsing HTML(design) as it is placed.

**Expected behavior**

**`Angular2`** should parse HTML as it is placed.

By defult I should not play with **`CSS`** to get the desire output. **`Angular2`** should parse HTML as they are placed.

**Minimal reproduction of the problem with instructions**

1) I'm having **`Primary Outlet`** which loads **`Dashboard Component`**.
2) I'm having other two named outlets **`HeaderOutlet`** and **`FooterOutlet`** which load **`Header`** and **`Footer`** Components respectively.

I have placed them in following order,

```

  <router-outlet name="HeaderOutlet"><router-outlet>

   <hr>

  <router-outlet><router-outlet>

   <hr>

  <router-outlet name="FooterOutlet"><router-outlet>

```

 **`DEMO`** :  **https://plnkr.co/edit/imNNtWXLo6RBxp1jYxbv?p=preview**

When app runs,

   **Output Should be :** <br>

```
Header Component
_______________________________________________
Dashboard Component
_______________________________________________
Footer Component
```

But output is not as expected.

**NOTE** : No Matter how I place them **`Dashboard`** remains on the top.
- **Browser:** [Chrome XX | Firefox XX ]
  
  
- **Language:** [TypeScript X.X]

**Comment by ericmartinezr** [comment]
It works if you close correctly the router-outlet tag.

**Comment by DzmitryShylovich** [comment]
👍 https://plnkr.co/edit/17a2jjMV622Pw1QmiGQR?p=preview

**Comment by vicb** [comment]
@ericmartinezr @DzmitryShylovich thanks for answering the question.

> The question is why doesn't angular throw template parse exception.

This is compliant with the HTML5 spec, you can check on `astexplorer.net`
