### ISSUE TITLE
The live example in Template Syntax has crashed

### ISSUE THREAD

**Issue by datbachkhoa** [angular/angular#12612]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**_I've read the guide of AngularJS 2, the Template Syntax page, and I clicked the live example to see the demo, but it was not running. Only the loading show and nothing happen. Please check the link for see the detail: https://angular.io/resources/live-examples/template-syntax/ts/plnkr.html_**
**Expected behavior**

The live example in Template Syntax is done. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io/issues
