### ISSUE TITLE
Click event that modifies child nested recursive component variable alters parent variable

### ISSUE THREAD

**Issue by mpduffey** [angular/angular#12611]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have built a component that nests itself recursively. The component contains a boolean variable "showSubform" that holds the state of *ngIf for the instance of nested recursive component. When the click event triggers the function that contains "showSubform = !showSubform", the showSubform for the parent component is modified as well. Since it is a boolean, if the parent is true and the child is false, clicking the link that toggles the variable in the child toggles the variable in the parent and sets it to false, hiding the entire hierarchy of components.

**Expected behavior**

Event impacting a component variable only modify the local component variable and do not bubble up to impact the value of a parent component variable with the same class and variable name.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

See above. Prevent parent component variables from modifying when recursively nested component variables are modified

**Please tell us about your environment:**

AWS Linux
- **Angular version:** 2.0.X
  
  
  
  2.0.1
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
  
  Chrome 54.0.2840.71 m
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  Typescript
- **Node (for AoT issues):** `node --version` =  
  6.9.1

**Comment by robwormald** [comment]
As stated in the issue template, please provide a plunker or reproduction of your problem. It's impossible to debug or troubleshoot otherwise.

**Comment by sod** [comment]
I tried it and it works for me!? https://plnkr.co/edit/nQlapclopU3HK0uwZuvN?p=preview

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
