### ISSUE TITLE
Browser Support results are getting worse

### ISSUE THREAD

**Issue by goriunov** [angular/angular#12621]
I am just checking some times browser support results 
here : https://saucelabs.com/u/angular2-ci 
for Angular 2 and now i found that  2 Android Browsers 4.3 and 4.2 are fail and Internet explorer 9 too,  when are you going to fix that >:)

Thank you for your work 👍

**Comment by tbosch** [comment]
This seems wired, as otherwise our CI would be red... This probably only a flake...

**Comment by goriunov** [comment]
Nit sure if it is problem with lab or angular 2 , however just check your Support result and it is not very good . Half of android browsers are red and plus IE 9 too

**Comment by IgorMinar** [comment]
this is now obsolete - most of the results are green and we are working quite hard on dealing with the flaky results.
