### ISSUE TITLE
Add positioning API to the Ruler 

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1262]
Add API to the `Ruler` #1253 which would allow setting the position of the component. 

* [ ] Low level API first `ruler.position(new Rectangle(...))`
* [ ] More constraint based API as in `ruler.position(new Size(...), offsetFrom: componentRef, ...)`.

**Comment by naomiblack** [comment]
Nice to have, but currently host properties are an ok workaround.

**Comment by pkozlowski-opensource** [comment]
ruler is gone, closing as obsolete
