### ISSUE TITLE
ActivatedRoute not emitting change for route data

### ISSUE THREAD

**Issue by qatsi** [angular/angular#12623]
**I'm submitting a ...** 
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I've added some static route data to a couple of routes
```
const routes: Routes = [
  { path: '', component: StartComponent, data: { headerStyle: 'transparent' } },
  { path: 'about', component: AboutComponent, data: { headerStyle: 'default' } },
];
```
And listen to change on my component with 
```
constructor(private route: ActivatedRoute) { }
ngOnInit() {
  this.route.data.forEach((data: any) => {
    console.log(data);
  });
}
```
The issue is that ActivatedRoute never emits change for data, the handler is only run once, on app bootstrap, but then not when first route is loaded or when app is navigated

**Expected behavior**

Expected ActivatedRoute event handling to work like described in ng2 documentation f.e. in https://angular.io/docs/ts/latest/guide/router.html#!#activated-route section

**Minimal reproduction of the problem with instructions**

* Create a new project with angular-cli (1.0.0-beta.19)
* Generate 3 components: start, about & header
* Add a routing module as below and import it in app.module.ts
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { StartComponent } from './start/start.component';
import { AboutComponent } from './about/about.component';

const routes: Routes = [
  { path: '', component: StartComponent, data: { headerStyle: 'transparent' } },
  { path: 'about', component: AboutComponent, data: { headerStyle: 'default' } },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
  providers: []
})
export class AppRoutingModule { }
```
* Update app.component.html to below
```
<app-header></app-header>
<router-outlet></router-outlet>
```
* Update header.component.html to below
```
<a routerLink="/" routerLinkActive="active">Home</a>
<a routerLink="/about" routerLinkActive="active">About</a>
```
* Lastly, update header.component.ts
```
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  constructor(private route: ActivatedRoute) { }
  ngOnInit() {
    this.route.data.forEach((data: any) => {
      console.log(data);
    });
  }
}
```

**Please tell us about your environment:**

macOS, Angular-cli

* **Angular version:** 2.1.2

* **Browser:** [all ]

 
* **Language:** [TypeScript 2.0]

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/11023

**Comment by qatsi** [comment]
Ah, I see, I thought ActivatedRoute would behave the same in every component that inject it, since DI injects the same instance of the service. Apparently thats not the case though as discussed in #11023. I guess this will not be considered a bug and a solution for the desired use case with global route data will be handled in the referenced issue, so closing this one
