### ISSUE TITLE
can't bind to ngModel even though FormsModule is imported

### ISSUE THREAD

**Issue by Optiq01** [angular/angular#12620]
I'm following this tutorial
https://angular.io/docs/ts/latest/tutorial/toh-pt1.html

when I get to the part that uses 2 way binding with the [(ngModel)] I started getting this error

> Can't bind to 'ngModel' since it isn't a known property of 'input'.

I searched the web and over 90% of what I see about this error is always resolved by the person importing the Forms Module.  I have it imported, after going back and forth from the tutorial to my code, I just copy and pasted their code into my component and still encountered the same problem.

I'm using node 5.7.0 and npm 3.6.0 on windows vista.  As far as everything else, here's the package.json file

    `{
      "name": "angular-quickstart",
      "version": "1.0.0",
      "scripts": {
        "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
        "lite": "lite-server",
        "tsc": "tsc",
        "tsc:w": "tsc -w"
      },
      "licenses": [
        {
          "type": "MIT",
          "url": "https://github.com/angular/angular.io/blob/master/LICENSE"
        }
       ],
      "dependencies": {
        "@angular/common": "~2.1.1",
        "@angular/compiler": "~2.1.1",
        "@angular/core": "~2.1.1",
        "@angular/forms": "~2.1.1",
        "@angular/http": "~2.1.1",
        "@angular/platform-browser": "~2.1.1",
        "@angular/platform-browser-dynamic": "~2.1.1",
        "@angular/router": "~3.1.1",
        "@angular/upgrade": "~2.1.1",
        "angular-in-memory-web-api": "~0.1.13",
        "bootstrap": "^3.3.7",
        "core-js": "^2.4.1",
        "reflect-metadata": "^0.1.8",
        "rxjs": "5.0.0-beta.12",
        "systemjs": "0.19.39",
        "zone.js": "^0.6.25"
      },
      "devDependencies": {
        "@types/core-js": "^0.9.34",
        "@types/node": "^6.0.45",
        "concurrently": "^3.0.0",
        "lite-server": "^2.2.2",
        "typescript": "^2.0.3"
      }
    }`

Here are my other files

main.ts

    `   import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
        import { AppModule } from './app.module';

         const platform = platformBrowserDynamic();
         platform.bootstrapModule(AppModule);`

app.module.ts

    `
    import { NgModule }      from '@angular/core';
    import { BrowserModule } from '@angular/platform-browser';
    import { FormsModule }   from '@angular/forms';

    import { AppComponent }  from './app.component';

    @NgModule({
      imports: [
        BrowserModule,
        FormsModule
      ],
      declarations: [
        AppComponent
      ],
      bootstrap: [ AppComponent ]
    })
    export class AppModule { }`

app.component.ts

    `  import { Component } from '@angular/core';

        export class Hero {
	  id: number;
	  name: string;
	
      }

      @Component({
	
	  selector: 'my-app',
	  template: `<h1>{{title}}</h1>
				<h2>{{hero.name}} details!</h2>
				<div><label>id: </label>{{hero.id}}</div>
				<div>
					<label>name: </label>
					<input [(ngModel)]="hero.name" placeholder="name">
				</div>`
      })

      export class AppComponent {
	  title	=	'Tour of Heroes';
	  hero: Hero ={
		id: 1,
    		name: 'Windstorm'
    	  };
      }`

index.html

    `
      <!DOCTYPE html>
     <html>
      <head>
        <title>Angular QuickStart</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="styles.css">
        
         
        <script src="node_modules/core-js/client/shim.min.js"></script>
        <script src="node_modules/zone.js/dist/zone.js"></script>
        <script src="node_modules/reflect-metadata/Reflect.js"></script>
        <script src="node_modules/systemjs/dist/system.src.js"></script>
        
        <script src="systemjs.config.js"></script>
        <script>
          System.import('app').catch(function(err){ console.error(err); });
        </script>
      </head>
      
      <body>
        <my-app>Loading...</my-app>
      </body>
    </html>
    '

I have absolutely no clue as to what I'm doing wrong here.

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kapilkarda** [comment]
I am facing the same issue, is anyone their, who can help me ?
