### ISSUE TITLE
[Proposal] new Http APIs with whatwg Fetch spec compatibility

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#12638]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

## Problem

`@angular/http`  (hereinafter called "Angular Http") was designed as a polyfill for **Fetch API**. For example, a documentation of `Headers` class is the below.

```
 * Polyfill for [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers), as
 * specified in the [Fetch Spec](https://fetch.spec.whatwg.org/#headers-class).
 *
 * The only known difference between this `Headers` implementation and the spec is the
 * lack of an `entries` method.
```

But currently, Angular Http is not playing the role of a polyfill of the spec. `Headers`, `Request`, `Response` and other class's type definitions are not compatible with the spec. When major web browsers have the API, Angular users will be confused by the differences. 

**Current behavior**
Angular Http is not a Fetch API polyfill. 

## Proposal

Even as it doesn't match the spec **now**, of course, I think it should do in the future. All APIs should be aligned to the latest Fetch API spec and they should be transparent as a polyfill. Since its type definitions are maintained as [`@types/whatwg-fetch`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/whatwg-fetch/whatwg-fetch.d.ts) package, Angular Http can use standard `Headers` and more interface types.

### e.g. `Headers`

```
// <reference path="path/to/node_modules/@types/whatwg-fetch/index.d.ts" />

class NgHeaders implements Headers /** ambient type **/ {
   // ... implementations
}

export { NgHeaders as Headers };
```

Angular Http is protected by semver now. So this proposal focuses on next major version, `@angular/http@3`.

BTW, who is the caretaker of Http?
cc/ @robwormald

**Comment by laco0416** [comment]
I'm thinking about creating new `@angular/fetch` module. it can save current http module and introduce new APIs.

**Comment by laco0416** [comment]
I talked with @robwormald offline about this. 
I will create a design doc for the proposal of new module, `@angular/fetch` (temporary name) by early 2017.

**Comment by jskrzypek** [comment]
Hi @laco0416, thank you for taking the initiative! This would be a wonderful feature to see land in angular 4.
Do you have any updates on this?
Also, would this module then give the community easy, zone-aware access to the full spectrum of the whatwg-fetch api (assuming proper browser support)?

**Comment by DzmitryShylovich** [comment]
@jskrzypek 
#14334
https://docs.google.com/document/d/1C_wzuuQEjIktJxrTlUTjTCDEZR8YduGTfbpe4WsNfNk/edit#heading=h.xgjl2srtytjt

**Comment by laco0416** [comment]
I wrote [Angular Fetch Design Doc](https://goo.gl/h0UkSj). Next week at ng-conf, I'd like to discuss with core team about the roadmap and future of Angular's HTTP client APIs. 

cc/ @alxhub @robwormald

**Comment by DzmitryShylovich** [comment]
I would prefer to have a single public api with 2 implementations: hxr and fetch. Fetch implementation won't do anything on cancellation and won't generate any progress events, but will parse response async. And users will be able to choose the implementation like `HttModule.withHxr()` or `HttModule.withFetch()`

**Comment by jskrzypek** [comment]
Wouldn't that make it rather cumbersome to use both fetch & xhr within the
same app?

**Comment by alxhub** [comment]
@laco0416, let's definitely meet at ng-conf. In the meantime I need to update my design doc with the latest ideas. Essentially they make the change non-breaking so it can land in an upcoming minor version, but also lots of the API design has evolved since I wrote the original doc. I'll share it with you when I do that.

**Comment by Urigo** [comment]
@alxhub would love to help as well! I'm also coming to ng-conf

**Comment by alxhub** [comment]
Closing as the proposal here was implemented in `HttpClient` - `fetch`-based backends are possible (but still not provided by Angular).
