### ISSUE TITLE
Incorrect encoding for URL path

### ISSUE THREAD

**Issue by huyph** [angular/angular#12637]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Colon (`:`) in URL is encoded (as `%3A`).

In `url_tree.js`:
```javascript
export function encode(s) {
    return encodeURIComponent(s);
}
....
export function serializePath(path) {
    return "" + encode(path.path) + serializeParams(path.parameters);
}
```

**Expected behavior**
Colon should be allowed unescaped in the URL path. This makes URL more readable.

The above `serialisePath(path)` should be changed to:
```javascript
    return "" + encodeURI(path.path) + serializeParams(path.parameters);
```

**What is the motivation / use case for changing the behavior?**
Making URL more readable and user-friendly.

* **Angular version:**
2.1.0 with @angular/router: 3.1.0

* **Browser:** 
Chrome 54 | Firefox 49.0.2
 
* **Language:** 
ES6

**Comment by vsavkin** [comment]
The default url serializer uses ":" to separate the outlet of a url segment from its path. Hence we have to escape it. You can provide your own url serializer that uses a different encoding scheme and doesn't escape colons, like this:

```
@NgModule({
  imports: [RouterModule.forRoot(routes)],
  providers: [
    {provide: UrlSerializer, useClass: MyCustomUrlSerializer}
  ]
})
class MyNgModule {}
```

**Comment by huyph** [comment]
"the outlet of a url segment from its path" . Can you elaborate on what is segment and what is path here?. In my understanding, "a/b/c" is path, where "a", "b", and "c" are segments?

**Comment by zoechi** [comment]
Is this related to #12740 ?

> Error: Cannot match any routes. URL Segment: 'list(full%3Afull)'

**Comment by Pittan** [comment]
Is [this](https://github.com/angular/angular/commit/8f7cce3) commit solves this issue? > @huyph
