### ISSUE TITLE
Support ICU message for xliff

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#12636]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using something like `<div i18n id="i18n-7">{count, plural, =0 {zero} =1 {one} =2 {two} other {<b>many</b>}}</div>` in the case of `other` it prints `many`.

**Expected behavior**

it should print `<b>many</b>`. It is omitting the html part.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/ucuVZuhU67Ul64ViUSa8?p=preview

**What is the motivation / use case for changing the behavior?**

It is a bug :)

* **Angular version:** 2.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by Foxandxss** [comment]
ping @vicb

**Comment by kemsky** [comment]
This is good point no doubt. My concern is overall state of i18n. It has to be carefully designed to work nicely with rich template syntax as well as AOT compilation and localization formats.

**Comment by mlaval** [comment]
I've been looking into that, the biggest challenge is to find a format to serialize ICU messages into XLIFF, knowing that this format should be compatible with translation tools.

I did some research which is documented here: https://docs.google.com/document/d/1FS02wIBSEbysCoxEqbEmJg3_LyfJ566DZLhhbOUheoA/edit?usp=sharing

Feedback is more than welcome :)

**Comment by mlaval** [comment]
@panuruj Based on your work on XLIFF 2.0 support, I can imagine that you are a heavy XLIFF user and we could use your expertise to solve this issue :)

Would you use ICU messages if they were available for XLIFF? Would you recommend one of the format I've documented above?
We are currently leaning towards solution 4, which is basically pasting the full ICU message into the XLIFF file and letting the translator take care of it ...

If you don't mind, it would be also interesting to understand how you handle plural cases in your applications.
