### ISSUE TITLE
ActivatedRoute.snapshot.queryParams undefined

### ISSUE THREAD

**Issue by isaac2004** [angular/angular#12644]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Having a url such as 
http://localhost:5000/?id_token=eyJ0eXAiO....

This statement results in undefined in console
`  this.path = this.activatedRoute.snapshot.queryParams['id_token'];
   console.log(this.path);`

**Expected behavior**
console should display querystring parameter

**What is the motivation / use case for changing the behavior?**
I am using Azure Active Directory that uses QS to pass an authentication token back the referrer. I need to capture it and than route accordingly

**Please tell us about your environment:**
Windows 10 Anniversary Update. Visual Studio 2015 for Development

* **Angular version:** 2.0.X
2.0.0

**Comment by DzmitryShylovich** [comment]
Pls provide reproduction in plunkr.

**Comment by pkozlowski-opensource** [comment]
Closing as we didn't hear back with the reproduce scenario.
