### ISSUE TITLE
Router breaks down when referencing a constant from within a component

### ISSUE THREAD

**Issue by btgoodwin** [angular/angular#12641]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a constant defined in the parent directory of an application.  If I import that constant and then try to reference it in my component, the Router fails to create the component (treats it like it's invalid even though it should be fine).  If I import that constant from a file within this component's directory or define it within the component's file, everything is fine.  It seems to be purely that the constant was imported from outside the component's directory.

When running in production, the router simply does not populate the router-outlet.  Instead navigating away from that location causes the router to throw an error about the outlet not being activated.  When running in the attached plnkr, the error is more evident: it's claiming the component itself is invalid at that route.

**Expected behavior**

I would expect the location of a constant declaration within the filesystem to have no bearing on whether or not a component is valid according to the Router.  In other words, I would have expected the router to instantiate the component and not have to define everything at the same folder hierarchy of the component.

**Minimal reproduction of the problem with instructions**

[Plnkr example](https://plnkr.co/edit/Ujnxbo13DN4QkrZWKbHO?p=preview)

Open the `src/sub/topb.ts` file.  There you'll see a comment block about the 3 different import/declaration methods that I've tried.  Uncommenting either of the first two will work as expected, direct declaration and import from a file at this hierarchy.  Trying to use the last one, importing from the parent directory, will cause the component to get flagged by an error in the console that indicates the Router sees it as an invalid component.

**What is the motivation / use case for changing the behavior?**

This isn't a change in behavior so much as making the behavior consistent.  I've attempted to correct this problem using OpaqueToken(s) also defined in the parent directory and then populated through that module's providers, but the `@Inject()` at the component in the subdirectory still results in the same behavior (treating the component as if it's invalid).

**Please tell us about your environment:**

CentOS 6.7 64-bit
npm 3.10.7

* **Angular version:** 2.0.X

Angular 2.1.2
Router 3.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 54
Safari 10
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.6
ES5

* **Node (for AoT issues):** `node --version` =

**Comment by btgoodwin** [comment]
Here's an additional [example](https://plnkr.co/edit/ruvRHec3l82rWXwgFQVl?p=preview).

In this example, I created a component that gets instantiated within that TopB component (which could not be instantiated if it used the imported-from-parent-directory constant).  This new component does the exact same thing that caused TopB to fail: import the constant from a file in its parent folder.  The only difference is the Router isn't creating it, and so there is no problem.

**Comment by olegdunkan** [comment]
You have cyclic dependencies, /sub/topb depends on /settings and vise versa, it is a bad  practice.

**Comment by btgoodwin** [comment]
Fair point.  Moving the constant to a separate file and importing it at /settings and /sub/topb allows this to work.  Even conceding that point though, the component instantiation method works and allowing the Router to create the component does not.  Is there a means to reduce that sensitivity in the Router?

**Comment by olegdunkan** [comment]
Router does nothing in this case, it is all about compiler and linker, when compiler create module factory you get hot code:
````
Object.defineProperty(AppModuleInjector.prototype, '_Token_ROUTES_36', { get: function() {
  var self = this;
    if ((self.__Token_ROUTES_36 == null)) { (self.__Token_ROUTES_36 = [[
      {
        path: 'TopA',
        component: jit_val31
      }
      ,
      {
        path: 'TopB',
        component: null
      }
      ,
      {
        path: '',
        redirectTo: 'TopA',
        pathMatch: 'full'
      }

    ]
  ]); }
  return self.__Token_ROUTES_36;
}});
````
And you can see  'component: null', it is because of cyclic dependencies.

**Comment by olegdunkan** [comment]
You can use forwardRef.
````
export const ROUTES: Routes = [
  { path:'TopA', component: TopA },
  { path:'TopB', component: forwardRef(() => TopB) },
  { path:'', redirectTo: 'TopA', pathMatch: 'full' }
  ];
````

**Comment by olegdunkan** [comment]
You can use forwardRef.
````
export const ROUTES: Routes = [
  { path:'TopA', component: TopA },
  { path:'TopB', component: forwardRef(() => TopB) },
  { path:'', redirectTo: 'TopA', pathMatch: 'full' }
  ];
````
We will have the TopB to be defined but compiler won't create factory for TobB

**Comment by btgoodwin** [comment]
I appreciate the workaround. I suppose this can be closed/deleted given it
isn't actually a bug. However it would be nice if both methods failed for
the same reason (component instantiation, router outlet, etc.).

Thanks for the info.
