### ISSUE TITLE
Accessing URL attribute of Router class directly gives incorrect path

### ISSUE THREAD

**Issue by sachanacar** [angular/angular#12649]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

It seems that accessing the Router’s class URL does not properly output the actual URL of the page. However, logging the whole Router object shows the proper URL.

Here is my code importing the Angular 2 Router class:

````
 import {Component, Input, OnInit} from '@angular/core';
 import {Router} from '@angular/router';

 private router: Router;

 @Input() toggle: Toggle;

 constructor(router: Router) {
   this.router = router;
 }

 ngOnInit(): void {
   console.log(this.router.url);
   console.log(this.router);
 }
````

The URL path is the following: "http://localhost:5000/nav2"

logging this.router gives the following:

````
Router
  config: Array[3]
  configLoader: RouterConfigLoader
  currentRouterState: RouterState
  currentUrlTree: UrlTree
  errorHandler: defaultErrorHandler(error)
  events: (...)
  injector: MainModuleInjector
  location: Location
  locationSubscription: Subscriber
  navigated: true
  navigationId: 1
  outletMap: RouterOutletMap
  rootComponentType: TesterComponent()
  routerEvents: Subject
  routerState: (...)
  url: (...) //this expands to "/nav2"
  urlSerializer: DefaultUrlSerializer
  __proto__: Object
````

Notice, the expansion of the URL attribute?

However, logging this.router.url outputs this:

```
/
```
**Expected behavior**

this.router.url should output "/nav2" in this case.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/FRuBEu6h3isGmpE8HsuW?p=preview

**What is the motivation / use case for changing the behavior?**
Right now the dirty workaround is using window.location.pathname, which is not ideal!

**Please tell us about your environment:**

Angular 2.0.1
Chrome Version 54.0.2840.71 (64-bit)
TypeScript ES5

**Comment by DzmitryShylovich** [comment]
Works as expected https://plnkr.co/edit/4ocISeTsjTKcHrRH84DO?p=preview

https://angular.io/docs/ts/latest/guide/router.html

**Comment by sachanacar** [comment]
Thanks for your answer @DzmitryShylovich, however I feel that this Plunkr does not reflect the scenario properly because it doesn't allow me to read the URL from the navigation bar the same way window.location does.

In the Plunkr I have to set the route link within the code (component) this way:

```
@Component({
  selector: 'my-app',
  template: `<a routerLink='route1'>Click me</a>
    <router-outlet></router-outlet>`
})
```

However, if you try building your own component locally (without Plunkr) and access the URL path directly using this.router.url, then you will see the error.

**Comment by HauntedSmores** [comment]
Im having the exact same Issue. If you delay, like using setTimout or ngAfterViewChecked(), then it will spit back the correct url. Idk why the Router object would have the correct value in its properties OnInit but not return the correct value using router.url

**Comment by vsavkin** [comment]
1. The router always starts with a blank url, and then navigates to the URL in the URL bar. This navigation is done in a microtask, so it is async.
2. The root component is created before the the first navigation. So "/" is the correct value.
3. url(...) is a getter, hence it is evaluated only when you click on "...". The value you see was updated after the console.log call, and, that's why you see the value from the URL bar. 

You should do something like this:

```
router.events.filter(e => e instanceof NavigationEnd).first().subscribe(() => {
  // the first navigation is complete and the URL is set
});
```

Closing this issue.

**Comment by intellix** [comment]
Just run into this myself and was surprised it doesn't have the value synchronously which is already available in the URL bar

URL is /products
```js
console.log(router.url); // logs "/"
setTimeout(() => console.log(router.url)); // logs "/products"
```

**Comment by IAMtheIAM** [comment]
Yes this is a problem. It does not show the current route, something with async?

**Comment by phil123456** [comment]
same here, it returns /, using angular 5

**Comment by crush83** [comment]
@phil123456 I would expect `window.location.pathname` to not work to well if you are running from a sub folder on your web server. Like `http://www.myserver.com/myapp/` as the root of your app, `window.location.pathname` will include `myapp/` almost certainly. So, using router is preferred as it is more portable. Unfortunately, getting the route relative to the root of your app, within your app component seems impossible without deferring executing.

**Comment by phil123456** [comment]
> @phil123456 I would expect `window.location.pathname` to not work to well if you are running from a sub folder on your web server. Like `http://www.myserver.com/myapp/` as the root of your app, `window.location.pathname` will include `myapp/` almost certainly. So, using router is preferred as it is more portable. Unfortunately, getting the route relative to the root of your app, within your app component seems impossible without deferring executing.

sounds legit althought it does not work, window.location.pathname gives the best results
