### ISSUE TITLE
Unit test - ngFor rendered child components' templates, do not register changes

### ISSUE THREAD

**Issue by gituser7878-Ultralinq** [angular/angular#12642]
**I'm submitting a ...**  (check one with "x")

[x ] bug report

**Current behavior**

*ngFor rendered child component templates, do not have a change in them when something is clicked on the template that should change them (unit test).

**Expected behavior**

The *ngFor rendered child components' templates would change, when something is clicked on the template in the unit test.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/PH0W1lkbXKFGDSrUHYxS?p=preview
The test's expectation should pass (but doesn't). Indeed you do see the order of the child components on the template once the test is finished ("second value, initial value" instead of "initial value, second value", on the Plunkr) as it should be. 

**What is the motivation / use case for changing the behavior?**
Well, I am sure child components' templates should always register changes in unit tests, whether they are initially rendered with *ngFor or not.

**Please tell us about your environment:**
Seems to be environment-independent.

* **Angular version:** 2.0.X
2.0.0

**Comment by vicb** [comment]
```
@Component({
 selector: 'my-cmp',
 template: `<div (click)="updateMe()"></div>
 <section *ngFor="let _testVar of _testVars; trackBy index">
   <child-cmp [_testVar]="_testVar"></child-cmp>
   </section>`
})

export class myCmp {
  _testVars = ["initial value", "second value"];
   private updateMe(): void {
      this._testVars = ["second value", "initial value"];
   }
   
   index(i) {
     return i;
   }
}
```

**Comment by elliotwesoff** [comment]
So what was the solution?
