### ISSUE TITLE
Removing traceur requirements

### ISSUE THREAD

**Issue by darcnite3000** [angular/angular#1265]
Is there anyway we can remove the traceurRuntime requirement for angular mainly in the es5 compatible version, given that i precompile my code with babeljs, the need for a live building runtime is a bit weird.

**Comment by pkozlowski-opensource** [comment]
Currently the `angular2` package contains "pure" ES6 sources (transpiled from AtScript). You can transpile those down to ES5 using babeljs and then the traceur runtime is nowhere in the picture. 

On top of this we are in the process of migrating the code base to TypeScript so this picture will be changing in the (near future). 

Closing this one as traceur runtime is not a requirement today and won't be in the future.
