### ISSUE TITLE
Error: SyntaxError: Unexpected strict mode reserved word 

### ISSUE THREAD

**Issue by sumitknoldus** [angular/angular#12657]
Hi guyz, 

I'm getting this error while I'm creating the build for my angular2 application using Rollup.js for Tree Shaking but I'm not sure what im doing wrong kindly help me.

**Below is the error: **
```
Error: (SystemJS) Unexpected strict mode reserved word
SyntaxError: Unexpected strict mode reserved word
at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.6.25?main=browser:203:28)
at Zone.run (https://unpkg.com/zone.js@0.6.25?main=browser:96:43)
at https://unpkg.com/zone.js@0.6.25?main=browser:462:57
at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.6.25?main=browser:236:37)
at Zone.runTask (https://unpkg.com/zone.js@0.6.25?main=browser:136:47)
at drainMicroTaskQueue (https://unpkg.com/zone.js@0.6.25?main=browser:368:35)
Evaluating http://localhost:9000/app/bundle.min.js
Error loading http://localhost:9000/app/bundle.min.js
```

**Comment by zoechi** [comment]
How can this be reproduced?
The issue template wasn't filled .


> IF YOU DON'T FILL OUT THE FOLLOWING INFORMATION WE MIGHT CLOSE YOUR ISSUE WITHOUT INVESTIGATING

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
