### ISSUE TITLE
AOT fails when using more than 9 interpolation values with Pug

### ISSUE THREAD

**Issue by freezy** [angular/angular#12663]
Compiling a project using the [pug template engine](https://pugjs.org) fails with the following error when there are more than 9 interpolation values:

```
C:\dev\aot-test>node_modules\.bin\ngc -p tsconfig-aot.json
Error: Template parse errors:
Error: Only support at most 9 interpolation values! ("[ERROR ->]h3 Home Component
p Welcome to Angular Seed
ul
"): HomeComponent@0:0
    at TemplateParser.parse (C:\dev\aot-test\node_modules\@angular\compiler\bundles\compiler.umd.js:7711:21)
    at OfflineCompiler._compileComponent (C:\dev\aot-test\node_modules\@angular\compiler\bundles\compiler.umd.js:13208:53)
    at C:\dev\aot-test\node_modules\@angular\compiler\bundles\compiler.umd.js:13152:109
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:456:3
Compilation failed
```

Note that unlike angular/angular#10253, these are **separate HTML elements**:

```pug
h3 Home Component
p Welcome to Angular Seed
ul
    li My variable: {{ foo }}
    li My variable: {{ foo }}
    li My variable: {{ foo }}
    li My variable: {{ foo }}
    li My variable: {{ foo }}
    li My variable: {{ foo }}
    li My variable: {{ foo }}
    li My variable: {{ foo }}
    li My variable: {{ foo }}
    li My variable: {{ foo }} (remove this line and it works)
```
You can reproduce it with [this fork of angular/angular2-seed](https://github.com/freezy/angular2-seed/tree/aot), which only adds AOT and replaces the home HTML template with a Pug template. Just run `./node_modules/.bin/ngc -p tsconfig-aot.json` and you should have it.

EDIT: Note that is works perfectly fine in the browser using `npm run server`.

**Comment by DzmitryShylovich** [comment]
It's not aot specific. Angular has a limit for interpolation values for performance reasons.

**Comment by freezy** [comment]
If it's not AOT specific, why does it work in the browser then?

**Comment by DzmitryShylovich** [comment]
yeah, nvm didn't read the full description.

**Comment by freezy** [comment]
Okay. You can see the changes I've made [here](https://github.com/freezy/angular2-seed/commits/aot), they are trivial.

**Comment by vicb** [comment]
> It's not aot specific. Angular has a limit for interpolation values for performance reasons.

That's true, the template parser is the same for AoT or JIT.

This is a known limitation - check the issue tracker for similar issues.
We have plan to handle static text nodes and expressions differently which might remove this limitation.

**Comment by freezy** [comment]
What, so you're saying that it's impossible to use any template engine if you need more than 9 expressions in an entire page?

**Comment by freezy** [comment]
@vicb Did you read through the whole description? This is not a case like angular/angular#10253 that you can solve with a filter or different DOM structure. This means that AoT basically fails for every project using an HTML templating engine with Webpack.

And with the risk of sounding repetitive, why would it work using JIT if it wasn't an AoT issue? Maybe it's not related to the template parser? 

I urge you to reconsider closing this because without AoT, Angular 2 is terribly slow to load. The only way I see around this is rewriting all our Pug templates into HTML, which would really suck.

**Comment by tbosch** [comment]
So the problem here is as follows (using your reproduction repo):

- [aot/src/app/home/home.component.ts](https://github.com/freezy/angular2-seed/blob/) refers to [https://github.com/freezy/angular2-seed/blob/](aot/src/app/home/home.component.pug) as template
- Angular treats the template as plain html, i.e. this is just one big chunk of text
- That is why Angular complains that there are more than 9 interpolation values, because of angular/angular#10253

**Comment by freezy** [comment]
Hmm isn't Webpack supposed to care of this? Is Webpack involved at all when doing AoT?

I've come across qdouble/angular-webpack2-starter#75 with the same problem, which was resolved by just pre-compiling Pug to HTML before launching `ngc` and referring to the HTML file instead of the Pug template. Is this how it's supposed to be done? Are there any more elegant workarounds?

If it's a performance problem, shouldn't there be at least a flag to disable this check because in this situation it's nonsense when doing AoT?

**Comment by vicb** [comment]
> Hmm isn't Webpack supposed to care of this? Is Webpack involved at all when doing AoT?

It should (not sure about your config here).

The error message clearly indicates that the template parser tries to parse the untransformed pug:

```
Error: Template parse errors:
Error: Only support at most 9 interpolation values! ("[ERROR ->]h3 Home Component
p Welcome to Angular Seed
ul
```

> Are there any more elegant workarounds?

This is not related to angular but to your build setup / webpack. No clue, sorry !

> f If it's a performance problem, shouldn't there be at least a flag to disable this check because in this situation it's nonsense when doing AoT?

It's a **runtime** performance pb (vs a compile time perf).

`<p>pre{{ exp1 }}post{{ exp2}}</p>` generates vaguely this code: `p.innerHtml = "pre${exp1}post${exp2}"` - generating an undefined number of args would required a for loop which is less perfomant _(the requirement for the `for` loop is not obvious on this pseudo code but you get the idea)_

**Comment by freezy** [comment]
> It's a **runtime** performance pb (vs a compile time perf).

Yes, only that in this case it isn't because `li {{ foo }} li {{ foo }}` becomes `<li>{{ foo }}</li><li>{{ foo }}</li>` after running through Pug. So Angular **falsely** identifies it as a runtime problem because it doesn't know it's yet to be processed by Pug. Hence a flag would be handy.

> This is not related to angular but to your build setup / webpack. No clue, sorry !

Well that's why I took the official Angular2 seed project to reproduce. I think at that point we can safely assume that it's a build problem, but since this comes from the official repo I was hoping for a more distinguished answer since I surely won't be the only one stumbling across this. ;)
