### ISSUE TITLE
RangeError: Maximum call stack size exceeded (caused by adding a table)

### ISSUE THREAD

**Issue by Methodician** [angular/angular#12668]
**I'm submitting a ...**
```
bug report
```

**Current behavior**
Introducing a table causes the application to crash after showing about 100 
> core.umd.js:717 Uncaught RangeError: Maximum call stack size exceeded

**Expected behavior**
A component should display a table without issue.

**Minimal reproduction of the problem with instructions**
Tested a few times using the "Visual Studio 2015 Quickstart" found here: https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html 

I'm using the Web API template and running the app through an ASP.Net MVC Razor View rather than a blank project but don't think that's related.

Simply created a new app, checked that it was working, then added a table such as this from W3:
```
<table>
    <tr>
    <th>Firstname</th>
    <th>Lastname</th> 
    <th>Age</th>
    </tr>
    <tr>
    <td>Jill</td>
    <td>Smith</td> 
    <td>50</td>
    </tr>
    <tr>
    <td>Eve</td>
    <td>Jackson</td> 
    <td>94</td>
    </tr>
</table>
```
Removing the table re-stabalizes the app. Adding it back in crashes the app. No way to move forward and my boss is angry >,<

**What is the motivation / use case for changing the behavior?**
Need to be able to display basic tables in most web applications...

**Please tell us about your environment:**

- Windows 10
- Visual Studio 2015 Update 3
- Node v6.9.1
- NPM v3.10.5
- Typescript for Visual Stodio 2015 2.0.6.0

Nothing else special except JetBrains ReSharper installed

I'm using the Web API template and running the app through an ASP.Net MVC Razor View rather than a blank project but don't think that's related.

* **Angular version:**
"~2.1.2"

* **Browser:**
[ Chrome | Edge ]
 
* **Language:**
TypeScript 2.0.6.0

**Comment by DzmitryShylovich** [comment]
Pls add a minimal repro in plunkr.

**Comment by Methodician** [comment]
@DzmitryShylovich - I'm not sure I can do that.

I haven't done much on plunkr and, from what I understand, I cannot replicate the environment. I did give it a go but the error was not reproduced. I am literally doing nothing more than creating a new app then adding a table to the app, given the environment and process described in my post with no un-mentioned deviation from the process at https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html

Perhaps someone can help me figure out if it's possible to reproduce the error on plunkr.

**Comment by DzmitryShylovich** [comment]
Sorry, but if u cannot reproduce it in plunker then it's not an angular issue and it's not actionable.

**Comment by Methodician** [comment]
I cannot reproduce it but maybe it's reproducible. The bug definitely correlates with the most recent iteration of Angular though that by no means proves causation.

In any case, I had the impression that Visual Studio and ASP.Net developers mattered to the Angular team. Never heard of a plunker developer. I'll continue to search for the root of the problem. I guess it's likely either Visual Studio or the quickstart guide on the Angular website but I'm not aware of anything unusual on my end.

**Comment by Methodician** [comment]
So, while I'm not a fan of Dzmitry's attitude, I found the problem. Sure enough not related to the Angular library. Turns out I had done one other silly thing - defined a component with the selector "table"...
