### ISSUE TITLE
Errors running ng-xi18n

### ISSUE THREAD

**Issue by spotnape** [angular/angular#12661]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When running the **ng-xi18n** command we encounter two different problems:

**1.** Our app.module.ts file contains a couple of function calls relating to redux. The process chokes with the following error:

> Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/***/src/app/app.module.ts, resolving symbol AppModule in C:/***/src/app/app.module.ts

This error can be circumvented by commenting out the function lines in app.module.ts.

**2.** We are using sass and the process errors with the following error on import statements:

> Error: Compilation failed. Resource file not found: C:/***/src/app/styles/common 

This error can be circumvented by commenting out all css import statements across the application.

With both situations corrected as indicated, the ng-xi18n process runs as intended.

**Expected behavior**
I would expect the ng-xi18n process to be able to handle these situations without causing a fatal error. Neither of them, when corrected, causes the resulting xlf file to be any different, so it seems that the process would be far more useful if it just swallowed these errors or maybe warned about them.

**Minimal reproduction of the problem with instructions**
Put a function call in app.module.ts, or an import statement in a scss file, when using sass, to see these errors.

**What is the motivation / use case for changing the behavior?**
Not really a change of behaviour - just an improvement to a very useful feature.

**Please tell us about your environment:**
- Windows 7 64bit + Cygwin
- Visual Studio Code
- npm
- angular-cli / webpack project - everything very current

* **Angular version:**
2.1.1

* **Browser:**
Not relevant
 
* **Language:**
TypeScript 2.0.2
ES6/7

* **Node (for AoT issues):**
v6.2.2

**Comment by NagRock** [comment]
For 1st there is workaround to replace anonymous/arrow function with exported functions. But this is just workaround and should be fixed.

**Comment by vicb** [comment]
ng-xi18n used to use the offline compiler. It is no more the case in the newest releases.

**Comment by NagRock** [comment]
@vicb what about reexported directives, is it fixed too?
https://github.com/angular/angular/issues/12506

**Comment by cbeldacap** [comment]
I'm trying it with ng2 final release and throws the same error output.

**Comment by serhiisol** [comment]
ng-xi18n uses OfflineCompiler which performs static analysis of your code and if it not aot-compatible it will throw an error

**Comment by cbeldacap** [comment]
the error is solved. I was using a MockBackend that was intercepting every HTTP call, including the ones to get `.json` files with **ng2-translate**.

The project's currently working and the module is working so fine and fast.
