### ISSUE TITLE
Dynamically add controls to reactive forms

### ISSUE THREAD

**Issue by natcohen** [angular/angular#12672]
[+] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 

**Current behavior**
The dynamically added controls are not responsive

**Expected behavior**
Dynamically added controls should behave like regular controls...

**Minimal reproduction of the problem with instructions**
In order to dynamically create the form with unknown objects (trying to solve [this limitation](https://github.com/angular/angular/issues/12219)), I've created the following recursive function:

    patchValue(form:FormBuilder, object){
        var iterate = (mForm:FormBuilder, mObject)=> {
            for (var key in mObject) {
                if (Array.isArray(mObject[key])) {
                    if(!mForm[key]){
                        mForm[key] = new FormArray([]);
                    }
                    iterate(mForm[key].controls, mObject[key]);
                }
                else if (typeof mObject[key] == 'string' || typeof mObject[key] == 'number' || typeof mObject[key] == 'boolean' || mObject[key] == null) {
                    if(!mForm[key]){
                        mForm[key] = new FormControl('');
                    }
                }
                else if (mObject[key] != null && typeof mObject[key] == 'object') {
                    if(!mForm[key]){
                        mForm[key] = new FormGroup({});
                    }

                    iterate(mForm[key].controls, mObject[key]);
                }
                else {
                    console.log(key);
                    console.log('undefined element');
                }
            }
        };
        iterate(form.controls, object);

        form.patchValue(object);
    }

What it basically does is going into the patched object and create controls in the form if they don't exist.

Here is a working [plunker](https://plnkr.co/edit/sTV9XBYxz27AgEQxuqwN?p=preview)

As you can see the name is created at the beginning and it works well (you can see the changes). However, the address controls are created dynamically. Try changing them and you will see that changes are not recorded.

**What is the motivation / use case for changing the behavior?**
I need to dynamically add controls to a reactive form

* **Angular version:** 2.1.2

* **Browser:** Chrome 54 (didn't test with the others)
 
* **Language:** Typescript 2

**Comment by DzmitryShylovich** [comment]
FromGroup has [addControl method](https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L869)

**Comment by natcohen** [comment]
@DzmitryShylovich Thanks! Got it working like this:

    patchValue(form:FormBuilder, object){
        var iterate = (mForm:FormBuilder, mObject)=> {
            for (var key in mObject) {
                if (Array.isArray(mObject[key])) {
                    if(!mForm[key]){
                      mForm.addControl(key, new FormArray([]));
                    }
                    iterate(mForm.controls[key], mObject[key]);
                }
                else if (typeof mObject[key] == 'string' || typeof mObject[key] == 'number' || typeof mObject[key] == 'boolean' || mObject[key] == null) {
                    if(!mForm[key]){
                      console.log(mForm);
                        mForm.addControl(key, new FormControl(''));
                    }
                }
                else if (mObject[key] != null && typeof mObject[key] == 'object') {
                    if(!mForm[key]){
                      mForm.addControl(key, new FormGroup({}));
                    }

                    iterate(mForm.controls[key], mObject[key]);
                }
                else {
                    console.log(key);
                    console.log('undefined element');
                }
            }
        };


        iterate(form, object);

        form.patchValue(object);
    }

or [plunker](https://plnkr.co/edit/2uOaMqS4CAsGKp9443Wu?p=preview)
