### ISSUE TITLE
Tour of Heroes tutorial app.component.ts moduleId property requirement

### ISSUE THREAD

**Issue by danstanger** [angular/angular#12673]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The tutorial app only displays a "Loading ..." message because moduleId property is missing.
**Expected behavior**

Documentation would instruct student to add moduleId property, and app would load correctly.
**Minimal reproduction of the problem with instructions**

After adding styleUrls property as described after the "The routerLinkActive directive" section in toh-pt5.html, the app only displays a "Loading ..." message. I see two problems here. First, the tutorial should be corrected, and second, some way of diagnosing this problem should be presented.
**What is the motivation / use case for changing the behavior?**

Tutorial problems make it harder to learn angular.
**Please tell us about your environment:**

Windows7, nodejs, npm.
* **Angular version:** 2.0.X

* **Browser:** [Chrome XX |  IE XX  ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls submit docs issues on https://github.com/angular/angular.io/issues
