### ISSUE TITLE
@angular/form: AbstractControl - build misses some abstract method declarations

### ISSUE THREAD

**Issue by akomm** [angular/angular#12680]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
npm build @angular/form:2.1.2 (others not checked) miss some [abstract method declarations](https://github.com/angular/angular/blob/2.1.2/modules/%40angular/forms/src/model.ts#L537-L547) for 
[AbstractControl](https://github.com/angular/angular/blob/2.1.2/modules/%40angular/forms/src/model.ts#L88). Implementing all abstract methods provided inside the declaration of the build still leads to errors like `this._forEachChild is not a function`. Implementing the missing - undeclared - abstract methods fixed the issues and made the custom control work.

**Expected behavior**
All abstract methods should be declared in the build.

**Minimal reproduction of the problem with instructions**
Install the npm package, check the abstract method declarations there, check them in source for the same version: missing in npm, available on source.

**Please tell us about your environment:**
* **Angular version:** 2.1.2
* **Browser:** all
* **Language:** Typescript 2.x

**Comment by DzmitryShylovich** [comment]
This is how `/** @internal */` works

**Comment by akomm** [comment]
<sarcasm>
That fixed the core problem
</sarcasm>

**Comment by kara** [comment]
As @DzmitryShylovich mentioned, these methods are intentionally not part of the public API.

**Comment by akomm** [comment]
Completely bypassed the whole point of this. Congrats
