### ISSUE TITLE
@angular/form  - controls: "throw if control missing" should be optional

### ISSUE THREAD

**Issue by akomm** [angular/angular#12686]
**I'm submitting a ...**
```
[x] feature request
```

**Current behavior**
[FormGroup.prototype.setValue](https://github.com/angular/angular/blob/2.1.2/modules/%40angular/forms/src/model.ts#L922) throws an exception, when the value provided contains fields not defined as a control of the group. 

**Expected behavior**
An option either for `setValue` and/or `FormGroup` (preferred) should allow value inputs with extra fields. When enabled, any extra fields in `value` which have no corresponding control should be silently ignored.

**Minimal reproduction of the problem with instructions**
This throws an exception `Cannot find form control with name: id.`:
```ts
let group = new FormGroup({
  name: new FormControl()
});

group.setValue({
  id:   'exception',
  name: 'ok'
});
```

**What is the motivation / use case for changing the behavior?**
When working with data from a backend there is rarely a case where you get data which exactly match any field in the `FormGroup`. Code like the following is required in many cases due to this restriction:
```ts
private createGroup(value: any) {
  let group = this.groupFactory();
  group.setValue(
    Object.keys(group.controls).reduce((acc, ctrlName) => {
      acc[ctrlName] = value[ctrlName];
      return acc;
    }, {})
  );
  return group;
}
```

**Please tell us about your environment:**
* **Angular version:** 2.1.2
* **Browser:** all
* **Language:** all

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/pull/10537

**Comment by akomm** [comment]
I'v understood the patchValue as `merge`. I'm checking if its behavior does match the requirement in any case. Thanks. Btw. was looking like crazy for an issue already existing ;)
