### ISSUE TITLE
ng1/ng2 dual router setup does not properly transition from ng1->ng2 pages when HTML5 navigation is enabled

### ISSUE THREAD

**Issue by bourey** [angular/angular#12690]
Under the current angular 2 build (on 2016-11-03), using the ng1 and ng2 routers together (via ngUpgrade) does not support page transitions from ng1 -> ng2 when HTML5 URLs are enabled.  ng1 pages always work, and ng2 pages work when loaded directly, or when navigating between ng2 pages.  If moving from an ng1 to an ng2 page, however, the ng2 URL results in a blank page.  This same code does work when using hash-based URLs.

When inspecting the DOM, it appears that the <router-outlet> element appears in the page, but is never expanded.  I also observed that under hash-based URLs ng2 router events fired for all page transitions (even including transitions from ng1->ng1), while under HTML5-based navigation the ng2 router events only fired when loading an ng2 page directly or when navigating between ng2 pages.  This seems likely to be the source of the empty <router-outlet> and blank page.

Repro instructions:
1. Check out https://github.com/bourey/ngupgrade-example/tree/html5
2. npm install
3. npm start
4. Visit http://localhost:3000, click "teams", and observe that no content appears in the page.
5. Constrast this to loading http://localhost:3000/teams directly, or using the link in the ng2 branch of the github project.

**Comment by vsavkin** [comment]
History.pushState does not fire onPopState, so the angular2 location object doesn't detect the change. The workaround is to attach a location change listener that will call navigate directly:

```
bootstrap(platformBrowserDynamic(), AppModule, document.body, footballApp).then((ref) => {
    console.log('Beginning initial navigation');
    const router = ref.injector.get(Router);
    router.initialNavigation();

    ref.$injector.get('$rootScope').$on("$locationChangeStart", (event:any, next:string, current:string) => {
      const url = document.createElement('a');
      url.href = next;
      router.navigateByUrl(url.pathname);
    });

    console.log('Initial navigation complete');
});
```

**Comment by vsavkin** [comment]
We should think about either creating an angular1-angular2 location bridge, so the two location services notify each other. Or at the very least providing a helper function to hide the workaround there.
