### ISSUE TITLE
location.go() doesn't notify the location.subscribe subject

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#12691]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
```
location.subscribe(event => console.log('location changed', event));
location.go('/foo');
```

Doesn't print anything, but window.location is changed.

**Expected behavior**

console.log should appear in console.

**Minimal reproduction of the problem with instructions**

```
export class AppComponent {
  constructor(private location: Location) {
    location.subscribe(event => console.log('location changed', event));
    location.go('/foo');
  }
}
```

* **Angular version:** 2.0.X
2.1.2 

* **Browser:** [Chrome 55]

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/browser/location/browser_platform_location.ts#L45

According to https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate :
> Note that just calling history.pushState() or history.replaceState() won't trigger a popstate event. The popstate event is only triggered by doing a browser action such as clicking on the back button (or calling history.back() in JavaScript). And the event is only triggered when the user navigates between two history entries for the same document.

**Comment by mcferren** [comment]
I'm getting "Property 'pushState' does not exist on type 'Location'."

is this fix just waiting for approval?

**Comment by curlyfro** [comment]
i'm also expecting a changed state after location.go().  where can i listen to these events?

**Comment by Predve4niy** [comment]
Same problem. 
Angular version 5.1.0.

**Comment by mlc-mlapis** [comment]
... you have to wait for PR https://github.com/angular/angular/pull/19463 which is still just only on the master.

**Comment by Fabian-Luque** [comment]
Hi,  i find that

`location.onUrlChange( (url: string, state: unknown) => {
        console.log("Location changes to "+url);
	console.log(state);
});`

**Comment by atscott** [comment]
As @DzmitryShylovich pointed out in https://github.com/angular/angular/issues/12691#issuecomment-264697166, this relates to the `popState` event not triggering. `onUrlChange` should be used instead https://stackblitz.com/edit/angular-ivy-router-base-17kggk?file=src%2Fapp%2Fapp.component.ts

This behavior is somewhat documented 
https://angular.io/api/common/Location#onurlchange
https://angular.io/api/common/Location#subscribe
but could use some revision to better address user expectations.

**Comment by kapunahelewong** [comment]
Docs team can refer to the material in this issue to update the API docs.
