### ISSUE TITLE
Help: <label for="{{val.id}}">{{ val.name }}</label>

### ISSUE THREAD

**Issue by ksphp** [angular/angular#12703]
## Help: <label for="{{val.id}}">{{ val.name }}</label>

for="{{val.id}}" ?

```
<span *ngFor=" let val of param.parameter ">
    <input type="radio" id="{{ val.id }}" name="time" value="{{ val.val }}" class="ui-radio" />
    <label for="{{ val.id }}">{{ val.name }}</label>
</span>
```

**Comment by michalstepien** [comment]
[attr.for]="val.id"  ?

**Comment by zoechi** [comment]
For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
@michalstepien is correct here, going to close this one as a support request. 

BTW, this is another case for #10546
