### ISSUE TITLE
View doesn't actually implement ChangeDetector

### ISSUE THREAD

**Issue by mprobst** [angular/angular#1270]
ts2dart supports `@IMPLEMENTS`, which leads us to this error message from dartanalyze:

```
dist/dart/angular2:[warning] Missing concrete implementation of 'ChangeDispatcher.onRecordChange' (/Users/martinprobst/src/angular/dist/dart/angular2/lib/src/core/compiler/view.dart, line 50, col 7)
```

I'm not sure what part of the code is wrong, could be either View or ChangeDetector, but I suspect View. @vsavkin for comments on the change detector.

**Comment by vsavkin** [comment]
@mprobst I've fixed it here https://github.com/angular/angular/pull/1272
