### ISSUE TITLE
Location, LocationStrategy, APP_BASE_HREF can't be injected anymore without explicitly providing them

### ISSUE THREAD

**Issue by zoechi** [angular/angular#12704]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

No provider found if one of `Location`, `LocationStrategy`, `APP_BASE_HREF` are injected without explicitly providing them

**Expected behavior**

The default values Angular uses should be injected

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/oCyMHxJ1XLrgDfvh8yNU?p=preview

Commenting in the `provider` line makes it work but by default `PathLocationStrategy` is used and should be provided by default

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Only tried in Plunker in Chrome Version 55.0.2883.28 beta (64-bit)

* **Angular version:** 2.0.X

The version Plunker fetches 2.1.2 or 2.2.0-rc.0 (don't know)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Only tried in Plunker in Chrome Version 55.0.2883.28 beta (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
They are provided by `RouterModule.forRoot`

**Comment by zoechi** [comment]
@DzmitryShylovich thanks. 
I'm going to close it. I expected at least `Location` to work without the router though.
