### ISSUE TITLE
Templates unnecessarily transform `undefined` to `null`

### ISSUE THREAD

**Issue by wwoods** [angular/angular#12700]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you have a template with e.g. `<div *ngIf="s !== undefined && s.i > 0"></div>`, the compiler seems to silently transform the `undefined` into a `null`, which breaks the template if `s` was, in fact, `undefined`.

**Expected behavior**
`undefined` should be translated as `undefined`, and `null` should stay `null`.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/TVqp0F8IU9RRGxgqW6z5?p=preview (thanks for the template, very helpful).

**What is the motivation / use case for changing the behavior?**
Javascript has always had `undefined` and `null` as separate objects.  It makes no sense to combine them in the template language unnecessarily.

**Please tell us about your environment:**
Fails on plnkr.

* **Angular version:** 2.0.X

* **Browser:** all
 
* **Language:** all?

**Comment by ericmartinezr** [comment]
Can you check if your issue is related to / dup of https://github.com/angular/angular/issues/11493 ? If that's the case then there's already a fix for it over here https://github.com/angular/angular/pull/11503. If it isn't, ignore this comment.

**Comment by wwoods** [comment]
Ah, yes, did not find those when looking.  That is exactly the issue (and
presumably the fix).
