### ISSUE TITLE
Change detection falls behind on IE9

### ISSUE THREAD

**Issue by gary-b** [angular/angular#12701]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you have multiple inputs on the page using FormControlName directives, and output the value of each on the view, changes are not reflected under certain circumstances. (Walk-through in the plunker)

**Expected behavior**
The view correctly shows the values in the text boxes.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/#!/ESQJQMrrd8gZ9GkOfZFV?p=preview

**What is the motivation / use case for changing the behavior?**
Broken.

**Please tell us about your environment:**
Windows 7 (the free vm Microsoft gives out for browser testing)

* **Angular version:** 2.0.X
2.1.2

* **Browser:** 
IE9
 
* **Language:** 
TypeScript

**Comment by AndrewKushnir** [comment]
Hi @gary-b, IE 9 and IE 10 support is deprecated in Angular v10 and support for these browsers will be removed in v11, [more info can be found here](https://next.angular.io/guide/deprecations#ie-9-10-and-ie-mobile-support). I will close this ticket, feel free to create a new one if you come across similar problems in other browsers using latest Angular version. Thank you.
