### ISSUE TITLE
Allow hexadecimal (and octal and binary) literals in expressions

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#12716]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Trying to bind a hexadecimal literal breaks the compiler.

```
Unexpected token 'x2A' at column 2 in [{{0x2A}}]
```

**Expected behavior**

We should be able to do `{{0x2A}}`. It would still print its decimal counterpart `42`, of course (as expected from `console.log(0x2A)` or any REPL). Of course, not just `{{}}`, but also things like `[data]=[0x2A, 0x2B]`.

Since we're at it, [ES6 also supports `0b` for binary and `0o` for octal](http://es6-features.org/#BinaryOctalLiteral), so that'd also be nice.

**Minimal reproduction of the problem with instructions**

[Plunker is here.](http://plnkr.co/edit/ClGjQm2unS45BbT3127A?p=preview) 

**What is the motivation / use case for changing the behavior?**

Perfectly normal thing to do. Eg. building memory simulator/visualisations.

* **Angular version:** 2.x

* **Browser:** all

* **Language:** all

**Comment by JoostK** [comment]
It was decided in https://github.com/angular/angular/pull/22289#issuecomment-738413236 not to support these syntax forms, so I'm closing this request.
