### ISSUE TITLE
Will native i18n supports in Angular 2 work for Angular 1.x?

### ISSUE THREAD

**Issue by eastenluis** [angular/angular#12711]
Hi, we are using angular 1.4.7 and we need to have a translated version fairly soon. But we are not ready (and don't have enough time) to migrate to 2.0 yet. I am wondering if the native angular i18n tools can be used for angular 1.x too, so when we do migrate from 1.x to 2 there won't be a massive change in the translation part. Thanks!

**Comment by vicb** [comment]
> I am wondering if the native angular i18n tools can be used for angular 1.x too

No, sorry

We can probably figure out a way to ease the transition, I guess other people will need this.

Please re-open when you have something ready to be migrated

/cc @petebacondarwin
