### ISSUE TITLE
Calling this.router.navigate does nothing when coming from a child component EventEmitter

### ISSUE THREAD

**Issue by meakyl** [angular/angular#12714]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Calling this.router.navigate does nothing when coming from a child component EventEmitter.

**Expected behavior**

this.router.navigate should navigate to the given url
**Minimal reproduction of the problem with instructions**

I extracted the impacted code :

HTML :
```
<div (click)="back($event)" />

<div class="row" *ngIf="myList">
    <div class="col-sm-6 col-md-4 col-lg-3" *ngFor="let item of myList>
        <person-card
            [id]="item.id"
            (clickEvent)="back($event)"
        ></person-card>
    </div>
</div>
```
The callback in the component (I have the router injected in the constructor of course)
```
public back(event?: Event) {
	this.router.navigate(["/home"]);
}
```
The person-card component
```
@Component({
    moduleId: module.id,
    selector: "person-card"
})
export class PersonCardComponent {
    @Output() public clickEvent = new EventEmitter();
    @Input() public id: string;

    public onClick() {
        this.clickEvent.emit(this.id);
    }
}
```
person-card html :
```
<div class="panel-body" (click)="onClick()" />
```

As you can see, I call the back() function twice from the html.
If I click on the first div, back() is called and the routing works perfectly.
If I click on the person-card component div, back() is called but the routing doesn't do anything and I have no error in the console.

I guess it's a bug but maybe I'm doing something wrong.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.1

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by meakyl** [comment]
http://plnkr.co/edit/70ZFRPJdAraDDV8heMlo?p=preview
I have made this plunkr but for some reason I can't make the router work with router.navigate from a (click) event. It works in my project so I must have missed something.

**Comment by zoechi** [comment]
Sounds like the code that emits the value on the `EventEmitter` runs outside Angulars zone `seems to be caused by (clickEvent)`. This way Angular doesn't run change detection afterwards which causes the effect that router.navigate doesn't properly update the page.

**Comment by meakyl** [comment]
That's the first thing I tried but it's not working when running into the zone.

The problem was that I had a div with a routerLink bound to an empty array next to my click event.
If you have both [routerLink] and (click) set on a div, the click callback will be called but the router.navigate won't work.

**Comment by vicb** [comment]
@meakyl please close your issues next time they are resolved, thanks !
