### ISSUE TITLE
whenStable should throw an exception if it is called outside an async or fakeAsyncZone

### ISSUE THREAD

**Issue by vikerman** [angular/angular#12721]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Developer writes a synchronous test without whenStable. Realizes they need whenStable by the exception thrown by detectChanges(See #12718). Adds a whenStable but forgets to update the test method wrapper to use async() (or fakeAsync if that's what they really want). The test would complete before the whenStable().then is completed.

**Expected behavior**
whenStable throws an exception if it is not invoked from AsyncTestZone or FakeAsyncTestZone.

cc @juliemr  @wardbell

**Comment by Goodwine** [comment]
When this gets implemented, will the test complain if it's called from a "jasmine async" function?
eg. using `(done) => {}` instead of `async(() => {})`

**Comment by DzmitryShylovich** [comment]
@vikerman afaik `whenStable` already throws when called outside `fakeAsync`

**Comment by thw0rted** [comment]
Is this issue still relevant?  If I understand correctly, the latest Zone patches make everything run inside the test Zone, so `whenStable` is able to do its thing even if you're not currently inside a `waitForAsync` call.  For example, I grabbed the [StackBlitz linked from the test docs](https://stackblitz.com/angular/nnvnepvjlxl) and edited `dashboard.component.spec.ts` to un-wrap the `beforeEach` call on line 114, and return the chained Promise instead:

````ts
beforeEach(() => {
  router = fixture.debugElement.injector.get(Router);
  fixture.detectChanges(); // runs ngOnInit -> getHeroes
  return fixture
    .whenStable() // No need for the `lastPromise` hack!
    .then(() => fixture.detectChanges()); // bind to heroes
});
````

(If you return a promise-like, Jasmine always waits for it to resolve.) All the tests still pass, and changing one of the tests to be wrong (e.g., expect `heroes.length` to be 10) fails as it should.  Of course, if there's a `whenStable` in the middle of the callback without an `await` or a `then` chain, the following code will be executed without waiting for it, but that's true of any asynchronous code.
