### ISSUE TITLE
Eventemitter execution losing focus on html interactive element

### ISSUE THREAD

**Issue by srkarya** [angular/angular#12723]
An Eventemitter execution is making the interactive element focus to be lost and it would not work by explicitly setting the focus on the same element where it begun. We are using [attr.aria-] attributes for screen readability. Event emitter seems to break the flow of tabbing the elements on events like blur, keyup... 
angular version - 2.0.0-rc.3

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
