### ISSUE TITLE
ngc should work with `rootDir` that does not include `node_modules`

### ISSUE THREAD

**Issue by PFight** [angular/angular#12725]
Original title: ngc ignores 'exclude' option in tsconfig and compiles node_modules

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

ngc ignores `exclude` option in [tsconfig](https://github.com/PFight/ngc-exclude-bug/blob/master/tsconfig.ngc.json), and compiles all in `./` dirrectory, including everything in `node_modules`.

**Expected behavior**

If [tsconfig](https://github.com/PFight/ngc-exclude-bug/blob/master/tsconfig.ngc.json) contains `exclude` option, it should be taken in account.

**Minimal reproduction of the problem with instructions**

[https://github.com/PFight/ngc-exclude-bug](https://github.com/PFight/ngc-exclude-bug)

    npm install
    "./node_modules/.bin/ngc" -p tsconfig.ngc.json

See [aot](https://github.com/PFight/ngc-exclude-bug/tree/master/aot) directory for compilation result.

**What is the motivation / use case for changing the behavior?**

1. AOT compilation takes too many time, because all contents of node_modules scanned and compiled.
3. If not specify genDir, content of node_modules changes (added ngfactory.ts files).
2. Referneces to compiled ngfactory.ts classes from project source created. So, these files can't be removed, they should be included in compilation. During typescript compilation we get errors like `error TS6059: File 'C:/Main/Work/angular-seed/node_modules/@angular/common/src/directives/ng_for.ngfactory.ts' is not under 'rootDir' 'C:/Main/Work/angular-seed/app-prod-compile'. 'rootDir' is expected to contain all source files.`

**Please tell us about your environment:**
Windows 8.1, Git Bash 2.10.2, npm 3.10.8

* **Angular version:** 2.0.X
2.1.2
 
* **Language:** [TypeScript 2.0.6]

* **Node (for AoT issues):** `node --version` =  6.9.1

**Comment by vicb** [comment]
> because all contents of node_modules scanned and compiled.

Is it really **all contents** or only the Angular modules referenced from your application.

The latter case is expected: Libs on have to ship their metadata files and the actual compilation (template to code) is done by ngc. A big advantage of this is that as the Angular compiler improves (in term of speed/size of the generated output) your apps will automatically benefits from the improvements across all the libs.

First ngc turns might be long but subsequent ones will only recompile what's needed and should be faster.

**Comment by PFight** [comment]
Yes,  only ones that referenced by my sources. It is strange, that angular do not ships with ngfactory already compiled... Why user should aot-compile angular directives by himself? Should I distribute my directives also without ngfactory classes, leaving it to users? Are there some reasons, why distribution of pre-compiled ngfactory-stuff is not possible?

When I discovered, that ngc changes contents of node_modules I got feeling, that something is going wrong. But, if it is by design, then all ok.  

Now I made up with specifying genDir `aot` where two folders created by ngc - `aot\app` and `aot\node_modules`, containing compiled ngfactory, so content of 'node_modules` keeps untouched.

**Comment by tbosch** [comment]
`ngc` will compile anything TypeScript would also compile. Could you try this by just calling `tsc` on the same `tsconfig.json`?

**Comment by PFight** [comment]
Yes, that's why @angular everyone ships only d.ts and compiled .js (without .ts). Otherwise every time it will be needed to change content of node_modules, compiling these .ts files, and getting that error `File ... is not under 'rootDir'`. By analogy, @angular should ships with already generated .ng-factory.d.ts and compiled .ng-factory.js files I think. It's the core problem (`ngc` itself have correct behaviour, as we found earlier in this discussion).

**Comment by CSchulz** [comment]
@tbosch Is there any argument against ng-factory files in the npm packages?

**Comment by kylecordes** [comment]
@CSchulz In other threads I've seen the following explanation, I think from core Angular team members. If packages shipped their .ngfactory files already generated, there would be these problems:

* Those packages would not benefit from further improvements to AOT, without also bringing out a new version of the package.
* AOT would need to generate code which works across version sku, in order to respect semver. this would be a frequent and problematic restriction.

The way it works now, where you always AOT at the project level rather than the library level, you can consume a library written with Angular 2.3.3 or whatever, even if your project is using Angular
2.4.5 (somewhat different AOT output) or Angular 4.x (very different AOT output).

**Comment by CSchulz** [comment]
I think there is no problem any more with including aot files regarding the new data format of Angular 4.

See http://angularjs.blogspot.de/2017/03/angular-400-now-available.html and especially https://docs.google.com/document/d/195L4WaDSoI_kkW094LlShH6gT3B7K1GZpSBnnLkQR-g/preview

**Comment by CSchulz** [comment]
@tbosch any explanation why it is closed? Is it fixed?

**Comment by tbosch** [comment]
@CSchulz 

Why we don't want users to ship `.ngfactory` files for now:
These files use internal APIs of angular, which we are still evolving. If users shipped these files, their components would only work with a specific angular release (specific down to the patch release).

However, we are working on having a stable internal API, and once we have this, we will actually switch the recommendation to ship the generated code. Even more, we are working on changing ngc to automatically inline the generated code into the regular `.js` files, removing the `.ngfactory` files all together.

**Comment by tbosch** [comment]
Regarding this bug: 
- using `exclude` is wrong, as we do want to compile the `node_modules`, as they don't ship generated code (as explained above)
- we should support this scenario of having a `rootDir` that does not include `node_modules`..

**Comment by Dashue** [comment]
I believe I'm hitting this as well and I've no idea how to work around it. Depending on a library from node_modules and importing some types from it. Is this an issue with the library I'm depending on, my project or angular?

**Comment by PFight** [comment]
@Dashue all code to compile (ts files) should be under rootDir. If you are using AOT, you should specify genDir, so ng-factory.ts files would be copied into some folder under rootDir. If library you use provides sources (ts-files) instead of js + d.ts you should copy these files to some location under rootDir. So, your code sould not import any ts-files from node_modules, only d.ts.

**Comment by smackfu** [comment]
We are currently upgrading from angular 4.3 to angular 5.2 and I spent a long time today figuring out that having a rootDir set was the root cause of our AOT build failing.  The only way I solved the issue was by reverting each line of our webpack/tsconfig/etc. configuration until the build started working.  It was very painful for what was supposed to be an easy upgrade.

The reported error from AngularCompilerPlugin was almost completely useless to finding the root cause:
```
ModuleNotFoundError: Module not found: Error: Can't resolve '../node_modules/ngx-toastr/index.ngfactory' in '/Users/bsmcinty/workspace/test/src'
...
resolve '../node_modules/ngx-toastr/index.ngfactory' in '/Users/bsmcinty/workspace/test/src'
  using description file: /Users/bsmcinty/workspace/test/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
```
Improving this scenario would be nice.

**Comment by errorx666** [comment]
@smackfu Thank you, I've been trying to debug this error for TWO MONTHS!

**Comment by gatimus** [comment]
Ignoring `exclude` is problematic for multiple apps, with shared code.

 https://github.com/gatimus/multiple-apps-lazy-loading run `ngc -p .\src\tsconfig.app-a.json`

Output has `app-b` but `tsconfig.app-a.json` has `"exclude": [ "app-b/" ]`

**Comment by JoostK** [comment]
This is no longer an issue today.

In @william-lohan's case, "app-b" is still compiled because the file "main-app-b.ts" is part of the compilation, so any referenced files will be compiled. This is as intended. The `noResolve` TS compiler option can be set to `true` in order to disable automatic inclusion of referenced files, but I would not recommend using it.
