### ISSUE TITLE
RXJS RC or Final Upgrade

### ISSUE THREAD

**Issue by giovannicandido** [angular/angular#12735]
This issue is to track the upgrade of rxjs to its final release.
As for today the packages:

@angular/core@2.1.2 
@angular/router@3.1.2 
@angular/http@2.1.2

Require rxjs@5.0.0-beta.12 which prevents us for using rc.2 (current version of rxjs) in your projects.

**Comment by mike-co** [comment]
Why was this issue closed and down-voted? rxjs is on 5.0.0-rc.3 version, while angular2 still relies on 5.0.0-beta.12. As a lot of code is based on using the Observables, keeping up to date with the bug fixes in rxjs will be good.

**Comment by giovannicandido** [comment]
Maybe they are waiting for final release. 

The big headache is that angular requires a specific version, instead of a range. I suppose because of breaking changes.

But I don't know why they close and rejected that issue, instead of put in a milestone.

**Comment by mmc41** [comment]
@vicb I think this is a reasonable issue. Why closing it without comment?
