### ISSUE TITLE
CanDiactivate guard gets null component

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular#12739]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/pYVPlWzNfNwS2efWKdFi?p=preview
Click 'Parent/Child', then click 'Home', see console, you will see 'null'.

CanDeactivate guard receives null component, but I expected it to be a real reference. 
If remove 'repo' segment from routes it will be all good.
I think the cause is in a componentless parent node.

````
export const ROUTES:Routes = [
    {
        path:'',
        component:Main
    },
    {
      path:'repo',
      children:[{
          path: 'parent',
          component: Parent,
          children: [
              {
                  path: 'child',
                  canDeactivate:[CanDeactivateGuard],
                  component: Child
              }
          ]
      }]
    }
  ]

````

**Comment by DzmitryShylovich** [comment]
See https://github.com/angular/angular/issues/12592#issuecomment-258136935

**Comment by olegdunkan** [comment]
@DzmitryShylovich yes, probably #12592 is connected to this issue if we suppose that first deactivated segment for Child (in my case) is absent ).

**Comment by vsavkin** [comment]
Fixed https://github.com/vsavkin/angular/commit/9245e9ec4f4fbb9fec8f0f2e643e3e8cf6e2d3ab
