### ISSUE TITLE
Bug on 2.2.0-rc.0: The change detection doesn't kick in for *ngFor array data change.

### ISSUE THREAD

**Issue by derekshi** [angular/angular#12733]
Issue relates to ng2-toastr: https://github.com/PointInside/ng2-toastr/issues/80

ToastContainer has template: 
```
<div *ngFor="let toast of toasts" [@inOut]="animate" class="toast toast-{{toast.type}}" 
      (click)="clicked(toast)">...</div>
```

When new `toast` object is added to `toasts` array, the template doesn't reflect changes until I manually call `changeDetectorRef.detectChanges()`. It used to be working in version 2.1.2 and earlier.

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by derekshi** [comment]
Before I create an example on http://plnkr.co, I want to add: The change detection not happening on dynamically created component. The above `TaostContainer` was created using `ViewContainerRef.createComponent`.

**Comment by vicb** [comment]
Please re-open an issue when you have a repro. Thanks.
