### ISSUE TITLE
Angular2 is not compatible with the stock browser of the Android 4.1.1 and 4.2 and 4.2.2 and 4.3

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#12737]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I try to load my website(not public yet) on the stock browser of the Android 4.1.1 or 4.2 or 4.2.2 or 4.3 system, the site is not finishing the loading. It's even better that the browser is crashing when visiting https://angular.io/ and selecting the Features menu item.

**Expected behavior**
Sites loads just fine.

**Minimal reproduction of the problem with instructions**
Issue1:
1. Open any kind of example on plunker for Angular2 using the stock browser
2. Run them.

Issue2:
1. Open https://angular.io/ in the stock browser
2. Select the Features menu item.

**Please tell us about your environment:**

Android 4.1.1 running in Genymotion
Android 4.2 running in Genymotion
Android 4.2.2 running in Genymotion
Android 4.3 running in Genymotion

* **Angular version:** 2.0.X
Most recent stable angular2 version: 2.1.2

* **Browser:** Android 4.1.1 Web Browser, Android 4.2 Web Browser, Android 4.3 Web Browser

**Comment by DzmitryShylovich** [comment]
https://angular.io/ is written in angular1

**Comment by DavidGangel** [comment]
Added 4.3 as well. Same behaviour as with 4.1.1.

**Comment by vicb** [comment]
> https://angular.io/ is written in angular1

or not yet written in ng2.

Angular2 tests run (and pass) on Android browsers.

**Comment by DavidGangel** [comment]
Android tests are running on 4.1 and 4.1 is not on this list...
AFAIK they not run on the systems that I described.
Please reopen or investigate.

Thank you.

**Comment by DavidGangel** [comment]
@mhevery would it be possible to test this issue manually by others on the affected platforms to see it's a valid issue or not?
I used the Genymotion emulator in factory state on 2 machines and have the same result.
It would be worth to check as the listed versions have ~15,6% market share from the Android ecosystem.

**Comment by DavidGangel** [comment]
I did run a test inside the original Android Emulator with Android 4.2 (factory state with google APIs)
Got the exactly same result as described here.

**Comment by mlaval** [comment]
Using an Android 4.3.1 emulator, I can reproduce the crash of https://angular.io/, please open an issue at https://github.com/angular/angular.io

Angular 2 is fully tested in these browsers on SauceLabs. Here are a few websites which loads successfully:
https://mlaval.github.io/optimize-angular-app/lazyloading-webpack/
https://ng-bootstrap.github.io
Please make sure to load the right polyfills in your application: https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by DavidGangel** [comment]
@mlaval thank you for your help.
Angular.io issue created under: [#2766](https://github.com/angular/angular.io/issues/2766)
Checking the polyfills.

**Comment by DavidGangel** [comment]
@mlaval I checked but I can not see what do I missing.
I'm having a very simple app with few modules from Angular:
```
{
  "jspm": {
    "dependencies": {
      "@angular/common": "npm:@angular/common@^2.1.2",
      "@angular/compiler": "npm:@angular/compiler@^2.1.2",
      "@angular/core": "npm:@angular/core@^2.1.2",
      "@angular/platform-browser": "npm:@angular/platform-browser@^2.1.2",
      "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@^2.1.2",
      "@angular/router": "npm:@angular/router@^3.1.2",
      "angular2-google-maps": "npm:angular2-google-maps@^0.15.0",
      "core-js": "npm:core-js@^2.4.1",
      "reflect-metadata": "npm:reflect-metadata@^0.1.8",
      "rxjs": "npm:rxjs@5.0.0-beta.12",
      "zone.js": "npm:zone.js@^0.6.26"
    },
    "devDependencies": {
      "@types/core-js": "npm:@types/core-js@^0.9.34",
      "@types/node": "npm:@types/node@^6.0.46",
      "typescript": "npm:typescript@^2.0.7"
    }
  }
}
```

In my indext.html I have this:
```
<script src="/skins/node_modules/core-js/client/shim.min.js"></script>
<script src="/skins/node_modules/zone.js/dist/zone.js"></script>
<script src="/skins/node_modules/reflect-metadata/Reflect.js"></script>
<script type="text/javascript" src="/skins/jspm_packages/system.src.js"></script>
			
<script>System.config({ baseURL: '/skins' });</script>
<script type="text/javascript" src="/skins/config.js"></script>
<script>System.import('dist/app/main.js');</script>
```

AFAIK in such a simple case the shim.min.js should be enough to run the app, but this is not the case, or something is wrong.

**Comment by DavidGangel** [comment]
Maybe I found something.
Will get back soon.

**Comment by DavidGangel** [comment]
I have checked the console log inside the Android browser and have found the following:
```
node_modules/zone.js/dist/zone.js:388
Unhandled promise rejection:
node_modules/zone.js/dist/zone.js:390
Error: Uncaught (in promise): Error:
(SystemJS) Window is not defined at eval(native)
Evaluating /dist/app/skins.module.js
Evaluating /dist/app/main.js
Error loading /dist/app/main.js
(SystemJS) Window is not defined
ReferenceError: Window is not defined at eval(native)
Evaluating /dist/app/skins.module.js
Evaluating /dist/app/main.js
Error loading /dist/app/main.js
```

Does someone has any idea what causing this?

**Comment by ozknemoy** [comment]
same story on Android 4.1 . only mozilla and chrome work. but https://ng-bootstrap.github.io/#/home works.

**Comment by ozknemoy** [comment]
my console show
1) INVALID_STATE_ERR: DOM Exception 11 (may be it related to  value inputs)
2) __extends is not defined (strange but code has this variable)

**Comment by ozknemoy** [comment]
to fix this i did:
1) ignored INVALID_STATE_ERR: DOM Exception 11
2) fix __extends issue (https://github.com/akveo/ng2-smart-table/issues/26)( noEmitHelpers didnt help me and i used helpers as temporary fix from that page
3) added polyfill for proxy
4) delete console.clear(...) from my build
