### ISSUE TITLE
pseudo classes selectors on :host element don't works correctly after angular updating 2.0.0 -> 2.1.1

### ISSUE THREAD

**Issue by holiber** [angular/angular#12730]
bug from #12451 discussion

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have component with 'active' class on :host

```ts
@Component({
  selector: 'my-component',
  template: '<div>My component</div>',
  styleUrls: ['./my-component.component.css']
})
export class MyComponent {
  @HostBinding('class') componentClass = 'active';
}
```
my-component has styles:
```css
:host:after {
  content: 'Component is not active';
  color: red;
}

:host.active:after {
  content: 'Component is active';
  color: green;
}
```

in angular 2.1.1 component shows wrong result:

![image](https://cloud.githubusercontent.com/assets/3768346/20029757/7ed64e60-a366-11e6-957d-1a18f2a93334.png)

**Expected behavior**
In angular 2.0.0 all is ok:

![image](https://cloud.githubusercontent.com/assets/3768346/20029769/a8c8d6f2-a366-11e6-89b7-de3e570263d3.png)

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/4xgwW5D8ZqhlHB06MXsQ?p=preview

**Please tell us about your environment:**

MacOSX 10.11, Node v6.9.1

* **Angular version:** 2.1.1

* **Browser:** [all ]

 
* **Language:** [TypeScript 1.8]

* **Node (for AoT issues):** `node --version` =  v6.9.1

**Comment by borislemke** [comment]
Same problem in similar case:
```
:host {

    &.outline {

        &:before {
            ...some styling stuff
        }
    }
}
```
will compile to:
```
.outline:before[_nghost-hyp-13] {}
```

where it should:
```
[_nghost-hyp-13].outline:before
```
