### ISSUE TITLE
Host metadata bindings no longer work on root components

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular#12744]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request 
```

**Current behavior**
If I specify a host binding via `@Component` metadata (rather than an `@HostBinding` decorator), it doesn't seem to get applied when the component in question is the root component. `@HostBinding` still seems to work. Pretty sure this worked properly in 2.1.1.

**Expected behavior**
Bindings specified in metadata should be applied.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/95rVxaPE6VG6q3ISsMJR?p=preview

**What is the motivation / use case for changing the behavior?**
Worked in 2.1.1, should work now. I don't need this for my app component, but it's thrown a wrench in my component unit tests that use `TestBed.createComponent()`, since the component is created as the root and thus my tests of the bindings fail.

**Please tell us about your environment:**

* **Angular version:** 2.1.2

* **Browser:** Chrome
 
* **Language:** TS

**Comment by pkozlowski-opensource** [comment]
I can confirm this one, it makes https://github.com/ng-bootstrap/ng-bootstrap test fail as well. @tbosch is this something that was changed "by design" or just a side-effect of recent refactorings? 

IMO this one could qualify as a regression as we shouldn't be doing breaking changes in 2.x and this is a breaking changes for some of the existing tests.

**Comment by tbosch** [comment]
Yes, this is a regression!
We need to apply the attributes also when we use an element provided by the user in https://github.com/angular/angular/blob/master/modules/@angular/core/src/linker/view_utils.ts#L360
