### ISSUE TITLE
Add feature to Injector that makes all classes Injectable by default

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/angular#12745]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, you have to add an `@Injectable()` decorator for every class where you want the params in the constructor to be automatically resolved when that class is instantiated by the injector. The problem with this is that it is crazy annoying when you have bought into the idea that EVERYTHING should be a class which is ultimate used as a singleton. I don't use classes for anything other than defining a type and as a vehicle for DI. Therefore, I literally need `@Injectable` on every one of my custom classes. 

**Expected behavior**

My desired behavior is to set a flag when I create the main Injector which makes all classes Injectable so I don't need to actually put the `@Injectable` decorator. Perhaps as a safety net we add a `NotInjectable()` decorator which prevents injection when this flag is turned on (though this second part is unnecessary for my particular use case). When NgModule is being used, you should be able to set this flag within the NgModule decorator.

**Minimal reproduction of the problem with instructions**

N/A

**What is the motivation / use case for changing the behavior?**

Besides my use case where I know what I am doing and I truly want every class to be injectable, this would remove a common pitfall I see many newbies run into when they first start trying Angular 2. Also, there is a really nice aspect to being able to write service code without any reference to any Angular code which can be used by Angular apps.

**Please tell us about your environment:**

N/A

* **Angular version:** 2.0.X

2.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X 

N/A
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript

* **Node (for AoT issues):** `node --version` =   

N/A

**Comment by frederikschubert** [comment]
The decorator is just there to force typescript to emit the metadata needed for the DI. Otherwise the types of the constructor arguments will not be available during runtime.
This is in detail explained in [this](http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html) article.

**Comment by jeffwhelpley** [comment]
Yeah, @pkozlowski-opensource just explained the details of this to me on Slack and I get it now. Basically, the decorator is needed because that is the way that TypeScript emits metadata that includes the type definition. There is no way to know the type after the fact (which is what I was suggesting) because the transpiled code doesn't have the type (and thus doesn't know what to inject). 

Very sad. Will go back to adding `@Injectable()` everywhere.

**Comment by MarkPieszak** [comment]
@mgechev Maybe this is a nice candidate for Codelyzer? 
Warn if `@Injectable()` isn't added to an exported class that doesn't have some `@` decorator already?

**Comment by mgechev** [comment]
Yes, I've been thinking about such rule recently. Here's issue that I just created https://github.com/mgechev/codelyzer/issues/139.

**Comment by MarkPieszak** [comment]
Sure, just made one here: https://github.com/mgechev/codelyzer/issues/140
