### ISSUE TITLE
Provide addControls on FormGroup to conveniently add multiple controls

### ISSUE THREAD

**Issue by bzums** [angular/angular#12747]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, if you want to add a lot of controls to a form group you have to use [addControl](https://angular.io/docs/ts/latest/api/forms/index/FormGroup-class.html#!#addControl-anchor) multiple times.

**Expected behavior**
Provide an `addControls` property on [FormGroup](https://angular.io/docs/ts/latest/api/forms/index/FormGroup-class.html) with the following signature:
`addControls(dir: FormControlName[]): FormControl;`

**What is the motivation / use case for changing the behavior?**
Instead of having to write:
```
formGroup.addControl('controlX', someControlX);
formGroup.addControl('controlY', someControlY);
formGroup.addControl('controlZ', someControlZ);
...
```
you could write:
`formGroup.addControls(someArray);`

Do you think that would actually be helpful and worth to implement? I am aware that it is just for convenience. But It seems to be a quite small and easy change, so I would give it a try and work on a PR.

Best

**Comment by bzums** [comment]
Ok, my suggested signature does not make sense since the `formControl` of the `formControlName` to add is returned. 

So in the case of `addControls` the return value should be an array of `formControl` I suggest, what do you think?

**Comment by clydin** [comment]
Have you tried using FormBuilder?  Unless you're doing some type of dynamic addition to the group.

**Comment by bzums** [comment]
@clydin The form is dynamically build on runtime so as you said, that is not possible.

**Comment by clydin** [comment]
I figured but was just checking; some people don't realize that it's there.

I was looking at your PR.  One thing i noticed (and it's not actually due to your changes) is that if a control is added with an existing name, nothing happens.  This may be awkward when using the new methods; as some controls would be changed but others wouldn't.

**Comment by bzums** [comment]
@clydin Good point, any suggestions how to handle that scenario?

**Comment by clydin** [comment]
One option is to run a check first and throw an error.  At least the user will have some feedback.
This would make the new method inconsistent with the existing singular version though; and changing the existing one would cause an API incompability issue.

**Comment by kara** [comment]
@bzums Thanks for taking the time to create an issue. I agree this is a relatively common use case. However, this is easy enough to accomplish with a simple loop (one line of code in your PR, for example).  If we wanted to add this functionality to the API, for symmetry we'd also have to add a `removeControls` method and complementary `addControls` and `removeControls` methods for `FormArrays`. This is quite a bit to add to the public API for something that is so simple.  We'd like to keep the API surface small if possible. For this reason, we've decided not to add the method at this time. But keep the ideas coming!
