### ISSUE TITLE
`redirectTo` with named outlet doesn't work

### ISSUE THREAD

**Issue by zoechi** [angular/angular#12740]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`{ path: '', redirectTo: '/list(full:full)', pathMatch: 'full', }`
gives me 

> unpkg.com/@angular/core/bundles/core.umd.js:3004 EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'list(full%3Afull)'

**Expected behavior**

should navigate to `/list(full:full)`

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/BoX4gRVKF4tczR3fOeTX?p=preview

Replace the current default route (`redirectTo`) with the commented out to get above exception
Navigating to `/list(full:full)` works with `router.navigate()` - click on the `[navigate]` button

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Only tried in Plunker in Chrome

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by uNki23** [comment]
I'm facing the same problem here and want to contribute something to "_What is the motivation / use case for changing the behaviour_"

My application is divided in two columns. 
First one contains sidebar and beneath it an "action area" (outlet: actions) where typical actions like "Save this and that" are located. The second one is the main content area (outlet: primary).

The actions area depends on the main content - obviously. If you are in _Customers_ pages you want a different actions-component (e. g. CustomersEditActionsComponent) in that actions outlet than in _Settings_ pages (e. g. SettingsActionsComponent).

When a user navigates to '**www.myapp.com/settings**', I actually want to router to navigate to '**www.myapp.com/settings/core(actions:settings-actions)**' - per default. But this won't work:

[{
    path: 'settings', component: SettingsComponent, canActivate: [AuthGuard],
    children: [
      { path: '', redirectTo: '/settings/core(actions:settings-actions)' , canActivate: [AuthGuard] },
      { path: 'core', component: SettingsCoreComponent, canActivate: [AuthGuard] },
      { path: 'roles', component: SettingsRolesComponent, canActivate: [AuthGuard] },
      { path: 'user', component: SettingsUserComponent, canActivate: [AuthGuard] }
    ]
  }](url)

**Comment by DzmitryShylovich** [comment]
Related to https://github.com/angular/angular/issues/12371
