### ISSUE TITLE
Form select box not showing the current value

### ISSUE THREAD

**Issue by cquillen2003** [angular/angular#12742]
Using an array of objects for rendering option values in a select drop-down is broken and/or not intuitive.  When updating an existing record, the current value is not selected in the form.

It appears that [ngValue] is demanding equivalence in terms of the object reference to set the selected value.

**I'm submitting a**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Form select box not showing current value if option tags are created via object.

**Expected behavior**
Form select box shows current value of object/record.  I should be able to specify the logic for the selected option.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/IyHv4nTy0EkGhX8s1vv8?p=preview

**What is the motivation / use case for changing the behavior?**
See plunker.

**Please tell us about your environment:**
Mac OS X 10.11.6, Visual Studio Code, angular/angular2-seed project setup

**Angular version:**
2.0.0

**Comment by zoechi** [comment]
Looks like http://stackoverflow.com/questions/40325480/angular2-ngmodel-ngvalue-select-option-object-equality-across-different-instan

**Comment by zoechi** [comment]
Looks like a dup of #13268 to me

**Comment by kara** [comment]
Thanks for the detailed desc! As @zoechi mentioned, there is an existing issue #13268, so we will track there.
