### ISSUE TITLE
Lazy Loading route causing issue in bundle

### ISSUE THREAD

**Issue by Sri276286** [angular/angular#12748]
Hi,

After I bundled my code with systemjs-builder, routing is causing an issue.

my routing file looks like : 
------------------------------
import { NgModule }             from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  { path: '', redirectTo: '/dashboard', pathMatch: 'full'},
  { path: 'dashboard', loadChildren: './app/dashboard/dashboard.module#DashboardModule' },
];

@NgModule({
  imports: [ RouterModule.forRoot(routes) ],
  exports: [ RouterModule ]
})
export class AppRoutingModule {}

The error : 
![image](https://cloud.githubusercontent.com/assets/19607054/20056138/b120913c-a50a-11e6-829e-62b017438920.png)

Please help me to fix this issue.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
