### ISSUE TITLE
:host(selector):before doesn't work with standard view encapsulation

### ISSUE THREAD

**Issue by bgotink** [angular/angular#12746]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`:host(selector):before` rules are rewritten to `selector:before[_nghost_xyz_1]`, which never matches anything.
Note that `:host:before` without a selector was fixed in #12171 (issue #12165), it is now rewritten to `[_nghost_xyz_1]:before`.

**Expected behavior**

`:host(.foo):before` should match the `:before` of `:host` if it matches `.foo`. [This plunkr](https://plnkr.co/edit/vItv5x9qrKikoj0f2wkN?p=preview) contains a working example in native ShadowDOM.

In this case I'd expect the `:host(selector):before` rule to be rewritten to `selector[_nghost_xyz_1]:before`.

**Minimal reproduction of the problem with instructions**

Use any `:host(selector):before` CSS selector. Example found [here](https://plnkr.co/edit/id2szqWRmCOidI0c7q5a?p=preview) (slightly modified the plunkr @krassx posted in #12165)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 

  * 2.1.2
  * next (`npm i @angular/{common,compiler,core,forms,http,platform-browser,platform-browser-dynamic}@next`)

* **Browser:** all
 
* **Language:** all

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/12730

**Comment by bgotink** [comment]
Huh, missed that one in my search. Thanks!
