### ISSUE TITLE
Import other modules on template level (i.e. enums, static variables etc.)

### ISSUE THREAD

**Issue by kemsky** [angular/angular#12743]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request
```

**Current behavior**
Currently you have to define class fields to make enum or other component available in template::
```
@Component({
selector: 'button',
template: '<div>{{type}}</div>'
})
export ButtonComponent {
@Input()
public type:ButtonType = ButtonType.ok;
}

export enum ButtonType {
ok,
cancel
}

@Component({
template: '<button [type]="ButtonType.ok"></button>'
})
export Component {
public ButtonType = ButtonType ;
}
``` 
It gets annoying very quickly. I could use custom decorator, but it is not AOT/Tree-Shake friendly.

**Expected behavior**
Provide way to either reexport symbols from component:
```
@Component({
template: '<button [type]="ButtonType.ok"></button>',
reexport: {ButtonType}
})
export Component {
}
```
or import symbols on template level:
```
@Component({
template: '
<import symbol="ButtonType" from="./button.type" />
<button [type]="ButtonType.ok"></button>
'
})
export Component {
}
```

**What is the motivation / use case for changing the behavior?**

Usually UI components have enum-like input parameters which allow compile-time checking and refactoring, but now there is no clean way to use them.
Also there are other purely template level helpers, which have the same problem - they need to be injected somehow into template context.

**Comment by vicb** [comment]
For now you have to expose everything you want to access on the component class.

That's something we are thinking about improving in the future - there are already pending feature requests on this repo, closing.
