### ISSUE TITLE
Renderer.listen does not supported multiple DOM events

### ISSUE THREAD

**Issue by musienkoyuriy** [angular/angular#12751]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**

`renderer.listen(ref.nativeElement, 'click mouseover', () => { })`

For now there are no supporting for multiple events in `listen` methos, so listener is not applies.

**Expected behavior**

I expected that listener is apply for all of events which is a string with space's separation in the second parameter. 

**What is the motivation / use case for changing the behavior?**

I think it will be a useful feature in cases where we can't specify events via `@HostListener`

**Comment by ericmartinezr** [comment]
This must be the same as https://github.com/angular/angular/issues/6675

**Comment by tbosch** [comment]
The `Renderer` interface is only meant for Angular's purposes. Once we have a full fledged web worker support, users can write their own render services via an RPC mechanism, and then they should not use `Renderer` any more...

**Comment by tbosch** [comment]
See https://github.com/angular/angular/issues/2409
