### ISSUE TITLE
(ngSubmit) and (submit) do not prevent default form submit causing a page reload

### ISSUE THREAD

**Issue by chrisnicola** [angular/angular#12757]
**I'm submitting a ...**  (check one with "x")

- [x] bug report

**Current behavior**

Currently when you create a form with a submit handler either `(ngSubmit)` or `(submit)` the submit handler is called but the form also continues to do a regular submit which if you have not set any method or action values reloads the page with the data from the form in the url query.

This can be worked around by calling `$event.preventDefault()` in your own handler.

**Expected behavior**

I would argue that most Angular 2 developers will expect that `preventDefault` is handled by the ngForm directive and not by them so I think this behaviour is potentially surprising and likely to cause them to pause and [Google/StackOverflow](http://stackoverflow.com/questions/39203428/ngsubmit-refreshes-the-page-in-angular-2-form) to see if they have done something wrong themselves.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/M4asNIIiXjgNYffrxtoJ?p=preview

**What is the motivation / use case for changing the behavior?**

Primarily developer productivity and ensure things work by default.

* **Angular version:** 2.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by chrisnicola** [comment]
May also be related to this closed issue: #6819

**Comment by DzmitryShylovich** [comment]
Because it's just a regular html5 form and angular doesn't involved. You need to import Forms/ReactiveFormsModule http://plnkr.co/edit/N8uuAAg0faASIQzOcQK4?p=preview

**Comment by chrisnicola** [comment]
Hmm, so that is weird. The module that my component is part of already imports FormsModule, and has done so since before I created the component in question. This should not have been an issue. 

I've gone back and removed the `preventDefault` from my component and it is in fact working now, so I'm at a loss to explain how this was happening. Perhaps it is worth noting that this component was being tested as part of an upgraded Angular 2 module in an Angular 1 app. However, again, it is working now so I don't know.

There must still be something else I am missing here. If I do manage to reproduce it again I'll reopen this with the correct setup. I apologize for the wasted time.

**Comment by zacharyclaysmith** [comment]
Just leaving a clue here for anyone that comes across this issue in similar circumstances as it is difficult to debug: 

If there are any errors with your `<form (submit)="someFunction()" ... >` declaration, you'll get the page reloading issue. 

In my specific case, I had a refactoring error where I was doing something like `<form (submit)="someFunction(someUndefinedVariable.property)" ... >`, which was assumedly throwing an undefined reference error right before the page was wiped :P.

**Comment by xealot** [comment]
Yes, I saw this issue @zacharyclaysmith, same exact thing. An error in the save handler does seem to cause this issue. I feel like the event should already have had `preventDefault` called on it by the time my save handler runs though.

**Comment by ederfranco23** [comment]
In my case this was a Firefox only problem. It was solved just passing the $event to the the invoked method (and also declaring it as a parameter in the method definition):

`<form (submit)="someFunction($event)">`


```
public someFunction(event){
    event.preventDefault();
}
```

**Comment by juanpablodelatorre** [comment]
`return false` with `(submit)` does the trick.

**Comment by zoaby** [comment]
for every one facing this you just need no import the FormsModule in the app.module.ts 
and it will prevent the refresh

**Comment by Mercinskiama** [comment]
Bonjour à tous j'ai un petit souci dans application écrit en Angular 6.
j'utilise un template d'enregistrement des utilisateurs qui contient 3 forms avec submit sur ces derniers.
je constate que le form fonctionne lorsqu'il est seul et les autres en commentaire mais ensemble rien ne marche. Aidez moi svp à résoudre ce problème
