### ISSUE TITLE
Pattern validation with ngModel causes browser freeze on repeated input

### ISSUE THREAD

**Issue by sylvainpolletvillard** [angular/angular#12753]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Having a text input bound with ngModel and a pattern validation, if you hold a letter key while focusing the input to enter a long string such as "aaaaaaaaaaaaa", after ~30 characters the browser freezes and does not respond anymore.

**Expected behavior**

Angular should prevent browser to freeze when spamming input on a field with complex validation.

**Minimal reproduction of the problem with instructions**

See http://plnkr.co/edit/ydMZGGQOh62fGwbLh0Yg?p=preview

**What is the motivation / use case for changing the behavior?**

You don't want browser to freeze or crash because of Angular

**Please tell us about your environment:**

Windows 7 64 bit

* **Angular version:** 2.1.2

* **Browser:** Chrome 54

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
I think it's just inefficient regexp because I cannot reproduce it using different email regexps from the web. For example http://plnkr.co/edit/pFsXDwh5DeHS2551rzAK?p=preview

**Comment by sylvainpolletvillard** [comment]
This regex is not *inefficient*, it is accurate. The regex you pick validates `---@---.com` and other oddities.

**Comment by DzmitryShylovich** [comment]
Yeah, you're right. Probably we need to debounce input.

**Comment by vicb** [comment]
> This regex is not inefficient

The regexp is inefficient - o(n^2)

http://stackstatus.net/post/147710624694/outage-postmortem-july-20-2016

**Comment by sylvainpolletvillard** [comment]
Okay fine, it is ineficcient. But don't you think you should still debounce input ? If not a suboptimal regexp, it would be something else next time.

**Comment by vicb** [comment]
> But don't you think you should still debounce input ?

Please submit an other feature request if this has not been reported yet.

_(I close this one because the report is not about debouncing)_
