### ISSUE TITLE
ReflectiveInjector not resolving in AOT mode before bootstrapping.

### ISSUE THREAD

**Issue by david-camdzic** [angular/angular#12750]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
```ts
var injector = ReflectiveInjector.resolveAndCreate([
	{ provide: ConfigToken, useValue: { format: 'mm/dd/yyyy', environment: 'test' } },
	{ provide: ConfigService, useClass: ConfigService }
]);
```

Injector resolves the ConfigService with JIT. With AOT I receive the following error:
Cannot resolve all parameters for 'ConfigService'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'ConfigService' is decorated with Injectable.

**Expected behavior**
ReflectiveInjector should resolve the ConfigService both in JIT and in AOT compilation.

**Minimal reproduction of the problem with instructions**

```ts
import { ReflectiveInjector, Inject, Injectable, OpaqueToken } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app.module';

export const ConfigToken: OpaqueToken = new OpaqueToken('ConfigToken');

const config = {
	format: 'mm/dd/yyyy',
	environment: 'PROD'
}

@Injectable()
export class ConfigService {
	format: string;
	environment: string;

	constructor(@Inject(ConfigToken) config: any) {
		this.loadConfig(config);
	}

	private loadConfig(config: any) {
		this.environment = config.environment;
		this.format = config.format;
	}
}

let injector = ReflectiveInjector.resolveAndCreate([
	{ provide: ConfigToken, useValue: { format: 'mm/dd/yyyy', environment: 'test' } },
	{ provide: ConfigService, useClass: ConfigService }
]);

var configService = injector.get(ConfigService);

platformBrowserDynamic().bootstrapModule(AppModule);
```

I've also attached an app demonstrating the issue.
[ng-app.zip](https://github.com/angular/angular/files/575706/ng-app.zip)

**What is the motivation / use case for changing the behavior?**
ReflectiveInjector should work the same in both compilation modes.

**Please tell us about your environment:**

* **OS/DEV environment**
Windows 7 Pro, SP1, 64-bit
webpack 2.1.0-beta.25

* **Angular version:**
Using @angular/* 2.1.2

* **Browser:**
Not Applicable
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.6
* **Node (for AoT issues):** `node --version` =   
v6.4.0

**Comment by vicb** [comment]
`ReflectiveInjector` is JIT mode only

**Comment by david-camdzic** [comment]
Thank you for the clarification.

This should be documented somewhere (https://angular.io/docs/ts/latest/api/core/index/ReflectiveInjector-class.html) with a comparable solution in AOT mode posted if any.

So I guess the current situation is to avoid using ReflectiveInjector when utilizing AOT mode if you want to provide a good user experience.

**Comment by david-camdzic** [comment]
I hope you don't mind me asking...  How would the following case from @robwormald  (https://www.youtube.com/watch?v=ZqGvilzDbac&feature=youtu.be&t=2100) be solved for AOT since he's using the ReflectiveInjector?
