### ISSUE TITLE
Router data should always be available to children components 

### ISSUE THREAD

**Issue by michaelchiche** [angular/angular#12767]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If a route with an empty path shares data to its children, the data is inherited and we can access the data from the resolver and the data of the route, but, if we have a route with a path, the children don't have access to the route data nor its params.

It looks like the data is being consumed by the parents. So the parent can see the data, but its children cannot.

To better understand what I mean, please look at the plunkers provided in the issue.

**Expected behavior**
The parent component should not consume the data, so that its children can get the same data.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/zpmMLC?p=preview 

vs 

http://plnkr.co/edit/wGd3ri?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by zoechi** [comment]
[`ActivatedRoute.parent`](https://angular.io/docs/ts/latest/api/router/index/ActivatedRoute-interface.html#!#parent-anchor) should allow you to get the data and params

**Comment by michaelchiche** [comment]
@zoechi I can do that, but it does not seem to be the expected behavior. I should be able to access the data without using parent IMO

**Comment by zoechi** [comment]
Sounds more like you *want* (than *it should*) to me. 
Data is route specific and you can have data with the same name for different route levels.
What would be the expected behavior in this case?

**Comment by olegdunkan** [comment]
The story are repeated one more time ))) There is no good description in docs about what router does with resolved data or doesn't.
I agree with @michaelchiche that rules which define how we can get data is absent. 
It is question of design. 
If design suppose that only componetless node data can share between its children then all good. If whole data coming from above are reached to any level in the flattened fashion then some bug exists.
We  defiantly need a api description in more detailed form.

**Comment by vsavkin** [comment]
it works as intended. These are the rules of inheriting params and data:

- Resolved data is derived from params. So the rules apply to params and data in the same way.
- An empty-path route inherits its parent's params and data. This is because it cannot have its own params (it's an empty-path route), and, as a result, it often uses its parent's params and data as its own.
- Any route inherits its parent's params and data if the parent is a componentless route. This is because there is no component that can inject the parent's activated route.  
- Nothing else gets inherited.

I'll update the API docs.

**Comment by olegdunkan** [comment]
Thanks @vsavkin

**Comment by michaelchiche** [comment]
@vsavkin thanks for the clarifications

**Comment by olegdunkan** [comment]
@vsavkin I've found out that this rules  doesn't describe access to resolved data in resolvers, because we have different behavior in it.

Let we have:
````
const ROUTES:Routes = [
   {
      path:'',
      resolve:{
        share:ShareResolver
      }
      children:[{
          path: 'consumer',
          resolve:{
            consumer:ConsumerResolver
          },
          component: Consumer
      }]
    }
  ]
````

Using 'parent.data' only, I can access data from componentless node in 'Consumer' resolver. But you say

>  route inherits its parent's params and data if the parent is a componentless route.

Try it https://plnkr.co/edit/jasdASivJWjSg6SWgbB4?p=preview

I think it needs clarification for resolver case.

**Comment by klinki** [comment]
@vsavkin We are using nested routes also for layouts (maybe it is not correct approach, but we couldn't find anything better).

So we have routes in form 

```
        {
            path: 'project/:id',
            component: ProjectLayoutComponent,
            resolve: {
                project: ProjectResolve
            },
            children: [
                { path: '', component: ProjectDetailComponent },
                { path: 'edit', component: ProjectEditComponent },
            ]
        }
```

where `ProjectLayoutComponent` creates left navigation menu for project and defines <router-outlet> where child components are displayed. Both `ProjectLayoutComponent` and all possible child components require project instance. So it makes sense to me to load it just once using `ProjectResolve` and get it into all child routes as well. 

Is there any workaround to support this scenario? Maybe it would be nice if it was possible to specify if route should inherit parents data and parameters?

**Comment by olegdunkan** [comment]
@klinki 

````
{
            path: 'project/:id',
            component: ProjectLayoutComponent,
            {
               path:'',
               resolve: {
                    project: ProjectResolve
               },
               children: [
                    { path: '', component: ProjectDetailComponent },
                    { path: 'edit', component: ProjectEditComponent },
               ]
            }
}
````
You can use above to get project for all children via 'data.project', 
or you can leave your code untouched and simply use 'data.parent.project'.

**Comment by klinki** [comment]
@olegdunkan Well the thing is I need the data to be available in `ProjectLayoutComponent` already. You are right, I could use `data.parent`. But in some cases, I don't now on which tree-level the data are. I guess I will have to write some tree traversing service which would merge parameters and data for all route levels.

We are using this pattern quite extensively and I was surprised it is not supported by angular :(

**Comment by olegdunkan** [comment]
@klinki yes, you can pull 'project' to any level deeper and use it simply via 'route.data'.

For example you can do:  
````
{
           path: 'project/:id',
           component: ProjectLayoutComponent,
           resolve:{
                project: ProjectResolve
           }
           children: [
                     ...
                        ...
                           ... 
                             {
                                 resolve:{
                                     project:PullProjectFromAboveResolver   
                                 },
                                 children: [
                                     { path: '', component: ProjectDetailComponent },
                                     { path: 'edit', component: ProjectEditComponent },
                                 ]
                             }
           ]
}
@Injectable()
class PullProjectFromAboveResolver  implements Resolve<Project> {
    resolve(route:ActivatedRouteSnapshot):Project{
      var ref = route.parent;
      while(ref){
         let project = ref.data['project'];
         if (project) {
             return project;
         }             
         ref = ref.parent;
      }
      return null;
   }
}

**Comment by klinki** [comment]
@olegdunkan  Well I have been playing with that and ActivatedRouteSnapshot cannot be reliably used for that. See https://github.com/angular/angular/issues/12912. It means I would have to traverse ActivatedRoute parents and subscribe to their parameter/data Observables and flatten those data to get what I need - inherited data and parent fields.

It seems unreasonably complicated and very tricky to me.

**Comment by wuyuchang** [comment]
Where is the API docuemnt of the "An empty-path route inherits its parent's params and data " in angular website?
How can I do if I prefer to use child data without inherits it's parent's if the parent is a componentless route?
@vsavkin

**Comment by nosachamos** [comment]
Is there a way to disable this inheritance?

I am building a breadcrumb component, but have lots of componentless and empty-path routes in my configuration, which causes data to be replicated down the children routes. Even if I explicitly set the same data on the children, they get overwritten by what is set on the parent (parent uses resolve, children use a plain data object). I'd like to disable inheritance entirely. Is there a way?

**Comment by artuska** [comment]
Angular 4.4.3 is here and I don't have any `.parent` objects in my `this.route` which is `ActivatedRoute` which is lazy-loaded child:

app.routing.ts:

```
{
    path: 'terms',
    data: {
        title: 'Terms of use'
    },
    loadChildren: './Terms/terms.module#TermsModule'
},
```

terms.routing.ts:

```
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { Routes } from '@angular/router';

import { TermsComponent } from './terms.component';

const routes:Routes = [
    {
        path: '',
        data: {
            heading: 'Правила',
            title: 'Правила пользования'
        },
        component: TermsComponent
    }
];

@NgModule({
    imports: [
        RouterModule.forChild(routes)
    ],
    exports: [
        RouterModule
    ]
})

export class TermsRouting {}
```

And here is some `top-panel` component which is inside the `app.component.html`:

```
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
    selector: 'top-panel',
    templateUrl: './top-panel.component.html',
    styleUrls: ['./top-panel.component.scss']
})

export class TopPanelComponent {

    constructor(private route: ActivatedRoute) {

    }

    ngOnInit() {
        this.route.data.subscribe((data) => console.log(data)); // just always empty {}
    }

    back() {
        this.location.back();
    }

}
```

How do I make `data` subscription work?

**Comment by zoechi** [comment]
@artuska closes issues are not monitored (at least not officially)
If you think there actually is a bug, then it is probably a new bug (even when the symptoms are the same) and should get a new issue.

**Comment by artuska** [comment]
@zoechi thank you, I just hope a notification will be sent for all this thread participants and someone will take a look :)

**Comment by zoechi** [comment]
@artuska I wouldn't expect that to happen.
If it's not worth for you to create an issue, it's probably not worth investigating, and therefore unlikely to prioritized and fixed.

**Comment by dirkluijk** [comment]
We are running into the same issue over and over again. We have quite a lot levels of nested routes. What bothers me is that the component needs to know where it is registered in the route tree.

It is quite messy to have `route.parent.parent.parent.data.map(...)` in your code.

**Comment by scaljeri** [comment]
This is indeed a very annoying problem. But maybe my decorators can help. If you have
 
```typescript
bar$: Observable<Foo>;
...
this.bar$ = this.route.parent.parent.parent.parent.data.map(d => d['bar'])
```

it can be written as
```typescript
    @RouteData() bar$: Observable<Foo>;
```

For those interested, I have it published to npm [here](https://www.npmjs.com/package/angular-route-xxl). Hope it helps!

**Comment by simeyla** [comment]
This is now possible via [`paramsInheritanceStrategy`](https://angular.io/api/router/Router)

> Defines how the router merges params, data and resolved data from parent to child routes. Available options are:
> 
> 'emptyOnly', the default, only inherits parent params for path-less or component-less routes.
> 'always', enables unconditional inheritance of parent params.
> 

PS. I found out about this thanks to @scaljeri and his https://github.com/scaljeri/angular-xxl package. 
Note that this is the link for newer version from the one referenced in his previous answer.

More info here:
https://www.bennadel.com/blog/3469-accessing-parent-route-params-via-paramsinheritancestrategy-in-angular-6-0-7.htm

**Comment by marcusportmann** [comment]
> Is there a way to disable this inheritance?
> 
> I am building a breadcrumb component, but have lots of componentless and empty-path routes in my configuration, which causes data to be replicated down the children routes. Even if I explicitly set the same data on the children, they get overwritten by what is set on the parent (parent uses resolve, children use a plain data object). I'd like to disable inheritance entirely. Is there a way?

@nosachamos Did you manage to solve this issue? I have the same problem where I want to populate route data using a resolver at a single level in the route hierarchy but when I do so it overrides whatever I specify below that point. For example, in the snippet below the CodeCategoryTitleResolver overwrites the title data I am explicitly setting for the 'codes' route.

`const routes: Routes = [
  {
    path: '',
    component: CodeCategoriesComponent,
    data: {
      title: 'Code Categories',
    }
  }
  , {
    path: ':codeCategoryId',
    resolve: {
      title: CodeCategoryTitleResolver
    },
    children: [{
      path: '',
      component: EditCodeCategoryComponent
    }, {
      path: 'codes',
      data: {
        title: 'Codes'
      },
      children: [{
        path: '',
        component: CodesComponent
      }
      ]
    }
    ]
  }
];`
