### ISSUE TITLE
about angular Chinese community

### ISSUE THREAD

**Issue by apawn** [angular/angular#12762]
Hello

 today , i am writting a article ,i want to publish on angular chinese community ,which is http://community.angular.cn/.

but it tell me error and error, i dont know if it is my mistake.

please help me 

thanks.

**Comment by damoqiongqiu** [comment]
@apawn Hi, I am Aaron Zhang, Angular's PM in China, and in charge of this site now, paste the errors here please. BTW, Angular team bought this site not long ago, so the program is a little bit out of date now, and we are going to update it soon.

你好，apawn，我是大漠穷秋，Angular中国的PM，请把你看到的错误贴到这里看看。 另外，Angular团队不久前刚收购这个站点，所以站点本身的程序有点老，我们正在计算升级它。

**Comment by apawn** [comment]
Hi 大漠老师，我在Angular 2的中文社区的群里看到过你。就是在这个网站上我点击发表文章，下方就会弹出Error，我点击验证邮箱也是。 我打开控制台，里面有报错。

不知道我是不是有什么操作错误。

我注册的邮箱 ： mymeat@126.com   我的昵称       小精灵。

万分感谢。

**Comment by damoqiongqiu** [comment]
好的，我自己来试试看，如果你能把报错的截图给我看看就好了。

**Comment by vicb** [comment]
Could this be closed now or do the Angular team needs to do something ?

**Comment by vicb** [comment]
@damoqiongqiu apparently you have everything under control, closing the issue. Thanks.

**Comment by damoqiongqiu** [comment]
@vicb Thank you, you are right, this issue is out about Angular core.
