### ISSUE TITLE
Angular 2: Attribute centric component in same module fail to render.

### ISSUE THREAD

**Issue by barrydaboom** [angular/angular#12766]
**I'm submitting a bug report**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1) **ComponentA** (with decorator's selector='[comp-a]')
and **ComponentB** (with decorator's selector='[comp-b]')
are declared and exported in (**the same**) feature module **MyModule**.

2) Template for **ComponentA** has an **div** element to render **ComponentB**
(e.g. &lt;div comp-b&gt;&lt;/div&gt;)

3) The problem is **ComponentB** is not rendered. It will only render if its 'selector' decorator is an element (selector='comp-b') and **ComponentA**'s template its contains (<comp-b></comp-b>).

Note: I'm using lazy loading of Modules/Components.

**Expected behavior**
I expect ComponentB to be rendered in ComponentA regardless of whether it's an element or attribute directive.

**Please tell us about your environment:**
1) ASP.NET rendered HTML
2) Visual Studio TypeScript 2 generated javascript files configured for AMD and ec6.
3) Angular 2.1.0

* **Angular version:** 2.0.X
This behavior is occurring in version 2.1.0

* **Browser:** Chrome 54.0.2840.87 m

 
* **Language:** TypeScript 2.0 | ES6

**Comment by vicb** [comment]
Please add a repro.

**Comment by barrydaboom** [comment]
Sorry, although I can reproduce in our (extremely) large project. My attempts to pull out the specific code and provide a repro project has failed. I cannot reproduce the behavior (it's working as I would expect) in my repro project. I'm closing the bug for now.
