### ISSUE TITLE
Allow multiple FormGroup/FormArray validators and asyncValidators

### ISSUE THREAD

**Issue by imgx64** [angular/angular#12763]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
The [`FormGroup` constructor](https://github.com/angular/angular/blob/2.1.2/modules/%40angular/forms/src/model.ts#L837) and [`FormArray` constructor](https://github.com/angular/angular/blob/2.1.2/modules/%40angular/forms/src/model.ts#L1138) take single validators in the following parameters: `validator?: ValidatorFn` and `asyncValidator?: AsyncValidatorFn`.

On the other hand, the [`FormControl` constructor](https://github.com/angular/angular/blob/2.1.2/modules/%40angular/forms/src/model.ts#L642) takes `validator: ValidatorFn|ValidatorFn[]` and `asyncValidator: AsyncValidatorFn|AsyncValidatorFn[]` and composes validator arrays into a single validator.

**Expected behavior**
`FormGroup` and `FormArray` should also be able to take arrays of validators like `FormControl` can.

**What is the motivation / use case for changing the behavior?**
It's useful to have multiple group validators, for example: One validator to check if password == confirm password, and another validator to make one field required or optional based on the value of another field.

* **Angular version:** 2.1.1

**Comment by rafaelss95** [comment]
As workaround, it works using `Validators.compose`:

`this.formBuilder.array([], Validators.compose([Validators.required, Validators.minLength(3)]));`

**Comment by natsid** [comment]
Just wanted to revive this issue since it's fairly important.

Even though you can techincally add multiple validators using Validators.compose(), this doesn't allow you to tell _which_ error is triggering the invalidity, i.e., use hasError(myError).

**Comment by kirilmitev** [comment]
bump

**Comment by kara** [comment]
This functionality was added in 5.0.0-beta.2. See [the commit for more info](https://github.com/angular/angular/commit/ebef5e697a19d38d761f15a123739481ddc74622).

**Comment by usmanajmal** [comment]
Why does `Validators.compose([Validators.required, Validators.maxLength(255)])` return Error: Duplicate Identifier Validators? :-/
