### ISSUE TITLE
Incorrect error message for empty href bindings, ie [href]=""

### ISSUE THREAD

**Issue by zewt112** [angular/angular#12768]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Console error on bootstrap. Error message is below. Error is shown when components have an empty href binding in the code, ie `[href]=""`.

Error message:
`zone.js?1478627523524:355 Unhandled Promise rejection: Cannot read property 'currValExpr' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'currValExpr' of null(…) TypeError: Cannot read property 'currValExpr' of null
    at eval (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:12344:115)`

**Expected behavior**

Either a better error message like "Empty href bindings are not allowed" or update the code to allow it. For your reference this is line 12344 in angular 2.1.2 of compiler.umd.js

The function throwing the error is
`updateStmts.push.apply(updateStmts, writeToRenderer(THIS_EXPR, boundProp, renderNode, evalResult.currValExpr, view.genConfig.logBindingUpdate));`

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Incorrect error message, took ages to work out when we upgraded from a previous version of angular 2.

**Please tell us about your environment:**

* **Angular version:** 2.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by zewt112** [comment]
Here you go: https://plnkr.co/edit/cwtcMhkrGf3coPsOujR0?p=preview

**Comment by ericmartinezr** [comment]
This was supposed to be fixed already, see https://github.com/angular/angular/issues/12583. If you try it with master does it still throw?

**Comment by vicb** [comment]
Fixed in master, will be part of next release.

Note: empty property bindings are ignored but we do not throw an error to stay compatible with older releases

**Comment by zewt112** [comment]
Thanks all

**Comment by winni4eva** [comment]
this error wasted my 7 hours.. its working now after i upgraded
