### ISSUE TITLE
ActivatedRoute is wrong after rejecting a CanDeactivate 

### ISSUE THREAD

**Issue by pieterhendrickx** [angular/angular#12776]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Given a navigation using 'router.navigate(...)' from an activated route for which a CanDeactivate routeguard is defined.

And when the CanDeactivate guard returns a Promise which is resolved with false (i.e. the route can not be deactivated)

Then the ActivatedRoute.firstChild injectable of the parent route points to the route that was navigated to, rather than the route that could not be deactivated.

**Expected behavior**
It would be better to only update the ActivatedRoute when the current route can be deactivated, and remain to be the current route if any CanDeactivate route guards fail.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/pLf5VTvq3Lh0H2N5g1Tl?p=preview

* Component2 cannot deactivate due to a routeGuard
* Click button twice... and look at the difference between the activatedRoute.firstChild of the main component and the activatedRoute of the childComponent

**What is the motivation / use case for changing the behavior?**
I feel the current value of the ActivatedRoute can not be 

**Please tell us about your environment:**
MacOS, Webstorm, webpack,...

* **Angular version:** 2.0.X
Angular 2.1.1
Router 3.1.2

* **Browser:** 
all

* **Language:** 
all

* **Node (for AoT issues):** `node --version` =  v6.2.1

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by pieterhendrickx** [comment]
link added in original post
