### ISSUE TITLE
form validation, field is no more valid when the [disabled] attribute is truthy

### ISSUE THREAD

**Issue by yashhy** [angular/angular#12778]
As per the [plunker](http://plnkr.co/edit/383odqRfZQ5CDRFlW70g?p=preview) when you select the disabled dropdown the valid field "Name" is shown as invalid.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/11432#issuecomment-245670999

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich
