### ISSUE TITLE
Custom validator is not getting called on onBlur

### ISSUE THREAD

**Issue by ssivaprasad** [angular/angular#12770]
[modelForm.zip](https://github.com/angular/angular/files/579186/modelForm.zip)

My custom validator is getting called on Page load but not getting called on onBlur

Could any one tell me why my custom validator is not getting called on when user leaves the input filed with typing anything?

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by zoechi** [comment]
Validators are only called on `change` or `input`, aren't they?

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have enough info / reproduce scenario.
