### ISSUE TITLE
Tracking: NgModule summaries

### ISSUE THREAD

**Issue by tbosch** [angular/angular#12787]

**Comment by tbosch** [comment]
Still missing: serialize all required metadata also into the summaries.

**Comment by fknop** [comment]
If I'm building a library compiled with `ngc`, do I need to ship these `ngsummary` with the library ? I see it contains absolute paths.

**Comment by tbosch** [comment]
@fknop no, these are only for build tools that do incremental compilation (which is not yet supported outside of Google).

**Comment by shlomiassaf** [comment]
@tbosch I'm using `.ngsummary.json` files to track down files that symbols exist on physically.

It is used for a webpack router loader (lazy loading) where I change literal strings into webpack compatible dynamic import (chunks)

When a module exists only to re-export symbols (e.g index.ts) it will not have an `.ngfactory.ts` file which makes it hard to reference it, I need to search for the file hosting the symbol (ngmodule)

I'm not doing TS compilation so I can't search for it, but I use the `ngsummary.json` to track the symbol.

Is it subject to change?
