### ISSUE TITLE
We really need a document explaining the underline render concepts of components...

### ISSUE THREAD

**Issue by born2net** [angular/angular#12780]
We really need a document explaining the underline render concepts of components...
I spoke to the guys at Gitter and many agreed that this is a missing piece of the puzzle and we really need this document.

In an effort to gain deeper knowledge into Angular 2 I wish someone would create an in depth explanation / tutorial on the underlying structure of components, directives and their containers and views.

As per the docs:

> The component’s container can contain two kinds of Views. Host Views, created by instantiating a Component via createComponent, and Embedded Views, created by instantiating an Embedded Template via createEmbeddedView. The location of the View Container within the containing View is specified by the Anchor element. Each View Container can have only one Anchor Element and each Anchor Element can only have a single View Container. Root elements of Views attached to this container become siblings of the Anchor Element in the Rendered View.

This leaves many open questions, such as: a Host view is referring to the element that Component resides in, and an Embedded view is referring to the component’s template itself?

Is that true for both cases when created manually (via createComponent) as well as when created declaratively via in another hosting component (parent)?

Is that the case for Directives as well which don’t have a template (thus no view)? And how all this works in a Shadow dom environment (browser actually support a component host) vs an emulated environment?

Angular 2 does do a lot of magic and in an effort to become an expert I wish to better understand, (maybe via a visual diagram) the entire relationship of: ViewContainerRef, Host views, Templates, Embedded Template, ViewChild, ViewContainer and their hierarchy of components and directives.

I consider myself extremely well versed in Angular2 (delivered 2 huge project already) but still feel I have holes in my understand of the underline internal workings.

Sure you don’t need to know how a car works to drive one, but you handle it much better if you do,

Thanks as always,

Sean

also posted at:

http://stackoverflow.com/questions/40423772/angular-2-how-underline-framework-works-with-relation-to-containers-hosts-and

**Comment by DzmitryShylovich** [comment]
https://youtu.be/ZqGvilzDbac?t=752

**Comment by born2net** [comment]
ya saw that last night... definitely helps TXXXXX!
hopefully will have the docs as well soon (I take credit for annoying Rob for making this video LOL )

**Comment by vicb** [comment]
Please report docs issue on https://github.com/angular/angular.io/issues

**Comment by born2net** [comment]
will do tx!!!
