### ISSUE TITLE
bootstrapModule doesn't catch compilation errors

### ISSUE THREAD

**Issue by bisubus** [angular/angular#12791]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Compilation errors are thrown before a promise is returned from `bootstrapModule(...)`:

```
@Component({
  selector: 'app',
  template: `...`,
})
export class App {
  constructor(badDependency) {}
}

...

try {
  platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(e => console.log('Bootstrap error', e)
} catch (e) {
  // logs `Can't resolve all parameters for App: (?)`
  console.log('Bootstrap error', e)
}
```
**Expected behavior**

Compilation errors are handled and result in returning a rejected promise from `bootstrapModule(...)`:

```
platformBrowserDynamic().bootstrapModule(AppModule)
// logs `Can't resolve all parameters for App: (?)`
.catch(e => console.log('Bootstrap error', e)
```

**Minimal reproduction of the problem with instructions**

A [plunk](http://plnkr.co/edit/pD88fe0S7zesgK9ClJiY) that demonstrates the issue.

**What is the motivation / use case for changing the behavior?**

Currently `bootstrapModule` method is inconsistent in catching errors. The fact that it returns a promise suggests that it uses promise rejection to handle errors, but compilation errors may be thrown before a promise is returned, this results in counterintuitive undocumented behaviour.

**Please tell us about your environment:**

* **Angular version:** 2.1.2

* **Browser:** [all]

 
* **Language:** [all]

**Comment by tbosch** [comment]
This should be fixed on master now. See the change to the test in https://github.com/angular/angular/blob/master/modules/@angular/platform-browser/test/browser/bootstrap_spec.ts#L152.
