### ISSUE TITLE
[ngModel] Value not initilize properlly

### ISSUE THREAD

**Issue by arv10singh** [angular/angular#12806]
```
<ion-input type="text " [ngModel]="amount123" (ngModelChange)="amount123 = blockChar_withDot($event)"></ion-input>

blockChar_withDot(amount){
        let rr = this.common.blockChar_withDot(amount);  //It will block all alphabet 
        let result = this.common.getValidData(rr)? rr: '';
console.log("Input data is->>(%o) after prosessing model value init->>(%o)",amount,result);
return result;
    }

```

**Current behavior**
```
Input data is->>("6") after prosessing model value init->>("6")
developer-settings.js:37 Input data is->>("66") after prosessing model value init->>("66")
developer-settings.js:37 Input data is->>("66r") after prosessing model value init->>("66") // view-> 66r
developer-settings.js:37 Input data is->>("66rr") after prosessing model value init->>("66") // view-> 66r
developer-settings.js:37 Input data is->>("66rrr") after prosessing model value init->>("66") // view-> 66rrr
developer-settings.js:37 Input data is->>("66rrrt") after prosessing model value init->>("66") // view-> 66rrrt
----------------------------------------------- Coming correct ---------------------------------------------------------
developer-settings.js:37 Input data is->>("66rrrt6") after prosessing model value init->>("666") // view-> 666
------------------------------------------------------------------------------------------------------------------------------
developer-settings.js:37 Input data is->>("666t") after prosessing model value init->>("666") // view-> 666t
developer-settings.js:37 Input data is->>("666ty") after prosessing model value init->>("666") // view-> 666ty
developer-settings.js:37 Input data is->>("666tyy") after prosessing model value init->>("666") // view-> 666tyy
----------------------------------------------- Coming correct ---------------------------------------------------------
developer-settings.js:37 Input data is->>("666tyy8") after prosessing model value init->>("6668") // view-> 6668
------------------------------------------------------------------------------------------------------------------------------
```

* When i am entering text field numeric value is working but when i am entring alphabet in controller it's change but in views  it's not change(not initilize at model)
* Again if i will enter again numeric then it will work (Removes all alphabet and add all numeric data) It is binding at view also as per already added console message. 
* One more thing if i will enter first time(alphabet) then that time is working(binding at view) but if i will add second time alphabet then it is not working (binding at view is not done).  

* **os: Ubuntu 14.04,** 

* **Angular version:** 2.1.1

* **Browser:**  Chrome-53.0.2785.116

**Comment by DzmitryShylovich** [comment]
> `ion-input`

this might be an ionic issue. Pls add a repro in plunker with native `input` element.

**Comment by arv10singh** [comment]
I created plunker with native input element, can see the console 
http://plnkr.co/edit/gxWyvTzVLRc0smZIZwON?p=preview
What ever i wrote the point it is stisfy, so problem with angular

**Comment by arv10singh** [comment]
Please as soon as possible fix this issue, becaue i am not able to validate.

**Comment by zoechi** [comment]
@arv10singh a Plunker to reproduce should contain minimal code. I can't imagine that all the code in `blockChar_withDot_eng(contnum)` is necessary to reproduce your issue. If it actually is, I'd feel safe to assume it's a bug in your code.

**Comment by arv10singh** [comment]
@zoechi I wrote that function _blockChar_withDot_eng(contnum)_  only block alphabet charcter if you enter the alphabet then function will block and numeric value will return and do binding with input element. 
**Might be problem with 2 way binding not in function same thing is working with angular 1.0 but Angular 2.0 it broke.** 
Can you verify with console message, if you enter any alphabet it will block but in view not reflect.

**Comment by tanveerahmaddar** [comment]
@arv10singh use (keyup) event instead of (ngModelChange) in your input field. it will work

**Comment by AndrewKushnir** [comment]
Hi @arv10singh, I've re-created your repro using Stackblitz ([see test page here](https://stackblitz.com/edit/angular-ivy-kn7eaw)) and simplified your custom processing function (the `blockChar_withDot_eng` one) and everything seems to be working as expected from Angular perspective. If the problem still exists, feel free to reopen the ticket and please provide an updated repro. Thank you.
