### ISSUE TITLE
ngSubmit isn't propagated to subgroups

### ISSUE THREAD

**Issue by binarious** [angular/angular#12808]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Listening to `ngSubmit` on a subgroup doesn't fire on form submit.

**Expected behavior**
`ngSubmit` should emit when the parent group gets submitted.

**Minimal reproduction of the problem with instructions**
Create a form:
```ts
const fb = new FormBuilder(); 
this.form = fb.group({
  subForm: fb.group({
    field: ['', Validators.required]
  })
});
```
With this template:
```html
<form [formGroup]="form">
  <div [formGroup]="form.controls['subForm']">
    <sub-component></sub-component>
  </div>
  <button type="submit">Submit</button>
</form>
```
And in the `sub-component` query for the `FormGroupDirective`:
```ts
constructor(formGroup: FormGroupDirective) {
  // doesn't get fired
  formGroup.ngSubmit.subscribe(() => console.log('works');
}
```
https://plnkr.co/edit/jVE8slMyqQD4sMY2b8lu?p=preview

**What is the motivation / use case for changing the behavior?**
Creating a directive to show form controls' errors on submit isn't possible with the current behavior.

* **Angular version:** 2.1.2

* **Browser:** all
 
* **Language:** all

**Comment by laco0416** [comment]
@binarious maybe `formGroupName` can resolve what you want to do.

```
    <form [formGroup]="form">
      
      <div formGroupName="subForm">
        <sub-component></sub-component>
      </div>
      
      <button type="submit">Submit</button>
    </form>
```

https://plnkr.co/edit/LMBlmn6MConsI0VSyoW6?p=preview

**Comment by binarious** [comment]
Great, thanks a lot. Shall I leave this issue open or is it the expected behaviour?

**Comment by laco0416** [comment]
I think it is not a bug. `FormGroupDirective` creates new form context, so `<sub-component>` can only access to `subForm`. I think it makes sense.

**Comment by binarious** [comment]
If there's a `ngSubmit` to subscribe to, I would assume that it will fire on form submission. In fact, that's stated in the docs as well:
> Furthermore, you can listen to the directive's ngSubmit event to be notified when the user has triggered a form submission. The ngSubmit event will be emitted with the original form submission event.

https://angular.io/docs/ts/latest/api/forms/index/FormGroupDirective-directive.html

If it's intended that you can only listen to the `ngSubmit` of the root `FormGroupDirective`, then this should be added to the docs. But then the `ngSubmit` in the childs groups don't make any sense since they won't fire.

**Comment by wesleycho** [comment]
I don't think submission should be propagated to subgroups - it is a browser construct on the form element. Having it propagated to subgroups goes in the reverse direction of standard browser event delegation with it propagating upwards. In addition, supporting this would add additional complexity with fairly weak benefits IMO, while also adding bloat.

**Comment by binarious** [comment]
@mhevery Why did you close this?
