### ISSUE TITLE
ng e2e doesn't use existing ng serve session

### ISSUE THREAD

**Issue by finalight** [angular/angular#12805]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
opens a new session everytime i test, which is very slow

**Expected behavior**
expects to use existing sessions

**Minimal reproduction of the problem with instructions**
just try to run ng serve, then run ng e2e

**What is the motivation / use case for changing the behavior?**
test faster

**Please tell us about your environment:**
mac OS sierra

* **Angular version:** 2.0.X
2.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
n.a

* **Node (for AoT issues):** `node --version` =   7

**Comment by ericmartinezr** [comment]
Is this angular-cli? If that's so please reopen in its repo https://github.com/angular/angular-cli
