### ISSUE TITLE
Error lazy-loading module that uses core module.

### ISSUE THREAD

**Issue by liongoncalves** [angular/angular#12809]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Lets say that we have a HomeModule that uses a component from the CoreModule (top-nav component for example). When you set the router to lazy load HomeModule and try to access this module (lets say /home) it always says that the top-nav component is not defined. Even when the CoreModule is imported in the AppModule (like the style guide says)

**Expected behavior**
It should lazy-load the HomeModule and this should work with the already imported CoreModule, without the need to importing it again (which goes against the style guide)

**Minimal reproduction of the problem with instructions**
1. Create a HomeModule
2. Lazy-load it in the routes.    ( loadChildren: 'app/home/home.module#HomeModule' )
3. Go to the route.

**What is the motivation / use case for changing the behavior?**
The behavior is going against the style guide

**Please tell us about your environment:**
Webpack on windows.

* **Angular version:** 2.0.1

* **Browser:** all
 
* **Language:** TypeScript X.X 

* **Node (for AoT issues):** `node --version` =   7.0.0

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by liongoncalves** [comment]
Is it ok if I upload the code to my github account and link it? I kinda hate working with plunkr... never know how to import the last version of angular 2 and stuff...

**Comment by DzmitryShylovich** [comment]
you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by DzmitryShylovich** [comment]
@liongoncalves did u solve the issue?

> The code is here https://github.com/liongoncalves/app

404

**Comment by DzmitryShylovich** [comment]
if u can't reproduce it then we can't do anything...

**Comment by liongoncalves** [comment]
Ok, I think the problem is not with the router itself but is with the module system.... i created a small test to see. Maybe I am doing something wrong or maybe the style guide is not right. But as you can see in the example below I created a core module with a topnav component and I'm tryng to use that topnav in the home module, and well i can't use it unless i import the module (which i think it goes against the style guide in the Angular.io page....)
http://plnkr.co/edit/rnSnJWYQ4y4YmAA2kKi4?p=preview

**Comment by DzmitryShylovich** [comment]
Modules do not inherit access to the components, directives or pipes that are declared in other modules. What AppModule imports is irrelevant to HomeModule and vice versa. Before HomeModulecan can use TopnavComponent, HomeModule must import CoreModule.

https://angular.io/docs/ts/latest/guide/ngmodule.html#!#add-the-_contactmodule_
