### ISSUE TITLE
Control instance error on adding/removing multiple dynamic controls from FormGroup.

### ISSUE THREAD

**Issue by moizshabbir** [angular/angular#12810]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am creating an editable table with add and remove row feature in the FormGroup with validation.
The table works when the rows add or remove from last. When the row is removed from the middle of the table, angular throw an error "There is no FormControl instance attached to form control element with name name_2".
On adding the row I have used the "addControl" method to add control in the group and on the removal of the row I am using "removeControl" method.
**Expected behavior**

There should be no error, from whichever place I remove or add the row.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, IIS server 7, angular 2.1.0
* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome Version 54.0.2840.71 m (64-bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.3
* **Node (for AoT issues):** `node --version` =   
Node 6.0

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by moizshabbir** [comment]
Here is the example.
http://plnkr.co/edit/KgC62qZd5Dp9CSUwJKdT?p=preview

**Comment by moizshabbir** [comment]
Found the solution. It was due to the naming convention of dynamic control. 
When the row was removed  from the table, the table index is reinitiated but the control name bound in the row didn't change and when a new row has added the name of the control duplicates, which caused the issue.

Here is the working example
http://plnkr.co/edit/S1aAuW?p=info

**Comment by DzmitryShylovich** [comment]
@moizshabbir close the issue pls if it was resolved

**Comment by nheidloff** [comment]
I had the same issue and use now the workaround with the unique ids from @moizshabbir (thanks). Without this workaround I couldn't get Angular to update the controls (tried various lifecycle hooks, updateValueAndValidity, direct DOM access, etc.). Shouldn't Angular remove these non-used form controls so that they don't cause duplication errors? Also shouldn't the error say that the control cannot be found because there is more than one (rather than saying not attached)?

**Comment by simonwiles** [comment]
I've just spent a couple of hours trying to figure this out too; it does seem like this could be made less problematic by either a) the framework removing the controls; or at least b) a more helpful error message.
