### ISSUE TITLE
i18n issues when using third party translation tools

### ISSUE THREAD

**Issue by soyzamudio** [angular/angular#12815]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I use www.transifex.com and pull the translations we have on their platform, the build breaks and it generates this error:

<img width="994" alt="screen shot 2016-11-11 at 10 18 09 am" src="https://cloud.githubusercontent.com/assets/3433118/20227545/97972466-a801-11e6-9f20-f4751afa229d.png">

If I manually create the translated file the build works correctly...

Here is a plunkr with the 3 translation files (messages.xlf, messages.de.xlf (manually created), messages.de_DE.xlf (transifex generated)): http://plnkr.co/edit/2xf1rDdn328NiXW4TkaT?p=info

* **Angular version:** 2.1.0
 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =   6.2.2

**Comment by vicb** [comment]
@soyzamudio could you please try to check what message (id) is processed when the error is thrown ?

**Comment by vicb** [comment]
And where exactly in the code we throw ?

**Comment by vicb** [comment]
Seems like this guy:

```
 <trans-unit datatype="html" id="31da99c0b4bac47b53e3a9b7de25c037e53ac513">
        <source>
        Editors' Blog
      </source>
```

is missing a translation which is probably the root cause. Could you please try to add one manually and report ?
