### ISSUE TITLE
i18n of interpolated strings

### ISSUE THREAD

**Issue by jaska45** [angular/angular#12819]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you have a strings that uses interpolation such as

`<p>Hello {{ownerName}} and {{sellerName}}</p>`

ng-xi18n extracts this

<source>Hello <x id="INTERPOLATION"/> and <x id="INTERPOLATION_1"/></source>

This has two problems:
1) Variable names are gone
2) Generated syntax is too hard for localziation tools.

**Expected behavior**

1) Important information is lost. The translator only sees two meaninsless strings: INTERPOLATION and INTERPOLATION_1. It would be better to have 

<source>Hello <x id="ownerName"/> and <x id="sellerName"/></source>

2) Very few localziation tool actually undestand this <x/> notation. Most likely  th text gets translated incorrectly. A better choise woul leave the placeholds in Angular style like

<source>Hello {{ownerName}} and {{sellerName}}</source>

**Minimal reproduction of the problem with instructions**

@Component({
  selector: 'my-app',
  template: `
  <p i18n>Hello {{ownerName}} and {{sellerName}}</p>
  `
})
export class AppComponent 
{ 
  sellerName: string;
  ownerName: string;

  constructor()
  {
    this.sellerName= "Bill";
    this.ownerName= "Jill";
  }
}

**What is the motivation / use case for changing the behavior?**

- Make localization easier. Eliminate issues where translator does not get the meaning of the string. 
- Localization tools can better cope with Angular resources.

**Please tell us about your environment:**
Windows 8.1, Node.js v6.9.1, npm 3.10.8, VS Code.

* **Angular version:** 2.0.X

Don't know how to find. Created the Project 11/11/2016 so it must be pretty new.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Tested with Chrome but this is not browser related so will happed on all.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScriot 2.0.9.

* **Node (for AoT issues):** `node --version` =   

v6.9.1

**Comment by vicb** [comment]
2 problems -> 2 answers:

 1) placeholders names

- There is a way to set the placeholder names, @Foxandxss you were looking for an use case in https://github.com/angular/angular.io/pull/2740, this is one !
- However I would rather see this solved by adding a description i.e. `<p i18n="i.e. Hello owner and seller">Hello {{ownerName}} and {{sellerName}}</p>`

2) Tools

> Very few localziation tool actually undestand this <x/> notation. Most likely th text gets translated incorrectly. A better choise woul leave the placeholds in Angular style like

You probably don't want your translator to mess with your html or angular markup. Hopefully the translator doesn't know anything about html/angular and he very happy about that.
So this is more of tools problem, you should open a ticket against your tools - that being said we are opened to ease tool support as long as those stay placeholders.

**Comment by jaska45** [comment]
I see you point. However I find it hard to use. Here is why

Your comment approach does not help because at that point the translator does not see 

Hello {{ownerName}} and {{sellerName}}

He or she sees 

Hello <x id="INTERPOLATION"/> and <x id="INTERPOLATION_1"/>

When a localization tool provides an interface to edit above it has to inject some placeholder there. It might happen like this.

Hello {0} and {1}
or
Hello {INTERPOLATION} and {INTERPOLATION_1}

Anyay you cannot get rid of markup. Either it is localziation tools own markup or then it is the Angular markup. Now when an essential information is lost it will be hard to translate it even with a proper description comment.

What is the reason you cannot use the variable names in x.id but you use INTERPOLATION_x.

**Comment by vicb** [comment]
> What is the reason you cannot use the variable names in x.id but you use INTERPOLATION_x.

It could be any expression, not a variable only.

FYI there are also plans to add an exemple to interpolation `{{ person.children[0].name // ex('John') }}`

**Comment by jaska45** [comment]
Thank you. That makes sense. I will instruct developers to add comment like this
"INTERPOLATION = name of the owner
INTERPOLATION_1 = name of the seller"

Localization tools shows the text in a single line
"Hello {INTERPOLATION} and {INTERPOLATION}" 
with the above comment.
