### ISSUE TITLE
Cannot read property 'clicked' of null error

### ISSUE THREAD

**Issue by JackRichardBusiness** [angular/angular#12811]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On my Google Chrome extension, when retrieving getElementById('send').clicked, the error: 
Uncaught TypeError: Cannot read property 'clicked' of null(…)
I am running the latest Google Chrome version.

**Expected behavior**
I expect the program to read the properties of three other input tags, which have no issue currently, and return a URL.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
I am on Windows 10, Google Chrome

* **Browser:** Google Chrome

 
* **Language:** JavaScript, HTML

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
