### ISSUE TITLE
Directive can't inject host's ChangeDetectorRef

### ISSUE THREAD

**Issue by stringham** [angular/angular#12816]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If a directive injects a ChangeDetectorRef it receives the parent element's instance rather than the one on the host element.

I'm not sure if this is intentional, but it seems like there should be a way for the directive to use the host element's ChangeDetectorRef.

**Expected behavior**

A directive should be able to inject the host element's ChangeDetectorRef

**Minimal reproduction of the problem with instructions**

I created a directive called RenderOnce that detaches the change detector in ngAfterViewInit.

http://plnkr.co/edit/HKF7etipvdVdl65RaWLG?p=preview

I have two <counter></counter> elements that increment a number on an interval, one of them I add the directive, the other one I don't. But the directive detaches the parent component's change detector so they both only render once.

**Comment by dfala** [comment]
Any updates on fixing this bug? This is a UGE issue for me.

**Comment by hccampos** [comment]
@dfala seems like this is fixed in rc.2

**Comment by DzmitryShylovich** [comment]
@hccampos don't think so http://plnkr.co/edit/Aqjpv3KDrDJbnI43YdzC?p=preview

**Comment by hccampos** [comment]
@DzmitryShylovich that is right, never mind. Here the use case was a directive to integrate with MobX (https://github.com/mobxjs/mobx-angular) and in that case it is actually acceptable to get the parent's change detector, hence why I thought it had been fixed.

**Comment by tbosch** [comment]
This also happens when using `Injector.get(ChangeDetectorRef)`, see https://github.com/angular/angular/issues/14656
