### ISSUE TITLE
Cleanup queries (breaking changes)

### ISSUE THREAD

**Issue by tbosch** [angular/angular#12818]
Change the semantics of queries in the following way:
- all properties that have a query decorator (e.g. `@ContentChild`) should be filled when `ngOnCreate` is called. Right now, view queries are not set until we first calculated them, e.g. not until `ngAfterViewInit` for view queries (see https://github.com/angular/angular/issues/9689).
- `QueryList.changes.subscribe` should replay changes that happened in the same change detection cycle. E.g. queries are already filled before `ngOnCreate` if they can be statically calculated, but a user of `QueryList.changes` should not need to know about this fact. (see https://github.com/angular/angular/issues/9078).
- view queries should be updated _before_ we dirty check nested components. This way, users could still query and change nested components without getting a dirty checking error.
  * this would require views to have 2 dirty checking methods: `dirtyCheckLocal` and `dirtyCheckDeep`
  * we probably should also have a new lifecycle callback `ngAfterLocalViewChecked` / `ngAfterLocalViewInit` to allow users to listen for this event directly.
- make `afterContentChecked` exact:
  * right now, we call it a bit too late, i.e. when _all_ elements in this view and nested view containers have been checked

**Comment by tbosch** [comment]
Maybe put this behind a flag?!
- enable new behavior by default, but have a flag per component to use the old behavior

**Comment by StarpTech** [comment]
Hi, what's the status? I still run into #9689 with angular 6

**Comment by johanchouquet** [comment]
Hi there, do you have any updates on this ? I still meet this problem #9689 with Angular 7.
Just like @filipesilva replied back in 2016, in the ngOnInit method, the queryList is still `undefined`. It seems to have no workaround.

**Comment by tgrassl** [comment]
Still running into this problem. Are there any updates on this? 
Thank you @IlCallo, your trick works!

**Comment by xavadu** [comment]
Still running into this problem. Are there any updates on this?

**Comment by nelson6e65** [comment]
@IlCallo 🍻 Thanks!

**Comment by pkozlowski-opensource** [comment]
This one is obsolete with all the changes we did to the query system in ivy, closing.
