### ISSUE TITLE
Routing to the same route with different parameters fails in child component router

### ISSUE THREAD

**Issue by eXxi** [angular/angular#12827]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Routing to the same child component with different parameters fails due to the primary outlet not being available here: https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L853 .

**Expected behavior**
Routing should work.

**Minimal reproduction of the problem with instructions**
Just click on "SUB". http://plnkr.co/edit/9nwXdCesBnjZIzLrC17B?p=preview

**What is the motivation / use case for changing the behavior?**
I would like to change the parameters of the current route.

**Please tell us about your environment:**
Ubuntu 16.04, angular-cli 1.0.0-beta.19-3

* **Angular version:** 2.1.2

* **Browser:** Chrome 53
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   6.6.0

**Comment by DzmitryShylovich** [comment]
1. `{path: '' }`  is incorrect. Route have to have a `component` or `redirectTo`.
2. you always have to specify primary outlet.

Fixed version: http://plnkr.co/edit/05ZlEGQ4RFKUZJhLVv5e?p=preview
