### ISSUE TITLE
<tag/>Template Perth Error

### ISSUE THREAD

**Issue by kgtkr** [angular/angular#12828]
OK
<tag></tag>

Error
<tag/>

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by vicb** [comment]
`<tag/>` is invalid according to the HTML spec.
