### ISSUE TITLE
i18n, cannot resource text from attributes

### ISSUE THREAD

**Issue by jaska45** [angular/angular#12820]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If I have text in a HTML attribute like in the following placeholder attribute

 <input type="text"
        id="skuInput"
        placeholder="SKU text"
        name="sku" ngModel>

ng-xi18n does not resource it.

i18n attribute seems to tell xg-x18n to extract only the element text not the attributes.

**Expected behavior**

Some way to mark attribute to be extracted. Something like this

      <input i18n_placeholder type="text"
        id="skuInput"
        placeholder="SKU sample"
        name="sku" ngModel>

**Minimal reproduction of the problem with instructions**

import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
  <form #f="ngForm"
    (ngSubmit)="onSubmit(f.value)"
    class="ui form">

    <div class="field">
      <label i18n for="skuInput">SKU</label>
      <input i18n type="text"
        id="skuInput"
        placeholder="SKU sample"
        name="sku" ngModel>
    </div>
    <button i18n type="submit" class="ui button">Submit</button>
  </form>  
  `
})
export class AppComponent 
{ 
}

**What is the motivation / use case for changing the behavior?**

Make localization possible

**Please tell us about your environment:**

Windows 8.1, VS Code 2.0.9, NPM 3.10.8

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.0.9

* **Node (for AoT issues):** `node --version` =   

v6.9.1

**Comment by soyzamudio** [comment]
to extract placeholder attributes you use `i18n-placeholder` or `i18n-placeholder="<note>"`

**Comment by jaska45** [comment]
Thanks. I tried i18n_placeholder and i18nplacehold but foget i18n-placeholder
