### ISSUE TITLE
upgradeAdapter Change detection issue when emitting events from ngOnInit or object construction.

### ISSUE THREAD

**Issue by ryanlangton** [angular/angular#12838]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you emit an event from a child component ngOnInit, then set a flag on the parent as a result of that event and use an ngIf to evaluate that flag, the template is unable to render the *ngIf element.
As a secondary bug, if you're using upgradeAdapter, an exception is swallowed.  If you're not using the upgradeAdapter, the following error occurs:
Error in ./FeatureComponent class FeatureComponent - inline template:16:45 caused by: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'true'.

**Expected behavior**
Should be able to emit events in ngOnInit, or it should be documented that you can't do this.  A meaningful exception should be thrown whether you're using the upgradeAdapter or not.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/mspxruqKzHHnuuzs4z0M?p=preview

Run the plnkr.
Click on Hardcoded Employee.
Notice when we don't use *ngIf, it works, when we do, the *ngIf isn't evaluated.

Change the option to Option 3.
Click on Http Employee.
Notice how the *ngIf fails again.

Now go to main.ts
Comment the following code:
angular.module('myApp')
        .directive('root',
        <IDirectiveFactory>upgradeAdapter.downgradeNg2Component(Root));
        
 upgradeAdapter.bootstrap(document.documentElement, ['myApp'], { strictDi: true }); 

Uncomment the following code:
platformBrowserDynamic().bootstrapModule(AppModule);

Now repeat the steps above.  Same behavior but you will see template exceptions.

**What is the motivation / use case for changing the behavior?**
Change detection fails in what could be a common occurance.  This is very difficult to troubleshoot and took a very long time to find the root cause.

**Please tell us about your environment:**
Plnkr

* **Angular version:** 2.0.X
2.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
na

**Comment by gelliott181** [comment]
This issue is a little wider than event emitters if my most recent experience is anything to go by.

I've been tasked to integrate QuaggaJS barcode scanning in an Angular 2 app. I can scan things just fine, and the results are stored to a variable on the component, but my template bindings never update. Change detection fails using a function's return value or binding a variable directly, but only if the variable is mutated by a statement within the NgOnInit function, namely my Quagga callbacks. Implementing ngOnChanges to log whenever the variable changes also doesn't work when the result is updated by the Quagga callback confirming the change detection fails, while it logs fine when the variable is modified outside NgOnInit confirming it only seems to affect NgOnInit at the moment.

Reproduction Repo: https://github.com/gelliott181/ng2-quagga-issue
QuaggaJS Issue: https://github.com/serratus/quaggaJS/issues/146

**Comment by nodehack** [comment]
This problem occurs with something as simple as using an *ngIf to toggle 2 components.  

Here's a plunker showing a very simple implementation.  
http://plnkr.co/edit/qSPoI9IHbUQKocc8ibwb?p=preview (thanks ryanlangton for the template)

You'll see that as soon as you click the toggle button to toggle the component, the angular zone gets lost.

A workaround is to use NgZone's run function to put you back into angular's zone.  This seems really silly though.  I would expect all ng2 component lifecycle events should happen within angular's zone.

**Comment by ryanlangton** [comment]
We've resorted to using NgZone.run within all of our stream .subscribe methods.  It works but is obviously not ideal.  Thanks nodehack for demonstrating a much leaner example.

**Comment by DzmitryShylovich** [comment]
@ryanlangton pls add in the issue title that this is related to upgradeAdapter

**Comment by tbosch** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).
