### ISSUE TITLE
Router swallows the console.error when a match is not found

### ISSUE THREAD

**Issue by jsgoupil** [angular/angular#12839]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When navigating to an incorrect URL not handled in your router, the error is swallowed and you are navigated back to the / root.

**Expected behavior**
In core@2.1.2, router@3.1.2, when navigating to an incorrect route, we were getting the error like this
`Error: Cannot match any routes. URL Segment: 'abcd'
Error: Cannot match any routes. URL Segment: 'abcd'
    at ApplyRedirects.noMatchError (http://localhost:57448/node_modules/@angular/router/bundles/router.umd.js:769:20)
`

This seems to be a zone/promise issue that is not sent back to the console.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
It is really hard to figure out the error caused by the router.
A Plnkr cannot handle this routing error as it will return Not Found.

**Please tell us about your environment:**
Visual Studio 2015, IIS Express, npm@3.10.5

* **Angular version:** 2.2.0-rc0
    "@angular/common": "^2.2.0-rc.0",
    "@angular/compiler": "^2.2.0-rc.0",
    "@angular/compiler-cli": "^2.2.0-rc.0",
    "@angular/core": "^2.2.0-rc.0",
    "@angular/forms": "^2.2.0-rc.0",
    "@angular/http": "^2.2.0-rc.0",
    "@angular/platform-browser": "2.2.0-rc.0",
    "@angular/platform-browser-dynamic": "^2.2.0-rc.0",
    "@angular/router": "^3.2.0-rc.0",
    "@angular/upgrade": "^2.2.0-rc.0",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tried in Chrome
 
* **Language:**
TypeScript 2.0.6

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
Could you please check the latest builds, this is probably already fixed by https://github.com/angular/router-builds/commit/9e77e338815a618b2516f5627fa81a486684f765

use `@angular/router-builds, @angular/common-builds, ...`

**Comment by jsgoupil** [comment]
@vicb confirmed, fixed.

**Comment by vicb** [comment]
@jsgoupil Thanks for testing and reporting !
