### ISSUE TITLE
Compiler-cli will never compile if ngfactory doesn't exist

### ISSUE THREAD

**Issue by cortopy** [angular/angular#12835]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

According to the [compiler docs ](https://github.com/angular/angular/tree/master/modules/@angular/compiler-cli) and [angular.io](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html), in order to do Ahead of Time Compilation, there should be a `main.ts` file like this:

```typescript
import {MainModuleNgFactory} from '../aot/app/main.module.ngfactory';
import {platformBrowser} from '@angular/platform-browser';

platformBrowser().bootstrapModuleFactory(MainModuleNgFactory);
```

However, that will never work when I do 

```
./node_modules/.bin/ngc -p tsconfig.aot.json
```

I get the following error:

```
Cannot find module '../aot/app/main.module.ngfactory'
```

I've tried many different paths and alternatives and all give the same result. In the compiler docs, a sanity check is suggested. Indeed, if I run:

`./node_modules/.bin/tsc -p tsconfig.aot.json`

I get exactly the same error. This doesn't happen if I point the typescript compiler to the JIT main file (it compiles fine!)

**Expected behavior**
For what I gather, the ngfactory module is created dynamically during compilation. However, what I have seen suggests that the typescript transpiler generates a blocking error and compilation doesn't happen. The import referenced in the bootstrap file doesn't exist after all. I guess this behaviour is to be expected.

I would expect the angular typescript compilation wrapper to be able to step in and deal with what, otherwise, will be a constant error in the typescript transpiler.

**Please tell us about your environment:**

* **Angular version:** 2.1.2

* **Language:** Typescript 2.0.9

* **Node (for AoT issues):** 7

**Comment by vicb** [comment]
Please include a small repro. Thanks

**Comment by thelgevold** [comment]
I generally add main.ts and app.module to tsconfig.json under "files"

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },

  "files": [
    "app/app.module.ts", // This will ensure the ngFactory is created
    "app/main.ts"
  ],

  "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : true
 }
}
```

**Comment by cortopy** [comment]
thanks @thelgevold 
playing with `files` and their order has done the trick
