### ISSUE TITLE
FormDirectives should be const in Dart

### ISSUE THREAD

**Issue by kwalrath** [angular/angular#1283]
When using forms, you should be able to say this:

    directives: const[FormDirectives, If]

But FormDirectives isn't a const, so you need a workaround like this:

    directives: const[
      const[ //XXX: workaround for FormDirectives not being const.
        ControlGroupDirective,
        ControlDirective,
        CheckboxControlValueAccessor,
        DefaultValueAccessor],
      If]

**Comment by naomiblack** [comment]
@mhevery I think this is closed now? Can you confirm?

**Comment by pkozlowski-opensource** [comment]
Nope, there is a PR for this but its review is blocked on the decision on how to transpire const in Dart.

**Comment by naomiblack** [comment]
This is blocked on https://github.com/angular/angular/pull/1648

**Comment by mhevery** [comment]
Unblocked: https://github.com/angular/ts2dart/commit/2e0210353280e6c555722541fbb04d651df0c011 and @pkozlowski-opensource  is working on merging it in.
