### ISSUE TITLE
Async/Await

### ISSUE THREAD

**Issue by John0x** [angular/angular#12834]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Hello, since TypeScript 2.1 finally seems to support async/await while targeting es5 it would be time to take adavantage of that, right?
Are there any plans to support Typescript 2.1 in the near future?

**Comment by vicb** [comment]
The plane is to bump TS requirement to 2.0 for the next Major release (3.0) beginning of next year.
Still we will probably not move to the bleeding edge.

Note that you should be able to use any version of TS > 1.8 for your app.
