### ISSUE TITLE
Unable to create custom Decorator using angular-cli with AoT compiler

### ISSUE THREAD

**Issue by dotansimha** [angular/angular#12846]
**I'm submitting a bug report ** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Unable to create custom TypeScript decorators when using AoT compiler.

Reproduce steps:
- Create new angular-cli project. 
- Run project using: `ng serve --port 3000` (serve without AoT)
- Create a new decorator and use it in one of the `Component`s:
```ts
function test(props: any) {
      return function(target: any) {
           console.log("Running decorator...", props, target);
      }
}

@Component({
     template: "Hello!"
})
@test({})
class MyComponent {
    // ...
}
```
- Note that the logic of the decorator works great and executed (printed to the browser's log).
- Now close the cli, and run again, now the command: `ng serve --aot --port 3000` (serve with AoT)
- The decorator is stripped from the Component and the logic of the decorator does not executed.

The generated factory file contain the actual decorator logic, but it does not execute it when creating the Component.

Tried to change `angularCompilerOptions` and change `skipMetadataEmit` - but still the same.

When running with JIT compiler all works, only AoT compiler causes problems.

**Expected behavior**
The decorator should execute when using AoT compiler.

**Minimal reproduction of the problem with instructions**
In the description above.

**What is the motivation / use case for changing the behavior?**
Same compiler behavior for AoT and regular compiler.

**Please tell us about your environment:**
```
Dotans-MacBook-Pro:~ dotansimha$ ng --version
angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: darwin x64
```

* **Angular version:** 2.1.0

* **Browser:** all

* **Language:** all / TypeScript?

* **Node (for AoT issues):** `node --version` =   
```
Dotans-MacBook-Pro:~ dotansimha$ node --version
v6.9.1
Dotans-MacBook-Pro:~ dotansimha$ npm --version
3.10.8
Dotans-MacBook-Pro:~ dotansimha$ watchman --version
4.7.0
```

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/2799

**Comment by dotansimha** [comment]
@DzmitryShylovich thanks. closing.
