### ISSUE TITLE
Allow customizing SAFE_URL_PATTERN in url_sanitizer.ts

### ISSUE THREAD

**Issue by arg20** [angular/angular#12840]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It is not possible to customize which URLs are considered safe.

**Expected behavior**
A user could customize the REGEX used to match safe urls.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
When you are using ionic 2, Android will usually return URLs that begin with `content://`. Then you have to explicitly call `bypassSecurityTrustUrl` to be able to show them. In Angular 1 you could customize this by injecting `$compileProvider` and calling: `$compileProvider.imgSrcSanitizationWhitelist(/^\s*(https?|ftp|file|blob|content):|data:image\//);`. But there's no convenience alternative for angular 2.

**Please tell us about your environment:**
N/A

* **Angular version:** 2.0.X
2.2.0-rc.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   7.1.0

**Comment by laco0416** [comment]
maybe relates to #12045 as a request for sanitization.

**Comment by rjamet** [comment]
Hi,

In the general case, I think that wasn't included on purpose, as it's hard to reason locally about security if other code (especially third-party modules you don't look into) can mess with your global settings. That being said, it sounds super annoying in your case...

More specifically, could you share a high level overview of some code doing that? I'm not that knowledgeable about Android, Ionic 2 and so on. I haven't seen content:// URIs in Ionic's doc and the [Android doc](https://developer.android.com/guide/topics/providers/content-provider-basics.html#ContentURIs) about these URIs doesn't make much sense to me in this context :/

And finally, for a lighter fix with the current Angular, I'd recommend a simple pipe that checks that your URL starts with content:// and just marks your input trusted if so?

**Comment by arg20** [comment]
> More specifically, could you share a high level overview of some code doing that? I'm not that knowledgeable about Android, Ionic 2 and so on. I haven't seen content:// URIs in Ionic's doc and the Android doc about these URIs doesn't make much sense to me in this context :/

Sure, since Android KitKat some Android APIs return URIs with `context://`, this, for instance is the issue that [this person](http://stackoverflow.com/questions/22682770/unable-to-display-contact-photo-in-phonegap-through-angularjs) has in angular 1.x

Ionic 2 is still in beta, hence why a lot of people aren't struggling with this yet. If you go to their forums for version 1, you'll see [that moderators suggest this answer](https://forum.ionicframework.com/t/image-displaying-issue-with-ng-repeat/3768/9).

Ultimately, I feel that there should be _some_ way for a developer to customize what urls are considered safe. Specially for this kind of use case. Angular 2 promises to deliver an amazing mobile development experience, and I think it's fairly reasonable to expect native mobile integrations to return urls that might differ from every day web urls.

BTW, the `content://` urls are a consequence of the [MediaStore](https://developer.android.com/reference/android/provider/MediaStore.html) API introduced in KitKat. [Ref](http://stackoverflow.com/questions/20067508/get-real-path-from-uri-android-kitkat-new-storage-access-framework)

I hear this kind of thing happens in [Windows Phones as well](http://stackoverflow.com/questions/30373565/windows-phone-8-ionic-app-navigation-issuehybrid-application/33761796#33761796).

**Comment by mprobst** [comment]
Thanks for the explanation! We'll need to assess whether we can generally trust `content://`. @rjamet is out for a week, but we'll get back to it.

For the time being I'd recommend writing a pipe so you can write:

```html
<img src="{{ something | trustContentUrl }}">
```

Make sure to validate it's a `content://` URL in the expected format.

**Comment by rjamet** [comment]
Hi ! sorry for the delay. Overall it looks fine to trust anything with these prefixes, our general type contract is "URLs that are safe to go to", which here means they cannot trigger unwanted actions. So content:// seem okay for security, and potentially the Windows Phone equivalent if it follows the same pattern.

I don't like including them in the URL whitelist as default, since they don't make sense in most platforms, and I'm not sure either about exposing the URL sanitization whitelist for the global settings reason explained above. A config function triggering support could make sense, but it's a half measure and adding a few for each platform seems weird. 

Having to use a pipe a few times is a little annoying, but on the other hand it seems to be the cleanest way of doing this in a misuse-resistant way, and providing that pipe in Angular or a mobile-centered module seems to make sense. It could also look at the current user agent and only trust the relevant schemes, maybe ?

**Comment by mprobst** [comment]
Maybe we should specialize the DOM sanitizer for apps running on Android? @vicb, can you route this to the right folks at ionic?

**Comment by vicb** [comment]
@arg20 could you please re-open this on the ionic repo ?

/cc @mlynch
