### ISSUE TITLE
Property binding to the object does not work!

### ISSUE THREAD

**Issue by tx8821** [angular/angular#12848]
I've described the issue in this stackoverflow post: http://stackoverflow.com/questions/40578305/property-binding-to-the-object-does-not-work-in-angular-2

Hope I'm not violating rules by linking it here.

It seems either a significant bug or significant documentation issue. If such behavior is expected, it should be documented.

angular-cli: 1.0.0-beta.19-3
angular: 2.1.2

**Comment by DzmitryShylovich** [comment]
> Hope I'm not violating rules by linking it here.

you're right, this issue tracker is not suitable for support requests.

Try to use `ngValue` instead of `value` 
here's an example https://plnkr.co/edit/HS9yDCxSGni9sziexu9u?p=preview

**Comment by tx8821** [comment]
@DzmitryShylovich thank you, [ngValue] worked instead of [value]. But why? Where (in the docs) can I find more about ngValue vs value differences, and when to use which? In tour of herous tutorial there was binding to value (not ngValue), and I wouldn't think that ngValue would be required. I think this behaviour needs to be explicitly documented. (Or if it is, could you please point me to it?)

**Comment by DzmitryShylovich** [comment]
Feel free to file docs issues on https://github.com/angular/angular.io/issues if anything is not clear for you.

**Comment by vicb** [comment]
I'n not sure this is the right fix.

Anyway reported issues must provide the information asked in the template. Re-open if still an issue.
