### ISSUE TITLE
Observer displayed with ngFor nested in ngIf does not display the right value

### ISSUE THREAD

**Issue by Mathou54** [angular/angular#12856]
```
[x ] bug report
```

http://plnkr.co/edit/glqjC6CFQDzSn1pJHHgF?p=preview

In this plnkr, the same observer is used to display a list via 2 ngFor. The ngFor nested in the ngIf is always out of sync with the one outside of the ngIf. The 2 list should display the same thing at the same moment, it is the same object.

**Comment by ericmartinezr** [comment]
This is not a bug, but how it works currently. Everytime you use the async pipe you're creating a new subscription and they're independent of each other. See this plnkr using the `share` operator http://plnkr.co/edit/wbmwZaS8LXl5lWeUYSPe?p=preview, see also this issue that proposes a solution for this https://github.com/angular/angular/issues/12237

**Comment by Mathou54** [comment]
But there is still a problem with your solution:
The letter 'a' appear only one time. Then when the second letter appear, 'ab' is written twice. So if for instance I put only one letter (first change), the list inside the ngIf is invisible.

http://plnkr.co/edit/jVmQOlituyqxpKlMltp9?p=preview

**Comment by ericmartinezr** [comment]
Here's another solution http://plnkr.co/edit/E0f8H0RefpVwwZx8527c?p=preview using ReplaySubject. In this case I'm not sure how many subscriptions are there (probably 3 but they're all receiving at the same time). 

I want to insist in that this is not a bug (don't take it wrong) but how observables and the async pipe work (they can be confusing sometimes). I think this will be solved by the issue I referenced in my first comment, and if that's not the case, there are other operators/observables that can make the magic happen. 

Note that I'm not proficient with Observables, probably someone else can come up with a better solution.

PS: If you think this could/should be documented, you're free to open an issue in the website's repo https://github.com/angular/angular.io

**Comment by Mathou54** [comment]
The thing is that I came from an observable from a FormControl. So when I map the value for my result and I flatMap to ReplaySubject, there is still the problem.

http://plnkr.co/edit/jVmQOlituyqxpKlMltp9?p=preview

The first time it runs, with the first letter in the input, we can still see the out of sync. And it is only the first time, on the first letter in the input.

**Comment by ericmartinezr** [comment]
http://plnkr.co/edit/RdT6kD4K5H78BD2nQZwP?p=preview

This is not a bug, but a support request. If you have any doubts you can go to [gitter's chatroom](https://gitter.im/angular/angular) or StackOverflow, for more info on why github is not the best place for asking support questions see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by Mathou54** [comment]
Indeed, the last plunker works very well. And yes, I should have change this issue into a support request earlier.
