### ISSUE TITLE
EXCEPTION: Expression has changed after it was checked. Previous value: ''. Current value: 'undefined'.

### ISSUE THREAD

**Issue by aezco** [angular/angular#12858]
I am getting errors with dynamic input fields. The error is:

>  Expression has changed after it was checked. Previous value: 'input'. Current value: 'undefined'.

```html
           <div class="input">
          <div *ngFor="let inputDynamic of inputs;">
            <ion-input type="text" [(ngModel)]="inputDynamic.descriptionTimeTable" class="timeline-input style-1 inputDynamic-top" formControlName="eventDescription" placeholder="eventDescription"></ion-input>
            <!--<ion-datetime [(ngModel)]="inputDynamic.dateTimeTable" class="timeline-input style-1" displayFormat="HH:mm" min="2016" formControlName="eventDescriptionTime" placeholder="eventDescriptionStartTime"></ion-datetime>-->
          </div>
        </div>

 <button ion-button (tap)="addInput()">
            <ion-icon class="input-container-icon" name="add"></ion-icon>
          </button>
```

```ts
  this.inputs = new Array();

     addInput() {
    var newItemNo = this.inputs.length+1;
    this.inputs.push({id: newItemNo,descriptionTimeTable:null, dateTimeTable:null})
    console.log(this.inputs);
  }
```

**Comment by DzmitryShylovich** [comment]
See http://stackoverflow.com/questions/34364880/expression-has-changed-after-it-was-checked/34364881#34364881
This issue tracker is not suitable for support requests, please use [StackOverflow](http://stackoverflow.com/) with tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vicb** [comment]
1) Please add a support channel for support question,
2) If you suspect an issue then you need to fully fill out the issue template,
3) you should use a `trackBy` and track item by id on your ngFor.
