### ISSUE TITLE
include bootstrap 3 globally

### ISSUE THREAD

**Issue by finalight** [angular/angular#12852]
how do I apply bootstrap globally to all the components?

I tried including bootstrap at index.html but the components don't render the bootstrap effect

**Comment by laco0416** [comment]
Hello. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
