### ISSUE TITLE
Tracking: Watch Mode for AoT compiler

### ISSUE THREAD

**Issue by tbosch** [angular/angular#12867]

**Comment by blacksonic** [comment]
@tbosch what is the ETA of this feature?

**Comment by tbosch** [comment]
@blacksonic hopefully we will have this in late spring for 4.0...

**Comment by wenerme** [comment]
4.1.2 now, any progress ?

**Comment by Joge97** [comment]
@tbosch any progress?

**Comment by tbosch** [comment]
That's done now. We have a new internal api that we will make public eventually once it has proven to be stable enough. See https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/api.ts. This is modeled like the TypeScript API, and incremental compilations are done by passing an `oldProgram` when calling `createProgram`.

The command line `ngc` also has a `-w` option now that watches the file system and we see speedups for subsequent builds of up to 10x, as we have some logic in place to only compile components in node_modules 1x.

**Comment by darekf77** [comment]
@tbosch I having issue with very high cpu useg in in ngc watch mode... (~160%-190%)  Do you know something about it ? I am using: mac osx sierra high, node 9.4, ngc 1.7.4 and typescript 2.6.2... Thanks for any help.

**Comment by darekf77** [comment]
Hi @tbosch. Thanks for any help with this issue https://github.com/angular/angular/issues/23570.
