### ISSUE TITLE
dynamic templateurl 

### ISSUE THREAD

**Issue by finalight** [angular/angular#12862]
Are there any example as to render different template in a single component based on certain conditions being fulfilled?

given route '/app', i want to render component/template A if the user A is logged in, and render component/template B if user B is logged in

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
