### ISSUE TITLE
ng-xi18n does not extract ICU message

### ISSUE THREAD

**Issue by reynardmh** [angular/angular#12863]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ng-xi18n does not extract ICU message

**Expected behavior**
ng-xi18n should extract ICU message to messages.xlf

**Minimal reproduction of the problem with instructions**
https://github.com/reynardmh/bugreport-angular2-i18n

**What is the motivation / use case for changing the behavior?**
bug fix

**Please tell us about your environment:**

MacOS Sierra 10.12.1 (16B2555), Webstorm, angular-cli: 1.0.0-beta.19-3, npm: v3.10.8, node: v7.0.0

* **Angular version:** 2.1.0

* **Browser:**  N/A

* **Language:** typescript 2.0.9

* **Node (for AoT issues):** `node --version` =   v7.0.0

**Comment by vicb** [comment]
This is a known limitation (see opened issues). We'll work on it soon.
