### ISSUE TITLE
AppView.detectChanges 100% all the time

### ISSUE THREAD

**Issue by iwoogy** [angular/angular#12864]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Page with 4 forms with 5 inputs per forms.
When page is displayed, AppView.detectChanges go to 100%.
After some time, it freezes the tab on Chrome.

**Expected behavior**
Not using that much CPU.

**Minimal reproduction of the problem with instructions**
The template html is about 600 lines. I'm not sure how to simply reproduce it.

**What is the motivation / use case for changing the behavior?**
The issue makes the web app not usable.

**Please tell us about your environment:**
OS X: 10.11.6
Computer: MacBook Pro 2015 15"

* **Angular version:** 2.0.X
Version: 2.1.2
[package.json](http://pastebin.com/yYx26sDP)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.6

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by iwoogy** [comment]
Profiler
![2016-11-14_22-56-43](https://cloud.githubusercontent.com/assets/479162/20271809/98e7ed0e-aabe-11e6-8a76-3ea6ea5f23ba.png)

**Comment by iwoogy** [comment]
The plunkr would be a bit difficult to do.

I was wondering if there is a way to trace the change detection mechanism to find out where the problem might come from.

**Comment by DzmitryShylovich** [comment]
> The plunkr would be a bit difficult to do.

then provide a minimal repository. Without repro it's not actionable.

**Comment by iwoogy** [comment]
Ok I understand.

I will prepare a plunkr and let you know.

Thanks

**Comment by iwoogy** [comment]
I finally find out where the problem came from.

For each input, I was using md-spinner to give user feedback on auto saving feature.

For each input I used [hidden] to have a smoother fade in out transition instead of *ngIf.

So my mistake was to use [hidden] since the md-spinner was created and hidden.

It appears that if you have more than 3 spinners alive, the CPU goes to 60% and up.

I replace all the [hidden] by *ngIf in order to have only one spinner at a time, and now, it's much better.

CPU is almost not used when displaying forms as expected.
