### ISSUE TITLE
How do I access an ngModel's FormControl from a Directive/Component

### ISSUE THREAD

**Issue by gitnik** [angular/angular#12866]
I'm not talking about the value of the ngModel but rather the `FormControl` associated with that model. What I want to do is add an entry to that `FormControl`.

```typescript
@Directive({
    selector: 'input',
})
export class InputDirective implements OnInit {
    constructor(private element: ElementRef) {
        debugger;
    }

    ngOnInit() {
        // how to I access the FormControl from here?
    }
}
```

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gitnik** [comment]
I guess this could technically be filed as a documentation issue since there is not mention of it, but I'll let it slide 😉
