### ISSUE TITLE
Navigator back button wrong work

### ISSUE THREAD

**Issue by gerkra** [angular/angular#12861]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Pressing the back button does not change the url and not saved a single step history

**Expected behavior**

Pressing changes the view and url buttons back, saved the entire history of transitions 

**Minimal reproduction of the problem with instructions**

There are three links
1. http: // localhost: 8080 / events
2. http: // localhost: 8080 / systems
3. http: // localhost: 8080 / requests

The sequential switching from first to third, by pressing the back button (3 -> 2), the view is changing, but remains the same url (№3), press again (2 -> 1) returns view №3 and url №2

**What is the motivation / use case for changing the behavior?**

There are three links
1. http: // localhost: 8080 / events
2. http: // localhost: 8080 / systems
3. http: // localhost: 8080 / requests

The sequential switching from first to third, by pressing the back button (3 -> 2), change view, url becomes №2, press again (2 -> 1) returns view №1 and url №1

**Please tell us about your environment:**

OS: Windows 7/10
IDE: IntelliJ IDEA 2016.2.4
Package manager: NPM
HTTP server: Webpack Dev Server OR NodeJS

* **Angular version:** 2.0.X

Version: 2.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome: 54.0.2840.71 m 
Firefox:   49.0.1
Opera:    41.0.2353.56

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript:  1.5.3
* **Node (for AoT issues):** `node --version` =   
Node version: 7.0.0

**Comment by DzmitryShylovich** [comment]
Pls add a repro.

And ensure u call `RouterModule.forRoot` only once in `AppModule`.

**Comment by marvinscharle** [comment]
I have a similar problem with the router when using the back button:

When the user presses back, the view changes to the previous route, the url stays the same. Another press on back updates the url but not the view.

The next press on back changes the view but not the url - and so on.

When using the router with `skipLocationChange: true` and the user clicks on back the router will change the url to the location that has been skipped first, afterwards it behaves as described above.

Very strange.

**Comment by DzmitryShylovich** [comment]
It's not actionable without reproduction. 
Usually there're problems with back button when u call RouterModule.forRoot more than 1 time.

**Comment by marvinscharle** [comment]
@DzmitryShylovich there is only one `RouterModule.forRoot` in the project.

**Comment by vicb** [comment]
Please add a small repro

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have reproduce scenario.
