### ISSUE TITLE
Docs: Use of `forEach` in Routing & Navigation guide can create memory leak

### ISSUE THREAD

**Issue by studds** [angular/angular#12879]
**I'm submitting a ...**  

```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

This is a documentation defect. The use of `forEach` in [Routing & Navigation guide](https://angular.io/docs/ts/latest/guide/router.html) seems as though it can create a memory leak. (As I understand...)

**Expected behavior**

The docs should use `subscribe` instead, and unsubscribe in `onDestroy`, or alternatively use `map` plus the `async` pipe.

Forgive me if I've got the wrong end of the stick here, but it seems important to be clear on this point in the docs. If there's actually no need to unsubscribe, it would be good to explain why in the docs.

**Comment by vicb** [comment]
Could you please re-open the issue on https://github.com/angular/angular.io which is the docs repo ?

Thanks
