### ISSUE TITLE
Debugging Angular 1.5 app with UpgradeAdapter

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular#12873]
I'm working on the Augury team and noticed that the window.ng variable is not defined when debugging an Angular 1.x app using UpgradeAdapter.

Is it possible to make ng variable available?  for calls to ng.probe($0) to work.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Using DevTools & Augury, unable to inspect Angular 1.x app.

**Expected behavior**
Expecting to see Angular app properties from devtools, augury.
Write an Angular 1.x app and use UpgradeAdaptor. 
Use devtools to inspect app using ng.probe, install Augury and open Augury tab from devtools.

**What is the motivation / use case for changing the behavior?**
Allow developers to debug and inspect their app during their upgrade to Angular 2.

**Please tell us about your environment:**
Mac OS, Angular 1.5 + Angular 2.2.0

* **Angular version:** 2.0.X
Verified with 2.2.0 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.3
* **Node (for AoT issues):** `node --version` =   
node 6.7.0

**Comment by gkalpak** [comment]
This is no longer an issue with the static version of ngUpgrade.
