### ISSUE TITLE
mouseleave/mouseout and mouseover/mouseenter called multiple times when using ngFor

### ISSUE THREAD

**Issue by ejaury** [angular/angular#12874]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 
```

**Current behavior**

I'm using ngFor to generate "li" elements with "mouseout" and "mouseenter" events.

```
<li *ngFor="let star of stars; let i = index;"
	[ngClass]="star"
	(mouseout)="mouseLeaveStarEvent($event)"
	(mouseenter)="mouseOverStarEvent(i, $event)"
	(click)="toggle(i, $event)"
	attr.aria-label="{{i+1}} star">
	<div class="ms-Icon ms-Icon--star" [ngClass]="star"></div>
</li>
```

When I keep moving my mouse pointer inside one "li" element, the mouseout and mouseenter handlers get fired multiple times.

Plunkr: https://plnkr.co/edit/D65CFnO7YIU1ile3lxaV?p=preview

**Expected behavior**

If I keep moving my mouse pointer inside one "li" element, I expect that mouseenter only gets called once the first time i enter that element, and mouseout to be called once when I leave that element.

The workaround right now is to NOT use ngFor by list all "li" elements manually.

* **Angular version:** 2.0.0

* **Browser:** Chrome

 
* **Language:** Typescript

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by vicb** [comment]
any chance `stars` array is a new array on each CD cycle ?

**Comment by ejaury** [comment]
The `stars` array is updated on mouseover/mouseleave.

**Comment by skreborn** [comment]
@vicb It was indeed a new array on each cycle, but changing that didn't help.

@ejaury I think the root of the problem is that `mouseleave` does one thing, and `mouseenter` does another, and they pretty much conflict. An easy solution to your problem would be to set `mouseleave` up on the `<ul>` element, [like so](https://plnkr.co/edit/YEavAcxeGmSFtct4zAHa?p=preview).

In any case, this sounds like a support request, rather than a bug, so let me redirect you to an [appropriate channel](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem), should you need any further assistance. If you still believe this to be a bug, please, let us know.

**Comment by vicb** [comment]
thanks @skreborn

**Comment by SS-jin** [comment]
@skreborn thanks for your answer, as i got the hint for my problem from your comment, what i was doing that i was making and ajax call on mouse over while passing true for 'async' parameter of dopost, once i changed it to false, it all worked fine, now the event handler is called only once !   Thank you !

**Comment by yu87109** [comment]
hello， i  get some mouseenter problems like you.  i donot know why, can you help me ?
![image](https://user-images.githubusercontent.com/36869615/59191091-189e2380-8bb1-11e9-8617-a3fcaf0a123d.png)

the panel component html:

```
<div>
  <panel-item 
    *ngFor="let item of panelItemData" 
    [itemData]="item" 
    (itemClick)="itemClick($event)"></panel-item>
</div>
```

the item component html:

```
<div 
  [ngStyle]="style" 
  (click)="mouseEvent($event)" 
  (mouseleave)="mouseEvent($event)" 
  (mouseenter)="mouseEvent($event)" 
>{{data.text}}</div>
```

the item component ts:

```
@Component({
  selector: 'panel-item',
  templateUrl: './item.component.html',
})
export class PanelItemComponent implements OnInit {
  @Input('itemData') data!: panelItemData;
  @Output() itemClick = new EventEmitter<panelItemClickEvent>();

  _textColor!: string;
  _mouseColor!: string;
  style!: { cursor: string, color: string };

  ngOnInit() {
    this._textColor = this.data.textColor || 'orange';
    this._mouseColor = this.data.mouseColor || '#fe007f';
    this.style = { cursor: 'pointer', color: 'orange' };
  }
  mouseEvent(event: MouseEvent) {
    console.log(event.type)
    switch (event.type) {
      case 'mouseenter':
        this.style.color = this._mouseColor;
        break;
      case 'mouseleave':
        this.style.color = this._textColor;
        break;
      case 'click':
        this.itemClick.emit({ itemCode: this.data.code });
        break;
    }
  }
}
```
