### ISSUE TITLE
docs: Modules, routing - lazy loaded modules with webpack

### ISSUE THREAD

**Issue by klinki** [angular/angular#12888]
There is no explanation in documentation that you have to use angular2-router-loader in order to use lazy loaded modules configured in routing.

This should be at least on webpack page. I think link could be also on modules page and FAQ.

**Comment by DzmitryShylovich** [comment]
Pls submit docs issues on https://github.com/angular/angular.io/issues

**Comment by klinki** [comment]
Sorry, I was little bit confused when I noticed docs tag in this repository.
I created issue in docs repo: https://github.com/angular/angular.io/issues/2801

**Comment by klinki** [comment]
I'm reopening this, since docs is now part of main repo.

**Comment by kapunahelewong** [comment]
Hey @klinki I'm not familiar with angular2-router-loader (and imagine it's different now) but if this is still something that needs to be covered in the docs, I'm happy to do it, I'd just need your help on the details of it. We've just recently re-organized and fleshed out the NgModules related documentation and now have a doc dedicated to [Lazy Loading Feature Modules](https://angular.io/guide/lazy-loading-ngmodules). (There's a PR to be merged that fixes the example, btw). That page doesn't mention a router loader though and I didn't have to use one to make the example. Do you think there's more to do in this direction?

**Comment by jelbourn** [comment]
Closing this as obsolete
