### ISSUE TITLE
Minification & Bundling : Angular2 VS2015

### ISSUE THREAD

**Issue by SrinivasKothapalli** [angular/angular#12883]
**Need tools that will do minification & bundling in VS2015.**  (check one with "x")
```
 
```

**Current behavior**
   It is loading all 45 MB files in LoginPage itself.

**Expected behavior**
  It should load fast and should minimize to max 2MB.

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Angular2 | Vs2015]

**Comment by vicb** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
