### ISSUE TITLE
Runtime compiler is not loaded in AOT service

### ISSUE THREAD

**Issue by sunnylearn** [angular/angular#12885]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**app.js?1479195046940:141 Error: Runtime compiler is not loaded
    at t (app.js?1479195046940:141)
    at e.compileModuleAndAllComponentsAsync (app.js?1479195046940:141)
    at e.compileComponent (app.js?1479195046940:115)**

**Expected behavior**
Compiler can be loaded。

**Minimal reproduction of the problem with instructions**
    file:*.service.ts*
  
    compileComponent(componentSelector:string, viewContainerRef:any, callBack:any) {
        return this.compiler.compileModuleAndAllComponentsAsync(this.dynamicLoadModule)
          .then((moduleWithFactories:ModuleWithComponentFactories<any>) => {
              const factory = moduleWithFactories
                .componentFactories.find((x : any) => x.selector === componentSelector);

              let componentRef = viewContainerRef.createComponent(factory, 0);
              if (typeof callBack === 'function') {
                  callBack(componentRef);
              }
          });
    }

**Please tell us about your environment:**
mac phpstorm

* **Angular version:** 2.1

* **Browser:** [all | Chrome 54 ]

 
* **Language:** [all | TypeScript 2.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by sunnylearn** [comment]
@vicb ,this issue only in AOT compile

**Comment by DzmitryShylovich** [comment]
Compiler in not available in aot. See https://github.com/angular/angular/issues/11780

**Comment by sunnylearn** [comment]
@DzmitryShylovich, Is there a solution to this problem?

**Comment by laco0416** [comment]
@sunnylearn I'm using RuntimeCompiler in `platformBrowser` with few hacks. 

1. Add `COMPILER_PROVIDERS` into `platformBrowser()`

```
import { COMPILER_PROVIDERS } from '@angular/compiler';

platformBrowser(COMPILER_PROVIDERS).bootstrapModuleFactory(AppModuleFactory);
```

2. Provide `RuntimeCompiler` as `Compiler`

```
providers: [
  { provide: Compiler, useExisting: RuntimeCompiler }
]
```

This is not a standard way, so please don't forget nobody knows when we can use this workaround until.

**Comment by sunnylearn** [comment]
@laco0416 ,tks!

**Comment by arwindgao** [comment]
@laco0416 hi, i tried ur workaround and met an exception below:
No ResourceLoader implementation has been provided. Can't read the url 'xxxx'.
And i also do some researches and find the potential [reason](http://stackoverflow.com/questions/39659389/cant-read-the-url-error-for-angular2-dynamic-components-with-templateurl), but the answers may not works with AoT (Compiler or Custom ResourceLoader).
Would you like help on this?
Thanks in advanced.

**Comment by patrikx3** [comment]
Same error here, I cannot use dynamic compiler.
I need both AOT and the compiler. Why cannot I add it in?

**Comment by ashwinirajput** [comment]
Same issue Runtime compiler is not loaded when i am using plunker ng2-date-time-picker

**Comment by shanurrahman** [comment]
Don't eagerly import something from a lazy loaded module
It's a common mistake. You've arranged to lazy load a module. But you unintentionally import it, with a JavaScript import statement, in a file that's eagerly loaded when the app starts, a file such as the root AppModule. If you do that, the module will be loaded immediately.
