### ISSUE TITLE
Http headers (Accept-Language) gets overridden in Android browser

### ISSUE THREAD

**Issue by hasher** [angular/angular#12886]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Setting the accept language header to use e.x. it, the android browser overrides it to the mobiles default language.

**Expected behavior**

If explicitely given the accept language header, it should overtake this

**Minimal reproduction of the problem with instructions**

Add custom headers to http calls in angular2 and use Fiddler to investigate the headers. The headers are overriden instead of taking the explicitely given one

**What is the motivation / use case for changing the behavior?**

Controlling the language of your app.

**Please tell us about your environment:**

Android device (Samsung S5), the default browser which is installed

* **Angular version:** 2.0.X

2.1.0

* **Browser:** [Android Web Browser ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   v4.6.0

**Comment by vicb** [comment]
Not enough information provided:
- missing a repro,
- some fixes have been made in the latest release that might help, please try on angular 2.2.0.
