### ISSUE TITLE
Component styleUrls referred css files cannot relative loading background image. 

### ISSUE THREAD

**Issue by dashng** [angular/angular#12881]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Component styleUrls referred css files cannot relative loading background image. 
**Expected behavior**

Component styleUrls referred css files load relative loading background image according css file's path.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 TypeScript 2.0.3 ES5
* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
There is nothing we can do without a repro, please attach a minimal one.

**Comment by dashng** [comment]
Hi, vicb

I try to duplicate the issue on Plunker, But it seems styleUrls not worked on.

Try to explain with some code:

Component loading the styles with stylesUrl.
component.ts
```
@Component({
  selector: 'my-hero-detail',
  stylesUrl: ['static/css/styles.css'],
  moduleId: module.id,
  template: `
    <div class="testclass">
      dddddddd
    </div>
    <div *ngIf="hero">
      <h2>{{hero.name}} details!</h2>
      <div><label>id: </label>{{hero.id}}</div>
      <div>
        <label>name: </label>
        <input [(ngModel)]="hero.name" placeholder="name"/>
      </div>
    </div>
  `
})
export class HeroDetailComponent {
  @Input()
  hero: Hero;
}

```

styles.css code:

```
.testclass{
    min-width: 150px;
    min-height:150px;
    background: url(static/img/test.jpg) no-repeat;
}
```

folder structure:
 |—— components
        | ______________ component.ts
        | ______________ static
                                 |________css
                                              |________ styles.css
                                 | _______ img
                                              |________ test.jpg

**Comment by dashng** [comment]
@vicb

**Comment by dashng** [comment]
@vicb 

css can't load the test.jpg according to the module path (moduleId).

**Comment by dashng** [comment]
@vicb 

Any suggestions on this issue?

**Comment by dashng** [comment]
@vicb

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by adros** [comment]
I was facing the same issue, and it was solved after updating webpack and related packages to latest 

    +    "@types/webpack": "^3.0.12",
    +    "add-asset-html-webpack-plugin": "^2.1.2",
    +    "extract-text-webpack-plugin": "^3.0.0",
    +    "ngc-webpack": "^3.2.2",
    +    "webpack": "^3.6.0",
