### ISSUE TITLE
ActivatedRoute different in service than in component?

### ISSUE THREAD

**Issue by piernik** [angular/angular#12884]
I have `resolve` statement in my route.
When I try to access it in my component's ngOnInit using `ActivatedRoute` resolved data is where it should be - in `ActivatedRoute.snapshot.data`.
But when I inject to that component my service and try to get resolved data using that service, `ActivatedRoute.snapshot.data` is empty. Why?

Is it a bug?

**Comment by skreborn** [comment]
I think that this is by design. Please see the docs for [`ActivatedRoute`](https://angular.io/docs/ts/latest/api/router/index/ActivatedRoute-interface.html).

> Contains the information about a route associated with **a component** loaded in an outlet.

It's probably just that services are not supposed to know anything about routing - it's not their purpose.

**Comment by dejour** [comment]
ActivatedRoute can't be injected to service, it's related to component.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
