### ISSUE TITLE
dynamic ng-options population with $http in IE9

### ISSUE THREAD

**Issue by olegakbarov** [angular/angular#1289]
Probably already been discussed here, but i came across the following issue — i have a list of items,  fetched via $http. This list populates ng-options. All works fine everywhere ... except IE9.

Anything i can do about it?

Angular 1.3.13

**Comment by pkozlowski-opensource** [comment]
@olegakbarov please ask general support questions like this one using a dedicated support channel, see : https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Don't forget to provide clear, minimal, live reproduce scenario so people can actually help you - IMO it is impossible to help you with your question in the current form - there is just not enough context...
