### ISSUE TITLE
Make decorators tree-shake out with rollup

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#12898]
This is a tracking issue, for which we've had some design discussion but have not settled on an approach yet.

In ngc, we use angular/tsickle to "down-level" the Decorators into annotations, which are just static properties assigned to a static data structure. Closure compiler can tree-shake out the unused components.
However, rollup is not sufficiently advanced to remove unused members from a class in this way. So, production apps are larger than they should be, due to decorator metadata (especially inline `template`s) being preserved in the JS.

We could remove these altogether, but then the resulting JS is no longer compatible with JIT mode, since the metadata is completely erased.
Also, it breaks Augury, which depends on runtime metadata reflection to understand the app structure.

cc @robwormald @chuckjaz @tbosch

**Comment by tbosch** [comment]
The conclusion is that we want to actually remove the decorators when ngc runs, assuming ngc will become the default way of developing (as JIT won't work then anymore).
