### ISSUE TITLE
Please create a simplified aot build

### ISSUE THREAD

**Issue by drager** [angular/angular#12891]
The AOT have lots of missing features, but as the run-time compiler runs fine we thought that it would be nice if the AOT compiler could be run in a mode that is more similar to the run-time version. We understand that it will not run the same amount of optimizations but as our current app takes over 30 seconds to start we want at least those optimizations we can get until all features are complete.

**Comment by DzmitryShylovich** [comment]
https://docs.google.com/document/d/1rC5dz7AkCZP813daT_bccbS-20OLmXgBVi50CSKx148/pub#h.r7mzd6yjkt2m as u can see its already on the roadmap

**Comment by chuckjaz** [comment]
@DzmitryShylovich This is different than what we are referencing in the meeting notes.

**Comment by tbosch** [comment]
We will focus on this as one of our next bigger changes.

Closing as not actionable...
