### ISSUE TITLE
How to remove/replace the angular2 component's selector tag from HTML

### ISSUE THREAD

**Issue by mlyknown** [angular/angular#12909]
That makes some of my CSS are not working as expected!

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by vicb** [comment]
maybe `cmp-selector {display: block}` ?

**Comment by mlyknown** [comment]
@vicb @ericcarraway  As well as this [problem ](http://stackoverflow.com/questions/34588933/how-to-remove-replace-the-angular2-components-selector-tag-from-html) ,but I want to remove tag...
