### ISSUE TITLE
Doesn't navigate to child route with empty path if defined after another route with common ancestor path

### ISSUE THREAD

**Issue by aeternusrahl** [angular/angular#12904]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After upgrading from router version 3.0.0 -> 3.2.0 the router does not appear to find or activate the correct route in the case where there are two top-level routes defined with the same path but whose child routes define unique paths if:
- one of the child routes has an empty path
- the route with the empty path is defined _after_ the other(s).

For example, if I define routes as follows I will not be able to navigate to `/some/common`, but I can still navigate to `/some/common/b`. When this issue does occur, there is no log output from the router to indicate a problem with navigation.
```
const routes: Route[] = [
  {
    path: 'some/common',
    children: [
      {
        path: 'b',
        component: ThingBComponent
      }
    ]
  },
  {
    path: 'some/common',
    children: [
      {
        path: '', // Cannot navigate to this route
        component: ThingAComponent
      }
    ]
  }
];
```

However, if I flip the order of the definitions, then navigation to both routes works as expected.
```
const routes: Route[] = [
 {
    path: 'some/common',
    children: [
      {
        path: '', // Can navigate to this route
        component: ThingAComponent
      }
    ]
  },
  {
    path: 'some/common',
    children: [
      {
        path: 'b',
        component: ThingBComponent
      }
    ]
  }
];
```

**Expected behavior**
In this case I would expect both routes to function properly regardless of the order in which they are loaded.

**Minimal reproduction of the problem with instructions**
This behavior can be observed in this [plunkr](https://plnkr.co/edit/uEuiHSDvjdaG3QIMcIvG). The default route here attempts to redirect to `/some/common` which never completes. But if you flip the order in which the routes are defined, you will see it load as expected.

**What is the motivation / use case for changing the behavior?**
In my app I have several feature modules which I want to keep separate but which rely on similar route parameters and guards. To keep them separate, each module defines a route with the same path (`/some/common` in this example) and then adds feature-specific children. 

**Please tell us about your environment:**

Problem observed with following versions:
```
"@angular/core": "2.2.0",
"@angular/router": "3.2.0",
```

and not observed in:
```
"@angular/core": "2.1.2",
"@angular/router": "3.1.0",
``` 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 2.0.2

* **Node (for AoT issues):** `node --version` =   
v6.9.1

**Comment by DzmitryShylovich** [comment]
I guess it was introduced here https://github.com/angular/angular/issues/12133

**Comment by ipassynk** [comment]
i have a similar issue with empty path and '**' redirect:

Basically this redirect works and display component2 and component1:

```
const fallbackRoute: Route = {
  path: '**',
  redirectTo: 'feature'
};

const worksRouter: Route = {
  path: 'feature',
  component: Component2Component,
  children: [
    {
      path: "",
      component: Component1Component
    }
  ]
};
```

and this one does not. It displays only component2 (with empty path)

```
const fallbackRoute: Route = {
  path: '**',
  redirectTo: 'feature'
};
const brokenRouter: Route = {
  path: '',
  component: Component2Component,
  children: [
    {
      path: "feature",
      component: Component1Component
    }
  ]
};
````

**Comment by DzmitryShylovich** [comment]
@aeternusrahl what's the use case for such config? We don't merge routes with the same path and I'm not sure we should...

Just change it to:
```
{
    path: 'some/common',
    children: [
      {
        path: 'b',
        component: ThingBComponent
      },
      {
        path: '',
        component: ThingAComponent
      }
    ],
  }
```
and it will work as expected: https://plnkr.co/edit/aHprV5JqDFUL7R8VgoRs?p=preview

**Comment by atscott** [comment]
Confirmed, still an issue in v9: https://stackblitz.com/edit/angular-ivy-opx9fe?file=src%2Fapp%2Fapp.module.ts

**Comment by tonysamperi** [comment]
Any workarounds? I've tried every possible combination of 
`{path: "", redirectTo: "myNestedRoute", pathMatch: "full"}` and `{path: "**", redirectTo: "myNestedRoute"}`
Both in the children and in the outer config. Always blank component 🤔

**Comment by atscott** [comment]
Closing as working as expected. The first route matches all segments in the URL. The Router only matches configs until all segments are consumed. Config matching is order dependent so it is expected that changing the order may affect the application behavior: https://angular.io/guide/router#route-order
