### ISSUE TITLE
No AOT-compatible way to reuse animation definitions 

### ISSUE THREAD

**Issue by benelliott** [angular/angular#12917]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As far as I can tell there is currently no way to reuse Angular animations in a way that is compatible with the AOT compiler. When using JIT, I could export some static `AnimationEntryMetadata` objects and then reference these in my component decorators, e.g. `animations: [Animations.EXPAND_WIDTH]`.

This doesn't work in AOT - animations' state metadata will not be generated correctly. I don't want to redeclare the animation in full in every component decorator as they can be 5-15 lines each and are all the same across my app.

**Expected behavior**
AOT compiler should allow for the reuse of animation metadata.

**Minimal reproduction of the problem with instructions**
Create an AOT project, create some static animation definitions and export them from one file. Import them into a component definition and reference one of the animations in the compiler's metadata. AOT compilation will fail.

**What is the motivation / use case for changing the behavior?**
DRY principles, maintainability, desire to make reusable animation libraries
 
**Please tell us about your environment:**
Windows 7, WebStorm

* **Angular version:** 2.2.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  5.8.0

**Comment by matsko** [comment]
@tbosch @mhevery @chuckjaz is there anything we can do here? Maybe we should expedite the reusable animation plugins feature.

**Comment by mhevery** [comment]
Could you provide an example of what does not work?

We think this works today:

`utils.ts`:
```
import {animate, keyframes, state, style, transition, trigger} from '@angular/core';

export  const backgroundAnimation = 
    trigger('backgroundAnimation', [
      state('focus', style({ 'background-color':'white' })),
      state('blur', style({ 'background-color':'grey' })),
      transition('* => *', [
        animate(500)
      ])
    ]);

export function hoverAnimation(delay) {
  return trigger('backgroundAnimation', [
      state('focus', style({ 'background-color':'white' })),
      state('blur', style({ 'background-color':'grey' })),
      transition('* => *', [
        animate(delay)
      ])
    ]);
}
```


`app.ts`:
```
import {Component} from '@angular/core';
import {backgroundAnimation, hoverAnimation} from './utils';

@Component({
  ...
  animations: [
    backgroundAnimation,
    hoverAnimation(1000)
  ]
})
class MyComponent {}
```

**Comment by benelliott** [comment]
I am writing a reusable library that exposes these animation definitions as well as some components that use them. I just tried refactoring my code to look like your suggestion (it was previously exporting an `Animations` class with static functions) but when I run `ngc` to build my library it fails with the error
```
Error encountered resolving symbol values statically. Calling function 'ANIM_EXPAND_WIDTH', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function.
```

This is my animation:

```
export function ANIM_EXPAND_WIDTH(transitionMs: number = 200): AnimationEntryMetadata {
    return trigger('expandWidth', [
        state('void', style({
            width: 0
        })),
        state('*', style({
            width: '*'
        })),
        transition('void <=> *', animate(`${transitionMs}ms ease`))
    ]);
}
```

and it is used in my component metadata like this:

```
...
import { ANIM_EXPAND_WIDTH } from '../../constants/animations';

@Component({
    ...,
    animations: [ANIM_EXPAND_WIDTH()]
})
```

**Comment by chuckjaz** [comment]
I will work on improving the error here but the reason this is not supported is because of the template substitution in call to `transition` on line 9. Consider changing this to,

```ts
export function ANIM_EXPAND_WIDTH(transitionMs: number = 200): AnimationEntryMetadata {
    return trigger('expandWidth', [
        state('void', style({
            width: 0
        })),
        state('*', style({
            width: '*'
        })),
        transition('void <=> *', animate(transitionMs + 'ms ease'))
    ]);
}
```

**Comment by benelliott** [comment]
Oh, thank you! I had no idea this could be a cause, especially since TypeScript seems to compile to that anyway. Will confirm that it fixes my use case tomorrow.

**Comment by benelliott** [comment]
This does seem to have fixed it for me. The compiler also dislikes `'use strict';` statements inside these function blocks.

I'll leave the issue open in case the error message is to be clarified.

**Comment by chuckjaz** [comment]
The function must be a single `return` statement. Do you need `use strict`?

**Comment by benelliott** [comment]
Nope I don't, it was my linter trying to put it in there. Just pointing it out in case it helps clarify things for anyone else.

**Comment by chuckjaz** [comment]
I created a more straight forward issue for the error message, #13132, and am closing this issue in favor of that one.

**Comment by AliAdravi** [comment]
Look this article, might be it can help anyone
http://www.advancesharp.com/blog/1228/angular-5-reusable-animation-with-a-single-file
