### ISSUE TITLE
platform-browser: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#12915]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`disableDebugTools` from `@angular/platform-browser` throws `Cannot convert undefined or null to object` error

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/fNA0htW5nau6L45mrMvb?p=preview

**Comment by vicb** [comment]
seems like the root cause is

```
    /**
     * Disables Angular 2 tools.
     *
     * @experimental All debugging apis are currently experimental.
     */
    function disableDebugTools() {
        delete context.ng.profiler;
    }
```

where ng is `undefined`. 

Could you please send a quick fix PR adding a check before the delete ?

Thanks
