### ISSUE TITLE
Feature request: use of es6 template literals in html templates if possible

### ISSUE THREAD

**Issue by sfabriece** [angular/angular#12914]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently we get template parse errors when we try to use template literals in html templates

**Expected behavior**

I would expect to use an es6 template literals in html templates
```js
`${variable}`
```

**What is the motivation / use case for changing the behavior?**

With this feature, we get rid of string concatenation in template

```js
/ + variable+ / + variable
```

**Please tell us about your environment:**

Windows 10, Vscode, Npm 

* **Angular version:** 2.2.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by vicb** [comment]
This has been rejected because it would not work with inline templates
