### ISSUE TITLE
Add animation query() functionality

### ISSUE THREAD

**Issue by matsko** [angular/angular#12924]
```ts
@Component({
    selector: 'app',
    styleUrls: ['app.css'],
    template: `
<button (click)="exp=!exp">Go</button>
<div class="trigger" [@container]="exp" *ngIf="exp">
  <header #header [@header]="exp ? 'true' : 'false'">header</header>

  <div #body>body</div>

  <footer #footer>footer</footer>
</div>
    `,
    styles: [`
      .trigger {
        display:block;
        padding:1em;
        border:10px solid #888;
      }
      .item {
        width:100px;
        line-height:100px;
        font-size:60px;
        border:10px solid black;
        display:inline-block;
        margin:10px;
        text-align:center;
      }
    `],
    animations: [
        trigger('header', [
          state('true', style({ backgroundColor: 'red' })),
          state('false', style({ backgroundColor: 'blue' })),
          transition('* => *', animate(2000))
        ]),
        trigger('container', [
          state('*', style({ opacity: 1 })),
          state('void', style({ opacity: 0 })),
          transition(':enter', group([
            query('footer', [
              style({ opacity: 0 })
              animate(2000, style({ opacity: 1 }))
            ]),
            query('header', animateChild()),
            query('body', [
              style({ opacity: 0 })
              animate(2000, style({ opacity: 1 }))
            ])
          ])),
          transition(':leave', [
            animate(500)
          ])
        ])
    ]
})
export class App {
  public exp = false;
}
```

**Comment by jordic** [comment]
Nice feature!
Could it be possible also to have a delay property on the query function? The delay property could be added incremental as staggering func. For example: 

```
<li *ngFor="let item of items">{{ item }}</li>

query('li', [
  style({ opacity: 0 }),
  animate(600, style({opacity: 1}))
], 200)
```
This will add a 200ms delay on each matching element.

PD: Perhaps I'm asking this, and with your current implementation there is a way of doing the same without touching the func signature. Anyway when using current implementation of animations I found the most missing part is something like this, when you are working on lists (of things), that is a common case.

Acutally I have a more or less workaround with something like this:
https://plnkr.co/edit/BRInrqnNJjNe4aZEKtfb
but it feels like is not the proper way of doing it. Also thank on implementing this as a async pipe extension... but this also doesn't fit (As my understanding animations had to life on another domain).

**Comment by matsko** [comment]
This will be a new method call to `stagger(delay, animation)`. This way it's easier to handle preparation styles (which site outside of where stagger() is used).

```
query('li', [
  style({ opacity: 0 }),
  stagger(200, [ // or -200
    animate(600, style({opacity: 1}))
  ])
])
```

**Comment by jtushar53** [comment]
eagerly waiting for stagger method, any workaround as of now.

Currently using 
http://stackoverflow.com/questions/39702396/staggering-angular2-animations-within-ngfor
https://plnkr.co/edit/NgwMMSILAxRuxkOBGyzi?p=preview

**Comment by laco0416** [comment]
@matsko I cannot wait for the new feature!

BTW, I have a question. Currently, all functions for Angular Animation are exported from `@angular/core`. I think possibly it will make core package so fat. Do you have any plans to make new `@angular/animate` package?

**Comment by shlomiassaf** [comment]
@laco0416 I think most of the animation code is compiler instructions.

How to take metadata instruction and convert them to compiled code...

**Comment by klaascuvelier** [comment]
Is there any word on the `query` implementation @matsko?
Has work been started on this and is there any way people can contribute?

**Comment by matsko** [comment]
It's getting close: https://github.com/angular/angular/pull/15574

**Comment by cexbrayat** [comment]
@matsko @jasonaden shouldn't that issue be closed now that #15574 landed?

**Comment by matsko** [comment]
This this is now possible with https://github.com/angular/angular/commit/16c8167886d63f5b4cf03d420478b64640e45654.

Please do test this out and provide feedback. I'm sorry it took so long to have it land.

**Comment by toniopelo** [comment]
Hi @matsko !
I copied pasted the code you published on the top of this issue. I'm with angular 4.2.0-rc.0 but it doesn't work as expected.
After few tests, I realized that the query firts parameter needed to be a html tag name or id if preceeded by a #.

For exemple, in your code, this doesn't work:
```
query('body', [
     style({ opacity: 0 })
     animate(2000, style({ opacity: 1 }))
])
```
because it cannot find any `<body></body>` tag whereas `<div #body>body</div>` is in your template.

I'm posting this as a comment because I don't know if this is a bug and it doesn't work as intended or if you changed your mind about how it's supposed to work.
Can we query something based on template variables ?

There is the error:
```
ERROR Error: animation building failed:
`query("body")` returned zero elements. (Use `query("body", { optional: true })` if you wish to allow this.)
```

Thank you for your work :)

**Comment by matsko** [comment]
hey @toniopelo.

Ah I see yes we do query off of the `body` tag. I didn't think of this when implementing it, but it is indeed needed.

I've created an issue for this and it will be apart of next week's release:
https://github.com/angular/angular/issues/17059

**Comment by JohnnyQQQQ** [comment]
@matsko 
I tried the code from the `stagger` function docblock. It works for me but I can't wrap my head around how I can i.e. give the queried children an initial state of `opacity:0` as any state style of a trigger won't get propagate to any queried children.

The `style` from the query seems to be passed much later to the queried dom element. As a result when I transition from `void` to `*` the elemets will do a blinking effect instead of a fadein.

http://plnkr.co/edit/FEyFp33nmBNyEwZSys17?p=preview

Is there a concept I am missing on how to animate such lists without first showing each item?

**Comment by matsko** [comment]
@JohnnyQQQQ you just need to issue a query before any actual animation takes place.
http://plnkr.co/edit/qM6esY9fH5Ag72TiNQ1D?p=preview

**Comment by JohnnyQQQQ** [comment]
@matsko 
works 👍
