### ISSUE TITLE
Router throws Illegal Invocation error when enableTracing is true

### ISSUE THREAD

**Issue by buddyackerman** [angular/angular#12923]
**I'm submitting a ...
[X] bug report => search github for a similar issue or PR before submitting

**Current behavior**

Set the router enableTracing option to true.  As soon as hte app loads and begins to route and Illegal Invocation error is thrown.

It did this with a brand new app created with angular-cli.  I added one test component and create a default route for it and it loaded fine.  Then I set enableTracing to true and it started throwing the error.

**Expected behavior**
No error thrown, just shows the router trace

This is occurring in a NG 2.1.0 (router 3.1.0) and above.  I found it while upgrading an app from 2.0.2 (where it worked fine) to 2.2.0.  

Here's a link to the error that's thrown: [error.png](https://postimg.org/image/dh20gkwct/)

**Comment by DzmitryShylovich** [comment]
Can u pls add a repro in plunkr?

**Comment by buddyackerman** [comment]
Just create a new project with ng-cli then add the following app.routing along with creating a dummy test component to replace the one I created and modify the app.module to import this routing module.


`

    import { TestComponentComponent } from './testcomponent/test-component/test-component.component';

    import { NgModule }     from '@angular/core';
    import { RouterModule } from '@angular/router';



    @NgModule({
      imports: [
        RouterModule.forRoot([
          { path: '**', component: TestComponentComponent }
        ],{enableTracing: true})
      ],
      exports: [
        RouterModule
      ]
    })
    export class AppRoutingModule {}

`
