### ISSUE TITLE
Subscribe to change detection

### ISSUE THREAD

**Issue by AmitMY** [angular/angular#12929]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Description**
Add an ability to subscribe to the change detector. when it is dirty, it changes the view, then it will emit finishing the render, with the amount of time in milliseconds it took

**Current behavior**
Currently, when I want to check my performance, I don't really have the idea what is going wrong.

**Expected behavior**
Me to have the possibility to know my performance

**What is the motivation / use case for changing the behavior?**
Better performance

**Please tell us about your environment:**
Angular-CLI

* **Angular version:** 2.2.0

* **Browser:** [all]
 
* **Language:** [all]

**Comment by vicb** [comment]
Your use case is covered by the `AngularProfiler`

Not sure about the docs, please check angular.io and if this is not well covered please open an issue on their repo angular/angular.io

Thanks
