### ISSUE TITLE
Cache ngFactory files to Disk in case of JIT compilation

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#12935]
Hi,

As per my understanding, in case of JIT compilation, ngc generates the ngFactory files at run time and store them in memory. If we have to make some minor change to a file of a large project and then to test that change when we refresh the browser ngc performs compilation for the complete application even the change only affected 1 file.

Is it possible, that for the first time when the user runs the application in browser ngc generate ngFactory files and store them in cache (disk cache). When the user refreshed the page, ngc check if the files has been modified (may be through hash) then remove the ngFactory file of that files from cache and recompile it, otherwise use the copy of the ngFactory file from cache. If possible, this would improve the load time of the subsequent refreshes.

**Comment by robwormald** [comment]
ngc is the offline compiler, and doesn't actually run in the browser. I'm not sure there's anything actionable in this issue, and I'm not sure what the practical benefit is - any change you make to code is likely to invalidate the cached ngfactory files.

**Comment by naveedahmed1** [comment]
@robwormald  sorry my mistake I was referring to Angular JIT Compiler.
