### ISSUE TITLE
Router Issues: Relative navigation not working when called via Service, ActivatedRoute provided incorrectly?

### ISSUE THREAD

**Issue by jeanpaulattard** [angular/angular#12938]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```
** Problem **

I recently ran in the following scenario, where I have a service A which after executing some logic , the service would navigate the user to a page relative to the current one, for example "/app/heroes" to "/app/heroes/edit". That said, attempting to perform relative navigation using 

router.navigate(['./edit'], {relativeTo: this.activatedRoute})   <--- Notice the . before the /

does not route to "/app/heroes/edit" but rather to "/edit"

I noticed that there already was an issue recently regarding this (see https://github.com/angular/angular/issues/12884) but was closed due to insufficient replication steps. (see plunkr below for this issue)

**Current behavior**
Relative navigation from a service does not navigate relative to current path as defined in url but relative to app component.

**Expected behavior**
Navigation would occur to a path relative to the current active path (as defined in browser url)

**Minimal reproduction of the problem with instructions**
Here is a plunkr to the issue. https://plnkr.co/edit/nrxx2m?p=preview

Clicking on "Relative Navigation via Component" would perform a relative navigation using the ActivatedRoute provided within the component. - Here the URL changes from /component1 to /component1/404

Clicking on "Relative Navigation via Service" would perform the same relative navigation using the ActivatedRoute provided within the service. - Here the URL changes from /component1 to /404

**Please tell us about your environment:**
Windows 10, WebPack

* **Angular version:** 2.1.2

**Comment by DzmitryShylovich** [comment]
> ActivatedRoute provided incorrectly?

yeap. See https://github.com/angular/angular/issues/11023

**Comment by baio** [comment]
exact problem which is I have right now +1

**Comment by vicb** [comment]
The issue here is that `this.activatedRoute` is injected at the root level so it will be the root route.

You can traverse the routes to find the one you are intersted in.

Not a bug.

**Comment by pscanlon1** [comment]
Is there any feature request for this? Might not be a bug but its extremely frustrating compared to UI router..
