### ISSUE TITLE
Listing directives in @View is verbose (especially for common / easy cases)

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#1293]
As of today one needs to enumerate all the directives used by a given `@View`. This is very verbose and repetitive process, especially for simpler cases / components where one uses only standard / built-in directives.

Assuming that I'm building a simple components that only consumes built-in directives I need to write:

```javascript
import {Component, Template, bootstrap} from 'angular2/angular2';
import {If} from 'angular2/angular2';

@Component({
....
})
@View({
  inline: '...',
  directives: [If]
})
class Simple {
...
}
``` 

In a nutshell it means that for every directive I need to:
* import it
* reference in `directives`

While I understand the benefits of this approach as well as technical limitations here, it is still very repetitive in practice, especially for very often (application-wide) directives (built-ins, directives used in most of the pages, etc.).

Here are few ideas of how to make it easier on people:
* allow omit `directives` and assume that all built-in directives are available
* allow omit `directives` and assume that all directives specified by an app developer are available

This is not urgent / critical piece but would make things significantly easier on people.

**Comment by tbosch** [comment]
As the directives list can contain nested lists, Angular could provide a
default list of directives that can be referenced, and we still get all the
benefits.
For a concrete project, the project can export its own list of directives
and reference this list everywhere.

With this, the overhead would be one module import + one line in the
Annotation.

**Comment by pkozlowski-opensource** [comment]
@tbosch yes, this is definitively something we could and should do - that is - provide a file with a list of all directives. Still, it doesn't change the fact that ones needs to import + reference this list.

I know that there are different forces here but this is boilerplate and IMO we need to find a way of removing it for simpler cases.

**Comment by jkurz** [comment]
I like the idea of exporting a list from a project, but maybe it would need to allow for multiple exports. Groups of directives that could be included not all. All too if you wanted.

Also could we make it optional for directives to be inherited from the parent? So we could just put a Custom List at the Root of the app and they could be available anywhere in the tree. Maybe a special directives attr on the Template, which is read from all children.

**Comment by jkurz** [comment]
On another thought, maybe we could change how we export classes, killing two birds with one stone. 

so you could do something like import {directives.view.If} from 'angular2/angular2/export'; 

then Angular would not have to have an extra list just for groups of exports and anyone could reference all directives, or all services, or just a subset of whatever they wanted, or just individual classes.

**Comment by timjacobi** [comment]
What is the performance impact of referencing a directive? If it's negligible I vote for having built-in directives available everywhere.

**Comment by yjbanov** [comment]
NOTE: `@Template` has been renamed to `@View`

One way to get rid of boilerplate is to extend the `View` annotation that preloads all standard directives. E.g.:

```typescript
class CommonView extends View {
  constructor({templateUrl, template, directives}) {
    super({
      templateUrl: templateUrl,
      template: template,
      directives: [If, For, Switch, directives]
    });
  }
}
```

Then you use it _instead_ of `View` in your components:

```typescript
@Component(...)
@CommonView({
  template: '<div *if="isVisible">...</div>'
})
```

That said, _to not want standard directives_ is an exception. Most ng2 apps will need the standard directives. Perhaps we could have a `RawView` that does not preload anything and `View` would bring in standard directives automatically.

**Comment by pkozlowski-opensource** [comment]
Thnx @yjbanov - updated `@Template` -> `@View`

> That said, to not want standard directives is an exception. Most ng2 apps will need the standard directives.

I like the sound of it :-)

>  Perhaps we could have a RawView that does not preload anything and View would bring in standard directives automatically.

This is definitively a possibility!

**Comment by un33k** [comment]
I believe having the ability to pre load commonly used directive might be preferred over just the core directives. Imagine if a project introduces a "Foo" directive that is heavily used, then it would be nice to load it up once and use it many times. (#1586)

**Comment by pkozlowski-opensource** [comment]
@un33k totally agree. What I'm trying to do as the very first step is to deal with built-in directives. But the very next step should be some kind of "registry" where users could register commonly used directives. There are few items to sort out to make it possible (how to deal with duplicates / collisions, tooling support etc.) but yeh, this is the plan!

**Comment by nicoabie** [comment]
What if the user just lists all the directives (built-in and custom) he is going to use in the @View for the performance benefits and there is a Grunt/Gulp/Broccoli task that adds the imports?

**Comment by timjacobi** [comment]
I don't think a framework should rely on a 3rd party tool to work.

**Comment by jbdeboer** [comment]
@mhevery @tbosch @naomiblack 

At the moment, this issue does not have a good resolution -- and we need one in the next couple weeks as we are migrating a large number of components.

At very least, could you document the proposed solution?

**Comment by ewinslow** [comment]
Personally I find the explicitness of api to be refreshing because it means compilers/tools can do tree-shaking and drop unused directives automatically, or lazy-load them in the correct order or whatever.

The `@View` and `@RawView` distinction seems like a good compromise. Gets people up and running quickly without boilerplate but then also offers the control you need when you want to optimize your app for download size.

**Comment by mhevery** [comment]
The current thinking is to have `View` and `BaseView` annotations where `View extends BaseView` and automatically adds angular core directives. In this way most of the time we don't have to specify core directives, but if a user does not want the core directives there is a way out.

**Comment by jbdeboer** [comment]
Could apps add to the list of "core directives"?

Or will app developers be encouraged to extend View?  In that case, how
will you ensure that tools work correctly?

**Comment by pkozlowski-opensource** [comment]
Yeh, my initial thinking was also to have some kind of "registry" where people could list they "default" directives (ones that are used most of the time and should be available in more or less all of the templates). Core directives would be in this registry by default but people could add more of their custom directives in there.

**Comment by gdi2290** [comment]
It would be nice to inject directives similar to bindings. For example if you look at [bootstrap.ts#L17](https://github.com/angular-class/angular2-webpack-starter/blob/5547869d0957f5ab95093637558ef170b57a2144/src/app/bootstrap.ts#L17) I'm including injectables from a services folder [services.ts#L4](https://github.com/angular-class/angular2-webpack-starter/blob/5547869d0957f5ab95093637558ef170b57a2144/src/app/services/services.ts#L4) and also creating injectables for each service [TodoService.ts#L45](https://github.com/angular-class/angular2-webpack-starter/blob/5547869d0957f5ab95093637558ef170b57a2144/src/app/services/TodoService.ts#L45). I don't have the same story when it comes to directives

Services:
`export todoInjectables`[TodoService.ts#L45](https://github.com/angular-class/angular2-webpack-starter/blob/5547869d0957f5ab95093637558ef170b57a2144/src/app/services/TodoService.ts#L45)
`export appServicesInjectables`[services.ts#L4](https://github.com/angular-class/angular2-webpack-starter/blob/5547869d0957f5ab95093637558ef170b57a2144/src/app/services/services.ts#L4)
`bootstrap(App, [appServicesInjectables])`[bootstrap.ts#L17](https://github.com/angular-class/angular2-webpack-starter/blob/5547869d0957f5ab95093637558ef170b57a2144/src/app/bootstrap.ts#L17)

Directive:
`export appDirectives`[directives.ts#L4](https://github.com/angular-class/angular2-webpack-starter/blob/5547869d0957f5ab95093637558ef170b57a2144/src/app/directives/directives.ts#L4)
`import appDirectives`[app.ts#L16](https://github.com/angular-class/angular2-webpack-starter/blob/5547869d0957f5ab95093637558ef170b57a2144/src/app/components/app.ts#L16)
`directives: [appDirectives]`[app.ts#L24](https://github.com/angular-class/angular2-webpack-starter/blob/5547869d0957f5ab95093637558ef170b57a2144/src/app/components/app.ts#L24)

this is the same pattern people use in angular1 with `angular.module`

**Comment by TedSander** [comment]
Angular.dart had some problems with deferred code loading, and code size. Which was one of the motivations of moving the bindings out of the bootstrap. The current solution of requiring the component to specify what it will be using largely solves these as @ewinslow said. I'm for making it easier on the developer, but the solution should take into account performance.

**Comment by johnpapa** [comment]
> The current thinking is to have View and BaseView annotations where View extends BaseView and automatically adds angular core directives. In this way most of the time we don't have to specify core directives, but if a user does not want the core directives there is a way out.


I like this idea. I have many apps where I can see several directives being needed. Having to list 20 directives would suck, so this would help with the baked in NG ones

**Comment by naomiblack** [comment]
@mhevery we need some input on the best way forward on implementation. Please weigh in?

**Comment by un33k** [comment]
https://github.com/angular/angular/issues/1293#issuecomment-105691051

**Comment by un33k** [comment]
@naomiblack I guess you missed it here: https://github.com/angular/angular/issues/1293#issuecomment-105691051

**Comment by naomiblack** [comment]
@un33k nope -- wanted more current than 20 days ago as we have been discussing further in person.

**Comment by mhevery** [comment]
We have decided to do the approach of `BaseView` which is then subclassed with  `View`. This allows the View to add the `ngCoreDirectives`. The app developer can further subclass with `MyView`.

We have decided against the global state since it would make component reuse problematic.

**Comment by timkindberg** [comment]
I would hope that tooling in my IDE would get good enough to auto import and add directives for me as I'm typing my template.

So if I type:
```js
import {Component, Template} from 'angular2/angular2';

@Component({ })
@View({
  inline: '<div *ng-if=""></div>'
})
class Simple { }
```

Then it will suggest to import ng-if for me (in Intellij it does this in Java when you type a class that isn't imported yet). So I'd say "Yes please import that for me", it would import it at the top and also add it to the directive array (creating the array if its not there) and end up with:

```js
import {Component, Template, If} from 'angular2/angular2';

@Component({ })
@View({
  inline: '<div *ng-if=""></div>',
  directives: [If]
})
class Simple { }
```

Yay tooling!

**Comment by pkozlowski-opensource** [comment]
@timkindberg the proposal discussed here doesn't prevents tools from doing what you are describing here. But tools can't be the only answer as:
* there are plenty of tools out there and getting good support for ng2 in all of them will take time
* even if a tool can generate code for us it is still more code to read / download into a browser

**Comment by naomiblack** [comment]
extending the deadline on this one to give @pkozlowski-opensource more time to dig into the details.

**Comment by IgorMinar** [comment]
Taking into account experience we have from Java and other languages that support wildcard imports (`import java.util.collection.*`) which are similar to the proposed View/BaseView approach, I think that we will quickly run into the same issues as experienced in this systems (see: http://stackoverflow.com/a/147461).

Especially the future expansion of the core directives will become problematic because parts of the template that previously were inert will not trigger directives. That means that just by upgrading to a new framework version that contains more directives you will suddenly break existing templates. This could be worked around by creating more view annotations e.g. `@View2` but that's really ugly and unmaintainable about.

In Java and other languages the execution flow constructs are keywords in the language and don't require imports. This is not the case in Angular 2 and that causes issues for ease of use. One option is  to create a very small set of directives (maybe just: NgIf, NgSwitch, NgSwitchWhen, NgFor) and auto import those. The rest of Angular directives would still require imports. This would be a compromise that would allow us to evolve the framework.

I personally prefer to use explicit imports for everything, but what makes that difficult is that the import needs to be specified twice (once via es `import` and the second time via the `directives` array) and I don't see that being discussed. Ideally I'd like the import to be in the template (where it belongs). We don't do this right now because of module loader issues that this would create.

One solution could be to generate code from the template. For example:

```
<!-- the actual syntax is up for debate -->
<link rel="ng/directive" href="angular2/forms#Form"></link>
<link rel="ng/directive" href="angular2/forms#NgModel"></link>
<form>
<input [(ng-model)]="foo">
</form>
```

would get compiled into:

```
import {Form, NgModel} from 'angular2/forms';

...
@View({
  directives: [Form, NgModel]
})
...
```

Doing this kind of transformation is not difficult but requires tooling (which Angular 2 relies on anyway). If you don't want to use tooling then you can always stick to manual import and `directives` definition. That will keep on working.

**Comment by ewinslow** [comment]
+1 putting the imports in the template itself would be ideal.

**Comment by ewinslow** [comment]
Didn't realize that was still on the table

**Comment by pkozlowski-opensource** [comment]
@IgorMinar thnx for your write-up - you are raising number of important points - in fact so many of them that I don't know where to start :-) So, few thoughts in the assorted order:

* I still believe that semantically it makes more sense to list directives in templates themselves, rather than in the `@View` annotation. But as @ewinslow I was under the impression that we've ruled out this option (not sure about the exact reasons - I guess the main one being difficulty of coming up with a syntax that would be easy to write / parse and load)
* Breaking things by adding more directives to the base `@View` is a very real concern, but I was under the impression that we want to list only very core things (if, for, class etc.) that are used in most (all?) templates. So it somehow would correspond to a set of "keywords". Still, there is potential for accidental breakage here...
* Tooling: my take on this is that ng2 syntax should be easy / pleasant to use "out of the box" and tools should be there to make the whole experience awesome. In my view tools can't be prerequisite / mandatory for frameworks.

Now, to be clear - I'm coming from ng1 where the dev experience is awesome. No tools required, things easy to write in any editor - this is my baseline. Compared to this baseline ng2 seems very verbose / painful atm, especially for things I'm using in almost each and every template. Taken from this perspective it doesn't shock me that there is a place where we list all those commonly used "keywords". 

Now, I'm still pondering "global registry" a bit - I know that there are problems with it as well. But we need to balance system "correctness" with dev experience - perfect system has no use it is too painful to use in practice.... 

Happy to dig / discuss this in more details, as it is important for me....

**Comment by un33k** [comment]
Would something like this fly? Ensuring both maintainability and performance. (we'd just document the use-cases & the benefits)

   ```typescript
    // index.ts
    import {bootstrap, NgFor, Component, View} from 'angular2/angular2';
    import {reflector} from 'angular2/src/reflection/reflection';
    import {ReflectionCapabilities} from 'angular2/src/reflection/reflection_capabilities';
    import {ToDoCommonlyUsedDirectives, ToDoRarelyUsed} from './directives/TodoDirectives';
    import {Store, Todo, TodoFactory} from './services/TodoStore';

    @Component({
        selector: 'todo-app',
        appInjector: [Store, TodoFactory]
    })
    @View({
        templateUrl: 'todo.html',
        directives: ToDoCommonlyUsedDirectives.concat([NgFor, ToDoRarelyUsed])
    })
    class TodoApp { ... }
   ```

   ```typescript
    // ./directives/TodoDirectives.ts

    import {Directive} from 'angular2/annotations';
    import {NgFor, NgIf, NgSwitch} from 'angular2/angular2';

    @Directive(
        {selector: '[todo-rare]', properties: [ ... ]
    })
    export class ToDoRarelyUsed { ... }

    @Directive(
        {selector: '[todo-common]', properties: [ ... ]
    })
    export class ToDoCommonlyUsed { ... }

    export CommonlyUsedDirectives = [NgFor, NgIf, NgSwitch, ToDoCommonlyUsed];
   ```

Disclaimer: Syntax may not be exact.

**Comment by pkozlowski-opensource** [comment]
@un33k this already works, at least in JS.

**Comment by afirdousi** [comment]
Can we introduce a simple concept of "containers" here (needs a better name may be). As @mhevery said, we are settling down for "ngCoreDirectives" to go in the @baseView  . In my understanding, what we are doing here is, we are creating a injectables container. 

Suppose I have custom injectables (not core directives) named A1,A2,A3 and B1,B2. 

When I sub class my injectors up in my components, I would like to use any combination of injectables, may be I would like to bring in a combination of A1,A2 and B1. In a different component, I want to a combination of A3,B1 and B2. e.t.c.

If the developer can create custom injectable container, then he create any sets of containers with any combination. For instance in some app, I have a injectable container with combination A1,A2 and B2 and I call it "paymentDirectives",

where ever this combination is required, I would do something like:


@View({
    directiveContainer: paymentDirectives,
    /*directive:  I still want to keep this for single injection or if the dev do not like directiveContainer he can still pass in an array here */
})
class MyCrazyComponent {   ....  }

**Comment by timkindberg** [comment]
I'm not sure introducing yet another decorator property is a good idea. Why can't devs arbitrarily package up multiple directives into an array and then add that to the directives array like so:

```js
@View({
directive: [...paymentDirectives]
})
class MyCrazyComponent { .... }
```

**Comment by afirdousi** [comment]
What exactly  do you mean when you say " arbitrarily package up " ?  I think we are talking about the same thing except that I proposed a new property for this.

Why the new property ?

-You wont be using both properties at the same time. 
-If you wish to inject a single directive, you can always use 'directive' property.
-If you wish to inject any different combination of directives which actually make sense for a particular component, only then I will first create a injectable container and then use the other property i proposed.

Another way, if we want to use the same 'directive' property, Angular engine has to be smart enough to recognize whether the injected object is a container of several directives or its referring to 1 directive. In this case, you will not be able to keep same name for a particular directive and a particular injectable container - which makes sense.

**Comment by naomiblack** [comment]
@mhevery community consensus is not in favor of the current proposal. We need a new one. Can you think about this in alpha-31?

**Comment by timkindberg** [comment]
@afirdousi I guess I figured the 'container' was really just an array of directives. So directive should easily be able to `.flatten` the directives. I think a new property should be avoided, if possible.

```js
let paymentDirectives = [directiveA, directiveB];
let directiveC = ...;

@View({
directive: [paymentDirectives, directiveC]
})
class MyCrazyComponent { .... }
```

**Comment by mhevery** [comment]
@pkozlowski-opensource what happened to: https://github.com/angular/angular/pull/2508? It was supposed to resolve this issue.

**Comment by mhevery** [comment]
Closing in favor of: https://github.com/angular/angular/issues/2844

**Comment by pkozlowski-opensource** [comment]
@mhevery I had pbs making #2508 to work so it kept moving from release to release :-/ But this PR was WIP, I never really managed to get things working correctly in both JS and Dart :-(

I will look / start working on #2844 instead.

**Comment by afirdousi** [comment]
Would love to help on this and other similar issues @mhevery @pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
@afirdousi rest assured that this is an important topic for us and we are trying to find the best possible solution here.

**Comment by johnpapa** [comment]
The subclassing of Views is a nice option. I like the idea of allowing devs to do this on their own. I am not sure I thin kits a good idea for Angular to do this in the box, but perhaps just show how to do it in the docs and guide folks there if they want to do that.

Is there a performance impact to listing more directives that is used? 

I can also see that it would be common to use a directive in an html template and then remove it, but forget to do so from the Component
