### ISSUE TITLE
<router-outlet> with the custom selector: <router-outlet mySelector></router-outlet>

### ISSUE THREAD

**Issue by AilisObrian** [angular/angular#12937]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If we want to add the custom selector (mySelector) to routed component (myComponent), need to wrap it one more depth like this:
```html
<div mySelector>
   <router-outlet></router-outlet>
   <myComponent></myComponent>
</div>
```

**Expected behavior**

1. Inject the selector into a routed component.
```html
<router-outlet mySelector></router-outlet>
<myComponent mySelector></myComponent>
```
2. Inject the component as a router-outlet's contents.
```html
<router-outlet mySelector><myComponent></myComponent></router-outlet>
```

**What is the motivation / use case for changing the behavior?**

It will increase the readability and productivity.

**Comment by zoechi** [comment]
Why would you want to add a selector to a routed component?
I don't get what problem you are trying to solve.

**Comment by vicb** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
