### ISSUE TITLE
Selective content projection not working when a component is used inside another component

### ISSUE THREAD

**Issue by ospatil** [angular/angular#12930]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Selective content projection (using `<ng-content select="someref"></ng-content>`) works fine when a component is used own its own but doesn't work as expected when such component is enclosed in another component.

**Expected behavior**

The selective content projection should work in the same manner irrespective of whether a component is used on its own or included in another component.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/iZ0cJciWf35F7SgHiPJX?p=preview

**Explanation**
**1. Direct content projection for a component**

I have a component `toolbar` with template as follows (_app/toolbar.component.ts_ in the plunker): 
```html
<div>
    <toolbar-row class="toolbar-first">
      <ng-content></ng-content>
    </toolbar-row>
    <ng-content select="toolbar-row"></ng-content>
</div>
```

It can be used as follows (_app/app.component.ts_ template in the plunker):
```html
<toolbar>
  <div>Banner content</div>
  <div controls>menu1</div>
  <div controls>menu2</div>
  <toolbar-row>
     <div style="background-color: white; color: #464646; line-height: 45px; height: 45px;">nav-bar</div>
  </toolbar-row>
</toolbar>
```

Basically, it uses `<ng-content select="toolbar-row"></ng-content>` to pick and render the the last `toolbar-row`  separately. The rendered markup looks as follows (under _Direct content projection_ header in preview). Note the first `div` in `toolbar` with **two `toolbar-row` sibling elements**. This is the **expected behaviour**.

```html
<toolbar>
  <div>
    <toolbar-row class="toolbar-first">
      <div>Banner content</div>
      <div controls="">menu1</div>
      <div controls="">menu2</div>
    </toolbar-row>
    <toolbar-row>
       <div style="background-color: white; color: #464646; line-height: 45px; height: 45px;">nav-bar</div>
    </toolbar-row>
  </div>
</toolbar>
```

**2. Content projection into same component when used inside another component**

Now when I wrap the `toolbar` component in another component `banner` which has template like this (_app/banner.component.ts_ file in the plunker):

```html
<header class="banner-layout">
  <toolbar>
    <ng-content></ng-content>
      <div class="banner-filler"></div>
      <ng-content select="[controls]"></ng-content>
      <ng-content select="toolbar-row"></ng-content>
  </toolbar>
</header>
```

which is then used in the following fashion (_app/app.component.ts_ in the plunker):
```html
<banner>
  <div>Banner content</div>
  <div controls>menu1</div>
  <div controls>menu2</div>
  <toolbar-row>
    <div style="background-color: white; color: #464646; line-height: 45px; height: 45px;">nav-bar</div>
  </toolbar-row>
</banner>
```

So basically the content is first projected into `banner` component which is then projected into `toolbar` component since it is being used internally. But now the resultant markup looks as follows (under _Content projection through component_ header in plunker preview):

```html
<banner>
  <header class="banner-layout">
    <toolbar>
      <div>
        <toolbar-row class="toolbar-first">
          <div>Banner content</div>
          <div class="banner-filler"></div>
          <div controls="">menu1</div><div controls="">menu2</div>
          <toolbar-row>
            <div style="background-color: white; color: #464646; line-height: 45px; height: 45px;">nav-bar</div>
          </toolbar-row>
        </toolbar-row>
      </div>
    </toolbar>
  </header>
</banner>
``` 

Note the first `div` in `toolbar`. It just has **one `toolbar-row` element instead of two** and other `toolbar-row` element is a child of it instead of being a sibling indicating the projection was not done.

**What is the motivation / use case for changing the behavior?**

The selective content projection behaviour should be consistent in both the cases mentioned above.

**Please tell us about your environment:**

* **Angular version:** 2.1.x, 2.2.0

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  v6.9.1

**Comment by vicb** [comment]
The issue here is probably that the toolbar `<ng-content>` selector should match the the **ng-content** tags in the banner template vs the original node. We have thought about matching the original nodes but it would be very complex !

So we came up with `ngProjectAs` which can override the selector as seen at the projection site:
```html
<header class="banner-layout">
  <toolbar>
    <ng-content></ng-content>
      <div class="banner-filler"></div>
      <ng-content select="[controls]" ngProjectAs="[controls]"></ng-content>
      <ng-content select="toolbar-row" ngProjectAs="toolbar-row"></ng-content>
  </toolbar>
</header>
```

http://plnkr.co/edit/YHgB32nyqMTh69uCv7Sv?p=preview

We have an issue opened on the docs repo https://github.com/angular/angular.io/issues/1683 but haven't had a chance to get to this yet.
That would be nice if someone from the community could help us here 😉

**Comment by ospatil** [comment]
That's great! Thank you very much for such a quick reply. I'll be happy to take up the documentation issue over the coming weekend provided that someone doesn't beat me to it 😀.

**Comment by pesimeao** [comment]
Great feature! @vicb 

I'm trying to use the ngProjectAs to query the projected content but had no luck until now :(
I've made a plnk based on this issue and #6164.
http://plnkr.co/edit/0PVQk28YcM1qO0E0zsV8
I try to query the "content" element, that was previous projected as "content".

Do you have any thoughts about what I'm doing wrong?
