### ISSUE TITLE
Alternative solution for ngInclude in Angular 2

### ISSUE THREAD

**Issue by amitgaikwad712** [angular/angular#12939]
I doing a Project on Online e-learning with interactive GUI. It has more than hundreds type of questions. Now I have created it for 50 components. But it is going to becomes more complex , that's why I have looking for dynamic rendering like ngInclude was in the Angular 1.x. I want load particular template as per the user select type of question from UI. Because there are more things which are common for all question or few question type like Question title, Description, Answer Choices Component, Multi-select Option, Timer, etc. 
          could someone help me to resolve this problem of redundancy in code and Component ?

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ericmartinezr** [comment]
You can also find some hacks over here https://github.com/angular/angular/issues/2753
