### ISSUE TITLE
Route matcher issues with leading slashes and queryParams

### ISSUE THREAD

**Issue by tiagoroldao** [angular/angular#12936]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When loading an application using a leading slash and query parameters, the route matcher misbehaves:

For the following routes:
```
a
a/:userName
```

Requesting 'site.com/a' and ''site.com/a/' both return the correct route `a`
Requesting 'site.com/a?someParam=1' returns the correct route `a`
Requesting 'site.com/a/?someParam=1' returns the route `a/:userName`

This is an edge case, as [routerLink] elements handle this correctly, and it is only when loading routes directly that the problem is observed

**Expected behavior**
Requesting 'site.com/a/?someParam=1' should return the route `a`, the query parameters shouldn't influence route matching

**Minimal reproduction of the problem with instructions**
Demo isn't possible through plunkr as direct links are not testable
Create an app with the routes defined above, and load the links directly (this only manifests itself on first loads)

EDIT: simplest way to reproduce:
- Clone https://github.com/angular/angular2-seed
- Running:
  - load `http://localhost:3000/#/home` and `http://localhost:3000/#/home/`, verify both work
  - load `http://localhost:3000/#/home/?test=1`, verify a "Cannot match any routes." error is thrown

**What is the motivation / use case for changing the behavior?**

This was found when creating email links to account verification. It is an edge case as specified above, but still possible and may have other implications I haven't considered

**Please tell us about your environment:**

Tested using Typescript + WebPack

* **Angular version:** 2.2.X

* **Browser:** Tested on Chrome 54.0.2840.98
 
* **Language:** TypeScript

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by tiagoroldao** [comment]
Plunkr doesn't reproduce the problem because no direct links to views are possible

**Comment by tiagoroldao** [comment]
I can add a repro for reference, but it will not display de bug (might be useful for copy-pasting?)

**Comment by tiagoroldao** [comment]
Updated description to describe the minimal steps required to reproduce - it is easily reproducible in `angular/angular2-seed`. This repo uses angular version 2.1.0, but it is consistent with what was verified in 2.2.0

**Comment by DzmitryShylovich** [comment]
Related to https://github.com/angular/angular/issues/11275

**Comment by tiagoroldao** [comment]
@DzmitryShylovich I'll close this as a duplicate of #11275 then, it is exactly my issue
