### ISSUE TITLE
property binding does not recognize the value change in a promise

### ISSUE THREAD

**Issue by johnqiuwan** [angular/angular#12948]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The property binding value "showResetPasswordModal" does not recognize the value change in a promise

**Expected behavior**
The property binding value "showResetPasswordModal" should update once the value is been changed in a promise

**Minimal reproduction of the problem with instructions**

HTML
`<site-password-reset  [hidden]="!showResetPasswordModal" (removePasswordResetForm)="removePasswordResetForm($event)" ></site-password-reset>`

Typescript
```
    this._firebase.auth().sendPasswordResetEmail(this.email).then(()=>{
        this.loading = false;
        this.showResetPasswordModal = false;
    })
    .catch((err)=>{this.loading = false; console.log(err)})
    .then(()=>{});
```

**What is the motivation / use case for changing the behavior?**
The value of the "showResetPasswordModal" will set to false after the reset password email is be sent successfully. However, the site-password-reset will always visible.

In addition, if I place the "this.showResetPasswordModal = false;" outside of the then callback, everything works!

```
    this._firebase.auth().sendPasswordResetEmail(this.email).then(()=>{
        this.loading = false;
    })
    .catch((err)=>{this.loading = false; console.log(err)})
    .then(()=>{});

    this.showResetPasswordModal = false;
```

**Please tell us about your environment:**

Windows 8.1 / VisualStudio / npm

* **Angular version:** 2.1.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript ~2.0.3 | ES6

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource looks like firebase + zone.js issue. can be closed
