### ISSUE TITLE
Support Typescript 2.1

### ISSUE THREAD

**Issue by jamespacileo** [angular/angular#12940]
Typescript 2.1 is currently not supported by Angular AOT.

[Typescript 2.1 has been RC for 2 weeks.](https://blogs.msdn.microsoft.com/typescript/2016/11/08/typescript-2-1-rc-better-inference-async-functions-and-more/)

It brings ES5-compatible async/await and ES7-like spread (along with many other features).

Please add 2.1 support.

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/12834#issuecomment-260139619

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr 

@jamespacileo you might use TS 1.8+ in your application, you are _not_ restricted to the same TS version as we are using.

**Comment by jamespacileo** [comment]
Thanks @pkozlowski-opensource @ericmartinezr does this mean any TS version after 1.8, including 2.1, is supported?

I'm raising this because apparently Ionic Framework is stuck at <2.0 until Angular AOT adds 2.1 support.

https://github.com/driftyco/ionic-app-scripts/issues/197

Thanks for your time
