### ISSUE TITLE
Unable to bind to value '0' to Component Input property   value:number

### ISSUE THREAD

**Issue by ckuetherwin** [angular/angular#12947]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a module that takes a number input
@Input() numDays:number;
When passing values through the DOM, all values work except the value '0'. 
<Component [numDays]="0">
It's as if I didn't even pass a number to to the numDays property.  
I have the property initialized as null and when passing '0', the value is still 'null'.
Any other number is passed through fine

**Expected behavior**

To pass the value '0' to the numDays property

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/1iEOEgPMD5YTm6cunB8J?p=preview

**What is the motivation / use case for changing the behavior?**

'0' is a number, it should be able to be passed as input

**Please tell us about your environment:**

It doesn't matter

* **Angular version:** 2.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
`0` evaluates to false this is why u see 999

http://plnkr.co/edit/l8H2mdUo94Tz71pEC4ob?p=preview works as expected.

**Comment by ckuetherwin** [comment]
I've noticed this, however since the input property is a number shouldn't you be able to pass a 0?  If I didn't want to pass the value I simply wouldn't bind to the property.  In my case I need to pass a 0 value

**Comment by DzmitryShylovich** [comment]
http://prntscr.com/d8ktpg ?

**Comment by ckuetherwin** [comment]
Okay I understand the issue now.  Thank you for the help
