### ISSUE TITLE
Reference Error: Can't find variable: Symbol in lang.ts iOS 8.1 safari

### ISSUE THREAD

**Issue by chandanch** [angular/angular#12959]
**I'm submitting a ...*bug report*  ")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I run the application on iOS 8.1 safari browser I get the following error:
ReferenceError: Can't find variable: Symbol:
function: getSymbolIterator — lang.ts
source path: node_modules/angular2/src/facade/lang.ts **at line: 455:26**

It shows a blank white screen and does not load the app.

**Expected behavior**
How to resolve this issue any work around for this?

**Please tell us about your environment:**

   OS: Mac OS X El Capitan
   Node Version: v4.4.5
* **Angular version:** 2.0.0-rc.3

* **Browser:** [iOS XX Safari, iOS XX UIWebView ]

 
* **Language:** [TypeScript  ES6 ]

* **Node (for AoT issues):** `node --version` =   v4.4.5

**Comment by robwormald** [comment]
It appears Safari 8.x does not support Symbol natively. You'd want to polyfill it with core-js or similar.
