### ISSUE TITLE
Compiler should not request setters for @Viewport bindings

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#1295]
This came up originally in https://github.com/angular/angular/pull/1267 where the `Compiler` was requesting a setter for `if` from the template defined on App in [this file][].

[this file]: https://github.com/angular/angular/blob/master/modules/benchmarks/src/naive_infinite_scroll/app.js#L94

Flagging @yjbanov here since he has more context than I do.

**Comment by yjbanov** [comment]
To more precise the compiler should be aware of the fact that in this code:

```html
<template [if]="expression">
  <div></div>
</template>
```

`if` is not a setter because `<template>` is a synthetic element used as the placeholder for `@Viewport`. It therefore never makes sense to look for a setter for the LHS expression `[if]`.

**Comment by naomiblack** [comment]
Assigning to Misko to think about the big picture solution to the "if property in Dart" problem. (https://github.com/angular/angular/blob/master/modules/angular2/src/directives/if.js)

**Comment by mhevery** [comment]
This may not be in issue if #868

**Comment by yjbanov** [comment]
@hevery, sorry, not sure I can connect #868 to this issue. Could you elaborate?

**Comment by mhevery** [comment]
@yjbanov by adding `ng-if` instead of `if` (see #1598) this dart problem goes away. (not sure how #868 got pulled into the discussion.)
