### ISSUE TITLE
Webpack Angular2 does not work with node_modules

### ISSUE THREAD

**Issue by lukemadera** [angular/angular#12952]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Building an angular2 component and using it from npm does not work - the webpack build finishes fine but it gives an error in the browser: 
`Uncaught Error: Unexpected value 'PLIconModule' imported by the module 'AppModule'(…)`

**Expected behavior**
No error in the browser.

**Minimal reproduction of the problem with instructions**
Add an angular2 component as an npm dependency and try to import it and build with webpack.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Mac OSX

* **Angular version:** 2.0.X

* **Browser:** [all]
 
* **Language:** [TypeScript X.X]

* **Node (for AoT issues):** `node --version` =   v5.8.0

**Comment by pringshia** [comment]
Try adding this:
```
module.exports = {
  resolve: { 
    modules: [ path.join(__dirname, "node_modules") ]
  }
};
```

From here:
https://github.com/angular/angular-cli/pull/2291

**Comment by lukemadera** [comment]
Thanks for the prompt reply @chuckjaz  - I've seen that advice and tried that (and many other proposed solutions). Perhaps I have the path wrong as it breaks things for me if I add it in..

Here's a demo project to clone and reproduce the issue.
https://github.com/lukemadera/ng2-webpack

Clone it, then `npm install` then `npm start` then load up `http://localhost:8091` in a browser.
You should see the issue I can't seem to get by..
`Uncaught Error: Unexpected value 'MyIconModule' imported by the module 'AppModule'(…)`

But if the library is in the same repository (rather than included by npm), it works fine:
https://github.com/lukemadera/ng2-component1

You can clone that one too and run `npm install`, `npm start` and go to `http://localhost:8090` and no error.

**Comment by pedro-sanchez** [comment]
I Have the same problem

In angular version 2.1.2 work.

When upgrade to 2.2.0 got the same error.

**Comment by clydin** [comment]
Your component should be using peer dependencies for angular

**Comment by lukemadera** [comment]
@clydin could you elaborate? What do you mean by that?

**Comment by DzmitryShylovich** [comment]
@lukemadera is this still an issue using the latest angular?

**Comment by lukemadera** [comment]
@DzmitryShylovich I made a workaround (webpack plugin to copy node_modules to a local folder) and have been using that. Has something changed with Angular 2 that you think this issue no longer exists? If so I can try it again.

**Comment by DzmitryShylovich** [comment]
@lukemadera yeah, there were some issues with metadata.

**Comment by lukemadera** [comment]
@DzmitryShylovich Sorry for the slower reply; just got around to update things. On Angular 4.0.0-beta.8 and webpack 2.2.1. Now I get a different error, but still not working:

```
Uncaught Error {__zone_symbol__error: Error: Unexpected value 'PLAppNavModule' imported by the module 'AppModule'
    at Error.ZoneAwareEr…, ngSyntaxError: true}
```

All I did was change this line of code:
```
import {
    PLAppNavModule,
// } from "../../index";
} from 'pl-components-ng2';
```

Before it was from a local copy (that works). When I try to import from node modules directly, it still fails. Any ideas?

**Comment by pringshia** [comment]
@lukemadera That error sometimes happens to me when dealing with barrel files. Is PLAppNavModule the last export you have in your index file? If not, try moving it down so it is.

**Comment by lukemadera** [comment]
@pringshia Hmm, it's not at the end of the barrel file, but I need all my exports to work, so moving it down would break the others? That doesn't seem like a good solution..?

**Comment by tbosch** [comment]
Hello,
please move this issue over to https://github.com/angular/angular-cli where we track issues for the webpack plugin.
