### ISSUE TITLE
AOT with upgrade/static depends on eval

### ISSUE THREAD

**Issue by buu700** [angular/angular#12958]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

By default, our application which uses the new static upgrade module works as expected. However, when deployed to an environment with a strict CSP, it complains about the lack of `unsafe-eval` permission and dies.

**Expected behavior**

The environment with the strict CSP should also be functional.

**Minimal reproduction of the problem with instructions**

Navigate to https://buu700-master.cyph.ws with your JS console open.

**What is the motivation / use case for changing the behavior?**

We can't move forward with Angular 2 at all if it requires a weak Content Security Policy, so for us the primary benefit of using AOT is to unblock us here.

**Please tell us about your environment:** OS X El Capitan, with compilation taking place in Debian Jessie in Docker

* **Angular version:** 2.2.1

* **Browser:** Chrome 54.0.2840.98
 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** 6.9.1

**Comment by robwormald** [comment]
The error in your console indicates that you're using the runtime compiler (eg from @angular/platform-browser-dynamic) - therefore *not* actually using AoT:

```
case 0:
                            _context109.next = 2;
                            return __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_5__angular_platform_browser_dynamic__["a"])().bootstrapModule(__WEBPACK_IMPORTED_MODULE_1__appmodule__["a"]);
```

**Comment by buu700** [comment]
Ah okay, got it. I'd thought that needing to use `platformBrowserDynamic` was a quirk of `upgrade/static` because it was used in the example in the new docs (#12717), but apparently I missed a line that would've clarified that:

    // (We are using the dynamic browser platform as this example has not been compiled AoT)

Anyway, got it working now, so thanks!

**Comment by buu700** [comment]
Semi-related, is it expected that AOT compilation will require compiling the same code twice?

To get it working in this project, I had to make it run `ngc` once with `platformBrowser().bootstrapModule(AppModule)`, and then after that run a few `sed` commands on that TypeScript file before compiling again (`s|./appmodule|./appmodule.ngfactory|g`, `s|AppModule|AppModuleNgFactory|g`, `s|bootstrapModule|bootstrapModuleFactory|g`). Not a big deal since it's at least working, but I would've expected `ngc` to have automatically done some equivalent to those replacements on the first pass.
