### ISSUE TITLE
Angular Documentation css property "backgroundColor" is wrong

### ISSUE THREAD

**Issue by ashishdoneriya** [angular/angular#12960]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

In Angular Doc
https://angular.io/docs/ts/latest/guide/ngmodule.html

Under heading "Declare directives and components". There is an example of file app/highlight.directive.ts that sets the background color of element by using 

renderer.setElementStyle(el.nativeElement, 'backgroundColor', 'gold');

Problem is there isn't any such property known as "backgroundColor". Its actually "background-color".

Please correct your documentation.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

**Comment by WilliamKoza** [comment]
Hi,
You must add this issue on angular.io github project : https://github.com/angular/angular.io

**Comment by DzmitryShylovich** [comment]
http://www.w3schools.com/jsref/prop_style_backgroundcolor.asp

**Comment by ashishdoneriya** [comment]
@WilliamKoza I clicked on the link "Report Issues" in the footer of the website angular.io [https://github.com/angular/angular/issues]

**Comment by ashishdoneriya** [comment]
@DzmitryShylovich I ran the sample code and unfortunately JavaScript based syntax (ie. backgroundColor) isn't working. I had to change it to background-color

**Comment by DzmitryShylovich** [comment]
> I ran the sample code and unfortunately JavaScript based syntax (ie. backgroundColor) isn't working

Pls provide a reproduction in plunkr.

**Comment by WilliamKoza** [comment]
With angular 2.0.0, i can write 

`this._renderer.setElementStyle(this._el.nativeElement, 'background-color', 'red');`
or
`this._renderer.setElementStyle(this._el.nativeElement, 'backgroundColor', 'red');`

There is no different. It's work in 2 cases. My element is a div for information.

**Comment by WilliamKoza** [comment]
see https://github.com/angular/angular.io/issues/2677

**Comment by vicb** [comment]
Close as doc issue
