### ISSUE TITLE
Supporting trackBy:<expression|id>

### ISSUE THREAD

**Issue by staeke** [angular/angular#12969]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

* **Angular version:** 2.1.2

**What is the motivation / use case for changing the behavior?**
Related to the discussion here http://stackoverflow.com/questions/36322829/how-to-use-track-by-inside-ngfor-angular-2, I'd like to propose supporting just stating a property name (alternatively inline function) for trackBy. The use case is that ```ngFor``` and ```trackBy``` are very common , and the current requirement of having to specify a function is confusing, terse, and arguably worse than Angular 1. Thus, I'd wish something like this to work

```html
<li *ngFor="let item of items; trackBy:'id'">
  {{item.whatever}}
</li>
```

and/or 

```html
<li *ngFor="let item of items; trackBy:item.id">
  {{item.whatever}}
</li>
```

**Comment by vsavkin** [comment]
I think we closest we can get to supporting this is to support closures/lambdas in bindings. That's why I assign it to core and not common.

**Comment by staeke** [comment]
@vsavkin ok cool. although I think in 99.99% of those cases that lambda is gonna look like ```item => item.id"``` (or ```item => item._id``` or similar). And if the feature is just for brevity...well. Anyhow, thanks

**Comment by Airblader** [comment]
This can be implemented in a custom directive. I've written a post describing it here: https://medium.com/@ingobrk/here-is-how-you-can-use-trackby-with-a-property-name-ec3bbba8fa75

**Comment by vincentjames501** [comment]
I agree that this would be extremely nice especially since our app is using immutable data. Writing trackBy functions everywhere is a pain and not clean at all.

**Comment by vincentjames501** [comment]
So it looks like #12985 was rejected because of potential future property minification issues. @mhevery, is this still a problem today? I'm not convinced that it would be with modern solutions and this is a big pain point for people using immutable data...

**Comment by mlc-mlapis** [comment]
@vincentjames501 ... the minification is a general problem ... just the name is changed after but in this context it's not clear how `the name` could be changed at all during the minification. It is passed as a static string.

**Comment by vincentjames501** [comment]
@Airblader , thanks for the article. I tried testing out the`ngForTrackByField` directive, but looks like the trackby function is invoked before the actual `@Input` property is set which is sort of surprising.

**Comment by intellix** [comment]
Didn't realise I wanted this so much until I was porting a VueJS app to Angular recently.

Looked like this in Vue:
```html
<div v-for="skin in skins" :key="skin.name">
```

and currently the same thing in Angular:
```html
<div *ngFor="let skin of skins; trackBy: getSkinName">
```
```ts
getSkinName(index: number, skin: Skin) {
  return skin.name;
}
```

Closures/Lambdas would make me soooo happy

**Comment by Airblader** [comment]
@Intellix You can make the Typescript part a little but shorter and turn it into a one liner (even when formatted) using

    public getSkinName = (_, skin: Skin) => skin.name;

You can also reuse these functions by importing them and do

    public getSkinName = getSkinName;

since it doesn't need to be bound to the class instance.

**Comment by trotyl** [comment]
@mhevery I can have a try, but an obvious problem is there's no type-checking for the anonymous function, which could make the logic less reliable.

+ Ref: https://github.com/angular/angular/issues/14129
+ Ref: https://github.com/angular/angular/issues/20600

**Comment by gatimus** [comment]
Even shorter:

    public getSkinName = (_, { name }) => name;

Also, I'm also using https://medium.com/@ingobrk/here-is-how-you-can-use-trackby-with-a-property-name-ec3bbba8fa75 as workaround. Seems like just adding the functionality of https://gist.github.com/Airblader/a76396032ddd5becbf329aaeca4c6ea5#file-ng-for-track-by-id-directive-ts to built in NgForOf would satisfy this issue.

**Comment by alberto-chiesa** [comment]
I don't get why this should be so complicated. Really, guys, KIS.
We just need to extend the ngForTrackBy signature to be less pedantic:

```
  private _trackByIndex(index: number, _value: any) {
    return index;
  }

  private _trackByPropertyFactory<T>(propName: keyof<T>): TrackByFunction<T> {
    return (x: T) => x[propName];
  }

  @Input()
  set ngForTrackBy(fn: TrackByFunction<T> | '$index'  | keyof<T>) {
      if (fn === '$index) fn = this._trackByIndex;
      if (typeof fn === 'string') fn = this._trackByPropertyFactory(fn);
      if (isDevMode() && fn != null && typeof fn !== 'function') {
      // TODO(vicb): use a log service once there is a public one available
      if (<any>console && <any>console.warn) {
        console.warn(
            `trackBy must be a function, but received ${JSON.stringify(fn)}. ` +
            `See https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html#!#change-propagation for more information.`);
      }
    }
    this._trackByFn = fn;
  }

  // changes also this signature, just to keep the TS compiler happy
  get ngForTrackBy(): TrackByFunction<T>  | '$index'  | keyof<T> { return this._trackByFn; }
```

Done. No fancy compiler stuff needed. And it's type safe because of keyof.

**Comment by alberto-chiesa** [comment]
If a PR implementing the changes above could conceivably be accepted, I could try to put up something including some tests.

**Comment by nigrosimone** [comment]
Disclaimer! I'm the author of [NgForTrackByProperty](https://github.com/nigrosimone/ng-for-track-by-property)

Angular global trackBy directive by passing a property name for track the ngFor item with strict type checking.

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <ul>
      <li *ngFor="let item of list; trackByProperty: 'id'">{{ item.id }} {{ item.name }}</li>
    </ul>
  `,
})
export class AppComponent {
  list = [
    { id: 0, name: 'foo' },
    { id: 1, name: 'bar' },
    { id: 2, name: 'baz' },
  ];
}
```

[Online demo](https://stackblitz.com/edit/demo-ng-for-track-by-property?file=src%2Fapp%2Fapp.component.ts)

[Source code](https://github.com/nigrosimone/ng-for-track-by-property/blob/main/projects/ng-for-track-by-property/src/lib/ng-for-track-by-property.directive.ts)

**Comment by itayperry** [comment]
Thank you @staeke!! I was just about to submit a feature request about this matter. I see no reason in writing a function in my typescript just so that I could return a key (keyof T - usually a simple string).

**Comment by pkozlowski-opensource** [comment]
Note: the new `@for` control flow makes it much easier to specify the expression that computes tracking keys.
