### ISSUE TITLE
angular 2 child routes lost data

### ISSUE THREAD

**Issue by farrukhsheikh248** [angular/angular#12962]
In child route when navigate then lost input data.
first child : finance
second child : asset 

"i am tired to fix this issue"
when i am going to finance and fill data into field and then going to asset and going back into finance then all data should be lost in finance.

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by vicb** [comment]
Please fill out the issue template and provide a repro. There is nothing we can do with such a succinct description.
