### ISSUE TITLE
Create view message bus

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1297]
```
----
Render API:

class RenderMessageRef {}

class Renderer {
  sendMessage(view:ViewRef, type:string, data:StringMap):RenderMessageRef;
  setMessageDispatcher(view:ViewRef, dispatcher:MessageDispatcher)
}

class MessageDispatcher {
  dispatchMessage(type:string, data:StringMap, inReplyTo:RenderMessageRef)
}

------
App side:

class AppView {
  sendRenderMessage(type:string, data:StringMap):RenderMessageRef;
  waitFor(List<RenderMessageRef>):Promise<List<any>>
}

-----
Render side (under src/render/dom):

class MessageManager {
  handlers:List<MessageHandler>
}

class MessageHandler {
  supports(type:string):boolean;
  handle(view:View, type:string, data:StringMap, messageRef:RenderMessageRef)
}

class View {
  sendAppMessage(type:string, data:StringMap, inReplyTo:RenderMessageRef)
}
```

**Comment by tbosch** [comment]
Very similar to `EventDispatcher` and `EventManager`/`EventHandler`

**Comment by pkozlowski-opensource** [comment]
@tbosch in the `AppView` interface you were proposing `sendRenderMessage(type:string, data:StringMap):RenderMessageRef;` but IMO we should also have a way of referencing individual elements. For example the [class directive](https://github.com/angular/angular/blob/master/modules/angular2/src/directives/class.js) is a decorator directive that allows toggling classes on a particular element within a View.

So 2 questions here:
* How the proposed API would allow me to specify a particular element? Shell we add `ElementRef` or similar to this API?
* How a decorator directive could get a reference to the enclosing View? Is it injectable?

Sorry if this is messed up in my head, but before implementing those services I would like to understand how those would fit / play together in the real-life use case (class directive)

**Comment by tbosch** [comment]
Pawel, you can reference elements within a regular angular view via a bound
element index, which you can get on the app side via ElementRef.
However, imperative views will have their own way of locating elements (eg
a css selector, ...).

That's why the general interface of the MessageBus has no notion of a
location, assuming the location will be part of the data map.

**Comment by pkozlowski-opensource** [comment]
OK, I see, thnx.

**Comment by tbosch** [comment]
Hi, I think this concept gets obsolete!
We have events for render -> app side communication, [actions](https://github.com/angular/angular/issues/1251) for app -> render side communication and imperative views. Together, they should allow to do anything!

**Comment by pkozlowski-opensource** [comment]
Wow, good to hear, since I wasn't that keen on this message bus and was struggling a bit with the impl. Will look at the actions.
