### ISSUE TITLE
AoT compiler does not ignore node_modules .ts imports

### ISSUE THREAD

**Issue by ajcrites** [angular/angular#12973]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When including a library installed in `node_modules` that has a `main` `.ts` file, the aot compiler will not ignore this file even when `node_modules` is specified to be ignored.

You will get an error that looks like:

> Error: Error File 'node_modules/ng2-mqtt/index.ts' is not under 'rootDir' 'app'. 'rootDir' is expected to contain all source files.

**Expected behavior**
These files should either be ignored as part of the compilation or there should be a way to handle them as a special case.

**Minimal reproduction of the problem with instructions**
Install a node_module with a main `.ts` file such as [https://www.npmjs.com/package/ng2-mqtt](ng2-mqtt). In a component file, `import { Paho } from 'ng2-mqtt';`

[Example files for reproduction are here](https://gist.github.com/ajcrites/ce5eb60fe9d85f5a88d0691b10218d7b)

**What is the motivation / use case for changing the behavior?**
Allow for AoT compilation when including TypeScript libraries in node_modules

**Please tell us about your environment:**
OS X 10.11.5

* **Angular version:** 2.2.0

* **Browser:** N/A
 
* **Language:** TypeScript 2

* **Node (for AoT issues):** `node --version` =  7.1.0

**Comment by DzmitryShylovich** [comment]
Related to https://github.com/angular/angular/issues/12725

**Comment by tbosch** [comment]
`ngc` will compile anything TypeScript would also compile. Could you try this by just calling `tsc` on the same `tsconfig.json`?

**Comment by DzmitryShylovich** [comment]
@ajcrites is this still valid in angular 4?
