### ISSUE TITLE
keypress and click events should be triggered after ng-model changes the value

### ISSUE THREAD

**Issue by stenflo** [angular/angular#12975]
THIS IS A FEATURE REQUEST. I'm currently using Angular 2.2.1

I'm trying to respond to an input field change event like this...

`<input type="text" [(ngModel)]="user.name" (keypress)="doSomething()">`

The only problem with "(keypress)" is that "user.name" will not yet contain the most recent value when the doSomething() method is fired because events such as 'keypress' and 'click' are triggered *before* ng-model changes the value. Therefore, it has been recommended to use "(ngModelChange)" instead.

`<input type="text" [(ngModel)]="user.name" (ngModelChange)="doSomething()">`

But the dilemma with "(ngModelChange)" is that the method doSomething() will get triggered not only when the user is typing in the input field, but also whenever any changes are made to the model programmatically.

WANTED: Something like "(keypress)" where the event is triggered *after* ng-model changes the value (I've yet to understand why this shouldn't be the default behavior) OR alternatively, a way to know within "(ngModelChange)" whether the event was triggered in response to a user interaction with the input field as opposed to a programmatic change to the model, as a workaround.

See similar closed issue: ["click event triggers before ng-model changes the value." #3406](https://github.com/angular/angular/issues/3406)

**Comment by kevinglier** [comment]
You can access the"target"-property of the $event-object. The target is the HTMLInputElement, which has the "value"-property. So you should be able to do it the following way:

`<input type="text" [(ngModel)]="user.name" (keypress)="doSomething($event.target.value)">`

You will always get the $event-object and it should always contain the target-property. I don't think that the Angular-Team will change the current behavior, because it would be a Breaking Change. The events need to be thrown before the value is changed, in case you want to maybe manipulate the value before it is updated or cancel the whole event.

**Comment by stenflo** [comment]
thank you for the feedback @kevinglier. Unfortunately your suggestion doesn't quite address the issue I'm having because "$event.target.value" still holds the old value as you have pointed out. In my scenario I need the new value.

While we can obtain the key pressed with "$event.key" or "$event.keyCode" there is no way to obtain the complete "projected" value of the target. There is no use of adding "$event.key" to the end of "$event.target.value" because we don't know if the user was entering characters at the end of the input field or inserting them elsewhere in the input field :-P

I agree the Angular team shouldn't make a breaking change to the current behavior. I agree also there are benefits of handling the event before the model is updated, to manipulate the value before it is updated or cancel the whole event - this is good by design. But there should be a way to hook into user input events with knowledge of the "projected" value of the input field. I'm baffled at finding a good workaround without resorting to jQuery. If only there was something like "$event.projectedTargetValue" available to keypress, or an alternate (keypressAfterModelChange) event hook.

On the flip side (ngModelChange) does not have any "$event" object available the way (keypress) does. So the alternative, to work with (ngModelChange) instead of (keypress), does not allow any way to know whether this is essentially a "KeyboardEvent" or that it's triggered otherwise programmatically somehow.

**Comment by kevinglier** [comment]
Oh, I thought that target.value would contain the new value. I found this topic Stackoverflow: http://stackoverflow.com/a/10911096

You could use a setTimeout to get the new value inside the keypress-event. Or trying to use (input)="doSomething($event.target.value)". I am currently not able to test this.

Another way could be the FormsModule, I think it has callbacks where you can get the old and new values.

If all this still doesn't work, we need a new feature I guess :)

**Comment by zoechi** [comment]
Please provide a Plunker to reproduce. I also think that `event.target.value` will work.

**Comment by stenflo** [comment]
RESOLVED!!!

My solution was to use (input) instead of (keypress) or (ngModelChange).

My pitfall was that I didn't know about (input), and I don't see it mentioned in the docs.

I'm marking this issue as closed. Thanks for all the help on this one!!!

**Comment by zoechi** [comment]
@irrfan13 sounds like you are looking for `keydown`. You can listen to any DOM event using `(event)="..."` binding. `input` also is just the DOM event the browser provides. `ngModelChange` is an Angular event as `ng...` indicates.
