### ISSUE TITLE
What best practices for creating of components

### ISSUE THREAD

**Issue by Valeriy1991** [angular/angular#12978]
I'm a beginner of Angular 2. I'm reading the Angular tutorial, cookbook and try creating one of my application with Angular 2 (server side is ASP.NET Core).

My question is what best practices for instantiation of components? With only using of routing? Or I can write custom "component factory"? Or I can use some existing component factory? What should I do, if I want to create a component, but without a route?

**Comment by WilliamKoza** [comment]
Use router is not mandatory. You can read angular.io for your fisrt step.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
