### ISSUE TITLE
Router 3.2.0 - child routes not loading when parent route has empty path

### ISSUE THREAD

**Issue by Cammisuli** [angular/angular#12976]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Setting up routes that have empty paths do not load any child routes.

**Expected behavior**
I expect the routes to work the same as it did with router@3.1.0

**Minimal reproduction of the problem with instructions**
Here's a reproduction with version 2.1.2 of angular/core and 3.1.2 of angular/router:
http://plnkr.co/edit/v8q3RQp4rdbVtmklCq6W?p=preview
Notice that the child route appears, and you are able to click the button that shows.

Here's a reproduction with the latest version of angular and the router:
http://plnkr.co/edit/KCxtwpls3LwMPFxlRa5P?p=preview
Here, the child route does not load.

**What is the motivation / use case for changing the behavior?**
I expected that a minor upgrade to angular would not cause a breaking change like this.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.2.0

* **Browser:** All
 
* **Language:** Typescript 2

* **Node (for AoT issues):** `node --version` =  v5.10.1

**Comment by GrahamFord** [comment]
I've been going back trying different versions of the router and to me it looks as though this bug was introduced in version 3.3.0.
I couldn't figure out which of the changes introduced the unintended behaviour though.

**Comment by Cammisuli** [comment]
@vicb sorry, I forgot to mention that I found a workaround for the latest version. I reverted the broken plunk to before the workaround.
http://plnkr.co/edit/KCxtwpls3LwMPFxlRa5P?p=preview

**Comment by DzmitryShylovich** [comment]
@Cammisuli what was the workaround? :)

**Comment by Cammisuli** [comment]
@DzmitryShylovich 
Looking at the broken plunk, i moved the redirect route: 
```
{
    path: '',
    redirectTo: '/child',
    pathMatch: 'full'
}
```
from `src/app.ts` to `src/main/main-view.ts`. Doing that allowed the routes to properly work.

**Comment by atscott** [comment]
Confirmed in v9 as well: https://stackblitz.com/edit/angular-ivy-ru59br?file=src%2Fapp%2Fmain%2Fmain-view.ts

Potentially related to #10726
