### ISSUE TITLE
Router: Using UrlMatcher function throws error that path is not defined

### ISSUE THREAD

**Issue by bontscho** [angular/angular#12972]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using the matcher function in Routes, it throws an error that no path has been defined.

Sample Config according to source code:

```typescript
function matcherFunction(url: UrlSegment[]) {
     if (url.length == 1 && url[0].path.startsWith('sample-url')) {
         return {consumed: url};
     }
     return null;
 }

const routes: Routes = [
    {
        matcher: matcherFunction,
        component: ComponentToUse
    }
];
```

The issue is in these 3 error messages: 

https://github.com/angular/angular/blob/master/modules/@angular/router/src/config.ts#L409

These error messages should be corrected to consider an existing matcher function. When omitting these 3 errors,  it works as intended.

**Expected behavior**

It should execute the matcher function and route to the correct component for the given url

**Minimal reproduction of the problem with instructions**

Just add the provided `matcher` function and omit the `path` property for any given route

plnkr: http://plnkr.co/edit/vtpDnJQ4YGtuRAryknqo?p=preview

**What is the motivation / use case for changing the behavior?**

My usecase is to have a matcher for a route with an optional id so the routes:
/news-articles
and
/news-articles/:id

are one route so the component does not get initialised again when navigating from /news-articles to /news-articles/:id

**Please tell us about your environment:**
Mac OS Sierra 10.12.1, VScode 1.7.1

* **Angular version:** 2.2.2
Router version 3.2.2

* **Browser:** all
 
* **Language:** Typescript

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by skreborn** [comment]
@bontscho Please add a plunker that reproduces your problem. The team has no capacity to reproduce each and every issue on their own based on instructions.

**Comment by bontscho** [comment]
i added the plnkr, hope this helps

**Comment by DzmitryShylovich** [comment]
How `matcher` function is a replacement for `path`?

**Comment by bontscho** [comment]
here you have the corresponding error code when you use both at the same time:
https://github.com/angular/angular/blob/master/modules/%40angular/router/src/config.ts#L400

matcher is your custom function to define the path your route should match, here you can have optional parameters just like described in my use case

**Comment by ronaksharma8** [comment]
@bontscho  i have replicated your code into demo project... I am unable to hit the component even though i pass url starting with "sample-url". Can you please let me know if i am missing something.

Below is my code for routing

export const APP_ROUTES: Routes = [
    { path: '', redirectTo: 'profile/:name', pathMatch: 'full' },
    { path: 'auth', component: AuthComponent },
    { path: 'profile/:name', component: ProfileComponent },
    { path: ':name', component: HomeComponent },
    {
        path: ':name/:reponame', component: ProjectComponent,
        children: [
            { path: 'file', component: ProjectContentComponent }
        ]
    },
    { path: '**', component: PageNotFoundComponent },
    {
        matcher: matcherFunction,
        component: ProjectContentComponent
    }
];

export function matcherFunction(url: UrlSegment[]) {
    if (url.length == 1 && url[0].path.startsWith('sample-url')) {
        return { consumed: url };
    }
    return null;
}

**Comment by bontscho** [comment]
@ronaksharma8 the ** route should be the last, since it will always return a match (404). your last route with the matcherFunction therefore will never be checked by the router. try putting the matcher function route before the ** route
