### ISSUE TITLE
Component methods must be public for AOT to work when accessed from the template...

### ISSUE THREAD

**Issue by born2net** [angular/angular#12981]
Component methods must be public for AOT to work when accessed from the template...
IMO its wrong.
A component should be able to mark its properties and methods as private and still allow its template full access (AOT or not). 
Remember this is not just a pure class, its a component and the view is part of it.
And just to prove my point, if you can refer to ```this``` in a template, and ```this``` == the Component / Class, why would you have to mark the methods of the controller / component as public?

Now to make things worse, WebStorm is following this pattern and so it will not allow for refactorting and other helper intelisence as per this PR:
https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FWEB-24234#comment=27-1730331

I beg to re-evaluate this as forcing public on all members of a component just to expose it to the view / template will add uncertainty on OOP and the core concept of encapsulation will be forgone :(

regards

Sean

**Comment by DzmitryShylovich** [comment]
It was already discussed 1m times.
Pls see http://blog.mgechev.com/2016/08/14/ahead-of-time-compilation-angular-offline-precompilation/#the-context-property for technical details

**Comment by born2net** [comment]
That's the technical data but the issue remains

**Comment by robwormald** [comment]
> Remember this is not just a pure class, its a component and the view is part of it.

This is incorrect. It is important to understand that Angular does not modify the behavior of your component class as all. Angular creates a *Host* element that represents the template/view, and it accesses your component instance (the "context"). This is also how typechecking of templates works.

**Comment by born2net** [comment]
so I am not sure from your answer which side are you on?
Do you think members of a component controller should be set as private or as public if only accessed from the template view?

**Comment by robwormald** [comment]
By definition, they must be public. This isn't Angular's opinion or anything. 

The psuedo-code version of what's happening looks like this
```ts

//component 
class MyComponent {
  name: string = 'Rob'
}

//generated HostComponent

class GeneratedHostComponent_MyComponent {
  context: MyComponent = new MyComponent();

  detectChangesInternal(){
    this.renderer.setText(this.el1, this.context.name);
  }
}

```

The generated HostComponent, again, "hosts" the component instance, and accesses its properties *from the outside* - so its just regular Typescript semantics.

**Comment by born2net** [comment]
ok tx clearing it up... from design perspective I really hate to expose all my class members as public just because the view is accessing them :(
Now I have to resort to a hack convention of naming my methods something like:

class MyComponent {
  public t_name: string = 'Rob'; // really private to view
}

so now I need to just go by convention that anything t_ is private (but really public) Yachhhiiiii...

**Comment by robwormald** [comment]
Note that you don't have to explicitly mark anything as public, that's implied if you don't define something as private. Having prefixed conventions is sort of unnecessary, as that's the entire point of the `private` keyword in typescript.

**Comment by born2net** [comment]
yes I know that no need for public... tx.
but this is the thing, I have a HUGE project, and today when I look at a component and I see a bunch of private methods and members, right away I have confidence that I am in control, I can re-factor, I can delete, I can go crazy, why, becuase I know everything that's accessing this private method is close by, its within the same view / controller. BUT, if its all public (or not marked as private, same) now I am worried, can I touch this? will I break something else? who is depending on this? encapsulation is kind of gone!!!! :(

**Comment by robwormald** [comment]
>  BUT, if its all public (or not marked as private, same) now I am worried, can I touch this? will I break something else? who is depending on this? encapsulation is kind of gone!!!! :(

The other way to think about this is that its exactly the same thing here - changing a public property is an indicator to you that you're going to have to update your component's template as well. There is a contract between your component class (the "controller") and the template, and that's expressed in the fact its public.

**Comment by born2net** [comment]
I guess, its as if we need a new decorator
'''
@viewAccessor
myMember
'''

and have typescript allow access only from template...

**Comment by robwormald** [comment]
That adds a huge amount of complexity (and would require changes to Typescript) - this is basically wontfix/works as intended. Final answer. Sorry.

**Comment by gdi2290** [comment]
use `protected` rather than `private`

**Comment by born2net** [comment]
so protected won't fix the AOT issue?

**Comment by mdarefull** [comment]
@robwormald I don't agree with your statements. We can take Web Forms (.NET) as an example. Its protected methods are allowed to be accessed from within their views, although this is not exactly the same architecture, the concept can be extrapolated.

I've came to this issue exactly because we are facing such a situation on an enterprise application my company is working on. We have hundreds of components, so many that they are really difficult to maintain. 
In some cases, some components are referenced as ViewChild and it feels really weird to me that if a component's template needs to access some component method, then that same method will be publicly accessible to everyone. It just seems wrong.

**Comment by mdarefull** [comment]
Couldn't the GeneratedHostComponent just extend the component?
