### ISSUE TITLE
Expose NgForRow as a provider

### ISSUE THREAD

**Issue by bisubus** [angular/angular#12993]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
import { NgForRow } from '@angular/common/src/directives/ng_for';
...
Object.defineProperties(NgForRow.prototype, { ... });

```

**Expected behavior**
```
import { NgForRow } from '@angular/common';
...
class CustomNgForRow extends NgForRow { ... }

@NgModule({
  providers: [{ provide: NgForRow, useValue: CustomNgForRow }], ...
})
class AppModule {}
```

**Minimal reproduction of the problem with instructions**

`NgForRow` has to be imported from `@angular/common` in order to be modified, yet the changes won't be applied if pre-bundled modules are used (e.g. in Plunker).

```
import { NgForRow } from '@angular/common/src/directives/ng_for';
...
Object.defineProperties(NgForRow.prototype, {
  key: {
    get: function () {
      return this.$implicit[0];
    }
  },
  value: {
    get: function () {
      return this.$implicit[1];
    }
  }  
});

@Pipe({ name: 'entries' })
class EntriesPipe implements PipeTransform {
  transform(value) {
    return Object.entries(value);
  }
}

@Component({
  selector: 'app',
  template: `
      <div *ngFor="let heroEntry of heroFeats | entries; let hero = key; let feat = value">
        {{ hero }} saved the day from {{ feat.villain.name }}
      </div>`
})
AppComponent { ... }
```

**What is the motivation / use case for changing the behavior?**

Currently `NgForRow` modification results in hacking, the class isn't injectable and has to be imported from internals. In order to provide extended behaviour to the directive, class prototype should be modified. Pre-bundled UMD Angular 2 modules won't be affected with this hacky approach.

`NgForRow` is responsible for some `ngFor` behaviour and can be used to add new local variables, e.g. in order for #6663 to be addressed.

While not being limited to mentioned use case, the introduction of custom local variables with `NgForRow` allows to bring `ng-repeat` functionality to plain objects in cases where iteration order doesn't matter.

Considering that deep object to array remapping may be impractical, the same snippet without custom locals results in less readable template, which may eventually worsen with nested iterated objects:
```
      <div *ngFor="let heroEntry of heroFeats | entries">
        {{ heroEntry[0] }} saved the day from {{ heroEntry[1].villain.name }}
      </div>
```
* **Angular version:** 2.2.X

* **Browser:** [all]

 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/2246#issuecomment-252654995

**Comment by bisubus** [comment]
@DzmitryShylovich That's correct, I've found myself in the same boat with async iterated objects, though I believe there may be other valid cases for this subject.

I see some problems with the approach that @gdi2290 has shown, it looks like more like a workaround rather than a solution.

`{{ key }} : {{ model[key] }}` is less expressive than `{{ key }} : {{ valueWithMeaningfulName }}` , that's why we've got `Object.entries` in addition to `Object.keys`.

Cluttering up component instance with temporary `model`/`viewModel` pairs doesn't look tidy, async item that was provided through input should be wrapped with another observable. `async` pipe is cleaner and just does the job - when it is applicable. 

Manually subscribed observables should be unsubscribed on destroy, something that `async` pipe takes care of.

**Comment by robwormald** [comment]
Sorry, not really clear why this is a useful thing to expose? It's an internal implementation detail of NgFor, and I'd be against adding complexity to NgFor for a case (key/value iteration) we'd already deemed something we don't really want to support ("allows to bring ng-repeat functionality to plain objects in cases where iteration order doesn't matter.")

I feel like supporting destructuring in expressions would solve this case in a cleaner way... 
```ts
<li *ngFor="let [key, value] of things">
        {{key}}: {{value}}
      </li>
```

and i'd argue that if you're going to do this kind of transform on something Observable its *far* more efficient to do it in your component before it reaches the template:

```
this.things = someInputStream.map(obj => obj.entries())
```

**Comment by bisubus** [comment]
@robwormald I understand the official position on the support of object iteration, but this doesn't necessarily mean that developers should be restrained from implementing it by themselves without total directive rewrite. 

`entries` pipe is there for explicitness, `.map(obj => obj.entries())` is obviously more practical. I totally agree that destructuring would look better in this context, but this would require work on parser. And the hindrance here is how destructuring syntax should translate from `*` to `template`, I guess.

Extensible `NgForRow` would allow limited `ngFor` customization with zero effort, on the other hand. Even an export of non-injectable `NgForRow` from `@angular/common` may help; I don't feel comfortable with adding new accessors to `NgForRow.prototype`, but this doesn't break anything per se.

**Comment by robwormald** [comment]
Internally we don't use it as a provider, so its not exactly zero effort - if it was provided as a provider, we'd get an instance of it - so we'd actually need to refactor ngFor to accept a NgForRowFactory (because we'd need to call it a bunch of times...)

> And the hindrance here is how destructuring syntax should translate from * to template, I guess.

This is a good point. Needs considering. @mhevery ?

**Comment by robwormald** [comment]
Perhaps refactoring to use a NgForRowFactory is a reasonable middle ground here, and then you could provide whatever implementation you like. That said, 3.0.0 is likely to introduce type-safe ngFor so @chuckjaz's input would be needed here

**Comment by gdi2290** [comment]
what's wrong with this?
```typescript
@Component({
  selector: 'app',
  template: `
      <div *ngFor="let heroEntry of heroFeats | entries; let hero = heroEntry[0]; let feat = heroEntry[1]">
        {{ hero }} saved the day from {{ feat.villain.name }}
      </div>`
})
AppComponent { ... }
```

NgForRowFactory would be great since it's the same as using Differs which allows you to manage the template yourself.

```typescript
@Component({
  selector: 'app',
  providers: [ {provide: NgForRowFactory, useClass EntriesNgForRowFactory }],
  template: `
      <div *ngFor="let heroEntry of heroFeats | entries; let hero = key; let feat = value">
        {{ hero }} saved the day from {{ feat.villain.name }}
      </div>`
})
AppComponent { ... }
```



I think for Pipes, it would be better for stateful pipes to expose properties in the template then the developer can have access to the Model and ViewModel created by the pipe

```typescript
@Pipe({
  name: 'keys',
  pure: false,
  expose: ['model', 'viewModel']
})
class KeysPipe implements PipeTransform {
  model = {};
  viewModel = [];
  transform(value) {
    // pretend async stuff happens before setting the model/viewModel
    this.model = value
    this.viewModel = Object.keys(this.model);
    return this.viewModel;
  }
}
```

```typescript
@Component({
  selector: 'app',
  template: `
      <div *ngFor="let key of heroFeats | keys; let hero = model[key];">
        {{ hero }} saved the day
      </div>`
})
AppComponent { ... }
```


I guess that falls apart when you have multiple stateful pipes but at that point the developer is losing predictability in their code since they're managing state in the template.

**Comment by bisubus** [comment]
I'm up to `NgForRowFactory`, this would do the trick.

@gdi2290 `....; let hero = heroEntry[0]; let feat = heroEntry[1]` was my first thought, but `heroEntry` is not available in `ngFor` expression. Actually, [only local variables are available there](http://plnkr.co/edit/YXmsDzlHbRBpXS0yJiEf?p=info), not sure if this is by design or by error.

**Comment by chuckjaz** [comment]
Extending the `NgForRow` in this way is quite awkward since it is unclear how you could do this in a way that will report errors correctly. For example, you would expect that accessing the extended `NgForRow` would only be legal when a non-array is passed. Expressing constraint in TypeScript is a bit challenging since there is no way to overload on type traits.

You also don't need to modify the `NgFor` class itself to extend its selector syntax.

Consider creating an `NgForObject` class instead that has a different context object that expects an object.  The `NgFor` directive is only selected when both `ngFor` and `ngForOf` are present so the `NgForKeyValue` class could have a selector such as,

```ts
    @Directive({ selector: '[ngFor][ngForOf-object]' })
    class NgForObject {
    ...
    }
```

This would then allow something like,

```
  <div *ngFor="let key of-object value; let value = value;"> 
    {{key}} : {{value}}
  </div>
```

This allows you to reuse the object differ and perform special optimizations that are only applicable when an object is the mode for iteration.
