### ISSUE TITLE
Feature request: link and unlink implementation

### ISSUE THREAD

**Issue by kevin-lot** [angular/angular#12997]
**I'm submitting a feature request**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Considering that 
https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/xhr_backend.ts
https://github.com/angular/angular/blob/2.2.x/modules/%40angular/http/src/enums.ts

**Expected behavior**
In file: https://github.com/angular/angular/blob/2.2.x/modules/%40angular/http/src/enums.ts

Can we add "Link" and "Unlink" in enum RequestMethod ?
```
export enum RequestMethod {
  Get,
  Post,
  Put,
  Delete,
  Options,
  Head,
  Patch,
  Link,
  Unlink
}
```

With this additional enum, we could implement our own function methods "link" and "unlink" in file: 
https://github.com/angular/angular/blob/2.2.x/modules/%40angular/http/src/http.ts

Or are there an other way to implement them ?

Thank you.

**What is the motivation / use case for changing the behavior?**
https://tools.ietf.org/id/draft-snell-link-method-01.html

**Please tell us about your environment:**

* **Angular version:**
2.0.X - 2.1X - 2.2X

* **Browser:**
all
 
* **Language:**
all

**Comment by skreborn** [comment]
@kevin-lot I don't think this will be done as `LINK` and `UNLINK` never made it to the HTTP specification as far as I'm concerned.

**Comment by alxhub** [comment]
@kevin-lot the newer HTTP APIs I'm working on will allow `string` values for HTTP methods, so `LINK` and `UNLINK` requests can be made.
