### ISSUE TITLE
Please update the router changelog

### ISSUE THREAD

**Issue by nevster** [angular/angular#12994]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
No clear list of changes

**Expected behavior**
Be able to see the list of what's changed since 3.0.0-rc.2

**Comment by robwormald** [comment]
Router changes are tracked with everything else in the regular changelog : https://github.com/angular/angular/blob/master/CHANGELOG.md

Is there something else specifically you're missing?

**Comment by nevster** [comment]
Ah I see how it works now.

Note for anyone else who comes across this:
- the version numbers for @angular/router are the same as for the other things like @angular/core, just bumped up by 1
- eg if you're using @angular/core 2.2.0-rc.0, then use @angular/router 3.2.0-rc.0 and look at the changelog for 2.2.0-rc.0 in the comment above

Thanks Rob

**Comment by robwormald** [comment]
No worries. This is indeed a bit confusing, we're pondering various solutions to this.

**Comment by nevster** [comment]
Tricky problem. As a small help, a note at the top of the the router changelog would be helpful. I've created a pull request : https://github.com/angular/angular/pull/13000
