### ISSUE TITLE
Router resolver can inject only root providers

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular#12995]
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Resolver injects custom providers from application root only.

But it will be better if resolver can see all providers instantiated above by components on the path (route) down to resolve section. 
 

Minimal reproduction:
https://plnkr.co/edit/3dosVPfBYQpfvGg2qf52?p=preview

1.Click 'child'
2.See console

**Comment by gerhard17** [comment]
Just left a coment at: Router: lazy loaded module doesn't honor component's provider list #10577
Same issue I think.

**Comment by olegdunkan** [comment]
@gerhard17 CanDeactivatedGuard receives component instance, maybe it is possibly to do the same for Resolver or link Resolver's injector to last parent component injector of course it is necessary to consider lazy modules.

**Comment by vicb** [comment]
The hooks are executed before everything is loaded and then not everything is available.
There is no way around but we will try to improve the docs.

**Comment by olegdunkan** [comment]
@vicb ok, thanks.

**Comment by DzmitryShylovich** [comment]
@olegdunkan can you pls re-open it on https://github.com/angular/angular.io/issues ?

**Comment by olegdunkan** [comment]
@DzmitryShylovich sorry, is this issue related to angular.io now? Was it implemented?

**Comment by DzmitryShylovich** [comment]
> There is no way around but we will try to improve the docs.

 https://github.com/angular/angular.io/issues is docs repo

**Comment by olegdunkan** [comment]
@DzmitryShylovich  Ok I will

**Comment by DzmitryShylovich** [comment]
@olegdunkan close this one pls. thx
