### ISSUE TITLE
AoT compilation fails when using 'new' to make a object instance before the '@component' decorator

### ISSUE THREAD

**Issue by eric-heihei** [angular/angular#12998]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The following is my code:
....
let carouselAnimates = new CarouselAnimatesService();
@Component({
      selector: 'app-carousel',
      templateUrl: 'carousel.component.html',
      styleUrls: ['carousel.component.css'],
      animations: [
            trigger('dataSourceState', carouselAnimates.dataSourceAnimate),
            trigger('partnerState', carouselAnimates.partnerAnimate),
            trigger('customerState', carouselAnimates.customerAnimate)
       ]
})

export class CarouselComponent implements OnInit {
    ourDataStyle: any;
    ourPartnerStyle: any;
    ourClientStyle: any;
    carouse1Style: any;
    carouse2Style: any;
    carouse3Style: any;
    dataSourceState: string;
    customerState: string;
    partnerState: string;
    dataSourceImg: any;
    partnerImg: any;
    customerImg: any;
    constructor() { }
    ngOnInit() {
        this.dataSourceImg = carouselAnimates.getDataSourceImg();
        this.partnerImg = carouselAnimates.getPartnerImg();
        this.customerImg = carouselAnimates.getCustomerImg();
        this.dataSourceState = carouselAnimates.dataSourceStates[0];
        this.customerState = carouselAnimates.customerStates[0];
        this.partnerState = carouselAnimates.partnerStates[0];
    }
    ...
}
When running the command 'ng build -prod --aot true', an error occurs:
Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol CarouselComponent in D:/workspace/web-angular2/angular-cli-b20p4V1/src/app/index/carousel/carousel.component.ts, resolving symbol CarouselComponent in D:/workspace/web-angular2/angular-cli-b20p4V1/src/app/index/carousel/carousel.component.ts, resolving symbol CarouselComponent in D:/workspace/web-angular2/angular-cli-b20p4V1/src/app/index/carousel/carousel.component.ts

**Expected behavior**

I want to know how to solve the problem, when using 'aot' to compile the code.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I want to use 'aot' to compile my code  to improve running speed.

**Please tell us about your environment:**

* **Angular version:** 2.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jeanpaulattard** [comment]
Could it be that the build is failing because the object isn't exported.

Would it work if you changed it to 

export const carouselAnimates = new CarouselAnimatesService(); ?

**Comment by jordic** [comment]
What had worked for me is to only put strings on meta info.

**Comment by 18601634641** [comment]
+1,  anyone help? thanks

**Comment by DzmitryShylovich** [comment]
Metadata should be statically analyzable. You cannot call functions, create objects etc.

**Comment by tbosch** [comment]
@DzmitryShylovich is right, sorry. During AoT, we don't execute your code, so we don't know what `CarouselAnimatesService` will contain in the properties `dataSourceAnimate`, ...

So this is works as intended.
