### ISSUE TITLE
ComponentFactoryResolver errors with TestBed

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [angular/angular#13009]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We are injecting ComponentFactoryResolver into a modal service to dynamically create modal components. When testing this service, we discovered that when we create a second test with the modal service (with a different module created with entry components), the instance of the ComponentFactoryResolver from the previous test is still used. Because it only recognizes the entry components from the previous test, it throws errors with a "No component factory found for ModalTest2Component" Error. Note that using beforeEach to inject the ComponentFactoryResolver manually into the test and calling `resolveComponentFactory` instantiates the correct instance of ComponentFactoryResolver.

**Expected behavior**
The updated ComponentFactoryResolver will be injected into our modal service on subsequent tests.

**Minimal reproduction of the problem with instructions**
I pared down our repository to the files necessary to run the modal tests here: https://github.com/Blackbaud-PatrickOFriel/skyux2/tree/modal-ut-issue. The second test file which displays the strange behavior is at https://github.com/Blackbaud-PatrickOFriel/skyux2/blob/modal-ut-issue/src/modules/modal/modal.component2.spec.ts. I inserted a couple console logs to show the injected ComponentFactoryResolver working in the test and not working in the Modal service call immediately after.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   

Thanks for your help and let me know if I can offer any more information

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/10760?

**Comment by Blackbaud-PatrickOFriel** [comment]
I don't believe so, just because in our tests we are importing the modules with the entry components that we are attempting to resolve and it works the first time we use the modal service. The problem is the second time we instantiate the modal service, the old ComponentFactoryResolver is still injected into that modal service.

**Comment by Blackbaud-PatrickOFriel** [comment]
Looks like this might have been a strange edge case on our side caused by our modal host component sticking around between tests (preserving previous injected dependencies throwing subsequent tests off). Thanks for your help
