### ISSUE TITLE
ContentChild and ContentChildren are inconsistent

### ISSUE THREAD

**Issue by cagataycivici** [angular/angular#13002]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ContentChild queries descendants but ContentChildren does not. This commit changed this behavior -> https://github.com/angular/angular/commit/0dc15eb64ac268e115c484319941ba11ce09d596

**Expected behavior**

ContentChild should behave like ContentChildren or better page author should decide with an option like descendats: true|false or we need to new decorators like ContentDescendant and ContentDescendants. Note that if you guys also decide to change ContentChildren to descendants:true all of a sudden, it will break whole a lot of apps. Even if you do, we need a way to customize the default behavior to restore the order back.

**What is the motivation / use case for changing the behavior?**
Lack of support to customize querying.

* **Angular version:** 2.0.X
2.2

**Comment by zoechi** [comment]
Plunker to reproduce?

**Comment by kukjevov** [comment]
Hmm interensting thing is that i tried to change descendants to false, but this change did not changed behavior of ContentChild(TemplateRef). It looks like it is not using it. Can you try changing it?

**Comment by mhevery** [comment]
Yes, we are aware of the inconsistency, and it is our intention. The reason  for the children to not descend by default is imagine if you are querying for `Tabs` but than one of the `Tabs` happens to include more `Tabs` in itself. This is probably not what you want.

On the other hand with child query you are looking for a specific child and so descending is useful as nesting is not an issue.

Works as intended, will not fix.
