### ISSUE TITLE
AoT Compiler breaks down when some dependent lib contains 'node_modules'

### ISSUE THREAD

**Issue by bromzh** [angular/angular#13005]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
In my app I have AoT-ready ng2 library with correct metadata.
I run **ngc** compiler.

1. When that lib don't contains dir **node_modules** then compilation ends successfully. 
2. When that lib contains dir **node_modules** then compilation fails.

For example, second case may be occur when you linking your library via **npm link** or library and app has different angular versions in their dependencies.

**Expected behavior**
Compiler must works same in both cases.

**Minimal reproduction of the problem with instructions**
See https://github.com/bromzh/ng2-aot-issue

**Please tell us about your environment:**
MacOS Sierra

* **Angular version:** 2.2.1

* **Language:** [TypeScript 2.0.9]

* **Node (for AoT issues):** `node --version` =  7.0.0

**Comment by DzmitryShylovich** [comment]
> via npm link

it's a known issue

**Comment by bromzh** [comment]
@DzmitryShylovich but it also may occurs when you have different dependencies in your app and lib.

**Example**.
```js
// Lib package.json
{
  "dependencies": {
    "@angular/common": "2.2.0",
    "@angular/core": "2.2.0",
  }
}
// App package.json
{
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/core": "2.2.1",
  }
}
```

But even if you have same deps versions, but lib have inner _node_modules_ directory, compilation still crashes.

I updated my repo, see case 2 and case 3.

**Comment by gdi2290** [comment]
there is also a problem when using di where it depends on the same js reference when using `instanceof` internally. You have to only have one reference of the angular codebase and if you're using es6-`module` then you can't use the umd bundles. If you use a bundler then you can force it to resolve the correct references

**Comment by tbosch** [comment]
@bromzh if I understand this correctly, this comes down to using nested `node_modules` folders, right? Both your cases 2 and 3 show this problem (e.g. `ng2-app/node_modules/ng2-app/node_modules/@angular/core`). Could you reword this issue accordingly?

**Comment by JoostK** [comment]
I am closing this issue as obsolete. Having nested `node_modules` occurs frequently and has not been a source of bugs in newer versions of Angular.
