### ISSUE TITLE
Angular - moving on from shadow-Piercing descendant combinator - /deep/

### ISSUE THREAD

**Issue by Ne-Ne** [angular/angular#13004]
Hi All,

Just seen the following notice, first I have heard seen until today:

> /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

This is best practise at the moment (https://angular.io/docs/ts/latest/guide/component-styles.html#!#-deep-) ?

Does the Angular Team have a better reccomendation going foward or is this going to be removed going forward?

Current Version: `2.2.1`

Many thanks.

**Comment by DzmitryShylovich** [comment]
It will be supported at least a year (it's a breaking change).

**Comment by PEsteves8** [comment]
Is it known if an alternative way of achieving the same thing will exist?

**Comment by DzmitryShylovich** [comment]
not yet

**Comment by Ne-Ne** [comment]
@DzmitryShylovich 

I think refactoring code using `/deep/` later to change the code again is pointless.

Did anyone from the Angular Core chime in on this depreciation notice?

**Comment by zoechi** [comment]
There is no point in talking about deprecation as long as there is no alternative in sight.
I guess it's at least required that all supported browsers support CSS variables but I wouldn't consider this a good enough replacement because it's still too limiting.

**Comment by zoechi** [comment]
Also that `/deep/` is deprecated in Chrome is irrelevant to Angular2. Angular2 emulates its behavior and doesn't depend on browser support. Other browsers than Chrome never supported it.

**Comment by Ne-Ne** [comment]
> Also that /deep/ is deprecated in Chrome is irrelevant to Angular2. Angular2 emulates its behavior and doesn't depend on browser support. Other browsers than Chrome never supported it.

https://github.com/angular/angular/blob/8f5dd1f11e6ca1888fdbd3231c06d6df00aba5cc/modules/%40angular/compiler/src/css_parser/css_parser.ts#L24

To confirm, Angular will respect this and enforce constant browser behaviour? Regardless of the browser support..

**Comment by zoechi** [comment]
It already does. Try in IE, Edge, Firefox. They never supported `/deep/`.
