### ISSUE TITLE
Title Service should not modify the dom directly

### ISSUE THREAD

**Issue by Darkein** [angular/angular#13007]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It's more an expectation than a bug. A service should never modify the dom directly so why the TitleService is doing it? 

**Expected behavior**
The service should just hold the page title, the dom will be updated by a component or a directive.
Or maybe just find another name for the TitleService? (without 'service' in it of course :))

**Angular version:** 2.2

**Comment by DzmitryShylovich** [comment]
> The service should just hold the page title

Why not? Angular for all dom interactions uses Renderer which is a service :)

**Comment by WilliamKoza** [comment]
I don't understand. Why do you talk about TitleService. The name is Title : https://github.com/angular/angular/blob/master/modules/@angular/platform-browser/src/browser/title.ts

**Comment by Darkein** [comment]
Yes that's true, i've seen it named TitleService in an article, nevermind for the name ^^'

But Title~~Service~~ is still a service.

I'm talking about this because you already have a title tag to hold the page name. Don't you find strange to have a service modifying the content of this tag without having an attribute on it?
And what append when you don't have any tag, what is the expected behavior in this case? 
Is it to angular to add the tag or should it behave without it?

I find proper to have something like an ngTitle attribute on the tag, calling the service. And it answer the question, leaving the choice to the user.

**Comment by DzmitryShylovich** [comment]
`<title>` is outside an angular app so u cannot use directives on it.

**Comment by WilliamKoza** [comment]
If <title> isn't present, Angular create this tag for you.

**Comment by pkozlowski-opensource** [comment]
The existing `Title` service is coming from the browser-specific platform and as such can freely do DOM manipulation (it assumes that it is running in a browser so has access to the DOM). Also there is no need to be "pedantic" about services touching the DOM.

In the feature we might have a generic `Meta` service that will operate on a higher abstraction level.

Closing this one for now as there is nothing immediately actionable here.
