### ISSUE TITLE
Documentation: Provide examples highlighting the benefit of splitting @Component and @View.

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#1301]
There is something novel in this design and I'd like to understand how to best capitalize on the split.

**Comment by naomiblack** [comment]
Yes, this is one of the things we will be covering in the angular.io dev guides. Would appreciate your input on the chapters as we complete them, see https://github.com/angular/angular.io

**Comment by jbdeboer** [comment]
Please provide a link to the angular.io issue.
