### ISSUE TITLE
ng-xi18n throws exception for using full path in templateUrl

### ISSUE THREAD

**Issue by bahodirk** [angular/angular#13016]
I have components where I use full path in templateUrl

```
@Component({
  templateUrl: 'app/components/controls/checkbox/checkbox.html'
})
```
I am aware that I can use moduleId: module.id, but I want to keep full path to html file for my deployment purpose. When I run ng-xi18n, I am getting an error:

```
Error: Compilation failed. Resource file not found: 
C:/Users/TestUser/Source/Workspaces/MyApp/src/app/
components/controls/checkbox/app/components/controls/checkbox/checkbox.html
```
Is there a way to solve this issue without using moduleId: module.id? Thanks

**Comment by ocombe** [comment]
I think that we can close this one, you shouldn't have this issue anymore. Can you confirm @bahodirk ?

**Comment by danbroun** [comment]
I still have that problem. Is it solved in any way?

**Comment by bahodirk** [comment]
On that time, I have updated all my templateUrl into short url with module.id. I haven't checked it.

**Comment by bahodirk** [comment]
@ocombe I am still getting the same error if I use full path `app/components/app.component.html`. Using module.id `app.component.html` not giving any error.

**Comment by ocombe** [comment]
yes, that's why I removed the "can be closed" flag

**Comment by Tryptich** [comment]
@ocombe , ng xi18n generate the message file but it the trans-unit component , i have absolute like you can see 
>  <trans-unit id="656c51a82d4bc457b7be7644e0a08e3cd95ecd33" datatype="html">
        <source>
                Connexion <x id="START_TAG_MD-SPINNER" ctype="x-md-spinner"/><x id="CLOSE_TAG_MD-SPINNER" ctype="x-md-spinner"/>
            </source>
        <target/>
        <context-group purpose="location">
          <context context-type="sourcefile">C:/dev/appvotion/workspace/lekiosque-web/src/app/login/login.component.ts</context>
          <context context-type="linenumber">42</context>
        </context-group>
        <note priority="1" from="description"> administrateur</note>
        <note priority="1" from="meaning">bouton de connexion </note>
      </trans-unit>
how can arrange it pls ?

**Comment by ocombe** [comment]
@bahodirk is this still an issue in v5 now that we have the new compiler?

**Comment by bahodirk** [comment]
@ocombe it is not an issue anymore. Thank you
