### ISSUE TITLE
Angular2 Testbed cannot use overrideComponent if the component class uses a custom annotation

### ISSUE THREAD

**Issue by vandanagopal** [angular/angular#13010]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I use a custom annotation on my component class, then I cannot use TestBed.overrideComponent, since overrideComponent only uses angular2 Component annotation.

**Expected behavior**
Should be able to override a property even if I am using a different Component annotation

**Minimal reproduction of the problem with instructions**
Below is the code:
`
@CustomComponent({
  selector: 'app-root',
  templateUrl: './app.component.html',
  rootCssUrl: 'ife-beagle.css'

})
export class AppComponent {
  title = 'app works!';
}
`
Below is the CustomComponent module code:
`import { Component } from '@angular/core';
import { AppComponent } from './app.component';
const url = require('url/url');

export interface IComponent {
  selector: string;
  template?: string;
  templateUrl?: string;
  styles?: string[];
  rootCssUrl?: string;
  styleUrls?: string[];
  directives?: any;
  providers?: any;
  encapsulation?: number;
}

export function CustomComponent(properties: IComponent): Function {
  try {
    if (properties.rootCssUrl == null) {
      return Component(properties);
    }
     properties.styleUrls.push('./foo.css');
  } catch (err) {
    console.warn(err);
  }
  return Component(properties);
}

`
**What is the motivation / use case for changing the behavior?**
I want to run a test, but TestBed fails if I push a custom css onto the styleUrls property. So I want to override the AppComponent, but can't since it uses a custom annotation.

**Please tell us about your environment:**
windows, npm

* **Angular version:** 2.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =  6.9.1

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
