### ISSUE TITLE
Templates supported by Angular 2

### ISSUE THREAD

**Issue by Kiran-N** [angular/angular#13028]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

html is supported by the angular 2 template urls.

**Expected behavior**
 Angular 2 supporting other templates like JSP, thmeleaf 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows , Tomcat

* **Angular version:** 2.0

* **Browser:** [IE 11 | CHROME]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by bromzh** [comment]
Did u see angular-cli? In its projects you can use sass or less instead of css: https://github.com/angular/angular-cli#css-preprocessor-integration

You can do same thing by configuring webpack. 

Of course you also can write custom template compiler service and use it (instead current compiler) when you bootstrapping modules on platform. But it a little bit complex.

**Comment by Kiran-N** [comment]
I am able to replace the .html with .jsp and it is working. 
templateUrl: `app/app.component.jsp`

Is this supported by angular or will this cause any issue in the near future.

**Comment by wulfsberg** [comment]
JSP and Thymeleaf are serverside templating.
If you load templates on demand runtime, one-by-one, you can generate them however you want. A text file is a text file after all.
But you will be cutting yourself off from a _lot_ of optimization and bundling, including Angular 2's Ahead-of-Time compilation.
Angular 2's philosophy is heavily geared towards bundling, compiling and minifying everything as a single block to deliver to the browser, and then data bind what you need from data services.

**Comment by robwormald** [comment]
as @wulfsberg said, this will absolutely cause issues with ahead-of-time compilation, and we *strongly* suggest you do not do this.

**Comment by Kiran-N** [comment]
Thank you
