### ISSUE TITLE
Plunker throws "Zone is not defined"

### ISSUE THREAD

**Issue by zoechi** [angular/angular#13024]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Open the Plunker link provided by the issue template, check the browser console.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome on Linux

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
only tested with TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
Seems like it is linked to the new zone.js release: https://github.com/angular/zone.js/issues/511

**Comment by ocombe** [comment]
Ahh I was about to post an issue about that myself !

**Comment by ocombe** [comment]
Ok fixed it with using the previous zonejs release, if anyone need one you can use this until the zonejs bug is resolved: http://plnkr.co/edit/JNLFF9qgQJh9t4cBkir7

**Comment by DzmitryShylovich** [comment]
Workaround is to use previous version of zone.js:
```
<script src="https://unpkg.com/zone.js@0.6.26/dist/zone.js"></script>
<script src="https://unpkg.com/zone.js@0.6.26/dist/long-stack-trace-zone.js"></script>
```

**Comment by DzmitryShylovich** [comment]
7.0.1 was released

**Comment by zoechi** [comment]
Works for me now :)
