### ISSUE TITLE
Validators should take just the value, not the entire AbstractControl

### ISSUE THREAD

**Issue by rupebac** [angular/angular#13025]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Right now, AbstractControl has a ValidatorFn, and ValidatorFn takes an AbstractControl to validate. A bit circular but ok.

The problem with this is that you cannot attempt a validation without actually writing it into the model of an AbstractControl. 

Lets say that you want, for instance, assert at construction time that your validators are consistent and that they accept some very basic business values. No way to do this (I believe).

Shouldnt the ValidatorFn validate just a value: any?

**Expected behavior**
Validators not linked to AbstractControl, so that they can be reused outside there.

**Comment by zoechi** [comment]
As stated in the issue template, a Plunker to reproduce is required.

**Comment by lqbweb** [comment]
A Plunker to reproduce a missing feature? What do you want me to do the Plunkr about?

**Comment by zoechi** [comment]
demonstrate the problem that you try to solve

**Comment by ovangle** [comment]
@lqbweb

It's not really an issue. I define my own type `type ValidatorFn<T> = (model: T) => {[err: string]: any}` and use that wherever I want to validate my models outside a form.

Then in `utils/forms` there is a wrapper function

```
import {ValidatorFn as FormValidatorFn, AbstractControl} from '@angular/forms';
export function formValidator(fn: ValidatorFn<any>): FormValidatorFn {
    return (control: AbstractControl) => control.dirty ? fn(control.value) : null;
}
```

Which has an added (small) virtue of not running my validators unnecessarily during change detection. 

👎
