### ISSUE TITLE
Provide idiomatic replacement for ng-model

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1303]

**Comment by naomiblack** [comment]
This is highly anticipated for Material Design and other users.

**Comment by mhevery** [comment]
https://github.com/angular/angular/pull/1887

**Comment by manfredsteyer** [comment]
@mhevery I'm wondering, how #1887 solves this issue. I've looked at the checkin, but I dont see it. Can you provide some information on that?

Does #1887 allow for dynamically creating a ControlGroup with Controls for a field, like ng-model created dynamically a FormController with a ModelController? Or is there an other issue towards this?

**Comment by manfredsteyer** [comment]
has anyone an idea on this?

**Comment by vsavkin** [comment]
There are a few PRs that implemented ng-model. Misko pointed to only one of them.

You can look at this PR that adds an example of using ng-model: https://github.com/angular/angular/pull/2385

**Comment by manfredsteyer** [comment]
Hi Victor,
thanks, that's great and I really like what I see there. I've noticed the new [(xyz)]-Binding. Can you provide some info about this or point me to some web-ressource?
Best wishes,
Manfred

**Comment by manfredsteyer** [comment]
Ok, just found the aswer at your blog: http://victorsavkin.com/post/119943127151/angular-2-template-syntax
Wishes,
Manfred
