### ISSUE TITLE
AfterViewChecked and AfterContentChecked fired too many times during Http get?

### ISSUE THREAD

**Issue by rkonstantinov** [angular/angular#13030]
**I'm submitting a ...** 
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```AfterViewChecked``` and ```AfterContentChecked``` hooks seems to be executed twice as much when using http request to populate a Component field in opposite when for example an ```Observable.timer``` is used to do the same. I guess that something in the Http implementation make the zone ticks.

**Expected behavior**
To not trigger the hooks while the request is being processed.

**Minimal reproduction of the problem with instructions**
minimal demo -> http://plnkr.co/edit/QHqw4dsQbG7SVOd7bEwE?p=preview
please take a look at the console output

* **Angular version:** 2.2.X

**Comment by wesleycho** [comment]
Zone likely needs to patch for the moment that the http request is fired and when the response is received, whereas Observable.timer should trigger only once.

It might be worthwhile to gate the `AfterViewChecked`/`AfterContentChecked` usage by actual state changes to avoid unnecessary logic evaluation as a result of triggers from situations like this. IMO this isn't a library bug at all.

**Comment by rkonstantinov** [comment]
Indeed, I'm OK with ticks at the start and the end. Those in the middle, while the request is still in progress  seems a bit odd. 
I can achieve the "expected" behavior by running the request outside angular. However running by default the checks for the entire component tree while nothing is happening seems a bit wasteful in this case.

**Comment by alxhub** [comment]
Closing as this is obsolete (it concerns `@angular/http` which has been removed in favor of `@angular/common/http`).

For `@angular/common/http` this is tracked in #27593 and indeed, I suspect it's zone.js causing the behavior you see.
