### ISSUE TITLE
http.post sends two requests instead one

### ISSUE THREAD

**Issue by rezikovka** [angular/angular#13033]
```
angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: linux x64
```

```
    "@angular/common": "~2.2.0",
    "@angular/compiler": "~2.2.0",
    "@angular/core": "~2.2.0",
    "@angular/forms": "~2.2.0",
    "@angular/http": "~2.2.0",
    "@angular/platform-browser": "~2.2.0",
    "@angular/platform-browser-dynamic": "~2.2.0",
    "@angular/router": "~3.2.0",
    "@angular/upgrade": "~2.2.0",

```

When i try to send http.post request with json data to my api server, i see in my browser 2 requests instead one. One of them with my data, the other is empty. This way i have 2 responses - one response with errors (because empty data are not valid), and the other response with correct reaction on data sent. Is it bag?

Plunker: http://plnkr.co/edit/NnpM6jwDrCkhavKeEZa9?p=info

If you have a luck at Chrome in Dev.Tools -> Network, you will see two requests. one of them have respons with true, the other - false

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by DzmitryShylovich** [comment]
The first one is preflight request https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

**Comment by rezikovka** [comment]
Thanks)) this is my shame :-)
