### ISSUE TITLE
Add scroll events to Angular.

### ISSUE THREAD

**Issue by ghost** [angular/angular#13048]
[ ] bug report
[x] feature request
[ ] support request

**Current behavior**

I've done a research to find a functionality within Angular 2 framework to detect the vertical position of the scroll bar so I can trigger animations in certain breakpoints, but the only [helpful solution](https://groups.google.com/forum/#!topic/angular/Sg326P53gRA) was a work around using Renderer class.
here is the code (toggle 'shrink' variable to active after 75px scrolled):

```
   constructor(private renderer: Renderer) {
    this.renderer.listenGlobal('window', 'scroll', (event) => { 
       this.shrink = (event.pageY>75 ? 'active' : 'inactive');
        });
```
 the problem is that there is no built in functions for scroll events, moreover, the code above does the trick only on firefox web browser because the pageY attribute (contains the vertical position of the scroll bar in pixels) has a different name in the scroll `event` object given by the browsers other than firefox (`event.pageY` is undefined [Chrome/Edge]).

**Expected behavior**

Provide functionalities dedicated for scroll events that works with the majority of web browsers.

**What is the motivation / use case for changing the behavior?**

Scroll events are very useful especially when it comes to animations (sticky headers...).

**My environment:**
Operating system: Windows 10
IDE: VS Code
package manager: npm/yarn
HTTP server: lite-server
* **Angular version:** 2.2.0

 
* **Language:** [all | TypeScript 2.0.3 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   7.1

**Comment by robwormald** [comment]
> the problem is that there is no built in functions for scroll events

What kind of functions would you expect to see? 

Scroll (and basically any) events can be listened to at the global level declaratively - see https://plnkr.co/edit/Us75dNkSKpaxXDvHtk0K?p=preview

Beyond that, I'm not sure what else we could provide in the core library. We generally feel like this kind of thing is better left to 3rd party open-source libraries to handle, as we are unlikely to cover every single use case one might want. A quick Google search reveals such libraries as https://www.npmjs.com/package/ng2-page-scroll or https://github.com/jkuri/ng2-slimscroll that are doing exactly this sort of thing - building their own extensions to Angular.

**Comment by ibraback** [comment]
Scroll events are very useful when it comes to animations, including them to the framework natively will be a great thing because scroll detection is widely used by many web developers (UI/UX) in most of their projects, they are comparably important to _click_ or _keypress_ events.

**Comment by robwormald** [comment]
Again, I don't know what you mean by "natively" - angular already supports "native" scroll events, like it natively supports every other browser event (like click or keypress). 

What, specifically, are you asking for?

**Comment by ibraback** [comment]
keypress and click events work in **every** browser as expected **without** including any external library, scroll event have a compatibility issue when it comes to the attribute names, for example in my case when I tried to retrieve `event.pageY` variable content, it worked only on firefox web browser [Chrome and Edge => undefined].

**Comment by b-strauss** [comment]
`pageX` and `pageY` are not standardized.

**Comment by wesleycho** [comment]
This should not be supported in Angular itself - not all applications require hooking into the scroll event, and it is not difficult to create a custom mechanism that listens for the appropriate events.

**Comment by BigFax** [comment]
How can we know which DOM events are supported directly (without host or @HostListener) ?

**Comment by zoechi** [comment]
@BigFax what do you mean with "supported directly"?

**Comment by BigFax** [comment]
I mean : i can do `(click)="myClickFunc()"` but i can't do `(scroll)="myScrollFunc()"`
click is supported, not scroll. I need to do : 
```
@HostListener('window:scroll', ['$event']) 
doSomething(event) {
   // ...
}
```
From : https://angular.io/docs/ts/latest/guide/user-input.html#!#binding-to-user-input-events

> You can use Angular event bindings to respond to any DOM event.

List of DOM event : https://developer.mozilla.org/en-US/docs/Web/Events
But they are not all "supported" as "click" is by default.
Is there a specifc list of DOM event supported by Angular ?

**Comment by zoechi** [comment]
@BigFax `(click)` listens only to click events of the element where you added it.
`(scroll)` also listens only to the element where you add it. If you add `(scroll)` to a `<div (scroll)="myScrollHandler($event)"` it won't be called when the window scrolls, only when the content of the div is scrolles.
Perhaps you want `<div (window:scroll)="myScrollHandler($event)"`

**Comment by BigFax** [comment]
No, it wanted to use scroll on my element and not on window, but my test was not good (the scrollbar was not on the element i was thinking).
Sorry and thank you.

**Comment by zygimantas** [comment]
I have also noticed that hammerjs swipe events are not detected.

**Comment by zoechi** [comment]
I think this can be closed.

**Comment by emilio-martinez** [comment]
HammerJs events are obviously from a third party; there's no reason for them to be supported out of the box in Angular. However, as other's have said, it's the case with scroll as well as touch events (e.g., touchstart, touchmove, etc) that they are supported simply because they're JS events. For the same reason, it would be expected for event data to come with the applicable cross-browser inconsistencies because it's not Angular's concern to fix the browsers but rather to provide the tooling to more easily author and implement these solutions.

**Comment by ShivPandey** [comment]
> I mean : i can do `(click)="myClickFunc()"` but i can't do `(scroll)="myScrollFunc()"`
> click is supported, not scroll. I need to do :
> 
> ```
> @HostListener('window:scroll', ['$event']) 
> doSomething(event) {
>    // ...
> }
> ```
> 
> From : https://angular.io/docs/ts/latest/guide/user-input.html#!#binding-to-user-input-events
> 
> > You can use Angular event bindings to respond to any DOM event.
> 
> List of DOM event : https://developer.mozilla.org/en-US/docs/Web/Events
> But they are not all "supported" as "click" is by default.
> Is there a specifc list of DOM event supported by Angular ?

if you are using angular material it will not going to work scroll :) use cdk to handle scroll
