### ISSUE TITLE
Lazy loading complex module makes app unresponsive for some time

### ISSUE THREAD

**Issue by iwoogy** [angular/angular#13049]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When lazy loading a complex module, the browser hangs and the web app freezes until the module finished bootstrapping. In the worst case, it could last 20 seconds.

**Expected behavior**
I would like to have some events on lazy loading process to display some waiting message to explain what's going on. And the module bootstrapping should not make the whole web app non responsive.

**Minimal reproduction of the problem with instructions**
Lazy load a complexe module (ex: 4 components with html template of 2000-3000 lines).

**What is the motivation / use case for changing the behavior?**
The user feels like the application crashed.

**Please tell us about your environment:**
OS X: 10.11.6
AngularCLI : beta.18

* **Angular version:** 2.0.X
Angular: 2.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =

**Comment by robwormald** [comment]
As stated in the issue template, please provide a reproduction of your issue. We are unable to help you if you do not provide your code in a runnable fashion. 

This is most likely the dynamic compiler running to compile your components, and this is generally a non-issue in AoT mode. I'd suggest moving to AoT mode if you're not already.

Additionally, what exactly are you doing that you've got a *3000* line template?

**Comment by iwoogy** [comment]
Thanks for your explanation.

I'm using angular-cli to build the project.

So far the cli does not fully support AOT as I understand.

I will wait for the CLI AOT support then.

For the 3000 lines, I'm building a configurable form with auto saving on each input. so a single value input take about 50 lines (error message, valid message, saving in progress message).
