### ISSUE TITLE
Renderer.setText for platform-browser is broken after 2.2.x

### ISSUE THREAD

**Issue by log2-hwan** [angular/angular#13047]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Renderer.setText function doesn't update element's text content.

**Expected behavior**
Renderer.setText function should update element's text content.

**Minimal reproduction of the problem with instructions**
Working version (2.1.2): http://plnkr.co/edit/jXl54wPrjcg4l6BYiv5a?p=preview 
Broken version (2.2.2): http://plnkr.co/edit/CCpPqGU1YvVQZAKw5I4L?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.2.x

* **Browser:** all
 
* **Language:** TypeScript 2.0.3

**Comment by gdi2290** [comment]
here's a workaround until a patch is released
```js
import { DomRenderer } from '@angular/platform-browser';
DomRenderer.prototype.setText = function fixSetText(renderNode: any, text: string): void {
  renderNode.textContent = text;
}
```

**Comment by tbosch** [comment]
`Renderer.setText` was never meant to be used for elements, only for text nodes.
I.e. it still works to update text nodes, but not replace the text content of elements. So this works as intended.

To do this, just use `elementRef.nativeElement.textContent = ...` directly. This won't work on webworkers, but our webworker story is not complete yet (and also experimental), the most important part, custom render services, is still missing which will allow you to split your services into a UI and a worker part
(see https://github.com/angular/angular/issues/2409).

**Comment by DzmitryShylovich** [comment]
@tbosch 
> Renderer.setText was never meant to be used for elements, only for text nodes.
I.e. it still works to update text nodes, but not replace the text content of elements. So this works as intended.

what about [dom adapter](https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/browser/browser_adapter.ts#L185)?

> To do this, just use elementRef.nativeElement.textContent = ... directly

universal?

**Comment by IgorMinar** [comment]
BrowserAdapter is not a public API, universal has been reaching into private API space. This is a known issue and we are working on fixing this in Universal.

**Comment by tbosch** [comment]
The change was introduced in https://github.com/angular/angular/commit/d708a8859ca3078a98e371b33ad560096070ad00. However, this was already in 2.2.0, but somehow we didn't update our bundles correctly...
