### ISSUE TITLE
Content lifecycle on conditional transclusion

### ISSUE THREAD

**Issue by ghetolay** [angular/angular#13059]
**I'm submitting a ...** 
```
[x] bug report
```

**Current behavior**
When you use conditional directive on `<ng-content>` content component are correctly added/removed to the DOM depending on the condition but they have weird lifecycle. They have the same lifecyle than the parent, meaning when they are removed from the DOM the component instance is kept and reuse when they are added again to the DOM.

**Expected behavior**
Content component should have their own lifecycle corresponding to the conditional. Instantiate when adding to the DOM and destroyed when removed from the DOM.

**Minimal reproduction of the problem with instructions**
Component using transclusion like that : 
```ts
@Component({
  selector: 'conditional-content'
  template: `
    <ng-content *ngIf="condition"></ng-content>
    <button (click)="condition = !condition">toggle</button>
  `
})
```

Let's say you do : 

```
<conditional-content>
    <some-component></some-component>
</conditional-content>
```

then `<some-component>` will have the same lifecycle has `conditional-content`.

Plunker example:
https://plnkr.co/edit/KdyKG6qtiA9eoqxJOIep

**What is the motivation / use case for changing the behavior?**
When content component rely on `ElementRef` because it becomes null when component is removed from the DOM.

* **Angular version:** 2.0.X
2.X.X

* **Browser:** [all]
 
* **Language:** [all]

**Comment by ghetolay** [comment]
I don't know if it's related but you can't use some animation inside transclusion. If you run [that plunker](https://plnkr.co/edit/vxH14hTvq4HPpGjwZJiy) for example, it'll freeze to death.
I don't really know what's causing this because if you change `transition()` or `animate()` parameters you can make it work but that special combinaison just doesn't. 

```ts
@Component({
   selector: 'test',
   template: `
     <div *ngIf="condition">
       <ng-content></ng-content>
     </div>
  `
})
```

```ts
@Component({
   template: `
     <test>
       <div @animation></div>
     </test>
   `,
  animations: [
    trigger('animation', [
	transition('void => *', animate('0.5s', style({opacity: 1})))
    ])
 ]
```

**Comment by zoechi** [comment]
The transcluded component is created as part of the parent, it's just displayed where the `<ng-content>` element is placed.

Can you please elaborate a bit more on 

> When content component rely on ElementRef because it becomes null when component is removed from the DOM.

I don't get what problem you're actually trying to solve and how the change would help.

**Comment by ghetolay** [comment]
From the [docs](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html) : 
> A component has a lifecycle managed by Angular itself.
>
> **Angular creates it, renders it**, creates and renders its children, checks it when its data-bound properties change, **and destroys it before removing it from the DOM**.

So from my understanding I don't expect a component instance to exist if it's not part of the DOM.

I took ElementRef as an example but I guess we could find more scenarios. 
Any component using ElementRef on `constructor`, `ngOnInit()` or `ngAfterViewInit()` will face a null `nativeElement` if the initial condition is false. 
Or even if the initial condition is true and you listen for an event, once the condition will turn to false, you won't listen anymore to that event because the component's element has been removed. And even if the condition becomes true again you won't never listen to the event anymore because none of `constructor`, `ngOnInit` nor `ngAfterViewInit()` will never be called again.

**Comment by tbosch** [comment]
This is by design. The lifecycle of a component is always tied to the place where the component was declared. I.e. not at the place where the `<ng-content>` is used. To conditionally create / destroy components together with content projection, use `<template>` and `ngTemplateOutlet`.

**Comment by gangadharjannu** [comment]
ngTemplateOutlet is in 'Experimental' state. Can we use it in production app? @zoechi @tbosch

**Comment by tbosch** [comment]
@gangadharjannu yes

**Comment by guaido79** [comment]
Same issue as @ghetolay. 
```
<ng-template [ngIf]="showContentAndStartHisLifecycle">
        <ng-content></ng-content>
</ng-template>
```

```
<component-with-content #master ([myData)]='myObservableData'  [showContentAndStartHisLifecycle]='_showContentAndStartHisLifecycle'  >
       <component-nested  [myDataOutOfSyncDuringLifecycle]='master.myData.property' ></component-nested>
</component-with-content>
```
**_showContentAndStartHisLifecycle** is declared as false but  <component-nested></component-nested> have is lifecycle called (but isn't in the dom),

**Comment by Antoniossss** [comment]
If this is by design, why the behavior is different when I use plain <ng-container>with condition? Using simple example that @guaido79 provided if we do
```
<ng-container *ngIf='_showContentAndStartHisLifecycle'  >
       <component-nested  [myDataOutOfSyncDuringLifecycle]='master.myData.property' ></component-nested>
</ng-container>
```

Then nested component is not initialized like expected

**Comment by FrozenPandaz** [comment]
For anyone still confused about this:

This video helped me: [Deep dive into content projection - Eudes Petonnet](https://www.youtube.com/watch?v=PTwKhxLZ3jI)
