### ISSUE TITLE
Router resolver are not canceled when we change a route.

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular#13056]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/ibO93yyF9H7I7bGHh1qO?p=preview

1.Click 'Parent'
2.Click 'Home' immediately (you have 3 sec to cancel route).
3.See console. You will see that the disposing function will be called after the resolving process will be completed.

I expected the resolver to be canceled immediately if we change the route. 

The motivation is simply the same as the motivation why we use rxjs, we can unsubscribe observable (dispose in rxjs 4) in any time (unlike promises), to cancel, for example, any backend requests and other unnecessary processing.
 
I don't know exactly is that is bug or design choices but I think it's very important to have that opportunity.

**Comment by vicb** [comment]
This is a design choice.
Rationale is that you can also use a Promise there and we want that both behave consistently.

**Comment by olegdunkan** [comment]
It so strange. Why you can't treat a promise and a observable as self-sufficing entities? The are not the same. And by the way, a simple value returning by resolver also has to behave consistently with promise and observable?) Because I don't understand what do value, promise and observable have in common? Yes, promise and observable have some in common we can wait for, they are async entities, value - we have right now, why we can't cancel waiting for observable?
Ok, thanks for answer. I appreciate this.

**Comment by goldenbearkin** [comment]
@vicb 
I think this issue shouldn't be closed or at least become a feature request. Now, there is no way to cancel the Observable subscription inside the resolve function. Resolve function makes less sense if it is not cancellable given even the route has changed, everything is frozen for waiting for the abandoned request back before next meaningful routing.
