### ISSUE TITLE
Router: Provide option to inherit data and params

### ISSUE THREAD

**Issue by klinki** [angular/angular#13058]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Current behavior of inheriting route data and params is not very clear. 
AFAIK it inherits when:
- route path is empty
- parent path doesn't have component set

**Expected behavior**
Please provide option to always inherit params and data. Of course it would be the best to have it as default behavior, but I understand it is not default now, and if it is not possible to make it default, I suggest those options how to do it:

1) One possibility could be to add parameter inheritParams to route definition.

So routes would like
```javascript
{
  path: 'groups/:groupId',
  component: GroupLayoutComponent,
  resolve: {
    applicationGroup: ApplicationGroupResolve
  },
  children: [
    { path: '', component: GroupPageComponent, inheritParams: true },
    { path: 'edit', component: ApplicationGroupForm, inheritParams: true },
    { path: 'applications', inheritParams: true, children: [
        { path: 'register', component: RegisterApplicationFormComponent, inheritParams: true },
        { 
	  path: ':applicationId', 
          inheritParams: true, 
          resolve: {
              application: ApplicationResolve
          },
          children: [
            { path: 'edit', component: EditApplicationFormComponent, inheritParams: true },
         ]
       }
    ]}
  ]
}
```
And after accessing url `/groups/1/applications/2/edit` `ActivatedRoute.data` would return: 
```javascript
{ 
  applicationGroup: {}, // resolved app. group from top-level route by ApplicationGroupResolve, 
  application: {} // resolved app. from last route by AppResolve
}
```

2) Second (and I think better) option would be to add additional fields to `ActivatedRoute`, which would contain inherited data. Something like `allParams` and `allData` (all because it would contain parameters of current route + inherited parameters).

3) Third possibility would be to add configuration option to RouterModule. (Similar as with `useHash: true`).

It could be something like boolean variable `alwaysInherit` or `iheritMode` with options `'always'` `'default'`

**What is the motivation / use case for changing the behavior?**
Currently it is not very clear how parameters and data inheritance works. It hasn't been documented properly. 

There are already some issues (https://github.com/angular/angular/issues/12767, https://github.com/angular/angular/issues/12306) when people expect this to be working.

Also workaround to get described behavior is very complicated.

**Comment by DzmitryShylovich** [comment]
It was already explained https://github.com/angular/angular/issues/12767#issuecomment-260493205

**Comment by klinki** [comment]
I know, I've been following that thread. But the fact it is already explained  (in github issue comment, I think it is still not explained in documentation)  doesn't change anything on the main motivation for this proposal - to get inherited parameters and data for all routes.

**Comment by vicb** [comment]
We do not plan to change the implementation as this is something you can implement easily according to your needs.

We look into improving the docs.

**Comment by klinki** [comment]
It is not so easily implemented. 

I have to subscribe to router NavigationEnd event and than use data from ActivatedRouteSnapshot. From that snapshot I can get required data with tree traversal up and down. It is annoying, but doable. 

But what concerns me more is testability. Because of this workaround, all components requiring it (and for our use case, quite a lot of them) are much worse testable.

**Comment by klinki** [comment]
@vicb We are constantly running into more and more issues with our workarounds for hierarchically resolving route data. It is definitely NOT easily implemented. Could you please provide some guidance how to do it easily and properly?

We currently have something like this:
https://gist.github.com/klinki/7fd7cc3eadb1c120c4f007154fb7e6c0

But there are multiple issues with it:
- every component now depends not only on `ActivatedRoute` but also on `Router` and `RouteFlattener`
- testing is much more difficult - you need to provide mock for `ActivatedRoute` and `Router` and not forget to trigger `NavigationEnd` event
- it doesn't really work very well for child components - they won't get `NavigationEnd` event, because they subscribe after that event occurs. To solve that, they need to use `ActivatedRoute`, load data from it and also do the `NavigationEnd` boilerplate

We managed to improve the last issue by listening to `NavigationEnd` events in `AppComponent` and providing a service which has `Observable` with already flattened route data.
But testing is really quite crippled by it.

We already considered writing our own custom Router. We wanted to extend existing Angular one and provide option to hierarchically resolve data. Unfortunately that is not possible, because all interesting things happen in `private` methods (could you please consider using `protected` instead?). We'd have to fork Angular Router (which means fork Angular) and fix it there. That is something we definitely don't want to do. 


Using Router has been really a huge pain for us and we are considering ways how to abstract it or get rid of it completely. But that's whole different story and doesn't help with this issue.

**Comment by DzmitryShylovich** [comment]
@klinki have you tried ui router?

**Comment by klinki** [comment]
@DzmitryShylovich I have considered it, but I didn't like the documentation much and I also wasn't happy I'd have to rewrite a lot of code to use it.  But it might be worth it after all. Do you have experience with it? Does it support hierarchical resolving of data and parameters?

**Comment by DzmitryShylovich** [comment]
> Do you have experience with it? 

no, I don't, but it's better than `We already considered writing our own custom Router` :)

**Comment by klinki** [comment]
Yep, that is :) you are right. I'll try to prototype it and we will see if it is better.

**Comment by wardbell** [comment]
I'm removing the "docs" label because there is no concrete documentation proposal here. We do not cover corner cases and wild workarounds in documentation because they confuse the general audience. If you have something you like, stackoverflow is a good place for it.

**Comment by dirkluijk** [comment]
We are running into the same issue over and over again. We have quite a lot levels of nested routes. What bothers me is that the component needs to know *where it is registered in the route tree*. 

When you change add a level (e.g. with an empty paths) you need to change your component.

Besides that, it is quite messy to have `route.parent.parent.parent.data.map(...)` in your code.

In the ideal world, I would just need to ask for the route data like this:
```
@Component()
class MyComponent {
	constructor(
		@RouteData('key') private foo$: Observable<Foo>
	) { }
}
```
And than find the first `Data` containing 'key' and map it.

**Comment by scaljeri** [comment]
This is indeed a very annoying problem. @dirkluijk I have taken the time to write a decorator which probably does what you need, except that it is a property @decorator So instead of doing:
 
```typescript
bar$: Observable<Foo>;
...
this.bar$ = this.route.parent.parent.parent.parent.data.map(d => d['bar'])
```

you can write it
```typescript
    @RouteData() bar$: Observable<Foo>;
```

For those interested, I have it published to npm [here](https://www.npmjs.com/package/angular-route-xxl). Hope it helps!

**Comment by jasonaden** [comment]
#20678 will solve this problem.
