### ISSUE TITLE
<select> can't initial when ngValue is object

### ISSUE THREAD

**Issue by lonyel** [angular/angular#13053]
`
@Component({
  selector: 'my-app',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss']  
})

export class AppComponent { 
    selected: any = {id: 1,name: 'a'};
   datas: any = [{id:1,name:'a'},{id:2,name:'b'}];
  }
`
`<select [(ngModel)]='selected' name='sekected' >
      <option *ngFor='let kk of datas' 
        [ngValue]='kk'>
          {{kk.name}}
      </option>
  </select>`

The <select> not initial at 'a'. if set 'selected=datas[0]',it's OK. Hope like angular1,use 'trackby kk.id' to resolve it.

 "@angular/common": "~2.2.2",
    "@angular/compiler": "~2.2.2",
    "@angular/core": "~2.2.2",
    "@angular/forms": "~2.2.2",
    "@angular/http": "~2.2.2",
    "@angular/platform-browser": "~2.2.2",
    "@angular/platform-browser-dynamic": "~2.2.2",
    "@angular/router": "~3.2.2",
    "bootstrap-material-design": "^0.5.10",
    "core-js": "^2.4.1",
    "ng2-bootstrap": "^1.1.14",
    "rxjs": "5.0.0-rc.4",
    "zone.js": "^0.7.1"

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

If you actually think it's a bug, it's required that the issue template is filled.

**Comment by robwormald** [comment]
@lonyel `trackBy` in Angular 2 uses a *function*:

```html
  <li *ngFor="let thing of things; trackBy:trackThing">
```
```ts
class Comp {
  trackThing(index, item){
   return item.id;
  }
}
```
