### ISSUE TITLE
update dependencies and devdependencies

### ISSUE THREAD

**Issue by e-cloud** [angular/angular#13051]
**I'm submitting a ...**  (check one with "x")

* [ ] bug report => search github for a similar issue or PR before submitting
* [x] feature request
* [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior**
a lot of outdated devDependencies. And some of dependencies are also not up-to-date.

**Expected behavior**
update dependencies as much as possible

**What is the motivation / use case for changing the behavior?**
keep updating dependencies could improve dev performance and code quality.
updating the dependencies incrementally can avoid big changes to the code base.

**Angular version:** 2.2.x

---
I have tested the `rxjs: 5.0.0-rc.4` locally, and it's safe to be updated. But the latest `zone.js: 0.7.1` failed a test case. I don't know the context knowledge about that test case. Can't help.

**Comment by WilliamKoza** [comment]
see PR #13022 Vs Issue #13031

**Comment by e-cloud** [comment]
@WilliamKoza that solves part of the issue

**Comment by DzmitryShylovich** [comment]
@e-cloud deps were updated. can this be closed?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed
