### ISSUE TITLE
Hybrid apps using both routers can instantiate components twice, breaking change detection.

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#13060]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When:
- bootstrapping a hybrid ng1/ng2 app that uses both routers
- routing to ng2 components with selectors that have been downgraded to ng1 with the same selector
- navigating to one such component

The component is instantiated twice, which leads to constructor logic being ran twice, and also seems to break change detection in async `ngIf` conditions upon further (non-reload) navigation.

**Expected behavior**
Components should not be instantiated twice, nor should change detection stop working.

**Minimal reproduction of the problem with instructions**
```
git clone https://github.com/filipesilva/hybrid-router-bug
cd hybrid-router-bug
npm install
npm start
```
1 - browser opens page, also open browser console
2 - notice `foo constructor called` twice in console
3 - click `async ngIf link to baz` (`routerLink` inside `ngIf`, changed via `setTimeout`)
4 - notice page only shows `baz component`, but console also says `async content loaded`
5 - click anywhere on the page, `async content loaded` will show up (message inside `ngIf`, changed via `setTimeout`)
6 - click the `bar` link at the top
7 - notice `bar component, id: 1` in the page, and `bar constructor called` and `id: 1` in the console
8 - refresh the page
9 - notice the page now says `bar component, id:`, and the console shows the constructor being called twice with `id: undefined` the second time.

In step 4/5, change detection needed to be triggered via a click on the page to detect that the message had changed.

In step 9, the instantiated component doesn't show the correct content.

Both these cases seem to be triggered by a component being instantiated twice, hence double constructor calls, when bootstrapping the application.

**What is the motivation / use case for changing the behavior?**
Components should not be instantiated twice, nor should change detection stop working.

**Please tell us about your environment:**
Windows 10, VSCode, npm, lite-server, Angular 2 quickstart

* **Angular version:** 2.2.2

* **Browser:** [ Chrome 54 ]
 
* **Language:** [ TypeScript 2.0.10 ]

/cc @petebacondarwin @vsavkin @wardbell @naomiblack

**Comment by filipesilva** [comment]
It is possible to work around this issue by deferring initial navigation until after Angular 1 is bootstrapped.
- in `app/app-routing.module.ts` change line 24 to 
```
imports: [ RouterModule.forRoot(routes, {initialNavigation: false}) ],
```
- in `app/main.ts` manually initialise navigation:
```
platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
  const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
  upgrade.bootstrap(document.documentElement, ['ng1app']);
  platformRef.injector.get(Router).initialNavigation();
});
```

**Comment by petebacondarwin** [comment]
Just to be clear on the problem here: the Angular 2 router is doing its initial navigation before the Angular 1 module has been bootstrapped which has the following repercussions:

* upgraded Angular 1 services are not available during this initial route navigation
* components that are created by the Angular 2 router may then get "re-compiled" during Angular 1 bootstrap.

**Comment by filipesilva** [comment]
I tried deferring the navigation in a slightly more complicated repro and it actually causes another problem in which the router URL seems bouncing/flickering back every time the url changes.

Repro steps:
```
git clone https://github.com/filipesilva/hybrid-router-bug-phonecat
cd hybrid-router-bug-phonecat
npm install
npm start
```
1 - click `Motorola XOOM™ with Wi-Fi`
2 - notice the routed page is blank
3 - click anywhere in the page, triggering change detection
4 - component contents now appear
5 - in app/app-routing.module.ts change line 26 to:
```
imports: [ RouterModule.forRoot(routes, {initialNavigation: false}) ],
```
6 - in app/main.ts manually initialise navigation:
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { UpgradeModule } from '@angular/upgrade/static';
import { Router } from '@angular/router';

import { AppModule } from './app.module';

platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
  const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
  upgrade.bootstrap(document.documentElement, ['phonecatApp']);
  platformRef.injector.get(Router).initialNavigation();
});
```
7 - reload page at root
8 - notice the url flickers from `http://localhost:3000/` to `http://localhost:3002/app/#!/phones` and back
9 - notice the phone list doesn't appear until you click somewhere in the page
10 - click `Motorola XOOM™ with Wi-Fi`, notice url flicker again

At the moment the only solution I found is to remove the Angular 2 component selectors, and thus not have both an Angular 1 and Angular 2 component with the same name.

**Comment by yanisIk** [comment]
Any news about this issue ? It is still happening in 2.4.7

**Comment by petebacondarwin** [comment]
I am told that we have a working example of using both routers: https://github.com/angular/angular.io/tree/master/public/docs/_examples/upgrade-phonecat-3-router/ts
But I haven't checked to see if there are still these issues.  It is something I will take a look at this week or next I think.

**Comment by jcperez-ch** [comment]
I faced exactly same problematic trying both routers.  The only solution I found was to remove 100% in angular pages the dependency to angularJS (no injectables and no directives).  This slowed the upgrading process, but at least we are in a stable stage.

I am using: 
- `@angular/*@4.0.2`
- `angular@1.5.11`
- `angular-ui-router@0.4.2`

**Comment by nasreddineskandrani** [comment]
For those who are still dealing with hybrid port of app. Or plan to do a move to angular2+.

I suggest to consider moving your app directly to a full angular2+ router solution.
Based on this example repo: https://github.com/aminpaks/angular-hybrid

This was done in a week our side... which you the best

note: $location injection was causing problem so make sure  (to remove any other angular1 router service injection in your code even if not used).

**Comment by jasonaden** [comment]
Cleaning up this issue as it's been sitting for a while.

There isn't a plan to specifically fix this problem. The best thing to do right now is as per @jcperez-ch or @nasreddineskandrani 's suggestions. Either do a full upgrade to Angular Router, or, if that's not an option, upgrade all components under a given route.

The hybrid approach may work for some applications to a limited extent, but it doesn't work well in all cases and can lead to odd and unexpected behaviors.

We are working on a new approach to upgrade through the router and are targeting `v7` for the release of this feature (called the Unified Router). Until that time I would suggest the above recommendations.

Closing this issue as "Won't Fix".
