### ISSUE TITLE
Route by this.router.navigate not work in child module

### ISSUE THREAD

**Issue by BtShp** [angular/angular#13073]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 
```

**Current behavior**
Im using child module with child router,. In this child router I have few "parent routings" that view by app component <router-outlet> ,
And within them I have Child routings that view by <router-outlet> of their parents components.
Im trying to navigate between the "parent routings", from one to other. 
when I do this by the HTML attribute  "router-link='/wow'" 
it works well. when I try to do the same by code like "this.router.navigate(['/wow'])" the router route to correct page to a second, and "jump" immidiatly to the home page.
I need to navigate by code becose i want to send dinamic parameters to dynamic urls. 
**Expected behavior**
can navigate also by code , alsoneeded some log of navigation....

**Minimal reproduction of the problem with instructions**
1. Create app module with root router.
2. Create child module imports by app module
3. In child module create child router.
4. In child router create few routings for the root , with childs routings.
5. In root router components that  declared by child module: 
 try to navigate by code from one root compnonet to other root component .

link of example to what i try to do: (not the real source because i cant...)
https://plnkr.co/edit/yZij0SvDLD2A6ggKBCKO

**What is the motivation / use case for changing the behavior?**
I need to navigate by code becose i want to send dinamic parameters to dynamic urls. 

**Please tell us about your environment:**
angular2 with kendo ui   "@angular/router": "~3.1.1", node js  6.9.1, typescript  2.1 

* **Angular version:** 2.0.X
 "@angular/router": "~3.1.1"

* **Browser:** [ Chrome XX | 
 
* **Language:**  TypeScript 2.0.3 | ES6/7 
* **Node (for AoT issues):** `node --version` =    6.9.1

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr

**Comment by DzmitryShylovich** [comment]
It doesn't load.

**Comment by BtShp** [comment]
But you can understand details? I dont have time now to handle this :(  :... just want to show what im doing

**Comment by vicb** [comment]
Please explain the steps to see the issue with your plunker (expected vs observed)

**Comment by DzmitryShylovich** [comment]
@BtShp did u solve it?

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
