### ISSUE TITLE
Cannot use types from ambient modules in AoT compiled providers

### ISSUE THREAD

**Issue by mprobst** [angular/angular#13072]
Assume you have ambient TypeScript declarations, e.g. like this:

```ts
declare module 'some/module' {
  export class AmbientClass {}
}
```

You cannot use the type declared in the ambient module as a provider:

```ts
import {AmbientClass} from 'some/module';

@NgModule({
  // Error: Unable to resolve some/module from mymodule.ts, resolving symbol ...
  providers: [{provide: AmbientClass, useFactory: ...}],  // fails
})
class MyModule {}
```

**Comment by mprobst** [comment]
A workaround is to have a TypeScript file that re-exports the ambient type. It must be in a separate file from the `{provide: ...}` reference:

```ts
export {AmbientClass} from 'some/module';
```

And update the `provide` reference to use this re-export.

**Comment by sclausen** [comment]
That worked for me too. But this seems totally unintelligible. Why does aot behaves like that? It's not the first time it creates problems.

**Comment by JoostK** [comment]
This is no longer an issue in Ivy.
