### ISSUE TITLE
Router - route with multiple required params and optional between them, causes router not to extract and track the optional params.

### ISSUE THREAD

**Issue by kmolerov** [angular/angular#13079]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If you have route configuration like:  {
  path: 'myPath/:id1/:id2',
  component: MyComponent,
}

and we navigate with optional parameter (with matrix notation):
this.router.navigate(['/myPath', 1, { optionalParam: 'foo' }, 2);

then:
this.route.params.subscribe(params =>{
params only contain:  { id1: 1, id2: 2}
and does not contain 'optionalParam' property
});

**Expected behavior**

this.route.params.subscribe(params =>{
 params should be { id1: 1, id2: 2, optionalParam: 'foo'
}
});

If this is required behavior, please document it, but in my case it is semantically correct to have the optional parameter between them.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I have a parent route with two id parameters and multiple child routes and child routes are subscribing to changes in parent params. When parent state changes, its Id param does not change, so I need to add optional parameter "version" so I can track the changes and could refresh the child routes.

**Please tell us about your environment:**

Win 8.1, VSCode, npm, lightserver

* **Angular version:** 2.0.X

2.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 54,  

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
pls add a repro in plunkr

**Comment by vicb** [comment]
This is by design - we only consider the matrix params for the last segment.
