### ISSUE TITLE
Sibling component interaction, 2nd component's UI is not changing on fetching flag from other.

### ISSUE THREAD

**Issue by sachin0110** [angular/angular#13078]
Sibling component interaction & sending flag when one finishes its data fetching, other to display the data whatever the other component has fetched & this is asynchronous calling (PS: I have 2 web api calls in first component, on success of first, I am redirecting to other component, & binding data to that component of both API's)

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Sibling component interaction & sending flag when one finishes its data fetching, other to display the data whatever the other component has fetched & this is asynchronous calling (PS: I have 2 web api calls in first component, on success of first, I am redirecting to other component, & binding data to that component of both API's)

**Expected behavior**

Since angular 2 supports 2 way data binding, it should reflect the data on second component.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7, Viisual studio code, IIS

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] Typescript

* **Node (for AoT issues):** `node --version` =    3.8.9

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by robwormald** [comment]
Without a reproduction, this is impossible for us to troubleshoot. Additionally, it sounds like a how-to question rather than an issue with the framework. 

Please take how-to questions to https://gitter.im/angular/angular - and I suggest you provide a plunker there - here's a starter: https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
