### ISSUE TITLE
CanDeactivate breaks route navigation

### ISSUE THREAD

**Issue by Fatslug** [angular/angular#13071]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Go to a new route from a current route which uses a CanDeactivate. The CanDeactovate returns false, the route does not change. This is good.
But when we try to navigate to that route again, no navigation events are fired.
The router.navigate function is called from the code, and the promise is returned, but no navigation events are fired (NavigationStart, End, etc). Because of this, the CanDeactivate condition is never re-evaluated.

**Expected behavior**
The navigation events should be fired, CanDeactivate should be re-evaluated, and shit should work.

**Minimal reproduction of the problem with instructions**
Issue is outlined here:
http://stackoverflow.com/questions/40754847/navigating-to-the-same-route-cancelled-by-the-candeactivate-guard-is-failing/40776664#40776664

Plunkr can be found here:
http://plnkr.co/edit/w1NCkGs0Tv5TjivYMdvt?p=preview

**What is the motivation / use case for changing the behavior?**
huh?

**Please tell us about your environment:**
Angular 2.0 version 2.2.0
Issue is specific to @angular/router version 3.2.0 and above

* **Angular version:** 2.2.0

* **Browser:** all
 
* **Language:** TypeScript 2.0.2

* **Node (for AoT issues):** `node --version` =   6.6.0

**Comment by ericmartinezr** [comment]
Can you see if your issue is the same as this one https://github.com/angular/angular/issues/12851 ?

**Comment by Fatslug** [comment]
Yes it's the same issue. Thought that one was closed though

**Comment by ipassynk** [comment]
#12851 is closed but with angular 2.2.0 and router 3.2.0 i see following problem:

- router navigate is called
- deactivate guard returns false
- user fixed the data so the guard can return true
- router navigate is called again
--- BUT this time guard is NOT called, router navigation is not finished and NO exception on a console.

**Comment by ericmartinezr** [comment]
It's not closed (it was), it was reopened, just in case. You can see at the top of the issue that it says "open". I would choose the other issue since there are already a few comments explaining what's wrong, see https://github.com/angular/angular/issues/12851#issuecomment-262071793 and https://github.com/angular/angular/issues/12851#issuecomment-262520855

**Comment by vsavkin** [comment]
Closing this. Dup of 12851.
