### ISSUE TITLE
Runtime error 'Error: Permission denied to access property "rejection" ' is mis-handled

### ISSUE THREAD

**Issue by realtebo** [angular/angular#13084]
I don't know what is the source of the error it self, but I see this error in the console

> Error: Permission denied to access property "rejection"

opening `main.bundle.js` I found that the following function is causing the error.

```
function consoleError(e) {

        var rejection = e &&; e.rejection;
        if (rejection) {
            console.error('Unhandled Promise rejection:', rejection instanceof Error ? rejection.message : rejection, '; Zone:', e.zone.name, '; Task:', e.task && e.task.source, '; Value:', rejection, rejection instanceof Error ? rejection.stack : undefined);
        }
        console.error(e);
}
```

The row 

```
        var rejection = e &&; e.rejection;
```

Is casuing a runtime error. So I, as developer, need to understand what e is, but I cannot because this utility function is causing an error itself instead of simply logging me the source error!

Sorry but I've no idea of WHAT piece of angular of what node js module is the parent of this snippet of code

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by realtebo** [comment]
@DzmitryShylovich I understand, but I'm a newbie with ng2, so I ask you help to understand where is the source code. So I can open an Issue (and do a patch and a PR) to the right github repo/developer

**Comment by realtebo** [comment]
Ok, I now can understand that this is related to zone.js, I close this issue and open is the right repo

**Comment by realtebo** [comment]
See: Isse on https://github.com/angular/zone.js/issues/519
