### ISSUE TITLE
build/analyze.dart task is missing contents lib/web directory

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#1308]
See the delta here: https://github.com/kevmoo/angular/commit/3566395163e7657ff93f01ccca8d233bbcf1a3cf?diff=unified

There are a lot of analyzer warnings and hints that are being missed.

CC @kegluneq

**Comment by mhevery** [comment]
Can you create a PR?

**Comment by kevmoo** [comment]
This has all been fixed.
