### ISSUE TITLE
feat: export ContentType from @angular/http

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#13086]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`ContentType` is not exported from `@angular/http`. Though, `Request.detectContentTypeFromBody()` which is public returns a value of the type `ContentType`.

**Expected behavior**

I should be able to use `ContentType` by importing from `@angular/http`.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by kopa** [comment]
@DzmitryShylovich Why wasn't the PR merged?

**Comment by textbook** [comment]
This caused us issues when upgrading our app to 4.x, as we'd been using a deep import to get the `ContentType` enum but that's no longer supported. We've had to put

```
const FORM_DATA_CONTENT_TYPE = 3;
```

in our tests instead, which is a bit awkward! It seems weird that only one of the five enums isn't part of the public API, especially as it's used as a public method return type.

**Comment by alxhub** [comment]
Closing as obsolete (`@angular/common/http` superseded `@angular/http`).
