### ISSUE TITLE
Provider.useFactory called multiple times

### ISSUE THREAD

**Issue by httpdigest** [angular/angular#13085]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When upgrading from Angular 2.1.2 to the current 2.2.3, the semantics of an NgModule provider changed, when it was using the useFactory property. In 2.1.2, the factory method was only called once and effectively gave a singleton to each injection point within the NgModule. Now, it is being called multiple times for each injection point.
Is this expected?

**Expected behavior**
The Provider.useFactory is only called one time per NgModule and all injection points in components it is injected into.

**Please tell us about your environment:**
OS: Windows 7 x64
IDE: IntelliJ IDEA Ultimate 2016.3
Package Manager: npm 4.0.2
TypeScript: 2.0.10

* **Angular version:** 2.2.3

* **Browser:** Chrome 54.0.2840.99 m (64-bit)
 
* **Language:** TypeScript 2.0.10 ES2015

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr

**Comment by httpdigest** [comment]
Yes, I will do. It's a rather very big application. Digging deeper into the issue, it looks that the whole NgModule is being created multiple times. Probably has something to do with routing. I'm checking.

**Comment by httpdigest** [comment]
Closing this for now, since it seems the issue is elsewhere.

**Comment by httpdigest** [comment]
It looks like I was bitten by https://github.com/angular/angular/issues/12889 and https://github.com/angular/angular/issues/12869 when upgrading to Angular 2.2.3 and Router 3.2.3
