### ISSUE TITLE
Anuglar 2 ZoneDelegate Prototype Error

### ISSUE THREAD

**Issue by aqeel-legalinc** [angular/angular#13088]
I am trying to configure the Angular2 Code on my local machine, I am getting following error for that. 

    Error: ZoneDelegate.prototype.invoke@http://legalincforms.local:81/themes/legalinc/node_modules/zone.js/dist/zone.js:232:17
    	Zone.prototype.run@http://legalincforms.local:81/themes/legalinc/node_modules/zone.js/dist/zone.js:114:24
    	scheduleResolveOrReject/<@http://legalincforms.local:81/themes/legalinc/node_modules/zone.js/dist/zone.js:502:52
    	ZoneDelegate.prototype.invokeTask@http://legalincforms.local:81/themes/legalinc/node_modules/zone.js/dist/zone.js:265:21
    	Zone.prototype.runTask@http://legalincforms.local:81/themes/legalinc/node_modules/zone.js/dist/zone.js:154:28
    	drainMicroTaskQueue@http://legalincforms.local:81/themes/legalinc/node_modules/zone.js/dist/zone.js:401:25
    	ZoneTask/this.invoke@http://legalincforms.local:81/themes/legalinc/node_modules/zone.js/dist/zone.js:339:25
    	
    	Evaluating http://legalincforms.local:81/themes/legalinc/assets/javascript/app/main.js
    	Error loading http://legalincforms.local:81/themes/legalinc/assets/javascript/app/main.js

I have reinstall/update all the dependencies like NPM and Node. 
Using NPM version "3.10.3"
Node 6.6.0

Here is my Package.Json file. This code is running on some other machines but on my machine specifically. 

    {
      "name": "ABC APP",
      "version": "1.0.0",
      "scripts": {
        "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
        "lite": "lite-server",
        "postinstall": "typings install",
        "tsc": "tsc",
        "tsc:w": "tsc -w",
        "typings": "typings"
      },
      "license": "ISC",
      "dependencies": {
        "@angular/common": "2.0.0-rc.4",
        "@angular/compiler": "2.0.0-rc.4",
        "@angular/core": "2.0.0-rc.4",
        "@angular/forms": "0.2.0",
        "@angular/http": "2.0.0-rc.4",
        "@angular/platform-browser": "2.0.0-rc.4",
        "@angular/platform-browser-dynamic": "2.0.0-rc.4",
        "@angular/router": "3.0.0-beta.1",
        "@angular/router-deprecated": "2.0.0-rc.2",
        "@angular/upgrade": "2.0.0-rc.4",
        "angular2-fontawesome": "^0.1.0",
        "angular2-in-memory-web-api": "0.0.14",
        "angular2-json2csv": "^1.0.2",
        "awesome-bootstrap-checkbox": "^1.0.0-alpha.4",
        "bootstrap": "^3.3.6",
        "core-js": "^2.4.0",
        "ng2-bootstrap": "1.0.17",
        "ng2-bs3-modal": "^0.6.1",
        "ng2-table": "1.0.2",
        "reflect-metadata": "^0.1.3",
        "rxjs": "5.0.0-beta.6",
        "systemjs": "0.19.27",
        "zone.js": "^0.6.12"
      },
      "devDependencies": {
        "@types/core-js": "^0.9.34",
        "concurrently": "^2.0.0",
        "gulp": "^3.9.1",
        "gulp-replace": "~0.5.4",
        "lite-server": "^2.2.0",
        "typescript": "^1.8.10",
        "typings": "^1.0.4"
      }
    }

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr

**Comment by aqeel-legalinc** [comment]
@DzmitryShylovich I guess plunkr is for start a new repo. its already a built project in Angular2. I cant add all of my files there.

**Comment by DzmitryShylovich** [comment]
Sorry, but you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by DzmitryShylovich** [comment]
@aqeel-legalinc did u solve your issue?

**Comment by aqeel-legalinc** [comment]
@DzmitryShylovich Yeah this got fixed.

**Comment by aqeel-legalinc** [comment]
@DzmitryShylovich Actually there was an issue with my Browser version.

**Comment by rjvarona** [comment]
did you update your browser version?????
