### ISSUE TITLE
NGC doesn't compile when default template imports used

### ISSUE THREAD

**Issue by barbatus** [angular/angular#13097]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`ngc` fails to compile component that imports a default template from another module.
Here is an [example](https://github.com/barbatus/ngc-issue/blob/master/client/app.component.ts#L5).
It throws an exception `can't find symbol undefined exported from module template.ts`.
At the same time It works fine when `template` const is not default export.

Stacktrace shows that the exception is raised in StaticReflector  https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/aot/static_reflector.ts

**Expected behavior**

**Minimal reproduction of the problem with instructions**
Run `node_modules/.bin/ngc` on https://github.com/barbatus/ngc-issue.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Metadata should be statically analyzable.

**Comment by barbatus** [comment]
@DzmitryShylovich it works for me when `const template = '<div></div>'` or `import {template} from './template'`. Also all metadata in typescript is statically analyzable.

**Comment by DzmitryShylovich** [comment]
Nvm sorry. It's past midnight already :)

It's a known issue with default imports https://github.com/angular/angular/issues/11402
Should be fixed soon

**Comment by barbatus** [comment]
ok, thx. closed as duplicate.
