### ISSUE TITLE
routerLinkActiveOptions doesn't exactly match with matrix url notation parameters

### ISSUE THREAD

**Issue by CamusAran** [angular/angular#13093]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Setting routerLinkActiveOptions to { exact: true } doesn't match matrix url notation parameters exactly. All three of these routerLinks are active at all three routes:
```
<a [routerLink]="['/feature', {all: true}]" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }"></a>
```
```
<a routerLink="/feature" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }"></a>
```
```
<a [routerLink]="['/feature', {group: group.id}]" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }"></a>
```

**Expected behavior**

Only one route should be active at each route.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/JYB9wXgMEsHwvRSyZyb1?p=preview
Click any of the links, they all get a green background (active).

* **Angular version:** 2.0.X

2.1.0 and whatever version the recommended plunker template uses.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Firefox 50
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 2.0.2

**Comment by vsavkin** [comment]
There are many ways to define "subset" for URLs. We chose to ignore matrix params, that's why it works like that. We should implement the following feature https://github.com/angular/angular/issues/13205.
