### ISSUE TITLE
routerLinkActive with [queryParams] is broken (worked in v2.0.2)

### ISSUE THREAD

**Issue by farin99** [angular/angular#13098]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
routerLinkActive of a child route with queryParams is not working when reloading the page with the params (it is working if you click the link). The 'a' element doesn't receive the class provided to the routerLinkActive when the route match.
This worked in version 2.0.2 and was broken between that version and version 2.2.1.

**Expected behavior**
When the route match, the 'a' element will receive the class provided to routerLinkActive.

**Minimal reproduction of the problem with instructions**
<a class="item" [routerLink]="['/insights']" [queryParams]="{id: myid}"
             routerLinkActive="tab-active" [routerLinkActiveOptions]="{exact: true}">
            Link
</a>

the following route will not match the routerLinkActive
http://localhost:4200/#/insights?id=aa

**Please tell us about your environment:**
Tested in chrome only mac os sierra

* **Angular version:** 2.0.X
I first spotted the issue in angular 2.2.1 (worked in older version - "2.0.2"). also broken on latest 2.2.3

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr

**Comment by farin99** [comment]
Seems to be because I'm navigating using code (router.navigate) and trying to change the queryParam dynamically 
<a ... [queryParams]="{id: myId}" ....>
to repreduce click the "Navigate query param 3" button in the plunkr:
http://plnkr.co/edit/Oy1u6G1Tie3cCpSRALRm?p=preview

I might be doing something wrong, however this approach worked in older versions (2.0.2)
Any way to tell routerLinkActive to ignore the queryParams?

**Comment by DzmitryShylovich** [comment]
I guess it was introduced here https://github.com/angular/angular/pull/12321

> Any way to tell routerLinkActive to ignore the queryParams?

nope

**Comment by vicb** [comment]
We will consider adding a `ignoreQueryParams` to the directive.

**Comment by DzmitryShylovich** [comment]
I don't think it will help. There's a state sync issue between 2 directives: `routerLink` and `routerLinkActive`. 

Example form https://github.com/angular/angular/issues/13075: http://prntscr.com/de91ic 
Hero object is loaded async this is why during component rendering `hero.id` is undefined. `hero/1`
 is not equal to `hero/undefined` and `routerLInkActive` evaluates to `false` which is ok. Then, when hero finally arrives from subscription, `hero.id` become 1 instead of undefined, but it's too late, active status has already been calculated (to fix it we need to manually trigger RouterLinkActive.update() somehow).

I think we should drop `routerLinkActive` and just use `routerLink`. `routerLink` can calculate active status itself and bind active class to its host element. Benefits:
1. We don't need to sync status between 2 directives.
2. It will be more efficient because we can implement some smart caching mechanism and not recalculate status during every change detection cycle. 
3. It will also simplify implementation of https://github.com/angular/angular/issues/9426

**Comment by zoechi** [comment]
related to #13205

**Comment by sandangel** [comment]
@rodmax you should not call isActiveFlagsByLink.get(link) in the template because it will be called everytime CD run.

my idea is creating a directive like this:

```ts
import {
  AfterContentInit,
  ContentChildren,
  Directive,
  ElementRef,
  Input,
  NgModule,
  OnChanges,
  OnDestroy,
  QueryList,
  Renderer2
} from '@angular/core';
import { NavigationEnd, Router, RouterLink, RouterLinkWithHref } from '@angular/router';
import { untilDestroy } from '../operators';

export interface MatchExp {
  [classes: string]: string;
}

/**
 * TODO: Add docs
 */
@Directive({
  selector: '[routerLinkMatch]'
})
export class RouterLinkMatch implements OnDestroy, OnChanges, AfterContentInit {
  private _curRoute: string;
  private _matchExp: MatchExp;

  @ContentChildren(RouterLink, { descendants: true })
  links: QueryList<RouterLink>;

  @ContentChildren(RouterLinkWithHref, { descendants: true })
  linksWithHrefs: QueryList<RouterLinkWithHref>;

  @Input('routerLinkMatch')
  set routerLinkMatch(matchExp: MatchExp) {
    if (matchExp && typeof matchExp === 'object') {
      this._matchExp = matchExp;
    } else {
      throw new TypeError(
        `Unexpected type '${typeof matchExp}' of value for ` +
          `input of routerLinkMatch directive, expected 'object'`
      );
    }
  }

  constructor(private router: Router, private _renderer: Renderer2, private _ngEl: ElementRef) {
    router.events.pipe(untilDestroy(this)).subscribe(e => {
      if (e instanceof NavigationEnd) {
        this._curRoute = (e as NavigationEnd).urlAfterRedirects;
        this._update();
      }
    });
  }

  ngOnChanges() {
    this._update();
  }

  ngAfterContentInit() {
    this.links.changes.pipe(untilDestroy(this)).subscribe(() => this._update());
    this.linksWithHrefs.changes.pipe(untilDestroy(this)).subscribe(() => this._update());
    this._update();
  }

  private _update(): void {
    if (!this.links || !this.linksWithHrefs || !this.router.navigated) {
      return;
    }

    /**
     * This a way of causing something to happen in the next micro-task / during a new round
     * of change detection.
     */
    Promise.resolve().then(() => {
      const matchExp = this._matchExp;

      Object.keys(matchExp).forEach(classes => {
        if (matchExp[classes] && typeof matchExp[classes] === 'string') {
          const regexp = new RegExp(matchExp[classes]);
          if (this._curRoute.match(regexp)) {
            this._toggleClass(classes, true);
          } else {
            this._toggleClass(classes, false);
          }
        } else {
          throw new TypeError(
            `Could not convert match value to Regular Expression. ` +
              `Unexpected type '${typeof matchExp[classes]}' for value of key '${classes}' ` +
              `in routerLinkMatch directive match expression, expected 'non-empty string'`
          );
        }
      });
    });
  }

  private _toggleClass(classes: string, enabled: boolean): void {
    classes
      .split(/\s+/g)
      .filter(cls => !!cls)
      .forEach(cls => {
        if (enabled) {
          this._renderer.addClass(this._ngEl.nativeElement, cls);
        } else {
          this._renderer.removeClass(this._ngEl.nativeElement, cls);
        }
      });
  }

  ngOnDestroy() {}
}
```

then use same as ngClass directive. This directive will add css class to any route that matches given regexp

<a [routerLinkMatch]="{'class': 'regular-exp-as-string'}">Link</a>

**Comment by bes1002t** [comment]
any progress?

**Comment by jared-christensen** [comment]
To vote do we thumbs up the angular bot or the first post?

**Comment by atscott** [comment]
This is available through the `routerLinkActiveOptions`: https://angular.io/api/router/IsActiveMatchOptions
