### ISSUE TITLE
how to pass data one component to another using router in angular 2

### ISSUE THREAD

**Issue by Vips120** [angular/angular#13100]

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Vips120** [comment]
i ddint get on stackoverflow

**Comment by zoechi** [comment]
https://angular.io/docs/ts/latest/cookbook/component-communication.html
