### ISSUE TITLE
Chrome workspace with Angular 2 component styling ?

### ISSUE THREAD

**Issue by rotemx** [angular/angular#13109]
**I'm submitting a ...** 
[X] feature request

**Current behavior**
When using styles or styleUrls arrays on @Component decorators to include CSS files, the styling rules are inlined inside a Shadow Dom root:

<img width="214" alt="angular" src="https://cloud.githubusercontent.com/assets/6062662/20653034/aec0a88c-b50e-11e6-917c-ff65dc464469.PNG">

As a web designer I find it extremely efficient to use Chrome workspaces to make permanent changes to CSS files served locally.

Most of the times I'm not sure about the right style, so I check it on Chrome's dev tools, and instead of coping it manually to the code, the fastest way to save it would be with the workspaces feature. 

As far as I know this is not possible right now with Angular 2 (or is it ?!)

**Expected behavior**
I would have the inline styling inside the DOM source-mapped to the local CSS files, so after enabling Google Chrome workspace (i.e. adding the local folder + mapping the resources) I would be able to edit the local CSS files from the browser dev tools.

**What is the motivation / use case for changing the behavior?**
The ability to edit CSS files directly from the browser dev tools AND take advantage of isolated Shadow Dom components in Angular 2.

* **Browser:** Chrome 52

* **Language:** all

**Comment by IgorMinar** [comment]
hmm.. I think there are several things at play here. the prerequisite for this feature to work is for the css source maps to be generated correctly by the angular compiler and for the source maps to be passed through correctly by the angular cli.
