### ISSUE TITLE
Setter @Input binding not working after upgrading to 2.2.3 from 2.1.2

### ISSUE THREAD

**Issue by michalboska** [angular/angular#13108]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In a component class

```
import { Component, EventEmitter, Input, Output, OnInit } from '@angular/core';

@Component({
	selector: 'navigation-sections',
	template: require('./navigation-sections.template.html'),
	styles: [
		require('./navigation-sections.style.scss')
	]
})

export class NavigationSectionsComponent implements OnInit {
	@Input() sections:Array<string>;
	private _selectedSection: number;
	@Output() onSelectSection = new EventEmitter<number>();

	constructor () {}

	ngOnInit(): void {
		if (!this._selectedSection) {
			this._selectedSection = 0;
		}
	}

	get selectedSection():number{
		return this._selectedSection;
	}

	@Input("selectedSection")
	set selectedSection(value:number){
		console.log("Setter called");
        this._selectedSection=value;
	}

	selectNavigationSection(value:number,event): void{
		if (event.currentTarget.classList.contains('complete')) {
		 	this.onSelectSection.emit(value);
		 	this._selectedSection = value;
		 }
	}
}

```

after using the component like this:

```
<navigation-sections [sections]="sections"
							 [selectedSection]="selectedSection"
							 (onSelectSection)="onSelectSection($event)">
		</navigation-sections>
```
following error is thrown:

```
error_handler.js:48 EXCEPTION: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'selectedSection' since it isn't a known property of 'navigation-sections'.
1. If 'navigation-sections' is an Angular component and it has 'selectedSection' input, then verify that it is part of this module.
2. If 'navigation-sections' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
	<div class="col-xs-12">
		<navigation-sections [sections]="sections"
							 [ERROR ->][selectedSection]="selectedSection"
							 (onSelectSection)="onSelectSection($event)">
		</naviga"): GlobalHomeTherapiesComponent@3:8
```

If i use the `@Input` annotation directly on the property (the component class looks as follows), then there is no error and property is bound successfully:

```
import { Component, EventEmitter, Input, Output, OnInit } from '@angular/core';

@Component({
	selector: 'navigation-sections',
	template: require('./navigation-sections.template.html'),
	styles: [
		require('./navigation-sections.style.scss')
	]
})

export class NavigationSectionsComponent implements OnInit {
	@Input() sections:Array<string>;
	private _selectedSection: number;
	@Input()
	private selectedSection:number = 0;
	@Output() onSelectSection = new EventEmitter<number>();

	constructor () {}

	ngOnInit(): void {
		if (!this._selectedSection) {
			this._selectedSection = 0;
		}
	}

	selectNavigationSection(value:number,event): void{
		if (event.currentTarget.classList.contains('complete')) {
		 	this.onSelectSection.emit(value);
		 	this._selectedSection = value;
		 }
	}
}

```

**Expected behavior**
Setter `@Input` binding should work as per https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#parent-to-child-setter

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/icPStVKWyT4cNSHxYvU3?p=preview

**Please tell us about your environment:**
* **OS**: Win10
* **Package manager** yarn, npm

* **Angular version:** 2.2.3

* **Browser:** all
* **Language:** TypeScript 2.1.1

* **Node (for AoT issues):** `node --version` =  4.4.2

**Comment by zoechi** [comment]
Can you please fix the selector of the custom-component?

**Comment by DzmitryShylovich** [comment]
also `Input` should be on the first propery occurance
```
@Input()
get selectedSection():number{
  return this._selectedSection;
}
    
set selectedSection(value:number){
  console.log("Setter called");
   this._selectedSection=value;
}
```

**Comment by zoechi** [comment]
@DzmitryShylovich interesting. I found that removing the getter also fixed it but I hadn't expect `@Input()` on a getter to work :D

**Comment by DzmitryShylovich** [comment]
@zoechi decorators just attach metadata to a property with the given name so it doesn't really matter setter or getter

**Comment by michalboska** [comment]
Fixed selector in Plunker. 
After placing setter before the getter, the code works (also in the original project).

However, the old code worked until upgrade from Angular 2.1.2 to 2.2.3 - is it possible something could have changed between those versions that started to require `@Input` being declared on the first occurence rather than any occurence?

In any case, i suggest changing the cookbook page https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#parent-to-child-setter because IMHO the way it is described there, suggest the annotation needs to be on the setter.

**Comment by zoechi** [comment]
Can you please open an issue in https://github.com/angular/angular.io for the cookbook?

**Comment by DzmitryShylovich** [comment]
> the old code worked until upgrade from Angular 2.1.2 to 2.2.3 

can u reproduce with an older version? might be a regression

**Comment by michalboska** [comment]
In 2.1.2 the error cannot be reproduced, the code works even if you place the annotated setter **after** the unannotated getter

**Comment by DzmitryShylovich** [comment]
> the code works even if you place the annotated setter after the unannotated getter

then update the title, description and attach repro pls. thx

**Comment by michalboska** [comment]
Can't get 2.1.2 to work in Plunker. 
My config.js

```
System.config({
  //use typescript for compilation
  transpiler: 'typescript',
  //typescript compiler options
  typescriptOptions: {
    emitDecoratorMetadata: true
  },
  paths: {
    'npm:': 'https://unpkg.com/'
  },
  //map tells the System loader where to look for things
  map: {
    
    'app': './src',
    
    '@angular/core': 'npm:@angular@2.1.2/core/bundles/core.umd.js',
    '@angular/common': 'npm:@angular@2.1.2/common/bundles/common.umd.js',
    '@angular/compiler': 'npm:@angular@2.1.2/compiler/bundles/compiler.umd.js',
    '@angular/platform-browser': 'npm:@angular@2.1.2/platform-browser/bundles/platform-browser.umd.js',
    '@angular/http': 'npm:@angular@2.1.2/http/bundles/http.umd.js',
    '@angular/router': 'npm:@angular@2.1.2/router/bundles/router.umd.js',
    '@angular/forms': 'npm:@angular@2.1.2/forms/bundles/forms.umd.js',
    
  
    'rxjs': 'npm:rxjs',
    'typescript': 'npm:typescript@2.1.1/lib/typescript.js'
  },
  //packages defines our app package
  packages: {
    app: {
      main: './main.ts',
      defaultExtension: 'ts'
    },
    rxjs: {
      defaultExtension: 'js'
    }
  }
});
```

but it seems those files are not on unpkg (i get 403 Forbidden)

**Comment by wardbell** [comment]
I don't think this has anything to do with Angular. I think it has to do with the fact that your using TypeScript 2.1.x which in PRE-RELEASE.  There appears to be a regression in THAT.  Not surprising since they appear to be doing a lot of work on getters/setters.

When you switch to the **latest current release (as I write this on Nov 29, 2016), TS 2.0.10**, the original code works!

I stripped your plunker example down to more closely reveal the problem. [Here is mine](http://plnkr.co/edit/dT3oGGXTj84aCnxWVwpC?p=info).  Follow the README.

To see that changing the TypeScript version controls the outcome,
open `config.js` and toggle the TypeScript version to 2.0.10 to see that the code works fine when the decorator is on the second property method.

I'm treating this as a **TypeScript bug**, not an Angular or Angular Documentation error.

**Comment by michalboska** [comment]
You're right, i haven't noticed that 2.1.x is still not stable (it is published in npm and i normally downloaded without actually enabling any "pre-release" options). 
Thanks for creating the issue with Typescript
