### ISSUE TITLE
ContentChild(TemplateRef) descendants not working on init phase

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#13118]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently when you have `ContentChild(TemplateRef)` it is not working correctly. Because after init you get different TemplateRef object as you get after another ContentCheck. 

If you have following html
```html
<grabber>
    <template>
        <div style="background-color: #FF00FF;">
            <span>ok</span>
            <div style="background-color: #00FFFF;" *ngIf="true">bad</div>
        </div>
    </template>
</grabber>
```

If your `grabber` component have `@ContentChild(TemplateRef)` and in `ngAfterContentInit()` method you will use this template, `<template>` element is used.

But if you use this template again, not during `ngAfterContentInit()` method call you get `<div style="background-color: #00FFFF;" *ngIf="true">bad</div>` template.

This is pretty awfull bug. 
Thanks for help

**Expected behavior**

It should return same template during init phase and also after another check of content. And also there is no explaination why `descendants: true` were set. This means that correct template in this case is div? If so, then during init phase this is not considered.

**Minimal reproduction of the problem with instructions**
Here is plunker where you can see problem described above. https://plnkr.co/edit/FWqPGlsENMJZHhD4SOCd?p=preview

If you add another template you see only `<div>` element.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, Visual Studio Code, npm, Connect server

* **Angular version:** >= 2.2.0

* **Browser:** all

 
* **Language:** TypeScript 2.0.9

**Comment by kukjevov** [comment]
I found even more interesting behavior. 

https://plnkr.co/edit/EOdOkydvHLRgyYz8wN4m?p=preview

You can see here that when you clear `ViewContainerRef` template changes. 

1. Add
2. Add
3. Clear
4. Add
5. Add

You will see very strange behavior.

**Comment by tbosch** [comment]
See https://github.com/angular/angular/pull/13167
/cc @mhevery

**Comment by sgomanf** [comment]
Related: primefaces/primeng#1346

**Comment by andrehaveman** [comment]
I ran into this issue when using `ngForTemplate` where the template contains an `*ngIf`.

[https://plnkr.co/edit/RdCUXH5rHOLIYrfbYw2L?p=preview](https://plnkr.co/edit/RdCUXH5rHOLIYrfbYw2L?p=preview)
