### ISSUE TITLE
Router - [routerNavigateBack]/[routerPrevousPath] attribute directive similar to [routerLink]

### ISSUE THREAD

**Issue by kmolerov** [angular/angular#13119]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

It will be very nice to be able to navigate back directly from template, without adding method to the component and using (click) binding.

Something like:
<a [routerNavigateBack]>Cancel</a>

when clicking, router should navigate you to previous active path/state.

proposed name of directive: routerNavigateBack, routerGoBack, routerBack, navigateBack, routerPrevousPath, etc.

**Comment by DzmitryShylovich** [comment]
You can easily create your own directive

**Comment by kmolerov** [comment]
Thanks, I have implemented it this way. I just thought it will be useful to be inside angular 2 framework.

**Comment by vicb** [comment]
no plan to introduce this in the router for now - we want to keep the router as small as possible and integrate only major use cases.
