### ISSUE TITLE
array with ngModel binded in input in ngFor loop acts strange

### ISSUE THREAD

**Issue by alanpurple** [angular/angular#13113]
http://plnkr.co/edit/PO9ujHLWfzvYD67nDCwT?p=preview

inputs are linked somehow

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alanpurple** [comment]
@DzmitryShylovich 
I solved this problem with dummyArray of same length.

http://plnkr.co/edit/PO9ujHLWfzvYD67nDCwT?p=preview
