### ISSUE TITLE
[tsc-wrapped] fail to run ngc when noEmitOnError is true

### ISSUE THREAD

**Issue by Delagen** [angular/angular#13120]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Compilation failed with not found module metadata.json at genDir(or outDir) path

**Expected behavior**
Compilation succeded

**Minimal reproduction of the problem with instructions**
Turn noEmitOnError option to true in tsconfig.json

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.2.3

* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** 7.2.0

**Comment by DzmitryShylovich** [comment]
Pls add repro

**Comment by Delagen** [comment]
Reproduction: https://github.com/Delagen/angular-issue13120
1. Clone repository
2. run `npm install`
3. run `npm run build.fail` see `tsconfig.success.json` differs from `tsconfig.fail.json` only with noEmitOnError flag
4. run `npm run build.success` and it works.

**Comment by JoostK** [comment]
Closing as obsolete. The compiler has evolved substantially over time, with the Ivy compiler no longer relying on metadata.json files.
