### ISSUE TITLE
update RxJS peer dependency to 5.0.0-rc.4

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#13125]
We are currently depending on 5.0.0-beta.12. The only significant breaking change between beta.12 and rc.4 seems to be the [removal of  the`cache` operator](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#breaking-changes-1).

We can either upgrade now and get this into 2.3.0 (feature freeze this Wednesday) or wait until the next major release due in March. I'd prefer 2.3 if `cache` operator removal is the only significant breaking change.

The list of things to do:

- [x] update the main package.json and shrinkwrap files
- [x] update all package specific package.json files under `modules/@angular/`
- [x] upgrade google3 with rc.4 (currently on rc.2) - @alexeagle working on this already, ETA tomorrow
- [x] figure out what to do about the `cache` operator for people that depend on it - one option is to [create a gist](https://gist.github.com/robwormald/19dea0c70a6e01aadced6731aed4f9f7) that people could paste into their apps ~~(or create an npm package, but we don't want to maintain that and we'd have to create a umd bundle in addition to d.ts and other stuff => gist is a much better option IMO)~~ - if we do go with gist, then we should create the TS and ES5 version to cover pretty much all the scenarios.
- [x] ping angular-cli to make sure they are aware of this change // @hansl 
- [x] ping docs team to make sure that they are aware of this change // @wardbell 

I believe that's it.

**Comment by IgorMinar** [comment]
@mhevery and @robwormald asked if we could unpin the version (currently our `peerDependencies` require `5.0.0-beta.12` and with this change we would require `5.0.0-rc.4`). 

I think it's too risky to unpin right now. Once rxjs 5 is stable and is following semver we can unpin, but until then we should require the exact version that angular/angular and google3 use.

**Comment by hansl** [comment]
@IgorMinar are we going to unpin before the next Angular major? Or is this planned to be done "as soon as rxjs is final"?

**Comment by mhevery** [comment]
http://cl/140504409

**Comment by mhevery** [comment]
@hansl my understanding is that we will unpin as soon as RxJS is final.

**Comment by hansl** [comment]
In master, but not on NPM. Which implies that everyone using Angular will be stuck to `rc.4` until March, and even then they'll have to upgrade their Angular major version.

Which means that Angular 2.x will be stuck with RxJS rc.4.

Correct?

**Comment by hansl** [comment]
I'd like to have my concerns addressed at least in person before this issue is closed. I'll talk to Misko tomorrow about it. Reopening until then.

**Comment by mp3por** [comment]
What is happening ? Any update on this ?

**Comment by mhevery** [comment]
Closed by 2d6a003dba165436d8e09a2eca3e01d5a545d4e3
