### ISSUE TITLE
i18n: support component input values

### ISSUE THREAD

**Issue by bahodirk** [angular/angular#13130]
I'm submitting a
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
........
<myComponent i18n-lable [label]="'Hello'"></myComponent >
........

@Component({
selector: 'myComponent',
template: `<h1>{{ label }} </h1>`
})

export class MyComponent {
@Input() label: string;
}
```
Currently, it is not possible to translate [label]. I know this can be fixed once TS translation is available, but it is somehow feels like a limitation.

**Comment by DzmitryShylovich** [comment]
Can't u use a pipe for this?

**Comment by vicb** [comment]
At some point we will support extracting string from the TS (/JS) code, ie

```ts
// the syntax is only an ex
const msg1 = __('to be translated');
``` 

Note that this feature will still be runtime only in the near future - we do *not* have plan to support dynamic translations in a near future.

Check https://github.com/ocombe/ng2-translate by @ocombe for that.
