### ISSUE TITLE
Cannot import @angular/upgrade/static in Webpack 1.x

### ISSUE THREAD

**Issue by battmanz** [angular/angular#13136]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Cannot import from '@angular/upgrade/static' when using Webpack 1.x
However, if I manually delete the `@angular/upgrade/static.js` file, then it works fine. Since, once I delete the `static.js` file, it then picks up the `bundles/upgrade-static.umd.js` file.

**Minimal reproduction of the problem with instructions**

// Add this to main.ts
import { UpgradeModule } from '@angular/upgrade/static';

**Please tell us about your environment:**

Webpack 1.13.3

* **Angular version:** 2.0.X

Angular 2.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 54

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.0.8

**Comment by vsavkin** [comment]
Dup of https://github.com/angular/angular/issues/13137
