### ISSUE TITLE
angular webpack @angular/common/src/directives/ng_class.d.ts:46:33 Cannot find name 'Set'.

### ISSUE THREAD

**Issue by thetrav** [angular/angular#13142]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Build process fails due to a dependency resolution error within angular code.  No js files are produced

**Expected behavior**
I expect the build to complete successfully and leave me with 3 js files in the dist folder
**Minimal reproduction of the problem with instructions**
Following the guide at https://angular.io/docs/ts/latest/guide/webpack.html
Leaves me with a project which I've pushed to https://github.com/thetrav/angular-webpack
After invoking npm install, as the guide says, I invoke:
```
angular-webpack thetrav$ npm run build
```
and get the output
```
> angular2-webpack@1.0.0 build /Users/thetrav/projects/angular-webpack
> rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail

4305ms build modules
9ms seal
9ms optimize
54ms build modules
14ms hashing
40ms create chunk assets
15341ms additional chunk assets
4171ms optimize chunk assets
 90% optimize assetsError in bail mode: [default] /Users/thetrav/projects/angular-webpack/node_modules/@angular/common/src/directives/ng_class.d.ts:46:33
Cannot find name 'Set'.
```

**What is the motivation / use case for changing the behavior?**
This is basic "get started" stuff for me, I'm delivering my angular app to web clients who have connections that suffer from loading many small files, the bundling is a hard requirement

**Please tell us about your environment:**
OSX sierra, sublime text editor, no http server used
```
Traviss-MBP:angular-webpack thetrav$ npm --version
3.10.9
Traviss-MBP:angular-webpack thetrav$ node --version
v7.1.0
```

* **Angular version:** 2.0.X
as per the guide all the @angular packages are listed as ~2.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
no browser used
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
as per guide: `"typescript": "^2.0.3"`
* **Node (for AoT issues):** `node --version` =   
```
Traviss-MBP:angular-webpack thetrav$ node --version
v7.1.0
```

**Comment by DzmitryShylovich** [comment]
> @angular/common/src/directives/ng_class.d.ts:46:33 Cannot find name 'Set'

u need es6 types. 

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by thetrav** [comment]
Is that addressed anywhere in the official guide I linked to?  
Searching for types doesn't mention es6, nor say anything about "es6 types"

Am I missing something in the docs, or is there something that isn't in the docs?

I can re-post as a StackOverflow question, however if the guide you've published doesn't mention es6 types, then that's at the very least a documentation bug, correcting it would probably help your new users

**Comment by ericmartinezr** [comment]
https://angular.io/docs/ts/latest/guide/typescript-configuration.html there you can find the configuration for typescript

**Comment by thetrav** [comment]
Ok, so it looks like the tsconfig.json in the angular-webpack guide I've linked above is missing at least `"lib": ["es2015", "dom"]` from its compiler options.  
There are other differences, but I'll play around some more and report any breaking changes I find.

If anyone is able to update the guide it'll probably help your new users a lot

**Comment by thetrav** [comment]
```
"typeRoots": [
      "node_modules/@types/"
    ]
```
Is the other critical line
