### ISSUE TITLE
Feature Request: Good documentation for debugging performance issues while using Angular

### ISSUE THREAD

**Issue by davityle** [angular/angular#13144]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It is easy to find basic angular 2 tutorials and blogs on the basics of change detection but there are little to no resources on debugging issues with angular. Such as how do I find which components are marking for check and when?

**Expected behavior**
Resources should be available for debugging purposes

**What is the motivation / use case for changing the behavior?**
We have had users say things such as "UI is very nice I'd love to use it on a daily basis, but performance is terrible...". We have done a lot of profiling and we have fixed many performance issues but right now the biggest cpu hogger is the change detector. We have already updated all of our components to use OnPush and have fixed many places where we knew that components were re-rendering needlessly but we have hit a point where we aren't sure what is marking components for check and or triggering the change detector. I opened [this issue on StackOverflow](http://stackoverflow.com/questions/40850766/debug-angular2-change-detector) but nobody answered (If someone wants to respond to that question that would be awesome). It would be much better if this information was just readily available online

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/browser/tools/tools.ts#L24

**Comment by vicb** [comment]
@davityle I'm closing this issue at it is not really actionable, please re-open on the doc repo (angular/angular.io).

We could help once you narrow down your issue. Please re-open an issue with more details at that time.

That being said if you still struggle to use the profiler please ping me from the issue on angular/angular.io and we'll do our best to help.
