### ISSUE TITLE
Lazy loading module and injected service behaviour

### ISSUE THREAD

**Issue by mananvpanchal** [angular/angular#13155]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Service instance is created whenever lazy module is loaded. It is not created only once when module loaded and not preserved in DI context. Even further service instance not preserved for component too. Each time lazy module loaded for any of component path the service instance would be created. Service instance not being shared between components of the lazy module. Even service instance not being preserved for a single component for reuse.

**Expected behavior**
Service instance is created whenever eager module initially loaded, and the instance would be shared among all components of the module. I expect same behaviour with lazy module too. Service should be created once lazy module loaded and should remain in DI context of the module and should be available for all components in the module.

**Minimal reproduction of the problem with instructions**

My code is here: https://github.com/mananvpanchal/angular2-webpack-boilerplate
please clone it and just run `npm install` and then `npm run start`.

If you want to code your own: Just create a lazy module and create two component in the module. Create a service which should be provided by the module. You can see that the service instance will be created each time you try to load the lazy module including any of two component. I am putting here little code snippet as well.

```
const routerConfig = [
  {
    path: "",
    component: LazyComponent
  },
  {
    path: "otherlazy",
    component: OtherLazyComponent
  }
];

@NgModule({
  imports: [ RouterModule.forChild(routerConfig) ],
  declarations: [ LazyComponent, OtherLazyComponent ],
  exports: [ LazyComponent, OtherLazyComponent ],
  providers: [ PrivateService ]
})
export class LazyModule {

}
```
```
@Component({
  selector: 'lazy',
  template: `<div><h1>Lazy</h1><button (click)="incr()">Increment</button><div>{{ps.getId()}}</div></div>`
})
export class LazyComponent {

  constructor(private ps : PrivateService) {

  }

  incr() {
    this.ps.incr();
  }
}
```
```
@Component({
  selector: 'other-lazy',
  template: `<div><h1>Other Lazy</h1><button (click)="incr()">Increment</button><div>{{ps.getId()}}</div></div>`
})
export class OtherLazyComponent {

  constructor(private ps : PrivateService) {

  }

  incr() {
    this.ps.incr();
  }
}
```
```
@Injectable()
export class PrivateService {
  id = 0;

  incr() {
    this.id++;
  }

  getId() {
    return this.id;
  }
}
```
```<a routerLink="lazy">Lazy</a><a routerLink="lazy/otherlazy">Other Lazy</a>```

If I click `Lazy` and I hit `<button (click)="incr()">Increment</button>` I can see the value `{{ps.getId()}}` would increment. But, if I go to `Other Lazy` I get `0`. If I again increment here and I go back to `Lazy` I again get `0`.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v5.4.0

**Comment by zoechi** [comment]
Is this a dup of #12889 ?

**Comment by mananvpanchal** [comment]
Oh yes.. Both seems same

**Comment by zoechi** [comment]
Would you mind closing this one then?

**Comment by mananvpanchal** [comment]
Not a problem.

**Comment by DzmitryShylovich** [comment]
@mananvpanchal close? :)

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed
