### ISSUE TITLE
replaceUlr, skipLocationChange doesn't  work in routerLink (@angular/router@3.3.0-beta.1)

### ISSUE THREAD

**Issue by yoelp** [angular/angular#13156]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

PR https://github.com/angular/angular/pull/12850 has a fix for https://github.com/angular/angular/issues/12849 , but it actually doesn't work
when passing replaceUrl or skipLocationChange to routerLink it does not take affect 

**Expected behavior**

It should behave as when passed to a router.navigate request

**Minimal reproduction of the problem with instructions**
See plunkr https://plnkr.co/edit/MEEad3YqXWzauoBxYgvr?p=preview (open in popup to see the url change, and history entry)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:** NA

* **Angular version:** router 3.3.0-beta.1

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
true the `skipLocationChange` should be passed here: `this.router.navigateByUrl(...);`
