### ISSUE TITLE
Meta: Plunker suggested in issue template does not work using Internet Explorer

### ISSUE THREAD

**Issue by chliebel** [angular/angular#13152]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The Plunker suggested to reproduce issues doesn’t contain the core.js shim. Therefore, the sample won’t even boot on Internet Explorer: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

Plunk is referenced here: https://github.com/angular/angular/blame/master/.github/ISSUE_TEMPLATE.md#L22

**Expected behavior**
You should add `<script src="https://unpkg.com/core-js@2.4.1/client/shim.min.js"></script>` in line 8 of `index.html` to make sure IE bugs can also be reproduced.

**Minimal reproduction of the problem with instructions**
1. Open Plunk in Internet Explorer: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5
2. See the error message in the console: `TypeError: Unable to get property 'apply' of undefined or null reference`

* **Browser:** IE
 
* **Language:** all

**Comment by robwormald** [comment]
Fixed 👍
