### ISSUE TITLE
Router can't parse optional parameter after refresh page!

### ISSUE THREAD

**Issue by keyiis** [angular/angular#13150]
**Current behavior**
`Cannot match any routes. URL Segment: 'admin/order/detail%3Bid%3D37'`

**Expected behavior**
without the bug

**Minimal reproduction of the problem with instructions**
i pass a optional parameter form "listComponent" to "detailComponent",below is code:
**listComponent**
`this.router.navigate(['detail', { id: rowData.id }], { relativeTo: this.route });`
**detailComponent**
```
ngOnInit() {
    this.route.params.forEach((params: Params) => {
            let orderId = params['id'];
            this.orderService.getOrder({where:{id:orderId}}).then(rst=>{
              this.order=rst||{};
            }).catch(err=>{
              this.globalService.tip(err);
            });
        });
  }
```
router.module.ts
```
export const adminRoutes: Routes = [
  {
    path: 'admin',
    component: AdminComponent,
    children: [
      {
        path: 'order', children: [
          { path: 'detail', component: OrderDetailComponent },
          { path: '', component: OrderManageComponent },
        ]
      },
      { path: '', redirectTo: 'order' }
    ],
    canActivate: [AuthGuard],
    canActivateChild: [AuthGuard]
  }
];

@NgModule({
  imports: [
    RouterModule.forChild(adminRoutes)
  ],
  exports: [
    RouterModule
  ]
})
export class AdminRoutingModule { }
```
it's work fine,but when i refresh detail page then i get error.so where is the mistake or a bug?

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
win10 x64
vscode
webpack 2.1.0

* **Angular version:** 2.0.3

* **Browser:** 
electron 1.4.5
 
* **Language:** 
TypeScript 2.0.10

* **Node (for AoT issues):**
node 4.6.1
npm 2.15.9

**Comment by vicb** [comment]
could you add a repro, probably a server setup issue.

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have reproduce scenario.
