### ISSUE TITLE
Not able to get templateUrl property of @Component dynamically by any way.

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#13153]
Not able to get templateUrl property of @Component dynamically by any way.

I have a component definition along with its class:

Component({
    moduleId: module.id,
    selector: 'contact-state',
    templateUrl: want to get template path as a @input in this component
})

export class ContactStateComponent{
}

Is it not feasible in AngularjS 2 ??????

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

And no, it's not possible just like that. See http://blog.lacolaco.net/post/dynamic-component-creation-in-angular-2-rc-5/

**Comment by vasuneet** [comment]
NgTemplateOutlet provide similar kind of feature but i am not able to explore it due to not having proper documentation.

**Comment by DzmitryShylovich** [comment]
> templateUrl: want to get template path as a @input in this component

it doesn't work like this. u can get template as input. component is compiled (with template ans styles) before any input is resolved.

**Comment by vicb** [comment]
As said above, the `templateUrl` has to be known at compile time.

You should use `NgTemplateOutlet`
