### ISSUE TITLE
Router navigate - option to trigger params subscription on navigating to same required parameters.

### ISSUE THREAD

**Issue by kmolerov** [angular/angular#13166]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**My scenario**
I have a parent and child routing configuration, where child is loaded based on the id required parameter of it's parent.
```
{
  path: 'parent/:id',
  component: ParentComponent,
  children: [{
    path: 'child',
    component: ChildComponent1,
  }]
}

from some component I am navigating to this state:
this.router.navigate(['parent', 1, 'child']);

in ChildComponent1 I have:
this.route.parent.params.subscribe(params =>{
   this.dataService.getBySomeChildEntityByParentId(params['id'])
     .subscribe(model =>{
        this.model = model;
});
```

in ParentComponent I have:
```
this.entityBackEndService.doSomeDomainLogic  // change state of entity and preserve it in Db.
    .subscribe(model =>{
        this.model = model;
        this.router.navigate(['parent', 1, 'child']); // which is exactly the same state
});
```
**Problem**
I should be able to trigger reload of model in ChildComponent by navigating to the same state/route with "this.router.navigate(['parent', 1, 'child']);" but there is no way to do it, because required parameter "id" has the same value as before. 

**Workaround **
Add optional parameter to the navigation in parent, which will trigger params change subscription in child:
 this.router.navigate(['parent', 1, { version: this.model.version }, 'child']);

**Required new behavior ** 
Have optional parameter in extras that will trigger subscription of params change even if parameter value stays the same:
this.router.navigate(['parent', 1, 'child'], extras: { forceParamsChange: true});

**Note**
I know components aren't going to be recreated, that's why we are using parameters subscription.
I don't want to force components to be recreated!
I know that I could use shared service for this scenario, but I don't want.
I know that this has something to do with Rxjs, but I am not yet proficient in it.

**Comment by DzmitryShylovich** [comment]
@kmolerov take a look at this https://github.com/angular/angular/pull/14567 feature

**Comment by atscott** [comment]
I believe this is available with `onSameUrlNavigation='reload'`/`RouteReuseStrategy` (for reloading the component)/`runGuardsAndResolvers`
