### ISSUE TITLE
Fix performance regression due to render layer

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1316]
Tree benchmark pureScriptTime:

With Viewpool:
- master: 40.35ms
- befor render layer+query: 31.92ms

Without Viewpool
- master: 85.89ms
- before render layer+query: 77.61ms

As reference:
- baseline: 22.16ms
- render time: 27.20ms

**Comment by tbosch** [comment]
This was accidentally closed...

**Comment by tbosch** [comment]
This is not the bug we had a week ago where the performance slowed down by 3x because our ViewPool did not work correctly (this is already fixed). 
Moving this issue out to M9 therefore.

**Comment by mhevery** [comment]
I believe this is obsolete. Closing, reopen if you feel otherwise.

**Comment by tbosch** [comment]
Yes, this is done
