### ISSUE TITLE
The router.navigate in ngOnInit is not working.

### ISSUE THREAD

**Issue by kiruto** [angular/angular#13174]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
import {Component, OnInit} from '@angular/core';
import {Tag} from "./tag.model";
import { Location } from '@angular/common';
import {Router} from "@angular/router";
import {PATH} from "./config.constant";

@Component({
  moduleId: module.id,
  selector: 'my-app',
  templateUrl: 'app.template.html'
})
export class AppComponent implements OnInit {
  constructor(private router: Router,
              private location: Location) { }

  ngOnInit() {
    alert(); // called
    this.router.navigate([PATH]); // not work
    this.router.navigateByUrl(PATH); // not work
    setTimeout(() => this.router.navigate([PATH]), 500); // not work
  }

  navigate() {
    this.router.navigate([PATH]); // works well
    this.router.navigateByUrl(PATH); // works well
  }
}
```
The navigate not works when called in ngOnInit(), and nothing throws or any error messages appears. The same navigate function when it be called out of ngOnInit(), it works well. 

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

HTTP server: nginx <- tornado <- flask

* **Angular version:** 2.2.0

* **Browser:** [Chrome 54.0.2840.98]

 
* **Language:** [TypeScript 2.0.10]

* **Node (for AoT issues):** `node --version` = v6.9.1

**Comment by zoechi** [comment]
Please provide a Plunker that allows to reproduce the issue as requested in the issue template.

**Comment by vicb** [comment]
Issue is that by default the router will perform the initial navigation in a microtask that will "override" your navigation in the **app** component.

The solution would be to disable the intial navigation by passing {intialNavigation: false} to .forRoot in your app module.

**Comment by ahelord** [comment]
@vicb  where put example?

**Comment by bob-lee** [comment]
With Angular 2.4.0 and router 3.4.0, navigate in ngOnInit seems working without passing { initialNavigation: false }

**Comment by DzmitryShylovich** [comment]
@bob-lee yeap, it was fixed

**Comment by joashmusyoka** [comment]
@DzmitryShylovich Navigation seems to work but the returned promise has null instead of true or false as per the spec
