### ISSUE TITLE
Angular2 can not render the hgroup tag

### ISSUE THREAD

**Issue by hieutranagi47** [angular/angular#13172]
Hi Angular team,

I just created a component then I use below html, but angular show me some error log:
```
<article>
    <header>
        <hgroup>
            <h3>Main title</h3>
            <h4>Subtitle</h4>
        </hgroup>
        <p>metadata - Esse in minim ipsum labore. Sunt labore sunt aute ea ullamco magna velit exercitation. Consectetur est sit nulla ea quis eu exercitation elit velit.</p>
    </header>
</article>
```

ERROR LOG:
zone.js:388Unhandled Promise rejection: Template parse errors:
'hgroup' is not a known element:
1. If 'hgroup' is an Angular component, then verify that it is part of this module.
2. If 'hgroup' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("<article>
    <header>
        [ERROR ->]<hgroup>
            <h3>Main title</h3>
            <h4>Subtitle</h4>
"): MusicComponent@2:8 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
'hgroup' is not a known element:
1. If 'hgroup' is an Angular component, then verify that it is part of this module.
2. If 'hgroup' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("<article>
    <header>
        [ERROR ->]<hgroup>
            <h3>Main title</h3>
            <h4>Subtitle</h4>
"): MusicComponent@2:8
    at TemplateParser.parse (http://localhost:4200/main.bundle.js:18362:19)
    at RuntimeCompiler._compileTemplate (http://localhost:4200/main.bundle.js:39141:51)
    at http://localhost:4200/main.bundle.js:39064:83
    at Set.forEach (native)
    at compile (http://localhost:4200/main.bundle.js:39064:47)
    at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:87043:26)
    at Zone.run (http://localhost:4200/main.bundle.js:86925:43)
    at http://localhost:4200/main.bundle.js:87313:57
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:87076:35)
    at Zone.runTask (http://localhost:4200/main.bundle.js:86965:47)consoleError @ zone.js:388
zone.js:390Error: Uncaught (in promise): Error: Template parse errors:(…).

Regard,
Hieu Tran

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)

**Comment by DzmitryShylovich** [comment]
@hieutranagi47 https://github.com/angular/angular/issues/12096#issuecomment-251800846

**Comment by RichardBray** [comment]
Why has this been closed. This still exists on the latest 4.1.3
