### ISSUE TITLE
Jsonp callbackName can be modified wanted

### ISSUE THREAD

**Issue by doxiaodong** [angular/angular#13175]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The jsonp callbackName is set as `__ng_jsonp__.__req0.finished`

**Expected behavior**

It will be nice if I can modify the jsonp callbackName

**Reason**
Some servers don't response right data if jsonp callbackName with `.`, And most of servers which need a jsonp method to get cannot easy to modify.
Please

* **Angular version:** <= 2.2.4

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =  all

**Comment by DzmitryShylovich** [comment]
> The jsonp callbackName is set as __ng_jsonp__.__req0.finished

can u add repro in plunkr?

**Comment by DzmitryShylovich** [comment]
We have 2 options here:
1. Introduce JsonpCallbackNameStrategy
2. We can make BrowserJsonp an abstract class so people can provide their own impl.

**Comment by awerlang** [comment]
I'm not sure why an Angular 2 user would like to know about implementation details, and inform a custom callback name. I bet they want the issue fixed on the Angular 2 side. Anyways, jsonp libraries usually accept a `callback` name. Of course, this is a workaround, not a solution.

@doxiaodong As I suggested on S.O. (http://stackoverflow.com/a/40948414/592792), you can use a 3rd-party library like this one: https://github.com/camsong/fetch-jsonp

**Comment by doxiaodong** [comment]
@awerlang thanks, I'm using `fetch-jsonp`. But I think there should be an angular way.

**Comment by splurtcake** [comment]
+1

The callback name I need to work with is `file.json?callback=jsonCallback_{{APP_ID}}`.

No idea why this is hard coded in Angular 2.

**Comment by DzmitryShylovich** [comment]
@doxiaodong was fixed here https://github.com/angular/angular/pull/13219

**Comment by doxiaodong** [comment]
@DzmitryShylovich , thanks

**Comment by doxiaodong** [comment]
I get error after this fix, my code is https://github.com/angular/angular/pull/13219#issuecomment-277179923
![image](https://cloud.githubusercontent.com/assets/6927481/22582776/cda6014e-ea23-11e6-87dc-2b945667eefe.png)

**Comment by DzmitryShylovich** [comment]
@doxiaodong file new issue pls

**Comment by doxiaodong** [comment]
@DzmitryShylovich , https://github.com/angular/angular/issues/14267

**Comment by dgvozd** [comment]
@DzmitryShylovich Is it possible right now to modify the jsonp callbackName?
