### ISSUE TITLE
Date: distinguish between european and american format.

### ISSUE THREAD

**Issue by FrancescoMussi** [angular/angular#13179]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I get a date from the API in the european format: 01-06-2018 (1 june 2018).
I need to convert it in a more beautiful format, for instance:

`{{ dateTest | date: 'd MMM y' }}`

But the result is **6 Jan 2018** while in my case should actually be **1 June 2018** .
No matter which pipe format i choose - Angular will always think that the first two cyphers of my date is the month (while for my european formatted date is the day).

**Expected behavior**

Could be nice to a direct date pipe to convert european dates.

**Minimal reproduction of the problem with instructions**

```
dateTest: Date;
this.dateTest = new Date(this.projectInfo['project_start_date']);

// or hardcoded:
this.dateTest = new Date('01-06-2018');

<span> {{ dateTest | date: 'd MMM y' }} </span>
```

**What is the motivation / use case for changing the behavior?**

Whenever we are working with european formatted dates in angular2 we need to find workarounds.
Could be nice a way to let know angular that i receive dates in the european format.

**Please tell us about your environment:**

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
OS: OS X El Capitan

```

* **Angular version:** 2.1.1

* **Browser:** [Chrome ]

 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` = v4.6.0

StackOverflow question:

https://stackoverflow.com/questions/40912459/how-to-convert-date-from-european-format

**Comment by DzmitryShylovich** [comment]
> But the result is 6 Jan 2018 while in my case should actually be 1 June 2018 .

pls add a repro in plunkr

**Comment by FrancescoMussi** [comment]
Here it is:

https://plnkr.co/edit/ZYMoaoxawVCtScUZfL3B?p=preview

**Comment by DzmitryShylovich** [comment]
what is the expected syntax? `<span> {{ dateTest | date: 'd MMM y':'eu' }} </span>`?

**Comment by FrancescoMussi** [comment]
Being an european formatted date - the expected date should be: 1 June 2018

**Comment by DzmitryShylovich** [comment]
It's not an angular pipe bug. 
You cannot construct date in European format by default. This is why `new Date('22-06-2018');` (from your plunkr) results in error.
So we have 2 options:
1. you need to preformat date so it will be in the right format (mm-dd-yyyy) 
2. you need to tell angular that date is in European format so we can preformat it for you.

**Comment by FrancescoMussi** [comment]
Ok thanks.
Can you be so kind to point out how the second choice can be done?
I have tried by injecting this in the provider in app.module:

`{ provide: LOCALE_ID, useValue: "en-GB" }`

But didn't work

**Comment by pkozlowski-opensource** [comment]
It is not about US vs. "European" format - what you are asking for is _parsing_ according to a locale. This might be an interesting feature but the one that is not currently supported by the Intl API (foundation we are building upon).

**Comment by fredrikredflag** [comment]
@FrancescoMussi `01-06-2016` isn't a valid for for javascript `Date`. I would say it falls a bit outside the scope of angular. Allowed formats for `Date` can be found here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

You can checkout moment, it can handle the formatting for you.
http://momentjs.com/docs/#/use-it/typescript/
http://momentjs.com/docs/#/parsing/string-format/

Something like this should do the trick:
```typescript
import * as moment from 'moment'

export class App {
  dateTest: Date;
   constructor() {
      // Get a date in european format:
      this.dateTest = moment("01-06-2016", "DD-MM-YYYY");
    }
}
```

**Comment by FrancescoMussi** [comment]
@fredrikredflag okay thanks!

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource outside of angular scope. can be closed
