### ISSUE TITLE
Animation of a nested element does not work correctly (it was fine till v2.2.0 incl.)

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular#13187]
**I'm submitting a**
```
[x] bug report
```

**Current behavior** Angular 2.3.0-rc.0
See the plunk: http://plnkr.co/edit/xyoxhBKOV5rNIdUtnirO?p=preview

**Expected behavior** Angular 2.2.0 = the last version with the correct behaviour
See the plunk: http://plnkr.co/edit/87xr84ZbJzhZnacSjaFr?p=preview

**Minimal reproduction of the problem with instructions**
Click the buttons: Expand Outer, Expand Inner and then Collapse Outer. Then you can continue with: Expand Outer, Collapse Inner, Collapse Outer. In both cases you can see a mistake at the animation movement on the inner element.

**Please tell us about your environment:**
Windows 8.1 64bits, NODE 6.9.1  64bits, NPM 3.10.8, VS Code 1.7.2, gulp-live-server 0.0.30

* **Angular version:** 2.3.0-rc.0
* **Browser:** all
* **Language:** TypeScript 2.0.10

**Comment by matsko** [comment]
Sorry this came up. We have been aware of this and the upcoming `query()` feature will handle the fix.

**Comment by mlc-mlapis** [comment]
Matias, thanks for your info. Which version does it mean? 2.3.0-rc.1?

**Comment by mlc-mlapis** [comment]
I tested version 2.3.1 and it looks that the animation works correctly. The query() feature was already implemented? Or is there something else that affects this problem?

**Comment by matsko** [comment]
There will be an earlier fix next week that will fix this and the query feature will be for 4.0.0.beta.

**Comment by mlc-mlapis** [comment]
Matias, thanks for your info.

**Comment by matsko** [comment]
I put this together using the head version of Angular and it looks like it's working fine: http://plnkr.co/edit/ijBHB0PYniAsWhVVZcZz?p=preview

**Comment by mlc-mlapis** [comment]
Yes, I can confirm that. As I wrote earlier I got the same good test result even on version 2.3.1. I do not know exactly if this fact corresponds with changes that were made by you. Do you think that it would be possible?

**Comment by matsko** [comment]
I'm not sure in what range the functionality broke, but it's likely it has something to do with the reordering of animation statements to get the cancel functionality to work (https://github.com/angular/angular/commit/9de76ebfa545ad0a786c63f166b2b966b996e64c).

I think it's best that a good unit test gets added so  this doesn't pop up again. I will open up a new issue for that. Can I close this one?

**Comment by mlc-mlapis** [comment]
Yes, thank you Matias.

**Comment by matsko** [comment]
Here is the new issue: https://github.com/angular/angular/issues/13571. Thank you @mlc-mlapis for the quick replies and for finding the issue.
