### ISSUE TITLE
"Usemap" isn't a known property of 'img' 

### ISSUE THREAD

**Issue by AndyBlatecky** [angular/angular#13181]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When attempting to use interpolation within a "usemap" attribute contained within an "img" tag in a template file. Per HTML5 spec, "usemap" should be an accepted attribute within an "img" tag.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

Console error: 
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'usemap' since it isn't a known property of 'img'. 

Example: 
`
<img src="url{{ x }}.html" usemap="#map{{ x }}" alt="" >
<map name="map{{ x}}"> 
<area>
</map>
`

**Expected behavior**
Expected for the interpolation to provide the variable value, similar to in the "src", "alt", and other img attributes - without error.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/LGFUrJAVLj1BJlI5CVF4?p=preview

**What is the motivation / use case for changing the behavior?**
Trying to add multiple and dynamic image maps on a page.

**Please tell us about your environment:**

VSCode
Node 6.9.1
Webpack 2.1.0-beta.27

* **Angular version:** 2.2.3

* **Browser:** All
 
* **Language:** All

* **Node (for AoT issues):**  Node 6.9.1

**Comment by DzmitryShylovich** [comment]
`[attr.usemap]="'#' + name"` or `useMap="#{{name}}"`

**Comment by vicb** [comment]
`[prop]="..."` is equivalent to `prop="{...}"` and is a **property** binding, you should use whatever @DzmitryShylovich mentioned above
