### ISSUE TITLE
Feature request: Programatical css urls injection for components

### ISSUE THREAD

**Issue by zzx88991** [angular/angular#13188]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, angular2 will only load styleUrls in the @Component's property `styleUrls:[".../some path"]`

**Expected behavior**

It would be nice we have api to inject the `styleUrls` dynamically.

An example to be like: 
```
export class MyComponent {
     contructor(styleInjector: StyleInjector){
         styleInjector.inject(['someStylesheet.css', 'anotherStylesheet.css']);
     }
}
```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all]

 
* **Language:** [TypeScript 2.0]

* **Node (for AoT issues):** `node --version` =  `7.1.0`

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/13153#issuecomment-263947120

**Comment by zzx88991** [comment]
Gotcha, thanks!

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed
