### ISSUE TITLE
feature (@angular/http) set request content type by RequestOptionsArgs / RequestOptions

### ISSUE THREAD

**Issue by RKaczmarek** [angular/angular#13185]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
To make a request the header with the content-type has to be added manually:

For example
```typescript
import { Http, Request, Headers } from '@angular/http';

var dummy: {
    anyProperty: 'AnyValue'
}

let headers: Headers = new Headers({
    'Content-Type': 'application/json'
});

let request: Request = new Request({
    url: 'any',
    body: JSON.stringify(dummy)
    headers: headers
});

http.request(request);
```

**Expected behavior**
It would be nice to be able to set the content type with the RequestOptions or RequestOptionsArgs. The property could be 'contentType' and the value should be of type ContentType.

The header could be added by Http before sending the request. I would suggest to override the content type in the header when it is already present with the passed content type in the options.

For example:
```typescript
import { Http, Request, ContentType } from '@angular/http';

var dummy: {
    anyProperty: 'AnyValue'
}

let request: Request = new Request({
    url: 'any',
    body: JSON.stringify(dummy)
    contentType: ContentType.JSON
});

http.request(request);
```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
- less code
- set default behavior in class extending Http and change type individually in requests
- make anum ContentType useful

**Please tell us about your environment:**

* **Angular version:** master

* **Browser:** [all]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` = 7.0

**Comment by DzmitryShylovich** [comment]
why don't u just set content type header?
