### ISSUE TITLE
FormArray errors when used with ngc

### ISSUE THREAD

**Issue by sudharsanmit** [angular/angular#13184]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**

Template:
`<div formArrayName="products">  
    <div *ngFor="let product of combo.get('products').controls; let i=index;">
`
Ngc failed:

```
pages/combodetail/combodetail.ngfactory.ts:706:63
[10:45:01]  Property 'controls' does not exist on type 'AbstractControl'.
[10:45:01]  ngc failed

```
Line 706: combodetail.ngfactory.ts

`const currVal_42:any = this.context.combo.get('products').controls;
`
So I go to fix the template

Template:
`<div *ngFor="let product of combo.get('products'); let i=index;">`

Ngc passed!! Yaay!!

Oops.. But I am getting error from Angular2!!! NgFor expects an iterable... Chicken egg situation..

`Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.
`
It works in dev mode without ngc...

Currently, there is no method to return an iterable to be used in ngFor along with FormArray.
There is no way to cast it to type <FormArray> in the template as we do in the typescript file.

Any help or direction appreciated.

Also tried using
`<div *ngFor="let product of combo.get('products').value; let i=index;">`
`<div *ngFor="let product of combo.get('products').getRawvalue(); let i=index;">`
but no luck.

**Comment by DzmitryShylovich** [comment]
try 
```
*ngFor="let product of (combo.get('products') as FormArray).controls
```
if it doesn't work u can create a method 
```
getControls(combo) {
    rerun combo.get('products') as FormArray).controls;
}
```
and use it like `*ngFor="let product of getControls(combo)`

**Comment by sudharsanmit** [comment]
Thank you!

This worked..

```
*ngFor="let product of getControls(combo); let i=index;"

  getControls(combo){
      return combo.get('products').controls;
  }

```
