### ISSUE TITLE
routerLink directive doesn't support dynamically binding to an observable

### ISSUE THREAD

**Issue by CalvinDale** [angular/angular#13190]
I'm submitting a [X] feature request

**Current behavior**
The `routerLink` directive apparently does not support binding to an observable stream such as  `Observable<string>` or `Observable<Any[]>`.

**Expected behavior**
Should be able to bind to an observable stream representing a valid `router.navigate()` instruction.

Possible syntax: 

``` 
<a [routerLink]="{{ urlString$ | async }}">Link 1</a>
<a [routerLink]="['static1', 'static2', {{ dynamicPath$ | async }}']">Link 2</a>
<a [routerLink]="['static1', {{ zeroOrMoreMatrixParams$ | async }}']">Link 3</a>
```
Or perhaps the syntax could omit the interpolation braces.

**Minimal reproduction of the problem with instructions**
Create a component with an `Observable<string>` property providing URLs. Try binding a `routerLink` directive to it. There appears to be no way to do this.

**What is the motivation / use case for changing the behavior?**
Represent application state as an observable as suggested here: https://vsavkin.com/managing-state-in-angular-2-applications-caf78d123d02.

Application state members are projected to generate route instructions as an observable stream. Application state observable emissions update route-instructions which should get propagated to anchor *href*s via *routerLink*s.

This functionality would be useful for keeping the URL bar in sync with application state upon revisiting a child-component. For example, a parent component with a router-outlet having several anchor elements with deep links into various child components, should update the anchors' *href*s in order to later restore (re-display) a previously visited component as the state changes.

One alternative is to use `router.navigate()` on element's click event handler. But among other drawbacks this approach breaks the *control+click* or *Open link in new tab|window* context-menu feature.

Another alternative is to bind an Observable<string> directly to an anchor's *href* and not use the `routerLink` directive. But since this approach ignores the router, the link behaves like a page refresh. Nevertheless it works in my implementation because I'm persisting state to local storage and critical state to the URL bar also. But it's a hack.

**Please tell us about your environment:**
```
angular-cli: 1.0.0-beta.15
node: 6.9.1
os: win32 x64 (Windows 10)
```

* **Angular version:** `2.2.3`

* **Browser:** `all`
 
* **Language:** `TypeScript 2.0.10`

**Comment by DzmitryShylovich** [comment]
`<a [routerLink]="urlString$ | async">Link 1</a>`

**Comment by CalvinDale** [comment]
I've tried that syntax @DzmitryShylovich. But it doesn't seem to work. Hence, I assumed it wasn't supported.

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plnkr.

**Comment by CalvinDale** [comment]
I'm off for a couple of weeks. But I'll create a plnkr eventually after I return. However, are you sure this feature is actually supported?

**Comment by DzmitryShylovich** [comment]
yeap

**Comment by CalvinDale** [comment]
An *href* bound to an `Observable<string>` works when the URL-fragment is suffixed with matrix parameters.

But a *routerLink* bound to the same observable URL-encodes the emitted values and consequently targets a route that the router cannot match.

If the emitted `urlString$` value is `"path1/path2;tcomp=2;tmake=1"`, this table highlights the difference:

```
| HTML                                                | Target URL                              |   Outcome    |
|-----------------------------------------------------|-----------------------------------------|:------------:|
| <a [href]="urlString$ | async">href</a>             | .../path1/path2;tcomp=2;tmake=1         |    Works     |
| <a [routerLink]="urlString$ | async">routerLink</a> | .../path1/path2%3Btcomp%3D2%3Btmake%3D1 | Doesn't work |
```

@DzmitryShylovich, Is there a work-around for this issue?

**Comment by DzmitryShylovich** [comment]
`routerLink` accepts an array of commands not a url https://github.com/angular/angular/blob/master/modules/%40angular/router/src/directives/router_link.ts#L169

**Comment by CalvinDale** [comment]
Thanks! Streaming the data as an array worked.

**Comment by ajonp** [comment]
So can you do it like this?
`<a [routerLink]="['/user',(activity.user | async)?.$key]" routerLinkActive="active">
                {{(activity.user |async )?.displayName}}
                </a>`

**Comment by CalvinDale** [comment]
I can't say @ajonp if that approach will work as I haven't tried it.

I'm doing something similar to this:

 `<a [routerLink]="exampleRoute$ | async">some route</a>`

```
private readonly stateExampleRootPath = 'example';
public exampleRoute$: BehaviorSubject<any[]> = new BehaviorSubject<any[]>([this.stateExampleRootPath]);

public ngOnInit(): void {
    this.stateSubscription = this.appStateService.state$.subscribe(() => {
        const filtersState: IFiltersState = this.appStateService.getValue().filters['primary'];
        const matrixParams: Object = this.getMatrixParams(filtersState);
        let path: any[] = [this.stateExampleRootPath];
        if (Object.keys(matrixParams).length > 0) {
            path.push(matrixParams);
        }
        this.exampleRoute$.next(path);
    });
}

```
