### ISSUE TITLE
Socket got error when use angular2 at MAC OS environment.

### ISSUE THREAD

**Issue by ducduongtmb** [angular/angular#13192]
my app use nodeJs , angular2 , socket.io .

Nodejs 6
Angular 2
socket at server 1.6.0 at client 1.6.0
MAC OS is my environment

I tried to make a chat room :

add a message to a chat room.
switch another chat room.
switch back to first room. Then nothing to display.
I've got chrome console messages.

`zone.js:1382 GET http:/X.X.X.X:YYYY/socket.io/?EIO=3&transport=polling&t=LYvYIgZ net::ERR_EMPTY_RESPONSE`
My code run well on some computer , but I got error when run on some other computers .
I don't know why . Thanks for help !

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by ericmartinezr** [comment]
@vicb can you close this one?
