### ISSUE TITLE
AOT + barrels not supported

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular#13193]
**I'm submitting a ...**  (check one with "x")
```
[* ] bug report => search github for a similar issue or PR before submitting
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In an index.ts I export a class in that folder.
When I import this file in another class, I get an error that the module could not be found:
````
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'app/core' in 'C:\Projects\temp\ng-cli-aot\src\app'
 @ ./src/app/app.module.ts 1:0-34
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi main
````

**Expected behavior**
In JIT this works fine, I expect the same with AOT.

**Minimal reproduction of the problem with instructions**
https://github.com/rolandoldengarm/ng-cli-aot

run "ng build --aot"

Even though I'm using Angular CLI, this is an Angular bug I believe.

* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by DzmitryShylovich** [comment]
@rolandoldengarm can't reproduce in angular 4. can you confirm and close the issue lease? thanks

**Comment by rolandoldengarm** [comment]
I'm not able to test in Angular 4. 
Plus I'm no longer using barrels.

Well not a lot of activity here anyway, let's close it.

**Comment by DzmitryShylovich** [comment]
> Plus I'm no longer using barrels.

👍

**Comment by battmanz** [comment]
@DzmitryShylovich I noticed you gave the thumbs up on not using barrels. Is it discouraged to use barrels?

**Comment by tytskyi** [comment]
@battmanz i think it was suggested to use them some time ago, but current guide says in the last sentence: 

> You can often achieve the same result using Angular modules instead.

https://angular.io/guide/glossary#barrel

**Comment by tytskyi** [comment]
update:

https://angular.io/guide/change-log

> **"Style Guide" with NgModules (2016-09-27)**
> StyleGuide explains recommended conventions for Angular modules (NgModule). Barrels now are far less useful and have been removed from the style guide; they remain valuable but are not a matter of Angular style.
