### ISSUE TITLE
Router lazy loading from http

### ISSUE THREAD

**Issue by carlosthe19916** [angular/angular#13195]
I'm not sure about this but I'd like to know if it's posible to load lazy modules using http like this:
`
{
 path: 'admin2',

 loadChildren:  () => System.get('http://localhost:8081/openfact').exportedFunction()        
}
`

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by carlosthe19916** [comment]
I'm so sorry for this...it was just a question. I'm going to move this question to stackoverflow.
