### ISSUE TITLE
Ability to create component instance with TestBed without HTML

### ISSUE THREAD

**Issue by wesleycho** [angular/angular#13197]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Sometimes I find myself testing pure business logic in components without wanting to render the HTML. Currently it renders completely, including DOM interaction & styles.

**Expected behavior**
I would like the ability to toggle off rendering into the DOM and render the pure JS component instance when configured.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
Currently running a suite of tests is expensive - I have ~350 tests in my work app, and it takes ~1 minute to compile & run them all. We could optimize some on other fronts, but I believe that the DOM rendering is partly to blame for testing performance in Angular 2. In the Angular 1 app we last worked on at my company, we run about 1800 tests in less time, and this app is also using TypeScript.

Strategies for improving test performance in core is much desired here, as that is one area that I believe can be refined.

**Please tell us about your environment:** macOS Sierra, Webpack 2, TypeScript 2

* **Angular version:** Angular 2.1.2

* **Browser:** Chrome 54, PhantomJS 2.1.7
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` = 4.5

**Comment by DzmitryShylovich** [comment]
```
TestBed.overrideComponent(Comp, {set: {template: ''}});
```

**Comment by laco0416** [comment]
Or you can `new YourComponent(someService)` with `inject([SomeService], (someService) => {})` and use the component instance.

**Comment by pnagar1705** [comment]
I am also facing the same issue. I am getting the Range Error. This is my code

```
describe('MileStoneTemp', () => {
    let component: MilestoneChartsComponent;
    let fixture: ComponentFixture<MilestoneChartsComponent>;
    beforeEach(async(()=>{
        TestBed.configureTestingModule({
            declarations:[MilestoneChartsComponent]
        }).compileComponents();
    }));

    beforeEach(async(()=>{
        try {
            TestBed.overrideComponent(MilestoneChartsComponent, {set: {template:''}});

            fixture = TestBed.createComponent(MilestoneChartsComponent);
        }
        catch(e) {

            console.log('error', e);
        }
    }));
    it('should create', () => {
        console.log('TEST');
    })
}); 
```
and this is my error on console.
`LOG: 'error', RangeError{ngDebugContext: DebugContext_{view: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ...}, nodeIndex: 0, nodeDef: Object{index: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, elDef: Object{index: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, elView: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ...}}, ngErrorLogger: function () { ... }}`
