### ISSUE TITLE
angular/compiler 2.2.4 compilation issue

### ISSUE THREAD

**Issue by JCThomas4214** [angular/angular#13204]
Hey guys,

I just updated to angular/compiler 2.2.4 and my ngc is no longer creating my application ngFactory files in the specified outGen folder. The last working version of angular/compiler on my stack was 2.1.2. I'm currently on node 6.9.1 and angular 2.2.4. You can check out my stack [here](https://github.com/projectSHAI/GOAT-stack) and follow the instructions below to reproduce the process

Thanks in advance!
JT 

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

initial angular/compiler compilation; app.module.ngFactory file not being created

**Expected behavior**

app.module.ngFactory file would be created along with component factories

**Minimal reproduction of the problem with instructions**

* clone https://github.com/projectSHAI/GOAT-stack
* run commands 
   * `npm install`
   * `gulp prod`
* ngc-aot folder should have node_module factories and app factories
   * app factories missing!!

**What is the motivation / use case for changing the behavior?**

cannot compile AoT

**Please tell us about your environment:**

MEAN stack

* **Angular version:** 2.2.4

* **Browser:** [all]
   * (not a dom issue)
 
* **Language:** [TypeScript 2.1.1]

* **Node (for AoT issues):** `node --version` =  6.9.1

**Comment by buu700** [comment]
I ran into this as well, after upgrading from Angular 2.2.4 with TypeScript 2.0.10 to Angular 2.3.0 with TypeScript 2.1.4.

**Comment by laco0416** [comment]
I guess it's caused by TypeScript 2.1. @JCThomas4214 Could you ensure whether it will also happen w/ TypeScript 2.0 ?

**Comment by JCThomas4214** [comment]
I just upped to 2.0.10 and it seems to be working now. Thanks @laco0416 ! Is it safe to assume this issue is cause typescript incompatibility?

**Comment by laco0416** [comment]
@JCThomas4214 maybe. 

@chuckjaz @alexeagle could you handle this issue? TS 2.1 is current stable version.

**Comment by laco0416** [comment]
probably this issue is duplicated w/ #12966

**Comment by actra-gschuster** [comment]
Typescript changed several internals with upgrading to 2.1, see the linked issue #12966

**Comment by ericmartinezr** [comment]
They're working on upgrading to ts2.1 https://github.com/angular/angular/pull/13294

**Comment by JCThomas4214** [comment]
@laco0416 @actra-gschuster Swell link mates! The issue is understandable. @ericmartinezr Angular 2.3.0 coupled with TS 2.0.10 is also throwing errors in my instance. Maybe 2.3.0 made progress towards TS 2.1 and lost 2.0 comparability? In any case, thanks for all the help! I'll be sticking with ng2.2.4 for now. 

Here's the error for reference: ng2.3.0 -> TS2.0.10

```
Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing
 the function or lambda with a reference to an exported function, resolving symbol AppModule in 
C:/.../.../.../.../.../GOAT-stack/app/app.module.ts, resolving symbol AppModule in C:/.../.../.../.../.../GOAT-
stack/app/app.module.ts
```

**Comment by actra-gschuster** [comment]
@JCThomas4214 That's not an issue with NG or TSC, it's just because you're not exporting the lambda function and thus NG is unable to resolve it statically.
E.g. instead of writing:
`let x: any = {
    abc: (foo: any) => foo.bar
};`
just write it as:
`
export const callback = (foo: any) => foo.bar;
let x: any = {
    abc: callback
};
`

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource was fixed https://github.com/angular/angular/issues/13204#issuecomment-265651316
can be closed
