### ISSUE TITLE
update Zone.js to 0.7.1

### ISSUE THREAD

**Issue by mp3por** [angular/angular#13202]
Currently the @angular/core project depends on 
```
"peerDependencies": {
    ....
    "zone.js": "^0.6.21"
},
```

In the [changelog of Zone.js project ](https://github.com/angular/zone.js/blob/master/CHANGELOG.md) I don't see any **breaking changes** only bug fixes and feature updates/additions. I believe it is reasonable to allow Angular users to use latest Zone.js.

**Comment by alexzuza** [comment]
Did you check 2.3.0 branch? https://github.com/angular/angular/blob/2.3.0-rc.0/modules/%40angular/core/package.json

**Comment by vicb** [comment]
It has been updated here: https://github.com/angular/angular/commit/ae26504e84ab06b5d76b2055083c75274efb6173
