### ISSUE TITLE
router.isActive and routerLinkActive to support more options 

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#13205]
Currently router.isActive and routerLinkActive support only one option `exact:boolean`.

When `exact = true`, isActive will return true if:

* queryParams match exactly
* the url has the same url segments with all "path" equal
* matrix params are ignored 

When `exact = false`, isActive will return true if:

* The queryParams of the containee is a subset of the queryParams of the container
* The url tree of the containee is a subtree of the url tree of the container
* Matrix params are ignored

We should replace the `exact=true` with a string type that supports more options:
* Include/exclude queryParams
* Include/exclude fragment
* Include/exclude matrix params

**Comment by artaommahe** [comment]
@vsavkin what about `intersection` option for `isActive` method?
I have this route
```ts
/:slug/chat
// /user1/chat
// /user2/chat
```
And need to check that current url is any of them. I would be cool to has `intersection` mode check like this
```ts
// current url /user1/chat
// route segments [ '/user1', 'chat' ]
router.isActive([ null, 'chat' ], { type: 'intersection' })  === true
```

more complex example route
```ts
// route /:param1/static1/:param2/static2

// url /123/static1/456/static2
router.isActive([ null, 'static1', null, 'static2' ], { type: 'intersection' })  === true
router.isActive([ null, null, 456, 'static2' ], { type: 'intersection' })  === true
router.isActive([ null, 'static1', 456 ], { type: 'intersection' })  === true
```

**Comment by doorman02** [comment]
What is the current state of this. Is it possible to ignore/exclude query parameters?

**Comment by DzmitryShylovich** [comment]
> ignore/exclude query parameters when routerLinkActiveOptions is set to exact?

nope

> What is the current state of this

it's will be a part of 4.0 release

**Comment by doorman02** [comment]
Ok thanks for the info, do you know when v4 will be released approx?

**Comment by DzmitryShylovich** [comment]
march-april

**Comment by doorman02** [comment]
Hi @DzmitryShylovich do you know if Include/exclude queryParams is included in the new v4 release?

**Comment by DzmitryShylovich** [comment]
@doorman02 nope, it wasn't included. there were more important tasks.

**Comment by doorman02** [comment]
Ok, thanks just checking :)

**Comment by overflew** [comment]
Can this also include similar handling for secondary routes?

E.g.: Some way that `.isActive('/profile/home')` would return true when on `'/profile/home(modal:confirmation)'`.

I have a plnkr + detail here: http://stackoverflow.com/questions/43647979/angular-router-should-isactive-identify-the-main-route-when-a-secondary-rou

**Comment by antonioasmoura** [comment]
News on this ?

**Comment by tytskyi** [comment]
@antonioasmoura nothing changed, docs: https://angular.io/api/router/RouterLinkActive

**Comment by devforey** [comment]
A workaround for ignoring the `queryParams` for `routerActive` with `exact: true` would be to create your own condition to check if the current URL without the query params is equal to the `routerLink`.

```HTML
<a routerLink="/my-link" [class.active]="isLinkActive('/my-link')"></a>
```

```TS
public isLinkActive(url: string): boolean {
  return (('/' + this.activatedRoute.snapshot.url.join('/')) === url);
}
```

**Comment by webdeveloperninja** [comment]
Im on angular 5 still have to use this hack?

**Comment by xMarkusSpringerx** [comment]
Any news about this topic? I would also need the possibility to set a route to active which some restrictings etc.
`
/store/ui/
/store/ui/new
/store/ui/news
/store/ui/friends
`
I would need sth like an ignore where I can set that the `/store/ui` should be ignored while evaluating the current active route.

**Comment by Saonela** [comment]
Still waiting... This is really annoying

**Comment by TobiasMalikowski** [comment]
+1

**Comment by cakeinpanic** [comment]
+1

**Comment by sirBlond** [comment]
Here's my workaround :) similar to what @devforey offered, but it uses `Router` class instead of `ActivatedRoute` so that it could work from child component.

```
public isLinkActive(url) {
    let charPos = this.router.url.indexOf('?');
    let cleanUrl = charPos !== -1 ? this.router.url.slice(0, charPos) : this.router.url;
    return (cleanUrl === url);
}
```

**Comment by gozeon** [comment]
see [doc](https://angular.io/api/router/Router)

```ts

@Component({
  selector: 'app-example',
  template: `
    <p>
      {{ router.isActive( any_path ) }}
    </p>
  `,
  styles: []
})
export class BreadcrumComponent {
  constructor(private router: Router) { }
}
...

```

**Comment by gozeon** [comment]
see [doc](https://angular.io/api/router/Router) & see [example](https://stackblitz.com/edit/angular-tsgp4k)

**Comment by tinyweasel** [comment]
Why isn't this sorted yet on 5? Seems like a fairly common use case.

**Comment by Halfist** [comment]
Was this added in Angular 6?

**Comment by SteamWind** [comment]
https://angular.io/api/router/RouterLinkActive#routerLinkActiveOptions
No...

**Comment by apolon23** [comment]
isLinkActive(url): boolean {
    const queryParamsIndex = this.router.url.indexOf('?');
    const baseUrl = queryParamsIndex === -1 ? this.router.url : this.router.url.slice(0, queryParamsIndex);
    return baseUrl === url;
  }

template
routerLinkActive="active"
          [class.active]="isLinkActive('/admin')"

Works for me

**Comment by caronalex** [comment]
@apolon23 

If you want to get urls like /blog or /blog/first-article, you should use this

```
isLinkActive(url): boolean {
    const queryParamsIndex = this.router.url.indexOf('?');
    const baseUrl = queryParamsIndex === -1 ? this.router.url : this.router.url.slice(0, queryParamsIndex);

    if(url.length > 1){ // if url != '/'
      return baseUrl.startsWith(url);
    }

    return baseUrl === url;

  }
```

**Comment by emolr** [comment]
https://github.com/angular/angular/issues/13205#issuecomment-392648730
> Or you could just use QueryParamsHandling="merge" which solves the problem

This is such a clean solution!

**Comment by BenRacicot** [comment]
Am I missing something or is there no solutions for fragments to trigger routerLinkActive?

**Comment by tinyweasel** [comment]
@BenRacicot no official one but the workarounds on this page work.

**Comment by mrshelly** [comment]
??
Thank you , For read this Email !
________________________________
发件人: Viacheslav <notifications@github.com>
发送时间: 2018年8月6日 11:46
收件人: angular/angular
抄送: Subscribed
主题: Re: [angular/angular] router.isActive and routerLinkActive to support more options (#13205)


isLinkActive(url): boolean {
const queryParamsIndex = this.router.url.indexOf('?');
const baseUrl = queryParamsIndex === -1 ? this.router.url : this.router.url.slice(0, queryParamsIndex);
return baseUrl === url;
}

template
routerLinkActive="active"
[class.active]="isLinkActive('/admin')"

Works for me

―

**Comment by ksuhiyp** [comment]
> Still waiting... This is really annoying

"The amateur software engineer is always in search of magic." - Grady Booch

**Comment by Splaktar** [comment]
Adding +1 comments and asking for a status update doesn't help and only risks this issue getting locked. If you are interested in this, please add your reaction to the original post. This way sorting issues by the most reactions or 👍🏼will be effective.

**Comment by kyoch1ro** [comment]
> Or you could just use QueryParamsHandling="merge" which solves the problem

Thanks! this solves my problem

**Comment by simeyla** [comment]
This gets scary with auxiliary routes!

    this.router.currentUrlTree.toString()
    "/crm/dashboard/customers/search/(searchResult:customer1@me.com/orders)"

     router.isActive(['blah', 'blah', 'doesnotexist']) is **TRUE**

In fact `router.isActive(...)` returns true for every single value I just tried.

**Comment by jdussouillez** [comment]
Any update on this ?

Thanks

**Comment by akshaytaywade** [comment]
any update on this it is annoying

**Comment by jmalStorm** [comment]
+1

**Comment by sviat9440** [comment]
Any news?

**Comment by sviat9440** [comment]
@petebacondarwin @gkalpak

**Comment by petebacondarwin** [comment]
@sviat9440 - this issue is being dealt with by @atscott in https://github.com/angular/angular/pull/40303
