### ISSUE TITLE
ViewContainerRef throws an error when it doesn't have views and indexOf is called

### ISSUE THREAD

**Issue by alex-okrushko** [angular/angular#13207]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When calling `ViewContainerRef` is empty and calling `viewContainerRef.indexOf(someViewRef)` results in
> Uncaught TypeError: Cannot read property 'indexOf' of undefined
>    at ViewContainerRef_.indexOf 

**Expected behavior**
I expect **-1** to be returned, same as for `array.indexOf()` when element is **not** found.

the actual error is because `this._element.nestedViews` are not validated to be present.
[actual code](https://github.com/angular/angular/blob/8f5dd1f11e6ca1888fdbd3231c06d6df00aba5cc/modules/%40angular/core/src/linker/view_container_ref.ts#L189,L191)
```typescript
indexOf(viewRef: ViewRef): number {
    return this._element.nestedViews.indexOf((<ViewRef_<any>>viewRef).internalView);
  }
```

this is what should be instead:
```typescript
indexOf(viewRef: ViewRef): number {
  const views = this._element.nestedViews;
  return isPresent(views) ? views.indexOf((<ViewRef_<any>>viewRef).internalView) : -1;
}
```
or
```typescript
indexOf(viewRef: ViewRef): number {
  return this.length ? views.indexOf((<ViewRef_<any>>viewRef).internalView) : -1;
}
```

**What is the motivation / use case for changing the behavior?**

I have a clean ViewContainer and I either `insert()` or `detach()` component based of some factors.
Initially the component is detached, I create component via
```typescript
let compRef = this.factoryResolver.resolveComponentFactory(MyComponent)
    .create(this.viewContainerRef.parentInjector);
```
**not** via 
```typescript
let compRef = this.viewContainerRef.createComponent(
    this.factoryResolver.resolveComponentFactory(MyComponent))
```
The latter automatically inserts component, which I don't need.
So I put the check to find the indexOf this component to determine if it should be removed.

* **Angular version:**
latest

**Comment by DzmitryShylovich** [comment]
@alex-okrushko was fixed here https://github.com/angular/angular/pull/13220
will be available in the next version
