### ISSUE TITLE
Pluggable NgModules with AoT compatibility

### ISSUE THREAD

**Issue by matt-psaltis** [angular/angular#13218]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I'll preface this by saying I *think* I have a basic understanding of *some* of the technical challenges here - I expect its a much bigger problem space. Essentially I'm trying to recreate our server side development process where teams work against agreed contracts and their code is consumed as optional plugins into the core system. I'm specifically interested in AoT compatibility here because of our observed application performance increases. 

**Current behavior**
When using AoT, Angular 2 currently supports monolithic applications where there is a clear compile time coherence between all NgModules.

**Expected behavior** (Expected is a bit strong here - desired?)
I am requesting techniques either through additional documentation or new supported features which allow for AoT compiled NgModules to be registered at runtime into the DI container. Furthermore, NgModules registered at runtime can be imported by other NgModules such that the exports of the module are available for use. Routers treat these as lazy loaded modules so routes become part of the route tree.

***Application composition:***
****Main application:****
- Built by core application team.
- Contains core application logic as well as shared vendor libraries.
- Contains call to bootstrapModuleFactory. Application boots from here.

****Plugin 1..n:****
- Built by auxiliary teams.
- Teams need to be able to compile the plugin for production without duplicating vendor code.
- Plugins register themselves with core application at runtime.
- Plugins should be able to add additional multi provider entries to existing multi providers.
- Plugins should be able to register additional forChild routes.

Currently using TypeScript and Webpack 2 with ngtools/webpack for AoT.

**Comment by alxhub** [comment]
I'm going to close this issue as I think a combination of evolutions since it was originally filed make it obsolete:

* Angular has shifted away from NgModules as an architectural piece.
* Microfrontends exist, and try to address the problem of multiple teams authoring and deploying independently.
* Angular has gotten more capable when it comes to lazy loading and providers.
