### ISSUE TITLE
Create benchmark for JIT compilation

### ISSUE THREAD

**Issue by tbosch** [angular/angular#13213]
We recently had a regression in JIT compilation, see https://github.com/angular/angular/issues/13146. The issue was a probably O(n^2) runtime in our book keeping logic (i.e. not in the template parsing). A reproduction can be found here: https://gist.github.com/simplifia/c9eb59e186083d2148561e2e9c22959d

**Comment by tbosch** [comment]
@chuckjaz could you check whether the regression is reproducible with this data?

**Comment by chuckjaz** [comment]
The following repo demonstrates the issue: https://github.com/chuckjaz/repro-13213

To see it execute `npm install && node_modules/.bin/ngc` in each directory.

**Comment by oliverjanik** [comment]
We're seeing a huge regression coming from rc.4 to 2.4.1.

**Comment by alxhub** [comment]
Closing as an obsolete internal issue. Ivy's architecture makes this kind of slowdown significantly less likely.
