### ISSUE TITLE
When routing in sub-module, error displays wrong module

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular#13214]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have setup a project with a number of child modules with child routes. However, I am trying to use a route param with the base component of one module (cellComponent), but if I route to `/cell/2` then I get the error:

> EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined

At best, this should be a more helpful 404 message? 

However, the main issue is that my LineModule renders instead.

**Expected behavior**
CellModule to render with the recognised params, or if there is an error with my code, there should be a clear self-explanatory message and no random other module rendering. 

**Minimal reproduction of the problem with instructions**

1. `git clone https://github.com/georgeedwards/ng-error-example`
2. `cd ng-error-example`
3. `npm i`
4. `ng serve`
5. Navigate to `http://localhost:4200/` - notice the home component works
6. Navigate to `http://localhost:4200/xyz` notice my CellComponent renders (even though it should be NoContentComponent)
7. Navigate to `http://localhost:4200/login` it works fine
8. Navigate to `http://localhost:4200/cell` - renders cell component 
9. 8. Navigate to `http://localhost:4200/cell/test` - renders Line component, on `http://localhost:4200/` with console error.

**What is the motivation / use case for changing the behavior?**
Aiding/Enabling development of multi-module routed applications which use route params.

**Please tell us about your environment:**
Windows 10 pro, VS Code

* **Angular version:** 2.2.1

* **Browser:** [all]

 
* **Language:** TypeScript 2.0

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by michalstepien** [comment]
It is rendering because you have : { path: ':dep/:id', component: LineComponent, pathMatch: 'full' }

**Comment by georgeedwards** [comment]
@michaelchiche Are you talking about behaviour no. 6?

**Comment by michalstepien** [comment]
9, number 6 is  : { path: ':dep', component: CellComponent, pathMatch: 'full' }

**Comment by georgeedwards** [comment]
@michalstepien But the `{ path: ':dep/:id', component: LineComponent, pathMatch: 'full' }` path is defined in my  LineModule, which is referenced in my root module, like this:
`{ path: 'line', loadChildren: './modules/line/line.module#LineModule', pathMatch: 'prefix'},` Shouldn't that mean the route defined is only called if it is prefixed with `/line/`?

**Comment by michalstepien** [comment]
For me is easier in this way:
app.module
```
const appRoutes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'home', component: HomeComponent },
  { path: 'cell/:dep', loadChildren: './modules/cell/cell.module#CellModule'},
  { path: 'cell', loadChildren: './modules/cell/cell.module#CellModule'},
  { path: 'login', loadChildren: './modules/login/login.module#LoginModule'},
  { path: 'line/:dep/:id', loadChildren: './modules/line/line.module#LineModule'},
  { path: '**', component: NoContentComponent },
];
```
line.routes
```
const lineRoutes: Routes = [
    { path: '', component: LineComponent }
];
```
cell.module
```
const cellRoutes: Routes = [
  { path: '', component: CellComponent }
];
```

**Comment by georgeedwards** [comment]
@michalstepien Is your solution not equivalent to mine? The issue is that I don't want a massive list of routes in my app.routes, so I would like to modularise them. If there is a reason why your solution should work differently to mine, then it would be good to know, otherwise, I think this is a bug.

**Comment by michalstepien** [comment]
you dont have to, you can do this:
```
const cellRoutes: Routes = [
  { path: '', pathMatch: 'full', children: [
    { path: '', component: CellComponent},
    { path: ':dep', component: CellComponent}
  ] }
];
```

**Comment by michalstepien** [comment]
Ahhh :) My fault. Why do you import:     
LoginModule,
 LineModule,
 CellModule

in app module?

**Comment by georgeedwards** [comment]
I thought that was how you contain independent modules, to make a single app?

**Comment by DzmitryShylovich** [comment]
provide a plunkr with repro

**Comment by georgeedwards** [comment]
@DzmitryShylovich my issue with plunkr is that you can't show routing, or console messages?

**Comment by georgeedwards** [comment]
@michalstepien I get the same result even if I don't import the modules to app.module. I have pushed a new update to the repo, if you look at that, and try the `http://localhost:4200/cell/test` route, It will load the line.component and throw an error...

**Comment by michalstepien** [comment]
@georgeedwards you repo before was correct, only you have to delete import from app

**Comment by michalstepien** [comment]
[ng-error-example-master.zip](https://github.com/angular/angular/files/629548/ng-error-example-master.zip)

**Comment by DzmitryShylovich** [comment]
@georgeedwards did u solve your issue?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed I think
