### ISSUE TITLE
Adding a div causes "Uncaught Error: Template parse errors"

### ISSUE THREAD

**Issue by gp187** [angular/angular#13217]
Angular: 2.2.1
Angular-cli:  1.0.0-beta.21
Browser: all
Language: Typescript

Generated app via `ng new`, added `d3 v4`.
Without any obvious cause, adding a `div` to a component template causes `Uncaught Error: Template parse errors` 

```typescript
import { Component, OnInit } from '@angular/core';
import * as d3 from 'd3';
import {log} from "util";

@Component({
  selector: 'app-selections',
  templateUrl: './selections.component.html',
  styleUrls: ['./selections.component.css']
})
export class SelectionsComponent implements OnInit {
  constructor() { }
  ngOnInit() {}
}
```

```html
<h1>
  Selections
</h1>
<p>

    <a href="#">About</a>
    <a href="#">Product</a>
    <a href="#">Contact</a>
  <a class="action" href="#">Buy now</a>

<em>asasa</em>
<div>xxxxx</div>
</p>
```
This is where it becomes weird: 

THIS WORKS:
```html
<div>xxxxx</div>
<p>
......
</p>
```

THIS DOESN'T WORK:
```html
<p>
<div>xxxxx</div>
......
</p>
```

**Comment by DzmitryShylovich** [comment]
The P element represents a paragraph. It cannot contain block-level elements (including P itself). You cannot nest a <div> element inside a <p> element according to the HTML standard.

**Comment by gp187** [comment]
Oh... OK. 
The stack trace provided no clues as to what happened or where to look. 
Thanks

**Comment by patrikx3** [comment]
why does it allow create angular custom elements but i cannot allow a ```<div>``` inside a ```<p>```
any browser allows it, angular 2 not?

**Comment by patrikx3** [comment]
besides angular2 itself is non valid html!
