### ISSUE TITLE
AoT compiler hardcodes node_modules folder into some factory import statements

### ISSUE THREAD

**Issue by marcovdb** [angular/angular#13216]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am including a third party component into my app. I am working on AoT compiling my app and noticing some unusual behavior where the third party component won't compile unless I install the @angular/common package into its own node_modules folder.

I went ahead and looked at the .ngfactory files for the component, and something seems off. Here's an excerpt from one of the files:

```
import * as import16 from '@angular/core/src/linker/view_container';
import * as import17 from '../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/common/src/directives/ng_for';
import * as import21 from '@angular/core/src/security';
import * as import22 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import23 from '../node_modules/@angular/common/src/directives/ng_switch.ngfactory';
import * as import24 from '@angular/common/src/directives/ng_if';
import * as import25 from '@angular/common/src/directives/ng_switch';
```

Why is it hardcoding the '../node_modules/' path for some of the statements, but not doing it for others, even though the modules are the same?

**Expected behavior**
I would expect this:
```
import * as import22 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import23 from '../node_modules/@angular/common/src/directives/ng_switch.ngfactory';
```

To be:

```
import * as import22 from '/@angular/common/src/directives/ng_if.ngfactory';
import * as import23 from '/@angular/common/src/directives/ng_switch.ngfactory';
```

**Minimal reproduction of the problem with instructions**
This is the component: https://github.com/PointInside/ng2-toastr
If you clone the GitHub repo and run the AoT compiler on it, you will reproduce the problem.

**What is the motivation / use case for changing the behavior?**
As it is, I need to manually pull the @angular/common package into the component node_modules. This also adds to the bundle size because the directives get included twice: once in my app, once in ng2-toastr.

**Please tell us about your environment:**
Windows 10 x64

* **Angular version:** 2.0.X
2.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
n/a
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by DzmitryShylovich** [comment]
@marcovdb is this still valid in v4?

**Comment by marcovdb** [comment]
I was actually just thinking about this last night after trying out v4.

Seems fixed in that version! Only 5 import statements now as compared to 20+ before.

```
import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from 'ng2-toastr/src/toast-container.component';
import * as import3 from '@angular/platform-browser';
import * as import4 from 'ng2-toastr/src/toast-options';
```

Impressive work!
