### ISSUE TITLE
Inheriting constructor with Jit mode fails when using closure compiler or property initializers

### ISSUE THREAD

**Issue by tbosch** [angular/angular#13211]
E.g. this should work:

```
@Injectable()
abstract class BaseService {
  constructor(private elementRef: ElementRef) {}
}

class MyService extends BaseService {}
```

However, closure compiler rewrites the constructor of `MyService` into the following way:
```
BaseService.apply(this, [].concat($jscomp.arrayFromIterable(arguments)));
```

Which does not match our regex in https://github.com/angular/angular/blob/master/modules/@angular/core/src/reflection/reflection_capabilities.ts#L66 to detect whether a class inherits the super constructor.

In addition, when using property initializers, the constructor also contains statements to set these, so the regex also does not match any more.

**Comment by tbosch** [comment]
Note: https://github.com/angular/angular/pull/15580 fixes this if the child class has at least one decorator (e.g. `@Injectable`)

**Comment by gkalpak** [comment]
(For reference, this is an updated link to where the RegExp is currently used: https://github.com/angular/angular/blob/67719f218560d94ff1accaeae67b857c6f89ec5a/packages/core/src/reflection/reflection_capabilities.ts#L64)

**Comment by alxhub** [comment]
This is likely not a problem with Ivy as a "bare" child class is no longer supported for other reasons.
