### ISSUE TITLE
Angular2 without npm (usage in node applications)

### ISSUE THREAD

**Issue by nehalist** [angular/angular#13227]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Within node applications (like Express or Sails) you need to make `node_modules` publicly accessible in order to run Angular2 - which is kinda bad, since you're exposing all the other npm stuff.
Additionally, it may the be case that TS compilation is done by a grunt task. This is currently really hard to achieve and very hacky.

**Expected behavior**
Either publish a compiled version to Bower (so usage would be same as for AngularJS) or provide guides on how to use angular without npm and take care of TS compilation yourself.

**Comment by alxhub** [comment]
Many tools and methods exist to bundle javascript applications for deployment at runtime. `node_modules` does not have to be deployed with a properly configured application bundle.
