### ISSUE TITLE
http Response headers incomplete ?

### ISSUE THREAD

**Issue by vfedoriv** [angular/angular#13226]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If I get Response from http request, response.headers contain only "application/json; charset=utf-8"
````
import { Component, OnInit } from '@angular/core';
import {Http} from "@angular/http";

@Component({
  selector: 'app-simple-test',
  templateUrl: './simple-test.component.html',
  styleUrls: ['./simple-test.component.css']
})
export class SimpleTestComponent implements OnInit {

  private test_url = "http://www.mocky.io/v2/5843ecc6100000da1c1a5734";
  private output_string ="";

  constructor(private http: Http) { }

  ngOnInit() {
    this.http.get(this.test_url)
      .subscribe(response => {
        this.output_string = "response: " + response + "; response headers values: " + response.headers.values();
      }, (error) => {
        console.log(error);
      });
  }
}
````
![headers_test](https://cloud.githubusercontent.com/assets/11440242/20866595/0984960a-ba39-11e6-9f41-5907de133b1b.png)

**Expected behavior**
Expected: get list all headers from http response

**Minimal reproduction of the problem with instructions**

I create link with REST response there: http://www.mocky.io/v2/5843ecc6100000da1c1a5734
(with added  headers "Access-Control-Allow-Origin: *" and "Errors: error message")
and create test
Plunker link: http://plnkr.co/edit/vJD4Zuo0MxKAdb4nA1Xl?p=preview

**What is the motivation / use case for changing the behavior?**

parsing response headers from backend application

**Please tell us about your environment:**

Win10 64bit, npm 4.0.3

* **Angular version:** 2.2.X

* **Browser:** [ Chrome 54 | Firefox 50 ]

 
* **Language:** [TypeScript 2.0.10]

* **Node (for AoT issues):** `node --version` =   7.2.0

**Comment by DzmitryShylovich** [comment]
Can u send the same request using plain xhr and compare results?

**Comment by vfedoriv** [comment]
`````
    var xhr = new XMLHttpRequest();
    xhr.open('GET', 'http://www.mocky.io/v2/5843ecc6100000da1c1a5734', false);
    xhr.send();
    this.output_string2 = "XMLHttpRequest().getAllResponseHeaders() " + xhr.getAllResponseHeaders();
`````
Result: XMLHttpRequest().getAllResponseHeaders() Content-Type: application/json; charset=utf-8 

But why ???

**Comment by vfedoriv** [comment]
Oh, I found problem: it's CORS.
Need add "Access-Control-Request-Headers" with list of headers in response headers.

**Comment by vfedoriv** [comment]
Thanks for you question - it's helped me to find answer.
