### ISSUE TITLE
ngAria module in Angular 2

### ISSUE THREAD

**Issue by tingtingren** [angular/angular#13229]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

1. using the following command to download the anguar-aria under node_modules folder
   npm install --save angular-aria 
2. adding ngAria as a dependency using the code below in root module, there is red curly lines underneath 'angular-aria', error message in webstorm IDE saying 'TS2307: can't find module 'angular-aria'
   import { ngAria } from 'angular-aria';   
3. running the app in Chrome, there is error in console log:
angular-aria.js:61 Uncaught TypeError: Cannot read property 'module' of undefined(…)(anonymous function) @ angular-aria.js:61(anonymous function) @ angular-aria.js:407

**Expected behavior**

we should be able to find 'angular-aria' as a module in root module and there should NOT be any console errors saying 'Cannot read property 'module' of undefined' in angular-aria.js file
**Minimal reproduction of the problem with instructions**
see current behavior

**What is the motivation / use case for changing the behavior?**

we should be able to use ngAria module in angular 2

**Please tell us about your environment:**

Operating system: using windows virtual machine in Mac
IDE: Webstorm
package manager: npm
* **Angular version:** 2.0.X

* **Browser:** [ Chrome XX  ]

 
* **Language:** [TypeScript X.X]

* **Node (for AoT issues):** `node --version` = 7.2.0

**Comment by DzmitryShylovich** [comment]
there's no such module

related to https://github.com/angular/angular/issues/9121

**Comment by tingtingren** [comment]
this is the angular official website about the ngAria:
https://docs.angularjs.org/api/ngAria

**Comment by DzmitryShylovich** [comment]
it's for angular1

**Comment by alxhub** [comment]
Closing as `ngAria` is an Angular v1 module.
