### ISSUE TITLE
AOT - emitDecoratorMetadata no longer working

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular#13231]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using [cerialize](https://github.com/weichx/cerialize), which is a plugin that generates strong-typed TypeScript objects based on JSON objects. It is using decorators to be able to know the property types (as this information is of course gone runtime).

This is working fine when using JIT. However, in AOT this is no longer working. I am not an expert, but I believe that the emitDecoratorMetadata flag is no longer working; i.e. the decorator metadata is not emitted such that cerialize can use it.

I have also tried [TypedJSON](https://github.com/JohnWhiteTB/TypedJSON), but the same problem occurs.

**Expected behavior**
I would expect the same behavior in AOT compared to JIT.

**What is the motivation / use case for changing the behavior?**
When using API's, you want to be able to create strong-typed objects to add business logic to data coming from an API.
It is working in JIT, so why not in AOT?

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.2.1

* **Browser:** 
all
 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by chuckjaz** [comment]
@rolandoldengarm Can you create a repository that demonstrates this issue?

**Comment by rolandoldengarm** [comment]
I've found out that it's not an Angular core issue.
I am using Angular-CLI which strips off the decorators in AOT build. See this issue: https://github.com/angular/angular-cli/issues/2799
So I'll close this one.

**Comment by mustafaekim** [comment]
hi @rolandoldengarm I wonder if you could make it work Angular 4 AOT with TypedJSON? If you did, can you share with me your configuration? Thanks!

**Comment by rolandoldengarm** [comment]
@mustafaekim nah we've removed TypedJSON. Our solution is this:

```
export class Serializable {
  constructor(json?: any) {
    if (json) {
      Object.assign(this, json);
    }
  }
}
```

And then every domain object inherits from Serializable :)
