### ISSUE TITLE
Angular Compiler issue with third-party NPM packages

### ISSUE THREAD

**Issue by nickkenens** [angular/angular#13233]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When importing third-party module into your code like the following example:
`import * as sha from "js-sha256"`

The first issue I stumbled upon was when trying to build the code to be run as a npm package and import it into other project.

I couldn't get past the `ngc` step, so I went on a search & found the following solution to get past the `ngc` compiling error. Since the `js-sha256` package didn't have any `@types/js-sha256` package associated with it, this fixed the issue, for now:

Adding a `typings.d.ts` file in the /src folder with the following line:
`declare module 'js-sha256'`

This solved the compiler issue and the code gets built.

BUT, here's the kicker:
After importing the package into another project, like any other third-party npm package, I get the following error:
`Uncaught Error: Cannot find module "js-sha256"`

And the cycle continues.

**Expected behavior**
`ngc` compiler compiling with third-party package code included in /dist or /aot folder.

**Minimal reproduction of the problem with instructions**
1. Make new angular module with template: https://github.com/driftyco/ionic-module-template
2. Add a third party package to it that doesn't have any typings: `npm install --save js-sha256`
3. Try compiling code to npm package using: `npm run build` script within template

**What is the motivation / use case for changing the behavior?**
We're currently working on a big project that requires several NgModules to be working together. All of these modules include third-party NPM packages that need to be compiled in order to re-use the NgModules as npm packages in later projects.

**Please tell us about your environment:**
Operating System: macOS Sierra
Package Manager: npm
IDE: Webstorm

* **Angular version:** 2.0.X
Overall compiler issue as far as I'm aware.

* **Browser:**
all
 
* **Language:**
all

* **Node (for AoT issues):** `node --version` =  v4.5.0

**Comment by DzmitryShylovich** [comment]
Don't think it's angular issue. Typescript requires type definitions for 3rd party modules for compilation.

**Comment by nickkenens** [comment]
@DzmitryShylovich I've tried the `require` approach without success.

I'll be trying a different package and see if that makes a difference.

Thanks for the speedy response.

**Comment by alxhub** [comment]
This is a Typescript concern, so closing this issue.

**Comment by nickkenens** [comment]
@alxhub Any recommendations on how to fix this issue?

I completely understand that this is a TypeScript issue, but since you guys work so closely with TypeScript maybe you have an answer or a clue as to why this is happening?
