### ISSUE TITLE
Form Validation Strange Behavior when "Name" attribute is duplicated

### ISSUE THREAD

**Issue by spederiva** [angular/angular#13236]
**Current behavior**
Within a form which (by error) contains two inputs fields with the same "name" attribute value (firstName is this case) Angular binds all the validations for both fields

**Expected behavior**
I expected to throw an error or apply the validation only for one field

**Minimal reproduction of the problem with instructions**
1) Go to: [Plnkr Example Code](https://plnkr.co/edit/iejyf2KtNhgl9PxQTbGk?p=preview)
2) The first field has only "required" attribute, so enter only ONE character
3) See that "valid" property is still _false_
4) Enter another two characters
5) Now "valid" is true because the second fields has also "minlength" validation

**What is the motivation / use case for changing the behavior?**
I think it's very confusing and there is almost no way to catch the problem in a big form

**Please tell us about your environment:**
All

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** all

**Comment by alxhub** [comment]
Having two controls with the same `name` is not supported.

**Comment by spederiva** [comment]
Exactly. If two controls with the same "name" is not supported, an error should be thrown
