### ISSUE TITLE
Disable inputfield on valid

### ISSUE THREAD

**Issue by nusje2000** [angular/angular#13239]
I'm submitting a bug report,
I was using angular forms and was just testing some things when I came across a little problem, I made an select field and gave the following attribute: [disabled]="select.valid" in combination with [required]. now when I select something so the select is valid, my current tab crashes and the OS I'm using becomes unusable until I press ctrl + alt + del. I tested it on Debian and Windows using chrome, Firefox and IE. I expected that the input just would become unavailable when something was selected. 

Plunker:
http://plnkr.co/edit/LOHt4ZoHYjs2agFisvZR?p=info
There is an extra closing div in hero-form.component.html, just remove it to reproduce the bug, the tab will become unavailable bat the OS and Browser will stay usable, to see it fully working you need to run it directly without using online sandboxes.

Angular: 2.0.1
Browser: Chrome, IE, Firefox
Language: Typescript Compiler 1.5.3
Node: 6.9.1

**Comment by Skahrz** [comment]
I m able to reproduce the problem, event without putting required attribute on the field. But, considering your pluncker the #power valid property is always true for me. Is that normal ?

**Comment by Skahrz** [comment]
It seems that change detection is looping and looping again :

http://plnkr.co/edit/pqeAVOWbLZuzD4wESzxz?p=preview

I don't know why, but something changes when you bind your property... I'll continue investigating

**Comment by Skahrz** [comment]
I've got the point.

In fact, when you pass your power.valid to true, it should pass your disable property to true. But when disable property is true, your field pass to an invalid state. And here begins the loop. This way, your browser is blocking.

You can see that in the console of the following plunkr : 

http://plnkr.co/edit/pqeAVOWbLZuzD4wESzxz?p=preview

It doesn't seem to be an angular 2 problem, but a specific case.

**Comment by alxhub** [comment]
Closing as WAI.
