### ISSUE TITLE
Provide better IDs for interpolation strings in ng-xi18n output

### ISSUE THREAD

**Issue by Luftzig** [angular/angular#13237]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, I have a template similar to:
     ```<p i18n>I'm template number {{number}}</p>```

Then the output message will have a source tag similar to:
    ```<source>I'm template number <x id="INTERPOLATION"/></source>```

This is confusing for translators, as they will have to guess what the interpolations are standing in for, and should remember the correct order.

**Expected behavior**

Suggested behaviour is to either use the interpolation content as the ID, eg:
    ```<source>I'm template number <x id="number"/></source>```

Or include it in another tag, for example:
    ```<source>I'm template number <x id="INTERPOLATION" original="number"/></source>```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
We want the ng-xi18n tool to produce messages that will be easier to translators to work with.

**Please tell us about your environment:**

* **Angular version:** 2.2.1

**Comment by vicb** [comment]
@Luftzig there is a way to do it: `<span i18n>Hello {{your.name // i18n-ph(PLACEHOLDER_NAME)}}</span>`. It needs doc (see ref to angular/angular.io above).
