### ISSUE TITLE
Memory leak on long running Ng2 app

### ISSUE THREAD

**Issue by bencameron00** [angular/angular#13235]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

We have an Ng2 app which is designed to running in the browser for an indefinite time. There will be no interaction from the user as the app is just a data display applicaton. It is constantly sent data updates through a signalr connection.
There is very little logic in the Ng2 application and the data is just bound to the UI.
All emitters and observables are cleaned up regularly. This was on advice gained from StackOverflow where I have posted and researched this issue.
I am running 2.3.0(rc0).

We have noticed that if we leave the app running for about 12 hours Chrome suffers from an out of memory issue, the same happens in IE11.

In the UI we are using *ngIfs and Hidden to show and hide data.
Components are implementing ngOnDestroy in which emitters are unsubscribed.

**Expected behavior**
The application should run indefinitely without breaking due to an out of memory issue.
Are there any known memory issues in Ng2?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
To confirm if there is a memory leak in Ng2 or to find out if this is due to our implementation. 

**Please tell us about your environment:**
Windows 10, Ng 2.3.0(rc0), webpack dev server, signalr.

* **Angular version:** 2.0.X
2.3.0(rc0)

* **Browser:** 
Chrome Version 54.0.2840.99 m
IE 11
 
* **Language:** 
ES5

* **Node (for AoT issues):** `node --version`
Node 7.0.0

**Comment by DzmitryShylovich** [comment]
Pls add a minimal repro.

**Comment by vicb** [comment]
There is nothing we can do to help without a repro. Please re-open when you have a small repro available. Thanks !

**Comment by bencameron00** [comment]
Hi
On further testing we don't think this is a Ng2 issue. It looks like the leak is in a third party product that we are using, PrimeNg. https://github.com/primefaces/primeng/issues/1496 
Thank you for considering this however.

**Comment by vicb** [comment]
Thanks for reporting !
