### ISSUE TITLE
Dynamic routing

### ISSUE THREAD

**Issue by bulentrahimkazanci** [angular/angular#13232]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In current structure, I manually add routes to route config array.

```
const routes: Routes = [
    { path: '', redirectTo: '/home', pathMatch: 'full' },
    { path: 'login', component: LoginPage},
    { path: 'pages/workflowpools', component: WorkflowPools},
    { path: 'pages/workflowpools/pool', component: WorkflowPoolComponent }
    { path: 'pages/employeelist/:branchCode', component: EmployeeListComponent},
    { path: 'pages/branchlist', component: BranchListComponent}
];
```

**Expected behavior**
I fetch menu definitions from rest  as 
```
routingDefinitions = [
        { "path" : "pages/workflowpools", "component" : "WorkflowPools"},
        { "path" : "pages/workflowpools/pool", "component" : "WorkflowPoolComponent"},
        ...
]

```

What I would like to do is to register fetched routes to current config without defining them manually. While doing that, I cannot convert string value of component type that I fetched from rest (ex: 'EmployeeListComponent') to class type of it.

Is there any way to implement dynamic route registration?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
angular/core 2.1.1
angular/router 3.1.1

* **Browser:** [all]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` = 4.4.5

**Comment by DzmitryShylovich** [comment]
> Is there any way to implement dynamic route registration?

`Router.resetConfig(routes)`

**Comment by bulentrahimkazanci** [comment]
@DzmitryShylovich  I cannot create item in routes array because It is provided as string name of component from rest; therefore, I cannot create type of component that I want.

**Comment by DzmitryShylovich** [comment]
Component name is not enough for angular to resolve the corresponding component (there might be multiple components with the same name).  You have to map name => component yourself.

**Comment by bulentrahimkazanci** [comment]
If I guarantee that component names are unique, is there another way to do it without mapping?

**Comment by vsavkin** [comment]
The router doesn't actually need component types. It needs component factories.

Component factories are created when you compile ng modules. (You can read more about it in the post I wrote on this topic: https://blog.nrwl.io/essential-angular-2-compilation-cfbebf9bb6e4#.4tb01kpp5.) The interface responsible for providing the factories is ComponentFactoryResolver, which takes a type, not a string. So you'll have to create the mapping of strings to types.

It depends on your setup, but in theory you could create a provider creating this mapping automatically.

**Comment by DzmitryShylovich** [comment]
@vicb support request. can be closed.
