### ISSUE TITLE
Meteor, zones and appRef.tick being called too often

### ISSUE THREAD

**Issue by staeke** [angular/angular#13234]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In short: ```appRef.tick()``` is called too often in Meteor apps.

Longer:
First, my use case is Meteor apps using Angular 2. Now, before moving on, let's look at how zones are handled today in Meteor and how they're recommended to be handled (as it seems) by zone.js. 

One core idea of zone.js is to "preserve" zones over asynchronous calls. Autopatching generally works, but for WebSockets, it's a little tough, as ```send``` can be called from different zones. Which zone should the ```onmessage``` callback come on? The zone.js answer (as of now at least) is where the WebSocket was created. I'd say that this means that any layer making use of a WebSocket to serve multiple zones, must be zone aware and implement the zone re-entrance on a higher level.

In Meteor, this is exactly what happens. The data layer opens a WebSocket before angular bootstrap (there is no supported way of changing that). Events on this socket will subsequently lead to data being propagated through observables (and reactive tracker functions) to listeners in the app. Potentially multiple Angular apps could be listening (or non-Angular apps). This propagation, by the way, is all handled in the event loop that started with the ```onmessage``` callback from the WebSocket.  

Now, the way Meteor has approached zones, is just like above, in higher layers - the actual tracker functions and observables. This means that one ```onmessage``` callback could lead to data changes that could cause a LOT of listener callbacks - each one being run in the Angular zone (or a child thereof). Now, we're getting to the problem...as all these callbacks are run principally as a single:

```
angularZone.run(() => dataListener(data));
```

...the angular's main zone's ```onMicrotaskEmpty``` will yield a LOT of times, leading to ```appRef.tick()``` calls being done excessively. Unless you implement ```onPush``` change detection strategies all over the place, performance clearly suffers.

**Expected behavior**
I would wish for either:
- a programmatic fix in Angular
- a clear and working policy/recommendation on how to handle these scenarios, and "who" should handle it

Ways I can see this could be fixed:
##### "Throttle" appRef.tick in Angular
Do something like:

```typescript
let pendingTick = false;
ngZone.onMicrotaskEmpty.subscribe(() => {
  pendingTick = true;
  setImmediate(() => {
    if (pendingTick) {
      pendingTick = false;
      appRef.tick();
    }
  })
})
```
I purposely wrote ```setImmediate``` although it's unclear what that would be. Maybe some new callback on the root zone, e.g. ```rootZone.onTurnDone```, maybe a polyfill for ```setImmediate```, maybe ```setTimeout(..., 0)```. 

##### Register all interested zones in Meteor's callback
Something like (pseudo code)

```typescript
// On Angular bootstrap (should be able to handle multiple zones, but simplified here)
registerZoneInMeteor();

// In Meteor (or patching lib)
function registerZoneInMeteor() {
  this.mainZone = Zone.current;
}
...
onMeteorWebSocketData(data) {
  this.mainZone.run(() => {
    runAllListeners(data);
  })
}
```

This way we would wrap all listener callback's in a root call on Angular's zone and thus the microtask queue wouldn't be empty. IMO it kind of smells though, as the whole main zone thing is because inner mechanisms of Angular has leaked into this design.

##### "Smarter" auto patching of WebSocket by zone.js
As outlined above, it isn't obvious how to patch WebSockets. One thing that COULD be done is to check zones on ```send```. If it isn't the original zone, add it to the list of zones that will contain the callback. Thus the stack trace in the ```onmessage``` callback would look something like

```
...
WebSocket_onmessageHandler
zone.run <-- later zone that called send
zone.run <-- original zone
zonejs.WebSocket_onmessagePatched
(native)
```

Although this would just "solve" things, it has at least two downsides that I can see:
- if new zones surface and old zones are no longer used, there is no automatic way of disposing them in zone.js - leading to garbage zones and longer and longer stacks. By just "changing" the zone on sends, we wouldn't fix the original problem.
- If zone.js idea is to preserve the zone, and we have a conflict between zones, it seems a little arbitrary to run them after each other in the same stack. Again - that's kind of a fix just to mitigate Angular's use of ```onMicrotaskEmpty```. 

**What is the motivation / use case for changing the behavior?**
Performance

**Please tell us about your environment:**
Meteor 1.4.2
npm package: angular2-meteor@0.5.6

**Angular version:**
Angular 2.1.2

**Comment by DzmitryShylovich** [comment]
I would say it's zonejs/meteor issue

**Comment by staeke** [comment]
@DzmitryShylovich Motivation? What do you think about the downsides in the arguments I outlined with solving it in Meteor/zone.js? Do you agree? not agree? Do you see other ways of solving it?

**Comment by staeke** [comment]
I might add that I personally think the most sensible thing is to solve it in Angular.

**Comment by mhevery** [comment]
This is working as intended. To fix this run Meteor outside the angular zone.

**Comment by staeke** [comment]
@mhevery That’s currently unsupported by Meteor as you can’t run scripts before platform setup (unleas you hack/fork etc.)
