### ISSUE TITLE
Image rendering jitter.

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular#13247]
First time around when the images toggle, there is a quick jumpy refresh, after this the image transition seem to be smooth.

![jitter](https://cloud.githubusercontent.com/assets/439226/20899152/353cba20-baf7-11e6-8ab2-731c3c3dbf43.gif)

```js
import { Component } from '@angular/core';

@Component({
  selector: 'app-toggle',
  template: `
    <div class="flex items-center">
      <img *ngIf="state" src="../../assets/lights-on.png" class="self-center p1">
      <img *ngIf="!state" src="../../assets/lights-off.png" class="self-center p1">
      <button (click)="onToggleState()" class="btn btn-primary caps">{{label}}</button>
    </div>
  `,
  styles: []
})
export class ToggleComponent {
  label = "Off";
  state = false;

  onToggleState() {
    this.state = !this.state;
    this.label = this.state ? "On" : "Off";
  }
```

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1. See code above.
2. Refresh browser.
3. Click button to toggle between same size images.

**Expected behavior**
Smooth image switching, ng2 should be smart enough to use current image size.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Avoid crappy user experience.

**Please tell us about your environment:**
MacOs 

* **Angular version:** 2.0.X
2.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
Using chrome.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by alxhub** [comment]
If I had to guess, this is the browser actually loading the second image when the `<img>` tag is first added to the DOM. If you style it with the correct width/height, it should maintain its size.

**Comment by zoechi** [comment]
Can you try `[hidden]="!state"` instead of `*ngIf="state"`?

**Comment by rajinder-yadav** [comment]
@zbjornson awesome suggestion, smooth & beautiful, thanks!
