### ISSUE TITLE
[2.2.1] ngOnChanges() doesn't get called when an @Input() property is changed

### ISSUE THREAD

**Issue by skateXY** [angular/angular#13245]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm trying to change a child's @Input() property using an @ViewChild instance in the parent,
and the method ngOnChanges() doesn't get called.

Changing "currentVal" in the parent will trigger an ngOnChanges() on the child.

Also, if I update "this.siderbarInstance.testVal" from the parent, the change will appear in DOM,
but  ngOnChanges() won't get called.

**Expected behavior**

The method ngOnChanges() should be called every time when a property is changed, and I should be able to get the changes.
If this shouldn't be possible then angular should throw an error, because silent fail isn't an accepted behaviour.

**Minimal reproduction of the problem with instructions**

@Component({
  selector: 'my-app',
  template: `<div class="wrapper"> <my-sidebar [testVal]="currentVal"></my-sidebar></div>`,
  providers: [AppService]
})

export class AppComponent  { 

  @ViewChild(SidebarComponent) siderbarInstance: SidebarComponent;
  public currentVal : string;

  public onInnerClick(): void {
        this.siderbarInstance.testVal = "I clicked";
  }

}

@Component({
  selector: 'my-sidebar',
  template: `<div class="sidebar"> Current child's value: {{testVal}} </div>`,
})

export class SidebarComponent implements OnInit, OnChanges, DoCheck {
 
    @Input() testVal : string;

    public ngOnChanges(): void{
        console.log(this.testVal);
    }
}

**What is the motivation / use case for changing the behavior?**

I'm just learning angular2 and ngOnChanges() doesn't seem reliable if it's not called every time
when a change occurs. 

**Please tell us about your environment:**

Windows 10, Visual Studio Code, npm

* **Angular version:** 2.0.X

[2.2.1]

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, IE11.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 2.0.1

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by skateXY** [comment]
I thought you can't do in constructor only, as the siderbarInstance isn't created yet, but then nothing breaks, and the changes are visible in the DOM.

Maybe it should throw then? Or...

**Comment by alxhub** [comment]
This is WAI.

Change detection does not check `@Input`s, it checks _bindings_. So `ngOnChanges` is only called when a `binding` causes an `@Input` to change.

Try making the `@Input` a getter/setter.

**Comment by im-so-handsome** [comment]
Hi @alxhub

my component like this:

```typescript
@Component({
  selector: 'little-tour',
  template: ` {{ prettyText }}  `
})
export class LittleTourComponent {
  @Input() text = '';
  prettyText = '';
  ngOnChanges(e) {
    this.prettyText = 'pretty' + e.text ;
  }
}
```

This works fine after compiled and use in other component.
But my question is, in this case, I am not able to use `fixture.detectChanges()` in component tests. 

For example:
```typescript
// in async test:
fixture.componentInstance.text = 'something';
fixture.detectChanges();
expect(fixture.debugElement.nativeElement.innerText).toEqual('prettysomething')
// ERROR
```

Obviously it does not trigger `ngOnChanges()` consequently. 

Another example:
```typescript
// in async test:
fixture.componentInstance.prettyText = 'something';
fixture.detectChanges();
expect(fixture.debugElement.nativeElement.innerText).toEqual('prettysomething')
// SUCCESS
```

My question is do you have any suggestions that can make the first example work in test without adding additional code?

Thanks a lot.
