### ISSUE TITLE
ng-xi18n Error: Unexpected value 'ServicesModule' imported by the module 'LoginModule'

### ISSUE THREAD

**Issue by bahodirk** [angular/angular#13240]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

I have LoginModule

```
import { ServicesModule } from '@myservices/service';
import { ControlsModule } from '@mycontrols/controls';

@NgModule({
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    LOGIN_ROUTES,
    ServicesModule,
    ControlsModule
  ],
  declarations: [
    LoginComponent
  ],
  providers: [
    LOGIN_PROVIDERS
  ],
  exports: [
    LoginComponent
  ]
})
```
export class LoginModule { }
ServicesModule and ControlsModule are imported from another project (private npm repository).

AppModule looks as following:

```
@NgModule({
  imports: [
    BrowserModule,
    HttpModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    ServicesModule,
    ControlsModule,
    ROUTES,
    LoginModule,
    SomeAnoterLocalModule
  ],
  declarations: [
    AppComponent
  ],
  providers: [
    { provide: LocationStrategy, useClass: HashLocationStrategy }
  ],
  bootstrap: [AppComponent]
})
```
I see that I am importing ServicesModule and ControlsModule both in LoginModule and AppModule, but otherwise it is not working.

When I run the project, everything works fine, no problem. However, when I run ng-xi18n to extract translation texts, I am getting an error:

Error: Unexpected value 'ServicesModule' imported by the module 'LoginModule'
I have tried to remove ServicesModule and ControlsModule from the "child" module (LoginModule) and keep import in AppModule, in that case I am getting an error that tags (selector) from ServicesModule and ControlsModule are not recognized.

The ServiceModule

```
@NgModule({
  imports: [
    HttpModule,
    RouterModule
  ],
  providers: [
    SERVICES_PROVIDERS
  ]
})
```
export class ServicesModule { }
It is only collection of services (providers).

Please tell us about your environment:

Angular version: 2.2.3
Browser: [Chrome Latest ]
Node: 6.9.1
TypeScript: 2.0.3

**Comment by alxhub** [comment]
The private repository needs to publish `metadata.json` files for the modules. Compile it with `ngc` not `tsc` in order to do that. See `@ngrx/store` for an example of how to do this.
