### ISSUE TITLE
Form data is empty when calling http.post() with ContentType header

### ISSUE THREAD

**Issue by maxbellec** [angular/angular#13241]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```typescript
var fd = new FormData();
fd.append('field', 'value');

// fires an empty request (in Chrome Developer Tools)
this.http.post('http://google.com', fd,
{headers: new Headers({'Content-Type': 'application/x-www-form-urlencoded'}))
 .subscribe(() => console.log("request done with success"));
```

The request data is empty (as seen in Chrome Developer Tools).

**Expected behavior**

The request should not be empty (and have the same body as if the Content-Type wasn't changed).

**Minimal reproduction of the problem with instructions**

**Plunker** with two requests, one valid (Content-Type wasn't changed), one failing (Content-Type was changed)
http://plnkr.co/edit/7PEsXmJ8dLN3CYx7hQaE?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0

* **Browser:** Chrome Latest

 
* **Language:** TypeScript

**Comment by Skahrz** [comment]
I had the same issue using fetch one time, I managed to workaround using the following function :

```
getFormUrlEncoded(toConvert) {
		const formBody = [];
		for (const property in toConvert) {
			const encodedKey = encodeURIComponent(property);
			const encodedValue = encodeURIComponent(toConvert[property]);
			formBody.push(encodedKey + '=' + encodedValue);
		}
		return formBody.join('&');
	}
```

And calling it this way :

```
const field = {field: 'value'};
     // failed request
    this.http.post('http://google2.com', this.getFormUrlEncoded(field),
    {headers: new Headers({'Content-Type': 'application/x-www-form-urlencoded'}))
     .subscribe(() => console.log("request done with success"));
```

I'm not sure this is a durable solution, but it might help you in short time periods :

http://plnkr.co/edit/fNhsjvusWn8mVfweMY9l?p=info

**Comment by vicb** [comment]
Seems like `FormData` support in not implemented in the http module yet. Anybody wants to submit a PR ?

**Comment by DzmitryShylovich** [comment]
Afaik http does support `FormData` https://github.com/angular/angular/blob/14ee75924b6ae770115f7f260d720efa8bfb576a/modules/%40angular/http/src/interfaces.ts#L70

**Comment by vicb** [comment]
Right, the issue is that it does not get converted to the `application/x-www-form-urlencoded` form. 
Anybody knows if there is an explicit conversion in angular1 ?

**Comment by DzmitryShylovich** [comment]
It work with `application/x-www-form-urlencoded;charset=UTF-8` instead of `application/x-www-form-urlencoded`

**Comment by vicb** [comment]
@DzmitryShylovich what works ? where ?

**Comment by DzmitryShylovich** [comment]
In repro http://plnkr.co/edit/hrP92MZCR6D78e8SLwDZ?p=info.
Just need to change `application/x-www-form-urlencoded` => `application/x-www-form-urlencoded;charset=UTF-8`

**Comment by vicb** [comment]
I think that the fix would be to convert the `FormData` to a `string` (code given above) in https://github.com/angular/angular/blob/13b41bd6310dd8c10d76deef45f157e0527b1707/modules/%40angular/http/src/body.ts#L42 and add a test.

**Comment by alxhub** [comment]
After consideration, I'm considering this a feature request, not a bug.

`FormData` is exclusively designed for encoding `multipart/form-data`. It's not compatible with `application/x-www-form-urlencoded` - `URLSearchParams` is a better (supported) body type for that encoding.

It would be a new feature to support conversion of `FormData` to URL-encoded format. Not all `FormData` instances can be converted, either - file uploads for example cannot be URL-encoded.

For that reason, I don't think this would be a good feature to implement. If you have a `FormData` instance you want to URL-encode, perform that encoding before passing it to `Http`.

In the future, a user-defined interceptor could convert `FormData` to a URL-encoded form automatically.

**Comment by sampath-karupakula** [comment]
even multipart/form-data has also similar issue.
not able to add the file content to the FormData.

let formData: FormData = new FormData();
    formData.append('file', file, file.name);
    formData.append('entityNumber',this.node.number);
    formData.append('itemType',getFileExtensionByDomainAndTab(this.node.baseModel.domainId,this.node.baseModel.dtoType));

    let headers = new Headers();
    headers.append('Content-Type', 'multipart/form-data;boundary='+Math.random());
    headers.append('Accept', 'application/json');

    this.http.post(`/file/fileupload`, formData, headers)
      .map(res => res.json())
      .catch(error => Observable.throw(error))
      .subscribe(
        data => {
          this.attachments.push(data);
          this.attachmentSubject$.next(data);
        },
        error => {
          alert("failed to upload");
        }
      )

**Comment by lqclester** [comment]
'@angular/common/http' is not fixed yet

**Comment by vithubati** [comment]
This issue has not been fixed yet as of latest version

**Comment by Danieliverant** [comment]
any news on this?

**Comment by jamesguan** [comment]
I'm having the same issue here as well using Angular 5 and trying to upload a file to flask. I even set the content type header to `multipart/form-data` with no form data being passed.

**Comment by trotyl** [comment]
This issue is about accepts `FormData` object for `application/x-www-form-urlencoded` Content-Type, has nothing to do with file uploads, please not submit unrelated comments.

**Comment by PratikTheGameDever** [comment]
I don't know if it helps anyone, but after spending quite some time I found out that when using FormData we don't have to set the content type to 'multipart/form-data'.

Removing the code which was setting the content type to 'multipart/form-data' worked for me.

Would like someone to shed some light into it.

**Comment by maneeshrao66** [comment]
Hi I have facing same issue formData is showing empty in payload of Chrome browser while sending the formdata to server. Can you please help me?

FormData {}.

  public uploadToServer() {
    let blob  = this.recordRTC instanceof Blob ? this.recordRTC : this.recordRTC.blob;
    let fileType = blob.type.split('/')[0] || 'audio';
    let fileName = (Math.random() * 1000).toString().replace('.', '');
    if (fileType === 'audio') {
      fileName += '.' + (!!navigator.mozGetUserMedia ? 'ogg' : 'wav');
    } else {
      fileName += '.webm';
    }
    // create FormData
    console.log(fileType);
    console.log(fileName);
    var formData: FormData = new FormData();
    console.log(formData);
    formData.append(fileType + '-filename', fileName);
    formData.append(fileType + '-blob', blob);
    var options = { content: formData };

    console.log(options);
     this.dashService.saveRecording(formData).subscribe(
       data => this.saveRecordingSuccess(data),
       error => this.saveRecordingFail(error)
     );
   }

**Comment by StewartJingga** [comment]
@maneeshrao66 Have you found the solution to the problem ?
The request payload on my Chrome DevTools is also showing empty.

**Comment by DustinJSilk** [comment]
**Angular**: _About to use multipart/form-data_

**Me**: Please use multipart/form-data

**Angular**: How dare you 🖕

**Comment by quenneth-bidchat** [comment]
Removing the content type doesn't help. The file shows in the formdata but then on post it shows the file object as empty in the network tab. Is there any other fix for this?

**Comment by karmadice** [comment]
> Removing ( 'Content-Type', 'multipart/form-data' ) Solved my issue with httpClient

I can not understand why and how, but it worked for me too

**Comment by deepbchudasama** [comment]
Still no solution! Anyone has any other solution than Removing ( 'Content-Type', 'multipart/form-data' ) ?

**Comment by ritikrishu** [comment]
Here is a working solution with Reactive forms.
_template_:
```html
<form [formGroup]="form" ngSubmit="postForm()">
    <input type="file" formControlName="file" (change)="onFileChange($event)">
<button type="submit">Upload</button>
```
_component_:
```js
import { HttpClient, HttpParams, HttpRequest } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { Component } from '@angular/core';

@Component({
    selector: 'my-selector',
    templateUrl: 'my-selector.component.html',
    styleUrls: ['my-selector.component.scss']
})

export class MyComponent {
    constructor(
        private http: HttpClient,
        private fb: FormBuilder
    ) { }

    file

    form = this.fb.group({
        file: [null, Validators.required]
    })

    postForm() {
        const formData = new FormData();
        formData.append('excel', this.file);

        const params = new HttpParams();

        const options = {
            params,
            reportProgress: true,
        };

        const req = new HttpRequest('POST', 'http://0.0.0.0:4000/v1/matric', formData, options);
        this.http.request(req).subscribe(console.log)
    }

     onFileChange(event) {
        if (event.target.files && event.target.files.length) {
            const [file] = event.target.files;
            this.file = file
        }
    }
}

```

**Comment by Ilyoskhuja** [comment]
> 'POST',

ishlamadiyu nedagon

**Comment by Ilyoskhuja** [comment]
> Here is a working solution with Reactive forms, but a similar setup will work with template driven forms as well.
> _template_:
> 
> ```
> <form [formGroup]="form" ngSubmit="postForm()">
>     <input type="file" formControlName="file" (change)="onFileChange($event)">
> <button type="submit">Upload</button>
> ```
> 
> _component_:
> 
> ```js
> import { HttpClient, HttpParams, HttpRequest } from '@angular/common/http';
> import { FormBuilder, Validators } from '@angular/forms';
> import { Component } from '@angular/core';
> 
> @Component({
>     selector: 'my-selector',
>     templateUrl: 'my-selector.component.html',
>     styleUrls: ['my-selector.component.scss']
> })
> 
> export class MyComponent {
>     constructor(
>         private http: HttpClient,
>         private fb: FormBuilder
>     ) { }
> 
>     file
> 
>     form = this.fb.group({
>         file: [null, Validators.required]
>     })
> 
>     postForm() {
>         const formData = new FormData();
>         formData.append('excel', this.file);
> 
>         const params = new HttpParams();
> 
>         const options = {
>             params,
>             reportProgress: true,
>         };
> 
>         const req = new HttpRequest('POST', 'http://0.0.0.0:4000/v1/matric', formData, options);
>         this.http.request(req).subscribe(console.log)
>     }
> 
>      onFileChange(event) {
>         if (event.target.files && event.target.files.length) {
>             const [file] = event.target.files;
>             this.file = file
>         }
>     }
> }
> ```

ishlamadiyu nedagon

**Comment by meksula** [comment]
:angry: I spent almost 4 hours at debuging this annoying issue... Newest version of Angular has this problem too. If I remove my headers it works, but.... API requires these all.

**Comment by ritikrishu** [comment]
@meksula 
you can append headers in this fashion-
```js
const options = {
       headers: new HttpHeaders({ 'Authorization': `Bearer ${token}` }),
        params: new HttpParams(),
        reportProgress: false,
};
const req = new HttpRequest('POST', `${BASE_URL}${url}`, formData, options)
```

**Comment by meksula** [comment]
@ritikrishu  thanks. Your solution works very well. But my issue laid my side laid. I appended `Content-Type` header but it was incorrect way to make multipart request.

**Comment by terranmarine** [comment]
@PratikTheGameDever 
God bless ur soul, I have been on this issue whole damn day.... thank you

**Comment by santu1994** [comment]
![1_Sdfm4E98ugZGQ-u5Xoa83g](https://user-images.githubusercontent.com/23427119/59032190-40287f80-8883-11e9-81d7-6bdf8b81fc13.png)
