### ISSUE TITLE
AOT Compiler does not persist quotes on property names in object literals

### ISSUE THREAD

**Issue by mitchellwills** [angular/angular#13249]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
AOT compiler turns quoted property names in object literals into unquoted property names

**Expected behavior**
The AOT respects the fact that the property names were quoted in the original source

**Minimal reproduction of the problem with instructions**
For a project using @angular/router create a resolve property for one of the routes with one key quoted and one not like the following. Run the AOT compiler on the module.
```
const ROUTES: Route[] = [{
    path: 'app',
    component: AppComponent,
    resolve: {
      resolve1: Resolve1,
      'resolve2': Resolve2,
    },
  }];
...
  imports:      [ BrowserModule, RouterModule.forRoot(ROUTES), ],
```

Inspect the .ngfactory.ts file for the module and find where the ROUTES property is defined. Observe that the generated code shows no quotes on resolve2.
```
resolve: {
  resolve1: import32.Resolve1,
  resolve2: import32.Resolve2
}
```

**What is the motivation / use case for changing the behavior?**
Tools like the closure compiler rename properties differently based on if they are quoted or not. In my use case the resolve names and the accesses (`this.route.snapshot.data['resolve2']`) are renamed differently are result in a failure at runtime.

**Please tell us about your environment:** Ubuntu 14.04

* **Angular version:** 2.2.4

* **Browser:** all

 
* **Language:** Typescript

* **Node (for AoT issues):** `node --version` =   v6.9.1

**Comment by dmitrysteblyuk** [comment]
@vicb, this one should be reopened. Broken in 4.2.6.

**Comment by chuckjaz** [comment]
@dmitrysteblyuk Please open a separate bug

**Comment by gurmukhp** [comment]
+1, this bug has resurfaced.
