### ISSUE TITLE
Exception on Renderer::setElementClass with simple example

### ISSUE THREAD

**Issue by thinkingmedia** [angular/angular#13258]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Trying to dynamically set the component's classes using the renderer.

```
import {Component, Input, Renderer, ElementRef} from "@angular/core";

@Component({
    selector: 'ux-icon',
    template: `<span></span>`
})

export class Icon {
    @Input()
    set name(value: string) {
        this.renderer.setElementClass(this.elementRef, 'fa fa-' + value, false);
    }

    constructor(public elementRef: ElementRef, private renderer: Renderer) {
    }
}
```

The above code is throwing an exception. Looking at the code trace the `classes` property of the element is `undefined`.

Happens for both adding and replacing.

**Expected behavior**

Should be able to set the class.

**Please tell us about your environment:**

Apache, Chrome, Windows 10

* **Angular version:** 2.2.1

* **Browser:** Chrome 54.0.2840.99
 
* **Language:** TypeScript 2.0

* **Node (for AoT issues):** `node --version` =  6.9.1

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr

**Comment by thinkingmedia** [comment]
@DzmitryShylovich do you have a plunkr template that runs 2.2.1 that you can share?

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by thinkingmedia** [comment]
@DzmitryShylovich thank you. I'll use this in the future.

I'm closing as I found that `setElementClass` is expecting the native element reference. It doesn't work with `ElementRef`.

Is it suppose to?

**Comment by DzmitryShylovich** [comment]
`this.renderer.setElementClass(this.elementRef.nativeElement, 'fa fa-' + value, false);`
