### ISSUE TITLE
canActivate guard only triggers on first attempt to access route.

### ISSUE THREAD

**Issue by Spittal** [angular/angular#13259]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`canActivate` method on route guard doesn't trigger when attempting to navigate to a route that the user was previously denied access to.

**Expected behavior**
That the `canActivate` method should be run on every attempting navigation to guarded route

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/LWQnCwnbWDjUXBO70c39?p=info

1. Click on a routerlink leading to a guarded route that will deny access
2. Click on the same link again, and see that the guard doesn't trigger the second time.

**What is the motivation / use case for changing the behavior?**
I have a modal that notifies the user that they can't access certain content, in the rare case they dismiss the notification, or don't read the notification the user may attempt to click the content again, to be greeted with no notification at all.

**Please tell us about your environment:**
MacOS Sierra 10.12.1, Linux Ubuntu Trusty

* **Angular version:**
Angular 2.2.4, router 3.2.4

* **Browser:**
all browsers.
 
* **Language:**
Typescript 2.0.3

* **Node (for AoT issues):** `node --version` =   6.5.0

**Comment by vicb** [comment]
This should have been fixed with https://github.com/angular/angular/commit/d46b8deeea7f6a66be576d9ccd63772901277801

You can check with the latest [router-builds](https://github.com/angular/router-builds) or wait for the next release probably later this week.
