### ISSUE TITLE
Is this possible to add a custom onChange function to the default FormControl?

### ISSUE THREAD

**Issue by DanielLuu** [angular/angular#13251]
Is this possible to add a custom onChange function to the default FormControl?  NOT my own custom input.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
