### ISSUE TITLE
"Maximum call stack size exceeded" when compiling component with no View template or templateUrl

### ISSUE THREAD

**Issue by matthewjh** [angular/angular#1326]
Given

```javascript
@Component({
  selector: 'app'
})
@View({
})
class AppComponent {}

bootstrap(AppComponent);
```

Angular fails with

```
Uncaught TypeError: Cannot redefine property: onclick
Uncaught RangeError: Maximum call stack size exceeded
```

There's an [existing throw](https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/compiler/template_loader.js#L45) intended to handle views without a `template` or `templateUrl`, but it never gets hit because the `viewDefinition`'s `absUrl` property gets set in `Compiler#_buildRenderTemplate` regardless.

**Comment by matthewjh** [comment]
See PR, which I think provides a quick fix for this issue.

Personally, though, I think it's a bit odd that `absUrl` has two slightly different uses: to store the URL of the template if there is one, and to store the URL of the component otherwise for stylesheet loading. Why not have both `absUrl` (to use for loading resources e.g. stylesheets) and `templateUrl` on a `ViewDefinition`?

**Comment by tbosch** [comment]
Thanks for catching this! Your PR looks good.

**Comment by matthewjh** [comment]
@tbosch:

There is already an exception thrown for this scenario in `TemplateLoader`: https://github.com/matthewjh/angular/blob/compiler-patch-mh/modules/angular2/src/render/dom/compiler/template_loader.js#L45

This PR just ensures that that line is reachable.
