### ISSUE TITLE
Angular 2 Documentations not clearly setup

### ISSUE THREAD

**Issue by teddywest32** [angular/angular#13264]
**I'm submitting a **
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**
I was looking on the `http` class
https://angular.io/docs/ts/latest/api/http/index/Http-class.html
and there was only the usage docs for `http.get ` and not for other options.
**At least there should be simple code for each of the options.**

**What is the motivation / use case for changing the behavior?**
Easy for every developers to use the functions without need to search and post unneccessary questions in stackoverflow.

* **Angular version:** 2.2.0
 
* **Language:**
 [TypeScript 2.0 | ES6]

**Comment by WilliamKoza** [comment]
you can post your request here : https://github.com/angular/angular.io/issues

**Comment by pkozlowski-opensource** [comment]
What @WilliamKoza have said :-)
