### ISSUE TITLE
Angular 2 : IE Syntax error\n   at __exec system.src.js:1511:10 system.src.js:3927  at linkDynamicModule 

### ISSUE THREAD

**Issue by Rashmi1900** [angular/angular#13262]
My angular 2 application is crashing in IE with syntax error when trying to load my app.module file
"SyntaxError: Syntax error\n   at __exec (http://localhost/test4/node_modules/systemjs/dist/system.src.js:1511:10)\n   at entry.execute (http://localhost/test4/node_modules/systemjs/dist/system.src.js:3927:11)\n   at linkDynamicModule (http://localhost/test4/node_modules/systemjs/dist/system.src.js:3253:5)\n   at getModule (http://localhost/test4/node_modules/systemjs/dist/system.src.js:3221:9)\n   at Anonymous function (http://localhost/test4/node_modules/systemjs/dist/system.src.js:3257:9)\n   at require (http://localhost/test4/node_modules/systemjs/dist/system.src.js:3894:13)\n   at Anonymous function (eval code:3:1)\n   at Anonymous function (eval code:1:31)\n   at eval code (eval code:1:2)\n   at __exec (http://localhost/test4/node_modules/systemjs/dist/system.src.js:1511:10)"

app.module.js code is 
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
const core_1 = require('@angular/core');
const platform_browser_1 = require('@angular/platform-browser');
const forms_1 = require('@angular/forms');
const router_1 = require('@angular/router');
const http_1 = require('@angular/http');
const app_component_1 = require('./app.component');
const home_component_1 = require('./home/home.component');
const product_list_component_1 = require('./product/product-list.component');
const category_list_component_1 = require('./category/category-list.component');
const category_selector_component_1 = require('./category/category-selector.component');
const grid_component_1 = require('./shared/controls/grid/grid.component');
const product_list_service_1 = require('./product/product-list.service');
const category_list_service_1 = require('./category/category-list.service');
const router_config_1 = require('./router.config');
let AppModule = class AppModule {
};
AppModule = __decorate([
    core_1.NgModule({
        imports: [platform_browser_1.BrowserModule,
            forms_1.FormsModule,
            router_1.RouterModule.forRoot(router_config_1.ROUTES),
            http_1.HttpModule],
        declarations: [app_component_1.AppComponent, home_component_1.HomeComponent, product_list_component_1.ProductListComponent, grid_component_1.GridComponent, category_list_component_1.CategoryListComponent, category_selector_component_1.CategorySelectorComponent],
        providers: [product_list_service_1.ProductListService, category_list_service_1.CategoryListService],
        bootstrap: [app_component_1.AppComponent]
    }), 
    __metadata('design:paramtypes', [])
], AppModule);
exports.AppModule = AppModule;
//# sourceMappingURL=app.module.js.map

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
