### ISSUE TITLE
Proposal: [style.xxx.url] binding for url(...)

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#13260]
**I'm submitting a ...**  (check one with "x")
```
[x] Proposal
```

### Goal

``` ts
@Component({
  template: `<div [style.background-image.url]="bgImage"></div>`
})
class SomeComp {
  bgImage = "url/to/foo.png";
}
```

### Motivation

Currently, to use `url(...)` function with style-binding, I have to wrap the URL property with quotes. 

```ts
@Component({
  template: `<div [style.background-image]="'url(' + bgImage + ')'"></div>`
})
class SomeComp {
  bgImage = "url/to/foo.png";
}
```

`'url(' + bgImage + ')'` is easy to mistake and not beautiful. :(

### Summary
- `[style.xxx.url]="prop"` will be expanded to `url(prop)`

**Comment by laco0416** [comment]
I think this is also good to sanitize property as `SecurityContext.RESOURCE_URL`.

**Comment by laco0416** [comment]
A problem is confliction with `style.xxx.<unit>`. `url` is not a unit. 

alternative ideas:

- `[style.background-image#url]`
- `[style.background-image:url]`

**Comment by zoechi** [comment]
`[style.background-image#url]` is a nice idea but 
I would just use a pipe `[style.background-image]="bgImage | url"`.
The pipe can do sanitization as well if you want.

**Comment by laco0416** [comment]
@zoechi It is a good way totally, but pipes can be placed only in a template. Being syntax means it can be used in decorators like `@HostBinding("style.background-image#url")`.

**Comment by DzmitryShylovich** [comment]
I also have an idea to use `[style.xxx.important]="prop"` for `!important` styles :)

**Comment by laco0416** [comment]
Current implementation for `[style.xxx.<unit>]` is not flexible to reuse the 3rd parameter for other features. Probably at first, refactoring to make it general is needed.

**Comment by intellix** [comment]
Was just looking at this, are these the 2 places where it would need adding?

setElementStyle: https://github.com/angular/angular/blob/master/packages/core/src/view/element.ts#L281 

NgStyle: https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_style.ts#L66

I don't think a extra syntax is a good idea. `style.background-image.url="something"` would really clean up views and I'm sure quite a few people tried it already :)

**Comment by tzachov** [comment]
This is an old issue but can make things much more convenient so it's worth bumping.
By making a very small change, we can support `url()`, `calc()` or whatever CSS function required.
I suggest keeping the current format (`style.<name>.<unit>`) but support parenthesis instead of limiting to unit: `style.background-image.url()`

Then the only change in code should be on `_setStyle` method in `ng_style.ts`:
```typescript
private _setStyle(nameAndUnit: string, value: string|number|null|undefined): void {
  const [name, unit] = nameAndUnit.split('.');
  value = value != null && unit ? unit.indexOf('()') > -1 ? unit.replace('()', `(${value})`) : `${value}${unit}` : value;

  if (value != null) {
    this._renderer.setStyle(this._ngEl.nativeElement, name, value as string);
  } else {
    this._renderer.removeStyle(this._ngEl.nativeElement, name);
  }
}
```

**Comment by pkozlowski-opensource** [comment]
From all the suggestions I like `style.background-image.url()` the most as it is explicit (`()` indicate that the value should be _wrapped_ and not used as a suffix) and doesn't conflict with the current handling of style units.

**Comment by vmasek** [comment]
`style.background-image.url()` wth `unit()` seems understandable and as a really nice solution.
I think it should also sanitize for `SecurityContext.RESOURCE_URL` as was already mentioned.

Do we have an approval for a PR?

**Comment by pkozlowski-opensource** [comment]
Thinking about this one a bit more, we are trying to tackle 2 use-cases here:
* have "nicer" syntax;
* sanitize for SecurityContext.RESOURCE_URL by default;

Let me start by saying that we considering some changes to the sanitisation algorithm which would make the "sanitize for SecurityContext.RESOURCE_URL by default" part null and void. This leaves us with the "nicer" syntax. Let's compare the proposal with what is available today:
* `[style.background-image]="'url(' + bgImage + ')'"` - possible today
* `style.background-image="url({{bgImage}})"` - also possible today (interpolation)
* `[style.background-image.url()]="bgImage"` - proposal

If we consider that it is possible today to use interpolation (style.background-image="url({{bgImage}})"`) it is not _very_ different from the proposal here (`[style.background-image.url()]="bgImage"`). As such I'm not sure if there is enough benefits of the new syntax and I'm not sure the benefits outweighs cost (changes in the framework, larger API / conceptual surface / additional documentation etc.).

Given all the above I would probably vote for _not_ implementing it as "not beneficial enough" but curious to hear other opinions.

**Comment by alxhub** [comment]
I agree with @pkozlowski-opensource's assessment - the benefits here don't outweigh the extra complexity.
