### ISSUE TITLE
demo is outdated, still using CORE_DIRECTIVES

### ISSUE THREAD

**Issue by intergleam** [angular/angular#13269]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The demo on the page https://angular.io/docs/ts/latest/api/common/index/NgIf-directive.html is wrong 
`import {Component, View, CORE_DIRECTIVES} from 'angular2/angular2'`
throws error
**Expected behavior**
demo should work with latest version
**Minimal reproduction of the problem with instructions**
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
any

* **Angular version:** 2.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io

**Comment by pkozlowski-opensource** [comment]
What @DzmitryShylovich is saying...

**Comment by ericmartinezr** [comment]
He meant the live demo plnkr, it's using alpha 37.
