### ISSUE TITLE
[BUG] Template vars in conditional expressions don't work

### ISSUE THREAD

**Issue by mp3por** [angular/angular#13270]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using template variables in condition expressions for directive Angular2 does not work.

**Expected behavior**
I expect it to know trigger the "hidden" class when the route is activated => to be able to use template variables in the conditional statements of directives

**Minimal reproduction of the problem with instructions**

PLINKER: http://plnkr.co/edit/cuqzxJBBcyq2tdl8765s?p=preview

**What is the motivation / use case for changing the behavior?**

I believe this is a reasonable  

**Please tell us about your environment:**

Latest build of all @angular packages (2.2.4) inside a project managed/generated by the latest angular-cli version (1.0.0-beta.19-3).

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a working repro in plunkr

**Comment by mp3por** [comment]
Let me first fix the formatting :D

**Comment by mp3por** [comment]
I have no idea how to fix the formatting of this post ... however here is a gitrepo : https://github.com/mp3por/Angular2FeatureModulesRouting 

The problem is replicated in core.component.html

**Comment by pkozlowski-opensource** [comment]
Please extract relevant code in a plunker. We can't debug entire projects....

**Comment by DzmitryShylovich** [comment]
@mp3por u can use http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 as a starting point

**Comment by mp3por** [comment]
Ok I will try but I have never been able to make the plunker thing work. In the mean time just checkout the project and run it. There is no need for debugging the whole project since everything else is working except this ( the code in core.component.html ). :)

**Comment by mp3por** [comment]
http://plnkr.co/edit/cuqzxJBBcyq2tdl8765s?p=preview

**Comment by vicb** [comment]
@mp3por when you submit a bug report:
1. add a **minimal** plunker,
2. describ what we see and what you expect we should see.

We don't have spare time to try to figure out what you are trying to do and what you expect the result should be.

Thanks.

**Comment by mp3por** [comment]
@vicb ? That is what I have done ? Is there something not clear ?

**Comment by DzmitryShylovich** [comment]
it's for the future reference

**Comment by vicb** [comment]
@mp3por yep 2 is unclear, I should open your plunker and ... ?

**Comment by mp3por** [comment]
@vicb do whatever you want, man - if you don't fix it now because you are annoyed by me someone else will report it and then you will have to fix it again - or don't fix it at all ... there are 5 more frameworks ... I think it is very clear once you open the plunker ... there is a big: "does not work" thing displayed and the console is filled with red - but hey who am I to talk to the Angular gods :)

**Comment by vicb** [comment]
> there are 5 more frameworks

there are actually much more !

What I am expecting from you is "2. describe what we see and what you expect we should see"

**Comment by robwormald** [comment]
this is exploding because the `links` property of RouterLinkActive is a querylist, which isn't defined until afterViewInit. Probably just need to define a check like https://github.com/angular/angular/blob/master/modules/%40angular/router/src/directives/router_link_active.ts#L124 before calling `links.some()`
