### ISSUE TITLE
CanActivate guard does not trigger when CanActivate had return false once

### ISSUE THREAD

**Issue by duboi381** [angular/angular#13288]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a CanActivate guard does not activate a component, if you try to navigate to the same component, it should check again the CanActivate guard, but it doesn't

**Expected behavior**
It should check again for the guard to see if it can be activated

**Minimal reproduction of the problem with instructions**
- Go to http://plnkr.co/edit/vamiUK?p=preview
- Press "Page 1"
- A popup will appear
- Press "Continue" (it will call router.navigateByUrl("/page1/")
- Notice that nothing happened
- Press "Page 1"
- Notice that nothing happened
- You need to press "Page 2" and after press "Page 1" to reactivate guard

**What is the motivation / use case for changing the behavior?**
It was working before Angular 2.2.0-rc.0

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.3.0-rc.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/13259#issuecomment-265030461

**Comment by duboi381** [comment]
This look pretty much like my problem, I will close this issue for now and will re-open if it's not fixed on next release.

Thanks
