### ISSUE TITLE
The value in service will be empty if the function returns a null object

### ISSUE THREAD

**Issue by snowsky** [angular/angular#1328]
If I use service as below, I can not access test.var variable anymore, but if I comment the return {}, then it works.

myApp.service('test', function () {
    this.var = "local";
    return {

    };
});

**Comment by matthewjh** [comment]
@snowsky 

Did you mean to put this in the [Angular 1 repo](https://github.com/angular/angular.js)? This repo is for Angular 2, which is currently an alpha version.

But anyway, as far as I can tell, there's nothing unintended on Angular's part going on here. When you `return obj;` from a constructor function (which a service is an example of), you're going to return that object a opposed to implicitly returning `this`.
