### ISSUE TITLE
Angular Doesn't Work in IE11

### ISSUE THREAD

**Issue by montella1507** [angular/angular#13285]
Angular doesn't work in IE11. This plunker is minimal reproduction:

Check this plunker please in IE11. 
https://plnkr.co/edit/LOJWgfDGvtKQzhxuD8Wa?p=preview

It doesn't work with webpack as well.

**Comment by DzmitryShylovich** [comment]
welcome back :)

Duplicate of https://github.com/angular/angular/issues/13152

plnkr is missing the core-js

**Comment by mlaval** [comment]
Thanks @DzmitryShylovich :)
