### ISSUE TITLE
TypeError: ResizeSensor is not a constructor error (Angular AOT)

### ISSUE THREAD

**Issue by quiringk** [angular/angular#13283]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am 

**Expected behavior**

I have an Angular 2 App and am using the external javascript library css-element-queries. When I run my Angular 2 app in development mode (JIT), everything works fine with css-element-queries. When I run my app in (AOT) mode for production, I get "TypeError: ResizeSensor is not a constructor" error which stops the css-element-queries from working. 

**Minimal reproduction of the problem with instructions**

at the top of the typescript file, I introduce ElementQueries like:
`declare var ElementQueries: any;`

After the page loads, I call:
`ElementQueries.init();`

And the scripts are loaded in index.html obviously.

That works in development mode, its in production AOT mode that I get the constructor error. I have other external javascript libraries that I use similarly and they are working in Angular AOT.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, SystemJS, vscode

* **Angular version:** 2.0.X

Angular 2.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 2.0.3

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
did u install typings for `css-element-queries`?

**Comment by chuckjaz** [comment]
Can you create a public repository that I can clone that has reproduces this issue?

I suspect the issue has to do with one of the providers not in form we support for AOT. You might consider replacing the promise with a factory function that evaluates to the value of `ElementsQuery` instead of providing it directly.

**Comment by quiringk** [comment]
@DzmitryShylovich When I try to install typings for css-element-queries i get 

`Unable to find "css-element-queries" ("npm") in the registry.`

and when I search for typings for css-element-queries i get 

`No results found for search`

**Comment by quiringk** [comment]
The confusing part for me is why this library works fine in JIT and not in AOT. I have two other .js scripts (autosize.js & naturalSort.js) that work fine without any typings installed. These work fine in AOT. What is different about css-element-queries?

**Comment by quiringk** [comment]
@chuckjaz I have a created a public repo for you to look at. 

`https://github.com/quiringk/ConstructorError.git`

This repo consists of Angular Quickstart with angular AOT added. I removed the angular quickstart template and replaced it with the first example from "css-element-queries". If you run "npm install", and then "npm start", the example works perfectly (Adjust the screen size and see the header change color and sizes). If you run "npm run build:aot && npm run lite:aot" you will see the example does not work and you will see the errors I have been describing. Thanks for looking at this.

**Comment by chuckjaz** [comment]
The default configuration of the `quickstart` repository uses the `index.html` in the `aot` directory instead of the root.

I modified `aot/index.html` to include the script tags you added to `index.html` and installed `css-element-query` into `aot/node_modules` and it appears to work.

**Comment by quiringk** [comment]
I forgot to add the scripts to aot/index.html for the repro but then I did and it still didn't work. Then I installed css-element-query into aot/node_modules and it didn't work. Finally I changed my script filepath in aot/index.html from

`<script src="ResizeSensor.js"></script>
        <script src="ElementQueries.js"></script>`

to

`<script src="node_modules/css-element-queries/src/ResizeSensor.js"></script>
        <script src="node_modules/css-element-queries/src/ElementQueries.js"></script>`

and it worked! The whole time I've been copying the scripts from app/node_modules/... to aot directory and just calling them directly in aot/index.html and that seemed to be the problem. Can you explain to me why installing css-element-queries in aot/node_modules and referencing them from there in aot/index.html was necessary, and why just referencing them directly in the aot/ directory didnt work but worked for other javascript libraries?
