### ISSUE TITLE
Allow overriding ResourceLoader

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#13286]
**I'm submitting a ...**  (check one with "x")
```
[ x] feature request
```

**Current behavior**
Allow overriding internal ResourceLoader implementation for templateUrl support in component. when components are defined with templateUrl and respective unit tests are taking long time to complete (due to karma requesting template url each unit test)

**Expected behavior**
allow override resourceloader to load template url content without actual template url http requests.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
when components are defined with templateUrl and respective unit tests are taking long time to complete (due to karma requesting template url each unit test). each unit test take about 1 sec to complete with this approach and this is leading to long unit test execution time.

**Please tell us about your environment:**
Windows 7 64 16GM RAM, VSCode IDE

* **Angular version:** 2.0.4

* **Browser:** PhantomJS/Chrome
 
* **Language:** [TypeScript 2.0.10]

* **Node (for AoT issues):**  =   6.9.1

**Comment by DzmitryShylovich** [comment]
You can provide your own impl `{provide: ResourceLoader, useClass: MyResourceLoaderImpl}`

**Comment by mlakmal** [comment]
@DzmitryShylovich i tried overriding like you have mentioned. but its still using internal resourceloader for component templateUrl request.

**Comment by frederikschubert** [comment]
You have to provide it using [this](https://angular.io/docs/ts/latest/api/core/testing/index/TestBed-class.html#!%23configureCompiler-anchor) method.

**Comment by mlakmal** [comment]
@frederikschubert thanks that worked. do you have an idea on how to do the same in actual application (instead of unit test configuration) ?

**Comment by DzmitryShylovich** [comment]
`platformBrowserDynamic[{provide: ResourceLoader, useClass: MyResourceLoaderImpl}]().bootstrapModule(AppModule)`

**Comment by mlakmal** [comment]
@DzmitryShylovich @frederikschubert  thanks for pointing out the code. i was able to use below code to get it working.

platformBrowserDynamic([{
  provide: COMPILER_OPTIONS,
  useValue: { providers: [{ provide: ResourceLoader, useClass: CustomResourceLoader }] },
  multi: true
}]).bootstrapModule(MainModule);

used below to override it in unit testbed.
TestBed.configureCompiler({
      providers: [
        { provide: ResourceLoader, useClass: TestResourceLoaderImpl }
      ],
      useJit: true
    });

**Comment by ericminio** [comment]
In case it is useful for someone, a working example: https://github.com/ericminio/learning-typescript/blob/master/test/mocha.shim.js
