### ISSUE TITLE
Angular 2 - AoT 404

### ISSUE THREAD

**Issue by phil123456** [angular/angular#13299]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

from : https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

After compiling my project with ngc, I keep getting a 404 on start

404 GET /aot/app/app.module.ngfactory

if I try to access the resource in the browser it works

200 GET /aot/app/app.module.ngfactory.js

I dont understand why angular does not add the ".js" extension here

**Expected behavior**

**Minimal reproduction of the problem with instructions**

I modified my main.ts:

```
import { platformBrowser }    from '@angular/platform-browser';
import { AppModuleNgFactory } from '../aot/app/app.module.ngfactory';
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

I compiled with ngc:

node_modules\.bin\ngc -p tsconfig-aot.json

tsconfig-aot.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },

    "files": [
    "app/app.module.ts",
    "app/main.ts"
  ],

   "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : true
 }
}
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
windows 7 64 

* **Angular version:** 2.2.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by arendjantetteroo** [comment]
I've got the same error after upgrading my node version to 6.9.2 on ubuntu 16.04.1 LTS today. 
Will try a node downgrade

**Comment by phil123456** [comment]
no idea, the support here is quiet absent aparently

**Comment by phil123456** [comment]
hello !!! ??? can someone investigate this?, it is clearly a bug
thanks

**Comment by DzmitryShylovich** [comment]
> the support here is quiet absent aparently

support? :)
it's open source project.

**Comment by arendjantetteroo** [comment]
In our case it was caused by typescript : ^2.0.3. Setting it to 2.0.9 fixes it for us.

**Comment by thelgevold** [comment]
If you are requesting files like app.module.ngfactory.js individually, I suspect you didn't complete the Rollup bundling step in the tutorial. If you follow all the steps you will be left with a single file that loads the entire application (including angular dependencies).

It's not recommended to run the app without bundling. Other than the performance impact, the first obstacle is that the JS is using es2015 modules. This prevents it from running in browsers that don't support es2015 import statements.

**Comment by vicb** [comment]
@phil123456:
1- We do not provide support, see details below,
2- Whenever you seek for support think about providing the requested information before (ie the issue template here)

--

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by phil123456** [comment]
@vicb that's odd, I certainely filled a bug repport, so I was expecting some support...like any other project I been dealing with on github for years now :-) 
I also registered a thread on stackoverflow wich nobody replied, so I came here

http://stackoverflow.com/questions/41012146/angular-2-aot-404

**Comment by phil123456** [comment]
@ thelgevold  sorry I am new to node.js/andgular, I have no idead what you are refering too
I simply followed the offcigial angular tutorial, with the official angular seed

I am not requesting app.module.ngfactory.js individualy, it was a test to see if the file was available through the server...arendjantetteroo  had the same issue btw

"It's not recommended to run the app without bundling" what are you talking about ?
I did a npm start wich made the app run fine, then I used ngc to compile it, and then modified the main.ts to load the ngfactory stuffs...this is all described here https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Comment by phil123456** [comment]
nice support
