### ISSUE TITLE
form input fields no longer respect the readonly attributes for --prod builds.

### ISSUE THREAD

**Issue by un33k** [angular/angular#13290]
**I'm submitting a ...** 
```
[x ] bug report
```

**Current behavior**
input readonly works with dev but not prod.

**Expected behavior**
input readonly should work with any type of compilation.

**Minimal reproduction of the problem with instructions**
```typescript
 // in profile.component.ts
  buildForm(profile) {
    this.profileForm = this.formBuilder.group({
      name: [profile.name, [Validators.required]],
      email: [profile.email, [Validators.required]],
    });
    this.profileForm.controls['email'].disable({ onlySelf: true });
  }
```
```html
  <form [formGroup]="profileForm" (submit)="saveProfile()">
    <input formControlName="email" placeholder="Email" class="form-control">
    ...
  </form
```

**Please tell us about your environment:**
$ ng --version
angular-cli: 1.0.0-beta.22-1
node: 6.0.0
os: darwin x64
IDE: vs code

**Angular version:** 
2.2.3

**Browser:**
Chrome, Firefox, Safari (tested)

**Remarks:**
Updated ng-cli and ng2 to the above versions. It seems that ng-cli may have turned on the --aot compilation (default) for --prod builds.

**Comment by DzmitryShylovich** [comment]
Pls provide a repro in plunker.

If it's cli related pls re-open it on https://github.com/angular/angular-cli/issues

**Comment by vicb** [comment]
Could you please try:
- 2.2.3 in JiT mode (add a plunker),
- 2.3.0 in JiT mode (if 2.2.3) does not work.

To help narrow down the issue

**Comment by un33k** [comment]
I am no longer able to reproduce the problem.  If I run into it again, for sure I will plunker it and reopen this.
