### ISSUE TITLE
RFC: <proposal #someId [bind]="expr" (event)="doWork()">

### ISSUE THREAD

**Issue by mhevery** [angular/angular#133]
## Update from @IgorMinar on 2014-11-10:

To summarize the constraints, the solution we are looking for must match the following:

1. Be valid HTML (see this [issue](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27228) for discussion about `[`, `]`, `(`, `)` chars in attr name of valid html).
2. Be Web designer friendly
3. Interoperable with web-components (don't interfere with web component initialization)
4. Support debugging story via inspecting rendered DOM during development
5. The syntax must clearly distinguish between 1) string literal; 2) expression (binding); 3) expression (events) 4) declaration of variables. All of this must be clear from template without understanding which directives are active or what the internal semantics of these directives are.
6. Support additional info or options for each binding in order to avoid directive specific micro-syntaxes (this enables for tooling to work without hardcoding support for micro-syntaxes). This must be supported in a way that preserves constraint no. 5.

Please don't propose any new solutions that don't meet all of the criteria above.

------
## Original description:

Current proposal for Angular2 syntax is 

```<element #someId [bind]="expr" (event)="doWork()">```

There are several issues with this proposal which have come to light recently. These are:

### `element.setAttribute('[foo]', 'exp')` does not work.

In all browsers tested (Chrome, IE, Safari) the above is an error. This means that it is not possible to create a valid template programatically. It is still possible to parse and read the template.

It seems like that calling `setAttribute` requires first character to be `a-z|_` specifically `-` is not allowed as starting character nor are any of these `~!@#$%^&*(){}`.

### Third part HTML shorteners don't support non-standard characters.

Tools such as Slim, Haml, JADE don't support generating special characters. This would break the backend servers such as Ruby on Rails.

### SVG requires valid XML and `[]()#` is not valid XML.

This seems to be in the [spec](http://www.w3.org/TR/SVG/), but at least Chrome browser does not have issues with these characters. Need to investigate more.

## Straw-man Proposal

We go back to slightly longer text based syntax

`<element var="someId" bind-value="expr" on-event="doWork()">`

The caveat is the `ng-repeat` syntax, which requires a parameter

```
<ul>
  <li bind-ng-repeat--item="items">{{item}}</li>
</ul>
```

Why the weird `ng-repeat` syntax? We want ta make sure that all bindings starting with `bind-` have right hand side as a valid expression. `item in items` is not a valid expression, it is a micro syntax. For this reason we need a way to pass the local-var-name into `ng-repeat` as a string literal, and not as an expression. Hence the `ng-repeat--<local-var-name-literral>="expression"`.

Please leave your thoughts here.

## Background

The reasoning behind the new syntax can be found here: https://docs.google.com/document/d/1kpuR512G1b0D8egl9245OHaG0cFh0ST0ekhD_g8sxtI/edit#heading=h.xgjl2srtytjt

**Comment by nilskp** [comment]
Not sure if this is a recent change, prompted by this, but Jade seems to support both parentheses and brackets as attributes.
http://jade-lang.com/demo/

**Comment by pnazeran** [comment]
* I agree with DeborahK: expressive is better than syntactical
* but syntax could mean shorter code too. So it is a compromise between typing and approachability

$scope variables may appear inside the brackets <> or outside. 
* **Outside**
    * the content of ${...} can be assumed a java-script expression as all binding would be one-way.
    * $ reminds most of the linux command prompt, where expressions are entered, so I prefer it to {{...}}
    * these are the general use cases I can think of:
        * Hello Visitor
        * Hello ${user_name}
        * Hello ${(a == b ? user_name : 'Visitor')} 
        * Hello ${myFactory.getUserName()}


* **Inside: Attributes**
I want to second kpentchev's proposal for attribute assignments, but without the ng- at the beginning. Something like:
    * on-click="..." (event binding)
    * sync-value="..." (two-way binding of the value property)
    * bind-value="..." (one-way binding of the value property)
    * set-value="..." (once off ...)
    * value = "..." for string literals

As was pointed out, it is important that:
> _The syntax must clearly distinguish between 1) string literal; 2) expression (binding); 3) expression (events) 4) declaration of variables._

There may not be any ambiguity regarding string-literals, expressions, etc. as kpentchev's proposal clarifies that for attributes, and takes care of one-way and two-way

* _on-click_: always an expression:
    * on-click = "click()"
    * on-click = "text.style = 'bold'"
* _sync-value_: a variable name otherwise two-way binding won't work.
* _bind-value_: a variable name or expression, so can be processed as expression
    * bind-value = "user_name"
    * bind-value = "myFactory.getUserName()"
* _set-value_ is just a special case of bind-value

.

**Comment by circlingthesun** [comment]
@EisenbergEffect's syntax for Aurelia looks really nice.

**Comment by gdi2290** [comment]
+1 for Aurelia

**Comment by PascalPrecht** [comment]
I think all syntaxes by Aurelia have already been proposed here by @EisenbergEffect. Please stop voting them up here.

**Comment by martinmcwhorter** [comment]
This may be late to the conversation, but I would like type hints available in templates:

    <form ng-type="vm.person: IPerson">
        <input type=text ng-model="vm.person.firstName" />
        <input type=text ng-model="vm.person.lastName" />
    </form>

This could then be validated by an IDE or build time gulp/grunt task. 

    AtScript or TypeScript:
    IPerson {
        firstName: string;
        lastName: string;
    }

The ng-type attribute could be removed from the template by the build task, as it would only be needed for development and build. Otherwise, it would get ignored in production. 

Could this help IDEs with other issues with trying to understand angular's template system?

**Comment by tonypee** [comment]
I think the reason people are voting up the Rob's dot syntax, is that it looks good. Semantically i think it works? (it seems as flexible as [] or ()) So, i would implore the angular 2 team (mhevery?) To please listen to the voting. Frankly, I've just seen the video on the 'alpha' release, and the syntax looks visually terrible. I hope never to have to write with that syntax

**Comment by jamm** [comment]
@tonypee I see only 2 votes and compared with size of thread is nothing.

--

I wonder why ngnl presentation and current docs about templates still promoting "[]()#" as parts of new syntax, when opening post in this thread contains
> element.setAttribute('[foo]', 'exp') does not work

and, especially
> SVG requires valid XML and `[]()#` is not valid XML.

If these problems are solved somehow and we just don't know - please let us know.

**Comment by tonypee** [comment]
@jamm the 'voting' followed positive multiple comments support a prefix/suffix style of defining binding. Originally, @EisenbergEffect suggested bind- on- etc. with 4 people supporting. Recently the dot suffix (which @mhevery suggested is semantically the same) has positive support of:
@DeborahK, @Awk34 , Alxandr, @akircher, @nborelli, @circlingthesun, @gdi2290, and now me

It seems that readability & usability might be taking a backseat to perceived restrictions. I feel the comments suggest that people would *rather a more elegant syntax.

I'll be interested to see some more full examples of the () [] syntax, as i can understand change is hard. But, initially perception is important too - and the . syntax looks more elegant and readable

**Comment by gdi2290** [comment]
Actually if we're voting or anything I'll withdraw mine. I'm in favor of the current syntax using `(event)="exp"` and `[property]="val"` after using angular2 to create a [todo app](https://github.com/gdi2290/angular2do) it I found it's pretty clear.

**Comment by Awk34** [comment]
@gdi2290 Thanks for the example code. I think I agree with you. As long as a new *can* use `bind-property="val"` as to make the syntax easier for beginners, and an experienced user can use the shorthand `[property]="val"` for more readable and terse code, I think it's a good solution.

**Comment by DavidSouther** [comment]
I like the `[]()#` syntax markers aesthetically, but I would like confirmation or refutation from @mhevery @IgorMinar et al that they will not break SVG or broader XML interoperability.

**Comment by petebacondarwin** [comment]
Read the summary of the syntax here: https://docs.google.com/document/d/1HHy_zPLGqJj0bHMiWPzPCxn1pO5GlOYwmv-qGgl4f_s/edit#heading=h.4w4k319ilnp8

There are two forms - shorthand (all these `[...]`, `(...)` and so on) and the canonical form (`bind-`, `on-` and so on). The canonical forms are basically what you could use if you are using Angular 2 inside SVG or X(HT)ML documents.

**Comment by DavidSouther** [comment]
@petebacondarwin That document has evolved quite a bit since I last looked at it :) Thanks for pointing out the updates.

**Comment by jamm** [comment]
thanks @petebacondarwin, finally it's resolved :)

**Comment by JeroMiya** [comment]
@DavidSouther It is indeed true that the []()# attribute syntax is incompatible in an application/xhtml+xml document. Dots are, however, valid - e.g. on.click="foo".

I do not agree that the []()# attribute syntax is more readable than the prefix proposal. I think using sigils in general in place of keywords results in things that are terse but ultimately harder to comprehend. I feel the same way about sigil-heavy programming languages.

I also *strongly* recommend against having two different ways of writing templates. This is really confusing to new developers and results in inconsistent and hard-to-read templates as some developers write them one way, and others write them another. It reminds me of how some developers would use data-ng-* and others just ng-*, and the three different ways of doing dependency injection (one of which I had to ban, despite it being used in EVERY sample and talk on the internet). In this case I would have to ban the []()# syntax as our xml meta-templating tools wouldn't be able to parse them.

Given the lack of xml/SVG compatibility, I would say that the []()# syntax simply fails to meet the constraints, and should be eliminated altogether in favor of the prefix proposal.

**Comment by ldiego08** [comment]
After reading the thread, these are my favorite suggestions:
* Period notation for attributes.
* JS object-like expressions for complex directives like ng-repeat.
* Namespacing for prefixing attributes.
* ${} enclosure for string interpolation.

Based on that, this is what I'm thinking of:

<h5>Template With Property Binding</h5>
```
<ng:template>
    <div ng:bind="{ title: expression1 }">
        <p>${expression2}</p>
    </div>
</ng:template>
```
<h5>Repeating, Event Binding, etc.</h5>
```
<ng:template>
    <ul>
        <li ng:for="{ each: 'item', in: items }">
            <span>${item.foo}</span>
            <button ng:on.click="deleteItem(item.id)">X</button>
        </li>
    </ul>
</ng:template>
```
<h5>Multi-line Lovers Compatible</h5>
```
<ng:template>
    <div ng:bind="{
            title: expression1,
            foo: expression2
         }">
        <ul>
            <li ng:for="{
                   each: 'item',
                   in: items
                }">
                <span>${item.foo}</span>
                <button ng:on.click="deleteItem(item.id)"
                        ng:on.blur="doSomething()">
                    X
                </button>
            </li>
    </div>
</ng:template>
```

**Comment by mhevery** [comment]
I know this is a sensitive topic to a lot of you. We have gotten a lot of good feedback from this discussion which was incorporated into our thinking, and so I think this thread has served its purpose, and will be not retired. 

Please watch my presentation on this topic: https://www.youtube.com/watch?v=-dMBcqwvYA0 which tries to answer many of the questions.

**Comment by lukehutch** [comment]
I'm late to the party here, but what about simply treating property binding as an "event"?:

    <web-component [title]="exp" (close)="exp()">

would be 

    <web-component ng-on-bind="ngBind('title','exp')" ng-on-close="exp()">

(As a bonus, it might actually be useful to be able to execute an arbitrary expression at bind time.)
