### ISSUE TITLE
Strict mode syntax error when running @angular/compiler 2.3.0 in PhantomJS

### ISSUE THREAD

**Issue by tsvetomir** [angular/angular#13301]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Running `@angular/compiler` in PhantomJS results in an error:
> Uncaught SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.

The offending code can be found in `@angular/compiler/bundles/compiler.umd.js:26587`:
```js
  JitCompiler.prototype._createCompiledHostTemplate = function (compType, ngModule) {
      if (!ngModule) {
          throw new Error("Component " + stringify(compType) + " is not part of any NgModule or the module has not been imported into your module.");
      }
      var /** @type {?} */ compiledTemplate = this._compiledHostTemplateCache.get(compType);
      if (!compiledTemplate) {
          var /** @type {?} */ compMeta = this._metadataResolver.getDirectiveMetadata(compType);
          assertComponent(compMeta);
          var HostClass_1 = (function () {
              function HostClass_1() {
              }
              HostClass_1.overriddenName = identifierName(compMeta.type) + "_Host";
              return HostClass_1;
          }());
          function HostClass_tsickle_Closure_declarations() {
//        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              /** @type {?} */
              HostClass_1.overriddenName;
          }
          var /** @type {?} */ hostMeta = createHostComponentMeta(HostClass_1, compMeta);
          compiledTemplate = new CompiledTemplate(true, compMeta.selector, compMeta.type, hostMeta, ngModule, [compMeta.type]);
          this._compiledHostTemplateCache.set(compType, compiledTemplate);
      }
      return compiledTemplate;
  };
```

**Expected behavior**
The code should run in PhantomJS

**Minimal reproduction of the problem with instructions**
See [tsvetomir/phantomjs-angular-2.3](https://github.com/tsvetomir/phantomjs-angular-2.3) for a runnable sample.

1. `git clone git@github.com:tsvetomir/phantomjs-angular-2.3.git`
1. `cd phantomjs-angular-2.3`
1. `npm install`
1. `./node_modules/.bin/phantomjs script.js`

**What is the motivation / use case for changing the behavior?**
The shipped code shouldn't violate Strict Mode restrictions.

**Please tell us about your environment:**

* **Angular version:** 2.3.0

* **Browser:** PhantomJS 2.1.7
 
* **Language:** TypeScript 2.1

* **Node (for AoT issues):** 4.7

**Comment by tsvetomir** [comment]
This also fails on Chromium 37, the version used on Travis CI. It runs fine in the latest Chrome.

> Chromium 37.0.2062 (Ubuntu 0.0.0) ERROR
>  Uncaught SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.

**Comment by steady-daddy** [comment]
Getting the same error using:

- **angular:**  2.3.0
- **angularfire2:** 2.0.0-beta.6
- **firebase:** 3.6.2
- **Firefox Developer edition:**  45.0a2

When I revert to previously working version:
````
    "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
````
the error goes away.

**Comment by tsvetomir** [comment]
Thanks @vicb @tbosch !

**Comment by nertzy** [comment]
Will there be a point release for this on npm?

**Comment by DzmitryShylovich** [comment]
they don't do releases on Friday. you can use `*-builds` if u need the fix rigth now

**Comment by englishandy** [comment]
is there a work around for this until fix? i just want to test a basic build with the "app works" simple code.

**Comment by vicb** [comment]
use the code in https://github.com/angular/angular/commit/4022173d1e682b78572c2ada6e2881185aa71824 (const -> var)

**Comment by vicb** [comment]
and should be in *-builds soon
