### ISSUE TITLE
Can't resolve module ./directives from form_providers.d.ts - NG 2.3.0

### ISSUE THREAD

**Issue by jwuliger** [angular/angular#13308]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using the latest version of the Angular-CLI and Angular 2.3.0, using `ng serve` or any other means to start the app causes Webpack to stop building due to this error:

`can't resolve module ./directives from C:/Code Projects/Web/request-it/node_modules/@angular/forms/src/form_providers.d.ts`

**Expected behavior**
I would run `ng serve` and my project would load on port 4200.

**Minimal reproduction of the problem with instructions**

1. Create a new Angular-CLI (Beta 22-1) project using `ng new` 
2. Upgrade all Angular dependencies to v2.3.0
3. Run `ng serve` and it will fail quickly.

**What is the motivation / use case for changing the behavior?**
I need to take advantage of the Zone.js and RxJS upgrades that were made.

**Please tell us about your environment:**

- Windows 10 Enterprise
- VS Code
- NPM v4.0.5
- Node v7.0
- Webpack Dev Server (Build into Angular-CLI)

* **Angular version:** 2.0.X

v2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript v2.1.4

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by DzmitryShylovich** [comment]
Can u reproduce it in plunkr? If no, I would say it's angular cli issue.

**Comment by jwuliger** [comment]
I am about to try in a Plunkr. First I thought that the problem was with using TypeScript 2.1.4. This is not the case. The problem still happens with TypeScript 2.0.3.

As for the Angular-CLI, the same project was working with NG 2.2.4. I see there is also a similar issue that was just filed that seems to be related to this.

**Comment by jwuliger** [comment]
The issue is #13296

**Comment by wulfsberg** [comment]
Also #13310. It seems 2.3.0 has made Angular-CLI angry in lots of creative ways.

**Comment by tbosch** [comment]
Angular-Cli beta 24 works with Angular 2.3.1 and above (2.3.0 won't work...).
Also make sure to not use TypeScript 2.1 yet.
