### ISSUE TITLE
javascript globals are not working in visual studio 2015 with Angular 2 (Confirm,window,alert etc...)

### ISSUE THREAD

**Issue by DineshkumarVellingiri** [angular/angular#13309]
**import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { Observable } from 'rxjs/Rx';
export class CounterPartsGuard implements CanActivate {
    canActivate(router: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | boolean {
        return confirm("are you sure?");
    }
}**

whenever using the confirm,window,alert etc.... globals of javascript in visual studio it cannot find or defined.How to overcome this issue.

Note:-

I am using VS2015 community edition and using angular 2 with MVC template...

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
