### ISSUE TITLE
@Input set array length issues

### ISSUE THREAD

**Issue by Scobee** [angular/angular#13300]
I'm submitting a:
[ x] bug report
[ ] feature request
[ ] support request

**Current behavior**
I am setting an input with some delay, but the variable options shows up as an array with length 0 (but with values in it) before the setTimeout .. and after the 1s timeout it has length 2 (as it should)

@Input()
set options(options:Object[]) {
    console.log(options);
    setTimeout(() => {
        console.log(options);
    }, 1000);
}

Response is:
First log:
Array[0] 0: Object 1: Object length: 2
Second log:
Array[2] 0: Object 1: Object

As you can see in the first console.log the array length shows up as 0, and I can't iterate on that object.

**Expected behavior**
First console.log should have Array[2]

**Minimal reproduction of the problem with instructions**
Above code takes care of minimal reproduction.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10 / WebStorm

* **Angular version:** 2.0.X
2.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> Above code takes care of minimal reproduction.

no, it doesn't. Pls provide a working repro in plunkr.

**Comment by DzmitryShylovich** [comment]
@Scobee did u fix it?
