### ISSUE TITLE
How to reentrance angular detector environment when callback of third-party api

### ISSUE THREAD

**Issue by suplch** [angular/angular#13304]
/assets/test.html
```
<!DOCTYPE html>
<html lang="en">
<body>
  <button onclick="window.parent.onMessage()">test third-party call</button>
</body>
</html>
```
class DetectorComponent
```
@Component({
  selector: 'app-detector',
  template: `
    {{value1}} {{value2}}
    <iframe src="/assets/test.html"></iframe>
  `
})
export class DetectorComponent implements OnInit {
  value1: string;
  value2: string;
  constructor(private ref: ChangeDetectorRef) {}

  ngOnInit() {
    this.value1 = 'hello';
    window['onMessage'] = () => {   // this method will be called by third-party library

        // this.ref.markForCheck();   // this line no use
        this.value2 = 'world';
        // this.ref.detectChanges();    this can apply for template immediately;

        this.someService.getBusiness().subscribe((result: any) => {
          this.value2 = result.dataValue;
        });
        // ......
        // other business logic and service callback
        // ......
    };
}
```
We must manually call this.ref.detectChanges() to let angular2 apply change to template.
I hope angular can reentrance automatic change mode like normal mode, because there are many business logic and service need to be executed in 'onMessage' callback.

**Comment by DzmitryShylovich** [comment]
You need to use `NgZone.run(() +> {...})` method

**Comment by suplch** [comment]
Oh, thanks very much, It is like angular1's $scope.apply();

**Comment by DzmitryShylovich** [comment]
I would say `this.ref.detectChanges(); ` is more like `$scope.apply();`. `NgZone.run` is different :)

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
