### ISSUE TITLE
route redirectTo not preserving query params

### ISSUE THREAD

**Issue by mdsauer** [angular/angular#13315]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Prior to release 2.3 query parameters were preserved through a configured route redirectTo.  This is no longer working in 2.3.  Is this an expected breaking change or was the prior behavior not correct?

**Expected behavior**
Query params preserved on a redirectTo, or at least allow it to be configured to do so.

**Minimal reproduction of the problem with instructions**
{ path: '',
    redirectTo: '/component1',
    pathMatch: 'full'
  },
  { path: 'component1', 
    component: Component1
  },

In Component1:
  ngOnInit(): void {
      let params = this.route.snapshot.queryParams;  //route is ActivatedRoute

Prior to 2.3 params passed in url as /?param1=val1&param2=val2 would be available to Component1

**Please tell us about your environment:**
Windows 7, VS Code

* **Angular version:** 2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, IE11

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by zoechi** [comment]
dup of #12664 ?

**Comment by DzmitryShylovich** [comment]
don't think so. According to:
> Prior to release 2.3 query parameters were preserved through a configured route redirectTo. This is no longer working in 2.3

it's a regression.

**Comment by mdsauer** [comment]
@DzmitryShylovich  I would be happy to create a repro but I am not familiar with creating a repro in plnkr.  I did see in another issue the following:
u can use http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 as a starting point
But it is not clear to me how I specify the version of angular to run under.  Can you point me to some instructions?

**Comment by DzmitryShylovich** [comment]
> But it is not clear to me how I specify the version of angular to run under. Can you point me to some instructions?

u don't need to specify anything. the plunkr already uses the latest version.

**Comment by mdsauer** [comment]
repro: http://plnkr.co/edit/EmmObNPt7lofzoM9YozT?p=preview

Result I get with this code running against 2.2.0 is:
Test Router Query Params
queryParams: params: {"param1":"val1","param2":"val2"}
routeData: params: {"param1":"val1","param2":"val2"}

**Comment by mdsauer** [comment]
I changed my redirect from an absolute to a local and now the query params are retained.  I think this issue can be closed.

**Comment by DzmitryShylovich** [comment]
@mdsauer u can close it yourself

**Comment by SusanAWAL** [comment]
@mdsauer can you put youe solution here, please?

**Comment by veroca** [comment]
@SusanAWAL a little late I guess, but I'll leave the comment here for future visitors.
To conserve the query params, instead of:
```
  { 
    path: 'whatever',
    redirectTo: '/component1'
  },
```

do:
``` 
  { 
    path: 'whatever',
    redirectTo: 'component1'
  },
```

**Comment by Ruluk** [comment]
I don't think this is ideal or logical. I don't see any reason why absolute paths shouldn't forward query params. At the very least, there should be a property to configure this.

**Comment by MaverickH** [comment]
The #1 reason to want to preserve those query params would be url re-writes where it is reasonable to assume the original url may be bookmarked by a user.

**Comment by FortinFred** [comment]
the workaround of the redirectTo without the leading "/" fails when using hash strategy.
