### ISSUE TITLE
routerLink doesn't invoke ngOnInit when only the id of the route changes

### ISSUE THREAD

**Issue by Kizmar** [angular/angular#13319]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm trying to use either routerLink on an anchor, or router.navigate() in the component to navigate to a different Id within the same route. Ex: from '/rate/1' to '/rate/2'. The resolver gets hit with the new Id, the correct API endpoint is hit, the address bar gets updated, but the constructor and ngOnInit don't get hit.

**Expected behavior**
ngOnInit would be invoked with the new route data.

**Minimal reproduction of the problem with instructions**
I will create one if it's completely necessary... I first want to see if this is a known issue.

**What is the motivation / use case for changing the behavior?**
I'm unable to link a user from one Id to another within the same route. Seems problematic.

**Please tell us about your environment:**
Windows 10 VM, using vscode, running the app with angular-cli in a command window.

* **Angular version:** 2.0.X
2.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   6.5.0

**Comment by DzmitryShylovich** [comment]
It's by design. See https://angular.io/docs/ts/latest/guide/router.html#!#reuse

**Comment by Kizmar** [comment]
@DzmitryShylovich Thank you for the link. Mimicking the observable params example...

**Comment by vicb** [comment]
thanks @DzmitryShylovich
