### ISSUE TITLE
Angular 2.3.0 does not start in Safari 9 - instead shows a strict mode error

### ISSUE THREAD

**Issue by ManuelRauber** [angular/angular#13311]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Current behavior**
When using Angular 2.3.0 with Safari 9, the application does not start up at all. Instead the console shows the following error message:

```
Error: (SystemJS) Strict mode does not allow function declarations in a lexically nested statement.
	eval@[native code]
	invoke@http://localhost:8000/lib/zone.js:229:31
	run@http://localhost:8000/lib/zone.js:113:49
	http://localhost:8000/lib/zone.js:509:60
	invokeTask@http://localhost:8000/lib/zone.js:262:40
	runTask@http://localhost:8000/lib/zone.js:151:57
	drainMicroTaskQueue@http://localhost:8000/lib/zone.js:405:42
	run@http://localhost:8000/lib/shim.js:4005:30
	http://localhost:8000/lib/shim.js:4018:32
	flush@http://localhost:8000/lib/shim.js:4373:12
	Evaluating http://localhost:8000/lib/@angular/compiler/bundles/compiler.umd.js
	Error loading http://localhost:8000/lib/@angular/compiler/bundles/compiler.umd.js as "@angular/compiler" from http://localhost:8000/lib/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js — zone.js:672
```

**Expected behavior**
Expected it, that the application works and starts up according to the [supported browser matrix](https://angular.io/docs/ts/latest/guide/browser-support.html). 

The same plunkr - as shown below - works as expected in Safari 10.

**Minimal reproduction of the problem with instructions**
To reproduce you can use the template offered when creating a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

Fire it up in Safari 9 and take a look into the console.

**Please tell us about your environment:**
macOS El Capitan 10.11.6

* **Angular version:** 2.3.0

* **Browser:** Safari 9.1.2

Error may be related to #13301

**Comment by thomashilzendegen** [comment]
Maybe it is due to this change? Was it "use strict" before?

https://github.com/angular/angular/commit/f5c8e0989d85bc064f689fc3595207dfb29413f4#diff-8700d5c4413733835abdc2480c6d5360R19

**Comment by sod** [comment]
Same error in phantomjs. The minified bundle works. So if you use `compiler.umd.min.js` instead of `compiler.umd.js`.

**Comment by Quantas** [comment]
I get the same errors in PhantomJS with webpack as well.

**Comment by vicb** [comment]
Could you please try to find the origin of the issue ?

**Comment by DorianGrey** [comment]
I'd suppose it's the same issue as mentioned here in https://github.com/angular/angular/issues/13301 , just with a less expressive error message.

**Comment by vicb** [comment]
Closing a a duplicate then. Thanks.
