### ISSUE TITLE
Can't bind directive over pseudo-element

### ISSUE THREAD

**Issue by dahfazz** [angular/angular#13318]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When creating a directive with selector: '.anyClassName:before' I receive the error "Can't bind to 'xxxxxx' since it isn't a known property of 'span'."
The same directive works perfectly with selector: '.anyClassName'

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Manipulating the DOM is a directive duty, then, if I need to manipulate pseudo-element I would need directive to be able to.

**Please tell us about your environment:**

Ubuntu, Sublime Text 3, Express server, angular-cli stack

* **Angular version:** 2.0.X

angular 2.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

tested on Chrome latest version 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr

**Comment by vicb** [comment]
Pseudo selectors are not supported (with the exceptions of `:not`).

_I don't even understand what `.anyClassName:before` would mean_
