### ISSUE TITLE
CookieXSRFStrategy send old values of the CSRF token after relogin to app (right after we received new cookie value)

### ISSUE THREAD

**Issue by VitalyVrublevskyy** [angular/angular#13313]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
CSRF token is incorrect. We send old version of token.

**Expected behavior**
We should inject CSRFToken related header based on current value of token from cookies.

**Minimal reproduction of the problem with instructions**
In my application I use CookieXSRFStrategy to handle CSRF token like this:
![image](https://cloud.githubusercontent.com/assets/8617175/21022121/18f54f0a-bd84-11e6-871a-e964dabdd450.png)

*STEPS TO REPRODUCE* 
1. Login to some application. In response I received cookies:
csrftoken=_PONBJe51vUEydcyLAXBiG2K1f53az3Oh_
2. Do any server request: Verify that we have valid 'X-CSRFToken' in each request's header.
3. Logout from application. 
- Force clear cookies  _csrftoken_ manually or programatically.
4. Login again to application.
- Received new csrftoken=_nOZlQHVNJqfDu9XUrzWsAfJfjou5HxC0_ in cookie
5. Do any server request and verify that sent OLD TOKEN (in my example: _PONBJe51vUEydcyLAXBiG2K1f53az3Oh_)

**What is the motivation / use case for changing the behavior?**
Because it's most common feature.

**Please tell us about your environment:**
Mac Os, Webstorm, npm

* **Angular version:** 2.1.2

* **Browser:** Chrome Version 54.0.2840.98 (64-bit)]
 
* **Language:** [all | TypeScript 2.0.3 | ES6/7 | ES5]

**Comment by vicb** [comment]
Please attach a small repro

**Comment by robwormald** [comment]
cc @mprobst - reading through the source, it *appears* this should work, as we call getCookie() for each request. 

The exception to this would be resubscribing to an existing Http request, as we're not calling getCookie() upon subscribe - in retrospect, we should probably change that, because it would be a fairly common use case to do something like

```
http.get(url)
  .retryWhen(reloginToServer) //if error, perform login, upon success, resubscribe to *existing* request
  .subscribe(...)
```

@VitalyVrublevskyy clearly you won't be able to repro your server side setup, but seeing the client side code would be helpful.

**Comment by VitalyVrublevskyy** [comment]
@robwormald , @vicb I attached appropriate  source code. This code related to my web application.
[Archive.zip](https://github.com/angular/angular/files/642016/Archive.zip). I can reproduce it issue in my **Ionic2** application as well.

More datails:
- **app.component**, **app.module** (Injecting CookieXSRFStrategy)
- **auth.service** handle authorization flow:

Steps:
- [x]  On login I do double request: check login and fetch current user details. I received coockie ('csrftoken'). For example 'csrftoken' = _PONBJe51vUEydcyLAXBiG2K1f53az3Oh_
- [x]  In each next request to the server I can see that we have 'X-CSRFToken' header with _PONBJe51vUEydcyLAXBiG2K1f53az3Oh_ in each request header
- [x]  On logout I clear programatically this  cookies. (I double checked that coockie is empty)
- [x]  Right after I relogin to application. I received new coockie 'csrftoken' = nOZlQHVNJqfDu9XUrzWsAfJfjou5HxC0 
- [x]  **document.cookie** return that we have NEW VALUE of  'csrftoken' = PONBJe51vUEydcyLAXBiG2K1f53az3Oh
- [ ] Do any server request and verify that application sent OLD TOKEN  in header 'X-CSRFToken' _PONBJe51vUEydcyLAXBiG2K1f53az3Oh_

**Comment by mprobst** [comment]
Rob is right, we call `getCookie()` intentionally on each request for this reason. It's particularly odd that you see a previous value @VitalyVrublevskyy. Some questions:

* Did you reload the Angular application in between (i.e. it's likely a stale browser cookie value) or is this with the application continuously running?
* Can you debug through and report what `document.cookie` returns at the various stages of the application (maybe just add logging)?

I'd like to clarify if this is the browser incorrectly caching your cookie, or if it's Angular incorrectly holding onto it.

What can be a common problem is that cookies are per path, so if you load your app once from `/foo` and once from `/bar`, you might accidentally set a cookie on different paths (which the browser then treats differently).

**Comment by VitalyVrublevskyy** [comment]
@mprobst Following up your questions:
- Browser refresh|F5 fix this issue. 
- Obviously yes. I double checked on each step using document.cookie. More details up.

As for the _cookies per path_: This problem appears on prod env (/foo)  and dev env (/bar) as well/

I going to prepare some short screen video to demonstrate all cases.

**Comment by mprobst** [comment]
@VitalyVrublevskyy thanks for debugging further!

When you reproduce the problem, can you do the following:

* follow your repro steps from above
* before sending out the last request (the one that has the wrong header), set a breakpoint here: https://github.com/angular/angular/blob/986abbe0b2ca0e33078db114637505996fa70bd7/modules/%40angular/http/src/backends/xhr_backend.ts#L198
* execute the request that would up with the wrong cookie value, check if
    * the method is being called at all
    * if you step through, what value gets returned from the underlying call
    * if the value returned by `document.cookie` (in code in the `browser_adapter`, try step into) is what you'd expect

I'm a bit puzzled by how this code could fail, unless you are resubscribing as @robwormald describes above.

**Comment by VitalyVrublevskyy** [comment]
Angular2 web app Video: _TBD_ 
Ionic2 app video: https://drive.google.com/open?id=0B08D5qEP4YtPRFFoWnJybFNGNTA
