### ISSUE TITLE
Proposal: add a 'Has pr' label

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#13320]
For example: https://github.com/angular/material2/issues/2042

So it will be easier to find issues for contribution :)

**Comment by vicb** [comment]
@mhevery @IgorMinar WDYT ? One problem I can image is that the label would not be applied...

**Comment by pkozlowski-opensource** [comment]
If a PR follows commit message convention (Fixes / Closes #XYZ) we wouldn't need labels as GH would link the 2 automatically. So I would prefer that we enforce commit messages rather than adding a new label that can quickly get outdated.

**Comment by DzmitryShylovich** [comment]
http://prntscr.com/dhcls0 I don't need to click on the issue to see if it has pr or not

**Comment by mhevery** [comment]
I believe we at one point had such a label, and we have gotten rid of it. I am fine with adding it back if we can be consistent about it, which in the past we have not been.
