### ISSUE TITLE
AOT (AngularFire) broken in 2.3.0

### ISSUE THREAD

**Issue by alxhub** [angular/angular#13327]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In 2.3.0 in AOT mode, my AngularFire application cannot inject `AngularFireDatabase` from a service. The generated DI code is:

```
get _DbService_36():import20.DbService {
    if ((this.__DbService_36 == null)) { (this.__DbService_36 = new import20.DbService(this.parent.get(import29.AngularFireDatabase))); }
    return this.__DbService_36;
  }
```

`this.parent.get` is incorrect here, as `AngularFireDatabase` is available at this level.

**Expected behavior**

It works in 2.2.x.

**Minimal reproduction of the problem with instructions**

This repro trivially reproduces the issue: https://github.com/alxhub/af-issue-repro. `npm run build` builds the app in AOT mode with rollup, then `app.js` and `index.html` in the root can be served. AOT code is generated in `ngfactory/`.

**Comment by vicb** [comment]
@alxhub I guess you you call `AngularFireModule.initializeApp(...)` in your app:

```ts
@NgModule({
  bootstrap: [RootComponent],
  declarations: [RootComponent],
  imports: [
    AngularFireModule.initializeApp({
      apiKey: '',
      authDomain: '',
      databaseURL: '',
      storageBucket: ''
    }),
    BrowserModule,
  ],
  providers: [
    DbService,
  ]
})
export class AppModule {}
```

Still the providers are not added.

**Comment by alxhub** [comment]
@vicb correct, the provider in question is a part of `AngularFireModule` itself, not the `ModuleWithProviders` that `initializeApp()` returns. So the problem reproduces either way.

**Comment by vicb** [comment]
@tbosch issue is:

```ts
// angularfire2.ts
import { FirebaseListObservable, FirebaseObjectObservable, FirebaseListFactory, FirebaseObjectFactory, AngularFireDatabase, FirebaseDatabase } from './database/index';

// ...

export { AngularFireAuth, AngularFireDatabase, FirebaseAuth, FirebaseDatabase, FirebaseListObservable, FirebaseObjectObservable, FirebaseListFactory, FirebaseObjectFactory, firebaseAuthConfig, AuthMethods, AuthProviders, WindowLocation };
```

We have no metadata for those symbols (this issue is about `FirebaseDatabase`).

Let's discuss this on Tuesday.
