### ISSUE TITLE
Failed to execute 'setAttribute' on 'Element': 'ng-reflect-active-object$' is not a valid attribute name.

### ISSUE THREAD

**Issue by feurjarx** [angular/angular#13332]
**I pass variable "activeObject$" through input() option in component

**Current behavior**
vendor.bundle.js:42872 EXCEPTION: Uncaught (in promise): Error: Error in ./BaseObjectReleasesPageComponent class BaseObjectReleasesPageComponent - inline template:170:43 caused by: Failed to execute 'setAttribute' on 'Element': 'ng-reflect-active-object$' is not a valid attribute name.
Error: Failed to execute 'setAttribute' on 'Element': 'ng-reflect-active-object$' is not a valid attribute name.
    at DomRenderer.setElementAttribute (http://beta.prwire:4201/vendor.bundle.js:32057:31)
    at DomRenderer.setBindingDebugInfo (http://beta.prwire:4201/vendor.bundle.js:32078:18)
    at DebugDomRenderer.setBindingDebugInfo (http://beta.prwire:4201/vendor.bundle.js:59773:24)
    at setBindingDebugInfo (http://beta.prwire:4201/vendor.bundle.js:19771:18)
    at http://beta.prwire:4201/vendor.bundle.js:19763:9
    at Array.forEach (native)
    at setBindingDebugInfoForChanges (http://beta.prwire:4201/vendor.bundle.js:19762:26)
    at Wrapper_EmailSubscriptionsBlockComponent.ngDoCheck (/AppModule/EmailSubscriptionsBlockComponent/wrapper.ngfactory.js:29:7)
    at CompiledTemplate.proxyViewClass.View_BaseObjectReleasesPageComponent0.detectChangesInternal (/AppModule/BaseObjectReleasesPageComponent/component.ngfactory.js:264:47)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://beta.prwire:4201/vendor.bundle.js:61297:14)

** OS:
 Linux user-desktop 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

ng version
angular-cli: 1.0.0-beta.21
node: 7.1.0
os: linux x64

* **Angular version:** 
"dependencies": {
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/router": "3.2.3",
    "angular2-cookie": "^1.2.5",
    "angular2-toaster": "^1.0.2",
    "core-js": "^2.4.1",
    "ng2-pagination": "^0.5.1",
    "rxjs": "5.0.0-rc.1",
    "systemjs": "0.19.41",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.2.3",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.22",
...

* **Browser:** Chrome

**Comment by Toxicable** [comment]
Please a minimum working repro plunkr like the Issue timeplate says

**Comment by vicb** [comment]
This is a duplicate (looks for an exiting issue for more details).

`Error: Failed to execute 'setAttribute' on 'Element': 'ng-reflect-active-object$' is not a valid attribute name` -> the attribute name is not supported by your browser - even though it's valid by spec.

We should sanitize the value. In the meantime you could disable debug infos

**Comment by feurjarx** [comment]
working situation:  
```TS
@Input()
asyncObservableObject: Observable<any>;
```
```HTML
<app-my-component [asyncObservableObject]="observableObject$"></app-my-component>
```
Not working situation:  
```TS
@Input()
observableObject$: Observable<any>;
```
```HTML
 <app-my-component [observableObject$]="observableObject$"></app-my-component>
```

### It seems the problem in the dollar

**Comment by yuanfeiz** [comment]
Alias binding for the above working situation doesn't work:

```
@Input('dataRx')
data$: Observable<any>

<app-my-component [dataRx]="observableObject$"></app-my-component>
```

Logs:
```
EXCEPTION: Uncaught (in promise): Error: Error in ./AppComponent class AppComponent - inline template:23:25 caused by: Failed to execute 'setAttribute' on 'Element': 'ng-reflect-data$' is not a valid attribute name.
Error: Failed to execute 'setAttribute' on 'Element': 'ng-reflect-data$' is not a valid attribute name.
```

**Comment by jcjolley** [comment]
Any word on this?  Appending $ to the end of an observable is becoming common practice.  It would be nice to support this.

**Comment by namnn** [comment]
What if we do a set only Input() and inside bind the observable to another public variable with $ postfix?
A temporary feeling while waiting for this issue to be fixed.
```
@Input()
set isLoading(data: Observable<boolean>) {
  this.isLoading$ = data;
}
public isLoading$: Observable<boolean>;
