### ISSUE TITLE
Angular Material Bidirectional Support

### ISSUE THREAD

**Issue by lbrevity** [angular/angular#13335]
Does Angular 1.5.8 support for BiDirectional for Angular Material? I tried with $mdBiDirectionalProvider, but it throws unknown provider error.

**Comment by robwormald** [comment]
I think you're looking for https://github.com/angular/angular.js or https://github.com/angular/material

**Comment by lbrevity** [comment]
@robwormald No, Actually I am working with Angular material only with reference link you mentioned. But now I want to RTL support, but that is not working.

**Comment by lbrevity** [comment]
@robwormald Can you please reopen this? whether it is issue of angular version or material version?

**Comment by robwormald** [comment]
@lbrevity this is the repository for angular2. So you should re-open it on the appropriate repo for angular 1.x
