### ISSUE TITLE
open angular in chrome

### ISSUE THREAD

**Issue by craigcosmo** [angular/angular#13336]
My default system browser is safari.

When I do `npm run start` I want angular app open in chrome.

How can I do this?

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
