### ISSUE TITLE
Compiler bundle breaks in strict mode - Functions cannot be declared in a nested block in strict mode

### ISSUE THREAD

**Issue by blacksonic** [angular/angular#13345]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When upgrading to 2.3.0 tests break with the following error message.
```
SyntaxError: Functions cannot be declared in a nested block in strict mode
  at webpack:///~/@angular/compiler/bundles/compiler.umd.js:26587:0 <- client/test.boot.js:28051
```

**Expected behavior**
After upgrading tests continue to run, because no breaking change was introduced.

**Minimal reproduction of the problem with instructions**
Inside my starter which is compiled with Babel upgrade the dependencies to 2.3.0
https://github.com/blacksonic/angular2-babel-esnext-starter

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Ubuntu 16.04, Node 6.9.1

* **Angular version:** 2.3.0

* **Browser:** PhantomJS, Chrome, all
 
* **Language:** ES6/7

**Comment by DzmitryShylovich** [comment]
Already fixed https://github.com/angular/angular/issues/13301

**Comment by blacksonic** [comment]
Thanks for pointing out
