### ISSUE TITLE
window.addEventListener is undefined in IE right after opening new window

### ISSUE THREAD

**Issue by marcovdb** [angular/angular#13343]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This issue has been giving me a lot of headache in the past days. In one part of my application I open up a new window using window.open, but I want to attach some code to the window's beforeclose event. Window.open returns a reference to the window object, but in IE if I access the reference right after opening the window the addEventListener method is undefined. If I wrap it in a short timeout it's usually OK, but this feels hackish an unreliable to me.

I know it has something to do with Angular because this only happens in my Angular app. My current guess it's because Zone.js monkey-patches the addEventListener function and it's taking some time in IE.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Check the following Plunker in IE and in Chrome and observe the difference...
https://plnkr.co/edit/nslCzrn2AmUVROeqJVBO?p=preview

**What is the motivation / use case for changing the behavior?**
We should be able to reliably access a newly opened window.

**Please tell us about your environment:**

-

* **Angular version:** 2.0.X

2.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Internet Explorer 11
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
1. Could you please try to reproduce with zone.js only (no angular),
2. If you have such a repro please reopen on angular/zone.js

thanks

**Comment by marcovdb** [comment]
Reproduced with Zone.js only. Reopening the issue there!
