### ISSUE TITLE
`core_1.Version is not a constructor` error on build

### ISSUE THREAD

**Issue by artigat1** [angular/angular#13342]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behaviour**
A project that previously was building has stopped building when all node packages are re-installed. 

**Expected behaviour**
Should build as normal.

**Minimal reproduction of the problem with instructions**
I've created a hello world project using angular-cli to show the problem. The project can be found at: https://github.com/artigat1/hello-world. This [commit](https://github.com/artigat1/hello-world/commit/669dfd8c522470f40e72eab369886d673736ddb6) shows the changes I made to package file. 

I use Appveyor for continuous integration, so the [successful build](https://ci.appveyor.com/project/artigat1/hello-world/build/1.0.2) and [unsuccessful build](https://ci.appveyor.com/project/artigat1/hello-world/build/1.0.3) can be seen on there.

**What is the motivation / use case for changing the behaviour?**
My project is no longer building.

**Please tell us about your environment:**
angular-cli: 1.0.0-beta.20-4
node: 6.9.2
os: win32 x64

* **Angular version:** 2.0.X
2.2.4 (~2.2.1)

* **Browser:** [all]
 
* **Language:** [TypeScript 2.0.3]

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by artigat1** [comment]
Fixing `@angular/compiler-cli` to version 2.2.4 has fixed the problem for me. Thank you.

**Comment by veton** [comment]
The problem is package generated by **ng init** references  @@angular 2.0.0-rc.1, so
```
ng init
ng build
```
will ultimately fail

**Comment by bruno-serfe** [comment]
Hey guys I'm facing same issue with Angular 2.4.9.. any ideas?

/modules/@angular/compiler-cli/src/version.ts:19
export const VERSION = new Version('2.4.9');
^
TypeError: core_1.Version is not a function
at Object. (/modules/@angular/compiler-cli/src/version.ts:19:24)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/modules/@angular/compiler-cli/index.ts:13:1)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/node_modules/src/main.ts:7:1)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/node_modules/src/plugin.ts:3:1)

**Comment by VijayIvy** [comment]
I have the below angular config. But i am getting "compiler_1.Version is not a constructor TypeError: compiler_1.Version is not a constructor" error. Please help me.

Angular CLI: 7.0.7
Node: 9.7.1
OS: win32 x64
Angular: 4.3.6
... common, compiler, core, forms, http, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/compiler-cli             7.0.4
@angular/language-service         7.0.4
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              5.4.2
typescript                        3.1.6
webpack                           4.19.1
