### ISSUE TITLE
Directive attribute selectors with dot notation should support assignments to maps.

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/angular#13355]
Currently dot notations used in selectors are supported for:

1)  **class** prefix:   `<div [class.someName]="whichClass">`
2)  **style**  prefix: `<div [style.opacity]="someTransparency">`
3)  **full property names** (fixed with PR #13351) `<div [fx-layout.xs]="direction">`

However (3) requires the following directive/component configuration:

```ts
Directive({selector: '[fx-layout], [fx-layout.xs]'})
export class LayoutDirective {  
  @Input('fx-layout') layout = 'row';
  @Input('fx-layout.xs') layoutXs;
}
```

where the full property is mapped to a unique Input variable.

DESIRED:

Dot notation should optionally support property maps:

```ts
Directive({selector: '[fx-layout]'})
export class LayoutDirective {  
  @Input('fx-layout') layout = { defaultVal : 'row' }
}
```

And attributes selectors with property chains should update fields in the parent property.
e.g.

`<div fx-layout.xs="east">` would result in the `layout == { defaultVal : 'row', xs : 'east' };`

and 

`<div fx-layout.xs.visits="3">` would result in the `layout == { defaultVal : 'row', xs : { visits : '3' }}` 

*Considerations*:

This should only work when the selectors Input property is a **map**. If it is a `string  | number | boolean` then a full property name is used instead of property chain parsing/injection; this allows existing dot notations using (3) to  work as expected.

Perhaps the rules would be:

1)  Does an `@Input(<full-selector>) someProperty` exists, use that.
2)  Does the `@Input(<root-selector>) someProperty : Map|Object` exist, then inject the value 
3)  Throw a parse error ?

**Comment by ThomasBurleson** [comment]
@vicb, @jelbourn, @mhevery  - FYI.

**Comment by vicb** [comment]
@ThomasBurleson we have discussed that with Misko and think it's reasonable.

However:
```
Directive({selector: '[fx-layout]'})
export class LayoutDirective {  
  @Input('fx-layout') layout = { defaultVal : 'row' };
}

<div [fx-layout.xs]="'east'"> 
```

would only work if `fx-layout` is bound to a map and also the `defaultVal` key makes no sense here.

```
Directive({selector: '[fx-layout]'})
export class LayoutDirective {  
  @Input('fx-layout') layout = {};
  @Input('prop.ali.as') map = {}; 
  
}

<div [fx-layout.xs]="'east'" [prop.ali.as.key]="0">

// would result in 
layout = {xs: 'east'};
map = {key: 0}; 
```

I don't think angular should be smart and try to see if the property is a map. The user should write valid code.
However TS type checking would help here.

**Comment by ThomasBurleson** [comment]
@vicb - So the dot notation would expect a map: cool! 

Question 1: What if the user does this:

```html
<div [fx-layout]="'row'" [fx-layout.xs]="'east'"></div>
```  

Remember that [for flex-layout] the selector without the dot notation is **also** allowed.  

*  What would happen to the imperatively initialized object ? 
*  Which attribute would fire first ?

I think the only reasonable solution is that using the selector without dot notation must also inject the value into the map using  some **default key**.

**Comment by vicb** [comment]
wrt to your first question:
- it would set your prop to `'row'`
- it would set the `xs` prop to `'east'`

same as `let p = 'row'; p.xs = 'east'`

> I think the only reasonable solution is that using the selector without dot notation must also inject the value into the map using some default key. 

reasonable for your use case ;)
The semantic should be the same as JS. Do you expect `a = 0` to set a value of `{default: 0}` ? IMO this would be much more unexpected !

**Comment by ThomasBurleson** [comment]
My primary concern is that the new support for selector property chains + @Input maps will break existing library uses of (3) above.

**Comment by ThomasBurleson** [comment]
@vicb - is your intention the following that 

```
<div fx-layout.xs="column"></div>
```
would internally do this
 ```ts
directive_instance.layout.xs = <some value>;
```

**Comment by vicb** [comment]
> My primary concern, however, is that this new feature will break existing library

Could you expand on that ? (I don't see why the proposal would break anything)

> use Maps internally

`Map`s and `{}` are different could we please not use `Map` here (I don't think you want `Map`, right ?)

> is your intention that this feature would do the following...

That would be the case if you have a `@Input('fx-layout') layout;` on the directive.

**Comment by CaerusKaru** [comment]
It's been a year since this has been posted, has there been any development on this? If there's an agreed-upon design, I'd be happy to implement.

**Comment by mhevery** [comment]
This is something which we would like to implement. It is currently on back burner pending Ivy implementation. The reason is that any such implementation would now:
-  have to be done twice (once for Render2 and once for Ivy) and 
- any new syntax we introduce would decrease the future possibilities for selector-less directives syntax. So this really has to be designed in that context.

**Comment by ThomasBurleson** [comment]
Thanks for the update @misko

**Comment by wiegell** [comment]
any news?
