### ISSUE TITLE
How to associate/map a DOM instance/ElementRef with its component instance in directives?

### ISSUE THREAD

**Issue by sampleapp** [angular/angular#13357]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As far i know, there is no way to do that. 

**Expected behavior**
Easily map ElementRef to its parent Component in directive. 

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**

For example: (pseudo code, not accurate just to give an idea)
\<comp1 mouseHandlingDirective="onSpecialChildFound($child)">
\<child1/>
\<child2/>
\</comp1>

I need to return component (child1 or child2) from mouseHandingDirective on comp1 via callback or event. 

based on some complex user interaction it calls back comp1 with identified child. For simplicity say child2 is selected by user.

I get, there are other ways to get this done. Moving directive on child which sent event back to parent, but assumes childs are dumb and comp1 becomes responsible for handling user interactions and identifying and not child (performance reason, or may be one can not modify child-3rd party).

One can associate a id with DOM element and search back on callback to comp1 from directive. However i feel we could easily map dom el to containing parent component via framework. 

**Please tell us about your environment:**
NA

* **Angular version:** 2.0.X
Latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

* **Node (for AoT issues):** `node --version` =   
NA

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
