### ISSUE TITLE
Proposal: async local storage module

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular#13354]
**I'm submitting a ...**
```
[X] feature request
```

**Current behavior**
Angular 2 does not provide any service for local storage, and leaves it to the user.

**Expected behavior**
Angular 2 should provide a module for local storage.

**What is the motivation / use case for changing the behavior?**
Angular 2 is (mostly) for building apps. Nearly every app needs at least some local storage (for the auth token, user profile or settings...).

Native APIs are a mess : localStorage is simple but synchronous (so not efficient), IndexedDB is asynchronous but too difficult to use for most developers (and not coherent with Angular observables, as it uses the old events callback hell).

As a trainer, it's the only subject of the course where I need to say to students : "well, you'll have to do it on your own". Angular 2, as a framework, should take care of this important feature for apps. Especially when it does so for HTTP where it's not that useful (as it's quite the same as the new fetch API).

**Proposal**
I've already done this module : [https://github.com/cyrilletuzi/angular2-async-local-storage](https://github.com/cyrilletuzi/angular2-async-local-storage)

It uses IndexedDB to be efficient, but via a simple API like localStorage. All wrapped in RxJS observables, to be coherent with the others Angular modules.

It's already bundled like an official Angular module (I copied the way @angular/http works). It's already compatible with AoT, and even with Universal. The only thing missing is unit tests (would need some help on this).

I can start a PR if the proposal is accepted.

**Comment by Toxicable** [comment]
In your Module the only provider is IndexedDb with a fallback to localStorage, since Angular is Platform agnostic, so how would it work with other platforms?

**Comment by cyrilletuzi** [comment]
There's not just a localStorage fallback, as explained in the README, there's also a MockDatabase fallback (non persistent storage in a simple object). So the module is platform agnostic, and as mentioned it's already compatible with other platforms, like Universal server rendering.

If I've understood what's ongoing in Universal, it could even be improved to be transferred from server to client and vice versa, with UniversalCache (@gdi2290).

**Comment by Toxicable** [comment]
I saw the MockDatabase but didn't think it was a reasonable substitute for localstorage or IndexedDB due to it's non persistent behavior. My opinion is that it should have an Abstract class of some sorts with pluggable providers similar to how Http works, and example can be found here https://angular.io/docs/ts/latest/cookbook/dependency-injection.html#!#useclass.
This way it much be much easier for users to plug in their own implementations for whatever platform they might be using.

**Comment by cyrilletuzi** [comment]
I used a factory because the module has to test which API is available or not, but yes, there is surely a better way to manage the providing part to be pluggable. I wasn't very confident when doing this part.

Storage doesn't need to be persistent on the server as it's a storage for the client. The MockDatabase is essentially here to avoid errors in other platforms, when the browser APIs are not available, it's not aimed to be directly use by the server. Eventually client and server should communicate data to each other (for the server to pre-render with the right data for example), but that would be the role of Universal.

**Comment by DzmitryShylovich** [comment]
I haven't seen you impl but it whould be nice to have api similar to http:

```

class Storage {
  constructor(storageBackend:StorageBackend)
  setItem(key, value){ return this.storageBackend.setItem(key, value);
}

abstract class StorageBackend {
  setItem(key, value):Promise<any>
 }

class LocalStorageBackend implements StorageBackend {
  setItem(key, value){ return Promise.resolve(localStorage.setItem(key, value))
}
```

**Comment by cyrilletuzi** [comment]
There is already a similar structure, with an abstract class (AsyncLocalDatabase), I think the potential problem is how I initialize the classes and provide them in the module.

**Comment by Toxicable** [comment]
I'm going to be investigating something like this for angular/universal soon
