### ISSUE TITLE
deregister $on handlers on $destroy

### ISSUE THREAD

**Issue by secrettriangle** [angular/angular#1335]
If an event handler is registered like so:
```js
$scope.$on('evt', function () {/* do stuff */});
```

Angular should add the handler to an array internally and deregister it when the scope is destroyed:
```js
$scope.$on('$destroy', function () {
    deregisterFns.forEach(function (deregister) { deregister(); });
});
```

**Comment by pkozlowski-opensource** [comment]
Wrong repo https://github.com/angular/angular.js

**Comment by secrettriangle** [comment]
OK, filed a new issue: angular/angular.js#11563
