### ISSUE TITLE
Metadata extractor requires symbols third-party packages to be exported from index.ts

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#13350]
### Reproduction
https://github.com/jelbourn/aot-index-bug-repro

1. Clone the repo
2. `npm i`
3. `ng build --aot`

### The problem
When running `ngc`, this error occurs:
```
can't resolve module ./autosize from 
/tmp/aot-index-error/node_modules/@angular/material/input/input.d.ts

Cannot read property 'MdTextareaAutosize' of undefined, 
resolving symbol MdInputModule in 
/tmp/aot-index-error/node_modules/@angular/material/input/input.d.ts, 

resolving symbol MdInputModule in
/tmp/aot-index-error/node_modules/@angular/material/input/input.d.ts
```

The pertinent code is in `node_modules/@angular/material/input` (must be version `2.0.0-alpha.11` _exactly_)

* `autosize.d.ts`, `autosize.js`, and `autosize.metadata.json` exist in the appropriate directory
* `MdTextareaAutosize` is defined in `autosize.d.ts` and has its metadata in `autosize.metadata.json`

If I add 
```ts
export { MdTextareaAutosize } from './autosize';
```
To `index.d.ts`, everything works as expected.

### Other info
I had multiple reports of this from several users on the material repo, so it's not just isolated to a single environment. 

Angular 2.2.3
Material 2.0.0-alpha.11
Node 6.9.0
TypeScript 2.0.10

CC @tbosch @chuckjaz

**Comment by JoostK** [comment]
Closing as obsolete.
