### ISSUE TITLE
only first radio input in ngFor can be disabled

### ISSUE THREAD

**Issue by geisi93** [angular/angular#13370]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a form which creates radio inputs in a for loop. I want them to be disabled, however only the first radio input will be disabled and gets the disabled html tag) but all of them get the ng-reflect-is-disabled="true" attribute.

**Expected behavior**
Every radio input should get the disabled tag in this case.

**Minimal reproduction of the problem with instructions**
```html
<form #form="ngForm" (ngSubmit)="logForm(form.value)">
      <div *ngFor="let field of fields">
        <div class="form-group">
           <div class="row">
              <div class="col-sm-1" *ngFor="let choice of field.choices">
                <label class="radio-inline nowrap">
                  <input type="radio" [disabled]="true" [name]="field.name" [(ngModel)]="field.value" [value]="choice.name"/>
                  <span>{{choice.description}}</span>
                </label>
              </div>
            </div>
        </div>
      </div>
  </form>
```

Plnkr demo:

https://plnkr.co/edit/rvGSf7?p=info

* **Angular version:** 2.3.0

* **Browser:** Chrome
 
* **Language:** all

Thanks in advance

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr

**Comment by geisi93** [comment]
plnkr: https://plnkr.co/edit/rvGSf7?p=info

**Comment by DzmitryShylovich** [comment]
All radios have the same name. This is why only first one is disabled. Angular uses input name to distinguish  inputs. 

Correct version: https://plnkr.co/edit/kHbP0eUpO54FJFcVcvNp?p=preview

**Comment by geisi93** [comment]
Okay, thanks for the quick response and explanation. Then, how can I get only the selected value on form submit?

**Comment by DzmitryShylovich** [comment]
This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
