### ISSUE TITLE
 location subscribe returns an object instead of "real" interface

### ISSUE THREAD

**Issue by lilling** [angular/angular#13378]
**I'm submitting a ...**  (check one with "x")
[X] feature request

**Current behavior**
the location.subscribe onNext() method gets 'any'.
![image](https://cloud.githubusercontent.com/assets/11631465/21089589/047e4a20-c042-11e6-85d2-5ba78de39b45.png)

**Expected behavior**
But the location.subscribe sends a popState object that described in [https://github.com/angular/angular/blob/2.3.0/modules/@angular/common/src/location/location.ts#L60-L63](url)
![image](https://cloud.githubusercontent.com/assets/11631465/21089600/19141cf8-c042-11e6-85fe-4e1cdcb6d0e0.png)

**Steps to reproduce**
Just call Loaction.subscribe and the callback you get is an Object instead of real ts class.

**What is the motivation / use case for changing the behavior?**
When I'm subscribing to it. I would like 

**Please tell us about your environment:**
windows 10 vsCode

* **Angular version:** 2.0.0

* **Browser:** [all]

 
* **Language:** [all ]

**Comment by DzmitryShylovich** [comment]
Pls provide:
1. small repro in plunkr.
2. steps to reproduce
3. expected behaviour

**Comment by DzmitryShylovich** [comment]
>  instead of real ts class

why would you want it to be a class?

**Comment by vicb** [comment]
The object has the same prototype as the **instance of** the class. This is valid.
