### ISSUE TITLE
es6 files contain double sourcemaps mappings

### ISSUE THREAD

**Issue by ocombe** [angular/angular#1338]
When you install this repository from npm, the es6 folder is created with the es6 files and the sourcemap files.
But the .es6 files have two sourcemaps mappings at the end instead of one. Example for core.es6:

```js
export * from './src/core/annotations/visibility';
export * from './src/core/compiler/interfaces';
export * from './src/core/annotations/template';
export * from './src/core/application';
export * from './src/core/annotations/di';
export * from './src/core/compiler/compiler';
export * from './src/core/compiler/template_loader';
export * from './src/core/compiler/view';
export * from './src/core/compiler/view_container';
export * from './src/core/dom/element';
//# sourceMappingURL=core.js.map

//# sourceMappingURL=./core.map
```

The folder only contains the file "core.map", so only the second mapping is the correct one. The problem is that only the first mapping is loaded, the second one is ignored (in the case of the webpack sourcemaps loader) :(

**Comment by alexeagle** [comment]
Yup, we have a todo to fix the original sourcemap written by traceur rather than append a second one. Sourcemaps are even more broken than that, in fact. While this issue is cosmetic, most of the time the sourcemap doesn't even work.

**Comment by naomiblack** [comment]
@rkirov is this alpha-28 urgent? it was on alex's to do list.

**Comment by rkirov** [comment]
Nope, not urgent (but good to keep track off). Outputting clean and usable `.d.ts` is more urgent than fixing sourcemaps

**Comment by mhevery** [comment]
obsolete, we no longer use traceur
