### ISSUE TITLE
Custom decorator doesn't work with aot compilation

### ISSUE THREAD

**Issue by Michael77** [angular/angular#13386]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The decorator is called "authenticated" and calls the method it is decorating if the current user is authenticated, otherwise the login/signup modal is opened up instead.

**Expected behavior**
When I compile my app with the --aot flag (I'm using angular-cli), my custom decorator does not work as expected. This should continue to work the same with aot compilation.

**Minimal reproduction of the problem with instructions**
This is the code for the decorator: 
```
export interface AuthenticatedServices {
	authService: AuthService;
}

export function authenticated(target: AuthenticatedServices, propertyKey: string, descriptor: TypedPropertyDescriptor<any>) {
	let originalMethod = descriptor.value;

	descriptor.value = function(...args: any[]) {
		if (!this.authService.isAuthenticated$.value) {
			return this.authService.openLoginSignup();
		}

		return originalMethod.apply(this, args);
	};
}
```
This decorator can be used on any method of a class that implements the AuthenticatedServices interface like so:
```
@Component({selector: 'upvote', templateUrl: 'upvote.component.html'})
export class AwesomeUpvoteComponent implements AuthenticatedServices {
	constructor(public authService: AuthService) {}

        @authenticated
        toggleUpvote() {
	        this.superUpvotingServiceOnlyAuthenticatedUserCanCall.toggleUpvote();
        }
}
```

**Please tell us about your environment:**

* **Angular version:** 2.2.1

* **Browser:** Chromium 55

 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` = 7.2.1

**Comment by ericmartinezr** [comment]
Have you seen this issue https://github.com/angular/angular-cli/issues/2799 ?

**Comment by Michael77** [comment]
Nope. I did a search for 'decorator' before posting, but nothing relevant came up.

**Comment by Michael77** [comment]
Didn't realize it was a cli issue. Thanks for the link.

**Comment by robwormald** [comment]
closing as this is specific to angular-cli.
