### ISSUE TITLE
Proposal: when inheriting components, merge decorators at the key level

### ISSUE THREAD

**Issue by tycho01** [angular/angular#13387]
**I'm submitting a ...**  (check one with "x")
- [x] feature request

I previously posted this suggestion at the [inheritance](https://github.com/angular/angular/issues/11606) thread, where as a follow-up proposal it was deemed out of scope -- hence the issue got closed.

**Current behavior**

We [recently](https://github.com/angular/angular/issues/11606#issuecomment-262315256) gained component inheritance, with the following semantics:
> only use the last decorator of each kind (e.g. @Component / ...)

**Expected behavior / What is the motivation / use case for changing the behavior?**

It feels like it might make more sense to merge metadata on a by-key basis.
You'd likely need a new decorator to specify a new selector anyway, at which point you can no longer transfer e.g. that `ChangeDetectionStrategy` / `ViewEncapsulation`.

To illustrate, here was my existing solution for decorator inheritance, which did take care of key-basis merging (forgive my use of `lodash`), here including array concatenation (follow-up proposal):

```ts
// annotations.ts

let _ = require('lodash');
import { Component, Directive, Pipe } from '@angular/core';

// extendible Component decorator, extended from here to merge items:
// http://stackoverflow.com/questions/36837421/extending-component-decorator-with-base-class-decorator/36837482#36837482
let mergeMetadata = (metadataClass) => function(annotation: any) {
  return function (target: Function) {
    let parentTarget = Object.getPrototypeOf(target.prototype).constructor;
    let parentAnns = Reflect.getMetadata('annotations', parentTarget);
    if(_.size(parentAnns)) {
      let parentAnn = parentAnns[0];
      Object.keys(parentAnn).forEach(key => {
        if (!_.isNil(parentAnn[key])) {
          if (!_.isNil(annotation[key])) {
            if (_.isArray(parentAnn[key])) {
              annotation[key] = parentAnn[key].concat(annotation[key]);
            } else if (_.isObject(parentAnn[key]) && _.isObject(annotation[key])) {
              Object.assign(annotation[key], parentAnn[key]);
            } else {
              annotation[key] = parentAnn[key];
            }
          } else {
            annotation[key] = parentAnn[key];
          }
        }
      });
    }
    let metadata = new metadataClass(annotation);
    Reflect.defineMetadata('annotations', [metadata], target);
  }
}

export let ExtComp = mergeMetadata(Component);
export let ExtDir = mergeMetadata(Directive);
export let ExtPipe = mergeMetadata(Pipe);

// in component file: import `ExtComp`, then decorate components with `@ExtComp` rather than `@Component`
```

Stated concern:
> [I]t is easier to merge on an override strategy than it is to override on a merge strategy.
You can't really override a prop on a merge strategy, you'll have to redefine all the props (the whole `@Component`) while if you want to merge on an override strategy you just need to redefine the property you want to merge (for example `styles:` ).

My interpretation:

- PR behavior: override. If the parent's decorator was exactly what you needed, you're good. If you want any property different, you'll have to redo them. You say "property you want to merge (for example `styles:` )". I suppose that's right, though it assumes you've exported the parent's decorator properties before using them there; Angular won't otherwise expose them to you to reuse (be it in adjusted form).

 - Alternative behavior: naive 'merge'. This is essentially an override on a per-property basis. If you wanted the same as the parent's decorator properties, you're good. If you wanted to change a property, you're good, just override it. If you wanted to remove one, override it with `null`. If you wanted to override an array, go ahead. If you wanted to add to an array, you have a problem, since unless you've manually exported the original for reuse, you won't have it available. AFAICT, this approach does not yet bring much controversy so far.

**Comment by tycho01** [comment]
### Optional follow-up proposal: concatenating arrays

- My current behavior: merge with array concat / object merge, see the code snippet above. For scalar properties, identical to the above. For arrays/objects, this facilitates adding at the expense of an easy way to remove array items.

To go over the properties for a bit:
```ts
export interface Directive {
  selector?: string;
  inputs?: string[];
  outputs?: string[];
  host?: {[key: string]: string};
  providers?: Provider[];
  exportAs?: string;
  queries?: {[key: string]: any};
}

export interface Component extends Directive {
  changeDetection?: ChangeDetectionStrategy;
  viewProviders?: Provider[];
  moduleId?: string;
  templateUrl?: string;
  template?: string;
  styleUrls?: string[];
  styles?: string[];
  animations?: AnimationEntryMetadata[];
  encapsulation?: ViewEncapsulation;
  interpolation?: [string, string];
  entryComponents?: Array<Type<any>|any[]>;
}

export interface Pipe {
  name: string;
  pure?: boolean;
}

export interface Input {
  bindingPropertyName?: string;
}

export interface Output { bindingPropertyName?: string; }

export interface HostBinding { hostPropertyName?: string; }
```

With that, the latter proposal becomes largely about whether the following properties would be desirable enough to more easily add to even at the potential expense of not being able to override existing items easily (mostly applies to arrays):
- Directive:
  - arrays: inputs, outputs, providers
  - objects: host, queries
- Component: also these (arrays): viewProviders, styleUrls, styles, animations, entryComponents

My interpretation here: having 'too much' of these could likely not hurt except potentially in the case of styles, in which case on could technically still override them at the style level, though it'd beg the question why you'd have the parent pass on a property you'd deemed not worth inheriting. I'd be inclined to consider the ability to easily add to these as out-weighing that. That said, I don't see this as half as important as the main proposal of merging on a key-basis (even if this were to overwrite arrays).

**Comment by vicb** [comment]
We do not plan to change the current inheritance behavior.

_It has known bugs as #13303 that we will fix_

**Comment by tycho01** [comment]
@vicb for posterity, could you perhaps elaborate on that? I wasn't able to find any comments on this in the previous thread or meeting notes.

**Comment by vicb** [comment]
fixing 13303 should hopfully happen tomorrow.
The behavior is described in the commit comment and we'll work on a more extensive docs for angular.io.

Anything else I missed ?

**Comment by tycho01** [comment]
Sorry, I was particularly curious about the decision to, in my interpretation, facilitate the sub-classing use-case up to the current point yet seemingly no further.
Was this coming from the perspective that suddenly allowing inheritance of non-overwritten keys would form a potentially breaking change from the previous commit (if already part of a release)?

**Comment by vicb** [comment]
every one expect/wants a different behavior and it is not possible to satisfy every request.
we have picked the behavior that we think is the more flexible.
also we consider that this is case should be rare.

**Comment by tycho01** [comment]
Thank you for elaborating.

**Comment by robgha01** [comment]
i cant figure out way this behavior should stay as it is now... for me its clearly broken, to say a replace behavior is equal to inheritance is just wrong it goes against everything abstraction stands for.

**Comment by robgha01** [comment]
@tycho01 yes, but i wanted to use the original "Component" decorator i ended up with this:
```
import { isPresent } from "@angular/core/src/facade/lang";
import { IDescribeReflect as DescribeReflect } from "../declarations/IDescribeReflect";

export function Inherit() {
    return (target: Function) => {
        let reflect: DescribeReflect = window["Reflect"];
        let metaInformations = reflect.getOwnMetadata("annotations", target);
        if (metaInformations) {
            let parentTarget = Object.getPrototypeOf(target.prototype).constructor;
            let parentMetaInformation = reflect.getMetadata("annotations", parentTarget);

            for (let metaInformation of metaInformations) {
                for (let parentMetadata of parentMetaInformation) {
                    if (parentMetadata.constructor === metaInformation.constructor) {
                        Object.keys(parentMetadata).forEach(key => {
                            if (!isPresent(metaInformation[key])) {
                                console.log(`Inheriting key: $(key) with value: $(parentMetadata[key])`);
                                metaInformation[key] = parentMetadata[key];
                            }
                        });
                    }
                }
            }
        }
    }
}
```
then i can do,
@Inherit()
@Component({
    selector: "search-box"
})

maybe not the best or most elegant solution but i dide not want to replace the Component as it may change or trigger someting else i am not aware of but i dide get alot of inspiration.

**Comment by tycho01** [comment]
Interesting, I must say I like the idea a lot! :)
One thing I'd been worried about with my approach was that e.g. the build scripts used by Ionic would scour files for the literal `@Component` decorator. I'd been wondering if I should've just exported my augmented decorators under that original name as well, but your approach is probably more elegant!
