### ISSUE TITLE
Router double dots does not work properly when navigating

### ISSUE THREAD

**Issue by jsgoupil** [angular/angular#13385]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On a route like: `/customers/1/view`, when navigating to `['..', 'sites', '1']`, it tries to navigate to `/customers/1/view/sites/1`

**Expected behavior**
It should navigate to `/customers/1/sites/1`.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/wSn0FnXwHndSF4LqonKJ

Click on "Navigate" then click on "Go Back".

The error message says:
`Error: Cannot match any routes. URL Segment: 'customers/1/view/sites/2'`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

```

    "@angular/common": "~2.3.0",
    "@angular/compiler": "~2.3.0",
    "@angular/compiler-cli": "~2.3.0",
    "@angular/core": "~2.3.0",
    "@angular/forms": "~2.3.0",
    "@angular/http": "~2.3.0",
    "@angular/platform-browser": "~2.3.0",
    "@angular/platform-browser-dynamic": "~2.3.0",
    "@angular/router": "~3.3.0",
    "@angular/upgrade": "~2.3.0",
```

* **Angular version:** 2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by SamVerschueren** [comment]
For some reason, this works

```js
this.router.navigate(['../../../../sites/1'], { relativeTo: this.route });
```

**Comment by jasonaden** [comment]
Please use `../`.

**Comment by jsgoupil** [comment]
In any operating system:
`cd ..`
works great.

Forced to use 
`cd ../`
is unfortunate at best.

**Comment by mlc-mlapis** [comment]
@jsgoupil ... hmmm, you are on the web ... not in any o.s.

**Comment by jsgoupil** [comment]
@mlc-mlapis You're right, I forgot. In the web the trailing slash / is mandatory.

**Comment by jsgoupil** [comment]
```
['..'] // not valid
['../'] // valid
['../..'] // valid
['../', '../'] // not valid
```

This thing makes no sense.

These are called "Commands" for a reason. This double dots calculation is valid only if it's the first entry, which also makes no sense.

**Comment by samuelkavin** [comment]
I added following code. It's working fine in desktop browser but in most of the mobile browser it's doesnt work. Any idea?

`this.router.navigate(['../submit-success']);`

**Comment by ali6p** [comment]
You can use "activatedRoute.parent" as "relativeTo", it depends on your module and routing architecture. 
```js

constructor(
    private activatedRoute: ActivatedRoute,
    private router: Router    
) {}

navigateTo() {
    this.router.navigate(['sites/1'], { relativeTo: this.activatedRoute.parent })
}

```
_Tested with Angular 7_
