### ISSUE TITLE
AOT compilation does not include app code

### ISSUE THREAD

**Issue by skendrot** [angular/angular#13389]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When running the AOT compiler it compiles angular dependencies, but not app code. No errors are encountered

**Expected behavior**

The NgFactories should be created for the app code as well as the angular dependencies

**Minimal reproduction of the problem with instructions**

Clone or download the sample at https://github.com/skendrot/angular-quickstart. Run `"node_modules/.bin/ngc" -p tsconfig-aot.json` 

**What is the motivation / use case for changing the behavior?**

App needs to be pre-compiled as well as angular dependencies

**Please tell us about your environment:**

Windows 10 
node v:6.9.1
npm v:4.0.2

* **Angular version:** 2.0.X

Angular 2.2.4

* **Browser:** [NA]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =  6.9.1

**Comment by andyws** [comment]
Same/similar as #13344

**Comment by mattlewis92** [comment]
This threw me as well, it's caused by using typescript 2.1.x which is currently [a WIP](https://github.com/angular/angular/pull/13294). Pin your typescript version to `~2.0.10` and it should work 😃

**Comment by skendrot** [comment]
That fixed it. Thanks!

**Comment by code-tree** [comment]
@mattlewis92 Thank you!!
