### ISSUE TITLE
Proposal: *ngFor - throw error when null is passed in as trackBy function

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#13388]
**I'm submitting a**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently if you pass in an expression that resolves to `null` for NgFor's trackBy function it does not throw and the user does tell that user what they are doing does nothing.
For example: `*ngFor="let item of items; trackBy: item?.id"`
This syntax is from ng1 and there are examples on StackOverflow which show people using it in Angular which mislead people into thinking it is working when it is not.
This is specifically when `?` is used since if you do `trackBy: item.id` it will throw, but `trackBy: anythingElse?.something` will return null due to the safe navigation operator

**Expected behavior**
It should throw an error when `null` is passed in as the trackBy function

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/jaY4TeiSHDYdHQpMOlVl?p=preview

**What is the motivation / use case for changing the behavior?**
People might be mislead or unknowing think that using trackBy: `item?.id` will actually track the item by that value

* **Angular version:** 2.3.0

Related #12969

**Comment by DzmitryShylovich** [comment]
I would say it's a docs issue

Related to https://github.com/angular/angular/issues/11727
