### ISSUE TITLE
Add generic return types to dependency injector.

### ISSUE THREAD

**Issue by thinkingmedia** [angular/angular#13381]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
let service = ReflectiveInjector.resolveAndCreate([MyService]], this.injector).get(MyService);
```

When you use the DI methods to get services the return type is `any`

**Expected behavior**

```
let service = ReflectiveInjector.resolveAndCreate([MyService]], this.injector).get<IMyService>(MyService);
```

I would like to define the return type using generics.

**What is the motivation / use case for changing the behavior?**

Provides for auto-completion in the IDE and helps provide the TypeScript compiler with type hinting.

**Please tell us about your environment:**

Windows 10, WebStorm, NPM, Apache 2

* **Angular version:** 2.2.3

* **Browser:** Chrome

* **Language:** TypeScript 2.0

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/12262#issuecomment-254874329

**Comment by thinkingmedia** [comment]
@DzmitryShylovich that's way beyond the scope of what I'm looking for. I totally understand the complexities of supporting generics in DI.

I just want to type hint the return types.

This is what I ended up doing as a work around.

```
import {ReflectiveInjector, Injector, Provider} from "@angular/core";

/**
 * Wrapper that provides generics on the return types.
 */
export class AppReflectiveInjectorWrapper {
    /**
     * Constructor
     */
    constructor(public reflect: ReflectiveInjector) {
    }

    /**
     * Gets an object from the DI.
     */
    public get<T>(token: any, notFoundValue?: any): T {
        return this.reflect.get(token, notFoundValue);
    }
}

/**
 * Provides some basic type generics to the Angular 2 injector.
 */
export class AppInjector {
    /**
     * Creates a DI that supports generics
     */
    public static resolveAndCreate(providers: Provider[], parent?: Injector): AppReflectiveInjectorWrapper {
        return new AppReflectiveInjectorWrapper(ReflectiveInjector.resolveAndCreate(providers, parent));
    }
}
```

All I really want is to add a generic parameter to the methods that return instances.

**Comment by thinkingmedia** [comment]
Okay, I read more on the referenced issue.

I'm create new instances from new DI containers. So I don't have the problem of the generic type obscuring the provider.

With that said, if we added generics to the return types this would confuse people to think that can create generic providers. So I'm going to close this.

**Comment by thinkingmedia** [comment]
I feel stupid now, but I forgot about type casting. I can just do this from now.

```
let service = ReflectiveInjector.resolveAndCreate([MyService]], this.injector).get(MyService) as MyService;
```

**Comment by aluanhaddad** [comment]
@thinkingmedia you shouldn't need to cast at all.

The signature of `ReflectiveInjector.prototype.get` should be improved, currently it is weak. This is trivial and should be in core
```ts
export declare abstract class ReflectiveInjector {
    abstract get<T>(token: new (...args) => T, notFoundValue?: T): T;
    abstract get(token: any, notFoundValue?: any): any;
}
```
clear as day and leads us toward success by letting the tools do their job.

Your example becomes:
```ts
let service = ReflectiveInjector.resolveAndCreate([MyService], this.injector).get(MyService);

service.methodOnMyServiceThatLightsUpWith(
    TypeInfo, 
    Documentation,
    AndCompileTimeChecking
);
```
Please reopen this issue.

**Comment by thinkingmedia** [comment]
I'm glad someone else liked me idea.

I ended up creating a wrapper class around the DI so that it was more fluid. I like fluid interfaces and think they make code easier to read..

Here's an example:

```
@Injectable()
export class MyService {
    constructor(@Inject('base') private base: string,
                @Inject('resource') private resource: string,
                @Inject('action') private action: string,
                private http: Http) {
    }
}
```

The above takes some custom values plus it needs the `Http` service. With my wrapper you can create an instance like this.

```
let service = ApiInjector.use(this.injector)
                         .inject('base', 'http://')
                         .inject('resource', 'www.example.com')
                         .inject('action', 'get')
                         .create<MyService>(MyService);
```

My only complaint is the need to pass the provider as both a generic and argument on `create()`. If you know how to reduce it to just on usage. That would be great help.

Here's my code:

**AppInjector.ts**

```
import {Injector} from "@angular/core";
import {FluidInjector} from "./FluidInjector";

/**
 * Provides some basic type generics to the Angular 2 injector.
 */
export class AppInjector {

    /**
     * Starts a fluid interface for the injector.
     */
    public static use(parent?: Injector): FluidInjector {
        return new FluidInjector(parent);
    }
}
```

**FluidInjector.ts**

```
import {Injector, Provider, ReflectiveInjector} from "@angular/core";

/**
 * Provides a fluid interface for the Angular injector.
 */
export class FluidInjector {

    /**
     * Custom values to inject.
     */
    private provides = [];

    /**
     * Constructor
     */
    constructor(private parent?: Injector) {

    }

    /**
     * Injects a custom named provider.
     */
    public inject(name: string, value: any): FluidInjector {
        this.provides.push({provide: name, useValue: value});
        return this;
    }

    /**
     * Creates a new instance of the object.
     */
    public create<T>(provider: Provider): T {
        let providers = this.provides.slice();
        providers.push(provider);
        return ReflectiveInjector.resolveAndCreate(providers, this.parent).get(provider) as T;
    }
}
```

Do you think the Angular team would be open to a more fluid interface for the DI?

**Comment by aluanhaddad** [comment]
> Do you think the Angular team would be open to a more fluid interface for the DI?

I don't know. I'm also not really asking for that.

Your original request, which is to leverage standard typescript features, such as type inference, to improve tooling and improve usability and code-correctness is both reasonable and necessary. WRT to the code you posted, it don't see it ending up in core, but if you want some thought on how to leverage type inference to improve it, we could discuss that elsewhere.

I want generic types to be used where obvious and sensible. I want fewer `any` annotations and for those reasons I want this feature request to be accepted. It takes about 5 minutes to write the generic `get<T>` which is a 100% backwards compatible no-breaking overload addition, and I would be happy to send a PR with it.

**Comment by DzmitryShylovich** [comment]
@thinkingmedia fixed https://github.com/angular/angular/pull/13785

**Comment by DzmitryShylovich** [comment]
@thinkingmedia can you close this please?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed ☝️

**Comment by DzmitryShylovich** [comment]
@thinkingmedia can you close the issue as it was fixed? thanks
