### ISSUE TITLE
JIT Compiler error for Provided Array with Objects containing `name` property

### ISSUE THREAD

**Issue by tmair** [angular/angular#13394]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I provide an array of objects to a component or a module, and the objects declare a name property of type `number` the JIT compilation fails.

I just did an upgrade of angular from version 2.1.2 to 2.3 and did a search for changes in the code. It seems that https://github.com/angular/angular/commit/2f7492c986bb64669bfc2d3d6da60f09db13ded7 broke the behaviour I am experiencing

**Expected behavior**
Providing an array of objects with a name property should be possible.

**Minimal reproduction of the problem with instructions**
Visit https://embed.plnkr.co/I624j5Bs9mx2fkYa5Jzj/ and you will see the error with the stack trace in the developer console.

**What is the motivation / use case for changing the behavior?**
I did not expect a `name` property to break JIT compilation. 

**Please tell us about your environment:**
Operating System: Windows 10

* **Angular version:** 2.3.0

* **Browser:** all
 
* **Language:** TypeScript 2.0.8

**Comment by tbosch** [comment]
Note, the problem here is that the `name` property returned a non string value...
