### ISSUE TITLE
Proposal: AsyncValidator interface

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#13398]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There isn't defined any interface that NG_ASYNC_VALIDATORS provider should implement.

**Expected behavior**
There should exist AsyncValidator interface similar to Validator interface.

**What is the motivation / use case for changing the behavior?**
The compiler and editor can call out misspellings.

**Please tell us about your environment:**

* **Angular version:** 2.2.X
 
* **Language:** TypeScript

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/validators.ts#L86

**Comment by dawidgarus** [comment]
@DzmitryShylovich that's not exactly what I meant. AsyncValidatorFn is async counterpart of ValidatorFn. But there is not async counterpart for Validator interface: https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/validators.ts#L31.
I would like to use AsyncValidator like that:
```typescript
@Directive({
	selector: '[myDirective]',
	providers: [
		{ provide: NG_ASYNC_VALIDATORS, forwardRef(() => MyDyrective), multi: true }
	]
})
export class MyDirective implements AsyncValidator {
	validate(control: AbstractControl): Promise<{[key: string]: any}> {
		return new Promise(resolve => {
			resolve(null);
		});
	}
}
```
