### ISSUE TITLE
Router should be able to detect pushState changes

### ISSUE THREAD

**Issue by vasslehel-c** [angular/angular#13396]
**I'm submitting a ...**  
```
[x] bug report 
```

**Current behavior**
One navigates to domain.com/mypath, which loads an iFrame, and from the iFrame the url is changed using pushState (eg. domain.com/mypath/2. After trying to navigate again to /mypath will not trigger the Router, because the activated route is still /mypath.

**Expected behavior**
A mechanism should exist to force the router to reevaluate the current location.
One solution would be NavigationExtras -> relativeTo to accept location.href besides an ActivatedRoute.

**What is the motivation / use case for changing the behavior?**

* **Angular version:** 2.3.0
* **Angular Router version:** 3.3.0
* **Language:** [TypeScript]

**Comment by DzmitryShylovich** [comment]
can u pls add a small repro in plunkr?

**Comment by vasslehel** [comment]
http://plnkr.co/edit/RUL43GPwOKBoERSO50Tw?p=preview

The scenario is the following:
1. After clicking Routed Comp link, the RoutedComponent is loaded.
2. Click on the Change URL button to change the url using pushState.
3. Click again Routed Comp link to reload RoutedComponent and reset the url. <- it's not working.

**Comment by DzmitryShylovich** [comment]
`pushState` doesn't trigger any event so it's not possible to intercept it.
One possible solution is to patch native `pushState` function http://stackoverflow.com/a/4585031
But I'm not sure we want to implement it inside angular.

If you want, u can patch it yourself and emit `popstate` invent.

**Comment by vsavkin** [comment]
Yup. It's impossible to intercept pushState. To make the Angular1/Angular2 scenario work, we had to manually wire them up by doing the following:

https://github.com/angular/angular/blob/master/modules/@angular/router/upgrade.ts#L84

You might want to do something similar.

**Comment by vasslehel-c** [comment]
But a mechanism to tell the router to reevaluate the current location would be welcome.

**Comment by jasonaden** [comment]
If this is still needed, please create a feature request with a description of what/why.
