### ISSUE TITLE
*ngIf on child of template element

### ISSUE THREAD

**Issue by KrakenTyP-co** [angular/angular#13392]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When i have component with template and inside of that template are *ngIf, something going wrong with ngIf.
Demo for this problem: https://embed.plnkr.co/Lyp1JGyWhJxDRfPdovmi/

```
 <wrapper>
    <template>
      <div *ngIf="false">1 shouldn't be displayed</div>
      <div *ngIf="true">2 should be displayed</div>
      <div *ngIf="false">3 shouldn't be displayed</div>
      <div *ngIf="true">4 should be displayed</div>
    </template>
  </wrapper>
```

**Expected behavior**
Shoud be shown Test and 2nd and 4th ngIf. Its shown only first one.
But this one is working correctly:
```
      <div *ngIf="false">1 shouldn't be displayed</div>
      <div *ngIf="true">2 should be displayed</div>
      <div *ngIf="false">3 shouldn't be displayed</div>
      <div *ngIf="true">4 should be displayed</div>
```

**Minimal reproduction of the problem with instructions**
https://embed.plnkr.co/Lyp1JGyWhJxDRfPdovmi/

On angular 2.1.2 working correctly, but after upgrading to 2.2.x or 2.3.x this happens.
Node version 7.x, npm 4.x, webpack 1.x, awesome-typescript-loader 3 beta 13

**Comment by alexzuza** [comment]
You have to specify `TemplateRef` which you use in `ngTemplateOutlet`
`<template #tmpl>`
and in `Wrapper`
`@ContentChild('tmpl') tpl: TemplateRef<any>;`
Here is working [Plunker](https://plnkr.co/edit/BkiJwwKNpoTQRxWa1T2V?p=preview)


See also http://stackoverflow.com/questions/41068032/template-with-ngif-inner-not-work-after-change-model
