### ISSUE TITLE
Disable URL Decoding for $resource

### ISSUE THREAD

**Issue by chrisjlee** [angular/angular#1339]
There anyway i can disable URL decoding when instantiating a $resource?

I did some searching and there was an older solution that works but involves hacking core:

http://stackoverflow.com/a/23087400/171217

If there isn't i'd happily look at contributing PR; if there aren't any security issues with this.

**Comment by SekibOmazic** [comment]
@chrisjlee This is the repo for Angular2 which is still in alpha. Please file the issue in Angular1 repo here:
https://github.com/angular/angular.js

**Comment by nachopro** [comment]
Hello, Can You reopen this feature request? Thanks!

**Comment by Pablo-Ivan** [comment]
@nachopro Why? As clearly stated above, that issue conscerns Angular 1. And not even a recent release, but 1.3.

**Comment by nachopro** [comment]
I sorry, but this issue appears in Angular2. Anyway I found a proper issue https://github.com/angular/angular/issues/9762

Thanks!
