### ISSUE TITLE
ngOutletContext causes template to re-initialize on data changes

### ISSUE THREAD

**Issue by parliament718** [angular/angular#13407]
https://plnkr.co/edit/mUXkCli6CUEyNlbn2PZV?p=preview

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Minimal reproduction of the problem with instructions**

```
     <template #chartsManagerTemplate let-data="data">
         <charts-manager data="data"></charts-manager>
    </template>
    
     <template [ngOutletContext]="{ data: chartsData }"
            [ngTemplateOutlet]="chartsManagerTemplate">
     </template>

```

In the component:

```
     this.loadChartsData().subscribe(data => {

          //this causes the template to re-instantiate, I believe it should not.
          this.chartsData = data; 
     });
```

**Current behavior**

When data passed into [ngOutletContext] changes, the template and its nested components are re-instantiated.

**Expected behavior**

The expected behavior is for the template to not be re-instantiated, similar to if a template was not used. For example, this:

```
     <template [ngOutletContext]="{ data: chartsData }"
            [ngTemplateOutlet]="chartsManagerTemplate">
     </template>
```

should behave the same as:

```
<charts-manager data="chartsData"></charts-manager>
```

and NOT re-instantiate

**What is the motivation / use case for changing the behavior?**
Nested component should have the ability to control when they redraw, rather than it being forced simply by the use of <template>. In my case, I would like to redraw charts with a transition.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Provide a small repro in plunkr

**Comment by parliament718** [comment]
https://plnkr.co/edit/mUXkCli6CUEyNlbn2PZV?p=preview

**Comment by DzmitryShylovich** [comment]
Still an issue in 4.x http://plnkr.co/edit/J3pPvM0Cstq2BtTaxY2h?p=preview

@parliament718 workaround https://plnkr.co/edit/kR2oTyTubaAS4UdFISM6?p=preview

**Comment by pkozlowski-opensource** [comment]
The issue described here is a combination of 2 implementation decisions combined together:
* view engine / change detection engine will _recreate_ objects literals used in expressions: https://plnkr.co/edit/vqBYylnvSkbJVgJW5LO5 
* `ngTemplateOutlet` will re-create templates as soon as a bound context changes: https://github.com/angular/angular/blob/5344be518283e40201e34af413ddd34db6b51059/packages/common/src/directives/ng_template_outlet.ts#L51-L60

We could change implementation of the `ngTemplateOutlet` although it would be a bit tricky. before doing so I will dig into part of the view / CD engine that re-creates object literals.

**Comment by ghetolay** [comment]
I think the root problem for `ngTemplateOutlet` is `ViewContainerRef.context` to be readonly so we can't change a context but just create it once and then mutate it.
When @DzmitryShylovich tried to fix that issue this was his main issue, if user provides a new context we can't just replace it but we would have to run a differ and mutate the actual context to shape it exactly like the new context being passed. 
I find it weird for Angular to enforce mutation of data here when it's more about immutable data everywhere else.  

So I think there should be a way to change the context (the reference) even if this is not directly but through a function to ensure/prevent some behavior.
