### ISSUE TITLE
Language service reports an error on sub-types of string

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#13403]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

```typescript
class FooCmp {
  something: 'foo' | 'bar';
}
```

```html
<div *ngIf="something === 'foo'"></div>
```

`getDiagnostics()` reports:

> 'Expected the operants to be of similar type or any'

**Expected behavior**

No diagnostic should be produced as `'foo' | 'bar'` is a sub-type of `string`.

**Comment by beaumkr** [comment]
I'd like to bump this one as I have a similar issue with enums.

I have this in my template:
`<div *ngIf="fileSet.category == 'OLD'">`

where the category field is defined as:

`category?: SessionFilesDTO.CategoryEnum;`

and the enum as 

`export enum CategoryEnum {
        AGENDAS = <any> 'AGENDAS',
        GLOSSARIES = <any> 'GLOSSARIES',
        BACKGROUND = <any> 'BACKGROUND',
        OLD = <any> 'OLD'
    }
`

So I'd expect that to work just as the string unions, or am I wrong?
It compiles and works fine, but VSCode is showing errors in the template on the *ngIf mentioned above.

**Comment by gimox** [comment]
same issue

**Comment by karocksjoelee** [comment]
+ 1 same issue here in VS-Code 

---- My Solution: 

Assign the string in the .ts file as a variable ( taberOne = 1 ) , than use it in the *ngif 
`<div *ngIf="tab.index === taberOne">`
