### ISSUE TITLE
71 Test failures on Windows, mostly relating to language-service

### ISSUE THREAD

**Issue by gary-b** [angular/angular#13402]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
[When running tests on Windows there are 71 failures](https://gist.github.com/gary-b/4af9415294ae45c341f42469240ea320). Some refer directly to path separator issues, while others relate to tests that read files from the file system, so may also be related to the path separator being used.

**Expected behavior**
No failures

**Minimal reproduction of the problem with instructions**
Get latest and then in git-bash:
`./test.sh node`

**What is the motivation / use case for changing the behavior?**
Broken

**Please tell us about your environment:**
Windows 10, git-bash 2.8.1.windows1

* **Angular version:** 2.0.X
Master

* **Node (for AoT issues):** `node --version` =   
v5.12.0

**Comment by JoostK** [comment]
Closing as obsolete. Tests are now running on Windows on CircleCI, so their platform compatibility is covered.
