### ISSUE TITLE
Cannot reference class name from it's methods

### ISSUE THREAD

**Issue by gund** [angular/angular#13417]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I reference class name within it's class methods ngc compilation fails.

**Expected behavior**
Should continue to compile.

**Minimal reproduction of the problem with instructions**
Reference a class name in one of it's methods and try to compile with ngc.
I created a minimal repro repo [here](https://github.com/gund/ngc-bug-demo).

**What is the motivation / use case for changing the behavior?**
I should not be constrained to not to reference class from it's methods directly.

**Please tell us about your environment:**
Windows 10 x64
Node 6.9.1
TypeScript 2.0.10
ngc 2.3.0

* **Angular version:** 2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by DzmitryShylovich** [comment]
https://github.com/gund/ngc-bug-demo/blob/master/yarn.lock#L113 Anguar doesn't work with ts 2.1.*+

**Comment by gund** [comment]
You are right, with exact version of TS 2.0.10 it works fine.

Thanks and sorry for not checked version beforehand =)
