### ISSUE TITLE
Async operator for template as a shorthand for `| async`

### ISSUE THREAD

**Issue by OndraZizka** [angular/angular#13410]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
To render an Observable, one has to write:

myModel.observableMember | async

This leads to quite unreadable and inefficient expressions, like

[*ngIf="(myModel.observableMember | async) != 0 && ((myModel.observableMember | async)?.someProperty | async) == "yes"]  // say, array object property... just for illustration
    [*ngFor="let foo of (myModel.observableMember | async)"]

**Expected behavior**
Introduce a shortened syntax with an async operator:

[*ngIf="myModel.observableMember^?.someProperty^ == "yes"]
    [*ngFor="let foo of myModel.observableMember^"]

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Shorter expressions in templates that operate with Observables a lot. We created a OGM framework which allows seamless browsing of a graph database, but inherently all hops between models are realized as Observable's rather than direct references. I believe this approach will become popular.

**Please tell us about your environment:**
Latest Linux, NetBeans, npm/yarn, JBoss EAP 7

* **Angular version:** 2.3.0

* **Browser:** [all]
 
* **Language:** [all]

* **Node (for AoT issues):**

**Comment by Toxicable** [comment]
So one issue with this is that the `async pipe` is a pipe and im not sure what `^` has to do with pipes but it would mean that it would be totally different from every other pipe in Angular, not to mention that the keyword `^` is often xor in other languages which is nothing to do with pipes

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/13061

**Comment by vicb** [comment]
see ngIf improvements above (13061). This should also be implemented for other common directives.

If think this would solve your use case ? If you think  so, please close the issue.

**Comment by OndraZizka** [comment]
#13061 Helps a lot.  
Even with that, a short operator would be nice. For instance, pages which have a lot of Observable's in their models will be filled with `| async`. I expect the observable paradigm to become first class syntax constructs in the future; why wouldn't Angular's template be the first. _Currently_ it's solved with a pipe. It doesn't have to be so in the future. For your consideration.

@Toxicable - Regarding ^ - that was an example. I seriously doubt that the templates will really need XOR rather than "resolving an Observable".

**Comment by vicb** [comment]
@OndraZizka we have a current effort going on, see https://github.com/angular/angular/issues/13248
