### ISSUE TITLE
DI system can't resolve parameters

### ISSUE THREAD

**Issue by Invis1ble** [angular/angular#13419]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
DI fails in certain condition. Fail depends on `import` order.
Error in the browser console:
> Error: (SystemJS) Error: Can't resolve all parameters for BService: (?).

**Expected behavior**
Consistent DI behaviour, obviously.

**Minimal reproduction of the problem with instructions**
I have two services, let's name it `AService` and `BService`.
`AService` has dependency `Injector` and `BService` has dependency `AService`.
Also, `AService` has a method where it gets instance of `BService` via `injector`.
This is a very simplified case that reproduces the bug.

Here is a demo: https://plnkr.co/edit/Bajplasfrbsih6z7v6sg?p=preview
Also, if I change order of the `import` statements in `src/app.ts` from
```ts
import { AService } from './a.service';
import { BService } from './b.service';
```
to
```ts
import { BService } from './b.service';
import { AService } from './a.service';
```
then all works fine.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [TypeScript 2.0]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Service B need service A and service A need service be - it's a circular dependency.

**Comment by alexzuza** [comment]
I think it is not DI problem it is about wrong projects architecture

**Comment by DzmitryShylovich** [comment]
@Invis1ble http://prntscr.com/ditbrq as u can seen service A is undefined. it has nothing to do with angular

**Comment by Invis1ble** [comment]
@DzmitryShylovich
> Service B need service A and service A need service be - circular dependency.
`AService` depends on `Injector`. Also the issue depends on the order of `import` statements in `src/app.ts`.

@alexzuza 
> I think it is not DI problem it is about wrong projects architecture. 
It's just simplified case, I write module that contains decorators. Decorator receives `typeof SomeService` as argument and gets instance via `injector`.

**Comment by Invis1ble** [comment]
@alexzuza
Here you can see some code
https://github.com/Invis1ble/angular2-rest/blob/v0.1.5/src/decorators/action.ts#L106
https://github.com/Invis1ble/angular2-rest/blob/v0.1.5/src/decorators/action.ts#L28

**Comment by dmitrykashuba** [comment]
I got the same problem after updating webpack to 2.1.0-beta.28.

**Comment by vicb** [comment]
The original error is not a DI issue but a SystemJS error (circular dep)

**Comment by Invis1ble** [comment]
@vicb this error also appears in project that built with `angular-cli`, so it's not only a SystemJS error I think. What solution you can recommend in my case?
