### ISSUE TITLE
while running ng-serve i am getting the following issues

### ISSUE THREAD

**Issue by epadma** [angular/angular#13423]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\padmavathi>cd downloads

C:\Users\padmavathi\Downloads>cd phototype-development

C:\Users\padmavathi\Downloads\phototype-development>cd web

C:\Users\padmavathi\Downloads\phototype-development\web>cd dashboard

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>ng init
installing ng2
? Overwrite .editorconfig? Yes, overwrite
? Overwrite README.md? Yes, overwrite
? Overwrite src\app\app.component.html? No, skip
? Overwrite src\app\app.component.spec.ts? No, skip
? Overwrite src\app\app.component.ts? No, skip
? Overwrite src\app\app.module.ts? No, skip
? Overwrite src\environments\environment.prod.ts? No, skip
? Overwrite src\environments\environment.ts? No, skip
? Overwrite src\index.html? No, skip
? Overwrite src\main.ts? No, skip
? Overwrite src\test.ts? No, skip
? Overwrite src\tsconfig.json? Yes, overwrite
? Overwrite src\typings.d.ts? Yes, overwrite
? Overwrite angular-cli.json? Yes, overwrite
? Overwrite e2e\app.po.ts? Yes, overwrite
? Overwrite .gitignore? Yes, overwrite
? Overwrite karma.conf.js? Yes, overwrite
? Overwrite package.json? Yes, overwrite
? Overwrite tslint.json? Yes, overwrite
  overwrite .editorconfig
  overwrite README.md
  create src\app\app.component.css
  skip src\app\app.component.html
  skip src\app\app.component.spec.ts
  skip src\app\app.component.ts
  skip src\app\app.module.ts
  identical src\app\index.ts
  skip src\environments\environment.prod.ts
  skip src\environments\environment.ts
  skip src\index.html
  skip src\main.ts
  identical src\polyfills.ts
  create src\styles.css
  skip src\test.ts
  overwrite src\tsconfig.json
  overwrite src\typings.d.ts
  overwrite angular-cli.json
  identical e2e\app.e2e-spec.ts
  overwrite e2e\app.po.ts
  identical e2e\tsconfig.json
  overwrite .gitignore
  overwrite karma.conf.js
  overwrite package.json
  identical protractor.conf.js
  overwrite tslint.json
Installing packages for tooling via npm.
^CTerminate batch job (Y/N)? y

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>cd..

C:\Users\padmavathi\Downloads\phototype-development\web>cd/.

C:\>cd users

C:\Users>cd padmavathi

C:\Users\padmavathi>cd downloads

C:\Users\padmavathi\Downloads>cd phototype-development

C:\Users\padmavathi\Downloads\phototype-development>cd web

C:\Users\padmavathi\Downloads\phototype-development\web>cd dashboard

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>ng init
installing ng2
? Overwrite .editorconfig? No, skip
? Overwrite README.md? No, skip
? Overwrite src\app\app.component.html? No, skip
? Overwrite src\app\app.component.spec.ts? No, skip
? Overwrite src\app\app.component.ts? No, skip
? Overwrite src\app\app.module.ts? No, skip
? Overwrite src\environments\environment.prod.ts? No, skip
? Overwrite src\environments\environment.ts? No, skip
? Overwrite src\index.html? No, skip
? Overwrite src\main.ts? No, skip
? Overwrite src\test.ts? No, skip
? Overwrite src\tsconfig.json? No, skip
? Overwrite src\typings.d.ts? No, skip
? Overwrite angular-cli.json? No, skip
? Overwrite e2e\app.po.ts? No, skip
? Overwrite .gitignore? No, skip
? Overwrite karma.conf.js? No, skip
? Overwrite package.json? No, skip
? Overwrite tslint.json? No, skip
  skip .editorconfig
  skip README.md
  create src\app\app.component.css
  skip src\app\app.component.html
  skip src\app\app.component.spec.ts
  skip src\app\app.component.ts
  skip src\app\app.module.ts
  identical src\app\index.ts
  skip src\environments\environment.prod.ts
  skip src\environments\environment.ts
  skip src\index.html
  skip src\main.ts
  identical src\polyfills.ts
  create src\styles.css
  skip src\test.ts
  skip src\tsconfig.json
  skip src\typings.d.ts
  skip angular-cli.json
  identical e2e\app.e2e-spec.ts
  skip e2e\app.po.ts
  identical e2e\tsconfig.json
  skip .gitignore
  skip karma.conf.js
  skip package.json
  identical protractor.conf.js
  skip tslint.json
Installing packages for tooling via npm.
Installed packages for tooling via npm.

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>npm start

> dashboard@0.0.0 start C:\Users\padmavathi\Downloads\phototype-development\web\
dashboard
> ng serve

can't resolve module @angular/core/src/di/opaque_token from C:\Users\padmavathi\
Downloads\phototype-development\web\dashboard\src\index.ts
Cannot read property 'parse' of undefined
TypeError: Cannot read property 'parse' of undefined
    at ReflectorHost.normalizeAssetUrl (C:\Users\padmavathi\Downloads\phototype-
development\web\dashboard\node_modules\@angular\compiler-cli\src\reflector_host.
js:54:43)
    at ReflectorHost.findDeclaration (C:\Users\padmavathi\Downloads\phototype-de
velopment\web\dashboard\node_modules\@angular\compiler-cli\src\reflector_host.js
:151:33)
    at StaticReflector.initializeConversionMap (C:\Users\padmavathi\Downloads\ph
ototype-development\web\dashboard\node_modules\@angular\compiler-cli\src\static_
reflector.js:145:38)
    at new StaticReflector (C:\Users\padmavathi\Downloads\phototype-development\
web\dashboard\node_modules\@angular\compiler-cli\src\static_reflector.js:42:14)
    at AotPlugin._setupOptions (C:\Users\padmavathi\Downloads\phototype-developm
ent\web\dashboard\node_modules\@ngtools\webpack\src\plugin.js:137:27)
    at new AotPlugin (C:\Users\padmavathi\Downloads\phototype-development\web\da
shboard\node_modules\@ngtools\webpack\src\plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (C:\Users\padmavathi\Downloa
ds\phototype-development\web\dashboard\node_modules\angular-cli\models\webpack-b
uild-typescript.js:20:13)
    at new NgCliWebpackConfig (C:\Users\padmavathi\Downloads\phototype-developme
nt\web\dashboard\node_modules\angular-cli\models\webpack-config.js:23:42)
    at Class.run (C:\Users\padmavathi\Downloads\phototype-development\web\dashbo
ard\node_modules\angular-cli\tasks\serve-webpack.js:20:22)
    at C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\node_mo
dules\angular-cli\commands\serve.js:102:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! dashboard@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dashboard@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\n
pm-debug.log

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>npm start

> dashboard@0.0.0 start C:\Users\padmavathi\Downloads\phototype-development\web\
dashboard
> ng serve

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\Users\padmavathi\Downloads\phototype-development\web
\dashboard\node_modules\typescript\lib\typescript.js:14571:109)
    at parseSourceFileWorker (C:\Users\padmavathi\Downloads\phototype-developmen
t\web\dashboard\node_modules\typescript\lib\typescript.js:14503:26)
    at Object.parseSourceFile (C:\Users\padmavathi\Downloads\phototype-developme
nt\web\dashboard\node_modules\typescript\lib\typescript.js:14452:26)
    at Object.createSourceFile (C:\Users\padmavathi\Downloads\phototype-developm
ent\web\dashboard\node_modules\typescript\lib\typescript.js:14307:29)
    at new TypeScriptFileRefactor (C:\Users\padmavathi\Downloads\phototype-devel
opment\web\dashboard\node_modules\@ngtools\webpack\src\refactor.js:25:35)
    at Object.resolveEntryModuleFromMain (C:\Users\padmavathi\Downloads\phototyp
e-development\web\dashboard\node_modules\@ngtools\webpack\src\entry_resolver.js:
108:18)
    at AotPlugin._setupOptions (C:\Users\padmavathi\Downloads\phototype-developm
ent\web\dashboard\node_modules\@ngtools\webpack\src\plugin.js:129:58)
    at new AotPlugin (C:\Users\padmavathi\Downloads\phototype-development\web\da
shboard\node_modules\@ngtools\webpack\src\plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (C:\Users\padmavathi\Downloa
ds\phototype-development\web\dashboard\node_modules\angular-cli\models\webpack-b
uild-typescript.js:20:13)
    at new NgCliWebpackConfig (C:\Users\padmavathi\Downloads\phototype-developme
nt\web\dashboard\node_modules\angular-cli\models\webpack-config.js:23:42)
    at Class.run (C:\Users\padmavathi\Downloads\phototype-development\web\dashbo
ard\node_modules\angular-cli\tasks\serve-webpack.js:20:22)
    at C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\node_mo
dules\angular-cli\commands\serve.js:102:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! dashboard@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dashboard@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\padmavathi\Downloads\phototype-development\web\dashboard\n
pm-debug.log

C:\Users\padmavathi\Downloads\phototype-development\web\dashboard>

**Comment by DzmitryShylovich** [comment]
Pls repot cli issues on https://github.com/angular/angular-cli/issues
