### ISSUE TITLE
HostBinding is not honored when multiple depths are applied

### ISSUE THREAD

**Issue by amcdnl** [angular/angular#13428]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When you use multiple `@HostBinding`'s to describe a root attribute as well as nested attributes, the nested ones are not honored. Example:

```
  @Input() cssClass: string = '';

  @HostBinding('class')
  get cssClasses(): string {
    let clz = 'drawer';
    clz += ` ${this.cssClass}`;
    return clz;
  }  

  @HostBinding('class.left-drawer')
  get isLeft(): boolean {
    return this.direction === 'left';
  }

  @HostBinding('class.bottom-drawer')
  get isBottom(): boolean {
    return this.direction === 'bottom';
  }
```
In the above example I have to use a generic `@HostBinding('class')` in order to achieve a dynamic css class name assignment. When doing that with other bindings it does not honor the other bindings.

**Expected behavior**

It would take the properties in order of depth and apply in order of that depth thus enabling this to work.

**What is the motivation / use case for changing the behavior?**

Dynamic CSS class assignment

**Please tell us about your environment:**

Mac, NPM, VSCode

* **Angular version:** 2.0.X

2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.x

* **Node (for AoT issues):** `node --version` =  
Node 7.x

**Comment by DzmitryShylovich** [comment]
pls add:
1. a small repro
2. steps to reproduce
3. expected behavior.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource no feedback. can be closed
