### ISSUE TITLE
Dynamic Hosting Bindings based on Inputs

### ISSUE THREAD

**Issue by amcdnl** [angular/angular#13429]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I need the ability to dynamic assign `Input()`'s to `HostBinding`'s. 

Use case is allowing a developer to pass a custom css class to attach to the host. Lets think about a modal, I might want the upload modal to look slightly different from my new user modal. I allow the developer to pass a custom css class via input. Currently, there is no clean way to apply that. You end up with code like this:

```
  @Input() cssClass: string = '';

  @HostBinding('class')
  get cssClasses(): string {
    let clz = 'drawer';
    clz += ` ${this.cssClass}`;
    return clz;
  }  
```

**Expected behavior**

Some way to accomplish this with the decorator, just spit balling but maybe something like:

```
  @HostBinding(`class.${this.cssClass}`)
  @Input() cssClass: string = '';
```

**Minimal reproduction of the problem with instructions**

NA

**What is the motivation / use case for changing the behavior?**

Dynamic css applying via decorators

**Please tell us about your environment:**

NA

* **Angular version:** 2.0.X

2.3.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

NA
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.1.x

* **Node (for AoT issues):** `node --version` =   
Node 7.x

**Comment by amcdnl** [comment]
Adding this could negate https://github.com/angular/angular/issues/13428

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/10499

**Comment by amcdnl** [comment]
@DzmitryShylovich - good call, hard to find this one via name.
