### ISSUE TITLE
Getting a TypeError: Cannot read property 'originalError' of undefined at ErrorHandler._findOriginalError 

### ISSUE THREAD

**Issue by ScaryWolfMan** [angular/angular#13424]
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Linux Mint 18 64-bit
Node v7.1.0

* **Angular version:** 2.1.0

I am getting the following error, and I have no idea what might be causing it:

```
/home/swm/Development/dwbi/cup/node_modules/zone.js/dist/zone-node.js:158 throw error; ^

TypeError: Cannot read property 'originalError' of undefined at ErrorHandler._findOriginalError (/home/swm/Development/dwbi/cup/node_modules/@angular/core/bundles/core.umd.js:3288:26) at ErrorHandler.handleError (/home/swm/Development/dwbi/cup/node_modules/@angular/core/bundles/core.umd.js:3254:38) at Object.next (/home/swm/Development/dwbi/cup/node_modules/@angular/core/bundles/core.umd.js:6677:86) at SafeSubscriber.schedulerFn [as _next] (/home/swm/Development/dwbi/cup/node_modules/@angular/core/bundles/core.umd.js:5975:56) at SafeSubscriber.__tryOrUnsub (/home/swm/Development/dwbi/cup/node_modules/rxjs/Subscriber.js:223:16) at SafeSubscriber.next (/home/swm/Development/dwbi/cup/node_modules/rxjs/Subscriber.js:172:22) at Subscriber._next (/home/swm/Development/dwbi/cup/node_modules/rxjs/Subscriber.js:125:26) at Subscriber.next (/home/swm/Development/dwbi/cup/node_modules/rxjs/Subscriber.js:89:18) at EventEmitter.Subject.next (/home/swm/Development/dwbi/cup/node_modules/rxjs/Subject.js:55:25) at EventEmitter.emit (/home/swm/Development/dwbi/cup/node_modules/@angular/core/bundles/core.umd.js:5967:80)
```

**Comment by DzmitryShylovich** [comment]
Provide a small repro in plunkr

**Comment by vicb** [comment]
Please re-open when you have a repro or can provide info (ie by debugging the error). Thanks.

**Comment by ScaryWolfMan** [comment]
Thanks.  I'm sorry I couldn't reproduce it, but in my case it turned out to be that the HTTP request would receive an error, and this error would be thrown when it entered into the .catch

I guess its something to do with the fact that I'm trying to port my application over to angular-universal.  Without angular-universal, I don't seem to have any issues.  If you have any insight that'd be nice.

**Comment by es-lab** [comment]
@ScaryWolfMan Maybe you've already solved your issue, but I'd like to add my use case here, maybe others that will encounter this and will not lose time on it.

I'm using Angular 2.4.9.
This happens to me when a response comes as an error (400 or more), and in the catch I throw it, and in the subscribe I don't handle it. 
The solution is to add the handling for the error and it solved the issue, well I could just return an Observable.of(something here) and in this case I don't have to handle the error inside subscribe. 
In the end It's up to you to decide how to handle errors.
