### ISSUE TITLE
DecimalPipe and AoT misses locale parameter

### ISSUE THREAD

**Issue by SamVerschueren** [angular/angular#13422]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When compiling my code with AoT, which internally uses the `DecimalPipe`, things fail. This is what I found in my `ngfactory.ts` file.

```ts
  get _DecimalPipe_89():import67.DecimalPipe {
    if ((this.__DecimalPipe_89 == null)) { (this.__DecimalPipe_89 = new import67.DecimalPipe()); }
    return this.__DecimalPipe_89;
  }
```

The `DecimalPipe` misses the locale parameter although I compiled with the `--locale=en-US` flag.

**Expected behavior**
Not sure what to expect or how this thing work. But at least not complain about missing parameters.

**Minimal reproduction of the problem with instructions**
I had everything working with `Angular@2.2.3` but after upgrading to `Angular@2.3.0`, things started to fail.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
macOS, VS Code

* **Angular version:** 2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by DzmitryShylovich** [comment]
pls add a small repro

**Comment by SamVerschueren** [comment]
I will when I find some time today.

**Comment by SamVerschueren** [comment]
Thanks for asking. Turns out it's something on my side...
