### ISSUE TITLE
RXJS 5.0.1 is out

### ISSUE THREAD

**Issue by larssn** [angular/angular#13434]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

So RXJS 5 is finally out, and is currently in version 5.0.1.
Wondering if we could get an updated package.json.

**Comment by DzmitryShylovich** [comment]
@larssn was fixed here https://github.com/angular/angular/pull/13572
