### ISSUE TITLE
Docs missing extended classes

### ISSUE THREAD

**Issue by OndraZizka** [angular/angular#13442]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
See https://angular.io/docs/ts/latest/api/http/index/Response-class.html
It's missing the information "class Response extends Body"

**Expected behavior**
It should say that it extends Body, and also contain a link to Body docs.

**Minimal reproduction of the problem with instructions**
See the URL

**What is the motivation / use case for changing the behavior?**
Incomplete documentation

**Please tell us about your environment:**
Irrelevant

* **Angular version:** Latest

* **Browser:** all
 
* **Language:** Irrelevant

* **Node (for AoT issues):** `node --version` =  Irrelevant

**Comment by ericmartinezr** [comment]
This one is being tracked over here https://github.com/angular/angular.io/issues/2791

**Comment by vicb** [comment]
Thanks @ericmartinezr !
