### ISSUE TITLE
Issues with [hidden] - Bring Back ngHide/ngShow Directive?

### ISSUE THREAD

**Issue by jongunter** [angular/angular#13443]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We're expected to bind to the `[hidden]` attribute in place of what was `ng-hide` in Angular 1. `[hidden]` is easily overridden in CSS, and often by libraries such as Bootstrap. This results in a lot of confusing situations where `[hidden]="true"` doesn't work. 

Check out this plunker with a bootstrap `form-control` not hidden: https://plnkr.co/edit/YdiKncEwjX1wotslQLqO?p=preview

**Expected behavior**
Since Angular2 already handles quite a bit of CSS-related abstraction, perhaps we could take care of this issue ,too. Yeah, I know developers could probably add one line to their global CSS to ensure anything with  a `hidden` attribute is `display:none !important`, but that's an extra step that could confuse people and may not work due to styles being overridden. Angular is already great at CSS scoping, so it seems logical it should manage showing/hiding DOM elements better.

**Comment by vicb** [comment]
@kara might have some thopughts about that, see http://angularjs.blogspot.com/2016/04/5-rookie-mistakes-to-avoid-with-angular.html

**Comment by mattdistefano** [comment]
@vicb @kara are there any valid scenarios where `hidden` _shouldn't_ be `display: none`? From what I understand, bootstrap recognizes the v3 specificity issues as a bug and will be implementing `[hidden] { display: none !important }` for v4.

**Comment by DzmitryShylovich** [comment]
you can pretty easy create your own directive with required functionality

**Comment by pkozlowski-opensource** [comment]
I don't think that we want to bring back `ngShow` / `ngHide`, at least not for now. Going to close this one for now but happy to re-consider if more real-life use-cases surface.
