### ISSUE TITLE
feature: investigate priority based / idle rendering

### ISSUE THREAD

**Issue by robwormald** [angular/angular#13448]
@aerotwist posted an interesting blog post yesterday discussing how frameworks typically don't yield at all during initial boot. Effectively, he's using requestIdleCallback to break up the initial render. See https://aerotwist.com/blog/when-everything-is-important-nothing-is/

Angular is not covered in the initial blog post, so I've sent a PR https://github.com/GoogleChrome/sample-framework-boot/pull/2 to add us. 

We should investigate if and where this could be beneficial/possible to us - we obviously use a different model than Preact etc, but its possible we could see improvements here.

It's also important here to use the right metrics for evaluating this - it may be that this sort of implementation might be slightly slower in raw MS, but if there's a win on not locking up the main thread during startup (especially on low-power devices) we should take that into consideration. @aerotwist any input here would be most welcome.

My implementation of the app is deployed here for convienence framework-boot-test.firebaseapp.com/angular/no-ssr.html

WPT run here (3g, emulated motoG) - https://www.webpagetest.org/chrome/inspector-20160510/inspector.html?experiments=true&loadTimelineFromURL=/getTimeline.php?timeline=t:161213_9Q_16C7,r:1,c:0

**Comment by robwormald** [comment]
One easy and non-invasive thing to test would be rendering huge lists as well - this is easy to insert in the ngFor (or ngForChunked?) directive. Angular suffers when rendering super long lists (arguably, this is a bad idea anyway, but...)

**Comment by vicb** [comment]
First trying to be constructive: reminds me a little of what fiber is trying to achieve.

And now the rant :)

> We should investigate if and where this could be beneficial/possible to us - we obviously use a different model than Preact etc, but its possible we could see improvements here.

But why ? 
No seriously I mean do we have targets, what are they, are we behind ?
We can always do better but we can not do it all better.
Is this our priority ?

**Comment by robwormald** [comment]
@vicb first question to answer is *do we have an issue*, and if we do, check out how to solve if such an issue exists! 

My initial impression is that the majority of our startup time on slow devices is in non-DOM related stuff, as we're highly optimized for touching the DOM - our majority cost appears to be straight JS parse time. 

If there was a `priority: optimization` tag I would have added ;-)

**Comment by alxhub** [comment]
Closing as this issue is not currently used for discussion and is not a good fit for our feature process.
