### ISSUE TITLE
can't clearInterval

### ISSUE THREAD

**Issue by zjcboy** [angular/angular#13449]
**I'm submitting**
the error no in console.

**Current behavior**
make video progress bar

**Expected behavior**
can't clearInterval

**Minimal reproduction of the problem with instructions**
```ts 
  play() {
    this.interval = setInterval(() => {
        clearInterval(this.interval);
    }, 1000);
  }

  pause() {
     clearInterval(this.interval);
  }
  stop() {
    this.test = 0;
      clearInterval(this.interval);
  }
```

**What is the motivation / use case for changing the behavior?**
setInterval and clearInterval

**Please tell us about your environment:**
win10\visual studio code\ angular-cli

* **Angular version:** 2.0.X
V 2.2.3

* **Browser:** 
all
 
* **Language:** 
TypeScript

* **Node (for AoT issues):** `node --version` =  
V6.9.1

**Comment by vicb** [comment]
I am not sure to understand what you are trying to do and what the problem is.

Could you attach an exemple and try to describe your use case more precisely ?

Thanks

**Comment by zjcboy** [comment]
![image](https://cloud.githubusercontent.com/assets/8294751/21171735/ce0c06ee-c208-11e6-8c3a-70189a025b59.png)

![image](https://cloud.githubusercontent.com/assets/8294751/21171759/ff59f666-c208-11e6-80fb-88f5e82f4a90.png)

I will make video progress bar, first i can setInterval, but click pause or stop can't clearInterval!

**Comment by zjcboy** [comment]
Just upload the wrong picture, Looking forward to your reply. thanks!
