### ISSUE TITLE
how to slice or remove images after ; when availble multiple images in single array seprated with some comma

### ISSUE THREAD

**Issue by rahullsinha** [angular/angular#13456]
i have multiple images in single array like

`img: http://example.com/xyz.jpg;http://example.com/zzz.jpg`

i want to use only first image, so can anyone tell me trick?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
