### ISSUE TITLE
Can't get route params for a lazy module within a CanActivate guard

### ISSUE THREAD

**Issue by templth** [angular/angular#13451]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have an application that uses a lazy module this way:

```
export const routes: Routes = [
  {
    path: '',
    component: WelcomeComponent
  },
  {
    path: 'items',
    loadChildren: 'app/modules/items/items.module#ItemsModule'
  }
];

export const AppRoutingModule: ModuleWithProviders
                      = RouterModule.forRoot(routes);
```

Within the `ItemsModule`, I would like to use a guard for one of the sub-routes:

```
const routes: Routes = [
  {
    path: ':slug', component: ItemComponent,
    canActivate: [ ItemFetchGuard ]
  }
];

export const coveragesRoutingModule: ModuleWithProviders = 
                          RouterModule.forChild(routes);
```

This guard needs to get the `slug` parameter to fetch data:

```
@Injectable()
export class CoverageFetchGuard implements CanActivate {
  constructor(
    private service: ItemService,
    private route: ActivatedRouteSnapshot,
    private ngRedux: NgRedux<IAppState>) {}

  canActivate() {
    // slug is undefined
    const slug = this.route.params['slug'];
    return this.service.getItem(slug)
      .map(item => {
        this.ngRedux.dispatch(itemSuccessfullyFetched(item));
        return true;
      })
      .catch(error => {
        this.ngRedux.dispatch(itemFetchFailed(error));
        return Observable.of(false);
      });
  }
}
```

**Expected behavior**

I expect the route parameter to be there in the route snapshot when the can activate guard is called.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

I'm using Angular CLI ([Universal version](https://github.com/devCrossNet/angular-cli))

universal-cli: 1.0.0-alpha.universal.2-2
angular-cli: 1.0.0-beta.20-1
node: 6.9.2
os: linux x64

* **Angular version:** 2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome - Version 55.0.2883.87 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
pls add a small repro in plunkr

**Comment by templth** [comment]
Thanks very much for the suggestion @DzmitryShylovich ! I implemented a plunkr (http://plnkr.co/edit/UVz5YUkK0JoAy0i64Lo3?p=preview) and this made me realize that I didn't use the right way to get route params: through DI instead of using the `canActivate` method parameters.

So it's not actually a bug ;-)

Closing...
