### ISSUE TITLE
Dependency injection fails when we using factory with deps 

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular#13452]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
When we use array in array form of deps:

````
const car = new OpaqueToken('car');
providers:[
    {provide:car, useValue:{name:'BMV'}},   
    {provide:'product', useFactory:(x?:any)=>x || {name:'optional'}, deps:[[car, new Optional()]]}
]

````

Try https://plnkr.co/edit/23gPjIOVJse6Y8enISat

Angular doesn't understand `OpaqueToken` as a valid type and all others except `StaticSymbol` and `Type`.

See https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/metadata_resolver.ts#L922
and 
https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/metadata_resolver.ts#L700

**Comment by vicb** [comment]
Actually works as expected: `deps:[[new Inject(car), new Optional()]]`

I know it is not ideal and I think I already created an issue for that.

Could you please make sure this is correctly documented on angular/angular.io and create an issue there otherwise ?

Thanks

**Comment by olegdunkan** [comment]
@vicb actually it works,, but not consistent :)
`{provide:'product', useFactory:(x:any)=>x || {name:'optional'}, deps:[car]}` - it works ok, no need for `@Inject(car)`

Why do I have to use decorator constructor for my case?
It is hard to understand why do we have to use and remember three different form:  

`{provide:'product', useFactory:(x:any)=>x || {name:'optional'}, deps:[car]}`  - ok
`{provide:'product', useFactory:(x:any)=>x || {name:'optional'}, deps:[[Car, new Optional()]]}`  - ok, where `Car` - is a class
`{provide:'product', useFactory:(x:any)=>x || {name:'optional'}, deps:[[@Inject(car), new Optional()]]}`  - ok
It is too tricky and complicated IMHO.

**Comment by olegdunkan** [comment]
I've submitted  request to doc, thanks @vicb

**Comment by vicb** [comment]
@olegdunkan could you please ask you to find my original issue and link this one there ? thanks

**Comment by olegdunkan** [comment]
@vicb sorry, I was asleep, we have different time zones, my is -3
