### ISSUE TITLE
Document the projectableNodes parameter to createComponent

### ISSUE THREAD

**Issue by mindscratch** [angular/angular#13453]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The documentation does not describe what the `projectableNodes` parameter is used for or where it might come from in the [createComponent](https://github.com/angular/angular/blob/2.3.0/modules/%40angular/core/src/linker/view_container_ref.ts#L90) function.

**Expected behavior**

The documentation describes, as it does for the other parameters of [createComponent](https://github.com/angular/angular/blob/2.3.0/modules/%40angular/core/src/linker/view_container_ref.ts#L90), what `projectableNodes` is used for or where it might come from.

**Minimal reproduction of the problem with instructions**

See [current documentation](https://github.com/angular/angular/blob/2.3.0/modules/%40angular/core/src/linker/view_container_ref.ts#L90).

**What is the motivation / use case for changing the behavior?**

To help developers understand how to use the API.

**Please tell us about your environment:**

N/A

* **Angular version:** 2.0.X

2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by devoto13** [comment]
I found this [SO answer](http://stackoverflow.com/a/40323785/1377864) useful. It provides some information until official documentation is improved.

**Comment by adumesny** [comment]
agree. dynamically creating modules is so undocumented (and lack examples). Doesn't seem like advanced topic (coming from C++ background where hell yeah you create stuff dynamically (delay load too) and manage them all the time)

**Comment by DevidCIC** [comment]
Also the rootSelectorOrNode?: any is not documented. A example how to use it and what is it for would be nice.

**Comment by wardbell** [comment]
Closing as too old. Please re-investigate the API docs for the current version of Angular. Create new issues for them as needed.
