### ISSUE TITLE
Please provide overrideProvider function for TestBed (when provider is not associated with a component)

### ISSUE THREAD

**Issue by gituser7878-Ultralinq** [angular/angular#13460]
Explanation of feature desired, through example:

    beforeEach(() => {
        TestBed.configureTestingModule({
          providers: [
            DocumentsLoaderSvc,
           { provide: MgrSvc, useClass: MockMgrSvc },
           { provide: URLLoaderSvc, useClass: MockURLLoaderSvcWhenData}
          ]
             });
    });

I want to be able to override URLLoaderSvc with another mock, in an "it" case with its own unique requirement. Something like TestBed.overrideProvider would be very helpful. This is a test suite for a service with other service/constructor dependencies. Right now, I have each it statement in its own "describe", with its own beforeEach.

**Comment by hbaltz** [comment]
Hello,

  I see that the function [overrideProvider](https://angular.io/api/core/testing/TestBed#overrideProvider), but I did not manage to use it in my test. When I use it in a "it", the provider doesn't change. I did manage to find an example where this function is called. Could you explain me how to use it properly?

**Comment by mariomurrent-softwaresolutions** [comment]
> Hello,
> 
> I see that the function [overrideProvider](https://angular.io/api/core/testing/TestBed#overrideProvider) exists, but I did not manage to use it in my test. When I use it in a "it", the provider doesn't change. I didn't manage to find an example where this function is called. Could you explain me how to use it properly?
> 
> Thank you in advance to any one who may be able to help me.

Have you managed to get the overrideProvider working?

**Comment by Rambou** [comment]
**TestBed.overrideProvider()** doesn't work when calling it after **TestBed.inject()** has been called. Otherwise, it is. But as far as I can see no error is being thrown or there is any mention in the Documentation. Any idea? Is this a bug?
