### ISSUE TITLE
Error: (SystemJS) In strict mode code <- upgrading to 2.3.0 

### ISSUE THREAD

**Issue by demiro** [angular/angular#13462]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I upgraded to 2.3.0 and try to run the page I am getting this error in **chrome (v40)**:

> Error: (SystemJS) In strict mode code, functions can only be declared at top level or immediately within another function. SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function. at eval (native) at ZoneDelegate.invoke (http://30.254.174.143:3002/node_modules/zone.js/dist/zone.js:229:26) at Zone.run (http://30.254.174.143:3002/node_modules/zone.js/dist/zone.js:113:43) at http://30.254.174.143:3002/node_modules/zone.js/dist/zone.js:509:57 at ZoneDelegate.invokeTask (http://30.254.174.143:3002/node_modules/zone.js/dist/zone.js:262:35) at Zone.runTask (http://30.254.174.143:3002/node_modules/zone.js/dist/zone.js:151:47) at drainMicroTaskQueue (http://30.254.174.143:3002/node_modules/zone.js/dist/zone.js:405:35) at g (http://30.254.174.143:3002/node_modules/core-js/client/shim.min.js:8:10016) at http://30.254.174.143:3002/node_modules/core-js/client/shim.min.js:8:10138 at MutationObserver.a.exports.k (http://30.254.174.143:3002/node_modules/core-js/client/shim.min.js:8:14293) Evaluating http://30.254.174.143:3002/node_modules/@angular/compiler/bundles/compiler.umd.js Error loading http://30.254.174.143:3002/node_modules/@angular/compiler/bundles/compiler.umd.js as "@angular/compiler" from http://30.254.174.143:3002/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js {originalStack: "Error: (SystemJS) In strict mode code, functions c…/node_modules/core-js/client/shim.min.js:8:14293)", zoneAwareStack: "Error: (SystemJS) In strict mode code, functions c…ules/core-js/client/shim.min.js:8:14293) [<root>]", originalErr: SyntaxError: In strict mode code, functions can only be declared at top level or immediately within …, stack: (...), message: "(SystemJS) In strict mode code, functions can only…r-dynamic/bundles/platform-browser-dynamic.umd.js"}

I tried even the fresh version cloning the quickstart one from the website
https://github.com/angular/quickstart.git

very similar error

**IT WORKS ON IE11**

**Expected behavior**
expecting to work well in Chrome

**Minimal reproduction of the problem with instructions**
I got files from the official repo, did npm install and all went well, normal npm start - with no problems... it works on IE

**Please tell us about your environment:**

* **Angular version:** 2.3.0

* **Browser:** [ Chrome 40.0 ]

 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =   v6.0.0

**Comment by DzmitryShylovich** [comment]
Already fixed https://github.com/angular/angular/issues/13301
