### ISSUE TITLE
we also need deep copy

### ISSUE THREAD

**Issue by infofromca** [angular/angular#13467]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
for performanence, angular 2 use shallow copy for object.

**Expected behavior**
it is good, but sometimes it has strange behavior, and we also need deep copy which is convenience.

**Minimal reproduction of the problem with instructions**
can we add a flag to switch this situation? by default, keep shallow copy .

**What is the motivation / use case for changing the behavior?**
easy, lazy

**Please tell us about your environment:**
any

* **Angular version:** 2.3

* **Browser:** [all  ]

 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =   any

**Comment by pkozlowski-opensource** [comment]
In this version of Angular, contrary to Angular 1.x, we've got no plans of adding / exposing general purpose utility methods. There are plenty of libraries that do deep copy of objects already. 

Do, thnx for the suggestion but we are going to pass on it.
