### ISSUE TITLE
dynamic render open or close html element as we need

### ISSUE THREAD

**Issue by infofromca** [angular/angular#13466]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have this use case which I think it is very common, notice that div of  class="row" added when i%2 ==0 and closed  when i%2 ==1

```
<div *ngFor="let product of products ; let i=index">
            <div *ngIf="i%2 ==0">
                **<div class="row">**

                    <div class="col-xs-6">
                        <img id="img{{product.ItemNo}}120" src="{{imageBaseUrl + findImageURL(product)}}" class="img-responsive" />            
                   
                    </div>
            </div>

            <div *ngIf="i%2 ==1">
               

                    <div class="col-xs-6">

                        {{product.Name}}
                        {{product.IsPriceRange}} <del>{{product.WasPriceRange}}</del>
 
                       
                    </div>

                **</div>**
            </div>
        </div>

```
this code get exeption because of closing html element

**Expected behavior**
can we find a way to do  something like:

```
<div *ngFor="let product of products ; let i=index">
           
             <!--ngIf="i%2 ==0>   **<div class="row">** <--/ngIf>

                    <div class="col-xs-6">
                        <img id="img{{product.ItemNo}}120" src="{{imageBaseUrl + findImageURL(product)}}" class="img-responsive" />            
                   
                    </div>            

                    <div class="col-xs-6">

                        {{product.Name}}
                        {{product.IsPriceRange}} <del>{{product.WasPriceRange}}</del>
 
                       
                    </div>

             <!--ngIf="i%2 ==0>    **</div>** <--/ngIf>
            
        </div>
```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
very common use case

**Please tell us about your environment:**
any

* **Angular version:** 2.3

* **Browser:** [all ]

 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =   any

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr. It's not very clear from code snippets what are u trying to accomplish.

**Comment by devoto13** [comment]
I think op wants to output products in two columns. One possible workaround is to do data transformation (into array of 2-item arrays) in the component, before passing into template.

**Comment by tbosch** [comment]
Sorry, but its very unlikely we will do this as there is a workaround (transform the array first), and all of our compiler relies on the fact that elements are well balanced.
