### ISSUE TITLE
(focus) event not fired when running in WebWorker.

### ISSUE THREAD

**Issue by josh-sachs** [angular/angular#13476]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

<input (focus)="SomeEvent($event)" />
When executing within BrowserModule the event will fire fine. 
When working in WorkerAppModule the event will not fire on focus (or ever).

The (blur) event fires fine.

**Expected behavior**

I would expect SomeEvent() on the controller to be called when the input gets focus.

**Minimal reproduction of the problem with instructions**

<input (focus)="SomeEvent($event)" />
When executing within BrowserModule the event will fire fine. 
When working in WorkerAppModule the event will not fire on focus (or ever).

The (blur) event fires fine.

**What is the motivation / use case for changing the behavior?**

Running angular app in WorkerAppModule (WebWorker)

**Please tell us about your environment:**

* **Angular version:** 2.0.X

ng2.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by codestothestars** [comment]
The same appears to be true of (focusin) and (focusout).

**Comment by mhevery** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
