### ISSUE TITLE
AOT ngc generates incorrect import path

### ISSUE THREAD

**Issue by diestrin** [angular/angular#13487]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This is my project structure (a small representation of it)
```
/node_modules/
/src/
/src/browser.module.ts
/src/app/
/src/node_modules/@wu/ <- See my notes
/tsconfig.json
/package.json
```
I have a node_modules folder inside src, because I want to split my server/client files using the package.json *browser* field. I don't want it to mix with the global node_modules folder.

*ngc* generates an incorrect relative import path when it builds the ngfactory.ts files
In the `/src/browser.module.ngfactory.ts` you can find something like:
```
import * as import76 from '@wu/pages/not-found/not-found.component';
import * as import74 from '../node_modules/@wu/pages/not-found/not-found.component.ngfactory';
```
When it resolves that path, it fails, because resolving ../node_modules from /src/ is incorrect.

**Expected behavior**
It should generate the paths correctly.

**Minimal reproduction of the problem with instructions**
https://github.com/diestrin/universal-starter/tree/bug-report/aot-incorrect-path
This is a fork of `angular/universal-starter` with the minimal changes required to reproduce the bug
Explained:
- create a node_modules/test folder inside ./src
- create the package.json and index.ts files there with a base component
- import the component in a module
- use the component in another component
- run `npm run ngc`
- open `app.component.ngfactory.ts` and you'll see something like
```
import * as import13 from '../../node_modules/test/index.ngfactory';
import * as import14 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
```
- path `../../node_modules/test` doesn't exist

**What is the motivation / use case for changing the behavior?**
Be able to compile :)

**Please tell us about your environment:**

* **Angular version:** 2.1.2
* **Browser:** [n/a] 
* **Language:** [TypeScript 2.0.6]
* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by alexeagle** [comment]
Our path handling in ngc is brittle, it assumes a certain directory layout. It will take us a while to fix because we lack the right testing harness to test ngc against more project setups and more build tools.
In the meantime, you should not include a `node_modules` folder under src.

**Comment by JoostK** [comment]
Closing as obsolete. Sorry this was never addressed!
