### ISSUE TITLE
HTTP observables do not fire request until other calls return

### ISSUE THREAD

**Issue by harleyb16** [angular/angular#13485]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

We are having a major issue with HTTP simultaneous ajax requests with angular 2. Our homepage has various services fire http calls to our REST api. Among these, is an availability call that takes a particularly long time to finish (between 5-15 seconds). On first page load, we see simultaneous ajax calls with no issue.
![image](https://cloud.githubusercontent.com/assets/11000810/21204444/c5084d6c-c214-11e6-8791-bc0e73fdc8da.png)

However, if we then refresh the page (rebootstrap angular) or even reroute to the homepage with the router, all of our calls stack up waiting for the previous call to return.
![image](https://cloud.githubusercontent.com/assets/11000810/21204539/2d33f45e-c215-11e6-8478-a82234fc608e.png)

Attaching to our REST API project, I verified that the location requests are not even being sent by the browser until the availability returns.

**Expected behavior**

The expected behavior is that HTTP requests would fire off independently of each other, as it does on initial page load. Subsequent pages/refreshes should not bump down into sequential-only ajax calls.

**Minimal reproduction of the problem with instructions**

We are not doing anything particularly special. We have services that return observables that various components subscribe to.

    public itemAvailability(itemAvailabilityRequestList: ItemAvailabilityRequest[]): Observable<any> {
		let sessionToken = this.sessionService.sessionToken;
		let headers = new Headers({ 'Content-Type': 'application/json', 'Accept': 'application/json' });
		if (sessionToken)
			headers.set('X-Session-Token', sessionToken);

		const url: string = this.appSettingsService.appSettings.apiUrl + 'booking/itemAvailability';
		let body = JSON.stringify(itemAvailabilityRequestList);
		let options = new RequestOptions({ headers: headers });
		return this.http.post(url, body, options)
			.map(this.functions.extractData)
			.catch(error => { return this.functions.handleError(error) });
	}

With an angular2 web project implement a couple components that will call an API at ngOnInit(). Preferably one API method that is noticeably long. Then have other components call other methods of more reliable speed. For simplicity, trigger one of the faster calls with a button press.

    ngOnInit() {
		this.getParticipantTypes(this.searchType, this.cultureCode, this.providerCode, this.itemTypeCode);
	}

	getParticipantTypes(searchType: number, cultureCode: string, providerCode: string, itemTypeCode: string) {
		this.participantTypeService.getParticipantTypes(searchType, cultureCode, itemTypeCode, providerCode)
			.subscribe(
			participantTypes => this.participantTypes = participantTypes,
			error => this.errorMessage = <any>error);
	}

Observe behavior on first load of your angular2 site. While the longer API method is being processed by the server, initiate other requests. You should see this functioning fine.

Now, refresh your tab or reroute to the homepage. Repeat the previous test. You should now see all of your calls lock up until the longer call completes. 

**What is the motivation / use case for changing the behavior?**

Although this is only painfully noticeable with slow API calls, this presumably would affect all calls throughout an angular2 site. Significant performance could be saved if concurrent ajax calls worked as it should.

Some other resources on the expected behavior:
http://sgdev-blog.blogspot.com/2014/01/maximum-concurrent-connection-to-same.html
http://stackoverflow.com/questions/24794718/simultaneous-ajax-requests-angularjs

**Please tell us about your environment:**

* **Angular version:** 2.0.2/2.3.0

* **Browser:** [all]

 
* **Language:** [TypeScript 2.0]

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr

**Comment by harleyb16** [comment]
@DzmitryShylovich It would be a bit challenging for us to fully simulate what is happening in a plunkr with the given API requirements. I will post here if we end up setting this up.

@chuckjaz We could provide a URL to our working dev server. However, the security team here wants to restrict the IPs that can access it. Is there some way we can get into non-public contact with you or other google angular employees to enable you to hit our project and assess the issue?

**Comment by astec** [comment]
@harleyb16 you can make requests to some public API. For axample using http://www.fakeresponse.com

**Comment by harleyb16** [comment]
Just as a follow up, the team here working on our Angular2 site has been busy wrapping up other critical tasks for a delivery date in mid-January, so we haven't set aside a developer to create a plunkr repro for this. We could still provide a URL to our dev site if we could restrict the allowed IPs. I think my management is hoping to get into contact with a Google employee directly and provide that. Do Google employees frequent the issues?

Otherwise, I may spend the time personally setting up a plunkr to replicate this over the holidays.

**Comment by Toxicable** [comment]
Angular is backend agnostic, if you cannot reproduce the error hitting an URL like http://www.fakeresponse.com then I do not see how it is an Angular issue.
However, I could just be wrong about something here, so to confirm this you could try reproduce this with a plain xhr request and see if you get the same behaviour. If you experience the same behaviour then it is something on your end and if you do not then there is indeed something going on with Angular

**Comment by harleyb16** [comment]
We found that the root of the issue is an internal one with our API. Without getting too deep into details, another team in our company managed the API core libraries and our REST calls were being caught in their code before reaching our controllers, so it appeared the calls were not making it to the API.

Closing this issue :+1:
