### ISSUE TITLE
Compiler not drop-in replacement when using awesome-typescript-loader

### ISSUE THREAD

**Issue by patrickhousley** [angular/angular#13484]
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The awesome-typescript-loader throws the below error for each TS entry point:
```
ERROR in ./demo-src/main.ts
Module build failed: TypeError: Cannot read property 'fileExists' of undefined
    at readConfigFile (/Users/patrickhousley/Documents/projects/sprint.com/frontend-components/node_modules/awesome-typescript-loader/src/instance.ts:259:73)
    at Object.ensureInstance (/Users/patrickhousley/Documents/projects/sprint.com/frontend-components/node_modules/awesome-typescript-loader/src/instance.ts:103:9)
    at compiler (/Users/patrickhousley/Documents/projects/sprint.com/frontend-components/node_modules/awesome-typescript-loader/src/index.ts:42:20)
    at Object.loader (/Users/patrickhousley/Documents/projects/sprint.com/frontend-components/node_modules/awesome-typescript-loader/src/index.ts:16:18)
 @ multi demoSrc
```

**Expected behavior**
I would like to be able to treat `ngc` as a drop in replacement of `tsc` while using the awesome-typescript-loader. I would expect the TS code to compile exactly the same with the exception of supporting and using AoT for templates.

**Minimal reproduction of the problem with instructions**
```
{
          test: /\.ts$/,
          exclude: [
            /\.(spec|e2e)\.ts$/
          ],
          use: [
            {
              loader: 'awesome-typescript-loader',
              options: {
                compiler: '@angular/compiler-cli',
                // Enable source maps so developers can see TS code in dev tools instead of compiled JS.
                sourceMap: true
              }
            }
          ]
        }
```

**What is the motivation / use case for changing the behavior?**
Support AoT compilation using a custom webpack based build process. There is an open issue for awesome-typescript-loader (https://github.com/s-panferov/awesome-typescript-loader/issues/236). If this issue is solely the responsibility of that repository, then please close this issue.

**Please tell us about your environment:**
Mac OS X El Capitan

* **Angular version:** 2.0.X
2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es6",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": false,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./src"
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ],
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```
* **Node (for AoT issues):** `node --version` =   
6.9.2

**Comment by DzmitryShylovich** [comment]
do u know about aot webpack plugin?

**Comment by patrickhousley** [comment]
@DzmitryShylovich Are you talking about @ngtools/webpack? I do know about that but I have a slight issue with it. Based completely on looking through the code [here](https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/plugin.ts), it appears the plugin supports compiling only a single project at a time. My setup actually has three independent Angular 2 applications, loaded via a CRM, that I build simultaneously as to produce a single vendors module.

I am currently looking at alternative build processes. I may try to compile each project down to ES6 modules via ngc and then use webpack to do the bundling.

**Comment by DzmitryShylovich** [comment]
> Are you talking about @ngtools/webpack?

yeap

**Comment by patrickhousley** [comment]
I have created an example project for this issue at https://github.com/patrickhousley/angular2-multi-project-test. It currently works as long as I run ngc manually before webpack. I would like to get the `webpack-ngtools.config.js` working if possible.

**Comment by tbosch** [comment]
Sorry, but this "drop in replacement" only meant to work for the command line, not for 3rd party tools that use the typescript API directly. You best shot is to use `ngtools/webpack` for now, as this will also get things like watch mode eventually (which we don't support right now).

Could you please file this issue with `ngtools/webpack`?
