### ISSUE TITLE
HashLocationStrategy: Possibility to define the position of baseHref

### ISSUE THREAD

**Issue by vandres** [angular/angular#13482]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using HashLocationStrategy for routing and providing a baseHref via APP_BASE_HREF, the baseHref is always placed after the hash e.g. http://example.com/#subdir/route1

**Expected behavior**

It would be nice to define the position where the baseHref should be placed to allow e.g. this url http://example.com/subdir/#route1 

**Minimal reproduction of the problem with instructions**
Start a new app in a subfolder e.g. example.com/subdir/ and enable HashLocationStrategy. When providing a custom APP_BASE_HREF and using a route, the baseHref is always appended to the hash, instead of the host e.g. example.com/#subdir/route1 This will lead to an error when refreshing or sharing the url.
```
import {NgModule} from '@angular/core';
import {RouterModule, Routes} from '@angular/router';
import {APP_BASE_HREF} from '@angular/common';

const appRoutes: Routes = [...];

@NgModule({
    imports: [
        RouterModule.forRoot(appRoutes, {useHash: true})
    ],
    providers: [{provide: APP_BASE_HREF, useValue: window.location.pathname}]
})

export class AppModule {
}
```

**What is the motivation / use case for changing the behavior?**
We use Angular in combination with a CMS, where components can be placed dynamically by the user. The CMS has its own routing and is using the `<base href="/">` in another way Angular is needing it. It is not possible to place the HTML5 rewrite rules, because the urls are dynamically generated by the CMS. So we can only use the HashLocationStrategy for the Angular routing. But in this combination, the Url gets always rewritten, so that refreshing the page would lead to a 404.

We fixed this issue with an own Implementation of the HashLocationStrategy, but it would be nice to see this in the core as a configurable option. Our very simple code:

```
import {Injectable} from '@angular/core';
import {HashLocationStrategy} from "@angular/common";

@Injectable()    
export class CustomLocationStrategy extends HashLocationStrategy {
    prepareExternalUrl(internal: string): string {
        const url = this.getBaseHref() + '#' + internal;
        return url;
    }
}
```

**Please tell us about your environment:**

* **Angular version:** 2.3.0

* **Browser:** [all ]

 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr

**Comment by vandres** [comment]
Hmm sorry, I don't know plunkr very good. Is it possible to emulate subdirectories?

**Comment by schroedan** [comment]
Here is a small Plunker example: https://plnkr.co/edit/p19SdWLJmxHfiMunHPFy

Just switch the `LocationStrategy` in the `app.ts` and you will see the difference in the location output.

**Comment by DzmitryShylovich** [comment]
@vandres does solution from @schroedan is suitable for you?

**Comment by vandres** [comment]
@DzmitryShylovich Sorry, don't know what you mean. That is my feature request in a plunkr

**Comment by DzmitryShylovich** [comment]
@vandres 
> It would be nice to define the position 

how?

You can extend `HashLocationStrategy` and override `prepareExternalUrl` method. To me it's a pretty decent solution.

**Comment by vandres** [comment]
@DzmitryShylovich 
> We fixed this issue with an own Implementation of the HashLocationStrategy, but it would be nice to see this in the core as a configurable option. Our very simple code:

**Comment by DzmitryShylovich** [comment]
There's already a mechanism to tune that behavior. If the default impl is not suitable for you, you can provide your own `LocationStrategy` impl or extend and override some methods. I don't see why we need to add `additional` configuration for your particular use case.

**Comment by vandres** [comment]
I think, that this may be a common use case when working with another server side technology. Thats why I opened a feature request. If the Angular team decides, that that use case is not common, then close it.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource out of angular scope + trivial workaround

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

**Comment by vandres** [comment]
@jasonaden Maybe I don't understand you right, but this is not a bug but a Feature Request

**Comment by ShinDarth** [comment]
any news on this ?

**Comment by ShinDarth** [comment]
somehow this solution cannot be used with es6 because of this bug:

https://github.com/angular/angular/issues/24592

**Comment by olvisdevalencia** [comment]
@schroedan  Thanks you so much , just in like that i want looking for . Glad and appreciate you comment.

**Comment by rmorrise** [comment]
Why is it expected behavior that BASE_HREF should be added after the hash? This should be considered as an open bug

**Comment by trotyl** [comment]
@rmorrise By using `HashLocationStrategy` then nothing outside hash can be changed, do you suggest Angular should just silently ignore that with doing nothing?

**Comment by rmorrise** [comment]
I think it would be easier if the APP_BASE_HREF worked the same regardless of which routing strategy is chosen. If the base is set to `/my-webappcontext`, all routes (regardless of whether I use path or hashes) should be derived from `/my-webappcontext`:

```
https://myserver/my-webappcontext/my/route
```

```
https://myserver/my-webappcontext/#/my/route
```

This behavior is often needed when the angular app is served from something like a Java servlet container.

It doesn't make sense to me that the APP_BASE_HREF is processed by the router location strategy, since the base URL of the app (```https://myserver/my-webappcontext```) isn't part of the UI route.
