### ISSUE TITLE
Routes.loadChildren adds the children to the root Route.

### ISSUE THREAD

**Issue by sterfpaul** [angular/angular#13499]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm using loadChildren to load some child routes into a existing tree of routes:

```
const appRoutes: Routes = [
    {
        path: 'campaign',
        component: CampaignComponent,
        children: [
            {
                path: 'list',
                component: CampaignListComponent
            },
            {
                path: 'create',
                component: CreateCampaignWizardComponent,
                loadChildren: () => new Promise(resolve => {
                    (require as any).ensure([], require => {
                        resolve(require('./create-campaign-wizard/create-campaign-wizard.module').CreateCampaignWizardModule);
                    })
                })
            },
            {
                path: '',
                redirectTo: 'list',
                pathMatch: 'full'
            }
        ]
    }
];
```

The route definition in create-campaign-wizard.module:

```
const appRoutes: Routes = [
            {
                path: 'step-1',
                component: CreateCampaignStep1Component,
                canDeactivate: [CanDeactivateStepService]
            },
            {
                path: 'step-2',
                component: CreateCampaignStep2Component,
                canDeactivate: [CanDeactivateStepService]
            },
            {
                path: '',
                redirectTo: 'step-1',
                pathMatch: 'full'
            }
];
```

These routes are added as children to the /campaign/create route (e.g. /campaign/create/step-1). But they are also added to the / root route (e.q. /step-1).

This is very annoying as the path:'' (default path) now redirects to /step-1 instead of a home-page i have in a different module.

**Expected behavior**
Child routes are added to /campaign/create but not the root route /.

**Minimal reproduction of the problem with instructions**
See provided configuration above.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
npm --version
3.10.9

angular-cli: 1.0.0-beta.21
node: 6.9.2
os: linux x64

Ubuntu.

* **Angular version:** 2.0.X
2.2.3

* **Browser:** 
All
 
* **Language:**
Typescript
* **Node (for AoT issues):** `node --version` =   
node: 6.9.2

**Comment by WilliamKoza** [comment]
Can you show us your @NgModule conf with RouterModule.for .... or a plunker ?

**Comment by DzmitryShylovich** [comment]
Pls add:
1. small repro in plunkr
2. steps to reproduce
3 expected behavior

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have a minimal reproduction in plunker. Here is why we are requesting one: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue
