### ISSUE TITLE
Using “if” without a container element

### ISSUE THREAD

**Issue by infofromca** [angular/angular#13490]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
no such implementation

**Expected behavior**
use the containerless control flow syntax, which is based on comment tags.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
```
<ul>
    <li>This item always appears</li>
    <!-- ko if: someExpressionGoesHere -->
        <li>I want to make this item present/absent dynamically</li>
    <!-- /ko -->
</ul>

```
In this case, you can’t put if on the <ul> (because then it would affect the first <li> too), and you can’t put any other container around the second <li> (because HTML doesn’t allow extra containers within <ul>s).

**Please tell us about your environment:**
any

* **Angular version:** 2.3
.

* **Browser:** [all ]

 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =any

**Comment by pkozlowski-opensource** [comment]
You can use `<template [ngIf]="expression"><li>....</li></template>`. Closing as already supported.
