### ISSUE TITLE
TestCase imports not defined

### ISSUE THREAD

**Issue by manharthakur** [angular/angular#13493]
My Directive
---------------
import { Directive, ElementRef, Input } from '@angular/core';
@Directive({ selector: '[myHighlight]' })
export class HighlightDirective {
    constructor(el: ElementRef) {
       el.nativeElement.style.backgroundColor = 'yellow';
    }
}
------------------------------------------------------------------------
My Test Case

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 /// <reference path="../../node_modules/@types/jasmine/index.d.ts" />
import {TestBed, async,inject,ComponentFixture} from "@angular/core/testing";
import {HighlightDirective} from "../widgets/contact-widget/highlight.directive";
import {ContactState} from "../widgets/contact-widget/contactstate.component";
import { By }              from '@angular/platform-browser';
import { DebugElement }    from '@angular/core';
import { NO_ERRORS_SCHEMA }          from '@angular/core';
let comp:    ContactState;
  let fixture: ComponentFixture<ContactState>;
  let de:      DebugElement;
  let el:      HTMLElement;

beforeEach(() => {
  fixture = TestBed.configureTestingModule({
    declarations: [ ContactState, HighlightDirective],
    schemas:      [ NO_ERRORS_SCHEMA ]
  })
  .createComponent(ContactState);
  TestBed.compileComponents;
  fixture.detectChanges(); // initial binding
});

it('should have yellow <p>', () => {
  const de = fixture.debugElement.query(By.css('p'));
  const bgColor = de.nativeElement.style.backgroundColor;
  expect(bgColor).toBe('yellow');
});
```
Error
        TypeError: Cannot read property 'debugElement' of undefined
```

**Current behavior**
when i am writing a test case which uses elementRef or ComponentFactoryResolver or ViewContainerRef which we import from @angular or any other module then while running a test case we get an error that these elements are not defined. The concern is how can we assign the value to these imports

**Expected behavior**
The expected behaviour is that a value of the import should be assigned to it as soon as we run the test case

* **Angular version:** 2.0.2

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
