### ISSUE TITLE
No way found to test the functionality of a Component. Document does not specified it completely. There are huge gapes in test cases. 

### ISSUE THREAD

**Issue by vasuneetarya** [angular/angular#13494]
No way found to test the functionality of a Component which uses @angular/core viewContainerRef , elementRef, componentFactoryResolver etc. Document does not specified it completely. There are huge gapes in test cases.  Please provide proper documentation or declare that angular component cannot be tested.

Regards
Vasuneet Arya

**Comment by DzmitryShylovich** [comment]
Pls re-open it on https://github.com/angular/angular.io/issues

**Comment by chuckjaz** [comment]
@vasuneetarya  I believe https://angular.io/docs/ts/latest/guide/testing.html#!#simple-component-test is what your are looking for. If this documentation is incomplete or deficient please consider reported an issue in the documentation as recommended by @DzmitryShylovich .
