### ISSUE TITLE
Response from Http in error condition is blank in Chrome

### ISSUE THREAD

**Issue by mscharp** [angular/angular#13501]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When Chrome "cancels" a web request, the response that angular is propagating is blank.  Firefox and IE have the response properties populated with information.

**Expected behavior**
The response object has its properties populated with information in all browsers.

**Minimal reproduction of the problem with instructions**
Browse to an angular application, with a login page via HTTPS.
Enter credentials and post to /login via HTTPS.
Have server respond with 302 and a Location header of HTTP.
Chrome will cancel the redirect.
The `...catch( error => { console.log( error ); } )` error handler will catch the response, but none of the properties inside of "error" are populated, except for "type" which is "3".

**What is the motivation / use case for changing the behavior?**
So that the behavior is consistent between browsers, and the user can respond to errors accordingly.

**Please tell us about your environment:**
Chrome 55 (but have seen the problem in other versions as well )
Angular app inside of spring boot application deployed into tc server

* **Angular version:** 2.0.0

* **Browser:** 
Chrome

**Canceled xhr requests**

![screen shot 2016-12-15 at 11 09 37 am](https://cloud.githubusercontent.com/assets/1426929/21236344/e6efb958-c2b7-11e6-8b0d-543fb3de6ba2.png)

**Blank response in Chrome**

![screen shot 2016-12-15 at 11 10 51 am](https://cloud.githubusercontent.com/assets/1426929/21236345/e6f159e8-c2b7-11e6-82e7-7ba0eef0547b.png)
![screen shot 2016-12-15 at 11 11 47 am](https://cloud.githubusercontent.com/assets/1426929/21236343/e6efa0d0-c2b7-11e6-8b1c-a861bf1c6f87.png)

**Good response in FF ( I've cut out the url property for privacy )**

![screen shot 2016-12-15 at 11 39 58 am](https://cloud.githubusercontent.com/assets/1426929/21237242/542062ea-c2bb-11e6-81e8-c7b7b425c88b.png)

**Comment by DzmitryShylovich** [comment]
can u add a small repro in plunkr?

**Comment by DzmitryShylovich** [comment]
Looks like Chrome issue http://stackoverflow.com/a/17306451

**Comment by mscharp** [comment]
Thanks for the quick response.

The problem isn't that Chrome cancels the request (FF does as well), but that the error response object doesn't have any information in it in Chrome, but does in FF.

I can try to setup a simple plunker with a login form and another page, but unless you can post the form to an HTTPS endpoint and have it respond with a 302 and a Location header with a url to HTTP, it won't do any good.

**Comment by DzmitryShylovich** [comment]
ok, can u try to make the same request using plain xhr or fetch api and compare results?

**Comment by mscharp** [comment]
OK, I will attempt and post back the details.

**Comment by mscharp** [comment]
This looks like it is an XHR bug in chrome.  I've filed a bug against Chromium.  In case anyone else runs into this or wants to keep track of it, here is the link:

https://bugs.chromium.org/p/chromium/issues/detail?id=674753

**Comment by DzmitryShylovich** [comment]
good. if it's not related to angular close the issue pls. thx
