### ISSUE TITLE
Throw in DirectiveResolver if more than 1 directives on type

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1350]
And do that with a descriptive message: "Exactly one directive annotation allowed per type. Found multiple directive annotations in class ${type}."

**Comment by mhevery** [comment]
@yjbanov Can you verify that this is still an issue, and close if appropriate?

**Comment by yjbanov** [comment]
Yes, although it's been renamed to `DirectiveResolver`. Updated description.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

DirectiveResolver has been depricated.
