### ISSUE TITLE
Browser not updated after DOM is updated

### ISSUE THREAD

**Issue by Cutless009** [angular/angular#13504]
**I'm submitting a ...** 
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request

**Current behavior**
Angular does not update the browser once it runs.  

For instance, if you have a label and an input, if you bind the "for" attribute of the label to the "id" attribute of the input via a passed input, the browser will not recognize that the two are linked because Angular does not let the browser know it updated the DOM.

### EXAMPLE MARKUP
`<myInput id="input1"></myInput>`

### EXAMPLE COMPONENT
`@Input id: string;`

### EXAMPLE COMPONENT MARKUP
`<label [for]="id">My Label</label>
<input [id]="id" type="text" />`

### RESULT:
Clicking the label does not apply focus to the input. This can also be seen with labels of radio buttons and checkboxes, where clicking the label does not produce the desired default browser behavior of interacting with the associated element.

### RESULT:
Clicking labels for related inputs does not interact with the assigned element.

**Expected behavior**
Default browser behavior should be maintained when associated form elements via `for` and `id`.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/jJeqHAbO7vNVLV9GTvQW?p=preview

**What is the motivation / use case for changing the behavior?**
Should be able to use Angular to create dynamic components without having to reproduce default browser behavior. All form elements using`for` and `id` linking do not work as expected when given a dynamic value

**Please tell us about your environment:**
Windows 7, VSCode, NodeJS, Angular Generator

* **Angular version:** 2.0.X
2.3.0

* **Browser:** 
all
 
* **Language:**
all

* **Node (for AoT issues):**
6.8.0

**Comment by DzmitryShylovich** [comment]
> No options are added to the parent component select. 

Because `option` is not a direct descendant of `select` http://prntscr.com/djwnxl

You can reproduce the same behavior by just wrapping `option` into `div. https://plnkr.co/edit/v8nM3dJ1MEQxluLHRKry?p=preview

**Comment by Cutless009** [comment]
That's fair, I can work with that as long as adding them to the parent component through a service produces options in the drop-down list. I'll try it out and report back.

Previous issues still stand.

**Comment by DzmitryShylovich** [comment]
> Previous issues still stand.

can u pls update your plunkr because it's not clear what exactly doesn't work and what is the expected behavior?

**Comment by Cutless009** [comment]
Updated original post and plunkr.

**Comment by vicb** [comment]
- you probably want `[attr.id]` ? Note that `[for]` is a shorthand for `[attr.for]` as `for` is not a property on the DOM - not sure if `[id]` works in this case,
- for sure you have too many `bob1`, id are supposed to be unique - they are duplicated on 4 different els in your plunker.

**Comment by Cutless009** [comment]
Yeah I totally posted this without trying `[attr.id]`, right?

Updated plunkr: http://plnkr.co/edit/jJeqHAbO7vNVLV9GTvQW?p=preview

In the future please don't close issues without trying your "fix" first. Thanks.

**Comment by vicb** [comment]
@Cutless009 In the future remember to be kind here and make your homework before posting issue. We do not provide support here.

Now read my previous message carefully, double check your plunker and fix your issue. You can even thank me after you're done !

**Comment by pkozlowski-opensource** [comment]
@Cutless009 the root cause here is that you've got multiple elements with the same `id` in the DOM (you will have one on an `<input>` but another one will be on your custom component element. An easy work-around is to use a property name different from `id` or explicitly remove id from the native element on which your component is sitting on.

@vicb what I find rather surprising is that we shadow binding to native properties if there is a directive with an input name equals to a property name BUT we don't do this for components: http://plnkr.co/edit/7joejbZMIlwvW04DSpuc

This took me by surprise and this is not something I would expect or would know how to explain (that is - what is the reasoning behind).

**Comment by Cutless009** [comment]
I wasn't trying to be rude. Did you look at my new plunk? There is nowhere that `bob1` is repeated, and the issues till persists. Here's the link again in case I got it wrong last time: http://plnkr.co/edit/jJeqHAbO7vNVLV9GTvQW?p=preview

**Comment by DzmitryShylovich** [comment]
http://prntscr.com/dlvsp0

**Comment by Cutless009** [comment]
Fair enough. Sorry for the trouble.
