### ISSUE TITLE
too many null check

### ISSUE THREAD

**Issue by infofromca** [angular/angular#13513]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
in template, I should check *ngIf="obj !=null" first , then execute "obj.anotherObj !=null", then 
{{obj.anotherObj.property}}

**Expected behavior**
do not need to check obj !=null, and obj.anotherObj !=null.
in this situation, don't give out exeption, just empty ""

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
in this way, a component(template) will not influence another because of no exception.
and it can be more independent

**Please tell us about your environment:**

* **Angular version:** 2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by trotyl** [comment]
Please try `{{obj?.anotherObj?.property}}` ...

**Comment by infofromca** [comment]
thanks
