### ISSUE TITLE
Template reference to conditionally rendered element/directive is not set

### ISSUE THREAD

**Issue by hristokostov** [angular/angular#13516]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using a template reference variable defined on a element/directive with applied `ngIf` throws exception because the value is not set.

It seems that using a component property set via `ViewChild` is a possible workaround.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/sd41e0WK0UXGEnc4vkUT?p=preview

* **Angular version:** 2.0.x-2.3.x

**Comment by DzmitryShylovich** [comment]
See this thread https://github.com/angular/angular/issues/6179#issuecomment-237216645

**Comment by hristokostov** [comment]
Haven't found that issue and posted a new one, I'm sorry. OK, but if this is by design, it have to be explained in the documentation. Currently the doc says:

> We can refer to a template reference variable _anywhere_ in the current template.

(emphasis in the original)

**Comment by vicb** [comment]
@hristokostov what documentation are you referring to please ? (so that we can fix)

**Comment by hristokostov** [comment]
https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ref-vars

**Comment by DzmitryShylovich** [comment]
If it's angular.io I think it should be re-opened on https://github.com/angular/angular.io/issues

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource documentation
