### ISSUE TITLE
real angular 2 comment on template

### ISSUE THREAD

**Issue by infofromca** [angular/angular#13514]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As Thierry Templier said on
http://stackoverflow.com/questions/36396765/commenting-out-code-in-angular2-typescript
If you are in the template, use the HTML comment :
```
@Component({
  selector: 'my-app',
  template: `
    <h1>{{title}}</h1>
    <h2>{{lene.name}}</h2>
    <div><label>id: </label>{{lene.id}}</div>
    <!-- div>
      <label>name: </label>
      <input [(ngModel)]="lene.name" placeholder="name">
    </div-->
    <div><label>description: </label>{{lene.description}}</div>
  `
})

```
.
**Expected behavior**
real angular comment out on template

**Minimal reproduction of the problem with instructions**
but this is not real angular comment
```
<!-- div>
      <label>name: </label>
      <input [(ngModel)]="lene.name" placeholder="name">
    </div-->


```
**What is the motivation / use case for changing the behavior?**
because if lene is null, we get exception 

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Angular strips out comments from a template.
Repro: https://plnkr.co/edit/jZnD8g6Q5SBAapIIMwZh?p=preview

**Comment by visualinventor** [comment]
For the record Angular 2 latest is stripping comments in any html template.

Is this expected behavior?
How, in a development environment can we KEEP the comments?

**Comment by DzmitryShylovich** [comment]
Angular has its own html parser and comments in templates will significantly complicate parsing.

**Comment by visualinventor** [comment]
So moving forward, to tell the next developer what was going on in the code, 6 months previously, what code mechanism is available?

**Comment by glinkot** [comment]
I find Angular just ignores the comment indicators and renders it anyway.  Having a way to comment things out would be a big help.

**Comment by mustafALshamari** [comment]
huh
