### ISSUE TITLE
@angular\core\src\application_ref #createPlatformFactory() Typo: parentPlaformFactory

### ISSUE THREAD

**Issue by oustn** [angular/angular#13512]
I think it is not a problem, But I want make it better.

@angular\core\src\application_ref #createPlatformFactory function may be the parameter **parentPlaformFactory** is a typo

**Comment by Toxicable** [comment]
Please fill out the Issue template or your issue may be clsoed without investigation

**Comment by oustn** [comment]
@Toxicable  It's not a issue. I just read the angular code and find a typo. The file is @angular\core\src\application_ref.ts and thecreatePlatformFactory faction's parameter : **parentPlaformFactory ** . Maybe it's a unnecessarily  feedback. Sorry.

**Comment by Toxicable** [comment]
A typo can still be considered an issue but there is a template there for a reason, I would suggest you use it
