### ISSUE TITLE
Template parse errors with ICU messages

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#13525]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using the i18n attribute and expressions, putting a wrapping div around my html fails the template parser.

The error message is

```
Unexpected closing tag "div" ("emale()">&#9792;</button>
    <span i18n>The hero is {gender, select, m {male} f {female}}</span>
[ERROR ->]</div>
```

If I remove the wrapping div it works. Seems to be related to the i18n expressions

**Expected behavior**
Should allow a wrapping div

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/JiQ74iOE5gAfoIcfSHRi?p=preview

The wrapper div is added in app.component.html

**What is the motivation / use case for changing the behavior?**

* **Angular version:** 2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [TypeScript 2.X]

**Comment by vicb** [comment]
`<span>{wolves, plural, =0 {no wolves} =1 {one wolf} =2 {two wolves} other {a wolf pack}}</span>`Cuases the issue and it's not related to i18n.
