### ISSUE TITLE
With 2.3.1 AOT compile is success but bootstrap error in browser

### ISSUE THREAD

**Issue by mmrath** [angular/angular#13521]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With 2.2.3 AOT Compile is success also I an able to load the application fine. After upgrading to 2.3.1 AOT compile is fine but the application does not load in browser. The application does nothing, just a seed app. Error in browser is

Error: No provider for Store!
    at NoProviderError.BaseError [as constructor] (errors.js:34) [angular]
    at NoProviderError.AbstractProviderError [as constructor] (reflective_errors.js:63) [angular]
    at new NoProviderError (reflective_errors.js:112) [angular]
    at ReflectiveInjector_._throwOrNull (reflective_injector.js:1007) [angular]
    at ReflectiveInjector_._getByKeyDefault (reflective_injector.js:1044) [angular]
    at ReflectiveInjector_._getByKey (reflective_injector.js:994) [angular]
    at ReflectiveInjector_.get (reflective_injector.js:756) [angular]
    at AppModuleInjector.createInternal (app.module.ngfactory.ts:773) [angular]
    at AppModuleInjector.NgModuleInjector.create (ng_module_factory.js:139) [angular]
    at NgModuleFactory.create (ng_module_factory.js:107) [angular]
    at eval (application_ref.js:367) [angular]
    at Object.onInvoke (ng_zone.js:271) [angular] 

**Expected behavior**

If AOT compile is fine, application should load fine. 

**Minimal reproduction of the problem with instructions**
Here is a sample repo.
https://github.com/mmrath/ngc-2.3.1-aot-bug.git

with the latest code run the following  commands and see the error in browser
1. npm install 
2. npm run compile:dev 
3. npm run prodserver 

If you remove the latest commit which only upgrades  to 2.3.1 from 2.2.3 and run  the above steps then application runs fine.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Mac, npm/yarn

* **Angular version:** 2.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v7.2.1

**Comment by DzmitryShylovich** [comment]
cc @robwormald

**Comment by mmrath** [comment]
@DzmitryShylovich Could it be ngrx/store issue?

**Comment by alexeagle** [comment]
I would guess that ngrx/store needs to re-publish, there was a bug in the metadata collector of 2.3.0 that produced v2 metadata.json files that are missing things.

**Comment by vicb** [comment]
When v2 metadata are loaded the compiler should throw, must not be the root cause.
v1 metadata still works (the issue is applicable to v2 only)

**Comment by vicb** [comment]
@mmrath could you try to reproduce the bug on a simpler setup with less dependencies (angular & store only). That would help. Thanks.

**Comment by chuckjaz** [comment]
This is the same issue as #13307. See the analysis I wrote of the problem there. The work-arounds, in this case, don't apply but the description of the issue does.

The PR #13526 is tracking the work to fix this regression.
