### ISSUE TITLE
Unhandled Promise Rejection: Template parse errors: 

### ISSUE THREAD

**Issue by steady-daddy** [angular/angular#13520]
**I'm submitting a ...**  (check one with "x")

[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior**
Using FormBuilder Component 

**Expected behavior**
Should build form with the provided fields

**Minimal reproduction of the problem with instructions**
The code at the bottom was used which produces this error.

**What is the motivation / use case for changing the behavior?**

To create a sign up form

**Please tell us about your environment:**
**OS:** Windows 7
**IDE:** WebStorm
**PM:** Webpack
This is a angular-cli project

* **Angular version:** **2.1.1**

* **Browser:** 
**Chrome:** Version 55.0.2883.87 m (64-bit)
**Firefox Developer Edition:** 45.0a2 (2015-12-23)
* **Language:** 
"typescript": "~2.0.3"

* **Node (for AoT issues):** `node --version` =   
v6.9.1

**ERROR**
```
Unhandled Promise rejection:

Template parse errors:
Can't bind to 'formGroup' since it isn't a known property of 'form'. ("

          <div class="card">
              <form [ERROR ->][formGroup]="signupForm" (ngSubmit)="submitForm(signupForm.value)" class="form">

```
**CODE**

**Component**

```
import {Component, OnInit, Inject} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';

@Component({
  templateUrl: './checkup.component.html',
})
export class CheckupComponent implements OnInit {

  signupForm: FormGroup;
  constructor(@Inject(FormBuilder) fb: FormBuilder) {
    this.signupForm = fb.group({
      firstName : '',
      lastName  : '',
      email     : '',
      avatar    : '',
      age       : '',
      hometown  : '',
      gender    : ''

    });
  }

}

```
**Template Snippet:**
```
<form [formGroup]="signupForm" (ngSubmit)="submitForm(signupForm.value)" class="form">
...
</form>

```

**Comment by DzmitryShylovich** [comment]
Pls add a small working repro in plunkr

**Comment by DzmitryShylovich** [comment]
> Can't bind to 'formGroup' since it isn't a known property of 'form'

means you didn't import `ReactiveFormsModule`

**Comment by steady-daddy** [comment]
@DzmitryShylovich Did that. It didn't work.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
