### ISSUE TITLE
Allow @Input setter to respond without change

### ISSUE THREAD

**Issue by ayyash** [angular/angular#13539]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Child component @Input setter:
```
private _total: number;
@Input()
	set total(total: number) {
		console.log("set");
		this._total = total;
	}
	get total(): number { return this._total; }
```
Currently, if the total does not change value, it does not call the setter, normally in Typescript, the setter always gets called.

**Expected behavior**
The setter should be called every time the bound property is set, not just when it changes

**Minimal reproduction of the problem with instructions**
See above

**What is the motivation / use case for changing the behavior?**
I know it has been discussed before that the Child component only detects changes, but I am arguing that ngOnChange is already designed for that, the need for a setter arises because the way a child component property can be directly set is not seamless (need to import the sub child class, and decorate it with @ViewChild), this becomes impractical after a couple of times in the same page. In my case, I use a pagination child component, I depend on the "total" to be set explicitly to reset the pager, when the total for whatever reason does not change, the pager does not get reset, so now, I have to explicitly reset the total to null, before getting into a process that might change it. This problem is easy to fix, but I can imagine more complex scenarios rising.

**Please tell us about your environment:**
VSCode insider, on Windows IISNode

* **Angular version:** 2.1.1

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
Could you elaborate more on your issue? or even better, reproduce it in a plunker
Specifically can you explain in what situation you expect the setter to be called, you mentioned that if the value doesn't change the setter wouldn't be called, in what situation would you expect the setter to be called if there isn't a new value to set?
I made this one trying to reproduce it https://plnkr.co/edit/ZiPdhZMbUefr9eo81cQ8?p=preview
which shows that the setter is indeed called when the component is created and the value of total is set

**Comment by kemsky** [comment]
In your case it is better to have paging model with current page and total and have component which can render this model, this way changes to paging model will be propagated correctly.

**Comment by vicb** [comment]
works as expected.
