### ISSUE TITLE
2.3.1 (electron) HostListener runs outside of NgZone

### ISSUE THREAD

**Issue by fknop** [angular/angular#13548]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

HostListener runs outside of NgZone and does not trigger change detection.
I have a piece of code that worked fine in `2.1.0` that broke when I updated to `2.3.1`.

After some tests in multiple components, not a single HostListener runs in the NgZone.

**Expected behavior**

HostListener always runs inside of NgZone.

**Minimal reproduction of the problem with instructions**

I could not reproduce the problem in a plunkr with `2.3.1` version. I think it may be related to Electron.

By looking at the commits between 2.1.0 and 2.3.1, I tried reverting the changes locally in the angular bundle from this commit https://github.com/angular/angular/commit/648ce59#diff-cfd9df831a0a999da4cd9bf53c8cd719L21 and it's working as expected.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* Windows 10

* **Angular version:** 2.3.1

* **Browser:** Electron app on Windows 10
* **Language:** Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by tbosch** [comment]
We did a recent performance optimization in 648ce5981bf22ba9b36d905183fb0825812354d0 where we don't first exit the zone and then enter again for plain dom events like `click`.

This works fine if your platform integrates correctly with zone.js and the component was also created in the Angular zone, as then zone.js will take care of calling the handler inside of the Angular zone as well.

So the real question here is how electron is integrating with zone, and how the initial component is created.

We need a reproduction for this, as this works fine in universal and the browser and our webworkers.

**Comment by tbosch** [comment]
I.e. it seems very likely that this is a problem with the electron integration. Which one are you using?

**Comment by tbosch** [comment]
@robwormald can you look into this as you created https://github.com/angular/angular-electron?

**Comment by fknop** [comment]
I'm going to try to create a minimal repro tomorrow if I have time.

**Comment by fknop** [comment]
I'm not using any integrations. The angular-electron repo is out of date and seems to be inactive.

**Comment by fknop** [comment]
The issue appears to be coming from the way I was importing Zone.js. I was using a `require` call to import it. I tried with a script tag and it's working as expected. 

I'm closing the issue.
