### ISSUE TITLE
 activeError: Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by theunreal** [angular/angular#13559]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When trying to `ng serve` my application, I get:

` activeError: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in c:/xampp/htdocs/pokemo/src/app/app.module.ts, resolving symbol AppModule in c:/xampp/htdocs/pokemo/src/app/app.module.ts`

**Expected behavior**

App builds successfully.

**Minimal reproduction of the problem with instructions**
Unable to reproduce. Build my app.. It's big and has more than 30 components

My app module providers:

```
providers: [JwtService,
  NotificationsService,
  {provide:RequestOptions, useClass: CustomRequestOptions }
  ],
```

**What is the motivation / use case for changing the behavior?**
App builds in more cases

**Please tell us about your environment:**
Windows, Xampp

* **Angular version:** 2.0.X
2.1.2

* **Browser:** [all]
 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =   6.5.0

**Comment by DzmitryShylovich** [comment]
You cannot use functions in metadata. Your code should be statically analyzable.

**Comment by DzmitryShylovich** [comment]
See https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.dpf91ab62
