### ISSUE TITLE
A few dynamic use-cases for ng-class

### ISSUE THREAD

**Issue by mcferren** [angular/angular#1355]
Is it possible to use ng-class to dynamically generate a relationship with the css/sass file so that I could invoke/instantiate animations and build out a better finite state machine? Instead of bool expressions as seen here:

ng-style="{'color': identity.color};"
       ng-class="{'red':matryoshkanode.color === 'red',
                       'blue':matryoshkanode.color === 'blue',
                       'green':matryoshkanode.color === 'green',
                       'purple':matryoshkanode.color === 'purple',
                       'orange':matryoshkanode.color === 'orange'}">

Is it possible to use ng-class to dynamically generate the directive annotation on that html element instead of having a bunch of ng-if's for each type of directive? 

	<div ng-repeat="tabBody in returnTabList">
		<div ng-if="nodeState.selection.name == tabBody">

			<div ng-if="nodeState.selection.layout === 'poster'" 
				 class="poster-tab"
				 matryoshkanode="nodeState"
				 matryoshkatemplate="templatestate"></div> 

			<div ng-if="nodeState.selection.layout === 'day'" 
				 class="day-tab"
				 matryoshkanode="nodeState"
				 matryoshkatemplate="templatestate"></div> 

			<div ng-if="nodeState.selection.layout === 'folder'" 
				 class="folder-tab"
				 matryoshkanode="nodeState"
				 matryoshkatemplate="templatestate"></div> 

			<div ng-if="nodeState.selection.layout === 'details'" 
				 class="details-tab"
				 matryoshkanode="nodeState"
				 matryoshkatemplate="templatestate"></div> 

			<div ng-if="nodeState.selection.layout === 'table'" 
				 class="table-tab" 
				 matryoshkanode="nodeState"
				 matryoshkatemplate="templatestate"></div>

			<div ng-if="nodeState.selection.layout === 'edit'" 
				 class="edit-tab"
				 matryoshkanodeidentity="identity"
				 matryoshkatemplate="templatestate"></div>
		</div>
	</div>

**Comment by pkozlowski-opensource** [comment]
@mcferren this is wrong repo, I guess you were looking for https://github.com/angular/angular.js

But please don't open GitHub issues for the general support questions like this one, but instead use a dedicated support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Thnx!
