### ISSUE TITLE
Make PostMessageBus API as a public API

### ISSUE THREAD

**Issue by apoterenko** [angular/angular#13555]
**I'm submitting a feature request** 
Can you make the API as Public?

**Current behavior**
I have to do something like at current time: 
```
import {
    PostMessageBusSource,
    PostMessageBusSink
} from '@angular/platform-webworker/src/web_workers/shared/post_message_bus';
```

**Expected behavior**
```
import {
    PostMessageBusSource,
    PostMessageBusSink
} from '@angular/platform-webworker';
```

**What is the motivation / use case for changing the behavior?**
I wanna use API out of the box at the third party library (https://www.npmjs.com/package/angular2-post-message)

* **Angular version:**
"@angular/platform-webworker": "2.2.4"

* **Language:**
TypeScript 1.x, 2.x

**Comment by apoterenko** [comment]
https://github.com/angular/angular/issues/13555

**Comment by jelbourn** [comment]
Closing all issues related to web-workers since Angular's experimental web-worker renderer has been deprecated and it now being removed completely in Angular v11.
