### ISSUE TITLE
control (for ex: lazy load) third party js in component

### ISSUE THREAD

**Issue by infofromca** [angular/angular#13557]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
right now, it seems the only way is using router to lazy load third party js according to angular.io

**Expected behavior**
lazy load third party js inside one component (or its child)
in other word, can use hook to control other js loading 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
do not need to wait for very heavy 3 party js

**Please tell us about your environment:**

* **Angular version:** 2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by tbosch** [comment]
Angular supports lazy loading via `NgModuleFactoryLoader`. I.e. you can inject it yourself and call it to get an `NgModuleFactory` which is able to create new instances of an NgModule. 

In Angular, the entry point to bootstrap and lazy loaded code is always an `NgModule` instance. If you want to just do your own lazy loading of third party code, use existing mechanisms like `System.import`, ... that work independently of Angular.
