### ISSUE TITLE
Cannot find templateUrl for debug build of aot enabled app

### ISSUE THREAD

**Issue by skendrot** [angular/angular#13553]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

With aot enabled site, templateUrl fails to download in debug build

**Expected behavior**

The templateUrl should download without issue

**Minimal reproduction of the problem with instructions**

Following the docs for setting up an aot enabled app I made templateUrl a relative path, set the moduleId on the component, set an id on the module and adding the window.module to the index.html page. When loading the component the site tried to load the template url from ~/templateUrl.
See plunker: http://plnkr.co/edit/M4yogzUSJDnQxojAUVpc?p=preview

**What is the motivation / use case for changing the behavior?**

Need to debug the application 

**Please tell us about your environment:**

My dev environment is Windows 10 using VS2015

* **Angular version:** 2.2.4

* **Browser:** [all ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
v6.9.1

**Comment by DzmitryShylovich** [comment]
See https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html

**Comment by skendrot** [comment]
If I change the modileId as such `moduleId: module.id` then TypeScript won't compile as well as the aot compiler. 
Running ngc yields the following error:

> Error: Error at D:/sandbox/angularmvc/angularmvc/app/components/todolist/todolist.component.ts:31:15: Cannot find name 'module'.
>     at check (D:\sandbox\angularmvc\angularmvc\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
>     at Tsc.typeCheck (D:\sandbox\angularmvc\angularmvc\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)
>     at D:\sandbox\angularmvc\angularmvc\node_modules\@angular\tsc-wrapped\src\main.js:33:23
>     at process._tickCallback (internal/process/next_tick.js:103:7)
>     at Module.runMain (module.js:606:11)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> Compilation failed

I'm using the following repo: https://github.com/skendrot/angular2-test

**Comment by DzmitryShylovich** [comment]
do u use systemjs or webpack?

**Comment by skendrot** [comment]
systemjs: https://github.com/skendrot/angular2-test/blob/master/angularmvc/systemjs.config.js

**Comment by skendrot** [comment]
added the following to my component
```
declare var module: any;
```

Is there another way to fix this? Is this a bug on the [aot doc](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#overview)?

**Comment by skendrot** [comment]
up?

**Comment by ibqn** [comment]
@skendrot This is one of the reasons, I do not like to deal with module.id at all, as it is only useful in development. So, instead I host the test server from multiple folders, see for more details my [quick start](https://github.com/ibqn/ng2-quick-start).

...and this answers from stackoverflow about [meaning of module.id](https://stackoverflow.com/questions/37178192/angular2-what-is-the-meanings-of-module-id-in-component).

**Comment by tbosch** [comment]
Yes, this is a know bug, see https://github.com/angular/angular/issues/11613.
Btw, Angular-cli does some magic so you don't need `moduleId` when using `jit`, but we should really fix this...

Closing as a duplicate.

**Comment by skendrot** [comment]
This actually had nothing to do with the linked bug. I did discover that I had to add @types/node to my packages. I do not believe this is noted in the documentation @tbosch
