### ISSUE TITLE
AOT: component is rendered without firing any lifeCycleEvents defined in a superclass

### ISSUE THREAD

**Issue by dabalyan** [angular/angular#13564]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Application runs perfectly without AOT.
structure: `AppModule -> PageComponent -> ChildComponent`
`ChildComponent` is derived from a superclass `TheSuperClass`, superclass defines some lifeCycleEvents for the `ChildComponent` like `ngOnit`. Component is rendered (in the DOM) but the `ngOnInit` is not called.

**Expected behavior**
AOT shouldn't break what was already working and call the `lifeCycleEvents` as expected.

**Minimal reproduction of the problem with instructions**

- run `$ npm install -g ionic cordova`
- run `$ ionic start TestApp --v2`
- run `cd TestApp`
- create `TheSuperClass` having `ngOnInit` defined within it, `console.log('somthing')` to test. 
- create `ChildComponent` by extending `TheSuperClass`. 
- use `ChildComponent` in any Page.
- run `$ ionic run android --aot`

I can't decide if it's Angular related or Ionic related.
I can make a pluker without Ionic, but is AOT possible there ?

**What is the motivation / use case for changing the behavior?**
I have multiple components with almost same methods and variables, with some differences in template and dedicated methods. Hence I use a `SuperClass` to avoid repeating the same code.

**Please tell us about your environment:**
OS: Windows10 Professional
Node: v6.9.1
npm: v3.10.8
Ionic: 2.0.0-rc.4 (2016-12-15)

* **Angular version:** 2.1.1

* **Browser:** [all ]
 
* **Language:** [TypeScript 2.0.9]

* **Node (for AoT issues):** `node --version` =   v6.9.1

**Comment by DzmitryShylovich** [comment]
> Angular version: 2.1.1

u need 2.3.1

**Comment by dabalyan** [comment]
Thanks for quick reply. Has this issue been solved explicitly. or it's just supposed to be solved in `2.3.1`. By the way Ionic defines used the Angular version by default, I don't if it will work with manual Angular update.

**Comment by DzmitryShylovich** [comment]
> Has this issue been solved explicitly.

yeap. https://github.com/angular/angular/blob/master/CHANGELOG.md#features-2

**Comment by dabalyan** [comment]
Oh OK. Let me give it a try.

**Comment by dabalyan** [comment]
Neah, didn't work. 
With `--aot` it fails like

> [15:04:11]  ionic-app-script task: "build" 
> [15:04:11]  TypeError: Cannot read property 'parse' of undefined 

guess I'll have to just head over to Ionic's repo and request for an upgrade as quickly as possible.
Thanks.

**Comment by DzmitryShylovich** [comment]
@dabalyan can this be closed?

**Comment by dabalyan** [comment]
Sorry for late reply. 
Ionic guys still haven't relaeased a new version with updated Angular, so I think it can be closed for now, I obviously don't know if it will surface again.

**Comment by DzmitryShylovich** [comment]
@dabalyan so close it pls. Feel free to reopen if it won't be fixed after new ionic release :)
