### ISSUE TITLE
Angular does not exclude ngIf elements from being sent as part of form data.

### ISSUE THREAD

**Issue by sudharsanmit** [angular/angular#13563]
[X] bug report

Angular does not exclude ngIf elements from being sent as part of form data.

**View:**
```
                      <ion-item *ngIf="storeData.taxbyCounty">          
                          <ion-label floating color="primary">County</ion-label>
                          <ion-input type="text" formControlName="county"></ion-input>
                      </ion-item>             
                      <ion-item *ngIf="storeData.taxbyState">          
                          <ion-label floating color="primary">State</ion-label>
                          <ion-input type="text" formControlName="state"></ion-input>
                      </ion-item>
                      <ion-item *ngIf="storeData.taxbyZip">          
                          <ion-label floating color="primary">Zip</ion-label>
                          <ion-input type="text" formControlName="zip"></ion-input>
                      </ion-item>                  
                      <ion-item *ngIf="storeData.taxbyCountry">          
                          <ion-label floating color="primary">Country</ion-label>
                          <ion-input type="text" formControlName="country"></ion-input>
                      </ion-item>                  

```
**Component**
  initTax(county,state,zip,country){
      return this.fb.group({
        'county': [county,Validators.required],
        'state':[state,Validators.required],
        'zip': [zip],
        'country': [country,Validators.required]        
      });
  }

Form Data being sent upon submit:

taxbyCountry:true
taxbyCounty:true
taxbyState:true
taxbyZip:false
..
country:"US"
county:"Salt"
state:"UT"
zip:"84116"

**Comment by DzmitryShylovich** [comment]
Pls add:
1. a small repro in plunkr without ionic.
2. steps to reproduce.
3. expected behavior.

**Comment by zoechi** [comment]
I think that is expected behavior. If the element doesn't exist then it's not part of the form data.
Use `[hidden]="storeData.taxbyCounty"` instead, then it will stay part of the form.

**Comment by sudharsanmit** [comment]
@zoechi Exactly my point. I want to exclude the data as part of my form, but still getting sent. [hidden] and *ngIf behaving the same way here which is not expected.
@DzmitryShylovich I will add it soon.

**Comment by sudharsanmit** [comment]
Checkout this plunkr.

[Plunker Example](https://plnkr.co/edit/3YnXNJUTRJDpRiBbw7eq)

When you just hit signup, the form data is not expected to have the account object in the console.log.

But it does. *ngIf functions as [hidden]=true in case of Forms.

**Comment by tytskiy** [comment]
@sudharsanmit i think `[ngIf]` is simple view directive, which has nothing to do with reactive form.

There is a potential solution for your use case: https://plnkr.co/edit/NfHNJgTvtq38Wil1l39x?p=preview

**Comment by sudharsanmit** [comment]
ngIf is a powerful view directive which takes out an element from being
rendered. If not rendered, it should not even be part of the json. Pls go
through the example I provided. It is a bug but with a workaround.

On Tuesday, December 20, 2016, Oleksandr Tytskyi <notifications@github.com>
wrote:
> @sudharsanmit i think [ngIf] is simple view directive, which has nothing
to do with reactive form.
>
> There is a potential solution for your use case:
https://plnkr.co/edit/NfHNJgTvtq38Wil1l39x?p=preview
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/ieXyObHDkXwI7NkTvaDAfoOKcFhNz4lpdCgoPBiUWsoqewmVHPvye6G7Dbjp_xaoThfhow-9YeRlM5ofZlkcVHfetvu-8WxA8QIHn-V1c7Hv-IIRSoGesiQbALXMSvOPl0AT6LMKP6GBJFzIPm79xMN3O_XaXg=s0-d-e1-ft#https://github.com/notifications/beacon/AP-IYZTszmjjve0oPZRZWPhzUjKCEzt5ks5rJ8KVgaJpZM4LQXo8.gif>

**Comment by tbosch** [comment]
@sudharsanmit `ngIf` only changes how your forms is displayed, but not what data it contains. I.e. the data controls the view, but not the other way around. Your `ngSubmit` callback will still be fired with the same data.

Regarding reactive forms: Angular has 2 kind of forms, "template driven" and "Reactive forms". you are using the "Reactive Forms" approach, see https://angular.io/docs/ts/latest/cookbook/form-validation.html. 

This is works as intended.
