### ISSUE TITLE
[i18n] Support multiple xlf/xmb files per application

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#13577]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Unless I am missing something obvious, it seems like the i18n tool assumes that you are extracting a single i18n file for the entire application. 

My experience is that this is not an ideal workflow for large multi-team applications. Maintaining a shared file doesn't seem like it will scale.

**Desired behavior**
It would be very helpful if the tool allowed us to extract the translations into multiple, smaller files that could be pieced together later. 

e.g.
Allow Team A and Team B to maintain separate files, specific to feature A and Feature B 

**What is the motivation / use case for changing the behavior?**
Making it easier for multiple teams to work on larger apps.

**Comment by sudharsanmit** [comment]
+1

You wouldn't publish 100 apps to app store if you want to support 100 languages!

**Comment by thelgevold** [comment]
Just to be clear. This is not about requiring separate apps per language. This is about helping the dev process by giving the developers access to feature specific pieces of the main xml file. 

This proposal would not remove the requirement to publish a different static app per language.

**Comment by sudharsanmit** [comment]
Oops. Misunderstood. 

If AoTcompiler is Angular's norm, putting it together later doesn't make sense. Also, multiple xmls will create non-unique translations and it will create more confusion than what it tries to help.

**Comment by vicb** [comment]
@sudharsanmit I guess it would be opt-in and would probably help some people.

**Comment by paumayr** [comment]
I think my feature request is related: #11431 (Feature Request [i18n]: Support providing TRANSLATIONS at NgModule level). I think module-level granularity seems right?

**Comment by vicb** [comment]
@paumayr right, I'm going to close this one as a duplicate. Still we should be able to provide multiple translations for the same "unit" - ie use the default translations provided by the "unit" (think module author here) but override some of them.
