### ISSUE TITLE
trackBy, class interp and class binding causes class binding to disappear

### ISSUE THREAD

**Issue by intellix** [angular/angular#13576]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If you have an `ngFor`, `trackBy`, `class interpolation` and `class binding` on an element, when you change the state of the user and replace the row (change class interp), it will remove the class binding and never work again.

**Expected behavior**

Expected the class interpolation to not be removed when combined with a class binding and trackBy after changing data.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/g1jZcFihiEd3hmYCl2Jf?p=preview

**What is the motivation / use case for changing the behavior?**

I want to use trackBy for performance and use both class interp and binding

**Please tell us about your environment:** 

* **OS:** OSX Sierra

* **Angular version:** 2.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

**Comment by vicb** [comment]
Please strip down your plunker to the minimal amount of code required to reproduce the issue and describe observed vs expected behavior clearly.

**Comment by intellix** [comment]
@vicb The plnkr increased in complexity as I debugged one of my own issues. I've simplified it greatly to showcase the error.

**Comment by pkozlowski-opensource** [comment]
In can by reproduced much, much simpler, check this plunk: http://plnkr.co/edit/pChDo1T5f8RUCyNo9xmo

The difference boils down to the _order_ of bindings: compare `<div class="{{'foo'}}" [class.me]="true">` to ` <div [class.me]="true" class="{{'foo'}}">`.

We should keep in mind that doing `class="exp"` is equivalent to binding to `className` property which means "replace _all_ classes with one from the expression". If it is done after `[class.me]="true"` then you are out of luck....

Maybe we could modify the framework so `[class.foo]` are executed after all other bindings. But using `class="{{exp}}"` and `[class.foo]="exp"` on one element is playing with fire as long as order of binding execution is not deterministic in the framework. As such I would stick to one: http://plnkr.co/edit/94JlXYovPiAJSFcv5Y7d?p=preview

**Comment by vicb** [comment]
@pkozlowski-opensource should this be closed ?

**Comment by pkozlowski-opensource** [comment]
@vicb we could close this _or_ make compiler more deterministic.

**Comment by intellix** [comment]
ok, thanks for the explanation. I originally thought it worked like a server-side language would:

```
<div class="something <?= $player->state ?>"></div>
```

Hope this helps someone else :)
