### ISSUE TITLE
Output a version number

### ISSUE THREAD

**Issue by armorik83** [angular/angular#1357]
Hi.

In AngularJS 1.x, `console.log(angular.version);` to output the following.

```
{
  full: "1.3.x",
  major: 1,
  minor: 3,
  dot: x,
  codeName: "codeName"
}
```

I want you to adopt also in Angular 2 this feature for utility development. For example,

``` js
import * as angular2 from 'angular2/angular2';
console.log(angular2.version);
```

```
{
  full: "2.0.0-alpha.n",
  major: 2,
  minor: 0,
  dot: 0,
  codeName: "codeName"
}
```

Thanks.

**Comment by DeborahK** [comment]
Would it be possible to provide the version at the command line? Something like this: `angular.core.version` or `angular.forms.version`? That would make it easier for us to help diagnose errors and issues reported by other developers, especially beginners.

**Comment by fmorriso** [comment]
+1
for both a command-line as well as a run-time API to get major, minor and full "version" information.

**Comment by vsavkin** [comment]
Closed by https://github.com/angular/angular/commit/e628b66cca623bb86e5350d60654cdbb51ae35db

**Comment by brentonklassen** [comment]
Why was this closed? I want to be able to view the version at runtime.

**Comment by DeborahK** [comment]
```
//our root app component
import {Component, NgModule, VERSION} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser'

@Component({
  selector: 'my-app',
  template: `
    <div>
      <h2>Hello {{name}}</h2>
    </div>
  `,
})
export class App {
  name:string;
  constructor() {
    this.name = `Angular! v${VERSION.full}`
  }
}

@NgModule({
  imports: [ BrowserModule ],
  declarations: [ App ],
  bootstrap: [ App ]
})
export class AppModule {}
```
