### ISSUE TITLE
Angular2 - ReactiveFormsModule - composeAsync fails

### ISSUE THREAD

**Issue by danicomas** [angular/angular#13588]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
CustomValidator observable not validate the input

**Expected behavior**

CustomValidator observable should validate the input

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/TVLKiunktrVbLSoFDkDY?p=info

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome 55 ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Second arg is sync validator. It should be `slug: ["", null, CustomValidator.slug]`

**Comment by danicomas** [comment]
@DzmitryShylovich I don't want a sync validator. I am creating a promise because I want to simulate an ajax request.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L645

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/YsYtVIZExcF9u12nX0ud?p=preview

**Comment by danicomas** [comment]
Thanks @DzmitryShylovich, the problem was ```slug: ["", null, CustomValidator.slug]]```, the second parameter.

**Comment by danicomas** [comment]
@DzmitryShylovich Why observable is mandatory if we add one observable validator? For example:

[Validators.Required (sync),Validators.slug(is async)] crash with the error doesn't have .subscribe.

Is it ok?

**Comment by danicomas** [comment]
https://github.com/angular/angular/issues/13662
