### ISSUE TITLE
Route data's symbol properties are lost during JIT

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#13587]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

* Add data with symbol property key to route
* Inject ActivatedRoute to component
* Check data on the route
* Property with symbol key is missing

**Expected behavior**

Properties with symbol key will be preserved as ordinary properties.

**Minimal reproduction of the problem with instructions**

Check console of this [plunker](https://plnkr.co/edit/WXiO9fsw4rskOkinzR6m?p=preview)

**What is the motivation / use case for changing the behavior?**
Ability to use Symbol properties in route data

* **Angular version:** 2.3.1

* **Browser:** [Chrome 55]

 
* **Language:** [TypeScript 2.0]

**Comment by vicb** [comment]
What is the use case ? (ie would you be happy if we document that it is not supported w/o further actions).
They are probably many other places in the framework where we do not propagate `Symbols`.

**Comment by WiseBird** [comment]
Yes, if it is hard to fix then at least made it clear please.

**Comment by DzmitryShylovich** [comment]
@WiseBird pls re-open it then on https://github.com/angular/angular.io/issues
