### ISSUE TITLE
Upgrade provider(static)  can't read property get of undefined

### ISSUE THREAD

**Issue by AlexKhymenko** [angular/angular#13584]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Static. Upgrade providers not working when you try upgrade 3-party libraries in this case ui router.
With angular upgrade iteration 1 everything works.
providers: [{
    provide: '$state',
    useFactory: (i: any) => i.get('$state'),
    deps: ['$injector']
  }],
it always shows can't read property get of undefined. With angular 1 services everything works.
**Expected behavior**
You can upgrade 3-party libraries
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:** [all ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by chuckjaz** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by AlexKhymenko** [comment]
If somebody encounters this problem check if you have service In APP initializer.
