### ISSUE TITLE
"Can't resolve all parameters for" error message masks invalid TypeScript syntax error message using AoT compiler

### ISSUE THREAD

**Issue by alexsapps** [angular/angular#13596]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When there's a TypeScript syntax error preventing resolving parameters, the AoT compiler gives "Can't resolve all parameters for MyComponent in path/to/file"

**Expected behavior**
The TypeScript syntax error should be printed instead. For example, this is a syntax error:

```
  constructor(
      // Wrong: decorator goes before `private`
      private @Inject(TOKEN) myDependency: any) {
  }
```

This results in a TypeScript compiler error and so should print the error given by the typescript compiler:
`Parameter 'private' implicitly has an 'any' type.`

Related: https://github.com/angular/angular/issues/12467
Related: https://github.com/angular/angular/issues/13087

**Minimal reproduction**

In an AoT enabled project, correctly inject a dependency into a component's constructor, then remove any visibility modifiers and add `private` after the `@Inject` decorator.

**What is the motivation / use case for changing the behavior?**
The correct error would be more actionable for developers than the opaque error given currently.

**Please tell us about your environment:**
ask who/ajxtaylor

* **Angular version:** 2.0.X

* **Browser:**
N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by DzmitryShylovich** [comment]
This error should be reported by proper ide :)

**Comment by vicb** [comment]
Also this probably belongs to TS (rather than Angular)

**Comment by DzmitryShylovich** [comment]
@alexsapps what ts version do u use?

**Comment by alexsapps** [comment]
@vicb I only see the vague error message when I use Angular's AoT compiler. The TS compiler gives a more specific error. Maybe I'm not understanding, but I don't think the TS people can make AoT produce more specific errors.
@DzmitryShylovich I think I'm using 2.0.6.

**Comment by DzmitryShylovich** [comment]
I agree with @alexcastillo A project is compiled using `ngc` before `tsc` so it's no a ts issue.
