### ISSUE TITLE
Documentation on testing components using RouterOutlet outdated

### ISSUE THREAD

**Issue by nbuso** [angular/angular#13608]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The documentation about RouterOutlet testing is out of date:
https://angular.io/docs/ts/latest/guide/testing.html#!#router-outlet-component

Specifically I can't find with a search the class RouterOutletStubComponent
https://github.com/angular/angular/search?utf8=%E2%9C%93&q=RouterOutletStubComponent

**Expected behavior**

Have a working example for the testing or pointing to a test in the source code repository

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

angular-cli 1.0.0-beta.22-1
angular 2.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

not relevant
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io

**Comment by nbuso** [comment]
OK I think in any case the documentation meant to create by yourself all the stubs in question. I'm closing this.
