### ISSUE TITLE
LOCALE_ID is overwritten with platformBrowserDynamic

### ISSUE THREAD

**Issue by fredrikredflag** [angular/angular#13607]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you provide `LOCALE_ID` as an extra provider like so:
`platformBrowserDynamic([{'provide': LOCALE_ID, 'useValue': 'sv'}]).bootstrapModule(AppModule) `
it gets overwritten with `en-US` .

**Expected behavior**
Keeping the `LOCALE_ID` provided.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/1Ev5fIVVwpPMgln6lMVJ?p=preview

* **Angular version:** 2.0.X
ng 2.3.0

**Comment by pkozlowski-opensource** [comment]
Since the default `LOCALE_ID` is registered as part of https://angular.io/docs/ts/latest/api/core/index/ApplicationModule-class.html it will overwrite platform providers. 

Just register `LOCALE_ID` as a provider in your root (app) module: http://plnkr.co/edit/8RnmGoSHgkYlHrHK4mLX?p=preview

**Comment by fredrikredflag** [comment]
@pkozlowski-opensource it's what I'm doing currently in my app. 

It's a bit odd that a default `provide` overwrites what has been provided by the application. In my case I'm using `i18n` as described in https://angular.io/docs/ts/latest/cookbook/i18n.html, where we already set `LOCALE_ID` in `getTranslationProviders()`.

Where you have this:
```
getTranslationProviders().then(providers => {
    const options = { providers };
    /// options.providers has the LOCALE_ID. 
    platformBrowserDynamic(<Provider[]>options.providers).bootstrapModule(AppModule, options);
});
```

You could always extract the logic that sets `LOCALE_ID` in `getTranslationProviders()` and then do something like:

```
@NgModule({
  imports: [ BrowserModule ],
  declarations: [ App ],
  providers: [{'provide': LOCALE_ID, 'useFactory': (LocaleService) => LocaleService.getLocale(), 'deps': [LocaleService]}],
  bootstrap: [ App ]
})
export class AppModule {}
```

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource what do u think is the proper fix in this case? provide it on platform lvl?
