### ISSUE TITLE
ReactiveForms: valueChanges unusable object 

### ISSUE THREAD

**Issue by hrantbagdasarian** [angular/angular#13619]
```
[x] bug report
[ ] feature request
[ ] support request
```
**Current behavior**
I have an object(make) which has child(models) elements. The form contains 2 select elements. The first element binds to the vehicle makes, and when a make is selected from the first select element, the second select element should be populated with the models of the vehicle make.
Subscribing to the valueChanges does in fact return an object, but I can't use the object in any way. It just always shows [object Object], even when piping to json or performing JSON.stringify.
I have even tried making the makes and models typed by creating classes and using them, but that does not work either.

**Expected behavior**
I would expect the value emitted by the valueChanges observable to be the actual selected make object and be able to access the models property.

**Minimal reproduction of the problem with instructions**
See this Plunker for the issue. 
https://plnkr.co/edit/WTncwIAm5Ijkg2tQqTKo?p=preview

**What is the motivation / use case for changing the behavior?**
This would allow binding to child elements when a parent element is selected.

**Please tell us about your environment:**
Mac OS Sierra 10.12.2
Angular: 2.2.3
Angular CLI: 1.0.0-beta-22-1

* **Angular version:** 2.2.3

* **Browser:** [all]
 
* **Language:** [TypeScript 2.0.3]

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by DzmitryShylovich** [comment]
You have to use `ngValue` instead of `value` for objects https://plnkr.co/edit/GTO8BKcOFAwksALzfb2R?p=preview

**Comment by hrantbagdasarian** [comment]
Thank you! You just saved me a lot of frustration.
