### ISSUE TITLE
formControl Performance issue with ngFor on <option> tags with a large array

### ISSUE THREAD

**Issue by airasheed** [angular/angular#13617]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have two routes. One route has a component that implements `[formControl]` on several `<select>` tags and uses `*ngFor` directive to populate the `<options>` like this:

```
    <select [formControl]="control" class="form-control">
       <option [value]="" disabled selected></option>
       <option [value]="item.id" *ngFor="let item of list">{{item.value}}</option>                
     </select>
```

The `fieldOptions.Product1` array can have 1000 values. When clicking on to the route with with the selects the route takes awhile to load. It looks like a performance issue with `*ngFor` on the `<option>` tag when there are 1000's of values for the `[formControl]`.

**Expected behavior**

The performance shouldn't take a hit when adding the `[formControl]` directive to the select.

**Minimal reproduction of the problem with instructions**

You can see a plunkr [here](https://plnkr.co/edit/2jNKFotBRIIytcmLto7y?p=preview).

If you click the Options route you will see the lag behavior.

**What is the motivation / use case for changing the behavior?**

Others may use [formControl] with an options array that has a large amount of values.

**Please tell us about your environment:**

Visual Studio Code, Mac OS X El Capitan

* **Angular version:** 2.3

* **Browser:** all

 
* **Language:** TypeScript 2.0.2

**Comment by DzmitryShylovich** [comment]
Did u try to use native select with the same amount of data?

**Comment by airasheed** [comment]
Yes when i remove `[formControl]` it seems to move quicker.

**Comment by kemsky** [comment]
9 * 10k  options, so there are 90k `NgSelectOption` directives created, 90k setters called, 90k `toString()` methods called (debug mode), 90k `onDestroy` methods called + change detection runs compare functions for each option directive multiple times. 

I doubt this approach can be optimized for your use case, it is better to create custom value accessor which has internal component with `OnPush` strategy and uses `innerHtml` for rendering.

**Comment by airasheed** [comment]
@kemsky do you think you can guide me to how to do what you suggested, through an example?

**Comment by jasonaden** [comment]
Sorry, but this is out of scope for the project. Rendering 90k records with a native browser API is certainly going to be faster than instantiating that many directives. However, the use case isn't clear here on when this could ever effectively be used in browser or mobile device.

If there's a use case that needs to be supported, please let us know in a new issue. Otherwise, you'll be better off wrapping these in some sort of a service so you're not rendering unusable DOM elements.
