### ISSUE TITLE
Error when upgrading from Angular 2.2.4 to Angular 2.4.0 with AOT compilation

### ISSUE THREAD

**Issue by wesleycho** [angular/angular#13613]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Without changing a working AOT build setup, when I upgrade my work app from Angular 2.2.4 to Angular 2.4.0 (and `@ngtools/webpack` to 1.2.1), I get this error in the console with no other useful identifier for figuring out the error (no stack trace or other info)
```
ERROR in Could not resolve "src/app/app.aot.module.ts" from "src/app/app.aot.module.ts".
```
Everything else seems to compile properly. `src/app/app.aot.module.ts` is my entry module file, and it just exports my entry module.

**Expected behavior**
It should compile fine with no errors

**Minimal reproduction of the problem with instructions**
I am not sure I can minimally reproduce this at all unfortunately

**What is the motivation / use case for changing the behavior?**
Upgrading breaks the app

**Notes**
The error seems to be thrown here: https://github.com/angular/angular/blob/a0a05041ac15598c3baccc3f84294199b589a195/modules/%40angular/compiler-cli/src/ngtools_impl.ts#L99 . Oddly enough, https://github.com/angular/angular/blob/a0a05041ac15598c3baccc3f84294199b589a195/modules/%40angular/compiler-cli/src/compiler_host.ts#L55-L57 seems to give me `undefined`.

**Please tell us about your environment:**
mac OS 10.12.1

* **Angular version:** 2.0.X
2.4.0

* **Browser:** N/A
 
* **Language:** TypeScript 2.0.7

* **Node (for AoT issues):** `node --version` =   4.5.0

**Comment by DzmitryShylovich** [comment]
Can u reproduce it without ngtools/webpack?

**Comment by mlaval** [comment]
I had the same kind of issue. I "solved" it by changing the plugin configuration from:
```
new aotplugin.AotPlugin({
  tsConfigPath: './tsconfig.json',
  entryModule: './app/module#AppModule'
})
```
to
```
new aotplugin.AotPlugin({
  tsConfigPath: './tsconfig.json',
  entryModule: 'app/module#AppModule'
})
```

I believe that the issue comes from `@ngtools/webpack`, it was working with 1.1.7 but started to happen with 1.2.1.
So it should be opened in the angular-cli repo.

**Comment by wesleycho** [comment]
Well I'll be damned - after removing `styleUrls`, `./node_modules/.bin/ngc -p ./tsconfig.aot.json` seems to have worked for me. Could this be a `@ngtools/webpack` bug?

**Comment by wesleycho** [comment]
Thanks everyone, will open a new issue there and cross-link this.
