### ISSUE TITLE
DI feature: lifecycle hooks for services, especially OnDestroy

### ISSUE THREAD

**Issue by wardbell** [angular/angular#13618]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
[x] feature request
[ ] support request 
```

**Current behavior**

When destroying an injector, Angular has no way AFAIK to inform the service instances in the injector that they are doomed.

If a service is holding valuable resources (e.g., a message bus holding subscriptions) it doesn't know to let go.

**Expected behavior**

If the service has an `ngOnDestroy`, Angular should call it as it destroys/releases its hold on an injector (e.g., when destroying a component).

Is this safe? Only if the service is created by the injector ... which isn't _always_ the case ( almost anything except `useClass`).

OTOH, if the developer adds an `ngOnDestroy` method, she should expect it to be called and not put her service in compromising position.

On balance, I think its a useful feature, with no obvious substitution, and one *consistent with disposable patterns in other languages*.

p.s.:  The only other lc-hook that makes sense is `ngOnInit` and the developer can easily compensate for its lack. I can't think of workaround for the lack of `ngOnDestroy`.

All

* **Angular version:** 2.3.0

* **Browser:** [all ]

 
* **Language:** [all ]

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/pull/13369

**Comment by wardbell** [comment]
Aha!  I've been thinking about adding this for months. And now its done. Thanks for pointing it out.
