### ISSUE TITLE
AoT error when provider specifies `useFactory` with inline function

### ISSUE THREAD

**Issue by mischkl** [angular/angular#13614]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If a provider specifies an inline function/arrow function for `useFactory`, the build fails with the error 'Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function.'

For instance, the following breaks:

```ts
providers: [
    {
      provide: AuthHttp,
      deps: [Http, RequestOptions],
      useFactory: function (http: Http, options: RequestOptions) {
        return new AuthHttp(new AuthConfig(), http, options);
      }
    }
]
```

but changing the notation to ES6 object method shorthand works:

```ts
providers: [
    {
      provide: AuthHttp,
      deps: [Http, RequestOptions],
      useFactory(http: Http, options: RequestOptions) {
        return new AuthHttp(new AuthConfig(), http, options);
      }
    }
]
```

This is completely bizarre IMHO since the semantics in the above examples are identical.

**Expected behavior**

Should work without issue

**Minimal reproduction of the problem with instructions**

Only occurs when compiling using AoT, not reproducible in a plunkr.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7, NPM 3.10.8

* **Angular version:** 2.4.0 (Was not an issue under Angular 2.2.x)

* **Angular-CLI version:** 1.0.0-beta.24

* **Browser:** N/A

 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by DzmitryShylovich** [comment]
`ngc` doesn't execute your code so it should be statically analyzable. Arrow/anonymous functions don't have a name. 

```
useFactory(http: Http, options: RequestOptions) {
        return new AuthHttp(new AuthConfig(), http, options);
}
```
is equal to
```
useFactory: function useFactory(http: Http, options: RequestOptions) {
        return new AuthHttp(new AuthConfig(), http, options);
}
```
this is why it works

**Comment by DzmitryShylovich** [comment]
https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.3xvtag7g9

**Comment by mischkl** [comment]
Interesting..  That explains why it doesn't work. But this is incorrect behavior according to ES6 spec: http://www.2ality.com/2015/09/function-names-es6.html?m=1

I don't know whether the problem lies with tsc or ngc but something isn't right here...

**Comment by mattlewis92** [comment]
Looking at the ES6 compat table, typescript doesn't seem to support them (I think it's `object methods (function)`): https://kangax.github.io/compat-table/es6/#typescript
<img width="770" alt="screen shot 2016-12-22 at 10 44 10" src="https://cloud.githubusercontent.com/assets/6425649/21423207/9af9e1c8-c833-11e6-9faf-4c653e45eafd.png">

Babel does have support for them, so I guess it's possible for typescript to as well. I'd suggest filing an issue with typescript and asking them to support function names of this type.

**Comment by mischkl** [comment]
@mattlewis92 thanks for that, I'll check out the TypeScript issues and let them know about this being a problem in combination with Angular 2.

Another thing worth mentioning, though, is that even if the code is changed to fulfill the AoT requirements, it still chokes on third-party libs that have been pre-compiled with TypeScript. Case in point is https://github.com/auth0/angular2-jwt - I am attempting to use the exported AUTH_PROVIDERS in my providers. If I copy the source `angular2-jwt.ts` into my angular project and fix it so that `useFactory` has a name, everything works great. However, if I compile the source code, copy the resulting `.d.ts` and `.js` into `node_modules/angular2-jwt`, and import from there, it chokes with the same warning again, even though I supposedly fixed it!

The weirdest thing is that this only started happening once I upgraded to angular-cli beta.24 and angular v2.4.0. Using angular-cli beta.22 and angular v2.2.3 there was no error.

**Comment by mattlewis92** [comment]
That's really odd, it does seem that there have been a few internal changes that have inadvertently been breaking in 2.4

**Comment by kemsky** [comment]
Any code that is referenced and uses static initialization is broken:
```ts
class Test {
     private static field = new Value(); // Error encountered resolving symbol values statically.
}
```

However, referencing using `Test['field']` does not trigger error and app works (but may broke if mangled).

I'm loosing so much time with this stuff.

**Comment by jpduckwo** [comment]
I'm running into this problem. For those using webpack AOT compilation the error message is the generic:

```Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'```

Updating useFactory as above fixed it for me

**Comment by trotyl** [comment]
Should have been fixed by #18905?

**Comment by WillHall** [comment]
I was stuck on this issue for a while, so I figured I would just share what I did to get around it.

Functions are not supported in decorators error in loadChildren solution.

Normal Way:
```
import { RouterModule, Routes } from '@angular/router';

export const routes: Routes = [
  {
    path: 'mypage',
    loadChildren: () => import('@whatever/mypage').then(m => m.MyPageModule),
  }
]
```

Becomes:
```
import { LoadChildrenCallback, RouterModule, Routes } from '@angular/router';

export const loadMyPage: LoadChildrenCallback = () => import('@whatever/mypage').then(m => m.MyPageModule);

export const routes: Routes = [
  {
    path: 'mypage',
    loadChildren: loadMyPage,
  }
]
```

HTH googlers like me.

**Comment by JoostK** [comment]
Support for this was added in #18390. Moreover, the Ivy compiler works a bit differently so that this is no longer an issue.
