### ISSUE TITLE
Feature request: Complete missing Javascript documentation

### ISSUE THREAD

**Issue by tilwinjoy** [angular/angular#13611]
Hello,

It's been a long time and still there is no proper documentation for Angular2 in JavaScript. Considering the improvements to JS in ES6 and rest planned in future, not everyone would want to learn TypeScript/CoffeeScript/Dart etc.

Is there any plans/roadmap to complete the documentation for JavaScript?

**Comment by DzmitryShylovich** [comment]
Pls re-open it on https://github.com/angular/angular.io

**Comment by tilwinjoy** [comment]
@DzmitryShylovich  according to https://github.com/angular/angular.io/issues/2989#issuecomment-326311807 now this should be reported here. Please re-open

**Comment by khuongduybui** [comment]
You should probably rename "complete missing JS docs" to "*provide* missing JS docs"
