### ISSUE TITLE
dynamic reactive form in Angular 2 lazy loading with Webpack

### ISSUE THREAD

**Issue by JeffreyChan** [angular/angular#13610]
I don't know it's a issue of angular 2 or angular2-router-loader

**Current behavior**

dynamic reactive form can't work in sub lazy load route.
here is error message:
![image](https://cloud.githubusercontent.com/assets/5321225/21392271/14a6bdb2-c7ca-11e6-9553-704dbef963de.png)

this component will work in root route, but not in sub route.

**Expected behavior**

I think dynamic reactive form should work in lazy loading route, but it doesn't. how odd !

**Minimal reproduction of the problem with instructions**

get [source code](https://github.com/JeffreyChan/angluar2-best-practice) 
first step: 

> npm i

second step:

> npm run start

finally step:

> click "Form List"

you will see the error message in console.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4

* **Browser:** Chrome

 
* **Language:**  TypeScript 2.1.4

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by DzmitryShylovich** [comment]
> I don't know it's a issue of angular 2 or angular2-router-loader

pls add a small repro in plunkr

**Comment by JeffreyChan** [comment]
sorry, I don't know plunkr works, my github repro not okay?

**Comment by DzmitryShylovich** [comment]
We need to locate the issue. And plunkr is ideal for this. If u can reproduce in plunkr - the issue with angular, if u can't - the issue with router lader.

U can use https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 as a starting point.

**Comment by JeffreyChan** [comment]
I'll give it try. but no dynamic reactive form in angular route loader works fine.

**Comment by JeffreyChan** [comment]
hi Dzmitry
I just check the author of angular2-route-lader
![image](https://cloud.githubusercontent.com/assets/5321225/21395309/f96e3798-c7d6-11e6-8aea-b1e74eb05936.png)

Can I say it is a issue of angular2?

**Comment by JeffreyChan** [comment]
hi Dzmity
I am pretty sure it's a issue of angular2. I just add the dynamic reactive form of my code in [angular2byexamle](https://github.com/chandermani/angular2byexample)
it runs by gulp, but still can't work for dynamic reactive form.

Would you check it now?

**Comment by clydin** [comment]
Your lazy loaded module doesn't know about your address component.

Also, "address" is a pre existing HTML element.  It's good practice to prefix your component selectors to avoid naming collisions.

**Comment by JeffreyChan** [comment]
You mean address component should be define in customer component? like detective? or named address component other selector? let me try first.

**Comment by JeffreyChan** [comment]
hi clydin , you are right. I have fixed it. sorry to trouble this.

**Comment by JeffreyChan** [comment]
I want to ask, angular 2 could provide nice error tip?

**Comment by clydin** [comment]
It would have if the selector wasn't the same as an existing HTML element.

**Comment by JeffreyChan** [comment]
I won't agree with that. even I change address component selector to inner-address, the error msg is still same
BTW would you close this issue. I am sorry to make a mistake, take you guys time.
