### ISSUE TITLE
Angular - router - outlets - urls are not friendly and shouldn't show the outlet id (it is not a good behavior)

### ISSUE THREAD

**Issue by danicomas** [angular/angular#13616]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
http://localhost:8080/#/users/danicomas/images doesn't work now
http://localhost:8080/#/users/danicomas/(user:images) it works

**Expected behavior**
http://localhost:8080/#/users/danicomas/images (remove parentesis and outlet name, this not make sense, the url is not friendly for the users. It is not a good approach)

**Minimal reproduction of the problem with instructions**
```
const appRoutes: Routes = [
  { path: '', redirectTo: 'users', pathMatch: 'full' },
  { path: 'users', component: UsersComponent },
  { path: 'users/:id', component: UserComponent, children: [
      { path: 'images', component: UserImagesComponent, outlet: 'user' },
  ]}
];

@Component({
	template: `
	<h1>{{id}}</h1>
	<nav>
      <ul class="nav nav-tabs">
        <li><a [routerLink]="[ '/users/' + id ]">About Me</a></li>
        <li><a [routerLink]="[ '/users/' + id, {outlets: {'user': ['images']}} ]">Images</a></li>
	  </ul>
	  </nav>
	<router-outlet name='user'></router-outlet>
  `
})
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.0

* **Browser:** [Chrome 55]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by robwormald** [comment]
This is the pattern we've implemented, and if you want the URL to be the linkable source of truth, you're going to have to describe UI state in the URL somehow.

As any change to this behavior would be a breaking change to Angular's API, it's unlikely we'll change this pattern. You may, however, implement your own strategy for this - https://github.com/angular/angular/blob/master/modules/%40angular/router/src/url_tree.ts#L234-L275

**Comment by danicomas** [comment]
@robwormald Yesterday I found the new implementation of UI-Router and seems that is the correct way
https://github.com/ui-router/quickstart-ng2/blob/b87590eb1bcc8334a9f3b8d7e899109c77b067fa/src/app.component.ts

I will try it.

**Comment by danicomas** [comment]
In Angular router you configure the outlets in the routes array. I don't understand why you need to pass in the url too. It could work loading the components into the outlet referencing in that array. @vsavkin

**Comment by marcelogodois** [comment]
Hi, but if you do /users/userId/images the outlet will be shown in the URL after. Right?! Is there a way to get rid of that?

**Comment by mlc-mlapis** [comment]
@marcelogodois ... use `skipLocationChange` then.

https://angular.io/api/router/NavigationExtras

**Comment by marcelogodois** [comment]
Thank you for your help @mlc-mlapis !It works for:

`this.router.navigate([{outlets: {centro: params['page']}}],
                             {relativeTo: this.route, skipLocationChange: true })`

but not for:

`<li><a [routerLink]="['main','course',{ outlets: { centro: ['course'] }, skipLocationChange: true }]" [routerLinkActive]="['active']">COURSE</a></li>`
