### ISSUE TITLE
Missing documentation for ViewChildren and ContentChild decorators on angular.io

### ISSUE THREAD

**Issue by ti1024** [angular/angular#13625]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

This was originally reported in angular.io repository (angular/angular.io#2636), but it was closed and redirected to this repository.

**Current behavior**
The following pages are empty:

* https://angular.io/docs/ts/latest/api/core/index/ViewChildren-decorator.html
* https://angular.io/docs/ts/latest/api/core/index/ContentChild-decorator.html
* https://angular.io/docs/js/latest/api/core/index/ViewChildren-decorator.html
* https://angular.io/docs/js/latest/api/core/index/ContentChild-decorator.html

**Expected behavior**
These pages should show the API documentation.

**Minimal reproduction of the problem with instructions**
Open the pages above in a browser.

**What is the motivation / use case for changing the behavior?**
Documentation is important.

**Please tell us about your environment:**

* **Angular version:** n/a
* **Browser:** Chrome 55
* **Language:** all

**Comment by WilliamKoza** [comment]
You must post this issue on GH [https://github.com/angular/angular.io](https://github.com/angular/angular.io) but it's true

**Comment by DzmitryShylovich** [comment]
@WilliamKoza 
> This was originally reported in angular.io repository (angular/angular.io#2636), but it was closed and redirected to this repository.

**Comment by WilliamKoza** [comment]
Thx @DzmitryShylovich !

**Comment by vicb** [comment]
Pb is that the docs are not on the right classes, should be easy to fix by looking at working docs (`Component` or `Directive`)

**Comment by ti1024** [comment]
Thank you for looking into this. I will try to fix it.

**Comment by ti1024** [comment]
I noticed the documentation of the Type decorator was also almost empty:

* https://angular.io/docs/ts/latest/api/core/index/Type-decorator.html
* https://angular.io/docs/js/latest/api/core/index/Type-decorator.html

The documentation exists in https://github.com/angular/angular/blob/master/modules/%40angular/core/src/type.ts. This might be a similar issue to the current one, but I am not sure how to fix it.
