### ISSUE TITLE
IE Issue using router.navigate

### ISSUE THREAD

**Issue by snehagokarn** [angular/angular#13628]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
**Only in IE**
I have a list items page with all the items on it and an update button for each item, clicking on which I route it to the update page of the item, after save I use router.navigate([constructed route]) and take it back to the list items page.
Clicking on the update button of the same item changes the url(showing the appropriate url for the item I intend to edit) but it does not load the page. 
Only way I can do this if I go to another page and come back.

**Expected behavior**
No matter how many times or where ever (coponent or template)  I call the url, the relevant page must be displayed,  

**Minimal reproduction of the problem with instructions**
1. Create 2 components
2. Anchor tag in Component 1 with href to component 2 route
3. Now using router.navigate go back to Component 1.
4. now click on the link again in component 1
5. This does not take you to component 2.

**What is the motivation / use case for changing the behavior?**
Consistency and support for IE

**Please tell us about your environment:**
Visual Studio code
IIS
Browser: IE 10

**Work around**
For now I've used window.location.href to redirect 

* **Angular version:** 2.0.X
2.4.1

* **Browser:** 
checked on IE 10  
* **Language:** 
all

* **Node (for AoT issues):** `node --version` =   
latest

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr.

**Comment by DzmitryShylovich** [comment]
@snehagokarn did u fix it?

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have any actionable reproduce scenario.

**Comment by satvik1986** [comment]
Angular 5
 this.router.navigate(['Home']); not working in Internet explorer 9, 10, 11
