### ISSUE TITLE
Angular 2 and IIS WebApplication with virtual directory cannot resolve the paths

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#13620]
For testing purpose, I have created a VirtualDirectory on IIS(inetmgr) on my local PC and later converted it into IIS Web Application. The web application's root is: http://localhost/Ebr/ When deployed and ran the application, I get the following error in the browser:

![image](https://cloud.githubusercontent.com/assets/12258728/21405689/7eead74c-c795-11e6-8865-176a90082acf.png)

```
import { Component } from "@angular/core";
import { Router } from "@angular/router";

@Component({
    moduleId: module.id,
    selector: "my-app",
    templateUrl: "app.component.html"
})
    //Test
export class AppComponent {
    constructor(private router: Router) { }
}
```
I have used moduleId concept but still URL's are not resolved. Since all my files are under virtual directory Ebr and when I run the application it doesn't work until I put Ebr after localhost of all the urls, how to fix this issue ?

**Comment by DzmitryShylovich** [comment]
I think u need to provide your own `UrlResolver` in this case

**Comment by vijender1256** [comment]
@DzmitryShylovich how to provide own UrlResolver ? any sample please

**Comment by DzmitryShylovich** [comment]
```
platformBrowserDynamic().bootstrapModule(AppModule, {providers:   
  [
    { provide: UrlResolver, useClass: CustomUrlResolver }
  ]});
```

**Comment by vijender1256** [comment]
@DzmitryShylovich I am trying to resolve the image URL's:
**app.component.ts code:**

```
import { Component } from "@angular/core";
import { Router } from "@angular/router";
import { UrlResolver } from '@angular/compiler';

@Component({
    moduleId: module.id,
    selector: "my-app",
    templateUrl: "app.component.html"
})
export class AppComponent {
    constructor(private urlResolver: UrlResolver) { }

    public resolvePath(path) {
        return this.urlResolver.resolve(module.id, path);
    }
}
```
**app.module.ts code**
```
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { AppComponent } from "./app.component";
import { routing, appRoutingProviders } from "./app.routing";
import { Routes, RouterModule } from "@angular/router";
import { CashierRiskProfileModule } from "./cashierriskprofile/cashierriskprofile.module";
import { ExceptionDashboardModule } from "./exceptiondashboard/exceptiondashboard.module";
import { ReportModule } from "./reports/report.module";
import { SharedModule } from "./shared/shared.module";
import { UrlResolver } from '@angular/compiler';

const routes: Routes = [
];

@NgModule({
    imports: [
        BrowserModule,
        routing,
        CashierRiskProfileModule,
        ExceptionDashboardModule,
        ReportModule,
        SharedModule.forRoot(),
        RouterModule.forRoot(routes, { useHash: true })
    ],
    declarations: [
        AppComponent
    ],
    providers: [
        appRoutingProviders, UrlResolver
    ],
    bootstrap: [AppComponent]
})
export class AppModule {
}
```
I am providing UrlResolver, but the constructor injection of UrlResolver is causing error:

![image](https://cloud.githubusercontent.com/assets/12258728/21437271/ead3a586-c850-11e6-8e09-0cf1d49e1923.png)

**HTML code**
```
 <img [src]="resolvePath('PublixLogo.jpg')" alt="Publix" width="50" height="50">```

can any idea on why am I getting error

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by plgregoire** [comment]
@vijender1256, we are in the same situation as you were:  "No provider for Token Application Packages Root URL". Did you find a solution?
