### ISSUE TITLE
Make ng-content's select attribute accept proper/multiple CSS selectors.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [angular/angular#13621]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Not to compare apples to oranges, but ng-content's select attribute is very limiting. Not all CSS selectors work and this is something that works on polymer.

This doesn't work:
`<ng-content select="custom-action[type^='icon'][group='1']"></ng-content>`

It doesn't appear that you can chain multiple selectors, and these don't work: "^=, *=, $=, |=, ~="

**Expected behavior**

The ng-content's select attribute should just work like in polymer, and it should accept all proper CSS selectors.

**Minimal reproduction of the problem with instructions**

The only "work around" this issue is to define multiple "select" attributes, but even this approach would not accept "^=, *=, $=, |=, ~=".
`<ng-content select="custom-action" select="[type=icon]" select="[group=1]"></ng-content>`

**What is the motivation / use case for changing the behavior?**

This is how easy it is to do the same in Polymer, Agular's approach seems to come out a bit short compared to polymer's way:
`<content id="ca_content_group1"
         select="tw-custom-action[type^='icon'][group='1']">
</content>`
**Please tell us about your environment:**

- OSX-Sierra
- Intellij 2016.3.1
- Dart SDK 1.2.1

* **Angular version:** 2.0.X

Angular 2.2.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chromium Version 45.0.2454.104 (64-bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Dart SDK 1.2.1
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Related to https://github.com/angular/angular/issues/7278

**Comment by RivkaKu** [comment]
I have some similar problem
I need to display in the ng-content all content that found in an <a> element
I tryed : <ng-content select="a *"></ng-content> but nothing display
It will be nice if all css selectors could be value of the select property

**Comment by tonosama-atlacatl** [comment]
Any updates on this, since we're on the midst of closing 2019?
