### ISSUE TITLE
Html Anchor tag in Angular 2 sourced from outside app

### ISSUE THREAD

**Issue by gaurav2887** [angular/angular#13622]
I am building an Angular 2 app and few of the HTML pages are coming from different App (not an angular app). Those HTML pages have `<a href="#Employee">` anchor tags to navigate to different location on the same page.

Tried both HashLocationStrategy and PathLocationStrategy but app is considering that href as link and trying to open new route instead of behaving like an Anchor.  Please let me know if you have solution to this.

**Comment by DzmitryShylovich** [comment]
It's called fragments https://angular.io/docs/ts/latest/guide/router.html#!#fragment

**Comment by gaurav2887** [comment]
@DzmitryShylovich - Fragment is an attribute for links inside the Angular 2 app. As I said, these links are coming from outside non angular 2 app and they cannot add fragment attribute to link. I do not want to traverse entire HTML document coming from outside and insert fragment attribute. Any workaround?

**Comment by DzmitryShylovich** [comment]
@gaurav2887 could u pls add a small repro in punkr of what are u trying to accomplish?

**Comment by mlakmal** [comment]
You could use a global click handler on HTML body and handle routing internally. Same process is used in AngularJS framework. We reused same code in our Angular app that contains external HTML fragments.

**Comment by DzmitryShylovich** [comment]
@mlakmal pls add a plunkr with a small demo otherwise it's not actionable

**Comment by mlakmal** [comment]
below is the code we have on main app component.

`
  @HostListener('click', ['$event'])
  private handleAnchorClicks(event: any) {
    let elm = $(event.target);

    while (ElementHelper.nodeName(elm[0]) !== 'a') {
      // ignore rewriting if no A tag (reached root element, or no parent - removed from document)
      //tslint:disable:no-conditional-assignment
      if (elm[0] === (this._viewContainerRef.element.nativeElement) || !(elm = elm.parent())[0]) {
        break;
      }
      //tslint:enable:no-conditional-assignment
    }

    if (ElementHelper.nodeName(elm[0]) !== 'a' ||
      event.ctrlKey || event.metaKey || event.shiftKey || event.which === 2 || event.button === 2) {
      return true;
    }

    let absHref = elm.prop('href') || elm.attr('href') || elm.attr('xlink:href');

    if ((typeof absHref === 'object') && absHref.toString() === '[object SVGAnimatedString]') {
      // SVGAnimatedString.animVal should be identical to SVGAnimatedString.baseVal, unless during
      // an animation.
      absHref = this._urlHelper.urlResolve(absHref.animVal).href;
    }

    if (absHref && !elm.attr('target') && this._navigationHelper.isAppUrl(absHref)) {
      this._navigationHelper.navigateTo(absHref);
      event.preventDefault();
      return false;
    }

    return true;
  }
`

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
