### ISSUE TITLE
Angular 2 refresh route broken when deploy into war on wildfly with specific context path 

### ISSUE THREAD

**Issue by fplini** [angular/angular#13633]
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request

I'm developing an angular 2 app. So essentialy, if I run the app with "ng serve" all works fine, if I refresh the page (for example http://localhost:4200/home) it works fine and angular recognizes the right route. The problem occurs when I build the app in a war and deploy it on wildfly with a different context path (ex. /myapp). At this point the routing navigation works fine but if I refresh the page I receive a "Not found error". My base href on index.html is <base href="."> I also tried with <base href="./myapp"> but in this case angular try to look for the resources under http://myhost/ and not under http://myhost/myapp/
Anyone have any idea on how to fix it?

**What is the motivation / use case for changing the behavior?**
I need to deploy the war on wildfly, the war contains only the angular 2 frontend app. I'm deployin it under a specific wildfly context path. 

**Please tell us about your environment:**
Windows 7, IntelliJ, Wildfly 9

* **Angular version:** 2.4.X

* **Browser:** [all]
 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by DzmitryShylovich** [comment]
> [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by MatthiasCruse** [comment]
You could enable routes containing the hash "#" sign in URLs, this can be achieved via "useHash: true" in your app routing ts

**Comment by anabulsi** [comment]
This is not Angular issue. You need to configure your backend to serve index.html no matter what URL is being requested. If this is too complicated, then configure your router to use hash sign

**Comment by fplini** [comment]
Resolved adding hash strategy
