### ISSUE TITLE
angular 2 doesn't support rxjs do operator

### ISSUE THREAD

**Issue by JeffreyChan** [angular/angular#13639]
Here is code:

` this.items = this.term.valueChanges
                 .debounceTime(400)
                 .do(term => console.log(term));`

**Current behavior**

as do operator, I want see value in console, but it doesn't.
**Expected behavior**

I want rxjs do operator works
**Minimal reproduction of the problem with instructions**

http://embed.plnkr.co/SIltBL/

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by klinki** [comment]
You forgot to import do operator... Add line `import 'rxjs/add/operator/do';` to main.ts and it will work.

**Comment by JeffreyChan** [comment]
hi klinki
I forget to subscribe

Hi Dzmitry
please close the issue.

**Comment by DzmitryShylovich** [comment]
@JeffreyChan u can close it yourself :)
