### ISSUE TITLE
Local Component Css style is not working in Dynamic HTML Content

### ISSUE THREAD

**Issue by gargtushar** [angular/angular#13631]
Hello Sir,

Please review my Component.html code given below:
_________________________________________________________________________________
Footer.component.html
<footer class="page-footer">
  <div class = " row">       
     <div class = "col-md-3 link" [innerHTML] ="footer.content"></div> 
     <div class = "col-md-3 links">
         <ul class="footer links">
            <li class="nav item"><a href="#">Privacy and Cookie Policy</a></li>
            <li class="nav item"><a href="#">Search Terms</a></li>
            <li class="nav item"><a href="#">Advanced Search</a></li>
            <li class="nav item"><a href="#">Orders and Returns</a></li><li class="nav item"><a href="{{store url=">About us</a></li>
            <li class="nav item"><a href="#">Contact Us</a></li> 
         </ul>
     </div> 
     <div class="content col-md-5">
        <form class="form" novalidate="novalidate" action="">             
             <label class="label" for="newsletter"><span>Sign Up for Our Newsletter:</span></label>
             <div class="control col-md-12">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                 <input class = "Subscribe" name="email" type="email" id="newsletter" placeholder="Enter your email address" data-validate="{required:true, 'validate-email':true}">
                 <button class="btn btn-primary Subscribe-btn" title="Subscribe" type="submit">
                       <span>Subscribe</span>
                  </button>
             </div>
        </form>
     </div>
  </div>  
</footer>
<small class="copyright col-md-12">
      <span>Copyright © 2016 Magento. All rights reserved.</span>
</small>
________________________________________________________________________________
Footer.component.css
.copyright {
    background-color: #8f8f8f;
    color: #fff;
    display: block;
    padding: 10px;
    text-align: center;
}
small, .small {
    font-size: 12px;
}
.content{
  float:right;
}
.Subscribe{
  display:table-cell;
  border-radius:0px; 
  height:36px;
  width: 66%;
  margin-right: -4px;
  border: 1px solid #c2c2c2;
  padding-left: 33px;
}

.control .fa-envelope {
    content: "\f0e0";
    position: absolute;
    padding-top: 10px;
    color: #c2c2c2;
    padding-left: 10px;
}
.Subscribe-btn{
    display: table-cell;
    border-radius:0px;
    height:36px;
    margin-left: 0px;
}
.form{
    padding:0px;
}
.control{
    margin-top:0px;
    display: table-cell;
}
.label{
    display:none;
}
.page-footer{
    background: #f4f4f4;
}
.links ul li >a {
    color: #575757 !important;
    font-size: 15px;
    text-decoration: none;
    padding-bottom: 10px;
}
.footer .item a {
    color: #575757;
}
_________________________________________________________________________________
Footer.component.ts
import { Component, OnInit} from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { FooterService } from './footer.service';
import { Http, Response, Headers,RequestOptions } from '@angular/http';
import { Footer } from './footer';
@Component({
  moduleId: module.id,
  selector: 'footer-block',
  templateUrl: 'footer.component.html',
  styles: [
      `.footer .item a {
    color: #575757;
}`
  ],
  styleUrls: ['footer.component.css']     
})
export class FooterComponent implements OnInit { 
    constructor(private footerService: FooterService){}
    name = "Footer";
    footer = Footer;
      ngOnInit(): void {
          //this.name = this.footerService.getFooter();
         this.footerService.getFooter().subscribe(
             (res:Response) =>{ this.footer = res.json();},
             (err :Response) => { console.log(err); } );
     }
     
 }
_________________________________________________________________________________
Dynamic Html coming from server :
<ul class="footer links">
    <li class="nav item"><a href="{{store url=">About us</a></li>
    <li class="nav item"><a href="{{store url=">Customer Service</a></li>
</ul>
_________________________________________________________________________________
In the <div class = "col-md-3 link" [innerHTML] ="footer.content"></div>  here I embedded the the dynamic Html content which is getting called by http.get request from server. 
Here in the dynamic Html, I try to apply the following CSS as given in my footer.component.css
.footer .item a {
    color: #575757;
}
but it is not working,
but the css for other divs and html elements defined in the footer.component.css are working fine.

Note: When the wrote the css for "dynamic html content" into style.css file located in my root Directory, then it is working on dynamic content.

I am unable to find the issue that why the css defined for Dynamic html content in the footer.component.css is not working. I hope you will provide the right solution for this.

Thank you 
Tushar Garg

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by DzmitryShylovich** [comment]
@gargtushar can u pls close this one? I believe it was resolved in the gitter room.

**Comment by gargtushar** [comment]
Sure,
