### ISSUE TITLE
*.ngfactory files are replaced by *.ngsummary.json files with Typescript 2.1+ when running ngc

### ISSUE THREAD

**Issue by blacksonic** [angular/angular#13632]
**I'm submitting a bug report**

**Current behavior**
Using Typescript 2.0.10 the *.ngfactory.ts files are created for modules and components. When upgrading to newest 2.1+ Typescript only *.ngsummary.json files are created instead of the factories making it unable to compile the application.

**Expected behavior**
Still generate ngfactory files besides ngsummary files.

**Minimal reproduction of the problem with instructions**
[In my repository](https://github.com/blacksonic/angular2-aot-webpack) changing Typescript to 2.1.4 and Awesome Typescript Loader to 3.0.0-beta.17 produces the aforementioned behavior.

**What is the motivation / use case for changing the behavior?**
Still be able to generate AOT applications with newest Typescript

**Please tell us about your environment:**
Ubuntu 16.04

**Angular version:** 2.4.1

**Browser:** all
 
**Language:** TypeScript 2.1.4

**Node (for AoT issues):** `node --version` =   6.7.0

**Comment by mattlewis92** [comment]
AFAIK angular isn't yet compatible with typescript 2.1 due to typescript API changes, you'll need to wait for this to land: https://github.com/angular/angular/pull/13294

**Comment by pkozlowski-opensource** [comment]
See #13715
