### ISSUE TITLE
Router: Force rerun Resolve without route changes

### ISSUE THREAD

**Issue by klinki** [angular/angular#13638]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**What is the motivation / use case for changing the behavior?**
It would be nice if it was possible to force `Resolve` to resolve data again.
Use case: user modifies entity which is used in multiple components and it is loaded using `Resolve` class. It would be nice to run `Resolve` again to get new version of entity into components.

**Comment by mattdistefano** [comment]
Alternatively/additionally, being able to `.next()` new values into the route data would be handy. Same basic use case, but for scenarios where the updated data is already available and only needs to be propagated. I believe we can already cast the route data back to the underlying `BehaviorSubject` but that feels hacky.

**Comment by jasonaden** [comment]
You can now use `onSameUrlNavigation` https://angular.io/api/router/Router#onSameUrlNavigation
