### ISSUE TITLE
Changing a property of parent component inside lifecycle hook causes error

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#13643]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When child component changes property of parent component inside a lifecycle hook function, accessing the property using local variable causes `Expression has changed after it was checked` error.

**Expected behavior**
No error should be thrown. Changing property of parent component inside lifecycle hook function should work as if the function was called in response to an event (like button click).

**Minimal reproduction of the problem with instructions**
This plunker should clarify what I mean: https://plnkr.co/edit/Lf7tZ20N9rl7UFmP1Dml
Not that calling update() in response to click works fine.

**What is the motivation / use case for changing the behavior?**
The behavior should be consistent. Change can be made in child component, but not from lifecycle hook - why?

* **Angular version:** 2.4.1

**Comment by DzmitryShylovich** [comment]
http://stackoverflow.com/questions/34364880/expression-has-changed-after-it-was-checked/34364881#34364881 ...

**Comment by DzmitryShylovich** [comment]
You need to trigger another cycle of change detection https://plnkr.co/edit/mrgl0L7IV6OaNWLI5yNk?p=preview
Works as intended.

**Comment by dawidgarus** [comment]
Sadly, this cannot be done with OnDestroy hook:
https://plnkr.co/edit/AHHLgKtTYZ8hmbt4qC0m?p=preview
and that what really interests me.

**Comment by matsko** [comment]
This works as planned. The idea is that change detection will always run once from top to bottom. If you do want to modify the parent and have that update via change detection, wrap the changes to the parent inside of a promise:

```ts
ngOnInit() {
  Promise.resolve(() => {
     parent.doStuff = true;
  });
}
```
