### ISSUE TITLE
Returning `false` on CanDeactivate implementation should not influence browser history

### ISSUE THREAD

**Issue by saverett** [angular/angular#13647]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Returning `false` on CanDeactivate implementation influences browser history.
Seems to be leftover from #10321 and #12825

**Expected behavior**
Returning `false` on CanDeactivate implementation does not influence browser history.

**Minimal reproduction of the problem with instructions**
Present in Angular Routing Demo plnkr:
https://angular.io/resources/live-examples/router/ts/eplnkr.html

*STEPS TO REPRODUCE*:

1. Click "Crisis Center"
2. Click Crisis Center 1, then 2, then 3
3. Edit Crisis Center 3's "Name" in its details
4. Press browser "Back" button, and press "Cancel" when confirm dialog pops up asking if you want to discard changes
5. Press browser "Back" button again, but this time press "OK" when confirm dialog pops up asking if you want to discard changes
6. *RESULT:*
You are taken back to Crisis Center 1 detail view instead of Crisis Center 2. If you press browser "Forward" button twice, you'll notice that both times you are taken to Crisis Center 3 detail view. The Crisis Center 3 detail view has essentially replaced the Crisis Center 2 detail view history entry.

**What is the motivation / use case for changing the behavior?**
I press my browser's "Back" button but then choose to cancel navigation in order to first save pending changes. When I press my browser's "Back" button again, I should navigate to the previous page as if this was the first time I pressed my browser's "Back" button. 

**Please tell us about your environment:**
-Angular demo plnkr (also present in my own ng-cli v1.0.0.24-beta environment)
-Windows 10 x64

* **Angular version:** 2.4.1, Router 3.4.1

* **Browser:** Chrome v55.0.2883.87 m (64-bit) (untested on others)
 
* **Language:** TypeScript 2.0.10

**Comment by DzmitryShylovich** [comment]
Pls add a small repro

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/13586?

**Comment by saverett** [comment]
Yes, looks like a duplicate of #13586. Sorry, I searched open issues but must've missed that one.
