### ISSUE TITLE
Angular2 doesn't seem to send cookies even though the withCredentials header attribute is still set

### ISSUE THREAD

**Issue by NoMercy235** [angular/angular#13640]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am submitting a login request on a Pyramid server which authenticates the user and, if everything's all right, extends the header with an auth_tkt cookie (it returns the 'Set-Cookie'). I can see the cookie in the chrome console and it's set in the browser. Then, I send a GET request on a resource like this:
```
protected get<T>(url: string): Observable<T> {
   let options = new RequestOptions();
   options.withCredentials = true;

    return this._http.get(url).map((response: Response, options) => <T>response.json())
        .do(data => console.log(data))
        .catch(this.handleError);
}
```
The request does not include the cookie I just received a moment ago and I am getting a 403 Forbidden.

**Expected behavior**

The withCredentials attribute should include the cookies present in browser on every request.

**Minimal reproduction of the problem with instructions**

I have tried to reproduce the issue in a plunker, but you need a server that can authenticate users and send a cookie based token afterwards.
http://plnkr.co/edit/gGXFvQftkxg48HZXLpA1?p=preview

Step 1: make a POST (in my case, login) to the server and get your cookie token. 
Step 2: make a GET(in my case, getMe) to the server and check the network request to see if the cookie was attached to the request

**What is the motivation / use case for changing the behavior?**

This should be needed for any backend which makes use of cookie based token authentication.

**Please tell us about your environment:**

OS: Windows 10,
IDE: Visual Code for AngularJS 2 (version 2.0.0) and Pycharm for Pyramid (version 1.7.3)
Package manager: npm and pip

* **Angular version:** 2.0.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  6.9.1

**Comment by DzmitryShylovich** [comment]
Angular doesn't do anything with cookies. It's browser responsibility.

Can u send the same request using plain hxr?

**Comment by SirMosh** [comment]
![after login](https://cloud.githubusercontent.com/assets/10923419/21430691/d6931afe-c86c-11e6-94da-cf9d30d1a516.png)
![cookies](https://cloud.githubusercontent.com/assets/10923419/21430689/d6927e64-c86c-11e6-9ce3-feaa78a8c527.png)
![on login](https://cloud.githubusercontent.com/assets/10923419/21430690/d69294f8-c86c-11e6-8a26-92210dd766ff.png)

**Comment by SirMosh** [comment]
Fixed: the problem was that we were using withCredentials attribute only on the login request, without using on the others. Thanks a lot.

**Comment by DzmitryShylovich** [comment]
could u close the issue pls? thx

**Comment by NoMercy235** [comment]
Done. Thank you for your time. I placed the withCredentials attribute in the .map function of the returned observable. My bad. :)

**Comment by jollysean** [comment]
I am facing a similar issue with ionic 3 and laravel.  Server is sending the cookies and browser is storing it as well. But cookies are not not sent in subsequent request. How did you resolve this?

**Comment by NoMercy235** [comment]
Hello @jollysean! My problem was that I was using the `options` config object on the wrong method (`map` instead of `get`).

Initial call:
`return this._http.get(url).map((response: Response, options) => <T>response.json())`
Good call:
`return this._http.get(url, options).map((response: Response) => <T>response.json())`

The `options` object was the one that had the `withCredentials` property set to `true`.

**Comment by Hanzofm** [comment]
Hi, how did you solve problems with CORS and cookie session?

**Comment by ssidevos** [comment]
Hi any update on solving the CORS and cookie issue. For the frst time, when the backend send response, cookie is there. But any subsequent request from client is not containing that cookie. How can i solve this issue?

**Comment by malixsys** [comment]
use
```
http.get<YourModel>(url, {withCredentials: true}) .pipe(...)
```

**Comment by camicase82** [comment]
Hi, im having the same issue but I think it migth be related to the server. First I had a problem login in, and had to add a proxy config to solve a problem of a parameter not being set in the request, and now, that I try to call a second endpoint, the cookie is not there, any ideas?


just in case this is my function:

```
public getReport(usrName, usrPass, groupId) {
    let loginInfo = 'login=' + usrName + '&password=' + usrPass

    let header= new Headers();
    header.append('Content-Type', 'text/plain;charset=UTF-8');
  
    let options = { withCredentials: true, headers: header };
    
    this.http.post( '/login', 'login=' + usrName + '&password=' + usrPass, {withCredentials: true}).toPromise()
      .then((response) => {
        //en caso que la llamada sea exitosa llamamos al siguiente servicio
        console.log(response);
        return this.http.get('rest/devices/jtzzp2mf/all', {withCredentials: true}).toPromise();
      })
      .then((response)=>{
        console.log(response);
      })
      .catch((error) => {
        console.error(error);
      });
  }
```

**Comment by pradeepsrawat029** [comment]
hey developer i am using current version 7.2 in angluar . my problem is http interceptor not send Cookie.
can any one enplane. 


`'x-token':"kyODNgn62jDK",`
`'content-type':"application/json",`
`'Access-Control-Allow-Origin':'*',`
`'x-client-date':`${+new Date()}`,`
`'Cookie':'any',`

show error in console
![error](https://user-images.githubusercontent.com/22400960/51422394-fab92d80-1bd3-11e9-88c8-83f84ea0f831.png)

**Comment by blixenkrone** [comment]
It's because `'Cookie'` is an illegal header to set in a browser.
