### ISSUE TITLE
2.4.1 breaks backward compatibility

### ISSUE THREAD

**Issue by cagataycivici** [angular/angular#13641]
Binding a an optional trackBy on ngFor gives;

"Track By must be a function but received undefined".

In previous versions, undefined was simply ignored, many PrimeNG users are having this problem now. Simply ignoring undefined instead of throwing an error should restore backward compatibility. We've thought breaking changes will be in major versions only, not with 2.x.

https://github.com/primefaces/primeng/issues/1652

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/pull/13420#issuecomment-267727477

**Comment by chunghha** [comment]
I have same concern. Just updating angular from 2.4.0 to 2.4.1 causes my app with Clarity failed. Patch update shouldn't be an issue to other 3rd party libraries. 

https://github.com/vmware/clarity/issues/282

**Comment by Toub** [comment]
Not sure if it is the same issue, but I am not able to use anymore the following syntax with v2.4.1:   
```html
<tr *ngFor="let user of users;trackBy:user?._id">
```
```
 trackBy must be a function, but received null
```

trackBy property is mentioned on the Web : http://stackoverflow.com/questions/36322829/how-to-use-track-by-inside-ngfor-angular-2

However, it is not on the official doc where just trackBy:function is documented: https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html

**Comment by DzmitryShylovich** [comment]
> However, it is not on the official doc where just trackBy:function is documented: 

really? http://prntscr.com/dne8kr

**Comment by mlc-mlapis** [comment]
I do not exactly know where this misunderstanding has its origin but it is a bit surprise for me because the fact that trackBy can be only a function is here from the very beginning, including docs.

**Comment by Toub** [comment]
Right, I was using the wrong syntax, probably due to ng1 practices and this stackoverflow response.

**Comment by robwormald** [comment]
@Toub your error is actually exactly what this was designed to catch, because you're using trackBy incorrectly - thus not getting the behavior you would expect. 

That said, I don't think we considered the use case that primefaces has, where the trackBy fn is wired up internally by default.

This is tough, because we're attempting to prevent the majority confusion here (there are a TON of poeple who do `trackBy:foo?.id` which is, and always has been, incorrect. 

We should probably revert this change and push it to 4.0.0 - cc @IgorMinar

**Comment by qdouble** [comment]
keeping a dev warning would be useful even if you don't throw an error until 4.0.0 as I'm sure many may be using it incorrect due to incorrect examples on the internet

**Comment by IgorMinar** [comment]
We have evaluated this issue and decided to partially revert the change.

Starting with 2.4.2 (due tomorrow) we will not throw an error, instead we will just `console.warn` about the incorrect usage.

We will however throw an error in Angular 4.0.0 (due in March).

Sorry about the innocence.

**Comment by asfernandes** [comment]
What is wrong with getting a easier and intuitive thing as track by a property?

**Comment by DzmitryShylovich** [comment]
> a easier and intuitive thing as track by a property

there's no syntax for it :)
