### ISSUE TITLE
UpgradeAdapter: Components displayed using structural directives are not in NgZone

### ISSUE THREAD

**Issue by rarmatei** [angular/angular#13644]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using the upgrade adapter, a downgraded Angular 2 component will be in NgZone, and any events triggered (and patched by NgZone) in this component will be in the zone as well.

However, if any children components (of this parent downgraded component) are enabled sometime after (by a structural directive - *ngIf), they will be outside of the zone. So if there's a button part of this child, anything happening inside its (click) handler will be outside of the zone.

**Expected behavior**

Any child components should be in NgZone when their structural directives enable them.

**Minimal reproduction of the problem with instructions**

Open up the demo:
https://plnkr.co/edit/UIJpjMnyzuWj6S9t9N6T?p=preview

Check on the output screen that the parent is in the zone (it should be).

Press the "show child" button: child component gets created, but is not in the zone (this should be on the output).

Open the console, and click the "LOG zone status" button. The button (click) event handler should output that it's also not in the zone.

EDIT:
Same problem occurs with the static upgrade module:
https://plnkr.co/edit/xbXu0XEUv3RUeSC2dtAK?p=preview

**What is the motivation / use case for changing the behavior?**

This could create problems for applications using the upgrade adapter.

**Please tell us about your environment:**

Windows 7, problem reproducible in Plunkr.

* **Angular version:** 2.0.X

Latest Angular version on npm.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Version 55.0.2883.87 m 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by MonkeyMagiic** [comment]
Adding to to the description: 

Any child component that is created as a side effect of triggering the *ngIf binding to fire is not created in the angular zone.

**Comment by arins** [comment]
i just wrote an issue but found this afterwards. Is it the same bug as #13770

**Comment by davidda** [comment]
Does anyone know a workaround? I'm hoping this gets fixed soon, because it makes *ngIf unusable in my ng1/ng2 mixed app. I will try to resort to [hide] for the time being.

**Comment by rarmatei** [comment]
I checked my Plunkr which is using Angular 2.4.8, and I see the issue has been fixed. Thank you!
