### ISSUE TITLE
Spam in gitter

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#13646]
There's a spammer in gitter room. Can somebody pls ban him? @vicb @chuckjaz @pkozlowski-opensource

**Comment by vicb** [comment]
Who ?

**Comment by DzmitryShylovich** [comment]
@JohnCashmore

**Comment by JohnCashmore** [comment]
Really?

**Comment by JohnCashmore** [comment]
It might be the slack bridge

**Comment by DzmitryShylovich** [comment]
@JohnCashmore https://gitter.im/angular/angular?at=585c0d17c02c1a39599e9e37 slack bridge? :)

**Comment by JohnCashmore** [comment]
Yes this https://sameroom.io/manage something clearly when really weird with it, i've turned it off now, sorry for any problems it caused
