### ISSUE TITLE
Angular2 - ngFor should generate an exception for undefined collections

### ISSUE THREAD

**Issue by DOMZE** [angular/angular#13642]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When a member variable of the class is used in a ngFor, if that member variable is undefined, no exception is generated

**Expected behavior**
An expected behavior would be that it generates an exception.

**Minimal reproduction of the problem with instructions**
See this plinkr: http://plnkr.co/edit/AUCgBm1NLGNRmDMBk1Iq

**What is the motivation / use case for changing the behavior?**
A real for loop with an undefined variable would have thrown an error.

**Please tell us about your environment:**
Windows 7
node: 4.6.0
npm: 3.10.8

* **Angular version:** 2.0.X
Angular: 2.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript: 2.X

**Comment by robwormald** [comment]
This is a on-purpose decision - consider basically anything that's going to arrive async would throw with this proposed idea. NgFor already effectively acts like an NgIf here - if the data isn't defined, it simply doesn't run the loop.
