### ISSUE TITLE
what's the difference between the 4.x version and 2.x version?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [angular/angular#13659]
# what's the difference between the 4.x and 2.x ? 

And, where is the 3.x version?

@vsavkin @vicb @mhegazy

**Comment by janousek** [comment]
http://angularjs.blogspot.cz/2016/12/ok-let-me-explain-its-going-to-be.html

**Comment by vicb** [comment]
- 3.x has been skipped so that we can align the `@angular` packages with the router 
- The 4.x branch will contain (minor) backward compatibility breaks while the 2.x branch will remain backward compatible - most 4.x breaks will actually be `@deprecated` and only changed in the 5.x release.

**Comment by xgqfrms-GitHub** [comment]
Thanks for your reply!
