### ISSUE TITLE
Angular 2.4.0  with clear cache ?

### ISSUE THREAD

**Issue by MrHOY** [angular/angular#13657]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I created app by angular 2.4.0, when I testing on localhost everything work good (it's mean when I change code component, html. etc.. brower change too
But when I upload code to server (I use nginx), everything new not valiable on brower of user,
the user have to clear cache by manually ( on chrome: Ctrl + Shift + Delete -> Clear browsing data) to see what's new, that not good.
I had to try add code to index file but not work.
   ```
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
   <meta http-equiv="Pragma" content="no-cache">
   <meta http-equiv="Expires" content="0">
```

Have any way to clear cache or not save cache with angular ?

Thank you.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by janousek** [comment]
It have nothing to do with angular. Meta tags that you specified says that page should not be cached. But it says nothing about JS, CSS, images, etc.. 
You have to specify cacheability for each document (using HTTP headers). Other possibility is to add some extra URL parameter when you are loading your JS (for example: ../js/angular.js?nocache=RANDOM_NUMBER)
