### ISSUE TITLE
Make lifecycle.registerWith private

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#1366]

**Comment by naomiblack** [comment]
@mlaval can you complete this one in the next day? We need it for the M7 API docs.

**Comment by mlaval** [comment]
It doesn't seem to be possible to make it private without creating other public properties/methods, or without a big refactoring.
To work around that, @petebacondarwin created a `@private` doc annotation and applied it in 97220dd2ba24963b471abde1424f200108c3ec31

**Comment by petebacondarwin** [comment]
Strictly the `@private` annotation was already available, we just updated the dgeni templates to ignore members marked with this annotation. :-)

**Comment by naomiblack** [comment]
@petebacondarwin this seems to still be showing up in the docs, even with the `@private` annotation?

See https://github.com/angular/angular/blob/99fdb9ac419bbb96fc355401f818ac49b297d1ec/modules/angular2/src/core/life_cycle/life_cycle.js#L47

**Comment by petebacondarwin** [comment]
We need to update the Jade templates or Processor along the lines of this commit: https://github.com/angular/angular/commit/e1b0bab9a6b361466ca7d1489ef71a25dce17a81
