### ISSUE TITLE
console.log messages swallowed in ngOnInit

### ISSUE THREAD

**Issue by agatlin** [angular/angular#13664]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

**Current behavior**

I have `console.log` messages placed in the `ngOnInit` routines in various modules, services, and components. The messages from the components display properly but no message from the modules or services appear in the console. 

**Expected behavior**

All `console.log` messages should appear in the console. 

**Minimal reproduction of the problem with instructions**

1. Place `console.log` messages in the `ngOnInit` routines of modules or services. 
2. Open `Chrome Debugger`
3. Launch site.
4. Scratch head and stare in disbelief when the messages do not appear in the console.

**What is the motivation / use case for changing the behavior?**

I need to be able to see what precisely is happening with data that is supposed to be being loaded in the `ngOnInit`. Without access to some logging, I am flying blind. 

**Please tell us about your environment:**

* **OS:** Windows 10
* **Angular version:** 2.2.3
* **Browser:** Version 55.0.2883.87 m (64-bit)
* **Language:** TypeScript 2.1.4
* **Node (for AoT issues):** `node --version` =   7.0.0
* **angular-cli:** 1.0.0-beta.22-1

I am using `angular-cli` and `WebPack` for the build.

**Comment by DzmitryShylovich** [comment]
> but no message from the modules or services appear in the console.

because modules and services don't have `ngOnInit` hook. It's by design. Use `constructor`.

**Comment by agatlin** [comment]
Ok. In the Angular documentation, they make a huge deal about not putting data access logic in the constructor. May I ask why modules and services don't have an ngOnInit hook? What is the design rationale for that? I just want to understand. Thank you!

**Comment by vicb** [comment]
Components are initialized by the framework and it makes sense to have a hook there. There is no "initialization" phase for services nor modules.

**Comment by agatlin** [comment]
Thank you @vicb !
