### ISSUE TITLE
zone.js: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by roroco** [angular/angular#13667]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

console raise `Uncaught RangeError: Maximum call stack size exceeded`
**Expected behavior**

don't raise any errors
**Minimal reproduction of the problem with instructions**

```
git clone https://github.com/angular/quickstart
cd quickstart; npm i; npm start
```

the chrome console raise:
```
Uncaught RangeError: Maximum call stack size exceeded
    at Function.Object.getOwnPropertyDescriptor (zone.js:1319)
    at HTMLBodyElement.desc.get (zone.js:911)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
    at HTMLBodyElement.desc.get (zone.js:913)
```
**What is the motivation / use case for changing the behavior?**

I getting started angular2
**Please tell us about your environment:**

```
roroco@roroco ~/Dropbox/jss/ro-js $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
roroco@roroco ~/Dropbox/jss/ro-js $ google-chrome -version
Google Chrome 55.0.2883.87 
```
* **Angular version:** 2.0.X

see [demo](https://github.com/angular/quickstart)
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =   
```
roroco@roroco ~/Dropbox/jss/ro-js $ node -v
v7.3.0
```

**Comment by Toxicable** [comment]
Please fill out the issue template

**Comment by roroco** [comment]
@Toxicable I update my issue

**Comment by DzmitryShylovich** [comment]
@roroco pls add a repro in plunkr

**Comment by roroco** [comment]
@DzmitryShylovich  it's hard to repro in plunkr since I must copy paste all js in node_modules, can you `git clone https://github.com/angular/quickstart` in linux vbox and reproduce it? it's your official angular demo

**Comment by DzmitryShylovich** [comment]
@roroco if u can't reproduce it in plunkr hen re-open on https://github.com/angular/quickstart/issues

**Comment by Toxicable** [comment]
@roroco I ran your reproduction on my machine and did not get any errors, therefore it is not a reproduction which implies that it's not a bug with Angular since I havn't been able to reproduce it.
Please try again to make a minimal reproduction in a plunkr or github repo.
However I assume it's something mis configured with your environment rather than the Quick start, in which case as @DzmitryShylovich said you should reopen on the quickstart repo

**Comment by roroco** [comment]
@Toxicable thanks your reply
when i disable chrome extensions, not error is raised
i re-enable chrome extension one by one, I found "Screenshot Capture(Better than Google's)", will cause this question, I remove it.
now everything work well
