### ISSUE TITLE
Angular2/forms - [formControl] in a child component crash

### ISSUE THREAD

**Issue by danicomas** [angular/angular#13661]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If we have a parent component with this template:

```
<form [formGroup]="form" (ngSubmit)="onSubmit(form)">
    <img [src]="data.avatar_url ? data.avatar_url : ''" width="100" height="100"/>
    <input-text control="name" [data]="data.name" [form]="form"></input-text> 
    <input type="submit" class="btn btn-primary" value="submit"/>
  </form>
```

And a child component inputText with this:
```
@Component({
  selector: 'input-text', 
  inputs: ['controlPath: control', 'value: data'],
  template: `
    <div class="form-group">
      <label [attr.for]="controlPath">{{controlPath}}</label>
      <input type="text" class="form-control" [id]="controlPath" [formControl]="control" [placeholder]="controlPath" [(ngModel)]="value" />
      <input type="button" (click)="hola()" value="click to hello!" />
    </div>
  `})
export class InputText implements OnInit, OnChanges {
  controlPath: string;
  value: string;
  @Input() form: FormGroup;
  control: FormControl;

  /*constructor() {
//this.control = this.form.controls[this.controlPath]; tried here -> crash. this.forms is null
  }*/
   
  ngAfterViewInit() {
    this.control = this.form.controls[this.controlPath]; //after this. crash
  }

   /*ngOnInit() {
     this.control = this.form.controls[this.controlPath]; //after this. crash
   }*/
   
   ngOnChanges(changes) {
   }
   
   hola() {
       alert(this.value);
   }
}
```

Appears the following error:
EXCEPTION: Error in ./InputText class InputText - inline template:3:117 caused by: Cannot find control with unspecified name attribute

I have seen that the problem is the [formControl] value. This value doesn't accept null values.

**Expected behavior**
I expect we could have formControls in a child component and this child component shouldn't have formGroup because is inherits of parentComponent.

**Minimal reproduction of the problem with instructions**
Explained in the current behavior. I attach a plunker too: https://plnkr.co/edit/0C7ihvzLUWMU5ExpvJy0?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.0

* **Browser:** [Chrome 55]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> <input type="text" class="form-control" [id]="controlPath" [formControl]="control" [placeholder]="controlPath" [(ngModel)]="value" />

Don't use reactive and template driven forms on the same time.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

**Comment by danicomas** [comment]
Thanks for your observation @DzmitryShylovich . It works now. I have updated the https://plnkr.co/edit/OxGCd2NiISOyqGO0uCgu?p=info
