### ISSUE TITLE
Dynamic Forms Validating multiple times

### ISSUE THREAD

**Issue by Phmager** [angular/angular#13660]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a dynamic form is built using ngfor, it runs updateValueAndValidity for each already existing control. This is quite an overhead, as it also reruns async validators. When this is used in combination with ng-bootstrap it also throws an exception: See here https://github.com/ng-bootstrap/ng-bootstrap/issues/1159
Because when you switch a tab it reruns the asyncValidators and then has the exception.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/1gfAl4oolKWkgQ7eca8g?p=preview

* **Angular version:** 2.0.X
See plunker

![image](https://cloud.githubusercontent.com/assets/9350951/21486868/66070a04-cbbc-11e6-9168-da2225fb42f7.png)

**Comment by Phmager** [comment]
There is also an exception in this plunker, that is also related to that problem:
http://plnkr.co/edit/QxVMdcmTq6Uj2v7Pc2mj?p=preview

**Comment by minuz** [comment]
I'm experiencing the same thing. In my case, I need a server-side validation which makes this multiple runs even worst.

**Comment by loginova-anna** [comment]
Same problem. Does anyone have a solution/workaround for this?

**Comment by minuz** [comment]
In some cases, changing the ChangeDetection strategy to OnPush solves the exception. However, it can have some unwanted side effects. 

What I have done as a workaround was to use form.reset({<model>}) on ngAfterViewInit(). This will call the updateAndRunValidity() only once per field. However, where I have asyncValidator I still haven't found a proper solution.

**Comment by sysmat** [comment]
Same problem. Does anyone have a solution/workaround for this?

**Comment by AndrewKushnir** [comment]
Hi, it looks like the original plnkr repro doesn't work and I tried to re-create it using [Stackblitz](https://stackblitz.com/). The repro is quite complex to re-create and if someone has a simplified version of it on [Stackblitz](https://stackblitz.com/), that'd be great. Thank you.

**Comment by AndrewKushnir** [comment]
Hi, I'm closing this issue since there is no up-to-date repro available. Feel free to reopen if the problem still exists and there is a minimal repro with more recent versions of Angular packages. Thank you.
