### ISSUE TITLE
Cannot read property 'listLazyRoutes' of undefined  Issue in Newly created Angular 2.2.3 Project

### ISSUE THREAD

**Issue by rahullsinha** [angular/angular#13663]
here is Screenshot
![angular 2 bug](https://cloud.githubusercontent.com/assets/20947986/21456939/846c62f4-c951-11e6-9860-89ea62ed977d.PNG)

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by rahullsinha** [comment]
this issue is occured in fresh installation
