### ISSUE TITLE
Angular2 - FormGroup - Validators - Can not merge sync with async validators

### ISSUE THREAD

**Issue by danicomas** [angular/angular#13662]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
[Validators.Required(sync),Validators.slug(is async)] fails with error .subscribe not found

**Expected behavior**
All validators fired

**Minimal reproduction of the problem with instructions**
I attach this plunkr, only you need to add a Validators.Required before the Validators.slug and we will see the crash
https://plnkr.co/edit/YsYtVIZExcF9u12nX0ud?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.0

* **Browser:** [Chrome 55]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by danicomas** [comment]
@DzmitryShylovich the correct way would be answering with the cause or the solution in case you think that is not an issue.
