### ISSUE TITLE
title selector doesn't work when used as a selector in app.ts file

### ISSUE THREAD

**Issue by micronyks** [angular/angular#13669]
`title` selector doesn't work when used as a selector or component in `app.component`.

`app.ts`

```
import {Component} from '@angular/core'
import {TitleComponent} './title.component';

@Component({
  selector: 'my-app',
  template: `
      <h2>Hello {{name}} - micronyks</h2><br>
      <title></title>
  `,
})
export class App {
  name:string;
  constructor() {
    this.name = 'Angular2'
  }
}

```

`title.component.ts`

```

import {Component} from '@angular/core'


@Component({
  selector: 'title',
  template: `
    abc
  `,
})
export class TitleComponent {}


```
This above setup doesn't allow me to use `title` selector. I have observed that it creates a DOM element having `<title>` tag but contents are not visible for some reason.

**doesn't work with `title` selector** : **https://plnkr.co/edit/yU09gEOttSV1w1KR2n28?p=preview**

If I change `title` selector name to `titles`, it will start working.

**works with `titles` selector** : **https://plnkr.co/edit/xv1ZRoI2dDQ8cb1l0aJd?p=preview**

**Comment by DzmitryShylovich** [comment]
There's a native title tag https://developer.mozilla.org/en/docs/Web/HTML/Element/title

You should prefix your component selector to avoid such situations.

**Comment by micronyks** [comment]
@DzmitryShylovich Oh yes!! I completely forgot it. Thank for your reply.
Gonna close this issue.
