### ISSUE TITLE
date pipe not working for date '1482796800000'

### ISSUE THREAD

**Issue by HALOH** [angular/angular#13675]
{{1482796800000|date}}                            =>    Dec 27,2016
{{1482796800000|date:"yyyy-mm-dd"}}     => 2016-00-27

**Comment by artsiom-aliakseichyk** [comment]
Month format should be capitalize otherwise it means minutes

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.
