### ISSUE TITLE
CanDeactivate doesn't work with Observable return value.

### ISSUE THREAD

**Issue by monad98** [angular/angular#13680]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Implement CanDeactivate guard to return Observable<Boolean> for route A.
Push browser's back button to navigate back to route B.
When CanDeactivate called with return value of true, nothing happens.
Push back button again, then route changes to B.
Normal navigation works without any problem.

**Expected behavior**
CanDeactivate should work with browser's back/forward button.

**Minimal reproduction of the problem with instructions**
[Reproduction on Plnkr.](https://plnkr.co/edit/o6avTqny4U2QUMCnC5Kb?p=preview)
I just changed canDeactivate funtion in `app/crisis-center/crisis-detail.component.ts` .
```
  canDeactivate(): Promise<boolean> | boolean {
    // Allow synchronous navigation (`true`) if no crisis or the crisis is unchanged
    if (!this.crisis || this.crisis.name === this.editName) {
      return true;
    }
    // Otherwise ask the user with the dialog service and return its
    // promise which resolves to true or false when the user decides
    // return this.dialogService.confirm('Discard changes?');
    return Observable.of(window.confirm("Discard changes?"));
  }
```
1. Launch the preview in a separate window.
2. Click Heroes and then click Crisis Center.
3. Click one of crisis. Edit name.
4. Press Alt + Left arrow to go back and press OK.
5. Route doesn't change.
6. Press Alt + Left again, then route changes to Heroes.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
I don't know which version of Angular is used on latest live example, but this problem happens with my environment.

* **Angular version:** 2.4.0 (Router version: 3.4.0)

* **Browser:** Chrome v55.0.2883.87 
 
* **Language:** TypeScript 2.0.3

**Comment by DzmitryShylovich** [comment]
@monad98 pls add a **small** repro

**Comment by vicb** [comment]
I guess `return window.confirm("Discard changes?");` should work here ?

**Comment by monad98** [comment]
Never mind. Update to Angular to 2.4.1 from 2.4.0 resolves the problem.
