### ISSUE TITLE
ng1 $rootScope dependency injected into ng2 getting an issue in aot (ng1 -> ng2 hybrid).

### ISSUE THREAD

**Issue by lokeshnagpal** [angular/angular#13687]
I have created the following RootScopeService wrapper of $rootScope as below and after that i have used this under angular2 service named for example xService. :

```
import {Injectable, Inject} from "@angular/core";
@Injectable()
export class RootScopeService {
     static instance: RootScopeService;
    constructor( @Inject("$rootScope") public $rootScope: any) {

        return RootScopeService.instance = RootScopeService.instance || this;
    }

    public broadcast(eventName, event, scope) {
        this.$rootScope.$broadcast(eventName, event, scope);
    };
    public getRootScope(): any {
        return RootScopeService.instance.$rootScope;
    };
}
```
```
import {
    Injectable,
    Inject
} from '@angular/core'
import {
    Logger,
    Level
} from 'angular2-logger/core';
//import {RootScopeService} from './RootScopeService';

@Injectable()
export class xService {
    private log: Logger;
    private static instance: xService;
    constructor(@Inject("$rootScope") public rootScopeService: any) {
        if (xService.instance == null) {
            this.log = new Logger();
            this.log.Level = Level.DEBUG;
            xService.instance = this;
        }
        return xService.instance;
    }
    trackCustomEvent(customEvent, currentScope) {
        try {
            xService.instance.rootScopeService.broadcast(customEvent, currentScope);
        } catch (ex) {
            x.instance.log.error("x:: trackCustomEvent : " + ex.toString());
        }
    }
    trackActionEvent(actionEvent, scope) {
        xService.instance.trackCustomEvent(actionEvent, scope);
    }
}
```
I have compiled with AOT and it is compiled without fail . After then created the build file with rollup. When running the build.js file 

Getting following issue 
Uncaught TypeError: Cannot read property 'get' of undefinedrootScopeFactory @ build.js:31452__rootScope_46 @ build.js:80486_RootScopeService_53 @ build.js:80528createInternal @ build.js:80897NgModuleInjector.create @ build.js:9964NgModuleFactory.create @ build.js:9938(anonymous function) @ build.js:9492e.invoke @ zone.min.js:1inner.inner.fork.onInvoke @ build.js:8897e.invoke @ zone.min.js:1n.run @ zone.min.js:1NgZone.run @ build.js:8766PlatformRef_._bootstrapModuleFactoryWithZone @ build.js:9490PlatformRef_.bootstrapModuleFactory @ build.js:9473(anonymous function) @ build.js:81349(anonymous function) @ build.js:81355
(index):1 Refused to execute script from 'http://tags.bkrtx.com/js/bk-coretag.js' because its MIME type ('image/gif') is not executable.

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. Luckily it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
