### ISSUE TITLE
Can't resolve token with injected parameter using OpaqueToken

### ISSUE THREAD

**Issue by not-for-me** [angular/angular#13684]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I declare a token for the injection of constant value with a OpaqueToken **in my AppModule,**
the injector can't resolve the token and the parameter in my service class.

But, declared token in other external file, it works correctly.

**Expected behavior**
A declared token in a AppModule will be resolved with a paramter in a service by the injector.

**Minimal reproduction of the problem with instructions**
here is repro. 
https://plnkr.co/edit/KwRRvp?p=preview

The service class below is the problematic code snippet.
Uncommenting the code below will result in an error.
```
import { Injectable, Inject, Optional } from '@angular/core';
import { TEST_TOKEN } from './app.module';
import { TEST_OTHER_TOKEN } from './app.tokens';

@Injectable()
export class TestService {
  testVal;
  testOtherVal;
  
  constructor(
    // can't resolve TEST_TOKEN when declare it in the AppModule
    
    // @Inject(TEST_TOKEN) 
    // @Optional()
    // testInjectedVal,
    
    @Inject(TEST_OTHER_TOKEN)
    testOtherInjectedVal,
  ) {
    // console.log(`inejcted testInjectedVal? ${testInjectedVal}`);
    // this.testVal = testInjectedVal;
    
    console.log(`inejcted testOtherInjectedVal? ${testOtherInjectedVal}`);
    this.testOtherVal = testOtherInjectedVal;
  }
  
  printTestVal() {
    console.log(`testVal:${this.testVal}`);
    console.log(`testOtherVal:${this.testOtherVal} `);
  }
}
```

**Please tell us about your environment:**
Mac 10.11.6 

* **Angular version:** 2.0.X
latest version. 2.4.1

* **Browser:** 
maybe all

**Comment by DzmitryShylovich** [comment]
`TEST_TOKEN` is undefined http://prntscr.com/dou3hs because u have a circular dependency. `app.module.ts` imports `test.service.ts` and `test.service.ts` imports `app.module.ts`. It has nothing to do with angular.

**Comment by not-for-me** [comment]
@DzmitryShylovich
I missed the problem of relationship between modules in ES6.
Thank you for checking this issue.
closed.
