### ISSUE TITLE
Have a common QueryList in both JavaScript and Dart

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1368]
Currently `QueryList` is implemented twice, once in JavaScript and once in Dart. This means that we have duplication in both code and documentation, since the only thing different is the iterate method.

Proposed fix:

```javascript
import {BaseQueryList} from 'base_query_list';

class QueryList extends BaseQueryList {
  // common methods go here
}
```

base_query_list.es5:
```javascript
class BaseQueryList {
  [Symbol.iterator]() {
    return this._results[Symbol.iterator]();
  }
}
```

base_query_list.dart:
```dart
class BaseQueryList extends Object with IterableMixin<Directive> {
  Iterator<Directive> get iterator => _results.iterator;
}
```

**Comment by matanlurey** [comment]
Ideally QueryList in Dart would be a package:observe.ObservableList<T>. Is that still planned?

**Comment by mhevery** [comment]
Creating a fallow up issue #1580 for observables.
