### ISSUE TITLE
angular1.6 的 $http 的success和error方法失效

### ISSUE THREAD

**Issue by dongxiaoyong009** [angular/angular#13682]
源码删掉了这两个方法。请解释一下原因好吗?

**Comment by DzmitryShylovich** [comment]
Wrong repo https://github.com/angular/angular.js

**Comment by laskoviymishka** [comment]
@dongxiaoyong009 those were deleted in angular 1.6 release to make $http service fully compatible with `Promise` standard (those methods not exist in ES2015 promises)

**Comment by laskoviymishka** [comment]
@dongxiaoyong009 see _https://github.com/angular/angular.js/commit/b54a39e2029005e0572fbd2ac0e8f6a4e5d69014_ main reason are explained in git commit message.

**Comment by dongxiaoyong009** [comment]
@laskoviymishka 明白了，谢谢~

**Comment by laskoviymishka** [comment]
@dongxiaoyong009 乐意帮助
我的中国是坏

**Comment by dongxiaoyong009** [comment]
@laskoviymishka 我说的话很容易被翻译, lol

**Comment by dongxiaoyong009** [comment]
@DzmitryShylovich 已经知道了，多谢反馈。

**Comment by dongxiaoyong009** [comment]
顶顶顶
