### ISSUE TITLE
published code & npm bundles include abstract methods

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#13696]
**I'm submitting a bug report**

**Current behavior**
Published code & umd bundles from npm such as `@angular/platform-browser/bundles/platform-browser.umd.js` from `@angular/platform-browser` include extra licenses and empty abstract methods.

**Expected behavior**
Ideally our .umd bundles would not include these abstract no-op methods or the duplicate license information. This would probably result in bundle size reduction and performance increase for all Angular apps using these bundles.

**Minimal reproduction of the problem with instructions**
```
npm install @angular/platform-browser
grep ") { }" node_modules/@angular/platform-browser/bundles/platform-browser.umd.js
```

**Angular version:** 2.4.1 & master

**Comment by IgorMinar** [comment]
this has been resolved already in v4 or thereabouts
