### ISSUE TITLE
Internet Explorer infinite digest with location change during 

### ISSUE THREAD

**Issue by thetrevdev** [angular/angular#13697]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

http://plnkr.co/edit/7SldRRsrYFO32hiG9abV?p=preview
Infinite digest error in Internet Explorer console after button click

**Expected behavior**

Location changes without error

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/7SldRRsrYFO32hiG9abV?p=preview with Internet Explorer
Check error console after button click.
Note: this happens when the location change occurs during an $evalAsync 

**What is the motivation / use case for changing the behavior?**
We have a large app with different redirect scenarios that may or may not be local to our app.  We wish to set location.href.  

* **Angular version:**  1.5/1.6

* **Browser:** [ IE 11 ] 

In internet explorer the hashchange event fires asynchronously.  this causes the $locationWatch to think that the $location url was updated as it doesn't match $browser url.   It seems like the location logic should know whether a url change occured via $location setters

**Comment by DzmitryShylovich** [comment]
Thx for reporting the issue but this is angular 2 repo. Pls re-open it on https://github.com/angular/angular.js/

**Comment by vicb** [comment]
this repo is for angular 2
