### ISSUE TITLE
Router navigate no longer working after upgrade from 3.1.2 to  3.2.0

### ISSUE THREAD

**Issue by critchie** [angular/angular#13693]
I'm submitting a
```
[ X] bug report
[ ] feature request
[ ] support request 
```

Current behavior
I have a similar scenario to that found in the Angular Router documentation.  I'm using Auth0 to authenticate users.  Long story short, after a successful login the user is redirected to the application home page.  My code was working up until I upgraded to Router v3.2.0.

Here is a screen shot of my console after the upgrade to v3.2.0:

![image](https://cloud.githubusercontent.com/assets/340046/21531125/91fed9cc-cd13-11e6-8f80-855c65b94895.png)

Notice the extra hop to the login page indicated by the 'login ngOnInit' message after the "redirecting: /home" message which tells me the login component is being initialized again (and eventually displayed).

**Expected behavior**
With 3.1.2 this is my console output:

![image](https://cloud.githubusercontent.com/assets/340046/21531205/227a59c2-cd14-11e6-880a-d94656717a97.png)

As you can see there is no extra hop to the login page.  After the successful authentication noted by the "authenticated" message it redirects to '/home' and all is good.

**Minimal reproduction of the problem with instructions**
This is very difficult to reproduce without the actual use of Auth0.  The concept is very similar to the  Angular Router documentation.  The big kicker is that the code works with 3.1.2 but breaks when moving to 3.2.0.

Here is the relevant login component ngOnInit:
```
  ngOnInit(): void {
    console.log('login ngOnInit');
    this.authService.login()
      .subscribe((authenticated: boolean) => {
        let redirectUrl = this.authService.redirectUrl ? this.authService.redirectUrl : '/home';
        console.log('redirecting: ' + redirectUrl);
        this.router.navigateByUrl(redirectUrl);
      });
  }
```

Here is the relevant AuthGuard:
```
export class AuthGuard implements CanActivate {

    constructor(private authService: AuthService,
                private router: Router) {}

    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
        let url: string = state.url;
        return this.checkAuthentication(url);
    }

    checkAuthentication(url: string): boolean {
        // if user logged in then allow routing to continue
        if (this.authService.authenticated()) {
            return true;
        }

        // if here then user not logged in so
        // save the return URL for redirect after login
        this.authService.redirectUrl = url;
        // navigate to login
        this.router.navigate(['/login']);
        // return false to cancel routing
        return false;
    }
}
```

**What is the motivation / use case for changing the behavior?**
I would like to be able to guard those parts of the app where the user is not authenticated.  A very simple, real life use case.

**Please tell us about your environment:**
Windows 7 Professional
Visual Studio Code

* **Angular version:** 2.0.X
Angular 2.4.1

* **Browser:** 
 Chrome Version 55.0.2883.87 m

* **Language:**
Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Thx for reporting the issue. Pls add a small repro in plunkr with observed vs expected behavior.

**Comment by critchie** [comment]
I wouldn't even know where to begin with plnkr.

**Comment by DzmitryShylovich** [comment]
You can use https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 as a starting point

**Comment by critchie** [comment]
After setting up the repo I gained more understanding of the router and what Auth0 is actually doing.  The issue is in my code not the router's.  Still can't figure out why it works with v3.1.2 and not with v3.2.0 but I'm moving on.  Thanks.
