### ISSUE TITLE
ng1 $filter injected into ng2 in aot hybrid(ng1 -> ng2). Getting issue "No provider for $filter!"

### ISSUE THREAD

**Issue by lokeshnagpal** [angular/angular#13705]
I have created the following filterService wrapper of $filter as below and after that i have used this under angular2 service named for example xService. :

```
import {Injectable, Inject} from "@angular/core";

@Injectable()
export class filterService {

    static instance: filterService;

    constructor( @Inject("$filter") public $filter: any) {
        return filterService.instance = filterService.instance || this;
    }
    getFilter() {
        return filterService.instance.$filter;
    }
};

import {Injectable,Inject} from '@angular/core'
import {Logger,Level} from 'angular2-logger/core';

@Injectable()
export class xService {
private log: Logger;
private static instance:xService;
constructor(@Inject("$filter") public $filter:any){
if(xService.instance==null){
this.log = new Logger();
this.log.Level = Level.DEBUG;
xService.instance = this;
}
return xService.instance;
}
trackCustomEvent(customEvent, currentScope){
try{
xService.instance.$filter.getFilter()("accountTypeFilterIcon");
}catch(ex){
x.instance.log.error("x:: trackCustomEvent : " + ex.toString());
}
}
trackActionEvent(actionEvent, scope){
xService.instance.trackCustomEvent(actionEvent, scope);
}
}
```

After running the application with aot compilation rollup  , getting an issue of "No Provide for $filter!" in 
build.js file
Uncaught Error: No provider for $filter!
ReflectiveInjector_._throwOrNull @ build.js:3422
ReflectiveInjector_._getByKeyDefault @ build.js:3459
ReflectiveInjector_._getByKey @ build.js:3409
ReflectiveInjector_.get @ build.js:3171
createInternal @ build.js:80890
NgModuleInjector.create @ build.js:9964
NgModuleFactory.create @ build.js:9938
(anonymous function) @ build.js:9492
e.invoke @ zone.min.js:1inner.inner.fork.onInvoke @ build.js:8897
e.invoke @ zone.min.js:1n.run @ zone.min.js:1NgZone.run @jdalton build.js:8766
PlatformRef_._bootstrapModuleFactoryWithZone @ build.js:9490
PlatformRef_.bootstrapModuleFactory @ build.js:9473
(anonymous function) @ build.js:81341
(anonymous function) @ build.js:81347

**Comment by gkalpak** [comment]
Not all Angular 1.x services are automatically upgraded. If you need a built-in Angular 1.x service/filter in the 2.x part of the app, you need to provide the factory yourself. An example can be found [here][1] (it applies to built-in and custom services alike).

[2]: https://angular.io/docs/ts/latest/guide/upgrade.html#!#making-angular-1-dependencies-injectable-to-angular-2
