### ISSUE TITLE
Add validator for <input type="email">

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#13706]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There's no validator for `<input type="email">` so users have to use pattern validator

**Expected behavior**
We should provide validators for basic input types

This is a duplicate of https://github.com/angular/angular/issues/2962 but it's too much for a single pr so I want to break it into multiple issues

**Comment by alyssamichelle** [comment]
You go @mhevery , you go!

**Comment by cyrilletuzi** [comment]
Is there a reason this new validator requires a specific attribute to be added, instead of detecting native `type="email"` ?

It does not seem consistent with other validators (`required`...).

**Comment by DzmitryShylovich** [comment]
@cyrilletuzi it's a common use case to disable/enable validators. if we would use `type="email"` selector you wouldn't be able to disable it
