### ISSUE TITLE
Router.isActive not work with parameters

### ISSUE THREAD

**Issue by kisdaniel** [angular/angular#13703]
When I tried to add active class to active route to my navbar, I found the following bug in router.isActive function:
isActive function returns true in all dasboard elements, so all links looks active with exact true parameter,
```
<li *ngFor="let item of dashboards" 
            [class.active]="router.isActive(router.createUrlTree(['dashboard', { dashboard: item }]), true)">
    <a [routerLink]="['./dashboard',  { dashboard: item }]">
       {{ item }}
    </a>
</li>
```
The router is Angular2 router and the dashboards is `public dashboards: string[];`

**Comment by DzmitryShylovich** [comment]
Duplicate https://github.com/angular/angular/issues/13093#issuecomment-264528917
