### ISSUE TITLE
Can not get header in response headers when upgrade to Angular final

### ISSUE THREAD

**Issue by Sophia-nguyen** [angular/angular#13700]
Hi, I have a problem when get response headers in my app.

In API:
```
res.header("Access-Control-Allow-Origin", "*");
res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
res.header("Access-Control-Allow-Methods", "*");
res.header("Access-Control-Expose-Headers", "WWW-Authenticate");
```
Send request and open debug mode in Chrome, I see:
![image](https://cloud.githubusercontent.com/assets/11731312/21541698/0054753a-cdeb-11e6-9678-073124f2fea6.png)

And in Front_end code:
```
this.http.get(url, options)
               .map(
                    res => res
                )
                .subscribe(
                    (res) => {},
                    (err) => {
                         let authenticateErr = res.headers.get("WWW-Authenticate");
                        //authenticateErr = null;
                     });
```
And err.heades that I see:
![image](https://cloud.githubusercontent.com/assets/11731312/21541701/0b5b3f54-cdeb-11e6-921b-c05e9452f28a.png)

My code is work corectly when I use Angular beta6. When I upgrade to angular rc4, and final it don't work.
How can I fix this issue, anyone can help me.
Thanks

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by DzmitryShylovich** [comment]
have u tried to make the same request using xhr?

**Comment by Sophia-nguyen** [comment]
not yet, I will try.

**Comment by DzmitryShylovich** [comment]
@Sophia-nguyen did u solve it?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource no feedback. can be closed
