### ISSUE TITLE
Feat: Support TypeScript 2.1

### ISSUE THREAD

**Issue by tbosch** [angular/angular#13715]
Right now, many users are trying to use TypeScript 2.1, but `ngc` either produces strange error messages, or does not create `.ngfactory.ts` files at all.

**Comment by RyanCavanaugh** [comment]
#13716 should fix this (/cc @chuckjaz ) as it has the appropriate 2.1-specific shims

**Comment by chuckjaz** [comment]
The changes @RyanCavanaugh mentioned should fix this plus, beginning with 2.1, the `SourceFile` we are receiving in write is the transformed source which confuses the collector. I am working on a fix for this.

**Comment by mmc41** [comment]
When and how can we expect the VS 2.1 support to be available. As a small fix for angular 2.0 or will it be bundled with all the incompatible changes of the future angular 4.0 ?

**Comment by DzmitryShylovich** [comment]
> As a small fix for angular 2.0

**Comment by jamespacileo** [comment]
The ticket linked by @RyanCavanaugh has been closed as complete 15 days ago.

Is this feat now considered complete?

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/pull/13294#issuecomment-274849622

**Comment by awerlang** [comment]
Not using any TS 2.1.x language feature, but I see inherited decorators/metadata ain't being honored in JiT mode. In AoT mode it works!

Plunker: http://plnkr.co/edit/5Ho7YY3g9i59BjIkWCS3?p=info

Saw the issue https://github.com/Microsoft/TypeScript/issues/12439 but I guess it's on the angular side now.

**Comment by DzmitryShylovich** [comment]
@awerlang http://plnkr.co/edit/0nU3LuUa7fthkxwul29T?p=preview

**Comment by Toxicable** [comment]
Can close since we support it in 4.x ?

**Comment by chuckjaz** [comment]
Yes. 2.1 is now required by 4.x.
