### ISSUE TITLE
NO_ERRORS_SCHEMA doesn't work for a directive in a template tag

### ISSUE THREAD

**Issue by jongunter** [angular/angular#13713]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If I use `NO_ERRORS_SCHEMA` in my module definition and I try to use unknown directives or components in my templates, those errors are suppressed. However, if use `NO_ERRORS_SCHEMA` and put an unknown directive on a `<template>` tag, I still get `Template parse errors`.

**Expected behavior**
Shouldn't `NO_ERRORS_SCHEMA` ignore unknown directives on all components, including `<templates>`.

**Minimal reproduction of the problem with instructions**
(Remove the template tag to see it not error-out)
https://plnkr.co/edit/UPTGW0ESIwRE4kL0XI3G?p=info

**What is the motivation / use case for changing the behavior?**
I'm trying to unit test a Wijmo control that implements template tags with custom directives, but I just want to ignore all of these rather than trying to mock them out.

* **Angular version:** 2.0.X
2.0

* **Browser:** Chrome? Others maybe?
 
* **Language:** TS

**Comment by vicb** [comment]
This is not related to the schema. Property binding on templates are supposed to be consumed by directives, as indicated by the error message:
```
Property binding title not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations"
```
