### ISSUE TITLE
add dgeni support for square-bracket links (or let me know what syntax we should be using)

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#1371]
@petebacondarwin currently we have a bunch of refs in the docs like [Directive] that should be replaced with a link to the `Directive class` docs page, but that are currently just passed through as plaintext.

Can we generate the links?

**Comment by petebacondarwin** [comment]
I took a look through the source code and I think we should stop using `[ComponentName]` for code links. I appreciate that this is the dartdoc style but it is much harder to identify these as links over actual square bracket usage in the docs. This is even more so now that we have the `<a [href]="someExpression">` style of templating.

Instead I would suggest that we go over to using the same inline annotations as in the angular-1 docs. This declares links in the form of `{@link ComponentName}`.

I can put together a PR with this update to the current docs.

**Comment by naomiblack** [comment]
If you have time to make this PR before Thursday morning PT, that would be awesome. I'll start using this now, and I have no objection to the change.

**Comment by petebacondarwin** [comment]
I am putting the PR together but there are some issues. A number of currently linked items don't match existing exports (or sort of link to parameters, which don't have docs of their own).

Also there is another issue: if you re-export a class, say `Directive`, then linking to it by `{@link Directive}` immediately creates an ambiguity, which can (at the moment) only be solved by giving the module too: `{@link angular2/annotations.Directive}`

**Comment by naomiblack** [comment]
Ah, got it. I think both of those are fine -- we are likely going to have to do a manual edit pass in any case for this first release and will fix the ones we've missed.

If you happen to have a list of the ones that don't link to exports, that would be helpful but not essential.
Would it make sense to support a kind of anchor for parameters? Or should we just not link to them...?

**Comment by naomiblack** [comment]
Sorry I missed you Thursday. Can you please merge (or publish) your PR Friday before going offline? We'll otherwise have to redo the work since all of this must be correct in the output (either automated or manually) by Friday for our internal user milestone.
