### ISSUE TITLE
Dynamic Landing page based on Role Angular  Router "~3.4.0"

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#13711]
I have different user roles and based on the logged in user role, I want to to change the default page(landing page) after log in. How do i achieve it, haven't found any resources online, is it something that needs to be implemented yet or I am missing something:

I have two modules ExceptionDashboard and cashierRiskprofile module routes

```
import { Routes, RouterModule } from "@angular/router";

import { CashierRiskProfileComponent }    from "./cashierriskprofile.component";

const cashierRiskProfileRoutes: Routes = [
    { path: "", redirectTo: "cashierriskprofile", pathMatch: "full" },
    { path: "cashierriskprofile", component: CashierRiskProfileComponent }
];

export const CashierRiskProfileRouting = RouterModule.forChild(cashierRiskProfileRoutes);
```

Above code will have default route as cashierRiskprofile.

ExceptionDashboard:

```
const exceptionDashboardRoutes: Routes = [
    { path: "exceptionDashboard", component: ExceptionDashboardComponent, pathMatch: 'full' },
    { path: "exceptionDetail", component: ExceptionDetailComponent, pathMatch: 'full' },
     { path: "exceptionTransaction", component: ExceptionTransactionComponent, pathMatch: 'full' }
];
```

For Admin users we show CashierRiskProfile as landing page which is already defaulted, for other users I wanted to show exceptionDashboard path as landingpage. How do I change it based on UserRole.

I know how to implement CanActivateViaAuthGuard "canActivate" service to redirect to a particular page if user is not autheticated , but I am looking at changing landing page based on user roles ?

```
import { Injectable } from '@angular/core';
import { CanActivate } from '@angular/router';
//import { AuthService } from './auth.service';

@Injectable()
export class CanActivateViaAuthGuard implements CanActivate {

    constructor(/*private authService: AuthService*/) { }

    canActivate() {
        //if logged in return true
        return true;

        //else retrun to login page
        //return false;
    }
}
```

I want to implement something which changes dynamically default page based on User Role.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vijender1256** [comment]
@DzmitryShylovich thank you, but is there any documentation or online resources which explains how to solve this issue ?

**Comment by vicb** [comment]
You can achieve this with a custom `matcher` in your route configuration.

This seems like a common use case, could you please open an issue on angular/angular.io so that the docs team document it. Thanks.
