### ISSUE TITLE
error_handler.js:45EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'routes' of undefined TypeError: Cannot read property 'routes' of undefine

### ISSUE THREAD

**Issue by mcnj2** [angular/angular#13712]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Code works on local NG serve. When build is created and deployed. It gives error.

**Expected behavior**
 It should work without any error and load the page

**Minimal reproduction of the problem with instructions**
You can check this at http://ec2-54-244-194-73.us-west-2.compute.amazonaws.com:8080/dist/ 

**Please tell us about your environment:**

* **Angular version:** 2.1.0
 YES

* **Browser:** [all | Chrome XX  ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

angular-cli: 1.0.0-beta.15
node: 6.9.2
os: linux x64
npm: '3.10.9'
Typescript Version 2.0.0

![image](https://cloud.githubusercontent.com/assets/24831853/21554137/fdf4f380-ce32-11e6-8d70-689814e3a1cc.png)

**Comment by DzmitryShylovich** [comment]
Thx for submitting the issue. Pls add a reproduction (plunkr/github repo) otherwise we can't do much.

**Comment by DzmitryShylovich** [comment]
Did u search for a similar issues like https://github.com/angular/angular/issues/12842 or https://github.com/angular/angular/issues/12682?

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by mcnj2** [comment]
@DzmitryShylovich :  Thanks for referring to similar issues. But unable to locate what;s actual fix for this?
