### ISSUE TITLE
Outdated Routing documentation

### ISSUE THREAD

**Issue by vadim-shb** [angular/angular#13727]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Outdated Routing documentation. In official documentation here:
https://angular.io/docs/ts/latest/guide/router.html
Paragraph "Milestone #3: The Heroes Feature" is outdated. Can not strictly follow the instructions, because file names and some parts of code not based on current version of "Tour of Heroes" (which is here: https://angular.io/resources/live-examples/toh-5/ts/eplnkr.html)

**Minimal reproduction of the problem with instructions**
For example there is no hero-list.component.ts and HeroListComponent class in current version of "Tour of Heroes"

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io/issues

**Comment by vadim-shb** [comment]
done
