### ISSUE TITLE
"ngFor...in" to iterate over the enumerable properties of an object

### ISSUE THREAD

**Issue by jsayol** [angular/angular#13723]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
The ngFor directive iterates over each value of iterable objects, akin to the ["for...of" statement](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of).

If one wants to iterate over the enumerable properties of an object, an array of those properties needs to be created first and passed to ngFor.

**Expected behavior**
Being able to use ngFor in a similar manner to the ["for...in" statement](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...in):

Model:
```ts
this.things = {
  hello: 42,
  world: true
};
```

Template:
```html
<div *ngFor="let name in things"> {{ name }} </div>
```

Output:
```html
<div> hello </div>
<div> world </div>
```

**Minimal reproduction ~~of the problem~~ with instructions**
[I have a sample implementation over here](https://gist.github.com/jsayol/3d6ec856880b8c510c7220d840715d12#file-ng_for_in-final-ts).

This would ideally be part of the NgFor class itself rather than extending it, but this is just a demo. Proper thought would need to go into an actual implementation to make sure all edge cases are covered.

**What is the motivation / use case for changing the behavior?**
While it is currently possible to achieve the desired behavior, it involves several extra steps like using the directive linked above, implementing a similar behavior as a pipe, or manually extracting and storing the enumerable properties in the model.

Having this as part of the framework would greatly simplify its usage when needed.

**Please tell us about your environment:**
* **Angular version:** 2.X, 4.0.X

* **Browser:** all
 
* **Language:** all

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/2246
TLTR: it's by design

**Comment by jsayol** [comment]
Sorry, I did a quick scan of existing issues and missed that one. Closing.
