### ISSUE TITLE
"Live Example" at URL https://angular.io/resources/live-examples/toh-6/ts/eplnkr.html not working in Firefox 50.1.0

### ISSUE THREAD

**Issue by bignmllc** [angular/angular#13735]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Only "Loading..." is displayed in the Preview pane

**Expected behavior**

The application page should eventually display, but it never does.

**Minimal reproduction of the problem with instructions**

Just try going to the URL https://angular.io/resources/live-examples/toh-6/ts/eplnkr.html using Firefox 50.1.0 and you will see the results.

**What is the motivation / use case for changing the behavior?**

It should be cross-platform, right?

**Please tell us about your environment:**

It is working in the following browsers:
Chromium Version 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit)
Chrome Version 49.0.2623.108 (64-bit)
But not in the following browsers:
Mozilla Firefox for Ubuntu 50.1.0

* **Angular version:** 2.0.X

Whatever the www.angular.io site is using.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chromium Version 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit)
Chrome Version 49.0.2623.108 (64-bit)
Mozilla Firefox for Ubuntu 50.1.0
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Whatever the www.angular.io site is using.

* **Node (for AoT issues):** `node --version` =   
Whatever the www.angular.io site is using.

**Comment by vicb** [comment]
Pls report docs issues on https://github.com/angular/angular.io/issues
