### ISSUE TITLE
Code sample in Augular Tutorial Services section wrong

### ISSUE THREAD

**Issue by velkur** [angular/angular#13733]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The code in the appendix section of the services section of Angular tutorial is wrong. 

Link: [https://angular.io/docs/ts/latest/tutorial/toh-pt4.html#!#slow](https://angular.io/docs/ts/latest/tutorial/toh-pt4.html#!#slow)

It is currently:
```
getHeroesSlowly(): Promise<Hero[]> {
  return new Promise(resolve => {
    // Simulate server latency with 2 second delay
    setTimeout(() => resolve(this.getHeroes()), 2000);
  });
}
```

**Expected behavior**
It should be:
```
getHeroesSlowly(): Promise<Hero[]> {
  return new Promise(resolve => {
    // Simulate server latency with 2 second delay
    setTimeout(() => resolve(HEROS, 2000);
  });
}
```
**Minimal reproduction of the problem with instructions**
This is a documentation bug.

**What is the motivation / use case for changing the behavior?**
I am using the tutorial to learn Angular and found the code mistake.

**Please tell us about your environment:**
MacOS, Visual Studio Code.

* **Angular version:** 2.0.X
Yes

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
v7.2.1

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io/issues

**Comment by velkur** [comment]
thank you
