### ISSUE TITLE
Checkbox updates without updating checked value

### ISSUE THREAD

**Issue by vinckobb** [angular/angular#13749]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When trying to use input checkbox with checked attribute it updates checkbox state even if checked value is not updating.

In the following template you can change checkbox state without changing check.visible value.
```
<div *ngFor="let check of checks; let i = index">
    <dl>
        <dt><input [id]="'column' + i" type="checkbox" [checked]="check.visible"/></dt>
        <dd><label [attr.for]="'column' + i">{{check.visible}}</label></dd>
    </dl>
</div>
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**
Here is sample that show current behavior. There are multiple checkboxes and click changes visible value only on odd items. http://plnkr.co/edit/5mKgEmNHP4aKRAN7ZvEG?p=preview

**What is the motivation / use case for changing the behavior?**
I want to allow user to choose for example one to five options from list while not disabling them and only check and update that value in its click method.

**Please tell us about your environment:**

Windows 7, Webstorm 2016.3.2, npm, Connect server

* **Angular version:** 2.4.1

* **Browser:** all

 
* **Language:** TypeScript 2.0.9

**Comment by DzmitryShylovich** [comment]
You didn't import FormsModule so angular is not involved here

**Comment by pkozlowski-opensource** [comment]
> I want to allow user to choose for example one to five options from list while not disabling them and only check and update that value in its click method.

Sorry but it is not clear from your plunker and description what is not working properly. If you ask me plunker works as intended. 

Could you please try to re-phrase expected vs. current behavior?

**Comment by DzmitryShylovich** [comment]
@vinckobb any updates or it can be closed?
