### ISSUE TITLE
Route data is undefined on page reload

### ISSUE THREAD

**Issue by anikets43** [angular/angular#13748]
I'm passing data along with the route and reading in the canActivate implementation to check whether user has privilege to the page. It works fine when navigated for the first time, but on page reload, the route data is undefined
**home.routing.ts**
```
export const HomeRoutes: Routes = [
    {
        path: '',
        component: HomeComponent,
        canActivate: [AuthGuard],
        children: [
            { path: '', component: DashboardComponent },
            {
                path: 'groups',
                loadChildren: 'app/modules/groups/groups.module#GroupsModule',
                data: { privilegeId: 5 }
            }
        ]
    },
];
export const HomeRouting = RouterModule.forChild(HomeRoutes);
```

**auth-guard.service.ts**
```
canActivate(routeSnapshot: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | boolean {
// Issue: privilegeId is undefined on page reload.
let privilegeId = routeSnapshot.data["privilegeId"] as number;

// Calls API with privilege id and returns boolean.
}
```
Angular 2.1.0
Router: 3.1.0

**Comment by DzmitryShylovich** [comment]
Pls update to the latest angular and add a small repro in plunkr

**Comment by anikets43** [comment]
Hi @DzmitryShylovich 

As you said, I have updated to latest angular 2.3.1 which CLI provides but no luck. I have tried creating a sample with the same scenario I have. Since, it route doesn't hold the data on page refresh, we can't verify the issue on the plnkr as it bootstraps the application on refresh.

[https://plnkr.co/edit/ohzN9GLPgSWz4vs2CoR4?p=preview](url)

Cheers,
Aniket

**Comment by DzmitryShylovich** [comment]
>  latest angular 2.3.1

the latest is 2.4.1 for angular and 3.4.1 for router.

> Since, it route doesn't hold the data on page refresh, we can't verify the issue on the plnkr as it bootstraps the application on refresh.

I'm not following. Pls add steps to reproduce and expected behavior. Thx.
