### ISSUE TITLE
Access higher parent component from child (not direct parent)

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#13752]
**I'm submitting a ...**
```
[ x ] bug report
[ x ] feature request
[ ] support request
```

**Current behavior**
From child component i can access only to direct parent, not to his higher parent via `@Host()`

**Expected behavior**
Access to any matched parent despite it's direct or higher one.

**Minimal reproduction of the problem with instructions**
Real app example with menu and his items

Plunkr - http://plnkr.co/edit/ArQZYZsHQgn6I2eK3AZd

```html
<!-- app component -->
<menu>
  <auth-logout></auth-logout>
</menu>

<!-- menu component -->
<div class="menu">
  <ng-content></ng-content>
</div>

<!-- auth-logout component -->
<menu-item (itemClick)="logout()">
  LOGOUT
</menu-item>

<!-- menu-item component -->
<div class="menu-item"
     (click)="onClick()">
  <ng-content></ng-content>
</div>
```

**What is the motivation / use case for changing the behavior?**
I need the ability to create menus that contains any list of unknown thirdparty components (`auth-logout` in example) that can have `menu-item` component in their templates and listen to `menu-item` component click event. On `menu-item` click menu should be closed.
This requires accessing from `menu-item` component `menu` parent component that is not his direct parent.

**Why not to use service?**
There is several menus on page with different names (`menu` component Input that i skiped in example above `<menu [name]="'smth'">`) that used to manipulate menu (open/close or smth else). I can pass this name directly to `menu` component in template and cant in thirdparty components that is contained by this menu cause they are unkown components from different modules and should not know anything about menu instance that contains them. So i cant pass this menu name to `menu-item` component to close menu via service through thirdparty components and need to somehow access `menu` component from `menu-item`.

This worked well in ng1 via `require` property.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by ronbnsim** [comment]
@artaommahe , did you ever solve this? @vicb was this ever solved?

**Comment by mlc-mlapis** [comment]
@ronbnsim ... you still have already known possibilities ... either cascading direct injection of `Parent` or some type of shared service which would be injected into all relevant places.
