### ISSUE TITLE
Expose XSRF token as a service

### ISSUE THREAD

**Issue by lqc** [angular/angular#13755]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The XSRF token used by CookieXSRFStrategy is retrieved from the cookie using a private API (``__platform_browser_private__.getDOM().getCookie('XSRF-TOKEN')``). There is no clean way of accessing the token without either using the private API or parsing the cookie on your own. 

**What is the motivation / use case for changing the behavior?**
While the XSRF protection works great for standard XHR-based communication, it is sometimes necessary to have a plain HTML form that doesn't do the POST request via XHR. 

In that case, most server frameworks allow to send the XSRF token as part of the form data instead of a header, but for that you need to access it's current value. Having the token exposed as a service, would allow me to inject it to the component and render the token value to the form just before the submit.

An alternate solution would be to expose the getCookie() function from the browser platform as a public API. It feels silly to include a library for parsing cookies when I know that Angular already does it.

* **Angular version:** 2.2.4

**Comment by alxhub** [comment]
Fair point. Our intention is to go the other direction, and not have an XSRF token service with non-standard behavior in Angular. Interceptors will allow users to implement their own XSRF logic should they desire.

Regarding access to cookies, please file a separate feature request - I believe there are plans for a `DocumentService` and this would seem like a good fit.
