### ISSUE TITLE
Template inheritance with ng-content or similar

### ISSUE THREAD

**Issue by asfernandes** [angular/angular#13757]
```
[x] feature request
```

Component inheritance without template inheritance has very limited usefulness.

It would be good if the base component can use a tag (say, ng-content) where the inherited component template goes there. The Wicket Java framework implements this and is very useful, you can read about it here: https://wicket.apache.org/learn/examples/markupinheritance.html

**Comment by chuckjaz** [comment]
I recast this as a concrete proposal in #13766.Does it capture what you are proposing?

**Comment by asfernandes** [comment]
@chuckjaz yes, #13766 is very good.
