### ISSUE TITLE
Validator that is using another validator results in strange onChange behavior

### ISSUE THREAD

**Issue by robgha01** [angular/angular#13754]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If a validator is using another validator in itself the execution onchange triggers massively.

**Expected behavior**

To work like normal and not run code xxxx increasing unlimited times for every diggest.

**Minimal reproduction of the problem with instructions**
plunker with example: https://plnkr.co/edit/IFdGQsGB54N4w2H4fHe9?p=preview
the email field is working as its not using any other validators in itself.
the password field however illustrates what happens when one type as in this:
![image](https://cloud.githubusercontent.com/assets/362726/21596464/d04855b0-d13b-11e6-852b-f7108c1483e3.png)

notice how the iteration numbers are sky high.

**What is the motivation / use case for changing the behavior?**

So one can build validators that wrapp other validators and validates then returns a new result like im doing with equalTo. as in "fix this performance bug or what it is"

**Please tell us about your environment:**

Visual studio 2015
IIS 7.5
Package.json
```
{
  "dependencies": {
    "@angular/common": "^2.4.1",
    "@angular/compiler": "^2.4.1",
    "@angular/core": "^2.4.1",
    "@angular/forms": "^2.4.1",
    "@angular/http": "^2.4.1",
    "@angular/platform-browser": "^2.4.1",
    "@angular/platform-browser-dynamic": "^2.4.1",
    "@angular/router": "^3.4.1",
    "angular-calendar": "^0.6.0",
    "angular2-cookie": "^1.2.6",
    "babel-runtime": "^6.20.0",
    "core-js": "^2.4.1",
    "date-fns": "^1.21.1",
    "jquery": "^3.1.1",
    "lodash": "^4.17.3",
    "ng2-validation": "^3.1.2",
    "reflect-metadata": "^0.1.9",
    "rxjs": "^5.0.2",
    "scriptjs": "^2.5.8",
    "zone.js": "^0.7.4"
  },
  "devDependencies": {
    "@angularclass/hmr": "^1.2.2",
    "@angularclass/hmr-loader": "^3.0.2",
    "@types/bootstrap": "3.3.32",
    "@types/core-js": "^0.9.35",
    "@types/jasmine": "^2.5.38",
    "@types/jquery": "^2.0.34",
    "@types/node": "^6.0.53",
    "@types/scriptjs": "^0.0.2",
    "@types/selenium-webdriver": "^2.53.38",
    "angular2-template-loader": "^0.6.0",
    "autoprefixer": "^6.6.0",
    "awesome-typescript-loader": "^3.0.0-beta.17",
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.18.0",
    "bootstrap-loader": "^1.3.3",
    "bootstrap-sass": "^3.3.7",
    "browser-sync": "^2.18.5",
    "browser-sync-webpack-plugin": "^1.1.3",
    "bs-fullscreen-message": "^1.1.0",
    "codelyzer": "^2.0.0-beta.4",
    "compass-options": "^0.1.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "deep-extend": "^0.4.1",
    "del": "^2.2.2",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "gulp": "^3.9.1",
    "gulp-clean-css": "^2.0.13",
    "gulp-compass": "^2.1.0",
    "gulp-env": "^0.4.0",
    "gulp-load-plugins": "^1.4.0",
    "gulp-sequence": "^0.4.6",
    "gulp-typescript": "^3.0.2",
    "gulp-util": "^3.0.7",
    "img-loader": "^1.3.1",
    "imports-loader": "^0.7.0",
    "lazy-object": "^1.0.1",
    "load-gulp-tasks": "^0.1.0",
    "ng2-bootstrap": "^1.1.16-9",
    "ng2-facebook-sdk": "^1.1.0",
    "node-sass": "^4.1.1",
    "postcss-loader": "^1.2.1",
    "progress-bar-webpack-plugin": "^1.9.1",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "^1.6.1",
    "sass-loader": "^4.1.1",
    "source-map-loader": "^0.1.5",
    "strip-ansi": "^3.0.1",
    "style-loader": "^0.13.1",
    "tslint": "^4.2.0",
    "tslint-loader": "^3.3.0",
    "typescript": "2.0.10",
    "url-loader": "^0.5.7",
    "vinyl-named": "^1.1.0",
    "webpack": "^2.2.0-rc.2",
    "webpack-bundle-analyzer": "^2.1.1",
    "webpack-dev-middleware": "^1.9.0",
    "webpack-dev-server": "^2.2.0-rc.0",
    "webpack-hot-middleware": "^2.14.0",
    "webpack-merge": "^2.0.0",
    "webpack-node-externals": "^1.5.4",
    "webpack-stream": "3.2.0"
  }
}
```

* **Angular version:** 2.0.X
2.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =   
6.6.0

**Comment by DzmitryShylovich** [comment]
Could u pls strip down your repro to a single input control and a pair of validators? It's very hard to understand what is going on...

**Comment by robgha01** [comment]
@DzmitryShylovich Ok, i tried to remove all code and validators that is not used. is it better now ?

**Comment by DzmitryShylovich** [comment]
did u save your changes?

**Comment by robgha01** [comment]
sec

**Comment by robgha01** [comment]
@DzmitryShylovich ok now it should be gone. check again :)

**Comment by DzmitryShylovich** [comment]
nah still don't see any changes

**Comment by robgha01** [comment]
@DzmitryShylovich dide you open the console ?

**Comment by robgha01** [comment]
@DzmitryShylovich here is a gif illustrating what is happening watch the numbers:
![illustrating](https://cloud.githubusercontent.com/assets/362726/21596913/7363f71c-d142-11e6-852c-1261b4fd120e.gif)

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

If this is still a bug, please create a small repro case that shows just this issue. Remove anything not applicable.
