### ISSUE TITLE
ContentChild with multiple templates inside

### ISSUE THREAD

**Issue by pesimeao** [angular/angular#13753]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I try to use the `@ContentChild` with `TemplateRef` and there are multiple `<template>` tags inside, new elements are rendered with the "last" `template` instead of the one that is in the DOM tree of the content.

**Expected behavior**

ContentChild should always use the first selector found in the DOM tree.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/AWo8rPjikGXZZeHBVRFx?p=preview

When we add a new item to the array, the new item list of the "list with template" is rendered with another template than its siblings.

If we apply a quick(-and-ugly) fix, to get always the last `ContentChildren` element, it is OK.

It seems that `ContentChild` uses the first element, that is OK, but the elements are flatten in reverse order than they are in the DOM.

**What is the motivation / use case for changing the behavior?**

See the plnkr.

**Please tell us about your environment:**

* **Angular version:** 2.4.1

* **Browser:** [Chrome 55]

 
* **Language:** [all]

**Comment by vicb** [comment]
Should have been fixed with https://github.com/angular/angular/pull/13677 that will be part of the next release

**Comment by pesimeao** [comment]
Great! Thanks!
