### ISSUE TITLE
Template transclusion is evaluated in wrong moment

### ISSUE THREAD

**Issue by asfernandes** [angular/angular#13760]
```
[x] bug report => search github for a similar issue or PR before submitting
```

Version: 2.4.1

A component with selector parent-component has this:

```
<div *ngIf="false">
	<ng-content></ng-content>
</div>
```

And it is inserted in another template with:

```
<parent-component>
    some logic error inside this
</parent-component>
```

If there is no parent-component and the div with ngIf was just above the logic error, it would not be an error.

But with transclusion the error happens.

**Comment by DzmitryShylovich** [comment]
pls add a repro

**Comment by asfernandes** [comment]
Without transclusion (no error in console): https://plnkr.co/edit/sVpf4SQzmKUvSNjmXpPB?p=preview

With transclusion (error in console): https://plnkr.co/edit/DXVegsNrdzy2BU3L9pZi?p=preview

**Comment by EddyP23** [comment]
We are noticing same issue for V2.1.1. Weird how this didn't get noticed for that long.

**Comment by DzmitryShylovich** [comment]
> With transclusion (error in console): https://plnkr.co/edit/DXVegsNrdzy2BU3L9pZi?p=preview

but this error has nothing to do with transcription. You just need to use safe navigation operator because `x` doesn't exist https://plnkr.co/edit/vu1W7T02CSPKC1pgfHeb?p=preview

**Comment by DzmitryShylovich** [comment]
> Without transclusion (no error in console): https://plnkr.co/edit/sVpf4SQzmKUvSNjmXpPB?p=preview

doesn't throw an error because ngIf is false. If u change it to `true` it will throw the same error and required the same fix. To me it works as intended...

**Comment by asfernandes** [comment]
Perhaps you're right, because with https://plnkr.co/edit/Ejwvtf5CDhwG9qhG7sWt?p=preview I see it evaluating x.y to the App component. I just don't think it's obviously, but I see similar thing documented in another (vue) library.

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/guide/template-syntax.html#!#safe-navigation-operator

If u think docs can be improved pls open an issue on https://github.com/angular/angular.io/issues

> I see similar thing documented in another (vue) library.

link? (just interesting)

**Comment by DzmitryShylovich** [comment]
@asfernandes did u open an issues on the docs repo?
can this be closed?

**Comment by devoto13** [comment]
@asfernandes It's by design. See #13921.

@DzmitryShylovich I have created issue in docs repo, so this can be closed now.
