### ISSUE TITLE
feat(router): add paramsFromRoot getter

### ISSUE THREAD

**Issue by chajath** [angular/angular#13767]
This is a follow up to #12601. Basically, I'd like to find a way to have a flattened view of router params available to components so that each components need not know about how the router tree has been configured. See #12601 for an implementation idea.

**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**

Components would need to manually traverse the tree in order to find parameters defined in router tree.

**Expected behavior**

Components can now be incognizant of the router configuration when finding parameter values.

**What is the motivation / use case for changing the behavior?**

This helps the components consuming ActivatedRoute finding all the parameters defined in the
route, decoupling them from the knowledge of how nested routers are configured.

* **Angular version:** 2.0.X

**Comment by DzmitryShylovich** [comment]
Isn't it a duplicate of https://github.com/angular/angular/issues/11023?

**Comment by chajath** [comment]
I don't think so. This issue is more to do with components in children routers accessing parameters from parent routers.

**Comment by klinki** [comment]
I'm huge fan of this idea. I would love to see it implemented too. I think it would be great to have not just params, but also data inherited.

I already created similar issue for it some time ago https://github.com/angular/angular/issues/13058  but Angular team doesn't seem to be very happy about that idea so I never actually pursued it with implementation. Instead I'm working with some very ugly workarounds and I'm very angry about that.

**Comment by borislemke** [comment]
@klinki would to see this with `data`, like yourself I also opened an issue regarding accessing `data` from parent components as referenced here. Makes me wonder why not more people wanting this feature.

**Comment by klinki** [comment]
I don't know. That is a good question... But I'm also wondering why is Angular team so negative about that :( I think providing opt-in option to hierarchically resolve data wouldn't harm anyone and it would greatly improve Router experience...

**Comment by jeremyputeaux** [comment]
I also need this.

**Comment by trotyl** [comment]
Likely closed by #20678? You can just inherit all parameters and use proper param naming to avoid override.

**Comment by chajath** [comment]
Checked and confirmed that `paramsInheritanceStrategy: 'always'` does the trick. Closing this issue. Thanks!
