### ISSUE TITLE
Unsupported import syntax

### ISSUE THREAD

**Issue by goleary** [angular/angular#13768]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
when I try to run ngc on a file that includes this import syntax:
`import telemetry = microsoft.applications.telemetry;` I get an error that this syntax is not supported. 

**Expected behavior**
I expect this to compile with no issue just like tsc does.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Aliasing namespaces

**Please tell us about your environment:**
Windows npm

* **Angular version:** 2.0.X

 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   4.4.7

**Comment by vicb** [comment]
Is this allowed in ES6 ? http://www.ecma-international.org/ecma-262/6.0/#sec-imports

Please add a repro.

**Comment by martinmcwhorter** [comment]
Ya. A workaround is to just change it to

const telemetry = microsoft.applications.telemetry;

**Comment by goleary** [comment]
Do you still need repro?

Will use workaround for now.

**Comment by Toxicable** [comment]
@goleary can be closed? it's not a Angular issue

**Comment by goleary** [comment]
supported by typescript but not working in angular... seems like an angular Issue. Altho I haven't verified the issue is still present in the latest versions.

**Comment by martinmcwhorter** [comment]
Typescript does NOT support using es modules and internal modules at the same time.

**Comment by goleary** [comment]
interesting that this code was causing zero problems in a Typescript project that I have but when imported to an angular project the problem was encountered.

**Comment by martinmcwhorter** [comment]
Was the other TypeScript project using "internal modules", es modules or
CommonJS modules?

If the other project uses internal typescript modules, then that makes
complete sense. Angular uses es modules. You can't use internal modules in
a project that uses es modules.

Internal modules are just globally defined nested objects, so you can
access them without the import syntax using the method previously
described.

**Comment by DzmitryShylovich** [comment]
@goleary is this still valid in ng4?

**Comment by markDrigola** [comment]
This problem still exists in version 5.2...

**Comment by KingMario** [comment]
Is telemetry used in a decorator? If so, use const instead.

**Comment by JoostK** [comment]
The Ivy compiler no longer has a metadata collector that was prone to unsupported syntax issues, so closing as resolved.
