### ISSUE TITLE
Invalid provider for the NgModule 'DesktopModule' - only instances of Provider and Type are allowed, got: [AuthService, ?undefined?]

### ISSUE THREAD

**Issue by sharathgg5** [angular/angular#13769]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

here is my module below
`import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { HttpModule, JsonpModule   } from '@angular/http';

import 'rxjs/Rx';
import {
    DesktopComponent,
    AccountsLoginComponent,
    SkrivbordComponent,
    DesktopRoutingModule,   
    SidebarComponent,
    NavbarComponent,
    MainContentComponent
} from './utils/export-components.utils';

**import {
    AuthGuard,
    AuthService
} from './utils/export-services.utils';**

@NgModule({
    imports: [
        BrowserModule,
        ReactiveFormsModule,
        HttpModule,
        DesktopRoutingModule,
        JsonpModule
    ],
    declarations: [
        DesktopComponent, AccountsLoginComponent, SkrivbordComponent, SidebarComponent, NavbarComponent, MainContentComponent
    ],
    **providers: [AuthService, AuthGuard],**
    bootstrap: [DesktopComponent]
})
export class DesktopModule { }`

below is my export-service provider **export-services.utils'**
`
export { AuthGuard } from '../core/auth-guard.service';
export { AuthService } from '../core/auth.service';
`

below is my auth.guard service
`import { Injectable } from '@angular/core';
import {
    CanActivate, Router,
    ActivatedRouteSnapshot,
    RouterStateSnapshot,
    CanActivateChild,
    NavigationExtras,
    CanLoad, Route
} from '@angular/router';

//import { AuthService } from '../utils/export-services.utils';
**import { AuthService } from '../utils/export-services.utils';**

@Injectable()
export class AuthGuard implements CanActivate, CanActivateChild, CanLoad {

    constructor(private router: Router, private authService: AuthService ) { }

    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
        let url: string = state.url;
        console.log('AuthGuard canActivate for url ' + url);
        return this.checkLogin(url);
    }

    canActivateChild(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
        return this.canActivate(route, state);
    }

    canLoad(route: Route): boolean {
        let url = `/${route.path}`;
        console.log('AuthGuard canLoad for url ' + url);
        return this.checkLogin(url);
    }

    checkLogin(url: string): boolean {
        if (this.authService.checkLocal()) { return true; }

        // Navigate to the login page with extras
        this.router.navigate(['/Login']);
        return false;
    }
}`

**Expected behavior**
i'm getting error as below in console
> Invalid provider for the NgModule 'DesktopModule' - only instances of Provider and Type are allowed, got: [AuthService, ?undefined?]

what i'm actually trying is i'll import all the injectable service into one ts file **export-services.utils**  and export all those services from this file... check the bold text for reference

**What is the motivation / use case for changing the behavior?**
motivation is to keep the code clean. instead of make multiple references just import and export from one file.

**Please tell us about your environment:**
visual studio 2015 update 3. below is my package.json
`{
  "name": "Treserva-Desktop",
  "version": "1.0.0",
  "description": "Treserva-Desktop package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "pree2e": "webdriver-manager update",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",

    "angular-in-memory-web-api": "~0.2.2",
    "systemjs": "0.19.40",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.1",
    "zone.js": "^0.7.4"
  },
  "devDependencies": {
    "concurrently": "^3.1.0",
    "lite-server": "^2.2.2",
    "typescript": "~2.0.10",

    "canonical-path": "0.0.2",
    "http-server": "^0.9.0",
    "tslint": "^3.15.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",

    "@types/node": "^6.0.46",
    "@types/jasmine": "^2.5.36"
  },
  "repository": {}
}
`

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
