### ISSUE TITLE
Minifying HTML and JS files for production

### ISSUE THREAD

**Issue by sprakashg** [angular/angular#13772]
Hi Team,

I'm looking for some help, I have tried many repository's with regards to minifying the .js, .html, .css files for production. I have used angular1.4 version before and have deployed it onto production using node as web server, where I could use a config file for development, testing and production. I'm not sure how to do the same here, I tried with this enableProdMode() function. Please let me know how to deploy angular2 to production by minifying the js and html files

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
