### ISSUE TITLE
OpaqueToken cannot be used to setup a Router Guard

### ISSUE THREAD

**Issue by ribizli** [angular/angular#13774]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`TypeError: Cannot convert undefined or null to object` is thrown when OpaqueToken is used as token for CanActivate guard DI.

**Expected behavior**
Should work.
Workaround: using a class instead:
http://plnkr.co/edit/LOVP2Ah5Xm01MXAMnf1V?p=preview

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/s3fSpmDIIVCeWqSASkKJ?p=preview
Error on boostrap

**What is the motivation / use case for changing the behavior?**
OpaqueToken was intended to use for DI, but not working in this special case

**Please tell us about your environment:**

* **Angular version:** 2.4.1

* **Browser:** [ Chrome 55 ]
 
* **Language:** [TypeScript 2.X]

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. Luckily it has already been fixed https://github.com/angular/angular/issues/13565. Will be available in the next release

**Comment by matsko** [comment]
Closing this issue due to the comment above.
