### ISSUE TITLE
Should support es2015 object literal property value shorthand in literal bindings

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#13773]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`<cmp [exp]="{name}"></cmp>` throws an error

**Expected behavior**
`<cmp [exp]="{name}"></cmp>` should be equal to `<cmp [exp]="{name: name}"></cmp>`

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/ZJHsfAr1Gs4BZYYWAHvu?p=preview

**Comment by vicb** [comment]
dup of https://github.com/angular/angular/issues/10277

**Comment by DzmitryShylovich** [comment]
indeed
