### ISSUE TITLE
Feature Request: Binding to multiple class with either [class.---] or [ngClass]

### ISSUE THREAD

**Issue by dessalines** [angular/angular#13778]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

This is a very common case, that I want to bind multiple classes based on a single logical parameter. Currently I have to do something like:

```html
<i class="fa" [class.fa-search]="!loading" [class.fa-circle-o-notch]="loading" [class.fa-spin]="loading"></i>
```

It would be really nice to be able to do this with a comma : 

```html
<i class="fa" [class.fa-search]="!loading" [class.fa-circle-o-notch,class.fa-spin]="loading"></i>
```

**Comment by DzmitryShylovich** [comment]
`ngClass` already supports multiple classes

**Comment by dessalines** [comment]
how? This isn't shown in any of the following docs:

https://angular.io/docs/ts/latest/guide/cheatsheet.html
https://angular.io/docs/ts/latest/api/common/index/NgClass-directive.html

**Comment by DzmitryShylovich** [comment]
```
<some-element [ngClass]="{'first': true, 'second': true, 'third': false}">...</some-element>
```

**Comment by dessalines** [comment]
That's exactly what I'm trying to avoid. I'd prefer something like:

`<some-element [ngClass]="{'first,second': true, 'third': false}">...</some-element>`

**Comment by DzmitryShylovich** [comment]
then create your own directive...

**Comment by dessalines** [comment]
@vicb is this a dupe or something? Why close this?

**Comment by ericmartinezr** [comment]
`[ngClass]="{'class1 class2 class3' : true}"`

**Comment by dessalines** [comment]
Oh sweet, thanks @ericmartinezr ! Where did you find this, or where are the docs for it?

**Comment by DzmitryShylovich** [comment]
@ericmartinezr thx

@dessalines will add an example in the docs https://github.com/angular/angular/pull/13779
