### ISSUE TITLE
*ngIf is not working when used inside a template tag.

### ISSUE THREAD

**Issue by viveksingh03** [angular/angular#13771]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We are using *ngIf inside the template tag after that if we fire a click event from inside the template control then the HTML inside the template gets deleted.

**Expected behavior**
Events fired from inside the template should not get deleted. It was working perfectly in Angular 2 rc 4.

**Minimal reproduction of the problem with instructions**

Please see the http://plnkr.co/edit/XHZz52?p=preview for mentioned issues.

- This a repeater component I am using for iterating it through data, once open please click on any of the list item for more clarity

@Component({
  selector: 'my-app',
  template: `
            <repeater [source]="dllApprovalStatus">
              <template let-data="item">
                  <p *ngIf='data.name==1' (click)='myclick(data.name)'> Your Name</p>
              </template>
            <repeater>`
})
export class AppComponent {

  dllApprovalStatus: any = [{ name: 1 }, { name: 1 }, { name: 0 }];
  myclick(data: any) {
    alert(data);
  }
}
- This is my main component .

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Visual Studio Code - using IIS as a Server.

* **Angular version:** ~2.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr

**Comment by viveksingh03** [comment]
@DzmitryShylovich I have added a plnkr  please have a look.

**Comment by DzmitryShylovich** [comment]
@viveksingh03 thx. Pls add steps to reproduce and what is the expected behavior.

**Comment by DzmitryShylovich** [comment]
@viveksingh03 what is the expected behavior in your plunkr?

**Comment by Toxicable** [comment]
@viveksingh03 can you explain what the plunkr is showing
