### ISSUE TITLE
Change ViewContainer to use move instead of insert/detach

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1377]
Right now,
`ViewContainer` has the methods `create`, `insert`, `detach` and `remove`. With this, a user can create a view, detach it, keep it around, and the insert it later. However, the user could also forget to destroy it. 

To prevent these kinds of errors, we probably want a `move` operation that replaces the `insert` and `detach` operations in a ViewContainer.

Regarding implementation:
The implementation of `for` directive and injector `query` feature needs to be changed to use move instead of detach/insert. For this, it would be nice if change detection would not report changes to collections in the form previous index / new index, but rather in the form of operations to perform on the original collection to get to the new collection (e.g. splices, see [Array.observe](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/observe)).

**Comment by tbosch** [comment]
Another approach:

ViewCobtainer moves

Add a `bulkMove` method: Gets records with from, to positions
- No from->  create, no to -> delete

Impl: create a temporary new array that may contain nulls while the move is executed 

With this, we don't need to change change detection, but still have an atomic operation, and it should be fast.

**Comment by mhevery** [comment]
related: https://github.com/angular/angular/issues/3442

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
