### ISSUE TITLE
AoT supporting manipulation of metadata (e.g. through decorators)

### ISSUE THREAD

**Issue by staeke** [angular/angular#13777]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It's unclear whether this is a bug or a feature request. Thus I marked both.

We currently use a lot of decorators to modify dependencies for components. We have also experimented with modifying the metadata of `@Component`, e.g. by looking up using `Reflect` style API:s, or accessing our own wrapped version, e.g. `@MyComponent(...)`. Unfortunately, none of these approaches seem to work in AoT compilation mode, which is a bummer and a surprising finding. You would principall want JiT and AoT to be the same functionality wise.

**Expected behavior**
This is a trivial example, but I'd expect this to work in AoT mode

```typescript
export function MyComponent(...args) {
    return Component(...args);
}

@MyComponent({
    selector: 'my-app',
    templateUrl: 'app.component.html'
})
export class AppComponent {
}
```

Is it the case that `ngc` relies on static analysis? That sounds brittle. Wouldn't it be better to actually import the components server side and analyze meta data? Although, of course, that risks code to be run with client-only dependencies or potential side effects. Hmmm...hard.

Maybe some kind of plugin system to ngc?

**Minimal reproduction of the problem with instructions**
It's hard to create a plunkr for this, but I think you get the gist

**What is the motivation / use case for changing the behavior?**
- It allows for less differences between different ways of running Angular, which means less hurdles, time spent fighting a framework.
- It allows for using decorators creatively to separate out different concerns to utility decorators (or similar)

**Please tell us about your environment:**
OSX

* **Angular version:** 
2.4.1
 
* **Language:**
Typescript 2.0.10 (higher doesn't work with `ngc` as of now)

* **Node (for AoT issues):**
6.6.0

**Comment by DzmitryShylovich** [comment]
What are u doing inside your custom decorators? Doesn't inheritance addresses your issues?

**Comment by martinmcwhorter** [comment]
I wonder if all angular decorators should be converted to annotations, get rid of Metadata for JiT,  so that the behavior is consistent.

**Comment by staeke** [comment]
@DzmitryShylovich We  have some debugging decorators for components that needs `ElementRef` references to interact with highlighting in the DOM. They run conditionally as well depending on runtime settings. We also have auto subscribe decorators (much like the `async` pipe), that sets up a dependency, a subscription on an observable property and tears down that description. Furthermore, we have decorators that automatically emits events based on existing properties and when they're sent. These decorators depend on custom services (typically specified to the decorator), `ElementRef`, `ChangeDetectorRef`, `ApplicationRef`, but possibly more. Sure, you could specify all dependencies everywhere, but it's tedious and not good separation of concerns when you want to introduce new functionality in one of those decorators that need a new dependency.

The thing about inheritance is that the whole idea with decorators is ruined - instead of having a neatly separated system where each thing does one thing, combined dependencies spill down to the component's constructor. If you have a base component that always wants everything, every sub component you write will need to pass all the references up to the super component. If/when our super base component introduces new functionality all sub components would have to be updated, which is...well...not optimal.

**Comment by trotyl** [comment]
Superseded by https://github.com/angular/angular/issues/23264
