### ISSUE TITLE
Router tries to resolve values of data object attached to route

### ISSUE THREAD

**Issue by iexela** [angular/angular#13784]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have updated angular version from 2.2.3 to 2.4.1 and angular router version from 3.2.3 to 3.4.1.
Now router has the problem in treatment of data attached to route. It handles correctly blank and primitive values, arrays and plain objects:
```javascript
data: {
  stringValue: "abc",
  arrayOfValues: ["abc", "def"],
  objectOfValues: {
    "abc": "abc",
    "def": "def"
  }
}
```
But if value is not one of above types, router considers it as token defining angular dependency and tries to load this dependency.
Look at the example below

**Expected behavior**
I expect that route should allow to attach data of any nature including object created by custom function.
In the version 2.2.3 (3.2.3) there was no such problem.

**Minimal reproduction of the problem with instructions**
1. Developer defines route like 
```javascript
{
  component: OfficeRolesPageComponent,
  path: "office-roles",
  data: {
    permission: new Permission("OFFICE_ROLES#EDIT")
  }
}
```
2. `Permission` is a function like
```javascript
function Permission(name) {
  this.name = name;
}
```
3. In this case router considers instance of permission as token defining angular dependency and tries to resolve it. Angular raises an exception correspondingly, because there is no provider for this value.

**What is the motivation / use case for changing the behavior?**
I believe that router should allow to attach data of any nature as it was before.

**Please tell us about your environment:**
Windows 10, WebStorm 2016.3.2, webpack-2.1.0-beta.25, webpack-dev-server-2.1.0-beta.10

* **Angular version:** 2.4.1

* **Browser:** all

* **Language:** TypeScript 2.1.4

* **Node (for AoT issues):** `node --version` =  v6.9.1

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr

**Comment by DzmitryShylovich** [comment]
do u have this error https://github.com/angular/angular/issues/13565 ?

**Comment by DzmitryShylovich** [comment]
yeap, it will be available in the next release

**Comment by matsko** [comment]
@iexela given that https://github.com/angular/angular/issues/13565 has been submitted will be apart of 2.4.2/4.0.0-beta.2 this issue can be closed. Please reopen if it still doesn't work when those releases are out.
