### ISSUE TITLE
Prevent strange behavior 

### ISSUE THREAD

**Issue by montella1507** [angular/angular#13782]
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[ ] support request 

**Current behavior**
Angular 2 has serious problems in IE11 after version 2.2.0 when Pace.js is used. Application works most time totally incorrectly, sometimes works correctly like there is a race condition or something.  

I have creates several issues previously:
https://github.com/angular/angular/issues/13302
https://github.com/angular/angular/issues/13285
Where i was pretty annoying.

After 30 hours of debugging and trying to produce minimal reproduction of the problems i find out the problem was **Pace.js** - https://github.com/HubSpot/pace/blob/master/pace.js 
included in angular-cli.json. If i use Pace.js, even the validation in very primitive form doesnt work correctly. 

**Motivation**
It took long time to find out whats the cause of my problems, because from my POV, there was not any mistake in the code and there was not any error in the IE11 console. I have tried everything - different IE shims, exclude all NG2 compatible 3rd party libraries from my solutin, etc. 

I was very demotivated and hopeless. So it would be very nice, if you could explain whats the concrete problem with usage NG2 + pace.js at the same time. Maybe there is  a way how to prevent mysteries like this? My first idea is that Pace.js "over-monkeypatch" NgZone somewhere? 

**Versions:**
angular-cli: 1.0.0-beta.24
node: 6.7.0
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

**Browser** 
Internet Explorer 11 
 
**Language**
Typescript

**Comment by matsko** [comment]
Sorry to hear that things are not working as expected. @IgorMinar is looking into https://github.com/angular/angular/issues/13152 to see if it is related to what's going on here.

**Comment by DzmitryShylovich** [comment]
> @IgorMinar is looking into #13152 to see if it is related to what's going on here.

don't think it's related. plunkr template doesn't work in ie because it's missing a shim. I already submitted a pr to fix it https://github.com/angular/angular/pull/13783

**Comment by montella1507** [comment]
@matsko  i think the problem is not directly in angular, but there may be  a way how to prevent those problems (conflicts) with commonly used 3rd party libraries..?

I think the strange problems could be caused because of this part:

`equestAnimationFrame = window.requestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.msRequestAnimationFrame;

  cancelAnimationFrame = window.cancelAnimationFrame || window.mozCancelAnimationFrame;

  if (requestAnimationFrame == null) {
    requestAnimationFrame = function(fn) {
      return setTimeout(fn, 50);
    };
    cancelAnimationFrame = function(id) {
      return clearTimeout(id);
    };
  }
`
in Pace.js but ONLY after version 2.2.0:
https://github.com/angular/angular/compare/2.2.0-rc.0...2.2.0
so it may be related to Animation / Rendering changes ? 
 
The main reason for this issue of mine is to prevent the users of living in shadows like i was during debugging those issues :-)

**Comment by DzmitryShylovich** [comment]
@montella1507 pls add small repro otherwise I don't see what we can do with it

**Comment by DzmitryShylovich** [comment]
@montella1507 did you fix it? 
If not pls add a plunkr with repro. Otherwise it's not actionable and will be closed.
