### ISSUE TITLE
Nested attribute translation in a translation not applied

### ISSUE THREAD

**Issue by LeResKP** [angular/angular#13796]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the following example: `<ng-container i18n>I don't output <a i18n-title title="Angular 2 logo">any element</a></ng-container>`

The translation of title is not applied. If I remove the i18n from the ng-container it works.

**Expected behavior**
The translation on i18n-title should be applied

**Minimal reproduction of the problem with instructions**
I adjusted the plnkr from the i18n doc:
https://plnkr.co/edit/8P92XurVX81eqUoeFfUx?p=preview

**What is the motivation / use case for changing the behavior?**
I need to translate the attributes

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 52.0.2743.82 (64-bit)

**Comment by matsko** [comment]
Closed by https://github.com/angular/angular/commit/424e6c4cb9f01114307d970c1ba75c4839665f8e

**Comment by phoenixking25** [comment]
Still facing this issue! Any solution?
