### ISSUE TITLE
AsyncPipe cannot be injected (into a pipe)

### ISSUE THREAD

**Issue by zorec** [angular/angular#13799]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

 An application cannot be bootstrapped, only white screen with "loading" is displayed. There is an error in the console "No provider for ChangeDetectorRef!".
It is caused by `AsyncPipe` which was injected (into another pipe) and declared in providers on a module. 
The only workaround I found was to declare pipes ONLY in a component since ChangeDetectorRef` is available there.

**Expected behavior**

It should be possible to declare `AsyncPipe` in providers array on a module so that it can be injected everywhere. Other pipes (e.g. DatePipe) can be injected like this.   

**Minimal reproduction of the problem with instructions**
Steps to reproduce: 

1. inject `AsyncPipe` to another pipe or a service
1. declare `AsyncPipe` in providers on a module

Plunker with minimal reproduction: http://plnkr.co/edit/5Q1X7PwcCGhPv1yutLgk?p=preview

**What is the motivation / use case for changing the behavior?**

In the plunker, I demonstrated one use case. There is `TranslatePipe` which translates a string by executing a server request. I would like to reuse the functionality of AsyncPipe in order to display resolved value of server request.  

**Please tell us about your environment:**

angular-cli: 1.0.0-beta.24
node: 6.4.0
os: linux x64

* **Angular version:** 2.4.1

* **Browser:** all

 
* **Language:** [TypeScript 2.0.3]

**Comment by DzmitryShylovich** [comment]
why did u inject it if u can just pipe chain them `data | async | translate`?

**Comment by DzmitryShylovich** [comment]
anyway there's no issue here. ChangeDetectorRef is bound to a component instance.

http://plnkr.co/edit/Bpp0YDLurx4JrtUxYqyl?p=preview

**Comment by zorec** [comment]
@DzmitryShylovich Thank you for the solving the issue in the Plunker. 

> why did u inject it if u can just pipe chain them data | async | translate?

Chaining would be in my real use case very cumbersome. I think that having a pipe that must be used in combination is almost an anti-pattern. 

Using `viewProviders` works for me so feel free to close the issue. Let me just point out that it does not allow injecting async pipe into another service although that's probably very rare.

**Comment by DzmitryShylovich** [comment]
> Let me just point out that it does not allow injecting async pipe into another service although that's probably very rare.

yes, because
> ChangeDetectorRef is bound to a component instance.

> feel free to close the issue

u can close it yourself :)
