### ISSUE TITLE
To navigate to '/' in canActivate might fail

### ISSUE THREAD

**Issue by JoniJnm** [angular/angular#13793]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If a route has a canActive provider which returns false and navigate to '/', the `'HomeComponent'` is not displayed. The problem doesn't occurs when the canActive navigate to a path that is not '/' (f.e: '/login')

My real problem
* an user has permissions to navigate to a custom path
* the user go to the path
* the user copy the URL
* the user lost the session
* the user paste the URL and navigate
* If the canActivate returns false and goes to '/', it fails. If it goes to '/login' it works.

**Expected behavior**
Display the `'HomeComponent'` in the router-outlet

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/qXH60zedNRpRUp0nHQxO?p=preview

* **Angular version:** 2.4.1
* **Browser:** Chrome
* **Language:** TypeScript 2.0

**Comment by DzmitryShylovich** [comment]
Looks like duplicate of https://github.com/angular/angular/issues/13530

**Comment by nertzy** [comment]
Seems like the same thing as #13530

**Comment by JoniJnm** [comment]
Duplicated #13530
