### ISSUE TITLE
Navigate method of router not working in root component

### ISSUE THREAD

**Issue by maxime-menard** [angular/angular#13795]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I use the method navigate of the router in the ngOnInit method of the root component, nothing happens. Same code is working fine in a child component.

**Expected behavior**
Should work on both root and child component.

**Minimal reproduction of the problem with instructions**

```
export class AppComponent implements OnInit {

  displayComponent: string;

  constructor(private router: Router, private elm: ElementRef) {
    this.displayComponent = elm.nativeElement.getAttribute('displayComponent');
  }

  ngOnInit(): void {
    // not working
    this.router.navigate([this.displayComponent]);
  }
}
```

**What is the motivation / use case for changing the behavior?**
Display dynamically a component by using the router on the root component

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.X
~2.4.0

* **Browser:** all
 
* **Language:**
"typescript": "~2.0.10"

* **Node (for AoT issues):** `node --version` =   v6.5.0

**Comment by DzmitryShylovich** [comment]
Workaround is to use `setTimeout(() => this.router.navigate(['comp2']));` to delay navigation

**Comment by maxime-menard** [comment]
Perfect, thanks !

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/12162#issuecomment-253370704 possible solution

**Comment by DzmitryShylovich** [comment]
@maxime-menard there's an option to disable initial navigation: `{useHash: true, initialNavigation: false}`. Then it will work as expected
https://plnkr.co/edit/DpELaS6ulYkjcbYKLM7R?p=preview

@vicb This should be labeled as a docs issue I think
