### ISSUE TITLE
Get reliable numbers on minified/compiled Angular size

### ISSUE THREAD

**Issue by mprobst** [angular/angular#1379]
We currently don't really have a good overview on this.

@rkirov @tbosch, maybe something for one of you? @tbosch, could we track this as a statistic over time?

**Comment by pkozlowski-opensource** [comment]
Some number available here: http://pkozlowski-opensource.github.io/ng2-code-size/
This shows weight distribution across different ng2 components.

**Comment by IgorMinar** [comment]
We started tracking the size with #5294

**Comment by IgorMinar** [comment]
sample: ![screen shot 2015-12-01 at 3 36 28 pm](https://cloud.githubusercontent.com/assets/216296/11517870/73fe9f0a-9841-11e5-9a48-ca2f399c21be.png)

**Comment by IgorMinar** [comment]
Less confusing graph:

<img width="1615" alt="screen shot 2015-12-01 at 5 06 56 pm" src="https://cloud.githubusercontent.com/assets/216296/11519307/f84f0bda-984d-11e5-9484-c27d646bdf91.png">
