### ISSUE TITLE
Reactive Form change through ControlValueAccessor doesn't update view

### ISSUE THREAD

**Issue by tiagoroldao** [angular/angular#13792]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When updating a value through a form field that uses the formControl directive, the view isn't updated. When, say, two fields hold the same form control, changing one does NOT change the other.

This **does happen** when using NgModel, and **does happen** when calling `formControl.setValue(newVal)`

**Expected behavior**
Behaviour is expected to be the same in NgModel as when using Reactive FormControls

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/LXyo6uHdbEpP3feudYoo?p=preview

**What is the motivation / use case for changing the behavior?**
The contract custom form fields have when using the `ControlValueAccessor` interface is broken. A good example is http://valor-software.com/ng2-bootstrap/#/buttons#radio - which works currently only with NgModel, as it requires updating the view on all relevant buttons on value change.

When using a set of buttons with reactive forms, currently, a `(click)` based hack needs to be put in place:

```html
<div class="btn-group">
    <label 
        class="btn btn-primary" 
        formControlName="privateApplication"
        (click)="form.get('privateApplication').setValue(false)"
        [btnRadio]="false">
            {{'LABEL_PUBLIC' | translate}}
    </label>
    <label 
        class="btn btn-primary" 
        formControlName="privateApplication" 
        (click)="form.get('privateApplication').setValue(true)"
        [btnRadio]="true">
            {{'LABEL_PRIVATE' | translate}}
    </label>
</div>
```
**Please tell us about your environment:**
OS Not relevant

* **Angular version:** 2.4.1

* **Browser:** Chrome 55

* **Language:** TypeScript 2

**Comment by nickiewooster** [comment]
I have the exact same problem
let say i have:
{{data}}
<custom-a [(ngModel)]="data"></custom-a>
<custom-b [ngModel]="data"></custom-b>

changes made in custom-a and custom-b will update data but changes made in each of them will not propagate to the other unless its clicked (OnPush) or 1 cycle late (Default)

Is this expected or i'm missing something here ?

**Comment by Toxicable** [comment]
Can you recheck this on the latest version, all appears to be working fine for me

**Comment by tiagoroldao** [comment]
The plunker is up to date (2.4.9) and still displays issue - are you saying you don't see issue in the plunker?

**Comment by Toxicable** [comment]
@tiagoroldao what is meant to happen? I click the ngmodel button and the 2 inputs + 1 label.
I click the Update Field button and it's 2 inputs change along with it's label, without moving my mouse or causing any other forms of CD

**Comment by tiagoroldao** [comment]
@Toxicable summing it up:
Top (correct) form using `[(ngModel)]`:
- changing any field updates the model and the other field, which shares value
- clicking the button changes model and both fields

Bottom (buggy) form using `formControlName`:
- changing any field updates the model **but not the other field**, which **should** share value
- clicking the button changes model and both fields

**Comment by Toxicable** [comment]
Sorry, ignore the above. I reread your issue see whats going on here, I don't know the inner workings overly well but it looks to me like a limitation of Reactive Forms currently not necessarily a bug. Maybe opening a Feature request for this after checking if there isn't one already

**Comment by tiagoroldao** [comment]
I do see it as a bug - when updating the reactive formControl through the directive, it specifically updates it without updating views (I'm thinking it assumes it isn't needed as it came from the view, but it doesn't account for multiple uses of the same formControl)

The culprit is here:
https://github.com/angular/angular/blob/551fe50ebd8d15237bfeb13892e9f39eca11c72f/modules/%40angular/forms/src/directives/shared.ts#L46

Although I don't know the full performance implications of removing `emitModelToViewChange: false`

**Comment by tiagoroldao** [comment]
By the way, the problem is fixed by removing the assumption that the views do not need to be updated when a change comes from view to model. Fixed here:
http://plnkr.co/edit/b7u3XWg1tFIsWTpAvQdH?p=preview 

Still I can't presume to know the implications of this. @DzmitryShylovich who could verify this?

**Comment by Ledzz** [comment]
For thost who came from google with this issue, there's a workaround that saved me:
```
control.valueChanges.subscribe(e => {
    control.setValue(e, {emitEvent: false});
});
```

**Comment by mlb6** [comment]
Facing the same issue. Thank you @Ledzz for the workaround.

**Comment by mmmichl** [comment]
@Ledzz solution works, but be aware of the jumping cursor in IE11:
![ie11-typing](https://user-images.githubusercontent.com/1167451/32340852-074c2d0c-bffc-11e7-9eeb-f1271df98562.gif)
Try it: https://plnkr.co/edit/ilRx7V7VfNbzgB2lqC1v?p=preview

I need a input field and a select to work on the same control. Following workaround worked for me:
```html
<form [formGroup]="form">
  <input type="text" formControlName="bewarage">
  <select formControlName="bewarage" #s
      [value]="form.get('bewarage').value"
      (change)="form.get('bewarage').setValue(s.value, {emitEvent: false})">
    <option *ngFor="let b of bewarages" value="{{b}}">{{b}}</option>
  </select>
</form>
```
try it: https://plnkr.co/edit/WaLHOlcNAVbSAH8m0a7o?p=preview


On topic: In my opinion this is an unexpected behaviour, so I see it as a bug not a missing feature.

**Comment by johannesjo** [comment]
No news in this one?

**Comment by FabienInan** [comment]
Thanks for the solution. But i hope this bug fixed soon.

**Comment by orasestravis** [comment]
I'm having the same problem. The workaround from @Ledzz does not work for me. I also tried calling ChangeDetectorRef.detectChanges() in my controller, but that doesn't help either.

**Comment by seth-git** [comment]
I'm having the same problem. When I do this from my controller:
```
this.myform.setValue({
	someLabel: somevalue
});
```
With this template:
```
<form [formGroup]="myform" novalidate>
   <custom-component formControlName="someLabel"></custom-component>
</form>
```
My custom component that implements ControlValueAccessor, never gets the new value passed to it's writeValue method. There appear to be no workarounds.

**Comment by simeyla** [comment]
If you only have a subset of form fields you know to be 'duplicated' you're slightly better off using `patchValue` instead.

     this.addressForm.valueChanges.subscribe((data) => {
            this.addressEditForm.patchValue({ firstName: data.firstName, lastName: data.lastName }, { emitEvent: false });
      });

This will probably mitigate issues with browser controls quirks such as the above mentioned IE11 issue.

Still strikes me as bizarre this is the 'by design' behavior. I suppose it is a performance issue. Everything in angular magically binds - except for the simplest forms :-/

**Comment by jayordway** [comment]
I have the same problem as well. Both setValue doesn't cause a change nor is valueChanges firing when values are set.

**Comment by mohamed-gara** [comment]
There is a subtle difference between the template driven and reactive versions:

- In the reactive version, there is a **single** FormControl object.
- But in the template driven version there are **two** FormControl objects

**Comment by mlc-mlapis** [comment]
... the problem is still valid for Angular 5.2.4 https://stackblitz.com/edit/mlc-two-inputs-same-formcontrol?file=app%2Fapp.component.html

**Comment by mohamed-gara** [comment]
There are two points to note about the following code: http://plnkr.co/edit/LXyo6uHdbEpP3feudYoo?p=preview

First, it's worth to say that in this example: there is a subtle difference between the template driven and reactive versions:
- In the reactive version, there is a single FormControl object.
- But in the template driven version there are two FormControl objects.

We can avoid this difference by wrapping the inputs in a form.

Second, the two versions (template driven and reactive) are not really equivalent. And the problem (if it's really a problem), exists also in the template driven forms as in the reactive ones. Here http://plnkr.co/edit/mPDLG7MZlp6KRvkYBN89?p=preview I give the equivalent reactive version of the template driven one and the template driven version equivalent to the reactive one.

**Comment by HelloPb** [comment]
This problem still exist. No fix from angular yet

**Comment by sayax** [comment]
If you have any solution please share, i have the same issue with custom checkbox, currently using formcontrolname with input to update which is not the best practice

**Comment by HelloPb** [comment]
I am doing this way to solve the issue.  Its working

import { Component, OnInit, Input, forwardRef, Self, Optional } from '@angular/core';
import { NG_VALUE_ACCESSOR, NG_VALIDATORS, ControlValueAccessor, NgControl, FormControl, Validator } from '@angular/forms';

@Component({
  selector: 'abc-radio',
  templateUrl: './radio.component.html',
  styleUrls: ['./radio.component.scss']
})
export class RadioComponent implements OnInit, ControlValueAccessor {

  @Input() label = '';
  @Input() value: any;

  public selected = false;
  public disabled = false;

  constructor(public ngControl: NgControl) {
    if (this.ngControl != null) { this.ngControl.valueAccessor = this; }
  }

  private propagateChange = (_: any) => { };

  public toggle(): void {
    if (!this.disabled) {
      this.selected = true;
      this.propagateChange(this.value);
      this.ngControl.control.setValue(this.value);
    }
  }

  private update(value: any): void {
    if (value === this.value) {
      this.selected = true;
    } else {
      this.selected = false;
    }
  }

  public writeValue(value: any): void {
    this.update(value);
  }

  public registerOnChange(fn: any): void {
    this.propagateChange = fn;
  }

  public registerOnTouched(fn: any): void {
  }

  public setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }

  public ngOnInit(): void {
    this.ngControl.control.valueChanges.subscribe(v => {
      this.update(v);
    });
  }
}

**Comment by sayax** [comment]
Well i have a working solution but it requires some input directives, however i wanna do it without the help of inputs only using formcontrolname

**Comment by seth-git** [comment]
This worked for me for both a reactive form and a non-reactive one:
```
import {ChangeDetectionStrategy, ChangeDetectorRef, Component, forwardRef, Input} from "@angular/core";
import {Observable} from "rxjs/Observable";
import {ControlValueAccessor, NG_VALUE_ACCESSOR} from "@angular/forms";
...

@Component({
	selector: 'my-select',
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: './outcome-select.template.html',
	styleUrls: ['./outcome-select.scss'],
	providers: [
		{
			provide: NG_VALUE_ACCESSOR,
			useExisting: forwardRef(() => OutcomeSelectComponent),
			multi: true
		}
	]
})
export class OutcomeSelectComponent implements ControlValueAccessor {
	// For more on the style of this component, see: https://alligator.io/angular/custom-form-control/
	@Input() isRequired: boolean;
	@Input() noSelectionText: string;
	@Input('value') _value: number; // outcome id
	onChange: any = () => { };
	onTouched: any = () => { };

	options$: Observable<OutcomeOption[]>;

	get value(): number {
		return this._value;
	}

	set value(val: number) {
		this._value = val;
		this.onChange(val);
		this.onTouched();
		this.cd.detectChanges();
	}

	constructor(
		private cd: ChangeDetectorRef
	) {
		this.options$ = Observable.of([
			{
				name:'Option 1',
				id: 1
			}, {
				name: 'Option 2',
				id: 2
			}
		]);
	}

	registerOnChange(fn) {
		this.onChange = fn;
	}

	registerOnTouched(fn) {
		this.onTouched = fn;
	}

	writeValue(value: number) {
		this.value = value;
	}
}
```
The template looks like this:
```
<select
		[required]="isRequired"
		[(ngModel)]="value">
	<option value="" [disabled]="isRequired">{{ noSelectionText }}</option>
	<option [ngValue]="opt.id" *ngFor="let opt of (options$ | async)">{{opt.name}}</option>
</select>
```

**Comment by pogiaron** [comment]
I use a painful hack, maybe you cant use this solution always, I don't know.
**template:**
`<input type="text" (input)="inputEventHandler($event)" #tstInput >`
**component:**
`@ViewChild('tstInput ') tstInput;`
```
writeValue(value: any) {
    if (!value) {
      this.tstInput.nativeElement.value = null;
    } else {
      this.tstInput.nativeElement.value = value;
    }
}
```

**Comment by slavafomin** [comment]
I'm experiencing the same issue with the latest Angular. Is this by design? Should the `formControlName` directive be used only for a single element (i.e. one-to-one and not one-to-many)?

**Comment by satbir90** [comment]
Please try this.
It worked for me
this.formGroup.patchValue(this.formGroup.value);
Its just a workaround.

**Comment by AstRonin** [comment]
unfortunately without positive effects

**Comment by BenceUszkai** [comment]
@AstRonin any update?

**Comment by arangates** [comment]
i confirm this it is still present in Angular v6.1.9 as well

**Comment by kirill-galushko** [comment]
Still, have this bug

**Comment by maxime1992** [comment]
Thought I was really missing something in my app... And decided to make a [small repro](https://stackblitz.com/edit/angular-qt5g14?file=src%2Fapp%2Fapp.component.html) before going insane.

Turns out it's a real issue.

If anyone ask for a use case, just imagine a color picker, like the one integrated in Chrome debug tool.

![image](https://user-images.githubusercontent.com/4950209/49887542-8f41aa80-fe34-11e8-924e-719b9740a586.png)

You can either change the color from the input or change it from the color palette. Both are same `formControlName` but with different display :man_shrugging:

**Comment by leye0** [comment]
I have a lot of nested FormGroup, FormArray and FormControl in an app, that I define dynamically (probably before the view HTML is generated), since this is one of the Reactive Form purpose.

Within the AbstractControl hierarchy, all values are properly set (myForm.controls[0].controls[1].controls['myCheckbox']), but the parent value itself (myForm.value.0.1.myCheckbox) is just -never- updated.

**Comment by rivanovuic** [comment]
Happened to me when I had the following in the `NG_CONTROL_VALUE_ACCESSOR`:

![image](https://user-images.githubusercontent.com/43039094/53770375-72050100-3ea4-11e9-9fe1-b5fd76da6756.png)

commenting out the `.reset()` code solved it

**Comment by AstRonin** [comment]
7.2.6 the same...

**Comment by Buttars** [comment]
This needs some serious looking. Is there any update on whether or not this is being looked into?

**Comment by debuggerpk** [comment]
still present with 7.3.4

**Comment by mistic100** [comment]
Hello ? Can you fix major 2 years old bugs ?  
This is a total blocker when implementing custom form component.

**Comment by marco6** [comment]
I was going mad about this until I found this issue that confirmed I am not (yet) crazy.

Still a problem in angular 8. I think the only way to get around this proble is to directly manipulate the underlying dom as I did: https://angular-e273lz.stackblitz.io

**Comment by madmiki80** [comment]
@marco6 still have the same problem.... this bug is still not closed :(
could you give me access to your example? ty

**Comment by eamador** [comment]
> @marco6 still have the same problem.... this bug is still not closed :(
> could you give me access to your example? ty

The @marco6 example can be found at https://stackblitz.com/edit/angular-e273lz

**Comment by yulianovdey** [comment]
+1

**Comment by anodynos** [comment]
A workaround I found for a checkbox, without involving timeouts etc, is to use `nativeElement.value` instead of `nativeElement.checked`. 

The code that worked: 
```
public writeValue(value: boolean): void {   
    this.checkbox.nativeElement.value = value;
  }
```

The code that was not updating the UI (unless some other component was updating), although all the form patching and events were fired properly: 
```
public writeValue(value: boolean): void {   
    this.checkbox.nativeElement.checked = value;
  }
```

**Comment by vijender1256** [comment]
Still same issue, anyone figured out the solution.

**Comment by JoepKockelkorn** [comment]
This is not a bug. When changing a class variable via the writeValue method it is a change which is not detected via zone.js or via an Input change. You need to manually trigger the ChangeDetectorRef detectChanges method to let Angular synchronize the class's instance properties with the DOM, or use the Renderer2 to change the native element value manually as [stated in the docs](https://angular.io/api/forms/ControlValueAccessor#writevalue) .

**Comment by RicardoVaranda** [comment]
@JoepKockelkorn 

What would it look like for a radio button though? That seems fine if it's a static component not one generated dynamically.

**Comment by JoepKockelkorn** [comment]
> @JoepKockelkorn
> 
> What would it look like for a radio button though? That seems fine if it's a static component not one generated dynamically.

@RicardoVaranda Do you have an example stackblitz?

**Comment by chrisv2** [comment]
Just a little heads up for folks like me who also might fall to this:

When calling `setValue` on a radiobutton or select, make sure set the value as string, e.g.

```html
<input [formControl]="myFormCtrl" type="radio" name="variant" value="1">
<input [formControl]="myFormCtrl" type="radio" name="variant" value="2">
```

```javascript
// this doesn't work
this.myFormCtrl.setValue(2);
// this works
this.myFormCtrl.setValue("2");
```

**Comment by slavafomin** [comment]
@chrisv2 Have you tried setting it this way?

`<input [formControl]="myFormCtrl" type="radio" name="variant" [value]="1">`

**Comment by nguyenbathanh** [comment]
> This worked for me for both a reactive form and a non-reactive one:
> 
> ```
> import {ChangeDetectionStrategy, ChangeDetectorRef, Component, forwardRef, Input} from "@angular/core";
> import {Observable} from "rxjs/Observable";
> import {ControlValueAccessor, NG_VALUE_ACCESSOR} from "@angular/forms";
> ...
> 
> @Component({
> 	selector: 'my-select',
> 	changeDetection: ChangeDetectionStrategy.OnPush,
> 	templateUrl: './outcome-select.template.html',
> 	styleUrls: ['./outcome-select.scss'],
> 	providers: [
> 		{
> 			provide: NG_VALUE_ACCESSOR,
> 			useExisting: forwardRef(() => OutcomeSelectComponent),
> 			multi: true
> 		}
> 	]
> })
> export class OutcomeSelectComponent implements ControlValueAccessor {
> 	// For more on the style of this component, see: https://alligator.io/angular/custom-form-control/
> 	@Input() isRequired: boolean;
> 	@Input() noSelectionText: string;
> 	@Input('value') _value: number; // outcome id
> 	onChange: any = () => { };
> 	onTouched: any = () => { };
> 
> 	options$: Observable<OutcomeOption[]>;
> 
> 	get value(): number {
> 		return this._value;
> 	}
> 
> 	set value(val: number) {
> 		this._value = val;
> 		this.onChange(val);
> 		this.onTouched();
> 		this.cd.detectChanges();
> 	}
> 
> 	constructor(
> 		private cd: ChangeDetectorRef
> 	) {
> 		this.options$ = Observable.of([
> 			{
> 				name:'Option 1',
> 				id: 1
> 			}, {
> 				name: 'Option 2',
> 				id: 2
> 			}
> 		]);
> 	}
> 
> 	registerOnChange(fn) {
> 		this.onChange = fn;
> 	}
> 
> 	registerOnTouched(fn) {
> 		this.onTouched = fn;
> 	}
> 
> 	writeValue(value: number) {
> 		this.value = value;
> 	}
> }
> ```
> 
> The template looks like this:
> 
> ```
> <select
> 		[required]="isRequired"
> 		[(ngModel)]="value">
> 	<option value="" [disabled]="isRequired">{{ noSelectionText }}</option>
> 	<option [ngValue]="opt.id" *ngFor="let opt of (options$ | async)">{{opt.name}}</option>
> </select>
> ```

Only this solution works for me, simple and straightforward.

**Comment by alexfeds** [comment]
Another solution that worked for me, using timeout, bit hacky but does a job, just wrap the patchValue or setValue with timeout


`  setTimeout(() => {
        this.complexSearchForm.patchValue({
          complexSearchQueryCtrl: ruleSet,
          filterTagsCtl: {
            filterTags: obj.tags ? true : false,
            selectedTagTypes: obj.tags && obj.tags.required ? obj.tags.required : [],
            excludedTagTypes: obj.tags && obj.tags.excluded ? obj.tags.excluded : []
          },
        });
      }, 0);`

**Comment by stefanomiccoli** [comment]
Got stuck with this issue in a scenario pretty close to the @maxime1992 colorpicker. Very disappointed when I saw this issue open for years... If not recognised as an issue it would be nice to hear the reasons from someone in angular core team.

in our cases, only solution was to trigger a `this.form.patchValue(changes, { emitEvent: false })`. Without emitEvent to false it would generate a loop

**Comment by JoepKockelkorn** [comment]
> Another solution that worked for me, using timeout, bit hacky but does a job, just wrap the patchValue or setValue with timeout
> 
> 
> ```
>   setTimeout(() => {
>         this.complexSearchForm.patchValue({
>           complexSearchQueryCtrl: ruleSet,
>           filterTagsCtl: {
>             filterTags: obj.tags ? true : false,
>             selectedTagTypes: obj.tags && obj.tags.required ? obj.tags.required : [],
>             excludedTagTypes: obj.tags && obj.tags.excluded ? obj.tags.excluded : []
>           },
>         });
>       }, 0);
> ```

While this works definitely, it's not optimal as Angular needs another ChangeDetection cycle to pick up your changes. Did you try to call `changeDetectorRef.detectChanges()` after the patchValue?

**Comment by alexfeds** [comment]
> > Another solution that worked for me, using timeout, bit hacky but does a job, just wrap the patchValue or setValue with timeout
> > ```
> >   setTimeout(() => {
> >         this.complexSearchForm.patchValue({
> >           complexSearchQueryCtrl: ruleSet,
> >           filterTagsCtl: {
> >             filterTags: obj.tags ? true : false,
> >             selectedTagTypes: obj.tags && obj.tags.required ? obj.tags.required : [],
> >             excludedTagTypes: obj.tags && obj.tags.excluded ? obj.tags.excluded : []
> >           },
> >         });
> >       }, 0);
> > ```
> 
> While this works definitely, it's not optimal as Angular needs another ChangeDetection cycle to pick up your changes. Did you try to call `changeDetectorRef.detectChanges()` after the patchValue?

I did try the change detection, but did nothing. What I finally did, I removed the [ngModel], and only used the reactive approach. In case you have [ngModel] and reactive form together, another solution to update the view, is setting the models with values, after the patching, in this case it updates the view

**Comment by hudzenko** [comment]
Almost 4 years for this bug.. 👎 

I have a stepper in my app and last step is a summary of previous forms. Well I have to use same forms groups at the last step, but summary is not updated anytime

**Comment by guilhermetod** [comment]
I'm not sure if this is a bug actually. The point of the ControlValueAccessor is to act as a bridge between the control and the native element, [as stated in the docs again](https://angular.io/guide/forms-overview#common-form-foundation-classes). If you override the default provider, you  need your own implementantion, includeing the native element update.

I have a currency control, where I want to keep the input display value masked, but record it as a numeric value in my formControl, so I can submit it straight away. If the Control Value Accessor keeps syncing the formControl to the native element, this will turn impossible. It seems reasonable for me that we should use renderer to set the native element input.

That being said, it only seems reasonable after a very long time that I spent not being able to understand what was happenning. I think the docs could get some attention not only for this issue, but for the ControlValueAccessor in general. I found really hard to understand the correct implementation of it at first, specially for simple cases, because most articles I found online were form groups with child controls, which, in the end, delegated the view update to the child controls.

A simple mask input example would be better to understand the purpose and how the ControlValueAccessor works.

Again, for the forms docs, I found the [(very cool) data flow diagrams](https://angular.io/guide/forms-overview#setup-in-reactive-forms) a bit misleading, because they lead you to think that the view to model and vice-versa flow is done through the FormControlDirective, when in fact it seems to be trough the ControlValueAccessor.

**Comment by worthy7** [comment]
If it wasn't a bug, then why doesn't `[formControl]` act the same way?

**Comment by harshalagrawal03** [comment]
I am also facing this issue.
Same form control is used at two places in view and when one is changed by user the other view is not changing.
However, using ngModel resolves the issue. However ngModel and formControl's simultaneous usage is deprecated now.

**Comment by ko1ebayev** [comment]
I guess triggering change detection could help in case of writing value from outside

**Comment by JeanMeche** [comment]
Same as @guilhermetod, this is not a bug to me. 

I took the stackblitz example given earlier and fixed it: https://stackblitz.com/edit/angular-urxsu8?file=src%2Fmain.ts
