### ISSUE TITLE
Script error while loading component from published library.

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular#13790]
If i render my custom component using component file means i can get my custom component.
But couldn't render component from published library and also getting script error  **"Error: No provider for class143!"** while loading module from systemjs file.

plnkr link with custom component file

https://plnkr.co/edit/QmiBtdZ5yCnQ5hMAbyst?p=preview

plunkr link for rendering component from published library

https://plnkr.co/edit/imARedUfrfyWHmcVgYbc?p=preview [issue link]

Navigate to grid and it will throws script error.

Using version **2.0.0**

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
