### ISSUE TITLE
Subscribe and Unsubscribe to both route params and query params

### ISSUE THREAD

**Issue by ThunderRoid** [angular/angular#13804]
We all know, when we subscribe to route params or query params, we must unsubscribe in onDestroy method to avoid memory leak. For example

```javascript
ngOnInit(): void {
        this.paramsSubscription = this.route.params.subscribe((param: any) => {
                console.log(params['type']);
        });
}

ngOnDestroy(): void {
        this.paramsSubscription.unsubscribe();
}
```

But I needed to Subscribe to both **route params and query params at the same time**, so did the following
```javascript
this.obsCombined = Observable.combineLatest(this.route.params, this.route.queryParams, (params, qparams) => ({params, qparams}));
        this.obsCombined.subscribe(ap => {
            console.log(ap.params['type']);
            console.log(ap.qparams['page']);
});
```

So, my question is, **do I need to unsubscribe, if yes then how do I unsubscribe** with "Observable.combineLatest ()" ?
I am also open to suggestions.
Note: query params are optional, i.e.
```javascript
this.router.navigate([type]);
this.router.navigate([type], {queryParams: {page: pageNo}});
```

**Comment by UnwrittenFun** [comment]
You would just capture the subscription to obsCombined the same way you do with the route params in the first example.
```typescript
this.paramsSubscription = obsCombined.subscribe(/* ... */)
```

**Comment by DzmitryShylovich** [comment]
> do I need to unsubscribe

No, u don't. [Docs](https://angular.io/docs/ts/latest/guide/router.html#!#reuse):
> When subscribing to an observable in a component, you almost always arrange to unsubscribe when the component is destroyed.

There are a few exceptional observables where this is not necessary. The ActivatedRoute observables are among the exceptions.

The ActivatedRoute and its observables are insulated from the Router itself. The Router destroys a routed component when it is no longer needed and the injected ActivatedRoute dies with it.

**Comment by DzmitryShylovich** [comment]
@matsko it's a support request not an issue.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed

**Comment by alanhg** [comment]
@UnwrittenFun 
If use it, when link changed, it triggers twice, but load page firstly, it triggers once.

```typescript
let obsCombined = Observable.combineLatest(this.route.paramMap, this.route.queryParamMap, (params, qparams) => ({
      params,
      qparams
    }));
    obsCombined.subscribe(ap => {
      console.log(ap);
      let params = ap['params']['params'];
      let qparams = ap['qparams']['params'];
      this.base64Id = params['id'];
      this.id = Base64.decode(this.base64Id);
      this.searchId = qparams['searchId'];
      this.index = +qparams['index'];
      console.log(this.id);
      this.showContent();
      this.showMetaData(qparams['index']);
    });
```

I need to use params and queryParams. how to do it?

**Comment by ThunderRoid** [comment]
For Angular 6+

    combineLatest(this.route.params, this.route.queryParams)
        .pipe(map(results => ({params: results[0].xxx, query: results[1].query})))
        .subscribe(results => {
            console.log(results);
        });

Where `xxx` is from your route

`{path: 'post/:xxx', component: MyComponent},`

**Comment by chrillewoodz** [comment]
@DzmitryShylovich Does the same apply for `Router` Observables such as `events`?

**Comment by BDominik** [comment]
We have a route, what we access multiple times with different params.
And we also subscribing to the ngrx store from that component.
My question is when and how to unsubscribe when I'm navigating to the same page.
Because then the ngOnDestroy not happening.
And my subscriptions also calling every time when I'm updating the state.
So if I retirecting to the same page 10 times. then changing the store than 10x times invoking the subscriptions.
We migrating from ionic 3 to ionic 4, and ionic 3 had his own push pop navigation, where this thing was working correctly, but it's really hard to migrate to ionic 4 with the new angular router.
