### ISSUE TITLE
ngSwitchCase does not allow expressions starting with '-'

### ISSUE THREAD

**Issue by mlipscombe** [angular/angular#13800]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ngSwitchCase does not allow an expression that beings with a '-', meaning negative numbers have to be expressed as '0-x'.

**Expected behavior**
ngSwitchCase should accept expressions beginning with -.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/d7fqKxv3WOh0oJl0VRqQ

    <div [ngSwitch]="test">
      <ng-container *ngSwitchCase="0">Test is zero.</ng-container>
      <ng-container *ngSwitchCase="-1">Test is -1.</ng-container>
    </div>

**What is the motivation / use case for changing the behavior?**
Accepting expressions that would be accepted by a regular switch statement is more intuitive than having to workaround with 0-x for negative numbers.

* **Angular version:** 2.4.1

* **Browser:** all
 
* **Language:** all

**Comment by vicb** [comment]
Yep, we have a problem here, seems like `0 - 1` works by accident also !

@chuckjaz could you please take a look ?
