### ISSUE TITLE
Router: Query params are removed when using preserveQueryParams

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#13806]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On a routerLink, if `queryParams` and `preserveQueryParams` are used together, the query parameters are not adding to the routerLink.

**Expected behavior**

Query params are still added to the href even if preserveQueryParams is set.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/CF3LxPo2XXWYdb40vDwb?p=preview

Run plunker
Note the two links
The first link has no preserveQueryParams set, and hovering over the link shows a query string of `?filter=true`
The second link has preserveQueryParams set, and hovering over the link shows no query params.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular 2.4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   

cc @DeborahK

**Comment by vicb** [comment]
The logic is: `preserveQueryParams ? this.currentUrlTree.queryParams : queryParams;` which makes sense.

Seems like you want a new feature where you could merge current & new params, right ?

**Comment by brandonroberts** [comment]
Yes, that would be more beneficial

**Comment by dejour** [comment]
seems i can work with this one.

**Comment by dmitrybabiy** [comment]
the same issue with skipLocationChange. Query params are removed when i use this one or preserveQueryParams

**Comment by dejour** [comment]
I think it's by design

**Comment by dejour** [comment]
pls add a plunkr

**Comment by dmitrybabiy** [comment]
i'm typing value in filtering field, and sending request to backend every 400 ms, also i want to store filtering value in query params.

**Comment by dejour** [comment]
can you provide a plunkr?

**Comment by dmitrybabiy** [comment]
https://plnkr.co/edit/b1zFsX1LIvMJgXyFcpuo

**Comment by dejour** [comment]
https://plnkr.co/edit/qEwN7pp4DW4asi8w1yrN?p=preview.
when skipLocationChange enabled,you still get queryParams in router. but it doesn't get reflected in location history.

**Comment by dmitrybabiy** [comment]
ok, i expected location changing without page reloading, what about preserveQueryParams?

**Comment by dejour** [comment]
currently,preserveQueryParams will ignore queryParams option.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource was fixed here https://github.com/angular/angular/pull/14095
