### ISSUE TITLE
xi18n and less modules

### ISSUE THREAD

**Issue by vdclouis** [angular/angular#13809]
**I'm submitting a ...** 
```
[x] bug report
```

**Current behavior**
Given an angular app bootstrapped with angular-cli and using less.
Using the less modules syntax throws an error when running `xi18n`.

module syntax (doesn't work, can't find the file)
```less
@import "~my-module/variables";
```

relative path and extension (works)
```less
@import "../../node_modules/my-module/variables.less";
```

**Expected behavior**
`xi18n` should work with the less module syntax.

**Please tell us about your environment:**

* **Angular version:** 2.4.1
 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =  7.4.0

**Comment by ocombe** [comment]
The tilde is an alias used by webpack, xi18n doesn't know anything about your webpack config (it doesn't know which module folders you added to your resolve config).
It's not reasonable to ask for xi18n to work with that.
It could maybe work with node_modules, but nothing more.

Unless this is part of the official modules spec, but I don't think that's the case ?

**Comment by vdclouis** [comment]
I think this is indeed a less spec. Maybe specially designed for webpack, not sure.

Would be cool to have support for this though. As this would require a lot of rewrite just for i18n support.

**Comment by ocombe** [comment]
Yes, but what might be better would be something like the AoT webpack plugin: have a webpack plugin that runs xi18n after compiling the rest of your app.
This way you can use any specific syntax that you need, webpack will transform it into regular typescript (or else), and then send this to xi18n

**Comment by vicb** [comment]
The angular core only knows about html/css. Any other formats should be converted by ressource loaders.
