### ISSUE TITLE
Webpack Angular2 JQuery Plugin Issue

### ISSUE THREAD

**Issue by nareshkrish12** [angular/angular#13808]
I'm using Angular2 Typescript for my application. During the initial loading of the application it is taking more time as it is downloading individual js files resulting upto 12 MB. I was suggested to use WebPack in order to bundle all the js files in to single file. I've configured necessary setups, but during application loading I get the following exception with regards to Jquery usuage.  I've coded using jquery selector ($) from typescript to perform some UI selection, use jquery methods but during load time it is throwing the below exception. I've even included necessary dependency in Webpack.config.js for jquery, so it compiles without any issues but during onload exception is being thrown.

EXCEPTION: TypeError: $ is not a function
app.bundle.js:53511 EXCEPTION: TypeError: $ is not a functionBrowserDomAdapter.logError @ app.bundle.js:53511BrowserDomAdapter.logGroup @ app.bundle.js:53521ExceptionHandler.call @ app.bundle.js:16196(anonymous function) @ app.bundle.js:19188ZoneDelegate.invoke @ zone.js:323onInvoke @ app.bundle.js:24163ZoneDelegate.invoke @ zone.js:322Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356onInvokeTask @ app.bundle.js:24154ZoneDelegate.invokeTask @ zone.js:355Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
zone.js:461 Unhandled Promise rejection: $ is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: $ is not a function(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): TypeError: $ is not a function(…)consoleError @ zone.js:463_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
app.bundle.js:74155 this.showHome >> true

Plugin:

plugins: [
new webpack.ProvidePlugin({
        jQuery: 'jquery',
        $: 'jquery',
        jquery: 'jquery'
  })

* **Angular version:** 2.0.0-rc.5

* **Browser:** all
 
* **Language:**  TypeScript 1.8.10 | ES5]

* **Node (for AoT issues):** `node --version` = 6.3.1

Package.Json File

{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "build:tsc1": "tsc --rootDir app --outDir dist",
    "postinstall": "typings install",
    "build": "webpack --progress",
    "build:prod": "webpack -p --progress",
    "serve": "webpack-dev-server --progress"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "^0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "core-js": "2.4.0",
    "jquery": "^3.1.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "ts-loader": "^0.8.2",
    "typescript": "^1.8.10",
    "typings": "^1.0.4",
    "webpack": "^1.13.1"
  }

**Webpack.config.js** :

var webpack = require("webpack");
module.exports = {
entry: {
  app: './app/main.ts'

},
	output: {
		path: './dist',
		filename: 'app.bundle.js'
	},
	module: {
		loaders: [
		  {test: /\.ts$/, loader: 'ts'}

	]
	},
	resolve: {
		extensions: ['', '.js', '.ts', '.css'],

	},
plugins: [
new webpack.ProvidePlugin({
        jQuery: 'jquery',
        $: 'jquery',
        jquery: 'jquery'
  })
  ]
};

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
