### ISSUE TITLE
 [4.x Cleanup] Remove Renderer.invokeElementMethod, as Angular does not use it!

### ISSUE THREAD

**Issue by vicb** [angular/angular#13818]
The `invokeElementMethod` of the renderer is not used in Angular.

It should be removed in the 4.x branch

**Comment by ericmartinezr** [comment]
Wouldn't this break people apps (I know the 4.x is for the breaking changes, but this may be too much imo)? I mean, if you google "renderer invokeElementMethod" you'll get a lot of results. It's even recommended in @kara's [Angular 5 rookie mistakes](http://angularjs.blogspot.cl/2016/04/5-rookie-mistakes-to-avoid-with-angular.html) under **Solution: ViewChild + local template variable**. It may not be used internally by angular, but people use it to not access the DOM directly. If the method gets removed, what would be the alternative?

**Comment by DzmitryShylovich** [comment]
> The invokeElementMethod of the renderer is not used in Angular.

not yet https://github.com/angular/angular/pull/12771 :)

This method is very useful for component libs (material, ng-bootstrap etc) to be platform agnostic. Not sure we can remove it as there's no any other alternatives.

**Comment by mgechev** [comment]
I'm using it frequently for developing Web Worker compatible libraries as well. Now after https://github.com/angular/angular/pull/12771 is merged, I suppose this issue should be closed?

**Comment by DzmitryShylovich** [comment]
@vicb `invokeElementMethod` was removed in `RendererV2` so I think it can be closed

**Comment by ericmartinezr** [comment]
@DzmitryShylovich @vicb has to tell us what's the proper way to do it without accesing `nativeElement` :D

**Comment by DzmitryShylovich** [comment]
you know the answer :)

**Comment by exequiel09** [comment]
@ericmartinezr  i agree with him. please tell us the proper way since i too also use this `Renderer.invokeElementMethod()`.

**Comment by DzmitryShylovich** [comment]
@exequiel09 create your own mini renderer https://github.com/angular/angular/issues/15008#issuecomment-285141070

**Comment by tbosch** [comment]
yes, this has been removed in the new `RendererV2`. The deprecated `Renderer` interface still has the method, but it does not work with web workers any more.

**Comment by ipassynk** [comment]
Should the documentation be updated to give people a clear direction upgrading from v2 to v4 who use invokeElementMethod?

```
 this.renderer.invokeElementMethod(this.inputElement.nativeElement, 'focus');
```

**Comment by tbosch** [comment]
@ipassynk Sorry, but our webworker support is still experimental, and far from production ready (all the APIs are marked as experimental as well). There is a ton of features that we are missing to call this stable, and general RPC mechanism as well.

**Comment by ipassynk** [comment]
Thanks for answer but I really need invokeElementMethod for Render 2 in the browser-platform. Render have it (Angular 2) and many people use invokeElementMethod. Render2 ((Angular 4) does not have any such method and there is only one easy way is to start using native element directly to focus (for example) that is against Angular recommendation to abstract all dom manipulation using Render. Please clarify!

**Comment by tytskyi** [comment]
@ipassynk your solution is to create your own service with `invokeElementMethod()`. Then you provide different implementations for the browser and the server (noop method).

**Comment by ipassynk** [comment]
Do you mean you own render service or what service, how to register this service? Do you have any example of such service? I feel this is so common use case that the framework should provide a solution and we had it in Angular 2.

**Comment by MatteoNY** [comment]
Greetings: 

Any ideas on when we can use Angular 4.x to get focus using Angular Render2?

Focus on an element is important for accessibility or if you're using the new animation lib to do something like slide-out a form. I was exploring the new Angular 4.x animations and found an example from Jason Watmore, see the link below. His code is using Angular 4.0.0. I wanted to learn more about the new animations so I tweaked it for my use as updated it to 4.1.0. When you use "add products" button the form slides-out which is cool. After the form slides-out it would be great to then put focus on the form. At the moment the focus does not move onto the form so the button, link are the activeElement.  

I tried to use the new Router2 with this.renderer.selectRootElement(this.elInput).focus;
Compiler did not complain but no focus. According to the docs selectRootElement expects "selectorOrNode" I have it a selector "#elInput" that is using @ViewChild.

Best!

Link:
http://jasonwatmore.com/post/2017/04/19/angular-2-4-router-animation-tutorial-example

**Comment by MatteoNY** [comment]
Got focus on input field to work with Angular 4.1.0 and Renderer2. It appears to work like jQuery selector this.renderer.selectRootElement(#myInput'). 

The input field has an id="myInput".  Not sure the slide-out approach is the best UI. After you do get focus on the field and you close it you really need to then put back the focus where you originated. It's an experiment. From what I understand Ionic framework uses a push on the router so it's like stacking up the page so when you go back you are where you left off. It would be nice if we could do the same. On older Angular where it was OK to use the DOM we could store the previous focus element via document.activeElement and then return focus. It would be great if there was a best practice on this for accessibility and some advanced types of animated panels. 
Focus worked for me using the following in a setTimeout.  
            let onElement = this.renderer.selectRootElement('#myInput');
            onElement.focus();

**Comment by tytskyi** [comment]
@ipassynk and @MatteoNY it is ok to use DOM API directly if you 100% sure your app will never run outside browser (DOM environment). Advice to not use DOM is overmarketed.

@ipassynk to have a focus you don't need to recreate the whole renderer. You can create 2 services with method `focus(el: any): void { ... } `. 1st will recreate logic using DOM api, 2nd service will have an empty method. Then you provide service with the DOM API to the application that is run in the browser, and you provide service with the empty method for the application that run in other environment (server?). 

So that you have `main.browser.ts`, `main.node.ts`, OR `environments.ts`. Or any other approach that lets you separate services for different environments. Meanwhile code of the rest of you application is the same.

**Comment by hallysonh** [comment]
This custom service can help someone:

```typescript
import { Injectable, PLATFORM_ID, Inject, ElementRef } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

@Injectable()
export class MyRenderer {

  constructor(
    @Inject(PLATFORM_ID) private platformId: Object
  ) { }

  invokeElementMethod(eleRef: ElementRef, method: string) {
    if (isPlatformBrowser(this.platformId)) {
      eleRef.nativeElement[method]();
    }
  }
}
```

**Comment by Jonathan002** [comment]
@hallysonh 

Thanks for posting the custom service code. It's really helpful. :)

Is it possible to have the custom service extend Renderer2? I'v tried doing 

```
export class MyRenderer extends Renderer2  {

  constructor(
    @Inject(PLATFORM_ID) private platformId: Object
  ) { }

  invokeElementMethod(eleRef: ElementRef, method: string) {
    if (isPlatformBrowser(this.platformId)) {
      eleRef.nativeElement[method]();
    }
  }
}
```

but I get a typing error where I need to implement all of Renderer2's methods in the custom service. I was hoping the extend would already inherit all of the methods and allow me to just add on the extra invokeElementMethod. Do you know if this is possible?
