### ISSUE TITLE
[4.x] The default ViewEncapsulation should be at @NgModule level (vs global compiler option)

### ISSUE THREAD

**Issue by vicb** [angular/angular#13819]
Only in 4.x.

**Comment by DzmitryShylovich** [comment]
@vicb so every module will have its own default encapsulation or it's only for the root module?

**Comment by djwelch** [comment]
Is https://stackoverflow.com/questions/39452729/angular2-setting-view-encapsulation-globally not the way to do this already?

**Comment by mtuzinskiy** [comment]
@djwelch No, the bootstrapModule setting work with JIT, but ignored by AOT :(

**Comment by pkozlowski-opensource** [comment]
Let's track it in one place, closing as a duplicate of #18346
