### ISSUE TITLE
Angular 2 *ngFor Error

### ISSUE THREAD

**Issue by rani2020** [angular/angular#13817]
I am getting this error
"find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays."

here is my code:

 <table class='table' *ngIf='tabs != 0'>
         
                <tbody>
                   
                    <tr *ngFor='let tab of tabs'>
                        <td>
                            <ul class="list-unstyled list">
                                <li><a href="#" class="anchorLink"><i class="icon-home scolor"></i><font color="white">{{tab.TabName}}</font></a></li>

                            </ul>
                        </td>
                    </tr>

                </tbody>
</table>

navMenu.copnent.ts

import {  Component, OnInit } from '@angular/core';
import { NavMenuService } from './navMenu.service';
import { InavMenuTabs } from './navMenu';

@Component({
    selector: 'nav-menu',
    moduleId: module.id,
    templateUrl: 'navMenu.component.html'
  

})

export class NavMenuComponent implements OnInit {

    tabs: InavMenuTabs[];
    errorMessage: string;
    constructor(private _navMenuService: NavMenuService) {

    }

    ngOnInit(): void {
        this._navMenuService.getTabs(1, 'XXXX')
            .subscribe(tabs => this.tabs = tabs,      
            error => this.errorMessage = <any>error);

        
         
    }
 

}

navMenu.service

import { Injectable } from '@angular/core';
import { Http, Response } from '@angular/http';
import { InavMenuTabs } from './navMenu';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/do';

@Injectable()

export class NavMenuService {

    private _fileUploadAPI = 'http://localhost:50180/API/FileUpload/GetTabs/';
    constructor(private _http: Http) {

    }

    getTabs(LinkID: number, PSNL_UID: string): Observable<InavMenuTabs[]> {
        return this._http.get(this._fileUploadAPI + LinkID.toString() + '/' + PSNL_UID)
            .map((response: Response) => <InavMenuTabs[]>response.json())
            .do(data => console.log('All' + JSON.stringify(data)))
            .catch(this.handleError);

    }

    private handleError(error: Response) {
        console.error(error);
        return Observable.throw(error.json().error || 'Server Error');
    }
}

navMenu.ts
export interface InavMenuTabs {

    LinkTabID: number;
    TabName: string;

}

What am I missing?

**Comment by DzmitryShylovich** [comment]
> <tr *ngFor='let tab of tabs'>

`tabs` is not an array

**Comment by rani2020** [comment]
but how do i Bind/ or loop through ?

**Comment by DzmitryShylovich** [comment]
```
 this._navMenuService.getTabs(1, 'XXXX')
        .subscribe(tabs => {
          console.log(tabs);
          this.tabs = tabs;
        },      
        error => this.errorMessage = <any>error);
```
what is the output in the console?

**Comment by rani2020** [comment]
from
this._navMenuService.getTabs(1, 'XXXX')
        .subscribe(tabs => {
          console.log(tabs);
          this.tabs = tabs;
        },      
        error => this.errorMessage = <any>error)
I get Tabs [object Object]

from 
private _fileUploadAPI = 'http://localhost:50180/API/FileUpload/GetTabs/';
constructor(private _http: Http) {

}

getTabs(LinkID: number, PSNL_UID: string): Observable<InavMenuTabs[]> {
    return this._http.get(this._fileUploadAPI + LinkID.toString() + '/' + PSNL_UID)
        .map((response: Response) => <InavMenuTabs[]>response.json())
        .do(data => console.log('All' + JSON.stringify(data)))
        .catch(this.handleError);


}

I get:
All{"result":[{"LinkTabID":1,"TabName":"Upload File"}]}

**Comment by DzmitryShylovich** [comment]
see, it's an object but must be an array

**Comment by rani2020** [comment]
yes, how do i covert it to array

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by rani2020** [comment]
your point from this link!

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by pushkar2** [comment]
its working 100%
use  this  **?.** you are  ittreating object through *ngFor . it only ittreating array not object but use this ?.
your problem solve
