### ISSUE TITLE
Provide a nicer API for ES5 usage

### ISSUE THREAD

**Issue by mprobst** [angular/angular#1381]
We should make sure that you can use Angular 2 from ES5 with a reasonable DSL-style syntax. E.g. (just making things up)

```js
component({selector: 'my-app'}, ['greetingService'], function(greetingService) {
  // my code.
});
```

@mhevery FYI.

**Comment by mhevery** [comment]
@davideast I believe that you have an idea on how to make that work in ES5. Could you update this bug.

**Comment by davideast** [comment]
I'll have a design doc out soon.

**Comment by mhevery** [comment]
Any update?

**Comment by davideast** [comment]
Working on it. The component part is mostly finished, but I'm also dealing with modules. I'll sync up with you on Monday.

**Comment by naomiblack** [comment]
Assigning to myself to figure out next steps on this.

**Comment by mhevery** [comment]
I think this is solved with the API, which I have crated for the AngularU. I am closing, re-open if I misunderstood.
