### ISSUE TITLE
[4.x] Don't allow injecting classes without @Injectable 

### ISSUE THREAD

**Issue by vicb** [angular/angular#13820]
- `Injectable` or any sub classes,
- Should be deprecated in 4.x, remove in the next major release,
- As of now it is possible when the ctor has no arguments or if any other decorator is applied.

**Comment by trotyl** [comment]
I have a question of why making `useClass` so different?

Would `@Injectable()` also mandatory for `useFactory` when decorator for function expression implementation being ready? 
If so, is it a good way to use the same decorator reference to supporting two different decorator types? 
If not, why everything using `useFactory/useValue...` is injectable by default while what in `useClass` needs explicitly declared to be injectable?

**Comment by DzmitryShylovich** [comment]
> I have a question of why making useClass so different?

angular doesn't call 'ngOnDestroy` on services provided using `useFactory/useValue` https://plnkr.co/edit/pv3XU0wjYC0L6Ay4iHfW?p=preview

**Comment by DzmitryShylovich** [comment]
The only inconsistent thing to me is that we don't need to add `@Injectable` on services provided using `useValue`. Everything else if fine.

**Comment by Toxicable** [comment]
Was this not fixed via b23ad395b73d15149a804cae623cde05a3419f4c ?

**Comment by chuckjaz** [comment]
Closed by #14931
