### ISSUE TITLE
Try using uglify on Angular 2

### ISSUE THREAD

**Issue by mprobst** [angular/angular#1382]
... and see how much benefit we get.

@IgorMinar FYI.

**Comment by mprobst** [comment]
Maybe this is something for our bundling guru?

**Comment by rkirov** [comment]
SystemJsBuilder uses uglify under the hood when called with `minify: true`.

https://code.angularjs.org/2.0.0-alpha.26/angular.min.js is already partially minified, but zone.js is concatenated unminified afterwards which makes it look unminified. The action item here is to concatenate with minified deps (zone and Reflect-metadata).

The result is still pretty good [code.angularjs.org](https://code.angularjs.org/2.0.0-alpha.26)
```
angular2.dev.js                                    05-Jun-2015 05:53             1015263
angular2.min.js                                    05-Jun-2015 05:53              470007
```
