### ISSUE TITLE
router and route instance are null on page refresh inside router.events.subscribe(...) method

### ISSUE THREAD

**Issue by bastienJS** [angular/angular#13829]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1. My enduser saves the link: www.domain.com/#/projects/1/tests as favorite link.
2. He pasts the link into the url bar and the page load starts.
3. The project with id 1 is not pre-selected in the dropdown of projects.
4. But the related tests data is loaded into the UI.
5. The UI  was put into an inconsistent broken state!

**Expected behavior**
1. My enduser saves the link: www.domain.com/#/projects/1/tests as favorite link.
2. He pasts the link into the url bar and the page load starts.
3. In the router.events.subscribe method I do: 

```
console.log('router', this.router.routerState.root.firstChild.firstChild && this.router.routerState.root.firstChild.firstChild.snapshot.params);
```

To get the current projects id. 
4. Then I search in the dropdown of projects for an project object with that id.
5. If that id exists set it as selected.
6. If that id does not exist make a redirect to the root path

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/qTjftING3Hk2fwN36bQa?p=preview

These are the steps how to edit the url bar of a plunkr, because you need to do that, to be able to reproduce the buggy behavior:

```
1. Load the plunkr and activate window mode
2. In window mode copy/paste the url into a new tab
3. When that is the pasted url: https://run.plnkr.co/LhwcQjzWHsRUda8H/projects/1/tests
4. Make it that url: https://run.plnkr.co/LhwcQjzWHsRUda8H/#/projects/1/tests
and change param: https://run.plnkr.co/LhwcQjzWHsRUda8H/#/projects/2/tests
5. If you dont add the hash then you get a not found 404.
```

**What is the motivation / use case for changing the behavior?**
This is actually already described above, this seems redundant to me.

**Please tell us about your environment:**

Win 10 x64, VS Code Editor, npm v4.0.5

* **Angular version:** 2.4.1 

* **Browser:** all  
 
* **Language:** all 

* **Node (for AoT issues):** `node --version` =   6.2.2

**Comment by DzmitryShylovich** [comment]
> https://plnkr.co/edit/qTjftING3Hk2fwN36bQa?p=preview

doesn't load http://prntscr.com/dskauw

**Comment by bastienJS** [comment]
Loads in latest google chrome v55

![image](https://cloud.githubusercontent.com/assets/5945955/21742159/29d600ea-d4e9-11e6-9945-655e1f68dd92.png)

**Comment by DzmitryShylovich** [comment]
so what's the problem? 
> The project with id 1 is not pre-selected in the dropdown of projects.

this?

**Comment by bastienJS** [comment]
The problem is that the router and route instances are NULL when I am inside the router.events.subscribe
so I can not access the route params to determine the current project in the dropdown.

**Comment by DzmitryShylovich** [comment]
Following
```
1. Load the plunkr and activate window mode
2. In window mode copy/paste the url into a new tab
3. When that is the pasted url: https://run.plnkr.co/LhwcQjzWHsRUda8H/projects/1/tests
4. Make it that url: https://run.plnkr.co/LhwcQjzWHsRUda8H/#/projects/1/tests
and change param: https://run.plnkr.co/LhwcQjzWHsRUda8H/#/projects/2/tests
```

everything is defined http://prntscr.com/dsm0e0

**Comment by bastienJS** [comment]
you can make it either a feature request or a bug I dont care. Fact is when the page loads and I have subscribed to the router.events then inside the router/route should not be null. When I am inside a component I am already that far in the pipeline that a router must be there else something is broken.

Its just a matter of time when the router/route is available. For this I have outcommented a setTimeout function in the router.events.subscribe(... setTimeout...) put some miliseconds there and I can access the router/route. That even worked in angularJS ui router where I had a global route change handler in the app.js. Angular 2 shouldn`t make it worse?

**Comment by bastienJS** [comment]
@vsavkin What do you think?

**Comment by vicb** [comment]
I am not sure to understand you problem.

Is the issue that you expect `https://run.plnkr.co/LhwcQjzWHsRUda8H/projects/1/tests` to work and it doesn't while `https://run.plnkr.co/LhwcQjzWHsRUda8H/#/projects/1/tests` doesn't ?

That doesn't work in plunker because of the server configuration but it should work if your server is configured properly (ie redirect all sub path to the main application)

**Comment by bastienJS** [comment]
@vicb The issue is for sure not the plunkr link... I have attached it because you guys asked for it. Then I put a detailed description to the issue how to edit the url.

Then I put a **current behavior** and my **expected behavior** there. What do you still want, what is not clear?

**Comment by preservance717** [comment]
@bastienJS how do you solve this problem,i met same problem with you
