### ISSUE TITLE
ngSwitch seems not working

### ISSUE THREAD

**Issue by calidion** [angular/angular#13826]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
shows two cases;

**Expected behavior**
show only one case.

**Minimal reproduction of the problem with instructions**
for code
```html
<div *ngFor="let message of messages">
  <div [ngSwitch]="message.type">
    <div class="time" *ngSwitchCase="time">
      <p>{{message.time}}</p>
    </div>
    <div class="from" *ngSwitchDefault>
      <div class="avater">
        <img src="{{message.friend.avatar}}" />
      </div>
      <div class="message">
        <div class="sender">{{message.friend.nickname}}</div>
        <div class="document">
          <pre>
{{message.text}}
        </pre>
        </div>
      </div>
    </div>
    <div class="to" *ngSwitchCase="to">
      <div class="message">
        <div class="document">
          <pre>
{{message.text}}
        </pre>
        </div>
      </div>
      <div class="avater">
        <img src="{{message.user.avatar}}" />
      </div>
    </div>
  </div>
</div>
```
every time i got case 'time' and default case displayed.
which only the default on is expected.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Ionic2

* **Angular version:** 2.0.X
2.3

* **Browser:** [all ]
 
* **Language:** [all]

**Comment by dejour** [comment]
can you provide a plunkr?

**Comment by trotyl** [comment]
Just a guess, `*ngSwitchCase` expects a expression instead of literal, are `time` and `to` properties of your component?

**Comment by pkozlowski-opensource** [comment]
Closing for now as we haven't heard back with the reproduce scenario. Happy to re-open when we've got a minimal reproduce scenario in a plunker.

**Comment by calidion** [comment]
using *ngIf instead.

**Comment by calidion** [comment]
@trotyl 
no.
'time' and 'to' are values of  message.type.
