### ISSUE TITLE
Force reload/refresh current route with RouteReuseStrategy

### ISSUE THREAD

**Issue by bisubus** [angular/angular#13831]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With route reuse strategy that is supposed to not reuse a route (`shouldReuseRoute` returns `false`) a route is reloaded only if navigated URL is different (e.g. route param).

Currently route component is refreshed only when another route link is navigated. It is not clear if it is a bug or a missing feature.

**Expected behavior**
Route component is expected to be refreshed when any route link is navigated, including the current one.

**Minimal reproduction of the problem with instructions**
[A plunk](http://plnkr.co/edit/yJy53kj433VgO0xtZOUl?p=info) shows that route component is refreshed only when another route link is clicked.

**What is the motivation / use case for changing the behavior?**
Restore `$route.reload()` functionality from Angular 1. Apparently, the only way to achieve it at this moment is to navigate to temporary route and back. See also #9105

* **Angular version:** 2.4.2

* **Browser:** [all]

 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/13340

**Comment by bisubus** [comment]
@DzmitryShylovich This may be parts of one bigger issue, but not sure if it is really a duplicate.

#13340 concerns navigation events. It also suggests that reloading current route was possible before the introduction of `RouteReuseStrategy` (<=2.3), which is not true, to my knowledge.

**Comment by DzmitryShylovich** [comment]
why do u want to reload it?

**Comment by bisubus** [comment]
@DzmitryShylovich In particular case it is a route component with non-Angular DOM that needs to be updated at some point, and updating resolvers simultaneously is also desirable. It can be any route component which state cannot be easily resetted without recompilation (not necessarily a dev's fault). [Made some points in this issue](https://github.com/angular/angular/issues/9105#issuecomment-251575968) which was prematurely closed.

Angular 1 router and UI Router can handle route reloading, so it would make sense that `RouteReuseStrategy` could handle this situation too. It is there to provide non-default reuse behaviour to routes after all (in this case no reuse at all).

And it inconsistent that `RouteReuseStrategy`  treats the same route with changed params and the same route with same params differently (see the example in the OP). Probably a bug.

**Comment by DzmitryShylovich** [comment]
> Probably a bug.

it's intentional. Navigation to the same url doesn't do anything (no events, RouteReuseStrategy is not even called). This is https://github.com/angular/angular/issues/13340#issuecomment-268532497 the explanation why.

Just found exactly the same issue https://github.com/angular/angular/issues/9669

**Comment by bisubus** [comment]
@DzmitryShylovich Thanks, will track #9669 for now.

**Comment by mihaicux2** [comment]
Hi,

If you really need to _trick_ the **Router** into reloading the component on each **routerLink** click, you can use the following code in your **Component**

    constructor(private router: Router){
         // override the route reuse strategy
         this.router.routeReuseStrategy.shouldReuseRoute = function(){
            return false;
         }

         this.router.events.subscribe((evt) => {
            if (evt instanceof NavigationEnd) {
               // trick the Router into believing it's last link wasn't previously loaded
               this.router.navigated = false;
               // if you need to scroll back to top, here is the right place
               window.scrollTo(0, 0);
            }
        });

    }

Hope this helps

**Mihail C.**

**Comment by Chris-DF** [comment]
@mihaicux2
Hi, Mihail C.
I tried this, but when I clicked one routerlink, it copys its url to the other routerlink, 
which ends up all my two routerlink gose the same url forever. 
Could you please help me with this.

**Comment by josever90** [comment]
@mihaicux2 
Your trick is great, but the problem is that I can't use routerLinkActive. Do you have a solution for this problem?

**Comment by vijaydhandapani** [comment]
@mihaicux2 , Thank you for the solution , I also had a same scenario,  its working fine with the trick. But **josever90** specified, me too have an issue, can't use the routerLinkActive. pls help if you have solution for this.

**Comment by googlicius** [comment]
@mihaicux2 , Thanks, but the resolve functions stick with the route was not called, I need new data from server in the same route.

**Comment by jagcolombat** [comment]
Great solution **@mihaicux2**, worked for me on 4.2.6, but i have the same problem with routerLinkActive as **@josever90** and **@vijaydhandapani**. 

**But on my case i found a solution**:

**Note:** A little detail, i using **router.navigate** instead of **routerLink** directive

On my component constructor only use:
```
this.router.routeReuseStrategy.shouldReuseRoute = function(){
        return false;
 } 
```
On the same component i have a anonymous function that is execute from a certain event and this function is who reload the actual route using:
```
...subscribe(() => {
        // Here is the other part of the trick
        this.router.navigated = false;
        this.router.navigate([this.router.url]);
})
```
Alternatively can test this with a setTimeout example on the ngOnInit hook:
```
setTimeout(() => {
        this.router.navigated = false;
        this.router.navigate([this.router.url]);
        }, 5000);
```
With this my routerLinkActive and my same route reload  work fine....
Hope this helps...

**Comment by senthilmca90** [comment]
@jagcolombat thanks

**Comment by jagcolombat** [comment]
you're welcome @senthilmca90 and to all users reactions

**Comment by TheOnlyMatt** [comment]
Is there a way to do the same thing with NS Router Extensions ?

**Comment by ahmadmgm** [comment]
j

**Comment by ahmadmgm** [comment]
when i use this router function all link in the website point to the same link 
is there any way to solve this problem please help me
this.router.routeReuseStrategy.shouldReuseRoute = function(){
        return false;
 }

**Comment by ramukodandapuram** [comment]
Hi @mihaicux2, I have two components named as **Parent** and **Child** components, there in child component submitting form, right after then I was routing back to parent component and refreshing parent route. for that I  placed your suggested code inside parent constructor by making `this.router.navigated = true;`  till that working fine, but  facing issue that I need to click button two times  at parent component to route  into child component. I have no idea what to do. any reply can be helpful

**Comment by suhailvs** [comment]
this worked for me, taken from [this](https://stackoverflow.com/a/49509706/2351696):

```
redirectTo(uri) {
    this.router.navigateByUrl('/', {skipLocationChange: true}).then(() =>
    this.router.navigate([uri]));
  }
```
now you can use like: `this.redirectTo(this.router.url)`;

**Comment by yanxch** [comment]
Just in case someone missed it: You can already configure your router with the **onSameUrlNavigation** property.
This can be done during the setup of the router `RouterModule.forRoot(routes, { onSameUrlNavigation: 'ignore' })` or via during runtime with `this.router.onSameUrlNavigation ='reload'`.

**Comment by ohabash** [comment]
this works for me but after installing `shouldReuseRoute()` then `this.route.snapshot.firstChild.data` is `null` but it was not null before... Any idea how to reach route data after installing this method?

**Comment by Arpapiemonte** [comment]
My solution is to pass a dummy parameter (i.e. the time in seconds), in this way the link is always reloaded:

`this.router.navigate(["/url", {myRealData: RealData, dummyData: (new Date).getTime()}])`

**Comment by rabiee3** [comment]
> Hi,
> 
> If you really need to _trick_ the **Router** into reloading the component on each **routerLink** click, you can use the following code in your **Component**
> 
> ```
> constructor(private router: Router){
>      // override the route reuse strategy
>      this.router.routeReuseStrategy.shouldReuseRoute = function(){
>         return false;
>      }
> 
>      this.router.events.subscribe((evt) => {
>         if (evt instanceof NavigationEnd) {
>            // trick the Router into believing it's last link wasn't previously loaded
>            this.router.navigated = false;
>            // if you need to scroll back to top, here is the right place
>            window.scrollTo(0, 0);
>         }
>     });
> 
> }
> ```
> Hope this helps
> 
> **Mihail C.**

Please note that this will work, however it'll disable the router adding active state class, because it still thinks that it hasn't navigated to the route.

tested myself and has many impacts

**Comment by tibinthomas** [comment]
> Great solution **@mihaicux2**, worked for me on 4.2.6, but i have the same problem with routerLinkActive as **@josever90** and **@vijaydhandapani**.
> 
> **But on my case i found a solution**:
> 
> **Note:** A little detail, i using **router.navigate** instead of **routerLink** directive
> 
> On my component constructor only use:
> 
> ```
> this.router.routeReuseStrategy.shouldReuseRoute = function(){
>         return false;
>  } 
> ```
> On the same component i have a anonymous function that is execute from a certain event and this function is who reload the actual route using:
> 
> ```
> ...subscribe(() => {
>         // Here is the other part of the trick
>         this.router.navigated = false;
>         this.router.navigate([this.router.url]);
> })
> ```
> Alternatively can test this with a setTimeout example on the ngOnInit hook:
> 
> ```
> setTimeout(() => {
>         this.router.navigated = false;
>         this.router.navigate([this.router.url]);
>         }, 5000);
> ```
> With this my routerLinkActive and my same route reload work fine....
> Hope this helps...

This has side effects but answer from @suhailvs  is working without side effects

**Comment by hari1928** [comment]
More simply  you can  user 
window.location.reload();   
where you want to reload the page

**Comment by aammfe** [comment]
0k after doing some digging, found a solid solution   
its just use to rerun Guards and resolves

```
rerunGuradsAndResolvers() {
    const defaltOnSameUrlNavigation = this.router.onSameUrlNavigation;
    this.router.onSameUrlNavigation = 'reload';
    this.router.navigateByUrl(this.router.url, {
      replaceUrl: true
    });
    this.router.onSameUrlNavigation = defaltOnSameUrlNavigation;
  }
```
it does not reload your component but data that you actually need

**Comment by alator21** [comment]
@aammfe Doesn't work for me for Angular 7.3.8

**Comment by mlc-mlapis** [comment]
@alator21 ... do you have a Stackblitz reproduction?

**Comment by alator21** [comment]
@mlc-mlapis  No unfortunately

**Comment by mlc-mlapis** [comment]
@alator21 ... do you mean that your case was not possible to reproduce or you didn't have time to do it?

**Comment by aammfe** [comment]
@alator21  0k . It might be because 
` runGuardsAndResolvers: 'always'` 



so this is full solution

```
{
    path: ':rawProductStockId/stockWithdraws/:id/edit',
    component: RawProductsStocksWithdrawCreateEditComponent,
    resolve: {
      toEdit: RawProductsStockWithdrawResolverService,
      stock: RawProductsStockResolverService
    },
    runGuardsAndResolvers: 'always'
  }
```


and utility reload function 

```
rerunGuradsAndResolvers() {
    const defaltOnSameUrlNavigation = this.router.onSameUrlNavigation;
    this.router.onSameUrlNavigation = 'reload';
    this.router.navigateByUrl(this.router.url, {
      replaceUrl: true
    });
    this.router.onSameUrlNavigation = defaltOnSameUrlNavigation;
  }
```

**Comment by alator21** [comment]
@aammfe  I didn't had the "runGuardsAndResolvers: 'always'" bit. Now it's fine. Thank you.

**Comment by tuanbs** [comment]
> My solution is to pass a dummy parameter (i.e. the time in seconds), in this way the link is always reloaded:
> 
> `this.router.navigate(["/url", {myRealData: RealData, dummyData: (new Date).getTime()}])`

My Chrome browser crashed using this code. :(

**Comment by tuanbs** [comment]
> this worked for me, taken from [this](https://stackoverflow.com/a/49509706/2351696):
> 
> ```
> redirectTo(uri) {
>     this.router.navigateByUrl('/', {skipLocationChange: true}).then(() =>
>     this.router.navigate([uri]));
>   }
> ```
> now you can use like: `this.redirectTo(this.router.url)`;

This solution works for me, but the issue is that the browser doesn't get back to previous page when I click the browser `back` button. After searching, I found a better solution by adding the following line of code before navigating:
```js
this._router.routeReuseStrategy.shouldReuseRoute = function(){
    return false;
};
```

**Comment by rahulccactus** [comment]
> Great solution **@mihaicux2**, worked for me on 4.2.6, but i have the same problem with routerLinkActive as **@josever90** and **@vijaydhandapani**.
> 
> **But on my case i found a solution**:
> 
> **Note:** A little detail, i using **router.navigate** instead of **routerLink** directive
> 
> On my component constructor only use:
> 
> ```
> this.router.routeReuseStrategy.shouldReuseRoute = function(){
>         return false;
>  } 
> ```
> 
> On the same component i have a anonymous function that is execute from a certain event and this function is who reload the actual route using:
> 
> ```
> ...subscribe(() => {
>         // Here is the other part of the trick
>         this.router.navigated = false;
>         this.router.navigate([this.router.url]);
> })
> ```
> 
> Alternatively can test this with a setTimeout example on the ngOnInit hook:
> 
> ```
> setTimeout(() => {
>         this.router.navigated = false;
>         this.router.navigate([this.router.url]);
>         }, 5000);
> ```
> 
> With this my routerLinkActive and my same route reload work fine....
> Hope this helps...

Thank you so much. This work like charm.

**Comment by jagcolombat** [comment]
Thanks for your comment rahulccactus.

**Comment by buster95** [comment]
### Resume all comments, this works for me
first added in router module
`
`

`
this.router.routeReuseStrategy.shouldReuseRoute = ( ) => false;
this.router.navigate([this.router.url]);
`
