### ISSUE TITLE
Try compiling Angular together with apps using it

### ISSUE THREAD

**Issue by mprobst** [angular/angular#1383]
... and see how much we might benefit form a globally optimizing compiler, e.g. Closure Compiler. There's a possibility that tree shaking and other advanced optimizations save a lot of code size and make the app faster by e.g. inlining.

@mhevery FYI.

**Comment by pkozlowski-opensource** [comment]
@mprobst what tools did you have on your mind here? Is it for Dart only? Asking since the only tools for ES6 that tries to enable tree-shaking is https://github.com/rollup/rollup - but it doesn't understand decorators / type annotations. Or maybe TS tooling has this tree-shaking capability?

**Comment by mprobst** [comment]
The idea is to use an optimizing compiler like Closure Compiler (which supports ES6 and tree shaking), after cross compiling. Indeed that doesn't get the type info, but maybe we can get gains just like it is? It'd also be interesting to figure out how much we could gain from the process, e.g. if it's worth to make an effort to better feed Closure Compiler with type info. Or use a different compiler, for that matter.

There's also what @dariajung works on.

**Comment by SynerG** [comment]
@pkozlowski-opensource Webpack 2 has also enabled tree-shaking for ES6 (currently in beta). See [this post](http://www.2ality.com/2015/12/webpack-tree-shaking.html) for a working example. It uses Babel under the hood, so it has a more complete feature set to achieve the transformation.
Anyway, to transpile Angular's TypeScript code to ES5 code that can be tree-shaked, it looks like it would require to use `tsc`with `target:es6`and then pipe the output into Webpack to obtain ES5 code where unused exports are removed.

**Comment by pkozlowski-opensource** [comment]
The work on this is in progress and is currently captured in #8550
