### ISSUE TITLE
Link is opened in the same tab, when target="_blank" is set using binding

### ISSUE THREAD

**Issue by devoto13** [angular/angular#13837]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When `target="_blank"` is set using data binding (e.g. `[target]="'_blank'"`) it doesn't open url in a new tab.

**Expected behavior**

When `target="_blank"` is set using data binding (e.g. `[target]="'_blank'"`) it opens url in a new tab, same as if `target` was set without using binding.

**Minimal reproduction of the problem with instructions**

Example: http://plnkr.co/edit/wCtDliPgWr3khL3NwCD3?p=preview

When clicking on "Working" it correctly opens link in a new tab.
When clicking on "Failing X" it loads new link in the same tab.

Example from plunker doesn't make sense. It just demonstrates issue. In real application I'm getting `target` value from another place and want to use binding to set it.

**What is the motivation / use case for changing the behavior?**

Broken?

**Please tell us about your environment:**

* **Angular version:** 2.4.1

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** not relevant

**Comment by DzmitryShylovich** [comment]
The issues is that `routerLink` handles `click` event and ignores `target` attribute. 
Without `routerLink` works fine `<a href="/" [attr.target]="target">Failing 4</a>`

**Comment by DzmitryShylovich** [comment]
As a workaround u can create your own directive which will handle `target` property

**Comment by devoto13** [comment]
@DzmitryShylovich See working example. It still uses `routerLink`, but works correctly when attribute is set directly. Not sure if it's related to `click` event, feels like something fun is going on with bindings. Also directive [seems to have](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/directives/router_link.ts#L141-L142) `@Input() target`.

**Comment by mohan1304** [comment]
I am on angular 2.4.6 and when I try to open new tab using target="_blank" it throws "HTTP Status 404 -" error. Am I missing anything?

My project is angular2 webpack

**Comment by devoto13** [comment]
@mohan1304 Does it also fail if you reload page? If so, it's server configuration issue. You should add to your `webpack.config.js`:

    devServer: {
        historyApiFallback: true
    }

**Comment by mohan1304** [comment]
@devoto13 its not on page reload. I have below anchor tag and it should open new tab when I click on it.

Below given is my code
<a class="left-header-images-link" [routerLink]="['/alternatetree']" [target]="'_blank'"> 

and the new tab shows below error after clicking on the anchor element

HTTP Status 404 - /DataModelViewer/alternatetree

It used to work until last week when I was using systemjs and recently I converted it to angular2 webpack and now I am seeing this issue

**Comment by mohan1304** [comment]
Forgot to mention I already added above recommended property in my project

**Comment by mohan1304** [comment]
created issue https://github.com/angular/angular/issues/14463

**Comment by nishantagrawal25** [comment]
This is still not working.

I want to update target of my links using bindings, If I am doing this directly in a tag it is working fine but not when I am trying to set it dynamically

issue #14463 is different than this issue
