### ISSUE TITLE
Hybrid app(UpgradeModule) using angular router doesn't invoke change detection on initial load

### ISSUE THREAD

**Issue by akhlesh** [angular/angular#13830]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When
* bootstrap hybrid app using angular2 router
* On initial load of application, Change detetction doesn't call ngOnChanges on change of input binding which suppose to get data via async filter.  for e.g.
 `<test [testData]="data | async"></test>`
this happens only with initial load of  hybrid app routing and If we move to another route and again back to first route then ngOnChanges works fine.

**Expected behavior**
It should fire changeDetection whenever input binding(with async) changes. 

**Minimal reproduction of the problem with instructions**
See this plunker with issue http://plnkr.co/edit/QUOLzNXYgDoTjeJ9iCiA?p=preview  
   &nbsp;&nbsp;   **Steps**
  * Check testData on home page, it doesn't get updated 
  * Now click on user link and again click on home link, you'll see testData is changing and ngOnChanges logs data in console.

**What is the motivation / use case for changing the behavior?**
Use hybrid app with angular2 routing

**Please tell us about your environment:**
* **Angular version:** <= 2.4.0 
* **Browser:** [all | Chrome 55 | IE 10]
* **Language:** [TypeScript 2.0.3]

**Comment by aminpaks** [comment]
I think this isn't the way things are supposed to work.
As far as the docs at [this page](https://angular.io/docs/ts/latest/guide/upgrade.html) explain we need a root component that is already downgraded no?
```
angular.module('heroApp', [])
  .controller('MainController', MainController)
  .directive('heroDetail', downgradeComponent({
    component: HeroDetailComponent,
    inputs: ['hero'],
    outputs: ['deleted']
  }) as angular.IDirectiveFactory);
```

**Comment by gkalpak** [comment]
The problem is that your are bootstrapping AngularJS in the promise returned by `bootstrapModule()`, which runs outside the Angular zone. (This was incorrectly recommended in our docs in the past. The docs have been long updated and bootstrapping AngularJS inside the Angular zone, works as expected ([updated demo][1]).

[1]: http://plnkr.co/edit/tPyIQIpTRNNvYu4Ny1ZJ?p=preview
