### ISSUE TITLE
Custom module loading error

### ISSUE THREAD

**Issue by bobbywarner** [angular/angular#13833]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have updated my Angular 2.1.2 application to Angular 2.4.1 this week (and 2.4.2 this morning).  It took quite a few updates, but everything actually works in the browser now.

There is a module loading error in the console though.  The module (and components in it) work fine in the running app in the browser.  There is just this error in the console.

```
ERROR in Could not resolve "app/application-event/application-event.module" from "/Users/bobby/workspace/myapp/src/app/app.module.ts".
```

`application-event.module` is one of my custom modules that I try to load from my app root module `app.module`.

If I actually completely remove `application-event.module` from my application, I get a similar error in console for the next custom module I attempt to load.  Once again, the module and components in it work fine in the running app, just the error in the console.

**Expected behavior**
It appears everything works great in the running app.  So, I don't understand why this error is output in the console and/or how to get rid of it.  I don't want to say to the other developers on my team "just ignore that error in console"

**Minimal reproduction of the problem with instructions**
I don't have a sample outside of my application, but can put one together if needed.  Just thought I'd see if there is something obvious I'm missing first since the app works and it's just an error in the console.

**What is the motivation / use case for changing the behavior?**
Just an error in the console.

**Please tell us about your environment:**
OSX Sierra, Angular-CLI

* **Angular version:** 2.4.1
 
* **Language:** [TypeScript 2.0]

* **Node (for AoT issues):** `node --version` = v7.4.0

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr

**Comment by bobbywarner** [comment]
I realized when creating a sample app that the root cause of this error is actually related to Angular-CLI not the framework itself.  So, closing.
