### ISSUE TITLE
Support Binding To Src Value For Video Element

### ISSUE THREAD

**Issue by JimTheMan** [angular/angular#13836]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This code doesn't work (video element is all black):

```
  <video src="{{currentVideoPlayingUrl}}" autoplay></video>
```

**Expected behavior**
display a video when _currentVideoPlayingUrl_ is set to a URL of a video file. 

**What is the motivation / use case for changing the behavior?**
People people use video in webapps....

**Please tell us about your environment:**
mac OS 10.11.5

* **Angular version:** 2.0.X

@angular 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.2

* **Node (for AoT issues):** `node --version` = 
angular-cli: 1.0.0-beta.15
node: 6.9.1
npm: 3.10.8

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr

**Comment by vicb** [comment]
Closing as:
- missing repro,
- missing infos (browser),
- probably not related to Angular - try to create a `<video>` and set the src *property* on the DOM node to see if this works. If not try to bind to the attribute `[attr.src]="..."` or use a `<source>` element.

**Comment by JManuelMT** [comment]
@JimTheMan  Just use [attr.src]="..." inside video tag (not in source tag) it works for me
