### ISSUE TITLE
Forms: Need setValue(obj, {ifNotEqual:true})

### ISSUE THREAD

**Issue by benneq** [angular/angular#13835]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When calling `setValue` or `patchValue` on a `FormGroup` (basically this is valid for any Form Control Element), it will call `setValue` for every child even if the value of some input didn't change. 
This will cause the cursor position and selection inside `<input>` elements to be reset. 

**Expected behavior**

There should be some option provided (like `ifNotEqual:true`) to only call `setValue` of those Form Controls where the value actually changed.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I have a big form with lot's of `<input>` fields. And there's a background job which updated the form while the user can enter data.
When this happens every selection within those `<input>` elements will get reset and the cursor position will be set to the end of the input element's value.

Currently I'm thinking about writing a custom method which does a diff of the form's current value and the new value. Then throw away every field with equal values and then use `form.patchValue`.
But it would be so much easier if Angular would provide this feature.

**Please tell us about your environment:**

MacOS Sierra, VS Code, NPM, Webpack, ...

* **Angular version:** 2.0.X

Angular 4.0.0 beta 2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.1.4

* **Node (for AoT issues):** `node --version` =   
7.3.0

**Comment by DzmitryShylovich** [comment]
> This will cause the cursor position and selection inside <input> elements to be reset.

could u pls add a small repro in plunkr?

**Comment by benneq** [comment]
Here you go: https://plnkr.co/edit/H9QzooDCqIfyN16DXbQC?p=preview

There's only a litte input box.

Steps to reproduce:
1. Type "abc"
2. Cursor is now behind "c"
3. Press left arrow
4. Cursor is not behind "b"
5. Delete "b" (or insert any other character)

Now cursor won't stay where it was. Instead it jumps to the end of the input.

This behavior is pretty obvious because the input's value is getting re-set (even if it's the same value, i.e. oldValue === newValue).

**Comment by DzmitryShylovich** [comment]
I think u can create a directive which will listen for input event and will reset cursor position. Something like http://stackoverflow.com/a/14508837

**Comment by benneq** [comment]
I had a look at your commits. Looks pretty nice and simple 👍 

Could you also add `notEqual` to FormGroup and FormArray? And also to the `patchValue` methods? Then there would be equal behavior across all classes and methods.

**Comment by benneq** [comment]
Great! Thank you! 👍  
Would love to see this in 4.0.0 beta 3

**Comment by frederikaalund** [comment]
When will this feature land in Angular?

**Comment by manimurugank** [comment]
patchValue not trigger focus after value set

**Comment by manimurugank** [comment]
can you please help me that "patchValue" not trigger focus

**Comment by manimurugank** [comment]
with placeholder not floating after patchValue
