### ISSUE TITLE
Broken links on Angular GitHub Projects page

### ISSUE THREAD

**Issue by valera-rozuvan** [angular/angular#13840]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Links on the [Projects](https://github.com/angular/angular/projects) page of Angular Github repository don't open relevant pages. For example, if you click on **go/ng-priorities**, it leads nowhere.

**Expected behavior**

Links should open the correct page.

**Browser:**

All.

**Comment by DzmitryShylovich** [comment]
It's internal google links. It's intentional :)

**Comment by matsko** [comment]
Yes we use this stuff internally and we can't change it.
