### ISSUE TITLE
Router marks target route's link as active route even when canDeactive returns false from the source route

### ISSUE THREAD

**Issue by burkilic** [angular/angular#13847]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
* Define two routes
* In your template, create bindings for those routes (see below for examples)
* For the component that one of the routes corresponds to, implement canDeactivate (follow instructions in the official documentation here: https://angular.io/docs/ts/latest/guide/router.html#!#can-deactivate-guard)
* Return false for canDeactivate()
* Toggle between the links. When you try to go from the route where canDeactivate returns false to the other route, even though the URL stays the same, as well the component rendered, the route that the you try to click is somehow marked as the active link and it's also styled as the active link

**Expected behavior**
The active route should be consistent with the URL and the click event on the <a> element (or whatever you've bound the link to) should have the 'active' class of the current route (not the target route).

**Minimal reproduction of the problem with instructions**
Here are my routes:

`{ path: 'a', component: ComponentA, pathMatch: 'full' },`
`{ path: 'b', component: ComponentB, canDeactivate: [CanDeactivateGuard] }`
 
My template:
`<li data-toggle="tab" routerLinkActive="active">`
`       <a [routerLink]="['a']">a</a>`
`</li>`
`<li data-toggle="tab" routerLinkActive="active">`
`          <a [routerLink]="['b']">b</a>`
`</li>`
 
CanDeactivateGuard is exactly as is from: https://github.com/angular/angular.io/blob/master/public/docs/_examples/router/ts/app/can-deactivate-guard.service.ts

canDeactivate() method in ComponentB:
`canDeactivate(): Promise<boolean> | boolean {`
`       return false;`
`}`

**Workaround**
As a workaround, I'm handling the click event for each route: 

`<li data-toggle="tab" routerLinkActive="active" (click)="onLinkClick($event, 'a')">`
`                   <a [routerLink]="['a']">a</a>`
`</li>`

And stopping the event propogation if the link that's being clicked on is not the active route (due to another link returning false for canDeactivate)

`private onLinkClick(event, routeUrl: string) {`
`        if (!this.router.isActive(routeUrl, false)) {`
`            event.stopPropagation();`
 `       }`
 `   }`
 
Where router is Router from @angular/router, injected into my parent component's constructor.

**What is the motivation / use case for changing the behavior?**
Route guards are fundamental functions and canDeactivate should behave as expected. What I'm doing as a workaround should be baked into how the active route is determined as part of the inner workings of routerLinkActive attribute.

**Please tell us about your environment:**
OS: Windows 7
Using Angular 2 with webpack
Router version:
@angular/router: "3.4.0"
Other angular library versions:
"@angular/common": "2.4.0",
    "@angular/compiler": "2.4.0",
    "@angular/core": "2.4.0",
    "@angular/forms": "2.4.0",
    "@angular/http": "2.4.0",
    "@angular/platform-browser": "2.4.0",
    "@angular/platform-browser-dynamic": "2.4.0"

* **Angular version:** 2.0.4

* **Browser:** Chrome Version 53.0.2785.143
 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` = 4.2.1

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr

**Comment by burkilic** [comment]
Hello, here it is:
http://embed.plnkr.co/kXSOvW4nocuVCI52k0s0/

**Comment by DzmitryShylovich** [comment]
@burkilic Hmm interesting. I can't reproduce it using webpack.

**Comment by DzmitryShylovich** [comment]
Similar to this one https://github.com/angular/angular/issues/10977
Only reproducible using systemjs.

**Comment by royling** [comment]
I believe this relates to #14059.

**Comment by jasonaden** [comment]
This should have been resolved when we fixed some sequencing behind these guards. If the issue persists, please create a new issue.
