### ISSUE TITLE
Router: Use '**' wildcard as catch-all to lazy loaded module with child routes

### ISSUE THREAD

**Issue by NathanWalker** [angular/angular#13848]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The `'**'` catch-all definition lazily loads the module, however it does not properly handle the child routes.

**Expected behavior**

Lazy load the module and properly handle all the child routes. The catch-all `'**'` lazily loaded module could either define more `'**'` catch-all's with other lazy loaded modules or it could of course also have it's own `'**'` catch-all to just a component to show a not found component if desired.

**Minimal reproduction of the problem with instructions**

This SO post describes the issue:
http://stackoverflow.com/questions/40276372/angular-router-wildcard-as-a-catch-all-with-child-routes-using-latest-2-4

This plunkr demonstrates the issue:
https://plnkr.co/edit/QfXx5KJGfhMskIldA0AA?p=preview

If you open the console, you will see `created [NameComponent]` for each link you click on *except* the 'whatever' link which lazily loads the `AnythingModule`.

**What is the motivation / use case for changing the behavior?**

More flexible routing setups.

**Please tell us about your environment:**

Mac os Sierra

* **Angular version:** 2.0.X

Angular `2.4.0`, Router: `3.4.1`

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript

* **Node (for AoT issues):** `node --version` =   

Node `6.9.1`, npm `3.10.1`

/cc @zoechi since he had helped initially with the SO post. Thank you!

**Comment by DzmitryShylovich** [comment]
It's a bug. not a feature request.

**Comment by NathanWalker** [comment]
Thanks @DzmitryShylovich just edited original description to specify bug. (wasn't sure if this was outside original design - didn't think so - but yeah wasn't sure). 👍

**Comment by dherges** [comment]
@DzmitryShylovich @NathanWalker did this fix make it into a release?

**Comment by dherges** [comment]
duplicated by #12024, #12955 ? there was a fix in #12024 but appears to not work in 2.4.x

Tried various combinations in 2.4.x

```
@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10
```


this fails (module is loaded, no component is shown for url `/`):
```
{
  path: '**',
  loadChildren: './+content/content.module#ContentModule'
}
```

setting to constant value works (module loaded, component shown for url `/content`)
```
{
  path: 'content',
  loadChildren: './+content/content.module#ContentModule'
}
```


prefixing with a path and a catch-all fails (error message `Promise rejection: Cannot match any routes. URL Segment: 'content/foo'` for url `/content/foo`):
```
{
  path: 'content/**',
  loadChildren: './+content/content.module#ContentModule'
}
```

setting to empty string works (module loaded, component shown):
```
{
  path: '',
  loadChildren: './+content/content.module#ContentModule'
}
```

**Comment by tskweres** [comment]
Is there a fix for this in the works?

**Comment by tskweres** [comment]
@DzmitryShylovich @NathanWalker anyone know any version where this works?

**Comment by jasonaden** [comment]
I'll be taking a look at the PR that should fix this issue. Hopefully we can get this into an upcoming release.

**Comment by MrSnappingTurtle** [comment]
Am having this issue with `4.2.4`. @jasonaden Any updates on your PR? Looks like the build is failing. Thanks!

**Comment by x4storm** [comment]
router 4.3.6 also having this issue

**Comment by adelloste** [comment]
I have same issue, this is my version:

```
@angular/cli: 1.2.1
node: 6.10.1
os: win32 x64
@angular/animations: 4.4.4
@angular/cli: 1.2.1
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/compiler-cli: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/language-service: 4.4.4
```

Thanks

**Comment by sopretty** [comment]
I'm using Angular 5 and I have the same issue :
Module is loaded, but no component is shown for different url then 'error' or '/'.
`const ROUTES: Routes = [
  {path: '', component: LoginComponent, canActivate: [LoginGuard]},
  {path: 'error', loadChildren: './modules/error/error.module#ErrorModule'},
  // Wildcard - select this route if the requested URL doesn't match any paths for routes defined earlier in the configuration
  {path: '**', loadChildren: './modules/error/error.module#ErrorModule'},
];`

**Comment by DominicBoettger** [comment]
Same problem here with angular4 and angular5

**Comment by customcodepl** [comment]
I have used:
`
  {path: 'error', loadChildren: './pages/error/error.module#ErrorModule'},
  {path: '**', redirectTo: 'error', pathMatch: 'full'}
`

**Comment by yarrgh** [comment]
I've used the same as @customcodepl using a redirect on a wildcard "catch all" route. Redirecting to a lazy loaded route/module works as expected.

**Comment by dereklin** [comment]
@customcodepl @yarrgh 

I am using Angular 5.1.2

When I use the redirect approach, my "root" redirect no longer works.

Here is my set up:

```
const routes: Routes = [
  {
    path: '',
    component: CoreComponent,
    children: [
      { path: '', redirectTo: 'f1', pathMatch: 'full' },
      { path: 'f1', component: Feature1Component },
      { path: 'f2', component: Feature2Component },
      { path: 'not-found', loadChildren: '@nx-demo-jest/not-found/src/not-found.module#NotFoundModule' },
      {
        path: '**',
        // component: NotFoundComponent // this works
        // loadChildren: '@nx-demo-jest/not-found/src/not-found.module#NotFoundModule' // this doesn't
        redirectTo: 'not-found', pathMatch: 'full' // the root (/) redirects to non-found
      },
    ]
  }
];
```
When I go to /f1, it goes to Feature1Component
When I go to /, it gets redirected to not-found; it should be redirected to f1 instead.

Here is my github repo: 

https://github.com/dereklin/nx-demo-jest/tree/wildcard-route-lazy-load-1

**Comment by dereklin** [comment]
Oh.  Nevermind, the wildcard redirect actually works.  What I am seeing here is the forChild routes overriding another forChild routes.

In my NotFoundModule, I set my routes like this:
```
RouterModule.forChild([{ path: '', component: NotFoundComponent }])
```
And when I import it here:
```
@NgModule({
  imports: [
    RouterModule.forChild(routes),
    NotFoundModule
  ],
  exports: [RouterModule]
})
export class CoreRoutingModule {}

```
the path: '' overrides the parent routes.  That's why I am getting not-found when I go to /
