### ISSUE TITLE
update table bot working in angular2

### ISSUE THREAD

**Issue by sureshhustle** [angular/angular#13843]
Hi,
   I am new to angular 2, I am using ng2-smart table from this update is not working , i will try to update but not working , if anyone have idea to update by using http url, and please give a sample code to implement

thanks advance

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
