### ISSUE TITLE
Proposal: Allow computed property names in map expressions

### ISSUE THREAD

**Issue by santialbo** [angular/angular#13855]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The expression parser currently doesn't support ES2015 computed property names, which allow to put an expression between brackets [] that will be computed as the property name.

Example of what's not currently supported:
```html
<div [ngClass]="{[className1]: true, [className2]: foo()}"></div>
```
*`className1` and `className2` are properties in the controller that contain the actual class names.*

This can be overcome by creating a property/function in the component class.
```js
get myClasses() {
  let self = this;
  return {
    [self.className1]: true,
    [self.className2]: self.foo()
  };
}
```
```html
<div [ngClass]="myClasses"></div>
```
**Expected behavior**
First example to work.

**What is the motivation / use case for changing the behavior?**
This would avoid the need for creating such properties in the component.

**Please tell us about your environment:**

* **Angular version:** 2.3.1

**Comment by santialbo** [comment]
I've done some work as an exercise trying to add this feature. If it's ok I'd like to make a PR for discussing my changes.
https://github.com/santialbo/angular/commit/6810e3f3638513eb234213ce75831ae59e87e2cf

Regards

**Comment by DzmitryShylovich** [comment]
@santialbo open a pr

**Comment by alxhub** [comment]
I'm going to close this issue - but that's not a sign that we're not thinking about this.

As Pete mentioned, this is something we think about more holistically - how Angular's expression syntax differs from JavaScript. We're unlikely to implement this as a particular feature (especially given the lack of upvotes) but as we work to align our expression syntax, it will come up again for discussion.
