### ISSUE TITLE
Test Driven Development does not seem to be supported for Components

### ISSUE THREAD

**Issue by AmyBlankenship** [angular/angular#13868]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Based on the available documentation, it doesn't look like it's possible to write a component in a test-first process (aka best practice). Instead, it looks like a significant amount of code has to be written before any tests can be run.

**Expected behavior**
It should be obvious how to write components test first and/or the testing docs should be updated to make this clearer.

**Minimal reproduction of the problem with instructions**
https://angular.io/docs/ts/latest/guide/testing.html

**What is the motivation / use case for changing the behavior?**
Code is more robust and the design is better when the tests are written first and then made to pass vs. writing the code first and then testing it.

Note that in AngularJS I tended to create Controllers as their own thing and test those for directives and utilize data binding to minimize need to test.  If there is a way to write the Controller separately and then compose it into a Component, this is not clear fro, the docs.

**Please tell us about your environment:**
Windows 10 Surface with Webstorm and Angular-CLI

* **Angular version:** 2.0.X
2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript for sure. There aren't very good docs for plain JS.

* **Node (for AoT issues):** `node --version` =   

**Edit since I can't comment**
First, thanks for the URL

Is this entirely a documentation issue? Does Angular actually support test-first development natively? If not, this is a functionality issue. If so, could you please point me in the right direction so I'll understand what's involved to create the bug at the URL provided.

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io/issues

**Comment by matsko** [comment]
@AmyBlankenship if you wouldn't mind, could you please recreate this issue on the link above. There isn't much we can do here to improve the documentation of guides.

**Comment by AmyBlankenship** [comment]
Is it a documentation issue or a design flaw?
