### ISSUE TITLE
Add documentation for @Host

### ISSUE THREAD

**Issue by jrgleason** [angular/angular#13863]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you look at [the code for metadata](https://github.com/angular/angular/blob/master/modules/%40angular/core/src/di/metadata.ts), you will see that under HostDecorator is suggests...

`For more details, see the {@linkDocs guide/dependency-injection "Dependency Injection Guide"}.`

Problem is there is nothing about the `@Host` inside that page. 

**Expected behavior**

We should either remove the reference to documentation, or add an appendix that speaks to this behavior

**What is the motivation / use case for changing the behavior?**

I am trying to create a directive that uses @Host to find a parent and looking for documentation around how the @Host annotation resolves.

**Comment by jrgleason** [comment]
Or we could at least update the link to https://angular.io/docs/ts/latest/api/core/index/Host-decorator.html

**Comment by jrgleason** [comment]
Also https://angular.io/docs/ts/latest/api/core/index/Host-decorator.html references the same page, which again says nothing about @Host

**Comment by jrgleason** [comment]
Also it would also be nice to know if View encapsulation style matters. So for example will I find a higher level element with emulated that I wont find with actual ShadowDom

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io/issues

> Also it would also be nice to know if View encapsulation style matters

di has nothing to do with encapsulation

**Comment by jrgleason** [comment]
I was more worried about since it is looking for the Host element. I was not sure if that would change anything I will open there.
