### ISSUE TITLE
How we can add new routes dynamically into RouterModule(@NgModule imports)

### ISSUE THREAD

**Issue by Sri276286** [angular/angular#13860]
Hi,

My question is "How we can add new routes dynamically?" . I will try to explain with some code.

```
import { NgModule }             from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

let routes: Routes = [
{ path: '', redirectTo: 'home', pathMatch: 'full'},
{ path: 'home', loadChildren: './dashboard/dashboard.module#DashboardModule' }
];

// How I can get this route dynamically
let my_routes = [
  { path: 'route_new', component: MyComponent }
];

let newRoutes = routes.concat(my_routes);

@NgModule({
  imports: [ RouterModule.forRoot(newRoutes) ],
  exports: [ RouterModule ]
})
export class AppRoutingModule {
}
```

Whatever I have done here is hard coded **my_routes** (but please some help me how I can load this variable dynamically with data from a service).

Please let me know if any things are still needed?

**Comment by DzmitryShylovich** [comment]
`Router.resetConfig()`

**Comment by onixie** [comment]
By modifying `ActivatedRoute.routeConfig` directly, it is also possible to dynamically add new routes.
This is very handy when you want to add new routes as children of a route existing deeply in route hierachy.

**And maybe it is the only way when the route is in a lazily loaded module.**

**The bad news is that it lacks validation on newly added routes.**

I propose to add a `resetConfig`-like api for `ActivatedRoute` which will make this method more user friendly.

**Comment by Sri276286** [comment]
@DzmitryShylovich Is your solution available with Angular 2.0

**Comment by Sri276286** [comment]
@onixie  Please provide any reference link where I can go and refer

**Comment by onixie** [comment]
@Sri276286 try this. https://embed.plnkr.co/wBorFvoG3hfD36iOcNqu/

`AppComponent` adds route to `FooComponent` by `Router.resetConfig()`.
`FooComponent` adds route to `GooComponent` which is in `GooModule` by `ActivatedRoute.routeConfig`.
`GooComponent` adds route to `BooComponent` as what `FooComponent` does.

There is one difference you need to notice between statically configured routes and dynamically added routes for component.

**You have to explicitly list the component you want to route to in `entryComponents` if using dynamic method.** 

For statically configured routes, `RouterModule.forRoot/forChild` will use a tricky token `ANALYZE_FOR_ENTRY_COMPONENTS` to propogate components to `entryComponents`. 
But dynamically added routes lacks this I guess.

**Comment by Sri276286** [comment]
@onixie Thanks for your solution. It worked.

But I have one more issue. I am not able to map unmapped routes with resetConfig.
Can you please update that plunk with that

{ path: '**', loadChildren: './error/error.module#ErrorModule' } or 
{ path: '**', component: ErrorComponent }

Both ways I tried and not working.

I am clear on this point from https://angular.io/docs/ts/latest/guide/router.html#!#wildcard-route : 
The router selects the route with a first match wins strategy. Wildcard routes are the least specific routes in the route configuration. Be sure it is the last route in the configuration.

**Comment by Sri276286** [comment]
Raised a new issue for wild card routes. Please check @onixie 
https://github.com/angular/angular/issues/14006

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource support request

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
