### ISSUE TITLE
Possible problem with using Map() objects (or iterators in general) with ngFor

### ISSUE THREAD

**Issue by vivanov-dp** [angular/angular#13877]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

This is just a heads-up. My current workaround is to use an array, but the behaviour the system exhibits with Map() seems very broken.

**Current behavior**
I tried to use Observable<Map<string, T>> to maintain a list of key->object pairs and render them in the view with <li *ngFor="let pair of (list | async)?.entries()">. The values come from a list of objects in Firebase, via my own service - not angularfire2, **and are rendered correctly when the page loads**. 
Few seconds after rendering the view, Angular throws "expression changed after it was checked" and change detection stops - further changing of values in the database do not propagate to the view until the page is reloaded, or routed elsewhere. It also ceases to work for other values on the view, that are outside this ngFor. (Not tested with values that are not delivered by Firebase).
In production mode the exception is of course gone, but change detection still freezes. The exception/freeze also occurs immediately upon changing a value in the database, but that involves switching tabs in the browser and I can't pinpoint it. 

Oddly enough it works just fine if I use an array like `[ [key, object], [key, object], ... ]`. Nothing else changed.

**Expected behavior**
Should render the template and track data changes.

**Minimal reproduction of the problem with instructions**
This is complicated and time consuming for me to minimize and reproduce, here is the function in my service I use to obtain the data (Reference, Query and DataSnapshot are firebase.database.XXX):

This creates some complicated trouble with Angular's change detection:
```
public getMapOnValue<T>(i_ref: Reference|Query): Observable<Map<string|number, T>> {
        return Observable.fromEventPattern(
            handler => i_ref.on('value', handler as (value: DataSnapshot) => any),
            handler => i_ref.off('value', handler as (value: DataSnapshot) => void),
            (snap: DataSnapshot) => {
                let map: Map<string|number, T>  = new Map<string|number, T>();
                snap.forEach(
                    (val: DataSnapshot) => {
                        map.set(val.key, val.val() as T);
                        return false;
                    }
                );

                return map;
            }
        );
}
```
( rendered with `<li *ngFor="let pair of (list | async)?.entries()">` )

This works as expected:
```
public getArrayMapOnValue<T>(i_ref: Reference|Query): Observable<Array<Array<string|number|T>>> {
        return Observable.fromEventPattern(
            handler => i_ref.on('value', handler as (value: DataSnapshot) => any),
            handler => i_ref.off('value', handler as (value: DataSnapshot) => void),
            (snap: DataSnapshot) => {
                let arr: Array<Array<string|number|T>>  = [];
                snap.forEach(
                    (val: DataSnapshot) => {
                        arr.push([val.key, val.val() as T]);
                        return false;
                    }
                );

                return arr;
            }
        );
}
```
( rendered with `<li *ngFor="let pair of (list | async)">` )

Having a Map() in there is the thing that changes. First case destroys change detection, second - doesn't. The link from this function to the view is simply storing the returned Observable in the component as is.

The browser is a current version of Chrome, there is a native Map() in it.
The project is created with angular-cli.

**Please tell us about your environment:**
Windows 8.1, webpack by angular-cli 1.0.0-beta.24, serving via `ng serve` and also a `ng build` via firebase hosting

* **Angular version:** 2.4.1

* **Browser:** [ Chrome 55.0.2883 ]
 
* **Language:** [ TypeScript 2.0.10 ]

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr

**Comment by DzmitryShylovich** [comment]
@vivanov-dp any updates? otherwise it's not actionable and we will close the issue

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource no repro. can be closed

**Comment by kushwahashiv** [comment]
I'm also getting the error

```console
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngForOf: [object Map Iterator]'. Current value: 'ngForOf: [object Map Iterator]'
```

**Comment by alxhub** [comment]
I believe this is user error. `Map.entries()` creates a new iterator each time. Binding to the result of this function will thus always cause change-after-checked errors, regardless of `NgFor`'s iteration logic.
