### ISSUE TITLE
EXCEPTION: Invalid argument '2017-01-11T09:25:14.014-0500' for pipe 'DatePipe'

### ISSUE THREAD

**Issue by anvesh48** [angular/angular#13874]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using date pipe in IE doesn't work it throws an error message in console:
EXCEPTION: Invalid argument '2017-01-11T09:25:14.014-0500' for pipe 'DatePipe'

I have seen there are several open issue regarding date Pipe. But, they are representing the incorrect format. Whereas, the date pipe is not working at all in my case.

**Expected behavior**
The date pipe show work for:
'2017-01-11T09:25:14.014-0500' | date: 'MM/dd/yyyy hh:mm:ss a'

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by tallkid24** [comment]
Also happening in Firefox for me. Chrome seems to work fine though.

**Comment by DzmitryShylovich** [comment]
@anvesh48
Open console in IE and try to create a date from your string 
```
new Date('2017-01-11T09:25:14.014-0500');
```
it's not a valid date in IE.

**Comment by intellix** [comment]
Also not a valid date in Safari. Funnily enough neither is this: `new Date("2017-01-06 23:07:57")`
Safari is a joke

**Comment by anvesh48** [comment]
@DzmitryShylovich You are right. But angular1 worked with the same date format.

**Comment by Toxicable** [comment]
@anvesh48 This isn't Angular1

**Comment by anvesh48** [comment]
@Toxicable I am sorry. It is angular2.

**Comment by DzmitryShylovich** [comment]
I'm working on a fix but npm registry is down in europe :)
