### ISSUE TITLE
http request can't be captured on chrome develpotool network panel

### ISSUE THREAD

**Issue by whimchang** [angular/angular#13871]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

All http request can't be captured on chrome delvelop tool network panel,no matter mock data(in-memory-web-api) or real api,success or failed.
Is it due to chrome version?but i test the firefox and it also can not.
So,how can i get http request detail information,like request header and response header
Chrome version:55.0.2883.87 m (64-bit)

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by matsko** [comment]
@whimchang this needs more information and it needs to be relatable to Angular. If you can produce reproduction that shows Chrome not behaving as expected in this regard with Angular then please reopen the issue.
