### ISSUE TITLE
Router: inconsistent commands for main and named outlets

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#13872]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Router.navigate() method works differently for main outlet and named outlets.
It's valid to pass commands like `['/resource/details', id]` or `['resource', 'details', id]` for main outlet, but named outlet throws error when using first syntax: `[{ outlets: { name: ['/resource/details', id] } }]`

**Expected behavior**
`[{ outlets: { name: ['/resource/details', id] } }]` should be a valid command.

**Minimal reproduction of the problem with instructions**
Demo: https://plnkr.co/edit/lE6AgLsAN5MGRekFBZMp

**What is the motivation / use case for changing the behavior?**
Router API should be consistent.

* **Angular version:** 2.2.0, 2.4.2

**Comment by atscott** [comment]
Confirmed this is still an issue in v9: https://stackblitz.com/edit/angular-ivy-wee8js?file=src%2Fapp%2Fapp.module.ts

**Comment by atscott** [comment]
Note that this is actually true for the "main" commands as well. It's only the _very first_ command in the array that does not encode the slashes: https://stackblitz.com/edit/angular-ivy-pzdhq2?file=src%2Fapp%2Fapp.module.ts
`router.navigate(['/main', 'test/3'])` will also be parsed as main/test%2F3.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
