### ISSUE TITLE
Compiler error when migrated to 4.0.0-beta.2 from 2.3.1

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#13875]
getting the following compiler error :

```
Can't resolve all parameters for in <componentpath....>: ([object Object], [object Object], [object Object], ?).
```

while in 2.3.1 it is compiling perfectly fine.

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by vasuneet** [comment]
The exact error is as below  
 Can't resolve all parameters for StateComponent in D:/va00120386/ATT/NG2/widget-container-framework/app/widget-framework/state.component.ts: ([object Object], [object Object], [object Object], ?).

The stateComponent source code is as below -

import {Component, Output, EventEmitter,OnDestroy} from '@angular/core';

import {ContainerService} from './services/containerservice';
import {LoggerService} from './services/logger.service';
import {WidgetConfigurationService} from './services/widgetconfiguration.service';
import {Http} from '@angular/http';


//declare var module: {
//    id: string;
//};

@Component({
    template:'',
    moduleId:module.id
   
})

export class StateComponent implements OnDestroy {
    myTitle: string = "hello world";
    publishedState: any = {};
    subscribedState: any = {};
    subsharedstate: any = {};
    instancemetadata: any = {};
    configPath: string;
    wid: string;
    containerService: ContainerService;
    widgetConfiguration: any;
    public patternData: string;
    $log: LoggerService;
    widgetConfigurationService: WidgetConfigurationService;
    @Output()
    stateChanged: EventEmitter<any> = new EventEmitter();
    protected _http: Http;

    constructor($log: LoggerService, http: Http, containerService:ContainerService,configPath?: string) {
        this.myTitle = "Your World!";
        this.publishedState = {};
//        this.containerService = ContainerService.getInstance();
        this.containerService = containerService;
        this.widgetConfigurationService = WidgetConfigurationService.getInstance();
        this.$log = $log;
        this._http = http;
        var thisRef = this;
        this.configPath = configPath;
    }

    emitEvent(stateValue) {
        this.stateChanged.emit({ state: stateValue });
        console.log("state Changethis.stateChanged.emit({state:stateValue});d");
    }

    getEmitObject() {
        return this.stateChanged;
    }

    reportEvent(payload) {
        this.containerService.notifyWidgetWithPattern(payload);
    }

    updatesystemrecord() {

    }

    init() {
        this.$log.info(this.widgetConfiguration);
        this.containerService.ngOnInit(this._http);
        var stateComponent: StateComponent = this;
        this.containerService.registerWidgetWithContainer(stateComponent.wid, function(info, type) {
            if (type === 'pub-sub') {
                stateComponent.subsharedstate = info;
            } else if (type === 'record') {
                //stateComponent.updatesystemrecord(info);// This will only work,if underlying widget have the logic
            } else
                stateComponent.$log.warn("widgetService: this type of callback is not supported on widget - " + this.wid);
        });

        this.$log.info(this.wid + ' - is registered with the container for future updates !!!');
        this.containerService.getolderupdates(stateComponent.wid);
        var thisRef = this;
        if (this.configPath != undefined) {
            this._http.get(thisRef.configPath).
                subscribe(function(result:any) {
                    thisRef.widgetConfiguration = JSON.parse(result._body);
                    thisRef.widgetConfigurationService.registerWidgetEvents(thisRef.widgetConfiguration, stateComponent);
                });
        }
        
    }

    publishState() {
        this.containerService.pushWidgetPublishState(this.wid, this.publishedState);
    }
    
    public ngOnDestroy(){
        
    }
}

**Comment by matsko** [comment]
@vasuneet can you please put together a live example of this using plnkr? This can get you started: http://plnkr.co/edit/9LDwpatYrVCbWK0DDQeK

**Comment by vicb** [comment]
Seems like you are trying to inject `configPath?: string` which can not be resolved.

It should probably be something like `@Optional [@Inject(Type)] configPath?: string`

**Comment by vasuneet** [comment]
No this solution doesn't work at all.

**Comment by vasuneet** [comment]
Issue is resolved. I removed this config property at all. it seems anything that cannot be injected will not be resolved here. And string is not injectable just like other services.
