### ISSUE TITLE
NGC doesn't recognize / handle "import * as Something" statments

### ISSUE THREAD

**Issue by NoNameProvided** [angular/angular#13879]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

`app.module.ts` can become quite large if the application (Ionic 2) has a lot of pages, pipes, services and components. So we wanted to simplify the `app.module.ts` by importing types together and make an array from them. Example: 

```typescript
// ... some more content above

import * as Pages from '../pages';
import * as Pipes from '../pipes';

const pages = objectToArray(Pages);
const pipes = objectToArray(Pipes);

// ... some more content

@NgModule({
  declarations: [
    App,
    ...components,
    ...pipes,
    ...pages,
  ],
  imports: [
    // some code
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    App,
    ...components,
    ...pages,
  ],
  providers: [
    { provide: Storage, useFactory: provideStorage },
    { provide: ErrorHandler, useClass: RavenErrorHandler },
    ...services,
  ]
})
export class AppModule {}

``` 

The `objectToArray` function is this:

```typescript
/**
 * This helper function is used in the app.module to extract the imported
 * components.
 */
export function objectToArray(iterableObject: any) : Array<any> {
  return Object.keys(iterableObject).map( key => iterableObject[key])
}
```

This works fine without NGC (aka in ionic serve), but NGC cannot recognize / handle ` import * as Something` statements and throw errors at compile time. Example: 

```
npm ERR!     node ./config/bootstrap.js && ionic-app-scripts build --prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs replaced-mobile
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls replaced-mobile
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/attila/budacode/replaced-mobile/npm-debug.log

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! replaced-mobile@ ionic:build: `npm run build`
W
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the replaced-mobile@ ionic:build script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the replaced-mobile package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs replaced-mobile
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls replaced-mobile
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/attila/budacode/replaced-mobile/npm-debug.log
```

**Expected behavior**
NGC can handle ` import * as Something` statements.

**Minimal reproduction of the problem with instructions**
- Take an Angular 2 project
- Modify `app.module.ts` to import services as `import * as Services from '../your/path/services'`
- In your `NgModule` replace those services instances in the `providers` array with `Object.keys(Services).map( key => Services[key])` line

**What is the motivation / use case for changing the behavior?**
- Allows developers to use NGC with the `import * as` statement
- Allows developers to create a simpler `app.module.ts` file

**Please tell us about your environment:**
* **OS:** macOS Sierra
* **IDE:** VS Code
* **PM:** NPM

* **Angular version:** 2.2.1

* **Browser:** all
 
* **Language:** Tried with TypeScript 2.0.10

* **Node (for AoT issues):** v7.3.0

**Comment by mhevery** [comment]
Sorry but the imports have to be statically analyzable and your `objectToArray ` function prevents that so this can not be supported. You will have to list them all explicitly.

**Comment by darkkean** [comment]
I'm also having the same problem when trying to use a non-typescript module "[numeral.js](http://numeraljs.com/)".

`import * as numeral from 'numeral';`

This was working fine on Angular 2.2.4. Started having his error after upgrading to 2.4.3. Anyone knows why?
