### ISSUE TITLE
Suggestion: use @Angular as name due to  SEAMVER

### ISSUE THREAD

**Issue by PFight** [angular/angular#13878]
With going to SEAMVER now we are not saying Angular 2, but simple Angular. But how we should distinguish between Angular 1 and Angular 2 in that case? There is a lot of data in google, and I want to find only articles for Angular 2. It is not possible already, because there are a lot of articles about Angular 2 RC1,2,... that are not actual.

I suggest choose @Angular as official name, so all mentions of new Angular (Angular 2) would be easy googlable, and no misunderstandings would occur. I think it's good name, because npm packages already are named @angular/common, @angular/core etc.

**Comment by StephenFluin** [comment]
PFight, thanks for your suggestion. 

We're trying to clean up the naming still, but to differentiate the two generations, we're trying to use the names most adopted by the community, namely "AngularJS" for the old generation and "Angular" for versions 2 and later.
