### ISSUE TITLE
Add option to turn on/off animations

### ISSUE THREAD

**Issue by bradyisom** [angular/angular#13881]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is currently no option to dynamically turn on/off animations.

**Expected behavior**
It would be nice to have a method like the old:
```
$animate.enabled(false);
$animate.enabled(true);
```

**What is the motivation / use case for changing the behavior?**
In order to be 508 compliant (Section 1194.21 (h)), we supply the user a setting that turns off all animations. Because the application is an SPA, we need to turn on/off that animation dynamically when a user logs in with that setting.

**Current workaround**
```
import { AnimationDriver } from '@angular/platform-browser';
import { WebAnimationsDriver } from '@angular/platform-browser/src/dom/web_animations_driver';

export function animationFactory(): any {
  const noop = AnimationDriver.NOOP;
  const driver = new WebAnimationsDriver();
  return {
    animate: (
      element: any, startingStyles: any, keyframes: any,
      duration: number, delay: number, easing: string,
      previousPlayers?: any
    ): any => {
      // Check whatever value determines the user setting to hide animations
      if (hideAnimations) {
        return noop.animate(element, startingStyles, keyframes, duration, delay, easing, previousPlayers);
      } else {
        return driver.animate(element, startingStyles, keyframes, duration, delay, easing, previousPlayers);
      }
    }
  };
};

@NgModule({
...
  providers: [
    { provide: AnimationDriver, useFactory: animationFactory }
  ]
...
})
export class AppModule {}
```

**Please tell us about your environment:**
NPM
SPA served as static files

* **Angular version:** 2.3.1

* **Browser:** all
 
* **Language:** TypeScript 2.0.3

**Comment by wawyed** [comment]
Hi, is this something that can be look at? It's stopping us from migrating to angular some of our components that rely on animations, since we have a business requirement to be able to disable animations on demand. 

Do you take PR requests about it? @matsko

**Comment by sherlock1982** [comment]
No longer possible

     import { WebAnimationsDriver } from '@angular/platform-browser/src/dom/web_animations_driver';

Now I need to do something like this to disable animations globally:

    import {
        ɵsupportsWebAnimations,
        ɵWebAnimationsDriver
    } from '@angular/animations/browser';
    
    export function animationDriverFactory(){
        if (!isSelenium && ɵsupportsWebAnimations()) {
            return new ɵWebAnimationsDriver();
        }
        // Disable angular animations if running under selenium control
        return AnimationDriver.NOOP;
    }

Is there at least a proper way to disable all animations?

**Comment by matsko** [comment]
This works now via `<div [@.disabled]="boolExp">`.
