### ISSUE TITLE
ngrepeat of mass cause the block of webpage 

### ISSUE THREAD

**Issue by guguji5** [angular/angular#13883]
I want to show thousand of data using ngRepeat .but the webpage blocks.

it isn't suitable to repeat thousand of data?

**Comment by DzmitryShylovich** [comment]
This is angular2 repo
https://github.com/angular/angular.js/issues

**Comment by guguji5** [comment]
@DzmitryShylovich this link include so many issues.I can't find which answer could solve my problem.
