### ISSUE TITLE
[(ngModel)] binding breaks if template includes specific element

### ISSUE THREAD

**Issue by AsherBarak** [angular/angular#13886]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Observed behavior**
When implementing `ControlValueAccessor` and including `md-select` (from angular-material2) in the template `ControlValueAccessor` methods are not invoked and banana-binding does not work.

**Desired behaviour**
When implementing `ControlValueAccessor` and including `md-select` (from angular-material2) in the template `ControlValueAccessor` methods are invoked and banana-binding works.

**Steps to reproduce**
This plunker contains tow identical components where the only difference is the inclusion of md-select in the template of 'with-select' component. This brakes banana binding as described.
1. Open plunker at http://plnkr.co/edit/BzgXV2?p=preview
2. Watch console and note logs for all events emitted from `ControlValueAccessor` methods on `no-select` component:
![image](https://cloud.githubusercontent.com/assets/6647171/21960670/6e39da8c-dafb-11e6-80f0-6faa37d4ce7c.png)

```
    writeValue(obj: any): void {
      this.val=obj;
                console.log('no-select writeValue: ' + obj);
          };

    registerOnChange(fn: any): void {
        console.log('no-select on change registered');
        this.onChange = fn;
    };

    registerOnTouched(fn: any): void {
      console.log('no-select on touched registered');
        this.onTouched = fn;
    };
```

3. Note `app.component` includes both `no-select` and `with-select` components:
![image](https://cloud.githubusercontent.com/assets/6647171/21960680/ba3ea50c-dafb-11e6-84aa-61e1637638c3.png)
Where the only differences is that `with-select` has `md-select` in it's template:
![image](https://cloud.githubusercontent.com/assets/6647171/21960687/e5610a86-dafb-11e6-8b79-5c32235cad78.png)
and yet all `ControlValueAccessor` methods calls for the `with-select` component are missing from the log (and binding is not functioning).

**See also**
https://github.com/angular/material2/issues/2609

**Comment by DzmitryShylovich** [comment]
Pls add:
1. steps to reproduce
2. observed vs desired behaviour

**Comment by AsherBarak** [comment]
Added to original ^

**Comment by mhevery** [comment]
Please include instructions as to where do I click, what should I see, what should happen, otherwise we spend too much time reverse engineering your intent.

**Comment by AsherBarak** [comment]
Hi @mhevery,
Thanks for looking into this. Added as much details as I could to original issue description above^. The problem is with something **not** happening so it is a bit trickier to document.

**Comment by jelbourn** [comment]
@kara can you take a look at this?

**Comment by kara** [comment]
@AsherBarak This is a bug in md-select, so I'll close this in core and retain the existing issue in the material2 repo, https://github.com/angular/material2/issues/2609.
