### ISSUE TITLE
*ngFor pass always first item as parameter to a custom event

### ISSUE THREAD

**Issue by jorgedkoala** [angular/angular#13896]
**I'm submitting a ...** 
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a component inside a *ngFor loop, whith a custom event created (myevent)="doSomething($event, currentItem)", when fired, currentItem is allways the first item of the ngFor Loop.

**Expected behavior**
expected currentItem of the loop passed to the function.

**Minimal reproduction of the problem with instructions**
Couldn't reproduce the issue in plnkr i have this ready,
http://plnkr.co/edit/XzuNHAU0H1EEvgm16ekU?p=preview
but i can`t get the button work on plunker ¿? so i can`t see if it happens on it.

**the parent html**
```
  <md-list>
      <md-list-item *ngFor="let control of checklistcontroles; let i = index">
          <label (click)="opciones(control)">{{control.nombrecontrol}}</label>
          <my-images [currentControl]="control" (image)="takeFoto($event,control)"         (click)="clickFoto(control,i)" style="width:25%; display:flex; float:left"></my-images>
          <md-slide-toggle class="toggle" [(ngModel)]="control.checked"></md-slide-toggle>
      </md-list-item>
  </md-list>
```

**the function on parent .ts**
```
takeFoto(foto,control){
    control.foto = foto;
    this.base64Image = foto;
  }
```

**here is the child.ts**
```
import { Component, Output, EventEmitter, OnInit } from '@angular/core';

@Component({
  selector: 'my-images',
  templateUrl: './images.html',
  styleUrls: ['./images.scss'],
})
export class Images implements OnInit {
@Output() image: EventEmitter<string>=new EventEmitter<string>();
    constructor() {}
    //Do Some things
...
    var dataUrl = canvas.toDataURL('image/jpeg');
    this.image.emit(dataUrl);
...
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OS: OS X El Capitan
Node Version: v7.2.0
angular-cli: 1.0.0-beta.24
node: 7.2.0
os: darwin x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

* **Angular version:** 2.0.X

My Package.json
```
{
  "name": "tfc-web",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "core-js": "^2.4.1",
    "ng2-translate": "^5.0.0",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3"
  }
}
```
* **Browser:** [all | **Chrome 55** | **Firefox 50.1** | IE XX | **Safari 10** | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | **TypeScript** X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
node: 7.2.0

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunk

**Comment by jorgedkoala** [comment]
http://plnkr.co/edit/XzuNHAU0H1EEvgm16ekU?p=preview
i can`t get the button work on plunker ¿? so i can`t see if it happens on it.
Updated on Question

**Comment by DzmitryShylovich** [comment]
> i cant get the button work on plunker

this is exactly why you shouldn't use native element names for your custom components. Change `option' to something else http://plnkr.co/edit/hWLhcgQesd7DxziVocxa?p=preview

**Comment by DzmitryShylovich** [comment]
@jorgedkoala what is the expected behavior in your plunkr?
http://plnkr.co/edit/RUlESYed4FizvcwZDLI5?p=preview to me everything works as intended

**Comment by jorgedkoala** [comment]
it works well in plunkr, but not in my project, i'll try to reproduce.

2017-01-12 20:22 GMT+01:00 Dzmitry Shylovich <notifications@github.com>:

**Comment by jorgedkoala** [comment]
I could reproduce the behavior, it happens when using a label to trigger. click on the button works well, click on the label not.
http://plnkr.co/edit/XzuNHAU0H1EEvgm16ekU?p=preview

**Comment by devoto13** [comment]
Because every form element created by loop has same `id`. And `id` should be unique on the page.  See documentation for `for` attribute [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label). Ensure that ID is unique by adding index to it for example and it will work (see http://plnkr.co/edit/WRUyg7MDOP94AJfZlbyg?p=preview).

I don't think it has anything to do with Angular or `ngFor`.

**Comment by jorgedkoala** [comment]
You are right. Thank you very much.
