### ISSUE TITLE
use ng-content more than once

### ISSUE THREAD

**Issue by fredrik-macrobond** [angular/angular#13894]
**I'm submitting a ...**  (check one with "x")
[x ] feature request

**What is the motivation / use case for changing the behavior?**
For instance, while building a recursive component such as a tree view, I would like to be able to reuse ng-content at least twice in the same template: Once for the node, and once for the recursive child nodes created in a ngFor loop.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add s small repro in plunk of what are you trying to accomplish

**Comment by mhevery** [comment]
`<ng-content>` moves children from the view to the a new location. It can't duplicate them and insert them twice. Works as intended.

**Comment by michaelbushe** [comment]
See nelibijil's solution: https://github.com/angular/angular/issues/22972#issuecomment-407358396

**Comment by oliverjanik** [comment]
This is all good and well. What's the recommended approach for the indented use-case?

**Comment by mlc-mlapis** [comment]
@oliverjanik ... a recommended approach for what? For duplication of that content?

**Comment by oliverjanik** [comment]
Yes, that's what the titles says.

**Comment by mlc-mlapis** [comment]
@oliverjanik ... as it was explained before ... transcluded content is processed by the Angular compiler which creates all necessary JS code for later use, which is run in run-time automatically then. Without severe changes / extending of API, it's hard to do it.
