### ISSUE TITLE
Mouseleave sometimes never fired

### ISSUE THREAD

**Issue by philjones88** [angular/angular#13911]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular (2.4.1) will not get the mouseleave event and results in the page element being "stuck" on hover.

**Expected behavior**
Coming from `ng-mouseenter` and `ng-mouseleave` (from memory) this used to be fine and the hover never "stuck"

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/TApW8fbiCSw0DNuzvV5X?p=preview

Roll you mouse up and down vertically over the elements checking if any get stuck like this:

![screen shot 2017-01-13 at 11 05 09](https://cloud.githubusercontent.com/assets/677167/21928125/eeac7278-d980-11e6-8b85-aa0b9fcdd10c.png)

I output to console too to check if it ever fires, you'll see "one" fires enter but never leave:

![screen shot 2017-01-13 at 11 20 11](https://cloud.githubusercontent.com/assets/677167/21928406/8351fc8a-d982-11e6-911a-9f407dbc5c29.png)

Please note this is a reproduction, a few question/answers as to why the weird code:

1. We run outside the zone as this page it comes from shows a list of elements that are refreshed by a HTTP request and Protractor won't mark the zones as stable otherwise.

2. Why interval? I did intend to use an Observable timer but Plunkr didn't like it.

3. I've also confirmed the same behaviour with `(mouseenter)=".."` and `(mouseleave)=".."`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Angular 2.4.1
Typescript: 2.0.10
This happens in Chrome Version 55.0.2883.95 (64-bit)
OSX 10.12

* **Angular version:** 2.4.1/2.4.3

* **Browser:** Chrome 55.0.2883.95 (OSX), Firefox 50.10 (OSX), not tested further
 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Can't u try to reproduce with `el.addEventListener()`? Angular doesn't do anything with native events

**Comment by philjones88** [comment]
@DzmitryShylovich something like https://plnkr.co/edit/dJgTx4lBvvrffNVIKTD5?p=preview ?

I can't get that to loose mouseleave events, so maybe it's the solution.

**Comment by DzmitryShylovich** [comment]
> something like https://plnkr.co/edit/dJgTx4lBvvrffNVIKTD5?p=preview ?

yeah

> I output to console too to check if it ever fires, you'll see "one" fires enter but never leave:

probably because you moved your mouse too fast.

Don't think we can do anything with it. Angular just uses native `element.addEventListener` under the hood.

**Comment by philjones88** [comment]
@DzmitryShylovich is there a more raw way to do this then?

I tried the second plunkr using `Renderer`'s `listen()` in my actual app and it still misses a `mouseleave` event so that workaround as I think you said doesn't do anything to help the issue.

**Comment by philjones88** [comment]
Could  close, but it might good be a good record for anyone else with angular mouseenter / mouseleave problems.

After lots of googling, seems to be other frameworks having the issue too.

Moved away from `mouseenter`/`mouseleave` in favour of CSS instead.
