### ISSUE TITLE
Support injection of ElementRef for root element

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#13919]
In AngularJS, one could inject `$rootElement` to get the root DOM element of the Angular application. 

For Angular Material, we want something like this so that we can check the DOM outside of the Angular application for the presence of a `dir` attribute that sets an `rtl` or `ltr` context.

You can _kind of_ do this today, but it's rather clunky:
```ts
  _getAppRootElement(injector: Injector): HTMLElement {  
    for (let i = 0; i < this._appRef.componentTypes.length; i++) {
      if (injector.get(this._appRef.componentTypes[i])) {
        return this._appRef.components[i].location.nativeElement;
      }
    }
  }
```
(see https://github.com/angular/material2/pull/2286)
* Because you can bootstrap multiple components, you have to figure out which one you're inside of for any given directive. The only way to do this is to use the `Injector` instance from that directive and attempt to get the component instance from `appRef.componentTypes`
* `ApplicationRef` contains a list of `ComponentRef`s from which we can get the `ElementRef`, but they're not available until bootstrap is completed. This means that `getAppRootElement` has to be called asynchronously, which makes the directive-facing API async, which is undesirable. 

It would be grealty helpful here to be able to directly inject the root component's `ElementRef` directly via a token. Something like
```ts
@Component({...})
class MdMenu {
  constructor(@Inject(APP_ELEMENT) appElement: ElementRef) { }
}
```

**Comment by tsvetomir** [comment]
Isn't it a better idea to set the text direction using an opaque token, similar to LOCALE_ID?
Or do you expect to be able to set the text direction outside the application?

Having to reference the DOM doesn't sound great for Universal.
