### ISSUE TITLE
Set return type for Renderer.invokeElementMethod() to any.

### ISSUE THREAD

**Issue by isaacplmann** [angular/angular#13916]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`Renderer.invokeElementMethod()` has a return type of `void` when it actually returns whatever the underlying method returns.

**Expected behavior**
`Renderer.invokeElementMethod()` has a return type of `any`.

**What is the motivation / use case for changing the behavior?**
Many element methods have return values.  One potential use case:

```ts
const myElement: Element = this.renderer.invokeElementMethod(elementRef.nativeElement, 'querySelector', ['.myElement']);
```

* **Angular version:** 2.4.1

* **Browser:** all

 
* **Language:** TypeScript 2.0.10

**Comment by mhevery** [comment]
We are planning on removing it. Won't fix.
