### ISSUE TITLE
Unsubscribe from event emitters during dehydration

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#1391]
- Create DirectiveA that has an event emitter.
- Store the reference to DirectiveA in a global variable
- Dehydrate the host view of DirectiveA and rehydrate it again
- Call DirectiveA to fire an event through the event emitter

Expected result:
The view should not receive the event

Actual result:
The view will receive the event

**Comment by mhevery** [comment]
@vsavkin can you verify this is still an issue.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
