### ISSUE TITLE
ASP.NET Core - Running two ng2 apps with prerendering

### ISSUE THREAD

**Issue by deliberaligiacomo** [angular/angular#13927]
Hey guys, can someone take a look at [https://github.com/aspnet/JavaScriptServices/issues/566](https://github.com/aspnet/JavaScriptServices/issues/566) issue regarding building two angular 2 apps in ASP.NET Core with prerendering feature? Cannot figure it out. Any example/suggestion will be appreciated

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
