### ISSUE TITLE
entryComponents in lazy loaded module is not working

### ISSUE THREAD

**Issue by MickL** [angular/angular#13926]
**I'm submitting a ...** 
[X] bug report
[ ] feature request
[ ] support request 

**Current behavior**
Inside a lazy loaded module entryComponents is not working.

If i import the module in root `app.module.ts` or declare entryComponents there its working fine. But as soon as the module is lazy loaded i get the following error message:

`No component factory found for xComponent. Did you add it to @NgModule.entryComponents?`
_(yes i did!)_

**Expected behavior**
entryComponents should work in lazy loaded module, too.

**Please tell us about your environment:**
angular-cli: 1.0.0-beta.24
node: 6.9.1
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

**Browser:**
all
 
**Node (for AoT issues):**
`node --version` =  6.9.1

**Also seen here:**
https://github.com/angular/material2/issues/2517
https://github.com/angular/material2/issues/1765

**Comment by DzmitryShylovich** [comment]
Pls add a small demo in plunkr

**Comment by MickL** [comment]
You may close this issue.
The problem was specific to [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) which is imported with `NgbModule.forRoot()`. Im not sure what this forRoot() means but Angular Material got rid of it to get entryComponents with lazy loading working.

In fact component creation is working fine, but i get this error as soon as i work with the ng-bootstrap. 

I fixed the problem by importing this module inside of my submodules even if i need a singleton for my whole application.

**Comment by DzmitryShylovich** [comment]
You can close it yourself :)

**Comment by izverev-aexsoft** [comment]
@MickL this worked! Angular black magic.
