### ISSUE TITLE
AOT : no newline at eof of generated file triggers tslint error

### ISSUE THREAD

**Issue by wardbell** [angular/angular#13924]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request
```

**Current behavior**

Our docs CI build fails on a linting error because AOT generated a file without a new line at eof for a styles file.

```
[23:29:55] [gulp-tslint] error inheritance/ts/aot/app/base.component.css.shim.ngstyle.ts[8, 97]: file should end with a newline
```

**Expected behavior**
Although we could try to suppress the error, someone else is bound to suffer. We should generate newlines, yes?

**Minimal reproduction of the problem with instructions**

Here's the build failure:  https://travis-ci.org/angular/angular.io/jobs/191798891

Here's the source (with newline at eof):
```
#speak { font-style: italic;  color: blue; }

```

Here's the AOT generated file (no newline at eof):
```
/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['#speak[_ngcontent-%COMP%] { font-style: italic;  color: blue; }'];
```

Yes ... I now see the ` /* tslint:disable */`.  I don't know why that was ineffective. I am checking on that on our end.

**Update:** Linting appears to ignore ` /* tslint:disable */` for this particular "newline missing eof" problem. It disables other complaints but not that one. The AOT compiler doesn't generate an EOF newline for _any_ of its files. Not just a style file concern.  Solution: always generate that newline.

**Environment**
Angular 2.4.0
@angular/compiler-cli@~2.4.0",

Windows

**Comment by vicb** [comment]
`/* tslint:disable */` -> open a bug again tslint

**Comment by wardbell** [comment]
It sure looks like their fault. But do you think adding a newline at the end of generated files is a bad thing?
