### ISSUE TITLE
Transcluded components hooks works incorrectly with upper `*ngIf` state

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#13921]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Transcluded via `ng-content` components `OnInit` and `AfterViewInit` hooks are triggered despite parent component `ngIf` state. `OnDestroy` hook does not triggered on removing from DOM.

**Expected behavior**
Hooks should be triggered only when component really are added/removed from DOM.

**Minimal reproduction of the problem with instructions**
Plnkr http://plnkr.co/edit/RkOXyEtvMNoSNLeAh8Jf?p=preview

`MenuItemComponent` `OnInit` and `AfterViewInit` hooks triggered despite `MenuComponent` `ngIf` false value and `OnDestroy` never fires despite component removing from DOM.

* **Angular version:** 2.4.3

**Comment by mhevery** [comment]
Works as intended. view children are always created regardless if they are projected or not. This is by design.

**Comment by artaommahe** [comment]
@mhevery em.. but what with menu/tabs components if their items depends on some data that should be updated before menu opens and has a lot of handlers in `OnInit` `AfterViewInit` `OnDestroy` hooks? Why this components should be init when they are not needed and should not do anything, that is controlled by upper `ngIf`.

**Comment by artaommahe** [comment]
Also as i understand `AfterViewInit` guarantees that component is added to DOM here that is wrong with this transclusion behavior.

**Comment by mhevery** [comment]
Then enclosed the content of in `*ngIf`. This is how web-components work and we are just following the spec here.

**Comment by artaommahe** [comment]
@mhevery so for any component there is no guarantees that init/destroy hooks will be related to component DOM existing state and depends on outer context that cant be detected from this component?

**Comment by artaommahe** [comment]
I cant understand hos this should be useful with menu-like elements that always uses transclusion and menu items should not be initialized until they are realy added (menu is open). It's break all menu behavior logic.

**Comment by mhevery** [comment]
Your demo has:

```
<menu>
  <menu-item></menu-item>
</menu>
```

Therefore `menu-item` instantiates in all circumstances. One can not have proper encapsulation if internal implementation details of `menu` will determine wether or not `menu-item` will be instantiated. We need to be able to reason about things without having global application knowledge.

Sorry this behaves as intended.

**Comment by artaommahe** [comment]
@mhevery but what with hooks? Does this realy mean that they have nothing to do with component DOM state?
It would follow that any code that depends on component template, children components/directives or component DOM instance should have a lot of checks to determinate if component in DOM or not.

Also with tabs - if we have any heavy work in component that in hidden tab, this work will be done despite tab is active or not. It could be a lot of http/websocket requests, data formating or smth like this.

**Comment by artaommahe** [comment]
There is more - anything inside `<menu-item></menu-item>` will be instantiated too despite it's needed or not.
http://plnkr.co/edit/2aaRtK3rppO9Qi8zWaWi

```
MenuItemComponent ngOnInit
MenuItemContentComponent ngOnInit
MenuItemContentComponent ngAfterViewInit
MenuItemComponent ngAfterViewInit
```

and all of this with no elements in dom, no `OnDestroy` calls..

**Comment by artaommahe** [comment]
Looks like this is solution, thx to Günter
http://stackoverflow.com/a/41655566/5803093

**Comment by amcdnl** [comment]
I want to add this is definitely not expected and if not known and handled can cause huge performance issues in instances like tabs.

**Comment by montella1507** [comment]
@mhevery if Initi hooks are called, even the component is not in DOM, why is not called NgOnDestroy aswell? I cannot see the logic there.

**Comment by mlc-mlapis** [comment]
@montella1507 ... because the instance still exists ... it is instantiated / destroyed in relation to the host.

**Comment by montella1507** [comment]
@mlc-mlapis  well that makes sense actually...  

<X> //ng-content inside 
  <Y (click)="foo()">  // transcluded
 </Y>
</X>

The Y instance is in X instance (thats what you said).  However.. if this is your argument, why is not component Y in case:
x.component.html
<div *ngIf="boolean">
  <Y> </Y>
</div>
 created with component X when the condition is false?

**Comment by mlc-mlapis** [comment]
@montella1507 ... what is exactly component X?

Generally ... if the template `abc.component.html` of the component ABC contains ...
```
<div *ngIf="boolean">
  <Y> </Y>
</div>
```
then `<div *ngIf="true">` would mean creating a new instance of component Y and inserting it to the DOM and with `<div *ngIf="false">` it is reversed.

But with transcluded content, like ...
```
<ABC> //ng-content inside 
  <Y (click)="foo()">  // transcluded
 </Y>
</ABC>
```
the instance of component Y is created in the same moment when the instance of the component ABC and it is kept regardless of the conditional logic and `*ngIf` applied on `<ng-content>` inside the template of ABC. All of that (generated JS code) is defined by Angular compiler when HTML templates are compiled (AOT / JIT) and on not during run-time.

**Comment by montella1507** [comment]
@mlc-mlapis  it was typo .. at first, ABC component was X in my text i had some problems with "encoding" in this editor.. sorry for that.

I understood all you have written... but still cannot overcome how to solve that problem when your component is used in ng-content...

When you are creaing your components, you have connected *View and *Init lyfecykle hooks with existence in DOM, because it works like that in every other situation... 

And now.. it works different way => lifecykle hooks are done yet but your component doesn't exist in DOM at all..

Of course the fix in most scenarios lends in adding *ngIf to your component too..

<abc *ngIf="boolean">
  <Y *ngIf="boolean">
  </Y>
</abc>

but if you look at that, you thinks it is not correct way...

**Comment by mlc-mlapis** [comment]
@montella1507 ...

> lifecykle hooks are done yet but your component doesn't exist in DOM at all.

Exactly ... Angular has its inner abstraction model which is applied to the DOM when necessary ... and it is true that the model contains more information then the DOM itself. That's also the reason why it is absolutely a wrong way to touch the DOM in those parts that are under control of Angular.

> Of course the fix in most scenarios lends in adding *ngIf to your component too.

Not necessarily. The most important is to understand the difference. Only in the cases of really massive transcluded content it can be suitable to count with memory consumption, timing and so on.

Also with `Ivy ` new renderer on the way we will see what will be added to this area ... especially with relation to `@ContentChild` and `@ContentChildren` and more dynamic behavior of `<ng-content>` itself.

**Comment by trotyl** [comment]
> lifecykle hooks are done yet but your component doesn't exist in DOM at all.

An Angular application can be entirely bootstrapped in a detach element, having a living component with detach element node is still valid case.

**Comment by montella1507** [comment]
@mlc-mlapis  i got you, however,.. we cannot strictly abstract from DOM...  It is relative common scenario when you need to call external 3rd party library like:

`someExternalMapLibrary.init(el.nativeelement)` 
 to create Map element on native element... the place you wanna make it is   AfterViewInit, right?  .. however .. if your AfterViewInit is called and "you" aree not in DOM it will fail? 

How do you wish to make your code safe (when manipulating DOM directly) if AfterViewInit is triggered, but you dont have needed elements in DOM? 

I have encountered this problem with ng-content when:
1) Captcha in ng-content 
2) Google map in mat-tab
3) any graph librabry in mat-tab

**Comment by trotyl** [comment]
@montella1507 As "Angular application can be entirely bootstrapped in a detach element", any component MUST NOT assume their host elements being mounted in `document` (if wanted to be robust). If your case require it being attached, then the component should guard that by itself.

**Comment by mlc-mlapis** [comment]
@montella1507 ... yep, you are right in that. Some of those third party libs are not able to work on the nodes which are not in DOM. Then you have to add some your custom logic to control what to invoke and when ... in relation if the node is or isn't in DOM.

**Comment by montella1507** [comment]
"Angular application can be entirely bootstrapped in a detach element"

thats good point. So basically what is AfterViewInit hook for? 

From definition:
"A lifecycle hook that is called after Angular has fully initialized a component's view"

what is component's view? From my POV it is DOM in BrowserModule, native ui in nativescript etc...

**Comment by trotyl** [comment]
@montella1507 DOM is only a representation, a detached element is totally valid DOM (there's no such thing of "in DOM"), just not being a descendant of `document` node.

**Comment by mlc-mlapis** [comment]
@montella1507 ... `component view` is one of the element of the Angular abstraction model. The other thing is how `BrowserModule` implements it in DOM, ... and there are other possibilities ... SSR, web workers, ... totally AI environments 😄  ... hundred variants.

**Comment by montella1507** [comment]
@trotyl  @mlc-mlapis  well... you helped me a lot, thank you. both of you.
