### ISSUE TITLE
Angular2 has not meet the competing library(frameworks) sizes or its touted claim in introduction

### ISSUE THREAD

**Issue by vairamsvsjdo** [angular/angular#13939]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When building a hello world (app works), There is a bloated amount of library build for vendor package while the rivalling vuejs and other libraries are much smaller. Or the size touted to reach 50KB stated in a conference has not been met.
**Expected behavior**

Make angular much smaller and smaller packages in code size
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Performance
**Please tell us about your environment:**

Windows , Linux, does not matter
* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All
* **Node (for AoT issues):** `node --version` = 6.9.4

**Comment by vicb** [comment]
Check https://github.com/alexeagle/closure-compiler-angular-bundling for a more accurate state - TLDR hello world is ~34k with.

Minimizing the delivered code size is on the top of our priority list and you should see better numbers in the coming months - we are also working on easing the build process for apps.

Stay tuned, meanwhile I hope this answers your questions.

**Comment by vairamsvsjdo** [comment]
Yes, do you have a issue number to know when that changes state or is it in development?
