### ISSUE TITLE
StoreDevtoolsModule.instrumentStore not compatible with AOT

### ISSUE THREAD

**Issue by born2net** [angular/angular#13937]
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior**
static analysis error with the popular ngrx instrumentOnlyWithExtension

**Expected behavior**
no error

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
not get an error and work instrumentStore

```
StoreDevtoolsModule.instrumentStore({maxAge: 3}),
```

angular-cli: 1.0.0-beta.25.5
node: 6.5.0
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.2.1
@angular/compiler-cli: 2.4.3
@angular/language-service: 2.4.3

```StoreDevtoolsModule.instrumentOnlyWithExtension()```  works with AOT.
```StoreDevtoolsModule.instrumentStore not compatible with AOT```

getting an error of:

```
ERROR in Error encountered resolving symbol values statically. Calling function 'StoreDevtoolsModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/msweb/studiotouch/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/studiotouch/src/app/app.module.ts
```

**Comment by DzmitryShylovich** [comment]
how is this related to angular?

**Comment by born2net** [comment]
opened at: https://github.com/ngrx/store/issues
