### ISSUE TITLE
There is no way I can get to display nested Json.

### ISSUE THREAD

**Issue by dannymorales** [angular/angular#13933]
Hi guys,

I have tried to display my nested json in angular 2 but there is no way I can do it. I have tried everything. I guess I have to wait until angular 2 is more developed.

**Comment by koolshams** [comment]
@dannymorales 

Please share some code/links so that everyone knows what is the actual problem. There may be some workarounds if you share more details.

Thanks

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
