### ISSUE TITLE
Docs for `OpaqueToken` seem to be wrong

### ISSUE THREAD

**Issue by zoechi** [angular/angular#13944]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

https://angular.io/docs/ts/latest/api/core/index/OpaqueToken-class.html

> Using an OpaqueToken is preferable to using strings as tokens because of possible collisions caused by multiple providers using the same string as two different tokens.
> 
> Using an OpaqueToken is preferable to using an Object as tokens because it provides better error messages.

**Expected behavior**

It should be just 

> Using an OpaqueToken is preferable to using strings as tokens because of possible collisions caused by multiple providers using the same string as two different tokens.

AFAIK there is no `Object` supported as token. Looks like a leftover to me, but might be wrong...

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> there is no Object supported as token

?

**Comment by alexzuza** [comment]
Can you check this https://plnkr.co/edit/BxbV5ppwnHIk8fiJDkiy?p=preview?

**Comment by zoechi** [comment]
@alexzuza Interesting, but to me it looks like a quite complicated way to provide a string token.

**Comment by DzmitryShylovich** [comment]
So what's the problem here? Can you pls reword? You should be able to use anything as a DI token

**Comment by zoechi** [comment]
There was a question on SO about what kind of tokens are supported for providers with a reference to the code docs and I found the last paragraph confusing, because I never heard of object token. The DI docs don't mention it either AFAIK. 

The paragraph looked like a leftover to mem because the same could be expressed more briefly by mentioning `string` and `object token` in the paragraph before instead.

**Comment by wKoza** [comment]
@zoechi,  in [https://angular.io/docs/ts/latest/guide/dependency-injection.html](https://angular.io/docs/ts/latest/guide/dependency-injection.html) , the definition of OpaqueToken is : 

> One solution to choosing a provider token for non-class dependencies is to define and use an OpaqueToken.

 I think is a good definition simply.

**Comment by zoechi** [comment]
@DzmitryShylovich the 2nd paragraph (object token) was actually about error messages, while the first (OpaqueToken) is about uniqueness. 
If object token is actually a think, then this can be closed.

**Comment by DzmitryShylovich** [comment]
@zoechi 
> If object token is actually a think

https://github.com/angular/angular/issues/13314#issuecomment-265869531

**Comment by zoechi** [comment]
@DzmitryShylovich thanks a lot.
