### ISSUE TITLE
"module": "es2015" in `tsconfig-build.json` breaks possibility of using ts source maps

### ISSUE THREAD

**Issue by maximusk** [angular/angular#13949]
Currently, `tsc` is configured to `"module": "es2015" ` in [tsconfig-build.json](https://github.com/angular/angular/blob/master/modules/%40angular/common/tsconfig-build.json).
This breaks possibility of using `ts` source maps until there is a browser that supports `es6 modules`. Is it possible to compile modules into `commonjs`?

**Comment by IgorMinar** [comment]
This is a dupe of #19841
