### ISSUE TITLE
Benchpress is causing webdriver commands to queue up unexpectedly

### ISSUE THREAD

**Issue by juliemr** [angular/angular#1394]
Normally, the selenium-webdriver node module should wait for each webdriver command to complete before scheduling a new one. For example:

```
23:28:35.869 INFO - Executing: [get: about:blank])
23:28:35.902 INFO - Done: [get: about:blank]
23:28:35.922 INFO - Executing: [get: data:text/html,<html></html>])
23:28:35.945 INFO - Done: [get: data:text/html,<html></html>]
23:28:36.032 INFO - Executing: [execute script: return window.location.href;, []])
23:28:36.037 INFO - Done: [execute script: return window.location.href;, []]
```

But when benchpress is running, it somehow gets around this and causes multiple commands to queue up at once:

```
23:36:36.804 INFO - Executing: [get: http://localhost:8001/benchmarks/src/element_injector/element_injector_benchmark.html?iterations=20000])
23:36:36.814 INFO - Executing: [find elements: By.cssSelector: #instantiateDirectives])
23:36:36.938 INFO - Done: [get: http://localhost:8001/benchmarks/src/element_injector/element_injector_benchmark.html?iterations=20000]
23:36:37.029 INFO - Done: [find elements: By.cssSelector: #instantiateDirectives]
```

The symptom has been stale element errors when upgrading to node 0.12, but the bad ordering occurs in both node 0.10 and 0.12

**Comment by tbosch** [comment]
Julie, this is because benchpress is using a different Promise
implementation than selenium webdriver. However, as selenium webdriver now
provides an A+ compatible implementation of promises, we could use these.
Is protractor already using this new selenium-webdriver version (don't
remember the exact numbers...) / could you create a new protractor version
that does this?

**Comment by juliemr** [comment]
Protractor is using selenium-webdriver@2.45.1, which uses A+ compatible promises.

**Comment by tbosch** [comment]
Oh, sweet. Thanks!

So, to fix this issue, benchpress should overwrite the global `Promise`
function with an implementation based on selenium-webdriver promises. The
override should happen here:
https://github.com/angular/angular/blob/master/modules/benchpress/index.cjs

**Comment by juliemr** [comment]
Yup, the issue, more precisely, is that the custom `waitFor` method is being scheduled as a child of a navigation command, instead of as a sibling after it.

We don't actually have to overwrite the global `Promise` everywhere, we could just explicitly wait for navigation to be done before letting the sampler complete. See https://github.com/angular/angular/pull/1399

**Comment by juliemr** [comment]
#1399 is committed, this can be closed.
