### ISSUE TITLE
Picture tag doesn't work if inside angular app

### ISSUE THREAD

**Issue by RatkoR** [angular/angular#13947]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`<picture>` tag can have multiple images defined. Browser chooses which one to load based on media queries and your browser's size. An example would be:

```
<picture>
      <source media="(min-width: 1280px)"  srcset="https://placehold.it/400x400">
      <source media="(min-width: 1024px)"  srcset="https://placehold.it/300x300">
      <source media="(min-width: 640px)"  srcset="https://placehold.it/200x200">
      <source srcset="https://placehold.it/100x100">
      <img alt="" src="https://placehold.it/401x401">
</picture>
```

If `<picure>` tag is inside angular app, it always loads only the top image. `<picture>` tag outside of an angular app loads images correctly.

Warning: `<picture>` tag *works* in chrome. It doesn't work in (at least) Firefox and Safari. Don't know about IE and edge.

**Expected behavior**
Should load images correctly.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/qpokJtZi6U3jP864rO9X?p=preview

Try opening this link in Firefox and then resize your window. `<picture>` tag that is not in angular app works correctly and the one that is in app doesn't. They are the same tags, copy-pasted.

**What is the motivation / use case for changing the behavior?**
We'd like to load only smaller images if user has mobile browser or hasn't opened his browser in fullscreen.

**Please tell us about your environment:**
Vhecked on ubuntu and iOS.

* **Angular version:** 2.4.1

* **Browser:** [Firefox XX | IE ?? | Safari | iOS ]

**Comment by DzmitryShylovich** [comment]
Does work in Edge

**Comment by alexzuza** [comment]
I think the problem here is in order of insertion tag in DOM. Seems Firefox wants that attributes to be applied at first and then could be insert tag in the DOM

We can see it on this plunker. It's just copy of what angular2 does internally when draws UI

https://plnkr.co/edit/rZ6kcsDH33jNxF7dtY3T?p=preview

**Comment by DzmitryShylovich** [comment]
@RatkoR I've just tested https://plnkr.co/edit/rZ6kcsDH33jNxF7dtY3T?p=preview in Mozilla Nightly and it does work as expected. Can you confirm?

**Comment by RatkoR** [comment]
Yes, the rZ6kcsDH33jNxF7dtY3T plunkr works correctly in FF (51.0.1 and 
52.beta).

Dzmitry Shylovich je 30. 01. 2017 ob 17:42 napisal:

**Comment by DzmitryShylovich** [comment]
it was wrong plunkr. nvm.

**Comment by DzmitryShylovich** [comment]
still valid in 4 http://plnkr.co/edit/L82QctoGAVVJGvwyCpLJ?p=preview

**Comment by RatkoR** [comment]
Thank you @DzmitryShylovich.

I'd really like to have this picture tag working for our project. Is there any way we can help to get your patch accepted or is it something browsers will have to fix?

**Comment by DzmitryShylovich** [comment]
@RatkoR we think it's a browser bug https://github.com/angular/angular/pull/13956#issuecomment-276099258

**Comment by tbosch** [comment]
This is working in safari now, but still not in Firefox.
This is also related to https://github.com/angular/angular/issues/13699.

Keeping it open as I think we can change the order for appending vs setting attributes easily.

**Comment by davec21** [comment]
This bug is definitely a pain. Worked around it by echoing out the media width so that the element is rebound after initial render (which fixes it on FF).

ie:
`let mediuamRes = 1024px;` in ts

`<source srcset="assets/images_1024/logo.png" media="(max-width: {{mediumRes}})">` in html.

Not the cleanest workaround but it at least works.

**Comment by stevengunneweg** [comment]
Any news on this issue?

**Comment by an0o0nym** [comment]
@davec21's answers seems to work for me!

However I have found out (using FF 57.0 Beta Responsive Design Mode & `Network` tab on Developer), that when screen image `plane@2x.png` is fetched from the server as soon as screen width is `830px`. The same happens for `plane@3x.png` -  as soon as the screen width reaches `1170px`.

```
<picture class="plane">
        <source srcset="assets/img/plane/plane@3x.png" media="(min-width: {{widthL}})">
	<source srcset="assets/img/plane/plane@2x.png" media="(min-width: {{widthM}})">
	<source srcset="assets/img/plane/plane.png" media="(min-width: {{widthS}})">
	<img class="plane" src="assets/img/plane/plane.png">
</picture>
```
where `widthL=1200px`, `widthM=992px`, `widthS=768px`

**Comment by DanDrix8391** [comment]
`<source srcset="assets/images_1024/logo.png" media="(max-width: {{mediumRes}})">`
It worked for me. THANKS!

**Comment by sergio-rojasa** [comment]
I still can't get my to work
`<picture>
        <source type="image/webp"  srcset="assets/ham-toe-touch.webp" media="(min-width: 1200px)">
        <source type="image/jpeg"  srcset="assets/ham-toe-touch.jpg"  media="(min-width: 500px)">
        <img src="assets/ham-toe-touch.jpg"  alt="" />
      </picture>`

**Comment by pkozlowski-opensource** [comment]
This issue is related to the element attribute setting vs. insertion order as [pointed out](https://github.com/angular/angular/issues/13947#issuecomment-272955518) by @alexzuza (thnx!)

But it also turns out that both FFox and Safari changed their behaviour so things work properly with the latest Angular on those browsers as well: https://stackblitz.com/edit/angular-mfbe6f

I'm going to close this issue here since:
*  browsers seem to support this scenario now;
* we are changing order of attribute vs. element insertion order with ivy.

**Comment by Achmed4** [comment]
Thanks @alexzuza your solution solved the issue for me.

**Comment by Achmed4** [comment]
> I think the problem here is in order of insertion tag in DOM. Seems Firefox wants that attributes to be applied at first and then could be insert tag in the DOM
> 
> We can see it on this plunker. It's just copy of what angular2 does internally when draws UI
> 
> https://plnkr.co/edit/rZ6kcsDH33jNxF7dtY3T?p=preview

Thanks @alexzuza your solution solved the issue for me.

**Comment by chris13524** [comment]
I was able to simplify the workaround to the below. No need for a variable in the component.

`<source srcset="image.png" media="(max-width: {{'500px'}})">`

I'm a little confused about the status of this issue. Firefox 66 still doesn't like the order that Angular 7.2 is putting stuff in. Also, what's ivy?
