### ISSUE TITLE
Async pipe doesn't read (or update) ngrx/store observables when triggered from specific places (Google API's callbacks)

### ISSUE THREAD

**Issue by tiangolo** [angular/angular#13957]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Google API's calls take a callback, when dispatching an ngrx/store "action" from that callback, the store receives and updates the value. Even observers subscribed to that value receive it, but `async` pipes don't take the value.

But if there's an event (a click in a button) then the `async` pipes update their content.

But when called from any other place different than those callbacks (even `setTimeout`) `async` works normally.

Interestingly, when the `ngrx/store-devtools` is configured and the Redux Chrome extension installed, everything works normally.

**Expected behavior**

Whenever there's a new value in an observer, sent from any place, the `async` pipe should work and update its value.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/79WK9dEItgEFsHLBSN1T

*Short version*

* If you click the "Authorize" button for the first time, it triggers an authorization screen to read Gmail data using Google APIs and it stores the fact that it is authorized in `ngrx/store` as `authorized`.
* After you reload, the code tries to use the same authorization you gave and stores the result in `ngrx/store` as `authorized` (as when you clicked the button).
*  `ngrx/store` sends the new values to observers, if you open the console you will see there are observers just `console.log`ing the new values they receive.
* The new values won't show up in the page in their sections with `async` pipes.
* If you click any of the buttons in the page, that will send new actions to `ngrx/store`, but most importantly, all the places with `async` pipes will suddenly update with all the values they should have, previous and new.

**Note**: as the `console.log` subscribers do get the values and output them normally, I think this is not a [ngrx/store](https://github.com/ngrx/store) issue but an Angular one, as it seems to be related closely to the `async` pipes.

**Note**: I created a new Google API token for this Plunkr. So, when you finish testing with it, please tell me so I can disable / remove it.

*Longer version with details*

* Check in `src/app.ts` -> `ngOnInit()`: it sends an "action" to the store "on init" adding a "string" to "test", `test` in the store just adds whatever string it receives to an array.
* Check in `src/app.ts` -> `constructor()`: there's an observer for "test" values from the store.
* Check in `src/app.ts` -> in the template: There's a debug display of `test`, with an `async` pipe and a `json` pipe.
* On init, that `test` action and value shows up in the section with the `async` pipe correctly. So `async` pipes work well when the observers' values sent are triggered from normal functions.
* Check in `src/app.ts` -> `ngOnInit()`: it also triggers a `checkAuth()` from `gapiService`.
* Check in `src/gapi.service.ts` -> `checkAuth()`: that `checkAuth()` will check if it is already authorized. If it is authorized (after the first time you authorize it by clicking the button and reload the page) it will dispatch an action to `ngrx/store` stored as `authorized`. 
* Check in `src/app.ts` -> `constructor()`: there's an observer for "authorized" values from the store that just `console.log`s them.
* Check your console: there will be some `new ngrx/store.authorized value:` with the value.
* Check that the "authorized" section of the page with the `async` pipe didn't update.
* Check in `src/gapi.service.ts` -> `checkAuth()`: in the same callback that stores the `authorized` value in the `ngrx/store` is another value sent to the `ngrx/store` saved as `test`.
* Check in `src/app.ts` -> `constructor()`: there's an observer for `test` values from the store that just `console.log`s them too.
* Check your console: there will be some `new ngrx/store.test value:` with the value. So observers do work. Is just the `async` pipe that is not working as expected.
* In the page, in the "test" section, the array should show all the values sent to `ngrx/store` in `test`, but it only shows the one sent before from the `ngOnInit()`, not the ones from the Google API's callbacks.
* Check in `src/app.ts` -> the template: there is a `click` event handler for the `Test` button.
* Check in `src/app.ts` -> `test()` (the `click` handler): It just dispatches another `test` action to `ngrx/store`.
* As this action is not sent from a Google API callback, the `async` pipe gets the new value immediately, and it takes all the previous values too.
* Although the "Test" button only sends a new value to `test` in `ngrx/store`, the `async` pipe for `authorized` also updates its value and the page shows "true".

**What is the motivation / use case for changing the behavior?**

`async` pipes are supposed to subscribe to any observer and update their final value based on those observers, independent of where the update of those observers was triggered.

**Please tell us about your environment:**

OS: 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

Browser: Chrome 54.0.x (64 bit) and Firefox 50.1.0

IDE: Atom with `atom-typescript` and Visual Studio Code

`npm version`: 

```
{ 'gapi-test': '0.0.0',
  npm: '3.10.8',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '48',
  node: '6.9.1',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8' }
```

`angular-cli` version (but the Plunkr version doesn't use `angular-cli` and the issue still occurs):

```
angular-cli: 1.0.0-beta.25.5
node: 6.9.1
os: linux x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3
```

yarn version: `yarn version v0.17.8`

`@angular/core` (taken from `yarn.lock`): `"@angular/core@^2.3.1": version "2.4.3"`

* **Angular version:** 2.0.X

* **Browser:** [ Chrome XX | Firefox XX | Mobile Chrome XX ]

 
* **Language:** [ typescript@2.0.2 (in Plunkr) | typescript@~2.0.3 (yarn version "2.0.10") (in local angular-cli project ]

* **Node (for AoT issues):** `node --version` =   v6.9.1

**Comment by alexzuza** [comment]
Your callback is executed outside of angular zone. That's why your `dispatch` event has no effect for updating UI

**Comment by tiangolo** [comment]
Thanks for the quick response @alexzuza !

OK, I didn't know about the zone and how to use it...

I've seen in this issue comment https://github.com/angular/angular/issues/13363#issuecomment-266280268 and in [this blog post](https://medium.com/@MertzAlertz/what-the-hell-is-zone-js-and-why-is-it-in-my-angular-2-6ff28bcf943e#.w8cq41nqj) that they use `this.zone`.

But it seems like `Component` doesn't have a `.zone` property anymore (probably in previous versions).

Then I saw the [`NgZone` class](https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html) and it seemed that it is (or was?) used as an injectable in components and then used as `this._zone.run(() => { <the code that needs to be run outside the "zone" but still trigger UI updates> });`, as in this comment: https://github.com/angular/angular/issues/7873#issuecomment-209991709. But that `NgZone` class is marked as "experimental".

Then in other comments, as https://github.com/angular/angular/issues/7873#issuecomment-238897038 , I saw that they used the [ApplicationRef class](https://angular.io/docs/ts/latest/api/core/index/ApplicationRef-class.html), that is marked as "stable". They use it injecting it in the constructor of the `Component`, and then, in the "out of the zone" code they call the `ApplicationRef.tick()` method, and that triggers a refresh in the UI.

And that worked in my Plunkr.

So the important code ended up something like this, in a simplified form to show only the important parts (I add it here for future reference, maybe for others that end up reading this):

```TypeScript
// The service that called external "out of zone" code. I think it should work for Components or anything else too.

import { Injectable, ApplicationRef } from '@angular/core';

@Injectable()
export class MyService {
  
  constructor(
    private appRef: ApplicationRef
    ) {};

    
  methodUsingExternalLib() {
    //externalLib calls code that ends up out of the "zone" when calling the callback
    externalLib('someParam', (result) => {
        //this is the callback, for example, do whatever you need with the result
        console.log(result);
        //for example, if you had set-up ngrx/store, you could dispatch an action like:
        //this.store.dispatch({type: actions.AUTHORIZE});

        //and after all that, run the ApplicationRef.tick() method to trigger any needed changes in the UI:
        this.appRef.tick();
  }
}
```

I will now remove the API token. So the Plunkr code won't work normally (all the authorization process won't work). But I'll leave the Plunkr with the updated working code there, just for reference.

---

Now, I would like to ask if that is the correct "Angular way" of doing it and solving it.

If it is, I think there should be some documentation about it, I've seen several issues that now ended up being related to the same problem, but I didn't know how it worked, so I thought it was a "bug", and now I see that, in it's strange way, it was just a "support request" that shouldn't go here.

I think there should be, for example, a section in the [FAQ](https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html) with an entry like "Why does my Component UI is not updating?" and then explaining or referencing there documentation to the `Zone` entry in the glossary, for example. And referencing the `ApplicationRef`class.

Also, I think that the `ApplicationRef` class documentation should have an example on how to use it and how it would solve the problem with "out of zone" code. ...if it is the case that using that is the way to solve it.

If the maintainers are OK with something like that, I could create a PR with some additions like those to the documentation.

**Comment by robwormald** [comment]
In general, the simplest solution to this problem is to just use `gapi` w/ Promises, which are correctly integrated with Zones. Ad far as I'm aware, all the `gapi` APIs that are callback based also support Promises.

**Comment by tiangolo** [comment]
Oh, I see! You are right @robwormald.

The type declarations in npm `@types/gapi` are incomplete, they only declare the version with callbacks. 

And `angular-cli` complains and stops if I try to use the  version with `Promise`s. 

But after adding some quick type declarations to `typings.d.ts` modifying that declaration to "return Promises", it worked (without needing the `ApplicationRef.tick()`). :tada: 

---

As a side note, thanks for `ngrx/store` (and family)! They are just awesome. :tada: :cake: 

---

Now, about docs, do you think adding a PR with updates similar to those described above would be worthwhile?

I mean, for general use cases with Angular. ...my problem is solved now, but maybe others could benefit from finding these answers faster (and not polluting GitHub issues with this kind of "question", as I did).

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource the original issue was resolved

**Comment by tiangolo** [comment]
I haven't closed this issue waiting for you to tell me if it would be good to have a PR with changes to the docs specifying that behavior.

**Comment by DzmitryShylovich** [comment]
@tiangolo https://github.com/angular/angular.io docs repo

**Comment by DzmitryShylovich** [comment]
Prs are always welcomed

**Comment by pkozlowski-opensource** [comment]
YEh, doc issues / PRs should go to  https://github.com/angular/angular.io

**Comment by tiangolo** [comment]
Cool! Thanks.

**Comment by Bigless27** [comment]
I just dealt with an issue like this. Use a behavioral subject instead of just an observable for authorize. That way you'll be able to still use the values in your component even though the redux dispatch is happening before the aync pipe is listening to it.
