### ISSUE TITLE
ngOnChanges triggers so frequently

### ISSUE THREAD

**Issue by paramsingh88** [angular/angular#13959]
It's been observed that on hover of checkbox too, ngOnChanges get triggered twice. I'm trying to implement a multi-select-dropdown component in which I'm rendering `<md-checkbox>` inside `ngFor` loop. Even on using native `<input type="checkbox">` and `ChangeDetectionStrategy.OnPush` I can see the same behaviour. It's slowing down my UI a lot. 
I wanna know why at the first place ngOnChanges is being called on hover of a component at all even for simple primitive input controls without css?

<img width="755" alt="screen shot 2017-01-16 at 10 36 48 pm" src="https://cloud.githubusercontent.com/assets/19772006/22018985/758eeee8-dcd7-11e6-918b-4e0e65dd34a8.png">

**Comment by DzmitryShylovich** [comment]
ngOnChanges is called on every change detection cycle. It's by design

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by chrisjmccrum** [comment]
@paramsingh88 did you ever figure this out? I'm experiencing the same behavior
