### ISSUE TITLE
[Bug] UI event not updating if called in between Async/Await calls

### ISSUE THREAD

**Issue by luchillo17** [angular/angular#13953]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

**Current behavior**
I'm calling a subject, which is called in between 2 async calls, in the component that subscribed to it, the subscription indeed changes the variable, however the NgClass expression that uses it doesn't update.

**Expected behavior**
I expect the NgClass to add the class based on the value of the variable being changed from the async function.

**Minimal reproduction of the problem with instructions**
I want to make a plunkr but i need target ES6 for such thing (in order to use Async/Await feature).

**Please tell us about your environment:**
MAC OS Sierra, Node 

* **Angular version:** 2.0.0-RC.4 (locked with my current Ionic version).

* **Browser:** all.
 
* **Language:** [TypeScript 2.1.4 | ES6/7]

* **Node (for AoT issues):** `node --version` = 6.9.2

* **Aditional Info:**
Here's how i'm using the function, The `PrinterService`'s `connect` function should trigger the UI change, but it doesn't, my theory is either the async/await feature is halting all js context execution, or that change is somewhat running outside of zone.js context due to the `async` keyword in the function declaration:
```ts
    async printDocument() { // <- Possible reason for error, the 'async' keyword?
      ...
      let printerDevice: string = await this.conf.showRadioButtons({
        title: `Seleccione dispositivo usb`,
        inputs: [
          // { name: 'dataTable', label: 'dataTable', type: 'text', placeholder: '13' },
          ...map(devices, (device) => ({ label: device, value: device, type: 'radio' }))
        ]
      });

      if (!printerDevice) {
        throw new ReferenceError('undefined device');
      }

      this.conf.showProgress(); // <- Line that tries to update the UI

      await this.printerService.connect(printerDevice);
      ...
```

**Comment by Luchillo** [comment]
I've been trying to replicate in [plunkr](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview), but haven't been able, maybe it's my Angular version, or my `tsconfig.json` settings?

Accordingly with [this](https://github.com/angular/angular/issues/7381) issue with similar context, it might as well be my function running outside the zone, however theirs were an error with babel, which i'm not using.

Or maybe it's because of Webpack?

**Comment by Luchillo** [comment]
Found a hack for it, in my code i put the `this.conf.showProgress()` function to return a `Promise` that resolves after 200ms and in code i prefix it with `async`, my theory is that the next function takes long to do, and that `await` does halt UI execution (correct me if i'm wrong, maybe it works like those hacky sleep functions people does, that rely on a for loop and constantly comparing current time/date with offset one).

New `showProgress` function:
```ts
  showProgress(args?: Args) {
    args = args || {};
    this.busyCtrl.next(true);

    // Here the hack
    return new Promise((resolve, reject) => {
      setTimeout(() => resolve(true), 250);
    });
  }
```

New `async printDocument` function:
```ts
    async printDocument() { // <- Possible reason for error, the 'async' keyword?
      ...

      if (!printerDevice) {
        throw new ReferenceError('undefined device');
      }

      await this.conf.showProgress(); // <- New line with the hack

      await this.printerService.connect(printerDevice);
      ...
```

Still this is a hack, i would like to know why, as well as a better how, any suggestions?

**Comment by TheGuardianWolf** [comment]
I seem to have hit a similar issue with Q promises, my ngIf component loading no longer triggers instantly. Example:
```
promise.done(() => { 
    this.router.navigate(['/path']);
}, (err) => {
    throw err;
});
```

If I move it outside the promise, it begins to work properly again. I'll see if I can code up a quick example for debugging.

**Comment by Luchillo** [comment]
I actually think i know how it goes for my issue, my theory is that `async/await` halt's the js process, so the fix i ended up doing is using my hack explained before but putting the interval to 0 ms, thus putting the other task in the end of the js engine callback loop, thus giving the animation the power to finish before the `async/await` process continues.

I would like someone to tell me i'm right/wrong and if there's a better way to handle this.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource sounds like zone.js issue and not directly related to angular

**Comment by Luchillo** [comment]
@DzmitryShylovich Really? i tough it was something to do with the way the `async/await` statement worked, or how it was being transpiled down to ES5.

**Comment by DzmitryShylovich** [comment]
@luchillo17 is this still valid with the latest zone.js and angular 4?

**Comment by luchillo17** [comment]
@DzmitryShylovich Sorry about that, i cannot test it, that was inside an Ionic 2 app, and i haven't been able to update since Ionic 2 beta.11 (bosses delaying the update because it just kind of works right now, so they boss me around other projects).

I guess for the time being i'll close the issue.
