### ISSUE TITLE
<form> together with *ngFor and [(ngModel)] does not behave correctly

### ISSUE THREAD

**Issue by OlliL** [angular/angular#13955]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
An array with data is looped through in the template and each element is shown. If the looping HTML-element is not surrounded by a form-tag, everything is fine. If it is surrounded by a form-tag the loop behaves correctly and for each element in the array an element in HTML is rendered. however, the ngModel which is used to show each array elements content always shows in all elements the data of the last array element.

**Expected behavior**
surrounding a loop with `form` or not should not make any difference.

**Minimal reproduction of the problem with instructions**
Minimal demo can be seen here - just check it out, npm install + ng serve:
https://github.com/OlliL/observableTwoWayBinding

**What is the motivation / use case for changing the behavior?**
I want to use  form validation so I started surrounding my input forms with a <form> tag and the story began....

**Please tell us about your environment:**
Windows 7, IntelliJ, local development only so far

* **Angular version:** 2.3.1 + 2.4.3

* **Browser:** 
Firefox 50
Chrome 55.0
 
* **Language:** 

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> the ngModel which is used to show each array elements content always shows in all elements the data of the last array element.

because all elements have the same `name` (and `id` which is not a valid html)

**Comment by OlliL** [comment]
OK... I see - then sorry for the  noise :(

**Comment by davidudofa** [comment]
I added this to my input element and it worked 

`[ngModelOptions]="{standalone: true}"`

**Comment by bcd6** [comment]
Facing the same issue!!!@davidudofa Thanks for your solution.
But this option seems let the  "the ngModel will not register itself with its parent form".
So all the validation disappeared on this input.

**Comment by HoudhaifaHamza** [comment]
and make the formControlNamein small case => formcontrolName   if we use ngModel inside ngFor inside a Form
