### ISSUE TITLE
 Could not resolve "D:/" from "D:/".

### ISSUE THREAD

**Issue by hendrawidjaja** [angular/angular#13964]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

A fresh install Angular project using angular-cli (ng new)

**Expected behavior**

Watch doesn't work. Ng serve displayed    Could not resolve "D:/" from "D:/".

**Minimal reproduction of the problem with instructions**

New installation

**What is the motivation / use case for changing the behavior?**

Hot reload doesn't work. Please see attached image
![browser-ss](https://cloud.githubusercontent.com/assets/2580855/22028648/30fbc6b0-dcd8-11e6-83cb-603c83b124bd.PNG)
![ps-ss](https://cloud.githubusercontent.com/assets/2580855/22028649/30fd719a-dcd8-11e6-8037-0ba9fd554756.PNG)

**Please tell us about your environment:**

* **Angular version:** 2.4.3

* angular-cli: 1.0.0-beta.25.5
* angular-core: 2.4.3
* Windows 10 Pro @i7-6700, 16GB RAM
* PowerShell with full admin

* **Browser:** [Chrome 55]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   7.2.0

**Comment by DzmitryShylovich** [comment]
Pls report cli issues on https://github.com/angular/angular-cli/issues
