### ISSUE TITLE
Load scripts in Angular 2

### ISSUE THREAD

**Issue by NightWnvol** [angular/angular#13965]
I am building an Angular2 WebApp using an external HTML template for my components. The template needs to run some scripts to load correctly the page but script tags like this `<script src="myScript.js"></script>` are not allowed in Angular 2 components.
If I include script tags in my `index.html` the page loads fine the first time but when I route to another page scripts are not reloaded for the component template and the page remains blank.
Is there another way to load scripts and solve this issue?
index.html

```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Angular2App</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">

  <!-- Facebook and Twitter integration -->
  <meta property="og:title" content="" />
  <meta property="og:image" content="" />
  <meta property="og:url" content="" />
  <meta property="og:site_name" content="" />
  <meta property="og:description" content="" />
  <meta name="twitter:title" content="" />
  <meta name="twitter:image" content="" />
  <meta name="twitter:url" content="" />
  <meta name="twitter:card" content="" />

  <!--<link href="build/main.css" rel="stylesheet">-->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">

  <!-- Animate.css -->
  <link rel="stylesheet" href="assets/css/animate.css">
  <!-- Icomoon Icon Fonts-->
  <link rel="stylesheet" href="assets/css/icomoon.css">
  <!-- Themify Icons-->
  <link rel="stylesheet" href="assets/css/themify-icons.css">
  <!-- Bootstrap  -->
  <link rel="stylesheet" href="assets/css/bootstrap.css">

  <!-- Magnific Popup -->
  <link rel="stylesheet" href="assets/css/magnific-popup.css">

  <!-- Owl Carousel  -->
  <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
  <link rel="stylesheet" href="assets/css/owl.theme.default.min.css">

  <!-- Theme style  -->
  <link rel="stylesheet" href="assets/css/style.css">

  <!-- Modernizr JS -->
  <script src="js/modernizr-2.6.2.min.js"></script>
</head>

<body>
  <app-root></app-root>

                    <!-- SCRIPTS THAT I NEED TO LOAD -->
  <!-- jQuery -->
  <script id="jquery.min" src="assets/js/jquery.min.js"></script>
  <!-- jQuery Easing -->
  <script id="jquery.easing.1.3" src="assets/js/jquery.easing.1.3.js"></script>
  <!-- Bootstrap -->
  <script id="bootstrap.min" src="assets/js/bootstrap.min.js"></script>
  <!-- Waypoints -->
  <script id="jquery.waypoints.min" src="assets/js/jquery.waypoints.min.js"></script>
  <!-- Carousel -->
  <script id="owl.carousel.min" src="assets/js/owl.carousel.min.js"></script>
  <!-- countTo -->
  <script id="jquery.countTo" src="assets/js/jquery.countTo.js"></script>
  <!-- Magnific Popup -->
  <script id="jquery.magnific-popup.min" src="assets/js/jquery.magnific-popup.min.js"></script>
  <script id="magnific-popup-options" src="assets/js/magnific-popup-options.js"></script>
  <!-- Main -->
  <script id="main" src="assets/js/main.js"></script>
                    <!-- SCRIPTS THAT I NEED TO LOAD -->

</body>
</html>
```

app.module.ts

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { routing } from './app.routing.module';

import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
import { LoginComponent } from './login/login.component';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    LoginComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    routing
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

app.routing.module.ts

```
import { Routes, RouterModule } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { LoginComponent } from './login/login.component';

const routes: Routes = [
    {
        path: 'login',
        component: LoginComponent
    },
    {
        path: 'home',
        component: HomeComponent
    },
    {
        path: '',
        component: LoginComponent
    },
    {
        path: '**',
        component: LoginComponent
    }
];

export const routing = RouterModule.forRoot(routes);
```

app.component.ts

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
}
```

app.component.html

```
<router-outlet></router-outlet>
```

**Comment by DzmitryShylovich** [comment]
Pls add a small repro on Plunkr

**Comment by NightWnvol** [comment]
Here's a simple example. I don't understand why here it works fine... I have included the script in my `index.html` as i did in my project.
https://plnkr.co/edit/tlC9GNDLwTcNgReSWCh9?p=preview
Any ideas???

**Comment by DzmitryShylovich** [comment]
Probably something wrong with local config. Maybe 3rd party lib...
Anyway we can't do anything on angular side without a reproduction.

**Comment by NightWnvol** [comment]
I think there's a problem with reload sripts in each component templates...
Anyway, here's my complete project - https://github.com/NightWnvol/angular2App
The issue occurs when I route from login-page to home-page (and vice versa), but if I refresh the page it works fine again.

**Comment by NightWnvol** [comment]
UPDATE: I noticed that if I enable the Toggle Device Toolbar (in Chrome DevTools view) the issue disappears. I am really confused... @DzmitryShylovich

**Comment by tytskyi** [comment]
@NightWnvol you probably have the `Disable cache (while DevTools is open)` tuned on.

**Comment by NightWnvol** [comment]
@tytskyi No I have the `Disable cache` already turned off.

**Comment by anabulsi** [comment]
I'm not sure I fully understand your problem, but here what I believe is happening:
1) All your scripts are loaded on first visit
2) You start navigating through your Angular app, Angular will add/remove DOM elements dynamically without a full page refresh
3) Your scripts are not notified of this change, therefore they will not do all the DOM manipulation they are supposed to do

What you need to do is to reinitialize them inside ngAfterViewInit event. Hope this will help

On a side note: I once tried to Angularize a jQuery website while maintaining all the jQuery scripts and libraries, it did work and but the code was really maintainable.  Angular and jQuery follow different philosophies, try not to mix them as much as you can. I'm sure you will find Angular version of most jQuery libraries. PrimeNG is a good place to start

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by faridjafri** [comment]
If there is a link for solution to this issue, please share it! Thanks

**Comment by AleB93** [comment]
I have the same problem with 3rd part scripts (with jquery) and the routes in angular 2.
The scripts load only the first time but changing route, and return on this route, the exsternal scripts don't work!

**Comment by cristiancamiloperezlopez** [comment]
Any update ?
Thanks

**Comment by AleB93** [comment]
@cristiancamiloperezlopez  In the component in which the 3rd part scripts are required, i have used the ngOnInit method, to 'write' the html file with the classic <script src="ecc ecc"></script>.
My code: `export class DevicesComponent {
  constructor(private elementRef:ElementRef) {

  };

  ngOnInit() {
    var s = document.createElement("script");
    s.type = "text/javascript";
    s.src = "../assets/global/scripts/datatable.js";
    this.elementRef.nativeElement.appendChild(s);
    var s1 = document.createElement("script");
    s1.type = "text/javascript";
    s1.src = "../assets/pages/scripts/table-datatables-responsive.min.js";
    this.elementRef.nativeElement.appendChild(s1);
    var s2 = document.createElement("script");
    s2.type = "text/javascript";
    s2.src = "../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js";
    this.elementRef.nativeElement.appendChild(s2);
    var s3 = document.createElement("script");
    s3.type = "text/javascript";
    s.src = "../assets/global/plugins/datatables/datatables.min.js";
    this.elementRef.nativeElement.appendChild(s3);

  }`
It doesnt work properly (switching routes, you have to wait some ms, and you see the html changing), but it is a solution.
Sorry for my bad enlgish.

**Comment by NightWnvol** [comment]
Hello, the only way I have to reload scripts is to remove and recreate the element in DOM every time like this:
```
export class AppComponent {

  constructor() {
    document.getElementById("testScript").remove();
    var testScript = document.createElement("script");
    testScript.setAttribute("id", "testScript");
    testScript.setAttribute("src", "assets/js/test.js");
    document.body.appendChild(testScript);
  }
}
```

**Comment by ajsnyde** [comment]
@NightWnvol It sucks that this is the solution - I would think that it would be easier to reload script.

**Comment by NightWnvol** [comment]
@ajsnyde You're right, it's a bad solution but I have not found any other way to reload a script already inserted in the HTML.

**Comment by rogensky** [comment]
This is happening to me to. 

I am using Visual Studio 2017 and I have tried several different Admin templates now. I have been trying to have a main "router-outlet" where I load my Login component or the a "Main" component where every other component will be loaded into.

I add a second "router-outlet" onto the "Main" component, and every time I navigate to the children of this component the custom JavaScript files just don't get loaded, although I can see them if "Inspect" the page.

The funny thing is that If I refresh/reload the page the scripts actually work, but not when I navigate to components.

I have tried this in 2 different projects, but I will probably give up on Angular 2 for ASPCore and just go back to use only MVC. 

It's a shame that this does not work as I used AngularJS on an MVC project before and I really liked it. I was hopping Angular 2 would make things easier, but apparently it does not.

Please let me know if you guys have a proper solution for this issue.

Many thanks

**Comment by NightWnvol** [comment]
@rogensky Hi, the only way I found for now it is as I wrote in the comment above. In your case you can cancel and recreate the script every time that you navigate to the children of your main component.

_Sent from my OnePlus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ajsnyde** [comment]
Yep, using it now on what will-be production code :(

**Comment by mmeendez8** [comment]
That's a good trick @NightWnvol, I did not even find something that could work! Anyway ,I had opened a new question in [StackOverflow](https://stackoverflow.com/questions/46447754/load-scripts-through-all-components-in-angular-2) before seeing your "patch", you are welcome to add your solution, I will up vote it!

**Comment by sunnyg1210** [comment]
A simple solution I found was just to add a `window.location.href = '...'` to whatever link you are opening after login. Heres my function for the when the login button is clicked (you can see the commented out line where i used the router.navigate originially)

`

this.authService.authenticateMember(member).subscribe(data => {

      if (data.success) {
              .....
              window.location.href = '/
              ......
      } else {
              .......
      }
}

`

So if you are using authentication then you can put that above code at the end of your login success response and it will refresh the page aswell as take the user to the login section.

This is not the best solution but it is the simplest one i can think of that dosent require too many changes. Hope it helps :)

**Comment by likeamugger** [comment]
Hi, thank you for providing your workaround.  @NightWnvol 
However when I use it in my AppComponent, I get the ajax icon loading on the main page. I believe it has some issue with XHR. Did you encounter the issue before? Thank you!

**Comment by NightWnvol** [comment]
@likeamugger Hi, I am sorry I can't help you. Can you post an example code?

**Comment by likeamugger** [comment]
@NightWnvol Hi, it's alright I can't replicate the error. I did the following but it does not work for me. Do you mind pointing out where I have done wrong? Thank you!

index.html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href="favicon.ico">
  <title>Angular App</title>
  <base href="/">
<app-root></app-root>
</head>

<link rel="stylesheet" href="assets/css/jquery.mobile-1.4.5.min.css"/>
<link rel="stylesheet" href="assets/css/themes/theme1.min.css" />
<link rel="stylesheet" href="assets/css/themes/jquery.mobile.icons.min.css" />

<script id="script1" src="./assets/js/jquery.min.js"></script>
<script id="script2" src="./assets/js/jquery.mobile-1.4.5.min.js"></script>


app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']

})
export class AppComponent {
  title = 'Angular App';
  
    constructor() {
        document.getElementById("script1").remove();
    var script1 = document.createElement("script");
    script1.setAttribute("id", "script1");
    script1.setAttribute("src", "./assets/js/jquery.min.js");
    document.body.appendChild(script1);

    document.getElementById("script2").remove();
    var script2 = document.createElement("script");
    script2.setAttribute("id", "script2");
    script2.setAttribute("src", "./assets/js/jquery.mobile-1.4.5.min.js");
    document.body.appendChild(script2);
  }
}

**Comment by likeamugger** [comment]
@NightWnvol Hi, it's alright I can't replicate the error. I did the following but it does not work for me. Do you mind pointing out where I have done wrong? Thank you!

index.html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href="favicon.ico">

  <title>Angular App</title>
  <base href="/">
<app-root></app-root>
</head>

<link rel="stylesheet" href="assets/css/jquery.mobile-1.4.5.min.css"/>
<link rel="stylesheet" href="assets/css/themes/theme1.min.css" />
<link rel="stylesheet" href="assets/css/themes/jquery.mobile.icons.min.css" />


<script id="script1" src="./assets/js/jquery.min.js"></script>
<script id="script2" src="./assets/js/jquery.mobile-1.4.5.min.js"></script>





app.component.ts
import { Component } from '@angular/core';

@component({
selector: 'app-root',
templateUrl: './app.component.html',
styleUrls: ['./app.component.css']

})
export class AppComponent {
title = 'Angular App';

constructor() {
document.getElementById("script1").remove();
var script1 = document.createElement("script");
script1.setAttribute("id", "script1");
script1.setAttribute("src", "./assets/js/jquery.min.js");
document.body.appendChild(script1);

document.getElementById("script2").remove();
var script2 = document.createElement("script");
script2.setAttribute("id", "script2");
script2.setAttribute("src", "./assets/js/jquery.mobile-1.4.5.min.js");
document.body.appendChild(script2);
    }
}

**Comment by likeamugger** [comment]
@NightWnvol Hi, I could not replicate the same error as previously, but it is still not working as desired. I have attached the codes. Thank you so much!

index.html
```
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href="favicon.ico">

<title>Angular App</title>
<base href="/">
<app-root></app-root>
</head>

<link rel="stylesheet" href="assets/css/jquery.mobile-1.4.5.min.css"/>
<link rel="stylesheet" href="assets/css/themes/theme1.min.css" />
<link rel="stylesheet" href="assets/css/themes/jquery.mobile.icons.min.css" />

<script id="script1" src="./assets/js/jquery.min.js"></script>
<script id="script2" src="./assets/js/jquery.mobile-1.4.5.min.js"></script>
```

app.component.ts
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Angular App';
  
    constructor() {
    document.getElementById("script1").remove();
    var script1 = document.createElement("script");
    script1.setAttribute("id", "script1");
    script1.setAttribute("src", "./assets/js/jquery.min.js");
    document.body.appendChild(script1);

    document.getElementById("script2").remove();
    var script2 = document.createElement("script");
    script2.setAttribute("id", "script2");
    script2.setAttribute("src", "./assets/js/jquery.mobile-1.4.5.min.js");
    document.body.appendChild(script2);
  }
}
```

**Comment by cauehqueiroz** [comment]
@likeamugger you should check if the element exists before removing it:
```
if(document.getElementById("script1")) 
    document.getElementById("script1").remove();
```

**Comment by NightWnvol** [comment]
@likeamugger Have you checked if 
```
./assets/js/...
```
 is the correct path of your scripts?

**Comment by likeamugger** [comment]
@cauehqueiroz I added the if statement but it still does not work.
@NightWnvol I changed it to `/assets/... `and I am certain that it is correct.

After editing based on the comments, my scripts still does not load without a refresh. This is how it looks like currently:

Navigate to a different component:
![before](https://user-images.githubusercontent.com/14154667/35307969-4f0cf126-009d-11e8-9d0a-b36e2c19eea5.PNG)

After refreshing the component page:
![after](https://user-images.githubusercontent.com/14154667/35307971-54339eac-009d-11e8-9c02-53e5bb7bf556.PNG)

Thanks for getting back to me! Appreciated your help.

**Comment by NightWnvol** [comment]
@likeamugger Have you any errors in your console when you route to a different component?

**Comment by likeamugger** [comment]
@NightWnvol With the old code I have, no errors at all during routing or no matter how much I refresh. Just that the scripts does not work.

For your workaround that I have added in, I do not have errors when navigating to any components. No issues with refresh as well. However, when I attempt to refresh for a component that requires id (eg. `localhost:4200/component/1`) , there are errors: 
![capture](https://user-images.githubusercontent.com/14154667/35364493-5b8cc91a-0167-11e8-8cba-7c0e4154844a.PNG)

**Comment by NightWnvol** [comment]
@likeamugger Have you tried to move the code that reload your scripts in `ngAfterViewInit()` instead of `constructor()`?

**Comment by NightWnvol** [comment]
@likeamugger I think the problem is that your scripts are loaded twice(in `index.html` and in `app.component.ts constructor()`).
Try to load your scripts with a `loadScripts()` function and add it to a `click` event to your `<a>` tag.

e.g.
app.component.ts
```
export class AppComponent {
constructor() { }

loadScripts() {
      document.getElementById("script1").remove();
      var script1 = document.createElement("script");
      script1.setAttribute("id", "script1");
      script1.setAttribute("src", "assets/js/jquery.min.js");
      document.head.appendChild(script1);

      document.getElementById("script2").remove();
      var script2 = document.createElement("script");
      script2.setAttribute("id", "script2");
      script2.setAttribute("src", "assets/js/jquery.mobile-1.4.5.min.js");
      document.head.appendChild(script2);
}
}
```
app.component.html
```
<html>
     . . . . . . . . . .

     <a routerLink="/route1" (click)="loadScripts()">Route1</a>
     <a routerLink="/route2" (click)="loadScripts()">Route2</a>
     <a routerLink="/route3" (click)="loadScripts()">Route3</a>

     . . . . . . . . . .
</html>
```

**Comment by likeamugger** [comment]
@NightWnvol This works for me! May not be the best solution but at least I could see the pages refreshing on their own. Thank you so much for your help!

**Comment by delsumit** [comment]
Do i need to always include the script in constructor when ever using external CSS and JS as it only works when using like  this

**Comment by yuviprathap** [comment]
Hi all,
I have a same problem pls anyone help me

**Comment by THEKINGIII** [comment]
So far I faced the same issue. All that happened because the browser tries to load the scripts using a relative path. In my case it was http://localhost:3000/about/5, when you hit refresh it will try to load script files using this path http://localhost:3000/about/5/system.config.js.
So, its an issue inside the base href. I fixed that by setting `<base href="/">` in the head tag of **index.html**.
@likeamugger

**Comment by Heryboy** [comment]
Hello all
I have to use your sample code above but still not work for anyone please help me now.

**Comment by anshul0430** [comment]
> testSc



> document.getElementById("testScript").remove();

RROR TypeError: Cannot read property 'remove' of null

**Comment by Rahul038** [comment]
> @likeamugger I think the problem is that your scripts are loaded twice(in `index.html` and in `app.component.ts constructor()`).
> Try to load your scripts with a `loadScripts()` function and add it to a `click` event to your `<a>` tag.
> 
> e.g.
> app.component.ts
> 
> ```
> export class AppComponent {
> constructor() { }
> 
> loadScripts() {
>       document.getElementById("script1").remove();
>       var script1 = document.createElement("script");
>       script1.setAttribute("id", "script1");
>       script1.setAttribute("src", "assets/js/jquery.min.js");
>       document.head.appendChild(script1);
> 
>       document.getElementById("script2").remove();
>       var script2 = document.createElement("script");
>       script2.setAttribute("id", "script2");
>       script2.setAttribute("src", "assets/js/jquery.mobile-1.4.5.min.js");
>       document.head.appendChild(script2);
> }
> }
> ```
> 
> app.component.html
> 
> ```
> <html>
>      . . . . . . . . . .
> 
>      <a routerLink="/route1" (click)="loadScripts()">Route1</a>
>      <a routerLink="/route2" (click)="loadScripts()">Route2</a>
>      <a routerLink="/route3" (click)="loadScripts()">Route3</a>
> 
>      . . . . . . . . . .
> </html>
> ```

This also works for me but is there any other solutiion because it refreshes the whole page while the purpose of routing is different. Can it be solved with out refreshing.
