### ISSUE TITLE
bug in ngFor with dynamic image src

### ISSUE THREAD

**Issue by praveens96** [angular/angular#13962]
**I'm submitting a ...**
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using <img/> tag with dynamic image source inside a ngFor loop there is a problem it seems. description is as follows:
<ion-row *ngFor="let onevar of vars; let i=index;let e=even">
  <ng-container *ngIf="e">
     <img [src]="testing(i)" class="tileCardImg"/>
</ng-container>
</ion-row>
to get my image source i am calling a method, testing which returns my img source.
the testing method is as follows:
in ionViewDidLoad(){
  this.vars = ["1","2"];
}
testing(i){
  console.log("index:"+i);
  return i+".jpg";
}
lets say i am returning same index with jpg extension. if i see my console, i am finding it as follows:
<img width="590" alt="screen shot 2017-01-17 at 8 03 58 pm" src="https://cloud.githubusercontent.com/assets/8864727/22024532/4772fe82-dcf0-11e6-9427-86082cd75869.png">

if you can observe the output, my testing functions is being called twice though it shows two images on my page. so printing each index twice. 

**Expected behavior**
it should call my testing once and it should print each index once.

**Minimal reproduction of the problem with instructions**
you can use the code given above and check console to reproduce it.

**What is the motivation / use case for changing the behavior?**
i have encountered it when using a rand function to generate a random number and trying to get one random image from my set of images. Its throwing an error saying: expression has changed after it was checked.

when i see why its being called, the reason is that looping twice over my ngFor and consequently my [src] function is called twice for each. since there is rand funciton, its giving a different value and it created the issue.

**Please tell us about your environment:**
I was using ionic 2. here is the env info:
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.2.1 Build version 8C1002

* **Browser:**
I tried only in Chrome.
 
* **Language:** please refer above ionic info

**Comment by DzmitryShylovich** [comment]
Pls add a small repro on plunkr

**Comment by praveens96** [comment]
https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview
check console and output in parallel.
<img width="623" alt="screen shot 2017-01-17 at 10 06 24 pm" src="https://cloud.githubusercontent.com/assets/8864727/22029668/3cd767fe-dd01-11e6-9d14-804b187f78f7.png">

**Comment by pkozlowski-opensource** [comment]
@praveens96 did you forget to save your plunker?

**Comment by praveens96** [comment]
sorry, please find it here: https://plnkr.co/edit/Mwo6NYDXw4V3icIG902x

**Comment by DzmitryShylovich** [comment]
@praveens96 you should avoid using function in bindings. Your function will be called on every change detection cycle. So it's by design

**Comment by vicb** [comment]
In dev mode, we run the CD twice which explains why the functions are called twice - switching to prod mode should "solve" this.

**Comment by praveens96** [comment]
thanks for your responses. enableProdMode() tried keeping in app.components.ts. didnt worked. so, added key to array instead of calling a function as @DzmitryShylovich suggested.
