### ISSUE TITLE
[4.x] Add @Injectable.lazy option

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#13960]
Currently we can eager initialize a service by adding `ngOnDestroy` hook, but:
1. Very few people know that services can have `ngOnDestroy` (afaik it's still not documented on angular.io).
2. Even less know that if `ngOnDestroy` is present, service will be initialized eagerly.
3. We don't always have a disposal logic, so we are forced to add an empty `ngOnDestroy` method with a comment so it won't be remove by accident.

According to https://github.com/angular/angular/issues/13820 in 4.x `@Injectable` will be mandatory, so I think it will be more intuitive to control instantiation via annotation `@Injectable({lazy: false})`

**Comment by kemsky** [comment]
Actually, i was thinking about forcing eager initialization for services without useless injection to root component. May it is better to extend `{provide: ..}` signature with eager option?

**Comment by DzmitryShylovich** [comment]
@kemsky 
> May it is better to extend {provide: ..} signature with eager option?

Don't think it's a good idea. `ngOnDestory` is not called on services provided via `useFactory/useValue`, only on services provided via `useClass` (or shorthand). And services provided via `useClass` must be annotated wit `@Injectable`. So, to me, it makes much more sense to use annotation.

**Comment by kemsky** [comment]
From design point of view it is responsibility of DI configuration to decide whether service is singleton or not, is it lazy or eager, in general you should not change your service class implementation if you want to make it eager or lazy. Also, application will be broken when you try to replace eager service with another lazy implementation and there is no way to detect it.

`ngOnDestory` should have consistent behavior across all cases because it is lifecycle callback.

Requirements for `@Injectable` have poor documentation:

> Injector will throw NoAnnotationError when trying to instantiate a class that does not have @Injectable marker, as shown in the example below.

Originally we were told that ` @Injectable` was required for services that require injection of other services.

**Comment by kemsky** [comment]
Furthermore, `ngOnDestroy` does not work for services provided via component's `providers`, quite disappointing, because it would much more usefull.

**Comment by DzmitryShylovich** [comment]
it does

**Comment by kemsky** [comment]
Looks like it does not work with dynamically created components.

**Comment by DzmitryShylovich** [comment]
@kemsky it does https://plnkr.co/edit/JwDvrdiyr62tL8DO2XQL?p=preview

**Comment by kemsky** [comment]
In fact I'm observing this behavior right now in my application, so I'm pretty sure it does not work in all cases, however it is difficult to extract relevant part, it is somehow related to dynamic component creation.

**Comment by DzmitryShylovich** [comment]
@kemsky how do you provide your service? maybe https://github.com/angular/angular/issues/14821 ?

**Comment by djejaquino** [comment]
Will this happen?

**Comment by JoostK** [comment]
Since #15070 injectables are now lazy regardless of having `ngOnDestroy` (I never knew this, that was weird behavior!) and the common pattern to make them eager is to inject them into an NgModule constructor, so this does not warrant additional functionality from the framework.
