### ISSUE TITLE
W3c Validation issue with all attributes starting with ng-reflect-

### ISSUE THREAD

**Issue by kalyan1102** [angular/angular#13969]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by kalyan1102** [comment]
Example Attribute ng-reflect-form not allowed on element form at this point.

**Comment by DzmitryShylovich** [comment]
did you enable prod mode?

**Comment by kalyan1102** [comment]
Hi,

I am sorry I am closing this issue as I found out after enabling the prod mode resolves the issue. Thanks a lot

**Comment by ericmartinezr** [comment]
You could also look at this answer http://stackoverflow.com/a/29023301/4933038, it's not that old and it's for angularjs, but it may be useful.

**Comment by kalyan1102** [comment]
I am able to resolve all the issues except one. I have tried to get help from StackOverflow as well but luck as well hence reopening the issue.  

Inside formgroup for I have used formControlName for form elements. 

Example :
input formControlName="Searchbycombo"
class="customcombocontrol" type="text" name="Searchbycombo" id="ctry"

When I am enabling prod mode still it's rendered as formcontrolname ="something" for which w3c giving errors 

> "Attribute formcontrolname not allowed on element input at this point."

Please help!

**Comment by dejour** [comment]
can you provide a plunkr?

**Comment by DzmitryShylovich** [comment]
`[formControlName]="'Searchbycombo'"`

**Comment by kalyan1102** [comment]
It worked. Thanks a ton
