### ISSUE TITLE
[4.x] Remove unused first argument from IterableDifferFactory.create method

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#13961]
```
export class DefaultIterableDifferFactory implements IterableDifferFactory {
  supports(obj: Object): boolean { return isListLikeIterable(obj); }
  create<V>(cdRef: ChangeDetectorRef, trackByFn?: TrackByFn): DefaultIterableDiffer<V> {
    return new DefaultIterableDiffer<V>(trackByFn);
  }
}
```
Currently we are forced to pass somwthing as the first argument
```
this._iterableDiffers.find({}).create(null);
```
 but it's not even used by angular so I think it should be removed.

For 2.4.x we can probably make it optional.

**Comment by FrozenPandaz** [comment]
It seems like ngFor is using it

https://github.com/angular/angular/blob/master/modules/@angular/common/src/directives/ng_for_of.ts#L133

Maybe it should be optional though?

```
  create<V>(cdRef?: ChangeDetectorRef, trackByFn?: TrackByFn): DefaultIterableDiffer<V> {
    return new DefaultIterableDiffer<V>(trackByFn);
  }
```

**Comment by FrozenPandaz** [comment]
EDIT: Dug Further.. @DzmitryShylovich is right, it's not being used even though it is being passed in.

Updated Git Diff: https://github.com/angular/angular/compare/master...FrozenPandaz:optional-cdref

**Comment by DzmitryShylovich** [comment]
Fixed https://github.com/angular/angular/pull/14311
