### ISSUE TITLE
*.ngfactory files replaced by *.ngsummary.json files when running nbc

### ISSUE THREAD

**Issue by ltenny** [angular/angular#13968]
I'm submitting a bug report
This might be related to issue #[13632](https://github.com/angular/angular/issues/13632)

Current behavior
Upgraded to @angular/* 2.4.3 now the *.ngfactory.ts files are no longer created, I get *.ngsummary.json files. However I'm still using typescript 2.0.10, AoT, and rollup.  Only change (famous last words) was to update to @angular/* 2.4.3 

Expected behavior
Should still generate *.ngfactory.ts files.

Minimal reproduction of the problem with instructions
Unfortunately, can't share the repository. Upgrade to @angular/* 2.4.3 from 2.2.0

Please tell us about your environment:
Windows 10/Visual Studio 2015

Angular version: 2.4.3

Browser: all

Language: TypeScript 2.0.10

node -v
v5.4.1

npm -v
3.3.4

What conditions cause the *.ngsummary.json files to be generated in place of the *.ngfactory.ts files? No errors except for '...cannot find module ./app/app.module.ngfactory'  which is a byproduct of not actually generating the *.ngfactory.ts files.

**Comment by DzmitryShylovich** [comment]
Pls provide a github repo with reproduction

**Comment by thelgevold** [comment]
I would double check to make sure that your tsconfig.json settings are picking up an ngModule file that can be used to generate a corresponding ngfactory.

I generally add the following `files` section in tsconfig.json

```
"files": [
    "app.module.ts",
    "main.ts"
  ]
```

Here main.ts in the entry point into the app and app.module is the ngmodule used to generate the ngfactory referenced from main.ts.

**Comment by ltenny** [comment]
At the moment the code can't be shared. I'll try to reproduce in a smaller, open repo.

I added:

"files": [
    "app.module.ts",
    "main.ts"
  ]

to tsconfig.json  it didn't change anything.  I get no .ngfactory files created at all after the upgrade.  I get all of the .ngsummary.json files none of which I'd ever seen before.  What role do the .ngsummary.json play?  Some sort of intermediate file I assume.  ngc is usually pretty good about errors, but this just quietly creates .ngsummary.json files and only complains at the end because it can't find the app.module.ngfactory file, which makes sense, it was never created.

**Comment by ltenny** [comment]
After a little digging it looks like there is a slight change in behavior for ngc. In previous versions (e.g. 2.1.2)  some *.ngfactory.ts  files were generated into the app/node_modules/@angular directory. Not sure why. These include output files from node_module/@angular such as common_module.ngfactory.ts  The presence of these output files did not affect the generation of .ngfactory.ts files for the application.  Now with 2.4.3 these files must be deleted before ngc is run otherwise the application's .ngfactory.ts files will not be created, only .ngsummary.json files will be created.   I'm not entirely sure why anything is being created in the app/node_modules/ directory  Note that in this project, npm deposits files one directory up into node_modules, not into app/node_modules. The app directory contains all of the application's .ts files

So everything now works if I add a task in my gulpconfig.js to delete everything in app/node_modules before running ngc.  Works, but real ugly.

**Comment by thelgevold** [comment]
By specifying `genDir` in `angularCompilerOptions` the factories will go to a directory of your choosing

```
"angularCompilerOptions": {
    "genDir": "./aot",
    "debug": false
  }
```

**Comment by ltenny** [comment]
Yes...I have that configured, perhaps that's why the files show up there, but in 2.4.3 (unlike 2.1.2) when files such as common_module.ngfactory.ts are generated, they prevent all of the app's .ngfactory.ts files from being generated.  I needed to add a clean step in my gulpconfig.js to delete everything generated under the node_modules directory (below the 'genDir' directory) otherwise ngc would not generate any of the *.ngfactory.ts files for my app.  This seems to be new in 2.4.3

**Comment by ltenny** [comment]
After a little more research and perhaps to make things a bit more clear.  

It appears that early on ngc creates a directory named node_modules at the same level as "rootDir" (from tsconfig.json). ngc generates a bunch of *.ngfactory.ts files in a folder structure that mimics much of the @angular structure. Then ngc generates the *.ngfactory.ts files for the app placing these in the "genDir" from the "angularCompilerOptions" property in the tsconfig.json. These generated *.ngfactory.ts files import from the previously generated (under node_modules) *.ngfactory.ts files. Great. No problem. But, in 2.1.2 these *.ngfactory.ts files in node_modules could exist from previous compilations and would simply be overwritten.  In 2.4.3, if these *.ngfactory.ts files exist under node_modules, ngc just creates *.ngsummary.json files for the app and silently exits...well, almost silently, at the end it complains that app.module.ngfactory.ts doesn't exist of course because it failed to generate it.

**Comment by lucenty** [comment]
This works bad (as described by @ltenny) also when trying to follow the angular aot guide: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Comment by DzmitryShylovich** [comment]
@ltenny is this still valid in angular 4?

**Comment by tbosch** [comment]
Closing as no reply. Please reopen if this is still a problem for you.

**Comment by mistrykaran91** [comment]
I am also having the same issue my dist file is not coming any one can help on this ?
