### ISSUE TITLE
use FormControlDirective for not standalone FormControls

### ISSUE THREAD

**Issue by advgal** [angular/angular#13978]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you want to bind reactive forms to dom element you have to use FormControlName. 

**Expected behavior**
I want to be able to bind form controls of a FormGroup to a dom element by using the FormControl directive. The api reference says:
"Syncs a standalone FormControl instance to a form control element."
I want to use it not only on standalone FormControls

**Minimal reproduction of the problem with instructions**
that's the code I want to write
```
<!--outer component-->
<ul [formArrayName]="array">
  <li *ngFor="let control of form.get(key).controls">

    <app-text [control]="control"></app-text>

  </li>
</ul>
<app-text [control]="form.get(key2)"></app-text>

<!--text-box component-->
<input [formControl]="control" type="text">
```

**What is the motivation / use case for changing the behavior?**
I want to pass the FormControl to a component and the component does not need to know the FormGroup or FormArray the FormControl is a child of. 

**Please tell us about your environment:**

* **Angular version:** 2.1.X

* **Browser:** [all  ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add s small demo on Plunkr

**Comment by advgal** [comment]
A small demo of a feature that is not yet implemented?

**Comment by DzmitryShylovich** [comment]
A demo of what are you truing to accomplish

**Comment by DzmitryShylovich** [comment]
> I want to pass the FormControl to a component and the component does not need to know the FormGroup or FormArray the FormControl is a child of.

I don't without a demo how that is an angular issue

**Comment by advgal** [comment]
https://embed.plnkr.co/qdLY9V7CMviMHTUodYsq/

added text-box.component,
replaced input element in dynamic-form-question.component.html with tex-box, passing control as parameter

**Comment by DzmitryShylovich** [comment]
`ControlValueAccessor` ?

https://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html

**Comment by advgal** [comment]
Does not match my example. My issue is to pass a FormControl to a ControlValueAccessor, not to implement the interface ControlValueAccessor, in https://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html#binding-value-via-formcontrolname it is done by using FormControlName.

When it can be done with a view lines of code, please show me how.
If not, wouldn't it be nice to have a simple solution with FormControlDirective?

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
