### ISSUE TITLE
Angular language service missing extra close >

### ISSUE THREAD

**Issue by born2net** [angular/angular#13975]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
no error

**Expected behavior**
show error

**Minimal reproduction of the problem with instructions**
add an extra closing as in ```>```
```<Logo></Logo>> ```

I've had this happen to me several times where I would put an extra closing tag, and got some weird errors, be great of language service can detect matching open close ```</>``` and report on mismatches.

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/43584638-87a124a6-9695-11e8-8093-6105b84ea5c6.png)

Why would it become error?

**Comment by kyliau** [comment]
Angular language service does not produce HTML diagnostics. If you're using external templates on vscode, this is automatically handled by the native HTML extension.
