### ISSUE TITLE
Failures when compiling templates for inherited components

### ISSUE THREAD

**Issue by fricker** [angular/angular#13971]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

If I create an external template for a component that extends a base component that uses the same templateUrl I cannot add any components to that template that are not imported by the module that declared the base component. Compilation fails with template parse errors that indicate the added components are not known elements.

The only way I discovered the root problem was to take a look at the angular source code to understand the behavior of the angular compiler. The JitCompiler is failing when it tries to compile the base component, even though it's selector is not included in any template. If I change the templateUrl of the component that extends the base component to a different path then compilation fails with a 404 (Not Found) for the templateUrl of the base component.

**Expected behavior**

I would expect that the JitCompiler not try to compile ahead of time templates for component selectors that are not used in an application. I also expected error messaging that indicated the problem was related to the base component's templateUrl.

**What is the motivation / use case for changing the behavior?**

I am creating an abstract component library that provides support for clients that have differing template requirements. Two examples would be web (Angular Material) and mobile (NativeScript). I would like to maximize the encapsulation of common component and service behavior in this library and enable others to customize apps built with this library by editing a set of provided templates. The goal is to minimize the amount of complexity exposed to these template authors as much as possible.

**Please tell us about your environment:**

macOS Sierra, VS Code, Angular CLI

* **Angular version:** 2.0.X

2.3.1 and 2.4.3

* **Browser:**

Chrome 55.0.2883.95
 
* **Language:**

TypeScript 2.0.10, Library built with ngc

* **Node (for AoT issues):**

6.4.0

**Comment by DzmitryShylovich** [comment]
Pls add a small demo

**Comment by fricker** [comment]
demo: http://plnkr.co/edit/F3zBZnDQcyvWlOxO0tNf

**Comment by DzmitryShylovich** [comment]
> If I create an external template for a component that extends a base component that uses the same templateUrl I cannot add any components to that template that are not imported by the module that declared the base component

it's by design. But you can disable it by specifying `CUSTOM_ELEMENTS_SCHEMA` in `LibModule` http://plnkr.co/edit/f3OTtOZczTfoyB5D10DB?p=preview

**Comment by fricker** [comment]
I verified that applying CUSTOM_ELEMENTS_SCHEMA prevented the compiler failures for my project's use cases.

```
1. If 'unknown-component' is an Angular component, then verify that it is part of this module.
2. If 'unknown-component' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
```

The error messaging is unfortunate in that the components  that were not getting recognized are Angular components, not Web Components. I am concerned that the users of my library may now have to deal with silent failures if they need to inherit one of my base components. The upside is I am now more informed about the inner workings of the JITCompiler. Thanks for the help.
