### ISSUE TITLE
The question of "Template parse errors: 'router-outlet' is not a known element:"

### ISSUE THREAD

**Issue by nostubborn** [angular/angular#13977]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
I create a project using angular-cli,and when running the application,it occured the error:
> Unhandled Promise rejection: Template parse errors:
'router-outlet' is not a known element

**Expected behavior**

  it should run normally

**Minimal reproduction of the problem with instructions**
  you can clone it with https via  https://github.com/nostubborn/mydemo.git
  

**Please tell us about your environment:**I use the angular-cli  ,the tool is  webpack

* **Angular version:** 2.2

* **Browser:** [all ]

 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by DzmitryShylovich** [comment]
You need to import `RouterModule`
https://angular.io/docs/ts/latest/guide/ngmodule.html

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mtpultz** [comment]
@zhuqingguang if you haven't figured it out you need to add this to your spec file:

`import { RouterTestingModule } from '@angular/router/testing';`

and 

```
beforeEach(async(() => {
  TestBed.configureTestingModule({
    imports: [
      RouterTestingModule
    ],
    declarations: [
      YourComponent
    ]
  }).compileComponents();
}));
```

**Comment by Sreevenkateshn** [comment]
@mtpultz  where do i find documentation related TestingModules,
 llr to RouterTestingModule

**Comment by zimovchanin** [comment]
i catch this problem too
i remove import { AppRoutingModule } from './app-routing.module'; from app.module.ts
remove my app-routing.module.ts
perform in the terminal ng generate module app-routing --flat --module=app
and configure my new app-routing.module.ts
