### ISSUE TITLE
form of ngIf which don't effects content of tag

### ISSUE THREAD

**Issue by advgal** [angular/angular#13979]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ngIf removes the complete tree below element containing ngIf, when false.

**Expected behavior**
Directive which conditionally switches on or off just the element which contains the directive.

**Minimal reproduction of the problem with instructions**
I would like to write something like:

`<div ngIf2="switch"><p>....</p></div>`

and depending on `switch` the dom would be

`<div><p>....</p></div>`

or

`<p>....</p>`

**What is the motivation / use case for changing the behavior?**

conditionally write enclosing elements

**Please tell us about your environment:**

* **Angular version:** 2.1.X

* **Browser:** [all ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
IMO It should be provided as a 3rd party directive.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource I think it's out of angular scope

**Comment by pkozlowski-opensource** [comment]
I don't even think that 3rd party directive makes sense here... I would rather extract the common part to a separate component and put if / else around common part and common part + wrapping tag.

Closing as I don't think we want to have any specific directives for the use-case described here.
