### ISSUE TITLE
wrong formatted class selector for component throws error as of version 2.4.2

### ISSUE THREAD

**Issue by maartentibau** [angular/angular#13982]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In Angular `2.4.1` I can select a component with a class selector this way `[.my-class-selector]`. I was not aware this was not the proper way to do this, but never had an issue with it.

As of version `2.4.2` this does throw an error:

```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'namesList' since it isn't a known property of 'ul'. ("
    <div>
      <h2>Hello {{name}}</h2>
      <ul class="names" [ERROR ->][namesList]="namesList"></ul>
    </div>
```

**Expected behavior**
I know that I've written the class selector in a wrong way for this whole time, but I think it might be good to maybe make a notice or something about this, so that people might run into the same problem can find the proper solution easily

**Minimal reproduction of the problem with instructions**
Version: `2.4.1`: [https://plnkr.co/edit/IsAfgmuW499XvqgyHFxK?p=preview](https://plnkr.co/edit/IsAfgmuW499XvqgyHFxK?p=preview)

Version: `2.4.2`: [https://plnkr.co/edit/93MDDO?p=preview](https://plnkr.co/edit/93MDDO?p=preview)
Open console to see the error message

**What is the motivation / use case for changing the behavior?**
Well... I wouldn't mind if the previous behavior would be implemented again, but then again .. since it isn't the proper way to define a class selector I think it's not a very good idea to implement it again.

**Please tell us about your environment:**
`does not apply`

* **Angular version:** 2.0.X
2.4.1 --> it works
2.4.2 --> it throws an error

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
`does not apply`

**Comment by alexzuza** [comment]
Why do not you use it as `.my-class-selector`?

**Comment by maartentibau** [comment]
@alexzuza as I said. I wasn't under the assumption that I was doing anything wrong. I have refactored all my class selectors now to the correct way. But still, I think it would be good if a mention or something would be made in the changelog or so about this.

I really have been searching for hours, until @DzmitryShylovich pointed out to me my class selector was formatted incorrectly.

**Comment by DzmitryShylovich** [comment]
Looks like it was a "side effect" of https://github.com/angular/angular/pull/13653

**Comment by maartentibau** [comment]
I'm closing this issue. Thanks @DzmitryShylovich for pointing me in the right direction and finding the "side effect". I've added a PR so that a reference to this issue can be put into the `CHANGELOG` of the version `2.4.2` because it might be useful for other people as well.

Because before the release of version `2.4.2` Angular didn't mind this thing, and if you're not aware you're doing something wrong, you are really in for a long search, since the error you get from Angular isn't really helpful to be honest.

PR: [13985](https://github.com/angular/angular/pull/13985)
