### ISSUE TITLE
routerLink and `null` value should remove `href` attribute from link

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#13980]
```
[ ] bug report
[ x ] feature request
[ ] support request
```

**What is the motivation / use case for changing the behavior?**
Currently null or empty value passed to `routerLink` adds current page `href` value to link that is not useful. There is a lot of usecases for 'disabled' links that should not navigate anywhere and should not has `href` attribute at all.
It would be useful to have null/empty value support by `routerLink` that will results with no `href` attribute on link at all to prevent any navigation/link copying.

**Comment by artaommahe** [comment]
By the way it can be `routerLink` input like `routerLinkDisabled` that will not break current behavior.

**Comment by DzmitryShylovich** [comment]
I believe you can workaround it like `<a [attr.href]="condition ? commands : null">`
it should override `routerLink`

**Comment by artaommahe** [comment]
@DzmitryShylovich does not work and it requires to duplicate link. I use array route format for `routerLink`, `href` expects plain string

**Comment by jayoungers** [comment]
Any word on if this would make a release?

We have some high level links that are disabled depending on where the user is at in the application, and as of right now I don't think there's a way to remove the href of the anchor

**Comment by dmitrysteblyuk** [comment]
I didn't find the way to fully solve the issue with css so I came up with this workaround.

import { Directive, ElementRef, Renderer2, OnChanges, Input } from '@angular/core';

@Directive({
    selector: '[routerLink]'
})
export class EmptyRouterLinkDirective implements OnChanges {
    @Input() routerLink: any;

    constructor (private elRef: ElementRef, private renderer: Renderer2) {}

    ngOnChanges() {
        if (this.routerLink == null) {
            setTimeout(() => this.renderer.removeAttribute(this.elRef.nativeElement, 'href'), 0);
        }
    }
}

**Comment by intergleam** [comment]
I am facing this when trying to conditionally set internal or external link. Any ideas?

**Comment by Joelbear5** [comment]
I had to change from 
`<a routerLink="" class="dropdown">Dropdown</a>` 
to 
`<a [routerLink]="" class="dropdown">Dropdown</a>`
to get the null href link. Otherwise I continually got a page reload.

**Comment by jasonaden** [comment]
This should be fixed with #20922.

**Comment by oliverjanik** [comment]
Any news? We're on version 5 and basic navigation does not work.

**Comment by ctwhome** [comment]
I solved it with the directive mentioned here in the meanwhile
https://stackoverflow.com/a/45759794/2764278

**Comment by tarekis** [comment]
@DzmitryShylovich Since https://github.com/angular/angular/pull/14194 was closed in favor of https://github.com/angular/angular/pull/14498, which was closed too, is there any chance this will be fixed or was this issue completely abandoned?
Did you, by any chance, receive any feedback from the angular team on whether this behavior is intended, or there is a different problem with this issue all together?

**Comment by lppedd** [comment]
Any news for Angular 8?

**Comment by hoang-innomizetech** [comment]
I worked for me when using [null] 
```
[routerLink]="menuItem.path !== '' ? [menuItem.path] : [null]"
```

**Comment by atscott** [comment]
This issue still exists in v9: https://stackblitz.com/edit/angular-ivy-router-base?file=src%2Fapp%2Fapp.component.html

Non-breaking fix could be: #35393

**Comment by jarahn** [comment]
Have there been any updates to this? Setting [routerLink] = "null" does not work for the use case where there are parameters in the route.

**Comment by atscott** [comment]
@jarahn Are you using the `-next` version? This change is considered breaking, so we could only merge it to a major release branch.
