### ISSUE TITLE
preprocess HTML templates before using it for components

### ISSUE THREAD

**Issue by advgal** [angular/angular#13981]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Templates for components are just HTML text.

**Expected behavior**
I would like to write templates which are preprocessed by a template engine before

**Minimal reproduction of the problem with instructions**
It would be nice to write templates like this:
```
//component
templateURLparsed="component.html"
<!-- component.html -->
$$button_deco:'class="btn btn-secondary btn-danger" type="button"'
<button $$button_deco >one</button>
<button $$button_deco >two</button>
<button $$button_deco >three</button>
<button $$button_deco >four</button>

```
this is just a poor example of a template language but it shows the principle, $$button_deco is to be inserted into 4 places.

**What is the motivation / use case for changing the behavior?**
Writing less text.
In some cases this solution is easier than factoring out code to components.

**Please tell us about your environment:**

* **Angular version:** 2.1.X

* **Browser:** [all ]

 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =

**Comment by mlc-mlapis** [comment]
It would not be usable for AOT mode.

**Comment by trotyl** [comment]
If you're using webpack, you can append whatever loaders you like before `angular2-template-loader`.

**Comment by pkozlowski-opensource** [comment]
Thnx for the suggestion but this is outside of the scope of the current Angular. As other suggested you might process your templates during build time using templating language of choice.

**Comment by advgal** [comment]
I am using angular-cli. How do I configure loaders for webpack there? Is this an issue for angular-cli?
