### ISSUE TITLE
"const variableName = {value};" causing error:  "Reference to a local (non-exported) symbol 'variableName'

### ISSUE THREAD

**Issue by darkkean** [angular/angular#13983]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Having error on compilation after running `ng serve` showing:

```
ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'dictionary'. Consider exporting the symbol (position 11:7 in the original .ts file), resolving symbol TRANSLATION_PROVIDERS in /apps/web-frontend-ng/src/app/translate/translations.ts, resolving symbol TRANSLATION_PROVIDERS in /apps/web-frontend-ng/src/app/translate/index.ts, resolving symbol AppModule in /apps/web-frontend-ng/src/app/app.module.ts, resolving symbol AppModule in /apps/web-frontend-ng/src/app/app.module.ts
```

This error started on Angular 2.4. Previously on version 2.2, it is still working fine. Did I miss something?

**Expected behavior**
The code should compile fine with no errors.

**Minimal reproduction of the problem with instructions**
I have a `translation.ts` file which contain constant values.

```
import { OpaqueToken } from '@angular/core';

// import translations
import { LANG_EN_NAME, LANG_EN_TRANS } from './lang-en';
import { LANG_ID_NAME, LANG_ID_TRANS } from './lang-id';

// translation token
export const TRANSLATIONS = new OpaqueToken('translations');

// all translations
const dictionary = {
    [LANG_EN_NAME]: LANG_EN_TRANS,
    [LANG_ID_NAME]: LANG_ID_TRANS,
};

// providers
export const TRANSLATION_PROVIDERS = [
    { provide: TRANSLATIONS, useValue: dictionary },
];
```

Now in my `app.module.ts` file, I imported this and added to providers section.

```
import {TRANSLATION_PROVIDERS} from './translate';

@NgModule
    declarations: [...],
    imports:  [...],
    providers: [TRANSLATION_PROVIDERS],
    bootstrap: [
      AppComponent
    ]
})
export class AppModule {}
```

**What is the motivation / use case for changing the behavior?**
Not applicable, I guess.

**Please tell us about your environment:**
angular-cli: 1.0.0-beta.22
node: 6.9.4
os: darwin x64

* **Angular version:**
2.4.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
not applicable.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

* **Node (for AoT issues):** `node --version` = v6.9.4

**Comment by DzmitryShylovich** [comment]
```
export const dictionary = {
    [LANG_EN_NAME]: LANG_EN_TRANS,
    [LANG_ID_NAME]: LANG_ID_TRANS,
};
```

**Comment by darkkean** [comment]
@DzmitryShylovich Thanks for the feedback. After doing that, still throwing an error:

```
ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 12:5 in the original .ts file), resolving symbol dictionary in /apps/web-frontend-ng/src/app/translate/translations.ts, resolving symbol TRANSLATION_PROVIDERS in /apps/web-frontend-ng/src/app/translate/translations.ts, resolving symbol TRANSLATION_PROVIDERS in /apps/web-frontend-ng/src/app/translate/index.ts, resolving symbol AppModule in /apps/web-frontend-ng/src/app/app.module.ts, resolving symbol AppModule in /apps/web-frontend-ng/src/app/app.module.ts
```

It seems that even it is already exported, it still can't see it.

**Comment by DzmitryShylovich** [comment]
Pls add a github repo with a small demo

**Comment by darkkean** [comment]
Removing the brackets fixed my error.

```
export const dictionary = {
    LANG_EN_NAME: LANG_EN_TRANS,
    LANG_ID_NAME: LANG_ID_TRANS,
};
```

**Comment by DzmitryShylovich** [comment]
https://github.com/rangle/angular-2-aot-sandbox#property-accessors-top here you can find the list of currently supported/unsupported by aot features

**Comment by thigrand** [comment]
> Removing the brackets fixed my error.
> 
> export const dictionary = {
>     LANG_EN_NAME: LANG_EN_TRANS,
>     LANG_ID_NAME: LANG_ID_TRANS,
> };
Yeah, error msg dissapear, but translation feature also. It doesn't work now.

**Comment by RasalShukla** [comment]
const dictionary  = {
    [LANG_EN_NAME]: LANG_EN_TRANS,
    [LANG_FR_NAME]: LANG_FR_TRANS,

};
i am also getting the same error , so do one thing directly write the language value in place of array 

const dictionary  = {  "en-US": LANG_EN_TRANS,   "fr-FR": LANG_FR_TRANS };
Thanks enjoy     Happy Coding       [Code and translation both are working fine]

**Comment by yeimmycl** [comment]
Thanks RasalShukla it works for me
