### ISSUE TITLE
"A type literal property cannot have an initializer" in nested model fields

### ISSUE THREAD

**Issue by nisenish** [angular/angular#13986]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

  address: {
    street: string = "";
    street2?: string;
    ...
  }
  gives following error: "A type literal property cannot have an initializer"

**Expected behavior**

I should be able to initialize nested model fields.

**Minimal reproduction of the problem with instructions**

create a typescript file for your model and have something like:
  address: {
    street: string = "";
  }

**What is the motivation / use case for changing the behavior?**

We need this to bind empty model to a form. Another good option to do this would be using elvis operator in two way binding (myModel.address?.street), there's another bug for this (#7697).

**Please tell us about your environment:**

* **Angular version:** 2.0.X

I am using 2.0.0 beta build.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
It's a typescript error. how is this related to angular?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
