### ISSUE TITLE
Instantiate abstract component is possible

### ISSUE THREAD

**Issue by wKoza** [angular/angular#13994]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I create an abstract component class, it's possible to 'instantiate' it 

semantically, it isn't normal to be able to instantiate an abstract class.

**Expected behavior**
we cannot create an instance of an abstract class / Component

**Minimal reproduction of the problem with instructions**

see plunkr : [https://plnkr.co/edit/A7Ja9FS4WlGYJ6tHM8HY?p=preview](https://plnkr.co/edit/A7Ja9FS4WlGYJ6tHM8HY?p=preview)

* **Angular version:** 2.3.X

 
* **Language:** [TypeScript X.X]

**Comment by pkozlowski-opensource** [comment]
This is fixed in Angular v9 running ivy where it is no longer possible to add an abstract component to `NgModule`: https://ng-run.com/edit/r1B61BrxTc6gXcTvk7KK
