### ISSUE TITLE
Core API: implementing Renderer requires types from private exports

### ISSUE THREAD

**Issue by platosha** [angular/angular#14001]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The `animate` abstract method from the `Renderer` abstract class is defined using types only available though private exports, namely: `AnimationStyles`, `AnimationKeyframe`, `AnimationPlayer`, `NoOpAnimationPlayer`.

**Expected behavior**
All the types to implement `animate` are public, or the `animate` is not required in the `Renderer`.

**Minimal reproduction of the problem with instructions**
1. Define a TypeScript Angular module.
2. In the module, implement and provide a `RootRenderer` injectable service with a custom `Renderer` implemention.
3. TypeScript compiler refuses to compile the `Renderer` without the `animate` method. After trying to add it, the issue occurs.

**What is the motivation / use case for changing the behavior?**
The `Renderer` is a public API, although experimental. Implementing a `Renderer` makes low-level DOM adjustments possible, those are sometimes essential to use together with third-party component libraries, such as `Polymer`.

As for now, a custom `Renderer` implementation is not achievable without importing the animation types mentioned above from private core exports.

**Please tell us about your environment:**

* **Angular version:** 2.3.X

* **Browser:** all

 
* **Language:** TypeScript 2.0.10

**Comment by DzmitryShylovich** [comment]
`AnimationPlayer` is exported
