### ISSUE TITLE
Unhandled routes or wild card routes not working with router.resetconfig()

### ISSUE THREAD

**Issue by Sri276286** [angular/angular#14006]
Hi,

I am able to add new routes dynamically with router.resetConfig()

I am facing an issue with unhandled routes now which worked well before adding routes dynamically.

Here is the code for reference.

```
import { NgModule }             from '@angular/core';
import { RouterModule, Routes, ActivatedRoute, provideRoutes, Router } from '@angular/router';
import { ErrorComponent } from './error/error.component';

let routes: Routes = [
{ path: '', redirectTo: 'home', pathMatch: 'full'},
{ path: 'home', loadChildren: './dashboard/dashboard.module#DashboardModule' }
// **working fine if I place { path: '**', component:ErrorComponent } here.** 
];

// **Dynamically added routes**
 let tpg_routes = [
   { path: 'mytpg', loadChildren: './mytpg/mytpg.module#MyTpgModule' }
 ];

let err_routes = [ { path: '**', component:ErrorComponent }];   // **not working**
 let newRoutes = routes.concat(tpg_routes);

@NgModule({
  imports: [ RouterModule.forRoot(routes) ],
  exports: [ RouterModule ]
})
export class AppRoutingModule {
  constructor(private router:Router){
     router.resetConfig(newRoutes);
  }
}
```

Please help me to fix this.

Note : I am clear on this point from https://angular.io/docs/ts/latest/guide/router.html#!#wildcard-route :
The router selects the route with a first match wins strategy. Wildcard routes are the least specific routes in the route configuration. Be sure it is the last route in the configuration.

**Comment by DzmitryShylovich** [comment]
Pls add s small repro on Plunkr

**Comment by Sri276286** [comment]
https://embed.plnkr.co/wBorFvoG3hfD36iOcNqu/ -- This plunker has code. Probably you can have a look and make it working.

**Comment by DzmitryShylovich** [comment]
> Here when clicking "tofoo" it has to display error component message

why?

**Comment by Sri276286** [comment]
Because routerLink is pointing to a wrong path. If path is wrong , I want to load ErrorComponent

**Comment by DzmitryShylovich** [comment]
did u save changes? because everything is correct `<a routerLink="foo">to foo</a>`

**Comment by Sri276286** [comment]
https://plnkr.co/edit/gXdB8AeThZbIvCB62Wl7?p=preview please have a look at this

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/HJtahdKhJgweTQZB85Us?p=preview

**Comment by Sri276286** [comment]
https://plnkr.co/edit/hmU5CSNaW4Mh4nJnRq21?p=preview Tried to implement lazy loading. Please correct this

**Comment by DzmitryShylovich** [comment]
This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Sri276286** [comment]
Please help me to fix this alone.

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/lM4al1BGFSiChHZD5Yp0?p=preview
the last time :)

**Comment by Sri276286** [comment]
Relative paths work with loadChildren in Angular2 right?

Why it's not working here and what made you to give full path?

**Comment by Sri276286** [comment]
One thing I observed after using resetConfig() is that "I lost social url support which means unable to navigate to links from browser url bar directly"

For ex : localhost:3200/mytpg --> entering this directly in browser url bar unable to navigate

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource support request

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
