### ISSUE TITLE
Can't bind to 'ngPluralCase' since it isn't a known property of 'template'.

### ISSUE THREAD

**Issue by amaschas** [angular/angular#14000]
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using the updated ngPluralCase directive throw an exception:

**Expected behavior**
Component should render without errors.

**Minimal reproduction of the problem with instructions**
The issue in #12363 was supposedly fixed by swapping `ng-container` for `template`, (via the example in commit f364557629754184251a37b87be050b685055134) but it appears to generate the same error as demonstrated in this plnkr:

https://embed.plnkr.co/OSmIjqVerdv7B2jTwaav/

```
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { Component, NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";

@Component({
  selector: "my-app",
  template:`
  <div [ngPlural]="1">
      <template *ngPluralCase="'=0'">...</template>
      <template *ngPluralCase="'other'">...</template>
  </div>
  `,
  styles: []
})
class AppComponent {

}

@NgModule({
  imports: [
    BrowserModule
  ],
  declarations: [AppComponent],
  exports: [AppComponent],
  bootstrap: [AppComponent]
})
class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);
```

Also worth noting that the docs still refer to `ng-container`.

**Please tell us about your environment:**

* **Angular version:** 2.4.3

* **Browser:** [Chrome 55]

 
* **Language:** [TypeScript 2.1.5]

**Comment by DzmitryShylovich** [comment]
works as expected https://plnkr.co/edit/gRgeY3V8RRmvJZ5QzZDu?p=preview

> Also worth noting that the docs still refer to ng-container.

where? https://github.com/angular/angular/blob/master/modules/%40angular/common/src/directives/ng_plural.ts#L24

**Comment by akirasosa** [comment]
@amaschas
These documents are outdated.
https://angular.io/docs/ts/latest/api/common/index/NgPlural-directive.html
https://angular.io/docs/ts/latest/api/common/index/NgPluralCase-directive.html

You have to write something like ```<template ngPluralCase="other">```.

**Comment by vicb** [comment]
API docs are up to date:
```
 * ```
 * <some-element [ngPlural]="value">
 *   <template ngPluralCase="=0">...</template>
 *   <template ngPluralCase="other">...</template>
 * </some-element>
 *```

angular.io is out of sync for now
