### ISSUE TITLE
Split out angular repo into respective namespaced npm modules

### ISSUE THREAD

**Issue by chrisjlee** [angular/angular#14012]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
angular/angular in github is all in one repo while it publishes many different npm modules that are namespaced

**Expected behavior**
split out each module (http, core, common) into it's own github repo and make them truly modular. 

**Minimal reproduction of the problem with instructions**

n/a

**What is the motivation / use case for changing the behavior?**

* Makes discovering the code easier to manage for newcomers. 
* The issue queue would be simpler to review.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** all

n/a
 
* **Language:** all
* **Node (for AoT issues):** `node --version` =   all

**Comment by pkozlowski-opensource** [comment]
Sorry, this won't happen any time soon (if ever) as it would incur huge maintenance cost / complexity for us.   The good news is that [this folder](https://github.com/angular/angular/tree/master/modules/%40angular) has layout where each sub-folder corresponds to a npm module (this not true for all the folders but most of them directly correspond to npm modules).

**Comment by tytskyi** [comment]
Hi @chrisjlee i would say that this is a lot easier to navigate Angular code when it's together.

I suggest you to clone/download repo to your laptop and run some smart IDE. 

With IDE you can quickly get a big picture how something is connected to something.

You just need to select some element's and use navigation options (in my IDE it's - Find Usages). Then you can quickly reason about it, discover how it is used. If you combine this with search by regular expressions - then you get the super power.

What you better not to do - is discovering code using browser.

**Comment by chrisjlee** [comment]
Thanks nonethless, i didn't think it would fly but i was curious what the rational was 😄

**Comment by DzmitryShylovich** [comment]
https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc

**Comment by chrisjlee** [comment]
Ok my other problem is now how do i discover it's dependencies? Their package.json's are templated
