### ISSUE TITLE
Using TestBed.overrideComponent() with webpack (Angular-CLI) has no effect.

### ISSUE THREAD

**Issue by DaveMBush** [angular/angular#14016]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I use 
```
    TestBed.overrideComponent(component,{
        set: {
            template: 'xyz'
        }
    });

   TestBed.createComponent(AppComponent)
```
The component renders the original template instead of 'xyz'

**Expected behavior**

I would expect it would render the template in the override

**Minimal reproduction of the problem with instructions**

Here is a sample test spec
```
import {TestBed, async} from '@angular/core/testing';
import {AppComponent} from './app.component';
import {XyzModule} from 'xyz';
impott {XyzComponent} from 'xyz';
import {AppRoutes} from './app.routes';
import {HttpModule} from '@angular/http';
import {FormsModule} from '@angular/forms';
import {BrowserModule} from '@angular/platform-browser';
import {APP_BASE_HREF} from '@angular/common';

describe('AppComponent', () => {
    let fixture;
    let app;
    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [
                AppComponent
            ],
            imports: [
                BrowserModule,
                FormsModule,
                HttpModule,
                XyzModule,
                AppRoutes
            ],
            providers: [
                {provide: APP_BASE_HREF, useValue: '/'}
            ]

        }).overrideComponent(XyzComponent, {
            set: {
                template: 'xyz'
            }
        });

        fixture = TestBed.createComponent(AppComponent);
        app = fixture.debugElement.componentInstance;
    }));

    it('should create the app', async(() => {
        expect(app).toBeTruthy();
    }));

    it('should render "xyz"', async(() => {
        fixture.detectChanges();
        const compiled = fixture.debugElement.nativeElement;
        expect(compiled.textContent).toContain('xyz');
    }));
});

```

**What is the motivation / use case for changing the behavior?**

Isolate component testing so I am only testing that the components were rendered as children of another component.

**Please tell us about your environment:**

Windows using Angular-CLI beta.25.5 and Angular 2.4.3

* **Angular version:** 2.4.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

I'm using PhantomJS for my tests, but I don't expect it would matter.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
I'm using TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   
node 6.7.0

**Comment by DaveMBush** [comment]
Sorry.  Not an issue

**Comment by gnitsenko93** [comment]
Hey @DaveMBush 
Why did you close the issue?

I have the same strange behaivor of overrideComponent with webpack but in terms of mocking a service for a component.

**Comment by DaveMBush** [comment]
As I remember things, the problem was my own confusion.  Once I fixed my code it worked as expected

**Comment by azulay7** [comment]
Hi @DaveMBush 
I'm glad to finally find someone who's trying to test a component that holds components from diffrent modules.
same as you I'm trying to to test only my component.
my problem is that in my main component I have @ViewChild that holds the sub compoonent, and I ean to spy and test single function.
I will be thankfull for any help.

export class MyComponent {

  @ViewChild(ChildComponent)
  private childComponent: ChildComponent;
  
  
  public iWantToTestIt()
  {
    childComponent.someFunction(); //spy on this function
  }

}
