### ISSUE TITLE
[i18n] Extraction failed: No template specified for component

### ISSUE THREAD

**Issue by lihanyu23** [angular/angular#14010]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I use ng-xi18n to extract translation source file from templates, it throws "No template specified for component" if the template is imported from ambient ts module:

```
import Template from './template.html';

@Component({
  selector: 'my-component',
  template: Template
})
export class MyComponent {}
```
**Similar issues for importing styles from module. (Error: Expected 'styles' to be an array of strings.)**

I have declared `shared/template.html.d.ts` as wildcard ambient module for matching *.html template file.
```
declare module '*.html' {
  const template: string;
  export default template;
}
```

This works well with classic JIT tsc compiler. I'm using SystemJS as module loader.
My tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "rootDir": "src",
    "outDir": "public",
    "lib": [ "es2015", "dom" ],
    "types": [
      "hammerjs"
    ]
  },
  "exclude": [
    "node_modules/*",
    "public/*"
  ],
  "angularCompilerOptions": {
    "genDir": "src/assets/locale",
    "skipMetadataEmit": true,
    "trace": true
  }
}
```

**Expected behavior**

Importing template as string from module should be resolved as inline template.

**Minimal reproduction of the problem with instructions**

```
$ ./node_modules/.bin/ng-xi18n -p tsconfig.json --basePath src
Error: No template specified for component MyComponent
    at SyntaxError.BaseError [as constructor] (/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:1595:29)
    at new SyntaxError (/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:1793:18)
    at DirectiveNormalizer.normalizeTemplate (/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:13562:21)
    at CompileMetadataResolver._loadDirectiveMetadata (/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:17874:77)
    at /xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:18050:56
    at Array.forEach (native)
    at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:18049:43)
    at /xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:27729:86
    at Array.map (native)
    at Extractor.extract (/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:27729:30)
Extraction failed
```

**What is the motivation / use case for changing the behavior?**

Importing templates as string from module has 2 advantages : 

- Keeps template html separate while developing, making it possible to profit IDE features for template editing.
- Easy to bundle templates into js modules for production use.

**Please tell us about your environment:**

* **Angular version:** 2.4.3

* **Browser:** all

 
* **Language:**  TypeScript 2.1.5

* **Node (for AoT issues):** `node --version` =  v6.6.0

**Comment by vicb** [comment]
Angular expect a string here.

According to your build env, you probably can add a plugin that would inline the template.

Closing as not an Angular issue - but related to the build config.

**Comment by Luzianadewi** [comment]
i have an error

Runtime Error
No template specified for component TabsPage

how to fix it?
help me please
