### ISSUE TITLE
Problem with pattern validation

### ISSUE THREAD

**Issue by vihuarar** [angular/angular#14028]
**I'm submitting a ...**  
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm doing a pattern validation related to a field named "email", checking this pattern "^[a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,15})$" 

It works most times... but when I type "adfsaf@dafsdfcom" it match the pattern.. but it should not match

**Expected behavior**
I'm checking the regex "^[a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,15})$" in the page:
https://regex101.com/

When I check the previous example "adfsaf@dafsdfcom" it doesnt match the pattern...  but in Angular 2 it match the pattern

**Minimal reproduction of the problem with instructions**
this is my code in the the x.component.ts
```
this.myForm = new FormGroup({
            nombre: new FormControl('', [<any>Validators.required ]),
            email: new FormControl('', [<any>Validators.pattern("^[a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,15})$") ]),
        });

```

This is my code in the x.component.ts
    <form [formGroup]="myForm" novalidate (ngSubmit)="save(myForm.value, myForm.valid)">
                <div class="form-group">
                        <label for="nombre">Nombre completo</label>
                        <input type="text" class="form-control" formControlName="nombre">

                    <small [hidden]="myForm.controls.nombre.valid || (myForm.controls.nombre.pristine && !submitted)">
                        Nombre es obligatorio
                    </small>
                </div>
                <div class="form-group col-md-6">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" formControlName="email">
                    <small [hidden]="myForm.controls.email.valid || (myForm.controls.email.pristine && !submitted)">
                        Campo invalido
                    </small>
                </div>
    </form>

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Ubuntu 16.04
Visual studio code

* **Angular version:** 2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Google Chrome Version 54.0.2840.100 (64-bit)

 
* **Language:** [TypeScript 2.0.10 ]

* **Node (for AoT issues):** `node --version` =   7.2.1

**Comment by DzmitryShylovich** [comment]
Pls add a small demo on Plunkr

**Comment by Markovy** [comment]
Have you tried to use `\\.` insted of `\.` in your string pattern?

**Comment by tytskyi** [comment]
@vihuarar please try to pass `/^[a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,15})$/` instead of string

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).

**Comment by vihuarar** [comment]
@tytskyi  your suggestion works perfectly...
Whats the difference? in what cases I should use that insted of a string?

**Comment by tytskyi** [comment]
@vihuarar consider source code https://github.com/angular/angular/blob/2.4.0/modules/%40angular/forms/src/validators.ts#L104

When you pass a string then validator will wrap it with `^` and `$`.
Otherwise it treat it as RegExp (no matter what you pass).

Well, RegExp is a bit more flexible: for example you don't want to check start-end.
Personally, i prefer always RegExp.

**Comment by vihuarar** [comment]
thank you @tytskyi but is not clear enoght
So... I have this other rule:
fecha_de_nacimiento: new forms_1.FormControl('', [ forms_1.Validators.pattern("^\d{4}-\d{2}-\d{2}$") ]),
I should pass it like: (because it already wrapped it?
fecha_de_nacimiento: new forms_1.FormControl('', [ forms_1.Validators.pattern("\d{4}-\d{2}-\d{2}") ]),
I also tried this: (but not worked)
fecha_de_nacimiento: new forms_1.FormControl('', [ forms_1.Validators.pattern("/^\d{4}-\d{2}-\d{2}$/") ]),
that is to validate a date....

**Comment by tytskyi** [comment]
@vihuarar i extracted code that builds pattern in your version of angular:

```javascript
function buildPattern(pattern) {
  let regex;
  let regexStr;

  if (typeof pattern === 'string') {
    regexStr = `^${pattern}$`;
    regex = new RegExp(regexStr);
  } else {
    regexStr = pattern.toString();
    regex = pattern;
  }
    
  return regex;
}

// Consider your string inputs:
let re1 = buildPattern("^\d{4}-\d{2}-\d{2}$")
// output: /^^d{4}-d{2}-d{2}$$/

let re2 = buildPattern("\d{4}-\d{2}-\d{2}")
// output: /^d{4}-d{2}-d{2}$/

let re3 = buildPattern("/^\d{4}-\d{2}-\d{2}$/")
// output: /^\/^d{4}-d{2}-d{2}$\/$/

re1.test("1234-24-23")
// false

re2.test("1234-24-23")
// false

re3.test("1234-24-23")
// false
```

Let's now consider `re2` 
```javascript
// input
"\d{4}-\d{2}-\d{2}"

// output
/^d{4}-d{2}-d{2}$/
```

Notice all backslashes gone `\`. 
That's because how `RegExp` constructor works - you need to escape some symbols. (details: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Description)

So this works.

```javascript
buildPattern("\\d{4}-\\d{2}-\\d{2}").test("1234-24-23")
```

I suggest you to just always use regular expression instead of validator and do not do extra work escaping pattern. 
I hope all is clear now.

**Comment by vihuarar** [comment]
Thanks!

**Comment by diamond-darrell** [comment]
@DzmitryShylovich , hi, I've run into some strange behavior of pattern validator, but don't know if it's deserved own issue.
I need to validate field if it has at least on caps letter and one number, so I've used pattern validator with this regexp `/^(?=.*[A-Z])(?=.*\d).*$/g`. It validates field very weird if I type an even number of symbols it validates correctly (for example `Q1`, `Q1as` and so on), but an odd number of symbols always give me an invalid state of the field (`Q1a`, `Q1as3`, ...).
I've provided an example on plunker: https://plnkr.co/edit/TaVfZ6bk5mY9kKj64sKb?p=preview
But, if I remove `g` flag from regular expression it works as expected.
Please, take a look, is it an issue of the pattern validator or I just wrote incorrect regexp?
Thank you :smile:

**Comment by DzmitryShylovich** [comment]
@diamond-darrell regex http://prntscr.com/ecc4qh

**Comment by diamond-darrell** [comment]
@DzmitryShylovich , yeah, it's really weird http://dl3.joxi.net/drive/2017/02/23/0011/0145/733329/29/4257c8c93d.jpg

I'm sorry to have bothered

**Comment by DzmitryShylovich** [comment]
@diamond-darrell we can't re-create a regex every time but we can probable reset `lastIndex` to 0

**Comment by MoAsmar** [comment]
Thanks @tytskyi , same case here, solved my problem by wrapping it with '/ myregex /'

**Comment by Bridgeway** [comment]
Having similar issue in Angular 6:
Simply trying to validate an eleven digit UK phone number
![mobile phone valid](https://user-images.githubusercontent.com/26764749/45208384-5b2d7b00-b282-11e8-8c2b-136d575ea4b3.png)

**Comment by PeymanKhodadust** [comment]
I have 3 different patterns which are all tested on regexr.com and on regex101.com. I have tried all different methods mentioned here to instantiate a regex. With all of the methods the form validator shows very weired behaviour. When I tip the value into the input field sometimes it shows invalid but when I cut that string and paste it again into the same input, it shows valid. At this point, I don't think this is a problem of the regex patterns or the constructor but a problem of the form validator.

This is my code:
`  phonePattern = /(0|0041|\+41)(\s?\(0\))?(\s)?[1-9]{2}(\s)?[0-9]{3}(\s)?[0-9]{2}(\s)?[0-9]{2}/g;
  zipPattern = /(CH-)?[1-9][0-9]{3}/g;
  nrPattern = /[1-9][0-9]+[a-z,A-z]?/g;
`
...

`
  initFormGroup() {
    this.formGroup = this._fb.group({
      "nr": new FormControl("", {validators: [Validators.required, Validators.pattern(this.nrPattern)], updateOn: "change"}),
      "zip": new FormControl("", {validators: [Validators.required, Validators.pattern(this.zipPattern)], updateOn: "change"}),
      "phoneNr": new FormControl("", {validators: [Validators.required, Validators.pattern(this.phonePattern)], updateOn: "change"})
    });
`

as I said, I have already tried the following:
`
  phonePattern = new RegExp(/(0|0041|\+41)(\s?\(0\))?(\s)?[1-9]{2}(\s)?[0-9]{3}(\s)?[0-9]{2}(\s)?[0-9]{2}/g);
  phonePattern = /^(0|0041|\+41)(\s?\(0\))?(\s)?[1-9]{2}(\s)?[0-9]{3}(\s)?[0-9]{2}(\s)?[0-9]{2}$/g;
  phonePattern = "/(0|0041|\\+41)(\\s?\\(0\\))?(\\s)?[1-9]{2}(\\s)?[0-9]{3}(\\s)?[0-9]{2}(\\s)?[0-9]{2}/g";
`
All variants show the same behaviour.

Thanks in advance

**Comment by PeymanKhodadust** [comment]
It is a bit like my comment above. Some arbitrary part of what I mark as code is rendered with that special style others not...

**Comment by trotyl** [comment]
@PeymanKhodadust Please take a look at https://stackoverflow.com/questions/2141974/javascript-regex-literal-with-g-used-multiple-times

The problem is that /g RegExps are stateful and the result is based on last match, you should never use global flag in form validation.

I’ll suggest to discuss JavaScript behavior in other threads if not relates to Angular.

**Comment by PeymanKhodadust** [comment]
@trotyl Thanks a lot dude!! Sry, I 'm not really fit with regexps due to lack of time...
