### ISSUE TITLE
RegExp bug since angular 2.4.2

### ISSUE THREAD

**Issue by hmarchadour** [angular/angular#14029]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Since angular 2.4.2, I've a bug on angular bootsrap only on Firefox 31 

**Expected behavior**
The RegExp should not throw a SyntaxError: invalid range in character class error on Firefox 31

**Minimal reproduction of the problem with instructions**
I've replay a <a href="https://plnkr.co/edit/xfhUu1FJmz3MR1y2V7Qz?p=preview">plunker demo</a> according to the pullrequest #13653 that seems introduce this bug.

It's a minimal script that can be reproduce on Firefox 31 according to <a href="https://github.com/angular/angular/commit/881eb894bc17092e61842e8b37955344829510c9#diff-79d7545cee5796c175e7e5595e489cd7">modules/@angular/compiler/src/selector.ts </a>.

**What is the motivation / use case for changing the behavior?**
XULRunner 31 (understand a subset of Firefox 31)  is the last compatible release supported on Eclipse (Mars/Neon) to embed a Firefox runtime in an Eclipse product.
Firefox 31 works well before angular 2.4.2 with webpack (I don't know with SystemJs).
Actually, angular 2.4.1 is the last compatible release of angular with a embedded Firefox runtime Eclipse product.
**Please tell us about your environment:**

I've replay this problem only on Firefox 31 (the Operating system does not matter)
* **Angular version:** 2.4.2

* **Browser:** [ Firefox 31 ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =  does not matter

**Comment by hmarchadour** [comment]
To get Firefox 31 https://ftp.mozilla.org/pub/firefox/releases/31.0/

**Comment by DzmitryShylovich** [comment]
I believe this https://github.com/angular/angular/pull/13900 will fix it

**Comment by hmarchadour** [comment]
A workaround -> build with AOT option
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!/%23aot-jit
