### ISSUE TITLE
the router article of high chapater can not run.

### ISSUE THREAD

**Issue by zhaojw83** [angular/angular#14025]
Hello,master:
I read the chinese version ,the page url is :https://angular.cn/docs/ts/latest/guide/router.html
I can not compile it,because this file have a error.
I change the file crisis-detail-resolve.service.ts into down:
export class CrisisDetailResolve implements Resolve<Crisis | boolean >{
    constructor(private cs: CrisisService, private router: Router) { }

    resolve(route: ActivatedRouteSnapshot): Promise<Crisis> | boolean{
        let id = route.params['id'];

        return this.cs.getCrisis(id).then(crisis => {
            if (crisis) {
                return crisis;
            } else {
                this.router.navigate(['/crisis-center']);
                return false;
            }

        });
    }
}

then,it can be compiled.But I have some runtime error:

/******************error one of 3********/
core.umd.js:3531 Error: Template parse errors:
Unexpected closing tag "label" ("
        </div>
        <div>
            <lable>Name:[ERROR ->]</label>
            <input [(ngModel)]="editName" placeholder="name" >
        </div>
"): CrisisDetailComponent@8:24
Unexpected closing tag "div" ("        <lable>Name:</label>
            <input [(ngModel)]="editName" placeholder="name" >
        [ERROR ->]</div>
        <p>
            <button (click)="save()">Save</button>
"): CrisisDetailComponent@10:8
Unexpected closing tag "div" ("
            <button (click)="cancel()">Cancel</button>
        </p>
      [ERROR ->]</div>
"): CrisisDetailComponent@15:6
/*************error end*********/
I am so sorry,i can not solve this problem,as i am just a Angular beginner.So Could you solve it.
Thank you.
If you fix it,can you send me one message,the email:   126.com.Thank you very much.

All the best for you.

Mark.
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
