### ISSUE TITLE
Create hostAttributes support

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1402]
## Goal

To be able to statically describe attributes on host element.

Example: <md-button> needs to be declared as <md-button aria-role="button"> for proper behavior. Doing this imperatively would be unnecessarily slow. Changing the template is more effective.

## API

```javascript
@Component({
  selector: 'md-button',
  hostAttributes: {
    'role': 'button'
  }
})
@View(...)
class MdButton {}
```

**Comment by vsavkin** [comment]
I think @tbosch might be a better person to work on this because this requires only changing the compiler.

**Comment by naomiblack** [comment]
@pkozlowski-opensource how do you feel about taking this one on?

**Comment by pkozlowski-opensource** [comment]
@naomiblack would be keen on taking it - funny thing, we've been just discussing this very part internally today.

**Comment by pkozlowski-opensource** [comment]
@mhevery @jelbourn here is a crazy idea of an alternative syntax that we've been toying with today. So, as of now we've got the following properties of a @Component annotation:
* `hostProperties`
* `hostListeners`
* `hostAttributes`

and it feels like those are part of a component's template - it is just that we don't have an appropriate element on which we could stick those (as a host element is not part of a component's template). But how about creating such an element? Ex.:

```javascript
@Component({
  selector: 'md-button',
  host: '<host aria-role="button" [prop]="exp"></host>'
})
@View()
class MdButton {}
```

or

```javascript
@Component({
  selector: 'md-button'
})
@View({
    template: `'<host role="button" [prop]="exp">...the real tpl goes here.. </host>'`
})
class MdButton {}
```

I'm not sure if this is implementable or if there are corner cases not covered here (probably there are!) but just wanted to bounce off some ideas we've been discussing.

**Comment by jelbourn** [comment]
This actually has gone through my mind before! In some ways, I really like the idea of being able to declaratively bind stuff to the host element. However, my problem with doing this is that it somewhat muddies the very distinction between the host element and its view (shadow content). For me, a large part of understanding Angular 2 is understanding how the Views hierarchy is arranged, and while this kind of host-proxy element is cool and convenient, I'd be worried that it would mess with that understanding.

You'd also have to add code to catch people having:
- More than one `<host>` element in a template
- Content _outside_ of the `<host>` element in a template.
- The `<host>` element is not at the root of the template.

**Comment by pkozlowski-opensource** [comment]
Yeh, right, probably having it as part of the `@View` annotation mixed up with the regular template is not ideal (especially if we want to have multiple views for one component). Still it feels strange to use different syntax (even more - JS vs. HTML!) to express the same concepts for regular elements vs. host elements...

**Comment by ajoslin** [comment]
In Ionic, we want to decide on angular bootstrap whether the platform is ios/android/etc, and set an attribute matching the platform on each component (for CSS).

We'll create a custom annotation that gets the `platform` we define on bootstrap and sets it has a `hostAttribute`.

**Comment by mhevery** [comment]
@pkozlowski-opensource I am open to other syntaxes. But I think it would be a mistake to have the host part of the `@View`, since as @jelbourn points out it is the exact opposite of the `View`. Do you have suggestion which does not involve `View`?

**Comment by tbosch** [comment]
Also think about DynamicComponents which have no View but might want to
control host properties as well ..

**Comment by pkozlowski-opensource** [comment]
@mhevery @jelbourn putting new syntax discussion aside for a sec, I was wondering if we really want to introduce new concept of `hostAttributes` knowing that the use-case can be already covered by `hostProperties` like so:

```javascript
@Component({
  selector: 'md-button',
  hostProperties: {
    '"button"': 'attr.role'
  }
})
@View(...)
class MdButton {}
```
See: http://plnkr.co/edit/sNNMlLLWZSuhagJCxAJ0?p=preview

IMO we shouldn't introduce new concept here, as `hostProperties` already handles the syntax as we've got in templates, works with dynamic attributes etc.

WDYT?

**Comment by pkozlowski-opensource** [comment]
@ajoslin I didn't quite get your last comment, I'm afraid.... Anyway, could you please check if the `hostProperties`, as described above, would work for your use-case?

**Comment by mhevery** [comment]
@pkozlowski-opensource `hostProperties` are runtime settings, where as `hostAttributes` can be set statically at compile-time. So while you could acchieve `hostAttributes` with `hostPropertios` as described, it would not perform as well.

**Comment by pkozlowski-opensource** [comment]
@mhevery OK, right, got it. Sent #1633

**Comment by naomiblack** [comment]
@mhevery is this closed? it looks like it should be.

**Comment by pkozlowski-opensource** [comment]
@naomiblack there is a PR for this that got reviewed, needs minor clean up, will land it in few hours and close this issue.
