### ISSUE TITLE
url query parameters changing in chrome angular2

### ISSUE THREAD

**Issue by nikhilrayaprolu** [angular/angular#14024]
I have my url as https://nikhilrayaprolu.github.io/susper.com/search;query=d;verify=false;nav=filetype%2Cprotocol%2Chosts%2Cauthors%2Ccollections%2Cnamespace%2Ctopics%2Cdate;startRecord=0;indexof=off;meanCount=5;resource=global;prefermaskfilter=%22%22;maximumRecords=10;timezoneOffset=-330

which is being changed to https://nikhilrayaprolu.github.io/search?query=d&Enter on chrome , but there is no such change in firefox . why is chrome doing this?How do I fix it?

I have my application in angular2 and below is the code for my routes
```

const appRoutes: Routes = [
{path: 'search', component: ResultsComponent},
{path: '', component: IndexComponent},
];
```

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource support request
