### ISSUE TITLE
A little uncertainty with documentation on router's routerLinkActive

### ISSUE THREAD

**Issue by Vohidjon** [angular/angular#14023]
I'm submitting a possible documentation error on the [docs page](https://angular.io/docs/ts/latest/guide/router.html) of angular.io;
It says '**You can also set the RouterLinkActive directive to a string of classes such as `[routerLinkActive]="active fluffy"` or bind it to a component property that returns such a string**'
As i know `[routerLinkActive]` takes property in the component and it should be `[routerLinkActive]="'active fluffy'"` (literal variable)

I did not know where to report such issues. So, I had to report it here.

**Comment by DzmitryShylovich** [comment]
> I did not know where to report such issues.

https://github.com/angular/angular.io/issues

**Comment by Vohidjon** [comment]
Thanks @DzmitryShylovich . Closing here and probably opening there
