### ISSUE TITLE
Using CoreModule.forRoot with Compiler does not bring in dependent providers

### ISSUE THREAD

**Issue by travist** [angular/angular#14022]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Anytime you dynamically create a module using ```Compiler```, and include imports for a dependent module that implements the ```CoreModule.forRoot```, the providers for that dependent module are not brought in and you receive errors that `No providers found`.

**Expected behavior**
Anytime `ComponentFactory` is used to dynamically create a new component and that uses `imports` for a module that implements `forRoot` which provides `providers`. Those `providers` should also be included in the dependency chain.

**Minimal reproduction of the problem with instructions**
This can be seen by using the ```ng2-bootstrap``` ```DatepickerModule```.  This module implements ```forRoot``` as follows.

https://github.com/valor-software/ng2-bootstrap/blob/development/src/datepicker/datepicker.module.ts#L22

Notice the ```providers``` declaration for ```DatepickerConfig```

When I dynamically create a module using ```Compiler```, and then render the element that was created, it complains with the following.

```
No provider for DatepickerConfig!
```

I am thinking that there is an issue with ```Compiler``` where it ignores the ```providers``` declaration.

The following code illustrates where this would be a problem.

```
import { NgModule, Compiler, Component, ComponentFactory, ViewContainerRef, ViewChild } from '@angular/core';
let find = require('lodash/find');
import { DatepickerModule } from 'ng2-bootstrap';
export class FormioElement implements OnInit {
  @ViewChild('formioElement', { read: ViewContainerRef }) element: ViewContainerRef;
  constructor(private compiler: Compiler) {}
  ngOnInit() {
    // These are really provided from a config, but put inline here for demonstration.
    @NgModule({
      imports: [
        DatepickerModule.forRoot()
      ]
    })
    class DynamicComponentModule {}

    this.compiler.compileModuleAndAllComponentsAsync(DynamicComponentModule).then((moduleWithFactories) => {
      let factory = find(moduleWithFactories.componentFactories, {selector: 'formio-textfield'});

      // Dynamically create an element.
      // The bug is that the "providers" required by the DatepickerModule are not available!
      let cmpRef = this.element.createComponent<FormioElement>(factory);
    });
  }
}
``` 

**What is the motivation / use case for changing the behavior?**
I would expect that the providers that are supplied by the dependency would get pulled in when dynamically creating a module.

**Please tell us about your environment:**
MacOSX, WebStorm

* **Angular version:** 2.0.X
2.4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
6.9.4

**Comment by DzmitryShylovich** [comment]
Pls add a small demo on Plunkr (without ng2-b)

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by meriturva** [comment]
@travist have you found a solution? you are right, when we use compileModuleAndAllComponentsAsync providers are not considered from ngModule.

@pkozlowski-opensource the issue is well written and it exits. tell me if you need info.
Issue has to be open in my opinion!

**Comment by travist** [comment]
I have not yet found a solution, and have not had the chance to develop a "simple" example. I ran into the problem since Form.io has an Angular 2 renderer that allows for dynamic "templates". Here is the Bootstrap template where I am including ```DatepickerModule``` and ```TimepickerModule``` https://github.com/formio/ng2-formio/blob/master/src/formio.ts#L13. 

This dynamically gets compiled at runtime here https://github.com/formio/ng2-formio/blob/master/src/components/components.ts#L69.  

The problem is if I only include the ```DatepickerModule ``` and ```TimepickerModule``` just within this template, I get this error. The ONLY way I could get through it for now is the ugly "patch" where the core engine includes those modules (even though the core should not care about the template). https://github.com/formio/ng2-formio/blob/master/src/formio.ts#L20

You can reproduce this issue with the Form.io [ng2-formio](https://github.com/formio/ng2-formio) renderer as follows...

### Working
```js
import { FormioModule } from 'ng2-formio';
@NgModule({
    imports: [ BrowserModule, ReactiveFormsModule, FormioModule ],
    declarations: [ AppComponent ],
    bootstrap: [ AppComponent ]
})
export class AppModule { }
```
```html
<formio src="https://examples.form.io/datetime"></formio>
```

### Not working
Remove the following from the core renderer includes. https://github.com/formio/ng2-formio/blob/master/src/formio.ts#L20. These should be included along with the template declaration @ https://github.com/formio/ng2-formio/blob/master/src/templates/bootstrap.templates.tpl.ts#L83 but because of this bug, they do not causing this error.

Now refresh your page and you will see the problem.

I agree, this should be fixed.

**Comment by DzmitryShylovich** [comment]
@travist pls reproduce on plunkr without any 3rd party libs and file a new issue

**Comment by meriturva** [comment]
@DzmitryShylovich i have tried to reproduce problem here: 

https://embed.plnkr.co/RPTFmGMLFzHRmvIxlUGU/

@travist check plnkr please.

Main problem is that if i set provider directly on DynamicComponent then DynamicService is correctly injects, when i move provider on NgModule DynamicService is not injected.

I just say sorry if i made few mistakes here....it is really late!

**Comment by DzmitryShylovich** [comment]
@meriturva it doesn't work because you don't use module injector http://prntscr.com/e5dcwq
Only component's injector + `this.inj`.

**Comment by DzmitryShylovich** [comment]
If you want to provide the service in the module then you need to create that module and retrieve its injector

**Comment by meriturva** [comment]
@DzmitryShylovich thanks for explanation but i have to ask you a sample about how to get injector from a `ModuleWithComponentFactories` because i don't find any working solution here.

Secondly am i right to say that if i compile dynamically a module i just would like that it works without taking care about providers meta property?

**Comment by meriturva** [comment]
Hi @travist did you find a way to get injector from a module durning call `compileModuleAndAllComponentsAsync` before create the final component?

**Comment by meriturva** [comment]
Here i found a work around using injector from module as described by @DzmitryShylovich 

https://plnkr.co/edit/TynXt76IukxrzTarQKSs

is it correct?

**Comment by DzmitryShylovich** [comment]
> this.ngInjector = moduleWithComponentFactory.ngModuleFactory.create(this.inj).injector;

yeah, this will give a module injector.

**Comment by arunsn43** [comment]
Thank you. This work around helped! I do have a similar scenario where the providers are being lost while resolving the Dynamic Modules.   The injector in ReflectiveInjector.resolveAndCreate([], injector$) is slightly misleading.
