### ISSUE TITLE
The selector “ng-component” did not match any elements error

### ISSUE THREAD

**Issue by achieverprince** [angular/angular#14026]
**I'm submitting a bug**

Related: https://github.com/angular/angular/issues/1662#issuecomment-98928582

**Current behavior**
App works fine while running with systemjs directly. When i tried to build globals.bundle.js and app.bundle.js using webpack and deploy i get this error.

`EXCEPTION: Error in :0:0 caused by: The selector "ng-component" did not match any elements`

**Expected behavior**
Angujar2 should work with webpack as show in the demo
https://angular.io/docs/ts/latest/guide/router.html
https://angular.io/docs/ts/latest/guide/webpack.html

**Minimal reproduction of the problem with instructions**
1.
Follow the guide and setup angular2 with webpack as below
https://angular.io/docs/ts/latest/guide/webpack.html
2.
Now replace component selector with router
https://angular.io/docs/ts/latest/guide/router.html
3.
Now build with webpack and deploy and run
4.
You will get this error (While i tested with systemjs before using webpack, there was no issue)
`EXCEPTION: Error in :0:0 caused by: The selector "ng-component" did not match any elements`

**Plunkr**
https://plnkr.co/edit/AfYGsdHpIVnVnuF7BCUJ?p=preview
Though it happens only in webpack build in my local environment, i can reproduce this through plnkr

**Stackoverflow**:
http://stackoverflow.com/questions/41743128/the-selector-ng-component-did-not-match-any-elements-error

**Please tell us about your environment:**

* **Angular version:** 2.4.4

* **Browser:** [all ]
 
* **Language:** [TypeScript 2.0.10]

* **Node (for AoT issues):** `node --version` =   6.9.4

**Comment by DzmitryShylovich** [comment]
Pls provide a repro on Plunkr

**Comment by achieverprince** [comment]
Even though it was only occurring in webpack in my local environment, while i was trying to create a plunkr i got the same issue.
Please have a look at 
https://plnkr.co/edit/AfYGsdHpIVnVnuF7BCUJ?p=preview

**Comment by achieverprince** [comment]
Got it fixed with help of @yurzui from stackoverflow
now i understand that i need to have a selector for bootstrap component or use

```
<body>
    <ng-component></ng-component>
  </body>
```
instead of

```
<body>
<router-outlet></router-outlet>
</body>
```
How ever it is stange why it would work if i am using systemjs and doestn't work with plunkr or webpack.
thanks to @Günter Zöchbauer and @yurzui
Fixed plunkr  https://plnkr.co/edit/xhAyEI600OpR3oUsQ9D3?p=preview

**Comment by bbottema** [comment]
@achieverprince which stackoverflow answer was it?

**Comment by anisanwesley** [comment]
@bbottema https://stackoverflow.com/questions/41743128/the-selector-ng-component-did-not-match-any-elements-error
