### ISSUE TITLE
Unable to access a components instance via a local variable

### ISSUE THREAD

**Issue by mattlewis92** [angular/angular#14038]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Accessing a local components instance inside of a dynamically added component doesn't work. i.e. I load a component inside of an ngSwitch and then I want to reference the components instance to a local variable. However this doesn't seem to work.

**Expected behavior**

You should be able to access any local components instance.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/jKpVgdErsJc7VwVexIvq?p=preview
Click the "Access foo" button - you'll see the inner instance of the foo component logged, but outside of the ngSwitch it cannot be accessed.

**What is the motivation / use case for changing the behavior?**

I'm guessing this is caused by the way *ngSwitchCase desugar's to a template tag, however it's not very obvious that this is the case by looking at the html structure. I'd expect to be able to create a local variable and reference it anywhere else in the components template.

**Please tell us about your environment:**

N/A

* **Angular version:** 2.0.X

2.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/13974

**Comment by mattlewis92** [comment]
Thanks @DzmitryShylovich, I'll close this in favour of that issue.
