### ISSUE TITLE
Angular2 testing setup not working. 

### ISSUE THREAD

**Issue by aravindfz** [angular/angular#14032]
**I'm submitting a bug report...**  

I navigated to the [Testing Guide](https://angular.io/docs/ts/latest/testing/#!#setup) of angular. When I clicked on the [Setup Instructions](https://angular.io/docs/ts/latest/testing/setup.html) with a motive to create my first testing application I find 404 error which seems to be strange. 
**Current behavior**
**Getting 404 not found**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls report docs issue on https://github.com/angular/angular.io/issues

**Comment by pkozlowski-opensource** [comment]
What @DzmitryShylovich have said...
