### ISSUE TITLE
Modules are loaded twice

### ISSUE THREAD

**Issue by ASmeha** [angular/angular#14030]
**I'm submitting a ...**
[x] bug report 

Modules are loaded twice.
• angular version : 2.4.4 (latest)
• angular/router : 3.4.4 (latest)

**Reproduction of the problem**
https://github.com/ASmeha/angular2-sample
In this sample modules are loaded when changing routes .

**Example in the repo for the issue** :  
Logs in modules class constructor are displayed twice.

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/12869

**Comment by ASmeha** [comment]
Thank you @DzmitryShylovich

**Comment by ASmeha** [comment]
Closing this as duplicate .
