### ISSUE TITLE
Builtin Authentication Module

### ISSUE THREAD

**Issue by un33k** [angular/angular#1403]
Coming from the Django side, it is nice to fall back on a default authentication module that is included as it gets all the updates and patches from the core contributors.

With the new router, it would be so great to have an option to just pull the default authentication in and setup the route & customize it further.

Handle:
1. Login
2. Logout
3. CSRF
4. Authorization (dict of some sort)

If a route requires auth, then it gets redirected to the login page.

**Comment by un33k** [comment]
Minimally, the angular core team's take on Auth in a form of a sample app would be fantastic.

**Comment by mhevery** [comment]
We are leaving this to the community for now.

**Comment by un33k** [comment]
Fair enough.
