### ISSUE TITLE
When canLoad returns false on initial page load, the routes aren't recalculated.

### ISSUE THREAD

**Issue by dietergeerts** [angular/angular#14031]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When canLoad returns false, the url is being reset, but the route that goes with it isn't being called.

**Expected behavior**
When canLoad returns false, the url should be reset, AND the route that goes with it should be called.

**Minimal reproduction of the problem with instructions**
This is my root route setup:
```javascript
RouterModule.forRoot([
            {
                canLoad: [AuthGuard],
                loadChildren: './dashboard/dashboard.module#DashboardModule',
                path: 'dashboard'
            },
            {
                loadChildren: './login/login.module#LoginModule',
                path: 'login'
            },
            {
                path: '',
                pathMatch: 'full',
                redirectTo: '/login'
            },
            {
                path: '**',
                pathMatch: 'full',
                redirectTo: '/login'
            }
        ])
```

Steps taken:
- I type in the url `myServer/dashboard`
- The canLoad guard returns false
- The route is being reset to `myServer`
- Nothing else happens.

**What is the motivation / use case for changing the behavior?**
To fix this now, we need to add a router.navigate step inside the guards, but it would be better if the route that is being reset, is also excecuted, and so in the above route setup, the redirect to login will happen instead.

* **Angular version:** 2.4.4

**Comment by DzmitryShylovich** [comment]
Pls add a small repro on Plunkr

**Comment by DzmitryShylovich** [comment]
@dietergeerts any updates? Otherwise we will close it as it's not actionable

**Comment by impankratov** [comment]
@DzmitryShylovich here's example (facing the same problem):

1. open https://angular-gitter-zjsfc9.stackblitz.io/ -> `info.component` will be loaded in router outlet
2. then try to open https://angular-gitter-zjsfc9.stackblitz.io/lazy -> `auth.guard` will prevent `lazy.module` from loading and we will end up on https://angular-gitter-zjsfc9.stackblitz.io/. That's good, BUT in this case router outlet will be empty (i.e. no `info.component`).

If I change use `canActivate`  instead of `canLoad` then in case 2 `info.component` will be loaded as expected.

My use case for `canLoad` is that Angular could check the route before even trying to load lazy module and waste bandwith/time.

**Comment by impankratov** [comment]
@vicb can this be re-opened?

**Comment by victorschinaider** [comment]
I'm having the same problem here. Angular 6.0.9. Same thing in #13530, but i didn't found any solution.

**Comment by perrosen** [comment]
@impankratov Does not seem that canActivate fixes it in your example unless I'm doing something wrong. Running into same issue in my Angular 6 app with canActivate so was keen to see what you did differently :D

#13530 only provides a sub optimal solution which is to manually redirect users in the guard which seems silly.

**Comment by impankratov** [comment]
@perrosen even though I've forgot to add that you should also
>(and implement `canLoad` method in `auth.guard`)

trying this now doesn't seem to work at all. So I'm afraid #13530 will be the way to go for now (completely agree that it's not the best way).
