### ISSUE TITLE
Add sample repos or plunkers to docs

### ISSUE THREAD

**Issue by robianmcd** [angular/angular#14042]
**I'm submitting a ...**
```
[X] feature request
```

**Current behavior**
Many of the documentation articles in the advanced and cookbook section of angular.io/docs describe how to build a particular angular app but do not give a sample repository or plunker that demonstrates that app

**Desired behavior**
Documentation articles would link to a repo or plunker similar to the ones linked to in the quick start documentation. e.g.
https://github.com/angular/quickstart
 https://angular.io/resources/live-examples/quickstart/ts/eplnkr.html

**What is the motivation / use case for changing the behavior?**
This would make it much easier to try out the concepts being described in the documentation

**Comment by DzmitryShylovich** [comment]
Pls re-open on https://github.com/angular/angular.io/issues

**Comment by robianmcd** [comment]
Move the issue to https://github.com/angular/angular.io/issues/3126
