### ISSUE TITLE
(AOT) Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda

### ISSUE THREAD

**Issue by fkolar** [angular/angular#14048]
##Environemtn:
ngular-cli: 1.0.0-beta.26
node: 4.6.0
os: darwin x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

##Problem
While running node_modules/.bin/ngc -p src/tsconfig.json, i am getting following error. 
Is this something on my side or Angular side -> as it does not say much about the error. 

```
Failed on type {"filePath":"/AngularMetaUI/node_modules/@angular/compiler/src/directive_resolver.d.ts","name":"DirectiveResolver","members":[]} with error Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 15:13 in the original .ts file), resolving symbol UNINITIALIZED in /AngularMetaUI/node_modules/@angular/core/src/change_detection/change_detection_util.d.ts, resolving symbol ___core_private__ in /AngularMetaUI/node_modules/@angular/core/src/core_private_export.d.ts, resolving symbol ___core_private__ in /AngularMetaUI/node_modules/@angular/core/src/core.d.ts, resolving symbol ___core_private__ in /AngularMetaUI/node_modules/@angular/core/index.d.ts, resolving symbol ReflectorReader in /AngularMetaUI/node_modules/@angular/compiler/src/private_import_core.d.ts, resolving symbol DirectiveResolver in /AngularMetaUI/node_modules/@angular/compiler/src/directive_resolver.d.ts
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 15:13 in the original .ts file), resolving symbol UNINITIALIZED in /AngularMetaUI/node_modules/@angular/core/src/change_detection/change_detection_util.d.ts, resolving symbol ___core_private__ in /AngularMetaUI/node_modules/@angular/core/src/core_private_export.d.ts, resolving symbol ___core_private__ in /AngularMetaUI/node_modules/@angular/core/src/core.d.ts, resolving symbol ___core_private__ in /AngularMetaUI/node_modules/@angular/core/index.d.ts, resolving symbol ReflectorReader in /AngularMetaUI/node_modules/@angular/compiler/src/private_import_core.d.ts, resolving symbol DirectiveResolver in /AngularMetaUI/node_modules/@angular/compiler/src/directive_resolver.d.ts
    at positionalError (/AngularMetaUI/node_modules/@angular/compiler/bundles/compiler.umd.js:25730:39)
    at simplifyInContext (/AngularMetaUI/node_modules/@angular/compiler/bundles/compiler.umd.js:25567:31)
    at StaticReflector.simplify (/AngularMetaUI/node_modules/@angular/compiler/bundles/compiler.umd.js:25581:17)
    at StaticReflector.parameters (/AngularMetaUI/node_modules/@angular/compiler/bundles/compiler.umd.js:25135:69)
    at CompileMetadataResolver._getDependenciesMetadata (/AngularMetaUI/node_modules/@angular/compiler/bundles/compiler.umd.js:18392:75)
    at CompileMetadataResolver._getTypeMetadata (/AngularMetaUI/node_modules/@angular/compiler/bundles/compiler.umd.js:18319:30)
    at CompileMetadataResolver._getInjectableMetadata (/AngularMetaUI/node_modules/@angular/compiler/bundles/compiler.umd.js:18307:25)
    at CompileMetadataResolver.getProviderMetadata (/AngularMetaUI/node_modules/@angular/compiler/bundles/compiler.umd.js:18549:44)
    at /AngularMetaUI/node_modules/@angular/compiler/bundles/compiler.umd.js:18507:53
    at Array.forEach (native)
Compilation failed
```

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/search?q=Error+encountered+resolving+symbol+values+statically.+Function+calls+are+not+supported&type=Issues&utf8=%E2%9C%93

**Comment by fkolar** [comment]
There are similar errors but for most of them I see direct reference to application code but this one jsut refers to angular core !!

Or are you trying to say that in 2.4.X its known issue and its currently broken?

**Comment by zoechi** [comment]
@fkolar any information about how to reproduce?

**Comment by fkolar** [comment]
Unfortunatelly not. The error is so general I cant even say where to look! So when I get time to disassemble my app to see what part is causing this or wait untill next version provide more specific errors logs

**Comment by DzmitryShylovich** [comment]
We don't need error logs. Pls provide a github repo with reproduction.

**Comment by fkolar** [comment]
Right!  As of now I do not have any public repo for our internal project. Will need to dissamble slowly my app to see which part of causing it OR link angular-master from local and put more console.log to static_reflector.ts to help me debug the area faster.

**Comment by DzmitryShylovich** [comment]
https://github.com/rangle/angular-2-aot-sandbox#current-status here you can find what is currently allowed/disallowed in aot

**Comment by fkolar** [comment]
Great. Let me look then!
Thank you, 
-FK

**Comment by fkolar** [comment]
I see a few areas already that could be wrong starting :
- using private modifiers, or using arrow fuctions for some ngModule initialization. 

Closing this issue to come back with something specific (if needed) after I go thru the all the AOT - current status and update my project accordingly !
