### ISSUE TITLE
Add NgModule support to  ngComponentOutlet

### ISSUE THREAD

**Issue by mhevery** [angular/angular#14043]
```
@Component({
  template: `
   <ng-container *ngComponentOutlet="child?.component; ngModule: child?.moduleFactory"></ng-container>
`
}) 
class MyApp {
   child: {component: Type<any>, moduleFactory: NgModuleFactory<T> };
}
```

**Comment by DzmitryShylovich** [comment]
@mhevery what is the use case? A component must be a part of a module anyway `ngc` will throw an error during compilation. So what's the purpose of `moduleFactory` arg? We will be able to create a component in the context of a different module?
Plus it's not user friendly syntax. In `jit` is have to be `NgModule` and it `aot` it have to be `NgModuleFactory`. We already faced s similar issue with router https://github.com/angular/angular/issues/14005 So we need to tool for automatic conversion.

**Comment by mhevery** [comment]
@DzmitryShylovich Let me clarify

1. yes Type can only be part of TypeFactory otherwise `ngc` would have an issue.
2. Both AoT and JIT should always behave same in the API, and this does not change that.
3. The change would allow the `ngComponentOutlet` to dynamically load a module into existence and then load a component from the that module. 
4. The use case is if someone wants to lazy load code, and then add the lazy loaded code into the page using `ngComponentOutlet`.

**Comment by DzmitryShylovich** [comment]
> Both AoT and JIT should always behave same in the API, and this does not change that.

but we don't have `NgModuleFactory` in jit, do we?

**Comment by mhevery** [comment]
> but we don't have NgModuleFactory in jit, do we?

Yes we do: https://angular.io/docs/ts/latest/api/core/index/Compiler-class.html

**Comment by DzmitryShylovich** [comment]
I've got it. Thx.
