### ISSUE TITLE
"Only void and foreign elements can be self closed " error in JIT compiler

### ISSUE THREAD

**Issue by Luftzig** [angular/angular#14054]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When trying to load my translated XLIFF file I get the following exception (using the JIT compiler):

```
ZoneAwareError {__zone_symbol__error: Error: Only void and foreign elements can be self closed "x" ("תרגום לבדיקה עם [ERROR ->]<x id="INTE…, __zone_symbol__stack: "Error: Only void and foreign elements can be self …teachers-site/vendor.bundle.js:37698:44) [<root>]", __zone_symbol__message: "Only void and foreign elements can be self closed …ERPOLATION"/>"): TranslationsHolderComponent@0:16"}
__zone_symbol__error
:
Error: Only void and foreign elements can be self closed "x" ("תרגום לבדיקה עם [ERROR ->]<x id="INTERPOLATION"/>"): TranslationsHolderComponent@0:16 at new Error (native) at TranslationBundle.get (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:106574:19) [<root>] at _Visitor._translateMessage (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:77286:61) [<root>] at _Visitor.visitElement (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:77178:45) [<root>] at Element.visit (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:27483:76) [<root>] at http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:77201:54 [<root>] at Array.forEach (native) [<root>] at _Visitor.visitElement (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:77200:24) [<root>] at Element.visit (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:27483:76) [<root>] at _Visitor.merge (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:77057:55) [<root>] at mergeTranslations (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:76991:20) [<root>] at I18NHtmlParser.parse (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:48120:115) [<root>] at TemplateParser.tryParse (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:37720:67) [<root>] at TemplateParser.parse (http://127.0.0.1:8000/static/teachers-site/vendor.bundle.js:37698:44) [<root>]
__zone_symbol__message
```

Notice the error saying 'Only void and foreign elements can be self closed "x"'.

**Expected behavior**

The compilation to succeed or at least get a meaningful error message.

**Minimal reproduction of the problem with instructions**

The trans-unit that is mentioned in the error is this one:
```
      <trans-unit datatype="html" id="728935803210085350c603a488adbc664d5287f6">
        <source>Translation with <x id="INTERPOLATION"/> in it</source>
        <target>תרגום לבדיקה עם &lt;x id=&quot;INTERPOLATION&quot;/&gt;</target>
        
      </trans-unit>
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.3

* **Browser:** [Chrome ]

 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
`<source>Translation with <x id="INTERPOLATION"></x> in it</source>`

**Comment by Luftzig** [comment]
OK, this seems to work.
But, since Angular had generated the original `<x id="..."/>` tag I expect it to be able to parse it. If that's a problem, then I expect Angular to generate the tag not self closed.

**Comment by vicb** [comment]
That's a bug in the serializer.

**Comment by vicb** [comment]
nope actually this is an issue with your translation
`<target>תרגום לבדיקה עם &lt;x id=&quot;INTERPOLATION&quot;/&gt;</target>`
should be
`<target>תרגום לבדיקה עם <x id="INTERPOLATION"/></target>`

Otherwise the placeholder is interpreted as text.

**Comment by marcosvrs** [comment]
Same here:

> ERROR in Only void and foreign elements can be self closed "x" ("[ERROR ->]<x id="START_TAG_STRONG" ctype="x-strong"/>Ocorreu um erro!<x id="CLOSE_TAG_STRONG" ctype="x-strong"/"): ng:///c:/Apps/marcosvrs.github.io/src/app/core/contact/contact.component.html@0:0
Only void and foreign elements can be self closed "x" ("<x id="START_TAG_STRONG" ctype="x-strong"/>Ocorreu um erro![ERROR ->]<x id="CLOSE_TAG_STRONG" ctype="x-strong"/> Favor tente novamente."): ng:///c:/Apps/marcosvrs.github.io/src/app/core/contact/contact.component.html@0:59
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'c:\Apps\marcosvrs.github.io\src'
 @ ./src/main.ts 4:0-74
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

`<trans-unit id="157209cfaee0bbd21e14507fd8fa19eb792c4b3e" datatype="html">
        <source><x id="START_TAG_STRONG" ctype="x-strong"/>An error occurred!<x id="CLOSE_TAG_STRONG" ctype="x-strong"/> Please try again.</source>
        <target>&lt;x id="START_TAG_STRONG" ctype="x-strong"/&gt;Ocorreu um erro!&lt;x id="CLOSE_TAG_STRONG" ctype="x-strong"/&gt; Favor tente novamente.</target>
        <context-group purpose="location">
          <context context-type="sourcefile">C:/Apps/marcosvrs.github.io/src/app/core/contact/contact.component.ts</context>
          <context context-type="linenumber">30</context>
        </context-group>
      </trans-unit>`

**Please tell us about your environment:**

- **Angular version:** 4.1.2
- **Browser:** [Firefox]
- **Language:** [TypeScript]
- **Node (for AoT issues):** node --version = v7.7.4
