### ISSUE TITLE
CanActivate runs always, even when CanDeactivate on target is not yet resolved to true

### ISSUE THREAD

**Issue by dzolnjan** [angular/angular#14059]
If I have two routes, one with CanDeactivate and second with CanActivate setup like this:

```
{
    path: '',
    component: EditorComponent,
    canDeactivate: [EditorGuard]
},
    path: 'campaign/:campaignId'
    component: CampaignComponent
    canActivate: [CampaignGuard],
}
```

1) Navigating from CampaignEditorComponent to CampaignDetailsComponent 
2) CampaignEditorComponent is not yet resolved to true (returning `Observable<boolean>`)

 then CampaignGuards CanActivate method will run anyway.

Is this behaviour by design?  

I was expecting that router will not try to run any future 'activations' before any current 'deactivations' are resolved to true.

**Update**: 
added plunker example
https://plnkr.co/edit/wjkIf33huhwo1HIMjen1?p=preview

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr with repro

**Comment by dzolnjan** [comment]
@DzmitryShylovich  here is simple repro https://plnkr.co/edit/wjkIf33huhwo1HIMjen1?p=preview

**Comment by vitorrd** [comment]
This is a very serious issue. You can't compose guards in any way because of this. Isn't this of the highest priority?
