### ISSUE TITLE
Component With RouterLinks ?

### ISSUE THREAD

**Issue by fearless23** [angular/angular#14058]
I have a Shared Module which is imported in 2 Lazy Loaded Modules viz. Projects Module and Store Module

app.routing.ts file has Root Routes declarations

Contents of Menu Component:  It contains app-wide links to major sections of app like projects, store... 

I want menu to be part of lazy loaded modules only.

**This Works:** 
Used selector <app-menu> in root Component and all routes work fine as expected....but i don`t want menu to be shown everywhere.

**This does not work:**
Moved Menu Component to the shared Module (imported, declared and exported), and shared Module is imported to Projects Module. Now i can use <app-menu> selector to show menu, which works fine. 
But the links don`t work. App works fine even routes work by typing in browser, but not by clicking in menu component links.. 
_Note: Internal links in projects Module and Store Module work fine._

**This does not work too ::**
imported app.routing.ts in shared module instead of root.app.module.
This throw an error --> Cant find projects Module
 _Could not resolve "app/projects/projects.module" from "I:/Code/week-tweak/src/app/app.routing.ts"._

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource support request
