### ISSUE TITLE
Named outlet not registered dynamically

### ISSUE THREAD

**Issue by Sakuto** [angular/angular#14051]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm trying to create a named outlet inside one of my component, but it's not dynamically registered. Error: Cannot find the outlet tabs to load 'TabsDeaComponent' More information here: http://stackoverflow.com/questions/41781753/named-outlet-not-registered

**Expected behavior**
The outlet should be registered and not create an issue.

**Minimal reproduction of the problem with instructions**
https://github.com/Sakuto/TabsPOC
http://plnkr.co/edit/P4q9yib0x9KtE15AQZAO?p=preview

**What is the motivation / use case for changing the behavior?**
Just get it work easily, not a true motivation.

**Please tell us about your environment:**
Windows 10, VS Code, AngularCLI 1.0.25, 

* **Angular version:** 2.0.X

Angular 2.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Every browser
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 

* **Node (for AoT issues):** `node --version` =   
Not related, but 7.2.0

**Comment by zoechi** [comment]
I don't think it's about the outlet not being registered, rather the `outlet` parameter in route configs not working. Perhaps it's because there is no unnamed router-outlet but AFAIR this requirement was removed recently (not sure).
Can you please provide a Plunker that allows to reproduce?

**Comment by Sakuto** [comment]
Added the plunkr: http://plnkr.co/edit/P4q9yib0x9KtE15AQZAO?p=preview

Also, there is one unnamed router-outlet on the application.

**Comment by brandonroberts** [comment]
The router renders components synchronously, so router outlets have to be defined at that time. Your named outlet does not need to be inside your route component because its not a parent. Just move the named outlet into your AppComponent template next to your unnamed outlet.

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
