### ISSUE TITLE
input performance issue with large arrays

### ISSUE THREAD

**Issue by thibaultsavary** [angular/angular#14056]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Binding a large array to an input of a component causes serious performance issue.
 `<virtual-list [items]="myFourBillionItemsArray">`
This is not the case when using a function
 `<virtual-list [getItemsFn]="myFnReturningAFourBillionItemsArray">`

**Expected behavior**
Input should be as performant as other way of getting data, eg. via a service
`this.items = this.virtualListService.getItems();`
```
getItem() {
    return Array.from(Array(40000000).keys())
}
```

**Minimal reproduction of the problem with instructions**
Take any component that would visually suffer from poor performance, add an input to it, bind an array of 1M+ elements to the input. See for yourself. 

In my case I'm building a virtual list;
Using a service the component is working perfectly with a 4 billion items array.
Using an Input the component starts to be noticeably unresponsive with a 500 thousands items array.
I've already tried to disable the change detector and triggering it after calculations using `cdr.detectChanges()` but still, no noticeable improvements.

I would be interested to learn what is the cause behind the slowness of `Input()`.

**What is the motivation / use case for changing the behavior?**
Performance

**Please tell us about your environment:**
Windows 10,

* **Angular version:** 
2.4

**Comment by DzmitryShylovich** [comment]
Pls add a repro on Plunkr

**Comment by thibaultsavary** [comment]
Sorry for the late response.

Here is the first plunker with an Input providing a 5M number[];
http://plnkr.co/edit/4KqZ7rjGgC96FioCayxK?p=preview

Here is the second plunker with the constructor providing a 5M number[].
I didn't created a service but basically the performance is very close to this example with the array created inside the constructor, maybe less than 1ms slower per slice.
http://plnkr.co/edit/LC2BMujWmYNXdpmlYSno?p=preview

As you can see the data provided via Input is weirdly very very slow.

**Comment by DzmitryShylovich** [comment]
My guess is that angular uses `IterableDiffer` on inputs. And every time your scroll, change detection is triggered and angular traverses 5m array again and again looking for changes.

**Comment by thibaultsavary** [comment]
To be honest I have no idea what's going on there.
Even with `OnPush` `ChangeDetectionStrategy` there's no noticeable change, even detaching the `ChangeDetectionRef ` from the component doesn't help.
But yeah there seems to be an issue with the Input, because even if the rendered items are sliced from an array provided by the constructor, the simple fact of binding a large array to an `Input` causes this performance issue, even if the value isn't accessed/mutated/re-assigned.

**Comment by DzmitryShylovich** [comment]
> Even with OnPush ChangeDetectionStrategy there's no noticeable change, even detaching the ChangeDetectionRef from the component doesn't help.

yeah, tried that too

**Comment by DzmitryShylovich** [comment]
It's the reflection attributes that get added to the DOM in non-prod mode. You need to enable prod mode: http://plnkr.co/edit/4JKp6ZdwgZazdF7Ri7Tu?p=preview

Related issue https://github.com/angular/angular/issues/9707

**Comment by thibaultsavary** [comment]
Oh my... I didn't thought about this.
Thank you for your help.
