### ISSUE TITLE
Using structural directive on `ng-content` in dev mode leaks DOM nodes

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#14061]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using directive like `*ngIf` on `ng-content` provides DOM Nodes leaks

**Expected behavior**
Rise error on adding this directives on `ng-content` to prevent unexpected leaks.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/jJMi8d6fdyQ8pXAFSMzP?p=preview
start Timeline record, click Toggle list 10-20 times than collect garbage and view Memory graphs
![](http://storage6.static.itmages.com/i/17/0122/h_1485123229_8337144_d2871ee2e6.png)

**What is the motivation / use case for changing the behavior?**
`ng-content` is undocumented and unclear thing that results in many issues. Even adding this case to documentation will not be clear, it's simple to forgot such things and try to use it like ng1 `ng-transclude`. So compiler should throw an error for this case to prevent unsafe usage.

* **Angular version:** 2.4.4

**Comment by tsvetomir** [comment]
Switching to production mode [seems to solve this](http://plnkr.co/edit/WLvigy8m6ROw3M4ojFir?p=preview). Perhaps it's limited to development mode only, can you confirm?

**Comment by artaommahe** [comment]
@tsvetomir yep, looks like this affects only dev mode

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource do you think we should fix it in dev mode?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource I think it can be closed as it does work as expected in prod mode

**Comment by artaommahe** [comment]
@DzmitryShylovich hm, but this still provides leaks in dev mode that wastes time on finding why and make ir difficult to find real leaks..

**Comment by DzmitryShylovich** [comment]
anyway I don't think it makes much sense to find memory licks in dev mode.

**Comment by DaveMBush** [comment]
Wait!  What?  "It doesn't make sense to find memory leaks in dev mode" ????

It may not make sense to you, but it makes a lot of sense to me.

First, dev mode is where most of us do most of our development.  We have an expectation that they only difference between dev and prod is that we have a better ability to debug our code.

Second, if the application has a memory leak in dev mode that it doesn't have prod mode, what's to say that something else doesn't work the same way?  Something we would all consider more critical.  Like rendering.

Third, after spending two years to release this product and 7 rounds of RCs where the interface changed quite a bit, NG2 currently has a reputation problem that this kind of bug, to say nothing of the attitude, doesn't help.  (Yes, yes, I understand why two years and 7RCs were necessary,, but not everyone does.  The point is, the reputation problem exist.)

**Comment by pkozlowski-opensource** [comment]
I believe that this one is fixed in Angular v9 running ivy
