### ISSUE TITLE
AOT build failed

### ISSUE THREAD

**Issue by arat3091** [angular/angular#14063]
AOT build get failed and i dont have any clue why it is failing.
I am using angular cli for the project

I have attached the package.json which we are using in the project.

Anyone has any clue ?

ERROR in Internal state: StaticSymbols in summaries can't have members! {"filePath":"C:/ankur/project/inni-front-end-client/node_modules/@angular/forms/src/validators.d.ts","name":"Validators"
,"members":["required"]}

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\ankur\project\inni-front-end-client\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
Module not found: Error: Can't resolve 'C:\ankur\project\inni-front-end-client\src\$$_gendir' in 'C:\ankur\project\inni-front-end-client\node_modules\@angular\core\src\linker'
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 71:15-36 87:15-102
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by arat3091** [comment]
{
  "name": "inni-front-end-client",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\" --project src/tsconfig.json --type-check && tslint \"e2e/**/*.ts\" --project e2e/tsconfig.json --type-check",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor",
    "postinstall": "node ./hooks/copy-hooks"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/flex-layout": "^2.0.0-beta.0",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.0",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@covalent/http": "^0.10.2",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/store": "^2.2.1",
    "@ngrx/store-devtools": "^3.2.2",
    "core-js": "^2.4.1",
    "fullcalendar": "^3.1.0",
    "md2": "0.0.13-1",
    "moment": "^2.17.1",
    "ng-formly": "^1.0.0-rc.0",
    "ng2-dnd": "^2.1.1",
    "ng2-translate": "^5.0.0",
    "primeng": "^1.1.4",
    "primeui": "^4.1.15",
    "reselect": "^2.5.4",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.26",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
}

**Comment by arvind-das** [comment]
i have same error : 

> node_modules/.bin/ngc -i tsconfig.i18-ao
t.json
Error: Internal state: StaticSymbols in summaries can't have members! {"filePath":"/home/neuron/Documents/typescrip
t_projects/kairosUI/node_modules/daypilot-pro-angular/daypilot-angular.min.d.ts","name":"DayPilot","members":["Angu
lar","Scheduler"]}
    at AotSummaryResolver._assertNoMembers (/home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angul
ar/compiler/bundles/compiler.umd.js:26300:23)
    at AotSummaryResolver.resolveSummary (/home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angular
/compiler/bundles/compiler.umd.js:26308:18)
    at CompileMetadataResolver._loadSummary (/home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angu
lar/compiler/bundles/compiler.umd.js:18032:70)
    at CompileMetadataResolver.getNgModuleSummary (/home/neuron/Documents/typescript_projects/kairosUI/node_modules
/@angular/compiler/bundles/compiler.umd.js:18226:56)
    at /home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angular/compiler/bundles/compiler.umd.js:1
8318:72
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/home/neuron/Documents/typescript_projects/kairosUI/node_module
s/@angular/compiler/bundles/compiler.umd.js:18313:53)
    at addNgModule (/home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angular/compiler/bundles/comp
iler.umd.js:25053:62)
    at /home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angular/compiler/bundles/compiler.umd.js:2
5064:18
    at Array.forEach (native)
Compilation failed


Any Ideas ?

Thanks!
