### ISSUE TITLE
componentFactoryResolver not working correctly its  confusing because in each documents new thing come out not specific due to lot of changes 

### ISSUE THREAD

**Issue by ashwinirajput** [angular/angular#14077]
## componentFactoryResolver not working
[http://plnkr.co/edit/P0spNzu8JbQad2aKACsX?p=preview](url)

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/HwJTUICo5zzLVEMXfcrg?p=preview

**Comment by ashwinirajput** [comment]
Thanku @DzmitryShylovich can we do it without function

**Comment by DzmitryShylovich** [comment]
This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ashwinirajput** [comment]
need help @DzmitryShylovich 
core.umd.js:3370 EXCEPTION: Error in ./AppComponent class AppComponent - inline template:26:12 caused by: Cannot read property 'createComponent' of undefined
ErrorHandler.handleError @ core.umd.js:3370
core.umd.js:3376 TypeError: Cannot read property 'createComponent' of undefined
