### ISSUE TITLE
Documentation for FormArray is not accurate

### ISSUE THREAD

**Issue by ashish173** [angular/angular#14075]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] Docs Update
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior/documentation**
For `[FormArray](https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L1101)` the doc says
```
@whatItDoes Tracks the value and validity state of an array of {@link FormControl} instances.
```

**Expected behavior/documentation**
```
@whatItDoes Tracks the value and validity state of an array of {@link FormControl}/{@FormGroup} instances.
```

**What is the motivation / use case for changing the behavior?**
As mentioned in the docs `FormArray` only can contain `FormControl` but It can also have `FormGroup`'s.  

```
For a simple relationship of 

Trip [FormGroup]
   --> Cities [FormArray] of [FormGroups]
     --> Places [FormArray] of [FormGroups]
        --> Images [FormArray] of [FormGroups]
   --> Cities
     --> Places
        --> Images 

(<FormArray>this.tripForm.controls['cities']).push(
    new FormGroup({
       id: new FormControl(id),
       name: new FormControl(name, Validators.required),
       country: new FormControl(country),
       places: places // places is again a FormArray of FormGroup's 
})
```
 
Since `FormArray`, `FormGroup` & `FormControl` all extend from `AbstractControl` so I guess a `FormArray` can have any of those.

Constructor for `FormArray` also shows how it expects `AbstractControl[]` which can be an array any of `FormGroup`, `FormControl` & `FormArray`.

```
constructor(public controls: AbstractControl[], validator: ValidatorFn = null,
      asyncValidator: AsyncValidatorFn = null) {
    .... // other not relevant code to this issue.
  }
```

I think we really need to update the docs in order for this be more clear on the angular.io website.

**Comment by Toxicable** [comment]
Please re open on https://github.com/angular/angular.io for docs issues
