### ISSUE TITLE
Style binding do not work on Safari

### ISSUE THREAD

**Issue by dolanmiu** [angular/angular#14078]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Styles do not get added if its binded with []. For example `[style.transform]=`. Problem only occours in Safari

**Expected behavior**

Expected it to work the same as the other browsers

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/qWNCm9ISXjK5Ce2w09by?p=preview

Look at this plunkr in Google Chrome and Safari. You will notice a difference.

**What is the motivation / use case for changing the behavior?**

Because its important that this works on all browsers for our company App.

**Please tell us about your environment:**

MacOS Sierra

* **Angular version:** 2.0.X

* **Browser:** Safari 10.0.2

 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment]
I believe you need to prefix it for Safari. But angular doesn;t support vendor prefixes in bindings.
There's a pending pr https://github.com/angular/angular/pull/12847

**Comment by dolanmiu** [comment]
Sorry, false alarm

I made a typo in the plunkr:
```js
    this.transformPos = this.sanitizer.bypassSecurityTrustStyle(`translate(100px, 100px`);
```

should be:
```js
    this.transformPos = this.sanitizer.bypassSecurityTrustStyle(`translate(100px, 100px)`);
```

Notice the missing bracket. Google Chrome intelligently works it out that there is a missing bracket, but Safari doesn't. After adding the bracket, it works fine on both 

Closing
