### ISSUE TITLE
:host-context does not account for global css rules that are applied to a parent component

### ISSUE THREAD

**Issue by gitnik** [angular/angular#14076]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When defining global CSS via `ViewEncapsulation.None` (for example in the top level app component), said CSS is not taken into account for the `:host-context()` selector

**Expected behavior**
In the specific reproduction I attached, I would expect the backgroundColor to be yellow.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/oJtPIY0HtkdazE8IDAc9?p=preview

* **Angular version:** 2.X

* **Browser:** all

**Comment by DzmitryShylovich** [comment]
To me it works as expected. Host element (`my-second-child`) doesn't have `red` class. Working example:
http://plnkr.co/edit/vizyDd1AfQrlKHCeFkev?p=preview

**Comment by gitnik** [comment]
Yours is a different use case. In mine, I'm applying a global css class (in the plunker `.red`) via `NgClass`.

**Comment by DzmitryShylovich** [comment]
> Yours is a different use case

mine? :) I just changed your code.
There's no `NgClass` in your plunkr. Probably you misunderstand how `:host-context()` works.

**Comment by gitnik** [comment]
I'm talking about my application, where I encountered this bug.

I've updated the plunker to show exactly what I'm doing: http://plnkr.co/edit/oJtPIY0HtkdazE8IDAc9?p=preview

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/guide/component-styles.html#!#-host-context
> Use the :host-context() pseudo-class selector. It works just like the function form of :host(). It looks for a CSS class in any ancestor of the component host element, all the way up to the document root. It's useful when combined with another selector.
In the following example, we apply a background-color style to all <h2> elements inside the component, only if some ancestor element has the CSS class theme-light.

in your case **host** element **doesn't** have `red` class http://prntscr.com/dzsal2

**Comment by gitnik** [comment]
> all the way up to the document root

I thought this would include global styles. If that's not the case, then how can I achieve what I'm trying to do?

**Comment by DzmitryShylovich** [comment]
> I thought this would include global styles

Don't see how it's relevant in your case tbh.

> If that's not the case, then how can I achieve what I'm trying to do?

You need to add `red` class to `my-second-child` (or change selector). For example like this http://plnkr.co/edit/x7dMpl8vk28XPbSOYoIz?p=preview

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource works as intended. can be closed

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich
