### ISSUE TITLE
AOT Compiler: Error resolving symbol statically with @types/mongodb package installed

### ISSUE THREAD

**Issue by Agamnentzar** [angular/angular#14086]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request
```

**Current behavior**

`ngc` closes with error if `@types/mongodb`, ([index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mongodb/index.d.ts)) package is installed but not imported. Removing the package directory from `node_modules` fixes the problem.

```
Error: Error encountered resolving symbol values statically. Could not resolve events relative to .../node_modules/@types/mongodb/index.d.ts., resolving symbol Db in .../node_modules/@types/mongodb/index.d.ts
    at simplifyInContext (...\node_modules\@angular\compiler\bundles\compiler.umd.js:25569:27)
    at StaticReflector.simplify (...\node_modules\@angular\compiler\bundles\compiler.umd.js:25581:17)
    at StaticReflector.annotations (...\node_modules\@angular\compiler\bundles\compiler.umd.js:25073:84)
    at NgModuleResolver.resolve (...\node_modules\@angular\compiler\bundles\compiler.umd.js:17557:86)
    at CompileMetadataResolver.getNgModuleMetadata (...\node_modules\@angular\compiler\bundles\compiler.umd.js:18058:64)
    at addNgModule (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24839:62)
    at ...\node_modules\@angular\compiler\bundles\compiler.umd.js:24850:18
    at Array.forEach (native)
    at _createNgModules (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24849:30)
    at analyzeNgModules (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24724:18)
```

**Expected behavior**

AOT Compilation should not fail when `@types/mongodb` package is installed.

**Minimal reproduction of the problem with instructions**
Install `@types/mongodb` package in any working angular 2 project and run `ngc` tool

**What is the motivation / use case for changing the behavior?**
Can't use `ngc` tool with `@types/mongodb` package installed in the same node project

**Please tell us about your environment:** Windows 10

* **Angular version:** 2.4.4

* **Browser:** node
 
* **Language:** TypeScript 2.1.5

* **Node (for AoT issues):** `node --version` = v7.4.0

**Comment by DzmitryShylovich** [comment]
did you exclude `node_modules` in `tsconfig`? https://github.com/qdouble/angular-webpack2-starter/blob/master/tsconfig.aot.json#L20

**Comment by Agamnentzar** [comment]
Yes, here's the full file
```
{
	"compilerOptions": {
		"target": "es5",
		"lib": [ "dom", "es6" ],
		"module": "es2015",
		"moduleResolution": "node",
		"importHelpers": true,
		"noImplicitAny": true,
		"noImplicitThis": true,
		"noUnusedLocals": true,
		"declaration": false,
		"noEmitOnError": false,
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"noImplicitReturns": true,
		"sourceMap": false,
		"outDir": "src/aot"
	},
	"exclude": [
		"src/scripts",
		"node_modules"
	],
	"files": [
		"src/ts/bootstrap-admin2.ts"
	],
	"angularCompilerOptions": {
		"genDir": "src/aot",
		"skipMetadataEmit": true
	}
}
```

**Comment by DzmitryShylovich** [comment]
Pls provide a github repo with reproduction

**Comment by Agamnentzar** [comment]
Reproduction repo: https://github.com/Agamnentzar/angular2-bug-repro

**Comment by DzmitryShylovich** [comment]
> "typescript": "^2.1.5",

angular doesn't officially support ts 2.1+. Can you downgrade it to `2.0.10` and try again?

**Comment by Agamnentzar** [comment]
Still the same error, updated the repo with typescript `2.0.10`

**Comment by DzmitryShylovich** [comment]
> "moduleResolution": "node",

https://github.com/Microsoft/TypeScript/issues/11055#issuecomment-248982482

**Comment by DzmitryShylovich** [comment]
@Agamnentzar does it work in your real app without `"moduleResolution": "node",`?

**Comment by Agamnentzar** [comment]
`"moduleResolution": "commonjs"` results in `Error Argument for '--moduleResolution' option must be:  'node', 'classic'`

and `"moduleResolution": "classic"` or removing the option results in `Error: Could not resolve module @angular/core/src/di/opaque_token relative to undefined`

this is in the reproduction repo: https://github.com/Agamnentzar/angular2-bug-repro

**Comment by Agamnentzar** [comment]
The same in the real app

**Comment by DzmitryShylovich** [comment]
Yeah, just added `"@types/mongodb": "^2.1.37",` into my real app and it failed with the same error. Looks like a valid bug. Thx

**Comment by mjohannessen** [comment]
Has this been resolved?

**Comment by DzmitryShylovich** [comment]
@mjohannessen  nope. as you can see the issue is still open

**Comment by dustintheweb** [comment]
Temporarily solved this w/ a hack by adding 2 scripts in my `package.json`.

- Script 1 renames `node_modules/@types/mongodb/index.d.ts.tm` and is placed just before the ng serve / build.
- Script 2 changes it back to the original name, and is placed right after the ng serve / build

https://github.com/angular/angular-cli/issues/3706#issuecomment-277456055

**Comment by willshowell** [comment]
Using @Agamnentzar's reproduction repo, I found that the smallest declaration file at `node_modules/@types/mongodb/index.d.ts` that still produced the same error was this:

```
/// <reference types="node" />

import {EventEmitter} from 'events';

export class Db extends EventEmitter { }
```

Changing it to this resolved the error (per [typescript documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-class-d-ts.html)):

```
/// <reference types="node" />

import {EventEmitter} from 'events';

declare class Db extends EventEmitter { }

export = Db;
```

@DzmitryShylovich, is this an Angular bug or something to be raised with `mongodb`?

**Comment by DmitryEfimenko** [comment]
@willshowell 
Not sure how you can do this change since `node_modules/@types/mongodb/index.d.ts` exports more things than just `Db` class.

Did anyone find an easier workaround than @dustintheweb?

**Comment by DmitryEfimenko** [comment]
I think this was related to the fact that Angular didn't support typescript v2.1.x.
I updated the project to use Angular 4.0.0-rc.2 and all compiles.
See quick [migration guide](https://blog.realworldfullstack.io/real-world-angular-part-6-1-upgrading-to-4-0-0-rc-2-fcaab81603fa#.8mxco638k) or full [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md) for upgrading details.

**Comment by DzmitryShylovich** [comment]
I can confirm it does work in angular 4

@pkozlowski-opensource can be closed
