### ISSUE TITLE
Error/Exception in form ngsubmit method causes page to be submitted with form fields appended to the URL as query params 

### ISSUE THREAD

**Issue by pgeyman** [angular/angular#14080]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behaviour**

If the method called in the (ngSubmit) handler throws an Error/Exception then this causes a GET request to the same page URL with the form fields appended to the URL as query params. 

**Expected behaviour**

Any exception shouldn't cause the data to be sent, especially as a GET request. At the very least the page should log an error and do nothing. This is a security concern.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/u37wuTrzh6W1dby7CQVd?p=preview

**What is the motivation / use case for changing the behaviour?**

Security concerns

**Please tell us about your environment:**

* **Angular version:** 2.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome but probably all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   5.7.1

**Comment by DzmitryShylovich** [comment]
I think you should `try/catch` an error yourself. `ngSubmit` is just a regular event for angular, don't think we should handle it differently. Plus what angular should do with the error?

**Comment by pgeyman** [comment]
So you are saying that every time I use a form and attach a method to handle the submit I need to remember to put a try/catch around the contents of the method just in case the framework happens to throw some error at runtime?

**Comment by DzmitryShylovich** [comment]
> put a try/catch around the contents of the method

another option
```
onSubmitForm(e) {
    e.preventDefault();
    throw "Error to simulate an error generated at runtime"
  }
```
http://plnkr.co/edit/llx2Q9MCjel4v4pKC3Aw?p=preview

**Comment by pgeyman** [comment]
Ok, so I can add `e.preventDefault();` to all my form submit methods. But this still leaves the opportunity for someone to forget to do that, leaving a data security issue in the event of an error.

What is the best/recommended way to override/extend the ngSubmit of ngForm at an application wide level to add `e.preventDefault();` so that it can't be forgotten?

**Comment by chrisnicola** [comment]
@DzmitryShylovich this seems to violate the principle of least surprise and breaks the expectation of the user that the error gets reported instead of the page reloaded. This is undoutedly going to lead to a huge amount of wasted time for developers.

**Comment by pgeyman** [comment]
@DzmitryShylovich I was just wondering why you opted for adding the code fix to DomEvents plugin rather than in the onSubmit method in the ngForm directive?

**Comment by DzmitryShylovich** [comment]
@pgeyman didn't know `ngSumbit` re-emits the same event. Yeah, it's much better to do this inside `ngForm`. Thx

**Comment by ubiqs** [comment]
Same behavior happens in Angular version 4.1.0. i.e. form gets submitted with page refresh if it has a null reference exception. In Chrome.

**Comment by AndrewKushnir** [comment]
Hi, I tried to reproduce this issue using the most recent version of Angular packages and everything seems to be working correctly, see [Stackblitz page](https://stackblitz.com/edit/angular-ivy-zawvnd). I'm closing this ticket, feel free to open a new one if the problem still exists. Thank you.
