### ISSUE TITLE
Dynamically Created Components' lifecycle not fired correctly

### ISSUE THREAD

**Issue by exequiel09** [angular/angular#14090]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
The parent component generates a component based on the supplied component metadata. The lifecycle hooks of the generated component which in turn the generated child component also generates another component is not fired/called.

**Expected behavior**
The lifecycle hooks defined in the nested generated components should be fired.

**Minimal reproduction of the problem with instructions**
Reproduction Link: http://plnkr.co/edit/wRfKN5wynVC3LZKDVw1s?p=preview

The output should be: 
```
Hello Angular2

Parent
Child
Foo
```

The current behavior is:
```
Hello Angular2

Parent
Child
```

**What is the motivation / use case for changing the behavior?**
I have different kinds of modals (chart, alert, pdf viewer). One of them is a modal that displays any kind of chart like line chart, bar chart etc. So basically the parent acts as a modal component factory, the child is the chart modal which in turn dynamically creates charts based on the supplied component metadata.

**Please tell us about your environment:**
Operating System: macOS 10.12.2
Package Manager: Yarn 0.18.1
Angular CLI: 1.0.0-beta.26

* **Angular version:** 2.4.4

* **Browser:** Chrome 55.0.2883.95, Firefox 50.1.0. Haven't tested on others
 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =  6.9.2

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/8113

tltr it's by design

**Comment by exequiel09** [comment]
@DzmitryShylovich Thanks for pointing out. Closing this Issue.
