### ISSUE TITLE
angular2 loading slow on android(had use lazy loading)

### ISSUE THREAD

**Issue by TainanKent** [angular/angular#14092]
This is my Router first load Loign component and check if login then redirect to devices

export const ROUTES: Routes = [
  { path: '',      component: Login },
  { path: 'login', component: Login },
  { path: 'login/superadmin', component: Login },
  { path: 'devices', loadChildren: './device/device.module#DeviceModule' },
  { path: 'slave', loadChildren: './device/slave/slave.module#SlaveModule' },
  { path: 'admin', loadChildren: './admin/admin.module#AdminModule' },
  { path: 'alarm', loadChildren: './alarm/alarm.module#AlarmModule' },
  //如果是不存在網址預設使用 裝置頁面
  { path: '**',    component: Login },
];

loading time
PC chrome: 3s
android chrome: 7-9s
ios safari: 3-5s 

how can i promote the loading speed

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by TainanKent** [comment]
THX

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource support request

**Comment by gomesNazareth** [comment]
@TainanKent i am having  the same  issue with  android  devices  . Did you find a fix for it??

**Comment by TainanKent** [comment]
I fix this problem is use AOT compiler and lazy loading,
i am use (https://github.com/AngularClass/angular2-webpack-starter) to
design and  compiler use (npm run build:aot)
hope this can hlep you sorry my English is not good。

by the way when i use aot compiler android loading time about 3~4s

2017-03-24 5:46 GMT+08:00 Cleve Gomes <notifications@github.com>:
