### ISSUE TITLE
Angular 2 HTTP post request parameters are null

### ISSUE THREAD

**Issue by Yashavanta** [angular/angular#14099]
I am trying to make a http request(Post) using the below code.

`let url = MyURL;
    let params: URLSearchParams = new URLSearchParams();
    params.set('tenantId', tenantId);
    params.set('branchId', branchId);
    params.set('vsLoginToken', vsLoginToken);

    let body = params.toString();
    let headers = new Headers({ 'Content-Type': 'application/json' });
    let options = new RequestOptions({ headers: headers });

    this._http.post(url, body, options).map(res => res.json()).
      catch(error => Observable.throw(error.json().error || 'Server error'));`

In backend we are using google end points REST services and  i try to get the parameters values, but all the 3 parameters values are null.  Is this is a issue or our API problem?

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by felipeperezsanchez** [comment]
Yo tengo el mismo problema!! los parametros llegan en null, al hacer el request.body.variable
