### ISSUE TITLE
makeParamDecorator incorrectly updating injected parameters in inheritance

### ISSUE THREAD

**Issue by arpit-agarwal** [angular/angular#14091]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We have 2 subclasses of a base component and Inject different token on first param. This leads to incorrect injected value based on order of metadata parsing.
```
class Person {
}

var male_gender_token:OpaqueToken = new OpaqueToken("male_gender_token");
var female_gender_token:OpaqueToken = new OpaqueToken("female_gender_token");

class Male extends Person {
constructor(@Inject(male_gender_token) gender:string) {}
}

class Female extends Person {
constructor(@Inject(female_gender_token) gender:string) {}
}

now when we create male component it will get value provided on 'female_gender_token' in gender property. which is incorrect
```
**Expected behavior**
In above case gender property should get value set on 'male_gender_token'

**Minimal reproduction of the problem with instructions**
This is occurring because  ReflectMetadata can return parameters array of proto and we are modifying the same to update tokens ( based on position). See [angular code](https://github.com/angular/angular/blob/2.0.x/modules/%40angular/core/src/util/decorators.ts#L325-L337)
Ideally either ReflectMetadata should give use clone of metadata array or we should make a clone before inserting any values so that base's metadata is not modified.

ReflectMetadata has denied to provide an immutable Array [see issue](https://github.com/rbuckton/reflect-metadata/issues/53)

This could easily be tested as a unit test-case but demo is also here http://plnkr.co/edit/KnioEwNxZT2p0ZtcQXHz?p=preview.. 

**What is the motivation / use case for changing the behavior?**
 When we have to created 2 component which are mostly similar but have minor difference in view and some handling . we can utilize classic inheritance of component 

**Please tell us about your environment:**
OS: macOS 10.11.14
IDE: VS code
Packaging: npm/ rollup
* **Angular version:** 2.0.2
I think this has been fixed on latest as per code in [2.4.x brnach](https://github.com/angular/angular/blob/2.4.x/modules/@angular/core/src/util/decorators.ts#L330). It would be great if we can back port

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.0 / es5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> This could easily be tested as a unit test-case or if required i will provide a minimalstic demo.

yeah, pls provide a plunkr with repro

**Comment by arpit-agarwal** [comment]
Please have a look at plunker http://plnkr.co/edit/KnioEwNxZT2p0ZtcQXHz?p=preview. The message should be "Hello male  hello female" but it is "hello female hello female"

**Comment by DzmitryShylovich** [comment]
Yeah, it does work in the latest version https://plnkr.co/edit/pxYFfKYx7JVNQ7IgmzoY?p=preview

why do you want to backport it? just update to the latest version

**Comment by arpit-agarwal** [comment]
I am working on a enterprise application where there is reluctance to move from stable angular 2.0 release to 2.4.x release. 

we suspect we may need a lot of change in upgrading to 2.4.x in our stable product.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed

**Comment by tbosch** [comment]
Sorry, but this would be really hard to backport. Also, there have been a couple of fixes to inheritance as well. I.e. this affects multiple commits... 

Note that for 4.x we will have a LTS version, which we don't have for 2.x so upgrading to 4.x might be worth the effort in the long term...
