### ISSUE TITLE
Angular2 : How to update rest call response to an exportable variable?

### ISSUE THREAD

**Issue by Sri276286** [angular/angular#14093]
Hi,

Requirement : _Somehow I need to export **dynamicRoutes** with data from rest call._

In the below code,
 I am trying to update **dynamicRoutes** value with a response from a rest call. How can I achieve that?

Please help me to fix this.

```
import { ReflectiveInjector,Injectable,Inject } from '@angular/core';
import { Http, Response } from '@angular/http';
import { Observable } from 'rxjs';
import 'rxjs/Rx';
import { URL_CONFIG } from '../config/urls.config';
export let dynamicRoutes =[];

@Injectable()
class LoadRoutesService{

constructor(private _http: Http,
  @Inject(URL_CONFIG) public urlConfig: any) {
      let dynamicRoutes1 = [];
  }

    getRoutes(){
	    this._http.get(location.origin+this.urlConfig.sysConfigUrl)
	   .map((res:Response)=>res.json())
       .subscribe(data => 
       {
	  for(let i=0;i<data.length;i++){
      dynamicRoutes.push({path:data[i].path,loadChildren:data[i].loadPath});
	  }
      console.log('dynamicRoutes inside',dynamicRoutes);
       })
	   }
   }
console.log('dynamicRoutes after',dynamicRoutes);
```

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Sri276286** [comment]
http://stackoverflow.com/questions/41846057/angular2-how-to-update-rest-call-response-to-an-exportable-variable

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed
