### ISSUE TITLE
Checking existence of route

### ISSUE THREAD

**Issue by gjuchault** [angular/angular#14096]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**What is the motivation / use case for changing the behavior?**
It would be nice to be able to check if, from a Url or a string, to be able to get the route that would match in case of a redirection.
Use case : I'm redirecting the user if the language code is missing from the URL. Current behavior: if no language code is present, I prefix the url with `/en/`. Which makes sense for redirecting `/home` to `/en/home`. If the user goes to `/foo/home`, then it gets redirected to `/en/foo/home/` which is 404. Wanted behavior: I check the for the route existence when prefixing. If the route exists (`/home` -> `/en/home`) then I redirect to it. If not, I consider that the first path is a failed language, and I replace it with `/en/`.

The idea would be to add a function to `Router`. Something like: `router.getMatchingRoute(url: Url|string): [Route]`

**Comment by DzmitryShylovich** [comment]
What about lazy loaded routes?

**Comment by gjuchault** [comment]
I don't get the point

**Comment by Toxicable** [comment]
@gjuchault the point is that Lazy Loaded routes are unknown at any point in the applications life cycle
