### ISSUE TITLE
DatePipe milliseconds

### ISSUE THREAD

**Issue by D-Thrane** [angular/angular#14103]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a google map where I click a unit. When I click a unit I get some data about the unit from a REST through a service. I then get StartToday witch is in seconds. I then want to show it as HH:mm:ss. My StartToday returns 360.

```
{{unit.StartToday * 1000}} // Works is 360000
{{360000 | date: "HH:mm:ss"}} // Works is 01:06:00
{{unit.StartToday * 1000 | date: "HH:mm:ss"}} // Does not work 
```

I get this error:

> EXCEPTION: Error in ./MapComponent class MapComponent - inline template:11:12 caused by: Invalid argument 'NaN' for pipe 'DatePipe' ORIGINAL EXCEPTION: Invalid argument 'NaN' for pipe 'DatePipe'

**Comment by DzmitryShylovich** [comment]
Pls provide a plunkr with reproduction

**Comment by D-Thrane** [comment]
http://plnkr.co/edit/SpQP2pxmOXsn2y3ufOoX?p=preview

**Comment by pkozlowski-opensource** [comment]
The problem is that you are using an async service so your get `360000` value only after some time, asynchronously. Initially your value is `NaN` and hence the error. Check [this plunk](http://plnkr.co/edit/08jTNFBAclrXDxlntfZR?p=preview) and see the flash of `NaN` -> `3600`.

We could change the date pipe to ignore `NaN` (@DzmitryShylovich, WDYT?) but the crux of the problem is that you are passing NaN to the pipe and this is an invalid argument as clearly stated in the error message.

**Comment by DzmitryShylovich** [comment]
> We could change the date pipe to ignore NaN

I think it makes sense to just ignore `NaN` instead of throwing an error.

**Comment by pkozlowski-opensource** [comment]
> I think it makes sense to just ignore NaN instead of throwing an error.

Yeh, this wouldn't hurt. PR?

**Comment by D-Thrane** [comment]
Thanks. I'm new to Angular. How do I fix this to wait until data i ready?

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/30STyW3UJM7rqBQOhrzx?p=preview

**Comment by D-Thrane** [comment]
Why is 360000 Milliseconds  shown as 01:06:00. It's only 6 minutes?

**Comment by DzmitryShylovich** [comment]
Try `new Date(360000)` in a browser console

**Comment by D-Thrane** [comment]
It also looks like it remembers the first date pipe result and add this value to the next.
http://plnkr.co/edit/46PdAjWsH5bk4KFIsvpV?p=preview

**Comment by D-Thrane** [comment]
new Date(360000) in console gives me "Thu Jan 26 2017 20:21:31 GMT+0100 (CET)"

**Comment by D-Thrane** [comment]
So was there a date problem or?
http://plnkr.co/edit/46PdAjWsH5bk4KFIsvpV?p=preview
