### ISSUE TITLE
Simply running ngc causes it to abort with UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by DanielJoyce** [angular/angular#14108]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Trying to use AOT. Simply running `ngc` causes it to abort with:

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Right-hand side of 'instanceof' is not an object`

I can't even get any kind of response from it beyond that. Trying to pass in a project file via -p fails with the exact same error message

**Expected behavior**

ngc runs, and prints out some kind of message. Passing in a project file with -p doesn't work either.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by DanielJoyce** [comment]
I expect `ngc` to run when called from the command line. Not abort with an error. I can't get beyond that point. 

typing `ngc` simple causes it to barf. I can't even see any kind of help message.

**Comment by DanielJoyce** [comment]
package.json 

``` json

{
  "name": "surveyor_server",
  "version": "0.0.1",
  "description": "Vizualiiz Surveyor Server Software",
  "main": "src/server/server.js",
  "scripts": {
    "deps": "./gradlew downloadDeps && npm update && typings install && ./gen-sscert.sh",
    "start": "CLASSPATH=`./gradlew printClasspath`:./ NODE_PATH=./node_modules ./node_modules/.bin/vertx run src/server/boot.js --redeploy='src/server/**/*.js' --launcher-class=io.vertx.core.Launcher -conf=$JANUS_CONF -Dvertx.options.maxEventLoopExecuteTime=40000000000 -Djava.util.logging.config.file=vertx-default-jul-logging.properties",
    "build:server:ts": "tsc -p src/server/tsconfig.json",
    "build:client:ts": "tsc -p src/client/tsconfig.json",
    "build:server:ts:watch": "tsc -w -p src/server/tsconfig.json",
    "build:client:ts:watch": "tsc -w -p src/client/tsconfig.json",
    "build:help": "src/client/buildScripts/compileHelp.js",
    "build:prod:css": "node-sass src/client/app --source-map src/client/app --output-style compressed --output src/client/app",
    "postbuild:prod:css": "postcss -u autoprefixer --replace src/client/app/**/*.css src/client/assets/css/*.css -m",
    "build:prod:css:watch": "nodemon -e scss -x \"npm run build:prod:css\"",
    "build:prod:all:watch": "concurrently \"npm run build:server:ts:watch\" \"npm run build:client:ts:watch\" \"npm run build:prod:css:watch\"",
    "build:release": "npm run build:help && npm run build:server:ts && npm run build:client:ts && npm run build:prod:css",
    "start:reload": " npm run build:help && npm run build:server:ts && npm run build:client:ts && npm run build:prod:css && concurrently \"npm start\" \"npm run build:server:ts:watch\" \"npm run build:client:ts:watch\" \"npm run build:prod:css:watch\""
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.2.0",
    "@angular/compiler": "2.2.0",
    "@angular/compiler-cli": "^2.4.4",
    "@angular/core": "2.2.0",
    "@angular/forms": "2.2.0",
    "@angular/http": "2.2.0",
    "@angular/platform-browser": "2.2.0",
    "@angular/platform-browser-dynamic": "2.2.0",
    "@angular/platform-server": "^2.4.4",
    "@angular/router": "3.2.0",
    "@angular/upgrade": "2.2.0",
    "angular2-infinite-scroll": "^0.2.6",
    "angular2-jwt": "0.1.23",
    "angular2-materialize": "5.1.0",
    "autoprefixer": "^6.3.3",
    "autosize": "^3.0.17",
    "core-js": "^2.4.1",
    "datatables.net": "1.10.12",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",
    "faker": "^3.1.0",
    "jquery": "^2.2.0",
    "jquery-ui": "^1.12.0",
    "jquery.scrollto": "^2.1.2",
    "jwt-decode": "^2.1.0",
    "materialize-css": "0.97.7",
    "node-uuid": "^1.4.7",
    "nodemon": "^1.8.1",
    "postcss": "^5.0.19",
    "postcss-cli": "^2.5.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.40",
    "vertx3-full": "3.3.2",
    "zone.js": "^0.6.26"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "later": "^1.2.0",
    "node-kit": "^0.9.0",
    "node-sass": "^3.8.0",
    "typescript": "^2.0.10",
    "typings": "^1.3.2",
    "vertx-lang-typescript-typings": "https://github.com/Vizualiiz/vertx-lang-typescript-typings.git#df590b7d1737a85fb3008d7813e49a47b8c74e9a",
    "vertx3-eventbus-client": "^3.3.3"
  }
}

```

node version: 6.6.0

**Comment by DanielJoyce** [comment]
@DzmitryShylovich Well, thats nice, but this is a bug, because 'ngc' simply fails if I run it from the commandline with no options passed in. If I try and pass in a project file, that fails with the same error.

**Comment by DanielJoyce** [comment]
tried v5.12.0 and v7.4.0 of node. Still dies immediately

**Comment by DanielJoyce** [comment]
Ugh, its due to JS / NPM versioning. Closing, but ugh, still a mess. I love how stuff becomes incompatible with minor x.y.z releases and npm still doesn't have a lock file. And I can't use yarn because yarn has open bugs with git repos. 

So much waste in JS land.

**Comment by seanlandsman** [comment]
In the event someone else hits this and they happen to be using gulp ngc, I saw this with gulp-ngc and the latest (4.0.0) version of the cli - just using ngc directly (instead of gulp-ngc) fixed the problem for me (at least until gulp-ngc is upgraded)

**Comment by pl-j** [comment]
Sorry to comment a closed issue, but I have the same (or so I think) problem, and I was unable to solve it with the sole indication of "JS / NPM versioning". Tried updating node and npm, and the only benefit that provided was adding another message :

`(node:6528) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Right-hand side of 'instanceof' is not an object`
`(node:6528) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise `rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Any chance you could add some more information on what setup/versions allowed you to finally run ngc @DanielJoyce ? This will probably be useful for others as well. Thanks in advance.
