### ISSUE TITLE
@angular/compiler 2.4.4 regular expr does not work on firefox but work on chrome

### ISSUE THREAD

**Issue by abcebf** [angular/angular#14109]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

code in selector.js as following: 
var /** @type {?} */ _SELECTOR_REGEXP = new RegExp('(\\:not\\()|' +
    '([-\\w]+)|' +
    '(?:\\.([-\\w]+))|' +
    '(?:\\[([.-\\w*]+)(?:=([^\\]]*))?\\])|' +
    '(\\))|' +
    '(\\s*,\\s*)', // ","
'g');

 firefox can not parse this regexpr: ''(?:\\[([.-\\w*]+)(?:=([^\\]]*))?\\])|', should change to '(?:\\[([-.\\w*]+)(?:=([^\\]]*))?\\])|'

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.4

* **Browser:** [all | Chrome XX | Firefox 31.4.0 | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
I believe it should be fixed here https://github.com/angular/angular/pull/14082
