### ISSUE TITLE
Possible bug in Angular validation form API

### ISSUE THREAD

**Issue by netstart** [angular/angular#14105]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I write two validation, to verify the value is same.

The two code works, but in automated test the result are diferent.

Please, look the example
Execute ng serve

The button  (id="btnModifyPassword")  enables when values are the same, in both example.

But, the same test for the two components does not return the same result (execute ng test)

change-password component has broken test
modify-password component pass

**Minimal reproduction of the problem with instructions**
https://github.com/netstart/sameInputValue

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
S.O: Linux Mint MATE, kernel 4.4.0-59-generic
IDE: WebStorm 2017.1 EAP
npm : 3.10.10
node: 7.2.1

* **Angular version:** 2.4.0
* **Browser:** Chrome Versão 55.0.2883.87 (64-bit)
* **Language:** typescript: "~2.0.10"
* **Node (for AoT issues):** `node --version` =   

Sorry for my bad english, is not my first language :)

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
