### ISSUE TITLE
NgPlural does not deal properly with Russian language

### ISSUE THREAD

**Issue by eakarpov** [angular/angular#14110]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Cases work properly in cases when we explicitly show matching of the value by "=". The case "one" works properly only with value "1". In other cases only the case "other" works every time.

**Expected behavior**
By changing values to 2-4, 22-24, 32-34 etc. I would like to make NgPlural work in the case "few", not in the one "other" . (2 товара, 3 товара) And by changing values to 21,32 etc. I would like to make NgPlural work in the case "one" . (21 товар, 31 товар)

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/5xLrP4iMct7YmQyOBh1k

**What is the motivation / use case for changing the behavior?**
I increase the value which is processing by NgPlural and get wrong declension cases.

**Please tell us about your environment:**
Windows, Intellij IDEA, Webpack, Webpack dev server

* **Angular version:** 2.4.4

* **Browser:** all 
 
* **Language:** TypeScript 2.1.5

**Comment by DzmitryShylovich** [comment]
You forgot to provide a locale https://plnkr.co/edit/ENou3WumLU5Vg5NaKc0g?p=preview
