### ISSUE TITLE
Use of @Query() annotation for building a tree-like structure

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1412]
Suppose the following:

```html
<tree>
  <node>
    <node></node>
    <node></node>
  </node>
</tree>
```

Ideally the `<tree>` component, when utilizing `@Query(NodeComponent)`, could optionally only receive directives directly beneath it, instead of deeper. Is this use case already covered or planned?

/ @jelbourn, @vsavkin

**Comment by vsavkin** [comment]
You will be able to specify if you want only direct children or descendants.

**Comment by matanlurey** [comment]
Ack, I'll keep this open for tracking. Will assign to M8.

**Comment by mhevery** [comment]
closing as dup of #1462
