### ISSUE TITLE
Proposal: AOT Compiler instructions

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#14128]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, the AOT compiler is very strict and requires every object involved in DI / metadata to resolve to a symbol that the AOT compiler can work with.

It is so strict that in some scenarios, even though the symbol information is not required, it will still fail (#12631, #13138)

It makes it difficult to write custom decorators to angular component or classes that are `@Injectable`

It is clear why all items in `providers` must resolve to a known symbol, but custom decorators for a `@Component` class can fail even though it's not important.

It also creates coupling between the compiler and the core. In general it must know about every runtime generated object even if the type is known in design time (via generic).

To solve this, the compiler workaround is to import core and register a bypass to all `core` decorators

```ts
   this._registerDecoratorOrConstructor(this.findDeclaration(diDecorators, 'Host'), Host);
    this._registerDecoratorOrConstructor(
        this.findDeclaration(diDecorators, 'Injectable'), Injectable);
    this._registerDecoratorOrConstructor(this.findDeclaration(diDecorators, 'Self'), Self);
```

See [code](https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/aot/static_reflector.ts#L233-L284)

This behaviour make is almost impossible to customise angular, you can customise in JIT but not in AOT.    
Since the compiler can not get instructions how to resolve symbols for dynamic objects the experience between JIT and AOT is different.

**Expected behavior**
Allow developers to provide instruction to the compiler.

The best approach would be to use **design-time decorators**, not yet supported Microsoft/TypeScript#2900

This gives the user the ability to provide design time information to the AOT compiler.  

Until it lands a workaround to remove it can be using a webpack loader either via [Transformers API](https://github.com/Microsoft/TypeScript/pull/11561) or through a simple loader that removes that code in 2 places.

A great use case is mixins. Now that Microsoft/TypeScript#13604 is in master, and will be in 2.2 this is really important for implementing the mixin pattern.

```ts
class User_ {
}

export const User = RestMixin(User);
export type User = User_ & Mixin
```

Currently, this will fail if `User` is included as a provider.  
There is no actual reason for it to fail since `RestMixin` returns all the type information.  
It fails because the compiler can't resolve `User` into a symbol since it is dealing with complex function (RestMixin)

If I could notify the compiler what to do no compilation error.
In this case telling the compiler to resolve the symbol of `User_` to `User`

In the current code I tried it via this hack, it worked:

```
if (staticSymbol.name === 'RestMixin') converter = (ctx, args) => { return args[0]};
```

@mhevery @tbosch

**Comment by chuckjaz** [comment]
Custom decorators are ignored and transparent to  `ngc`. There was a bug introduced in 2.4.0 that has been fixed, #13605. If there are other cases where custom decorators produce errors during `ngc` please file a bug.

Libraries that use custom decorators cannot turn on strict metadata checking as such annotation will still record errors in the metadata, but the errors will not be reported by the static reflector.

As for `RestMixin`, it seems like what you need is a way to mark a function as a class factory (that is a function that produces a reference to a class). It is not important how `User` is constructed, only that it is exported and should be treated as if it were a class. Maybe something recording if `@classfactory` is in the comment block associated with the function would be sufficient. Then the `StaticReflector` would consider symbols that have the a value returned from a `@classfactory` identically as it treats symbols created by using the `class` syntax.

**Comment by shlomiassaf** [comment]
@chuckjaz I will test the first part, see if custom decorators work past 2.4.x

The `RestMixin` case is a bit more complicated, I'm not sure this single "flag" will do, but it might be so... The AOT compiler is mysterious in many (many) recursive ways :)

If so, why do you register a bypass to all class decorators defined in core?


```ts
   this._registerDecoratorOrConstructor(this.findDeclaration(diDecorators, 'Host'), Host);
    this._registerDecoratorOrConstructor(
        this.findDeclaration(diDecorators, 'Injectable'), Injectable);
    this._registerDecoratorOrConstructor(this.findDeclaration(diDecorators, 'Self'), Self);
```

See [code](https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/aot/static_reflector.ts#L233-L284)


Seems redundant?

By the way mixin's are now fully supported, Microsoft/TypeScript/#13743 , that is from 2.2 :)

**Comment by chuckjaz** [comment]
What you are seeing is not a "bypass". It is registration of classes that have special meaning in the context of AOT compile. The functions and constructors registered have known and tested semantics for use during AOT compile.

I am not convinced extending the `StaticReflector` is the right solution here. 

Once #14154 is fixed, we will support the syntax proposed in Microsoft/TypeScript#13743:

```ts
class Customer extends Tagged(Person) {
}
```

The only thing we need to support:

```ts
const TaggedPoint = Tagged(Point);
```

is something to tell us that `Tagged` produces classes. Currently the `StaticReflector` does not need type information to provide the information necessary for the AOT compiler to produce valid TypeScript. The only thing, without annotation, that tells me that `Tagged` returns a class is its type. Using `@classfactory` would allow me to distinguish it as a class factory without having to look for a `new` function in its type.

**Comment by shlomiassaf** [comment]
@chuckjaz that's great.

Implementation details... are you planning on comment annotation or code decorators?

While comments will work with no issues they are limiting refactor wise, analysis wise etc...
On the other hand, decorators will currently effect code output, they require a new decorator construct in angular and they require an extra build configuration.

**Comment by chuckjaz** [comment]
`function` cannot have decorators so we are restricted to comment annotations for now.

**Comment by shlomiassaf** [comment]
@chuckjaz Another update

```ts
export const User = RestMixin(User_);
export type User = RestMixin<Use_r>;
```

This works with AOT as long as `User` is not part of any providers array.

```ts
export class User extends RestMixin(User_) { }
```

This does not work with AOT regardless, even if the class is not used in angular it still errors.


The latter is also a mixin pattern supported in TS (2.2)

Does your proposed solution solve this as well?

**Comment by chuckjaz** [comment]
#14154 should have fixed this.

**Comment by shlomiassaf** [comment]
@chuckjaz @mhevery does this issue need to be tagged so it won't be forgotten?

What's the milestone for this?

**Comment by DzmitryShylovich** [comment]
@shlomiassaf #14154 was fixed

**Comment by tbosch** [comment]
@shlomiassaf does it work now for you?

**Comment by shlomiassaf** [comment]
@tbosch @DzmitryShylovich @chuckjaz 
Seems to be working now :)

**Comment by crh225** [comment]
@shlomiassaf, you commented AOT fails, but @tbosch  still closed the ticket? I am confused

**Comment by shlomiassaf** [comment]
Lol, yep, didn't notice that.

My first message was that it was ok, then I ran AOT and it failed.

I edited before he closed but I guess he's browser only updated the message in real time, not the edit. It happens on GitHub.

Ping  @tbosch

**Comment by tbosch** [comment]
@shlomiassaf could you create a branch that reproduces the error?

**Comment by vicb** [comment]
Closing after no update in 1 year
