### ISSUE TITLE
Router: Allow suffixes behind parameter-variables

### ISSUE THREAD

**Issue by nhnb** [angular/angular#14137]
**I'm submitting a

```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I like to handle an url like /lecture/12345.html with the Angular Router.

**Current behavior**

If I define a route '/lecture/:id.html' or '/lecture/:{id}.html', ActivatedRoute.params gets a property with the key named id.html or {id}.html and a value of 12345.html

**Expected behavior**

I would like a route of '/lecture/:{id}.html' with the url '/lecture/12345.html' to result in ActivatedRoute.params = {id: 12345}

**Minimal reproduction of the problem with instructions**

```
URL in Browser: /lecture/12345.html

// Routes in AppModule:

const appRoutes: Routes = [
  { path: 'lecture/:{id}.html', component: LectureComponent }
];

// Component:

class LectureComponent implements OnInit {
  constructor(private route: ActivatedRoute) {}
  ngOnInit() {
      this.route.params.subscribe((params: Params) => console.log(params))
  }
```

**What is the motivation / use case for changing the behavior?**

I like to use nice URLs with a .html suffix to encourage and reassure users, that it is okay, to copy and share the url.

**Comment by nhnb** [comment]
A workaround without modifying the Angular Router is to use a route such as '/lecture/:{id}.html' and strip of the curly braces and everything behind it from the parameter name and value in the component:

```
this.route.params
          .map((params: Params) => this.cleanupParamSuffixes(params))
          .switchMap((params: Params) => this.service.get(+params["id"])

  /**
   * clean up parameter suffixes.
   * 
   * Workaround for https://github.com/angular/angular/issues/14137
   */
  cleanupParamSuffixes(params: Params): Params {
      let res = {};
      for (let key in params) {
          if (key.indexOf("{") == 0) {
              let pos = key.indexOf("}");
              let suffixLength = key.length - pos - 1;
              let realKey = key.substring(1, pos);
              let realValue = params[key].substring(0, params[key].length - suffixLength);
              res[realKey] = realValue;
          } else {
              res[key] = params[key];
          }
      }
      return res;
  }
```

**Comment by DzmitryShylovich** [comment]
You need to provide your own impl of `UrlSerializer`.

**Comment by Toxicable** [comment]
@nhnb the solution to your problem I believe is with `UrlSerializer as @DzmitryShylovich mentioned

**Comment by jasonaden** [comment]
Use solution as above.
