### ISSUE TITLE
wrong date format in Thai locale

### ISSUE THREAD

**Issue by kekhuay** [angular/angular#14131]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
When i use date pipe with 'th-TH' locale something like this
`[value]="today | date: 'dd-MM-yy'"`
the result is "27-01-พ.ศ. 60" which is wrong because "พ.ศ." is Buddhist Era (BE) and i don't specify era symbol in date format.

**Expected behavior**
The correct display result should be "27-01-60".

**Please tell us about your environment:**

* **Angular version:**
2.3.1

* **Browser:**
all

**Comment by ocombe** [comment]
Hello, this will be fixed with the PR to replace the intl API for angular v5 (see [#10809](https://github.com/angular/angular/issues/10809))
