### ISSUE TITLE
Import primitive should be removed it ts2dart

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1414]
```javascript
import {int} from 'angular2/src/facade/lang';

var i:int = 10;
```
Breaks in Dart because `int` is implied import, and dart analyzer complains that it is not needed. `ts2dart` should remove primitive imports.

**Comment by tbosch** [comment]
As far as I know, this is the only type where we do this. This type relies
on our rtts asserts, in JS, which will go away after switching to
typescript. Does Typescript allows this trickery? If not, we probably
should stick to number..

**Comment by naomiblack** [comment]
Obsolete.
