### ISSUE TITLE
Css with comments parse incorrectly causing styles to be removed

### ISSUE THREAD

**Issue by xaviergxf** [angular/angular#14143]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
My component has a templateUrl that points to an html file with a style tag on the top with comments, ex:
 /*align-items: center;
        box-sizing:border-box;
        max-width:100%;/*https://github.com/philipwalton/flexbugs */

I was using the version 2.4 without problems, when i started using 2.4.5 the component had no styles applied at all.

**Expected behavior**
Comments should be ignored and styles should be added to the component

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Creation of a component

**Please tell us about your environment:**
Windows 7, VS 2015, npm

* **Angular version:** 2.0.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr with repro

**Comment by xaviergxf** [comment]
https://plnkr.co/edit/2ksSQF7jSl96o9eXXG9r?p=preview

**Comment by xaviergxf** [comment]
The error comes from having "/*" inside the comment

**Comment by DzmitryShylovich** [comment]
@xaviergxf yeah, I see, thx

**Comment by pkozlowski-opensource** [comment]
This is fixed in Angular v9 running ivy: https://ng-run.com/edit/qBKKZDattT6hdInakkHU
