### ISSUE TITLE
ES7 Private Fields and methods

### ISSUE THREAD

**Issue by Jordan-Hall** [angular/angular#14142]
**I'm submitting a ...**  (check one with "x")
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request

**Current behavior**
TypeScript:
```
class MyClass{ 
 private FieldName = 'Bob';
}
```

ES7:
```
class MyClass{ 
 this.#FieldName = 'Bob';
}
```
HTML:
```
`<span>{{FieldName }}</span> <!-- Bob -->`
```
**Expected behavior**
HTML:
```
`<span>{{FieldName }}</span> <!-- ''-->`
```

I was thinking about ES7 private fields and methods. Currently using TypeScript you can still use Private fields and methods in the view as private isn't compiled to private. However with ES7 private now exists so wouldn't it make sense that the view wouldn't be able to access private properties and methods?

**What is the angular version** 2.2.3

 
**Language:** all

**Comment by DzmitryShylovich** [comment]
> However with ES7 private now exists so wouldn't it make sense that the view wouldn't be able to access private properties and methods?

you already can't access private properties in aot.

**Comment by pkozlowski-opensource** [comment]
Yeh, members exposed to templates should be public so this is a non-issue.

**Comment by trotyl** [comment]
@pkozlowski-opensource This is actually feasible in both AOT and JIT (as long as landed in TypeScript). I'll be glad to help if it's going to be re-visited in the future.
