### ISSUE TITLE
Angular2 Docs not providing webpack + i18n solution, is there one?

### ISSUE THREAD

**Issue by emreavsar** [angular/angular#14146]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Current behavior**
The current docs[1] (and provided plunkr [2] example) shows a systemjs solution for i18n and not webpack.  

**Expected behavior**
Since angular moved to webpack, this doc should be updated to use webpack instead of systemjs for i18n.

**Minimal reproduction of the problem with instructions**
Not needed. Go to the docs page [1].

* **Angular version:** All versions until now (2.4.x)

* **Browser:**
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

* **References:**
[1] i18n docs: https://angular.io/docs/ts/latest/cookbook/i18n.html
[2] plunkr example referenced in [1]: https://angular.io/resources/live-examples/cb-i18n/ts/eplnkr.html

Since i18n is a big part of enterprise applications, this should be working out of the box with the provided toolbox.

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io/issues

**Comment by emreavsar** [comment]
Oh sorry for that. Closing this one. Opened: https://github.com/angular/angular.io/issues/3163
