### ISSUE TITLE
Closure Compiler produces too many warnings

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#14152]
This shows up in our travis logs.
Also, as users try closure as their bundler, they get too much output.
Really tsickle should produce .JS files that shut up closure - TS and ngc are responsible for checking the program, not closure compiler.
/cc @evmar

**Comment by evmar** [comment]
I agree, we should silence all Closure warnings.

**Comment by alexeagle** [comment]
I think long-term, as we ensure that a given warning is redundant with TS tooling, we should silence the Closure warning.
For now I'll just set --warning_level=QUIET in our compiler options.
