### ISSUE TITLE
static reflector should not throw when trying to simplify extend expressions

### ISSUE THREAD

**Issue by rkirov** [angular/angular#14154]
Currently the static reflector fails on cases like this:

```typescript
function metaClass() {...};
class X extends metaClass() {...}
```
or
```typescript
let ctor: {new(): T} = function() { ... };
class X extends ctor { ... }
```
When looking for annotations on X or its superclass chain, the static reflector fails. I would be preferable to not throw, but rather assume that extend expressions do not have annotations.

//cc @alexeagle

**Comment by alexeagle** [comment]
I had a fix for this in my TS 2.1 PR, I'll port it here with better tests
