### ISSUE TITLE
Template Reference Variable Immediately Usable in Template, Changed after Checked in @ViewChild

### ISSUE THREAD

**Issue by cjc343** [angular/angular#14163]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Given:**
- A template reference variable exists which is not currently defined due to being wrapped by ngIf
- A ViewChild exists for that template reference variable
- Siblings of the referenced element exist that bind values dependent on the referenced element

**Current behavior**
A sibling which uses the template reference variable directly works as expected.
A sibling which uses a function that depends on the ViewChild causes 'Expression has changed after it was checked' due to the ViewChild being undefined during the first CD run.

**Expected behavior**
The ViewChild is defined before the sibling's bound function is evaluated.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/gXwT4xMdG1z9Hlv52d1a?p=preview

While the second sibiling is present in the template, the error will be thrown upon button click & app will be unusable. If the second sibling is removed, no error is thrown and app continues to be usable after initial toggle.

**What is the motivation / use case for changing the behavior?**
When there are additional factors / criteria / checks that must be evaluated or performed to bind a value, it is preferable to define them in a well-named helper function rather than leaving complex criteria in the template.

**Please tell us about your environment:**
Ubuntu 16.04, IntelliJ IDEA, npm, webpack-dev-server

* **Angular version:** 2.4.5

* **Browser:** 
Explicitly tested in: Chrome 56, Firefox 51.

 
* **Language:**
Explicitly tested in: TypeScript 2.0.2

**Comment by Jonatthu** [comment]
@ViewChild(SomeComponent) someComponent: SomeComponent;
try this

**Comment by mlc-mlapis** [comment]
There is also similar problem with @ViewChildren when at least one component `<dynamic-component>` is under control of *ngIf and you toggle its visibility. Then runtime error `Expression has changed after it was checked.` happens.

```
<dynamic-component></dynamic-component>
<dynamic-component *ngIf="displayOtherDynamicComponent"></dynamic-component>
<div *ngIf="displayOtherDynamicComponent">Dynamic components count: {{dynamicCount}}</div>
```
where `@ViewChildren` is used to get all `<dynamic-component>` components:
```
@ViewChildren(DynamicComponent) private _dynamicCmps: QueryList<DynamicComponent>;
```
and where `dynamicCount` is evaluated in
```
ngAfterViewInit() {
    this.dynamicCount = this._dynamicCmps.length;

    this._countSub = this._dynamicCmps.changes.subscribe(x => {
      this.dynamicCount = this._dynamicCmps.length;
    });
}
```

Tested even on Angular 4.0 and 4.0.1.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/10962

**Comment by mlc-mlapis** [comment]
@DzmitryShylovich Thanks for your comment. I have not noticed that yet.

**Comment by tbosch** [comment]
Yes, this is works as intended and we need to update our docs (#10962)
