### ISSUE TITLE
Update i18n documentation: System is not defined

### ISSUE THREAD

**Issue by MickL** [angular/angular#14169]
Following the [i18n cookbook](https://angular.io/docs/ts/latest/cookbook/i18n.html) i get `System is not defined`.

Im using latest Angular CLI. My index.html looks like this:

```
<body>
  <app-root>Loading...</app-root>

  <script>
    // Get the locale id somehow
    document.locale = 'de';

    // Map to the text plugin
    System.config({
      map: {
        text: 'systemjs-text-plugin.js'
      }
    });

    // Launch the app
    System.import('app').catch(function(err){ console.error(err); });
  </script>
</body>
```

**Comment by MickL** [comment]
Took me ages to figure this out. **Documentation should be updated**.

1. Download [system.js](https://github.com/systemjs/systemjs), but it in root (/app) and import it before the script tag.
2. In index.html remove the System.import('app')
3. Rename everything from System to SystemJS (index.html, i18n-provides.ts)

Finally it looks like this:

_index.html_

```
<body>
  <app-root>Loading...</app-root>

  <script src="system.js"></script>
  <script>
    // Get the locale id somehow
    document.locale = 'en';

    // Map to the text plugin
    SystemJS.config({
      map: {
        text: 'systemjs-text-plugin.js'
      }
    });
  </script>
</body>
```

_i18n-providers.ts_
```
export function getTranslationProviders(): Promise<Object[]> {
   [...]
}

declare let SystemJS: any;

function getTranslationsWithSystemJs(file: string) {
  return SystemJS.import(file + '!text'); // relies on text plugin
}
```

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io/issues

**Comment by DzmitryShylovich** [comment]
@MickL close the issue pls as it's not a documentation repo. thx

**Comment by MickL** [comment]
https://github.com/angular/angular.io/issues/3279
