### ISSUE TITLE
Replace all occurrences of value instanceof Observable with isObservable method

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#14166]
We should replace all occurrences of `value instanceof Observable` with the method here #14067 once merged so that we have a single way for checking `Observable` types, further reasoning can be found here #8848

The only occurrence found was here: 
https://github.com/angular/angular/blob/635bf02b02973c62fb0180e64732fe601d350a45/modules/%40angular/router/src/utils/collection.ts#L132

**Comment by DzmitryShylovich** [comment]
Already did it...

**Comment by Toxicable** [comment]
Fixed here https://github.com/angular/angular/pull/14067/files#diff-e8f000a7243471d2b8cada564cb77595L132
