### ISSUE TITLE
AoT: Uncaught ReferenceError: require is not a function. 

### ISSUE THREAD

**Issue by baktash93** [angular/angular#14176]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After successfully compiling the required files with `ngc` and carrying out tree shaking with `rollup`, when the `build.js` file is loaded in the index.html, the browsers's console comes with the following error:

    build.js:2 Uncaught ReferenceError: require is not defined
    at build.js:2
    at build.js:11

If the `build.js` file is examined, you can see that there are many references to `require` which I suppose the `"module": "es2015"` value in the `compilerOptions` of the `tsconfig` enforces.

The following is an excerpt of the `dist/build.js`:

    function Yn(t){void 0===t&&(t="");var e=new Map;if(t.length>0){var n=t.split("&");n.forEach(function(t){var n=t.indexOf("="),r=n==-1?[t,""]:[t.slice(0,n),t.slice(n+1)],o=r[0],i=r[1],s=e.get(o)||[];s.push(i),e.set(o,s)})}return e}function tr(t){return encodeURIComponent(t).replace(/%40/gi,"@").replace(/%3A/gi,":").replace(/%24/gi,"$").replace(/%2C/gi,",").replace(/%3B/gi,";").replace(/%2B/gi,"+").replace(/%3D/gi,"=").replace(/%3F/gi,"?").replace(/%2F/gi,"/")}function er(){var t="object"==typeof window?window:{};return null===zh&&(zh=t[Gh]={}),zh}function nr(t,e){return t.createConnection(e).response}function rr(t,e,n,r){var o=t;return e?o.merge(new rd({method:e.method||n,url:e.url||r,search:e.search,headers:e.headers,body:e.body,withCredentials:e.withCredentials,responseType:e.responseType})):o.merge(new rd({method:n,url:r}))}function or(){return new td}function ir(t,e){return new hd(t,e)}require("../modules/es6.symbol"),require("../modules/es6.object.to-string"),module.exports=require("../modules/_core").Symbol,require("../modules/es6.symbol"),require("../modules/es6.object.create"),require("../modules/es6.object.define-property"),require("../modules/es6.object.define-properties"),require("../modules/es6.object.get-own-property-descriptor"),require("../modules/es6.object.get-prototype-of"),require("../modules/es6.object.keys"),require("../modules/es6.object.get-own-property-names"),require("../modules/es6.object.freeze"),require("../modules/es6.object.seal"),require("../modules/es6.object.prevent-extensions"),require("../modules/es6.object.is-frozen"),require("../modules/es6.object.is-sealed"),require("../modules/es6.object.is-extensible"),require("../modules/es6.object.assign"),require("../modules/es6.object.is"),require("../modules/es6.object.set-prototype-of"),require("../modules/es6.object.to-string"),module.exports=require("../modules/_core").Object,require("../modules/es6.function.bind"),require("../modules/es6.function.name"),require("../modules/es6.function.has-instance"),module.exports=require("../modules/_core").Function,require("../modules/es6.parse-int"),module.exports=require("../modules/_core").parseInt,require("../modules/es6.parse-float"),module.exports=require("../modules/_core").parseFloat,require("../modules/es6.number.constructor"),require("../modules/es6.number.to-fixed"),

**Expected behavior**

The build for the application's modules should be loaded such that all the transformed `import` statements from the TS files be somehow brought inline in the final build of the application.

**Minimal reproduction of the problem with instructions**

*STEPS TO REPRODUCE*

1. Set up an angular 2 application, either with angular's quick start, or via `angular-cli` (_I've done it with the latter_)
2. [Following all the steps from angular.io's instructions on [angular.io](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html)] First, setting up a `tsconfig-aot.json` with the following structure:

        {
	    "compilerOptions": {
		    "target": "es5",
	             "module": "es2015",
		    "moduleResolution": "node",
		    "sourceMap": true,
		    "emitDecoratorMetadata": true,
		    "experimentalDecorators": true,
		    "lib": ["es2015", "dom"],
		    "noImplicitAny": true,
		    "suppressImplicitAnyIndexErrors": true
	    },

	    "files": [
		    "app/app.module.ts",
		    "main.ts"
	    ],

	    "angularCompilerOptions": {
		    "genDir": "aot",
		    "skipMetadataEmit" : true
            }
        }

3. Setting up a `rollup-config.json` as mentioned in the docs.
4. Compiling with `ngc` via cmd: `"node_modules/.bin/ngc" -p "src/tsconfig-aot.json"
5. Creating a new `main.ts` specifically for AoT with the following lines of code:
          
        import { platformBrowser }    from '@angular/platform-browser';
        import { AppModuleNgFactory } from '../aot/app/app.module.ngfactory';
        platformBrowser().bootstrapModuleFactory(AppModuleNgFactory)

5. Rolling up with `rollup`: `"node_modules/.bin/rollup" -c "rollup-config.json"`
6. Using the build in the index.html (after the `body` closing tag) which looks like the following:
            
         <script src="dist/build.js"></script>
7. Serving the application (I use express server).
8. Loading the application on the browser with the configured port.

**What is the motivation / use case for changing the behavior?**

Quoting the docs:
> Loading the generated application bundle does not require a module loader like SystemJS.

Therefore, the compiler should be able to include all imports (maybe inline) without resorting to `require` statements or a module bundler like SystemJS or Webpack.

**Please tell us about your environment:**

* Operating system: Windows 7 64bit
* Package manager: NPM
* HTTP Server: ExpressJS v4.14.1
* Angular compiler-cli: 2.4.5
* Typescript: 2.1.5
* Rollup: 0.41.4
* rollup-plugin-commonjs: 7.0.0
* rollup-plugin-node-resolve: 2.0.0
* rollup-plugin-uglify: 1.0.1
* **Angular version:** 2.3.1

* **Browser:**  Chrome v55.0.2883.87 m and Firefox v48

* **Language:** TypeScript 2.1.5

* **Node (for AoT issues):** `node --version` =  v6.9.4

**Comment by fknop** [comment]
It's probably an issue with your rollup configuration.

Can you paste it ?

**Comment by baktash93** [comment]
Yeah sure, well this is how it looks:

     import rollup      from 'rollup'
     import nodeResolve from 'rollup-plugin-node-resolve'
     import commonjs    from 'rollup-plugin-commonjs';
     import uglify      from 'rollup-plugin-uglify'

     export default {
        entry: 'app/main.js',
        dest: 'dist/build.js', // output a single application bundle
        sourceMap: false,
        format: 'iife',
        onwarn: function(warning) {
      
        if ( warning.code === 'THIS_IS_UNDEFINED' ) { return; }
       
        if ( warning.indexOf("The 'this' keyword is equivalent to 'undefined'") > -1 ) { return; }

        // console.warn everything else
        console.warn( warning.message );
    },
    plugins: [
        nodeResolve({jsnext: true, module: true}),
        commonjs({
            include: 'node_modules/rxjs/**',
        }),
        uglify()
        ]
    }

**Comment by joh04667** [comment]
Any updates on this? Running into the same issue with almost the same setup, minus the `onwarn` key.

**Comment by fknop** [comment]
How are you importing core-js ? It looks like the require come from there.

**Comment by baktash93** [comment]
Hey folks, I just did the whole process once again and guess what, now when I searched the `build.js` file, there was no usage/reference to `require(...)` statements.
But, when the app was loading on the browser, I would still get the following error:
    
    Uncaught reflect-metadata shim is required when using class decorators

After adding the `reflect-metadata` to there was still an error indicating that a _prolyfill_ (yeah, not _polyfill_) of `Zone.js` is required:

    Uncaught Error: Angular requires Zone.js prolyfill

Yet, after adding the script for that too, ***the app is working***!

This is how the content of my `index.html` looks like now:

    <head>
        <script src="node_modules/zone.js/dist/zone.js"></script>
        <script src="node_modules/reflect-metadata/Reflect.js"></script>
        <script>window.module = 'aot'</script>
        ...
    </head>
    <body>
    </body>
    <script src="dist/build.js"></script>

As you can see, there still seems to be a problem with carrying out AoT as the two shims/scripts should have been somehow included in the original AoT build. Any suggestions for that?

**Comment by Toxicable** [comment]
@baktash93 Are you still getting this on the latest version?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource bundling issue. can be closed

**Comment by tbosch** [comment]
Closing, as this seems to have been a configuration error, unrelated to Angular.

**Comment by AnupKumarGupta** [comment]
@baktash93 I faced the exact similar problem and same exact solution worked for me too, but this can't be implemented always (i.e. creating a new project).  
@Toxicable  Yeah I am facing this issue on the latest version too.
