### ISSUE TITLE
AOT compilation seems to ignore main file defined in package.json

### ISSUE THREAD

**Issue by pgrm** [angular/angular#14171]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I add a dependency to https://github.com/IdentityModel/oidc-client-js I cannot run AOT compilation anymore. Normal build without AOT still work. 

````
ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve 'oidc-client/oidc-client' in '/Users/peter/Sync/GitHub/test-ng2-aot-oidc-client/src/$$_gendir/app'
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 55:0-52
 @ ./src/main.ts
 @ multi main
````

**Expected behavior**

I'd like AOT compilation to work as well.

**Minimal reproduction of the problem with instructions**

see the following repository: https://github.com/pgrm/test-ng2-aot-oidc-client

- clone repository
- make sure you have [angular-cli](https://github.com/angular/angular-cli) installed
- run `npm install`
- run `ng build --prod --aot`
- you should see an error saying something like this: **... Module not found: Error: Can't resolve 'oidc-client/oidc-client' ...**
- copy the `oidc-client.js` file from `node_modules/oidc-client/lib` one directory up to `node_modules/oidc-client` (`cp node_modules/oidc-client/lib/oidc-client.js node_modules/oidc-client/`)
- run again `ng build --prod --aot`
- *now it should work*

**What is the motivation / use case for changing the behavior?**

I'm not sure this is an issue with AOT compilation, or the library itself, but the closest I came to the investigation makes me think, that for AOT compilation the information about the main file in package.json is being ignored. (`"main": "lib/oidc-client.min.js"`)

**Please tell us about your environment:**

This is failing on MacOS Sierra, Windows 10 and Ubuntu 16.04 x64 

* **Angular version:** 2.4.5

````
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
````
 
* **Language:** TypeScript 2.0 and TypeScript 2.2

* **Node (for AoT issues):** `node --version` =   7.3.0 and 6.9.4

**Comment by SamVerschueren** [comment]
I had exactly the same issue when I was creating an external library. https://github.com/angular/angular/issues/14228#issuecomment-276894033

**Comment by Toxicable** [comment]
@pgrm Are you still experiencing this issue on the latest version?

**Comment by pgrm** [comment]
@Toxicable - still the same issue. My current dependencies are `@angular/*: 2.4.9` and `@angular/cli: 1.0.0-rc.0`

**Comment by gatimus** [comment]
I'm experiencing the same issue with the following:
```
@angular/cli: 1.1.1
node: 7.9.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3
```
Typescript 2.3.3
oidc-client 1.3.0

**Comment by figuerres** [comment]
Yes, i have my oidc client used with a service and that is working for me.
on the oidc-client repo is a topic where moving to typescript is being discussed and i have mentioned that  using the library might be improved for a lot of users if it was typescript based.

**Comment by vladtar** [comment]
Have people found any good workarounds for this? Still hitting this issue a year later... I've tried webpack resolve alias and/or typescript paths but just hitting other errors with those.

**Comment by JoostK** [comment]
The Ivy compiler fully relies on TypeScript module resolution so this issue has been resolved (I tested with the repro using Angular 9 to confirm).
