### ISSUE TITLE
Custom Attribute Directive and Router-Outlet

### ISSUE THREAD

**Issue by julianobrasil** [angular/angular#14170]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Custom Attribute Directives (not even the simple Angular Guide example), built inside a shared module don`t work in a component rendered in a router-outlet, in another module (lazy loaded) wich imported the former one. When I put the directive in the same module of the component that use it, it works normally.

**Expected behavior**
It should work even if built in another imported module.

**Minimal reproduction of the problem with instructions**

Build any Directive and put in a shared module. Then build a component using the custom built directive in another module and lazy load it to the project, rendering the component inside a router-outlet. The directive simply makes no effect (it throws no error messages)

**What is the motivation / use case for changing the behavior?**
I was building a directive to format currency in an input, so it was a reusable component.

**Please tell us about your environment:**
Windows 10, Microcosft Code, nodejs, ng serve

* **Angular version:** 2.0.X
2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 55
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.3

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by DzmitryShylovich** [comment]
> Build any Directive and put in a shared module

did you export it?

**Comment by julianobrasil** [comment]
@DzmitryShylovich, no I hadn`t. I tried it out and it worked. Thanks.
