### ISSUE TITLE
Don't use `[hidden]` as an example in the docs

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1417]
There are a couple of places where a binding on the `hidden` property is used as an example. This is actually not such a great idea. 

The spec _does_ say that elements with the `hidden` attribute [should not be displayed](http://www.w3.org/TR/html5/editing.html#the-hidden-attribute).

However, it goes on to [suggest that browsers implement this via CSS](http://www.w3.org/TR/html5/rendering.html#hiddenCSS). This means that the mechanism though which an element with `hidden = true` is actually hidden is:
```css
[hidden] {
  display: none;
}
```

The problem is that this rule does not have a very high specificity. It is so low, in fact, that a single CSS class rule will overcome it:
```html
<style>
  .box {
    display: block;
  }
</style>

<div class="box" hidden>Box</div>
```
The `div` will still be visible. 

I tested this in Chrome, Firefox, IE11, and mobile Safari.

(Mainly filing this issue to document why `[hidden]` shouldn't be used for future reference).

**Comment by mhevery** [comment]
Thanks for the write up. I don't think this is actually a problem, since we will have to intercept the `[hidden]` for the purposes of animation and there we can fix the specificity.
