### ISSUE TITLE
Request for something similiar to $compile

### ISSUE THREAD

**Issue by JuanAzassino** [angular/angular#14186]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
No compile type directive as in Angular 1, by loading in html content (using the appropriate sanitation rules to sanitize that html) which contain binding variables does not bind or reflect those variables within that loaded html when rendered. For example: 
```
//Inner our component:
someValue : string = "hello"
htmlContent  : string = "<div>{{someValue}}</div>"
 public getContent(thing : any) : SafeHtml{
    return this.sanitizer.bypassSecurityTrustHtml(thing);
  }

//then in our template we have:
<div [innerHtml]="getContent(htmlContent)"></div>`
```

**Expected behavior**
to return: '**hello**'

**Minimal reproduction of the problem with instructions**
Follow the above example

**What is the motivation / use case for changing the behavior?**
add in dynamic content with dynamic modeled data to that content 

* **Angular version:** 
2.4.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   6.9.4

_Due to this missing ability we had to roll back to Angular 1_

**Comment by DzmitryShylovich** [comment]
How to compile dynamically you can find [here](http://stackoverflow.com/questions/38888008/how-can-i-use-create-dynamic-template-to-compile-dynamic-component-with-angular/38888009#38888009)

But it won't work in AOT and you should avoid it

**Comment by JuanAzassino** [comment]
This is the problem, that method is complicated and 'messy', I would rather like to see Angular team give us a solution as they did in RC4 with createDynamicComponent etc... but if all else fails that solution might be needed. (Thank you for your quick reply)

**Comment by DzmitryShylovich** [comment]
Don't think it will be possible ever. Compiler is not available after aot compilation.

**Comment by Toxicable** [comment]
Can be closed? We already have the `Compiler` you just need to make sure it's shipped with your app

**Comment by JuanAzassino** [comment]
This can be closed, I made a custom component factory, which compiles during run-time, it works great!

**Comment by Toxicable** [comment]
@JuanAzassino Awesome, well you're the one who can close it :D
