### ISSUE TITLE
Nesting components often breaks layout

### ISSUE THREAD

**Issue by rodhoward** [angular/angular#14180]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Nesting components causes extra unavoidable dom elements to be included. An example of this is creating a table-row component inside a table. The layout of the table is broken due to the extra elements between the tr and tbody elements (widths don't align properly with the header).

Using attribute directives is exactly what I want I just also want to be able to include an optional nested template.

**Expected behavior**

Attribute Directives with optional templates. Why isn't this the normal used case? I can't see why you would ever want your logical component break down exposed in the html where it can mess with css and other built-ins like table structures.

**Minimal reproduction of the problem with instructions**

Create a table with a thead tag and a tbody tag in a parent container then create a child container table-row that has the <tr> elements inside it. If you add header and body data you will find that the table doesn't line up as expected. Issues like this happen when using css libraries like bootstrap as well due to extra 'filler' component elements breaking the relationship between parent and child elements.

Parent:
```
<table>
<thead>
<tr><td>header wider than body......</td></tr>`
</thead>
<tbody>           
   <my-row ></my-row>
   <my-row ></my-row>
</tbody>
</table>
```

MyRowComponent:
`<tr><td>body</td></tr>`

**What is the motivation / use case for changing the behavior?**

Less clutter and most importantly the ability to refactor the html at any point without fear of changing the final result. 

**Please tell us about your environment:**

Linux, Visual Studio Code, npm

* **Angular version:** 2.0.X

2.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 55.0.2883.59 beta (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 2.1.5

* **Node (for AoT issues):** `node --version` =   
v6.6.0

**Comment by DzmitryShylovich** [comment]
`<template>` or `<ng-container>

**Comment by vicb** [comment]
or 
```
<ng-container *myRow>
   ...
<ng-container>
```

ng-containersx are not rendered in the resulting DOM.

**Comment by rodhoward** [comment]
Thanks
