### ISSUE TITLE
ngIf with upgrade adapter is causing component to run outside zone

### ISSUE THREAD

**Issue by arins** [angular/angular#14182]
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see

Current behavior
I am using upgrade adapter. When using *ngIf on components angular runs the components outside of zone which causes the GUI not to update.
This bug is reported before and have been closed and fixed but its still the same behavior in the latest version 2.4.5

Expected behavior
I expect the angular component to run in a zone regardless of upgrade adapter (because without it works just fine)

Minimal reproduction of the problem with instructions
zone is lost when toggling a *ngIf
in my plunker example click on ng2 link then on the button "test" twice. On second click it runs outside of zone which is printed in the template
[plunker](https://plnkr.co/edit/xgyiXw?p=preview)

What is the motivation / use case for changing the behavior?
It is working without upgrade adapter so it should work in the same way with upgrade adapter.

Please tell us about your environment:
chrome

Angular version: 2.4.5

Browser: [all ]

Language: [ TypeScript]

**Comment by gkalpak** [comment]
This has been fixed with #14039 and backported to v2.4.x (with 117fa79), so it will be included in the next release. You can see the fix in action [here][1].

[1]: https://plnkr.co/edit/DC2zKI4ni36oEi9K8Y6C?p=preview

**Comment by arins** [comment]
Thanks so much for the plunker as proof! Now I know for sure it will be working in next version.
