### ISSUE TITLE
Router CanDeactivate returning false on back button press still changes browser history

### ISSUE THREAD

**Issue by JordanHeinrichs** [angular/angular#14195]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Given CanDeactivate is setup to warn user of navigation (via confirm or whatever)
1. user clicks back
2. unsaved warning comes up
3. user clicks to cancel navigation
4. user clicks back
5. user accepts the navigation
6. user is taken back two route changes

If the user continues to click back but cancelling then eventually they will leave the webapp

**Expected behavior**

@6 user is taken to the previous page/route. If the user cancels then the browser history state should be the same as before they tried to navigate.

**Minimal reproduction of the problem with instructions**

Follow instructions on plnkr
http://plnkr.co/edit/X9KfCvIs2m7lsLiygYk4?p=preview

**What is the motivation / use case for changing the behavior?**

If CanDeactivate is used to warn about unsaved changes, they click back then decide to cancel but later decide to go back anyway. The user should be presented with the previous page.

**Please tell us about your environment:**

OS: Windows 7
Using Angular 2 with webpack

* **Angular version:** 2.4.4

* **Browser:** Chrome 55

 
* **Language:** TypeScript 2.0.2

* **Node (for AoT issues):** `node --version` =  v7.3.0

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/13586

**Comment by JordanHeinrichs** [comment]
Whoops, didn't find that one while searching... Closing.
