### ISSUE TITLE
(Enhancement) Function to escape route mapping

### ISSUE THREAD

**Issue by ddlees** [angular/angular#14192]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no mechanism to escape Angular's client side routing.

**Expected behavior**
When multiple SPAs are served behind a reverse proxy, the Router should have a function to escape the Angular's route mapping to make the request instead of defaulting to an unmatched route error.

Note: Implementing this could be in config or a function call.
 
**Minimal reproduction of the problem with instructions**

N/A

**What is the motivation / use case for changing the behavior?**

Being able to serve multiple SPAs behind a reverse proxy improves UX and leverages browser side caching of shared resources and login cookies while allowing contextually different apps to remain separate. Allowing a mechanism to escape the client route mapping easily supports navigating between SPAs served from the same reverse proxy.

**Please tell us about your environment:**

OS: MacOS (El Capitan)
IDE: VSCode
Package Manager: npm
HTTP server: NginX

* **Angular version:** 2.4.1

* **Browser:** all

* **Language:** TypeScript 2.0.3
* **Node (for AoT issues):** `node --version` =   6.9.4

**Comment by devoto13** [comment]
Can you elaborate what you mean by "escape Angular's client side routing"? 

Also I don't see how anything in the Angular can help you to escape URL, which your user will paste directly into browser's address bar. So for me it seems more like issue with your reverse proxy configuration, than with Angular.

**Comment by DzmitryShylovich** [comment]
@ddlees you can call `Router.dispose()` and it will unsubscribe the router from location changes.

**Comment by ddlees** [comment]
@DzmitryShylovich Thanks! I tried `router.dispose()` with `router.initialNavigation()` and was able to get the functionality I was looking for. Fortunately, I was given access to our NginX configuration and made some adjustments which proved to be a much cleaner approach.
