### ISSUE TITLE
IE   SCRIPT5009: 'Promise' not defined

### ISSUE THREAD

**Issue by Danieleeee** [angular/angular#14202]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
At startup error: SCRIPT5009: 'Promise' not defined
File system.src.js
**Expected behavior**
No errors

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7
* **Angular version:** 2.4.5

* **Browser:** [ IE 9, 10, 11 ]

 
* **Language:** [ES5]

**Comment by DzmitryShylovich** [comment]
Looks like you need a polyfill. See https://angular.io/docs/ts/latest/guide/browser-support.html
This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Danieleeee** [comment]
Thanks for the quick response.
I will write on StackOverflow.
Anyway I have polyfill and it worked with Angular version 2.4.3
