### ISSUE TITLE
Angular2 unstability on previous releases

### ISSUE THREAD

**Issue by jindalrohit** [angular/angular#14203]
My angular2 app was working fine before yesterday. Yesterday i remove node_modules and run npm install and i get into a problem ctorParameters.map is not a function.

But i did not install any new module and not updated any angular version. Is angular2 developer are making changes in modules which were released previously ?

It destroyed my running app.

I am using angular-cli version : 1.0.0-beta.15

package.json file

`{
      "name": "myapp",
      "version": "0.1.0-pre.0",
      "license": "MIT",
      "angular-cli": {},
      "scripts": {
        "start": "ng serve",
        "lint": "tslint \"src/**/*.ts\"",
        "test": "ng test",
        "pree2e": "webdriver-manager update",
        "e2e": "protractor"
      },
      "private": true,
      "dependencies": {
        "@angular/common": "2.0.0",
        "@angular/compiler": "2.0.0",
        "@angular/core": "2.0.0",
        "@angular/forms": "2.0.0",
        "@angular/http": "2.0.0",
        "@angular/material": "^2.0.0-alpha.9",
        "@angular/platform-browser": "2.0.0",
        "@angular/platform-browser-dynamic": "2.0.0",
        "@angular/router": "3.0.0",
        "@types/lodash": "4.14.42",
        "angular2-moment": "^1.0.0-beta.rc.1",
        "angular2-notifications": "^0.4.46",
        "angular2-tag-input": "^1.2.1",
        "core-js": "^2.4.1",
        "dragula": "^3.7.2",
        "lodash": "4.17.2",
        "moment": "^2.16.0",
        "ng2-bootstrap": "^1.1.16",
        "ng2-cache": "^0.1.5",
        "ng2-dragula": "^1.2.1",
        "ng2-select": "^1.1.2",
        "ng2-sidebar": "^1.6.2",
        "ng2-toastr": "^1.3.1",
        "ng2-vs-for": "^1.1.1",
        "rxjs": "5.0.0-beta.12",
        "tether": "^1.4.0",
        "ts-helpers": "^1.1.1",
        "zone.js": "^0.6.23"
      },
      "devDependencies": {
        "@types/jasmine": "^2.2.30",
        "@types/lodash": "^4.14.42",
        "angular-cli": "1.0.0-beta.15",
        "bootstrap": "4.0.0-alpha.5",
        "codelyzer": "~0.0.26",
        "jasmine-core": "2.4.1",
        "jasmine-spec-reporter": "2.5.0",
        "jquery": "1.9.1 - 3",
        "karma": "1.2.0",
        "karma-chrome-launcher": "^2.0.0",
        "karma-cli": "^1.0.1",
        "karma-jasmine": "^1.0.2",
        "karma-remap-istanbul": "^0.2.1",
        "process-nextick-args": "^1.0.7",
        "protractor": "4.0.5",
        "tether": "^1.3.7",
        "ts-node": "1.2.1",
        "tslint": "3.13.0",
        "typescript": "2.0.10",

      }
    }`

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jindalrohit** [comment]
It's a bug in angular not an issue to me.

**Comment by jindalrohit** [comment]
It seems angular2 is unstable.
