### ISSUE TITLE
CookieXSRFStrategy: Calling function 'CookieXSRFStrategy', function calls are not supported

### ISSUE THREAD

**Issue by dineshrsharma** [angular/angular#14200]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The description provided for CookieXSRFStrategy at (https://angular.io/docs/ts/latest/guide/security.html#!#http) should work but I am getting below error when using CookieXSRFStrategy as useValue:

> Error encountered resolving symbol values statically. Calling function 'CookieXSRFStrategy', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in ...../src/app/app.module.ts, resolving symbol AppModule in ...../src/app/app.module.ts

app.module.ts
`@NgModule({
    declarations: [.....],
    imports: [
        RouterModule.forRoot(appRoutes),
        BrowserModule,
        FormsModule,
        HttpModule
    ],
    providers: [
        { provide: XSRFStrategy, useValue: new CookieXSRFStrategy('RESPONSE_TOKEN', 'RESPONSE_TOKEN') }
    ],
    bootstrap: [AppComponent]
})`

**Expected behavior**

It shouldn't throw any error & all the request should contain the RESPONSE_TOKEN

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OS: Windows 10
IDE: Visual Code Editor
Package Manager: npm

* **Angular version:** 2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
>  providers: [ { provide: XSRFStrategy, useValue: new CookieXSRFStrategy('RESPONSE_TOKEN', 'RESPONSE_TOKEN') } ]

You cannot call functions in decorators. See https://github.com/rangle/angular-2-aot-sandbox#func-in-declarations-top

Replace it with a factory provider
```
 providers: [ { provide: XSRFStrategy, useFactory: xsrfFactory:} ]

export function xsrfFactory() {
    new CookieXSRFStrategy('RESPONSE_TOKEN', 'RESPONSE_TOKEN');
}
```

**Comment by dineshrsharma** [comment]
Hey, thanks for the quick response :).

By using useFactory there is no errors but the RESPONSE_TOKEN is missing in the requests.

Am I missing something?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource the origin issue was resolved so I think it can be closed

**Comment by dineshrsharma** [comment]
@DzmitryShylovich thanks for the quick response.

**Comment by zackthoutt** [comment]
I'm experiencing the same issue. When I try to use the recommended method `ng build` stops throwing an error, but when I load the app I get 
```
error_handler.js:54EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'configureRequest' of undefined
TypeError: Cannot read property 'configureRequest' of undefined```

**Comment by maw** [comment]
@zackthoutt The answer was sloppy - add a `return` to `xsrfFactory` and it ought to work.

**Comment by badcoder28** [comment]
Im following @DzmitryShylovich instruction but in the end i got this error:

`this._xsrfStrategy.configureRequest is not a function`
