### ISSUE TITLE
Angular 2 Final Release IE11 TypeError: Object doesn't support this action

### ISSUE THREAD

**Issue by blubberbo** [angular/angular#14212]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I get the following error while running my application in IE 10 & 11:

```
TypeError: Object doesn't support this action
   at MyAppService.prototype.myFunction(eval code:64:9)
   at Anonymous function (eval code:359:21)
   at SafeSubscriber.prototype.__tryOrUnsub (eval code:223:13)
   at SafeSubscriber.prototype.next (eval code:172:17)
   at Subscriber.prototype._next (eval code:125:9)
   at Subscriber.prototype.next (eval code:89:13)
   at MapSubscriber.prototype._next (eval code:83:9)
   at Subscriber.prototype.next (eval code:89:13)
   at onLoad (eval code:1230:25)
   at ZoneDelegate.prototype.invokeTask (http://localhost:56159/node_modules/zone.js/dist/zone.js:234:17)
```
where MyAppService is a service I have created and myFunction is a function defined within that service, that I am calling from my component.

Although I would like the issue is related possibly to the shims - I have both es-5 and es-6 loaded:

```
<script src="./node_modules/es5-shim/es5-shim.js"></script>
<script src="./node_modules/es6-shim/es6-shim.js"></script>
```
downloaded via npm just earlier today, above all my other angular scripts.

The application works fine in both Chrome and Firefox

**Expected behavior**
No error

**Minimal reproduction of the problem with instructions**
I am not sure how to create a minimal reproduction in a public space, but I will try and create something. It seems like a more general issue than can be repoduced

**Please tell us about your environment:**
Windows, .NET, Visual Studio, NPM

* **Angular version:** 2.0.X
2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE 10, 11 (earlier versions as well I would guess)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr with repro

**Comment by blubberbo** [comment]
@DzmitryShylovich I will try and create one now

**Comment by kevinwardenga** [comment]
Just try to use `core-js` and import `core-js/client/shim`, in our Application its working without issues with IE11

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
