### ISSUE TITLE
Http get Issue in Angular 2

### ISSUE THREAD

**Issue by pvuser** [angular/angular#14219]
Hi

I am new angular2

I have used the following code to get data from my controller

export class TodoItem {
    constructor(     
        public name: string,
        public city: string
    ) { }
}

import { Http, Jsonp, Response, Headers, RequestOptions } from 'angular2/http';
import { Injectable, Inject } from  'angular2/core';
import { TodoItem  } from './model';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/forkJoin';

//const PEOPLE: TodoItem[] = [
//    { name: 'XXX', city: 'USA' },
//    { name: 'YYY', city: 'USA' },
//    { name: 'ZZZ', city: 'India' },
//];

//@Injectable()
//export class DataService {
//    getAll(): TodoItem[] {
//        return PEOPLE;
//    }
//}

@Injectable()
export class DataService {

    constructor(private http: Http) { }

    getComments(): Observable<TodoItem[]> {       
        return this.http.get('http://localhost:59024/api/User/GetUsers')
            .map((res: Response) => res.json());         
         

    }

}

import { Component,OnInit, Injectable, Inject} from 'angular2/core';
import { NgIf, NgFor } from 'angular2/common';
import {Http, Response, HTTP_PROVIDERS, Headers, RequestOptions} from 'angular2/http';
import { TodoItem } from './model';
import { DataService } from './data.service';
import { Observable } from 'rxjs/Observable';

@Component({
    selector: 'angularjs2demo',  
    template: `    
<ul>
    <li *ngFor="let person  of people">
    
      {{person.name}}
    
     {{person.city}}
    </li>

  </ul>

              `,

    providers: [DataService]

})

export class AppComponent implements OnInit
{
    people: TodoItem[];

    constructor(private dataService: DataService) { }

    ngOnInit() {
        // Load comments
        this.loadComments()
    }

    loadComments() {
        // Get all comments
        this.dataService.getComments()
            .subscribe(
            people => this.people = people, //Bind to view
            err => {
                // Log errors if any
                console.log(err);
            });
    }
   

}

I cant see the result . Please guide for the above issue

Thanks

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
