### ISSUE TITLE
Angular2 Module with private nested DI Context

### ISSUE THREAD

**Issue by linvi** [angular/angular#14215]
Hello,

I'm submitting a FEATURE REQUEST / QUESTION.

I am aware that Angular2 default DI Context strategy is to enrich an application-wide Dependency Injection Context. But I would like some Injectables to not be globally available.

Here is a concrete example of what I am trying to achieve.
There is probably a doc explaining how to do so but I have not been able to find it.

I would like to create a ServiceModule that would differentiate Public/Exported services from Private services.

``` ts
@Injectable() export class PrivateService{} // Not available in AppModule
@Injectable() export class PubliclyExportedService{ // Available in AppModule
  constructor(private privateService: PrivateService) { }
}

// The imported module
@NgModule({
  exports: [PubliclyExportedService],
  declarations: [PubliclyExportedService],
  providers: [
    PubliclyExportedService,
    PrivateService
  ]
})
export class ServiceModule {}

// The main module
@NgModule({
  imports: [ServiceModule]
})
export class AppModule { }
```

The goal is to use the dependency injection so that `PubliclyExportedService` can use `PrivateService` but any class outside of the `ServiceModule` would not be capable of injecting the `PrivateService`.

Any help is greatly appreciated

PS: This is a duplicate of a [stackoverflow question](http://stackoverflow.com/questions/41935142/angular2-module-with-private-nested-di-context) where nobody seemed to have an answer to this problem.

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#how-do-i-restrict-service-scope-to-a-module-

**Comment by linvi** [comment]
Thank you, it looks like it is exactly what I am looking for.

Thought the idea of creating a component to be used as a service is a bit strange, I will try this solution!

**Comment by pkozlowski-opensource** [comment]
ello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
