### ISSUE TITLE
canActivateChild service for lazy loading route must be registered in eagerly loaded module 

### ISSUE THREAD

**Issue by feng-xiao** [angular/angular#14224]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Routes defined in a lazily loading module (path: /customer/:customerNumber/)
```
const routes: Routes = [
    {
        path: ':customerNumber',
        component: CustomerComponent,
        resolve: {
            customerStateData: CustomerStateDataResolverService
        },
        children: [
            {
                path: '',
                canActivate: [CustomerRoutingGuardService],
                canActivateChild: [CustomerRoutingGuardService],
                children: [
                    { path: 'detail', component: DetailComponent } // loadChildren: './detail#DetailModule' },
                ]
            }
        ]
    }
];
```
got following error when accessing children routes /customer/1234/detail

> zone.js:420 Unhandled Promise rejection: No provider for CustomerRoutingGuardService! ; Zone: angular ; Task: Promise.then ; Value: NoProviderError {__zone_symbol__error: Error: DI Error
>     at NoProviderError.ZoneAwareError (http://localhost:61544/assets/js/polyfills.dl…, _nativeError: ZoneAwareError, keys: Array[1], injectors: Array[1], __zone_symbol__message: "No provider for CustomerRoutingGuardService!"…} Error: DI Error
>     at NoProviderError.ZoneAwareError (http://localhost:61544/assets/js/polyfills.dll.js:5113:33)
>     at NoProviderError.BaseError [as constructor] (http://localhost:61544/assets/js/vendor.dll.js:23016:16)
>     at NoProviderError.AbstractProviderError [as constructor] (http://localhost:61544/assets/js/vendor.dll.js:156608:16)
>     at new NoProviderError (http://localhost:61544/assets/js/vendor.dll.js:156670:16)
>     at ReflectiveInjector_._throwOrNull (http://localhost:61544/assets/js/vendor.dll.js:291800:19)
>     at ReflectiveInjector_._getByKeyDefault (http://localhost:61544/assets/js/vendor.dll.js:291839:25)
>     at ReflectiveInjector_._getByKey (http://localhost:61544/assets/js/vendor.dll.js:291786:25)
>     at ReflectiveInjector_.get (http://localhost:61544/assets/js/vendor.dll.js:291546:21)
>     at AppModuleInjector.NgModuleInjector.get (http://localhost:61544/assets/js/vendor.dll.js:157573:52)
> 

canActivateChild guard works if I register the service in parent's eagerly loading module.

**Expected behavior**
canActivate guard service doesn't need to register in eagerly loading module to make it work, so shouldn't throw errors for canActivateChild guard

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- Windows 10
- Webpack: 2.2
- ng-router-loader: 2.1

* **Angular version:** 2.0.X
2.4.5
router: 3.4.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.1.5

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. Luckily it has already been fixed https://github.com/angular/angular/pull/13989 and will be available in the next release.

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich

**Comment by kiran8910** [comment]
I'm using @angular/router@2.4.6 and still facing this issue. Any suggestions?
