### ISSUE TITLE
Transitions With Preloader

### ISSUE THREAD

**Issue by sGerli** [angular/angular#14220]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`:enter` gets triggered before route is preloaded, so when the component appears it has no transition because it has already been executed.

**Expected behavior**
`:enter` gets triggered after route finishes preloading and transition is visible to the user.

**Minimal reproduction of the problem with instructions**

1. Create an angular app with a router, add preloader to the root or home route.
2. Then add a transition for the `:enter` state of that route.

Example: 
- https://github.com/iGerli/clockOS-ui/blob/dev/angular2/src/app/app-routing.module.ts#L10
- https://github.com/iGerli/clockOS-ui/blob/dev/angular2/src/app/animations.ts#L35

**What is the motivation / use case for changing the behavior?**

If you design nice transitions you at least want them to get displayed.

**Please tell us about your environment:**

- Ubuntu 16.10
- Visual Studio Code
- Angular CLI

* **Angular version:** 2.4

* **Browser:** [Chrome | Firefox] (Didn't try on the others but I'm sure the issue is there)

 
* **Language:** [TypeScript]

**Comment by matsko** [comment]
This can be handled now via `animateChild()`.
