### ISSUE TITLE
Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported.

### ISSUE THREAD

**Issue by SamVerschueren** [angular/angular#14228]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It might be related to https://github.com/angular/angular/issues/14221, but not sure. So I'm building this [GoogleAnalytics](https://github.com/SamVerschueren/angular-ga) library for Angular and it works like it should work in development. But when I run it with AoT, I get this `makeDecorator` error

> Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported.

I searched for that error but really couldn't find anything. I wondered a couple of hours what could cause this issue but because the library is pretty small I figured it might be something in angular core that causes this.

**Expected behavior**
The library to work with AoT.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
macOS Sierra, VS Code, Yarn, angular-cli

* **Angular version:** 2.4.5

* **Browser:** all
 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =  6.9.1

**Comment by DzmitryShylovich** [comment]
Pls add a repro

**Comment by SamVerschueren** [comment]
Thanks for asking @DzmitryShylovich! I planned on doing that yesterday but didn't have much time so I did it today. Because I was working in a very small dummy project, I could debug it more easily.

I was using the `angular-cli` and that might be the culprit of the issue. The thing is that my packaged library looked like this

```
- package.json
- readme.md
- dist
   |- index.js
   |- index.d.ts
   |- index.metadata.json
   |- lib
       |- ...
```

And the `main` property in my `package.json` was pointed to `dist/index.js`. So I changed the structure of my library like this

```
- package.json
- readme.md
- index.js
- index.d.ts
- index.metadata.json
- lib
   |- ...
```

It might be that `angular-cli` isn't looking at the `main` property in the `package.json` file and is just assuming that an `index.js` file is present.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/14171

**Comment by SamVerschueren** [comment]
Thanks!

**Comment by QuantumInformation** [comment]
I just run into this with ng build --prod. ng serve works fine.

**Comment by QuantumInformation** [comment]
repro here: https://github.com/QuantumInformation/angular-finance/tree/master/demo

**Comment by 1-0-1** [comment]
Why are so many of these "Calling function 'makeDecorator', function calls are not supported" issues just being closed without coming up with a solution?  With the latest cli, this error won't even allow the build to complete.  I wish this would get changed to a warning.

**Comment by SamVerschueren** [comment]
How could it be a warning? It just can't build because something is wrong in your code. Angular can't magically work around that.

**Comment by 1-0-1** [comment]
Up until beta26, it would continue the build process and everything worked afterwards. It was still an error which means other build processes would be halted, but at least it would build.
This is usually an issue with third party libraries.  If this error where changed to a warning, developers could continue working until the library caught up with the changes made at the angular / angular-cli level.

**Comment by itsnotvalid** [comment]
I tested with just updating @angular/cli from beta.32 to 1.0.0-rc.1. The problem is actually on other dependencies for my case with ng2-truncate@1.3.2 (installed via yarn). If I just update my @angular/cli to 1.0.0-rc.1, aot/non-aot compilation doesn't break. But when I also upgrade my @angular/* from 2/3.4.8 to 2/3.4.9, 'makeDecorator' starts to show up.

Somehow between 2.4.8 and 2.4.9, something is changed for me. I'd produce a more reliable yarn.lock diff to make sure this is angular's or something else's problem.
