### ISSUE TITLE
JSONP 'finished' callback should not be obfuscated

### ISSUE THREAD

**Issue by vqtran** [angular/angular#14223]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

It is expected that the JSONP callback is of the form `__ng_jsonp__._req0.finished(...)` however when an minified/obfuscated build of Angular is used, 'finished' gets renamed.
**Expected behavior**

'finished' should not be renamed. The way the JSONP callbacks are named should be reliable and independent of how Angular is minified.

**Minimal reproduction of the problem with instructions**
1. Generate a minified build of Angular 2.
2. Create a test.jsonp file with the contents, `__ng_jsonp__._req0.finished('hello world');`
3. Create a component which uses the minified build, imports the Angular 2 JSONP module, and tries to load test.jsonp.
4. Expect an error related to the callback not found. We can verify that 'finished' doesn't exist by opening the console and running: `console.log(window.__ng_jsonp__._req0)`. This object should be obfuscated.

I can also point out where in the code causes this behavior:

1. In browser\_jsonp.ts, [exposeConnections()](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/browser_jsonp.ts#L37) sets the connection at `window.__ng_jsonp__._req0`. This is done properly to prevent `__ng_jsonp__` and `_req0` from being minified.
2. [`JsonpConnection_` however calls this with itself](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/jsonp_backend.ts#L70).
3. But [`finished()`](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/jsonp_backend.ts#L132) is a function on `JsonpConnection_` that is not protected from minification.

**What is the motivation / use case for changing the behavior?**

1. It should be possible to reliably make a static file that can be served via JSONP. This requires a consistent callback independent of build process. Its not possible to guess what 'finished' will be renamed to.
2. This renaming also breaks how JSONP_CALLBACK is replaced. [(It assumes the callback always is called 'finished').](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/browser_jsonp.ts#L35) This means that a proper JSONP server parsing the callback param can't properly generate a JSONP response either.

**Please tell us about your environment:**

Ubuntu, vim, Bazel, AppEngine

* **Angular version:** 2.0.X

* **Browser:**  all

 
* **Language:** Typescript

**Comment by alexeagle** [comment]
Note, @mprobst and I already triaged this one, PR may be contributed today

**Comment by alxhub** [comment]
Obsolete (`HttpClient` uses a dynamic callback name, not subject to this bug).
