### ISSUE TITLE
@Inject of AngularJS service into Ng2 Component constructor fails

### ISSUE THREAD

**Issue by pdhar-tibco** [angular/angular#14239]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am trying to integrate a bunch of AngularJS services to be used in a Hybrid AngularJS and Angular app using the documented method here https://angular.io/docs/ts/latest/guide/upgrade.html#making-angularjs-dependencies-injectable-to-angular.

After looking at the #14065 fix it used an OpaqueToken instead of string.  I tried using token and string to get the service, but it is only visible at the main bootstrap() call where you use the platformRef.injector to get the token values or by string 'heroes'.
```
platformBrowserDynamic().bootstrapModule(Ng2AppModule,[]).then(platformRef => {
  
  console.debug('AppModule bootstrapped');
  const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
  console.debug('upgrade obtained')
  upgrade.bootstrap(document.body, [Ng1AppModule.name]);
  console.debug('bootstrapping finished');
  let heroService = platformRef.injector.get('heroes');
  console.log(heroService);
  console.log(heroService.get());
  svc = platformRef.injector.get(AuthService);
  console.log(svc);

  // setTimeout is necessary because upgrade.bootstrap is async.
  // This should be fixed.
  setTimeout(() => {
    platformRef.injector.get(Router).initialNavigation();
  }, 0);
});
```
The upgraded services are defined in the main ng2 app module as
```
    {
            provide: AuthService, 
            useFactory: ($injector: any) => $injector.get('dataService'), 
            deps: ['$injector']
     },
    {
        provide: 'heroes',
        useFactory: (i: any) => i.get('heroes'),
        deps: ['$injector']
    },
```
However when the same is used in a component using @Inject in the constructor arguments
```
constructor(
       @Inject(AuthService) private logoutSvc: any,
       @Inject('heroes') heroes: HeroesService
    ) {
      
    }
```
I tried to debug in the browser console and found that the Ng2AppModuleInjector is not initialized with the Service Instance values
```
Ng2AppModuleInjector.prototype.getInternal = function(token,notFoundResult) {
  var self = this;
  if ((token === jit_CommonModule56)) { return self._CommonModule_0; }
  if ((token === jit_ApplicationModule57)) { return self._ApplicationModule_1; }
  if ((token === jit_BrowserModule58)) { return self._BrowserModule_2; }
  ......
  if ((token === jit_Token_auth_service106)) { return self.**_Token_auth_service_59**; }
  if ((token === 'heroes')) { return **self._heroes_60**; }
  if ((token === jit_Unique55)) { return self._Unique_61; }
  return notFoundResult;
};
```
**I get this error** 
```
core.umd.js:3527 TypeError: Cannot read property 'get' of undefined
    at useFactory (https://run.plnkr.co/OI78UetXmT3BAAF3/src/app.header.ts!transpiled:55:84)
    at CompiledTemplate.proxyViewClass.View_App0.createInternal (/Ng2AppModule/App/component.ngfactory.js:32:34)
    at CompiledTemplate.proxyViewClass.AppView.create (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:12408:25)
    at CompiledTemplate.proxyViewClass.DebugAppView.create (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:12812:48)
    at CompiledTemplate.proxyViewClass.View_App_Host0.createInternal (/Ng2AppModule/App/host.ngfactory.js:16:19)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:12421:25)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:12829:56)
    at ComponentFactory.create (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:7766:29)
    at ApplicationRef_.bootstrap (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:8753:61)
    at eval (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:8581:93)
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:8581:46)
    at eval (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:8533:31)
    at ZoneDelegate.invoke (https://npmcdn.com/zone.js@0.7.4/dist/zone.js:242:26)
    at Object.onInvoke (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:4427:41)
ErrorHandler.handleError @ core.umd.js:3527
(anonymous) @ core.umd.js:8442
ZoneDelegate.invoke @ zone.js:242
onInvoke @ core.umd.js:4427
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:520
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ core.umd.js:4418
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:418
ZoneTask.invoke @ zone.js:349
core.umd.js:3530 ERROR CONTEXT:
ErrorHandler.handleError @ core.umd.js:3530
(anonymous) @ core.umd.js:8442
ZoneDelegate.invoke @ zone.js:242
onInvoke @ core.umd.js:4427
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:520
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ core.umd.js:4418
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:418
ZoneTask.invoke @ zone.js:349
core.umd.js:3531 DebugContext {_view: C…e.proxyViewClass, _nodeIndex: 1, _tplRow: 2, _tplCol: 5}
ErrorHandler.handleError @ core.umd.js:3531
(anonymous) @ core.umd.js:8442
ZoneDelegate.invoke @ zone.js:242
onInvoke @ core.umd.js:4427
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:520
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ core.umd.js:4418
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:418
ZoneTask.invoke @ zone.js:349
zone.js:405 Unhandled Promise rejection: Error in ./App class App - inline template:2:5 caused by: Cannot read property 'get' of undefined ; Zone: <root> ; Task: Promise.then ; Value: ViewWrappedError {_nativeError: Error: Error in ./App class App - inline template:2:5 caused by: Cannot read property 'get' of undef…, originalError: TypeError: Cannot read property 'get' of undefined
    at useFactory (https://run.plnkr.co/OI78UetXm…, context: DebugContext} TypeError: Cannot read property 'get' of undefined
    at useFactory (https://run.plnkr.co/OI78UetXmT3BAAF3/src/app.header.ts!transpiled:55:84)
    at CompiledTemplate.proxyViewClass.View_App0.createInternal (/Ng2AppModule/App/component.ngfactory.js:32:34)
    at CompiledTemplate.proxyViewClass.AppView.create (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:12408:25)
    at CompiledTemplate.proxyViewClass.DebugAppView.create (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:12812:48)
    at CompiledTemplate.proxyViewClass.View_App_Host0.createInternal (/Ng2AppModule/App/host.ngfactory.js:16:19)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:12421:25)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:12829:56)
    at ComponentFactory.create (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:7766:29)
    at ApplicationRef_.bootstrap (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:8753:61)
    at eval (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:8581:93)
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:8581:46)
    at eval (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:8533:31)
    at ZoneDelegate.invoke (https://npmcdn.com/zone.js@0.7.4/dist/zone.js:242:26)
    at Object.onInvoke (https://unpkg.com/@angular/core@2.4.5/bundles/core.umd.js:4427:41)
```

**Expected behavior**

I should be able to inject the Angular1 service into a Angular 2 component constructor
**Minimal reproduction of the problem with instructions**

Plunker test case: 

https://plnkr.co/edit/OcQ6LKz9LPk66Vl30286

https://plnkr.co/edit/ZtpTcj?p=preview

The angular 2 component is src/app.header.ts
This component has a link "logout" which will call the function logout() to console.log the service.
The current workaround is to store the service from main.ts into a global variable and use it in the component, which is not the right way.

This plunk tries to follow the documented way of upgrading a ng1 service to be called in a ng2 component https://angular.io/docs/ts/latest/guide/upgrade.html#making-angularjs-dependencies-injectable-to-angular
https://plnkr.co/edit/ZtpTcj?p=preview

The component level injectors are not able to find the injected item.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OSX, Visual Code, NPM, Node koa

* **Angular version:** 2.0.X

2.4.5 latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript->ES5

* **Node (for AoT issues):** `node --version` =   
6.9.4 using platformBrowserDynamic bootstrap..

**Comment by pdhar-tibco** [comment]
After changing the angular/modules/@angular/upgrade/test/aot/integration/injection_spec.ts I can reproduce the error
`/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */

import {Component,Injector,Inject, NgModule, OpaqueToken, destroyPlatform} from '@angular/core';
import {async} from '@angular/core/testing';
import {BrowserModule} from '@angular/platform-browser';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import * as angular from '@angular/upgrade/src/angular_js';
import {$INJECTOR, INJECTOR_KEY} from '@angular/upgrade/src/aot/constants';
import {UpgradeModule, downgradeInjectable} from '@angular/upgrade/static';

import {bootstrap, html} from '../test_helpers';

export function main() {
  describe('injection', () => {

    beforeEach(() => destroyPlatform());
    afterEach(() => destroyPlatform());

    it('should downgrade ng2 service to ng1', async(() => {
         // Tokens used in ng2 to identify services
         const Ng2Service = new OpaqueToken('ng2-service');

         // Sample ng1 NgModule for tests
         @NgModule({
           imports: [BrowserModule, UpgradeModule],
           providers: [
             {provide: Ng2Service, useValue: 'ng2 service value'},
           ]
         })
         class Ng2Module {
           ngDoBootstrap() {}
         }

         // create the ng1 module that will import an ng2 service
         const ng1Module =
             angular.module('ng1Module', []).factory('ng2Service', downgradeInjectable(Ng2Service));

         bootstrap(platformBrowserDynamic(), Ng2Module, html('<div>'), ng1Module)
             .then((upgrade) => {
               const ng1Injector = upgrade.$injector;
               expect(ng1Injector.get('ng2Service')).toBe('ng2 service value');
             });
       }));

    it('should upgrade ng1 service to ng2', async(() => {
         // tslint:disable-next-line:no-console
        console.log("##### HERE #########");
         // Tokens used in ng2 to identify services
         const Ng1Service = new OpaqueToken('ng1-service');
         const HeroesNg1Service = new OpaqueToken('heroes-service');
          // the ng2 component that will be used in ng1 (downgraded)
         @Component({selector: 'ng2', template: `<p>{{data}}</p>`})
         class Ng2Component {
            data:string;
            constructor(@Inject(HeroesNg1Service) private ng1Service:HeroesService) {
              // tslint:disable-next-line:no-console
              console.log("##### CONSTRUCTOR #########");
              // tslint:disable-next-line:no-console
              console.log(ng1Service.getHeroes());
              this.data = ng1Service.getHeroes();
              expect(ng1Service.getHeroes()).toBe('HEROES');
            }
         }
         // Sample ng1 NgModule for tests
         @NgModule({
           imports: [BrowserModule, UpgradeModule],
           declarations:[Ng2Component],
           entryComponents:[Ng2Component],
           providers: [
             // the following line is the "upgrade" of an Angular 1 service
             {
               provide: Ng1Service,
               useFactory: (i: angular.IInjectorService) => i.get('ng1Service'),
               deps: ['$injector']
             },
             {
               provide: HeroesNg1Service,
               useFactory: (i: angular.IInjectorService) => i.get('heroes'),
               deps: ['$injector']
             }
           ],
           bootstrap:[Ng2Component]
         })
         class Ng2Module {
           ngDoBootstrap() {}
         }

         class HeroesService {
            getHeroes() {
              return "HEROES";
            }
         }

         // create the ng1 module that will import an ng2 service
         const ng1Module = angular.module('ng1Module', [])
         .value('ng1Service', 'ng1 service value')
         .value('heroes',HeroesService);


         bootstrap(platformBrowserDynamic(), Ng2Module, html('<ng2></ng2>'), ng1Module)
             .then((upgrade) => {
               const ng2Injector = upgrade.injector;
               expect(ng2Injector.get(Ng1Service)).toBe('ng1 service value');
               // tslint:disable-next-line:no-console
               console.log("HEROSERVICE:"+ng2Injector.get(HeroesNg1Service));
             });
       }));

    it('should initialize the upgraded injector before application run blocks are executed',
       async(() => {
         let runBlockTriggered = false;

         const ng1Module = angular.module('ng1Module', []).run([
           INJECTOR_KEY,
           function(injector: Injector) {
             runBlockTriggered = true;
             expect(injector.get($INJECTOR)).toBeDefined();
           }
         ]);

         @NgModule({imports: [BrowserModule, UpgradeModule]})
         class Ng2Module {
           ngDoBootstrap() {}
         }

         bootstrap(platformBrowserDynamic(), Ng2Module, html('<div>'), ng1Module).then(() => {
           expect(runBlockTriggered).toBeTruthy();
         });
       }));
  });
}
`

**Comment by vasuneet** [comment]
I am having the same issue when i am trying to use the upgraded service (implemented in ng1) in ng2 component. When i am trying to bootstrap my ng2 AppModule it looks for service provider via useFactory and injector is undefined.

**Comment by pdhar-tibco** [comment]
Using Angular's own example https://github.com/angular/angular.io/tree/master/public/docs/_examples/upgrade-module/ts/src/app

It works here when the main app directive is from Ng1 http://plnkr.co/edit/rcb8b7?p=preview 
and it does not work here when the main app selector is Ng2  https://plnkr.co/edit/1NZTAM?p=preview

**Comment by gkalpak** [comment]
I am a little lost. Could you please create a minimal reproduction and explicitly mention what you expect and what happens instead?

**Comment by pdhar-tibco** [comment]
The minimal reproductions is here https://plnkr.co/edit/1NZTAM?p=preview

**Comment by daniel-a-melo** [comment]
The official docs for integrating ng-router and angular router (https://angular.io/docs/ts/latest/guide/upgrade.html#!#dividing-routes-between-angular-and-angularjs) indicates using an angular component (ng2+) as a bootstrap component. 

In that case, as @pdhar-tibco demonstrated, angular fails to inject upgrades services into angular components, as the factory is invoked before ng1 bootstraped. 

Tested with Angular 4.0.2

**Comment by grbush** [comment]
I also come across the same problem as @daniel-a-melo @pdhar-tibco mention. My not-so-cunning work around is to downgrade my Angular component and then create a dummy AngularJS component which serves as the root of my app. 

const module = angular.module('bootModule', ['linqCore']);
module.directive('linqNg2', downgradeComponent({component: AppComponent}));
module.component('linqNg1', {template: '<linq-ng2></linq-ng2>'});

**Comment by JBriesen** [comment]
I am having the same issue now. Been following the tutorial for the upgrade but it doesnt work when i switch to the angular Route provider.
I have currently decided toe upgrade the services first because the option to upgrade a service for use inside an angular component works when using angularjs routing and breaks when i switch to using angular routing.

i might try the methode that @grbush is using.

**Comment by gkalpak** [comment]
Sorry for the very late response, @pdhar-tibco. I missed the reproduction in https://github.com/angular/angular/issues/14239#issuecomment-293269726 😞

Due to how ngUpgradeFull (which is what you are using) is implemented inside, it is indeed necessary that AngularJS "owns" the root of the app. So, if you want to use an Angular component at the root, you need to downgrade it. This won't change, but only adds very minimal overhead.

Alternatively, you could also use the new ngUpgradeLite, which allows having Angular at the root (along with other differences). You can find some docs [here][1] (I hope to land this soon).

[1]: https://github.com/angular/angular/pull/18487
