### ISSUE TITLE
Encapsulation = None styles persist after component removal.

### ISSUE THREAD

**Issue by jcomputer** [angular/angular#14238]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Given a component with `encapsulation` set to `none`, if no instances exist on the page (such as `*ngIf="false"`), its styles are not applied to the page. Once it does exist (that `*ngIf` becomes true), its styles are applied to the whole page. All of this is as expected.

However, if this `*ngIf` is set back to false, these styles continue to be applied to the page.

**Expected behavior**

If at least one instance of this component exists on a page, its styles should be applied to the page. If no instances of this component exist on a page, its styles should not be applied to the page (or should be removed if previously applied).

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/WEOWO8vl3UyoqlutoB35?p=preview

**What is the motivation / use case for changing the behavior?**

This could be used for a component to override surrounding styles (which it shouldn't be doing if it doesn't exist on the page) or for easy conditional restyling of a page (maybe running an experiment?). 

**Please tell us about your environment:**

Linux. I just wrote this in Plunker.

* **Angular version:** 2.4.5

* **Browser:** I am using Chrome Version 55.0.2883.105 (64-bit), but I suspect this applies to all browsers.
 
* **Language:** TypeScript 2.0.2

**Comment by bassrock** [comment]
I am seeing this issue as well and am curious if this is planned to get integrated. I am also seeing it occur with other view modes.

**Comment by tbosch** [comment]
Yes, this occurs with any view modes. I.e. we add the styles lazily at the time a component is created the first time. However, we might change this in the future to do this more eagerly e.g. by adding the styles of all components at once.

So this is works as intended, and we are not planning in changing this behavior.

**Comment by bassrock** [comment]
@tbosch I get the lazy load, but shouldn't the styles that got added be removed when that component is removed?

**Comment by tbosch** [comment]
@bassrock yes we could, but as I said we will probably change our behavior to eagerly insert styles, or even generate a single `.css` file for the whole application. I.e. in that case, the styles are used permanently as well. So if we change this behavior now, we will have a breaking change later...

**Comment by webdevan** [comment]
I don't understand the reason to apply every route's global CSS at the same time. It would be very useful to have the ability to load specific global CSS per view (and I thought we were half-way there).

If all the CSS gets eager-loaded into one CSS file, can there at least be a unique CSS parent class added to the html tag automatically to change the global CSS whenever the route changes? It's a very common web development need to have different global CSS per view, and this would have been an elegant way to handle the need.
