### ISSUE TITLE
Access wsdl daat from Angular2 framework

### ISSUE THREAD

**Issue by bansanguy** [angular/angular#14250]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [TypeScript X.X]

* **Node (for AoT issues):** `node --version` =   

Hi All,

I need to access data through a wsdl file. My approach is to convert the wsdl data into json format and later work with the json file. check.wsdl​​ is the associated file with the url and authenticate​ is the method to validate the logged in user credentials of user & password.
Please let me know if it is the right approach to connect to the wsdl from Http.

​export class WSDLService {

constructor (private http:Http) { }
getData:string;
postData:string;
  let params = new URLSearchParams();
  params.set('user', 'user123');
  params.set ('password', 'pwd@1234');

return this.http
      .get('https://dpls.gf.com:1234/SRDCTM_WebService/Security/WEB-INF/wsdl/check.wsdl'; {method: authenticate}; {search: params})
      .map(request=>request.json())
      .subscribe(
        data => this.getData = JSON.stringify(data),
        error => alert(error),
        () => console.log("Completed!")
      );   

Regards, Pradeep

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
