### ISSUE TITLE
JiT compiler produces JavaScript code that lacks `use strict`

### ISSUE THREAD

**Issue by awerlang** [angular/angular#14254]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Use of two-way binding fails silently when writing to a frozen object.

**Expected behavior**
Should throw an exception when writing to a frozen object.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/5Ho7YY3g9i59BjIkWCS3?p=preview

See how the underlying object is mutated, for regular and frozen object. A frozen object doesn't change its value, but also doesn't throw. `xOnChange` throws as expected, because it runs my own code transpiled with SystemJS.

Click on reset button to see that the frozen object indeed throws.

**What is the motivation / use case for changing the behavior?**
It is expected that ES6 modules run on a strict-mode context. I'm using `ngrx-store-freeze` to freeze objects in the store.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.4.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by DzmitryShylovich** [comment]
It's not specific to `ngModel` and affects all two way bindings.
All  https://plnkr.co/edit/Gq4hw0Dn0gfyh9JTAVXk?p=preview
Can you pls change the misleading title?

**Comment by awerlang** [comment]
Updated. I did further investigation, now I believe it's related to jit compiler. It happens with both SystemJS and angular-cli (webpack). Have yet to verify with aot, but this is more a feature request for dev mode, which jit mode is more common.

Anyway, due to how code it's transpiled in aot, I don't think it would happen there. jit compiler produces js code that lacks a `use strict`. Given that ngfactory's are generated by angular and angular itself runs in strict mode, I guess it would only be natural to expect ngfactory also in strict mode, as I guess it already would in aot mode.

**Comment by pburgmer** [comment]
We have the same problem using frozen objects and https://github.com/Tydux/Tydux/ (redux like state management).

If the developer uses a two-way data-binding somewhere the assign will fail silently. Tydux wants to prevent the usage of two-way data-binding. But without an error reporting the misuse this will only produce bugs instead of improve the code quality.

Are there any plans to change this?

**Comment by JoostK** [comment]
This has been changed in #30122.
