### ISSUE TITLE
Animation .done callback is not called when you are on a different browser tab

### ISSUE THREAD

**Issue by venelinpetrov** [angular/angular#14269]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Animation `.done` callback is not called when you are on a different browser tab.

**Expected behavior**
Animation `.done` should be called when the animation is over.

**Minimal reproduction of the problem with instructions**
I have a notification mechanism that renders \<li\>s with some text (basically mutating an array of objects, iterated with \*ngFor). They come in with animation and when the animation is over I need to schedule a timer (timeout) to hide the notification (splice the array). 

The problem is that when I am on a different tab and notifications are emitted in background from source the animation `.done` callback is not called, which in turns doesn't schedule the timer, which in turns makes a whole bunch of notifications to stack and flood the page. At the moment when you come back to the tab then the callback is called for every notification almost simultaneously and thus they all disappear at the same time approximately. I can see that by adding `console.log(new Date())` in the callback function which outputs the same times even though the notifications appear with delay one respect to the other.

**What is the motivation / use case for changing the behavior?**
I know it's possible to define animation with keyframes and basically to achieve the same without callbacks and timers, but I need to be able to pass parameters like delay time, whether a notification of certain type should auto hide or not and so on. I don't see a way to do this solely with Angular animations, because they are part of the component's metadata and can't be parametrized as far as I can tell. So this is my motivation.

**Please tell us about your environment:**
OS: Windows 8.1
IDE: VS Code 1.9.0
Infrastructure: Angular CLI (1.0.0-beta.25.5) Project

* **Angular version:** 2.4.4

* **Browser:** Google Chrome 55, Opera 42, Firefox 50

* **Language:** TypeScript 2.0.10

**Comment by DzmitryShylovich** [comment]
@venelinpetrov does the issue still persist in angular 4? can you add a plunkr, please?

**Comment by matsko** [comment]
Closing this for now. Please reopen if it has still something to do with 4.x/5.x
