### ISSUE TITLE
AOT Compiler:  StaticSymbols in summaries can't have members!

### ISSUE THREAD

**Issue by PFight** [angular/angular#14266]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If we import module class, that was exported via `export * as Test from '...'`, and then uses Test.TestModuel in `imports` statement, ngc produces error `StaticSymbols in summaries can't have members!`.

If we add middle way object in export, no error occured (see minimal example side way).

Is not dublicate of [this](https://github.com/angular/angular/issues/14063)!

**Expected behavior**

No error should occur when using correct es6 import/export syntax.

**Minimal reproduction of the problem with instructions**

[https://github.com/PFight/ngc-static-symbols-members-bug](https://github.com/PFight/ngc-static-symbols-members-bug)

**What is the motivation / use case for changing the behavior?**

Using expression `export * as BlaBla from '..'` can solve problem of thousands of dots like `import { BlaBla} from '../../../../../Test/TestModule'`. Just make order of imports and exports of modules with special files. See [my starter](https://github.com/PFight/angular-gulp-starter) for example.

**Please tell us about your environment:**

Windows 8.1, npm 3.10.8

* **Angular version:** 2.4.6
* **Angular-compiler-cli version:** 2.4.6

 
* **Language:** TypeScript 2.1.5

* **Node (for AoT issues):** `node --version` =   
v6.9.1

**Comment by XAMelleOH** [comment]
👍

**Comment by arvind-das** [comment]
I got the same 

> node_modules/.bin/ngc -i tsconfig.i18-ao
t.json
Error: Internal state: StaticSymbols in summaries can't have members! {"filePath":"/home/neuron/Documents/typescrip
t_projects/kairosUI/node_modules/daypilot-pro-angular/daypilot-angular.min.d.ts","name":"DayPilot","members":["Angu
lar","Scheduler"]}
    at AotSummaryResolver._assertNoMembers (/home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angul
ar/compiler/bundles/compiler.umd.js:26300:23)
    at AotSummaryResolver.resolveSummary (/home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angular
/compiler/bundles/compiler.umd.js:26308:18)
    at CompileMetadataResolver._loadSummary (/home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angu
lar/compiler/bundles/compiler.umd.js:18032:70)
    at CompileMetadataResolver.getNgModuleSummary (/home/neuron/Documents/typescript_projects/kairosUI/node_modules
/@angular/compiler/bundles/compiler.umd.js:18226:56)
    at /home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angular/compiler/bundles/compiler.umd.js:1
8318:72
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/home/neuron/Documents/typescript_projects/kairosUI/node_module
s/@angular/compiler/bundles/compiler.umd.js:18313:53)
    at addNgModule (/home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angular/compiler/bundles/comp
iler.umd.js:25053:62)
    at /home/neuron/Documents/typescript_projects/kairosUI/node_modules/@angular/compiler/bundles/compiler.umd.js:2
5064:18
    at Array.forEach (native)
Compilation failed


Did you guys find a solution ?

Please let me know.
Thanks

**Comment by fopnet** [comment]
my example has the same error! 
in JIT mode, it works fine, but in AOT compilation returns the StaticSymbols in summaries can't have members!

There are there cases in app.routing.ts to simulate the problem, but my interested case is case 2

[my sample is here](http://plnkr.co/edit/r1Gvw5idBweW6PyoaLpI?p=preview)

**Comment by interimproj** [comment]
I also have this problem!

**Comment by DzmitryShylovich** [comment]
@PFight could you try it out with angular4?

**Comment by PFight** [comment]
On angular 5.2.5 repro, but changed error message:

    $ "./node_modules/.bin/ngc"
    : Unexpected value 'Test in C:/Main/Work/ngc-static-symbols-members-bug/app/app-imports.ts' imported by the module 'AppModule in C:/Main/Work/ngc-static-symbols-members-bug/app/app.module.ts'. Please add a @NgModule annotation.

Workaround still works.

**Comment by JoostK** [comment]
This is no longer an issue in Ivy!
