### ISSUE TITLE
Angular 1 unit tests fail with Angular 2 components using downgradeComponents

### ISSUE THREAD

**Issue by Rhathe** [angular/angular#14263]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

We are using the current documented way of downgrading Angular 2 components with the `UpgradeModule` for use in an Angular 1 hybrid app, specifically an angular 1 component. We have unit tests that uses `$compile` to create an element with our angular 1 component which itself uses a downgraded angular 2 component, which is downgraded with `downgradeComponent` in the static upgrade as opposed to the one in `UpgradeAdapter`. This works with interacting with the app in the browser. However, an error pops up in the unit test that says `Error: [$injector:unpr] Unknown Provider $$angularInjectorProvider`.

The error was previous documented here:
http://stackoverflow.com/questions/41128236/angular-2-unknown-provider-angularinjectorprovider-when-unit-testing-with

A possible hacky solution here was to call `beforeEach(angular.mock.module('$$UpgradeModule'))`. While the error is gone, the unit tests still fail because changes are not being detected in the downgraded angular 2 component.

There seems to a fix in 2fc056098804e660a6788802291fd99a979ef62e that fixed the issue in #5462, but that is for the `UpgradeAdapter` and not for `UpgradeModule`.

**Expected behavior**

Existing angular 1 unit tests should be able to test angular 1 components that have angular 2 downgraded components without failing.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jwoos** [comment]
I have also experienced this issue

**Comment by sshev** [comment]
I have the same problem when trying to unit test ng1 services that have ng2 dependencies registered with `downgradeInjectable()`
have to mock such ng2 dependencies in order to make existing tests pass, which makes migration from ng1 to ng2 more painful

**Comment by dkanev** [comment]
+1

**Comment by ronwang01** [comment]
+1

**Comment by djpark** [comment]
+1

**Comment by idoglik6** [comment]
+1

**Comment by bh86** [comment]
+1

**Comment by ninaneter** [comment]
+1

**Comment by moanrose** [comment]
+1

**Comment by amosuro** [comment]
+1 the documentation is great but this issue is making the idea of gradually migrating to Angular very difficult.

**Comment by nikolay-lesko** [comment]
+1

**Comment by gkalpak** [comment]
For the time being, the simplest approach is to bootstrap a "mini hybrid app" for each test (which is less than ideal for several reasons). Testing with ngUpgrade will be improved much once #16848 is merged :smiley:

**Comment by gkalpak** [comment]
I am going to close this. Let's track the test helpers for ngUpgrade in #16848.
