### ISSUE TITLE
[upgrade/static] Support targeted projection

### ISSUE THREAD

**Issue by youdz** [angular/angular#14261]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, statically downgraded Angular components (with `@angular/upgrade/static`) project all their content into the first `<ng-content>`, completely ignoring its `select` attribute. This is not the case for dynamically downgraded components (with `@angular/upgrade`), but was not ported to the new upgrade solution.

**Expected behavior**

Statically downgraded components should still project their content into the correct slots, based on the `select` attribute of the `ng-content` tags.

**Minimal reproduction of the problem with instructions**

Dummy component that only projects:
http://plnkr.co/edit/w0yGlAsadJ97LiIP3AMJ?p=preview

**What is the motivation / use case for changing the behavior?**

It makes it impossible for people using the targeted projection feature, supported by the previous version of the Upgrade Adapter, to move to the new static upgrade paradigm.

* **Angular version:** 2.4.X

* **Browser:** all

 
* **Language:** all

**Comment by petebacondarwin** [comment]
How about that for a turnaround: #14282?

**Comment by youdz** [comment]
Hahaha, awesome, thanks! 😄 
I need to learn these jedi mind tricks too, to anticipate requests before they come in. 😛
