### ISSUE TITLE
Jsonp error `Uncaught ReferenceError: __ng_jsonp____req0_finished is not defined` after https://github.com/angular/angular/pull/13219

### ISSUE THREAD

**Issue by doxiaodong** [angular/angular#14267]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

hello, after upgrade to 2.4.6, I get `Uncaught ReferenceError: __ng_jsonp____req0_finished is not defined` as https://github.com/angular/angular/pull/13219#discussion_r90797936
![image](https://cloud.githubusercontent.com/assets/6927481/22582776/cda6014e-ea23-11e6-87dc-2b945667eefe.png)

**Plunkr**
http://plnkr.co/edit/WcRnPrJHa04rJy3xTIky?p=preview

And my code is
```
search(key: string) {
  const params = new URLSearchParams()
  params.set('key', key)
  params.set('jsonpCallback', 'JSONP_CALLBACK')
  return this.jsonp.get('https://c.y.qq.com/splcloud/fcgi-bin/smartbox_new.fcg?' + params)
  .toPromise()
  .then(res => {
    console.log(res)
    return []
  })
}
```

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr with repro

**Comment by doxiaodong** [comment]
@DzmitryShylovich , done

**Comment by DzmitryShylovich** [comment]
Callback must have dot before finished `__ng_jsonp____req0.finished`

**Comment by doxiaodong** [comment]
@DzmitryShylovich , I make a simple pr to fix. If you have a better way, close this.

**Comment by DzmitryShylovich** [comment]
I'll take a look thx

**Comment by DzmitryShylovich** [comment]
btw discussion about dot in callback names from ng1 https://github.com/angular/angular.js/issues/1551#issuecomment-48765163

**Comment by DzmitryShylovich** [comment]
Ok I think I have a better solution.
First of all we need to revert https://github.com/angular/angular/commit/9e5617e41e222d29c3952ba71a401804030cd153 commit.

I don't like the idea to pollute global namespace by default. So we should expose `BrowserJsonp` as a DI token so users can provide their own implementation with their own callback names etc.

@mhevery what do you think about that?

**Comment by dejour** [comment]
but implementation function name is always `finished`.so i think `JSONPCALLBACK` is fine. all user care about is returned data.

**Comment by DzmitryShylovich** [comment]
@dejour callback name must end with `.finished`. Some apis don't allow callback names with dots. To avoid dots we need to add callbacks directly to `window`.

**Comment by doxiaodong** [comment]
Greate, I make an example with no dot about @DzmitryShylovich 's pr.
1. make `custom-browser-json.ts`
```
import { BrowserJsonp } from '@angular/http'

function getJsonpCallbackName(id: string): string {
  return `__custom__ng__jsonp${id}__`
}

export class CustomBrowserJsonp extends BrowserJsonp {
  requestCallback(id: string): string {
    return getJsonpCallbackName(id)
  }

  exposeConnection(id: string, connection: any): void {
    window[getJsonpCallbackName(id)] = connection.finished.bind(connection)
  }

  removeConnection(id: string): void {
    window[getJsonpCallbackName(id)] = null
  }
}

```
2. in you module
```
import { BrowserJsonp } from '@angular/http'
import { CustomBrowserJsonp } from './custom-browser-json'

@NgModule({
  providers: [{
    { provide: BrowserJsonp, useClass: CustomBrowserJsonp }
  }]
})
export class AppModule { }
```

**Comment by Klerith** [comment]
What is the status of this issue? 
I have the same problem using jsonp module

![image](https://cloud.githubusercontent.com/assets/3438503/22802705/822079e4-eed7-11e6-9db5-c23bf52ab4c3.png)


![image](https://cloud.githubusercontent.com/assets/3438503/22802718/8f805064-eed7-11e6-83a5-e18bcb7c4169.png)

**Comment by DzmitryShylovich** [comment]
@Klerith will be fixed in the next release. Use `2.4.5` version of http module

**Comment by Klerith** [comment]
Thank you for the super fast reply @DzmitryShylovich ,

But for my bad luck, still doesn't work, I update to @angular/http@2.4.7, even delete and make the npm to recreate that folder, but still get the same error.

Or maybe I am doing something wrong, ( I am using Angular-CLI "version": "1.0.0-beta.28.3")

Thank you for anything you can tell me

![image](https://cloud.githubusercontent.com/assets/3438503/22803725/bbd6818e-eedb-11e6-8b5e-8681c6b8a9fa.png)

**Comment by DzmitryShylovich** [comment]
@Klerith he bug was introduced in 2.4.6. So you need to use 2.4.5

**Comment by Klerith** [comment]
@DzmitryShylovich, If you live in Costa Rica, I will invite you to a good coffee for this excellent support.

I will use that HTTP version (2.4.5) until I the next release comes out.

Thank you so much! That fixed my issue.

**Comment by gastikirs** [comment]
@DzmitryShylovich Great! 
With @angular/http 2.4.5 jsonp requests work.

**Comment by DzmitryShylovich** [comment]
@doxiaodong the commit that caused this bug was reverted so it can be closed

**Comment by doxiaodong** [comment]
close

**Comment by erneledesma** [comment]
Hi all! I have the following problem to want to make the request .. I do not realize about the error..
I appreciate any suggestions
![captura de pantalla 2019-02-12 a la s 20 22 23](https://user-images.githubusercontent.com/1206862/52676051-88ecaf00-2f07-11e9-9ecd-ebb3abbdfeac.png)
![captura de pantalla 2019-02-12 a la s 20 22 43](https://user-images.githubusercontent.com/1206862/52676052-88ecaf00-2f07-11e9-9da4-5c1f4a115b6d.png)
![captura de pantalla 2019-02-12 a la s 20 34 18](https://user-images.githubusercontent.com/1206862/52676152-e680fb80-2f07-11e9-9270-56796f1e2e67.png)
