### ISSUE TITLE
Routing loop in canActivate() makes browsers crash

### ISSUE THREAD

**Issue by esbeto** [angular/angular#14262]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When routing to a guarded route, which in turn routes to the same component makes Chrome and Firefox Crash.

**Expected behavior**
Throw exception error.

For example: Safari doesn't crash and displays the following error message:

```
EXCEPTION: Uncaught (in promise): SecurityError (DOM Exception 18): Attempt to use history.replaceState() more than 100 times per 30.000000 seconds
replaceState@[native code]
replaceState
replaceState
replaceState
resetUrlToCurrentUrlTree

onInvoke
run@https://unpkg.com/zone.js@0.7.6/dist/zone.js:113:49
https://unpkg.com/zone.js@0.7.6/dist/zone.js:535:60
invokeTask@https://unpkg.com/zone.js@0.7.6/dist/zone.js:275:40
onInvokeTask
invokeTask@https://unpkg.com/zone.js@0.7.6/dist/zone.js:274:52
runTask@https://unpkg.com/zone.js@0.7.6/dist/zone.js:151:57
drainMicroTaskQueue@https://unpkg.com/zone.js@0.7.6/dist/zone.js:433:42
invoke@https://unpkg.com/zone.js@0.7.6/dist/zone.js:349:44
```

This bug doesn't affect router v3.2.3 it fails silently.

**Minimal reproduction of the problem with instructions**
 *DEMO*
*Warning: clicking Navigate to Component 2 will crash Chrome, Firefox*
https://plnkr.co/edit/GHqAYiKRuhIxhE8qP4h4

*Steps to reproduce*
1. Configure a route with canActivate guard:
```
        {
          path: 'component',
          component: Component,
          canActivate: [Guard]
        }
```

2. redirect to same route within guard:
```
    canActivate() {
        if (true) {
          this.router.navigate(['/component']);
          return true;
        }
        return false;
    }
```

3. navigate to said route.

**What is the motivation / use case for changing the behavior?**
canActivate is used to protect routes.

Sometimes this protection can route users to two different options. For example:
option a) Paywall
option b) Content

If you navigate to content and canActivate discriminates you as a user that should be able to access content, it can route you to the content route, making a redirect loop. 

**Please tell us about your environment:**
MacOS, Chrome 55. Firefox 51. Safari 10

* **Angular version:**
Angular 2.3.1
Router 3.3.1
This bug apparently doesn't affect router v3.2.3 it fails silently.

* **Browser:**
Chrome 55. Firefox 51.
 
* **Language:**
Typescript 2.0.3

* **Node (for AoT issues):** `node --version` =   
node v7.4.0

**Comment by bruno-serfe** [comment]
Hey guys, I'm running angular 2.4.9, is that fixed in that version?
I've the same issue, when I'm trying to redirect stays in a loop.

**Comment by DzmitryShylovich** [comment]
Don't see ` "bug" here. It crashes browser like any other infinite loop

**Comment by bruno-serfe** [comment]
I'm trying to allow access to /sign-up route, currently I've /login path without "canActivate" param in route.
The other paths (those that requires the user to be logged) has "canActivate" handler, but when I'm trying to access to sign-up route, always I'm redirected to previous path, for example /login

And doing something like this

 canActivate() {
        if (true) {
          this.router.navigate(['/sign-up']);
          return true;
        }
        return false;
    }

is not redirecting me to the /sign-up path, instead of that, the app crash in an infinite loop..
is not this an error in Angular?

**Comment by DzmitryShylovich** [comment]
> Warning: clicking Navigate to Component 2 will crash Chrome, Firefox
https://plnkr.co/edit/GHqAYiKRuhIxhE8qP4h4

 click on `routeChange` (this.router.navigate(['/two'])) => guard => this.router.navigate(['/two']) => guard => this.router.navigate(['/two']) etc.

**Comment by bruno-serfe** [comment]
Disregard my last comment I've found the issue, there was in the OUTER and INNER routes.

I've implemented something like this:

const OUTER_ROUTES = [
  { path: 'login', component: LogInComponent},
  { path: 'sign-up', component: SignUpComponent},
];

export const ROUTES = [
  {
    path: '',
    children: [
      ...OUTER_ROUTES
    ]
  },
  {
    path: '',
    canActivate: [AccessGuard],
    children: [
      ...INNER_ROUTES,
    ],
  },

Thank you so much for your help .

**Comment by esbeto** [comment]
I'm closing this now

**Comment by arusakov** [comment]
I have faced the same problem in 4.0.3: `router.navigateByUrl()` in `canActivate` handler.
Why router doesn't have protection against "navigation to the same url twice"? Or there are some reasons?

**Comment by Massay** [comment]
I had the same issue in version 5.1.1. Am using the do observable operator for the redirection  and it some times runs endless and crashes my browser
`
canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): Observable<boolean> | Promise<boolean> | boolean {
      return this.userService.isAuthenticated.take(1).map(bool => !bool).do( data => {
            console.log(' no auth guard value => ', data);
            if (!data){
                // this.router.navigate(['/home']);
            }
      } );
  }
`

**Comment by catonice** [comment]
Found my AuthComponent had an AuthGuard in the routing module which caused the infinite loop on my side - removed the guard and fixed! Leaving this comment for others!
