### ISSUE TITLE
getValue from  route params

### ISSUE THREAD

**Issue by ar53n** [angular/angular#14271]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Error for method this.route.params.getValue(param);

**Expected behavior**
This method not declare can i use this method?

**Please tell us about your environment:**
Work in Visual Studio Code

* **Angular version:** 2.4.2

 
* **Language:** [ TypeScript]

**Comment by DzmitryShylovich** [comment]
what is `getValue`?

Params is an observable:
`this.route.params.subscribe(params => ...)`

**Comment by dawidgarus** [comment]
Why not `this.route.snapshot.params`?

**Comment by ar53n** [comment]
@dawidgarus because sometimes this params find in `this.route.parent.snapshot.params`

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
