### ISSUE TITLE
HammerGesturesPlugin calls ApplicationRef.Tick too ofthen.

### ISSUE THREAD

**Issue by vdolbnya** [angular/angular#14272]
I'm using HammerJs in my Angular2 application to handle [press] event in some UI elements that are shown very rarely.

I have faced with performance issues with my application in Android tablets and when have started profile it with using Chrome Dev tools in touch device emulation I have observed performance degradation even on PC.

I found that processing of each click of button (I handle [Click] event, not hammer events) produces  up to 24 ApplicationRef.Tick calls. When I clicking same button without touch device emulation, amount of ApplicationRef.Ticks' is reduced to 6.

I have found a cause of this behavior. HammerGesturesPlugin have following lines of code:
```js
      HammerGesturesPlugin.prototype.addEventListener = function (element, eventName, handler) {
          var _this = this;
          var /** @type {?} */ zone = this.manager.getZone();
          eventName = eventName.toLowerCase();
          return zone.runOutsideAngular(function () {
              // Creating the manager bind events, must be done outside of angular
              var /** @type {?} */ mc = _this._config.buildHammer(element);
              var /** @type {?} */ callback = function (eventObj) {
                  zone.runGuarded(function () { handler(eventObj); });
              };
              mc.on(eventName, callback);
              return function () { return mc.off(eventName, callback); };
          });
      };
```
problem is that after each zone.runGuarded call following code is called 
```js
            this._zone.onMicrotaskEmpty.subscribe({ next: function () { _this._zone.run(function () { _this.tick(); }); } });
```
So as I understand even if user is not subscribed on [touchstart],[touchent] and other events of particular div, ApplicationRef.Ticks will be called a lot of times when application is working on touch screen.

and when I have replaced the line 
`
  zone.runGuarded(function () { handler(eventObj); });
`
by
`
 zone.runOutsideAngular(function () {handler(eventObj); });
`

Problem was solved, then I have tested my HammerJs  flows and they were not broken.

Sure I understand that there is a reason why zone.runGuarded is called. Also I understand that problem is also that some changes are detected during  ApplicationRef.Tick handing when screen is not actually changed. As I see  in ideal situation ApplicationRef.Tick should do nothing if screen is not changed. 

I have profiled and eliminated some of places when changes were detected during this flow but not all and also I understand that if somebody will accidentally introduce more of these places - performance on tablets will be degraded much more that on desktop version (and obviously performance is much more critical on tablets then on desktop)

I think about following solutions:

1) Introduce a way to somehow override the addEventListener  method of HammerGesturesPlugin to run event handler outside Angular
2) Somehow add hammer event listners only for DOM elements when I really need it (in this case only click on these elements will produce extra  ApplicationRef.Ticks and performance of remaining UI will be the same as on desktop.

Could you please explain how to implement one of them provide more suitable solution of my case if it is exists?

**Comment by vicb** [comment]
What the hammer plugin does:
1. "// Creating the manager bind events, must be done outside of angular" so that mouse-move events on the like do not trigger the change detection,
2. Run the "final" event handler in the zone so that the CD is executed after the handler.

There is little we can do without a repro. I you think there is a real bug please re-open an issue with a small code example. If you are looking for help use the support channels. Thanks.

**Comment by vdolbnya** [comment]
Hello, Victor, 
Thank you for answer, you are right, I have found several subscriptions document:touchstart and document:tap events, (that have produced ApplicationRef.Tick's) that I have missed before.
