### ISSUE TITLE
White screen of death.

### ISSUE THREAD

**Issue by KingsDevelopment** [angular/angular#14273]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After building or compiling (both AOT enabled), the screen sometimes just turns white, the app component is loaded, and there is no error in the console. After I hit reload like 6 times or ctrl+shift+f5 (usually clear cache etc), the app runs once, and after that it's white screen again. As if the router does not match any routes any more. I got a visual representation of the problem in a video: https://www.youtube.com/watch?v=Ko_LHDe0mIM

**Expected behavior**
Load the full application every time.

**Minimal reproduction of the problem with instructions**
It's very hard for me to give you a working plunkr or repo with the problem, as this is a private project of the company and I have no idea where this is coming from, you might want to try if the problem happends on https://superbuddy.nl (most frequently happends on mobile phones)

**What is the motivation / use case for changing the behavior?**
Our customers are having this problem, on both mobile & desktop on a build version of the application in production mode using AOT.

**Please tell us about your environment:**
Using our own docker image: https://hub.docker.com/r/superbuddy/ng-cli-nginx/

* **Angular version:** 2.0.X
```
angular-cli: 1.0.0-beta.28.3
node: 6.9.1
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/compiler-cli: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@ngtools/webpack: 1.2.6
```

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by DzmitryShylovich** [comment]
Don't think we can do much without reproduction.

Do use use router guards/resolvers?

**Comment by KingsDevelopment** [comment]
I do use guards, but not on the particular page I am showing (landing page)

**Comment by DzmitryShylovich** [comment]
do you use template or templetUrl? how do you build you project?

**Comment by KingsDevelopment** [comment]
build command: `ng build -prod --aot | tee /build.log`

Yes, usually `templateUrl`, except for the `AppComponent` as it consists of just 4 tags

**Comment by KingsDevelopment** [comment]
I could give one the repo, but rather in personal ways and with a ssh key.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by KingsDevelopment** [comment]
I do not agree, as the lazy loaded routes are not loading when running from cache.

**Comment by vicb** [comment]
If you can reproduce the issue on a small example we can investigate - re-open an issue when you have such a repro available
