### ISSUE TITLE
problem with ngFor and iterables

### ISSUE THREAD

**Issue by tonai** [angular/angular#14275]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm using an ngFor directive over an iterable object.
I add some content into the iterable and the ngFor updates correclty.
Then I update an oher part of my app and the ngFor disappear while the iterable has not been updated.

**Expected behavior**

The ngFor should update with the content of the iterable.

**Minimal reproduction of the problem with instructions**

Here is a plunker : https://plnkr.co/edit/bRlrmJJ4voltArRZy5tF
1. Click "Add message"
2. Click "Update"
3. Click "Add message"
4. ...etc.

**What is the motivation / use case for changing the behavior?**

ngFor should be compatible with iterable.
**Note:** ngFor do work correctly when replacing the iterable with an array.

**Please tell us about your environment:**

* OS : Ubuntu 14.04
* Project initialized with the angular cli
* **Angular version:** 2.4.6

* **Browser:** Tested with [ ~~all~~ | Chrome 55 | Firefox 51 | ~~IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView~~ ]

 
* **Language:** [ ~~all~~ | TypeScript 2.0.10 | ~~ES6/7 | ES5~~ ]

**Comment by DzmitryShylovich** [comment]
@tonai `Map.values()` returns an `Iterator` rather than an `Iterable`. Iterators are not supported as you can see [here](https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/core/src/change_detection/differs/iterable_differs.ts#L17). Only arrays and iterables.

**Comment by tonai** [comment]
@DzmitryShylovich Ok I think that make sense.
Thank you for your help
