### ISSUE TITLE
Create a dynamic template,component and pipe based on JSON received

### ISSUE THREAD

**Issue by tremolet** [angular/angular#14280]
I would like to create a generic template based on received data in PHP by the server and then converted in JSON by an Angular 2 service

If my PHP data sent by the sever looks like this :

`return array('title'=>'Generic title','headers'=>array(array('label'=>'Price','type'=>'number'),array('label'=>'Date of..','type'=>'date'));`

And have in my template:

```
<h1>Generic title</h1>
<table>
 <thead>
  <th>Price</th>
  <th>Date of..</th>
 </thead>
 <tbody>
  <tr *ngFor="let data of content | selectorPipeName:priceValue:minDateOf:maxDateOf">
    <td *ngFor="let cell of data"> ->in that case,2 td tags
       {{cell}} ->this can also change according if it's a date,number etc.. for the format,etc,if it's a boolean,whatever 
    </td>
   </tr>
 </tbody>
</table>
```

And have filters:

```
<input type="text" [value]="priceValue"(keyup)="changePrice($event.target.value)">
<input type="date" [value]="minDateOf" (input)="changeDateMinOf($event.target.value)">
<input type="date" [value]="maxDateOf" (input)="changeDateMaxOf($event.target.value)">

```
And have the generated component(models,functions),pipe for the filters,just by having the JSON data.

Do you think it's possible ? I don't know in advance how many filters there will be,and what type(radio,etc...) will it be...I want it to be generic but i don't know if there is a way

Best

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by tremolet** [comment]
Oups,ok sorry ! Done
