### ISSUE TITLE
[upgrade/static] ChangeDetectionStrategy.OnPush - input change doesn't induce change check

### ISSUE THREAD

**Issue by sebek64** [angular/angular#14286]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

A downgraded component with OnPush change detection strategy is used in an ng1 component. Changes to the component inputs are completely ignored.

This occurs only in upgrade mode. Workarounds:
* disable OnPush,
* use setter method and call changeDetectorRef.markForCheck() in the setter

**Expected behavior**

Change to input property should induce a change detection check.

**Minimal reproduction of the problem with instructions**

Here is a plunker demonstrating that:

https://plnkr.co/edit/2ysh3ddan7aD3tfntDZ4

and a plunker without upgrade:

https://plnkr.co/edit/8fzk7Ftkivka18F3esS3

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.6

* **Browser:** Chrome | all

 
* **Language:** TypeScript 2.1

* **Node (for AoT issues):** `node --version` =

**Comment by gkalpak** [comment]
As explained [here][1], this is indeed a bug/limitation. At this point it is better to wait for the new View Engine to land in v4 and then address it there (if it is still broken).

[1]: https://github.com/gkalpak/angular/commit/fe11346cae57dd7c0f4417c8c8e0cb3c07956b3f#commitcomment-20786114

**Comment by sebek64** [comment]
I've just tested it in angular 4-rc1 and the problem is still there. According to changelog, the new view engine is already there. So maybe the next few weeks is a good time to fix this to get it into final 4.

**Comment by masterkidan** [comment]
Any update on this issue?

**Comment by gkalpak** [comment]
@mhevery, is this something that we could/should support now?
(See https://github.com/gkalpak/angular/commit/fe11346cae57dd7c0f4417c8c8e0cb3c07956b3f#commitcomment-20786114 for previous discussion.)
