### ISSUE TITLE
Getting Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by born2net** [angular/angular#14297]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Erroring in console

```
(CONTENT_SCRIPT context for lmhkpmbekcpmknklioeibfkpmmfibljd) Lazy require of extension.binding did not set the binding field
(CONTENT_SCRIPT context for lmhkpmbekcpmknklioeibfkpmmfibljd) extensions::lastError:82: Uncaught TypeError: Cannot convert undefined or null to object{TypeError: Cannot convert undefined or null to object
    at Object.clear (extensions::lastError:82:23)
    at handleResponse (extensions::sendRequest:84:15)
    at chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/pagewrap.bundle.js:1:1}
(CONTENT_SCRIPT context for lmhkpmbekcpmknklioeibfkpmmfibljd) extensions::messaging:9: Uncaught Natives disabled{<stack trace unavailable>}
Uncaught
  (anonymous function)	
Service Worker registered
NgmslibService constructed
running in dev mode: true
App loaded and ready
Angular is running in the deve
```

**Expected behavior**
no error

**Minimal reproduction of the problem with instructions**
Using repo: https://github.com/born2net/studioweb

versions:
```
@angular/cli: 1.0.0-beta.30
node: 6.9.5
os: win32 x64
@angular/cli: 1.0.0-beta.30
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/language-service: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.6
@ngtools/webpack: 1.2.8
```

seems to be related to WebStorm debugger and Redux dev tools...

**Comment by kumargandhi** [comment]
Having same issue, any solution found?.

**Comment by DzmitryShylovich** [comment]
@born2net did you find the issue?

**Comment by born2net** [comment]
unfortunately no :(
still same problem

**Comment by kumargandhi** [comment]
@angular/cli: 1.0.0-beta.30 adds version 2.4.0 @angular dependencies and i changed them to 2.4.6 (not sure if that makes any difference).

Anyhow i was able to solve this run-time error by doing build with-out --prod flag.
Changing >ng build --prod to >ng build.
This worked for me for now. 
I will need to come back sometime soon and investigate more.

**Comment by born2net** [comment]
I run ```ng serve --port 4208 --aot false``` and same issue

**Comment by zalmoxisus** [comment]
I just published Redux DevTools Extension `2.14.0`, which includes a fix for this issue. Just update it from Chrome Store.

As discussed in https://github.com/gaearon/redux-devtools/issues/338, it's an issue with Webstorm's extension (I was able to replicate in `2017.1 EAP`, but not in earlier versions). Somehow it blocks `chrome.sync.get` as described in http://stackoverflow.com/questions/41197282/chrome-extension-storage-sync-set-in-content-script-throws-exception. I can replicate it with an extension which does nothing except calling `chrome.sync.get`. Anyway we were planning to deprecate [storing users options](https://github.com/zalmoxisus/redux-devtools-extension/issues/296).

**Comment by born2net** [comment]
thanks soooooooo much
will test asap

**Comment by born2net** [comment]
tx again, issue resolved!!!

**Comment by joseCocodin** [comment]
I forget return a promise in a $q.all and it was the problem.
