### ISSUE TITLE
Can't install @angular/core etc with npm.  Node 7.5.0, npm 4.1.2

### ISSUE THREAD

**Issue by sjatkins** [angular/angular#14296]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

npm install -S @angular/core@2.4.4
npm ERR! unpack Could not read data for @angular/core@2.4.4
npm WARN @angular/core@2.4.4 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.4 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN temp@1.0.0 No description
npm WARN temp@1.0.0 No repository field.
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-S" "@angular/core@2.4.4"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! Invalid name: "@angular/core"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /data/work/temp/npm-debug.log

**Expected behavior**

To install it as it in fact does on some of my other machines.  

**Minimal reproduction of the problem with instructions**

See the above. 
**What is the motivation / use case for changing the behavior?**

It doesn't work!
**Please tell us about your environment:**

Linux Mint very recent. 

* **Angular version:** 2.0.X

In the bug report

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 completely irrelevant.
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
irrelevant. 
* **Node (for AoT issues):** `node --version` =   
npm -v
4.1.2
node -v
v7.5.0

**Comment by sjatkins** [comment]
odd.  I built node from source and got the above.  i installed the same version via nvm and do not see the issue.  Very strange.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource support request

**Comment by sjatkins** [comment]
Closing and moving nvm vs fresh build discrepancy back to npm.  Sorry for the noise here.
