### ISSUE TITLE
Capture whether quotes have been used in template expressions

### ISSUE THREAD

**Issue by tbosch** [angular/angular#14292]
The following example fails when used with Closure compiler, as we don't record whether the user has used quotes or not in the expression in the template:

```
@Component({
  template: `<other-comp [someProp]="{'a': x}"></other-comp>`
})
class MyComp {}
```

A workaround is to put the object into the TypeScript code, e.g.
```
@Component({
  template: `<other-comp [someProp]="aObject(x)"></other-comp>`
})
class MyComp {
  aObject(x: any) { return {'a': x}; }
}
```

**Comment by austinrmiller** [comment]
Note it's supposed to be the quotes in the object:

[someProp]="{'a': x}"
aObject(x: any) { return {'a': x}; }

**Comment by rkirov** [comment]
@austinrmiller, I fixed the issue description.

@tbosch Correct me if I am wrong, but if the original expression is static - `{'a': 'b'}` the workaround will have a slight difference that it will recreate the object at each change detection pass.

**Comment by DzmitryShylovich** [comment]
> [someProp]="{'a': x}"

also creates a new object  at each change detection pass (if I understood your question correctly)

**Comment by rkirov** [comment]
With `{'a': x}` in the template I see `pureProxy1` being used in the aot generated code - https://github.com/angular/angular/blob/c33fda260726f5c050a75fc01fbd7a74800f8e37/modules/%40angular/core/src/linker/view_utils.ts#L183

Thus the object is recreated only when `x` changes (further optimization can keep the object around too). With the workaround it is recreated on each check, considered changed and repopulated in the DOM.

**Comment by DzmitryShylovich** [comment]
> Thus the object is recreated only when x changes

yeah, you are right.

> With the workaround it is recreated on each check, considered changed and repopulated in the DOM.

```
class MyComp {
  private _myObj = {'a': x};
  aObject(x: any) { return this._myObj  ; }
}
```
?

**Comment by dmitrysteblyuk** [comment]
Any updates on this? Because of this issue all properties passed to ngTemlateOtletContext are not available when you try to access them in ng-template. The only workaround is to create context in component class (with normal, not quote syntax, because in compiled code in ng-template context properties are accessed with dot syntax) and pass this context to ngTemplateOutlet. But this is rarely used and passing variables in template more common:

```<ng-container *ngTemplateOutlet="someTemplate; context: { ...template variables here }"></ng-container>```

**Comment by tbosch** [comment]
This bug seems to be even worse:

1. for actions, we seem to always strip quotes: We are just creating an `o.literalMap` which defaults to using no quotes for property names (see [here](https://github.com/angular/angular/blob/master/packages/compiler/src/compiler_util/expression_converter.ts#L40))
2. for property bindings, we generate calls to `pureObjectDef`, which takes an array of property names (see [here](https://github.com/angular/angular/blob/master/packages/core/src/view/pure_expression.ts#L21)). As we captured the property names during compilation, they won't get renamed.

**Comment by tbosch** [comment]
Idea for the solution in `pureObjectDef`: Change it to receive an object literal, where we only use the keys. This way, closure compiler can also minify the property names. We already do this in other places in the view engine too...
