### ISSUE TITLE
*ngFor with `{}` blank objects are referring to single reference when collection defined on template

### ISSUE THREAD

**Issue by pankajparkar** [angular/angular#14302]
[x ] bug report

**Current behavior**

I've requirement where I'm displaying series of text box with Initial blank data. So for the same I created one array with 3 blank `[{},{},{}]`. Then I did loop over each element and displayed on view using `*ngFor`

    <div *ngFor="let item of [{},{},{}]">
        {{item.Id}}
        <input type="text" [(ngModel)]="item.Id">
    </div>

Above render my all text boxes correctly, but when I try to change any of input element, all textboxes refers to same reference.

[Problem Plunker](http://plnkr.co/edit/gbhfxFk5kDIArYROEnYQ?p=preview)

**Expected behavior**

I'm expecting to change the particular `item` object `Id` property. 

**What is the motivation / use case for changing the behavior?**

I know I can move array declaration inside my component class(though that's solves my issue), I'm curious to know whats wrong with array declaration on template? 

**Reference**
Logged [Stackoverflow issue](http://stackoverflow.com/questions/42039478/ngfor-with-blank-objects-are-referring-to-single-reference-when-collection)

**Comment by returnlytom** [comment]
Also having an issue with nested children components in an ngFor getting the same reference to a single object in the driving array. Will see if I can extract the relevant code into a plunker for further debugging and possibly supplementing this issue.

**Comment by DzmitryShylovich** [comment]
@returnlytom did you use custom `trackBy` function?

**Comment by returnlytom** [comment]
@DzmitryShylovich here's the relevant template snippet:

```
<div *ngIf="dataLoaded">
  <product-card *ngFor="let product of products; trackBy: trackProductBy" [product]="product"></product-card>
</div>
```
and have tried both without a `trackBy` and with the following:

```
  trackProductBy(index: number, product: Product): number {
    return product.order_line_id;
  }
```

```
  trackProductBy(index: number, product: Product): number {
    return index;
  }
```

What started me on this wild goose chase - when I render `{{ product.order_line_id }}` in the child template, it displays the correct unique values in the DOM. But when accessing the `product` after a click event on one of the children, it always references the first `product` in the `products` array.

Working on a plunker now to see if I can isolate the problem (and determine if it's "user error" :) ).

**Comment by returnlytom** [comment]
Able to reproduce this, here's a plunker with the behavior I'm experiencing:

http://plnkr.co/edit/e1KwSpVa1nKE6GW1CTdA?p=preview

Try clicking on the radio inputs in each of the products and observe the debug and console output. Maybe the `onClick` is causing the issue? In my actual app, I'm using the click handler to update the state-tracking BehaviorSubject in my StateService.

FWIW, also experiencing this issue on the latest beta (what I'm using in my local development).

**Comment by DzmitryShylovich** [comment]
@returnlytom radios have the same `id` http://prntscr.com/e4kw3q
I think this is the origin of your issue

**Comment by returnlytom** [comment]
@DzmitryShylovich that did the trick, thanks!! 👍

**Comment by pankajparkar** [comment]
I don't understand why this issue got closed? I haven't got any explanation regarding what I've asked for.

**Comment by DzmitryShylovich** [comment]
@pankajparkar 
> I know I can move array declaration inside my component class(though that's solves my issue), I'm curious to know whats wrong with array declaration on template?

compiler creates a single object for `[{},{},{}]`. this is why when you type into 1 input it affects all 3 inputs. Looks like pref optimization. 
You can fix it by adding some props to the objects. For example, `[{id: 1},{id: 2},{}]`. In this case compiler will create 3 different objects.

**Comment by pankajparkar** [comment]
@DzmitryShylovich Thanks for explanation. The example you gave `[{id: 1},{id: 2},{}]` works perfect.
Interestingly from `[{},{id: 2},{}]` this object 1st and 3rd object refers to same object.

May I get source code line from Angular core/common/compiler where it is doing this all?

**Comment by DzmitryShylovich** [comment]
> Interestingly from [{},{id: 2},{}] this object 1st and 3rd object refers to same object.

yeah. Lookslike compiler uses the same object for all `{}` in a template

> May I get source code line from Angular core/common/compiler where it is doing this all?

I don't have a link. Parser and compile are not trivial.

**Comment by pankajparkar** [comment]
@DzmitryShylovich I got the same thought from @zoechi  on SO thread @zoechi  .. Thanks for your insight on it though ;)
