### ISSUE TITLE
Submitting the form after changing value in Angular2 submits old value

### ISSUE THREAD

**Issue by wpitallo** [angular/angular#14309]
**I'm submitting a ...**  (check one with "x")
```
[* ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a form that I load:

patchForm_LoadActiveObjectByStaticKey(key){
    this.locationService.loadActiveObjectByStaticKey(key).subscribe((result) => { 
    if(result){
         this.LOCATION_MODEL_OBJECT = result;
         this.LOCATION_MODEL_FORM.patchValue(this.LOCATION_MODEL_OBJECT);
        }
    });
}

This works correctly and I can see all the forms values as expected.

So province displays  "Loaded Province" in the UI

I then have a button on my form that I use to call the function clear keys:

  clearKeys(){
    this.LOCATION_MODEL.PROVINCE = "New Province";
  }

The UI is correctly updated and province now displays  "New Province"

Now I call submit and submit the form:

HTML:
<form Class="form-horizontal col-md-10" [formGroup]=" LOCATION_MODEL.LOCATION_MODEL_FORM"
      (ngSubmit)="LOCATION_MODEL.createUpdate(LOCATION_MODEL.LOCATION_MODEL_FORM.value)">

Component:

createUpdate(model){
    this.submitAttempt = true;
    if (this.LOCATION_MODEL_FORM.valid) {
        this.locationService.createUpdate(model).subscribe((result) => {this.LOCATION_MODEL_OBJECT = result });
    }
}

However the value I have  in my model is for model.province is "Loaded Province", I would expect this to be  "New Province".

Also, if I enter any value on the form before calling submit then it works and the model is updated and the value for model.province = "New Province"

I am guessing this is a bug?

**Expected behavior**
I would expect this to be  "New Province".

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr with repro

**Comment by wpitallo** [comment]
Do you have a plunker forms example setup with the latest angular2 version that I fork by any chance?

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by wpitallo** [comment]
Thanks :)

https://plnkr.co/edit/yo5NV5tlTLCfV1qFzeM5?p=preview

So:

1) Load Model
2) Change Values
3) Submit (Province is incorrect)

4) Enter a value into LOCATION
5) Submit (Province is now correct)

**Comment by DzmitryShylovich** [comment]
> Submit (Province is incorrect)

what do you mean by incorrect? Looks ok http://prntscr.com/e4qv5j

**Comment by dejour** [comment]
caused by `onlySelf` options

**Comment by wpitallo** [comment]
thanks removing the onlySelf worked 👍
