### ISSUE TITLE
RequestOptions is not merging  headers

### ISSUE THREAD

**Issue by Serginho** [angular/angular#14319]
**I'm submitting a ...**
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The problem is in http.ts file when options "are merged", well...that's the problem, headers are not merged.

```ts
function mergeOptions(
    defaultOpts: BaseRequestOptions, providedOpts: RequestOptionsArgs, method: RequestMethod,
    url: string): RequestOptions {
  const newOptions = defaultOpts;
  if (providedOpts) {
    // Hack so Dart can used named parameters
    return newOptions.merge(new RequestOptions({
      method: providedOpts.method || method,
      url: providedOpts.url || url,
      search: providedOpts.search,
      headers: providedOpts.headers,
      body: providedOpts.body,
      withCredentials: providedOpts.withCredentials,
      responseType: providedOpts.responseType
    }));
  }

  return newOptions.merge(new RequestOptions({method, url}));
}
```
If I extended de BaseRequestOptions class, add default headers like `"header1" => "foo"`, and create an http post request with header param `"header2" => "bar"`, the resulting headers map is `"header2" => "bar"`, so header1 disappears.
**Expected behavior**
Headers should be merged.
Expected code in that line:
```ts
headers: defaultOpts.headers.merge(providedOpts.headers),
```

Demo Plunker: https://plnkr.co/edit/skebbP6bqlVKFVSGoEyC
The first request GET send header Client: web, but if I add a new header as a param in get method, then DefaultHeader disappear.

**Comment by DzmitryShylovich** [comment]
If you already extend `BaseRequestOptions` then you can override `merge` method

**Comment by Serginho** [comment]
@DzmitryShylovich I updated the issue. I cannot override that mergeOptions function. Look at function params: 
`defaultOpts: BaseRequestOptions, providedOpts: RequestOptionsArgs` params enter, defaultOpts has base headers and providedOpts has the specific operation headers. But obly specific headers are applied. 
```ts
headers: providedOpts.headers,
```

**Comment by DzmitryShylovich** [comment]
could you add a plunkr with repro?

**Comment by Serginho** [comment]
@DzmitryShylovich 
Debug http.umd.js line 1707.

Demo Plunker: https://plnkr.co/edit/skebbP6bqlVKFVSGoEyC
The first request GET send header Client: web, but if I add a new header as a param in get method, then DefaultHeader disappear.

**Comment by Serginho** [comment]
Why does no one answer? there's no bounty here.

**Comment by DzmitryShylovich** [comment]
As I said you need to override `merge` method https://plnkr.co/edit/m0kNzctq3VWyZCZyMVhl?p=preview (impl can be improved but I have no time)

> The class name is clear: BaseRequestOptions, I think that means: "the minimal options that any request should have". But If I add a params with a new header, the base headers disappear. Doesn't make any sense.

base means that you can extend from it for your own impl

**Comment by Serginho** [comment]
@DzmitryShylovich Sorry, It made a mistake in the example, your code doesn't work with post method, look this plunkr https://plnkr.co/edit/H21gujRz74tKoOFvQ563

The problem is here:
```js 
    Http.prototype.post = function (url, body, options) {
        return this.request(new Request(mergeOptions(this._defaultOptions.merge(new RequestOptions({ body: body })), options, RequestMethod.Post, url)));
    };

function mergeOptions(defaultOpts, providedOpts, method, url) {
    var /** @type {?} */ newOptions = defaultOpts;
    if (providedOpts) {
        // Hack so Dart can used named parameters
        return newOptions.merge(new RequestOptions({
            method: providedOpts.method || method,
            url: providedOpts.url || url,
            search: providedOpts.search,
            headers: providedOpts.headers,
            body: providedOpts.body,
            withCredentials: providedOpts.withCredentials,
            responseType: providedOpts.responseType
        }));
    }
    return newOptions.merge(new RequestOptions({ method: method, url: url }));
}
```
In these chunks of code: 
```js 
// Post method chunk
mergeOptions(this._defaultOptions.merge(new RequestOptions({ body: body })), options, RequestMethod.Post, url)

// mergeOptions chunk
 headers: providedOpts.headers,
```
mergeOptions receives your merged headers in the param 1, and method headers as param 2. And mergeOptions just ignore it, only use the second!

So you can override merge method as many time as you want, won't work. It's required to modify mergeOptions, no choice.

**Comment by Serginho** [comment]
@DzmitryShylovich Sorry but, I made a mistake in plunkr, your example doesn't work with POST method. As you can see here: https://plnkr.co/edit/H21gujRz74tKoOFvQ563

I solve it overriding the merge method, but I didn't use BaseRequestOptions, I had to extend RequestOptions. See that:

```ts
export class DefaultRequestOptions extends RequestOptions {

  constructor(options: RequestOptionsArgs) {
    super(options);
  }

  merge(options: RequestOptions) {
    let newRequestOptions = super.merge(options);
    if (newRequestOptions.headers) {
      Object.keys(environment.defaultHeaders).forEach(key => {
        if (!newRequestOptions.headers.has(key)) {
          newRequestOptions.headers
            .append(key, environment.defaultHeaders[key]);
        }
      });
    } else {
      newRequestOptions.headers = new Headers(environment.defaultHeaders);
    }

    return new DefaultRequestOptions({
      method: newRequestOptions.method,
      headers: newRequestOptions.headers,
      body: newRequestOptions.body,
      url: newRequestOptions.url,
      search: newRequestOptions.search,
      withCredentials: newRequestOptions.withCredentials,
      responseType: newRequestOptions.responseType
    });
  }

}

@Injectable()
export class DefaultRequestOptionsService extends DefaultRequestOptions {

  constructor() {
    super({method: RequestMethod.Get, headers: new Headers()});
  }
} 
``` 


Actually, BaseRequestOptions is useless.

**Comment by devoto13** [comment]
@Serginho Yes, BaseRequestOptions is useful for limited amount of use cases. I have faced same issue and had to extend `Http` instead. If [new implementation](https://github.com/angular/angular/pull/14334) of Http module will find it's way into 4.x release, we should get much more flexible way to do customizations with interceptors.

**Comment by Serginho** [comment]
@devoto13 That sounds good. I've also created my custom http class to add request and response interceptors.

**Comment by nallwhy** [comment]
It's weird that Http should be changed when we want to change just headers.
The document of [BaseRequestOptions](https://angular.io/docs/ts/latest/api/http/index/BaseRequestOptions-class.html) says that it's possible to use it to that object, but it never gonna work when merging RequestOptions.
Adding default headers is a very common process.
I really want to see the simple way to do.

**Comment by doronsever** [comment]
+1

**Comment by ghillert** [comment]
In case somebody comes across this issue. I also needed to add dependency injected values as header values for `POST` requests. This works in `4.2.x`.

```typescript
import { Injectable } from '@angular/core';
import { RequestOptions, RequestOptionsArgs, Headers } from '@angular/http';

export class DefaultRequestOptions extends RequestOptions {

  constructor(options: RequestOptionsArgs) {
    super(options);
  }

  private xAuthTokenHeaderName = 'x-auth-token';

  merge(options: RequestOptions) {
    const newRequestOptions = super.merge(options);

    if (ValueHolder.xAuthToken) {
      if (!newRequestOptions.headers) {
        newRequestOptions.headers = new Headers();
      }
      newRequestOptions.headers.append(this.xAuthTokenHeaderName, ValueHolder.xAuthToken);
    }

    return new DefaultRequestOptions({
      method: newRequestOptions.method,
      headers: newRequestOptions.headers,
      body: newRequestOptions.body,
      url: newRequestOptions.url,
      search: newRequestOptions.search,
      withCredentials: newRequestOptions.withCredentials,
      responseType: newRequestOptions.responseType
    });
  }
}

@Injectable()
export class SecurityAwareRequestOptions extends DefaultRequestOptions {

  constructor() {
    super({headers: new Headers()});
  }

  public set xAuthToken(xAuthToken: string) {
    ValueHolder.xAuthToken = xAuthToken;
  }

  public get xAuthToken(): string {
    return ValueHolder.xAuthToken;
  }

  merge(options: RequestOptions) {
    return super.merge(options);
  }
}

/**
 * Work-around to the fact that Angular re-instantiates
 * RequestOptions internally for POST requests. Therefore
 * setting a property does not work and we have to resort
 * to using a static property on this ValueHolder class.
 */
class ValueHolder {
  static xAuthToken: string;
}

```

**Comment by rajkeshwar** [comment]
Check out here. This might help. https://stackoverflow.com/questions/34464108/angular2-set-headers-for-every-request/46684345#46684345
