### ISSUE TITLE
Quick Start Tutorial Module Services (==Take it slow==)

### ISSUE THREAD

**Issue by karosi12** [angular/angular#14310]
```
getHeroesSlowly(): Promise<Hero[]> {
  return new Promise(resolve => {
    // Simulate server latency with 2 second delay
    setTimeout(() => resolve(this.getHeroes()), 2000);
  });
}
```

Please correct this.getHeroes() to this.getHeroesSlowly() 

Thank you in advance.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vicb** [comment]
@karosi12 where do you suggest the edit ?

**Comment by DzmitryShylovich** [comment]
@karosi12 could you re-open the issue on https://github.com/angular/angular.io/issues and close this one? thx

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed

**Comment by wardbell** [comment]
No reason to change. Closing.
