### ISSUE TITLE
Router: parseUrl() and navigateByUrl() fail if URL contains %

### ISSUE THREAD

**Issue by paustint** [angular/angular#14317]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Calling `Router.parseUrl()` when there is a `%` in the URL causes a malformed URI exception to be thrown.

Example:

**Passes**: `router.parseUrl('/some/test/url?q=someQueryThatRequiresaPercentagewillfail')`

**Fails**: `router.parseUrl('/some/test/url?q=someQueryThatRequiresa%willfail')`

![image](https://cloud.githubusercontent.com/assets/5461649/22633633/7054a9dc-ebe0-11e6-9887-ddfc62f103b1.png)

**Expected behavior**

A URL should be successfully parsed the same way `encodeURI()` would parse a URL, which allows `%` characters
**Minimal reproduction of the problem with instructions**

1. Import router with necessary setup to include the router service in a component
1. Attempt to call any router method that will ultimately call `UrlParser` (e.x. `router.parseUrl` or `router.navigateByUrl`
1. notice exception is thrown for `Uncaught URIError: URI malformed`

**Plunkr** http://plnkr.co/edit/4IZYAhAN8s41ZkndbpK2?p=preview

**What is the motivation / use case for changing the behavior?**

1. I have a use-case where query parameters are the best fit to allow users to bookmark/share their page location.  The query parameter includes a SOQL query ultimately is used to call out to Salesforce.com and a very common character is '%', which is a wildcard for strings.

**Please tell us about your environment:**

1. OSX latest
1. VSCode
1. Chrome
* **Angular version:** 2.0.X

```javascript
    "@angular/common": "~2.4.6",
    "@angular/compiler": "~2.4.6",
    "@angular/compiler-cli": "~2.4.6",
    "@angular/core": "~2.4.6",
    "@angular/forms": "~2.4.6",
    "@angular/http": "~2.4.6",
    "@angular/platform-browser": "~2.4.6",
    "@angular/platform-browser-dynamic": "~2.4.6",
    "@angular/router": "~3.4.6",
```
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Tested on Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
`"typescript": "2.0.10"`

**Comment by DzmitryShylovich** [comment]
The `%` is an escape character, it can't be on its own. I don't think we should handle such non standard use cases inside angular.
You have 2 options:
1. encode query params yourself so it will be correctly decoded by the router
```
var param = encodeURIComponent('someQueryThatRequiresa%willfail');
decodeURIComponent(param) // 'someQueryThatRequiresa%willfail'
```
2. provide your own impl of `UrlParser`

**Comment by dejour** [comment]
or you can provide encoded %  `%25` .

**Comment by paustint** [comment]
@DzmitryShylovich - thanks. I was having issues when I tried to encode the URI but I think I was missing that I would have to manually decode.  I will give that a try and am very hopeful I will be able to figure it out!

**Comment by paustint** [comment]
Hey team - thanks for helping me out. There was some other issue in the subsequent API call that I was making that caused my first attempt of encodeURI to fail somewhere else but I was able to work through that.

Encoding manually has solved my issue.
