### ISSUE TITLE
Dependency injection only works if classes are declared in the right order

### ISSUE THREAD

**Issue by ppham27** [angular/angular#14312]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If I declare classes in the wrong order, the injector cannot resolve the dependencies of Car. I need to declare Engine before Car for it to work. Otherwise, I get the message: `Error: Cannot resolve all parameters for 'Car'(undefined). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Car' is decorated with Injectable.`

**Expected behavior**

I expect that injector should be able to resolve the dependency. If this is the intended behavior, I expect that the error message would be more useful since Car is decorated with `Injectable`.

**Minimal reproduction of the problem with instructions**

See this demo: http://plnkr.co/edit/HhTthfukXqpojRLZoRfJ?p=preview

The offending code is:

```
// Declared here it works.
// @Injectable()
// class Engine {
//   makeNoise(): string {
//     return 'VROOM!!';
//   }
// }

@Injectable()
class Car {
  constructor(private engine: Engine) {}
  
  drive(): string {
    return this.engine.makeNoise();
  }
}

// Declared here it is broken.
@Injectable()
class Engine {
  makeNoise(): string {
    return 'VROOM!!';
  }
}

const injector = ReflectiveInjector.resolveAndCreate([Car, Engine]);
```

**What is the motivation / use case for changing the behavior?**

I want to be able to use the injector manually to create Car models and inject locals.

**Please tell us about your environment:**

macOS Sierra, Emacs, npm, webpack dev server

* **Angular version:** 2.4.6 and 4.0.0-beta.6

* **Browser:** [Chrome 56 | Firefox 51] Haven't tried other browsers.
 
* **Language:** [TypeScript 2.2]

* **Node (for AoT issues):** `node --version` =   v7.5.0

**Comment by DzmitryShylovich** [comment]
Everything works as intended and it has nothing to do with DI or angular.
`Engine` is not available in `Car`s constructor (undefined) and error clearly says about it http://prntscr.com/e4wvzd 

Here https://blog.thoughtram.io/angular/2015/09/03/forward-references-in-angular-2.html you can find the exaplanation.

**Comment by ppham27** [comment]
@DzmitryShylovich Okay, thanks for the information. While not ideal, using forwardRef is an acceptable workaround.
