### ISSUE TITLE
Produce closure externs in Angular distro

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#14325]
Tsickle can convert an interface declaration like
```
declare interface MyJsonData {
  fieldThatComesAsJson: string;
}
```

to the Closure Compiler externs format, preventing `fieldThatComesAsJson` from being renamed to something shorter by Closure.

We just need to hook up the externs generation in `@angular/tsc-wrapped` and include them in the Angular distro (for things like testability API that Protractor calls), and make sure an example user app also generates externs that can be discovered by closure.

**Comment by b-strauss** [comment]
I thought the plan was to let closure optimize symbols across the whole program (RxJS + Angular + App). Would this not significantly increase the output?

**Comment by alexeagle** [comment]
@b-strauss yes, that is what we do already. A single JS bundle containing the parts of angular/rxjs that your app uses. The externs are needed only for:
- parts of Angular that need to be used outside the bundle (just the testability interface for Protractor so far)
- interacting with the JSON data you receive at runtime
- usage of 3rd party libraries you use that aren't compatible with closure, and you plan to load outside the bundle

**Comment by IgorMinar** [comment]
@alexeagle I think this one is already being taken care of by us running the ts code through tsickle before shipping it to npm. can this be closed?

**Comment by alexeagle** [comment]
We have some externs copied manually out of tsickle's output. Ideally we should generate them, but I reviewed them again just now, and they are very trivial (search for *.externs.js in the angular repo) so I think there's nothing more to do.
