### ISSUE TITLE
i18n Xlif Load and Parse repeated calls (perfomance impact)

### ISSUE THREAD

**Issue by Shireilia** [angular/angular#14322]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

Actually, the xlif file used for translation seems to be loaded and parsed multiple times (one for each component in the app) wich lead to a severe loss in performances at bootstrap in our applications.

We've used the profiler in chrome to see why the bootstraping was taking so long (around 16 sec) :

![xlifissue](https://cloud.githubusercontent.com/assets/18397984/22649166/16618dce-ec7a-11e6-80d2-0d55fdf5b5a5.png)

After that, we have setup a new repo with the minimal basics, based on the webpack config we are using, and our actual translation file and did the same : 

![withourtranslationfile](https://cloud.githubusercontent.com/assets/18397984/22649437/2b3a0ac2-ec7b-11e6-911c-55c02dcbe441.png)

And finally, with the actual translation file of the repo : 

![withnewfile](https://cloud.githubusercontent.com/assets/18397984/22649514/8c91795e-ec7b-11e6-92c8-ca923c7c0faf.png)

**Expected behavior**

The Xlif file should be loaded and parsed once, and not for every component to avoid performance loss.

**Minimal reproduction of the problem with instructions**

We've setup a repo based on  https://github.com/AngularClass/angular2-webpack-starter : 
- git clone https://github.com/Shireilia/angularI18nRepro
- npm install
- npm start
- start profiling and go to localhost:3000

**Please tell us about your environment:**

Ubuntu, VSCode, Webpack, Node 7.0.0

* **Angular version:** 2.4.4

* **Browser:** [all]
 
* **Language:** [TypeScript 2.1.5]

**Comment by vicb** [comment]
Nice catch, this should be fixed in the next releases(2.x and 4.x branch).

However you should use AOT for prod

**Comment by Shireilia** [comment]
We're going for AoT in production, we just were working with JIT at the moment :)

Thanks for the feedback !

**Comment by JoniJnm** [comment]
Why this change is not in 2.4.8? :(

**Comment by Shireilia** [comment]
As @vicb said, 2.x, so my guess is it will be in 2.5 :) (but i'm sad too :p)

**Comment by mhevery** [comment]
@igorminar. Does this apply cleanly?

**Comment by Shireilia** [comment]
Hello guys, just wanted to know if this will ship in a release soon ?
