### ISSUE TITLE
AoT Error encountered resolving symbol values statically (when using third party decorators)

### ISSUE THREAD

**Issue by hccampos** [angular/angular#14323]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using MobX with Angular via ng2-mobx (https://github.com/500tech/ng2-mobx), AoT fails to compile components that use any of MobX's decorators saying:

```
ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 174:13 in the original .ts file), resolving symbol observable in .../app/node_modules/mobx/lib/mobx.d.ts
```

**Expected behavior**

Angular should either disregard variables declared in third party libraries or provide some sort of configuration option to do so. In MobX's case, Angular should still be able to normally AoT compile the templates, oblivious to the fact that MobX will actually replace the property accesses with getters and setters and wrap the `@action` annotated methods in transactions. Or would be impossible to do given the transformations that the Angular compiler does?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Ubuntu 16.10, VSCode, yarn package manager

* **Angular version:** 2.0.X

Angular 2.4.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
Compilation problem, so not tested in-browser.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =   

Node 7.3.0 compiled from source

**Comment by alvaro9210** [comment]
Did you find a workaround for this?!

**Comment by DzmitryShylovich** [comment]
@hccampos is this still valid in angular4?

**Comment by ubaidazad** [comment]
@DzmitryShylovich  yes, please refer to the stackoverflow question. http://stackoverflow.com/questions/43039026/singleton-service-error-in-app-module-on-ng-build

**Comment by tbosch** [comment]
Hello, we need a reproduction to analyze this...

**Comment by th0r** [comment]
@tbosch Here is the reproduction repository: https://github.com/th0r/ng-mobx-aot-bug
Just run `ng build -aot` and you'll see an error we're talking about.

**Comment by queejie** [comment]
Is there a temporary workaround for this, until it gets fixed?  I upgraded to Angular 4.1 from 2.4 and now get this error.

**Comment by th0r** [comment]
@tbosch Sorry for being annoying but are there any updates on this?

**Comment by th0r** [comment]
Updated Angular and dependencies in reproduction repository to the latest versions - the same error.
@tbosch If you have more prioritized issues maybe you just could the root of the problem so I can try to fix it myself?

**Comment by stefan-leye** [comment]
Is there any solution for this problem yet?

**Comment by th0r** [comment]
No, and seems like it has low priority 🙁

**Comment by stefan-leye** [comment]
Hmm that's disappointing. I don't know how to get AoT running in my project with this issue. I'm using core-decorators in basically every class. If AoT doesn't work with decorator libraries the whole feature is pretty unusable for me.

**Comment by skorunka** [comment]
Same problem. Is there any plan to fix this? Thank you.

**Comment by idanaim** [comment]
Hey I found solution you should import action computed and the other functions from mobx-angular and the ng build --prod works like.  import {action} from 'mobx-angular'

**Comment by villelahdenvuo** [comment]
Has anyone found a workaround for core-decorators package?

**Comment by th0r** [comment]
Updated Angular and dependencies in the [reproduction repository](https://github.com/th0r/ng-mobx-aot-bug) to the latest versions (`Angular v5.2.7`, `Angular CLI v1.7.2`) and the error is still there:
```
ERROR in app/app.component.ts(11,4): Error during template compile of 'AppComponent'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'observable'
    'observable' references 'observable'
      'observable' is not initialized at ../mobx/lib/api/observable.ts(54,22)
```

**Comment by villelahdenvuo** [comment]
I found that version 0.19.0 of core-decorators works so I downgraded to that version for now, for anyone wondering.

**Comment by th0r** [comment]
Updated Angular and dependencies in the [reproduction repository](https://github.com/th0r/ng-mobx-aot-bug) to the latest versions (`Angular v6.0.3`, `Angular CLI v6.0.8`) and the error is still there:
```
ERROR in app/app.component.ts(11,4): Error during template compile of 'AppComponent'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'observable'
    'observable' references 'observable'
      'observable' references 'observable'
        'observable' is not initialized at ../mobx/lib/api/observable.ts(39,22)
```

**Comment by idanaim** [comment]
You need to import all the decorators functions from mobx-angular and it works! e.g import {observeoble} from 'mobx-angular'

**Comment by th0r** [comment]
@idanaim I know, but it's a just a workaround for this bug.

**Comment by KevinGuancheDarias** [comment]
The problem still exists in Angular 8 

I'm using the NPM package `ts-mixer` to apply mixings, but on aot compilations it tails

```ts
export const aotHelp: any = 'foo';
ix(aotHelp)
@Injectable()
export class ImageStoreService extends WithReadCrudMixin<ImageStore, number> {

}
```

```
ERROR: ts-mixer/dist/mixins.ts(29,15): Error during template compile of 'mix'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
```

**Comment by th0r** [comment]
I can confirm that the problem is solved in Angular 9! 🎉🎉🎉

**Comment by JoostK** [comment]
Thanks @th0r for confirming!
