### ISSUE TITLE
Request for applying the 'ngIf else' feature to version 2.X

### ISSUE THREAD

**Issue by goldenbearkin** [angular/angular#14326]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

The ngIf else feature is now on version 4 only. Really want to have it on a stable version 2 as well. Since the reactive functional style has been all over the place in Angular, the ngIf else pattern is really desirable. And now we have forced to use an unstable version in favour of this great feature. So please consider to include the ngIf else pattern to version 2.

**Comment by Toxicable** [comment]
The ngIf improvements is a new feature, since there will not be a version 2.5.x it will not be released on this major version hence why it is on version 4.x this is to maintain semver.

**Comment by michaeljota** [comment]
> Really want to have it on a stable version 2 as well.
4.x it's a stable version. Just semver naming for now and on.
