### ISSUE TITLE
Unsubscribe and http-request

### ISSUE THREAD

**Issue by ichent** [angular/angular#14339]
Hello.

I'm submitting a bug.
Now "unsubscribe" doesn't break http-request.
Early, it worked correctly. I use Angular 2.4.1, typescript 2.0.10, rxjs 5.0.3.

This error with AOT and without AOT.

**Comment by DzmitryShylovich** [comment]
Nothing has changed with the impl https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/xhr_backend.ts#L148
So the problem is on your site.

**Comment by ichent** [comment]
Thanks to @DzmitryShylovich.

Hmm, I have just changed from GET to POST.
OK. I will try to make plnkr-example.

**Comment by ichent** [comment]
Now I close this bug. There is a problem with resolver in my version of Angular (2.4.1). So router.navigate waits, while current request will be completed, and only after this agnualr exec resolver for new request. So I can't break current request (I do it in the resolver.). I changed the version of Angular to 2.1.2 (my manager was very angry), and now it is ok.
