### ISSUE TITLE
Unable to use @ContentChildren when downgrading Angular components

### ISSUE THREAD

**Issue by BjornRombaut** [angular/angular#14338]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Unable to use `@ContentChildren` when downgrading Angular components. Result is empty.

**Expected behavior**

Result should contain a list of the transcluded children.

**Minimal reproduction of the problem with instructions**

We are running a hybrid app using `@angular/upgrade`. Bootstrapping of the hybrid app is successful.

Angular Components
```
@Component({
  selector: 'child',
  template: `<p>Hello World</p>`
})
export class ChildComponent {
}

@Component({
  selector: 'parent', 
  template: `<ng-content></ng-content>`
})
export class ParentComponent {
  @ContentChildren(ChildComponent) children: QueryList<ChildComponent>;

  ngAfterContentInit() {
    console.log(this.children); // Result should not be empty
  }
}
```

Usage in Angular App **Does work**
```
@Component({
  selector: 'app',
  template: `
    <parent>
      <child></child>
      <child></child>
    </parent>
  `
})
export class AppComponent {}
```

Usage in AngularJS App **Does not work**
```
angular.module('demo')
.directive('parent', downgradeComponent(...))
.directive('child', downgradeComponent(...))
.component('app', {
  template: `
    <parent>
      <child></child>
      <child></child>
    </parent>
  `
});
```

**Please tell us about your environment:**

* **Angular version:** 2.4.5

* **Browser:** all

 
* **Language:** all

**Comment by tbosch** [comment]
AngularJS does not have the concept of `@ContentChildren`. As you downgraded each component into an AngularJS component, `@ContentChildren` does not have a meaningful semantic any more (i.e. what would happen if you put a pure AngularJS 1 component as a child which contains the Angular 2 component?).
