### ISSUE TITLE
using "ViewEncapsulation.Native" breaks down Angular 2 animations

### ISSUE THREAD

**Issue by mountju** [angular/angular#14340]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1. There is a Component which uses "encapsulation: ViewEncapsulation.Native" mode
2. This component also needs to be animated, so it uses "animations" provided by Angular 2

**Expected behavior**
Component is isolated from styles of parent's service, they don't influence on a Component. (thanks to ShadowDom features)
Animations work fine

**Minimal reproduction of the problem with instructions**
Animations don't work while we are using  ViewEncapsulation.Native
here is a demo
https://plnkr.co/edit/vYgTLWd5Ck0Wyk7BOWXO?p=preview

* **Angular version:** 2.4.1
with 2.0.0 works just fine! but we need the latest version of the framework.

* **Language:** [TypeScript X.X | ES6/7 | ES5]

**Comment by DzmitryShylovich** [comment]
@mountju does the issue still persist in angular 4?

**Comment by mountju** [comment]
@DzmitryShylovich don't know, we use Angular 2

**Comment by tbosch** [comment]
My feeling is that we won't be able to fix this, but let's see what @matsko  says...

**Comment by abalad** [comment]
+1

**Comment by abalad** [comment]
@DzmitryShylovich Yes it still continues

**Comment by robjtede** [comment]
Angular 4.3 - this remains an issue.

**Comment by brgaulin** [comment]
Forked Plunkr to reproduce on latest: https://plnkr.co/edit/NbwmvcmzSr55FKcQvkzn?p=preview

**Comment by matsko** [comment]
OK I see that there is an issue here. I'm looking into it.

**Comment by zavvla** [comment]
any progress?

**Comment by robjtede** [comment]
still the case in angular v6

**Comment by jamestalton** [comment]
still the case in angular 7

**Comment by quekqh** [comment]
still the case in angular 8

**Comment by crisbeto** [comment]
This should've been resolved by https://github.com/angular/angular/pull/40134.
