### ISSUE TITLE
Lazy loading bundled Modules: No NgModule metadata found.

### ISSUE THREAD

**Issue by about-code** [angular/angular#14343]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
I am submitting this as a bug report but it may turn out to be a general limitation in how Angular apps can be built and bundled. Given that there is [a similar issue posted on the SystemJS-Builder issue tracker](https://github.com/systemjs/builder/issues/739) my use case may not be so unique and of interest to a wider community.

**Use Case and Current behavior**
Consider an NgModule `LazyFeatureModule`. The feature implements a workflow with a few View Components that may be used in multiple applications.

It was transpiled against Angular 2.4.6 and bundled with [Rollup](http://rollupjs.org). The entry file to Rollup is `foo-feature/index.js` which only exports `LazyFeatureModule`. From this Rollup generates `foo-feature/bundle.js` which contains all the dependencies required by `LazyFeatureModule` - including all (ES2015-imported) Angular dependencies - and which eventually exports `LazyFeatureModule` again. `bundle.js` was meant to become a pre-bundled Angular module shipped with an npm-package, such that applications which lazily load the bundle don't need to be rebuilt when updating the feature. They should be fine with running an `npm update foo-feature` on their side.

The application which aims to incorporate the pre-bundled feature has a routing configuration which lazily loads the feature like so:

```javascript
{path: 'my-foo-feature', loadChildren: './node_modules/foo-feature/bundle.js#LazyFeatureModule'}
```
The bundle gets loaded, so the paths are correct, but I get an error stating `No NgModule metadata found for LazyFeatureModule`.

Rollup builds the feature-bundle without warnings and the export produced by Rollup actually looks quite good. These are the last few lines in `bundle.js`:

```javascript
// ...
exports.LazyFeatureModule = (function () {
    function LazyFeatureModule() {
    }
    return LazyFeatureModule;
}());
exports.LazyFeatureModule = __decorate([
    NgModule({
        imports: [
            CommonModule,
            RouterModule.forChild(ROUTES)
        ],
        declarations: [
            HelloView
        ]
    })
], exports.LazyFeatureModule);
```
So LazyFeatureModule is actually decorated with NgModule metadata and exported.  I could track down the problem and the reason seems to be that when Metadata is resolved, a function

```
 function _isNgModuleMetadata(obj) {
    return obj instanceof NgModule;
  }

```
is called and returns *false*.

Above function is included in both bundles. When the error happens it is called inside of *app-bundle* but `obj` is a `DecoratorFactory` of the lazy-loaded feature bundle. Since the feature bundle has been bundled separately, there's not only one but two`NgModule` definitions, one in *app-bundle* and one in *feature-bundle*. So we got two bundles with two `NgModule` class definitions. Therefore I suspect that when above code in *app-bundle* tests a `DecoratorFactory`  of *feature-bundle* it will test against a different NgModule constructor function reference and therefore returns *false* for the feature bundle.

As "fix" for the problem at hand I could suggest that above function replaces a hard *instanceof* check for a test against a special property which indicates that `obj` is a valid NgModule (something which TypeScript Reference calls *Discriminant Properties*). However I wonder if my intended use case is possible at all or whether code duplication may also affect dependency injection (which compares against constructor references).

One of the motivations of shipping *pre-bundled* features was to enable apps to npm-update the feature without the need for a complete rebuild and to ease the build configuration for applications incorporating the feature.

However, as of today *deduplication* seems to be a strong requirement when building apps out of multiple chunks (multiple chunks are a logical consequence when aiming for lazy-loading). Now the questions which remain for me:

- Do you consider this issue a bug or did Angular never intend to support the given use case?
- Do you agree with the analysis given in the issue or may I am wrong? If code duplication is a problem should *deduplication* be mentioned in guides on bundling Angular apps?

**Angular version:** 2.4.6
... bundles use JIT compiler at the moment

**Please tell us about your environment:**
- rollup@0.41.4
- rollup-plugin-commonjs@7.0.0
- rollup configured with
   format: `"iife"` for app-bundle
   format: `"cjs"` for feature-bundle
- gulp 3.9.1

* **Browser:** [all]
* **Language:** [TypeScript | ES6 | ES5]

**Comment by vdzundza** [comment]
@about-code 
When I am using this path for loadChildren `./modules/moduleA/moduleA.module#ModuleAModule`
I got the same problem, but when I changed to this one
`@myscopeofpublishedpackage#ModuleAModule` the module is loaded properly. What can cause this problem>

**Comment by vdzundza** [comment]
@about-code it looks like this one in my case partially relates to this one [webpack/issues/4545](https://github.com/webpack/webpack/issues/4545)

**Comment by about-code** [comment]
@vdzundza It's hard to tell you without knowing your setup in more detail. Do you have a sample repo I could clone?

**Comment by tbosch** [comment]
It seems like you are including `@angular/core` in both of your bundles. This way, you also have 2 prototypes for `NgModule`. This setup is not supported, i.e. we need to have only one version of `@angular/core`.

**Comment by tbosch** [comment]
I.e. even if we fix this case, there will be a couple of other cases that won't work. 
Besides the extra playload...

**Comment by Bjeaurn** [comment]
@furydam I noticed your comment is a little dated for the pace at which Angular and other packages are evolving; but you can get it to work when using `@myscopeofpublishedpackage/module#ModuleAModule`? I'm doing the equivalent of that and I run into the `No NgModule metadata found for` error. 

I'm doing this with Angular 5.0.5, has there been any changes to the way this loads?

**Comment by barrychapman** [comment]
I have this same problem, documented in this use case:

https://stackblitz.com/edit/angular-ppzwky
