### ISSUE TITLE
4.0.0-Beta.6 opaque_token relative to undefined

### ISSUE THREAD

**Issue by mattma** [angular/angular#14348]
My angular application works fine with version `2.4.6`, no error was reported in the `ng serve`.

Without any code changes, I updated angular packages from `2.4.6` to `4.0.0-Beta.6`. Run `ng serve` (in Angular-CLI version 1.0.0-beta.30), it runs into an error 

```
ERROR in Could not resolve module @angular/core/src/di/opaque_token relative to undefined
```

So i looked in the code, and I do use `OpaqueToken`. 

```
import { OpaqueToken } from '@angular/core';

export const SOME_STRING: OpaqueToken = new OpaqueToken('some_string');
```

I launch `localhost:4200` in the browser, The page is white screen of death. I simply add an empty space in my source file to trigger a incremental reload, the error goes away, build is fine, the page is working as expect.

So I dig in the code to find what is going on. I find the [file has been renamed](https://github.com/angular/angular/commit/6d1f1a43bb95427556834193ef067fe1bb488c06#diff-dca06b67ac8e2bc4253322dcc4a46acc). I am sure that in the build step, the code is still looking for `@angular/core/src/di/opaque_token` when I imported `import { OpaqueToken } from '@angular/core';`.  Second reload is trigger to load up the right class, but the initial load does not.

Is there a workaround in beta series? or I have to stick with `2.4.6`  stable release.

**Comment by vicb** [comment]
Seems like you had an outdated file in your build artifacts. 
It's a good idea to do a clean build after having updated angular.

**Comment by mattma** [comment]
@vicb 

I have removed my packages `rm -rf node_modules`, cleaned up npm cache by `npm cache clean`, installed latest `yarn`, run `yarn`, yarn locked with `@angular/core` on version `4.0.0.beta.6`, when I do `cat ./node_modules/@angular/core/package.json`, I do see the version `4.0.0.beta.6`.

Run with `ng serve`. still got the same error. 

![screen shot 2017-02-08 at 1 34 47 pm](https://cloud.githubusercontent.com/assets/1148428/22758403/68c471d2-ee03-11e6-9230-57d9a34f9836.png)


So I looked into the `yarn.lock`, `@angular/cli` version `1.0.0.beta.30` is using dependency of `@angular/core` on version `^2.3.1`. so I used `npm link` the latest `master` branch of `@angular/cli` running on my local computer. Clean installed all node packages. run `ng serve`, still got the same error.

**Comment by vicb** [comment]
@hansl does the CLI support 4.x yet ?

**Comment by mattma** [comment]
I used the latest releases. 

Angular-cli beta 31  (released 5 min ago)
Angular  4.0.0-beta.7

I generated a new Angular-cli project, then updated the dependencies of all Angular packages from '^2.x.x' to '4.0.0-beta.7'

I am still seeing the error. App crashed.

```
ERROR in Could not resolve module @angular/core/src/di/opaque_token
webpack: Failed to compile.
```

In addition, @hansl   `ng test` command is falling as well.

@vicb I think it is a Angular Cli related problem. Should I open an issue on cli?

**Comment by beeman** [comment]
@mattma just looked into a similar issue at the Angular CLI repo https://github.com/angular/angular-cli/issues/4611 , it might help you fix yours too.

**Comment by mattma** [comment]
@beeman Thank you for the workaround. It is good to confirm it is an error of CLI, not the Angular itself.

**Comment by mattma** [comment]
@beeman Thank you for helping. [I believe the issue has been fixed](https://github.com/angular/angular-cli/issues/4611#issuecomment-284172455)
