### ISSUE TITLE
Authorization Custom Token Header not being included in HTTP secure API request

### ISSUE THREAD

**Issue by victorsauri** [angular/angular#14359]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently the Authorization attribute is not being set on the headers request to a another projects API. Whereas HTTP tools can successfully make the connection and obtain the response without any CORS warning.
Below there is an screenshot  of the request headers:
![corsexceptionheaders](https://cloud.githubusercontent.com/assets/8926084/22747618/d6311fda-ee27-11e6-801e-50806ffc3b42.PNG)

Where the "Authorization" attribute is missing, even though on the Angular 2 application we did follow the same approach as the one stated in: https://github.com/angular/angular/issues/10654

**Expected behavior**
Ideally we wanted to reproduce a GET request similar to:

```
GET http://localhost:8080/inputEndpoints
Authorization: Bearer eyJhbGci...
```
Whereas "eyJhbGci..." is a json token key already tested and accepted by the running application on the 8080 port.
The above request does produce the expected response:

```
200 
X-Content-Type-Options:  nosniff
X-XSS-Protection:  1; mode=block
Cache-Control:  no-cache, no-store, max-age=0, must-revalidate
Pragma:  no-cache
Expires:  0
X-Frame-Options:  DENY
Content-Type:  application/hal+json;charset=UTF-8
Transfer-Encoding:  chunked
Date:  Wed, 08 Feb 2017 15:23:04 GMT

{
  "_key" : {
    "value" : [ ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/inputEndpoints"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile/inputEndpoints"
    },
    "search" : {
      "href" : "http://localhost:8080/inputEndpoints/search"
    }
  }
}
```
**What is the motivation / use case for changing the behavior?**
For this particular use case this authorization request is crucial for the integration of Angular within other project's back end.

**Please tell us about your environment:**
Server side there is no nothing to comment, since it has been with multiple HTTP tools, independent node.js requests modules and also in different browsers to reduce the exception to the **@angular/http/angular2-jwt** dependencies.

Any information on similar issues/behaviours will be greatly appreciated. 
Alternatively there is an ongoing discussion on **StackOverflow** regarding this exception encountered: http://stackoverflow.com/questions/42114709/angular-2-authhttp-with-jwt-not-connecting

**Comment by DzmitryShylovich** [comment]
Pls add a small repro

I don't see how it's an angular issue tbh. Try to send the same request using plain xhr.

**Comment by victorsauri** [comment]
Sorry for the late update, for the last few days the team has been trying to attempt the request by following a variety of approaches. The main conclusion is that the backend project does not support OPTIONS requests to be accepted. Since those are not allowed, no OK response is returned for this preflight OPTIONS request and therefore the following GET method never reach its destination ([complete explanation](http://restlet.com/blog/2015/12/15/understanding-and-using-cors/)).

So we are now trying to override the method within the request made by angular2 to prevent this initial OPTIONS one made to verify the credentials on the client side. Otherwise we will have to use sort of middleware strategy with a node.js layer, for instance, to prevent the extra requests made.

Any info on overriding the http request method (preventing the options one) will also be extremely useful.

**Comment by DzmitryShylovich** [comment]
@victorsauri http://stackoverflow.com/questions/29954037/how-to-disable-options-request
can you close this as it's not directly related to angular, pls? thx

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed

**Comment by tbosch** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by laskasn** [comment]
HttpClient is full of bugs... it seems to be impossible to add/create custom headers for a get or post request... Fails terribly... The official documentation is full of crap also... Pieces of code which do not work in many cases...

**Comment by lazarljubenovic** [comment]
> The official documentation is full of crap also...

Please save that kind of talk for over a beer with friends. This is a place for constructive talk. Criticism is always welcome if reported politely.

Also, this is an old, closed issue. You're free to [open an issue](https://github.com/angular/angular/issues/new) to describe what exactly is confusing with the documentation, so the community can help fix it (you can help as well). Thanks!

**Comment by whitecat** [comment]
I am facing this same issue. There is another post in this form https://github.com/angular/angular/issues/6583. What was done to resolve the issue?

I am using ionic framework. When I do `ionic serve` the headers are created correctly. When I do `ionic cordova run browser` the headers stop being created correctly and I am faced with the same errors reported. This is very strange behavior.  Why would I get 2 different results with the same piece of code?

**Comment by ojoadeolagabriel** [comment]
HttpClient, is full of very bad issues. For one, headers are not propagated with the requests. Really hard to determine what is wrong.
