### ISSUE TITLE
Wildcard Route and Named Router-Outlet

### ISSUE THREAD

**Issue by Massimiliano-Perelli** [angular/angular#14352]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Consider the following routing config array:

```
const appRoutes: Routes = [
  {
    path: "login",
    component: LoginAuthenticationComponent
  },
  {
    path: "mainpage",
    component: MainPageComponent,
    children: [
              {
                path: "out",
                outlet: "secondary",
                component: OutletPageComponent
              }
    ]
  },
  {
    path: "**",
    component: NotFoundPageComponent
  },
];
```
Now, if I enter an wrong URL like "localhost/blablabla" the wildcard route ** is followed and the NotFoundPageComponent displays.

If I enter a wrong URL in the named outlet part (i.e. localhost/mainpage/(sdfsdf:out)) the wildcard route is not followed and router navigates to localhost/mainpage

**Expected behavior**

I expect that wildcard route cath all wrong URL, not only the one on primary outlet.
If I'm wrong I should configure the desired behavior?
**Minimal reproduction of the problem with instructions**

The above information should be enough to reproduce the issue.

**What is the motivation / use case for changing the behavior?**

Have an unique configuration for wildcards.

**Please tell us about your environment:**

Windows, live-server
* **Angular version:** 2.0.X

Angular 2.2.3
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr

**Comment by Massimiliano-Perelli** [comment]
Hi, I cloned this plunk from the angular.io documentation link in router & navigation section:

https://plnkr.co/edit/PVx2BmKa0ygPgA7mHpW8

1. I haven't change anything on routing config

2. I've added two button links on the app.component:

-Go to wrong page
This one goes as expected to the notfoundpage

-Go to wrong outlet

this one does not bring to notfoundpage

**Comment by DzmitryShylovich** [comment]
It's impossible to figure out anything with so many components.
Pls use https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue as a starting point

**Comment by Massimiliano-Perelli** [comment]
check with this one:

https://plnkr.co/edit/PVx2BmKa0ygPgA7mHpW8

**Comment by 82antu** [comment]
Hi, I have the Same Issue

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
