### ISSUE TITLE
Why click function triggers twice for custom component in Angular 2

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular#14355]
My custom component click function is triggered twice - both custom component's event and sample level event are triggered.

Here's my Plunker:

https://plnkr.co/edit/wp2iWh7OStdPm5uXsWbP?p=preview

**Comment by skreborn** [comment]
Isn't that just standard event bubbling? You click on the inner element, which fires a `click` event, you handle that, then it bubbles up the DOM until it's either stopped (using [`stopPropagation`](https://developer.mozilla.org/en/docs/Web/API/Event/stopPropagation)) or there's no more parent nodes.

**Comment by DzmitryShylovich** [comment]
@AbinayaSubbiah Yeah, read about event bubbling

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed
