### ISSUE TITLE
Is there any feature can support compile html as dynamic component in simpler way?

### ISSUE THREAD

**Issue by blackcatIan** [angular/angular#14357]
I read the solution in http://stackoverflow.com/questions/34784778/equivalent-of-compile-in-angular-2.

It's really too complex! And you can see that some solution maybe out of date when version updated

Although there is a third party solution like https://github.com/patrikx3/ng2-compile-html but I'm worried about one day it is out of date and does not work.

Expect there would be a offical solution to make it easier to use compile html as dynamic component.

**Comment by mlc-mlapis** [comment]
Try to read some more info about this topic. The basic fact is that COMPILE during runtime = JIT mode is not the right way. You have to count that the prefered way is AOT mode and then you have not any compiler in a browser so you can't compile anything.

**Comment by DzmitryShylovich** [comment]
>  You have to count that the prefered way is AOT mode and then you have not any compiler in a browser so you can't compile anything.

[Here](http://blog.assaf.co/angular-2-harmony-aot-compilation-with-lazy-jit-2/) you can find an interesting approach of how to benefit from aot and still have the ability to dynamically compile templates.

**Comment by mlc-mlapis** [comment]
@DzmitryShylovich Thanks for reminding it. I bookmarked it some time ago with that I read the post later but then I forgot about it.

And yes, it is intereting way how to combine both modes of course - especially on some edge cases, using advantages of lazy loaded modules or just pre-loading them in a right moment.

But I'm not sure if @blackcatIan appreciates that idea.

**Comment by yunxuanyan** [comment]
@DzmitryShylovich Thanks so much to introduce this approach. I have wanted it for ages. It works!

**Comment by blackcatIan** [comment]
@DzmitryShylovich Great!Thank you,the approach is wonderful!  : )
