### ISSUE TITLE
Disable production mode from console

### ISSUE THREAD

**Issue by kikar** [angular/angular#14358]
**I'm submitting a**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behaviour**
Once `enableProdMode()` is called, there is no way of disabling from the console.

**What is the motivation / use case for changing the behaviour?**
There should be a method exposed to disable production mode and reload app, so that `isDevMode()` return true.

For example if in production I disable all logging because `isDevMode()` is `false`, I would like to reload the app in dev mode to see them.

* **Angular version:** 2.4.6

**Comment by DzmitryShylovich** [comment]
So every person will be able to open your site and disable prod mode?

**Comment by kikar** [comment]
What are the implications in that? According to [documentation](https://angular.io/docs/ts/latest/api/core/index/enableProdMode-function.html) all `enableProdMode()` does is

> Disable Angular's development mode, which turns off assertions and other checks within the framework.

**Comment by igormalyk** [comment]
@DzmitryShylovich 
According to [angular docs](https://docs.angularjs.org/guide/production) everyone can do it with an angular1 app using `angular.reloadWithDebugInfo();` Could you please explain why it might be not desired?

**Comment by gkalpak** [comment]
I don't see why it would be undesirable, @DzmitryShylovich. It is indeed possible in AngularJS, for the purpose of debugging.

In AngularJS, it is currently implemented by manipulating `window.name`, but this is not ideal and [people have complained][1] about it. Other options would be using `localStorage`, `cookies`, URL query params (each with their pros and cons).

[1]: https://github.com/angular/angular.js/issues/13031

**Comment by DzmitryShylovich** [comment]
@gkalpak in 4.0 we will use strategy pattern to add debug information / checks, instead of constantly checking for isDevMode [link](https://github.com/angular/angular/pull/14345/files#diff-739891f5dc12cd9610c452541ec52b4eR34). So after aot compilation it will no be able to enable debug info just by reloading the page.

it will work in `jit`, but `jit` has nothing to do with `prod` :)
So it sounds pretty useless to me

**Comment by gkalpak** [comment]
I wasn't aware of that. Obviously, if devMode is not supported by the served scripts (e.g. because AOT), then there is no reason to implement that :grin:

**Comment by kemsky** [comment]
Actually it is pretty simple to implement for JIT mode:

```typescript
    if(!localStorage.getItem('disableProdMode')){
         enableProdMode();  
    }
```

**Comment by tbosch** [comment]
In Angular 4.x, our generated code for dev and prod is the same. I.e. this switch would be the same for AOT as well...

And we need this kind of switch for tools like Augury...

**Comment by trotyl** [comment]
Obsolete for ivy, as all debugging helpers will not be shipped to runtime.

**Comment by pkozlowski-opensource** [comment]
> Obsolete for ivy, as all debugging helpers will not be shipped to runtime.

To be more precise: debugging helpers will not be present in the _production_ builds of the application.

**Comment by pawelkondraciuk** [comment]
> To be more precise: debugging helpers will not be present in the production builds of the application.

Will there be any way to provide those helpers in prod build (e.g browser addon, extra lib)? It would be awesome to be able to debug angular code in production (`ng.probe`)

**Comment by pkozlowski-opensource** [comment]
In Angular v9 prod mode is mostly the build-time concept and the dev / debug helpers are mostly tree-shaken away. As soon has dev mode build it is possible to access debugging helpers.

I'm going to close this one since the general plan is to drop `enableProdMode()` with ivy
