### ISSUE TITLE
npm start fails on second run

### ISSUE THREAD

**Issue by mickeyse** [angular/angular#14363]
As suggested below this report is moved to http://stackoverflow.com/questions/42123253/angular-2-local-development-environment-runs-only-once-after-install-reproducib

It should be noted that having the "Report Issues" link on pages such as https://angular.io/ go to https://github.com/angular/angular/issues ends up wasting lots of people's time for Angular issues  deemed not appropriate here.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mickeyse** [comment]
This actually did turn out to be an issue with the Angular local development environment.  

Certain bugs in *.ts files such as missing commas will not produce any errors in the local development environment while it is running, but will block the local development environment from starting if it is not already running.  

For details see the StackOverflow thread.  

The inconsistency in behavior is particularly problematic since it is encountered by people using the tutorials for learning Angular, and not yet familiar with all the tools.  Angular would be more approachable if such issues were dealt with.

**Comment by DzmitryShylovich** [comment]
Not sure how angular can help you with missing commas :)

> error TS2393: Duplicate function implementation.

this is a ts error and has nothing to do with angular.
can you close this if it was resolved?

**Comment by mickeyse** [comment]
A typo in the code should either prevent both starting and running the environment (when already open) or allow both.  The different behavior under the two circumstances is a bug, is confusing, and should be fixed.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource not related to angular
