### ISSUE TITLE
Stripping component metadata breaks UI-Router apps

### ISSUE THREAD

**Issue by christopherthielen** [angular/angular#14364]
**I'm submitting a ...**
```
[X] bug report
```

**Current behavior**

Component metadata is no longer available at runtime.  Angular decorators are stripped by `ngc` and/or `@ngtools/webpack 1.2.5`.  

**Expected behavior**

Component metadata should be available at runtime.

**Minimal reproduction of the problem with instructions**

https://github.com/christopherthielen/ng-stripped-decorators

- Works: `ng serve`
- Doesn't work: `ng serve --aot`
- Doesn't work: `ng serve --prod`

**What is the motivation / use case for changing the behavior?**

_The primary motivation is to write components that are ignorant of routing._

I prefer writing components that don’t know (or care) if they’re a) being routed or b) just being used within some other component.  The component's data prerequisites should be supplied to the component via its `@Input()`s.

---

UI-Router uses the metadata added by `@Input` to determine if a routed component can have data bound to it and if so, what the class property is (`@Input() property`) and what the input name is (`@Input('name') property`).  If a resolve token matches a `@Input('name')` name, then the component property receives the resolved data.

Now that decorators are being stripped, we can no longer introspect the routed components to determine their input bindings (in order to bind the resolve data).  This means all ui-router apps which bind resolve data to routed components are now broken.

**Please tell us about your environment:**
OSX, yarn, angular-cli

* **Angular version:** 2.0.X

- @angular/*: 2.4.6
- @angular/cli: 1.0.0-beta.30
- @ngtools/webpack: 1.2.8

Note: I tried to figure out the last combination of @angular, angular-cli and @ngtools/webpack that this worked, but could not determine the correct combination.

* **Browser:**
all
 
* **Language:** 
TS

* **Node (for AoT issues):** 
v7.5.0

---

This pull request is related: https://github.com/angular/angular-cli/pull/4301/commits/d911a0cafa0284d59907eb1215ca53ac4ab7b7d6

This bug report is related: https://github.com/ui-router/ng2/issues/36

Note 1: This was a breaking change for UI-Router.  There are workarounds (none are ideal), but this is affecting any ui-router app where resolve data is bound to components.  

Note 2: In the short term, to unbreak ui-router, we would only require the `@Input('name') property;` metadata to be accessible somewhere.   In the future, we may also ask for `@Output` as well.  

---

Perhaps the Input/Output metadata could be retained (similar to the constructor parameter metadata in @ngtools), or an opt-out for decorator stripping.

**Comment by DzmitryShylovich** [comment]
It's `ngtools` issue. Would be better to re open on https://github.com/angular/angular-cli/issues

**Comment by christopherthielen** [comment]
@DzmitryShylovich understood.  However, I was discussing with @robwormald and he suggested:

<img width="637" alt="screen shot 2017-02-08 at 2 10 10 pm" src="https://cloud.githubusercontent.com/assets/2053478/22755343/55e79bf2-ee08-11e6-823b-004b03125e0b.png">

**Comment by DzmitryShylovich** [comment]
Ok :)
But they are removed for a reason. Smaller bundle size, we no longer need to ship reflect metadata etc. This is should be an optional feature.

**Comment by robwormald** [comment]
It's not specific to ngtools. Both `ngc` and `@ngtools/webpack` use the same logic.

Assume:
```ts

@Component({ ... })
export class MyComponent {
  @Input('people') privatePeople; //note the indirection between @Input and class prop name
}

```
Ui-R config does something like
```ts
resolve: [
  { 
    token: 'people',
    deps: [PeopleService], 
    resolveFn: (peopleSvc) => peopleSvc.getAllPeople()
  }
]
```

In JIT mode UIR uses the reflection APIs to retrieve the metadata about inputs, so it knows that it has to assign the resolved `people` property to the `privatePeople` class on the instance. This behavior is not available after decorators have been stripped, and thus there's (currently) no way to do this in a sane fashion in AOT.

**Comment by robwormald** [comment]
cc @chuckjaz @tbosch @vsavkin

**Comment by christopherthielen** [comment]
> But they are removed for a reason.

Understood.

To be clearer:
- I don't care that ng decorators are stripped in AoT.  
- I do care that metadata is not available.   
- I don't care how it would be implemented (i.e., Reflect vs something else).

**Comment by lexigren** [comment]
@christopherthielen what are the possible workarounds? I've used resolver to share data between same state subviews, but in aot mode was forced to switch to shared services, which are not really handy.

**Comment by christopherthielen** [comment]
@lexigren off topic for this issue, but you can inject the resolve tokens into the routed component constructor using `constructor(@Inject('fooResolve') fooResolve)`

**Comment by christopherthielen** [comment]
This is fixed by https://github.com/angular/angular/pull/15214/commits/bd64ab5925e874ccc2a1ef80f08c6c28158e104d and the [public API](https://angular.io/docs/js/latest/api/core/index/ComponentFactory-class.html) added therein
