### ISSUE TITLE
Incorrect rounding with DecimalPipe in IE

### ISSUE THREAD

**Issue by iacii** [angular/angular#14360]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
{{1.15 | number:'1.1-1'}} rounds to 1.1 in IE 11. Works in Chrome.

**Expected behavior**
Rounds to 1.2.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/d15buC5Xu0XbHnqOIsJ1?p=preview

**Comment by vicb** [comment]
Should be fixed in the 5.x branch.
