### ISSUE TITLE
Angular fails to display the component with no errors in the console

### ISSUE THREAD

**Issue by ajayullal** [angular/angular#14377]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Angular fails to display the component with no errors in the console when a small typo is made in the css file.

**Expected behavior**

Without the bug, angular needs to display an error in the console.

**Minimal reproduction of the problem with instructions**

Steps to reproduce:
1.) Create a new component with anular cli (ng g c nav-bar)
2.) Enter boostrap's boilerplate code for navbar component into nav-bar's html template file.
3.) Add a :host {background:red;} (*** instead of ::host{background:red;}) 
4.) Run the app, ng serve.
5.) The component isn't renderd on the screen and the console displays no errors.
6.) Change :host to ::host and then repeat step 4
7.) The component is rendered as expected.

**What is the motivation / use case for changing the behavior?**

N/A
**Please tell us about your environment:**

I'm using Typescript 1.9.1, angular CLI beta 24, Chrome.

* **Angular version:** 2.0.X

No

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 56

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 1.9
* **Node (for AoT issues):** `node --version` =   
6.9.2

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr with repro

**Comment by DzmitryShylovich** [comment]
@ajayullal Pls add a plunkr with repro

**Comment by DzmitryShylovich** [comment]
@ajayullal any feedback or it can be closed?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
