### ISSUE TITLE
Unable to compile when import COMPILER_PROVIDERS

### ISSUE THREAD

**Issue by vivian7169** [angular/angular#14375]
**I'm submitting a bug report**

**Current behavior**
when I ran 'ng serve' after upgraded to 2.4.6, return an error and webpack was failed to compile (error message as below).

**Minimal reproduction of the problem with instructions**
in xxx.module.ts file, included code as below for dynamic component purpose: 
import { COMPILER_PROVIDERS } from '@angular/compiler';

@NgModule({...
  providers: [ COMPILER_PROVIDERS, ...]
})
export class xxxModule { }

Error message as below: 
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 58:17 in the original .ts file), resolving symbol COMPILER_PROVIDERS in /Users/xxx/.../node_modules/@angular/compiler/src/jit/compiler_factory.d.ts, resolving symbol COMPILER_PROVIDERS in /Users/xxx/.../node_modules/@angular/compiler/index.d.ts, resolving symbol xxxModule in /Users/xxx/.../xxx.module.ts, resolving symbol xxxModule in /Users/xxx/.../xxx.module.ts

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/Users/xxx/.../node_modules/typescript/lib/typescript.js:8062:20)
    at Object.createCompilerHost (/Users/xxx/.../node_modules/typescript/lib/typescript.js:44978:26)
    at Object.ngcLoader (/Users/xxx/.../node_modules/@ngtools/webpack/src/loader.js:171:31)
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

**What is the motivation / use case for changing the behavior?**
when run in version 2.4.2, no such an issue

**Please tell us about your environment:**
MacOS 10.12.1

* **Angular version:** 
2.4.6

* **Browser:** all

 

* **Node (for AoT issues):** `node --version` =   
Node 6.9.4

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr with repro

**Comment by vivian7169** [comment]
attached for your investigation.

[test.zip](https://github.com/angular/angular/files/763828/test.zip)

**Comment by DzmitryShylovich** [comment]
https://github.com/shlomiassaf/lazy-jit here you can find an example of aot compilation with `COMPILER_PROVIDERS`

**Comment by DzmitryShylovich** [comment]
@vivian7169 did you fix it?

**Comment by vivian7169** [comment]
Yes, I followed up with the example in lazy-jit and solve the issue. Thanks!

**Comment by DzmitryShylovich** [comment]
@vivian7169 close the issue please. thanks
