### ISSUE TITLE
Angular.io Webpack Intro with VS 2015 Update 3

### ISSUE THREAD

**Issue by miladchamo** [angular/angular#14387]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using the [Angular webpack intro docs/sample](https://angular.io/docs/ts/latest/guide/webpack.html) with Visual Studio 2015 and Typescript 2.  After completing all steps, when I try to start the site via npm start, I get a bunch of compile errors that state 'cannot find promise', 'cannot find map', or 'cannot find require'.

![image](https://cloud.githubusercontent.com/assets/6742750/22804310/77d4d4d0-eee6-11e6-892c-91a800d046ca.png)

**Expected behavior**
I expect the site to build, and then start.  Note, a few months back, I previously followed the same exact steps.  Back then, I believe the dependency was Typscript 1.8 and Angular 2.1.0; and everything worked without issues.  I was probably also using an earlier version of npm/node, I think they were npm 3.3, and node 4.x.

**Minimal reproduction of the problem with instructions**
simply setup an empty MVC project with VS 2015, and follow the steps outlined in the [Angular webpack intro docs](https://angular.io/docs/ts/latest/guide/webpack.html)

**What is the motivation / use case for changing the behavior?**
Having correct documentation/steps documented.

**Please tell us about your environment:**
Windows 7, VS 2015, npm version 3.10.10, node v6.9.5.  **Note, if I use the angular-cli to generate a new angular app, on this same machine, I am able to do so without issues.**

* **Angular version:** 2.0.X
Angular 2.4.0

* **Browser:** 
all
 
* **Language:** 
Typescript

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io/issues

**Comment by miladchamo** [comment]
@DzmitryShylovich done, thank you.

**Comment by DzmitryShylovich** [comment]
@miladchamo close this issue pls. thx
