### ISSUE TITLE
AngularJS static analyzer breaks dynamic components generation 

### ISSUE THREAD

**Issue by metamaker** [angular/angular#14397]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you include `imports` inside your `RuntimeComponentModule`, which is created dynamically using `createComponentModule`, AngularJS static analyzer thinks that parent module, which creates `RuntimeComponentModule`, also has `RuntimeComponentModule`'s imports, and it is not true. Thus in some situations we end up with circular dependencies.

See "use case" section of this issue for detailed description.

**Expected behavior**
Static analyzer should not think that parent module of dynamically created modules includes its children modules imports.

**Minimal reproduction of the problem with instructions**

When imports are not inside `RuntimeComponentModule` order of modules loading is proper, but code fails with syntax error due to unknown component `component-from-module1`:
http://plnkr.co/edit/1omNv59OGABWSw82kbIZ

When imports are inside `RuntimeComponentModule` order of modules loading is wrong, and code fails with syntax error due to Module2 unable to import Module1 (logical, because it wasn't created yet):
http://plnkr.co/edit/aYvxXkRVga8xH57dfpOK

Hack that fixes the problem. Since the order of modules loading becomes improper, `Module2` should use `forwardRef` link to `Module1` and wait for resolution until `Module1` is not loaded. It solves problem, but it is like solving symptoms and not the cause of problem:
http://plnkr.co/edit/hMvaA1DcTYrwJ3Dl8nQq

**What is the motivation / use case for changing the behavior?**
We need to have real components in `FormsModule`  and thin wrapper that can generate them in `DynamicTemplateBundle`. Some components in `FormsModule`, like forms, can use `<sio-dynamic-template-component>` directive to create children components, so we have dependency from `FormsModule` to `DynamicTemplateBundle`. `DynamicTemplateBundle` doesn't import anything except `CommonModule`, so no circular dependency here, but it creates `RuntimeComponentModule` that imports `FormsModule`. `FormsModule` doesn't know about existence of `RuntimeComponentModule`. `RuntimeComponentModule` injects dynamically generated components to some components like forms of `FormsModule`.

So we have next dependencies:

```
`FormsModule` --- (imports) ---> `DynamicTemplateBundle`
`DynamicTemplateBundle` --- (creates, but doesn't import) ---o `RuntimeComponentModule` 
`RuntimeComponentModule` --- (imports) ---> `FormsModule`
```
The problem is that AngularJS thinks that `DynamicTemplateBundle` has `RuntimeComponentModule` 's imports, so we end up with circular dependency `FormsModule` <-----> `DynamicTemplateBundle`, which is not true in reality and can be ommited by using hack for what I created Plunker script above.

* **Angular version:** 2.0.X

2.4.5

* **Browser:** 

all 

* **Language:** 
TypeScipt 2.1.5

* **Node (for AoT issues):** `node --version` =   
7.4.0

SystemJS = 0.19.41

**Comment by tbosch** [comment]
So we have a solution using `forwardRef`, which is exactly intended for the situation you described. I am not sure about having a special case for `import`, as its probably easy to construct other cases as well.

Closing as so far we don't have a better way of expression circular value dependencies in decorators.
