### ISSUE TITLE
Let @Injectable also inject a parent constructor

### ISSUE THREAD

**Issue by nicojs** [angular/angular#14395]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Current behavior**
If i extend the `Http` class, i need to provide a constructor explicitly.

Let's say i have this `Service`:

```typescript
@Injectable()
export class HttpService extends Http {
}
```

And I use it like this:

```typescript
import { NgModule } from '@angular/core';
import { Http, ConnectionBackend } from '@angular/http';
@NgModule({
/*...*/
  providers: [
    { provide: ConnectionBackend, useClass: XHRBackend},
    { provide: Http, useClass: HttpService }
  ]
});
export class AppModule {
}
```

Now i get this error when i try to use `Http`: `TypeError: Cannot read property 'merge' of undefined`. This is because the values `ConnectionBackend` and `RequestOptions` are not provided by the DI container.

However If i add the (for TypeScript redundant) constructor to the `HttpService` it does work:

```typescript
@Injectable()
export class HttpService extends Http {
  constructor(backend: ConnectionBackend, defaultOptions: RequestOptions) {
    super(backend, defaultOptions);
  }
}
```

**Expected behavior**
I would expect that `@Injectable` would also work for implicit parent constructors.

**What is the motivation / use case for changing the behavior?**
It's a feature of TypeScript, so i feel like it should be supported in some way. A tslint warning would be fine with me as well.

**Please tell us about your environment:**
Windows 10.

* **Angular version:** 2.4.7

* **Browser:** Chrome
 
* **Language:** TypeScript 2.1

**Comment by DzmitryShylovich** [comment]
1. Http doesn't actually support inheritance. Use composition over inheritance.
2. In 4.0 http is completely reworked. See https://github.com/angular/angular/pull/14334

**Comment by nicojs** [comment]
@DzmitryShylovich thanks! I didn't know about the `HttpInterceptor`. I will use it as soon as there is an rc.

However, i feel like this DI issue still stands, do you agree?

**Comment by DzmitryShylovich** [comment]
> If i extend the Http class, i need to provide a constructor explicitly.

it's not true https://plnkr.co/edit/3lL7gdr6nrsVJLzhXz4c?p=preview
If you don't specify constructor in child class ts will inherit it from parent.

**Comment by nicojs** [comment]
@DzmitryShylovich hmm indeed, the plnkr works awesomely! Even with http (tried it).

However using angular with cli doesn't work. I've created an example here: https://github.com/nicojs/angular-issue14395

Any ideas about what the problem is here?

**Comment by DzmitryShylovich** [comment]
@nicojs ts 2.1.x is not supported in angular 2.x
try to use ts `2.0.10`

**Comment by DzmitryShylovich** [comment]
@nicojs did you fix it? if not pls re-open on https://github.com/angular/angular-cli/issues

**Comment by nicojs** [comment]
@DzmitryShylovich yeah, i guess that was it. Any idea why that is? Or when ts 2.1 ~ 2.2 etc would be supported?

**Comment by DzmitryShylovich** [comment]
@nicojs 2.1 is supported in angular 4

**Comment by nicojs** [comment]
Thanks for all the help! 👍  I'm curious to know what the big differences are from 2.0 to >=2.1. I'll do a search on that later
