### ISSUE TITLE
Errorhandler does not catch error in hybrid app

### ISSUE THREAD

**Issue by arins** [angular/angular#14394]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am running with upgrade adapter and errorhandler does not catch errors

**Expected behavior**
errorhandler must catch errors

**Minimal reproduction of the problem with instructions**
I have implemented a errorhandler with help of https://angular.io/docs/ts/latest/api/core/index/ErrorHandler-class.html
here is an example
https://plnkr.co/edit/xgyiXw?p=preview
click in ng2 link it should console.log the error but it is not. It is only angular1 which is logging the error to console.

**What is the motivation / use case for changing the behavior?**
to be able to log error

**Please tell us about your environment:**
any

* **Angular version:** 2.0.X
2.4.6

* **Browser:** Chrome
 
* **Language:** typescript

**Comment by gkalpak** [comment]
I think this is expected behavior. The error happens while creating a downgraded component (not inside the component's view for example), so at this point AngularJS (1.x) is still in charge. Thus, the error is passed to AngularJS's `$exceptionHandler`.

If you want all errors passed through your custom error handler, you can overwrite the built-in `$exceptionHandler` with yours (as shown [here][1]):

```ts
angular.module('testing').value('$exceptionHandler', downgradeInjectable(ErrorHandler))
```

[1]: https://plnkr.co/edit/iUHoIT?p=preview

**Comment by petebacondarwin** [comment]
You don't even need to pass the error on explicitly.  Just throwing it in the exception handler is enough for it to arrive at the Angular error handler:

```js
angular.module('testing').value('$exceptionHandler', function(error) { throw error; });
```

**Comment by arins** [comment]
somehow the exception was lost when using the first example done by @gkalpak. So I tried to use the second example by @petebacondarwin but with the same result. But I saw that error in his function actually was the original exception so i just injected my CustomErrorHandler and called handleError manually and it worked. See example https://plnkr.co/edit/zmUfqB?p=preview. Thanks for both for your help!
