### ISSUE TITLE
Minor error in documentation

### ISSUE THREAD

**Issue by nikosgpet** [angular/angular#14398]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In the angular documenation 
https://angular.io/styleguide#!#04-10

It's writtent : 
**Do** _not_ provide services in shared modules. Services are usually singletons that are provided once for the entire application or in a particular feature module.

**Expected behavior**

**Do** should be used for positive phrases, **Avoid** for negative phrases. 

The advice is really contradicting, especially given that services **_are_** used in the shared module given as example below this advice.

Depending on what you actually meant the phrase should either be changed to : 

**Avoid** providing services in shared modules. Services are ...
or 
**Do** provide services in shared modules. Services are ...

**Minimal reproduction of the problem with instructions**

Visit the documentation at https://angular.io/styleguide#!#04-10

**What is the motivation / use case for changing the behavior?**

Improve documentation.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls re-open this issue on https://github.com/angular/angular.io/issues

**Comment by nikosgpet** [comment]
Ooops, will do. Thanks ;)

**Comment by DzmitryShylovich** [comment]
pls close this issue. thx
