### ISSUE TITLE
Dirty/Pristine not restored on undo

### ISSUE THREAD

**Issue by staeke** [angular/angular#14401]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As this is such a common thing, I'm expecting this is by design. Still I find it slightly bad (and different from Angular 1). As I couldn't find any similar issue, I'm reporting it (note that it's slightly similar to https://github.com/angular/angular/issues/12116 but that talks about programmatic model changes, not user interaction). 

Template driven forms. User changes a text input. It becomes dirty. Then changes back (e.g. by action Undo in the browser). The control is still dirty.

**Expected behavior**
I'd expect dirtyness to be removed/pristine state restored

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/M9u2ShsmhlkddME6Tpgo?p=preview

**What is the motivation / use case for changing the behavior?**
It's such a common scenario to display enable a submit or similar ONLY if the user actually has changed the form. And it was possible with Angular 1. If you don't want to change dirty/pristine, may I recommend adding a new variable pair (maybe changed/unchanged)

* **Angular version:**
2.4.7

* **Browser:**
all

**Comment by wKoza** [comment]
With AngularJS, the behavior is the same for dirty state : https://demos.scotch.io/angular-validation/demos/
no ?

**Comment by tbosch** [comment]
@kara Is this works as intended?

**Comment by kara** [comment]
Yes, this works as intended. The dirty flag is intended to mark when the end user changes the value, which should still be true if they change it back to the original value.

**Comment by ToniaDemchuk** [comment]
Is there any workaround to override this default behavior and check value changes?
