### ISSUE TITLE
What is the proper way to deal with exceptions in a router resolver?

### ISSUE THREAD

**Issue by marclerman** [angular/angular#14403]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have defined a resolver in my route. The resolver calls a web service. If the http call fails, I catch the exception in the resolve() method, like so:

public resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<any> {
    return this.callWebService().
    first().
    catch(e => {
        toast.show(e);
        return Observable.throw(e);
    }
}

The first time we get the exception, we get a NavigationError from the router and the exception is shown on the console (indicating the exception was not caught). The second time, we only get a NavigationError.

**Expected behavior**
I would have expected nothing to be displayed on the console, since the exception was indeed caught in the resolver.

What is the best way if dealing with exceptions so that the router will not navigate to the target path if there is one? If this is the proper way, then:

(1) this should be documented
(2) we should not get the exception on the console, ever

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
Angular 2.4.6.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
```
catch(e => {
toast.show(e);
return Observable.empty();
}
```
This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by marclerman** [comment]
Thanks for the code.
I am however going to change this to a bug: although the behavior is what I was hoping for (no navigation and the application does not crash when I handle the exception in the catch), the console still reports that the exception had not been caught (no element in the sequence with the code that returns Observable.empty()), and it does that only the first time --which is what I had reported originally.

**Comment by DzmitryShylovich** [comment]
> the console still reports that the exception had not been caught 

ofc, because you are re-throwing it :)

**Comment by marclerman** [comment]
Thanks for your comment.
Well, that is sort of my point: whatever I return or throw from my resolver, I expect this to become a NavigationError, without any exception being logged on the console indicating that the exception had not been caught --the router code should catch it and make it become a Navigation Error. No?

**Comment by DzmitryShylovich** [comment]
An error inside a resolver doesn't mean navigation error to me. See https://github.com/angular/angular/issues/13873

**Comment by marclerman** [comment]
OK so what I understand from @JohannesRudolph in [#13873](https://github.com/angular/angular/issues/13873) is that the router will not navigate if the returned Observable completes or errors.
This is what I want in my case: I do not want it to navigate when there is an error fetching data from my web service when I do a resolve, and I also do not expect an exception on the console --I want a clean way to let the router know: please do not navigate because something happened.
Maybe this is just a documentation issue?

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
