### ISSUE TITLE
Router should fire event for successful CanActivate/CanDeactivate checks

### ISSUE THREAD

**Issue by ylibrach** [angular/angular#14404]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The router will fire a `NavigationStart` event on a route change, as expected. However, if the route has a guard such as `CanDeactivate`, there will be no further events fired until either `NavigationCancel` or `NavigationEnd`.

**Expected behavior**
The router should fire an additional event (such as something like `NavigationConfirm`) and/or provide some mechanism for determining that a guard is pending or confirmed (for reasons described below).

**What is the motivation / use case for changing the behavior?**
We have a thin progress bar at the top of the page that gets activated on `NavigationStart` event, and ends on `NavigationEnd` (somewhat similar to YouTube's progress bar). However, we have some pages that have a `CanDeactivate` guard for showing a modal with "are you sure you want to leave this page and lose your changes?" 

The `CanDeactivate` guard runs after `NavigationStart` fires, meaning the progress bar starts showing at the top of the page while the modal is active, despite the fact that the user has not actually confirmed that they want to navigate away from the page. If they click cancel, the `NavigationCancel` event is fired and the progress bar disappears, but we ideally don't want to show the progress bar at all until the user actually confirmed that they want to navigate away.

If the router provided an event such as `NavigationConfirm` which happens *after* all guards, then it would be possible to react to confirmed navigation changes.

**Comment by DzmitryShylovich** [comment]
@ylibrach `RoutesRecognized`?

**Comment by ylibrach** [comment]
@DzmitryShylovich you had written a reply about `RoutesRecognized` but I'm not seeing it anymore. Regardless, we've tested `RoutesRecognized` and it doesn't seem to provide this capability or solve this problem. The event is fired prior to any guards completing.

**Comment by DzmitryShylovich** [comment]
As a workaround you can emit custom events yourself:
```
constructor(private router: Router) {}
canDeactivate() {
   (<any>this.router).routerEvents.next(new MyCustomCanDeactivateEvent());
   return true;
}
```

**Comment by ylibrach** [comment]
Thanks @DzmitryShylovich, we'll try this as a workaround for now. Is it possible for the framework itself to emit such an event in the future?

**Comment by DzmitryShylovich** [comment]
maybe :)

**Comment by jasonaden** [comment]
We've added a couple new events recently. Since there's a workaround as above, I don't want to add more events as they bloat the codebase.
