### ISSUE TITLE
[4.x] Forms module refactoring

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#14411]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

There some outstanding issues with forms module:
1. parsers & formatters https://github.com/angular/angular/issues/3009
2. observable validators https://github.com/angular/angular/issues/9119
3. ability to specify event for validation https://github.com/angular/angular/issues/7113
4. ability to dynamically change input type https://github.com/angular/angular/issues/13243 (it doesn't work at all with the current design (ControlValueAccessors) because angular doesn't dynamically initialize directive when attributes change).

All of these require serous refactoring or even rewrite. There's some time before 4.0 when we can still make breaking changes otherwise we will be locked for the next 6 months.

Would be nice to address this before 4.0 release. 
What do you think? @kara 

There's a proposal to embrace the idea of `controlled components` from react https://github.com/angular/angular/issues/5184 . I'm not very familiar with react but it can be useful I guess.

**Comment by StephenFluin** [comment]
@DzmitryShylovich thanks for your feature request.

Some of these are definitely features that we want to add to forms, including parsers & formatters being one of our top priorities.

We'd definitely welcome your contributions, but each of these major features needs a design document. We've implemented a process internally that forces major changes like this to go through a design review, and we're hoping to share this document with the community very soon. In particular, we already have some work started on parsers and formatters, so you probably want to wait to see that before getting started on anything.

In terms of getting these things in for 4, the schedule has us going to RC next week, so I don't think we will have time to land these for 4, even with your help.

There are already issues for the subfeatures you list, and we definitely are aware of these, so I'm going to close this issue. Thanks again for sharing your desire and time to make forms great.
