### ISSUE TITLE
ngc with AOT: support deprecations

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/angular#14410]
Consider the situation where I want to deprecate the static `.forRoot()` call in a library module.
I want to warn the developers that the call will soon be deprecated.

```js
/**
 *
 */
@NgModule({
  declarations: ALL_DIRECTIVES,
  imports: [MediaQueriesModule],
  exports: [MediaQueriesModule, ...ALL_DIRECTIVES],
  providers: [ MediaMonitor ]
})
export class FlexLayoutModule {
  /** @deprecated */
  static forRoot(): ModuleWithProviders {
    console.warn('FlexLayoutModule.forRoot() has been deprecated and is no longer needed.');
    return {
      ngModule: FlexLayoutModule
    };
  }
}
```

Application developers using the `FlexLayoutModule.forRoot()` calls  and compiling with **ngc** and AOT,  will see the following error:

```console
Error encountered resolving symbol values statically. 
Calling function 'FlexLayoutModule', function calls are not supported. 
Consider replacing the function or lambda with a reference to an exported function, 
resolving symbol AppModule in /Users/thomasburleson/Desktop/ng2-aot-demo/builds/release/app.module.ts, 
resolving symbol AppModule in /Users/thomasburleson/Desktop/ng2-aot-demo/builds/release/app.module.ts
```

---- 

Discussions with @vicb:

The 'forRoot()' fn is never evaluated in AoT, ngc only analyzes the content of the fn to get the module and ngc does not know what to do with the first statetement (console.warn).

One possible solution would be to introduce a `@deprecated` annotation that would be understood by ngc

**Comment by ThomasBurleson** [comment]
Ping @LucasSloan

**Comment by trotyl** [comment]
> The 'forRoot()' fn is never evaluated in AoT, ngc only analyzes the content of the fn to get the module and ngc does not know what to do with the first statetement (console.warn).

Fixed by Ivy, any provider expression will be evaluated at runtime. So https://github.com/angular/angular/issues/11996 would be enough.

**Comment by JoostK** [comment]
This restriction has been lifted with Ivy now that #37126 has been merged. As there's a more general feature request for dealing with deprecations in #11996, I'll go ahead and close this.
