### ISSUE TITLE
dead lock when use async pipe dynamically

### ISSUE THREAD

**Issue by naivefun** [angular/angular#14416]
The code is frozen so I cannot provide plnkr link, however the code is very simple:

![screen shot 2017-02-11 at 9 42 53 am](https://cloud.githubusercontent.com/assets/10683378/22850067/e3e8b3ae-f03e-11e6-94e7-1d115e150050.png)

The use case is that I need resolve some properties on the fly so I am trying the async pipe style and it simply dead. From what I observe the function is called infinitely but I do not know why? Thanks.

**Comment by DzmitryShylovich** [comment]
Do not use functions in interpolations and bindings.

**Comment by naivefun** [comment]
@DzmitryShylovich  what if I use OnPush change detection?

**Comment by dejour** [comment]
no, I think it has nothing to do with `OnPush `change dectection

**Comment by naivefun** [comment]
@dejour  May I say Promise/Observable bypasses `OnPush` detection?
