### ISSUE TITLE
OpaqueToken not resolved

### ISSUE THREAD

**Issue by jeusdi** [angular/angular#14427]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Opaque token is not resolved from a third-party library.

**Expected behavior**

Opaque token imported from third-party library is resolved.

**Minimal reproduction of the problem with instructions**
I've created a library where I declare several services like:

    @Injectable()
    export class UsersService {
        protected basePath = 'http://localhost/commty/cmng';
    
        constructor(@Optional()@Inject(BASE_PATH) basePath: string) {
            if (basePath) {
                this.basePath = basePath;
            }
        }
    }

On this library, I'm using an `OpakeToken` in order to get `UsersService`'s `basePath` constructor parameter. This parameter is defined on `variables.ts` as:

    export const BASE_PATH = new OpaqueToken('basePath');

On this library, I've created a module called `ApiModule`:

    @NgModule({
      imports:      [ CommonModule, HttpModule ],
      declarations: [],
      exports:      [],
      providers:    [ PlansService, UsersService ]
    })
    export class ApiModule {}

I've published this library and it's used as an straightforward npm dependency package on my `webapp`: `"@living/cest": "0.1.0-unstable0028"`.

**On my `webapp`**, I've created an `environtment.ts` file in order to set this `OpaqueToken`:

    ENV_PROVIDERS = [
      { provide: BASE_PATH, useValue: 'http://localhost:8082/commty/cmng' }
    ];

I'm using `ngrx` in order to create my internal behavior using a reflux model. I've created three modules: `AppModule`, `CoreModule` and `SharedModule`:

    import { ENV_PROVIDERS } from './environment';

    @NgModule({
      bootstrap: [ AppComponent ],
      declarations: [ AppComponent, ErrorComponent ],
      imports: [
        BrowserModule,
        CoreModule,   <<<<<<<<<<<<<<<<
        SharedModule, <<<<<<<<<<<<<<<<
        RouterModule.forRoot(ROUTES, { useHash: true })
      ],
      providers: [
        ENV_PROVIDERS
      ]
    })
    export class AppModule { ... }

So, I'm setting `ENV_PROVIDERS` (`BASE_PATH` opaque token provider) in `AppModule`, and I'm importing `CoreMoudle` and `SharedModule`.

I'm using `UsersService` inside all my `@Effect`s:

    @Injectable()
    export class UserEffects {
      constructor(
        private _actions$: Actions,
        private _store$: Store<IStore>,
        private _userService: UsersService,
      ) { }
    
      @Effect({ dispatch: true }) userLogin$: Observable<Action> = this._actions$
        .ofType('USER_REDUCER_USER_LOGIN')
        .switchMap((action: Action) =>
          this._userService.checkPasswd(action.payload.username, action.payload.password)
            .map((user: any) => {
              return { type: 'USER_REDUCER_USER_LOGIN_SUCCESS', payload: user };
            })
            .catch((err) => {
              return Observable.of({
                type: 'USER_REDUCER_USER_LOGIN_ERROR',
                payload: { error: err }
              });
            })
        );
    }

Each `@Effect` is bootstraped on `CoreModule`:

    @NgModule({
      imports: [
        ApiModule,
        StoreModule.provideStore(getRootReducer),
        StoreDevtoolsModule.instrumentOnlyWithExtension(),
        EffectsModule.runAfterBootstrap(UserEffects)
      ],
    })
    export class CoreModule { }

As you can see, I'm importing `ApiModule` once in `CoreModule`. This `CoreModule` is imported once in `AppModule`.

By other hand `SharedModule` stands for providing `ngrx` functionality to all components of `webapp`:

    export const modules = [
      StoreModule,
      StoreDevtoolsModule
    ];
    
    export const declarations = [];
    
    @NgModule({
      imports: modules,
      exports: [...modules, ...declarations],
      declarations
    })
    export class SharedModule { }

I'm really check everything out, but `UsersService`'s `basePath` constrcutor parameter is not resolved to my url, it's always `null`.

I've took a look on debugger in order to find out what's wrong. Up to now I've been able to see that angular is trying to resolve `UsersEffect`'s `_userService` constructor parameter injectable. This code is reached:

    Object.defineProperty(AppModuleInjector.prototype, '_UserEffects_77', { get: function() {
      var self = this;
      if ((self.__UserEffects_77 == null)) { (self.__UserEffects_77 = new jit_UserEffects63(self._Actions_60,self._Store_62,<b>self._UsersService_47</b>)); }
      return self.__UserEffects_77;
    }});

Also, this code is generated but never reached:

    Object.defineProperty(AppModuleInjector.prototype, '_Token_basePath_81', { get: function() {
      var self = this;
      if ((self.__Token_basePath_81 == null)) { (self.__Token_basePath_81 = 'http://localhost:8082/commty/cmng'); }
      return self.__Token_basePath_81;
    }});

`LoginModule` is lazily loaded using this router configuration:

    export const ROUTES: Routes = [{
       path: '', redirectTo: 'login', pathMatch: 'full'
      }, {
        path: 'login', loadChildren: () => System.import('./login/login.module')
      }, {
        path: 'error', component: ErrorComponent
      }, {
        path: '**',    component: ErrorComponent
      }
    ];

`SharedModule` and `CoreModule` are eagerly loaded.

I hope I've explained so well.

**EDIT**

I've also tried to remove `CoreMoudule` and `SharedModule` and import everything on `AppModule`. Nevertheless, `BASE_PATH` opaque token keeps faling to resolve any value:

    @NgModule({
      bootstrap: [ App ],
      declarations: [
        App,
        ErrorComponent
      ],
      imports: [ // import Angular's modules
        BrowserModule,
        ApiModule,
        StoreModule.provideStore(getRootReducer),
        StoreDevtoolsModule.instrumentOnlyWithExtension(),
        EffectsModule.runAfterBootstrap(UserEffects),
        //CoreModule,
        //StoreModule,
        //StoreDevtoolsModule
        //SharedModule,
        RouterModule.forRoot(ROUTES, { useHash: true })
      ],
      providers: [ // expose our Services and Providers into Angular's dependency injection
        ENV_PROVIDERS,
        APP_PROVIDERS
      ]
    })
    export class AppModule {

**What is the motivation / use case for changing the behavior?**
I don't quite know. I'm using latest version.

**Please tell us about your environment:**

* **Angular version:** 2.4.6

* **Browser:** [Firefox XX | all]

 
* **Language:** [TypeScript 2.1.5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a small repro...

**Comment by jeusdi** [comment]
I've set up this repository: https://github.com/jeusdi/issueAngular

**Comment by jeusdi** [comment]
Have you been able to take a look on repository?

**Comment by DzmitryShylovich** [comment]
I can't even install it
> '@living/cest' is not in the npm registry.

**Comment by jeusdi** [comment]
Sorry, could you add

    npm adduser --registry=http://nuget.living-digital-way.com:81/npm/npm_unstable --scope=@living --always-auth

Please warn me as soon you have installed package correctly.
This is third-party package I talked above.

**Comment by jeusdi** [comment]
Have you been able to install it?

**Comment by jeusdi** [comment]
Have you had any problems? Is everything right?

**Comment by jeusdi** [comment]
Please @DzmitryShylovich , could you tell me something? Are you working on it? Is there any problem?

**Comment by DzmitryShylovich** [comment]
No, I'm not. I don't have free time now.

**Comment by jeusdi** [comment]
@DzmitryShylovich , have you been able to take a look on?

Please, sorry for asking you for it again. Nevertheless, I'm still sticking in solving that.

**Comment by DzmitryShylovich** [comment]
@jeusdi have you tried 4-rc2? `OpaqueToken` was deprecated

**Comment by jeusdi** [comment]
I'm using these dependencies by now:

```
dependencies": {
    "@angular/common": "2.4.6",
    "@angular/compiler": "2.4.6",
    "@angular/core": "2.4.6",
    "@angular/forms": "2.4.6",
    "@angular/http": "2.4.6",
    "@angular/platform-browser": "2.4.6",
    "@angular/platform-browser-dynamic": "2.4.6",
    "@angular/platform-server": "2.4.6",
    "@angular/router": "3.4.6",
    ...
```

**Comment by bammadamma** [comment]
Hi 
Just updated to angular v4 
I used OpaqueToken before which used to work fine.
Then got the error No provider for Token api.config  ...
Investigated the error and found out that OpaqueToken is deprecated in favour InjectionToken:  replaced the code for OpaqueToken with  

export let BLOG_CONFIG = new InjectionToken<string>('blog.config');
export let APP_CONFIG = new InjectionToken<string>('app.config');
export let API_SERVICE_CONFIG = new InjectionToken<string>('api.config');

I have nor changed all other code where the token is used. For example:

 {provide: BLOG_CONFIG, useValue: APP_DEFAULT_BLOG_CONFIG},

and usage when injecting I did as was the case  for OpaqueToken as

@Inject(BLOG_CONFIG) public wpr: IAppBlogConfig

But I am getting the same error as OpakeToken with the exception InjectionToken is now mentioned in the error. see below.  
Am I doing something not right?  Please help with example how to implement InjectionToken

The error I am getting
ERROR Error: No provider for InjectionToken api.config!
    at injectionError (reflective_key.ts:1) [angular]
    at noProviderError (reflective_key.ts:44) [angular]
    at ReflectiveInjector_._throwOrNull (application_tokens.ts:1) [angular]
    at ReflectiveInjector_._getByKeyDefault (application_tokens.ts:53) [angular]
    at ReflectiveInjector_._getByKey (application_init.ts:54) [angular]
    at ReflectiveInjector_.get (reflective_injector.ts:547) [angular]
    at AppModuleInjector.NgModuleInjector.get (profile.ts:24) [angular]
    at resolveDep (pure_expression.ts:83) [angular]
    at createClass (provider.ts:594) [angular]
    at _createProviderInstance (provider.ts:552) [angular]
    at createProviderInstance (provider.ts:371) [angular]
    at createViewNodes (view.ts:518) [angular]
    at callViewAction (services.ts:215) [angular]
    at execComponentViewsAction (services.ts:143) [angular]

**Comment by DzmitryShylovich** [comment]
```
{provide: BLOG_CONFIG, useValue: APP_DEFAULT_BLOG_CONFIG},
{provide: APP_CONFIG , useValue: {}},
{provide: API_SERVICE_CONFIG , useValue: {}},
```

**Comment by bammadamma** [comment]
@DzmitryShylovich  Thank you for getting back to me !

I did exactly that as I indicated in my previous message context.  But I am getting the error message

ERROR Error: No provider for InjectionToken api.config!
    at injectionError (reflective_key.ts:1) [angular] .....

I have checked using ncu to check if my dependencies are all up to date and all are up to date.

Also checked here (https://angular.io/docs/ts/latest/api/core/index/FactoryProvider-interface.html)  where InjectionToken is used. I used it in the similar fashion but still getting the error.
The only diff is the way how the new InjectionToken is used when injecting in the constructor, which I could not find and documentation.  I used it in similar fashion as used to be in OpaueToken ... here is an example of how I used it  //
 constructor(public wp: WpService, @Inject(BLOG_CONFIG) public wpr: IAppBlogConfig)

I am learning Angular and so far it was going well now started breaking after updating to V4

**Comment by DzmitryShylovich** [comment]
@bammadamma please reproduce here http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by bammadamma** [comment]
@DzmitryShylovich  I can not seem to reproduce it in plunker @ http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

It seems it is working fine .. Thank you for your help. I will revisit my code and try to debug code.
Thank you once again!!!!

**Comment by jeusdi** [comment]
```
@DzmitryShylovich I've update angular version to latest one: 4.0.2. It keeps failing.

I'm an exhausted man. I don't really getting what's wrong.

I only have a single PROVIDERS on `variables.ts`:

// Development
  PROVIDERS = [
    ...PROVIDERS,
    // custom providers in development
    { provide: BASE_PATH, useValue: 'http://guest1:8080/commty/cmng' }
  ];

export const ENV_PROVIDERS = [
  ...PROVIDERS
];
```

So in `app.module.ts` I import it and I'm setting in AppModule `providers`:

import { ENV_PROVIDERS } from './environment';
```
@NgModule({
  bootstrap: [ App ],
  declarations: [
    App,
    ErrorComponent
  ],
  imports: [
    CoreModule,
    SharedModule,
  ],
  providers: [
    ENV_PROVIDERS
  ]
})
export class AppModule {
```

Into `CoreModule` I'm importing `ApiModule`:
```

@NgModule({
  imports: [
    ApiModule
  ],
  exports: [ ],
  providers: []
})
export class CoreModule { }
```

`ApiModule` is who declares `BASE_PATH` as `InjectionToken` but it's never resolved!

I'm trying to solve that but I've really stuck with this issue. I don't quite figure out what's wrong.

**Comment by gilbertowa** [comment]
I receivied error "No provider for InjectionToken api.config! ", when my token was declared in main.ts file.
I changed location and works.
