### ISSUE TITLE
ngFor inside ngFor - Angular 2

### ISSUE THREAD

**Issue by fahidmohammad** [angular/angular#14428]
ngFor doesn't work with multidimensional array using.
Below is the DOM Wrapper im using:

    <li *ngFor="let menuName of menuNames" routerLinkActive="active" [ngClass]="{'has-submenu':menuName.submenu?.length>0 }">
    	<a href="#" [routerLink]="menuName.route" *ngIf="!menuName.enableSM"> <i class="glyphicon {{menuName.icon}}"></i><span class="nav-label">{{menuName.name}}</span> </a>
    	<a href="#" *ngIf="menuName.enableSM"> <i class="glyphicon glyphicon-list-alt"></i> <span class="nav-label">Pages</span> </a>
    	<ul class="list-unstyled" *ngIf="menuName.enableSM">
    		<li *ngFor="let subMenuName of menuName.submenu"> <a [routerLink]="subMenuName.route">404</a> </li>
    	</ul>
    </li>

And the nested array:

    menuNames = [{
    	name: "Dashboard",
    	route: '/home',
    	icon: "glyphicon-th-large",
    	submenu: [],
    	enableSM: false
    }, {
    	name: "Pages",
    	route: '',
    	icon: "glyphicon-list-alt",
    	submenu: [{
    		name: "404",
    		route: '/404.html'
    	}, {
    		name: "Signin",
    		route: '/auth/signin'
    	}],
    	enableSM: true
    }];
The second loop does not render at all.

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr with repro

**Comment by fahidmohammad** [comment]
Sorry it was an compile error, its working  now after initiating the ng serve from scratch.

**Comment by DzmitryShylovich** [comment]
@fahidmohammad then close the issue. thx
