### ISSUE TITLE
Animations transitions with target disordered when change value by the index of ngFor

### ISSUE THREAD

**Issue by blackcatIan** [angular/angular#14422]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Animations transitions with target disordered when change value by the index in ngFor.
In the Minimal example,animations transitions effected in 'menu 1-4',they change color, it's wrong.
You must click a lot of times 'menu 1-4'  when 'menu 1' is changing color to reproduce the bug.

**Expected behavior**

Animations transitions should be worked with right target.
In the Minimal example,animations transitions should not be worked,since state in variable 'hero' nerver changed

**Minimal reproduction of the problem with instructions**

Minimal example:

app.component.ts
```
import {Component, state, style,transition,animate, trigger} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  animations: [
    trigger('heroState', [
      state('open', style({
        backgroundColor: 'yellow'
      })),
      state('close', style({
        backgroundColor: 'skyblue'
      })),
      transition('open <=> close', animate('3000ms linear')),
    ])
  ]
})
export class AppComponent {

  arr = [true, false, false, false];

  hero = [
    'open', 'close', 'close', 'close'
  ];

  close(index) {
    this.arr[index] = !this.arr[index];
  }
}

```

app.component.html
```
{{arr}}

<ul>
  <li *ngFor="let peek of arr;let i = index">
    <a (click)="close(i)">{{i+1}}menu</a>
       <ul  [@heroState]="hero[i]">
        <li>arr-peekOne:{{peek}}</li>
        <li>animate-status-peekOne:{{hero[i]}}</li>
      </ul>
  </li>
</ul>
```

In the example,when you click severial times different menu from 'menu 1-4' quickly ,you can see the "animate-status-peekOne" never change in "menu 1-4" but the animation make the transition,it's wrong.

**Please tell us about your environment:**

window 7
webstrom 2017.1 EAP

* **Angular version:** 2.4.7

* **Browser:**Chrome 56.0.2924.76

 

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by Toxicable** [comment]
I would suggest using a trackBy function

**Comment by blackcatIan** [comment]
@Toxicable Thank you.You are right.It works well if use trackBy.

It look when using ngFor with animation,we must use trackBy, otherwise angular will make new element that cause animation looks like disordered.

**Comment by Toxicable** [comment]
This isn't just for animations,  this is for any situation where you're changing the contents of a list then displaying it with a ngFor since the default way that Angular track elements is by index position which is very fragile when you're editing the indexes.
