### ISSUE TITLE
is not assignable to parameter of type 'Component' Object literal may only specify know properties, and directives does not exist in type 'Component'

### ISSUE THREAD

**Issue by chavda141286atul** [angular/angular#14420]
Hi,

I want to transfer data between 2 component here bellow is my parent component code but i have problem while using directives its always show me error like bellow :

[**Error** : "is not assignable to parameter of type 'Component' Object literal may only specify know properties, and directives does not exist in type 'Component'"]

Bellow is my parent component.

import { Component } from '@angular/core';
import { LoadableData } from '../../models/common';
import { TextLookup } from '../../models/common';
import { ActivatedRoute, Router } from '@angular/router';
import { ChildCoponent } from "./child.test";

@Component({
    selector: 'parent-selector',
    template: 'parent.component.html',
    directives: [ChildCoponent]    
})
export class ParentComponent { }

can you please guide me if i am wrong thanks

Atul.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by chavda141286atul** [comment]
Ok I can understand thanks...

**Comment by lazarljubenovic** [comment]
`directives` in `@Component` has been removed in [2.0.0-rc.5](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc5-2016-08-09) which was _long_ ago. You now declare components in an [NgModule](https://angular.io/docs/ts/latest/guide/ngmodule.html).

Please close this issue since it's a request support and is not suitable for the issue tracker.
