### ISSUE TITLE
angular2  : When i press F5 or refresh the page, the page content has not changed  ！

### ISSUE THREAD

**Issue by Christian-Yang** [angular/angular#14437]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

after npm  run build.prod   ,i  get a  production .
When i  press F5 or refresh the page, the page content has not changed.
I must clear all the history of the browser in order to see the latest page.
Often this happens on some pages<br/>
**Expected behavior**

I expect to see new data from the server.
When i  press F5 or refresh the page, the page content has changed.
<br/>
**Minimal reproduction of the problem with instructions**
nothing

**What is the motivation / use case for changing the behavior?**

nothing
**Please tell us about your environment:**

$:uname   -v
~precise1-Ubuntu SMP Fri Dec 18 10:38:55 UTC 2015

IDE: webstorm 

package manager:  gulp": "^3.8.32",

http server :   nginx

angular-seed:
"name": "angular-seed",
  "version": "0.0.0",
  "description": "Modular starter project for Angular 2 (and beyond) with statically typed build and AoT compilation",
  "repository": {
    "url": "https://github.com/mgechev/angular-seed"
  },

 "@angular/compiler-cli": "^2.1.0",
    "@angular/platform-server": "^2.1.0",
    "@angular/tsc-wrapped": "^0.3.0",
    "@types/async": "^2.0.32",
    "@types/browser-sync": "^0.0.34",
    "@types/core-js": "^0.9.34",
    "@types/express": "^4.0.33",
    "@types/gulp": "^3.8.32",
    "@types/gulp-load-plugins": "^0.0.28",
    "@types/gulp-protractor": "^1.0.29",
    "@types/gulp-sass": "^0.0.29",
    "@types/gulp-util": "^3.0.29",

* **Angular version:** 2.0.X

in  package.json  , i get followings:
 "@angular/common": "^2.1.0",
    "@angular/compiler": "^2.1.0",
    "@angular/core": "^2.1.0",
    "@angular/forms": "^2.1.0",
    "@angular/http": "^2.1.0",
    "@angular/platform-browser": "^2.1.0",
    "@angular/platform-browser-dynamic": "^2.1.0",
    "@angular/router": "^3.1.0",
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome  : version 56.0.29
Firefox: version  51.0.0
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript   1.8.10

* **Node (for AoT issues):** `node --version` =   v6.9.0

Thanks  very much  for help me  !!!

**Comment by DzmitryShylovich** [comment]
Sounds like server/browser caching issue

Pls add a repro

**Comment by Christian-Yang** [comment]
@DzmitryShylovich  

Really sorry，I can not provide a repro.

But,I have the following information：

![prob1](https://cloud.githubusercontent.com/assets/25613332/22963102/ea264dd0-f38b-11e6-851a-4234d2d7b8cc.png)

And  i found the preview content is the main page (index.html ) of my project. The content of the response  is the html souce code of index.html  

Looking forward to your help, this problem bothers me for a long time.

Thank you again.

**Comment by mohamedelmancy** [comment]
this is an cashing issue and the solution is press ctrl + f5 and will update the content
