### ISSUE TITLE
upgrade AngularJS to Angular guide

### ISSUE THREAD

**Issue by IgorZh** [angular/angular#14434]
Hello, **I'm submitting a bug**
I try use that [guide](https://angular.io/docs/ts/latest/guide/upgrade.html#!#phonecat-upgrade-tutorial). I follow all instructions. When I finished paragraph **Bootstrapping a hybrid PhoneCat** I get erron in my App

**Current behavior**

```
Unhandled Promise rejection: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at ZoneDelegate.invoke (http://localhost:8000/node_modules/zone.js/dist/zone.js:242:26)
	    at Zone.run (http://localhost:8000/node_modules/zone.js/dist/zone.js:113:43)
	    at http://localhost:8000/node_modules/zone.js/dist/zone.js:535:57
	    at ZoneDelegate.invokeTask (http://localhost:8000/node_modules/zone.js/dist/zone.js:275:35)
	Evaluating http://localhost:8000/app
	Error loading http://localhost:8000/app ; Zone: <root> ; Task: Promise.then ; Value: 
```

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
