### ISSUE TITLE
Direct Contradiction in Angular Documentation

### ISSUE THREAD

**Issue by justinwilaby** [angular/angular#14439]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This is a documentation defect found in the [Respond to user-initiated events](https://angular.io/docs/ts/latest/guide/attribute-directives.html#!#respond-to-user) section.  In this section, 3 reasons are provided as to why you should use `@HostListener` instead of attaching an event listener directly to the DOM element manually.  Number 3 states: `Talking to DOM API directly isn't a best practice.` but then the example given in the documentation *talks directly to the DOM api*.
```js
private highlight(color: string) {
    this.el.nativeElement.style.backgroundColor = color; // This is talking directly to the DOM api directly contradicting the 3rd reason listed above. 
  }
```

**Expected behavior**
Provide an example that does not contradict the advice given in the documentation.

**Minimal reproduction of the problem with instructions**
Open https://angular.io/docs/ts/latest/guide/attribute-directives.html#!#respond-to-user and scroll down a few lines to the example provided.

**What is the motivation / use case for changing the behavior?**
To improve the quality and credibility of the documentation.

**Please tell us about your environment:**
Any Browser

* **Angular version:** 2.0.X
Angular 2+

* **Browser:** all
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls report docs issues on https://github.com/angular/angular.io/issues
