### ISSUE TITLE
Cannot use *ngIf to manipulate input fields inside a form

### ISSUE THREAD

**Issue by paul-thomas0** [angular/angular#14432]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If we try to put a structural *ngIf attribute directive inside a input element in a form
to make it appear on certain conditions and not on others. And when we try to access the
DOM of the element using #ControlOfTheInput it shows the element is undefined as if the
DOM wasn't created.
**Expected behavior**

It is expected that if the condition is true the input field should be accessible
**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/EhLdqIt931SJB0MsvVVq

**What is the motivation / use case for changing the behavior?**

To be able to conditional change form elements in a form when certain conditions have been fulfilled
**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Plunkr doesn't work

**Comment by paul-thomas0** [comment]
Here: https://plnkr.co/edit/EhLdqIt931SJB0MsvVVq

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/Zw0VzTpuvp6i0oy0ffAh?p=preview

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/13974

**Comment by paul-thomas0** [comment]
So for conditionally inserting/removing input fields inside a form and if I want to use *ngIf for that I would have to write that input field into a template tag and bind ngIf directive to it?

**Comment by paul-thomas0** [comment]
I will close this then.
