### ISSUE TITLE
please update https://code.angularjs.org/ 

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular#14447]
cdnjs   https://cdnjs.com/libraries/angular.js   

can not find angular 2 rc in cdnjs

because cdnjs  used https://code.angularjs.org/  data 

**look:**
https://github.com/cdnjs/cdnjs/issues/8102#issuecomment-223673419

They waiting for rc1 been release on https://code.angularjs.org/ ！

😄

**Comment by trotyl** [comment]
There is no full-bundle any more since the rc version.

**Comment by iloveyo123u1** [comment]
@trotyl   how to find angular2 in cdnjs

**Comment by trotyl** [comment]
@iloveyo123u1 There is no angular bundle in CDNJS, if you want to use a CDN, you can try UNPKG:

+ Core module bundle: https://unpkg.com/@angular/core/bundles/core.umd.js
+ Common module bundle: https://unpkg.com/@angular/common/bundles/common.umd.js
+ Compiler module bundle: https://unpkg.com/@angular/compiler/bundles/compiler.umd.js
+ Platform-browser module bundle: https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js
+ Platform-browser-dynamic module bundle: https://unpkg.com/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js
+ And so on

If you want to find how to use these bundle directly, please have a look at JavaScript version quick start: https://angular.io/resources/live-examples/quickstart/js/eplnkr.html

But do remember, they're only for demo, not for production. For production you'll need to setup local build tools.
