### ISSUE TITLE
APP_INITIALIZER with useFactory Compilation Error on first run 

### ISSUE THREAD

**Issue by Bretto** [angular/angular#14445]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using APP_INITIALIZER with useFactory I have an error on first compilation run, on the second run the error goes away.

**Expected behavior**
No errors on first compilation run.

**Minimal reproduction of the problem with instructions**
```
@NgModule({
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: fooFactory,
      deps: [MainConfigService],
      multi: true
    },
  ],
...

export function foo(mainConfigService) {
  return function() {
    return mainConfigService.loadConf();
  };
};

export function fooFactory(mainConfigService: MainConfigService) {
  return foo(mainConfigService);
}
```
**What is the motivation / use case for changing the behavior?**
We need a working demo/way to asynchronously bootstap the application. 

**Please tell us about your environment:**
The issue has been replicated on Windows 10 and Ubuntu 16.04.1 LTS

* **Angular version:** 2.0.X
angular-cli: 1.0.0-beta.28.3
node: 7.0.0
os: linux x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/compiler-cli: 2.4.7
@angular/cli: 1.0.0-beta.31

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome XX
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript X.X

* **Node (for AoT issues):** `node --version` =   
none

**Comment by DzmitryShylovich** [comment]
Pls add a repro

**Comment by Bretto** [comment]
https://plnkr.co/edit/tJKF8kcjqLeBPhdjsfG2?p=preview

You don't see the error in the console in the plunkr context.
Here is the error when in a dev environment:
```ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 12:42 in the original .ts file), resolving symbol compose in ...```

What should we do ? I have followed the AOT best practice, with no success
https://github.com/rangle/angular-2-aot-sandbox
 
Many have reported this error already, is this a CLI concern or Ng2 ? 
https://github.com/angular/angular/issues/11262
https://github.com/angular/angular-cli/issues/3707

**Comment by DzmitryShylovich** [comment]
I've just tested this:
```
@NgModule({
  imports: [ BrowserModule],
  declarations: [ App ],
  bootstrap: [ App ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: fooFactory,
      deps: [],
      multi: true
    }
    ]
})
export class AppModule {}

export function fooFactory() {
  return () => loadConfig({});
}

export function loadConfig(config: any) {
  console.log('do load', config);
}
```
and it works just fine.
2.0.10 ts
2.4.6 angular

**Comment by DzmitryShylovich** [comment]
try to change
```
export function fooFactory() {
  return foo();
}
```
to
```
export function fooFactory() {
  return () => foo();
}
```

**Comment by Bretto** [comment]
sorry but it's the same issue fro me...
"@angular": "2.4.7"
"typescript": "2.1.1"

**Comment by Toxicable** [comment]
@Bretto Angular does not currently support TS 2.1 on version 2.x

**Comment by Bretto** [comment]
I did try with 2.0.10 ts same problem...

**Comment by DzmitryShylovich** [comment]
@Bretto pls provide github repro with repro

**Comment by DzmitryShylovich** [comment]
@Bretto try this https://github.com/angular/angular/issues/14485#issuecomment-279849202

**Comment by Bretto** [comment]
I have got down to the root of my problem, 
The APP_INITIALIZER was actually a red herring the real issue was with the way I was declaring the ngrx Store
```
// was 
export const appStore =  compose(storeLogger(), combineReducers)({
    toasts: registerReducer(ToastReducer, toastInitState)
});

// needs to be
const reducers = {
  toasts: registerReducer(ToastReducer, toastInitState)
};

const developmentReducer = compose(storeLogger(), combineReducers)(reducers);

export function reducer(state: any, action: any) {
  return developmentReducer(state, action);
}
```
Plus after that I had to remove all the ```default``` of the modules declared with ```export default```. After that the problem was solved. Unfortunately I had to result to dichotomy to find what was the issue. The Error was completely misleading.  Thank you for the support though.

**Comment by cmckni3** [comment]
I ran into the same error when trying to use an anonymous arrow function in `4.1.3`.

```
@NgModule({
  imports: [ BrowserModule],
  declarations: [ App ],
  bootstrap: [ App ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: (configService: ConfigService) => () => configService.loadConfiguration(),
      deps: [ ConfigService ],
      multi: true
    }
    ]
})
```

**Comment by mlc-mlapis** [comment]
@cmckni3 ... you can't use an arrow function in that place. Use exported factory like:
```
providers: [
	...,
	AppConfig,
	{
		provide: APP_INITIALIZER,
		useFactory: appConfigServiceFactory,
		deps: [AppConfig],
		multi: true
	},
	...
]
```
where `appConfigServiceFactory` is something like:
```
export function appConfigServiceFactory(config: AppConfig) {
	return () => config.load().then((status) => {
		...
	});
}```

**Comment by cmckni3** [comment]
Yes, I had an exported function and switched to arrow function which broke it. Switched back to fix it.

**Comment by mrucelum** [comment]
For everyone still getting `Metadata collected contains an error that will be reported at runtime: Lambda not supported.` error message: for me it only worked when I changed

```
export function appConfigServiceFactory(config: AppConfig) {
	return () => config.load().then((status) => {
		...
	});
}
```

to something like

```
export function appConfigServiceFactory(config: AppConfig) {
        let extractedFn = () => {
              return () => config.load().then((status) => {
		...
              });
        };

	return extractedFn();
}
```

The first version worked in one of my 2 projects, but not in the other one, although they use the same versions (angular, ts, ...). Cost me quite some time to find this "workaround" (?), so hopefully this is helpful for others as well! 

Version info: 
angular 5.9.2
angular/cli 1.6.7
angular/compiler 5.2.9
angular/compiler-cli 5.2.9
typescript 2.7.2

**Comment by mlc-mlapis** [comment]
@mrucelum ... or use `// @dynamic` comment ... just put it exactly before the line with `@NgModule`.

```
// @dynamic
@NgModule({...})
```
