### ISSUE TITLE
ng-content projection without rendering the selector container

### ISSUE THREAD

**Issue by riyunoa** [angular/angular#14450]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```
It would be nice if we could use `<ng-content>` in the following way:

Defining:
```
<th>title</th>
<ng-content select="[stuff]"></ng-content>
```
Using:
```
<div stuff>
    <th>category</th>
</div>
```
The HTML that gets generated doesn't include the `<div stuff>`:
```
<th>title</th>
<th>category</th>
```

**Comment by vicb** [comment]
`div` is not permitted content in `tr`s.

next time your report an issue please attach a repro.

**Comment by riyunoa** [comment]
@vicb My issue is not about displaying the div - yes, divs are not allowed in trs. My feature request is so that after projection, the <div> element is not shown.

Currently, the HTML that is generated is 
```
<th>title</th>
<div stuff> <--- don't render this
    <th>category</th>
</div> <--- don't render this
```

What I need:
```
<th>title</th>
<th>category</th>
```

I hope this makes more sense.

**Comment by riyunoa** [comment]
Found out in Gitter that <ng-container> can be used for a placeholder element without adding it to the dom.
