### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by hajderr** [angular/angular#14454]
Hey guys

Not sure where I should report typos' but in the documentation it says the following

> so of which can be loaded later ("lazy loaded") if and when the user chooses to visit those features.

I believe it should say

> so**me** of which can be loaded later ("lazy loaded") if and when the user chooses to visit those features.

[AppModule Documentation](https://angular.io/docs/ts/latest/guide/appmodule.html)

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular.io/issues

**Comment by DzmitryShylovich** [comment]
@hajderr pls close this one. thx
