### ISSUE TITLE
2 Selects instance mixed up

### ISSUE THREAD

**Issue by jneveux** [angular/angular#14456]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have two tags select bound to the same list, after changing the selection a couple times I can see items from the first select being overridden by the second select selection. 
 This happens when I was testing bindings types on *select* with *ngValue*, *value* and a *change* event.

**Expected behavior**
The list instance should not change.

**Minimal reproduction of the problem with instructions**
This behavior seems ramdom, you'll need to change selection in both drop down a couple times before both select start containing only one duplicated object.
Here is a plunker on version 2.4.7: http://plnkr.co/edit/u4Owq7NeP5GMlUGrR9Oa?p=preview

**What is the motivation / use case for changing the behavior?**
Testing/prototyping

**Please tell us about your environment:**
Window 7 / Xeon

* **Angular version:** 2.4.7

* **Browser:** [Chrome 55 | IE 11 ]
 
* **Language:** [TypeScript 2.0.2 | ES6]

**Comment by DzmitryShylovich** [comment]
> I can see items from the first select being overridden by the second select selection.

because both selects are bound to the same variable `user`. When you change `user` (the 2nd select) it also affect the first select. To me it works as expected.

> The list instance should not change.

use different variables to store selected options

**Comment by jneveux** [comment]
Fair enough it works on 2 separates instance and I don't see this use case in real life happening, but still it got me worried.
