### ISSUE TITLE
While animating a leaving route, embedded child routes disappear immediately.

### ISSUE THREAD

**Issue by matze1234** [angular/angular#14457]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I've added an animation to my component, to make it slide out on route-change: 

```
@HostBinding('@slideHorizontal')
slideHorizontal: string = 'fromLeft';
```

Which works fine for the most part. 
The only problem is, there are nested child routes within this component. 
Everything within &lt;router-outlet&gt;&lt;/router-outlet&gt; disappears immediately from DOM and doesn't wait for the component's animation to finish.

**Expected behavior**

I'd expect, that nested child routes kind of freeze until the wrapping component's animation has finished.

I'm using 
@angular/router@3.4.7
@angular/core@2.4.7

**Comment by matsko** [comment]
The contents of the route should stay intact until the parent view is removed. If this is still an issue with Angular 5.x and above, please reopen the issue and I'll investigate.

**Comment by ChristianSchroedel** [comment]
We have the exact same issue with Angular 5.1.1.

The ':leave'-Animation of the top-level router-outlet is triggered correctly but every component in the nested router-outlet immediately disappears.

**Comment by fiste788** [comment]
same with version 7.0.2. please reopen it
