### ISSUE TITLE
New directive: ngLink

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#14453]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
There several issues with `routerLinkActive` which cannot be easily fixed with the current design:
1. https://github.com/angular/angular/issues/13865
2. https://github.com/angular/angular/issues/9426
3. https://github.com/angular/angular/issues/13533
4. https://github.com/angular/angular/issues/13075

I think it was a bad idea to introduce an additional directive to manage `active` state. We already have everything we need for this inside `routerLink`. So I think we should deprecate `routerLink` and `routerLinkActive` and introduce a brand new directive (working name `ngLink`), a merged version of these directive.
I will allow us to fix all listed issues and will also simplify templates
```
<a routerLink="/user/bob" routerLinkActive="active-link" [routerLinkActiveOptions]="{exact: true}">Bob</a>
```
vs
```
<a ngLink="/user/bob" [ngLinkOptions]="{exact: true, activeClass: 'active'}">Bob</a>
```

New directive will include features like:
1. https://github.com/angular/angular/issues/9426
2. https://github.com/angular/angular/issues/13205
3. https://github.com/angular/angular/issues/13980

@vicb what do you think?

**Comment by mattlewis92** [comment]
Having routerLinkActive as a separate directive has the advantage that you can apply it to a parent of the routerLink. E.g when using bootstraps CSS: https://github.com/mattlewis92/angular2-tv-tracker/blob/master/src/app/app.component.ts#L36

**Comment by DzmitryShylovich** [comment]
> a separate directive has the advantage

but also too many disadvantages :)

**Comment by kylecordes** [comment]
I have also found the ability to use routerLinkActive on a different element them the router link, very useful. I request that this feature not be lost within the upcoming enhancement.
