### ISSUE TITLE
One formControl, multiple inputs

### ISSUE THREAD

**Issue by cztomsik** [angular/angular#14451]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Reactive forms do not support binding multiple input components to one formControl instance

**Expected behavior**
The opposite

**Minimal reproduction of the problem with instructions**
Duplicate input with `formControlName` in [reactive forms demo](https://www.google.cz/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjkztrc0ozSAhWDzxQKHaoSAMIQFggbMAA&url=https%3A%2F%2Fangular.io%2Fresources%2Flive-examples%2Freactive-forms%2Fts%2Ffinal.eplnkr.html&usg=AFQjCNEvfokCZ2Ca3VW3h3LibNGuxIknwA)
Form inputs are not in sync after change

**What is the motivation / use case for changing the behavior?**
Combination of slider and input field

**Please tell us about your environment:**
OSX, VSCode

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by alexxxnf** [comment]
Is there any reliable workaround?

**Comment by mlc-mlapis** [comment]
@alexxxnf ... just using nesting ... via CVA or ControlContainer. It's not a workaround, it's a common way how to do it.

**Comment by alexxxnf** [comment]
@mlc-mlapis Thanks for the advice, I'll give it a try.

**Comment by dylhunn** [comment]
The Forms package makes a design assumption that controls correspond to at most one input. Changing that assumption would be a gigantic task.

Without a very compelling use case and lots of upvotes, this is unlikely to be prioritized.
