### ISSUE TITLE
New tab opened with target="_blank" is throwing HTTP Status 404 error

### ISSUE THREAD

**Issue by mohan1304** [angular/angular#14463]
**Current behavior**

opening new tab is throwing HTTP Status 404 error on page. Below given is the html template code
<a class="left-header-images-link" routerLink="/test" target="_blank">

Found below error in browser console
**"Failed to load resource: the server responded with a status of 404 (Not Found)"**

**Expected behavior**
It should not throw error and new tab should be loaded as per component template

**Minimal reproduction of the problem with instructions**

1) Create angular2 webpack project
2) Create a component as a.component.ts
3) Create a component as b.component.ts
4) Provide routing to Component b in component "a" template as below
`<a class="left-header-images-link" routerLink="/test" target="_blank">`
5) Click on the router link above and the new tab displayed is showing 404 error

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Operating System : Windows7
* **Angular version:** 2.0.X

 Angular 2.4.6 and webpack 2.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome:56
IE:11
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript:2.1.6
ES5
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a repro

**Comment by mohan1304** [comment]
I uploaded sample code to below repo

https://github.com/mohan1304/Angular2-Webpack-Open-New-Tab.git

Please download "angular2-webpack-starter-master" from above repo and build the project using "npm run build" and then deploy the "dist" folder to any application server.

Once deployed click on the Test link on page displayed

**Comment by mohan1304** [comment]
It works fine if we test as "npm start". Issue comes when we deploy to any server. In my case I am using tomcat server

**Comment by diicar** [comment]
@mohan1304 I think you have to redirect all requests into index.html.

**Comment by mohan1304** [comment]
I am not sure how to do that. Could you please provide me with an example. May be one are two lines of code is fine

**Comment by diicar** [comment]
Using the config file of your server (apache, nginx..) or .htaccess

**Comment by mohan1304** [comment]
its not clear to me. Also I am not expert in web technologies. I recently learnt angular2 and this is my first project on angular2. Please provide more details if you can

Thanks,
Mohan

**Comment by diicar** [comment]
@mohan1304 if you google with something like **nginx redirect all requests to index.html** , you should find what you need.
@DzmitryShylovich what do you think?

**Comment by DzmitryShylovich** [comment]
@mohan1304 http://stackoverflow.com/a/39482787
do you use spring?

**Comment by mohan1304** [comment]
Yes I use spring but only as services and I have separate angular2 client project

**Comment by mohan1304** [comment]
Thank you all for your inputs. 

I finally found a solution to my issue by setting { useHash: true }. I don't know why it doesn't work when useHash property of router module is not set to true. I believe it should work in both ways.

**Comment by DzmitryShylovich** [comment]
> I believe it should work in both ways.

`{ useHash: true }` requires special server configuration. 

> I finally found a solution to my issue

close the issue, pls. thx

**Comment by mohan1304** [comment]
But its not working if we don't set useHash to true. Don't you think this should be fixed?

**Comment by DzmitryShylovich** [comment]
fix what? your server configuration? :)

**Comment by mohan1304** [comment]
Not sure whether you properly understood the issue. 

when we have an anchor tag with target="_blank" it should open new tab as per HTML documentation and render the page.

As expected it is opening new tab with angular2 router functionality. But the problem with new tab is, it is not rendering the page and throws **"Failed to load resource: the server responded with a status of 404 (Not Found)"** error. 

It only works(render the page properly) when we set useHash property to true. Could you please confirm whether this is the desired behavior and is it the purpose of useHash property?

FYI... I didn't do any special server configuration. All I did was below change

Old code: 
RouterModule.forRoot(routes);    --> Not working

New Code:
RouterModule.forRoot(routes, { useHash: true });

**Comment by gkalpak** [comment]
@DzmitryShylovich meant that `{useHash: false}` (which is the default), requires special server configuration in order to work. Essentially, you need to configure you server to rewrite all (non-API) URLs to `index.html` (or whatever you main page is).

**Comment by mohan1304** [comment]
@gkalpak , Thank you.

From below comment from @DzmitryShylovich , I understood that need special server configuration if the property value is true.
**{ useHash: true } requires special server configuration.**

If this is the desired behavior then I am closing the issue. Its better if angular documentation is updated properly to avoid such confusions and it will save lot of time for developers

Thank you all for your inputs
