### ISSUE TITLE
Is CanLoad supposed to be called evertime the route is accessed?

### ISSUE THREAD

**Issue by victornoel** [angular/angular#14475]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Everytime a route with a `CanLoad` guard is accessed, the guard is executed, even after it was already loaded once.

**Expected behavior**

I would expect for the route to be loaded once the `CanLoad` guard returns `true` and then, once loaded, the guard not be called again. I thought it was the role of `CanActivate` to do this kind of checks everytime…
Note that I make the assumption that "loaded" means loaded in memory, as in lazy-loading or stuffs like this, maybe I'm wrong :)

**What is the motivation / use case for changing the behavior?**

Currently I am making a call to the backend in the `CanLoad` guard, and I want to avoid that :)

* **Angular version:**

2.4.7

* **Browser:**
 
Chromium (but I think all)

* **Language:**

Typescript (but I think all)

* **Node (for AoT issues):** `node --version` =   

7.5.0

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr with repro

**Comment by victornoel** [comment]
@DzmitryShylovich http://plnkr.co/edit/0xgU2Ts1gURFPbm6IfWf?p=preview

**Comment by victornoel** [comment]
the problem is that console.log is called everytime!

**Comment by DzmitryShylovich** [comment]
yeah, looks like a bug to me.

**Comment by wKoza** [comment]
I not sure : 
@vsavkin write in his book : "Finally, the router will call the canLoad guard during any navigation loading contacts, not just the first time, even though the bundle itself will be loaded only once"

**Comment by DzmitryShylovich** [comment]
ok, why? :)

**Comment by wKoza** [comment]
That, I don't know. For me, canLoad is use  for testing permissions. Permissions can change at any time.

**Comment by victornoel** [comment]
That, I don't know. For me, canLoad is use for testing permissions.
Permissions can change at any time.

Isn't that the role of CanActivate? CanLoad is for loading and CanActivate
for activating. And I think the official guide about routing says so too...
(On my phone, so I can't give a link right now).

**Comment by wKoza** [comment]
> CanLoad
Sometimes, for security reasons, we do not want the user to be able to even see the source code of the lazily loaded bundle if she does not have the right permissions. That’s what the canLoad guard is for. If a canLoad guard returns false, the router will not load the bundle.

> CanActivate
The canActivate guard is the default mechanism of adding permissions to the application.

**Comment by vicb** [comment]
@vsavkin once a route has been loaded it seems that the guard should not be called any more ?

**Comment by victornoel** [comment]
@wKoza I'm not sure where you got this citation, but that doesn't make any sense: you can't enforce security at the frontend side, anybody can simply get the bundle from the backend.
`CanLoad` is about performance (lazy-loading and the such), not about security. It can't be about security except if it is enforced at the server side.

Anyway, even if it was at the server side, after loaded once by the client, the bundle content is visible, so there is no need for revalidating authorization for loading, you can't make the bundle disappear from the client.

**Comment by wKoza** [comment]
This citation comes from the vsavkin's book. vsavkin is the architect  in charge of router. 

> after loaded once by the client, the bundle content is visible, so there is no need for revalidating authorization for loading, you can't make the bundle disappear from the client.

I agree with that. Probably, It misses a state in this case.

**Comment by victornoel** [comment]
@vicb any news on this issue? I think it should be good to fix it before releasing the 4.0.0 at least since it may be breaking (or should I say unbreaking) things…
By the way, from memory, it is actually a regression bug, since in the past, canload wasn't called everytime I think and this changed in one of the versions of 2.x… (not 100% sure about that though :)

**Comment by DzmitryShylovich** [comment]
@victornoel just add a boolean flag and set it to true after the first invocation

**Comment by victornoel** [comment]
@DzmitryShylovich I already do that, I was more worried about the underlying problem of interpreting the semantics of `CanLoad` for the benefit of the Angular community :)
