### ISSUE TITLE
core.umd.js isObservable always return false

### ISSUE THREAD

**Issue by hstarorg** [angular/angular#14473]
```
[ x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
`isObservable ` always return false

**Expected behavior**
Correct execution

```javascript
function isObservable(obj) {
        return !!(obj && obj[rxjs_symbol_observable.$$observable]);
    }
```

that `rxjs_symbol_observable.$$observable` is undefined, should update to `rxjs_symbol_observable.observable`

* **Angular version:** v4.0.0-beta.7
* **Language:** [ TypeScript 2.1.6 ]

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/LenguAe59TPMhKEzo0ID?p=preview returns true. It's an issue with your config.

**Comment by hstarorg** [comment]
In your demo, you used AMD loader. In my project, I only use global window.
`https://unpkg.com/@angular/core@4.0.0-beta.7/bundles/core.umd.js`, the `global.rxjs_symbol_observable` is undefined.

**Comment by hstarorg** [comment]
If I not edit the core.umd.js, I will Add some script 
```javascript
Rx.Symbol.$$observable = Rx.Symbol.observable;
window.rxjs_symbol_observable = Rx.Symbol;
```
after Rx loaded.

**Comment by inossidabile** [comment]
Just like @hstarorg said - there seem to be a missing reference in rollup for UMD build that throws confusing exception while attempting to use something like `|async`.

The given workaround with assigning `window.rxjs_symbol_observable` helps.

**Comment by DzmitryShylovich** [comment]
ping @robwormald
