### ISSUE TITLE
How to make form model update on blur in angular 2

### ISSUE THREAD

**Issue by ileler** [angular/angular#14472]
Is there an equivalent to this in angular 2?
```html
ng-model-options="{ updateOn: 'blur' }"
```

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ciesielskico** [comment]
+1, also looking for a way to perform form validation on blur

**Comment by Toxicable** [comment]
@ileler Please fill out the Issue template. What you have provided is not enough information.

**Comment by tbosch** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
