### ISSUE TITLE
innerHTML loses id attribute

### ISSUE THREAD

**Issue by PoiScript** [angular/angular#14474]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```html
<p>test</p>
```

**Expected behavior**

```html
<p id="test">test</p>
```

**Minimal reproduction of the problem with instructions**

```html
<div [innerHTML]="'<p id=\'test\'>test</p>'"></div>
```

**What is the motivation / use case for changing the behavior?**

I want to use [fragment](https://angular.io/docs/ts/latest/guide/router.html#!#fragment), but it can't work without **id attribute**

**Please tell us about your environment:** openSUSE, WebStorm

* **Angular version:** 2.4.6

* **Browser:** Chrome 58.0.3004.3

 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/S5VaczH7qZ0G53BIvWGR?p=preview

**Comment by PoiScript** [comment]
@DzmitryShylovich Oh, thank a lot! So `innerHtml` will lose id because of security?
