### ISSUE TITLE
trackBy (ngFor) function called without 'this' pointing to class

### ISSUE THREAD

**Issue by mmc41** [angular/angular#14478]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
if I configure ngFor's ngForTrackBy function to point to a class method in a component, it gets called without setting up "this" to point to the instance. Instead "this" is pointing to a DefaultIterableDiffer. This is a big problem for me, since I need to lookup state on the component in my tracking function.

**Expected behavior**

I expect "this" for the ngForTrackBy function to point to the component that contains the view with the ngIf, so that I can lookup state on the component. Otherwise, how can I make sure the GUI is changed if state changes on a component are not in the objects iterated by ngFor but in state that is referred to inside the ngFor statements ? 

**What is the motivation / use case for changing the behavior?**
To address complex tracking functions for updating the GUI depending on not only the components that are iterated through but also additional state.

**Please tell us about your environment:**
Mac OS X

* **Angular version:** 2.0.X
2.4.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X 
 Chrome and  Safari

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =   

v7.4.0

**Comment by DzmitryShylovich** [comment]
use arrow function or `bind`

**Comment by mmc41** [comment]
Thanks. That is a fast reply :-) 

I got an arrow function working by declaring a property for ngForTrackBy instead of a function but it looks a bit strange. How can I use a bind instead as you suggested as the  docs state that ngForTrackBy MUST be a function and I read issues that noted that the upcomming v4 will flag any attempt to set ngForTrackBy to anything else as an error?

**Comment by DzmitryShylovich** [comment]
> I got an arrow function working by declaring a property for ngForTrackBy instead of a function but it looks a bit strange. 

don't see anything strange

> How can I use a bind instead

http://plnkr.co/edit/Gz5yDEsvNunNotMd2r9p?p=preview

**Comment by mmc41** [comment]
Thanks - binded version looks better. Will close this issue.

Again thanks for being so fast and supportive!

**Comment by fr0** [comment]
The `bind` workaround works, but it seems like it shouldn't be necessary. Every other function, when invoked from a binding, automatically gets the correct `this` pointer. Why is `trackBy` special? It was surprising behavior once I realized what was happening, which is sometimes indicative of a design flaw.
