### ISSUE TITLE
Custom Pipe doesn't take locale on CI

### ISSUE THREAD

**Issue by rokerkony** [angular/angular#14477]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Extended currency pipe locale is overwritten. Btw. All tests for angular's currency pipe are only in en_US.

Pipe:
```
import {Pipe, PipeTransform} from '@angular/core';
import {CurrencyPipe} from '@angular/common';

@Pipe({name: 'eur'})
export class EurPipe implements PipeTransform {
    transform (value: number): string {
        const parentPipe = new CurrencyPipe('de');

        return parentPipe.transform(value, 'EUR', true, '1.0-2');
    }
}
```

Test:
```
import {EurPipe} from './eur.pipe';

// There is a special character between the symbol and the number.
const normalize (s: string): string => s.replace(/\u00A0| /g, ' ');

describe('EurPipe', () => {
    const pipe = new EurPipe();
    it('should transform to eur currency', () => {
        expect(normalize(pipe.transform(123))).toBe('123 €');
    });
});
```

Result of the test:
`Expected '€123' to be '123 €'`

Distribution on CI is `Debian GNU/Linux 8 (jessie)` and `LANG=de_DE.UTF-8`

It works locally on mac os sierra.

**Expected behavior**
Test should pass.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
```
Debian GNU/Linux 8 (jessie)
LANG=de_DE.UTF-8
in docker container
```

* **Angular version:** 2.4.6
with angular-cli@1.0.0-beta.28.3

* **Browser:**
test are running in PhantomJS
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):**
`node -v => v7.2.1`
`npm -v => 3.10.10`

**Comment by DzmitryShylovich** [comment]
Pls add a plunkr

**Comment by rokerkony** [comment]
well this is about testing ... is there possibility to run tests on plunkr?

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/Ph8CxhfUm0vHhTq3UBdo?p=preview

**Comment by rokerkony** [comment]
thank you, good to know 👍 

there is a plnkr, but as I wrote before, locally (in test and directly in application) it works - not on CI
http://plnkr.co/edit/ldWVQfKMvhYrDRkdurdY?p=preview

I investigated it more in deep an it seems like issue with standard built-in object `Intl` which is used in `@angular/common/src/pipes/intl.js`.

```
it('should convert to eur with built-in Intl', () => {
  // THIS DOESN'T WORK ON CI !!!
  const normalize = (s: string): string => s.replace(/\u00A0| /g, ' ');
  expect(normalize(
    new Intl.NumberFormat('de', {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 0,
      maximumFractionDigits: 2,
      style: 'currency',
      currency: 'EUR',
      currencyDisplay: 'symbol',
    }).format(123456)
  )).toContain('123.456 €');
});

>>> Expected '€123,456' to contain '123.456 €'.
```

**Comment by DzmitryShylovich** [comment]
> it seems like issue with standard built-in object Intl

if it's not reproducible in plunkr then we can't do much about it :(

**Comment by rokerkony** [comment]
ok,
so I fixed the issue on CI with adding 

```
import 'intl';
import 'intl/locale-data/jsonp/en';
import 'intl/locale-data/jsonp/de';
```

to `main.ts` and also to `polyfills.ts` for older browsers

would be nice to extend documentation about this

**Comment by DzmitryShylovich** [comment]
> would be nice to extend documentation about this

pls file a new issue on https://github.com/angular/angular.io/issues
