### ISSUE TITLE
Metadata collector errors on simple factory functions that return closures

### ISSUE THREAD

**Issue by alxhub** [angular/angular#14485]
The metadata collector errors when a factory function is a "simple" function which returns a closure.

Example:
```typescript
export function factoryFn(dep: Dep) {
  return () => {};
}

@NgModule({
  providers: [{provide: FOO, useFactory: factoryFn, deps: [Dep]}],
})
export class SomeModule {}
```

Error:
```
Metadata collected contains an error that will be reported at runtime: Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function.
```

Expected:
The factory function should be treated as an exported symbol and not inlined (?).

**Comment by DzmitryShylovich** [comment]
What ngc version do you use? I tested it yesterday it it worked fine.

**Comment by alxhub** [comment]
This is at `HEAD` in `angular/angular` currently.

I filed this bug at the request of @chuckjaz. He gave me a workaround:
```
export function factoryFn(dep: Dep) {
  const res = () => {};
  return res;
}
```

That works, while the code above doesn't.

**Comment by trotyl** [comment]
Should be fixed by Ivy.

**Comment by JoostK** [comment]
Closing as obsolete.
