### ISSUE TITLE
Add sugar for accessing values in input types

### ISSUE THREAD

**Issue by bradlygreen** [angular/angular#1448]
In this example:
```html
    <input #todo>
    <button (click)="addTodo(todo.domElement.value)">Add Todo</button>
```

Having to add `.domElement.value` to every `input` I reference is more typing than I'd like.  It's quite a lot more than in Angular 1.

I'm wondering if we could have sensible defaults for all `inputs` and maybe more element types?  That is, could I just pass in `todo` instead of `todo.domElement.value` and have Angular do the most likely thing I want?

**Comment by SekibOmazic** [comment]
Or at least `todo.value` (as we had it before alpha.19):
#1359

**Comment by tbosch** [comment]
Brad, this should be fixed now (ie not needing .domElement any more). See
https://github.com/angular/angular/commit/eac5c88893a5784384b6c7667945d7c21b94a48a
