### ISSUE TITLE
ElementRef.nativeElement has no type (any)

### ISSUE THREAD

**Issue by goleary** [angular/angular#14488]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
using vs code the type of `ElementRef.nativeElement` is `any`.  
**Expected behavior**
shouldn't the type be `Element` so we can get code completion and type checking?

**Minimal reproduction of the problem with instructions**
plnkr won't work because it doesn't do type checking (to my knowledge)

**What is the motivation / use case for changing the behavior?**
so we can get code completion and type checking

**Please tell us about your environment:**
windows 10 vs code

* **Angular version:** 2.4.1

* **Browser:** not a browser issue
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 2.1.5
* **Node (for AoT issues):** `node --version` =

**Comment by devoto13** [comment]
No, it shouldn't, because Angular can be used on other platforms, not only web. 

See #13139 for discussions and some workarounds. And I think this can be closed as duplicate.
