### ISSUE TITLE
Ignore Typescript Errors in ngc AOT Compilation

### ISSUE THREAD

**Issue by Marry7** [angular/angular#14492]
I have Angular 2 with Webpack and application working perfectly fine with JIT Compilation.
But when I tried to compile an Application usibg ngc AOT compilation becuase typescript errors it is not working. There are many typescript Errors in application some errors also because of theird party modules that i used in my application, those errors are almost imposible to fix. So Is there any way to ignore those typescript errors in AOT compilation
It is almost not possible to create plnkr with all errors.So if is there any way to disable all typescript errors while running ngc

* **Angular version:** 2.4.0
OS: Windows 10
TypeScript 2.0.10

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
