### ISSUE TITLE
this is a child router issue

### ISSUE THREAD

**Issue by xingguangsixian** [angular/angular#14490]
**Current behavior**
I have configed the app router module and the feature router module according to 
<href>https://angular.cn/docs/ts/latest/guide/router.html#!#routing-module</href>,
but my request can  not find the right component.
**Expected behavior**

 show the portal compontent content
**Minimal reproduction of the problem with instructions**
when the brower request the portal component,but redirect to the 404 

**What is the motivation / use case for changing the behavior?**
I want to spilt the feature component to the specific module.

**Please tell us about your environment:**

OS : win10 ,
IDE：webstorm
Compiler:angular-cli@1.0.0-beta.31
package manager: npm
server：node 6.9.2

* **Angular version:** 2.0.X
2.4.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 chrome 54.0.2840.87 m
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =   
6.9.2

**Comment by DzmitryShylovich** [comment]
pls add a plunkr

**Comment by xingguangsixian** [comment]
Sorry,I Can not Understand the "plunker"，I am a newer. I think that plunker is some code.  please give me some  instructions, thks!



qunxing_1989@163.com
 
From: Dzmitry Shylovich
Date: 2017-02-15 14:52
To: angular/angular
CC: xingguangsixian; Author
Subject: Re: [angular/angular] this is a child router issue (#14490)
pls add a plunkr

**Comment by DzmitryShylovich** [comment]
If the current behavior is a bug or you can illustrate your feature request better with an example, 
please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**Comment by xingguangsixian** [comment]
oh, I find  that the plunker load slowly in my country，so I post som main files . 
## app.modules.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import {AppRoutingModule } from './app-routing.module';
import {PortalsModule} from './portal/portals.module';
let modules = [
  BrowserModule,
  FormsModule,
  HttpModule,
  AppRoutingModule,
  PortalsModule
]

import { AppComponent } from './app.component';
import { LoginComponent } from './login/login.component';
import { PageNotFoundComponent } from './common/page-not-found.component';
let components = [
  AppComponent,
  LoginComponent,
  PageNotFoundComponent
];

import {AuthGuardService} from "./services/auth-guard.service"
import {AuthService} from "./services/auth.service"

let services = [
  AuthGuardService,
  AuthService,
];



@NgModule({
  declarations: [
    ...components
  ],
  imports: [
    ...modules
  ],
  providers: [
    ...services
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

## app-routing-module.ts
import {Routes, RouterModule} from "@angular/router";
import {LoginComponent} from "./login/login.component";
import {PageNotFoundComponent} from "./common/page-not-found.component";
import {NgModule} from "@angular/core";

// Components


const appRoutes: Routes = [
  // Root
  {
    path: 'login',
    component:LoginComponent
  },
  {
    path:'',
    redirectTo:"/portal",
    pathMatch:"full"
  },
  {
    path:'**',
    component:PageNotFoundComponent
  }
];


@NgModule({
  imports: [
    RouterModule.forRoot(appRoutes,{
      enableTracing:true
    })
  ],
  exports: [
    RouterModule
  ]
})
export class AppRoutingModule {}

## portals.module.ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PortalsRoutingModule } from './portals-routing.module';

import {PortalComponent} from './portal.component';
import {PortalDefaultComponent} from './portal-default.component';
@NgModule({
  imports: [
    CommonModule,
    PortalsRoutingModule
  
  ],
  declarations: [
    PortalComponent,
    PortalDefaultComponent
  ]
})
export class PortalsModule { }
## portals-routing.module.ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import {PortalComponent} from "./portal.component";
import {AuthGuardService} from "../services/auth-guard.service";
import {PortalDefaultComponent} from "./portal-default.component";

const routes: Routes = [
  {
    path:'portal',
    component:PortalComponent,
    canActivate: [AuthGuardService]
  },
  {
    path:'portalDefault',
    component:PortalDefaultComponent,
    canActivate: [AuthGuardService]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: []
})
export class PortalsRoutingModule { }


there are some main files in the above
