### ISSUE TITLE
Query param attached to route param when typing URL in browser (or refreshing page)

### ISSUE THREAD

**Issue by marclerman** [angular/angular#14496]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If I navigate to a route such as http://mysite/todos/abc?option=sort with the router.navigate method (router.navigate(["/todos/abc"], { queryParams: { option: "sort" } }), the route param and the query param are properly picked up with route.params["todoId"] and route.queryParams["option"].

However, when I refresh the page or enter the URL manually in the browser, route.params["todoId"] gives me "abc?option=sort" and route.queryParams["option"] gives me undefined.

**Expected behavior**
I would expect the route's param and query param to be properly differentiated when a URL is provided by the browser.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, .NET Core

* **Angular version:** 2.4.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls provide a plunkr

**Comment by marclerman** [comment]
I'd love to. But how do I write a Plunkr that demonstrates something that happens when you enter a URL in the browser?

**Comment by DzmitryShylovich** [comment]
1. open a plunkr in a separate window http://prntscr.com/e8xsy5
2. copy paste url int a new tab.
Then you will be able to change url manually

**Comment by marclerman** [comment]
Well, here is the Plunkr: https://plnkr.co/edit/VwLjrlPwqNDB86JO5ELc?p=preview.
Pasting the URL into another tab is fine, then navigating is fine.
But refreshing the Plunkr page gives a "Not found"... This prevents reproducing the problem in Plunkr (unless you know how to make refresh work in there).
You may want to download the code and give it a try.

**Comment by DzmitryShylovich** [comment]
`useHash: true`

**Comment by marclerman** [comment]
I am not reproducing the probem with that Plunker when using the hash strategy.
But in my original application, I am not using the hash strategy... I am wondering if this could be a problem linked to that particular mode of operation...

**Comment by vicb** [comment]
Please provide a repro as a git repo then.

**Comment by marclerman** [comment]
The problem was in my code: you cannot call router.navigateByUrl("/todos/abc?option=sort"), you have to explicitly separate the queryParams from the path.
Not a bug, can be closed.
