### ISSUE TITLE
Documentation correction - guide/forms.html uses template variable before it's defined

### ISSUE THREAD

**Issue by robstarbuck** [angular/angular#14500]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Following the guide on angular forms:
https://angular.io/docs/ts/latest/guide/forms.html

A reference to the template variable "heroForm" is made before it's inclusion.

    <button type="button" class="btn btn-default" (click)="newHero(); heroForm.reset()">New Hero</button>

Above this, in the section headed "Create an initial HTML form template" only.

    <form>

is shown

**Expected behavior**

In the section headed "Create an initial HTML form template", I would expect to see the template variable.

    <form #heroForm="ngForm">

**Minimal reproduction of the problem with instructions**

See https://angular.io/docs/ts/latest/guide/forms.html

**What is the motivation / use case for changing the behavior?**

Correction of documentation

**Please tell us about your environment:**

N/A

* **Angular version:** 2.0.X

N/A

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

N/A
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

N/A

* **Node (for AoT issues):** `node --version` =   

N/A

**Comment by lazarljubenovic** [comment]
Doc issues go to [angular.io](https://github.com/angular/angular.io)
