### ISSUE TITLE
Redirect routing at the top freezes browser without error message

### ISSUE THREAD

**Issue by lebsral** [angular/angular#14504]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When a redirect is before the thing redirects to it crashes the browser without an error message
**Expected behavior**

It is ok if it doesn't work, but it should produce an error.
**Minimal reproduction of the problem with instructions**
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule  } from '@angular/router';

import { PageNotFoundComponent } from './not-found.component';
import { LoginComponent } from './login/login.component';
import { UserProfileComponent } from './user-profile/user-profile.component';


const appRoutes: Routes = [
  {
    path: '',
    redirectTo: '/products', pathMatch: 'full'
  },
  {
    path: 'products',
    loadChildren: 'app/products/products.module#ProductsModule'
  },
  {
    path: 'admin',
    loadChildren: 'app/admin/admin.module#AdminModule'
  },
  {
    path: 'login',
    component: LoginComponent
  },
  {
    path: 'profile',
    component: UserProfileComponent
  },
  { path: '404', component: PageNotFoundComponent },
  { path: '**', component: PageNotFoundComponent }
];


@NgModule({
  imports: [RouterModule.forRoot(appRoutes)],
  exports: [RouterModule],
  providers: []
})
export class AppRoutingModule { }
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Mac OSX 10.12.3
Angular cli running localhost:4200
Atom editor
* **Angular version:** 2.0.X

angular-cli: 1.0.0-beta.25.5
node: 6.9.5
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/compiler-cli: 2.4.7
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome Version 56.0.2924.87 (64-bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS
* **Node (for AoT issues):** `node --version` =   
6.9.5

Moving the  redirectTo: '/products' towards the bottom fixes this problem.  Which is fine, but doing it wrong should not crash the browser.

**Comment by DzmitryShylovich** [comment]
Pls provide a plunkr

**Comment by lebsral** [comment]
Ok, I'll put together the smallest possible project that duplicates and then post that.

**Comment by lebsral** [comment]
First off, I no longer think the title of this issue is an accurate description of the problem.  But the problem is still there.

I created a version of a project that has the problem.
https://github.com/KillionCorp/c3atalog

To recreate the problem
download the repo
$yarn
$ng serve
in Chrome localhost:4200

The main part of the screen should be mostly blank (and you see login form sign-in.ts)

Now go to
http://localhost:4200/products/list
It should also be mostly blank because you can't see the products without logging in. Good.

Now go to 
http://localhost:4200/login
and click the Sign In Anonymously
(nothing seems to happen but that is ok for this demo). Good.

Go back to 
http://localhost:4200/products/list
Now you can see products (pics of airplanes etc) because you are logged in.  Good.

Now go back to the first link
http:/localhost:4200
Bad.
Chrome will now freeze up.  (sometimes firefox does too).  All tabs.  You have to force quit.  Then once you log back into chrome it will refreeze if you go back to ANY localhost:4200 link above.

To stop that go to settings -> advanced -> clear browsing data -> cookies and other site data -> the past hour -> clear.

I don't mind having a bug in my project.  I can figure that out.  (In fact I think it has something to do with src/app/auth/index.ts routing)

What I do mind, is being able to do anything with Angular that breaks Chrome so badly that even after a force quit /restart the problem persists. 

TIA

**Comment by DzmitryShylovich** [comment]
@lebsral thx but your demo app is too big. Nobody has time to debug such apps.

**Comment by esbeto** [comment]
Might be related:

https://github.com/angular/angular/issues/14262

**Comment by lebsral** [comment]
If nobody else is having this problem you can go ahead and close this

**Comment by DzmitryShylovich** [comment]
@lebsral you can close it yourself :)

**Comment by phMalatji** [comment]
I'm also having the same problem right now. Was this issue resolved?

**Comment by darkmeton** [comment]
Yes, same problem here.

**Comment by Sjerd** [comment]
This is still an issue. an angular redirect loop crashes my whole pc with chrome. imo the router should just quit if it detects/should detect a loop.

**Comment by JNaeemGitonga** [comment]
Seeing this in 2019, was there ever a resolution or did we ever find the culprit?
