### ISSUE TITLE
ngc doesn't find not typed third library

### ISSUE THREAD

**Issue by Pilukina** [angular/angular#14501]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When launch: 
`ngc -p tsconfig-aot.json && rollup -c rollup-config.js`

The terminal shows the follow error:
`Error Cannot find type definition file for 'xml2js-es6-promise'`

**Expected behavior**
I've expected the project compiles as It is compiled and served when using tsc compiler.

**Minimal reproduction of the problem with instructions**
Project created using **Angular CLI version: 1.0.0-beta.29.**
**I'm using a third party library which is not typed:**  'xml2js-es6-promise'.
When running: npm install -D @types/xml2js-es6-promise
the result is: '@types/xml2js-es6-promise' is not in the npm registry

Following the Angular CLI instructions, I declare it on **typings.d.ts** (declare module 'xml2js-es6-promise') which is on same folder as tsconfig-aot.json. 

The lib is also declared on tsconfig-aot.json:
`{
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": true,
    "stripInternal": true,
    "experimentalDecorators": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "module": "es2015",
    "moduleResolution": "node",
    "paths": {
      "@angular/core": ["node_modules/@angular/core"],
      "rxjs/*": ["node_modules/rxjs/*"]
    },
    "rootDir": ".",
    "outDir": "dist",
    "sourceMap": true,
    "inlineSources": true,
    "target": "es5",
    "skipLibCheck": true,
    "lib": [
      "es2015", 
      "dom"
    ],
    "types": ["xml2js-es6-promise"],  
    "typeRoots": ["node_modules/@types"]
  },
  "files": [
    "index.ts"
  ],
  "angularCompilerOptions": {
    "strictMetadataEmit": true
  }
}`

**What is the motivation / use case for changing the behavior?**

I need using the library in order to transform some xml got from a soap request in jso objects.

**Please tell us about your environment:**

Windows 7, npm
* **Angular version:** 2.0.X

@angular/cli: 1.0.0-beta.29
node: 6.9.2
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.29
@angular/compiler-cli: 2.4.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript@2.0.10
* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Pilukina** [comment]
It is created:
http://stackoverflow.com/questions/42249760/ngc-not-compiling-project-using-not-typed-third-party-libraries
Many thanks for your answer!
