### ISSUE TITLE
Upgrade to Aangular V4 fails

### ISSUE THREAD

**Issue by mmrath** [angular/angular#14513]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

AOT compilation success with 2.4.7 but fails with 4.0.0-beta.7

Error on console:
```
ERROR in Can't resolve all parameters for HttpInterceptorService in /Users/murali/Projects/test-ng/src/app/http/interceptors/http-interceptor.service.ts: ([object Object], [object Object], [object Object], ?).

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/murali/Projects/test-ng/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

**Expected behavior**

AOT compilation should pass with 4.0.0-beta.7

**Minimal reproduction of the problem with instructions**

A very minimal repo is located at https://github.com/mmrath/ng4-upgrade-test 
`master` branch has code for 4.0.0-beta.7 which is failing to build.
`ng2` branch has code for 2.4.7 which builds successfully. The only change here is version numbers for angular packages

To build run `npm install` and then `ng build --prod` assuming cli is installed globally

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

@angular/cli: beta 31
node 7.2.1
npm 3.10.10

* **Angular version:** 4.0.0-beta.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** Typescript: 2.1.6
* **Node (for AoT issues):** `node --version` =   `v7.2.1`

**Comment by DzmitryShylovich** [comment]
err msg?

**Comment by mmrath** [comment]
Updated issue description. Error is

```
ERROR in Can't resolve all parameters for HttpInterceptorService in /Users/murali/Projects/test-ng/src/app/http/interceptors/http-interceptor.service.ts: ([object Object], [object Object], [object Object], ?).

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/murali/Projects/test-ng/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

**Comment by vicb** [comment]
Typescript version ?

**Comment by mmrath** [comment]
2.1.6

**Comment by mmrath** [comment]
@vicb is there something trivial I am missing here. I have tried to look up breaking charges, but the changelog does not mention this. I am using typescript 2.1 for both 2.4.7 and 4.0 beta, so it may not be typescript issue.

**Comment by mmrath** [comment]
This is still an issue with rc.1. Is there a workaround or fix?

**Comment by Tragetaschen** [comment]
I'm getting the same error for a component of mine:
```
import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs/Rx';

@Injectable()
export class AlarmService {
    public P1: BehaviorSubject<boolean>;
    public P2: BehaviorSubject<boolean>;

    constructor(p1: boolean, p2: boolean) {
        this.P1 = new BehaviorSubject<boolean>(p1);
        this.P2 = new BehaviorSubject<boolean>(p2);
    }
}

> .\node_modules\.bin\ngc -p .\Client\
Can't resolve all parameters for AlarmService in C:/Users/kairu/Source/Repos/[...]/alarm.service.ts: (?, ?).
```

 It looks like ngc doesn't like built-in types, `boolean` in my case and an array in your case.

**Comment by DzmitryShylovich** [comment]
@Tragetaschen did you provide `p1` and `p2`?

**Comment by Tragetaschen** [comment]
What do you mean? The way I use this service is through
```ts
export function defaultAlarmService() {
    return new AlarmService(false, false);
}
// ...
    { provide: AlarmService, useFactory: defaultAlarmService },

```

**Comment by DzmitryShylovich** [comment]
@Tragetaschen ensure that you don't have somewhere `providers: [AlarmService]`

**Comment by Tragetaschen** [comment]
Done. I have `{ provide: AlarmService, useFactory: defaultAlarmService },` and `{ provide: AlarmService, useClass: InstrumentAlarmService },`. `InstrumentAlarmService` itself only has di-able dependencies

**Comment by DzmitryShylovich** [comment]
paste InstrumentAlarmService

**Comment by Tragetaschen** [comment]
```ts
import { Injectable } from '@angular/core';
import { GuiConnectionService } from './gui-connection.service';
import { AlarmService } from './alarm.service';

@Injectable()
export class InstrumentAlarmService extends AlarmService {
    constructor(guiConnectionService: GuiConnectionService) {
        super(false, false);

        // simplified:
        guiConnectionService.Update
            .subscribe(x => {
                this.P1.next(x.P1);
                this.P2.next(x.P2);
            });
    }
}

```

**Comment by mmrath** [comment]
@DzmitryShylovich Any chance you can help me with this repo https://github.com/mmrath/ng4-upgrade-test 

This fails with beta 7 as well  as rc1

**Comment by DzmitryShylovich** [comment]
@Tragetaschen the same code does work in 2.x with aot, right?

**Comment by Tragetaschen** [comment]
Yes

**Comment by Tragetaschen** [comment]
I've reproduced the issue based on an angular-cli project: https://github.com/Tragetaschen/angular-issue-n14513

The second commit adds two services as above. `ngc -p src/tsconfig.app.json` from angular ^2.4.0 works.

The third commit upgrades to angular 4.0.0-rc.1 and fails with the above error: `Can't resolve all parameters for AlarmService in C:/Users/kairu/Source/Repos/angular-issue-n14513/src/app/alarm.service.ts: (?).`

**Comment by DzmitryShylovich** [comment]
@Tragetaschen interesting. and error disappears when you remove `Injectable` from `AlarmService`. looks like a valid bug.

**Comment by Tragetaschen** [comment]
`flag: should remain open!`?

**Comment by mmrath** [comment]
The original example repo that I provided contains code from covalent. I see there is a merged PR which resolves the issue. I'll give it a try today 

Ref: https://github.com/Teradata/covalent/pull/377

**Comment by DzmitryShylovich** [comment]
@mmrath did it help?

**Comment by alxhub** [comment]
This appears to be a compiler/metadata issue, not http. Reassigning.

**Comment by mmrath** [comment]
This is resoved.

**Comment by mmrath** [comment]
I just had to remove Injectable annotation

**Comment by Kyderman** [comment]
Worth noting to anybody who sees this, if you have a normal class you use for just constructing objects, leave out the @Injectable annotation, it seems that from Angular 5 onwards it will cause an error in aot compiling.
