### ISSUE TITLE
Integrating More Convention over Configuration in Angular 2

### ISSUE THREAD

**Issue by DanWahlin** [angular/angular#1451]
Is any consideration being given to integrating more default conventions into Angular 2? This may be something that is already in there and I just haven't seen it or something already planned, but I wanted to  explore it. Here's what I mean by "default conventions". 

A typical component looks like this:

```javascript
import {
  bootstrap,
  Component,
  View
} from 'angular2/angular2'

@Component({
  selector: 'MyComponent'
})
@View({
  templateUrl: 'my-component.html'
})
class MyComponent {
  constructor() {
    this.name = 'My Component';
  }
}
```

By adding some smart default conventions it could look like this:

```javascript
import {
  bootstrap,
  Component,
  View
} from 'angular2/angular2'

@Component()
class MyComponent {
  constructor() {
    this.name = 'My Component';
  }
}
```

Here's what default conventions would buy us:

1. The component selector defaults to **my-component** (much like directives do today in Angular 1.x).
2. The view defaults to a URL of **my-component.html** (with a default view location that would have to be determined). No need to add @View in this situation but in cases where the templateUrl is different or it's an inline template then @View can be added.

I realize this doesn't cover component injectables, view directives (still not a fan of having to define those here), and other properties that may be needed, but there may be a way to add some convention there as well.

I'm sure there are several other cases where conventions could potentially be used. By adding some smart default conventions some of the boilerplate code could be eliminated while still allowing people to override the defaults by supplying the proper annotations as needed. That would be great for people moving to the framework (code would appear much less intimidating at first glance since many aren't used to annotations) and also great for devs since less code would have to be written in some cases.

There might even be a simplified convention for importing the default modules used in this case. For example, a "standard" component that needs bootstrap, Component, and View might just be wrapped up like this:

```javascript
import {ComponentDefault} from 'angular2/angular2'

@Component()
class MyComponent {
  constructor() {
    this.name = 'My Component';
  }
}
```

If some of the convention suggestions are already in there (or being planned) let me know. For me personally, it just feels like way too much boilerplate code to something relatively simple. Some default conventions would clean that up.

**Comment by pkozlowski-opensource** [comment]
@DanWahlin you must be reading my mind since I was about to propose a set of very similar "boilerplate busters". More specifically:
* I was already talking to @rkirov and @mhevery about inferring selector from the class name (if none explicitly provided)
* I'm also not sold on listing all the directives in the @View annotation, here is the issue I've opened for this: #1293
* @yjbanov seem to have even more radical proposal for the @View annotation, see #1454

But yeh, I fully agree that we need more sensible defaults to cut down amount of code for typical / common use-cases.

**Comment by DanWahlin** [comment]
Thanks for the info on the related issues @pkozlowski-opensource. Sounds like we're all on the same track here. Hopefully some of this can be cleaned up to reduce the boilerplate code more.

**Comment by SekibOmazic** [comment]
@pkozlowski-opensource One of the "issues" I almost always stumble upon is
```Javascript
@Component({
  injectables: [SomeService]
})
class MyComponent {
  constructor(someService:SomeService) {}
}
``` 
So I have to declare `SomeService` both in `injectables` and in the `constructor` and this is something I foreget pretty often. It should be possible to write only:
```Javascript
@Component()
class MyComponent {
  constructor(someService:SomeService) {}
}
```
or:
```Javascript
@Component()
class MyComponent {
  constructor(@Inject(SomeServiceImpl) someService:SomeService) {}
}
```
if you want to express `bind(SomeService).toClass(SomeSerice)`

What do you think?

**Comment by DanWahlin** [comment]
Completely agree with you. I don't like having the injectables way above the constructor (which will happen if you like to define your fields at the top of the class - which I do). I think it should be immediately above the constructor or in the constructor params like you show. I'd like something like this since it keeps the constructor params clean but also makes it obvious what is being injected into the constructor:

```javascript
@Component()
class MyComponent {
  @Inject(SomeServiceImpl) 
  constructor(someService:SomeServiceImpl) {}
}
```

**Comment by SekibOmazic** [comment]
Yes, that is even better. And maybe easier to implement if the annotations are to be replaced by the decorators?

**Comment by mhevery** [comment]
I am all for streamlining things. Just want to point out that getting the mental (explicit) model right and creating shortcuts are two separate concerns. We can always do the convention later, but we need to get the configuration right first.

**Comment by pkozlowski-opensource** [comment]
@mhevery right, I believe that we've got a mix of 2 here (that is, sugar for the already established / non-controversial config and conceptual issues as well):
* sugar:
  * inferring selector from the class name 
  * inferring template url from the class name 
* conceptual issues
  * listing directives, pipes etc. in @View
  * listing injectables (although I think that here there is mostly misunderstanding)

I agree that we should get the concepts right before adding sugar.

**Comment by DanWahlin** [comment]
@mhevery Completely agree with you - have to get that right first. But, it's always good to keep in mind some potential convention wins while working on the configuration part which is why we're listing a few things to consider. :-)

**Comment by benpetersen** [comment]
Also, for route annotations, there seems to be a lot of ways like ui-router .state, john papa's suggestion .when; would it be possible to add smart defaults similar to a boiler plate, so annotations are a little simpler?

**Comment by ewinslow** [comment]
I think having `@Inject(ables)` annotation near the constructor would be great. Moves the information closer to where it is relevant.

**Comment by manfredsteyer** [comment]
This is exactly what I'm thinking about since months. I'm very glad to see this planned for the Sugar-Milestone.

**Comment by mhevery** [comment]
Closing, as this discussion came to an end. We will have a separate effort to streamline verbosity.
