### ISSUE TITLE
createUrlTree ignoring <base href=.. />?

### ISSUE THREAD

**Issue by wannadream** [angular/angular#14522]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am using Router.createUrlTree() to generate URL for pop up window. However, the URL generated does not include <base href=".." />.

For example, my app file structure is like this:
--/
--/cloud/
--/other/

All code for Angular application is under cloud folder so I put <base href="/cloud" /> in index.html.
In browser, I will use http:/hostname/cloud to access my application.
However, Router.createUrlTree() generates URL without base href setting, which is like http:/hostname/home/detail

**Expected behavior**

I am expecting the generated URL should be http://hostname/cloud/home/detail

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, Visual Studio 2015/2017RC, NPM, IIS

* **Angular version:** 2.0.0.0

* **Browser:** Chrome 56.0.2924.87

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls provide a plunkr

**Comment by wannadream** [comment]
Looks like Plunkr does not support sub folder structure. I will send you a public link of our application tomorrow.
![11](https://cloud.githubusercontent.com/assets/6989212/23011883/2efe7f3a-f3d8-11e6-8725-698231c540b9.gif)

**Comment by DzmitryShylovich** [comment]
Anyway I would say it's by design. `createUrlTree` has nothing to do with base href or folder structure.

**Comment by wannadream** [comment]
Okay, here is the link: https://primecloud.hdlgov.com/cloud, see console output for debugging information.
If that is the case, there is no way to generate absolute URL relatively?

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
