### ISSUE TITLE
AOT/Rollup with modules which have no default export

### ISSUE THREAD

**Issue by lexon0011** [angular/angular#14526]
I try to ajust my angular app to be ready for AOT compilation and Tree Shaking (rollup). But I have problems by using modules which have no default exports (immutable.js, moment.js, ...). According to typscript (look [here](https://github.com/Microsoft/TypeScript/issues/14083)) it is only possible to use such modules with the following statement: `import x = require('x') `or `import * as x from 'x'`
But both statements cause problems during the rollup. In some cases I get an error during the rollup: `Cannot call a namespace ('x')` and in some cases I get an runtime error that: `x is undefined`

Here you find my rollup-config.js and tsconfig-aot.json
[tsconfig-aot_rollup-config.zip](https://github.com/angular/angular/files/779237/tsconfig-aot_rollup-config.zip)

I need a way to use packages like immutable.js, moment.js during the AOT compilation and rollup. Is there a way to do this?

Thanks!

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by lexon0011** [comment]
Thanks! For other people having the same problem, I ask the question [here ](http://stackoverflow.com/questions/42267240/angular-aot-rollup-with-modules-which-have-no-default-export-like-immutable-js)

**Comment by Blazzze** [comment]
Hello friend, i found that in the **rollup-config.js** in the ts cookbook they did put specifically rxjs in the commonJs include..
if you change from including only rxjs it will deal with 3rd party modules too:

example: i'm using angular2-materialize so:

```
    commonjs({
      include: [
        'node_modules/rxjs/**',
        'node_modules/angular2-materialize/**'
      ],
```


or simply include all ( i dont think any difference to the ending build.js file, feel free to check :)  )

```
 commonjs({
   include: 'node_modules/**'
 })
```

**Comment by kylecordes** [comment]
The problems around this are frustrating, but I think they are issues how TypeScript and various module formats and loaders work together (or don't...), not actually related to Angular.
