### ISSUE TITLE
Cannot bundle typings

### ISSUE THREAD

**Issue by Delagen** [angular/angular#14529]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`typings bundle` does not work with `@angular/core` 4.0.0-beta.7

**Expected behavior**
Works

**Minimal reproduction of the problem with instructions**
`typings bundle --out bundle.d.ts`

**Please tell us about your environment:**
Windows 10

* **Angular version:** 4.0.0-beta.7

* **Language:** TypeScript 2.1.6

* **Node (for AoT issues):** `node --version` =   7.5.0

Original issue and fix: https://github.com/typings/core/issues/170

**Comment by DzmitryShylovich** [comment]
Can you provide a small demo app? Don't see how it's related to angular tbh :)

**Comment by Delagen** [comment]
```
npm i @angular/core@4.0.0-beta.7
npm i typings -g
cd ./node_modules/@angular/core
typings bundle --out bundle.d.ts
```
This is cause of import using folder barrel. I prefer not to use resolve module using index file barrel. Due many modules does not use index in their resolution system.
So may resolve instance from direct file or specify full path to barrel. It's for now single place.

```
import { DebugContext } from './view';
```

to replace with 
```
import { DebugContext } from './view/index';
```
or 
```
import { DebugContext } from './view/types';
```

**Comment by Delagen** [comment]
https://github.com/typings/core/pull/171

**Comment by Delagen** [comment]
I think it's not your issue.
