### ISSUE TITLE
Conflicting docs for @Component({ providers: [...] }) - sandbox or singleton?

### ISSUE THREAD

**Issue by alexsapps** [angular/angular#14525]
Conflicting docs about whether @Component({ providers: [...] }) results in a singleton or per-component instance.

Here it says it's not a singleton:

"Each HeroBioComponent gets its own HeroCacheService instance by listing the HeroCacheService in its metadata providers array."
https://angular.io/docs/ts/latest/cookbook/dependency-injection.html#!#multiple-service-instances

Here it says it's a singleton:

"By providing VillainsService in the VillainsListComponent metadata — and nowhere else —, the service becomes available only in the VillainsListComponent and its sub-component tree. It's still a singleton, but it's a singleton that exist solely in the villain "
https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html

**Comment by vicb** [comment]
It means that when it's listed in the provider of A each A has a new instance while the children of A share the same instance as their A parent.

**Comment by alexsapps** [comment]
Then this statement is wrong:
"It's still a singleton, but it's a singleton that exist solely in the villain domain"

Singleton means only one, especially since it says "still" a singleton, like the same kind of singleton as before and the only thing singleton can mean: only one.  :)

"In the villain domain" does not mean "in this villain instance". I believe it's talking about visibility here, not scope.

**Comment by DzmitryShylovich** [comment]
@alexsapps https://github.com/angular/angular.io/issues docs repo

**Comment by alexsapps** [comment]
Thanks. Submitted https://github.com/angular/angular.io/issues/3262
