### ISSUE TITLE
A ? sign comes at the end of the route when ever i try to navigate?

### ISSUE THREAD

**Issue by nitishkumarnitc** [angular/angular#14524]

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
