### ISSUE TITLE
Getting issue in upgradeAdapter at the time of downgradeProvider

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#14534]
Hi ,

I have application in angular 1.x and now i have migrated some of services in angular 2 and now those services i still want to use in ng1 code using upgradeAdapter.downgradeNg1Provier method.
But i am getting the following issue in this specific case for each service : 
(index):405 Error: (SystemJS) Cannot read property 'injector' of null(…)

**Comment by ScottyVG** [comment]
This issue is closed currently, reference #11165? Can you link a Plunkr? https://github.com/angular/angular/issues/11165

**Comment by vasuneet** [comment]
The mentioned reference issue is related to test case only.

**Comment by tbosch** [comment]
Hello,
we really need a reproduction for this, otherwise we can't work on it...

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
