### ISSUE TITLE
Change detection problems on safari

### ISSUE THREAD

**Issue by nekkon** [angular/angular#14533]
On Safari Version 9.1.2 If the template (.html) contains a variable in {{ example }} that changes during runtime, the template does not re-render to update the change. Tested the same code and works properly on Chrome and Firefox. Unfortunately it does work properly on Safari. Not sure what causes this. Need some help on this one. Thanks in advance.

**Comment by DzmitryShylovich** [comment]
sounds like zone.js on Safari issue.
Pls add a plunkr

**Comment by Toxicable** [comment]
@nekkon Can you please fill out the Issue template, it's there for a reason. Most importantly can you create a minimal reproduction in a plunkr.

**Comment by nekkon** [comment]
I am trying to understand what is causing this in order to able to reproduce it. I will add a plunkr link whenever I manage to do that.

**Comment by nekkon** [comment]
Can not reproduce it on plunkr https://plnkr.co/edit/oEfZOW?p=preview. Something else causes this to happen in my app. I will try to find what it is. Till then I close this issue.
