### ISSUE TITLE
A feature request for auto-disposable observables

### ISSUE THREAD

**Issue by DAB0mB** [angular/angular#14549]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When creating a new Observable inside a `@Component` it won't be automatically disposed once the component is being destroyed (unless it is hooked to an `async` pipe). 

**Expected behavior**
I would expect the Observable to be automatically destroyed unless specified not to.

**Minimal reproduction of the problem with instructions**
Here's a brief implementation of a lazy load mechanism in a chat application:

```ts
  lazyLoadMessages() {
    this.autoScroller = this.autoScroll();
    this.subscribeMessages();

    // Get total messages count in database so we can have an indication of when to
    // stop the auto-subscriber
    this.countMessages().then((messagesCount) => {
      Observable
        // Chain every scroll event
        .fromEvent(this.scroller, 'scroll')
        // Remove the scroll listener once all messages have been fetched
        .takeUntil(this.autoRemoveScrollListener(messagesCount))
        // Filter event handling unless we're at the top of the page
        .filter(() => !this.scroller.scrollTop)
        // Prohibit parallel subscriptions
        .filter(() => !this.loadingMessages)
        // Invoke the messages subscription once all the requirements have been met
        .forEach(() => this.subscribeMessages());
    });
  }
```

The code snippet above loads more messages whenever scrolling to the top of the page in the `messages` page. If I don't stop this Observable manually in the `onDestroy` callback, there might be a potential memory leak and unnecessary requests made in the background. The full component can be found [here](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/blob/master/src/pages/messages/messages.ts).

**What is the motivation / use case for changing the behavior?**
Lots of developers might forget to handle their observations which may lead to a total disaster with unnecessary requests and processes running in the background. Observables should be disposed by default unless specified else wise. It's hard for me to think of a scenario where the developer wants the Observable to keep running in the background despite the fact that the component has been already disposed long ago, it will only cause slow downs and issues.

It would be a good idea to create a dedicated service called `NgObservable` where it can be injected to the component and be used to create new Observable instances which are bound to the component. After a brief thinking of how the service should look like led me to the following result, which might inspire you and give you an idea what I'm actually talking about:

```ts
import { Observable } from "rxjs";

/* Declarations */

// Save duplicate importations
export interface NgObservable<T> extends Observable<T> {
  _keep: boolean;
};

// Will define a dynamic interface based on the current version of "rxjs" installed
export interface NgObservableService extends Rx.ObservableStatic {
  readonly keep: NgObservableService;
};

/* Implementations */

// Creates new Observable instances through its prototypical methods.
// The constructor only holds options which should be applied to these instances
export class NgObservableService {
  private _keep: boolean;

  constructor({ keep }: { keep?: boolean } = {}) {
    this._keep = !!keep;
  }
}

// Solves "Index signature is missing in type" error:
// https://github.com/Microsoft/TypeScript/issues/1887
const IterableObserver = Observable as { [key: string]: any };

// Delegating all kind of Observable factory functions like 'of', 'from' etc.
// The advantages of automatically generated prototype are that we're always gonna
// be correlated with the currently installed Observable API
Object.keys(Observable).forEach((key) => {
  const value = IterableObserver[key];

  // Delegate function
  if (typeof value == "function") {
    const methodHandler = function () {
      const observable = value.apply(Observable, arguments);

      if (observable instanceof Observable) {
        const ngObservable = observable as NgObservable<any>;
        ngObservable._keep = this._keep;
      }

      return observable;
    };

    Object.defineProperty(NgObservableService.prototype, key, {
      configurable: true,
      enumerable: true,
      writable: true,
      value: methodHandler
    });
  }
  // Delegate value
  else {
    Object.defineProperty(NgObservableService.prototype, key, {
      configurable: true,
      enumerable: true,
      get() {
        return IterableObserver[key];
      },
      set(value) {
        return IterableObserver[key] = value;
      }
    });
  }
});

// The "keep" getter will make sure that created observables won't be disposed
// automatically once their belonging components are being destroyed,
// e.g. this.observable.keep.of([1, 2, 3]);
Object.defineProperty(NgObservableService.prototype, "keep", {
  configurable: true,
  enumerable: true,
  get() {
    return new NgObservableService({ keep: true });
  }
});
```

The biggest advantage of the code snippet above is that it's generic and it will work with whatever `rxjs` version currently installed in your project, you don't even need to be worried about maintaining this module.  Unfortunately this is not something that can be provided as a third-party service since the auto-disposal mechanism should be hard-coded in the `angular` library, since a service has not direct effect on a component. The implementation above is only a partial implementation of a bigger picture. I believe there should also be few additions made in the [application_ref.ts](https://github.com/angular/angular/blob/master/modules/@angular/core/src/application_ref.ts) file where `onDestroy` callbacks are being registered.

Moreover I would like to know why my feature request is not a good idea and what reason do you have to decline it, if at all. Let's discuss about it first and I would like to know your thoughts of such a feature.

**Comment by DzmitryShylovich** [comment]
The proper solution for this is observable hooks rather a service like `NgObservable`

**Comment by ericmartinezr** [comment]
I might be missing something here, but why not use `takeWhile` instead of `takeUntil`? That will complete the stream, it won't necessary to unsubscribe manually. [More here](https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87#.vlczrzkzy).

**Comment by gdi2290** [comment]
see https://github.com/angular/angular/issues/13248

**Comment by DAB0mB** [comment]
@DzmitryShylovich We can discuss regards the way of the implementation, there can be certainly more than one. Are you talking about global Observable hooks? I've never heard of such a thing. Besides, we need to register a global **component** hooks for `onDestroy`, not for **Observable**.

@ericcarraway The `takeUntil` will complete the subscription only once all messages have been fetched, but what if not all have been fetched and I disposed the component?

@gdi2290 The issue that you referenced, can you please show me exactly where my use case is mentioned? I didn't see anything in particular.

**Comment by DzmitryShylovich** [comment]
@DAB0mB there's a proposal to add observable lifecycle hooks https://github.com/angular/angular/issues/10185

Custom impl looks something like https://gist.github.com/DzmitryShylovich/9b544502fe23fbf2288a3cd2408e23e5

**Comment by intellix** [comment]
I'm using modals from ngb-bootstrap which take Inputs for pushing data in. Now I'm using them to subscribe to `@Output()` EventEmitters as well like:

```ts
const modalRef = this.modalService.open(SomeModalComponent);
modalRef.componentInstance.item = this.item;
modalRef.componentInstance.repeat.subscribe(() => this.open());
```

At the moment I have to manually complete EventEmitters OnDestroy of a component like so:

```ts
doRepeat() {
  this.repeat.next();
  this.activeModal.dismiss();
}

ngOnDestroy() {
  this.repeat.complete();
}
```

I'm thinking this should be auto. Shouldn't all Outputs of a Component emit complete on destroy?

**Comment by Davilink** [comment]
In ours projects we create an array of subscription, pushing every subscription from a subscribe in the array and in the ngOnDestroy with loop over and unsubscribe all the subscription.
```typescript
export class Test implements OnDestroy {
  private subscriptions: Subscription[] = [];

   lazyLoadMessages() {
    this.autoScroller = this.autoScroll();
    this.subscribeMessages();

    // Get total messages count in database so we can have an indication of when to
    // stop the auto-subscriber
    this.countMessages().then((messagesCount) => {
      this.subscriptions.push(
        Observable
          // Chain every scroll event
          .fromEvent(this.scroller, 'scroll')
          // Remove the scroll listener once all messages have been fetched
          .takeUntil(this.autoRemoveScrollListener(messagesCount))
          // Filter event handling unless we're at the top of the page
          .filter(() => !this.scroller.scrollTop)
          // Prohibit parallel subscriptions
          .filter(() => !this.loadingMessages)
          // Invoke the messages subscription once all the requirements have been met
          .forEach(() => this.subscribeMessages())
      )
    });
  }
  ngOnDestroy() {
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }
}
```

**Comment by intellix** [comment]
@Davilink since then I've found you can clean it up by using a single subscription and unsubscribing from the whole collection easily like:
```ts
export class MyComponent implements OnInit, OnDestroy {

  private subscriptions = new Subscription();

  constructor() {
    this.subscriptions.add(timer(100, 100));
  }

  ngOnInit() {
    this.subscriptions.add(timer(200, 200));
  }

  ngOnDestroy() {
    this.subscriptions.unsubscribe();
  }
}
```

**Comment by Davilink** [comment]
So do you think this proposal is still relevant ?
