### ISSUE TITLE
export UrlParser from Router

### ISSUE THREAD

**Issue by govorov** [angular/angular#14544]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

UrlParser class is not exported, so it's impossible to subclass it.
https://github.com/angular/angular/blob/5d9cbd7d6f20dc0d63bd297ccaf68bd0257cb4b8/modules/@angular/router/src/url_tree.ts#L376

**Expected behavior**

UrlParser class may be imported like
import { UrlParser } from '@angular/router';

**What is the motivation / use case for changing the behavior?**

In current version you need to implement all methods from UrlParser on your own, even if you need to tune just few details.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
current

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
Why not use `DefaultUrlSerializer `?

**Comment by govorov** [comment]
I need to create `UrlTree` with custom logic in `parse` method of `DefaultUrlSerializer` subclass.
`UrlTree` uses `UrlParser` inside.

**Comment by DzmitryShylovich** [comment]
> DefaultUrlSerializer uses UrlParser inside

it's an impl detail. If we export it we won't be able to change it...

**Comment by govorov** [comment]
There's also a weird bug with
`let tree = new UrlTree(new UrlSegmentGroup([],{}), {}, null);`
Typescript compiler throws
`Supplied parameters do not match any signature of call target`,
but I copied this line as is from `url_tree.ts`

My tsconfig:
```
{
  "compilerOptions": {
    "target"                 : "es5",
    "module"                 : "commonjs",
    "moduleResolution"       : "node",
    "baseUrl"                : "./src",
    "lib"                    : ["es6", "dom"],
    "emitDecoratorMetadata"  : true,
    "experimentalDecorators" : true,
    "sourceMap"              : true,
    "typeRoots": [
      "./node_modules/@types"
    ]
  }
}
```

**Comment by DzmitryShylovich** [comment]
> There's also a weird bug with

`UrlTree`'s constructor is private.

What are you trying to accomplish? Why do you need to manually create `UrlTree`?

**Comment by govorov** [comment]
I need to parse such url:
`segment1/segment2/filter1=value1/filter2=value2`
and grab `filter1, filter2...` as parameters.

Default parser implementation will cut everything after `filter1`

Would be great if you help me with this.

**Comment by DzmitryShylovich** [comment]
To create `UrlTree`:
```
const urlTree = new UrlTree();
urlTree.queryParams = ...
urlTree.fragment = ...
```

To parse url try to extend `DefaultUrlSerializer`:
```
class MyUrlSerializer extends DefaultUrlSerializer {
    parse(url: string): UrlTree {
        const urlTree = super.parse(url);
        // do some modifications with urlTree
    }
}
```

**Comment by govorov** [comment]
Thank you. It works now)

**Comment by Toxicable** [comment]
@govorov Since it is not planned for `UrlParser` to be exposed and since you have solved your problem you were having do you still consider this issue valid? If not then would you kindly close it

**Comment by DzmitryShylovich** [comment]
everything will be public soon anyway :D
