### ISSUE TITLE
Lazy loaded modules - Component is not defined

### ISSUE THREAD

**Issue by ddyrcz** [angular/angular#14558]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm following the angular module tutorial. 
https://angular.io/docs/ts/latest/guide/ngmodule.html#

 Working on the lazy loading modules with router

![image](https://cloud.githubusercontent.com/assets/20314986/23061681/25eff848-f503-11e6-8405-9f2a98f44670.png)

My code looks almost identical to the code in the tutorial. Before upgrading angular-cli to the latest version everything worked fine, but after update i'm getting error while loading application

![image](https://cloud.githubusercontent.com/assets/20314986/23061858/bc34971e-f503-11e6-8533-db5eeb4d7069.png)

**Expected behavior**

Lazy loading works with the latest version of angular-cli

**Minimal reproduction of the problem with instructions**

Reproduce the lazy loaded modules tutorial steps. 
My package.json dependencies:

"dependencies": {
    "@angular/common": "~2.4.7",
    "@angular/compiler": "~2.4.7",
    "@angular/core": "~2.4.7",
    "@angular/forms": "~2.4.7",
    "@angular/http": "~2.4.7",
    "@angular/material": "^2.0.0-beta.1",
    "@angular/platform-browser": "~2.4.7",
    "@angular/platform-browser-dynamic": "~2.4.7",
    "@angular/router": "~3.4.7",
    "@types/jasmine": "^2.5.41",
    "@types/node": "^6.0.63",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "primeng": "^2.0.0",
    "rxjs": "5.1.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.7"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0-beta.32.3",
    "@types/jasmine": "^2.2.30",
    "@types/node": "^7.0.5",
    "codelyzer": "2.0.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.1",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "5.1.1",
    "ts-node": "2.1.0",
    "tslint": "4.4.2",
    "typescript": "~2.1.6",
    "webdriver-manager": "12.0.2"
  }

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** ~2.4.7

* **Browser:** [Chrome 56]

 
* **Language:** [TypeScript ~2.1.6]

* **Node (for AoT issues):** `node --version` =  v6.9.5

**Comment by DzmitryShylovich** [comment]
Pls provide a small plunkr with repro

**Comment by ddyrcz** [comment]
I could not reproduce this problem by plunker

i've just make a minimal repo that shows the issue

https://github.com/ddyrcz/angular-issue-reproduce

**Comment by DzmitryShylovich** [comment]
`login-routing.module.ts` file
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { LoginComponent } from './login';

export const routes: Routes = [
    { path: 'login', component: LoginComponent }
];

```

**Comment by ddyrcz** [comment]
Works, thanks!

**Comment by DzmitryShylovich** [comment]
close the issue pls, thx.
