### ISSUE TITLE
attribute binding in `@Component()`s `host: {}` doesn't require `attr.`

### ISSUE THREAD

**Issue by zoechi** [angular/angular#14554]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`[attr.spellcheck]="true"` and in `@HostBinding('attr.spellcheck') sp = true;`, 
but in `host: {"spellcheck":"true"}` attr. is not required.

**Expected behavior**

Consistent behavior. `attr.` should be required everywhere when it's attribute binding.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/RyCb9Cs4g5J6fociXfKl?p=preview

Check the added attributes. `spellcheck1` should not be added but cause an error like `@HostBinding('spellcheck4')` (when commented in)

**What is the motivation / use case for changing the behavior?**

consistency

**Please tell us about your environment:**

* **Angular version:** 2.0.X

2.4.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome  57.0.2987.37 (Official Build) beta (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TS

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
`host: {"spellcheck":"true"}` is consistent with `<host spellcheck="true">`

`@HostBinding()` is on a property, which implies `[...]` and `@HostBinding(attr.name) v;` works for `[attr.name]="v"`.
