### ISSUE TITLE
Can't find nested router outlets

### ISSUE THREAD

**Issue by pablodoble** [angular/angular#14556]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a named router-outlet is declared in a component that's been rendered inside a primary router-outlet, angular throws the following error: 

```
Cannot find the outlet dashboard to load 'HomeComponent'
```

**Expected behavior**
Angular should find the nested router-outlet and render the component specified on the route object.

**Minimal reproduction of the problem with instructions**
I've made a plunkr to reproduce the error:

http://plnkr.co/edit/8DYYI03fsty4oGLalgNw?p=preview

In fact, a workaround is been added to the DashboardComponent (commented at this moment). If you register the outlet manually, it works, but in involves accessing a private variable of the Router object.

**What is the motivation / use case for changing the behavior?**
This error should not be raised on this case.

**Please tell us about your environment:**

* **Angular version:** 2.4.7
* **Router version:** 3.4.7

* **Browser:**  Chrome 56.0.2924.87

 
* **Language:**  TypeScript 2.1.6

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Don't think it's a bug. It was never intended to work like this. Named outlets must be used on the same template with primary outlet:
```
template: `
      <router-outlet></router-outlet>
      <router-outlet name="dashboard"></router-outlet>
`,
```

**Comment by pablodoble** [comment]
@DzmitryShylovich so I understand this should be a feature request instead of a bug, right?

**Comment by DzmitryShylovich** [comment]
yeap

**Comment by pablodoble** [comment]
@DzmitryShylovich thanx! Closing this.
