### ISSUE TITLE
FormBuilder.group() calls each custom-validator 3 times

### ISSUE THREAD

**Issue by MickL** [angular/angular#14551]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
FormBuilder.group() calls each custom-validator 3 times per FormControl. Same behavior on sync- and async-validators.

Calling "this.form.controls.KEY.updateValueAndValidity();" would call another validation.

**Expected behavior**
custom-validators should be called only once.

**Minimal reproduction of the problem with instructions**
Plunker:
https://plnkr.co/edit/ejTYTlQc9hxXnPSD2qRa?p=preview
(Please see console)

**Angular version:** 
2.4.1

**Comment by kelvinsleonardo** [comment]
Is there any solution of it ?

**Comment by mhevery** [comment]
There is no guarantees how many times the validator gets called. Your code should be idempotent to the number of calls.

**Comment by MickL** [comment]
Custom validators are often used for http validation. Why do 3 http requests if one is enough and nothing changed? Please reopen as a feature request then.

**Comment by MickL** [comment]
@mhevery Please reopen! Imagine having 1 million users and 3 million requests instead of 1 million. Thats an unnecessary workload of 300%.

**Comment by seritools** [comment]
@MickL Try using a small delay in your pipe before doing your http request. This causes the async validators to be cancelled before the request happens, as the validation engine cancels the ongoing validations.
