### ISSUE TITLE
Angular, SharePoint and IE11, Edge = Memory Leak

### ISSUE THREAD

**Issue by andtii** [angular/angular#14555]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Just by including Angular in a SharePoint environment a memory leaks starts to occur in IE11, Edge, for every page reload the memory increases and is never released until the browser is closed.

**Expected behavior**
No memory leak

**Minimal reproduction of the problem with instructions**
1. Add a script editor webpart to a SharePoint page
2. Include the angular javascripts
3. Save and publish page
4. Start reloading the page in Internet explorer 11
You can see that the memory is increasing and it is not released between page loads

**What is the motivation / use case for changing the behavior?**
Memory Leak = Bad, We have 60+ customers running IE getting memory leak until browser hangs

**Please tell us about your environment:**
We have a SharePoint Online environment ready where you can get the login information so that you can test the behavior!

* **Angular version:** 2.3.0

* **Browser:** IE11, Edge

**Comment by DzmitryShylovich** [comment]
did you enable prod mode?
Pls provide a repro

**Comment by andtii** [comment]
yes prod mode enabled and repro updated, we have a environment setup if you want to try it out i can hand out some login information

**Comment by DzmitryShylovich** [comment]
Can you create a repository that we can clone that demonstrates this?

**Comment by mike-morrison** [comment]
@andtii Can you provide the code they are inserting into the content editor web part?

**Comment by andtii** [comment]
@mike-morrison @DzmitryShylovich Here is the code in the script editor webpart

`
<hello-world></hello-world>
<script type="text/javascript" src="https://mod114707.sharepoint.com/Pages/angular2.bundle.libs.js"></script>
<script type="text/javascript" src="https://mod114707.sharepoint.com/Pages/helloworld.js"></script>
`
And here is the code for helloworld component
https://gist.github.com/anonymous/7ab88a66d234357ae7ca28c9880a50c4

**Comment by andtii** [comment]
If someone wants to try it in SharePoint i can send you the login information.

**Comment by andtii** [comment]
@mizzle-mo  @DzmitryShylovich Intrested helping out here? We can give out Login information to anyone intrested in getting this solved

**Comment by DzmitryShylovich** [comment]
@andtii did you try angular 4?

**Comment by andtii** [comment]
@DzmitryShylovich Yes we tried angular 4 and still same problem

**Comment by tbosch** [comment]
@andtii We really need a simpler way of reproducing this... Could you try to bisect the problem?

**Comment by tbosch** [comment]
Closing to keep our bug tracker under control. Please reopen once you have a good way of reproducing the problem. Thanks!
