### ISSUE TITLE
transform.directive_processor.rewriter assumes `bool` is in "scope" – it might not be

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#1455]
If you turn on package warnings in `examples` or the benchmark projects...

```yaml
- $dart2js:
    commandLineOptions:
    - --show-package-warnings
```

You'll see warnings like this 
```
[Warning from Dart2JS on examples|web/src/hello_world/index.dart]:
packages/angular2/src/facade/math.ng_deps.dart:7:1:
Cannot resolve type 'bool'.
bool _visited = false;
^^^^
```
https://travis-ci.org/angular/angular/jobs/59171347#L1108

```dart
library angular.core.facade.math.ng_deps.dart;

import 'math.dart';
import 'dart:core' show double, num;
import 'dart:math' as math;

bool _visited = false;
void initReflector(reflector) {
  if (_visited) return;
  _visited = true;
}
```

Your code assumes `bool` is always available, but if core is imported with a name, it won't be.

**Comment by kegluneq** [comment]
I'm not sure I'm willing to explicitly add an import for this case, maybe we'll just issue a warning if we think we see `bool` being hidden.

**Comment by kevmoo** [comment]
@kegluneq How do you figure out which imports to put in this file?

Could you do

```dart
import 'dart:core' as dart_core;

dart_core.bool _visited = false;
```

Or similar?

**Comment by kegluneq** [comment]
We copy over all imports from the file each `.ng_deps.dart` file is based on.

We could add that import, but I'm hesitant to do so for every generated file. My objection was going to be code size, but since deployed apps will use `dart2js` anyway maybe that isn't applicable.

**Comment by kevmoo** [comment]
The extra import won't cause any problems in output size.

Getting rid of noise here is important – it'll help us find real bugs later.

**Comment by kegluneq** [comment]
Turns out the proposed solution won't work

From [the spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf)
```
18.1 Imports 

The dart core library dart:core is implicitly imported into every dart library
other than itself via an import clause of the form
import ‘dart:core’;
unless the importing library explicitly imports dart:core.
Any import of dart:core, even if restricted via show, hide or as, preempts the
automatic import.
```

So adding `import 'dart:core' as ...` means that any other uses of dart:core in the file would need to be prefixed as well. I think I'm back to failing the transform if someone his hiding `bool`.

**Comment by kegluneq** [comment]
Is there any reason not to use `var`?

**Comment by kevmoo** [comment]
@kegluneq Nope. :smile:
