### ISSUE TITLE
Error encountered resolving symbol values statically. Calling function 'CreateCustomComponent', function calls are not supported

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular#14553]
I am getting below error when creating my custom component. 

> Error encountered resolving symbol values statically. Calling function 'CreateCustomComponent', function calls are not supporte
d. Consider replacing the function or lambda with a reference to an exported function, resolving symbol cus_input

my file like as below. Any one please give me a answer for below my code ?

    import { NG_VALUE_ACCESSOR } from '@angular/forms';

    export { ContentChild, Type, forwardRef } from '@angular/core';

    export class MyComponent {
    constructor() {
        console.log("Component created");
    }
    }

    export function CreateCustomComponent(componentArgs: {
    selector: string,
    inputs: Array<string>,
    template: string

    }): Type<any> {
    let comp = Component(componentArgs);
    return comp.Class({
        extends: MyComponent,
        constructor: [function () { MyComponent.call( "") }]

       });
    }

    export let cus_input: any = CreateCustomComponent({ selector: 'cus-inp', inputs: ["myinput"], template: '<input [value]="myinput" />' })

    export const MY_INP_Component: any = [cus_input];
Importing like as below in "app.modeule.ts"

     import { MY_INP_Component} from './customcomponent/core';

     import { AppComponent } from './app.component';

     @NgModule({
        imports: [BrowserModule, FormsModule, HttpModule,       RouterModule.forRoot(rootRouterConfig, { useHash: true })],
        declarations: [AppComponent, 
         MY_INP_Component
       ],
      bootstrap: [AppComponent],
  
       })
    export class AppModule { }

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AbinayaSubbiah** [comment]
@DzmitryShylovich  could you please help me to find out answer for the above.

**Comment by AbinayaSubbiah** [comment]
am having number of jquery component, so i have dynamically creating component. In that i passed component model to my jquery plugin and rendering my jquery control.


i have used common method "CreateCustomComponent" to create component dynamically.

But with AOT m getting the error 

>  Error encountered resolving symbol values statically. Calling function 'CreateCustomComponent', function calls are not supporte d. Consider replacing the function or lambda with a reference to an exported function, resolving symbol cus_input "

help me to find out solution?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource support request

**Comment by tbosch** [comment]
For AOT, you cannot use the ES5 helper functions `.Class`, ... but you should rather create real TypeScript `class` definitions with decorators like `@Component` / `@NgModule` on them...
