### ISSUE TITLE
[NO ERROR LOGS] Why is the new 1.6.2 version not spitting errors?

### ISSUE THREAD

**Issue by dashawk** [angular/angular#14557]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

My callback function is not being called.

An example:
```javascript
var getItem = function(id, callback) {
   if (x.callable(callback)) {
      callback.call(this, arguments);
   }
};

getItem(1, function (myArgs) {
   console.log('This is not called here');
});
```

**Expected behavior**

An example:
```javascript
var getItem = function(id, callback) {
   if (x.callable(callback)) {
      callback.call(this, arguments);
   }
};

getItem(1, function (myArgs) {
   console.log('This should be called here');
});
```

**Minimal reproduction of the problem with instructions**

Create a wrapper for example $resource. Do not return anything for this wrapper, just add a callback argument for the response.

**What is the motivation / use case for changing the behavior?**

I wanted to my services to like myFn(data, callback) and not myFn().then();

**Please tell us about your environment:**

* **OS:** Windows 10
* **IDE:** Webstorm

* **Angular version:** 1.6.2

* **Browser:** [ Chrome 56.0.2924.87 ]

 
* **Language:** [ES5]

* **Node (for AoT issues):** `node --version` =  6.3.1

**Comment by DzmitryShylovich** [comment]
this is angular 2 repo
