### ISSUE TITLE
Directive naming conventions need to be clearer

### ISSUE THREAD

**Issue by Roam-Cooper** [angular/angular#1456]
I haven't found specific documentations stating EXPLICITLY (and boldly) that directives MUST be named in camelCase, I spent a long time trying to figure out why a particular directive was not working. It'd be nice to see this mentioned very clearly, at the very start of the documentation on controllers (I was reading https://code.angularjs.org/1.3.15/docs/guide/directive

In Angular 1.3.15 I can't name a directive TestDirective. It had to be named testDirective to work.

Please let me know if I am in error.

**Comment by vicb** [comment]
This repo is for Angular2. If your question only apply to 1.x, please re-open it on https://github.com/angular/angular.js

**Comment by Roam-Cooper** [comment]
Ah, thank you. :) I'll reopen it there.
