### ISSUE TITLE
dealing with library specific attribute

### ISSUE THREAD

**Issue by craigcosmo** [angular/angular#14563]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
angular doesn't understand library specific attribute

`Parser Error: Unexpected token Lexer Error: Unterminated quote at column 3 in expression [ 'youtube] at column 4 `

**Expected behavior**
angular should know what is library specific attribute and leave it alone

**Minimal reproduction of the problem with instructions**
```ts
import plyr from 'plyr'
@Component({
    selector: 'VideoPLayer',
    template: `
        <div data-type="youtube" data-video-id="qiML7qMvxWE"></div>
    `
})
export class PlayerComponent implements AfterViewInit {
    ngAfterViewInit(){
        let instances = plyr.setup({
        })
    }
}
```
**What is the motivation / use case for changing the behavior?**
`data-type` and `data-video-id` is necessary for plyr lib to run.

**Please tell us about your environment:**
sublime, mac os 10

* **Angular version:** 2.0.X
2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all browser
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
node 6

**Comment by DzmitryShylovich** [comment]
> angular doesn't understand library specific attribute

what does it mean? error?

**Comment by craigcosmo** [comment]
yes, updated the post with error message.

**Comment by DzmitryShylovich** [comment]
pls provide a plunkr

**Comment by craigcosmo** [comment]
http://plnkr.co/edit/jvNg4NtkZwNycbP8OYUe?p=preview

**Comment by DzmitryShylovich** [comment]
yeah, I don't see any errors

**Comment by craigcosmo** [comment]
the video is not shown. If you change `data-video-id="name" to `data-video-id="qiML7qMvxWE"` it shows.

**Comment by DzmitryShylovich** [comment]
`[attr.data-video-id]="name"`
