### ISSUE TITLE
Dyanmic Component With Dynamic CSS and Dynamic Template

### ISSUE THREAD

**Issue by BrkCoder** [angular/angular#14568]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Not Existing

**Expected behavior**
I want to have the ability to generate a dynamic component using dynamic template and dynamic css and dynamic selector
```
@Component({
    // 2a
    selector: 'dynamic placeholder',

    // 2b
    styles: [`dynamic styles`] 

    // 2c
    template: `dynmic template`
})

IF this feature already exist I would be happy to know about it and get an example of use.
```

**Please tell us about your environment:**
Window

* **Angular version:** 2.0.X
angular 2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:**TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/api/core/index/Compiler-class.html

**Comment by BrkCoder** [comment]
Thanks for the quick replay, but how can I use this compiler class, no examples are provided in the docs and neither in the internet.
I am clueless regarding this subject.

**Comment by DzmitryShylovich** [comment]
https://github.com/shlomiassaf/lazy-jit/blob/15018f29da7b6fff653f63f40f9a6c592c150339/src/app/features/lazy/lazy.component.ts#L34

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by BrkCoder** [comment]
ok thx

**Comment by DzmitryShylovich** [comment]
close the issue pls, thx :)
