### ISSUE TITLE
Cannot find namespace angular

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#14561]
i used the following statement in typescript source file as below referred from angular.io documentation 
declare var angular:angular.IAngularStatic;

But it giving me error -
Cannot find namespace angular.

I tested the same in quickstart project also. same issue

**Comment by DzmitryShylovich** [comment]
what is `declare var angular:angular.IAngularStatic;`?

**Comment by vasuneet** [comment]
this is for reference angular in hybrid approach as mentioned in documentation 

https://angular.io/docs/ts/latest/guide/upgrade.html#!#making-angularjs-dependencies-injectable-to-angular

**Comment by DzmitryShylovich** [comment]
Pls re-open it on https://github.com/angular/angular.io/issues

**Comment by vasuneet** [comment]
But what is the issue any idea ?

**Comment by DzmitryShylovich** [comment]
I don't use ng1 so no ideas :)

close this issue, pls. thx

**Comment by vasuneet** [comment]
This issue is related to angular 2 itself.

**Comment by Adol1111** [comment]
@vasuneet npm i --save-dev @types/angular

**Comment by vasuneet** [comment]
I did as advised but now i am getting the following errors -

node_modules/@types/core-js/index.d.ts(21,14): error TS2300: Duplicate identifier 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(85,5): error TS2687: All declarations of 'name' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(145,5): error TS2403: Subsequent variable declarations must have the same type.  Variable '[Symbol.unscopables]' must be of type '{ copyWithin: boolean; entries: boolean; fill: boolean; find: boolean; findIndex: boolean; keys: ...', but here has type 'any'.
node_modules/@types/core-js/index.d.ts(262,5): error TS2687: All declarations of 'flags' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(276,5): error TS2687: All declarations of 'EPSILON' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(311,5): error TS2687: All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(318,5): error TS2687: All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(457,5): error TS2403: Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"Symbol"', but here has type 'string'.

**Comment by DzmitryShylovich** [comment]
paste `tsconfig.json`

**Comment by vasuneet** [comment]
resolved this. It is giving due to having core-js. resolved.

**Comment by shiraeeshi** [comment]
I'm trying to integrate angularjs and angular and I'm stuck now because of this issue.
I tried to remove core-js dependency - same result.
@vasuneet, would you please explain how did you resolve it?

**Comment by correasebastian** [comment]
hi @vasuneet , how did you fix the error "Cannot find namespace angular."
im following the upgrade guide but i cannot find the solution.
thx

**Comment by squirrelsRduck** [comment]
@correasebastian If you are following the ngUpgrade tutorial, the issue is not having core-js installed, as @vasuneet mentioned.  Rather, the issue occurs when you forget to delete the .js file from index.html for the given *.ts file name that is receiving the error.  Delete the corresponding JS file from the script tags in index.html, and the issue goes away.

**Comment by happysamyak** [comment]
I am facing the same issue.

**Comment by HimanshuDreamer** [comment]
Hello friends,

I have faced the same issue while working with Angular JS with SharePoint Frameworks (SPFX), I have resolved after performing following modifications in code

In the code editor, open the **./src/webparts/toDo/ToDoWebPart.ts** file. After the last import statement, add the following code:
**import * as angular from 'angular';**

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/migrate-angular-1-x-applications-to-sharepoint-framework

**Comment by ghoule636** [comment]
I fixed this issue but putting 'use strict';
