### ISSUE TITLE
http injection is undefined when running as prod

### ISSUE THREAD

**Issue by tmburnell** [angular/angular#14560]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://stackoverflow.com/questions/42276122/angular2-this-http-undefined-when-run-as-prod
When using --prod flag (or --aot) all my services inject undefined in the constructor to HTTP ... therefore when this.http.get is run an error occurs saying get is not a function of undefined. 

**Expected behavior**
Should work the same as when the prod flag is not used.  

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Trying 

**Please tell us about your environment:**
Have tried using "ng serve --prod" with proxy to nodejs.
Also "ng build --prod" then hosted by a springboot app. 
I have seen the same issue when i use --AOT

* **Angular version:
cli 31, core 2.4.7

* **Browser:
Only tested with Chrome (but assume it is all)
 
* **Language:
TypeScript

* **Node (for AoT issues):
7.5.0

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
