### ISSUE TITLE
How to reload “index.html” in angularJS without manual intervention?

### ISSUE THREAD

**Issue by kmalhotra** [angular/angular#14575]
I have a website developed in AngularJS, and index.html serves the root of the application.

All the JS and CSS versions are maintained in the index.html itself, which means for any changes to reflect to the user, "index.html" is to be reloaded at the browser.(correct me if I am wrong here). This is a problem, since there could be chances that the user has a tab opened of our website in his browser and we have published a new release. This release will not be published at user's browser till the time a "Manual refresh" is not triggered and "index.html" is not reloaded and hence bring up the possibility that the user will not be using our latest release.

We have written a framework to reload all resources once a release is detected by sending the latest version from web-server and comparing this with the current version in the browser and trigger a reload automatically. This fix works fine, but the problem again is, how to publish this release first time to all user's browser?

I hope you get my problem? let me know otherwise.

**Comment by DzmitryShylovich** [comment]
This is angular 2 repo
