### ISSUE TITLE
Expression has changed after it was checked. Previous value

### ISSUE THREAD

**Issue by AmitMY** [angular/angular#14577]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When value change, seldom, this error is thrown and the app fails to respond any longer.
I have in my view this function:
`{{generalService.timeFromNow(item.creation_time)}}` which calls:
`moment(timestamp, "X").fromNow()`

Randomly, when time changed from 35 to 36, this error happened.
![image](https://cloud.githubusercontent.com/assets/5757359/23095342/10324650-f611-11e6-8e07-04e60276bc6d.png)

If I have another time moving (ticking) minutes, no error is thrown.

**Expected behavior**
Value to be able to change without breaking the app

**Minimal reproduction of the problem with instructions**
I don't know.

**What is the motivation / use case for changing the behavior?**
Bugs need to be resolved.

**Please tell us about your environment:**
Windows 10, PHPStorm, NPM, Node.js  (ionic 2)

* **Angular version:** 2.2.1

* **Browser:** all
 
* **Language:** TypeScript 2.0.9

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AmitMY** [comment]
I thought it was a bug, From your response I understand it is intended
