### ISSUE TITLE
<ng-component> doesn't replace <router-outlet> when the code is loaded

### ISSUE THREAD

**Issue by oztek22** [angular/angular#14576]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently <ng-component> is being placed after the <router-outlet> Instead of replacing it.

**Expected behavior**

<ng-component> should replace the content of <router-outlet> as the selector does(Code Inside <root> tag is replaced by the template of AppComponent).

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I want to display the loader inside router-outlet until the screen is loaded.(Like it shows the message "AppComponent is loading..." in angular starter pack.

**Please tell us about your environment:**

* **Angular version:** 2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All Browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript:2.0.10
ES5

* **Node (for AoT issues):** `node --version` =   7.4.0

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/8529#issuecomment-217718704 it's required for animations
