### ISSUE TITLE
2.4.8 breaks - error is "Mixing multi and non multi provider is not possible for token"

### ISSUE THREAD

**Issue by yonimoses** [angular/angular#14589]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The app won't start. error message is "Mixing multi and non multi provider is not possible for token"

**Expected behavior**
The app should start ?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Linux, NG 2.4.8

* **Angular version:** 2.0.X
2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =   
6.9.5

**Comment by DzmitryShylovich** [comment]
Pls provide a plunkr

**Comment by AlexKhymenko** [comment]
Having the same issue but using version angular 4.0.0-beta-8. With ng-Upgrade.

**Comment by yonimoses** [comment]
I found the the issue .. I've provided my own provider to angular to support  i18n which gave me the error .
Removed it and the error is gone.

**Comment by AlexKhymenko** [comment]
I had the problem in this code Maybe it will help somebody

` { provide: APP_INITIALIZER, useFactory:  (HttpErrorHandler) => {
      //do something here    
     }, deps: [HttpErrorHandler]
  },`

**Comment by DzmitryShylovich** [comment]
@AlexKhymenko 
```
{ provide: APP_INITIALIZER, multi: true, useFactory: (HttpErrorHandler) => {}, deps: [HttpErrorHandler] },
```
See https://blog.thoughtram.io/angular2/2015/11/23/multi-providers-in-angular-2.html

**Comment by AlexKhymenko** [comment]
@DzmitryShylovich Thank you.

**Comment by georgefrick** [comment]
What is the point of multi argument if it has to be true?
