### ISSUE TITLE
Feature Request: Watch changes in a model

### ISSUE THREAD

**Issue by shyamal890** [angular/angular#14585]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no way to dirty check an object or an array. 

**Expected behavior**
Would be great if angular2 can support $watch alternative as RxJs doesn't have anything to watch model changes.

**What is the motivation / use case for changing the behavior?**
Say you have a sidebar model with following model structure:

```
                                  SidebarInfo
                                         /\
                             Group1    Group2...... GroupN
                                 /\
                        Users   OtherInfo...........
```
Whenever, any user model property in this model is updated, another `globalUsers` model too should be updated. Note, users under `SidebarInfo` is a subset of `globalUsers` array. The problem of not having $watch is:

One needs to be careful and not forget updating `globalUsers` when any of the `SidebarInfo->Users` have been updated. As we want both of the `globalUsers` users and `SidebarInfo` users to be in sync property wise.

Extra code that has to be written for each user property CRUD operation, so that both models are in sync.

Having $watch in Angular1 made this very simple.

**Comment by Toxicable** [comment]
Can you please fill out the Issue template correctly

**Comment by DzmitryShylovich** [comment]
@shyamal890 use case?

**Comment by shyamal890** [comment]
Usecase:

Say you have a sidebar model with following model structure:
                                  SidebarInfo
                                         /\
                             Group1    Group2...... GroupN
                                 /\
                        Users   OtherInfo...........
 
Whenever, any user model property in this model is updated, another `globalUsers` model too should be updated. Note, users under `SidebarInfo` is a subset of `globalUsers` array. The problem of not having $watch is:

1. One needs to be careful and not forget updating `globalUsers` when any of the `SidebarInfo->Users` have been updated. As we want both of the `globalUsers` users and `SidebarInfo` users to be in sync property wise.

2. Extra code that has to be written for each user property CRUD operation, so that both models are in sync.

Having $watch in Angular1 made this very simple.

**Comment by vicb** [comment]
@shyamal890 please update the original message

**Comment by mlc-mlapis** [comment]
You are probably requesting something what is fully under your control.

**Comment by DzmitryShylovich** [comment]
There's `Observable.ofObjectChanges` in rxjs v4 but it was removed in v5.

We can add a helper method. Here's the impl https://gist.github.com/jayphelps/d8641e7213b56d368e7b
@vicb what do you think?

**Comment by otodockal** [comment]
"$watch in Angular1 made this very simple."
- yeah, but your model should not affect CD time, so I'm happy it's gone in NG2.0+

In my opinion, it is out of the scope of the framework. Shouldn't be Angular responsible only for watching changes in templates?

**Comment by tbosch** [comment]
Yes, sorry, but watching changes in models is out of scope for Angular.
There are already multiple solutions for this, and they depend on your model. E.g. you can use immutable data structures, use observables, ...
