### ISSUE TITLE
Symbol without members expected error after 2.4.7 -> 4.0.0-beta.8

### ISSUE THREAD

**Issue by ctrl-brk** [angular/angular#14580]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After moving from 2.4.7 to 4.0.0-beta.8 I'm getting the following error when executing `ng build -prod`. Just `ng build` (without -prod) works fine.

ERROR in Illegal state: symbol without members expected, but got {"filePath":"C:/Projects/myproj/node_modules/@angular/router/index.d.ts","name":"__router_private__","members":["ROUTER_PROVIDERS"]}.

**Expected behavior**

`ng build -prod` should work as `ng build`

**Please tell us about your environment:**
Windows 10, @angular/cli 1.0.0-beta.32.3
* **Angular version:** 4.0.0-beta.8
* **Node (for AoT issues):** `node --version` =  7.5.0

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by truongminh** [comment]
My project encounters the same issues.
Can you help explain the reason?
