### ISSUE TITLE
Unable to get property 'apply' of undefined or null reference in IE 11 with Angular 2.4

### ISSUE THREAD

**Issue by zhxx** [angular/angular#14592]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I used 'ng init' to initialized an Angular 2 web app, and after 'ng serve' it keeps showing 'Loading...' in IE 11. I noticed that in the console of development tools of IE, it said 'SCRIPT5007: Unable to get property 'apply' of undefined or null reference'. It works in 2.3.0 and 2.2.x as I known.

**Expected behavior**

It should say 'app works!' in the page.

**Minimal reproduction of the problem with instructions**

* create a new folder.
* run 'ng init' in command line.
* run 'ng serve' and open http://localhost:4200 in IE browser.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.0

* **Browser:** IE 11

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  6.9

**Comment by Habeeb-mohamed** [comment]
I am also having same issue

**Comment by fscali** [comment]
I have the same issue too..

**Comment by rusdawg400** [comment]
same issue here

**Comment by DzmitryShylovich** [comment]
@zhxx pls provide a plunkr

**Comment by zhxx** [comment]
@DzmitryShylovich Sorry, I don't know how to create a plunkr demo with Angular 2.4 version.

**Comment by DzmitryShylovich** [comment]
@zhxx http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by Habeeb-mohamed** [comment]
Not even piece of code is needed

1. ng new ietest
2. cd ietest
3. ng serve

`ng --version`
```
@angular/cli: 1.0.0-beta.32.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8
```

**Comment by DzmitryShylovich** [comment]
@Habeeb-mohamed if it's not reproducible on Plunkr then it's an issue with angular cli and should be reported on the different repo

**Comment by zhxx** [comment]
@DzmitryShylovich I know how to create an Angular 2 plunkr demo, but I don't know how to select the version of Angular. This issue can be reproduce with version 2.4 but cannot be reproduced with 2.2.x or 2.3.x. All of the configuration files are the same, only the version of Angular is different, could it be an Angular CLI issue?

**Comment by DzmitryShylovich** [comment]
@zhxx the given plunkr uses `2.4.8` version

> I don't know how to select the version of Angular

in `config.js` file change `@angular/core': 'npm:@angular/core/bundles/core.umd.js` => `@angular/core': 'npm:@angular/core@2.3.0/bundles/core.umd.js` (for all modules)


> could it be an Angular CLI issue?

of course

**Comment by zhxx** [comment]
@DzmitryShylovich Thanks.
