### ISSUE TITLE
Router 3.4.8 tries to import missing token

### ISSUE THREAD

**Issue by KyKyPy3** [angular/angular#14590]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The app won't start.  Error message is 'Token must be defined!'

**Expected behavior**
Application successfully start

**Minimal reproduction of the problem with instructions**
Angular Router (v 3.4.8) try to import **LOCATION_INITIALIZED** from @angular/common. But I could not find such constant in @angular/common sources.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

MacOS, Visual Studio Code

* **Angular version:** 2.0.X
4.0.0-beta.8
Angular Router 3.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome  56.0.2924.87 (64-bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.1.5
* **Node (for AoT issues):** `node --version` =   
v7.5.0

**Comment by DzmitryShylovich** [comment]
Pls provide a plunkr with repro

**Comment by KyKyPy3** [comment]
I think the problem is that the [https://github.com/angular/angular/pull/14155](commit) is not merged. You can download router from npmjs and invistigate the source.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
