### ISSUE TITLE
Component doesn't inherit service from superclass in 2.4.7

### ISSUE THREAD

**Issue by doender** [angular/angular#14591]
In Angular 2.4.4, inheriting from a superclass component worked, as in the following example:

```
@Component({
    selector: 'base-component',
    templateUrl: 'base-component.html',
})
export class BaseComponent {
    constructor(private service:MyService) {
        console.log("Service:", service);
    }
} 

@Component({
   selector: 'child-component',
    templateUrl: 'child-component.html',
})
export class ChildComponent extends BaseComponent {
}

```

However, in Angular 2.4.7, the service now is undefined when instantiating `<child-component>`.

**Comment by DzmitryShylovich** [comment]
pls provide a plunkr with repro

**Comment by DzmitryShylovich** [comment]
what ts version do you use? ng 2.x doesn't support ts 2.1.x+

**Comment by doender** [comment]
We use typescript 2.0.3

**Comment by DzmitryShylovich** [comment]
@doender plunkr?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource works as expected https://plnkr.co/edit/3lL7gdr6nrsVJLzhXz4c?p=preview
can be closed

**Comment by tbosch** [comment]
Sorry, but I agree with @DzmitryShylovich that we need a reproduction...

**Comment by doender** [comment]
I wasn't able to reproduce this in a plunkr... I haven't had this issue anymore in Angular 4, so I'll close this
