### ISSUE TITLE
Cannot find name 'Iterable'.

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#14595]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
```

**Current behavior**

I recently upgraded my angular 2 project to 4.0.0-beta.8. But when I try to compile, it throws below error:
 
**node_modules/@angular/core/src/change_detection/differs/iterable_differs.d.ts(15,48): error TS2304: Cannot find name 'Iterable'.**

I have also seen a question with similar error on stackoverflow but no one has responded yet.

http://stackoverflow.com/questions/42252002/angular2-cannot-find-name-iterable-in-core

**Comment by ericmartinezr** [comment]
This has nothing to do with angular itself, it's a typing thing. How does your tsconfig look like? Make sure you're using ts2.0+

**Comment by naveedahmed1** [comment]
Thank you @ericmartinezr for your reply. I am using TypeScript 2.1.5 and below is my tsconfig:
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": true,
    "sourceMap": false,
    "target": "es5",
    "outDir": "../content/app/"
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}

and I am using Visual Studio 2015 with latest update 3

**Comment by ericmartinezr** [comment]
If you add `lib: ["es2015", "es2015.iterable"]` (as seen [here](https://github.com/Microsoft/TypeScript/blob/03b9066b7d2e5ea4f042103400760b70a002194e/src/lib/es2015.iterable.d.ts#L22)) to your `compilerOptions`, does it work?

**Comment by naveedahmed1** [comment]
It increased the number of errors to 2297

**Comment by ericmartinezr** [comment]
lol... can you share a repo of your project? I can't look at it right now though

**Comment by naveedahmed1** [comment]
In my main.ts I removed

/// <reference path="./../typings/browser/ambient/es6-shim/index.d.ts" />

and added

///<reference path="./../typings/globals/core-js/index.d.ts"/>

which fixed the issue.

**Comment by ericmartinezr** [comment]
@naveedahmed1 
I know you fixed it, but lets try something else, if it doesn't work just go back to what solved your issue.

Remove the line you posted above and add this in your tsconfig.json

```
"compierOptions" : {
     "lib" : ["es2015", "es2015.iterable", "dom"]
}
```
if that works, try removing `es2015.iterable`, if that doesn't work ignore everything :P 

PS : If you already solved your problem please close this issue, thanks.

**Comment by naveedahmed1** [comment]
With the changes you suggested, it now throws 26 errors including:

```
All declarations of 'size' must have identical modifiers
All declarations of 'prototype' must have identical modifiers.
```

**Comment by ericmartinezr** [comment]
@naveedahmed1 sorry then man, I'm out of ideas, stick to what works for you 👍

**Comment by naveedahmed1** [comment]
no worries! always appreciate your help :)

**Comment by pawelczak** [comment]
I came across same issues. Fixed it by adding parameter in tsconfig.json `"skipLibCheck": true`.

**Comment by xtianus79** [comment]
@pawelczak is this a bug?  The fix works but why

**Comment by xtianus79** [comment]
I added this and it fixed all my new typescript warnings. 

"lib": ["es2015", "es2017", "dom"]

You can read this

[https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#including-built-in-type-declarations-with---lib](lib manual)

[https://github.com/Microsoft/TypeScript/issues/6974](typescript lib origination doc)

[http://stackoverflow.com/questions/35959372/property-assign-does-not-exist-on-type-objectconstructor](related issue and ref)

**Comment by jspizziri** [comment]
I was experiencing the same issue and the first **PS** from https://github.com/angular/angular/issues/14595#issuecomment-281148058 solved my issue. I simply reinstalled all my typings with the `@types` method.

**Comment by KoushikJit** [comment]
Same issue. 
adding 
```
"compierOptions" : {
     "lib" : ["es2015", "es2015.iterable", "dom"]
}
```
solved it.
Thanks @ericmartinezr !

**Comment by jsvini** [comment]
Upgrading typescript solved the issue for me.

**Comment by scriptmaster** [comment]
"compilerOptions": {
        "target": "es5",
        "lib": [ "es6", "dom" ]
    }

solved it.

**Comment by irejwanul** [comment]
"compilerOptions": {
    "target": "es5",
    "lib": [ "es2017", "dom" ]
}
The 'lib' option was mainly causing the error, and more specifically it is the "dom" lib option to add.

**Comment by tylerjgarland** [comment]
"compilerOptions": {
"target": "es5",
"lib": [ "dom" ]
}

worked for me

**Comment by preist** [comment]
This worked for me:
```bash
npm i @types/node --save-dev`
```

The node typing contains the `Iterable` definition for `--lib es5` it seems.

**node_modules/@ types/node/index.d.ts**
```javascript
interface Iterable<T> { }
interface Iterator<T> {
    next(value?: any): IteratorResult<T>;
}
```

**Comment by kumaresan-subramani** [comment]
I came across same issues. Fixed it by  Adding “lib”: [ “es2015”, “dom” ] in tsconfig.json
