### ISSUE TITLE
[Feature Request] @TemplateChild and @TemplateChildren decorators

### ISSUE THREAD

**Issue by robgha01** [angular/angular#14593]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We have no way to query for a template child or childreen with a decorator ex:
"inputEditTemplate" can have "EditorInstanceComponent" this is sort of a marker for the user to set where he/she wants to output a editor in the user based template.

The component then tries to query for ContentChild "EditorInstanceComponent" however this returns
undefined as it lives inside the "EditState" template.
```
@ContentChild("EditState") inputEditTemplate: TemplateRef<any>;
@ContentChild(EditorInstanceComponent, { read: true }) inputEditorControl: EditorInstanceComponent;
```
If we got a decorator that looks inside a template for the selector for example:
```
@ContentChild("EditState") inputEditTemplate: TemplateRef<any>;
@TemplateChild(EditorInstanceComponent, { read: true }) inputEditorControl: EditorInstanceComponent;
```

**Expected behavior**
Support for template based selectors.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
To be able to "query" for "selectors" in templates.

**Please tell us about your environment:**

* **Angular version:** 2.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by ghetolay** [comment]
You're looking for [@viewChild](https://angular.io/docs/ts/latest/api/core/index/ViewChild-decorator.html)

**Comment by robgha01** [comment]
@ghetolay well, the actual template is not in the view itself its in the content as in not in the component template html. i tested with @ViewChild however it cant find the selector in a template it looks like this:
```
<inline-text-editor style="display: inline-block;" class="row" formControlName="displayName" type="text" name="Namn" [oneState]="true">
<template #PresentationState let-editor>
    <span class="col-xs-3 text-right">Namn</span>
    <p class="col-xs-9 text-left"> {{ editor?.value }}</p>
</template>
<template #EditState let-editor>
    <div class="row">
        <div class="col-xs-12">
            <label for="inline-editor-{{ editor.name }}" class="control-label">{{ editor.name }}</label>
            <editor-instance></editor-instance>
        </div>
    </div>
</template>
```
This is a user based template variant if no one passes in EditState template then the Default is used:
```
<template #DefaultEdit>
    <input #inlineEditControl class="form-control" id="inline-editor-{{ this.name }}" [value]="value" (input)="value = $event.target.value"
           (blur)="onTouched()" (focusout)="onTouched()"
           [required]="required" [disabled]="disabled" [name]="name" [placeholder]="placeholder" />
</template>
```
the main problem here is that i need to select editor-instance and that has "#inlineEditControl" in itself by using a template outlet that looks like this (omitting unrelated code):
```
@Component({
    selector: "editor-instance",
    template: `<template #Editor *ngIf="this?.inlineEditor.editing" [ngTemplateOutlet]="this?.inlineEditor.defaultEditTemplate" [ngOutletContext]="{ $implicit: this?.inlineEditor }"></template>`
})
export class EditorInstanceComponent
...
```
however ContentChild or ViewChild can not query for stuff that live in a template (im using template outlet).

**Comment by ghetolay** [comment]
I'm blown by the complexity of your example. 
Try a minimal example on a plunker.

**Comment by robgha01** [comment]
@ghetolay yea, it is complicated i reverted back to my start point where i need to figure out how to well let the child template context mark where the editor should get inserted this is not someting i know is possible i mean how can one even get hold of a template reference that live inside a template ex:
```
<some-component>
<template #TemplateForEditingState>
<div>
<h3>Hi i am a consumer that wants a custom template when the edit button is clicked and state changes to editing</h3>
<p>However now when i have overriden the "Default" editing template the input is not inserted anywhere and i cant edit the value :'( </p>
</div>
</template>
</some-component>
```
What i would want to do with the above is someting like a marker or placeholder:
```
<some-component>
<template #TemplateForEditingState>
<div>
<h3>Hi i am a consumer</h3>
<p>A happy day with no rain washes away... </p>
<template #InputPlaceholder></template>
</div>
</template>
</some-component>
```
Then the InputPlaceholder would inject the overriden template as in it would insert what was default but
with the users additions.

I tried to simplify the problem and what i am trying to accomplish :)

**Comment by robgha01** [comment]
@ghetolay Ok, i managed to do it like this: (note the important part in #EditState template)
`<template [ngTemplateOutlet]="editor.defaultEditTemplate" [ngOutletContext]="{ $implicit: editor }"></template>`
```
<inline-text-editor>
    <template #PresentationState let-editor>
        <div>
            <i class="fa fa-user" aria-hidden="true"></i> namn
        </div>
        <p>{{ editor?.value }}</p>
    </template>
    <template #EditState let-editor>
        <div class="row">
            <div class="col-xs-12">
                <label for="inline-editor-{{ editor.name }}" class="control-label">{{ editor.name }}</label>
                <template [ngTemplateOutlet]="editor.defaultEditTemplate" [ngOutletContext]="{ $implicit: editor }"></template>
            </div>
        </div>
    </template>
</inline-text-editor>
```
This actually works and is simple to what i had before but i still need to pass in the editor.defaultEditTemplate i would want a component or someting to figure that out by itself somehow and not force that upon the user. is that possible ?

**Comment by robgha01** [comment]
Ok i think its solved now xD its easy to complicate but hard to simplify the solution to my problem was 
point 2. inject the parent to its child component by doing this:

The parent has this:
`@ContentChild(RenderEditorComponent) protected renderEditorComponent: RenderEditorComponent;`

that component is like a placeholder that looks like this:
```
@Component({
    selector: "render-editor",
    template: `<template [ngTemplateOutlet]="editor?.defaultEditTemplate" [ngOutletContext]="{ $implicit: editor }"></template>`
})
export class RenderEditorComponent {
    editor = null;
}
```
now one can just override the default edit template and use the above RenderEditor where one wants to insert the pre defined template.

To set the editor in "RenderEditorComponent" so template outlet gets outputted:
```
public initEditState() {
        const self = this;
        if (self.renderEditorComponent) {
            setTimeout(() => {
                this.zone.run(() => {
                    self.renderEditorComponent.editor = self;
                });
            });   
        }
    }
```
its that simple but still sort of a hack xD
Thanks for the help @ghetolay i needed to realise that this solution was just to complicated build. :)
