### ISSUE TITLE
To-void animation fails when declared prior to another animation declaration

### ISSUE THREAD

**Issue by bkirby989** [angular/angular#14606]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If an animation describing a transition to a void state is declared before another animation on a component then the void animation doesn't run. 

**Expected behavior**

Void animation should run on elements with multiple animations defined regardless of the order that those animations were declared.

**Minimal reproduction of the problem with instructions**
I re-purposed a previous animation bug plunk. http://plnkr.co/edit/77wjzmcZAlrWp0ZCg7OE?p=preview

Outer animates its collapse as it should, Inner doesn't animate and throws a "partial keyframes are not supported" error. Defining the void animation ([@animateInner] / [@animateOuter]) last on the element makes the animation run normally; defining it first causes it to fail. 

* **Angular version:** 4.0.0-beta.8

* **Browser:** **all** 

 
* **Language:**  **TypeScript 2.0.10**

**Comment by matsko** [comment]
This may very well be fixed in the current version of Angular. Can you please retest and reopen the issue if it is still relevant? Thank you.
