### ISSUE TITLE
Bad error message `Cannot read property 'replace' of undefined`

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#1460]
User got stuck, asked for help on SO:
http://stackoverflow.com/questions/29121678/angular-2-component-inside-main-component

caitp mentions on slack:
that one in particular is thrown here https://github.com/v8/v8-git-mirror/blob/master/src/ic/ic.cc#L698 --- i'm surprised the type assertion stuff isn't catching that before the inline cache gets it

**Comment by vicb** [comment]
Unable to reproduce, I get the "descriptive" error message
```
Failed to load the template "function () {
        ;
      }"
```

I'll open a PR to add the url though.
