### ISSUE TITLE
NgModule not found after update node_modules to 3.10.10

### ISSUE THREAD

**Issue by Sovondev** [angular/angular#14612]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am not able to find NgModule inside "@angular/core" after i update the node_modules to 3.10.10 using the command "npm update".Actually core.d.ts is not there in the @angular/core/src.
**Expected behavior**

VSCODE intellisense throwing error while I am importing the NgModule after the update.Though it should not be .
**Minimal reproduction of the problem with instructions**

Using [(ngmodel)] for two way data binding i have add an extract dependency(@angular/forms) to my package.json file.The form module was not there inside the @angular folder as i am playing with my package.json file to know it closely.But after the update i found the error.
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 8,VSCODE,npm,lite-server
* **Angular version:** 2.0.X

NA
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 chrome 56.0.2924.87 (64-bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0
* **Node (for AoT issues):** `node --version` =   
6.9.4

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
