### ISSUE TITLE
@angular/router@3.4.8 is not working?

### ISSUE THREAD

**Issue by arrian0511** [angular/angular#14610]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular app is not loading all of its component after updating to latest version.

**Expected behavior**
Angular app is working the same thing as the previous version.

**Minimal reproduction of the problem with instructions**
I'm trying to load a angular app using @angular/router@3.4.6 and all works fine, However when I tried to update my packages using "npm update" all packages which are outdated are updated as expected, but when I tried to run again the angular app it fails (no error on inspect element in browser).

**What is the motivation / use case for changing the behavior?**
During the investigation, I tried to update the packages 1by1 and found out that the error occurred in @angular/router@3.4.8. Trying to downgrade the version of @angular/router@3.4.6 will fix the issue.
However, I just want to confirm if this is a issue in 3.4.8?

**Comment by Toxicable** [comment]
What does not working mean? can you look at #14588 and confirm that it's not related if it is then please close as duplicate. If it isn't a duplicate then can you please do a minimal reproduction in plunkr.

**Comment by arrian0511** [comment]
@Toxicable Thank you for your information, yeah it is the same issue, however there is no fix for this yet?

**Comment by DzmitryShylovich** [comment]
@arrian0511 pls close this one. there's no need to have 2 separate issues for the same bug. thx

**Comment by arrian0511** [comment]
reference #14588
