### ISSUE TITLE
passing data to child component angular2 (Data recived from web service not append on child)

### ISSUE THREAD

**Issue by kakul232** [angular/angular#14613]
Checkout the link

http://stackoverflow.com/questions/42359727/passing-data-to-child-component-angular2-data-recived-from-web-service-not-appe

**Comment by DzmitryShylovich** [comment]
Hello, this issue tracker is not suitable for support requests.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
