### ISSUE TITLE
Module not found when using type from .d.ts file

### ISSUE THREAD

**Issue by Draccoz** [angular/angular#14616]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
When assigning a custom type (like Post, or User) to a decorated property (with either ng decorator like `@Input()` or a custom one), where type is declared in `d.ts` file, angular throws an error:
```
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve './types' in '/home/dracco/projects/ng2/src/app'
 @ ./src/app/app.component.ts 11:0-31
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
webpack: Failed to compile.
```

This does ** happen if:
* type is added through generic (like `Array<Post>`) OR
* no decorator is added to property OR
* file with declaration has `.ts` extension instead of `.d.ts`

**Expected behavior**
No error should be thrown. property should have given type.

**Minimal reproduction of the problem with instructions**
1.  Run `ng init` to create a new Angular project.
2.  Create a `d.ts` file in `app` folder
3. Add an exported interface to the `.d.ts` file
4. Import above interface in component file
5. Add a property with decorator and above type (e.g. `@Input() prop: MyType`)
6. Run `ng serve`

**What is the motivation / use case for changing the behavior?**
The default workflow in TypeScript suggests keeping declarations and interfaces in `.d.ts` file. Simple Angular components might not use Observables and still accept data from the host. I am actually surprised nobody mentioned and solved it so far as it is pretty severe (it also happens in `4.0.0-beta.8`).

**Please tell us about your environment:**

* **OS:** linux x64 (Ubuntu 16.10)
* **Angular version:** 2.3.1, 2.2.4, 4.0.0-beta.8
* **Angular CLI version:** 1.0.0-beta.28.3
* **Node (for AoT issues):** 7.5.0
* **NPM:** 4.1.2

**Comment by DzmitryShylovich** [comment]
> Module not found: Error: Can't resolve './types' in '/home/dracco/projects/ng2/src/app'

looks like a typescript error.

pls provide a github repo that demonstrates the issue

**Comment by Draccoz** [comment]
TypeScript throws no errors, especially that the same type can be used in for example method parameter and has no issues, or like mentioned above used within generics.

Repo with faulty code here:
https://github.com/Draccoz/ng2-type-import-issue
Like I described above, it is fresh CLI app + 1 file + 1 property in component.

**Comment by DzmitryShylovich** [comment]
jit or aot? I've just tested in my own project I haven't got any errors.

**Comment by DzmitryShylovich** [comment]
I would say it's a `cli` issue

**Comment by Draccoz** [comment]
And how did you make it work? Did you run `npm start` after installing? Or using global CLI? What node/ts/ng versions you have? I will try those myself.

**Comment by DzmitryShylovich** [comment]
I use custom webpack config.

> What node/ts/ng versions you have?

ng 2.4.8
ts 2.0.10

**Comment by DzmitryShylovich** [comment]
Try to reproduce using one of the webpack starters (for example, https://github.com/AngularClass/angular2-webpack-starter)

And if it's not reproducible there re-open this issue on https://github.com/angular/angular-cli/issues

**Comment by Draccoz** [comment]
Just like you said, it works correctly on webpack starter. Closing this issue and reopening on cli issues. Thanks!
