### ISSUE TITLE
Angular 1 service not able to use in Angular2

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#14618]
I have a LoginInfoService implemented in ng1.

To use this in hybrid angular application as per documentation i have done the following -
1. created app module

```ts
import { NgModule, ElementRef}      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }   from './app.component';
import { UpgradeModule } from '@angular/upgrade/static';
@NgModule({
    imports: [BrowserModule,
        HttpModule,
        JsonpModule,
        UpgradeModule
    ],
    declarations: [...    ],
    providers: [      
        LoginInfoService,
        { provide: 'LoginInfoService', useFactory: (i: any) => i.get('LoginInfoService'), deps: ['$injector'] },
    ],
    entryComponents:[...   ]
    

})
export class AppModule {
    ngDoBootstrap() { /* this is a placeholder to stop the boostrapper from complaining */
    }
}
```

2. created a wrapper ng2 service as below -

```ts
import {Injectable, Inject} from "@angular/core";

@Injectable()
export class LoginInfoService {

    constructor( @Inject("LoginInfoService") public loginInfoService: LoginInfoService) {
        return loginInfoService;
    }
    isDirectvInFocus() {
        return this.loginInfoService.isDirectvInFocus();

    }
    isWirelessInFocus() {
        return this.loginInfoService.isWirelessInFocus();

    }
    getAccountInFocus() {
        return this.loginInfoService.getAccountInFocus();
    }
    getLoginType() {
        return this.loginInfoService.getLoginType();
    }
}
```

3. in main ts

```ts
platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
  const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
  upgrade.bootstrap(document.documentElement, ['myApp']);//this is angular1 module
});
```

And getting the following error -

zone.js:405 Unhandled Promise rejection: No provider for LoginInfoService! ; Zone: <root> ; Task: Promise.then ; Value: Error: No provider for LoginInfoService!

**Comment by vasuneet** [comment]
Any comment on this?

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vasuneet** [comment]
This is bug report as the same service was working perfectly fine using upgradeAdapter. As soon as i switeched to upgradeModule . this issue happens as i relied on added four API - UpgradeModule, UpgradeComponent, downgradeInjectables,downgradeComponent.
I am blocked due to this issue.

**Comment by gkalpak** [comment]
@vasuneet, your code above is either incomplete or wrong (e.g. you never seem to import `LoginInfoService` in `app.module.ts`). I would be happy to investigate if you provide a runnable demo of the issue (you can use [this plnkr][1] as a base). At this point we can't investigate further.

[1]: http://plnkr.co/edit/BXA3Onj8CkbmfuDKXu1N?p=preview

**Comment by vasuneet** [comment]
please check the following plnkr -

http://plnkr.co/edit/Yz8NnrTC1oWcQu0QIVpo?p=preview

In this plunkr ,  i created a service in ng1 and trying to use in DemoComponent by using wrapper class.

**Comment by gkalpak** [comment]
@vasuneet: In your plnkr, you are using incorrect injection tokens for the upgraded service (i.e. you are using `@Inject('services')` and `i.get('services')` instead of the correct `'LoginInfoService'`). If you use the correct token, [it works as expected][1].

Closing as there doesn't seem to be any issue, but feel free to continue the discussion below and provide an actual reproduction of the issue.

[1]: http://plnkr.co/edit/hnDpi2xWhwQAsoZj3Maj?p=preview

**Comment by vasuneet** [comment]
please check now.

**Comment by vasuneet** [comment]
thanks. its resolved.

**Comment by vasuneet** [comment]
Hi however plunker is worked but the same solution is not working in local system and getting the below error -
zone.js:344 Unhandled Promise rejection: Cannot read property 'get' of undefined ;

I debugged and found error is - injector is not available in service factory in the following code

    import { LoginInfoService } from './ng2/login/services/LoginInfoService';

    export function LoginInfoServiceFactory(i: any) {
        return i.get('LoginInfoService'); ////////This is the error point
    }
    export const LoginInfoServiceProvider = {
        provide: LoginInfoService,
        useFactory: LoginInfoServiceFactory,
        deps: ['$injector']
    };

Any idea how injector cannot be available in this .

**Comment by gkalpak** [comment]
No idea. We need the whole picture to investigate why it might not be available (e.g. how are you using `LoginInfoServiceProvider`, what is included in each module, how are the modules "wired together" etc).

**Comment by vasuneet** [comment]
Just want to know how this injector is provided through ng2 here in factory class.

**Comment by gkalpak** [comment]
`$injector` is made available to Angular's injector in an AngularJS `run` block (you can find the relevant code [here][1]).

[1]: https://github.com/angular/angular/blob/6b7937f112186c779916ad0599ce92991744219f/modules/%40angular/upgrade/src/static/upgrade_module.ts#L193-L200

**Comment by vasuneet** [comment]
Ok. So now i got the idea.
I am getting this code called before ng1 bootstrapped. Consider the following code snippet -
platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
    const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
    upgrade.bootstrap(document.body, ['myATTApp'], { strictDi: true });
});

Here i am bootstrapping AppModule first before bootstrapping ng1 module as per documentation.
And in AppModule i have LoginServiceInfoProvider.

In your plunker example we are using DemoCompnent after downgrading it. and DemoComponent is using the upgraded service. So as we are using DemoComponent in ng1 context . Service is also upgrading from ng1 context. Injector would be available.

In my case, I am using ng2 component and trying to use the upgraded service before ng1 bootstrap. So injector would not be available.

**Comment by gkalpak** [comment]
I'm afraid not. The mental model with `ngUpgrade` is that AngularJS (1.x) is the outermost part and in charge of the rest of the hybrid app. This essentially means that any Angular component must be downgraded and wrapped in this outer AngularJS "shell".

The problem with your usecase, is that you need both the Angular part and the AngularJS part initialized (e.g. both injectors created and available to one another), before you can go on and start instantiating components/services etc.

(There are some thoughts to remove this restriction, but nothing concrete yet. cc @petebacondarwin)

**Comment by vasuneet** [comment]
So i have done the following changes. still same erro -

1. I have downgraded the AppComponent (ng2 main app)
2. Made entry of AppComponent in entryComponent


Details are as below 
I have a LoginInfoService implemented in ng1.

To use this in hybrid angular application as per documentation i have done the following -

Created ajs-upgraded-providers for LoginInfoServiceProvider -
import { LoginInfoService } from './ng2/login/services/LoginInfoService';

export function LoginInfoServiceFactory(i: any) {
return i.get('LoginInfoService');
}
export const LoginInfoServiceProvider = {
provide: LoginInfoService,
useFactory: LoginInfoServiceFactory,
deps: ['$injector']
};

created app module
import { NgModule, ElementRef} from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { UpgradeModule } from '@angular/upgrade/static';
@NgModule({
imports: [BrowserModule,
HttpModule,
JsonpModule,
UpgradeModule
],
declarations: [... ],
providers: [
LoginInfoServiceProvider
],
entryComponents:[AppComponent ]
})
export class AppModule {
ngDoBootstrap() { /* this is a placeholder to stop the boostrapper from complaining */
}
}

created a wrapper ng2 service as below -

import {Injectable, Inject} from "@angular/core";

@Injectable()
export class LoginInfoService {

 constructor( @Inject("LoginInfoService") public loginInfoService: LoginInfoService) {
     return loginInfoService;
 }
 isDirectvInFocus() {
     return this.loginInfoService.isDirectvInFocus();

 }
 isWirelessInFocus() {
     return this.loginInfoService.isWirelessInFocus();

 }
 getAccountInFocus() {
     return this.loginInfoService.getAccountInFocus();
 }
 getLoginType() {
     return this.loginInfoService.getLoginType();
 }
}

in main ts

    angular.module('myATTApp')
       .directive('myApp',
        downgradeComponent({ component: AppComponent }));


    platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
    const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
    upgrade.bootstrap(document.documentElement, ['myApp']);//this is angular1 module
    });

And getting the following error -

    zone.js:344 Unhandled Promise rejection: Cannot read property 'get' of undefined ; Zone: <root> ;     Task: Promise.then ; Value: TypeError: Cannot read property 'get' of undefined(…) TypeError: Cannot read property 'get' of undefined
    at LoginInfoServiceFactory (http://localhost:3000/ajs-upgraded-providers.js:5:17)

**Comment by vasuneet** [comment]
Note : - I am not upgrading any component as mentioned here - http://plnkr.co/edit/hnDpi2xWhwQAsoZj3Maj?p=preview

**Comment by petebacondarwin** [comment]
@vasuneet - can you recreate the error on a fork of the Plunker that you posted?
