### ISSUE TITLE
New change detection strategy onPushStrict

### ISSUE THREAD

**Issue by MickL** [angular/angular#14628]
**I'm submitting a ...**
```
[ ] bug report
[X] feature request
[ ] support request
```

**Current behavior**
We only have two change detection strategies: `Default` and `OnPush`

- OnPush doesn't trigger change detection if no input changed
- If something changed inside of this component change detection runs for whole application
- To prevent this we have to set OnPush for EVERY other component

![current](https://cloud.githubusercontent.com/assets/5103210/23215034/33a19444-f911-11e6-9718-416c422f0cca.jpg)

**Expected behavior**
New strategy 'onPushStrict' (working title) OR default behavior if component has not output's:

- Don't trigger change detection if no input changed (same as OnPush)
- Trigger change detection only for this component and its child's
- Changes will not affect parent(s) at all

![expected](https://cloud.githubusercontent.com/assets/5103210/23215225/e887ca9a-f911-11e6-9ae3-892c47534769.jpg)

**What is the motivation / use case for changing the behavior?**
Lets say we have a component which is a "closed system": It gets input and any changes inside of the component will ONLY affect this component. 

For example a component which has no input at all. It gets an image of a webcam from the server and displays it. There would be no need to run change detection for the whole application.

Lets make this example more problematic: The component subscribes to document event "mousemove" and does something with the event. EVERY mousemove (alot per second!) will then trigger change detection for the whole app if none of the outside components use OnPush.

**Angular version:** 
2.4.X or 4.x.x

**Comment by MickL** [comment]
I want to show the second example here as a motivation. 

Lets say we want to do a simple image that follows the mouse-pointer(like back in the old days). The Angular-way would look something like this: 

```
@Component({
  styles: [`img { position: fixed; }`],
  template: `<img [style.left]="mouseX + 'px'" [style.top]="mouseY + 'px'" src="...">`
})
export class MyComponent {
  mouseX = 0;
  mouseY = 0;

  constructor() {}

  ngOnInit() {
    Observable.fromEvent(document, 'mousemove').subscribe((ev) => this.onMouseMove(ev));
  }

  onMouseMove(ev) {
    this.mouseX = ev.clientX;
    this.mouseY = ev.clientY;
  }
}
```

Which works fine but triggers change detection a few times per seconds. If there are complex components that get checked, too, it starts lagging.

So we would end up subscribing the observable out of zone and update manually with basic JavaScript (of course we could use jQuery, too):

```
@Component({
  styles: [`div { position: fixed; }`],
  template: `<img id="myImage" src="#">`
})
export class MyComponent {
  mouseX = 0;
  mouseY = 0;
  el = document.getElementById('myImage');

  constructor(private ngZone: NgZone) {}

  ngOnInit() {
    this.ngZone.runOutsideAngular(() => {
      Observable.fromEvent(document, 'mousemove').subscribe((ev) => this.onMouseMove(ev));
    });
  }

  onMouseMove(ev) {
    this.el.style.left = ev.clientX;
    this.el.style.top  = ev.clientY;
  }
}
```

**Comment by DzmitryShylovich** [comment]
I wouldn't expect it to be implemented in the near future as there're more priority features/bugs.

I would recommend you to play with `NgZone.runOutsideAngular/runGuarded` and `ChangeDetectorRef.detach/reattach` methods.

**Comment by MickL** [comment]
Yes i did but, as in the example above, everything leads back to manual dom manipulation with plain JS or jQuery which doesn't seem to whats Angular been made for.

**Comment by MickL** [comment]
As i checked out `ChangeDetectorRef` i was sure i found the needed behavior. For `detach()` the documentation says `This can also be used in combination with {@link ChangeDetectorRef#detectChanges} to implement local change detection checks` which is not true:

- DOM for this component is not updated when detached (ok)
- Changes will still trigger change detection for full application with all components
- using `detectChanges()` later will trigger cd for full app once again (documentation says local cd)

**Comment by MickL** [comment]
Maybe a new strategy is not needed if Angular is "smart enough" (dont get me wrong it is smart already!) to see:

"There are changes in X. X has no output so i start change detection on this node instead of root node"

Personally i would like to see this default behavior more than a new strategy. Would increase performance in all Angular apps immediately without the need to change code.

**Comment by ClementVidal** [comment]
I find this interesting, 
How can Angular know from which component change detection should start ?
Does zone.js know which component trigger a particular asynchrone event ?

**Comment by DzmitryShylovich** [comment]
> Does zone.js know which component trigger a particular asynchrone event ?

zone.js doesn't know anything about angular :)

**Comment by zoechi** [comment]
> This leads us back to manual dom manipulation

There is no need to use manual DOM manipulation. Just call `cdRef.markForCheck()` 

```
  ngOnInit() {
    this.ngZone.runOutsideAngular(() => {
      Observable.fromEvent(document, 'mousemove').subscribe((ev) => this.onMouseMove(ev));
    });
  }
 onMouseMove(ev) {
    this.mouseX = ev.clientX;
    this.mouseY = ev.clientY;
    this.cdRef.markForCheck();
  }
```

**Comment by MickL** [comment]
This would trigger change detection for the whole app few times per second again? Exactly what i wanted to prevent.

**Comment by zoechi** [comment]
@MickL not AFAIK. `ApplicationRef.tick()` is for the whole app.

**Comment by crysislinux** [comment]
> There is no need to use manual DOM manipulation. Just call cdRef.markForCheck()

@zoechi  Are you sure that works? I tried but have to wrap "this.mouseX = xxx ..." expressions in ngZone.run, or the UI won't update even markForCheck is called.

**Comment by illiano** [comment]
sometimes you just need to rerender the current components and sub-components without to recheck the hole virtualdom. 
Maybe it is possible to include a new change detection strategy like @MickL introduced with excluding the components in a separate zone. I can try to include it, if the feature will be accepted.

I have created an example where a simple clock/counter will check each second the hole tree for changes. It would be nice, to have a good way, where you can use angular for rendering the view without rechecking the hole tree.

for the example: https://plnkr.co/edit/pthiNUdskQRAP2Oy1fE9

**Comment by MickL** [comment]
Basically my "workaround" is to use onPush as much as possible. This is not always possible if you don't want to use a bunch of `markForCheck()`. And dare you not forgetting `markForCheck()` somwhere! 

Btw. I had 2 projects already containing a simple timer `setInterval(() => {this.timer ++}, 1000)` which slowed down the performance so much that i had to exclude the component vom ngZone and use vanilla javascript instead.

**Comment by illiano** [comment]
This is what i am thinking to do as well. I am thiniking about rewriting the component in vanilla js or vue and include it later as decoupled component in the angular App. If someone knows a good solution please let me know.
 
I hope this feature request will approved and implemented soon.

**Comment by anjmao** [comment]
@MickL Totally agree with you.  I also posted similar proposal here https://github.com/angular/angular/issues/22646.

1) If I understand correctly it is not possible to implement this easily because of current architecture limitations. Here https://github.com/angular/angular/blob/master/packages/core/src/application_ref.ts#L418 application tick happens for every event which happened inside zone. This means that event if you have your component detached from cd tree zone will catch events from this component( except you use custom event management and runOutsideZone) and trigger change detection again.

2) I was thinking to implement OnPushStrict by checking which component triggered dom event but there is not such information on NgZone.

3) I'm investigating possible changes to dom linker so it can pass more information to zone when maybe it could be implement something like this:

In ApplicationRef.ts
```ts
_zone.onMicrotaskEmpty.subscribe((event) => {
     if (event.component.changeDetection === ChangeDetectionStrategy.OnPushStrict) {
           this._views.find((v) => this.event.component).detectChanges();
     } else {
           this._views.forEach((view) => view.detectChanges());
     }
})
```

**Comment by mhagnumdw** [comment]
@crysislinux 
> > There is no need to use manual DOM manipulation. Just call cdRef.markForCheck()
> 
> @zoechi Are you sure that works? I tried but have to wrap "this.mouseX = xxx ..." expressions in ngZone.run, or the UI won't update even markForCheck is called.

try to use `cdRef.detectChanges()` instead of `cdRef.markForCheck()`. This worked for me.
