### ISSUE TITLE
feat(language service): relax component/directive error checks when defined in spec

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14622]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request 
```

**Current behavior**
How do I suppress errors/warnings for test helper components in unit tests.

Given a `spec.ts` with the following test component:

```
@Component({
  selector: 'aio-foo',
  template: `Foo Component`
}) 
class FooComponent { }
```
The language service redlines the template contents and complains “_No Directive Annotation found on FooComponent_”

I can cure that by `exporting` the class (not obvious) but then it redlines the `@Component` and complains that I haven’t declared it in an `NgModule`.

I tried creating one of those within the file … but couldn’t clear the error.  Even if I can rearrange the code to avoid the error, the problem isn't obvious and the friction is unnecessary. 

Chuck and I discussed possible solutions on Feb 12

>Chuck: I report what AOT would report but, you are right, that is not applicable for test classes. What would you recommend as a trigger? Should I detect use of Jasmine? Look for an attribute such as `testing: true`? Look for a comment? Which would be the least impactful?
>
>Ward: We might mocha or something else so testing for Jasmine would be brittle. Can you check for the presence of the `TestBed`?
>
>Chuck: Yes. Sounds like a plan.

**Expected behavior**

Language service shouldn't complain about components/directives defined within the spec file. While these would be errors under AOT, spec files aren't compiled under AOT.

I love the support that the language service offers. But if the solution required disabling ALL error checking and intellisense for directives defined within specs, that would be OK.  We'd just have to document that.

**Minimal reproduction of the problem with instructions**

See above. For an example, see https://github.com/angular/angular/blob/master/aio/src/app/sidenav/sidenav.component.spec.ts#L15

**Please tell us about your environment:**
* **IDE:** VSCode on OS/X
* **Angular version:** 2.4.x
* **Browser:** All
* **Language:** all TypeScript

**Comment by gsziszi** [comment]
I'm using Webstorm 2019.1 and the problem comes again - it worked fine without error notification in the previous version, but error shown in test files for mock classess. Please check!

**Comment by kyliau** [comment]
This has been fixed in https://github.com/angular/angular/pull/34115
