### ISSUE TITLE
changeDetection should be available for Directive's, too

### ISSUE THREAD

**Issue by MickL** [angular/angular#14627]
**I'm submitting a ...**
```
[ ] bug report
[X] feature request
[ ] support request
```

**Current behavior**
@Directive() does not have changeDetection attribute. It gets checked always even if no input changed.

**Expected behavior**
Same ChangeDetectionStrategy's available for Components should be available for Directives, too.

**What is the motivation / use case for changing the behavior?**
Lets say we want create an image-zoom-directive which displays a zoomed image on mouseover. This directive (and maybe created child components) get checked even if there was no change in input.

**Angular version:** 
2.4.X or 4.x.x

**Comment by DzmitryShylovich** [comment]
As a work around you can use the component with attribute selector and empty template

**Comment by DzmitryShylovich** [comment]
> 2.4.X or 4.x.x

it's a new feature so it will never be in 2.x

**Comment by vicb** [comment]
Nodes of the CS tree are components. Directives in OnPush component only get checked when their parent cmp is checked.
