### ISSUE TITLE
Angular 4.0.0-beta.8 - ES5 JavaScript with DSL - rxjs references undefined  

### ISSUE THREAD

**Issue by uparlange** [angular/angular#14626]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Application don't launch with Angular 4.0.0-beta.8 - ES5 JavaScript with DSL.

Problem to start application
Unhandled Promise rejection: Cannot read property 'merge' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'merge' of undefined

Problem to launch module with canActivate / canDeactivate option
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property '$$observable' of undefined
TypeError: Cannot read property '$$observable' of undefined

**Expected behavior**
Application should work normaly

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/tPtY1a31CnFqhNbzVViU?p=preview

Problem to start application --> corrected by adding this two lines in index.html
window.rxjs_observable_merge = Rx.Observable;
window.rxjs_operator_share = Rx.Observable.prototype;

Problem to launch module with canActivate / canDeactivate option --> corrected by adding this two lines in index.html
Rx.Symbol.$$observable = Rx.Symbol.observable;
window.rxjs_symbol_observable = Rx.Symbol;

**What is the motivation / use case for changing the behavior?**
Having application launch and work normaly

**Please tell us about your environment:**
Not important !

* **Angular version:** 4.0.0-beta.8 and earlier (not sure !)

* **Browser:** Chrome and all others
 
* **Language:** ES5

* **Node (for AoT issues):** `node --version` = Not concerned

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/14603 / https://github.com/angular/angular/issues/14298

**Comment by uparlange** [comment]
Waouh fast answer !
Sorry for duplicates.

**Comment by DzmitryShylovich** [comment]
@uparlange close?

**Comment by uparlange** [comment]
Ok closed.
Do you know if this bugs will be corrected in next beta version ?

**Comment by DzmitryShylovich** [comment]
don't think so. there're more priority tasks

**Comment by uparlange** [comment]
It seems to be only a config problem so not complicated to correct... 
It is embarrassing especially since it is not the first time that this type of problem happens :-(

**Comment by DzmitryShylovich** [comment]
> It seems to be only a config problem so not complicated to correct

prs are welcomed :)
I use ts version with webpack and don't have any issues
