### ISSUE TITLE
Query does not support differentiating between direct and descendant children.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1462]
The tests for this only show direct children.

```javascript
constructor(@Query(Dependency) list:queryList<Dependency>)
```

The tests should show what happens when the `Dependency` is not direct child.

Also we should have the non-direct child us case.

```javascript
constructor(@QueryDescendants(Dependency) list:queryList<Dependency>)
```

- [x] Add tests to show that you can not inject non-direct child descendants using the `Query`
- [x] Create new annotation `QueryDescendents` which extends `Query`
- [x] Add tests for `QueryDescendents`.

**Comment by matanlurey** [comment]
#1412 would be interested in this.

**Comment by mhevery** [comment]
https://github.com/angular/angular/issues/1935
