### ISSUE TITLE
Provide DOM interface to DOCUMENT on server side

### ISSUE THREAD

**Issue by vikerman** [angular/angular#14638]
This is for the 4.1 timeframe.

Currently the DOCUMENT you get in the browser is an actual 'document', while in the server it is a parse5 Document.

We need to get rid of the DOM Adapter(and salvage only the helper functions) and provide an actual DOM interface to the DOCUMENT returned on the server side (using jsdom?)

This would make the DOCUMENT actually useful without conditional logic on the browser and server.

**Comment by harshes53** [comment]
@vikerman performance wise does `domino` do any improvement in rendering large SSR?
