### ISSUE TITLE
FormControl errors property should be an Observable

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/angular#14639]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Curently the `errors` property of the `FormControl` is an object

**Expected behavior**
It would be better if it was an `Observable` of that object.

**What is the motivation / use case for changing the behavior?**
I wanted to build a directive similar to `ng-messages` from angular 1. My directive would take the FormControl as an `@Input() theControl` and subscribe to changes on its errors:
```ts
this.theControl.errors.subscribe((errors) => {
  // logic to hide or show appropriate error messages
});
```
Because this is not an option, I had to write the following in order to catch events when errors would possibly change:
```ts
Observable.merge(
  this.theControl.valueChanges,
  this.theControl.statusChanges.distinctUntilChanged()
).subscribe(() => {
  // logic to hide or show appropriate error messages
})
```
notice that I have to subscribe to both - `valueChanges` and `statusChanges`. Subscribing just to `valueChanges` might miss asynchronous changes to errors. Similarly, subscribing just to `statusChanges` does not guaranty getting all changes in `errors` value.
Even the solution above might miss some changes to the `errors`.

* **Angular version:** 2.4.8

* **Browser:** all 
* **Language:** all

**Comment by DzmitryShylovich** [comment]
> subscribing just to statusChanges does not guaranty getting all changes in errors value.

pls add a plunkr demonstrating that status and errors are out of sync

**Comment by DmitryEfimenko** [comment]
my mistake. Got confused due to the `status` property. Once I saw it, I thought `statusChanges` will only be triggered when `status` *changes*. Seeing that it changes more often than that I thought it might be a bug, and applied `distinctUntilChanged()` on it.
Docs for `statusChanges` clarified it for me. It is emitted when `status` *re-calculates*.
Conclusion: `statusChanges` does exactly what I need it to do. However, its name is a bit confusing and does not reflect its true purpose.

**Comment by DzmitryShylovich** [comment]
> statusChanges does exactly what I need it to do

then close the issue pls. thx

**Comment by DmitryEfimenko** [comment]
Before closing the issue I was wondering if the Angular team would consider a different name for `statusChanges`. It's a minor thing, and might not be worth a breaking change, but people might get confused in the future.
I'm fine either way.
