### ISSUE TITLE
Child components given incorrect values with Width/Height 100%

### ISSUE THREAD

**Issue by jpmoney** [angular/angular#14636]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using a component that acts as a navigation handler, for example, a component that displays a simple HTML list of navigation links and places a router-outlet below it, all of its child components get the incorrect data for height 100%. I am trying to implement a simple template to have a navigation component and have the children take up the remaining available space. When I run the application the child component is displayed below the navigation component which itself takes up a vertical space of 20px. However the child component, when using a height of 100% is given a height of the full screen 100% and does not take into account the existence of the nav. Because of this the page overflows vertically by 20 pixels. 

**Expected behavior**

I would expect the child component to be positioned below the navigation component and know that 100% of the height would not create overflow. 

**Minimal reproduction of the problem with instructions**

Create a component to act as a simple navigation with a router-outlet. Have the child routes of that router-outlet use a div with height:100%. This will create an overflow and the child div will not take into account the parent div. 

**What is the motivation / use case for changing the behavior?**

I would like to have a general template where the nav is changing the component being displayed in a sort of "content frame" with it actually be able to take up all remaining available height and width without unnecessary overflow.

**Please tell us about your environment:**

Windows, using Angular-CLI, both with and without Angular-Flex

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
pls add a plunkr

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by vqw** [comment]
kill yourself
