### ISSUE TITLE
Angular Reactive Form Controls don't change in response of @Input changes when user hits browser back button

### ISSUE THREAD

**Issue by klikas** [angular/angular#14642]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Maybe I am doing something wrong as I am quite new to Angular2 but I am trying to create an angular form, using Reactive (a.k.a. Model Driven Forms). 

Let's imagine a form, containing keyword and location and a bunch of filters. The form controls may be populated by the user or may be pre-populated using URL parameters (i.e. if keyword parameter exists in the URL, my form field with name "keyword" gets pre-populated with the value of the URL parameter).

When the user types something and they click on search, I push the form values to the url using router.navigate and navigating to the current component, with different queryParams.

I split this form to a top-level component that contains the opening and closing form tags and a child component that expects keyword and location as @Input() parameters.

The top-level component subscribes to the URL changes and updates the properties that get passed as @Inputs to the child component.

The child component, within it's constructor, creates a formGroup, using the input parameters. 

When the input parameters change, I can see the ngOnChanges event firing in the child component but the form control values stay the same, so changes to the @Input() that was used to create the formGroup, don't get mirrored in the formControl values, unless you explicitly do a patchValue or setValue within the ngOnChanges lifestyle hook. 

This creates issues when the user hits the browser's back button, as the url parameters change, which causes the router query parameters subscription to run on the parent component and change the values that are provided as Inputs() to the child component but the form inputs in the UI are not updated to reflect the new URL state unless I manually set the values for the form group.

If I create the formGroups in my parent component and pass the whole FormGroup as @Input() in my child component, everything works as expected.

If I don't use Reactive forms and have just Template Driven Forms, everything works as expected. 

**Expected behavior**
In a scenario like the above, I would expect the form controls to reflect the values that are shown in the URL.

**Minimal reproduction of the problem with instructions**

To reproduce, I used the quickstart seed and created a simple child component with a couple of input tags inside a form. I used a router so that my parent component can route to itself and  

**What is the motivation / use case for changing the behavior?**
The desire to split a large reactive form into smaller subcomponents and keep the logic of looking at URL parameters just in a top-level component that provides subcomponents just with the values they need as @Input parameters

**Please tell us about your environment:**
Windows 10, Sublime text, npm, npm lite-server

* **Angular version:** 2.0.X
Angular v 2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 56.0.2924.87 (May happen in other browsers as well)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript v 2.0.10 with ES6

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
pls add a plunkr

**Comment by klikas** [comment]
Hi @DzmitryShylovich, not sure if I can add a plunkr to replicate the exact issue as I need to play with the URL and change it. Could I create a sample application and share a link to it in my google drive for example? Would this be acceptable?

**Comment by DzmitryShylovich** [comment]
sure, you can add a link to a github repo

**Comment by FabioAparicio** [comment]
@klikas how are you binding the value to the form control? AFAIK Model driven forms are updated imperatively, or by the view itself (value accessors), a route change means you have to update them imperatively either with `patchValue` or `setValue` as you mentioned, however you should do it on a route listener instead of `ngOnChanges`.

Be advised, im still on rc4  (yep.), I might be wrong.

**Comment by klikas** [comment]
@FabioAparicio I am now updating the form values imperatively, inside ngOnChanges and it seems to be working. I also patch the values on route changes.

This item could probably be closed as I think I misunderstood how model-driven forms are supposed to work and it probably is not a bug on Angular's side.

**Comment by DzmitryShylovich** [comment]
@klikas you can lose it yourself
