### ISSUE TITLE
Improve error message for NgModule import cycles (e.g. A imports B which imports A)

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#14649]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Throws `RangeError: Maximum call stack size exceeded`

**Expected behavior**
Should throw a meaningful error message

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/xYJdkgfXvxn7X1svZvRY?p=preview

**Comment by dylhunn** [comment]
Error messages have improved since 2017, and we now have standalone. Closing as likely obsolete.
