### ISSUE TITLE
fix: better error messages for NgFor

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#14641]
**I'm submitting a ...**  (check one with "x")

[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request

**Current behavior**
While there have been a lot of improvements in the error messages space in Angular, it turns out that there's one case left that can causes many hours of debugging, because the error message is confusing.

When forgetting the `let` keyword in `NgFor`'s micro syntax, that error message points the developer in a wrong direction. **Basically, doing this**:

```
<ANY *ngFor="item of items"></ANY>
```

Throws this error:

```
Can't bind to 'ngFor' since it isn't a known property of 'ANY'.
1. If 'ANY' is an Angular component and it has 'ngFor' input, then verify that it is part of this module.
2. If 'ANY' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
```

This error messages usually occurs when one forgets to add/export a directive/component (in this case `NgFor`), but the actually issue is that the developer forgot the `let` keyword in the micro syntax.

Unfortunately this caused me once 1.5 hours of debugging and wondering why Angular thinks I haven't declared `NgFor` anywhere, while it is in fact properly setup.

I'm seeing more and more people running into this, so I thought it's worth bringing up.

**Expected behavior**
It would be cool if we can throw a more specific error message, or maybe extend the existing one to tell the developer that she needs to double-check the micro syntax.

**Plunker for reproduction

https://plnkr.co/edit/SAI2cYUjuiVXcg4sL8vz?p=preview (check the console)

* **Angular version:** 2.x.

**Comment by DzmitryShylovich** [comment]
pls add a plunkr

**Comment by PascalPrecht** [comment]
@DzmitryShylovich added to the description.

**Comment by DzmitryShylovich** [comment]
@vicb is `item of items` a valid expression? I'm trying to figure out the right place for the fix. I think `Parser` should throw

**Comment by BrunoViera** [comment]
Hello! some news about it? I have the same error

**Comment by Toxicable** [comment]
@BrunoViera to fix this change `<ANY *ngFor="item of items"></ANY>` into `<ANY *ngFor="let item of items"></ANY>` the part you were missing was the `let`.
This issue however is about improving the error messages that it throws when this situation does occur

**Comment by eldaromer** [comment]
So I gave at shot at a fix for this. Bear in mind that this is my first time doing something like this so feel free to just shut me down if I'm wrong :) I'm not entirely sure how to link the pull request I made :(

**Comment by Toxicable** [comment]
@eldaromer any PR to Angular should be made in this repo

**Comment by eldaromer** [comment]
@Toxicable sorry, I'll delete the other one and fix it, thank you!

**Comment by doctorstal** [comment]
Same with 'ngIf' directive. You get same message if directive syntax is messed up. 
Plunker: https://plnkr.co/edit/y1R2KaRRnfMFXJH2mCe1

**Comment by Math3v** [comment]
@eldaromer @Toxicable Is this fixed, or can I take a look at it?

**Comment by Toxicable** [comment]
@Math3v it's not fixed, feel free to make a PR for it

**Comment by Math3v** [comment]
@Toxicable PR is in place.

**Comment by jessicajaniuk** [comment]
This issue should now be fixed with a new extended template diagnostic.
