### ISSUE TITLE
NgUpgrade AOT bug introduced in 4.0.0-beta.8

### ISSUE THREAD

**Issue by JamesHenry** [angular/angular#14648]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Source**

```ts
// Source file
import { UpgradeModule } from '@angular/upgrade/static'
```

**AOT Compiled**

```ts
// Example AOT compiled - Angular 4.0.0-beta.7
import * as import5 from '@angular/upgrade/src/static/upgrade_module';

// Example AOT compiled - Angular 4.0.0-beta.8
import * as import4 from '../../../@angular/upgrade/static';
```

This naturally results in the following:

> app.module.ngfactory.ts:12:26: Cannot find module '../../../@angular/upgrade/static'.

I can only imagine something about this PR https://github.com/angular/angular/pull/14509 is not quite right...

**What is the motivation / use case for changing the behavior?**
Bug fix

**Please tell us about your environment:** macOS 10.12.3

* **Angular version:** 4.0.0-beta.8

 
* **Language:** TypeScript 2.2.0 (Current RC)

* **Node (for AoT issues):** `node --version` =   6.9.4

**Comment by gkalpak** [comment]
cc @chuckjaz (in case it is indeed #14509)
I wonder if this only affects `upgrade/static` (and if so why)?

**Comment by chuckjaz** [comment]
We have a regex that decides if the path should be relative or absolute import that is failing. Looking....

**Comment by chuckjaz** [comment]
As a work-around you can change SHALLOW_IMPORT to /^((\w|-)+|(@(\w|-)+(\/(\w|-)+)+))$/ in the compiler-cli bundle.

**Comment by JamesHenry** [comment]
Thanks, @chuckjaz - reverting to 4.0.0-beta.7 works fine for me as a solution for now
