### ISSUE TITLE
Local template variables vs Viewport execution context

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1464]
Following scenario:

```html
<my-component #reference *if="reference.active">
```
This throws an error:

```sh
Uncaught (in promise) ChangeDetectionError {originalException: TypeError: Cannot read property 'active' of undefined, location: "AST", message: "TypeError: Cannot read property 'active' of undefined in [AST]", toString: function}location: "AST"message: "TypeError: Cannot read property 'active' of undefined in [AST]"originalException: TypeError: Cannot read property 'active' of undefined__proto__: ChangeDetectionError
```

Which makes sense once we translated the viewport directive shorthand syntax to it's canonical version:

```html
<template [if]="reference.active">
 <my-component #reference>
 </my-component>
</template>
```

As we can see, what looks actually quite okay in the shorthand syntax, translates to code that won't work that way. We're trying to evaluate an expression that is not available in the current execution context.

Should we "just" document such a scenario and make clear that this doesn't work, or do we wanna find a way to make it (somehow) work, in order to keep it convenient?

**Comment by mhevery** [comment]
This can not work by definition. When `*if` is false there is no `<my-component>` to bind to. This needs to be documented.
