### ISSUE TITLE
Dynamically load Modules?

### ISSUE THREAD

**Issue by seanbotha123** [angular/angular#14640]
**I'm submitting a ...**  (check one with "x")
```
[ X ] feature request
```

Hi guys. 

We are busy building a rather large enterprise application, which has a large array of modules and components. I am sitting with an issue where I need to allow other developers in the company to develop components for this application, without them having to change the code used in the application itself.

An example would be:

> 'Peter' is a developer from another business unit inside the organization needs to build a charting component. We don't want Peter to change the code of the larger application, but instead, he would build and maintain his own 'Module' (these components would be built off a set interface, to allow the hosting application to communicate to the child 'chart' component) that handles all the functionality that he needs in his chart component. Inside of the larger application we would then need to be able to point to this module (through configuration) and load it dynamically.

The main point here is that I need to allow any developer to reference his own module, without my application specifically knowing about the component. I.E. I cannot have it inside my entryComponents or declarations as it needs to be loaded at runtime and should be allowed to change based on the requirements of the business unit using the application. 

I have been looking at the 'SystemJsNgModuleLoader', but I see no way of loading components that aren't directly part of my application.

I am not sure if this is possible and if I have missed something somewhere. Any guidance/advice would be greatly appreciated.

Sean.

**Comment by DzmitryShylovich** [comment]
You can't load particular components dynamically, only a module. You can dynamically load modules using the router or manually using the same technique (SystemJsNgModuleLoader etc). But anyway this issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vicb** [comment]
Not sure what your issue is. When you include a NgModule you don't have to know the components.

**Comment by seanbotha123** [comment]
Hi Victor

The point to my question is that I do not know about the NgModule at all. It has to be external to the program. Somebody else needs to build this and use it on my site without having to import it as a node_module.

They will need to point my program to a location where their code is, which will be configured and saved to the database. When my program loads up (at runtime) it will read this string and then build/render the component from a path instead of having it imported at build time.

I do understand how the NgModule works, but what we need is to 'inject' the module dynamically. The point is to have other developers code their own 'widgets' and use them on the larger application, without having direct references to them and without having to rebuild the entire application every time a dev wants to include a new widget.

The scope that we are looking at is huge, with hundreds of widgets needing to be built. As I have said this is an enterprise app, so we are trying to find the best option of allowing other developers to add widgets. 

I can explain in further detail if you require that.

Thanks
Sean
