### ISSUE TITLE
Angular 2.4.8 TypeError, cannot read property 'Version' of undefined.

### ISSUE THREAD

**Issue by Noctisdark** [angular/angular#14651]
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I recently downloaded angular 2.4.8 via npm, downloaded packages include:
- `@angular/core`.
- `@angular/compiler`.
- `@angular/common`.
- `@angular/platform-browser`.
- `@angular/platform-browser-dynamic`.

I was aiming for a `Hello World` app as a starting point, I'm currently using `Babel` with `latest-preset` to transpile the code back to ES5, `script-loader` to load all necessary scripts and `Webpack` to bundle to whole thing.

I'm getting this runtime error: `index.html:9 Uncaught TypeError: Cannot read property 'Version' of undefined.`

I did some digging and I found out that the error was probably thrown at`@angular/compiler`, `@angular/compiler/bundle/compiler.umd.jd`. this line to be precise:
```javascript
var /** @type {?} */ VERSION = new _angular_core.Version('2.4.8');
```

**Expected behavior**
The build should display hello word instead of `<my-app>Loading...</my-app>`.

**Minimal reproduction of the problem with instructions**
I made a stackoverflow [question](http://stackoverflow.com/questions/42375523/angular-cannot-read-property-version-of-undefined) where I precisely describe my configurations.

**Please tell us about your environment:**
Windows 7, Adobe Brackets, NPM

* **Angular version:** 2.4.8
* **Browser:** [Chrome 56]
Didn't try anyother as this is probably not browser related.

 
* **Language:** [ES6/7]

* **Node (for AoT issues):** `node --version` = v7.3.0

**Comment by DzmitryShylovich** [comment]
pls add a plunkr

**Comment by Noctisdark** [comment]
@DzmitryShylovich, can we skip that part ? I'm not sure if I can use Plunker.

**Comment by DzmitryShylovich** [comment]
we can't do anything without repro

**Comment by Noctisdark** [comment]
@DzmitryShylovich would it be fine to share a Cloud9 workspace ?

**Comment by DzmitryShylovich** [comment]
@Noctisdark 99% it's a config issue. have you tried angular cli instead of your custom build?

**Comment by Noctisdark** [comment]
@DzmitryShylovich, I just tried angular-cli, I'm not really sure where did I go wrong..
Thanks for the assistance :heart:
