### ISSUE TITLE
Router navigation fails in ngOnDestroy lifecycle hook

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#14653]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Calling `router.navigate` from the `ngOnDestroy` hook for a component fails to navigate.

**Expected behavior**
The `router.navigate` call is made successfully

**Minimal reproduction of the problem with instructions**

~~http://plnkr.co/edit/nzOISC?p=info~~

https://stackblitz.com/edit/angular-5z3htl?file=app%2Fapp.component.ts

1. Click on the Product Info link
2. Note that Product Info and Product Summary are displayed
3. Click on the Products link
4. Note that Products and Product Summary are displayed
5. The Product Summary outlet contents should be cleared when navigating a way from Product Info.

The current workaround is to wrap the `router.navigate` in a setTimeout, which will cause the outlets to be cleared properly.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jasonaden** [comment]
@brandonroberts Can you validate this is still broken? It's an old issue. If it's now working, please close this issue.

**Comment by brandonroberts** [comment]
@jasonaden it's still broken. Here is an updated reproduction using stackblitz.

https://stackblitz.com/edit/angular-5z3htl?file=app%2Fapp.component.ts

**Comment by atscott** [comment]
This issue appears to have been resolved in v9 (or earlier). Update stackblitz example is showing the product summary outlet context as cleared: https://stackblitz.com/edit/angular-ivy-cc9xn6?file=src%2Fapp%2Fapp.component.ts
