### ISSUE TITLE
Component reference is not of type NgElement when not a native element

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1465]
Considering this code:

```html
<button (click)="doSomething(foo)"></button>

<my-component #foo></my-component>
```

`foo` reference will **not** end up as `NgElement` when passed to `doSomething()`, whereas native elements do.

Is that a bug? I know that the whole `NgElement` thing will be changed, but what's the reasoning behind that for now?

**Comment by mhevery** [comment]
It should return an `Element` which sounds like it does what it says. `NgElement` is going away.
