### ISSUE TITLE
Create an Angular 2 app inside no Angular project

### ISSUE THREAD

**Issue by crisiiii** [angular/angular#14666]
I've created an Angular 2 app inside a normal javascript project and I need to use some files (.CSS, .JS, etc) outside the Angular app, but if I use the CLI with command `ng serve` it creates the app in the `http://localhost:4200/`, and the app works, but these files outside the angular app they won't be loaded. So I have to deploy the app with `ng build --prod` to get these files and see the real result. But I think this is not the best way as I have to deploy the app for every change in the code.

So, is there any way to manage this situation?

Thanks!

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
