### ISSUE TITLE
ngroute data binding issue

### ISSUE THREAD

**Issue by hiharsh** [angular/angular#14676]
Hi, I am working on my first AngularJs SPA.
I am trying to implement routing for my first AngularJs application. 
My stand alone code without any routing works as expected.  Here is the plnkr link for the working code. 
[](http://plnkr.co/edit/JjMbEXgXYQ42A00Aw6gB)

However the code with routing enabled doesn't work. i.e the traffic.html doesn't accept the text box input + websocket button doesn't work.
Here is the plnkr link.
[http://plnkr.co/edit/WiGz8dwO8yFjl2fk2lY7](url)

I am missing something very simple but important. 
Could someone please help?

**Comment by ericmartinezr** [comment]
Hey there @hiharsh , this repo is for angular2 (or just angular, don't kill me guys :( ). You're looking for https://github.com/angular/angular.js 👍
