### ISSUE TITLE
Add support for pure Dart modules in ng2 build system

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1467]
# Problem

Dart code in core Angular 2 modules cannot be edited and analyzed simultaneously. The code needs to be transpiled and pubspec templates need to be filled in before you can analyze it. That code goes into `dist`, but it's pointless to edit code in `dist` for obvious reasons. Therefore, today, it is not possible to use Dart IDEs with Dart code in any meaningful way.

We currently have Dart transformers and the analyzer plugin that are Dart-only, and coding experience suffers because of this.

# Solution

*tl;dr* introduce a new type of module into ng2 build system that's Dart-only. Such a module can be opened, edited and tested in any IDE and be analyzable by the IDE. Compiler warnings could be caught much earlier without needing any transpilation. During build gulp would only need to copy dart files into dist and rewrite the pubspecs to match the dist file structure.

## Details

- Add a new folder `modules_dart` which contains plain Dart packages conforming to pub folder convention.
- `pubspec.yaml` is a plain pubspec (not a template):
  * `version`: 0.0.0
  * `authors`: blank
  * `homepage`: blank
  * `dependency_overrides`: points to dist/dart/...
- Add a new gulp task `build/packages.pure.dart` that:
  * Copies everything to `dist` as is, excluding:
    - `packages` folders
    - pubspec.yaml
    - pubspec.lock
  * Rewrite `pubspec.yaml` files into `dist`

**Comment by tbosch** [comment]
+1

**Comment by yjbanov** [comment]
Fixed in #1518
