### ISSUE TITLE
Change detection issues in Office add-in after upgrading from 2.0.0 to  2.4.4

### ISSUE THREAD

**Issue by Ibrahim-Islam** [angular/angular#14673]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Have to manually do `this.cd.detectChanges()` to reflect changes in UI.

**Expected behavior**

Did not have to do `this.cd.detectChanges()` to reflect changes.

**Minimal reproduction of the problem with instructions**

```
this.someService.addItemInList({/..../});
setTimeout(() => {
    this.itemChildComponentsQueryList.last.doSomething();
}, 0);
```
The above code as it was running fine in version `2.0.0` but had to be changed as shown below after upgrading to `2.4.4`.
```
this.someService.addItemInList({/..../});
this.cd.detectChanges();
setTimeout(() => {
	let children = this.itemChildComponentsQueryList.toArray(),
		lastIndex = children.length - 1;
    children[lastIndex].doSomething();
}, 0);
```

**Please tell us about your environment:**

OS: Windows 10 64-bit
Package Manager: yarn/npm
HTTP server: IIS Express

* **Angular version:** 2.0.X

2.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE 11 (M-integrity level)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.0

* **Node (for AoT issues):** `node --version` =   
Node 6.9.5

**Comment by DzmitryShylovich** [comment]
pls add a plunkr

**Comment by Ibrahim-Islam** [comment]
@DzmitryShylovich It would not matter. Code runs fine in other browsers and even in outlook's web version but not in Outlook Desktop which is a IE 11 (M-integrity level).

**Comment by DzmitryShylovich** [comment]
Sounds like a zone.js issue. Pls re-open on https://github.com/angular/zone.js/issues

**Comment by DzmitryShylovich** [comment]
@Ibrahim-Islam close this issue pls as it's not directly angular related. thx
