### ISSUE TITLE
Custom Validator / TypeScript 2.0 with strictNullChecks Compilation Error

### ISSUE THREAD

**Issue by daddyman** [angular/angular#14677]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

This was reported against Angular 2.x in ticket #10166 but that was closed with a comment that this would be fixed in Angular 4.x but it is still an issue.

**Current behavior**
In Angular 4.0.0 beta 8 when writing a custom validator and the TypeScript 2.0 strictNullChecks compiler option is enabled, then `null` cannot be returned from a validator. This applies to both a simple validator (like required) or a validator that returns ValidatorFn.

`Type 'null' is not assignable to type '{ [key: string]: any; }'.`

**Expected behavior**
As custom validators require you return null when valid, the ValidatorFn and Validator interface definitions need to allow for null in the return type.
```
export interface Validator {
    validate(c: AbstractControl): {
        [key: string]: any;
    } | null;
}
```
```
export interface ValidatorFn {
    (c: AbstractControl): {
        [key: string]: any;
    } | null;
}
```

It might also be helpful to add a ValidateFnReturn type to specify the return type from the validator:
```
type ValidatorFnReturn { [key: string]: any; } | null;
```
and use that in the Validator and ValidatorFn interfaces and could be used in the validator code as well.

**Minimal reproduction of the problem with instructions**
- Add strictNullChecks: true to tsconfig.json
- Write a custom validator:
```
public static requiredCustom1(control: AbstractControl): { [key: string]: any; } {
	if (!control.value || control.value.length === 0) {
		return { required: true };
	}
	return null;   //Compile error when strictNullChecks enabled
}
```

```
public static requiredCustom2(trim: boolean = true): ValidatorFn {
	return (control): { [key: string]: any } => {
   	    if (!control.value || control.value.length === 0) {
		return { required: true };
	    }
   	   return null;   //Compile error when strictNullChecks enabled
	};
}
```

There are compile errors about the validators should not return null. I have a work around (that is ugly) where I make all of my custom validators be the type that returns a `ValidataFn` and make the returned function have an `any` return type,

**What is the motivation / use case for changing the behavior?**
This is needed to have custom validators and be able to use strictNullChecks flag with the TypeScript compiler.

**Please tell us about your environment:**
* Windows 10 and Mac 10.12.3
* **Angular version:** 4.0.0-beta.8
* **Browser:** all
* **Language:** Typescript 2.2.1

**Comment by DzmitryShylovich** [comment]
@daddyman fixed by https://github.com/angular/angular/pull/14679
will be available in the next release

**Comment by kara** [comment]
Looks like we can close this then.

**Comment by DzmitryShylovich** [comment]
@kara yeah, I made a mistake in the commit message and close another issue 😄
