### ISSUE TITLE
Pristine property isn't working in IE11\Edge

### ISSUE THREAD

**Issue by szykov** [angular/angular#14672]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When the first open of page with a form it shouldn't show an error if a field is required and empty. In angular 2 there's a property for that purpose - 'pristine'. Seems it doesn't work in IE11/Edge.

**Expected behavior**
No errors in UI when pristine property is true. Example:
`<span *ngIf="!name.pristine && !name.valid" [ngStyle]="{'color': 'red'}">Name is required.</span>`

* **Angular version:** 
Latest possible. 2.4.8

* **Browser:** 
IE11, Edge.
 
* **Language:** 
TypeScript 2.2.1

Please see plnkr with IE11/Edge - http://plnkr.co/edit/wqTpopzxUSjEAkALsHgA?p=preview

**Comment by DzmitryShylovich** [comment]
it's not material2 repo
https://github.com/angular/material2/issues/3256

**Comment by szykov** [comment]
My bad, sorry. Removing material2 module from root module solves the issue.
