### ISSUE TITLE
how to pass an ngFor item into a pipe?

### ISSUE THREAD

**Issue by ashleycuk** [angular/angular#14674]
I have this piece of code...

`            <tr *ngFor="let name of measureNames">
                <td>{{name}}</td>
                <td><input class="form-control"></td>
                <ng-container *ngFor="let rating of ratings | groupFilter:{{name}} ">
                    <ng-container *ngFor="let key of rating | keys">
                        <td *ngIf="key=='measureRating'"><input class="form-control" value={{rating[key]}}></td>
                    </ng-container>
                </ng-container>
            </tr>`

I want to pass {{name}} into my groupFilter pipe but get an error:

Exception: Call to Node module failed with error: Error: Template parse errors:
TypeError: Cannot read property 'toUpperCase' of undefined ("{{name}}</td>
<td><input class="form-control"></td>
<ng-container [ERROR ->]*ngFor="let rating of ratings | groupFilter:{{name}} ">

this is my pipe code....
`import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
    name: 'keys'
})

export class KeysPipe implements PipeTransform {

    transform(value, args: string[]): any {
        let keys = [];
        for (let key in value) {
            keys.push(key);
        }
        console.log("Filter KEYS: " + keys);
        return keys;
    }
}`

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
