### ISSUE TITLE
Registering event listeners making huge impacts on performances

### ISSUE THREAD

**Issue by marijanlekic** [angular/angular#14685]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
Similar problem was already reported in ticket #11857.

**Current behavior**
When registering event listeners (using (event), element.addEventListener, Observable.fromEvent(), HostListener or any other way), performances are really bad. For an example if i have 70 tooltips in the component, and each one has attached 4 events ("mousenter", "focusenter"...) it increases time to render that component for 250ms?

**Expected behavior**
Registering event listeners making very small impact on performances.

**Minimal reproduction of the problem with instructions**
Array items contains 100 items (for an example)
```
<div *ngFor="let item of items;">
    <div class="nested" (click)="clickHandler($event)">
        {{item.toString()}}
    </div>
</div>
```

as you see, in this example we will have 100 click event listeners (registered)

**What is the motivation / use case for changing the behavior?**
 Currently my workaround for this is to register listeners out of angular world:
`   
 this.zone.runOutsideAngular(() => {
    element.addEventListener('event',callback});
 `

And then wrap callback function:

`
this.zone.run(() => {callback();});
`

And if needed trigger markForChange() in callback function.

Is there some better way?

**Please tell us about your environment:**
Windows 10 and Mac 10.12.3
Angular version: 2.4.8
Browser: all
Language: Typescript 2.2.1

**Comment by DzmitryShylovich** [comment]
did you try with enabled prod mode and 4.0?

also add a plunkr pls

**Comment by marijanlekic** [comment]
@DzmitryShylovich Yeah, that combination did the trick. Thank you.
