### ISSUE TITLE
build: gulp format fails on windows

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#14680]
running `gulp format` on windows throws
```
Error: EPERM: operation not permitted, open 'D:\Workspace\angular\modules\@angular\core\src\animation_next\dsl.ts'
    at Error (native)
```

cc @mhevery @matsko

**Comment by lazarljubenovic** [comment]
Here's some possible solutions that worked for me in the past on Windows with similar problems on other projects. Clear cache? Disable any AV software? Close any other programs that might be using the files?

**Comment by DzmitryShylovich** [comment]
> Close any other programs that might be using the files?

I tested it with everything closed and still the same error.
It's something with the file content. If I comment it out it works fine.
This is how it looks like in ide http://prntscr.com/ecqrxn :)
