### ISSUE TITLE
The html element name of [ p-dataTable ] must be in lowecase <tagname-lowercase>

### ISSUE THREAD

**Issue by rathordeepak1985** [angular/angular#14696]
Hi 

I am working on angular 2 app and for grid i am using http://www.primefaces.org/primeng/#/datatable/lazy
I am able to load grid on my html template but when I am building the application or compiling it I am getting the error 

`The html element name of [ p-dataTable ] must be in lowecase <tagname-lowercase>`

I am using webpack,tslint.json,polyfills.ts.

I am wondering how no budy faced this issue or do i need to add anything to tslint.json file to suppress the
error since tag name is with dash-case + camelcase

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource ☝️
