### ISSUE TITLE
Angular 2 giving Invalid Argument Exception in Internet Explorer

### ISSUE THREAD

**Issue by sweco-sezeid** [angular/angular#14697]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The bug manifests when there's a div with contenteditable and information is getting saved after editing.
I've tested it on Edge and Chrome where this bug never shows up. But on Internet Explorer I get this little tidbit

```
EXCEPTION: Error in src/page.html:19:180 caused by: Invalid argument.
ORIGINAL EXCEPTION: Invalid argument.
ORIGINAL STACKTRACE:
Error: Invalid argument.
   at DomRenderer.prototype.setText (eval code:3166:71)
   at DebugDomRenderer.prototype.setText (eval code:11447:76)
   at View_App1.prototype.detectChangesInternal (Function code:167:5)
   at AppView.prototype.detectChanges (eval code:12208:13)
   at DebugAppView.prototype.detectChanges (eval code:12355:17)
   at ViewContainer.prototype.detectChangesInNestedViews (eval code:12466:21)
   at View_App0.prototype.detectChangesInternal (Function code:432:3)
   at AppView.prototype.detectChanges (eval code:12208:13)
   at DebugAppView.prototype.detectChanges (eval code:12355:17)
   at AppView.prototype.internalDetectChanges (eval code:12193:17)
   at View_App_Host0.prototype.detectChangesInternal (Function code:27:3)
   at AppView.prototype.detectChanges (eval code:12208:13)
   at DebugAppView.prototype.detectChanges (eval code:12355:17)
SCRIPT5022: Error: Error in src/page.html:19:180 caused by: Invalid argument
File: Subscriber.js, row: 238, column: 13
```

**Expected behavior**

Text is supposed to get updated and no error thrown same as in Edge or Chrome, the moment invalid argument exception appears no other angular 2 work anymore and the app is broken and does not run a summing function anymore.

**Minimal reproduction of the problem with instructions**

Try it with both IE and other browser to compare the result as it works fine in other browsers
So far I've found two ways how to trigger the bug.

1) Instantly selecting a whole div field and changing the number to something else will throw invalid argument and stops calculating the total.
2) Changing a number that's alone, for example, changing "2" to "15" will trigger the bug, but if you first edit "2" to "2,2" and then delete the characters one by one and write "15" it will work fine again and no invalid argument will be thrown.

https://plnkr.co/edit/0706UMhaCl7QzE36pqni

**What is the motivation / use case for changing the behavior?**

Need to be able to support IE for company environment, so therefore making sure it's also working the same on IE, which it doesn't seem to be doing

**Please tell us about your environment:**

Writing in Visual Studio, using the Angular 2 SPA premade setup, using Chrome and sometimes checking the website on IE too.

* **Angular version:** 2.0.X

Current project angular version is 2.0.2, using the latest version does not seem to solve the issue.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome: works as expected,
Edge: works as expected,
IE: Weird behavior and illegal argument exception
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript is at 2.0.10

* **Node (for AoT issues):** `node --version` =   
v7.4.0

**Comment by DzmitryShylovich** [comment]
It's a known bug in IE. I don't think we can do anything about it

**Comment by sweco-sezeid** [comment]
@DzmitryShylovich 

Ahh, I see, will look for some work around then, probably using some stowed away input box till it's needed.

Thanks for the information! :)

**Comment by DzmitryShylovich** [comment]
did you find a workaround?

**Comment by sweco-sezeid** [comment]
I tried to test some different things, but none of them seemed to work reliably sadly :/

Right now just binding click event to cells in table and then calling input field which overlays the cell, have it set to disappear again on blur and update all the value.
