### ISSUE TITLE
Cached http responses

### ISSUE THREAD

**Issue by Geschan** [angular/angular#14699]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I'm looking for a solution to enhance the http service to use cached results to speedup nagivation in my application.
I's my first time working with Observables, so I'm lack of experience to do it myself, but I have an idea how I would expect such a feature could/would work. I still hope it's the right place to post such an idea even if I'm not able to implement it myself yet. But I would give it a try if somebody would lead me in the right direction.

```
this.http.get(`${environment.cloudBase}/items`)
      .cache({cacheHandler: this.cacheHandler, expirationTime: 300000, alwaysCacheFirst: true})
      .map(response => response.json())
```

- `cacheHandler`: CacheHandler should store a global map of called api endpoinds and their last result with a timestamp. 
- `expirationTime`: How long the cached items are valid until the http service is calling for a new result
- `alwaysCacheFirst`: `true`: If the service should always return the cached item first even if it's already expired (if that's the case, the result of the http request should be published to the subscribers as soon as the response is ready) or `false` if it's completely skipping the cache and waits for the api response

I belive such a feature would be a massive improvemt to a lot of applications:

- makes the app faster, as it doesn't always have to wait for the server response to display something
- the navigation in the browser history would not as often lead into calling the api again (I know, I could use a custom RouteReuseStrategy for this, but I find it to unflexible and difficult to handle)
- the traffic would be drastically reduced (depending on the expiration time)
- I believe there would be more advanteges I didn't think of ;)

In my research I didn't really found something that would match these freature request. What I found is this for example, that tries to solve the same problem with a different approach with RxJava:
http://fedepaol.github.io/blog/2016/01/01/cached-rest-requests-with-rxjava/

**Comment by mattlewis92** [comment]
I wrote a library a while back that can do everything you stated apart from expiry times, it might be of some help to you 😄 https://github.com/mattlewis92/angular-async-cache

Angular 1 did have this feature baked in though, I'd imagine there's probably a good reason why it wasn't ported to `@angular/http`, perhaps because caching logic varies so much between apps its impossible to provide an implementation that suits everyones use cases.

**Comment by Geschan** [comment]
Thank you, that looks really interesting.
I'll have a look at it. :)

You're might be right. I would love to hear the reasons so. 
Caching is clearly something a lot of apps would benefit from, so maybe there is an option to make it at least easier to implement such a feature.

**Comment by alxhub** [comment]
@Geschan I'm currently working on an interceptors feature, which would provide a convenient hook for anyone wishing to implement caching.

There are no current plans to provide a built-in cache implementation, though that could change in the future.
