### ISSUE TITLE
ContentChild and ContentChildren empty when projectableNodes passed via createComponent

### ISSUE THREAD

**Issue by salanford** [angular/angular#14693]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://plnkr.co/edit/8trWhknoIgYnVBsJuKPG?p=preview
ContentChild and ContentChildren queries produce empty results when component is created via ViewContainerRef.createComponent and projected content is passed in via the projectableNodes parameter.

**Expected behavior**
ContentChild and ContentChildren queries find matched content nodes just as if the content nodes were statically declared in markup.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/8trWhknoIgYnVBsJuKPG?p=preview

1. Create EmbeddedViewRef from TemplateRef
2. Create component (containing ng-content) via createComponent of ViewContainerRef, passing in rootNodes of the EmbeddedViewRef for the projectableNodes parameter.
3. Try and access projected content node(s) via ContentChild or ContentChildren in ngAfterContentInit of created component. They will be empty.

**What is the motivation / use case for changing the behavior?**
To allow access to child components. 

**Please tell us about your environment:**
Windows 10, Visual Studio Code, IIS Express

* **Angular version:** 2.0.X
2.4.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, Firefox, IE 11, Edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
afaik it's by design. candidates for projection mus be known at compile time.

**Comment by salanford** [comment]
Okay, I just expected that the "projected nodes" would manifest themselves the same as if they were statically defined. Is there a recommended way for a parent to gain access to child components that are projected dynamically? Is it even possible? The use case for me is simply to have access to child components so that I can set some properties. For example I have a scenario where the parent component has an IsActive property and when it gets set to true I want certain child components (which were projected dynamically) to also have their IsActive property set.

**Comment by salanford** [comment]
Sorry, didn't mean to close this just yet. Was hoping to get some feedback/guidance first on how to work around this design "limitation" (for lack of a better word).

**Comment by seckardt** [comment]
@DzmitryShylovich Could you be more specific about why this limitation is in there by design (vs. being a bug) as it's a severe issue/limitation in terms of being able to create dynamic components. It's strange being able to project content into a component and then the component is not able to recognize it.

**Comment by amoscatelli** [comment]
Is there any workaround ?
