### ISSUE TITLE
What is the proper way to access QueryList results

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1469]
Accessing child components with the `Query()` annotation like this:

```js
constructor(@Query(Type) query:Type) {

}
```
Gives us a `QueryList` object that comes with methods to `add()`, `remove()`, ... etc.

The results of the query are located in `query._results`. Since it has an underscore in it's name, I thought it might be rather considered private. But I couldn't find a method `getResults()` or alike.

Is it okay-ish to access `_results` here, or is there a better way to get hold of them?

**Comment by matanlurey** [comment]
`QueryList` isn't meant to be an entirely accessible List interface. It only exposes an `Iterable` interface, e.g. you could iterate through it, and receive updates when it's changed.

**Comment by PascalPrecht** [comment]
@matanlurey I get that.

But since `Query` seems to be the way to go to access a component's children from LightDOM, the question remains.

**Comment by mhevery** [comment]
No `_results` is private. The correct way is to iterate over it is using the ES6 construct.

```
for(var directive of queryList) {
  ...
}
```

**Comment by PascalPrecht** [comment]
@mhevery so if I have something like this:

```html
<tabs>
  <tab></tab>
  <tab></tab>
</tabs>
```

If I want to get hold of all `<tab>` components inside `<tabs>` is the following the way to go?

```js
class Tabs {
  constructor (@Query(Tab): query:Tab) {

    this.tabs = [];

    for (tab of query) {
      this.tabs.push(tab);
    }
  }
}
```

Or do you think in such a case it's better to provide a method for the child component to add itself to the parent component like this:

```js
class Tabs {
  constructor() {
    this.tabs = [];
  }

  addTab(tab) {
    this.tabs.push(tab);
  }
}
```

```js
class Tab {
  constructor (@Parent('Tabs') tabs:Tabs) {
    tabs.addTab(this);
  }
}
```

**Comment by hawaiikaos** [comment]
It seems shortsighted to not have this accessible by index (very frustrating to work with it).

**Comment by webtsofficial** [comment]
In My case it works fine with foreach:

`
queryList.forEach((directive, index) => {
  console.log(index);
   console.log(directive);
})
`
