### ISSUE TITLE
Inconsistent application of HostBindings in parent element when ngIf used on a child element.

### ISSUE THREAD

**Issue by pwpatton** [angular/angular#14708]
**I'm submitting a**
```
[x] bug report
```

**Current behavior**
I'm having a problem with when HostBindings are applied to parent elements when a child element is using a ngIf. If the child element has an ngIf then host binding of it's parents are applied after the ngAfterViewInit of the child element is called. If no ngIf they are applied before. 

**Expected behavior**
Parent element HostBindings are applied before the child element ngAfterViewInit regardless of whether the child element has an ngIf or not.

**Minimal reproduction of the problem with instructions**

See plnkr to duplicate the issue.
http://plnkr.co/edit/jy5oEQNRbQ6VdqqpGJOy?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Operating system:** Window7
* **IDE:** Intellij 2016.3.4
* **package manager:** npm 3.10.10
* **HTTP server:** angular-cli server

* **Angular version:** 2.4.8

* **Browser:** all

 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
you need `ngAfterViewChecked`
http://plnkr.co/edit/MAQSUJtNgtyp9CPMAhuH?p=preview

**Comment by pwpatton** [comment]
That's difficult to rely on because I have to wait until the classes becomes available on the parent element and the first time `ngAfterViewChecked` is called they are not. I need to rely on consistent behavior w/o having to check the state of the parent element because I likely would not know what state to check anyway.

**Comment by pkozlowski-opensource** [comment]
@pwpatton I had a look at your plunker but it kind of hard of make out what is going on here as:
* plunker doesn't run any more;
* there is quite a bit of code in the plunker, and I'm not sure what is expected vs. observed behaviour (nor how I should reproduce bug)

Anyhow, it looks like you are trying to read _DOM_ (`class.buttonsetarea`) from the parent element in your child and _then_ use this DOM value as a model to render your child. By doing so you are trying to use the DOM as a source of truth while the whole point of Angular is to use model (data).

I _think_ that what you are trying to do is to figure out what is your parent type. If so you should just inject your parent(s) and check its type, something along those lines: https://stackblitz.com/edit/angular-8qwwd1?file=src%2Fapp%2Fapp.component.ts

Obviously there is more than one way to go about it and I hope that you can adjust it to your specific use-case. But the principle remains the same - you shouldn't be reading DOM to drive your display. Data model should rule the display.
