### ISSUE TITLE
Pro/Cons using @Query vs. @Parent/@Ancestor

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1470]
Let's say we build a tabs component and have these two components:

```js
class Tabs {

}

class Tab {

}
```
those will later be used like:
```html
<tabs>
  <tab>foo</tab>
</tabs>
```

In order to make this component work, the `Tabs` component needs to be in charge of an internal collection of `Tab`. Now there are two ways to do it.

1) In `Tab` we inject `@Parent()` in order to get hold of the parent component and use it's methods to extend it's internal collection:

```js
class Tab {
  constructor(@Parent() tabs:Tabs) {
    tabs.addTab(this);
  }
}
```
This is pretty much the Angular 1.x way, where we need to ask for a parent directive's controller in order to communicate with it. The downside is that in the `Tabs` constructor, we don't have access to the children.

2) In `Tabs` we can use `Query` annotation to query for `Tab` children like this:

```js
class Tabs {
  constructor(@Query(Tab): query:Tab) {
    // query._results === collection
  }
}
```

This seems to be much more straight forward. Also `Tab` component now doesn't know anything about `Tabs`. 

I still wonder, what is the right way to go here? Are there any downsides I haven't seen yet? Once thing I can think of, is that `Tab` component maybe **should** require a `@Parent` of type `Tabs`. In that case option 1 would be better, since the code would error in case somebody uses `<tab></tab>` without wrapping `<tabs>`

**Comment by matanlurey** [comment]
There a good handful of projects now that use a form of the `@Parent` approach. There are some subtle differences (please someone correct if I'm wrong!):

- `@Parent` can go through the ShadowDOM, `@Query` is *only* for LightDOM.
- `@Query`, when selecting elements in LightDOM, is the preferred method. Is an automatically updating Observable list, and you won't have to manually register/de-register child components

**Comment by PascalPrecht** [comment]
Is there also a way for a component to get hold of children inside it's Shadow DOM?

**Comment by tbosch** [comment]
Also, @Query always gives the right order, even if For changes it...

**Comment by SekibOmazic** [comment]
@matanlurey If a `@Parent` can go through shadow DOM why the `@Ancestor` can't do the same? 
I thought it could until I read following comment:
https://github.com/angular/angular/issues/1216#issuecomment-90755590

**Comment by PascalPrecht** [comment]
@SekibOmazic I think what @matanlurey wanted to say was, `@Parent` and `@Ancestor` **both** only work in the same Shadow DOM and hence are not able to cross shadow boundaries.

The comment you've linked explains that parent dependencies can be injected across shadow boundaries through the dependency injection system.

**Comment by SekibOmazic** [comment]
@PascalPrecht I'm still having problems to understand when and where shadow dom boundaries emerge. Movin' to gitter to get some answers.

**Comment by PascalPrecht** [comment]
@SekibOmazic if you have a component like this;

```html
<my-component></my-component>
```

And the component has it's own template,

```js
@View({
   inline: `<div>Shadow DOM</div>`
});
```

This template is going to be part of the component's shadow dom. What ever happens inside a Shadow DOM is an implementation details and therefore encapsulated. The template inside the Shadow DOM e.g. is not able to communicate to elements that are not in the same Shadow boundary (the same Shadow Root).

That also mean, a component directive that uses `@Parent()` or `@Ancestor()` to get hold of some dependencies, can only access components that are in the same shadow boundary.

Does that make things clear?

**Comment by SekibOmazic** [comment]
@PascalPrecht Thanks.

**Comment by PascalPrecht** [comment]
Since things have been clarified I'll close this one.
