### ISSUE TITLE
[FEATURE REQUEST] Should be able to import raw TypeScript files from npm

### ISSUE THREAD

**Issue by QuantumInformation** [angular/angular#14704]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Try to import npm module with raw ts files like so:

https://github.com/QuantumInformation/angular-finance/blob/master/src/component.ts#L2

ng serve shows error:
```
ERROR in ../src/component.ts
Module not found: Error: Can't resolve 'vanilla-typescript' in '/Users/nikos/WebstormProjects/angular-finance/src'
```

**Expected behavior**
Compiles the external module with no extra steps

**Minimal reproduction of the problem with instructions**
this demo project: https://github.com/QuantumInformation/angular-finance/tree/master/demo

**What is the motivation / use case for changing the behavior?**

We really should be able to use native ts libs. here is a successful example:
https://github.com/quantumjs/solar-popup/blob/master/src/SolarPopup.ts#L2
https://github.com/quantumjs/solar-popup/blob/master/webpack.config.js#L26

**Please tell us about your environment:**
Mac OSX

* **Angular version:** 2.3.1

**Comment by QuantumInformation** [comment]
Main file is ts:

https://github.com/quantumjs/vanilla-typescript/blob/master/package.json#L5

**Comment by DzmitryShylovich** [comment]
Can't reproduce it using a custom webpack build so it's not an angular issue. Pls re-open it on https://github.com/angular/angular-cli/issues

**Comment by QuantumInformation** [comment]
roger that
