### ISSUE TITLE
maxlength directive truncates and doesn't allow user to exceed max

### ISSUE THREAD

**Issue by msosa** [angular/angular#14713]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When typing inside an input with maxlength, the user cannot exceed the maxlength, and will truncate if text pasted in is too long

**Expected behavior**
When typing inside an input with maxlength, the user can exceed the maxlength and will mark the model as invalid.

Here is a plunk:
http://plnkr.co/edit/dZmmZKNspSPHYXCVYYU6?p=preview

**What is the motivation / use case for changing the behavior?**
If the html attribute of maxlength is used, the validator will never be used when typing inside the input.  The model length will never go past what the max length is set to. If the directive is renamed to something other than the html attribute the user will be allowed to exceed the limit and mark the model as invalid.

* **Angular version:** 2.4.8

* **Browser:** [all ]
 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment]
it's intentional to match the html spec. 
if you need something else just create your own validator.

**Comment by msosa** [comment]
I see, okay I was expecting the directive to be usable on an input unhindered. I'll create my own, thank you

**Comment by MartinMa** [comment]
No offense, but the implementation for the maxlength validator seems a little bit redundant. Considering the fact, that the browser limits the user to type in more characters than specified by the `maxlength` attribute, the `validatorFn` never kicks in. Do I miss a use case though?

AngularJS had a directive called `ng-maxlength` to circumvent this dilemma. So, I figured, this could be of some help: [ngMaxLength for Angular 2 / Angular 4](https://gist.github.com/MartinMa/c0bb39afe6dd8164f6194627bba1fbe2). It utilizes the existing `maxlength` validator implementation.

**Comment by jziggas** [comment]
@MartinMa thank you so much for sharing you directive. Just ran into this same issue that caused a couple other features of our app to break during component upgrades as we allow users to exceed maxlength but then showed help text when that occurs.
