### ISSUE TITLE
Angular 2 - webpackJsonp is not defined

### ISSUE THREAD

**Issue by Maksi1994** [angular/angular#14714]
I use commands `ng build --prod` or `ng build --prod --aot` for production my projects after connected file in document index.html -> errors occur:

>   Uncaught ReferenceError: webpackJsonp is not defined
>         at vendor.bundle.js:1

and

> TypeError: Cannot read property 'call' of undefined
>     at r (inline.fc1c1a5….bundle.js:1)
>     at Object.585 (main.caf6b13….bundle.js:11)
>     at r (inline.fc1c1a5….bundle.js:1)
> Previously everything worked fine... thank you in advance

**Comment by DzmitryShylovich** [comment]
pls report cli issues on https://github.com/angular/angular-cli/issues

**Comment by IgorMinar** [comment]
yeah. @Maksi1994 can you please file a bug against the cli project? Also you no longer need `--aot` because it's the default when you specify `--prod`
