### ISSUE TITLE
Decorator to inject services from template owner scope only

### ISSUE THREAD

**Issue by kemsky** [angular/angular#14710]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
//Parent
template: <div> <child></child> </div>
provide: [Service] //this is optional provider

//Child
template: <div> <component></component> </div>
provide: [Service] //this is optional provider
constructor(@Optional() service:Service) {}

//Component
template: <p>OK</p>
constructor(@Optional() service:Service) {}
```
It is only possible to specify `@Self` (component itself) or `@Host` (host component) to limit search for services. There is no way to prevent `Component` from injecting `Service` from `Parent` if `Child` provider is empty. 

**Expected behavior**
I suggest to add `@Parent` (whatever name you like) decorator, which will limit search to template owner, in this case `Child` will be limited to `Parent`, `Component` will be limited to `Child`.

```
//Component
template: <p>OK</p>
constructor(@Optional() @Parent() service:Service) {}
```
**What is the motivation / use case for changing the behavior?**
For example, if you repeatedly use pattern like Toolbar + Table you may want to connect this two components using additional service, however it gets complicated when components are nested, child components can pickup wrong service from parent.

* **Angular version:** 2.4.8

* **Browser:** [all]
 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment]
> child components can pickup wrong service from parent.

pls add a plunkr

**Comment by kemsky** [comment]
This is pretty obvious, see https://plnkr.co/edit/LmuudMQ1gPVR1Rpwt2i3?p=preview

**Comment by DzmitryShylovich** [comment]
`Host`? https://plnkr.co/edit/d3Yd58uaFmM8YPNngqu6?p=preview
what is the expected behavior?

**Comment by kemsky** [comment]
`@Host` will exclude `Child` service if it was provided. `@Self` and `@Host` are both too low level (node level actually).

`Service` should only be injected if it is provided by owner (nearest parent) component. `Parent` is direct owner of `Child`, `Child` is direct owner of `Component`. Currently there is not way to stop service inheritance, only override with `{provide: Service, useValue: null}`.
