### ISSUE TITLE
Single-file bundles not available in npm

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#1471]
I've just checked the latest `2.0.0-alpha.20` and the single-file bundles (ex.: `./dist/build/angular2.dev.js`) are not available in npm.

We should push them so people depending on ng2 in their apps are not obliged to bundle those files themselves.

**Comment by swirlycheetah** [comment]
I don't want to just +1 this but I feel it's one of the major barriers to entry for people wanting to give angular2 a try. If you're building a file that people can just drop into their page then it should definitely be published to npm as an option for people to use.

**Comment by pkozlowski-opensource** [comment]
@swirlycheetah if you are just after a dropping a link in the script tag, you can use those files published here: https://code.angularjs.org/2.0.0-alpha.20/

But yeh, we need npm as well

**Comment by swirlycheetah** [comment]
Great, good to know! Thanks @pkozlowski-opensource.

**Comment by mhevery** [comment]
obsolete
