### ISSUE TITLE
ng-xi18n should include some contextual info in the .xlf file

### ISSUE THREAD

**Issue by OndraZizka** [angular/angular#14725]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
The ng-xi18n tool generates the translation file based on what it finds in the templates' i18n attribute, see [here](https://angular.io/docs/ts/latest/cookbook/i18n.html).

The generated file doesn't contain the context in which the string was found. To give that context, the template must have an explanatory text in the i18n attribute. That is quite a lot of extra content, which makes the template less readable and maintainable. Besides, just to wriite that text takes time.

The tool could include some context automatically:
1) The content of the nearest h1-h6 predecessor. The idea is that these contain what the current page, section or component is. For instace:

    `<div> <h3>Server error</h3> <div>...</div> <button i18n>Dismiss</button> </div>`

Here, the "Dismiss" text would be accompanied by `nearestHeading="Server error"`

2) The full path CSS selector. The idea is that the path will most likely contain identifier and classes that can give a hint what the current text is. For instance:

    `<div> <h3>Server error</h3> <div>...</div> <button i18n>Dismiss</button> </div>`

Here, the "Dismiss" text would be accompanied by `cssSelector="div > button"`, which would be quite useful hint that it is a label of a button.

3) The file name. The "Dismiss" would be accompanied by `file="server-error-modal-dialog.component.html"`.
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Linux, IDEA, Yarn, WebPack, WildFly

* **Angular version:** 2.4.7

* **Browser:** [N/A]

 
* **Language:** [all]

**Comment by vicb** [comment]
will be fixed by adding a ref to the source in https://github.com/angular/angular/pull/14705
