### ISSUE TITLE
CSSClass decorator directive executes on static class attributes 

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1472]
I have a native button:

```html
<button [class]="{ 'active': expr }">Click me</button>
```

It uses `CSSClass` decorator directive to set a class conditionally. When executing this code, I get the following error:

```sh
Error: Cannot find a pipe for type 'keyValDiff'
```

Any pointers where I get pipes from and what I need to do with them?

**Comment by pkozlowski-opensource** [comment]
@PascalPrecht seems to be working fine for me in 2.0.0-alpha.20:
http://plnkr.co/edit/NAN1Q89S73ljEEG1TCX2?p=preview

**Comment by PascalPrecht** [comment]
Seems like `CSSClass` selector doesn't work correctly. As you can see here: http://plnkr.co/edit/4qJgKzOSigfUyObSZsYy?p=preview

I is executed even for just static classes.

**Comment by pkozlowski-opensource** [comment]
Oh, right, I see, thnx for narrowing this down!

**Comment by PascalPrecht** [comment]
@pkozlowski-opensource if you can give me any pointers, I can try to fix it.

**Comment by pkozlowski-opensource** [comment]
@PascalPrecht I believe that it is hard to fix it properly right now due to #1506. Will get back to you when all the required elements for this fix are in place.

**Comment by pkozlowski-opensource** [comment]
@PascalPrecht so I was chatting with @vsavkin yesterday and there are some refactorings pending that will change how property bindings are transformed in directives. There is not much point in solving things now, so let's wait till the mentioned refactoring is done.

**Comment by PascalPrecht** [comment]
Alright, thank you for keeping me in the loop.

**Comment by pkozlowski-opensource** [comment]
@mhevery shell we rename [the existing class directive]() to `ng-class` as it was done for `ng-if`, `ng-for` etc.? This would solve this particular issue (there are other ways of solving this, of course!)

**Comment by mhevery** [comment]
@pkozlowski-opensource I don't think we should rename as the goal is 
`<div [class]="exp">` `<div [class.foo]="exp">` be consistent.

**Comment by mhevery** [comment]
I think this is a dup of #2025
