### ISSUE TITLE
4.0.0-Rc.1 AnimationsModule not found / exported in @angular/animations

### ISSUE THREAD

**Issue by dharders** [angular/angular#14728]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Followed changelog instructions to upgrade to 4.0.0-rc.1 with the extra step of including the new animations package.
>>If you rely on Animations you’ll also need to install the animations package and import the new AnimationsModule from @angular/animations in your root NgModule. Without this, your code will compile and run, but animations won’t activate.

Typescript and ng serve (cli beta32.3) both complain of AnimationsModule not found (after npm install). Looking at the node_modules folder (and also master src) for animations there is no exported AnimationsModule declared. 

Is this a case of incorrect animations package or changelog instructions? (ie looking through the source I found refs to BrowserAnimationsModule in platform-browser but I'm yet to try this out) 

**Expected behavior**

Expect to follow changelog instructions and have it work. 

**Minimal reproduction of the problem with instructions**

ng create new (cli beta32.3)
Create simple component with an animation
Follow changelog instructions for 4.0.0.rc1 with animations
ng serve

(compile err with `import { AnimationsModule } from '@angular/animations'` etc)
(Remove animations import etc and app will compile and run, but without animations)

**What is the motivation / use case for changing the behavior?**

Want animations to work with latest rc 

**Please tell us about your environment:**

* **Angular version:** 4.0.0-rc.1

* **Browser:** all 

 
* **Language:** Typescript 2.2.1

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Looks like there's an error in the changelog and you need 
```
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
```

**Comment by dharders** [comment]
@DzmitryShylovich thanks for the confirmation, i haven't had a chance to test it yet as I'm away from work but I'll report back soon

**Comment by dharders** [comment]
@DzmitryShylovich  Also, I assume the `@angular/animations` npm package is still required? But the module defs are in platform-browser?

**Comment by DzmitryShylovich** [comment]
@dharders yeah, you need `@angular/animations` module.

> But the module defs are in platform-browser?

I think there will be 2 modules: 1 for browser platform (BrowserAnimationsModule) and 1 for server platform (tbd)

**Comment by Delagen** [comment]
Cause error when calling `ngc`
```
Calling function 'style', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
```

**Comment by dharders** [comment]
@DzmitryShylovich 
Yes all good now, thanks. I see you submitted a PR to update the changelog too, awesome. One quick note: could probably also add: `import { trigger, state, style, transition, animate } from '@angular/animations';`  instead of `@angular/core`, but I think both work for now. I assume Angular will deprecate this at some point.

Note: I also had another issue with (some) animations not working in 4.0.0-rc.1, but issue was related to a different bug here #14732 and easily fixed.

@Delagen Yes, I just found that happens only with AoT (i.e ng build --prod) but not `ng serve`. Know of a workaround yet?

**Comment by crumhorn** [comment]
Might be worth mentioning the mapping needed in systemjs.config.js (for those that use systemjs) as well as otherwise it won't load.

```
map = {
'@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
...
}
```

**Comment by IgorMinar** [comment]
Sorry all! The changelog was incorrect. I merged  #14729 from @DzmitryShylovich to fix this.

**Comment by naveedahmed1** [comment]
@crumhorn can you please confirm if the systemjs config you mentioned here https://github.com/angular/angular/issues/14728#issuecomment-282710030 works with Angular 4 RC 5 (for me its not working and showing Error "/node_modules/@angular/animations/browser/ 403 (Forbidden)" in console)?

**Comment by Delagen** [comment]
@naveedahmed1  RC.4 introduce new submodule @angular/animations/browser so it must be added to config

**Comment by naveedahmed1** [comment]
@Delagen you are right, I have added below to the systemjs config and its working now:

```
map = {
'@angular/animations': 'node_modules/@angular/animations/bundles/animations.umd.min.js',
        '@angular/animations/browser':'node_modules/@angular/animations/bundles/animations-browser.umd.js',
        '@angular/platform-browser/animations': 'node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js'
}
```

**Comment by egonallison** [comment]
@naveedahmed1 

This is 100% if you are trying to use angular 4.1! Thanks!

**Comment by michaelsterpka** [comment]
Kept having errors until using @naveedahmed1 solution

Thank you so much!

**Comment by ufthelp** [comment]
Thank you @naveedahmed1  for your solution.

**Comment by Aakash1393** [comment]
In which file should I put naveedahmed1 solution to the problem.
