### ISSUE TITLE
After restart the backend server , When i  press F5 or refresh the page, the page content has not changed.

### ISSUE THREAD

**Issue by Christian-Yang** [angular/angular#14727]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

after npm  run build.prod   ,i  get a  production .
When I close the backend server, then reopen the backend server. When i  press F5 or refresh the page, the page content has not changed.Restful request reply 200 OK (from cache). The data is not retrieved from the backend server. And the response is shown in the index.html page code, preview page shows the contents of index.html.I must clear all the history of the browser in order to see the latest page.
Often this happens on some pages

If  i close  the backend server . Then  when i  press F5 or refresh the page, the page content has not changed.Restful request reply 200 OK (from cache).why it  do not  response  502  or 404???
![kkkkkkkkkkkkkkkkkkkkk](https://cloud.githubusercontent.com/assets/25613332/23329064/16012e8e-fb6b-11e6-8ce8-8da4000154d9.jpg)
![pppppp](https://cloud.githubusercontent.com/assets/25613332/23329071/25aa0cca-fb6b-11e6-95e3-08433b60fc02.jpg)
![qqqqqqqqqq](https://cloud.githubusercontent.com/assets/25613332/23329077/3e670628-fb6b-11e6-8270-97a7fbe39f7c.jpg)

<br/>
**Expected behavior**

When I close the backend server, then reopen the backend server.I expect to see new data from the server.
When i  press F5 or refresh the page, the page content has changed.
<br/>
**Minimal reproduction of the problem with instructions**
nothing

**What is the motivation / use case for changing the behavior?**

nothing
**Please tell us about your environment:**

$:uname   -v
~precise1-Ubuntu SMP Fri Dec 18 10:38:55 UTC 2015

IDE: webstorm 

package manager:  gulp": "^3.8.32",

http server :   nginx

angular-seed:
"name": "angular-seed",
  "version": "0.0.0",
  "description": "Modular starter project for Angular 2 (and beyond) with statically typed build and AoT compilation",
  "repository": {
    "url": "https://github.com/mgechev/angular-seed"
  },

 "@angular/compiler-cli": "^2.1.0",
    "@angular/platform-server": "^2.1.0",
    "@angular/tsc-wrapped": "^0.3.0",
    "@types/async": "^2.0.32",
    "@types/browser-sync": "^0.0.34",
    "@types/core-js": "^0.9.34",
    "@types/express": "^4.0.33",
    "@types/gulp": "^3.8.32",
    "@types/gulp-load-plugins": "^0.0.28",
    "@types/gulp-protractor": "^1.0.29",
    "@types/gulp-sass": "^0.0.29",
    "@types/gulp-util": "^3.0.29",

* **Angular version:** 2.0.X

in  package.json  , i get followings:
 "@angular/common": "^2.1.0",
    "@angular/compiler": "^2.1.0",
    "@angular/core": "^2.1.0",
    "@angular/forms": "^2.1.0",
    "@angular/http": "^2.1.0",
    "@angular/platform-browser": "^2.1.0",
    "@angular/platform-browser-dynamic": "^2.1.0",
    "@angular/router": "^3.1.0",
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome  : version 56.0.29
Firefox: version  51.0.0
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript   1.8.10

* **Node (for AoT issues):** `node --version` =   v6.9.0

Thanks  very much  for help me  !!!

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by IgorMinar** [comment]
@Christian-Yang I second what @DzmitryShylovich said. Your problem is most likely the http cache headers that your nginx server sends that instruct the browser to not reload the content, but that's not an issue we should be solving on this issue tracker. Please try StackOverflow.

**Comment by Christian-Yang** [comment]
@IgorMinar   thank you very much  !  The problem was finally solved.Nginx configuration and http response header error caused this problem.
