### ISSUE TITLE
Animation styles not applied in case of multiple state names

### ISSUE THREAD

**Issue by fjozsef** [angular/angular#14732]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Animation state name expression doesn't work properly with multiple state names. No style applied.

**Expected behavior**

Animation state name expression should work with multiple state names and the given styles should be applied. [See](https://angular.io/docs/ts/latest/api/core/index/state-function.html)

**Minimal reproduction of the problem with instructions**

It works in 2.4.8: https://plnkr.co/edit/LNgWJJ1hJbAOuxGeZLIN
But not in 4.0.0-rc.1: https://plnkr.co/edit/Z65objqs8vIHQdcLJvoU

Notice if you remove `, grey` from the state then it works in 4.0.0-rc.1, too.

**What is the motivation / use case for changing the behavior?**

It is probably a regression. Angular Animation should support multiple state names in 4.0.0, too.

**Please tell us about your environment:**

* **Angular version:** 4.0.0-rc.1

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by dharders** [comment]
Good catch! Confirmed bug.

Simple workaround until this is patched:

Change this:
```javascript
state('gray, grey', style({ backgroundColor: 'grey'}))
```
To this:
```javascript
[ state('gray', style({ backgroundColor: 'grey'})),
  state('grey', style({ backgroundColor: 'grey'})) ]
```
