### ISSUE TITLE
ES5 testing bundles contain ES2015 codes

### ISSUE THREAD

**Issue by log2-hwan** [angular/angular#14730]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
ES5 testing bundle files(`testing.es5.js`) contain ES2015 codes.

**Expected behavior**
`testing.es5.js` files contain transpiled ES5 codes.

* **Angular version:** 4.0.0-rc.1

 
* **Language:**: Typescript 2.1.6

**Comment by wesleycho** [comment]
To give more useful information, I am seeing this error in tests
```
25 02 2017 05:28:23.601:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket _2cnmwANx86QAZZZAAAA with id 80543945
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at webpack:///~/@angular/core/@angular/core/testing.es5.js:10:0 <- karma-shim.js:11349
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at webpack:///~/@angular/core/@angular/core/testing.es5.js:10:0 <- karma-shim.js:11349
```

Possibly related, I also see this particular message when running my Webpack build
```
WARNING in ./~/@angular/core/@angular/core.es5.js 3705:332-415 Critical dependency: the request of a dependency is an expression
```

I suspect that whatever build process is generating these `.es5` files is not doing the appropriate compilation from ES6 to ES5.

**Comment by csentis** [comment]
@wesleycho  re the warning...
```
WARNING in ./~/@angular/core/@angular/core.es5.js 3705:332-415 Critical dependency: the request of a dependency is an expression
```
... you can, thanks to @Martin-Wegner, find a solution in #11580:

```
new webpack.ContextReplacementPlugin(
  /angular(\\|\/)core(\\|\/)@angular/,
  path.resolve(__dirname, '../src')
)
```
Use the snippet above to replace what was common before (up until 4.0.0-beta.8):
```
new webpack.ContextReplacementPlugin(
  /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
  path.resolve(__dirname, '../src')
)
```

**Comment by DjolePetrovic** [comment]
If you use angular cli, you are out of luck? Or can you still use this snippet somehow?

**Comment by stevermeister** [comment]
@csentis the snippet did not help to solve the actual issue

**Comment by csentis** [comment]
@DjolePetrovic I have no experience with an angular-cli-based setup. As far as I have learned, angular-cli hides the webpack config which is exactly the place where you would put the snippet I referenced above - which is why I assume: out of luck. Someone here who could please contribute hard facts instead of my assumptions?
@stevermeister true - as originally stated, the snippet targets the part of the "critical dependency" warning only.
