### ISSUE TITLE
Expose name in package.json of subpackages

### ISSUE THREAD

**Issue by Delagen** [angular/angular#14736]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
No name in `@angular/platform-browser/animations` package.json

**Expected behavior**
name equals `@angular/platform-browser/animations`

**What is the motivation / use case for changing the behavior?**
Possibility to bundle typings using `typings` 

* **Angular version:** 4.0.0-rc.1

* **Language:** TypeScript 2.2.1

* **Node (for AoT issues):** `node --version` =   7.6.0

**Comment by IgorMinar** [comment]
we don't know how to expose these secondary entry points in the main package.json. there is no standard or precedence for this as far as I know.

We do want to bundle the d.ts files though. `tsc` currently doesn't support this option. Are you saying that `typings` can do that? Does it produce d.ts files with ES modules (exports) or with ambient modules?

**Comment by Delagen** [comment]
Thanks
