### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getDOM' of undefined

### ISSUE THREAD

**Issue by starksds** [angular/angular#14733]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Upgraded from 4.0.0-beta.8 to 4.0.0-rc-1. Run project with and without AoT.

**Expected behavior**

The project has been running as expected before the change.

**Minimal reproduction of the problem with instructions**

I can give invite to private repo if needed.

**What is the motivation / use case for changing the behavior?**

Site doesn't work in the browser now.

**Please tell us about your environment:**

Macbook Pro with macOS Sierra

* **Angular version:** 2.0.X

4.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Latest version of Chrome. 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.1

* **Node (for AoT issues):** `node --version` =   
node = 6.9.4
npm = 3.10.10

**Comment by DzmitryShylovich** [comment]
pls add a plunkr or a github repo that reproduces the issue

**Comment by starksds** [comment]
@DzmitryShylovich can i just invite you to my repo?

**Comment by DzmitryShylovich** [comment]
@starksds no. thanks :) I don't have time to debug a real app

**Comment by starksds** [comment]
@DzmitryShylovich cool, i don't have time to convert this to a plunkr.  It's a legit new error as I've been upgrading my app immediately with each new release but I'll figure it out.  Thanks anyway.

**Comment by aitboudad** [comment]
@starksds can you try with
```ts
import { ɵgetDOM as getDOM } from '@angular/platform-browser';
```
since `4.0.0.rc1` we can't anymore use import from `src` not sure why
```ts
import { DomAdapter, getDOM } from '@angular/platform-browser/src/dom/dom_adapter';
```

**Comment by DzmitryShylovich** [comment]
@aitboudad DomAdapter is a private api. You shouldn't use it at all.

**Comment by aitboudad** [comment]
I know but it's useful in case you want to add some class to body for example ;)
``` ts
this.dom.addClass(this.document.body, 'test'); 
```

**Comment by DzmitryShylovich** [comment]
@aitboudad you can add a class to the `body` element using `HostBinding`

**Comment by starksds** [comment]
@aitboudad thank for the suggestion but I'm not trying to use DomAdapter
@DzmitryShylovich My guess would be I have an issue with my vendor webpack build.

![image](https://cloud.githubusercontent.com/assets/4741087/23332376/5316b4ba-fb3e-11e6-9707-424379b0ae51.png)

**Comment by DzmitryShylovich** [comment]
@starksds looks like the same error https://github.com/angular/angular/issues/14730#issuecomment-282484178

**Comment by alexzuza** [comment]
I don't know maybe it is a bug but we have access to `getDom` through

`import { ɵgetDOM } from '@angular/platform-browser'`

http://plnkr.co/edit/yUeTxo0k8cugg6FBN5wt?p=preview

**Comment by DzmitryShylovich** [comment]
@starksds I think `flex-layout` is not ready for rc migraton

**Comment by starksds** [comment]
@DzmitryShylovich sounds reasonable.  thanks for debugging a "real app"!

**Comment by aitboudad** [comment]
@DzmitryShylovich but angular doesn't provide any way to modify DOM elements outside the root component

**Comment by DzmitryShylovich** [comment]
@starksds they already removed usage of private apis https://github.com/angular/flex-layout/commit/d95cb095042e9e2c45d0a63e50b07622474a74c3
what version do you use?

**Comment by starksds** [comment]
@DzmitryShylovich I missed upgrading flex to rc-1 (user error... face palm).  I'm going to close the issue.

**Comment by miliu99** [comment]
ah, I started getting this error after I upgraded from angular v2.4.1 to v4.0.0. 

this is my vendor.ts:

```
// polyfills
import 'core-js/client/shim';
import 'core-js/es6';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
import 'reflect-metadata';

import 'rxjs/Rx';

// vendor
import '@angular/common';
import '@angular/core';
import '@angular/animations';
import '@angular/forms';
import '@angular/http';
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/router';
```

here is my package.json:

```
{
  "name": "angular2-express-mongoose",
  "version": "1.4.0-rc.7",
  "description": "Angular 2, Express.js, Mongoose.js, Node.js",
  "author": "Davide Violante",
  "repository": {
    "type": "git",
    "url": "https://github.com/DavideViolante/Angular2-Express-Mongoose.git"
  },
  "scripts": {
    "postinstall": "typings install",
    "prestart": "webpack",
    "start": "concurrently \"webpack --watch --colors\" \"nodemon src/server.js\"",
    "typings": "typings"
  },
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/compiler-cli": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/platform-server": "4.0.0",
    "@angular/router": "^3.4.1",
    "body-parser": "^1.15.2",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "express": "^4.14.0",
    "font-awesome": "^4.6.3",
    "jquery": "^2.2.4",
    "moment": "^2.18.1",
    "mongoose": "^4.6.0",
    "morgan": "^1.7.0",
    "ng-bootstrap": "^1.1.16-1",
    "ng2-toastr": "^4.0.1",
    "nodemailer": "^3.1.8",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.2.0",
    "tether": "^1.3.7",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "jscs": "^3.0.7",
    "nodemon": "^1.10.2",
    "source-map-loader": "^0.1.5",
    "ts-loader": "^0.8.2",
    "typescript": "^2.2.2",
    "typings": "^1.3.3",
    "webpack": "^1.13.2"
  }
}

```

I don't see any error on npm start though. What do I miss?

**Comment by micronyks** [comment]
Facing same error.
wrote below line in `app.module.ts` 

    import { ɵgetDOM } from '@angular/platform-browser'

OR

    import { ɵgetDOM as getDOM } from '@angular/platform-browser';

but it says

>  '"../node_modules/@angular/platform-browser/platform-browser"' has no exported member 'ɵgetDOM'.

Need help on this issue.

**Comment by yogesh2singh** [comment]
I upgraded my angular 2 project from 2.4.7 to  4.0.2 and getting below error

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'ɵgetDOM' of undefined
    at k (index.4b38103….min.js:25)
    at k (index.4b38103….min.js:25)
    at index.4b38103….min.js:25
    at a.invokeTask (index.4b38103….min.js:25)
    at Object.onInvokeTask (index.4b38103….min.js:36)
    at a.invokeTask (index.4b38103….min.js:25)
    at c.runTask (index.4b38103….min.js:25)
    at f (index.4b38103….min.js:25)

**Comment by yogesh2singh** [comment]
I have tried above options and still not able to resolve the issue. Please see below error
I have migrated angular from 2.4.7 to 4.0.2

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'ɵgetDOM' of undefined
    at k (index.4b38103….min.js:25)
    at k (index.4b38103….min.js:25)
    at index.4b38103….min.js:25
    at a.invokeTask (index.4b38103….min.js:25)
    at Object.onInvokeTask (index.4b38103….min.js:36)
    at a.invokeTask (index.4b38103….min.js:25)
    at c.runTask (index.4b38103….min.js:25)
    at f (index.4b38103….min.js:25)

**Comment by saxena511** [comment]
I am facing TypeError Issue.
Exception: Call to Node module failed with error: Prerendering failed because of error: TypeError: Cannot read property 'getDOM' of undefined
at Object.<anonymous> (D:\Angularplayapp\node_modules\angular2-platform-node\get-dom.js:3:61)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (D:\Angularplayapp\node_modules\angular2-platform-node\index.js:5:17)
at Module._compile (module.js:570:32)

Please suggest me, what actually I missing?

**Comment by bakoserge** [comment]
facing same issue as @saxena511 . Any fix?

**Comment by dafabulousteach** [comment]
Same here. Still having getDom issues

**Comment by henriquecustodia** [comment]
Angular v4.3.3

works for me:  
```ts
import { ɵgetDOM as getDOM } from '@angular/platform-browser';
```

**Comment by bakoserge** [comment]
@henriquecustodia did you do that in the app.module ?

**Comment by salah21500** [comment]
i got the same problem,
Try this to upgrade your project to latest versions.


`npm install @angular/common@latest @angular/compiler@latest @angular/core@latest @angular/forms@latest @angular/http@latest @angular/platform-browser@latest @angular/platform-browser-dynamic@latest @angular/platform-server@latest @angular/router@latest @angular/animations@latest --save`

**Comment by GagikAbovyan** [comment]
npm install @angular/common@latest @angular/compiler@latest @angular/core@latest @angular/forms@latest @angular/http@latest @angular/platform-browser@latest @angular/platform-browser-dynamic@latest @angular/platform-server@latest @angular/router@latest @angular/animations@latest --save +1

**Comment by Syakiran407** [comment]
Thanks, @salah21500 your solution works for me
