### ISSUE TITLE
Unexpected token: name (AnimationEngine)

### ISSUE THREAD

**Issue by starksds** [angular/angular#14737]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using the new animation module throws AoT error if using uglifyjs webpack plugin

**Expected behavior**

No error

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I would like my animations to work

**Please tell us about your environment:**

Macbook Pro macOSSierra

* **Angular version:** 2.0.X

4.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Didn't make it that far 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.1

* **Node (for AoT issues):** `node --version` =   
node = 6.9.4
![image](https://cloud.githubusercontent.com/assets/4741087/23334539/a8882f96-fb66-11e6-8a57-dfeb412e36fd.png)

**Comment by matsko** [comment]
Make sure to load and use `BrowserAnimationsModule` from platform_browser instead of `BrowserModule`.

**Comment by matsko** [comment]
If you end up using a UMD instead of webpack then you can load it from `@angular/platform-browser/animations`.

**Comment by dharders** [comment]
@starksds I got the same error when importing trigger, state, etc from `@angular/core`, and it went away when I swapped it to import trigger, state etc from `@angular/animations`

However, now I get a different error (for AoT only, ng serve works fine): `Calling function 'style', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function`, see related issue here [#14728 comment](https://github.com/angular/angular/issues/14728#issuecomment-282521755). Any suggestions @matsko ?

**Comment by starksds** [comment]
@matsko I am using BrowserAnimationsModule

`import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`

@dharders I am also getting the same error when switching to `@angular/animations`

**Comment by alexzuza** [comment]
![2](https://cloud.githubusercontent.com/assets/4223314/23342347/1150babe-fc72-11e6-8f83-c6511c75c00c.png)

**Comment by bboehm86** [comment]
I've got the same issue
```
Calling function 'style', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
``` 
while using the 
`import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`


But when I remove all of my animations that error is gone an the
```
ERROR in vendor.855441f7a43ae9868342.bundle.js from UglifyJs
SyntaxError: Unexpected token: name (AnimationEngine) [vendor.855441f7a43ae9868342.bundle.js:12855,6]
```
greets me when I'm trying to compile the app with aot

**Comment by maku** [comment]
I get the same error (using @angular/cli 1.0.0-rc.0)

**Comment by DzmitryShylovich** [comment]
@bboehm86 there's a separate issue for it https://github.com/angular/angular/issues/14774

**Comment by matsko** [comment]
This commit should fix the issue: https://github.com/angular/angular/commit/9560ad81b9fea40015738ca9c068b8942c3d3244

**Comment by DzmitryShylovich** [comment]
@starksds does the issue still persist in rc2?

**Comment by naveedahmed1** [comment]
I can confirm it has been resolved.

**Comment by DzmitryShylovich** [comment]
@starksds then close the issue please. thanks
