### ISSUE TITLE
Uncaught (in promise): RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by angheladrianclaudiu** [angular/angular#14743]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

I am using angular cli 1.0.0-beta.28 to build my project and I managed it to do so. However I have a problem when I try to add a component with a footer tag like this one below.

Also filled a bug on angular-cli but they told me that the bug would rather be in angular itself and not in angular-cli. Check here: https://github.com/angular/angular-cli/issues/4935

**Expected behavior**

The main view of the app should load.

**Minimal reproduction of the problem with instructions**

```
<footer class="bg-lightgray footer">
	This is a footer
</footer>
```

The code builds successfully, but when I load the application in the browser I encounter the following error:
[EXCEPTION: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Object.b (http://localhost:8080/vendor.64f55cc7b77cf4fbea63.bundle.js:1109:1214)
    at Object.z (http://localhost:8080/vendor.64f55cc7b77cf4fbea63.bundle.js:1102:2666)
    at Object._13 (http://localhost:8080/vendor.64f55cc7b77cf4fbea63.bundle.js:1592:1803)
    at Object.ViewEncapsulation (http://localhost:8080/vendor.64f55cc7b77cf4fbea63.bundle.js:1:3173)
    at t.createViewRoot (http://localhost:8080/vendor.64f55cc7b77cf4fbea63.bundle.js:766:2279)
    at proxyViewClass.View_t0.createInternal (/t/t/component.ngfactory.js:12:40)
    at proxyViewClass.t.create (http://localhost:8080/vendor.64f55cc7b77cf4fbea63.bundle.js:1641:1105)
    at proxyViewClass.View_t0.createInternal (/t/t/component.ngfactory.js:72:19)
    at proxyViewClass.t.create (http://localhost:8080/vendor.64f55cc7b77cf4fbea63.bundle.js:1641:1105)
    at proxyViewClass.View_t0.createInternal (/t/t/component.ngfactory.js:72:19)
    at proxyViewClass.t.create (http://localhost:8080/vendor.64f55cc7b77cf4fbea63.bundle.js:1641:1105)
    at proxyViewClass.View_t0.createInternal (/t/t/component.ngfactory.js:72:19)
    at proxyViewClass.t.create (http://localhost:8080/vendor.64f55cc7b77cf4fbea63.bundle.js:1641:1105)
    at proxyViewClass.View_t0.createInternal (/t/t/component.ngfactory.js:72:19)
    at proxyViewClass.t.create (http://localhost:8080/vendor.64f55cc7b77cf4fbea63.bundle.js:1641:1105)]

### This is my package.json content:

```
{
  "name": "eventpromoter-website",
  "version": "1.0.0",
  "license": "Wrapbootstrap",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
	"prod": "ng build -prod",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
	"core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2",
    "body-parser": "^1.15.2",
    "cookie-parser": "^1.4.3",
    "serve-favicon": "^2.3.2",
    "bootstrap": "3.3.7",
    "jquery": "^2.2.4",
	"flexslider": "2.6.3",
	"jquery.easing": "1.4.1",
	"magnific-popup": "1.1.0",
	"jquery-sticky": "1.0.4",
	"owl.carousel": "2.2.0",
	"parsleyjs": "2.6.2",
	"themify-icons": "1.0.0"
  },
  "devDependencies": {
    "@types/jasmine": "2.2.30",
    "@types/node": "6.0.42",
    "angular-cli": "^1.0.0-beta.28",
    "codelyzer": "1.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "2.0.3"
  }
}

```
**What is the motivation / use case for changing the behavior?**

I don't know, maybe something isn't compiled properly.

**Please tell us about your environment:**

* **Angular version:** 2.3.1

* **Browser:** Chrome 56.0.2924.87

 
* **Language:** 2.0.3

* **Node (for AoT issues):** `node --version` =  6.9.5

**Comment by DzmitryShylovich** [comment]
pls add a plunkr

**Comment by angheladrianclaudiu** [comment]
Pretty complicated to do this considering the current configuration of my project with angular-cli. However, I will close this since I've fixed it.

**Comment by DzmitryShylovich** [comment]
in general ` RangeError: Maximum call stack size exceeded` means you have an infinite loop somewhere

**Comment by angheladrianclaudiu** [comment]
I know that. But I didn't have any code with loops. I just had HTML code wrapped in angular components that wasn't loading properly at runtime. However, I managed to fix the components by wrapping the HTML tags that were breaking the loading (i.e. footer and section) with container divs. So I managed to fix it by changing the structure of HTML a little bit.

Thanks,
Adrian

**Comment by fbasa** [comment]
Same issue here when I forgot to import the routing module,

**Comment by mumairofficial** [comment]
May be strange I solved by updating **app-scripts** `npm install @ionic/app-scripts@latest --save-dev`

**Comment by frederikocmr** [comment]
I solved this problem _"Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded"_ by running `ng serve` again.
Why I got this problem?
 I had two terminals opened at once. In terminal 1, there was the 'ng serve' serving. And in the terminal 2, I was creating components/services/modules with `ng generate `. 

So I think that there was a problem with the new changes and the process that was serving the application, by some reason it did not recognize the changes and got a infinite loop in some observer...

Well, anyway, **by running `ng serve` again this fixed** for me!

**Comment by shubh9415** [comment]
The possible reason for this error might be that wherever the routes are written to redirect the application, it can't find any component to load.
Try making a routing file and assign default route component like 
   {path: '', component: first}
and then import it in the module file.
