### ISSUE TITLE
docs Multi Page App - Is there any way to use Angular2 in multi-page app instead SPA?

### ISSUE THREAD

**Issue by hasnatbabur** [angular/angular#14745]
I can not use Angular 2 for some of my projects because it forces me to do a SPA app. Is there is a way to use Angular 2 in multi page app like Angular 1, ReactJS or VueJS do? Thanks

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mikeandersun** [comment]
@DzmitryShylovich  This is a important feature request that NOT in Angular2.

**Comment by zoechi** [comment]
@mikeandersun How does Angular2 force you to do that? What feature are you missing?

**Comment by Toxicable** [comment]
@mikeandersun if you want to make a feature request then please fill out the issue template with proper use cases and motivation

**Comment by snewell92** [comment]
@hasnatbabur @mikeandersun [This reddit post](https://www.reddit.com/r/Angular2/comments/424nwn/using_angular_2_without_it_being_a_single_page_app/) links to [this article](https://www.mediacurrent.com/blog/building-wundergroundcom-drupal-angular-2-challenge-1-how-bootstrap) which shows [this plunker](http://plnkr.co/edit/A7fyFUST9IdP1FriauXk?p=preview), demonstrating a bootstrapping process that would work in an MPA.

I don't think Angular is constraining you to an SPA.

**Comment by meyacine** [comment]
I don't recommand this way to use angular. It's like you want to restart your application on each URL change (If you have one entry page).

Not that the Router is not in @angular/core, so your <a href="foo/bar"> works normaly, and reload your page.

**Comment by squadwuschel** [comment]
@meyacine not everyone live in a dreamworld :-) - sometimes you have to use the environment you have. Its a good question and it would be nice if Angular would support multiple apps on one page. Or better to say creating simple components I can use everywhere.

**Comment by gkalpak** [comment]
> Or better to say creating simple components I can use everywhere.

@squadwuschel, look out for `@angular/elements` :wink:
@robwormald has talked about it on [AngularMIX][1] and [AngularConnect][2]. An initial implementation is being worked on in the [labs/elements][3] branch.

[1]: https://www.youtube.com/watch?v=ljsOPm4MMEo
[2]: https://www.youtube.com/watch?v=ZNTsdaZiqP8&t=1h25m5s
[3]: https://github.com/angular/angular/tree/labs/elements

**Comment by sod** [comment]
We use it multipage. Can't recommend it. Either wait for official sollutions or do an SPA.

As we jumped on angular2 from angularjs we didn't know it was supposed to be used as an "it owns everything inside `<body></body>` framework". When AoT was not a thing back then, multipage was pretty easy to do.

But the code to make this work got very fragile over time. Every major and sometimes minor releases breaks stuff. We are still not on angular5 as the removal of annotations in AoT mode made some things we do at runtime impossible.

**Comment by inquiztr** [comment]
I have also been struggling to get angular work with MPA. We currently use angular 4 with webpack and ngcwebpack plugin to compile our multi page app with AOT. I have been unable to do so with Angular5 and the ngtools plugin. It has been hard to explain to our management that it just isn't meant to be used in such a way. I do regret having adopted Angular now that we have spent a year converting our ecommerce site over to it. It just seems the team is more focused toward spa. Which is odd as we chose Angular as we thought it would be more suited for larger institutional projects, not little toy projects.

**Comment by snewell92** [comment]
@inquiztr  I ended up doing the 'spa' way, yet I still have the app shell rendered on the server, and my server routing is able to do processing. Angular catches the routes and goes to the correct module/component - so it behaves adequately. With lazy-loaded routes I think you could get behavior like you want (not loading the whole app on every page).

I was trying to make each page its own app - but that's such a pain. Lazy loaded routes r the way to go.

**Comment by inquiztr** [comment]
I would like to go that way but our environment doesn't support it right now. We use a .net framework and my understanding to switch to Angular Universal rendering we would first have to switch our backend to .net core. Once we do that, I agree that the SPA way with lazy loaded routes and universal rendering should probably be the way forward.

**Comment by jenniferfell** [comment]
@robwormald @StephenFluin Can either of you comment on this thread? Is this something that gets addressed with Angular elements?

**Comment by sgf** [comment]
ppl really need MPA support,
SPA is good for management system.
but not apply to every situation.

such as when ppl need open a full page view.
ppl could let the new tag show full page,and keep the old page (the management Main page) is opening.
This is a huge improvement on the user experience.

**Comment by mgechev** [comment]
I'd recommend you to check our [Angular Elements](https://angular.io/guide/elements) guide. Additionally, there are a lot of community blog posts that you can follow.

Let us keep our focus more on SPA for now.
