### ISSUE TITLE
[Router bug?]Spinner on Route change doesn't show with *ngIf

### ISSUE THREAD

**Issue by dereklin** [angular/angular#14741]
I am using 2.4.8.

I followed the accepted answer of http://stackoverflow.com/questions/37069609/show-loading-screen-when-navigating-between-routes-in-angular-2 but it's no longer working.

When I remove 
```
*ngIf="loading"
```
from 
```
  <div class="flex-item" fxFlex="20px" fxFlexFill *ngIf="loading">
    <md-progress-bar mode="indeterminate"></md-progress-bar>
  </div>
```
I can see the progress bar is running

At NavigationStart, loading is set to true, but the progress bar doesn't show
```
      if (event instanceof NavigationStart) {
          this.loading = true;
      }
```
The 
```
  <div class="flex-item" fxFlex="20px" fxFlexFill *ngIf="loading">
    <md-progress-bar mode="indeterminate"></md-progress-bar>
  </div>
```
block doesn't update

But through debugging, I can tell it updates at NavigationEnd.  But because the loading is set to false at NavigationEnd, the progress bar is never visible.

Why doesn't the progress bar show when loading is set to true at NavigationStart?

Here is my test site: https://blooming-dusk-1808.herokuapp.com/#/home
Here is my code repo: https://github.com/dereklin/ng-ws-ngrx-hmr-heroku
Here are the specific code:
https://github.com/dereklin/ng-ws-ngrx-hmr-heroku/blob/master/src/app/core/core.component.ts
https://github.com/dereklin/ng-ws-ngrx-hmr-heroku/blob/master/src/app/core/core.component.html

**Comment by DzmitryShylovich** [comment]
Probably related to https://github.com/angular/angular/issues/14588

**Comment by DzmitryShylovich** [comment]
@dereklin should work in 2.4.9

**Comment by dereklin** [comment]
@DzmitryShylovich I have upgraded to 2.4.9, but the progress bar is still not showing on route switch.

**Comment by DzmitryShylovich** [comment]
@dereklin please add the plunkr that illustrates the issue. thanks

**Comment by dereklin** [comment]
@DzmitryShylovich This is interesting, it actually works even with 2.4.8 with simple routes: https://plnkr.co/edit/bm7lIBsdF2gI5mio1tdB?p=preview

I am using nested routes in my repo.  I will try to replicate my set up with plunker when I have time...

**Comment by dereklin** [comment]
OK. This is interesting.  It turns out adding the DelaySerivce actually "fixed" the problem.  So I added the same delay, but 100 ms to my site, it worked: https://blooming-dusk-1808.herokuapp.com/#/home

Prime Table takes forever to load, the progress bar will show.  It seems that tiny delay enable Angular to update the DOM.

This still feel a bug to me.  Or is it expected?

**Comment by jasonaden** [comment]
Adding a delay creates a `Promise.then()` which likely means this was a Zones issue. You can track the issue here: https://github.com/ReactiveX/rxjs/pull/2266
