### ISSUE TITLE
Http.patch sends incorrect method

### ISSUE THREAD

**Issue by prydin** [angular/angular#14749]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm calling http.patch as follows:
```
this.http.patch('http://localhost:4201/images/pontus/hello.zip?file=' + this.selectedFile, this.code)
         .subscribe(result => this.code =result.text());
``` 

This should result in a request starting with the following line:
PATCH /images/pontus/hello.zip?file=foo.txt

**Expected behavior**
This is what it looks like if I send a PATCH request through Postman:
```
PATCH /images/pontus/hello.zip?file=handler.js HTTP/1.1
Host: localhost:4201
Connection: keep-alive
Content-Length: 420
Postman-Token: e9863551-7ff5-6b87-cb52-4ad29430145f
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: */*
DNT: 1
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,sv;q=0.6
```

**Actual behavior**
```
OPTIONS /images/pontus/hello.zip?file=handler.js HTTP/1.1
Host: localhost:4201
Connection: keep-alive
Access-Control-Request-Method: PATCH
Origin: http://localhost:4200
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Access-Control-Request-Headers:
Accept: */*
DNT: 1
Referer: http://localhost:4200/edit
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,sv;q=0.6
```

Notice how Angular2 sends an OPTIONS request rather than a PATCH

**Minimal reproduction of the problem with instructions**
Execute a http.patch request similar to this: 

```
this.http.patch('http://localhost:4201/images/pontus/hello.zip?file=' + this.selectedFile, this.code).
     subscribe(result => this.code =result.text());
```
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

prydin-m01:sth-ui prydin$ node -v
v6.9.1

* **Angular version:** 2.0.X
Angular http 2.4.8

* **Browser:** [Chrome Version 56.0.2924.87 (64-bit), FireFox 38.0.5 ]
 
* **Language:** [TypeScript ]

* **Node (for AoT issues):** `node --version` =   
prydin-m01:sth-ui prydin$ node --version
v6.9.1

**Comment by DzmitryShylovich** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

**Comment by prydin** [comment]
Not a bug. My bad.
