### ISSUE TITLE
Angular 4.0.0-rc.1 error with "angular2-universal": "~2.1.0-rc.1",

### ISSUE THREAD

**Issue by damirkusar** [angular/angular#14753]
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
Current behavior
After updating Angular 4 beta 3 to RC1, i am getting an error in Angular-Universal

```
Exception: Call to Node module failed with error: Prerendering failed because of error: TypeError: Cannot read property 'getDOM' of undefined
at Object.<anonymous> (C:\Users\TDAMIKUSA\Documents\docs\Code\WebAppSolution\WebApp\node_modules\angular2-universal\node_modules\angular2-platform-node\get-dom.js:3:61)
Expected behavior
Error should not occure
```

Minimal reproduction of the problem with instructions
Take this repo: https://github.com/damirkusar/AngularMeetsNetCore,
update in package.json the angular libraries to RC1

    "@angular/common": "4.0.0-rc.1",
    "@angular/compiler": "4.0.0-rc.1",
    "@angular/compiler-cli": "4.0.0-rc.1",
    "@angular/core": "4.0.0-rc.1",
    "@angular/forms": "4.0.0-rc.1",
    "@angular/http": "4.0.0-rc.1",
    "@angular/platform-browser": "4.0.0-rc.1",
    "@angular/platform-browser-dynamic": "4.0.0-rc.1",
    "@angular/platform-server": "4.0.0-rc.1",
    "@angular/router": "4.0.0-rc.1",

Remove in ClientApp/boot-client.ts and boot-server.ts the universal workourand since there is an error as well, but assuming it is not needed anymore.

`//import './_workaround.universal.ts';`
This is the error when keeping the workaround:

```
Exception: Call to Node module failed with error: Prerendering failed because of error: TypeError: Cannot read property 'ViewUtils' of undefined
at Object.c (C:\Users\TDAMIKUSA\Documents\docs\Code\WebAppSolution\WebApp\ClientApp\dist\main-server.js:690:29)
```

Start the app

What is the motivation / use case for changing the behavior?
I would like to use the newest angular release

Please tell us about your environment:

Windows 7, Visual Studio 2015

Angular version: 4.0.0-rc.1
All Browsers

Language: [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "^2.1.6",

-> Opened Issue in Angular [https://github.com/angular/universal/issues/666](https://github.com/angular/universal/issues/666) as well

**Comment by DzmitryShylovich** [comment]
does `angular2-universal` support angular 4 rc? I think you should open it on https://github.com/angular/universal

**Comment by damirkusar** [comment]
Good question.. I thought so when reading your readme..

Universal, the project that allows developers to run Angular on a server, is now up to date with Angular again

is universal not part of Angular ecosystem? is and will this always be a separate release flow?

**Comment by DzmitryShylovich** [comment]
> is universal not part of Angular ecosystem?

it is, but the core team doesn't maintain `angular2-universal` module.

**Comment by damirkusar** [comment]
Aha, ok..

but will angular2-universal be once a part of the core and under @angular/universal some day? which will be maintained at the same time? It is a bit annoying if this is not in sync..

**Comment by DzmitryShylovich** [comment]
See https://github.com/angular/angular/issues/13822

**Comment by damirkusar** [comment]
Cool :)

So, hoping to get a fix for RC1 as well :)

**Comment by DzmitryShylovich** [comment]
@damirkusar close this issue please. it's not actionable on this repo
