### ISSUE TITLE
HTTP Header issue with angular 2 and JWT authentication.  

### ISSUE THREAD

**Issue by DILEEP-YADAV** [angular/angular#14751]
Hi! HTTP POST error like this
![error](https://cloud.githubusercontent.com/assets/8583769/23342494/6154742e-fc81-11e6-950c-f209040eae80.PNG)

Angular 2 http login code:
![login](https://cloud.githubusercontent.com/assets/8583769/23342500/a66d743e-fc81-11e6-8445-e41207f81806.PNG)

my rest aouth API working well with Postman. as
![token](https://cloud.githubusercontent.com/assets/8583769/23342487/372d1b42-fc81-11e6-83df-ad84c7fd770c.PNG)

**Comment by DzmitryShylovich** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

**Comment by DILEEP-YADAV** [comment]
Ok! But how to use with angular 2 ? my backed with spring boot rest api with spring security. it working fine with postman API test. Same request header applying with angular 2 http. But still getting above error.
Please help me. anyone....

**Comment by Chyngyz** [comment]
Try searching here [stackoverflow](http://stackoverflow.com/search?q=preflight+OPTIONS+spring). I think it is backend related in your case, as your http post seems ok.

**Comment by DILEEP-YADAV** [comment]
Resolved ! it issue with same origin , server and client running same machine. when , I put same angular 2 code with spring boot app .it is working fine.

**Comment by erycoking** [comment]
@DILEEP-YADAV Hi, am having the same problem. if you can kindly share the code snippet on how you solved it, this would be of great help to me
