### ISSUE TITLE
Rollup fails to bundle after ngc compile with 4.0.0-rc.1

### ISSUE THREAD

**Issue by steveblue** [angular/angular#14754]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
[0:9:48] LOG ngc started compiling ngfactory
[0:9:53] LOG ngc compiled /ngfactory 
[0:9:53] LOG Rollup started bundling ngfactory
Error: Unexpected token
node_modules/@angular/platform-browser/@angular/platform-browser.es5.js (6:1)
4:  * License: MIT
5:  */import{PlatformLocation,ɵPLATFORM_BROWSER_ID,CommonModule}from'@angular/common';import{PLATFORM_INITIALIZER,PLATFORM_ID,Sanitizer,platformCore,createPlatformFactory,ErrorHandler,APP_ID,ApplicationModule,Testability,RendererFactoryV2,RootRenderer,NgModule,SkipSelf,Optional,ɵNoOpAnimationPlayer,AUTO_STYLE,Injectable,Inject,InjectionToken,APP_INITIALIZER,setTestabilityGetter,ViewEncapsulation,NgZone,SecurityContext,isDevMode,ApplicationRef,Version}from'@angular/core';import*as core from'@angular/core';
6:  */var NoOpAnimationDriver=function(){function NoOpAnimationDriver(){_classCallCheck(this,NoOpAnimationDriver);}_createClass(NoOpAnimationDriver,[{key:'animate',
    ^
7:      */value:function animate(element,startingStyles,keyframes,duration,delay,easing){var previousPlayers=arguments.length>6&&arguments[6]!==undefined?arguments[6]:[];return new ɵNoOpAnimationPlayer();}}]);return NoOpAnimationDriver;}();
8:  */var AnimationDriver=function(){function AnimationDriver(){_classCallCheck(this,AnimationDriver);}_createClass(AnimationDriver,[{key:'animate',

```
**Expected behavior**

platform-browser.es5.js should be able to be parsed by Rollup.js

**Minimal reproduction of the problem with instructions**

Clone https://github.com/steveblue/angular2-rollup/
Checkout feature/4.0.0-rc1 branch
Install per README and Quick Start
Run `NODE_ENV=prod npm start` 
Notice error in Terminal

**What is the motivation / use case for changing the behavior?**

In above repository which serves as starter code ngc and Rollup work with 2.4.8. This process should work in 4.0.0-rc.1.

**Please tell us about your environment:**

MacOS Sierra

* **Angular version:** 2.0.X

4.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 No browser specified as build is failing.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.1.6

* **Node (for AoT issues):** `node --version` =   
5.5.0

**Comment by Delagen** [comment]
I think you must use ES2015 modules for rollup. Use "es2015" key resolution for package.json

**Comment by sod** [comment]
The es5 version has es2015 modules. Is you rollup up to date? The [platform-browser.es5.js](https://raw.githubusercontent.com/angular/platform-browser-builds/master/%40angular/platform-browser.es5.js) is minified. Has statements like `import*as core from'@angular/core'`. Your rollup version seems to choke on it. But the REPL on http://rollupjs.org/ can parse it.

**Comment by steveblue** [comment]
Im running rollup 0.41.4 @sod

**Comment by DzmitryShylovich** [comment]
@steveblue should be fixed in rc-2

**Comment by kylecordes** [comment]
@Delagen I have a PR outstanding on rollup-plugin-node-resolve to add support for the new "es2015" key. I think that makes more sense (the way Angular has chosen to implement it) versus shoving this new and different format, that many older tools will not understand, into "jsnext:main". Here's the PR:

https://github.com/rollup/rollup-plugin-node-resolve/pull/85

...   I think it is merely waiting for @Rich-Harris to have a chance to look at it.

For anyone eager to try it today, I have published a temporary fork with the new feature added:

https://www.npmjs.com/package/@oasisdigital/rollup-plugin-node-resolve

To see it in action:

https://github.com/OasisDigital/angular-aot-es2015-rollup

**Comment by steveblue** [comment]
This issue seems to be resolved now, even without the modification to `rollup-plugin-node-resolve` @kylecordes. TY for the notification @DzmitryShylovich

**Comment by kylecordes** [comment]
@steveblue Yes - without the change in node-resolve, you can still bundle using Rollup; but you get the "module" field rather than the "es2015" field. Therefore you get ES5-in-ES2015 modules rather than ES2015-in-ES2015 modules. The latter produces a smaller final output. (even if you ultimately compile the result after bundling, down to ES5.)
