### ISSUE TITLE
[class.foo-class] binding is not applied correctly

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular#14757]
**Current behavior**

I have component with class bindings which look like:

<foo class="class1 {{classFromProp1}}" [class.foo-class]="classFromProp2"></foo>
classFromProp2= true
when resizing screen classFromProp1 changes and foo-class gets lost.

this behavior works as expected if I use [ngClass]="{'foo-class': classFromProp2}" 

**Expected behavior**
should merge classes correctly

* **Angular version:** 2.0.X
~2.4.0

**Comment by DzmitryShylovich** [comment]
please add a plunkr

**Comment by vytautas-pranskunas-** [comment]
not sure if i have time for this... but this is easily reproducible.

**Comment by vytautas-pranskunas-** [comment]
Am this is something more serious, maybe i will try provide plunker later on because it it seams binding works correctly if i add it via method not via property like [class.foo-class]="shouldAddClass()".

**Comment by vytautas-pranskunas-** [comment]
here is the plunker: https://plnkr.co/edit/BNp0kgsJfOPqffrOQErU?p=preview

if you inspect html before press the button you can notice that 'template-wrapper' element has class 'to-be-added', but once you press button class is gone. But please notice that 'addClass' variable never is false.

**Comment by DzmitryShylovich** [comment]
yeah, looks like a bug, thanks.

**Comment by jsayol** [comment]
It seems that when a change on `bar` is detected, only the interpolation is taken into account when updating the `class` attribute and the property binding is ignored.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can you close this as a duplicate of https://github.com/angular/angular/issues/15038 because it has a better description please?

**Comment by pkozlowski-opensource** [comment]
This is the same as #15038. I'm going to close this one as a duplicate of #15038 since there is more discussion / info in #15038.
