### ISSUE TITLE
rc1 error

### ISSUE THREAD

**Issue by istiti** [angular/angular#14756]
I update all my package to  rc1
``` 
  "@angular/animations": "^4.0.0-rc.1",
    "@angular/common": "^4.0.0-rc.1",
    "@angular/compiler": "^4.0.0-rc.1",
    "@angular/compiler-cli": "^4.0.0-rc.1",
    "@angular/core": "^4.0.0-rc.1",
    "@angular/forms": "^4.0.0-rc.1",
    "@angular/http": "^4.0.0-rc.1",
    "@angular/platform-browser": "^4.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^4.0.0-rc.1",
    "@angular/platform-server": "^4.0.0-rc.1",
    "@angular/router": "^4.0.0-rc.1",
```
_typescript 2.1.6, cli rc0, win10_

after run `ng serve` i get : 

> Cannot read property 'length' of undefined
> TypeError: Cannot read property 'length' of undefined

What does this mean ?

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by istiti** [comment]
Trough this report I want to say 

> please guys improve error message

**Comment by DzmitryShylovich** [comment]
reproduce on Plunkr

**Comment by ericmartinezr** [comment]
This is not an angular issue, it seems to be cli's. Doing a simple search in their repo gives two results https://github.com/angular/angular-cli/issues/4940 and https://github.com/angular/angular-cli/issues/4759
