### ISSUE TITLE
OpaqueToken is deprecated -- add to CHANGELOG

### ISSUE THREAD

**Issue by JohannesHoppe** [angular/angular#14763]
Since `OpaqueToken` is deprecated on master, this fact should be mentioned in the CHANGELOG for 4.0.0-rc.1 

```
 * @deprecated since v4.0.0 because it does not support type information, use `InjectionToken<?>`
 * instead.
 */
class OpaqueToken {
```

see https://github.com/angular/angular/blob/d169c2434e3b5cd5991e38ffd8904e0919f11788/modules/%40angular/core/src/di/injection_token.ts#L29

**Comment by PascalPrecht** [comment]
It's actually in there. Not mentioned as a deprecation explicitly though.

![screen shot 2017-02-27 at 14 24 36](https://cloud.githubusercontent.com/assets/445106/23362988/a37e34ee-fcf8-11e6-8be4-71a92377c78c.png)

**Comment by JohannesHoppe** [comment]
Sure, and additionally I would like to see something like:

----

# BREAKING CHANGES
* core: `OpaqueToken` is now deprecated, use `InjectionToken` instead.

and maybe:
OpaqueToken will be removed / not removed in XXX

**Comment by wesleycho** [comment]
Deprecation isn't a breaking change, and should not be listed as such - maybe deprecated fields could have more prominent notice, but it should not be shoehorned where it does not belong.

**Comment by JohannesHoppe** [comment]
This is an absolutely valid point. I'll close the issue.

**Comment by JohannesHoppe** [comment]
I scrolled down a little bit in the changelog and found a section [deprecation](https://github.com/angular/angular/blob/master/CHANGELOG.md#deprecation) for 4.0.0-beta.3.
Which means we already have a good way for a  prominent notice.
My suggestion is now the following:

# DEPRECATION

* deprecate `OpaqueToken`. Use `InjectionToken` instead.

**Comment by vicb** [comment]
@PascalPrecht the change you mention is a different thing.

**Comment by IgorMinar** [comment]
To summarize, there request is to rollup all beta changelogs especially the breaking changes and deprecations sections into on that will be part of the final 4.0.0 changelog. I agree.

cc: @StephenFluin

**Comment by vicb** [comment]
I think the only request to document the deprecation when it occurs. 
I don't think release notes are a place to add docs, may be a migration guide would be more appropriate - and we could start creating it along the way.

**Comment by JohannesHoppe** [comment]
:+1:
