### ISSUE TITLE
Can't pass class instance as context to ngTemplateOutlet

### ISSUE THREAD

**Issue by guojenman** [angular/angular#14778]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When passing a class instance as the context for ngOutletTemplate, I get a run-time error "_Cannot read property 'index' of null_". Passing a regular plain object seems to be OK.

**Expected behavior**
I should be able to use a class instance as context for ngOutletTemplate (it worked up until  4.0.0-beta.8)

**Minimal reproduction of the problem with instructions**
rc.1 - does not work
http://plnkr.co/edit/KMImWNCd4D4tZjNUzNvn?p=preview
beta-8 works
http://plnkr.co/edit/JbtlWLri7yl9TpQPaooK?p=preview

**What is the motivation / use case for changing the behavior?**
For templates that are internal using and not for public API, it's advantageous to be able to pass the entire class instance to the templates and let the templates decide what it needs from the instance. We still define what the templates access via the "let-" declarations.

**Please tell us about your environment:**
N/A

* **Angular version:** 4.0.0-rc.1

* **Browser:** All

**Comment by vicb** [comment]
Thanks for reporting the issue is

```
export function isComponentView(view: ViewData): boolean {
  return view.component === view.context && !!view.parent;
}
```

Pb is that the context is the component in your example. Expect a fix in the next release.
