### ISSUE TITLE
style() from animations is incompatible with AOT & metadata collector

### ISSUE THREAD

**Issue by alxhub** [angular/angular#14774]
In 4.0.0-rc.1, the `style()` DSL function from animations is not statically analyzable, hence it fails AOT compilation.

> Error encountered resolving symbol values statically. Calling function 'style', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

https://github.com/angular/angular/blob/830393d234d2b7a41a5f1db375613ffa8dde97c3/modules/%40angular/animations/src/animation_metadata.ts#L341

**Comment by Delagen** [comment]
https://github.com/angular/angular/issues/14728#issuecomment-282503789

**Comment by filoxo** [comment]
Just as an additional observation, reverting to importing the animation methods from `@angular/core` gets AOT to build successfully but animations do not work (polyfill is still loaded).

**Comment by DzmitryShylovich** [comment]
@filoxo https://github.com/angular/angular/pull/14775 the fix is comming
