### ISSUE TITLE
MockBackend verifyNoPendingRequests() method not working?

### ISSUE THREAD

**Issue by sinedied** [angular/angular#14777]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`verifyNoPendingRequests()` does not throw an exception if a connection has not received a response.
**Expected behavior**
`verifyNoPendingRequests()` should throw an exception if any connection has not received a response.

**Minimal reproduction of the problem with instructions**
Here is a minimal example, base on the doc examples:
```ts
import 'rxjs/add/operator/toPromise';
import { Injectable } from '@angular/core';
import { fakeAsync, tick, inject, TestBed } from '@angular/core/testing';
import { BaseRequestOptions, Http } from '@angular/http';
import { MockBackend } from '@angular/http/testing';

@Injectable()
class HeroService {
  constructor(private http: Http) {}

  getHeroes(): Promise<String[]> {
    return this.http.get('myservices.de/api/heroes')
      .toPromise()
      .then(response => response.json().data)
      .catch(e => this.handleError(e));
  }

  private handleError(error: any): Promise<any> {
    console.error('An error occurred', error);
    return Promise.reject(error.message || error);
  }
}

describe('MockBackend HeroService Example', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        MockBackend,
        BaseRequestOptions,
        {
          provide: Http,
          useFactory: (backend: MockBackend, defaultOptions: BaseRequestOptions) => {
            return new Http(backend, defaultOptions);
          },
          deps: [MockBackend, BaseRequestOptions]
        },
        HeroService
      ]
    });
  });

  beforeEach(inject([HeroService, MockBackend], (heroService: HeroService, mockBackend: MockBackend) => {
    this.heroService = heroService;
    this.backend = mockBackend;
    this.backend.connections.subscribe((connection: any) => this.lastConnection = connection);
  }));

  it('getHeroes() should return some heroes', fakeAsync(() => {
    let result: String[];
    this.heroService.getHeroes().then((heroes: String[]) => result = heroes);
    tick();
    this.backend.verifyNoPendingRequests(); // does not throw :-(
  }));
});
```

**Please tell us about your environment:**
Sample project based on @angular/cli: 1.0.0-rc.0

* **Angular version:** 2.4.8

* **Browser:** [phantomjs]
 
* **Language:** [TypeScript 2.2.0]

* **Node (for AoT issues):** `node --version` =   7

**Comment by Wykks** [comment]
Sorry to be "that guy" but... Any news on this ? Or nobody actually write test with http ?
How can you be sure that your service works as expected without `verifyNoPendingRequests` ?

**Comment by dscheerens** [comment]
Yup, just ran into this issue as well.

**Comment by katagaStyle** [comment]
Any news on this topic??

**Comment by Wykks** [comment]
A new httpClient just landed (https://github.com/angular/angular/pull/17996) since 4.3.0-rc.0. I'll see if this scenario is now correctly handled.

**Comment by mmc41** [comment]
Status?

**Comment by sinedied** [comment]
I did not tried with the new HttpClient, but `verifyNoPendingRequests` still does not work as expected with `4.3.6`.

**Comment by Wykks** [comment]
Sorry forgot to post, it works fine with the new HttpClient !

**Comment by alxhub** [comment]
Closing as this is obsolete (it concerns `@angular/http` which has been removed in favor of `@angular/common/http`).
