### ISSUE TITLE
equalsTo validator could also expect controls

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#14770]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We can't add the validator to a control before adding it to the group:

    const f1 = new FormControl('a');
    const f2 = new FormControl('a', Validators.equalTo('f1')); // breaks
    const group = new FormGroup({f1, f2});

This breaks with `Cannot read property 'get' of undefined`, see repro in [this plunker](http://plnkr.co/edit/aAESRPi62JkT5nz8E95F?p=preview)

**Expected behavior**
We should be able to pass a control directly

    const f1 = new FormControl('a');
    const f2 = new FormControl('a', Validators.equalTo(f1));
    const group = new FormGroup({f1, f2});

Edit: #14771 is an attempt to achieve this

**Minimal reproduction of the problem with instructions**
Repro in [this plunker](http://plnkr.co/edit/aAESRPi62JkT5nz8E95F?p=preview)

* **Angular version:** 4.0.0-rc.1

**Comment by kara** [comment]
As the equalsTo validator is being removed in https://github.com/angular/angular/pull/15050, closing this issue.
