### ISSUE TITLE
ERROR in Illegal State: literal maps should have been converted into functions

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#14782]
**I'm submitting a bug report**

When a template includes an assignment such as `<button (click)="title = {}"></button>`, AOT Compilation Fails.

**Current behavior**
AOT Compilation fails with the error:
 `ERROR in Illegal State: literal maps should have been converted into functions`

**Expected behavior**
AOT Compilation Succeeds without error

**Minimal reproduction of the problem with instructions**
See reproduction here: 
https://github.com/StephenFluin/literal-error-repro

Clone the project, `npm install`, `ng build -prod`

* **Angular version:** 4.0.0-rc.1
I also tested with the latest master.

* **Node (for AoT issues):** `node --version` =   v7.6.0

**Comment by splintercode** [comment]
Not sure if this is related seems like a similar error but with the Angular CLI RC.0 and Angular 4 RC1 
I get the following error:

`Error: Illegal State: literal arrays should have been converted into functions`

I haven't been able to narrow down what is causing this specifically yet.

**Comment by pablocespedes** [comment]
Hello,

I am getting this issue in my application on running `ng build-c=production` using AOT compilation. The current angular version that I have is 6.1.0, angular CLI 6.1.5 in the project and in my machine.

Any ideas why I am getting this issue with this new version?

```
ERROR in : Error: Illegal State: literal arrays should have been converted into functions
 at _AstToIrVisitor.visitLiteralArray....
```

**Comment by fabioformosa** [comment]
I've just got the same error migration from angular 6.0 to angular 7.0
