### ISSUE TITLE
TSICKLE: Option to remove decorators entirely

### ISSUE THREAD

**Issue by hansl** [angular/angular#14786]
Currently the `annotationsAs` option has 2 options: `static fields` or `decorators`. In order to minimize the size of application bundles in AOT we need a third option: `remove` (alternative names could be `none` or `drop`).

For libraries either options can't work for deploying because they both keep the metadata and publish it. In order for libraries to support both JIT and AOT without deploying templates in AOT, they'd need to:

1. Release a bundle for JIT:
    1. use `ngc` to build the JavaScript with `annotationsAs: "static fields"`
    1. use bundler-of-choice to build a UMD bundle which contains annotations
1. Release code compatible with AOT:
    1. use `ngc` to build JavaScript and `.metadata.json` files, with `annotationsAs: "remove"` so that the JavaScript files don't contain the annotations at all.
1. Publish both UMD bundle for JIT, and single files for AOT.

This is the most AOT/JIT friendly way to publish libraries on npm. Currently it's impossible because `ngc` does not support removing decorators entirely.

**Comment by alexeagle** [comment]
This is not possible with tsickle today, because the decorator lowering is a pre-processing step (it removes the decorators before TypeScript loads the files) and then the metadata collector doesn't find them. We need to re-implement tsickle as an emit pipeline transform so the decorators are still in the AST that the collector visits.

**Comment by trotyl** [comment]
Fixed by Ivy as tsickle no longer matters any more.

**Comment by JoostK** [comment]
In Ivy, any Angular decorator is removed during in AOT mode.
