### ISSUE TITLE
Using webpack to create angular1 and angular2 hybrid app throw upgrade static error

### ISSUE THREAD

**Issue by atul221282** [angular/angular#14787]
**I'm submitting a ...**  (check one with "x")
`BUG

**Current behavior**
Upgrade static node module throw syntax error when using angular1 and angular2 together. Using systemjs loader it works fine

**Expected behavior**
upgrade static should not throw any syntax error it should be compatible with both webpack and systemjs

**Minimal reproduction of the problem with instructions**
[http://stackoverflow.com/questions/42486090/using-webpack-to-create-angular1-and-angular2-hybrid-app-throw-upgrade-static-er]

**What is the motivation / use case for changing the behavior?**
I am trying to use existing angular1 one app and creating new and changing old functionality to new angular2

**Please tell us about your environment:**
OS - Windows 10, IDE - Visual Studio 2015, Package Manager - NPM

* **Angular version:** 2.0.X
angular 2.4.6 thats what I got in my package.json

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web 
Was testing in Chrome and it was failing there
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version`
v7.2.0

**Comment by gkalpak** [comment]
There isn't enough info to further investigate the problem or verify that it has been fixed in recent versions. Also, the linked StackOverflow question has an accepted answer.

Based on that, I am going to close this issue, but feel free to open a new one (providing a reproduction) if the problem persists.
