### ISSUE TITLE
angular 4.0.0-rc.1 breaks animation

### ISSUE THREAD

**Issue by derekshi** [angular/angular#14783]
After I upgrade from angular 4.0.0-beta.8 to 4.0.0-rc.1. All animations are not working anymore. Not animation hooks are being called as well.

**Comment by Toxicable** [comment]
did you read the change log?https://github.com/angular/angular/blob/master/CHANGELOG.md#animation-package

**Comment by DzmitryShylovich** [comment]
Did you import `BrowserAnimationsModule` from `@angular/platform-browser/animations` in your root NgModule? Also imports from `@angular/core` were deprecated, use imports from the new package `import { trigger, state, style, transition, animate } from '@angular/animations';`.

**Comment by IgorMinar** [comment]
Can you please check that you followed https://github.com/angular/angular/blob/master/CHANGELOG.md#installing-rc1

If the issue still persists please create a new issue and describe the steps to reproduce your problem (animations work in all of our projects, so the issue is not widespread)
