### ISSUE TITLE
The Directive selector doesn't work at runtime 

### ISSUE THREAD

**Issue by Bretto** [angular/angular#14781]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I would like to add some behaviour via a directive to an element when a class is present.
In my current test the selector is the class:"next". The h5 that have the class on bootstrap of the app is being processed by the directive, but the h5 to which I apply to class at runtime is not beeing process by the directive. Why ?

I have created a plunkr that illustrate my problem:
http://plnkr.co/edit/fpgZKNLQcRvaer0SyZzC?p=preview

**Expected behavior**
I would expect the selector to work at runtime

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/fpgZKNLQcRvaer0SyZzC?p=preview

**What is the motivation / use case for changing the behavior?**
using the directive at runtime

**Please tell us about your environment:**
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.31]
node: 7.0.0
os: linux x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome XX
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 

* **Node (for AoT issues):** `node --version` =   
None

**Comment by DzmitryShylovich** [comment]
yeah, it's a known limitation https://github.com/angular/angular/issues/11716

**Comment by Bretto** [comment]
Thanks

**Comment by vicb** [comment]
This is by design, directives are resolved at compile time. This has never worked and will never work.

**Comment by Bretto** [comment]
If you look a #11716 is it still a bug or a feature by design ?  Is it the class selector that is causing the closed status of the issue ? Is the run-time aspect of the Directive still consideration ? Thank for your time.

**Comment by vicb** [comment]
still by design.

`[attr.foo]` will match where `[foo]` or `foo` match regardless the value (ie if the value is null and the attribute is removed the directive will still be active).

If you need to enable a directive `<tag [enableMyDirective]="boolValue" [class.addThisWhenActive]="boolValue"></tag>` (this is one of many options, the directive could also automatically add a class, ...)
