### ISSUE TITLE
404 in Angular documentation for UrlMatcher

### ISSUE THREAD

**Issue by nikhildev** [angular/angular#14791]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The section for UrlMatcher at https://angular.io/docs/ts/latest/api/router/index/UrlMatcher is throwing a 404 page

**Expected behavior**
It should contain the documentation for UrlMatcher

**Minimal reproduction of the problem with instructions**
Visit https://angular.io/docs/ts/latest/api/router/index/UrlMatcher

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 56.0.2924.87 (64-bit)

**Comment by DzmitryShylovich** [comment]
Please re-open it on https://github.com/angular/angular.io/issues
