### ISSUE TITLE
Benchmark the cost of decorators

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1479]
We intend to use decorators as location markers for tooltips. For that to scale to tables with thousands of cells the cost of decorator must be negligible.

**Comment by matanlurey** [comment]
+1

**Comment by tbosch** [comment]
A component can also show a tooltip for its element without an additional
decorator...

**Comment by matanlurey** [comment]
@tbosch, can you explain? In this case, tooltip is implemented through an external service. E.g.

<md-button md-tooltip="Click to save">Save</md-button>
