### ISSUE TITLE
Fail to upgrade to 4.0.0-rc.1 

### ISSUE THREAD

**Issue by julianobrasil** [angular/angular#14795]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Just tried to execute the suggested command line to upgrade Angular: 
`npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@next --save`

I brings up the following error message (translated from portuguese):
```
At line:1 character:29
+ npm install @angular/{common,compiler,compiler-cli,core,forms,http,pl ...
+                             ~
Missing argument in the parameters list.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument
```

**Expected behavior**
Angular upgrade to 4.0.0-rc.1

**Minimal reproduction of the problem with instructions**
`npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@next --save`

**What is the motivation / use case for changing the behavior?**
Try out 4.0.0-rc.1 in a existing project

**Please tell us about your environment:**
@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: win32 x64
@angular/cli: 1.0.0-rc.0
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/compiler-cli: 2.4.8

* **Angular version:** 2.4.8 (angular core)

* **Browser:** not a browser issue
 
* **Language:** Typescript 2.3.0-dev.20170228

* **Node (for AoT issues):** `node --version` =  6.9.5

**Comment by DzmitryShylovich** [comment]
Just add in you `package.json`:
```
"dependencies": {
    "@angular/common": ">=4.0.0-beta <5.0.0",
    "@angular/compiler": ">=4.0.0-beta <5.0.0",
    "@angular/core": ">=4.0.0-beta <5.0.0",
    "@angular/forms": ">=4.0.0-beta <5.0.0",
    "@angular/http": ">=4.0.0-beta <5.0.0",
    "@angular/platform-browser": ">=4.0.0-beta <5.0.0",
    "@angular/platform-browser-dynamic": ">=4.0.0-beta <5.0.0",
    "@angular/router": ">=4.0.0-beta <5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },
```

**Comment by julianobrasil** [comment]
@DzmitryShylovich I updated my dependencies. I worked. Now the compiler is complaining about NgControl. Aparently something changed about it. Is it deprecated or replaced for something else?

**Comment by julianobrasil** [comment]
My mistake. It was just a wrong import statement. But now I see a lot of messages like "ERROR in ./src/$$_gendir/app/app.component.ngfactory.ts"

**Comment by julianobrasil** [comment]
The first compile error is different from the others (see bellow: it's a router_config_loader error). From the second error and on, they are all similar, just changing the package part (core, common etc).
 
```
ERROR in Could not resolve module @angular/router/src/router_config_loader

ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve '../../../@angular/core' in 'E:\xxxxx\src\$$_gendir\app'
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 12:0-50
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by BaconLord** [comment]
@julianobrasil got the same problem `Could not resolve module @angular/router/src/router_config_loader`
Did you resolve the issue?

**Comment by aitboudad** [comment]
angular now use Flat ES Modules which means using `@angular/router/src/router_config_loader` path is not possible anymore

Before:

```ts
import { ROUTES } from "@angular/router/src/router_config_loader";
```

After:
```ts
import { ROUTES } from "@angular/router";
```

**Comment by julianobrasil** [comment]
@BaconLord Nop. I saw this other issue #14513 that shows an error message pointing to problems relating to ngfactory.ts, but found nothing about this particular issue.

@aitboudad so is an issue with the compiler? I don't have any import like @angular/router/src/router_config_loader.

**Comment by aitboudad** [comment]
@julianobrasil check your third-party dependencies, for example [ui-router-ng2](https://github.com/ui-router/ng2/blob/master/src/uiRouterNgModule.ts#L13)

**Comment by DuncanLewis** [comment]
@aitboudad @julianobrasil Try disabling MaterialModule, just disabled it and worked again for me.

**Comment by julianobrasil** [comment]
@aitboudad, unfortunatly my project is almost 100% using angular.io products (Angular + Angular Material 2).

The 'almost' is because I use [ng2-pagination](http://michaelbromley.github.io/ng2-pagination/#/), but so far as I know it doesn't use any routing feature.

**Comment by julianobrasil** [comment]
@DuncanLewis Tried it here, but still got the error. I'll try disabling material after lunch.

**Comment by Delagen** [comment]
@julianobrasil if you use thirdparty libraries even from author of framework you often cannot to upgrade core to latest version because of dependent library does not updated synchronously. So read docs, changelogs (breaking changes parts read two times), and of cause source as the one source of truth. And simply wait for dependent library be ready for new version of core

**Comment by julianobrasil** [comment]
@Delagen you're right. This is the case with angular and material (same umbrella project, but not at the same point in evolution). I'm gonna wait for the material team (not blaming material for the problem, but there are material error messages related to it's use of <template>).

**Comment by intellix** [comment]
Was wondering where this was coming from. I did a grep inside my project and the only instance of router_config_loader was inside angular/compiler-cli:
```ts
node_modules/@angular/compiler-cli/src/ngtools_impl.js:var ROUTER_MODULE_PATH = '@angular/router/src/router_config_loader';
```

**Comment by aitboudad** [comment]
you should make sure to update `@angular/compiler-cli` too in your package.json as the latest version 
contains 
```ts
ROUTER_MODULE_PATH = '@angular/router';
```

**Comment by robwormald** [comment]
@Delagen that's what we're explicitly trying to avoid, actually. There should not be breakages from existing component libraries from 2.4.x when upgrading to 4.0. 

The original issue here appears to be resolved. Please open a new issue if you can narrow it down to a specific bug.

**Comment by julianobrasil** [comment]
Opened new issue  #14817

**Comment by Delagen** [comment]
@robwormald As someone said at angular 2 final launch event "we will try to not break the code more than once every 6 months" (or something similar, cannot find video :sad: )
Product cannot evolve without breaking changes. So it's normal that major upgrade will break your code. But upgrade process must be simple if you read changelogs and follow product guidelines.
