### ISSUE TITLE
Defining styleUrls throws "Expected 'styles' to be an array of strings"

### ISSUE THREAD

**Issue by ssougnez** [angular/angular#14799]
**I'm submitting a ...**
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I followed this "https://angular.io/docs/ts/latest/guide/webpack.html" and I have an issue when I define the "styleUrls" property of the "Component" decorator, whatever the component. When I do so, I get the error "Expected 'styles' to be an array of strings" in the "Google Developer Toolbar". 

The things that differ between my source code and this one are versions and the usage of karma/phantom (I don't use them). However, I also tried with the same version as the tutorial and I have the same behaviour. For now, the only way to get rid of this behaviour consist of not using "styleUrls" but an "import" statement (causing the css to be bundled with the others).

**Expected behavior**
The CSS should be inlined in the JS (I guess) without causing any issue.

**Minimal reproduction of the problem with instructions**
I just followed this: https://angular.io/docs/ts/latest/guide/webpack.html

**Please tell us about your environment:**

* **IDE:**
Visual Studio Code 1.9 (Windows 10)

* **Angular version:**
2.4.8

* **Browser:** 
Chrome 56
IE 11
 
* **Language:**
TypeScript 2.2.1

* **Node (for AoT issues):** 
Node 7.4.0

* **Package manager:** 
Yarn 0.20.3

* **Tools:** 
webpack 2

**Comment by DzmitryShylovich** [comment]
please add a reproduction

**Comment by ssougnez** [comment]
Is it possible to use webpack with http://plnkr.co?

**Comment by DzmitryShylovich** [comment]
nope

**Comment by ssougnez** [comment]
So what can I say more than "_I just followed this: https://angular.io/docs/ts/latest/guide/webpack.html_" ? I really just followed that tutorial and got the issue. If it helps, I can join a light version of my app with just the necessary to my initial post ?

**Comment by lazarljubenovic** [comment]
> "Expected 'styles' to be an array of strings"

This is a TypeScript error meaning you didn't give `styles` an array of strings, but something else. Maybe you accidentally passed in just a string? 

Bad:
```js
styles: `p { color: red }`,
```

Good:
```js
styles: [`p { color: red}`],
```

Anyway, without a proper repro or even at least some sample code, this issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests; please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

**Comment by ssougnez** [comment]
Okay, I will. 

However, I'm not using the "styles" property but only the "styleUrls" one with a value like "[ './my-css.css' ]". Anyway, maybe I did something wrong and am the only one concerned. 

Thanks

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
