### ISSUE TITLE
DatePipe.transform (from angular/common) returns wrong results

### ISSUE THREAD

**Issue by MaklaCof** [angular/angular#14792]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report =>I did
[ ] feature request
[ ] support request
```

**Current behavior**
This is my code:
```
constructor(private datepipe: DatePipe) { }
....
const d = new Date(0, 0, 0, 0, 0, 9);
this.datepipe.transform(d, "hh:mm:ss")    //returns 12:00:09
this.datepipe.transform(d, "yyyy-MM-dd")  //returns 1899-12-31.  //notice dot at the end
```
Also a screenshot with wrong values:
![chrome_2017-02-28_09-09-51](https://cloud.githubusercontent.com/assets/1589573/23396781/bec8e544-fd95-11e6-8cc2-08c1dace3084.png)

**Expected behavior**
```
this.datepipe.transform(d, "hh:mm:ss")    //returns 00:00:09   //not 12 for hours
this.datepipe.transform(d, "yyyy-MM-dd")  //returns 1899-12-31.  //without dot at the end
```

**Minimal reproduction of the problem with instructions**
[Use this plunkr](http://plnkr.co/edit/9vwEUv063gumvSBvgtVW).

**Please tell us about your environment:**
[JavaScript Services](https://github.com/aspnet/JavaScriptServices).
and
[aspnetcore-spa-template](https://www.npmjs.com/package/generator-aspnetcore-spa).

* **Angular version:** 2.0.X
2.4.4. Yes, I think this is still a bug.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome for sure, probably others too.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Looks like `Intl` bug in Chrome/Firefox.
Works fine in IE/Edge

**Comment by vicb** [comment]
4.x and prior were based on the Intl API.

We have moved away from using the API on 5.x+.
