### ISSUE TITLE
Compiler emits `null as any` in places where call takes `undefined`

### ISSUE THREAD

**Issue by mprobst** [angular/angular#14798]
Angular's compiler emits code such as:

```ts
export function View_VideoAnnotation_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)), ...)
```

Those arguments of `ɵeld` are actually defined as `Something|undefined` - the compiler could easily drop the cast for the `null` values if it just passed `undefined` instead.

This would be nice to have as it'd fix a whole bunch of legitimate warnings when compiling apps with Closure Compiler.

**Comment by JoostK** [comment]
The typings of `elementDef` have been adjusted somewhere in the past to include the `null` type as appropriate. Moreover has the generated code been changed completely in Ivy.
