### ISSUE TITLE
FormArray get values

### ISSUE THREAD

**Issue by nchizhov** [angular/angular#14794]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ReactiveForm with FormArray error with get form.value

**Expected behavior**
```this.form.value``` shold show form values.
But if I try to get ```this.form.controls['phones'].value``` I get correct array data

**Minimal reproduction of the problem with instructions**
For example code of form:
```
form: FormGroup;
constructor(private _formBuilder: FormBuilder) {
    this.form = this._formBuilder.group({
      phones: this._formBuilder.array([])
    });
  }

open() {
    (<FormArray>this.form.controls["phones"]).push(this._formBuilder.control(['XXXXXXXX']));
}

submit() {
   console.log(this.form.value);
}
```

**Please tell us about your environment:**
OS: Windows 7 SP1 64 bit
IDE: JetBrains PhpStorm 2016.3.2
Angular-Cli 1.0.0-beta.32.3

* **Angular version:** 2.4.8
```
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
```

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by DzmitryShylovich** [comment]
please add a plunkr

**Comment by nchizhov** [comment]
Plunkr sample: https://plnkr.co/edit/6h1ezEjSQ8Chvrb3hABt?p=info

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/H0Efof2rHrWYKvySKUP1?p=preview

**Comment by nchizhov** [comment]
OK. Thank you. But I need output like:
```Output: { "phones": [  "XXXXXX", "XXYYYYY" ] }```
Not as array in array

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/IedlDD3rRCdxIBU7xJbt?p=preview

**Comment by nchizhov** [comment]
Thank you
