### ISSUE TITLE
Render Layer cleanup

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1480]
Open TODOs:

Discuss
- [ ] why does `EventManager` use `VmTurnZone`? Should we then move it to `src/services`?
- [ ] should `src/services/xhr` stay there, although it's mostly an internal service?

Improve performance: See #1316

Missing (smaller) refactorings:
- [ ] remove `ProtoView.bind*` methods and move the logic into `ProtoViewFactory`
- [x] align `render/test_bed` with usual `test_lib/test_bed` / use at least the `test_injector` in the integration tests
- [ ] use render layer for `class` directive as well (wait for DirectiveRef to land so that we get the bound element index)
- [x] only pass `selector` to `renderer.createRootView` (see https://github.com/angular/angular/issues/1541)

Missing unit tests:
- [ ] core/compiler/proto_view_factory
- [ ] core/compiler/view_manager_util
- [ ] core/compiler/view_container_ref
- [ ] render/dom/dom_renderer

Docs:
- [ ] more inline docs and mark public entries via `@publicModule`

**Comment by mhevery** [comment]
Can you update this bug with current status.

**Comment by tbosch** [comment]
I am working on ramping up the unit tests.
