### ISSUE TITLE
Incorrect upgrade instructions in changelog for Windows users

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular#14809]
http://stackoverflow.com/questions/42516188/cannot-upgrade-a-existing-angular-cli-project-to-angular-4-rc1

**Comment by DzmitryShylovich** [comment]
This issue tracker is not suitable for support requests.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by rahulrsingh09** [comment]
This is a issue i feel as the npm command itself is not working nothing to dp with the code as of now

**Comment by Delagen** [comment]
As I know, this is bash extension command line. It not supported on windows

**Comment by DzmitryShylovich** [comment]
@rahulrsingh09 https://github.com/angular/angular/issues/14795#issuecomment-283013156

**Comment by rahulrsingh09** [comment]
So as of now i need to install all the dependencies manually or i can updatr in the package.json as mentioned . These are the only two ways possible. But i think using this will break a lot of things in the app

**Comment by IgorMinar** [comment]
The problem is that the command we list in the changelog only works on unix-based systems. The `{ }` substitution won't work on windows. we should update the changelog with both versions.

@StephenFluin could you own this one plz?
