### ISSUE TITLE
site angular.io is not available in belarus.

### ISSUE THREAD

**Issue by siarheikwork** [angular/angular#14800]
tracert angular.io

Tracing route to angular.io [151.101.65.195]
over a maximum of 30 hops:

  1     1 ms    <1 ms    <1 ms  192.168.1.1
  2     1 ms     1 ms     1 ms  192.168.0.1
  3     3 ms     4 ms     4 ms  37.17.20.227
  4     4 ms     2 ms     2 ms  178.163.135.34
  5     5 ms     4 ms     7 ms  178.163.163.105
  6    22 ms     3 ms    23 ms  185.32.225.229
  7    28 ms    27 ms    28 ms  ae2.RT.HWE.LBD.PL.retn.net [87.245.245.97]
  8    31 ms    28 ms    43 ms  ae3-4.RT.EQX.FKT.DE.retn.net [87.245.232.233]
  9     *        *        *     Request timed out.
 10    37 ms    39 ms    35 ms  151.101.65.195

Trace complete.

**Comment by DzmitryShylovich** [comment]
Please re-open it on https://github.com/angular/angular.io/issues
