### ISSUE TITLE
Compiler-generated factory doesn't call 'new', which fails for ES6.

### ISSUE THREAD

**Issue by EricABC** [angular/angular#14816]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This line [here](https://github.com/angular/angular/blob/1ece7366c8b67f387fbe13f8d128c19f4c50dd19/modules/%40angular/compiler/src/output/class_builder.ts#L27) calls '.callFn'.  In a unit test, the DynamicTestModule module.ngfactory.js output will be ```jit_NgModuleInjector0.call(this, parent,[],[]);```.  This fails because NgModuleInjector is a class and needs to be called with 'new'.  

**Expected behavior**
I believe '.instantiate' instead of '.callFn' needs to be called in some cases.

**Minimal reproduction of the problem with instructions**

See the plunk in #14808, however that issue currently blocks reproduction of this issue.  If you modify the ```useFactory: () => ...``` to ```useFactory: function (...``` to bypass that issue, this issue should be the next one you hit.  I tried to put up a gist for a modified compiler.js, but github doesn't seem to like the theta char used for the internal exports.

* **Angular version:** 4.0.0-rc.1

* **Browser:** [chrome]
 
* **Language:** [ES6]

**Comment by tbosch** [comment]
To be clear, this is the place where we call the super constructor...

**Comment by tbosch** [comment]
Did this work in 2.x? As far as I know, our jit mode never worked with ES6 yet...

**Comment by EricABC** [comment]
Yup, we were at 6 and dropped to 5 for ng4. I think if I recall JIT output es5 but worked fine with eS6, whereas AOT is outputing full es6 with class and super calls. It's not devastating, but we do miss a few things like generators.

Perhaps these two should be combined into one tracking JIT ES6 support, but duplicating now for completeness.

**Comment by tbosch** [comment]
This is the same underlying problem / workaround as in https://github.com/angular/angular/issues/14808#issuecomment-286265650

**Comment by tbosch** [comment]
Closing this and tracking ES6 support in #15127.
