### ISSUE TITLE
Angular 4.0.0-rc.1 Exit animation (* => void) is not called

### ISSUE THREAD

**Issue by derekshi** [angular/angular#14813]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => After upgrade from beta.8 to rc.1, Exit animation is not called
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have animation defined in template as follows:
```
<div *ngFor="let toast of toasts" [@inOut]="animate" (@inOut.done)="onAnimationEnd($event)">
{{toast.name}}
<div>
```

animation decoration as:
```
 animations: [
    trigger('inOut', [
      state('flyRight', style({opacity: 1, transform: 'translateX(0)'})),
      transition('void => flyRight', [
        style({
          opacity: 0,
          transform: 'translateX(100%)'
        }),
        animate('0.2s ease-in')
      ]),
      transition('flyRight => void', [
        animate('0.2s 10 ease-out', style({
          opacity: 0,
          transform: 'translateX(100%)'
        }))
      ]), ....
```

The entering animation `void => flyRight` works as expected, but no animation for `flyRight => void` at all when a `toast` is removed from `toasts` array.

**Comment by josiah1888** [comment]
Can confirm, just had the same problem

**Comment by Bretto** [comment]
the :leave animation are not working anymore aswell...

**Comment by nicky-lenaers** [comment]
Can't get `:leave` and `:enter` to work as well.

**Comment by matsko** [comment]
OK I've been able to reproduce the issue. Now I'm going into JS detective mode.

**Comment by matsko** [comment]
@derekshi the problem with the code here is that `0.2s 10 ease-out` is invalid (the `10` is missing a timing value), but for some reason the errors are not reported properly. This is definitely a problem with how Angular does things.

@nicky-lenaers @Bretto @josiah1888 can you guys please provide your own failing examples with enter/leave animations?

**Comment by gilbertowa** [comment]
@matsko I have a similar problem that @derekshi, but I don't use aditional value: 

 ```
animations: [
    trigger('shortcutState', [
      state('out', style({ height: 0 })),
      state('in', style({ height: '*' })),
      transition('out => in',[ animate('250ms ease-out')]),
      transition('in => out', [animate('250ms 300ms ease-in ')])
    ]),
    trigger('inOut', [
      state('flyRight', style({opacity: 1, transform: 'translateX(0)'})),
      transition('void => flyRight', [
        style({
          opacity: 0,
          transform: 'translateX(100%)'
        }),
        animate('0.2s ease-in')
      ])])
  ]
```

**Comment by josiah1888** [comment]
@matsko I don't have a plunker for you, but here is my failing animation

```
export const slideInDownAnimation = trigger('routeAnimation', [
  state('in',
    style({
      opacity: 1,
      transform: 'translateX(0)'
    })),
  transition(':enter', [
    style({
      opacity: 0,
      transform: 'translateX(-100%)'
    }),
    animate('0.5s ease-in')
  ]),
  transition(':leave', [
    animate('0.5s ease-out',
      style({
        opacity: 0,
        transform: 'translateX(100%)'
      }))
  ])
]);
```

Also tried to simplify and use the exact same animation as the `:enter` one which is working
```
export const slideInDownAnimation = trigger('routeAnimation', [
  state('in',
    style({
      opacity: 1,
      transform: 'translateX(0)'
    })),
  transition(':leave', [
    style({
      opacity: 0,
      transform: 'translateX(-100%)'
    }),
    animate('0.5s ease-in')
  ])
]);
```

**Comment by matsko** [comment]
@josiah1888 I tried your example and it works if you use `*ngIf` instead of a router. It **does** fail with the router (no leave animations are fired).

**Comment by josiah1888** [comment]
@matsko @tbosch You guys are the best!

**Comment by matsko** [comment]
This issue is being looked at here: https://github.com/angular/angular/issues/15193

**Comment by nicky-lenaers** [comment]
Nice, which `rc` will this be available?
