### ISSUE TITLE
Are there plans to support source maps for core angular ts files

### ISSUE THREAD

**Issue by deli6z** [angular/angular#14814]
[x] feature request

**Current behavior**
It is not possible to debug angular typescript files

**Expected behavior**
Source maps should be created so that debugging is possible

**What is the motivation / use case for changing the behavior?**
It will be much easier to understand how the engine works if it is possible to debug it

Thank you!

**Comment by robwormald** [comment]
Sourcemaps are shipped with all stable releases. Sourcemaps not appearing in the RC release of 4.0.0 are a known issue documented in the changelog. Is this what you mean?

**Comment by deli6z** [comment]
Currently, if following the https://angular.io/docs/ts/latest/quickstart.html systemjs.config.js includes this line 
`'@angular/core': 'npm:@angular/core/bundles/core.umd.js',`

I guess my question is regarding how do I change it so that in browser I can debug actual angular/core typescript files rather than generated core.umd.js. 

Thank you
