### ISSUE TITLE
Fail to upgrade Angular from 2.4.8 to 4.0.0-rc.1

### ISSUE THREAD

**Issue by julianobrasil** [angular/angular#14817]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I updated angular:

```
npm install @angular/common@next @angular/compiler@next @angular/compiler-cli@next @angular/core@next @angular/forms@next @angular/http@next @angular/platform-browser@next @angular/platform-browser-dynamic@next @angular/platform-server@next @angular/router@next @angular/animations@next --save
```

Now there are some error messages like:

```
ERROR in Could not resolve module @angular/core/src/di/opaque_token

ERROR in multi script-loader!./~/crypto-js/crypto-js.js (...) Module not found: Error: Can't resolve 'script-loader'

Module not found: Error: Can't resolve 'webpack-dev-server/client

Module not found: Error: Can't resolve 'style-loader'

Module not found: Error: Can't resolve '@ngtools/webpack' 

Error: Can't resolve 'raw-loader'

```

**Expected behavior**

The 2.4.8 Angular project should run after upgraded to Angular 4.0.0-rc.1
**Minimal reproduction of the problem with instructions**

Same as said above
**What is the motivation / use case for changing the behavior?**

Upgrade Angular to 4.0.0-rc.1
**Please tell us about your environment:** Windows 10 64 bits

* **Angular version:** 2.4.8

* **Browser:** Issue Not related to browser
 
* **Language:**  Typescript 2.1.5 (tried also 2.2.1 and it gave me the same error)

* **Node (for AoT issues):**    
@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: win32 x64
@angular/animations: 4.0.0-rc.1
@angular/cli: error
@angular/common: 4.0.0-rc.1
@angular/compiler: 4.0.0-rc.1
@angular/compiler-cli: 4.0.0-rc.1
@angular/core: 4.0.0-rc.1
@angular/flex-layout: error
@angular/forms: 4.0.0-rc.1
@angular/http: 4.0.0-rc.1
@angular/material: error
@angular/platform-browser: 4.0.0-rc.1
@angular/platform-browser-dynamic: 4.0.0-rc.1
@angular/platform-server: 4.0.0-rc.1
@angular/router: 4.0.0-rc.1

Don't know why @angular/material, @angular/flex-layout and @angular/cli lines above has the 'error' word (this is the output of `ng --version` command), but I think it is not related to the problem - it has the same behavior with Angular 2.4 and the project runs. I'm using **@angular/Material 2.0.0-beta.2 flannel-papaya**,  **@angular/flex-layout 2.0.0-rc.1** and **@angular/cli 1.0.0-rc.0**

**Comment by DzmitryShylovich** [comment]
@julianobrasil does the issue is still persist with rc2 and the latest cli?

**Comment by julianobrasil** [comment]
Totaly solved. There are some warnings but related to material 2.
