### ISSUE TITLE
Custom Async Validation needs docs or improved developer ergonomics

### ISSUE THREAD

**Issue by the-destro** [angular/angular#14811]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
The docs are rather lacking around custom Async Validators and how they should be constructed. This has lead to a lot of different methods, some not always correct, appearing on blog posts etc. A complete example in the tutorial or cookbook would be great.

**Comment by DzmitryShylovich** [comment]
Please report doc issue on https://github.com/angular/angular.io/issues

**Comment by the-destro** [comment]
Re-opened as, 1) this has been an open issue on the docs repo since October and 2) A significant part of the issue is that the "developer ergonomics" of the API makes using it non-obvious.

**Comment by DzmitryShylovich** [comment]
> using it non-obvious

? 
async validator is just a function that returns Observable/Promise.

**Comment by the-destro** [comment]
Sure, but trying to do a common pattern of debouncing input is problematic.

**Comment by DzmitryShylovich** [comment]
it's a known issue https://github.com/angular/angular/issues/6895

**Comment by the-destro** [comment]
Also, one last bit, while it is straightforward to explain as a function that returns an observable, it is somewhat awkward to use in the context of DI. You can bind the this to the class, wrap it in a closure, etc.
