### ISSUE TITLE
Imperative View Shadow DOM integration

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1481]
Goals:

- [ ] Create imperative views which can use a `<content>` tag to project their light DOM.
- [ ] Provide light DOM for bootstrapped child components.

**Comment by naomiblack** [comment]
@tbosch can you update status on this? What remains TBD?

**Comment by tbosch** [comment]
Have not started to work on this. However, I don't think GT needs this (I talked to Ferhat...)
