### ISSUE TITLE
Feature Module Routes not inheriting from root routes.

### ISSUE THREAD

**Issue by paramsinghvc** [angular/angular#14810]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm using Angular 2 for my huge CRM dashboard project. So, I have created several modules for different pages of my app like `tickets` for tickets listing page and `tickets/:ticketId` for ticket details page. My Root Router Module looks something like this

```
const routes: Routes = [

    { path: 'login', component: LoginComponent },    
    {
        path: '',
        component: HomeComponent,
        canActivate: [LoginRouteGuard],
        children: [            
            { path: '', redirectTo: '/tickets', pathMatch: 'full' },
            { path: 'tickets', component: TicketsComponent },
        ]
    },    
]

@NgModule({
    imports: [RouterModule.forRoot(routes)],
    exports: [RouterModule]
})
```
And one of my feature module say `tickets/:ticketId` router looks like this
```
const routes: Routes = [    
    {
        path: 'tickets/:ticketId',
        component: HomeComponent,
        canActivate: [LoginRouteGuard],
        children: [
            { path: '', component: TicketDetailsComponent }
        ]
    }

]

export const TicketDetailsRouting = RouterModule.forChild(routes);
```

My HomeComponent has basically a sidebar and a right content holder as
```
<app-sidebar>
	<app-main-content>
                <router-outlet></router-outlet>
        </app-main-content>
</app-sidebar>
 ```

Now as you can see , in my feature module I had to specify the component 'HomeComponent' again, although I expected it to automatically pick up from my root module for '/' route. But I had to do this workaround finally. There was no other way. 
The problem with this approach is that, since I use `LoginRouteGuard` route guard for home component which makes an api call to test the JWT token stored in the localStorage. So, it gets called every time I navigate to my feature routes, hence adding to the latency. Not only this, I need to call an api when home loads like this

```
export class HomeComponent implements OnInit {

	title: String;
	constructor(private brandUserActions: BrandUserActions, private redux: NgRedux<any>) {
		this.title = "Abc";
	}

	ngOnInit() {
		this.redux.dispatch(<any>this.brandUserActions.getBrandInfo());
	}

}

```
This Api call is also getting called every time since the routes defined in the feature module is loading HomeComponent again.

**Expected behavior**

Expected behavior should be that the routes defined in the child or feature modules should respect the routes defined in the feature module. I mean, that should be the right purpose of using `forChild` in child router.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OS: Mac OS X (Sierra)
IDE: Sublime Text 3
Package Manager: npm

* **Angular version:** ^2.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 56.0
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript ~2.0.3

* **Node (for AoT issues):** `node --version` =   
v6.7.0

**Comment by DzmitryShylovich** [comment]
Please add a plunkr

**Comment by paramsinghvc** [comment]
@DzmitryShylovich I'm having a tight schedule. Can you please work up with the given information. I'll try to sneak time and add though.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by paramsinghvc** [comment]
@vicb It could be a serious bug which needs to be investigated. It's adversely impacting my app performance. Please reopen it.

**Comment by DzmitryShylovich** [comment]
@paramsinghvc it's not actionable without a repro anyway. Feel free to file a new issue when you have a plunkr or github repo that reproduces the issue.
