### ISSUE TITLE
A function returning observable is attached directly to the async pipe is called infinitely

### ISSUE THREAD

**Issue by bmrinal** [angular/angular#14826]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The async pipe calls the function infinitely upon which the pipe has been applied. 
```
<select class="form-control" style="width:100px">
            <option *ngFor="let course of api.getCourses() | async)">testing</option>
       </select>
```
The above results in infinite calls to api.getCourses(). However if I attach the async pipe to a component behavior, it works. 

In component:
```
`this.courses = api.getCourses()`
```
In template
```
<select class="form-control" style="width:100px">
            <option *ngFor="let course of courses | async">IND AS</option>
       </select>
```

**Expected behavior**
async pipe should only call the function once on which it is being applied.

**Minimal reproduction of the problem with instructions**
```
<select class="form-control" style="width:100px">
            <option *ngFor="let course of api.getCourses() | async)">testing</option>
       </select>`
```
Where api.getCourses() returns a observable.

**What is the motivation / use case for changing the behavior?**
A function returning observable is attached directly to the async pipe

**Please tell us about your environment:**
Windows 7, VS CODE, ng-cli

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by vicb** [comment]
This is the expected behavior as `api.getCourses()` could return a different value each time it is called.

As you describe `this.courses = api.getCourses()` is one way to fix this problem.
