### ISSUE TITLE
BUG: AOT:  Property access in template is restricted to host component.

### ISSUE THREAD

**Issue by dabalyan** [angular/angular#14829]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a variable `camps` of type `Array<ChildComponent>` in `ParentComponent` and use it with `ngFor` in `ParentComponent's` template ie: 
```
<li *ngFor="let camp of camps">
        {{ camp.someProperty }}
</li>
```

AOT compiler thinks that `someProperty` is supposed to be present on `ParentComponent` , 
ie: 

> Property 'someProperty' does not exist on type 'ParentComponent'.

while it should be checking it on `ChildComponent`.

**Expected behavior**
It should work.

**Minimal reproduction of the problem with instructions**
I'm using `https://github.com/AngularClass/angular2-webpack-starter`, if it helps in reproduction?

* **Angular version:** 2.4.6

* **Browser:** [NA]

 
* **Language:** [TypeScript 2.1.6]

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by DzmitryShylovich** [comment]
please add the github repo that we can clone that reproduces the issue

**Comment by dabalyan** [comment]
Thanks for prompt reply.

It's a private project, so I'll have to create a demo project for that. Give me some time, I'll try.

**Comment by DzmitryShylovich** [comment]
I think it's already fixed in 4.0 https://github.com/angular/angular/pull/14104

**Comment by dabalyan** [comment]
Sure looks like it's fixed. Closing it for now, because I don't have time to test with `4.0` yet. Is there any possibility of it coming in `2.x` `bug fix release` ? that would be nice.

**Comment by DzmitryShylovich** [comment]
nope, it's a breaking change
