### ISSUE TITLE
A router-outlet must be named "primary"

### ISSUE THREAD

**Issue by ssougnez** [angular/angular#14830]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If I have a single `router-outlet` with the attribute `name` defined on something else than "primary", routes other than the root one don't work.

**Expected behavior**
If I decide to put one or more named `router-outlet`, I should be able to name them the way I want.

**Minimal reproduction of the problem with instructions**
You can see this with this Plunker: http://plnkr.co/edit/1JLu7yvphW81YPHLxAsw

As such, it works well but if you renamed every occurrences of "primary" by anything else, it will be impossible to navigate via the link "Route".

**What is the motivation / use case for changing the behavior?**
The user shouldn't be forced to name a component with a specific name. In my case, I have a design with two `router-outlet`: "left-zone" and "right-zone", and I find it more clear than "primary" and "secondary".

**Please tell us about your environment:**

* **Angular version:** 2.4.8 (but applies also to 4.0.0-rc.1
* **Browser:** Chrome
* **Language:** TypeScript 2.2.1
* **Node (for AoT issues):** 7.4.0

**Comment by DzmitryShylovich** [comment]
You must have the outlet with the name `primary` on a template (if you don't specify the name it will be `primary` by default). Named outlets are **auxiliary**.

**Comment by ssougnez** [comment]
I get this but it's quite confusing. 

As I explained in the initial post, my main design is composed of two columns and for every route, some component have to be loaded in the left column, and some other components have to be loaded in the right one. I could, indeed, just put a unnamed `router-outlet` for the content and a named one for the aside, but if angular gives me the possibility to name the outlets, I should be able to name all my `router-outlet` without having issues. 

For example, my application has these routes:

```
export const AppRoutes: Routes = [
  {
    path: "",
    component: ComponentAggregatorComponent,
    data: { components: [ HomeSummaryComponent ] },
  },
  {
    path: "",
    component: ComponentAggregatorComponent,
    outlet: "aside",
    data: { components: [ DataSummaryComponent, AskSummaryComponent ] }
  },
  {
    path: "payments",
    component: ComponentAggregatorComponent,
    data: { components: [ PaymentComponent ] }
  },
  {
    path: "payments",
    component: ComponentAggregatorComponent,
    outlet: "aside",
    data: { components: [ AskSummaryComponent ] }
  }
];
```

It works fine but the confusing thing is that I should be able to define the first route like this:

```
{
  path: "",
  component: ComponentAggregatorComponent,
  outlet: "whatever-I-want",
  data: { components: [ HomeSummaryComponent ] },
}
```

But this wouldn't work. I realize that it is not really a "bug" as such but it seems pretty not intuitive to me.

Regards

**Comment by vicb** [comment]
This is the way the router is designed

**Comment by ssougnez** [comment]
And that's it? There is no possibility of discussion ?

My usecase is pretty common and it could be worth thinking about it. Just a precision, the code that I showed above actually does not really work. Indeed, once I'm on the page "payments", the "aside" `router-outlet` does not get updated with the `AskSummaryComponent`.

The main idea behind this is to have a "master page" mechanism where the root component would contain some `router-outlet` that could be all different according to the route. Having the possibility to define this via the URL (with "(outlet: component)") is not really usable in a public facing web site (except maybe for blogs), it means that the user could change the URL to display the component in a different order. Here, the idea is to say something like:

- For route A, load "component A" here, component "B" here and component "C" there.
- For route B, load "component D" here, component "E" and "F" here and component "A" there.

This way, when the user access "A", the component are dynamically loaded in the correct place and the user can't leverage this. Basically, you would use route configurations to define the content of the pages. 

If this interests anyone, here is a more complete explanation of the matter: http://stackoverflow.com/questions/42550918/multiple-router-outlet-on-the-page-for-the-same-route

Maybe I'm not smart enough to understand why it's a bad idea, so if someone knows it, I would be interested to learn it ;-)
