### ISSUE TITLE
Form reset not working on IE / Firefox browsers as documented in reactive form example

### ISSUE THREAD

**Issue by apimm** [angular/angular#14832]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I run the "Angular Reactive Forms" live demo in IE 11 and Firefox 51.0.1 the reset button does not reset the form back to the default view state as it does in Chrome. Instead, it completely clears the form control values. I first noticed this behavior in my own forms, and tested both Windows 7 and Windows 10 versions of these browsers. Both exhibit these behaviors.

**Expected behavior**

I expect the form reset to work exactly the same as Chrome. 

**Minimal reproduction of the problem with instructions**

The existing plnkr.co example of the reactive forms live demo illustrates the problem when you perform the following steps:

1. load the reactive forms demo in plnkr.co by clicking the link I provided above
2. select the "Whirlwind" hero
3. Type "New Name" in the Name field to replace "Whirlwind"
4. Press the "Revert" button. The name field and all of the Address fields are reset to a fully cleared state. In Chrome, these form elements are actually reverted back to the original state when Whirlwind hero was loaded. Specifically, the name field is reverted to "Whirlwind".

**What is the motivation / use case for changing the behavior?**

I cannot use reactive forms in this state since the behavior for IE and Firefox is not the documented behavior and would cause issues with my clients that use these browsers.

**Please tell us about your environment:**

Running on Windows 7, Windows 10, VS Code, npm -v = 3.8.1, IIS 7.5
* **Angular version:** 2.4.7

My local version of the heroforms reactive application is running as an Angular 2.4.7

* **Browser:** [Firefox 51 | IE 11]

 IE 11.0.9600.18537
Microsoft Edge 38.14393.0.0
Firefox 51.0.1

* **Language:** [TypeScript 2.0]
Typescript 2.0.3

* **Node (for AoT issues):** `node --version` =   v6.9.5
not using AOT or node to serve the web pages.
node -v = v6.9.5

**Comment by DzmitryShylovich** [comment]
please add a plunkr

**Comment by apimm** [comment]
I provided one:
https://angular.io/resources/live-examples/reactive-forms/ts/eplnkr.html

**Comment by apimm** [comment]
ok, I found a solution to the problem. It seems that in your example the reset button is specified in html as:

` <button type="reset" (click)="revert()" [disabled]="heroForm.pristine" class="btn btn-danger">Revert</button>
`

This apparently works in Chrome, but the type="reset" apparently clears out the form values in IE and Firefox. In my code, I tried changing the button from type="reset" to type="button" and that fixes the issue. I would suggest that your examples be updated to reflect this to reduce confusion for other developers trying to make reactive forms work.

**Comment by DzmitryShylovich** [comment]
> I would suggest that your examples be updated to reflect this to reduce confusion for other developers trying to make reactive forms work.

please file an issue on https://github.com/angular/angular.io/issues

**Comment by DzmitryShylovich** [comment]
btw it's not necessary to change button type:
```
<button type="reset" (click)="revert($event)" [disabled]="heroForm.pristine" class="btn btn-danger">Revert</button>

revert(ev) { 
    ev.preventDefault();
    this.ngOnChanges(); 
  }
```
https://plnkr.co/edit/bIr0JKmwBIFYKICtyznU?p=preview

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed as a doc issue
