### ISSUE TITLE
ErrorHandler not fired for SyntaxError

### ISSUE THREAD

**Issue by sergey-morenets** [angular/angular#14839]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I created new error handler and specified in the "providers" section of the root module:

export class MyErrorHandler extends ErrorHandler {
  constructor() {
    super(true);
  }

  public handleError(error: any): void {
    console.log("I handle the given error " + error);
  }
}

1) When I throw new Error() in my code this error handle is fired. However when I put incorrect template content, for example, <p><div></div></p> this error handler is not fired and default error message is printed in the console: "_zone_symbol__error: Error: Template parse errors: Unexpected closing tag "p""
2) When I put invalid property name in the component template, error handler is fired but default error message is also printed in the console: "Unhandled Promise rejection: Error in ./PanelHeaderComponent class PanelHeaderComponent - inline template:1:5 caused by: Cannot read property 'aa' of undefined "

**Expected behavior**
1) Error handler should fire if template parse error happens
2) Default error handler shouldn't fire in the second case

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

The main goal is to catch and report all the application errors
**Please tell us about your environment:**

Windows 7, Webstorm 2016.3
* **Angular version:** 2.0.X
2.4.8

Yes
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 56.0
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.8
* **Node (for AoT issues):** `node --version` =   
6.9.5

**Comment by DzmitryShylovich** [comment]
@sergey-morenets syntax errors are intended for development mode. why do you want to handle syntax errors inside `ErrorHandler`?

**Comment by sergey-morenets** [comment]
@DzmitryShylovich Hi 

That's OK for me. Is there any way to handle syntax errors except ErrorHandler?

**Comment by pkozlowski-opensource** [comment]
Syntax errors are thrown by the JS engine before Angular has even chance to do anything. Closing as we can't channel syntax errors through `ErrorHandler`
