### ISSUE TITLE
[Dart] Bind to normal String fields on <input> 

### ISSUE THREAD

**Issue by cgarciae** [angular/angular#1483]
Based on the example shown next, it seems that you cannot bind input to normal text fields.
```
@Component({
  selector: 'form-example'
})
@Template({
  // we are binding the input element to the control object
  // defined in the component's class 
  inline: `<input [control]="username">Hello {{username.value}}!`,
  directives: [forms]
})
class FormExample {
  constructor() {
    this.username = new Control('World');
  }
}
```
Instead you have to create the field of type `Control` and the syntax doesn't look that bad, although the `.value` is not as intuitive. In AngularDart 1 I mostly use my own classes as fields of the component, then bind to their internal values, setting data on the page is extremely easy, so is sending it back to the server.

The **BIG** problem in Angular2 is that non of my data structures have fields of type `Control`, nor will they because of serialization issues (from/to JSON and from/to MongoDB). Is there a way to solve this without creating special classes/methods just to convert from/to these control structures?

**Comment by mhevery** [comment]
solved by `[(username)]` syntax
