### ISSUE TITLE
ngc generates incorrect import paths (with proposed fix)

### ISSUE THREAD

**Issue by timbell** [angular/angular#14838]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When referencing angular in a folder outside the current project incorrect import paths are generated in ngfactory files causing compilation to fail 

**Expected behavior**
Correct import paths should be generated in ngfactory files for externally referenced items. I have a fix that seems to work - see below

**Minimal reproduction of the problem with instructions**

(This is just to repro the problem quickly. Normally I'd want to have all of `@angular` and maybe other libs in an external library project.)
- Clone this repo: https://github.com/johnpapa/angular2-tour-of-heroes into a folder `aot_test`
- cd into `aot_test`
- `npm install`
- edit `tsconfig-aot.json` - add `"lib": [ "es2015", "dom" ],` to `"compilerOptions"`
- test ngc compile by running `npm run aot` - should run with no errors
- create a folder `aot_lib` as a sibling of `aot_test`
- move `aot_test/node_modules/@angular/common` folder to `aot_lib/node_modules/@angular/common`
- edit `tsconfig-aot.json` - add the following to `"compilerOptions"` to reference the now external `@angular/common`. Normally you'd move all of `@angular` and `rxjs` to the `aot_lib` but that would necessitate more script changes. This is a quicker way to illustrate the problem.
```    
    "baseUrl": ".",
    "paths": {
      "@angular/*": ["../aot_lib/node_modules/@angular/*", "node_modules/@angular/*"],
      "rxjs/*": ["node_modules/rxjs/*"]
    }
``` 
- **important**: delete the previously generated `aot` folder from `aot_test`
- run `npm run aot` again. You should get compiler errors like this:
```
Error at /<snip>/aot_test/aot/app/hero-search.component.ngfactory.ts:22:27: Cannot find module '../node_modules/@angular/common/src/directives/ng_for.ngfactory'.
Error at /<snip>/aot_test/aot/app/dashboard.component.ngfactory.ts:21:27: Cannot find module '../node_modules/@angular/common/src/directives/ng_for.ngfactory'.
Error at /<snip>/aot_test/aot/app/hero-detail.component.ngfactory.ts:30:27: Cannot find module '../node_modules/@angular/common/src/directives/ng_if.ngfactory'.
Error at /<snip>/aot_test/aot/app/heroes.component.ngfactory.ts:24:27: Cannot find module '../node_modules/@angular/common/src/directives/ng_for.ngfactory'.
Error at /<snip>/aot_test/aot/app/heroes.component.ngfactory.ts:25:27: Cannot find module '../node_modules/@angular/common/src/directives/ng_if.ngfactory'.|
```
- if you look in `/aot_test/aot` you will find `aot_lib/node_modules/@angular/common` but the errors above show that this folder isn't being referenced correctly 

**Proposed fix**
The problem appears to be coming from [here](https://github.com/angular/angular/blob/49b462e8152a9842a82585e61a8308f4f6f0373d/modules/%40angular/compiler-cli/src/compiler_host.ts#L120-L130) 
I would suggest changing this to:
```
        if (isGeneratedFile) {
            // rewrite to genDir path
            return this.dotRelative(containingDir, this.calculateEmitPath(importedFile));
        } else {
```
I've made the change locally and it seems to work well. By using `calculateEmitPath` we would ensure consistency with where the files are actually being generated.

* **Angular version:** 2.4.8

* **Language:** [TypeScript 2.2.1]

* **Node (for AoT issues):** `node --version` = 6.9.1

**Comment by DzmitryShylovich** [comment]
@timbell could you try it out with angular 4?

**Comment by timbell** [comment]
@DzmitryShylovich the code in question (compiler_cli/src/compiler_host.ts) is unchanged in angular 4 other than the addition of an used import of CollectorOptions

**Comment by tbosch** [comment]
See also https://github.com/angular/angular/issues/14838

**Comment by timbell** [comment]
@tbosch did you mean to reference a different issue? [#14838](https://github.com/angular/angular/issues/14838) is this one
@DzmitryShylovich I have finally migrated to 4.0.3 and no longer have the issue. I guess it was fixed elsewhere?

**Comment by tbosch** [comment]
It's #12249

**Comment by JoostK** [comment]
Closing as obsolete. Factories are no longer used with Ivy and import path generation has completely changed in the new compiler.
