### ISSUE TITLE
FormGroup.valueChanges not being fired for input type='date' on Firefox for Android 

### ISSUE THREAD

**Issue by rgrasso** [angular/angular#14834]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
A date select on Firefox for Android where <input type="date"> is not firing a value change on the FormGroup.

**Expected behavior**
When the date selection is made the FormControl's value should be updated

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/eaowHLZJOn4guUg4ZdrM

**What is the motivation / use case for changing the behavior?**
support for html5 input types should be uniform across browsers / platforms

* **Angular version:** 2.0.X
I see this behavior on Angular 2.4.0 and 2.0.0-rc.4  and 2.4.1 (on plunker)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox for Android (version as of 3/1/2017) is the only platform have been able to reproduce this on.  I do not see this behavior on Firefox or Chrome on windows 10 or Chrome on Android
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript versions 1.8.10, and 2.0.10

* **Node (for AoT issues):** `node --version` =   N/A

**Comment by DzmitryShylovich** [comment]
does this work?
```
<input id="date-input" type="date"  />
var dateInput = document.getElementById('date-input');
dateInput.addEventListener('change', function(e) {
  console.log(e.target.value);
});
```

**Comment by rgrasso** [comment]
My work-around is essentially the same:

`<input type="date" class="form-control" (change)="onTransDtChange($event)" formControlName="transdt">`

`    onTransDtChange(event:any) {
        this.transForm.patchValue({'transdt': event.target.value});
    }`

**Comment by AndrewKushnir** [comment]
Hi @rgrasso, thanks for reporting the issue and creating a repro.

I've re-created it using Stackblitz ([see test page here](https://stackblitz.com/edit/angular-ivy-hiqebv)) and latest versions of Angular packages. We tested this behavior with Firefox on Android and everything seems to work as expected now. Most likely it was a browser-specific issue that was fixed in the newer version of Firefox.

I will close this ticket, feel free to reopen if the problem still exists.

Thank you.
