### ISSUE TITLE
ngIf should allow assignment expressions

### ISSUE THREAD

**Issue by benlesh** [angular/angular#14846]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Assuming `foo$` is `Observable<string[]>`, and the following template:

```html
<ul *ngIf="let items = (foo$ | async)">
  <li *ngFor="let item of items">{{item}}</li>
</ul>
```

**Expected behavior**

The `ul` should be rendered only of a value has been observed from `foo$`.

**Minimal reproduction of the problem with instructions**

```ts
@Component({
  template: `<ul *ngIf="let items = (foo$ | async)">
    <li *ngFor="let item of items">{{item}}</li>
  </ul>`
})
class SomeComponent {
  foo$ = Observable.of(['test', 'this', 'now'], Rx.Scheduler.async)
}
```

Plunker: http://plnkr.co/edit/OlR9EokB8wJcpSz4wDvB?p=preview

**What is the motivation / use case for changing the behavior?**

Ideally people would be able to assign a complex type from an Observable somewhere, and toggle a view based on it's existence. 

**Please tell us about your environment:**

Mac OSX, VSCode, NPM, using angular-cli latest as of today.

* **Angular version:** 4.0.0-rc.1 and under

* **Browser:**  all

* **Language:**  TypeScript 2.2 (although this is unrelated)

* **Node (for AoT issues):** `node --version` =   v7.4.0

**Comment by DzmitryShylovich** [comment]
please add a plunkr :)

**Comment by benlesh** [comment]
@DzmitryShylovich it's probably unnecessary, but I've added one.

**Comment by DzmitryShylovich** [comment]
It doesn't work. You can't import everything from `'rxjs'` on plunkr for some reason

**Comment by benlesh** [comment]
@DzmitryShylovich probably a limitation of the module system in use... I've updated it to import `rxjs/Rx`... it's showing the error I was seeing now.

**Comment by DzmitryShylovich** [comment]
your plunker uses ng 2.x
here's an example with 4.x http://plnkr.co/edit/D7g9x4uvpt9LOmQsEP9t?p=preview

**Comment by DzmitryShylovich** [comment]
so for me it works as expected. if `users` is an empty array or null/undefined `ngIf` won't render anything. or I'm missing something?

**Comment by vicb** [comment]
as indicated by @DzmitryShylovich this works in the 4.x branch with the following syntax:

```
    <div>
      <ul *ngIf="foo$ | async; let items">
        <li *ngFor="let item of items">{{item}}</li>
      </ul>
    </div>
```
