### ISSUE TITLE
Angular 1.4.0rc-0 Error with ng-if

### ISSUE THREAD

**Issue by blittle** [angular/angular#1484]
I have a very strange error showing up very reproducably within our APP, but as of yet I have not been able to reproduce it as a stand alone example. I am hesitant to report it because I cannot reproduce it outside our APP. 

The gist of the problem is that we have a dialog which has an ng-if at the root element:

```html
<div class="bss-modal" ng-if="vm.editSettings">
 ...content ...
   <div class="bss-modal__dialog__actions">
       <button class="bss-btn +primary" ng-click="vm.patchMasterSurvey()">DONE</button>
   </div>
 </div>
</div>
```

```javascript
vm.patchMasterSurvey = function() {
  vm.editSettings = false;
  SurveyService.patchMasterSurvey();
}
```

When the button is clicked which invokes `patchMasterSurvey` and `vm.editSettings = false` is within the method, the following error is thrown:
```
undefined is not an object (evaluating 'c.runner.end')
```

I did some testing and narrowed this particular issue down to 1.4.0-rc.0. The 1.4.0-beta.6 works fine. It also seems to only happen inside Safari. Tested inside Firefox and Chrome and no problem.

**Comment by fxck** [comment]
this is angular2 repo, you should post your 1.x issues here https://github.com/angular/angular.js/issues

**Comment by blittle** [comment]
K, will move it :)
