### ISSUE TITLE
aio: incorrect links to in-page anchors

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14851]
These links are misrepresented as `/#`.

Repro:
1. http://localhost:4200/guide/setup
1. Examine the link within "You [should develop locally](http://localhost:4200/#why-locally) on your own machine ... "
1. It is `http://localhost:4200/#why-locally` which yields doc-not-found

Should be `http://localhost:4200/guide/setup.html#why-locally`.

**Comment by petebacondarwin** [comment]
Related to (or duplicate to some extent of) #14850

**Comment by petebacondarwin** [comment]
Actually I realise that we cannot do this particular step in the link click interceptor, because the hrefs will still be wrong if someone wants to copy-paste the URL to share a link to the anchor.
We need to fix this part in dgeni

**Comment by petebacondarwin** [comment]
Fixed in #15285
