### ISSUE TITLE
angular2 library: need finals

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#1485]
- [ ] All tokens
- [ ] defaultPipes - src/change_detection/change_detection.dart

If this relates to a tweaks to another tool, great. I'd love to keep this open until it's resolved, though.

**Comment by mprobst** [comment]
Sorry, I don't understand the issue description (`NO_CHANGE`? All tokens?). Can you expand? Does this relate to the `const` vs `final` issue we discussed?

**Comment by mprobst** [comment]
@kevmoo ping?

**Comment by kevmoo** [comment]
@mprobst Digging in now. Will provide details shortly.

**Comment by kevmoo** [comment]
`src/change_detection/change_detection.dart`. `defaultPipes` is a mutable hash.

```dart
var defaultPipes = {
  "iterableDiff": iterableDiff,
  "keyValDiff": keyValDiff,
  "async": async,
  "uppercase": uppercase,
  "lowercase": lowercase,
  "json": json
};
```

Ideally, it'd be

```dart
const Map defaultPipes = const <String, dynamic>{
  "iterableDiff": iterableDiff,
  "keyValDiff": keyValDiff,
  "async": async,
  "uppercase": uppercase,
  "lowercase": lowercase,
  "json": json
};
```

**Comment by mprobst** [comment]
@kevmoo we do support const hashes:

```
const defaultPipes = CONST_EXPR({
  "iterableDiff": iterableDiff,
  "keyValDiff": keyValDiff,
  "async": async,
  "uppercase": uppercase,
  "lowercase": lowercase,
  "json": json
});
```

The reference on the left hand side currently will come out as `final`, due to the `final` vs `const` mess that we discussed earlier. But I assume something like `dart2js` can detect that `defaultPipes` is effectively `const` (never assigned into), and this doesn't really matter all that much.

**Comment by mprobst** [comment]
I see, you're already fixing it :-)

**Comment by kevmoo** [comment]
@mprobst I'm blocked, though. Can you help with https://github.com/angular/ts2dart/issues/217 ?

**Comment by yjbanov** [comment]
Does this issue need more work? Should it be closed? If not, would it be reasonable to expect that it will be closed in alpha-29?

**Comment by mprobst** [comment]
I think this should be fixed.

**Comment by kevmoo** [comment]
I've got a CL landed that takes care of this for top-level members in the angular2 lib.

I think there are a lot more places where things should be final, but top-level members – since they are shared – are clearly the most important.

We may just need to do an occasional review of the API to find bad examples.
