### ISSUE TITLE
Platform-browser package incorrectly contains transpiled files misrepresented as ES6

### ISSUE THREAD

**Issue by mattmutt** [angular/angular#14857]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When checking out an Angular 4.0.0-rc.1 new project with all Angular assets pulled in with that exact version, the platform-browser contains a folder that eventually contain animation and testing.

that folder's relative path would be
`@angular\platform-browser\@angular\platform-browser\animations`

There are ES5 builds of for animations and testing. The problem is that the `.es5.js` files are incorrect. How can ES5 use the `class` keyword? 

**Expected behavior**
The files must be ES5 compliant. That means transpile to functions.

**Minimal reproduction of the problem with instructions**

```
npm i @angular/animations@4.0.0-rc.1 zone.js rxjs @angular/core@4.0.0-rc.1 @angular/platform-browser@4.0.0-rc.1 @angular/common@4.0.0-rc.1
```
then change directory into
`node_modules\@angular\platform-browser\@angular\platform-browser`

Examine the alleged ES5 files `animations.es5.js` and `testing.es5.js`. Judge if the syntax complies with the older JS version.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** [4.0.0-rc.1]

latest version of 4

* **Browser:** [IE11 ]

 Mainly affects old school IE

* **Language:** [ES5] 
 

* **Node (for AoT issues):** `node --version` =

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/14730

**Comment by mattmutt** [comment]
thanks will monitor that related defect

**Comment by DzmitryShylovich** [comment]
@mattmutt fixed by https://github.com/angular/angular/pull/14820
