### ISSUE TITLE
Access Route data property in parent components

### ISSUE THREAD

**Issue by borislemke** [angular/angular#14860]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a router wrapper(let's call it `AppComponent`) that has a fixed `navbar` component and a `<route-outlet>` beneath it. Each children route of `AppComponent` I'm passing some values in the `Route`'s data property like so:
```javascript
...
[
    ...
    {
        path: 'dashboard',
        loadChildren: 'path/to/dashboard#DashboardModule',
        data: { showNavbar: false }
    },
    ...
];
```

I can access the data alright from within my `dashboard.component`(declared in `DashboardModule`) using `ActivatedRoute`. The issue is, it seems not possible to access the data property from within `AppComponent`. Some pages I have will have the option to either show or hide the navbar, this is possible from within each component but not a viable option to do if you have a lot of pages.

In my case, I'm watching over navigation events in the `AppComponent` like so:

```javascript
...
constructor(private router: Router) {
    // also tried with router: ActivatedRoute, but this value only applies to `AppComponent`'s `Route` configuration and not any of it's children, obviously.
}

ngOnInit(): void {
    this.router.events
    .filter(event => event instanceof NavigationEnd)
    .susbcribe(event => {
        // Want to access event.data? here.
        this.setNavbarVisibility(event.data.showNavbar); // either true or false
    });
}
...
```

**Expected behavior**
We would like to be able to access a `Route`'s `data` property from a parent component.

**Minimal reproduction of the problem with instructions**
Any new project:
`ng new project`

**What is the motivation / use case for changing the behavior?**
Would be very helpful in managing multiple pages with page-specific preference. Although possible by doing the task in each component independently, not an easy task when having many pages.

**Please tell us about your environment:**
OSC 10.11.6 El Capitan

* **Angular version:** 2.0.X
2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Any browser
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.1.6

* **Node (for AoT issues):** `node --version` =   
7.4.0

**Comment by DzmitryShylovich** [comment]
please add the plunkr that reproduces the issue. thanks

**Comment by borislemke** [comment]
@DzmitryShylovich https://plnkr.co/edit/po5uFM3qCJ1iCsDiYU0O?p=preview

**Comment by DzmitryShylovich** [comment]
@borislemke https://plnkr.co/edit/7PF32p0LBZ5OQcPl28Cb?p=preview
https://toddmotto.com/dynamic-page-titles-angular-2-router-events here you can find an explanation

**Comment by borislemke** [comment]
Wouldn't you think there should be an easier way to do this? What happened to `RouteData`? I noticed that the team removed this from the cookbook http://a2.hubwiz.com/docs/ts/latest/api/router/RouteData-class.html. I think it would be helpful to many if we could have a more exposed API in getting the data as previously implemented in `RouteData`.

**Comment by Toxicable** [comment]
@borislemke This method allows you to set the title outside of the router, as you previously could not. You could always assign data to the route since it still has the Data property.

**Comment by borislemke** [comment]
@DzmitryShylovich  Furthermore, would this method work if I was watching over router changes from a child component. In the plunker example, AppComponent is the route component, but what if we wanted to do it from a child component, say:

```
AppComponent -----> AuthPageComponent
             -----> ContentComponent // Component after logging in, we want to watch the route events only when the user has logged in
                  |-----> DashboardComponent
                  |-----> SettingsComponent
```

This would require to be changed somehow, no?
```
    ...
      .map(route => {
        while (route.firstChild) route = route.firstChild; // <-- route.firstChild?
        return route;
      })
      .filter(route => route.outlet === 'primary') // <--- is it still the primary router?
    ...
```

**Comment by DzmitryShylovich** [comment]
it will work from any component

**Comment by borislemke** [comment]
@DzmitryShylovich you can close this issue if the team will not consider making a more "exposed" API to this functionality.

**Comment by DzmitryShylovich** [comment]
@borislemke you can close it yourself
there's already the issue https://github.com/angular/angular/issues/13767 to improve api

**Comment by borislemke** [comment]
@DzmitryShylovich thanks. #13767 is what I was hoping for.
