### ISSUE TITLE
Help me injecting angular 1 framework components like $rootScope, $scope, $timeout into Angular 2 components in AOT compatible hybrid app

### ISSUE THREAD

**Issue by shnmkhk** [angular/angular#14863]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Help me injecting angular 1 framework components like $rootScope, $scope, $timeout into Angular 2 components in AOT compatible hybrid app

**Please tell us about your environment:**

Windows, VS Code, ngc, Tomcat

* **Angular version:** 2.0.X

2.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
