### ISSUE TITLE
TypeError: Cannot read property ‘map’ of undefined at Evaluator.evaluateNode -npm run build.prod.aot

### ISSUE THREAD

**Issue by srinivasan-g** [angular/angular#14869]
![image](https://cloud.githubusercontent.com/assets/8088685/23511654/c38cb6de-ff55-11e6-98d0-164eeab3884e.png)

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.
