### ISSUE TITLE
docs: add ngStyle to Cheat Sheet

### ISSUE THREAD

**Issue by siva636** [angular/angular#14861]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The 'Built-in Directives' section of the Cheat Sheet has ngClass, but ngStyle is missing.

**Expected behavior**

The missing ngStyle needs to be added there.

I created similar issue on angular.io repo, but referred here. https://github.com/angular/angular.io/issues/3331#issuecomment-283593001 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jenniferfell** [comment]
Thanks for this feedback. We're doing some cleanup. It looks like this issue was resolved. If this is not resolved to your satisfaction, please reopen or submit a new issue. Thanks!
