### ISSUE TITLE
Lazy loading does not work when integrating into another application

### ISSUE THREAD

**Issue by maxime-menard** [angular/angular#14867]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I want to use lazy-loading for feature modules. I use angular-cli and **it works fine when I run ng serve**.
Now I'm trying to include the js files generated by angular-cli in a legacy jquery application :
- Copy 0.chunk.js, inline.bundle.js, main.bundle.js, polyfills.bundle.js, styles.bundle.js and vendor.bundle.js in a directory called angular
- in my html file, I'm loading the files :
```
<script type="text/javascript" src="/js/angular/inline.bundle.js"></script>
<script type="text/javascript" src="/js/angular/polyfills.bundle.js"></script>
<script type="text/javascript" src="/js/angular/styles.bundle.js"></script>
<script type="text/javascript" src="/js/angular/vendor.bundle.js"></script>
<script type="text/javascript" src="/js/angular/main.bundle.js"></script>
```

In my application, let's say I go to this webpage :
http://localhost:8090/myapp/test.action

In order to integrate angular components in my application, I'm using the router to redirect to the component I want to display in the AppComponent :

```
ngOnInit(): void {
    if (this.displayComponent) {
      this.router.navigate([this.displayComponent]);
    }
  }
```

Let's say I want to display my component called 'componentTest', it will redirect to :
http://localhost:8090/myapp/test.action#/componentTest with this code in my html file :
`<app-root displayComponent="componentTest">Loading...</app-root>`

And then I have this error :
`EXCEPTION: Uncaught (in promise): Error: Loading chunk 0 failed.
`
It seems is is trying to load the chunk file at this address :
`http://localhost:8090/myapp/0.chunk.js`
and not
`http://localhost:8090/js/angular/0.chunk.js`

How to fix this issue ?

**This is working perfectly fine without lazy loading.**

**Expected behavior**
Should load 0.chunk.js

**Please tell us about your environment:**
Windows 10

* **Angular version:** 
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/material: 2.0.0-beta.2
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

* **Browser:** 
Chrome 56
 
* **Language:** 
Typescript 2.0

* **Node (for AoT issues):** `node --version` =   v6.9.5

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by slmyers** [comment]
maybe [this thread](https://www.reddit.com/r/Angular2/comments/5wozkl/angularcli_how_can_i_allow_content_to_be_served/) can help you?

**Comment by maxime-menard** [comment]
Nice, thanks @slmyers !
