### ISSUE TITLE
How to access a component's children components inside it's Shadow DOM

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1486]
`Query` annotations allow us to query for children components that are in the light DOM of a component (and get projected into it's Shadow DOM).

I wonder if there's a way to access children components of a component's Shadow DOM too. For example we have an app component like that:

```js
@Component({
  selector: 'app'
})
@View({
  template: `
    <foo #foo></foo>
    <bar #bar></bar>
    <button (click)="run(foo, bar)">Click me</button>
  `
})
class App {

  run(foo, bar) {
    // do something with foo and bar
  }
}
```

Let's say we not only want to execute `run()` when the button is clicked, but also on initial load, once all child components are done. We could use `onAllChangesDone` lifecyle like this:

```js
@Component({
  ...
  lifecycle: [onAllChangesDone]
})
class App {
  ...
  onAllChangesDone() {
    run(); // where do we get `foo` and `bar` from?
  }
}
```

As we can see, this doesn't really solve the problem since there's still no way to access children components.

The only way I can think of to solve this right now, is to introduce another wrapper component, that basically get's the children as LightDOM (and projects them just into it's Shadow DOM), and using `Query` to access them accordingly. We also need to move the `run()` method to that component:

```html
<runner>
  <foo></foo>
  <bar></bar>
</runner>
```

```js
class Runner {
  constructor(@Query(Foo) query:Foo) {

  }

  run(foo, bar) {

  }
} 
```

Is that the way to go?

**Comment by PascalPrecht** [comment]
I somehow get the feeling that a parent component should rather not directive ask for components that are already in it's shadow DOM...

**Comment by alexpods** [comment]
@PascalPrecht I think you know about [action concept in angular2](https://github.com/angular/angular/issues/1251). You can create `@run` action on `foo` and `bar` directives. Then emit `run` action in the `onAllChangesDone()`. Cant it handle your case?

**Comment by PascalPrecht** [comment]
@alexpods Need to reread the action thing, but I tried `onAllChangesDone()`. Didn't work because of some error I can't remember. Also, turned out that `onAllChangesDone()` is executed several times per second (infinitely). I want to call it once.

**Comment by mhevery** [comment]
Yes this sounds as dup of #1251

**Comment by mhevery** [comment]
Closing since it is dup
