### ISSUE TITLE
Feature: extend template microsyntax to allow references

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#14877]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, it is not possible using template microsyntax to create reference on template element.

**Expected behavior**
Template microsyntax should be extended to allow references.
Proposed syntax:
```
<div *ngFor="let item of list; trackBy: foo; #ref=bar" #inner="baz" class="item"></div>
```
should be equivalent of:
```
<template let-item [ngForOf]="list" [ngForTrackBy]="foo" #ref="bar">
  <div #inner="baz" class="item"></div>
</template>
```

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
It will enhance the means of interaction between components and directives.
For example, with the new feature, new (cleaner IMHO) if-else syntax could be possible:
```
<div *myIf="condA; #aRef=myIf">if condA is satisfied</div>
<div *myIf="condB; elseOf: aRef; #bRef=myIf">if condB is satisfied but not cond A</div>
<div *myIf="true; elseOf: bRef">if neither condA nor condB are satisfied</div>
```
And yes, I know 4.0.0 will introduce if-else, but that's not the point.

**Please tell us about your environment:**

* **Angular version:** 2.4.8

**Comment by DzmitryShylovich** [comment]
> #ref=bar" #inner="baz"

what is `bar` and `baz`?

**Comment by dawidgarus** [comment]
> what is bar and baz?
Just some random name directive may have as `exportAs`.
It's just an example of syntax, not logically correct code that does something in particular.

**Comment by DzmitryShylovich** [comment]
I'm not following.
Can you please add the plunker that demonstrates what you are trying to accomplish?

**Comment by dawidgarus** [comment]
I'm not trying accomplish anything in particular. I wan't to introduce new syntax.
As we all know, something this:
```html
<div *structuralDirective="value"></div>
```
is equivalent of this:
```html
<template [structuralDirective]="value"><div></div></template>
```
Currently it's not possible to get reference to structural directive using template microsyntax:
```html
<div *structuralDirective="value" #ref="structuralDirective"></div>
```
will be translated to:
```html
<template [structuralDirective]="value"><div #ref="structuralDirective"></div></template>
```
That's no good, because I was to reference directive on template element. So I proposed new sytanx:
```html
<div *structuralDirective="value;  #ref=structuralDirective"></div>
```
Which will work like this:
```html
<template [structuralDirective]="value" #ref="structuralDirective"><div></div></template>
```

**Comment by DzmitryShylovich** [comment]
> to get reference to structural directive using template microsyntax

why? you can expose public properties via context object

**Comment by dawidgarus** [comment]
> why? you can expose public properties via context object

But they could be accessed only inside the template. As far i know, You cannot query for context object, or access it outside template, like this:
```html
<div *structuralDirective="let ref"></div>
<div>{{ref}}</div>
```

**Comment by DzmitryShylovich** [comment]
Ok, but there's already an issue about that https://github.com/angular/angular/issues/12121 :
> exportAs is not supported in * directives.

**Comment by petebacondarwin** [comment]
This is being tracked in the aggregate issue of #43485 for which we need to create a project proposal.

**Comment by alxhub** [comment]
Closing due to insufficient votes.
