### ISSUE TITLE
Unintentional breaking change in Renderer (starting from 4.0.0-rc.1)

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#14872]
The plunker says it all: https://plnkr.co/edit/eDNXO0iNeiG1InnSvSqQ?p=preview

Before it was possible to call `Renderer.createText(...)` from a listener registered via `Renderer.listen(...)` but from 4.0.0-rc.1 it blows with an error as seen in the linked plunker.

The error is thrown in the debug mode only - production mode is not affected. Seems like there is some shared state related to debug info and something is not initialized / cleaned up properly.

I fully recognize that this is a corner case but it was [reported against ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap/issues/1338) for the real-life use-case (we are using similar code in tooltips / popovers). I can work-around it on my side but again, this is an accidental breaking change and IMO one worth fixing if possible.

**Comment by MatteoNY** [comment]
Greetings:  DzmitryShylovich, After the querystring issue was resolved I found the tooltip issue with Bootstrap 4 alpha-20 as well. 

I am using Renderer to manage focus and when I changed it to RendererV2 I'm getting compile error. 
Property 'invokeElementMethod' does not exist on type 'RendererV2'. 
Is Renderer going away and RendererV2 the latest? If this is so I have to get Focus to work again.
re:   this.renderer.invokeElementMethod(this.elContinue, 'focus');

BTW: I did not see any deprecated warning about "Renderer" but see notes in code "Note: `Renderer` can still be injected/used, but is deprecated."  Anyway... rc2 is still young and not as breaking as Angular2 rc-4 to rc-5 with @modules which was worth the effort. Best
