### ISSUE TITLE
Provide support for SharedWebworkers

### ISSUE THREAD

**Issue by ZuSe** [angular/angular#14871]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Right now it's only supported to bootstrap the app with legacy web workers. This allows a nice separation of the service layer from the UI layer. Nevertheless all components have to last in one browser window/tab

**Expected behavior**
Let's assume we have a really big app (e.g. some finance dashboard) with a lot of information to show or tools to manipulate live-data. Wouldn't it be cool to spread the application across multiple monitors (browser windows) but have all data synchronized by sharing the same services?
I think this should be possible if we put the services in a shared webworker that can be accessed from any browser window (with respect to some constraints as described here: https://developer.mozilla.org/de/docs/Web/API/SharedWorker)
It would allow building multi window applications without the nasty task to share everything through localStorage or multi retrieve data via WebSocket o.s.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Make development easier + better architecture. 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

I think this would be more important for desktop browsers, dunno if there are good use cases for mobile.

**Comment by Splaktar** [comment]
For non-German readers: https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker

**Comment by jelbourn** [comment]
Closing all issues related to web-workers since Angular's experimental web-worker renderer has been deprecated and it now being removed completely in Angular v11.
