### ISSUE TITLE
aio: add google analytics for page views when navigate within app

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14876]
Feature.  Needs to be done imperatively I believe.

See PR #15081

**Comment by petebacondarwin** [comment]
Here is how it is done in AngularJS docs: https://github.com/angular/angular.js/blob/master/docs/app/src/docs.js#L23

**Comment by petebacondarwin** [comment]
In the case of AngularJS docs we were using `ng-include` which raises this `$includeContentLoaded` event every time it changed page

So perhaps the simplest place is to subscribe to `LocationService.currentUrl`?

**Comment by wardbell** [comment]
closed by #15081
