### ISSUE TITLE
`required` attribute usage not consistent in component template

### ISSUE THREAD

**Issue by Bidthedog** [angular/angular#14883]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When binding on an `<input>`'s `required` attribute, the `required` attribute is rendered in the HTML, but the component property does not set, and can't be used elsewhere in the template (e.g. within an *ngif). Console.log outputs an empty string for the `required` property.

**Expected behavior**
`required` to be treated as a boolean consistently across the entire template.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/deE8mzUpFOwx89a73UVo?p=preview

The issue in question is that the `<span *ngIf="required">(required)</span>` is not showing, even though the `required` attribute is being successfully added to the `<input>` tag (inspect both text boxes in my plunkr). The `First Name` text box has the `required` attribute applied to the rendered HTML as expected, but the `ngIf` doesn't render the span as I would expect.

If I change the parent template to use `required="true"` instead of just `required`, it works as expected. There is some console output to verify the read value of the component's `required` property.

Just noticed that if I remove ` [(ngModel)]="value"` from the component template, the `required` attribute doesn't show up either.

**What is the motivation / use case for changing the behavior?**

Consistency - when using the `required` attribute (without a setter, bound to a boolean), why does the `<input>` have a `required` attribute, but the boolean property is empty?

**Please tell us about your environment:**

 - Win 10
 - VSCode (latest)
 - npm + yarn, depending on mood
 - Angularcli / webpack

**Angular version:**
$ ng --version
angular-cli: 1.0.0-beta.26
node: 6.9.4
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/compiler-cli: 2.4.8

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Only checked in Chrome (56.0.2924.87)
 
**Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3

  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "bootstrap": "^3.3.7",
    "bootstrap-sass": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.1.1",
    "moment": "^2.17.1",
    "ng2-bootstrap": "^1.3.3",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.26",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }

**Node (for AoT issues):** `node --version` =   
6.9.4

**Comment by DzmitryShylovich** [comment]
> <text-box required>

will initialize `required` input with an empty string this is why `<span *ngIf="required">(required)</span> is not showing` is not showing

**Comment by DzmitryShylovich** [comment]
There's already a feature request https://github.com/angular/angular/issues/14761 to change the default behavior

**Comment by Bidthedog** [comment]
Thanks - worth observing that applying the required attribute renders when binding is used - but the component property doesn't set. It makes sense, but it's confusing, especially to beginners such as myself.

**Comment by DzmitryShylovich** [comment]
> applying the required attribute renders when binding is used - but the component property doesn't set

example?

**Comment by Bidthedog** [comment]
Look at my plunkr, it's all there - detail in my first post

**Comment by mhevery** [comment]
closing as dup of https://github.com/angular/angular/issues/14761
