### ISSUE TITLE
aio: add responsive TOC widget

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14885]
Feature: add table-of-contents widget that floats on the page like MDN’s “In this article”.

Example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor

Make it responsive. MDN's floats at top-right when the browser is wide; turns into a zippy (accordion) when the page is narrow.

**Comment by wardbell** [comment]
Discussed in an internal conversation, reproduced here:
<hr>
I like how this google [Service Worker documentation page](https://developers.google.com/web/fundamentals/getting-started/primers/service-workers) works and I think we can implement it pretty quickly if we choose to do so.

*When very wide*
- Logo instead of hamburger. Click logo to go to site home.
- User settings menu item (vertical “…”); we’ll need it!
- 3-panel: sidenav, main, toc
- sidenav and toc scroll independently of main so they never disappear (as our sidenav does now)
- Top menu items do have a hover response but do NOT ripple. We don’t have to ripple to match MD standard.
- TOC items light up (light blue) when you’re in the corresponding section of the doc.

*When normal (>1040px)*
- Logo instead of hamburger.
- Top menu scrolls left right with < and > buttons
- toc move between title and content
- toc appears in a four line expando with “…” and rotating caret to draw your attention
- `<h2>` has an up-arrow on the right that takes to `#top_of_page#

*When narrow (720px)* (mobile)
- Like normal plus ...
- Hamburger appears to open/close sidenav. The name of the site (”Web”) remains; clicking it takes you home.
-  Most top menu items are gone. Not reproduced in left nav (I prefer our way)
-  User settings and search remain at top
- Search is just the magnifying glass icon; click to reveal search box
- Breadcrumbs above the doc title tell you where you are in the left nav hierarchy

**Comment by wardbell** [comment]
See PR #16078

**Comment by petebacondarwin** [comment]
We now have this.
