### ISSUE TITLE
Basic usage example

### ISSUE THREAD

**Issue by pumpk1n** [angular/angular#1488]
Hey!

I saw today that there are a couple of bundled js at this link: https://code.angularjs.org/2.0.0-alpha.20/
I really want to try out Angular 2 so I'm happy to see these bundles. But simply I just can't get it working at all. Could someone just make a real easy example please that uses a single-file bundle with a simple component? I think it would be really helpful for many of us.

Thanks!

**Comment by PascalPrecht** [comment]
Hey @pumpk1n 

this is not really a single-file bundle, but at least a simple way to start: https://angular.io/docs/js/latest/quickstart.html

There also a nice open source boilerplate project by @pkozlowski-opensource which you might want to check out: https://github.com/pkozlowski-opensource/ng2-play

Hope that helps!

**Comment by pkozlowski-opensource** [comment]
Actually we've got a single-bundle file available now at: https://code.angularjs.org, ex.: https://code.angularjs.org/2.0.0-alpha.20/

This file can be used as in this plunk: http://plnkr.co/edit/cPEKMOufrVhyGbfeHLnX?p=preview

There is still more work needed on making it even easier on people, documenting things etc.

**Comment by pkozlowski-opensource** [comment]
OK, I think that we've given all the pointers to @pumpk1n - at least ones we've got for now. The formal documentation is work in progress and will be available at https://angular.io/docs/js/latest/

Docs are high priority and being worked on, so I don't think there is any reason to keep this issue open.
