### ISSUE TITLE
Error: Provider parse errors:↵Cannot instantiate cyclic dependency!

### ISSUE THREAD

**Issue by smajazayeri** [angular/angular#14893]
I developed a custom error handler which implements Angular2 Error Handler class. My custom error handler uses a logger service to log errors. The code looks like as follows:

`export class CustomErrorHandler implements ErrorHandler {
   constructor(private logger: LoggerService) {}
    handleError(error: any): void {
        logger.error('....');
    }
}`

However, since the logger service uses Angular2 router, I cannot inject the logger service to the custom error handler! Running the above code throws the following exception!

`Error: Provider parse errors:↵Cannot instantiate cyclic dependency!`

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by smajazayeri** [comment]
Thanks for the prompt reply. IMO, it falls in Angular2 bugs section as both Error Handler and Router are part of Angular2 core. Although I'll create a case in SatckOverflow, I wonder if you can help me in this regard!

**Comment by DzmitryShylovich** [comment]
> it falls in Angular2 bugs section as both Error Handler and Router are part of Angular2 core

ok. please add a plunkr

**Comment by smajazayeri** [comment]
Sorry I didn't get you! What do you mean by "add a plunkr"?

**Comment by DzmitryShylovich** [comment]
reproduce the error here http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview

**Comment by Toxicable** [comment]
@smajazayeri Have you been able to reproduce your error in the plunkr template that was provided?

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).

**Comment by santoshsas** [comment]
For any one who is facing this issue remove Router from dep
{
        provide: Http,
        useFactory: httpFactory,
        deps: [XHRBackend, RequestOptions]
    }

**Comment by vytautas-pranskunas-** [comment]
I have simillar issue, not sure how to solve this...

**Comment by AshwinDfd** [comment]
I found a solution in which we do not inject the Router service directly in the constructor but use an Injector service to inject it dynamically inside the handleError function.
 `
export class ErrorHandlerService implements ErrorHandler {
  constructor(
       // Because the ErrorHandler is created before the providers, we’ll have to use the Injector to get  them.
       private injector: Injector,
   ) { }

   public handleError(error: any) {
        const router = this._injector.get(Router);
        router.navigateByUrl("/");
    }
}
`

Hope this helps. :)
Reference article: [https://medium.com/@aleixsuau/error-handling-angular-859d529fa53a](url)
