### ISSUE TITLE
All exceptions are being swallowed by Zone.js

### ISSUE THREAD

**Issue by fredsa** [angular/angular#1489]
When using angular dev build (alpha-20), I tried to register window.onerror listener to intercept all errors, but noticed that several errors were not making it into my handler.

The particular scenario was a typo in my ES6 code, which threw while the code was being transpiled by the module loader. Module loader correctly rethrows this error, but then Zone catches it and console.logs the stack trace without forwarding the error to any other error handlers. This behavior is surprising.

Ideally the zone code should augment the current exception to attach the long stack trace to it and then rethrow it. Or this behavior should be documented and configurable.

**Comment by vicb** [comment]
see https://github.com/angular/angular/issues/1344

**Comment by btford** [comment]
Zones give an onError hook – I'd expect angular's exception handler to use this feature.

**Comment by yjbanov** [comment]
What's the status of this issue? Fixed or should we push to alpha-29?

**Comment by btford** [comment]
I haven't taken a look at it – @fredsa are you seeing this on the most recent beta still? So much has changed since then. Do you have a reproduction?

**Comment by naomiblack** [comment]
I'm demoting this one to backlog for now. @fredsa let us know if it's still an issue for you?

**Comment by naomiblack** [comment]
@IgorMinar we need to know if there's a repro case for this.

**Comment by IgorMinar** [comment]
@fredsa's repro: http://plnkr.co/edit/lYEwRcj3ZQc1TTIbXdxZ?p=preview

however I don't think that this repro is the only problem. @johnlindquist mentioned during his presentation at AngularU that there are other exceptions being swallowed during bootstrap. @johnlindquist do you have a repro?

**Comment by IgorMinar** [comment]
@caitp  can you please look into this issue? I suspect that the issue is with long-stacktraces zone, but we need to investigate to be sure.

**Comment by vicb** [comment]
- `NgZone` captures exceptions and forward them to the error handler,
- The default error handler `console.log` error,
- You can pass a custom error handler during the `bootstrap()` as the 3rd component

IIUC the original issue, the requested feature (a custom error handler) is supported since ever (or almost). Might be a doc only issue ?

**Comment by IgorMinar** [comment]
I think that problem is the default behavior. I think we should rethrow by default and if you want to log stuff only, then that should be an opt-in.

**Comment by caitp** [comment]
Debugging, even with a custom error handler which throws, it gets handled and used to reject a promise. The unhandled rejection doesn't seem to be logged in whatever promise implementation is being used, which is sort of weird

**Comment by caitp** [comment]
I think this is blocked on https://github.com/jakearchibald/es6-promise/issues/70, which would solve this. For the time being we probably want to keep logging by default, because the thrown exception will just be eaten.

**Comment by caitp** [comment]
As a side-note, in the v8/Blink implementation, unhandled rejections are only printed, and are never passed to the onerror handler https://chromium.googlesource.com/chromium/blink/+/7cfccdd6ae324eb3998ccb683969f39f0c6b15f4/Source/bindings/core/v8/RejectedPromises.cpp#88 --- plus this works inconsistently in different browsers. Promises kind of suck this way

**Comment by caitp** [comment]
So uh, per the comments above, changing the default error handler to throw won't help with a good number of exceptions, and logging and throwing by default will be very spammy in non-promise cases. Making es6-promise throw on unhandled rejections would help, but is not a super-realistic goal, and still doesn't really solve the problem.

**Comment by vicb** [comment]
Also see https://github.com/tildeio/rsvp.js/issues/386 (related to uncaught Promises)

> Making es6-promise throw on unhandled rejections would help, but is not a super-realistic goal

Making es6-promise throw would be a departure from the current browsers behavior (plus there might be false positive as described in the link above). IMO it should only be considered for dev mode.

**Comment by caitp** [comment]
I don't think the "macro-task false positive" is realistically something that people will run into, and if they do it won't really matter.

as noted before, the Chrome thing does not actually throw anything, it just logs to the console --- the window.onerror handler never gets triggered (which is what is being asked for by the OP, IIUC). This is just not how promises work anywhere (which might be a shame, and might be something https://github.com/whatwg/javascript could add as a thing for browser environments to do)

**Comment by fredsa** [comment]
I'd like to have a global error handler of some sort which can, either at
development time or in production builds, intercept the truly unexpected
exceptions and do something with them.

- In development this is useful for showing a cleanly formatted and
detailed exception in the browser UI or elsewhere.

- In production this is useful to inform the user that the web app is (now)
broken in some expected way and what she should do about. Then, if
possible, one could report the exception back for further analysis.
​
I'm okay with having to install more than one error handler hook, as long
as these hooks are all clearly documented. In fact I expect there to be at
least two types of error handlers:
1. Error handlers which work within Angular land and deal with data issues,
network connectivity issues, application logic bugs and whatnot
2. Error handlers for when things go wrong at a lower level (e.g. app
bootstrapping) or outside of Angular (e.g. plain old JS interacting with
the Angular app)

**Comment by caitp** [comment]
the error is already logged in the plnkr, by the default exception handler. It never hits `window.onerror`, because promise rejections just don't do that anywhere (although I agree it might be useful if they did, so I've brought it up on whatwg/javascript).

If you wanted to explicitly handle the bootstrapping error, you could `bootstrap(...).catch(function(e) { console.error(e); });` or something.

I think this is working as expected.

**Comment by IgorMinar** [comment]
Relevant discussion in the web spec land: https://lists.w3.org/Archives/Public/public-whatwg-archive/2015May/0051.html

@caitp's proposal to do:
```
bootstrap(...).catch(function(e) { console.error(e); });
```

works but only for errors thrown during bootstrap. any other error will not be caught in this way.

We could allow users to register custom error handlers via zones, but that will not solve the issue with breaking on "uncaught" exceptions.

**Comment by caitp** [comment]
https://github.com/domenic/unhandled-rejections-browser-spec Domenic is working on this I guess, which sort of solves the problem (although I think a number of the features in that proposal don't add a whole lot of value) --- He says it's implemented in Blink behind a flag, but I don't believe this to be true

**Comment by naomiblack** [comment]
@caitp pushing to alpha-31 -- can you update whether you're working on this or need anything?

**Comment by caitp** [comment]
I don't think this bug is actionable, at least not in this codebase

**Comment by naomiblack** [comment]
@vsavkin any other suggestions? Otherwise, I think I'll agree with @caitp  and close.

**Comment by vsavkin** [comment]
Agree with @caitp. This does not seem to be actionable.

**Comment by GaryChamberlain** [comment]
I'm building an app that works fine on a laptop (chrome), works fine on IOS (Safari) but crashes on IOS (Chrome).  The template content is being generated but then it stops.

I have no way of seeing the console output in IOS/Chrome.  For testing, to help determine the issue, I'd like to log to document.body instead of the console.  Is there a way to do that?  I tried window.onerror but no dice.

**Comment by NikGovorov** [comment]
Is it related issue https://github.com/angular/zone.js/issues/239? Can we at least in angular ```catch```(and log) all promises from Lifecycle methods?
