### ISSUE TITLE
Change Detection and/or Zone issue - not updating the IU (2.4.9 and RC.2)

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#14892]
I'm working on a file upload component, and you can see how it looks/kind-of-works here - http://ngx.azurewebsites.net. Click on 'Select files to Upload' button, choose some files (preferably 2-3Mb in size, to see the effect). Open the console to see some important output. **It does NOT upload anything**.

So there's this Uploader component and underlying service which actually uploads files (I use fake service on that page). Now, every file is split in pieces before actual upload, then it's uploaded piece by piece. And the service is doing this by emitting an Observable:

```
uploadFiles$(filesToUpload: Array<IlgUploadFileData>): Observable<Array<IlgUploadFileData>>;
```

so, it emits new array (immutable) every time it uploads a piece (this IlgUploadFileData). This is all good.

The problem is the Uploader component does not change anything in its UI while the service is uploading files. You can see it when you click 'Start' (presuming you've selected some files). If this would work, you'd see progress bar changing its value. But it doesn't. The only way you can force changes is clicking on that yellow  'Force UI change' button **while it's uploading**. That click makes CD work. But why without it?

Here's the repo of my pet project where you can see that code, you need to look into this folder https://github.com/alvipeo/zone-issue/tree/master/src/app/ilgGallery/azureUploader. All code is there. Feel free to play with it.

Basically, here's the code in the Uploader component:
```
            this.uploadService
                .uploadFiles$(this.selectedFiles)
                .sample(Observable.interval(1000))
                .subscribe(
                (arr: Array<IlgUploadFileData>) => {
                    if (this.selectedFiles !== arr) {
                        this.selectedFiles = arr;
                    }
                },
                err => {
...
                },
                () => {
                    // console.log(Zone.current.name);
                    this._uploadInProgress = false;
                    this._uploadComplete = true;

                    console.log("upload done");
                });
```
and Uploader template:
```
                <div *ngIf="selectedFiles">
                    <ilg-uploader-filelist [filesToUpload]="selectedFiles"></ilg-uploader-filelist>
                </div>
```

File list is pretty simple:
```
@Component({
    selector: 'ilg-uploader-filelist',
    changeDetection: ChangeDetectionStrategy.OnPush,
    templateUrl: "./uploadFileList.component.html"
})
export class IlgUploaderFileListComponent implements OnInit {
    private _files: Array<IlgUploadFileData>;
    get filesToUpload(): Array<IlgUploadFileData> {
        return this._files;
    }
    @Input() set filesToUpload(fileArray: Array<IlgUploadFileData>)  {
        console.log("IlgUploaderFileListComponent: @Input() changed");
        this._files = fileArray;
    }

    constructor() { }

    ngOnInit() { }
}
```
and its template:
```
<div class="row" *ngFor="let file of filesToUpload">
    <div class="col-md-3"><small class="text-uppercase">{{ file.name }}</small> <small><em>({{ file.size }} bytes)</em></small></div>
    <div class="col-md-9">
        <div class="progress">
            <div class="progress-bar" [style.width]="file.progress + '%'" role="progressbar" aria-valuenow="set here" aria-valuemin="0" aria-valuemax="100">
                <ng-template [ngIf]="file.progress > 0">{{ file.progress }}%</ng-template>
            </div>
        </div>
    </div>
</div>
```

ChangeDetectionStrategy.OnPush doesn't play any role here, it can be commented out. It won't help.

**Comment by alexzuza** [comment]
> ChangeDetectionStrategy.OnPush doesn't play any role here, it can be commented out. It won't help.

I commented it and it works. What do you except if you have the following structure:
```
     EditVideoComponent (OnPush)
                  ||
                  \/
    EditVideoFormComponent (OnPush)
                  ||
                  \/
   IlgAzureUploaderComponent
                  ||
                  \/
  IlgUploaderFileListComponent  (OnPush)
```

Use `ChangeDetectorRef.markForCheck()` to open parents for checking

**Comment by Toxicable** [comment]
>ChangeDetectorRef.markForCheck()

If you need to do this you're probably doing something wrong

**Comment by alvipeo** [comment]
@alexzuza oh, of course! thanks, man! This is what happens when you forget you use ngrx! :) ok, but now I need to get rid of those OnPush from a parent... ok

thank you guys!

**Comment by alvipeo** [comment]
but still the question, what would be the best way of doing this with ngrx (when everything is OnPush)? really use ChangeDetectionRef?

**Comment by alexzuza** [comment]
I think the best way is using AsyncPipe

**Comment by alvipeo** [comment]
huh?

**Comment by alvipeo** [comment]
So my question is - if I create a component, how can I make sure it works even inside "OnPush tree" - when all/some parents use OnPush?

**Comment by Toxicable** [comment]
@alvipeo  At this point it sounds like you are asking for Support of which this issue tracker is not suitable for,  please repost your question on [StackOverflow](http://stackoverflow.com/) using tag `angular` or on https://gitter.im/angular/angular

**Comment by alvipeo** [comment]
Yeah, thank you guys! closing it now.
