### ISSUE TITLE
can  angular decide which module to bring for the frontend or always travel the complete application with all the modules?

### ISSUE THREAD

**Issue by alejandrohn** [angular/angular#14906]
[ x] feature request

ubuntu 14.04,webstorm, npm

* **Angular version:** 2.4.7

* **Browser:** [all | Chrome 54.028
 
* **Language:** [TypeScript 2.1.5| ES5]

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load

**Comment by IgorMinar** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
