### ISSUE TITLE
Universal "renderModule" gives Error: No NgModule metadata found

### ISSUE THREAD

**Issue by nicky-lenaers** [angular/angular#14903]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Error while rendering non-aot module on server.

**Expected behavior**

Render non-aot module on server.

**Minimal reproduction of the problem with instructions**

1. Clonse [this](https://github.com/robwormald/ng-universal-demo/tree/006f0e1bd1704fc173afcd9427172342abded6f8) repo
2. On [this](https://github.com/robwormald/ng-universal-demo/blob/006f0e1bd1704fc173afcd9427172342abded6f8/src/express-engine.ts#L16) line, change `renderModuleFactory` to `renderModule` (don't forget to import `renderModule`)
3. On [this](https://github.com/robwormald/ng-universal-demo/blob/006f0e1bd1704fc173afcd9427172342abded6f8/src/main.server.ts#L15) line, change `AppServerModuleNgFactory` to `AppServerModule` (already imported)
4. Run using `npm start` and visit site.

**What is the motivation / use case for changing the behavior?**

Unable to compile Angular App without using ngfactory modules.

**Please tell us about your environment:**

Mac OSX
Visual Studio Code
Node.js / NPM

* **Angular version:** 4.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2.1

* **Node (for AoT issues):** `node --version` =   
7.7.0

I have cloned the minimal repo of @robwormald as seen [here](https://github.com/robwormald/ng-universal-demo/tree/006f0e1bd1704fc173afcd9427172342abded6f8). As stated in the release of [4.0.0-rc.1 Universal Section](https://github.com/angular/angular/blob/4.0.0-rc.1/CHANGELOG.md#universal) there is now a `renderModuleFactory` function. In the above mentioned repo, I changed `renderModuleFactory` to `renderModule` in `src/express-engine.ts` and passed in a non-aot module `AppServerModule` instead of `AppServerModuleNgFactory` in `src/main.server.ts`.

When compiling, I get this error:

```sh
Error: No NgModule metadata found for 'e'.
```

**Comment by vikerman** [comment]
The AOT plugin in webpack is essentially stripping decorators from the modules(This is how AOT works so that tree shaking works properly).

I changed the example here to use renderModule instead of renderModuleFactory. Essentially removed the AOT plugin and just doing vanilla tsc - https://github.com/vikerman/ng-universal-demo/commit/dd6e860482d6eb5ed1d01fb606886f12f06eb0b3

BTW - Never use renderModule in your production server - It compiles the templates every single request. It exists purely as an option we wanted to explore for dev mode. But even for that you better off just using the AOT version.
