### ISSUE TITLE
Errors are not always thrown during second pass change detection

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#14908]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Whether `Expression has changed after it was checked.` error is thrown  during second pass change detection depends on component order and their placement in the template.

**Expected behavior**
It shoudn't depend on component placement in the template.

**Minimal reproduction of the problem with instructions**
Let's consider this example:
[https://plnkr.co/edit/6hgFUfo6hhJrFQIOrlmt?p=preview](https://plnkr.co/edit/6hgFUfo6hhJrFQIOrlmt?p=preview)
It throws `Expression has changed after it was checked` as expected.
But when we change:
```html
<bar [bar]="test"></bar>
<foo (foo)="test=$event"></foo>
```
into:
```html
<foo (foo)="test=$event"></foo>
<bar [bar]="test"></bar>
```
it's fine for angular, but it (in my opinion) should throw error.

For the plunker example, we have following tree:
```
App
|- Bar
|- Foo
```
And change detection is performed in this order: App -> Bar -> Foo (output changed, markForCheck path to root) -> App -> Foo. `{{bar}}` expression changed after change detection was performed on Bar component => throw error.
But when we change order of Foo and Bar, change detection is performed in this order: App -> Foo (output changed, markForCheck path to root) -> App -> Foo -> Bar. It this case, `{{bar}}` changed not once, but twice, but it's ok for angular since the change detection for Bar is performed last.

**What is the motivation / use case for changing the behavior?**
Inconsistent behavior might be misleading and is error prone.

* **Angular version:** 2.4.8

**Comment by atscott** [comment]
Closing as working as expected. The act of checking/executing `foo` causes external values read by `bar` to change. Because the input for `bar` was already checked, the value has "changed after it was checked". This behavior _is_ consistent: the error will always throw when this occurs.
