### ISSUE TITLE
When to compile the file size can be less than 100KB？

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular#14904]
eg : vuejs  ?

**Comment by istiti** [comment]
Dont understand

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
