### ISSUE TITLE
Expressions in event handlers fail to complain about undefined parameters

### ISSUE THREAD

**Issue by fredsa** [angular/angular#1490]
version alpha-20

Given
```
<my-component
  (win)="tallyWin(i_do_not_exist)">
</my-component>
```

I would expect `i_do_not_exist` to cause either a compile time error or at least a run time exception.
Instead, `i_do_not_exist` is simply passed to the `tallyWin()` function as `undefined`. No exception is logged or thrown.

**Comment by vicb** [comment]
> Instead, i_do_not_exist is simply passed to the tallyWin() function as undefined

Expressions use host langage (ie JS or Dart) semantics. However this is something that could probably be caught by linters / IDEs.

**Comment by mhevery** [comment]
Yes, this should be an error.

**Comment by mhevery** [comment]
@vsavkin / @tbosch is this still an issue? can this be closed?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

The new offline compiler will complain of method signatures.
