### ISSUE TITLE
Rolup 5.2.0 failing with 4.0 rc2 and RxJS 5.2.0

### ISSUE THREAD

**Issue by hugodes** [angular/angular#14900]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Rollup fails with rxjs 5.2.0

[14:54:23] Starting 'rollup'...
'default' is imported from external module 'rollup' but never used
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected token
    at error (/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/node_modules/rollup/dist/rollup.js:7997:2)
    at tryParse /node_modules/rollup/dist/rollup.js:7700:10)
    at new Module (/node_modules/rollup/dist/rollup.js:7735:14)
    at node_modules/rollup/dist/rollup.js:9481:17

**Expected behavior**

Rollup succeeds with the latest version of rxjs

**Minimal reproduction of the problem with instructions**

Compile an anguar 4.0 rc2 project with rxjs v 5.2.0

**What is the motivation / use case for changing the behavior?**
transpile and then rollup

**Please tell us about your environment:**

MacOS 10.12.3 with Homebrew
* **Angular version:** 4.0 rc2

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   7.7.1

**Comment by sod** [comment]
The latest version of rollup as of 3.3.2017 is 0.41.4 - https://github.com/rollup/rollup/releases

**Comment by hugodes** [comment]
My bad, I men rxjs 5.2.0, rollup process works fine with rxjs 5.1.0

**Comment by chuckjaz** [comment]
@hugodes Can you edit the report and the description to better describe the problem based on your last comment?

**Comment by thelgevold** [comment]
RxJs does not publish an es2015 build, so you have to convert their commonjs modules to es2015 using the commonjs plugin.

Here is a working configuration with rc1 and rxjs 5.0.1
```
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify';

export default {
    entry: 'main.js',
    dest: 'dist/bundle.js',
    sourceMap: false,
    format: 'iife',
    plugins: [
      commonjs({
          include: 'node_modules/rxjs/**'
      }),
      nodeResolve({
          jsnext: true, module: true
      }),
      uglify()
      
    ]

}
```
Are you using the common

**Comment by hugodes** [comment]
@chuckjaz : yes, done.

@thelgevold: yes I'm using commonjs also, here is my code:

`import rollup      from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify'

export default {
  entry: 'main.js',
  sourceMap: false,
  format: 'iife',
  plugins: [
    nodeResolve({jsnext: true, module: true}),
    commonjs({
      include: ['node_modules/rxjs/**', 'node_modules/angular2-jwt/**', 'node_modules/mydatepicker/**', 'node_modules/file-saver/**'],
      namedExports: {
        'node_modules/mydatepicker/index.js': [ 'MyDatePickerModule' ]
      }
    }),
    uglify()
  ]
}`

**Comment by jasonaden** [comment]
@hugodes I can't reproduce this issue. Please confirm that the example in https://github.com/jasonaden/angular_tests (sub-directory project "update_dependencies").

**Comment by hugodes** [comment]
Ok, I'll check ASAP

**Comment by hugodes** [comment]
Ok, we have now moved to angular-cli so we're not using rollup anymore.
Hence I couldn't make an attempt at reproducing the problem.
