### ISSUE TITLE
Feedback on Angular 4.0-rc0 success with warnings and exception on router.event for querystring.

### ISSUE THREAD

**Issue by MatteoNY** [angular/angular#14901]
Good news for my Angular 2.x project I did get it to work.
Initially my project failed on the snippet (shortened), please see below.
It appears the code may be noted as experimental but I will need a solution to obtain the querystring values for a use case scenario. The offending part of the code was with the s.url. 

Additional notes:
1) I found a ton of warnings `"The <template> element is deprecated. Use <ng-template> instead..."`
It appears to be coming from MD2.  

2) Angular-CLI latest -rc0, see stack info below. I had to use an older .angular-cli-.json for some reason I found it pointing to an incorrect "tsconfig". The one that is working is: 
   "tsconfig": "tsconfig.json". The one that did not work had something like;
   "tsconfig": "tsconfig-app.json" this file did not exist so the Angular-cli had failed. 
Once I noticed and correct 4.0-rc0 the angular-cli ng serve worked. :-)

```ts 
 this.router.events
       .take(1)
       .subscribe(s => {
         let params = new URLSearchParams(s.url.split('?')[1]);
         var QSValue = params.get('flightkey');
         //    console.info("qs: ", QSValue);
         var paramsTraveler = new URLSearchParams(s.url.split('?')[1]);
         var QSValueparamsTraveler = params.get('key');
        // console.info("qs: ", this.QSValueparamsTraveler)

       // *** after getting queryString call the service with parm.
       //  var dataInit = this.service.getData(QSValue)
         
   });
```

CURRENT STACK: ISSUE ON BOTH PC & Mac
Note: using NPM and Yarn mostly Yarn:

```
@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: win32 x64
@angular/common: 4.0.0-rc.2
@angular/compiler: 4.0.0-rc.2
@angular/core: 4.0.0-rc.2
@angular/forms: 4.0.0-rc.2
@angular/http: 4.0.0-rc.2
@angular/material: 2.0.0-beta.2
@angular/flex-layout: 2.0.0-rc.1
@angular/platform-browser: 4.0.0-rc.2
@angular/platform-browser-dynamic: 4.0.0-rc.2
@angular/router: 4.0.0-rc.2
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 4.0.0-rc.2
```

**Comment by DzmitryShylovich** [comment]
ok, so what's the problem? :)
and please add a plunkr

**Comment by MatteoNY** [comment]
Thanks for your response, no major problem with the update. The exception is now getting queryString values from url.  The code snippet I had worked with A v:2 but broke with A v:4. I tried using some other approach, for example, this.activatedRoute.queryParams.subscribe((params: Params) => {
        let QSValue = params['flightkey'];
        console.log(QSValue);

and it also fails returning undefined value for QSValue. Looking for A v:4 solution to getting simple QueryString value from a URL.  Thanks

**Comment by MatteoNY** [comment]
DzmitryShylovich : Sorry, no plunker for A-v4-rc0. My code worked in A-v2.x. My original code snippet was from Angular.io but noted as "experimental". At some point experimental code should become a reality or reference to reality. In some use cases queryStrings from a URL will be required. I do like how the experimental code hid the query string from the address-bar in the browser.

**Comment by DzmitryShylovich** [comment]
> Sorry, no plunker for A-v4-rc0

you can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point

**Comment by MatteoNY** [comment]
Many thanks for the pinkr link: I was exploring a bit and found that if I take the take(1) out it continues but returns null. I will test on my local machine not sure I can pass querystring in pinkr. Here is my link:
http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview

**Comment by DzmitryShylovich** [comment]
you forgot to save the plunkr

**Comment by MatteoNY** [comment]
http://plnkr.co/edit/kGKyeTf2e2CWb1Hjsvry?p=preview

I did and downloaded it. I think this is it I can visit from another browser. :-)

**Comment by DzmitryShylovich** [comment]
why are you doing this? `this.router.queryParams.subscribe(...)` will give you query params

**Comment by MatteoNY** [comment]
In my pinkr version I am using the version that originally worked in my Angular 2. 4.8 version fine. 
When I updated to Angular 4-rc2 it broke.  The code in my pinkr is from Angular.io docs (marked experimental): 
https://angular.io/docs/ts/latest/api/http/index/URLSearchParams-class.html

The Angular-cli compiler on my local machine provides the following error: 
ERROR in .../seats-app.component.ts (312,44): Property 'url' does not exist on type 'Event'.
  Property 'url' does not exist on type 'RouteConfigLoadStart'.)

I just noticed some new code that uses MyQueryEncoder and extends QueryEncoder I did not see this before. I will give this a try. 

Nice-to-have: It would be great in the Angular.io docs can add "Last updated date: " some place on the page as even offer a notify email if you subscribe to angular.io.  Thanks again for all the great work and support with Angular.

**Comment by MatteoNY** [comment]
I did try "why are you doing this? this.router.queryParams.subscribe(...) will give you query params" did not work for some reason.

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/guide/router.html#!#query-parameters

**Comment by MatteoNY** [comment]
Looks like it's using Angular 2.4.9 not 4 in the latest link.  
Javascript works using var urlParams = new URLSearchParams(window.location.search).
In my original Angular 2 version URLSearchParams worked but broken in Angular 4-rc2 that is why I'm posting. It appears the router.event may not have the .url value that is needed. For a workaround I will use window.location.search and when the Angular 4 version of the router works I will use the router event's url. 
Thanks again for all your help. 
JS reference: https://davidwalsh.name/query-string-javascript

**Comment by MatteoNY** [comment]
I did get it to work but it has to do with the type being returned from the router.event. When I added the type of any then I could access .url. I did try to use the type of "NavigationStart",  router "Event" and "Parms" but typescript did not like it. Any is working for now. This should be noted to fix or update docs on the best practice.  :-) 

 // subscribe to router event marked as !experimental
 // ?f=a123&t=11
   this.router.events
   .take(1)
   .subscribe( r => {
      let qs:any = r;
      let params = new URLSearchParams(qs.url.split('?')[1]);
      let qsF = params.get('f');
          console.log (qs);
          console.log ("qs0... " + qsF);
      let qsT = params.get('t');
          console.log ("qs1... " + qsT);
   });

**Comment by DzmitryShylovich** [comment]
> When I added the type of any then I could access .url

`Event` is a union type. And not all event have `url` property this is why you can't access it.

**Comment by MatteoNY** [comment]
Many thanks!! :-)

**Comment by IgorMinar** [comment]
I think we are tracking all of these issues in cli and material projects respectively. I'll keep this issue open until we can confirm that they have been resolved.

**Comment by vicb** [comment]
I don't see any specific pb with the router here. Please re-open an issue with more details if there is a real pb. Thanks

**Comment by DzmitryShylovich** [comment]
@vicb we introduced 2 new events for lazy loaded router and those events don't have `url` property. Which breaks code like
```
this.router.events.subscribe(event => event.url // error, url doesn't exist on type Event)
```
