### ISSUE TITLE
FormData not work!

### ISSUE THREAD

**Issue by JansenMoscol06** [angular/angular#14918]
Hi, 
`let formData: FormData = new FormData()
formData.append('key','value')
console.log(formData)
`
Result in console:
`
FormData { }
`
Alguien me puede ayudar ?

**Comment by DzmitryShylovich** [comment]
http://stackoverflow.com/questions/17066875/how-to-inspect-formdata

**Comment by chuckjaz** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Please see @DzmitryShylovich  link above for an answer to your question.

**Comment by JansenMoscol06** [comment]
You can say why type FormData only recognize the method append and not others? (get, keys, set, has) ?

**Comment by chuckjaz** [comment]
https://www.w3.org/TR/2010/WD-XMLHttpRequest2-20100907/#the-formdata-interface
