### ISSUE TITLE
@ContentChildren memory leak with ngTemplateOutlet

### ISSUE THREAD

**Issue by youdz** [angular/angular#14919]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`@ContentChildren` somehow gets hold of children that are passed in a template and instantiated through `[ngTemplateOutlet]`, and never gets rid of them even if they are destroyed.

**Expected behavior**

I am not sure what the correct behavior for `@ContentChildren` here is (should it see the children or not?) but either way it should not keep a reference to destroyed children. This creates potentially a large memory leak.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/esib13wg0pTmzVEKhNNM?p=preview
Click on the button a few times, you will see that the QueryList keeps growing. On further inspection, you could see that the children in the list are the ones that were destroyed on each previous toggle.

* **Angular version:** 2.4.9

* **Browser:** all

 
* **Language:** all

**Comment by alexzuza** [comment]
I think here is the same issue https://github.com/angular/angular/issues/14835

**Comment by nikidimi** [comment]
I have a similar issue when using NgbTabset from ng-bootstrap and ViewChildren.
The query list just keeps getting bigger and bigger with every tab change.

Plunker:
http://plnkr.co/edit/wOCLhhbAlJEraEie2Tl2?p=preview
Switch between P1/P2 and then click "Log children" and it will log the query list to the console.

**Comment by adammedford** [comment]
Just wanted to pile on here since this is currently causing some pretty massive performance issues for me. I've managed to reproduce this with both ng-bootstrap components and the ngx-datatable so I suspect this is a pretty common use case that it leaks on. (As opposed to me doing something wonky/hacked together.)

**Comment by mhevery** [comment]
Dup of https://github.com/angular/angular/issues/15578 ?

**Comment by tbosch** [comment]
Yes, this is a duplicate.
