### ISSUE TITLE
Failure to declare directives used by component should result in compile time error

### ISSUE THREAD

**Issue by fredsa** [angular/angular#1491]
version alpha-20

This `*for` directive silently fails to do anything…
```
<div *for="var t of tabs">
  this is a div {{t.name}}
</div>
```

…if the corresponding component does not declare the directive as shown here…

```
@Component({
  selector: 'tab-group'
})
@View({
  templateUrl: './tab_group.html',
  // directives: [For], // <----------- NOTE: COMMENTED OUT
})
class TabGroup {
  constructor(@Query(Tab) tabs: QueryList) {
    this.tabs = tabs;
  }
}
```

A lack of both a compile time and runtime error to alert the developer to this results in developers spending a lot of time looking in the wrong place for a reason why their component isn't rendering as expected.

**Comment by SekibOmazic** [comment]
Related to:
#1451 
#1293

**Comment by mhevery** [comment]
Will be solved by: https://github.com/angular/angular/issues/2014
