### ISSUE TITLE
TS2035 AnimationDriver

### ISSUE THREAD

**Issue by tyrone98** [angular/angular#14920]
**I'm submitting a ...**  (check one with "x")
```
[ *] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I use webpack for develop , When I upgrade to 4.0.0-rc.2 from 4.0.0-beta.2。
```
ERROR in [at-loader] node_modules\angular2-platform-node\node-platform.d.ts:1:10
    TS2305: Module '"D:/work/mercury/frontend/node_modules/@angular/platform-browser/typings/platform-browser"' has no exported member 'AnimationDriver'.

ERROR in [at-loader] node_modules\angular2-platform-node\node-renderer.d.ts:2:10
    TS2305: Module '"D:/work/mercury/frontend/node_modules/@angular/platform-browser/typings/platform-browser"' has no exported member 'AnimationDriver'.
```

**Expected behavior**
4.0.0-beta.2 

**Minimal reproduction of the problem with instructions**
Node 6.3.0
Angular 4.0.0-rc.2
Browser chrome

**Comment by Toxicable** [comment]
Similar to #14917

**Comment by matsko** [comment]
We did some file swapping across the codebase. Is there a way that you can test against master right now to see if the problem persists?

**Comment by matsko** [comment]
Now that RC4 is out, I'm closing this issue for now. Please reopen if this issue persists.

**Comment by CisSasGot** [comment]
I reopen this problem in https://github.com/angular/angular/issues/15332
