### ISSUE TITLE
file:// path support for router redirects (electron)

### ISSUE THREAD

**Issue by HalfLegend** [angular/angular#14929]
**I'm submitting a ...**
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using Angular with Electron, and everything works fine before I use router.
The angular-router cannot match the file path URL and the first page cannot display.

"E:/Product/electron-angular-sample/router/node_modules/elegular/src/window/elegular-window.html" is the starting page of Electron, where Angular is initialized.
I don't know why It translated ":" into "%3A".
I tried to put "E:/Product/electron-angular-sample/router/node_modules/elegular/src/window" in the "&lt;base&gt;" element and it is still not working.

**Stack Trace**
```
core.umd.js:3064 EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'E**%3A**/Product/electron-angular-sample/router/node_modules/elegular/src/window/elegular-window.html'
Error: Cannot match any routes. URL Segment: 'E%3A/Product/electron-angular-sample/router/node_modules/elegular/src/window/elegular-window.html'
    at new Error (native)
    at ApplyRedirects.noMatchError (file:///E:/Product/electron-angular-sample/router/node_modules/@angular/router/bundles/router.umd.js:1098:20) [angular]
```

**Expected behavior**
It should match file path URL correctly. 

**Minimal reproduction of the problem with instructions**
I am using a framework "elegular" and the sample:
     https://github.com/HalfLegend/electron-angular-sample/tree/master/router

framework:
    https://github.com/HalfLegend/elegular

**What is the motivation / use case for changing the behavior?**
    To use router in Electron.

**Please tell us about your environment:**
  Operating system : Win 10
  IDE: Web Storm
 package manager: npm
HTTP server: none (Desktop application, using Electron)

* **Angular version:** 2.4.7

* **Browser:**  Electron (Chrome)

* **Language:** TypeScript 2 and ES6

**Comment by DzmitryShylovich** [comment]
@HalfLegend I think this https://github.com/angular/angular/issues/13948 thread might be helpful

**Comment by HalfLegend** [comment]
Issue solved in new version. Nothing changed in my code, but it is working after I updated the angular version.

Thank you

**Comment by jasonaden** [comment]
Closing as it now works.
