### ISSUE TITLE
`@angular/animations` next and latest discrepancy

### ISSUE THREAD

**Issue by emilio-martinez** [angular/angular#14923]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
While `@angular/animations` is a new package, having the distribution versions show as below is problematic in scenarios where if the `package.json` has a range (`>=4.0.0-rc <5.0.0`) as the version for all  `@angular` packages, `@angular/animations@4.0.0-rc.1` will be installed whereas all the other packages will be on `4.0.0-rc.2`, resulting in a Peer Dependency error.

```
{ name: '@angular/animations',
  'dist-tags': { next: '4.0.0-rc.2', latest: '4.0.0-rc.1' },
...
```

Of course this can be resolved by setting a version such as `4.0.0-rc.2` for all `@angular` packages, but it might just be easier to set `next` and `latest` on `@angular/animations` to the same version, given that it's only existed on prerelease stages.

**Expected behavior**
Allow for a version range declared in the `package.json`, which is not a completely uncommon scenario, e.g., [@angular/cli](https://github.com/angular/angular-cli/blob/master/package.json#L46).

**Minimal reproduction of the problem with instructions**

* **Angular version:** `4.0.0-rc.2`

* **Browser:** No browser required
 
* **Language:** `TypeScript 2.1.6`

* **Node (for AoT issues):** `node --version` =  `v6.9.5`

**Comment by IgorMinar** [comment]
I resolved this manually. Unfortunately it seems that the latest tag cannot be deleted so we need to keep tag for this one package in sync with the `next` tag every time we release until 4.0.0 is released.

```
$ npm dist-tag add @angular/animations@4.0.0-rc.3 latest
+latest: @angular/animations@4.0.0-rc.3
```

```
$ npm info @angular/animations dist-tags
{ next: '4.0.0-rc.3', latest: '4.0.0-rc.3' }
```

**Comment by IgorMinar** [comment]
thanks for the report
