### ISSUE TITLE
4.0.0-rc.2 - es5 - CanDeactivate with EventEmitter 

### ISSUE THREAD

**Issue by uparlange** [angular/angular#14926]
**I'm submitting a ...**  (check one with "x")

[ * ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 

**Current behavior**
CanDeactivate does not work with EventEmitter !

**Expected behavior**
CanDeactivate should work with true/false and with EventEmitter

**Minimal reproduction of the problem with instructions**
https://embed.plnkr.co/tPtY1a31CnFqhNbzVViU/
--> Unable to return to Home when List Displayed

**What is the motivation / use case for changing the behavior?**
CanDeactivate should work with true/false and with EventEmitter

**Please tell us about your environment:**
Windows 7 / VisualCode / NPM / Express

* **Angular version:** 2.0.X
4.0.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

* **Node (for AoT issues):** `node --version` =   
Not concerned

**Comment by DzmitryShylovich** [comment]
did you try `.take(1)`?

**Comment by uparlange** [comment]
Can you be more specific ?

**Comment by DzmitryShylovich** [comment]
You need to complete the stream.

**Comment by uparlange** [comment]
Ok... Did you try with my plnkr sample... It does not seem to change anything... except having errors !

**Comment by DzmitryShylovich** [comment]
I'm not familiar with angular es5 but ts version works fine http://plnkr.co/edit/FGGSd80pDDp5HTCGGC8y?p=preview so it's something wrong with your config and not an angular issue

**Comment by uparlange** [comment]
Your sample is not the same as mine as i'm lazing loading the components.

**Comment by DzmitryShylovich** [comment]
Ok still works :)
https://plnkr.co/edit/1i9MtpkggOd5AZL0Nwfa?p=preview

**Comment by uparlange** [comment]
Humm ok.
What i don't understand is that it was working with 4.0.0-rc.1 and workaround described in #14603.
It is not working anymore with 4.0.0-rc.2

**Comment by tbosch** [comment]
@uparlange did this work in 2.x?

**Comment by tbosch** [comment]
@uparlange Your latest punker seems to work, i.e. I can navigate from Home to List and back...

**Comment by DzmitryShylovich** [comment]
@tbosch the latest plunkr uses rc1.
> What i don't understand is that it was working with 4.0.0-rc.1. It is not working anymore with 4.0.0-rc.2.

**Comment by DzmitryShylovich** [comment]
it does work with ts version so it's something wrong with es5 distribution. I'm not very familiar with it

**Comment by tbosch** [comment]
Ok, I can reproduce now if I change the latest plunker manually to use v2 (i.e. change `index.html` to load v2...)

**Comment by vicb** [comment]
Nothing has changed in the router in-between [rc1 and rc2](https://github.com/angular/angular/compare/4.0.0-rc.1...4.0.0-rc.2)

Night be related to #14603 / #14820 (the latter **was part of rc2**), @jasonaden could you please chime in ?

Note: seems to work with rc1 and no more in rc2 and rc3.

**Comment by jasonaden** [comment]
There was a change after rc.1 (move from babel back to rollup to generate UMDs) which made the workaround (adding to global Rx) stop working. We are looking at how to get a fix in for https://github.com/ReactiveX/rxjs/issues/2415 or a usable workaround that should fix this issue for the next RC.

**Comment by uparlange** [comment]
Meanwhile and as a workaround we can change the eventemitter way by a Promise.

canDeactivate:function(component)
{
	return new Promise((resolve) => 
	{
		resolve(true);
	});
}

**Comment by DzmitryShylovich** [comment]
@jasonaden don't look like anybody cares in rxjs repo :)

As a workaround I suggest to change impl and just check if object has `subscribe` property (like it was in rc1). It's nice to use observable symbol, but if it causes issues I think we can live without it. I can send a PR

**Comment by DzmitryShylovich** [comment]
@jasonaden done https://github.com/angular/angular/pull/15171
