### ISSUE TITLE
Allow transplanting of <template> ProtoViews into other ViewContainers

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1492]
## Goal

Have the ability to declare templates in one location, but have them rendered in another. 

## Implementation

1. The `View` should be created at declaration location, with local context, injection etc. (This also implies that we should have a `ChangeDetector` inserted at declaration location)
2. The Destination should receive the `View` and set local vars on it.
3. The Destination should insert the `View` into the `ViewContainer` (Render Location)

## Ionic Example

```html
<div>
  <template toolbar-part #i="index">
    <button (click)="onClick()">{{i}}:  {{action}}</button>
  </template>
</div>
```

some other place:
```html
<toolbar>
  <!-- place where the toolbar-part will be inserted -->
</toolbar>
```

```javascript
@Component({
  selector: 'toolbar'
})
class Toolbar {
  viewContainer:ViewContainer;
  constructor(viewContainer:ViewContainer) {
    this.viewContainer = viewContainer;
  }
  addView(view:View) {
    view.setLocal('index', this.viewContainer.length);
    this.viewContainer.add(view);
  }
}

@Viewport({
  selector: 'toolbar-part'
})
class {
  constructor(viewFactory:ViewFactor, toolbar:Toolbar) {
    var view:ViewRef = viewFactory.create();
    toolbar.addView(view);
  }
}
```

### Issues
- The template expressions need to be executed in the context of where the template is declared.
- The `View` created by the DOM is inserted in a different location.
- The insert location should be able to insert values into the inserted `View` provided that the template declares the variable.

### Table Example

```html
<virtual-table [data-source]>
  <template row-header-cell #row="rowIndex">
    {{row}} Row Header
  </template>
  <template col-header-cell #col="colIndex">
    {{col}} Column Header
  </template>
  <template cell #row="rowIndex" #col="colIndex">
    {{row}}:{{col}}
  </template>
</virtual-table>
```

### SVG Charts Example

```HTML
<bar-chart>
  <template chart-title>
  </template>
  <svg *x-axis>
    <g  ...>{{text}}</g>
  </svg>
</bar-chart>
```

Issues:
- [ ] context
- [ ] injecting the other `ViewContainer`
- [ ] getting hold of the `PortoView`

**Comment by blesh** [comment]
The final API for nf-graph looks like this pseudocode:

```html
<nf-graph width="100" height="100" min-x="0" max-x="100" min-y="0" max-y="20">
  <nf-x-axis output-named-var-as="tick"><text>{{tick.value}}</text></nf-x-axis>
  <nf-y-axis output-named-var-as="tick"><text>{{tick.value}}</text></nf-y-axis>
  <nf-graph-content>
    <nf-line [data]="lineData"/>
  </nf-graph-content>
</nf-graph>
```

One tricky thing is the `output-named-var-as` bit. The axis components essentially generate a range of values and pass them in as `tick` or some other named value to their inner templates... I don't know what the syntax is here.

The HTML output would look something like the following: (again pseudocode)

```html
<svg class="nf-graph" width="100" height="100">
  <g class="nf-x-axis">
    <g class="nf-x-axis-tick-group">
      <g class="nf-x-axis-tick-content"><text>1</text></g>
      <line class="nf-x-axis-tick-line" x1="0" x2="0" y1="80" y2="85"/>
    </g>
    <g class="nf-x-axis-tick-group">
      <g class="nf-x-axis-tick-content"><text>2</text></g>
      <line class="nf-x-axis-tick-line" x1="10" x2="10" y1="80" y2="85"/>
    </g>
    <!--- and so on... -->
  </g>

  <g class="nf-y-axis"> <!-- same for y axis --> </g>

  <g class="nf-graph-content">
    <path class="nf-line" d="..."/>
  </g>
</svg>
```

**Comment by naomiblack** [comment]
@tbosch we think you are working on this -- any status? :)

**Comment by tbosch** [comment]
Have a prototype locally, need to add tests. Will land together with the
changes to the ViewRef, ElementRef, ProtoViewRef.

**Comment by naomiblack** [comment]
@tbosch any update on this?

**Comment by tbosch** [comment]
Will finish this today
