### ISSUE TITLE
[platform-server]: Unable to set Title

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular#14936]
**I'm submitting a ...**  
```
[x] bug report
```

**Current behavior**
When trying to `setTitle` using either the `Title` service (from platform-browser) or even trying to manually set it through the `DOCUMENT`, neither are able to actually change the `<title>` in the server-rendered View.

Code example:
```
  constructor(
    private title: Title,
    @Inject(DOCUMENT) private document
    ) {}

  ngAfterViewInit() {
      this.title.setTitle(`This doesn't work`);
      this.document.title = `This doesn't work either :(`;
  }
```

![image](https://cloud.githubusercontent.com/assets/2574412/23589717/1552e9f6-01a0-11e7-88f6-f6a1c1e70400.png)

**Expected behavior**
In server-rendered view: `<title>Something got updated here</title>`

**Minimal reproduction of the problem with instructions**
https://github.com/MarkPieszak/ng-universal-demo/tree/title-bug
You can see in the [HomeComponent ](https://github.com/MarkPieszak/ng-universal-demo/blob/title-bug/src/app/home/home-view.component.ts#L29-L30)the code above trying to manipulate the Title 

**What is the motivation / use case for changing the behavior?**
Title update needed for SEO. `this.document.title = 'new title';` worked in previous angular2-universal.

* **Angular version:** 
4.0-rc2

* **Browser:** [all ]
 
* **Language:** [ TypeScript 2.2.1 ]

cc/ @vikerman @alxhub @gdi2290

**Comment by gdi2290** [comment]
when creating the fake document a few getters were also attached to the dom because angular depends on them.

.head
.body
._window
.title
