### ISSUE TITLE
Tests fail when a component in a feature module uses a service

### ISSUE THREAD

**Issue by ebrehault** [angular/angular#14934]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
My main module (foo in the example) contains a feature module (bar in the example), this feature module contains a service (ConfigurationService in the example) and a component (DisplayComponent in the example) which uses ConfigurationService. The component is exported by the bar module, and we use it in the foo module.
The application works fine, but the tests fail with the following error (note: in the test, BarModule is imported in configureTestingModule)
```
	Error: No provider for ConfigurationService!
	Error: DI Error
```
Note: it only happen with component, if I have a service (ManagerService in the example) in BarModule which uses the ConfigurationService and if we call this service from a main module component, it works fine and the tests pass.

**Expected behavior**
Tests should pass.

**Minimal reproduction of the problem with instructions**
Here is an example generated with Angular CLI 1.0.0.rc1:
https://github.com/ebrehault/ng-feature-module-example

Just run:
```
ng test
```

**What is the motivation / use case for changing the behavior?**
The motication is to be able to write tests :)

**Please tell us about your environment:**

Ubuntu 16.10, npm 3.8.6

* **Angular version:** 2.4.9

* **Browser:** Chrome (which is the browser used by karma)

 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   6.1.0

**Comment by DzmitryShylovich** [comment]
https://github.com/ebrehault/ng-feature-module-example/blob/master/src/app/bar/display/display.component.spec.ts#L11 there's no provider for `ConfigurationService` this is why it fails. Works as expected to me.

**Comment by ebrehault** [comment]
oops sorry, thanks
