### ISSUE TITLE
bug(language service): spurious "no directive found" error 

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14938]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Getting all manner of strange errors in the AIO doc viewer but a red squiggly over the `template` value like this one seems the most common.
```
No Directive annotation found on DocViewerComponent
```
Here's the code:
```
@Component({
  selector: 'aio-doc-viewer',
  template: '', <--- SQUIGGLY HERE
  styles: [ `
    :host >>> doc-title.not-found h1 {
      color: white;
      background-color: red;
    }
  `]
export class DocViewerComponent implements DoCheck, OnDestroy { ... }
```
**Expected behavior**

**Minimal reproduction of the problem with instructions**

 See `/aio` folder in `angular/angular` master. Examine any of the components with templates (e.g., `DocViewerComponent`). They are all failing.

**Please tell us about your environment:**
OS/X, vsix is v.0.0.12, VS Code 1.10.1, Angular@next (see `package.json`).

**Comment by kyliau** [comment]
We've made significant changes to the language service, and this bug is no longer reproducible. Please open a new issue if further discussion is needed.
