### ISSUE TITLE
Angular2 - Compile to AOT using absolute path in component templateUrl not working

### ISSUE THREAD

**Issue by dipendrakangane** [angular/angular#14947]
am using Angular2 and pre-compiling code using AOT.

I am able to compile code when I am using relative path in Component's templateUrl.

But compilation is failing when using absolute path in component's templateUrl

Compilation command: `"node_modules/.bin/ngc" -p tsconfig-aot.json`

I am getting below error while using absolute templateUrl:

> Error: Compilation failed. Resource file not found: {Absolute htmlUrl path} at ModuleResolutionHostAdapter.readResource (C:\Dipendra\stash-workspace\angular2Aot\WebContent\node_modules\@angular\compiler-cli\src\compiler_host.js:291:19) at CompilerHost.loadResource (C:\Dipendra\stash-workspace\angular2Aot\WebContent\node_modules\@angular\compiler-cli\src\compiler_host.js:230:85) at Object.get (C:\Dipendra\stash-workspace\angular2Aot\WebContent\node_modules\@angular\compiler\bundles\compiler.umd.js:26374:111) at DirectiveNormalizer._fetch (C:\Dipendra\stash-workspace\angular2Aot\WebContent\node_modules\@angular\compiler\bundles\compiler.umd.js:13753:47) at DirectiveNormalizer.normalizeTemplateAsync (C:\Dipendra\stash-workspace\angular2Aot\WebContent\node_modules\@angular\compiler\bundles\compiler.umd.js:13799:25) at DirectiveNormalizer.normalizeTemplate (C:\Dipendra\stash-workspace\angular2Aot\WebContent\node_modules\@angular\compiler\bundles\compiler.umd.js:13771:48) at CompileMetadataResolver._loadDirectiveMetadata (C:\Dipendra\stash-workspace\angular2Aot\WebContent\node_modules\@angular\compiler\bundles\compiler.umd.js:18074:79) at C:\Dipendra\stash-workspace\angular2Aot\WebContent\node_modules\@angular\compiler\bundles\compiler.umd.js:18250:58 at Array.forEach (native) at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (C:\Dipendra\stash-workspace\angular2Aot\WebContent\node_modules\@angular\compiler\bundles\compiler.umd.js:18249:45) Compilation failed

**Comment by DzmitryShylovich** [comment]
please add the github repo that reproduces the issue. thanks

**Comment by dipendrakangane** [comment]
Please find below repository:
https://github.com/dipendrakangane/angular2Aot

We are getting compilation error in two cases as below:
1. Use of external library in system.config.js
Ex. I have used external library for "file-saver" as below:
     "file-saver" : "https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2014-11-29/FileSaver.min.js"
And when I use it in app.module.ts, it throws error while compilation
import * as FileSaver from 'file-saver';

2. Use of absolute url as component's templateUrl
Ex. When I use absolute templateUrl for app/test1/test1.component.ts, it throws error mentioned in previous post

**Comment by jskrzypek** [comment]
@dipendrakangane I was curious and tried your repo, but I don't see the errors with the absolute html paths that you mentioned. Possibly those are a windows only bug (I have mac os x).

On the other hand, I was able to reproduce the external library errors for `file-saver`, and they should go away if you install the type definitions with `npm install @types/file-saver --save-dev`.

**Comment by JoostK** [comment]
I can no longer reproduce using latest Angular, neither using the ViewEngine compiler and the new Ivy compiler.
