### ISSUE TITLE
aio: move cookbook source files to guide folder

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14941]
and remove the `.../app/content/cookbook` folder because we're collapsing cookbooks into guides.

Until we do, cookbook docs will be "not found"

**Comment by petebacondarwin** [comment]
I guess that this is not going to happen on angular.io - so is part of the migrator's job?

**Comment by petebacondarwin** [comment]
I have updated the migrator: https://github.com/petebacondarwin/aio-migrator/commit/9988f17f79ae55799c616a2e96bf6175d8102959
