### ISSUE TITLE
Where to keep Angular 2 Integration test files?

### ISSUE THREAD

**Issue by subbu-nama** [angular/angular#14942]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular 2 CLI project, Unit test case files are available at component level.

**Expected behavior**
Can we have a common understanding to keep Integration test files path?

**What is the motivation / use case for changing the behavior?**
I have created Angular 2 project through Angular CLI and updated component ( app.component.ts ) and corresponding component test file ( app.component.spec.ts ). Here, updated component ( app.component.ts ) to gets the data from 'Angular 2 Service' ( which communicates with REST API ). I would like to write an Integration test cases about the component ( app.component.ts ) and want to create the separate file from normal unit test cases file ( app.component.spec.ts ). Can we have the best practices to keep the integration test files ( folder path and file naming convention ) and any suggested way to run them like 'npm test'.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
