### ISSUE TITLE
How to stop the Observable.timer which is used through observable operators like debounceTime and switchMap for asynchronous validations

### ISSUE THREAD

**Issue by maruthi-menlo** [angular/angular#14945]
I need to stop the Observable.timer when I navigate from that page to another page.
Below is the code which I'm using in my project.
import { Component, ChangeDetectorRef, OnDestroy } from '@angular/core';
import { NavController, MenuController } from 'ionic-angular';
import {Observable, Subject}from 'RxJs/Rx';

export class SettingsPage extends BasePage implements OnDestroy {
ionViewDidLoad() {
		let initial: boolean = true;
			
	this.serverUrlStream
			.debounce((val)=> Observable.timer(initial ? 0 : 500))	
			.switchMap(val => {		
					this.canLeave = false;	
					this.apiClientService.ocServiceUrl = val;
					return Observable.fromPromise(this.apiClientService.getHospitals());
			})
			.catch((err, caught)=>{
				console.log(err);
				return caught;	// Continue after error
			})
			.subscribe((hospitals: Hospital[]) => {
				this.hospitals = hospitals;
				if (hospitals.length > 0) {
					this.settings.hospitalInstallId = hospitals[0].InstallId;
					this.canLeave = true;					
					this.cd.detectChanges();
				}
			});
		
		
		this.serverUrlStream.next(this.settings.serverUrl);
		initial = false;
	}

//I tried like below to stop the timer when I left from this  page.

ngOnDestroy(){
		this.serverUrlStream.unsubscribe();
	}

}

Above code is not working still ajax call is running every 5 seconds. Can anyone please help me to stop the Observable.timer when user leave the current page

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
