### ISSUE TITLE
Tests fail when we extend a component from a feature module

### ISSUE THREAD

**Issue by ebrehault** [angular/angular#14944]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
(note: this is the bug I wrongly reported in my first report https://github.com/angular/angular/issues/14934 , but now I have successed in reproducing it properly)
My main module (foo in the example) contains a feature module (bar in the example), this feature module contains a service (ConfigurationService in the example) and a component (DisplayComponent in the example) which uses ConfigurationService. The component is exported by the bar module.
In the foo module, we inherit from this component to create the CustomDisplay component.
The application works fine, but the tests fail with the following error:
```
Cannot read property 'getStuff' of undefined
```
It happens because the ConfigurationService is not injected in the component.

**Expected behavior**

Tests should pass.

**Minimal reproduction of the problem with instructions**

Here is an example generated with Angular CLI 1.0.0.rc1:
https://github.com/ebrehault/ng-feature-module-example

Just run:
```
ng test
```

**What is the motivation / use case for changing the behavior?**

The motication is to be able to write tests :)

**Please tell us about your environment:**

Ubuntu 16.10, npm 3.8.6

* **Angular version:** 2.4.9

* **Browser:** Chrome (which is the browser used by karma)

 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   6.1.0

**Comment by DzmitryShylovich** [comment]
@chuckjaz can you take a look please? looks like something wrong with inheritance

**Comment by chuckjaz** [comment]
@ebrehault We have a work-around to a TypeScript bug (fixed in 2.1) that is being defeated.  Our work-around doesn't detect this case when using `es6` target.

 You have a couple of work-arounds:

1) Add an explicit constructor to CustomDisplayComponent that just calls `super(config)`.
2) Change the target to `es5`.
3) Upgrade to `4.0` and TypeScript `2.1`  or better

**Comment by ebrehault** [comment]
Ok, fair enough. Thank you :)

**Comment by ebrehault** [comment]
Hi,

I have upgraded to Angular 4.0.0 and Typescript 2.2.1 and I still get my test failing.
Example here: https://github.com/ebrehault/ng-feature-module-example

**Comment by Toxicable** [comment]
@ebrehault I just tried reproducing your issue with the cli on Angular v4.0.0 and CLI v 1.0.0
here is the test
This did not throw any errors
```
import { TestBed, async } from '@angular/core/testing';

import { AppComponent, ConfigurationService, BarModule, OtherComponent } from './app.module';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent,
        OtherComponent
      ],
      imports: [BarModule]
    }).compileComponents();
  }));

  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));

});
```

here is my classes 
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, OnInit, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { Injectable } from '@angular/core';

@Injectable()
export class ConfigurationService {
  getStuff() {
    return 'stuff';
  }
}

@Component({
  selector: 'app-display',
  template: '',
})
export class DisplayComponent implements OnInit {

  message: string;
  constructor(private config: ConfigurationService) { }

  ngOnInit() {
    this.message = this.config.getStuff();
  }
}

@Component({
  selector: 'app-other',
  template: ''
})
export class OtherComponent extends DisplayComponent {

}

@Component({
  selector: 'app-root',
  template: '<app-other></app-other>'
})
export class AppComponent {

}


@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [DisplayComponent],
  providers: [ConfigurationService],
  exports: [DisplayComponent]
})
export class BarModule { }

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**Comment by ebrehault** [comment]
If you add `fixture.detectChanges();` in the test, yo ushould get the error.

**Comment by Toxicable** [comment]
I changed the test to be the below and din't get any exceptions
```
  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    fixture.detectChanges();
    expect(app).toBeTruthy();
  }));
```

**Comment by ebrehault** [comment]
@Toxicable your code does work indeed. And comparing your code and mine really was driving me crazy.
And then I found the reason:

- in my `src/tsconfig.spec.ts`, I have `"target": "es6"` (which used to be the default with Angular CLI 1.0.0-rc.1),
- in a default Angular CLI 1.0.0, we have now `"target": "es5"` (that's a recent change https://github.com/angular/angular-cli/commit/e0aeccbfab6632475cd1c66673c87ece91da799a)

And that's what make the test fail or success :)

Thank you very much for your help!

**Comment by sasxa** [comment]
@ebrehault Thanks for this. I was starting to go crazy too (:
