### ISSUE TITLE
[v4] Property binding order

### ISSUE THREAD

**Issue by ghetolay** [angular/angular#14959]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When we bind multiple properties on an element, the order in which binding are defined is not necessary preserved to set the properties.

**Expected behavior**
Order should be preserved because there is case where it matters. My use case is setting `min`, `max` and `value` of an input range. `value` must be set last otherwise it gets reset when we set `min` or `max`.

**Minimal reproduction of the problem with instructions**
This is were it gets complicated, I've created a plunker that copy my component : 
https://plnkr.co/edit/mhRq17kdKiamfCuk7r3X?p=preview

But on that plunker, order is preserved ! :/
In my app its not and I don't know why.

For example that input : 
```
<input
    	type="range"
    	[disabled]="disabled"
    	[min]="min"
    	[max]="max"

    	[value]="contrast"
    	(change)="contrastChange($event)"/>
```

generate that ngFactory : 
```
 jit_elementDef2(0,null,null,0,'input',[[
        'type',
        'range'
      ]
    ],[
      [
        3,
        'disabled',
        0
      ]
      ,
      [
        3,
        'max',
        0
      ]
      ,
      [
        3,
        'value',
        0
      ]
      ,
      [
        3,
        'min',
        0
      ]

    ]
      ,[[
        null,
        'change'
      ]
    ],function(view,eventName,$event) {
      var allowDefault = true;
      var comp = view.component;
      if (('change' === eventName)) {
        var pd_0 = (comp.contrastChange($event) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },null,null)
```

`value` comes before `min`.

Both the plunker and my app are running **4.0.0-rc.2**

**Comment by tbosch** [comment]
Did this work in v2.x?

**Comment by tbosch** [comment]
Sorry, but we need a way of reproducing this... AFAIK, this didn't change compared to v2...

**Comment by ghetolay** [comment]
I'm really sorry here.
I just found out the problem: I have an html minifier in my build chain (for whitespace/newline) and it was also sorting my attributes.

Thks for your time and sorry again, I feel dumb....
