### ISSUE TITLE
angular route do not match

### ISSUE THREAD

**Issue by scofieldpeng** [angular/angular#14951]
**I'm submitting a issue about issue about the hash change redirect**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Hello,  I have a url which is "example.com/example" and I want to redirect to "exmplate.com/#!/hello" when user browse this page. To do this, I use the `location.href="/#!/hello"` in "exmplate.com/hello" html page.

unfortunately, It's not work, but if i input the `exmplate.com/#!/hello",the angular can match the route...

**Current behavior**

notice me do not match any routes.

**Expected behavior**

match the route route

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Nothing change but update the angular from 1.5.8 to 1.6.2

**Please tell us about your environment:**

* **Angular version:** 2.0.X

1.6.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
All browser

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

es6

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
please add a plunkr

**Comment by Toxicable** [comment]
@scofieldpeng can you please add a plunkr to reproduce the issue you're experiencing, if not then this is not actionable

**Comment by DzmitryShylovich** [comment]
> Nothing change but update the angular from 1.5.8 to 1.6.2

@pkozlowski-opensource it's angular 1. can be closed :)
