### ISSUE TITLE
Container component with <ng-content *ngIf="false"> brakes binding of hosted template declared in parent component (model binding with template reference variable), when model from reference variable is null.

### ISSUE THREAD

**Issue by kmolerov** [angular/angular#14957]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have container component and wish to host inside its<ng-content> a form (declared inside the parent component of my container), that is binded to a model that is managed by the container component. 
Initially model is undefined/null and ng-content is not shown in view. Template declared in parent component still tries to process the binding and this result in exception  Cannot read property property of null, as model is empty.
parent component: 
Main View template:
      <my-container #container>
        <input type="text" [(ngModel)]="container.model.property"/>
      </my-container>

Template of container component - my-container :
   <ng-content *ngIf="false"></ng-content>

**Expected behavior**
Binding in hosted template should not be triggered as <ng-content *ngIf="false">  is not rendered.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/nMJSHv2CUWzIxVSGTpDC?p=preview
result in "Cannot read property 'property1' of null". 

**What is the motivation / use case for changing the behavior?**

I can't set the template that must be hosted inside <ng-content> to have same scope as the container component. 
Is there some other way to change the scope of hosted template?

**Please tell us about your environment:**

Win 8.1
* **Angular version:** 2.4.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> "Cannot read property 'property1' of null".

`model2 = null` => `model2 =  { property1: 'test2'};` 
http://plnkr.co/edit/OwvY5D0NRfy65pM7Nsee?p=preview

**Comment by kmolerov** [comment]
model2 is intentionally null/undefined. Problem is that <ng-content *ngIf="false"> should force the bind to not be processed.  Use case is that after some business logic model2 will be initialized/retrieved and then <ng-content *ngIf="true"> -> the binding should then work.

**Comment by kmolerov** [comment]
workaround for the problem (not convenient):
parent component:
<my-container #container>
 <div *ngIf="container.model">
    <input type="text" [(ngModel)]="container.model.property"/>
 </div>
</my-container>

**Comment by kmolerov** [comment]
workaround for the problem (not convenient):
parent component:
<my-container #container>
  <div *ngIf="container.model">
    <input type="text" [(ngModel)]="container.model.property">

**Comment by kmolerov** [comment]
workaround for the problem (not convenient):
parent component:
<my-container #container><div *ngIf="container.model"><input [(ngModel)]="container.model.property">

**Comment by artaommahe** [comment]
@kmolerov 'by design' everything inside `<ng-content>` initialized despite `*ngIf` state/usage #13921
