### ISSUE TITLE
A bug about method createComponent of ViewContainerRef

### ISSUE THREAD

**Issue by suplch** [angular/angular#14953]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => createComponent of ViewContainerRef behavior is different with document description.
```

**Current behavior**

I call method createComponent of ViewContainerRef, I want to insert a child component into a parent element, but current behavior is insert it after parent element, it is brother element of parent element
```html
    <div #parent></div>
```

```typescript
    @ViewChild('parent', {read: ViewContainerRef})
    parent: ViewContainerRef;

    ngOnInit() {
        let compFactory = this.componentFactoryResolver.resolveComponentFactory(TestComp);
        this.parent.createComponent(compFactory);
    }
......
......
    @Component({
        selector: 'test-comp',
        template: `
            hello this is test comp
        `
    })
    export class TestComp {}

```

```html
     // current behavior
    <div></div>
    <test-comp>hello this is test comp</test-comp>
```
**Expected behavior**
I read document of ViewContainerRef, its mean is insert childComponent into parent element, but now its behavior is not that.
```html
    // expected behavior
    <div><test-comp>hello this is test comp</test-comp></div>
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
OS:  macOS 10.12.1
IDE: WebStorm
package manager: Npm,
Http server: nodejs express web framework
* **Angular version:** 2.4.8

* **Browser:** [all | Chrome XX ]

 
* **Language:** [all | TypeScript 2 | ES5]

* **Node (for AoT issues):** `node --version` =   7.0.0

**Comment by DzmitryShylovich** [comment]
> I want to insert a child component into a parent element, but current behavior is insert it after parent element

this is by design

**Comment by pkozlowski-opensource** [comment]
@DzmitryShylovich is right, this is by design.
