### ISSUE TITLE
aio: doc viewer scss and accompanying UX tweaks

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14963]
Stefanie Fluin to lead and implement

**Comment by petebacondarwin** [comment]
To include:

* [ ] ensure search box placeholder is aligned correctly
* [ ] style the toolbar when the window is narrow
* [ ] provide styling for formatted code
*

**Comment by sjtrimble** [comment]
@petebacondarwin

Search Box - done!
Responsive Toolbar Styling - will get on this, on my to-do list
Formatted Code Styling - do you mean the style code, or the designs (designs - done!)

**Comment by sjtrimble** [comment]
@petebacondarwin I believe all of these are done. Let me know otherwise.
