### ISSUE TITLE
aio: Integrate preboot

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14966]
To enable users to start typing while the app is loading. Preboot captures those interactions and replays them once the app loads.

Delay this feature until after v4 release

**Comment by IgorMinar** [comment]
since we currently don't prerender the site we don't need this.

**Comment by wardbell** [comment]
This issue is on our _future_ plan for when we DO pre-render the site. Last I checked, we were still planning to pre-render in a near-future iteration of this doc viewer app. Therefore, reopening ... until you say we have no plans to pre-render any time soon.
