### ISSUE TITLE
docs: API - link to the source code of EventEmitter is a 404

### ISSUE THREAD

**Issue by ocombe** [angular/angular#14960]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
The link to the source code of EventEmitter on angular.io is a 404 because of the symlink for facade in the core module: https://angular.io/docs/ts/latest/api/core/index/EventEmitter-class.html
It points to https://github.com/angular/angular/tree/2.4.8/modules/@angular/core/src/facade/async.ts#L12-L116

**Expected behavior**
It should point to https://github.com/angular/angular/blob/2.4.8/modules/@angular/facade/src/async.ts#L14-L116

**Minimal reproduction of the problem with instructions**
Go to https://angular.io/docs/ts/latest/api/core/index/EventEmitter-class.html and click on the link at the end of the page: `exported from @angular/core/index, defined in @angular/core/src/facade/async.ts`

**What is the motivation / use case for changing the behavior?**
I don't like 404 errors, my motivation is to exterminate them all

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/pull/14837

**Comment by wardbell** [comment]
Closing because API docs no longer link to source code at all!

At least I couldn't find those links. See issue #17718
