### ISSUE TITLE
aio: Accessibility audit

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14964]

**Comment by marcysutton** [comment]
This issue was opened a long time ago. Is it ever going to be done?

**Comment by IgorMinar** [comment]
Hi @marcysutton, we did do a pass when we were launching the app a while back and never closed this issue.

We've since regressed and web.dev/lighthouse reports some issues we should fix.

If you have any other suggestions or accessibility bug reports, can you please open a new issue? Thank you!

**Comment by IgorMinar** [comment]
I filed #27723 with a more concrete bug report.
