### ISSUE TITLE
Question: Property binding with strict equality

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#1496]
Hi 

I was wondering why this code works:

```html
      <label [class.great-framework]="name.value == 'Angular'">
        Framework:
        <input type="text" #name (keyup)/>
      </label>
```

But using strict equality in the expression doesn't:

```html
      <label [class.great-framework]="name.value === 'Angular'">
        Framework:
        <input type="text" #name (keyup)/>
      </label>
```

Is strict equality not yet supported by the expression parser? Whats the plan here?

The above expression fails with: Error: Parser Error: Unexpected token null at column 14 in [name.value === 'Angular'] in null

**Comment by pkozlowski-opensource** [comment]
Yeh, seems like `===` isn't well parsed / recognized. This has nothing to do with binding to classes, here is a minimal reproduce scenario: http://plnkr.co/edit/cPEKMOufrVhyGbfeHLnX?p=preview

**Comment by vicb** [comment]
I guess this has to do with legacy when expressions had the same semantics in JS/Dart.

Now that expressions match the langugage semantics, it would make sense to support === (=== in JS, identical() in Dart)

**Comment by pkozlowski-opensource** [comment]
@vicb yep, same conclusion here. I will take this one to have an excuse to dive into parser's code :-)

**Comment by gionkunz** [comment]
@pkozlowski-opensource happy coding! :-)
