### ISSUE TITLE
Question: General information on "property binding"

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#1497]
Hello there

First of all what's your preferred terminology for what I call a property binding?

```html
<div [title]="title"></div>
```

Then I was wondering if you could give me some clues where in the code I could look behind the "magic" of this binding resolution.

For example I completely understand that these bindings works without any magic:

```html
<div [title]="title" [style.text-transform]="'uppercase'"></div>
```

As it's a regular chained property accessor it would do something like this under the hood:
```javascript
element.title = title;
element.style['text-transform'] = 'uppercase';
```

Which is possible using a very generic approach of accessing and setting properties on the DOM Element.

However, what I don't understand, and where the magic for me starts, is how this is done for, let's say, the classList of a DOM Element.

I can do the following (which is great!):
```html
<div [class.is-active]="item == selectedItem"></div>
```

As the DOM API is not providing a property on elements with the name class, neither does the classList (which is a Array like list) supports to set named keys to truthy / falsy, I wonder where you transform this to apply to the classList?

I was browsing the code for a while but I couldn't find the spot that is concerned about this.

Cheers
Gion

**Comment by vicb** [comment]
see https://github.com/angular/angular/blob/0ff99081bd35a2332dc3a89c298b1552b870332b/modules/angular2/src/render/dom/view/property_setter_factory.js#L11

**Comment by gionkunz** [comment]
Great, thanks! :-)
