### ISSUE TITLE
Dynamically Load Module

### ISSUE THREAD

**Issue by seanbotha123** [angular/angular#14977]
**I'm submitting a ...**  (check one with "x")
```
[ X ] feature request
```

Hi Guys

So I asked a question about 2 weeks ago regarding loading components dynamically, which was closed - #14640. I have raised this as a feature request as I am unsure of whether the functionality that I require is possible. 

What I need is as follows; I need to load my NgModule from a dynamic URL. The reason for this requirement is that I am not always aware where the module is, and it needs to be configured by a user. I also would not know about the Module at build time, that is why I need to load it from a dynamic URL.

The closest example I can find to what I need is in this plunker (https://plnkr.co/edit/khdS8xFkvqe7ZIsz0kc7?p=preview), but it seems that this can only load relative modules? 

If somebody could please give me any advice here I would really appreciate it.

**Comment by DzmitryShylovich** [comment]
You need to implement your own `NgModuleFactoryLoader` based on xhr/http so you will be able to load modules from dynamic urls. 
A similar service to load templates: https://github.com/angular/angular/blob/f2adb2900d93677517215a8ab6ccc10d95a5df48/modules/%40angular/platform-browser-dynamic/src/resource_loader/resource_loader_impl.ts#L13

**Comment by seanbotha123** [comment]
Can you please elaborate here? Do you maybe have an example on this?

**Comment by DzmitryShylovich** [comment]
In your [example](https://plnkr.co/edit/khdS8xFkvqe7ZIsz0kc7?p=preview) you need to provide your own implementation of `NgModuleFactoryLoader ` instead of `SystemJsNgModuleLoader`. Everything else is the same

**Comment by seanbotha123** [comment]
Okay, that makes sense. Is it possible to load a module at runtime instead of needing to specify it at compile time? 

I have been trying to use 'require', and when I specify the module at compile time everything runs perfectly, but when I try to pass it a variable to load it dynamically it does not work.

**Comment by seanbotha123** [comment]
Hi @DzmitryShylovich, any feedback here?

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

----

Here are some tips on where to look for similar solutions to the problem you described: you can take a look at how cli's custom webpack NgModuleFactoryLoader works. There is also this 3rd party gist:
https://gist.github.com/brandonroberts/02cc07face25886fe142c4dbd8da1340
