### ISSUE TITLE
Router events not exposing properies

### ISSUE THREAD

**Issue by paistipoikka** [angular/angular#14976]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In Angular 2.4.7 the following code is typescript compatible:

```
someFunction(private router: Router) {
        this.routerSubscription = router.events.subscribe(data => {
            console.log(data.url);
        });
}
```

In Angular 4.0.0-rc.2 (for the same code) the only property that typescript recognises is the `toString() `method. 

```
someFunction(private router: Router) {
        this.routerSubscription = router.events.subscribe(data => {
            console.log(data.url);   // error
            console.log(data.toString());
        });
}
```
> Error:(51, 28) TS2339:Property 'url' does not exist on type 'Event'.
  Property 'url' does not exist on type 'RouteConfigLoadStart'.

**Expected behavior**
`RouteConfigLoadStart` exposes the `id` and `url` properties.

**Minimal reproduction of the problem with instructions**
see code above

**What is the motivation / use case for changing the behavior?**
Breaks existing code written with 2.4.7.

**Please tell us about your environment:**
OS X
Intelli-J/Webstorm

* **Angular version:** 2.0.X
Angular 4.0.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

n/a
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

typescript: 2.1.5

```
{
  "compilerOptions": {
    "outDir": "build/compiled",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "node",
      "core-js",
      "googlemaps"
    ]
  },
  "exclude": [
    "node_modules",
    "typings"
  ]
}
```

* **Node (for AoT issues):** `node --version` =   

n/a

**Comment by DzmitryShylovich** [comment]
RouteConfigLoadStart doesn't have id and url properties

**Comment by paistipoikka** [comment]
@DzmitryShylovich 

So it appears the API has changed and it now returns a completely different type.

Previously data was of type `NavigationStart`. Now it's of type `RouteConfigLoadStart`. Nothing in the change logs that explains this (AFAIKT).

How do we get the URL now?

**Comment by DzmitryShylovich** [comment]
> So it appears the API has changed and it now returns a completely different type.

https://github.com/angular/angular/blob/master/modules/%40angular/router/src/events.ts#L144
You need to read about union types in typescript

> How do we get the URL now?

For example:
```
this.routerSubscription = router.events
      .filter((e: Event) => e instanceof NavigationStart)
      .subscribe((e: NavigationStart) => {
            console.log(data.url);
            console.log(data.toString());
        });
```

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
