### ISSUE TITLE
ERROR: Invalid date for pipe on IOS device (updated)

### ISSUE THREAD

**Issue by bop10** [angular/angular#14984]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
http://plnkr.co/edit/tk29FgVU8C1woBFAeyED?p=preview

```
@Component({
  selector: 'my-app',
  template: `
    <div>
      <p>
      <strong>Date 1: </strong>
      {{date | date: 'dd/MM/yyyy'}}
      </p>
    </div>
     <div>
      <p>
      <strong>Date 2: </strong>
      {{date2 | date: 'dd/MM/yyyy H:mm:ss'}}
      </p>
    </div>
  `,
})
export class App {
  date: Date;
  date2: string;
  
  constructor() {
    this.date = new Date("2017-03-06 12:32:26");
    this.date2 = "2017-03-06 12:32:26"
  }
}
```

On my PC (Ubuntu, windows) i don't have problems, and i see all the dates in the format i want:
```
Date 1: 06/03/2017

Date 2: 06/03/2017 12:32:26
```
But I'm getting this errors on my IOS device (even the plnkr doesnt load the dates like i posted below, on Chrome, Safari):
[SCREENSHOOT](https://cloud.githubusercontent.com/assets/16181441/23663734/c59c2a34-0353-11e7-8f31-4a6bef81cd0b.jpg)

"EXCEPTION: Invalid argument 'Invalid Date' for pipe 't'" 

"EXCEPTION: Invalid argument '2017-03-06 12:32:26' for pipe 't'"  

I tried to install intl (npm install --save intl) and then added this to my polyfillls.ts file (using angular-cli) but still does not work:
```
import 'intl';
import 'intl/locale-data/jsonp/en';
```

**What is the motivation / use case for changing the behavior?**
Getting my app to work on my IOS device

**Please tell us about your environment:**

* **Angular version:** 2.4.9
* **Angular cli version:** 1.0.0-rc.0

* **Browser:** tested on Chrome and Safari

**Comment by leo6104** [comment]
http://stackoverflow.com/questions/4310953/invalid-date-in-safari 
`selected_model.created_at  -> selected_model.created_at.replace(/-/g, "/") `
it works. 
Safari not support YYYY-MM-DD Format Parsing.

**Comment by bop10** [comment]
Hi @leo6104 thanks for the answer , but im having the same error on Chrome, not only on Safari only on the IOS device.

**Comment by leo6104** [comment]
As mentioned in [submission guideline](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue), please add plnkr reproduction code to find out root cause quickly.

**Comment by bop10** [comment]
@leo6104 here is the plnkr reproduction:
http://plnkr.co/edit/tk29FgVU8C1woBFAeyED

When i load it on my IOS device, it doesnt load the dates

**Comment by Doehl** [comment]
It works for me when I use the following pollyfill.
https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en

**Comment by bop10** [comment]
Hey @Doehl i installed intl (npm install --save intl)
 
Then i added this lines to my src/polyfills.ts (since im using angular-cli):
```
import 'intl';
import 'intl/locale-data/jsonp/en';
```

Still doesn't works on my IOS device, im getting the same error.
Thanks

**Comment by bop10** [comment]
I updated the issue to clarify the problem @leo6104 @Doehl , thanks

**Comment by leo6104** [comment]
Did you try this? 
The pattern yyyy-MM-dd isn't an officially supported format for Date constructor. 

```
    this.date = new Date("2017-03-06 12:32:26".replace(/-/g, "/"));
    this.date2 = "2017-03-06 12:32:26".replace(/-/g, "/")
```

It changes '2017-03-06 12:32:26' to '2017/03/06 12:32:26' official supported format for Date constructor.

**Comment by bop10** [comment]
@leo6104 Ok, i tried your solution and it works!, thanks a lot.
Do you know if the angular team plans to add yyyy-MM-dd as an officially supported format?
Closing the issue

**Comment by artuska** [comment]
I just solved this issue — told backend to send all the dates in timestamp format not date strings. So now I don't need all those polyfills (they are ~70 KB and not working) and I don't get any errors. Works for me :)
