### ISSUE TITLE
Module constructor invoked twice

### ISSUE THREAD

**Issue by Liork1** [angular/angular#14986]
Hi,

I'm trying to load a module in my application router in 2 ways:
1)   {  path: 'lazy',  loadChildren:'src/lazy/lazy.module#LazyModule' }
2) { path: 'lazy', loadChildren: ()=> LazyModule }

In both ways the constructor of LazyModule is being invoked twice.
Is there any way to avoid it?

Regards,
Lior

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/12869
