### ISSUE TITLE
Better error message for "Runtime compiler not loaded"

### ISSUE THREAD

**Issue by dhilgarth** [angular/angular#14981]
I encountered the error "Runtime compiler not loaded" in my app after building it for production.  
I wasn't aware of anything I did in my app that would require a runtime compiler. The error message I got failed to highlight the component / class that caused the error.

I only found out by clicking through my app and noticing the part that no longer worked. In the end it was a third party library.

http://stackoverflow.com/questions/42645623/trouble-shoot-runtime-compiler-is-not-loaded

**Comment by maplion** [comment]
I agree; this would be very helpful as I just spent quite a bit of time fighting this error without having much idea as to the cause.  Thankfully, dhilgarth's StackOverflow gave me the clue since I was using the same library (angular2-busy), which was causing the issue.

**Comment by JoostK** [comment]
This is being addressed for Ivy in #42693. Sorry it took 4 years!
