### ISSUE TITLE
Bootstrap does not remove unused Light DOM of entry component

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1499]
Let's say we're bootstrapping an app

```html
<my-app>
  loading...
</my-app>
```
```js
bootstrap(MyApp);
```

The text `loading` appears until the component is bootstrapped and ready to expose it's Shadow DOM. Since a component's Shadow DOM instead of Light DOM get's displayed, `loading...` disappears.

However as soon as we put actual DOM nodes into the Light DOM like this:
```html
<my-app>
  <p>loading...</p>
</my-app>
```
The Light DOM is not replace with the Shadow DOM of the component, but simply stays there.

This seems like a bug to me.

**Comment by rkirov** [comment]
+1 I noticed that bug too.

**Comment by jeffwhelpley** [comment]
I noticed this as well. Looks like the generated HTML has an extra <content> tag with the original content of the component.

**Comment by naomiblack** [comment]
This is a bug, but not blocking.

**Comment by SekibOmazic** [comment]
It seems to be fixed in alpha 20. But only if there is exactly one child DOM element. Following doesn't work:
```html
<my-app>
  <p>loading...</p>
  <p>and loading...</p>  <!--  doesn't get removed -->
</my-app>
```

**Comment by vicb** [comment]
Can not reproduce on master

**Comment by vicb** [comment]
Actually it doesn't work when there is a `<content>` tag in the template

**Comment by mhevery** [comment]
@tbosch is this still an issue with the latest code base (`<ng-content>`?)

**Comment by tbosch** [comment]
No.
@vicb If there is a `<content>` tag in the template (not an `<ng-content>` tag), we are keeping the original content as light dom so that the `<content>` shows it.
