### ISSUE TITLE
Able to define aux route that targets to router-outlet defined in ancestor routes (similar feature as named view in ui-router)

### ISSUE THREAD

**Issue by feng-xiao** [angular/angular#14996]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Got following error:

> Uncaught (in promise): Error: Cannot find the outlet layout-module-detail-bar to load 'CustomerLayoutModuleDetailBarComponent'

**Expected behavior**

No error. Following is the code using AngularJS ui-router 

```ts
        static routeState: angular.ui.IState = {
            url: '/{oppNo:int}',
            views: {
               '': // module content definition
                {
                    templateUrl: "modules/ci/customer/lead/edit/index.tpl.html",
                    controller: IndexController,
                    controllerAs: "edit",
                    
                },
                 // layout section template config
                 'module-titlebar-rightpane@': {
                    templateUrl: './edit.module-titlebar-rightpane.tpl.html',
                    controllerAs: 'actionBar',
                    controller: EditController
                }
            }
        };
```
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Easier to define UI layout, like ASP.NET MVC nested layout (RenderSection, etc.), or named views in ui-router.

So the root route define the layout (top navbar, left nav bar, title bar, etc.), then child route can define the content that goes into right spot (e.g. left navbar)

**Please tell us about your environment:**

Windows 10 Pro

* **Angular version:** 2.0.X

Angular 4 RC2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome latest
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2.1

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Please add the plunkr that reproduces what you are trying to accomplish. thanks

**Comment by feng-xiao** [comment]
Basically, I would like Angular Router can support 'views' feature found in UI-Router (https://ui-router.github.io/guide/views)

**Comment by dietergeerts** [comment]
+1.
Right now, if you have a parent component, you can't use the named outlet from your root component, so if I use a modalPane router outlet, I have to add this outlet everywhere, while I only want it to be in my root component, as it will only be used once at a time.

**Comment by papaiatis** [comment]
+1.
I would use this to have a context sensitive aside navigation. 
So for example when the user is on the home page, the aside navigation would hold links to 'A', 'B' and 'C' pages. When he goes to page 'A' I would like to both update the aside navigation to hold links to 'D' and 'E' pages and, of course, update the main content.

**Comment by kirakishin** [comment]
anyone has a tip to use an alternative to do that ?

**Comment by dietergeerts** [comment]
@papaiatis , you can achieve that in another way too. We added data to our routes, and the navigation component keeps track of the current route, and then read all data on that route to have the menu populated.
