### ISSUE TITLE
Angular Router: navigate([...], relativeTo) failing when used from service

### ISSUE THREAD

**Issue by utnas** [angular/angular#14991]
**I'm submitting a ...** (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When trying to do: `router.navigate(['route'], { relativeTo: this.activatedRoute})` from inside a service, the router cannot find the parent route and tries to match `route` against the root path and throws an error.

**Expected behavior**

Router should be able to resolve the proper route regardless of where the `navigate` instruction is sent from

**Minimal reproduction of the problem with instructions**

See _**[this plunker](https://plnkr.co/edit/tpJs21Zd0lksr3vSaEkD)**_
More specifically the file `app/first-section.component.ts` (see the comments in there) and `app/NavService.ts`

- - -
**What is the motivation / use case for changing the behavior?**

The concern is to be able to have a better separation of concerns between business logic (services) and presentation logic (component), and making everything easier to test

Angular's documentation makes no mention of whether or not Navigation should be done only from components.

**Please tell us about your environment:**

Not Relevant
Mac Os Sierra
IntelliJ Idea 2017.1 
Angular-cli Server's
Yarn
...

* **Angular version:** 2.0.X

Angular-Cli 1.0.0-rc.1
@angular/* 2.4.9 (also tested and failing with 4.0.0-rc2)
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Tested with:
* Chrome 56.0.2924.87 (64-bit)
* Firefox 51.0.1 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1
* **Node (for AoT issues):**`node --version` =

Not relevant: 6.9.2

**Comment by DzmitryShylovich** [comment]
> tries to match route against the root path

this is by design. Angular will inject root `ActivatedRoute` inside a service

**Comment by OClement** [comment]
> this is by design. Angular will inject root ActivatedRoute inside a service

I see what you mean, however I'm not sure I understand how this can be "by design"
What's the rationale behind this?
I find it extremely counter intuitive that a service behaves differently like so
Shouldn't `ActivatedRoute` means exactly that, regardless of where it is used?

PS: I'm the person who created the issue, but from my colleague's computer

**Comment by DzmitryShylovich** [comment]
`ActivatedRoute` is bound to a component. Each component gets a different instance of `ActivatedRoute`. This is why angular can only inject root `ActivatedRoute` into a service.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed

**Comment by DzmitryShylovich** [comment]
@vicb works as intended as for me

**Comment by GitHubish** [comment]
I understand the concept. So, how would you redirect to a route relative to the active route without using the ActivatedRoute service? Thanks

**Comment by choopage** [comment]
Is this coming along the way?

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
