### ISSUE TITLE
Cannot read property 'createRenderer' of undefined

### ISSUE THREAD

**Issue by Quantas** [angular/angular#15008]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Before Angular 4.0.0-beta.8 the application, using Renderer, would compile just fine with AOT and there would be no issues in production. After beta.8 I get the error stated in the title, "Cannot read property 'createRenderer' of undefined". I scoured the issues/docs to find upgrade notes for 7 to 8 regarding Renderer and could not find any note specifically that would prevent this from working after the upgrade.

**Expected behavior**
App would continue to work after upgrading to beta.8 or beyond.

**Minimal reproduction of the problem with instructions**
This is a proprietary production application, I can attempt to create minimal steps but I'm not sure when I will be able to get to that.

**Please tell us about your environment:**
Linux
Webpack 2.2
Node 6.9.5
Apache 2

* **Angular version:** 4.0.0-beta.8 through 4.0.0-rc.2 with AOT

* **Browser:** all
 
* **Language:** Typescript 2.2

* **Node (for AoT issues):** `node --version` =  6.9.5 & `@ngtools/webpack` = 1.2.12

**Comment by DzmitryShylovich** [comment]
please reproduce in plunkr http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview

**Comment by Quantas** [comment]
Ok, I made a Plunkr, but I get a slightly different error:

```
TypeError: Cannot read property 'apply' of undefined
    at RendererAdapter.invokeElementMethod (https://unpkg.com/@angular/core@next/bundles/core.umd.js:8655:42)
    at App.ngOnInit (http://run.plnkr.co/BY4lKP9T7ehcLPDd/src/app.ts!transpiled:31:35)
```

http://plnkr.co/edit/1jvIcLE53eQCD23xHLbu?p=preview 

I know the CHANGELOG.md said that you shouldn't use Renderer any more and you should favor RendererV2, but RendererV2 is "missing" `invokeElementMethod` and there doesn't seem to be any docs on how to migrate to V2, any help would be greatly appreciated. Our use case is we are trying to call focus on a specific element for ADA purposes.

**Comment by DzmitryShylovich** [comment]
`Renderer` is deprecated and will be removed in the next release.
`invokeElementMethod` was removed because it wasn't used by angular. See https://github.com/angular/angular/issues/13818
And there's no replacement for it.

**Comment by Quantas** [comment]
As I saw in #13818 there was no resolution for calling focus on an element, are there any suggestions or best practices?

**Comment by DzmitryShylovich** [comment]
create your own Renderer and implement it for different platforms:
```
abstract class MyRenderer {
    invokeElementMethod(el, method, args): any;
}

class MyDomRenderer implements MyRenderer {
   invokeElementMethod(el, method, args): any {
       // impl...
   }
}
```

**Comment by Quantas** [comment]
I replaced references to Renderer in my app with a custom Renderer now. My AOT production build still throws an error about createRenderer and my application has no references to the Renderer or the RendererFactory any more.

Browser console:
```
TypeError: Cannot read property 'createRenderer' of undefined
    at createRootData (http://localhost:8080/main.2ae9c3565cdd3cdd5921.js?2ae9c3565cdd3cdd5921:21349:51)
```

Here is the relevant source from the browser:
```
/**
 * @param {?} injector
 * @param {?} rendererFactory
 * @param {?} projectableNodes
 * @param {?} rootSelectorOrNode
 * @return {?}
 */
function createRootData(injector, rendererFactory, projectableNodes, rootSelectorOrNode) {
    var /** @type {?} */sanitizer = injector.get(Sanitizer);
    var /** @type {?} */renderer = rendererFactory.createRenderer(null, null);
    return {
        injector: injector,
        projectableNodes: projectableNodes,
        selectorOrNode: rootSelectorOrNode, sanitizer: sanitizer, rendererFactory: rendererFactory, renderer: renderer
    };
}
```

**Comment by laco0416** [comment]
you can call `nativeElement.focus()` directly

**Comment by Quantas** [comment]
@laco0416 I tried that initially and it was giving me mixed results so I decided to make my own Renderer impl as @DzmitryShylovich suggested. That said, I still get errors as I eluded to in my last comment.

**Comment by Quantas** [comment]
Well, I'm not sure why, but my webpack build wasn't separating out vendor code into it's own chunk, once I switched to doing that everything worked as expected.

**Comment by SnareChops** [comment]
@IgorMinar and @DzmitryShylovich 

I have encountered this same error and have a reproduction to submit

I'm submitting a ...
```
[x] bug report
[ ] feature request
[ ] support request
```
## Current behavior
Application errors during bootstrap as shown below with a barebones angular application

## Expected behavior
Application should bootstrap and display

## Minimal reproduction of the problem with instructions
https://github.com/SnareChops/OverwatchAlgebra
```
npm install
npm run build:site
serve / open index.html in browser of your choosing using server of your choosing
```

## Please tell us about your environment:
Mac OSX (10.12.3)
Rollup IIFE
Node 7.5.0

Angular version: 4.0.1

Browser: chrome (haven't tested others)

Language: Typescript 2.2.1

Node (for AoT issues): node --version = 7.5.0

## Error received
<img width="1205" alt="screen shot 2017-03-30 at 4 04 20 pm" src="https://cloud.githubusercontent.com/assets/3210560/24523871/92c9a25a-1562-11e7-8090-48b57cec76c8.png">

Application is barebones. Entire application code is:

```
@Component({
	selector: 'owa',
	template: `
		<p>Overwatch Algebra</p>
	`
})
export class MainComponent{}

@NgModule({
	declarations: [
		MainComponent
	],
	imports: [
		CommonModule,
		BrowserModule
	],
	schemas: [
		CUSTOM_ELEMENTS_SCHEMA
	],
	bootstrap: [
		MainComponent
	]
})
export class MainModule{}

platformBrowser().bootstrapModuleFactory(MainModuleNgFactory);
```
(of course in separate files and with relevant imports)

**Comment by DzmitryShylovich** [comment]
@SnareChops please open a new issue. thanks

**Comment by Quantas** [comment]
I will say, it was a false positive when I said it was fixed. It was still broken for me :(

**Comment by jponeill** [comment]
Not sure it's related, but for me switching from ISO-8859-1 to UTF-8 fixed the problem. Lines like the following in the "main" bundle were causing problems (e.g, "_\u0275...")

    Object.defineProperty(AppModuleInjector.prototype, "_\u0275AnimationEngine_93", {
        get: function () {
            if ((this.__ɵAnimationEngine_93 == null)) {
                (this.__ɵAnimationEngine_93 = new __WEBPACK_IMPORTED_MODULE_34__angular_platform_browser_animations__["c" /* ɵa */](this._AnimationDriver_91, this._ɵAnimationStyleNormalizer_92));

**Comment by Quantas** [comment]
@jponeill where did you make the change from ISO-8559-1 to UTF-8 ? Webpack config? tsconfig?

**Comment by jponeill** [comment]
For me it was a server change, but an easy way to test if the character set encoding is the problem is to use a chrome extension that lets you change the character set to UTF-8 (if it's not that already).

**Comment by ptrzyna** [comment]
@jponeill Where did you set the encoding?

**Comment by Quantas** [comment]
I believe @SnareChops has discovered the bottom of this rabbit hole in #15638 !

**Comment by DanielSchaffer** [comment]
I was able to fix this by just adding a `<meta charset="utf-8">` tag. I don't even need the replace fix with the tag in place.

**Comment by msaiyaff** [comment]
Will this be a reason to disappoint upgrading the app to v4? :D
Btw, anyways(guidance: doc or articles) to pull this off [To write our own renderer as well](https://github.com/angular/angular/issues/15008#issuecomment-285141070)?

**Comment by hallysonh** [comment]
This custom service can help someone:

```typescript
import { Injectable, PLATFORM_ID, Inject, ElementRef } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

@Injectable()
export class Renderer {

  constructor(
    @Inject(PLATFORM_ID) private platformId: Object
  ) { }

  invokeElementMethod(eleRef: ElementRef, method: string) {
    if (isPlatformBrowser(this.platformId)) {
      eleRef.nativeElement[method]();
    }
  }
}
```
