### ISSUE TITLE
Select element option not selected on form reset

### ISSUE THREAD

**Issue by joelwaymack** [angular/angular#15006]
**I'm submitting a ...** 
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After a form is reset and given a new ngModel when using the template-driven form method, select elements are not guaranteed to choose the correct option.

**Expected behavior**

After a form reset, if a new ngModel is set, a select should choose and display the correct option.

**Minimal reproduction of the problem with instructions**

The following plunker resets the form and sets a new backing model for the form when the reset button is clicked. If you change the select box to a different option before hitting reset, the form is reset correctly and the correct option for the select is set. If the select is still set to the first option, the select is cleared and the correct option is not shown on a reset.

http://plnkr.co/edit/vSlserRLWwBIv6uNQBP7?p=preview

**What is the motivation / use case for changing the behavior?**

When the backing ngModel changes, a select should choose the correct option.

* **Angular version:** 2.4.X

* **Browser:** all

 
* **Language:** TypeScript 2.X

**Comment by kara** [comment]
If you want the form to reset to a certain value, it should be passed into the `reset` function:

```ts
form.reset({selectThing: this.vehicle.typeId})
```

See example here: http://plnkr.co/edit/eeXHrXxdNhnmvfVO139z?p=preview
