### ISSUE TITLE
AOT regression in 4.0.0-rc.2 for services with parameters

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#15003]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

AOT compilation in 4.0.0-rc.2 fails for code that used to work in 2.4.8.

**Expected behavior**

AOT compilation shouldn't fail in 4.0.0-later

**Minimal reproduction of the problem with instructions**

https://github.com/tragetaschen/angular-issue-n14513

- Check out and npm-install the second commit (angular 2.4.8)
- Run `node_modules/.bin/ngc -p src/tsconfig.app.json` - works fine
- Check out and npm-intall the HEAD (angular-4.0.0-rc.2)
- Run `node_modules/.bin/ngc -p src/tsconfig.app.json` -fails with
```
Can't resolve all parameters for AlarmService in C:/Users/kairu/Source/Repos/angular-issue-n14513/src/app/alarm.service.ts: (?).
```

**What is the motivation / use case for changing the behavior?**

It's my understanding that there are no breaking changes going to angular version 4.

**Please tell us about your environment:**

Windows, command line, npm

* **Angular version:** 2.0.X

4.0.0-rc.2

* **Browser:** [<s>all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView </s>]

 
* **Language:** [<s>all |</s> TypeScript 2.2 <s>| ES6/7 | ES5</s>]

* **Node (for AoT issues):** `node --version` =   
`v6.1.0`

**Comment by filoxo** [comment]
Angular is following [semver](http://semver.org/), and the jump from 2 to 4 is major. Major version changes denote that incompatible API changes were made. By upgrading from 2 to 4 you actually *should* expect breaking changes.

**Comment by laco0416** [comment]
@vicb I think this behavior is caused by inheritance of `Injectable()` decorators at AoT compilation. could you check this out?

**Comment by laco0416** [comment]
```
@Injectable()
export class AlarmService {

  constructor(public p1: boolean) { }

}

@Injectable()
export class InstrumentAlarmService extends AlarmService {
  constructor() {
    super(true);
  }
}
```

I think `AlarmService` must not have its own `Injectable` annotation. I don't know why can this work in 2.4...

**Comment by Tragetaschen** [comment]
My reason to have this in the first place is the documentation for dependency injection (https://angular.io/docs/ts/latest/cookbook/dependency-injection.html#!#-injectable-):
```
We add @Injectable() from the start for the sake of consistency and to avoid future pain.
```

So having the `@Injectable()` on `AlarmService` is explictly encouraged in Angular.

**Comment by DzmitryShylovich** [comment]
as for me it's a valid bug

**Comment by otodockal** [comment]
I see also regression here and I don't use inheritance.

This code was correct in Ng 2x AOT, but the same error as above in Ng 4x AOT

```typescript
// app.module.ts
providers: [
    {
        provide: AppStore,
        useFactory: appStateFactory,
    }
],
```

```typescript
// app.state.ts
const states = {
    [STORE_USER]: null,
}
export function appStateFactory() {
    return new AppStore(states)
}
```

```typescript
// app.store.ts
@Injectable()
export class AppStore {

    private _store = new Map<string, BehaviorSubjectStore<any>>();

    constructor(initialState) {
        for (let event in initialState) {
            this._store.set(event, new BehaviorSubjectStore<any>(initialState[event]))
        }
    }

    select(key) {
        return this._store.get(key)
    }

}
```

**Comment by DzmitryShylovich** [comment]
@otodockal remove `@Injectable()` from `AppStore`

**Comment by otodockal** [comment]
@DzmitryShylovich good catch!!! Thank you!

**Comment by DzmitryShylovich** [comment]
cc @chuckjaz

**Comment by tbosch** [comment]
I am going to change the compiler for v4 to only emit a warning, so we don't break users / users are able to create components that work in v2 and v4.

**Comment by DzmitryShylovich** [comment]
@tbosch why does compiler analyse injection token (`provider.provide`) at all?

**Comment by tbosch** [comment]
1) we need to find its declaration place, to be able to compare across
re-export s
2) for summaries, we need to read the metadata of all angular decorators
eagerly, so that dependents don't need to reevaluate them
