### ISSUE TITLE
ngForm.form.valid does not change when control invalidated

### ISSUE THREAD

**Issue by Bidthedog** [angular/angular#15007]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm following the forms tutorial [here](https://angular.io/docs/ts/latest/guide/forms.html). Scroll down to "Submit the form with ngSubmit". The ngForm.form.valid property does not change when a form's input is invalidated. The inputs invalidate correctly, but they aren't bubbled up to the form itself.

**Expected behavior**

As per the tutorial, the Save button should be disabled when any form control is invalidated and enabled when all controls are valid.

**Minimal reproduction of the problem with instructions**

Very cut down version of what I have:
http://plnkr.co/edit/7VCmkhgzdAaCqZMGDzqW

Click "Save" after loading and you will get a validation message. If you complete the field and click "Save", the form will submit as expected.

However, the "f" template reference is being used to disable the "Save" button when the form is invalid, but this is not working. I believe I have followed the tutorial correctly.

**What is the motivation / use case for changing the behavior?**

Behaviour matching the tutorial

**Please tell us about your environment:**

Win 10, VSCode, Angular CLI, npm / yarn

* **Angular version:** 2.0.X

$ ng --version
angular-cli: 1.0.0-beta.26
node: 6.9.4
os: win32 x64

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 56.0.2924.87, not tried in any other browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> Very cut down version of what I have:
https://plnkr.co/edit/L5WDFGQOackQHUTxQwKr?p=preview

did you save your changes?

**Comment by Bidthedog** [comment]
I just realised I didn't use the angular template, give me a few mins - sorting it now.

**Comment by Bidthedog** [comment]
Updated the plunkr, sorry about that @DzmitryShylovich

**Comment by DzmitryShylovich** [comment]
you need to add `ngModel` directive http://plnkr.co/edit/NkSoNxzlAOl7mKPYpOA0?p=preview

**Comment by Bidthedog** [comment]
Very interesting... I am using two way binding, but only via child components in my real code, e.g:

**Component template**
```
<form #f="ngForm">
  {{f.form.valid}}

    <button type="submit"
            class="btn btn-success"
            [disabled]="!f.form.valid">Save</button>
  </div>
        <text-box id="NHSNumber"
                  name="NHSNumber"
                  friendlyName="NHSNumber"
                  [(value)]="model.NHSNumber"
                  required="true"
                  pattern="^\d{3}-\d{3}-\d{4}$"></text-box>
</form>
```

**The text-box component looks like this:**

```
<div class="form-group has-feedback"
     [ngClass]="{'has-success': ctl.valid && ctl.touched, 'has-error': !ctl.valid && ctl.touched}">
      <label [for]="id"
             class="control-label">{{friendlyName}} <span *ngIf="required">(required)</span></label>
      <input type="text"
             class="form-control input-lg"
             [id]="id"
             [name]="id"
             [placeholder]="friendlyName"
             attr.aria-describedby="ctl{{id}}Status"
             [required]="required"
             [attr.maxlength]="maxLength"
             [attr.minlength]="minLength"
             [pattern]="pattern"
             #ctl="ngModel"
             [(ngModel)]="value"
             (ngModelChange)="valueChange.emit($event)">
      <span class="glyphicon form-control-feedback"
            [ngClass]="{'glyphicon-ok': ctl.valid && ctl.touched, 'glyphicon-remove': !ctl.valid && ctl.touched}"
            aria-hidden="true"></span>
      <span id="ctl{{id}}Status"
            class="sr-only">({{ctl.valid && ctl.touched ? 'success' : 'error'}})</span>
</div>

```

Am I doing something wrong?

**Comment by DzmitryShylovich** [comment]
does `text-box` implement ControlvalueAccessor`?

**Comment by Bidthedog** [comment]
Nope:

```
import { Component, Input, Output, OnInit, EventEmitter } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'text-box',
  templateUrl: './text-box.component.html',
  styleUrls: ['./text-box.component.scss']
})
export class TextBoxComponent implements OnInit {
  @Input() id: string;
  @Input() value: string;
  @Input() friendlyName: string;
  @Input() required: boolean = false;
  @Input() minLength: number;
  @Input() maxLength: number;
  @Input() pattern: string;

  @Output() valueChange: EventEmitter<string> = new EventEmitter<string>();

  constructor(
  ) { }

  ngOnInit() {
    if (!this.id) throw new Error("'id' property is required by 'text-box' component");
    if (!this.friendlyName) throw new Error(`'friendlyName' property is required by 'text-box' component '${this.id}'`);
  }
}
```

**Comment by DzmitryShylovich** [comment]
See https://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html

**Comment by Bidthedog** [comment]
Thanks, I will take a look. Finding it quite difficult to learn ng2, and I've been around a while!

**Comment by kara** [comment]
It looks like you just need to implement ControlValueAccessor, as @DzmitryShylovich suggested. Closing this, as it doesn't look like a bug.

**Comment by Bidthedog** [comment]
Thank you, this finally sorted the problem once I figured it out! You might want to update the official documentation to include such an example - I spent quite a lot of time trying to get two way data binding working with my custom controls.
