### ISSUE TITLE
Animation callback timeline in IE and Edge

### ISSUE THREAD

**Issue by MrMartinRoy** [angular/angular#15016]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When adding callback for 'start' and 'done', the 'done' callback occur first in IE or Edge browser. In Chrome, we get the 'start' callback first and than the 'done' callback

**Expected behavior**
Expecting the 'start' callback to occur first

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/ZkdTdCaaxrDlKLkAFDnA?p=preview
Using IE11 or Edge, the console display "Done callback" followed by "Start callback". Other browser display "Start callback" first

**What is the motivation / use case for changing the behavior?**
We want to change the display behavior of some element during an animation and revert once done.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.X

* **Browser:** [ IE 11 | Edge ]

**Comment by ericmartinezr** [comment]
If you add the webanimations polyfill for IE (as stated in the [docs](https://angular.io/docs/ts/latest/guide/browser-support.html)) it works fine, see [this plnkr](http://plnkr.co/edit/84eMROM3nPn1I8Bqa8ns?p=preview) with IE. Now, I don't see the fading but I'm not sure what's happening there. Hopefully the plnkr will give you a starting point.

**Comment by MrMartinRoy** [comment]
That was it. Got it working. Thank you
