### ISSUE TITLE
Element.load issue in safari

### ISSUE THREAD

**Issue by kotmatpockuh** [angular/angular#1501]
In my app i use image crop tool for image cropping. But i have one trouble with safari: after 1-2-3-n crop it stop to work. Event load is not fired. But in other browsers all is ok.

When i use broadcast-technic: all is ok. But then architecture is bad and ugly...

my code:

in controller: event is fired when image is selected:

    funcName = function(argument) {
      reader.onload = function(e) {
        angular.element('#image-crop-modal').modal('show');
        scope.imagecontent = e.target.result;
      }
    }

and in directive (which i attach to crop image) i have:

    element.bind('load', function(){...})

and this sometimes didn't work in safari, but is ok in other browsers.

if i do it so:

    funcName = function(argument) {
      reader.onload = function(e) {
        scope.$broadcast('cropOnload');
        angular.element('#image-crop-modal').modal('show');
        scope.imagecontent = e.target.result;
      }
    }

and directive:

    scope.$on('cropOnload', function() {...}

than it works. But what's wrong? Why only in safari load event is not fired always?

**Comment by vicb** [comment]
This repo is for angular2, please re-open on https://github.com/angular/angular.js
