### ISSUE TITLE
Pipe Transform multiple values as array not working

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular#15010]
I have a pipe transform for which i am passing and argument as an array
like

import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'square'
})
export class SquarePipe implements PipeTransform {

  transform(value: number, args?: number[]): number {
    if(value != null){
        return Math.pow(value,2) + args[0];
    }
    else {
      return 0;
    }
  }

}

Passing from template like

<p>Squared Number plus 2 is {{val | square:[2,2]}} </p>

This gives and error like cannot read property 0 of undefined where as this works with Angular2

**Comment by DzmitryShylovich** [comment]
please add a plunkr

**Comment by pkozlowski-opensource** [comment]
hanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by rahulrsingh09** [comment]
@pkozlowski-opensource I wasn't able to add Plunker for Angular 4 Rc 2 That is the reason i coudnt provide inputs but i did post the code and the problem where i was facing is that not sufficient , Please help as that will be great

**Comment by lenoln** [comment]
Hi, I tried something similar, however, I could not. can anybody help me?
I created Pipe, I'm using it, but it does not recognize the 'blacklist' changes. 
Plunkr: [https://embed.plnkr.co/1sI1HQBLblK4TAq1eBRS/](url)
