### ISSUE TITLE
[Router] Redirect to Url outside the Angular app but on the same domain

### ISSUE THREAD

**Issue by KenavR** [angular/angular#15015]
**Potential Bug**
I am not sure if this is a bug, the expected behavior or if I am not seeing an option in the docs.

**Current behavior**
With an earlier version of the router, I used a guard to redirect the user to a separate `/signin.html` page, if the user wasn't signed in. For the redirect/url change I used `window.location.replace('/signin.html');`. That worked flawlessly, but today I updated to 3.4.9 of the router and now the router seems to catch the URL change and tells me

```
EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'signin.html'
Error: Cannot match any routes. URL Segment: 'signin.html'
    at ApplyRedirects.noMatchError (http://localhost:3000/vendor.bundle.js:115127:16)
    ...
```

*Relevant code*
//routes
```
export const routes: Routes = [
    {
        path: '',
        canActivate: [IsAuthenticatedGuard],
        children: [...]
    }
];
```
```
//guard
@Injectable()
export class IsAuthenticatedGuard implements CanActivate {

    constructor(private _router: Router) {}

    canActivate(
        route: ActivatedRouteSnapshot,
        state: RouterStateSnapshot
    ): Observable<boolean> {
        if (!this._isSignedIn()) {
            window.location.replace('/signin.html');
            return Observable.of(false);
        }
        return Observable.of(true);
    }

    _isSignedIn(): boolean {
        return document.cookie.indexOf('jwt') !== -1;
    }
}
```

**Expected behavior**
The behavior the router had before or an option to define an URL the router should ignore.

**Minimal reproduction of the problem with instructions**
Couldn't make a reasonable example using plunker, but here is small example - https://github.com/KenavR/router-redirect-issue

**What is the motivation / use case for changing the behavior?**
It was quite a while ago when I decided to create a separate html file for the sign in, but when I tried moving it into the normal route structure after the update, I found at least one drawback which requires me to "majorly" restructure my app. Since sign in is a child of root ('') I would need to place the guards on every route instead of just defining for every child on the root. Some of the routes (lazy loaded modules) currently do not have access to the guards.

These problems could be solved/worked around, but since the "redirect" worked in past versions I thought about asking here, before restructuring my app.

**Please tell us about your environment:**

Don't think that's relevant here, but

- Win 10
- VS Code
- Java backend using Zuul as Gateway server in front of the backend and Angular dev environment using the CLI

* **Angular version:** 2.4.9
* **Angular router version:** 3.4.9

thanks

**Comment by DzmitryShylovich** [comment]
try to call `Router.dispose()` before redirect

**Comment by KenavR** [comment]
Sadly that didn't change anything. The more I try and look through the documentation, the more I am surprised that it worked in the past.

**Comment by jasonaden** [comment]
This should work in the current version of the router. If this is still an issue, please file a new issue here.

**Comment by kesarawimal** [comment]
I am facing the same issue and I didn't find any solution yet.

**Comment by petermweeks** [comment]
similar issue here; I get a "cannet GET /url/" error when I try to hit my backend on the same domain
