### ISSUE TITLE
ngModel in select options not working

### ISSUE THREAD

**Issue by FructuosoRobles** [angular/angular#15035]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I try to find the solution and found some examples but is not working in my code, when I select an option, object does not change or updates, problem just in select, text fields are working.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

html
`<div class="input-field col s12">
                                    <select name="country" id="country" [(ngModel)]="user.country">
                                        <option [value]="" disabled selected>Pais</option>
                                        <option *ngFor="let country of countries" [value]="country.value">{{country.display}}</option>
                                    </select>
                                </div>`

model

`export class User {
    email: string;
    password: string;
    country: string;
    descriptionText: string;
    userDetailInfo = new UserDetailInformation();
}`

component

`user = new User();

  countries = [
    { value: 'eeuu', display: 'EEUU' },
    { value: 'mexico', display: 'Mexico' },
    { value: 'canada', display: 'Canada' }
  ];`

**What is the motivation / use case for changing the behavior?**

Can not make the form works

**Please tell us about your environment:**

Visual studio code 1.10.2
Mac osSierra 10.12.3

* **Angular version:** 2.0.X

angular 2: 1.0.0-beta.24

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}
* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
