### ISSUE TITLE
Collabarating angular2 with fullpagejs, need to load fullpage js after binding template from anular

### ISSUE THREAD

**Issue by rakeshbhupathi** [angular/angular#15037]
So i am trying to use fullpage js features in angular2. There are few sections rendered through template binding, which is happening  after loading fullpagejs. 

My issue is there are 4 main sections in my page and 1 of them hav 3 child sections which are generated through json data(template binding). For example "servicesSection" is one of the child section generated through template binding, so when I enter "http://localhost:3000/#servicesAnchor3" in url, its not auto scrolling to that particular section since fullpage js doesnt know that slide, because it is being binded after fullpage js loaded. 

I appreciate if anyone could help me out solving this issue, i am scratching my head from weeks, fed up finding solution.

Is there a way that we could reload fullpage js after loading all the slides, that would fix my issue.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
