### ISSUE TITLE
Changing LOCALE_ID in runtime does no change formatting of pipes

### ISSUE THREAD

**Issue by ajantsch** [angular/angular#15039]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I change the LOCALE_ID during runtime of my app, the formatting of DatePipe outputs stays the same, e.g. change from en-EN to de-DE, date output still formats as 3/3/2017 instead of 3.3.2017.

**Expected behavior**
As soon as the LOCALE_ID gets changed, pipes based on this information should update their output.

**Minimal reproduction of the problem with instructions**
In my main module I do
```
{
    provide: LOCALE_ID,
    useValue: "en-EN",
},
```
When I now inject the LOCALE_ID in any component
```
constructor(
        @Inject(LOCALE_ID) private _locale: string,
 ) {}
```
and change the locale in this component
```
this._locale = "de-DE";
```
the  output of e.g. the DatePipe should be formatted according to the locale.

**What is the motivation / use case for changing the behavior?**
Language/Formatting change during app runtime

* **Angular version:** 
2.4.9

* **Browser:** 
all
 
* **Language:**
Typescript 2.2.1

**Comment by DzmitryShylovich** [comment]
How do you change it at runtime? Please add a plunkr

**Comment by ajantsch** [comment]
Will create a plunkr soon, for the meantime: As shown above, I inject LOCALE_ID in my component and assign a new value to the property (in my example _locale). I'm not sure if this is actually the right way to do this and if this is reflected in the LOCALE_ID, so feel free to show me the right way if I'm doing anything wrong.

**Comment by DzmitryShylovich** [comment]
> if this is reflected in the LOCALE_ID

it won't be reflected. You can't dynamically change locale with the default pipe. You should create your own.

**Comment by ChrisProlls** [comment]
I cannot agree with this behavior. If my user navigate into my application after he changes his locale, I want all dates and numbers to be correctly formatted with the new locale.
@ajantsch have you found a solution ?

**Comment by ajantsch** [comment]
@ChrisProlls No, haven't found a solution yet. It would of course be possible if I implement my own version of the pipe and pass the current locale as parameter from the template, but I want to avoid this. Second possibility would be to make the custom pipe impure, but that also doesn't seem like a nice solution to me.

**Comment by ChrisProlls** [comment]
My solution was to reload the entire app (refresh the page) if I detect that the user has changed his locale. Weird but it's working and acceptable for our needs.

**Comment by ivanpadavan** [comment]
Make LOCALE_ID non-primitive may help

**Comment by crh225** [comment]
@ChrisProlls  this is what we are ending up doing also. have you found a different way to do this?

**Comment by ChrisProlls** [comment]
@crh225 not for the moment sadly ...

**Comment by brunano21** [comment]
@ChrisProlls can you tell me how you do reload the app with a different locale, please?

**Comment by quangtvdevnet** [comment]
Hi Guys,

Have this issue been fixed? I am facing exactly problem in Angular 6.

Best,

**Comment by ivanpadavan** [comment]
I've acomplished this task using Minko Gechev's [aspect.js](https://github.com/mgechev/aspect.js) library. Languages handeled by [ngx-translate](https://github.com/ngx-translate).

So I'vs got a file with code: 
```typescript
import {CurrencyPipe, DatePipe, DecimalPipe, PercentPipe} from '@angular/common';
import {beforeMethod, Metadata, onThrowOfMethod} from 'aspect.js';
import {TranslateService} from '@ngx-translate/core';

export class PipesPatchingAspect {
  static translate: TranslateService;

  @beforeMethod({
    classes: [
      DatePipe,
      CurrencyPipe,
      DecimalPipe,
      PercentPipe,
    ],
    methodNamePattern: /^transform$/
  })
  beforeTransform(meta: Metadata) {
    meta.method.context.locale = PipesPatchingAspect.translate.currentLang;
    meta.method.context._locale = PipesPatchingAspect.translate.currentLang;
  }
}
```
In module where ngx-translate is configured:  
```ts
@NgModule({...})
export class TranslationsModule {
  constructor(translate: TranslateService) {
    PipesPatchingAspect.translate = translate;
  }
}
```
And the last part: reload page when language changes: 
```ts
translate.onLangChange.subscribe(() => {
      const reuse = router.routeReuseStrategy.shouldReuseRoute;
      router.routeReuseStrategy.shouldReuseRoute = () => false;
      router.navigated = false;
      router.navigateByUrl(router.url).then(() => {
        router.routeReuseStrategy.shouldReuseRoute = reuse;
      });
    });
```
So to use this method seamlessly,  state management should be decoupled from components. Good luck!

**Comment by quangtvdevnet** [comment]
Hi,

Thanks a lot,

But I am waiting for a solution that doesn't require to reload page.

Anyone please tell me is it possible to do that?

Best,

**Comment by ivanpadavan** [comment]
You can pass locale as said [here](https://angular.io/api/common/DatePipe);

**Comment by ivanpadavan** [comment]
You can pass locale as said [here](https://angular.io/api/common/DatePipe)

**Comment by yildiraymeric** [comment]
Hi,

You can use following provider declaration in AppModule to supply LOCAL_ID according to your system preferences (I'm using ngx-translate)

```typescript
@NgModule({
  declarations: [
    ...
  ],
  imports: [
    ...
    TranslateModule.forRoot(),
    ...
  ],
  providers: [
    ...  
    {
      provide: LOCALE_ID,
      useFactory: (translate: TranslateService) => {
        return translate.currentLang;
      },
      deps: [TranslateService]
    }
    ...
  ],
  bootstrap: [AppComponent]
})
export class AppModule { 
}
```
BUT, this still requires to reload the page  :(

**Comment by trotyl** [comment]
@jusefb Angular is still a normal JavaScript library, it's up to you when to mount or unmount an app. Reload is simply a shortcut for unmount and mount again.

**Comment by jscssphtml** [comment]
I'm also using ngx-translate. Very untested, but maybe this will help anyone or give new ideas of solving this problem:

```
export class DynamicLocaleId extends String {
  constructor(protected service: TranslateService) {
    super('');
  }

  toString() {
    return this.service.currentLang;
  }
}

...

providers: [
  ...
  { provide: LOCALE_ID, useClass: DynamicLocaleId, deps: [TranslateService] }
],
```

**Comment by amoscatelli** [comment]
> I'm also using ngx-translate. Very untested, but maybe this will help anyone or give new ideas of solving this problem:
> export class DynamicLocaleId extends String {
>   constructor(protected service: TranslateService) {
>     super('');
>   }
> 
>   toString() {
>     return this.service.currentLang;
>   }
> }
> 
> ...
> 
> providers: [
>   ...
>   { provide: LOCALE_ID, useClass: DynamicLocaleId, deps: [TranslateService] }
> ],

That's brilliant, that's the real solution.
I wouldn't even call this a workaround.

**Comment by cfoulkes** [comment]
> > I'm also using ngx-translate. Very untested, but maybe this will help anyone or give new ideas of solving this problem:
> > export class DynamicLocaleId extends String {
> > constructor(protected service: TranslateService) {
> > super('');
> > }
> > toString() {
> > return this.service.currentLang;
> > }
> > }
> > ...
> > providers: [
> > ...
> > { provide: LOCALE_ID, useClass: DynamicLocaleId, deps: [TranslateService] }
> > ],
> 
> That's brilliant, that's the real solution.
> I wouldn't even call this a workaround.

Hi @amoscatelli 
I've followed the above but I'm not sure about the final step.
How do you declare the date pipe in the html to get this working?  {{ dateVal  | date ?????   }}

Thanks
Colin

**Comment by amoscatelli** [comment]
> I'm also using ngx-translate. Very untested, but maybe this will help anyone or give new ideas of solving this problem:
> export class DynamicLocaleId extends String {
> constructor(protected service: TranslateService) {
> super('');
> }
> toString() {
> return this.service.currentLang;
> }
> }
> ...
> providers: [
> ...
> { provide: LOCALE_ID, useClass: DynamicLocaleId, deps: [TranslateService] }
> ],
> 
> That's brilliant, that's the real solution.
> I wouldn't even call this a workaround.
> 
> Hi @amoscatelli
> I've followed the above but I'm not sure about the final step.
> How do you declare the date pipe in the html to get this working?  {{ dateVal  | date ?????   }}
> Thanks
> Colin

This is my code:

`export class DynamicLocaleId extends String {
    constructor(protected service: TranslateService) {
        super();
    }

    toString() {
        return this.service.currentLang;
    }
}

export const LocaleProvider: StaticClassProvider = {
    provide: LOCALE_ID,
    useClass: DynamicLocaleId,
    deps: [TranslateService]
};`

And I use date pipe normally without problems (I am not sure I understood your problem) :

{{ dateVal | date }}

**Comment by cfoulkes** [comment]
Thanks @amoscatelli.


I was confused by the locale being allowed as a parameter in the pipe itself.

I see this works fine when initially painting the screen, but if the language changes while the screen is displayed, the pipe doesn't redisplay the date in the (now) current language.

Colin

**Comment by yildiraymeric** [comment]
> Thanks @amoscatelli.
> 
> I was confused by the locale being allowed as a parameter in the pipe itself.
> 
> I see this works fine when initially painting the screen, but if the language changes while the screen is displayed, the pipe doesn't redisplay the date in the (now) current language.
> 
> Colin

Angular's date, number, currency & percent pipes are implemented as "pure" pipes. As a result of this they did not re-render their content when Locale is changed. Only solution that I've found to this problem is to patch the angular pipes as follows;

``` typescript
import {Inject, LOCALE_ID, OnDestroy, Pipe} from '@angular/core';
import {DatePipe} from '@angular/common';
import {TranslateService} from '@ngx-translate/core';
import {LangChangeEvent} from '@ngx-translate/core/lib/translate.service';
import * as _ from 'lodash';

@Pipe({
  name: 'i18nDate',
  pure: false
})
export class I18nDatePipe extends DatePipe implements OnDestroy {
  private changeSubs: any;
  private cache;
  private previousParams = [];

  constructor(@Inject(LOCALE_ID) locale: string,
              translate: TranslateService) {
    super(locale);
    this.changeSubs = translate.onLangChange.subscribe(($event: LangChangeEvent) => {
      (<any>this).locale = $event.lang;
      this.cache = null;
    });
  }

  transform(value: any, format?: string, timezone?: string, locale?: string): string | null {
    const currentParams = [value, format, timezone, locale];
    if (!this.cache || !_.isEmpty(_.difference(this.previousParams, currentParams))) {
      this.previousParams = currentParams;
      console.log('datepipe transform');
      this.cache = super.transform(value, format, timezone, locale);
    }
    return this.cache;
  }

  ngOnDestroy(): void {
    this.changeSubs.unsubscribe();
  }

}
```

This is kind of a hack by the way because `this.locale` is a private member of DatePipe. Thus this class may break with the future Angular updates. But it is working for me now.

I've created similar classes for number, percent & currency pipes, too.  Hope this helps..
