### ISSUE TITLE
Can't use auxiliary routes from lazy modules

### ISSUE THREAD

**Issue by templth** [angular/angular#15033]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I try to use auxiliary routes from a lazy module:

* I have a router-outlet element with name `modal` in the root module
* I try to display a component in it using a `routerLink`: `<a [routerLink]="[{ outlets: { 'sidebar': ['component-aux'] } }]">Component Aux</a>`

I have the following error:

```
Error: Uncaught (in promise): Error: Cannot match any routes: 'sub/component-sub'
    at resolvePromise (VM2052 zone.js@0.6.25:429)
    at eval (VM2052 zone.js@0.6.25:406)
    at ZoneDelegate.invoke (VM2052 zone.js@0.6.25:203)
    at Object.onInvoke (VM2080 core.umd.js:6242)
    at ZoneDelegate.invoke (VM2052 zone.js@0.6.25:202)
    at Zone.run (VM2052 zone.js@0.6.25:96)
    at eval (VM2052 zone.js@0.6.25:462)
    at ZoneDelegate.invokeTask (VM2052 zone.js@0.6.25:236)
    at Object.onInvokeTask (VM2080 core.umd.js:6233)
    at ZoneDelegate.invokeTask (VM2052 zone.js@0.6.25:235)
    at Zone.runTask (VM2052 zone.js@0.6.25:136)
    at drainMicroTaskQueue (VM2052 zone.js@0.6.25:368)
```

**Expected behavior**

I expect my component to be displayed into the router-outlet with name `modal`.

**Minimal reproduction of the problem with instructions**

See this plunkr: https://plnkr.co/edit/l8aHoLENOUFRhBf4zvGi?p=preview.

**What is the motivation / use case for changing the behavior?**

Use auxiliary routes with lazy modules.

**Please tell us about your environment:**

Angular CLI, Visual Studio Editor

* **Angular version:**

2.4.9 and 4.0.0-beta.8

* **Browser:**

Chrome
 
* **Language:**

TypeScript 2

* **Node (for AoT issues):** `node --version` =

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

If this is still an issue with current Angular & Router and it's not something answered on StackOverflow, please create a new issue.
