### ISSUE TITLE
Element interpolated class removes bound classes.

### ISSUE THREAD

**Issue by JanBoshoff** [angular/angular#15038]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If an element has an interpolated class as well as a class that is bound to a component property, bound class is removed if the interpolated class value changes.

Take the following html as example: 
`<h2 class="existing-class {{compClass}}" [class.bound]="hasClass">Hello {{name}}</h2>`

Once the `compClass` property changes, the `bound` class is removed. 

**Expected behavior**

The expected behavior is that the class that is bound by a variable is unaffected by an interpolated class.

Thus, in the above example, if `hasClass` is true the element should have the following classes present "existing-class", "bound" and whatever the value of `compClass` is.

When `compClass` changes and `hasClass` is still true, the element should still have the "bound" class. 

**Minimal reproduction of the problem with instructions**

1. Create a component with a boolean and string property.
2. Within the component template, add the string property as a interpolated string in an element's class attribute.
3. Bind another class to the element with the boolean property (`[class.bound]="boolProp"`)
4. Change the string property's value after a certain amount of time.
5. The the class that is added with attribute binding is removed.

Or check out this [plunker](http://plnkr.co/edit/McE9UyP3h07eMqS3EOag)

**What is the motivation / use case for changing the behavior?**

I think it makes sense to be able to change one class without effecting other classes on an element.

**Please tell us about your environment:**

* **Angular version:** 2.4.9 && 4.0.0-rc.2

* **Browser:** [Chromium 56 | Firefox 52]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.2 (with Angular 2.4.9)
Typescript 2.1.5 (with Angular 4.0.0-rc.2)

* **Node (for AoT issues):** `node --version` =

**Comment by willmendesneto** [comment]
@JanBoshoff Your example will works fine if you use `[ngClass]` with bindings instead `[class.bound]`. Here's a plunkr with the expected result:

http://plnkr.co/edit/YdCJkVIc5TOQ7vY0GNIS?p=preview

**Comment by JanBoshoff** [comment]
@willmendesneto Great, thanks. I missed that one. 

I guess it's still a bug, since it makes sense for it to work correctly in both ways? But [ngClass] seems cleaner anyway.

**Comment by JanBoshoff** [comment]
@willmendesneto Oh I just tested some more, and the `[ngClass]` solution does not actually work 100% correctly.

But using `[ngClass]` to bind the property and interpolation `{{compClass}}` works as expected. So it's just the `[class.className]` syntax that doesn't work as expected.

Example plunkr: [http://plnkr.co/edit/tngggh00Zlik9F8XI7cV](http://plnkr.co/edit/tngggh00Zlik9F8XI7cV)

**Comment by willmendesneto** [comment]
@JanBoshoff I got your point. I didn't get this step, but looks good.

This is a plunkr using the same idea using `ngClass`. For sure you can use other approaches but still works fine via `ngClass`. http://plnkr.co/edit/Ow4Vr2juTX4I5DDplgHM?p=preview

**Comment by pkozlowski-opensource** [comment]
In the original plunker we've got 2 bindings on the `<h2>` element:
* `[className]="'existing-class ' + compClass"` (this is what `class="existing-class {{compClass}}"` gets transformed to)
* `[class.bound]="hasClass"`

On the first change detection the expressions are evaluated to `existing-class` and `true` which translates to the following operations:
* set `className` to `existing-class`
* add `bound` to the element's `classList`

So far so good and the element ends up with the `existing-class bound` classes.

Then, after 5 seconds the change detection runs again and this time the values evaluate to `existing-class interpolated` and `true`. **Please notice that only one expression changed value here and only it will trigger DOM update**. But binding to `[className]` is "destructive" in the sense that it will wipe out and re-assign all the CSS classes.

Now, having _both_ interpolation and `[class.bound]` works (even if `hasClass` doesn't change) would mean that we would have to _systematically_ trigger DOM manipulations for  `[class.bound]`-like bindings. **This would be super-expensive and would bring performance to its knees**. 

I don't think that there is a good solution here (meaning one that is correct _and_ performant) and this is why I'm going to close this issue. As other suggested please use `ngClass` (or interpolation only).

**Comment by staeke** [comment]
@pkozlowski-opensource I stumbled upon this issue now. I think you have a fair argument. However, if it's not supported I think the compiler should throw an error, e.g. "You cannot mix interpolated class values with class bindings"
