### ISSUE TITLE
Provide an guidance and/or api for dispatching events in tests

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#15051]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request
```

**Current behavior**
Currently there is no good way to dispatch events in component unit tests. Some people use private `dispatchEvent` api, but that's not an api that we want to maintain as as a public api.

No good alternative exists today, so we should come up with one because it is fairly common that in order to unit tests a component, some tests need to fire synthetic events.

**Comment by trotyl** [comment]
Relates to #3782

**Comment by trotyl** [comment]
Should be closed by https://github.com/angular/angular/pull/22726

**Comment by IgorMinar** [comment]
Thanks @trotyl
