### ISSUE TITLE
x-xsrf-token: token is added even for other origins. 

### ISSUE THREAD

**Issue by bhoomabrsr** [angular/angular#15052]
There is no check for urlIsSameOrigin or not, before appending to request headers in the CookieXSRFStrategy

Please check out this plunker: https://plnkr.co/edit/vhiBHiVpt598FS15orFX?p=preview

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

x-xsrf-token: token is added even for other origins
**Expected behavior**

it should not added if URL origin is different.

**Minimal reproduction of the problem with instructions**

Please check out this plunker: https://plnkr.co/edit/vhiBHiVpt598FS15orFX?p=preview

* **Angular version:** Angular v2.4.9

**Comment by DzmitryShylovich** [comment]
Please fill out the issue template. thanks

**Comment by bhoomabrsr** [comment]
Updated with template.

**Comment by dherges** [comment]
For clarification: same origin should be determined by cookie's domain value (i.e. `run.plnkr.co` in your example). Right?

**Comment by zenlambda** [comment]
Is there a work around for this?

**Comment by alxhub** [comment]
This is fixed in `HttpClient`.
