### ISSUE TITLE
Button in form binding a click event trigger form submit and page refresh when clicked.

### ISSUE THREAD

**Issue by qvodthy** [angular/angular#15058]
**I'm submitting a support request.**

**Current behavior**

On chrome.
When bind a click event to a button in a form, and click the button, it will trigger the click event and then submit the form(just like execute form.submit()), which will change the url and refresh the application.
It works well on Firefox.

**Minimal reproduction of the problem with instructions**

```
<form (submit)="onSubmit()">
  <button (click)="onClick()">A</button> //error, onSubmit() doesn't run.
  <button (click)="onClick()" type="button">A</button> //works well, onSubmit() doesn't run.
  <button>A</button> //works well, onSubmit() runs.
</form>
```

**Please tell us about your environment:**

* **Angular version:** 2.1.2

* **Browser:** [Chrome 55]

 
* **Language:** [TypeScript 2.0.3]

* **Node (for AoT issues):** `node --version` =   v6.2.2

**Comment by Toxicable** [comment]
can you reproduce this in a plunkr please

**Comment by DzmitryShylovich** [comment]
@qvodthy https://github.com/angular/angular/issues/14080

**Comment by spock123** [comment]
I think you need to set the type of buttons:

```
<button type="submit"> ....   

or 

<button type="button"> ... 
```

**Comment by qvodthy** [comment]
@Toxicable Weird...  I try to reproduce it on plunkr, but it works well. Perhaps it's something wrong with my runtime environment or my old angular2 version. My situation is just like #9936. 
I will continue to try to reproduce this.

**Comment by DzmitryShylovich** [comment]
@qvodthy did you fix your issue?

**Comment by BioPhoton** [comment]
FYI, I also tried to reprodce this without luck. using angular 4 latest...

**Comment by laxmikanta415** [comment]
Reseting the form in simple javascript is the solution for now.

    var form : HTMLFormElement = 
    <HTMLFormElement>document.getElementById('id');
    form.reset();

**Comment by mhevery** [comment]
non reproducable

**Comment by sjsambala** [comment]
I'm getting this issue in angular 8 as well.
