### ISSUE TITLE
Validator.minLength does not work with input type number

### ISSUE THREAD

**Issue by pflopez** [angular/angular#15053]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The build in validator for minLength works for input with type text, email, etc. However, its not working with type number. The value when inspecting `valueChanges` is a number, so I'm guessing its because number does not have a .length method.

**Expected behavior**

minLength validator should return true for any number which length in character count (number.toString() ?) is bigger than provided value, or false otherwise.

**Minimal reproduction of the problem with instructions**

Plunk with issue:
https://plnkr.co/edit/sAITWc?p=preview

**What is the motivation / use case for changing the behavior?**

The validator should work regardless of the type of input field used.

**Please tell us about your environment:**

Mac, chrome, npm.

* **Angular version:** 2.0.X

2.4.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 only tested on chrome.
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
You are looking for this https://github.com/angular/angular/pull/13688

**Comment by mhevery** [comment]
resolved https://github.com/angular/angular/pull/13688
