### ISSUE TITLE
external stylesheet in index.html cannot be found

### ISSUE THREAD

**Issue by lpx1233** [angular/angular#15055]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using `<link rel="stylesheet" href="forms.css"/>` in index.html, the chrome console outputs a 404 for GET http://localhost:4200/forms.css.

When using `<link rel="stylesheet" href="src/forms.css"/>` in index.html, it works fine.

**Expected behavior**

When using `<link rel="stylesheet" href="forms.css"/>` in index.html, it can find my stylesheet.

**Minimal reproduction of the problem with instructions**

https://github.com/lpx1233/angular-forms
The project is here. Using `ng serve` to start application in the root project directory, then goto localhost:4200 and the console will output 404 for GET http://localhost:4200/forms.css 

**Please tell us about your environment:**

OS: Win7
IDE: PyCharm
Browser: Chrome
Package manager: npm + webpack
* **Angular version:** 2.4.8

* **Browser:** [Chrome 56.0.2924.87]

 
* **Language:** [TypeScript 2.0.0]

* **Node (for AoT issues):** `node --version` =   v6.10.0

**Comment by lucastetreault** [comment]
I think you just need to point your angular-cli to your stylesheet: 

`{
$schema: "./node_modules/@angular/cli/lib/config/schema.json",
project: {
name: "angular-forms"
},
apps: [
{
root: "src",
outDir: "dist",
assets: [
"assets",
"favicon.ico"
],
index: "index.html",
main: "main.ts",
polyfills: "polyfills.ts",
test: "test.ts",
tsconfig: "tsconfig.app.json",
testTsconfig: "tsconfig.spec.json",
prefix: "app",
styles: [
"styles.css",
**## "forms.css"**
],
scripts: [ ],
environmentSource: "environments/environment.ts",
environments: {
dev: "environments/environment.ts",
prod: "environments/environment.prod.ts"
}
}
],
e2e: {
protractor: {
config: "./protractor.conf.js"
}
},
lint: [
{
project: "src/tsconfig.app.json"
},
{
project: "src/tsconfig.spec.json"
},
{
project: "e2e/tsconfig.e2e.json"
}
],
test: {
karma: {
config: "./karma.conf.js"
}
},
defaults: {
styleExt: "css",
component: { }
}
}`

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by lpx1233** [comment]
ok, I'm sorry for bothering you @DzmitryShylovich and thank you @lucastetreault I'll try this.
