### ISSUE TITLE
Why is it so annoying to debug angular2 apps and understund error messages ?

### ISSUE THREAD

**Issue by amineparis** [angular/angular#15059]
All the time I get error angular messages that makes debug the worst thing I can notice on this framework
How can I understund something like : `ViewWrappedError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:127413:33)` is it possible to see messages pointing a line of my code instead of to a node package ?

PS: I user ` ng serve`

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vicb** [comment]
@amineparis why do people do no fill out issue templates ?

Jokes aside we are improving both the error message and the debug experience. A lot of improvement has already been made in the last 4.x RC and more should come before the final.
