### ISSUE TITLE
control.updateValue() not working

### ISSUE THREAD

**Issue by ShMcK** [angular/angular#1505]
It seems Form Controls & Local variables can be set, but not changed from within a class (controller).

A basic use case would be resetting a text box to an empty string. [Plnkr example](http://plnkr.co/edit/yii9eY) `main.es6.js` line 24.

I imagined `Control.updateValue(value)` would provide a way, but no change. Is this feature simply undercooked or is there another solution?

**Comment by mhevery** [comment]
can you share more info on how to reproduce the use case? I have a Plnkr but I don't know what to click, and what is expected behavior, or what was hard to implement.

**Comment by vsavkin** [comment]
Fixed here 652ed0cf6df6bd96808bbd6042c2b23a64a9b693
