### ISSUE TITLE
Unexpected page reload on changing url with hash

### ISSUE THREAD

**Issue by axxx307** [angular/angular#15057]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In Chrome when using latest version of angular/router and `RouterModule.forRoot(ROUTES, { useHash: true}) ` changing url with hash will result in page reload. The problem could be a Chromes prefetch which should be disabled with HTTPS, although it doesn`t solve the issue. 

Issues is not present in Firefox, IE, Edge and Opera.

**Expected behavior**

Page should not reload on hash change in url and navigate to another screen.

**Minimal reproduction of the problem with instructions**

As example take this repo [angular-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter).
Start the project with webpack-dev-server. Changing url manually from `http://localhost:3000/#/barrel` to `http://localhost:3000/#/home` would cause a page reload.

HTTPS:
In agular2-webpack-starter/config/webpack.dev.js add `https: true` to devServer:{}.
Use fiddler with HTTPS decryption option enabled to make connection safe. 
Changing url manually from `https://localhost:3000/#/barrel` to `https://localhost:3000/#/home` would cause a page reload and Chrome prefetch, which should be disabled om HTTPS pages.
**Please tell us about your environment:**

* **Angular version:** 2.4.8

* **Browser:** Chrome 57.0.2987.98 (64-bit)

 
* **Language:** TypeScript ~2.2.1

* **Node (for AoT issues):** 7.3.0

**Comment by DzmitryShylovich** [comment]
> Changing url from http://localhost:3000/#/barrel to http://localhost:3000/#/home

changing how? manually in url bar?

**Comment by axxx307** [comment]
@DzmitryShylovich yes, just manualy.

**Comment by DzmitryShylovich** [comment]
we can't do anything with it. this is how browsers work :)

**Comment by axxx307** [comment]
@DzmitryShylovich  I forgot to mention that issue is not present in Firefox nor in IE or Edge. Shoud`ve said it in original post.

**Comment by DzmitryShylovich** [comment]
you are right. didn't notice `{useHash: true}`. But I can't reproduce it on my own project. Looks like an issue with https://github.com/AngularClass/angular2-webpack-starter
Can you try it out using cli or https://github.com/qdouble/angular-webpack2-starter ?

**Comment by axxx307** [comment]
@DzmitryShylovich I've tried your example, works great, but I think the trick is about preloadingStrstegy. As far as I understood every module is preloaded before start. My app structure is a bit different, I have components for screens with some data. Not sure if it's possible to preload them without creating a folder of modules for each component.

**Comment by DzmitryShylovich** [comment]
The router doesn't reload anything by itself so I don't see how we can fix it inside the framework anyway

**Comment by DzmitryShylovich** [comment]
@axxx307 did you fix it?

**Comment by axxx307** [comment]
@DzmitryShylovich Nope, issue still persists. Though I`ve made a simple workaround: if path is blocked canActivate navigates user to / and redirect component takes them to available screen (based on app`s privileges).

**Comment by jasonaden** [comment]
Looks like this is an issue with `angular2-webpack-starter`
