### ISSUE TITLE
Directive not applying on component created using viewerContainerRef.createComponent

### ISSUE THREAD

**Issue by MoLow** [angular/angular#15063]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If a component is created through some template in the components tree,
a directive using the same selector, would apply to it.
however - when creating the same component using `viewerContainerRef.createComponent`, the directive wont apply on that instance of the component.

**Expected behavior**
A directive should apply on any element inside the app's component tree, no matter what way it is created.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/KPF0AYwVUnVIIv8jF3Wa?p=preview
this is a plunkr demonstrating creating the same component via a template, and programically,
it shows that only one instance of the componrnt is being "selected" by the directive.

**What is the motivation / use case for changing the behavior?**
I would expect a directive, to simply "work".

**Please tell us about your environment:**
Winodws 10, Visual studio, using google chrome and webpack.
Node.js 6.9.x

* **Angular version:** 2.0.X

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
it's by design. directives must be known at compile time

**Comment by MoLow** [comment]
So Would it work usinh AOT?

**Comment by DzmitryShylovich** [comment]
nope (not even sure how it's relevant)

See https://github.com/angular/angular/issues/14781#issuecomment-282905662

**Comment by MoLow** [comment]
10x!
