### ISSUE TITLE
Viewchild has potential race condition issue

### ISSUE THREAD

**Issue by samrantmedia** [angular/angular#15060]
The solution \ workaround is fairly simple, but this has the potential to trip some people up, so I want to share this one.

**Current behavior**
The code to replicate looks like this: 
In parent component:
@ViewChild('myHook') child;
mode: string = 'oldValue';
 openModal() {
   this.mode='newValue';
    this.child.open(t);
  }

Where: mode is being passed to the child component as an input. 

The child compoent, then does something like:

open(){
      console.writeline(this.mode);
}

You would expect that 'this.mode' is now set to 'newValue'. However, it was set to 'oldValue'. I got around this issue by passing the mode in as a parameter:

 openModal(mode) {
    this.mode = mode;
    this.child.open(mode);
  }

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Expected behavior**
I would expect that calling the viewChild happens after updating the input values.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Race conditions can be very confusing in a large app

**Please tell us about your environment:**
I am using angular-cli 1.0.0-beta.28.3 
Windows 10

* **Angular version:** 2.0.X
I am using angular-cli 1.0.0-beta.28.3 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome latest. I imagine it is across all browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Whichever ships with the cli mentioned above

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
please add a plunkr

**Comment by samrantmedia** [comment]
Good idea. I hope to do this soon, but unlikely that I will have time today

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
