### ISSUE TITLE
Cannot re-resolve parent routes even with a RouteReuseStrategy

### ISSUE THREAD

**Issue by davidbarratt** [angular/angular#15075]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no way for the parent's route to re-resolve when there are changes even with a `RouteReuseStrategy`.

**Expected behavior**
I expected the `RouteReuseStrategy` to also be run for the parent route(s) when any route in the tree is changed. This way you can change the logic on when it should be reused or not. For instance, I could set a flag to not reuse the parent immediately after a save and then unset the flag when resolve() is executed.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/7v8ARNVT8FSWC7qeEjvv?p=preview

Click on "View" to load the initial node from the "database". Then go to edit, make some changes and click "Save". Going back to "View" has the initial view, not the updated view, even though `RouteReuseStrategy` is set to never reuse.

**What is the motivation / use case for changing the behavior?**
The use case can be seen from the Plunker, but if you make a change on one route and switch to another route. The only work around I have found is to ignore the routing completely in the component and instead rely on the store directly, but this makes the route resolving somewhat useless.

**Please tell us about your environment:**

* **Angular version:** 2.4.9

* **Browser:** [all ]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
@davidbarratt have you tried this https://github.com/angular/angular/pull/14567 feature?
