### ISSUE TITLE
ng4 ngModelChange regression on mobile

### ISSUE THREAD

**Issue by buu700** [angular/angular#15079]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

On mobile, `ngModelChange` is only triggered on completion of typing a word (e.g. by hitting space or enter), rather than on every character input.

**Expected behavior**

As in 2.x, `ngModel` should emit every time a character is typed.

**Minimal reproduction of the problem with instructions**

http://embed.plnkr.co/bXrMnRI9GyRbzR9r19sZ

On desktop, this logs the text of the textarea each time a character is typed, as expected.

On mobile, the change event is only triggered after completing a word, such that typing a sequence of non-whitespace characters or swyping a word won't register any changes.

**What is the motivation / use case for changing the behavior?**

In the case of @cyph, this bug is causing the following incorrect behaviour in our development branch:

![balls](https://cloud.githubusercontent.com/assets/415435/23818043/d636fd32-05c5-11e7-966b-75d9d2a33749.png)

(In the first screen, the message box hadn't transitioned to show the send button as was expected. In the third screen, the last word of the intended message wasn't included because `ngModel` hadn't updated the message value.)

**Please tell us about your environment:**

* **Angular version:** 4.0.0-rc.2  
(Edit: also reproduced with 4.0.0-rc.3)

* **Browser:** Mobile Chrome 56 and Mobile Firefox 52 on Android 6.x
 
* **Language:** TypeScript 2.2.1

**Comment by Toxicable** [comment]
I investigated this a little bit and noticed something interesting; while remote debugging with chrome and my android (chrome 56, Android 7) and noticed that when you enter in values via the remote debugging window it works 100% fine but as mentioned when you use the mobiles keyboard it will not behave the same and only update on end of word. 
I also tested with ReactiveForms and works totally fine there https://plnkr.co/edit/cnIVZmAXn8lHX6sipUhk?p=preview

**Comment by sensen1991** [comment]
hello

**Comment by robwormald** [comment]
Interesting! First - you're sure this is a regression between 2.x and 4.x (as opposed to say, the Chrome version changing out from under you?)

If so, there's a couple of likely causes I can think of offhand:
- the first would be that something differs in the way zone.js patches on android vs desktop chrome, and that would mean potentially your event listeners are running outside Angular's zone.

The easiest way to check that is to check inside your event handler if you're running in Angular's Zone:
```typescript
import {NgZone} from '@angular/core'

//in component
onSomeEventHandler(){
  NgZone.assertInAngularZone()
  //do stuff
}
```
This will throw an Error if you're running outside Angular's zone, which would cause change detection not to run.

If this is the issue, go ahead and open an issue on the ZoneJS repo: https://github.com/angular/zone.js. You can temporarily work around it by explicitly running inside the zone:
```
class MyComp {
  constructor(private zone:NgZone){}
  onSomeEventHandler(){
    this.zone.run(() => {
      //do stuff
    })
  }
}
```

If this isn't the issue, then there's likely something different about the event handlers that we'd need to look at, but i suspect its the above.

**Comment by robwormald** [comment]
Went a bit deeper (thanks @Toxicable for helping out) - it's related to https://github.com/angular/angular/commit/c5ea03a023ccece0c55158ac274e9f9aa7b47e1e

Maybe @vthinkxie can comment? I think we should maybe listen to the `compositionupdate` event as well, but I don't have enough experience to know for sure. @robdodson any advice here? 

(for those wanting to replicate, on OS X you can turn on the japanese Hiritanga/Katakana keyboard and see this behavior) - see also https://jsfiddle.net/oamnkkvL/ for seeing what happens on different setups

Also, the fact this works with reactive forms means we probably have a mismatch in our API

**Comment by robwormald** [comment]
cc @kara @mhevery

**Comment by buu700** [comment]
Well, it sounds like you already confirmed that this is definitely an Angular problem, so not sure if this is helpful, but I was just testing your suggestions and replying when your last comments popped up.

---

re: Chrome, nope, it's definitely not a Chrome / Android / Google Keyboard issue; Cyph still works as expected for me in prod.

re: Zone.js, just tested both `assertInAngularZone` and `zone.run` (and also tried reverting from Zone.js 0.8.0 to the version we have in prod, 0.7.6), and nothing changed.

Also, I was able to reproduce @Toxicable's observation that his `ReactiveFormsModule` variant of the Plunker doesn't have the same problem.

**Comment by vthinkxie** [comment]
@robwormald It seems that android device has different behavior with pc when you enter english words.
In [angularjs code](https://github.com/angular/angular.js/blob/a24777a2c4ad2ac087d9e3aa278fa2e61e8cc740/src/ng/directive/input.js#L1240), when android device is detected the composition event listener should be disabled.
I think this can be patched as where in Angular 4.x code, then I find that there is a UA detector in [exist code](https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/platform-browser/testing/src/browser_util.ts#L30), but it seems it is only used for testing.
any one has idea to patch this to forms module?

**Comment by DzmitryShylovich** [comment]
> Any one has idea to patch this to forms module?

I think we should fix this in `EventsPlugin`.
