### ISSUE TITLE
APP_INITIALIZER should also work with observables

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#15088]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
APP_INITIALIZER only works with promises.

**Expected behavior**
Should also work with observables

**What is the motivation / use case for changing the behavior?**
Consistency with other parts of the framework

**Comment by nukec** [comment]
2 years later.

**Comment by TheAifam5** [comment]
hmmmmmmmmmmmmm :D what's the status?

**Comment by hevans90** [comment]
This still doesn't seem to work at all 0_0

**Comment by johnsnow20087349** [comment]
2 and a half years later

**Comment by vthinkxie** [comment]
I have opened a PR to fix this issue, anyone could check it?
https://github.com/angular/angular/pull/33222

**Comment by pauldraper** [comment]
User expected this to work: https://stackoverflow.com/questions/47422095/angular-app-initializer-promise-vs-observable

**Comment by Thehee** [comment]
3 years later

**Comment by AndrewKushnir** [comment]
Hi, just want to give a quick update: the `APP_INITIALIZER`-related logic was extended (see PR #33222) to also support observables. The change would be available in a few weeks as a part of v12 release.

Thanks @vthinkxie for implementing this feature 👍
