### ISSUE TITLE
AOT with UpgradeModule no longer works with 4.0.0-rc.3

### ISSUE THREAD

**Issue by buu700** [angular/angular#15080]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

JIT compilation works as expected. However, when trying to AOT compile our project that depends on UpgradeModule, it fails with the following error:

```
Unexpected value 'UpgradeModule in /tmp/tmp.dfE8oZDxr2/js/node_modules/@angular/upgrade/typings/static/index.d.ts' imported by the module 'AppModule in /tmp/tmp.dfE8oZDxr2/js/cyph.com/app.module.ts'
...
[a bunch of "Cannot determine the module for class $Component" errors]
...
Cannot determine the module for class AppComponent in /tmp/tmp.ZbOf0oLE7n/js/cyph.com/app.component.ts! Add AppComponent to the NgModule to fix it.
```

**Expected behavior**

As with 4.0.0-rc.2, AOT compilation should succeed. (Our code doesn't depend on anything mentioned in the breaking changes for this release.)

**Minimal reproduction of the problem with instructions**

Not sure if there's anything special about my project that would cause this, but if this isn't a trivially reproducible happy path bug then I can dig into it some more and try to isolate the problem.

**What is the motivation / use case for changing the behavior?**

Normal use.

**Please tell us about your environment:**

* **Angular version:** 4.0.0-rc.3

* **Browser:** Chrome 57
 
* **Language:** TypeScript 2.2.1

* **Node (for AoT issues):** 6.10.0

* **Operating System:** Debian Jessie (in a Docker container on OS X El Capitan)

**Comment by gkalpak** [comment]
This is real :)

**Comment by gkalpak** [comment]
It seems that the `.metadata.json` file for `upgrade/static` is "empty": https://unpkg.com/@angular/upgrade@4.0.0-rc.3/typings/static/index.metadata.json
