### ISSUE TITLE
[4.0.0-rc.3]: Where is BrowserAnimationsModule?

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/angular#15087]
I installed Angular 4.0.0-rc.3 and want to use animations. However, I cannot find `BrowserAnimationsModule` in the following files. Any hint is appreciated.

*  `node_modules\@angular\animations\typings\animations.d.ts`
*  `node_modules\@angular\animations\typings\public_api.d.ts`
*  `node_modules\@angular\animations\typings\src\animations.d.ts`
* `node_modules\@angular\animations\typings\src\private_export.d.ts`

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/blob/master/CHANGELOG.md#installing-rc1

**Comment by juergenzimmermann** [comment]
It was a problem of VS Code: after installing `@angular/animations` it wasn't recognized by VS Code. A simple restart solved the issue...

**Comment by Toxicable** [comment]
@juergenzimmermann Please close this if it's solved for you

**Comment by uitgewis** [comment]
For anyone else stumbling upon this issue after 4.0 final, it's in `@angular/platform-browser/animations`.

**Comment by RezaRahmati** [comment]
I `import { BrowserAnimationsModule } from '@angular/platform-browser/animations'` and added this module to imports in app.module.ts but I get `Cannot find name 'AnimationEngine'` error message on compile.
