### ISSUE TITLE
router: remainder path

### ISSUE THREAD

**Issue by patrikx3** [angular/angular#15097]
I cannot find in StackOverflow or the docs how to use a wildcard path, like this:
```typescript
  {
        path: 'github/:repo/**',
        component: Page
    },
```
To match:
```/github/my-project```
as well
```/github/my-project/any/as/long/i/want/path/an/match/it```

is it possible? I need to get a remained path.

**Comment by DzmitryShylovich** [comment]
You need [UrlMatcher](https://github.com/angular/angular/blob/master/packages/router/src/config.ts#L293)
