### ISSUE TITLE
 Dynamically injecting third party module to Root Module  using webpack

### ISSUE THREAD

**Issue by abhiindian** [angular/angular#15091]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, we can create a shared module or feature module and can inject them in root module.

**Expected behavior**

Is there any possible way where we can dynamically inject shared module or feature module into root module which is already instantiated.

In Angular 1, we can do

angular.module('myApp',['someThirdParty']);
 
for dynamically adding third party module:

angular.module('myApp').requires.push('someThirdParty');

Is it possible in Angular 2??

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

This will help SharePoint developer to dynamically inject their module into root module via OOB Content Editor Webpart

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Don't Know 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 

* **Language:** all 

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
I think you're talking about Lazy Loading
https://angular.io/docs/ts/latest/guide/router.html#!#asynchronous-routing

**Comment by abhiindian** [comment]
@Toxicable Thanks for your reply.

The reason for asking such question is to design the architecture for my project.

I have two pages:

1. Index.html (Home Page)
2. Admin.html (Admin Control Panel with Sign-in mandatory to access this page)

for these pages do I need to create separate root module or single root module?
And how to bundle them in case there is single root module using webpack.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by abhiindian** [comment]
@DzmitryShylovich apologizes for the inconvenience caused.

**Comment by IgorMinar** [comment]
thanks @DzmitryShylovich
