### ISSUE TITLE
ViewChild not ready by ngAfterViewInit

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular#15100]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Manipulating the DOM on the `ngAfterViewInit` event fails, as the `ViewChild`s are invalid.

**Expected behavior**
When you see the demo of this issue, the function called by the `ngAfterViewInit` should have the same response it does as when it is triggered by the button press.

**Minimal reproduction of the problem with instructions**
See this [plunk](http://plnkr.co/edit/BNK6rbfBUAleXF6X9ckg?p=preview), a function is called both on the `ngAfterInit` event and on button click, but only has an impact on the button click.

**What is the motivation / use case for changing the behavior?**
The DOM should be manipulatable from the ngAfterInit event?

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.4.5

* **Browser:** [all]

 
* **Language:** [TypeScript 2.1]

**Comment by DzmitryShylovich** [comment]
> import {Component, View, CORE_DIRECTIVES} from 'angular2/angular2'

please use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview for repro :)

**Comment by georgeedwards** [comment]
@DzmitryShylovich Will do, but the plunk is replicating an issue I am facing with 2.4.5

**Comment by Toxicable** [comment]
In your plunkr's `ngAfterViewInit()` is never even being called.
However the version you're targeting looks < 2.0.0-RC.4 since you don't have modules, you're using the `@View` annotation and importing from `'angular2/angular2'`, what even is this?
Please use https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 for 2.x and 
http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview for 4.x

**Comment by georgeedwards** [comment]
@Toxicable @DzmitryShylovich OK, here is the same issue shown using the up to date [plunk](http://plnkr.co/edit/JxMVyp92Xa3ukfcM0wQY?p=preview)

**Comment by DzmitryShylovich** [comment]
@georgeedwards http://plnkr.co/edit/unRT5eTrid5UkYUtoo2z?p=preview
http://stackoverflow.com/a/11435082

**Comment by DzmitryShylovich** [comment]
@IgorMinar it's not a bug. everything works as intended and it can be closed

**Comment by georgeedwards** [comment]
@DzmitryShylovich Thanks for finding that! 
The docs say that on that event the DOM will be loaded and manipulatable , that isn't the case when using SVGs, so why is this the intended behaviour?

**Comment by DzmitryShylovich** [comment]
it can be svg or some lib that takes time to load. angular doesn't know and shouldn't know about it

**Comment by georgeedwards** [comment]
@DzmitryShylovich I do agree, but I feel like for SVGs (and all major image files), it would be handy to have a built in event so you know your DOM is fully loaded. It depends on the design goals of the lifecycle events.

Anyway, if this is out of scope, then no problem, please do close the issue. 

On a side note, is there a way of querying an svg to see if it is loaded, otherwise if the function is called after the svg has been loaded, then the event never triggers and the logic never completes?

**Comment by DzmitryShylovich** [comment]
>  is there a way of querying an svg to see if it is loaded

for example http://plnkr.co/edit/A7htKzZzmVrQ71yc9weV?p=preview
