### ISSUE TITLE
Cannot match routes when I use multi router-outlet in child router module

### ISSUE THREAD

**Issue by xn330125** [angular/angular#15108]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

there are 2 router-outlet in a child module, but i can't navigate to the named outlet. And it's ok if I combine routers into one module.

**Minimal reproduction of the problem with instructions**
this is an example, i can't navigate to compenent 4. It throws error ' Cannot match any routes'
http://plnkr.co/edit/oK8d9dWV2j35iT85W6ve?p=preview

* **Angular version:** 

2.4.0

**Comment by joshmobley** [comment]
Having the same issue. Works fine if it's an empty child route, or if the outlet is unnamed, but if i try to use a child route with a named outlet, I get the error.

**Comment by joshmobley** [comment]
@xn330125 -- is this resolved in 4.x?

**Comment by xn330125** [comment]
@joshmobley yes, it's been solved in v4.0. There is a little difference when using child router. you can read the document.

**Comment by joshmobley** [comment]
I'm currently working on a project on 4.0.0 and it's having the same issues...what specific version took care of the bug?

**Comment by xn330125** [comment]
sorry, actually my enviroment is in  v4.1.0-beta.1
