### ISSUE TITLE
ng4: flattened module exports break third-party dependencies

### ISSUE THREAD

**Issue by marshall007** [angular/angular#15119]
See also https://github.com/angular/angular/issues/14795#issuecomment-283022951

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Attempting to upgrade a project to `v4.0.0-rc.*` results in compilation errors for any third-party dependencies referencing deep imports (like `ui-router-ng2` in the case below):

```
ERROR in ./~/ui-router-ng2/lib/uiRouterNgModule.js
Module not found: Error: Can't resolve '@angular/router/src/router_config_loader' in './node_modules/ui-router-ng2/lib'
 @ ./~/ui-router-ng2/lib/uiRouterNgModule.js 6:0-66
 @ ./~/ui-router-ng2/lib/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

**Expected behavior**

Deep imports should either still be supported or this needs to be documented in the release notes as a breaking change.

**Minimal reproduction of the problem with instructions**

`import { ROUTES } from '@angular/router/src/router_config_loader';`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** `4.0.0-rc.*`

* **Browser:** all
 
* **Language:** TypeScript `v2.3.0-dev.20170308`

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
deep imports are not supported and this is intentional

**Comment by DzmitryShylovich** [comment]
cc @IgorMinar

**Comment by IgorMinar** [comment]
Yeah, this works as expected. the ui-router depends on private APIs which are no longer reachable. If these private apis are needed at all I suggest that a new issue is created requesting the desired functionality.
