### ISSUE TITLE
Select is not working when the value is 0

### ISSUE THREAD

**Issue by Jonatthu** [angular/angular#15120]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When we have the number 0 as a value coming from a object the select is not selecting the` value="0"`, until I apply` JSON.stringify(0)` (0 is the value) this now is working, but this is not happening to other number greater than 0. I'm using reactive forms if that is helpful.

**Expected behavior**

Select the option with the value 0 without apply JSON.stringify to the object value.

* **Angular version:** 2.0.X

Angular 4 rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Latest Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   6.9.x

**Comment by DzmitryShylovich** [comment]
Please add a plunkr
