### ISSUE TITLE
Feature: Allow multiple structural directives on element

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#15139]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, it's not possible to use more than one structural directive on element.
If one wants to use `NgIf` and `NgFor` on element, it must be wrapped in `<template>`.
It's necessary, because we need to specify which directive should be outer, and which inner, but we get ugly code like this:
```html
<ul>
  <template ngFor let-item [ngForOf]="list">
    <li *ngIf="item % 2 === 0">{{item}}</li>
  </template>
</ul>
```

**Expected behavior**
We should be allowed to use multiple structural directives on the same element. To do so, I propose to extend asterisk syntax, like this:
```html
<ul>
  <li *ngFor=let item of list" **ngIf="item % 2 === 0">{{item}}</li>
</ul>
```
Notice, there are two asterisk by `ngIf`. In general, more asterisks, deeper the directive should be nested.
We still need to explicitly state the order and which attribute is first doesn't matter.
Following example:
```html
<div *ngIf="A" **ngIf="B" ***ngIf="C"></div>
```
Should be expanded to:
```html
<template [ngIf]="A">
  <div *ngIf="B" **ngIf="C"></div>
</template>
```
Which should be expanded to:
```html
<template [ngIf]="A">
  <template [ngIf]="B">
    <div *ngIf="C"></div>
  </template>
</template>
```
And so on...

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
I think combing `NgIf` and `NgFor` on the same element very common case.
Extended syntax allow to write cleaner code without necessity for expanding `*ngFor` microsyntax.

* **Angular version:** any

**Comment by DzmitryShylovich** [comment]
It was already discussed multiple times. It won't be supported.

**Comment by dawidgarus** [comment]
I didn't find any issues when I search for 'asterisk' or 'structural', but if it was discussed it multiple times before and people still wan't it, why not reconsider?
Perhaps previous proposals didn't met angular standards. My proposal is backwards compatible and it doesn't require that template parser know anything about order of attributes.
If angular team is not willing to implement it, maybe someone else can, but it will be pointless if You decide not to include the feature.

**Comment by DzmitryShylovich** [comment]
For example, this discussion https://github.com/angular/angular/issues/4792#issuecomment-149282241

**Comment by dawidgarus** [comment]
But I'm not talking about just `NgIf` + `NgFor` - it's more generic.
Clearly, You can see that issues You had with AngularJS, will not occur here, because what I'm proposing is just a syntax sugar for already _existing_ and _recommended_ way of using `NgIf` and `NgFor` together.
And as I mentioned before, with proposed syntax, preserving order of attributes is not an issue.
There is no need for directive priorities or anything like that.
My proposal addressed all the issues that arose before. Angular changed a lot since the discussion mentioned before and it might be a good time to reconsider it.

**Comment by alxhub** [comment]
We have no plans to make major changes to Angular template syntax at this time.
