### ISSUE TITLE
Click events aren't handled for icon fonts

### ISSUE THREAD

**Issue by jkap** [angular/angular#1513]
version alpha-20, tested in Chrome 42.0.2311.90 on OS X 10.10.3.

plunker: http://plnkr.co/edit/FiabLGTEe4RV4YfiuVzT?p=preview

Clicking both the lightbulb and the "test" text should pop up an alert, but the alert only appears when clicking "test".

This bug also seems to be present in alpha-19.

**Comment by SekibOmazic** [comment]
@jkap In Angular2 the event do not bubble up. So when you click on the lightbulb you click on the `<i>` where you have no handler. And since the event doesn't get bubbled up your click handler on <a> never gets invoked. Just put the `(click)=...` to the `<i>` and everything will be fine.

**Comment by rkirov** [comment]
or use `(^click)` to catch bubbled events.

**Comment by jkap** [comment]
We ended up using `(^click)` to handle nested elements. We're going to do an internal benchmark to determine whether or not one `(^click)` or multiple `(click)`s is more performant for a large page. Is this something that would be useful to have in the main repo? If so, we can open a PR for it

**Comment by pkozlowski-opensource** [comment]
There is an issue opened by @jelbourn where he argues in favor of catching bubling events by default: https://github.com/angular/angular/issues/1040

This also seems to be default behavior in ng 1.x: http://plnkr.co/edit/BcugmXyRKjX9EahAvpD7?p=preview

**Comment by mhevery** [comment]
Since we already have #1040 open, closing this one.
