### ISSUE TITLE
Book feature on the Resources page

### ISSUE THREAD

**Issue by packtpartner** [angular/angular#15135]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**What is the motivation / use case for changing the behavior?**

I would like to feature books published under the "Education" section which would help budding developers. Where can I find the repository to feature books on https://angular.io/resources/#!#Education ?
Would appreciate your help

**Comment by DzmitryShylovich** [comment]
> Where can I find the repository to feature books on https://angular.io/resources/#!#Education ?

https://github.com/angular/angular.io
But new site is under development so I'm not sure if they merge prs.

**Comment by packtpartner** [comment]
@StephenFluin can you help me out?

**Comment by StephenFluin** [comment]
@packtpartner Packt is already featured on the Education -> Books section.
