### ISSUE TITLE
UrlMatcher should be exported or removed from the API docs

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#15140]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The Router interface uses `UrlMatcher` and `UrlMatcher` is not exported.

**Expected behavior**

The `UrlMatcher` should be exported as well. We have documentation for it but leads to a 404.

**What is the motivation / use case for changing the behavior?**

I am a member of the docs team and we get an issue every other week about the `UrlMatcher` link [here](https://angular.io/docs/ts/latest/api/router/index/Routes-type-alias.html) leading to a 404.

There are a few issues in this repo, a few issues on aio repo. I decided to investigate the issue with @petebacondarwin to see if that was a dgeni issue and we discovered (well, he did) that dgeni is not parsing out the `UrlMatcher` documentation [which exist here](https://github.com/angular/angular/blob/master/packages/router/src/config.ts#L273-L292) because at the end, the `UrlMatcher` is not exported with the barrel.

I am in no position to assert that it should be public or not, but we can't document it otherwise, so it would be better to decide in make it public or remove the link from the API since we cannot document it (and I think we shouldn't if it is not public).

**Comment by IgorMinar** [comment]
I'm marking this as a candidate for 4.0.0 because it's an easy fix and currently results in issues in our docs infrastructure.  // @vicb

**Comment by Foxandxss** [comment]
I don't see this anymore in the API docs @IgorMinar . Should we close or ... ?
