### ISSUE TITLE
Method inside *ngFor is getting called multiple times

### ISSUE THREAD

**Issue by ask007java** [angular/angular#15145]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Method inside *ngFor is called multiple times.  

**Expected behavior**
I am expecting it to be called n times where n is the size of an array.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/6dBtJRPPiTaW6YShczzM?p=preview
please check developer tool's console log.

**What is the motivation / use case for changing the behavior?**
Iterate through an array and display its content using *ngFor.

**Please tell us about your environment:**
 chrome 56.0

   <script src="https://cdnjs.cloudflare.com/ajax/libs/typescript/2.1.1/typescript.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.41/system.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>

**Comment by DzmitryShylovich** [comment]
don't use functions in bindings. your function will be called on every change detection cycle. and angular runs x2 cycles in dev mode

**Comment by IgorMinar** [comment]
@DzmitryShylovich is right. This works as expected. The bound methods are called twice in dev mode in order to guarantee that they don't have unexpected side-effects.

**Comment by omt66** [comment]
@IgorMinar  I am curious why it runs twice in the dev mode? Are they safe in production mode?
