### ISSUE TITLE
Nested route animation triggered while parent route change

### ISSUE THREAD

**Issue by bobotu** [angular/angular#15141]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If I have a nested route:
```html
<router-outlet>
  <!--some thing here-->
  <router-outlet></router-outlet>
</router-outlet>
```
And I set a route animation for component in the child outlet (follow instructions in official docs). It works fine if I don't navigate out of this router, for example `/foo/bar` to `/foo/foo`. But when I change the parent route path, `/foo/foo` to `/bar`, both the outer and inner route's animation will trigger. 

**Expected behavior**

Have a method to config whether child route's animation will trigger when parent route change.

**Minimal reproduction of the problem with instructions**

[plunkr demo](http://plnkr.co/edit/ZyOmxb6wm4B6aISKCZLv?p=preview)

**What is the motivation / use case for changing the behavior?**

Two different transition animation trigger at the same time make the final effect unexpected.
**Please tell us about your environment:**

* **Angular version:** 2.4.9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** 
TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   

EDIT 1: 
[plunkr demo](http://plnkr.co/edit/ZyOmxb6wm4B6aISKCZLv?p=preview)
`/bar` <=> `/foo` have scale and opacity transition.
`/foo/1` <=> `/foo/2` have translateX transition.
When navigate from `/foo/1` to `/bar`, will trigger scale and translateX.

**Comment by DzmitryShylovich** [comment]
Please add a plunkr

**Comment by matsko** [comment]
This should be fixed in the current master. Please retry to see if it works and reopen the issue if it's still problematic. Thank you @bobotu.
