### ISSUE TITLE
input type="file" Validators.required Failed in Chrome 

### ISSUE THREAD

**Issue by marvindaviddiaz** [angular/angular#15149]
I have a form with a required input file, When I select a file, the component status is 'INVALID'.
It happens in Chrome, but It works in Firefox.

I attach you the image.

HTML
<input
type="file"
name="file"
formControlName="file"
(change)="onFileChange($event)"
accept=".xls,.xlsx">

TS:
this.form = new FormGroup({
  'hexId': new FormControl(''),
  'name': new FormControl('', [Validators.required]),
  'file': new FormControl('', [Validators.required]),
...

![issuefile](https://cloud.githubusercontent.com/assets/13956614/23918503/dbd001f8-08b8-11e7-8deb-458d6d7104f7.png)

**Comment by DzmitryShylovich** [comment]
Angular doesn't officially support file input. See https://github.com/angular/angular/issues/7341

**Comment by DzmitryShylovich** [comment]
@marvindaviddiaz please add the plunkr that illustrates the issue. thanks

**Comment by marvindaviddiaz** [comment]
Here it is.

https://embed.plnkr.co/sk7nNlVsmSwzxdcriV2D/

**Comment by mhevery** [comment]
Angular does not have support for file input since that requires server side component. Out of scope.

**Comment by woodcockjosh** [comment]
@mhevery How would I see if the user selected a file or not? Isn't that the point here? I don't think that a client side validation to make sure the user selected a file is out of scope for a client side validation feature set.

**Comment by israelpereira** [comment]
I got here with the same problem, I need validate if the client selected a file or not .. this is not a server side stuff. I need it in the client side .. I never imagine that angular doesn't support something absolutely basic.
