### ISSUE TITLE
get a comment in the template

### ISSUE THREAD

**Issue by teabagp** [angular/angular#15143]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When i use empty template, i get a comment in component (this ). 
This behavior occurred after the update to 4.0.0-rc.1

**Expected behavior**
In 4.0.0-beta.8 I get empty component

**Minimal reproduction of the problem with instructions**
angular 4.0.0-rc.1
http://plnkr.co/edit/C4uCLuL5pQqsH8ToR5yS?p=preview

angular 4.0.0-beta.8
http://plnkr.co/edit/8TnxGwzojU2Z026RcaHD?p=preview

* **Angular version:**  4.0.0-rc.1

* **Browser:** all

**Comment by DzmitryShylovich** [comment]
This change was introduced by https://github.com/angular/angular/pull/14469
Angular creates an empty comment [here](https://github.com/angular/angular/blob/cdc882bd36056c74f03964f37eeb4a6ffbe95525/packages/core/src/view/element.ts#L164)

@tbosch do you know why it as required?

**Comment by teabagp** [comment]
Give advice on how best to get rid of comment?

**Comment by DzmitryShylovich** [comment]
@teabagp for example like this http://plnkr.co/edit/FANAd3wPtqrKoTdxG2c5?p=preview

but you should really avoid direct dom manipulations. why do you need a component with an empty template? maybe directive would be better?
