### ISSUE TITLE
[universal] renderModuleFactory and d3 library

### ISSUE THREAD

**Issue by jkuri** [angular/angular#15150]
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using some 3rd party library, such as `d3` that manipulates with DOM directly or using any of `document` or `window` methods `renderModuleFactory` does not get bootstrapped. 
In the repository below I could manage to get it bootstrapped with "fix" to add

```ts
if (!el) {
  return;
}
```

before https://github.com/angular/angular/blob/018e5c979b05e3240705e5d414b588820a99a6aa/packages/platform-server/src/parse5_adapter.ts#L142 this line.

Also, I needed to use `isBrowser` [function](https://github.com/jkuri/angular-universal-d3-bug/blob/master/src/is-browser.ts) and return if rendered from node side. 

**Expected behavior**

I would expect `isBrowser` function would be implemented and checked inside `renderModuleFactory` and stop executing current method where something is used from the DOM directly. At least it would be cool not to check everytime manually. If this is not possible then it would be okay that we could import `isBrowser` method from `platform-server`.

**Minimal reproduction of the problem with instructions**

```sh
git clone https://github.com/jkuri/angular-universal-d3-bug.git
cd angular-universal-d3-bug
npm install
npm run build:prod
node dist/server.js 
```

**What is the motivation / use case for changing the behavior?**

I believe libraries such as `d3` people are using a lot and also Universal is essential for websites seo so this can save a lot of pain and opened issues.

* **Angular version:** 4.0.0-rc.3

**Comment by vikerman** [comment]
Sorry - we don't handle arbitrary DOM API calls from third part library in Universal at this time - but thanks for the feedback. We are considering a better solution for this post 4.0.

You would have to exclude it from your server side by
1) injecting PLATFORM_ID and using isPlatformBrowser(id) from @angular/periscope-functions 
2) Detect you are running on node and don't include the d3 parts
3) Use Angular DI that hooks up your D3 stuff only on the client module

**Comment by jkuri** [comment]
@vikerman thanks 👍 `isPlatformBrowser()` is what I was looking for. 
I managed to solve this by removing `@HostListener('window:resize', ['$event'])` and add listener after checking if it is in browser.

**Comment by vikerman** [comment]
@jkuri - The @HostListener('window:...') issue is resolved in rc.4. It will be noop on the server.
