### ISSUE TITLE
DI: bind(Type) should be equivalent to just specifying the Type

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1515]
Example:

```dart
bootstrap(MyAppComponent, [
  bind(ShadowDomStrategy).toClass(NativeShadowDomStrategy),
  bind(AwesomeService)
]);
```

Does not work. It's a little non-intuitive why.

```dart
bootstrap(MyAppComponent, [
  bind(ShadowDomStrategy).toClass(NativeShadowDomStrategy),
  AwesomeService
]);
```

Does work.

Either error should be improved, or `bind()` (`BindingBuilder`) should implement `Binding` interface

**Comment by pkozlowski-opensource** [comment]
We are [already throwing](https://github.com/angular/angular/blob/b72eb0783b24a785c34d4f74e667c224adb36b12/modules/angular2/src/di/injector.js#L381-L382) in this situation so I've sent PR #1573 to improve the error message.
