### ISSUE TITLE
Routing works, but jasmine fails the component test - 'caused by: No provider for RouterOutletMap'

### ISSUE THREAD

**Issue by mLaird** [angular/angular#15152]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using Angular 2.4.9, Jasmine 2.4.1, and Typescript 2.2.1, I have a Material header and footer with `<router-outlet></router-outlet>` in between in my AppComponent. Jasmine tests OK for creating the component. 
When I add the HomeComponent and route it to load by default, it loads in both Chrome and FF and displays correctly, but the same Jasmine test for AppComponent fails with the messages - 

> "AppComponent should create the AppComponent component.   Error in http://localhost . . . /headerFooter.html:71:5 caused by: No provider for RouterOutletMap! " and "Error: Expected undefined to be defined."

The line 71:5 is the `<router-outlet></router-outlet>` line.
I have tried importing RouterOutletMap into app.component.ts, app.component.spec.ts, and app.module.ts - each individually, and importing into all 3 at once.  In all 4 cases, I get the above test error.  I have searched the current Routing & Navigation section of devdocs for RouterOutletMap, and the term is nowhere explained for use. 

**Expected behavior**

Routing a component should not affect Jasmine test for creating a component -  expect(comp).toBeDefined()

**Minimal reproduction of the problem with instructions**

*STEPS TO REPRODUCE*
1. make an AppComponent with a Material header and footer and `<router-outlet></router-outlet>` between them.
2. make a spec.ts test with `it('should create the AppComponent component', () => expect(comp).toBeDefined() );`
3. default route a simple text statement home component into `<router-outlet></router-outlet>` with `{ path: '', redirectTo: '/home', pathMatch: 'full' }` in the app.module.ts  Observe the Jasmine test results.
4. Check documents and error statements for useful explanations of RouterOutletMap and how to use it.

**What is the motivation / use case for changing the behavior?**

Routing a component should not affect Jasmine test for creating a component. If RouterOutletMap is required somewhere, its existence and use should be explained in devdocs.

**Please tell us about your environment:**

Windows 10
Atom

* **Angular version:** 2.0.X

Angular 2.4.9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, FF
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.1

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
did you import `RouterTestingModule`?
and please add a plunkr

**Comment by mLaird** [comment]
Thanks for the clue. It helped me fix the test.  This link has very helpful information about how to use RouterTestingModule.  
https://github.com/antonybudianto/angular2-starter/blob/master/src/app/app.component.spec.ts
 
My suggestion is to change the Console error message to say something like - RouterTestingModule is missing.  The error - No provider for RouterOutletMap - leads down the wrong road.

Thank you for your help.
