### ISSUE TITLE
FormControl errors property get old value

### ISSUE THREAD

**Issue by finalxcode** [angular/angular#15161]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Curently the errors property of the FormControl is an object

**Expected behavior**

It would be better if it was new object after form valid finished

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

 `this.userForm = this._formBuilder.group({
      'name': ['', [Validators.required, Validators.minLength(2), Validators.maxLength(100)]],
    });`
  `let control = this.userForm.controls['name'];
  console.log('form error', control.errors);`

when i input name for 1 character, `control.errors` is still `{required: true}`, but when i use control.valueChange or control.statusChange, i get `control.errors` is `{minlength: {actualLength
:1, requiredLength:2}}`.
1.  i want to know which correct way to get form control error property ? 

2.  where can i use event `valueChange` or `statusChange`,  just `ngOnInit` function inside? 

3.  What is status change? form control value change will trigger it, else about form control `pristine, valid...` also will trigger it?

**Please tell us about your environment:**

npm -v    3.10.10
node -v   v6.9.4
os   win32 x64
IDE visual studio code 1.10.2

* **Angular version:** 2.0.X

   @angular/cli: 1.0.0-beta.31
   @angular/common: 2.4.8
   @angular/compiler: 2.4.8
   @angular/core: 2.4.8
   @angular/forms: 2.4.8
   @angular/http: 2.4.8
   @angular/material: 2.0.0-beta.2
   @angular/platform-browser: 2.4.8
   @angular/platform-browser-dynamic: 2.4.8
   @angular/router: 3.4.8
   @angular/cli: 1.0.0-beta.31
   @angular/compiler-cli: 2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

   Chrome  56.0.2924.87 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
   "typescript": "~2.0.0"
   ES5

* **Node (for AoT issues):** `node --version` =

**Comment by alexzuza** [comment]
Please add a plunker

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
