### ISSUE TITLE
302 server status code redirection is not workin

### ISSUE THREAD

**Issue by stefdelec** [angular/angular#15165]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When we make a get request, server send us back a 302 to the same SPA. Angular2 is not handling the redirection, and we have a 404 error in browser
It is working fine if I copy paste myself the link in browser.

**Expected behavior**
It should redirect properly to the page and route to the component based on the url.

**Minimal reproduction of the problem with instructions**
1/ Make a get request
2/ Server send back a 302
3/ Browser console log a 404 error.
(see below provided code)
**What is the motivation / use case for changing the behavior?**
Angular2 should be able to handle this behavior because 302 is used in Auth2 standard.

**Please tell us about your environment:**

Angular

* **Angular version:** 2.4.0

* **Browser:** [all ]

 * **Language:** [ TypeScript 2.1]

--Esxtra code:

Node server:
```
app.get('/app', function(req, res) {
    console.log(req.query.redirecturi);
    res.writeHead(302, {
        'Location': req.query.redirecturi,
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept",

        //add other headers here...
    });
    res.end();
});
```

Angular2 request
`  this._http.get("http://localhost:3000/app")`

**Comment by DzmitryShylovich** [comment]
It's not an angular problem http://stackoverflow.com/a/24785762

**Comment by stefdelec** [comment]
I think it is an angular problem as making an interceptor for a 302 is not very "clean" coding I think.

**Comment by DzmitryShylovich** [comment]
@gkalpak how do you handle this in ng1?

**Comment by stefdelec** [comment]
I didn't do anything on angular1. But it seems to me that is not the right way of handling 302.

**Comment by DzmitryShylovich** [comment]
it's not about angular. did you read the link?
> it's not a problem in the angular platform. The xmlHttpReuest do not support this kind of behaviour, and the browser act before you can do anything about it

**Comment by stefdelec** [comment]
Yes, I did. But anyway. I should'n't have a 404 error. Angular Router is  not routing anywhere. It should be the same behavior as I write myself an url in my browser.

**Comment by marcusvetter** [comment]
Hi! Any progress on this @stefdelec ? We have exactly the same issue as you described ;-) The browser should redirect the page before angular gets control -- but unfortunately this does not happen :-/

**Comment by stefdelec** [comment]
2 or 3 solutions : 

1/ We had to do it because of oAuth2 standard. So had a temporary workaround instead of doing a get we do : window.replace().
2/ Angular 4.2 (or 3) implemented an interceptor :https://angular.io/guide/http#intercepting-all-requests-or-responses . However I don't like this solutions.
3/ We will change next month the server side implementation of oAuth2 and  intead of doing a 'get', we will go a 'post'.

Hope it helps.

**Comment by kibbled** [comment]
@stefdelec this helped however I noticed that the event doesn't fire when the HTTP code is 302. Those redirects end up getting sent to the handler with 200 code.

> export class RedirectHttpInterceptor implements HttpInterceptor {
>   intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
>     return next.handle(req).do(event => {
>       if (event instanceof HttpResponseBase) {
>         const response = event as HttpResponseBase;
>         if (response.status === 302) {
>           window.location.href = 'https://www.google.com';
>           return;
>         }
>       }
>     });
>   }
> }

**Comment by kibbled** [comment]
I had forgotten that you cannot intercept 302 HTTP codes so you pretty much have to hack it. The correct solution is to rework the web services to not return 302 HTTP codes if you're using existing web services that cannot be refactored you can do something like this:

export class RedirectHttpInterceptor implements HttpInterceptor {
  private readonly logoPartialUrl = 'helloWorld/logon'.toLowerCase();

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req)
      .do(event => {
        if (event instanceof HttpResponseBase) {
          const response = event as HttpResponseBase;
          if (response && response.ok && response.url && response.url.toLowerCase().indexOf(this.logoPartialUrl) >= 0) {
            const queryStringIndex = response.url.indexOf('?');
            const loginUrl = queryStringIndex && queryStringIndex > 0 ? response.url.substring(0, queryStringIndex) : response.url;
            console.log('User logout detected, redirecting to login page: %s', loginUrl);
            window.location.href = loginUrl;
          }
        }
      });
  }
}

**Comment by adammedford** [comment]
As much as has been said about this not being an "Angular" problem, it is. We've had code in production for months that handled this exact scenario. However, after upgrading to the new HttpClient this seems to be a breaking change. I even consulted the source for the HttpClient and there is nothing in it that would suggest a 302 response would be swallowed. 

To be clear, I don't expect this to handle the redirect - my existing code does that fine. My issue is that I no longer see any response when it has a status code of 302 (except for my in my browser's network tab.) Previously my error handling watched for the 302 and redirected manually. If this isn't a behavior that the Angular team plans to implement - fine. But this definitely needs to be included as a breaking change.

**Comment by Malkiat-Singh** [comment]
same issue in firefox, safari 
chrome working fine

**Comment by stefdelec** [comment]
@Malkiat-Singh It is not an Angular problem, but a normal behavior of your browser.

**Comment by Malkiat-Singh** [comment]
@stefdelec 
But different behavior for chrome and safari/firefox 
I think that should be in known issue of angular

**Comment by Malkiat-Singh** [comment]
@stefdelec  any update please

**Comment by kriscoleman** [comment]
I'm having the same problem. I am calling a api that sends a 302, which I have no control over. 

What's interesting to me, is if I hit the endpoint directly in my browser, my browser does the right thing and will redirect to the Location provided by the 302 response. 

But when Angular handles it, it just fails. It does not handle the redirect at all. People are saying this is a browser issue and not an Angular issue, but if that were true, I'd expect the browser to fail too when I hit the endpoint directly through my browser (not through the angular frontend). What's more, is people here are suggesting it worked on Ng 1... Perhaps this should have a second look.

**Comment by cguilhermef** [comment]
I've a little bit problem like this. When server returns a 302 code, i WANT to be redirected. But, Angular fails - my browser doesn't redirect.

**Comment by mcterrySep** [comment]
We are seeing this same behavior when posting to an API that responds with a 302. It looks like the Angular HTTP client is trying to re-post using the redirect URL, which doesn't result in an actual redirect in our case.

**Comment by cguilhermef** [comment]
After an unpleasant exchange of messages in Stackoverflow, I understood the problem. when Angular makes a request that results in a 302 response, it is a ajax request. Then, Angular http will do the next call to the new url. What we want is the browser acting, redirecting it. But it will not ocurr. Is not a browser request that is redirecting. Is an ajax request.

**Comment by Malkiat-Singh** [comment]
@cguilhermef 
@mcterrySep 
Just resolved by create the proxy API. So angular app  have to call proxy api

**Comment by stefdelec** [comment]
@Malkiat-Singh can you be more detailed ?

**Comment by Malkiat-Singh** [comment]
@stefdelec 
I have created one more API endpoint(Proxy API ) 
Proxy API internally call the actual API that returns 302 
So its whatever actual API returned after 302 proxy API returned same back.

**Comment by cguilhermef** [comment]
@Malkiat-Singh hmm... maybe work, but I belive that it will not solve my issue. I need the browser rendering a new application, on other URI. I will solve my issue using OpenID approach. But your soluction may can be used to solve some issues from other peoples here.

**Comment by akuniyil** [comment]
Is anyone able to find a work around for this issue?

**Comment by kibbled** [comment]
@akuniyil it's not an issue with Angular, it's a problem with how older web services were designed. If you cannot refactor the web services you can work around it with an interceptor (see above).

**Comment by rpcarnell** [comment]
Don't forget to add the CORS library:

var corsOptions = {
  origin: 'localhost:8102',
  optionsSuccessStatus: 200 // some legacy browsers (IE11, various SmartTVs) choke on 204 
}

app.use(cors(corsOptions))

**Comment by Agora-Analytics** [comment]
@kriscoleman We have the very similar issue.  Did it work in some way?

**Comment by panchaln0110** [comment]
@kriscoleman I am having same issue. Did you find any solution? if yes Please let me know.

**Comment by stefdelec** [comment]
Yes I did. And I answered this question. You should not intercept a 302.

**Comment by panchaln0110** [comment]
@stefdelec How do I solve it?

**Comment by stefdelec** [comment]
If you server says there is a reidrection... Why do you need to intercept?
Change the server side method

**Comment by panchaln0110** [comment]
Sorry! May I know how to change it?

**Comment by Daniieloo10** [comment]
i have the same problem just change in the server side the status of Response from 302 to another statut like 200

**Comment by pks90** [comment]
Just in case you are initiating a **post request from the frontend api** and **on the express side you are using a put request** the browser responds with this error. This error response code won't help as cors error in the console but this could be a case.
