### ISSUE TITLE
do we need to use state management 3rd library like ngrx to make an apps?

### ISSUE THREAD

**Issue by hengkyz** [angular/angular#15162]
i want to know do we need to make an apps?

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by hengkyz** [comment]
@DzmitryShylovich sorry , and thank you for your guidance

**Comment by Toxicable** [comment]
@hengkyz no you don't have to use a 3rd party lib for state management, but it is a good addition. I wouldn't advise it if you'res tarting out, learn one thing at a time.

**Comment by hengkyz** [comment]
@Toxicable please help me in here https://stackoverflow.com/questions/42803891/do-we-need-state-management-library-like-ngrx-to-make-an-apps-in-angular2

**Comment by hengkyz** [comment]
@Toxicable i just don't know when to use it or not? i mean which case that we really need that kind of library
