### ISSUE TITLE
Add a reference language option to ng-xi18n

### ISSUE THREAD

**Issue by sebdej** [angular/angular#15167]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The ng-xi18n tool assumes that English is the reference language of i18n markers in the source code.

**Expected behavior**
The user should be able to configure ng-xi18n for a different language.

**What is the motivation / use case for changing the behavior?**
In many cases English is not the most suitable as a reference language for translation. It is difficult to describe in English grammatical rules that do not exist in this language.

**Comment by mlaval** [comment]
This was already implemented in #14537, please use the new `locale` option, e.g. 
`./node_modules/.bin/ng-xi18n -p tsconfig-xi18n.json --i18nFormat=xlf --locale=fr`
