### ISSUE TITLE
By.css() query does not find SVG elements

### ISSUE THREAD

**Issue by dominique-mueller** [angular/angular#15164]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, the `By.css()` query function seems not to be able to find SVG elements in the DOM.

**Expected behavior**
It is expected that the `By.css()` query function returns the HTML element as a result, no matter of what kind the element is (div or span or svg or ...).

**Minimal reproduction of the problem with instructions**
In one of my components, I do have an SVG element which looks similar to:

``` html
<svg class="button__icon" viewBox="0 0 64 64" *ngIf="showIcon()">
    <path d="..."></path>
</svg>
```

Then, within my unit test, I want to query for this SVG element in order to check whether it gets displayed or not, depending on the result of `showIcon()`. To do so, I've tried to use Angular testing tools, resulting in the following code:

``` typescript
const iconElement: SVGElement | null =
    testComponentFixture.debugElement.query( By.css( '.button__icon' ) );
expect( iconElement ).not.toBeNull(); // Check that element exists
```

However, it turns out that the `iconElement` is always `null` - `By.css()` seems to not be able to find the SVG element, in this specific case by a given class name.

*Is there any reason why this isn't working, or is this behaviour intentional / by design?* The docs don't reveal any specifics regarding this case.

**What is the motivation / use case for changing the behavior?**
The `By.css()` query function should work consistently, with all kinds of HTML elements, without any workaround needed.

**Workaround**
As described [right here](http://stackoverflow.com/questions/39905388/component-unit-test-by-css-does-not-match-when-in-svg-namespace), using the following code instead works just fine:

``` typescript
const iconElement: SVGElement | null =
      testComponentFixture.debugElement.nativeElement.querySelector( '.button__icon' );
```

**Please tell us about your environment:** Angular CLI 1.0.0-RC.1, Visual Studio Code on a Windows 7 machine

* **Angular version:** 2.4.9 (latest at the moment)

* **Browser:** Karma & PhantomJS
 
* **Language:** TypeScript

**Comment by DzmitryShylovich** [comment]
Please add the plunk that illustrates the issue. thanks

**Comment by dominique-mueller** [comment]
Here you go with a stripped-down, very simplified Plunkr: https://plnkr.co/edit/40pejiIO2OUn1b9QHitl.

The template includes a button, which then includes an SVG element. As one can see, the button element can be found with `By.css( '.my-button' )` - this tests succeeds. The SVG element, however, does not show up when searching it with `By.css( '.my-svg' )` - thus, the tests fails.

**Comment by DzmitryShylovich** [comment]
@dominique-mueller thanks. Yeah, it's a valid bug.  `By.css()` doesn't work with `SVGElement`, only with `HTMLElement`

**Comment by wawyed** [comment]
Are you guys planning to do something about it? Bug been opened since March. Can we get an update?

Thanks.

**Comment by dominique-mueller** [comment]
I'm also wondering, PR https://github.com/angular/angular/pull/15372 by @DzmitryShylovich is still open ...

**Comment by gregjhogan** [comment]
I want this fixed, too, but in the meantime I have been working around it by using `debugElement.nativeElement.querySelector()`

```typescript
fixture = TestBed.createComponent(MyComponent);
component = fixture.componentInstance;
const textElement: HTMLElement = fixture.debugElement.nativeElement.querySelector('.myClass');
expect(textElement.textContent).toBe('hello world!');
```

**Comment by dominique-mueller** [comment]
Interesting - it seems this got fixed by https://github.com/angular/angular/commit/2f2d5f35bd086abeafceabdd5ff9430221b1917f, without anyone noticing. This change should be included with Angular 5+, and I can actually verify it's now working as expected (tested with Angular 5.2).

Feel free to re-open if the issue still exists.

**Comment by mjrcmrma** [comment]
Still an issue with Angular 5.2.1

**Comment by ksadralodabai** [comment]
Confirming here also, that it's an issue with Angular 5.0.0.

**Comment by collink** [comment]
Busted in 5.2.5 as well

Another workaround I've found is `debugElement.query(By.css('svg[class=className]'))`

**Comment by Justus-Maier** [comment]
Still not working in 5.2.9, please reopen the issue.

**Comment by dominique-mueller** [comment]
As it seems many people are still encountering this issue, I'm re-opening it. We should, however, create a new reproduction for this, e.g. a Plunkr or on StackBlitz.

**Comment by Justus-Maier** [comment]
Another workaround, since nothing else seemed to work for me:

```typescript
    const svg = fixture.nativeElement.firstChild; // adjusted template for svg to be the only child element
    // bars = fixture.debugElement.queryAll(By.css('rect[class=bar]')); // nothing
    // bars = fixture.debugElement.nativeElement.querySelector('rect.bar'); // empty
    bars = svg.getElementsByClassName('bar'); // finds bars!
```

**Comment by dominique-mueller** [comment]
I took the time to create a reproduction in StackBlitz, using the latest and greatest Angular 7: https://stackblitz.com/edit/angular-issue-15164?file=src%2Fapp%2Fexample.component.spec.ts

Result: All seems to work as expected.

Thus, I'm closing this issue again. Should anyone still experiencing issue, feel free to fork this StackBlitz / create a new StackBlitz to pre-produce the issue.

**Comment by hansmaad** [comment]
> Thus, I'm closing this issue again. Should anyone still experiencing issue, feel free to fork this StackBlitz / create a new StackBlitz to pre-produce the issue.

`debugElement.query` behaviour is still different from `nativeElement.querySelector` if the svg was added (by a 3rd party library for example), see:

https://stackblitz.com/edit/angular-issue-15164-1qhoqz?file=src/app/example.component.spec.ts

I have the same issue in Angular 8.0
