### ISSUE TITLE
patchValue and Getters and Setters

### ISSUE THREAD

**Issue by victorschinaider** [angular/angular#15163]
**I'm submitting a ...**  (check one with "x")

I suppose it is a... 

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Getters and Setters in a javascript object is not being passed through ``patchValue`` of a ``FormGroup``.

![image](https://cloud.githubusercontent.com/assets/16581931/23944351/53f183a8-0951-11e7-89ff-e7d695485d81.png)

**Expected behavior**
It should pass the correct value.

**Minimal reproduction of the problem with instructions**
Looks at Console:
http://plnkr.co/edit/1kWQiH

* **Angular version:** 2.0.X
lastest
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by DzmitryShylovich** [comment]
You need to make getters/setters enumerable otherwise there's no way for angular to know about their existence.

http://plnkr.co/edit/Zp51QhlcL0ocVzTpBbUI?p=preview

**Comment by victorschinaider** [comment]
Thanks.

**Comment by DzmitryShylovich** [comment]
For example you can use decorator https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators
Better to ask it typescript support channels

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlg-jbojcic** [comment]
@DzmitryShylovich when I try to do this with @enumerable, it seems that getter/setter is created on prototype instead of on object so it doesn't work with Object.keys which is used in patchValue
