### ISSUE TITLE
disabled FormControl is invalid

### ISSUE THREAD

**Issue by MeMeMax** [angular/angular#15172]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If I open a form and a formcontrol is disabled, it is invalid. So calling `anyForm.controls['anyField'].valid` returns false.
Calling `anyForm.valid` returns true which is expected behaviour.

**Expected behavior**
On opening a form a disabled formcontrol shouldn´t be invalid.

**What is the motivation / use case for changing the behavior?**
Since you don´t expect to be a disabled field invalid this should be changed.

**Please tell us about your environment:**
Using Angular CLI

* **Angular version:** 2.0.X
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.1
node: 6.9.4
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/compiler-cli: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/platform-server: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web 

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by DzmitryShylovich** [comment]
It's by design. See https://github.com/angular/angular/issues/11432#issuecomment-245670999

Please, search for a similar issues before submitting a new one. thanks
