### ISSUE TITLE
Using ng global does not work with import/require @angular/{core/common/etc.}

### ISSUE THREAD

**Issue by james-criscuolo** [angular/angular#15178]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Importing a Module which enters [this code](https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/core/src/reflection/reflection_capabilities.ts#L130) returns a DecoratorFactory that does not load  because it fails [this check](https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/compiler/src/ng_module_resolver.ts#L14). It leads to [this error](https://github.com/angular/angular/blob/322bf7a0d55afab5526c4bb3e4faeb5caf1c39a9/packages/compiler/src/metadata_resolver.ts#L434).

**Expected behavior**

I'd expect `decoratorFactory instanceof decoratorFactory` to return true and allow the module to load.

**Minimal reproduction of the problem with instructions**

I can attempt to get a working minimal demo later, if the problem is not clear enough.

**What is the motivation / use case for changing the behavior?**

It seems that NgModules that come through that function should be loadable just like other functions.

**Please tell us about your environment:**

Max OSX 10.12.3
NPM 3.10.9
node 6.9.2

* **Angular version:** 2.4.9

* **Browser:** Chrome 56

 
* **Language:** ES5

* **Node (for AoT issues):** `node --version` =   v6.9.2 (aot was not used)

**Comment by james-criscuolo** [comment]
While attempting to make a demo for this, I stumbled upon the real issue. I was using script tags to import angular, which allowed me to reference `ng` for all of my angular libraries (`ng.core.NgModule`, for example. The third party library I was using uses `var core = require (@angular/core);` (or matching `import` statement). `ng` reads from the bundle I included, while `require`ing/`import`ing reads from the individual files. So `NgModule's` constructor is defined in `decorators.js` for the `require`/`import`, and in the core bundle for the other, so `instanceof` returns false.

It seems the title is no longer relevant here, but is there some other clean way to address this? I know `ng` isn't the suggested way to use these libraries, but this bug makes it very scary to use, to the point of it being unusable.

**Comment by IgorMinar** [comment]
Hi there @james-criscuolo, I know that this issue is super old, but reading through it I can't really figure out what the issue was and how did you come across it. Can someone please help by providing a reproduction or confirming that this bug no longer exists? Thank you.

**Comment by james-criscuolo** [comment]
Hard to say if this would still be an issue for anyone, I believe I only hit it because I was attempting to make a hybrid app. My [comment](https://github.com/angular/angular/issues/15178#issuecomment-287102616) lays it out clearer than I can remember. I was using the global `ng` (importing angular via script tag) to make my ngModules at the time, but the newer way (via import) was being used by 3rd party dependencies, and the mismatch lead to an error. The whole situation lead to a broken app with no obvious clue as to why it was broken.

I was able to get around this by expanding the scope of my hybridization effort, and touching many more things to eliminate the use of `ng` (at least I think). I know the upgrade route has come a long way since Angular 2, so its very possible this isn't even relevant anymore. I'm on the latest angular at this point, so it isn't an issue for me, but I left the issue here in case others hit it.

**Comment by JoostK** [comment]
I am going to close this as obsolete, as the originally mentioned code no longer exists in any shape or form in latest Angular.
