### ISSUE TITLE
host element removals do not run through the same animation renderer as other animations

### ISSUE THREAD

**Issue by matsko** [angular/angular#15193]
If you have an animation like so:

```ts
@Component({
  animations: [
    trigger('animation', [
      transition(':leave', [...]) // this will not fire
    ])
  ]
})
class Cmp {
  @HostBinding('@animation')
  public animations = true;
}
```

Then when the host is issued to be from the DOM (through the renderer) it will not trigger a leave animation. This is because the parent renderer is used to remove the element.

**Comment by tbosch** [comment]
Let's close this one, and just track https://github.com/angular/angular/issues/14813
