### ISSUE TITLE
ngc's flatModuleOutFile does not emit metadata on windows

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#15192]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Compiling using `ngc` and with `flatModuleOutFile` does not produce a `*.metadata.json` file on Windows.

**Expected behavior**

 `*.metadata.json` file should be produced on all platforms.

**Minimal reproduction of the problem with instructions**

```
git clone https://github.com/filipesilva/ngc-flatmodule-windows
cd ngc-flatmodule-windows
npm run build
```

On a OSX machine, there will be a `out-tsc/index.metadata.json`. On Windows, this file will not be present.

**What is the motivation / use case for changing the behavior?**

`ngc` should work on Windows.

**Please tell us about your environment:**

Windows 10, VS Code, npm@4.0.5, node@7.4.0, typescript@2.2.1

* **Angular version:** 4.0.0-rc.3

* **Browser:** [ N/A ]

 
* **Language:** [ TypeScript 2.2 ]

* **Node (for AoT issues):** `node --version` =  7.4.0

**Comment by chuckjaz** [comment]
I reproduced the error and have a fix PR out to fix the Windows issue.

I also sent a PR for changes I would recommend to your library setup. The attached repository doesn't quite work as you are obscuring the `index.ts` in the source.
