### ISSUE TITLE
Cannot get input element value 

### ISSUE THREAD

**Issue by anivaisu** [angular/angular#15207]
Hi all,

  I am beginner in angular 2

  I develop web chat app using angular 2.Pls refer this http://imgur.com/dpnLSSv

  I need dont display repeated value.Because I will check two variable.

  below my html code

    <div class="messagesholder" *ngFor="let chat of chatval | orderby:'[date]'" >
       <div *ngIf="chat.sender == currentuser || chat.receiver == currentuser">
              <p style="font-size:9px;text-align: center;" id="amount" #amount>{{chat.date | amDateFormat:'LL'}}</p>
               <input #myname type="hidden" value={{chat.date}}>
               </div>
       <div class="message" *ngIf="chat.sender == currentuser || chat.receiver == currentuser" [ngClass]="{'me': currentuser == chat.sender}">
              <div class='image' *ngIf="chat.path" >
                <img *ngIf="chat.path" [src]="chat.path"/><br>
                <span *ngIf="chat.path_text">{{chat.path_text}}</span>
                <span style="font-size:9px;">{{chat.date | amDateFormat:'hh:mmA'}}</span>
              </div> 
               <div *ngIf="chat.message_text">
               <span>{{chat.message_text}}</span>
               <span style="font-size:9px;">{{chat.date | amDateFormat:'hh:mmA'}}</span>
               </div>
        </div>
</div>

    So i Bind the chat.date value using input tag.i get input element value using id.below my typescript file

   import { Component,Inject,ViewChild,ElementRef,AfterViewInit} from '@angular/core';

   export class ChatPage implements AfterViewInit {
     @ViewChild('myname') input:ElementRef; 
     constructor(public modalCtrl: ModalController,public navCtrl: NavController) {}
      ngAfterViewInit() {
       console.log(this.input.nativeElement.value);
      }
   }

   i am getting this error

  Cannot read property 'nativeElement' of undefined

   How to fix this issue.or any other way to find slutions.I need same values are does not show.

  .I tried to many way.I have no idea.
   
   Kindly Advice me,
   Thanks & Regards.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by anivaisu** [comment]
any other way to fin slutions i need does not repeated same data....

**Comment by DzmitryShylovich** [comment]
Please reproduce in plunkr
You can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point

**Comment by anivaisu** [comment]
Pls refer this http://plnkr.co/edit/FrRLDas75MU447BOmk0s?p=preview

**Comment by DzmitryShylovich** [comment]
@anivaisu we need a small working example, not just copy pasted code with 3rd party libs

**Comment by kara** [comment]
This seems like a support request rather than an Angular issue.  @anivaisu You might try our gitter chatroom or the Ionic gitter to see if anyone has insight with inputs + Ionic components.
