### ISSUE TITLE
transition from angular 2 to angular 4 what's new what is backward incompatible ?

### ISSUE THREAD

**Issue by amineparis** [angular/angular#15201]
I can't find any ressources talking about what's new in angular 4 and what are the backward compatibilities to consider when migrating my angular 2 projects ?

**Comment by pkozlowski-opensource** [comment]
All the details are in https://github.com/angular/angular/blob/master/CHANGELOG.md. There will be more guides when 4.x gets final.

**Comment by amineparis** [comment]
is breaking changes another name for backward incompatibilities ?
