### ISSUE TITLE
aio: /content/**/*.json HTTP  requests occasionally rewritten to index.html

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#15200]
When browsing through the site and clicking on various items in the left side-nav, the navigation works well for a few menu item clicks, but eventually stops working.

When I open the console I see that some (I don't know which and why) http requests for our json files are being incorrectly rewritten to index.html by firebase. This results in JSON.parse errors from @angular/http (since it can't parse the html file).

Steps to repro:
1. go to https://aio-staging.firebaseapp.com
2. in the side-nav select "core >" for that menu item to unroll
3. select sub-item "directives >"
4. check console

Screenshot attached:

<img width="626" alt="screen shot 2017-03-15 at 11 05 13 pm" src="https://cloud.githubusercontent.com/assets/216296/23983992/59a73350-09d4-11e7-99f9-3c2550a74ecd.png">

**Comment by petebacondarwin** [comment]
This has been fixed.
