### ISSUE TITLE
Re-enable test/test_summaries.js to make sure we don't break it moving forward

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#15219]
We disabled test_summaries run in offline_compiler_test.sh temporarily. Need to move metadata for secondary entry points up one level and get rid of `alias: ...` stuff.

**Comment by ocombe** [comment]
Should we re-enable the test now? I think that the alias stuff was removed?

**Comment by tbosch** [comment]
This is not needed anymore for master, as `test_summaries` uses the old compiler api, and we have good tests for summaries in @angular/compiler-cli as well as via tests for bazel.

**Comment by ocombe** [comment]
Ok, we can close this then?
