### ISSUE TITLE
Error: Expression has changed after it was checked. Inside of nested ControlValueAccessor

### ISSUE THREAD

**Issue by vovikdrg** [angular/angular#15217]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 
[ ] feature request
[ ] support request
```
I am using ControlValueAccessor inside of other ControlValueAccessor both of them are self validating.

If inControlValueAccessor at ngOnChanges I propagate new value which triggers child component validation and validation status is change I am getting Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.

**Expected behavior**
To avoid error i need to do workarounds such as debounceTime(1) or 

const resolvedPromise = Promise.resolve(null);
 resolvedPromise.then(() => {
      this.propagateChange(this.registerForm.value);
    });

But in real world application when many components could have other components it could be hard to find out where is actuall problem

**Minimal reproduction of the problem with instructions**
1. Go to https://plnkr.co/edit/ZmYBiH6kciXqQXp2f3KU?p=preview 
2. Open console.
3. Change value of input to number

**What is the motivation / use case for changing the behavior?**
Its not intuitive to delay propagate changes in next tick.

**Please tell us about your environment:**

* **Angular version:** 2.4.9

* **Browser:** all
 
* **Language:** [TypeScript 2.0]

* **Node (for AoT issues):** `node --version` =   v6.9.5

**Comment by DzmitryShylovich** [comment]
So what is a bug here? Data flows one way in angular and yes to avoid an error you need to trigger the next  CD cycle using promise, setTimeout etc.

**Comment by vovikdrg** [comment]
@DzmitryShylovich set timeouts sounds like a workaround to the problem. On the other hand at least some notes should be in documentation about that. Because reading this docs https://angular.io/docs/ts/latest/api/core/index/OnChanges-class.html its not telling me that i must do updates in next tick.

**Comment by DzmitryShylovich** [comment]
This error is not specific to `OnChanges`. See http://stackoverflow.com/a/34364881

**Comment by vovikdrg** [comment]
@DzmitryShylovich  but then it means that instead of propagateChange function shouldn't be a Subject?

**Comment by vovikdrg** [comment]
I come out with workaroud/solution, but still I'd like angular to do so. 
Since problem is that propageChange is triggering for re validation now I need to wrap onChange propagation 

```
 public registerOnChange(fn) {
    this.propagateChange = (value) => { Promise.resolve(null).then(() => fn(value)) };
  }
```

But i would expect angular to do so

**Comment by MohsenBzm** [comment]
Neither the `promise` at `registerOnChange`  works for me. The `ngOnChanges` is would work only at the first change!

**Comment by mhevery** [comment]
This works as intended since it is telling you that the data flow is incorrect.
