### ISSUE TITLE
Cannot update value if using uppercase chars in local variant

### ISSUE THREAD

**Issue by shaunxu** [angular/angular#1521]
Assuming I have an input field with local vairant `<input #lowercase type="textBox" (keyup)>`. Then a follow element shows the local variant `<pre>{{lowercase.value}}</pre>`.
If the local variant are all lowercase it works, but doesn't work when contains uppercase chars. For example: `<input #UpperCase type="textBox" (keyup)><pre>{{UpperCase.value}}</pre>`.

Plunker: http://plnkr.co/edit/iZuBHwTFhMo9CDUH6l5M?p=preview
You can rename the variant `upperCase` to `uppercase` then it works.

**Comment by alexpods** [comment]
This is because HTML is case insensitive. So your `UpperCase` variable will turn into `uppercase` when will be handled by browsers. Use dash-case to define upper case variable:

```js
<input #upper-case type="textBox" (keyup)><pre>{{upperCase.value}}</pre>.
```

See [answers to this issue](https://github.com/angular/angular/issues/1447) for more information.

**Comment by pkozlowski-opensource** [comment]
Thnx @alexpods for helping out with the issues, your answer is spot on!

**Comment by shaunxu** [comment]
Thanks @alexpods for the clarification.
