### ISSUE TITLE
SystemJS >0.22 does not work with Angular UMD modules.

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#15211]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When doing all these:
- using SystemJS@^0.22, 
- compiling Typescript with `"module": "system"`
- using Angular UMD bundles, 

Named exports of Angular packages cannot be loaded, showing errors like `Error: core_1.Component is not a function`.

This is because SystemJS has dropped named exports support from CommonJS modules:
http://guybedford.com/systemjs-alignment#node-modules-compatibility

Using `__esModule` re-enables the named exports.

**Expected behavior**

There should be no errors loading modules.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/brjn0Hjh91GrfTMcVIb7?p=preview
The following error will be shown:
```
Error: core_1.Component is not a function
  Evaluating http://run.plnkr.co/32CYZkBfmPuzTqHB/src/app.ts
  // ...
```

**What is the motivation / use case for changing the behavior?**

Being able to use Angular UMDs with the current SystemJS versions.

**Please tell us about your environment:**

Windows 10, VS Code, npm, plunker

* **Angular version:** 2.4.9

* **Browser:** [all ]

 
* **Language:** [ TypeScript 2.0 ]

* **Node (for AoT issues):** `node --version` =

**Comment by jasonaden** [comment]
Resolved with #14196
