### ISSUE TITLE
PATTERN_ALIASES combine during bootstrap fails in Internet Explorer 11

### ISSUE THREAD

**Issue by bohoffi** [angular/angular#15228]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 
```

**Current behavior**
When bootstrapping the application using @angular@4.0.0-rc.3 it fails calling the "combine" function in the PATTERN_ALIASES literal using Internet Explorer 11.

**Expected behavior**
Application should complete bootstrapping without any errors running in IE

**Minimal reproduction of the problem with instructions**
The problem appears running the following repo [angular-audio-footprint](https://github.com/bohoffi/angular-audio-footprint).

**Please tell us about your environment:**
OS: Windows 8.1 x64
IDE: Visual Studio Code v1.10.2
Package Manager: npm

* **Angular version:**
4.0.0-rc.3

* **Browser:**
[IE 11]
 
* **Language:**
[TypeScript 2.1.0]

**Comment by DzmitryShylovich** [comment]
Please reproduce in plunker. You can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point

**Comment by bohoffi** [comment]
I'm really sorry but I can't reproduce the error using plunker (even used the exact same package versions).
BUT I was able to reproduce the error using a freshly generated project using:
```
ng new ng-test --ng4
```

**Comment by DzmitryShylovich** [comment]
@bohoffi do you use date pipe in your project (didn't find it in your sample repo)? 

Can't reproduce it neither in plunkr nor in a custom webpack build. Looks like a CLI issue. I think you should re-open this on https://github.com/angular/angular-cli/issues

**Comment by bohoffi** [comment]
@DzmitryShylovich No I did not use the date pipe.

I will re-open this issue in the cli project.

Thank you. I think that this can be closed.
