### ISSUE TITLE
bug(animations): `false` (0) state is being confused as `"void"` in transitions in 4.0.0-rc.4

### ISSUE THREAD

**Issue by emoralesb05** [angular/angular#15223]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The `*` auto-style wildcard stopped working when upgrading the @angular@4.0.0-rc.3 and the element keeps the `opacity` at `0` and `display` at `none` even after animating. (also the returning transition is not working)

e.g.
```
trigger('fade', [
    state('false', style({
      opacity: '0',
      display: 'none',
    })),
    state('true',  style({
      opacity: '*',
      display: '*',
    })),
    transition('0 => 1', animate('200ms ease-in')),
    transition('1 => 0', animate('200ms ease-out')),
  ])
```

**Expected behavior**
It was working in `2.X.X` without any issues. Should set `opacity` to `0` and `display` to `none` when `trigger` is `false` and should set `opacity` and `display` to whatever it was when `trigger` is `true` while animating between `opacity`.

**Minimal reproduction of the problem with instructions**
Plnkr with issue: https://plnkr.co/edit/IGvg3RIcdVtfhOV9M0sI?p=preview

**What is the motivation / use case for changing the behavior?**
Working animations are broken now.

* **Angular version:** 4.0.0-rc.3

* **Browser:** all

**Comment by emoralesb05** [comment]
After digging around more, i notice that its confusing `false` with `void` in the transitions.

![screen shot 2017-03-16 at 7 08 07 pm](https://cloud.githubusercontent.com/assets/5846742/24026094/0072acda-0a7c-11e7-9cef-3ff9d5d9009d.png)

Notice the transitions are going from `true` to `false` and then `void` to `true` 🤔

**Comment by emoralesb05** [comment]
Renamed the issue since the `*` works fine, the problem is the confusion between `false` and `"void"`

**Comment by matsko** [comment]
This will be fixed tomorrow.

**Comment by emoralesb05** [comment]
Pulled `rc.4` and still has the same error. 😞

**Comment by matsko** [comment]
This is now waiting to go in: https://github.com/angular/angular/pull/15245

**Comment by emoralesb05** [comment]
Awesome @matsko. looking forward for 4.0.0 😄

**Comment by matsko** [comment]
Just you wait until 4.1.0-beta and you'll get some crazy new stuff ;)

**Comment by emoralesb05** [comment]
Oh snap! extra excited 💥 haha
