### ISSUE TITLE
2.0.0-alpha.20 fails in Firefox 37.0.2 (ES5)

### ISSUE THREAD

**Issue by s-trooper** [angular/angular#1522]
I tried to use https://code.angularjs.org/2.0.0-alpha.20/angular2.sfx.dev.js but it violate strict mode and FF don't run it. 

Error:
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function - angular2.sfx.dev.js:5609:17

**Comment by pkozlowski-opensource** [comment]
This err is thrown from RxJS but at the end of a day it is a combination of RxJS and zone.js that makes the problem appear: concatenating zone.js adds strict mode to the entire file and this upsets RxJs.

IMO we should fix it in zone.js by moving strict mode declaration to the self-executing function.

**Comment by hourliert** [comment]
Same issue in PhantomJS2. This fix solves the problem.

**Comment by vicb** [comment]
zone.js 0.4.4 has been release earlier today

**Comment by vicb** [comment]
closed via #1751
