### ISSUE TITLE
ERROR in BrowserAnimationsModule is not an NgModule

### ISSUE THREAD

**Issue by vdclouis** [angular/angular#15229]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
updated to rc4
using latest angular-cli
when running Karma: `ERROR in BrowserAnimationsModule is not an NgModule`

**Expected behavior**
Karma should run

**Minimal reproduction of the problem with instructions**
set up an angular cli project
use angular rc4
run tests

**What is the motivation / use case for changing the behavior?**
broken

**Please tell us about your environment:**
macOS, vscode, npm

* **Angular version:** 4 rc4

* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =  7

**Comment by DzmitryShylovich** [comment]
Please add reproduction

**Comment by bboehm86** [comment]
@vdclouis I ran into the same issue when I updated to rc4. Removing `node_modules` and run a clean install fix that

**Comment by vdclouis** [comment]
did the trick @bboehm86 thanks!
