### ISSUE TITLE
Upgrading from  2.4.6 to 4.0.0-rc.3: lost my Rx operators

### ISSUE THREAD

**Issue by masonk** [angular/angular#15220]
This happen when upgrading to the latest rc. It is the _only_ change I made to go from working to not working.

```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

EventEmitter does not have extra Rx operators, even though those operators are being required in my app's entry points.

```
import * as rxjs from "rxjs";
import "rxjs/Rx";
import { enableProdMode, ViewEncapsulation, EventEmitter } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';

console.log(new rxjs.Subject().debounce); // function debounce(durationSelector) { ...
console.log(new EventEmitter().debounce); // undefined
```

**Please tell us about your environment:**
Windows 10.
browserify

* **Angular version:** 4.0.0-rc.3

* **Browser:** all
 
* **Language:** TypeScript 2.1.6\
package.json
```
{
  "name": "nganalytics",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "clean": "gulp clean:all",
    "build": "gulp build",
    "test": "gulp unit",
    "styles": "gulp styles"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-preset-es2015": "6.3.13",
    "babelify": "7.3.0",
    "browser-sync": "2.13.0",
    "browserify": "13.0.0",
    "browserify-istanbul": "0.2.1",
    "browserify-shim": "3.8.11",
    "connect-livereload": "0.4.0",
    "del": "2.2.0",
    "esdoc": "0.4.7",
    "express": "4.1.1",
    "gulp": "3.9.1",
    "gulp-autoprefixer": "0.0.7",
    "gulp-clean": "0.3.1",
    "gulp-if": "2.0.0",
    "gulp-jshint": "1.5.5",
    "gulp-less": "3.0.5",
    "gulp-livereload": "2.1.0",
    "gulp-rev": "7.0.0",
    "gulp-rev-replace": "0.4.3",
    "gulp-tslint": "6.0.2",
    "gulp-uglify": "1.5.1",
    "gulp-util": "2.2.14",
    "isparta": "4.0.0",
    "jasmine-core": "2.5.2",
    "karma": "1.3.0",
    "karma-browserify": "5.1.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-coverage": "0.5.3",
    "karma-spec-reporter": "0.0.30",
    "karma-firefox-launcher": "1.0.0",
    "karma-ie-launcher": "0.2.0",
    "karma-jasmine": "1.0.2",
    "require-dir": "0.3.0",
    "run-sequence": "1.1.5",
    "superagent-mocker": "0.3.0",
    "tsify": "1.0.7",
    "tslint": "3.15.1",
    "typescript": "2.1.4",
    "vinyl-buffer": "1.0.0",
    "vinyl-paths": "2.1.0",
    "vinyl-source-stream": "1.1.0"
  },
  "dependencies": {
    "@angular/common": "4.0.0-rc.3",
    "@angular/compiler": "4.0.0-rc.3",
    "@angular/core": "4.0.0-rc.3",
    "@angular/forms": "4.0.0-rc.3",
    "@angular/http": "4.0.0-rc.3",
    "@angular/platform-browser": "4.0.0-rc.3",
    "@angular/platform-browser-dynamic": "4.0.0-rc.3",
    "@angular/router": "4.0.0-rc.3",
    "angular-2-data-table": "0.1.2",
    "bootstrap": "3.3.7",
    "d3": "3.5.17",
    "gulp-util": "2.2.20",
    "jquery": "3.1.1",
    "jquery-datetimepicker": "2.5.4",
    "lodash": "4.17.2",
    "moment": "2.17.1",
    "ng2-dragula": "1.3.0",
    "ng2-inline-svg": "1.2.0",
    "ng2-translate": "3.1.3",
    "nvd3": "1.8.5",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.1",
    "typings": "2.0.0",
    "watchify": "3.9.0",
    "yargs": "6.6.0",
    "zone.js": "0.7.2"
  }
}
```

**Comment by sod** [comment]
Try changing
```typescript
import * as rxjs from "rxjs";
import "rxjs/Rx";
```

into
```typescript
import * as rxjs from "rxjs/Rx";
```

In my plunkr it works:
https://plnkr.co/edit/yMptOruLPOKGuv6OeQzC?p=preview (see app/app.component.ts & browser console)

**Comment by masonk** [comment]
if `import "rxjs"` appears anywhere, before or after `import "rxjs/Rx"`, EventEmitter won't have the extra operators.

For example,
```
import "rxjs"
import * as rxjs from "rxjs/Rx"
```
breaks your plunkr. 

so does 

```
import * as rxjs from "rxjs/Rx"
import "rxjs"
```

This was strongly suggestive of the problem I'm having and lead to fixing it: I configured browserify to resolve `"rxjs"` to `"rxjs/Rx"`. _Should_ it matter which one gets imported first? Is this an Rx issue, an Angular issue, or an issue with my build configuration? I don't really know. But thank you much for your suggestion.

**Comment by sod** [comment]
When you `import "rxjs"`, you import then [index.js](https://github.com/ReactiveX/rxjs/blob/master/index.js) that returns the commonjs bundle.
When you `import "rxjs/Rx"` you import the Rx.js file compiled from [Rx.ts](https://github.com/ReactiveX/rxjs/blob/master/src/Rx.ts).

Just don't import bundle and source files in a single project. Decide for one of both.

**Comment by mateenQureshi** [comment]
Hello Guys,
I am facing the same issue, i have import of "import {Observable} from 'rxjs/Rx'", when upgraded my project from angular 2.4 to angular 4.1, eveything works fine, but my systemjs builder is not able to build my project throwing the following error: Error on fetch 'rxjs/add/observable/dom/ajax.js'..
Any help would be appreciated.
Thank You!

**Comment by kylecordes** [comment]
If you import RxJS in the way shows in the tutorial:

https://angular.io/docs/ts/latest/tutorial/toh-pt6.html

... instead of the import examples in this issue thread, all of these problems are fixed.

**Comment by mateenQureshi** [comment]
First of all, thank you for the response.. 
Secondly, i would like to share my systemjs.config and gulp.js file, please help me by suggesting the best way as i m new to angular

Systemjs.config.js

/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'lib/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
            '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
            "@ng2-dynamic-forms/core": "npm:@ng2-dynamic-forms/core/bundles/core.umd.js",
            "@ng2-dynamic-forms/ui-bootstrap": "npm:@ng2-dynamic-forms/ui-bootstrap/bundles/ui-bootstrap.umd.js",
            'ng2-bootstrap': 'npm:ng2-bootstrap/bundles/ngx-bootstrap.umd.min.js',
            'ng2-date-time-picker': 'npm:ng2-date-time-picker',

            'angular2-fullcalendar/src/calendar/calendar': 'npm:angular2-fullcalendar/src/calendar/calendar.js',
            'jquery': 'npm:jquery/dist/jquery.min.js',
            'fullcalendar': 'npm:fullcalendar/dist/fullcalendar.js',
            'moment': 'npm:moment',

            // other libraries
            'rxjs': 'npm:rxjs',
            'videogular2': 'npm:videogular2',
            'socket.io-client': 'npm:socket.io-client/dist/socket.io.js',
            'ng2-pagination': 'npm:ng2-pagination',
            'text-mask-core': 'npm:text-mask-core',
            'angular2-text-mask': 'npm:angular2-text-mask/dist/angular2TextMask.js',
            'ng2-progressbar': 'npm:ng2-progressbar/bundles/ng2-progressbar.umd.js',
            'ng2-notify-popup': 'npm:ng2-notify-popup'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            },
            videogular2: {
                defaultExtension: 'js'
            },
            'ng2-pagination': {
                main: './index.js',
                defaultExtension: 'js'
            },
            'text-mask-core': {
                defaultExtension: 'js'
            },
            'angular2-text-mask': {
                defaultExtension: 'js'
            },
            'ng2-date-time-picker': {
                main: './index.js',
                defaultExtension: 'js'
            },
            'moment': {
                main: './moment.js',
                defaultExtension: 'js'
            },
            'ng2-notify-popup': {
                main: './index.js',
                defaultExtension: 'js'
            }
        }
    });
})(this);



Gulp.js

const del = require('del');
const gulp = require('gulp');
const cleanCSS = require('gulp-clean-css');
const concat = require('gulp-concat');
const runSequence = require('run-sequence');
const sourcemaps = require('gulp-sourcemaps');
const sysBuilder = require('systemjs-builder');
const uglify = require('gulp-uglify');
const tsc = require('gulp-typescript');
const htmlreplace = require('gulp-html-replace');
const tslint = require('gulp-tslint');

const tscConfig = require('./tsconfig.json');

// Clean app prod
gulp.task('clean:app', function () {
    return del(['public/**/*']);
});

gulp.task('compile:ts', function () {
    return gulp
        .src('app/**/*.ts')
        .pipe(sourcemaps.init())
        .pipe(tsc(tscConfig.compilerOptions))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('public/app'));
});

gulp.task('lint:ts', function () {
    return gulp
        .src('app/**/*.ts')
        .pipe(tslint({
            formatter: "verbose"
        }))
        .pipe(tslint.report());
});

// Generate systemjs-based builds
gulp.task('bundle:js', function () {
    var builder = new sysBuilder('public', './systemjs.config.js');
    return builder.bundle('app', 'public/app/app.min.js')
        .then(function () {
            console.log('Build Complete');
            return del(['public/app/**/*', '!public/app/app.min.js']);
        })
        .catch(function (err) {
            console.error('>>> [systemjs-builder] Bundling failed'.bold.green, err);
        });
});

// Copy dependencies
gulp.task('copy:prod:libs', function () {
    gulp.src(['node_modules/rxjs/**/*'])
        .pipe(gulp.dest('public/lib/rxjs'));

    gulp.src(['node_modules/moment/**/*'])
        .pipe(gulp.dest('public/lib/moment'));

    gulp.src(['node_modules/ng2-bootstrap/**/*'])
        .pipe(gulp.dest('public/lib/ng2-bootstrap'));

    gulp.src(['node_modules/jquery/**/*'])
        .pipe(gulp.dest('public/lib/jquery'));

    gulp.src(['node_modules/fullcalendar/**/*'])
        .pipe(gulp.dest('public/lib/fullcalendar'));

    gulp.src(['node_modules/angular2-fullcalendar/**/*'])
        .pipe(gulp.dest('public/lib/angular2-fullcalendar'));

    gulp.src(['node_modules/videogular2/**/*'])
        .pipe(gulp.dest('public/lib/videogular2'));

    gulp.src(['node_modules/socket.io-client/**/*'])
        .pipe(gulp.dest('public/lib/socket.io-client'));

    gulp.src(['node_modules/ng2-pagination/**/*'])
        .pipe(gulp.dest('public/lib/ng2-pagination'));

    gulp.src(['node_modules/text-mask-core/**/*'])
        .pipe(gulp.dest('public/lib/text-mask-core'));

    gulp.src(['node_modules/angular2-text-mask/**/*'])
        .pipe(gulp.dest('public/lib/angular2-text-mask'));

    gulp.src(['node_modules/ng2-progressbar/**/*'])
        .pipe(gulp.dest('public/lib/ng2-progressbar'));

    gulp.src(['node_modules/ng2-date-time-picker/**/*'])
        .pipe(gulp.dest('public/lib/ng2-date-time-picker'));

    gulp.src(['node_modules/traceur/**/*'])
        .pipe(gulp.dest('public/lib/traceur'));

    gulp.src(['node_modules/ng2-notify-popup/**/*'])
        .pipe(gulp.dest('public/lib/ng2-notify-popup'));

    // concatenate non-angular2 libs, shims & systemjs-config
    gulp.src([
        'script/jquery.js',
        'script/bootstrap.min.js',
        'node_modules/moment/moment.js',
        'node_modules/moment-timezone/builds/moment-timezone-with-data-2012-2022.min.js',
        'node_modules/core-js/client/shim.min.js',
        'node_modules/zone.js/dist/zone.js',
        'node_modules/systemjs/dist/system.src.js',
        'systemjs.config.js'
    ])
        .pipe(concat('vendors.min.js'))
        .pipe(uglify())
        .pipe(gulp.dest('public/lib/'));

    return gulp.src(['node_modules/@angular/**/*'])
        .pipe(gulp.dest('public/lib/@angular'));
});

// Copy dev dependencies
gulp.task('copy:dev:libs', function () {
    gulp.src(['node_modules/rxjs/**/*'])
        .pipe(gulp.dest('public/lib/rxjs'));

    gulp.src(['node_modules/moment/**/*'])
        .pipe(gulp.dest('public/lib/moment'));

    gulp.src(['node_modules/ng2-bootstrap/**/*'])
        .pipe(gulp.dest('public/lib/ng2-bootstrap'));

    gulp.src(['node_modules/jquery/**/*'])
        .pipe(gulp.dest('public/lib/jquery'));

    gulp.src(['node_modules/fullcalendar/**/*'])
        .pipe(gulp.dest('public/lib/fullcalendar'));

    gulp.src(['node_modules/angular2-fullcalendar/**/*'])
        .pipe(gulp.dest('public/lib/angular2-fullcalendar'));

    gulp.src(['node_modules/videogular2/**/*'])
        .pipe(gulp.dest('public/lib/videogular2'));

    gulp.src(['node_modules/socket.io-client/**/*'])
        .pipe(gulp.dest('public/lib/socket.io-client'));

    gulp.src(['node_modules/ng2-pagination/**/*'])
        .pipe(gulp.dest('public/lib/ng2-pagination'));

    gulp.src(['node_modules/text-mask-core/**/*'])
        .pipe(gulp.dest('public/lib/text-mask-core'));

    gulp.src(['node_modules/angular2-text-mask/**/*'])
        .pipe(gulp.dest('public/lib/angular2-text-mask'));

    gulp.src(['node_modules/ng2-progressbar/**/*'])
        .pipe(gulp.dest('public/lib/ng2-progressbar'));

    gulp.src(['node_modules/lodash/**/*'])
        .pipe(gulp.dest('public/lib/lodash'));

    gulp.src(['node_modules/ng2-date-time-picker/**/*'])
        .pipe(gulp.dest('public/lib/ng2-date-time-picker'));

    gulp.src(['node_modules/traceur/**/*'])
        .pipe(gulp.dest('public/lib/traceur'));

    gulp.src(['node_modules/ng2-notify-popup/**/*'])
        .pipe(gulp.dest('public/lib/ng2-notify-popup'));

    return gulp.src(['node_modules/@angular/**/*'])
        .pipe(gulp.dest('public/lib/@angular'));
});

// copy core files for dev env
gulp.task('copy:dev:dependencies', function () {
    gulp.src(['node_modules/moment/moment.js'])
        .pipe(gulp.dest('public/script'));

    gulp.src(['node_modules/moment-timezone/builds/moment-timezone-with-data-2012-2022.min.js'])
        .pipe(gulp.dest('public/script'));

    gulp.src(['node_modules/zone.js/dist/zone.js'])
        .pipe(gulp.dest('public/script'));

    gulp.src(['node_modules/systemjs/dist/system.src.js'])
        .pipe(gulp.dest('public/script'));

    gulp.src(['node_modules/core-js/client/shim.min.js'])
        .pipe(gulp.dest('public/script'));
    
    gulp.src(['node_modules/core-js/client/shim.min.js.map'])
        .pipe(gulp.dest('public/script'));

    return gulp.src(['systemjs.config.js'])
        .pipe(gulp.dest('public'));
});

gulp.task('prod:index', function () {
    gulp.src('index.html')
        .pipe(htmlreplace({
            'css': 'styles.min.css',
            'js-vendors': 'lib/vendors.min.js',
            'js-app': 'app/app.min.js'
        }))
        .pipe(gulp.dest('public/'));

});

gulp.task('dev:index', function () {
    gulp.src('index.html')
        .pipe(htmlreplace({
            // 'css': [
            //     'styles/font-awesome.min.css', 'styles/theme.css', 'styles/primeng.min.css',
            //     'styles/fullcalendar.css', 'styles/videogular.css', 'styles/main.css',
            //     'styles/bootstrap.min.css', 'styles/animate.css', 'styles/main.css',
            //     'styles/style-responsive.css', 'styles/svg-style.css', 'styles/style.css'
            // ],
            'css': 'styles.css',
            'js-vendors': [
                'script/jquery.js',
                'script/bootstrap.min.js',
                'script/moment.js',
                'script/moment-timezone-with-data-2012-2022.min.js',
                'script/shim.min.js',
                'script/zone.js',
                'script/system.src.js',
                'systemjs.config.js'
            ]
        }))
        .pipe(gulp.dest('public/'));
});

gulp.task('copy:static:dev', function () {

    gulp.src('fonts/*')
        .pipe(gulp.dest('public/fonts'));

    gulp.src('images/*')
        .pipe(gulp.dest('public/images'));

    gulp
        .src('styles/*.css')
        .pipe(concat('styles.css'))
        .pipe(cleanCSS())
        .pipe(gulp.dest('public/'));

    gulp.src('script/*')
        .pipe(gulp.dest('public/script'));

    return gulp
        .src('app/**/*.html')
        .pipe(gulp.dest('public/app'));
});

gulp.task('copy:static:prod', function () {

    gulp.src('fonts/*')
        .pipe(gulp.dest('public/fonts'));

    gulp
        .src('styles/*.css')
        .pipe(concat('styles.min.css'))
        .pipe(cleanCSS())
        .pipe(gulp.dest('public/'));

    gulp.src('images/*')
        .pipe(gulp.dest('public/images'));

    return gulp
        .src('app/**/*.html')
        .pipe(gulp.dest('public/app'));
});

gulp.task('clean', ['clean:app']);

gulp.task('build', function (callback) {
    runSequence('clean:app', 'copy:prod:libs', 'lint:ts', 'compile:ts', 'bundle:js', 'copy:static:prod', 'prod:index', callback);
});

gulp.task('dev', function (callback) {
    runSequence('clean:app','copy:dev:libs','copy:dev:dependencies','lint:ts','compile:ts','copy:static:dev', 'dev:index', callback);
    // runSequence('copy:dev:dependencies', 'lint:ts', 'compile:ts', 'copy:static:dev', 'dev:index', callback);
});

gulp.task('default', function (callback) {
    runSequence('dev', callback);
});

**Comment by mateenQureshi** [comment]
Also, the rxjs file missing error comes when i include ng2-notify-popup in my project..
Thank You!
