### ISSUE TITLE
[4.0.0-rc4] Cannot resolve module '@angular/animations/browser'

### ISSUE THREAD

**Issue by smitpsanghavi** [angular/angular#15231]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using webpack to build my Angular project. I was using 4.0.0-rc3 and was getting error regarding change detection which rc4 supposedly fixed. After upgrading to rc4, the build is now failing. The error during webpack build is

`ERROR in ./~/@angular/platform-browser/bundles/platform-browser-animations.umd.js
Module not found: Error: Cannot resolve module '@angular/animations/browser' in D:\Workspace\project\node_modules\@angular\platform-browser\bundles
 @ ./~/@angular/platform-browser/bundles/platform-browser-animations.umd.js 7:148-186`

Seems like #15114 i still not fixed somehow.

**Expected behavior**
Build passes without any error

**Minimal reproduction of the problem with instructions**
I cannot give steps to reproduce the problem as I don't know how to. Probably the error is self-explanatory. If needed, then I can try to reproduce it somehow.

**What is the motivation / use case for changing the behavior?**
Upgrading to latest version

**Please tell us about your environment:**
Windows 10, VS 2015 Update 3

* **Angular version:** 2.0.X
4.0.0-rc4

* **Browser:**
Happens during build process so browser selection is not relevant.
 
* **Language:** [TypeScript 2.2.1]
ES5

* **Node (for AoT issues):**
`node --version` =   v7.2.0

**Comment by uparlange** [comment]
You need to add 2 more imports 

<script src="node_modules/@angular/animations/bundles/animations.umd.min.js"></script>
<script src="node_modules/@angular/animations/bundles/animations-browser.umd.min.js"></script>
<script src="node_modules/@angular/platform-browser/bundles/platform-browser.umd.min.js"></script>
<script src="node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.min.js"></script>

**Comment by smitpsanghavi** [comment]
I added `import '@angular/animations';` to my `vendor.ts` file and everything is working now.
Upgrading to 4.0.0-rc4 introduced the _@angular/animations_ package which I had not imported in my `vendor.ts`

**Comment by FunCracker** [comment]
Faced Build Error:
ERROR in ./~/@angular/platform-browser/bundles/platform-browser-animations.umd.js
Module not found: Error: Cannot resolve module '@angular/animations/browser' in D:\project_code\repository\perforce\PACKAGES\apps\MultiLaneStorage\DEV\Verifier\Web\node_m
odules\@angular\platform-browser\bundles
 @ ./~/@angular/platform-browser/bundles/platform-browser-animations.umd.js 7:148-186

ERROR in [at-loader] ./src/components/app/app.component.ts:26:28
    TS2339: Property 'url' does not exist on type 'Event'.
  Property 'url' does not exist on type 'RouteConfigLoadStart'.
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 2.73 kB
webpack: Failed to compile.

**Comment by nni123** [comment]
Also make sure you run the following while upgrading from angular 2.4.x 

npm install @angular/animations@latest --save

Source link:

http://angularjs.blogspot.com/2017/03/angular-400-now-available.html

**Comment by MickL** [comment]
@nni123 thanks alot! Solution:

1. npm install @angular/animations --save
2. In app.module.ts add BrowserAnimationsModule to imports
