### ISSUE TITLE
Migrating to ng4 latest rc3 giving issue in aot build 

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#15230]
At the time of application starting getting the following error as soon as i migrated to rc3 from rc2(Angular4)

Uncaught TypeError: appInits[i] is not a function

Please comment!

**Comment by DzmitryShylovich** [comment]
do you use `APP_ANITIALIZER`?

**Comment by vasuneet** [comment]
No. But i don't have idea if generated code may have. This is present in build.js file when we compiled in aot way.

**Comment by DzmitryShylovich** [comment]
Add a breakpoint to `ApplicationInitStatus` constructor and see what you get

**Comment by ericmartinezr** [comment]
```
<!--
IF YOU DON'T FILL OUT THE FOLLOWING INFORMATION WE MIGHT CLOSE YOUR ISSUE WITHOUT INVESTIGATING
-->
```

**Comment by vasuneet** [comment]
![image](https://cloud.githubusercontent.com/assets/3884434/24041057/d8adaed2-0b31-11e7-9a74-9c58e74e9be9.png)

**Comment by DzmitryShylovich** [comment]
so the first element is a boolean but must be a function.

**Comment by vasuneet** [comment]
Issue was the aot folder which generated in rc2 was giving some issue. I have deleted this aot folder manually and again used the following commands  -
"node_modules/.bin/ngc" -p tsconfig-aot.json
"node_modules/.bin/rollup" -c rollup-config.js
