### ISSUE TITLE
[4.0.0-rc.4] isPlatformBrowser(PLATFORM_ID) not returning correct platform

### ISSUE THREAD

**Issue by nicky-lenaers** [angular/angular#15232]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`PLATFORM_ID` taken from `@angular/core` returns this object (logged):
```sh
InjectionToken {
  _desc: "Platform ID"
}
```
while it is validated against string value "`browser`" (from `ɵPLATFORM_BROWSER_ID`) using `isPlatformBrowser(PLATFORM_ID)`.

Thus, `isPlatformBrowser(PLATFORM_ID)` never returns `true`.

**Expected behavior**
`isPlatformBrowser` should return true on browser platform. Same holds for `isPlatformServer(PLATFORM_ID)`.

**Minimal reproduction of the problem with instructions**

```sh
import { PLATFORM_ID } from '@angular/core';
console.log(PLATFORM_ID); // prints object

import { isPlatformBrowser, isPlatformServer, ɵPLATFORM_BROWSER_ID } from '@angular/common';

console.log(ɵPLATFORM_BROWSER_ID); // returns 'browser'
console.log(isPlatformBrowser(PLATFORM_ID)); // returns false anyway
```

**What is the motivation / use case for changing the behavior?**

Should be usable to distinguish Universal server app from browser app.

**Please tell us about your environment:**

- VSCode
- NPM

* **Angular version:** 4.0.0-rc.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   v7.7.0

**Comment by DzmitryShylovich** [comment]
you need to inject `PLATFORM_ID` into a component or service

**Comment by nicky-lenaers** [comment]
Thank you. Is this referenced somewhere in the docs? For all the RC's it's hard to find any documentation on new features. How can you gather feedback if no docs exist on these features? Isn't that the idea of RC's? Please correct me if I misunderstand!

Cheers and keep up the awesome work!

**Comment by DzmitryShylovich** [comment]
> For all the RC's it's hard to find any documentation on new features.

there's no documentation (yet) for new features because the team is working on a new angular.io

**Comment by DzmitryShylovich** [comment]
> console.log(ɵPLATFORM_BROWSER_ID)

and don't use things with `ɵ` prefix. it's a private api and it can change any time

**Comment by nicky-lenaers** [comment]
Thanks for the feedback! Too bad no docs exist, but it's obvious it's all work in progress. Closing this issue.

**Comment by nicky-lenaers** [comment]
@DzmitryShylovich one more question: how would I use `PLATFORM_ID` inside `Directive`?

**Comment by DzmitryShylovich** [comment]
```
import { PLATFORM_ID, Inject } from '@angular/core';
import { isPlatformBrowser, isPlatformServer } from '@angular/common';

constructor(@Inject(PLATFORM_ID) platformId: string) {
   isPlatformBrowser(platformId);
}
```

**Comment by nicky-lenaers** [comment]
Perfect, thanks again.

**Comment by guzuomuse** [comment]
@DzmitryShylovich ,can u explaine how to  

>  inject PLATFORM_ID into

thanks

**Comment by DzmitryShylovich** [comment]
@guzuomuse https://github.com/angular/angular/issues/15232#issuecomment-287351827

**Comment by hheexx** [comment]
When I try to inject platformId I receive this error
`Error: No provider for PLATFORM_ID!`

**Comment by DzmitryShylovich** [comment]
did you call `platformDynamicServer` or `platformBrowserDynamic`?

**Comment by michzio** [comment]
How to use this isPlatformBrowser(this._platformId) to encapsulate code I want to be rendered in browser, and not pre rendered on server side (I am using angular 4  with universal that has code pre rendered on the server and throws errors like no window, no event, etc. )

I have tried 
```
ngOnInit() { 
  if(isPlatformBrowser(this._platformId) 
  { // than execute some code here }
 else 
  { // do nothing }
}
```

**Comment by webdeveloperneeraj** [comment]
```
constructor(private http: Http, @Inject(PLATFORM_ID) private readonly platformId: any) {
         this.originUrl = this._utils.ORIGIN_URL;
        console.log(isPlatformBrowser(this.platformId))
         if(isPlatformBrowser(this.platformId) ) {
              this.originUrl = window.location.origin;
        }
  }

```

It's not working for me i am getting false in console.

**Comment by paninee** [comment]
> isPlatformBrowser

Same issue. Is there any fix to this?
