### ISSUE TITLE
Version skew between @angular/compiler-cli and @angular/cli-wrapped

### ISSUE THREAD

**Issue by kylecordes** [angular/angular#15236]
[ X ] possible? bug report

The latest `@angular/compiler-cli 4.0.0-rc.4` depends on `"@angular/tsc-wrapped": "4.0.0-rc.2"`.

I have not confirmed whether this causes any visible big. But I've seen commits go by, and a quick look at:

https://github.com/angular/angular/blob/master/tools/%40angular/tsc-wrapped/

 ...shows that there are recent changes in tsc-wrapped, and that the current tsc-wrapped is `4.0.0-rc.4`.

Therefore, this version skew appears most likely to be an accidental glitch in the release process.

package.json for `@angular/compiler-cli 4.0.0-rc.4`:

```
{
  "name": "@angular/compiler-cli",
  "version": "4.0.0-rc.4",
  "description": "Angular - the compiler CLI for Node.js",
  "main": "index.js",
  "typings": "index.d.ts",
  "bin": {
    "ngc": "./src/main.js",
    "ng-xi18n": "./src/extract_i18n.js"
  },
  "dependencies": {
    "@angular/tsc-wrapped": "4.0.0-rc.2",
    "reflect-metadata": "^0.1.2",
    "minimist": "^1.2.0"
  },
  "peerDependencies": {
    "typescript": "^2.0.2",
    "@angular/compiler": "4.0.0-rc.4",
    "@angular/core": "4.0.0-rc.4"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/angular/angular.git"
  },
  "keywords": [
    "angular",
    "compiler"
  ],
  "contributors": [
    "Tobias Bosch <tbosch@google.com> (https://angular.io/)",
    "Alex Eagle <alexeagle@google.com> (https://angular.io/)"
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/angular/angular/issues"
  },
  "homepage": "https://github.com/angular/angular/tree/master/packages/compiler-cli"
}
```

( @alexeagle ?)

**Comment by DzmitryShylovich** [comment]
yeah, must be `"0.0.0-PLACEHOLDER"` instead of ["4.0.0-rc.2"](https://github.com/angular/angular/blob/master/packages/compiler-cli/package.json#L12)

**Comment by DzmitryShylovich** [comment]
@kylecordes  there's a pr https://github.com/angular/angular/pull/15226 already so I think it can be closed

**Comment by kylecordes** [comment]
@DzmitryShylovich  I'm in the process now verifying I can build and run a bunch of apps with the new stuff.  I'm hoping to confirm the use of rc.2 doesn't actually hurt anything for now. But if I find a bit of yarn hackery or whatever is needed to force rc.4, I will post that here. Then I will close it, either way.

**Comment by DzmitryShylovich** [comment]
rc5 is out with the fix :)

**Comment by kylecordes** [comment]
Excellent! (That wasn't long...)

**Comment by klihelp** [comment]
Peer-dependencies warnings not following the news (typescript installed v2.1.0 or v2.2.0)
https://github.com/angular/angular/blob/master/CHANGELOG.md#typescript-21

```
npm WARN @angular/compiler-cli@4.0.0-rc.5 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN @angular/tsc-wrapped@4.0.0-rc.5 requires a peer of typescript@^2.1.5 but none was installed.
npm WARN @angular/core@4.0.0-rc.5 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@4.0.0-rc.5 requires a peer of zone.js@^0.8.4 but none was installed.
npm WARN @angular/http@4.0.0-rc.5 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/router@4.0.0-rc.5 requires a peer of rxjs@^5.0.1 but none was installed.
```

**Comment by kylecordes** [comment]
@klihelp If the thing in your message is a new problem with rc.5, I suggest opening a new issue for it. I don't think anyone will see it on this closed issue.
