### ISSUE TITLE
Error "ngModule should be provided" when ViewContainerRef.createComponent is called

### ISSUE THREAD

**Issue by apoterenko** [angular/angular#15241]
**I'm submitting a bug report** 

**Current behavior**
I get an error "ngModule should be provided".
This is a regress after migration from 2.2 to  4.0.0-rc.4. See link and my review comment

https://github.com/angular/angular/pull/15044/commits/607a88ae3a284f3005ded8bda4d0cd657a7e0e5a#diff-6d9bd2a10f7802bd4825bb455a32f063R58

**Expected behavior**
The method ViewContainerRef.createComponent should pass optional ngModule parameter or something other solution

```
  createComponent<C>(componentFactory: ComponentFactory<C>..): ComponentRef<C> {
    ...
    const componentRef = componentFactory.create(contextInjector, projectableNodes, .., ngModule?: NgModuleRef<any>);  // XXXXX <---
  ...
  }
```

**Minimal reproduction of the problem with instructions**

It's work
```
const componentRef = this.componentInstance = factory.create(this.injector, null, null, _moduleRef);
this.viewContainer.insert(componentRef.hostView, 0);
```
 
it's not working

```
// TODO Make angular ticket
// this.componentInstance = this.viewContainer.createComponent<MyFuturisticDynamicComponent>(
//	factory,
//	0,
//	this.injector
//);
```

See here https://github.com/apoterenko/angular2-dynamic-component/commit/f255ee3b33465e160a85f9915e9d5a7b2535fa18#diff-6b1acb1c3e5f53cfc8f7c21dafa7d593R141

* **Angular version:** 4.0.0-rc.4

* **Browser:** all
 
* **Language:** TypeScript 2.2.1

**Comment by DzmitryShylovich** [comment]
Please reproduce in plunkr. You can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point

**Comment by alexzuza** [comment]
https://github.com/angular/angular/commit/13686bb

> BREAKING CHANGES
> 
> `ComponentFactory.create()` takes an extra optional `NgModuleRef` parameter.
> No change should be required in user code as the correct module will be used
> when none is provided

**Comment by DzmitryShylovich** [comment]
cc @vicb

**Comment by KhanaevRoman** [comment]
Have some solutions if I have only factory and ViewContanerRef in component?

**Comment by tbosch** [comment]
So where did this `ComponentFactory` come from? From a `ComponentFactoryResolver`? Or is it directly imported from a `.ngfactory.ts` file / from a call to `Compiler.compile`?

**Comment by tbosch** [comment]
A workaround is as follows:

1. call `const compRef = componentFactory.create(..., viewContainerRef.injector.get(NgModuleRef))`
2. call `viewContainerRef.insert(compRef.hostView)`

**Comment by jiann4321** [comment]
@tbosch can you elaborate?

I'm trying to modify a third party library and it's also not working

`
        // code issue on createComponent
        const busyFactory = this.cfResolver.resolveComponentFactory(BusyComponent);
        this.busyRef = this.vcRef.createComponent(busyFactory, null, this.injector);

        // template
        <div [class]="wrapperClass" *ngIf="isActive()" @flyInOut>
            <DynamicComponent [componentTemplate]="template" [componentInputData]="context">
            </DynamicComponent>
        </div>
`

Thanks

**Comment by tbosch** [comment]
@jiann4321 This is because the `DynamicComponent` is compiling the template on the fly, i.e. does not use a `ComponentFactoryResolver`. But my PR https://github.com/angular/angular/pull/15350 should fix this case...
