### ISSUE TITLE
Animations: boolean triggers not working in rc.4 (update from rc.2)

### ISSUE THREAD

**Issue by denisyilmaz** [angular/angular#15247]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I updated from 4.0.0-rc.2 to 4.0.0-rc.4. After update, my animation trigger are not supporting boolean states, I'm getting the error "TypeError: undefined is not a valid value for easing "

**Expected behavior**
Same behaviour as in rc.2, where a animation state can be a boolean.

**Minimal reproduction of the problem with instructions**
```typescript
export function fadeInOutFast() {
  return trigger('fadeInOutFast', [
    state('void', style({opacity: 0}) ),
    state('true', style({opacity: 1}) ),
    state('false', style({opacity: 0}) ),
    transition('0 <=> 1', animate('0.35s linear')),
    transition('* <=> void', animate('0.35s linear'))
  ]);
}
```
```html
<div id="loading-bar-spinner" #loadingBarSpinner [@fadeInOutFast]="state">
```
```typescript
private state:boolean = false;
```

* **Angular version:** 2.0.X
4.0.0-rc.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by denisyilmaz** [comment]
changing `private state:boolean = false;` to `private state:string = 'false';` solves the problem, but I think the state should be able to be a boolean as well

**Comment by AdamJo** [comment]
Same error message as above when upgrading from rc.3 to rc.4 but with different behavior. 

I get `Failed to execute 'animate' on 'Element': 'undefined' is not a valid value for easing` when trying to initiate an animation when it is already in progress.

As in, if the animation is `animate('1s ease-in')` and I click the same button before the 1 second animation has finished, it will cause the above error.   I Tried to get a working Plnkr but haven't got it to run with rc.4 or rc.5 packages.

**Comment by matsko** [comment]
Looking into it.

**Comment by karlhaas** [comment]
Same issue here after upgrading to rc4. When using angular material tooltip and the fade out animation triggers while the fade in animation is still being executed the error occurs.
