### ISSUE TITLE
How to use Angular 2 with Microservices?

### ISSUE THREAD

**Issue by lukecorf** [angular/angular#15249]
Hi. I just learned how to use the Angular 2 framework. But now I need to learning how to use Angular 2 with Microservices. Someone could tell me a page. Or a course that teaches this?

I know many frameworks to use microservice. For exemple:

Kubernetes
Spring

But I don't find material to learning how to use this with angular 2.

If they can help me. Thanks

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by lukecorf** [comment]
Ok. Sorry
