### ISSUE TITLE
Component CSS with @import in comment will trigger fetch

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#15255]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Having comments like this in component css causes a runtime error:
```
/**
 * @import 'path/to/this/file';
 */
```
```
Unhandled Promise rejection: Failed to load app/path/to/this/file ; Zone: <root> ; Task: Promise.then ; Value: Failed to load app/path/to/this/file
```
Apparently these comments are common in sass DocBlocks.

**Expected behavior**

Text in comments should not be interpreted as code.

**Minimal reproduction of the problem with instructions**

Plunker: https://plnkr.co/edit/AQFWDsIHasYsfCr0HnoE?p=preview

**What is the motivation / use case for changing the behavior?**

Text in comments should not be interpreted as code.

**Please tell us about your environment:**

Plunker

* **Angular version:** 2.4.X

* **Browser:** [ Chrome 56  ]

 
* **Language:** [ TypeScript 2.0 ]

**Comment by DzmitryShylovich** [comment]
Pr to fix this https://github.com/angular/angular/pull/14148

**Comment by DzmitryShylovich** [comment]
btw not sure if it's a valid comment at all https://developer.mozilla.org/en-US/docs/Web/CSS/Comments

**Comment by filipesilva** [comment]
@DzmitryShylovich according to that page, this is a valid comment as well:
```
/*
A comment
which stretches
over several
lines
*/
```

**Comment by JoostK** [comment]
This doesn't reproduce for me anymore (in v12)
