### ISSUE TITLE
Get element value ng For

### ISSUE THREAD

**Issue by anivaisu** [angular/angular#15271]
Hi,
I am beginner in angular 2,ionic 2

I create chat application using ionic2.

I have an array value display UI using ngFor.

Pls refer this http://imgur.com/dpnLSSv

I need does not display repeated data.Because I need get input element value and compare with another value.I try to this way.

Below my html code

<ion-content padding>
  <div *ngIf="online === true">
  <ion-refresher (ionRefresh)="onPullOldMessages($event)">
      <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
  <div class="chat" *ngIf="chatval">

    <div class="messagesholder" *ngFor="let chat of chatval | orderby:'[date]';let i = index; trackBy:trackByIndex">
       <div *ngIf="chat.sender == currentuser || chat.receiver == currentuser">
               <input [(ngModel)]="chat.date" type="hidden" value="John Doe">
               <p style="font-size:9px;text-align: center;" id="amount" #amount>{{chat.date | amDateFormat:'LL'}}</p>
       </div>
       <div class="message" *ngIf="chat.sender == currentuser || chat.receiver == currentuser" [ngClass]="{'me': currentuser == chat.sender}">
              <div class='image' *ngIf="chat.path" >
                <img *ngIf="chat.path" [src]="chat.path" imageViewer/><br>
                <span *ngIf="chat.path_text">{{chat.path_text}}</span>
                <span style="font-size:9px;">{{chat.date | amDateFormat:'hh:mmA'}}</span>
              </div> 
               <div *ngIf="chat.message_text">
               <span>{{chat.message_text}}</span>
               <span style="font-size:9px;">{{chat.date | amDateFormat:'hh:mmA'}}</span>
               </div>
        </div>
   </div>
 </div>  
 </div>
</ion-content>
Here is my chat.ts component file

  import { Component,Inject,ViewChild,ElementRef,AfterViewInit} from '@angular/core';

export class ChatPage implements AfterViewInit {
   constructor(public modalCtrl: ModalController,public navCtrl:     NavController) {}

 trackByIndex(index: number, value: number) {
   console.log("ngFor");
   console.log(index);
   console.log(value);
   return index;
   }
}
Does not called the trackByIndex function.How can I get this input element value. I was tried another way. Pls refer this link Angular 2 get Input element value Its not still wrk.

any other way to find this solutions.

Thanks

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

cc @pkozlowski-opensource
