### ISSUE TITLE
Compile error in including toastr js in angular 2 cli project  

### ISSUE THREAD

**Issue by prasadrajacse** [angular/angular#15274]
I am trying to include toastr js in angular 2 cli project. The below error is encountered while running ng build command.

https://github.com/CodeSeven/toastr

ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'toastr'. Consider exporting the symbol (position 33:13 in the original .ts file), resolving symbol AppModule in /Users/durgaprasad/Desktop/ng2-fundamentals-cli/src/app/app.module.ts

version: 1.0.0-beta.20-4

Thanks.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
