### ISSUE TITLE
Trackby index value display UI

### ISSUE THREAD

**Issue by anivaisu** [angular/angular#15273]
Hi all,

    Below my templates code 

  **<div class="chat" *ngIf="chatval">
      <div class="messagesholder" *ngFor="let chat of chatval | orderby:'[date]';let i = index; trackBy:trackByIndex">
                  <div *ngIf="chat.sender == currentuser || chat.receiver == currentuser">
                <p style="font-size:9px;text-align: center;" *ngIf="date !== chat.date " id="amount" #amount>{{chat.date | amDateFormat:'LL'}}</p>
                 <h5>{{dateval}}</h5>
         </div>
     </div>**

It's work perfect.I called trackByIndex method().Here is my function.
dateval;
constructor(){}
trackByIndex(index: number, value: any) {
     console.log("ngFor");
     console.log(value.date);
    this.dateval=value.date;
    console.log(this.dateval);
    return value;
  }

It's console d the date value.But this.dateval is not display the UI.Kindly advice me.

Thanks

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by IgorMinar** [comment]
+1
