### ISSUE TITLE
How to make serverrequest(http) as separate class and user interface for success or error response ?

### ISSUE THREAD

**Issue by aadityanj** [angular/angular#15276]
# How to make a singleton class for http services in Angular2 typescript 
Hi, I am trying to make a singleton class for http service in typescript and also want to use interface for success & error response on http call. I tried inheritance and interface as similarly in  Java.But no luck.
Kindly let me know if anyone have idea about this. Thank you!

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
