### ISSUE TITLE
Improve error message for running build statically

### ISSUE THREAD

**Issue by phil294** [angular/angular#15279]
### Bug Report or Feature Request (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [x] feature request

Coming from https://github.com/angular/angular-cli/issues/5479

### Versions. (latest, 4.0)

@angular/cli: 1.0.0-rc.2
node: 6.10.0
os: linux x64
@angular/animations: 4.0.0-rc.3
@angular/common: 4.0.0-rc.3
@angular/compiler: 4.0.0-rc.3
@angular/compiler-cli: 4.0.0-rc.3
@angular/core: 4.0.0-rc.3
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.0.0-rc.3
@angular/http: 4.0.0-rc.3
@angular/platform-browser: 4.0.0-rc.3
@angular/platform-browser-dynamic: 4.0.0-rc.3
@angular/platform-server: 4.0.0-rc.3
@angular/router: 4.0.0-rc.3
@angular/cli: 1.0.0-rc.2
@ngtools/webpack: 1.2.13

### Repro steps.

A `ng build` generates a `dist/index.html`. Running this file in your browser (aka `file:///home/.../index.html`) might seem intuitive but will not work (reason: [cannot issue XHR requests](https://github.com/angular/angular-cli/issues/641)).
However, the error message is not helpful at all, **saying nothing but**

> EXCEPTION: Uncaught (in promise): SecurityError: The operation is insecure.
BrowserPlatformLocation.prototype.replaceState@file:///home/phi/d/ls/repo/web/dist/vendor.bundle.js:22446:13

### Desired functionality.

Any hint to solve this error would be helpful. 
Note: For local testing or even deploying, one could set up a simple `http-server` (npm).

**Comment by DzmitryShylovich** [comment]
Please reproduce in plunkr

**Comment by phil294** [comment]
@DzmitryShylovich this error message cannot be reproduced in plunkr really. It only applies to transpiled code. 

One thing I notcied: The error only applies when there is routing included. So, steps for reproducing are:

- `ng new` 
- add a standard RouterModule with >=1 route
- `ng build`
- open `index.html` in browser (with `<base base href="">`) (hard file, no http server)

-> error: ` SecurityError: The operation is insecure.`

**Comment by DzmitryShylovich** [comment]
@phil294 if I understood correctly you are trying to load files from files system without http server. In this case you need to change your `base href`. See this thread https://github.com/angular/angular/issues/13948#issuecomment-284944339

**Comment by divyaksh-shukla** [comment]
@DzmitryShylovich I have put the base-href option as well but I still don't get over the error @phil294 mentioned
```bash
ng build --target=production --base-href /home/divyaksh/Documents/Coding/angular_firebase_login/login-angular-app/dist/.
```

**Comment by pkozlowski-opensource** [comment]
I agree that the most likely root cause is https://github.com/angular/angular/issues/15279#issuecomment-289241690

Please open a new issue with a minimal reproduce scenario if this is still an issue.
