### ISSUE TITLE
build with aot - provideLocationStrategy error

### ISSUE THREAD

**Issue by TheILPlace** [angular/angular#15281]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

build with AOT  (with cli) : ng build --prod
receiving the following error

**Expected behavior**

**Minimal reproduction of the problem with instructions**

i've created an interface

```
import {ModuleWithProviders} from '@angular/core';

export interface IRouting {
routes: ModuleWithProviders,
components: any[]
};

```

---

```
i use that interface when declaring my routing class

import { Routes, RouterModule } from '@angular/router';
import { IRouting } from './shared/interfaces/IRouting';

import { HomeComponent } from './home.component';

const routes: Routes = [

{ path: 'home', component: HomeComponent }

];

export const appRouting: IRouting = {
routes: RouterModule.forRoot(routes),
components: [ HomeComponent ]
};

```
and in my app.module, i import the appRouting const in two places
```

import { appRouting } from './app.routing';

@NgModule({
declarations: [
AppComponent,
    appRouting.components
],
imports: [
BrowserModule,
      appRouting.routes
],
providers: [],
bootstrap: [AppComponent]
})
export class AppModule { }

```

when compiling/build with AOT (ng build --prod) the following error occures:

```
ERROR in Can't resolve all parameters for provideLocationStrategy in C:/Angular2_
Clients/ng2lab/angular/node_modules/@angular/router/src/router_module.d.ts: ([obj
ect Object], ?, [object Object]).

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in
'C:\Angular2_Clients\ng2lab\angular\src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts
```

i'm using the above notation, so save importing the route components again in the app.module.

thanks.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

windows 10, angular cli rc1
* **Angular version:** 2.0.X

angular 2.4.9
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 56
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =   
6.9.10

**Comment by DzmitryShylovich** [comment]
Please fill out the issue template and format the code, it's unreadable. thanks

**Comment by TheILPlace** [comment]
thanks ! i've rewrote it, and now it looks better.

**Comment by DzmitryShylovich** [comment]
Much better, thank you. Can you reproduce this in plunkr? You can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point

**Comment by DzmitryShylovich** [comment]
did you call `RouterModule.forRoot` somewhere?

**Comment by DzmitryShylovich** [comment]
Ok, according to the error, angular can't resolve `baseHref`. Did you add `<base href="." />` in the index.html?

**Comment by TheILPlace** [comment]
of course/... 
`  <base href="/">`

should it be  `<base href="." />`  ??
this is the default created with angular-cli scaffolding

i've created the plunkr, but dont know how to use AOT with plunkr
http://plnkr.co/edit/j9PYhqRuqtoBrU4aBgMz?p=preview.

**Comment by DzmitryShylovich** [comment]
> i've created the plunkr

you didn't save your changes

> dont know how to use AOT with plunkr

it's not possible. does it work in jit?

does it work if you add
```
@NgModule({
...
providers: {provide: APP_BASE_HREF, useValue : '/' }]
})
export class AppModule { }
```
?

**Comment by TheILPlace** [comment]
i've saved it. double checked.
http://plnkr.co/edit/j9PYhqRuqtoBrU4aBgMz?p=preview

the problem doesnt occur in GIT. i've triple checked it.
i use angular-cli.
if i run "ng serve" it works
if i run "ng build --prod" (which does AOT by default) it gives the error mentions.
if i run "ng build --prod --aot false" no error

if i change the following

```
export const appRouting: IRouting = {
routes: RouterModule.forRoot(routes),
components: [ HomeComponent ]
};

```
to  simply :

`export const myRoutig = RouterModule.forRoot(routes) ;`

and import that in the app.module

everything works fine in AOT.
so the problem is the use of the interface. not the base-href

i've tried your suggestion

`providers: {provide: APP_BASE_HREF, useValue : '/' }]`

error remains the same.

**Comment by DzmitryShylovich** [comment]
@TheILPlace can you try it out using ng4?

**Comment by TheILPlace** [comment]
created a fresh ng4 project.
tried again. the error now changes to:
```

ERROR in Can't resolve all parameters for ɵc in C:/projects/first-app/node_modules/@angular
/router/router.d.ts: ([object Object], ?, [object Object]).

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\projec
ts\first-app\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

i must add, that during my attempts to write the sample, i had to stop "ng s" and restart it again many times, as each time i got different errors, that god knows where they came from. only after "ng s" again, the compilation changed and things got better.

as to the point: ng s  works for the sample, ng build --prod   does  not
meaning - without AOT it works. with AOT - it fails

**Comment by TheILPlace** [comment]
anyways, i went in a different path to resolve this.
got rid of the interface, and made a my own routing module, in which i re-export the components used in the routes, and the RouterModule itself

importing it in the AppModule.ts - seems to do the trick and now aot build works.

```


import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { AboutComponent } from './about/about.component';

 const routes: Routes = [
  { path: '', redirectTo:'home',pathMatch:'full' },
  { path: 'home', component: HomeComponent },
  { path: 'about', component: AboutComponent },
    { path: '**', redirectTo:'home' }
];

@NgModule({
  declarations: [
      HomeComponent,
    AboutComponent,
      ],
  imports: [RouterModule.forRoot(routes)
      ],
  exports: [RouterModule,HomeComponent,AboutComponent]
  })
export class AppRoutingModule { }

```

**Comment by dipunm** [comment]
I don't understand the reason why, but the solution of moving the `RouterModule.forRoot` into it's own XRoutingModule fixed the problem for me too. I know the documentation recommended to do this from the beginning, so maybe there is a logical reason why this fixed the problem, but technically, I think it's cleaner not to have an XRoutingModule.
