### ISSUE TITLE
ServerModule  could not resolve

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#15283]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am trying to build library using ngc. As soon as i add `import {PlatformState} from '@angular/platform-server';` statement ngc fails with error:

*Error encountered resolving symbol values statically. Could not resolve @angular/platform-browser relative to F:/git/lib/node_modules/@angular/platform-server/platform-server.d.ts., resolving symbol ServerModule in F:/git/lib/node_modules/@angular/platform-server/platform-server.d.ts, resolving symbol ServerModule in F:/git/lib/node_modules/@angular/platform-server/platform-server.d.ts*

**Expected behavior**
It should compile like when i use any other angular package.

**Minimal reproduction of the problem with instructions**
tsconfig ngc section
```json
,
    "angularCompilerOptions": 
    {
        "skipMetadataEmit" : false,
        "genDir": "dist"
    }
```

**Please tell us about your environment:**
Windows 10, VScode

* **Angular version:** 4.0.0-rc.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [TypeScript 2.2.1]

* **Node (for AoT issues):** `node --version` = v7.7.1

**Comment by kukjevov** [comment]
Here repository illustrating problem https://github.com/kukjevov/ngc-server-fail

Just run npm install and npm run build.

Thank you :)

**Comment by vikerman** [comment]
Please add 

"@angular/platform-browser": ">=4.0.0-rc.5",

to your package.json.
