### ISSUE TITLE
FormGroup and FormControl - values / valueChanges?

### ISSUE THREAD

**Issue by kylecordes** [angular/angular#15282]
[X] feature request

This is a feature I am proposing for a future Angular.

**Current behavior**

Both FormGroup and FormControl provide `.valueChanges`, and observable stream of changes to the control or group of controls' value. This is very helpful, but it seems to omit the first value (before the first "change") for no particularly good reason other than consistency with the name.

This is easily worked around by with something like this:

```
const x$ = this.aControl.valueChanges.startWith(this.aControl.value);
```

... which is effective, but verbose and repetitive.

**Expected behavior**

Programmatically, very often when handling a control or group as an observable stream, one wants access to the entire stream from the beginning.

Therefore, I request that `.valueChanges` be supplemented with `.values`, which would be an Observable that emits both the initial value and changes.

**Minimal reproduction of the problem with instructions**

A search of Github yields numerous cases in published Angular code where something similar to the above pattern appears.

https://github.com/search?q=valueChanges.startWith&ref=simplesearch&type=Code&utf8=%E2%9C%93

All of these, as well as similar code behind countless corporate firewalls, could be tightened up by this API improvement.

**Comment by DzmitryShylovich** [comment]
just need to replace `EventEmitter`s with `BehaviorSubject`s.

**Comment by Toxicable** [comment]
@DzmitryShylovich just replacing Subject with BehaviourSubject might cause issues with people who have solved this problem by calling `updateValueAndValidity()` to make the Subject emit since BehaviourSubject it would then effectively emit twice

**Comment by wulfsberg** [comment]
This is particularly relevant for select dropdowns which by nature have a filled-out default state.
If you then initialize those with setValue to a value which happens to match the default, no valueChanges is emitted, giving you the worst of both worlds: No information about the original (default) value, and no change event since the value didn't technically change.
This is strictly speaking not unique to dropdowns; they are just more prone to falling into that trap.

**Comment by jraadt** [comment]
This has also been a bit of a pain for me as well.  I agree that it would be great if .valueChanges be supplemented with .values, which would be an Observable that emits all values (initial, changes, duplicates, etc).  .valueChanges is still a useful shortcut in many instances, but .values would give the developer full control over ALL values coming from the form.

For example, I have a filtered search and when the component initializes I setup my filter form and then I want to execute a search off of all form changes including an initial search with the initial values I set.

**Comment by aksenovdev** [comment]
Also it will be uselful in sitaution, when you have some piped form value observable with startWith, and want suscribe to it when some event emmited. If we do it with
```
formValue$ = this.form.valueChanges
      .pipe(
        startWith(this.form.value),
      );
```
Then every time, when you subscribe on formValue$, you will get initial form value, not current.
[Example](https://stackblitz.com/edit/angular-1h4bzr)

**Comment by dylhunn** [comment]
We are very unlikely to ever change this:

1. It would be a tremendous breaking change -- every consumer of `valueChanges` would start getting extra events.
2. It doesn't really fit with how JS treats events in general (consider `onChange` for a select, for example).

We *are* looking at revamping the value and status changes, but that's likely to be a totally new design.

**Comment by wulfsberg** [comment]
The request was specifically to add a new observable with a more desirable, pragmatically more useful behavior, not to make a breaking change in the existing.

**Comment by dylhunn** [comment]
Right, we probably *are* going to add new observables at some point, but that's tracked in #10887.
