### ISSUE TITLE
Wrong error about non exported function for decorators

### ISSUE THREAD

**Issue by tflori** [angular/angular#15287]
I'm researching a lot but all I found is "do this and it will work" but it does not. Also the error message can not be correct and it is working when I save the file again.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When I start `ng serve` and everything is compiled already I get the following error:

```
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 17:12 in the original .ts file), resolving symbol TranslateLogHandler in /home/iras/work/angular2-cli-t
est/node_modules/angular2-translator/src/TranslateService.ts, resolving symbol TranslateLogHandler in /home/iras/work/angular2-cli-test/node_modules/angular2-translator/index.d.ts, resolving symbol AppModule in /home/iras/work/angular2-cli-test/src/app/app.module.ts, resolving symbol AppModul
e in /home/iras/work/angular2-cli-test/src/app/app.module.ts
```

Yes, of course you will write use an exported function - please have a look in *Minimal reproduction of the problem with instructions*.

When I save/touch the file (update mtime from file) while ng-serve is running. It gets recompiled without error: `webpack: Compiled successfully.`.

**Expected behavior**
It should always work not just sometimes.

**Minimal reproduction of the problem with instructions**
Create a new project `ng new justAnotherBug`. And a file `src/app/Logger.ts` with the following content:

```ts
export const Logger = {
  debug: () => {},
  error: (message) => console && console.error && console.error(message),
  info: () => {},
}
```

Write this in your app.module.ts:

```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';
import { Logger } from './Logger';

export function getLogger() {
  return {
      debug: () => {},
      error: (message) => console && console.error && console.error(message),
      info: (message) => console && console.log && console.log(message),
  };
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [
    { provide: Logger, useFactory: getLogger, deps: [] }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Finally run `ng serve`. When it works: restart `ng serve` without modifying the file again (first time it will work usually).

**What is the motivation / use case for changing the behavior?**
The use case is to overwrite the Logger for this application (the Logger could be from any third party module).

**Please tell us about your environment:**
```
$ uname -sr
Linux 4.9.13-1-MANJARO
$ npm --version
4.4.1
$ node --version
v7.7.2
node: 7.7.2
$ npm list |egrep '(\@angular|typescript)'
├─┬ @angular/cli@1.0.0-rc.2
│ ├─┬ @angular/tsc-wrapped@0.5.2
│ ├── typescript@2.1.6
├── @angular/common@2.4.10
├── @angular/compiler@2.4.10
├─┬ @angular/compiler-cli@2.4.10
├── @angular/core@2.4.10
├── @angular/forms@2.4.10
├── @angular/http@2.4.10
├── @angular/platform-browser@2.4.10
├── @angular/platform-browser-dynamic@2.4.10
├── @angular/router@3.4.10
├── typescript@2.0.10

**Comment by DzmitryShylovich** [comment]
The problem here is that `Logger` is an object. You can't use arbitrary objects as provider tokens.
Use:
1. string
2. `InjectionToken`
3. class/abstract class

and it will work

**Comment by tflori** [comment]
Hm the message states out it is because of and lambda or anonymous function. Is there a document that says it has to be a class? The next question: Why is this the case? You can't figure out a name from it or can't ask if `(obj instanceof Logger)` or why?

And even then: Why it is working when the watcher get triggered?

**Comment by DzmitryShylovich** [comment]
> And even then: Why it is working when the watcher get triggered?

it's something related to cli. I tested it in custom webpack starters (for example, https://github.com/AngularClass/angular2-webpack-starter) and I got an error every time.

> Hm the message states out it is because of and lambda or anonymous function.

this is because of arrow functions `debug: () => {}` etc. If you remove them `export const Logger = {}` you will get a different error.

**Comment by tflori** [comment]
When I use the longer version in the object is the same error but an object without functions works and it does not make sense for me. I never heard that you can't use objects for providers. And it has no errors when it compiles second time.

This works:

```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';

export const Logger = {
  info: false,
  error: "console.error",
  debug: false,
};
export const AppLogger = {
  info: "console.log",
  erro: "console.error",
  debug: false,
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [
    { provide: Logger, useValue: AppLogger }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

And this not:
```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';

export const Logger = {
  info: () => {},
  error: message => console.error(message),
  debug: () => {},
};
export const AppLogger = {
  info: message => console.log(message),
  erro: message => console.error(message),
  debug: () => {},
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [
    { provide: Logger, useValue: AppLogger }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by DzmitryShylovich** [comment]
@tflori btw in ng5 only Types (classes/abstract classes) and InjectionTokens will be allowed for injection. See [Injector.get](https://github.com/angular/angular/blob/master/packages/core/src/di/injector.ts#L57). So I wouldn't recommend to use strings/objects etc as tokens.

**Comment by tflori** [comment]
what is injection token for you? only the name given in "provide"?

Here is another example that should work, works on `touch app.module.ts` and shows the error message that I should `consider replacting the function or lambda with a reference to an exported function`.

I think the most people using ng are developers. Developers understand cryptic error messages. We should at least write a error message that states out what the developer has to do to make it work.

```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';

export class ThirpartyModuleConfig {
  constructor(public path: string = 'assets/some.json') {}
}

export const myModuleConfig = new ThirpartyModuleConfig('assets/another.json');

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    //TranslatorModule
  ],
  providers: [
    { provide: ThirpartyModuleConfig, useValue: myModuleConfig },
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**Comment by tflori** [comment]
It's getting really annoying. Especially that it works (typescript and browser don't see an error here) and the compiler can be tricked by changing something in the file.

When I understand it correct you try to figure out problems by parsing the files by yourself instead of trusting the typescript compiler.

There are so many examples out there that do not work with `ng build` or `ng serve`. Even in the official angular documentation: https://angular.io/docs/ts/latest/api/core/index/FactoryProvider-interface.html

I created a fresh angular application with `ng new angular-cli-test` and just changed the app.module.ts to:
```ts
import { BrowserModule } from '@angular/platform-browser';
import {InjectionToken, NgModule} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';

const Location = new InjectionToken('location');
const Hash = new InjectionToken('hash');

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [
    { provide: Location, useValue: 'http://angular.io/#someLocation' },
    {
      provide: Hash,
      useFactory: (location: string) => location.split('#')[1],
      deps: [Location]
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

```
$ ng build
Hash: c96e426f958ae21096b2                                                              
Time: 4794ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 3.98 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.77 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.07 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 24:19 in the original .ts file), resolving symbol AppModule in /home/iras/work/angular-cli-test/src/app/app.module.ts
```

For me this is major bug. Not just anything that can be solved in angular 5...

**Comment by tflori** [comment]
It's getting more and more strange. I'm developing a module for angular and linked the module to a angular project with a symlink when I import this module it gets everytime the same error - even when this module only provides some classes (no useValue, useFactory - not even useClass).

I'm out of ideas - I tried debugging the code but it's just a wild jumping between compiler.es5.js and compiler.umd.js with wrong line numbers. It's really frustrating not to know if it will be solved or not. I also can't compile using --aot=false.

I'm on @angular/cli@1.0.0, node@7.7.3, npm@4.4.4, @angular/compiler@4.0.1

**Comment by tflori** [comment]
I just realized what is the problem in the most cases: the metadata.json.. this behavior will result in everyone is monkeypatching information in metadata.json. I'm totally disappointed.

For example

```ts
export static function provideSomething(providers): Provider[] {
   providers.push(AnotherClass); // without this line it works
   return providers;
}
```

This results in a metadata.json where provideSomething has no `value` and this throws this error (which is a misleading error message). You can patch this file and add the information you need: `"value": { "__symbolic": "reference", "name":"providers"}`...

**Comment by alxhub** [comment]
I agree with the premise of the bug, the error message here is misleading and confusing. Using an object as a provider token isn't supported by View Engine, but it doesn't tell you that.

This is only a problem with View Engine, though, as in Ivy providers are an entirely runtime concept.

**Comment by JoostK** [comment]
Closing as resolved in Ivy.
