### ISSUE TITLE
an option to controle imported css styles for imported modules 

### ISSUE THREAD

**Issue by chaouiy** [angular/angular#15298]
Angular auto-import all css styles for imported modules. sometimes we need to install third party plugin and override it's style to be more consistent with  visual identity. having an option to controle imported css styles when importing modules would be greate to override default styles.

**Comment by Toxicable** [comment]
Can you please fill out the issue template? Some examples might also help your case

**Comment by IgorMinar** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by amineparis** [comment]
it's not an issue. it's a possible enhancement. let's give an example. I have installed ng2-smart-table. I can't change table css since it's imported within the module. 
_**wanted behaiviour:**_ possibility to importe module without importing css files inside it.

**Comment by Arap919** [comment]
The same problem. Is there any news?

**Comment by Arap919** [comment]
Because we have problem with audit by pcidss

**Comment by JoostK** [comment]
Angular modules don't get to inject styles through Angular, they'd have to manually add the stylesheet to the document when loaded which is outside of the control of the framework.
