### ISSUE TITLE
runGuardsAndResolvers: 'paramsOrQueryParamsChange': resolve on query param change works but data does not seems to be passed to subscribed Observable.

### ISSUE THREAD

**Issue by basilikum** [angular/angular#15290]
**I'm submitting a ...**
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using `runGuardsAndResolvers: 'paramsOrQueryParamsChange'` to make sure that a resolver is run whenever a query parameter changes, the resolver does runs, but the fetched data is not passed onto the subscription to the `route.data` Observable within the component.

**Expected behavior**
If I subscribe to `route.data` within the component, I would expect to get updates whenever new data is fetched, but I only get the initial data, no updates.

**Please tell us about your environment:**
Ubuntu 16.04

* **Angular version:** 2.0.X
Angular 4.0.0-rc.5

* **Browser:** 
Chrome 54

**Comment by Toxicable** [comment]
Can you reproduce in a plunkr please

**Comment by basilikum** [comment]
@Toxicable I'm sorry I'm afraid that I am not really familiar with plunker and fiddling around with it to create an angular4.0.0-rc.5 setup will simply take too much time, that I don't have right now. But I created a sample app with angular-cli and moved it to my github: https://github.com/basilikum/bug15290_ng4

It is very straight forward: the link "change query param" changes the query param `i`, to the current value of `item` (which is the big letter number on screen). Then the resolver kicks in and resolves `item` to a new random number. But as you can see, the number is never updated, despite the fact, the the resolver actually runs.

**Comment by Toxicable** [comment]
@basilikum here's a template plunkr for v4
http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview

**Comment by basilikum** [comment]
@Toxicable Sorry I could not get it to run within plunker. Probably just a small mistake but I have to look into it but currently not time. I can try to get the plunker demo to run within the next 2 days or so but probably not before that. Sorry again. Does the github repo not help?

**Comment by Toxicable** [comment]
I don't know why it's happening but here's a plunkr showing it
http://plnkr.co/edit/iGxAp2jfTCjUNGs5vQQ4?p=preview

**Comment by Toxicable** [comment]
I didn't try your github repo but it works fine in this plunkr
http://plnkr.co/edit/iGxAp2jfTCjUNGs5vQQ4?p=preview
So looks like something wrong with the way you're testing it possibly, or maybe your setup

**Comment by basilikum** [comment]
@Toxicable Hmm...but your plunker does not even change the query params in the url? Still does not seem to work for me in this example: http://plnkr.co/edit/UC39EjWv261lnbGMxVqT?p=preview
If you click on the link, it changes the query param and should therefore update with a new random number, which it does not.
You can also see that in the console. The "resolve" log will be executed, but not the "in subscribe" log.

**Comment by Toxicable** [comment]
@basilikum Right, sorry I see what you're saying. Okay well i'm not sure what's up in this case then

**Comment by basilikum** [comment]
@Toxicable Ok, thank you anyway. Especially for the help with plunker.
