### ISSUE TITLE
angular parse problem

### ISSUE THREAD

**Issue by patrikx3** [angular/angular#15291]
fine

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/6652, https://github.com/angular/angular/issues/13217, https://github.com/angular/angular/issues/5540, https://github.com/angular/angular/issues/6648. If you look for more you'll find for sure

**Comment by patrikx3** [comment]
ok but when it will be fix? it is just an angular problem? it is forceful and any browser allows.

**Comment by patrikx3** [comment]
besides angular2 itself is non valid html!

**Comment by DzmitryShylovich** [comment]
@patrikx3 please don't spam everywhere...

`p` element has been closed by `div` element, so you don't need to close it yourself. See https://developer.mozilla.org/en/docs/Web/HTML/Element/p `Tag omission` section

**Comment by patrikx3** [comment]
it should work, not break.
that's all i am saying.

**Comment by DzmitryShylovich** [comment]
@patrikx3 it's not a valid html http://prntscr.com/em4nlv

**Comment by patrikx3** [comment]
Angular 2 is not valid html itself.
Besides all browsers allow anything.
I understand HTML, come on.

**Comment by DzmitryShylovich** [comment]
> I understand HTML, come on.

oh I see :)

> Angular 2 is not valid html itself.

it's not valid by the spec. Try it out https://validator.w3.org/

**Comment by patrikx3** [comment]
so if i create a custom element:
```<anything-goes-on/>```
is it valid?
let me know!

**Comment by patrikx3** [comment]
check out the specs:
https://pages.corifeus.tk/

What's the idea? Angular 2 itself is invalid, but the inner working is valid??? So weird!

![image](https://cloud.githubusercontent.com/assets/4770180/24091782/81129334-0d4a-11e7-9852-f26d00c2108f.png)

**Comment by patrikx3** [comment]
Angular 1 used to be allow a lot, open.
All I am stating it is now is becoming very
