### ISSUE TITLE
[4.0.0-rc.5] Animate programmatically

### ISSUE THREAD

**Issue by nicky-lenaers** [angular/angular#15294]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Ways to animate apart from Component declarations don't work.

**Expected behavior**

Run animations e.g. from within a Directive.

**Minimal reproduction of the problem with instructions**

As #13818 describes, there's no `invokeElementMethod` available, so this is out of question. But I understand that `Renderer` will be removed anyway from the `4.0.0` release, so `Renderer.animate(/*...*/)` will also not be available.

Since there's no way of adding `animations` to a `Directive` like you can with a Component declaration, is there any way to use `animate` to e.g. animate from within a `Directive`?

I currently get:
```sh
Renderer.animate is no longer supported!
```

Which is a clear message, sure, but I'm left in the dark as to how to make them work again. Any documentation would be nice 👍 , or please improve the Error message, as this breaks people's app without offering alternative solutions.

**What is the motivation / use case for changing the behavior?**

We should be able to animate e.g. from within Directives.

**Please tell us about your environment:**

- VSCode

* **Angular version:** 2.0.X

4.0.0-rc.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

* **Node (for AoT issues):** `node --version` =   7.7.0

**Comment by DzmitryShylovich** [comment]
@nicky-lenaers `Renderer` is deprecated and you should use `Renderer2`. But as you said `Renderer2` doesn't have doesn't have `animate` and `invokeElementMethod` methods.

`animate` is now a part of `AnimationDriver` but it's not injectable so looks like there's no way to do this manually.

ping @matsko

**Comment by nicky-lenaers** [comment]
> animate is now a part of AnimationDriver but it's not injectable so looks like there's no way to do this manually.

Ah, that's unfortunate! Correct me if I'm wrong, but it seems to me that it's not a very DRY solution, since there's an `AnimationDriver` powering animations, but its not injectable. I have to write my own implementation now, while it was actually already written in e.g. `Renderer.animate()`.

Any reason for this design decision in `Renderer2` with respect to `Renderer`?

**Comment by matsko** [comment]
So there's annoying news and really good news.

What's annoying: We can't support renderer.animate() anymore because animations are totally decoupled from the framework with 4.0.0 and onwards. This means that programmatically generating raw keyframes and passing them into renderer.animate won't work anymore.

What's really good: With the **first beta of angular 4.1** (which comes out as the follow-up release to this weeks 4.0.0) you can do the following:

```ts
class MyCmp {
   constructor(private _builder: AnimationBuilder) {
   }
   myMethod() {
      const animation = this._builder.build([
        style(...),
        animate(...),
        group([
          animate(...)
          animate(...)
          animate(...)
        ])
      ]);
      const player = animation.create(someElement);
      player.play();
   }
}
```

This is effectively programmatic animations without the need to conform to the renderer API and web-animations.

If you really really really want to use this now then you can always import the undocumented class `Animation` (`import {Animation as Animation} from "@angular/animations/browser";`) and you can use the `constructor` and `create` methods to achieve this (https://github.com/angular/angular/blob/master/packages/animations/browser/src/dsl/animation.ts#L43). If you look at https://github.com/angular/angular/blob/master/packages/animations/browser/test/dsl/animation_spec.ts then you can get an idea of how to use this undocumented class. Once the beta arrives then please do use the new AnimationBuilder feature.

**Comment by nicky-lenaers** [comment]
@matsko Thanks a lot, this looks very promising! Also, the syntax is way more intuitive and very close to native Web Animations API 👍  Gonne give it a shot real soon

**Comment by emilio-martinez** [comment]
Incidentally, I'm only getting the `Renderer.animate is no longer supported!` error at runtime. If it's not supported, anymore I would ideally have that surface at compile time.

Looking forward to `AnimationBuilder`!

**Comment by oliveti** [comment]
Hi,

Beta of angular 4.1 is here and I do not see this AnimationBuilder inside. 
Is it still planned ?

**Comment by emilio-martinez** [comment]
@oliveti According to the Angular Weekly Meeting Notes for April 17:

> - 4.1 plan
>   - Plan is to ship on May 5
>   - Nullability support and Animations bits are on track

**Comment by CaerusKaru** [comment]
4.1 is here, but AnimationBuilder and other enhancements have been left out of the release. Is there a timeline for inclusion in the next release?

**Comment by CaerusKaru** [comment]
For those still following this, @matsko has just merged the animations features into master with 16c8167886d63f5b4cf03d420478b64640e45654. My bet is that it should be available in the next 4.2 beta.

**Comment by CaerusKaru** [comment]
And it's here! As of 4.2.0-rc.1 (3d382dc7509880cbb8d945c28090c1a5eac336b8), the new animations features are live on angular/animations@next

**Comment by matze1234** [comment]
@CaerusKaru Where can one learn about those features?

**Comment by d3viant0ne** [comment]
@matze1234 - Given how `new` `@angular/animations` is, the best place I have found at the moment is code diving and hacking on play projects.

Some info here - https://angular.io/guide/animations

And rangle.io / thoughtram.io have some blog content as well iirc

**Comment by CaerusKaru** [comment]
The best way to learn about all of these new features is to review @matsko's presentation at ng-conf this year. Slides can be found [here](http://slides.yearofmoo.com/ng-conf-2017-slides/#/0/0/) (navigate using space bar and arrow keys). It comes with links to the code used, and the live demo. Then there are two parts of the documentation to look at. One is the API list, found [here](https://angular.io/api) (under the **animations** header). The other is the Animations guide, which has not yet been updated to include the new features but will probably be soon, found [here](https://angular.io/guide/animations).

**Comment by dario-piotrowicz** [comment]
Given that `AnimationBuilder` has been present for quite a long time now and it does provide a programmatic way to handle animations, shouldn't this issue be closed?

**Comment by JeanMeche** [comment]
Per above.
