### ISSUE TITLE
Improving dev experience with faster builds/tests

### ISSUE THREAD

**Issue by ocombe** [angular/angular#15296]
**I'm submitting a ...**
```
[x] feature request
```

**Current behavior**
When I want to run integration tests for compiler-cli (scripts/ci/offline_compiler_test.sh) I have to build all of the angular code with build.sh and it takes a loooong time (about 7mn on my VM).
This means that when I'm working on the compiler-cli I loose a lot of time just to check that my code works. The simplest check will take me 10mn.
I usually end up editing the umd files in the generated folder instead of source files because it's way faster this way, but then I have to find and copy my updates...
The build does a lot of things, but I probably don't need most of them (like transforming the packages in x formats, since we only use umd files for the compiler tests).

**Expected behavior**
Only build what I need for my tests, I don't need optimized files when I'm still developing. What I need is some kind of "cheap minimal build for tests", and/or maybe to ability to only rebuild the one package I'm working on.

**Minimal reproduction of the problem with instructions**
launch `build.sh`, go take a coffee, come back and still wait 2 more minutes for it to finish, then run `scripts/ci/offline_compiler_test.sh`

**What is the motivation / use case for changing the behavior?**
Stop loosing time on building files to have more time on real code

**Comment by IgorMinar** [comment]
This is not going to happen before we migrate over to Bazel which is being planned now and we'll start working on in the next few weeks.

**Comment by alexeagle** [comment]
Bazel has solved this, could still be faster but that's tracked in other issues (e.g. running `integration/` tests under Bazel)
