### ISSUE TITLE
Request: "animate" compatible with Web Animations API "animate"

### ISSUE THREAD

**Issue by cortopy** [angular/angular#15303]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
Currently, `animate` in angular takes `timing` as the first parameter, this being either a string or a number. However, this is confusing when compared with [web animations api](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate), which either takes a number or an options object.

It is convenient that in angular you can pass a string with formatted time and easing. But web animations API is far richer and angular is not taking advantage of this.

It would be great if angular could just pass the options to the animations API so that we can have things like:
- iteration
- fill
- direction
etc.

**Comment by matsko** [comment]
Sorry @cortopy that it took me forever to respond to this, but you can actually do this already in the API (it's just not documented).

```ts
// fill mode is disabled due to the nature of how animation @triggers work
animate({ duration: 1000, delay: 10, easing: 'ease-out' }, style(...))
```

**Comment by matsko** [comment]
I've created an issue that you can follow along with: https://github.com/angular/angular/issues/20401
