### ISSUE TITLE
module.run() equivalent in Angular 2

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1530]
I wonder if there's something like `angular.module().run()` in Angular 2. Angular 2 doesn't have `config()` and `run()` anymore (which is good), but I think there are still some cases where we want to execute some code, once everything inside a component is compiled. Something that is only initially executed.

I'm currently playing with the instance of `ComponentRef` that we get from `bootstrap()` a la:

```js
bootstrap(MyComponent).then((ref) => {
  let app = ref.instance;

  app.run();
});
```

Whereas `run()` is a method that needs to be executed once everything inside `MyComponent` is compiled. I also tried using `onAllChangesDone` but it seems this is executed several times per second and not only once.

**Comment by robwormald** [comment]
I was wondering about this too. One of the biggest issues with the current 1.x implementation is that its nigh-impossible to wait for async stuff in run, so you end up doing some mess with resolve to wait for that sort of thing to complete. *If* such an API gets added, it would be good if i could just return a promise...

**Comment by mhevery** [comment]
Use of `then` on `ComponentRef` should be the right approach.

```javascript
bootstrap(MyComponent).then((ref) => {
  let app = ref.instance;

  app.run();
});
```

What specifically is not working?

**Comment by PascalPrecht** [comment]
@mhevery waiting for `bootstrap(comp)` to resolve works perfectly fine! Just wanted to make sure that this is the way to go. Closing this since my question is answered.

**Comment by rizwanhussain-vteams** [comment]
@PascalPrecht I don't know if there is a better practice around now but one solution i found was to use put my logic in `onNgInit` of my bootstrap component. Is this a viable approach? Because i want to keep the bootstrap ts as thin as possible.

**Comment by PascalPrecht** [comment]
@rizwanhussain-vteams there's difference between running something when an app is bootstrapped (once) and running something whenever a component is initialized (multiple times).

It depends on the use case but I think the closest equivalent would be to use bootstrap().then().

**Comment by eapenjohn** [comment]
if i understanding  correct we can only have one bootstrap. That means we can only have one run for all the modules in my application .But i have case that need to initialise the service.
Is it possible run a service from a module after that module fully initialised.?

**Comment by mhevery** [comment]
You can put work into the constructor of the module.

**Comment by clavecoder** [comment]
I know in .NET initializing in a constructor is an antipattern due to limited error handling options. Also you can't declare a constructor as async.

Not the case in ES?

**Comment by clavecoder** [comment]
Does this answer meet the canonical test? https://stackoverflow.com/a/44731279/2240669

text:

> [...]it's not easy to find information on APP_INITIALIZER. The short version is you can use it to run initialization code before any of your other application code runs. ...
