### ISSUE TITLE
publish-build-artifacts.sh no longer works per DEVELOPER.md

### ISSUE THREAD

**Issue by kylecordes** [angular/angular#15307]
[X] bug report

**Current behavior**

`publish-build-artifacts.sh` no longer works as described in DEVELOPER.md, to support publishing builds for other people to try out. Issues:

* Script has moved to `./scripts/ci/publish-build-artifacts.sh`, no longer exists at documented location.
* Script fails with:

```
./scripts/ci/publish-build-artifacts.sh: line 68: TRAVIS: unbound variable
```

It appears this was moved and edited, in further support of CI (great!) but breaking non-CI use (boo!).

**Expected behavior**

Work as docs, or docs updated.

**Minimal reproduction of the problem with instructions**

Follow instructions in DEVELOPER.md:

https://github.com/angular/angular/blob/master/DEVELOPER.md#publishing-snapshot-builds

**Please tell us about your environment:**

OSX, but it probably does not matter.

* **Angular version:** 

Current master.

**Comment by kapunahelewong** [comment]
Thank you for this, @kylecordes. :)

I believe this was fixed in https://github.com/angular/angular/pull/29048.

I'll close but if you have any outstanding questions, please feel free to re-open and tag me.
