### ISSUE TITLE
compiler-cli: Can't load modules (using SystemJS) after compiler-cli replaces absolute import by relative imports

### ISSUE THREAD

**Issue by karlhaas** [angular/angular#15301]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In our project we use system js in order to create our application bundles. Because we split our project into several applications, we build one bundle for all common services and components (lib.bundle.js) and one bundle per app (app.bundle.js) which does not include what is already available in lib.bundle.js. We are using https://github.com/systemjs/builder (Version 0.15.35) to build the bundles.

Further we are using baseUrl and paths in tsconfig in order to be able to import our core files with an absolute import path. Example:
tsconfig:

```
    "baseUrl": "./",
    "paths": {
      "@our-lib/*": [
        "src/our-lib/*"
      ]
```

When transpiling without AoT, the import statements remain absolute and we are able to configure SystemJS (0.19.42) in order to load the file from the lib.bundle.js

Now we want to use AoT. ngc runs successfully and we can bundle the files by using index-aot.ts (bootstraps the module factory) instead of index.ts. 

We can't find a way to configure SystemJS in order to locate the modules in our lib.bundle.js. We see that ngc replaces the absolute import by a relative import although it uses the same baseUrl/paths configuration.

**Expected behavior**
ngc should produce absolute imports if there is a path mapping in tsconfig or we need a way to map relative imports to absolute imports in system js config.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Use AoT in a complex project which uses system js / system js builder and later on lazy loading.

**Please tell us about your environment:**

* **Angular version:** 4.0.0-rc.3

* **Browser:** Chrome
 
* **Language:** TypeScript 2.1.6

* **Node (for AoT issues):** `node --version` =   v6.10.0

**Comment by DzmitryShylovich** [comment]
Duplicate https://github.com/angular/angular/issues/13008 ?

**Comment by karlhaas** [comment]
@DzmitryShylovich it seems to be related but we can successfully transpile using ngc to generate the factories. It also works if we load one full app from our lib.bundle.js. It seems to be a problem in combination how SystemJS resolves the paths. It tries to load the files from the same location as it does without AOT. Without AOT (with absolute imports) we can use a path mapping in our SystemJS configuration in order to tell SystemJS to look for modules with an absolute path starting with @our-lib.

When using ngc (and relative imports) the same path mapping does not work anymore. It seems that SystemJS tries to apply the path mappings on the relative path. It can't replace the path and does not find a registered module and then requests the module from the server ...

**Comment by fulls1z3** [comment]
Hi @karlhaas @DzmitryShylovich, I can reproduce the same issue using **webpack** and **ngtools** (*AoT compilation*) right over here. So, it's not just `SystemJS` specific.

The interesting point is, It also affects `templateUrl`, `styleUrls` resolution using `paths` from `tsconfig.json`.

I know there's a topic about avoiding use of **non-relative** URL's in `templateUrl`, `styleUrls`, but resolving this issue might lead into ability to use paths` from `tsconfig.json` to resolve `templateUrl`, `styleUrls` - in **AoT**.

**Comment by karlhaas** [comment]
Currently we replace the relative paths by absolute paths after the ngc step and before we build the bundles. This works but should not be the final solution.

**Comment by JoostK** [comment]
The Ivy compiler will always refer to absolute module imports using that absolute module name, so I believe this has been resolved.
