### ISSUE TITLE
ViewEncapusulation doesn't work as expected when assigning css styles.... VE.Native and VE.None produce intended results but not VE.Emulated (default)

### ISSUE THREAD

**Issue by xtianus79** [angular/angular#15312]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When assigning a component's corresponding style or stylesURL to a component and that component has component(s) templated into the dom the styles don't get picked up in time for the styling to take place on the templated html... 

I assumed encapsulation was the primary cause so i changed the the encapsulation parameter in the parent component to these 3 choices... 

encapsulation: ViewEncapsulation.None
encapsulation: ViewEncapsulation.Native
encapsulation: ViewEncapsulation.Emulated // (default)

The third, which is the default i.e. as if they didn't post the parameter in the first place does not attach the styling to the child/templated component

So therefore, the styling doesn't take hold.  The initial reaction is to place it with !important tags via the global styling but that isn't necessarily desirable. 

oddly, .Native and even .None work as intended.... I can understand .Native but .None?

**Expected behavior**

The styles would attach to the shadow dom tree even with the default VE

**Minimal reproduction of the problem with instructions**

have a child template component with styling and try to add styling effecting that template via the main components style tree 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Mac OS
* **Angular version:** 2.0.X

2.4.8
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5 from Typescript 2.+
* **Node (for AoT issues):** `node --version` =   
Node 7.22+

**Comment by DzmitryShylovich** [comment]
Please add a plunkr

**Comment by xtianus79** [comment]
@DzmitryShylovich the difficultish part about plunkr is adding the parts to do what you are attempting to do... For example, How do I add a node package to my plunkr?

**Comment by DzmitryShylovich** [comment]
Why do you need a node package? 

You can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point

We don't need your real code. The easier you make it for us the more likely we will be able to get to the bottom and have a fix for you.

**Comment by xtianus79** [comment]
@IgorMinar @DzmitryShylovich I created a plunkr that illustrates the issue nicely.  In fact, the same thing is happening in verison 2 and angular version 4.  

here is the plunkr.  https://plnkr.co/edit/ih37qJ?p=preview

as you see 

`
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.Emulation
})
` 
if you set the VE to none or native it works fine.

**Comment by DzmitryShylovich** [comment]
@xtianus79 
> encapsulation: ViewEncapsulation.Emulation

it's `Emulated` not `Emulation`

**Comment by xtianus79** [comment]
@DzmitryShylovich Sorry about that I have since updated it.  It is Emulated now but the effect is the same.  and I could swear it was emulations.

**Comment by xtianus79** [comment]
Also, I fixed the plunkr... it wasn't working when I gave the Test component it's own css file.  

https://plnkr.co/edit/9o0oNz?p=preview

As you see in this plunkr the Emulated provides this to the class... However, in None or Native the effect is different

`
.div-box[_ngcontent-kuo-0] {
    background-color: lightblue;
    width: 400px;
    margin-bottom: 20px;
}
` 

None or Native the style results to this... and is not attached with a component specific extension

`
.div-box {
    background-color: lightblue;
    width: 400px;
    margin-bottom: 20px;
}
`

So, what I see from this is that the emulated dom will attach a style to the head tag which only works for the emulated component... no child components... 

If I do none or native the style is in the style sheet and works for everything.  

I would like to hear you guy's direction on this because Emulated is technically the default.  

I think the fix is how the style tags are added to the dom upon final render.  

Also, I would like to know if there are performance benefits for going for none rather than native or emulated?  Can you guys speak to this.  

Lastly, what is the proposed plan of solution for this issue/bug

**Comment by xtianus79** [comment]
Ok I have added a 3rd box now to the child using only the child's css... Here are my findings.  Obviously the child is going to be VE Emulated for this scenario. 

so with None:
Box A styled 
Box B Styled
Box C Styled (because the emulation is via the child component

with Emulated: 
Box A Styled
Box B non-styled
Box C Styled (*same as above)

***With Native: 
Box A Styled
Box B Styled
Box C non-styled (this is peculiar)

My thought here is that the encapsulation would have worked again for the child component but alas it does not.  The style header isn't implemented and the resultant correlating styles for the child component are ignored in the case of native.  

The good part of having a style with encapsulation.Native is not useful here because the children components will lose their inherent styles.

**Comment by xtianus79** [comment]
I don't know how this is supposed to work officially but here is my suggestion. 

1st. Viewencapsulation for Emulated and Native should work exactly the same. (broken)

2nd.  None should be a sure fire way to not use shadow dom and collects styles based on what the style sheet illustrates (currently working.) 

3rd.  Placing a css style via the component level should always win and thus be the style of priority.  Even when that said style is from a class placed on a subordinate component class i.e. child class.  (broken)  

    3a.  If I have a class on a child component of a parent component called ExampleClass1  and there is either default styling or no styling for that class via the child's component associated css it should come succumb to the parent's associated component css. 

          3ai.  Specifically, a parents associated component css should win all the time.  In the case of the "Emulated" VE the inserted and then tagged css style should be present for underlying styles.  It should wait until the DOM loads and assure that it is placing the style defined or redefined by the parent into the DOM.  

4.  If there is an associated style with the child and not the parent this should be persisted through to the parent.  Currently, this is working for VE Native but broken for VE Emulated.  

    4a.  Currently, if there is a child associated component style it will work for the VE Native but in VE Emulated the style doesn't appear because that associated component style doesn't persist through to any other component but unto itself.  

Perhaps I am forgetting another scenario but this should cover the issues and concerns and what would be needed to properly fix this.

**Comment by xtianus79** [comment]
Wanted to add an update on this topic as there has been a change.... 

Native now acts exactly as the default/none. 

Here is the new plunkr 

https://plnkr.co/edit/Cae3LD?p=preview

No longer is the Native Box C not styled.  It inherently picks up the style from the parent and adds it to the original css and thus having it available for the third box C.  

***With Native:
Box A Styled
Box B Styled
Box C non-styled (this is peculiar)

But, viewencapsulation.Native and .Emulated are still not at parity.  

with Emulated:
Box A Styled
Box B non-styled
Box C Styled (*same as above)  // the same as before. 

What this is means is that the style from the child ts file that is trying to reference a parent css style is not being picked up... thus the Box B is still not styled. 

What does this mean for part 3 from above?  To me this is the most important part

> 3rd. Placing a css style via the component level should always win and thus be the style of priority. Even when that said style is from a class placed on a subordinate component class i.e. child class. (broken)

In this case I made a new plnkr but took the same css from the parent and placed it on the child and added a different background to the child to see what would happen.

Here is the plnkr 

https://plnkr.co/edit/P3su0w?p=preview

Here was the result.  Everything acted the same!!! 

which is encouraging.  

Digging in I found the following: 

For V.Emulated the style is now on the child so it worked accordingly. 

For V.Native The parent style was added to the main css but the specific child style was apart of the localized component styling being picked up from the child component.  <<<!!! this to me is how it should work!!! And thus why as of now .Native is still the best option.  

**Should Emulated work the same as .Native?**  I still argue this is the best way to handle the situation.  

Your thoughts 

@IgorMinar @DzmitryShylovich

**Comment by xtianus79** [comment]
Any update on this?

**Comment by petebacondarwin** [comment]
So things have moved on... there is no longer a `.Native` mode. It was replaced by the `.ShadowDom` mode.
Closing since, as far I as can tell, this is all working as expected in the latest Angular: https://stackblitz.com/edit/angular-ivy-cajkkq.
If there is still a problem @xtianus79 - please create a new issue with a repro from the latest Angular.
