### ISSUE TITLE
Safari Router Bug: Reused Component scrolls to top on Router.navigate

### ISSUE THREAD

**Issue by denisyilmaz** [angular/angular#15313]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a Component that is used for multiple depth of Router …

```typescript
{
    path: ':lang',
    component: PageComponent,
    canActivate: [CanActivateLanguage],
    children:  [
        {   path: '',
            component: MainComponent,
            resolve: { […] }                    },
        {   path: ':type',
            component: MainComponent,
            resolve: { […] }                    },
        {   path: ':type/:slug',
            component: MainComponent,
            resolve: { […] }                    }
    ]
}
```
… when navigating from ":lang/:type/:slug" to another ":lang/:type:slug2" the current scroll keeps at the same position as expected. But if I'm navigation from ":lang/:type/:slug" to ":lang/:type" or ":lang/" the component scrolls to the top of the page. 

**Expected behavior**
In Chrome everything seems to work fine. The scroll position is kept even with routing from ":lang/:type/:slug" to ":lang"

* **Angular version:** 4.0.0-rc.2 (downgraded because of animation bug in rc.5 – same error there)

* **Browser:**
Safari 10.0.3

**Comment by DzmitryShylovich** [comment]
Please reproduce in plunkr. You can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point. thanks

**Comment by denisyilmaz** [comment]
here is a plunkr that shows the bug appearing only in safari:

http://plnkr.co/edit/ZxkQ8W10wUwgatIkIjX7?p=preview

1. click on any link "test" and "slug", scroll down, try again. the scroll stays at the correct position
2. click on "home" link while not on top scroll.
>> in chrome: scrolling stays at the right position.
>> in Safari: scrolling jumps almost to top

tested in Safari 10.0.3 and Chrome 57.0.2987.110

![scrollpositon in safari after home click](https://cloud.githubusercontent.com/assets/4189607/24148126/be275f86-0e3d-11e7-82a7-d22349709d91.jpg)

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by denisyilmaz** [comment]
Thanks for closing, forgot to close the issue here.
For everyone searching for answers to this question: Error was finally solved using custom RouteReuseStrategy (or in other words error was due to missing custom RouteReuseStrategy … ).
