### ISSUE TITLE
Source maps for @angular/upgrade are missing

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#15314]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```
See: https://github.com/angular/upgrade-builds/tree/4.0.0-rc.5%2B80075af/%40angular

**Please tell us about your environment:**

* **Angular version:** 4.0.0-rc.5

**Comment by jasonaden** [comment]
Fixed by deleting bogus .gitignore from angular/upgrade-builds repo.
