### ISSUE TITLE
Provide service when dynamically compiling modules

### ISSUE THREAD

**Issue by todudotivu27** [angular/angular#15317]
[x] feature request

**Current behavior**
I have a module that I am dynamically importing and compiling. I am able to compile and render components using compileModuleAndAllComponentsSync. However if any of the components reference a provided service (in the same module) I get the following:

```
No provider for ApplicationService!
```

**Expected behavior**
When dynamically compiling a module it should resolve any provided services.

**Minimal reproduction of the problem with instructions**

```
// Module is imported and available in the importedModule variable

const mod = this.compiler.compileModuleAndAllComponentsSync(<any>importedModule);

const factory = mod.componentFactories.find((comp) =>
    comp.componentType === route.component
);

const component = this.container.createComponent(factory);
```

The above works and displays the component. However, If I attempt to inject a service in the constructor of the component, using the below I get the "No provider" error:

```
constructor(private applicationService:ApplicationService) {
}
```

I am providing the service in the same module that is being dynamically imported:

```
@NgModule({
...
providers: [
    ApplicationService
  ]
})
export class TestModule {
}
```

The service:

```
@Injectable()
export class ApplicationService {
}
```

**What is the motivation / use case for changing the behavior?**
I need to dynamically load modules at runtime that make use of services.

**Please tell us about your environment:**

Angular 2
Webpack 2

* **Angular version:** 2.4.1

* **Browser:** all
 
* **Language:** Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =  v5.8.0

**Comment by DzmitryShylovich** [comment]
Please reproduce in plunkr. You can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point

**Comment by todudotivu27** [comment]
Upon further investigation I was able to get this working using a parent injector.
Closing this issue due to the functionality already existing.

**Comment by hrfarrokh** [comment]
hi
i have this issue too.
what did yo do?
what is your solution

please share us

**Comment by hrfarrokh** [comment]
@todudotivu27
