### ISSUE TITLE
resolveRedirectTo lacks documentation

### ISSUE THREAD

**Issue by tsclaus** [angular/angular#15316]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
resolveRedirectTo lacks specific documentation regarding how the dependencies are injected, but as far as I can tell they are supposed to be specified as arguments to the function, however I'm not sure if there is alternate injection syntax, but if the function argument names are the only way to inject them it might cause problems with minification, though minifiers as new as the resolveRedirectTo option should be able to handle it.

**Expected behavior**
resolveRedirectTo's documentation for when it fires the $routeChangeError event should include the condition if any of the dependencies fail to inject (for instance you pass as an argument name a factory name that doesn't exist)

**Minimal reproduction of the problem with instructions**
From the docs: `If the function throws an error or the returned promise gets rejected, no further processing will take place and the $routeChangeError event will be fired.` This does not reference the dependency injection option and merely referring to `resolve`'s documentation does not fully confer understanding of the possible error.

**What is the motivation / use case for changing the behavior?**
The resolveRedirectTo option is one of the most powerful parts of $routeProvider but lacks the necessary documentation for people to use it effectively.

* **Angular version:** 2.0.X
The quoted documentation excerpt is from master documentation

**Comment by DzmitryShylovich** [comment]
this is angular 2 repo

**Comment by tsclaus** [comment]
My mistake I will copy it to Angular 1.

**Comment by DzmitryShylovich** [comment]
@tsclaus close this one please. thanks
