### ISSUE TITLE
Checkbox doesn't pass value (checked) in the webworker

### ISSUE THREAD

**Issue by mdaveynis** [angular/angular#15329]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
input[type=checkbox] control doesn't pass value checked to webworker

**Expected behavior**
event.target.checked should be passed to webworker for checkbox control

**Minimal reproduction of the problem with instructions**
```ts
import { Component } from '@angular/core';
@Component({
  selector: 'my-app',
  template: `<label><input type="checkbox" [(ngModel)]="testCheckbox" />Test Checkbox</label><h2>Checked={{testCheckbox}}</h2>`
})`
export class AppComponent {
  testCheckbox = true;
}
```
After clicking check box "Checked=" is cleared. Can be fixed by adding following to addTarget(e, serializeEvent) of event_serializer.ts:
```ts
if (target.checked !== undefined) {
    serializedEvent['target']['checked'] = target.checked;
}
```

**What is the motivation / use case for changing the behavior?**
Use checkbox in webworker until #3374 is implemented

**Please tell us about your environment:**

* **Angular version:** 4.0.0-rc.5

* **Browser:** all

 
* **Language:** TypeScript 2.1.6

* **Node (for AoT issues):** `node --version` = 5.3.0

**Comment by AndrewKushnir** [comment]
As of Angular version 8, all `platform-webworker` APIs are deprecated (see [deprecations page](https://angular.io/guide/deprecations#running-angular-applications-in-platform-webworker) for additional info), so I'm closing this ticket. Thank you.
