### ISSUE TITLE
valueAsDate is not sent to webworker for input[type=date] control

### ISSUE THREAD

**Issue by mdaveynis** [angular/angular#15330]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
input[type=date] control doesn't pass value valueAsDate to webworker

**Expected behavior**
event.target.valueAsDate to be passed to webworker for input[type=date] control

**Minimal reproduction of the problem with instructions**
```ts
import { Component } from '@angular/core';
@Component({
  selector: 'my-app',
 template: `<input type="date" [valueAsDate]="testDate_valueAsDate" (change)="onChange($event.target.valueAsDate)" /><h2>testDate_valueAsDate={{testDate_valueAsDate}}</h2>
`
})
export class AppComponent {
  testDate_valueAsDate = new Date(2016, 2, 15);

  onChange(newDate: Date) {
    if(newDate != null) {
      this.testDate_valueAsDate = newDate;
    }
  }
}
```
After changing date value of testDate_valueAsDate is not updated. Can be fixed by adding following to addTarget(e, serializeEvent) of event_serializer.ts:
```ts
if (target.valueAsDate !== undefined) {
    serializedEvent['target']['valueAsDate'] = target.valueAsDate;
}
```
**What is the motivation / use case for changing the behavior?**
Use valueAsDate in webworker until #3374 is implemented

**Please tell us about your environment:**

* **Angular version:** 4.0.0-rc.5

* **Browser:** [Chrome | Edge]

 
* **Language:** TypeScript 2.1.6

**Comment by jelbourn** [comment]
Closing all issues related to web-workers since Angular's experimental web-worker renderer has been deprecated and it now being removed completely in Angular v11.
