### ISSUE TITLE
Upload form field

### ISSUE THREAD

**Issue by nomack84** [angular/angular#1533]
Is there any plan to implement some sort of input file field or somehow improve the featureds of the native input file field? In Angular1 the input file field was unsupported by the library, no ng-model and no validation. It'll be really nice to have a component which integrates with the new Form Component allowing to make file uploads. I'm not sure if this is possible, just wanting to know if there is any plan to do something like this.
Regards.

**Comment by markevich** [comment]
What value do you expect to see in the model when choosing the file? base-64 string?

**Comment by nomack84** [comment]
I'm not sure. I just want to know whether is possible to have a better integrated file input. Perhaps is not possible. Perhaps the Angular team have an idea and they want to share it? Just want to know. Maybe they found something new.

**Comment by dcominottim** [comment]
@markevich @nomack84 A Base64 string seems like a useful approach.
