### ISSUE TITLE
Angular 2 : AOT not working with dynamic component load. 

### ISSUE THREAD

**Issue by patelsandiph** [angular/angular#15343]
I am implementing AOT in my angular-2 application, which load dynamic pages initially from landing page.

When it load, it throw error like below.

> No ResourceLoader implementation has been provided

![image](https://cloud.githubusercontent.com/assets/14085973/24144463/534a8876-0e53-11e7-9a48-d2cd40867ac0.png)

**Component declaration** look like below:

`@Component({
selector: 'page1',
templateUrl: 'Page1.html',
})`

**Main.ts**

`import { platformBrowser }    from '@angular/platform-browser';
import { AppModuleNgFactory } from '../aot/configs/Application.ngfactory';
import { COMPILER_PROVIDERS } from '@angular/compiler';

platformBrowser(COMPILER_PROVIDERS).bootstrapModuleFactory(AppModuleNgFactory);`

Note: If i use template instead templateUrl it works, but for long HTML Template is not good

I have also tried: ["Can't read the url" error for angular2 dynamic components with templateUrl](http://stackoverflow.com/questions/39659389/cant-read-the-url-error-for-angular2-dynamic-components-with-templateurl)

any one has idea how to resolve this issue.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by DzmitryShylovich** [comment]
did you read the answers? http://stackoverflow.com/a/39769312

**Comment by patelsandiph** [comment]
Yes, and i have also replied him on same threat as well, no luck for me

**Comment by DzmitryShylovich** [comment]
@patelsandiph so do you want to provide a custom impl of `ResourceLoader`?

**Comment by patelsandiph** [comment]
**@DzmitryShylovich** I wants to run my application which has a component which not available in DOM OR not imported in our mainModule.ts, so when I am going to call that component at runtime it throw me above mention error.

**Comment by DzmitryShylovich** [comment]
remove `COMPILER_PROVIDERS`

**Comment by patelsandiph** [comment]
**@DzmitryShylovich** If I remove `COMPILER_PROVIDERS` it throw error for runtime module not found

**Comment by DzmitryShylovich** [comment]
See http://blog.assaf.co/angular-2-harmony-aot-compilation-with-lazy-jit-2/

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by patelsandiph** [comment]
@Vicb : I think I have provided enough information, if someone has implemented AOT, he/she definately understand my issue like @DzmitryShylovich
