### ISSUE TITLE
Can't provide mock for Renderer during component tests

### ISSUE THREAD

**Issue by nabilnaffar** [angular/angular#15341]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I Have a component which uses the Renderer via dependency injection.
In my component test I provide Renderer mock instead of the real one.
When running the test, the real Renderer is being injected instead of my mock (DebugDomRenderer).

**Expected behavior**

Renderer mock should be injected during the component test instead of the real one.

**Minimal reproduction of the problem with instructions**

1. Use the Renderer in component via DI:
```
import { Component, ElementRef, Renderer } from '@angular/core';

  @Component({
    selector: 'app-main',
    templateUrl: './main.component.html',
    styleUrls: ['./main.component.less']
  }) export class MainComponent {
    @Input() globalInputRef: ElementRef;
    constructor(private renderer:Renderer) {
    }
    setColor() {
      this.renderer.setElementStyle(this.globalInputRef.nativeElement, 'backgroundColor', 'yellow');
    }
  }
```

2. Create renderer mock with spies, inject it on tests:

```
describe('Main component tests', () => {
    let fixture: ComponentFixture<MainComponent>,
        component: MainComponent;

    const rendererMock = jasmine.createSpyObj('rendererMock', ['setElementStyle']); 

    beforeEach(done => {
        TestBed.configureTestingModule({
            declarations: [MainComponent],
            schemas: [NO_ERRORS_SCHEMA]
        }).overrideComponent(MainComponent, {
            set: {
                providers: [
                                     {provide: Renderer, useValue: rendererMock}
                                   ]
            }
        });

        TestBed.compileComponents().then(() => {
            fixture = TestBed.createComponent(MainComponent);
            component = fixture.componentInstance;
            done();
        });
    });

    it('should inject renderer mock', () => {
         component.globalInputRef = {nativeElement: 'nativeElement'};
         component.setColor();
        expect(rendererMock.setElementStyle).toHaveBeenCalled();
    });
});
```

Karma fails because it tries to call real functions from the real Renderer (DebugDomRenderer).

Workaround:
Inject the Injector, and use it to inject the Renderer:
in MainComponent class:
```
constructor(injector:Injector) {
   this.renderer = injector.get(Renderer);
}
```

**What is the motivation / use case for changing the behavior?**

Isolating my component from outer services/modules during tests.

**Please tell us about your environment:**

OS: macOS Sierra 10.12.1 
IDE: WebStorm
npm: v4.1.1
* **Angular version:** 2.1.0

* **Browser:** all

 
* **Language:** TypeScript 2.0.7

* **Node (for AoT issues):** `node --version` =  v6.9.2

**Comment by DzmitryShylovich** [comment]
This is by design. You can't override renderer per component. 
Only like this [link](https://blog.nrwl.io/experiments-with-angular-renderers-c5f647d4fd9e)  `Building a Custom Renderer` section

**Comment by nabilnaffar** [comment]
@DzmitryShylovich Thanks for the quick respond! I ended up creating my own custom renderer with spies for tests.

```
let rendererMock = jasmine.createSpyObj('rendererMock', ['selectRootElement',
        'createElement',
        'createViewRoot',
        'createText',
        'setElementProperty',
        'setElementAttribute',
        'setText',
        'setBindingDebugInfo',
        'createTemplateAnchor',
        'projectNodes',
        'attachViewAfter',
        'detachView',
        'destroyView',
        'listen',
        'listenGlobal',
        'setElementClass',
        'setElementStyle',
        'invokeElementMethod',
        'animate']);

    let rootRendererMock =  {
        renderComponent: () => {
            return rendererMock;
        }
    };

    TestBed.configureTestingModule({
            declarations: [MainComponent],
            schemas: [NO_ERRORS_SCHEMA],
            providers: [
                { provide: RootRenderer, useValue: rootRendererMock }
            ]
        });

```

**Comment by jakefreeberg** [comment]
`const renderer2Mock = jasmine.createSpyObj('rendererMock', [
  'destroy',
  'createElement',
  'createComment',
  'createText',
  'destroyNode',
  'appendChild',
  'insertBefore',
  'removeChild',
  'selectRootElement',
  'parentNode',
  'nextSibling',
  'setAttribute',
  'removeAttribute',
  'addClass',
  'removeClass',
  'setStyle',
  'removeStyle',
  'setProperty',
  'setValue',
  'listen'
]);

const rootRendererMock =  {
  renderComponent: () => {
      return renderer2Mock;
  }
};`

**Comment by blackholegalaxy** [comment]
@jakefreeberg where exactly do you use it? Only on the component-you-want-to-test spec file or at a higher level?

**Comment by gkamperis** [comment]
The above did not work for me on Angular v6.

Instead of mocking the renderer try to hijack it...

In your component.spec.ts

    let renderer2: Renderer2;
    ...
    beforeEach(async( () => {
       TestBed.configureTestingModule({
          ...
          providers: [Renderer2]
       }).compileComponents();
    }));

    beforeEach(() => {
       fixture = TestBed.createComponent(YourComponent);
       // grab the renderer
       renderer2 = fixture.componentRef.injector.get<Renderer2>(Renderer2 as Type<Renderer2>);
       // and spy on it
       spyOn(renderer2, 'addClass').and.callThrough();
       // or replace
       spyOn(renderer2, 'addClass').and.callFake(..);
       // etc
    });

    it('should call renderer', () => {
        expect(renderer2.addClass).toHaveBeenCalledWith(jasmine.any(Object), 'css-class');
    });

**Comment by danieldanielecki** [comment]
With any of these methods can't make it working on Jest 23 & Angular 7. Getting all the time the same error 

> TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.


**component.ts**
```
const icosahedron = document.getElementById('renderIcosahedron');
this.renderer2.appendChild(icosahedron, this.renderer.domElement);
```
