### ISSUE TITLE
how to handle instagram redirecturl response using angular 2 in mvc 

### ISSUE THREAD

**Issue by vipulupadhyay** [angular/angular#15345]
I have create one project using angular 2 in mvc.I want to integrate instagram api.but at the time of login instagram resond on redirect url ..at this time i got error ..how to handle this which one get back call to our project action url

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by IgorMinar** [comment]
+1
