### ISSUE TITLE
[platform-server] vague error when entire URL is not provided for Http

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular#15349]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[x] (or) feature request
```

**Current behavior**
When calling a rest local rest API for example /api/getproducts, the server Http throws a vague error 

```
ERROR { Error: Uncaught (in promise): Error at resolvePromise
```

Providing the entire URL fixes it: (but user would never know to do this)

    this.http.get('http://localhost:5000/API/test') 

**Expected behavior**

Previously (angular2-universal) we set the origin-URL for the user in these situations, so if we *don't* want to add that same behavior, 
we need to make sure to Throw a more specific error letting the Dev know why the server didn't render that Http response. (Note the rest of the app actually renders it doesn't break rendering).

Also Docs should reflect whatever we decide to do here as well, to prevent confusion.

**Minimal reproduction of the problem with instructions**

    this.http.get('/API/test') 

**What is the motivation / use case for changing the behavior?**
Previous Users of Universal might be confused why his existing functionality doesn't work anymore, especially if not given a good Error message explaining it.

* **Angular version:** 4.0.0.rc5 (or nightly build)

CC/ @vikerman @alxhub @gdi2290

**Comment by hheexx** [comment]
@MarkPieszak @alxhub 
What is recommended way to do http now ?

**Comment by MarkPieszak** [comment]
Well in Angular2-universal we assumed it was localhost if you didn't provide a full URL. The server doesn't handle relative URLs so the whole must be provided there.

In the providers you pass into the ngAspnetCoreEngine [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/angular4.0-NEW-wip/Client/boot-server.ts#L15-L21), just pass in another Provider there, that has the Origin URL. Have all your Http calls prepend it automatically.

Most cases people are using external Rest endpoints anyway, it's not often they're served from the same location.

**Comment by hheexx** [comment]
That is exactly what I have done. Thanks.
```
    const providers = [{
        provide: INITIAL_CONFIG,
        useValue: {
            document: '<app></app>', // Our Root application document
            url: params.url
        }
    },
    {
        provide: 'ajaxHost',
        useValue: params.origin
    }
    ];
```

**Comment by PickRelated** [comment]
What about people using ngx-translate? It uses relative URL to get translation file.
