### ISSUE TITLE
'Error: ngModule should be provided' during http requests

### ISSUE THREAD

**Issue by Sky4CE** [angular/angular#15342]
**I'm submitting a bug**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After updating from 4.0.0-rc.3 to 4.0.0-rc.5 all http requests throw error:
![image](https://cloud.githubusercontent.com/assets/9821633/24143959/35c2dfa2-0e34-11e7-8738-547060bf1847.png)
in fact requests are work fine, but spam console with these errors.
I'm doing just simple http requests without any fancy stuff, for example:
```this.http.post(`${this._rootPath}/email/confirmation/send`, model)```

**Expected behavior**

No errors should be thrown.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Keep console clean from buggy errors.

**Please tell us about your environment:**

OS: Windows 10 x64
IDE: Visual Studio 2017
npm: v4.3.0

* **Angular version:** 4.0.0-rc.5

* **Browser:** all

 
* **Language:** TypeScript 2.2.1

* **Node (for AoT issues):** `node --version` =  v7.7.0

**Comment by DzmitryShylovich** [comment]
Related to https://github.com/angular/angular/issues/15241

**Comment by DzmitryShylovich** [comment]
@Sky4CE are you sure it's http related? I can't reproduce http://plnkr.co/edit/hAjB450PO0qgPtEBq3Nd?p=preview

**Comment by Sky4CE** [comment]
@DzmitryShylovich thanks for help, I figured it out. The problem not in http indeed. I have angular2-busy third party lib in my project and seems like it throw this error. And as I understand that lib doing exactly the same things as guy in #15241. So I hope this situation will be fixed by angular team, because I'm strongly rely on angular2-busy in my project to show spinners.
