### ISSUE TITLE
NgIf live demo still uses `ng-if` syntax

### ISSUE THREAD

**Issue by zoechi** [angular/angular#15348]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Plunker linked to in https://angular.io/docs/ts/latest/api/common/index/NgIf-directive.html
still uses `ng-if` syntax.

**Expected behavior**

should be updated to current syntax

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by kylecordes** [comment]
That plunkr is also based on alpha.37... Does that old syntax even work at all with current Angular?

**Comment by zoechi** [comment]
No, with recent Angular versions this only throws.

**Comment by DzmitryShylovich** [comment]
@zoechi it's already fixed in 4.x https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_if.ts
