### ISSUE TITLE
Precompute the light dom insertion points in emulated shadow DOM

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1535]
Currently the Emulated ShadowDOM runs `.querySelectorAll` during distribution. Turns out that the selectors in the `<content>` are simple selectors which are identical to the selectors we use in the directives. This means that if we know the selectors ahead of time (which we do by looking at the component's template) we can precompute the nodes which will need to be distributed and don't need to execute the `.querySelectorAll`

**Comment by mhevery** [comment]
@vsavkin, @tbosch can you comment on this?

**Comment by tbosch** [comment]
No, we don't do querySelectorAll but use `DOM.matchesSelector()` (see
https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/shadow_dom/light_dom.js#L128
).

With this, we cannot compile a single component template in isolation any
more, as we need to mark the content in the light dom depending on the
selectors on the content elements in the shadow dom. Also, when integrating
with imperative views this could be troublesome...
