### ISSUE TITLE
Local notifications with audio

### ISSUE THREAD

**Issue by anivaisu** [angular/angular#15353]
Hi all,

I am beginner in ionic 2.

I am used localnotification in ionic 2.

Here is my app.component file

import { Component } from '@angular/core';
import { Platform,AlertController } from 'ionic-angular';
import { StatusBar, Splashscreen } from 'ionic-native';
import { HomePage } from '../pages/home/home';
import { AngularFire} from 'angularfire2'
import {LocalNotifications} from 'ionic-native';
import { AudioProvider } from 'ionic-audio';
@Component({
templateUrl: 'app.html'
})
export class MyApp {
rootPage = HomePage;
audio;
//playSelectedTrack:any;
constructor(private _audioProvider: AudioProvider,private AlertController:AlertController,platform: Platform,public af:AngularFire,) {
//this.audio=new Audio();
this.audio='https://ia800406.us.archive.org/16/items/JM2013-10-05.flac16/V0/jm2013-10-05-t30-MP3-V0.mp3';
platform.ready().then(() => {
// Okay, so the platform is ready and our plugins are available.
// Here you can do any higher level native things you might need.
StatusBar.styleDefault();
Splashscreen.hide();
this.af.database.list('/notifications').subscribe(data=>{
console.log("firebase collection");
console.log(data);
if(data[0].STATUS === 'opened')
{
var length=data[0].STATUS;
console.log("STATUS OPENED");
console.log(length);
this.schedule();
LocalNotifications.on("click", (notification, state) => {
let alert = this.AlertController.create({
title: "Notification Clicked",
subTitle: "You just clicked the scheduled notification",
buttons: [{
text: "exit?",
handler: () => { this.playSelectedTrack() }
}]
});
alert.present();
});
}
})
});
}

schedule()
{

LocalNotifications.schedule({
        title: "Test Title",
        text: "You have new notification",
        at: new Date(new Date().getTime() + 5 * 1000),
        sound:this.playSelectedTrack(),
    })
}

playSelectedTrack():any{
var audio=new Audio();
audio.src = 'https://ia800406.us.archive.org/16/items/JM2013-10-05.flac16/V0/jm2013-10-05-t30-MP3-V0.mp3';
if(audio.paused)
{
console.log("play")
audio.play();
}
else{
console.log("pause");
audio.pause();
}
}
}

It'work perfectly.My app received notifications play audio file.when on click notifications diplay alert.and click OK button does not pause audio file.

How to fix this problem.

Kindly advice me,

Thanks

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
