### ISSUE TITLE
Angular 4.x regression with embedded view handling

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#15352]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Minimal reproduction of the problem with instructions**

This was discovered when switching ng-bootstrap to Angular 4 rc.5. Here is a plunker that works with the latest 2.3.x but fails when switching to Angular 4 rc.5:

http://plnkr.co/edit/Ha2UMEOc3pT2jUpg1Mjf?p=preview

Steps to reproduce:
- hover over stars and mouseleave - see that the care comes back to the initial value
- switch to 4.0.0-rc.5 in the `config.js` and repeat the scenario - see that with 4.0.0-rc.5 rating doesn't come back to the initial version on mouseleave 

You can see the code for the rating directive here: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/rating/rating.ts

I'm working on a reduced reproduction scenario but wanted to open an issue ASAP as an "early warning". Currently my suspicion is that sth goes wrong when creating embedded views (or more precisely - refreshing them when context changes). I will provide a smaller reproduce as soon as I can narrow it down.

* **Angular version:** 2.0.X

4.0.0-rc.5

* **Browser:** 

all
 
* **Language:** 

TypeScript

**Comment by vicb** [comment]
expected vs observed behavior ?

**Comment by pkozlowski-opensource** [comment]
> expected vs observed behavior ?

Observed: using 4.0.0-rc.5 when you hover over stars (mouseenter and mouseleve without click) the highlighted rating comes doesn't come back to the initial;

Expected: hovering overs stars without clicking should display initial rating on mouseleve.

@vicb sorry for not having a smaller reproduce scenario atm, I'm trying to isolate it as we speak. What I'm seeing is that refreshing a property on a context passed to an embedded template doesn't refresh the template bindings. But in ratings there are multiple levels of embedded views involved so I'm trying to come up with a minimal reproduce.

In any case there is a scenario that used to work just fine in 2.4.x and fails in 4.x and we are not doing anything too crazy. 

Let me try to reproduce it in a simpler way

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource have you tried without OnPush?

**Comment by pkozlowski-opensource** [comment]
@vicb here is a minimal plunker: http://plnkr.co/edit/eJ8XjQJHeZyFzvLDWV64?p=preview

**Observed**: clicking on a text node _doesn't_ increment numbers

**Expected**: clicking on a text node increment numbers

@DzmitryShylovich good path: in fact this is a combination of a host listener + OnPush.

**Comment by tbosch** [comment]
@pkozlowski-opensource could you try https://github.com/angular/angular/pull/15359?

**Comment by pkozlowski-opensource** [comment]
@tbosch I can confirm that your PR #15359 fixes the issue: http://plnkr.co/edit/ZZK6szqSUvc7YnsknXfs?p=preview

Many thnx for looking into it and extremely fast turnaround on this one!
