### ISSUE TITLE
Issue in loading APK created using cordova for an Angular 2 application

### ISSUE THREAD

**Issue by usersk12** [angular/angular#15354]
I've created an Angular 2 Typescript application. I'm building this application to create an APK using Cordova. The APK is built successfully but when i try to run the APK on Android emulator, it gets stuck at Loading.. page and application is not bootstrapped.
Kindly provide help with above issue, if it has something to do with Angular 2 version. I'm using Angular 2.4.9.

I'm using Windows 8.1 and Android Studio 2.3 on Windows. The application is developed using TypeScript 2.0.3. The node version and npm versions are v6.9.4 and v3.10.10 respectively.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
