### ISSUE TITLE
LOCALE_ID provider gets called before APP_INITIALIZER provider

### ISSUE THREAD

**Issue by ctrl-brk** [angular/angular#15369]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In order to set LOCALE_ID in the application module (can I?) I need to reach a web service to obtain the value. Usually you can do such things in APP_INITIALIZER, but it looks like LOCALE_ID gets called before APP_INITIALIZER.

**Expected behavior**

Set LOCALE_ID after APP_INITIALIZER

* **Angular version:** 4.0.0-rc.5

**Comment by DzmitryShylovich** [comment]
Please reproduce in plunkr. You can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point

**Comment by ctrl-brk** [comment]
Here it is https://embed.plnkr.co/F5KqOA/

The date should be in D.M.YYYY format but it's in your local locale.

**Comment by DzmitryShylovich** [comment]
@ctrl-brk https://plnkr.co/edit/pHqPFAEU6YuzZvbKXrBV?p=preview

**Comment by ctrl-brk** [comment]
I have no idea what's wrong here, but for me localeFactory() never gets called

**Comment by DzmitryShylovich** [comment]
in plunkr or in your real app?

**Comment by ctrl-brk** [comment]
In real app. That's why I thought I need to use useValue instead

**Comment by DzmitryShylovich** [comment]
it works in plunkr so this is not an angular bug

**Comment by ctrl-brk** [comment]
You never know )) It might work when you don't have any additional stuff there.

Any clue why that might not being called?

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/cWHqA1Ns8KuIVohzzBsi?p=preview here's another option. preload locale before bootstrap

**Comment by ctrl-brk** [comment]
Interesting, thank you. Can I use useFactory this way? I tried but it's not getting called ))

**Comment by ctrl-brk** [comment]
Well again, of course it works in your plunker just not in my app. I'm clueless here ((

**Comment by DzmitryShylovich** [comment]
it's a mistake somewhere on you side. it must work

**Comment by ctrl-brk** [comment]
Ok, looks like it's an angular-cli issue. Just created a new project, added these 2 providers to it. Init works, Locale doesn't.

**Comment by DzmitryShylovich** [comment]
Try it out here https://github.com/AngularClass/angular2-webpack-starter or here https://github.com/qdouble/angular-webpack2-starter

If it does work there re-open this on https://github.com/angular/angular-cli/issues

**Comment by ctrl-brk** [comment]
No it does not. Webpack?

**Comment by DzmitryShylovich** [comment]
I've just tested using https://github.com/qdouble/angular-webpack2-starter and it works perfectly fine. So I have no idea what's your problem

**Comment by Toxicable** [comment]
@ctrl-brk I just tested this https://plnkr.co/edit/pHqPFAEU6YuzZvbKXrBV?p=preview out in a new CLI project and it worked fine apart from your type error in your class called `App`

**Comment by ctrl-brk** [comment]
@DzmitryShylovich, here's my app module. Can you see 'locale' in your console?
```
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import {
  NgModule,
  APP_INITIALIZER, LOCALE_ID, 
  ApplicationRef
} from '@angular/core';
import {
  removeNgStyles,
  createNewHosts,
  createInputTransfer
} from '@angularclass/hmr';
import {
  RouterModule,
  PreloadAllModules
} from '@angular/router';

/*
 * Platform and Environment providers/directives/pipes
 */
import { ENV_PROVIDERS } from './environment';
import { ROUTES } from './app.routes';
// App is our top level component
import { AppComponent } from './app.component';
import { APP_RESOLVER_PROVIDERS } from './app.resolver';
import { AppState, InternalStateType } from './app.service';
import { HomeComponent } from './home';
import { AboutComponent } from './about';
import { NoContentComponent } from './no-content';
import { XLargeDirective } from './home/x-large';

import '../styles/styles.scss';
import '../styles/headings.css';

// Application wide providers
const APP_PROVIDERS = [
  ...APP_RESOLVER_PROVIDERS,
  AppState
];

type StoreType = {
  state: InternalStateType,
  restoreInputValues: () => void,
  disposeOldHosts: () => void
};

/**
 * `AppModule` is the main entry point into Angular2's bootstraping process
 */
@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [
    AppComponent,
    AboutComponent,
    HomeComponent,
    NoContentComponent,
    XLargeDirective
  ],
  imports: [ // import Angular's modules
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(ROUTES, { useHash: true, preloadingStrategy: PreloadAllModules })
  ],
  providers: [ // expose our Services and Providers into Angular's dependency injection
    ENV_PROVIDERS,
    APP_PROVIDERS,
        {
            provide: APP_INITIALIZER,
            useFactory: initFactory1,
            //deps: [ConfigurationService],
            multi: true
        },
        {
            provide: LOCALE_ID,
            useFactory: localeFactory,
        }

  ]
})
export class AppModule {

  constructor(
    public appRef: ApplicationRef,
    public appState: AppState
  ) {}

  public hmrOnInit(store: StoreType) {
    if (!store || !store.state) {
      return;
    }
    console.log('HMR store', JSON.stringify(store, null, 2));
    // set state
    this.appState._state = store.state;
    // set input values
    if ('restoreInputValues' in store) {
      let restoreInputValues = store.restoreInputValues;
      setTimeout(restoreInputValues);
    }

    this.appRef.tick();
    delete store.state;
    delete store.restoreInputValues;
  }

  public hmrOnDestroy(store: StoreType) {
    const cmpLocation = this.appRef.components.map((cmp) => cmp.location.nativeElement);
    // save state
    const state = this.appState._state;
    store.state = state;
    // recreate root elements
    store.disposeOldHosts = createNewHosts(cmpLocation);
    // save input values
    store.restoreInputValues  = createInputTransfer();
    // remove styles
    removeNgStyles();
  }

  public hmrAfterDestroy(store: StoreType) {
    // display new elements
    store.disposeOldHosts();
    delete store.disposeOldHosts;
  }

}

export function initFactory1() {
    return () => {
        console.log('init');
    };
}

export function localeFactory() {
    console.log('locale');
    return "de-DE";
}
```

**Comment by Toxicable** [comment]
@ctrl-brk if you want anyone to run that reduce it to a point where it has none of your internal dependancies

**Comment by ctrl-brk** [comment]
@Toxicable there should be none. Just get angular-webpack2-starter and replace app.module.ts with the code above.

**Comment by Toxicable** [comment]
none of these work
```
import { ENV_PROVIDERS } from './environment';
import { ROUTES } from './app.routes';
// App is our top level component
import { APP_RESOLVER_PROVIDERS } from './app.resolver';
import { AppState, InternalStateType } from './app.service';
import { HomeComponent } from './home';
import { AboutComponent } from './about';
import { NoContentComponent } from './no-content';
import { XLargeDirective } from './home/x-large';
```

**Comment by DzmitryShylovich** [comment]
@ctrl-brk do you use date pipe anywhere? `localeFactory` is not invoked because `LOCALE_ID` is not used

**Comment by ctrl-brk** [comment]
Oh, that explains the issue. I use date pipes in lazy loaded modules but not in the app module.
So, I have to provide it to each module separately? No way to set it globally just once?

**Comment by ctrl-brk** [comment]
@Toxicable, strange because it's not mine. It's a part of https://github.com/qdouble/angular-webpack2-starter. You are probably trying the one from AngularClass? They might be different.

**Comment by Toxicable** [comment]
No im trying with the CLI which has none of those generated components

**Comment by ctrl-brk** [comment]
Oh, I thought you're using starter. Anyway looks like we've identified the issue, now would be nice to be able to set the locale somehow globally.

**Comment by vicb** [comment]
Please re-open an issue with the root cause, not clear to me what is wrong here. Thanks.
