### ISSUE TITLE
[4.0.0-rc.5] The problem that the path of '**' takes precedence over the forChild paths.

### ISSUE THREAD

**Issue by vermilion928** [angular/angular#15379]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

This problem occurred because it was upgraded from Angular 2.4.6 to 4.0.0 rc5.

**Current behavior**
Routing to ChildComponent becomes NoContentComponent.
(The wildcard (**) path takes precedence.)

**Expected behavior**
As before, wildcards should work as fallback(404) paths.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/AHbaKa?p=preview

**What is the motivation / use case for changing the behavior?**
Wildcard routing(**) takes precedence over Routing as 'forChild', when Routing modules are separated.

The wildcard is a fallback function when there is no other way to route.

**Please tell us about your environment:**
@angular/cli: 1.0.0-rc.4
node: 6.9.5
os: linux x64
@angular/animations: 4.0.0-rc.5
@angular/common: 4.0.0-rc.5
@angular/compiler: 4.0.0-rc.5
@angular/core: 4.0.0-rc.5
@angular/forms: 4.0.0-rc.5
@angular/http: 4.0.0-rc.5
@angular/platform-browser: 4.0.0-rc.5
@angular/platform-browser-dynamic: 4.0.0-rc.5
@angular/router: 4.0.0-rc.5
@angular/cli: 1.0.0-rc.4
@angular/compiler-cli: 4.0.0-rc.5

**Comment by DzmitryShylovich** [comment]
Module import order matters https://angular.io/docs/ts/latest/guide/router.html#!#routing-module-order

**Comment by vermilion928** [comment]
@DzmitryShylovich Sure it is written as such.

However, there is a difference from the behavior of 2.4.6.
Which of 4.0.0-rc.5 and 2.4.6 does the correct behavior?

**Comment by DzmitryShylovich** [comment]
I don't see any difference. Here's 4.x example https://plnkr.co/edit/jivSalZX1jxDBlosYOK3?p=preview

**Comment by vermilion928** [comment]
Sorry, it seems that there was a mistake in my reproduction method.

If I can find a way to reproduce this problem I will also make an issue.

I close issue.
Thanks.
