### ISSUE TITLE
Angular 4 / Angular Cli / Universal Services

### ISSUE THREAD

**Issue by kamalkech** [angular/angular#15373]
* **Angular version:** 4

* **OS:** Windows 10
 
I update angular cli and of course i update all in my package check this link

https://github.com/angular/...

But in thidarticle you not explain how implement " import { platformServer, renderModuleFactory } from '@angular/platform-server' " and Rob's example is not a good way for my case, have you any idea ?

**Comment by IgorMinar** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior.

**Comment by kamalkech** [comment]
@IgorMinar : when you try to build an application frontend side with angular 4 we need to improve the SEO so the question is how can use angular universal services which it's already integreted on angular core ??

**Comment by DzmitryShylovich** [comment]
@kamalkech documentation for `platform-server` is a WIP https://github.com/angular/angular.io/pull/3378

**Comment by kamalkech** [comment]
@DzmitryShylovich : so the documention not finish yet ??
