### ISSUE TITLE
Angular 2 - pipes inside ngIf through cross domain

### ISSUE THREAD

**Issue by phil123456** [angular/angular#15388]
[x] bug report 

**Current behavior**

an ngIf div contains piped translations, outside of the ngIf they work, inside of it, it depends (pipes are pure and should then be refreshed when translations arrive)

I load translation inside a service, pipes are all subscribed to an observable from that service so they get notified when translations arrive and refresh themselves

in another service, I load product informations, if I load that json via http, 

- it works when the json is part of the angular project 

- it does not work if the json is on another url (php)

- problem is intermitent (adding an empty line in any file makes the plunkr refresh and sometimes translations show up, sometimes not)

**Expected behavior**

I expect the pipes to refresh every time; they fetch the translations but sometimes nothing gets displayed inside the ngIf div

**Minimal reproduction of the problem with instructions**

the whole problem is in src/data.service.ts, you can see one "does work" line and one "does not work line"

https://plnkr.co/edit/RITJVLa19UvqDhzvXzgs

**What is the motivation / use case for changing the behavior?**
translations through pipes

**Please tell us about your environment:**
DEV : win 7
php server : Apache 2.4 Debian 8.5 PHP 5.6

* **Angular version:** 2.4.0

* **Browser:** Chrome  56.0.2924.87
 
* **Language:** TypeScript (v??) 

angular 2 seed is original seed from official tutorials

**Comment by DzmitryShylovich** [comment]
what are the steps to reproduce? expected vs observed behavior?

**Comment by phil123456** [comment]
everything is there above, what do you need more ?
did you check the plunkr

**Comment by phil123456** [comment]
so ? any idea ?

**Comment by phil123456** [comment]
@IgorMinar hello, did you check it any further ? sheers

**Comment by Toxicable** [comment]
@phil123456 man, that plunker is massive, can you make a it a bit more minimal, all you need is enough code to show the issue, not your entire app

**Comment by phil123456** [comment]
massive ? it's not the entire app
it's really a small trimed version of my app, and since I am not sure what goes wrong

 I put in the trads (2 classes and 1 json) that's all
the data service
and the product component supposed to list the products

really not a big deal (and I am a angular noob)

**Comment by Toxicable** [comment]
@phil123456 for someone trying to debug your code I have 0 idea what's going on. I don't know the exact expected behavior or what im observing and the amount of code in there which is nearly 200 LOC dosen't help, if anything it makes me less likely to continue looking

**Comment by phil123456** [comment]
??? but it does not make any sens, I had to fill the template, dont people see it above ?

**Comment by phil123456** [comment]
- I use piped trads (trads are json loaded, and pipes get notified of the trads via an observer/observable)
- there is a div with an ngIf
- outside of it all trads show up
- inside of it, they dont always show up

check src/data.service.ts, you can see one "does work" line and one "does not work line"

let me know if you need more info, but I already filled tons above, I dont get it

**Comment by DzmitryShylovich** [comment]
We have a lot of issues to look at, the easier you make it for us the more likely we will be able to get to the bottom and have a fix for you.

**Comment by phil123456** [comment]
totaly, that's why I tried to put as much infos as I could, let me know what more you need

**Comment by phil123456** [comment]
@Toxicable  I clearly indicated above (conforming to your template) the current and expected behaviour

**Comment by Toxicable** [comment]
@phil123456 from what I can tell your issues are all around your use of async. I don't actually see why your pipe needs to be inpure here, all it does is take a text input and swaps it for the translated text. Things like loading in the translations should be done either at build time or as the app is starting up the pipe should not have to wait for it. There are no bugs here with Angular

**Comment by phil123456** [comment]
so I can load any json, not translation json ?
this does not make sens

the issue is that my trads files are huge and we have 4 languages, so I wanted to load the trad dynamicaly
otherwise I would have to load the json inside the html page itself , setting the language with php

**Comment by phil123456** [comment]
so maybe I can create some sort of loading page, then use the router to go to the next pages, I'll check this option

**Comment by phil123456** [comment]
sorry to insist on this one, but I get ZERO support everywhere else ....

first, the pispes have the translations(see log in chrome) so they dont wait for anything, when the ngIf is supposed to display, trads are already there

then I tried merging my observables (trads+product data) , I tried using ChangeDetectorRef , I tried zone.run, the trads just dont display, all the data are there, the ngIf just dont refresh itself

also I cant find a way to include json in my web pages without resorting to dynamic (ajax) loading

**Comment by phil123456** [comment]
I finaly nailed it

I added a surounding ngIf on a trads variable

and in my onNgInit :

```
    this.translateService.getTrads()
			.then(response => this.trads=response.json())
            .catch(this.handleError); 

```
in my service :

```
getTrads()
    {
    	return this.http.get("app/translations/"+this.language+".json").toPromise();
    }
```

I got this.translateService.getTrads()
			.then(response => this.trads=response.json())
            .catch(this.handleError); 

```

what frightens me is that I got no idea why it works

**Comment by tytskyi** [comment]
@phil123456 just my guess, but could you look at this https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/core/src/change_detection/change_detection_util.ts#L37

and this https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/common/src/pipes/async_pipe.ts#L88

and check if it helps?

**Comment by phil123456** [comment]
thx mate, I'll have a look

**Comment by vicb** [comment]
If this still a problem ?

**Comment by vicb** [comment]
closing as no feedback after my last comment.
open a new issue if this is still an issue.
