### ISSUE TITLE
Angular2 Testing guide resource example not work : Error with external template

### ISSUE THREAD

**Issue by MrHOY** [angular/angular#15381]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I go to page: [https://angular.io/docs/ts/latest/guide/testing.html#!#live-examples](https://angular.io/docs/ts/latest/guide/testing.html#!#live-examples), and download a resource [A component spec with external template downloadable example](https://angular.io/resources/zips/testing/banner-specs.testing.zip)
Install package:  `npm install`
Run testing:  `npm test`

Image of error
![error](https://cloud.githubusercontent.com/assets/20653706/24185201/650a211e-0f04-11e7-9dce-f95cc9a2246a.jpg)

I see on plnkr it work good but i don't know why it have problem on my computer.

**Please tell us about your environment:**

* **Angular version:** 2.4.5

* **Browser:** [Chrome ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node:** `node --version` =   6.9.2
* **npm:**`npm --version` = 4.1.1

**Comment by DzmitryShylovich** [comment]
Please re-open this on https://github.com/angular/angular.io/issues

**Comment by DzmitryShylovich** [comment]
@MrHOY close this issue please. thanks
