### ISSUE TITLE
 app/angular2.module.ts(5,22): error TS6143: Module '../node_modules/sqlite3' wa  resolved to 'D:/Angularsetup/node_modules/sqlite3/lib/sqlite3.js', but '--allo Js' is not set.

### ISSUE THREAD

**Issue by umapathi20** [angular/angular#15380]
I need to import sqlite3 from node_modules to connect sqlite3 database. Please see the below which is wrriten in app.component.ts

import * as sqlite3 from 'sqlite3';
let db = new sqlite3.Database('../data/database.sqlite');

it throws error when run the npm start command

 app/app.module.ts(5,22): error TS6143: Module '../node_modules/sqlite3' was  resolved to 'D:/Angularsetup/node_modules/sqlite3/lib/sqlite3.js', but '--allo Js' is not set.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
