### ISSUE TITLE
hostProperties binding does not work on dynamically loaded components.

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1539]
```js
dynamicComponentLoader.loadIntoNewLocation(DialogComponent, elementRef, dialogElement);
```

Using `hostProperties` on `DialogComponent` does nothing.

**Comment by jelbourn** [comment]
Also `hostListeners`

**Comment by SekibOmazic** [comment]
`properties` doesn't work either:
#1236

**Comment by vsavkin** [comment]
The `loadedIntoNewLocation` method creates a new element without bindings. So `properties` should not work, but `hostProperties` a `hostListeners` should.

**Comment by vsavkin** [comment]
@tbosch, it looks like it is an issue in the compiler. `compileInHost` does not call `bindHostElementProperty` and `bindEvent` for the "root" view.  Can you help me to fix it on Monday?

**Comment by SekibOmazic** [comment]
@vsavkin In my example I use `loadIntoExistingLocation`. Should `properties` work in that case?

**Comment by vsavkin** [comment]
@SekibOmazic my current thinking is that they should not. The dynamic component should delegate setters to the dynamically-loaded component.

**Comment by tbosch** [comment]
@vsavkin Yes, Monday is good

**Comment by mhevery** [comment]
@vsavkin I think delegation is the right behavior. So is there anything to be done here?

**Comment by vsavkin** [comment]
Mixed via https://github.com/angular/angular/commit/e3c11045bf335b141cc986be411ed7d71dd4ed5b
