### ISSUE TITLE
indexDebugNode() and removeDebugNodeFromIndex() are causing memory leaks in test suites

### ISSUE THREAD

**Issue by Eddman** [angular/angular#15395]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`DebugDomRenderer` calls `removeDebugNodeFromIndex` only for root nodes and ignores children. As results after running 260+ tests Chrome consumes cca. 2 Gb of memory. The underlying map contains huge amount of nodes. (the node is referencing components, view, application and elements/native nodes, these are referencing other parts of DOM, etc.).

**Expected behavior**

After each test run the map should be empty.

**Minimal reproduction of the problem with instructions**

The behavior is observable for each component test. Just put a breakpoint into `removeDebugNodeFromIndex` and run the test.

For test I've modified the method and as result the Chorme is now consuming only cca. 200 Mb:
```javascript
    function removeDebugNodeFromIndex(node) {
        if(!node) {
            return;
        }
        if (node.childNodes) {
            for (var i = 0; i < node.childNodes.length; i++) {
                removeDebugNodeFromIndex(node.childNodes[i]);
            }
        }
        _nativeNodeToDebugNode.delete(node.nativeNode);
    }
```
This works fine, but as result it sometimes removes elements/nodes before the `DebugDomRenderer` does. Therefor the first `null` check. I assume a more sophisticated solution will be needed.

A simple Plunker to test on: http://plnkr.co/edit/MANVAYBe5g4C5P1GGDVj?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.10 (4.0.0-rc.5 seems to work fine, or at least the leak is not that massive)

* **Browser:** all 

 
* **Language:** irrelevant 

* **Node (for AoT issues):** `node --version` =   irrelevant

**Comment by vicb** [comment]
@Eddman please add a quick repro. Thanks.

**Comment by Eddman** [comment]
The minimal reproduction is simple here:
```typescript
@Component({
    template: '<div><div>text</div></div>'
})
export class TestComponent {
}
```
And the test:
```typescript
describe('Sample test', () => {

    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [TestComponent ]
        }).compileComponents();
    }));

    beforeEach(fakeAsync(() => {
        let fixture = TestBed.createComponent(TestComponent );
        fixture.detectChanges();
        tick();
    }));

    if('empty test', ()=> {});
}
```
As indexDebugNode(...) is called for each element and node (both `div` elements and text node) after the test 3 nodes will be in the Map. Only the root element is removed.

**Comment by Eddman** [comment]
For my 260+ tests it generates 100k+ nodes in the Map.

**Comment by Eddman** [comment]
Here it is: http://plnkr.co/edit/MANVAYBe5g4C5P1GGDVj?p=preview

**Comment by leonpanjtar** [comment]
Can anybody please provide more info about when will this be solved?

**Comment by pkozlowski-opensource** [comment]
This is fixed in Angular v9 running ivy
