### ISSUE TITLE
`Error trying to diff ‘[object Object]'` needs to pass the error message

### ISSUE THREAD

**Issue by b264** [angular/angular#15402]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`Error trying to diff ‘[object Object]'` Does not say what the actual error is. Once you get this, the path forward relies on diving into the angular source code since the error message was erased.

**Expected behavior**
`Error trying to diff ‘[object Object]': ReferenceError: Invalid left-hand side in assignment` Does not drop the actual reason there was an exception raised.

**Minimal reproduction of the problem with instructions**
Unknown how to minimally reproduce, specifically because the error message is dropped.  This is in fact, the exact problem.

**What is the motivation / use case for changing the behavior?**
Dedicate time to fixing the problem instead of everyone needing to go into the angular source code when the bug is probably (but don't know) in their own project.

**Please tell us about your environment:**
Ubuntu 16.04LTE, geany 1.27, ionic2

* **Angular version:** 2.2.1

* **Browser:** all
 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =  6.9.2

**Comment by DzmitryShylovich** [comment]
Please provide reproduction in plunkr

**Comment by b264** [comment]
I cannot provide a minimum reproduction because it's private source code and I don't know which part triggers it, because the error is being hidden.  I think the error comes from this line https://github.com/angular/angular/blob/ea49a95bd93c40350f61ceafdab2af5a833e994d/packages/core/src/change_detection/differs/default_iterable_differ.ts#L160

**Comment by DzmitryShylovich** [comment]
> I don't know which part triggers it

debugger? probably ngClass/ngStyle/ngForTrackBy.
we can't fix what we can't reproduce

**Comment by b264** [comment]
Thanks @DzmitryShylovich

**Comment by b264** [comment]
I did figure out that changing `this.data += results;` to

**Comment by DaanTacoSchool** [comment]
I have this curious problem as well. However the error says "DeckEditComponent.html:61 ERROR Error: Error trying to diff '4'. Only arrays and iterables are allowed".

The "4" in question is the value passed in [ngValue]="user.id". When i change the ngValue to "user", the error changes to "trying to diff '[Object object]'". I have not a clue about why the code is trying to diff the ngValue...

**Comment by b264** [comment]
The `[` `]` is why it's trying to diff.  Look at my fix above.  I basically rebuilt the `+=` operator from scratch and it worked.  Why?  Who knows

It doesn't look like the error is coming from that line though.  Is there an ngFor around that, like for user in users or something.  If so, look at users
