### ISSUE TITLE
currency pipe breaks rendering of Googlebot's "Fetch as Google" in Google Search Console

### ISSUE THREAD

**Issue by kblestarge** [angular/angular#15404]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using the "Fetch as Google" tool within the Google Search Console, specifically the Fetch and Render option, the page's dynamically loaded asynchronous content does not show up while the currency pipe is being used within the page. This is how Google renders the page with the pipe:
![screen shot 2017-03-22 at 5 18 23 pm](https://cloud.githubusercontent.com/assets/11730298/24225127/6c38cfd8-0f24-11e7-86b9-b055c8218643.png)

**Expected behavior**

The page should load fine and be rendered by google while the currency pipe is being used. This is how Google renders the page with the pipe commented out:
![screen shot 2017-03-22 at 5 18 45 pm](https://cloud.githubusercontent.com/assets/11730298/24225120/5d369286-0f24-11e7-99f4-2f742b3a62f1.png)

**Minimal reproduction of the problem with instructions**

Use the currency pipe inside of a page that displays dynamically loaded content via a RESTful API, then use the Fetch as Google tool on Google's Search Console. Select the "Fetch and Render" option. Once the fetch and render is complete, view the results. The page will not show any of the dynamically loaded content.

**What is the motivation / use case for changing the behavior?**

SEO optimization

**Please tell us about your environment:**

{npm: '4.0.5',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.4.0',
  openssl: '1.0.2j',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.10.1',
  v8: '5.4.500.45',
  zlib: '1.2.8' }
* **Angular version:** 2.0.X

angular-cli: 1.0.0-beta.28.3
node: 7.4.0
os: linux x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/compiler-cli: 2.4.7
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =   
v7.4.0

**Comment by Toxicable** [comment]
Can you please reproduce this error in a plunkr?

**Comment by DzmitryShylovich** [comment]
do other/custom pipes work? any errors?

**Comment by kblestarge** [comment]
I just did some more tests. 

Here are the pipes that worked fine:
- lowercase
- uppercase
- json
- slice
- custom pipe that reformats a string input

Here are the pipes that broke the rendering:
- currency
- number (decimal)
- percent
- date

Seems like the pipe issues are all related to manipulating number type variables... Any idea what the underlying problem is?

**Comment by pkozlowski-opensource** [comment]
> Seems like the pipe issues are all related to manipulating number type variables... Any idea what the underlying problem is?

All the pipes that you've listed depend in the Intl API. It seems to me like you are running on a server that doesn't provide natively Intl API implementation and maybe you are not loading appropriate polyfills?

**Comment by kblestarge** [comment]
@pkozlowski-opensource, good hypothesis. Which polyfills should I be using to fix this problem?

**Comment by pkozlowski-opensource** [comment]
@kblestarge check:
* https://angular.io/docs/ts/latest/guide/browser-support.html
* https://angular.io/docs/ts/latest/guide/pipes.html

**Comment by DzmitryShylovich** [comment]
https://github.com/andyearnshaw/Intl.js/

**Comment by pkozlowski-opensource** [comment]
> it was my initial idea, but shouldn't it throw an error in this case?

@DzmitryShylovich since this is server-side rendering I wouldn't assume anything :-)

**Comment by kblestarge** [comment]
@DzmitryShylovich, I tried using the intl.js dependancy, but it didn't seem to work (pipes still break rendering). I ran `npm install intl` and then added this line to the polyfills.ts file: `import 'intl';`
Am I implementing intl correctly?

**Comment by DzmitryShylovich** [comment]
@kblestarge usually people add it via script tag [link](https://github.com/qdouble/angular-webpack2-starter/blob/master/src/index.html#L22) but I'm not sure if it's suitable in your case

**Comment by kblestarge** [comment]
@DzmitryShylovich, I think you're right. It doesn't seem suitable in my case. Any other suggestions?

**Comment by kblestarge** [comment]
I got it to work!
I included intl in the polyfills like this: https://github.com/angular/angular-cli/issues/1675#issuecomment-254027916

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource maybe we should throw an error when the Intl polyfill isn't active?
