### ISSUE TITLE
Importing {window} from '@angular/platform-browser/src/browser/tools/browser' causes a compilation error in angular 4 rc6

### ISSUE THREAD

**Issue by yosigolan** [angular/angular#15415]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Importing {window} from '@angular/platform-browser/src/browser/tools/browser' causes a compilation error in angular 4 rc6. the error is:

ERROR in .<some class>
Module not found: Error: Can't resolve '@angular/platform-browser/src/browser/tools/browser' in '<some path>'
 @ ./<some class>
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Expected behavior**
import and use same way as in angular 2 (the element path was changed in angular 4 from '@angular/platform-browser/src/facade/browser' to '@angular/platform-browser/src/browser/tools/browser'

**Minimal reproduction of the problem with instructions**
* opwn new angular 4 project using the cli
* in the app ts import {window} from '@angular/platform-browser/src/browser/tools/browser'
* run ng s

**Please tell us about your environment:**
windows 10, web storm, cli rc4, angular 4 rc 6

* **Angular version:** 4.0.0-rc6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by DzmitryShylovich** [comment]
> @angular/platform-browser/src/browser/tools/browser

deep imports are not supported in ng4

**Comment by IgorMinar** [comment]
this is not a public api. please see https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md for info about what is and what is not public api

**Comment by yosigolan** [comment]
Thanks for the clarification

**Comment by biemond** [comment]
@yosigolan What do you use now? because I have the same issue as you also need window

Thanks

**Comment by yosigolan** [comment]
i just coded it my self: 
const win = typeof window !== 'undefined' && window || <any>{};

**Comment by waterplea** [comment]
I'm implementing my own `EventManagerPlugin`. How do I import it to extend if it's not importable?
