### ISSUE TITLE
Change DynamicComponentLoader.loadIntoNewLocation to use abstraction over native DOM

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1541]
`loadIntoNewLocation` currently needs an element or a selector to load the component into. To do the web-worker separation / rendering on another platform, there needs to be some abstraction.

The abstraction must still allow somehow for the creation of a new element to into which the component will be loaded (a requirement for overlays, so that the overlaid component can be loaded into the document body).

**Comment by tbosch** [comment]
Proposed design: https://docs.google.com/document/d/1M9FmT05Q6qpsjgvH1XvCm840yn2eWEg0PMskSQz7k4E/edit#heading=h.vqv7a69lcwsl

**Comment by tbosch** [comment]
I.e. allow component based renderers.

**Comment by tbosch** [comment]
See https://github.com/angular/angular/issues/1675

**Comment by tbosch** [comment]
Closing this in favor of #1675
