### ISSUE TITLE
Two way data binding failed to work while working with jQuery plugin

### ISSUE THREAD

**Issue by bhubanstha** [angular/angular#15419]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Two way data binding is not working after element  uses jQuery plugin

**Expected behavior**
It should work

**Minimal reproduction of the problem with instructions**
I have posted my scenario on StackOverflow
http://stackoverflow.com/questions/42973549/two-way-binding-not-working-in-angular-2

**What is the motivation / use case for changing the behavior?**
 

**Please tell us about your environment:**
Windows 10, Visual Studio 2017 Community Edition, NPM, IIS

* **Angular version:** 2.0.X
Getting 2.4.9 on browser ng-version attribute.
In package json: 
"@angular/core": "~2.4.0"

* **Browser:** [all | Chrome XX | Firefox XX  ]

 
* **Language:** [all | TypeScript 2.2.1 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   7.0.0

**Comment by pkozlowski-opensource** [comment]
@bhubanstha you've posted a question on SO already, no need to duplicate it here. Support questions like this one belong to SO.
