### ISSUE TITLE
Template reload on value update like cascading dropdown 

### ISSUE THREAD

**Issue by ShyamVashista** [angular/angular#15418]
Hi 
I am using a directive and that is load  by parent dropdown value like 
Country ( as template and directive)
State (as template and directive)
City( as template and directive)

As it is parent
<custom-project-multicolumn-select2 [require]="true"
                                                                        [blankOption]="false"
                                                                        [controlId]="'ddlProject'"
                                                                        [controlName]="'ddlProject'"
                                                                        [placeholder]="'No Selection'"
                                                                        [allowClear]="false"
                                                                        [width]="'100%'"
                                                                        (onChange)="selectedProject($event)"
                                                                        [value]="dto.ProjectId" [disable]="false" [hideSelection]="true">
                                    </custom-project-multicolumn-select2>

and 
<div *ngIf="dto.ProjectId > 0">
                                        <custom-primecontract-multicolumn-select2 [require]="false"
                                                                                  [projectId]="dto.ProjectId"
                                                                                  [blankOption]="false"
                                                                                  [controlId]="'ddlPrimecontract'"
                                                                                  [controlName]="'ddlPrimecontract'"
                                                                                  [placeholder]="'No Selection'"
                                                                                  [allowClear]="true"
                                                                                  [width]="'100%'"
                                                                                  (onChange)="selectedPrimeContract($event)"
                                                                                  [value]="dto.PrimeContractId" [disable]="false" [hideSelection]="true">
                                        </custom-primecontract-multicolumn-select2>
                                    </div>

If I use this way it not load 2nd dropdown is loaded when 1st dropdown value is changes or assigned
Is there any way to load blank dropdown and after project selection reload that

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/docs/CONTRIBUTING.md#-got-a-question-or-problem).
