### ISSUE TITLE
Issue in UpgradeModule for hybrid approach.

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#15421]
Hi,

I am following the following url for hybrid approach using upgradeModule -
https://angular.io/docs/ts/latest/guide/upgrade.html#!#bootstrapping-hybrid-applications

Earlier i was using UpgradeAdapter (old api).

as soon as i switched to this i am getting this issue . It came when i followed Dividing routes between Angular and AngularJS topic-

No Provider for hybridConfig!

Any comment what i missed ?

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/docs/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by gkalpak** [comment]
@ericmartinezr, is right. Happy to reopen and investigate if you can provide a reproduction.
