### ISSUE TITLE
Local vars should only be read if no LHS.

### ISSUE THREAD

**Issue by matteosuppo** [angular/angular#1542]
https://jsfiddle.net/matteosuppo/gryazezr/

You can see the issue in this fiddle: I have two nested For that display a list of parents and a list of children. The problem is that the children have a property called 'parent' which apparently conflicts with the var parent instatiated by the For directive.

I don't know if this is a known problem. If it is, I'm sorry. If it's not, I'll try to fix it.

**Comment by pkozlowski-opensource** [comment]
It looks like a bug  to me (some kind of name collision, see: https://jsfiddle.net/kn606px2/)

**Comment by matteosuppo** [comment]
Seems like the problem is here: https://github.com/angular/angular/blob/master/modules/angular2/src/change_detection/proto_change_detector.js#L172

It returns variables on the parent scope if they exists.

In the next few days I'll try to submit a pull request with a test case

**Comment by naomiblack** [comment]
Local variables should only be checked if there is no LHS. For example, `localA` has no LHS but `foo.localA` does.

**Comment by mhevery** [comment]
removed @pkozlowski-opensource  since #1550 has a fix.
