### ISSUE TITLE
4.0.0-rc.6 AOT regression: exporting function named toString breaks AoT

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#15420]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

Exporting a function named `toString` [like so](https://github.com/ng-bootstrap/ng-bootstrap/blob/5856a75ace90c7323d073f1a9838560016bbb5d4/src/util/util.ts#L5) breaks AoT with the following error:

>   0% compilingCould not resolve module 'function toString() { [native code] }' relative to file /Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/core/src/util/util.ts
 10% building modules 3/3 modules 0 activeModuleNotFoundError: Module not found: Error: Can't resolve './../../$$_gendir/demo/src/app/app.module.ngfactory' in '/Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/core/demo/src'
    at factoryCallback (/Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/core/node_modules/webpack/lib/Compilation.js:230:39)

**Expected behavior**

Functions named `toString` are allowed or there is a precise documentation and clear AoT error when a "disallowed" function named is used.

**Minimal reproduction of the problem with instructions**

* clone https://github.com/pkozlowski-opensource/core/tree/ng_rc_6
* run `gulp build:demo` and see the error almost immediately.

This used to work in rc.5 and is linked to the function name (renaming the utility function in question from `toString` to sth like `stringify` makes the error go away.

**What is the motivation / use case for changing the behavior?**

Regression. 

**Please tell us about your environment:**

OSX, node v6.9.5

**Comment by DzmitryShylovich** [comment]
looks like it was introduced here https://github.com/angular/angular/pull/15367
`module` is a function but must be a string
cc @chuckjaz

**Comment by pderks** [comment]
+1
