### ISSUE TITLE
Tests Freeze when Failing Against the Existence of a DebugElement

### ISSUE THREAD

**Issue by SethGunnells** [angular/angular#15428]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```
This would appear to be an issue with Jasmine during the pretty printing stage, but I am also logging it here in case there is something about Angular's testing that is causing this issue and should be changed.
**Related Issue:** https://github.com/jasmine/jasmine/issues/1263

**Current behavior**
Attempting to test the existence of a `DebugElement` in a unit test results in the test hanging.

**Expected behavior**
It should not hang. The test should immediately fail.

**Minimal reproduction of the problem with instructions**
Set up a typical testing harness for an Angular component and create the following test:
```
var result = fixture.debugElement.query(By.css("#something"));
// The following line hangs when result is a DebugElement
// Also occurs with .toBeNull() and some others
expect(result).toBeFalsy();
```

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**
Windows 10, Visual Studio Code, Karma

* **Angular version:** 2.4.10
* **Language:** TypeScript 2.2.1

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/14235

**Comment by SethGunnells** [comment]
Apologies. I did look before logging but didn't see it. Closing.
