### ISSUE TITLE
Incorrect route link parsing in template

### ISSUE THREAD

**Issue by deastr** [angular/angular#15423]
**I'm submitting a ...**  (check one with "x")

[ x] bug report

**Current behavior**
routerLink parsing is wrong in template: it includes current path.

**Expected behavior**
It should not include current path rather replace it.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/MYoIl9lWwEYLvd9iezh5?p=preview

1) Click "`Heroes`" 
2) Click any hero (current route: `/hero/XX/`)
3) Click any of the "`heroes`" or "`/heroes`" or the "`/heroes/`" buttons to navigate to those routes
4) Check the invalid route error message for the route it tried to navigate

The link buttons are generated in `app/heroes/hero-detail.component.ts` like this:

```
<div>
      <template ngFor [ngForOf]="columns" let-column>
        <button routerLink="['{{column.routerLink}}']">{{column.routerLink}}</button>
      </template>
    </div>
..
columns: any[] = [
    {
      routerLink: "heroes"
    },
    {
      routerLink: "/heroes"
    },
    {
      routerLink: "/heroes/"
    }]

```

Error message `activatedRoute.snapshot.toString()` in `app/not-found-component.ts`:

`Page not found: Route(url:'hero/11/%5B'heroes'%5D', path:'**')`

**Comment by DzmitryShylovich** [comment]
> `<button routerLink="['{{column.routerLink}}']">`

invalid syntax. it should be `<button [routerLink]="column.routerLink">`

**Comment by deastr** [comment]
@DzmitryShylovich : I tried [routerLink] but that one is giving this error:

```
Error: Uncaught (in promise): Error: Template parse errors:
Parser Error: Got interpolation ({{}}) where expression was expected at column 2 in [['{{column.routerLink}}']] in HeroDetailComponent@15:16 ("
    <div>
      <template ngFor [ngForOf]="columns" let-column>
        <button [ERROR ->][routerLink]="['{{column.routerLink}}']">{{column.routerLink}}</button>
      </template>
    </div>
"):
```

**Comment by DzmitryShylovich** [comment]
```
<div>
      <template ngFor [ngForOf]="columns" let-column>
        <button [routerLink]="column.routerLink">{{column.routerLink}}</button>
      </template>
</div>
```

**Comment by DzmitryShylovich** [comment]
and, please,read docs https://angular.io/docs/ts/latest/guide/template-syntax.html before submitting issues. thanks
