### ISSUE TITLE
4.0.0-rc.6 [platform-server] - Cannot find module '@angular/animations/browser'. & other errors

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular#15427]
[x] bug report => search github for a similar issue or PR before submitting

**Current behavior**
When upgrading from rc5 to rc6 these errors now pop-up from the generated typings within Angular platform-browser & platform-server.

```
ERROR in C:/Users/mark.pieszak/Documents/GitHub/ng-universal-demo/node_modules/@angular/platform-browser/animations/src/animation_renderer.d.ts (1,53): Cannot find module '@angular/animations/browser'.)

    ERROR in C:/Users/mark.pieszak/Documents/GitHub/ng-universal-demo/node_modules/@angular/platform-browser/animations/src/providers.d.ts (8,276): Cannot find module '@angular/animations/browser'.)

    ERROR in C:/Users/mark.pieszak/Documents/GitHub/ng-universal-demo/node_modules/@angular/platform-server/src/server.d.ts (8,34): Cannot find module '@angular/animations/browser'.)

    ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/animations/browser relative to C:/Users/mark.pieszak/Documents/GitHub/ng-universal-demo/node_modules/@angular/platform-server/platform-server.d.ts., resolving symbol ɵSERVER_RENDER_PROVIDERS in C:/Users/mark.pieszak/Documents/GitHub/ng-universal-demo/node_modules/@angular/platform-server/platform-server.d.ts, resolving symbol ServerModule in C:/Users/mark.pieszak/Documents/GitHub/ng-universal-demo/node_modules/@angular/platform-server/platform-server.d.ts, resolving symbol ServerModule in C:/Users/mark.pieszak/Documents/GitHub/ng-universal-demo/node_modules/@angular/platform-server/platform-server.d.ts

    ERROR in ./~/@angular/platform-server/@angular/platform-server.es5.js
    Module not found: Error: Can't resolve '@angular/animations/browser' in 'C:\Users\mark.pieszak\Documents\GitHub\ng-universal-demo\node_modules\@angular\platform-server\@angular'
     @ ./~/@angular/platform-server/@angular/platform-server.es5.js 13:0-63
     @ ./src/app/server-app.module.ts
     @ ./src/main.server.ts

    ERROR in ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
    Module not found: Error: Can't resolve '@angular/animations/browser' in 'C:\Users\mark.pieszak\Documents\GitHub\ng-universal-demo\node_modules\@angular\platform-browser\@angular\platform-browser'
     @ ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js 13:0-249
     @ ./~/@angular/platform-server/@angular/platform-server.es5.js
     @ ./src/app/server-app.module.ts
     @ ./src/main.server.ts
```

**Expected behavior**
No errors

**Minimal reproduction of the problem with instructions**
Repro here: https://github.com/markpieszak/ng-universal-demo/tree/rc6-error
`yarn install && npm start`

* **Angular version:**

**Comment by vikerman** [comment]
platform-server now needs @angular/animations as peer dependency. npm install should show an error if you don't have that in your dependencies.

**Comment by MarkPieszak** [comment]
(Just incase others find it)
Make sure `@angular/animations` is installed as a dependency, and the errors will go away.

**Comment by omanoel** [comment]
From http://angularjs.blogspot.fr/2017/03/angular-400-now-available.html

Animation Package
We have pulled animations out of @angular/core and into their own package. This means that if you don’t use animations, this extra code will not end up in your production bundles. 
This change also allows you to more easily find documentation and to take better advantage of autocompletion. You can add animations yourself to your main NgModule by importing BrowserAnimationsModule from @angular/platform-browser/animations.

**Comment by vikerman** [comment]
@omanoel - The code still won't end up in your client bundle. On your server we took the route of including http and animations by default so that you have a single ServerModule that provides overrides for everything. The idea is we are not sensitive to bundle size on the server at the same levels as on the client. Please let us know if you still think this is problematic.

**Comment by YoLoADR** [comment]
Try this command
 npm install '@angular/animations' -- save

**Comment by paulintrognon** [comment]
There's something I don't understand: I don't want animations, I rather want to use the NoopAnimationsModule, because I don't want the animation module to be in my production code (I'm trying to keep it lightweight)

But it seems that the NoopAnimationsModule stills require the `@angular/animations` to be installed. Is there a way I can use NoopAnimationsModule without installing `@angular/animations` ?

**Comment by Gamage-Supun-Perera** [comment]
same error. above answers not set

**Comment by MarkPieszak** [comment]
For your `server-app.module` do you have `NoopAnimationsModule` in your imports[] there 
(from `import { NoopAnimationsModule } from '@angular/platform-browser/animations';`) @Gamage-Supun-Perera

**Comment by shivatom** [comment]
Same error,
ERROR in node_modules/@angular/platform-browser/animations/src/providers.d.ts(1,119): error TS2305: Module '

**Comment by stevermeister** [comment]
only install of `@angular/animations` helped.
taking in account that I don't have dependency to animations, it looks pretty strange
