### ISSUE TITLE
Child component with blur event binding consumes click event from parent component and click event is not fired

### ISSUE THREAD

**Issue by brmckenna** [angular/angular#15435]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Scenario:  Child component which contains an input element and binds the blur event of the input to one of its methods.  The parent component has a button which when clicked triggers the blur event of the child component input element if this element currently has focus.  The problem is the button click triggers the blur event in the child component and this event is consumed entirely by the child component.  The event does not bubble back up or return to the parent component button click and is lost in the method bound to the focus event in the child component.  The user has to click the button on the parent component twice since the second time around the child input element no longer has focus and the click event is properly received. 

**Expected behavior**

The button click rightfully fires the blur event of the input which has focus but the button click event should also fire afterwards. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

We should be able to safely bind the blur event on a component which may be used as a child component. 

**Please tell us about your environment:**

Visual Studio 2015, Windows 10, node 7.5.0, npm 4.1.2, .NET 4.5.1 target framework, IIS express, HTTPS, ASP.NET
* **Angular version:** 2.0.X

Angular 2.4.7
"dependencies": {
    "@angular/common": "2.4.7",
    "@angular/compiler": "2.4.7",
    "@angular/core": "2.4.7",
    "@angular/forms": "2.4.7",
    "@angular/http": "2.4.7",
    "@angular/platform-browser": "2.4.7",
    "@angular/platform-browser-dynamic": "2.4.7",
    "@angular/router": "3.4.7",
    "bootstrap": "3.3.7",
    "core-js": "^2.4.1",
    "jquery": "2.2.4",
    "lodash": "4.17.2",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.1",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@types/bootstrap": "^3.3.32",
    "@types/jasmine": "2.5.36",
    "@types/jquery": "^2.0.41",
    "@types/lodash": "4.14.43",
    "@types/node": "^6.0.46",
    "@types/selenium-webdriver": "^2.53.33",
    "angular2-template-loader": "^0.4.0",
    "awesome-typescript-loader": "2.2.4",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^2.1.0",
    "graceful-fs": "^4.1.11",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "istanbul": "^0.4.5",
    "istanbul-instrumenter-loader": "^2.0.0",
    "istanbul-lib-instrument": "^1.4.2",
    "jasmine-core": "~2.4.1",
    "karma": "^1.5.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-coverage-istanbul-reporter": "^0.3.0",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.0.3",
    "karma-nightmare": "^0.4.5",
    "karma-remap-istanbul": "0.2.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.26",
    "karma-webpack": "^2.0.3",
    "less": "^2.7.2",
    "less-loader": "^3.0.0",
    "mocha": "^3.2.0",
    "nightmare": "^2.10.0",
    "remap-istanbul": "^0.6.4",
    "resolve-url-loader": "^2.0.2",
    "rimraf": "^2.5.4",
    "style-loader": "^0.13.1",
    "tslint": "^4.0.0",
    "tslint-loader": "3.3.0",
    "typescript": "2.0.10",
    "webpack": "^2.2.1",
    "webpack-merge": "^0.14.0"
  }

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Tested on Chrome so far
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Please reproduce in plunkr. You can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point

**Comment by brmckenna** [comment]
Situation was too intricate to reproduce - after attempting to on Plunk it was not a simple parent/child relationship since I was unable to reproduce.  May have been due to ReactiveForms, formbuilder, and validation.  We took a different approach in our code, you may close this issue.  Thank you.

**Comment by simanjuntak123** [comment]
any body help me?
its not work in angular:

<button class="btn btn-primary btn-round float-right mx-1" (click)="$event.target.blur();" type="submit">Submit</button>
