### ISSUE TITLE
Is there a way to create a component without entryComponents

### ISSUE THREAD

**Issue by chinra02** [angular/angular#15437]
**I'm submitting a 
```
 feature request


**Current behavior**
Not possible



 I am working on an app where components are being passed as arguments, It's not possible to specify at the entryComponets. So is there any way to create a component without entryComponents being specified.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/docs/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by pkozlowski-opensource** [comment]
Nope, components to be created dynamically need to be listed in the `entryComponents` section.
