### ISSUE TITLE
Can we call angular 1.x directives

### ISSUE THREAD

**Issue by prasannapattam** [angular/angular#1543]
Is it possible to use angular 1.x directives, such as ui-grid within angular 2 components? If yes, please point me to some more info on this.

**Comment by pkozlowski-opensource** [comment]
No, as of today you can't call Angular 1.x directive from Angular 2 code (well, technically there would be a way, but not the one that would be a recommended co-existence / migration strategy).  

The co-existence / migration story is still work in progress and will be described on https://angular.io/ when ready.
