### ISSUE TITLE
DEVELOPER.md is not found

### ISSUE THREAD

**Issue by jnizet** [angular/angular#15446]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The README links to CONTRIBUTING.md, which links to DEVELOPER.md, but that results in a 404 Not Found because DEVELOPER.md was moved to docs, but the references have not been changed. 

**Expected behavior**

The link should not 404

**What is the motivation / use case for changing the behavior?**

Making contribution easier for newcomers like me.

I would submit a PR, but I don't know if the DEVELOPER.md should rather be moved back to the root (where it's typically located in github projects), or if the references from CONTRIBUTING.md should be fixed.

**Comment by DzmitryShylovich** [comment]
> was moved to docs

it was reverted. Works fine for me

**Comment by jnizet** [comment]
Then the reversal was reverted, too, or has not been pushed to master yet, because currently, clicking from the README on "contributing", then on "developer documentation" results in a 404.

**Comment by DzmitryShylovich** [comment]
yeah, I see, sorry, my bad :)

**Comment by thomaspink** [comment]
Opened a PR #15455 
Hope it helps
