### ISSUE TITLE
Lazy loaded component into aux outlet doesn't add anything

### ISSUE THREAD

**Issue by RatkoR** [angular/angular#15447]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

While investigating why lazy loaded components cannot be rendered into auxiliary outlet #15033 I came accross this and I don't know if it's a bug or not.

https://plnkr.co/edit/Hist8S2MBmUeuon5AvBj?p=preview

This plunker has an aux outlet and loads into it a 'normal' component and a lazy loaded one. Normal component works ok, while clicking on the lazy loaded one produces nothing. No error is generated and no template is being rendered.

If I change [routerLink]
from `{ outlets: { 'sidebar': ['aux-lazy', 'aux-lazy-url'] }` 
to `{ outlets: { 'sidebar': ['aux-lazyX', 'aux-lazy-url'] }` 
or `{ outlets: { 'sidebar': ['aux-lazy', 'aux-lazy-urlX'] }` an error is thrown.

So if I get no error, outlet link must be correct. Why is then component not rendered?

**Expected behavior**

I guess an error should be thrown or component should be rendered. Or am I doing something wrong?

**Minimal reproduction of the problem with instructions**

See above...

**What is the motivation / use case for changing the behavior?**

Trying to get aux components lazy loaded. We have quite some of them and because they are not really important to the app we'd like to only load them on demand.

**Please tell us about your environment:**

Linux

* **Angular version:** 2.0.X

2.4.9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
FF and Chrome tested

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

If this is still an issue, please file against StackOverflow first and see if it can get resolved there. We're a couple versions ahead at this point though, so this might be resolved already.
