### ISSUE TITLE
Property 'xxx' is private and only accessible within class 'xxxComponent'

### ISSUE THREAD

**Issue by Hanfrey** [angular/angular#15451]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Made a new project with Angular CLI 1.0.0 and Angular 4. Tried to make "ng build --prod" or "ng build --aot --prod". Now he tells me that all my private propertys not accessible in the template.

**Expected behavior**

Since the template is part of the component it sould be possible to access private propertys.
**Minimal reproduction of the problem with instructions**
ng build --prod" or "ng build --aot --prod".

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.2 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  7.5.0

**Comment by pkozlowski-opensource** [comment]
All properties that are to be accessible in a template needs to be public. This is because Angular generates a separate TS class representing a template.

Closing since the current behaviour is expected.

**Comment by da45** [comment]
@pkozlowski-opensource , 

Let me ask you please, why this error doesn't appear when using a simple ng serve ? or when using ng build (whithout --prod option) ?  your answer is not clear for me,

**Comment by dhyey35** [comment]
@da45 When you run ng serve angular CLI doesn't generate a separate TS class, when you run ng build --prod it does.
If you want to use a service or any other variable in html please change them from `private` to `public` like below:

test.component.html

`
    <span *ngIf="someService.displayItem">Item to display</span>
`

test.component.ts


    import { Component } from '@angular/core'
    import { SomeService } from '../someService/someService'

    @Component({
      moduleId: module.id,
      selector: 'test',
      templateUrl: 'test.component.html'
    })
    export class TestComponent {
    	constructor(
    		public someService: SomeService
    	) { }
    }

**Comment by giscafer** [comment]
terrible
