### ISSUE TITLE
Update Guide: incorrect advice for implementing lifecycle hooks?

### ISSUE THREAD

**Issue by benelliott** [angular/angular#15454]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The [Angular Update Guide](https://angular-update-guide.firebaseapp.com/) advises users to:

> Ensure you don't use implements OnInit, or use implements with any lifecycle event. Instead use extends <lifecycle event>.

But the related commit (ee747f7) suggests the opposite is true:

>  Because all lifecycle hooks are now interfaces the code that uses 'extends' keyword will no longer compile.

Users may perform a time-consuming refactor after reading the guide, only to find that they actually broke something that was working!

**Expected behavior**
Guide is updated to be correct.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
Correct documentation

**Please tell us about your environment:**
N/A

* **Angular version:** 2.0.X
N/A

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by DzmitryShylovich** [comment]
> The [Angular Update Guide] advises users to

link?

**Comment by benelliott** [comment]
@DzmitryShylovich  Fixed. It's linked in the official Angular blogpost but can't find the source repo.

**Comment by DzmitryShylovich** [comment]
@benelliott thanks.
yeah, this is an error and should be fixed.

cc @StephenFluin

**Comment by benelliott** [comment]
There is also a typo in

> Stop using Renderer.invikeMethodElementas this method has been removed. There is not currently a replacement.

Should be

> Stop using Renderer.invokeMethodElement as this method has been removed. There is not currently a replacement.

**Comment by JonathanYates** [comment]
Yeah I noticed this. Lifecycle hooks like OnInit are interfaces and have been as long as I can remember. Dreadful guide, avoid it.

**Comment by trotyl** [comment]
@JonathanYates Life-cycle hooks just became `interface`s in 4.0.0-rc.1, before that they're `abstract class`es. You can find this in [change log](https://github.com/angular/angular/blob/master/CHANGELOG.md#user-content-breaking-changes-2). It's a valid mentioning as it may be a breaking change for other people, what's wrong is it saying the opposite.

**Comment by IgorMinar** [comment]
@StephenFluin can you please fix this. it should be `implements` and not `extends`

**Comment by StephenFluin** [comment]
Fixed.

**Comment by DzmitryShylovich** [comment]
@StephenFluin there's also a missing space https://github.com/angular/angular/issues/15454#issuecomment-288980157

**Comment by benelliott** [comment]
@DzmitryShylovich @StephenFluin Yep, actually the method name is incorrect too.

**Comment by paesku** [comment]
There are two update/upgrade URLs which might be confusing:

https://angular-upgrade-guide.firebaseapp.com  
and 
https://angular-update-guide.firebaseapp.com  

Whereas **https://angular-update-guide.firebaseapp.com** is describing it correctly with implements <lifecycle event> and **https://angular-update-guide.firebaseapp.com** as describing it with extends <lifecycle event>

**Comment by StephenFluin** [comment]
@paesku Thanks for finding that second out of date site. It's been deleted.
