### ISSUE TITLE
Missing Http.request.search

### ISSUE THREAD

**Issue by vaseker** [angular/angular#15456]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
http.request(new Request({ url: 'https://ya.ru', search: 'foo=bar' })) causes request to 'https://ya.ru' without search string.

**Expected behavior**
Request to 'https://ya.ru?foo=bar'

**Minimal reproduction of the problem with instructions**
```ts
import { Http, Request, RequestMethod } from '@angular/http'

Http.request(new Request({ url: 'https://ya.ru', method: RequestMethod.Get, search: 'foo=bar' }))
```
* **Angular version:** 4.0.0

**Comment by vaseker** [comment]
Hmmm. 'search' cutted out without deprecation warning. 'params' works fine.

https://github.com/angular/http-builds/blob/master/src/base_request_options.d.ts#L52

**Comment by DzmitryShylovich** [comment]
> new Request({ url: 'https://ya.ru', method: RequestMethod.Get, search: 'foo=bar' })

you shouldn't create a `Request` object like this. You need to use `RequestOptions`:
```
const req = new Request(new RequestOptions({
          url: 'test',
          method: 'GET',
          body: null,
          headers: new Headers({'content-type': 'multipart/form-data'})
        }));
```

**Comment by vaseker** [comment]
Oh. It looks insane. 
But thanks for reply.

**Comment by DzmitryShylovich** [comment]
Http module will be rewritten and api will be improved in 4.1
[Design doc](https://docs.google.com/document/d/1C_wzuuQEjIktJxrTlUTjTCDEZR8YduGTfbpe4WsNfNk/edit#heading=h.xgjl2srtytjt) #14334
