### ISSUE TITLE
AngularJS Custom Filter orderBy sortPredicate not working

### ISSUE THREAD

**Issue by paramsinghvc** [angular/angular#1545]
The problem is that I have an array of recipe objects. Each recipe object has some comments on it. I want to sort the array in angularJS controller using the $filter service provided by angular.

 $scope.recipes = $filter('orderBy')($scope.data, function(recipe) {
    return recipe.comments.length;
  });
But its not giving the required results. However, I'm able to achieve the desired results using the JS array sort functionality like this

$scope.data.sort(function(a, b) {
     if (a.comments.length < b.comments.length) return 1;
     if (b.comments.length < a.comments.length) return -1;
     return 0;
    });
The Plunkr for the same scenario is : http://plnkr.co/edit/L9Bt67xHRCJLBoWG8EZp?p=preview

Thanks in advance. Please Help!

**Comment by otodockal** [comment]
Wrong repo. Please, move your issue to Angular.js repo https://github.com/angular/angular.js. 

This is repo for Angular2!
