### ISSUE TITLE
Language service: internal error

### ISSUE THREAD

**Issue by karptonite** [angular/angular#15459]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular language service seems to run into an internal error when processing a message (using PHPStorm's support for Angular Language service). (see bottom of issue)

**Expected behavior**
No internal error.

**Minimal reproduction of the problem with instructions**
In my project, I open any ts file in our angular project, and switch to the Angular console. I expect that something in my project is the culprit, but I'm not sure what, and cannot easily share my entire project to reproduce, unfortunately. If necessary, though, I'll see what I can do.

**Please tell us about your environment:**
Mac OS 10.12.3, PHPStorm 2017.1
Note also that my project has two node_modules dirs, one in the base project dir, and one in "front end" directory. Angular (with the language service) is installed in both because PHPStorm appears to look for the language service only in the base directory. I don't think this is relevant to the bug, but I can't be sure.

* **Angular version:** 2.0.X
4.0.0 for everything

* **Browser:**
N/A
 
* **Language:**
TypesScript 2.2.1

* **Node (for AoT issues):**   7.7.3
```
Process: Error processing message: Cannot read property 'token' of undefined TypeError: Cannot read property 'token' of undefined
    at /Users/karp/Documents/git/bgg/node_modules/@angular/language-service/bundles/language-service.umd.js:30604:33
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (/Users/karp/Documents/git/bgg/node_modules/@angular/language-service/bundles/language-service.umd.js:30571:19)
    at /Users/karp/Documents/git/bgg/node_modules/@angular/language-service/bundles/language-service.umd.js:30148:63
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/karp/Documents/git/bgg/node_modules/@angular/language-service/bundles/language-service.umd.js:30139:49)
    at addNgModule (/Users/karp/Documents/git/bgg/node_modules/@angular/language-service/bundles/language-service.umd.js:38714:58)
    at /Users/karp/Documents/git/bgg/node_modules/@angular/language-service/bundles/language-service.umd.js:38725:14
    at Array.forEach (native)
    at _createNgModules (/Users/karp/Documents/git/bgg/node_modules/@angular/language-service/bundles/language-service.umd.js:38724:26)

**Comment by kemsky** [comment]
The same error on Windows 10 + Intellij Idea 2017.1. Language Service fails with many errors.

The reason (in my case) is that `providers` property contains function calls:

```typescript
@Component({
    selector   : '.ReportComponent',
    templateUrl: './report.component.html',
    providers  : [
        forDetailsComponent(ReportComponent, Page.report),
        FileChooserPopupService
    ]
})

export const forDetailsComponent = function forDetailsComponent(type:Type<any>, page:Page):Provider[]
{
    const options:ControllerOptions = new ControllerOptions();

    return [
        provideValue(ControllerOptions, options),
        provideClass(CONTROLLER, ComponentController),
        provideExisting(UIComponent, forwardRef(() => type)),
        provideValue(Page, page),
        provideFactory(PageContextBase, (page:Page, route:ActivatedRoute, pageService:PageService) => new PageContextBase(page, route, pageService, new DefaultContextStrategy(page)), [Page, ActivatedRoute, PageService]),
        provideExisting(PageContext, PageContextBase)
    ];
};
```

Language Service fails even to report correct error because of many nullpointers in its own code.

After fixing null pointers it shows:
```
Error:(15, 2) Angular: Invalid providers for "ClaimComponent in D:/Dev/Projects/... claim.component.ts" - only instances of Provider and Type are allowed, got: [?null?, ...]
```

I do think that replacing `forDetailsComponent` function with raw providers are is not an option since there are literally hundreds of components using it. It is not possible to maintain application codebase in this case.

**Comment by Ionaru** [comment]
Original issue seems related to #14366

**Comment by kevincam3** [comment]
Same problem

**Comment by karptonite** [comment]
While I don't know what originally caused this issue, I haven't seen it in a while. I'm going to assume it was fixed along the way, and close this.
