### ISSUE TITLE
Ng style doesnt remove old style when the model object changes

### ISSUE THREAD

**Issue by lakshaydulani** [angular/angular#15457]
**Current behaviour** - If you assign an object to ngStyle in a div, ngStyle doesnt flush the style properties from the older object when it changes.

**Expected/desired behavior** - All the old object style should be flushed, and only the new object style properties should be applied.

**Reproduction of the problem**
http://plnkr.co/edit/ccS4gOZgdMqguwIcGRob?p=preview

In the above plunkr, click on first button (margin border background), then on second and then on third. Till this, it works fine.
But now click on second button (border background), margin property should be removed but it isn't.

I had earlier reported the same issue - https://github.com/angular/angular/issues/10315

**Comment by DzmitryShylovich** [comment]
it will work if you change prop order
```
 this.style = {"margin":"10px", "border":"1px solid black"};
```

**Comment by sod** [comment]
![image](https://cloud.githubusercontent.com/assets/905328/24294791/3bad26dc-1098-11e7-9f5e-e675939a3fd7.png)

**Comment by DzmitryShylovich** [comment]
Yeah, it's a bug with `KeyValueDiffer`

**Comment by vicb** [comment]
Can reproduce @lakshaydulani please complete the full template next time you report an issue, thanks
