### ISSUE TITLE
Question: How can I use angular2 with typescript today

### ISSUE THREAD

**Issue by KhaosTheory1012** [angular/angular#1546]
I am trying to get some prototype REST client thingy to work and I am writing in typescript. My problem is I don't know how to import into typescript from angular2. I heard angular2 will be written/rewritten in typescript but at the moment I can only use the angular2 files from the ngconf2015demo.

I wanted to know when there will be a repo with the .ts .d.ts files so I can use it with typescript.

I just started out with angular2 and typescript so excuse me if I understood something wrong.

**Comment by mhevery** [comment]
This is till work in progress. We should have some demos in the next couple of weeks.
