### ISSUE TITLE
Quick Start for Visual Studio 2015 No Longer Works

### ISSUE THREAD

**Issue by PSheriff** [angular/angular#15465]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you follow the exact instructions for adding Angular 2 to Visual Studio 2015 at https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html the application does not run. When you look at the F12 tools it gives the following error:

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3144/main.js
	Error: XHR error (404 Not Found) loading http://localhost:3144/main.js
	   at wrapFn (http://localhost:3144/node_modules/zone.js/dist/zone.js:1199:17) [<root>]
	   at Zone.prototype.runTask (http://localhost:3144/node_modules/zone.js/dist/zone.js:165:21) [<root> => <root>]
	   at invoke (http://localhost:3144/node_modules/zone.js/dist/zone.js:460:21) [<root>]
	Error loading http://localhost:3144/main.js

However, main.js is now under the /src folder. If you move the files in the /src folder to the project root, and move the /app folder to the project root, then you get a different error.

Error: (SystemJS) Invalid character
	SyntaxError: Invalid character
	   at ZoneDelegate.prototype.invoke (http://localhost:6424/node_modules/zone.js/dist/zone.js:363:13)
	   at Zone.prototype.run (http://localhost:6424/node_modules/zone.js/dist/zone.js:125:17)
	   at Anonymous function (http://localhost:6424/node_modules/zone.js/dist/zone.js:760:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:6424/node_modules/zone.js/dist/zone.js:396:13)
	   at Zone.prototype.runTask (http://localhost:6424/node_modules/zone.js/dist/zone.js:165:21)
	Evaluating http://localhost:6424/systemjs-angular-loader.js
	Error loading http://localhost:6424/systemjs-angular-loader.js
	Error loading http://localhost:6424/app/app.module.js as "./app/app.module" from http://localhost:6424/main.js

**Expected behavior**
Should be able to walk through the instructions and it should work.

**Minimal reproduction of the problem with instructions**
Follow the instructions at https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html

**What is the motivation / use case for changing the behavior?**
Lots of developers use Visual Studio and want Angular 4 to work.

**Please tell us about your environment:**
Windows 10
Visual Studio 2015 with Update 3
IIS Express
npm v3.10.10

* **Angular version:** 2.0.X
Yes, this is now a problem in 2.0x as well. I tested it yesterday before I updated to Angular 4.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome v56.0.2924.87
IE v11
IE Edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript v2.2.2

* **Node (for AoT issues):** `node --version` =   
node v6.9.4

**Comment by DzmitryShylovich** [comment]
Please re-open this issue on https://github.com/angular/angular.io/issues

**Comment by DzmitryShylovich** [comment]
@PSheriff close this issue please. thanks
