### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when changing a component 'non model' value in afterViewInit

### ISSUE THREAD

**Issue by adrienboulle** [angular/angular#15464]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
changing a component 'non model' value in afterViewInit throws `ExpressionChangedAfterItHasBeenCheckedError` if the value has an impact on a method used in the view.

in the plunker:
-> `getTextDecoration()`  returns `none` before  ngAfterViewInit is called (`isViewInit === false`) 
-> `getTextDecoration()`  returns `underline` after  ngAfterViewInit is called (`isViewInit === true`) 

**Expected behavior**
it should not throw the error since `getTextDecoration` is just a method and not part of the model.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/k8AsppUH8V2RvPeLJ0JT?p=preview

* **Angular version:** 4.0.0 => KO
* **Angular version:** 4.0.0-beta.8 => OK

**Comment by DzmitryShylovich** [comment]
cc @tbosch

**Comment by jesussobrino** [comment]
@adrienboulle It's still happening in Angular 4.0.1. (I've just get updated)

**Comment by chrishandorf** [comment]
I'm on 4.0.1 and also getting this error

**Comment by ThomasKerbrat** [comment]
I had a similar issue when I wanted to created a component with `resolveComponentFactory` and inserting the created component back into the template.
Looking at the [lifecyle hooks documentation](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#lifecycle-sequence), I changed `ngAfterViewInit` to `ngAfterContentInit` and it worked.

Hope it helps ;)

**Comment by adrienboulle** [comment]
@jesussobrino indeed i've checked the plunker which use @next and the error is still thrown

**Comment by tbosch** [comment]
This is works as intended, as you are using `getTextDecoration()` in your template. Therefore Angular will call it whenever it dirty checks your template. I.e. Angular only looks at the resulting values of expressions...

In dev mode (i.e. you didn't call `enableProdMode()`), angular does 2 dirty checks:
- 1x to apply new values and
- 1x afterwards to check that nothing has changed (to enforce the unidirectional data flow).

**Comment by adrienboulle** [comment]
@tbosch so it was a bug that it worked on angular@2.0.0->2.4.6 ?

**Comment by tbosch** [comment]
@adrienboulle yes, this was a bug before. In general, whenever you change a bound value during change detection, you should expect this kind of error...

**Comment by adrienboulle** [comment]
ok thanks :)

**Comment by Dj-jom2x** [comment]
this happend to me if i use time ago pipe xD
`CboxComponent.html:37 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '49 minutes ago'. Current value: '50 minutes ago'.`

**Comment by djejaquino** [comment]
@Dj-jom2x  this just happened to me using Moment.js inside an "impure" pipe.

@tbosch, what can be done here?

**Comment by tmjssz** [comment]
@djejaquino this worked for me: 
[How to manage Angular2 “expression has changed after it was checked” exception when a component property depends on current datetime](http://stackoverflow.com/questions/39787038/how-to-manage-angular2-expression-has-changed-after-it-was-checked-exception-w)

**Comment by Dj-jom2x** [comment]
i fix my issue ... 
every new msg i sent .. i push 1 of them as old msg object array
then keep it 15 as max .. just replace and replace the top one and remove the last one ..

i always put new date xD as chat time ago inside object array ...  now i put in on variable at the top so the time ago will stay as is ..

**Comment by maximusk** [comment]
Check the [Everything you need to know about the `ExpressionChangedAfterItHasBeenCheckedError` error](https://medium.com/@maximus.koretskyi/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4) for the in-depth explanation of the cause and the need for the check.

**Comment by zhantewei2** [comment]
```js
@ContentChildren(controls)controls
ngAfterViewInit(){
   this.controls._results[0].value='someValue'
 }
```
I will get this error;
I changed `ngAfterViewInit` to `ngAfterContentInit` and it worked;
but when my page insert  multiple of this component ,I will also get this error;
*So I have to use it like this*:
```js

ngAfterContentInit(){
  setTimeout(()=>{this.controls._results[0].value='someValue'},1)
}

```
This is a bad way. Sometimes it cause the page to flash.
