### ISSUE TITLE
Previous version 2.4.8 does not resolve absolute module paths after new version 4.0.0 was released

### ISSUE THREAD

**Issue by rgrstvcr** [angular/angular#15474]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Absolute module paths are not being resolved causing this Error: Cannot find module.
The error is caused when trying to route and navigate to any module.

**Expected behavior**

We didn't have this issue with version 2.4.8 until today Friday Match 24th.

**Minimal reproduction of the problem with instructions**

Use version 2.4.8 with an application with several modules and routes.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.X

Angular version: 2.4.8
Angular/CLI version: 1.0.0.rc-0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
