### ISSUE TITLE
Bindings on `class` clobber all existing css classes

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#15476]
Example: http://plnkr.co/edit/MVGtfe8LL8RyPoI6PaOc?p=preview

If any element has a binding on the `class` property, it will blindly overwrite the existing element classes. `ngClass` will intelligently add and remove its given class (or classes). 

Should Angular keep this behavior for basic `class` bindings, or should the default behavior match `ngClass`?

(@mhevery asked me to open this issue for discussion)

**Comment by DzmitryShylovich** [comment]
There's already such issue https://github.com/angular/angular/issues/7289 :)

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #7289. Please subscribe to that issue for future updates.

**Comment by jelbourn** [comment]
@IgorMinar it's only the same issue if you consider the current `class` binding behavior to be wrong.
