### ISSUE TITLE
Angular@4.0.0 doesn't have a proper JSONPBackend for platform-server

### ISSUE THREAD

**Issue by diestrin** [angular/angular#15471]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

**Expected behavior**
When doing a jsonP call in server using platform-server, the server crashes. There's no JsonpBackend in platform-server, the browser version is being used.

**Minimal reproduction of the problem with instructions**
https://github.com/diestrin/ng-universal-demo/tree/issue-report/angular-4-json-on-server
Do a jsonp call and render using platform-server

**What is the motivation / use case for changing the behavior?**
JsonP should work in both scenarios, in server should be translated to an http call

**Please tell us about your environment:**
Express

* **Angular version:** 4.0.0

* **Browser:** [all]
 
* **Language:** [TypeScript 2.2]

* **Node:** `node --version` =   6.9.1

* **Error Log:**
```
ERROR { Error: Uncaught (in promise): ReferenceError: document is not defined
ReferenceError: document is not defined
    at e.build (/Users/diestrin/Documents/Projects/18Techs/Weather/ng-universal-demo/dist/main.js:463:3120)
    at e._subscribe (/Users/diestrin/Documents/Projects/18Techs/Weather/ng-universal-demo/dist/main.js:470:725)
    at e._trySubscribe (/Users/diestrin/Documents/Projects/18Techs/Weather/ng-universal-demo/dist/main.js:1:1060)
...........
```

**Comment by vikerman** [comment]
will look into it

**Comment by diestrin** [comment]
Anyone having a similar issue, can temporally work around it by providing a `JSONPBackend` like this `{ provide: JSONPBackend, useClass: XHRBackend }`. Do this in server code only, for browser use the normal providers.

**Comment by vikerman** [comment]
We want to understand the use case better. JSONP is not a server thing. If your endpoint supports only JSONP you should use the regular Http and then do the unwrapping yourself in the server.

For now we would probably throw a better error when you use JSONP on the server.

**Comment by diestrin** [comment]
I don't want JSONp in my server, there's no reason for that. But I need to have the same code running on client and server. So in case of a component using JSONp for browser requests, it should do Http calls on server, without me having to check if I'm on server or not.

The old angular/universal does this: https://github.com/angular/universal/blob/2.x/modules/platform-node/node-http.ts#L446

**Comment by vikerman** [comment]
If you hit the same JSONP endpoint on the server, how do you extract the json from the response? Isn't that code you have to have only on the server? 

We recommend having a provider for the service that uses the jsonp implementation on the client and http on the server - each using different end points.

**Comment by diestrin** [comment]
Not really. Any JSONP call on server will just be converted to HTTP, no extraction needed, since it's not an actual JSONP response. That's why I can "patch" this in my app with `{ provide: JSONPBackend, useClass: XHRBackend }`.

The service split on server/browser would work, although I still think it's too much for something that simple, specially if you have a lot of endpoints. Anyway, feel free to close this if you don't think it makes sense. I already have my patch :)
