### ISSUE TITLE
No interface declaration needed for the OnInit hook to be called

### ISSUE THREAD

**Issue by moniuch** [angular/angular#15488]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Classes do not need to declare `implements` in order for the OnInit hook to be actually called. Might apply to other hooks as well.

**Expected behavior**

Not being an expert, I would expect the implementation method would not be called without proper declaration.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/j1Ge1Qgs6NmclIBCDsJP?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

2.4.9, 4.0.0

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Independent

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
2.4.9: TS 2.2.1, 4.0.0: Plunkr env

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
Since interfaces don't exist at runtime it's impossible for the framework to check if a component is *implementing* an interface, therefore it is not needed, however it is definitely recommended

**Comment by DzmitryShylovich** [comment]
yeah, see https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#interface-optional

**Comment by moniuch** [comment]
True, sorry for the noise.

**Comment by jotatoledo** [comment]
If your problem is solved consider to close this issue
