### ISSUE TITLE
View not reflecting change when changing the bonded variable updated with repro

### ISSUE THREAD

**Issue by crackrKD** [angular/angular#15485]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

On a event if a element state changes and using the script if a condition is true again the state changes then the change is not being reflected in the view but reflected in the bonded model variable. For example, Consider a input type checkbox and using ngModel bind it to a variable check and adding a click event which changes the state of checkbox to false always. Now on clicking the checkbox checkbox should never be checked but it doesn't happen that way. 

**Expected behavior**

When clicking on checkbox --> ngModel variable should and it does change in every case.
But when clicking on checkbox --> a event fires --> which changes ngModel variable bonded to the checkbox --> It should reflect the bonded value state in the view.

**Minimal reproduction of the problem with instructions**

Steps to reproduce.
AT plunkr --> https://plnkr.co/edit/AA8EEwhZhb1RfTehvVfO?p=preview
1. npm install -g @angular/cli@latest
2. npm install -g typescript
3. ng new hello-checkbox
4. go to src/app/app/component.html and add the following line of html
<input type="checkbox" value="Google" [(ngModel)]="check" (click)="change()"/>Google
5. go to src/app/app.component.ts and replace the class AppComponent with mine
export class AppComponent {
  title = 'app works!';
  check : boolean = true;

  change (){
    console.log("check value : " + this.check);
    this.check = false;
  }
}
6. ng serve 

now when you click on the checkbox it gets checked even if the `check` variable is false.

**What is the motivation / use case for changing the behavior?**

When displaying a list of checkbox elements if it is needed that not to allow more than 5 checkbox to get tick then in this scenario even if a user checks 6th checkbox element then if should automatically be deselected.

**Please tell us about your environment:**

OS : Win 10
IDE : Visual Studio Code
package Manager : node.js

* **Angular version:** 2.0.X

@angular/cli: 1.0.0
node: 7.7.3
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Browser : all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
language : all [tested]

* **Node (for AoT issues):** `node --version` =   v7.7.3

**Comment by DzmitryShylovich** [comment]
Please reproduce in plunkr

**Comment by crackrKD** [comment]
https://plnkr.co/edit/AA8EEwhZhb1RfTehvVfO?p=preview

**Comment by DzmitryShylovich** [comment]
what ng version do you use? `2.0.0-alpha.45` like in your plunkr? :)

**Comment by crackrKD** [comment]
{
  "name": "hello-checkbox",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}

My original project uses the following package.json but the problem persist in 2.0.0-alpha.45

**Comment by crackrKD** [comment]
Angular 1.4.8 this is not a problem but most later versions it is
https://plnkr.co/edit/oGj3qjVzzihQ6LI5HPkN?p=preview

**Comment by ericmartinezr** [comment]
@crackrKD you're having issues with versions. Forget about angular2 alpha 45, forget about angular 1.4.8. You're reporting an issue with angular 4, stick to it. 

Use this plnkr http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview which @DzmitryShylovich provided you above, to reproduce your issue. There's no point on reproducing it in other versions (angularjs has nothing to do with angular4+ btw and angular4+ is far far away from alpha versions)

**Comment by crackrKD** [comment]
plunkr 
http://plnkr.co/edit/FEtlPyENG2kHkTFzJeYm?p=preview

**Comment by ghetolay** [comment]
You should just return false on your click listener if you want to hijack original behavior.
Doing stuff during click doesn't stop the native handler to set the checkbox as true (after your click listener function).

And your model is being updated but after your click handler (you can see it by using a setter for example).

**Comment by crackrKD** [comment]
plunkr 
http://plnkr.co/edit/FEtlPyENG2kHkTFzJeYm?p=preview

If i return false then the state of the checkbox doesn't change always.

As you said "Doing stuff during click doesn't stop the native handler to set the checkbox as true"
but if during the click event of one checkbox I make other checkbox change their state then it works great.

**Comment by ghetolay** [comment]
Issues are not meant to provide support request. 
You can post on stackoverflow or ask on the gitter room if you need help.

**Comment by chuckjaz** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
