### ISSUE TITLE
Angular Material 

### ISSUE THREAD

**Issue by mkrtchyankaro** [angular/angular#15496]
The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): ng:///MdAutocompleteModule/MdAutocomplete.html@0:0

Please fix that from Angular Material package

**Comment by pkozlowski-opensource** [comment]
Wrong repo: https://github.com/angular/material2
