### ISSUE TITLE
Async validators and form valid state

### ISSUE THREAD

**Issue by hassanasad** [angular/angular#15497]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
I have an async validator in my reactive forms. When an HTTP request is sent to the API the form becomes valid (even though some of the other validators on other fields are still not passing) until the response comes back (when it sets the form invalid again). If for some reason the API call never returns the response the form stays valid

**Expected behavior**
The form should not become valid if other field validators are not passing.

**Minimal reproduction of the problem with instructions**
I am using similar logic to this plunker for Async validation
http://plnkr.co/edit/zTveSyiNehqKGzsJrfYG?p=info

**What is the motivation / use case for changing the behavior?**
A user is able to submit the form even though some of validations have not passed yet by clicking the submit button which becomes active when form is valid (which it shouldn't be).

**Please tell us about your environment:**

* **Angular version:** 2.0.X
4.0.0

* **Browser:**
Tested only on Chorme
 
* **Node (for AoT issues):** `node --version` =   
7.7.4

**Comment by hassanasad** [comment]
Similar problem has been reported here http://stackoverflow.com/questions/38509357/angular-2-with-async-form-field-validation

**Comment by DzmitryShylovich** [comment]
what angular version do you use?

**Comment by hassanasad** [comment]
@DzmitryShylovich  NG 4.0.0

**Comment by DzmitryShylovich** [comment]
Ok, then your plunkr is outdated. Please reproduce using http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by Toxicable** [comment]
@hassanasad Works fine here https://plnkr.co/edit/7S3lpEVvf9bnYS3vUqMV?p=preview 
can you confirm if this is the same setup you have?

**Comment by hassanasad** [comment]
@DzmitryShylovich , @Toxicable :: 
You will notice that in certain cases form.valid and form.invalid both become false

Please checkout this plunker: http://plnkr.co/edit/qw17Tg0dtn5bVrKNeJJI?p=info

**Comment by DzmitryShylovich** [comment]
> You will notice that in certain cases form.valid and form.invalid both become false

because the status is PENDING. See https://github.com/angular/angular/issues/11432#issuecomment-245670999

**Comment by hassanasad** [comment]
@DzmitryShylovich - Ah thanks. I was not aware of those other form states. Not a bug then, thanks for your help :)
