### ISSUE TITLE
Angular 4 - Platform Server - Document serialization broken

### ISSUE THREAD

**Issue by diestrin** [angular/angular#15494]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Node attributes that evaluates to false will cause the server to break when serializing.
This is only when `enableProdMode()` is not called.

**Expected behavior**
Angular to normalize the attribute as a string instead of boolean

**Minimal reproduction of the problem with instructions**
https://github.com/diestrin/ng-universal-demo/tree/issue-report/angular-4-false-attribute-parse
A template like `<test-component [test]="value"></test-component>`
This will call the [normalizeDebugBindingValue](https://github.com/angular/angular/blob/5efc86069ff92d980bb460c15deccb1e0fff9363/packages/core/src/view/services.ts#L278) but it's only converting it to string if the value evaluates to true `return value ? value.toString().slice(0, 30) : value;` which is incorrect.
This causes parse5 to break when [trying to scape](https://github.com/inikulin/parse5/blob/fabc6d8eaba7904ae667dd20741bed9ea1a39ca0/lib/serializer/index.js#L35) the attribute.

**What is the motivation / use case for changing the behavior?**
Server crashes trying to load the pages

**Please tell us about your environment:**
Express

* **Angular version:** 4.0.0

* **Browser:** [all]
 
* **Language:** [TypeScript 2.2]

* **Node:** `node --version` =   6.9.1

**Comment by vikerman** [comment]
Thanks for the repro! Will look into it

**Comment by diestrin** [comment]
BTW, anyone running with this same issue (which is currently a blocker for me), can work around it by calling `enableProdMode()`.This way the debugServices will never be created and this code will never be called.
