### ISSUE TITLE
deprecated commands not reported in TypeScript in ng4

### ISSUE THREAD

**Issue by born2net** [angular/angular#15504]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Deprecated commands not reported in TypeScript in ng4
for example, see image below. I see the cross out in WebStorm but if I would never open this file I wouldn't know it's been deprecated.

![capture](https://cloud.githubusercontent.com/assets/5090936/24331843/3497b11e-11f1-11e7-8c96-18882394310e.PNG)

**Expected behavior**
Expect TS to show the errors, at least as warnings 

**Minimal reproduction of the problem with instructions**
I can provide a project if need be

```
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/animations: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
@angular/language-service: 4.0.0
@ngtools/webpack: 1.3.0

```

**Comment by DzmitryShylovich** [comment]
> Expect TS to show the errors, at least as warnings

how it's related to angular? :)

**Comment by born2net** [comment]
well it is, but that's not the right answer.
The issue was:
importing
```
import {trigger, transition, animate, state, style} from "@angular/animations";
```
instead of from core 
changed

**Comment by DzmitryShylovich** [comment]
See https://github.com/Microsoft/TypeScript/issues/390

btw VSC doesn't even cross out deprecated methods :)

**Comment by born2net** [comment]
ok tx!
