### ISSUE TITLE
Eager providers and Injector.get() can cause errors

### ISSUE THREAD

**Issue by ph55** [angular/angular#15501]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After updating from `4.0.0-rc.2` to `4.0.0` `Router` not injected as expected

**Expected behavior**

Should be injected as expected 

**Minimal reproduction of the problem with instructions**

Plunker: http://plnkr.co/edit/ogCHjeYuCDM8vNLdwAFx?p=preview

Update from `4.0.0-rc.2` to `4.0.0`

`ConfigService` provided in `AppModule` as `APP_INITIALIZER`
```
  providers: [
    ConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: configServiceFactory,
      deps: [ConfigService],
      multi: true
    }
  ],
```

`ApiService` injected manually from `ConfigService`
```
@Injectable()
export class ConfigService {

  private api: ApiService;

  public constructor(
    private injector: Injector
  ) {

    // Avoid cyclid dependencies, inject manually:
    this.api = injector.get(ApiService);
  }
```

`router` is undefined when injected in `ApiService`
```
import { Http, Headers, RequestOptionsArgs, Response } from '@angular/http';
import { Router } from '@angular/router';

@Injectable()
export class ApiService {

  constructor(
    private router: Router,
    private http: Http
  ) {

    console.log(router, 'router'); // undefined
    debugger;
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

@angular/cli: 1.0.0
node: 7.4.0
os: win32 x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/compiler-cli: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/platform-server: 4.0.0
@angular/router: 4.0.0
@angular/material: 2.0.0-beta.2
@angular/flex-layout: 2.0.0-rc.1
@angular/cli: 1.0.0
@ngtools/webpack: 1.3.0

* **Angular version:** 4.0.0

* **Browser:** all
 
* **Language:** TypeScript 2.2.1

* **Node (for AoT issues):** `node --version` =  7.4.0

### The log given by the failure.

```
core.es5.js:1085 ERROR TypeError: Cannot read property 'url' of undefined
    at CatchSubscriber.selector (api.service.ts:127)
    at CatchSubscriber.error (catch.js:104)
    at MapSubscriber.Subscriber._error (Subscriber.js:128)
    at MapSubscriber.Subscriber.error (Subscriber.js:102)
    at XMLHttpRequest.onLoad (http.es5.js:1210)
    at ZoneDelegate.invokeTask (zone.js:363)
    at Object.onInvokeTask (core.es5.js:4136)
    at ZoneDelegate.invokeTask (zone.js:362)
    at Zone.runTask (zone.js:166)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:416)
defaultErrorLogger @ core.es5.js:1085
ErrorHandler.handleError @ core.es5.js:1145
next @ core.es5.js:4774
schedulerFn @ core.es5.js:3848
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3834
NgZone.triggerError @ core.es5.js:4205
onHandleError @ core.es5.js:4166
ZoneDelegate.handleError @ zone.js:334
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:416
Navigated to http://localhost:4200/
core.es5.js:3053Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): ng:///MdAutocompleteModule/MdAutocomplete.html@0:0
Console.warn @ core.es5.js:3053
TemplateParser.parse @ compiler.es5.js:11508
JitCompiler._compileTemplate @ compiler.es5.js:25195
(anonymous) @ compiler.es5.js:25119
JitCompiler._compileComponents @ compiler.es5.js:25119
createResult @ compiler.es5.js:25004
ZoneDelegate.invoke @ zone.js:330
Zone.run @ zone.js:126
(anonymous) @ zone.js:679
ZoneDelegate.invokeTask @ zone.js:363
Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
api.service.ts:31 undefined "router"
```

![2017-03-26 15_39_04-mtcrm](https://cloud.githubusercontent.com/assets/1386622/24331329/793a21a0-123a-11e7-8f57-195271c76098.png)

**Comment by DzmitryShylovich** [comment]
Please provide a small repro. You can use http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue as a starting point

**Comment by ph55** [comment]
Here you go. Open console

http://plnkr.co/edit/ogCHjeYuCDM8vNLdwAFx?p=preview

**Comment by Provson** [comment]
Same problem in my project

**Comment by vicb** [comment]
Issue is 
```ts
AppModuleInjector.prototype.createInternal = function() {
  var self = this;
  //...
  // 1. The injector is not fully initialized when the ConfigService is created
  self._ConfigService_4 = new jit_ConfigService37(self);
  // ...
  // 2. the router is not only initialized after
  self._Router_20 = jit_setupRouter59(self._ApplicationRef_8,self._UrlSerializer_12,self._RouterOutletMap_13,self._Location_16,self,self._NgModuleFactoryLoader_18,self._Compiler_17,self._InjectionToken_ROUTES_19,self._InjectionToken_ROUTER_CONFIGURATION_14,self.parent.get(jit_UrlHandlingStrategy60,null),self.parent.get(jit_RouteReuseStrategy61,null));

}
```

**Comment by Nehmiabm** [comment]
When would this bug be fixed? I'm still facing the issue. Please notify

**Comment by Provson** [comment]
Me too, my project is blocked

**Comment by natedanner** [comment]
I was blocked also but was able to work around this issue with AOT by following https://github.com/angular/angular-cli/issues/5762#issuecomment-295670906. Injecting the injector into my service used with APP_INITIALIZER and waiting for it to be initialized. 

`import { LOCATION_INITIALIZED } from '@angular/common';
import { Injectable, Injector } from '@angular/core';
import { Http } from '@angular/http';

// Services
import { AnalyticsService } from './services/analytics.service';
import { SettingsService } from './services/settings.service';

@Injectable()
export class AppConfigService {
	private isInit = false;

	/**
	 * Creates an instance of AppConfigService.
	 * @param {Injector} injector - angular injector
	 * @param {SettingsService} settingsService - service used to load config from server
	 * @param {Http} http - angular http
	 * @param {AnalyticsService} analyticsService - Injected here to instantiate only
	 *
	 * @memberOf AppConfigService
	 */
	constructor(
		private injector: Injector,
		private settingsService: SettingsService,
		private http: Http,
		private analyticsService: AnalyticsService) {}

	// Initializes the settings service with data from server as app starts
	load(): boolean|Promise<boolean> {
		const p: Promise<any> = this.injector.get(LOCATION_INITIALIZED, Promise.resolve(null));
		return p.then(() => {
			if (!this.isInit) {
				return this.settingsService.init();
			} else {
				return true;
			}
		});
	}
}
`

**Comment by kaushalshah45** [comment]
Any update on this?

**Comment by tbosch** [comment]
This also breaks component providers when used with `Injector`, e.g.
```
import { Component, Injectable, Injector } from '@angular/core';

@Injectable()
export class MyService {
  say(): void {
    console.log('saying hi');
  }
}

@Component({
  selector: 'my-app',
  template: `<h1>Hello {{name}}</h1>`,
  providers: [MyService]
})
export class AppComponent {
  name = 'Angular';
  constructor(injector: Injector) {
    let service = injector.get(MyService);
    service.say();
  }
}
```

**Comment by Provson** [comment]
Always blocked in version 2.4.10
Any update ?

**Comment by Provson** [comment]
Any update ?

**Comment by ph55** [comment]
![ezgif-2-b15b8fa300](https://user-images.githubusercontent.com/1386622/27768576-86a07362-5f1f-11e7-9974-65259d140076.gif)

**Comment by Provson** [comment]
I found a trick :

    private _userService: UserService;
    private _router: Router;

    constructor(private injector: Injector) {
        //Work
        setTimeout(() => this._userService = injector.get(UserService));
        setTimeout(() => this._router = injector.get(Router));
        //Don't work
        //this._userService = this.injector.get(UserService);
        // this._router = this.injector.get(Router);

**Comment by Provson** [comment]
Any update ???

**Comment by Oceris** [comment]
Is there any known workaround for this issue?

**Comment by Korbraan** [comment]
Still facing the issue (Angular 5.2.0). Any workaround ?

**Comment by SkyLax** [comment]
Hi everyone, I'm currently facing this problem, any updates ?
Thanks

**Comment by ZbigiMan** [comment]
I have the same problem in Angular 6. Workaround is putting `injector.get` into `setTimeout` like Provson did it.
