### ISSUE TITLE
aio: add proper marketing pages

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#15519]

**Comment by lazaridis-com** [comment]
@petebacondarwin , may I ask something here:

Does this mean to "polish" e.g. the content within https://angular.io/features.html with the usual graphics, screenshots etc., to make it all more "shiny"?

If yes, then this is an absolute need (It was something i missed when I first hit on the angular website)

**Comment by petebacondarwin** [comment]
@lazaridis-com in a word, yes.

**Comment by wardbell** [comment]
Closing as non-actionable. We need specifics. All pages that are required to be present are present, whatever their lack of polish.
