### ISSUE TITLE
"Test a component with an external template" example from docs fail

### ISSUE THREAD

**Issue by apieceofbart** [angular/angular#15513]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I wanted to test component with templateUrl. 
I am following the docs and have cloned the quickstart repo.
I created files for the banner component as stated here: https://angular.io/docs/ts/latest/guide/testing.html#!#component-with-external-template
Just to be 100% sure I have copied the 4 banners component files exactly as here:
https://embed.plnkr.co/?show=preview&show=app%2Fbanner.component.spec.ts

In all of the tests I see error:

Failed: Uncaught (in promise): Failed to load banner.component.html
Error: Uncaught (in promise): Failed to load banner.component.html
Error: This test module uses the component BannerComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/3791384/24344458/e6f28250-12cb-11e7-8397-0599fda34a8c.png)

**Expected behavior**
I expect tests to pass

**Minimal reproduction of the problem with instructions**
The best way is to clone the quickstart repo and the 4 banner files I mentioned above and run npm t

**What is the motivation / use case for changing the behavior?**
If there is no bug then I think docs are wrong as I was following them.

**Please tell us about your environment:**
Windows 7, Chrome etc.

* **Angular version:** 2.0.X
4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tried Chrome only
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Please repost this issue on https://github.com/angular/angular.io/issues

**Comment by apieceofbart** [comment]
Thanks for info, I see this bug is already reported there.
