### ISSUE TITLE
How to use external libraries for AOT?

### ISSUE THREAD

**Issue by JainamJhaveri** [angular/angular#15514]
* **Environment:**
Operating system: Ubuntu 16.04 , IDE: Atom

* **Angular version:** 2.3.1

* **Browser:** [ Chrome 57.0.2987.110 ]
 
* **Language:** [  TypeScript 2.1.6 | ES6 ]

* **Node (for AoT issues):** `node --version` =6.9.5   

When do the scripts inside script tag actually get executed during AOT ?

In one of my components, I have used minified amazon s3 sdk. ('aws-sdk-2.23.0.min.js')
In JIT, my app is working fine when I use

`declare let AWS: any;`

But in AOT it produces following error:
```
Cannot read property 'S3' of undefined
TypeError: Cannot read property 'S3' of undefined.
```

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by JainamJhaveri** [comment]
Okay, I have added the question on StackOverflow as well.
http://stackoverflow.com/questions/43041069/how-to-use-external-libraries-for-aot-in-angular2
