### ISSUE TITLE
One-time property binding possible?

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1551]
I have the following scenario:

```html
<component
   [content]="data.value"
   (change)="updateData()"
></component>
```
`data` is an object that has `value` which is passed to component. Component fires `change` event if there's a change happening in the given value. The event handler writes the new value back into `data.value`

The problem: whenever `data.value` changes, `(change)` event is fired. Which results in an infinite loop. What's the best way to deal with that?

Is there a way to setup a property binding that is only evaluated once?

**Comment by tbosch** [comment]
Pascal, you could take on the strategy that a Dom input field uses:
When 'content' is set programmatically (in your case 'content' is changed
via change detection), don't fire an event. Only fire an event when the
value changes via the user or via some data that is not the input to the
component...

**Comment by PascalPrecht** [comment]
@tbosch right, I could set an internal flag that knows wether this event needs to be fire or not. I even think, If I set the initial value programatically is already enough, but that I'd need to figure out.

**Comment by mhevery** [comment]
I think that events should only be fired due to other events and not due to value changes. 

We should make that a best practice. 

So I think angular is doing the right thing here. I am not even sure how we could detect these kinds of loops.

**Comment by PascalPrecht** [comment]
@mhevery in my particular case, my component wraps the ace editor which fires it's own events. So basically what happens is this:

```js
@Component({
  selector: 'ace-editor',
  lifecycle: [onChange]
})
class AceEditor {
  constructor(el:NgElement) {
    this.editor = ace.edit(el.domElement);
    this.change = new EventEmitter();

    this.editor.on('change', () => {
        this.change.next();  // gets emitted whenever a change to the editor happens
    });
  }

  onChange() {
    let content = ... 
    this.editor.setValue(content);  // triggers `change`
  } 
}
```

Maybe the use of `onChange()` is wrong here. Would love to hear your opinions on that.

**Comment by mhevery** [comment]
sounds like you need to wrap the `this.editor.setValue(content)` in a try-finally block and suppress  firing `this.change.next()` when it is a result of setting a new value. Event's should only happen due to user interactions not setting a property. (This needs to be documented as best practice.)

**Comment by PascalPrecht** [comment]
@mhevery could you be a bit more specific on what exactly you'd do with a try-finally block? There's no exception thrown, so I'm not sure how I can use that construct to suppress anything...
