### ISSUE TITLE
binding ngFor with <tr>

### ISSUE THREAD

**Issue by AbbeYassine** [angular/angular#15511]
**I'm using a project angular-cli and I have an issue with binding ngFor with** `tr`

the html code is like : 

          
```
           <tbody>
            <tr *ngFor="let event of events">
              <td>{{event.title}}</td>
              <td>{{event.address}}</td>
              <td>{{event.time}}</td>
              <td>
                {{event.startDate}}
              </td>
              <td>
                {{event.endDate}}
              </td>
            </tr>
            </tbody>
```

component.ts 

```
events: Event[] = [];

  constructor() {
    this.events = [
      {
        description: "de",
        endDate: "12/02",
        id: "1234",
        nbInterested: 21,
        organisation: new Organisation(),
        time: "10:00 AM",
        startDate: "10/02",
        photo: "",
        title: "Event 1",
        address: "sfax , tunis"

      }
    ];
}
```
and the output is : 

> Can't bind to 'ngForOf' since it isn't a known property of 'tr'

works fine with `<div>`
any help please , thanks .

**Comment by Toxicable** [comment]
Works fine here https://plnkr.co/edit/mJR5VHrYOcMHjjNO0kl5?p=preview
In the future please fill out the Issue template correctly. Also this issue tracker isn't suitable for support requests, please use [Gitter](https://gitter.im/angular/angular) or [StackOverflow](http://stackoverflow.com/) using tag `angular`

**Comment by kr-pawan** [comment]
`*ngFor` requires that you must have `CommonModule` in your list of `@NgModule imports` for the module in which your component resides.
