### ISSUE TITLE
Will angular2 support Dart enums in templates?

### ISSUE THREAD

**Issue by jrote1** [angular/angular#1552]

**Comment by mhevery** [comment]
Maybe.

**Comment by jrote1** [comment]
What's the reason for not doing this?

**Comment by jrote1** [comment]
@mhevery Is it possible this will still be done?

**Comment by zoechi** [comment]
@jrote1 https://angular.io/docs/ts/latest/guide/template-syntax.html search "Expression context" and "Statement context". Enums are in the global namespace.
