### ISSUE TITLE
Improve the error message for a invalid *ngFor expression

### ISSUE THREAD

**Issue by matsko** [angular/angular#15523]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Try creating a ngFor look in a component template with an invalid statement (in this case the prefixed `let` token is missing):

```html
            <div *ngFor="item of items" class="item">
              {{ item }} 
            </div> 
```

**Expected behavior**
It would be nice to have a clear error message that informs the user that the ngFor expression is invalid, instead of something like this:

```
Error: Template parse errors:
	Can't bind to 'ngFor' since it isn't a known property of 'div'. ("
	            <div [ERROR ->]*ngFor="item of items" class="item">
	              {{ item }}
	            </div>
```

**Minimal reproduction of the problem with instructions**
Just follow the steps above.

**What is the motivation / use case for changing the behavior?**
NgFor is the most important templating feature in Angular and it looks like this error can show up quite a bit. Let's make this easier on the user.

**Please tell us about your environment:**
Works anywhere. This is in the angular/angular project.

* **Angular version:** 2.0.X
4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome (running on Karma).
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

* **Node (for AoT issues):** `node --version` =   
This is running in runtime. Not sure how this looks post AOT.

**Comment by DzmitryShylovich** [comment]
Duplicate https://github.com/angular/angular/issues/14641

**Comment by matsko** [comment]
Ah perfect. Closing. Thank you.
