### ISSUE TITLE
upgrade/static not listed in API documentation

### ISSUE THREAD

**Issue by epelc** [angular/angular#15524]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The API section doesn't list anything in `@angular/upgrade/static`(Example: `UpgradeComponent`).

No entry for `UpgradeComponent`
https://angular.io/docs/ts/latest/api/#!?query=upgradecomponent

No entries for `upgrade/static`
https://angular.io/docs/ts/latest/api/#

Note the `upgrade/static` files have documentation comments in them so I'd imagine it's a bug somewhere in the build system? I haven't looked into the cause.

**Comment by gkalpak** [comment]
Good catch! :+1:
(Probably an angular.io issue. @petebacondarwin is looking into it.)

**Comment by petebacondarwin** [comment]
Here is the problem:

```
'upgrade/static.ts'
```

https://github.com/angular/angular.io/blob/master/tools/api-builder/angular.io-package/index.js#L73

The path to the static library should be

```
'upgrade/static/index.ts'
```

**Comment by petebacondarwin** [comment]
This should fix it: https://github.com/angular/angular.io/pull/3450

**Comment by gkalpak** [comment]
The fix is now live: https://angular.io/api?query=upgrade
