### ISSUE TITLE
aio: Invalid links to "defined in" page in docs

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#15522]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
*Defined in* links, as in:
```
exported from router/index, defined in router/src/directives/router_outlet.ts
```
are broken for all components, directives, pipes etc.

**Expected behavior**
Links should not be broken

**Minimal reproduction of the problem with instructions**
Go to: https://angular.io/docs/ts/latest/api/router/index/RouterOutlet-directive.html
and click on "router/src/directives/router_outlet.ts"

* **Angular version:** 4.0.0

 
* **Language:** all

**Comment by gkalpak** [comment]
This has been fixed in the new version with #15263. It is still an issue on the current version.
Can you please reopen on https://github.com/angular/angular.io (if it doesn't been reported already)?
