### ISSUE TITLE
<input> `required` attribute not respected (4.0.0 regression)

### ISSUE THREAD

**Issue by buu700** [angular/angular#15531]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

Submitting a form with an empty `<input required />` succeeds.

**Expected behavior**

As with 2.x, the submit event should be blocked and the browser should display an error message message like this one:
<img width="197" alt="screen shot 2017-03-27 at 3 06 57 pm" src="https://cloud.githubusercontent.com/assets/415435/24373351/117fbe56-12ff-11e7-98ca-04188bd8734e.png">

**Minimal reproduction of the problem with instructions**

Click the submit button in a form like this:

```
<form (submit)='doSomething()'>
	<input type='text' name='text' required />
	<input type='submit' />
</form>
```

**What is the motivation / use case for changing the behavior?**

Functionality regression.

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:** Chrome 57
 
* **Language:** TypeScript 2.2.1

* **Node (for AoT issues):** 6.10.1

* **Operating System:** Debian Jessie (in a Docker container on OS X El Capitan)

**Comment by DzmitryShylovich** [comment]
Angular automatically has added `novalidate` attribute since 4.0 . To disable it add `ngNativeValidate`:
```
<form ngNativeValidate>...</form>
```

**Comment by buu700** [comment]
Ah, that was the problem. Thanks!

Looking back at the changelog, I see that this change was discussed in some of the RC feature bullets, but never listed as a breaking change; might be worth adding it to the breaking changes for others who may run into this in the future.

**Comment by DzmitryShylovich** [comment]
@StephenFluin can you please update the changelog and your migration app with this change?

**Comment by rwngallego** [comment]
This should be also mentioned in the official docs. I don't see any reference to this breaking change.

**Comment by kemsky** [comment]
Is there any way disable this behavior without adding directive to every form in the application??

**Comment by StephenFluin** [comment]
@kemsky In general our recommendation is to choose one forms technique. If you don't include FormsModule in your module, then the forms directives won't apply and native validation will work as-is. If you add FormsModule, most developers are looking to use the validation capabilities of the FormsModule, and use its status to manage the submission of forms. @kara might have other thoughts as well.

**Comment by kimamula** [comment]
Is this still correct?

> Caution: Use these HTML5 validation attributes in combination with the built-in validators provided by Angular's reactive forms. Using these in combination prevents errors when the expression is changed after the template has been checked.

https://angular.io/guide/reactive-forms#step-2-making-a-field-required

**Comment by wondering639** [comment]
> Is this still correct?
> 
> > Caution: Use these HTML5 validation attributes in combination with the built-in validators provided by Angular's reactive forms. Using these in combination prevents errors when the expression is changed after the template has been checked.
> 
> https://angular.io/guide/reactive-forms#step-2-making-a-field-required

I doubt it: One can use the developer tools to see that even Angular 8 still adds novalidate to the form tag. So any validation isn't used anyways. Yet I'd also be happy about an official statement about this and a correction of the documentation.
