### ISSUE TITLE
Unused Parameters in Ng Factory code

### ISSUE THREAD

**Issue by hansl** [angular/angular#15532]
I'm submitting a Bug Report.

## Current Behaviour

Running `ngc` generates a `View_AppComponent_0()` function that takes the logger as argument. If the component template does not declare any element or text that function is basically empty. The `l` parameter is not used, which can lead to errors when typescript builds it with `noUnusedParameters`.

## Expected Behaviour

The factory code should not take an argument, or should always use that argument so that typescript doesn't show an error.

**Comment by DzmitryShylovich** [comment]
Duplicates https://github.com/angular/angular/issues/11074

**Comment by hansl** [comment]
#11074 is indeed a duplicate, but no one is assigned to it and it's obviously been forgotten. I'll bring it back. Let's keep this comment open for the time being.

**Comment by DzmitryShylovich** [comment]
There's also https://github.com/angular/angular/issues/15475 :)

**Comment by Tragetaschen** [comment]
@hansl Thanks for reminding the angular team. I have noted the tendency to forget about older bugs (two weeks?) on more than one occasion in the angular team. More than 1000 open issues is certainly not a manageable amount of work :-/

**Comment by robertohuertasm** [comment]
Hi, I'm still getting this annoying `'$event' is declared but never used` message whenever I try to use `noUnusedParameters` with AoT compilation. Is there anything that can be done to avoid it? I'm using `v4.1.3`. Maybe the fix hasn't been release yet? Thanks for your time 😉

**Comment by nicolashenry** [comment]
@tbosch @jasonaden As @robertohuertasm said, I confirm that the issue have not been fixed for $event.

**Comment by nicolashenry** [comment]
@tbosch @jasonaden Should I open a new issue about $event and noUnusedParameters ?

**Comment by tbosch** [comment]
Yes please.

**Comment by jrmcdona** [comment]
Was this only fixed in angular/material?  This is an issue outside of material.
Happens n 4.3.6 and CLI 1.3.2 and not using material.   Thanks

**Comment by JWess** [comment]
What was the earliest version of Angular that fixed this problem?
