### ISSUE TITLE
server: inconsistent platform name

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#15538]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
platform fn name is `platformDynamicServer`

**Expected behavior**
platform fn name should be `platformServerDynamic` to be consistent with `platformBrowserDynamic`

cc @vikerman

**Comment by vikerman** [comment]
Maybe it's good because I don't want anyone using platformDynamicServer :) We can deprecate the old one and create the new one for 4.1
