### ISSUE TITLE
Router doesn't navigate when Route is different

### ISSUE THREAD

**Issue by AHelper** [angular/angular#15535]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Resetting the config on a router or changing the route config on an ActivatedRoute does not allow navigation to new Route (same URL).  Doing
```typescript
      this.router.resetConfig([...newConfig, ...POSTLOAD_ROUTES]);
      this.router.navigate(["."], {skipLocationChange: true, relativeTo: this.route});
```
Fails to execute navigation due to last navigation and new URL being equivalent, even though the Route config that the URL represents is not equal.

**Expected behavior**
If the Route from the last navigation and the Route config determined at the time of navigation aren't equal, then navigation should be allowed.

**Minimal reproduction of the problem with instructions**
See: https://plnkr.co/edit/6YU6N4rFbBRq5fZs1ya3?p=preview
1. Click _Custom_ link.
2. Observe that `RouterLoaderComponent` resets config and attempts to navigate, but doesn't trigger a navigation.
3.  Uncomment workaround in `RouteLoaderComponent.ngOnInit`, observe navigation is allowed, intended result.
4. Click _Modify my route!_, observe that lazy loaded module's route config is changed, navigation doesn't execute.
5. Uncomment workaround in src/custom.module.ts -> CustomBaseComponent.modifyRoute, observe intended behavior.

**What is the motivation / use case for changing the behavior?**
Applications that rely on dynamically generating/changing routes can run into problems, such as dynamically loading route subtrees or replacing the current Route config, especially when routing is data-driven.

**Please tell us about your environment:**
Windows 7, npm 3.10.9

* **Angular version:** 4.0.0, 2.4.10, different workarounds used since 2.0.x

* **Browser:** Chrome 57 (Presumably all)

 
* **Language:** TypeScript 2.2

* **Node (for AoT issues):** `node --version` = v4.4.5

**Comment by DzmitryShylovich** [comment]
The router doesn't navigate to the same url. See https://github.com/angular/angular/issues/13340

**Comment by IEvangelist** [comment]
I believe that an invocation to the `.resetConfig` should invalidate the entire route tree and force a re-evaluation. If the URL doesn't change, that should not matter - as the routes that existed before are potentially no longer valid at all.

**Comment by AHelper** [comment]
From what I see in what's trying to be done in #13340 and some of the linked issues, the router is attempting navigation to the same URL, however no navigation actually happens, which makes sense as no state has changed (maybe to re-run guards, etc. that are part of the route). Although in this case, I think the navigation in my plunker is hiding the larger issue here.   If you look at the router as a state machine, then no change in URL means no change in state... except when the config that defines the states has changed.

I would expect that by changing the configuration in the router that it would have to re-evaluate whether or not a state change has occurred.  The URL would not change, however the config defining states would.

Having `.resetConfig` check if the resulting route changed seems logical, except (afaik) the only way to change routes in a lazy loaded module (scoped to that module, not going out to the router and touching routes from the root of the application) is to modify route config on `ActivatedRoute`.  If there was a mechanism to change the config that worked across the board that gave the router a chance to evaluate what changes happened, (like .resetConfig on `ActivatedRoute` or some other way to update config in lazy-loaded modules), then the navigation wouldn't be necessary, just reset the config and check if the resulting states changed to decide whether or not to change state.  I don't know if that could still be called "navigation" at that point, but the resulting state isn't the same.
