### ISSUE TITLE
Webpack 2: Critical dependency: the request of a dependcy is an expression, Angular 4

### ISSUE THREAD

**Issue by lharzenetter** [angular/angular#15549]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm using Angular 4.0.0 with Webpack 2.3.2 and I get some warnings for the angular core:
![image](https://cloud.githubusercontent.com/assets/23058331/24397663/4818c798-13a7-11e7-8cd9-0250235085d2.png)

**Expected behavior**
No warnings would be nice :)

**Minimal reproduction of the problem with instructions**
I think the warnings appear as soon as you try to use webpack 2 in addition with angular 4. So simply setup a angular project with webpack 2.

**Please tell us about your environment:**

I use npm along with the lite server for development on a Windows machine

* **Angular version:** 4.0.0.

 
* **Language:** [TypeScript 2.2.1]

**Comment by DzmitryShylovich** [comment]
Duplicates https://github.com/angular/angular/issues/11580

**Comment by lharzenetter** [comment]
@DzmitryShylovich not really, different lines, different versions....

**Comment by harangue** [comment]
@lharzenetter https://github.com/angular/angular/issues/11580#issuecomment-282705332
