### ISSUE TITLE
VALID Not Found From Import After Updating to Angular 4 

### ISSUE THREAD

**Issue by wuno** [angular/angular#15542]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After updating to Angular 4 when importing VALID from 
`import from "@angular/form/src/model `
I get 

> ERROR in ./src/app/contract/contract.component.ts
> Module not found: Error: Can't resolve '@angular/forms/src/model' in

I tracked the file and the imports seem to exist the same way they did in prior versioning 

>  "@angular/forms": "^2.3.1",

**Expected behavior**

This feature allows checking validity when using form builder. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I use it to check if the form is VALID
**Please tell us about your environment:**

OSX 
MacOS Sierra
version 10.12.3

* **Angular version:** 2.0.X

Angular 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

This never runs in the browser because the application does not compile without errors. 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

* **Node (for AoT issues):** `node --version` =   
v7.2.1

**Comment by hstarorg** [comment]
Why did you need to import from `@angular/forms/src/model`?
Try to `import { something } from @angular/forms`

**Comment by Toxicable** [comment]
Angular v4 no longer supports deep imports like this

**Comment by wuno** [comment]
@hstarorg  Cause I need to use VALID. When I `import from import { something } from @angular/forms` it does not compile and cannot find VALID. 

If it no longer supports deep imports than how do I import VALID?

**Comment by wuno** [comment]
@Toxicable How do I import VALID if it no longer supports deep imports?

@hstarorg Cause I need to use `VALID`. When I
`import { VALID } from @angular/forms`
it does not compile and cannot find `VALID`.

**Comment by DzmitryShylovich** [comment]
@wuno because `VALID` is not exported. Use a string value 'VALID'

Also see https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md

**Comment by wuno** [comment]
@DzmitryShylovich hey thanks a ton for that! That is what I ended up doing. But I am still curious. Is there some way to import things that would otherwise be deep imports? Or do we need we need to find some other way to handle any issue that we run into like that? Like this one for example. Obviously this one ended up being an easy fix but if something a little more complicated come up?

**Comment by DzmitryShylovich** [comment]
> Obviously this one ended up being an easy fix but if something a little more complicated comes up?

If you need something that is not exported open a new issue and we will consider to export it.

**Comment by kara** [comment]
Yep, VALID is not currently exported (private API). You should be able to use `control.valid` or `control.status === 'VALID'` for the same purpose.

**Comment by rokerkony** [comment]
@kara why closing this issue? I think it would be very beneficial to make these constant public again.

**Comment by amostech** [comment]
I would also like to report here that the method isPropertyUpdated from @angular/forms is also not reachable anymore. This created a bug while trying to create a solution for binding contenteditable two-way binding. 

Any chance we can export the methods from @angular/forms? If not, I will use a workaround that doesn't support two-way binding.

**Comment by Toxicable** [comment]
@amostech 
>If you need something that is not exported open a new issue and we will consider to export it.

**Comment by kyr0** [comment]
Hmm..

    import {INVALID} from "@angular/forms/src/model";

Results in:

    Module not found: Error: Can't resolve '@angular/forms/src/model' in '...'

I'm using angular-cli but according to @filipesilva the problem belongs to angular itself. That's how I came here. https://github.com/angular/angular-cli/issues/5735

model.d.ts states:

    /**
     * Indicates that a FormControl is invalid, i.e. that an error exists in the input value.
     */
    export declare const INVALID = "INVALID";

Well, does this mean that I have to use "INVALID" as a string in my code several times? Or to re-implement the interface by myself? 

I consider both a bad practice and would like to use the constants instead.

**Comment by Toxicable** [comment]
@kyr0 `INVALID` is simply a variable which holds the string `'INVALID'`, simply use this yourself or use `control.valid`.
There is no need to export it.
It is not going to change anytime since it would be a breaking change which without the appropriate deprecation period is not allowed to be broken according to the deprecation policy.

**Comment by Toxicable** [comment]
If anything I personally think that `INVALID` and other status constants should be removed and the types should be inline 
eg: `status: 'VALID'|'INVALID'|'PENDING'|'DISABLED'`
which will help with IDE support and enforce the decision made in this issue

**Comment by kyr0** [comment]
@tomically Yep, in my opinion the inline type definition would be a good compromise. IDE's would help highlighting wrong values and the transpiler would throw an error while and there would be no need to export the constants. Would lead to cleaner code instantly and it would reveal bugs in user code immediately.

**Comment by tomically** [comment]
@kyr0 Thanks for mentioning me, but I think you meant @Toxicable , right?

**Comment by Toxicable** [comment]
@kyr0 I actually have a PR for this exact thing here https://github.com/angular/angular/pull/18442

**Comment by kyr0** [comment]
@tomically Yep, I'm sorry :) 
@Toxicable Awesome! 👍
