### ISSUE TITLE
Support multiple renderers

### ISSUE THREAD

**Issue by jack-guy** [angular/angular#15546]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If one provides a custom `RendererFactory2` in a child module and a different `RendererFactory2` in another child module, those children will not have different renderers.

**Expected behavior**

The components of those child modules should use different renderers. If this is too hard to implement, I'd be OK with having to declare my custom renderers with each of the root components I bootstrap. (e.g.)
```
@NgModule({
  bootstrap: [
    { component: ComponentA, renderFactory: CustomRenderFactoryA },
    { component: ComponentB, renderFactory: CustomRenderFactoryB },
  ]
})
```

**Minimal reproduction of the problem with instructions**

```
@Component({
  'selector': 'a',
})
class AComponent () {}

@NgModule({
  declarations: [ AComponent ],
   providers: [{
      provide: RendererFactory2,
      useClass: CustomRendererFactoryA,
   }]
})
export class CustomModuleA {}


@Component({
  'selector': 'b',
})
class BComponent () {}

@NgModule({
  declarations: [ BComponent ],
  providers: [{
    provide: RendererFactory2,
    useClass: CustomRendererFactoryB,
  }]
})
export class CustomModuleB {}


@Component({
  'selector': 'app',
  'template': '<a></a><b></b>'
})
class AppComponent () {}

@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [ ],
  imports: [ CustomModuleA, CustomModuleB ],
  providers: []
})
export class AppModule {
  constructor() {}
}
```

**What is the motivation / use case for changing the behavior?**

Renderers are very powerful and there's no reason why multiple shouldn't be used within the same application. For instance, I'm writing a custom renderer to be used as a game engine that makes WebGL calls. I'd also like to be able to overlay an in-game menu. It seems silly to try to do this with WebGL when the browser makes this stuff so easy - therefore having both the custom renderer and the platform-browser dom renderer would be very helpful.

* **Angular version:** 4.0.0

**Comment by harangue** [comment]
Update - after some effort, I was able to get multiple renderers to work with a lazy loaded module. Perhaps the actual solution is to allow someone to manually create a child dependency injection root when they declare a new module?

Also, perhaps this deserves another issues but [DomRendererFactory2](https://github.com/angular/angular/blob/master/packages/platform-browser/src/dom/dom_renderer.ts#L62) is not publicly exposed which makes reverting back to the `DomRenderer` difficult in this scenario.

**Comment by alxhub** [comment]
It's not necessarily a lazily loaded module that's needed, just a different injector.
