### ISSUE TITLE
canActivateChild should only run once for a navigation

### ISSUE THREAD

**Issue by royling** [angular/angular#15547]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
this is to reopen #12410.

**Current behavior**

With the following routes:
```js
[{
  path: 'root',
  canActivateChild: [RootGuard],
  children: [{
    path: 'branch',
    canActivateChild: [BranchGuard],
    children: [{
      path: 'leaf', component: LeafCmp
    }]
  }]
}]
```
when navigating to `/root/branch/leaf`, RootGuard will run **twice**.
With more levels of nested routes, it's repeating more times. Generally, canActivateChild will run repeatedly for each level of children.

**Expected behavior**

canActivateChild guard should only run once for a navigation.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/1Qs4vFxKOGAedNYagFwq?p=preview

**What is the motivation / use case for changing the behavior?**

This is a bug with canActivateChild, and after walking through all test suites related, no found of cases to test this.

Update: for example, if firing XHR request in the canActivateChild guard, the requests may be repeated, that's apparently a perf issue.

**Please tell us about your environment:**

* **Angular version:** 2.x/4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =   
6.9.x

**Comment by DzmitryShylovich** [comment]
> when navigating to /parent/team/22, ParentGuard will run twice.

please update the plunker with the routes from your example, or use routes from the plunker for the explanation of the problem. thanks

**Comment by royling** [comment]
updated the plunkr.

**Comment by DzmitryShylovich** [comment]
Ok I reread #12410 and I don't think it's a bug. `CanActivate` is what you need.

> no found of cases to test this

To reduce code duplication. See https://github.com/angular/angular/issues/11836

**Comment by royling** [comment]
reducing the level of router config seems like only a workaround...

**Comment by DzmitryShylovich** [comment]
I'm not following. workaround for what? :)
There're 2 guards: CanActivate and CanActivateChild. CanActivate will be called only once. CanActivateChild will be called for every child route. Everything works as designed.

**Comment by royling** [comment]
Sorry, I misunderstood your reference to #11836 about reducing config duplication.

But my issue is not about config duplication.
In the given example, the RootGuard is configured on `/root` node. When debugging, I noticed that it's pushed for checking twice, one for `/root/branch` and the other for `/root/branch/leaf`.

As for my understanding of what it's documented about [the guard](https://angular.io/docs/ts/latest/guide/router.html#!#guards):
>The router checks the CanDeactivate() and CanActivateChild() guards first, from the deepest child route to the top. Then it checks the CanActivate() guards from the top down to the deepest child route.

All guards are checked in order as: `BranchGuard -> RootGuard`, is that right?
But in fact, the checks are `BranchGuard -> RootGuard -> RootGuard (again)`, that seems like a bug.

**Comment by royling** [comment]
closing this issue, see the conclusion I came up with in #15651.

**Comment by stephengardner** [comment]
(worth noting the "conclusion" appears to be that this is a feature not a bug)
