### ISSUE TITLE
aio: server must return zips and plunker.html

### ISSUE THREAD

**Issue by wardbell** [angular/angular#15545]
`<live-example>` wants to serve plunkers from `'content/live-examples/'  and zips from `content/zips/`. Can’t stop the server (whatever server we’re using locally anyway) from trying to relaunch the application with the plunker/zip as the doc page. Examples:
```
http://localhost:4200/content/zips/test/test.zip
http://localhost:4200/content/live-examples/test/eplnkr.html
```
Both of these test links should 404 … but not by pretending to be documents within the app.

**Comment by petebacondarwin** [comment]
We might need some extra logic inside the click catcher: 
https://github.com/angular/angular/blob/master/aio/src/app/app.component.ts#L84

What is the exact behaviour you want? I assume that 404 is not the long term goal. :-)

**Comment by gkalpak** [comment]
FWIW, the preview and staging servers should work as expected (because we don't rewrite URLs to files - i.e. containing a `.` in the last part f the path). It is only an issue on the local server and it should only affect non-existing files (existing `.zip` and `.eplnkr` should be served as expected - although I haven't tried it :grin:).

**Comment by IgorMinar** [comment]
Is it really a must-have?

Why don't we create the plunkers on the fly by generating and submitting a form at runtime (just like we do on docs.angularjs.org)?

Also, why do we need to serve zip files? anyone can download a plunker via the UI there. no?

**Comment by petebacondarwin** [comment]
I think @IgorMinar makes a good point about the zips. If we let Plunker worry about that we would save ourselves a whole load of extra tooling.

**Comment by petebacondarwin** [comment]
Regarding the plunker generation. One requirement is that we need to strip out all of the doc-region tags, which is easier to do at build time I believe, than trying to do it in the browser.

**Comment by wardbell** [comment]
Issue has been addressed.
