### ISSUE TITLE
enableLegacyTemplate option ignored

### ISSUE THREAD

**Issue by hotforfeature** [angular/angular#15555]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Bootstrapping an app with `enableLegacyTemplate` set to false will create a compiler with `enableLegacyTemplate` set to true. This occurs when merging compiler options array:

https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/compiler/src/jit/compiler_factory.ts#L148-L153

```ts
platformBrowserDynamic().bootstrapModule(AppModule, [
  {
    enableLegacyTemplate: false
  }
]);
```

**Expected behavior**
Compiler should not warn about deprecated `<template>` and should not consume them as Angular templates when `enableLegacyTemplate` is false.

Or, if this is *not* the correct way to set `enableLegacyTemplate`, provide clearer documentation on how to set the option.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/3h8VvL6v4jh5HbsHkiwT?p=preview

**What is the motivation / use case for changing the behavior?**
In order to use Polymer with Angular, we must use `<ng-template>` and allow webcomponents to consume `<template>`s regularly.

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:** [all]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =  6.9.5

**Comment by hotforfeature** [comment]
@DzmitryShylovich I see you were working on this, any chance a PR is coming?

**Comment by MickL** [comment]
Does not work for me on AOT build. Yes, i added the option to tsconfig.json
