### ISSUE TITLE
ReactiveForms validators to dynamically update when parameter changes

### ISSUE THREAD

**Issue by pdela** [angular/angular#15553]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When setting validators, the values passed as parameters (i.e. Validators.maxLength(5) ) are stored and never change even if the original parameter is a variable that has been changed by code:
  len:number=5;
  form:FormGroup;
  constructor(private _builder:FormBuilder){
    this.form= this._builder.group({
      name: ['example', Validators.maxLength(this.len)]
    }); 
  }
  changeRule(){
    this.len=10;
    console.log(this.len, form.get('name').status);
  }

Only way to update the value is to set again the validator of the control with the new parameter value. However, this is tricky since there might be multiple validators in the same control and re setting just the maxLength will cancel the others.

**Expected behavior**
Being able to change the value passed as parameter to validators functions dynamically.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/CYOybB3NFyFeGvOxIwTO?p=preview
-->

**What is the motivation / use case for changing the behavior?**
When validation of control is dependent to an external value that may change over time

**Please tell us about your environment:**
Angular CLI, Windows 10, Visual Studio Code

* **Angular version:** 2.0.X
Angular 2.4.1

* **Browser:** [ all ]
Tested only in Chrome, but not relevent as this is an Angular feature
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
>  if the original parameter is a variable that has been changed by code

Primitive types are passed by value. any changes outside a function won't be reflected. 
If you need to change parameters dynamically then create your own validator.

**Comment by pdela** [comment]
You're totally right!
I tried the appraoch before opening the issue, but every time I was generating a new object to pass to the validator in the hope to trigger changedetection (as for pipes for examples).
Instead it was even simpler.
Thanks!
