### ISSUE TITLE
<template> children not appended to content

### ISSUE THREAD

**Issue by hotforfeature** [angular/angular#15557]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With `enableLegacyTemplate` set to false (must be hardcoded in `CompilerConfig`, see #15555 for issue in disabling this option), `<template>` child elements are appended using `templateEl.appendChild(childEl)`. This should be `templateEl.content.appendChild(childEl)` to correctly append child elements to the template's document fragment.

![screen shot 2017-03-28 at 10 25 29 am](https://cloud.githubusercontent.com/assets/14365924/24413412/f2ade5fa-13a0-11e7-9ade-3ab6bf273792.png)

In the above screenshot, the template inside Angular's `<app-root>` is incorrectly rendered. The template outside is rendered correctly in Chrome.

Using `encapsulation: ViewEncapsulation.Native` does not resolve the issue.

**Expected behavior**
If the browser supports `<template>` elements, children should be appended to the template element's content attribute.

**Minimal reproduction of the problem with instructions**
Due to #15555 I cannot provide a Plunker. Create a new project and go to `node_modules/@angular/compiler/@angular/compiler.es5.js` and set `enableLegacyTemplate` to false on line 2287.

```js
    function CompilerConfig(_a) {
        var _b = _a === void 0 ? {} : _a, _c = _b.defaultEncapsulation, defaultEncapsulation = _c === void 0 ? ViewEncapsulation.Emulated : _c, _d = _b.useJit, useJit = _d === void 0 ? true : _d, missingTranslation = _b.missingTranslation, enableLegacyTemplate = _b.enableLegacyTemplate;
        this.defaultEncapsulation = defaultEncapsulation;
        this.useJit = useJit;
        this.missingTranslation = missingTranslation;
        this.enableLegacyTemplate = enableLegacyTemplate !== false;
        // Hard code to false until a valid way to set it is found
        this.enableLegacyTemplate = false;
    }
```

Then, add the following markup to `app.component.html`

```html
<template>
  <div>Hello World</div>
</template>
```

Optionally, add this outside of `<app-root>` in `index.html` to view the correct render. Note that the browser must support HTML template elements for this to work (http://caniuse.com/#feat=template)

**What is the motivation / use case for changing the behavior?**
Compatibility with custom elements

* **Angular version:** 4.0.0

* **Browser:** [all]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =  6.9.5

**Comment by hansl** [comment]
After discussion to @tbosch, this is not a regression as stamping out `<template>` in the DOM is a new feature. It is broken, so labeling it as such.

**Comment by ctaepper** [comment]
how does this issue not get more love? practically cannot use angular together with custom elements...

**Comment by hotforfeature** [comment]
@hansl any update? Been over a year and this is still broken.

**Comment by hansl** [comment]
I'm not the one who's responsible for investigating this issue, so I have no more information, sorry.

**Comment by pkozlowski-opensource** [comment]
Excellent reproduce scenario with Angular v9, extracted from #35588: https://stackblitz.com/edit/ng-template-fce

**Comment by andronat** [comment]
Hello! Any news on this? 

I'm building a VR project on top of [aframe](https://aframe.com/) and [networked-aframe](https://github.com/networked-aframe/networked-aframe). 

Unfortunately, this bug currently breaks any integration between the projects. Any plans on fixing this soon?

**Comment by andronat** [comment]
If someone can point me to the right direction I can put some time to fix the issue.

**Comment by asyncLiz** [comment]
According to a comment on the PR for this issue (https://github.com/angular/angular/pull/15558), it should have become obsolete with Ivy. Is it still a problem with Ivy?

**Comment by pkozlowski-opensource** [comment]
@asyncLiz I believe that this is still an issue in ivy as we didn't change / add special treatment for the `<template>` element. Here is the reproduction scenario with ivy: https://github.com/angular/angular/issues/15557#issuecomment-589283519

**Comment by IndreSv** [comment]
Is there any update on this issue or maybe suggested workaround until it's fixed? as someone mentioned before, it's quite a blocker when trying to use Angular with custom elements.

**Comment by pkozlowski-opensource** [comment]
@IndreSv I'm afraid that that I can't think of an easy work-around for this one - the code that adds elements to the DOM is rather deep inside framework.

**Comment by asyncLiz** [comment]
This is a shim I've used to work around the issue: [origami/shim-template-append.ts](https://github.com/hotforfeature/origami/blob/master/templates/src/shim-template-append.ts).

Basically override `HTMLTemplateElement.prototype.appendChild` and forward children to the template's content instead. Bit hacky, but it's been pretty reliable for a few years.

An [APP_INITIALIZER](https://github.com/hotforfeature/origami/blob/777c37cc095e8b29ee5afa851c9fd2c19e896e3d/templates/src/template.module.ts#L8-L12) provider can ensure that the shim runs before templates are processed.

[`@codebakery/origami/templates`](https://github.com/hotforfeature/origami/tree/master/templates) is a standalone module if you want to import the shim or initializer itself, even if you're not using Polymer.

**Comment by Oram** [comment]
@IndreSv 
When I encountered the problem I created the template with createElement.
https://stackoverflow.com/a/57782399/9839191
