### ISSUE TITLE
Error in core documentation/ quickstart

### ISSUE THREAD

**Issue by min-tcs** [angular/angular#15562]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Microsoft Edge 38.14393.0.0

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 

* **Node (for AoT issues):** `node --version` =   3.10.10

**Comment by DzmitryShylovich** [comment]
Please report documentation issues on https://github.com/angular/angular.io/issues

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
