### ISSUE TITLE
Silent failure if template + templateUrl are specified

### ISSUE THREAD

**Issue by mprobst** [angular/angular#15566]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**

```ts
@Component({
  template: 'hello',
  templateUrl: './my.template.html',
})
class Component {}
```

This silently uses `template` instead of `templateUrl`. I just taught an Angular class, and this completely baffled student and two teachers for half an hour.

**Expected behavior**

Report an error if both `template` and `templateUrl` are specified.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:** [all]
 
* **Language:** [all]

**Comment by johnpapa** [comment]
perhaps codelyzer can do this, too @mgechev

**Comment by mgechev** [comment]
I will open an issue; sounds like a good candidate for the linter.

**Comment by mgechev** [comment]
Since it's now a compile-time error, I'll keep it out of codelyzer.
