### ISSUE TITLE
Error loading module from another dir

### ISSUE THREAD

**Issue by KhaosTheory1012** [angular/angular#1556]
GET http://localhost:8080/build/ArticleRest.js 404 (Not Found)window.(anonymous function).(anonymous function) @ angular2-bundle.js:498i @ es6-module-loader@0.16.5.src.js:2605$__Object$defineProperty.value @ es6-module-loader@0.16.5.src.js:2780n @ es6-module-loader@0.16.5.src.js:377t @ es6-module-loader@0.16.5.src.js:365$__Object$defineProperty.value @ es6-module-loader@0.16.5.src.js:2779$__global.upgradeSystemLoader.e.fetch @ system@0.16.7.src.js:731$__global.upgradeSystemLoader.e.fetch @ system@0.16.7.src.js:1754$__global.upgradeSystemLoader.e.fetch @ system@0.16.7.src.js:1851(anonymous function) @ es6-module-loader@0.16.5.src.js:1525run @ angular2-bundle.js:89zoneBoundFn @ angular2-bundle.js:66D @ es6-module-loader@0.16.5.src.js:1183I @ es6-module-loader@0.16.5.src.js:11427.O.when @ es6-module-loader@0.16.5.src.js:9307.w.run @ es6-module-loader@0.16.5.src.js:8213.e._drain @ es6-module-loader@0.16.5.src.js:973.e.drain @ es6-module-loader@0.16.5.src.js:62t @ es6-module-loader@0.16.5.src.js:268
angular2-bundle.js:752 Error loading "ArticleRest" at http://localhost:8080/build/ArticleRest.js
Error loading "ArticleRest" from "scripts/cart" at http://localhost:8080/build/scripts/cart.js
Not Found: http://localhost:8080/build/ArticleRest.js

ArticleRest is at:
./build/scripts/ArticleRest.js

But angular2 doesn't seem to find it there. Other files can be found there.

html looks like this:

script
    System.import('../scripts/cart', './build/scripts/ArticleRest');
/script
    cart></cart

**Comment by mhevery** [comment]
This seems like a configuration issue on your side, not an angular issue. Closing.
