### ISSUE TITLE
APP_BOOTSTRAP_LISTENER, APP_INITIALIZER as lifecycle hooks

### ISSUE THREAD

**Issue by dherges** [angular/angular#15575]
**I'm submitting a feature request** 
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**

`APP_BOOTSTRAP_LISTENER` is for function type `(componentRef: ComponentRef<any>) => void`

`APP_INITIALIZER` is for function type `() => void`

**Expected behavior**
In addition to that, it'll be nice to register for "APP_BOOTSTRAP_LISTENER" and "APP_INITIALIZER" through lifecycle hooks of a class, e.g. by implementing a marker interface similar to `OnInit`, `OnDestroy`, etc. Example:

```ts
interface OnAppBootstrap {
  onAppBootstrap(componentRef: ComponentRef<any>): void
}
```

Are there any plans to provide an API for that? If yes, what is the current state of implementation? If no, is the following solution considered "stable" (possibly making its way into 4.x)?

Right now, it's possible to achieve this behaviour by hooking up several factory providers. To me, it feels like this approach is some rape on factories. Example / code excerpt:

```ts
export class MyBootstrap implements OnAppBootstrap, OnAppInitializer {

  public val: string = 'empty';

  constructor() {
    console.log(`MyBootstrap created`);
  }

  onAppBootstrap(componentRef: ComponentRef<any>) {
    this.val = 'app_bootstrap';

    console.log(`MyBootstrap getting bootstrapped!`, componentRef);
  }

  onAppInitialize() {
    this.val = 'app_initializr';

    console.log(`MyBootstrap was initialized!`);
  }
}
```

```ts
@Component({ selector: 'app-root', template: '..' })
export class AppComponent implements OnInit {

  constructor(
    private myBoot: MyBootstrap
  ) {}

  ngOnInit() {
    console.log("AppComponent onInit", this.myBoot);
  }
}

@NgModule({
  providers: [
    MyBootstrap,
    provideBootstrapListener(MyBootstrap) // <-- registers interface impl OnAppBootstrap to be called from an APP_BOOTSTRAP_LISTENER
    provideInitializer(MyBootstrap) // <-- registers interface impl OnAppInitializer to be called from an APP_INITIALIZER
  ]
})
export class AppModule { }
```

Which results in a start-up order of

```
MyBootstrap created.
MyBootstrap was initialized!
AppComponent onInit
MyBootstrap getting bootstrapped!
```

The glueing code :spaghetti: 

```ts
export interface OnAppBootstrap {
  onAppBootstrap(componentRef: ComponentRef<any>)
}

export interface OnAppInitializer {
  onAppInitialize();
}


export function bootstrapListenerFactory(listener: OnAppBootstrap) {

  return function (componentRef: ComponentRef<any>): void {
    listener.onAppBootstrap(componentRef);
  }
}

export function provideBootstrapListener(listenerType: any): FactoryProvider {

  return {
    provide: APP_BOOTSTRAP_LISTENER,
    multi: true,
    useFactory: bootstrapListenerFactory,
    deps: [ listenerType ]
  };
}


export function initializerListenerFactory(listener: OnAppInitializer) {

  return function () {
    listener.onAppInitialize();
  }
}

export function provideInitializer(listenerType: any): FactoryProvider {

  return {
    provide: APP_INITIALIZER,
    multi: true,
    useFactory: initializerListenerFactory,
    deps: [ listenerType ]
  }
}
```

**Minimal reproduction of the problem with instructions**
does not apply

**What is the motivation / use case for changing the behavior?**
services or non-visible parts of the application have a possibility to hook into/listen for angular bootstrap.

**Please tell us about your environment:** does not apply

* **Angular version:** 2.4.10

* **Browser:** all
 
* **Language:** TypeScript 2.2

**Comment by DzmitryShylovich** [comment]
what is your use case? what can you accomplish with `OnAppInitializer` but can't with `APP_INITIALIZER`?

**Comment by dherges** [comment]
A service listening for initialization, e.g. providing data that is needed prior to bootstrapping components. It's possible to wire up factory providers for `APP_INITIALIZER` by hand. It feels like more fluent code to implement an interface `OnAppInitializer`.

**Comment by DzmitryShylovich** [comment]
Personally I don't like the idea to introduce one more way to do the same thing.

**Comment by dherges** [comment]
If it's not intended to include more lines of code, should it be added to docs of [APP_INITIALIZER](https://github.com/angular/angular/blob/master/packages/core/src/application_init.ts#L14-L18) and [APP_BOOTSTRAP_LISTENER](https://github.com/angular/angular/blob/master/packages/core/src/application_tokens.ts#L55-L64)?
