### ISSUE TITLE
ngc output directory mismatch

### ISSUE THREAD

**Issue by PRR24** [angular/angular#15577]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report (unless there is some hidden additional config parameter I missed)
```

**Current behavior**
If tsconfig.json has 
compilerOptions / outDir = "aot" &&
angularCompilerOptions / genDir = "aot"
then js files are correctly created to aot directory. But the file references from *.ngfactory.js point to original location of all non-ngfactory files, not to generated corresponding js files.

**Expected behavior**
References from ngfactory.js files poin to compilerOptions / outDir location

**Minimal reproduction of the problem with instructions**
Create project as described https://angular.io/docs/ts/latest/cookbook/aot-compiler.html and add compilerOptions / outDir to tsconfig-aot.js

**What is the motivation / use case for changing the behavior?**
Separate AOT and non-AOT build/dependency locations

**Please tell us about your environment:**
Ubuntu 16.04

* **Angular version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` = 6.10.0

**Comment by michal-filip** [comment]
I've had the same issue with:
Angular version: 4.0.0
Node (for AoT issues): node --version = v6.9.5

But in my case, when omitting both compilerOptions.outDir and angularCompilerOptions.genDir, original source files were still included in the produced bundle, which may point to a different issue.

**Comment by mustafaekim** [comment]
I have having the same issue. If I do simply use genDir: "aot" everthing works. But that causes Js files all over my workspace. When I change genDir: "../../aot/weby" and put "outDir": "../../aot/weby" I am getting error:
`PS D:\dev\nodespace\peoplive\front\peopc> node_modules/.bin/ngc -p src/weby/tsconfig-aot.json
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.component.ngfactory.ts:10:26: Module './app.component' was resolved to 'D:/dev/nodespace/peoplive/front/peopc/aot/weby/ap
p/app.component.js', but '--allowJs' is not set.
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module.ngfactory.ts:10:26: Module './app.module' was resolved to 'D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.
module.js', but '--allowJs' is not set.`

**Comment by mustafaekim** [comment]
Sorry for not to post at once. But the error may be misleading. If I set allowJs, I keep getting errors:
`D:\dev\nodespace\peoplive\front\peopc> node_modules/.bin/ngc -p src/weby/tsconfig-aot.json
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.component.ngfactory.ts:28:20: Namespace '"D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.component"' has no expor
ted member 'AppComponent'.
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.component.ngfactory.ts:40:69: Namespace '"D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.component"' has no expor
ted member 'AppComponent'.
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.component.ngfactory.ts:40:107: Argument of type '() => void' is not assignable to parameter of type 'Type<any>'.
  Type '() => void' provides no match for the signature 'new (...args: any[]): any'
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module.ngfactory.ts:14:67: Namespace '"D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module"' has no exported me
mber 'AppModule'.
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module.ngfactory.ts:23:24: Namespace '"D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module"' has no exported me
mber 'AppModule'.
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module.ngfactory.ts:122:28: Namespace '"D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module"' has no exported m
ember 'AppModule'.
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module.ngfactory.ts:135:25: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module.ngfactory.ts:173:65: Namespace '"D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module"' has no exported m
ember 'AppModule'.
Error at D:/dev/nodespace/peoplive/front/peopc/aot/weby/app/app.module.ngfactory.ts:173:129: Argument of type '() => void' is not assignable to parameter of type 'Type<any>'.
  Type '() => void' provides no match for the signature 'new (...args: any[]): any'`

**Comment by TakanashiOuken** [comment]
Having the same problem here 
I really don't understand why https://angular.io/guide/aot-compiler#bootstrap say 
> Be sure to recompile with ngc!
at the end???
There is no `allowJs` in tsconfig-aot.json. How could ngc read *.ngfactory.js files

**Comment by trotyl** [comment]
Obsolete, `genDir` option has been removed since v5.
