### ISSUE TITLE
Memory leak when using ngTemplateOutlet

### ISSUE THREAD

**Issue by tsvetomir** [angular/angular#15578]
**I'm submitting a ...** 
```
[x] bug report
```

**Current behavior**
I'm using ngTemplateOutlet in a similar way to render a table:

```html
<template #cell1 let-dataItem>
  {{dataItem.field1}}
</template>

<table>
  <tr *ngFor="let dataItem of data">
    <td>
      <template [ngTemplateOutlet]="cell1" [ngOutletContext]="{ $implicit: dataItem }">
      </template>
    </td>
  </tr>
</table>
```

The heap size and node count grows uncontrollably when updating the data.

![image](https://cloud.githubusercontent.com/assets/247917/24454419/7dd9b1a6-1494-11e7-91a7-f4fb288f5bc9.png)

**Expected behavior**
The heap size and node count should remain fairly constant since we're only replacing their content.
Note that the application is running in production mode.

**Minimal reproduction of the problem with instructions**
1. Open [this plunkr for 2.0.10](http://plnkr.co/edit/TS7hWAKYi4V1fyK9edwX?p=preview) or [this plunkr for 4.0.0](http://plnkr.co/edit/38sEmoUCkPHqK1nnhW06).
1. Start your browsers memory profiler or observe the process memory usage
1. Notice that memory is not reclaimed

**What is the motivation / use case for changing the behavior?**
Application memory usage should be stable.

**Please tell us about your environment:**
Linux

* **Angular version:** 2.4.10, 4.0.0

* **Browser:** Chrome 57 | Firefox 52
 
* **Language:** TypeScript 2.0

**Comment by DaveMBush** [comment]
For the record, this happen in Windows (7) environment as well

**Comment by alexzuza** [comment]
Will this solve the problem?
```
ngOnDestroy() {
  if (this._viewRef) {
     this._viewContainerRef.remove(this._viewContainerRef.indexOf(this._viewRef));
  }
}
```
Without `ngOnDestroy`
![2](https://cloud.githubusercontent.com/assets/4223314/24459281/318b8d02-14ac-11e7-9ebf-c488a4edbb06.png)

After applying the code above
![1](https://cloud.githubusercontent.com/assets/4223314/24459327/4d838014-14ac-11e7-822f-2a0f431de196.png)

https://plnkr.co/edit/ciBnuI1m6xYO9cyjj5zH?p=preview

**Comment by ericmartinezr** [comment]
related to https://github.com/angular/angular/issues/14919 ?

**Comment by tsvetomir** [comment]
@alexzuza it helps indeed :) Your version of ngTemplateOutlet does not leak memory:

![image](https://cloud.githubusercontent.com/assets/247917/24460997/8e7ece10-14a8-11e7-98fa-7b0637fef77d.png)

@ericmartinezr maybe the references are kept by the template outlet and selecting them with @ContentChildren is not necessary for the leak to occur.

**Comment by tbosch** [comment]
Hi,
could you make a version that also destroys the component that contains the declaration place of the `<template>`?

**Comment by tsvetomir** [comment]
@tbosch I'm not sure what I should do. Should I move the templates to a sub-component?

**Comment by tbosch** [comment]
Yes, fixing `ngTemplateOutlet` is the right place.

**Comment by tbosch** [comment]
Thinking about this a bit more, I think we can fix this in a general way, without needing to change `ngTemplateOutlet`... Working on it...

**Comment by sgrinich** [comment]
Hi, 

I'm wondering what the minimum version of Angular 2.x is needed to resolve this bug. Our application is using Angular 2.4.10 and I am hoping to fix this memory leak without needing to upgrade the entire app to Angular 4.

**Comment by tsvetomir** [comment]
@sgrinich upgrading from 2 to 4 shouldn't be too hard. Also 4.x is an LTS release.
Check out the [Angular Update Guide](https://angular-update-guide.firebaseapp.com/) for a summary of necessary changes.

**Comment by sgrinich** [comment]
Ok, thanks @tsvetomir
