### ISSUE TITLE
can't get animation working with ng4 and lazy loading 

### ISSUE THREAD

**Issue by born2net** [angular/angular#15579]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting (or maybe I missed something :/ )
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Animation working in main module but not in lazy loaded module.

**Expected behavior**
work everywhere if I load animation module in a shared module.

**Minimal reproduction of the problem with instructions**
Can't get Angular4 to work with lazy loading and animation.
So I loaded ```BrowserAnimationsModule``` in my app-modules.ts and animation works fine in main module, but not in lazy loaded modules, so I tried to load
```BrowserAnimationsModule```in my shared module as I get an error of :
```Unhandled Promise rejection: BrowserModule has already been loaded.
 If you need access to common directives ```

This is my shared module:

    var sharedComponents = [Tabs, Tab, Infobox, Sliderpanel, Slideritem, SlideritemContent, PanelSplitMain, PanelSplitSide, PanelSplitContainer, ListToArrayPipe, FormatSecondsPipe, MatchBodyHeight, ScreenTemplate, BlurForwarder, DraggableList, AddContent, Loading,
        FontSelector, BlockPropContainer, BlockPropCommon, BlockPropHtml, BlockPropClock, BlockPropWeather, BlockPropInstagram, BlockPropJsonPlayer, BlockPropJsonItem, LivePreview, LocationMap, MediaPlayer, FilterModelPipe, SvgIcon,
        BlockPropScene, BlockPropCalendar, BlockPropSheets, BlockPropTwitter, BlockPropVideo, BlockPropImage, BlockPropLabel, BlockPropMrss, BlockPropLocation, BlockPropRss, BlockPropDigg, BlockPropFasterQ, BlockPropCollection, BlockPropQR, BlockPropYouTube, JsonEventGrid];
    
    @NgModule({
        imports: [CommonModule, FormsModule, HttpModule, JsonpModule, ReactiveFormsModule, ContextMenuModule, ChartModule, ReactiveFormsModule, ColorPickerModule, DropdownModule, RadioButtonModule, SimpleGridModule, Ng2Bs3ModalModule, AgmCoreModule, VgCoreModule, VgControlsModule, VgOverlayPlayModule, VgBufferingModule],
        exports: [CommonModule, FormsModule, HttpModule, JsonpModule, ReactiveFormsModule, ContextMenuModule, ChartModule, ColorPickerModule, DropdownModule, RadioButtonModule, SimpleGridModule, Ng2Bs3ModalModule, AgmCoreModule, VgCoreModule, VgControlsModule, VgOverlayPlayModule, VgBufferingModule, ...sharedComponents],
        entryComponents: [ScreenTemplate],
        declarations: [...sharedComponents]
    })
    
    export class SharedModule {
        static forRoot(): ModuleWithProviders {
            return {
                ngModule: SharedModule,
                providers: []
            };
        }
    }
```

and as soon as I add to it the ```BrowserAnimationsModule``` it will error out,

this is the project if you wish to look at:
https://github.com/born2net/studioweb

```
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
@angular/language-service: 4.0.0
@ngtools/webpack: 1.3.0
```

**Comment by Toxicable** [comment]
A minimal reproduction would be handy, plunkr is a good start

**Comment by racerhere** [comment]
@Toxicable I ran into the same problem. Please follow the repro instructions:
* Clone project [https://github.com/racerhere/animation-lazy-error](https://github.com/racerhere/animation-lazy-error)
* `npm install`
* `ng serve`
* Go to `http://localhost:4200/eager`. Everything works when modules are eagerly loaded.
* Go to `http://localhost:4200/lazy`. See console for
    >  Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

* Comment the import of NoopAnimationsModule in src\app\shared\shared.module.ts (lines 6 and 15).
* Go to `http://localhost:4200/lazy`. Works fine now.

**Comment by Toxicable** [comment]
@racerhere taking a look at this now. I used your code to reproduce this in plunkr since it's easier to work with: http://plnkr.co/edit/GhyrJJMuXT6bQZusizj8?p=preview

**Comment by born2net** [comment]
tx as I still believe this is a bug!

**Comment by Toxicable** [comment]
Looks like this is working as intended.
AnimationModule only imports providers as seen here https://github.com/angular/angular/blob/master/packages/platform-browser/animations/src/module.ts#L18 which means this should not be a Shared import but instead a 1 time root import.
In other words, move it from Shared to Core and you should be good

**Comment by born2net** [comment]
ya that's how I have it, just in core and does not work in lazy, I looked at your plunkr and didn't seem to work either.

**Comment by Toxicable** [comment]
@born2net yes, that's becasue im importing NoopAnimationsModule into my SharedModule which is not how you're meant to use it. It should be imported once and once only in your root Module

**Comment by born2net** [comment]
ok, so can you get your plunkr working with animation and lazy loading? would love to see it work / animate,
tx!

**Comment by born2net** [comment]
by the way I don't se Noop, I use ```BrowserAnimationsModule```

**Comment by Toxicable** [comment]
Noop is the "mock" version, I was just doing that for testing

**Comment by DzmitryShylovich** [comment]
http://angularjs.blogspot.com.by/2017/03/angular-400-now-available.html :
> If you rely on Animations, import the new BrowserAnimationsModule from @angular/platform-browser/animations in your **root NgModule**. 

does it say to import it in a shared module?

**Comment by born2net** [comment]
nope, and I don't, never did.
still animation is broken in lazy loaded modules!

**Comment by DzmitryShylovich** [comment]
@born2net please reproduce in plunkr

**Comment by born2net** [comment]
I am on mobile, will do tonight when I can ,tx

**Comment by Toxicable** [comment]
works fine here http://plnkr.co/edit/9RZ6msmiJGOQRaDiRy7G?p=preview

**Comment by born2net** [comment]
can you please move the animation delectation from my-app to lazy component?

**Comment by DzmitryShylovich** [comment]
why? it's not allowed

**Comment by Toxicable** [comment]
@born2net no, that'll break it, you're not meant to import AnimationsModule anywhere else except the root as stated above

**Comment by born2net** [comment]
ok I will check your code again, what I meant was to put the animation trigger inside the lazy, but you are already doing that, you just named the selector 'app' as well so it through me off.
I will check your code and compare asap,
tx again,
Sean.

**Comment by Toxicable** [comment]
@born2net oh I see your confusion, my mistake, I just copied it out of another plunkr I had with animations already

**Comment by born2net** [comment]
Obviously it's working for you, I am closing this bug until I can provide more info.
tx again,
Sean

**Comment by racerhere** [comment]
@Toxicable thank you for the plunkr! @DzmitryShylovich thanks for pointing out the guide to me.

-@racerhere

**Comment by born2net** [comment]
yes appreciate the effort @Toxicable

**Comment by MurhafSousli** [comment]
#15829 @Toxicable here is an [minimal reproduction](http://plnkr.co/edit/Z5jVnWi15wG6aI6cY8Rq?p=preview)

**Comment by Toxicable** [comment]
@MurhafSousli read the above conversation, you don't import Animations Module into lazy modules

**Comment by anuradhawick** [comment]
@Toxicable I am using angular 8 and I have done exactly as you have suggested. Just in AppModule. However, I cannot get the animations to work in my lazy loaded modules. Could you advice me on this matter? Thanks

**Comment by Dj-jom2x** [comment]
> @Toxicable I am using angular 8 and I have done exactly as you have suggested. Just in AppModule. However, I cannot get the animations to work in my lazy loaded modules. Could you advice me on this matter? Thanks

me too it only triggered ones in app.component.ts

**Comment by anuradhawick** [comment]
@Dj-jom2x I was able to solve the issue by having globally defined CSS and Material icons in the index.html and styles.css.

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  
  <base href="/">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
        integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <link rel="icon" type="image/x-icon" href="favicon.ico">

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
        name='viewport'/>

  <link rel="stylesheet" type="text/css"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
</head>
<body>
<app-root></app-root>
</body>
</html>
```

```css
/* styles.css */
@import "~@angular/material/prebuilt-themes/indigo-pink.css";
```

Thay way these global ripples and etc can be used across the entire app. Also if you have any other css, from a template or so add them in the angular json so you'll have them minified and bundled for production. If you need more info have a look at my project which is in early production. [LINK](https://github.com/anuradhawick/vinly-search/)

**Comment by Dj-jom2x** [comment]
> @Dj-jom2x I was able to solve the issue by having globally defined CSS and Material icons in the index.html and styles.css.
> 
> ```
> <!doctype html>
> <html lang="en">
> <head>
>   <meta charset="utf-8">
> 
>   
>   <base href="/">
> 
>   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
>         integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
>   <link rel="icon" type="image/x-icon" href="favicon.ico">
> 
>   <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
>         name='viewport'/>
> 
>   <link rel="stylesheet" type="text/css"
>         href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"/>
>   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
> </head>
> <body>
> <app-root></app-root>
> </body>
> </html>
> ```
> 
> ```css
> /* styles.css */
> @import "~@angular/material/prebuilt-themes/indigo-pink.css";
> ```
> 
> Thay way these global ripples and etc can be used across the entire app. Also if you have any other css, from a template or so add them in the angular json so you'll have them minified and bundled for production. If you need more info have a look at my project which is in early production. [LINK](https://github.com/anuradhawick/vinly-search/)

mine is just a mistake xD its just i had two router ...  one is default.. and one is the real one the content of the app in the dashboard... toolbar -> breadcrumb -> here content... its all working now
