### ISSUE TITLE
AoT "function calls are not supported" error with exported animation function

### ISSUE THREAD

**Issue by chrisnicola** [angular/angular#15587]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently I'm getting an error of the form:

```

ERROR in Error encountered resolving symbol values statically. Calling function 'rotate', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppComponent in /Users/chrisnicola/src/aot-bug/src/app/app.component.ts, resolving symbol AppComponent in /Users/chrisnicola/src/aot-bug/src/app/app.component.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/chrisnicola/src/aot-bug/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

However the error message is referring to a function that is in fact exported in the file. The component code is below:

```
import { Component } from '@angular/core';

import {animate, transition, trigger, style, state} from "@angular/animations";

export function rotate(rotation = 180, animRotate = '400ms', animUnrotate = '400ms') {
  let unrotated = style({ transform: 'rotate(0)' });
  let rotated = style({ transform: `rotate(${rotation}deg)` });
  return trigger(`rotate${rotation}`, [
    state('unrotated', unrotated),
    state('rotated', rotated),
    transition('rotated => unrotated', [rotated, animate(animRotate, unrotated)]),
    transition('unrotated => rotated', [unrotated, animate(animUnrotate, rotated)]),
  ]);
}
export function rotateState(rotated: boolean) {
  return rotated ? 'rotated' : 'unrotated';
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  animations: [ rotate() ]
})
export class AppComponent {
  title = 'app works!';
}
```

**Expected behavior**

It should compile, or if there is in fact an error in the code the error should state the problem correctly, since the function in question is in fact exported.

**Minimal reproduction of the problem with instructions**

Steps to reproduce:

1. Start a new application like `ng new aot-bug`
2. Edit `app.component.ts` and use the code snippet above
3. Run `ng build -prod`

**What is the motivation / use case for changing the behavior?**

Getting a working AoT for us in our project. We have been trying to get a working AoT build with our production code since version 2.0 with no luck.

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v6.9.1

**Comment by DzmitryShylovich** [comment]
> animations: [ rotate() ]

function call

**Comment by chrisnicola** [comment]
So this line is irrelevant? 

`Consider replacing the function or lambda with a reference to an exported function`

Also how is one supposed to use trigger then, it would have the same problem.

**Comment by chrisnicola** [comment]
Interestingly, testing this with stuff inlined into a `trigger()` call works. Clearly I'm just not understanding the limitation of the `ngc` compiler here when it comes to exported functions. Can someone explain this?

**Comment by chrisnicola** [comment]
Ok so the closest thing to the original that I could get working was the following:

```
import { Component } from '@angular/core';

import {animate, transition, trigger, style, state} from "@angular/animations";

export const time = '400ms'
export const unrotated = style({ transform: 'rotate(0)' });
export const rotated = style({ transform: 'rotate(180deg)' });
export function rotate() {
  return trigger('rotate180', [
    state('unrotated', unrotated),
    state('rotated', rotated),
    transition('rotated => unrotated', [rotated, animate(time, unrotated)]),
    transition('unrotated => rotated', [unrotated, animate(time, rotated)]),
  ]);
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  animations: [ rotate() ]
})
export class AppComponent {
  title = 'app works!';
}
```

So basically we are saying is that any kind of dynamic function doesn't work here. Even if the function generates a fixed result. Such as:

```
export function rotate(rotation = 180, animRotate = '400ms', animUnrotate = '400ms') {
  let unrotated = style({ transform: 'rotate(0)' });
  let rotated = style({ transform: `rotate(${rotation}deg)` });
  return trigger(`rotate${rotation}`, [
    state('unrotated', unrotated),
    state('rotated', rotated),
    transition('rotated => unrotated', [rotated, animate(animRotate, unrotated)]),
    transition('unrotated => rotated', [unrotated, animate(animUnrotate, rotated)]),
  ]);
}
```

Which produces the same result as above when `rotate()` is called but has the flexibility of being reused in other components with different rotation and timing values.

This seems like a severe limitation of the AoT compiler assuming that this is by design and not simply a bug. Additionally if it is by design then the error message produced is not useful in this context as it is basically suggesting something that is already being done with no additional clue as to the real problem.

**Comment by chrisnicola** [comment]
So based on further testing it seems the things that are problematic are:

1. Back tick string interpolation, like `rotate(${value}deg)`. Concatenation works however.
2. Any internal `var`, `const` or `let` in the function. Instead it must be extracted from the function and exported. Surprisingly, you can pass values as parameters and they can have defaults.

These limitations seem both severe and inconsistent. Now that I've at least narrowed them down can someone from the Angular team chime in and let me know if they are intentional design, short-term limitations or simply bugs?

As an additional problem I've noted, it does seem that `ng server -aot` does not always pick up all changes and often has to be restarted to compile properly again.

**Comment by jeffwhelpley** [comment]
I believe that the root cause of this issue is also affecting the one that I just entered with #16584. Basically, functions that are imported should be supported for component attributes. It is clearly supported when you define the function in the same module as the component.

**Comment by jaesung2061** [comment]
It was back ticks for me. I was interpolating as well but I removed both at once so I'm not sure which specifically caused the issue.

**Comment by p-jan** [comment]
Thanks @chrisnicola for the breakdown of the issue and its workarounds. After spending hours searching for a workaround, your post really helped out.

**Comment by chrisnicola** [comment]
Honestly it is ridiculous to me that this is even a problem. But then again that is why I switched to Vue.

**Comment by jaesung2061** [comment]
@chrisnicola how's Vue treating ya? I've moved from Angular to React and back. I'm still trying to find the easiest and fastest way (with the best support) to create a SPA.

**Comment by chrisnicola** [comment]
@jaesung2061 probably not the place for this discussion, but it's been pretty great. It is somewhat familiar if you have experience with Angular 1.x. Sadly Vue feels like what Angular 2 should have been instead of this over designed attempt to make a javascript framework look more like a Java enterprise project.

**Comment by jiayihu** [comment]
So sad to see that this problem is not yet solved, even with `Angular 4.2` animations which are focused on making animations more reusable

**Comment by webcat12345** [comment]
same issue here.

**Comment by alxhub** [comment]
Hello everyone,

`ngc` is working as intended in the problem as reported - functions which are not statically analyzable (do not immediately `return` a value which is foldable) - are not supported by AOT. See this [gist](https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60) by @chuckjaz for an explanation of which expressions are foldable (although it's slightly outdated, closures are indeed supported via lowering). Per that gist, string templating should also be supported.

**Comment by chrisnicola** [comment]
@alxhub sadly I think this just demonstrates that Angular 2's AoT strategy isn't a particularly good one.

The fact that code that is completely valid to the typescript compiler doesn't work with the AoT compiler seems like a pretty big limitation.

**Comment by alxhub** [comment]
@chrisnicola the issue is that the function isn't being called by code, it's being called as part of metadata, which looks like code but isn't. Metadata needs to be fully resolved at compile time, not runtime.

If you actually want to execute code at runtime to produce a value to satisfy a provider, use `useFactory`:

```
providers: [
  {provide: ROUTES, useFactory: () => computeRoutesAtRuntime()}
]
```

**Comment by jiayihu** [comment]
@alexbyk  How would I solve my issue with higher-order functions then? In my case I cannot use `useFactory` because I'm publishing a library of animations and I strongly need functions to avoid repeating over and over animations which differ only of 1-2 values (for instance `bounceUp` and `bounceDown`). You can find an example of what I'm talking [here](https://github.com/jiayihu/ng-animate/blob/master/src/bouncing.ts#L29).

**Comment by alxhub** [comment]
@jiayihu, most of these are fine - the compiler can understand functions which immediately return a statically analyzable value, and invocations of those functions with statically analyzable ("foldable") arguments.

Where the code you linked gets into trouble is with the `bounceInDirection` / `bounceOutDirection` functions, which contain logic that violates the above rule (must return immediately). You might be able to rewrite them to be foldable. Inline conditionals (`a ? b : c`) are okay. For example, here's `bounceOutDirection('x')`:

```
function bounceOutDirectionX(params: Object) {
  return animation(
    animate(
      '{{ timing }}s {{ delay }}s',
      keyframes([
        style({ transform: translate3d('a'), offset: 0.2 }),
        style({ opacity: 1, transform: translate3d('b'), offset: 0.4 }),
        style({ opacity: 1, transform: translate3d('c'), offset: 0.45 }),
        style({ opacity: 0, transform: translate3d('d'), offset: 1 }),
      ])
    ),
    { params: {timing: DEFAULT_TIMING, delay: 0, ...params } }
  );
}
```

then this is legal:

```
const bounceOutLeft = bounceOutDirectionX({a: '20px', b: '-200px'});
```

**Comment by jiayihu** [comment]
Thanks kindly for your explaination, your solution is already something much more acceptable! I'll try the reading more about what's "foldable" and retry AOT support. 
Just one question: how is `{ params: {timing: DEFAULT_TIMING, delay: 0, ...params } }` different from `Object.assign(...)` ? It seems to me that it's still dynamic, depending on the params. But if I understand correctly the main difference is that you're using an operator and not a function call, which is surely "more dynamic" and completely unpredictable.
