### ISSUE TITLE
Misleading errormessage when using HostBinding with @animation trigger but no defined animations 

### ISSUE THREAD

**Issue by marcorinck** [angular/angular#15581]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you have a HostBinding attribute in a component which refers to an animation trigger, but you have no defined animations, you get a quite misleading error message: "Found the synthetic property @myAnimationTrigger. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application."

**Expected behavior**
The error message should be more explicit, ideally something like: "Found defined synthetic property @propertyname but found no corresponding animation definition"
  
**Minimal reproduction of the problem with instructions**
* have a HostBinding("@myAnimationTrigger") property in a component
* forget to define any animations on the component

After initializing this component (activating the route for it) angular throws an exception:

> Error: Found the synthetic property @myAnimationTrigger. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (dom_renderer.ts:368) [angular]
    at EmulatedEncapsulationDomRenderer2.DefaultDomRenderer2.setProperty (dom_renderer.ts:311) [angular]
    at DebugRenderer2.setProperty (services.ts:883) [angular]
    at setElementProperty (ng_content.ts:1) [angular]

[Here is a plunkr](http://plnkr.co/edit/0jQrNvDkTQNR8oHKSoxP?p=preview) where it happens after switching to PageComponent. I have commented out the animation definition. If you remove the comment, its working without any further changes.

This error message is misleading as the problem is NOT caused by missing BrowserAnimationsModule but instead by the developer who forgot to define the animations.

**What is the motivation / use case for changing the behavior?**
I invested a good hour after copy/pasting my animations from one component to the other (so I thought) and getting this error on one component but not on the other. It lead me to a completely wrong direction where to search for the error. 

* **Angular version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
---

**Comment by istibekesi** [comment]
The error message is fine tough, if you recently updated to Angular 4. It refers to one of the few breaking changes.

**Comment by johnchristopherjones** [comment]
The error message is not fine.  The error message says you're importing `BrowserAnimationsModule` incorrectly.  This put me on track to trying to figure out how I was loading BrowserAnimationsModule incorrectly in my lazy loading modules after one of the few  breaking change in Angular 4.x.

The problem had nothing to do with importing BrowserAnimationsModule; I just forgot to include the animations property on my component.  Oops.  Now I'm here.

**Comment by alxhotel** [comment]
Thanks @johnchristopherjones. That fixed my problem.

**Comment by dave11mj** [comment]
Thanks @johnchristopherjones ! Your comment made me realize I had the same issue. `BrowserAnimationsModule` was imported correctly, but I simply forgot to use `animations` in my component.

**Comment by jfcere** [comment]
I am having the same issue when running tests on my component which has an animation on host element ... but the difference in my case is that I have a seperate file for the animation so it can be reused in another component.

##### example.animation.ts
```typescript
import { trigger } from '@angular/animations';

export const ExampleAnimationHost = { '[@example]': '' };
export const ExampleAnimationTrigger = trigger('example', []);
```
##### example.component.ts
```typescript
import { Component } from '@angular/core';
import { ExampleAnimationHost, ExampleAnimationTrigger } from './example.animation';

@Component({
  selector: 'app-example',
  templateUrl: './example.component.html',
  styleUrls: ['./example.component.scss'],
  animations: [ExampleAnimationTrigger],
  host: ExampleAnimationHost,
})
export class ExampleComponent { }
```

The fact is that if I _copy-paste_ the trigger into the `animations` property of the `@Component` decorator my test pass ... otherwise it fails with the unexplicit error message mentioned in this issue.

Any ideas?

**Comment by DBosley** [comment]
Just had the same problem, but my issue was slightly different. I had the HostBinding in a component I moved animations out of during a refactor.

**Comment by timblakely** [comment]
Lost a lot of time to this error message. Turns out when I tried to create the template variable `#sidenav` I had fat-fingered it to `@sidenav`, subsequently spending the next two hours trying to figure out why browser animations weren't being imported correctly, much less why they were involved at all.

**Comment by cdcarson** [comment]
Thanks @johnchristopherjones. The error message is totally misleading. I've waited an hour or two googling & staring at my package.json. 

How about something like "Hey you forgot to include an animation for @fooState."

**Comment by AndrewKushnir** [comment]
It looks like this might be a good issue for community contribution:

- to add a couple tests that would capture additional scenarios where the error is being thrown (existing tests location: packages/core/test/animation/animation_integration_spec.ts)
- to update the error message itself to mention other possible scenarios, for example:

```
Unexpected synthetic property @myAnimationTrigger found. Possible reasons:
- "BrowserAnimationsModule" or "NoopAnimationsModule" modules are missing in your application.
- There is no corresponding configuration for this animation defined using `animations` field of  the `@Component`  decorator (see https://angular.io/api/core/Component#animations).
```

Thank you.

**Comment by AndrewKushnir** [comment]
Also related issue #18751 which refers to the same error message and how it's confusing to many developers. Updating error message should resolve #18751 too.

**Comment by kirjs** [comment]
I'm going to dig into it
