### ISSUE TITLE
aio: remove dead tests from AppComponent

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#15593]
See https://github.com/angular/angular/pull/15570#discussion_r108780389 and https://github.com/angular/angular/pull/15570#discussion_r108780426

**Comment by wardbell** [comment]
I think I did this, Pete. Reopen if I'm wrong.

**Comment by petebacondarwin** [comment]
This test is still there: https://github.com/angular/angular/blob/master/aio/src/app/app.component.spec.ts#L285-L291

**Comment by wardbell** [comment]
That is a VALID TEST

**Comment by petebacondarwin** [comment]
The lines have moved. The test to remove is the search worker initialization one
