### ISSUE TITLE
tag <!DOCTYPE html> crashes SSR angular 4.0.0

### ISSUE THREAD

**Issue by ozknemoy** [angular/angular#15591]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
```

**Current behavior**
i use this demo https://github.com/FrozenPandaz/ng-universal-demo.
after i added tag !DOCTYPE html(needed for some directive) node server throw error: TypeError: Cannot read property '0' of undefined
    at ServerTransferState.inject ...

inside this 
```
ServerTransferState.prototype.inject = function () {
        ...
            var head = document.children[0].children[0];
```

**Please tell us about your environment:**
win7 node 6.9.2

* **Angular version:** 4.0.0

* **Language:** TypeScript 2.2.1

**Comment by vikerman** [comment]
This is a bug in the demo. Not in the platform.
