### ISSUE TITLE
aio: fix copy button styling and behaviour

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#15597]
- [x] The copy button should appear on every code-example and code-pane.
   _Fixed in #15541._
- [ ] It should also have a tooltip that gives a visual indication when you have copied the code.
- [ ] There should never be a `lang-` CSS class on code, this is a bug that needs fixing in the `CodeComponent` template.

**Comment by gkalpak** [comment]
- [ ] The copy button gets misplaced (afaict) in code blocks with headers, as can be seen [here][1]:

![misplaced-copy-button-2][2]

[1]: https://pr15541-857631e5ceb1aae0910836a2a2bfe4c863425a4e.ngbuilds.io/guide/architecture
[2]: https://cloud.githubusercontent.com/assets/8604205/24490428/37b854ba-152b-11e7-87b0-e1b688bd7ca4.png

**Comment by Foxandxss** [comment]
Naomi wanted the `sh` snippets not to have a copy button and I agree with that. Doesn't make sense.

**Comment by gkalpak** [comment]
Why not? Depends on the content. At least in some cases, `sh` snippets contain commands that people are supposed to run in the terminal, right?

**Comment by Foxandxss** [comment]
Yes, but if I say:

```
mkdir foo
cd foo
npm install
npm start
```

I don't want to copy and paste that and then wait. I would like to go one by one or at least the first three ones and then the start.

**Comment by petebacondarwin** [comment]
I am not sure I agree @Foxandxss.

**Comment by Foxandxss** [comment]
Original issue https://github.com/angular/angular.io/issues/1979

**Comment by gkalpak** [comment]
I am sure I don't agree :smiley: If you don't want to copy it, it's fine, but oftentimes I do want to copy the commands instead of typing them in.
The rest of the original issue (which is about having a different style than source code snippets) is fine by me.

**Comment by petebacondarwin** [comment]
Copy button styling is fixed.
