### ISSUE TITLE
update to angular 4.0.0  an error occur !    

### ISSUE THREAD

**Issue by Christian-Yang** [angular/angular#15601]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After executing the command : <br/>npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@latest --save<br/>

The following information is displayed: <br/>
angular-seed@0.0.0 /root/Code/Project2/client
├── @angular/animations@4.0.0 
├── UNMET PEER DEPENDENCY @angular/common@4.0.0
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.0
├─┬ @angular/compiler-cli@4.0.0  invalid
│ └─┬ @angular/tsc-wrapped@4.0.0 
│   └── tsickle@0.21.6 
├── UNMET PEER DEPENDENCY @angular/core@4.0.0
├── UNMET PEER DEPENDENCY @angular/forms@4.0.0
├── UNMET PEER DEPENDENCY @angular/http@4.0.0
├── UNMET PEER DEPENDENCY @angular/platform-browser@4.0.0
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@4.0.0
├─┬ @angular/platform-server@4.0.0  invalid
│ ├── parse5@3.0.2 
│ └── xhr2@0.1.4 
├── @angular/router@4.0.0 
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
├── typescript@2.2.2 
└── UNMET PEER DEPENDENCY zone.js@0.6.25

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/core@4.0.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@4.0.0 requires a peer of zone.js@^0.8.4 but none was installed.
npm WARN @angular/http@4.0.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/router@4.0.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/router-deprecated@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN @angular/router-deprecated@2.0.0-rc.1 requires a peer of @angular/common@2.0.0-rc.1 but none was installed.
npm WARN @angular/router-deprecated@2.0.0-rc.1 requires a peer of @angular/platform-browser@2.0.0-rc.1 but none was installed.
npm WARN ag-grid-ng2@5.0.0 requires a peer of @angular/core@~2.0.0-rc.2 but none was installed.
npm WARN codelyzer@1.0.0-beta.3 requires a peer of @angular/compiler@~2.1.1 but none was installed.
npm WARN codelyzer@1.0.0-beta.3 requires a peer of @angular/core@~2.1.1 but none was installed.
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN ng2-bootstrap@1.1.5 requires a peer of @angular/forms@2.0.0 but none was installed.
npm WARN ng2-bs3-modal@0.10.4 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN ng2-bs3-modal@0.10.4 requires a peer of @angular/compiler@^2.0.0 but none was installed.
npm WARN ng2-bs3-modal@0.10.4 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN ng2-bs3-modal@0.10.4 requires a peer of @angular/platform-browser@^2.0.0 but none was installed.
npm WARN ng2-bs3-modal@0.10.4 requires a peer of @angular/platform-browser-dynamic@^2.0.0 but none was installed.
npm WARN ng2-file-upload@1.1.0 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN ng2-file-upload@1.1.0 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN ng2-file-upload@1.1.0 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN ng2-file-upload@1.1.0 requires a peer of @angular/forms@2.0.0 but none was installed.
npm WARN ng2-translate@3.2.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN ng2-translate@3.2.1 requires a peer of @angular/http@^2.0.0 but none was installed.

Then I followed the warning message to upgrade zone.js and rxjs, but when I opened the page in the browser, still have the following error message on the console.The chrome can not see the message,but
the firefox can.

TypeError: result is undefined
Stack trace:
subscribeToResult@http://localhost:5555/project/node_modules/.tmp/Rx.min.js?1490777820203:9:27450
CatchSubscriber</CatchSubscriber.prototype.error@http://localhost:5555/project/node_modules/.tmp/Rx.min.js?1490777820203:3:10002
Subscriber</Subscriber.prototype._error@http://localhost:5555/project/node_modules/.tmp/Rx.min.js?1490777820203:11:13243
Subscriber</Subscriber.prototype.error@http://localhost:5555/project/node_modules/.tmp/Rx.min.js?1490777820203:11:12896
XHRConnection/this.response</onLoad@http://localhost:5555/project/node_modules/@angular/http/bundles/http.umd.js:1218:17
ZoneDelegate.prototype.invokeTask@http://localhost:5555/project/node_modules/zone.js/dist/zone.js?1490777820202:236:23
NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask@http://localhost:5555/project/node_modules/@angular/core/bundles/core.umd.js:4143:28
ZoneDelegate.prototype.invokeTask@http://localhost:5555/project/node_modules/zone.js/dist/zone.js?1490777820202:235:23
Zone.prototype.runTask@http://localhost:5555/project/node_modules/zone.js/dist/zone.js?1490777820202:136:28
ZoneTask/this.invoke@http://localhost:5555/project/node_modules/zone.js/dist/zone.js?1490777820202:304:28

**Expected behavior**

no error message 
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

after update to angular 4.0.0
**Please tell us about your environment:**

Operating system:Linux ZTE 3.13.0-74-generic #118~precise1-Ubuntu SMP Fri Dec 18 10:38:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux<br/>
IDE:webstorm<br/>
package manager:npm
* **Angular version:** 2.0.X

angular version:4.0.0<br/>
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome : 48<br/>
Firefox : 43.0<br/>
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 
* **Node (for AoT issues):** `node --version` =   
npm -v : n3.10.8
node -v : v6.9.0

thanks  for you help

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Christian-Yang** [comment]
thanks you !  @DzmitryShylovich
