### ISSUE TITLE
Canceled http requests needs to be handled

### ISSUE THREAD

**Issue by FabienDehopre** [angular/angular#15604]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When an http request is canceled by the browser (or any other source), there is no error in the observable.

**Expected behavior**
If an http request is aborted by the user or canceled by the browser, an error should be thrown and passed to the error handler of the observable (just like if an error has occurred during the request).

**What is the motivation / use case for changing the behavior?**
If you have an action  to do at the end of the request that need to be done in all cases (success, error, abort, etc...). For the moment, the action is only executed on success (next) and on error (error) but not if the request is aborted.
For example, let say that when data are loaded using http request, you display a "Loading screen". That loading screen needs to be removed when the http request completes (even if the request is aborted). For the moment, the loading screen cannot be removed if the request is aborted (only when it succeed or fail).

**Comment by DzmitryShylovich** [comment]
> For the moment, the loading screen cannot be removed if the request is aborted (only when it succeed or fail).

I believe you can do this inside `.finally()`

**Comment by FabienDehopre** [comment]
@DzmitryShylovich I don't think so... indeed, you don't handle the abort event on the xhr object in https://github.com/angular/angular/blob/master/packages/http/src/backends/xhr_backend.ts#L140.
See the [MDN Doc](https://developer.mozilla.org/en-US/docs/Web/Events/abort).

**Comment by FabienDehopre** [comment]
Indeed, I didn't think about this operator.

thanks

**Comment by itbrandonsilva** [comment]
In my own instance, it's necessary for me to know whether or not a request was aborted to potentially attempt to retry the request.
