### ISSUE TITLE
Providing from inheritor to constructor of base component doesn't work in Angular 4

### ISSUE THREAD

**Issue by ivanpadavan** [angular/angular#15615]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After updating to Angular 4 code below throws errors (Cannot read property 'instance' of undefined). It was working without any problems before update:

```
export` const entity = new InjectionToken<string>('entity');

export class BaseComponent {
   protected entity<string>;
   constructor(injector: Injector) {
       ...
       this.entity = injector.get(entity)
   }
}

@Component({
   ...
   providers: [{provide: entity, useValue: 'whoCares'}]
})
export class InheritorComponent {
    constructor(injector: Injector) {
        super(injector)
    }
}
```

**Expected behavior**

I excepted InheritorComponent to be initialized with provided data via token.

**Minimal reproduction of the problem with instructions**

Here is working example:
http://plnkr.co/edit/CQLX3D5WWjixnzV5zQgN?p=preview
Here is unwoking (to brake it uncomment 26 line of app.ts)
http://plnkr.co/edit/5yeUn0j1VxASsAD0657n?p=preview

Code is similar. The only difference is angular version.

**Please tell us about your environment:**

* **Angular version:** 4.0.X

* **Browser:** [all ]

 
* **Language:** [TypeScript 2.2]

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by DzmitryShylovich** [comment]
Doesn't work even without inheritance http://plnkr.co/edit/h4WlNJ6jwOVlCjVYXAIL?p=preview

**Comment by DzmitryShylovich** [comment]
cc @tbosch

**Comment by moohkooh** [comment]
same here. On Angular 2.4.x it was possible to inject all providers inside the constructor, since 4.0.x its not possible.
Here one example: 
http://plnkr.co/edit/byWUOe?p=preview

**Comment by tbosch** [comment]
Note: This is a general bug when using `Injector` and eager providers (`useValue` is always eager)

**Comment by CSchulz** [comment]
Doesn't work either with `useClass`. I have encountered this issue on upgrade to Angular 4.

**Comment by CindySLiu** [comment]
I have some issue. Do we have any work around so that we can use Angular 4?

**Comment by shelacek** [comment]
We use something like this as workaround:
```
@Component({
   ...
   providers: [{provide: entity, useValue: 'whoCares'}]
})
export class InheritorComponent {
    constructor(injector: Injector, @Inject(entity) _: string) {
        super(injector)
    }
}
```

**Comment by ivanpadavan** [comment]
There is one another workaround:

```
export class BaseComponent implements OnInit {
    constructor(private injector: Injector) {
    }

    ngOnInit() {
        this.entity = this.injector.get(entity);
    }
}
```
```
@Component({
   ...
   providers: [{provide: entity, useValue: 'whoCares'}]
})
export class InheritorComponent implements OnInit {
    constructor(private injector: Injector) {
        super(this.injector);
    }

    ngOnInit() {
        super.ngOnInit();
    }
}
```

**Comment by CindySLiu** [comment]
@ivanpadavan Does your work around work for regular Angular class instead of Angular component?

Will ngOnInit() be called in Angular class who implements OnInit?

**Comment by CindySLiu** [comment]
@ivanpadavan I tried your work around. It doesn't work. this.injector in BaseComponent is undefined when its ngOnInit is called.

**Comment by CindySLiu** [comment]
@ivanpadavan I used your work around to fix the issue in http://plnkr.co/edit/5yeUn0j1VxASsAD0657n?p=preview
(to brake it uncomment 26 line of app.ts). I got the following error:

VM6686 App_Host.ngfactory.js:5 ERROR ReferenceError: injector is not defined
    at App.Base.ngOnInit (VM6533 app.ts!transpiled:39)
    at App.ngOnInit (VM6533 app.ts!transpiled:52)

**Comment by huntering** [comment]
@CindySLiu in stead of 
`useValue: 'Nice to meet you'`
 use this
`useFactory:  () => 'Nice to meet you!'`

**Comment by trotyl** [comment]
Already fixed by #19558 in `4.4.5`.

**Comment by wbhob** [comment]
It looks to me like this issue can be closed, since it has been fixed. Can you close it please @ivanpadavan

**Comment by andzejsw** [comment]
I am using different approach.

From app.module.ts constructor i am calling service setter, which one needs to include that other service.

```
export class AppModule {
  constructor(private wampService: WampService) {
    this.wampService.setErrorHandler(WampErrorHandler);
  }
}
```

Bur in WampService setErrorHandlermethod looks like this:
```
    setErrorHandler(handler) {
        this.wampErrorHandler = this.injector.get(handler)
    };
```
