### ISSUE TITLE
Couldn't make semantic-ui JS work

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#15617]
I created a brand new 4.0.1 project with angular-cli and wanted to try semantic-ui (2.2.10). Added everything that's needed and when I open it in a browser. I see all semantic styling but js simply doesn't work (added a dropdown that requires semantic.min.js). I tried to include it into .angular-cli.json (scripts), tried to use it just with a script tag. No luck.

I think there's an issue with angular or angular-cli. Sorry if this is wrong place to report. But semantic-ui is really mature framework and it's a pity it can't be used with angular 4.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alvipeo** [comment]
ok, thank you. I will post on SO in 90 min. BTW, there's no tag `angular` on SO.
