### ISSUE TITLE
websocket connection failed

### ISSUE THREAD

**Issue by BlankHrt** [angular/angular#15616]
WebSocket connection to 'ws://127.0.0.1/sockjs-node/276/3dvethmi/websocket' failed: Connection closed before receiving a handshake response<br/>
i don't use websocket but the error occurred every redeployed.

please help me.

i use 
angular 4,
node: 7.7.3
npm: 4.1.2
angular-cli: 1.0.0

**Comment by DzmitryShylovich** [comment]
Angular has nothing to do with websockets

**Comment by BlankHrt** [comment]
@DzmitryShylovich 
nothing imported except primeng
i use loadChildren
i don't know why ,where to find the answer,could you give me some tips?

**Comment by DzmitryShylovich** [comment]
> angular-cli: 1.0.0

I think this is related to webpack dev server

**Comment by BlankHrt** [comment]
@DzmitryShylovich  
i'm sorry i don't use webpack and don't config webpack too.
forgive me that i ask you for help again.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
