### ISSUE TITLE
How to get the values from One Component to Another Component @ Angular2

### ISSUE THREAD

**Issue by sureshsenthatti** [angular/angular#15614]
#15210 
Hi,

I have confusion on getting the values from one component to another component in Angular2.

For Example:
1. I have registration/contact form which user submits.(registration component)
2. After submit the form, i should get the values to another component using class extends.

can anybody guide ?

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/cookbook/component-communication.html

**Comment by sureshsenthatti** [comment]
Hi @DzmitryShylovich , My query is all about different component which means different pages. like registration and login.

**Comment by UCKFA** [comment]
Hi, in order to share data between components, look at the ngrx platform, or you can use a shared service as shown in the link posted by @DzmitryShylovich . There is no other way. I hope that this helps you.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
