### ISSUE TITLE
The HTML 5 validations like (required, min, max etc.) don't work with Angular 4.0.0. 

### ISSUE THREAD

**Issue by satyajit8282** [angular/angular#15622]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The HTML 5 validations like (required, min, max etc.) don't work with Angular 4.0.0.  The form is submitted without any validation fired.

**Expected behavior**
The HTML 5 validation worked fine with Angular 2.4.9.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
A regular form built with typical formGroup and ngSubmit.

**Please tell us about your environment:**

OS: Windows 10, 
IDE: VS Code
Package manager: NPM
HTTP Server: IIS, .Net Web API.

* **Angular version:** 
4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome latest version
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.1

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
See https://github.com/angular/angular/issues/15531#issuecomment-289555359

**Comment by satyajit8282** [comment]
Thanks. That worked.
