### ISSUE TITLE
"Can't resolve all parameters for X" only when component is referenced in a routing module

### ISSUE THREAD

**Issue by kirjai** [angular/angular#15627]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Getting a "Can't resolve all parameters for X" error only when a component is referenced in a routing module.
I have a component that depends on two services. Both of the services are used in a number of other components without any problems. The component, as well as the services are referenced in the `AppModule` (in `declarations` and `providers` respectively).
If i then add my component to a page by its selector - it works without any problems.
However, as soon as I reference this component in my `AppRoutingModule` and set it as component for a specific route - I get the "Can't resolve all parameters for X" error for **one** of the two services. Out of **100+ components** of my angular application, only one component is affected. 

However, I get the identical behaviour with a few of my `canActivate` route guards. Exactly the same situation, as soon as the guards are added to a `canActivate` array on any route - I get the "Can't resolve all parameters for X" error for one of the guard's dependencies. 

It is also worth mentioning that my tests for that particular component are passing **until the point when I reference the component in the routing module**. Which to me, doesn't make sense at all, because the component's tests use the `TestBed` and both dependencies are mocked!

It isn't a circular dependency issue within the services - they do not depend on each other.

```
// choose-company.component.ts
@Component({
  selector: 'app-choose-company',
  templateUrl: './choose-company.component.html',
})
export class ChooseCompanyComponent {
  constructor(private userModel: UserModel, private companyModel: CompanyModel) {}
}
```
```
// app.module.ts
@NgModule({
  imports: [
    ...
    AppRoutingModule,
  ],
  declarations: [
    ...
    ChooseCompanyComponent,
  ],
  providers: [
    ...
    UserModel,
    CompanyModel,
  ]
})
export class AppModule {}
```

```
// app-routing.module.ts
const appRoutes: Routes = [
  // everything breaks as soon as this line is present.
  { path: 'choose-company', component: ChooseCompanyComponent, canActivate: [...] }
];

@NgModule({
  imports: [RouterModule.forRoot(appRoutes)],
  exports: [RouterModule],
})
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**

As mentioned, only one of 100+ components is affected by this bug, therefore it is a very elusive bug and i couldn't recreate it in a brand new repo yet. Hoping someone has seen something similar before and will be able to help.

**What is the motivation / use case for changing the behavior?**

The behaviour is inconsistent.

**Please tell us about your environment:**

Mac OS X, VS Code, yarn, Angular CLI

* **Angular version:** 2.0.X

Angular 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 56 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.1

**Comment by DzmitryShylovich** [comment]
Please provide a small plunkr

**Comment by vicb** [comment]
- Why do you export the `RouterModule` ?
- Do you confirm the bug is with 4.0.0 or 4.0.1 only ?

**Comment by DzmitryShylovich** [comment]
@kirjai do you use lazy loading? does the issue occur with a component from a lazy loaded module?

**Comment by DzmitryShylovich** [comment]
@vicb 
> Why do you export the RouterModule ?

it's a "pattern" from the docs https://angular.io/docs/ts/latest/guide/router.html#!#routing-module

**Comment by kirjai** [comment]
@DzmitryShylovich tried creating a plunkr for this issue a couple of times - but to no avail, i'm afraid, the bug is extremely elusive. I might try recreating it in a new repo.

I do use lazy loading in the app, but not for this particular route. None of the services or components from the example are lazy loaded, they are all defined in the root `AppModule`.

@vicb the routing module (where I export the `RouterModule` from, is then imported into my root `AppModule`. From the link to the docs that @DzmitryShylovich posted, I thought that that is a requirement for routing to work. 

Never stumbled upon this problem before 4.0.0. Afraid downgrading back to 2.x isn't possible because of many 4.0 features that are already present in my code.

**Comment by kirjai** [comment]
@DzmitryShylovich 

> does the issue occur with a component from a lazy loaded module?

Just tried and actually the issue is gone at that point. Specifically, if the problematic component is now an entry component for a route that's present in a lazy loaded module - the issue is gone.

**Comment by DzmitryShylovich** [comment]
@kirjai can you try it out with ng 4.0.0 and 4.0.1?

**Comment by kirjai** [comment]
@DzmitryShylovich original bug is present in both 4.0.0 and 4.0.1

**Comment by DzmitryShylovich** [comment]
good news. so it's something new :)

**Comment by kirjai** [comment]
Just a small update. Still no luck recreating the bug in a fresh environment.
However, I found a workaround. If I wrap the problematic component in a container component - it works fine.
So with the workaround, a new container component is referenced in the `AppRoutingModule`. That container component doesn't have any logic or dependencies. All container component does is load the problematic component in the view.

**Comment by vicb** [comment]
I'm closing this issue until we have a repro as it is not actionable for now.

**Comment by ggranum** [comment]
@kirjai Any chance it relates to this: https://github.com/angular/angular/issues/13008#issuecomment-295827461 ?

**Comment by kirjai** [comment]
@ggranum
Unfortunately not. I've been bitten by the barrel issue before (classes exported in index.tx), so that was one of the first things I checked

**Comment by jensbodal** [comment]
@kirjai check your `tsconfig.json` and `tsconfig.app.json` for `emitDecoratorMetadata` and make sure it's set to `true`.  Also make sure it's spelled correctly and has the correct casing (casing was the issue here: https://www.reddit.com/r/Angular2/comments/739q24/constructor_parameters_cause_promise_rejection/dnriled/)

https://github.com/monounity/karma-typescript/issues/155

https://stackoverflow.com/a/41286776/679716
