### ISSUE TITLE
aio: animate when showing a new doc so not as abrupt

### ISSUE THREAD

**Issue by wardbell** [angular/angular#15629]
Toggle "Resources" / "Events" to see the problem. Consider quick fade-in animation.

**Comment by petebacondarwin** [comment]
Is this still a problem @wardbell ?

**Comment by IgorMinar** [comment]
I don't think so, or? I'm going to close it. Please reopen if this is still a problem.

**Comment by IgorMinar** [comment]
oops.. wrong issue.
