### ISSUE TITLE
Support async bindings in directives / injectables

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1563]
I want to be able to create a binding to be injected into a dynamically loaded component, but for an instance that isn't available until after that dynamically loaded component is already constructed. This would look something like this:

```js
bind(MdDialogRef).toAsyncFactory(() => {
  return someDeferred.promise;
});
```

along with

```js
class SomeComponent {
  constructor(@InjectPromise(MdDialogRef) dialogRef: Promise<MdDialogRef>) {
    dialogRef.then(() => {
      if (someConditon()) {
        dialogRef.close();
      }
    });
  }
}
```

I'm probably not actually going to use an API like this one, but thought it was worth filing the issue top track this feature regardless.

**Comment by mhevery** [comment]
I believe this should already work. Is there a specific error you get?

**Comment by jelbourn** [comment]
I talked to @vsavkin earlier today and he said "async binding works only when di is used independently of angular".

I was doing this:
```js
var dialogRef = null;
var dialogRefBinding = bind(MdDialogRef).toAsyncFactory(() => {
  return PromiseWrapper.resolve(dialogRef);
});
```
```js
constructor(@InjectPromise(MdDialogRef) dialogRefPromise: Promise<MdDialogRef>) {
```

And got an error: 
`Cannot instantiate MdDialogRef synchronously. It is provided as a promise! (SimpleDialogComponent -> MdDialogRef)`
(also tried a few different syntax variants, nothing accomplished the expected outcome).

**Comment by mhevery** [comment]
Per discussion with @jelbourn, this should work since the constructor injects a `Pramise<MdDialogRef>`. So the error is both confusing, and there should be no error. 

This should work (since everything can be resolved synchrounosly): 
```
constructor(@InjectPromise(MdDialogRef) dialogRefPromise: Promise<MdDialogRef>) 
```

This should fail with the above error:
```
constructor(@Inject(MdDialogRef) dialogRef: MdDialogRef) 
```

**Comment by rolandjitsu** [comment]
@mhevery I get the same exception when I use `constructor(@InjectPromise(MyAsyncService) myAsyncService: Promise<MyAsyncService>) `:

![screenshot 2015-06-29 15 07 20](https://cloud.githubusercontent.com/assets/1479737/8408514/08ec7a74-1e71-11e5-8a5f-c6e4131ee277.png)

**Comment by mhevery** [comment]
We have dropped this feature. Obsolete issue.
