### ISSUE TITLE
Allow view creation during change detection

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#15634]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

Creating dynamically a new view from a lifecycle hook (ex.: `ngOnInit`) will result in the following error:

> ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'xxx'. Current value: 'yyy'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?

**Expected behavior**

Dynamically created views should be change detected "inline" if possible (as right now), but if we cannot do this, we should change detect them at then end of the current run, and not throw the mentioned error.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/uh4oxxA3Yq6i45SA52SS?p=preview

**What is the motivation / use case for changing the behavior?**

There are legitimate use-cases where a new view needs to be created from a lifecycle hook, ex.: opening a modal window from the `ngOnInit` lifecycle hook. This was initially reported on ng-bootstrap side via https://github.com/ng-bootstrap/ng-bootstrap/issues/1159

The pb was discussed with @tbosch and the issue is opened as the result of this discussion.

* **Angular version:** 

2.3.x, 4.0.X

* **Browser:** 

all
 
* **Language:** 

all

**Comment by squadwuschel** [comment]
Its a strange behavior and a fix would be really nice, because without it the modal is not realy useable, only iwth hacks around the problem.

**Comment by tytskyi** [comment]
Isn't trick with resolved promise the solution? https://plnkr.co/edit/o7xY1pBO9wY5ssIdW66s?p=preview

**Comment by victornoel** [comment]
@tytskyi yes, that's an acceptable workaround, as well as using `setTimeout()` too.

I have the same problem when opening material2 dialogs from within an observable chain (the dialog is opened and closed when some conditions are verified in the ngrx store).

**Comment by Martin-Wegner** [comment]
The same problem was reported here: https://github.com/angular/angular/issues/17572#issuecomment-311589290

**Comment by dgroh** [comment]
This is also happening when having nested `router-outlets` and using `subscribe` to watch for changes in the child outlet, for example:

```html
  <div class="component-wrapper">
    <div *ngIf="!spinner.visible">
      <router-outlet></router-outlet> <!--This is the parent outlet-->
    </div>
    <app-spinner #spinner></app-spinner>
  </div>
```
that is my **SpinnerComponent**:

```ts
@Component({
  selector: "app-spinner",
  templateUrl: "./spinner.component.html",
  styleUrls: ["./spinner.component.scss"]
})
export class SpinnerComponent  implements OnInit, OnDestroy {

  public visible = true;

  private subscription: Subscription;

  constructor(
    private loaderService: LoaderService
  ) { }

  public ngOnInit() {
    this.subscription = this.loaderService.loaderState
      .subscribe((state: LoaderState) => {
        this.visible = state.show;
      });
  }

  public ngOnDestroy() {
    this.subscription.unsubscribe();
  }
}
```
I tried to wrap the subscription in a `setTimeout`, but it still didn't work.

**Comment by maxisam** [comment]
@dgroh  You can subscribe to Router.event and use start and end event to turn on and off the spinner.

**Comment by wulfsberg** [comment]
I have a situation where the app and a component are both injecting a shared `trackerService`.
This service has an Observable value which the app subscribes to with an `|async` pipe.

The ngOnChanges/ngOnInit in the component causes an operation which emits a new value on the Observable.

This currently causes an ExpressionChangedAfterItHasBeenCheckedError, since the Observable has been resolved and shown in the app template(*) before the component is instantiated and triggers an emit.

Is a case like this covered under this issue?


(*) Simply writing the value with {{trackerService.count|async}} does not cause an exception, but doesn't update, while doing <div [ngClass]="{shown: trackerService.count|async}"> throws the exception.

**Comment by Martin-Wegner** [comment]
@mlaval I see that you working on it :) Do you have an idea when we can expect a solution? 5.0.0-beta.8?

**Comment by maxisam** [comment]
setTimeout trick doesn't work for subscribing for reactive form either.

http://plnkr.co/edit/AWUVT14RLohPhHCE8WkF?p=preview

**Comment by dinvlad** [comment]
Would be pretty nice to have this working. Currently reactive packages like https://github.com/ngrx/platform suffer from this issue when using dialogs or snackbars.

**Comment by yooRabbit** [comment]
Seem problem when  opening material2 dialogs within an observable,and It's been angular 5.

**Comment by danvwells** [comment]
I believe this manifests itself for me when opening a modal from ng-bootstrap during the ngModelChange or change events of a ```<select>```.  

None of the workarounds presented here work for me, but maybe I'm missing something.  

I created a demo of the issue with the most minimal code changes to get into the situation (3 commits from project creation, adding ng-bootstrap, and adding the modal) in case it helps: https://github.com/danvwells/ng-modal-bug.  Thanks for any help!

**Comment by victornoel** [comment]
@danvwells just wrap the content of `onIdChange` in a `setTimeout`:
```
  onIdChange(entityId: string) {
    setTimeout(() => {
      let mymodal = this.modalService.open(MymodalComponent, {
        keyboard: false,
        backdrop: 'static'
      });
    });
}
```

**Comment by danvwells** [comment]
@victornoel Thanks for the suggestion, however this still produces the error.  I tried it just as you coded it, as well as with a few different timeout lengths... up to 10 seconds.  None of it worked.  Weird, right?

**Comment by victornoel** [comment]
@danvwells ha, you are right. I suspect this issue is not the same as your problem then. I would suggest reporting it as an issue to ng-bootstrap, there is something really strange happening but I'm not clear what, I suppose the error is happening in one of the components managed by `NgbModal`.

**Comment by alexzuza** [comment]
@victornoel Hey, the following workaround should work for you

**html**
```
 <select [ngModel]="selectedId"  #ngModelDir="ngModel"
          (ngModelChange)="onIdChange($event, ngModelDir)">
```
**ts**

```
import { NgModel } from '@angular/forms';
...
onIdChange(entityId: string, ngModelDir: NgModel) {
  ngModelDir.control.markAsTouched();
  let mymodal = this.modalService.open(MymodalComponent, {
    keyboard: false,
    backdrop: 'static'
  });
}
```

**Comment by victornoel** [comment]
@alexzuza lol, that wasn't my problem :)

**Comment by alexzuza** [comment]
@victornoel Sorry:)

@danvwells Hey, please check the code above

**Comment by danvwells** [comment]
@alexzuza that appears to have got me passed that error, both in the sample as well as in my actual project!  Thanks!

**Comment by Martin-Wegner** [comment]
5.1.0 is out and this issue is still not fixed although PR #18352 is ready since October. I can't understand...

**Comment by susheelbanyal** [comment]
I have read [here](https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4
) and its working for me;
I have to update my code like this if i was using the **EventEmitter** to show the loader.


`ngAfterViewInit() {
    this.subscription = this.commonService.showLoader()
      .subscribe(item => {
        this.showLoader = item;
      });
  }`

` @Output() loader: EventEmitter<any> = new EventEmitter(true); //<-- true in EventEmitter(true)`

**Comment by Martin-Wegner** [comment]
@susheelbanyal this issue has nothing to do with EventEmitter?! For example: https://github.com/angular/angular/issues/17572#issuecomment-311589290

**Comment by susheelbanyal** [comment]
Ok

**Comment by Sntax** [comment]
Really crossing fingers this is fixed in the next update.

**Comment by kayvanbree** [comment]
Me too, I am working on a dockable panels solutions, in which I attach a dynamic component to a portalHost, which also throws this error.

**Comment by dottodot** [comment]
I'm seeing the same issue using portalHost for a loading indicator, wrapping it in a setTimeout does work but isn't ideal.

**Comment by russelltrafford** [comment]
As a note for others wanting more background reading on this:
https://hackernoon.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4

**Comment by tidusjar** [comment]
Is there an update on this?

**Comment by yaelkfir** [comment]
What worked for me was opening the `MatDialog` from a route gruard/resolver :)

**Comment by schankam** [comment]
2019, still not working ?

**Comment by montella1507** [comment]
Well.. CDK portal was a throb, that angular/material was more than example of bad implementation full of bugs.. unfortunately it is the same...  almost year old important bug, without any meaningfull response from development team :-( 

setTimeout() is propably good workarround (push it to next "change-cycle")

**Comment by internalsystemerror** [comment]
Guessing this milestone v7.0 issue isn't even going to make it to v8.0?

**Comment by gauri-focaloid** [comment]
2019 - August - Still not working ? :/

**Comment by Stephane-Peyroutet** [comment]
This issue was on the last batch of issues planned before v7 but it was not solved before the release.
It was not mentionned for v8 or v9.
Does anyone know if Ivy will change anything for this isssue ? or if Ivy has anything to do with that ?

**Comment by tayambamwanza** [comment]
Hopefully this will get sorted with Ivy

**Comment by omar-dulaimi** [comment]
2020, any updates?

**Comment by wirdehall** [comment]
Status on this? 2020 almost april now.
I see a commit referencing this thread but not sure if it solves it or not.

**Comment by mostlymark** [comment]
We ran into this issue with an async-triggered terms of service modal. The browser would throw an ExpressionChangedAfterItHasBeenCheckedError if the modal open call happened to trigger when the user has an [(ngModel)] form field in focus. We were able to workaround by doing this:

```javascript
this.service.mustRenewPolicyAgreement().subscribe((r) => {
  if (r) {
    try {
        document.activeElement.blur();
    } catch (e) {
        // do nothing
    }
    this.modal = this.modalService.open(this.modalTemplate, {
      centered: true,
      size: 'lg',
    });
  }
}

**Comment by fabiodamasceno** [comment]
Can we contribute to this somehow? At least we need to know if we keep use workarounds to deal with this problem. Libraries like ng material will be benefited with that. Today in Dialog component, for example, we need to use setTimeout :( : 
```js
 setTimeout(() => {
      const dialogRef = this.dialog.open(DialogComponent);
      dialogRef.afterClosed().subscribe(
         //some subscribe state changes that do not work without asked corretion.
      );
});
```

**Comment by petebacondarwin** [comment]
Since this appears to be affected a lot of users and is a fairly common use-case, I have bumped the priority to P2. Also I moved it from the `v7.0` milestone since that is clearly not appropriate any more.

**Comment by petebacondarwin** [comment]
Possibly this can be solved via `markDirty()`... see https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/core/src/render3/instructions/change_detection.ts#L27-L42

**Comment by sheikhziadahmed** [comment]
Any updates on this one? Its mid of 2021.

**Comment by all2pie** [comment]
Getting the same issue in my Directive

```
export class MyDirective implements Validator {
  
  constructor(
    inputRef: ElementRef,
    view: ViewContainerRef,
    factoryResolver: ComponentFactoryResolver
  ) {
    const compFactory = factoryResolver.resolveComponentFactory(
      SelectComponent
    );

    view.createComponent(
      compFactory,
      undefined,
      view.injector,
      [[inputRef.nativeElement]]
    );

  
  }

```

**Angular Version: 12.1.0**

**Comment by jsdevtom** [comment]
> We ran into this issue with an async-triggered terms of service modal. The browser would throw an ExpressionChangedAfterItHasBeenCheckedError if the modal open call happened to trigger when the user has an [(ngModel)] form field in focus. We were able to workaround by doing this:
> 
> ```js
> this.service.mustRenewPolicyAgreement().subscribe((r) => {
>   if (r) {
>     try {
>         document.activeElement.blur();
>     } catch (e) {
>         // do nothing
>     }
>     this.modal = this.modalService.open(this.modalTemplate, {
>       centered: true,
>       size: 'lg',
>     });
>   }
> }
> ```

@markanye This works. Especially when dealing with large forms where you don't want to mark controls as touched before opening the modal. It is also very legitimate, as the error arises from the ng-touched class being set after the view has changed. Thus, ensuring that the ng-touched is already set to true (becuase it has been), by blurring the active element is a logical solution. Thank you.

**Comment by danielsuter** [comment]
Issue still exists on Angular 14.

**Comment by atscott** [comment]
This is fixed internally by https://github.com/angular/angular/commit/606de5166e33affd7bd53d1ad86c11afa3cdbe21 and will be available to enable via a private export in the next 17.1 release. We found it to be breaking in what appears to be very rare cases (see https://github.com/angular/angular/pull/53022#issuecomment-1850817532) so it won't land officially until v18.
