### ISSUE TITLE
Angular Hero Tutorial: codes out of date

### ISSUE THREAD

**Issue by billcccheng** [angular/angular#15633]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Hi Angular! I wasn't sure where I file this because this is not a code related bug but it might cause a lot of frustration for new users trying out the **angular-hero-app**. The is just a code that is breaking because of new plugin being installed. On this [page](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html) under the **Add heroes to the dashboard** section. The original code is

```
@Component({
  selector: 'my-dashboard',
  templateUrl: './dashboard.component.html',
})
```

I believe it should be changed to:

```
@Component({
  selector: 'my-dashboard',
  templateUrl: 'app/dashboard.component.html',
})
```
or

```
@Component({
  moduleId: module.id
  selector: 'my-dashboard',
  templateUrl: './dashboard.component.html',
})
```

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> I wasn't sure where I file this

Report it on https://github.com/angular/angular.io/issues please. thanks

**Comment by Foxandxss** [comment]
@billcccheng we changed the docs long ago to not having to use module.id anymore with a systemjs plugin.

Is this still failing to you?

**Comment by wardbell** [comment]
This should not be a problem and we are discouraging people from using absolute paths because they don't AOT. We stopped even mentioning `moduleId`.

Closing as we won't be pursuing the recommendation in this issue.
