### ISSUE TITLE
Upgrading CLI rc1 to 1 (Angular 2.4 to 4.0) getting below error for .spec.ts

### ISSUE THREAD

**Issue by SirajGadhia** [angular/angular#15645]
windows 10 (64bit) and Visual studio Code 

C:/ ... src/app/about/about.component.spec.ts (7,3): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'beforeEach'.
C:/ ... src/app/about/about.component.spec.ts (7,15): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'beforeEachProviders'.
C:/ ... src/app/about/about.component.spec.ts (8,3): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'describe'.
C:/ ... src/app/about/about.component.spec.ts (8,13): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'xdescribe'.
C:/ ... src/app/about/about.component.spec.ts (9,3): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'expect'.
C:/ ... src/app/about/about.component.spec.ts (9,11): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'it'.
C:/ ... src/app/about/about.component.spec.ts (9,15): Module '"C:/ ... node_modules/@angular/core/testing/index"' has no exported member 'xit'.

**Comment by vikerman** [comment]
I am assuming you were importing from testing_internal. This is meant only for Angular team's internal use. You shouldn't have to import the above symbols - And you should get the global ones from Jasmine/Mocha.

Please re-open if this is still an issue.
