### ISSUE TITLE
Route params disappear on page reload

### ISSUE THREAD

**Issue by pddigital** [angular/angular#15643]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
For example, /brands/mybrand, where mybrand is a param...

On page refresh, this route redirects to root / in address bar. Component stays intact, but data is lost since the param is lost. Console.log does not hit on ngOnInit, so the component never actually reloads.

****Expected behavior****
Route params are available from an external link or on page refresh.

**Minimal reproduction of the problem with instructions**

1) Compile webpack bundle. 2) Launch Node server. 3) Navigate to page with params. 4) Refresh the browser.

`<base href="/">` exists and Node/Express is serving  the catchall route using the code below:

```
app.get('*', (request, response) => {
    response.sendFile(path.resolve(__dirname, 'dist', 'index.html'));
})
```

**What is the motivation / use case for changing the behavior?**
Routes with params need to be accessible by end users for sharing/linking...

**Please tell us about your environment:**
Windows 10, Mac OS X Sierra - both.

* **Angular version:**
 Angular common 2.4.10, Cli 2.4.1.

* **Browser:** [Chrome 57 | Firefox 52 ]

 
* **Language:** [TypeScript 2.0]

* **Node (for AoT issues):** `node --version` = 6.91

**Comment by DzmitryShylovich** [comment]
Please provide a small repro

**Comment by pddigital** [comment]
This is for a commercial application, but I have it up publicly on github. You won't be able to run it without a database, but look at it here: https://github.com/pddigital/catalog-site

**Comment by DzmitryShylovich** [comment]
we don't need your real code. just a small demo app

**Comment by pddigital** [comment]
Thanks for that suggestion... It works in my small demo app. The issue is that the ajax on the page wasn't resolving before the page content, I need to resolve that before the view/route loads. Closing.
