### ISSUE TITLE
canDeactivate guard runs from top down to child routes

### ISSUE THREAD

**Issue by royling** [angular/angular#15657]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

- navigate from `/root/branch/1` to `/root/branch/2`, canDeactivate guard runs from top down to the child
- navigate from `/root/branch/1` to `/`, canDeactivate guard runs from child to the top (which is as documented)

**Expected behavior**

As [documented](https://angular.io/docs/ts/latest/guide/router.html#!#guards), it should always run from child to top.
>The router checks the CanDeactivate() and CanActivateChild() guards first, from the deepest child route to the top.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/NxLmkAq1zTpWHjgH6S4C?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =   
6.9.5

**Comment by DzmitryShylovich** [comment]
> canDeactivate guard runs from child to the top (which is as documented)

> As documented, it should always run from top down to child.

could you please add a link to the docs? :)

**Comment by royling** [comment]
@DzmitryShylovich updated.

And I found this pb when fixing another issue. You may check PR#15651 for more details.

**Comment by DzmitryShylovich** [comment]
> The router checks the CanDeactivate() and CanActivateChild() guards first, from the deepest child route to the top.

looks like an error about `CanActivateChild`. The router checks `CanActivate` first and from the top to bottom http://plnkr.co/edit/NxLmkAq1zTpWHjgH6S4C?p=preview

**Comment by royling** [comment]
_I could remove other guards to demo this issue only, my fault._

In the example, if navigate from `/root/branch/1` to `/root/branch/2/leaf`, the deactivate guard runs in **top to bottom** (wrong) order:
```
DEACTIVATE: root
DEACTIVATE: branch
DEACTIVATE: leaf
```
if nav from `/root/branch/2/leaf` to `/whatever`, the guard order is **bottom to top** (as expected):
```
DEACTIVATE: leaf
DEACTIVATE: branch
DEACTIVATE: root
```

**Comment by DzmitryShylovich** [comment]
@royling correct. it's a `CanDeactivate` bug.
I'm talking about incorrect `CanActivateChild` description in the documentation.

**Comment by DzmitryShylovich** [comment]
@royling could you please create a new pr for this issue (1 issue - 1 pr) with a test only for `CanDeactivate` without can activate guards so it will be more clear and easier to review?

**Comment by royling** [comment]
@DzmitryShylovich 👌 will do it.
