### ISSUE TITLE
aio: improve performance and follow best practices 

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#15650]
Our current [Lighthouse][1] PWA score on staging is **99/100** (on my laptop).
Here is the [report][2] for dropping into [Lighthouse Report Viewer][3].
<sub>(See #15588 and #15628 for more info).</sub>

The report identified some things we can improve (independent of the PWA score) in terms of performance and following best practices, such as optimizing images, improving a11y etc. They are listed in the "Best Practices" and "Performance" sections of the report.

##
_UPDATE (2019-12-10):_
_[Note to self] We should also look into reducing render-blocking CSS size (and payload) by moving component-specific styles to components (instead of putting everything in `styles.css`)._

[1]: https://developers.google.com/web/tools/lighthouse/
[2]: https://github.com/angular/angular/files/884611/aio-staging_2017-03-31.report.txt
[3]: https://googlechrome.github.io/lighthouse/viewer/

**Comment by petebacondarwin** [comment]
Where are we at with this @gkalpak ?

**Comment by gkalpak** [comment]
We haven't done anything specifically for that. The current scores are:

```
PWA:            100%
Performance:     88%
Accessibility:   89%
Best Practices:  92%
```

There is still room for improvement, but nothing critical.
