### ISSUE TITLE
angular4 loadchildren component issue 

### ISSUE THREAD

**Issue by itranga** [angular/angular#15653]
Try load component lazy in angular 4 . Got the following  issue 

Code :  { path: 'about', loadChildren: './content/about/about.module#AboutModule' } ,
ERROR Error: Uncaught (in promise): Error: Cannot find module './content/about/about.module'.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by itranga** [comment]
Thanks . I submit issue in StackOverflow
