### ISSUE TITLE
Unable to get route working with 2 levels of lazy loaded modules (nested)

### ISSUE THREAD

**Issue by shankarvn** [angular/angular#15652]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have been trying to create a sample cli based angular4 application with a main module and 3 product modules (product itself being a route param that loads each of the product screen's lazily).

Here is my sample - https://github.com/shankarvn/angular4lazyloading

Steps to reproduce

git clone https://github.com/shankarvn/angular4lazyloading.git
cd application
npm install
ng serve -p 4003

In the browser localhost:4003 => Should load 3 cards showing product1, product2 and product3. At this point, click on product1 and you will see the route change and the ui for product1 loads. Now click on Dashboard and you will see an error in the console

ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'product1/dashboard'
Error: Cannot match any routes. URL Segment: 'product1/dashboard'
    at ApplyRedirects.noMatchError (router.es5.js:1404) [angular]
    at CatchSubscriber.selector (router.es5.js:1379) [angular]
    at CatchSubscriber.error (catch.js:104) [angular]

Unsure what I am doing wrong - Just that dashboard routes need to be loaded when the product1 module is lazily loaded. Shouldn't the routes get registered when the product1 module is lazy loaded? Any help is appreciated.

Thanks.

**Expected behavior**

Expect the Dashboard component to load.

**Minimal reproduction of the problem with instructions**

git clone https://github.com/shankarvn/angular4lazyloading.git
cd application
npm install
ng serve -p 4003
In the browser localhost:4003 => Should load 3 cards showing product1, product2 and product3. At this point, click on product1 and you will see the route change and the ui for product1 loads. Now click on Dashboard and you will see an error in the console

**What is the motivation / use case for changing the behavior?**

Nested lazy loading of modules should be a common thing.

**Please tell us about your environment:**

Browser web application.

* **Angular version:** 2.0.X

Angular 4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript

* **Node (for AoT issues):** `node --version` =   v7.7.4

**Comment by royling** [comment]
@shankarvn this is a question, so I think it'd better ask it on stackoverflow instead.

anyway, there're 2 errors in your code:
1. https://github.com/shankarvn/angular4lazyloading/blob/master/application/src/app/product1/product1.routes.ts#L13: use relative path instead, ie. `./dashboard/...` (otherwise, it's treated as absolute path, which is invalid).
2. Most importantly, always define the [default route ](https://github.com/shankarvn/angular4lazyloading/blob/master/application/src/app/product1/product1.routes.ts#L15-L19) as the first item

**Comment by shankarvn** [comment]
This is my error. Closing this - http://stackoverflow.com/questions/43133736/unable-to-get-route-working-with-2-levels-of-lazy-loaded-modules-nested
