### ISSUE TITLE
Canceled Location.forward() breaks history

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#15664]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When `CanDeactivate` cancels `Location.forward()` routing history is 1 item ahead.
Workflow
```
Home -- navigate to     --> Child 1
Child 1 -- navigate to     --> Child 2
Child 2 -- navigate to     --> Child 3 (CanDeactivate returned true)
Child 3 -- location.back() --> Child 2
Child 2 --  location.forward() --> Child 2 (navigation canceled CanDeactivate returned false)
Child 2 -- location.back() --> Child 2 (should be Route 1)
```

**Expected behavior**
```
Home -- navigate to     --> Child 1
Child 1 -- navigate to     --> Child 2
Child 2 -- navigate to     --> Child 3 (CanDeactivate returned true)
Child 3 -- location.back() --> Child 2
Child 2 --  location.forward() --> Child 2 (navigation canceled CanDeactivate returned false)
Child 2 -- location.back() --> Child 1 (expected)
```

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/PbKRj7v1B1tRVXRSrEup?p=preview

1. Click button Child1
2. Click button Child2
3. Click button Child3
4. Click button Back
5. Click button Forward
6. Click button Back

Expected behavior is to see `Child1` but it's still `Child2`

**Comment by patrickracicot** [comment]
Any progress on this issue? The PR #18135 for the referenced issue #18135 is still pending and the frequency seems to be bigger then initialy estimated.

**Comment by UlricW** [comment]
Any news on it ? 
That cause big side effect on our application. 
Thanks

**Comment by atscott** [comment]
Confirmed and marking as duplicate of #13586. Example in https://github.com/angular/angular/issues/13586#issuecomment-634226667 extended to include this use-case.
