### ISSUE TITLE
Callback on fail to load LazyLoaded chunks & Clear Browser Cache

### ISSUE THREAD

**Issue by iridiumsoft** [angular/angular#15665]
Is there anyway i can do something if application fail to load (LazyLoaded modules) chunks files. 
The reason why i want is that sometime on my live application when i build the project after changes and pull on live serve which removes the old js files and some of the clients browsers are still trying to get the old because of the browser cache, so in that case it just break Application. I want to clear cache when chunks fails to load so that the browsers can load different js file. May be other people do not face such a problem but its a lot pain for me. 
 
#### Version
@angular/cli: 1.0.0
node: 6.9.1
os: darwin x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/animations: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/platform-server: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

**Comment by DzmitryShylovich** [comment]
Just provide your own implementation of `NgModuleFactoryLoader` and handle any errors.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
