### ISSUE TITLE
DynamicComponents do not respect injectables property

### ISSUE THREAD

**Issue by TedSander** [angular/angular#1566]
DynamicComponent annotation has it's own injectables property which gets parsed separately from Component annotations. This information later gets dropped in DirectiveMetadataReader as only Component is checked:

https://github.com/angular/angular/blob/3667854a8f7a9f84c56c2e69aad0a804a0b52739/modules/angular2/src/core/compiler/directive_metadata_reader.js#L17

**Comment by TedSander** [comment]
Seems like it would also need to be added to element_injector.js here
https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/element_injector.js

Or better yet fix the TODO to extract into AbstractComponent

**Comment by naomiblack** [comment]
@pkozlowski-opensource how do you feel about taking a look at this one?

**Comment by pkozlowski-opensource** [comment]
Looks like `DynamicComponent` is going away with https://github.com/angular/angular/pull/1604. I'm going to wait till #1604 is merged and then re-test this scenario.

**Comment by pkozlowski-opensource** [comment]
@TedSander just to be sure that I understand your use-case, could you please have a look at this (failing) test and confirm that this is what you are trying to do: https://github.com/pkozlowski-opensource/angular/commit/1e554f91a3c4112a297d950072b23678712fa301 ?

@tbosch I wonder how we should treat injectables from the dynamic components: shell we make them available to dynamically loaded components as requested in this issue?

**Comment by TedSander** [comment]
It looks a lot like what I was seeing, but the particular bug probably
would have been fixed by removing DynamicComponent. The injectable
parameters on DynamicComponent wasn't doing anything, but now that they are
gone it should be OK :)

On Sat, May 2, 2015 at 2:16 AM, Pawel Kozlowski <notifications@github.com>
wrote:

> @TedSander <https://github.com/TedSander> just to be sure that I
> understand your use-case, could you please have a look at this (failing)
> test and confirm that this is what you are trying to do:
> pkozlowski-opensource@1e554f9
> <https://github.com/pkozlowski-opensource/angular/commit/1e554f91a3c4112a297d950072b23678712fa301>
> ?
>
> @tbosch <https://github.com/tbosch> I wonder how we should treat
> injectables from the dynamic components: shell we make them available to
> dynamically loaded components as requested in this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular/issues/1566#issuecomment-98337688>.
>



-- 
Ted Sander | Software Engineer | tsander@google.com | 408-857-5591

**Comment by pkozlowski-opensource** [comment]
@TedSander OK, so it looks like a non-issue after recent code changes. Feel free to open a new issue if / when it re-surfaces in this form or another.
