### ISSUE TITLE
Error: Can't resolve '@angular/core/src/metadata/directives'

### ISSUE THREAD

**Issue by pekubu** [angular/angular#15679]
I upgrade from 2.4 to 4.0.0 but I has error, pls help me
npm start
`ERROR in ./src/app/core/sidenav-item/sidenav-item.component.ts
Module not found: Error: Can't resolve '@angular/core/src/metadata/directives' in 'D:\Material\StartUp\src\app\core\sidenav-item'
 @ ./src/app/core/sidenav-item/sidenav-item.component.ts 11:0-62
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/core/generic-table/components/gt-pagination.component.ts
Module not found: Error: Can't resolve '@angular/core/src/metadata/directives' in 'D:\Material\StartUp\src\app\core\generic-table\components'
 @ ./src/app/core/generic-table/components/gt-pagination.component.ts 11:0-62
 @ ./src/app/core/generic-table/generic-table.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/core/generic-table/components/gt-table-info.component.ts
Module not found: Error: Can't resolve '@angular/core/src/metadata/directives' in 'D:\Material\StartUp\src\app\core\generic-table\components'
 @ ./src/app/core/generic-table/components/gt-table-info.component.ts 11:0-62
 @ ./src/app/core/generic-table/generic-table.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts`

ng build --aot
`ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 765:22 in the original .ts file), resolving symbol Input in D:/Material/StartUp/node_modules/@angular/core/src/metadata/directives.d.ts, resolving symbol GtPaginationComponent in D:/Material/StartUp/src/app/core/generic-table/components/gt-pagination.component.ts, resolving symbol GtPaginationComponent in D:/Material/StartUp/src/app/core/generic-table/components/gt-pagination.component.ts`

* **Angular version:** 4.0.0

* **Browser:** [all ]

 
* **Language:** [all | TypeScript 2x | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
do you import `Input` from `@angular/core/src/metadata/directives`?

**Comment by pekubu** [comment]
I edit import {Input} from '@angular/core/src/metadata/directives'; to import {Input} from '@angular/core';

and it working, thank you

**Comment by DzmitryShylovich** [comment]
yeah, deep imports are not supported. See https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md

**Comment by pekubu** [comment]
ok thank you
