### ISSUE TITLE
support for package a giant vendor.js

### ISSUE THREAD

**Issue by yupengfei** [angular/angular#15675]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Can not package a giant vendor.js with all angular 2 dependencies included easily.

**Expected behavior**

Provide a way to package a giant vendor.js with all angular 2 dependencies included easily.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I develop a app with 40 or more embed web apps as individual functions, I hope I can package every web app into index.html main.js vendor.js, among these index.html and main.js are small and loaded from server, while all those web apps use the same vendor.js  that contains everything and loaded from local.

**Please tell us about your environment:**

iOS, Android, PC(Qt WebEngine a.k.a chrome)

* **Angular version:** 2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
