### ISSUE TITLE
ngc aot fails when using Array.concat for declarations

### ISSUE THREAD

**Issue by KamelJabber** [angular/angular#15671]
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior**
When building the NgModule declarations array using Array.concat the ngc compiler fails with the following error:
> Cannot determine the module for class NavComponent in .../nav.component.ts! Add NavComponent to the NgModule to fix it.
Cannot determine the module for class AppComponent in .../app.component.ts! Add AppComponent to the NgModule to fix it.

**Expected behavior**
I expect to be able to concat arrays in my NgModule

**Minimal reproduction of the problem with instructions**
From an NgModule:

`import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { CommonModule } from '@angular/common';

import {
    AppComponent,
    NavComponent
} from './index';

const componentsArray: any[] = [
    AppComponent,
    NavComponent
];

const directivesArray: any[] = [
];

const pipesArray: any[] = [
];

var declarations: any[] = componentsArray.concat(directivesArray).concat(pipesArray);

@NgModule({
    imports: [ BrowserModule ],
    declarations: declarations,
    bootstrap: [ AppComponent ],
})

export class AppModule { }`

**What is the motivation / use case for changing the behavior?**
I thought the module would be easier to read if components, directives and pipes were listed in separate arrays.

**Please tell us about your environment:**
Visual Studio 2017, Windows 7 x64, NodeJs v6.10.0, NPM v3.10.10

* **Angular version:** 2.0.X
Angular version 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
v6.10.10

**Comment by DzmitryShylovich** [comment]
just `declarations: [directivesArray, pipesArray],` will unwrap and flatten it for you

**Comment by KamelJabber** [comment]
Wow, I'm a n00b, lol

That makes sense...Do I get partial credit for it being a bug though? :)

**Comment by DzmitryShylovich** [comment]
>  it being a bug

it's not a bug. function calls in decorators are not supported with aot

**Comment by KamelJabber** [comment]
ah, very enlightening, thanks!

**Comment by DzmitryShylovich** [comment]
Here you can find a full list of what is currently supported by ngc https://github.com/rangle/angular-2-aot-sandbox#current-status

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by marekozw** [comment]
@DzmitryShylovich could you be more specific? AFAIK Not all function calls are not supporter. Array.prototype.map or Array.prototype.push are totaly fine in AOT. It seems that there is something fishy about concat itself. Could you provide more elaborate explanation or point out a specific part in AOT compiler code that is responsible for that phenomena?

**Comment by alexsapps** [comment]
Could we consider this issue a feature request for detection of unsupported function calls and reporting a better error when its detected?
