### ISSUE TITLE
Route data not updated when upstream parameters change

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#15677]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Route params at parent level change, child level resolver is called to resolve new data, but route data observers are not notified that data has changed.
See https://github.com/angular/angular/issues/12942 where this issue as initially titled was fixed but the actual use case is still broken (I never tested the fix as the initial feedback was that the issue wasn't going to be fixed so prior to the fix landing I had already changed my routing to avoid this issue. Now attempting to refactor the resulting strange routing configuration and finding that the issue is still there)

**Expected behavior**
Route observers would be given the newly resolved data

**Minimal reproduction of the problem with instructions**

See https://github.com/slubowsky/resolve-issue
Run the app (ng serve). Click on the links to navigate. Resolver is called every navigation regardless of whether parent or child param changes and a message is logged to the console "FooResolve ..."

Component which has subscribed for route data is only notified (as evidenced by the console messages) when the child param changes.

**What is the motivation / use case for changing the behavior?**
Having resolver re-resolve the data without letting the components know is kind of useless...

**Please tell us about your environment:**

* **Angular version:** 2.0.X

@angular/cli: 1.0.0
node: 7.8.0
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
The new data is not pushed because it's the same as it was before.

**Comment by slubowsky** [comment]
OK, I guess that makes sense. Its a bit of a pain as my component may have long since moved on from the original data it received when the route was initially resolved and wants to be "reset" when route changes.

e.g. in my use case I use the param "new" to resolve to a new empty object for my form component to edit. If user navigates to "new" on another parent object, my component doesn't update with a new empty object since it thinks the one it created for last route is the same. (normally this isn't an issue as each object typically has an id to differentiate it from others but "new" is a special case where the same "id" can be found on multiple parents)

Ill close this issue and look for an alternative approach.

**Comment by DzmitryShylovich** [comment]
@slubowsky I believe we can make it configurable so you will receive data regardless of the previous value.

@vicb what do you think?

**Comment by slubowsky** [comment]
@DzmitryShylovich Thinking about it some more, I think you have to do this. Aside from my case of a new empty object Its easy to imagine cases where 2 sibling objects have child objects that happen to appear to be identical and rely on being inside their parent to differentiate them from each other. It might not be common for exact equality but when it does happen it will be a nightmare trying to duplicate the issue being reported by users and figure out why components sometimes aren't updating.

**Comment by mscu** [comment]
If i understood corrently, you could easily archive what you try to do by merging all parents data observables and then subscribe to it. A configurable option would also be nice.

**Comment by sharpmachine** [comment]
Experiencing this too. We have an omni search at the top of our app to search for people. If we're inside of a person's profile, and search from another person, and click a result to switch that that persons profile, the component doesn't reinitialize and all the data is still the previous person's data.

**Comment by kenisteward** [comment]
@sharpmachine if you want to get it to reinitialize every time implement the RouteReuseStrategy and change the default implementation of the shouldReuseRoute to return false.  

By default if a navigation switch has the same route config the just reuses the same route without reinitializing saving DOM manipulation time.

Default Implementation can be found here

https://github.com/angular/angular/blob/5d4f5434fd1c387f88ea46332a792ea94f9538da/packages/router/src/route_reuse_strategy.ts#L58-L69

i.e. 
```
export class CustomRouteReuseStrategy extends DefaultRouteResuseStrategy {
    shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
          return false
    }
}
```

I actually use a true custom RouteReuseStrategy that allows me to store previously created components and I reload based on the observable activated routes data.  It's super clean and super fast!  However this will get the job done for you.

**Comment by jasonaden** [comment]
Closing as this looks resolved as covered above. Open a new issue if there's still a bug.
