### ISSUE TITLE
Language Service: `[ngClass]` value not showing completions

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#15682]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

The value of an `[ngClass]` is not showing completions.

**Expected behavior**

Completions should be shown in the value of directives

**Minimal reproduction of the problem with instructions**

1. clone https://github.com/StephenFluin/ames
2. sync to 8d8026252c03d3a3e40a15dbaee0f263f9f7fb34
3. npm install
4. open ames/src/app/events/event-view.component.html
5. In line 14 request a completion in the value of the `[ngClass]`

**Comment by JoostK** [comment]
Closing as I can no longer reproduce this.
