### ISSUE TITLE
Jesus' list of aio issues

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#15681]
I am comparing 1-1 the old site with the new site and there is the list of issues, already discussed with @wardbell. I am not putting the design issues since @sjtrimble has her own document and she will document them there.

Issues to be fix manually in the Jade files **before migration**:

- [x] Escape HTML characters within a table (<script>, <link>...) @foxandxss
- [x] Remove some rogue `<i>` tags that are not needed @foxandxss
- [x] Change list created with `-` to list created to `*` @wardbell 
- [x] Add an extra space before and after a list @wardbell 

Rho issues:

- [x] Docplaster are doing nothing. *this is p0* @petebacondarwin 
- [x] Sometimes, after an URL there is no whitespace "Go to dependency injection, search `this guide explains what` and you will see what I mean" @petebacondarwin 
   _Partly fixed in #15698. There are still issues (e.g. `/guide/setup`: "npmpackages")_
- [x] Snippets (hardcoded or not) have an extra empty lines @petebacondarwin 
- [x] All the ** strong ** things are not parsed correctly. They generate an empty `<strong></strong>` tag and then the text to be bold. @petebacondarwin 
- [x] **Inside tables and ordered list, there is no markdown at all**. If it is to hard to fix, we could fix it by hand after migration @petebacondarwin 
- [x] One * is not for strong, it is for italics. @petebacondarwin 
- [x] On architecture, there is a list at the end as a blockquote (> signs) that is not being processed correctly. @petebacondarwin 
   _Rho does not support blockquotes. Pete suggested implementing it on his fork._
- [x] In template syntax, in the TOC at the beginning, there are links that are not ... links @petebacondarwin 
- [x] 3 stars (*) is a strong cursive.

Migrator issues:

- [x] The `hr` needs to be transformed into `<hr>` and not a div with a class @petebacondarwin 
   _Done : https://github.com/petebacondarwin/aio-migrator/commit/ba04030f0bde22950da12bfad5a38c58f6953a2a_
- [x] The :marked tags needs to be replaced by an empty line @petebacondarwin 
   _Done : https://github.com/petebacondarwin/aio-migrator/commit/e27b8a7837239a48669ef40e1c66f62d4be0d1d3_
- [x] Headers (lines with # signs) need to have an extra empty line before them to show up @petebacondarwin 
- [x] the makeExcerpt transformations are missing a title / header. The title is the content of the first parameter @petebacondarwin 
   _I believe this is fixed by https://github.com/petebacondarwin/aio-migrator/commit/7a01cad60265c698fea9b3ec154d4b5f3cb0a23b_
- [x] Fix when a link has a title, it sometimes cuts it (look for "you may need it" at aot-compiler)
- [x] makeExample without header gets the first param as header, unless it has an empty string as the third one
- [x] makeExcerpt are getting a header from the first parameter even if they get overriden.

Extra:

- [x] Add a BAD FILENAME or something when a snippet is empty @wardbell 

Issues to fix after the migration is done:

- [x] Change some hardcoded url for zips by hand @foxandxss
- [x] Some pages have double title (the old HERO + first header) @wardbell / @foxandxss
- [ ] Fix some `<br clear-both>` and make it looks good @wardbell / @foxandxss
- [x] Add jade includes, like the one at toh5 by hand @wardbell / foxandxss

**Comment by petebacondarwin** [comment]
> Docplaster are doing nothing. this is p0

I need more information and an example.

> All the ** strong ** things are not parsed correctly. They generate an empty <strong></strong> tag and then the text to be bold
> One * is not for strong, it is for italics

I believe I have already fixed this with https://github.com/angular/angular/commit/8c925bca71e8333e621daa25df574d9ed633edf2
Perhaps you need to do any `yarn install`?

> Inside tables and ordered list, there is no markdown at all. If it is to hard to fix, we could fix it by hand after migration

It is not really possible to automate this. Especially if the table cells contain more than one row of text.

> Headers (lines with # signs) need to have an extra empty line before them to show up 

I need some examples for this.

**Comment by petebacondarwin** [comment]
Closing as the last item is being tracked in #16681
