### ISSUE TITLE
build: Running out of filehandles when running tests

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#1570]
I've been sporadically getting an error from node,
EMFILE, too many open files
which I suspect could be attributed to leaking filehandles in our new broccoli build, since it creates a large number of temporary tree directories with lots of files.
+ @IgorMinar

**Comment by alexeagle** [comment]
I've been running `ulimit -n 2048` as a workaround.

**Comment by IgorMinar** [comment]
I believe that this is fixed since we switched to chokidar/fsevents based-watching.

it this is still an issue, please reopen.
