### ISSUE TITLE
Property 'controls' does not exist on type 'AbstractControl'

### ISSUE THREAD

**Issue by matheo** [angular/angular#15709]
**I'm submitting a**
```
[x] bug report
```

**Current behavior**
As there's no clean access to the `FormGroup`' controls, currently there's a `ng build -prod` error related to types when you try to access the `.controls` property, and `AbstractControl` does not have that property:
```
ERROR in ng:///path/to/app/my/custom.component.html (7,10): Property 'controls' does not exist on type 'AbstractControl'.
```
https://github.com/angular/angular/blob/4.0.0/packages/forms/src/model.ts#L834

where I have a form with subgroups like:
```
this.inputForm = this._builder.group({
  base: this._builder.group({
    monthly: [
      '', Validators.compose([Validators.required, Validators.pattern(regInt)])
    ],
   ...
  }),
  user: this._builder.group({
    ...
  })
});
```
and perform template-driven validations per row like:
```
<div class="form-group row" [ngClass]="{'has-danger': inputForm.controls.base.controls.monthly.dirty && !inputForm.controls.base.controls.monthly.valid}">
  <label class="col-4 col-form-label" for="inp-monthly">
    Monthly Expenses
  </label>
  <div class="col-8">
    <div class="input-group">
      <span class="input-group-addon" id="inp-monthly-s">$</span>
      <input class="form-control" id="inp-monthly" formControlName="monthly" aria-describedby="inp-monthly-s"
        type="number" min="1" placeholder="Add up all your costs (rent, salary, telephone, internet, inventory costs, etc)" />
    </div>
    <div class="form-control-feedback" [hidden]="inputForm.controls.base.controls.monthly.pristine || inputForm.controls.base.controls.monthly.valid">
     Please enter a quantity.
    </div>
  </div>
</div>
```

**Expected behavior**
`ng build -prod`to compile without Type errors.

**Minimal reproduction of the problem with instructions**
References to this issue are in this ticket: https://github.com/angular/angular/issues/10192#issuecomment-264246375

* **Angular version:** 4.0.1
Project built with angular/cli 4.0.0 but packages updated today to 4.0.1

**Comment by alexzuza** [comment]
Please create plunker. I am getting

> ERROR Error: Cannot find control with name: 'monthly'

with your code that can be solved by using `formGroupName`:

```
<div class="col-8" formGroupName="base"> <== this line
  <div class="input-group">
    <span class="input-group-addon" id="inp-monthly-s">$</span>
    <input class="form-control" id="inp-monthly" formControlName="monthly" />
  </div>
</div>
```

https://plnkr.co/edit/zClqshuN9AiTs6PGVcKq?p=preview

**Comment by matheo** [comment]
@alexzuza I'm just reporting a particular case of #10192

@DzmitryShylovich requested a new issue and I'm just showing how `ng build -prod` is failing with template-based validation or any other usage ot `.controls`

**Comment by DzmitryShylovich** [comment]
@matheo thanks. `FormGroup.controls` return type is `{[key: string]: AbstractControl}`. This is why you can't chain it. `inputForm.controls.base` will return `AbstractControl`. This is why you got an error.

as a workaround use `get` method: `inputForm.get('base..monthly').pristine`

**Comment by matheo** [comment]
@DzmitryShylovich wow, nice an clean.

I see, the issue in the other ticket is about not having a clean way to iterate the controls of a `FormGroup` or `FormArray`, but his simple stuff is Ok. Thanks a lot.

**Comment by matheo** [comment]
@DzmitryShylovich a little off-topic question about a problem I'm having firing `BehaviorSubject.next()` inside Angular services please, I have no clue of the cause so I don't open an issue yet:

I've tried to inject a `@ngrx/store` on a Service, and it subscribe Ok to it.
But then I try to `_store.dispatch` something, `ng serve` breaks
and the Service cannot be resolved anymore.

So, I've switched to a custom `rxjs/BehaviorSubject` and was able to dispatch new values with `.next()`. Then I faced some type errors because I opted by create a
```
result$: BehaviorSubject<Object> = new BehaviorSubject({});
```
and `{}` is not a "valid type" to fetch values later in the template.
So I built my interfaces and tried this in my service:
```
result$: BehaviorSubject<ResultState> = new BehaviorSubject(initialResult);
```
but it breaks again.

If I try to set an initial value there I have problems, I have to cast the contents to `<ResultState>` in the subscriptor in the meanwhile. So, this means that I have to study better the initial state for services because it's not that simple? Thanks in advance!

**Comment by DzmitryShylovich** [comment]
`result$: BehaviorSubject<ResultState> = new BehaviorSubject<ResultState>(initialResult);`

**Comment by matheo** [comment]
@DzmitryShylovich no luck :(
```
Uncaught Error: Can't resolve all parameters for MyCustomComponent: (?).
    at syntaxError (http://localhost:4200/vendor.bundle.js:40573:34) [<root>]
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:53421:35) [<root>]
    at CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.bundle.js:53289:26) [<root>]
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:4200/vendor.bundle.js:52900:24) [<root>]
    at CompileMetadataResolver._getEntryComponentMetadata (http://localhost:4200/vendor.bundle.js:53540:45) [<root>]
    at http://localhost:4200/vendor.bundle.js:53115:53 [<root>]
    at Array.map (native) [<root>]
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:53115:18) [<root>]
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:64148:64) [<root>]
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:64107:52) [<root>]
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:64069:21) [<root>]
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:5770:25) [<root>]
    at PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:5756:21) [<root>]
    at Object.179 (http://localhost:4200/main.bundle.js:106:124) [<root>]
```

**Comment by lazaridis-com** [comment]
@matheo , @DzmitryShylovich: maybe you want to exchange some cooking-recipes, too?

**Comment by matheo** [comment]
@lazaridis-com Yes please, cooking this `BehaviorSubject` with the `@Injectable` Service seems like a big deal... even when there are plenty of examples using them on Internet.

**Comment by lazaridis-com** [comment]
https://github.com/angular/angular/issues/10192#issuecomment-290826148

**Comment by matheo** [comment]
@lazaridis-com When I have the time to make a reproducable case, I will do.

**Comment by lazaridis-com** [comment]
@matheo, I meant the "please don't comment on closed issue.".  It's difficult enough to follow the angular development here, but if you use the issue-tracker as kind of "chat-support-system", then things become very difficult.

If you are not sure if something is a bug or not, or if you have questions, there are other resources to ask for help:

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

.

**Comment by itsnotvalid** [comment]
I'd have to say that @DzmitryShylovich 's workaround for AbstractControl doesn't work anymore with 4.0.2. I just think that validation for template on dynamic values is totally wrong even for aot, as there is no way to cast a value in template. Please add casting to template or shut that feature off.

**Comment by doppelgunner** [comment]
Yeah @itsnotvalid is right @DzmitryShylovich 's solution doesn't work for me. But I found a way, just reference the formArray in typescript:
```
formGroup: FormGroup;
formArray: FormArray;

initForm() {
  this.formArray = new FormArray([]);

  //init form array here - push FormGroups

 //then insert form array
 this.formBuilder.group({
 forms: formArray;
 });
}
```

Then just use `*ngFor="let form of formArray.controls` this way you don't need casting anymore

**Comment by artuska** [comment]
Well, issue is closed, but anyway, ` as FormGroup` is the key:

```
buildForm() {
    let fb = this.formBuilder;

    this.form = fb.group({
        animals: fb.group({
            cat: '',
            dog: '',
            other: ''
        })
    });
}

get animals(): FormGroup {
    return this.form.get('animals') as FormGroup;
}

<div class="button-list" formGroupName="animals">
    <label class="button" *ngFor="let animal of animals.controls | keys" [ngClass]="{'active': form.value.animals[animal]}">
        <input type="checkbox" formControlName="{{animal}}">
        <span class="button__text">{{animal}}</span>
    </label>
</div>
```

Angular 4.4.3

**Comment by almgwary** [comment]
I have nested arrays in the same forms, this doesn't work from me . why it should run on dev and after 2 weeks of development we get this error ?
