### ISSUE TITLE
why i can't get the cookie?

### ISSUE THREAD

**Issue by ws2823147532** [angular/angular#15708]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

i use http like this:
```typescript
login(loginUser: LoginUser): Promise<User> {
        return this.http.post(BaseUrl.getBaseUrl() + 'users/login', JSON.stringify(loginUser), { headers: this.headers })
            .toPromise()
            .then(res => res.json())
            .catch(this.handleError)
    }
```
**Expected behavior**

this should set cookie to broswer automatically,like this:
![image](https://cloud.githubusercontent.com/assets/19347103/24584646/a1ea46ae-17a6-11e7-9bc7-ae752eab16b9.png)
but, there is nothing.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Operating system - OS X EI 10.11.6 (15G31)
IDE - VS Code
HTTP server - java
* **Angular version:** 2.4.10

* **Browser:**  Chrome  56.0.2924.87 (64-bit) | FireFox 52.0.2 (64 位)

 
* **Language:** TypeScript 2.2.1 

* **Node (for AoT issues):** `node --version` =   3.10.10

**Comment by ws2823147532** [comment]
there is response headers:
![image](https://cloud.githubusercontent.com/assets/19347103/24584739/8177a53a-17a9-11e7-8611-f4185d8cfd09.png)

**Comment by DzmitryShylovich** [comment]
Angular has nothing to do with cookies.

**Comment by ws2823147532** [comment]
But,if I use tools like ‘postman’ to simulate request ,I can see the cookie in the broswer.

**Comment by ws2823147532** [comment]
Can you give me some reasons about the problem may happen.And give me some solutions to solve it. Thank you a lot. @DzmitryShylovich

**Comment by rikuayanokozy** [comment]
Github issues is not StackOverflow, you should ask questions on StackOverflow, and report bug/issues on the Github issues.
In this case, the cookie marked as HttpOnly so you can't access it via JavaScript.

**Comment by ws2823147532** [comment]
ok.
