### ISSUE TITLE
[PROJECT] Migration of "angular.io" repo to "angular" repo

### ISSUE THREAD

**Issue by ghost** [angular/angular#15703]
> IF YOU DON'T FILL OUT THE FOLLOWING INFORMATION WE MIGHT CLOSE YOUR ISSUE WITHOUT INVESTIGATING

[I did not even read it. Now shoot me.]

Within angular/angular.io#3493 a project-member mentioned that angular.io will migrate to the angular repo/project. I responded with this here:

"it surely has it benefits to have code&docu in one repo... but has the angular core-project not already too much traffic on it? I mean, an angular-docs subproject/repo/tracker enables to keep the noise away from the core-developers."

The angular project is already very difficult to follow, and it is nice to have the documentation completely within a separate repo/tracker.

Are there any chances that the decision to migrate the documentation-project (angular.io) will be revised?

**Comment by Toxicable** [comment]
https://github.com/angular/angular/tree/master/aio

**Comment by DzmitryShylovich** [comment]
+1 it was definitely not the best decision to move AIO into the main repo. To much unnecessary noise for regular devs.

**Comment by lazaridis-com** [comment]
At least keep the angular.io project for issues re documentation.

**Comment by wardbell** [comment]
Sorry folks but this decision is not up for debate. Let's make the best of it. Thanks.
