### ISSUE TITLE
Outdated i18n documentation

### ISSUE THREAD

**Issue by seanmcoleman** [angular/angular#15717]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The [current i18n documentation](https://angular.io/docs/ts/latest/cookbook/i18n.html) appears outdated. It describes a method of adding a plugin to SystemJS in order to load locale XML files as a string. Since Angular 4.0.0 does not use SystemJS in favor of webpack, this seems inapplicable. I'm currently unable to determine the best way to load static files with webpack.

**Expected behavior**
Updated documentation. 

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
I'm creating an app with basic i18n capabilities and instead of using a 3rd part plugin, I'm attempting to use the officially supported Angular approach.

**Please tell us about your environment:** 
N/A

* **Angular version:** 4.0.0

* **Browser:** [ N/A ]
 
* **Language:** [ N/A ]

* **Node (for AoT issues):** `node --version` =   7.6.0

**Comment by Toxicable** [comment]
Angular does not use either of SystemJS or Webpack, you can use whatever build tools you'd like. That is an example of how you can do it with SystemJS

**Comment by seanmcoleman** [comment]
@Toxicable What is the best way to load the file as a string via Angular CLI so not to introduce a new build system like SystemJS or Webpack?

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
