### ISSUE TITLE
Animations: Importing and Unit Tests

### ISSUE THREAD

**Issue by schmuli** [angular/angular#15713]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[x] support request
```

**Note**
I have searched both Github issues and Stackoverflow for anything related, and have not found anything. Additionally, because I think that this might be a Bug, I am opening an issue, rather than asking a question on SO.

**Current behavior**
I'm trying to update an app to Angular 4.x, and need to add `@angular/animations` for third-party components (the app itself doesn't use any).

Looking at the minimal documentation currently available on animations, and after looking a little at the source code, I am trying to figure out the correct way to import the Animation module.

1. Contrary to components, it appears that I only need to import the `AnimationsBrowserModule` once for my application, and then I can use the animation functions anywhere in my (or third party) code. Is this correct?
2. When writing unit-tests using the Angular testing framework, what is the correct way to import an animation module into the testing module?

3. I noticed that the `AnimationBrowserModule` imports the `BrowserModule`, and since the docs on `BrowserModule` states that it should only be imported once at the root of the application, is this also correct for the `AnimationBrowserModule`?

4. If Q3 above is correct, how do I import an animation module for unit-tests written using the Angular testing framework, for library code? I.e. in the case where there is no root `app` module, which module should be imported and by whom?

5. Related: Please clarify the different bundles that need to be imported, when and where to import them, and optionally how to correctly configure SystemJS:
    - `'@angular/animations'`
    - `'@angular/animations/browser'`
    - `'@angular/platform-browser/animations'`

**Expected behavior**
Add a testing animation module, or allow animation state attributes (`@state`) to be valid even when no animation module is imported.

Additionally, can the animation bundles be made easier to use, especially in a SystemJS environment.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
Make it easier to document, write code, and write unit-tests, including library code, when using animations or third-party components with animations.

**Please tell us about your environment:**
* **Platforms:** Windows 7 & 10, macOS

* **IDEs:** WebStorm, VS Code

* **Angular version:** 4.0.X

* **Browser:** all
 
* **Language:** TypeScript 2.2.x

**Comment by mscu** [comment]
I used the NoopAnimationsModule because i had a different problem, but this worked for me

```typescript
import { TestBed, async } from '@angular/core/testing';

import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { animationPlayerFactory } from './animation-player.factory';

import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      import: [
        NoopAnimationsModule
      ],
      declarations: [
        AppComponent
      ],
    }).compileComponents();
  }));

  // tests...

});
```

**Comment by schmuli** [comment]
@mscu I understand that I can do that, and that will work for my testing issue.

However, what is still non-consistent, is that when writing code, I can rely on the fact that someone somewhere has imported the correct animation module into the application. So for example in a library that relies on animation, there might not be anywhere in the library code that actually imports the animation module.

But then all of a sudden when writing tests, not only do I need to worry about importing an animation module, but now I need to remember to do this for every single testing module, even in situations where I'm just referencing other (potentially 3rd party) modules and don't necessarily know that animations are being used.

**Comment by tbosch** [comment]
For tests, you can also configure the `NoopAnimationsModule` at a central place: At the place where you call `TestBed.initTestEnvironment`. The first argument can now be an array, e.g.

```
TestBed.initTestEnvironment([
  BrowserDynamicTestingModule, NoopAnimationsModule
], platformBrowserDynamicTesting());
```

**Comment by patrickoneill46** [comment]
Hi, I am trying to use this example to fix an issue I have with one of my tests. I am simply sliding in a menu on clicking a toggle button.

When I call `fixture.detectChanges` after clicking I get an error which I am pretty sure is related to animations not being run

`    at Object.debugUpdateRenderer [as updateRenderer] (http://localhost:9876/base/src/test.ts?b14a89702f2a8965475dd99b005fe58200f63b19:17813:21)
    at checkAndUpdateView (http://localhost:9876/base/src/test.ts?b14a89702f2a8965475dd99b005fe58200f63b19:17118:14)
    at callViewAction (http://localhost:9876/base/src/test.ts?b14a89702f2a8965475dd99b005fe58200f63b19:17476:21)
    at execEmbeddedViewsAction (http://localhost:9876/base/src/test.ts?b14a89702f2a8965475dd99b005fe58200f63b19:17434:17)
    at checkAndUpdateView (http://localhost:9876/base/src/test.ts?b14a89702f2a8965475dd99b005fe58200f63b19:17114:5)
    at callViewAction (http://localhost:9876/base/src/test.ts?b14a89702f2a8965475dd99b005fe58200f63b19:17476:21)
    at execEmbeddedViewsAction (http://localhost:9876/base/src/test.ts?b14a89702f2a8965475dd99b005fe58200f63b19:17434:17)
    at checkAndUpdateView (http://localhost:9876/base/src/test.ts?b14a89702f2a8965475dd99b005fe58200f63b19:17114:5)
    at callViewAction (http://localhost:9876/base/src/test.ts?b14a89702f2a8965475dd99b005fe58200f63b19:17476:21)`

**Comment by matsko** [comment]
As was pointed out in the example before, initializing a TestBed setup with NoopAnimationsModule will do the trick. If it gets to be too much code then just make a module that extends your app module and also includes the noop module as an import.

Closing this for now. Please open a new issue incase it still persists.
