### ISSUE TITLE
Module 'ts' has no exported member 'NoSubstitutionTemplateLiteral'.

### ISSUE THREAD

**Issue by MohammedSabbah** [angular/angular#15710]
ERROR in /home/sabbah/Desktop/Here-you-will-work/watania_live/Devlop/node_modules/codelyzer/util/astQuery.d.ts (6,101): Module 'ts' has no exported member 'NoSubstitutionTemplateLiteral'.
/home/sabbah/Desktop/Here-you-will-work/watania_live/Devlop/node_modules/codelyzer/util/astQuery.d.ts (13,67): Module 'ts' has no exported member 'NoSubstitutionTemplateLiteral'. 

{
  "name": "al-watania",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.7",
    "@angular/compiler": "^2.4.7",
    "@angular/compiler-cli": "^2.4.7",
    "@angular/core": "^2.4.7",
    "@angular/forms": "^2.4.7",
    "@angular/http": "^2.4.7",
    "@angular/platform-browser": "^2.4.7",
    "@angular/platform-browser-dynamic": "^2.4.7",
    "@angular/router": "^3.4.7",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.20",
    "@types/node": "^6.0.63",
    "angular2-universal": "^2.1.0-rc.1",
    "body-parser": "^1.17.1",
    "codelyzer": "^2.0.0",
    "core-js": "^2.4.1",
    "express": "^4.15.2",
    "jquery": "^3.1.1",
    "ng2-bootstrap": "^1.3.3",
    "ng2-file-upload": "^1.1.4-2",
    "ng2-meta": "https://github.com/chocobozzz/ng2-meta#build",
    "ng2-page-transition": "^0.2.6",
    "ng2-pagination": "^2.0.1",
    "preboot": "^4.5.2",
    "rxjs": "^5.1.1",
    "ts-helpers": "^1.1.1",
    "web-animations-js": "^2.2.2",
    "zone.js": "^0.7.7"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3",
    "html-loader": "^0.4.3"
  }
}
![screenshot from 2017-04-02 09-44-49](https://cloud.githubusercontent.com/assets/22482236/24585015/351948ee-1789-11e7-80ca-31fcd4fdb5aa.png)
![screenshot from 2017-04-02 09-46-45](https://cloud.githubusercontent.com/assets/22482236/24585024/4fb7e66a-1789-11e7-9746-a1b8eb20fd42.png)

I had this problem after upgrading to node 7.8

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by DzmitryShylovich** [comment]
> work/watania_live/Devlop/node_modules/codelyzer/util/astQuery.d.ts (13,67): Module 'ts' has no exported member 'NoSubstitutionTemplateLiteral'.

Looks like it's `codelyzer` issue. Please repost this issue on https://github.com/mgechev/codelyzer/issues

**Comment by MohammedSabbah** [comment]
https://github.com/mgechev/codelyzer/issues/288
