### ISSUE TITLE
 Server-side rendering: [innerText] doesn't render while {{ }} does

### ISSUE THREAD

**Issue by Owain94** [angular/angular#15719]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When you use [innerText]="var" it will not show up on the server rendered view while {{ var }} does

**Expected behavior**

[innerText] should be rendered on the server-side rendered view

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Angular 4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

All

* **Node (for AoT issues):** `node --version` =   v7.7.3

**Comment by adrienboulle** [comment]
i can confirm it does not work.
On the other hand [innerHTML] works.

**Comment by Owain94** [comment]
Fix in https://github.com/angular/angular/pull/15818
Closing this one
