### ISSUE TITLE
Confused! Where should we file router issues now? 

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#1571]
I'm a bit confused now, in which repo we should file issues regarding the router now? Here, or in [Brians](https://github.com/angular/router)?

And if I want to pull a wip copy to play with?

**Comment by PascalPrecht** [comment]
The router is only temporarily moved to this repo. I'd suggest opening issues and PR's at the standalone repo.

**Comment by btford** [comment]
@PascalPrecht is correct – until the angular2 build system becomes modular enough to use in angular/router, I'm going to move the whole thing here.
