### ISSUE TITLE
AuthGuard with roles

### ISSUE THREAD

**Issue by OdaiTu** [angular/angular#15712]
hello

i would like know what is the best practice to make my AuthGuard with roles so i can control the admin ,superadmin and user using jwt token with roles

i see this question here but it seems not good idea to do it this way

[http://stackoverflow.com/questions/38402776/angular2-routing-canactivate-and-authguard-jwt-with-user-role-parameter](url)

so i want to hear as other people want form a angular team

thank you

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by OdaiTu** [comment]
thank you for your fast reply i understand this but can you leave a comment on stackoverflow 
so the question there requires to be answered with correct answer ?

**Comment by Toxicable** [comment]
There are countless number of ways you can do this and for the most part which one is better depends on different factors per situation. Therefore there is no correct answer here but I'll admit there are some worse ones and better ones.
Either way, this isn't the place for this kind of question, please repost it ti StackOverflow with the tag `angular` or ask in [gitter](https://gitter.im/angular/angular)
