### ISSUE TITLE
Ionic 2 and Laravel API Route

### ISSUE THREAD

**Issue by aneeskodappana** [angular/angular#15724]
has anyone used ionic 2 and Laravel API routes mechanism together

how to get the data passed along with the post request in angular 2.

```
http.post('someurl.com', {title: "title goes here", body: "Body goes here"})
.map(res => res.json()).
subscribe(res => {
    console.log(res);
})
```

how to access the data passed through the second parameter of the post method in Laravel 5.4

```
Route::post('/testurl', function(Request $request){
    return $request->title;
});
```

The above code doesn't work

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
