### ISSUE TITLE
ngc: inlining templates and styles

### ISSUE THREAD

**Issue by dherges** [angular/angular#15722]
**I'm submitting a ...** 
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**

Inlinig `templateUrl` and `stylesUrls` is implemented in external tools, e.g. [rollup-plugin-angular-inline](https://github.com/filipesilva/rollup-plugin-angular-inline), [gulp-inline-angular-templates](wmluke/gulp-inline-angular-templates), or custom build scripts like in [material2](https://github.com/angular/material2/blob/master/tools/gulp/tasks/release.ts#L197-L223).

This leads to situation where inlining happens in different build phases. Also, feature is implemented multiple times by community.

**Expected behavior**

Inlining templates and styles could be performed by `ngc`.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Are there any plans to implement this feature in `ngc`?

I think it'll be helpful for library authors. I think it's going to lead to more simplicity in build tool chains and less code dupes, making it easier to understand and track what is going on in angular builds.

Of course, this should be an opt-in feature and could be configured in `angularCompilerOptions`, e.g.  `inlineTemplates: true|false` and `inlineStyles: true|false }`.

**Please tell us about your environment:** does not apply

* **Angular version:** 2.X / 4.X

* **Browser:** all
 
* **Language:** TypeScript

**Comment by efreethy** [comment]
https://www.npmjs.com/package/gulp-inline-ng2-template is a library that does this and is getting ~30k dl/mo so I will add that there is a strong demand for this. 

Right not the ngc compiler doesn't create a build that can be properly pulled from npm after publish. Developers are currently forced to transform their templateUrls into template string references before running ngc as a workaround

**Comment by AnimaMundi** [comment]
Rather than including this functionality in ngc, I think it would be great if ngc was able take to take vinyl files or a stream as input and emit the same. This would allow for ngc to be included in a gulp pipeline much more easily and then ngc can focus on its job. I think if ngc included inlining then it would be doing too much.

**Comment by dherges** [comment]
Let's ask whether it's possible with TypeScript transforms? See [ng-packagr#261](https://github.com/dherges/ng-packagr/issues/261)
