### ISSUE TITLE
Router NavigateByUrl freezes in resolver

### ISSUE THREAD

**Issue by dajxr8** [angular/angular#15725]
**I'm submitting a ...** 
```
[x] bug report 
[ ] feature request
[ ] support request => 
```

**Current behavior**

Using router.navigateByUrl inside an observable .catch() freezes the whole app preventing the user from navigating and nothing appears in the console logs.
(API call from a resolver )

And I want to add that on one of my old project ( router version 3.0.0 ) the router.navigateByUrl works as expected. So I can't really tell when the bug appeared.

**Expected behavior**
For example I should be able to get a user from the API using http, if the request returns 404,  .catch() catches the error and redirects to '/404' with router.navigateByUrl.

**Minimal reproduction of the problem with instructions**
Here is the plunker : https://plnkr.co/edit/SL69HN6i4auKJXmObkMi?p=preview

It's basically the example from the Angular official tutorial.
I edited it a bit with a real api call from an online test API.
The methods are defined in hero.service.ts and the API call happens in the hero-detail-resolver.service.ts

You can click on a user, it works as expected you can't still come back to /dashboard and click on another.
But whenever you click on "404 Here and freeze" it calls the API, returns 404 and it just freezes and you can't navigate anymore.

**What is the motivation / use case for changing the behavior?**

I want to be able to redirect a user to a 404 route if the API call returns 404.

**Please tell us about your environment:**

The bug happens on my computer ( Windows 10 / Visual Studio Code / NodeJS )
But it does not really matter as it also happens on plunker.

* **Angular version:** 4.0

* **Browser:** [all]
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` = 7.4.0

**Comment by DzmitryShylovich** [comment]
> Here is the plunker : https://plnkr.co/edit/SL69HN6i4auKJXmObkMi?p=preview

thanks for submitting the issue, but this plunkr is too big. Please remove all unrelated stuff. The easier you make it for us the more likely we will be able to get to the bottom and have a fix for you. Thanks.

**Comment by vicb** [comment]
Please open a new issue when you have a smaller reproduction (the minimal set of files to reproduce the issue). Thanks.
