### ISSUE TITLE
animations is adding style onto parent elements

### ISSUE THREAD

**Issue by dsoltesz** [angular/angular#15726]
Bug with animations module

**Current behavior**
when animations library is used, parent elements are getting styles applied

`<div>`

    <div fxLayout="row" fxLayoutAlign="start start" fxFlex.xs="100" fxFlex.sm="50" fxFlex.md="33" fxFlex.lg="33" fxFlex="25">
        <div [routerLink]="['/program/search']" routerLinkActive="active" class="homeModule" fxLayout="column" fxLayoutAlign="center center">
            <i class="fa fa-search" aria-hidden="true"></i>
                    </div>
    </div>
`</div>`

when I run the parent div is getting a style added onto which is throwing off my layout

`<div style="display: flex;box-sizing: border-box;flex-direction: row;-webkit-box-orient: `horizontal;-webkit-'box-direction: normal;">

Have no idea where or why this style is being added.  If I create a project that doesn't have animations, the parent div is untouched and renders as expected
    

**Expected behavior**
animations should not be adding inline styles onto parent elements

**Minimal reproduction of the problem with instructions**
here is link to sample project that demonstrates the issues, you'll see styles added onto the app-root node

https://1drv.ms/u/s!Av38BrZQIQSFqYsqNGeZKxUA9ZQdwg

if a create a new project using cli and add in flexLayoutModule and don't add any dependencies on animations, the issue does not happen.

**Please tell us about your environment:**
angular cli 1.0

* **Angular version:** 4.0.0

Happens in all browsers

**Comment by dsoltesz** [comment]
This seems like a pretty big issue, any help out there?

**Comment by kkoutros** [comment]
The same issue here as well using flex layout and animations module.

**Comment by rosslavery** [comment]
I'm also affected by this issue. Not certain whether it belongs to flex-layout, or animations module, but seems quite serious, as layouts become totally broken and the inline styles make it challenging to wrangle/override.

Tried substituting `BrowserAnimationsModule` with `NoopAnimationsModule`, but no luck.

@matsko @ThomasBurleson Any thoughts?

**Comment by rosslavery** [comment]
Decided to dive in to @dsoltesz example application. Fairly certain this is a flex-layout related issue. If you completely remove @angular/animations, the issue still happens.

Will create issue in flex-layout repo.

**Comment by ThomasBurleson** [comment]
@dsoltesz - @angular/flex-layout directives inject css styles directly onto the host element. This works as expected. @matsko - we should close this as "not an issue".

**Comment by mcwebdev** [comment]
@ThomasBurleson that is slightly incorrect. The bug @dsoltesz reported was inline styling being attached to a parent element, not the host element.

**Comment by matsko** [comment]
This isn't an animation issue with Angular's animation system due to the lack of `@properties`. Flex layouts also doesn't use animations.

**Comment by ThomasBurleson** [comment]
@matsko - Agreed. 
@dsoltesz - please close this issue here and reopen a [Angular Flex-Layout Issue](http://github.com/angular/flex-layout/issues/new).

**Comment by dsoltesz** [comment]
when I first created this, I couldn't get the issue to happen until I added in the animations library so that's why I thought it was related

**Comment by matsko** [comment]
ok so when `BrowserAnimationsModule` is activated then the issue surfaces?

**Comment by rosslavery** [comment]
@matsko Nah you're fine :). It's `flex-layout`-related, and conversation happening about whether it's an issue or not.

**Comment by matsko** [comment]
Closing this since it's tied to flex layouts.
