### ISSUE TITLE
CanDeactivate Bug

### ISSUE THREAD

**Issue by Max-Lev** [angular/angular#15737]
"@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",

CanDeactivate with location.back redirects outside of an app on 3 click.

**Comment by DzmitryShylovich** [comment]
Please provide:
1. a plunkr that reproduces the issue
2. observed behavior
3. expected behavior

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by suplch** [comment]
reproduce url
http://plnkr.co/edit/YL329mc7PxMYvx7ad5eK?p=preview

https://github.com/angular/angular/issues/15978
