### ISSUE TITLE
aio: Provide Information about Ongoing Doc Migration

### ISSUE THREAD

**Issue by ghost** [angular/angular#15738]
E.g.: If I want to correct a documentation file (send a PR in), which repo do I use? (this is an actual question of mine)

- Where to file issues re docu? (angular or angular.io) 
- What are you migrating, and why.
- Someone who wants to contribute now (during the migration), which repo to use for local docu build?

**Comment by Foxandxss** [comment]
Documentation changes are still open at angular.io but I expect it to be frozen in the next few days. For issues, you can still use the old site until we fully migrate.

For local build I suggest the old site for now.

**Comment by petebacondarwin** [comment]
We have no committed the migration to angular/angular. All docs fixes should be targeted here and not at angular.io.
