### ISSUE TITLE
Router data subscribe calling twice on MacOs and once on windows

### ISSUE THREAD

**Issue by Jonatthu** [angular/angular#15734]
**I'm submitting a ...** 
```
[x ] bug report
```

**Current behavior**
I have a resolver and a component is subscribed to the data result, but this only on windows inputs one console log and on macOS two, no matters if is google chrome or safari, the same for iOS safari and iOS google chrome
```
    this.listing$Subs = this._route.data.subscribe(x => {
      const results: Listing[] = x['listings']['data'];
      if (results.length === 0) {
        console.log('No results add alert'); // All this function is being called twice on macOS or iOS
        this.store.alerts.add();
      }
 });
```
The problem comes when I call `this.store.alerts.add();` which is added two times only on macOS or iOS.
Which is not happening on Windows

**Expected behavior**
Should only call once the subscribe function

**Minimal reproduction of the problem with instructions**
I will add plunkr if is necessary, I don't know if this is part of a milestone yet.
![angularsubscribeevent](https://cloud.githubusercontent.com/assets/3742176/24625398/c4bd28d2-1863-11e7-9a94-02c2f16dad57.png)

**Please tell us about your environment:**
MacOS sierra, iOS 10, windows 10 and the latest on all the browsers 

* **Angular version:** 4.0.0

* **Browser:**  all
 
* **Language:** TS 2.2.1

**Comment by Toxicable** [comment]
Can you please make a minimal reproduction of this in Plunkr so we can test it

**Comment by Jonatthu** [comment]
Ok working on a Plunkr ultil I have it I will reopen this issue
