### ISSUE TITLE
Race condition in `Testabilities` API.

### ISSUE THREAD

**Issue by krotscheck** [angular/angular#15743]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ x ] feature request
```

**Current behavior**
This is a cross-post of https://github.com/angular/protractor/issues/3763, as it is a race condition between protractor and the angular testabilities API.

The issue appears when you start with an APP_INITIALIZATION provider that returns _after_ protractor has triggered its check for angular. It also occurs if you are testing with high latency to your hosted site, but low latency to your selenium grid/browser (i.e. selenium grid is on an internal corpnet, application on AWS).

An application is not registered with the `Testabilities` api until after app initialization is complete. If protractor checks before that happens, protractor will time out.

**Expected behavior**
Protractor should be able to check at any time how many applications are testable, and what initialization state they are in. It should be able to wait for all applications on a page to finish initialization.

I see a few different approaches here:

1. Move testability registration before initialization.
2. Register the initialization state of the application via promises.
3. Similar to 2; keep track of the 'stability' of the application via Observables.

Once a fix lands in angular, a complementary fix in protractor will be required.

**Minimal reproduction of the problem with instructions**
Taken from @cnishina's example in the linked ticket.

```
providers: [
    {provide: APP_INITIALIZER, useValue: () => new Promise((resolve) => {
      setTimeout(resolve, 10000);
    }), multi: true}
],
```

**What is the motivation / use case for changing the behavior?**
Reduce race condition and unexpected timeouts when testing with protractor.

**Please tell us about your environment:**
Browsers on browserstack, and on an internal selenium grid. Using protractor 5, selenium 3, Angular 2.0. Application hosted on S3. Initialization routine that returns in 500ms or less for session initialization.

* **Angular version:** 2.0.X

* **Browser:** [all]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   7.5.0

**Comment by dylhunn** [comment]
Closing, as protractor is deprecated.
