### ISSUE TITLE
Upgrade Angular 2 to Angular 4 has no exported member 'AnimationDriver'. Error

### ISSUE THREAD

**Issue by pvuser** [angular/angular#15747]
Hi,

I have upgraded Angular 2 to Angular 4. When run my project i am facing the below error.

node_modules/@angular/platform-browser/platform-browser"' has no exported member 'AnimationDriver'.

Please guide me soon.This is my live Project.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
