### ISSUE TITLE
function getOutlet(outletMap, route)

### ISSUE THREAD

**Issue by sail-sail** [angular/angular#15746]
In the router.es5.js , I change the function:
```typescript
/**
 * @param {?} outletMap
 * @param {?} route
 * @return {?}
 */
function getOutlet(outletMap, route) {
    //Sail
    var tmpFn = function(_outlets) {
        var outlet = _outlets[route.outlet];
        if(outlet) return outlet;
        var keys = Object.keys(_outlets);
        for(var i=0; i<keys.length; i++) {
            var key = keys[i];
            if(!_outlets[key] || !_outlets[key].outletMap) continue;
            outlet = tmpFn(_outlets[key].outletMap._outlets);
            if(outlet) return outlet;
        }
    };
    var outlet = tmpFn(outletMap._outlets);
    if (!outlet) {
        var /** @type {?} */ componentName = ((route.component)).name;
        if (route.outlet === PRIMARY_OUTLET) {
            throw new Error("Cannot find primary outlet to load '" + componentName + "'");
        }
        else {
            throw new Error("Cannot find the outlet " + route.outlet + " to load '" + componentName + "'");
        }
    }
    return outlet;
}
```

**Comment by DzmitryShylovich** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
