### ISSUE TITLE
ngModel gets updated when local variable gets changed

### ISSUE THREAD

**Issue by itsbalavignesh** [angular/angular#15745]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   

I am setting a local variable which is assigned with ngModel property as shown below

this.elementvalue holds the value ["AAA"]

let elvalue:any=this.elementvalue;

The issue is when i change the local variable the ngModel also gets updated

elvalue=["BBB"]

Result:

this.elementvalue changed to ["BBB"]

How to make a ngModel property as one way. Provide a solution.

**Comment by adrienboulle** [comment]
your two variables refer to an array which is an object so you have `elvalue === elementvalue`
If you want you can copy the array since its an array of strings by doing `elvalue = elementvalue.slice(0);`
(if your array is an array of objets it won't work)

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
