### ISSUE TITLE
All minified umd bundles uses absolute path to refer to the source map file

### ISSUE THREAD

**Issue by pe8ter** [angular/angular#15740]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**

The npm module `@angular/compiler` has a file _compiler.umd.min.js_ that contains an absolute file system path of a developer's machine to the map file _compiler.umd.min.js.map_

    //# sourceMappingURL=/Users/berchet/Code/angular/dist/packages-dist/compiler/bundles/compiler.umd.min.js.map

which 404s.

**Expected behavior**

The path should be relative:

    //# sourceMappingURL=compiler.umd.min.js.map

**Minimal reproduction of the problem with instructions**

No need to reproduce. The bug is evident from the installed `@angular/compiler` npm module.

**What is the motivation / use case for changing the behavior?**

Source should have correct source maps. Avoid 404s.

**Please tell us about your environment:**

* **Angular version:** 4.0.1

**Comment by Riobe** [comment]
Just saw this 404 while learning angular. These are the exact built files that have it in them:

```bash
$ grep -o '/Users/berchet' ./node_modules/@angular/compiler/bundles/*
./node_modules/@angular/compiler/bundles/compiler.umd.min.js:/Users/berchet
./node_modules/@angular/compiler/bundles/compiler.umd.min.js.map:/Users/berchet
./node_modules/@angular/compiler/bundles/compiler.umd.min.js.map:/Users/berchet
```

**Comment by pe8ter** [comment]
Confirmed this bug still exists in Angular 4.0.2, but with a different path:

```javascript
//# sourceMappingURL=/Users/hansl/Sources/angular/dist/packages-dist/compiler/bundles/compiler.umd.min.js.map
```

**Comment by ova2** [comment]
I got a similar issue:

DevTools failed to parse SourceMap: http://127.0.0.1:8080/Users/hansl/Sources/angular/dist/packages-dist/compiler/bundles/compiler.umd.min.js.map

After looking in compiler.umd.min.js I saw:

**//# sourceMappingURL=/Users/hansl/Sources/angular/dist/packages-dist/compiler/bundles/compiler.umd.min.js.map**

This is wrong. The path is relativ in other *.umd.js files.

**Comment by rallets** [comment]
Same for me. This break my build process. I'm waiting this fix to be able to upgrade my app from angular 2.x to 4.x

**Comment by hong-hu** [comment]
It is a bit annoying. 
Confirmed this bug still exists in Angular 4.0.2, but with a different path:
GET /Users/hansl/Sources/angular/dist/packages-dist/compiler/bundles/compiler.umd.min.js.map 404 0.892 ms - 100

**Comment by pe8ter** [comment]
Confirmed this bug still exists in Angular 4.0.3, but with a different path:

```javascript
//# sourceMappingURL=/usr/local/google/home/misko/angular/dist/packages-dist/compiler/bundles/compiler.umd.min.js.map
```

**Comment by rallets** [comment]
I hope someone will take a look to this. I don't understand why a fix is not already available. I consider this bug as a breaking change that will stop people to use angular (like me). 
How I could help to fix this?

**Comment by pe8ter** [comment]
Confirmed this bug still exists in Angular 4.1.0.

**Comment by pe8ter** [comment]
Confirmed this bug still exists in Angular 4.1.1, but with a different path:

```
//# sourceMappingURL=/Users/matsko/code/angular/dist/packages-dist/compiler/bundles/compiler.umd.min.js.map
```

**Comment by pe8ter** [comment]
Confirmed this bug still exists in Angular 4.1.2, but with a different path:

```
//# sourceMappingURL=/Users/jasonaden/Projects/angular/dist/packages-dist/compiler/bundles/compiler.umd.min.js.map
```

**Comment by pe8ter** [comment]
Confirmed this bug still exists in Angular 4.1.3.

**Comment by pe8ter** [comment]
Confirmed this bug still exists in Angular 4.2.1.

**Comment by pe8ter** [comment]
Confirmed this bug still exists in Angular 4.2.2.

**Comment by lewis-as** [comment]
Confirmed bug still exists in Angular 4.4.4

**Comment by elliot-xu** [comment]
Confirmed bug still exists in Angular 5, but name has been changed to matsko.

**Comment by IgorMinar** [comment]
I can still repro this with 5.1.2 see the end of:

- https://unpkg.com/@angular/core@5.1.2/bundles/core.umd.min.js
- https://unpkg.com/@angular/compiler@5.1.2/bundles/compiler.umd.min.js

**Comment by IgorMinar** [comment]
I sent out a fix for this. See #21147
