### ISSUE TITLE
Angular 4 is slower and bigger file size than Angular 2

### ISSUE THREAD

**Issue by cheerun** [angular/angular#15748]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

https://github.com/krausest/js-framework-benchmark/issues/154
He said Angular 4 is slower and bigger file size than Angular 2.
krausest is JavaScript framework benchmarker and his result is famous at vue.js communities.
Please Help for reviewing his code.

**Expected behavior**

Angular 4 is faster and smaller than Angular 2

**Minimal reproduction of the problem with instructions**

look this repo, https://github.com/krausest/js-framework-benchmark

**What is the motivation / use case for changing the behavior?**

Above repo explains well for running benchmark.

**Please tell us about your environment:**

Not related.

* **Angular version:** 2.0.X

4.0.0 and 2.4.9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Not related.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2.2

* **Node (for AoT issues):** `node --version` =   
I don't know.

**Comment by cheerun** [comment]
![screen shot 2017-04-04 at 4 27 51 pm](https://cloud.githubusercontent.com/assets/20786586/24645584/b1340a38-1953-11e7-99f7-797457c3405c.png)
You can confirm the result at https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/table.html

**Comment by trotyl** [comment]
As per [Design doc](https://docs.google.com/document/d/195L4WaDSoI_kkW094LlShH6gT3B7K1GZpSBnnLkQR-g/preview), the View Engine do have **slower** performance than original "fully" compiled templates, it's expected.

For the size part, the **generated code** size is smaller than the original 2.x, not the runtime size (as there're new features and deprecated features), the benefits in total cannot be observed in a single-component app.

**Comment by tbosch** [comment]
Hello,
yes, with the new view engine we expected a slight decrease in performance for simple applications. However, for bigger applications we should not have regressed.

Closing this issue as not actionable.
