### ISSUE TITLE
Angular 4.0 Platform Server Ability to Set Title and Meta Tags

### ISSUE THREAD

**Issue by thinkadi** [angular/angular#15742]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The new Angular 4.0 version does not have ability to set Title and Meta Tags on the server platform. The feature is only available on the browser platform.

**Expected behavior**
Allow setting the title and meta tags on the server platform (as part of platform-server module.

**Minimal reproduction of the problem with instructions**
This is not a bug

**What is the motivation / use case for changing the behavior?**
When users, search engines and page preview generators reach a page other than home page on my site, I want to be able to set the title and meta tags that is appropriate. Right now the page title and meta tags are constant no matter the page viewed. The feature is currently only available as part of platform-browser which only executes on the client side.

**Please tell us about your environment:**
NodeJS, ExpressJS, AWS Beanstalk with Linux

* **Angular version:** 2.0.X
Angular 4.0

* **Browser:** all
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   6.10.0

**Comment by DzmitryShylovich** [comment]
There're `Title` and `Meta` services for this use case.

**Comment by thinkadi** [comment]
Thanks for your response. But based on the API reference documentation on angular.io, the Title and Meta and services are only available as part of the platform-browser module which means they can be executed only on the browser, right? I am looking for a similar functionality that I can execute on the server (platform-server). Please advise. Thanks!

**Comment by DzmitryShylovich** [comment]
> the Title and Meta and services are only available as part of the platform-browser module which means they can be executed only on the browser, right?

nope, they will work on both platforms

**Comment by thinkadi** [comment]
Oh really? Ok thanks... let me try and I will post a comment about the results.

**Comment by thinkadi** [comment]
Thank you DzmitryShlovich... it worked as you said. The only thing though is that I had to use platform-browser module for my server side rendering. I'm just surprised and a little uncomfortable using platform-browser module for both browser and server rendering. It might be better to keep them separate. But, thanks for your help.

**Comment by DzmitryShylovich** [comment]
There was a plan to move all these classes into `common` module, but I don't now what is the current status.

cc @alxhub @vikerman

**Comment by thinkadi** [comment]
Oh ok that makes sense... Thanks for your input. Appreciate it.

**Comment by fulls1z3** [comment]
Although Title and Meta services are located under the `platform-browser` package, they avoid direct manipulation of DOM, by depending on DomAdapter and they work great with server-side rendering as well as client-side rendering.

Awesome job @DzmitryShylovich 👍
