### ISSUE TITLE
Validator.pattern does not work with a Regular Expression

### ISSUE THREAD

**Issue by sylvainpolletvillard** [angular/angular#15751]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When passing a RegExp to an input `[pattern]` attribute, Angular is calling regex.toString() and pass the result to the pattern attribute. `/[a-z]/.toString() === "/[a-z]/"` so we get `pattern="/[a-z]/"` in the output

**Expected behavior**

The input pattern attribute receives a regular expression without the `/` characters around it. The expected value of the pattern is `[a-z]` and not `/[a-z]/`. As a consequence, the validation does not work as intended as shown in the example.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/ky7ixixrm4hRV0Ufg39Z?p=preview

**What is the motivation / use case for changing the behavior?**

fix pattern validation using regexp

**Please tell us about your environment:** Windows 10

* **Angular version:** 2.4.9

* **Browser:** Chrome 57

 
* **Language:** ES6+

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pattern validator selector is
```
selector: '[pattern][formControlName],[pattern][formControl],[pattern][ngModel]',
```
http://plnkr.co/edit/uEZ4MNmpI3IZLKt8jtx5?p=preview
Please read documentation before submitting new issues. Thanks.

**Comment by sylvainpolletvillard** [comment]
I read it but it did not make any sense at all to me

**Comment by sylvainpolletvillard** [comment]
It looks like you change the styles to `.ng-valid` and `.ng-invalid` but regarding the HTML5 specification, the field is still invalid: http://plnkr.co/edit/v58lkhdgyHOVuMniAUnd?p=preview

**Comment by MartinMuzatko** [comment]
Related: #20241

**Comment by mhevery** [comment]
This works as intended. Angular simply takes your regexp and assigns it to the `pattern` property of the `input` it is `input` which than does `toString` on it.
