### ISSUE TITLE
Lifecycle hooks inheritance not working in production

### ISSUE THREAD

**Issue by dmitrysteblyuk** [angular/angular#15756]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If some component extends a class that implements lifecycle hooks, then methods of super class (ngOnInit, ngAfterViewInit etc) are not being called. Event though they exist on component instance.

**Expected behavior**
Inherited lifecycles hooks should be called.

**Minimal reproduction of the problem with instructions**
This issue happens only when building in production mode (I'm using for that @angular/cli 4.0.1).
```
import { Component, OnInit } from '@angular/core';

class Foo implements OnInit {
    ngOnInit() {
        alert('Foo initialized');
    }
}

@Component({
    selector: 'app-root',
    template: 'App works',
})
export class AppComponent extends Foo {}
```

**What is the motivation / use case for changing the behavior?**
Now to fix this, one has to add manually ngOnInit on the component:
```
@Component({
    selector: 'app-root',
    template: 'App works',
})
export class AppComponent extends Foo {
    ngOnInit() {
        super.ngOnInit();
    }
}
```

**Please tell us about your environment:**
Windows 10, Sublime text, angular-cli

* **Angular version:** 4.0.1

* **Browser:** Chrome
 
* **Language:** Typescript 2.2.2

* **Node (for AoT issues):** `node --version` =   7.8.0

**Comment by DzmitryShylovich** [comment]
Please fill out the issue template and format the code.

> I have no idea why code blocks are displayed in such way or how to fix it

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by dmitrysteblyuk** [comment]
@DzmitryShylovich done, thank you!

**Comment by DzmitryShylovich** [comment]
I believe it was fixed by https://github.com/angular/angular/pull/15583 but the fix hasn't been released yet

**Comment by vicb** [comment]
The fix will be part of the next release
