### ISSUE TITLE
docs: API - EventEmitter API should say whether `isAsync` is `true` or `false` by default

### ISSUE THREAD

**Issue by zoechi** [angular/angular#15758]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

https://angular.io/docs/ts/latest/api/core/index/EventEmitter-class.html

doesn't provide any info about the default behavior when `isAsync` isn't passed.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jenniferfell** [comment]
Thanks. This is fixed in v6 RC: https://next.angular.io/api/core/EventEmitter
The markup for the parameter description was added to the source by PR #15780, but the description wasn't displaying on the page until the API template changes were made for v6.
