### ISSUE TITLE
App freezes when using router.NavigateByUrl in resolver 

### ISSUE THREAD

**Issue by dajxr8** [angular/angular#15766]
**I'm submitting a ...** 
```
[x] bug report 
[ ] feature request
[ ] support request => 
```

**Current behavior**

Using router.navigateByUrl inside an observable .catch() freezes the whole app preventing the user from navigating and nothing appears in the console logs.
(API call from a resolver )

And I want to add that on one of my old project ( router version 3.0.0 ) the router.navigateByUrl works as expected. So I can't really tell when the bug appeared.

**Expected behavior**
For example I should be able to get a user from the API using http, if the request returns 404,  .catch() catches the error and redirects to '/404' with router.navigateByUrl.

**Minimal reproduction of the problem with instructions**
Here is the plunker : https://plnkr.co/edit/LVramgMcquvxfA9bosUg?p=preview

You can click on one of the two users, go back and click on the other, works as expected as long as it doesn't return a 404.
But whenever you click on "404 Here and freeze" it calls the API, returns 404 and it just freezes and you can't navigate anymore, nothing appears in the console.

1st page is the HomeComponent, the 2nd is the DetailComponent.
API calls are made from the TestService and the call that triggers the freeze is in the DetailResolver.

**What is the motivation / use case for changing the behavior?**

I want to be able to redirect a user to a 404 route if the API call returns 404.

**Please tell us about your environment:**

The bug happens on my computer ( Windows 10 / Visual Studio Code / NodeJS )
But it does not really matter as it also happens on plunker.

* **Angular version:** 4.0

* **Browser:** [all]
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` = 7.4.0

**Comment by DzmitryShylovich** [comment]
you must return an observable from `catch`:
```
.catch((err) => {
      this.router.navigateByUrl("/dashboard");
      return Observable.of(null);
      })
```
https://plnkr.co/edit/6A5HFeO0PbZ88gLyNnYp?p=preview
