### ISSUE TITLE
Forms don't support multi checkboxes by default

### ISSUE THREAD

**Issue by gregordotjs** [angular/angular#15765]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Neither template forms nor reactive forms support multi checkboxes by default (see the example: https://plnkr.co/edit/gQShPEDr09AEwq1dlBzl?p=preview). 

The odd thing is, if defining "select" element with "multiple" attribute, the array is created, as evident from the example: https://plnkr.co/edit/aYcjvjXLWRBaaobNM6mf?p=preview

**Expected behavior**

Without the bug, multi checkboxes would behave like "select" element with "multiple" attribute, as described above: https://plnkr.co/edit/aYcjvjXLWRBaaobNM6mf?p=preview

**Minimal reproduction of the problem with instructions**

The example of how multi checkboxes don't behave as expected: https://plnkr.co/edit/gQShPEDr09AEwq1dlBzl?p=preview

**What is the motivation / use case for changing the behavior?**

The motivation is that the developer wouldn't have to perform a workaround to get this very basic feature. Here's my example of a workaround: https://plnkr.co/edit/NrJJ6iyiHwVimyGNqqVX

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.X

Angular 4, the issue is present in Angular 2.0.X as well.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript version 2.1.6

* **Node (for AoT issues):** `node --version` =   
Node v6.9.4

**Comment by DzmitryShylovich** [comment]
have you tried `FormArray`?

**Comment by javascrewpt** [comment]
yes, as described, my workaround uses `FormArray`, but that's still a workaround (see here: https://plnkr.co/edit/NrJJ6iyiHwVimyGNqqVX?p=info ). Multi checkboxes should work out-of-the-box, since it's not an advanced feature and is used quite often for most of the basic cases. Again, as described, the behavior should mimic the `select` element with `multiple` attribute, as evident here: https://plnkr.co/edit/aYcjvjXLWRBaaobNM6mf?p=preview
