### ISSUE TITLE
The Request constructor doesn't respect the deprecated RequestOptionsArgs.search property

### ISSUE THREAD

**Issue by hristokostov** [angular/angular#15761]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When creating a new instance of the `Request` class, the value of the `search` property of the `RequestOptionsArgs` object that is passed to the constructor is not respected, i.e. the `Request` instance has no query parameters. If we use the new `params` property, query parameters are properly set.

**Expected behavior**
It is expected the now deprecated property to works too.

**Minimal reproduction of the problem with instructions**
Here is the plunk: https://plnkr.co/edit/udWvbiYOwLzx29F974jK

* **Angular version:** 4.0.X

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/15666#issuecomment-290730388

**Comment by hristokostov** [comment]
Thanks for the quick reply.

OK, but how could anyone know that the `RequestOptions` class exists and have to be used? The `Request` constructor signature expects `RequestOptionsArgs` and the [documentation](https://angular.io/docs/ts/latest/api/http/index/Request-class.html) example is like this:

```
 return this.http.request(new Request({
      method: RequestMethod.Get,
      url: url,
      search: 'password=123'
    }));
```

Today I updated to v4 and my app just broke.

>Request wasn't designed to work with RequestOptionsArgs directly.

You mean "was never designed to work with RequestOptionsArgs" or that it was redesigned in the v4 phase? Because I believe the signature/documentation has always been like it is now.

**Comment by DzmitryShylovich** [comment]
`RequestOptions` doesn't implement `RequestOptionsArgs`. There's no a single test that uses `RequestOptionsArgs`. There're a lot of inconsistencies. In 4.1 http module will be rewritten and I hope all these issues will fixed.

Right now you have 2 options:
1. use `RequestOptionsArgs` with `search`
2. use `RequestOptions` with `params`

**Comment by hristokostov** [comment]
Currently option 1 (passing `RequestOptionsArgs` with `search`) is not working. In order to fix my app I just switched from `search` to `params`.

`RequestOptions` with `search` is fine (as you have pointed in the 15666 comment).
