### ISSUE TITLE
aio: Suggestion for side nav revisions

### ISSUE THREAD

**Issue by ghost** [angular/angular#15774]
I took a look at the new docs site navigation:

https://aio-staging.firebaseapp.com/docs

The navigation should be changed in a similar way described here (for the old site) :

angular/angular.io#3500

The resulting menu would be something(!) like this (the order/content is relevant, not so much the naming):

* **Docs Home**
* **Quick Start** (the current Cli Quickstart, simplified, see angular/angular.io#3497)
* **Entry Tutorial** (the current Tutorial, simplified, see angular/angular.io#3492)
* **Beginner Guide** (or "Basic Guide", the current "GETTING STARTED")
  * Intro (the current "quickstart")
* **Core Architecture** (possibly with a diagram, which shows Angular Subsystems)
* **Advanced Concepts** (current ADDITIONAL TECHNIQUES)
* **API**
* **References**

An expert sees it, click directly "Core Architecture" and "Advanced Concepts". A beginner goes shyly to "Quick Start" and "Entry Tutorial" and of course "Beginner Guide".

Nice, compact and self-explaining, with the level of expertise increasing top-to-bottom.

**Comment by wardbell** [comment]
Changed PR title to make clear that this issue asks for changes in the side nav item content (an 
(aio" concern ), not in the doc content ( a "docs" concern). Thus the "aio" label rather than "docs" label.

**Comment by petebacondarwin** [comment]
The `aio` label is for the underlying application and docs-generation.
Changes to the data that is display (including navigation items) should have `docs` label.

**Comment by jenniferfell** [comment]
Thanks. We've been looking at the side navigation. Your thoughts are helpful.

**Comment by jelbourn** [comment]
We've updated the nav a bit over the years, closing this as obsolete.
