### ISSUE TITLE
Spelling mistake in the Angular 2 Tutorial 

### ISSUE THREAD

**Issue by 1david1** [angular/angular#15787]
![angulartutorialspellingfix](https://cloud.githubusercontent.com/assets/17274162/24704342/e8040c2c-1a0f-11e7-9bc5-53f839e9198a.png)

**Comment by DzmitryShylovich** [comment]
Please report docs issues on https://github.com/angular/angular.io/issues

**Comment by Foxandxss** [comment]
This got fixed long ago.
