### ISSUE TITLE
Don't work in IOS8.1.2 safari but new IOS version work

### ISSUE THREAD

**Issue by suplch** [angular/angular#15783]
I create an angular application by angular-cli tool. this application don't work in iOS 8.1.2 safari, but other high iOS version can work.
Is there a bug in iOS 8.1.2

**Current behavior**
angular2 application doesn't work in iOS 8.1.2 safari, but in other version iOS can work.
```html
<app-root>
        load...
</app-root>
```
In iOS 8.1.2, The text "load..." display in safari browser forever, app don't launch, but In other iOS version, it can work well.
**Expected behavior**
Expected work with iOS8.1.2 safari
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Hoping the app can work, compatible old iOS version
**Please tell us about your environment:**
@angular/cli: 1.0.0
node: 7.0.0
os: darwin x64

* **Angular version:** 2.4.10

* **Browser:** [iOS 8.1.2 Safari ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0

* **Node (for AoT issues):** `node --version` =   
node: 7.0.0

**Comment by DzmitryShylovich** [comment]
https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by tbosch** [comment]
Hello,
we need:
- exact steps on how to reproduce
- the error that you are getting (you can use ios remote debugging to look at the browser console).

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
