### ISSUE TITLE
Router 4.01 - throwing error on resolve() promise -- ngNavigationCancelingError

### ISSUE THREAD

**Issue by ganySA** [angular/angular#15782]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have upgraded to angluar router 4.01. I have an ActivateRouteGuard which was working correctly prior to upgrading.

**Expected behavior**

**Minimal reproduction of the problem with instructions**
```
@Injectable()
export class CanActivateAuthAdminGuard implements Resolve<any> { 

    constructor() {
    }
    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Promise<Boolean> {
        console.log("running resolver");
        return new Promise((resolve, reject) => {
            resolve();
        });
    }
}
```
Throws the following error:

> Error: Uncaught (in promise): TypeError: Cannot read property 'ngNavigationCancelingError' of undefined TypeError: Cannot read property 'ngNavigationCancelingError' of undefined at isNavigationCancelingError 

* **Angular version:** 2.0.X
Angular 4.01
Angular Router 4.01

**Comment by DzmitryShylovich** [comment]
Please provide a plunkr

**Comment by ganySA** [comment]
Hi 

I have debugged this. The issue is that in previous versions you could call resolve() without specifying true or false and it would still work.

Now resolve(true) or resolve(false) must be specified.

**Comment by DzmitryShylovich** [comment]
Can't reproduce http://plnkr.co/edit/rmyzhlVwmbsWHR3Gcmlj?p=preview

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by juanpablodelatorre** [comment]
Here's a plunkr that reproduces the error with a `CanActivateChild` guard:
http://plnkr.co/edit/NdjKz0bAbwHPklrjB7CA
