### ISSUE TITLE
Travis build will fail when using personal travis account

### ISSUE THREAD

**Issue by JiaLiPassion** [angular/angular#15785]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When commit to forked angular repository, I also want to run all ci test with my travis account, but it will fail because scripts/ci/env.sh has some hardcode settings.

**Expected behavior**

I can run ci test with my travis account.
**Minimal reproduction of the problem with instructions**

here is error travis log.
https://travis-ci.org/JiaLiPassion/angular/builds/218714468

**What is the motivation / use case for changing the behavior?**

want to run ci test on my forked repository.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular latest 4.1.0-beta.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by IgorMinar** [comment]
I don't think that we can make this work because you'll need auth tokens for various services like saucelabs, etc and you won't have those available.

What's your goal with running the CI on a fork?

**Comment by vicb** [comment]
Closing as no feedback/important use case
