### ISSUE TITLE
Secondary (auxiliary) routes throw exception

### ISSUE THREAD

**Issue by darren-temenos** [angular/angular#15781]
**I'm submitting a**
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using a routerLink to a secondary route with a named router outlet an exception is thrown.

```
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '%5B%20%7B%20outlets%3A%20%7B%20testing%3A%20'test'%20%7D%20%7D%20%5D'
Error: Cannot match any routes. URL Segment: '%5B%20%7B%20outlets%3A%20%7B%20testing%3A%20'test'%20%7D%20%7D%20%5D'
```

**Expected behavior**

Upon navigating to the secondary route, the specified component to be inserted into the DOM after the named router outlet.

**Minimal reproduction of the problem with instructions**

In app.module.ts
```
...
import { TestComponent } from './test/test.component';
...
declarations: [TestComponent]
...
```

In app-routing.module.ts:

```
...
import { TestComponent } from './test/test.component';
...
{
    path: 'test',
    component: TestComponent,
    outlet: 'testing'
  }
...
```

In app.component.html:

```
...
<a routerLink="[ { outlets: { testing: 'test' } } ]">Test</a>
<router-outlet name="testing"></router-outlet>
<router-outlet></router-outlet>
...
```

**What is the motivation / use case for changing the behavior?**

To work as understood or to understand mistake.

**Please tell us about your environment:**

* **Angular version:**

Angular 4.0.1 and initial setup by Angular CLI 1.0.0

* **Browser:**
 
Chrome 57.0.2987.133

* **Language:**

TypeScript 2.2.2

* **Node (for AoT issues):** 

NodeJS 7.7.4

**Comment by DzmitryShylovich** [comment]
Please provide a small plunkr that reproduces the issue

**Comment by darren-temenos** [comment]
http://plnkr.co/edit/cc6DA4whd933VLcuId4S

**Comment by darren-temenos** [comment]
A mistake.

RouterLink was:

```
<a routerLink="[ { outlets: { testing: 'test' } } ]">Test</a>
```

Should have been:

```
<a [routerLink]="[ { outlets: { testing: 'test' } } ]">Test</a>
```

Closing.
