### ISSUE TITLE
aio: rewrite rules to redirect old links to new doc-viewer pages

### ISSUE THREAD

**Issue by wardbell** [angular/angular#15795]

**Comment by petebacondarwin** [comment]
This might be a good thing for @gkalpak to work on?

**Comment by gkalpak** [comment]
For reference, here are the redirect rules/patterns: https://gist.github.com/Foxandxss/92bc50d2d4a66981bdaab1025d769aba

**Comment by gkalpak** [comment]
For reference: We also need to redirect `docs/ts/latest/glossary` to `guide/glossary` and cookbooks (see https://github.com/angular/angular/pull/16133#discussion_r112157727).
