### ISSUE TITLE
how to store information from http and be used everywhere

### ISSUE THREAD

**Issue by BlankHrt** [angular/angular#15799]
i use behaviorSubject to observe user information like this:

 user = new BehaviorSubject({});
login(params): Observable<any> {
        return this.http.post(this.HttpUrl + '/auth/login', {'username': params.username, 'password': params.password})
            .map((params) => this.extractData(params))
            .catch(this.handleError);
    }
extractData(res: Response) {
        let body;
        if (res.text()) {
            body = res.json();
            try {
                this.storage.store('isLogin', true);
                this.storage.store('token', body.token);
                this.user.next(body);
            } catch (e) {
                console.log(e);
            } finally {
                return body || null;
            }
        }
    }
and when i login, i use asObservable().subscribe()
i get{}  not the information i get from http
thank you

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
