### ISSUE TITLE
Angular4 doesnt support html5 validation anymore

### ISSUE THREAD

**Issue by rudolfschmidt** [angular/angular#15797]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After upgrading from angular2 to angular4 I have noticed that my reactive Forms do not use html5 validation like before with Angular2.

**Expected behavior**
If I click a button with type "submit" inside a form with a field with attribute required, you should be asked to enter any value when submitting.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/F5fsJLdlvEDdmSODpnig?p=info

**What is the motivation / use case for changing the behavior?**
The motivation is to be able still use the html5 validation combined with reactiveForms. It makes sense because the notification that you get from the browser using html5 validation are good enough for most use cases. Otherwise you would be forced to create your own validation notification like "field value is required" that is double work.

**Please tell us about your environment:**
Chromium., Angular4, Linux, Webpack Dev Server

**Comment by bigjetplane** [comment]
See https://github.com/angular/angular/issues/15531#issuecomment-289555359

**Comment by rudolfschmidt** [comment]
thank you, My feedback, change it back. Dont see any benefit to disable html5 validation. If you want to disable it, you have novalidate already.

**Comment by bigjetplane** [comment]
> Dont see any benefit to disable html5 validation

it's a very common use case. most of the people disable validation so we made it simpler for them.

**Comment by mlc-mlapis** [comment]
@rudolfschmidt If you want to consistent and predictable validation system I think that you have to cover all cases in your app so then you have to have your own solution because it is better to have the same logic without any exceptions, especially when you use `live`  validation rules. HTML5 validation is fine but probably not for advanced Angular apps. I'm sorry.

**Comment by cortopy** [comment]
I think it's wrong to make decisions based on what developers should want. It gets very closed to being patronising.

I was using HTML5 validation in an extremely simple form within an angular app. This app needs to be developed fast and simple. i agree angular validation is better to cover all use cases, but HTML5 validation was created for the very case of simplicity and speed in development!!

The app was working fine in angular 2, now that it has been upgraded to angular 4 validation doesn't work any more. 

Something like:

```html
<input type="text" ngModel name="name" required id="name"
              placeholder="Name" oninvalid="this.setCustomValidity('Please write the new user\'s name')" oninput="setCustomValidity('')">
```

used to display validation messages nice and easily in angular 2. 

I don't understand why in Angular 4 it is forbidden to use HTML validation

**Comment by kara** [comment]
As @bigjetplane mentioned, this is working as expected to support the most common use cases. If you want to turn native validation back on, this is possible with `ngNativeValidate`.

**Comment by puneetkankar** [comment]
use like this code 

<form [formGroup]="form" ngNativeValidate (ngSubmit)="onSubmit(form.value)" novalidate>

 <input type="text" name="name" required id="name"/>
   <input type="submit" value="SAVE"   > 
               
</form>

**Comment by Halfist** [comment]
I'm a little bit confused. Since Angular 4+ automatically adds `novalidate` to `<form>`, why then official guide [cautions](https://angular.io/guide/reactive-forms#step-2-making-a-field-required) us to use `required` etc. in combination with the Angular's built-in validators? Does `required` work with `novalidate`? Doesn't Angular 7 automatically add `novalidate` anymore? Is an official guide outdated?

**Comment by hanct** [comment]
> I'm a little bit confused. Since Angular 4+ automatically adds `novalidate` to `<form>`, why then official guide [cautions](https://angular.io/guide/reactive-forms#step-2-making-a-field-required) us to use `required` etc. in combination with the Angular's built-in validators? Does `required` work with `novalidate`? Doesn't Angular 7 automatically add `novalidate` anymore? Is an official guide outdated?

II try an online angular editor, and observe that Angular 7 seems NOT to add 'novalidate' by default. This means that we no need to do anything to do native browser validation. Maybe that explain the official "cautious" guide.

Hence can we add an assurance that Angular now by default does not add 'novalidate' . If that is the case, no need to explicit indicate ngNativeValidate anymore to do browser validation

**Comment by caiges** [comment]
Heh, @Halfist I just noticed this as well. It is confusing reading the recommendation in the docs when by default forms have `novalidate` set.
