### ISSUE TITLE
FormsModule blocks Html5 form validation

### ISSUE THREAD

**Issue by szavoda** [angular/angular#15796]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

A form that imports FormsModule will not validate using Html5 validation.  Example of issue:[http://plnkr.co/edit/1sKo4ORDty141wpTkJcY?p=preview](url)

**Expected behavior**

All forms should be able to use Html5 validation.  As far as I know, this worked in previous versions - at least back in 2.x.  Working plunker omitting FormsModule: [http://plnkr.co/edit/bG8EuWTEDDrWA49XUReU](url)

* **Angular version:** 2.0.X
Angular 4.0.1

* **Browser:** 
Chome v57

**Comment by bigjetplane** [comment]
See https://github.com/angular/angular/issues/15531#issuecomment-289555359

**Comment by szavoda** [comment]
Thanks for the quick help!  Hours of hunting finally solved...
