### ISSUE TITLE
QueryList in Dart needs to be package:observe.ObservableList

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1580]

**Comment by devanp92** [comment]
@mhevery Can you elaborate on the issue? Do you either want:

* A Base Query List as proposed in [#1368](https://github.com/angular/angular/issues/1368)
* Or replace the [QueryList](https://github.com/angular/angular/blob/fd0ba37734f1df3455346bb47df85c55d479d679/modules/angular2/src/core/linker/query_list.dart)'s imports with "import 'package:observe/observe.dart' show ObservableList;"

**Comment by mhevery** [comment]
Will not implement.
