### ISSUE TITLE
ng4 canLoad triggered twice when redirecting back to current page

### ISSUE THREAD

**Issue by gedclack** [angular/angular#15802]
**I'm submitting a ...**
```
[x ] bug report
```

**Current behavior**
canLoad guard called twice when fails to navigate to target route from current page.

**Expected behavior**
I think it should be only called once.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/Rj5hXJRlluFmEk656kIT?p=preview
I rechecked, It does not happen when we navigate via a link (routerLink).
to reproduce : 
1. from current page "x.com/#/login"
2. change the url by typing directly into the address bar to "x.com/#/dashboard"
*I think it has a relation with my `dashboard-routing.module.ts` which has 2 empty routes (see plunker)

**What is the motivation / use case for changing the behavior?**
**When the user is on Login Page**, I want to prevent the user from navigating to other routes before logged in.
But when the user opens a new tab and enter this address `x.com/#/dashboard/`, canLoad works OK (only triggered once).

**Please tell us about your environment:**
Win7 64bit, VSCode, node.js npm, apache

* **Angular version:** 4.0.X

* **Browser:** Chrome XX
 
* **Language:** TypeScript 2.X

**Comment by zoechi** [comment]
A plunker that demonstrates the issue is required.

**Comment by adrienboulle** [comment]
I could not reproduce it:
http://plnkr.co/edit/uytY0qrmr1soeoiWrTbg?p=preview

**Comment by gedclack** [comment]
*added plunker.
I can't get it to run in plunker but please check the link

**Comment by Toxicable** [comment]
@gedclack  How is your plunkr reproducing it? I only ever see it called once

**Comment by gedclack** [comment]
@Toxicable I don't think that plunkr can reproduce it, it must be typed directly from address bar.
to reproduce :
1. from current page "x.com/#/login"
2. change the url by typing directly into the address bar to "x.com/#/dashboard"
*I think it has a relation with my dashboard-routing.module.ts which has 2 empty routes (see plunker)

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by gedclack** [comment]
related to #16211
