### ISSUE TITLE
Angular can't recieve cookies

### ISSUE THREAD

**Issue by amineparis** [angular/angular#15804]
I have two projects (SPA) using two different ports (front: 4200, Back : 8000):

* **Project 1:** 
 * *Front :* Angular 1
 * *Back :* Django / Django-rest-framework.
* **Project 2:** 
 * *Front :* Angular 2+
 * *Back :* Django / Django-rest-framework.

The problem I am facing **(only)** with project 2 *(3 days trying to solve it)* is that Angular 2+ can't receive cookies sent by the back.

***Additional information :*** 

* Project 1 => cookies received **OK**
* Project 2 => no cookies **Problem**
* Back of project 1 with front of project 2 => no cookies **Problem**
* Back of project 2 with front of project 1 => cookies received **OK**
* withCredentials is configured in both projects.
* cors configured for both projects.
* Response for both projects contains set-cookie header attribute.

**Comment by tbosch** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by tbosch** [comment]
This is probably a duplication of #15805

**Comment by Juansasa** [comment]
Could it be that Webpack server from Angular-cli set Access-Control-Allow-Origin to '*' which is not a valid value for cookies to be set on client. ?

**Comment by amineparis** [comment]
the exact issue is Angular is ignoring withCredentials: true

**Comment by souravmondal93** [comment]
@amineparis Did you get any solution for this problem? I think I am also facing the same problem.

**Comment by trotyl** [comment]
@souravmondal93 I guess you could help to provide a reproduction then.

**Comment by amineparis** [comment]
**one additional information that may help you to help us :** in production environnent the problem doesn't occure since I use same somain.

**Comment by ericmdantas** [comment]
@Juansasa if that's the case, keep in mind that the header `Access-Control-Allow-Origin: *` doesn't work with `With-Credentials: true`. See [the explanation in developer.mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Credentialed_requests_and_wildcards). 

This makes the problem part of the dev server, not Angular.
