### ISSUE TITLE
[ng-template] compiler generate code that does not use typechecking

### ISSUE THREAD

**Issue by Delagen** [angular/angular#15801]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ngc compiler generate code for component as
```
var co:any = v.component;
```
No template typecheck when compiling

**Expected behavior**
ngc compiler generate code for component as
```
var co:ComponentType = v.component;
```
or something that throw error when in code used something that does not exists on ComponentType

**Minimal reproduction of the problem with instructions**
- run ngc
- look at generated ngfactory code

**Please tell us about your environment:**
Windows 10

* **Angular version:** 4.0.1

* **Language:** Typescript 2.2.2

* **Node (for AoT issues):** `node --version` =   7.8.0

**Comment by Toxicable** [comment]
can you make an example repo for us to investigate this issue.
What is your reasoning for wanting this change? you never touch the ngc files so why do Types matter?

**Comment by Delagen** [comment]
Found issue. It only applied when compiling `ng-template`
this component code does not find any issues.
```html
<h1>
  {{title}}
  <ng-template #tt>
    {{notExistTitle}}
  </ng-template>

  <ng-template [ngTemplateOutlet]="tt"></ng-template>
</h1>
```

**Comment by Delagen** [comment]
Any news?

**Comment by JoostK** [comment]
In Ivy, there's 100% customized codegen logic for the sole purpose of template type checking. This means that templates can be checked regardless of the generated code for runtime execution. As such, this issue has become obsolete and the showcased problem is no longer an issue with Ivy's template type checker.
