### ISSUE TITLE
Angular 4: ngFor is not typesafe anymore (AoT)

### ISSUE THREAD

**Issue by kondi** [angular/angular#15809]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the new view engine `ngFor` variables are typed as `any`, so type errors do not brake the build anymore.

**Expected behavior**
The variable introduced by `ngFor` directive should have the type of the array items.

**Minimal reproduction of the problem with instructions**
```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <div *ngFor="let user of users">
      {{user.name}}
      <!-- The next line refers to a missing member of user, should generate compile error -->
      {{user.missing}}
    </div>
  `
})
export class AppComponent {
  users = [{ name: 'username' }];
}
```
**What is the motivation / use case for changing the behavior?**
The biggest advantage of AoT is the ability to write typesafe templates. It should work even if you use ngFor, it is a very common directive.

**Please tell us about your environment:**

* **Angular version:** 4.0.1, 4.1.0-beta.0

* **First broken angular version:** 4.0.0-beta.8
* **Last working angular version:** 4.0.0-beta.7

* **Browser:** all
 
* **Language:** TypeScript 2.2

* **Node (for AoT issues):** `node --version` =   v7.4.0

**Comment by kondi** [comment]
Fixing this would be very useful for the @angular/language-service as well.


Angular 2.4, content assist:
![content-assist](https://cloud.githubusercontent.com/assets/278688/24758799/b46cb966-1ae3-11e7-8e10-106d243d4fd2.png)


Angular 2.4, error checking:
![angular2](https://cloud.githubusercontent.com/assets/278688/24758759/9e45b0b6-1ae3-11e7-9d96-d1e97371530d.png)


Angular 4.0:
![angular4](https://cloud.githubusercontent.com/assets/278688/24758784/aa77ce8c-1ae3-11e7-95fc-3be195a58b4d.png)

**Comment by Delagen** [comment]
#15801

**Comment by tbosch** [comment]
As far as I know, this has never worked. But we are aware of this issue, and are working to fix it, see  https://github.com/angular/angular/issues/12398.
