### ISSUE TITLE
an option exclude css files from imported module ?

### ISSUE THREAD

**Issue by amineparis** [angular/angular#15807]
It would be greate if we can have the possibility to exclude style from imported css files. many Angular 2 packages force users to use theire style. users don't have the ability to erase style and define their own, this enhancement enables users to do so

**Comment by textbook** [comment]
Isn't this just the same as angular/angular#15298?

**Comment by amineparis** [comment]
it's . I keep doing it until having an answer

**Comment by tbosch** [comment]
Reopened #15298, closing this one.
