### ISSUE TITLE
WARNING exported interface not found 

### ISSUE THREAD

**Issue by istiti** [angular/angular#15800]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I don't know if this is about angular compiler itself or additional warning from angular cli. I open issue here so please apologize. 

I have an exorted interface in `src/app/shared/form-utils/localized-input/localized-input.component.ts` like:
```
export interface Language {
  id: number;
  cultureName?: "fr-CH" | "de-CH";
}
```
And I import this interface inside  a component in `src/app/shared/form-utils/autocomplete/autocomplete-plan-comptable-element/autocomplete-plan-comptable-element.component.ts` I import it like this:
`import {Language, LocalizationKey} from "../../localized-input/localized-input.component";`
but when I compile (ng serve) I get warning like:
```
WARNING in ./src/app/shared/form-utils/autocomplete/autocomplete-plan-comptable-element/autocomplete-plan-comptable-element.component.ts
203:50-58 "export 'Language' was not found in '../../localized-input/localized-input.component'
```

**Minimal reproduction of the problem with instructions**
read above...

**Please tell us about your environment:**
windows10, webstorm 2017.1.1

* **Angular version:** 2.0.X
```
@angular/cli: 1.0.0
node: 7.7.2
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
```

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** 
typescript 2.2.2 (on webstorm tsc is run and it didn't get me error for this import) 

All other import are correct and same and works

**Comment by Toxicable** [comment]
Can you please make a minimal reproduction of your issue

**Comment by mlc-mlapis** [comment]
@istiti Is it the same problem as we discuss yesterday? I thought that it was explaided.

**Comment by istiti** [comment]
@mlc-mlapis import was good, I was in subsub directory normal that import was ../../../ but here im only in sub direcotry so ../../ need to be good ! 

@Toxicable how you want me make repro ? isn't it suffient current behavior you see path of my component and content 

thanks

**Comment by istiti** [comment]
@Toxicable  here you are https://cloud.githubusercontent.com/assets/2789203/24741578/cf06326c-1aa6-11e7-82a6-771b033edbc9.gif

**Comment by Toxicable** [comment]
@istiti by reproduction I mean either a plunkr or a repro that we can download and see the error ourselves in isolation, without any other code , without this it's very hard to identify what's going on.
The think you posted shows no more than what you said in your issue

**Comment by istiti** [comment]
K thanks for help

**Comment by tbosch** [comment]
Hi, sorry, but angular-cli tracks their issues in https://github.com/angular/angular-cli. Could you reopen the issue there and link it here? Thanks!
