### ISSUE TITLE
Angular2 typescript not working for IE 11

### ISSUE THREAD

**Issue by fhackenb** [angular/angular#15814]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I load my application on IE 11, it fails to load and outputs an error:

SCRIPT1002: Syntax error
main.bundle.js(7,1)

the first few lines of that file are:

 webpackJsonp([1,4],{

/***/ 140:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
class AuthCredentials {
    constructor() {
        this.password = "";
        this.email = "";
        this.role = "account-holder";
    }

with line 7 being "class AuthCredentials"
I saw a few other issues expressing problems with IE for typescript and I tried adding some scripts that supposedly addressed similar issues but they didn't appear to have any affect.

    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.33.3/es6-shim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.20/system-polyfills.js"></script>
    <script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>

**Expected behavior**
With chrome or any other browser, the app loads as expected.

**Minimal reproduction of the problem with instructions**

You can navigate to http://dev-portal.dev.funfangle.com/ on IE

**Please tell us about your environment:**

IE 11

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE is all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript es6

**Comment by Toxicable** [comment]
Could you make a minimal reproduction of your issue in plunkr or a minimal repo that we can see the issue with
Here is a plunkr template https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by tbosch** [comment]
You seem to have created an ES6 bundle (as there is a `class` statement in your source). However, IE11 does not support ES6 / the `class` statement. So you probably need to change your build pipeline to use ES5 (and the ES5 version of Angular).
