### ISSUE TITLE
Angular with XComponent is not working properly. View is not updated when using AsyncPipe

### ISSUE THREAD

**Issue by vovikdrg** [angular/angular#15819]
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using angular with XComponent is not working properly. After new value is pushed to Observable view is not updated

**Expected behavior**
Using AsyncPipe I'd expect to view always be updated

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/Bx6eGpRUKpfF3gUIRO96?p=preview
Click "Get Time Async with Async Pipe"  - View is not updated
Click "Get Time" - both values are shown

**Please tell us about your environment:**
VSCode, NPM

* **Angular version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [TypeScript ]

**Comment by tbosch** [comment]
Sorry, I don't know the xcomponent library. Please file a bug with them instead to investigate what the underlying issue is.

**Comment by vovikdrg** [comment]
@tbosch Sorry but i dont undestand why its closed? This is issue with AsyncPipe have you looked to example?

**Comment by tbosch** [comment]
@vovikdrg We need a reproduction that only involves Angular, as digging into other frameworks takes time...

I looked into this case in more detail though:
- xcomponent creates an iframe and runs angular inside of it (via `app.html`).
- The code in `app/app.component.ts` for the buttons with async behavior takes a Promise from the parent frame and passes it to angular. 
- This won't work as Angular's change detection relies on zone.js, which patches `Promise` to know when all async work is done. However, this does not work in this case, as the Promise was created in another frame.

See this modified plunker that just inlined the `getTimeAsync` function into `app/app.component.ts` and everything works fine: http://plnkr.co/edit/ircPkToDqzbBenzXsRLt?p=preview

**Comment by vovikdrg** [comment]
@tbosch My concern is only that AsyncPipe must handle it. Because what if i inject observable from outside of angular? AsyncPipe is notified by subscription that there is something new but its not updating view, this is why i am confused and posted this bug since ideas of using observables it to do not care about change detection and ngzone, since AsyncPipe must do it

**Comment by tbosch** [comment]
@vovikdrg Angular's rendering is based on change detection. I.e. even if async pipe triggers, we still rely on Angular's change detection to update the DOM. 

Note that everything works fine if you stay in the same frame, and only breaks if you create a Promise in another frame than Angular and then pass it to Angular.
