### ISSUE TITLE
Multi EventEmitter

### ISSUE THREAD

**Issue by shijilesh** [angular/angular#15816]
Dears,

i would like to know how i can use EventEmitter for multiple functions

I'm having a ButtonFrame component which has 3 buttons. i would like to trigger the same button function from parent component, its working fine for one eventemitter how i can call the second and third button function ?

i have created sample in plunker 
https://plnkr.co/edit/kaA1j1tPPKoxxlGm6wYE?p=preview

 
-->button frame
```
import { Component, EventEmitter, OnInit, Input, Output } from '@angular/core';

@Component({
    selector: 'ButtonFrame',
    template: `<button (click)="ufbAclist()">Account List</button>
               <button (click)="ufbApprove()">Approve</button> 
               <button (click)="ufbAttachments()">Attach</button>  `
})

export class ButtonFrameComponent implements OnInit {

    @Output() eufbAclist: EventEmitter<any> = new EventEmitter();
    @Output() eufbApprove: EventEmitter<any> = new EventEmitter();
    @Output() eufbAttachments: EventEmitter<any> = new EventEmitter();

    constructor() {
    }

    ngOnInit() {
    }
      
    public ufbAclist() { 
        this.eufbAclist.emit('Some value to send to the parent');
    }

    public ufbApprove() {
        this.eufbApprove.emit('Some value to send to the parent');
    }

    public ufbAttachments() {
        this.eufbAttachments.emit('Some value to send to the parent');
    }

 }

```
  parent -->Window1 
```

import { Component, EventEmitter, OnInit, Input, Output } from '@angular/core';

@Component({
    selector: 'Window1',
    template: `<ButtonFrame (eufbAclist)="ufbAclist($event)"> </ButtonFrame>`
})

export class Window1Component implements OnInit {

     
    constructor() {
    }

    ngOnInit() {
    }

     
    public ufbAclist(evt) { 
        alert("ufbAclist 2");
    }

    public ufbApprove(evt) {
     alert("ufbApprove 2");
    }

    public ufbAttachments(evt) {
     alert("ufbAttachments 2");
    }
 
}
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by fredrik-lundin** [comment]
@ericmartinezr note that the `angular` tag doesn't exist on SO. Only `angularjs` and `angular2` unfortunately..

**Comment by tbosch** [comment]
@fredrik-lundin We are working on getting it :-)
