### ISSUE TITLE
Angular2: How to access index.html querystring in App Component

### ISSUE THREAD

**Issue by Ckakkireni** [angular/angular#15810]
# Hello Firends, 

I am new to Angular2 Development.

I have a requirment where i need to call Angular2 Web site from my ASP.Net Web site. While calling Angular2 website (localhost:4200\index.html), will pass querystring like as below 
**localhost:4200\index.html?UserID=Chandra**

Now my Question is.

How to get **UserId** querystring value into **App Component (i.e. BootStrap Compoent) or any other component**.

Please help me witht this.

**Thanks in Advance.**

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by diicar** [comment]
https://angular.io/docs/ts/latest/guide/router.html#!#query-parameters

**Comment by guilhermejcgois** [comment]
I don't think that here is the correct place for your question, did you try StackOverflow? Btw [this](https://angular.io/docs/ts/latest/api/router/index/ActivatedRoute-interface.html) can help you.

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular` or [gitter](https://gitter.im/angular/angular).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
