### ISSUE TITLE
Unable to iterate through dynamic forms controls in AOT

### ISSUE THREAD

**Issue by rafiwardak2003** [angular/angular#15817]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Running development mode works fine, but when building with aot, I get "Property 'controls' does not exist on type 'AbstractControl'", which is caused by `*ngFor="let option of formGroup.get('options').controls; let i=index;"` which worked before. Wasn't sure if this was a bug or something changed.

**Expected behavior**
I should be able to use `*ngFor="let option of formGroup.get('options').controls; let i=index;"` without any issues.

**What is the motivation / use case for changing the behavior?**
When using dynamic forms, in the mark up sometimes I want to iterate through the controls and I do it this way. There's another way of declaring a property in the component and which would return an array.

* **Angular version:** 2.0.X
Angular 4

**Comment by Mnwa** [comment]
You can try to initialize a new variable for this
`let formGroup_controls = formGroup.get('options').controls;`
`*ngFor="let option of formGroup_controls; let i=index;"`

**Comment by rafiwardak2003** [comment]
Well I mentioned at the top that I can declare a property or variable in the component and do it, but I want to avoid that. What if I have 10 different arrays, declare one for each? It used to work this way already. I am not sure if it's a bug or something changed all of a sudden.

**Comment by Mnwa** [comment]
So, you can create object
`formGroup_controls = {
options: formGroup.get('options').controls,
labels: formGroup.get('labels').controls,
..etc
}`
and use it at 
`*ngFor="let option of formGroup_controls.options; let i=index;"`

Or you can use Pipes, but I'm don't sure about this.

**Comment by tbosch** [comment]
Hi,
could you double check if this only appears in AOT, and not in JIT?

And could you provide a reproduction branch somewhere / exact steps on how to reproduce?

**Comment by rafiwardak2003** [comment]
This doesn't happen in JIT. I will work on a repo to reproduce this issue. Basically it will just be a form with a form array and iterate through it in the mark up, and compile it using AOT.

**Comment by tbosch** [comment]
For AOT, a branch on Github works great as reproduction...
