### ISSUE TITLE
Testing: Location is not assignable to type SpyLocation

### ISSUE THREAD

**Issue by blackholegalaxy** [angular/angular#15815]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

I don't know exactly where to put this since it's related with examples provided in the doc of angular.io at testing section. But it seems related with framework itself.

**Current behavior**
In encounter an error when testing using `SpyLocation` type.

Error occurs:

>  src/app/app.component.router.spec.ts(144,3): Type 'Location' is not assignable to type 'SpyLocation'.
>   Property 'urlChanges' is missing in type 'Location'.

**Expected behavior**
Being able to run the example doc package about testing without error.

**Minimal reproduction of the problem with instructions**
Download the example package in Angular.io doc section about testing: [All specs that test the sample application](https://angular.io/resources/zips/testing/app-specs.testing.zip)

`npm install`

`npm run test`

**Please tell us about your environment:**
Win 10

> node --version
> v7.5.0

> npm -v
> 4.1.2

> npm ls --depth=0
> angular-io-example@1.0.0 I:\tour-heroes-testing
> +-- UNMET PEER DEPENDENCY @angular/animations@4.0.1
> +-- @angular/common@4.0.1
> +-- @angular/compiler@4.0.1
> +-- @angular/compiler-cli@4.0.1
> +-- @angular/core@4.0.1
> +-- @angular/forms@4.0.1
> +-- @angular/http@4.0.1
> +-- @angular/platform-browser@4.0.1
> +-- @angular/platform-browser-dynamic@4.0.1
> +-- @angular/platform-server@4.0.1
> +-- @angular/router@4.0.1
> +-- @angular/tsc-wrapped@4.0.1
> +-- @angular/upgrade@4.0.1
> +-- @types/angular@1.6.14
> +-- @types/angular-animate@1.5.6
> +-- @types/angular-cookies@1.4.3
> +-- @types/angular-mocks@1.5.9
> +-- @types/angular-resource@1.5.8
> +-- @types/angular-route@1.3.3
> +-- @types/angular-sanitize@1.3.4
> +-- @types/jasmine@2.5.36
> +-- @types/node@6.0.68
> +-- angular-in-memory-web-api@0.3.1
> +-- babel-cli@6.24.0
> +-- babel-preset-angular2@0.0.2
> +-- babel-preset-es2015@6.24.0
> +-- canonical-path@0.0.2
> +-- concurrently@3.4.0
> +-- core-js@2.4.1
> +-- http-server@0.9.0
> +-- jasmine@2.4.1
> +-- jasmine-core@2.4.1
> +-- karma@1.6.0
> +-- karma-chrome-launcher@2.0.0
> +-- karma-cli@1.0.1
> +-- karma-jasmine@1.1.0
> +-- karma-jasmine-html-reporter@0.2.2
> +-- karma-phantomjs-launcher@1.0.4
> +-- lite-server@2.3.0
> +-- lodash@4.17.4
> +-- phantomjs-prebuilt@2.1.14
> +-- protractor@4.0.14
> +-- rollup@0.36.4
> +-- rollup-plugin-commonjs@4.1.0
> +-- rollup-plugin-node-resolve@2.1.1
> +-- rollup-plugin-uglify@1.0.1
> +-- rxjs@5.0.1
> +-- source-map-explorer@1.3.3
> +-- systemjs@0.19.39
> +-- tslint@3.15.1
> +-- typescript@2.2.2
> `-- zone.js@0.8.5

**Suspected**

This may be caused by some package versions update. Since the live example seems to work (or the live example on plunkr wasn't updated).

**Additional information**

Similar issue is encounted in another file of the test example package:

> src/app/hero/hero-detail.component.spec.ts(83,5): Type 'HeroDetailService' is not assignable to type 'HeroDetailServiceSpy'.
>   Property 'testHero' is missing in type 'HeroDetailService'.

but the latest error seems related with overriding not clearly "understood" by typescript compiler as it sees only the original service and not the one declared in `usevalue`

**Comment by tbosch** [comment]
This is works as intended. `Injector.get` will cast the result based on the given token, and the token is `Location` (which is correct). As `SpyLocation` is a subclass of `Location`, you need to add a cast manually...
