### ISSUE TITLE
Router Guards - overloaded term for both services and their methods

### ISSUE THREAD

**Issue by shairez** [angular/angular#15827]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is a confusion about the name "Guards".
Currently, it refers both to **services** and their **methods**.

According to the docs (and other tutorials, blog posts etc) - 

We have methods like `canActivate` which are refered to as "guards". 
And we have services which hold these methods, like `AuthGuard`, which are also called "guards".

This overloading term is repeating all over the official [router documentation](https://angular.io/docs/ts/latest/guide/router.html#!#guards) :

### Guards as methods?

Here, we refer to the methods themselves as guards:
>The router supports multiple kinds of guards:

and then a list of methods like `canActivate`.

which is followed by:

> The CanActivate guard is the tool to manage these navigation business rules.

### Guards as services?
But we also refer to the services as guards - 

> **Guards** and the service providers they require must be **provided** at the module-level

In the code examples further on, we show code examples where we use `AuthGuard`, which is in fact the service which implements the `CanActivate` interface.

### Giving you a free potential WAT here, on me 😄 

From the docs (these 2 sentences are orgiinally written one after the other in the docs) - 

>Instead you'll write a `CanActivate()` **guard** to redirect anonymous users to the login page when they try to enter the admin area.

>This is a general purpose **guard** - you can imagine other features that require authenticated users - so you create an auth-**guard**.service.ts in the application root folder.

So it turns out that guards can have methods... which are called... guards... which is another potential ng-wat moment.  

**Expected behavior**
It's not a matter of changing the docs, we first need to agree on the concepts. 

So my suggestion is  that "Guards" will refer to **services**,
and their methods should be called `guarding methods`.

**What is the motivation / use case for changing the behavior?**
This change will reduce the confusion and overloaded terms. It'll make it easier to learn and also teach about this subject.

**Comment by ocombe** [comment]
Okaaaay? :bird:

**Comment by shairez** [comment]
@ocombe ... that's @PascalPrecht 's job 😃 

But seriously, what do you think? who decides on these things? who should we tag?

**Comment by ocombe** [comment]
I'm not sure :) if it's about documentation then it's @wardbell

**Comment by zoechi** [comment]
> In the router documentation we refer to methods like canActivate as guard.

any link? I'm not aware of an `canActivate` method

**Comment by shairez** [comment]
@zoechi I've updated the issue and added a link to the official routing docs -  the guards section.

**Comment by jasonaden** [comment]
Thanks for the issue. I agree, this is definitely a classic [`WAT`](https://www.youtube.com/watch?v=M_Wp-2XA9ZU) moment. Adding to the feature list.
