### ISSUE TITLE
Animation: State change not working if another animation is running

### ISSUE THREAD

**Issue by metrophos** [angular/angular#15823]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If an animation on a state change is running another state change on the same trigger is ignored. The event is triggered but nothing happend.

**Expected behavior**
If an animation on a state change is running another state change on the same trigger is not ignored and processed like in Angular 2

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/dcHvXiz0jOz0H07EmFuC?p=preview:
- Enter and leave mouse fast on the grey content block (second state change is ignored)
- Enter mouse on the grey content block. Wait for animation is done. Leave Mouse. (works correctly)

Here the same example with Angular 2: http://plnkr.co/edit/toNM80fPRNcCzLQQyojd?p=preview

**What is the motivation / use case for changing the behavior?**
On Angular 2 it works as expected an I guess the expected behavior it's the correct one.

**Please tell us about your environment:**
plnkr

* **Angular version:**
4.0.x

* **Browser:** 
all
 
* **Language:**
all

* **Node (for AoT issues):** `node --version` =

**Comment by metrophos** [comment]
Hi!
Is there any new information?

Best wishes,
Daniel

**Comment by eric-andresen** [comment]
Does anyone know of any workarounds, e.g. a way to manually cancel the executing animation or delay the second one until it is done?

**Comment by matsko** [comment]
@metrophos this seems to work now on master.

@eric-the-bike-man for the next 5.x release there will be a `event.finishAnimation()` method for the AnimationEvent class. There are also plans to use event details to direct when animations start in a delayed way (that will come later).

Closing.
