### ISSUE TITLE
Angular/core: core.umd.js (and min.js) declares 'use strict', while its not strict 

### ISSUE THREAD

**Issue by dimitrijuchtmans** [angular/angular#15828]
[X ] bug report

I am using Angular 4.0.1, and systemjs to bootstrap my app

I get the following error in IE 11, when starting my app:
![image](https://cloud.githubusercontent.com/assets/6793282/24799115/d682944c-1b99-11e7-9f9f-d1211de84ff6.png)
in english: Multiple definitions of a property not allowed in strict mode

This points to the following code:
![image](https://cloud.githubusercontent.com/assets/6793282/24799138/f75f0fa6-1b99-11e7-871f-f59c36ff30c1.png)

So it is not strict :(

**Comment by pkozlowski-opensource** [comment]
Traceur? It seems like something went wrong with your transpilation process, you shouldn't be using Traceur. Could you please try to reproduce this issue in a plunker?

**Comment by dimitrijuchtmans** [comment]
I removed traceur from my dependencies. Now it works.
I still don't know why i can't use traceur, but ok.
