### ISSUE TITLE
filter config null value is not filtered

### ISSUE THREAD

**Issue by amineparis** [angular/angular#15824]
this setting doesn't work. filtered return nothing even if I have null values
```
filter: {
            type: 'list',
              config: {
                selectText: '--',
                  list: [
                    { value: null, title: 'n/a' },
                    { value: 'urgent', title: 'urgent' },
                    { value: 'en retard', title: 'en retard' },
                  ]
                }
          },
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by amineparis** [comment]
it's an issue, send null values to smartTableData and define filter like so, choosing n/a from the dropbown clears all
