### ISSUE TITLE
Importing animation module in a lazy module

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular#15829]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
Error on importing animation module in a lazy module

```ts

import { NgModule } from '@angular/core'
import { CommonModule } from '@angular/common';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';


@NgModule({
  imports: [
      CommonModule,
      NoopAnimationsModule
    ]
})
export class Shared{}

@NgModule({
  imports: [ Shared ]
})
export class LazyModule{}
```

**Current behavior**

`ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

**Expected behavior**

Should work

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/Z5jVnWi15wG6aI6cY8Rq?p=preview

Click on lazy link to get the error

**Comment by MurhafSousli** [comment]
Animation module should only imported in root component, working plnkr from #15579
http://plnkr.co/edit/9RZ6msmiJGOQRaDiRy7G?p=preview

**Comment by deepakgoel999** [comment]
@MurhafSousli  In working Plunker also it has included the animation module from App Module and i.e. not lazy loaded.

**Comment by RenChunhui** [comment]
I really don't know how to use BrowserAnimationsModule. I usually give up this function.
