### ISSUE TITLE
@angular/platform-server visibly re-renders app before client is finished loading

### ISSUE THREAD

**Issue by spiffyjr** [angular/angular#15831]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
1. App is loaded and rendered via server.
2. Client begins loading in background.
3. A few client bundles load which initializes the client.
4. Server view is replaced with client.
5. Client finishes loading.

**Expected behavior**
1. App is loaded and rendered via server.
2. Client begins loading in background.
3. A few client bundles load which initializes the client.
4. Client finishes loading in background.
5. Server view is replaced with client.

**Minimal reproduction of the problem with instructions**
This is a fresh application using the `ngExpressEngine` from https://github.com/FrozenPandaz/ng-universal-demo with some minor bug fixes. Both the `ServerAppModule` and the `BrowserAppModule` import `BrowserModule.withServerTransition({ appId: 'app' })`. I can also see the `ng-transition` attribute on the styles in the `<head>`. Server-side rendering and client rendering are working perfectly the only issue is the transition is very noticeable as the entire page is loaded twice.

**What is the motivation / use case for changing the behavior?**
I just want it to work ;)

**Please tell us about your environment:**
ExpressJs ~4.15.2, angular 4.0.1, tested via Chrome on Ubuntu.

* **Browser:** [Chrome 57 | Firefox 52]
 
* **Language:** [TypeScript 2.2.2]

* **Node (for AoT issues):** `node --version` =  7.0.8

**Comment by adrienboulle** [comment]
can you provide a repo ?
I have a working repo with both server and browser side and I don't see any noticeable transition

**Comment by spiffyjr** [comment]
Alright, I managed to tree filter a working repository @ https://github.com/ggsoftwarellc/guardian-client.
You can use `yarn start:server` or `npm run start:server`. It looks like the homepage is reloaded right after the 0.chunk.js loads. I'm going to try and build a single bundle and see if that affects anything.

Can I see your repository for reference?

**Comment by adrienboulle** [comment]
sure https://github.com/adrienboulle/ng-universal-sp/tree/login

you should just `npm i && npm start`

**Comment by spiffyjr** [comment]
Okay, after some more testing here's what I've found.

- The FAQ page which has no ajax calls works fine when I remove it from lazy-loading. With chunks there's a visible render on the page still.
- The homepage is extremely noticeable because the client is requesting content again after the server already loaded it which causes the loading indicator to show up again. Ideally this should be a seamless transition. e.g., if that call was already loaded on the server then don't repeat the call for the client. There might be a way to do this on my app side but hopefully it's something the angular team can address at some point.

**Comment by spiffyjr** [comment]
Seems I was missing a key part of server/client in that transferring the HTTP state should be done by the application. I'm implementing a form of this now to see how that works. Thanks!

**Comment by adrienboulle** [comment]
what you do in the component is done server side AND browser side.

it's in theirs TODO to add a transfer state module to avoid it.

you can see in my repo that I use a transfer state module who does exactly that.
it stores in the rendered html a script which transfers the data in the window in order to get them back without calling again the api.

**Comment by spiffyjr** [comment]
Right, that's basically what I'm implementing. I didn't realize that wasn't automatic yet.
