### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by albandaft** [angular/angular#15834]
Is there a tutorial, an official documentation, or whatever on how to run a server side rendering with Angular ?
I am trying all imaginable useless tutorials, no one working, this is a bit frustating, as all this stuff is declared as final release but actually no documentation nothing on the fire.

**Comment by adrienboulle** [comment]
there is an example here (server-side only):
https://github.com/angular/angular/tree/master/packages/platform-server/integrationtest

**Comment by fulls1z3** [comment]
Hi @albandaft, I have suffered from the same, and spent almost half a week to get the server-side rendering running. Just after, I've decided to publish [this article](https://medium.com/burak-tasci/angular-4-with-server-side-rendering-aka-angular-universal-f6c228ded8b0) (*considering it could be helpful to other people having this problem*) as well as creating the [universal-example-app](https://github.com/nglibs/universal-example-app) repo. I hope it would help you a bit.

**Comment by tbosch** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by albandaft** [comment]
@fulls1z3 Thank you I have already tried that but failed (not remember why right now) but I will give a try again. 

@tbosch I know what you mean. But this is an issue, because right now on universal.angular.io and every angular official repo this is said to be working, but actually neither works neither there is an official documentation. I am not asking for support.
