### ISSUE TITLE
Testing: angular async not passing jasmine done

### ISSUE THREAD

**Issue by Karasuni** [angular/angular#15830]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I want to test behavior with a delayed Observable like this : 
```
it('should trigger twice', async(() => {
    Observable.of('data')
      .do(res => console.log('received pre delay:', res) || expect(true).toEqual(true)) // This is executed
      .delay(200)
      .do(res => console.log('received post delay:', res) || expect(true).toEqual(true)) // This is not executed
      .subscribe();
  }));
```
I notice that if executed within Jasmine the second statement is never reached.

In order to do actual async execution of the code according to the [jasmine docs](https://jasmine.github.io/2.0/introduction.html#section-Asynchronous_Support) I have to inject the `doneFn`:
```
it('should trigger twice', async((done) => {
    Observable.of('data')
      .do(res => console.log('received pre delay:', res) || expect(true).toEqual(true))
      .delay(200)
      .do(res => console.log('received post delay:', res) || expect(true).toEqual(true))
      .do(() => done()) // Failed: done is not a function
      .subscribe();
  }));
```
But here `done` is not a function. Without the `async()` everything works but then I will lose angular async support:
```
it('should trigger twice', (done) => {
    Observable.of('data')
      .do(res => console.log('received pre delay:', res) || expect(true).toEqual(true))
      .delay(200)
      .do(res => console.log('received post delay:', res) || expect(true).toEqual(true))
      .do(() => done())
      .subscribe();
  });
```

**Expected behavior**
`async()` should pass the parameter `doneFn`.

**Minimal reproduction of the problem with instructions**
See example

**Please tell us about your environment:**
Windows 10, Jasmine 2.5.41, Angular 4.0, Typescript 2.1.5

* **Angular version:** 4.0

* **Browser:** Chrome
 
* **Language:** Typescript 2.1.5

**Comment by JiaLiPassion** [comment]
this issue will be fixed in next version of `zone.js` (0.8.21), and you don't need to pass `done`.

**Comment by JeanMeche** [comment]
This is an outdate issue. One has to either call `done()` or use `fakeAsync` but not both at the same time.
