### ISSUE TITLE
Flag to remove css files when generating component!

### ISSUE THREAD

**Issue by IamManchanda** [angular/angular#15844]
**I'm submitting an Advancement** 

Like many others i am a fan of global styles (ofcourse, if used correctly like [BEMIT](https://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/) and i basically (quite surely like many others) don't like this below thing for my css unless needed

```scss
h3[_ngcontent-c0] {
  margin-top: 1rem;
  color: #0277bd;
}
```
I will instead use global styles by either using `styles.css` global file or using sass tools for my css so i basically delete my `foo.component.css` file and its declaration from a **foo** component and do it like this 

```scss
.c-foo--title {
  margin-top: 1rem;
  color: #0277bd;
}
```
In short, just would like to separate my styling with Javascript and the HTML DOM!

So just want to know if is there any way (and if not can it be provided) to have a flag on not adding separate component styling css file when we generate a component from CLI!

Something like 

```bash
$ ng g c --nocss foo
```

-------------------------------------------------------------------------------------------------------------------------------

**What is the motivation / use case for changing the behavior?**

- [BEMIT](https://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/) 

**Please tell us about your environment:**

* **Angular version:** 4.0.X

 
* **Language:** TypeScript X.X 

* **Tool:** CLI

**Comment by tbosch** [comment]
Thanks for the feature request. Please file issues for angular-cli against https://github.com/angular/angular-cli. Thanks!

**Comment by IamManchanda** [comment]
@tbosch done!
