### ISSUE TITLE
angular4 aot throw require is not defined error

### ISSUE THREAD

**Issue by xhe** [angular/angular#15849]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When loading AOT result, I am getting  this error:
require is not defined

**Expected behavior**
Should meet no problem

**Minimal reproduction of the problem with instructions**
I spent quire a while to do AOT with angular 4, and always got this error:
Uncaught ReferenceError: require is not defined

I got this error because I am using jquery in my app, and in the application, I am having this code:

    var jQuery = require('jquery');
    jQuery("xxxx").val()

If I remove this, the whole AOT worked like a charm.

My tsconfig-aot.json:

    {
      "compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
    "lib": ["es5", "dom"],
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true
      },
     "files": [
        "src/app/app.module.ts",
        "src/main.ts"
      ],
    
      "angularCompilerOptions": {
       "genDir": "aot",
       "skipMetadataEmit" : true
     }
    }

And my rollup config:

    import rollup      from 'rollup'
    import nodeResolve from 'rollup-plugin-node-resolve'
    import commonjs    from 'rollup-plugin-commonjs';
    import uglify      from 'rollup-plugin-uglify'
    
    export default {
      entry: 'src/main.js',
      dest: 'public/build.js', // output a single application bundle
      sourceMap: false,
      format: 'iife',
      onwarn: function(warning) {
        // Skip certain warnings
    
        // should intercept ... but doesn't in some rollup versions
        if ( warning.code === 'THIS_IS_UNDEFINED' ) { return; }
        // intercepts in some rollup versions
        if ( warning.indexOf("The 'this' keyword is equivalent to 'undefined'") > -1 ) { return; }
    
        // console.warn everything else
        console.warn( warning.message );
      },
      plugins: [
          nodeResolve({jsnext: true, module: true}),
          commonjs({
            include: [ 'node_modules/rxjs/**','node_modules/jquery/**']
          }),
          uglify()
      ]
    }

Does this mean, if you are using require() inside your ng4 app, then AOT will not work?

Thanks and hope to hear your advice

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Elohina** [comment]
Hi, any solution for the problem? I have the same issue.

**Comment by darincardin** [comment]
Is there any solution to this? With AOT, it seems to be one problem after another.

**Comment by xhe** [comment]
I solved jquery issue by using this:

import * as jquery_ from 'jquery';
let jQuery:any = (<any>jquery_).default || jquery_;

You can try.

**Comment by chuckjaz** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

Specifically, this is asking a way to use `jQuery` in an angular application, and is not reporting an issue with Angular itself.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
