### ISSUE TITLE
route content is blank on iOS when tapping a router link

### ISSUE THREAD

**Issue by danielhaan** [angular/angular#15846]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I use the router links to navigate to other pages in my app, the page is blank, even though the component shows up in the inspector. Only happens on iOS.

**Expected behavior**

The router links show the components as normally expected. Same as on desktop (mac/windows) and android phones.

**Minimal reproduction of the problem with instructions**
You can try for yourself at www.appollodev.com where my app is uploaded (copied dist folder and built using "ng build --prod --aot")
Steps:

1. Tap the burger-menu in the top right corner
2. Tap any menu-point (my example uses "EVENTS")
3. See that the page is blank
4. Try refreshing and see that the component appears as it is supposed to.

I have tried this using the Safari Remote Inspection tool and here are two screenshots that reveal, that the component is indeed loaded and the elements are taking up space on screen, but the actual content isn't rendered. Only on refresh.

[Screenshots](http://imgur.com/a/9NXl1)

**What is the motivation / use case for changing the behavior?**

The bug makes the app unusable for iOS users.

**Please tell us about your environment:**

iOS version: 10.0.1 (14A403.
Tested on safari, chrome and firefox. None of them work.

**Versions of things:**
```
@angular/cli: 1.0.0-rc.1
node: 6.10.0
os: win32 x64
@angular/cli: 1.0.0-rc.1
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/compiler-cli: 2.4.9

npm version: 4.4.4
```
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Seemingly it is the same for all browsers. I have tested on Safari, Chrome and Firefox all for iOS.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Vanilla Angular 2

* **Node (for AoT issues):** `node --version` =   v6.10.0

If I missed something, you can see a more in depth explanation of this problem I posted on [StackOverflow](http://stackoverflow.com/questions/43295965/angular-2-app-route-content-is-blank-on-ios)

**Comment by Toxicable** [comment]
Can you make a minimal reproduction in plunkr, it's not very helpful debugging your code since we cannot change and test it, plus it's not showing the issue in isolation. here's a template that you can use https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by danielhaan** [comment]
Sorry about the inconvenience, but I have tried implementing just the routing and 2 components in the plunker, but it isn't working (unrelated). Can you see why?
https://plnkr.co/edit/yKynacyI7T33JKzHGQ2o?p=preview

**Comment by Toxicable** [comment]
here's a template with some basic routing config http://plnkr.co/edit/NHrcNEDHVD6bUa5kMxcr?p=preview

**Comment by Toxicable** [comment]
@danielhaan Thanks for investigating this further
