### ISSUE TITLE
nested *ngFor delete parent throws error because fails to update child *ngFor

### ISSUE THREAD

**Issue by vfistri2** [angular/angular#15854]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

when you try nested *ngFor and delete parent ngFor it throws error because it still tries to do ngFor on child of null

**Expected behavior**

remove both parent element and child element from dom

**Minimal reproduction of the problem with instructions**

demo is here 
http://stackoverflow.com/questions/43312028/angular-4-nested-ngfor-on-delete-parent-error

**What is the motivation / use case for changing the behavior?**

simplicity and rapid programming i could first delete all children but that is something i expect framework to do for me, i can keep a backup copy of data and delete there but still...

**Please tell us about your environment:**

win 10, chrom latest version

* **Angular version:** 2.0.X

@angular/cli: 1.0.0
node: 7.7.2
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript
* **Node (for AoT issues):** `node --version` =   
v7.7.2

**Comment by zoechi** [comment]
It looks like this issue was solved in StackOverflow. Please consider closing this issue.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
