### ISSUE TITLE
canActivate not fired after navigate to "same" page

### ISSUE THREAD

**Issue by isometriq** [angular/angular#15855]
**I'm submitting a ...**
```
[X] bug report
[  ] feature request
[  ] support request
```

**Current behavior**
1. Default page "/" redirects to "/dashboard"
2. "/dashboard" has canActivate(), it redirects to "/login"
3. Login successful, then press logout button (it clears authentication)
4. After logout, redirect to default page "/"
5. Default page "/" redirects to "/dashboard"
6. "/dashboard" has canActivate(), it is NOT fired

**Expected behavior**
I expect canActivate() to be fired and redirect to "/login".
In the issue title, I say "same" page because the page is not the same, but perhaps the redirection is interpreted as the same page.

**Minimal reproduction of the problem with instructions**
See my steps above.
Here is my router config:
```
export const AppRoutes: ModuleWithProviders = RouterModule.forRoot([

    // Default page
    { path: '', pathMatch: 'full', redirectTo: '/dashboard' },

    // Login page is outside the protected routes
    { path: 'login', component: LoginComponent },

    // Group of protected routes
    {
        path: '',
        canActivate: [AuthGuardService],
        canActivateChild: [AuthGuardService],

        children: [
            { path: 'dashboard', component: DashboardComponent },
            { path: 'users', component: UsersListComponent },
        ]
    },

    // Default page, when route does not match a rule
    // If not authenticated, user is sent to the login screen first
    { path: '**', component: PageNotFoundComponent, canActivate: [AuthGuardService] }
]);
```
Here is my AuthGuardService:
```
export class AuthGuardService implements CanActivate, CanActivateChild {

    constructor(private authService: AuthService, private router: Router) {
        // empty...
    }

    canActivate(activatedRoute: ActivatedRouteSnapshot, routerState: RouterStateSnapshot): boolean
    {
        if (this.authService.isAuthenticated()) {
            return true;
        }

        this.authService.setRedirectUrl(routerState.url);

        this.router.navigateByUrl('/login');
        return false;
    }

    canActivateChild(activatedRoute: ActivatedRouteSnapshot, routerState: RouterStateSnapshot): boolean {
        return this.canActivate(activatedRoute, routerState);
    }
}
```

**What is the motivation / use case for changing the behavior?**
It should always be fired, isn't?

**Please tell us about your environment:**
Windows, Chrome, Angular-CLI, NPM

* **Angular version:**
```
    "@angular/animations": "^4.0.1",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
```

* **Browser:** 
Chrome, but any browser will do i think
 
* **Language:**
Typescript

**Comment by isometriq** [comment]
Some observations:

1. At step 4 (After logout, redirect to default page "/")
If I redirect instead to "/users" or "/login" ..then canActivate() is fired.

2. After login at step 3, I'm redirected to step "/dashboard"..
If I go to "/users" before logging out at step 4 ..then the redirect to "/" will fire canActivate().

**Comment by isometriq** [comment]
Hopefully I can fix this issue by redirecting to "/login", but I think something may not be right and it would be problematic in certain cases.

**Comment by rafiwardak2003** [comment]
As far as I remember (maybe I am wrong), it was never going to fire rerouting to the same URL, unless something in the URL changed. It's basically how Angular keeps track of routes and their history. The children one should fire though.

**Comment by isometriq** [comment]
that's the thing ..since the redirection leads to the same address, it counts like no navigation i think. However this is wrong. The url that determines a change should be the one before the redirection.

**Comment by jasonaden** [comment]
This was a recently added feature: 

https://angular.io/api/router/Router#onSameUrlNavigation
