### ISSUE TITLE
Animation midlevel callbacks

### ISSUE THREAD

**Issue by hassanasad** [angular/angular#15857]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently there are two animation callbacks:
```
(@triggerName.start)="animationStarted($event)"
(@triggerName.done)="animationDone($event)"
```
**Expected behavior**

In certain animations a midlevel callback is also required so that another animation can be triggered before the first one ends on an element. There are several use cases for this, one of them being to load up a list of items sliding in some what parallel with slight delay one after the other.

Perhaps new midlevel callbacks such as the ones listed below can be implemented:
```
(@triggerName._25)="animation($event)"
(@triggerName._50)="animation($event)"
(@triggerName._75)="animation($event)"
```
The numbers (25, 50 and 75) are just to represent percentage completion of the animation and the `$event` object can have a value such as `animationProgress` so a single animation handler can be used to implement any logic based on animation % completion.

**Comment by kinkoazc** [comment]
Hi! Maybe a progress event(on the lines of http://velocityjs.org/#progress) would be more convenient.

**Comment by benneq** [comment]
Using this:
```
(@triggerName._25)="animation($event)"
(@triggerName._50)="animation($event)"
(@triggerName._75)="animation($event)"```
means that the function should be called at EXACTLY 25%, 50% and 75%. This is nearly impossible.

It's more likely you want to call the function when current progress is >= 25%, but < 50%. But what if the progress does a huge step? Like from 24% to 51%. Should the 25% trigger be called? I'd say: depends.

Though I'd vote for a progress callback. There you can define on your own how to handle these cases.

**Comment by hassanasad** [comment]
@benneq You are right, I just wanted to request some extension to the animations module. The start and stop triggers do not seem enough for slightly advanced animations.
Progress callback method is also a reasonable (and probably preferred method)
