### ISSUE TITLE
[Docs] Angular Universal in an existing project

### ISSUE THREAD

**Issue by IamManchanda** [angular/angular#15850]
**I'm submitting a Docs addition**

I can't find any help material on Angular universal  on how to install it in existing project for angular 4. Please provide docs for the same.

Also, platform-server is not been added when i update to angular cli 
http://i.imgur.com/Co4tEOc.png

* **Angular version:** 4.0.X

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

------------------------------------------------------------------------------------------------------

On a sidenote, thanks to gitter just could find => https://github.com/robwormald/ng-universal-demo
But this is not helping me out on how to add universal in an existing project

**Comment by Toxicable** [comment]
Docs are coming.

>Also, platform-server is not been added when i update to angular cli
http://i.imgur.com/Co4tEOc.png

You need to add it manually with the current version of the cli `npm i --save @angular/platform-server`

**Comment by hiepxanh** [comment]
excuse me, when we will have an official docs for user to use with existing project ? any infomation of tentative schedule

**Comment by vikerman** [comment]
Please refer to https://angular.io/guide/universal

https://github.com/angular/universal-starter - provides a Angular CLI starter repo.
