### ISSUE TITLE
Passing data between NON parent and children components with a service

### ISSUE THREAD

**Issue by jrothrock** [angular/angular#15856]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When a service is created between two components, with subscriptions to the service, the data isn't emitted by the observable.

I created a SO question here: [https://stackoverflow.com/questions/43312920/angular2-passing-data-between-non-parent-child-components/43312986#43312986](https://stackoverflow.com/questions/43312920/angular2-passing-data-between-non-parent-child-components/43312986#43312986)
**Expected behavior**

The data would be emitted by the observable.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Passing data between two components
**Please tell us about your environment:**

OSX, VSCode, Angularcli using webpack
* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
es6
* **Node (for AoT issues):** `node --version` =

**Comment by ericmartinezr** [comment]
You missed this important part: **Minimal reproduction of the problem with instructions**, If you're 100% sure this is a bug, you **MUST** provide a reproduction. 

In any case you have to, provide the service in the most top parent of the hierarchy, Do not provide the service again in the children. 

Please do not open support requests in github (you already did it in SO), if you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jrothrock** [comment]
Op, sorry about that. That did the trick, thanks for the quick response

**Comment by hansl** [comment]
Closing issue as fixed, per comment above.
