### ISSUE TITLE
 If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. 

### ISSUE THREAD

**Issue by kjhatis** [angular/angular#15860]
**I'm submitting an issue  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

zone.js@0.6.25?main=browser:355 Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template> <div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()"): MdAutocomplete@0:0 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template> <div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()"): MdAutocomplete@0:0
    at TemplateParser.parse (https://unpkg.com/@angular/compiler@2.2.1//bundles/compiler.umd.js:7730:21)
    at RuntimeCompiler._compileTemplate (https://unpkg.com/@angular/compiler@2.2.1//bundles/compiler.umd.js:17573:53)
    at eval (https://unpkg.com/@angular/compiler@2.2.1//bundles/compiler.umd.js:17493:64)
    at Set.forEach (native)
    at RuntimeCompiler._compileComponents (https://unpkg.com/@angular/compiler@2.2.1//bundles/compiler.umd.js:17493:21)
    at createResult (https://unpkg.com/@angular/compiler@2.2.1//bundles/compiler.umd.js:17389:21)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.6.25?main=browser:203:28)
    at Zone.run (https://unpkg.com/zone.js@0.6.25?main=browser:96:43)
    at https://unpkg.com/zone.js@0.6.25?main=browser:462:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.6.25?main=browser:236:37) Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template> <div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()"): MdAutocomplete@0:0
    at TemplateParser.parse (https://unpkg.com/@angular/compiler@2.2.1//bundles/compiler.umd.js:7730:21)
    at RuntimeCompiler._compileTemplate (https://unpkg.com/@angular/compiler@2.2.1//bundles/compiler.umd.js:17573:53)
    at eval (https://unpkg.com/@angular/compiler@2.2.1//bundles/compiler.umd.js:17493:64)
    at Set.forEach (native)
    at RuntimeCompiler._compileComponents (https://unpkg.com/@angular/compiler@2.2.1//bundles/compiler.umd.js:17493:21)
    at createResult (https://unpkg.com/@angular/compiler@2.2.1//bundles/compiler.umd.js:17389:21)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.6.25?main=browser:203:28)
    at Zone.run (https://unpkg.com/zone.js@0.6.25?main=browser:96:43)
    at https://unpkg.com/zone.js@0.6.25?main=browser:462:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.6.25?main=browser:236:37)

**Please tell us about your environment:**

'@angular':                   'https://unpkg.com/@angular', // sufficient if we didn't pin the version
        '@angular/router':            'https://unpkg.com/@angular/router' + routerVer,
        '@angular/forms':             'https://unpkg.com/@angular/forms' + formsVer,
        'angular2-in-memory-web-api': 'https://unpkg.com/angular2-in-memory-web-api', // get latest
        'rxjs':                       'https://unpkg.com/rxjs@5.0.0-beta.12',
        'bootstrap':                  'https://unpkg.com/bootstrap@3.3.7',
        'core-js':                    'https://unpkg.com/core-js@2.4.1',
        'jquery':                     'https://unpkg.com/jquery@3.1.1',
        'ts-helpers':                 'https://unpkg.com/ts-helpers@1.1.1',
        'zone.js':                    'https://unpkg.com/zone.js@0.6.23',
        'angular-cli':                'https://unpkg.com/angular-cli@1.0.0-beta.21',
        'codelyzer':                  'https://unpkg.com/codelyzer@1.0.0-beta.4',
        'jasmine-core':               'https://unpkg.com/jasmine-core@2.5.2',
        'jasmine-spec-reporter':      'https://unpkg.com/jasmine-spec-reporter@2.5.0',
        'karma':                      'https://unpkg.com/karma@1.2.0',
        'karma-chrome-launcher':      'https://unpkg.com/karma-chrome-launcher@2.0.0',
        'karma-jasmine':              'https://unpkg.com/karma-jasmine@1.0.2',
        'karma-remap-istanbul':       'https://unpkg.com/karma-remap-istanbul@0.2.1',
        'protractor':                 'https://unpkg.com/protractor@4.0.9',
        'ts-node':                    'https://unpkg.com/ts-node@1.2.1',
        'tslint':                     'https://unpkg.com/tslint@3.13.0',
        'webdriver-manager':          'https://unpkg.com/webdriver-manager@10.2.5',
        'ts':                         'https://unpkg.com/plugin-typescript@4.0.10/lib/plugin.js',
        'typescript':                 'https://unpkg.com/typescript@2.0.3/lib/typescript.js',
        'angular2-modal':             'https://unpkg.com/angular2-modal' + angular2ModalVer,
        'ng2-drag-drop':              'https://unpkg.com/ng2-drag-drop@0.5.3/index.js',
        'dragula':                    'https://unpkg.com/dragula@3.7.2/dist/dragula.js'

IMPORTED:

import { NgModule, CUSTOM_ELEMENTS_SCHEMA }  from '@angular/core';

ADDED:

@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        HttpModule,
        JsonpModule,
        CKEditorModule,
        Ng2DatetimePickerModule,
        Ng2DragDropModule,
        DragulaModule,
        ModalModule.forRoot(),
        MaterialModule.forRoot(),
        BootstrapModalModule,
        RouterModule.forRoot(appRoutes, {useHash: true})
    ],
    declarations: [something
    ],
    providers: [],
    bootstrap: [AppComponent],
    schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
})

* **Angular version:** 2.0.X

ANGULAR 2.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome, Firefox Safari
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
`<ng-template>` is only available from 4.0.0 RC: https://github.com/angular/angular/blob/master/CHANGELOG.md#400-rc1-2017-02-24

**Comment by kjhatis** [comment]
If it is only available in angular 4.0.0 then why i am getting this on 2.2.1 , My project is almost completed and sudden i am facing this.

**Comment by tytskyi** [comment]
@kjhatis check what of your 3rd party modules use it. You could find over your `node_modules`. 

Mu guess is that some 3rd party widget uses that tag and specifies both angular 2 and 4 as peer dependency

**Comment by kjhatis** [comment]
i am using online libraries from unpkg.com to transpile i am not using npm

**Comment by tytskyi** [comment]
@kjhatis you said you use version 2.2.1 but in fact it is not pinned in your config, so that we don't know which version is used. The other thing is that Material package uses `ng-template` https://github.com/angular/material2/search?utf8=%E2%9C%93&q=ng-template&type=

Please check your config, probable you need to fix angular version. However i don't know how does unpkg work so please look for some docs.

**Comment by kjhatis** [comment]
Removed material, Now Its Working, Thanks for your help.

**Comment by atomicnation** [comment]
The same _'ng-template' is not a known element_ error is happening to me. I'm using angular-cli, and here the versions of packages:
angular-cli: 1.0.0-beta.28.3
node: 7.10.0
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/compiler-cli: 2.4.10

Any ideas of what could be causing the issue?

Full error here:

```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngIfElse' since it isn't a known property of 'h3'. ("<button (click)="cambiar(administrador)">{{loginBtn}}</button>
<br>
<h3 [ERROR ->]*ngIf="administrador; else noAdmin">Hello, Admin!</h3>
<ng-template #noAdmin>Bye!</ng-template>"): PlantillasComponent@2:4
Property binding ngIfElse not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("<button (click)="cambiar(administrador)">{{loginBtn}}</button>
<br>
[ERROR ->]<h3 *ngIf="administrador; else noAdmin">Hello, Admin!</h3>
<ng-template #noAdmin>Bye!</ng-template>"): PlantillasComponent@2:0
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
<br>
<h3 *ngIf="administrador; else noAdmin">Hello, Admin!</h3>
[ERROR ->]<ng-template #noAdmin>Bye!</ng-template>"): PlantillasComponent@3:0 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
Can't bind to 'ngIfElse' since it isn't a known property of 'h3'. ("<b……} Error: Template parse errors:
Can't bind to 'ngIfElse' since it isn't a known property of 'h3'. ("<button (click)="cambiar(administrador)">{{loginBtn}}</button>
<br>
<h3 [ERROR ->]*ngIf="administrador; else noAdmin">Hello, Admin!</h3>
<ng-template #noAdmin>Bye!</ng-template>"): PlantillasComponent@2:4
Property binding ngIfElse not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("<button (click)="cambiar(administrador)">{{loginBtn}}</button>
<br>
[ERROR ->]<h3 *ngIf="administrador; else noAdmin">Hello, Admin!</h3>
<ng-template #noAdmin>Bye!</ng-template>"): PlantillasComponent@2:0
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
<br>
<h3 *ngIf="administrador; else noAdmin">Hello, Admin!</h3>
[ERROR ->]<ng-template #noAdmin>Bye!</ng-template>"): PlantillasComponent@3:0
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:6872:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:64471:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:5727:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:17596:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:47244:68)
    at http://localhost:4200/vendor.bundle.js:47127:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:47127:19)
    at createResult (http://localhost:4200/vendor.bundle.js:47009:19)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6214:26)
    at Zone.run (http://localhost:4200/polyfills.bundle.js:6006:43)
    at http://localhost:4200/polyfills.bundle.js:6593:57
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6247:31)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6046:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6426:35)
consoleError @ zone.js:522
handleUnhandledRejection @ zone.js:527
_loop_1 @ zone.js:562
drainMicroTaskQueue @ zone.js:566
zone.js:524 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngIfElse' since it isn't ……}
consoleError @ zone.js:524
handleUnhandledRejection @ zone.js:527
_loop_1 @ zone.js:562
drainMicroTaskQueue @ zone.js:566
```
