### ISSUE TITLE
Cannot read property 'exclude'  of undefined at applyDefaults

### ISSUE THREAD

**Issue by saurabhschauhan** [angular/angular#15864]
![screenshot from 2017-04-10 16-59-27](https://cloud.githubusercontent.com/assets/25522343/24859685/46deab00-1e0f-11e7-9817-240e29efe2cc.png)

Hello,
I'm developing my project using angular2 on Linux os and I updated my app to angular 4  using **" npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@latest --save** this but I'm getting the following error.
```

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
