### ISSUE TITLE
When I try assets in URL browser shows message "Sites is Offline"

### ISSUE THREAD

**Issue by GigaDeveloper** [angular/angular#15861]
When I try assets in URL browser shows message "Sites is Offline".
How can I change message or redirect to home page, after someone try to enter assets folder by URL 

http://example.com/assets

![sites is offline](https://cloud.githubusercontent.com/assets/8425033/24850487/586dd860-1de1-11e7-905a-95ba2cd21cd4.PNG)

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
