### ISSUE TITLE
fetch backend implementation for http package

### ISSUE THREAD

**Issue by sagar12861** [angular/angular#15872]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
Is there any reason for not having fetch backend implementation for http package ?

**Comment by alxhub** [comment]
Hi @sagar12861, 

Yes, currently the `Http` API is incompatible with `fetch`, as in the `fetch` API the response body is retrieved asynchronously. Currently `Http` gives synchronous access to the response body.

We do plan to support (not implement) a `fetch` backend in the newer http APIs - coming soon to an Angular near you.

**Comment by sagar12861** [comment]
Hi @alxhub Thanks for your replay.
Is it going to be released in angular 4.x ? Do you welcome contributions to the same ?

**Comment by alxhub** [comment]
`fetch` is possible in `HttpClient` (and you can implement your own). I don't plan on providing a native implementation at this time.

**Comment by epelc** [comment]
@alxhub any chance we could get a native implementation to help ease debugging service worker related issues since they convert everything to fetch?
