### ISSUE TITLE
docs(changelog): typo "Perviously" in 4.0.0-rc.4 (2017-03-17)

### ISSUE THREAD

**Issue by alexeychikk** [angular/angular#15871]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
BREAKING CHANGES
Perviously, any provider that had an ngOnDestroy lifecycle hook would be created eagerly.

**Expected behavior**
BREAKING CHANGES
Previously, any provider that had an ngOnDestroy lifecycle hook would be created eagerly.

**Minimal reproduction of the problem with instructions**
https://github.com/angular/angular/blob/7a715b2403867aa3adfab1c87acd22af4fd8697b/CHANGELOG.md#breaking-changes

**Comment by vicb** [comment]
please send a PR
