### ISSUE TITLE
aio(docs): set the image width / height for all pages

### ISSUE THREAD

**Issue by wardbell** [angular/angular#15888]
Set the image width / height for all pages, marketing pages especially, to minimize page reflows. Sweep docs and fix all images by hand.

**Comment by wardbell** [comment]
**Why is this a "Blocker"?**
It's a perf tuning issue for small devices. We have much more important and substantive content and visual concerns.

**Comment by petebacondarwin** [comment]
I will look into whether it is possible to automate this via dgeni...

**Comment by wardbell** [comment]
Addressed in PR #16353
