### ISSUE TITLE
Ngselect showing "functions", "length" in ng-options for inherited array (v1.4)

### ISSUE THREAD

**Issue by superasn** [angular/angular#1588]
Hi,

Please take a look at this fiddle:

http://jsfiddle.net/fggx31k7/

Open the extended Array drop-down (SELECT), you will see all sorts of things like functions, length, etc. 

![Preview](http://i.imgur.com/mPmomXf.png)

This was not happening until Angular 1.3.

https://jsfiddle.net/superasn/k2uwdjh5/ **(working fine)**

Any ideas?

Thanks,
San

**Comment by erwinmombay** [comment]
hey thanks for reporting! unfortunately i think you are in the wrong repository (this is the angular 2 repo) :) https://github.com/angular/angular.js/issues is the more appropriate link to report anything related to angular 1.x

**Comment by pkozlowski-opensource** [comment]
Yeh, @erwinmombay is right. @superasn could you please move it over to https://github.com/angular/angular.js ?
