### ISSUE TITLE
W3c Validation issue with all attributes starting with _ngcontent-

### ISSUE THREAD

**Issue by bhushanbhagat** [angular/angular#15891]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The attribute **_ngcontent-** is  fails under **W3C validation** in prod mode.
W3C validation gives the error: **"Attribute _ngcontent-c0 not allowed on element div at this point."**
[sample.txt](https://github.com/angular/angular/files/912822/sample.txt)

**Expected behavior**
The attribute **_ngcontent-** is should not be present in the prod mode.

**Minimal reproduction of the problem with instructions**
I referred the sample from http://plnkr.co/edit/tmGQ43m3OGhn8uoAYWua?p=preview
I have attached the sample test file [sample.txt](https://github.com/angular/angular/files/912822/sample.txt) which can be tested on "https://validator.w3.org/" under validate by direct input. Copy-paste the content in the text area and run the validator.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by tbosch** [comment]
Hello, we are only adding the attribute during runtime.
Are you using serverside rendering?

**Comment by bhushanbhagat** [comment]
@tbosch No server side rendering is used

**Comment by chuckjaz** [comment]
This is working as expected. The attributes are added at runtime for style encapsulation and are necessary for this feature to work even in prod mode.

**Comment by trotyl** [comment]
@raDiesle Are you serious? All HTML templates are compiled to JavaScript code in AOT build, there's no HTML to be shipped.

**Comment by raDiesle** [comment]
HTML wrapped in string in a JS file ;)
So basically no way to use w3 validator. By using Regex to only return HTML within js file would make validator fail.

**Comment by trotyl** [comment]
That why it’s only runtime-added. And W3C validation is for HTML input, not for DOM API manipulation result.
