### ISSUE TITLE
streaming ndjson response for http package

### ISSUE THREAD

**Issue by sagar12861** [angular/angular#15892]
**I'm submitting a 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see 

As of my knowledge currently there is no streaming option for ndJSON responses.
Do you have any plans to add that in later versions ?

**Comment by alxhub** [comment]
Hi @sagar12861, thanks for your question.

Streaming is not planned for `Http` currently. It could probably be supported in upcoming APIs.

I will consider this issue a feature request for stream support.

**Comment by markbarks** [comment]
Hi @alxhub - apologies if I'm missing something obvious, but I'm trying to determine whether NDJSON chunked http streaming is already supported by the new httpclient module. I'm attempting to connect an Angular app to the Kubernetes watch endpoints. I saw your response about the NDJsonStreamInterceptor in the #16270 issue, but I haven't been able to get anything like that to work yet. Should I persist, or perhaps try to integrate the [fetch](https://davidwalsh.name/streaming-data-fetch-ndjson) library for the time being? Thx
