### ISSUE TITLE
Resampling wav file in angular

### ISSUE THREAD

**Issue by lararogu** [angular/angular#15893]
Is there any library to resample a wav file using its URL or array bytes[ ]?
I would like to do it inside my controller code.
Any ideas? I found a resamplerjs (https://github.com/notthetup/resampler) library but it seems deprecated.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
