### ISSUE TITLE
aio: Search-results issues/improvements

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#15894]
.search-results
  - has `overflow: scroll`, which adds unnecessary scrollbars
  - has `width`+`box-sizing`, such that it is wider than viewport and vertical scrollbar is hidden
  - has no obvious way to close/hide it

**Comment by devoto13** [comment]
Maybe it's intended behavior, but to me it looks a bit strange, that search results have position fixed (i.e. stay on the screen, while you scroll), but search box hides together with header, when page is scrolled.

**Comment by petebacondarwin** [comment]
@gkalpak is this now fixed?

**Comment by gkalpak** [comment]
I previously thought it would be nice to have a closing `x` at the top-right corner, but I am not sure any more. (Leaving it up to @sjtrimble to consider :smiley:)
The rest has been fixed.

**Comment by sjtrimble** [comment]
I believe it's best without, unless we are not taking into account accessibility considerations.

Maybe we add that separately as a design consideration for future topic of discussion?

**Comment by gkalpak** [comment]
I don't think a11y-wise a close button helps. (E.g. keyboard users are much more likely to use the ESC key, than reach for the `x` button.)
