### ISSUE TITLE
[attr.disabled] behaves incorrectly

### ISSUE THREAD

**Issue by klinki** [angular/angular#15900]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`[attr.disabled]` sets disabled state even if value is `false`. Only way how to remove disabled state is set `[attr.disabled]` to `null`.

**Expected behavior**
it should be disabled only for `true` value

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/iQA20W4zFzI3AfqEV1jO?p=preview

**What is the motivation / use case for changing the behavior?**
It is not straightforward and it requires workaround 

**Please tell us about your environment:**
* **Angular version:** 4.0.X
* **Browser:** [all ]
* **Language:** [all ]

**Comment by pkozlowski-opensource** [comment]
This works as expected, try in your favorite browser:

```javascript
var i = document.createElement('input');
i.setAttribute('disabled', false);
console.log(i);
```
The explanation here is that attributes can have only string values so `false` gets converted to `"false"`.

**Comment by klinki** [comment]
@pkozlowski-opensource I disagree with you. Look at this jQuery example: http://plnkr.co/edit/75vCj6uid0FwKkDc6Jn1?p=preview

This works as expected.

Why do you refer to default browser behavior (which is IMHO wrong)? I thought framework is here to provide us higher abstraction? Why couldn't angular do that in this case? (and jQuery could)
