### ISSUE TITLE
feat(aio): dgeni migrates file-tree to html

### ISSUE THREAD

**Issue by wardbell** [angular/angular#15904]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

The current migration tool converts `file-tree` markup to new tags in the `<aio-filetree>` family. 
That's actually a hindrance. It would be much easier for everyone if dgeni produced the same html that Jade produces.

From the authors perspective:
1) We don’t want many of these file-tree thingy’s anyway; in fact we will be deleting many
2) We rarely write or change them
3) Therefore we shouldn’t invest heavily in them
4) The generated `<div>` HTML is actually pretty easy to read and write.
5) If we stick with that, we (ahem … Stef)  don’t have to do anything.

Accordingly, it would be nice if dgeni just did a straight conversion from `.whatever some...text` to `<div class="whatever">some...text</div>`

**Comment by petebacondarwin** [comment]
Fixed via https://github.com/petebacondarwin/aio-migrator/commit/abb2815a5af5f88b2d139d2ab777850af4e7b46d
