### ISSUE TITLE
The collector throws on the expression `new f`

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#15906]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

The collector will throw `Cannot read property 'map' of undefined` when a variable is initialized with `new f`. 

**Expected behavior**

Generates a new expression with no arguments.

**Minimal reproduction of the problem with instructions**

Collect metadata for a module containing:

```
export var a = new f;
```

**Comment by gkalpak** [comment]
OOC, why is it not a valid new expression?

**Comment by chuckjaz** [comment]
Updated the description to remove that comment as it is valid.

**Comment by gkalpak** [comment]
And I removed my comment to avoid confusion :smiley:
