### ISSUE TITLE
virus Trojan:Win32/Vigorf.A - reported by Windows Defender when installing @angular 4.0.2

### ISSUE THREAD

**Issue by marius-oprea** [angular/angular#15909]
- Create a new project using node 7.9.0, npm 4.4.4 and @angular/cli 1.0.0 .
- Use @angular 4.0.2 in your package.json
- execute 'npm install'
- Windows Defender anti-virus will detect the file 'node_modules\ .staging\hash.js-954dfe4a\lib\hash\sha.js' as the Virgorf.A trojan virus.

I'm not sure if this is the node v7.9.0 fault, Windows Defender or @angular 4.0.2, but maybe 'sha.js' file from the 'hash.js' npm package deserve to be investigated and reported to npm Inc. or further. Could be Windows Defender's fault after a virus signature update. But since sha.js has some hardcoded hexadecimal code inside, it's worth investigate.

**Comment by vicb** [comment]
seems like the project is aware of the issue https://github.com/indutny/hash.js/issues/7
really looks like a false positive.
