### ISSUE TITLE
Cannot monitor Angular2 internal http calls within iOS WKWebView

### ISSUE THREAD

**Issue by kmyllyvi** [angular/angular#15901]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On iOS app the methods of the WKNavigation​Delegate implement custom behaviors that are triggered during a web view's process of accepting, loading, and completing a navigation request.
https://developer.apple.com/reference/webkit/wknavigationdelegate
This monitoring is very useful, and often mandatory, in order to support iOS App native features with Angular 2 webapp.
I have made extensive trials and troubleshooting trying catch Angular webapp http requests and page loading on iOS native side using WKNavigation​Delegate which works for any other tested website when http loading occurs. For Angular 2 app this does not work. None of the delegate methods are triggered on iOS side.
The tested Angular2 app uses regular Angular routing and http get/post requests to the backend.

**Expected behavior**
As a hybrid app developer I would expect Angular2 app would support iOS webview wrappers in order to monitor http loading activity.

**Minimal reproduction of the problem with instructions**
It is hard to reproduce unless you have an iOS app ready for this. The explanation will have to do now I suppose.

**What is the motivation / use case for changing the behavior?**
Trying to interrupt certain webview calls on iOS app to be able to handle them natively.

**Please tell us about your environment:**
iOS app

* **Angular version:**
2.0

* **Browser:** 
iOS 9-10 WKWebView
 
* **Language:**
TypeScript / ES6

* **Node (for AoT issues):** `node --version` =

**Comment by jaumefm** [comment]
Any updates on this?

**Comment by shahul-basha** [comment]
ad

**Comment by amcastror** [comment]
Hi, were you able to solve this? thanks.

**Comment by kmyllyvi** [comment]
Hi, for me this issue is no longer relevant.

**Comment by alxhub** [comment]
Closing as this is obsolete (it concerns `@angular/http` which has been removed in favor of `@angular/common/http`).
