### ISSUE TITLE
XHR, Ajax & REST support like Restangular

### ISSUE THREAD

**Issue by nomack84** [angular/angular#1591]
Hi!
Nice update in the docs released yesterday, great work guys. 
I've been looking for the XHR module and looked throught the source code and tests and can't find anything. Also there is nothing about it in the docs. So perhaps there is nothing about this yet, isn't it? 
Another question: is there any plan to make the REST support like it is in Restangular, which is much more powerful than $ngResource?
Regards!

**Comment by pkozlowski-opensource** [comment]
@nomack84 data-access layer is cooking in a separate repo (https://github.com/jeffbcross/http-design) and here is an associated design doc: https://docs.google.com/document/d/1DMacL7iwjSMPP0ytZfugpU4v0PWUK0BT6lhyaVEmlBQ/edit#heading=h.adsv85z7smgj

There is no preview-ready implementation yet hence no docs.

If you've got other questions about directions of ng2, you can try https://gitter.im/angular/angular where core team members are commenting on those types of questions.

**Comment by nomack84** [comment]
Thanks @pkozlowski-opensource. This was exactly what I was looking for.
