### ISSUE TITLE
Animate in 4.0.X should warn about browser compatibility in animations

### ISSUE THREAD

**Issue by japalo** [angular/angular#15918]
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
web-animations.js throws error in safari 10 (probably others as well) when trying to animate on 'background' property:
```
transition('* => dim',
    animate('500ms ease-out',
        keyframes([
            style({ opacity: 1, offset: 0 }),
            style({ opacity: 0.5, background: 'rgba(0, 0, 0, 0.2)', offset: 1 })
        ])
    )
)
```

Thrown error:
`TypeError: undefined is not an object (evaluating 'b.replace') web-animations.min.js`

_If i change `background` to `'background-color'` no errors are thrown._

**Expected behavior**
If the property isn't supported for animations angular should warn about browser support.

**Minimal reproduction of the problem with instructions**
Use the above animation and trigger it in safari with `web-animations-js` imported.

**What is the motivation / use case for changing the behavior?**
Developers can spend less time worrying about browser compatibility.

**Please tell us about your environment:**
`Sierra OSx, Angular-cli`

```
  "dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "d3": "^4.6.0",
    "d3-ng2-service": "^1.6.0",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "localize-router": "^0.6.4",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.2.2",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "^2.4.10",
    "@types/d3": "^4.7.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.68",
    "codelyzer": "~2.0.0-beta.4",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-teamcity-reporter": "^1.0.0",
    "normalize.css": "^6.0.0",
    "protractor": "~5.1.0",
    "sass-loader": "^6.0.3",
    "susy": "^2.2.12",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "^2.3.0",
    "webfont": "^7.1.1"
  }
```

* **Angular version:** 4.0.X

* **Browser:** [ Safari XX ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v7.6.0

**Comment by skreborn** [comment]
I believe this is out of scope for Angular. There is a [currently open issue over at web-animations-js](https://github.com/web-animations/web-animations-js/issues/80) that addresses this exact issue. I suggest you follow and/or join that conversation.

**Comment by japalo** [comment]
Oh, couldn't find that one while searching for solutions. I guess we'll see what they come up with over there.
