### ISSUE TITLE
`ngOnInit` is called multiple times in production mode if an error happens in it

### ISSUE THREAD

**Issue by tbosch** [angular/angular#15925]
This is because we are setting `ViewState.FirstCheck` not until a view has been fully change detected.

Solution:
```
detectChanges(view: ViewData) {
  view.wasFirstCheck = view.firstCheck;
  view.firstCheck = false;
  // dirty check all directives, use view.wasFirstCheck instead of view.firstCheck.  
}
```

**Comment by p0rsche** [comment]
I'd like to subscribe to this issue too. Second call to OnInit effectively hides the source of error.
