### ISSUE TITLE
No casting in template breaks code working with angular2

### ISSUE THREAD

**Issue by itsnotvalid** [angular/angular#15921]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[*] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Pre-angular 4: If an object has no proper type, for example AbstractControl to specific control member. e.g FormArray has property controls but no actual property on abstract class. The current suggested workaround is to use get('property-name'), but this would not give any type checking.

**Expected behavior**

Instead, it should be done with actual casting of the object to the actual type being used.

**Minimal reproduction of the problem with instructions**

```
<div *ngFor="let question of form.get('questions').get('controls'); let i=index">
</div>
```
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

(ngc build with aot)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =   
v7.7.2

**Comment by tbosch** [comment]
We are working on this, see https://github.com/angular/angular/issues/12398.
