### ISSUE TITLE
ngUpgrade: scope.$applyAsync and scope.$digest should always enforce angular zone

### ISSUE THREAD

**Issue by ukrukarg** [angular/angular#15928]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When scope.$applyAsync() and scope.$digest() are called from outsize of angular zone, they don't make sure to go back into angular zone.

**Expected behavior**
$applyAsync and $digest both make sure to go back into the zone if called from outside of it.

**Minimal reproduction of the problem with instructions**
Bug was reproduced in the troubleshooting session with @mhevery 
In general you need to register a callback to an async event before angular is fully bootstrapped.

**What is the motivation / use case for changing the behavior?**
The error causes very hard to reproduce change detection problem in hybrid app.

**Please tell us about your environment:**
Ubuntu, VS code

* **Angular version:** 4.1.0-beta.0

* **Browser:**
Chrome, was broken so severely I didn't bother testing in others.
 
* **Language:** TypeScript

**Comment by mhevery** [comment]
@petebacondarwin what do you think?

**Comment by petebacondarwin** [comment]
Hmm I guess we could monkey patch this but it is ironic that on the other side there are people trying to escape the zone in digests...

**Comment by gkalpak** [comment]
I suspect this was an issue with bootstrapping AngularJS outside the zone (e.g. in the promise returned by `bootstrapModule()`). This should not be an issue when bootstrapping AngularJS inside the zone (e.g. in the Angular module's `ngDoBootstrap()` method).
