### ISSUE TITLE
Unable to get property 'apply' of undefined or null reference

### ISSUE THREAD

**Issue by Sevensnake** [angular/angular#15938]
Have this issue been resolved. I am currently having this issue also.
This happens only in IE.   AngularCLI latest install.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
