### ISSUE TITLE
language-service: Identifier 'valid' is not defined. 'NgForm' does not contain such a member

### ISSUE THREAD

**Issue by kemsky** [angular/angular#15930]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

![71c6a-clip-158kb](https://cloud.githubusercontent.com/assets/3826972/24972942/c5dc4536-1fc5-11e7-8258-84edaadd9510.png)

**Expected behavior**
No error.

**Please tell us about your environment:**
Intellij Idea 2017.1

* **Angular version:** 4.0.2

 
* **Language:** [TypeScript 2.1]

**Comment by kemsky** [comment]
It seems that #15460 did not fix this error.

**Comment by chrisbmoore** [comment]
I don't know if some docs are wrong, but I use ...#myForm="ngForm"...  and later ...**myForm.form.valid**... and it appears to work.

**Comment by kemsky** [comment]
Works in 4.1.0
