### ISSUE TITLE
aio: fix live-server styling

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#15935]
See https://github.com/angular/angular/pull/15911#discussion_r111222887

**Comment by sjtrimble** [comment]
I believe we no longer need this - the intent is for the live-example to take up the full width of the screen.

**Comment by gkalpak** [comment]
[My comment][1] is still not addressed, so I think this is still relevant.

[1]: https://github.com/angular/angular/pull/15911#discussion_r111222887

**Comment by petebacondarwin** [comment]
To make it easier to track:

---

The structure of the contents of a `<live-example>` is determined [here][1]. Relying on the exact structure for styling is not a good idea, because it is likely to change (and in fact it so happens that #15887 will replace the `<div>` in the current structure).

What we should do instead, is identify what exactly it is that you want to style and add a class on it, so that we can preserve the styling even if we move things around.

(If the Angular stuff on the [live-example template][1] doesn't make sense to you, let me know :wink:)

[1]: https://github.com/sjtrimble/angular/blob/71365634c80420bf4e424f84e65ec52e364532c8/aio/src/app/embedded/live-example/live-example.component.html

**Comment by petebacondarwin** [comment]
@gkalpak do you want to fix this?

**Comment by gkalpak** [comment]
Will do.

**Comment by gkalpak** [comment]
Actually, the `live-example > div:first-child` style l=no longer has any effect (because the structure has changed). So, if (as @sjtrimble says) _"the intent is for the live-example to take up the full width of the screen"_), we just need to remove that redundant style :smiley:
