### ISSUE TITLE
Routes with .do extension 

### ISSUE THREAD

**Issue by RameshNeelam** [angular/angular#15945]
In my angular2 application i have two components  (profile / projects) so my routes  are like 
 { path: 'profile', component: ProfileComponent },
 { path: 'projects',        component: ProjectsComponent } 

and i need to integrate angular 2  in existing struts application where all urls are having .do as url extension 

so i have updated my routes to 
 { path: 'profile.do', component: ProfileComponent },
 { path: 'projects.do',        component: ProjectsComponent }   

when i launch my application directly with localhost:3000/profile.do    i am getting  Cannot GET /profile.do   error  where as when launch application using localhost:3000/ and click hyper link  <a routerLink="/profile.do" routerLinkActive="active">my profile</a> it works 
 
 any suggestion or solution to access my application with localhost:3000/profile.do  url

**Comment by vicb** [comment]
Your question sounds like a support request - probably a bad server configuration

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
