### ISSUE TITLE
AOT Compilation issue getting Error: Error encountered resolving symbol values statically. Calling function 'TranslateModule'

### ISSUE THREAD

**Issue by Sarvesh19** [angular/angular#15949]
I am trying to compile AOT but getting this issue even though i tried replacing 

TranslateModule.forRoot(TRANSLATE_LOADER)

export function translateLoader(http: Http): TranslateStaticLoader {
	return new TranslateStaticLoader(http, (window as any).rest + "textmodules", ".json");
};
const TRANSLATE_LOADER: any = {
	provide: TranslateLoader,
	useFactory: translateLoader,
	deps: [Http]
}
in my app.module.ts

**Comment by tbosch** [comment]
Hello,
we need a reproduction for this to investigate (e.g. create a branch on Github).

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
