### ISSUE TITLE
Template variable is never set when any containing element uses *ngIf

### ISSUE THREAD

**Issue by OndraZizka** [angular/angular#15948]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

*ngIf makes a template reference not work.

```
<input #foo *ngIf="..."> ... </p>
{{ foo || foo.value }}
```
This is always null because foo is null, regardless of the value. If `*ngIf` is not used, it works fine.

**Expected behavior**
The template variable should be seit if `*ngIf` evaluates to `true`.
Or it should be documented in Template Syntax guide.

**Minimal reproduction of the problem with instructions**

```
Type "hello" here:
<input #confirmInput type="text">
Input {{confirmInput}}, value {{confirmInput && confirmInput.value}}
<button #yes type="button" [disabled]="confirmInput && confirmInput.value.trim() != 'hello'">Go ahead</button>

**What is the motivation / use case for changing the behavior?**
To be able to create basic forms functionality with Angular templates.

**Please tell us about your environment:**
HTML 5, latest Chrome/Firefox, the rest is not relevant

* **Angular version:** 2.4.9

* **Browser:** Chrome 57 | Firefox 52
 
* **Language:** TypeScript 2.2.1

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
can you please provide a reproduction with the expected and observed behavior, here's a template https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
