### ISSUE TITLE
Redo bootstrapping logic

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1594]
```javascript

ng
  .platform([Cookies])
  .createApp([bind(ExceptionHandler).toClass(MyExceptionHandler])
  .loadComponent(MyComponet, [bind(MySerivice].toClass(MyService)]


class Platform {
  dispose()
}

class Application {
  componentRef:ComponentRef;
  dispose();
  whenReady() {
  }
}

class ComponentRef {
  dispose()
}

bootstrap(Type, cmpBind, appBind, pltformBind):Application {
  var platform = Platform.create(pltformBind);
  var app = platform.createApp(appBind);
  var componentRef = app.loadComponent(ComponentRef);
  return app;
}


bootstrap(MyApp).whenReady((rootComponent) {
  rootComponent.init();
});

```

**Comment by mhevery** [comment]
Please add your thoughts and edit requirements as you see fit: @tbosch @rkirov

**Comment by tbosch** [comment]
I think `Application` should not contain `ComponentRef` as people might call `component.destroy()`, and then they have a weird state of a still ok application with a destroyed root component.
Instead, we might just expose the component instance on `Application`.

**Comment by vicb** [comment]
+1 for `whenReady()` instead of returning a `Promise`, should we have a `whenError()` ? _or something like `whenReady(succesCb, errorCb)`_

Returning a `Promise` is not a great idea because:

```js
function main() {
  // here we are in the root zone
  bootstrap().then(() => {
    // .then() is called in the root zone, hence the cb will be executed in the root zone
    // while we want it to run in the Angular inner zone
  });
}
```

Hopefully people won't come with smart things as 
```js
var ok, ko;
var p = new Promise((rs, rj) => {
  ok = rs;
  ho = rj;
});

bootstrap(...).whenReady(ok).whenError(ko);

p.then(() => {
  // root zone :(
});
```

**Comment by tbosch** [comment]
For serverside rendering, it would be nice to separate compiling from instantiating in the API as well, as we would compile only once but instantiate on every request.

**Comment by yjbanov** [comment]
Marking as blocked by https://github.com/angular/angular/issues/2304 just so we work on these issues sequentially. Both are messing around the same code.

**Comment by tbosch** [comment]
I think we should also split bootstrap further into a compile and create call. 
This is e.g. very interesting for benchmarks, or also for serverside rendering, which would compile only once but create the view instances multiple times.

**Comment by vsavkin** [comment]
As far as I understand, the following means append MyService to the list of bindings that MyComponent provides: `.loadComponent(MyComponet, [bind(MySerivice].toClass(MyService)]`.

**Comment by gdi2290** [comment]
:+1: for more control over the binding. For universal we need to provide a Node version of `BrowserXhr` for Http (also Router). When users include `httpInjectables` we can replace the default bindings are for the correct environment. (this might just be solved with platformBindings)

I also think renderer should be separate. Consider this example of a pending react release
```es6
var React = require('react');
var ReactDOM = require('react-dom');

var MyComponent = React.createClass({
  render: function() {
    return <div>Hello World</div>;
  }
});

ReactDOM.render(<MyComponent />, node); // previously React.render(<App>, node)
```
now the benefit there is that they're able to now "fix" their server rendering problem by allowing users to use `var ReactServerDOM = require('react-server-dom');` which would allow react to use the same strategy that Angular uses for faster initial loads.

I also need a bit more control over the Renderer so perhaps the separation could allow for that. If we separate compile/create steps (as Tobias mentioned above) that will allow for more optimization on server/client. One example for the client is being able to debounce inserting of the client view, when a user is typing, until they hit an action (`enter` key). While this is not a problem currently for Desktop we do see this being a problem for mobile users as the keyboard toggles on and off during the transition of input focus.

```es6
bootstrap(MyComponent, bindings) {
  var app = ng.
    platform([ Cookies ])
    createApp(MyComponent, [ overrides ]);
  return renderer.
    loadComponent(app).
    compile(/*DOM.querySelector(DOM.defaultDoc(), app.selector)*/) // I much rather provide the root element rather than having DomRenderer query for it and providing the document
}
```

**Comment by yjbanov** [comment]
One thing that would be great to see in our bootstrap API, given our focus on code size and load time, is a way to specify the Angular features you want to enable in your app. This should be done using a method that would allow a tree-shaker to not include unused features. Here's a strawman:

```typescript
ngBlank  // start with no features
  .platform([Cookies])
  .enableForms()  // add features
  .enableHttp()
  .enableI18n()
  .enableTestability()
  .createApp(...);
```

The calls to `enable*` methods would be fully typed allowing a tree-shaker (Closure, dart2js, etc) get rid of unused code. The `enable*` methods themselves would simply populate the DI module with relevant bindings.

**Comment by alxhub** [comment]
Bumping to alpha-36. I am working on a design proposal and will link here this week for comments.

**Comment by mhevery** [comment]
@alxhub Do you have an update? or a design proposal you mentioned?

**Comment by alxhub** [comment]
Here is my design for Angular bootstrapping. Note that this is the "long form" for bootstrapping multiple apps on a single page. The existing `bootstrap()` function should continue to work for simple apps.

## Non-web worker app:

```
// Bindings for non-web worker apps.
var domAppBindings = ListWrapper.concat(
    appCommonBindings(), appDomBindings());

// The platform holds bindings which are singletons on a browser page.
var platform = ng.platform(rootBindings);

// First application.
var appFoo = platform.application(ListWrapper.concat(domAppBindings,
    [/* first application bindings */]));

// With two root components:
appFoo.root(AppFooComponent).then((ref: RootComponentRef) => {
  // This component is ready. This callback runs in the application zone.
});

appFoo.root(AppFooSideComponent).then((ref: RootComponentRef) => {
  // Second component for this app is ready.
});

// Second application (independent zone, change detection, compiler, etc):
var appBar = platform.application(ListWrapper.concat(domAppBindings,
    [/* second application bindings */]));

appBar.root(AppBarComponent).then((ref: RootComponentRef) => {
  // Second application is ready!
});
```

## Web worker app (running in the web worker thread):

```
// Bindings for web-worker apps.

var bus = /* Somehow get a MessageBus */;

// Web-worker apps need bindings that are initialized asynchronously,
// because that initialization only happens after a setup event is received.
ng.platform(rootBindings) 
  .asyncApplication(() => {
    var completer = PromiseWrapper.completer();
    var subscription: any;
    var emitter = bus.from(SETUP_CHANNEL);
    subscription = ObservableWrapper.subscribe(emitter, (message: StringMap<string, any>) => {
      ObservableWrapper.dispose(subscription);
      // Now bindings can be determined based on the setup message.
      var appWorkerBindings = ListWrapper.concat(
        appCommonBindings(), appWebWorkerBindings(bus, message));
      completer.resolve(ListWrapper.concat(appWorkerBindings,
          [/* application bindings */]));
      });
      ObservableWrapper.callNext(bus.to(SETUP_CHANNEL), "ready");
      return completer.promise;
  })
  .then((app: ApplicationRef) => app.rootComponent(WebWorkerAppComponent))
  .then((ref: RootComponentRef) => {
    // Web worker application is ready!
  });
```

Unfortunately, due to my absence last week I don't think I'll be able to make the M36 target, so I'm going to push this back to M37. This should be the last delay - I should have a PR ready for evaluation & review soon.

**Comment by vicb** [comment]
> appFoo.root(AppFooComponent).then((ref: RootComponentRef) => {
  // This component is ready. This callback runs in the application zone.
});

Not sure what you mean by "application zone" ?

The cb should run inside an NgZone so that asynchronous code triggers the change detection - which I don't is possible is `appFoo.root(AppFooComponent)` returns a Promise because the code would be executed in the same zone where `then()` gets called.

**Comment by alxhub** [comment]
The application zone is the `NgZone` associated with the application, and shared among the application's root components.

I don't know too much about how zones work, but `bootstrap()` returns a `Promise<ApplicationRef>` - I'm not changing this mechanism, only the type of the `Promise`.

I'll do some research to see if that callback is broken, though.

**Comment by vicb** [comment]
@alxhub see [this comment](https://github.com/angular/angular/issues/1594#issuecomment-97728561) for more details - returning a `Promise` would run the callback in the calling zone (ie outside of angular / NgZone).

**Comment by jteplitz602** [comment]
WebWorker design looks good to me.

**Comment by tbosch** [comment]
@alxhub Could you change this so that the long form as an explicit `compile` and `run` phase? We need this for serverside applications where we compile only once (which is asynchronous), and then `run` on every request (sync).

**Comment by PascalPrecht** [comment]
> // With two root components:
appFoo.rootComponent(AppFooComponent).then((ref: RootComponentRef) => {
  // This component is ready. This callback runs in the application zone.
});

> appFoo.rootComponent(AppFooSideComponent).then((ref: RootComponentRef) => {
  // Second component for this app is ready.
});

What's the use case for having two root components in an application? Wasn't the whole idea that an application is always the root component itself?

**Comment by mhevery** [comment]
@PascalPrecht you may want to run several applications side by side. Also for ng-upgrade we need the ability to bootstrap a lot of child applications.

**Comment by btford** [comment]
@alxhub – did this land? Can this be closed?

**Comment by mhevery** [comment]
Yes this landed.
