### ISSUE TITLE
docs(aio): Style-guide: add "fields referred inside a template should be declared public"

### ISSUE THREAD

**Issue by wKoza** [angular/angular#15951]
Why : 
- When we use AOT, all fields referred inside a template should be declared public
- In the near future, the AOT should become systematic

Closes : #11978

**Comment by Toxicable** [comment]
That issue is already closed.
This isn't a style issue, this is just how accessibility modifiers work; the view is once class and your related component class is another, therefore the view cannot access private classes of another class

**Comment by jenniferfell** [comment]
for categorizing issue
filename=https://angular.io/guide/aot-compiler

**Comment by jelbourn** [comment]
@alxhub do we have compiler/language service errors about using private members in templates today? IMO we should revisit this now that generated template code lives in the same file as the component which would let you reference private members in TypeScript by itself.

**Comment by mgechev** [comment]
I suggest keeping this as a tooling warning/error since we may change the compiler behavior over time. Given that we'll enforce this at build/development time, I'd suggest to keep it outside the scope of the style guide, which mostly targets style/linting errors.
