### ISSUE TITLE
Router/RouterLink nodes leaks

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#15959]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

There is strange node leaks for simple example with only one router link on each page

**Minimal reproduction of the problem with instructions**
- load example http://plnkr.co/edit/x6Jo42UOM2XFivzTEyDv?p=preview
- open chrome devtools, timeline, start recording
- make 20-30 clicks on links
- collect garbage (timeline tab button)
- stop timeline recording, display memory graphs
- see nodes leak

![image](https://cloud.githubusercontent.com/assets/1944061/25017046/f8495aa2-208a-11e7-8cfb-2d2e02d5ec30.png)

* **Angular version:** 4.0.2

Browser: Chromium Version 57.0.2987.98 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by wKoza** [comment]
I doesn't reproduce your scenario. In my case,   I have this result :
![capture d ecran 2017-04-13 a 20 16 38](https://cloud.githubusercontent.com/assets/11403260/25018071/4c766dae-2086-11e7-8b2f-141eb96b5c13.png)

**Comment by tytskyi** [comment]
Does not reproduce on Windows - Chrome 57.0.2987.133 (64-bit)

@artaommahe do you use any debuggers for Angular, Augury or something?

Could you try in incognito mode / without extensions?

**Comment by artaommahe** [comment]
@wKoza @tytskyi disable-enable extensions and looks like i'ts ublock issue.. looks strange :(
