### ISSUE TITLE
"pure" components

### ISSUE THREAD

**Issue by Darkein** [angular/angular#15957]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
sorry if this request has already been asked, but i didn't find any similar topic.

i have a `parentComponent` and and a `childComponent`. my `parentComponent `hold an `elementModel`, passed to my childComponent using an input property. When i modify my `elementModel `inside my `childComponent`, it's modified inside my `parentComponent` too

**Expected behavior**
`elementModel` should be modified only in the `childComponent`.

**Plunker**
https://plnkr.co/edit/T4PslBXCusL8nOZbeM9Z?p=preview

**What is the motivation / use case for changing the behavior?**
- The components must be independents between each others, and stateless. We have to use properties for the inputs and events for outputs, but it's still possible to update an element directly (which is a bad practice :( ).
- If we want to modify our element inside our child without changing the parent element, we must clone it ourselves.
- Finally, if we have a list of elements and if an element is added to this list, the `ngOnChange `(or a setter) is not called in our `childComponent`

**Angular version:** 2.X, 4.X
**Browser:** [all] 
**Language:** [all]

**Comment by mohammedzamakhan** [comment]
Can you please provide a working plnkr

**Comment by Darkein** [comment]
i've updated my first post. I can create another plunker with a list of elements, but it's the same behavior.

**Comment by mlc-mlapis** [comment]
The explanation is that you pass through a ref to you model.

**Comment by Darkein** [comment]
yes i know, but for me Angular should create itself a new element, like react does.

**Comment by mlc-mlapis** [comment]
Ok, but the ref is still the ref, so pass an immutable structure.

**Comment by Darkein** [comment]
I think immutable.js is just a way to compensate the weakness of angular.
My object is necessarily passed by reference, so angular could copy this object when the child got it.

**Comment by mlc-mlapis** [comment]
But it is Angular principle how `onPush` strategy works, so you are asking for what exactly?

**Comment by Darkein** [comment]
i just want to break the link(the references) between the components.

To be honest i've played with react a few weeks ago and i really loved the way they managed the inputs of their components. When a child got an input from a parent, it get an object whose can be used/modified without any impacts to the rest of the site.

With angular you have to think "ah yes, i can't touch the input because it'll modify the parent" even if the child is "in theory" independent.

do you understand what i mean?

**Comment by mlc-mlapis** [comment]
Fine. But I am not sure if there is something to change. There are other consequences related to. And you have a bit different (= not the same way as in React) way (somehow opposite to React) how to get what you want. I do not know all related parts that could be affected by your supposed change and all +/-.

**Comment by Darkein** [comment]
Yes i agree, react and angular are 2 différents philosophies. But the way they manage input/output between the components is very close to what is done in web components.

So, why not? it can just be considered, maybe it could be an improvement, and maybe it's not so hard to implements :)

**Comment by alxhub** [comment]
@Darkein, if you pass a reference to the same object to two different components, then changing the object from one of the references will be visible on the other reference, because it's the same object. `OnPush` won't help as that only affects when detection happens.

If you want your component to have a different mutable model, you need to copy the object before you pass it to the child component. Deep copying of an object is a non-trivial problem and something best handled by your application, not Angular.

**Comment by tytskyi** [comment]
Hi @Darkein React does not work as you expect. I created a simple demo that demonstates it: http://plnkr.co/edit/IqpzE7QEI9H1FrKOj6ak?p=preview
Open console and observe that child component changes parent state. 

It turns that it works the same way as Angular, the only difference it's that **React does not re-render**. Meanwhile Angular does. 

It means it's even worst because it shows wrong value. And if you make logic in parent that depends on thinking that it works as you expect than it may appear in bugs that are hard to hunt.

**Comment by mlc-mlapis** [comment]
@Darkein I supposed that what you said is the fact. Because of demo of @tytskyi, can you try to make some research and confirm his conclusion also from your side? I think that it is an important factor for all of us. Thanks.

**Comment by Darkein** [comment]
okay, i will make some research and tests to be sure i'm not saying
something wrong :)

Le jeu. 13 avr. 2017 à 22:34, Miloš Lapiš <notifications@github.com> a
écrit :

**Comment by Darkein** [comment]
Well it's true, i said something wrong.
The inputs in Angular and React are a few differents.
In react, all the inputs are stored in one object (props), and they are **readonly** (you will get an error if you try to modify it). If you need to edit the element , you have to create your own variable and make a copy of your prop.
```
var element1 = {...props.element1};
var element2 = {...props.element2};
```

In angular, your own variable **is** your input. But because it's an input you must not edit it directly, and **you have no error if you try**. You have to create another variable, or play with getter/setter

```
private _element1;
  public get element1(){
    return this._element1;
  }
  @Input()
  public set element1 (e) {
    this._element1= {...e};
  }
private _element2;
  public get element2(){
    return this._element2;
  }
  @Input()
  public set element2(e) {
    this._element2= {...e};
  }
```

So i think angular must at least make the inputs read-only just to prevent the edition of it.
 And for the getter/setter boilerplate when I want to copy my input, I suppose a decorator `InputCopy` whose could encapsulate this code should be enough :)

**Comment by mlc-mlapis** [comment]
OK. Thanks for your observations. The only thing what I don't understand is why you are so fixed to the idea that an input should be immutable by default even if you pass it by a ref. They are just two sides of the same coin. So can you look at it from the opposite view? Then if you pass an object by its ref and you don't want to allow mofification from a child then pass immutable copy of it.

**Comment by tytskyi** [comment]
@Darkein `@InputCopy()` can be good option. However my guess is that people will use it by default for big objects and then claim that "Angular is slow".

**Comment by Darkein** [comment]
@tytskyi i agree with you, the perfomances could be really bad. I should test it with a shallow copy (not deep)

@mlc-mlapis the `input` must never be modified, so technically i have to pass an immutable each time. I tell this because i learned Angular 2 to my colleages, and lots of them edit the `input` and don't understand why the application their applications were broken.

**Comment by mlc-mlapis** [comment]
@Darkein ... I supposed that answer. 😄  Now a new object ref means on `@Input()` and `onPush` strategy that there is a change and CD should run on that component and its children. If `@InputCopy()` decorator would be applied on the component, then a new object ref on `@Input()` would also mean that another new copy of that object will be created on CD?

**Comment by Darkein** [comment]
yes that's true. So if we modify our child input and after the parent element, the child will be overwritten. It's more complicated than i though ^^'

**Comment by tytskyi** [comment]
Meanwhile it would be helpful to have something like `@Input({warnWhenMutate: true})`. Which will `console.warn` only in development mode. That will help to avoid mistakes where mutations are not expected

**Comment by Darkein** [comment]
Good idea :)
