### ISSUE TITLE
How to create a service in angular2 ? 

### ISSUE THREAD

**Issue by MeriemBo** [angular/angular#15954]
I m creating an app with angular2 , the app is synchronized with Odoo , I was able to connect to odoo server and fetch data using this :

import { Component, OnInit } from '@angular/core';
import { OdooRPCService } from 'angular2-odoo-jsonrpc';
import { Http} from '@angular/http';
@Component({
selector: 'app-root',
templateUrl: './app.component.html',
styleUrls: ['./app.component.css'],
providers: [OdooRPCService]
})
export class AppComponent implements OnInit{

projectList;
ngOnInit(){
let self = this;
self.projectList = [];
self.odooRPC.init({
odoo_server: "https://demo9"
});
self.odooRPC.login('DB', 'admin', 'admin').then(res => {
console.log('login success');
}).catch( err => {
console.error('login failed', err);
})
self.odooRPC.call('project.project', 'search_read', [], {}).then((projects:any) => {
if(projects){
self.projectList = projects;
}
})
}
constructor( private odooRPC: OdooRPCService){
}}

but since the app is growing , I wanted to creat a service that will provide data for the other components:
ProjectService.ts :
import { Injectable } from '@angular/core';
import {Http, Response} from '@angular/http';
import {Observable} from 'rxjs';
import 'rxjs/Rx';
import 'rxjs/add/operator/map';
import {ProjectList}from'./projects';
import { OdooRPCService } from 'angular2-odoo-jsonrpc';

@Injectable()
export class ProjectsService {
public projectList;
constructor( private http:Http, private odooRPC: OdooRPCService) {}

getProjects(){
let self = this;
self.projectList = [];
self.odooRPC.init({
odoo_server: "https://demo"
});
self.odooRPC.login('DB', 'admin', 'admin').then(res => {
console.log('login success');
}).catch( err => {
console.error('login failed', err);
})
self.odooRPC.call('project.project', 'search_read', [], {}).then((projects:any) => {
if(projects) {
self.projectList = projects;
})
}
}}

and I import the service in app.module.ts :

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';
import {ProjectsService} from "./projects.service";

@NgModule({
declarations: [
AppComponent
],
imports: [
BrowserModule,
FormsModule,
HttpModule
],
providers: [ProjectsService],
bootstrap: [AppComponent]
})
export class AppModule { }

and called the service from app.component.ts :

import { Component,OnInit} from '@angular/core';
import {ProjectsService} from "./projects.service";

@Component({
selector: 'app-root',
templateUrl: './app.component.html',
styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {

constructor(private projectsservice: ProjectsService) {}

ngOnInit() {

let projectList;
this.projectsservice.getProjects();

}

and I also provided a model :

projectList.ts :
export class ProjectList {
constructor( public name : string , public id : number ){}
}

but my code won't compile and there's something wrong with my projectlist.service.ts , I get this error TSS1128 : declaration or statement expected , I m a beginner and I don't know if the service is written correctly. any help ?

**Comment by wKoza** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
At least the right formatting can give a chance to read that at all!
