### ISSUE TITLE
Trigger for animated routes cannot be disabled by setting host-bound property to false

### ISSUE THREAD

**Issue by dmgudeman** [angular/angular#15965]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am implementing route animations and need to be able to turn on or off the animations. It is my
understanding that the trigger is bound to the component using HostBinding and this can  be disabled by setting the property to false.  Currently it does not matter if the property resolves to true or false or indeed is never set at all. The only way I can get it to be disabled is by commenting out the line.

**Expected behavior**
When using HostBinding with an animation trigger if the property evaluates to false the animation will be disabled.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/dnofDqzZcTNdUm02LOa9?p=preview

**What is the motivation / use case for changing the behavior?**
I want to slide the component in from the left if it slide out to the left and slide it in from the right if it slid out to the right. 

**Please tell us about your environment:**
macOS Sierra v 10.12.4, visual studio, webpack with an angular-cli.

* **Angular version:** 2.0.X
Angular version: 4.0.1

* **Browser:**
Version 57.0.2987.133
 
* **Language:**
ES5

* **Node (for AoT issues):** `node --version` =   7.1.0

**Comment by matsko** [comment]
Unfortunately it does seem like setting the binding value to false will disable the animation, but this isn't the case. `false` is still seem as a value state to go to (and since `:enter` and `:leave` work as `void => *` and `* => void` under the hood this means that they will match it).

So the solution here is to add an empty transition that is matched when `false` is used.

```ts
trigger('routeFadeState', [
  transition('* <=> false', []), // this will ignore all animations that have false as the value
  transition(':enter', [
  ])
])
```
