### ISSUE TITLE
docs(aio): Provide access to previous versions of API Reference docs

### ISSUE THREAD

**Issue by diminutivesloop** [angular/angular#15966]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Expected behavior**
The Angular website should provide easy access to older versions of the [API Reference docs](https://angular.io/docs/ts/latest/api/).

**What is the motivation / use case for changing the behavior?**
Without this feature the docs are unreliable for anyone who isn't using the latest version.

**Comment by gkalpak** [comment]
Thx for reporting. This is already on our roadmap.
Tracked in #14962.
