### ISSUE TITLE
Ngc fails when UpgradeModule is imported in NgModule in 4.0.1

### ISSUE THREAD

**Issue by davityle** [angular/angular#15962]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I might be a unicorn, but after upgrading to angular 4.0 any `NgModule` that imports `UpgradeModule` fails with this error 
```
Unexpected value 'UpgradeModule in unicorn/node_modules/@angular/upgrade/static/index.d.ts' imported by the module 'UnicornModule in unicorn/unicorn.module.ts'. Please add a @NgModule annotation.
```

**Expected behavior**
Ngc should recognize that there is an `@NgModule` on the `UpgradeModule`. (even though it is using a .d.ts to resolve the dependencies)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
4.0.1 (You should update the boilerplate ^)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by gkalpak** [comment]
Do you have a reprodution (e.g. a repo we can checkout and reproduce the error)?
We have a minimal ngUpgrade example [here][1] (using v4.0.1) and `ngc` seems to work fine.

[1]: https://github.com/angular-upgrade-examples/todo-app

**Comment by davityle** [comment]
I upgraded to 4.0.2 and was able to fix it
