### ISSUE TITLE
bug: Injectables in a DynamicComponent aren't recognized

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1596]
- **Works**: A Component with an injectable: http://plnkr.co/edit/4uUq7Hqtk43ZHEQMbeM4?p=preview

- **Broken**: A DynamicComponent with an injectable: http://plnkr.co/edit/lJyRdelIxhInuGn5blnl?p=preview

**Comment by mhevery** [comment]
Is this a dup of #1566 ?

**Comment by ajoslin** [comment]
Yes.

**Comment by pkozlowski-opensource** [comment]
Ok, closing as duplicate of #1566
