### ISSUE TITLE
bug(AOT): @HostBinding with variable prefixed `__` does not work

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#15967]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When you use `@HostBinding` with a variable prefixed with `__` the HostBinding will not be applied when running in AOT

**Expected behavior**
The host binding to be applied

**Minimal reproduction of the problem with instructions**
1. Make new CLI project
2. delete `app.component.ts`
3. replace the contents of `app.module.ts` with:
```
import { BrowserModule } from '@angular/platform-browser';
import { Component, NgModule, HostBinding } from '@angular/core'
@Component({
  selector: 'app-root',
  template: `Component`,
})
export class App {
  @HostBinding('style.background-color') __dosentWork = 'red';
  @HostBinding('style.font-size') _works= '200%';
  @HostBinding('style.color') alsoWorks= 'blue';
}
@NgModule({
  imports: [BrowserModule],
  declarations: [App],
  bootstrap: [App]
})
export class AppModule { }
```
4. run `ng serve`
5. observe that font-size = 200%, color='blue', background-color='red'
6. run `ng serve --aot`
7. observe that font-size = 200%, color='blue' and background-color is not red

* **Angular version:** 4.0.2

* **Browser:** [  Chrome 57  ]
 
* **Language:** [all | TypeScript 2.2.2 ]

* **Node (for AoT issues):** `node --version` =   6.9.4

~~Looks like this might have something to do with it 
https://github.com/angular/angular/blob/540581da3e58924f3a8526b66bb8f5f727cb38d2/packages/language-service/src/completions.ts#L391~~
Credit to @superamadeus for pointing this out

**Comment by chuckjaz** [comment]
The reference above to `completions.ts` is not used during AOT. It is only used in the language service to filter the completions supplied in the editor.

**Comment by Toxicable** [comment]
@chuckjaz ,oh my mistake, I am rather unfamiliar with the compiling side of the code base

**Comment by pkozlowski-opensource** [comment]
This seems to be fixed in Angular v9 running ivy: https://ng-run.com/edit/bc6RoDut6BG1nUorTsCJ?open=app%2Fapp.component.ts
