### ISSUE TITLE
markAsTouched behaves differently depending how called

### ISSUE THREAD

**Issue by ukrukarg** [angular/angular#15961]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
```

**Current behavior**
AbstractControl.markAsTouched behaves differently depending how called. It says it will mark descendants as touched, but it does it only sometimes (when action triggered from within the form).

**Expected behavior**
markAsTouched behaves the same way no matter how called.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/QxPzhTbiUuyNV3kcrY9C?p=preview
First button is inside the `<form>`: works as advertised.
Second button is outside the `<form>` doesn't mark fields as touched.

**What is the motivation / use case for changing the behavior?**
There is no way to know if form is submitted when using reacitve forms. So my md-errors are not shown when users tries to submit the form. Instead I want to mark all fields as touched to force md-errors to be shown. Because of this bug, I need to do this recursively.

**Please tell us about your environment:**
Ubuntu, VS code

* **Angular version:** 4.1.0-beta.0

* **Browser:** Chrome
 
* **Language:** TypeScript

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
Your are confusing how touched works, take a look at this example:
https://plnkr.co/edit/QxPzhTbiUuyNV3kcrY9C?p=preview

**Comment by tytskyi** [comment]
@ukrukarg i think @Toxicable meant this: https://plnkr.co/edit/yBfj0gw106yAHJXTYVrk?p=preview (observe no click handler - it is touched because you touched the button inside form)

**Comment by kara** [comment]
It looks like `markAsTouched` is working as intended. If you look at the docs [here](https://angular.io/api/forms/AbstractControl#markAsTouched), it is intended to set all *ancestors* as touched and it does so. If you're still having specific issues with error display with `md-error`, I'd file that in the material2 repo.
