### ISSUE TITLE
Inline template error reporting is not showing JS errors in some cases

### ISSUE THREAD

**Issue by rmanuel200** [angular/angular#15973]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Inline template error reporting is not showing JS errors in browser when bad code is nested under an element with [formGroup] and *ngIf. This was working with previous version of angular 2.

**Expected behavior**
Inline template error reporting should work as it used to inside [formGroup]

**Minimal reproduction of the problem with instructions**
xyz below is undefined

Shows js error in browser:
&lt;p *ngIf="xyz.test">&lt;/p&gt;
&lt;form *ngIf="searchForm" [formGroup]="searchForm"&gt;

Show no JS error in browser but app is broken from JS error:
&lt;form *ngIf="searchForm" [formGroup]="searchForm"&gt;
   &lt;p *ngIf="xyz.test">&lt;/p&gt;

This also shows no JS error in the browser but the app is broken from JS error:
 &lt;div *ngIf="searchForm"&gt;
     &lt;p *ngIf="xyz.test">&lt;/p&gt;
 &lt;/div>

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Win 10

* **Angular version:** ~4.0.0

* **Browser:** Chrome, any browser
 
* **Language:** TypeScript ~2.1.0

**Comment by Toxicable** [comment]
Can you please make a minimal reproduction of your issue in a plunkr so we can investigate
Here's a template to get you started: https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by kemsky** [comment]
I can confirm that. Component (actually a popup) was created dynamically. It took some time to realize that one of the bindings throws NPE, but console was empty all the time. Unfortunately i can not create plunkr.

**Comment by tbosch** [comment]
Yes, this is a known issue and we are working on it: https://github.com/angular/angular/issues/15988

**Comment by rmanuel200** [comment]
Ok looks like this happens when the form is built in ajax promise
