### ISSUE TITLE
Change detection is not automatically triggered after upgrading to 4.0.2

### ISSUE THREAD

**Issue by florian-wahl** [angular/angular#15971]
Hello everyone,

**I'm submitting a ...** 
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

### Previously

After updating from Angular 2.4.2 to Angular 4.0.1, the API response does not trigger the change detection anymore. My API send the response, but the template of my component is not updated (even though the data is correctly received and the variable is updated).
Nothing changed between both versions in my code; I'm only working on the migration between the versions.

As of now, the only way I found to patch this problem is by manually triggering the change detection by calling *ChangeDetectorRef.detectChanged();*

### UPDATE
I continued my investigation and find out that even a direct variable change (not a response from my backend) does not trigger the change detection automatically...
Example:

```typescript
<button (click)="test = !test">Click</button>
<div *ngIf="test">Yes</div>
<div *ngIf="!test">No</div>
```
In this short example, on my project, the template isn't updated on click.
So, **is it possible that I disabled the automatic change detection when I upgraded?**

## Minimal reproduction of the problem with instructions

*Before upgrade*
```typescript
//The Service
getData(): Observable<SomeClass[]> {
    return this.http.get(environment.backURL, this.options)
      .map((res: Response) => res.json() as SomeClass[])
      .catch(err => this.handleError(err));
  }

//In the component
ngOnInit() {
this.myService.getData()
          .subscribe((apiData) => {
          this.data = apiData
            // At this point, the view was updated with the new value of this.data
          });
}
```

Here is a simple plunkr (https://plnkr.co/edit/RuhGdN?p=preview) that reproduce how it should work (the *test* variable is updated in the template after the backend response). Sadly, I didn't achieve as of now to reproduce the problem I have in my project.

*After the update, the "patch"*
```typescript
//The Service
getData(): Observable<SomeClass[]> {
    return this.http.get(environment.backURL, this.options)
      .map((res: Response) => res.json() as SomeClass[])
      .catch(err => this.handleError(err));
  }

//In the component
ngOnInit() {
this.myService.getData()
          .subscribe((apiData) => {
          this.data = apiData
          this.changeDetectorRef.detectChanges();
//If I don't call this function, the template is not updated at all.
          });
}
```

So, before posting this issue, I checked the changed logs and the open/closed issues but I didn't find a similar problem. Is there something I missed during the upgrade? Do we have to trigger the change detection manually?

Thanks for your help and let me know if you need more information!

## Please tell us about your environment:

* **Angular version:** 4.0.1 
* **Language:** TypeScript 2.2.2

* **Node:** v7.8.0

**Comment by Toxicable** [comment]
Can you please make a minimal reproduction of your issue in a plunkr so we can investigate
Here's a template to get you started: https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5
Here's a dummy endpoint you can use for data https://jsonplaceholder.typicode.com/posts/1

**Comment by florian-wahl** [comment]
Hi! Thanks for the template and the endpoint. Here is the plunkr: https://plnkr.co/edit/RuhGdN?p=preview
However, I didn't achieve to reproduce the problem I have in my project... In the plunkr's case, the change detection appends and the *test* variable is updated.
I'm still trying to find out what are the differences that could impact the behavior. I'll update my main post if I find anything relevant.

**Comment by florian-wahl** [comment]
One line in one of my templates had (apparently) an issue that broke the change detection on Angular. I removed this line `[value]="getTodayDate() | 'date:'yyy-MM-dd' "` and everything went fine again.
By the way, having this type of problem without Angular detecting it is kind of weird.

Thanks for the help!

**Comment by kevcunnane** [comment]
@florian-wahl do you have any hint on how you detected the broken code causing this? I am having this exact same issue - change detection seems broken after upgrading to Angular 4, but manually calling detectChanges() seems to work around it. It's recently become a blocker since this doesn't work for referenced node modules, so need to find a solution. Thanks!
