### ISSUE TITLE
can't access FormGroup in FormGroup in FormControl

### ISSUE THREAD

**Issue by grapgrap** [angular/angular#15979]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I can't access `FormGroup` in `FormGroup` in `FormControl`.
```
ngOnInit () {
        this.testForm = this.formBuilder.group( {
            'inputGroup': new FormGroup( {
                'input1': new FormControl( '', Validators.required ),
                'input2': new FormControl( '', Validators.required )
            } ),
            'input3': new FormControl( '', Validators.required )
        } );
    }

console.log(this.testForm.controls['inputGroup'].controls); //Property 'controls' does not exist on type 'AbstractControl'.
```

**Please tell us about your environment:**
@angular/cli: 1.0.0
node: 6.9.4
os: win32 x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
this.testForm.get('inputGroup').get('input1');

**Comment by grapgrap** [comment]
I thought it was a bug. thanks for letting me know.
