### ISSUE TITLE
Unexpected mutation behavior when one-way binding a complex object

### ISSUE THREAD

**Issue by jbeck8176** [angular/angular#15983]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When working with a nested component, one way data binding of a complex object does not seem to function as expected. When the child component manipulates the object, the changes are reflected in the parent. However this is not the case when binding to a primitive data type like a string. I am assuming it is passing a reference to the actual object, but it's unclear if that's the intended functionality. If I make the change in the child using a deconstructor (this.dataObjectInput = {...this.dataObjectInput, someProperty:"Parent shouldn't see this yet!"}) it seems to break the reference and function as expected.

**Expected behavior**
I would expect the object to only change on the child component.

**Minimal reproduction of the problem with instructions**
I've added a CLI project that reproduces the scenario to GitHub.
https://github.com/jbeck8176/angular4BindingBug

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Angular CLI project

* **Angular version:** 4.0.2

* **Browser:**Chrome 57
 
* **Language:** TypeScript 2.2

* **Node (for AoT issues):** `node --version` =

**Comment by tbosch** [comment]
Angular's databinding is not cloning objects during dirty checking, only passing references.
Angular is also only comparing references, and not values deeply.

This is working as intended...

**Comment by jbeck8176** [comment]
I see you're point about the databinding not cloning the objects. But if that's the case, then why do primitives not behave in the same fashion as complex objects?

**Comment by tbosch** [comment]
That's just how JavaScript works: primitives like strings or numbers always have value semantics.

**Comment by jbeck8176** [comment]
interesting, thanks for the info
