### ISSUE TITLE
Tracking: Template type checker

### ISSUE THREAD

**Issue by tbosch** [angular/angular#15988]
With the view engine, we lost some type checking capabilities of templates as the generated code is more generic.

Solution: Port the type checker from the language service over to the angular compiler.

**Comment by darxmac** [comment]
I'm having similar issues when using promises and elements behind *ngIf that don't throw errors like they should. Any idea when this could be fixed, or if there is something we can do until then ?

**Comment by djimoh5** [comment]
Experiencing this same issue quite frequently. Very frustrating debugging through template errors when this occurs...is there an ETA for when this will be fixed. Alternatively, is there any workaround, or angular library code I can modify myself for the time being? Thank you.

**Comment by JoostK** [comment]
With Ivy, the template type checker has been completely rewritten.

The funny part is that we are now at the point where the language service needs to be rewritten to take advantage of Ivy's template type checker, the opposite of the proposed solution here 😄
