### ISSUE TITLE
Is there a way to load different javascript for different component?

### ISSUE THREAD

**Issue by thandonguocmo2020** [angular/angular#15986]
Can we get a way to also load Javascript files such like css file in the component section though I am oon Typescript Angular.

@Component({ selector: 'app-company', templateUrl: './company.component.html', jsUrl: ['somejs.js'] })

 and can make like  jsUrl: ["https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/0.6.7/js/min/perfect-scrollbar.jquery.min.js"]

**Comment by MGazi42** [comment]
I think it would be awesome!

**Comment by tbosch** [comment]
Sorry, but we don't have this feature and are not planning on adding it...

**Comment by thandonguocmo2020** [comment]
You have any solution for this problem.

**Comment by thandonguocmo2020** [comment]
I made it run but not really good 

ngAfterViewInit(){
    var  str_Elemenr = `
    <script type="text/javascript" src="http://localhost:9045/js/script_1.js"></script>
    <script type="text/javascript" src="http://localhost:9045/js/script_2.js"></script>
    <script type="text/javascript" src="http://localhost:9045/js/script_3.js"></script>
    <script type="text/javascript" src="http://localhost:9045/js/script_4.js"></script>
    <script type="text/javascript" src="http://localhost:9045/js/script_5.js"></script>
    `;
    var nodeElement =   this.createDiv("div",str_Elemenr);
    document.body.appendChild(nodeElement);
}


createDiv(node_name,textElement) {
          var _nodeElement = document.createElement(node_name);
          _nodeElement.innerHTML = textElement;
          return _nodeElement;
}
