### ISSUE TITLE
Router / Resolver stuck?

### ISSUE THREAD

**Issue by jpmoney** [angular/angular#15997]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If you are navigating between two routes that each have a resolver,  navigating back and forth too quickly via the browser's forward and back buttons will create a "stuck" state. To better understand the bug I added logging in the ngOnInit and Resolve for each Component and its corresponding resolver. To better illustrate:

PurchasesComponent
OrdersComponent
PurchasesResolver
OrdersResolver

console.log in the ngOnInit of both components and the first line of resolve in each resolver.

Clicking and waiting to navigate between each would produce the following:

Click on Purchases:
Purchases Resolver firing
Purchases Component ngOnInit firing

Click on Orders:
Orders Resolver firing
Orders Component ngOnInit firing

This would obviously continue on each route resolved.

However if I am on the OrdersComponent and I quickly click "back" and then "forward" the console reads:
Purchases Resolver firing

The browser displays /orders

and the router is stuck and neither route ever resolves. 

**Expected behavior**

I would expect the router to handle the rapid route changes and move back to the OrdersResolver, let it resolve and then show the OrdersComponent.

**Minimal reproduction of the problem with instructions**

Create two components under your app component. Give each component a route and a resolver. Delay the observable by at least 1000 to give you enough time. Click on route, let it resolve. Then click back and forward as quick as you can.

**What is the motivation / use case for changing the behavior?**

This appears to be a bug. The only thing I can think to do is to subscribe to the router in all of my resolve functions and if the route change observable emits then to immediately return false. It appears that resolvers have a global knowledge of other resolvers and are dependent on the route matching? So the resolver for A can't resolve because it was so quickly routed back to B, but B's resolver can't resolve because A is still resolving and therefore component B will never resolve and the application becomes stuck.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular: 2.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, Safari, Mobile Chrome, Mobile Safari 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yohanfernando** [comment]
I am having the exact same problem, not just in Resolvers, but in CanLoad guard as well. It seems this issue happen when resolver/guard response is of an Observable type (especially when there is a short delay, for argument sake one second). 

I must add that CanActivate, CanActivateChild works OK.

I am using Angular 4.0.2 with ng-cli (v1) and node version is v7.5.0.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
