### ISSUE TITLE
Audio tag in template increases elements render time

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#15995]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Adding `<audio>` tag to ng template increases other elements render time

**Minimal reproduction of the problem with instructions**
- open http://plnkr.co/edit/LXCqDDkbd5np6n0e6lUD
- open chrome devtools, timeline
- run plunkr
- start timeline recording after app loading
- stop after elements appear (3s timeout)
- see ~115ms for simple ngFor/ngIf block rendering
- comment out `<audio></audio>` in template
- repeat timeline recording
- see ~20-30ms for same block

**Angular version:** 4.0.2

**Browser:** Version 57.0.2987.98 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by artaommahe** [comment]
any ETA here?) cant use audio tags on page due to huge performance drop

**Comment by pkozlowski-opensource** [comment]
I can't confirm this with the attached plunker and latest Chrome (see screenshot). Could you please check again that it happens on your side and if so record timeline and share it here (with the clear description for which part of the stack we should be looking). 

Also make sure that you measure performance under the following conditions:
* prod mode and AOT
* latest browser version 
* incognito mode with all the extensions disabled.

I'm kind of expecting that you've got an extension that interferes with `<audio>` elements but it is impossible to confirm without having exact reproduce. 
![screen shot 2017-07-24 at 17 50 02](https://user-images.githubusercontent.com/973550/28532039-db758b68-7098-11e7-9fa8-6e6c7a43a724.png)

**Comment by chuckjaz** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
