### ISSUE TITLE
Tab navigation not working 

### ISSUE THREAD

**Issue by doorman02** [angular/angular#16004]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a tab navigation where the first tab url equals to the path of the root path and the second tab path is a suburl. The problem is if the first tab equals to the root path it does not navigate anymore.

**Expected behavior**

It should navigate

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, 

* **Angular version:** 2.0.X
Latest Angular

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome latest
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by doorman02** [comment]
Hi @pkozlowski-opensource  I accidently commented out the plunkr I created. I updated the issue above with the plunkr link clearly demonstrating the bug. Could you please reconsider your closing the issue?
