### ISSUE TITLE
Projected templates do not update when using ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by stringham** [angular/angular#16012]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I am dynamically creating a component (using `viewContainer.createComponent`) which uses ChangeDetectionStrategy.OnPush and that component instantiates a template provided by the parent component with `viewContainerRef.createEmbeddedView(templateRef)`. When the parent component updates the template, the dynamically created component does not update.

**Expected behavior**
It should update

**Minimal reproduction of the problem with instructions**
Here is a plnkr which has implemented a way to show a callout when clicking on an element. I have hooked up two different callout components (one uses OnPush and one uses Default).

https://plnkr.co/edit/vYCuDwHj64qIp6GEShC9?p=preview

**What is the motivation / use case for changing the behavior?**
Right now we're having to use some hacky workarounds which register child change detector refs with the parent components, and having the parent component mark the children for check. Using OnPush is necessary for the performance of our app.

* **Angular version:** 4.0.2

* **Browser:** all
 
* **Language:** all

**Comment by tbosch** [comment]
The general problem here is that views for projected templates get data from 2 places:
- the place where they were declared (for all regular expressions)
- the place where they were projected into (via template variables).

**Comment by tbosch** [comment]
Duplicate for https://github.com/angular/angular/issues/14321, for which I submitted a fix in https://github.com/angular/angular/pull/16592. @stringham could you try that fix and give me feedback?

**Comment by davityle** [comment]
@tbosch I was looking into this with @stringham and it is working in almost every case :tada:. However, we did run into a single case that didn't seem to be working as we would expect it to. 

We have a component that works something like this:
```html
<component-a
    *ngFor="let item of items"
    (mouseenter)="setHoveredItem(item)"
>
</component-a>
<ng-template directive-a>
    <component-b
        [item]="hoveredItem"
    ></component-b>
</ng-template>
```
When the `mouseenter` event happens the first time everything works as expected. However, the second time the `mouseenter` event gets triggered the change detector is not run on the projected template. The third time the event gets triggered the change detector will run iff `hoveredItem` is not set back to what it was set to after the first event as fired. If the change detector didn't run on the projected template after the third event it will always run on the fourth event. This flow chart describes the issue we are seeing.

![blank diagram - page 1](https://cloud.githubusercontent.com/assets/5864474/25826591/a2c6da36-3404-11e7-9606-f21e29b06263.png)

**Comment by davityle** [comment]
If you would like a reproduction than I can work on that.

**Comment by tbosch** [comment]
@davityle 
The problem in your example seems to be that `component-b` is also `OnPush`. I.e. the `ng-template` might be dirty checked, but the nested `component-b` is not as its input has not changed.
Yes, a reproduction would be great!

**Comment by davityle** [comment]
@tbosch it took me way to long to reproduce this and it is super edge case. If you are even slightly interested in fixing it then let me know and I will open a new github issue for it. Here is a gif of the reproduction. 
![gifrecord_2017-05-09_164834](https://cloud.githubusercontent.com/assets/5864474/25876003/d2f5bcd0-34d7-11e7-88eb-41a20dd06985.gif)

Here is the code that was used to reproduce it (almost all of that is necessary which tells you how much of an edge case it is).
https://plnkr.co/edit/cZArlzit2aYgIxOTbpE2?p=preview

In the end it involved `AsyncPipe`, `ViewContainerRef#createComponent`, `@ViewChild`, and projected templates. In fact, it is much harder to get it to break than it is to fix it.

**Comment by tbosch** [comment]
@davityle So do you have a workaround / different way of achieving your goal?

**Comment by davityle** [comment]
Yes, we have a simple workaround

**Comment by stringham** [comment]
@tbosch thanks for taking this one on! In cleaning up our workarounds, we were able to delete nearly 500 lines of code.

**Comment by tbosch** [comment]
@davityle Ok, then let's leave this closed for now. Thanks for providing feedback.

**Comment by geocine** [comment]
@davidtyle can you share your workaround

**Comment by davityle** [comment]
obligatory xkcd https://xkcd.com/979/
@geocine I didn't post the workaround because it is a little gross but essentially it boils down to this:
```onMouseEnter() {
       // logic etc
       requestAnimationFrame(() => this.changeDetector.markForCheck());
}
```
Hope that helps! (if you found a better workaround let me know)

**Comment by pshurygin** [comment]
@tbosch I think I'm having the same issue in a more reasonable use case without ViewContainerRef#createComponent usage but with *ngTemplateOutlet instead. I'm essentially having code like this inside the OnPush component:
`   <ng-container *ngIf="{valid: valid$|async} as data">
        <ng-container *ngTemplateOutlet="template; context: data"></ng-container>
    </ng-container>

<ng-template #template let-valid="valid">
    <button type="button" (click)="onClick(valid)">Click</button>
</ng-template>`

Whenever 'valid$' observable changes, i expect the 'valid' variable to change inside the <ng-template>(because async pipe should mark component for check), but that does not happen until another change detection cycle occurs triggered by some other event. The proposed workaround makes everything work as expected (subscribe to valid$ observable manually and do markForCheck inside requestAnimationFrame) but is really dirty.
Is it indeed an issue with angular or is there something wrong with my approach?
