### ISSUE TITLE
The reset FormGroup method empty the form data in Firefox.

### ISSUE THREAD

**Issue by Davilink** [angular/angular#16011]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I follow the tutorial https://angular.io/docs/ts/latest/guide/reactive-forms.html.

when i click on the revert button the form data is cleared but doesn't put back the old data.

the bug can be reproduce on the demo from the tutorial : https://angular.io/generated/live-examples/reactive-forms/final.eplnkr.html
The bug doesn't affect Chrome.

**Expected behavior**
clear the dirty data and put back the old data.

**Minimal reproduction of the problem with instructions**
Go on the demo from the turorial with firefox Browser and hit the revert button

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10 x86-64
Xubuntu 16.10

* **Angular version:** 4.0.X
  "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"

* **Browser:** 

Windows: Firefox 52 (32-bit), firefox developer 54.0a2 (64-bit), Firefox 55 Beta (64 bits)
Linux: Firefox 52.0.2 (64 bits)

* **Language:**
TypeScript: 2.2.2

* **Node (for AoT issues):** `node --version` =   
Node v6.10.2

After a little investigation i saw that firefox execute 3 times the cycle, but chrome execute the cycle only one time.
in the first cycle, firefox doesn't seem to do anything, in the second cycle it put back the data correctly (the old one), but in the third cycle it's empty the form.

**Zone.js**
```
var ZoneTask = (function () {
  function ZoneTask(type, source, callback, options, scheduleFn, cancelFn) {
    this._zone = null;
    this.runCount = 0;
    this._zoneDelegates = null;
    this._state = 'notScheduled';
    this.type = type;
    this.source = source;
    this.data = options;
    this.scheduleFn = scheduleFn;
    this.cancelFn = cancelFn;
    this.callback = callback;
    var self = this;
    this.invoke = function () {  <---------
      _numberOfNestedTaskFrames++;
      try {
        self.runCount++;
        return self.zone.runTask(self, this, arguments);
      }
      finally {
        if (_numberOfNestedTaskFrames == 1) {
            drainMicroTaskQueue();
        }
        _numberOfNestedTaskFrames--;
      }
    };
  }
```

**core.es5.js**
```
NgZone.prototype.forkInnerZoneWithAngularBehavior = function () {
  var _this = this;
  this.inner = this.inner.fork({
      name: 'angular',
      properties: /** @type {?} */ ({ 'isAngularZone': true }),
      onInvokeTask: function (delegate, current, target, task, applyThis, applyArgs) { <------
          try {
              _this.onEnter();
              return delegate.invokeTask(target, task, applyThis, applyArgs);
          }
          finally {
              _this.onLeave();
          }
    
```

**Comment by deepaknasa** [comment]
@Davilink looks like plunkr link is broken, it doesn't show any code there.

**Comment by Davilink** [comment]
@deepaknasa Sorry, my bad, i updated the link.

**Comment by Aninstance** [comment]
Confirmed, exactly as above, on Firefox 54.0.

**Comment by Goonmeister** [comment]
For those still running into this problem, try changing the button attribute of **type** to be something other than **reset**. It seems Firefox picks up on that attribute and clears the form when the button is clicked. Tested on Firefox 54.0.1.

**Comment by Aninstance** [comment]
@Goonmeister Confirmed. Setting the type to be other than 'reset' (or indeed leaving it empty) solves this issue for me, testing on Firefox 54.0 (Fedora 26, Gnome3 shell).
