### ISSUE TITLE
how to fix url not found 

### ISSUE THREAD

**Issue by thandonguocmo2020** [angular/angular#16018]
GET http://localhost:4200/lib/open-sans/regular/opensans-regular-webfont.woff not-found angular2

I uses it on index.html 

```<link rel="stylesheet" type="text/css" href="assets/lib/stroke-7/style.css"/>
<link rel="stylesheet" type="text/css" href="assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css"/>
 <link rel="stylesheet" href="assets/css/app.css" type="text/css"/>```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
