### ISSUE TITLE
docs: testing - clarify status of TestBed.override<X> methods

### ISSUE THREAD

**Issue by roolebo** [angular/angular#16026]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
#10727 created some buzz around core/testing API changes. A set of override<X> methods were introduced in September'16. All of them except overrideTemplate have similar implementation. overrideTemplate is a shortcut for overrideComponent that disables templateUrl to pass template override.

The methods don't have any documentation but they are listed on stable Testbed. The second parameter of the methods takes parametrized MetadataOverride class and it's experimental. Does it mean that the methods are still experimental? If so, what's the roadmap to make the API stable?

**Expected behavior**
MetadataOverride should be marked as stable. Otherwise overrideX methods should be marked as experimental too.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:**  TypeScript 2.2

* **Node (for AoT issues):** `node --version` =

**Comment by jenniferfell** [comment]
Seems to still be a valid question in v6. 
https://angular.io/api/core/testing/TestBed is marked stable.
https://angular.io/api/core/testing/MetadataOverride is marked experimental

**Comment by jenniferfell** [comment]
@IgorMinar Who can respond to this from the engineering team? Thanks.

**Comment by aikidave** [comment]
It looks like this issue was resolved with https://github.com/angular/angular/pull/26595.
