### ISSUE TITLE
compiler bug! compiler about di part 

### ISSUE THREAD

**Issue by xsilen** [angular/angular#16021]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

provide useFactory is not behave as expected

**Expected behavior**

injector.get("token") should always fire factory call

**Minimal reproduction of the problem with instructions**

```
@NgModule({
    imports: [
    ],
    providers: [
       {
            provide: "userService",
            useFactory: () => {
                debugger;
                return "hello world"
            },
            deps: []
        },
    ]
})
export class AmBotmmApplicationModule {

}

```

```
@Component({
   ...
})
export class AmComponent implements OnInit {
    constructor(
        private injector: Injector
    ) {
    }

    public packLoginBuffer() {
        let loginPack = this.injector.get("userService");
        console.log(loginPack);
    }
```

![image](https://cloud.githubusercontent.com/assets/5467712/25064966/bbf00e98-2238-11e7-8cfa-9dcde9fa436d.png)

why statement `self.__userService_127 == null` is here?

does  all of provider in ngModule became singletone ???

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
DI tokens are singletons, regardless of the form (class, factory on value) that was used to declare / produce them. This works as designed.
