### ISSUE TITLE
SystemJS error trying to use BrowserAnimationsModule

### ISSUE THREAD

**Issue by SamML** [angular/angular#16027]
Hi, I am sorry for being using this way but could you give me a hand here please?
http://stackoverflow.com/questions/43431500/error-systemjs-unexpected-token-when-i-add-angular-animation

I am coming from here https://github.com/angular/angular/pull/15190#issuecomment-287972812
and here https://github.com/angular/angular/blob/master/CHANGELOG.md 

Im begining to think that it is a bug.
![60252f7a1190944a386bc131c5598d6c](https://cloud.githubusercontent.com/assets/13733343/25069017/0c5bd4ac-2275-11e7-8226-2ea8a7c019e6.png)
![e28a569ac53e770f05cac739841fb785](https://cloud.githubusercontent.com/assets/13733343/25069019/10a3b44e-2275-11e7-9aa0-f18013ef5c9c.png)

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Can't load BrowserAnimationsModule

**Expected behavior**

Use BrowserAnimationsModule

**Minimal reproduction of the problem with instructions**

I have tried to import BrowserAnimationsModule and read all about info and known bugs but stille I got error of SystemJS

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows10, Visual Studio, ASP.NET Core app serving Angular version ^4. NPM used for angular package management.

* **Angular version:** 4.0.0, 4.1.0.beta.1

* **Browser:** Chrome 56, IE 11 | 

 Chrome 56, IE 11

* **Language:** [all | TypeScript 2.2 | ES5]
Typescript ES5 2.2
* **Node (for AoT issues):** `node --version` =

**Comment by PoojaM0267** [comment]
Is there any solution to this?

**Comment by PoojaM0267** [comment]
While trying to import this BrowserAnimationsModule is giving error : **Unexpected token <**

**Comment by mlc-mlapis** [comment]
@PoojaM0267 ... use the similar code as the template for a plunker on Angular Gitter -> located at the top part of the screen.
