### ISSUE TITLE
Exception err 

### ISSUE THREAD

**Issue by anivaisu** [angular/angular#16030]
I am using ionic 2

Here is my code.
<div class="messagesholder" 
      *ngFor="let chat of chatval | orderby:'[date]'; let i = index;let first=first;let last = last;">
           {{last ? callFunction() : ''}} 

             <div *ngIf="chat.sender == currentuser || chat.receiver == currentuser" >
                   {{checkdate(chat.date)}} 
                    <p class="chat-date"  id="abc" #abc>{{msgdate | amDateFormat:'LL'}}</p>

      </div> 

  checkdate(date)
  {
    var res = date.split(" ");
    var A=res[0];
    var local=localStorage.getItem('chatdate');
    this.msgdate="";
    if(local === undefined || local === null)
    {
      this.msgdate=A;
      localStorage.setItem('chatdate',this.msgdate);

    }
    else if(local !== undefined)
    {
      console.log(local != A);
      if(local != A)
      {

        this.msgdate = A;
         localStorage.setItem('chatdate',this.msgdate);
      }
    }

   }
 callFunction(){
    this.content.scrollToBottom(0)
  }
I am getting this err

FIREBASE WARNING: Exception was thrown by user callback. Error: Expression has changed after it was checked. Previous value: 'April 10, 2017'. Current value: ''.

Kindly advice me,

THanks

**Comment by tbosch** [comment]
Hello, we need a reproduction, otherwise we can't work on this...

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
