### ISSUE TITLE
docs: universal guide is missing steps

### ISSUE THREAD

**Issue by Develofrog** [angular/angular#16038]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I cannot serve Angular Universal build when I followed only Angular Universal Docs.

**Expected behavior**

I can serve Universal build successfully.

It is great Document. Thank you!
But, It has missing steps for serving AOT or Universal build.

# 1. There is no explanation about index-aot.html
Of course, It is not hard. I succeed with below code.
```html
<!DOCTYPE html>
<html>
  <head>
    <base href="/">
    <title>Angular Tour of Heroes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="styles.css">

    <!-- Polyfills -->
    <script src="node_modules/core-js/client/shim.min.js"></script>

    <script src="node_modules/zone.js/dist/zone.js"></script>
  </head>

  <body>
    <my-app>Loading...</my-app>
  </body>
  <script src="dist/build.js"></script>
</html>
```
But, the beginner may be confused about missing this code.

# 2. webpack's output.path requires absolute path
I don't know when they requires absolute path at output.path, But webpack said "please give me absolute path at output.path" with version webpack 2.4.1.

Therefore, instead of
```javascript
output: {
        path: 'src/dist',
        filename: 'server.js'
},
```
, use it.
```javascript
output: {
        path: path.join(__dirname, 'src/dist'),
        filename: 'server.js'
},
```
or any more simple code.

# 3. webpack.config.uni.js has 3 differences.
Docs says..
```text
The Webpack configuration file for Universal is almost the same as for AOT. There are two differences:

The entry points
The output file name
```
But, Exactly, There are one more differences at plugins!

It needs to change to tsconfig-uni.json.
```javascript
plugins: [
    new ngtools.AotPlugin({
      tsConfigPath: './tsconfig-uni.json'
    }),
```

# 4. We need @types/express 

Thank you for super-easy Angular Universal Document!

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Just read and write code with Angular Universal Docs for learning

**Please tell us about your environment:**

Not related.

* **Angular version:** 2.0.X

4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Not related.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2.0

* **Node (for AoT issues):** `node --version` =   
6.9.4

**Comment by tanis2000** [comment]
`webpack.config.uni.js` would also need to add the require for `path`

```
const path = require('path');
```

**Comment by Swoox** [comment]
Also to generate the aot files can run (is included in the AOT guide)
`ngc -p tsconfig-uni.json`

**Comment by wnabil** [comment]
i got this error on a new project generated by the cli .
TypeError: Cannot read property 'prototype' of undefined
the aot is working fine but uni can not run

**Comment by rafaelscosta** [comment]
Everthing works fine, until you need to import mongoose.  It generate this error when compiling: WARNING in ./~/es6-promise/dist/es6-promise.js
Module not found: Error: Can't resolve 'vertx' in '/Users/rafaelcosta/Documents/UTI-das-Ideias/develop/universal-testes/from-zero 2/node_modules/es6-promise/dist'

I found some topics, but without solution for me: https://github.com/stefanpenner/es6-promise/issues/100

Any idea?

**Comment by ThomasP1988** [comment]
I resolved it by adding 
`npm install vertx3-min` 

and in webpack config

    resolve: {
      alias: {
        vertx:  path.resolve(__dirname, 'node_modules/vertx3-min')
      }
    },

**Comment by wnabil** [comment]
Any one tried that tutorial with lazy loading ?
modules can't be resolved :\

**Comment by deveshjadon98** [comment]
Thanks a lot for this, But even after executing all of this. There's an error 

ERROR in PATH/src/uni/server-aot.ts (4,26): Could not find a declaration file for module 'ex
press'. 'PATH/node_modules/express/index.js' implicitly has an 'any' type.

at the given line  

`import * as express from 'express';`

in server-aot.ts

It got resolved by running this command

`npm i --save "@types/express"` 

It installs the typescript definitions for express.

**Comment by Thomas-Webber** [comment]
Hi guys, with to all your answers I managed to write a bash scripts, generating files for enabling aot and uni on an angular4 app. Check it out here  https://github.com/Thomas-Webber/angular-aot-uni-configuration
thanks

**Comment by jenniferfell** [comment]
docsarea=universal
docsarea=webpack

**Comment by jenniferfell** [comment]
Universal doc has been rewritten for v7. Closing this old issue. Please open a new issue if you find errors or omissions in the new v7 doc. Thanks!
https://github.com/angular/angular/pull/25752
