### ISSUE TITLE
docs(aio): toh-pt5 does not show file content

### ISSUE THREAD

**Issue by RikTheunis** [angular/angular#16032]
In [part 5 of the tour of heroes tutorial](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html) there is code listing that is not shown correctly.
This listing is found at the subtitle 'Update AppModule' as you can see here:

![screenshot from 2017-04-16 12-58-39](https://cloud.githubusercontent.com/assets/17219915/25070658/afc9dc90-22a4-11e7-8a34-6af1d8678217.png)

I think it should show some code listings similar to this:

![screenshot from 2017-04-16 12-59-08](https://cloud.githubusercontent.com/assets/17219915/25070661/dfa7e150-22a4-11e7-9e9f-e9cc1e69b338.png)

**Comment by Foxandxss** [comment]
Weirdly enough, it still happens on the new site with different markdown and so. Yikes!
