### ISSUE TITLE
No NgModule metadata found for 'TemplateModule'. (So how can I provide metadata for a dynamic module?)

### ISSUE THREAD

**Issue by patrikx3** [angular/angular#16033]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

With JIT it works and with AOT + JIT it does not. (AOT works, JIT borken now for me)

**Expected behavior**

The JitCompiler shouldn't it not need NgModule metadata, since it is JIT?
What am I missing?

**Minimal reproduction of the problem with instructions**

```typescript
    public compile(opts: CompileHtmlServiceOptions) {
        try {
            @Component({
                template: opts.template || ''
            })
            class TemplateComponent {
                ref = opts.ref;
            }
            @NgModule({
                imports: opts.imports,
                declarations: [TemplateComponent],

            })
            class TemplateModule {}
            const compiled = this.compiler.compileModuleAndAllComponentsSync(TemplateModule);
            const factory = compiled.componentFactories.find((comp) =>
                comp.componentType === TemplateComponent
            );
            opts.container.clear();
            opts.container.createComponent(factory);

        } catch(e) {
            console.error(e);
        }
    }
```
I get the error above right there. 
Right now I made it to work with JIT but a get this error:
```bash
Error: No NgModule metadata found for 'TemplateModule'.
    at NgModuleResolver.resolve (<anonymous>:112642:23) [angular]
    at CompileMetadataResolver.getNgModuleMetadata (<anonymous>:113221:60) [angular]
    at JitCompiler._loadModules (<anonymous>:124416:64) [angular]
    at JitCompiler._compileModuleAndAllComponents (<anonymous>:124395:52) [angular]
```

### So how can I provide metadata for a dynamic module?

**What is the motivation / use case for changing the behavior?**

I need an JIT compilation with AOT.

**Please tell us about your environment:**

Debian, Mint, Win 10

* **Angular version:** 2.0.X

4.0.2 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Firefox, Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

* **Node (for AoT issues):** `node --version` =   
v7.9.0

**Comment by tbosch** [comment]
Hello,
we don't support mixing JIT and AOT right now. A better way of doing dynamic content is using `ComponentFactoryResolver` and `ViewContainerRef`.

**Comment by tbosch** [comment]
Mmh, maybe I don't understand the question. Could you provide a plunker, if the error shows in JIT mode?

**Comment by patrikx3** [comment]
I am trying to use dynamic JIT with AOT. So I am understanding that AOT + JIT at the same time is not supported?

**Comment by patrikx3** [comment]
I send you a REPO so that you can reproduce.

**Comment by patrikx3** [comment]
```bash
https://github.com/patrikx3/angular-compile-html.git
# aot test http://localhost:9999
yarn install
grunt aot-test --verbose

# pure jit http://localhost:8080
grunt run
```

**Comment by patrikx3** [comment]
So you mean we cannot create dynamically modules, components with AOT, so just forget an use JIT?

**Comment by bohacc** [comment]
Hi, I have the same issue.

**Comment by fknop** [comment]
You can create dynamic component by using the ComponentFactoryResolver and the entryComponents entry of an NgModule.

A dynamic NgModule is probably not possible.

**Comment by fknop** [comment]
You may want to read this https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html

**Comment by patrikx3** [comment]
ciao! thanks for responding! 
how can i create a dynamic component if it is not existing in the NgModule? 
I create a new component with a dynamic template (anything i want) without a module when the component created at run time?

Thanks so much!

**Comment by patrikx3** [comment]
https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html is only for an existing component, but like angular compile html, i can create a dynamic template, doesn't JIT does it?

**Comment by fknop** [comment]
It will probably not work with AoT then, as tbosch said, mixing JIT and AOT is not supported (yet?).

**Comment by patrikx3** [comment]
Hey! 
OK, so it is confirmed. 
Do you guys know if it will be enabled ever?  Please just answer, when you get a chance! Thanks so much!

[ ] Not sure
[ ] Future
[ ] Never

**Comment by patrikx3** [comment]
Guys, this is weird. 
My AOT bundle is 2.75MB.
Bigger.
JIT is 2.5MB. 
Though AOT is faster! For sure! Had I no needed JIT a lot, I would use AOT.

My solution is: 
For now I turned on GZIP the server and it flyes as hell! **600KB** (Material, tons of stuff)

I wish I had no the ```No NgModule metadata found for``` error! Let's keep it on ```how to use AOT+JIT```. 

For me, same exact code and same error, why??? So weird!

**Comment by Dunos** [comment]
@fknop The example of the link https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html is not working

**Comment by patrikx3** [comment]
aot and jit is different...
jit works, with aot is not working out of the box.

**Comment by mkariti** [comment]
Hi, 
Any update on this issue? 
I would like to use dynamic with aot as well.
thanks

**Comment by gatimus** [comment]
I have been using the solution [here](https://github.com/Alekcei/AotAndJit) of using the JitCompilerFactory to load the runtime compiler and custom decorators to preserve the component and module metadata [demo](https://github.com/gatimus/compiler-test). but I can't get it to work with the cli build-optimizer [SO](https://stackoverflow.com/questions/46737688/aot-and-jit-with-build-optimizer)

**Comment by snarun** [comment]
Any updates over here? This scenario is applicable especially in building pluggable modules. Like loading modules from external UMD files and then instantiating the Angular module from them.

**Comment by mlc-mlapis** [comment]
@snarun ... read https://github.com/angular/angular/issues/20875

**Comment by snarun** [comment]
Thank you @mlc-mlapis !! The soln. for [#20875](https://github.com/angular/angular/issues/20875) works if all the modules are referred in same location, but for dynamic loading from umd bundles, it is leading to problems such as 

> No NgModule metadata found for nested imported modules

This is more applicable, if you try to instantiate an UMD bundle with an entry module, but internally has multiple imports to all referred modules.  Adding custom NgModule annotation to all those modules and later stitching it out, is not fit for these cases. Any other alternatives? 

I'm using a combination of ngc, rollup for generating a bundle, webpack for building a container app and SystemJS for importing dynamic bundles.

**Comment by mlc-mlapis** [comment]
@snarun ... I am a bit lost ... nested imported modules? Why do you need JIT Complier in AOT app ... when you use static modules?

**Comment by snarun** [comment]
@mlc-mlapis... Look at the case of building a pluggable system, where plugins will be in the format of UMD bundles.. Your angular app should import those umd bundles to the browser client and compile it using sync or async methods of compiler. I had tried with both compiler as well as JITCompiler at client and both of them leads to NgModule metadata not found error.  I could able to successfully build the modules, if its @NgModule annotation has no further imports, but that is not the case for most of the real-time scenarios.

**Comment by mlc-mlapis** [comment]
@snarun ... ah, for us ... when running an app in AOT mode ... we just load a custom bundle ... that is bundled ahead of time and contain original UMD part ... (but with decorators extracted) + *.ngfactory.js part so we are able to run it without compiler at all ...

I thought that it is important to compile really dynamical modules ... mainly when HTML templates come from DMS where you aren't able to guess what it'll be.

**Comment by snarun** [comment]
@mlc-mlapis ... very true... If the decorators are not extracted and the link is maintained, then the compilation would go through and the components can be initialized... Not sure whether Angular team address this..

**Comment by mlc-mlapis** [comment]
@snarun ... what tool you are using for building UMDs? ... generally for building your libs?

**Comment by snarun** [comment]
@mlc-mlapis .. I use ngc + rollup

**Comment by mlc-mlapis** [comment]
@snarun ... hmm, we are using `ng-packagr` to build all custom packages ... and all UMDs created by that way contain complete decorators so we have to extract them after that on our own to optimize a bundle size ... before creating our custom bundles.

**Comment by snarun** [comment]
@mlc-mlapis ... I've verified the output from ng-packagr and rollup on UMD bundles. Both are same. Decorators are defined without annotation tag.  JIT compiler does not recognize the module without the metadata.  As decorators are arranged differently, using JIT summary is another option.. but that will increase the bundle size. Its a trade off in the current context.

**Comment by mlc-mlapis** [comment]
@snarun ... thanks for your info. 👍

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
