### ISSUE TITLE
Wrong Chinese Currency

### ISSUE THREAD

**Issue by paulusklerk** [angular/angular#16048]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When you call the currency pipe Symbol for China (CNY) it produces "CN¥" as a prefix. This is wrong it should be "¥" or "CNY" but NOT "CN¥"

**Expected behavior**

currency pipe + "CNY" produces prefix: "¥" or "CNY" 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
It is simply just wrong output

**Please tell us about your environment:**
any

* **Angular version:** 2.0.X
^4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
ALL
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ALL

**Comment by bOmBeLq** [comment]
@paulusklerk I doubt it's angular bug. Angular uses Intl extension internally. 
You can test it even here on github:
![zaznaczenie_331](https://user-images.githubusercontent.com/1465880/27295684-ff09a05a-551d-11e7-81f9-8380abe536b2.png)
Notice the en-US and en-cn. It is locale. You need to change the angular locale. I've tested and it does the trick.
This comment describes very well how to set app wide locale:
https://stackoverflow.com/questions/34904683/how-to-set-locale-in-datepipe-in-angular2/39344889#39344889

**Comment by paulusklerk** [comment]
Thanks Damian we will look into it, thanks for the reply!

**Comment by vicb** [comment]
The currency comes from the Intl API on 4.x so closing as there is nothing we can do there.

In 5.x we moved away from the Intl.js API
