### ISSUE TITLE
Promise resolve by setTimeout will case renderer error out of Angular env

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [angular/angular#16047]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

if some one get a renderer errror on a promise that resolve by a setTimeout, the error will never print to console, and they still get a freezen UI.

like follow code,
I change 'preLoadingMode' to 'ok' to let ngIf show a template that have a BUG in a Promise resolved by setTimeout. The Renderer throw a error, but Angular never print the error to console and no body can catch it.
But, if you manual thow error or manual toggle 'preLoadingMode' to caase the  renderer error, it can print to console as normal.

i open trace config 'Pause On Caught Exceptions' in Chrome, I look a exception throw and lost by follow way.
if step over next function:
```
core.es5.js: callWithDebugContext():viewWrappedDebugError
Subscriber.js: SafeSubscriber.prototype.__tryOrUnsub():throw error
```
and then, lost the exception.

if step out of currnet function:
```
core.es5.js: callWithDebugContext():viewWrappedDebugError
Subscriber.js: SafeSubscriber.prototype.__tryOrUnsub():throw error
......
zone.js: patchTimer():delete tasksByHandleId[data.handleId];
```
and then, lost next function

i sugest that maybe the BUG case by Timer Patch and Zone.js .

**follow is the mininize code**

app.component.ts
```ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  ngOnInit(): void {
    let p = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve();
      }, undefined);
    });
    p.then(
      T => {
        // throw Error('1');
        this.preLoadingMode = 'ok';
      }
    );
  }

  title = 'app works!';
  preLoadingMode;

}
```
app.component.html
```html
<h1 *ngIf="preLoadingMode!='ok'">
  aaa
</h1>
<h1 *ngIf="preLoadingMode=='ok'">
  bbb
  <input [(ngModel)]="aaa.bbb"> <!--    MAKE A Renderer Exception In This Line   -->
</h1>

<button (click)="preLoadingMode='error'">
  error
</button>
<button (click)="preLoadingMode='ok'">
  ok
</button>


<input [ngModel]="preLoadingMode">

```

**Expected behavior**

as above, a renderer error need print to console that can let developer the codding bug.

**Minimal reproduction of the problem with instructions**

demo on this:
http://plnkr.co/edit/StYfCdLmzV3sl2eQ9Jyp?p=preview

**What is the motivation / use case for changing the behavior?**

I need a Sleep() function like other language,  to use in async/await function, to let server have a break.
so i write follow function 
```ts
export function sleepAwait(timeout: number) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve();
    }, timeout);
  });
}
```
and use it like follow in a real project:
```ts

    ngOnInit() {
        setTimeout(() => {
            this.preLoading().catch(E => devConsole.error(E)).then(T => {
                this.loadingStringTimerSubscription.unsubscribe();
            });
        });
    }

    async preLoading() {
        devConsole.log("begin loading");
        const waitTime = undefined; // debugging
        // const waitTime = 1000;    //  make enough time to show a loading animation to let user happy
        this.preLoadingPercentage = 0;
        try {

            // ....... do many many wast time async task with server
            // and use <code>await sleepAwait(waitTime);</code> to let server have a break

            await sleepAwait(waitTime);
            this.preLoadingPercentage = 98;
            await sleepAwait(waitTime);
            this.preLoadingMode = 'ok';    //  OK, hidden loading animation and show the real thing
            devConsole.log("end loading OK");
        } catch (e) {
            this.preLoadingMode = 'error';
            devConsole.log("end loading error");
            devConsole.log(e);
        }
    }

```
but when a BUG case a renderer Error that bug case by the line <code>this.preLoadingMode = 'ok';</code>, no error print to console and UI freezen.

**Please tell us about your environment:**

Windows10, WebStorm, Yarn, Angular-cli Ng serve

* **Angular version:** v4.0

Angular V4
Angular-Cli V1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

test in Firefox , Chrome , Edge , may be All.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2.2, 2.1.6

* **Node (for AoT issues):** `node --version` =   
npm 3.10.10
node v6.10.2
yarn install v0.23.2

**Comment by Lyoko-Jeremie** [comment]
And just now, i write sleepAwait() function as follow.
its not print, too.

```ts
import {TimerObservable} from "rxjs/observable/TimerObservable";

export function sleepAwait(timeout: number) {
    return new Promise((resolve, reject) => {
        let s = new TimerObservable(timeout || 0).subscribe(
            T => {
                resolve();
                s.unsubscribe();
            },
            E => {
                reject();
                s.unsubscribe();
            }
        );
    });
}
```

so, i think that maybe it case by Rxjs, OR Promise A+ have a wrong patch.

**Comment by Lyoko-Jeremie** [comment]
i wrote a function like follow and let it run outside angular and notice change detect
```ts
// constructor(private zone: NgZone, @Inject(ChangeDetectorRef) private viewRef) {
// }
export function runOutsideAngularAndDetectChanges(zone: NgZone, viewChangeDetectorRef: ChangeDetectorRef, func: Function) {
  zone.runOutsideAngular(() => {
    func();
    zone.run(() => {
      viewChangeDetectorRef.detectChanges();
    });
  });
}
```

now its working and pring error on console.

demo on this:
http://plnkr.co/edit/gttIYIZon35JNfNvYL4U?p=preview

**Comment by JiaLiPassion** [comment]
@Lyoko-Jeremie , could you updated the plunker to reproduce the bugs with latest `zone.js` again? Thanks!

**Comment by Lyoko-Jeremie** [comment]
@JiaLiPassion 
Oh, it seems like work with not reproduce the plunker.

the plunker load zone.js without version code as follow
```
    <script src="https://unpkg.com/zone.js/dist/zone.js"></script>
    <script src="https://unpkg.com/zone.js/dist/long-stack-trace-zone.js"></script>
```

i think plunker always load the latest version.

  

and i need some time to upgrade zone.js in the product and verify this issue make sure it fixed on the production env.

**Comment by Lyoko-Jeremie** [comment]
yes , i think this issue can be closed.
@JiaLiPassion Thank you very much !!!
