### ISSUE TITLE
docs(AIO) inline link to Step 2 Create Project doesn't work

### ISSUE THREAD

**Issue by toymachiner62** [angular/angular#16044]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The inline anchor tag for step 2 doesn't jump you down to step 2. https://angular.io/docs/ts/latest/cli-quickstart.html#!#create-proj

**Expected behavior**
Clicking step 2 link should jump you to the create project section.

**Minimal reproduction of the problem with instructions**
Go to this page https://angular.io/docs/ts/latest/cli-quickstart.html and click step 2. It doesn't take you to the section for creating a project

**What is the motivation / use case for changing the behavior?**
It's broken

**Please tell us about your environment:**
OSX, Chrome

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
I tried in Chrome only
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by petebacondarwin** [comment]
This is also true in the AIO staging site. It looks like the step 2 link is pointing to an invalid anchor.

**Comment by Foxandxss** [comment]
Anchors should be fixed now.
