### ISSUE TITLE
docs(aio): fix broken links on API docs

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#16055]
Investigate and fix broken links/icons on API docs: ![ngif][1]
Do we need "Improve this doc" link for non API-docs?

[1]: https://cloud.githubusercontent.com/assets/8604205/25100373/7c4c62ce-23b8-11e7-950a-d71ac2a6ea08.png

**Comment by wardbell** [comment]
Fixed by PR #16132

**Comment by gkalpak** [comment]
It is #16122 that was fixed by #16132. Not this one. Reopening...

**Comment by gkalpak** [comment]
Previously we had the following fields:
- `exported from` (e.g. _animations/browser/index_)
- `defined in` (e.g. _animations/browser/src/render/animation_driver.ts_)

In ef48ee0a0, the fields were changed to:
- `npm package`
- `NgModule`
- the link to where it is defined

##
I assume that `NgModule` (which gets its value from `doc.moduleDoc.name`) is supposed to be the equivalent of `exported from` (which got its value from `doc.moduleDoc.id`).

`npm package` is supposed to take its name from `doc.package`, but it currently appears to be empty. Is it something that was planned to be implemented but hasn't yet?

@petebacondarwin, any idea?

**Comment by petebacondarwin** [comment]
I don't know where that `doc.package` came from. It has never been implemented in the Angular docs. But we could indeed implement it based on the `moduleDoc.id` I guess.

**Comment by petebacondarwin** [comment]
This is what I think we need in this template: https://github.com/angular/angular/pull/16444/files#diff-096b24ccfdb8a0485cb0eecc02034c01R3

**Comment by petebacondarwin** [comment]
Regarding the `NgModule` link: this will be quite a lot of work, since we will need to identify each of the NgModule annotated classes, e.g. https://aio-staging.firebaseapp.com/api/forms/FormsModule, and then parse all of the declarations for that module, to identify what is "owned" by that module, then go to each of those docs and associate them with the NgModule.

**Comment by petebacondarwin** [comment]
It might be that we end up doing this manually by attaching an `@ngModule` tag to each thing in the docs that is declared on an NgModule.
