### ISSUE TITLE
docs: toh-pt4 - snippet error in "Appendix: Take it slow"

### ISSUE THREAD

**Issue by hrskrs** [angular/angular#16056]
**I'm submitting a ...**
- [x ] other (Please do not submit support requests here (see above))

**Current behavior:**
On the Documentation page, on Services section there exist a  buggy snippet on `[Appendix: Take it slow](https://angular.io/docs/ts/latest/tutorial/toh-pt4.html)` where `this.getHeroes()` is called instead of `HEROES` constant in `mock-heroes.ts`:

```
getHeroesSlowly(): Promise<Hero[]> {
  return new Promise(resolve => {
    // Simulate server latency with 2 second delay
    setTimeout(() => resolve(this.getHeroes()), 2000); //instead of this.getHeroes, call HEROES
  });
}
```

**Expected / new behavior:**
Instead of returning `this.getHeroes()`, you have to return `HEROES` constant from `mock-heroes.ts`

**Anything else:**
The link for buggy snipper is here:
https://angular.io/docs/ts/latest/tutorial/toh-pt4.html under `Appendix: Take it slow`

**Comment by jenniferfell** [comment]
App and tutorial section have been rewritten since this issue was opened. "Appendix: Take it slow" no longer exists, nor does the doc mention getHeroesSlowly. 

Closing as resolved.
