### ISSUE TITLE
ng2 path normalization doesn't work if query parameters are present

### ISSUE THREAD

**Issue by bourey** [angular/angular#16069]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular's path normalization usually strips trailing slashes from URLs, redirecting /foo/ -> /foo.  This ensures that URLs have a standard format and that mistakenly adding a slash to the end of a URL doesn't result in a page not found error.  

This logic currently does not work if the URL contains a query parameter.  As an example /foo/?bar=baz results in page not found behavior.

**Expected behavior**
I'd expect /foo/?bar=baz to be normalized to /foo?bar=baz.

**Minimal reproduction of the problem with instructions**
1. Download https://github.com/bourey/ngupgrade-example/tree/ng2
2. npm start
3. npm install
4. Visit http://localhost:3000/teams/?foo=bar.  Compare this to the behavior for http://localhost:3000/teams?foo=bar

**Please tell us about your environment:**

* **Angular version:** 4.0.2
* **Browser:** Chrome 
* **Language:** TS

**Comment by royling** [comment]
Interesting, the inconsistency should be fixed following the URL standard, which is to preserve trailing slash in pathname. This is reported as a feature request in #16051.

**Comment by czimmons** [comment]
I have a similar issue except with the hash not the querystring. A user visits an app with a link to /foo using Internet explorer. Our server redirects to /foo/ then somehow IE ends up navigating to /foo/# and the route isn't found. 

Adding a route with a path of 'foo/' fixes it.
