### ISSUE TITLE
Associate router events with the originating router outlet

### ISSUE THREAD

**Issue by bourey** [angular/angular#16065]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It's not possible to determine which router outlet was associated with a routing event. If we have a main router outlet with a child outlet, events from each router outlet are indistinguishable. 

**Expected behavior**
We'd like a way to determine which router outlet was associated with the routing event.

**What is the motivation / use case for changing the behavior?**
This currently prevents us from adding a loading indicators to each router outlet and displaying them appropriately. Right now, a parent loading indicator would display when the child router outlet was in the loading state.

* **Angular version:** 2.0.X
4.0.2

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

**Comment by jasonaden** [comment]
➤ 343224876090953 commented:

The router is set up to handle events at the router level. A `RouterOutlet` is at the rendering level, so at the point of running through navigation events, the router doesn’t actually know what specific outlets are being reloaded and/or re-rendered.

As an example, if a child route were lazy-loaded, the router wouldn’t even know about the router outlet until it tried to render the route, which is too late to be showing a spinner.

I think the right place to handle this would be in route-specific events. Either by having an observable of `routeEvents` that can be subscribed to from the route config, or add hooks to the route config. Probably out of these two solutions, I would prefer to keep the API somewhat consistent and have a `routeEvents` observable available on a route config. Then events could first be published to the specific route they apply to (`routeEvents`), then `merge` these route-specific events to produce the higher-level `routerEvents` observable.

**Comment by naomiblack** [comment]
@jasonaden can you confirm that this issue is closed by https://github.com/angular/angular/pull/18407? I think this is fixed.

**Comment by jasonaden** [comment]
@naomiblack Yep, this can be closed now.
