### ISSUE TITLE
docs(aio): Form Validation: Syntax error in code example

### ISSUE THREAD

**Issue by andys8** [angular/angular#16063]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The current website shows this code example. `onSubmit`  has a an additional closing bracket in Line 23. The resulting code is wrong.
![image](https://cloud.githubusercontent.com/assets/13085980/25103290/3a2dc6a4-23bc-11e7-8aa5-02a4a3147dc5.png)

**Expected behavior**
Line 23 should not be existing in the example and the syntax of the example would be correct.

[hero-form-reactive.component.ts](https://github.com/angular/angular/blob/master/aio/content/examples/cb-form-validation/src/app/reactive/hero-form-reactive.component.ts) in this repository doesn't look to have this problem. So either the page is not up-to-date (but I found it in current builds, too), the file isn't the one causing the issue, there is an issue with the parsing (Why is there an `// #enddocregion` in line 28?) or I'm missing something.

**Minimal reproduction of the problem with instructions**
Visit the latest documentation page: https://angular.io/docs/ts/latest/cookbook/form-validation.html#!#committing-changes

**Comment by andys8** [comment]
I think the reason is that the whole part between [Line 28 and 45](https://github.com/angular/angular/blob/master/aio/content/examples/cb-form-validation/src/app/reactive/hero-form-reactive.component.ts#L28-L45) is excluded due to the `docregion` comments. Therefore the `}` in line 47 will break the syntax. But the actual problem is that there is a bunch of code missing when somebody is reading the documentation.

**Comment by wardbell** [comment]
Thanks for catching this. Closing issue as it is cleaned up as a part of other changes in PR #17734.
