### ISSUE TITLE
How to use hostSetters?

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1606]
Before alpha 21 I used `@PropertySetter`  annotations to set a CSS class. This is more a work around due to https://github.com/angular/angular/issues/1472. So I did something like this:

```js
@Component({
  selector: 'component',
  lifecycle: [onChange],
  properties: {
    active: 'active'
  }
})
class Cmp {
  constructor(@PropertySetter('class.active') activeClassSetter) {
    this.activeClassSetter = activeClassSetter;
  }

  onChange() {
    // set `active` class based on `active` property
    this.activeClassSetter(this.active);
  }
}
```
This is super hacky but it worked for now. However, since alpha 21 we have `hostSetters` that should do the work using EventEmitters. So I ported the code to something like this:

```js
@Component({
  selector: 'component',
  lifecycle: [onChange],
  properties: {
    active: 'active'
  },
  hostSetters: ['activeClassSetter: class.active']
})
class Cmp {
  constructor() {
    this.activeClassSetter = new EventEmitter();
  }

  onChange() {
    this.activeClassSetter.next(this.active);
  }
}
```

This unfortunately doesn't work, the `active` class is not set. I rather think that I'm just using it wrong, so can anybody give me any pointers? :)

**Comment by pkozlowski-opensource** [comment]
@PascalPrecht isn't it `hostProperties`?

https://github.com/angular/angular/blob/bb50fc131bd74bed2e394df2eaba1bcff75fc6bc/modules/angular2/src/core/annotations_impl/annotations.js#L467

**Comment by PascalPrecht** [comment]
As part of the big rename issue (https://github.com/angular/angular/issues/1244) this is task talk about `hostSetters` (https://github.com/angular/angular/issues/1256)

**Comment by pkozlowski-opensource** [comment]
@PascalPrecht yeh, but have a closer look at #1256 - I think that it is named `hostProperties` - at least what the code says and it tends to be more up-to-date than GH issues :-)

**Comment by PascalPrecht** [comment]
When I use `hostProperties` with a mapping like this:

```js
hostProperties: ['activeClassSetter: class.active']
```

I get:

```sh
Uncaught (in promise) SyntaxError: Unexpected token :
    at Function (native)
    at ReflectionCapabilities.execute.ReflectionCapabilities.setter (http://localhost:9000/lib/angular2.js:8664:20)
    at Reflector.execute.Reflector.setter (http://localhost:9000/lib/angular2.js:17896:50)
    at setterFactory (http://localhost:9000/lib/angular2.js:13343:42)
    at http://localhost:9000/lib/angular2.js:19669:69
    at Map.forEach (native)
    at Function.execute.MapWrapper.forEach (http://localhost:9000/lib/angular2.js:8191:15)
    at http://localhost:9000/lib/angular2.js:19668:28
    at Array.map (native)
    at Function.execute.ListWrapper.map (http://localhost:9000/lib/angular2.js:8294:26)
```

So the `:` is doesn't seem to be allowed there.

**Comment by pkozlowski-opensource** [comment]
`hostProperties` is a map, not a collection and it works only in alpha.21. Maybe it would be easier with a plunk?

**Comment by pkozlowski-opensource** [comment]
Also see: https://github.com/angular/angular/commit/8ccafb0524e3ac4c51af34ef88e0fe27482336a6#diff-bcd2b4a07e5dcbc8a7842482e5242728R32

**Comment by PascalPrecht** [comment]
@pkozlowski-opensource thanks for the pointers!

```js
hostProperties: {
  'active': 'class.active'
}
```

Works perfectly fine! Didn't know I could use the CSS prefix syntax here in a map :)
