### ISSUE TITLE
Angular2 component/webpage not showing the entire page

### ISSUE THREAD

**Issue by krish07** [angular/angular#16076]
In a component when i use scroll down and click on the navigation of the page, it going to new component but page position/scrollbar is at the same place how can we resolve this issue please can any once check this

**Comment by pengcl** [comment]
<div style="overflow:hide">
<router-outlet></router-outlet>
</div>

set a scroll div in the component of router-outlet

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
