### ISSUE TITLE
inline, vendor, client bundle script tags are not getting in page source for universal CLI app

### ISSUE THREAD

**Issue by BattiniSantthosh** [angular/angular#16074]
### Versions.
```
universal-cli: 1.0.0-alpha.universal.3
angular-cli: 1.0.0-beta.23
node: 7.5.0
os: win32 x64
```
### server.routes.ts
export const routes: string[] = [
	'*'
];
### app.routes.ts

export const appRoutes: Routes = [    
  { path: 'contact', component: ContactComponent },
  { path: '',   component: HomeComponent },
  { path: '**', component: PageNotFoundComponent }
];

### contact.component.html

<p>
			&lt;form #f=&quot;ngForm&quot; (ngSubmit)=&quot;addTodo()&quot;&gt;<br />
			&lt;input name=&quot;newTodo&quot; [(ngModel)]=&quot;newValue&quot;&gt;<br />
			&lt;button&gt;Submit&lt;/button&gt;</p>

### contact.component.ts

export class ContactComponent implements OnInit {

  newValue: string = "";
  constructor() { }
  ngOnInit() {
  }
  addTodo(){  
  	console.log(this.newValue)	    
    
  }

}
### index.html
<p>
			&lt;!doctype html&gt;<br />
			&lt;html&gt;<br />
			<br />
			&lt;/html&gt;</p>

### contact.component.html
<p>
			&lt;head&gt;<br />
			&nbsp;&nbsp; &nbsp;&lt;meta charset=&quot;utf-8&quot;&gt;<br />
			&nbsp;&nbsp; &nbsp;&lt;title&gt;{{ globals.metaTitle }}&lt;/title&gt;<br />
			&nbsp;&nbsp; &nbsp;&lt;meta name=&rdquo;description&rdquo; content=&quot;{{ globals.metaDescription }}&quot; /&gt;<br />
			&nbsp;&nbsp; &nbsp;&lt;meta name=&rdquo;keywords&rdquo; content=&quot;{{ globals.metaKeywords }} &quot; /&gt;<br />
			&nbsp;&nbsp; &nbsp;&lt;base href=&quot;/&quot;&gt;<br />
			&nbsp;&nbsp; &nbsp;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;<br />
			&nbsp;&nbsp; &nbsp;&lt;link rel=&quot;icon&quot; type=&quot;image/x-icon&quot; href=&quot;favicon.ico&quot;&gt;<br />
			&nbsp;&nbsp; &nbsp;&lt;script src=&quot;http://localhost:35729/livereload.js?snipver=1&quot;&gt;&lt;/script&gt;<br />
			&lt;/head&gt;<br />
			&lt;body&gt;<br />
			&nbsp;&nbsp; &nbsp;&lt;router-outlet&gt;&lt;/router-outlet&gt;<br />
			&lt;/body&gt;</p>

### app.component.ts

import { Component } from '@angular/core';
import { AppServiceService } from './services/app-service.service';

@Component({
  selector: 'html',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [AppServiceService]
})
export class AppComponent {
  constructor(private globals: AppServiceService){
    }
}
### app-service.service.ts
export class AppServiceService {
	metaTitle = 'This is the Title';
    metaDescription = 'This is the Dis';
    metaKeywords = 'This is the Keys';
  constructor() { }

}
### Page sorece

<pre id="line1">
<span class="doctype">&lt;!DOCTYPE html&gt;</span><span>&lt;<span class="start-tag">html</span> <span class="attribute-name">_nghost-0</span>=&quot;&quot;&gt;</span><span>&lt;<span class="start-tag">head</span> <span class="attribute-name">_ngcontent-0</span>=&quot;&quot;&gt;</span><span>
	</span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">_ngcontent-0</span>=&quot;&quot; <span class="attribute-name">charset</span>=&quot;<a class="attribute-value">utf-8</a>&quot;&gt;</span><span>
	</span><span>&lt;<span class="start-tag">title</span> <span class="attribute-name">_ngcontent-0</span>=&quot;&quot;&gt;</span><span>This is the Title</span><span>&lt;/<span class="end-tag">title</span>&gt;</span><span>
	</span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">_ngcontent-0</span>=&quot;&quot; <span class="attribute-name">name</span>=&quot;<a class="attribute-value">&rdquo;description&rdquo;</a>&quot; <span class="attribute-name">ng-reflect-content</span>=&quot;<a class="attribute-value">This is the Dis</a>&quot; <span class="attribute-name">content</span>=&quot;<a class="attribute-value">This is the Dis</a>&quot;&gt;</span><span>
	</span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">_ngcontent-0</span>=&quot;&quot; <span class="attribute-name">name</span>=&quot;<a class="attribute-value">&rdquo;keywords&rdquo;</a>&quot; <span class="attribute-name">ng-reflect-content</span>=&quot;<a class="attribute-value">This is the Keys </a>&quot; <span class="attribute-name">content</span>=&quot;<a class="attribute-value">This is the Keys </a>&quot;&gt;</span><span> 
	</span><span>&lt;<span class="start-tag">base</span> <span class="attribute-name">_ngcontent-0</span>=&quot;&quot; <span class="attribute-name">href</span>=&quot;<a class="attribute-value">/</a>&quot;&gt;</span><span> 
	</span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">_ngcontent-0</span>=&quot;&quot; <span class="attribute-name">content</span>=&quot;<a class="attribute-value">width=device-width, initial-scale=1</a>&quot; <span class="attribute-name">name</span>=&quot;<a class="attribute-value">viewport</a>&quot;&gt;</span><span>
	</span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">_ngcontent-0</span>=&quot;&quot; <span class="attribute-name">href</span>=&quot;<a class="attribute-value">favicon.ico</a>&quot; <span class="attribute-name">rel</span>=&quot;<a class="attribute-value">icon</a>&quot; <span class="attribute-name">type</span>=&quot;<a class="attribute-value">image/x-icon</a>&quot;&gt;</span><span>
	
</span><span>&lt;/<span class="end-tag">head</span>&gt;</span><span>
</span><span>&lt;<span class="start-tag">body</span> <span class="attribute-name">_ngcontent-0</span>=&quot;&quot;&gt;</span><span>
	</span><span>&lt;<span class="start-tag">router-outlet</span> <span class="attribute-name">_ngcontent-0</span>=&quot;&quot;&gt;</span><span>&lt;/<span class="end-tag">router-outlet</span>&gt;</span><span>&lt;<span class="start-tag">app-contact</span> <span class="attribute-name">_nghost-4</span>=&quot;&quot;&gt;</span><span>&lt;<span class="start-tag">p</span> <span class="attribute-name">_ngcontent-4</span>=&quot;&quot;&gt;</span><span>
  contact works!
</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">_ngcontent-4</span>=&quot;&quot;&gt;</span><span>
</span><span>&lt;<span class="start-tag">h1</span> <span class="attribute-name">_ngcontent-4</span>=&quot;&quot;&gt;</span><span>Add Todo</span><span>&lt;/<span class="end-tag">h1</span>&gt;</span><span>
</span><span>&lt;<span class="start-tag">form</span> <span class="attribute-name">_ngcontent-4</span>=&quot;&quot; <span class="attribute-name">class</span>=&quot;<a class="attribute-value">ng-untouched ng-pristine ng-valid</a>&quot;&gt;</span><span>
</span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">_ngcontent-4</span>=&quot;&quot; <span class="attribute-name">name</span>=&quot;<a class="attribute-value">newTodo</a>&quot; <span class="attribute-name">ng-reflect-name</span>=&quot;<a class="attribute-value">newTodo</a>&quot; <span class="attribute-name">class</span>=&quot;<a class="attribute-value">ng-untouched ng-pristine ng-valid</a>&quot; <span class="attribute-name">value</span>=&quot;&quot;&gt;</span><span>
</span><span>&lt;<span class="start-tag">button</span> <span class="attribute-name">_ngcontent-4</span>=&quot;&quot;&gt;</span><span>Submit</span><span>&lt;/<span class="end-tag">button</span>&gt;</span><span>
</span><span>&lt;/<span class="end-tag">form</span>&gt;</span><span>
</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
</span><span>&lt;/<span class="end-tag">app-contact</span>&gt;</span><span>
</span><span>&lt;/<span class="end-tag">body</span>&gt;</span><span>
</span><span>&lt;/<span class="end-tag">html</span>&gt;</span></pre>

### Issue.
addTodo() function is not responding while submit the form in contact page
After submitting the form, values are displaying in the URL as below
http://localhost:4200/contact?newTodo=Test

Below scripts tags are not displaying in page source
<p>
			&lt;script type=&quot;text/javascript&quot; src=&quot;inline.bundle.js&quot;&gt;&lt;/script&gt;<br />
			&lt;script type=&quot;text/javascript&quot; src=&quot;vendor.bundle.js&quot;&gt;&lt;/script&gt;<br />
			&lt;script type=&quot;text/javascript&quot; src=&quot;client.bundle.js&quot;&gt;&lt;/script&gt;</p>
Please resolve this issue

**Comment by pkozlowski-opensource** [comment]
Please report in https://github.com/angular/angular-cli
