### ISSUE TITLE
strange behavior when template checking undefined variable

### ISSUE THREAD

**Issue by zealitude** [angular/angular#16075]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

strange behavior when template checking undefined variable
<template ngIf="var1===undefined"></template>

**Expected behavior**

correctly check the undefined variable

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/Ombhi4bqPTCJHuzwsXZw?p=preview

the more strange part is that, plnkr behave in the opposite of my original bug.

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
You didn't bind to `ngIf`, when you do `<ng-template ngIf="expression" >` the expression is evaluated as a string, since that's exactly what you are doing. Binding to ngIf like `<ng-template [ngIf]="expression" >` will evaluate the expression instead of treating it as a string
http://plnkr.co/edit/tpdtfJXqXhrZbQjCPldj?p=preview
