### ISSUE TITLE
HTTP Request - Support other custom HTTP methods - MERGE

### ISSUE THREAD

**Issue by murraybauer** [angular/angular#16081]
**I'm submitting a ...**
```
[x] feature request
```

**Current behavior**
Unable to use HTTP MERGE method/verb.
throws new Error('Invalid request method. The method "${method}" is not supported.');

According to:
```export function normalizeMethodName(method: string | RequestMethod): RequestMethod {
  if (typeof method !== 'string') return method;

  switch (method.toUpperCase()) {
    case 'GET':
      return RequestMethod.Get;
    case 'POST':
      return RequestMethod.Post;
    case 'PUT':
      return RequestMethod.Put;
    case 'DELETE':
      return RequestMethod.Delete;
    case 'OPTIONS':
      return RequestMethod.Options;
    case 'HEAD':
      return RequestMethod.Head;
    case 'PATCH':
      return RequestMethod.Patch;
  }
  throw new Error(`Invalid request method. The method "${method}" is not supported.`);
}
```

https://github.com/angular/angular/blob/4.0.0/packages/http/src/http_utils.ts

**Expected behavior**
Either: 
1) Support HTTP MERGE method/verb in enum
2) Don't block (throw error) if a 'custom' method not pre-defined is used.

**What is the motivation / use case for changing the behavior?**
Whilst the library HTTP methods are compliant with the RFC 
https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html:

Not all established REST API's on the web fully conform.  For example, Microsoft Azure Table Storage (a NoSQL database) which uses MERGE.https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/merge-entity

**Comment by alxhub** [comment]
Hello @murraybauer,

This is currently planned for upcoming HTTP APIs.

**Comment by murraybauer** [comment]
@alxhub This has not been fixed in the latest release of the new HTTP client.

**Comment by esanzgar** [comment]
In version 4.3.1 there is a new class that allows arbitrary methods:
https://github.com/angular/angular/blob/4.3.1/packages/common/http/src/request.ts#L147-L176
https://angular.io/guide/http

I believe it should be possible to do something like this:
this.httpClient.request('MERGE', 'https://yourdomain.com, ...)

**Comment by murraybauer** [comment]
@esanzgar many thanks - hadn't pickup on the difference - that it was a new module of sorts.
