### ISSUE TITLE
compiler-cli: when using `annotateForClosureCompiler` option and target is `es6` import paths are wrongly extended

### ISSUE THREAD

**Issue by cebor** [angular/angular#16084]
I'm using https://github.com/jasonaden/simple-ui-lib as reference for my angular lib https://github.com/cebor/angular-highcharts.

The problem is that the import paths for the external dependency Highcharts are overridden wrongly.

It's reproducible in following simplified example:

```json
// package.json

{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "highcharts": "^5.0.10"
  },
  "devDependencies": {
    "@angular/compiler": "^4.0.2",
    "@angular/compiler-cli": "^4.0.2",
    "@angular/core": "^4.0.2",
    "@types/highcharts": "^4.2.54",
    "typescript": "^2.2.2"
  }
}
```

```json
// tsconfig.json

{
  "compilerOptions": {
    "module": "es2015",
    "target": "es2015",
    "moduleResolution": "node",
    "types": ["highcharts"]
  },
  "files": [
    "./index.ts"
  ],
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "strictMetadataEmit": true,
    "skipTemplateCodegen": true
  }
}
```

```typescript
// index.ts

import * as Highcharts from 'highcharts';
export { Highcharts };
```

```bash
# compiler-cli compiles index.ts to the following index.js
node node_modules/.bin/ngc
```

```javascript
// index.js

import * as Highcharts from 'highcharts/index';
export { Highcharts };
```

As you see the compiled index.js extends the import path of highcharts with `/index`, which leads to an failing import cause highcharts module has no index.js.

* When setting `"annotateForClosureCompiler": false` all works fine
* Or when setting `"target": "es5"` all works fine
* Or when removing `highcharts` from `"types": []` and deleting @types/highcharts from node_modules all works fine

**Comment by tbosch** [comment]
This is a known bug in tsickle, which we use under the hood (see https://github.com/angular/tsickle/issues/376).

**Comment by meriturva** [comment]
@cebor we have here same problem.... how you fixed it? have you disabled `annotateForClosureCompiler ` flag? so thanks.

**Comment by cebor** [comment]
@meriturva i uninstalled all "@types/*"

**Comment by meriturva** [comment]
@cebor we really cannot install/uninstall "@types/*" every time we compile with `annotateForClosureCompiler` true.
