### ISSUE TITLE
Tests running old versions of files.

### ISSUE THREAD

**Issue by QuantumInformation** [angular/angular#16083]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Minimal reproduction of the problem with instructions**

When running the tests in[ this directory ](https://github.com/QuantumInformation/money-input/tree/master/tests)I am getting an old version of the src file.

Current code:
![image](https://cloud.githubusercontent.com/assets/216566/25128187/b5cdf6fc-2430-11e7-9662-03e76965cc4d.png)

Code that is running in the browser
![image](https://cloud.githubusercontent.com/assets/216566/25128199/c5056c90-2430-11e7-8386-1a35c419d1cc.png)

**Expected behavior**

Running tests has the latest code

**Please tell us about your environment:**

Mac OSX
* **Angular version:** 2.0.X

4.0.0-rc.2
* **Browser:** [ Chrome ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by tbosch** [comment]
Hello, could you file this bug against https://github.com/angular/angular-cli?

**Comment by QuantumInformation** [comment]
yup:https://github.com/angular/angular-cli/issues/6003
