### ISSUE TITLE
Forms validation error messages are missing for built in validators

### ISSUE THREAD

**Issue by vukasin0** [angular/angular#16080]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Built in validatior `Validators.required` is applied to formControl with name `name`. 
I expect to have `form.controls['name'].errors` object filled with key/val of object returned from validator. 
Validators.required returns `{required: true}` of validation false.

This works for custom created validators (tested with async validators).

**Expected behavior**

So `console.log(form.controls['name'].errors)` should print something like this:
```
{
    required: true,
}
```

I expect to see the same for `form.errors` object as well.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/RAJDLJ3YpTwvMNMJPowE?p=preview

**What is the motivation / use case for changing the behavior?**
I would like to know which exact validator failed in array of applied validators onto formControl.

**Please tell us about your environment:**
@angular/cli, vscode editor

* **Angular version:** 
4.0.2

* **Browser:** 
all
 
* **Language:**
```
$ tsc --version
Version 2.2.2
```

* **Node (for AoT issues):**
```
$ node --version
v6.10.2
```

**Comment by Toxicable** [comment]
Errors on FormGroups are separate from errors on FormControls. They do not share errors since you can have separate validation on the separate controls

**Comment by vukasin0** [comment]
@Toxicable - OK I understand that `form.errors` and `form.controles['controleName'].errors` are separate but this doesn't work in both cases.

**Comment by vukasin0** [comment]
@Toxicable thx - I've updated plnkr to support explanation.
