### ISSUE TITLE
Change event raised by hovering with mouse over input control

### ISSUE THREAD

**Issue by coder925** [angular/angular#16082]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
If the model is changed when an input control is focused, a change event is raised if the user hover the mouse over the input control’s up and down arrows.

**Expected behavior**
There should not be a change event since the user has not changed the input.
As expected, no event occurs if the user instead simply leavs the control using for example TAB key.

**Minimal reproduction of the problem with instructions**

1. Run [the sample application](https://plnkr.co/edit/lE5BZHdoKTslRXTsp36S?p=preview) in Plunker. Press F12 to see console output.
2. Change the first input box to **200** and press tab.
Within one second the model will be updated and the second input box is showing the correct percentage.
3. Hover with mouse over the second input’s up and down arrows without clicking.

As can be seen in the console, suddenly the input control fires a change event even if nothing has changed.

**What is the motivation / use case for changing the behavior?**
In a real application I depend on that the change event only is fired when a user actually has made a change to the value.

**Please tell us about your environment:**
Microsoft Windows [Version 10.0.14393], Plunker

* **Angular version:** 4.0.2

* **Browser:** Chrome 57.0.2987.133 (64-bit)

Not reproducable in Edge 38.14393.1066.0 (as there are no up/down arrows)
Not reproducable in Firefox 52.0.2 (32-bitars).

* **Language:** all

* **Node (for AoT issues):** `node --version` = v6.10.1 (on local machine)

**Comment by alexzuza** [comment]
https://jsfiddle.net/c6yajvwx/

**Comment by coder925** [comment]
@alexzuza, thank you for simplifying my reproduction code. I conclude from your code that this issue is related to Chrome and not to Angular. Anyone know if this bug already been reported to Chrome?

**Comment by kara** [comment]
This doesn't seem like an Angular forms issue, so closing.
