### ISSUE TITLE
Unit test setup should be available in bundled Angular

### ISSUE THREAD

**Issue by juliemr** [angular/angular#1609]
It should be easy for consumers of Angular to set up unit testing. A basic setup should be shown for the scenarios outlined in https://github.com/rkirov/ng2-bundle.

- A version of Angular including TestBed should be available for use when unit testing components.
- a solution for solving loading in Karma should be available.

**Comment by naomiblack** [comment]
@juliemr can you prioritize this for the coming week, to get jeremy's unit tests for angular material unblocked?

**Comment by juliemr** [comment]
Yup!

**Comment by naomiblack** [comment]
This work is done now. Using *Test Component Builder* is the recommended solution.

**Comment by firecube** [comment]
Hi naomiblack,

Are there any examples on how to use this approach with our own components?

Thanks.

**Comment by dpsthree** [comment]
I'm also having a hard time deciphering its usage.
