### ISSUE TITLE
router subscription executed inside of Angular zone even when wrapped in runOutsideAngular()

### ISSUE THREAD

**Issue by magnattic** [angular/angular#16092]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```
**Current behavior**
It seems that runOutsideAngular() is not working consistently in combination with routing.

If I surround a subscription to ActiveRoute.params with ``ngZone.runOutsideAngular()`` within a component, it will run outside of the Angular zone for the initial navigation, but return to the zone for subsequent router navigations.

**Expected behavior**
If I wrap any subscription in ``ngZone.runOutsideAngular()``, I would expect the code to run outside of zone consistently.

**Minimal reproduction of the problem with instructions**
Minimal working example: http://plnkr.co/edit/bg3nuimPGNppsF5wX20h?p=preview

There is one default redirection in the routes to '/foo' and one manually in the SubComponent to '/foo2'.

The console output shows the strange behaviour:
```
param: foo, run outside of zone: true
param: foo2, run outside of zone: false // <-- I would expect this to be true!
```

The relevant code is in sub.component.ts:

```
@Component({
  template: 'RouteParam: {{ activeRoute }}'
})
export class SubComponent {
  public activeRoute: string;

  constructor(private route: ActivatedRoute, private ngZone: NgZone, private router: Router) {
    
    this.ngZone.runOutsideAngular(() => {
      route.params
        .map(params => params['routeParam'])
        .do(param => console.log('param: ' + param + ', run outside of zone: ' + !NgZone.isInAngularZone()))
        .subscribe(param => this.activeRoute = param);
      
      this.router.navigate(['foo2']);
    });

  }
}
```

**What is the motivation / use case for changing the behavior?**
I want to combine the params with HTTP polling, so I need the subscription to run outside of the ngZone or protractor will time out. (see http://stackoverflow.com/questions/36358405/how-to-implement-intervals-polling-in-angular2-to-work-with-protractor)

**Please tell us about your environment:** Windows 10, Angular CLI 1.0.0-rc.1

* **Angular version:** reproduced with 2.4.0 and 4.0.2

* **Browser:** all
 
* **Language:** TypeScript 2.0.0

**Comment by magnattic** [comment]
Possibly related to https://github.com/angular/angular/issues/15770?

**Comment by magnattic** [comment]
Is there any workaround I can use? This kills (as in: times out) my protractor tests when switching routes...

**Comment by jasonaden** [comment]
I believe this is related to an issue between Rx and Zones: https://github.com/ReactiveX/rxjs/pull/2266

Please track that issue for updates.

**Comment by JiaLiPassion** [comment]
@jasonaden, , this one has been closed https://github.com/ReactiveX/rxjs/pull/2266.
@magnattic, and now `zone.js` has a new patch for `rxjs`, you can try to 
```javascript
import 'zone.js/dist/zone-patch-rxjs';
```
in `polyfill` after `import zone`

**Comment by chriszrc** [comment]
Wow, I just spent hours trying to figure out why the angular router wasn't fully rendering auxiliary routes, and it turns out just adding this import solved the problem. The calls to `router.navigate` were coming from a leaflet map, and even though it had the right reference to the angular component, it somehow wasn't triggering the zone and the view wasn't refreshing-
