### ISSUE TITLE
Stale news headline on the front page of aio

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16094]
**I'm submitting a ...**  (check one with "x")
`[x]` bug report

**Current behavior**
The main headline on the front page is stale referring to "Join us for DEVintersection Amsterdam Nov 14-16!REGISTER NOW".

-----
<img width="825" alt="screen shot 2017-04-18 at 5 54 27 pm" src="https://cloud.githubusercontent.com/assets/216296/25140310/255c96e8-2460-11e7-88ac-b5f6d5dc102f.png">

----

**Expected behavior**
We should copy the headline from the current angular.io and refer to Angular v4.0 instead.

**Comment by sjtrimble** [comment]
Updated to what the current site displays.
