### ISSUE TITLE
aio recals and reflows several time during loading causing flicker

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16096]
![profile-20170418t181636](https://cloud.githubusercontent.com/assets/216296/25141254/4e43cbaa-2463-11e7-9fb3-7822b493eba3.gif)

The screen capture above shows what the users have to go through in order to see the page load. The user experience would be much better if the site rendered without recalcs and reflows. This can be achieved by loading all styles before rendering anything and providing dimensions of all lazy loaded resources (mainly images) via css or html width/height attributes.

-----

note for future reference: I generated the screenshot by capturing the page load via chrome devtools with cpu throttling at 20x and network throttling at 2G. Then I fed the resulting profile file into [an gif generator](https://blog.hospodarets.com/demos/chrome-timeline-to-gif)

**Comment by petebacondarwin** [comment]
I think this is much better now @IgorMinar. We now specify the width and height of images.
Can we close this one?

See the latest profile:
![profile-20170510t114654](https://cloud.githubusercontent.com/assets/15655/25895207/e27527a0-3576-11e7-8509-7b642f5a7672.gif)

**Comment by gkalpak** [comment]
@IgorMinar, could this be closed?

**Comment by gkalpak** [comment]
Closing. Please reopen if still an issue :grin:
