### ISSUE TITLE
API page uses inconsistent alignment of visual elements

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16098]
**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior**
The filter is center-aligned, while the individual items are left-aligned. This results in weird UX:

<img width="1878" alt="screen shot 2017-04-18 at 6 31 16 pm" src="https://cloud.githubusercontent.com/assets/216296/25141922/769003f6-2465-11e7-974d-6ef9d998f829.png">

**Expected behavior**
Use consistent alignment.

**Comment by sjtrimble** [comment]
On it.

**Comment by IgorMinar** [comment]
@sjtrimble I see that this issue is still open, but the PR referencing it was merged already. I still see that the filter input controls are not aligned with the results.  The results are now padded to the right, but not quite centered, while the filter controls are centered. Is this intentional?
<img width="1567" alt="screen shot 2017-04-25 at 12 23 05 am" src="https://cloud.githubusercontent.com/assets/216296/25361380/20b05ae2-294e-11e7-871e-f043fd9315af.png">

**Comment by gkalpak** [comment]
FWIW, the results are technically centered (more obvious [on wide screens][1]), but each columns is wider than most entries, so it looks like there is more padding on the right. (But I agree it doesn't look nice on many screens.)

[1]: https://cloud.githubusercontent.com/assets/8604205/25381636/2f76790c-29bd-11e7-9250-11286df16e5a.png

**Comment by sjtrimble** [comment]
What George said :)

PR #16301 should address this with the max-width. I'm doing several updates on the API pages in general, so this will change a bit with PR #16327 as well.
