### ISSUE TITLE
docs(aio): why recommend catching bootstrapping errors, but not do so in angular-cli?

### ISSUE THREAD

**Issue by bedag-moo** [angular/angular#16095]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The style guide [writes](https://angular.io/docs/ts/latest/guide/style-guide.html#!#02-05):

> Do include error handling in the bootstrapping logic.

but no such handling is generated by angular/cli. Also, the style guide gives no rationale for catching errors here, and doing so in Angular 4 causes most bootstrapping errors to be logged twice: First by the ErrorHandler, then by the catch block.

**Expected behavior**
angular-cli and the style guide should agree on best practices. The style guide should document why a practice is best.

**Comment by jenniferfell** [comment]
filename=https://angular.io/guide/styleguide

**Comment by jelbourn** [comment]
Closing since CLI now does this
