### ISSUE TITLE
Weird highlight of the Doc menu item in the main menu

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16097]
**I'm submitting a ...**  (check one with "x")
`[x]` bug report

**Current behavior**
Weird vertical lines on both sides of the Docs menu item in the main header.

------
<img width="748" alt="screen shot 2017-04-18 at 6 25 54 pm" src="https://cloud.githubusercontent.com/assets/216296/25141748/d0d48a72-2464-11e7-96ba-9ee2514f2cbe.png">

------

**Expected behavior**
No weird stuff. :-)

**Minimal reproduction of the problem with instructions**
1. navigate to https://aio-staging.firebaseapp.com/
2. click on the "Docs" menu item in the header
3. click on the "Features" menu item

The line should now be present around the "Docs" menu item.

No other menu items have this issue, so I think it might be related to the side navbar.

**Comment by sjtrimble** [comment]
I think this has to do with the click handler for routing. We should be removing the focus ring after navigation. 

Can someone familiar with the routing take a look at this?

**Comment by gkalpak** [comment]
The "vertical lines" is a blue outline applied by default to any `:focus`ed element by Chrome. We could easily overwrite that.
What I can't understand is why this only affects the "Docs" link? Other nav-var anchors do not match the `:focus` selector even if they are the `document.activeElement` 😕

**Comment by gkalpak** [comment]
@IgorMinar was right. It is seems to be the sidenav that [tries to return focus][1] back to the element that was focused before is was opened. This does this be calling `.focus()`, which makes the anchor match `:focus`.

We should: 
(a) Remove the default outline.
(b) Somehow stop `MdSidenav` from messing with our focus :smiley:
     This could be an `MdSidenav` bug: If the focus is already outside of the sidenav, I don't see why return focus back to the element that had focus before opening the sidenav.

[1]: https://github.com/angular/material2/blob/76faae5f378f2949bbe215df38369190773eba60/src/lib/sidenav/sidenav.ts#L146

**Comment by gkalpak** [comment]
For (b), I opened angular/material2#4203.
@sjtrimble, can you take care of (a)?

**Comment by petebacondarwin** [comment]
This is now fixed visually.
