### ISSUE TITLE
The Alphabet index on the glossary content page is broken and kind of useless 

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16106]
**Current behavior**
The glossary page contains links to various letters of the alphabet like: https://aio-staging.firebaseapp.com/guide/glossary#J

------
<img width="1077" alt="screen shot 2017-04-18 at 7 11 50 pm" src="https://cloud.githubusercontent.com/assets/216296/25143523/137eb9be-246b-11e7-89d6-6d897265f718.png">

------

Unfortunately most links don't do anything.

I'd actually argue that this kind of table of content is not that useful, we should instead add a new section into the search results that would deep link to the glossary.

**Comment by wardbell** [comment]
Let's get Jules take on this. Virtually every glossary I've seen has this kind of Alpha thumbnail, albeit usually prettier. 

The _should_ work. If they don't, the certain task is to fix them.

**Comment by IgorMinar** [comment]
since the links work now. I'm going to close this one.
