### ISSUE TITLE
Left & Right arrows in tabs don't do anything useful when there are many tabs

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16107]
**Current behavior**
If I look at an example component with tabs that has too many tabs to display, left and right arrows appear. If I click these, nothing useful happens. 
<img width="1048" alt="screen shot 2017-04-18 at 7 17 39 pm" src="https://cloud.githubusercontent.com/assets/216296/25143935/8341ecca-246c-11e7-8233-a677080e5ec6.png">

**Expected behavior**
I'd expect to be able to select various tabs and especially get access to tabs that are not visible.

**Minimal reproduction of the problem with instructions**
1. go to https://aio-staging.firebaseapp.com/guide/style-guide
2. scroll down to Style 04-10
3. play with the tabbed example component

**Comment by petebacondarwin** [comment]
I have opened an issue with the Material team: https://github.com/angular/material2/issues/4176

**Comment by petebacondarwin** [comment]
Closed by #16206 

(@sjtrimble - if you added a `Closes #16107` in your commit message then this issue would have auto closed when the PR was merged.)
