### ISSUE TITLE
Odd rendering artifacts in sidenav when it's being rendered for the first time

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16100]
**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior**
When the sidenav is being rendered for the first time, there are several weird rendering artifacts present on the screen before it is rendered in its final state. This causes unnecessary flicker.

At minimum there are "key" text nodes present in place where eventually arrows will be rendered:
----
<img width="2006" alt="screen shot 2017-04-18 at 6 46 41 pm" src="https://cloud.githubusercontent.com/assets/216296/25142764/64c23a6a-2468-11e7-9631-b54976d31645.png">

----

There also seems to be some kind of vertical text along the right edge of the sidenav that I wasn't able to capture on a screenshot.

**Expected behavior**
No flicker.

**Comment by wardbell** [comment]
I don’t know how to cure the artifacts described by @igorminar in issue 16100. Presumably they occur on slow network/slow device. The word "key" is likely the consequence of delayed processing of the `<md-icon>`. Here's the source:
```
<md-icon class="rotating-icon">keyboard_arrow_right</md-icon>
```
Is there a way to know when the `<md-icon>` has done its job? Or when Angular had done its job? I suppose we could hide the nav items until `afterViewInit` + a tick. If we start going down that road, I fear the wheels just come off of Angular altogether. 

To whom should we turn?

**Comment by gkalpak** [comment]
> There also seems to be some kind of vertical text along the right edge of the sidenav that I wasn't able to capture on a screenshot.

I think I found out what this is: ![sidenav artifact][1]. (It also comes in horizontal flavor for the rotated icons of expanded accordions).
It is the `keyboard_arrow_right` text, after our CSS has been, but before the Material font has relaced the text with the icon.

So #16226 would solve this too.

[1]: (https://cloud.githubusercontent.com/assets/8604205/25326917/d0d77618-28da-11e7-8992-204aa0583e7e.png)
