### ISSUE TITLE
Do no animate the sidenav during the first rendering

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16101]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When a user enters the page at https://aio-staging.firebaseapp.com/docs we animate the slideing out of the navbar. This animation is distracting, unnecessary, and only adds to the flicker that happens during the initial rendering of the page.

**Expected behavior**
The animation should be present only when we navigate from a marketing page to the docs page. Not when we enter the site at the docs/

**Minimal reproduction of the problem with instructions**
1. go to https://aio-staging.firebaseapp.com/docs 
2. reload the page several times

**Comment by wardbell** [comment]
Closed by PR #16297
