### ISSUE TITLE
Code of conduct link missing from the footer

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16105]
**Current behavior**
Somehow even on the old page we missed to add a link to the code of conduct into our footer.

I'm not sure which section is most appropriate. It could go in either Help or Community. 

Since Community is already long, I suggest we add it to the Help section as the last item.

<img width="801" alt="screen shot 2017-04-18 at 7 06 30 pm" src="https://cloud.githubusercontent.com/assets/216296/25143393/82bb8e66-246a-11e7-83de-55eb553fd77b.png">

**Comment by petebacondarwin** [comment]
https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md
