### ISSUE TITLE
Show loading indicator when document viewer is loading new content after navigation

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16110]
**Current behavior**
Currently there is no visual doohickey telling user that after they clicked on a link in the sidenav the content in the document viewer is stale and will be replaced once the new content is downloaded. This results in potentially confusing behavior for users if their network connection is slow.

**Expected behavior**
It would be nice to see some kind of visual indication that the viewer is loading new document. Either a subtle spinner (easy) or a youtube style progress bar (trickier to do since to make it meaningful we'd have to hook it up with XMLHttpRequest progress events).

In any case, we the ux element should be subtle and not overly distracting.

**Comment by sjtrimble** [comment]
Design to be implemented based on certain events in the process:
![aio-loading-mockup-vs1](https://cloud.githubusercontent.com/assets/2958442/25460315/a1ba93d8-2a97-11e7-9e9b-68442464e9cc.png)

**Comment by petebacondarwin** [comment]
The `http` library does not support progress out of the box. So to display this loader with meaninful progress will require one of three things:

a) install and use a 3rd party adapter for `http` library: e.g. https://github.com/DarkXaHTeP/angular-progress-http
b) ditch `http` and use barebones APIs, such as `fetch` or `XHR`, directly
c) wait for @alxhub to release `HttpClient` to us (perhaps as an early preview?)

**Comment by gkalpak** [comment]
We could at least show an indeterminate progress bar (until the new HttpClient is usable).

**Comment by IgorMinar** [comment]
@wardbell I spoke with @petebacondarwin and he suggested that we use the indeterminet progress bar from material: https://material.angular.io/components/component/progress-bar I'm totally fine with this and it simplifies the implementation quite a bit since we don't need to worry about progress points to tie the animations to. I think this is a good idea.

can you use the placement that @sjtrimble suggested, but use the material progress bar.
