### ISSUE TITLE
docs(aio): create the include embedded component and fill it

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#16119]
We want a new component to add some common includes. But first we need to research how many they are.

**Comment by petebacondarwin** [comment]
I could do with some more information about what this is and why it needs to be an embedded component.

**Comment by Foxandxss** [comment]
Yes!

We have this jade includes:

https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/tutorial/toh-pt5.jade#L27

And we would need to port them to the new site. @wardbell thought about creating a embedded component that would pick a .md and include it in another one. So we could have this `_see-addr-bar` somewhere and include it where needed.

He also pointed that it depends in how many times we use it and seems that only use it there and 3-4 times in the router.

**Comment by petebacondarwin** [comment]
I believe that this could be done more easily in dgeni (maybe using an inline tag) similar to how we inject examples, rather than dynamically in the app.

**Comment by Foxandxss** [comment]
I am all in for that.

**Comment by wardbell** [comment]
Given that we are striving to make docs _smaller_, I'm less inclined than ever to perpetuate the include.

**Comment by petebacondarwin** [comment]
Are we ever actually going to do this? It seems unlikely now. Shall we close @Foxandxss and @wardbell ?
