### ISSUE TITLE
Spacing between the H1 and top header seems a bit insufficient

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16114]
**Current behavior**
<img width="852" alt="screen shot 2017-04-18 at 7 57 43 pm" src="https://cloud.githubusercontent.com/assets/216296/25145420/6e10c754-2471-11e7-891c-17998fb064c9.png">

**Expected behavior**
Maybe add a tad more space so that the header doesn't look so crammed?

**Comment by sjtrimble** [comment]
This PR addresses this: https://github.com/angular/angular/pull/16061

Just stuck with Travis errors I cannot figure out.

**Comment by IgorMinar** [comment]
resolved. thanks @sjtrimble
