### ISSUE TITLE
The sidenav in the resources page is rendered over the main content

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16113]
**Current behavior**
1. go to https://aio-staging.firebaseapp.com/resources
2. scroll down half a page

You'll see:
<img width="1161" alt="screen shot 2017-04-18 at 7 53 22 pm" src="https://cloud.githubusercontent.com/assets/216296/25145205/cbe8aa0a-2470-11e7-8451-4300f58b20d7.png">

The menu is overlaid on top of the main content, and does not scroll with the page as expected.

**Comment by sjtrimble** [comment]
I believe the plan here was to remove this and replace with the finished TOC. @wardbell do you know?
