### ISSUE TITLE
Search is not accessible

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16129]
**Current behavior**
At minimum we should do the following three things:

1. assign a keyboard shortcut that will activate search, `/` is common, but there are other precedences as well
2. ensure that one can navigate from the search input box to results via a single tab, and then advanced through results via tab
3. enable closing the search results via escape (remain on the current page) or enter (navigate to the highlighted result)

**Comment by IgorMinar** [comment]
@wardbell can you take on this one?

**Comment by petebacondarwin** [comment]
Items 2 and 3 are already fixed. So once #16636 lands 1 will also be fixed.
