### ISSUE TITLE
Quickstarts are missing headers

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16124]
**Current behavior**

Basic quickstart:
<img width="1189" alt="screen shot 2017-04-18 at 8 34 49 pm" src="https://cloud.githubusercontent.com/assets/216296/25147066/794d1122-2476-11e7-8cd5-d3be84cb30ee.png">

-----
CLI quickstart:
<img width="1206" alt="screen shot 2017-04-18 at 8 34 56 pm" src="https://cloud.githubusercontent.com/assets/216296/25147077/82c87d90-2476-11e7-816c-3a4f8cf054e1.png">

**Comment by sjtrimble** [comment]
Done. https://github.com/angular/angular/pull/16138
