### ISSUE TITLE
Lazy load all embedded components to shave off bytes needed for initial rendering

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16127]
**Current behavior**
We load all material components and embedded components upfront - even if we don't need them.

**Expected behavior**
All embedded components should be lazy loaded and prefetched instead.

This will require us to refactor the site a bit. In the first step we should just move all the embedded components into a single NgModule that is lazy loaded and along with that change, move most material modules to that module.

Later, we can be more sophisticated and break the ngmodule with embedded components into smaller units and load those on as needed basis.

**Comment by JLuitjens** [comment]
https://oclazyload.readme.io/
