### ISSUE TITLE
Add anchors & anchor icons to all headers

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16126]
**Current behavior**
It's not possible to link to an arbitrary header in a document content.

**Expected behavior**
Github and many other sites (wikipedia?) allow you to however over any header and activate an icon that allows the reader to construct or navigate to the current page and scroll down to the selected header. Example from https://github.com/angular/angular:

<img width="448" alt="screen shot 2017-04-18 at 8 58 11 pm" src="https://cloud.githubusercontent.com/assets/216296/25148109/0840de88-247a-11e7-83af-198ec2822c8c.png">

It would be awesome to have this feature for all of our headers, as this would allow us to completely get rid of the address bar on mobile devices, because there the anchor could be used to retrieve the url of the current page.

**Comment by petebacondarwin** [comment]
I have a fix for this... just tidying up the PR.
