### ISSUE TITLE
Content errors in the the main docs page

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16122]
**Current behavior**
Navigate to https://aio-staging.firebaseapp.com/docs and you'll see:

<img width="1071" alt="screen shot 2017-04-18 at 8 01 53 pm" src="https://cloud.githubusercontent.com/assets/216296/25146969/24a7eb2e-2476-11e7-89de-e1a4f9b8cbe6.png">

1. The page should not claim that version of the docs is 4.0.0 and there should be no space between "v" and "4". We should say that these are "v4" docs unless we rea
lly want to update them every time we cut a new minor.
2. Mentioning the changelog without a link is not useful. I don't know what's the purpose of the changelog for the docs that is separate from the changelog of Angular itself. We should find a way to unite these two an in the meantime not mention it here at all.
3. There is a typo in the last sentence about v2 docs.
4. The developer guide link is broken, it leads to `https://aio-staging.firebaseapp.com/..api`.

**Comment by sjtrimble** [comment]
I addressed most of these items.

@IgorMinar The text was provided by Jules, so she might have some input on the versioning (v4 versus vs4.0.x

3. Can you verify the typo?
5. Where does vs2.angular.aio go? Wasn't sure what link to use for that.

**Comment by wardbell** [comment]
Then I worked the page over some more in PR #16132. I found the version naming strange as well. I took the liberty of "fixing it" and moving it all _below_ the card. Then I extended the cards to better align with the sidenav.

I repaired/added links.
