### ISSUE TITLE
$location.search() doesn't take initial query parameters into account without Html5Mode

### ISSUE THREAD

**Issue by monokrome** [angular/angular#1613]
If you visit `http://example.com/?domain=example.com` and run `$location.search()` without `Html5Mode` enabled, then you will get `{}`. I would expect to get `{domain: "example.com"}`. If you visit `http://example.com/#?domain=example.com` then you will get the expected result.

I feel like Angular should be carrying over the parameters from the original URL in this case. If this is agreed then I will be happy to pursue a pull request.

Thanks!

**Comment by pkozlowski-opensource** [comment]
@monokrome this is wrong repo, you should check https://github.com/angular/angular.js

But I think your analysis is incorrect and the observed behaviour is correct. You should be getting `{domain: "example.com"}` output in hasbang mode with URLs like: `http://example.com/#?domain=example.com` only.
