### ISSUE TITLE
AOT issues with form having HTML validation attributes

### ISSUE THREAD

**Issue by pranPC** [angular/angular#16146]
**I'm submitting a ...**  (check one with "x")

[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see

**Current behavior**
I have login html having form attributes like required, minlength, maxlength etc. The below is part of my login html form.

`<div class="form-group">
        <label for="officerId">Officer ID</label>
        <input class="form-control" type="text" placeholder="Enter your Officer ID" autocomplete="off"
               name="officerId" id="officerId"
               [(ngModel)]="user.name" minlength="5" #officerId="ngModel" required/>
        <div [hidden]="officerId.valid || officerId.pristine"
             class="alert alert-danger">
          <small *ngIf="officerId.errors?.required" class="errorText"> Officer Id is required</small>
          <small *ngIf="officerId.errors?.minlength" class="errorText"> Please enter at least 5 characters.</small>
        </div>
      </div>
`

ng build --aot gives me the following errors -

ERROR in Z:/WebstormProjects/callhealth2-cli/src/$$_gendir/app/login/login.component.ngfactory.ts (604,127): Property 'required' does not exist on type '{ [key: string]: any; }'.
Z:/WebstormProjects/callhealth2-cli/src/$$_gendir/app/login/login.component.ngfactory.ts (607,127): Property 'minlength' does not exist on type '{ [key: string]: any; }'.

**Expected behavior**
This should build properly

**Please tell us about your environment:**
windows 10

* **Angular version:** 2.0.X
angular 2.4.10
 
* **Node (for AoT issues):** `node --version` =   
angular-cli: 1.0.0-beta.28.3
node: 6.10.0

**Comment by TheZeroNine** [comment]
This is related to AoT. Use: `officerId.hasErrors('required')` instead of `officerId.errors?.required`

More details on this can be found here: https://github.com/qdouble/angular-webpack2-starter#aot--donts

**Comment by pkozlowski-opensource** [comment]
Thnx @TheZeroNine
