### ISSUE TITLE
Angular-Performance NG2 Vs NG4

### ISSUE THREAD

**Issue by moorthi07** [angular/angular#16141]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Here is the performance study results.. 
"Angular JS - Performance Ng2 vs Ng4" https://www.linkedin.com/pulse/angular-js-performance-ng2-vs-ng4-moorthi-pichaikannu

Final result comes to ,
ANGULAR 4 - Reduced the file size about 1 MB and the Load time about .50 s

**Expected behavior**

Is this the optimal performance? or can it be tuned in?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Performance 

**Please tell us about your environment:**

Visual Code, Windows 10
* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
5.6

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
