### ISSUE TITLE
Error when generate custom module

### ISSUE THREAD

**Issue by qiluo** [angular/angular#16145]
**I'm submitting a bug**  (check one with "x")

**Current behavior**
I'm writing a custom module which is a shared utility module, but I got error 
```
Runtime Error
Uncaught Error: Unexpected value 'JsonHttpClient' declared by the module 'MyCustomModule'. Please add a @Pipe/@Directive/@Component annotation
```

**Expected behavior**
Custom module could be imported by other module

**Minimal reproduction of the problem with instructions**
Module definition
```
import { NgModule } from '@angular/core';
import { HttpModule } from '@angular/http';
import { CommonModule } from '@angular/common';
import { JsonHttpClient } from './json-http-client';

@NgModule({
    imports: [CommonModule, HttpModule],
    declarations: [JsonHttpClient],
    exports: [JsonHttpClient],
    providers: []
})
export class MyUtilModule { }
```

json-http-client.ts (short version)
```
import { Injectable } from '@angular/core';
import { Http, Request, Response, Headers, RequestOptionsArgs, RequestMethod } from "@angular/http";

@Injectable()
export class JsonHttpClient {
    constructor(private _http: Http) {
        this.headers = new Headers();
        this.headers.append('Content-Type', 'application/json');
        this.headers.append('Accept', 'application/json');
    }
  
    // ...
}
```
app.module.ts (short version)
```
import { MyCustomModule } from '../my-custom-module';

@NgModule({
  declarations: [
    MyApp,
  ],
  imports: [
    BrowserModule,
    HttpModule,
    MyCustomModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp
    HomePage
  ],
  providers: [
    { provide: ErrorHandler, useClass: IonicErrorHandler }
  ]
})
export class AppModule { }
```

**What is the motivation / use case for changing the behavior?**
I want to modularize some utiltiy class for better reuse so I need encapsulate them into module. In my case, the util is not a pipe/component or whatever, I was confused with error message

**Please tell us about your environment:**
OSX Serria

* **Angular version:** 4.0.0, @angular/cli 1.0.0

* **Browser:** [Chrome 56]
 
* **Language:** [TypeScript 2.2.1]

* **Node (for AoT issues):** `node --version` =   6.10

**Comment by pkozlowski-opensource** [comment]
`JsonHttpClient` is a _module_ so it should go into _imports_ not _declarations_.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
