### ISSUE TITLE
Property  'userPassword' does not exist on type 'FormGroup'  issue in primeng 4.0 with angular CLI 1.0

### ISSUE THREAD

**Issue by vinodkumar526** [angular/angular#16159]
I am trying to migrate my project from primeng 1.0 to 4.0ver 
I am facing the compilation issue above as i have mentioned 
I am using versions angular cli 1.0.0,ts 2.0,angular 4, es5 (Stack is angular CLI 1.0.0 ver stack)

import { UserPassword } from './../../models/userPassword.model'
import { GlobalSharedService } from './../../services/globalSharedService'
import {Component, OnInit} from '@angular/core';
import {Router} from '@angular/router';

import { Validators, FormControl, FormGroup, FormBuilder } from '@angular/forms';
//import {ROUTER_DIRECTIVES} from '@angular/router';
import {GlobalEventsManager} from "./../globalEventsManager.component";
import {ChangePasswordService} from './../../services/changePasswordService.service';
import { SharedComponent } from './../shared.component';

@Component({
    templateUrl: './changePassword.html',
   // selector: 'loginUser',
    providers:[ChangePasswordService,SharedComponent]
})

export class ChangePasswordComponent implements OnInit {
    frmUserPassword = new UserPassword();
    cols: any[];
    changePasswordform:FormGroup;
    constructor(private _router: Router,private changePasswordService:ChangePasswordService ,private globalSharedService:GlobalSharedService,private globalEventsManager: GlobalEventsManager,private sharedComponent : SharedComponent) {
       this.changePasswordform = new FormGroup({
            userPassword: new FormControl(),
            newPassword: new FormControl(),
            confirmPassword: new FormControl(),
            userId: new FormControl()
            });
  }
    ngOnInit() {
    }
   changePassword(){
      
      this.changePasswordform.userPassword=this.frmUserPassword.userPassword;
      this.changePasswordform.newPassword=this.frmUserPassword.newPassword;
      this.changePasswordform.confirmPassword=this.frmUserPassword.confirmPassword;
     
      if(this.frmUserPassword.newPassword==this.frmUserPassword.confirmPassword)
        {
        this.changePasswordService.changePassword(this.globalSharedService.getJWTHeader(), this.frmUserPassword).subscribe();
      }   
    this._router.navigate(['frmUser']);
    }
    cancelAction(){
        this._router.navigate(['frmUser']);
    }
}

Error::

ERROR in D:/PROJECT/Angular_cli/Development/jpaf_web_angular/src/src/app/modules/change-password/changePassword.component.ts (46,31): Property
 'userPassword' does not exist on type 'FormGroup'.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
