### ISSUE TITLE
Unable to get value of the property 'apply': object is null or undefined; Zone:<root>; Task:Promise.then;

### ISSUE THREAD

**Issue by inggil2407** [angular/angular#16155]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

can't use http get on IE 9, in chrome and mozilla work well,
all pollyfills.ts for IE 9 is actived
version angular 4.00, version typescript 2.2.0
**Expected behavior**
can use http get on IE 9

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
Please add:

> Minimal reproduction of the problem with instructions

**Comment by inggil2407** [comment]
Minimal reproduction of the problem with instructions

[http://plnkr.co/edit/oClr6mDFTnGrL60qa9Ec?p=preview](http://plnkr.co/edit/oClr6mDFTnGrL60qa9Ec?p=preview)
