### ISSUE TITLE
elements generated by jquery are not seen/captured by @Directive

### ISSUE THREAD

**Issue by icenold** [angular/angular#16158]
Directive Selector: '.clicker'

//-----app.component.html
```
<h1>
  {{title}}
</h1>

//this is captured by my directive and effectively added a click event via 'HostListener'
<button class="clicker" >abcd</button>


<div id="test" >
//im going to put a button inside here with class "clicker"...the directive does nothing to this element
</div>
```

I'm using jqPuzzle plugin to generate a slide puzzle but I need to add additional events when the user clicks and everybody has recommended it should by done via Directive

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by icenold** [comment]
@ericmartinezr  and why is this not a bug? CMIIW but attribute directives are made to mark and capture elements that are marked by the directives. This feature is supported by angularJS and is clearly a bug on Angular2.

**Comment by Toxicable** [comment]
@icenold please provide a plunkr heres a template https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 , to show how this is a bug with Angular.
Also note that directives cannot be Dynamically added

**Comment by vicb** [comment]
Angular compiles the templates before the application starts - any node added after will not been "handled" by Angular.
