### ISSUE TITLE
http://ui-grid.info/ not working

### ISSUE THREAD

**Issue by faraziny** [angular/angular#16166]
My app was working fine but suddenly it broke today due to unavailability of http://ui-grid.info/

Please find the error below for reference.

Uncaught Error: [$injector:modulerr] Failed to instantiate module chmApp due to:
Error: [$injector:modulerr] Failed to instantiate module ui.grid due to:
Error: [$injector:nomod] Module 'ui.grid' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=ui.grid
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:68:12
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:1958:17
    at ensure (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:1882:38)
    at module (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:1956:14)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4362:22
    at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:336:20)
    at loadModules (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4346:5)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4363:40
    at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:336:20)
    at loadModules (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4346:5)
http://errors.angularjs.org/1.4.3/$injector/modulerr?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by faraziny** [comment]
But how can somebody help on stackoverflow if the required component is not even available

**Comment by faraziny** [comment]
i repeat http://ui-grid.info/ is down

**Comment by gkalpak** [comment]
In addition to what @ericmartinezr said, this seems to be an AngularJS (1.x) issue (while the repository is for Angular (2+)). In any case, the fact that `ui.grid` is not available when your app is bootstrapped indicates an issue with your application setup, not with AngularJS or `ui.grid`.

Also note that `ui.grid` is a 3rd party library (not maintaned by the Angular/AngularJS team), so you should report issues with their website on their repo.

**Comment by faraziny** [comment]
Now that's a better explanation. Thanks.
