### ISSUE TITLE
angular 4 template for visual studio 2015?

### ISSUE THREAD

**Issue by sachinjkarche** [angular/angular#16169]
Hi all i am new to angular 2, i am learning. and today got to know angular 4 already came. Is there any angular 4 template for visual studio 2015 like angular 2?

**Comment by tinchou** [comment]
Wouldn't say there's any official Angular 4 template yet, but take a look at this for some context: https://github.com/aspnet/JavaScriptServices/issues/800. There's also @MarkPieszak's advanced template https://github.com/MarkPieszak/aspnetcore-angular2-universal (yes, it was updated to Angular 4 despite the project name).

**Comment by MarkPieszak** [comment]
Thank you Martin.

@sachinjkarche Also don't forget Angular 2 & 4 are the same thing, it's just "Angular" now 😄 (the version numbers aren't used anymore).

Also note the template is for VS2017 now that it's released and project.json is gone.

**Comment by icenold** [comment]
> Thank you Martin.
> 
> @sachinjkarche Also don't forget Angular 2 & 4 are the same thing, it's just "Angular" now 😄 (the version numbers aren't used anymore).
> 
> Also note the template is for VS2017 now that it's released and project.json is gone.

But when I make google searches with keyword "Angular" the search engine always gives me results related to AngularJS....Can't they rename it to AngularTS instead?

**Comment by tinchou** [comment]
That's a very innocent request 😁. Short answer is they won't do that and you'll have to adjust your search patterns.

Long answer is... Well, there are blog posts from the team about this, you should look for those.

**Comment by icenold** [comment]
```
That's a very innocent request 😁. Short answer is they won't do that and you'll have to adjust your search patterns.

Long answer is... Well, there are blog posts from the team about this, you should look for those.
```
Most of their documenations are incomplete. They don't even have list of events for '@Hostlistener' class and they didn't even mention that directives cannot see/capture elements generated by jquery

**Comment by sachinjkarche** [comment]
Thanks @tinchou specified URL have template with angular 4 template for vs2015. still i am facing issue while running this and getting error which i observed in angular 2 with .net core as well.

//////////////////////////////////
HTTP Error 502.5 - Process Failure
Common causes of this issue:

The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port

/////////////////////////////////////////
Event Viewer Details: 

Failed to start process with commandline '"%LAUNCHER_PATH%" %LAUNCHER_ARGS%', ErrorCode = '0x80070002'.
Source: Express AspNetCore Module

------------------

reinstall .net core, created separate app pool, full permission for folder..but didn't help.

Is any thing i am missing.?

**Comment by sachinjkarche** [comment]
@icenold  I think i have to try this using VS2017..i will update once done.

**Comment by MarkPieszak** [comment]
Yes it's VS2017 only if you're using my repo @sachinjkarche

**Comment by sachinjkarche** [comment]
Thanks to all. Installed VS 2017. Angular 2 template is available in VS2017 (screen)
![screenshot_1](https://cloud.githubusercontent.com/assets/27780469/25218091/38e4a26a-25c7-11e7-86c1-ad2a75e57eb1.png)
. and project created from template running properly. But still not able to run the github app suggested (https://github.com/MarkPieszak/aspnetcore-angular2-universal) - May anyone tried in VS2017

Special Thanks to @tinchou , @MarkPieszak .

Closing this issue.

Thanks Sachin
