### ISSUE TITLE
Having more than one same child component inside a HTML template.

### ISSUE THREAD

**Issue by AliCharper** [angular/angular#16163]
**I'm submitting a bug report 

**Current behavior**

Kindly please let me know how can I have such this situation in my HTML template.
<countryautocomplete [FormGroupName]="familyEditForm" [placeholder]="'Born in'"></countryautocomplete>

<countryautocomplete [FormGroupName]="familyEditForm" [placeholder]="'Die in'"></countryautocomplete>

both are the same, but I want to use both of them inside a same page. The problem is that they shared their data and also it shows me this error:

ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: ''. Current value: 'UAE'.

**Expected behavior**

They should be independent from each other. I tried to solve by make a [placeholder] to send different value as an input param for the component, but it has not had any benefit to solve the issue.
@Input('FormGroupName')
    public familyEditForm: FormGroup;

  @Input('placeholder')
    public componentplaceholder: string;

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

I am using Angular 2/TypeScript inside VS.NET and running by npm.

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:**  TypeScript

* **Node (for AoT issues):** `node --version` =   6

**Comment by mhevery** [comment]
This is for reporting issue not for getting help with your application.

Have you tried:
http://stackoverflow.com/questions/tagged/angular
https://gitter.im/angular/angular
https://groups.google.com/forum/#!forum/angular
