### ISSUE TITLE
Secondary route can't use outlet-less path

### ISSUE THREAD

**Issue by dietergeerts** [angular/angular#16164]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you place a link to an outlet, so using a secondary route, it's not enough to have the named router-outlet, but the route you want to show also must have an outlet set to the same name.

**Expected behavior**
It should be possible to have normal router paths display in named outlets, so we can re-use those paths, for when you want to give the user the possibility of multi-view for example. + It's just strange to have the need to define the outlet twice.

* **Angular version:** 2.4.4

**Comment by royling** [comment]
>the route you want to show also must have an outlet set to the same name.

This is not true.

However, you do need to specify outlet when routing:
assuming the routes config as below:
```js
export const routes = [{
  path: '/path/to/view',
  component: RootCmp,
  children: [
    {path: 'ad1', component: AdCmp, outlet: 'popup'}
  ]
}]
```
and the `popup` outlet is included in the RootCmp template:
```html
<router-outlet name="popup"></router-outlet>
```

To show AdCmp in the popup outlet, you need to do:
```js
router.navigate(['/path/to/view', { outlets: { popup: 'ad1' }])
```
or via routerLink directive:
```html
<a [routerLink]="['/path/to/view', { outlets: { popup: 'ad1' }]">Show ad1</a>
```

If that is still not working for you, pls provide a plunkr example.

**Comment by dietergeerts** [comment]
@royling, you say it's not true, but you do it in your example. What I want to see if that you can put any route into a router outlet, so you can re-use those routes as for example for modals, for this, the outlet shouldn't be set in the routes, but setting the full path in the navigate function outlet part should do this.

**Comment by royling** [comment]
@dietergeerts ok, I got your point and deleted my comment.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
