### ISSUE TITLE
 Dynamically loading modules inside Angular 2 modals

### ISSUE THREAD

**Issue by Vasudev2129** [angular/angular#16168]
I am trying to create a modal inside which i am trying to load component and their modules dynamically.
But I was not able to find a way yet in which i could do so. The component and the module that i am trying to load has angular 2 implementation as well. So it has to be compiled before it gets displayed inside the modal.I am using third party module angular2-modal for creating modal. The modal i am trying to create should be a reusable component. I will be exposing my modal as a node module to my client. Therefore i cannot directly import the required module, which is to be displayed inside my modal.I am using SystemJsNgModuleLoader for compiling the module but in this case it is searching for js file rather than TS.
I am using webpack for my compilation and bundling process. 

Regards
Vasudev Gupta

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
