### ISSUE TITLE
Extract logic from DatePipe into DateService

### ISSUE THREAD

**Issue by alxhub** [angular/angular#16174]
Many users need to localize date values in the same manner as `DatePipe`, but within their component or service code. Currently these users either declare `providers: [DatePipe]` and inject the `DatePipe` into their component/service, or they use `new DatePipe()` explicitly. Both of these are unexpected and unsupported usages of `DatePipe`.

Instead, `DatePipe`'s logic could be extracted into a theoretical `DateService`, which `DatePipe` could then use in its implementation. This would expose the logic of `DatePipe` to developers in a much safer format for them to consume.

**Comment by josephliccini** [comment]
We use `DecimalPipe` for number localization as well

**Comment by vicb** [comment]
When @ocombe refactored the pipes he moved the logic to separate files.
May be we should expose those API now.

**Comment by ocombe** [comment]
It could be added to the i18n API yes

**Comment by vicb** [comment]
This will be fixed together with https://github.com/angular/angular/issues/20536 (opening the API)
