### ISSUE TITLE
Please rename this framework to AngularTS

### ISSUE THREAD

**Issue by icenold** [angular/angular#16171]
Now that Angular 2 and Angular 4 are now officially just "Angular"
Every search engine gives people result of "AngularJS" when they are searching for "Angular"
For the glory of christ please....name yourself AngularTS instead

**Comment by dherges** [comment]
💣  🔥  💥

**Comment by ericmartinezr** [comment]
No need to rename it (again). Dup of https://github.com/angular/angular/issues/14802, in the meantime you can google as "angular2", or follow this advice https://github.com/angular/angular/issues/14802#issuecomment-283116190

**Comment by mhevery** [comment]
closing as dup of #14802
