### ISSUE TITLE
Animation 4.0 number states 'less forgiving' when triggering animations?

### ISSUE THREAD

**Issue by bratzie** [angular/angular#16186]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Using numbers as state triggers ever since animations were extracted into its own package will not produce any error, but will not trigger states/animations correctly and consistently.

**Expected behavior**
Using numbers as states used to work, and was very nice to use when you had animation states between 2 states as `0` would evaluate to false and `1` to true, enabling you to use them for other purposes as well, i.e. when adding and removing classes based on the animations. So the expected behavior would be to have this work the way it did in 2.4 and below.

**Minimal reproduction of the problem with instructions**
```
animations: [
  trigger('switchBackgroundNumber', [
    state('0', style({ 'background-color': 'red' })),
    state('1', style({ 'background-color': 'blue' })),
    transition('0 <=> 1', animate('100ms ease-in'))
  ]),
  trigger('switchBackgroundString', [
    state('red', style({ 'background-color': 'red' })),
    state('blue', style({ 'background-color': 'blue' })),
    transition('red <=> blue', animate('100ms ease-in'))
  ])
]

this.numberState = 0;
this.stringState = 'red';
```

If you try to call these animations with `[@switchBackgroundNumber]="numberState"` and then switching numberState between `0` and `1` will apply the styles of 1, but not of 0. However, the case with `[@switchBackgroundString]="stringState"` works as expected when switching `stringState` between `'red'` and `'blue'`.

**What is the motivation / use case for changing the behavior?**
It used to work in 2.4, and it stopped working in 4.0. Did not produce any errors, it just wouldn't activate the animations properly. It took me quite some time to locate what was causing this and I couldn't find any mention of it anywhere in the upgrade guides. You could argue that it was never supposed to work though as the docs states that you should use `strings` for states and my way of doing it  was just never really intended to work.

**Please tell us about your environment:**
OSX 10.11.6 (Yarn, Angular-CLI, Angular Material also present within project, but should not be relevant to this 'bug').

* **Angular version:** 4.0.0

* **Browser:** Chrome 57
 
* **Language:** Typescript 2.1.0

* **Node (for AoT issues):** `node --version` =   7.7.3

**Comment by vicb** [comment]
Closing as no repro has been provided and obsolete.
