### ISSUE TITLE
core.es5.js throw error when having multiple with and without factory providers

### ISSUE THREAD

**Issue by kaifeong** [angular/angular#16181]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I'm having multiple providers with and without factory, I encountered javascript error when it tried to call `appInits[i]()` when is undefined.

**Expected behavior**
Those providers with factory shall be loaded only.

**Minimal reproduction of the problem with instructions**
Below are the sample app.module.ts code. It happen when it tried to invoke core.es5.js line 2908 `var initResult = appInits[i]();` with 4th init `Service4` where there ain't any function.

```@NgModule({
    providers: [
        Service1, {
            provide: APP_INITIALIZER,
            useFactory: Service1.factory,
            deps: [Service1],
            multi: true
        },
        Service2, {
            provide: APP_INITIALIZER,
            useFactory: Service2.factory,
            deps: [Service2],
            multi: true
        },
        Service3, {
            provide: APP_INITIALIZER,
            useFactory: Service3.factory,
            deps: [Service3],
            multi: true
        },
        Service4,
        Service5
    ],
    ...
```

**What is the motivation / use case for changing the behavior?**
I did a quick fix @angular/core.es5.js in my local at line 2908. Otherwise can it filter out those are undefined in appInits array or where it was pushed.
```
var initResult = appInits[i]();
  if (isPromise(initResult)) {
    asyncInitPromises.push(initResult);
```
can be replace:
```
if (appInits[i]) {
  var initResult = appInits[i]();
  if (isPromise(initResult)) {
    asyncInitPromises.push(initResult);
  }
```

**Please tell us about your environment:**
* Win 10
* Visual Studio 2017
* Angular 4.0.2
* Angular cli 1.0.0
* Chrome 57.0.2987.133
* Node v7.4.0

**Comment by tbosch** [comment]
Thanks for the bug report. However, we need a reproduction for this problem, e.g. a plunker. Could you create one?

**Comment by kaifeong** [comment]
I just tested with latest @angular/core 4.0.3, all objects in appInits no longer undefined even those service without factory. Therefore this issue no longer valid. Thanks.

**Comment by maphi88** [comment]
The errors in my project does not show on node or on the browser but on newrelic it shows error https://ibb.co/dyr996 https://ibb.co/dDNhU6 Please find the screenshot
