### ISSUE TITLE
Add option to @View to opt out of view reuse

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1618]
*tl:dr* Components that use imperative templates or web components may not be able or want to cleanly implement dehydration and rehydration. Such components are likely to be rare, but when they are used we should have a way for them to opt out of view reuse.

# Problem

Imagine a component that has a YouTube player web component inside. A user is in the middle of watching a video and then they close the component. When they come back, if we reuse the player element and there's no explicit rehydration logic, it may show up in the middle of playing the old video.

# Proposal

```dart
@View(
  cacheable: true/false  // default is true
)
```

**Comment by mhevery** [comment]
Sounds reasonable to me. But I think the annotation should be on `@View`  not on `@Component` as it is the view which should not be cached.

**Comment by yjbanov** [comment]
Dynamic components don't have the `@View` annotation, but I'm guessing view reuse doesn't apply in dynamic case?

**Comment by mhevery** [comment]
@yjbanov correct, but dynamic components load static components which do have `View`s and hence will have a place to put this. So it works out great.

**Comment by yjbanov** [comment]
Sounds good. I updated the proposal.

**Comment by tbosch** [comment]
The ViewPool has been dropped.
