### ISSUE TITLE
View not render

### ISSUE THREAD

**Issue by jsenjobs** [angular/angular#16185]
when I use ng2 I found a problom that I cant not fix it.
I use route and outlet to route some component in a dashboard,when i routing in to component,that both page are request a http get use promise when nginit.When I first click and it work will(route and render),but when routed,I click the rowser's back button or use location.back function it also request the net resources and the http get is ok(get the data),but the view can not display such as ngFor data but simple str is displayed.In otherwise I try promise with a timeout instead of http request,the problom is also appeared,directly return a str or list it render will.

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
Please fill out the Issue template correctly and provide a minimal reproduction for any feature issues
