### ISSUE TITLE
docs(aio): the routing tutorial has an unrendered code snippet frame

### ISSUE THREAD

**Issue by haoliangyu** [angular/angular#16180]
**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request
* [ ] support request

**Current behavior**

In the **Rounting** page of the tutorial, the second code snippet frame at the **Refactor routes to a Routing Module** section is not rendered. Instead it shows the source code .

```
+makeTabs( toh-5/ts/src/app/app.module.ts, toh-5/ts/src/app/app.module.3.ts, null, src/app/app.module.ts (after), src/app/app.module.ts (before)) :marked
```

See the line above **Select a hero in the HeroesComponent**

![screenshot from 2017-04-20 00-08-34](https://cloud.githubusercontent.com/assets/1726265/25213313/dd4237ce-255d-11e7-8973-b5305beaa9fa.png)

**Expected behavior**

I think there should be a frame to show several code snippets.

**Comment by gkalpak** [comment]
Thx for reporting this. It [seems to be fixed][1] on the new version.

[1]: https://aio-staging.firebaseapp.com/tutorial/toh-pt5#update-appmodule
