### ISSUE TITLE
The Plunkr template suggested in the github New Issue boilerplate does not work with RxJS

### ISSUE THREAD

**Issue by mikechamberlain** [angular/angular#16182]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The Plunkr template suggested in the github New Issue boilerplate does not work out of the box with RxJS. It fails to load RxJS with a bunch of 404s. Seems that SystemJS in not configured properly?

**Expected behavior**
It should work out of the box.

**Minimal reproduction of the problem with instructions**
- go to http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 (the suggested Plunkr template from the current boilerplate)
- in `app.ts` add `import {Observable} from 'rxjs'` at the top and `const s = Observable.of(null);` in the component constructor
- open the network tab and run it
- observe as it crashes and burns, eg: `GET https://unpkg.com/ReplaySubject 404 ()`

Here: http://plnkr.co/edit/LEwg50TI90K4idOc0ei4

**Please tell us about your environment:**
Latest Chrome on latest MacOS

* **Angular version:** 4.0.2

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
to use `Observable.of` you have to import like 
```
import {Observable} from 'rxjs/Observable'
import 'rxjs/add/observable/of'
```
just like in any normal app

**Comment by ericmartinezr** [comment]
In addition to @Toxicable 's suggestion, you can simplify it (just when working with plnkrs, in your app you always want to import only the operators you need) by importing the whole Observable thing `import {Observable} from 'rxjs/Rx'`

**Comment by mikechamberlain** [comment]
Thanks everyone. It confused me because In my current Angular app I just do:

    import {Observable} from 'rxjs';

at the top of my file, and all the Observable methods are magically available.
