### ISSUE TITLE
can support spa reload page

### ISSUE THREAD

**Issue by kinanson** [angular/angular#16188]
**I'm submitting a ...**  (check one with "x")

[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
can't reload page for spa

**Minimal reproduction of the problem with instructions**
My page in the iframe.If I use location.reload().I will go to default page because iframe page url dependency querystring.

**What is the motivation / use case for changing the behavior?**
Router doesn't has reload page.I don't like window.location.reload().I want spa reload that a like angularjs $route.reload()

**Please tell us about your environment:**
windows 7.vs code.

* **Angular version:** 4.0.2

* **Browser:** [Chrome 57.0.2987.133  ]
 
* **Language: TypeScript 2.2.0

**Comment by mhevery** [comment]
Sorry this is not a place for technical help, but rather for reporting issues. Please check 
http://stackoverflow.com/questions/tagged/angular2
https://gitter.im/angular/angular
https://groups.google.com/forum/#!forum/angular
