### ISSUE TITLE
bug canLoad WHEN redirect to ["/"] and return false

### ISSUE THREAD

**Issue by istiti** [angular/angular#16197]
**I'm submitting a ...**
```
[x] bug report with CanLoad Guard
```

**Current behavior**
Actually I  lazy load my LoginModule and I have `canLoad ` guard. In this canLoad I just check if token is valid.
1. If NOT valid I simply `return true;` and it works LoginModule is allowed to load
The problem is :
2. if token IS valid I don't want to load LoginModule I simply navigate to home route and return false using:
```
this.router.navigate(['/']);
return false;
```

Problem is when in canLoad guard you return false the url is automatically cleared and my `navigate(['/']);` is never fired :S 

**Expected behavior**
Simply execute `navigate(['/']);` when return false; in canLoad

**Minimal reproduction of the problem with instructions**
can't reproduce  but here's my routing: 

```
const APP_ROUTES: Routes = [
  { path: 'login', loadChildren: 'app/login/login.module#LoginModule', canLoad: [CanLoadLoginGuard]},
  ...
  { path: '', component:HomeComponent, pathMatch: 'full', canActivate:[CanActivateHomePageGuard] },
  { path: '**', redirectTo:'' }
];
```

**Please tell us about your environment:**
ng 4.0.3, ng-cli 1.0.0, ts 2.3 (win10,webstorm,npm)

## Update (more infos)
I tried [plunker here ](https://plnkr.co/edit/WMlunnCSy47BYjwCUKcP?p=preview) and can't reproduce because I need to come for first time to certain route where I have canLoad,  afaik in plunker preview you can't come directly to [.../mod1](https://run.plnkr.co/preview/cj1rl90d100093c5p806cjogo/mod1) but only on [.../](https://run.plnkr.co/preview/cj1rlfe0y00093c5pb1m5cvlx/)

I have zipped project with very light/simple example. So if you have angular-cli you can simply `run npm i&& ng s` and open your browser on [localhost:4200/mod1](http://localhost:4200/mod1) then CANCEL `confirm()` dialog, that's all!

[Download issue16197.zip project (angular-cli)](https://drive.google.com/file/d/0BzKW4KaSm_QMZjdJLXlVZjZfYkk/view?usp=sharing)

Cheers

**Comment by zoechi** [comment]
What do you mean with 

> can't reproduce but here's my routing:

Have you tried reproducing in Plunker?

**Comment by istiti** [comment]
@zoechi yes AS SAID i tried [here ](https://plnkr.co/edit/WMlunnCSy47BYjwCUKcP?p=preview) and can't reproduce in Plunker because I need to come for first time to route where I have canLoad .... and afaik in plunker preview you can't come directly to [.../mod1](https://run.plnkr.co/preview/cj1rl90d100093c5p806cjogo/mod1) but only on [.../](https://run.plnkr.co/preview/cj1rlfe0y00093c5pb1m5cvlx/)

I have zipped project with very light/simple example. So if you have angular-cli you can simply `run npm install && ng s` and open your browser on [localhost:4200/mod1](http://localhost:4200/mod1) then CANCEL `confirm()` dialog, that's all!

[Download issue16197.zip project](https://drive.google.com/file/d/0BzKW4KaSm_QMUUgxRml0Wlk4TXc/view?usp=sharing)

Cheers

**Comment by DanielKucal** [comment]
I'm facing the same issue and @ghetolay's workaround works for me, thanks.
Current behavior when starting app in lazy-loaded path and trying to redirect to `/` from `canLoad` guard is displaying a blank page, although the same code works from `canActivate` guard... For me, this is an obvious bug.

**Comment by jasonaden** [comment]
We recently fixed some issues with redirect after errors or navigation cancel. Please take another look at this issue and create a new one against the current router if it's still applicable.

**Comment by stovbur** [comment]
Hello @jasonaden. The situation is not fixed :-(

https://stackblitz.com/edit/angular-4kt7bp
If I open https://angular-4kt7bp.stackblitz.io/test the route "/" not triggered on redirect to him

**Comment by zoechi** [comment]
@stovbur This issue is long closed. If this is still a problem for you it's better to create a new issue (with a link to this one).
Don't expect comments on closed issues to be seen.

**Comment by stovbur** [comment]
@zoechi Thx)
