### ISSUE TITLE
aio: fine-tune which files are cached/pre-fetched by the ServiceWorker

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#16198]
Currently there are several files that are eagerly fetched by the ServiceWorker (e.g. plunkers, zips, content/images/bios) that are likely not necessary. We need to decide what we want to be eagerly fetched and modify `ngsw-manifest.json` accordingly.

**Comment by gkalpak** [comment]
Also related: The ServiceWorker doesn't cache external resources (such as `https://fonts.googleapis.com/icon?family=Material+Icons`), leading to undesirable artifacts when offline (e.g. text in place of icons etc).

**Comment by alxhub** [comment]
The SW has a plugin for external content which reads an `"external"` section of `ngsw-manifest.json`. This section can be used to cache URLs such as the Material Icon font:

```
"external": {
  "urls": [
    "https://fonts.googleapis.com/icon?family=Material+Icons"
  ]
}
```
