### ISSUE TITLE
How to do modification in Angular 2 App after build

### ISSUE THREAD

**Issue by jigarb-1992** [angular/angular#16203]
I am new to Angular 2. I have developed one small application. In my application there is a Login and Register page.

After all done I have build my app using
<code>ng build --prod --aot</code>
All the js is minified and It all work fine.

My question is now I have to do a little change
like change label text 'Username' to 'Email'

Is I need to do change and rebuild full solution every time for this type of small changes?

**Comment by istiti** [comment]
Yes of course you need, this is fundamental to understand when programming . In what language (no jit) you don't need do compilation ? (as ng build here) ?

N.B. Be careful your question isn't welcome by people here..  For this kind of question you need to use stackoverflow for help not open issue, thanks.

**Comment by zoechi** [comment]
@jigarb-1992 
Already asked and answered in http://stackoverflow.com/questions/43522689/how-to-do-modification-in-angular-2-app-after-build

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

Please consider closing the issue.
