### ISSUE TITLE
aio: API missing in certain cases

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#16208]
For example, https://aio-staging.firebaseapp.com/api/core/Component this one

**Comment by petebacondarwin** [comment]
I think this is partly due to the fact that angular.io has replaced the `mergeDecoratorDocs` processor with one called `mergeDecoratorDocsEmpty` which does nothing.

**Comment by petebacondarwin** [comment]
In any case there is definitely something wrong with dgeni at the moment, which I will fix tomorrow.

**Comment by petebacondarwin** [comment]
@Foxandxss can you check if there are other API pages missing after #16278 and #16284 land?

**Comment by Foxandxss** [comment]
Deal

**Comment by petebacondarwin** [comment]
@Foxandxss told me on Slack that there are no missing API docs now.
