### ISSUE TITLE
aio: avoid duplicate name for downloaded zips

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#16227]
See https://github.com/angular/angular/pull/16194#discussion_r112537439 for more details.

**Comment by IgorMinar** [comment]
Is this still a problem?

If I got to e.g. https://angular.io/guide/reactive-forms and scroll down, I see this link: https://angular.io/generated/zips/reactive-forms/reactive-forms.zip is the problem that the link has a directory name that duplicates the file name? or something else?

**Comment by gkalpak** [comment]
No, the problem is that it is possible for two zips to have the same name. It happened with the (now removed) `cb-ts-to-js` guide; not sure if there are other occurrences atm.

(Fix: #20586)
