### ISSUE TITLE
@Inject does not add metadata when in AoT

### ISSUE THREAD

**Issue by tieppt** [angular/angular#16224]
I have some code below, the problem is: it working in JIT mode, and when I run `ng serve -aot`, the generated code for class `Computer` dose not have metadata for DI work. So an error occur like this:

`Cannot resolve all parameters for 'Computer'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Computer' is decorated with Injectable.`

<details>
 <summary>Code example</summary>

```
import { ReflectiveInjector, Inject, Injectable } from '@angular/core';

class CPU {
  constructor() {}
  start() {
    console.log('CPU speed 3.2GHz');
  }
}

class Computer {
  constructor(@Inject(CPU) public cpu: CPU) {}
}


function context() {
  const injector = ReflectiveInjector
    .resolveAndCreate([Computer, CPU]);
  const computer = injector.get(Computer);
  computer.cpu.start();
}

context();
```

</details>

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It cannot resolve dependency when in AoT, but it work in JIT mode.

**Expected behavior**
working in both.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:**
@angular/cli: 1.0.0
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v6.10.0

**Comment by zoechi** [comment]
Your issue looks like a support request.
Classes used as service need the `@Injectable()` decorator like `@Injectable() class Computer {`
If the constructor doesn't have parameters it's not strictly required (like your `CPU` class), but for `Computer` it's required.
Also `@Inject(CPU)` is redundant.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by tieppt** [comment]
@zoechi I know, `@Injectable()` could make it work, but I only want to using `@Inject`, and it work on JIT mode. Why on AoT, it's not working.

**Comment by trotyl** [comment]
@tieppt That's not allowed any more, see https://github.com/angular/angular/issues/13820 , if it works in JIT, then it's a JIT bug.

**Comment by tieppt** [comment]
@trotyl thank you.
