### ISSUE TITLE
Calling method of a child component if parent has two children of the same component

### ISSUE THREAD

**Issue by icenold** [angular/angular#16220]
https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#parent-to-view-child

so according to the "official" docs, calling method of child component can be done inside the parent's Class using: ```
@ViewChild(CountdownTimerComponent)
  private timerComponent: CountdownTimerComponent;
```
`and doing timerComponent.methodName()`

So what if the parent component uses two CountDownTimerComponent and only to call timerComponentNumber1.methodName()?

Assuming the developer wants to call the method inside the ParentClass and not from template

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
