### ISSUE TITLE
feat(aio): show a "back to top" link in narrow view

### ISSUE THREAD

**Issue by wardbell** [angular/angular#16223]
**Feature suggestion - not a release blocker**

While dgeni is adding anchor/links to headings, it could also add this nifty "Back to top" widget just like they have on google web docs:

![image](https://cloud.githubusercontent.com/assets/129061/25259056/7941ece2-25f8-11e7-9402-ae031e0bc7a8.png)

See [this page for example](https://developers.google.com/fonts/docs/technical_considerations).

In google web docs, this widget is only available on H2s and is only visible in medium screen widths.  Seems reasonable.

**Comment by gkalpak** [comment]
👍 For having a "Back to top" button".

Things that I don't get/would do differently:

- Why only show it on medium screens. What's wrong big wide screens?
- Why not have it always visible as a floating/fixed button?

**Comment by petebacondarwin** [comment]
> Why not have it always visible as a floating/fixed button?
+1 for this, as long as it doesn't block contents

That being said, once we have the floating table of contents, there is less need for this feature at all IMO, since one can always click the first item of the ToC to get back to the top.

**Comment by gkalpak** [comment]
Except for small screens where the TOC won't be floating.

**Comment by petebacondarwin** [comment]
> Except for small screens where the TOC won't be floating.

OK, in that case (where the screen is narrow) we should have a floating "back to top" anchor that is stuck to the bottom of the screen. There is nothing special about headings as take off points for getting back to the top.

**Comment by petebacondarwin** [comment]
Anyone want to take this on? It should be fairly straightforward to do...

**Comment by sonukapoor** [comment]
@petebacondarwin I am taking on this one.

**Comment by sonukapoor** [comment]
@petebacondarwin / @gkalpak What size is considered small screen?

**Comment by gkalpak** [comment]
We decided not to implement this feature for now. See https://github.com/angular/angular/pull/34580#issuecomment-921032398.
