### ISSUE TITLE
Angular 4 Error

### ISSUE THREAD

**Issue by Roshan1729** [angular/angular#16231]
I'm getting the following error on loading of my app.

![capture](https://cloud.githubusercontent.com/assets/27290616/25278596/acc7af56-2671-11e7-8804-74399ef48d4b.PNG)

This is my app.module.ts

import { NgModule, APP_INITIALIZER, ErrorHandler } from '@angular/core';
import { LocationStrategy, HashLocationStrategy } from '@angular/common';
import { HttpModule, JsonpModule, Jsonp } from '@angular/http';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule, FormGroup, FormControl, ReactiveFormsModule } from '@angular/forms';
import { routing, appRoutingProviders } from './app.routing';
import { AppConfig } from './app.config';

import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';

{

@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        routing,
        HttpModule,
       
        SimpleNotificationsModule.forRoot(),
    ],
    exports: [
        GenericFilterPipe,
        OptionsFilterPipe
    ],
    declarations: [
       
        HomeComponent,
        AppComponent,
       
    ],
    providers: [
        HttpModule,
        ConfigurationService,
       
        { provide: LocationStrategy, useClass: HashLocationStrategy },
        LOGGING_ERROR_HANDLER_PROVIDERS,
        {
            provide: LOGGING_ERROR_HANDLER_OPTIONS,
            useValue: {
                rethrowError: false,
                unwrapError: true
            }
        },
        appRoutingProviders,
        
        AppConfig,
       
        {
            provide: APP_INITIALIZER,
            useFactory: init_app,
            deps: [AppConfig, ConfigurationService, LoggerService],
            multi: true
        }
    ],
    bootstrap: [AppComponent, appRoutingProviders]
})

export class AppModule
{
    constructor(private httpModule: HttpModule)
    {

    }
}

Any help would be appriciated.

**Comment by nicais** [comment]
Hi, think you might get better help if you used plunkr to display code and maybe getting help from the (gitter)[www.gitter.im/angular/angular] chat room. 
Issues here are for informing about bugs and issues in the code that everybody is experiencing. There is more information on submitting issues here: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-issue
