### ISSUE TITLE
Add i18n parameters to tsconfig.json

### ISSUE THREAD

**Issue by ocombe** [angular/angular#16232]
**I'm submitting a ...**
```
[x] feature request
```

**Current behavior**
We cannot set i18n parameters into tsconfig.json like we can with other ngc parameters

**Expected behavior**
Being able to set i18n parameters into tsconfig.json

**What is the motivation / use case for changing the behavior?**
Easier to setup your project

**Comment by vicb** [comment]
closed by https://github.com/angular/angular/pull/18494
