### ISSUE TITLE
@InjectLazy not working on directive

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#1623]
Hi

I was doing some tests with the DI module and found that it's not possible to use `@InjectLazy` within directives. I've tried with a Component that is bootstrapped, a sub component and Decorator. The behavior is that `@InjectLazy` will behave like `@Inject` on directive constructors. Is this behavior expected?

```javascript
import {Component, Decorator, View, bootstrap} from 'angular2/angular2';
import {Inject, InjectLazy} from 'angular2/di';

class Test {
  constructor() {
    console.log('Test was constructed');
  }
}

@Decorator({
  selector: 'test'
})
class TestDecorator {
  test:Test;

  constructor(@InjectLazy(Test) testFactory) {
    // ERROR: Object is not a function; testFactory wll be an instance of Test
    this.test = testFactory();
  }
}

@Component({
  selector: 'ng2-sandbox',
  injectables: [Test]
})
@View({
  template: '<test></test>',
  directives: [TestDecorator]
})
class App {}

bootstrap(App);
```

**Comment by gionkunz** [comment]
Same goes for `@InjectPromise` on Components. It also tries to do a synchronous inject.

**Comment by mhevery** [comment]
seems lie a bug

**Comment by vsavkin** [comment]
It looks like a bug in the compiler. This is a valid use case and should be fixed.

**Comment by rolandjitsu** [comment]
@mhevery any news on this one? I've experienced the same thing and I also get an exception saying: `Cannot instantiate MyService synchronously. It is provided as a promise! (MyComponent -> MyService)`.

**Comment by mhevery** [comment]
@vsavkin is this still relevant?

**Comment by PascalPrecht** [comment]
@InjectLazy has been removed from DI specific decorators. I think this can be closed.
