### ISSUE TITLE
ng-xi18n regression 4.0.2 -> 4.0.3

### ISSUE THREAD

**Issue by sebek64** [angular/angular#16235]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The compiler fails with the following error:

> ng-xi18n -p src/tsconfig-i18n.json

TypeError: Cannot read property 'toLowerCase' of null
    at Extractor.serialize (.../node_modules/@angular/compiler-cli/src/extractor.js:44:32)
    at .../node_modules/@angular/compiler-cli/src/extractor.js:32:33
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
Extraction failed

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript 2.2.2

* **Node (for AoT issues):** `node --version` =   v6.10.2

**Comment by wiwski** [comment]
Got the same error as well

**Comment by ocombe** [comment]
Easy to workaround: you have to specify the format with `--i18nFormat` (xlf, or xmb).
I'll work on the fix right now though.

**Comment by jiangyaqi2** [comment]
oh,./node_modules/.bin/ng-xi18n  --i18nFormat=xmb
 and perfect

**Comment by Safe0** [comment]
It's working well for xmb but for xfl I have an unsupported format error. Am I missing something?

**Comment by ocombe** [comment]
because it's "xlf", not "xfl"

**Comment by Safe0** [comment]
Wow, I'm so dumb... thanks!

**Comment by dgroh** [comment]
Also having the same error:

after running `npm run i18n --i18nFormat=xlf`

I got:

>TypeError: Cannot read property 'toLowerCase' of null
    at Extractor.serialize (C:\Projekte\Git\KWKPortal\App\node_modules\@angular\compiler-cli\src\extractor.js:47:32)
    at C:\Projekte\Git\KWKPortal\App\node_modules\@angular\compiler-cli\src\extractor.js:33:33
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
Extraction failed

**Comment by trotyl** [comment]
@dgroh That way you're passing the `i18nFormat` option to npm itself, obvious npm doesn't know that. A `--` is needed for passing to the inner command. See [npm-run-script](https://docs.npmjs.com/cli/run-script) for more information.

**Comment by sarat9** [comment]
For Windows Users:
"./node_modules/.bin/ng-xi18n" --i18nFormat=xlf

If the tsconfig.json TypeScript configuration file is located somewhere other than in the root folder, you must identify the path to it with the -p option:
"./node_modules/.bin/ng-xi18n" --i18nFormat=xlf -p path\to\tsconfig.json

Also follow the quotes order.

**Comment by ocombe** [comment]
I believe that this has been solved. Closing the issue. Let me know if that's not the case.
