### ISSUE TITLE
aio: api page code snippets should be wrapped in <aio-code>

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#16246]
The API template does not render code blocks with the doc viewer's `<aio-code>` tags as happens when guide authors write `<code-example>` and `<code-tabs>`.

Therefore, API code snippets are not pretty-printed and rendered as they are in the guide pages. The likely solution is for dgeni to transform those snippets appropriately.

Tangentially, what would dgeni do if an author used backtick markdown inside a guide page rather than the prescribed `<code-example>`  (or `<aio-code>`) technique?

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Unable to style api page code snippets

**Expected behavior**
To use `<aio-code>` component for consistency across the site

**Comment by Foxandxss** [comment]
What dgeni does (Pete correct me if I am wrong) is parsing the code file to extract stuff (no idea how, reflection perhaps) and then with a template, it generates a <code> tag with the content inside.

Not sure if we can put embedded components in those templates.

**Comment by petebacondarwin** [comment]
I think we need to change the current rendering for `{@example }` inline tags. (Really we should remove them all and just use `code-example` tags.

Regarding triple back tick blocks. I am not sure. I'll have to check :-)

**Comment by petebacondarwin** [comment]
It appears to me that all the `{@example ... }` blocks are being rendered correctly.
I'll fix the triple backticks

**Comment by Foxandxss** [comment]
It is not the fact that we are using {@example ...} correctly. Is stuff like class overview that is generating a custon code tag and not an @example
