### ISSUE TITLE
aio: styleguide h3 alignment

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16241]
The styleguide appears to have two lots of anchors for the h3 headings, which is somehow causing the alignment to break.
See https://pr16218-fbae440efce92c98db028bc87aad0abd85bdde7f.ngbuilds.io/guide/style-guide#naming

![screen shot 2017-04-21 at 16 07 15](https://cloud.githubusercontent.com/assets/15655/25283914/4df30778-26ad-11e7-8265-e9f6a050cee1.png)

**Comment by sjtrimble** [comment]
Is there a need for the style reference `a` tags inside of the h3's? I don't see them being used anywhere. Do you know @petebacondarwin?

**Comment by sjtrimble** [comment]
@wardbell @petebacondarwin Just following up on this one ---- can we get rid of the links inside of the headers? That is what is causing the extra indent.

**Comment by petebacondarwin** [comment]
Not easily. Sorry. The header anchors are autogenerated in a standard way across the site. Why can we not just apply appropriate CSS here?

**Comment by petebacondarwin** [comment]
Oh, hold on. Sorry I missed the point. There are TWO anchors.
We ought to be able to move (or remove) one of them.

**Comment by petebacondarwin** [comment]
Here you go: https://github.com/angular/angular/pull/16460
