### ISSUE TITLE
webjars for angular4

### ISSUE THREAD

**Issue by softboy99** [angular/angular#16240]
we need webjars for angular 4.where to find it?

**Comment by wKoza** [comment]
Webjars Angular are a very bad solution. How will you perform the tree shaking and AOT for example ?

**Comment by mhevery** [comment]
Sorry this is not a place for technical help, but rather for reporting issues. Please check 
http://stackoverflow.com/questions/tagged/angular2
https://gitter.im/angular/angular
https://groups.google.com/forum/#!forum/angular
