### ISSUE TITLE
avoid duplicated members

### ISSUE THREAD

**Issue by younes-amiti** [angular/angular#16244]
Hi guys i'm trying to displays some data in a view html using angular 2 but when after consuming the json file to display data i observe that there is some duplicated members in my situation the slot.fromTime.concat(slot.toTime) attribute sooooo is there a solution to avoid displaying the duplicated data.
So this is the the json file : http://cfp.devoxx.be/api/conferences/DVBE17/schedules/wednesday

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
