### ISSUE TITLE
pleaaase guys i got this problem when i import the lodash library in angular component

### ISSUE THREAD

**Issue by younes-amiti** [angular/angular#16243]
ERROR in /home/lyffy/ngproject/cfp1/src/app/skeleton/skeleton.component.ts (2,8): Module '"/home/lyffy/ngproject/cfp1/node_modules/@types/lodash/index"' has no default export. what's the solution guys please !!!!!

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by younes-amiti** [comment]
@ericmartinezr it's done thanks ;)
