### ISSUE TITLE
docs(aio): Unclear Instructions in the Routing & Navigation angular documentation

### ISSUE THREAD

**Issue by thefliik** [angular/angular#16259]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When following the ["Routing & Navigation Milestone 4: Crisis center feature,"](https://angular.io/docs/ts/latest/guide/router.html#!#milestone-4-crisis-center-feature) in the advanced section of the current angular documentation (4/22/17), readers are instructed to build a `src/app/crisis-center/crisis-list.component.ts` view template by copying the contents from a previously created `src/app/heroes/hero-list.component.ts` view template which does not contain a `<router-outlet></router-outlet>` tag. Readers are then [instructed to build](https://angular.io/docs/ts/latest/guide/router.html#!#child-route-configuration) a `src/app/crisis-center/crisis-center-routing.module.ts` file in the following format

```
const crisisCenterRoutes: Routes = [
  {
    path: 'crisis-center',
    component: CrisisCenterComponent,
    children: [
      {
        path: '',
        component: CrisisListComponent,
        children: [
          {
            path: ':id',
            component: CrisisDetailComponent
          },
          {
            path: '',
            component: CrisisCenterHomeComponent
          }
        ]
      }
    ]
  }
];

@NgModule({
  imports: [
    RouterModule.forChild(crisisCenterRoutes)
  ],
  exports: [
    RouterModule
  ]
})
export class CrisisCenterRoutingModule { }
```

Unless I'm missing something, this format expects that the `CrisisListComponent` template contains a `<router-outlet></router-outlet>` tag. The lack of this tag generates errors.

The need for this tag is subtly referenced in one line of the documentation: "The CrisisListComponent contains the crisis list and a RouterOutlet to display the Crisis Center Home and Crisis Detail route components." Readers are never explicitly instructed to actually add this RouterOutlet to the CrisisListComponent however, and this generated confusion for me.

This documentation should be updated to explicitly instruct readers to add a RouterOutlet to the CrisisListComponent. Simply saying that `CrisisListComponent` _has_ a `RouterOutlet`, when the component we were instructed to create _does not have_ a `RouterOutlet`, is not a strong enough indication that the reader _needs_ to add a `RouterOutlet` to the `CrisisListComponent`.

**What is the motivation / use case for changing the behavior?**

To make clearer documentation which is easier for inexperienced readers to follow / understand.

**Comment by wardbell** [comment]
I think this is adequately addressed in PR #17760
