### ISSUE TITLE
aio: horizontal scrollbar on pages with table

### ISSUE THREAD

**Issue by donroyco** [angular/angular#16258]
**I'm submitting a ...**
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On pages like [the component for slider](https://material.angular.io/components/component/slider) where a table is displayed, a horizontal scrollbar is visible below the table.

![chrome-issue-hor-scrollbar](https://cloud.githubusercontent.com/assets/1763537/25308395/8630e4aa-27b3-11e7-9f6e-3abf3e8fbdc5.png)

**Expected behavior**
The page should be displayed without the horizontal scrollbar.

**Minimal reproduction of the problem with instructions**
Go to [the slider component page](https://material.angular.io/components/component/slider) in Google Chrome and Apple Safari. Other example is the API Reference section of [Toolbar component](https://material.angular.io/components/component/toolbar).

**What is the motivation / use case for changing the behavior?**
Element shouldn't be there in the first place.

**Please tell us about your environment:**
macOS Sierra 10.12.4

* **Angular version:** 4.0.1 (from `body`)

* **Browser:** [Chrome Version 57.0.2987.133 (64-bit) | Safari Version 10.1 (12603.1.30.0.34) ]

**Comment by donroyco** [comment]
A simple fix for this could be to remove the `border-collapse: collapse;` from `table` in [_typography.scss](https://github.com/angular/angular/blob/master/aio/src/styles/0-base/_typography.scss), but I'm not sure if this will interfere with anything.

**Comment by Foxandxss** [comment]
I am super confused my friend. On the one hand you seem to be talking about the material design page and then aio page. Can you explain more?

**Comment by donroyco** [comment]
@foxandxss Well, it's regarding the Material pages, but since the class that is causing this behaviour is coming from aio, I thought to put it here, as here is the fix to be done.

**Comment by Foxandxss** [comment]
that `aio` is a project that is not even public yet, and material design webpage is a different project that sits in a different repo.

**Comment by donroyco** [comment]
@foxandxss Sorry, I didn't know that. Can you point me in the right direction, please? Thanks in advance!

**Comment by Foxandxss** [comment]
Sure, here is the repo for Angular material 2 https://github.com/angular/material2
