### ISSUE TITLE
pipes in Angular 2

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#1625]
Now that we have a way to "register" our own pipes (overwrite the existing registry) which features/DSL in Angular 1 should be transferred over? One feature is passing arguments for something like the famous `filterFilter` and any other `filter` that can take arguments.

for example let's just assume we have a `FilterPipe`

```html
<li *for="var items of collection | filter:{text: 'something'}">
  {{ items | json }} 
</li>
```
In Angular 1 we use colon to signal that it's an argument. We also add event more colons for more arguments.
```html
<li *for="var items of collection | filter:{text: 'something'}:true">
  {{ items | json }} 
</li>
```

What if we used parentheses rather than colons. If we used parentheses this time around the intent is a bit more clear. I can already use the feature of using parentheses for arguments 
[app/components/app.ts#L162](https://github.com/angular-class/angular2-reactive-starter/blob/2f29104a32df4bbbaff82fd28b65316cd92907f8/src/app/components/app.ts#L162) using [GetPipe](https://github.com/angular-class/angular2-reactive-starter/blob/2f29104a32df4bbbaff82fd28b65316cd92907f8/src/common/rxPipes.ts#L38) but it doesn't allow for when you don't want arguments. (keep in mind I made that pipe because I didn't have elvis operator in alpha.25)

```html
<li *for="var items of collection | filter({text: 'something'}, true)">
  {{ items | json }} 
</li>
```
```html
<input #search>
<li *for="var items of collection | filter(search.value, true)">
  {{ items | json }} 
</li>
```

<h2 id="CollectionLocal">CollectionLocal</h2>
What about including a `$collection` local that would allow you to place the collection in any argument

```html
<input #search>
<li *for="var items of collection | otherFilter(otherValue, $collection)">
  {{ items | json }} 
</li>
```
<h2 id="AdHocFunctions">AdHocFunctions</h2>
What about ad hoc functions as pipes? In Angular 1 we only needed a function on the scope in order for our function to filter any data we wanted. At the moment we are missing that feature in Angular 2. Having this feature was great for prototyping a filter or we can add a decorator that will turn it into a Pipe to be used
```html
<template>
<li *for="var items of collection | onlyComplete">
  {{ items | json }} 
</li>
</template>
<script type="text/angular2">
@Component()
@View()
class App {
  constructor(){}

  @asPipe
  onlyComplete(collection) {
    return collection.filter(item => item.complete);
  }
}
</script>
```

<h2 id="FunctionBind">FunctionBind</h2>
Also what about [Function Bind Syntax (bind operator)](https://github.com/zenparsing/es-function-bind) that's in ES7 strawman phase at the moment. With syntax like function-bind (which is also in Dart) then you may not need to use pipes for filters with something like [the examples](https://github.com/zenparsing/es-function-bind#examples)
```es6
import { map, takeWhile, forEach } from "some-developer-iterator-library";

getPlayers()
::map(x => x.character())
::takeWhile(x => x.strength > 100)
::forEach(x => console.log(x));
```
or something like [ng-lodash](https://github.com/rockabox/ng-lodash) in angular one where you allow the developer to provide their own iterator compatible library (just as `@memo` or `@debounce` decorators) rather then having it baked into the framework. 
another example (https://twitter.com/BenLesh/status/602923031934021633)
```es6
function customOp() {
  return this.map(x => 'custom  ' + x);
}

myObservable::customOp().subscribe(success);
```

<h2 id="Comprehension">Comprehension</h2>
[ES7 Array/Generator Comprehension](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions)
There is also the question of es6 Array Comprehension in the template syntax but that's probably another directive
```es6
// syntax
[for (x of iterable) x]
[for (x of iterable) if (condition) x]
[for (x of iterable) for (y of iterable) x + y]
/* ... */
[for (i of [ 1, 2, 3 ]) i*i ]; 
```

sidenote issue:
https://github.com/angular/angular/issues/1680
~~when I use a pipe inside a function invocation I have to wrap it in parentheses for the expression to work in the correct order
` Rating {{ rate((model.getValue('rating') | async)) }}`
initially that's fine since it forces the user to be explicit about their expressions but it doesn't look that great. If we allowed functions to be used as ad hoc pipes then we could simply do 
` Rating {{ model.getValue('rating') | async | rate }}`
unwrapping with async before transforming it~~

update: 
added Function::bind and Array Comprehension, and GetPipe

**Comment by tuurbo** [comment]
I just ran into the issue of needing to pass arguments as well. I like what you've proposed.

**Comment by mhevery** [comment]
1. We are missing a good way to register the Pipes in ng2.
2. I think we would like to keep the same syntax unless there is a technical reason not to.
3. I am a bit confused about the `$collection`. What probelm does it solve?
4. can you file a bug on the correct order bit. I would file it for you, but I don't think I understand what you mean about wrong order. There is only one argument, so how can it be in wrong order. (But parentheses should not be necessary)

**Comment by pkozlowski-opensource** [comment]
@mhevery @vsavkin I would like to come back to the topic of registering custom pipes. It would be best if I could create a custom pipe for the purpose of handling `class` and `style` attributes. But my current understanding is that I can only register "global" pipes, right? Or was anything implemented in this respect?

**Comment by naomiblack** [comment]
Needs @mhevery to sync with @vsavkin before we can move forward.

**Comment by vsavkin** [comment]
Closing this issue.  I've created these actionable issues: https://github.com/angular/angular/issues/2901
https://github.com/angular/angular/issues/2902

**Comment by e-oz** [comment]
Issue is closed and we don't have so important "filter" pipe yet and even task for it...
