### ISSUE TITLE
No errors in console when setting bound *ngIf value during a Promise's then() function.

### ISSUE THREAD

**Issue by johnhwright** [angular/angular#16252]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Given a simple template like:
```
  <div *ngIf="promiseCompleted">
     {{foo.doesntExist.Error}}
  </div>
```
If promiseCompleted is set using a promise: 
```
    this.doAsync().then(() => { 
      this.promiseCompleted = true;  
    });
```
No errors appear in the console, but the application crashes.
Note that if you set `promiseCompleted = true` during a timeout or observable subscription, you will receive the correct error in the console.

**Expected behavior**
The console should give me **any** kind of indication that an error just happened, such as: 
ERROR TypeError: Cannot read property 'Error' of undefined

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/8HZgsvlVtyQGuaRX7Luk?p=preview

**What is the motivation / use case for changing the behavior?**
Almost impossible to debug when you aren't receiving any errors.

* **Angular version:** 
4.1.0-beta.1, but issue was happening in previous version (recently updated hoping it would fix it).

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  v7.3.0

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/15702, see the zone.js issue linked.
