### ISSUE TITLE
docs(aio): Would like to help...

### ISSUE THREAD

**Issue by betweenbrain** [angular/angular#16251]
I would like to help contribute updates to https://angular.io/docs/js/latest/quickstart.html, but PRs to https://github.com/angular/angular.io are being reported as no longer accepted. I can't find the same material that needs updating within https://github.com/angular/angular/tree/master/aio/content.

Can you please clarify how I can contribute? I have searched this repo and can't find an answer.

Thanks!

**Comment by StephenFluin** [comment]
@betweenbrain Our documentation efforts hosted on https://angular.io have moved from angular/angular.io to angular/angular as part of the rebuild we're doing for the site.

We're not yet including any documentation related to ES2015/2016 in the relaunch as there hasn't been community demand for this types of documentation. If you want to tell us more about your use of ES2015/ES2016, we'd love to chat and learn more about your use cases: devrel@angular.io
