### ISSUE TITLE
Angular + SystemJS child router access error

### ISSUE THREAD

**Issue by aebmknrl** [angular/angular#16254]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a angular 2 app with this routes:

```
export const MODULE_ROUTES: Route[] =[
    { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    { path: 'dashboard', component: HomeComponent, canActivate: [AuthGuard] },
    { path: 'user', component: UserComponent, canActivate: [AuthGuard] },
    { path: 'table', component: TableComponent, canActivate: [AuthGuard] },
    { path: 'icons', component: IconsComponent, canActivate: [AuthGuard] },
    { path: 'notifications', component: NotificationsComponent, canActivate: [AuthGuard] },
    { path: 'typography', component: TypographyComponent, canActivate: [AuthGuard] },
    { path: 'maps', component: MapsComponent, canActivate: [AuthGuard] },
    { path: 'upgrade', component: UpgradeComponent, canActivate: [AuthGuard] },
    { path: 'calendar', component: CalendarComponent, canActivate: [AuthGuard] },
    { path: 'login', component: LoginComponent },
    { path: 'unauthorized', component: UnauthorizedComponent },
    { path: 'adminarea',component: AdminareaComponent, canActivate: [AuthGuard],
    children: [
        {
            path:'test1', component: CalendarComponent
        }
    ] },
    { path: '**', component: DashboardComponent }

]
```
I have the `<base href='/'>` on my index.html file. Also, i have the `<router-outlet>` tag too on my component.

If i put on the browser:

`http://localhost:8000/adminarea` or `http://localhost:8000/dashboard` the page and the route is displayed normally. But if i put `http://localhost:8000/adminarea/test1` then the page is broken with strange errors:

![image](https://cloud.githubusercontent.com/assets/5152002/25304767/bfa6f4f4-273b-11e7-9228-e043497d7a84.png)

If i put any sub route (or child) of any parent on my browser address bar then got this same error and behavihor. For example:

`http://localhost:8000/dashboard/xyz
`But if i have { path: '**', component: DashboardComponent } should not redirect to my DashboardComponent (in case that is a 404 route)? Why my child route 'test1' don't work?

**Expected behavior**

I want to put on the address bar: `http://localhost:8000/adminarea/test1` and access to the child route
 
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, MS Code, npm, nodejs
* **Angular version:** 4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All
* **Node (for AoT issues):** `node --version` =   
v6.10.2

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
