### ISSUE TITLE
How to implement Airline calendar with Angular 4 

### ISSUE THREAD

**Issue by vibingopal** [angular/angular#16267]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ x] feature request

**Current behavior**
Hi ,

I am trying to implement Airline calendar with Angular 4 release But unable to do that. Any idea on already existing module with the same feature where user can't allowed to select previous dates

Version : Angular 4

**Comment by fxck** [comment]
http://lmgtfy.com/?q=angular2+calendar

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
