### ISSUE TITLE
template's local variable not honored by *ngIf/*ngSwitch 

### ISSUE THREAD

**Issue by richlim** [angular/angular#16262]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

Passing local variable to a component works only if the component
delivering local variable is not subject to *ngIf/*ngSwitch in the template

**Expected behavior**

Local variable (or null/undefined) should be passed to components
referencing it on creation/destruction of the referenced component

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/Doy0zrLPUKhoHHXFNKjI

**What is the motivation / use case for changing the behavior?**

I want a component to execute actions depending on existence
of certain component(s).

**Please tell us about your environment:**

iOS 10.14.2, VisualCode

* **Angular version:** 2.0.X

4.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 I guess, all.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

* **Node (for AoT issues):** `node --version` =   
irrelevant

**Comment by dawidgarus** [comment]
Here's explained why angular behaves like this: http://stackoverflow.com/a/36651625

**Comment by mhevery** [comment]
Sorry, this is working as intended per explanation ^^^^. 
The `#ADd` refers to the template ref, not the component, hence the behavior. Imagine that it would be `*ngFor` (instead of `*ngIf`) You would have more than one `#ADd` or even zero.

**Comment by richlim** [comment]
I see :|
Thank your for your time/knowledge.
