### ISSUE TITLE
bug? : Child Resolver still run after navigate away from Parent's Resolver

### ISSUE THREAD

**Issue by gedclack** [angular/angular#16271]
```
[x ] bug report
```

**Current behavior**
I made 2 resolve in the route, a parent and a child resolver, but when I do `router.navigate(['somewhere'])` in the parent's resolver, **the child's resolver still run**

**Expected behavior**
I think when it navigates away in Parent's resolver, it should cancel the routing, then the Child's resolver won't run.

**Minimal reproduction of the problem with instructions**
any routes that has parent and child resolver can reproduce this. but here is my routes :
```
const myRoutes: Routes = [
	{
		path: '',
		component: DashboardComponent,
		resolve: { ha: ParentResolver },
		canActivateChild: [ AuthGuard ],
		children: [
			{
				path: 'xxx',
				loadChildren: 'app/dashboard/xxx/xxx.module#xXx', resolve: { isValid: ChildResolver }
			}
		]
	}
];
```

* **Angular version:** 4.0.2
* **Browser:** Google Chrome
* **Language:** TypeScript 2.X

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
