### ISSUE TITLE
INTERNATIONALIZATION (I18N)  is not generating messages.xlf

### ISSUE THREAD

**Issue by junaidahmed93** [angular/angular#16279]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Trying to generate "message.xlf" using ng-xi18n (with and without flag) as instructed in angular cookbook  INTERNATIONALIZATION (I18N)
but didn't get message.xlf on root project (or src folder).

**Expected behavior**

There should be generate translation source file according to docs.

**Minimal reproduction of the problem with instructions**

* **Angular version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
> Trying to generate "message.xlf" using ng-xi18n (with and without flag) as instructed in angular cookbook INTERNATIONALIZATION (I18N)
but didn't get message.xlf on root project (or src folder).

I think that we need more details here (sample repository + steps to reproduce).

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
