### ISSUE TITLE
Remove ng-version from the DOM generated in Production Mode

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#16283]
Currently the DOM generated by Angular 2 app contains **ng-version** as an attribute.

For example : ng-version="4.0.1"

Its not clear what benefit does it provide in production mode?

If its not used internally by angular? Should it be removed? or should it be optional?

**Comment by mhevery** [comment]
This is there intentionally, so that tools such an augury, can detect that it is an angular page and can provide useful UI.

**Comment by smartm0use** [comment]
How to deal with W3C validation?

**Attribute ng-version not allowed on element div at this point.**

Does exist any way to disable it?

**Comment by smartm0use** [comment]
I have created a PR about this... hope someone can apply it.

**Comment by smartm0use** [comment]
Meanwhile someone accept my PR, I pass W3C validation using javascript:

    @Component({
        selector: '[data-app]',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.scss']
    })
    export class AppComponent {
        constructor(private _elementRef: ElementRef) {
	}

	ngOnInit(): void {
		this._elementRef.nativeElement.removeAttribute("ng-version");
	}
    }

**Comment by naveedahmed1** [comment]
Shouldn't there be an option to enable/disable it?

**Comment by matiger** [comment]
@mhevery Since he talks about the production mode, I wouldn't say that Augury (and whatever) is an issue here. More so, I'd argue that disclosing of version information is considered as harmful in big parts of the security community.

**Comment by mlc-mlapis** [comment]
@matiger ... don't you think it's a false security illusion then? Real security is not based on it. It's the same as thinking that an unknown algorithm is safer than the known one.

**Comment by naveedahmed1** [comment]
Probably giving developer the option to enable/disable it makes more sense.

**Comment by nemhods** [comment]
@mlc-mlapis It's considered good practice to hide version information. You can almost never create a 100% secure system, therefore the goal is to deter attacks as much as possible.

If a vulnerability becomes public in a specific angular version, attackers will be able to leverage search engines such as shodan to quickly identify all vulnerable websites out there that use this version. If the version number was hidden, the attacker would have to resort to fingerprinting the website to derive the version number themselves. this is time consuming and imprecise for the attacker - thus hiding the version number is another useful deterrent to attacks.

**Comment by mlc-mlapis** [comment]
@nemhods ... hmm, 99,9 % of the real security layer is located on a server. The client side can't do a lot for it in reality.

**Comment by nemhods** [comment]
@mlc-mlapis yeah, the server side has the more severe security problems.
There are many possible client-side vulnerabilities in web applications though. Cross-site scripting would be the most prominent one.

**Comment by naveedahmed1** [comment]
@mlc-mlapis angular apps run on server environment as well in case of SSR/Universal.

**Comment by matiger** [comment]
I dont see a good reason to put the version in. I do, however, see a few reasons to leave it out (arguably valid or not, although @nemhods makes a very good point.) Therefore it should be either up to the developer, or just be left out.

**Comment by jesselima** [comment]
To know the version is not a safe practice. Attackers may look for specific vulnerabilities of your version and explore it. If they do not know the version is so much harder to find a security breach. It's a very known practice for databases.
