### ISSUE TITLE
Use of Object.assign unsupported in IE11 or Android and generating 

### ISSUE THREAD

**Issue by NormSoftwareEng** [angular/angular#16286]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In https://github.com/angular/angular/blob/master/packages/common/src/pipes/intl.ts

the function 

function combine(options: Intl.DateTimeFormatOptions[]): Intl.DateTimeFormatOptions {
  return (<any>Object).assign({}, ...options);
}

generates an exception when building PATTERN_ALIASES	in IE11 because Object.assign is not supported in IE11 or Android.

SCRIPT5007: Unable to get property 'apply' of undefined or null reference

**Expected behavior**
succesfully build PATTERN_ALIASES on all platforms

**Minimal reproduction of the problem with instructions**
Include node_modules\@angular\common\@angular\common.es5.js

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Win 7, VSCode, WebPack
Created using 
npm install -g @angular/cli
ng new 

* **Angular version:** 4.0.0
"dependencies": {
    "@angular/animations": "^4.0.2",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@progress/kendo-angular-dropdowns": "^0.39.0",
    "@progress/kendo-angular-grid": "^0.26.3",
    "@progress/kendo-angular-inputs": "^0.23.2",
    "@progress/kendo-angular-intl": "^0.12.0",
    "@progress/kendo-angular-l10n": "^0.3.0",
    "@progress/kendo-data-query": "^0.5.1",
    "@progress/kendo-drawing": "^0.15.5",
    "@progress/kendo-theme-default": "^2.29.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"

* **Browser:** [IE 11 ]
 
* **Language:** [all | TypeScript 2.2 |ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
`Object.assign` is part of the [core-js](https://github.com/zloirock/core-js/blob/v2.4.1/modules/es6.object.assign.js) so it seems to me that you are not including this polyfill properly. Could you please share a plunker that reproduces the issue?

Also check https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by NormSoftwareEng** [comment]
That would be it.  

Since including these polyfills is a manual step in the process, my contribution for this would be to suggest writing a warning message to the console in intl.ts to "check polyfills" if Object.assign is undefined or something equivalent, just to catch the typical occurance . 

I don't know if it was just me or not, but I wasn't finding a solution with the searches I was using and seems like this issue would be a trouble hot spot. 

Thanks
