### ISSUE TITLE
docs(aio): Include Submenus

### ISSUE THREAD

**Issue by spottedmahn** [angular/angular#16288]
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The left hand menu does not include submenus

**Expected behavior**
Please include a submenu on the tree on the left.  For example, I was reading the [Routing and Navigation](https://angular.io/docs/ts/latest/guide/router.html#) and it is a very long page.  There's a sub-menu but it is all the way at the top.  Even if I'm somewhere in the middle it would be much easier to navigate from the tree on the left than having to navigate all the way back to the top.

![image](https://cloud.githubusercontent.com/assets/14079228/25357844/56ca5204-290d-11e7-98e4-a99c15d37bdf.png)

**What is the motivation / use case for changing the behavior?**
Easier to read/navigate documentation

**Comment by Foxandxss** [comment]
We are working on a new site and the Router guide is the first one that is going to get exactly what you want. Be split into different parts with submenus on the left.

I am going to close this because that is already top priority in our list.
