### ISSUE TITLE
Nothing happens when invalid search query is entered into the search box

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16294]
Steps to repro:
1. go to https://aio-staging.firebaseapp.com/
2. start typing into the search box: "templa"
3. check search results
4. type "x", to turn the search query into "templax"
5. check search results

Expected: I get some kind message in the ui, like: `no search results found for query "templax"`
Current: the search results disappear

<img width="1918" alt="screen shot 2017-04-25 at 2 49 34 am" src="https://cloud.githubusercontent.com/assets/216296/25364385/6faf80a0-2962-11e7-94e2-74670adb8638.png">

**Comment by wardbell** [comment]
Resolved by PR #16443
