### ISSUE TITLE
CSS issues on the styleguide page

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16291]
https://aio-staging.firebaseapp.com/guide/styleguide#02-03

<img width="1920" alt="screen shot 2017-04-25 at 12 56 09 am" src="https://cloud.githubusercontent.com/assets/216296/25362610/526ad632-2955-11e7-87ba-6bf2630cb425.png">

**Comment by sjtrimble** [comment]
This is a dupe: https://github.com/angular/angular/issues/16241
