### ISSUE TITLE
Better alignment of the "Copy to clipboard" icon

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16292]
Currently we vertically align the "copy to clipboard" to the center of code snippet:

<img width="665" alt="screen shot 2017-04-25 at 1 33 49 am" src="https://cloud.githubusercontent.com/assets/216296/25362966/781ade98-2957-11e7-98ce-8f4d37a7d579.png">

This looks unusual to me. We could either move it up:

<img width="665" alt="screen shot 2017-04-25 at 1 33 49 am" src="https://cloud.githubusercontent.com/assets/216296/25363472/fd8a82ec-295a-11e7-8571-683845495efa.png">

Which I'm afraid won't look much better. Or we could move it top-right corner, where it originally was. But in order for the icon not to be too far away from the code, we should constrain the width of the content and center it. Maybe something along the lines of this:

<img width="1365" alt="screen shot 2017-04-25 at 2 04 27 am" src="https://cloud.githubusercontent.com/assets/216296/25363574/cc8f2f98-295b-11e7-8d2c-fa51984e5a6c.png">

@sjtrimble how did we end up with the icon on the left? was there a reason for it?

**Comment by sjtrimble** [comment]
I believe this was an unintentional result of https://github.com/angular/angular/pull/16226/files

@petebacondarwin Can you verify that I'm not destroying anything by adding the class back in in https://github.com/angular/angular/pull/16298?

**Comment by gkalpak** [comment]
It seems unexpected to have a generic class (such as `mat-icon` or `material-icons`) position items on the top right corner. I think we need to target the copy button (or other icons that need it) specifically.

**Comment by petebacondarwin** [comment]
@gkalpak I don't think that is what the PR is doing. It is just providing normal styling for icons. There is other styling for putting it in the top right, which relies upon this generic styling.

**Comment by petebacondarwin** [comment]
See https://github.com/angular/angular/blob/master/aio/src/styles/2-modules/_code.scss#L90-L102

**Comment by gkalpak** [comment]
@petebacondarwin, I was not referring to a specific PR. I was referring to the fact that we use a very generic selector to target all icons, while the desired behavior is probably to affect sidenav icons only: [here][1]

<sub>(I see now that it is not related to the copy button issue anyway. @sjtrimble, can you confirm that we shouldn't be doing [this][1], but specifically target icons inside the sidenav?</sub>

[1]: https://github.com/angular/angular/blob/11b2f62ed25bfb2a96dce07cac779176e1b0e1e2/aio/src/styles/1-layouts/_sidenav.scss#L97-L103
