### ISSUE TITLE
docs(aio): code sample fails to display

### ISSUE THREAD

**Issue by swseverance** [angular/angular#16296]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

code-tabs / code-pane directives in toh-pt5.md do not properly render the code sample
```
<code-tabs>
  <code-pane path="toh-pt5/src/app/app.module.ts" title="src/app/app.module.ts (after)"></code-pane>
  <code-pane path="toh-pt5/src/app/app.module.3.ts" title="src/app/app.module.ts (before)"></code-pane>
</code-tabs>
```
![image](https://cloud.githubusercontent.com/assets/18009315/25365386/4fadab96-2936-11e7-82c1-eb3c78d77852.png)

**Expected behavior**

The code sample should display properly

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by gkalpak** [comment]
Closing, since this has been already fixed on the [latest -not yet deployed- version][1].

[1]: https://aio-staging.firebaseapp.com/tutorial/toh-pt5#update-appmodule
