### ISSUE TITLE
Multiple module.ts won't work

### ISSUE THREAD

**Issue by jeroenouw** [angular/angular#16303]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X ] support request 
```

**Current behavior**
In my project I have a app.module.ts where I declare all components, services etc. But it becomes a too long and unclear file, so I want per component group a module.ts like example I have already setup: [backgrounds.module.ts](https://github.com/jeroenouw/Angular4MaterialDesign/blob/master/src/app/components/backgrounds/backgrounds.module.ts ) 

When I import these new modules in my  [app.module.ts](https://github.com/jeroenouw/Angular4MaterialDesign/blob/master/src/app/app.module.ts) (Currently commented) all my components from for example the backgrounds.module.ts won't work.

**Expected behavior**
What I want is multiple smaller module.ts imported in the app.module.ts and working normally.

**Repository where you can test if necessary**
[https://github.com/jeroenouw/Angular4MaterialDesign](https://github.com/jeroenouw/Angular4MaterialDesign)

* **Angular version:** 4.X

* **Language:** [all]

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
To be able to use `Component`s from an improted Module, the imported Module must include those `Component`s in the `export` array of the Module.
More here https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html

**Comment by pkozlowski-opensource** [comment]
Thnx @Toxicable for helping out with the issues, much appreciated!
