### ISSUE TITLE
Binding doesn't work anymore after setting bound value in ViewChild setter

### ISSUE THREAD

**Issue by lexon0011** [angular/angular#16305]
**I'm submitting a** 
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Binding doesn't work anymore after setting bound value in ViewChild setter

**Expected behavior**
Binding keeps working as expected

**Minimal reproduction of the problem with instructions**
See the provided sample on plunker: [sample](https://plnkr.co/edit/phBeO8eATuEm5jJO2hlF?p=preview)
As you can see in the app.component.ts I change the bound property "showMyComponent" in the ViewChild setter. If I use a setTimeout for this action, it behaves as expected (look  at the commented line)

* **Angular version:** version from https://unpkg.com

* **Browser:** all

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
you have a few issues this the code here
-`showMyComponent` is not defined because in the setter you haven't defined it, I think you want to do : `this.showMyComponent = !this.showMyComponent;`
-Once you fix the above issue then you get the `ExpressionChangedAfterItHasBeenCheckedError` error which means you're changing a value *during* a CD run which you should not be doing
```
@ViewChild(MyComponent) set myComponent(value: MyComponent){
    this.showMyComponent = !showMyComponent;    
    //setTimeout(() => { this.showMyComponent = !showMyComponent;});
  };
```
