### ISSUE TITLE
delete old branches?

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#1630]
![](http://cdn.meme.am/instances/250x/61790099.jpg)
* update-traceur
* rename-to-ats
* chirayu-debug-travis
* update_docs_about_on_change
* newrouter

<hr>

![](http://cdn.meme.am/instances/250x/61790079.jpg)
* ts2dart
* rado-presubmit
* presubmit-naomi
* kegluneq_change_detect

<hr>
Keep
* perftest

**Comment by pkozlowski-opensource** [comment]
Yes, +1

**Comment by btford** [comment]
We can get rid of `newrouter`

**Comment by tbosch** [comment]
perftest needs to stay as we use it in our (currently not working) local
travis machine for manually pushing changes on which perftests should be
executed...

**Comment by mhevery** [comment]
cleaned up
