### ISSUE TITLE
[i18n] - Overriding of xlf file

### ISSUE THREAD

**Issue by DanniB** [angular/angular#16304]
I'm submitting a ...

`[x] feature request`
Current behavior
Generating to an existing i18n file overrides target sections (`<target/>`)

Expected behavior
Already generated trans-units should not be overridden during generation. 

What is the motivation / use case for changing the behavior?
Avoid copy & paste errors because no need to copy trans-units from one file to another

**Comment by vicb** [comment]
This is by design.
Angular only generates xlif files. Use a translation tool if you need.
