### ISSUE TITLE
【Request】New syntax for css encapsulation

### ISSUE THREAD

**Issue by kgtkr** [angular/angular#16315]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Encapsulation of CSS with material2.

#### What is the current behavior?
It can not be encapsulated.

#### What are the steps to reproduce?
````scss
//_my-component-theme.scss
@mixin my-component-theme($theme){
  my-component{
    //style
  }
}
````

````scss
//theme.scss
@import './app/my-component/_my-component-theme.scss';
@include my-component-theme($theme);
````

#### New syntax example
````ts
@Component({
  styleUrls: ['./_my-component-theme.scss#my-component-theme($theme)']
})
````

**Comment by pkozlowski-opensource** [comment]
I guess that the discussion should start in https://github.com/angular/material2. An issue here should be opened here only if material2 team determines that there is sth needed for changes the framework's core.

Closing for now, please open in https://github.com/angular/material2
