### ISSUE TITLE
Create a testing firebase environment for running e2e

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16311]
We need to be able to catch firebase rewrite rules issues before we push to staging/production. To do this we should:

- [ ] setup a new firebase instance called aio-testing.firebaseapp.com
- [ ] configure our CI to deploy there before pushing to production and run a few e2e tests there that test basic navigation (top page, deep navigation to guides and api docs)

**Comment by petebacondarwin** [comment]
I am not sure that this is a blocker for release. @IgorMinar can we move this to the TODO column.

**Comment by petebacondarwin** [comment]
@gkalpak and @IgorMinar is this still something we want to do?
Now that we have the monitoring tasks in CircleCI, I think we will get notified fairly soon about breakages, right?

**Comment by gkalpak** [comment]
I agree. Plus we have unit tests for the redirection rules.
The only thing that we can't catch is Firebase internal changes (e.g. in hosting behavior), but these can happen at any time, so running e2e tests against an actual Firebase instance adds little value imo.

**Comment by petebacondarwin** [comment]
Let's close then.
