### ISSUE TITLE
dgeni warnings about decorators in code snippets

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16319]
Looks like dgeni doesn't skip over code blocks marked with tripple backticks

```
info:    running processor: extractTagsProcessor
warn:    Invalid tags found - doc "common/index/APP_BASE_HREF" (let)  - from file "/Users/iminar/Dev/angular/packages/common/src/location/location_strategy.ts"
Line: NaN: @NgModule({   providers: [{provi...
```

Source: https://github.com/angular/angular/blob/5331fc1aab7d49a4d2f585e8edecd88247cc99a8/packages/common/src/location/location_strategy.ts#L52-L60

**Comment by petebacondarwin** [comment]
It used to, so I obviously seem to have broken something...

**Comment by petebacondarwin** [comment]
Ahah! Adding in the animations packages broke it. For ages I couldn't work out why.
But then I realised that there must be an unbalanced triple backtick in those docs.
The JSDOC parser tracks whether it is in a code block or not to decide whether it is supposed to ignore tags. But it was not re-initializing properly on each new run, so the bad docs from animations were putting everything out of sync.
