### ISSUE TITLE
Angular tutorial switchMap problem.. 

### ISSUE THREAD

**Issue by Naz786** [angular/angular#16324]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

On the Angular documentation Tour of Heroes Routing tutorial that I am following: https://angular.io/docs/ts/latest/tutorial/toh-pt5.html , I am on the "Revise the "HeroDetailComponent" section and the browser does not show the results expected. 

**Expected behavior**

To land in the dashboard page.

**Minimal reproduction of the problem with instructions**

AA question of the issue has been asked on stackoverflow: http://stackoverflow.com/questions/42549115/q-angular2-switchmap-does-not-exist-on-type-observableparams However the answer does not work any better. 

**What is the motivation / use case for changing the behavior?**

So that I am able to continue the Angular tutorial. 

**Please tell us about your environment:**
Windows 10, Chrome. 

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
You need to import `switchMap` via `import 'rxjs/add/operator/switchMap';`

**Comment by gkalpak** [comment]
You don't seem to follow the tutorial very closely (based on your code in the StackOverflow question), so it is not possible to know what might be wrong in your setup. In any case, [it seems][1] that you have been able to resolve this (one way or another), so I am going to close the issue.

[1]: http://stackoverflow.com/questions/42549115/q-angular2-switchmap-does-not-exist-on-type-observableparams#42642711

**Comment by Naz786** [comment]
The problem was that Visual Studio was giving red underline errors even though the actua application was working fine. So the application actually works, but Visual Studio gives the switchmap a red underline error for some reason.
