### ISSUE TITLE
aio: extracted titles sometimes contain HTML

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16325]
The HTML is leaking into the browser title bar.  We need to clean out the HTML before allowing it into the title property.

**Comment by petebacondarwin** [comment]
For example:

![screen shot 2017-04-25 at 19 43 05](https://cloud.githubusercontent.com/assets/15655/25402030/728cc278-29ef-11e7-8332-415739c42b91.png)

**Comment by petebacondarwin** [comment]
@wardbell is going to fix this as part of his work on walking the document contents.

**Comment by wardbell** [comment]
Fixed by client-side rendering of the title. Closing
