### ISSUE TITLE
Cant use shift/unshift on a FormArray 

### ISSUE THREAD

**Issue by Chris-Devine** [angular/angular#16322]
[x ] bug report
[ ] feature request
[ ] support request 

**Current behavior**
Typescript throws an error when trying to use  shift/unshift on a FormArray. So i cant add/remove FormGroups to the top of a FormArray

**Expected behavior**
i can add/remove FormGroups to the top of a FormArray

**Minimal reproduction of the problem with instructions**
Create a Form array and try to shift/unshift a formgroup. Eg..
const control = <FormArray>this.editTemplateFieldForm.controls['options'];
control.unshift(this.createEditTemplateFieldOptionsForm(tempIOption));

**What is the motivation / use case for changing the behavior?**
So i can add FormGroups to the start of a list and this will save the user having to scroll to the bottom of a page to get to the FormGroup thats been added to modify it. 

**Please tell us about your environment:**
windows: 10 
angular-cli: 1
typescript: 2.2.0

* **Angular version:** 
4.0.3

**Comment by Toxicable** [comment]
Works fine here
https://plnkr.co/edit/g0ga9o8vkvq390XnUPl4?p=preview

**Comment by pkozlowski-opensource** [comment]
Thnx @Toxicable . @Chris-Devine could you please share a live reproduce scenario in a plunker? Hardly possible to action on a bug without a live reproduce, here is why: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue

**Comment by Chris-Devine** [comment]
I will try to reproduce in plunkr and get back to you

**Comment by Chris-Devine** [comment]
Here is a plunker

http://plnkr.co/edit/tW4bnatLYYeYdBtKtsoV?p=info

**Comment by Toxicable** [comment]
@Chris-Devine `FormArray` does not have the unshift method as seen here https://angular.io/docs/ts/latest/api/forms/index/FormArray-class.html
You can access the underlying `Array` by using `FormArray#controls` then use unshift as seen here
http://plnkr.co/edit/gSTTIfKRE47EC3DuLmW6?p=preview

**Comment by Chris-Devine** [comment]
I see now. My mistake it just that control.push worked and mislead me to believe it should be the same for shift/unshift/pop.

Feel free to close the bug. Thanks a lot for the support, sorry to waste your time

**Comment by Toxicable** [comment]
@Chris-Devine you can close this issue if it is now resolved. I cannot close it for you.

**Comment by pkozlowski-opensource** [comment]
Thnx @Toxicable for helping out with the issues!!!

**Comment by brunomrpx** [comment]
An alternative is to use the method insert from FormArray class with the position 0: ```formArray.insert(0, formGroup)```. By this way if any FormGroup is invalid the FormArray is also invalid. Using ```formArray.controls.unshift(formGroup)``` nested validation doesn't work.
