### ISSUE TITLE
docs: update browser support documentation with note on IE compatibility view

### ISSUE THREAD

**Issue by brosenfi** [angular/angular#16329]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Browser support documentation at https://angular.io/docs/ts/latest/guide/browser-support.html details IE 9/10/11 support with polyfills, but does not mention how support is not there for those same browsers in "compatiblity view".  

**Expected behavior**

Documentation on https://angular.io/docs/ts/latest/guide/browser-support.html specifies lack of support for IE 9/10/11 in "compatibility view" mode.  Info on how to instruct IE to not load in compatibility view would be a bonus.

**Minimal reproduction of the problem with instructions**

Very easy to reproduce on IE 11 - setup a test project via `ng new TestApp`, run via `ng serve`, then open in IE 11 and force it into compatibility view via "Change Compatibility View Settings" - add localhost - app will fail with multiple errors.

**What is the motivation / use case for changing the behavior?**

This little bit of documentation could save people time looking for the wrong root cause on errors and from opening up phantom IE bug reports.

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE 9/10/11
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by brosenfi** [comment]
Apologies - forgot to include a couple of lines in the reproduction instructions:

`ng new TestApp`
Then include all of the needed polyfill modules as indicated inside of TestApp/src/polyfills.ts that are necessary for IE11 (uncomment the necessary lines).
`ng serve`
Open in IE 11 - site works showing "app works!" without compatibility view on
Force compatibility view on via "Change Compatibility View Settings" - add localhost - app fails with multiple errors

**Comment by pkozlowski-opensource** [comment]
Yeh, there is no intention of supporting compatibility view so a note in the docs would be in order. Marking as a documentation issue.

**Comment by jenniferfell** [comment]
Still an issue in v6 docs. 
Refined labels for more accurate triage/prioritization.
filename=https://angular.io/guide/browser-support

**Comment by jbogarthyde** [comment]
Resolved by https://github.com/angular/angular/pull/31808
