### ISSUE TITLE
Will components inside SVG be supported?

### ISSUE THREAD

**Issue by Pajn** [angular/angular#1632]
Currently elements inside the components template seems to be rendering using the xhtml name-space and is not showing up on the screen. I realize Angular 2 is in an early stage but I wanted to know if this scenario is on the track at all.

I.E. this is the usecase i mean:
```
<svg>
  <my-component></my-component>
</svg>
```

**Comment by mhevery** [comment]
1. Yes we want to support SVG
2. not sure what custom element inside SVG really means. SVG does not have shadow DOM. Can you better describe your use case?

**Comment by Pajn** [comment]
For this project I more or less desided on UIX at least for this part, but I can still discuss the use case if you want.

I'm working on a visual programming tool using nodes/blocks that connects via wires. Similar to Unreal Engines Bluprint system (https://docs.unrealengine.com/latest/images/Engine/Blueprints/Editor/blueprint_editor_example.png). The work area are completely rendered in SVG to be able to render advanced shapes but keep all event handling from the DOM that would have been lost with canvas.

Because of the complexity of the work area it's built using multiple nested components, having everything in a single would just not be feasible.
From what I have seen by UIX and React the short while that I have tested them, that kind of library may be a better fit than the very template oriented approach by Angular anyway. So it may be that I first intended to use it for something it was never meant for, but that is the use case ;)

**Comment by mhevery** [comment]
not actionable

**Comment by Vinnl** [comment]
So to be clear: Angular will not support composing SVG documents using separate components? Or in other words, as [mentioned in the documentation of Angular 1](https://docs.angularjs.org/api/ng/service/$compile#-replace-deprecated-will-be-removed-in-next-major-release-i-e-v2-0-) for the deprecated `replace` option:

> There are very few scenarios where element replacement is required for the application function, the main one being reusable custom components that are used within SVG contexts (because SVG doesn't work with custom elements in the DOM tree).

...that main scenario is no longer supported by Angular 2?

**Comment by nborelli** [comment]
In alpha 45, if you use a attribute selector for a SVG group, it will work, but I cannot seem to get the component as a custom element syntax that you are looking for to work.

```javascript
@Component({
  selector: 'g[inner-svg]'
})
@View({
  template: `
    <text x="10" y="20">{{ text }}</text>
  `
})
export class InnerSvg {
  @Input() text: string;
}
```
```html
<svg>
<g inner-svg text="This works"></g>
</svg>
```

**Comment by mhevery** [comment]
@nborelli: yes this is a known issue with the new compiler, and we are working on a fix (@tbosch)

**Comment by Pajn** [comment]
This is an edge case so using g with attribute selectors is absolutely fine. Nice to see that it works :)

**Comment by megasmack** [comment]
@mhevery Sorry to dig up an old post, but is the know issue you mentioned being tracked? If so can you link that issue so I can follow it? I'm looking to do a similar project like the original poster.

**Comment by MonkeyDo** [comment]
Same here, this is a feature I would love to see on the map.
For now the g[attribute] solution will have to do.

My use case is reusable components that generate svg programatically (using D3, ported from another project) and that I would like to use both in regular html and in svg elements.

For example:
```html
<gauge-component>
    <svg>…</svg>
</gauge-component>

<svg>
    <gauge-component>
        <svg>…</svg>
    </gauge-component>
    <gauge-component>
        <svg>…</svg>
    </gauge-component>
</svg>
```

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166561.
------------------------------------------------------------------------------------------------------------


[[5f562426a877ea244fb06fcd9b8a966eff1a3b70-673074314]]

**Comment by Svjard** [comment]
Is there any workaround when using <ng-content>, even though I can use the attribute selector workaround for certain pieces of our ported code, we still need have components which rely on <ng-content>and that is currently a blocker. Would be nice to see a workaround in that case at least.

**Comment by smurphy917** [comment]
Any potential upcoming support for `[ngForOf]` on SVG-namespaced elements (i.e. `<g>`)? My use case is to create an SVG block with multiple components (paths) based on component data. It's the classic Angular2 use case, but with SVG elements vs (x)html elements. 

I have something like: 
```
@Component({
    selector: 'my-component',
    template: '<svg><g my-subcomponent *ngFor="let d of data;"></g></svg>'
})
export class MyComponent {
    data = [1, 2, 3, 4, 5];
}
```
And:
```
@Component({
    selector: 'g[my-subcomponent]',
    template: '<svg:path d="M0 0,H100"></svg:path>'
})
export class MySubComponent {}
```
Which returns:
```
Can't bind to 'ngForOf' since it isn't a known property of ':svg:g'.
```

**Comment by mhevery** [comment]
Can you create a plunker showing the error? What you are describing should
work.

**Comment by smurphy917** [comment]
Silly mistake - forgot to import `BrowserModule` into a separate feature module. Thus the `ngForOf` directive wasn't recognized and it was trying to find it as a property of `:svg:g`. Move along...nothing to see here...

**Comment by stijmeer** [comment]
I just found [this great article](https://teropa.info/blog/2016/12/12/graphics-in-angular-2.html) explaining how to use svg-components with angular 2!

You will have to namespace the svg elements and use an attribute selector for the component:

```
@Component({
  selector: '[app-logo-left]',
  templateUrl: './app-logo-left-component.html'
})
```
```
<svg viewBox="0 0 250 250">
  <svg:g app-logo-left />
  <svg:g app-logo-right />
  <svg:g app-logo-a />
</svg>
```

**Comment by dgroh** [comment]
only using namespace it does not work.

In plain HTML it's working: https://plnkr.co/edit/3DlIMZuvtxIDiLet5Vpt?p=preview

I get this error in the Angular 5 application:

> :inkscape:perspective' is not a known element:

Here is the plunker with Angular 5: https://plnkr.co/edit/1iJadaGc8CN8NoWhpDwV?p=preview

**Comment by pilsen86** [comment]
Is it possible to inject dynamic components that are child svg elements? 
For instance, I have a main component (CanvasComponent) , and its template is something like this

```
<svg width="400" height="400">
 <ng-template appCanvasAnchor></ng-template>
</svg>

```
That ng-template is the anchor used to dynamically inject components as per [https://angular.io/guide/dynamic-component-loader](url)

The dynamic (SquareComponent) has got this template
`<svg:rect width="100" height="100" style="fill:red" />`

Now, because of the way dynamic components get added to the DOM, when my Square component gets added to the canvas component it'll be contained by a div element like below.

```
<svg width="400" height="400">
  <div app-square>
   <rect width="100" height="100" style="fill:red" />
 </div>
</svg>
```

In theory that all works pretty well, except for the fact that this is SVG, and therefore my square won't render because it's got unknown markup (the div). The question here is, can I somehow change what element the injector uses so that rather than using a div, it uses and svg know element like g?

**Comment by shmorhun** [comment]
Hi, but what about simple html angluar component inside svg?

import { Component, Input } from '@angular/core';

@Component({
  selector: 'my-component',
  template: `<span>Holle from Angular</span>`,
})

export class MyComponent {
}


Now I need
<svg>
<my-component>
</my-component>
</svg>
but it doesn't work

**Comment by MonkeyDo** [comment]
@shmorhun, you can try using [attribute directives](https://angular.io/guide/attribute-directives), and make sure you use SVG elements like <g> and <text> in your template. html elements will not be rendered
[See it in action in Plunker](https://plnkr.co/edit/yQWkXUKJO9N5Bg21lLJ6?p=preview)

In short:
```
@Component({
selector: 'g[my-component]',
template: <text x=0 y=30>Holle from Angular</text>,
})
```

and then use `<svg> <g my-component> </g> </svg>`
