### ISSUE TITLE
docs(aio): BAD FILENAME for NG_VALIDATORS-let.html

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#16331]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Example is not linked for https://angular.io/docs/ts/latest/api/forms/index/NG_VALIDATORS-let.html

**Expected behavior**
Example should be linked.

**Comment by gkalpak** [comment]
This will be fixed by #16326.
