### ISSUE TITLE
Translation not recognized on production (webpack, JIT)

### ISSUE THREAD

**Issue by Masterrg** [angular/angular#16339]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using the "official" angular i18n to provide translations for my app. I am [loading the specific xlf file from the backend](https://pastebin.com/2rH8Teb3) (Promise) and hand it over to bootstrapModule() in the[ main.ts](https://pastebin.com/nRSbJtdH) file.

Everything works fine as long as my app isn't in production mode, as soon as I switch to it, it seems like the translations aren't recognized anymore (even though no error messages are thrown).

Dev: http://prntscr.com/f0ylzi
Production: http://prntscr.com/f0ym9j

The xlf file is requested and loaded correctly in both cases from the specific backend (http://prntscr.com/f0yn5w)

**Expected behavior**
The translations should be recognized.

**Minimal reproduction of the problem with instructions**

main.ts: https://pastebin.com/nRSbJtdH
i18n-provider.ts: https://pastebin.com/2rH8Teb3

1. Create a new empty project via angular-cli
2. Add a translation provider which loads the xlf file from the server
3. Add the provider to your main.ts
4. Add some translations to the template and create a xlf file
5. Switch between production and development environment

**What is the motivation / use case for changing the behavior?**

Well ehm, it should work I think? :)

**Please tell us about your environment:**

Dev Environment: W10 x64, PHPStorm 2016.3.2, NPM, ng-serve integrated HTTP Server
Prod Environment: Debian 8 x64, NPM, nginx

* **Angular version:** 4.0.3

* **Browser:** [Chrome XX | Firefox XX]

 
* **Language:** [TypeScript 2.3]

* **Node (for AoT issues):** `node --version` =  7.4.0 (JIT)

**Comment by jakob-bebop** [comment]
I have the same problem with @angular/core@4.1.0.

The broblem is also reproducable by running `ng s -t production -e dev`, meaning that:
 - the build is production (lazy-loaded code in seperate bundles)
 - the app prints "Angular is running in the development mode" etc. in console
 - the translation file xlf still loads, but it doesnt get loaded.

####I tried to debug it:
I used this provider object  at bootstrap
```
{
        provide: TRANSLATIONS,
        useFactory: () => {
          console.log("Providing translations", translations.substring(0,50));
          return translations
        }
}
```

and the factory method is not called (which otoh it does if I run the development build)

**Comment by ocombe** [comment]
If you set the flag `-t production` or `--prod` it sets the build to use AoT.
For AoT the cli creates a new "main" file that is different from the dev one.
To use i18n with AoT you must pass the i18n parameters as cli arguments, it won't matter if you set them in your dev main file.
The reason is that you will probably build your application for multiple locales, and you shouldn't have to edit your main file for that.

To know how to use arguments for build, please read the i18n story in the angular-cli wiki: https://github.com/angular/angular-cli/wiki/stories-internationalization

**Comment by jakob-bebop** [comment]
Thank you! Setting --aot=false helped

**Comment by fixako** [comment]
thanks this helped me!

**Comment by bcneves13** [comment]
I have a question yet.
What's the difference between '--aot=false' And not using '--aot' ?
the cli compiles different between these two?
