### ISSUE TITLE
aio: fixed maximum width content makes home page look weird

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16337]
The content now has a fixed maximum width (thanks to #16301) but this makes the homepage splash look a bit strange on a wide screen, since it now leaves a blank space to the right.

Perhaps we should add more one-off styling for this page?

![screen shot 2017-04-26 at 08 53 57](https://cloud.githubusercontent.com/assets/15655/25423884/26b241ce-2a5e-11e7-8100-b8d0e0668b4d.png)

**Comment by sjtrimble** [comment]
This should be removed once @wardbell's PR lands tagging the marketing pages differently. We'll need this for the design refresh regardless.

The md-sidenav (that contains the max-width restriction) is above the section IDs we currently have available, so we'll need the aio-shell tags that encompass the entire page to apply custom styling to the marketing pages as intended.
