### ISSUE TITLE
Transition animation skipped when used with router.navigate in Firefox.

### ISSUE THREAD

**Issue by p0kjin57** [angular/angular#16348]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Transition animation is skipped when used with router.navigate in Firefox.

**Expected behavior**

Transition animation is rendered for the amount of transition-duration specified.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/fokgaGNVDkwpESsxTsAm?p=preview

Try to toggle back and forth between Dashboard and Heroes in different browsers
to see the issue. In Chrome, and Safari the animation (changing text color from black to yellow)
happens in the duration of 3000ms, but in Firefox this happens instantly.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4

* **Browser:** [Firefox 53.0]

**Comment by matsko** [comment]
So the code in the tour of heros code doesn't have any tracking to reflect what's in the URL for the buttons. So if you hit back and forth then nothing happens. This issue doesn't have anything to do with Angular animations or Angular at all.
