### ISSUE TITLE
Testability API not stabalizing - ng-upgrade

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#16349]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After introducing zones in an ng-upgrade app, existing Protractor tests fail due to pending macro task check.

The testability API is used by external tools like Protractor to determine if an Angular application is stable. The typical use case is waiting for http requests to complete before asserting against the UI.

One of the conditions for "stable" is no pending macro tasks (xhr, setInterval, timeout, etc). If a macro task is still "in flight", Protractor waits for the event to finish. However, there is an issue with long running setIntervals. The macro task stays in pending state until the interval is cancelled. This means applications with never ending intervals will never be stable per the testability check.

**Expected behavior**
There should be a way to allow setIntervals to live on in the app, without blocking Protractor tests.

**Minimal reproduction of the problem with instructions**
I have a repro of this behavior here: https://github.com/thelgevold/e2e-ngupgrade-clock
The application implements a clock using an interval.
This particular application is an ng-upgrade application.

I also have some more detailed info here: http://www.syntaxsuccess.com/viewarticle/ngupgrade-and-long-running-intervals

So far the only workaround I've found is to run the interval in a new Zone. This ensures that the interval is not counted towards the pending macro task check.

ex:

```
// AngularJS part of ng-upgrade application
new Zone().run(() => {
      $interval(() => {
         this.time = new Date().toLocaleString();
      }, 100);
    });
```
I had to create a brand new zone. It doesn't work to fork the current zone since it inherits the problematic pending check.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Angular CLI

* **Angular version:** 4.0.X

* **Browser:** all
 
* **Language:** [TypeScript]

**Comment by olore** [comment]
The other workaround we found was to grab `window.setInterval` before zone.js gets loaded. Far from ideal, but functional.

```
window.oldSetInterval = window.setInterval;
<script src="lib/zone.min.js"></script>

// use window.oldSetInterval instead of setInterval if you want to avoid the zone
```

**Comment by heathkit** [comment]
You can also make your AngularJS $timeout calls Zone-aware like this:

```js
if (Zone && Zone.current.name === 'angular') {
  let angularZone = Zone.current;
  Zone.parent.run(() => {
    $interval(() => {
       // Stuff here is run outside the Angular zone and will not be change detected
       angularZone.run(() => {
         // Inside the zone and will be change detected.
       });
    }, 500);
  });
}
```

I am working on a fix for this, though.

**Comment by ChrisGibb** [comment]
browser.waitForAngularEnabled(false);

worked for me
