### ISSUE TITLE
Custom attribute dot bind the imageUrl

### ISSUE THREAD

**Issue by atlabiz** [angular/angular#16341]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
    zone.js:569 Unhandled Promise rejection: Template parse errors:
    Can't bind to 'default-file' since it isn't a known property of 'input'. ("ers/200x200.png" data-
    height="300" />-->
                    <input type="file" [(ngModel)]="image" [ERROR ->]data-default-file="{{imageUrl}}" 
     name="image" class="dropify" data-height="400" />

                 "): ng:///AppModule/AdminProsforaDetailsComponent.html@148:59 ; Zone: <root> ; Task: 
     Promise.then ; Value: Error: Template parse errors:
     Can't bind to 'default-file' since it isn't a known property of 'input'. ("ers/200x200.png" data-
     height="300" />-->
                    <input type="file" [(ngModel)]="image" [ERROR ->]data-default-file="{{imageUrl}}" 
    name="image" class="dropify" data-height="400" />

     "): ng:///AppModule/AdminProsforaDetailsComponent.html@148:59
    at syntaxError (http://localhost:4200/vendor.bundle.js:47755:34) [<root>]
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:57764:19) [<root>]
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:71538:39) [<root>]
    at http://localhost:4200/vendor.bundle.js:71462:62 [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:71462:19) [<root>]
    at createResult (http://localhost:4200/vendor.bundle.js:71347:19) [<root>]
    at Zone.webpackJsonp.626.Zone.run (http://localhost:4200/polyfills.bundle.js:2122:43) [<root> => <root>]
    at http://localhost:4200/polyfills.bundle.js:2757:57 [<root>]
    at Zone.webpackJsonp.626.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2162:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2590:35) [<root>] Error: Template parse errors:

```

**Expected behavior**

I want to bind the image URL that comes from firebase, the problem is i nead to pass the image path like
## .images/someimage.png inside the input to get image preview i use the  **dropify.js lib** 

this example works
<input type="file" [(ngModel)]="image" name="image" class="dropify" data-default-file="../../../../assets/img/placeholders/200x200.png" data-height="300" />

But if i take the src with {{ imageUrl }} is not workin
<input type="file" [(ngModel)]="image" data-default-file="{{imageUrl}}" name="image" class="dropify" data-height="400" />

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

ES6

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
You need to bind to an attribute if you want to set an attribute: `[attr.data-default-file]="...."`

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by atlabiz** [comment]
thnx bro you save me
I came up with this ``` attr.data-default-file=" {{ imageUrl }}" ```
