### ISSUE TITLE
errors.ts:42 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'form' of undefined

### ISSUE THREAD

**Issue by balhelhas** [angular/angular#16350]
Hi, getting one error on my logging component can't solve it!

Here's the error:
![aaa](https://cloud.githubusercontent.com/assets/19665765/25443344/7a627db6-2a9f-11e7-813d-9253dae4ea13.PNG)

And i have the follow code:
![code](https://cloud.githubusercontent.com/assets/19665765/25443391/9e0d5fc4-2a9f-11e7-9ae3-04768315043d.PNG)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
