### ISSUE TITLE
TestBed.configureTestingModule should allow to use non exported directives from imported Modules

### ISSUE THREAD

**Issue by tbosch** [angular/angular#16351]
Usually, users create test components to test a component of a library that they wrote.
However, if the component under test is an internal one and shouldn't be used by other users, the corresponding NgModule won't export that directive. 
The only way for a test component to use such a component under test is to duplicate the NgModule definition to be able to add the test component to the `declarations`. This leads to hard to maintain code.

**Comment by tbosch** [comment]
This is a design bug.

**Comment by alxhub** [comment]
Standalone directives solve this particular use case.
