### ISSUE TITLE
loadChildren and UpgradeComponent

### ISSUE THREAD

**Issue by YaroslavLyzlov** [angular/angular#16369]
Hi! I use loadChildren with UpgradedComponent. But UpgradeComponent not see $injector
base (Angular) -> home-new (Angular) -> home (Upgrade from AngularJS)
![image](https://cloud.githubusercontent.com/assets/2513879/25479981/4c43cc16-2b60-11e7-81fa-3fdbe3efa9e7.png)

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by gkalpak** [comment]
@ericmartinezr is right. We need more info in order to be able to investigate (e.g. a minimal reproduction).
