### ISSUE TITLE
language-service: Member X is not callable

### ISSUE THREAD

**Issue by istiti** [angular/angular#16364]
```
[ x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
I'm using public method in template which is declared in an Abstract class and language-service telle me `Angular: Member onSelect is not callable`

Here is my code structure
### My component:
```
@Component({
  selector: 'autocomplete-homepad-divisions',
  templateUrl: './autocomplete-homepad-divisions.component.html',
})
export class AutocompleteHomepadDivisionsComponent extends AutocompleteAbstract { ... }
```
### And in this templateUrl I have:
```
...
 <li role="presentation"
        (click)="onSelect(o)"
        *ngFor="let o of options" 
...
```
**!!! Here this onSelect is not callable !!!** 

### My abstract class:
```
export abstract class AutocompleteAbstract {
  public onSelect:Function;
...
...
 registerOnSelect(fn:Function ) {
     this.onSelect = fn;
  }
}
```

### My directive where I set onSelect : 
```
@Directive({
  selector: 'input[tsabAutocomplete]',
 ...
})
export class AutocompleteDirective {
this.autocomplete.registerOnSelect((value)=> {
      ...
 });
}
```

How can I write signature of this public `onSelect:Function;` to be callable from template ? even if its in abstract class because my code works well just language-service tellin me this in loggs 

**Expected behavior**
Allow calling function from simple abstract class even if it isn't defined directly, don't want create abstract class component with decorator just like this simple abstract class

**Minimal reproduction of the problem with instructions**
don't know reproduce on plunker, i think can't extend abstract class in plunker 

**Versions & Environment:**
angular4.1, cli1.0.1, wind10, webstorm2017.1.2

 
* **Language:** [TypeScript 2.3.0]

* **Node = v7.7.2

**Comment by vicb** [comment]
It would help if you can attach a minimal project demonstrating the issue. Thanks.

**Comment by istiti** [comment]
bon ok, here you are https://drive.google.com/file/d/0BzKW4KaSm_QMS01IaXowSnY0UDA/view?usp=sharing

cc @vicb

**Comment by ddimaria** [comment]
This is more of a TypeScript question than an Angular one.  While you can use `onSelect:(o:any) => any;`, you're not really getting the benefit of the TypeScript type system.  If you know the parameter and return data types, it's best to use those in the declaration (e.g. `onSelect: (o: string) => void;`.  You would want to repeat that on the `registerOnSelect(fn:Function )` method signature as well.  I think this issue can be closed.
