### ISSUE TITLE
Input with Union type is undefined in Typescript 2.x.x

### ISSUE THREAD

**Issue by TheBlindSleuth** [angular/angular#16362]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Component inputs with a custom, union type throw an error and are not defined.
Eg: @Input() someModel: TestModel | undefined; 

Results in
`Error: (SystemJS) ReferenceError: test_model_model_1 is not defined`

An input without the alternative type (`@Input() someModel: TestModel`) works as expected

**Expected behavior**
TestModel would be defined.

**Minimal reproduction of the problem with instructions**
Steps to Reproduce:

See example:
https://plnkr.co/edit/I3w0quJT8ycdJ9jckqNx?p=preview

Go to TestComponent.
Uncomment the Input with unioned type -> Error

**What is the motivation / use case for changing the behavior?**
Fixing the erroneous behaviour.

**Please tell us about your environment:**
OSX Sierra
Chrome
NPM

* **Angular version:** 2.0.X
4.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Bug is present in Typescript 2.2.2

**Comment by alexzuza** [comment]
https://github.com/Microsoft/TypeScript/issues/15046

**Comment by vicb** [comment]
Seems like `@Input() someModel?: TestModel;` works for now.

Closing as not an Angular issue.
