### ISSUE TITLE
Remove @Hostlistener()

### ISSUE THREAD

**Issue by Smiranin** [angular/angular#16366]
How can I removed **@Hostlistener()** in Angular 2, like used **removeEventListener** in Native JS?  

**Example:** 
*I have many dropDown components in my page. When dropDown opened I want to add handler on document click event and to remove handler when dropDown closed.*

**Native JS:**

    function handler(){
      //do something
    }
    document.addEventListener('click', handler); // add handler
    document.removeEventListener('click', handler); // remove handler

**Angular 2:**

      @HostListener('document: click') onDocumentClick () {
        // do something
      }
    
      // How can I remove handler?

**Comment by vicb** [comment]
There is no way to remove a `@HostListener`.

Also it is probably not a good idea to have a `@HostListener` if you have many dropdown as you will have as many listeners as you have dropdowns.

**Comment by ericmartinezr** [comment]
Follow this discussion https://github.com/angular/angular/issues/7626

**Comment by Smiranin** [comment]
@vicb I think, as an alternative, to use Rx.Observable.fromEvent(document, 'click') in someService and dropDown will subscribe and unsubscribe to it.

**Comment by avbentem** [comment]
Just for future reference: using `Rx.Observable.fromEvent(...)` also keeps Angular from running change detection in the **parent** components, which would happen for, e.g., `@HostListener('window:keydown')`
