### ISSUE TITLE
Change Detection does not work when target es2017

### ISSUE THREAD

**Issue by zh99998** [angular/angular#16363]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

when target es2017, all async changes could not be detected

**Expected behavior**

change detection should works normally

**Minimal reproduction of the problem with instructions**

create a new Angular App by angular-cli
set target to `es2017` in `tsconfig.json`

```ts
export class AppComponent implements OnInit {
  title = 'app works!';

  async ngOnInit() {
    this.title = await Promise.resolve('async');
  }
}
```
**What is the motivation / use case for changing the behavior?**

my website will only target latest chrome and it support all needed es7 features, there is no need to downlevel es target.
 
**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:** Chrome 57

 
* **Language:** TypeScript 2.2.0

**Comment by trotyl** [comment]
Related to https://github.com/angular/zone.js/issues/740

**Comment by vicb** [comment]
This is a zone.js issue.
