### ISSUE TITLE
Removal from tsd.json doesn't clean up typings folder

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#1636]
reported by @juliemr

**Comment by alexeagle** [comment]
I think it's an issue in tsd, actually. Filed https://github.com/DefinitelyTyped/tsd/issues/151

**Comment by alexeagle** [comment]
Not sure yet how frequent this problem will be, so I'm going to prioritize other things. If it bites us again, we can do something like force-delete the typings every time. Or, maybe it will be fixed upstream before then.

**Comment by alexeagle** [comment]
FYI for the team:
fix is `rm -rf modules/angular2/typings` and then `tsd reinstall --config=modules/angular2/tsd.json`

**Comment by alexeagle** [comment]
We can fix this now that From https://github.com/DefinitelyTyped/tsd/issues/184#issuecomment-132449101 is available

**Comment by mhevery** [comment]
@alexeagle is this still an issue?

**Comment by alexeagle** [comment]
Yes, we are waiting on a tsd release so we can use the new flag. Let's keep this issue open to remind us to do that.
AT present, tsd is @0.6.3 which doesn't include this.

**Comment by alexeagle** [comment]
tsd 0.6.4 was released so I'll try to fix this now.
