### ISSUE TITLE
Marketing pages should take up the full width of the viewport

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16368]
After the recent change that constraint the content to a fixed width we end up with marketing pages looking like this:

<img width="1918" alt="screen shot 2017-04-27 at 10 30 50 am" src="https://cloud.githubusercontent.com/assets/216296/25476901/ee0a382a-2b3b-11e7-9075-c4871c60de78.png">

It would be better to keep marketing pages unconstrainted and centered, while all the non-markerting pages will have fixed-with.

**Comment by sjtrimble** [comment]
Dupe: https://github.com/angular/angular/issues/16337

Restating from original issue:
This should be removed once @wardbell's PR lands tagging the marketing pages differently.

The md-sidenav (that contains the max-width restriction) is above the section IDs we currently have available, so we'll need the aio-shell tags that encompass the entire page to apply custom styling to the marketing pages as intended.

**Comment by IgorMinar** [comment]
closing dupe
