### ISSUE TITLE
docs: router - improve docs on the router redirect

### ISSUE THREAD

**Issue by vicb** [angular/angular#16377]
Need to be documented:
- for absolute redirect, the router use the query parameters and the fragment from the `redirectTo` config,
- for relative redirect, the router use the query params and the fragment from the URL from which we are redirected.

Also it is possible to use positional parameters and query params in the redirected url:
- `{path: 'a/:aid/b/:bid', redirectTo: 'newa/:aid/newb/:bid'}`
- `{path: 'b/:id', redirectTo: '/absolute/:id?a=1&b=:b#f1'}`

See apply_redirect_spec.ts for details

**Comment by kapunahelewong** [comment]
Hi @vicb, has this issue been resolved to your satisfaction? If so, can we close this issue? If not, is there anything else I can do to help?

**Comment by jenniferfell** [comment]
It looks like this has been resolved. The following sections were added/updated and seem to address the issues here.

https://angular.io/guide/router#changing-heroes-to-superheroes
and
https://angular.io/guide/router#activated-route

Closing. If additional corrections or clarifications are required, please open a new issue. Thank you.
