### ISSUE TITLE
aio: need path info when code snippet source not found

### ISSUE THREAD

**Issue by wardbell** [angular/angular#16379]
When a code snippet is not found, dgeni _may report_ that fact to the console but authors overlook it or have lost that message by the time they discover the code snippet is missing.

The `CodeExampleComponent` and `CodePaneComponent` have no information about the intended snippet source and so they can only display a generic message along the lines of "no code snippet". Duh.

We need a diagnostic message that authors can see within the Doc Viewer itself so that authors can track down the problem.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Two possible solutions:

1) Pass the snippet source string as an attribute to the code element as in `<code-example src="path/to/nowhere"><code-example>` and `<code-pane src="path/to/nowhere"><code-pane>`. We could do that _for all snippets_ or maybe just when dgeni tried and failed to find it.

2) Display the source path in the body as in:
```
<code-example>
 Could not find code for "path/to/nowhere"
<code-example>```

Option (1) may be better because it  lets the embedded code component decide how to display missing code snippet guidance for both authors and users ... if the page w/ missing snippet happens to get published.

**Comment by petebacondarwin** [comment]
Let's do option 1. It is easy enough because the path is already that as a ... `path` attribute :-) but currently we strip it out. How about we just never strip it and leave it there?
