### ISSUE TITLE
NgComponentOutlet - @Input() ngComponentOutletProviders documented but not implemented

### ISSUE THREAD

**Issue by instantaphex** [angular/angular#16373]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The documentation for ngComponentOutlet as well as the comments at the top of the source code seem to indicate that one of the properties is ngComponentOutletProviders where it is possible to specify individual providers.

[https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_component_outlet.ts#L25-L26](url)

It appears from looking at the source code that this feature has not been implemented (I was banging my head against my desk trying to figure out why it didn't work until I read the angular source code).

**Expected behavior**
Documentation matches current functionality

**Minimal reproduction of the problem with instructions**
```
import { MyDynamicComponent } from './my-dynamic.component';

@Component({
    selector: 'parent-of-dynamic-component',
    template: '<ng-container *ngComponentOutlet="myDynamicComponent; providers: myProvider;"></ng-conatiner>'
})
export class ParentOfDynamicComponent {
    myDynamicComponent = MyDynamicComponent;
    myProvider = [ { provide: 'THING', useValue: { thing: 'thing' } ];
}
```

**What is the motivation / use case for changing the behavior?**
It causes a lot of confusion when the documentation states certain functionality that doesn't exist.  It would be a convenient feature to have, but it's easy to work around by creating an injector with your provider.

**Please tell us about your environment:**
N/A

* **Angular version:** 2.0.X
4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All
* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
This was never implemented. I have submitted a PR to fix the docs. Thanks for reporting.

**Comment by broodjetom** [comment]
Can this feature be added to Angular? I'm looking for a way to input data into components that are rendered by the ngComponentOutlet. Is there a other way to do this?

**Comment by instantaphex** [comment]
@broodjetom Although you can't specify a single provider for a dynamic component, you can specify an injector.  What I did to get around it was to an injector that had the provider I needed.

**Comment by broodjetom** [comment]
@instantaphex Can you show me how you did that? Because how does the dynamically loaded component what provider is its provider? Because I am having multiple components dynamically loaded but some can be duplicate but they have different type of data and thus provider.

**Comment by instantaphex** [comment]
```how does the dynamically loaded component what provider is its provider?```

It get's it from it's injector

So what I've done is something like this

```
@Component({
  selector: 'my-component',
  templateUrl: './my-template.html',
})
export class MyComponent {
    public newInjector: Injector;
    constructor(public injector: Injector) {}
    
    ngOnInit(): void {
      this.newInjector = ReflectiveInjector.resolveAndCreate(
        [ { provide: 'myNewProvider', useFactory () => ({ providedObject: 'test' }) } ],
        this.injector);
    }
```

Then when I'm instantiating my dynamic component, I give it this new injector that I created:

```<ng-container *ngComponentOutlet="myDynamicComponent; injector: newInjector;"></ng-conatiner>```

That way when my new component is instantiated, it is using an injector that inherits all the providers from my current injector and also has an added token which is ```'myNewProvider'``` and it provides the object ```{ providedObject: 'test' }```

**Comment by broodjetom** [comment]
@instantaphex 
Hey, I got the injector working, but how can I now get the object inside my components? Because I need to inject the provider in it somehow?

**Comment by instantaphex** [comment]
@broodjetom In my example I used a string token as the injection token.  If you aren't using a class (string token, opaque token, injection token, etc...) you need to use @Inject() from '@angular/core'

so in your dynamic component you need this:

```
import { Inject, Component } from '@angular/core';

@Component({
  selector: 'my-dynamic-component',
  templateUrl: './my-dynamic-component.html',
})
export class MyDynamicComponent {
  constructor(@Inject('myNewProvider') public providedOjbect: any) {}
}```

Then this will make it available to your dynamic component.

Also keep in mind, you can use a class in your provider like this:

```
import { MyClass } from './my-class.component';

@Component({
  selector: 'my-component',
  templateUrl: './my-template.html',
})
export class MyComponent implements OnInit {
    public newInjector: Injector;
    constructor(public injector: Injector) {}
    
    ngOnInit(): void {
      this.newInjector = ReflectiveInjector.resolveAndCreate(
        [ { provide: MyClass, useFactory () => ({ providedObject: 'test' }) } ],
        this.injector);
    }
}```

And then in your dynamic component you don't need to use ```@Inject()```, you just import the class and use it in your constructor like you would when you are injecting any other dependency.

**Comment by Zaliro** [comment]
@instantaphex You're god.

**Comment by binDongKim** [comment]
@instantaphex Pure gold! Thanks a lot!
