### ISSUE TITLE
check if URLSearchParams is know

### ISSUE THREAD

**Issue by ss-bb** [angular/angular#16378]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you use URLSearchParams in your code without importing it, you request will go without parameter ans you won't understand why

**Expected behavior**
make an error explaining URLSearchParams is undefined

**Minimal reproduction of the problem with instructions**
just put a let urlparam: URLSearchParams = new URLSearchParams(); and use it
(without the import at the top) , you will have no error message and 0 parameter going in your get request.

**What is the motivation / use case for changing the behavior?**
spend 2 hours debuging for a forget dependencies!
I do agree it's a distracted misstake, but still would have like a warning saying 'what is URlSearchParam ?'.

**Please tell us about your environment:**
ubuntu 16

* **Angular version:** 4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v6.10.2

**Comment by trotyl** [comment]
Because `URLSearchParams` is also the name of a property of [[global]] object defined in HTML standard, this problem also applies to `Request`, `Response` and `Headers` classes.

This is a known issue and (originally) should be fixed by https://github.com/angular/angular/pull/14334 , but that was suspended for some reason.

**Comment by antonovicha** [comment]
Just encounter the very same issue. And also spend few hours finding out the reason.
URLSearchParams is a name of 2 different types and TS compiler give no error (why?).

**Comment by trotyl** [comment]
Allowing same name in different lexical scope is natural in all languages, there shouldn't be any error since there is no ambiguity.

But Angular indeed has a bad naming for it.

**Comment by antonovicha** [comment]
@trotyl RequestOptionsArgs have following params field definition:
```params?: string | URLSearchParams | { [key: string]: any | any[]; } | null;```
where ```URLSearchParams``` is Angular type.

However TS compiler does not give an error when object with params set as window.URLSearchParams cast to RequestOptionsArgs:
```let r = { params: new window.URLSearchParams() } as RequestOptionsArgs;```

**Comment by trotyl** [comment]
`{ [key: string]: any | any[]; }` is almost same as `object`, everything is allowed except primitive types.

**Comment by trotyl** [comment]
Can be closed as `@angular/http` is already deprecated and this is just for better error message.
