### ISSUE TITLE
Referring a static attribute of a class in a const variable.

### ISSUE THREAD

**Issue by luisbirchenz** [angular/angular#16372]
Hi everyone,

                   I provided all the details requested here  
[issue](https://github.com/angular/angular/issues/16321#issuecomment-297150947)

A demo was requested to reproduce the error, I created the example asked for and I put the link to get the demo from github. But due to the ticket was closed I have never received the feedback.

Can someone give me an explanation about that? The demo included there is going to help in order to reproduce the error.

Thanks in advance,

Luis.

**Comment by matsko** [comment]
Please follow the issue guidelines when creating an issue. It's hard to understand what you're asking for here.

**Comment by luisbirchenz** [comment]
I followed the issue guidelines the first time and I did not receive any help.

Anyway, forget it.

Regards.

**Comment by gkalpak** [comment]
#16321 has enough info indeed (e.g. [here][1]), but it was added after the issue was closed, so that's probably why it didn't get much attention. I reopened #16321.

[1]: https://github.com/angular/angular/issues/16321#issuecomment-297439174
