### ISSUE TITLE
Angular 4 / Angular-cli: Date polyfill with Internationalization API does not work

### ISSUE THREAD

**Issue by TomTheBomb94** [angular/angular#16384]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using polyfill to use date pipes with edge it does not work. As stated in the docs on https://angular.io/docs/ts/latest/guide/pipes.html one simply needs to add a script to the index.html:

`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.de"></script>`

or import the Internationalization API via `npm run install intl --save` and then edit polyfills.ts with e.g. 
```
import 'intl';
import 'intl/locale-data/jsonp/de.js';
```
but broken behavior in edge (Version 40.15063.0.0) still persists.

**Expected behavior**
date pipe should work with polyfill in edge and safari.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I need to display time in a calendar.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
@angular/cli: 1.0.0
node: 6.10.1
os: win32 x64
@angular/animations: 4.0.2
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Edge (Version 40.15063.0.0) and as stated in the docs there might be also a problem with safari.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript Version 2.2.2
* **Node (for AoT issues):** `node --version` =

**Comment by TomTheBomb94** [comment]
![example 1](https://cloud.githubusercontent.com/assets/28112764/25499111/b8aa17fa-2b8a-11e7-8681-8f522b3949c9.png)

**Comment by TomTheBomb94** [comment]
![example 2](https://cloud.githubusercontent.com/assets/28112764/25499117/bd7498dc-2b8a-11e7-8b8b-eaadddb1b64e.png)

**Comment by TomTheBomb94** [comment]
I'm sorry it was my fault, I guess I used wrong format. As I did not understand/ found the correct format in the Angular documentation for german time,  I tried myself using `| date: 'HH:mm'` caused this issue. I needed to change it to `H:mm` and now it works. Could you close / reject this issue ?

**Comment by TomTheBomb94** [comment]
Sorry this was my fault. Installing the polyfill worked, I just did not see as I used wrong format. I thought I could use date Pipe with free formatting like ` | date: 'HH:mm'` for german time. But this worked for some reason only in chrome... But with correct locale set (in my case de) one can use angulars 'shortTime'. Could you please reject this issue or close it :). But might be valuable to mention this in documentation though.

**Comment by vicb** [comment]
We plan to rework the i18n pipes (date, number, ...).

/cc @ocombe @pkozlowski-opensource
