### ISSUE TITLE
Angular2 property binding not working with foundation modal

### ISSUE THREAD

**Issue by sanjeev2315** [angular/angular#16383]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In my application, I have a foundation reveal, which gets called from a button of the html template of a component and show data in textboxes. It is working fine when I load the application. Once I go to another tab and comes back then my page loads the data correctly but reveal modal not able to bind to properties of component and no data displayed.

**Expected behavior**
I am doing jQuery(document).foundation() in ngviewAfterInit() in each component. If I do {{component field}}, it prints it in the modal but`` <input name="abc" type="text" ([ngModel]) ="component field" > not showing the value

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.5

* **Browser:** [all  ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` = 6.9.5

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by hollandz** [comment]
Did you ever find a workaround for this?
