### ISSUE TITLE
[Bug] Cannot find primary outlet to load 'ScheduleComponent'

### ISSUE THREAD

**Issue by luchillo17** [angular/angular#16381]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
The app navigates back as expected, but shows this error in console:
![image](https://cloud.githubusercontent.com/assets/9698639/25496268/e1fef6f6-2b45-11e7-9d4f-4d8ef6ef8d95.png)

**Expected behavior**
No error log. Think the issue is because i'm calling `this.location.back()` in a component instantiated inside an `ngComponentOutlet` like:
```html
<ng-container
  *ngComponentOutlet="type && type.component"
></ng-container>
```

**Minimal reproduction of the problem with instructions**
Have the project in: https://github.com/luchillo17/Electron-Webpack/tree/feature/task-list
Current specific commit: 26a7c4f13aad11272c8ecb585ee29ba35032d548
After it opens paste this url: http://localhost:8080/#/task;method=NEW;type=%7B%22name%22%3A%22Tarea%20tipo%20log%22%2C%22type%22%3A%22LogTaskComponent%22%7D;id=undefined

Then at last click the red button to trigger the back navigation, the error should show in console.

**Please tell us about your environment:**

Mac OSX Sierra,
VSCode,
Npm.

* **Angular version:** 4.0.2

* **Browser:** [all | Chrome 57 ]

 
* **Language:** [all | TypeScript 2.2.2]

**Comment by MoxxNull** [comment]
I get the same errors when using browser's Back-Button. Routing works just fine, but prints out said error-message. 

Using  angular-cli 1.0.2 / Angular 4.1.0

**Comment by luchillo17** [comment]
@MoxxNull You using the `ngComponentOutlet` as well?

**Comment by MoxxNull** [comment]
Sorry, should have provided some more detail here :)  .. No, I have a plain <router-outlet></router-outlet>.  I just realized the error today in my medium-sized project, but found no information on SO & Co. Maybe I can investigate it a little further this weekend.

**Comment by jmarlow4** [comment]
Still no fix for this?

**Comment by luchillo17** [comment]
I think i just worked around it by setting the route directly instead of triggering a back navigation:
```ts
this.router.navigate(['/']);
```

**Comment by jmarlow4** [comment]
For some reason the problem just went away for me. I still experience it from time to time but it has no effects on the UI.

**Comment by luchillo17** [comment]
If it comes and goes maybe it's a race condition.

**Comment by jasonaden** [comment]
Closing as this was mentioned to be fixed. If this comes up and is reproducible, please create a new issue.
