### ISSUE TITLE
Http auto content-type detection based on content doesn't work

### ISSUE THREAD

**Issue by midnightstarr** [angular/angular#16393]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I post like this:
```
var payload = new URLSearchParams();
payload.append('username', username);
payload.append('password', password);
this.http.post("/api/account/login", payload).subscribe(....
```
And it results in this:
![image](https://cloud.githubusercontent.com/assets/3116731/25507987/88c8ad42-2baf-11e7-9386-88f89bbbd621.png)

**Expected behavior**

It should automatically change content-type to application/www-form-urlencoded

**Minimal reproduction of the problem with instructions**

Just use http client with URLSearchParams and you will see.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OS: Windows 8.1
IDE: no IDE(Visual studio code)
Package manager: npm
HTTP server: Kestrel

* **Angular version:** 4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 57.0.2987.133 (64-bit) 
Didn't test it all.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2

* **Node (for AoT issues):** `node --version` =

**Comment by midnightstarr** [comment]
Nevermind. You can close it. The cause of it:

I didn't import URLSearchParams from @angular/http and it took it probably from some other place.

**Comment by alxhub** [comment]
You could consider it a separate bug that `@angular/http` shadows `URLSearchParams` from the browser. `HttpClient` won't do this, and will support both.
