### ISSUE TITLE
Recommendation: When you want to provide a development, the component can preview the view

### ISSUE THREAD

**Issue by lanmingle** [angular/angular#16397]
建议：希望提供开发时组件可预览视图。

Google ：

Recommendation: When you want to provide a development, the component can preview the view

**Comment by trotyl** [comment]
**Better translation here.**

Suggestion: Provide a real-time preview mechanism for component development.

**Comment by mlc-mlapis** [comment]
... do you think it serious?

**Comment by vicb** [comment]
I do not understand the request.

You can re-open a new one and provide information as requested in the templates. Thanks.
