### ISSUE TITLE
Routing to named outlets doesn't work with non-empty paths

### ISSUE THREAD

**Issue by ptrts** [angular/angular#16406]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In case of a named router-outlet, routing works only with empty paths. 
This is written to the browser console:
Error: Cannot match any routes. URL Segment: 'a'

**Expected behavior**

Routing should create components whether the outlet is named or not. 

**Minimal reproduction of the problem with instructions**

Here's a code for a simple routing app. 
It's got three paths (/, /a, /b) and a button for each. 
The paths are routed to components. 
The code has got several Routes configurations. 
Some of them are working (navigating to a know path renders a component), others are bugged. 

```typescript
import {Component, NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {RouterModule, Routes} from '@angular/router';

@Component({
  selector: 'our-main',
  template: `
    <a href="">Navigate to /</a>
    <a href="a">Navigate to /a</a>
    <a href="b">Navigate to /b</a>
    <div>router-outlet name='the-out':</div>
    <router-outlet name="the-out"></router-outlet>
    <div>router-outlet, name='':</div>
    <router-outlet></router-outlet>
  `,
  styles: ['a { display: block; }']
})
class MainComponent {}

@Component({ selector: 'our-default', template: '<h1>Default</h1>' })
class DefaultComponent {}

@Component({ selector: 'our-a', template: '<h1>A</h1>', })
class AComponent {}

@Component({ selector: 'our-b', template: '<h1>B</h1>' })
class BComponent {}

const ROUTES_OK_1: Routes = [
  { path: '', component: DefaultComponent, outlet: 'the-out', pathMatch: 'full'},
  { path: 'a', component: AComponent, outlet: ''},
  { path: 'b', component: BComponent, outlet: ''}
];

const ROUTES_OK_2: Routes = [
  { path: '', component: DefaultComponent, outlet: 'the-out'},
  { path: 'a', component: AComponent, outlet: ''},
  { path: 'b', component: BComponent, outlet: ''}
];

const ROUTES_OK_3: Routes = [
  { path: '', component: DefaultComponent, outlet: '', pathMatch: 'full'},
  { path: 'a', component: AComponent, outlet: ''},
  { path: 'b', component: BComponent, outlet: ''}
];

const ROUTES_BUG_1: Routes = [
  { path: '', component: DefaultComponent, outlet: 'the-out', pathMatch: 'full'},
  { path: 'a', component: AComponent, outlet: 'the-out'},
  { path: 'b', component: BComponent, outlet: 'the-out'}
];

const ROUTES_BUG_2: Routes = [
  { path: '', component: DefaultComponent, outlet: '', pathMatch: 'full'},
  { path: 'a', component: AComponent, outlet: 'the-out'},
  { path: 'b', component: BComponent, outlet: 'the-out'}
];

@NgModule({
  imports: [BrowserModule, RouterModule.forRoot(ROUTES_BUG_1)],
  declarations: [MainComponent, DefaultComponent, AComponent, BComponent],
  bootstrap: [MainComponent]
})
export class AppModule {}
```
**What is the motivation / use case for changing the behavior?**

I don't know. I'm just learning. I can't even tell why there're named router-outlets at all. The developers should know better. 
**Please tell us about your environment:**
Linux Mint 17.3
IDE IntellijIDEA 2017.1.2
package manager yarn
HTTP server lite-server
* **Angular version:** 4.0.0
* **Browser:** Firefox 53
* **Language:** TypeScript 2.1.0
* **Node (for AoT issues):** `node --version` =   7.4.0

**Comment by vicb** [comment]
Please add a plunker that demonstrate the issue

**Comment by ptrts** [comment]
@vicb I didn't manage to make the plunker demo work, sorry, but you could use the commit that's auto attached to your message

**Comment by kamranahmedse** [comment]
I have the same issue, component doesn't get added to the outlet for non-empty paths i.e. below does not work

```
{
    path: 'some-path',
    component: SidebarComponent,
    outlet: 'sidebar'
}
```
But it does work for the non-empty paths. For now I have been using the below stated _hack_ to achieve it, since it seems to be working when the path is empty.
```
{
    path: 'some-path',
    children: [
        {
            path: '',
            component: SidebarComponent,
            outlet: 'sidebar'
        }        
    ]
}
```
I am not sure if it is by design or not as I am not able to find anything regarding this in the documentation. Would love a word from the core team? /@vicb

PS, I have it in one of the feature modules that is lazy loaded and haven't tried it in the parent module so I am not sure about the behavior in parent module.

**Comment by webmatrixxxl** [comment]
Same problem with angular 4.3.6

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by ptrts** [comment]
@jasonaden The reproduction has already been posted:
https://github.com/ptrts/angular-test/commit/0701e0d1b58a386a100806528b3a498207b9ed10

**Comment by greggbjensen** [comment]
I am running into the same issue with Angular 4.4.3.  I was able to do the workaround @kamranahmedse suggested.  However, this seems like a pretty key bug for named routes.  This is the first time I used the feature, and I immediately found the issue.  I appreciate any help on getting this one addressed.

**Comment by CharlieGreenman** [comment]
I should mention using @kamranahmedse 's solution does not work for me, as not using lazy loaded modules. For non lazy loaded modules, I am running across the issue: `Error: Cannot activate an already activated outlet`.

@jasonaden my apologies, I am not 100% familiar with process. Would it be possible to re-open this issue, or would it be preferable that I go ahead and create a new one, with a proper example? Thank you.

**Comment by jasonaden** [comment]
@CharlieGreenman I ended up back on this issue from a new issue #21490. Are these the same?

Generally we don't see issues after they have been closed. So the best thing is to just open a new issue, ideally addressing whatever reason the earlier one was closed. In this case, it would be adding a link to the reproduction in the PR description.

**Comment by tawalters61** [comment]
I am running into the exact same issue. Is this resolved?

**Comment by alexus85** [comment]
in my case, the component does not get added added whenever I try assign it to a specific router-outlet name.

**Comment by CharlieGreenman** [comment]
@jasonaden my apologies for the late response. Will look into and report back.

**Comment by mdelorimier** [comment]
Hello, i am seeing the same issue in Angular 5.2.5. Has this been resolved?
I have tryed @kamranahmedse's hack and it does not seem to work for me.

**Comment by mo-norant** [comment]
Hi, in the newest angular version is this bug still existing. Shoutout to the angular team?

**Comment by mo-norant** [comment]
@kamranahmedse workaround worked for me

**Comment by UladzislauCharneny** [comment]
workaround that worked for me:

didn't work before:
```
{
        path: 'some/path',
        component: MainComponent,
        children: [
          {
            path: '',
            component: SideComponent,
            outlet: 'outlet',
          },
        ],
      },
```

work after:
```
{
        path: 'some/path',
        children: [
          {
            path: '',
            component: SideComponent,
            outlet: 'outlet',
          },
          {
            path: '',
            component: MainComonent,
          }
        ],
      },
```
