### ISSUE TITLE
[Forms-Template-driven] When switching values from 2 inputs, template render the form finely, but when submitting the form, the values are binded to the orignial input name

### ISSUE THREAD

**Issue by Rebolon** [angular/angular#16400]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a form (template-driven) with 2 fields and a button that switch the value of the 2 fields.
Field's name are data[0] and data[1] with values france and usa.
When i click the switch button, the template render usa in data[0] and france in data[1] as expected
And when i submit the form i have data[0]=france and data[1]=usa

**Expected behavior**
I expect that the form has the same values as the template render so data[0]=usa and data[1]=france

**Minimal reproduction of the problem with instructions**
http://plnkr.co/PUqr4UF8V50594kyDL7I

**What is the motivation / use case for changing the behavior?**
I don't understand why the template render everything as expected but form seems not binded as expected to data

**Please tell us about your environment:**
Windows 7, WebStorms 2017, npm, bitbucket, ng serve in dev mode

* **Angular version:** 2.0.X
tested on 4.0.1 and 4.1

* **Browser:** 
all
 
* **Language:** 
es6

* **Node (for AoT issues):** `node --version` =

**Comment by alexzuza** [comment]
Try using `trackBy`

```
*ngFor="let country of countries; let i = index; trackBy: trackByFn"

trackByFn(i: number) {
  return i;
}
```
http://plnkr.co/edit/mRiYG7fJcmsnSm0Bfn5g?p=preview

**Comment by Rebolon** [comment]
@alexzuza thx it works. But i find this really strange : a callback that just return the parameter sent by the loop... Any reason why it's dnot done by default by the framework ?
In this case i have the feeling to wrote useless code.
