### ISSUE TITLE
Testing Observables fails?

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular#16419]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When testing a component with an Observable based mocked Service, the observables are returned as undefined.

**Expected behavior**
The returned Observables should behave in the test in the same way as they do in normal operation.

**Minimal reproduction of the problem with instructions**
`git clone https://github.com/georgeedwards/ng-demo`
`yarn install`
`ng test` - Observe the failed test
`ng serve` - Observe the successful running of the app

**What is the motivation / use case for changing the behavior?**
Allow the mocking of observable based services when testing components

**Please tell us about your environment:**
Windows 10 x64, VS Code, Yarn

* **Angular version:** 4.1.0

* **Language:** [all]

* **Node (for AoT issues):** `node --version` =  6.10.1

**Comment by trotyl** [comment]
```typescript
spyOn(mockTest, 'getComments');
```
Change it to:
```typescript
spyOn(mockTest, 'getComments').and.callThrough();
```
If you spy on something, you need to specify the behavior, see https://jasmine.github.io/api/edge/Spy_and.html for more information.

BTW, here is not for support questions.
