### ISSUE TITLE
Plunkr live example on Angular documentation not working

### ISSUE THREAD

**Issue by waynechaw** [angular/angular#16424]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
live plunkr example on this page is not loading at all:
https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html

**Expected behavior**
Live example should work
**Minimal reproduction of the problem with instructions**
Go to https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html and click on live example

**What is the motivation / use case for changing the behavior?**
To learn Angular2

**Comment by gkalpak** [comment]
I opened the live example and it works fine. Maybe it was some temporary network/plnkr issue.
