### ISSUE TITLE
internet explorer 11 Authoraization Error in Angular 4  Ask

### ISSUE THREAD

**Issue by rajasekharreddyjava** [angular/angular#16435]
I have created a pdf viewer component in angular 4 and I am getting authorization error while opening the doc. here is the HTML templet and I am also using the DomSanitizer to bypassSecurityTrustResourceUrl.
`<object *ngIf="url" [data]="url" type="application/pdf" style="height: 781px"> </object>`
I also enabled the protected mode in Adobe pdf reader. It is working in all the remaining browsers. 
thanks in advance.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
