### ISSUE TITLE
navigate bug

### ISSUE THREAD

**Issue by repertory** [angular/angular#16432]
I have a project structure as follows: (The routing address is the same as the folder structure)
```
.
├── app
│   ├── admin
│   │   ├── admin-children.module.ts
│   │   ├── admin.component.css
│   │   ├── admin.component.html
│   │   ├── admin.component.spec.ts
│   │   ├── admin.component.ts
│   │   ├── admin.module.ts
│   │   ├── admin-routing.module.ts
│   │   └── index
│   │       ├── index.component.css
│   │       ├── index.component.html
│   │       ├── index.component.spec.ts
│   │       ├── index.component.ts
│   │       ├── index.module.ts
│   │       └── index-routing.module.ts
│   ├── app-children.module.ts
│   ├── app.component.css
│   ├── app.component.html
│   ├── app.component.spec.ts
│   ├── app.component.ts
│   ├── app.module.ts
│   ├── app-parse.module.ts
│   ├── app-routing.module.ts
│   ├── forget
│   │   ├── forget.component.css
│   │   ├── forget.component.html
│   │   ├── forget.component.spec.ts
│   │   ├── forget.component.ts
│   │   ├── forget.module.ts
│   │   └── forget-routing.module.ts
│   ├── login
│   │   ├── login.component.css
│   │   ├── login.component.html
│   │   ├── login.component.spec.ts
│   │   ├── login.component.ts
│   │   ├── login.module.ts
│   │   └── login-routing.module.ts
│   ├── register
│   │   ├── register.component.css
│   │   ├── register.component.html
│   │   ├── register.component.spec.ts
│   │   ├── register.component.ts
│   │   ├── register.module.ts
│   │   └── register-routing.module.ts
│   └── ...
├── ...
```
I call `this.router.navigateByUrl ('/admin')` in `app/login/login.component.ts`; the following problems arise

/login -> /admin , admin no

/admin -> /login -> /admin , admin yes

**Comment by Toxicable** [comment]
Can you please provide a minimal reproduction?

**Comment by repertory** [comment]
https://github.com/repertory/angular-admin/blob/master/src/app/login/login.component.ts

**Comment by Toxicable** [comment]
@repertory Im sorry I think you misunderstand what I mean by minimal reproduction.
A minimal reproduction is where you reproduce the error in isolation, generally the best way is to do it with a plunkr, here is a template you can use https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 .If the error is AOT related then I would suggest making a Repo for the issue with the CLI.
If you are unable to do this then most of the time your issue will be unactionable.

**Comment by repertory** [comment]
@Toxicable Thank you, I think I found the reason, when remove `material2`, the page is ok now

**Comment by repertory** [comment]
demo: http://angular.demo.wangdong.io
> username `wangdong` and  password `wangdong`

code: https://github.com/repertory/angular-admin

plan1: click admin
plan2: click login

**Comment by vicb** [comment]
Please provide a *minimal* project. We don't have time to debug your full app. Thanks.

**Comment by repertory** [comment]
@vicb  https://plnkr.co/edit/0yfe3kzofrzERX29ekP0?p=preview  systemjs mode is ok ， but angular-cli is not ok

loadChildren mode: MaterialModule event is not work

**Comment by jasonaden** [comment]
Closing as OP mentioned the page is okay now.
