### ISSUE TITLE
aio: collect up all declarations of an NgModule

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16447]
We can then list all the declarations on that ngModule's doc page.

There is already a `@ngModule` tag that should be applied to API elements that are declared on an NgModule. Via #16446, we already show this information on API docs pages for the declared item. This issue is suggesting that we should also create a list on the module's page that links back to all the declared items.

**Comment by jenniferfell** [comment]
@petebacondarwin @jbogarthyde Is this handled by our recent and in-progress API changes?

**Comment by jbogarthyde** [comment]
I believe so.

**Comment by petebacondarwin** [comment]
Resolved by https://github.com/angular/angular/pull/25734
