### ISSUE TITLE
feat(aio): GaService should only send a tracking event if the path changes, net of # and ?

### ISSUE THREAD

**Issue by wardbell** [angular/angular#16442]
gkalpak: If necessary, also test that `LocationService` forwards the necessary "events" (see https://github.com/angular/angular/pull/15570#discussion_r108603082).

wardbell:  I had arbitrarily decided to GA track in-page #frag clicks too and have no instructions to stop doing so. 

Added PR #16441 which states this explicitly and confirms with a test.  All we have to do is decide.

**Comment by petebacondarwin** [comment]
We are now only sending a message to Google Analytics if the path changes, and not the hash or query.
