### ISSUE TITLE
Build fails for @angular/forms with Typescript 2.3 Strict flag

### ISSUE THREAD

**Issue by tkhemani** [angular/angular#16454]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

On compiling Angular CLI App with "strict": true, flag in tsconfig.json and using ts 2.3. ng server fails with below error: 

    ERROR in node_modules/@angular/forms/src/model.d.ts (544,19): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'emitEvent' and no string index signature.

    ERROR in node_modules/@angular/forms/src/model.d.ts (571,9): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'onlySelf' and no string index signature.

    ERROR in node_modules/@angular/forms/src/model.d.ts (571,19): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'emitEvent' and no string index signature.

    ERROR in node_modules/@angular/forms/src/model.d.ts (607,25): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'onlySelf' and no string index signature.

    ERROR in node_modules/@angular/forms/src/model.d.ts (607,35): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'emitEvent' and no string index signature.

    ERROR in node_modules/@angular/forms/src/model.d.ts (711,29): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'onlySelf' and no string index signature.

    ERROR in node_modules/@angular/forms/src/model.d.ts (711,39): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'emitEvent' and no string index signature.

    ERROR in node_modules/@angular/forms/src/model.d.ts (735,31): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'onlySelf' and no string index signature.

    ERROR in node_modules/@angular/forms/src/model.d.ts (735,41): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'emitEvent' and no string index signature.

    ERROR in node_modules/@angular/forms/src/model.d.ts (770,25): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'onlySelf' and no string index signature.

    ERROR in node_modules/@angular/forms/src/model.d.ts (770,35): Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean |
    undefined; } | undefined' has no property 'emitEvent' and no string index signature.

**Expected behavior**

Build should be successful

**Minimal reproduction of the problem with instructions**

* Install latest angular CLI
* Update to latest Typescript
* `"strict": true`, flag in tsconfig.json
* Build using : `ng serve`

**What is the motivation / use case for changing the behavior?**

* To be able to enable strict checking with latest Typescript

**Please tell us about your environment:**

* **Angular version:** 4.1

* **Browser:** all 

 
* **Language:** TypeScript 2.3

* **Node (for AoT issues):** `node --version` =  7.8

**Comment by devoto13** [comment]
Duplicate #16357.

**Comment by matsko** [comment]
Closing since this is apart of the framework now.
