### ISSUE TITLE
Getters don't work with Creating objects in arrays

### ISSUE THREAD

**Issue by MahmoudElias** [angular/angular#16453]
I defined the following class for Employee:
`  export class Employee {
    id: number;
    firstName: string;
    lastName: string;
    get fullName():string {
        return this.firstName + ' ' + this.lastName;
    }
    set fullName (name:string) {
        let words = name.toString().split(' ');
        this.firstName = words[0] || '';
        this.lastName = words[1] || '';
    }
  }
`
Then, I created an array of Employee:
`  export const EMPLOYEES: Employee[] = [
    { id: 101, firstName: 'John', lastName: 'Smith' },
    { id: 102, firstName: 'William', lastName: 'Carry' }
  ];
`

I created a component that uses the previous constant:
`  employees : Employee[] = EMPLOYEES;`

When calling the fullName property, it gives me undefined value. But, when I push a new entry to the array employees like the following:
`  let e = new Employee();
      e.id = 103;
      e.firstName = 'Sami';
      e.lastName = 'Haddad';
      this.employees.push(e);
`

Now, calling the fullName property works very well.

Can you please tell me what's going on?

**Comment by fknop** [comment]
You're probably confusing classes and object litterals. In your initial array, these are object littterals. Thus they are not instances of Employee.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by MahmoudElias** [comment]
Sorry and thank you
