### ISSUE TITLE
Language Service is not marking private methods as errors in template files

### ISSUE THREAD

**Issue by Cammisuli** [angular/angular#16451]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Take a look at the screen shot below:
![image](https://cloud.githubusercontent.com/assets/4332460/25569284/6f6e9868-2de2-11e7-8eee-e78a676f6323.png)

Using a private method in a template does not show it as being an error. I thought this was a problem with the VSCode Angular Language extension, but the problem also exists with Webstorm.

**Expected behavior**
I expect that private methods used in templates should be an error and underlined in the template. Without this basic support, we would have to rebuild the whole application in AoT just to see the error. 

**Minimal reproduction of the problem with instructions**
Here's a repo that just has this error showing at it's most basic form:
https://github.com/Cammisuli/ng-language-server-errors

**What is the motivation / use case for changing the behavior?**
We don't want to build the whole application (2000+ modules, which takes about 4 minutes to build...) just to see these errors that should be present while we are building components.

**Please tell us about your environment:**
Operating system: Windows 10, MacOS 10.12.4
VSCode: 1.11 / Angular Extension - 0.13.0
Webstorm: 2017.1.2

* **Angular version:** 4.1
 
* **Language:** Typescript 

* **Node (for AoT issues):** `node --version` =   7.5.0

**Comment by mkoczka** [comment]
I pushed the PR(#19740) that fixes this issue.

**Comment by kyliau** [comment]
This has already been fixed some time ago, see test case here https://github.com/angular/angular/blob/1d5ca55aab6d49eecbb19e84739f7178b52a64ed/packages/language-service/test/diagnostics_spec.ts#L296-L300
