### ISSUE TITLE
Observable 'catch' not giving me the JSON response sent from server

### ISSUE THREAD

**Issue by lansana** [angular/angular#16455]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I get a `ProgressEvent` when converting the response with `response.json()` in the `catch` of an observable after making an HTTP request that returns a non-200 status code.

**Expected behavior**
I should get the response JSON sent back from the server, in the same way that I get it when doing `response.json()` in a `map` on a 200 status code response.

**Minimal reproduction of the problem with instructions**
http://stackoverflow.com/questions/43705854/angular2-rxjs-catch-on-observable-giving-progressevent-instead-of-json-from-r

**What is the motivation / use case for changing the behavior?**
I want to handle 401 status codes by doing some other things, but I cannot even get the status code because it's always 0 since my response is never received in that `catch` block.

**Please tell us about your environment:**
Using `ng serve`, or a web server written in Go. 

* **Angular version:** 2.0.X
Angular version 4.0.2

* **Browser:**
Chrome 57 browser on a Mac
 
* **Language:**
TypeScript

* **Node (for AoT issues):** 
v7.5.0

**Comment by lansana** [comment]
Solved this... apparently it was an issue with my middleware. In the event of an authorized request, the CORS did not properly set the `Access-Control-Allow-Origin` header.

Even with this being the case, I could still see the error JSON response in the network tab coming in from the server, so why does the `catch` not show the response, but instead shows `ProgressEvent`? 

Is this a bug or the intended functionality?

**Comment by matsko** [comment]
@alxhub please advise.

**Comment by alxhub** [comment]
@lansana, in the event of a CORS failure, nothing about the response is accessible to the client, including the response body (DevTools can show it, of course, but the page doesn't have access). In that case, `Http` will return the actual error from the browser (in this case apparently `ProgressEvent` - there are reports of this being the behavior in e.g. Chrome).

So this is working as intended, sorry.
