### ISSUE TITLE
aio: search result duplicate "AUTO_STYLE"

### ISSUE THREAD

**Issue by wardbell** [angular/angular#16464]
Search for “AUTO_STYLE” returns two API entries in the search results. Both link to the same API page.

Searching for that in the API search revealed  two entries as well: (1) in core, which is deprecated and (2) in animations. 

Curiously BOTH pages present the SAME content … the content for the one in animations. The info about the deprecated  `AUTO_STYLE` in core doesn’t appear. The browser address bar shows the two different paths to that content.

There is an API filter for deprecated so clearly we intend to show deprecated objects in the API search. The bug there is that we show the non-deprecated animations content in the deprecated core link.

This may be **a symptom of a deeper problem with API pages** that have the same title. It is unusual ... perhaps bad ... but not impossible for two different modules to have an object with the same name (that's what is happening here with `AUTO_STYLE`).  If that is OK, then the content should be different. I think a bug is causing the last-generated content to be assigned to all links with the same title.

<hr>

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Comment by petebacondarwin** [comment]
API docs are keyed of their "id", which is more than their name (it includes the ES6 module from which they were exported). So I don't think there is a bug there.

If two exports point to the same original symbol then they will indeed display the same content. This can happen if a thing is re-exported more than once, which is probably what is happening in the case of `AUTO_STYLE`?

**Comment by petebacondarwin** [comment]
Actually, in this case AUTO_STYLE really is two different code entities and has two different docs. It is just that neither has any `description` so the docs look the same.

**Comment by petebacondarwin** [comment]
I think once the API docs templates are better it will be easier to distinguish, but perhaps we need to make the search titles more informative. For instance, if an item is deprecated it should be styled differently (or have "deprecated" appended to its title) in the search results?

**Comment by petebacondarwin** [comment]
The documents are now clearly different and so this is no longer a valid issue.

See https://aio-staging.firebaseapp.com/api/core/AUTO_STYLE and https://aio-staging.firebaseapp.com/api/animations/AUTO_STYLE
