### ISSUE TITLE
PhantomJS 2 not working

### ISSUE THREAD

**Issue by armorik83** [angular/angular#1646]
Hi.

Maybe because of the vicinity of `src/facade/lang.js`, to work on the browser, but it does not work with PhantomJS 2. 

```js
// static replace(s, from, replace) {
//   assert.argumentTypes(s, assert.type.string, from, assert.type.string, replace, assert.type.string);
//   return assert.returnType((s.replace(from, replace)), assert.type.string);
// }
```

For some reason it was run when I comment out the `es6/dev/src/facade/lang.es6#L66-69`. I have no idea! :sob:  Thanks.

**Comment by alexeagle** [comment]
Sorry, I need some more context - what is the error? How to reproduce?

**Comment by armorik83** [comment]
My report was too simple.
I will provide a reproducible way, please wait.

**Comment by armorik83** [comment]
I've tried to provide a reproducible way, it was used Babel and Browserify.
However, I became unable to convert at Babel by `export var __esModule` has been added from alpha.22.

```
SyntaxError: node_modules/angular2/es6/dev/di.es6: Line 17: Illegal export "__esModule"
  15 | // It expects all transpiled modules to contain this marker.
  16 | // TODO: remove this when we no longer use traceur
> 17 | export var __esModule = true;
     |            ^
  18 | //# sourceMappingURL=di.js.map
```

Because the Angular 2 are presently considered to be a transition period, I wait and see a little more about how PhantomJS correspondence. I will try again once the situation has changed.

**Comment by mhevery** [comment]
obsolete
