### ISSUE TITLE
internet explorer 11 Authoraization Error in Angular 4

### ISSUE THREAD

**Issue by rajasekharreddyjava** [angular/angular#16467]
I have created a pdf viewer component in angular 4 and I am getting authorization error while opening the doc.here is the simple plunker exampe. I must not use CORS for this problem. Is there any other way to solve this problem.

https://plnkr.co/edit/vn3V2ccKAGVzHGPGKadE?p=preview

I also enabled the protected mode in Adobe pdf reader. It is working in all the remaining browsers.
thanks in advance.

**Comment by rajasekharreddyjava** [comment]
@vicb

**Comment by rajasekharreddyjava** [comment]
[Bug] 
here is the update plunker example which is working in chrome and not in IE.
https://plnkr.co/edit/9d9E4kazdNeHrR09nnId?p=preview

**Comment by YARARMAN** [comment]
Replace follow code instead of your object code:
<iframe *ngIf="objectUrl" [src]="objectUrl" style="width: 100%; height: 100%;" frameborder="0" scrolling="no">

I tried Internet Explorer 11, on Plunker. It's working.

Solution:
[http://stackoverflow.com/a/21417321](url)

**Comment by matsko** [comment]
This issue doesn't appear to have anything to do with Angular. Please provide more info incase this is incorrect and reopen.
