### ISSUE TITLE
OnInit

### ISSUE THREAD

**Issue by yaroslavert** [angular/angular#16463]
I have proble from call OnInit with Modules;

import { NgModule , OnInit, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthComponent } from './auth.component';
import { SharedModule} from './../shared/shared.module';

@NgModule({
  imports: [
    CommonModule,
    SharedModule
  ],
  declarations: [AuthComponent]
})
export class AuthModule implements OnInit { 
  constructor(){
    console.log('forms');
  }
  ngOnInit(){
    console.log('forms');
    let forms = document.querySelectorAll('.clientHeight');
    console.log('forms');
  }
}
I run my app 
![image](https://cloud.githubusercontent.com/assets/19486652/25592245/b492ee92-2ec0-11e7-90e0-4cf786811d67.png)
console write *form* only from constructor not word with ngOnInit

**Comment by MattMorrisDev** [comment]
OnInit is for components. You don't get that lifecycle hook for NgModule's.

**Comment by yaroslavert** [comment]
thank
