### ISSUE TITLE
docs: router - URLMatch link in docs 404

### ISSUE THREAD

**Issue by ljmerza** [angular/angular#16465]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://angular.io/docs/js/latest/api/router/index/Routes-type-alias.html has a link for URLMatcher docs but the link is broken. Links here
https://angular.io/docs/js/latest/api/router/index/UrlMatcher

**Expected behavior**
link works

**Minimal reproduction of the problem with instructions**
go to https://angular.io/docs/js/latest/api/router/index/Routes-type-alias.html and click on the URLMatcher link in blue

**What is the motivation / use case for changing the behavior?**
better docs

**Please tell us about your environment:**

* **Angular version:** 2.0.X
Angular4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jasonaden** [comment]
Looks like this is no longer an active page. If there's an internal link that sends people to it, please file an issue to fix that URL.
