### ISSUE TITLE
td [hidden] attribute not working when I assign a CSS class to it

### ISSUE THREAD

**Issue by angular2fan** [angular/angular#16461]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a td element with hidden attribute and it was working till I applied a bootstrap class. Once I applied the bootstrap css class "col-md-3" the hidden attribute is not working [td element is still visible even if the hidden attribute condition satisfies to true]. If I remove the CSS class, the hidden attribute is fucntional. *ngIf works even if I apply the CSS class. i got to change from Hidden to *ngIf to make it to work. 

**Expected behavior**

td should be hidden even if I apply some css styles.
**Minimal reproduction of the problem with instructions**
Create a table->tr->td. on the td apply [hidden] attribute and make the hidden attribute driven by model variable. apply a CSS class to the same td and see the behavior

**What is the motivation / use case for changing the behavior?**

 I have a td which should be visible only if a certain condition is met and should be hidden if the condition is not met
**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by robwormald** [comment]
Please provide a reproduction, preferably with a plunker.

**Comment by angular2fan** [comment]
Here you go. There is a model variable 'hideMe' which I am making use for toggling behavior.

http://plnkr.co/edit/ELRIVTf52hs5tihADaFO?p=preview

Thank you.

**Comment by ericmartinezr** [comment]
This is an *issue* with bootstrap, not angular. If you see the css you'll see that bootstrap is adding `display: table-cell` to whatever has `col-md-12` as class. Inspect the table, uncheck "display" in the dev tools and the td will dissapear

![image](https://cloud.githubusercontent.com/assets/13039652/25595873/ded03972-2e9c-11e7-9ccd-239cdd1f9e83.png)

I'm not an expert with bootstrap css, but google suggested classes like `hide` and `hidden`, so you could do `[class.hidden]="hideMe"`.

**Comment by angular2fan** [comment]
Perfect explanation and thanks for looking into this. 
This info helps in understanding what's causing this behavior and yeah [class.hidden] seems to do the trick.
I now got to know what is the difference between [hidden] and [class.hidden]. Thanks Eric, Rob and Google.

Closing this out as angular has nothing to do with this behavior.

**Comment by ericmartinezr** [comment]
@angular2fan sorry, I didn't see that that could cause confusion. The `[hidden]` is angular binding to the [hidden](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) attribute, while `[class.hidden]=".."` is angular binding to the [class](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class) attribute plus adding the `hidden` class which is provided by bootstrap css (ends in the html being `class="hidden"`). You can always ask for help on [gitter chatroom](https://gitter.im/angular/angular) 👍

**Comment by angular2fan** [comment]
You are awesome Eric. Thanks so much and I will make use of Gitter Chatroom (I didn't know we have a chat community till you mentioned that). And, now I know the difference between [hidden] and [class.hidden] as well. +1 for gitter chatroom +10 for the nice explanation.
