### ISSUE TITLE
Nesting url segment elements in ActivatedRouteSnapshot url property

### ISSUE THREAD

**Issue by repkins** [angular/angular#16473]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

Instance of **ActivatedRouteSnapshot**, which represents nested route, property `url` always has array of one url segment (instance of UrlSegment)

**Expected behavior**

Instance of **ActivatedRouteSnapshot** property `url` should have array with all url segments

**Minimal reproduction of the problem with instructions**

*MINIMAL DEMO*
http://plnkr.co/edit/i5QPI9JY60vqm4oUoGSV?p=preview

When you open up the console, you should see ActivatedRouteSnapshot property `url` value output. Instance of such class is a property `snapshot` of ActivatedRoute.

**What is the motivation / use case for changing the behavior?**

Building navigation paths (breadcrumbs)

**Please tell us about your environment:**

Xubuntu 16.04, Visual Studio Code, NPM, angular-cli

* **Angular version:** 4.0.1

* **Browser:** Chrome 58.0.3029.81

 
* **Language:** TypeScript 2.2

**Comment by basst314** [comment]
any progress on this?

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

In the snapshot, this is a specific segment. In ActivatedRoute, you should see the array.
