### ISSUE TITLE
Build: `test.unit.dart` fails silently in case of errors in Dart code

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#1647]
It seems that no errors in Dart code are reported while `test.unit.dart` is run - the only symptom is that Dartium doesn't get captured in Karma. This leads to very long and painful investigations, especially for cases where you need to update Dart version (and is extra-confusing for people not familiar with Dart and its tooling).

@alexeagle @IgorMinar I know that you guys are planning to move from Karma pre-processor to Brocolli for unit tests, so could you please look at this one while doing changes to the build?

**Comment by IgorMinar** [comment]
can you provide steps to reproduce this? are the errors coming from ts2dart, or dartium or are these test failures?

I noticed that some syntax errors are ignored by ts2dart (e.g. appending `}` to the end of the file should result in emit failure, but it doesn't and ts2dart/typescript somehow autocorrects the file and moves on).

**Comment by pkozlowski-opensource** [comment]
@IgorMinar I didn't investigate this issue so I'm not sure what is the source. The way I was able to reproduce this in this past all the time would be:
* stop all the Karma instances
* go to any Dart file (one with the *.dart extension) and modify it in the way that creates syntax error
* start karma (`gulp test.unit.dart`) - the tests are not run at all (it looks like Karma hangs and doesn't start running tests)

Maybe it was a problem in Dart pre-processor for Karma and maybe it is solved now since we are now not using this pre-processor.

**Comment by pkozlowski-opensource** [comment]
@IgorMinar sorry, can't confirm now if it still happens as I don't have access to my machine, but I hope that the above steps to reproduce are clear.

**Comment by IgorMinar** [comment]
I was able to repro this and fix it.

**Comment by pkozlowski-opensource** [comment]
Awesome, thnx @IgorMinar !
