### ISSUE TITLE
docs: HTTP Client document page miss 'import' for 'throw' operator

### ISSUE THREAD

**Issue by hellamps** [angular/angular#16471]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://angular.io/docs/ts/latest/guide/server-communication.html#!#fetch-data
in source code of src/app/toh/hero.service.ts (revised)
there is no string 
   >import 'rxjs/add/observable/throw';

as result, on bad JSON coming from API we got __WEBPACK_IMPORTED_MODULE_2_rxjs_Observable__.Observable.throw is not a function

**Expected behavior**
> import 'rxjs/add/observable/throw';

should present

**What is the motivation / use case for changing the behavior?**
Fix documentation

* **Angular version:** 4

* **Browser:** all
 
* **Language:** all

**Comment by kapunahelewong** [comment]
Hey @alxhub, I'm happy to submit the PR for this. Should I add 
`import 'rxjs/add/observable/throw';` to `heroes.service.ts`?

**Comment by jenniferfell** [comment]
@jbogarthyde This was originally filed against v4. When you get some time, could you take a look and make an assessment in the context of the current rxjs implementation?  Thanks.

**Comment by jbogarthyde** [comment]
@jasonaden @alxhub Is this still relevant? What needs to be done to fix it? 
Should the example code be using throw at all?

**Comment by jasonaden** [comment]
I can't find `throw` in the referenced doc anymore, and this should have been updated anyway with the update to RxJS v6. So I'll close this issue. If for some reason this is still needed, let's open a new issue.
