### ISSUE TITLE
Update AppModule

### ISSUE THREAD

**Issue by andretortolano** [angular/angular#16475]
This is regarding the Hero Tutorial on the webpage

**Current behavior**
during https://angular.io/docs/ts/latest/tutorial/toh-pt5.html on "Update AppModule" there is one line showing:

+makeTabs( toh-5/ts/src/app/app.module.ts, toh-5/ts/src/app/app.module.3.ts, null, src/app/app.module.ts (after), src/app/app.module.ts (before)) :

**Expected behavior**

the expected behavior in this case is to show a widget with code as it shows in other cases when its mentioned "here is a revised version of file X"

**Comment by gkalpak** [comment]
Thx for reporting. This has been fixed on the [new version][1].

[1]: https://aio-staging.firebaseapp.com/tutorial/toh-pt5
