### ISSUE TITLE
Angular2 routing not working

### ISSUE THREAD

**Issue by sushilraj786** [angular/angular#16476]
Hi,

I was doing exercise in Angular 2 routing and was able to create and run the project in Angular-2.
when I run the application it works fine if used 2 layer routing.
but when I increase routing layer to 3 it behaves unexpected.
![multilayerrouting](https://cloud.githubusercontent.com/assets/26320913/25622281/8d9e4488-2f71-11e7-8950-60415e6125f2.png)

There is one app module in which I am loading application.
then I have created separate modules for signin, signup and baselayout for others.
after login I want to use base layout as my app layout and want to load everything inside baselayout so that header and footer can be consistent.

and for each functionality I have created separate modules like DivisionModule, OrganizationModule and I want to load these two modules inside baselayout module but when I load any component of DivisionModule it directly loads inside app module not inside baselayout.

here is git url of my project.

https://github.com/sushilraj786/Angular.git

When I access signin or signup it works but when I try to access app/Organization/edit or app/organization/list or app/division/edit or app/division/list it loads under app module not under baseLayout module.

Any help would be appreciated.

Thanks
Sushil

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
