### ISSUE TITLE
feat(forms): block submit on invalid controls

### ISSUE THREAD

**Issue by natsid** [angular/angular#16481]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, the ngSubmit action happens as soon as the submit button is clicked on a form, regardless of whether the form is valid.

**Expected behavior**
I'd like the same functionality of AngularJS forms, where the submit action is actually blocked until the form is valid. See this codepen: http://codepen.io/anon/pen/PmWPaO (a dialog pops up when the form is actually 'submitted').

**Minimal reproduction of the problem with instructions**
See this plunk with a 'required' input: http://plnkr.co/edit/N7Cqz0QRlzNgwWki56jE?p=preview (a dialog pops up when the form is actually 'submitted').

**What is the motivation / use case for changing the behavior?**
I don't want to just disable the submit button until valid, because there are cases where a user may not notice a field (and thus never touch it), and it won't be highlighted as invalid until they either touch it or attempt to submit it.

* **Angular version:** I believe this is the case in the most recent version of Angular.

* **Browser:** [all]
 
* **Language:** [all]

**Comment by devoto13** [comment]
You can easily do it by just adding `[disabled]="myForm.invalid"` on the submit button.
See: http://plnkr.co/edit/9EQoaZWqGDWY9NkIIRJi?p=preview

**Comment by natsid** [comment]
I _don't_ want to disable the submit button. I want it to still be clickable but not actually perform the (ngSubmit) action, so that invalid fields can be highlighted but the form is not actually submitted.

The reason for this is that if the button is disabled, it can be frustrating for a user who may not see what is wrong with the form until the invalid fields are highlighted (we generally don't want to highlight fields as invalid until they have been touched, or else there has been a submit attempt).

**Comment by devoto13** [comment]
It's still easy to implement. Especially using reactive forms. And I don't think that what you're asking should be the default behavior. Other people may want their forms to work differently.

http://plnkr.co/edit/IPDhjggKn1yivHuNwKCP?p=preview

**Comment by bourey** [comment]
In addition to not actually submitting the form, we need the form to then display all error messages, whether the form field has been touched or not.  This is not currently simple to implement on a form-wide basis, but it worked out of the box in Angular Material 1.

**Comment by devoto13** [comment]
@bourey If you are using template-driven forms you can use `NgForm.submitted` to check (see my plunker from previous comment). In the model-driven forms it's a bit more dirty, you'll have to introduce extra `submitted` variable in your component and use in a similar way as `NgForm.submitted`.

**Comment by bourey** [comment]
Presumably that would require us to manually check submit status in every single error validation message. That adds more work for developers and also increases the risk that some fields may be missing that logic and provide an inconsistent user experience.

**Comment by natsid** [comment]
@devoto13, yep I have been using the `NgForm.submitted` for template-driven, and the extra `submitted` variable for reactive forms, and this works. However, as @bourey mentioned, we'd need to make sure to do this on every form/form element.

**Comment by kara** [comment]
We talked about this in person and came up with a solution, but so people know what's going on:

In both Angular and AngularJS, the `ngSubmit` event is a simple pass-through of the submit event. If the form is not submitted, it won't fire.  The difference between the two versions is that Angular adds the `novalidate` attribute by default when using Angular forms, while AngularJS leaves this to the developer. As a result, when using AngularJS, if you don't add `novalidate` yourself, native form validation is turned on. This will block the submission of the form when invalid, and thus  `ngSubmit` never fires. Angular turns off native validation, so it doesn't block the submit event. 

There are a few options. One is to add the `ngNativeValidate` attribute to the form tag to turn native validation back on. This will make the form functionally similar to AngularJS and it will block submission until the form is valid.  Another is to use something like `md-error` in Angular Material that automatically hides itself until the form is submitted. This avoids having to write it over and over. See [example of the latter pattern here](http://plnkr.co/edit/hT1KBSJn6kPFP8u9jqsm?p=preview).  Given that these options cover the use case, I don't think it's necessary to change the behavior of `ngSubmit` for all framework users. We definitely want to take another look at error message handling down the line to see if we can improve the experience, so we can approach it from that angle.
