### ISSUE TITLE
No direct way to disable animation children

### ISSUE THREAD

**Issue by matsko** [angular/angular#16483]
Up to this point there has been a big effort to refactor the animation code and make it runtime compatible and to introduce new features such as query, variables and router animations. There is, however, no support for disabling animations on a DOM-structure level.

Here is what is in mind for doing this:

```html
<!-- disable animations here and for its children -->
<div [@$disabled]="bool">...</div>

<!-- issue a callback when ANY animation event occurs -->
<div (@$all)="callback($event)">...</div>

<!-- issue a callback when any start animation event occurs -->
<div (@$all.start)="onStart($event)">...</div>

<!-- issue a callback when any done animation event occurs -->
<div (@$all.done)="onDone($event)">...</div>
```

**Comment by thesmartwon** [comment]
Being able to disable animations for an element and all its children would be amazing! Is there an easy way to do this in the meantime until this is released? Currently I have to add an extra transition to each element I want not to be animated that resets back to a normal state in 0ms...

**Comment by lokeshdaiya** [comment]
@matsko 
Its not working....throwing error in browser console "ERROR Error: Found the synthetic property @.disabled. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
"
Here is sample plnkr  https://plnkr.co/edit/uOASzz.

**Comment by matsko** [comment]
Yes sorry there was a bug that this PR (https://github.com/angular/angular/pull/18064) intended to fix, but it failed to make the release. It will show up in this week's release.

In the meantime, to get around the error, just add an empty animation to the component that contains the `@.disabled` in the template. So something like this:

```ts
@Component({
  animations: [
    trigger('removeThisWhen301isOut', []) 
  ]
})
```

**Comment by matsko** [comment]
@lokeshdaiya 5344be518283e40201e34af413ddd34db6b51059 has fixed the issue and is now in master. The release for it should pop up within the next couple of days.

**Comment by lokeshdaiya** [comment]
Thanks @matsko  for update.
