### ISSUE TITLE
aio: toc scroll back to top when toc-more-items clicked

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#16482]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/2958442/25630398/d8b759c8-2f21-11e7-8e3e-9a33ec2fc6f6.gif)

**Expected behavior**
It would be nice if the user is sent back to the top (table of contents area) once they click on the toc-more-items button to close the TOC back up (three circles button)

**Comment by petebacondarwin** [comment]
Is this really a blocker? The fact that @sjtrimble even says "it would be nice" is bit of a flag that this is not blocking release.
