### ISSUE TITLE
Error: Cannot find module when using template strings in LoadChildren path in router

### ISSUE THREAD

**Issue by mark-siama** [angular/angular#16494]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using the below code block it produces the listed error below on `ng serve`. I have already logged this with the CLI team and they have asked for it to be logged here.
Previous issue request => https://github.com/angular/angular-cli/issues/6123

**Code example**
```
const modName = 'Lazy';

const appRoutes: Routes = [
  { path: '', component: SecondComponent },
  {
    path: 'lazyMod',
    loadChildren: 'app/' + modName.toLowerCase() + '-mod/lazy-mod.module#' + modName + 'ModModule'
  }
];
```
Replacing the ES6 template string or concatenated string with `loadChildren: 'app/lazy-mod/lazy-mod.module#LazyModModule` will load the module as expected.

**Error Output**
```
ERROR Error: Uncaught (in promise): Error: Cannot find module 'app/lazy-mod/lazy-mod.module'.
Error: Cannot find module 'app/lazy-mod/lazy-mod.module'.
    at webpackEmptyContext (src async:2) [angular]
    at SystemJsNgModuleLoader.loadAndCompile (core.es5.js:5870) [angular]
    at SystemJsNgModuleLoader.load (core.es5.js:5858) [angular]
    at RouterConfigLoader.loadModuleFactory (router.es5.js:3324) [angular]
    at RouterConfigLoader.load (router.es5.js:3308) [angular]
    at MergeMapSubscriber.project (router.es5.js:1562) [angular]
    at MergeMapSubscriber._tryNext (mergeMap.js:120) [angular]
    at MergeMapSubscriber._next (mergeMap.js:110) [angular]
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:89) [angular]
    at ScalarObservable._subscribe (ScalarObservable.js:49) [angular]
    at ScalarObservable.Observable._trySubscribe (Observable.js:57) [angular]
    at ScalarObservable.Observable.subscribe (Observable.js:45) [angular]
    at MergeMapOperator.call (mergeMap.js:85) [angular]
    at Observable.subscribe (Observable.js:42) [angular]
    at webpackEmptyContext (src async:2) [angular]
    at SystemJsNgModuleLoader.loadAndCompile (core.es5.js:5870) [angular]
    at SystemJsNgModuleLoader.load (core.es5.js:5858) [angular]
    at RouterConfigLoader.loadModuleFactory (router.es5.js:3324) [angular]
    at RouterConfigLoader.load (router.es5.js:3308) [angular]
    at MergeMapSubscriber.project (router.es5.js:1562) [angular]
    at MergeMapSubscriber._tryNext (mergeMap.js:120) [angular]
    at MergeMapSubscriber._next (mergeMap.js:110) [angular]
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:89) [angular]
    at ScalarObservable._subscribe (ScalarObservable.js:49) [angular]
    at ScalarObservable.Observable._trySubscribe (Observable.js:57) [angular]
    at ScalarObservable.Observable.subscribe (Observable.js:45) [angular]
    at MergeMapOperator.call (mergeMap.js:85) [angular]
    at Observable.subscribe (Observable.js:42) [angular]
    at resolvePromise (zone.js:710) [angular]
    at resolvePromise (zone.js:681) [angular]
    at :4200/polyfills.bundle.js:3415:17 [angular]
    at Object.onInvokeTask (core.es5.js:4116) [angular]
    at drainMicroTaskQueue (zone.js:591) [<root>]
    at HTMLAnchorElement.ZoneTask.invoke (zone.js:464) [<root>]
```

**Expected behavior**

The loadChildren property should take a string, concatenated string or an ES6 template string.

**Minimal reproduction of the problem with instructions**

**Link to sample repo =>** 
https://github.com/markvdesign/angular-cli-issue

**Steps to reproduce**
Add a route using loadChildren string path to a module and use a variable in either an ES6 template string or concatenated string will reproduce the error when running `ng serve`
**Example**
```
const modName = 'Lazy';

const appRoutes: Routes = [
  { path: '', component: SecondComponent },
  {
    path: 'lazyMod',
    loadChildren: 'app/' + modName.toLowerCase() + '-mod/lazy-mod.module#' + modName + 'ModModule'
  }
];

**This works**
{ path: 'lazyMod', loadChildren: 'app/lazy-mod/lazy-mod.module#LazyModModule' }

**These do not**
{ path: 'lazyMod', loadChildren: 'app/' + modName.toLowerCase() + '-mod/lazy-mod.module#' + modName + 'ModModule' }

{ path: 'lazyMod', loadChildren: `app/${modNam}-mod/lazy-mod.module#${modNam}ModModule` }

{ path: 'lazyMod', loadChildren: `app/lazy-mod/lazy-mod.module#LazyModModule` } // NOTE: using back ticks only
```

**Please note**
If you load the demo app with the `loadChildren: 'app/lazy-mod/lazy-mod.module#LazyModModule` string to begin. You will need to stop `ng serve`, clear the cache on the browser (I was using Google Chrome	57.0.2987.133 (Official Build) (64-bit)) change to the template string then restart `ng serve` to reproduce the error.

**What is the motivation / use case for changing the behavior?**

The ability to add variables to the `loadChildren` path.

**Please tell us about your environment:**

OS: Windows 10
IDE: Visual Studio Code

```
@angular/cli: 1.0.0
node: 7.5.0
os: win32 x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.0
```

* **Angular version:** 2.0.X

```
@angular/cli: 1.0.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.0
```

* **Browser:** [all]

Google Chrome	57.0.2987.133 (Official Build) (64-bit)

Microsoft Edge 40.15063.0.0

Firefox 53.0 (64-bit)

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.2.2

* **Node (for AoT issues):** `node --version` =  node: 7.5.0

**Comment by Adol1111** [comment]
The first problem is about @angular/compiler, the expression is not support for function. So modName.toLowerCase() was never called when aot.  

https://github.com/angular/angular/blob/master/packages/compiler/src/aot/static_reflector.ts#L565-L587.

```
staticSymbol = simplifyInContext(context, expression['expression'], depth + 1) 
// expression['expression'] is toLowerCase, it's a function . so it will return IGNORE
```

The second problem is about @angular/tsc-wrapped. It is not support for express（like ``）、lambda and function ( modName.toLowerCase() is a member function, but the check is missing)

https://github.com/angular/angular/blob/master/tools/%40angular/tsc-wrapped/src/evaluator.ts#L571-L575

**Comment by tickluo** [comment]
@Adol1111  awesome!!

**Comment by splincode** [comment]
How to dynamically load the compiled Angular file into routing?

I use:
`
@Component({ ... })
export class WorkspaceOutletComponent {

    constructor() {
    }

    ngOnInit() {
        // detect routing and exec init
    }

    public init(workSpaceUrl: string, workSpacePathModule: string) {
        console.log(`url: ${workSpaceUrl} path: ${workSpacePathModule}`)();

        this.router.resetConfig([
            {
                path: workSpaceUrl, loadChildren: workSpacePathModule
            }
        ]);

        this.router.navigate([workSpaceUrl])
            .then(() => console.log('Navigate to'))
            .catch((e) => console.error('Error', e));
    }

}
`

But cannot find module (((

https://stackoverflow.com/questions/44734387/how-to-dynamically-load-the-compiled-angular-file-into-routing/44735515#44735515

**Comment by jasonaden** [comment]
It will need to be a constant. If you were to assign to a constant variable instead, this example should work.

**Comment by mark-siama** [comment]
@jasonaden the name of the module is a constant as per line one of the example
 `const modName = 'Lazy';`
Could you please provide an example of what you mean?
And when you say **should work** did you test it before closing it? I'm a little confused.

**Comment by izverev-aexsoft** [comment]
Same here, have two sub-sites, and cannot load views depending on City constant. All following versions failed:

```
loadChildren: "app/views/" + APP_CONFIG.City + "/views.module#ViewsModule"
loadChildren: `app/views/${APP_CONFIG.City}/views.module#ViewsModule`
loadChildren: APP_CONFIG.City === "NY" ? "app/views/ny/views.module#ViewsModule" : "app/views/la/views.module#ViewsModule"
```

**Comment by rodrigoEclipsa** [comment]
after 2 weeks of research, apparently there is no clear way to load modules that are not present at the time of compilation, it also seems that the angular cli does not help at all, I have tried with
SystemJsNgModuleLoader
system.import
require.ensure

and I have failed in all my attempts, it is a pity without this characteristic angles module system is not complete
