### ISSUE TITLE
When to expect the first angular2 version working with tsc?

### ISSUE THREAD

**Issue by KhaosTheory1012** [angular/angular#1649]
I am currently using the angular2 bundle and .d.ts from ngconf2015demo but it is not enough to work with if I want to use typescript.

Are there any ways to get ts and ng2 work at the moment?

**Comment by pkozlowski-opensource** [comment]
@KhaosTheory1012 it should be already possible with the latest development preview - please check https://angular.io/docs/js/latest/quickstart.html (and the corresponding repo: https://github.com/angular/ts-quickstart)

It might still have some rough edges so please do report issues in https://github.com/angular/ts-quickstart if you bump into any issues.
