### ISSUE TITLE
language-service: if template/templateUrl is function result should not trigger error

### ISSUE THREAD

**Issue by shalomdotnet** [angular/angular#16492]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
![angular bug](https://cloud.githubusercontent.com/assets/16134688/25639065/39172af2-2f93-11e7-84d4-57594ee351e9.png)

**Expected behavior**
No error.

**Minimal reproduction of the problem**
```
import { Component } from '@angular/core';

@Component({
    templateUrl: module.filename.replace('.ts', '.html'),
})

export class TestComponent { }
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.3
* **Typescript version:** 2.2.2
* **VS Code version:** 1.11.2
* **[Angular Language Service](https://github.com/angular/vscode-ng-language-service) version:** 0.1.3
(This extension uses `@angular/language-service@4.1.0-beta` and `typescript@2.1.5`)

**Comment by tbosch** [comment]
This is works as intended. The language service analyses the code whether it is compatible with Ahead of time compilation (AOT), and function calls are not supported in this case.
