### ISSUE TITLE
Confusing error message using @HostBinding with @Input

### ISSUE THREAD

**Issue by karptonite** [angular/angular#16493]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
See the error message in the console of this Plunkr
https://plnkr.co/edit/sRSRE6E4BFDKD9cH1q2w?p=preview
Can't bind to 'foo' since it isn't a known property of 'my-component'.
1. If 'my-component' is an Angular component and it has 'foo' input, then verify that it is part of this module.

However, myComponent is an angular component with a 'foo' input.

The actual error, according to  @tbosch , is that "you cannot use @HostBinding to set @Inputs. @HostBinding is always directly to the DOM."

**Expected behavior**
The error message should be more clear in this case.

* **Browser:** [Chrome 57 ]

@Toxicable reported at your request.

**Comment by pkozlowski-opensource** [comment]
Sadly, this error message got worse with Angular 9 + ivy: https://ng-run.com/edit/ZIGDmWt7Czf0UXklK9LE
* it is console.warn so not very visible to the end-user;
* it doesn't provide any means of identifying a component - there is no tag name, no stack trace - we only have a property name:

> Can't bind to 'dosNotExist' since it isn't a known property of 'null'.

**Comment by kara** [comment]
Totally agree that this error message is confusing / misleading. We have an existing issue tracking the problem here: https://github.com/angular/angular/issues/13776. Closing this issue as a dupe.
