### ISSUE TITLE
Error: Please add a @Pipe/@Directive/@Component annotation

### ISSUE THREAD

**Issue by anilkamujula** [angular/angular#16502]
Unexpected value 'PostService' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.

when i am calling service module in the AppModule i got the above issue. can any one please suggest me

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/15890

**Comment by anilkamujula** [comment]
But i didn't get the solution #15890  in that post. still i am getting the same issue while lunch the application  using  ng serve --aot. 
**Error as shown below.**

ERROR in Unexpected value 'PostService in C:/myAngularApp/src/app/service/posts.
component.ts' declared by the module 'AppModule in C:/myAngularApp/src/app/app.m
odule.ts'. Please add a @Pipe/@Directive/@Component annotation.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in
 'C:\myAngularApp\src'
 @ ./src/main.ts 4:0-74
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

**Comment by ericmartinezr** [comment]
Sorry, I didn't mean to say that there was a solution in that issue. I just pointed it out so there aren't two issues reporting the same bug (?). The other issue has more context and it could be reproducible since it has code and the configuration of the user's project, which you didn't provide.

**Comment by pkozlowski-opensource** [comment]
Agree with @ericmartinezr - there is no point in opening new issues for the same error message. Rather, please provide a _minimal_ and _runable_ reproduce scenario (a plunker, a small repository that we could clone etc.) and post it in #15890

**Comment by jososaga** [comment]
You can also get this error if you declare a service in the declarations array. You have to declare your services in the providers array.

**Comment by acasdej** [comment]
Be sure the decorator has de caracter @.
If you don´t type @ before de decorator function you will have this error message
@Component({ selector: '...', }) -> Ok
Component({ selector: '...', }) -> ERROR MESAGE: 'add a @Pipe/@Directive/@Component'

**Comment by Parinita789** [comment]
I was getting this issue because I forgot to add @Component decorator:
@Component({
     selector:  'something',
     templateUrl:  'somrthing.html',
     styleurls: ['./something.css']
})
 After adding the decorator this issue was solved.

**Comment by projectoblio** [comment]
I got this issue because I put an @Injectable after my @Component declaration inside the .ts page file

**Comment by snehagollapaliwar** [comment]
Uncaught Error: Unexpected module 'n' declared by the module 'n'. Please add a @Pipe/@Directive/@Component annotation.

![image](https://user-images.githubusercontent.com/15356010/50512924-d5e10700-0aba-11e9-8a3a-3a9fb3bc7f8b.png)


didn't find any solution for this.. Kindly suggest something good.

**Comment by totheskyer** [comment]
Please check if all services were provided in providers array at module
