### ISSUE TITLE
aio: Fix async docs-tests to remove flaky behaviour

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16501]

**Comment by gkalpak** [comment]
FWIW, the test that I see failing more frequently is:
[authors-package should generate API doc if the "fileChanged" is an API doc][1]

[1]: https://github.com/angular/angular/blob/71f5b73296708014b740fb5dd0145c0599de7a19/aio/tools/transforms/authors-package/index.spec.js#L69-L75

**Comment by petebacondarwin** [comment]
Exactly. Both of the API tests rely upon the TypeScript compiler booting up, which can take a while and appears to be quite variable.

**Comment by petebacondarwin** [comment]
These are integration tests and as such are async. Apart from trying to speed up Dgeni and increase the timeout length, there is not much we can do but keep an eye on these.
