### ISSUE TITLE
Template annotation - Is it removed in the developer preview

### ISSUE THREAD

**Issue by shtefanntz** [angular/angular#1650]
Greetings!

I am trying to prepare a demo to show the new stuff in angular2, but it seems that the @Template annotation is missing. Other people have used it in their example, but I cannot find it.

Also, is there a type definition file with all the directives/components on github?

Thanks,
Stefan

**Comment by matanlurey** [comment]
It is currently the `@View` annotation.

See: https://angular.io/docs/js/latest/quickstart.html

**Comment by pkozlowski-opensource** [comment]
@matanlurey is totally right - `@Template` was renamed to `@View` in developer preview.
