### ISSUE TITLE
Angular 2 style in microsoft edge

### ISSUE THREAD

**Issue by armangevorgyan** [angular/angular#16509]
`<div [style.background-image]="backgroundImg"></div>`

this doesn't work in microsoft edge. how i can fix that??

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
