### ISSUE TITLE
aio: IE no bueno. Need polyfill strategy

### ISSUE THREAD

**Issue by wardbell** [angular/angular#16519]
Angular apps - including this one - won't run in IE without polyfill. But a polyfill for everyone will slow loading. What do we do? We don't want to punish everyone to make IE happy. @IgorMinar - a solution please?

Btw, the fact that our aio code uses features not native to IE is a drop in the bucket.

**Comment by petebacondarwin** [comment]
I think an approach like https://philipwalton.com/articles/loading-polyfills-only-when-needed/ is what we want.

**Comment by wardbell** [comment]
Maybe. But his test for "modern browsers" may need refining.
```
function browserSupportsAllFeatures() {
  return window.Promise && window.fetch && window.Symbol;
}
```
I fear this may exclude an important set of devices ... the ones that actually need to load quickly:
 
I don't know. Just saying.

**Comment by petebacondarwin** [comment]
Obviously we write our own test!

**Comment by petebacondarwin** [comment]
This is the test that AngularJS uses for IE 9-11: 

```
// Support: IE 9-11 only
/**
 * documentMode is an IE-only property
 * http://msdn.microsoft.com/en-us/library/ie/cc196988(v=vs.85).aspx
 */
msie = window.document.documentMode;
```

See https://github.com/angular/angular.js/blob/4a12ae7b3617e7c5389cf67ce3e3c7b309fcd9b9/src/Angular.js#L197

**Comment by petebacondarwin** [comment]
So we cannot use https://polyfill.io because it appears to make too many changes to the global objects, which upsets things like Zone aware Promises.

We can, though, generate our own IE polyfill file from the `core-js` project and use that instead.

This works with IE 10 and 11 but there are still issues getting the site to work with IE 9.
