### ISSUE TITLE
Custom Elements does not work inside of angular component

### ISSUE THREAD

**Issue by jianliao** [angular/angular#1651]
I try to make a very simple custom element([copied from here](http://webcomponents.org/articles/introduction-to-custom-elements/)) work with Angular2. If I use it directly in top level index.html, everything works fine. But if use it in a angular2 component template, my custom element does not seem to work. Please check the full demo from my [Plunker](http://plnkr.co/edit/sAnwQZ?p=preview). The angular2 version is 2.0.0-alpha.20, this is newest version that can be found in code.angularjs.org, but I tested 2.0.0-alpha.21 in my local box, the result is still the same.

**Comment by matanlurey** [comment]
I think this is a known bug: #1442.
