### ISSUE TITLE
ReactiveForms

### ISSUE THREAD

**Issue by buctwbzs** [angular/angular#16515]
**I'm submitting a bug**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
i have read Doc about reactive form, after i  did a demo,i found a bug about formArry and i user Angular2.2.4.
```<div class="container">
  <form [formGroup]="$form">
    <div formArrayName="formItems" class="well well-lg">
      <div *ngFor="let formItem of $form.controls.formItems.controls;let i =index" [formGroupName]="i">
             <input type="text" class="form-control" formControlName="a">
             <input type="text" class="form-control" formControlName="b">
             
      </div>
    </div>
  </form>
  <button class="btn" (click)="addForm()"></button>
</div>
```
**in the above way** ,i can get formControl a and b. but when i follow  the demo in Doc,it's wrong.

for example:
```<div class="container">
  <form [formGroup]="$form">
    <div formArrayName="formItems" class="well well-lg">
      <div *ngFor="let formItem of formItems.controls;let i =index" [formGroupName]="i">
             <input type="text" class="form-control" formControlName="a">
             <input type="text" class="form-control" formControlName="b">
             
      </div>
    </div>
  </form>
  <button class="btn" (click)="addForm()"></button>
</div>```
what the browser console was "Cannot read property 'controls' of undefined "

last but not least,this is my component class:
``` $baseform = [{a:1111,b:2222},{a:7777,b:8888}]
  constructor(private fb: FormBuilder) {
    this.createForm();
    this.setForm(this.$baseform);
  }
  ngOnInit() {
    console.log(this.$form);
  }
  createForm(){
    this.$form = this.fb.group({
      formItems: this.fb.array([])});
  }
  setForm(a:any[]){
   let a1= a.map($a=>this.fb.group($a));
   let a2 = this.fb.array(a1);
   this.$form.setControl('formItems',a2);
  }
  addForm(){
    this.$form.controls.formItems.controls.push(this.fb.group({a:222,b:5555}))
  }
```

**Expected behavior**

will be like example one.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

window,VScode,npm,ng serve
* **Angular version:** 2.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by trotyl** [comment]
In the doc (if you mean [this one](https://angular.io/docs/ts/latest/guide/reactive-forms.html)), there's a property defined in component class for access that formArray:

```typescript
get secretLairs(): FormArray {
  return this.heroForm.get('secretLairs') as FormArray;
}
```

Then it was used in the template:

```html
<div *ngFor="let address of secretLairs.controls; let i=index" [formGroupName]="i" >
  <!-- The repeated address template -->
</div>
```

But I didn't find the `formItems` property provided in your component class code.

**Comment by buctwbzs** [comment]
in createForm method,you will see formItems.  besides,i found another bug. when i put <p>{{ $form| json}}</p>,i can get the form's value,but when i add a form group in formArry nameed formItems useing addForm method. then  the tag 'p' make no  changes.

**Comment by buctwbzs** [comment]
@trotyl  i think i kown you in 知乎~

**Comment by buctwbzs** [comment]
another bug.

- 

 initialize page
![1](https://cloud.githubusercontent.com/assets/19690435/25711088/abfe5fe8-3120-11e7-954c-05114e2b1962.png)

- after add a formGroup in formArry.
![2](https://cloud.githubusercontent.com/assets/19690435/25711142/c980d4d8-3120-11e7-9427-815a705b8fbe.png)

you can see,the formArry have changed.but  {{$form | json}} make no changes.

**Comment by buctwbzs** [comment]
all my code.

- component
```export class HeroDetailComponent implements OnInit {
 public $form;
 $baseform = [{a:1111,b:2222},{a:7777,b:8888}]
  constructor(private fb: FormBuilder) {
    this.createForm();
    this.setForm(this.$baseform);
  }
  ngOnInit() {
    console.log(this.$form);
  }
  createForm(){
    this.$form = this.fb.group({
      formItems: this.fb.array([])});
  }
  setForm(a:any[]){
   let a1= a.map($a=>this.fb.group($a));
   let a2 = this.fb.array(a1);
   this.$form.controls.formItems('formItems',a2);
  }
  addForm(){
    this.$form.controls.formItems.controls.push(this.fb.group({a:222,b:5555}))
  }```

- HTML
```<p>
  hero-detail works!
</p>
<div class="container">
  <form [formGroup]="$form">
    <div formArrayName="formItems" class="well well-lg">
      <div *ngFor="let formItem of $form.controls.formItems.controls;let i =index" [formGroupName]="i">
             <input type="text" class="form-control" formControlName="a">
             <input type="text" class="form-control" formControlName="b">
             
      </div>
    </div>
  </form>
  <button class="btn" (click)="addForm()">addForm</button>
  <p>{{$form.value | json }}</p>
</div>```

thanks.

**Comment by buctwbzs** [comment]
another question rasie.

- when i input some value in added formControl(after fourth),{{$form | json}} still have no changes,but when i input some value in these initialize formControl(no.1-no.4),{{$form | json}} get all value!

**Comment by trotyl** [comment]
@buctwbzs 

```typescript
this.$form = this.fb.group({
    formItems: this.fb.array([])
});
```

You just set the `formItems` control in the form, but not in the template context (namely component instance).

```html
<div *ngFor="let formItem of formItems.controls;let i =index" [formGroupName]="i">
```

 And here you're accessing the `formItems` variable directly in the template, that's nothing to do with your form.

**Comment by buctwbzs** [comment]
@trotyl 
``` <div *ngFor="let formItem of $form.controls.formItems.controls;let i =index" [formGroupName]="i">``` 
i must use $form.controls.formItems.controls can init my page,when i use formItems.controls, a bug warinng in browser:"controls property can not found on formItems".that is to say i must use all whole reference so that i can access a formGroup(i).

**Comment by trotyl** [comment]
That's true. And it's better to extract complicated expression to component class for readability, you can check the [live example](https://angular.io/resources/live-examples/reactive-forms/ts/final.eplnkr.html) (in `hero-detail.component.ts`) of the reactive form docs for how it works.

**Comment by buctwbzs** [comment]
@trotyl @matsko 
but hero-detail.component.ts used formItems.controls,and it works!

**Comment by trotyl** [comment]
It works with the property explicitly provided in component:

```typescript
get secretLairs(): FormArray {
   return this.heroForm.get('secretLairs') as FormArray;
}
```

**Comment by buctwbzs** [comment]
I think this is not so simple, the example in the document only presents the perfect side. As far as my example is concerned, as I mentioned above, changing the value of the last added form control does not change the form value. Change the value of the above form control, the entire form of the value of the updated again. It is not clear that some changes in the dynamic form of detection asked, I need to seriously look at the form and change detection.

**Comment by trichetriche** [comment]
Just saying a big thank you to @trotyl, you saved my life with the getter, was pulling my hair off for half an hour on that. Thank you !

**Comment by kara** [comment]
Thanks @trotyl for narrowing down the problem. This doesn't look like a forms bug or a docs bug, so I'm closing this issue.
