### ISSUE TITLE
Language Service does not understand index signature in templates

### ISSUE THREAD

**Issue by wulfsberg** [angular/angular#16524]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When a template accesses a property which is defined with an index signature, the Language Service reports `Identifier ... is not defined. '__type' does not contain such a member`.

**Expected behavior**

No warning raised from the Language Service, since this is valid TypeScript.

**Minimal reproduction of the problem with instructions**

Given a variable defined as

    data: { [key: string]: any }

this is valid TypeScript:

    this.data.iCanBeAnything = 'SomeValue';

But when used in a template this way...

    {{data.iCanBeAnything}}

...the Language Service raises a warning.

**What is the motivation / use case for changing the behavior?**

My specific use case is OpenLayers' `Feature` object which exposes a `getProperties()` with the return value defined as `{ [key: string]: any }`, i.e. a geographic object which carries arbitrary, but known-in-context properties. While it is possible to address such properties using the `getProperties()['iCanBeAnything']` notation without provoking the Language Service, this is excessively cluttered.
On a more general level, the Language Service should accept it simply because it is valid TypeScript.

**Please tell us about your environment:**

Win 10, IntelliJ 2017.1.2

* **Angular version:** 4.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by PaulKujawa** [comment]
any progress here?

**Comment by WiseBird** [comment]
[Reproduction](https://github.com/WiseBird/angular_ls_string_index) (if it will help)

**Comment by JoostK** [comment]
Hello folks, this issue has been resolved in the Ivy language service.
