### ISSUE TITLE
aio: have a way to see previews for any PR

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#16526]
Currently, previews are only generated for PRs that (a) touch some file inside `aio/` and (b) have a trusted author. Often it is useful to be able to see a preview for PRs that don't meet these requirements (e.g. touch API docs outside `aio/` or the changes have been verified by a trusted user).

**Comment by IgorMinar** [comment]
this was already implemented

**Comment by IgorMinar** [comment]
oh. I see. sorry.
