### ISSUE TITLE
JSPM install angular2

### ISSUE THREAD

**Issue by hourliert** [angular/angular#1652]
Hi,

I am trying to get angular2 working using jspm.

To setup this, I ran this command:
`jspm init && jspm i npm:angular2 && jspm i npm:rtts_assert`

Here are my files:

package.json
```
{
  "jspm": {
    "directories": {},
    "dependencies": {
      "angular2": "npm:angular2@^2.0.0-alpha.21",
      "rtts_assert": "npm:rtts_assert@^2.0.0-alpha.21"
    },
    "devDependencies": {
      "traceur": "github:jmcriffey/bower-traceur@0.0.88",
      "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.88"
    }
  }
}
````

my system js config file : 
```
System.config({
  "baseURL": "/",
  "transpiler": "traceur",
  "traceurOptions": {
    "annotations": true,
    "memberVariables": true,
    "typeAssertions": true,
    "typeAssertionModule": "rtts_assert/rtts_assert",
    "types": true
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});

System.config({
  "map": {
    ... auto generated by jspm, dependances map
  }
});
```

My index.html

```
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>

System.import('lib/app');
```

And finally my lib/app.js

```
import {Component, bootstrap, View} from "angular2/angular2";

@Component({
  selector: 'my-app'
})
@View({
  template: "Hi {{ name }}"
})
class AppComponent {
  constructor() {
      this.name = 'Alice';
  }
}

bootstrap(AppComponent);
```

I get this error on boot : 
```
Potentially unhandled rejection [2] TypeError: Cannot read property 'defaultDoc' of undefined
    at _injectorBindings (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-alpha.21/src/core/application.js:129:45)
    at _createAppInjector (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-alpha.21/src/core/application.js:198:114)
    at http://localhost:3000/jspm_packages/npm/angular2@2.0.0-alpha.21/src/core/application.js:179:23
    at VmTurnZone.run (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-alpha.21/src/core/zone/vm_turn_zone.js:22:12)
    at bootstrap (http://localhost:3000/jspm_packages/npm/angular2@2.0.0-alpha.21/src/core/application.js:178:8)
    at System.register.execute (http://localhost:3000/lib/app.js!eval:29:7)
    at t (http://localhost:3000/jspm_packages/es6-module-loader.js:7:19798)
    at v (http://localhost:3000/jspm_packages/es6-module-loader.js:7:20180)
    at u (http://localhost:3000/jspm_packages/es6-module-loader.js:7:19856)
    at s (http://localhost:3000/jspm_packages/es6-module-loader.js:7:19737)
```

I inspect the code. It seems, the require of 'angular2/src/dom/dom_adapter' works, but accessing DOM doesn't.  So accessing defaultDoc of DOM doesn't work.

Thanks in advance.

Thomas

**Comment by rkirov** [comment]
The default npm published sources are transpiled using commonJS for module imports. Our dom wrappers use a feature of ES6 modules that does not transpile well to CommonJS - modifying the exported object after it has been required. Thus the error that your are seeing.

We are looking into fixing that, but for now the fastest way to get started with angular 2 is to use the bundles https://code.angularjs.org/2.0.0-alpha.20/ as outlined in the quickstarted guides on http://angular.io.

**Comment by robwormald** [comment]
Couple of notes from poking around at this the past few days, I got a single-file bundle output working via jspm and the builder tool, but its a bit hacky at the moment:

### workaround
You can add an overrride to your app's package.json as follows:
```js
{ 
  "jspm" : {
    "npm:angular2@2.0.0-alpha.23": {
       //forces it to treat it as ES6
      "format" : "es6",
      "directories" : {
        //installs only from the named directory (ignores the CJS source)
        "lib" : "es6/dev"
      }  
    }
  } 
}
```
Then if you do jspm install npm:angular2, that'll get you 90% of the way there. I had to add an additional mapping in my config.js, because of the .es6 extension.

### interim solution
I added angular2 to the registry, PR here https://github.com/jspm/registry/pull/385 - this still doesn't work out of the box due to the file extensions - @rkirov could we get .js (not .es6)  file extensions in the distributed ES6 files? 

### long term 
- move the overrides from the above PR into this repo. 
- make zoneJS exportable (might be able to do this with a shim config)
