### ISSUE TITLE
docs(aio): Add link to Dart site

### ISSUE THREAD

**Issue by kwalrath** [angular/angular#16520]
If you [search for "dart" on angular.io](https://angular.io/search/#stq=dart&stp=1), you get no results. (You do get a quasi-funny hint: did you mean "data"?)

You should instead find at least one page that links to [AngularDart](https://webdev.dartlang.org/angular). Better yet, make it findable without search. 

We'd be happy to return the favor. Let me know how I can help with this.

**Comment by juleskremer** [comment]
Resolved with PR [18080](https://github.com/angular/angular/issues/16520)

**Comment by kwalrath** [comment]
https://github.com/angular/angular/pull/18080
