### ISSUE TITLE
$browser.defer ends up triggering changeDetection in zonejs through settimeout

### ISSUE THREAD

**Issue by masterkidan** [angular/angular#16533]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Due to monkeypatching of settimeout, any action that triggers a browser.defer, (even if it is a $timeout with invokeApply = false), ends up triggering a change detection/digest. 
This means that things that happen on $interval end up constantly triggering digests, even though invokeApply has been set to false. 
See the below timeline: 
![image](https://cloud.githubusercontent.com/assets/942002/25692571/97a78ce0-3058-11e7-8328-777a25f957e3.png)

Here is the offending snippet of code from angularjs 1.5.5
 ```
function interval(fn, delay, count, invokeApply) {
      var hasParams = arguments.length > 4,
          args = hasParams ? sliceArgs(arguments, 4) : [],
          setInterval = $window.setInterval,
          clearInterval = $window.clearInterval,
          iteration = 0,
          skipApply = (isDefined(invokeApply) && !invokeApply),
          deferred = (skipApply ? $$q : $q).defer(),
          promise = deferred.promise;

      count = isDefined(count) ? count : 0;

      promise.$$intervalId = setInterval(function tick() {
        if (skipApply) {
          **$browser.defer(callback);**
        } else {
          $rootScope.$evalAsync(callback);
        }
        deferred.notify(iteration++);

        if (count > 0 && iteration >= count) {
          deferred.resolve(iteration);
          clearInterval(promise.$$intervalId);
          delete intervals[promise.$$intervalId];
        }

        if (!skipApply) $rootScope.$apply();

      }, delay);

      intervals[promise.$$intervalId] = deferred;

      return promise;

      function callback() {
        if (!hasParams) {
          fn(iteration);
        } else {
          fn.apply(null, args);
        }
      }
    }
```

```
self.defer = function(fn, delay) {
    var timeoutId;
    outstandingRequestCount++;
    timeoutId = **setTimeout**(function() {
      delete pendingDeferIds[timeoutId];
      completeOutstandingRequest(fn);
    }, delay || 0);
    pendingDeferIds[timeoutId] = true;
    return timeoutId;
  };
```

**Expected behavior**

invokeApply parameter should be honored, and browser.defer should be run outside of ngzone.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Traditionally in angularjs, we are allowed to use $interval/$timeout with invokeapply false to avoid running a changedetection $digest cycle.

* **Angular version:** 2.0.X

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   NA

**Comment by gkalpak** [comment]
I think the main challenge here is that this would need access to AngularJS's internals, which we don't have from `ngUpgrade` 😞

**Comment by kseamon** [comment]
Would it be possible to make AngularJS aware of ngUpgrade, and ngZone, more to the point. It could check for the presence of the Angular Zone and explicitly run the callback outside of it.

**Comment by gkalpak** [comment]
It is possible to do it "from inside AngularJS". But that would mean that it will only work for AngularJS versions that include the "fix", while previous versions will behave differently.

**Comment by kseamon** [comment]
That's probably ok though, but it might have to wait for 1.7. NgUpgrade is an odd enough thing that it's probably worth some potentially breaking changes to make it work better.

**Comment by masterkidan** [comment]
So as a work around (a bit ugly though). I tried creating a monkey patch like the following to browser.defer: 
```
let _$browser_defer_cancel = $browser.defer.cancel;
      let _$browser_defer = $browser.defer;
      $browser.defer = (fn: Function, delay: number)=> {
        ngZoneService.runOutsideAngular(() => {
          _$browser_defer(fn, delay);
        });
      };

      $browser.defer.cancel =  _$browser_defer_cancel;
```
But this still seems to end up triggering change detection for some reason, is there another way we can workaround this?

**Comment by jbedard** [comment]
Can NgUpgrade `decorate` AngularJS services to solve things like this?

I'm not sure if `$browser.defer` should always run outside the NgZone, but I'd think whenever `invokeApply = false` is manually specified it should...

**Comment by masterkidan** [comment]
browser.defer doesn't actually have an invokeApply parameter to my knowledge. The invokeApply is specified on $timeout/$interval, which do a $rootScope.$apply anyways.

**Comment by jbedard** [comment]
I'm suggesting that the NgZone opt-out should be along with the `invokeApply = true`, so in `$timeout` and `$interval` (and `$$q` etc), not within all `$browser.defer` calls.  Only doing it in locations that explicitly set `invokeApply = true` might avoid some confusion...?

**Comment by masterkidan** [comment]
Ah got it thanks!

**Comment by gkalpak** [comment]
I am going to close this. Let's track the `invokeApply`-based opting-out in #17973.
