### ISSUE TITLE
Suggestion for ng2 docs: cookbook examples

### ISSUE THREAD

**Issue by dgbonomo** [angular/angular#1653]
I'm not sure where else to place this, but I think having a dedicated cookbook section in the Angular 2 docs would be great.  It could provide minimal working examples on how to achieve specific goals that aren't immediately straightforward with step-by-step documentation.  For example, sharing data between nested components, creating components that "pop up" a detail screen, and so on (these are just cases I've run into in the past - I'm not sure how it relates to what Angular 2 does or doesn't do easily or at all).  I think it's a good idea because it can help bridge the knowledge gap for programmers just getting started with Angular 2 who are stuck trying to progress past a rudimentary app.

**Comment by naomiblack** [comment]
Yes, we are planning to do this on angular.io, later in the year.
