### ISSUE TITLE
How to do normal routing with mdDialogref in angular 4?

### ISSUE THREAD

**Issue by bhoomi65** [angular/angular#16532]
```
import { Component, NgModule } from '@angular/core';
import { MdDialog } from '@angular/material';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { Product } from '../../models';
import { ProductService } from '../../services/product.service';
import { MdDialogRef } from '@angular/material';
@Component({
    selector: 'product',
    template: `
    <button mdButton class="md-fab md-primary md-hue-2 addProduct" aria-label="Profile" (click)="openDialog()" >
        add
    </button>
    `
})
export class ProductComponent {
    constructor(public dialog: MdDialog, public dialogRef: MdDialogRef<AddProductComponent>) { }
    openDialog() {
        this.dialogRef = this.dialog.open(AddProductComponent);
    }
}

@Component({
    selector: 'addproduct',
    template: require('./add.product.html'),
})
export class AddProductComponent {
    constructor(public productService: ProductService, public dialogRef: MdDialogRef<AddProductComponent>) {
    }



    addProduct(product: Product) {
        this.productService.addProduct(product).subscribe(() => {
            this.dialogRef.close();
            //this.productService.getAllProducts();
        });
    }
}
```
**This works perfect for me but When I use below code in logincomponent**
```
   this.router.navigate(['/product']);
```
**It throws me error of**
```
ERROR Error: Uncaught (in promise): Error: No provider for MdDialogRef!
```
**When I go through this question on stackoverflow :**

[http://stackoverflow.com/questions/41581712/no-provider-for-mddialogref](http://stackoverflow.com/questions/41581712/no-provider-for-mddialogref)

that tells that we should not use component by 
```
<product></product>.
```

But I need to call product component when I get success of login.So How do I do normal routing with mdDialogRef in angular 4?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
