### ISSUE TITLE
Add toggleClass to Renderer2

### ISSUE THREAD

**Issue by yazeedb** [angular/angular#16538]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

No way to manually toggle a class without writing conditional logic

**Expected behavior**

```javascript
constructor(private renderer: Renderer2) {}
ngOnInit() {
  this.renderer.toggleClass('active');
}
```

**What is the motivation / use case for changing the behavior?**

Renderer2 should allow toggling a class, like its DOM counterpart.

* **Angular version:** ^4.0.0

* **Browser:** all
 
* **Language:** TypeScript ~2.2

**Comment by joelpierre** [comment]
Why is this not a feature by now?

**Comment by marioteik** [comment]
this would be nice.

**Comment by crystalfinch** [comment]
+1

**Comment by tonysamperi** [comment]
+1
something like `classlist.toogle` would be very appreciated.

**Comment by codeherk** [comment]
this feature would be useful.
will **addClass** and **removeClass** work for the time being?

**Comment by JoSeTe4ever** [comment]
Today we discussed this functionality within my team. At the moment what we are doing is emptying the classList and then calling addClass. 

It works if you only have one class :( 

Please implement toggle !

**Comment by zarghamkhandev** [comment]
please add this, highly needed

**Comment by esolioz** [comment]
Hi folks! Please add this. 
It would be quite useful instead of adding and removing a class.
Thx

**Comment by AndrewKushnir** [comment]
Hi, I'm closing this ticket based on https://github.com/angular/angular/pull/22271#issuecomment-729216344. Thank you.
