### ISSUE TITLE
<ng-content> doesn't work properly

### ISSUE THREAD

**Issue by klinki** [angular/angular#16537]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In order to use `<ng-content>` in `*ngIf` statement, selectors must be used.

**Expected behavior**
It should work without needing any additional selectors.

**Minimal reproduction of the problem with instructions**
Broken version (without any additional selectors): 
http://plnkr.co/edit/cD0WAYY1nV2dU0pkWDjJ?p=preview

Working version (additional selectors needed): 
http://plnkr.co/edit/isydjF86jUlVhB3rHm1Y/?p=preview

See `<li>` items - in first example, first `<li>` is empty, but it is there. `<ng-content>` is not properly projected. In second example, both `<li>` items have properly projected `<ng-content>`.

* **Angular version:** 4.1.X

* **Browser:** [all]

 
* **Language:** [TypeScript]

**Comment by vicb** [comment]
`<ng-content>` uses static (compile time) projection and is not updated at runtime

**Comment by klinki** [comment]
@vicb Hmm ok, could you please explain why second example works, but first one doesn't?

**Comment by klinki** [comment]
@vicb @mhevery @tbosch @jasonaden Could anyone of you please look at these plunks? I'm probably doing something wrong, but that behavior seems very suspicious to me and I think there really is some bug in it.

**Comment by tbosch** [comment]
@klinki binding to `select` of `<ng-content>` is not supported, as we evaluate it during compilation. However, we should give a better error message... Created https://github.com/angular/angular/issues/16593 to track this.

**Comment by klinki** [comment]
@tbosch I now encountered problem with `<ng-template>` not working with `<ng-content>`. Is it related to the same problem, not evaluating `select` of  `<ng-content>` during compilation?

```html
<ng-content select="[something]"></ng-content>
```

This doesn't work

```html
<ng-template something>
<button>A</button>
<button>B</button>
</ng-template>
```
This works

```html
<div someting>
<button>A</button>
<button>B</button>
</ng-template>
```

(to be honest I still don't understand it much, but I don't have any other option then accept it as it is...)
