### ISSUE TITLE
wrong email validation 

### ISSUE THREAD

**Issue by ElWardi** [angular/angular#16544]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**

Email validator does not work properly. It validates emails without host domain. 
Currently *me@host* is validated to `true`
**Expected behavior**

`me@host` should not validate, 
`me@host.domain` should validate. 

**Minimal reproduction of the problem with instructions**

Issue appears to be in the `EMAIL_REGEXP` , at `packages/forms/src/validators.ts` `line 45`
```
const EMAIL_REGEXP =
    /^(?=.{1,254}$)(?=.{1,64}@)[-!#$%&'*+/0-9=?A-Z^_`a-z{|}~]+(\.[-!#$%&'*+/0-9=?A-Z^_`a-z{|}~]+)*@[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$/;
```
* **Angular version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by pkozlowski-opensource** [comment]
Actually `me@host` _is_ a valid e-mail address: http://stackoverflow.com/questions/20573488/why-does-html5-form-validation-allow-emails-without-a-dot

**Comment by edmundo096** [comment]
Maybe this should be reopened?
The (not very useful) white space email (`" "@example.org`) is marked as invalid by this regex.

But as this comments says, it _should_ be valid: http://stackoverflow.com/questions/20573488/why-does-html5-form-validation-allow-emails-without-a-dot#comment63780880_28124678
I don't mind about it.

Maybe various Regex could be provided, with the option of selecting the restrictiveness in this/any other email validating directive.

**Comment by zinzinday** [comment]
That is valid email on HTML5 but i think, we need implement an argument to code faster
example: `Validators.email(dotted: boolean = false)` . If reactive model we can using attribute `pattern`

**Comment by NYAZAK** [comment]
But if It validates emails without "@" like monemail ?
