### ISSUE TITLE
Problem with form

### ISSUE THREAD

**Issue by 1heg0d** [angular/angular#16543]
Hi!

I found the problem, and I don't understand, this is an Angular problem or something else.
When I use the **Object.assign function({}, obj)** for the copy object, it doesn't copy object from **form**.
Any changes to the copied object change the original object.

You can see the problem in this [plunker example](https://plnkr.co/edit/eYl1e8z3360gxoPqIKwY).

Try to "Edit" someone from "User". You'll see that the changes you made changed the original "User".

Best regards.

**Comment by mlaval** [comment]
`Object.assign` doesn't deep clone, more details here: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
