### ISSUE TITLE
feat. request: allow inheritance (abstract class constructor)

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular#16566]
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Current behavior**
I want basic inheritance concept: 
```
export abstract class AbstractForm{
 abstract data;
 constructor(protected dialog: DialogService){}
}
//then use it in component
@Component({
  selector: 'abc',
  template: '...'
})
export class AbcComponent extends AbstractForm{
 data = {}
// here I don't want create same constructor one more time and call super(dialog) 
}
```
But here I get error:

> Uncaught (in promise): Error: Can't resolve all parameters for AbcComponent : (?).
> Error: Can't resolve all parameters for AbcComponent : (?).

I don't have error with language-service and in my webstorm all seems correct, I only get this response directly when launch app in browser, even ng serve and ng build --prod works well, **BUT** even when I decorate my AbstractClass with `@Component({})` it doesn't works on build and angular language service tell me 

> Error:(9, 2) Angular: Component 'AbstractForm' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration

I don't want add this abstract class into ngModule because it's only an abstraction and I will never use it inside a template, while on dev mod it works (even if angular-language-service awar from this)

**Expected behavior**
I juste want avoid set consctructor again while I don't need specify other DI it's annoying to always add duplicate code in each component extending this AbstractForm:
```
constructor(protected dialog : DialogService) {
    super(dialog);
  }
```

**Minimal reproduction of the problem with instructions**
see above ( can't reproduce on plunkr)

**What is the motivation / use case for changing the behavior?**
avoid annoying duplication of code : i don't want call abstract constructor using super()... when on child I don't have one; simply use existant constructor wirted in abstract class

**Please tell us about your environment:**
win10, webstorm 2017.1.3

* **Angular version:**
```
@angular/cli: 1.0.2
node: 7.7.2
os: win32 x64
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1
@angular/language-service: 4.1.1
```
* **Browser:** [all]
* **Language:** [ts 2.3]

**Comment by RatkoR** [comment]
I got hit by this today. Don't know much about angular internals, so I though I'd ask: is this a major change (meaning that it will not be done) or something eventually someone could pick up.

**Comment by codethief** [comment]
I'm having the same issue.

> BUT even when I decorate my AbstractClass with @Component({}) it doesn't works on build and angular language service tell me
>
> >  Error:(9, 2) Angular: Component 'AbstractForm' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration
>
> I don't want add this abstract class into ngModule because it's only an abstraction and I will never use it inside a template, while on dev mod it works (even if angular-language-service awar from this)

Even if one *does* add it to the ngModule, this will then cause Angular's AOT compiler to complain about the fact that the base component is an abstract class:

> Type 'typeof MyBaseComponent' is not assignable to type 'Type<any>'.
> Cannot assign an abstract constructor type to a non-abstract constructor type.

**Comment by devoto13** [comment]
I think the problem is that there should be some Angular decorator, so compiler will collect the metadata from constructor. Wondering if putting `@Injectable()` on the abstract class will make it work without errors.

**Comment by codethief** [comment]
@devoto13 You mean, adding `@Injectable()` on top of `@Component()`?

**Comment by devoto13** [comment]
Nope, only `@Injectable()`. It will cause compiler to collect metadata on the class, but decorator itself does nothing (so should not cause any warnings or runtime implications).

**Comment by codethief** [comment]
But using `@Input` and `@Output` inside the abstract class still wouldn't be possible then, would it?

**Comment by basst314** [comment]
I had the same problem, but @devoto13 s proposal worked - i marked the abstract parent class as `@Injectable()` just like @trotyl wrote and compilation worked again.
Thanks everyone!

@codethief : I have not tried `@Input()` or `@Output()` yet.

**Comment by alalonde** [comment]
Verified that `@Input()`s and `@Output()`s work fine.  IMO this feature request is unnecessary as there are multiple workarounds.

**Comment by benelliott** [comment]
One caveat of annotating the abstract superclass with `Injectable()` is that any constructor parameters not recognised by the `Injector` (e.g. a boolean) will be flagged by the Angular compiler as an unresolved parameter:

```
 10% building modules 5/5 modules 0 activeWarning: Can't resolve all parameters for AbstractComponentSuperclass in [path-to-abstract-component-superclass]: ([object Object], ?). This will
 become an error in Angular v6.x
```

with

```
@Injectable()
export abstract class AbstractComponentSuperclass() {
    ...
    constructor(private someService: SomeService, private someBoolean: boolean) {}
    ...
}

```

**Comment by alxhub** [comment]
This is fully supported in Ivy via the abstract `@Directive()` annotation 👍
