### ISSUE TITLE
Parent component didn't realize child component initial update value.

### ISSUE THREAD

**Issue by everedifice** [angular/angular#16565]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Parent composent didn't realize that child component's form value at update initialize time.

**Expected behavior**
Parent and child component has same value.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/1MMpOYOKIouwnNc3uIuy

`NumComponent` update initial value to literal number 3 when `@Input() useThree` property is true.

But in this demo. despite of update value to 3 in `NumComponent`. `AppComponent` value is '' (empty string)

If i wrap update code with `setTimeout` then work well. but it is tricky and worry about other side effect problem.

**What is the motivation / use case for changing the behavior?**
For some case. I want use computed value. not directly passing initial form control value. 

**Please tell us about your environment:**
MacOS, spacemacs, npm

* **Angular version:** 2.0.X
4.1.0 (but this behavior caused also 4.0.1)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers where this could be reproduced
 
* **Language:** TypeScript 2.3.2

* **Node (for AoT issues):** `node --version` =   7.3.0

**Comment by alexzuza** [comment]
Template-driven forms are asynchronous. registerOnChange function is executed after you call this.updateValue within writeValue. NgModel doesn’t add a form control synchronously — it does it in a microtask(promise.then). You can only wait by scheduling another microtask like this

```
const resolvedPromise = Promise.resolve(null);
...
registerOnChange(fn: any): void {
  this.onChange = fn;
   if (this.useThree) {
    resolvedPromise.then(() => {
       this.num = 3;
       this.updateValue(3);
    })
    this.useThree = false;
  }
}
```

https://plnkr.co/edit/A4xBldIIj58fPFjzndEW?p=preview

**Comment by everedifice** [comment]
@alexzuza Thank you very much. I close this issue.
