### ISSUE TITLE
Router: ability to have optional children through CanActivate

### ISSUE THREAD

**Issue by dietergeerts** [angular/angular#16579]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm creating a dashboard for users with multiple roles, but only the parts that his/her roles has access to can be shown, because the resolves for those routes do BE calls that check this, so giving an error when you don't have the role. The logical thing to do for me was using child routes with empty paths + outlets, which can be done, but setting a CanActivate that check the role, so that when that child can't be activated, it will not be shown. BUT: when one of the guards returns false, none is shown.
```
function getRoutes(): Routes {
    return [
        {
            canActivate: [IsLoggedInGuard],
            children: [
                {
                    canActivate: [HasRoleAGuard],
                    component: ComponentForA,
                    outlet: 'componentForA',
                    path: '',
                    resolve: {
                        // ...
                    }
                },
                {
                    canActivate: [HasRoleBGuard],
                    component: ComponentForB,
                    outlet: 'componentForB',
                    path: '',
                    resolve: {
                        // ...
                    }
                }
            ],
            component: DashboardComponent,
            path: '',
            resolve: {
                // ...
            }
        }
    ];
}
```

**Expected behavior**
When one of the outletted childs CanActivate guards return false, it must not be shown AND doesn't affect the rest of the children/routes.

**What is the motivation / use case for changing the behavior?**
When having dashboard-like behaviour, where parts must be shown based on some condition, and by that, when a part isn't shown, the resolve will not be run, because they can only run when the route is activated, for avoiding errors from BE etc....

* **Angular version:** 2.4.X

**Comment by jasonaden** [comment]
Thank you for the suggestion. However, the router is designed such that recognizing the URL shouldn't depend on anything at runtime. If guards were involved, it would flip the sequence considerably and add significant confusion to how routing works.
