### ISSUE TITLE
Do you think there is need to change Angular name to something else?

### ISSUE THREAD

**Issue by vinodraut** [angular/angular#16577]
No doubt **Angular is best JS framework** available today, as like us many of the people using AngularJS as their main JS framework & we are continuously trying to upgrade to Angular.

While doing this there are lot of problems facing on the web while searching, as Angular is completely different from AngularJS but the name similarities creating lot of issues in result pages.

So I personally think it would be great if **Angular Team can rename this project to something else** which make it more identical & clear out any confusions with AngularJS.

**What do you think?**

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/14802

**Comment by matsko** [comment]
Closing this due to the existing issue.
