### ISSUE TITLE
Animation problem with Automatic property calculation

### ISSUE THREAD

**Issue by michel06** [angular/angular#16570]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using Auto Style, a state transition starting from 'expanded' state to 'collapsed' then 'expanded' before the 'collapsed' animation completed would result in a 'collapsed' pane.

**Expected behavior**

Have the same behavior when animation start with no race condition.

**Minimal reproduction of the problem with instructions**

https://embed.plnkr.co/g4I5QD6Z3b03G2J3CQdd/

**What is the motivation / use case for changing the behavior?**

Have the Automatic property calculation working as expected:
https://angular.io/docs/ts/latest/guide/animations.html#!#automatic-property-calculation

**Fix proposal**

Do not call "onDoneFns" on overlapping animations by either using an other destroy method or calling the WebAnimationsPlayer.reset method instead.

**Please tell us about your environment:**

Windows 7 64bits

* **Angular version:** 4.1.X

* **Browser:** Chrome 58

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v7.10.0

**Comment by matsko** [comment]
I will revisit this tomorrow once `4.2-rc.0` is out.

**Comment by michel06** [comment]
Release 4.3.6 fixed it!
