### ISSUE TITLE
Embedded source maps are broken

### ISSUE THREAD

**Issue by tsabirgaliev** [angular/angular#16576]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Sourcemaps accompanied with scripts contain wrong embedded sources of Angular. This breaks in-browser debugging.

**Expected behavior**

When I put a breakpoint in my component, I should be able to walk down the call stack and see the original TS source of Angular.

**Minimal reproduction of the problem with instructions**

PR #16574 adds scripts that show that most of the embedded sources don't match the actual framework source code.

**What is the motivation / use case for changing the behavior?**

It is critical to see the correct framework code during debugging, to understand NG better.

**Please tell us about your environment:**

MacOS, angular-cli, vscode

* **Angular version:** 4.x

reproduces in master

* **Browser:** Chrome

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v6.10.2

**Comment by IgorMinar** [comment]
We spent a lot of time fixing source maps in v5.0. The line numbers should now be correct but they point to JS files rather than TS files, so I'm leaving this issue open for now.

**Comment by IgorMinar** [comment]
Actually there is a better issue to track the remaining work: #19841
