### ISSUE TITLE
docs: toh-pt5 - add Router import line at "Update the HeroesComponent class" section

### ISSUE THREAD

**Issue by stemar** [angular/angular#16585]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
On the `toh-pt5.html` tutorial page, after we go through the section called "Update the HeroesComponent class", we get an error, either: "Can't resolve all parameters for HeroesComponent" or an error related to a missing Router module.

**Expected behavior**
The page refresh would display successfully the Top Heroes boxes in our local environment.

**Minimal reproduction of the problem with instructions**
At the section called "Update the HeroesComponent class", number 1 is:
```
1. Import the Router from the Angular router library.
```
and the box that displays: `src/app/heroes.component.ts (class)` doesn't show the entire file content which would include:
```
import { Router } from '@angular/router';
```
near the top of the file.

**What is the motivation / use case for changing the behavior?**
For a beginner, it's better to explicitly show the line:
```
import { Router } from '@angular/router';
```
for the correct syntax and the correct position of the line in the `heroes.component.ts` file to avoid the console error in the browser.

**Please tell us about your environment:**
Debian 8, npm 3.10.10

* **Angular version:** 2.0.X
v 4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
v 6.10.2

**Comment by wardbell** [comment]
We _tell_ you to add the import but, for brevity, we often omit the import statements in code snippets and this is an example of that policy.  Maybe it's not a great policy. But to change it, we'd have to change it everywhere.

The full download is always available for definitive clarification on this and other omissions.

While I'm sympathetic with your point of view, I'm closing because we are not changing out policy at this time.
