### ISSUE TITLE
AoT issue with CSS in JS integration to Angular because of error when setting @Component style attribute to a function

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/angular#16584]
**I'm submitting a ...**  (check one with "x")

[x] bug report
[ ] feature request
[ ] support request

**Current behavior**

Currently when you do this:

```
import { getStyles } from './util';

@Component({
  template: '<div></div>',
  styles: getStyles('foo')
})
export class MyComponent { }
```

and then run `ngc` you get the following error:

```
Error encountered resolving symbol values statically. Calling function 'getStyles', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
```

It does work if I bring the function into the component module and export it like this:

```
export function getStyles() {
  return ['somecss'];
}

@Component({
  template: '<div></div>',
  styles: getStyles()
})
export class MyComponent { }
```

But I can't import a function from somewhere else and use it here. Note that importing the `getStyles()` function and using it on the `styles` attribute does work without AoT. When I run my code in development it is just fine. So this is only a problem when I run `ngc` on my code.

**Expected behavior**

I should be able to set a function that returns a string array to the styles attribute in the component decorator. I understand that AoT needs to have certain constraints, but this function is pure and does nothing but return a static string. So, AoT should be able to evaluate the function and put the resulting static string into the optimized code that comes out of the AoT compiler.

**Minimal reproduction of the problem with instructions**

Look at code I put above. Only thing missing is the implementation of getStyles:

```
// in separate module
export function getStyles(name: string): string[] {
  return [`body { color: 'red' }`];
}
```

**What is the motivation / use case for changing the behavior?**

This is needed for doing CSS in JS for Angular. Here is a better example of how this would look which will make it clear why/how this would be used:

```
@Component({
    template: `
        <h1>Matias is the Man</h1>
        <subtitle>50 reasons why we all love yearofmoo</subtitle>
    `,
    styles: getStyles({
        h1: {
          color: 'green',
          'font-size': '40px'
        },
        subtitle: {
          'font-size': '10px',
          ...bigMargin,   // mixin
          ...underline     // mixin
        }
    })
})
export class MyComponent {

}
```

I am creating a library that will enable autocomplete and have various mixins. The idea is to leverage JavaScript inheritance/composition/etc. and have legit tree shaking for CSS.

**Please tell us about your environment:**

@angular/cli: 1.0.2
node: 7.9.0
os: darwin x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1
TypeScript 2.3.2

**Comment by tbosch** [comment]
So whether this works or not depends on the implementation of `getSize`: If `getSize` just has a `return` statement, this should work no matter where it is defined, as ngc will just inline it.

However, if `getSize` e.g. contains an `if` statement, then this fails in `ngc`, as we don't evaluate user code, only analyze it. 

Could you past the implementation of `getSize` here?

**Comment by jeffwhelpley** [comment]
Yo yo, word up, @tbosch. OK, so the implementation of the function in question does have somewhat complicated logic under the scenes as it calls a library function from https://github.com/blakeembrey/free-style

```
import { create } from 'free-style';

export function generateStyles(styles: Styles): string[] {
    const Style = create();
    Style.registerCss(styles);
    const stylesString = Style.getStyles();
    return [stylesString];
}
```

The issue is probably within the `free-style` library calls. I understand what you are saying about the compiler currently analyzing code and not evaluating it today. I am going to guess that this rule is in place in order to provide guarantees on performance and prevention of unwanted side effects, right? If that is true, then it makes sense....HOWEVER, this can be a powerful feature and I want to throw a couple ideas out at you which could jive well with `ngc` in the future:

Option 1 - ngc pre-processor
My `generateStyles()` function above is a pure function and it executes quickly. What about if I could somehow define a custom decorator or attribute that actually evaluates the function and sets `styles` to a static string output before `ngc` does it's thing?

Option 2 - setting `styles` with JSON
My ultimate goal here would be if we could give CSS in JS first class status by allowing anyone to set the `styles` attribute to a static JSON object. You could provide a hook for the JS to CSS string conversation provider. For example:

```
@Component({
  template: '<h1></h1>',
  styles: {
    h1: {
      fontSize: '10px',
      color: 'red'
    }
  }
})
```

All the work to convert this to a string is within `typestyle` and `free-style` with a very thin layer on top of it (my current implementation is just 4 lines of code).

So, which approach do you think would be best here? I want this to exist so I will help to implement this with whatever solution you think is most appropriate.

**Comment by jeffwhelpley** [comment]
@mgechev suggested on twitter to potentially use prepack in a webpack plugin to evaluate the function and turn it into a static string. That is a great idea that I will try out, but I would still be interested in hearing @tbosch's thoughts on option 2 because that is the ideal solution in the long run (i.e. in terms of developer ergonomics for something like this).

**Comment by tbosch** [comment]
Why `ngc` needs to be able to read the `styles` is because we do the style encapsulation already during compilation (for performance reasons, as it is a non trivial operation). For this to happen, we need to have the complete stylesheet.

Regarding Option 1 - ngc pre-processor:
Using a custom decorator does not work as ngc should not execute user code when compiling. E.g. if a malicious user had some virus in their decorator, they could now access your filesystem, ... as it would be running in node.js.

Regarding Option 2) - setting styles with JSON
This would require that Angular converts the JSON object into a css stylesheet as this is what we need eventually in the browser.

So I think the best way would be Option 3) - using a general purpose preprocessor:
- e.g. similar to sass that takes in a json object (e.g. based on file suffix `.css.js`) and produces a file `.css`. Then your components could refer to that generated file.
- e.g. you could plug this into the angular webpack plugin as well, so that the user could actually refer to the `.json` file in `styleUrl`.

**Comment by jeffwhelpley** [comment]
@tbosch thanks for the suggestions. I understand what you are saying about how `ngc` works. I think a general preprocessor that hooks into webpack also makes sense. One last question, though, and then you can feel free to close this issue:

Assuming I can create a general purpose preprocessor as a webpack plugin, how can I get the Angular Language Service to not complain about setting JSON as styles (or a function or whatever) in my IDE? I haven't found documentation for this, but is there something similar to `/* tslint:disable */ for the language service?

**Comment by tbosch** [comment]
No, not right now, sorry.

**Comment by jeffwhelpley** [comment]
OK, I will work around it for now. Thanks. I will close this.
