### ISSUE TITLE
Router: ability to listen to query param changes in resolves

### ISSUE THREAD

**Issue by dietergeerts** [angular/angular#16581]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In a resolve, we can get the current query params, but we can't listen to changes, like we can in a component.

**Expected behavior**
The ability to listen to query param changes in resolves

**What is the motivation / use case for changing the behavior?**
I use resolves to create a app state tree with observables, so each resolve will return an observable based on the route params, parent resolves, and in some cases the query params. I can then use the async pipe where I need the actual values from them, as then the BE call will be done. These observables must change in 3 ways:

1. When an action has been done, then an event is fired through an event emitter. The observables will listen to this event emitter, and if a certain event is fired that could cause a data change, the BE call will be done again.
2. Parent resolve changed. Some observables are using the parent resolve observable to flatmap further, so when the parent changes, they will change too.
3. When query params change, because some data will depend on them, like data that is bound to a date range for example. When we could listen to query param changes in resolves, I could put this in the observable chain, so the data will update automatically with the change

Number 3 doesn't work at the moment, so I would like to see the ability to get the query param observable inside the resolve function, so it can be used there.

* **Angular version:** 2.4.X

**Comment by tianyangj** [comment]
It seems "runGuardsAndResolvers" in "Routes" (https://angular.io/docs/ts/latest/api/router/index/Routes-type-alias.html) is what you are looking for?

"runGuardsAndResolvers defines when guards and resovlers will be run. By default they run only when the matrix parameters of the route change. When set to paramsOrQueryParamsChange they will also run when query params change. And when set to always, they will run every time."

**Comment by dietergeerts** [comment]
Nope, that's not the case, as the Observables don't have to be remade. An observable from such resolve will keep in mind the query params and active based on that.

I actually found a way, because of the queryParams being shared for all routes, you can do Router.routerState.root.queryParams, and put it into the observable chain.
