### ISSUE TITLE
FR: Textarea should support mdAutocomplete

### ISSUE THREAD

**Issue by KevinVillela** [angular/angular#16587]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
<md-input-container>
  <textarea mdInput [mdAutocomplete]="auto"></textarea>
</md-input-container>
<md-autocomplete #auto="mdAutocomplete">

Gives error:
Can't bind to 'mdAutocomplete' since it isn't a known property of 'textarea'.

**Expected behavior**
The ability to attach an autocomplete to a textarea, similar to how it is done with an input element.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/EwjoZPaxL766dQm8timK?p=preview

**What is the motivation / use case for changing the behavior?**
The main use-case is probably for inputs that can have comma-separated values, where each value should be autocompleted. The canonical example of this is the Drive sharing UI.

**Please tell us about your environment:**
Should be environment-agnostic, since it is reproducible on the plnkr.

* **Angular version:** 4.1.1

* **Browser:**  all - this is an FR for compilation time.
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
I guess you wanted to open it here: https://github.com/angular/material2

**Comment by KevinVillela** [comment]
D'oh thanks!
