### ISSUE TITLE
Uncaught ReferenceError: Map is not defined (Angular doesn't work for android 4)

### ISSUE THREAD

**Issue by TheRockstarGamer** [angular/angular#16596]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Uncaught ReferenceError: Map is not defined  on android browser see 

http://kangax.github.io/compat-table/es6/#test-Map <<< it's not compatible on jelly bean!

https://github.com/angular/angular/blob/910c0d9ee7e1f556f773e37e7385d5dd58ef79fd/packages/core/src/di/reflective_key.ts#L61

![screenshot_3](https://cloud.githubusercontent.com/assets/3116731/25769369/9e969bb6-3217-11e7-9f5b-f8699043fa34.png)

It seems like it's a new feature of 4.0

**Expected behavior**

It should work like it works on PC.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Android 4.4.2, Newest chrome

* **Angular version:** 4.X.X

* **Browser:** all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mhevery** [comment]
You need to have Map polyfill on old browsers. Try: https://polyfill.io/v2/docs/
