### ISSUE TITLE
Currency pipe is not working in compliance with the localization settings.

### ISSUE THREAD

**Issue by ankakusu** [angular/angular#16591]
**I'm submitting a**  bug report.

**Current behavior**

`USD 12,30`

**Expected behavior**

I configure the LOCALE_ID provider to the Dutch language on the app module level. 
My purpose it to use the currency pipe and have the number text converted to this:

`€ 12,30`

As mentioned on the [documentation for the currency pipe](https://angular.io/docs/ts/latest/api/common/index/CurrencyPipe-pipe.html), I expect
to see the currency sign rather than the currency code.

**Minimal reproduction of the problem with instructions**

I configure the localization at the app module level.

```
@NgModule({
  imports: [ BrowserModule ],
  declarations: [ AppComponent ],
  providers: [
    { provide: LOCALE_ID, useValue: 'nl' }
  ],
  bootstrap:    [ AppComponent ]
})

export class AppModule { }
```

I'm using the currency pipe on my component.

```
@Component({
  selector: 'my-app',
  template: '<h1>{{title}}</h1>' +
            '<div>{{convertNumber | currency}}</div>',
})

export class AppComponent {
   title = 'Currency Pipe Test';
   convertNumber = '12.30';
}
```

For the working example, please check this [plnkr link](https://plnkr.co/edit/0lh50OHED5d8CBEifEUW?p=preview).

**What is the motivation / use case for changing the behavior?**

Apparently, the localization file for Dutch language is wrong. I can't find the
location of this localization file. If I can, I would like to fix it.

**Please tell us about your environment:**
-

* **Angular version:** 4.0.X

* **Browser:** [all ]
 
* **Language:** [all |TypeScript ]

* **Node (for AoT issues):** `
v6.10.0

**Comment by Denfie** [comment]
Maybe you forgot to put the output correct.

```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: '<h1>{{title}}</h1>' +
            '<div>{{convertNumber | currency:\'EUR\':true:\'.2-2\'}}</div>',
})
export class AppComponent {
  title = 'Currency Test';
  convertNumber = '12312.30';
}
```
Here a fork of your [plnkr link](https://plnkr.co/edit/LoPX3vhLneHYqCrtsI2Q?p=preview).

I hope it helps.

**Comment by ankakusu** [comment]
@Denfie What is your suggestion if I want to implement several languages?

In addition to the i18n setup, do I need to write separate if/else statements to for currency?

**Comment by ocombe** [comment]
Hello, we are working on a full rewrite of the i18n pipes as they have a lot of issues due to the intl api that we use.
We will replace it with our own api which will give us more control over what we/you can output.

**Comment by bvamos** [comment]
Looks like it is not fixed in 5.0.3. I cannot see that function getLocaleCurrencyName is used somewhere in the pipe.

**Comment by ocombe** [comment]
The locale will only influence the way the number is formatted, it will never change the currency because €15 is always worth €15 in another locale.

**Comment by ocombe** [comment]
Ah yes, that's something else, there's an issue opened for that: https://github.com/angular/angular/issues/20385
