### ISSUE TITLE
input[date] changes reference to Date object

### ISSUE THREAD

**Issue by dg192** [angular/angular#1660]
I've created a jsbin to demonstrate what's happening.  Basically, it looks like the input[date] directive may be changing the reference to the Date object model.  This is on angular 1.3.15, and I'm able to reproduce in Chrome and Firefox.

http://jsbin.com/dexakuriro/4/edit

In the demo, if you click "update formDate" it will change the input[date] model and update the view in two places - one using $scope.formDate and the other returning $scope.formDate from a higher order function.  Once you interact with the date field, the reference seems to change, and the date captured in the closure is no longer the same as $scope.formDate.

Also, it doesn't look like the two-way binding of input[date] directive is working.  I didn't see any note of this in the documentation.  Does input[date] not support two way binding between the model and view?

**Comment by vicb** [comment]
This repo is for angular2, please reopen on https://github.com/angular/angular.js

**Comment by dg192** [comment]
Oops, sorry about that.  Will open at the other repo.
