### ISSUE TITLE
Cannot use braces when running localized application

### ISSUE THREAD

**Issue by jaska45** [angular/angular#16618]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have the following template
&lt;p i18n&gt;Special characters &amp;#123; &amp;#125; !&lt;/p&gt;

So my string is "Special charactes {}!"
When I compile this and run it correctly shows the string.

Then I run ng-i18n and it creates the .xmb file. It contains following:

&lt;msg id="..."&gt;Special characters { } !&lt;/msg&gt;

So the strings is extracted without escapes. Then I localize it

&lt;translation id="..."&gt;Special characters { } !&lt;/translation&gt;

When AOT-compiling I will get an error that { should be escaped as {{. Then I change the translation to

<translation id="...">Special characters {{ }} !</translation>

Now it compiles but when I run I get a runtime error that interpolation cannot be null.

I don't know what is wrong. It is either the original extracted &lt;mgs&gt; or then the compiler that consumes &lt;translation&gt; has a bug.

**Expected behavior**

Because none-localized application can have {} that should be possible in localized one too.

**Minimal reproduction of the problem with instructions**

Create the template I am using, extract strings and localize it.

**What is the motivation / use case for changing the behavior?**

To be able to localized strings that contains { and } but are not interpolation placeholders.

**Please tell us about your environment:**

Windows 10, Visual Studio Code 1.12.1, NPM 3.10.10

* **Angular version:** 2.0.X

Most recent (4.0.x)

* **Browser:** 

All

**Comment by dawidgarus** [comment]
Did You tried to escape braces like this: `{{'{'}}`?

**Comment by jaska45** [comment]
That works. Still it is a bit odd that you need to use interpolation to add { characters in your template. Actually you can add { if you use HTML encoding &#123; (as I used) but if you do that then it is impossible to localize the text. I still think that there is a bug in ng-i18n or AOT compiler that consumes the translationbundle.

**Comment by mhevery** [comment]
Sorry, Working as intended.

**Comment by jaska45** [comment]
How is it intended that way that there are some characters that you can not use in the templates if you are planning to localize. I think that all characters that are possible in the templates must be able to use in the resource files too.

Let me put it this way

1) You are writing an English only or Japanese only application
-> All characters are available.

2) You are writing a multilingual application
-> Suddenly some characters are not allowed.
