### ISSUE TITLE
aio: inline code looks like link; change text color

### ISSUE THREAD

**Issue by wardbell** [angular/angular#16610]
Link and inline code are both the same blue; light gray background of code is not always visible on monitors so  code looks clickable on some monitors.

None of the blue text items in the following image are clickable. The gray background is evident on my laptop. But on my home Samsung TV monitor, the gray background is white so _they all look clickable_.

![image](https://cloud.githubusercontent.com/assets/129061/25775095/fe31c2d2-3251-11e7-9c90-fcbee20a99cf.png)

**Comment by petebacondarwin** [comment]
What is the suggested alternative styling/colour?
