### ISSUE TITLE
1,246 issues, what a joke..

### ISSUE THREAD

**Issue by broros** [angular/angular#16613]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by ericmartinezr** [comment]
@vicb / @pkozlowski-opensource  please close

**Comment by mlc-mlapis** [comment]
Some of them are non-relevant but still not closed. Some not very good documented so it is hard to go through. Some are long-term things. Many under discussion ... in reality the number is not so high but it would be nice to decrease the number to ~ 500.

There is interesting number that for April build of VSC was closed 2199 issues. But by the same time 1925 new ones were opened. The result = they decreased the total number by 274 issues in that period. So the actual status is about 3775 issues.

**Comment by HarelM** [comment]
@broros the joke is on you :-P
Kidding, 
Keep up the good work guys! you make web development a happier journey.
