### ISSUE TITLE
Unable to get access to child elements from Webcomponent

### ISSUE THREAD

**Issue by chenthillrulz** [angular/angular#16622]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have an angular app where am using a webcomponents based on custom elements V0 specification. 

```
<cse>
  <div class="step">
      <!-- bunch of child elements -->
  </div>
</cse>
```

Unable to get access to child elements of custom element "cse" in attachedCallBack or createdCallBack (lifecylce callbacks of webcomponents custom element) in the webcomponent.

**Expected behavior**

Angular needs to provide a way for the webcomponent to access its child elements.

* **Angular version:** 4.0.X

**Comment by zoechi** [comment]
As the issue templates mentioned a Plunker is required that allows to reproduce.

**Comment by mhevery** [comment]
All issues must have a plunker (http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) repro case. Please open a new issue.
