### ISSUE TITLE
using isDevMode under a production builded  project throws Uncaught Error: Cannot enable prod mode after platform setup.

### ISSUE THREAD

**Issue by psaussure** [angular/angular#16628]
### I'm submitting:
```
- [x] bug report
- [ ] feature request
```

### Versions.

> node: 7.8.0
> os: win32 x64
> @angular/animations: 4.1.0
> @angular/common: 4.1.0
> @angular/compiler: 4.1.0
> @angular/compiler-cli: 4.1.0
> @angular/core: 4.1.0
> @angular/forms: 4.1.0
> @angular/http: 4.1.0
> @angular/platform-browser: 4.1.0
> @angular/platform-browser-dynamic: 4.1.0
> @angular/platform-server: 4.1.0
> @angular/router: 4.1.0
> @angular/cli: 1.0.1

### Repro steps.
In the app router module, try to set:

```
import { NgModule, isDevMode } from '@angular/core';

// Log all router events on dev environment
const ENABLE_ROUTER_TRACING = true;
if (!isDevMode()){
  const ENABLE_ROUTER_TRACING = false;
}
```
and 
 
`RouterModule.forRoot(routes,  {enableTracing: ENABLE_ROUTER_TRACING})`

**It seems the call of `isDevMode` somewhere within the main app module, before `enableProdMode()`  make the build fail.**

Is there any workaround to determine which is the current environment?

As soon as you then build this app containing this module, an error is triggered.

### The log given by the failure.

> vendor.5b5257b….bundle.js:225
> 
> Uncaught Error: Cannot enable prod mode after platform setup.

### Mention any other details that might be useful.
No error occurs at build time.

**Comment by mhevery** [comment]
Working as intended. `isDevMode` must be constant, hence once you call it it can't return a different value.
