### ISSUE TITLE
Angular's change detection Error (FormValidation)

### ISSUE THREAD

**Issue by gags88** [angular/angular#16620]
**I'm submitting a bug**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular change detection in Form Validation occurs before routing.

**Expected behavior**
Angular routing shall overtake the change Detection for form validations.

**Minimal reproduction of the problem with instructions**
1. Click on Go to Login
2. Place the cursor on Email address field.
3. Do not click anywhere else instead of Register Link at the bottom. Keep in mind that cursor shall still be in Email address field.
4. When you click on Register, then as per routing module, register page shall show up
5. But when you click on Register, then Validation occurs first not routing. 
6. The second click on the register will show up the register page.

Use Below Plunker to reproduce the issue
[Plunker URL-Click Here](https://plnkr.co/edit/IyJDVOLQb1V9VBp1QxT0?p=preview)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
MACOS, Web Storm, npm, Lite Server(ng serve)

* **Angular version:** 2.0.X

* **Browser:** [all]

 
* **Language:** [all]

**Comment by alexzuza** [comment]
When you click on link `blur` event is fired on input and it is running validation. Validation message is added to dom and you `link` jumps down. So `click` event doesn't happen on link

To prevent this behavior you can do some trick

`<a routerLink="/register" id="login_id" (mousedown)="false">Register</a>`
https://plnkr.co/edit/cVw1jJzvOYAQ8EtKFMzK?p=preview

**Comment by gags88** [comment]
Thanks alexzuza.. it works now.
But just curious to know if it works as intended or considered as bug..

**Comment by Toxicable** [comment]
@gags88 That's just how a click event works, it's made up of a `mousedown` + `mouseup` events

**Comment by gags88** [comment]
@Toxicable ... If you mean that i shall move register link only because it works then that is not true and can you please explain your line `where it will not move like so` ... I have even tried placing link out of form and even then it fails. Only `(Mousedown)=false` worked for me.

And i do know that click event is `mousedown` + `mouseup` ...

But this thing does not happen in simple jQuery/Javascript solution, then why only in Angular

**Comment by Toxicable** [comment]
>can you please explain your line `where it will not move like so`
Look at this plunkr: https://plnkr.co/edit/FUXs7VLc8WdGUhIJUtiZ?p=preview
I move the register link so that it wont be moved by the validation and it works how you think it would work

**Comment by mhevery** [comment]
This should be resolved. If still in issue open new.
