### ISSUE TITLE
Relative path would be better in source element/attribute

### ISSUE THREAD

**Issue by jaska45** [angular/angular#16639]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When ng-i18n extract strings it adds source element that contains the source code and line where the strings was extracted. This is very good.

However the extracted source code file is absolute.

`<msg id="1238358838717941284"><source>D:/Source/Angular/Escape/src/app/app.component.ts:2</source>Sample</msg>
`

Would be better to have relative to the project root

`<msg id="1238358838717941284"><source>src/app/app.component.ts:2</source>Sample</msg>
`

This would make it easier to move the project into different location. It might also be the different developers or localization enginerrs have different local directory structures.

**Expected behavior**

Use relative path.

`<msg id="1238358838717941284"><source>src/app/app.component.ts:2</source>Sample</msg>
`

In addition it would be better to store source into an attribute instead of source element inside the string playload.

`<msg id="1238358838717941284" source="src/app/app.component.ts:2">Sample</msg>
`

**Minimal reproduction of the problem with instructions**

Extract any template

**What is the motivation / use case for changing the behavior?**

Make localization easier.

**Please tell us about your environment:**

Windows 10, VS code 1.12.1

* **Angular version:** 4.0.X

* **Browser:** all

**Comment by ovidiubarbu** [comment]
Relative path usage and attribute use for file location, will make the output closer to other files used in Localization, like XLIFF, and will be easier to digest by users.

**Comment by POEditor** [comment]
Hi guys,

We, at [poeditor.com](https://poeditor.com), were among the first to implement XMB/XTB support (and I think we're still the only localization service to support it).
When deciding on the structure of the files, please consider the backwards compatibility. Changing the format so often drives away the users that trusted it and used it in their applications.

PS: the lack of documentation doesn't help either.

Adrian

**Comment by ocombe** [comment]
@POEditor don't worry, the source element won't move to an attribute for xmb/xtb, the spec is clear about where it should be. Also sorry but you're not the only ones to support it, textunited.com support it well too (even better if I remember correctly because they handle placeholders better).

**Comment by POEditor** [comment]
Thank you.
Can you point us to the specs of the XTB / XMB formats?

**Comment by ocombe** [comment]
I don't think that there is anything public available except for http://cldr.unicode.org/development/development-process/design-proposals/xmb that you already know. I'll ask around.

**Comment by ocombe** [comment]
@POEditor I've asked the i18n team at google, there's no official spec, except for the dtd at the beginning of the xmb/xtb files (if you can call this a spec...)

**Comment by Tryptich** [comment]
Hi @ocombe , what is the point about relative path ?

**Comment by ocombe** [comment]
if you mean what's the status, nothing yet

**Comment by Tryptich** [comment]
OK.
