### ISSUE TITLE
Importing AngularJS app after Zone.JS makes AngularJS "not found" when bootstrapping

### ISSUE THREAD

**Issue by AntJanus** [angular/angular#16633]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using CommonJS (or ES2015 modules), the order of imports matters when importing an AngularJS app to bootstrap. Here is an example Plunkr that demonstrates the problem: https://plnkr.co/edit/lKE6a3sPqjMWvoWJF9oT?p=preview

But basically:

When AngularJS lives in: `app.js` like this one:

```js
import * as angular from 'angular';

export default angular.module('app', [])
  .run(function() { console.log('Angular 1 is running!')})
```

and Angular lives in `main.ts` like this one:

```ts
import 'core-js/es7/reflect';
import 'zone.js';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { UpgradeModule } from '@angular/upgrade/static';
import { AppModule } from './app.module';

import app from '../app/app';

const platform = platformBrowserDynamic();
platform.bootstrapModule(AppModule).then(platformRef => {
  const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
  upgrade.bootstrap(document.body, [app.name], { strictDi: true})
})
```

The bootstrap will fail with:

```
Unhandled Promise rejection: AngularJS v1.x is not loaded! ; Zone: <root> ; Task: Promise.then ; Value: Error: AngularJS v1.x is not loaded!
```

However, moving `import app from './app'` before `zone.js` import, the bootstrap will work

**Expected behavior**
Importing an AngularJS app should work after the main dependency imports like `zone.js` and `reflect` and other libraries.

**Minimal reproduction of the problem with instructions**
Here is the Plunkr: https://plnkr.co/edit/lKE6a3sPqjMWvoWJF9oT?p=preview

The code above also recreates the problem

**Please tell us about your environment:** Windows 10, VSCode, Webpack bundling (SystemJS fails as well).

* **Angular version:** Angular 4.1.0 and AngularJS 1.6.4

* **Browser:** all
 
* **Language:** TypeScript

**Comment by mhevery** [comment]
This works as expected. When AngularJS is loaded as `import * as angular from 'angular'` then there is no `window.angular` created. Hence the bootstrap code thinks that angular is not loaded. 

Here is a potential fix? https://plnkr.co/edit/Z37dAfocW7WVVpOwFG05?p=preview

**Comment by gkalpak** [comment]
Duplicate of #16484. See https://github.com/angular/angular/issues/16484#issuecomment-298852692 for more info.

**Comment by AntJanus** [comment]
@mhevery ahh, that may be a worthwhile addition to the guide since there is no mention of needing `window.angular` to be present (or using my workaround of importing before zone.js).

Still, importing the AngularJS app before importing zone.js solves the issue. I checked the app in production and it looks like AngularJS automatically attaches itself to the `window` despite being bundled; however, if that happens after `zone.js` is imported, it doesn't detect it.

That was the crux of my issue.

@gkalpak ahh! Thank you!
