### ISSUE TITLE
docs: core API - missing documentation for HostBinding

### ISSUE THREAD

**Issue by aiboy** [angular/angular#16634]
Right now the page is empty
https://angular.io/docs/ts/latest/api/core/index/HostBinding-interface.html

It's really confusing since HostBinding is used in other parts of documentation but it's never explained what it dose exactly.

Where can I find contribution guide for documentation to make pull request?

**Comment by tytskyi** [comment]
@aiboy meanwhile you can check it's usage in https://angular.io/docs/ts/latest/guide/cheatsheet.html

`@HostBinding('class.valid') isValid;`

> Binds a host element property (here, the CSS class `valid`) to a directive/component property (`isValid`).

**Comment by aiboy** [comment]
@tytskyi Tnx, but it's not the point here. I know what it dose, but a lot of newcomers complain about this because documentation uses this interface in a lot of places but never explains how it works. Looking for it in "cheatsheet" is counter intuitive.

**Comment by pkozlowski-opensource** [comment]
We've got it now here: https://angular.io/api/core/HostBinding
