### ISSUE TITLE
Translated resource files cannot have source element

### ISSUE THREAD

**Issue by jaska45** [angular/angular#16638]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I run ng-i18n it creates .xbm file that has source element

`<msg id="1238358838717941284"><source>D:/Source/Angular/Escape/src/app/app.component.ts:2</source>Sample</msg>
`

If I translate those and keep the source element line

`<translation id="1238358838717941284"><source>D:/Source/Angular/Escape/src/app/app.component.ts:2</source>Esimerkki</translation>
`

When I compile  I get a compilation error

`
ERROR in xtb parse errors:
Unexpected tag ("[ERROR ->]<source>D:/Source/Angular/Escape/src/app/app.component.ts:2</source>Sample"): i18n@0:0

`

If I remove the source element then compilation works.

`<translation id="1238358838717941284">Esimerkki</translation>`

**Expected behavior**

Compilation should work even if the source elements is there.

**Minimal reproduction of the problem with instructions**

Create a project. use ng-i18n to extract .xmb. Translate it to any language and keep the source elements.

**What is the motivation / use case for changing the behavior?**

Make localization easier.

**Please tell us about your environment:**

Windows 10, VS code 1.12.1

* **Angular version:** 4.0.X

* **Browser:**  all

**Comment by vicb** [comment]
See my comment on the PR.

`source` is not allowed per xtb DTD.

@ocombe why do you this this is valid ?

**Comment by vicb** [comment]
closing as `source` is not valid in xtb
