### ISSUE TITLE
aio: decide what to do about whether to display "pure" tag on Pipes

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16641]
The Pipes API docs contain information about whether the Pipe is pure or not.
We need to decide if this should be displayed in the doc, and if so how.

**Comment by IgorMinar** [comment]
Let's not display it for now. Pipe purity is an implementation detail that shouldn't be important to the reader.

if we realize that somehow that information should be surfaced, we'll deal with it then.
