### ISSUE TITLE
Async call inside before each breaks next async calls in specs

### ISSUE THREAD

**Issue by Sergeon** [angular/angular#16647]
**I'm submitting a ...**  
```
[x ] bug report
```

There is [this open issue](https://github.com/angular/angular/issues/12115) which seems to reveal the same behavior, but no direct mention to `beforeEach` is made until the last comment.

**Current behavior**

From a fresh angular-cli `ng new` install, with `angular-cli1.0.0` and `Angular4.0.0`,  a call to `async` inside the `beforeEach` hook makes next `async` calls within `it` funcitons to behave incorrectly, making an asynchronous ad hoc failing `expect` to just pass:

```typescript
describe('an async invocation inside jasmine beforeEach breaks async inside specs' , () => {

  beforeEach( async( () => {} ) );

  it('this should fail, but it doesn\'t' , async(() => {
    setTimeout( () => {
      expect(false).toBe(true);
    } , 100 );
  }));
});
```
This test pass, like `async` was not doing it's job.
 Instead, if you get rid of the `async` call within `beforeEach`, it fails as expected.

**Expected behavior**

The same test should fail with an *expected false to be true* message.

**Minimal reproduction of the problem with instructions**
+ create a new angular project with angular-cli using: `ng new`
+ create an asynchronous spec calling `async` both in the `beforeEach` hook an in a spec.

Also, I set up a [repo you can clone to check this fast](https://github.com/Sergeon/Angular-beforeEach-async-issue-demonstration).

**Please tell us about your environment:**
Mac Os 10.11.16

* **Angular version:** 4.0.X

Using 4.1.x, which is the latest at the moment as far as I know, also shows this behavior.

* **Browser:** [Chrome XX | Firefox XX ]
Chrome and Firefox from `karma.conf.js`. Didn't test other browsers.
 
* **Language:** [TypeScript 2.2.0]

**Possible current fixes**

As is stated [in this other issue](https://github.com/angular/angular/issues/12115), replacing `async` for `fakeAsync` inside the `it` calls would do the trick. 

However, `fakeAsync` has its own limitations (can't perform xhr requests) and **I believe `async` should be able to work properly in a spec regardless it has been called in the `beforeEach` hook or not.** If this is not agreed, at least, this *weird* behavior should be explicitly mentioned in the `async` api.

**Comment by willwsharp** [comment]
Having this same problem too, hopefully there's an update soon.

**Comment by fallXone** [comment]
Would like some more communication on this topic, as we have the same issue. We have over 6,000 unit tests and due to this issue, it intermittently causes our test runs to fail due to asynchronous work occurring while a completely unrelated test is running. We've used async on all of our beforeEach's as a standard, and I'm questioning if we even need to be doing this at all, but regardless, this is still a bug. Having an extra async shouldn't hurt anything, it's just an added safety net.

**Comment by omnibrain** [comment]
How is such a severe bug still open since 2017, and how are not more people complaining about this here? This increases my suspicion that most Angular projects aren't actually unit-tested.

**Comment by JeanMeche** [comment]
I've tested following with success. 

```
describe('an async invocation inside jasmine beforeEach breaks async inside specs' , () => {

  beforeEach( fakeAsync( () => {} ) );

  it('this should fail, but it doesn\'t' , fakeAsync(() => {
    setTimeout( () => {
      expect(false).toBe(true);
    } , 100 );
    flush();
  }));
});
```

`fakeAsync` works fine, here `flush` is required because of the pending timer.
