### ISSUE TITLE
docs(di): the `NoAnnotationError` link is invalid

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16640]
https://github.com/angular/angular/blob/c5ce0408a130fa7ca64d7cf7c3aa6d253f37d9aa/packages/core/src/di/metadata.ts#L130

This link is to a document for an API item that is not exported as part of the public API for Angular.

Actually with its current casing it is not valid at all. But if you lower case the first letter: `noAnnocationError` there is a function but it is not part of the public API.

Shall we remove the link, rewrite the doc, add the function to the public API???

**Comment by IgorMinar** [comment]
Such error class doesn't exist. Can you please send a PR to remove the link. Just say that an injector will throw an error.
