### ISSUE TITLE
angular2 PageNotFound always displayed instead of routes requested

### ISSUE THREAD

**Issue by ovione** [angular/angular#16648]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I add a PageNotFound route at the end of my routes it always matches it even if there is a matching route.
When I take the PageNotFound  route out it works

**Expected behavior**
It shouldn't match the PageNotFound route because the main/home is declared before.

Is it because there is a Guard in the main route ?
Is it because my main/home is lazy loaded ?
Why when I take the PageNotFound  route out it works and it gets to the main/home route ?

**Minimal reproduction of the problem with instructions**
When I access

http://localhost:3000/main/home

then I get redirected to the PageNotFoundComponent instead of going to the main/home route. When I take out the PageNotFoundComponent it works. Here is my code:

My AppRoutingModule

const routes: Routes = [
  { path: 'notloggedin', component: NotLoggedInComponent },
  { path: '', redirectTo: '/main/home', pathMatch: 'full' },
  { path: '**', component: PageNotFoundComponent }
];

My MainRoutingModule

const routes: Routes = [
  { path: 'main',
    component: MainComponent,
    canActivate: [ LoggedinUserGuard ],
    children: [
      { path: 'home', loadChildren: 'app/home/home.module#HomeModule'},
      { path: 'about', loadChildren: 'app/about/about.module#AboutModule'},
      { path: 'table', loadChildren: 'app/table/table.module#TableModule'},
      { path: 'user', loadChildren: 'app/user-list/user-list.module#UserListModule'},
    ]
  },
];

If someone could help it would be great thanks

**What is the motivation / use case for changing the behavior?**
**Please tell us about your environment:**
@angular/cli: 1.0.2
node: 7.9.0
os: win32 x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.0

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ovione** [comment]
I thought it was a bug and after reading the documentation I realized its not.
I thought its worth mentioning it anywyas here in case someone falls on this same problem.

The answer is in https://angular.io/docs/ts/latest/guide/router.html#!#heroes-feature

I was importing in my app.module the MainModule containing the MainRoutingModule like this:
@NgModule({
  imports: [
    .......
    AppRoutingModule,
    MainModule 
  ],

the correct way is:
@NgModule({
  imports: [
    .......
    MainModule 
    AppRoutingModule
  ],

for the reasons explained in in https://angular.io/docs/ts/latest/guide/router.html#!#heroes-feature


cheers
O
