### ISSUE TITLE
Reactive forms and bootstrap's radio buttons

### ISSUE THREAD

**Issue by ismcagdas** [angular/angular#16642]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm trying to use bootstrap's radio button group with angular's reactive forms and it seems like it is not working with bootstrap's radio button group.
I have used bootstrap 3.3.7 and jQuery 3.1.1.
When you exclude both libraries from following plunkr, it works but when you include them it does not.
I tried to figure it out but couldn't find the reason by myself. Any help would be really appriciated.

**Expected behavior**
In the following plunkr, when I change the selected button, I expect to handle valueChanges of formGroup.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/HyrZDs?p=preview

Thanks.

**Comment by tytskyi** [comment]
@ismcagdas

Why do you need jQuery and Bootstrap.js? 

Would one of those "native to angular" libraries fit your needs? 
- http://valor-software.com/ngx-bootstrap
- https://ng-bootstrap.github.io

Wiring up original Bootstrap.js to Angular would be the real adventure 🙂

**Comment by mhevery** [comment]
Sorry we don't support jQuery and boostrap as such. Please have a look at https://github.com/ng-bootstrap/ng-bootstrap instead.

**Comment by ismcagdas** [comment]
Thanks a lot for the information.
