### ISSUE TITLE
HTTP headers are being converted to lower case

### ISSUE THREAD

**Issue by waincent** [angular/angular#16651]
**Current behavior**
`new Promise((resolve, reject) => {
      let search = new URLSearchParams();
      search.set('grant_type', 'password');
      search.set('username', userName);
      search.set('password', password);

      let clientCredentials =  base64.encode(this.clientId + ':' + this.dummyClientSecret);

      console.log(clientCredentials);
      let headers = new Headers();
      headers.set('Content-Type', 'application/json;charset=UTF-8');
      headers.set('Authorization', 'Basic '+ clientCredentials); //Basic YWRtaW46MTIzNDU2

      let options = new RequestOptions({ headers: headers, params: search });

      this.http.post(this.tokenEndpoint, options).map(r => r.json()).subscribe(
        (tokenResponse) => {
          console.debug('tokenResponse', tokenResponse);
          this.storeAccessTokenResponse(tokenResponse.access_token, tokenResponse.refresh_token, tokenResponse.expires_in);

          resolve(tokenResponse);
        },
        (err) => {
          console.error('Error performing password flow', err);
          reject(err);
        }
      );
    });`

**Expected behavior**
`{
  "access_token": "850b3575-4776-49c9-a2d1-487370010418",
  "token_type": "bearer",
  "refresh_token": "ffa10b3f-eaa5-4afd-b268-f5fb3f100c3d",
  "expires_in": 80503,
  "scope": "read"
}`

**Minimal reproduction of the problem with instructions**
in Java Spring Security Oauth2 ==> org.springframework.security.web.authentication.www.BasicAuthenticationFilter ==>doFilterInternal method

`String header = request.getHeader("Authorization");
`
**What is the motivation / use case for changing the behavior?**
the headers converted the [Authorization] to [authorization], can't not get the Authorization param.

**Please tell us about your environment:**

WebStorm

* **Angular version:** 2.0.X
`"@angular/common": "^4.1.1"`

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 59
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by trotyl** [comment]
> Each header field consists of a case-insensitive field name followed by a colon (":") ...

https://tools.ietf.org/html/rfc7230#section-3.2

HTTP header name is case-insensitive, if some implementation depends on the specific case of a header name, then it's violating the HTTP standard.

**Comment by zoechi** [comment]
See also 
- #6142 (continued in the now removed http repo)
- #8831 (continued in the now removed http repo)
- #10290
- #11624

**Comment by waincent** [comment]
Thank you, I have found the cause of the problem.
[https://spring.io/blog/2015/01/20/the-resource-server-angular-js-and-spring-security-part-iii#cors-negotiation](url)
