### ISSUE TITLE
Context binding error on service if provided in both parent and child module

### ISSUE THREAD

**Issue by SherlockStd** [angular/angular#16652]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Service's method can't access the service attribute when called from a child component of ChildModule with `this` if the service is declared in the providers array of AppModule and ChildModule.

**Expected behavior**
An error need to spawn to warning the duplicated declaration of the service. Because without this error I searched for 3 days where was the problem in my service /or/ my component trying everything but nothing was working, then I just removed the service from my ChildModule and it was working fine.

**Minimal reproduction of the problem with instructions**
I tried to make a [Plunker](http://plnkr.co/edit/kRyrAZm3jG0OIffqiZ3x?p=preview), but I can't manage to setup the router on it, so it's not representative because it seems we need to load the sub-module with the router loadChildren method.

You can see the code issuing this problem on my Github here (protected branch): https://github.com/SherlockStd/ME4N-Starter/tree/this-error/src/app

Here is the main structure of the files:
```
src/
├── app.component.html
├── app.component.ts
├── app.module.ts <== provide AuthenticationService
├── app.routes.ts <== load authentication.module with router.loadChildren()
│
├── +authentication/
│   ├── authentication.component.html
│   ├── authentication.component.ts
│   ├── authentication.module.ts <== provide AuthenticationService
│   ├── authentication.routes.ts <== expose a route to login component
│   └── login
│       ├── login.component.html
│       └── login.component.ts <== using service's methods here don't work
│
└── shared/
    └── services/
        ├── authentication.service.ts
        └── base.service.ts
```
What I mean by `login.component.ts <== using service's methods here don't work` is that the service is unable to set his own attributes, it can read them but can't write.

If we provide `AuthenticationService` only in `app.module.ts`, instead of both `app.module.ts` and `authentication.module.ts` (), the problem is solved.

**What is the motivation / use case for changing the behavior?**
If something like this break the context, we need to display an error explaining why.

**Please tell us about your environment:**
Ubuntu 16.10, VSCode, yarn 0.23.4

* **Angular version:** 4.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript 2.3.2 compiling to ES5 (with AoT for prod)

* **Node (for AoT issues):** 7.10.0

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by SherlockStd** [comment]
This is not a support issue, this is actually a bug
