### ISSUE TITLE
Errors from Observable.throw() in catch operator in subscriptions without onError handler should appear in the browser's console

### ISSUE THREAD

**Issue by olgamelnichuk** [angular/angular#16650]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Current behavior**

If using Observable.catch operator and returning Observable.throw(...) from it, the updated error is not shown in the browser's console when subscription's onError handler is missing.

**Expected behavior**

When Observable.catch operator returns Observble.throw(...) then the corresponding error shoud appear in the browser's console if service subscription doesn't specify onError handler.

**Minimal reproduction of the problem with instructions**

<hello.service.ts>
...
hello(): Observable<any> {
    return this.http.get('/hello').catch(error => Observable.throw('an error'));
}
...
<hello.component.ts>
...
this.helloService.hello().subscribe(res => { ... });
...
'an error' is not shown anywere.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Mac OS X 10.10.5, @angular/cli 1.0.2, ng serve, rxjs 5.3.1, zone.js 0.8.4
* **Angular version:**  2.4.10 or 4.1.1

* **Browser:** Chrome Version 58.0.3029.96 (64-bit)

* **Language:** TypeScript 2.3.2
* **Node (for AoT issues):** `node --version` =   v6.10.3

**Comment by jasonaden** [comment]
I'm sorry but this issue is not caused by Angular. Please contact the author(s) of RxJS or file issue on their [issue tracker](https://github.com/ReactiveX/rxjs/issues).
