### ISSUE TITLE
http.request does not care about options parameter when url is of type Request and not string.

### ISSUE THREAD

**Issue by alexanderbaran** [angular/angular#16659]
I'm submitting a bug report when calling http.request.

`request(url: string|Request, options?: RequestOptionsArgs): Observable<Response>`

**Current behavior**
The `options?: RequestOptionsArgs` parameter seems to be ignored if the `url: string|Request` parameter is of type Request and not string. If it is type Request then this overrides any headers set on the optional options parameter.

**Expected behavior**
The `options?: RequestOptionsArgs` parameter should override Request's own options. If headers are set with options? they should be merged with headers set in Request.

**Minimal reproduction of the problem with instructions**
```
const optionsArgs: RequestOptionsArgs = {
    method: RequestMethod.Get,
    url: '/api/test'
};
const options = new RequestOptions(optionsArgs);
const request = new Request(options);

const optionsWithHeaders: RequestOptionsArgs = { headers: new Headers({'Content-Type': 'application/json'}) };

this.http.request(request, optionsWithHeaders)
    .subscribe(
        (response: Response) => {
            const body = response.json();
            console.log(body);
        }
    );    
```

Headers are not updated here.

* **Angular version:** 2.0.X
Angular version: 2.4.2

* **Browser:** 
Chrome: Version 58.0.3029.96 (64-bit)

**Comment by trotyl** [comment]
I guess it's by design (just a guess), maybe it's better to change the union type API:

```typescript
request(url: string|Request, options?: RequestOptionsArgs): Observable<Response>
```

to overloads:

```typescript
request(url: string, options?: RequestOptionsArgs): Observable<Response>
request(request: Request): Observable<Response>
```

**Comment by echonax** [comment]
I think this issue has been fixed here http://stackoverflow.com/q/43877015/5706293 :)

**Comment by jasonaden** [comment]
Please refer to the [docs here](https://angular.io/docs/ts/latest/api/http/index/Http-class.html#!#request-anchor) which specify that `RequestOptions` is optional if the first argument is a URL string.
