### ISSUE TITLE
Angular 2 Error “Uncaught ReferenceError: module is not defined” in systemjs-angular-loader.js

### ISSUE THREAD

**Issue by lvasilev1** [angular/angular#16661]
I'm submitting a [x] bug report.

**Current behavior**
I am trying to use Angular 2 in the same app as Angular 1. To accomplish that I am using the Angular UpgradeModule. To install and set-up TypeScript and Angular 2, I've used the following guide: [https://angular.io/docs/ts/latest/guide/upgrade.html#!#making-angular-dependencies-injectable-to-angularjs](url)

My tsconfig.json looks like this:

> {
"compilerOptions": {
"target": "es5",
"module": "umd",
"moduleResolution": "node",
"sourceMap": true,
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"lib": [ "es2015", "dom" ],
"removeComments": false,
"noImplicitAny": false,
"suppressImplicitAnyIndexErrors": true,
"typeRoots": [
  "../../node_modules/@types/"
],
"types": [
  "core-js"
]
},
"compileOnSave": true,
"exclude": [
  "node_modules/*",
  "**/*-aot.ts"
]
}

And my systemjs.config.js:

> (function (global) {
System.config({
paths: {
  // paths serve as alias
  'npm:': '/node_modules/'
},
// map tells the System loader where to look for things
map: {
    // our app is within the App/Angular2 folder
    'app': '/App/Angular2',

  > // angular bundles
  '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
  '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
  '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
  '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
  '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
  '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
  '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
  '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
  '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',

  > // other libraries
  'rxjs':                      'npm:rxjs',
  'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
},
// packages tells the System loader how to load when no filename and/or no extension
packages: {
  app: {
    defaultExtension: 'js',
    meta: {
      './*.js': {
        loader: 'systemjs-angular-loader.js'
      }
    }
  },
  rxjs: {
    defaultExtension: 'js'
  }
}
});
})(this);

I have a main.ts component in the root folder of the project that boostraps the Angular 2 and Angular 1 modules:

> import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { UpgradeModule } from '@angular/upgrade/static';
import { AppModule } from './App/Angular2/app.module';

> // This is the entry point for the AngularJS/Angular hybrid application.
> // It bootstraps the Angular module 'AppModule' and the AngularJS module 
'mainApp'.
platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
    const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
    upgrade.bootstrap(document.documentElement, ['mainApp']);
});

The issue I am having is when I start the application, in Visual Studio 2015, with F5 (or Debug), I get the following error in the developer console of my browser (Chrome):

> Uncaught ReferenceError: module is not defined at systemjs-angular-loader.js

![image](https://cloud.githubusercontent.com/assets/16479217/25866860/86007c18-34bd-11e7-8ce4-433b8ecc0078.png)

**Expected behavior**
The application should run without errors.

**Minimal reproduction of the problem with instructions**

--install npm and Node.js

--create new Visual C# Web Application project

--install TypeScript to project: "npm i typescript --save-dev"

--install type definitions for AngularJS and Jasmine:   

> npm install @types/jasmine @types/angular  @types/angular-animate @types/angular-cookies @types/
           angular-mocks @types/angular-resource @types/angular-route @types/angular-sanitize --save-dev

--donwload Quick Start files from Setup guide: [https://angular.io/docs/ts/latest/guide/setup.html](url)

--copy tsconfig.json file from Quick Start files to project root folder

--add content of package.json from Quick Start files to local copy of file

copy configuration files **systemjs.config.js** and **systemjs-angular-loader.js** from Quick Start files to project root folder

--run "npm install"

--in package.json change the value of attribute "start", in object "scripts", to "http-server -a localhost -p 8000 -c-1 ./"

--add the following tag to index.html: **base href="/app/"**

--install 'upgrade' package: "npm install @angular/upgrade --save" (during installation, several "PEER DEPNDENCY Missing" warnings might be dispplayed. I belive those can be safely ignored).

-- in **systemjs.config.js**, add "'@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js'," after the last Angular binding to include  a mapping for '@angular/upgrade/static' package.

--add root NgModule class called AppModule in the folder 'App'

--import UpgradeModule in 'AppModule' and override its bootstrap method

--remove 'ng-app' attribute from index.html

--copy file main.ts from Quick Start files to project root folder

--in tsconfig.json, change the value of "module" (under compilerOptions) from "commonjs" to "umd"

--launch TypeScript compiler: "npm run tsc:w"

**Please tell us about your environment:**
Windows 8, Visual Studio 2015 Update 3, **npm** package manager

* **Angular version:** 4.0.3

* **Browser:** Chrome
 
* **Language:** TypeScript 2.3.2

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by HarelM** [comment]
I have an almost same error only it fails when trying to bundle the application using systemjs builder.
I don't mind opening this issue in the quickstart repository, but I'm not sure what to do in order to be able to bundle all my application code to a single js file. does current implementation of angular and systemjs support that?

**Comment by dineshjgd** [comment]
HI @lvasilev1 
I hope you were able to resolve the issue, Can you please share the solution..

Many Thanks
Dinesh

**Comment by lvasilev1** [comment]
Nope, I still don't have a solution to this, but I am working on other projects now, so I haven't looked at at in months.
    On Wednesday, December 6, 2017, 12:51:36 AM CST, dineshjgd <notifications@github.com> wrote:  
 
 
HI @lvasilev1
I hope you were able to resolve the issue, Can you please share the solution..

Many Thanks
Dinesh

**Comment by HarelM** [comment]
I migrated to angular-cli a long time ago, best move I made...

**Comment by dineshjgd** [comment]
Hi @lvasilev1 

In my case: Module is already defined in node_modules/@types/Node/index.d.ts file. It was not being loaded onto the server (in my case Karma server for testing). Once its loaded, error will be resolved.

Please check at your end :-)

Regards
Dinesh
