### ISSUE TITLE
Create fesm files for all testing entry points

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16662]
currently @angular/core/testing, @angular/animations/browser/testing, etc don't have fesm files.

there is no reason for this, we should produce fesm files for all entry points instead of distributing individual files.

**Comment by trotyl** [comment]
Obsolete?

https://unpkg.com/@angular/core@5.2.4/esm2015/testing.js
https://unpkg.com/@angular/animations@5.2.4/esm2015/browser/testing.js

**Comment by IgorMinar** [comment]
yup. thanks
