### ISSUE TITLE
Proposal: support expression on left-hand-side of hostProperties

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1666]
Say I have a Component `Tile` that has a bunch of style properties it needs to bind:
```js
  hostProperties: {
    'styleHeight': 'style.height',
    'styleWidth': 'style.width',
    'styleTop': 'style.top',
    'styleLeft': 'style.left',
    'styleMarginTop': 'style.marginTop',
    'stylePaddingTop': 'style.paddingTop'
  }
```

There is also another class responsible for figuring out what all of these styles should be:
```js
getTileStyle(t: Tile): TileStyle {
  // ...
}
```
It would be nice to be able to contain all of these related properties into one model object on the component (`TileStyle`) instead of manually unrolling it into individual properties:
```js
  hostProperties: {
    'tileStyle.height': 'style.height',
    'tileStyle.width': 'style.width',
    // ...
  }
```
```
tile.tileStyle = layoutManager.getTileStyle(this);
```

**Comment by mhevery** [comment]
I think this should work:

```javascript
@Component({
  hostProperties: { 'style': 'style' },
  ...
})
class MyComponent {
  style:any;
}
```

The above should work since it is equivalent to:

```html
<div [style]="style"></div>
```

And we need to special case the `[style]` to bind to object literals.

**Comment by jelbourn** [comment]
That would work for style, but I was thinking it could be more generally useful. Other examples I could think of where it makes sense to group related properties into some model object:

* `aria` attributes (however,  a lot of the time you actually want to bind those to some other existing property, such as `disabled` or `checked`).
* `<video>` config: autoplay, autobuffer, controls, loop, muted, preload, etc.

After style, though, the rest of the use-cases do seem a bit weak.

**Comment by mhevery** [comment]
obsolete by: https://github.com/angular/angular/issues/2268
