### ISSUE TITLE
docs(aio): Webpack Sample App Karma tests don't run 

### ISSUE THREAD

**Issue by Bradleycorn** [angular/angular#16673]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After downloading the [webpack sample app](https://angular.io/resources/zips/webpack/webpack.zip), installing node modules, and fixing the [known issue](https://github.com/angular/angular.io/issues/3514) ... running the karma tests via `npm test` does not work. Instead of the tests running properly, karma outputs a Warning that a 404 was returned when requesting [object%20object].

```
09 05 2017 21:04:56.456:WARN [web-server]: 404: /[object%20Object]
```

**Expected behavior**

The tests should run properly without errors.

**Minimal reproduction of the problem with instructions**

1. Download the [webpack sample app](https://angular.io/resources/zips/webpack/webpack.zip)
2. Install node modules via `npm install`
3. Fix the [known issue](https://github.com/angular/angular.io/issues/3514#issuecomment-291999784) both in the `webpack.common.js` AND the `webpack.test.js`
4. run the tests: `npm test` 

Observe the error (see last line of the output below)
```
$ npm test

> angular-io-example@1.0.0 test /webpackTest
> karma start karma.webpack.conf.js

webpack: Compiled successfully.
webpack: Compiling...

[at-loader] Using typescript@2.2.2 from typescript and "tsconfig.json" from /webpackTest/src/tsconfig.json.

[at-loader] Checking started in a separate process...
[at-loader] Ok, 0.474 sec.

webpack: Compiled successfully.
09 05 2017 21:04:55.383:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
09 05 2017 21:04:55.385:INFO [launcher]: Launching browser Chrome with unlimited concurrency
09 05 2017 21:04:55.394:INFO [launcher]: Starting browser Chrome
09 05 2017 21:04:56.082:INFO [Chrome 58.0.3029 (Mac OS X 10.11.6)]: Connected on socket tzFL4ctVLEqFGhgdAAAA with id 67235997
09 05 2017 21:04:56.456:WARN [web-server]: 404: /[object%20Object]
$
```

**What is the motivation / use case for changing the behavior?**

The webpack guide aims to provide a fully working sample application, but the application does not work, as the tests don't run properly. Given that there is relatively little other documentation on how to get karma tests working with Angular 2/4 and webpack, this sample should provide a working solution.

**Please tell us about your environment:**

OS: OSX
IDE: Intellij Ultimate Edition

* **Angular version:** 2.0.X

Angular Version: 4.0.0.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

N/A, though Karma is setup in the sample to use Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 2.2.2
ES6

* **Node (for AoT issues):** `node --version` =   
node: 6.9.2

**Comment by petebacondarwin** [comment]
I can confirm that we have the same behaviour with the example in the new website: https://aio-staging.firebaseapp.com/guide/webpack

**Comment by Foxandxss** [comment]
I checked and well, they do run. The problem is that for some reason I haven't put the "progress" reporter (the one that says, "1 from 1 tests passes") so it seems like it stops there because the warning.

If you force the test to go red, you will see the error.

The warning is due the loading of the `styles.css` on the `AppComponent` and having the `.css` disabled for testing. You can ignore that for now. I want to rework the Webpack guide eventually.

**Comment by petebacondarwin** [comment]
@Foxandxss can we add this reporter easily?
