### ISSUE TITLE
Component doesn't inherit service from non component superclass

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#16677]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`Can't resolve all parameters for CustomComponentComponent: (?).`

**Expected behavior**
Should resolve all parameters.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/Z9CR1zHUvvvtmKNkyRpq?p=preview

**What is the motivation / use case for changing the behavior?**
Remove not needed super constructor call chains.

Related to #15502 and #14591

**Please tell us about your environment:**
@angular/cli: 1.1.0-beta.0
node: 6.9.5
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.1.0-beta.0
@angular/compiler-cli: 4.0.1

* **Language:** TypeScript 2.2.2

**Comment by trotyl** [comment]
Just add an @Injectable() decorator could solve this, like:

```typescript
@Injectable()
export class BaseComponentComponent {
  constructor(private service: MyServiceService) { }
}
```

An example is http://plnkr.co/edit/pgQJllu6Fw7gIbBQurHm?p=preview

This is not an issue of Angular, TypeScript will only emit metadata for class with decorator, so it's technically impossible (in JIT) for Angular to achieve that. And for AOT it should keep the same behavior as JIT.

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
