### ISSUE TITLE
ERROR Error: Cannot find a differ supporting object '[{'id': 01, 'name': 'Superman'}, {'id': 02, 'name': 'Batman'}]' of type 'string'. NgFor only supports binding 

### ISSUE THREAD

**Issue by MichaelAndresSoto** [angular/angular#16674]
import { Component, OnInit } 	from '@angular/core';

import { Hero }           from './Classes/hero.class';
import { HttpService }	  from './Services/http.service';

@Component({
  selector: 'my-app',
  template: `<li *ngFor="let hero of heroes">
  <span class="badge">{{hero.id}}</span> {{hero.name}}
	</li>`,
  providers: [HttpService]
})

export class AppComponent  implements OnInit { 

	private name: string = 'Michael!';
	heroes: Hero[];

	constructor(private httpService: HttpService){}

  	getHeroes(): void {
  		this.httpService.httpGet().then(heroes => this.heroes = heroes);
  	}

  	ngOnInit(): void {
    	this.getHeroes();

  	}

}

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
