### ISSUE TITLE
aio: better job at keeping events up-to-date

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16683]
Would it make sense to:

1. Use a component to hide too old (or too "future") events?
2. Have a way to show past (old) events?

Could have a list of events (JSON) and auto-generate the page.

**Comment by petebacondarwin** [comment]
We would also need to agree a process for the people managing the events.

**Comment by juleskremer** [comment]
@petebacondarwin I am not sure this is an issue and I'd rather not over engineer the page.  The page is a listing of events that the Angular team will be at and one of us usually just makes a PR to add a new one.  I'm fine with historical events being still listed as it lets people plan for future years (what events we typically go to).  I think this PR can be closed unless there is an issue I'm unaware of?

**Comment by petebacondarwin** [comment]
Works for me.
