### ISSUE TITLE
Chrome ignores target attribute inside Angular2 app

### ISSUE THREAD

**Issue by abhishekhingu** [angular/angular#16689]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I want to post traditional form in iframe like https://jsfiddle.net/4km4cvw1/ . It's work with normal JavaScript but same behavior not working under angular 2  context in  chrome browser  

**Expected behavior**
When we post form dynamically with target set with some iframe then posted form should open in iframe. please check http://plnkr.co/edit/nCPMJKczxIpAddoXJbk1 in IE11 browser. It working with IE11 but with chrome it is different chrome tab/window.

**Minimal reproduction of the problem with instructions**
Please used http://plnkr.co/edit/nCPMJKczxIpAddoXJbk1 to reproduce this issue.

**What is the motivation / use case for changing the behavior?**
See Above plnkr code.

**Please tell us about your environment:**
Windows 7, Chrom 51.0.2704.106 m

* **Angular version:** 2.0.X
2.0.0-rc.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
[Chrome(57.0.2987.133),IE11]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
default from Angular2.0.0-rc.4

**Comment by abhishekhingu** [comment]
Any update on this. Please help me to resolve this asap

**Comment by abhishekhingu** [comment]
can someone please look into this, this behavior is ncessary  for my application

**Comment by abhishekhingu** [comment]
@jasonaden please provide update on this.

**Comment by izoomi** [comment]
Same issue

**Comment by izoomi** [comment]
I found a workaround. If you create the iframe in javascript, Chrome will honor the target attribute.

**Comment by chintan3100** [comment]
Please provide solution for same

**Comment by chintan3100** [comment]
facing same issue. any workaround. how to set iframe in javascript

**Comment by rjdsilv** [comment]
Same problem here. Using angular 6.1.7, chrome 69.0.3497.100 or IE11 (version 11.0.9600.19035). Same thing work fine on firefox. Here is a simple sample code:

<form noNgForm name="searchForm" target="responseFrame" action="http://localhost:8080/assessment/list" method="POST">
  <input type="text" name="healthCardNumberText" value="8060101956" />
  <button type="submit">Search</button>
</form>
<iframe name="responseFrame" frameborder="0" class="embed-responsive-item">

**Comment by tony-gutierrez** [comment]
Same issue.

**Comment by rsteegers** [comment]
After several hours looking for a solution I did this and worked.
Is a trick to fix this error. The solution is add a structure directive to Iframe like *ngIf = "true"
<iframe name="responseFrame" *ngIf="true">

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
