### ISSUE TITLE
Feature Request: Negate Guards

### ISSUE THREAD

**Issue by jdell64** [angular/angular#16698]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you have a guard for logged in users, it would be great to be able to negate it thusly:

    canActivate: [!LoggedInGuard]

**Expected behavior**
This would negate the results of the boolean or observable to save from making another guard called "NotLoggedInGuard".

**What is the motivation / use case for changing the behavior?**
Faster negation of guards, DRY, etc. Certainly a "nice to have" rather than a need.

**versions:** 
```
@angular/cli: 1.0.0
node: 7.7.3
os: darwin x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.0
```

**Comment by jdell64** [comment]
In addition, it seems that if in one guard, I call `this.router.navigate(['/login'])`, it won't trigger any guards to that path.

**Comment by jasonaden** [comment]
Thanks, but we can't do that because JavaScript will interpret it like this:

```
canActivate: [!LoggedInGuard]
// becomes
canActivate: [false]
```

Also, generally I think it would be better to just wrap your guard in a local function. That way we don't need to add bytes to the Router (and make all apps bigger) when it could be done locally with a helper function. Make sense?
