### ISSUE TITLE
circular reference issue with services failing silently when not more than two services communicating 

### ISSUE THREAD

**Issue by samrantmedia** [angular/angular#16700]
If you have two services a and b, and service a includes service b in the constructor and service b includes service a in the constructor then an error is thrown. This is as expected. 

However, 
when userService calls checkoutService in the constructor. 
And checkoutService calls httpHelperService in the constructor. 
And httpHelperService calls userService in the constructor. 

This causes a loop of calls, which will sometimes fail silently (depending on the order in which the components are loaded by the browser), causing the httpHelperService to not load. 

Note that the fail does not occur when there are not method calls between the services. If I limit one of the services to just using a messageSubscription (the httpHelperService), then the circular reference does not matter. However, perhaps it is safer to forbid anyway this behaviour to avoid very confusing bugs or perhaps a severe warning would suffice. 

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by samrantmedia** [comment]
No problem. 

I have a workaround. I won't have a plunkr on this for some time, but hopefully I will get around to reproducing it sometime. 

The version of angular was version 4.

**Comment by tytskyi** [comment]
@samrantmedia, did you use AOT compilation? I think there it does fail not silently (just my guess)
