### ISSUE TITLE
SVG element inside template is not initializing properly

### ISSUE THREAD

**Issue by denzp** [angular/angular#1671]
Following html code in template should at least make a request to **filename.svg**, but it doesn't.
```html
<svg>
  <use xlink:href="filename.svg#object" />
</svg>
```

Browser won't make a request to the external file while `svg` is inside `template` element. 
But normally when we copying `svg` to DOM browser should make a request to the file.

I found a two workarounds:
* create any other than `template` element in [BrowserDomAdapter::createTemplate](https://github.com/angular/angular/blob/master/modules/angular2/src/dom/browser_adapter.es6#L192)
* replace [BrowserDomAdapter::importIntoDoc](https://github.com/angular/angular/blob/master/modules/angular2/src/dom/browser_adapter.es6#L314) with:
```javascript
importIntoDoc: function(node) {
  return document.importNode(this.content(node), true);
}
```

I'm using Chrome 44.

**Comment by mhevery** [comment]
should be fixed
