### ISSUE TITLE
Add version property to NgModule

### ISSUE THREAD

**Issue by k3nsei** [angular/angular#16714]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is none common and easy way to store NgModule version.

**Expected behavior**
There can be property `version` like `id` in NgModule interface. To have common way to versioning our NgModules.

**Minimal reproduction of the problem with instructions**
Every one can se what NgModule interface is:
https://github.com/angular/angular/blob/4.1.2/packages/core/src/metadata/ng_module.ts

**What is the motivation / use case for changing the behavior?**
To show information about versions of used modules.

**Please tell us about your environment:**
Any

* **Angular version:** 2.0.X
4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Any
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
Exactly what version are you talking about here? the Angular version? the Developers defined version? some other sort of versioning?

**Comment by zee92** [comment]
How to make template editable in angular2 ??? waiting for your kind reply.............

**Comment by k3nsei** [comment]
@Toxicable version of module defined by developer.

Example:
`@NgModule({
  ...,
  id: 'module-id',
  version: "1.2.0"
})`

**Comment by tbosch** [comment]
Hello,
so far we didn't have the need of a version, as NgModules are automatically versioned via the npm package in which they ship. Could you explain what having a version would enable?

**Comment by Toxicable** [comment]
@tboscg he's talking about for developers to be able to version their Modules

**Comment by tbosch** [comment]
Yes, but how would a developer use this version?

**Comment by k3nsei** [comment]
@tbosch I want to have component that display dependencies and it's versions. This could be help for example to QA to report bugs.

**Comment by tbosch** [comment]
@k3nsei so you could create a
```
interface Versioned {
  readonly version: number
}
```

And make all of your NgModule and component classes implement this. 

Why would it need to be in the decorator?

**Comment by k3nsei** [comment]
@tbosch Yeah I can add custom stuff. But what I really want is and standardized approach that every developer of angular will use.

**Comment by Toxicable** [comment]
@k3nsei What if not every developer wants to use this approach though?

**Comment by k3nsei** [comment]
This is only proposal, there could be other mechanisms. I only want to have easy and common way to show NgModule id and version.

**Comment by tbosch** [comment]
Sorry, but so far I am not convinced we need this in the core of angular:

- As it is optional, only some users will set this.
- As it is not synced with `package.json`, this will easily get out of date / it is not clear how it relates to the version a component is published under on npm
- There is a way of having this in a user defined way into which libraries could opt into if they wanted to.

**Comment by pkozlowski-opensource** [comment]
I'm with @tbosch and @Toxicable - this sounds like something specific to a particular application need and not something that we want to add to the core of the framework. The good news is that multiple user-land options were provided in the discussion so things _are_ possible.

Closing as won't implement.
