### ISSUE TITLE
Error function paramParser(rawParams)  

### ISSUE THREAD

**Issue by gsyjdcg** [angular/angular#16715]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Cuando en un campo de un formulario escribo el caracter & la función paramParser cree que es otro campo y lo divide. Por ejemplo:
Si yo escribo "John & Mary" paramParser envía al servidor por la URL "John " y por otro lado " Mary" por lo que todo lo que hay por detras de & se pierde.

El problema está en la siguiente línea de código que trozea la url por & sin tener en cuenta si se trata realmente de una separación entre parametros de la URL o no:

function paramParser(rawParams) {
    if (rawParams === void 0) { rawParams = ''; }
    var /** @type {?} */ map = new Map();
    if (rawParams.length > 0) {
        **## var /** @type {?} */ params = rawParams.split('&');** <-- ERROR
        params.forEach(function (param) {
            var /** @type {?} */ eqIdx = param.indexOf('=');
            var _a = eqIdx == -1 ? [param, ''] : [param.slice(0, eqIdx), param.slice(eqIdx + 1)], key = _a[0], val = _a[1];
            var /** @type {?} */ list = map.get(key) || [];
            list.push(val);
            map.set(key, list);
        });
    }
    return map;
}

**Expected behavior**

Lo normal es que cuando encuentre el carácter & lo trate como un carácter más y no lo trozee.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.3.2. | ES5]

* **Node (for AoT issues):** `node --version` =   6.10.2

**Comment by jasonaden** [comment]
Please resubmit in English. Also, we need to see a plunker reproducing your issue. You can use this template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
