### ISSUE TITLE
Incorrect DebugContext Component Reference

### ISSUE THREAD

**Issue by cgatian** [angular/angular#16711]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
In debug mode, throwing an exception during the ngOnInit on a component retrieves the wrong [context](https://github.com/angular/angular/blob/77fd91d615c937857e0959a40c713d92727f641f/packages/core/src/error_handler.ts#L54) object that originally threw the error.

**Expected behavior**
The context object should contain the proper nodeDef that raised the exception.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/XiV5GomrgB9HLqnhME2u?p=preview
* Create a component and throw an exception in the OnInit lifecycle
* Place a breakpoint in [ErrorHandler.ts ln 54](https://github.com/angular/angular/blob/77fd91d615c937857e0959a40c713d92727f641f/packages/core/src/error_handler.ts#L54)
* inspect `context` (error.ngDebugContext) and verify  is referring to the wrong node 

Doing a little debugging, the I found that [_currentNodeIndex](https://github.com/angular/angular/blob/109229246c4b1233668e150122318d740c74db69/packages/core/src/view/services.ts#L168) is not referencing the correct node index when [getCurrentDebugContext](https://github.com/angular/angular/blob/109229246c4b1233668e150122318d740c74db69/packages/core/src/view/services.ts#L448) is invoked by the [catch](https://github.com/angular/angular/blob/109229246c4b1233668e150122318d740c74db69/packages/core/src/view/services.ts#L440).  With little knowledge of the code, it looks like the [debugCheckDirectivesFn](https://github.com/angular/angular/blob/109229246c4b1233668e150122318d740c74db69/packages/core/src/view/services.ts#L184) function should call [debugSetCurrentNode](https://github.com/angular/angular/blob/109229246c4b1233668e150122318d740c74db69/packages/core/src/view/services.ts#L166) once the `nodeDef` is [selected](https://github.com/angular/angular/blob/109229246c4b1233668e150122318d740c74db69/packages/core/src/view/services.ts#L186).

**What is the motivation / use case for changing the behavior?**
I'm attempting to get node reference in the `ErrorHandler` which raised an exception, so I can apply CSS styles to the native element, which will provide a visual cue while debugging raised exceptions.

**Please tell us about your environment:**
Windows 10, Angular CLI

* **Angular version:** 4.0.3

* **Browser:** Chrome 58

 
* **Language:** TypeScript 2.2

* **Node (for AoT issues):** `node --version` =   NA

**Comment by tbosch** [comment]
Note that the `nodeIndex` is a private property. But you are right, in that the the `DebugContext` contains the wrong node reference (in your case it seems to be pointing at the first text node in the component).

**Comment by cgatian** [comment]
@tbosch thank you for reviewing so quickly. I understand the node index is private and shouldn't be consumed. I was hoping to provide more context to the issue to aid in the debugging and resolution of this issue.

**Comment by pkozlowski-opensource** [comment]
This is no longer relevant as `DebugContext` is gone with Angular 9 running on ivy
