### ISSUE TITLE
Expose a Content Projection slot for the template of a derived component to be inserted in the base component's template.

### ISSUE THREAD

**Issue by mattxo** [angular/angular#16716]
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see 

**Current behavior**
When inheriting a component, there is no way to insert a derived component's template into the base component's template.

**Expected behavior**
Expose a ~~transclude~~ Content Projection slot for the template of a derived component to be inserted in the base component's template.

**Minimal reproduction of the problem with instructions**
```
<!--./modal.template.html-->
<div [hidden]="!isVisible">
  <span>{{title}}</span>
  <ng-content select="[modal-content]"></ng-content> <!-- CONTENT PROJECTION SLOT -->  
</div>
```

```
@Component({
    selector: 'modal',    
    styles: [require('./modal.style.scss')],
    template: require('./modal.template.html')
})
export abstract class ModalComponent
{   
    @Input('title') public title : string;
    
    public isVisible : boolean = false;

    public show() 
    {
        this.isVisible = true;
    }

    public hide() 
    {
        this.isVisible = false;
    }
}
```

And then derive say, MySpecialModalComponent from it...
```
<!--my-special-modal.template.html-->
<div modal-content> <!-- PROJECT THIS INTO BASE TEMPLATE -->
  <button (click)="doSpecialThing()"></button>
</div>
```
```
@Component({
    selector: 'my-special-modal',    
    styles: [require('./my-special-modal.style.scss')],
    template: require('./my-special-modal.template.html')
})
export class MySpecialModalComponent extends ModalComponent
{   
    public doSpecialThing()
    {
       alert('omg!');
       this.hide();
    }
}
```

**What is the motivation / use case for changing the behavior?**

So we can use it somewhere like

```
<my-special-modal [title]="'So special'" #modal></my-special-modal>
<button (click)="modal.show()">Show special modal</button>
```

**Please tell us about your environment:**
Webpack

* **Angular version:** 2.4.X

* **Browser:** all
 
* **Language:** all

**Comment by Toxicable** [comment]
Small aside, it's called Content Projection, not transclude, transclude is from AngularJS

**Comment by tbosch** [comment]
A simple solution for this could be to just concat the templates via strings. This should actually also work with AOT.

What would this feature add in addition to string concatenation?

**Comment by mattxo** [comment]
So, currently we can inherit a Component, but we can't inherit the template (that I know of). A feature like this would, at least to my mind, make component inheritance more elegant and more useful. 

I'm not certain string manipulation gets there because you'd really need to know where in the base template string to insert the parents template. I can imagine a hierarchy of components manipulating there string's could get difficult too due to the parsing, potential name clashes etc. 

The other way it could work I think is in the @Component decorator itself. Perhaps something like

```
BASE TEMPLATE 
<!--./modal.template.html -->
<div [hidden]="!isVisible">
  <span>{{title}}</span>
  <ng-content select="[modal-content]"></ng-content> <!-- CONTENT PROJECTION SLOT -->  
</div>
```

Derived component decoractor
```
@Component({
    selector: 'my-special-modal',    
    styles: [require('./my-special-modal.style.scss')],
    template: require('./my-special-modal.template.html')
    projectInto: 'modal-content' <!-- DEFINE WHICH CONTENT PROJECTION SLOT THIS TEMPLATE SHOULD BE INSERTED INTO -->
})
```

The Modal is one example but really, any inherited Component is likely to want to use the base class template in some way. If you have base class functionality, it's probably used in some way by the template, a click handler, a binding etc. 

At the moment, we're required to assign a new template to an Component, and that means breaking the DRY principle (eg. I have to change the bindings in all derived component instead of just on the base template, if I add a feature to the base template, in reality I have to implement that in the template of all derived components because they can't share the base template).

**Comment by tbosch** [comment]
Does https://github.com/angular/angular/issues/13766 or https://github.com/angular/angular/issues/13764 already solve your use case?

**Comment by mattxo** [comment]
#13766 would, thanks :)

**Comment by tbosch** [comment]
Ok, closing.
