### ISSUE TITLE
Router dont wait to resolve everything (flaky)

### ISSUE THREAD

**Issue by llafuente** [angular/angular#16719]
```
[ x ] bug report 
```

**Current behavior**
Router don't wait to resolve everything (it seems that just the first one...). So ActiveRoute.data.value don't have all the correct information.

**Expected behavior**
Wait for all Subject to finish.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/9SzWljqG7wTiIkvtRyRx?p=preview

Click alternatively to "root" - "component with resolve" until you see in the console

> ActivatedRoute Object {r1: true} 2017-05-11T10:20:55.315Z

instead of

> ActivatedRoute Object {r1: true, r2: true} 2017-05-11T10:20:49.308Z

* **Angular version:** all versions

**Comment by jasonaden** [comment]
The router will wait for Observables to complete or a Promise to resolve. It blocks routing until all async resolvers have completed, and this is the intended behavior. I went through the example provided and it appears to be working as intended. Create a new issue if this is still a bug.
