### ISSUE TITLE
RouteReuseStrategy components are not destroyed even if shouldDetach is true and shouldReuseRoute is false

### ISSUE THREAD

**Issue by m4mbart** [angular/angular#16713]
**I'm submitting a ...**
```
[ x ] bug report
```

**Current behavior**
I am using a specific RouteReuseStrategy where the master page of certain master-detail views should be reused. All other views are not reused. Those other views are indeed not being reused, but they should be destroyed. This does not happen and ngOnDestoy() is never called for those views/components or their child components. But I do need these components to destroy properly in order to perform some cleanup work.

**Expected behavior**
The component and its children of a route that is not being reused should be destroyed and ngOnDestroy() should be called.

**Minimal reproduction of the problem with instructions**
Could be added later

**What is the motivation / use case for changing the behavior?**
I think one expects ngOnDestroy() to be called if one is routing away from a view that will not be reused. So the current behaviour is unexpected.

**Please tell us about your environment:**
angular-cli 1.0. Both local development server and production server.

* **Angular version:** 2.4.10 and 4.1.1

* **Browser:** all
 
* **Language:** Typescript 2.0 and 2.3

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by e-cloud** [comment]
Here is the plunkr https://plnkr.co/edit/kvFQ2u6lQDjIOsVP3dOU?p=preview

Now switching between `dashboard`, `heroes/list`, `heroes/:id/detail` will not destroy the `HeroesComponent` nor `HeroDetailComponent`.

The expected behavior is that if the user switch out of `heroes` scope, detached component should destroyed.

**Comment by e-cloud** [comment]
Here is the plunkr https://plnkr.co/edit/kvFQ2u6lQDjIOsVP3dOU?p=preview

Now switching between `dashboard`, `heroes/list`, `heroes/:id/detail` will not destroy the `HeroesComponent` nor `HeroDetailComponent`.

The expected behavior is that if the user switch out of `heroes` scope, detached component should destroyed.

**Comment by e-cloud** [comment]
please reopen this issue!

**Comment by m4mbart** [comment]
That is indeed the same use case we are using this for. It has not been on my radar for some time, because we had other priorities. But now that the amount of users and data in the application is growing users are complaining that after a certain amount of time the application is getting slow. Due to high memory and CPU usage. I suspect that is related to this issue. 

Thanks Scott for adding the Plunkr. Please reopen

**Comment by e-cloud** [comment]
@vsavkin It seems to either we need to add an extra hook like `ShouldDestroy` or do some destruction after `shouldReuseRoute`

**Comment by m4mbart** [comment]
Hi, a lot of users are currently reporting that when they are using the application for a longer period and are clicking through a lot of detail screens the application becomes really unresponsive. We suspect that this has to do with this issue. 
Is there any thing we can do to help you on this issue?

**Comment by m4mbart** [comment]
At least I found out that shouldDetach() should return false instead of true to have a routing component be destroyed. But returning true on a master component that is not actually reused later on because a user first browses to another context of the application results in a master component that cannot be destroyed afterwards. 
Is there a way to force the destruction of a component manually through a handle or snapshot?

**Comment by m4mbart** [comment]
Also I think the names of the methods are somewhat confusing and returning a boolean might do the exact opposite of what one would naturally expect. Maybe the documentation/comments above the abstract methods of ReusableRouteStrategy could be more clarifying?

**Comment by ofriedrich** [comment]
@m4mbart The names of the methods are exactly what they do:
- shouldDetach : Asks if the snapshot should be detached from the router. That means that the router will no longer handle this snapshot after it has been stored by calling the store-method.
- store : After the router has asked by using the shouldDetach-method and it returned true, the store-method is called (not immediately but some time later). If the router sends you a null-value, you can delete this entry from your storage. No need to take care about the memory. Angular should handle this.
- shouldAttach : Asks if a snapshot for the current route already has been stored. Return true, if your storage contains the right snapshot and the router should re-attach this snapshot to the routing. 
- retrieve : load the snapshot from your storage. It's only called, if the shouldAttach-method returned true.
- shouldReuseRoute : Asks if a snapshot from the current routing can be used for the future routing.

**If a snapshot is detached from the routing and re-attached later, there should be no memory leak.** But if a snapshot is detached from the routing and never re-attached to the router, the developer has to take care about the memory management.

I could not find any support in the angular documentation. Here is a part of my solution:

```
export class CutomRouteReuseStrategy implements RouteReuseStrategy {
    [...]
    private deactivateOutlet(handle: DetachedRouteHandle): void {
        let contexts: Map<string, OutletContext> = handle['contexts'];
        contexts.forEach((context: OutletContext, key: string) => {
            if (context.outlet) {
                // Destroy the component
                context.outlet.deactivate();
                // Destroy the contexts for all the outlets that were in the component
                context.children.onOutletDeactivated();
            }
        });
    }
}
```

I'm not sure if the objects are deleted from memory, but the objects receive the angular lifecycle callback "OnDestroy".

**Comment by m4mbart** [comment]
Hi @ofriedrich That seems like proper documentation for the ReusableRouteStrategy interface :)

I agree, memory leaks should be the responsibility of the developer. I guess memory leak in this case was also not the right name for what was happening. There are all kinds of components which listen for scroll events etc. But they never unsubscribe when ngOnDestroy() is not called. So there was more of an subscription leakage that caused problems in the long run.  Your deactivateOutlet seems like a good fix for that. Wonder if that can somehow be part of the DetachedRouteHandle as a standard method... Would have been useful for me at least.

I think I was mainly misusing the Strategy and misunderstood some of its methods. You'r comment clarifies a lot. But by this time the issue became so pressing that I ditched the Strategy entirely and moved to a custom solution that stores state of a Master component and restores it when required (if navigating from Detail -> Master in the same context). 

Thanks for the help!

**Comment by ofriedrich** [comment]
As soon as a snapshot is re-attached to the router, angular will fire all the lifecycle callbacks, you missed.

If a snapshot is detached from the router and not re-attached later, your components will not receive the `OnDestroy` callback and will never die. I think, that could be the problem you have. And then your application will run into memory leaks.

**Comment by m4mbart** [comment]
That's right. But most components don't need reattaching. But I only know about that after a future rout event. (Going from Master -> Detail and then back from Detail -> Master, but only if its the same master). If it doesn't need reattaching, I throw away the handle. But that is not enough.

**Comment by ofriedrich** [comment]
That's nearly the same problem, I have. I do not know, if a snapshot is needed and will be re-attached later, at the time, angular asks the reuse-strategy. So I have to clean up manually.

**Comment by e-cloud** [comment]
@ofriedrich I think you may have got something misunderstood.

**But thanks for your inspiration.**

 All i talk about is based on Angular v4.3.2+.

See here: https://github.com/angular/angular/blob/5d4f5434fd1c387f88ea46332a792ea94f9538da/packages/router/src/router_outlet_context.ts#L60

In my use case, the `contexts` of `DetachedRouteHandle` is empty map mostly. So I have to destroyed the componentRef manually.

```ts
    deactivateAllHandles() {
        // tslint:disable-next-line forin
        for (const key in this.handlers) {
            this.deactivateOutlet(this.handlers[key])
        }
        this.handlers = {}
    }

    // Todo: we manually destroy the component view here. Since RouteReuseStrategy is experimental, it
    // could break anytime the protocol change. We should alter this once the protocol change.
    private deactivateOutlet(handle: DetachedRouteHandle): void {
        const componentRef: ComponentRef<any> = handle['componentRef']
        if (componentRef) {
            componentRef.destroy()
        }
    }
```

And do some extra tracking in side route events, then call `deactivateAllHandles` at the right moment. **That's hacky.**

my route structure looks like:

* /
  * dashboard/
  * about/     --------- the subtree needs custom route reuse strategy
     * abouta
     * aboutb

**Comment by cravi24** [comment]
Although solution by @e-cloud helped destroy components and thus avoid subscription leak issue, there is one more issue which is aggravated when using custom-route-reuse-strategy. All the instances of components linger on in memory even after these components are destroyed. For example, we end up with multiple instances of HeroDetailComponent created for each hero  associated with route https://example.com/hero/{id}/detail
https://github.com/angular/angular/issues/13725
Is there any workaround which can help atleast tone down this issue to a level where we don't use custom-route-reuse-strategy.

**Comment by albanx** [comment]
`shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot)` is a bit confusing to me because the future parameter seems to be the route we just left not the future one.

**Comment by ofriedrich** [comment]
We totally removed the usage of RouteReuseStrategy components because we had to many problems. One thing was that we couldn't get it working with sub-routes.

**Comment by albanx** [comment]
@ofriedrich I understand it is not easy to manage because this provider affects all routing and it is up to the developer to manage the reuse logic (which is not easy).
I had to test and run a lot to understand it fully, also I published a small guide for future references https://medium.com/@albanx/cache-components-with-angular-routereusestrategy-3e4c8b174d5f
