### ISSUE TITLE
Dart: How to extend/add to existing DI bindings? [Angular 1 --> 2 Migration]

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1672]
In Angular Dart 1.0, modules were imperative, and non-const, allowing the following:

```dart
class AngularModule extends Module {
  bind(UrlRewriter);
  bind(TemplateResolver);
}
```

```dart
class MyAppModule extends Module {
  install(new AngularModule());
  bind(UrlRewriter, toImplementation: MyUrlResolver);
}
```

However, because injectables in Dart in Angular 2 are const, it's less clear how to do this pattern. I understand the following would be possible using the App injector:

```dart
final myAppModule = []
  ..addAll(angularModule)
  ..addAll([const Binding(UrlRewriter, toImplementation: MyUrlResolver]);
```

My understanding though is this is not statically analyzable anymore. 

@yjbanov, plz respond :)

**Comment by mhevery** [comment]
I believe this is already solved because module definitions can be nested. 

```javascript
const angularModule = cost [...];
const myApp = cost [
  const Binding(UrlRewriter, toImplementation: MyUrlResolver)
];

injectables: const [
  angularModule,
  myApp
]
```

Does the above solved your problem? If so could you close the issue?

**Comment by matanlurey** [comment]
This might be good enough. I'll re-open if I run into any issues.
