### ISSUE TITLE
@Component Template concat function 

### ISSUE THREAD

**Issue by illiano** [angular/angular#16721]
The Template of a Component becomes sometimes very long with standard html elements without bindings and is hard to read.  Creating Components only for separating the Template will only cost Performance. A solution could be to allow an Array for templateUrl and concat them before compiling. A second solution could be, having an *Include Directive inside the Template. 
 
Solution one:
```
@Component({
    selector   : "a",
    templateUrl: ["./a.head.component.html","./a.main.component.html" ,"./a.footer.component.html"]
})
```

Solution two (inside the template):
```
<div>
   <div *Include="./a.header.component.html" />
   <div *Include="./a.main.component.html" />
   <div *Include="./a.footer.component.html" />
</div>
```

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by tbosch** [comment]
So far we didn't see creating components to wrap html as a bottleneck, i.e. this would be the preferred way of splitting a template.

Having a new way of doing this would require at least a 2x performance improvement, as otherwise it is just another feature that users won't use.
