### ISSUE TITLE
Refactor response.json() to handle none json responses without exceptions thrown

### ISSUE THREAD

**Issue by kenisteward** [angular/angular#16735]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://github.com/angular/angular/blob/4.0.0/packages/http/src/body.ts#L13-L36

Currently the way response.json() works is it checks to see if the data is either a string or string buffer and then tries to do a parse.  If it can't parse it loudly passes an exception. 

This is a contrast to if the body isn't a string.  It just returns the body with no exception at all.

**Expected behavior**
I would expect 1 of either of these things to happen

1. If the response is anything other than a string parsable by JSON.parse() it throws an exception (including blobs and other returns supported by Fetch)

2. If the response is a not parseable string with JSON.parse() it should simply just pass back the original body instead of throwing an exception.

**Minimal reproduction of the problem with instructions**
1. make a request with .http() that returns a string that is not parseable by JSON.parse().
2. call response.json()
3. Note that there is an exception but if you have null or undefined as the return no exception is thrown.

Could also try running ut's where the body returned for the response is not parseable as JSON but null or undefined in other cases.

**What is the motivation / use case for changing the behavior?**
I'm currently contributing to this conversation:
https://github.com/swagger-api/swagger-codegen/issues/4962#issuecomment-300907678

Currently we have complaints that there is an issue when there non parsable json bodies for the generated swagger clients.  Even though I know if you want to use the .json() function you should send back JSON from the server other users might not.  The current implementation doesn't really signify to the user what is happening well especially when you take into consideration null / undefined doesn't throw and exception

* **Angular version:** 2.0.X
Technically 2.0.0 BUT i looked at the code for 4.0.x and it is the exact same code!

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by fljmayer** [comment]
This is not just inconvenient. I do a Form POST to log into my Spring Security backend, and that returns a HTTP 200 response upon success, but Angular 4 throws an error and cannot handle it.

**Comment by MSAJJAN-EEOC** [comment]
`return (<any>res)._body === '' ? {} : res.json();`

worked for me

**Comment by alxhub** [comment]
Closing as this is obsolete (it concerns `@angular/http` which has been removed in favor of `@angular/common/http`).
