### ISSUE TITLE
AIO: The Animations downloadable example is missing a dependency, causing `npm serve` to fail

### ISSUE THREAD

**Issue by kiley0** [angular/angular#16736]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The downloadable example in the Animations section of the Guide is missing a dependency for @angular/animations, so `npm install` `npm start` fails.

**Expected behavior**

`npm install` `npm start` should successfully run the application in the browser.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Users who want to download the downloadable example will have a broken build without this fix.

**Please tell us about your environment:**

Mac OS X, VS Code

* **Angular version:** 2.0.X

4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by kiley0** [comment]
I would submit the fix (just add `"@angular/animations": "~4.0.0"` to the `package.json` file but since the example is a .zip, I wasn't sure where the source code lives.

**Comment by gkalpak** [comment]
This should be fixed in the new (yet to be released) [version][1]. @kiley0, can you confirm it works for you?

[1]: https://aio-staging.firebaseapp.com/guide/animations

**Comment by kiley0** [comment]
@gkalpak -- I downloaded the .zip from the version you linked, ran `npm install` and `npm start` and everything worked like a charm.  I believe it is fixed.
