### ISSUE TITLE
ERROR in Maximum call stack size exceeded : Feature module circular dependecy

### ISSUE THREAD

**Issue by vaibhavbparikh** [angular/angular#16743]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
I have 3 feature modules which contains other sub feature modules.
I want to load Sub feature module of Feature 1 into Sub Feature module of Feature 2 and vice a versa. below is sample code.

**action-routing.module.ts**

    const routes: Routes = [
        {
            path: '',
            component: ActionComponent,
            children: [
              {
               path: ':id',
               loadChildren: 'app/action/action-detail/action-detail.module#ActionDetailModule'
              }
            ]
         }
    ];

**action-detail-routing.module.ts**

    const routes: Routes = [
        {
            path: '',
            component: ActionDetailComponent,
        },    
        {
            path: 'topic-detail/:id',
            loadChildren: 'app/topic/decision-topic-detail/decision-topic-detail.module#DecisionTopicDetailModule',
        }
    ]

**topic-routing.module.ts**

    const routes: Routes = [
        {
            path: '',
            component: TopicComponent,
            children: [
              {
               path: ':id',
               loadChildren: 'app/topic/decision-topic-detail/decision-topic-detail.module#DecisionTopicDetailModule'
              }
            ]
         }
    ];

**decision-topic-detail-routing.module.ts**

    const routes: Routes = [
        {
            path: '',
            component: DecisionTopicDetailComponent,
        },    
        {
            path: 'action-detail/:id',
            loadChildren: 'app/action/action-detail/action-detail.module#ActionDetailModule'
        }
    ]

**Current behavior**

This creates cyclic dependency and throws error of **ERROR in Maximum call stack size exceeded** at compile time.

> ** NG Live Development Server is running on http://localhost:4200 **
Hash: f669143e24ec08ff9586
Time: 23223ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 232 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 332 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 304 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.64 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
ERROR in Maximum call stack size exceeded
webpack: Failed to compile.

However when I do any changes in file and save it again, angular-cli compiles it again and it runs fine then. 

**Expected behavior**

This behaviour shall not create cyclic dependency, there should be mechanism to detect this and break.
Either it shall not compile at all or it shall not throw error at first compile.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

> I have 3 Feature modules in the application. Each Feature modules contains 3 or more sub feature modules with their own components and specially **routes** with router module.
> Now consider below scenario.
> I have modules as below.
> 
> - Feature 1
>   - Feature1Sub Feature 1
>   - Feature1Sub Feature 2
> - Feature 2
>   - Feature2Sub Feature 1
>   - Feature2Sub Feature 2
> - Feature 3
>   - Feature3Sub Feature 1
>   - Feature3Sub Feature 2
> 
> Now Consider below flow.
> I am loading Feature 1 -> Feature1Sub Feature 1. I want to load Feature2Sub Feature 1 directly from Feature1Sub Feature 1. Without loading whole Feature 2 module. Also, I need to maintain navigation flow with back button.
> So I will need to write routes and load that module with loadchildren feature in module of Feature1Sub Feature 1.
> Same way I want to load Feature1Sub Feature 1 directly from Feature2SubFeature 1 without loading whole Feature 2 module. So again I will need to write routes in Feature1Sub Feature 1 module.
> 

As a complex and large application, there might be need to create flow where two or more modules needs each other with routing.

**Please tell us about your environment:**

Ubuntu 14.04 LTS
VSCode Version 1.12.1
NPM 4.4.1

> @angular/cli: 1.0.0-rc.2
node: 6.10.0
os: linux x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

N/A 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript  Version 2.2.1
* **Node (for AoT issues):** `node --version` =   
node: 6.10.0

**Comment by jasonaden** [comment]
While this sounds like an issue, I'm not clear where to assign it. Sounds like it might be a CLI bug, in which case it should be filed against the [Angular CLI](https://github.com/angular/angular-cli) repo.

In either case, please provide a way to reproduce locally. If a plunker works, you can use [this template](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue). Or you can create a gist or create a public repo exposing the problem.

Please add this documentation and resubmit.

**Comment by ericmartinezr** [comment]
@jasonaden consider that there was a PR to fix this issue (closed and deleted, no idea why) https://github.com/angular/angular/pull/14654

**Comment by vaibhavbparikh** [comment]
@trotyl @jasonaden I have update issue with git repo where issue can be reproduced.
https://github.com/vaibhavbparikh/circular-routes
