### ISSUE TITLE
docs(aio): Nested list not displayed correctly

### ISSUE THREAD

**Issue by donroyco** [angular/angular#16744]
**I'm submitting a ...**
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
See the [Ahead-of-Time Compilation page](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) on Angular.io, in *Contents*, the Tree shaking subitems are displayed incorrectly. Same goes for the *Tour of Heroes* subitems.  

<img width="500" alt="Current nested lists" src="https://cloud.githubusercontent.com/assets/1763537/25986802/ae6f0a94-36f1-11e7-86ce-f737871a6bdb.png">

**Expected behavior**
The subitems should behave like a nested list.

**Minimal reproduction of the problem with instructions**
Navigate to [Ahead-of-Time Compilation page](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) and see the *Contents* section.

**What is the motivation / use case for changing the behavior?**
It's confusing how this should be read. It's not behaving like a nested list.

**Browser:** 
Tested in Chrome Version 58.0.3029.110 (64-bit), Firefox 53.0.2 (64-bit), Safari Version 10.1 (12603.1.30.0.34)

**Comment by gkalpak** [comment]
This has been fixed in the new (yet to be released) [version][1], where the ToC is auto-generated.

[1]: https://aio-staging.firebaseapp.com/guide/aot-compiler#running-the-application
