### ISSUE TITLE
Dynamically loaded components - insert cached component instance

### ISSUE THREAD

**Issue by ddyrcz** [angular/angular#16747]
**I'm submitting a ...**  (check one with "x")
```
[ * ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Inserting _**cached**_ instance of component into **ViewContainerRef**:
  containerRef.insert(this.cachedInstance.hostView);

Produce that material controls (Angular Material) has **no interaction**

I was thinking about creating an issue in Angular Material repo, but it turned out that other controls (PrimeNg) behaved the same way

**Expected behavior**

After inserting the cached component, the angular material controls like **md-select** has full interaction

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/lt6EoOfir39HDNZoTxLW?p=preview

Steps:
1) Check controls (input and select) works as expected
2) [_first button_] Load second component (caching the first one)
3) [_second button_] Load cached first component
4) Check the angular material controls interaction

**Please tell us about your environment:**

* **Angular version:** ^4.1.1

* **Browser:** [all]

**Comment by tbosch** [comment]
The problem here is that you are calling `ViewContainerRef.clear()`. This will actually destroy the attached views, not detach them. 

To fix this, change your component to do `ViewContainerRef.detach` instead.
E.g. 
```
  onShowSecondClick(){
    this.contentHost.viewContainerRef.detach(0);
  ...
```

**Comment by ddyrcz** [comment]
thanks a lot!
