### ISSUE TITLE
feature request: reactive forms event on control add

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular#16756]
**I'm submitting a ...**  (check one with "x")
```
[ x] feature request
```

**Current behavior**
When you add a control or group to a form there is no event fired, which one could subscribe to.

**Expected behavior**
i would like to subscribe to something like: 
form.controlAdded or form.groupAdded

Same for removal and validators.

**What is the motivation / use case for changing the behavior?**
I have a parent combonent which defines a form. A child component has a @Input() form property and adds controlls to the parent components form. The parent form should get notified of new controlls. at the moment i emit a custom event on my child control. but it would be great if the parent components formgroup would notify me.

* **Angular version:** 4.1.X

* **Language:** 
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
What is the specific reason for this feature? You say you're using a custom event to emit to your parent component but what is the reason for wanting to know when this happens?

**Comment by mbeckenbach** [comment]
In my special use case, the form should always initiate in a disabled state, as the user as to click a button to enter some kind of edit mode. As i add form controls in the child component's ngOnInit method, i would have to disable the form in every child component after adding the controls. This edit mode is toggled at the parent component. As well as form submit, reset and so on.

The parent and child component are used to generate an aggregated from containing the parents controls as well as some custom controls which will be added in a generic way. I have several child components, which are rendered based on a ngSwitch expression. So i could have several different form configurations. 

As new child components will be build over the time, the developer of those child components should not have to think about enable / disable the form.

**Comment by mbeckenbach** [comment]
I discovered another use case:
When adding a form group to a disabled form, the new form group is enabled.
