### ISSUE TITLE
Angular 4.1.2 animation fail after update and add imports

### ISSUE THREAD

**Issue by Varooneh** [angular/angular#16753]
**I updated angular 2.x to angular 4.1.2 and change app.module.ts to**
`
import { BrowserAnimationsModule } from '@angular/platform-browser/animations'
import { trigger, state, style, transition, animate } from '@angular/animations'
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { UniversalModule } from 'angular2-universal';
import { AppComponent } from './components/app/app.component'
import { NavMenuComponent } from './components/navmenu/navmenu.component';
import { HomeComponent } from './components/home/home.component';
import { FetchDataComponent } from './components/fetchdata/fetchdata.component';
import { CounterComponent } from './components/counter/counter.component';

@NgModule({
    bootstrap: [ AppComponent ],
    declarations: [                
        AppComponent,
        NavMenuComponent,
        CounterComponent,
        FetchDataComponent,
        HomeComponent
    ],
    imports: [
        UniversalModule, // Must be first import. This automatically imports BrowserModule, HttpModule, and JsonpModule too.               
        RouterModule.forRoot([
            { path: '', redirectTo: 'home', pathMatch: 'full' },
            { path: 'home', component: HomeComponent },
            { path: 'counter', component: CounterComponent },
            { path: 'fetch-data', component: FetchDataComponent },
            { path: '**', redirectTo: 'home' }
        ])
    ]
})
export class AppModule {
}
`

**with this link [http://angularjs.blogspot.com/2017/03/angular-400-now-available.html](url)**

**but when I run application in Visual Studio 2017 i've this error**

![error](https://cloud.githubusercontent.com/assets/16257304/25995863/8daa70cc-3729-11e7-9866-9a1b88574593.png)

**please help me how to fix error**

node version 7.10.0
angular version 4.1.2
vs 2017
asp .net core 1.1

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/15332
