### ISSUE TITLE
docs(aio): clarify Angular DI outside of Angular

### ISSUE THREAD

**Issue by tycho01** [angular/angular#16752]
Earlier asked on [SO](http://stackoverflow.com/questions/43158243/use-ngmodule-outside-of-angular).

I wonder if `Http` could be used in non-Angular projects, as nothing in `@angular/http` seems Angular-specific afaict. However, I'm not sure how to use an `NgModule` (or the classes it contains) outside of Angular, notably w.r.t. DI.

[`NgModule`](https://angular.io/docs/ts/latest/guide/ngmodule.html) has its share of documentation on use within Angular, as it was intended. However, I can't actually seem to find any particular documentation specifically about using any of this outside of the Angular context. I'm curious how this might be done, and hope this could make it into the documentation.

**Comment by jasonaden** [comment]
Answering on SO.
