### ISSUE TITLE
Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

### ISSUE THREAD

**Issue by leomayer** [angular/angular#16754]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
in the `app.module.ts` I have configured 

```
 providers: [    {      provide: LOCALE_ID,
      deps: [SettingsService],      // some service handling global settings
      useFactory: (settingsService) => settingsService.getLanguage()   // returns locale string
    }   ],
```
when I insert this code at runtime the changes are applied and taken into account, i.e. changes of the language are done properly. When I compile the code after the restart (`ng-serve`)I get the Error: `ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function`

**Expected behavior**

I would expect that the code could be launched without problems - especially since it could compile during runtime without any kind of errors.

I would expect as well that
```
providers: [
{     provide: LOCALE_ID,
      deps: [SettingsService],      // some service handling global settings
       useFactory: getLanguage  // returns locale string
    }
] ...
export function getLanguage(settingsService: SettingsService) {
  return () => settingsService.getLanguage();
}
```
works as workaround - but matter of fact this does not provide the same functionality for the Pipe-operator `date`, e.g. 

`{{curDate|date:'medium'}}`

while in the first case - on the hot-code-replacement the Pipe-Operator works on the fly for the second scenario.

Q1) How to fix it generally?
Q2) What kind of workaround should I use so I could compile && date-pipe works?
Q3) What kind of build flags should I apply that it works for `ng build`? (Since changes are compiled properly with `ng server`)
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Language translation on the fly as well as usage for the `date`Pipe.
**Please tell us about your environment:**

* **Angular version:** 4.1.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` = v7.10.0

**Comment by leomayer** [comment]
When I use `export function getLanguage(settingsService: SettingsService) {
  return settingsService.getLanguage();
}` at least the build works again... ==> Q2 is solved

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
