### ISSUE TITLE
angular4 requests the whole html template when the  app was first loaded

### ISSUE THREAD

**Issue by Elliottssu** [angular/angular#16768]
**When I refresh the browser, the app loads all the whole HTML templates**
chrome console like this
```
vendor-a4833abf7f.js
main-98ebb07788.js
main-05f0102cf0.css
index-loading.gif
fontawesome-webfont.woff2?v=4.7.0
app.component.html
admin.component.html
login.component.html
system.component.html
wish.component.html
home.component.html
user.component.html
login.component.html
feedback.component.html
download.component.html
search.component.html
recommend.component.html
user-focus.component.html
user-detail.component.html
tag.component.html
```
I have compressed the css and javascript files  and I don't want all html tempaltes to be loaded .  but 
 only  load router change.so.  Is there a  way?

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
Sorry I don't understand specifically what you're asking, it looks related to build processes, if so then I would recommend looking at https://github.com/angular/angular-cli

**Comment by Elliottssu** [comment]
ok, it seem to related to build processes, I would checked it ,it  may not a bug
