### ISSUE TITLE
Calling function 'InjectionToken', function calls are not supported.

### ISSUE THREAD

**Issue by fkolar** [angular/angular#16762]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
when I do `ng build`

I get: 
Calling function 'InjectionToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol UserConfigToken in ....

I have created token and I am trying to use it as:

```
export const UserConfigToken = new InjectionToken<string>('User.Config');

export class CoreModule {
	 static forRoot(config: {[key: string]: any} = {}): ModuleWithProviders
    {
        return {
            ngModule: CoreModule,
            providers: [
                {provide: UserConfigToken, useValue: config},
}

```
**Expected behavior**

It will compile without these errors

I replaced *OpaqueToken* with *InjectionToken* and I think I am using it exactly the same one as in latest angular's 4.1.0 code e.g. when I look at 
```export const APP_BASE_HREF = new InjectionToken<string>('appBaseHref');``` that I am using as well but I dont see any errors for this one. 

I guess this usecase shoudl work...

**What is the motivation / use case for changing the behavior?**
OpaqueToken was deprecated

**Please tell us about your environment:**
I am running on latest Angular 4.1.0 as well as ng 1.0.3

Thanks for any input,

Frank

**Comment by fkolar** [comment]
I tried to comment out all these usages and tested again and now I get more errors like:

`
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /aw7/coreui/node_modules/@angular/core/core.d.ts, resolving symbol CoreModule in /project/coreui/src/lib/core/core.module.ts, resolving symbol CoreModule in /project/coreui/src/lib/core/core.module.ts
`

Could this be related to case-sensitivness of the path. It seems the build makes everythign lowercase.  Cuz on latest angular-cli I am getting this error as well described here:
There is this issue: https://github.com/angular/angular-cli/issues/5126 where instead of having path:

/project/CoreUI/node_modules/@ngtools/webpack/src/index.js!/project/**CoreUI**/src/lib/core/extensible.ts

But something make it all lowercase and I get this warning.
/project/CoreUI/node_modules/@ngtools/webpack/src/index.js!/project/**coreui**/src/lib/core/extensible.ts

**Comment by fkolar** [comment]
I found this issue on angular -cli https://github.com/angular/angular-cli/issues/3854
whcih resolved my case. 

adding path to my tsconfig

```
 "@angular/*": ["../node_modules/@angular/*"]

```
But stil not sure what is the real root case. It seems webpack is not able to find and map correct paths?

**Comment by achieverprince** [comment]
@fkolar 
Thanks for the solution, it worked for me too.

**Comment by allanjames** [comment]
Spent more time on this than I care to mention.  fkolar saved me here as well.  Many thanks
