### ISSUE TITLE
packages\upgrade\static\src symlink doesn't work on Windows

### ISSUE THREAD

**Issue by bisubus** [angular/angular#16760]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`packages\upgrade\static\src`  is a symbolic link that isn't interpreted correctly on Windows. This results in error during compilation:

```
Compiling tools...
Creating .metadata.json files...
Error: Error at <...>/packages/upgrade/static/public_api.ts:15:44: Cannot find module './src/common/angular1'.
Error at <...>/packages/upgrade/static/public_api.ts:16:34: Cannot find module './src/common/downgrade_component'.
Error at <...>/packages/upgrade/static/public_api.ts:17:35: Cannot find module './src/common/downgrade_injectable'.
Error at <...>/packages/upgrade/static/public_api.ts:18:23: Cannot find module './src/common/version'.
Error at <...>/packages/upgrade/static/public_api.ts:19:32: Cannot find module './src/static/upgrade_component'.
Error at <...>/packages/upgrade/static/public_api.ts:20:29: Cannot find module './src/static/upgrade_module'.
    at UserError.Error (native)
    at new UserError (<...>\dist\tools\@angular\tsc-wrapped\src\tsc.js:21:28)
    at check (<...>\dist\tools\@angular\tsc-wrapped\src\tsc.js:87:15)
    at Tsc.typeCheck (<...>\dist\tools\@angular\tsc-wrapped\src\tsc.js:172:9)
    at <...>\dist\tools\@angular\tsc-wrapped\src\main.js:106:23
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
Compilation failed
```

**Expected behavior**

Symbolic link is supposed to work for all operation systems.

**Minimal reproduction of the problem with instructions**

In cloned repo:

npm i
bash ./scripts/windows/create-symlinks.sh 
bash ./test.sh node

**Please tell us about your environment:**

Windows 7
Node 6.10.3
NPM 3.10.10
git 2.9.0.windows.1

* **Angular version:** 4.2.0-beta.1

**Comment by gkalpak** [comment]
This happens because [scripts/windows/create-symlinks.sh][1] doesn't fix this symlink.
<sub>(That said, even after manually fixing the symlink, I haven't been able to run `./build.sh` successfully on Windows. Yet 😛)</sub>

[1]: https://github.com/angular/angular/blob/569b1e0eb7471c4888777b13858dcf48f6ba85f9/scripts/windows/create-symlinks.sh

**Comment by bisubus** [comment]
@gkalpak I've just investigated it. Yes, it is so indeed. Just submitted a PR to fix this. I've had some problems on Windows, but currently I'm able to run `./build.sh`.

**Comment by gkalpak** [comment]
@bisubus, anything special you had to do to get `./build.sh` to successfully run on Windows? What version of Windows?

**Comment by bisubus** [comment]
@gkalpak Windows 7 x64, as administrator. I've accidentally got some weird issues with NPM 3 installation, but after fixing the symlink and installing Bower packages it went ok.

Yes, there are some kinks. I've used MinGW, and I'm running here

```
npm i
bower i
C:\MinGW\msys\1.0\bin\bash.exe ./scripts/windows/create-symlinks.sh 
C:\MinGW\msys\1.0\bin\bash.exe ./build.sh ./build.sh
```

It looks like it does the job, at least there were no errors.

Git for Windows has got bundled MinGW/msys and bash but has no rsync, which is required. And no luck with Cygwin, too, Windows paths were showstoppers there.

Actually, this sounds a bit more sophisticated than [the paper](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md) suggests, to say the least of it. I guess this deserves a separate issue, since it's not nearly as simple for Windows devs as expected. They aren't able to run `./build.sh` from command line for starters.

**Comment by tpeter1985** [comment]
Can someone tell when the pull request can be approved?
Tried to get angular running for 3 hours now (on windows) but it shows up this error.
