### ISSUE TITLE
POST call isn't working

### ISSUE THREAD

**Issue by jatinvmehta** [angular/angular#16766]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm learing node.js with angular 4. I build a sample node api for simple get/post request. My get operation works fine and i am able to fetch data in angular. My post operation isn't getting called at all from angular. If i use POSTMAN, i'm able to call post successfully and data also get inserted in database.

Here is my sample code for node post

    app.post('/groups', function (req, res, next){
    

    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "X-Requested-With, Content-Type");
    res.header("Access-Control-Allow-Methods", "GET, POST","PUT");

    console.log('Request received with body' + req.body);
    //DEV AWS MySQL
    var mysql = require('mysql');
    
    var connection = mysql.createConnection({
                          host     : 'xxxxxxx',
                          user     : 'xxxxxxx',
                          password : 'xxxxxxx',
                          database : 'xxxxxxx',
                          port     : 3306
    });
    connection.connect();

    connection.query('CALL storedprocedure(?, ?, ?, ?, ?, ?)', [req.body.group_avatar_image,req.body.name,req.body.display_name,req.body.unique_id,req.body.description,req.body.adzone], function (err, results, fields){

        if (err)
            res.send(results);

        //res.status(201).send("Groups created successfully");
        res.status(201).send(results[0]);
    });

This works fine with POSTMAN and i can get 201...

Here is my angular 4 code

        CreateGroup(Group): Observable<Group>{
        
        let headers = new Headers({ 'Content-Type': 'application/x-www-form-urlencoded' });
        //let headers = new Headers({ 'Content-Type': 'application/json' });
        let options = new RequestOptions({ headers: headers });    

        console.log('Calling ' + this._GroupsUrl + ' with Options :' + options.headers.toJSON());
        return this._http.post(this._GroupsUrl,Group,options)
                    .map((Response: Response) => <string>Response.json()[0])
                    .do(data => console.log('Service response: ' + data))
                    .catch(this.handleError);
    }

What is wrong here?
when i attach debugger, it calls internally http.prototype.post and inside that it call requestOption and URL, method becomes null. Now i know why i don't see it in network tab but don't understand why this is happening

**Expected behavior**

POST operation should work as expected
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows Server 2008 R2
VS Code
Node as HTTP Server
"dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@swimlane/ngx-datatable": "^9.0.0",
    "bootstrap": "^3.3.7",
    "bootstrap-sass": "^3.3.7",
    "core-js": "^2.4.1",
    "ng2-bootstrap": "^1.6.3",
    "ngx-bootstrap": "^1.6.6",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.1",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }

* **Angular version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 ALL
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by BurningHand** [comment]
I think your RequestOptions.method is null because you never set it, I noticed the same "method becomes null" functionality yesterday while debugging for JWT auth headers—but the fact that the requestOption's method was null didn't stop my POST requests from firing off

If I had to guess, I'd say you're having CORS issue—I may have just dealt with this same problem myself like 2 days ago lol, it sounds like your POST request isn't firing off because there's a preflight request being rejected by your backend; if so, maybe this will work for you~
```javascript
	res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, OPTIONS');
	res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
```

**Comment by pkozlowski-opensource** [comment]
Yep, sounds like CORS issue, nothing to do with Angular: https://www.html5rocks.com/en/tutorials/cors/

**Comment by jatinvmehta** [comment]
import { Injectable } from '@angular/core';
import { Http, Response,RequestOptions, Request, RequestMethod, Headers} from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/do';
import { Group } from './group';

@Injectable()
export class GroupsService{

    private _GroupsUrl = 'http://localhost:5000/api/groups';
    constructor(private _http: Http){};

    getGroups(): Observable<Group[]> {
        let headers = new Headers({ 'Content-Type': 'application/json' });
        headers.append('Accept', 'application/json');
        headers.append('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, DELETE, PUT');
        headers.append('Access-Control-Allow-Origin', '*');
        //headers.append('Access-Control-Allow-Headers', "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding");
        let options = new RequestOptions({ method: RequestMethod.Post, headers: headers,  url:this._GroupsUrl  });    

        //debugger;
        return this._http.get(this._GroupsUrl)
                .map((Response: Response) => <Group[]>Response.json()[0])
                //.do(data => console.log ('ALL: ' + JSON.stringify(data)))
                .catch(this.handleError);
    }

    CreateGroup(GroupM): Observable<string>{
 
        let headers = new Headers({ 'Content-Type': 'application/json' });
            headers.append('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, DELETE, PUT, OPTIONS');
            headers.append('Access-Control-Allow-Origin', 'http://localhost:4200');
            headers.append('Access-Control-Allow-Headers', "X-Requested-With, Content-Type");
        //let options = new RequestOptions({ method: RequestMethod.Post, headers: headers, body:JSON.stringify(GroupM),  url:this._GroupsUrl  });    
        let options = new RequestOptions({ method: RequestMethod.Post});    

        console.log('Calling ' + this._GroupsUrl + ' with body as :' + JSON.stringify(GroupM) + ' and request options are : ' + JSON.stringify(options));

        var req = new Request(options.merge({
        url: this._GroupsUrl
        }));

        debugger;
        //return this._http.post(this._GroupsUrl,GroupM)
        return this._http.post(req.url,JSON.stringify(GroupM),options)
                     .map(res => res.json())
                     .do(data => console.log ('ALL: ' + JSON.stringify(data)))
                     .catch(this.handleError);
    }

    private handleError(error:Response) {
        console.error(error);
        return Observable.throw(error.json().error || 'Server Error');
    }
}

I don't see any CORS issue  or don't see any error
