### ISSUE TITLE
input events update multiple input fields angular 4.1 withing angular cli 1.0.2

### ISSUE THREAD

**Issue by LevytsRoman** [angular/angular#16778]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Imagine that you have an array of strings in your component, 
each string populates the value attribute in an input, 
each input has an event listener that updates the value in the array. 

If there are two inputs with the same value angular updates both the one you typed in and the next one (see plnkr for an illustration that makes sense). 

**Expected behavior**

I expect each input to modify its appropriate value and nothing else.

**Minimal reproduction of the problem with instructions**

[demo](http://plnkr.co/edit/d6KhPwSq5L2KReDmFl28?p=preview)

if you go in and modify the letter 'a' in the first input, everything works as expected, 
but if you modify letter 'p' in the second input field, the name variable gets updated correctly, however on blur angular seems to update the next input field containing letter 'p' with the same value.

**What is the motivation / use case for changing the behavior?**

I'm currently attempting to build a sudoku game using angular cli, and the board is a bunch of input fields. When a user goes in and puts number 1 in a cell, next cell also gets updated.

**Please tell us about your environment:**
linux x64, @angular/cli: 1.0.2

* **Angular version:** 2.0.X
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Version 57.0.2987.133 (64-bit), 
Firefox 53.0.2 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   
node: 6.10.2

**Comment by tbosch** [comment]
The problem here is that the array contains strings. In javascript, 2 strings are referentially identical if they have the same value. Because of that, Angular's change detection gets confused.

I think you are right that this is a bug, and Angular shouldn't do anything in this case.

**Comment by pkozlowski-opensource** [comment]
Isn't it "classical" case for `trackBy`? http://plnkr.co/edit/vWlc1DRSJ5lXbCBiJuif?p=preview

**Comment by petebacondarwin** [comment]
Perhaps this can be solved by @matsko's "watch collection" pipe: https://github.com/angular/angular/pull/36731 ?

**Comment by petebacondarwin** [comment]
@pkozlowski-opensource is exactly correct. Here is a StackBlitz to demonstrate: https://stackblitz.com/edit/ivy-gnt4zl?file=src%2Fapp%2Fapp.component.ts
