### ISSUE TITLE
Angular Universal server side renderer does not work with node_modules that have Angular deps

### ISSUE THREAD

**Issue by samuelhorwitz** [angular/angular#16776]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When attempting to use Angular 4 SSR with Universal, including a library in your main project that depends on Angular leads to server-side errors being thrown (which *are not* thrown on the client) regarding `NgModule` decorators being incorrect, specifically `Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.` I would like to clarify this is not an issue regarding the library having an outdated Angular dependency messing up NPM. The error manifests in the same way but the two are unrelated.

**Expected behavior**
Angular server side rendering should not fail when one of the dependencies also depends on Angular.

**Minimal reproduction of the problem with instructions**
I will set up a GitHub repo in a bit. Basically, you just need to set up an SSR project and then attempt to include a library in your code that expects Angular as a dependency.

**EDIT**: Here is the repo as promised https://github.com/samuelhorwitz/angular-16776-example

**Please tell us about your environment:**
OS X, Yarn, Express

* **Angular version:** 4.1.2

* **Browser:** N/A this is an SSR issue (so, Node)
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   7.3.0

**Comment by samuelhorwitz** [comment]
The specific library I'm experiencing this with is https://github.com/apollographql/apollo-angular. I have an open ticket there: https://github.com/apollographql/apollo-angular/issues/298

The solution for that instance (hacky and bad) is the following:

```javascript
ApolloModule['decorators'][0].type = NgModule;
ApolloModule['decorators'][0].args[0].declarations[0].decorators[0].type = Pipe;
```

I include that in my server-side `NgModule`.

**Comment by jplefebvre** [comment]
I got exactly the same error with the module 'ng2-opd-popup'. I will try hacky trick tomorrow.

**Comment by vikerman** [comment]
Not sure what the issue on Angular is. Please re-open with what we should do to fix in angular
