### ISSUE TITLE
animation in angular 4

### ISSUE THREAD

**Issue by kirtiesl** [angular/angular#16779]
ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
any help??

**Comment by zoechi** [comment]
This is not enough information to reproduce the issue. Please fill the full issue template.

If this is not a bug report:
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
