### ISSUE TITLE
'next' is declared but never used.

### ISSUE THREAD

**Issue by doronsever** [angular/angular#16771]
**I'm submitting a ...**  
```
[ X ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

After upgrading to 4.1.1(happens on 4.1.2 also), my app fails to compile if i don't use the 'next' parameter in a guard's canActive function.

I have the following guard code:

`@Injectable()
export class AuthGuard implements CanActivate {  
    constructor(private authService: AuthenticationService) {}
    canActivate(
        next: ActivatedRouteSnapshot,
        state: RouterStateSnapshot): Observable<boolean> | Promise<boolean> | boolean {
            return this.authService.guardCheck(state.url);
      }
}
`

If i run `ng serve` i get the following error: `'next' is declared but never used.`

**Expected behavior**

Don't break the app if i have unused function's parameters, especially this is the way to implement the guard's canActive interface.

**Please tell us about your environment:**

Mac OSX, Webstorm.

* **Angular version:** 4.1.X

4.1.1/4.1.2

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker (in this case if a plunker won't cause the issue, please provide a downloadable example or repo) using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
