### ISSUE TITLE
Error: No provider for FormControl

### ISSUE THREAD

**Issue by crossRT** [angular/angular#16772]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When my directive constructor injects `NgForm`, it throws `Error: No provider for NgControl!`

**Expected behavior**
It's working when I using Angular 4.0. So my directive can refer to the form control and listen on value changed.

**Minimal reproduction of the problem with instructions**

here's my directive:
```typescript
import {Directive, HostListener, Input, ElementRef, OnInit} from '@angular/core';
import {NgControl} from '@angular/forms';

export class ValidationMessageDirective implements OnInit {

    @Input('validationMessage') customMessage: string;
    constructor(private el: ElementRef, private formControl: NgControl, private validationMessageService: ValidationMessageService) {
        this.target = $(el.nativeElement);
        this.formGroup = this.target.closest('.form-group');

        this.formControl.valueChanges.subscribe((newValue) => {
            this.checkValidation();
        });
    }
}
```

and my module:
```typescript
import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormControlDirective } from '@angular/forms';
import { ValidationMessageDirective } from './src/ng2-validation-message.directive';
import { ValidationMessageService } from './src/ng2-validation-message.service';

export * from './src/ng2-validation-message.directive';
export * from './src/ng2-validation-message.service';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule
  ],
  declarations: [
    ValidationMessageDirective
  ],
  exports: [
    ValidationMessageDirective
  ],
})
export class Ng2ValidationMessage {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: Ng2ValidationMessage,
      providers: [ValidationMessageService]
    };
  }
}
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
macOS

* **Angular version:** 2.0.X

Angular 4.1.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.3.2 ES6

* **Node (for AoT issues):** `node --version` =   
node 6.10

**Comment by alexzuza** [comment]
Please create plunker to reproduce it

**Comment by crossRT** [comment]
Sorry, I have solved it.
This problem happens when the input is not a form control, which is not related to any Angular version.

**Comment by heidermatos** [comment]
@crossRT I'm going through the same problem. What would be the solution?

**Comment by crossRT** [comment]
@heidermatos make sure it's a form control will solve the problem.
what I missed last time is I forget to use ngModel and name attribute.

**Comment by heidermatos** [comment]
@crossRT you could share your working code. Thank you.

**Comment by heidermatos** [comment]
When I add NgControl to my directive, I get this message in the console of my page.

> Cannot instantiate cyclic dependency! NgControl

**Comment by smasala** [comment]
@heidermatos and others: If you use angular DI to load `NgControl`: `constructor(private ngControl: NgControl) { }` then you cannot declare `NG_VALUE_ACCESSOR` as a `@Component provider` at the same time.

Following **does _not_ work** and leads to `Cannot instantiate cyclic dependency! NgControl` error:

```
@Component({
    selector: "my-cmp",
    templateUrl: "mycmp.html",
    providers: [{
        provide: NG_VALUE_ACCESSOR,
        useExisting: MyCmp,
        multi: true
    }]
})
export class MyCmp  implements ControlValueAccessor {
   constructor(private ngControl: NgControl) {
   }

    onButtonClick(): void {
        this.ngControl.reset();
    }

   ... ControlValueAccessor implemented methods, writeValue, registerOnChange etc ...
}
```
What **does work**:
All you need to do is remove the provider and assign the value accessor manually:
```
@Component({
    selector: "my-cmp",
    templateUrl: "mycmp.html"
})
export class MyCmp  implements ControlValueAccessor {
   constructor(private ngControl: NgControl) {
        ngControl.valueAccessor = this;
    }

    onButtonClick(): void {
        this.ngControl.reset();
    }

   ... ControlValueAccessor implemented methods, writeValue, registerOnChange etc ...
}
```

**Comment by tytskyi** [comment]
@smasala why do you need to inject `NgControl` to component that implement custom `ControlValueAccessor`?

**Comment by smasala** [comment]
@tytskyi in my case I have a custom component which houses an input or other component which uses the NgModel directive. The custom component basically just passes the `ngModel` to it's children. If I want to reset the value of the `sub` component, the `host` (custom component) is not notified and remains `ng-dirty`. Hence I need to call `reset()` on the host component as well.

**Comment by smasala** [comment]
**Update:** Angular DI injects an `NgModel` rather than the declared `NgControl`.

**Comment by stguitar** [comment]
@crossRT I would love to see your code here.  I have an input control, using the formControlName syntax with my directive as '*theDirective' on the same element.  I am running into this problem and I do have the FormsModule imported in my shared module which holds the directive.   im using angular 6.  

any ideas what i am missing?

**Comment by crossRT** [comment]
@stguitar if you using `formControlName`, I think you should import `ReactiveFormsModule`, instead of `FormsModule`. Kindly check that!

**Comment by stguitar** [comment]
@crossRT yes, that is what is confusing as I actually have placed both ReactiveFormsModule and  FormsModule in the imports for the module.

if you could post a working plunkr or stackblitz that would be amazing.

**Comment by stguitar** [comment]
Just in case this helps anyone, I was never able to inject NgControl, however I can inject ControlContainer, and use the API to get down to the given control.  

`theControlContainer.formDirective.form.controls['controlName']` will give you the FormControl object in this case.  I have no idea if that is officially supported, etc, but it seems to work fine.

**Comment by smasala** [comment]
**Update:** Angular 7.2.x can still inject `NgControl`

**Comment by luismiguelmoncada** [comment]
> Sorry, I have solved it.
> This problem happens when the input is not a form control, which is not related to any Angular version.

Excelent...
