### ISSUE TITLE
How to pass multiple tables through http?

### ISSUE THREAD

**Issue by shijilesh** [angular/angular#16770]
Hi ,​

I have 2 tables order and itemdetails .How to pass multiple tables through http​
my angular http service for saving is like this, here i can passing only "order ​" and i need to pass "itemdetails" ​ also .

/////////////////////////////////////////////

save(paramProduct: order ​): Observable<order ​> {

    let headers = new Headers({'Content-Type': 'application/json'});
    let options = new RequestOptions({ headers: headers });
    return this.http.post('http://localhost:62178/api/order ​', JSON.stringify(paramProduct), options).map((response: Response) =><order ​>response.json());

}

My api receiving section is like this  .i m receiving JObject ​ which has 2 json arrays.
//////////////////////////////////////////////////

 public IHttpActionResult Post(JObject objData)
    {
        List<ItemDetails> lstItemDetails = new List<ItemDetails>();
        //1.
        dynamic jsonData = objData;
        //2.
        JObject orderJson = jsonData.order;
        //3.
        JArray itemDetailsJson = jsonData.itemDetails;
        //4.
        var Order = orderJson.ToObject<Order>();
        //5.
        foreach (var item in itemDetailsJson)
        {
            lstItemDetails.Add(item.ToObject<ItemDetails>());
        }
        //6.
        ctx.Orders.Add(Order);
        //7.
        foreach (ItemDetails itemDetail in lstItemDetails)
        {
            ctx.ItemDetails.Add(itemDetail);
        }
 
        ctx.SaveChanges();
 
        return Ok();
    }

http://www.dotnetcurry.com/aspnet/1278/aspnet-webapi-pass-multiple-parameters-action-method​

Please help.

**Comment by mlc-mlapis** [comment]
This is not a place for technical help and your request is not related to Angular at all.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
