### ISSUE TITLE
aio: consider elasticlunr for search

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16781]
This search engine claims to have a smaller index file than lunr

**Comment by olivernn** [comment]
Not sure if you are using the latest version of lunr, but there have been some improvements in index size, possibly worth a try. Either way I'd be interested in knowing the results of any comparison.

**Comment by petebacondarwin** [comment]
Indeed it looks like we are still on 0.7.2, so I will take a look at v2

**Comment by olivernn** [comment]
There is an [upgrading](https://lunrjs.com/guides/upgrading.html) guide that might be of some help...

**Comment by petebacondarwin** [comment]
Lunr seems to be doing a good enough job for now.
