### ISSUE TITLE
[issues] angular4.0 _compiler.clearCache() cannot clear html template cache

### ISSUE THREAD

**Issue by Elliottssu** [angular/angular#16793]
**Current behavior**

official provides a method to clear html template cache,  It is a pity that the template can't clear.
```
//app.component.ts
import {  Compiler } from '@angular/core';
constructor(private _compiler: Compiler) {
  this._compiler.clearCache();
}
```
**Expected behavior**

When the page is refreshed, the html is not loaded from the cache, but the new data is retrieved

**Environment:**

**Angular version:** 4.1.X

**Comment by jasonaden** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by lapisanlangit** [comment]
I have this issue also, please angular team fix this problem

**Comment by saifrehman15** [comment]
I am following the https://angular.io/tutorial/toh-pt3 tutorial. I also have the same issue. Does anyone find the solution ?

**Comment by rakesh-singh-shekhawat** [comment]
You can try like this :
@Component({
templateUrl: './app.component.html?v=${new Date().getTime()},
styleUrl: ['./app.component.scss??v=${new Date().getTime()}]
})
Hope this will resolve your cache issue.
