### ISSUE TITLE
NavigationExtras not evaluated on NavigationCancel for initial Route

### ISSUE THREAD

**Issue by GusGold** [angular/angular#16796]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In the case where the Route contains `{path: '', redirectTo: '/home'}`:

1. Navigate to a guarded url from a new window so that the app is loaded for the first time to this url
2. Have the Guard deny the route activation
3. The Router will then navigate back to the previous route which is defaulted to `/` when initialised
4. No Router Parts will be evaluated on the new location of `/` such as `redirectTo` and instead of being redirected to `/home` and loading that page, it will be blank as no components are specified for `/`

This isn't an issue if the app has already been loaded in the tab as the router will have already redirected from `/` to `/home` and `/home` will be `currentUrlTree` for which the Router returns to.

**Expected behavior**

At step `4.` above, evaulate the router parts for the route.

**Minimal reproduction of the problem with instructions**

Have routes setup:
```typescript
const routes: Routes = [
  {path: '' redirectTo: '/home', pathMatch: 'full'},
  {path: 'home', component: HomeComponent},
  {path: 'guardedendpoint', component: GuardedEndpointComponent, canActivate: [EndpointGuard]}, 
];
```
and the `EndpointGuard.canActivate` returns `false`

1. Navigate browser to `/#/guardedendpoint` in a new tab (so that the app loads to this url, rather than navigating to it)
2. `EndpointGuard` will deny the naviation, so a `NavigationCancel` event will fire from `Router.events`
3. `Router` will [`resetUrlToCurrentUrlTree`](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L729) to the [`rawUrlTree`](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L275-L276) which is [initialised](https://github.com/angular/angular/blob/master/packages/router/src/url_tree.ts#L13) to the root path of `/`
4. `Router` will then navigate to this route but won't check the `Routes` configuration (because it assumes it was already checked and parsed when it was initially navigated to though in this case, it wasn't) for the `redirectTo` parameter and so will display an empty page and won't redirect

**What is the motivation / use case for changing the behavior?**

Router will now follow any redirects (or other Router Parts) on the root path instead of ignoring them

The work around I am using is to `subscribe` to `Router.events` `Subject` and if the navigation is cancelled (`Router/NavigationCancel`) is emitted with an `id` of `1` (where it is the first route), I am queuing naviation to `/` so that the router will then know to `redirectTo` using the following code

```typescript
export class AppModule {
  constructor(router: Router){
    var routerEvents$ = router.events.subscribe((message) => {
      if(message.id === 1 && message instanceof NavigationCancel){ //if first navigation and it is cancelled
        router.navigate(['']); //nav to '' so that redirects will be applied!
        routerEvents$.unsubscribe();
      } else if(message.id > 1) routerEvents$.unsubscribe(); 
    });
  }
}
```

* **Angular Router version:** 3.4.8

* **Language:** TypeScript 2.2

**Comment by jasonaden** [comment]
This should have been fixed with #20803. Please open a new issue if that is not the case.
