### ISSUE TITLE
Router redirects to root when accessing a route with an error

### ISSUE THREAD

**Issue by diestrin** [angular/angular#16798]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
When hitting a route with an error (`/test`), router changes the url to `/`, however it doesn't change the rendered component with the root component. The user still thinking they're on the desired route, refresh the page due to error, and gets a completely different route rendered.

**Expected behavior**
Router shouldn't change the url when an error is produced in an router component. If it's really necessary to change the url, then it has to change the component as well. Right now it's only changing the url.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/MEjMyx7hDmV0G9KSt3Y8
You can check accessing the preview directly with the route `#/test`. You can see how it changes the url to `#/` but not the component rendered.

**What is the motivation / use case for changing the behavior?**
Users that lands to a page with an error and try yo refresh the page, gets redirected to the landing page instead of the actual page they were requesting.

* **Angular version:** 4.1.2

* **Browser:** [all]
 
* **Language:** [all]

**Comment by wushawn** [comment]
Agree, imo, this is an unexpected behavior. In dev, you want to refresh the erroring route, not app root. Users may also be confused when reloading the page why they are not seeing the expected page.

**Comment by atscott** [comment]
This doesn't appear to be an issue in v9: https://stackblitz.com/edit/angular-ivy-c4i84c?file=src%2Fapp%2Fapp.ts

The `/test` route activates and there is no redirection.
