### ISSUE TITLE
angular.io is not using this repo

### ISSUE THREAD

**Issue by tobmaster** [angular/angular#16802]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
angular.io docs are not using angular/aio content yet but from the angular/angular.io repo.

**Expected behavior**
angular.io should show the current content

**Minimal reproduction of the problem with instructions**
visit angular-io ;)

**What is the motivation / use case for changing the behavior?**
I found a Bug in the documentation 
https://angular.io/docs/ts/latest/tutorial/toh-pt5.html#!#update-appmodule-
The makeTabs mixin was not used correctly.
It seems to be fixed in angular/aio

I was not able to find an issue for that

**Comment by wardbell** [comment]
We intend to publish this new version to angular.io when it is ready.

Closing because ... well that's the whole point of the new angular/aio.

**Comment by trotyl** [comment]
@tobmaster Meanwhile, it's available on https://aio-staging.firebaseapp.com, you can see the current process for the new site there.

**Comment by tobmaster** [comment]
Yeah but then you might want to still take PRs for the old repo which currently says "Do not post issues and PRs to this repo anymore" ;)

@trotyl thank you for the link
