### ISSUE TITLE
Destroying individual angular instances

### ISSUE THREAD

**Issue by brechtbilliet** [angular/angular#16818]
```
[x] bug report 
[x] feature request
```

**Current behavior**
There is no way to destroy a specific angular instance when having multiple angular instances running in one page.

```
platformBrowserDynamic().bootstrapModule(AppModule);
```
**Expected behavior**
There should be a way to have multiple angular instances running on the same page and destroying them individually
```
platformBrowserDynamic().bootstrapModule(AppModule);
// destroy this on some action
platformBrowserDynamic().destroyModule(AppModule);
```
**Minimal reproduction of the problem with instructions**
- bootstrap application A
- bootstrap application B
- destroy application A (to avoid memory leaks)  => no way to destroy A only 

**What is the motivation / use case for changing the behavior?**
Trying to refactor an angular 1 application towards angular 4+ without having to refactor everything. That's why we divide different angular4 projects to different teams.
If it's not possible to destroy specific angular 4 applications than we might get memory leaks (subscriptions not being cleaned up etc) 

**Please tell us about your environment:**

* **Angular version:** 4.1.0

* **Browser:** [all]
 
* **Language:** [TypeScript]

**Comment by tytskyi** [comment]
see https://github.com/angular/angular/issues/15929

**Comment by brechtbilliet** [comment]
Thanks!
