### ISSUE TITLE
Dynamic module with providers fails when creating a component factory

### ISSUE THREAD

**Issue by MortenSkjoldager** [angular/angular#16816]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Current behavior**

I have a typebuilder that can load a module using SystemJS. This works just fine. 
The code looks like this below:

```
let [moduleName, exportName] = this.pathToComponentImport.split("#");
          window["System"].import(moduleName)
            .then((module: any) => module[exportName])
            .then((type: any) => {
                this.typeBuilder.createComponentFactoryFromType(type)
                .then((factory: ComponentFactory<any>) =>
                {
                    console.log(factory);
                    // Target will instantiate and inject component (we'll keep reference to it)
                    this.componentRef = this
                        .dynamicComponentTarget
                        .createComponent(factory);

                    // let's inject @Inputs to component instance
                });
            });

```
The module is loaded, i can extract the NgModule and get a componentFactoryWithTypes from here. When i insert the instance the specified component are correctly shown on the page. However if the module contains a service in the providers array - lets say SomeService, and i dependency inject that into my component, i will get the "**ERROR Error: Uncaught (in promise): Error: No provider for SomeService!**"

However if I provide the service directly on the component like this:

**@Component({
    selector: 'custom-editor',
    template: '<h1>HELLO WORLD123</h1>',
    providers: [
        SomeService
    ]
})**

My component is correctly inserted, and i can use the SomeService in my component. 

**Expected behavior**

Expected behavior is that I can provide SomeService in the module that import, instead of providing it directly on the component itself.

I've added a github repo to reproduce the error:
https://github.com/MortenSkjoldager/moduleloaderangular

just run NPM install and NPM start
The app should immidietly fail as there's no provider for the service "SomeService". 
You can swap out extensions.bundle.works.js to see it work. In that case, the extensions bundle has SomeService provided directly on the component in the module itself.

**What is the motivation / use case for changing the behavior?**
I'm providing an application for other developers that should be able to dynamically hook their extensions into our default app. With no code changes needed to the vendor bundle.

**Please tell us about your environment:**

Win 10, visual studio code, lite-server,

* **Angular version:** 4.1.2

I'm using the latest version of Angular

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All browsers 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript. TS config provided:

```
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "suppressImplicitAnyIndexErrors": true,
        "types": [
            "node"
        ]
    }

```

* **Node (for AoT issues):** `node --version` =   
There's no AoT involved here

Best regards
Morten

**Comment by alexzuza** [comment]
**type.builder.ts**

```
public createComponentFactoryFromType(type: any) : Promise<{ factory: ComponentFactory<any>, injector: Injector }> {
    let module = this.createComponentModule(type);
    return new Promise((resolve) => {
        this._compiler
            .compileModuleAndAllComponentsAsync(module)
            .then((moduleWithFactories : any) =>
            {
                console.log(moduleWithFactories);
                const moduleRef = moduleWithFactories.ngModuleFactory.create(this.inj);
                let _ = window["_"];

                let factory = _.find(moduleWithFactories.componentFactories, { selector: 'custom-editor' });
                resolve({ factory, injector: moduleRef.injector });
            });
    });
}
```

**dynamic.component.ts**

```
this.typeBuilder.createComponentFactoryFromType(type)
  .then((factoryWithInjector: { factory: ComponentFactory<any>, injector: Injector }) => {
      console.log(factoryWithInjector.factory);
      // Target will instantiate and inject component (we'll keep reference to it)
      this.componentRef = this
          .dynamicComponentTarget
          .createComponent(factoryWithInjector.factory, null, factoryWithInjector.injector);

      // let's inject @Inputs to component instance
  });
```

**Comment by MortenSkjoldager** [comment]
Hi alexzuza,
thanks for your input.
This leads to:

```
zone.js:1980 XHR finished loading: GET "http://localhost:3000/browser-sync/socket.io/?EIO=3&transport=polling&t=LmH4y37&sid=D8dqEc5_4dQpjIm2AABI".
scheduleTask @ zone.js:1980
ZoneDelegate.scheduleTask @ zone.js:400
Zone.scheduleTask @ zone.js:225
Zone.scheduleMacroTask @ zone.js:248
(anonymous) @ zone.js:2004
proto.(anonymous function) @ zone.js:1402
i.create @ browser-sync-client.js?v=2.18.8:2
i @ browser-sync-client.js?v=2.18.8:2
o.request @ browser-sync-client.js?v=2.18.8:2
o.doPoll @ browser-sync-client.js?v=2.18.8:2
n.poll @ browser-sync-client.js?v=2.18.8:2
n.onData @ browser-sync-client.js?v=2.18.8:2
(anonymous) @ browser-sync-client.js?v=2.18.8:2
n.emit @ browser-sync-client.js?v=2.18.8:2
i.onData @ browser-sync-client.js?v=2.18.8:2
i.onLoad @ browser-sync-client.js?v=2.18.8:2
hasXDR.r.onreadystatechange @ browser-sync-client.js?v=2.18.8:2
wrapFn @ zone.js:1032
ZoneDelegate.invokeTask @ zone.js:414
Zone.runTask @ zone.js:181
ZoneTask.invoke @ zone.js:476
```

Also I'm uncertain if t**his.inj** in **type.builder.ts** should come from platformBrowserDynamic().injector ?

Am i missing an import of a module in either the core or the extensions bundle?

**Comment by MortenSkjoldager** [comment]
That indeed did solve the problem!
