### ISSUE TITLE
Form data / model mismatch with ngFor

### ISSUE THREAD

**Issue by PRR24** [angular/angular#16815]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```
**Current behavior**
Input fields created dynamically with ngFor mismatch with with model.

Code:
```
    elements: any[] = [];
    addElement() {
        this.elements.push({ data: "new" });
    }
    removeElement(idx: number) {
        this.elements.splice(idx, 1);
    }
```
HTML:
````
    <form novalidate>
        <div *ngFor="let el of elements; let idx = index">
            <input type="text" [name]="'name_' + idx" [(ngModel)]="el.data">
            <button type="button" (click)="removeElement(idx)">Remove</button>
        </div>
        <button type="button" (click)="addElement()">Add</button>
    </form>
    {{ elements | json }}
````
**Expected behavior**
Elements and form remain in sync

**Minimal reproduction of the problem with instructions**
- Create three elements with clicking Add button (x3).
- Fill the fields with values: "First", "Second", "Third"
- Remove second element by clicking Remove button
- Add new row by clicking Add button.

Model and form will be not in sync. See image below.
![form](https://cloud.githubusercontent.com/assets/6473764/26101027/6e7d160c-3a38-11e7-934e-60af9289cca3.png)

**What is the motivation / use case for changing the behavior?**
Complex structured dynamic form creation and manipulation.

**Please tell us about your environment:**
Ubuntu 16.04, IntelliJ IDEA.

* **Angular version:** 4.0.0

* **Browser:** Chrome 56 | Firefox 52
 
* **Language:** TypeScript

**Comment by alexzuza** [comment]
I would use trackBy option to solve it


```
  
*ngFor="let el of elements; let idx = index; trackBy: trackByFn"
  
trackByFn(i) {
   return i;
}
```

https://plnkr.co/edit/tdpXtwnnjD42mVuWP8C4?p=preview

**Comment by jasonaden** [comment]
`trackBy` is the correct way to fix this.
