### ISSUE TITLE
`ngc` ignores outDir, creates intermediate source file beside sources

### ISSUE THREAD

**Issue by HorvathAkosPeter** [angular/angular#16819]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`ngc` creates *.json and *.ngfactory.ts files in the source directory.

**Expected behavior**
`ngc` should create these files in the directory specified by `compilerOptions.outDir` in the `tsconfig.json`.

**Minimal reproduction of the problem with instructions**
Compiling any minimal project with the ngc, while the `compilerOptions.outDir` setting is in the `tsconfig.json` specified.

**What is the motivation / use case for changing the behavior?**
I want a clean source directory, intermediate files should have their place in a target directory.

**Please tell us about your environment:**
Linux, command line, latest Angular stable (4.1.2), but I've experienced the issue already in the 2-beta* times.

* **Angular version:** 4.1.2

* **Browser:** all (not browser specific)
 
* **Language:** TypeScript 2.3.2 (likely not language specific)

* **Node (for AoT issues):** `node --version` =  6.10.2 (latest LTS)

**Comment by alexzuza** [comment]
AFAIK `ngc` uses `angularCompilerOptions.genDir` option for that

```
"angularCompilerOptions": {
  "genDir": "aot",
  "skipMetadataEmit" : true
}
```

**Comment by HorvathAkosPeter** [comment]
@alexzuza Thank you very much! It was the solution.

**Comment by jasonaden** [comment]
@HorvathAkosPeter Agreed. The only place I can find docs on it is [here](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) but that's lacking quite a bit. Filed #16861 against the docs so this can be added.

**Comment by leovo2708** [comment]
Document is here by comments:
https://github.com/angular/angular/blob/master/tools/%40angular/tsc-wrapped/src/options.ts
