### ISSUE TITLE
Using function as binding for [ngModule] freezes everything

### ISSUE THREAD

**Issue by SmallhillCZ** [angular/angular#16822]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When I use component method as a one-way binding for ngModel, the whole application and browser freezes.

**Expected behavior**
Either binding should work, or error should be thrown if it is forbidden to bind like this.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/yv1S2GzLE62tNhzMGVBB

```html
<form #testForm="ngForm">
  <input type="date" name="date" [ngModel]="getCurrentDate()">
</form>
```
```typescript
@Component({
...
})
export class App {
...
  getCurrentDate(){
    return new Date();
  }
}

```

* **Angular version:** 4.1.2

* **Browser:** Chrome 59.0.3071.47
 
* **Language:** [ TypeScript 2.1 ]

**Comment by dawidgarus** [comment]
`YYYY-MM-DD` string is expected as value for `input[type=date]`.
Also, `getCurrentDate()` returns new instance of `Date` which is different each time (`new Date() !== new Date()`), so angular keeps detecting changes.
I fixed it for You: http://plnkr.co/edit/vlVu9seRGzy5RYQj48y9 although it's not very efficient.

**Comment by jasonaden** [comment]
Closing, as the binding value you're binding to is changing each time it's checked. See @dawidgarus fix above.

**Comment by SmallhillCZ** [comment]
Oh, ok, my bad, I guess it was a hard day, I didn't realize I'm binding a changing value.
