### ISSUE TITLE
Angular2 Dart tutorial missing async library import

### ISSUE THREAD

**Issue by Deithrian** [angular/angular#1682]
https://angular.io/docs/dart/latest/guide/displaying-data.html
The first part of the code "Showing properties with interpolation" does not import the async library, but apparently uses a class from it "Timer", which fails to run.
Please mention that we need to import the library.

The library is added much further down at "Conditionally display data using *if".

**Comment by mhevery** [comment]
Docs are getting rewritten, obsolete.
