### ISSUE TITLE
Error in click handler should break a test

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#16821]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

**Current behavior**
Debug Context is printed and the test is success.

```
ERROR: 'ERROR', Error{ngDebugContext: DebugContext_{view: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ...}, nodeIndex: 10, nodeDef: Object{index: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, elDef: Object{index: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, elView: Object{def: ..., parent: ...,viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ...}}, ngErrorLogger: function () { ... }}
```

**Expected behavior**
Error in click handler should break a test

**Minimal reproduction of the problem with instructions**
https://github.com/CSchulz/angular-error-test

Execute **npm test**.

**What is the motivation / use case for changing the behavior?**
Test should always fail to see any development mistakes.

**Please tell us about your environment:**
@angular/cli: 1.1.0-rc.0
node: 6.9.5
os: win32 x64
@angular/animations: 4.1.2
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.1.0-rc.0
@angular/compiler-cli: 4.1.2
@angular/language-service: 4.1.2

* **Language:** Chrome 53 

* **Language:** TypeScript 2.3

**Comment by alexzuza** [comment]
See https://github.com/angular/angular/commit/07cef36
I think you can implement `ErrorHandler` and throw error there.

```
export class MyErrorHandler {
  handleError(error: any) {
    throw error;
  }
}
describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      providers: [
        { provide: ErrorHandler, useClass: MyErrorHandler }
      ]
    }).compileComponents();
  }));

  it('should fail', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.debugElement.query(By.css('button')).nativeElement.click();
  }));
});

```

**Comment by CSchulz** [comment]
A good idea, but I think it would be good to have an integrated way for test failures.

**Comment by tbosch** [comment]
Right, we could have an integration with the `ErrorHandler` and the test framework.
Marking this as a feature request.

**Comment by CSchulz** [comment]
Can I provide any PR? Are there any ideas how it should be implemented?

In my opinion both variants are not sufficient, but I have no idea how to improve them.

```
export class MyErrorHandler {
  handleError(error: any) {
    throw error;
  }
}
```

```
export class MyErrorHandler {
  handleError(error: any) {
    fail(error);
  }
}
```

**Comment by CSchulz** [comment]
@tbosch Any input for me for providing a PR?

**Comment by pkozlowski-opensource** [comment]
Exception in event handlers fail TestBed tests in Angular v9 with ivy. Closing as resolved.
