### ISSUE TITLE
DatePipe wrong german short date format

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular#16838]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see
```

**Current behavior**
When using locale 'de-DE':

{{myDate | date: 'short'}}  returns day and month numbers < 10 without a leading 0
Example 23.3.2017 13:25

**Expected behavior**
Format should be 23.03.2017 13:25
Same leading 0 for the day as for the month.

**Minimal reproduction of the problem with instructions**
Set locale to 'de-DE' and output any date in short format.

**What is the motivation / use case for changing the behavior?**
Correct date formating :-)

* **Angular version:** 2.0.X
´4.1.x

* **Browser:** 
All

* **Language:** 
Typescript

**Comment by mbeckenbach** [comment]
Looks like the material 2 datepicker uses the short date too. I can simply pass a custom format in to the pipe, but not into the date picker - as far as their docs say.
I need to deploy a customer demo in a few days. Is there any way to override the short date format globally until this is fixed? This would help me much for the moment.

**Comment by ocombe** [comment]
Hello, with the PR to replace the intl API for angular v5 (see [#10809](https://github.com/angular/angular/issues/10809)) the "short" date format for the locale `de` will be `dd.MM.yy, HH:mm`, which means that you will get `23.03.17, 13:25`.
