### ISSUE TITLE
aio: scrollToTop should clear the hash

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#16833]
As it sits right now, when you use the `scrollToTop` from the `scrollService`, it doesn't clear the hash and it should.

**Comment by sivapoonkodi** [comment]
Shall I start working on this? If yes, please let me know how to test the fix?

**Comment by IgorMinar** [comment]
@Foxandxss can you please provide repro steps?

**Comment by Foxandxss** [comment]
No, I don't. Probably something we commented while doing th site but completely forgot. I did some demos and there is nothing wrong, so I am closing it.
