### ISSUE TITLE
代码块内的英文字体不是很友好。

### ISSUE THREAD

**Issue by liyonghuvip** [angular/angular#16842]
最开始看的时候，分不清字母的大小写，尤其是"C"这个字母。
在了解的angular2 的命名规范后，这种情况好很多。
但还是希望改进下（15寸笔记本，1080P，字体很小，如果缩放屏幕字体会模糊）

**Comment by jasonaden** [comment]
Thanks for the issue, but I don't understand it and the translation services do a poor job of translating this issue. If you still have a problem, please log this bug in english.

**Comment by jlee2cacn** [comment]
At beginning the letter can not tell the case, especially the "C" the letter.
After understanding the naming specification of the angular2, this situation is much better.
But I still want to improve the next (15-inch notebook, 1080p, the font is very small, if the zoom screen fonts will be blurred)

(Just translate)

**Comment by jasonaden** [comment]
Yes, unfortunately that is the same translation I got and it doesn't help to understand the issue. I would need a more thorough description of what the problem is to know what's being referred to.
