### ISSUE TITLE
Cross-platform utility scripts on Windows

### ISSUE THREAD

**Issue by bisubus** [angular/angular#16846]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Utility scripts (including Windows-specific `scripts/windows/*`) are not cross-platform, they are shell scripts and require *nix-like environment.

It is possible to run some scripts (`test.sh`, `scripts/windows/*.sh`) with Bash that comes with Git for Windows (which contains stripped-down MSYS and is a prerequisite):
```
"c:\PortableGit\bin\bash.exe" ./test.sh
```

Other scripts (`build.sh`) cannot be run with Bash from Git for Windows because they rely on *nix-like environment and require full MinGW installation (which isn't a prerequisite and works by a lucky chance):
```
# fails due to CRLF and numerous problems with Windows paths
c:\cygwin\bin\bash.exe build.sh 

# fails with `rsync: command not found` error
c:\PortableGit\bin\bash.exe build.sh 

# succeeds
c:\MinGW\msys\1.0\bin\bash.exe ./build.sh 
```

**Expected behavior**
Utility scripts are cross-platform and can be executed on Windows as .bat/.cmd files and/or Gulp tasks.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Current scripts aren't cross-platform and don't match [the requirements for building and testing ](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#prerequisite-software) on Windows.

**Please tell us about your environment:**

Windows 7 x64
Node 6.10.3
NPM 3.10.10
git 2.9.0.windows.1

* **Angular version:** 4.2.0-beta.1

**Comment by alexeagle** [comment]
Angular is now built with Bazel. It still requires the minimal MSYS prerequisite which provides Bash.
I'll leave this issue open since we need to update our DEVELOPER.md documentation.

**Comment by jelbourn** [comment]
Closing since this is obsolete now that Angular builds with bazel
