### ISSUE TITLE
Remembering URL state when navigating between components

### ISSUE THREAD

**Issue by d-damien** [angular/angular#16845]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Let's say you have a router allowing access to several components (in this case, inherited from a single abstract class, but that is not necessarily relevant). Each one is able to modify URL in order to preserve its state for later − like bookmark or copy-paste it to someone. Something like :

1. you are on `/panel/query`
2. play with some filter
3. URL becomes `/panel/query;filter=value`
4. you can reload page ; URL remains the same and you get the same filtered view
5. click to another panel ; URL becomes `/panel/otherpanel`

That part works. But when I navigate to the first component :

6. click to `/panel/query`, you go to query panel, but the `filter` parameter disappeared from the URL (but not from the view).

**Expected behavior**

6. paramaters are preserved, URL is `/panel/query;filter=value` again

That would of course be optional.

**What is the motivation / use case for changing the behavior?**
Much easier coherence between URL and app state during navigation & remembering each component's state.

**Please tell us about your environment:**
App will be used on the most common OSes ; npm ; Apache 2.4.

* **Angular version:** 2.3.1

* **Browser:** [Chrome 58 | Firefox 53.0.2 | IE 11 | Safari 10]
 
* **Language:** [TypeScript 1.7.5]

* **Node (for AoT issues):** `node --version` =   7.6

=======

I tried several things : changing my implementation of RouteReuseStrategy, saving URL in each component, changing the DOM directly.

**Comment by d-damien** [comment]
We did it ! It's working − thanks to @gregdeback. This lecture helped :

https://stackoverflow.com/questions/41280471/how-to-implement-routereusestrategy-shoulddetach-for-specific-routes-in-angular/41515648

``` ts
import { RouteReuseStrategy } from '@angular/router'
import { DetachedRouteHandle } from '@angular/router'
import { ActivatedRouteSnapshot } from '@angular/router'

/**
 * Basic implementation comes from @manfredsteyer.
 * We extended it to add functionality described in current issue.
 */
export class CustomReuseStrategy implements RouteReuseStrategy {

  tab: string = null
  handlers: {[key: string]: any/*DetachedRouteHandle*/} = {}

  /// Should detach and not destroy: true (always)
  shouldDetach(route: ActivatedRouteSnapshot): boolean {

    return true

  }

  /// If detached, store
  store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {

    this.handlers[route.routeConfig.path] = {
      handle: handle,
      params: route.params
    }

  }

  /// Should reuse existing component: if avalaible
  shouldAttach(route: ActivatedRouteSnapshot): boolean {

    // Avoid multiple calls
    this.tab = route.routeConfig.path // current tab

    // the double exclamation mark (!!) casts to actual boolean
    return !!route.routeConfig && !!this.handlers[route.routeConfig.path]

  }

  /// Should we retrieve component and parameters
  retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle {

    if (!route.routeConfig || !this.handlers[route.routeConfig.path])
      return null

    let handler = this.handlers[route.routeConfig.path]
    let sentParameters = route.url.slice(-1)[0].parameters
    let parameters = null

    // Send back params (only if current tab, last retrieve call)
    if (this.tab === route.routeConfig.path) {
      // Which parameters to send to the retrieved component ?

      // If you send parameters from one panel to another
      // (like clicking on a button to access a related object in another panel),
      // then use them
      if (Object.keys(sentParameters).length)
        parameters = sentParameters
      // if you don't, use the old ones (cf. **Expected behavior**)
      else
        parameters = handler.params

      // urlParse() is in each panel component (inheritance is your friend)
      // and can do some specific parameters name and/or value parsing
      // before injecting them into said component
      handler.handle.componentRef.instance.urlParse(parameters)
    }

    return handler.handle

  }

  // I'm not too sure about this part
  /// Should we load/retrieve other component: if path is different
  //  @todo /!\ if routeConfig is null, say "yes"
  shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {

    // @todo: strange case with null/null values
    return future.routeConfig === curr.routeConfig

  }

}
```

So yes it is possible, but it was quire tiresome to implement. Would be great to have it available with an option.

What's the difference between query params and matrix params ?

**Comment by kenisteward** [comment]
@d-damien in the angular docs
https://angular.io/docs/ts/latest/guide/router.html#!#optionally-selecting
https://angular.io/docs/ts/latest/guide/router.html#!#query-parameters

Basically, the idea is that matrix params are per route but query params should be site wide.  There is no hard rule to use them that way though.  Also, the matrix params are put on the url differently. 

Also, I would be very careful on that implementation.  It doesn't take into consideration lazily loaded routes which I had to make a workaround for.

**Comment by kenisteward** [comment]
Also if you have your solution you should close this :)

**Comment by d-damien** [comment]
> in the angular docs
I need to read this part of the doc more thoroughly :scroll:

I meant matrix params indeed. We use classical query params only in backend requests, although others may have different use.

So no new feature / option to have that automatically ? I'm surprised there aren't more people interested : it soon came as an obvious need in our application's development (but my opinion might be biased of course).

**Comment by kenisteward** [comment]
Automatically? You can include any Paramus automatically using navigation
extras

**Comment by jasonaden** [comment]
Closing as this was resolved through the discussion above.
