### ISSUE TITLE
data binding not working for dynamic component

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#16849]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When a component is created and inserted using a factory it shows up in the UI, but data-binding (both one-way and two-way) does not get applied.

**Expected behavior**

Component should work as though it was created the "normal" way.

**Minimal reproduction of the problem with instructions**

This plunkr illustrates the issues: https://plnkr.co/edit/sD800XIb23gD7xftJha8?p=preview

This was reported in https://github.com/angular/angular/issues/10523, but the issue was closed because it was deemed a support request.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7, Tomcat 8.5

* **Angular version:** 2.0.X

4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE 11, FF 44 ESR, FF 53
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2

* **Node (for AoT issues):** `node --version` =

**Comment by alexzuza** [comment]
You're creating component outside change detection tree. Either use `vcRef.createComponent` or `appRef.attachView` as below
```
compRef : any
constructor(private appRef: ApplicationRef){}
...
this.compRef = cmpFactory.create(ctxInjector, null, '#dynCompDiv');
this.appRef.attachView(this.compRef.hostView);
...
ngOnDestroy() {
   if(this.compRef) {
      this.appRef.detachView(this.compRef.hostView)
   }
}
```

https://plnkr.co/edit/4OF5PeEk0zc71tdJqCqN?p=preview

**Comment by mcalmus** [comment]
Such a simple fix. Thanks.

**Comment by thw0rted** [comment]
I know this is over a year old, but I'm confused about how it works.  What part of the added code binds the value of `name` in the `App` instance to the value of `name` in `DynComponent`?  Normally you'd have to declare a binding in the `App` template along the lines of `<dyn-app [name]="name">` but of course the child instance is being dynamically created so that's not possible.  I was expecting a call where I have to make an explicit call that says something like

````
this.compRef.bind(
  "name", // DynComponent input name
  this, // Object containing member to be tracked
  "name" // Property to be tracked
);
````

I assume the Plunkr worked when this issue was posted but of course it doesn't anymore -- I'd really like to see it in action to understand this better.

**Comment by mlc-mlapis** [comment]
@thw0rted ... you can use the pattern:

... for `@Input()`:
```
this._cmpRef.instance.inputname = 'mytextvalue';
```
... for `@Output()`:
```
this._cmpRef.instance.outputname.subscribe(this.anymethod);
```

**Comment by thw0rted** [comment]
Thanks, I just found a bunch of stuff about how dynamic components don't actually support Input / Output, how ngOnChanges won't run, etc.  I might rewrite my components to support this better (e.g. using Observables for `@Input`) but I might also try to solve my higher-level problem differently -- I'm doing something similar to [this](https://github.com/angular/angular/issues/20088) so I'm going to see if there's a better pattern to use.
