### ISSUE TITLE
App won't load - Probably Router problem 4.1.2

### ISSUE THREAD

**Issue by fkolar** [angular/angular#16853]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Please see: https://github.com/fkolar/RouterInitProblemNG412.git

After I upgraded to Angular 4  (4.1.2 now), I started to have this weird problem that used to work in 2.4.7.
It has something to do with Router Initialization and maybe something related to 
https://github.com/angular/angular/issues/14588 ?

I tried to isolate this into reproducible case and here it is https://github.com/fkolar/RouterInitProblemNG412.git:  

_Exception included on the github -> Readme.md_

I have my *AppModule* which uses 3 modules:
* test - My simple test app that renders some content
* core - represent core reusable module 
* feaure - some additional feature module which shows actual problem
 
 
**Module description:**
  
 * App Module, just setups ```router-outlet```  and imports `Coremodule `  to have access to a Service `RoutingService`
 * Test App Module tries to use some component from `FeatureModule`, but it fails as feature module will not initialize
 * `FeatureModule` has `APP_INITIALIZER`, with `Injector` dependency which is used to get a Service from Core Module. 
    * here it fails as a Service from core module `RoutingService` is trying to inject Router, that has not been probably initialized yet. 
     

**Expected behavior**
Feature module is able to get a Service inside its initializer from core module

**Minimal reproduction of the problem with instructions**

https://github.com/fkolar/RouterInitProblemNG412.git

**What is the motivation / use case for changing the behavior?**
Moved to angular 4

**Please tell us about your environment:**
I am on MacOS X, using latest NG. Please check out github for more details

* **Angular version:** 2.0.X
Angular 4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all ] all

**Comment by fkolar** [comment]
I added some logs and here is execution order:

- router.es5.js =>  RouterModule.forRoot()
- router.es5.js:5782  router.es5.js =>  RouterModule.forChild()
- my-core.module.ts:42 init i18n support .....
- my-feature.module.ts:35 init feature module.....
- router.es5.js:5885 router.es5.js => rootRoute() undefined
- router.es5.js:5856 router.es5.js => setupRouter() called
- app-routing.module.ts:28 Constructor AppRoutingModule
- my-core.module.ts:33 Constructor MyCoreModule
- my-feature.module.ts:27 Constructor MyFeatureModule
- test-app.module.ts:22 Constructor TestAppModule
- app.module.ts:30 Constructor AppModule

**Comment by fkolar** [comment]
I just compared both JIT generated code and it seems pretty similar:

```
Object.defineProperty(AppModuleInjector.prototype, '_RoutingService_61', { get: function() {
  var self = this;
  if ((self.__RoutingService_61 == null)) { (self.__RoutingService_61 = new jit_RoutingService34(self._Router_22,self._ActivatedRoute_54)); }
  return self.__RoutingService_61;
}});
```

it just `jit_RoutingService34` might process arguments in different order?  can you maybe navigate me where to look to speed the things. 
WHere i can find the code that calls this ngfactory and pass arguments in? Or maybe I will try to do AOT to find it better?

**Comment by fkolar** [comment]
**Ok see the difference:**

in older version `2.4.9, 1.0.0-rc.4` it is not done as in `4.2.1 ` initializing property directly inside `createInternal`

```
AppModuleInjector.prototype.createInternal = function () {
    this._Router_22 = __WEBPA......
```

But its implemented as getter now

```
Object.defineProperty(AppModuleInjector.prototype, "_Router_55", {
        get: function () {
              ....
```

ao anytime somebody request `Router` to be inject like in my case the getter is involved so it works everytime. 

```
Object.defineProperty(AppModuleInjector.prototype, "_RoutingService_61", {
 ...
..new __WEBPACK_IMPORTED_...2__app_core_routing_service_service__["a" ](this._Router_55, this._ActivatedRoute_54));

```
Does it make sense?  Not is this webpack problem or angular where we maybe changed private property with getter to public field?

**Comment by jasonaden** [comment]
This appears to be an old issue that should have been resolved when we changed how we're using `get`ers in the codebase. If there's still a problem, please create a new issue.
