### ISSUE TITLE
aio: Core module does not import the shared module

### ISSUE THREAD

**Issue by HoumanKml** [angular/angular#16855]
In [the section on NgModules](https://angular.io/docs/ts/latest/guide/ngmodule.html), after introducing the shared module, the core module does not import the shared module and instead imports the CommonModule directly. The document provides no explanation and it seems some kind of anti-pattern. Is there any reason not to import the shared module into the core module?

**Comment by wardbell** [comment]
The core module should _not_ import shared. This _is_ discussed on that page ... [around about here](https://angular.io/guide/ngmodule#the-core-module).

Closing.

**Comment by HoumanKml** [comment]
@wardbell Docs explain why the core module, or more precisely some of the components and the singletons it provides, should not be in the shared module, not the other way around. Not that we should, but the doc does not reason one way or the other. The reason I can think of for the separation is that not all of the modules will import the share module, and so in order to keep the size at a bare minimum, we do not import the shared module in the core module?

**Comment by dgroh** [comment]
Good one! Just came across this question, ebcause I had to Import `SharedModule` in `CoreModule`, beucase some components declared in `CoreModule` depend on Modules of `SharedModule` so I thought I would avoid duplication. For example, why importing `CommonModule` and `FormsModule` in `Core` and `Shared` modules? I don't see any documentation telling why!

**Comment by NRaf** [comment]
Agreed with the other commenters. If there's any harm in importing the `SharedModule` in `CoreModule` it should be called out in the docs. At the moment, it's vague whether importing it is going to cause any harm or not.

**Comment by AchalBhatnagar** [comment]
Do we have any reason as to why core modules should not import shared modules?

**Comment by dgroh** [comment]
After working with those modules a while since my last post I can guarantee you there is no need to import SharedModule in CoreModule. Import both in AppModule.

**Comment by fredgate** [comment]
@dgroh What if in core module we need need some somponents of shared modules ?

Another point. Suppose I have AppModule, CoreModule, SharedModule, Feature1Module, Feature2Module. There are some modules that I need in many of my 5 modules : for example CommonModule in my last 4 modules.
So where to import CommonModule ? In my 4 modules ? In SharedModule that I then import in my core and feature modules ?
And so where to import FormsModule and HttpModule ?

**Comment by dgroh** [comment]
There is no point in importing things of shared module in code module. Those are different concerns. If you need to do so, then you should re-evaluate your architecture.

Do import Common, Forms and Http in `SharedModule`

You can see this at thinkster: 

https://thinkster.io/tutorials/angular-2-ngmodule/creating-the-sharedmodule

**Comment by fredgate** [comment]
Ok to import Common and Forms in SharedModule. But curious to also import  Http. In angular documentation, it is explained that Shared module is for components, directives, pipes shared accross feature modules, and that services should not be included here because it can produce unstable behaviour with dependency injector when included from a lazy loaded module.
Services should preferly be included in CoreModule.
If a module provides both providers and declarations (components, directives, pipes) then to avoid duplication provider instances (loading it in a child injector such as a route) it is necessary that module has a forRoot method.

**Comment by dgroh** [comment]
That is a point a lot a people make and is also legit. This does not imply you to have `SharedModule` with `forRoot` and then call `SharedModule.forRoot()` in `AppModule`. The Angular docs about modules is not well documented IMO. A service is always Singleton in Angular, so the only real danger **might** be if you have lazy loaded module, but if this is not the case I would go for the KISS principle and in case you have lazy loaded module I would start rethinking.

I also don't agree that core should not contain components. If your app relies on a component to exist, I would nevet put it in Shared. You could of course put it in AppModule, but conceptual this would be wrong.

I still have my thoughts. I wish Angular team to improve its docs with more information and samples about modules.
