### ISSUE TITLE
Angular 4 umd fails at runtime when loaded by webpack via "externals" config option

### ISSUE THREAD

**Issue by sergiomcalzada** [angular/angular#16857]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**

Create an application that loads umd modules instead of compiling them:
* Create a new app with angular-cli
* run ng eject
* tune webpack +index.html to make angular modules "externals" and load umd versions
* npm run start

The app does not stars, fails at runtime.

**Expected behavior**

The app load and the "Apps works" is rendered

**Minimal reproduction of the problem with instructions**

Here is a repo: https://github.com/sergiomcalzada/angular_umd
In the last commit I changed angular 4 for angular 2 umd modules and the app runs

**What is the motivation / use case for changing the behavior?**

I want to load umd modules from [external modules](https://webpack.js.org/configuration/externals/) at runtime from a "main" application, so angular modules must be loaded externally

**Please tell us about your environment:**

Windows 10
@angular/cli: 1.0.1 (e)
node: 6.10.0
os: win32 x64
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.2

**Comment by sergiomcalzada** [comment]
Any progress?

**Comment by IgorMinar** [comment]
have you by chance tested this with Angular v5?

The umds are used in other scenarios without problems so I'm unclear about what is it that we could be doing incorrectly.

**Comment by IgorMinar** [comment]
I do have to say though that loading Angular in the configuration that you mentioned is not recommended for production use-cases because it bypasses all of the size and performance optimizations provided by modern tooling.

**Comment by sergiomcalzada** [comment]
Hi,

I does not tested (yet) with any other version. I know that it is not the best option becouse performance and optimizations are lost, but that isn't a problem. 

We want to load angular as an "external" dependency so we could load other external angular dependant modules at runtime. We are trying to build a runtime independent composite UI that load compile independent modules. If there are other mode to do it any help will be wellcomed

**Comment by IgorMinar** [comment]
I'm sorry, but I'm not sure how to help here. I looked at your repo and from what I can tell you are using a very unusual setup that we don't really consider as supported.

If you can reduce your problem to a particular actionable bug report, we'll take a look at that, but we can't debug your application in this way.

In general however, if you continue down the path you are going, you'll end up with megabytes of JavaScript being downloaded to all of your clients, which is not likely something you want.

**Comment by sergiomcalzada** [comment]
The size of the final javascript files is not a problem (for now). I'm investigating a way to load external modules as if they were _plugins_. So the modules (plugins) could be developed independently and loaded at run time from external hosts.

PD: Tested with angular 5 and it works.
