### ISSUE TITLE
$event is never declared anywhere in the template

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#1685]
Currently you can write a handler like this:

```
<button (click)="doSomething($event)">
```

`$event` here is magical, and is the one exception I can think of to the very-nice policy of "all template variables are declared explicitly".

Consider if we instead wrote event handlers a bit more like JS method declarations:

```
<button click($event)="doSomething($event)"></button>
```

So the win here is: no more magic $event variable. 

Also a plus: this resembles ES6 method shorthand syntax slightly better than the current `(click)`:

```
Current:  <button (click)="doSomething()"></button>
Proposed: <button click()="doSomething()"></button>
JS:             { click() {doSomething()} }
```

Of course the semantics are different because in the template you're adding an event handler, not defining a new method, but I doubt this would be a point of confusion, since the motivation for using "parens" in the first place is this same reason.

Another plus: this allows us to alias the name, so the above would be totally equivalent to:

```
<button click(e)="doSomething(e)"></button>
```

If you don't need the event object (very common), you just leave it off, and we're no worse for the wear:

```
<button click()="doSomething()"></button>
```

I haven't thought deeply about how to make this de-sugarable to the on-* style syntax.

I don't want to turn this into #133 all over again, but I didn't see anywhere where this inconsistency was explicitly addressed so I just thought I'd bring it up. If `$event` is meant to be an exception to declaring all introduced variables explicitly and that's just what we're going to do then it'd be good to have this exception explicitly documented (i.e. via this ticket).

**Comment by mhevery** [comment]
there is a lot more than just `$event`, `$self`, `$element`, `$target`, etc..

Good intention, but I don't think it will work.

**Comment by ewinslow** [comment]
:( too bad. I guess this means whatever parser we come up with will just have to special case those vars? As long as only the framework can introduce them I guess we're OK.
