### ISSUE TITLE
docs: angularCompilerOptions not in angular.io docs

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#16861]
The only place I can find that documents angularCompilerOptions is at [this link](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) which is quite insufficient. There are comments in the code as to what the options are and what they do, so the docs should reflect this.

Referred from #16819

**Comment by leovo2708** [comment]
I only know it is option which used by Angular compiler (ngc). Some properties: genDir, skipTemplateCodegen, skipMetadataEmit, ... but no document about them.

Angular team should write document same as angular cli. Thanks.

**Comment by leovo2708** [comment]
Yeah, document is here by comments :)
https://github.com/angular/angular/blob/master/tools/%40angular/tsc-wrapped/src/options.ts

**Comment by jusefb** [comment]
The link appears to be broken

**Comment by gkalpak** [comment]
The file has been moved here: https://github.com/angular/angular/blob/master/packages/tsc-wrapped/src/options.ts

**Comment by NColey** [comment]
Looks like the above link is also broken as of this past week. [This file](https://github.com/angular/angular/blob/745b59f49cacb55c54d11e948c011fbbf8b724f7/packages/compiler-cli/src/transformers/api.ts) looks like it has the compiler options but it would be great to add this to the docs.

**Comment by KKrisu** [comment]
Thanks @NColey for providing an updated link.

Can you - the Angular team - please document these configs in a stable place?

**Comment by christrude** [comment]
They exist here now: https://angular.io/guide/aot-compiler#angular-compiler-options

**Comment by dinony** [comment]
What happened to the `genDir` option?

**Comment by emilio-martinez** [comment]
@dinony I believe that was removed as of v6
