### ISSUE TITLE
`animate` timing parameter can't be used as param

### ISSUE THREAD

**Issue by ShadowManu** [angular/angular#16864]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After @matsko presentation on animations in ng-conf, and the merge of #15574, I wanted to use a snippet like the following.

```
import { animate, animation, style, AnimationReferenceMetadata } from '@angular/animations';

export const fadeIn: AnimationReferenceMetadata = animation([
  style({ opacity: 0 }),
  animate('$duration', style({ opacity: 1 }))
], { params: { duration: 1000 } });
```

However, Angular complains on invalid value when used on a `trigger`.

**Expected behavior**
To customize the `animate` timing parameter through the input variables on the new animation system

**Minimal reproduction of the problem with instructions**
Use the [https://github.com/filipesilva/angular-quickstart-lib] project referencing angular #master builds on github and adding this animation the app component. I haven't pushed changes to the initial repo on [`ng-contrib/animations`](https://github.com/ng-contrib/animations) but if needed I can do so. There isn't anything custom though (except the package versions and systemjs config).

**What is the motivation / use case for changing the behavior?**
As the referred repo implies, I needed to work on a set of animations for our project but wanted to make it separated and open source. The duration of an animation is probably a parameter expected to be customizable (as was explained on the conference).

Can it be due to incorrectly using the API?

**Please tell us about your environment:**
Linux x64, VS Code, NPM

* **Angular version:** master builds on 2017-05-17

* **Browser:** tested on Chrome 57 but since this is error hapenning on Angular, I could say all.
 
* **Language:** TypeScript 2.3

* **Node (for AoT issues):** `node --version` =  6.10

**Comment by matsko** [comment]
We discarded the `$dollar` values. Try `{{ duration }}`.
