### ISSUE TITLE
cannot import TestBed after upgrade to angular4

### ISSUE THREAD

**Issue by pearldiver** [angular/angular#16867]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
import {  async,  TestBed, ComponentFixture } from '@angular/core/testing'
The TestBed is undefined.
All production code works, but tests not.

**Expected behavior**
all functions/const have correct import from @angular/core/testing

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows Server, npm

* **Angular version:** 2.0.X
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.0.0",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
v6.9.5

**Comment by pearldiver** [comment]
I add one repository which can reproduce the issue. All import (async, TestBed and ComponentFixture) is undefined.
https://github.com/pearldiver/testsample

To make the test work, downgrade all angular module to 2.4.4, except for router, router downgrade to 3.4.4
And in spec-bundle.js
change platformBrowserDynamicTesting to platformBrowserDynamicTesting() because it is a function in angular 2.

**Comment by gonzofish** [comment]
Have you tried re-installing? Just a simple `npm i @angular/core` seems to fix it for me

**Comment by pearldiver** [comment]
@gonzofish yes i tried but the error is same, is your solution fixed my testsample on your machine?

**Comment by redboul** [comment]
Hi, 

don't know if you are still facing the issue but there are 3 things to do to make your test pass.

1. you need to remove the `.d.ts` extension resolution from [webpack.test.config](https://github.com/pearldiver/testsample/blob/master/config/webpack.test.js#L50) to have 
   ```
   extensions: ['.ts', '.js', '.adv.js', '.min.js']`
   ```
2. call the right testing object in [spec-bundle.js](https://github.com/pearldiver/testsample/blob/master/config/spec-bundle.js#L33)
   ```
   var testing = require('@angular/core/testing');
   ```
3. finally **call** the _platformBrowserDynamicTesting_ function in [spec-bundle.js](https://github.com/pearldiver/testsample/blob/master/config/spec-bundle.js#L38):
   ```
   testing.TestBed.initTestEnvironment(
    browser.BrowserDynamicTestingModule,
    browser.platformBrowserDynamicTesting()
   );
   ```
Your sample repo is working on my machine with these changes.
Hope this helps,

Cheers

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
