### ISSUE TITLE
canDeactivate called with null as component when lazy loading

### ISSUE THREAD

**Issue by Ristaaf** [angular/angular#16868]
**I'm submitting a ...**

[X ] bug report => search github for a similar issue or PR before submitting

**Current behavior**
When trying to use a canDeactivate guard with a lazy loaded route, the component parameter is null

This might be a regression of #15626 but I have not seen the provider problem

**Expected behavior**
I expect to be able to get a reference to the lazy loaded component

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/mkgL1GOuRdk2w2xgYkrL

The StartComponent will be lazy loaded as route ''
Click the link "Click Me!" to trigger a routing to another component, this also triggers the canDeactivate guard for the '' route. 
However the CanDeactivateGuard.canDeactivate(component) will not get the StartComponent into it as a parameter, it will get null instead, so you cannot call functions on the StartComponent to see if you can deactivate or not. 
You can see the problem in the console.

**Angular version:** 
4.1.3

**Browser:** 
I use chrome, but the problem is there in other browsers too, it does not seem to be browser specific in any way.

**Comment by Loster102** [comment]
Hi,

I got this error too. But i realized, that this error still occurs, even if either the start or the next module is lazy loaded.

**Comment by michie1** [comment]
I've got the same issue with Angular 2.4.

**Comment by MazherUddin** [comment]
Same problem here. I was scratching my head for several days.

**Comment by megasharks** [comment]
the same with Angular 4.1

**Comment by csvn** [comment]
Does anyone know a workaround for this issue? Other than *not* using lazy-loading that is. I haven't been able to come up with a way to get a hold of the component instance so far.

**Comment by Ristaaf** [comment]
Problem still there in 4.2.4

**Comment by KeyboardSounds** [comment]
I'm also experiencing this issue (in angular 4.2.2).

**Comment by TheILPlace** [comment]
this is super crucial for me.
in all conference talks, it is always said: lazy load everything.
now we cannot use the CanDeactivate functionality to check for changes in the component we're navigating from.

**Comment by glapointe** [comment]
I'm on 4.2.6 and having the same issue.

**Comment by TheILPlace** [comment]
@chuckjaz is this planned to be resolved in the near future ?

**Comment by xblader** [comment]
getting the same problem here. I will disable lazy-load and break down my modulo into several small modules.

**Comment by chuckjaz** [comment]
`canDeactivate` will be called with a `null` component when the route doesn't have a `component`. Currently lazy loaded routes are treated as component-less routes and call their guards with a `null` component. The route that is being mounted is defined in the `NgModule` in `start.module.ts` and you can put the guard there to get the component. In general, this means that the guard that knows about the component's type should be placed in the module that declares the component (or, at least, the route to the component).

CC'ing the owners of the router for more clarification on whether this behavior should be changed.

//cc: @vicb @jasonaden

**Comment by hannut91** [comment]
I solved problem like this

```
@Injectable()
export class RouterGuardService implements CanDeactivate<CanComponentDeactivate> {

  constructor(private router: Router,
              private injector: Injector,
              private componentFactoryResolver: ComponentFactoryResolver) {
  }

  canDeactivate(component: CanComponentDeactivate) {
    if (!component) {
      const index = this.router.url.indexOf('/template-detail');
      if (index > -1) {
        return this.componentFactoryResolver
          .resolveComponentFactory(TemplateDetailComponent)
          .create(this.injector)
          .instance.canDeactivate();
      }
      return true;
    }
    return component.canDeactivate ? component.canDeactivate() : true;
  }
}
```

**Comment by zkewal** [comment]
Any update on this fix? We are facing similar issue.

**Comment by hannut91** [comment]
problem is that we can't access current's component instance. 
So I tried to get current component instance but i failed.

```
@Injectable()
export class RouterGuardService implements CanDeactivate<CanComponentDeactivate> {

  constructor(private router: Router,
              private injector: Injector,
              private componentFactoryResolver: ComponentFactoryResolver) {
  }

  canDeactivate(component: CanComponentDeactivate) {
    if (!component) {
      if (this.router.url.indexOf('/template-detail') > -1) {
        return this.componentFactoryResolver
          .resolveComponentFactory(TemplateDetailComponent)
          .create(this.injector)
          .instance.canDeactivate();
      }

      return true;
    }
    return component.canDeactivate ? component.canDeactivate() : true;
  }
}
```

Above code is making new instance of component.
not working.
key code solve to problem is get current component instance. but I can't found.

**Comment by picninim** [comment]
Same issue, on 4.3.3.
 
For work around I added a Singleton service that I emit an event and catch it at the component, and there Im doing the logic that I needed to be done on the Guard.

Hope they fix it soon :/

**Comment by picninim** [comment]
@Ristaaf, I was having the same issue, but I realise that I was using the guard on the wrong place. instead of placing the Guard at the:

```
const routes: Routes = [
  {path: '', loadChildren: 'app/start/start.module#StartModule', canDeactivate: [CanDeactivateGuard]},
  {path: 'another', component: AnotherComponent}
  ];
```

Place it at the main route of your Start module:

```
@NgModule({
    declarations: [StartComponent],
    imports: [
        RouterModule.forChild([
        { path: '', component: StartComponent , canDeactivate: [CanDeactivateGuard], children: [
           ...
        ]}
        ])
    ]
})
```
At the Lazyload module definition, you are setting an "alias" for when to load the Module and its components. So basiclly it does have a component. You can place all the components/routes you want to protect from that point by placing them inside `children` Route property

**Comment by tuurbo** [comment]
This is still any issue as of 4.4.6

If I stay within the lazy loaded modules set of routes it works fine. If i click a different lazy loaded route (that hasn't been loaded yet) i get null.

**Comment by JihedHalimi** [comment]
Thank you @picninim for informing us about the correct usage. It Works!!

**Comment by ssolida** [comment]
Guys any news about that bug ?

**Comment by vsavkin** [comment]
I'm probably missing some context.

The following route doesn't have a component set (it's a componentless route), so you won't have a component provided.

```
{path: '', loadChildren: 'app/start/start.module#StartModule', canDeactivate: [CanDeactivateGuard]}
```

As far as I remember, even if you replace `loadChildren` with `children`, it will not provide a component instance. 

Only routes that have components set should receive them.

**Comment by Ristaaf** [comment]
Update for all who have this problem. The setup was simple, one lazy loaded route and one not lazy loaded route both have a canDeactivate guard, when navigating from one to the other the canDeactivate guard was called with null as component. 

The situation where I navigated from a lazy loaded route to a non lazy loaded route was an error from my side, the canDeactivate guard was placed in the wrong routing table, it should be in the routing table of the lazy loaded route, when placing it there it works fine.

The other situation however still fails in 4.4.6 but works in 5.0.0, where you navigate from a non lazy loaded route to a lazy loaded one, the canDeactivate guard on the non lazy loaded path also gets called with null as component. 

This is an updated plunker using Angular 4.4.6 showing the situation navigating from a non lazy loaded to a lazy loaded route: http://plnkr.co/edit/z2OqgTXTiPpTgXcmNiDM?p=preview

This is closed because in Angular 5 both of the situations works fine!

**Comment by majid-mashhadi** [comment]
The solution for this issue is moving the canDeactivate  to the lazy load module.
here is the route to start component:
{path: 'start', loadChildren: 'app/start/start.module#StartModule'}

create a route module file (start.route.ts) for the start component:
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { CheckoutComponent } from './start.component';
import { CanDeactivateGuard}  from 'your path to guard'
const routes: Routes = [
    {
        path: '', component: StartComponent,
        canDeactivate: [CanDeactivateGuard]
    }
];

@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule]
})

export class StartRoutingModule { };

then import the above file to the start.module.ts

**Comment by flaska** [comment]
I had this issue. I love these issues which make no sense ... haha

My solution turned out to be same as @tuurbo [BTW thanks so much, Daniel, for posting your answer. #save-a-day-hero !!!

`<router-outlet *ngIf="!isLoading"></router-outlet>`

For some reason Angular didn't like the `*ngIf` on `router-outlet`

Peace for everyone. Good luck and never forget this one:

https://daveceddia.com/images/angular_dev_cycle.png

**Comment by wctiger** [comment]
I am still seeing this issue as of 9/5/2018. Version 6.1.0 - the workaround mentioned by @majid-mashhadi works, but downside of it is I have to specify the same CanDeactiveGuard class for all of my lazy-loaded routes/components. It will still be good if we just need to write it once in the parent routing module.

**Comment by Farouk19** [comment]
Thanks @Ristaaf for your well explained solution.
It works perfectly!

**Comment by DavidDon13** [comment]
I'm facing the same issue in angular 6. The canDeactivate guard is attached to non-lazy loaded component. If I try navigate to a lazy loaded module, I get the null component error and my browser will eventually crash. As a workaround I've put an if statement in my canDeactivate service to check if the component is null or not.
`            
if (component) {
   return component.canDeactivate();
}

return true;
`
I'm not proud of it but it stops the app from crashing and it seems to be working as expected.

**Comment by majid-mashhadi** [comment]
HI,You have to place the CanDeactivate in the component route file, for solving the issue please do these steps:1- Create a guard and implement the CanDeativate interface for that component2- Create a route file and add the canDeactivate to the routes constant and use it in imports array of @NgModule3- Import the routes and add it to the imports array of the component module
here is the code for route file:
import { NgModule } from '@angular/core';import { Routes, RouterModule } from '@angular/router';import { XComponent } from './x.component';import { XCanDeactiveGuard } from '@app/guards/x.guard'; // x.guard.ts path
const routes: Routes = [    {        path: '', component: XComponent,        canDeactivate: [XCanDeactiveGuard]    }];
@NgModule({    imports: [RouterModule.forChild(routes)],    exports: [RouterModule]})
export class XRoutingModule { };
Here is the code x.guard:

import { Injectable } from '@angular/core';import { CanDeactivate } from '@angular/router';import { Observable } from 'rxjs/Observable';

@Injectable()export class XCanDeactiveGuard implements CanDeactivate<XComponent> {
    canDeactivate(component: CheckoutComponent): Observable<boolean> | boolean {
//        write your code here
    }}



Best Regards,Majid Mashhadi
 

    On Thursday, November 1, 2018, 11:11:33 AM PDT, DavidDon13 <notifications@github.com> wrote:  
 
 
I'm facing the same issue in angular 6. The canDeactivate guard is attached to non-lazy loaded component. If I try navigate to a lazy loaded module, I get the null component error and my browser will eventually crash. As a workaround I've put an if statement in my canDeactivate service to check if the component is null or not.
`
if (component) {
return component.canDeactivate();
}

return true;
`
I'm not proud of it but it stops the app from crashing and it seems to be working as expected.

**Comment by harryjoy** [comment]
I have routing as below:

{
  path: "home",
  children: [{
    path: "dashboard",
    children: [{
      path: "user",
      canDeactivate: [CanWeDeactivateThis]
    }]
  }]
}

There are components defined in routes, above is just a simple snapshot.
I get component as null when I add can deactivate in user path but if I add it on dashboard path it works well.
Adding in the dashboard does not work for me, as I have multiple children on the dashboard and I need show confirmation if the user navigates to them as well.

Not sure how to resolve this one.

**Comment by HighSoftWare96** [comment]
I have a similar issue: I've put a canDeactivate guard inside a lazy loaded module component, but when I try to navigate from the lazy loaded module (and the component with the guard) to the root module (app.module.ts) the canDeactivate guard is not even triggered.... Can this be reconducted to this issue or similar?

**Comment by mconti80** [comment]
I still have the problem with angular 7. I can't figure out how to make canDeactivate work with lazy loading. I've tried @picninim solution by putting canDeactivate in a parent route, declare all other routes as children and load with RouterModule.forChild() at main component level, but I didn't succeed.

And by the way, why one who would like to use 2 pretty common feature in a very likely use case (a deactivation guard used in a lazy loaded app) has to write lines of code that are completely different from any documented example? And why angular site has not a clear working example of this pretty common use case?
