### ISSUE TITLE
fakeAsync should trigger change detection

### ISSUE THREAD

**Issue by heathkit** [angular/angular#16878]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When writing tests that use `fakeAsync`, users currently need to manually trigger change detection. This is because `fakeAsync` can't fully simulate task updates, so NgZone running within fakeAsync will never emit `onMicrotaskEmpty` events, and thus change detection will not run.

We currently fix this by allowing users to call `fixture.detectChanges()`, but users are often confused about when and why they need to do this. Users tend not to think about change detection in detail until they start writing unit tests, which creates some friction. 

**Proposed solution**

Angular runs change detection when there are no more microtasks, just before execution returns to the browser. fakeAsync has a `tick()` function that simulates the passage of time, where `tick(0)` will flush all pending microtasks. Thus, it's reasonable to expect that change detection should run every time `tick()` is called, since this implicitly flushes all microtasks.

This could be done either by modifying fakeAsync such that it can make NgZone emit onMicrotaskEmpty events, but an easier solution might just be to have the `tick()` function directly invoke change detection.

This might not be the right behavior if the app is using an alternate change detection strategy, such as OnPush or something custom. We should still allow people to call `fixture.detectChanges()`, but we should also by default do a change detection pass with every `tick()` call, since this would be less surprising to users.

**Comment by JiaLiPassion** [comment]
@heathkit , I would like to make a PR to implement this feature, I will let you review when I finished.

**Comment by heathkit** [comment]
Please check with @vikerman first - we have work along these lines internally.

**Comment by JiaLiPassion** [comment]
@heathkit , got it, thank you !
@vikerman , could you provide some more information about this one? thank you!

**Comment by jessicajaniuk** [comment]
Closing as this has insufficient votes to be added for consideration in our feature requests process. Feel free to open a new issue if this is still a need. Thank you.
