### ISSUE TITLE
docs(aio): One code block in tutorial pt. 5 not shown on angular.io

### ISSUE THREAD

**Issue by nikwen** [angular/angular#16870]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Go to https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

In the section "Update AppModule", instead of the code I see the following:

```
+makeTabs( toh-5/ts/src/app/app.module.ts, toh-5/ts/src/app/app.module.3.ts, null, src/app/app.module.ts (after), src/app/app.module.ts (before)) :marked
```

**Expected behavior**

There should be a code block as everywhere else.

**Please tell us about your environment:**

Firefox 53.0 on 64 bit Fedora

**Comment by gkalpak** [comment]
This has been fixed in the latest (yet to be released) [version][1].

[1]: https://aio-staging.firebaseapp.com/tutorial/toh-pt5

**Comment by nikwen** [comment]
Thanks. :)
