### ISSUE TITLE
Any Input attribute named 'style' failing in PhantomJS

### ISSUE THREAD

**Issue by puroboros** [angular/angular#16887]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When you make a Component with an attribute with @Input() named style, PhantomJS will produce a TypeError: Failed: Attempted to assign to readonly property.

It works properly with any other navigator.

**Expected behavior**

It shouldn't fail in PhantomJS

**Minimal reproduction of the problem with instructions**

export class StyleComponent implements OnInit {
  @Input() style: any;
}
in app.html: <app-style [style]="whatever"></app-style>

I've detected this bug using primeng, wich uses [style] property to pass style to its components, and then I found in an issolated project this weird behaviour.

**What is the motivation / use case for changing the behavior?**

With this bug, developers may not use an attribute named style (wich is a name very usual for an input attribute) if they want to test with PhantomJS their code.

**Please tell us about your environment:**

Windows 7, ng-cli 1.0.0, npm 4.1.2, node 6.9.5

* **Angular version:** 4.1.2

* **Browser:** [ PhantomJS ]

 
* **Language:** [ ES5]

* **Node (for AoT issues):** `node --version` =   6.9.5

**Comment by wKoza** [comment]
duplicate #14910 ?

**Comment by tbosch** [comment]
Hello,
could you create a reproduction as a Github branch?

**Comment by puroboros** [comment]
Hi, I uploaded the simplest example so you can reproduce it here
https://github.com/puroboros/ngphantomjsbug
I'm very new at open source projects and I don't know how I should open a branch to show the error, sorry.

**Comment by wKoza** [comment]
You use `schemas: [NO_ERRORS_SCHEMA]`in your test and you don't declare StyleComponent. So, in your test, app-style is a simple HTML Element and with webkit, you can't rewrite style attribute.
In your case, you have a problem with your test. It's not a bug form Angular

**Comment by connor4312** [comment]
I can also consistently reproduce this in Safari.

**Comment by pkozlowski-opensource** [comment]
So it sounds like the original was due to trying to bind to the native `style` property of a DOM element and those are read-only so it failed rightfully. 

The other aspect of the problem is that author probably meant being to the `style` property of a component and a component wasn't matching due to a type / declaration mistake. Currently we are not good at detecting those cases but it is already tracked in  #24376
