### ISSUE TITLE
Need to expose API in HammerGestureConfig to control stoppropagation or preventDefault in Hammerjs

### ISSUE THREAD

**Issue by zhaxi** [angular/angular#16885]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently If we use hammerjs to control page scrolling and element scrolling using hammerjs, both the page and element will detect swipe action and react. I can't find the API in HammerGestureConfig to control the stoppropagation or preventDefault in hammerjs.
**Expected behavior**

If I'm swiping on the element in the page, I don't want the page go scrolling. 
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OSX, Visual Studio
* **Angular version:** 2.0.X

Angular 4.1.3
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All browsers
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =

**Comment by tbosch** [comment]
Angular has only limited support for hammerjs. We only have it for convenience.
For cases like this, the best way to solve it is to create a `EventManagerPlugin` yourself, similar to our `HammerGesturesPlugin` (see https://github.com/angular/angular/blob/master/packages/platform-browser/src/dom/events/hammer_gestures.ts). This way, you can control everything about hammerjs.
