### ISSUE TITLE
Static reflector should treat Object.freeze() as a no-op

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#16882]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**

An error is generated if the use uses `Object.freeze()` in a metadata expression.

**Expected behavior**

Calling `Object.freeze()` should be treated as a no-op.

**Minimal reproduction of the problem with instructions**

Wrap any expression in `Object.freeze()`.

**What is the motivation / use case for changing the behavior?**

Improve economics. Objects that are used at runtime for const values cannot be frozen if the value is also referenced by metadata.

**Comment by gkalpak** [comment]
For reference, the Ivy compiler currently supports [Object.assign()][1] (but the infrastructure is in place to support more methods).

BTW, this is related to #21265 (which is about `Array` methods).

[1]: https://github.com/angular/angular/blob/168a393589f80bd2fa6fb3fb6235754c5e75a384/packages/compiler-cli/src/ngtsc/partial_evaluator/src/builtin.ts#L44-L62

**Comment by JoostK** [comment]
Although we have the infrastructure in the static evaluator today, that's only there to support ngcc. I also believe this adds little value today, as the Ivy compiler is less strict in the metadata that it needs to statically understand.
