### ISSUE TITLE
Could not resolve on lazy loading modules

### ISSUE THREAD

**Issue by AyzPat** [angular/angular#16888]
ERROR in Could not resolve ".../admindashboard/admindashboard.module" from "/Users/Desktop/my_app/public/src/app/sudashboard/sudashboard.module.ts"
guys i get this error when I run ng build -op dist -w and immediately wen I make some changes and automatically when the app runs again in the watch mode this error is gone, I am not able to figure out y

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
