### ISSUE TITLE
Documentation issue - Prefixing private variables with underscore - Style Guide vs Intercepting inputs through a setter

### ISSUE THREAD

**Issue by hisham** [angular/angular#16893]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The style guide says to avoid [prefixing private properties with underscores](https://angular.io/styleguide#!#03-04) but the example in Component Communication about intercepting change to a [property via a setter](https://angular.io/docs/ts/latest/cookbook/component-communication.html#parent-to-child-setter) does exactly that. 

**Expected behavior**

Either we change the style guide to take account this exception, or change the component communication example to have variables with no underscore. 

**Minimal reproduction of the problem with instructions**

Contrast https://angular.io/styleguide#!#03-04 with https://angular.io/docs/ts/latest/cookbook/component-communication.html#parent-to-child-setter

**What is the motivation / use case for changing the behavior?**

Consistent easy to understand documentation and best practices.

**Comment by ericmartinezr** [comment]
Related https://github.com/angular/angular.io/issues/1108#issuecomment-213580426 (the entire issue discusses this)

**Comment by mlc-mlapis** [comment]
I think that the whole topic is about personal preferences and customs ... and the exception which is necessary for setter/getter only just confirms that.

**Comment by wardbell** [comment]
Smart minds may disagree. Decisions must be made. Nothing here persuades me we should change this. Closing.
