### ISSUE TITLE
TemplateURL - Relative Path not resolving.

### ISSUE THREAD

**Issue by Davy-F** [angular/angular#16891]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
With the latest version of Angular 4.1.3, we need to use Relative URL's for TemplateURL on the components. 

These components are being used within an Angular Library I am building. 
The library compiles and is then referenced as a dependency in a new application.

Here is the old code I had within a Nav.Component :
```
@Component({
  selector: 'navigation',
  templateUrl: 'app/components/nav.component.html',
  styleUrls: ['app/components/nav.component.css'],
  providers:[CredentialManagementService]    
})
```

New Proposed Code:
```
@Component({
  selector: 'navigation',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.css'],
  providers:[CredentialManagementService]    
})
```

However I am getting the following error:

> :3000/nav.component.html Failed to load resource: the server responded with a status of 404 (Not Found)

**Expected behavior**
The path should route correctly to nav.component.html which is in the same folder as the nav.component.ts file.

**Minimal reproduction of the problem with instructions**
Since we are building a library which isn't quite yet finished, it is quite hard to reproduce a plunker for another another environment. 

However hopefully someone will have some guidance/help with how the new TemplateURL's work.
As you can see from the above example, we have a standard typescript component which is referencing a html template. The directory is similar to this:

>app
>>components
>>>nav.component.ts
>>>nav.component.html**

So I need to reference the 'nav.component.html' as a templateURL within 'nav.component.ts'.
Both of these files are in the same folder.

**What is the motivation / use case for changing the behavior?**
Upgrading to the latest version of Angular 4.1.3. 
Ideally need to use relative paths in the URL as absolute paths / module.id are now deprecated.

**Please tell us about your environment:**
Windows 7. Visual Studio Code. 

* **Angular version:** 4.1.3

* **Browser:** [Chrome v58 ]
 
* **Language:** [Typescript 2.3 / ES6]

**Comment by tbosch** [comment]
This is a technical restriction when running in JIT mode, and requires the component author to add the `moduleId` property. See e.g. [this article](https://blog.thoughtram.io/angular/2016/06/08/component-relative-paths-in-angular-2.html) about it.

In AOT mode, this works as expected.

**Comment by Davy-F** [comment]
Sorry, but this isn't a fix.

According to the angular [changelog](https://angular.io/docs/ts/latest/guide/change-log.html) and the latest update:
> You no longer need to write @Component({ moduleId: module.id }), nor should you.

This doesn't seem to be the case as I'm still getting 404 'not found' errors.

**Comment by Davy-F** [comment]
Could this issue be reopened please, @tbosch @chuckjaz ? As I believe it is a genuine bug.

As mentioned in my previous comment, relative paths used within a node module do not get resolved.
For example, if I have an imported nav.component.ts in my 'node_modules' directory with a nav.component.html file in the same folder, you would usually expect the following code to work:

**nav.component.ts:**
`templateUrl: './nav.component.html'
`

However Angular then looks for nav.component.html in the following directory:

> "app/components/nav/nav.component.html"

...when really the nav.component.html template is in...

> "node_modules/CustomLibrary/components/nav/nav.component.html".


This issue cropped up whilst reusing code within an Angular common library, which gets imported into node_modules for future projects/re-usability. 

Thank you.

**Comment by VijetaH** [comment]
Same issue.

**Comment by Davy-F** [comment]
@VijetaH Did you have any luck solving this? Currently I'm having to write the full path which isn't ideal.

**Comment by darincardin** [comment]
The answer is: don't use angular 2. It is extremely bug prone, especially the more advanced stuff. Don't even try to configure AOT. I know that is not the answer you wanted. Trust me, its not the answer I wanted. But it is simply not stable at this point.

**Comment by Yugloocamai** [comment]
I have to say, I'm starting to agree with @darincardin.  The immense amount of dev time spent trying to make things work is not even close to worth it.  I could have built my own framework by now.

**Comment by rydergillen-compacSort** [comment]
/Agree... the DEV overhead required for getting a BASIC Angular working is a complete joke. The 1200+ open bugs should have been a red flag
