### ISSUE TITLE
Cannot get component-provided service from injector

### ISSUE THREAD

**Issue by aeternusrahl** [angular/angular#16892]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Since upgrading to angular 4.x, I am unable to use `Injector` to get a service instance that is provided in the @Component definition. This was possible in angular 2.4.10 but throws an exception in 4.0.3, 4.1.3. 

```
ERROR TypeError: Cannot read property 'instance' of undefined
    at Object.resolveDep (provider.ts:499)
    at Injector_.get (refs.ts:548)
    at new AppComponent (app.component.ts:17)
    at createClass (provider.ts:365)
    at createDirectiveInstance (provider.ts:192)
    at createViewNodes (view.ts:291)
    at createRootView (view.ts:223)
    at callWithDebugContext (services.ts:645)
    at Object.debugCreateRootView [as createRootView] (services.ts:89)
    at ComponentFactory_.create (refs.ts:125)
```    

**Expected behavior**
I would expect to be able to resolve an instance of any service that can be injected into the Component's constructor via the component's Injector instance.

**Minimal reproduction of the problem with instructions**
The following component will throw the exception (taken from angular quickstart project).
```
import { Component, Injectable, Injector } from '@angular/core';

@Injectable()
export class MyService {
  say(): void {
    console.log('saying hi');
  }
}

@Component({
  selector: 'my-app',
  template: `<h1>Hello {{name}}</h1>`,
  providers: [MyService]
})
export class AppComponent {
  name = 'Angular';
  constructor(injector: Injector) {
    let service = injector.get(MyService);
    service.say();
  }
}
```

[https://embed.plnkr.co/xZxVa1EtFvwASl2m48vD](https://embed.plnkr.co/xZxVa1EtFvwASl2m48vD)

However if you also inject `MyService` into the component, then no exception is thrown and the service can be retrieved via the injector as I would expect.

```
// WORKS
constructor(injector: Injector, anotherService: MyService) {
    let service = injector.get(MyService);
    service.say();
  }
```

**What is the motivation / use case for changing the behavior?**
In my app I have many component-level service classes which implement various behaviors which can be used by my components. However, unlike regular services, I need these to receive component lifecycle events--ngOnInit, ngOnDestroy. Because I need to mix-and-match these behaviors, I do not want to use inheritance on the component class.

To achieve this, I use ReflectiveInjector to manually instantiate these services and stash the instances in a map so that I can forward lifecycle events to them. 

```
// create a reflective injector using the Component's injector as the parent
let injector = ReflectiveInjector.resolveAndCreate([], injector);
// create an instance of one of my component-level services. These services 
// are @Injectable() and may depend on other services provided by the Component.
let instance =injector.resolveAndInstantiate(type);

// .... when the ngOnDestroy is invoked on the Component
if ('ngOnDestroy' in instance) {
  instance.ngOnDestroy();
}
```

This worked well prior to upgrading to angular 4. Now the exception listed above is thrown when I try to create the instance of one of my services that depends on another service provided in the @Component definition.

**Please tell us about your environment:**

Running on OSX Sierra, WebStorm, npm, webpack.

* **Angular version:** 4.1.3

* **Browser:** 
Able to reproduce in Chrome 58 and FireFox 53 (OSX)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Using typescript 2.2.1

* **Node (for AoT issues):** `node --version` =   
node 6.10.1

**Comment by aeternusrahl** [comment]
As an additional workaround, if you can move the injector code above from the constructor into `ngOnInit`. In the above example the component class is being instantiated before the service (due to the order of the nodes in createViewNodes).

```
@Component({
  selector: 'my-app',
  template: `<h1>Hello {{name}}</h1>`,
  providers: [MyService]
})
export class AppComponent {
  name = 'Angular';
  constructor(private injector: Injector) {
    
  }

  ngOnInit(): void {
    let service = this.injector.get(MyService);
    service.say();
  } 
}
```

**Comment by CindySLiu** [comment]
I have similar problem, but mine is not component, it is super class. I want to use inheritance. Here is my error:
app.template.html:23 ERROR TypeError: Cannot read property 'instance' of undefined
    at Object.resolveDep (provider.ts:512)
    at Injector_.get (refs.ts:551)
    at ModalConsoleComponent.DynamicConsoleClass (dynamic-console.class.ts:46)
    at new ModalConsoleComponent (modal-console.component.ts:77)
    at createClass (provider.ts:378)
    at createDirectiveInstance (provider.ts:192)
    at createViewNodes (view.ts:292)
    at callViewAction (view.ts:768)
    at execComponentViewsAction (view.ts:686)
    at createViewNodes (view.ts:357)

My super class looks like:
export class DynamicConsoleClass {
    data: any;          // Console Type data

    protected typeBuilder: DynamicTypeBuilder;
    protected _router: Router;
    protected _route: ActivatedRoute;
    protected injector: Injector;
    protected viewContainerRef: ViewContainerRef;
    protected _sessionService: SessionService;
    protected _interactionService: ConsoleInteractionService;
    protected _consoleDataService: ConsoleDataService;
    protected _dynamicConsoleService: DynamicConsoleService;


    protected sub: Subscription;
    protected selectedRowsSubscription: Subscription;
    protected changeMenuStateSubscription: Subscription;
    protected doublieClickRowSubscription: Subscription;
    
    protected viewHtml: string;
    protected componentRef: ComponentRef<DynamicConsoleInterface>;

    @ViewChild('mainContent', { read: ViewContainerRef })
    mainContent: ViewContainerRef;

    @Output() public openModalDialog: EventEmitter<any> = new EventEmitter<any>();

    constructor(injector: Injector) {
        this.typeBuilder = injector.get(DynamicTypeBuilder); <== failed here
        this._router = injector.get(Router);
        this._route = injector.get(ActivatedRoute);
        this.injector = injector.get(Injector);
        // this.viewContainerRef = injector.get(ViewContainerRef);
        this._sessionService = injector.get(SessionService);
        this._interactionService = injector.get(ConsoleInteractionService);
        this._consoleDataService = injector.get(ConsoleDataService);
        this._dynamicConsoleService = injector.get(DynamicConsoleService);

    }

My subclass looks like:
@Component({
    moduleId: module.id,
    selector: 'modal-console',
    template: `<div #mainContent></div>',
    providers: [DynamicTypeBuilder]
})
export class ModalConsoleComponent extends DynamicConsoleClass implements OnInit, OnDestroy, DynamicConsoleInterface {
    title: string;
    buttons: any = { add: false, save: false, ok: false, yes: false, no: false, cancel: true };

    private _tabService: ConsoleTabService;

    private tabSelectSubscription: Subscription;
    private tabOpenSubscription: Subscription;
    private consoleSaveCompleteSubscription: Subscription;

    // Tab Filter Value
    private set tabFilterValue(v: string) {
        this._interactionService.tabFilterValue = v;
    }

    private get tabFilterValue(): string {
        return this._interactionService.tabFilterValue;
    }

    constructor(injector: Injector, private vCR: ViewContainerRef, private cdr: ChangeDetectorRef) {
        super(injector);
        this.viewContainerRef = vCR;
        this._tabService = injector.get(ConsoleTabService);
    }

What is workaround for me?

Thanks in advance!!!

**Comment by JoostK** [comment]
I am able to reproduce in Angular 4.1.3 as reported, but it works correctly in Angular 4.2.0 so it looks like this has been resolved a long time ago.
