### ISSUE TITLE
Input value depend of Media Query

### ISSUE THREAD

**Issue by MiguelAngelLV** [angular/angular#16896]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Actually, for media query, each component must implement the its own system for detected the change and create specific input

**Expected behavior**

The components could add a input decorator to support a media query values.

```
@Component({
  selector: 'mycomponet',
  template: `
  <div class="component">
    <div [hidden]="!visible">
      <ng-content></ng-content>
    </div>
 </div>`})
export class Component {
  @Input(media = true)
  visible: boolean = true;
}
```

```
<mycomponent visible="true" visibile.xs="false" visibile.gt-xs="true"><mycomponent>
```

**What is the motivation / use case for changing the behavior?**
Add fast media query support for all component, as Material components

**Comment by pkozlowski-opensource** [comment]
I don't think we want to tie `@Input()`s to media queries like this. What you would like to do instead is something along those lines: 
```
<mycomponent [visible]="mediaQueryUtil.screenSize !== 'xs'"><mycomponent>
```

or 

```
<mycomponent *ngIf="mediaQueryUtil.screenSize !== 'xs'"><mycomponent>
```
