### ISSUE TITLE
Docs are out of date (4.0 instead of 4.1)

### ISSUE THREAD

**Issue by Kapeli** [angular/angular#16909]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
The docs at https://angular.io/docs/ts/latest/ say they are for Angular 4.0.

**Expected behavior**
The docs should be for Angular 4.1.

**Minimal reproduction of the problem with instructions**
Go to https://angular.io/docs/ts/latest/.

**Comment by ericmartinezr** [comment]
They are working on the new docs here https://aio-staging.firebaseapp.com/

**Comment by Kapeli** [comment]
The sidebar at https://aio-staging.firebaseapp.com/docs shows "v4.0.0". Isn't the latest version 4.1.3?

**Comment by petebacondarwin** [comment]
I'll fix this.
