### ISSUE TITLE
Router should support RouteConfigs with paths that contain hashes

### ISSUE THREAD

**Issue by TommyM** [angular/angular#1690]
I think that RouteConfig should support hashes. I would like to have the following type of urls should be supported by the router:
```
http://localhost/#/one
http://localhost/#/two
```

Imagine the following App:
```javascript
@Component({
  selector: 'app'
})
@View({
  template: `
    <a router-link="one">Page 1</a>
    <a router-link="two">Page 2</a>
    <router-outlet></router-outlet>
  `,
  directives: [RouterLink, RouterOutlet]
})
export class App {
  constructor(@Inject(Router) router: Router) {
    router.config({
      'path': '#/one',
      'component': Comp1,
      'as': 'one'
    });

    router.config({
      'path': '#/two',
      'component': Comp2,
      'as': 'two'
    });
  }
}
```
I expect to be able to click on the links to navigate between the two components. This doesn't work because of the following code in Location:
```javascript
  _onPopState(_) {
    ObservableWrapper.callNext(this._subject, {
      'url': this._location.pathname
    });
  }
```

With the fix supplied in #1689 and the following change to Location the links in my app will work and the router works like I expected. I am not sure if this would conflict with Dart (I know nothing about Dart tbh) or if there are other reasons to not support hashes in urls.

```javascript
_onPopState(_) {
  ObservableWrapper.callNext(this._subject, {
    'url': this.path()
  });
}

path() {
  return this._location.pathname + (isPresent(this._location.hash) ? this._location.hash : '');
}
```

**Comment by TedSander** [comment]
@naomiblack can I get this on the GT hotlist and get the priority increased? It is blocking some of our routing evaluation.

**Comment by btford** [comment]
Landed in https://github.com/angular/angular/pull/2692
