### ISSUE TITLE
**docs(aio):** toh-pt5.html missing code

### ISSUE THREAD

**Issue by vuelto** [angular/angular#16915]
**I'm submitting a ...**  (check one with "x")
```
[XXXX ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The "Update Appmodule" section displays this...

`+makeTabs( toh-5/ts/src/app/app.module.ts, toh-5/ts/src/app/app.module.3.ts, null, src/app/app.module.ts (after), src/app/app.module.ts (before)) :marked The revised and simplified AppModule is focused on identifying the key pieces of the app.`

**Expected behavior**

Display the changes that should have been made to the code in the section above.

**Minimal reproduction of the problem with instructions**
Point your browser here...
https://angular.io/docs/ts/latest/tutorial/toh-pt5.html#!#update-appmodule-

**What is the motivation / use case for changing the behavior?**
So that nubes like me can know what code changes should look like.

**Please tell us about your environment:**
Ubuntu Linux 16.04

* **Angular version:** 2.0.X
Dunno

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chromium Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Dunno

* **Node (for AoT issues):** `node --version` =  Dunno

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/16913

**Comment by vuelto** [comment]
Yep, it is a dupe.

DoH!
