### ISSUE TITLE
Animations Timing -- order of delay does not match up with css3 order

### ISSUE THREAD

**Issue by christinakayastha** [angular/angular#16912]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently the [angular animations](https://angular.io/docs/ts/latest/guide/animations.html#!#animation-timing) timing string has the order:
`duration delay timing-function`

This order is different than the CSS [animations syntax](https://www.w3schools.com/cssref/css3_pr_animation.asp): 
`animation: name duration timing-function delay ...`

**Expected behavior**
I expected the order to be `duration timing-function delay` to match with CSS syntax for consistency.

**Comment by matsko** [comment]
Thank you for bringing this up, but unfortunately we can't change this since it's been around for almost a year now and it was never intended to align with the css `animation` style value.
