### ISSUE TITLE
Docs - ROUTING - example code not showing

### ISSUE THREAD

**Issue by ido-ran** [angular/angular#16913]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In Tutorial -> 6. Routing -> Update AppModule the example code show this text:

`+makeTabs( toh-5/ts/src/app/app.module.ts, toh-5/ts/src/app/app.module.3.ts, null, src/app/app.module.ts (after), src/app/app.module.ts (before)) :marked The revised and simplified AppModule is focused on identifying the key pieces of the app.`

**Expected behavior**
See the source code of app.module.ts after the change.

**Minimal reproduction of the problem with instructions**
Open [routing tutorial page](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html) and search for `Update AppModule`.

**What is the motivation / use case for changing the behavior?**
fix the docs

**Please tell us about your environment:**
Chrome browser.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser

**Comment by ericmartinezr** [comment]
Looks fine here https://aio-staging.firebaseapp.com/tutorial/toh-pt5

**Comment by ido-ran** [comment]
I agree but in the [public URL of Routing Docs in the tutorial](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html#!#update-appmodule-), it looks like bellow.

![image](https://cloud.githubusercontent.com/assets/187938/26286744/3a76e860-3e75-11e7-84c7-478d73d3a468.png)

**Comment by ericmartinezr** [comment]
Yes, but the link I shared is where they're working the new docs so this can't be fixed since it is already fixed  :P

**Comment by gkalpak** [comment]
Closing since this has already been fixed (as @ericmartinezr mentioned) in the new version. It should be released soon (famous last words 😛). Thx for reporting it anyway, @ido-ran.
