### ISSUE TITLE
Angular 2 http posting empty form data

### ISSUE THREAD

**Issue by Rajashanmugam** [angular/angular#16914]
Hi,
I tried posting form data through http rxjs observable it went well till the last project and it is not working at this time have attached my code with this for your classification.

`import { Injectable } from '@angular/core';
import { Http, Response, Headers } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';

import { AppSettings } from '../app.settings';

const contentHeaders = new Headers();
contentHeaders.append('Accept', 'application/x-www-form-urlencoded');
contentHeaders.append('Content-Type', 'application/x-www-form-urlencoded');

@Injectable()

export class UserService {

    private signin_url = AppSettings.BASE_URL + AppSettings.USER_SIGNIN;
    private signup_url = AppSettings.BASE_URL + AppSettings.USER_REGISTER;

    constructor(private http: Http) {

    }

    signin(user) {
        console.log('Inside signin service ', user, { headers: contentHeaders });
        return this.http.post(this.signin_url, JSON.stringify(user))
            .map(this.extractData)
    }
    register(user) {
        console.log('Inside signup service ', user);
        return this.http.post(this.signup_url, JSON.stringify(user), { headers: contentHeaders })
            .map(this.extractData);
    }

    private extractData(res: Response) {
        console.log('Response ', res.json());
        let body = res.json();
        return body.data || {};
    }
    private handleError(error: Response | any) {
        // In a real world app, you might use a remote logging infrastructure
        let errMsg: string;
        if (error instanceof Response) {
            const body = error.json() || '';
            const err = body.error || JSON.stringify(body);
            errMsg = `${error.status} - ${error.statusText || ''} ${err}`;
        } else {
            errMsg = error.message ? error.message : error.toString();
        }
        console.error(errMsg);
        return Observable.throw(errMsg);
    }

}
![image](https://cloud.githubusercontent.com/assets/27273337/26285652/7a373652-3e71-11e7-8750-cb72b69c9d30.png)
`

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
