### ISSUE TITLE
How to set variable key as #variable="ngModel" in form input?

### ISSUE THREAD

**Issue by godbasin** [angular/angular#16920]
**I'm submitting a ...**  (check one with "x")
```
[x] support request
```

I'm updating my project's angular version from `v2.0.0-beta.6` to `v4.1.1`.

Normally, I update 
```
<input type="text" ngControl="name" .../>
```
 to
```
<input type="text" #name="ngModel" .../>
```

It works well in my project until I met this:
```
<input type="text" required ngControl="{{[param.key]}}"  [(ngModel)]="params[param.key]" ... />
```

How can I set the attribute name variable? 
Thanks!

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
