### ISSUE TITLE
routeConfig routeConfig BUG

### ISSUE THREAD

**Issue by herohoner** [angular/angular#16922]
```
package.json

    "@angular/animations": "4.1.1",
    "@angular/common": "4.1.1",
    "@angular/compiler": "4.1.1",
    "@angular/core": "4.1.1",
    "@angular/forms": "4.1.1",
    "@angular/http": "4.1.1",
    "@angular/platform-browser": "4.1.1",
    "@angular/platform-browser-dynamic": "4.1.1",
    "@angular/platform-server": "4.1.1",
    "@angular/router": "4.1.1",
    ...
```
I want to user dynamic route ,but ...  

the following code

```
private updateRouteConfig(routes){
        let a={
            path: '900000109',
            loadChildren: '../../system/usermanager/bf-user-manager.module#BfUserManagerModule'
        }
        let path = '900000119';
        let loadChildren = "../../system/usermanager/bf-user-manager.module#BfUserManagerModule";
        let b={
            path: path,
            loadChildren: loadChildren
        }

        this.activatedRoute.routeConfig.children.push(a)
        this.activatedRoute.routeConfig.children.push(b)
    }
```

and then the  result is

![2017-05-22_164724](https://cloud.githubusercontent.com/assets/19522627/26299982/5e803550-3f0f-11e7-9861-b5a52bdf823d.png)

**Comment by herohoner** [comment]
My English is not really good, Sorry.  Hoped that you can understand

**Comment by kenisteward** [comment]
What is the problem here?  I can't tell what issue you are having.

**Comment by herohoner** [comment]
The route is not initialized,The only way to use a string initialized successfully, Use of Variable not initialized successfully.
![2017-05-22_164724](https://cloud.githubusercontent.com/assets/19522627/26335164/a11687e2-3f9c-11e7-87e0-aadcde1694a1.png)

**Comment by kenisteward** [comment]
I'm not able to replicate.  Please create a plunkr with the problem you are having and use the latest stable which looks like 4.1.3 (4.2.0.rc1 is out as well)

**Comment by herohoner** [comment]
thanks form you time , that this problem has been solved. Is caused by the webpack pack .
