### ISSUE TITLE
Force a model value to be changed via ngKeypress doesn't reflect the ngValue on itself

### ISSUE THREAD

**Issue by betonetotbo** [angular/angular#16925]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Force a model value to be changed via ngKeypress doesn't reflect the ngValue on itself.

**Expected behavior**
After change the value, the ngValue must be evaluated and the input value must be updated.
Using angular 1.6.x this doesn't occurs.

**Minimal reproduction of the problem with instructions**
https://codepen.io/betonetotbo/pen/LyMNpK

**What is the motivation / use case for changing the behavior?**
Maintain the same behavior between angular 1.5 and 1.6

**Please tell us about your environment:**
Windows 10 PRO, Eclipse Neon JEE, Spring Boot

* **Angular version:** 1.5.8~

* **Browser:** [Chrome 58]
 
* **Language:** [ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` = not applicable

**Comment by ericmartinezr** [comment]
This repo is for angular. You're looking for angular/angular.js
