### ISSUE TITLE
docs: document new syntax for local assignment in expressions

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#16928]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I checked the [Template Syntax](https://angular.io/docs/ts/latest/guide/template-syntax.html) page, and didn't see docs for the new assignment syntax:

```html
<div *ngIf="me$ | async as me">
  {{ me.name  }}
  {{ me.title }}
</div>
```

Would be nice to have it included there.

**Comment by kapunahelewong** [comment]
Hi @jeffbcross! I'd be happy to document this but don't quite get it. Would you recommend a reference for me? Maybe a talk or something where I could get started? Thanks!

**Comment by petebacondarwin** [comment]
This is being tracked in the aggregate issue of #43485 for which we need to create a project proposal.

**Comment by JeanMeche** [comment]
It is now mentioned in the control flow page: https://angular.dev/guide/templates/control-flow
Also this is likely to be superseeded by #15280. 
I think we can close it for now.
