### ISSUE TITLE
aio: add staging site to google webmaster

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16932]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by IgorMinar** [comment]
done:

<img width="950" alt="screen shot 2017-05-31 at 11 17 13 am" src="https://cloud.githubusercontent.com/assets/216296/26642552/c4250d32-45f3-11e7-9514-da4595af3540.png">
