### ISSUE TITLE
Story: Multiple independent Apps on same Page for CMS Content Extensions

### ISSUE THREAD

**Issue by iJungleboy** [angular/angular#16930]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Story / Current behavior**
Based on what I understand ATM, a production grade Angular 4 App will create a few compact JS files which work together, but assume that they are the only Angular stuff on the existing HTML page. This prevents using Angular in a lot of important CMS use cases, which require adding multiple standalone parts to a page. It also causes a lot of trouble when needing to inject instance-specific initialization values (like an instance ID needed to talk to the server APIs). 

In Angular 1 it was possible to work around this limitation by loading the partial libraries one-by-one (so that the CMS could ensure certain libraries were only loaded once) and by creating a custom bootstrapper, which would inject initialization values for each instance of the app. In Angular 4, this seems impossible or extremely difficult. 

**Expected behavior**
Many CMSs allow content-editors to add multiple parts to a page - for example a gallery + an interactive graphic + a contact form and some content. Many of these parts will be JS based as in the example of the touch-gallery and the contact form. To function properly, these parts should be

1. autonomous, so that adding one doesn't require the other
2. side-effect free, so that adding the second doesn't break the first

In addition to this, the same app could be inserted multiple times (imagine some text + a gallery + some more text + more galleries). So both of these scenarios must work:
1. multiple instances of the same app
2. various instances of different apps

For this to work properly, each app must be fed with initialization parameters like an instance-id, which must be provided by the surrounding HTML around the `<app-something>` tag and/or by a custom JS bootstrapper, which can say _bootstrap the first app-something with these values, the second with these_. 

It would also be beneficial if certain optimizations could easily prevent loading certain libraries multiple times, but this is of much lower priority. 

**Minimal reproduction of the problem with instructions**
It's very hard to provide a running example, but basically just try to add two different Angular apps to the same page, and you'll be met by a plethora of errors - for example because some Angular parts complain about pre-existing initialization etc. 

In Addition I've tried many ways to inject external parameters, but all the methods I found rely on cluttering the `window` variable or other global mechanisms, which doesn't work when you have different values for each instance. I have also not found a way to access the initial tag (it could contain initialization values), as it's not available at the moment the app is being built, especially not during the APP_INITIALIZER. 

**What is the motivation / use case for changing the behavior?**
Very important use case in many CMS-component scenarios. 
Note that we're explicitly talking about components which run in the CMS output, not admin UIs. Admin-UIs could in some ways sync the development to somehow be compatible and work out the complex dependencies (but it would be nasty), whereas output-components are impossible to coordinate, as they are made by separate teams. 

**Please tell us about your environment:**
In my case I'm developing for [2sxc](https://2sxc.org/) a CMS built with [DNN](https://github.com/dnnsoftware/Dnn.Platform). 

* **Angular version:** 4.0.X

* **Browser:** all / not applicable
 
* **Language:** all using CLI / both normal build and prod

**Comment by dgroh** [comment]
+1

**Comment by VashJuan** [comment]
Can we bump this issue? Is there no solution/approach for this? (Maybe there's another approach that is moving forward - and solves these issues?)  I'm certainly concerned how to address this fairly basic issue before going further with Angular.

Thx for any pointers!

**Comment by iJungleboy** [comment]
To all - please vote for this with a thumbs-up for it to be considered in the features. It needs at least 20 votes, way more would be better.

**Comment by VashJuan** [comment]
Where do we actually vote: on your initial comment, or some list of issues? Thx for reinvigorating this issue!

**Comment by petebacondarwin** [comment]
@VashJuan - you give the issue description a thumbs up 👍 - see https://github.com/angular/angular/blob/e29eb8abfbfdfb793e08ac88e14b7ba6d2ff2136/docs/GITHUB_PROCESS.md#voting-phase

**Comment by VashJuan** [comment]
My question was more *where* to do so, but I've not found other places to vote, so I think it is the top/original item in this thread, not the ngular-bot announcement of a vote, not another page or anything. Thanks!

**Comment by VashJuan** [comment]
It seems to me that this issue may likely fit within an existing issue already on the roadmap:
https://angular.io/guide/roadmap#investigate-micro-frontend-architecture-for-scalable-development-processes

I know little about that issue currently, but will explore it & report back

**Comment by jessicajaniuk** [comment]
The new bootstrap APIs for standalone components should enable this functionality. You should be able to bootstrap multiple applications and individual components within those applications individually. Feel free to try these new APIs and report any issues that come with them so we can address them during the developer preview. Check out the [bootstrapApplication](https://angular.io/api/platform-browser/bootstrapApplication) and there's a PR that was merged today with the [createApplication API](https://github.com/angular/angular/pull/46475).
