### ISSUE TITLE
aio: update google analytics code and check what is being captured

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#16931]

**Comment by petebacondarwin** [comment]
I think this was opened as a project card by @IgorMinar. Can you shed some light on why this is a blocker?

**Comment by IgorMinar** [comment]
we can't stop collecting metrics during the transition. the GA metrics are a strong indicator of how well the new site is doing.

**Comment by petebacondarwin** [comment]
@IgorMinar can you confirm that GA is working as expected for the production site?

**Comment by IgorMinar** [comment]
yup. all good.
