### ISSUE TITLE
docs: ahead of time compilation

### ISSUE THREAD

**Issue by ionous** [angular/angular#16946]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

the source for "rollup-config.js" used by https://angular.io/docs/ts/latest/cookbook/aot-compiler.html has the following lines: 

```JavaScript 
export default {
   entry: 'src/main.js',
   dest: 'src/build.js', // output a single application bundle"
   // ...
```
dest seems incorrect. the explanatory text says:

> "The dest attribute tells Rollup to create a bundle called build.js in the **dist** folder."

which would imply "dist/build.js".

**Expected behavior**

rollup-config.js should probably specify:

```JavaScript 
export default {
  entry: 'src/main.js',
  dest: 'dist/build.js', // output a single application bundle"
  // ...
```

**Minimal reproduction of the problem with instructions**

visit https://angular.io/docs/ts/latest/cookbook/aot-compiler.html, examine the source for "rollup-config.js".

**What is the motivation / use case for changing the behavior?**

improving the documentation.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

angular2.0 docs as of monday May 22,2017.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by dherges** [comment]
Hi @ionous, is the change in #17072 what you expect?

**Comment by trotyl** [comment]
Obsolete, rollup no longer mentioned in doc.

**Comment by jenniferfell** [comment]
@trotyl Thanks! 

Double-checked. rollup-config.js is no longer mentioned in docs nor does it exist in the examples folder. Closing.
