### ISSUE TITLE
Wait for included css to be fully loaded before instantiating a component / finishing the compilation

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1694]
Use case:

A component needs to know how high it is. Right now it would schedule a promise / eventually use the new `size` event (see #1693). However, if we don't wait for nested CSS to be fully loaded before we instantiate a component the component has no way of knowing the right size.

The problem probably only appears for `NativeShadowDomStrategy`, as in the emulated mode we load nested stylesheets manually.

**Comment by tbosch** [comment]
Needed for migrating the GT calendar picker.

**Comment by tbosch** [comment]
@naomiblack I assigned this to M9, could you double check with Matan?

**Comment by tbosch** [comment]
The solution here is to also inline styles when using native shadow dom, so view instantiation stays synchronous.

**Comment by tbosch** [comment]
This will be solved automatically when #2459 is implemented.

**Comment by naomiblack** [comment]
@tbosch can you confirm this is closed?

**Comment by vicb** [comment]
it is not, but it should be fixed when #2563 gets merged - re-assigning to me as I own the PR

**Comment by jpsfs** [comment]
Hey,

Sorry to dig-up this issue but I think I've found a nasty side-effect from the inline style approach.

**Tested on alpha 30. This issue didn't occur on alpha 27.**

I'm doing a test app, building components based on a commercial theme. The theme css's have multiple references to other files (images, fonts, ...) using relative paths.

Example:

> Folder Structure:
```
index.html
| theme
    | css
        style.css
    | img
        progress.gif
```

> style.css:
```css
.elfinder-resize-spinner {
	position: absolute;
	width: 200px;
	background: url(../img/progress.gif) center bottom repeat-x;
}
```

**Error:**
*/img/progress.gif* not found. (that's true, it should look for the file on */theme/img/progress.gif*)

With this change, **relative paths are no longer calculated based on the css file paths**, but on the index.html file location.

Are you open to review this solution?

**Comment by yjbanov** [comment]
@jpsfs We have logic to correct relative URLs while inlining, but perhaps there's a bug. Please, file an issue.
