### ISSUE TITLE
Remove or move "Docs" sidenav item from the list in the mobile view

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16940]
<img width="515" alt="screen shot 2017-05-22 at 2 56 01 pm" src="https://cloud.githubusercontent.com/assets/216296/26330031/e971f52e-3efe-11e7-967e-642b7b9ede84.png">

The "Docs" item is already expanded under all the marketing menu items, so it's not necessary to list it there. Can we remove it? Or should we move it to be the last in the list of marketing pages and add a colon or something to suggest that the items under are the docs menu subitems?

**Comment by petebacondarwin** [comment]
OK, we should definitely not do this through hard coding rules into the viewer.
One option is to have two different TopBar navigation views: one for wide screen and one for narrow screen. (At the moment we use the same view for both screen widths).

I think it is worth keeping the "Docs" menu item in the narrow view, as it does actually point to a real page. So let's go with moving it to the bottom.
