### ISSUE TITLE
ROUTING & NAVIGATION - Example does not compile

### ISSUE THREAD

**Issue by ido-ran** [angular/angular#16954]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I've download the example code for [Routing & Navigation](https://angular.io/resources/zips/router/router.zip).

I've run `npm install` which complete successfully.

I've run `npm start` and got the following tcs errors:

```
npm start

> angular-io-example@1.0.0 prestart C:\Users\a\Documents\learn\angular\router
> npm run build


> angular-io-example@1.0.0 build C:\Users\a\Documents\learn\angular\router
> tsc -p src/

node_modules/@angular/platform-browser/animations/src/animation_renderer.d.ts(1,53): error TS2307: Cannot find module '@angular/animations/browser'.
node_modules/@angular/platform-browser/animations/src/providers.d.ts(8,276): error TS2307: Cannot find module '@angular/animations/browser'.

```

**Expected behavior**
The example code will compile and run.

**Minimal reproduction of the problem with instructions**
Download the example, run `npm install` and then `npm start`.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
I'm using Windows 10 Intel machine. Windows version 1511 OS Build 10586.873.

* **Angular version:** 2.0.X
Angular ~4.0.0.0 fpr all dependencies.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript version 2.2.2

* **Node (for AoT issues):** `node --version` =   
I'm using node version 6.10.2 and npm version 3.10.10.

**Comment by ido-ran** [comment]
I've followed a [SO suggestion](https://stackoverflow.com/a/43717202/355401) to delete `node_modules` and reinstall the latest `@angular/animation` library and it worked so it probably issues with my env.

**Comment by ido-ran** [comment]
I've download the example code again and run into the same problem so maybe it is a bug.

**Comment by gkalpak** [comment]
Thx for reporting. It has been fixed on the latest (yet to be released) [version][1].

[1]: https://aio-staging.firebaseapp.com/guide/router
