### ISSUE TITLE
tutorial ToH page 5

### ISSUE THREAD

**Issue by Lumpenstein** [angular/angular#16961]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Tabs for a section are not created.

**Expected behavior**

[https://angular.io/docs/ts/latest/tutorial/toh-pt5.html](url)
On the 5th page of the Hero-tutorial under the section Update AppModule the tabs are not being created, but it shows this code instead:

> +makeTabs( toh-5/ts/src/app/app.module.ts, toh-5/ts/src/app/app.module.3.ts, null, src/app/app.module.ts (after), src/app/app.module.ts (before)) :marked

* **Browser:** 

Chrome 5x, Mozilla

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/16913

**Comment by Lumpenstein** [comment]
Oh right, I dind't find that one while searching.
