### ISSUE TITLE
Multiple named validators per form field

### ISSUE THREAD

**Issue by rscottfree** [angular/angular#1696]
In Angular 2 is it possible to assign multiple validators to a single form input field? If not, I propose it be added.

I currently use the ui-validate directive in UI-Utils for this, and having something similar in Angular 2 would be nice.

The reason for this functionality is to display different error messages based on which validators failed. From the code example on the [blog post](http://angularjs.blogspot.com/2015/03/forms-in-angular-2.html) it looks like it's possible to check which validator failed but it's not clear if it is possible to declare multiple validators for a single field.

Syntax may look something like this:

```javascript
    {
        field: 'city', label: 'City',
        validators: { 'required': required, 'validCity': validCityName }
    }
```

And then checking them:
```html
<div *if="form.hasError('city', 'required')">This field is required</div>
<div *if="form.hasError('city', 'validCity')">This city not built on rock and roll</div>
```

**Comment by mhevery** [comment]
this is already planned.
