### ISSUE TITLE
Update aio docs with Angular instead of Angular 2

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/angular#16965]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

https://aio-staging.firebaseapp.com/resources

I see more than 43 mentions of `Angular 2` in the docs, please change it to only say `Angular`

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by wardbell** [comment]
I don't see 45 but I saw plenty. Addressed in PR #17679
