### ISSUE TITLE
ɵReflector  Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by gatimus** [angular/angular#16968]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
throws 

```
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵReflector', function calls are not supported. Consider replacing the
 function or lambda with a reference to an exported function, resolving symbol ɵreflector in [project path]/node_modules/@an
gular/core/core.d.ts, resolving symbol COMPILER_PROVIDERS in [project path]/node_modules/@angular/compiler/src/jit/compiler_
factory.d.ts, resolving symbol COMPILER_PROVIDERS in [project path]/node_modules/@angular/compiler/src/compiler.d.ts, resolv
ing symbol COMPILER_PROVIDERS in [project path]/node_modules/@angular/compiler/compiler.d.ts, resolving symbol AppModule in
[project path]/src/app/app.module.ts, resolving symbol AppModule in [project path]/src/app/app.mod
ule.ts
```

**Expected behavior**
provide `COMPILER_PROVIDERS` without error

**Minimal reproduction of the problem with instructions**
- `ng new project-name`
- add `import { COMPILER_PROVIDERS } from '@angular/compiler';` to `app.module.ts`
- add `providers: [ COMPILER_PROVIDERS ],` to `app.module.ts` 

```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { COMPILER_PROVIDERS } from '@angular/compiler';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [
    COMPILER_PROVIDERS
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**What is the motivation / use case for changing the behavior?**
Inject `Compiler` for runtime use.

**Please tell us about your environment:**
Windows 10 x64
Visual Studio Code 1.12.2
@angular/cli 1.0.4

* **Angular version:**
4.1.3

* **Browser:**
all
 
* **Language:**
TypeScript 2.2

* **Node (for AoT issues):**
7.8.0

* **Output from: `ng -v`.**
@angular/cli: 1.0.4
node: 7.8.0
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.4
@angular/compiler-cli: 4.1.3

**Comment by gatimus** [comment]
I can successfully provide the compiler on http://plnkr.co/edit/GAGoQtIi1pTyq8uUBbu1?p=preview dose that suggest an angular/cli issue and not an angular issue?

**Comment by gatimus** [comment]
I found out you can inject the `Compiler` with out importing or providing anything in your module. Is that the correct way?

**Comment by MichaelCPell** [comment]
What was your solution to this?  I can run `ng serve`, hit the error, and then save a file, and then it recompiles successfully.  But, no way to do that when running `ng build`...

**Comment by gatimus** [comment]
@MichaelCPell 
I just removed COMPILER_PROVIDERS from AppModule.
