### ISSUE TITLE
Add instructions for creating bs-config json file to the JS quickstart tutorial

### ISSUE THREAD

**Issue by Phansa** [angular/angular#16978]
**I'm submitting a ...**  (check one with "x")
[X] feature request

**Current behavior**
When working through the tutorial it just mentions the bs-config.json file but doesn't show where to place the file or the contents of it. To find the contents you have to scroll down to where it says "And here are the files:" and click bs-config.json. I was working through this tutorial without using the zipped code and this part was not clear to me until I looked at the final diagram.

**Expected behavior**
I would add a section showing the path / contents of the bs-config.json file along with instructions of where to place (much like the other files in the doc) to make this clearer.
A line to add could be similar to the package json instructions and say -
"Add a bs-config.json file to the project folder and copy/paste the following:"
(bs-config contents)

**Minimal reproduction of the problem with instructions**
N/A
**What is the motivation / use case for changing the behavior?**
Make it easier for people to use the javascript tutorial without having to download the zip file in advance

**Please tell us about your environment:**
Windows 10 cygwin

* **Angular version:** 2.0.X
2.4.10

* **Browser:** [all]
 
* **Language:** [all]

**Comment by wardbell** [comment]
The JS Quickstart has been removed from the docs (as has the non-cli QuickStart.  The`bs-config.json` was never essential anyway. Closing.
