### ISSUE TITLE
Benchpress: only use promises of selenium-webdriver and not the patch by traceur

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1697]
Right now, we are using both, promises of selenium-webdriver and the promises of traceur.
This leads to race conditions and prevents long stacktraces to show up correctly.

As selenium-webdriver now has an A+ compliant promise implementation, we can just use this (i.e. export this as global `Promise` function).

**Comment by tbosch** [comment]
See https://code.google.com/p/selenium/source/browse/javascript/node/selenium-webdriver/CHANGES.md

**Comment by mhevery** [comment]
@tbosch is this still an issue?

**Comment by tbosch** [comment]
Yes.
It's only relevant for JS though, where we don't have as lot of users yet.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
