### ISSUE TITLE
incorrect file path in js quickstart tutorial on the docs website

### ISSUE THREAD

**Issue by Phansa** [angular/angular#16977]
**I'm submitting a .
[X] bug report 

**Current behavior**
On this page  - https://angular.io/docs/js/latest/quickstart.html
it says "Add a new file , main.js, to the src/app/ folder as follows:"
when it should be "Add a new file , main.js, to the src/ folder as follows:"
The correct path is shown below this sentence (src/main.js)
![bootstrap_path](https://cloud.githubusercontent.com/assets/16921040/26382533/e5f0ce14-3ffa-11e7-9bf7-a141c8914b44.png)

**Expected behavior**
The page would display - "Add a new file , main.js, to the src/ folder as follows:"

**Minimal reproduction of the problem with instructions**
Visit  https://angular.io/docs/js/latest/quickstart.html

**What is the motivation / use case for changing the behavior?**
Instructions are incorrect

**Please tell us about your environment:**
Windows 10 

* **Angular version:** 2.0.X
2.4.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
I used google chrome but it is all
 
* **Language:** [all]

I tried to find where the source of this page's contents are but I could only find the typescript guide page here - https://github.com/angular/angular/blob/master/aio/content/guide/quickstart.md. Are the javascript doc pages somewhere else?

**Comment by wardbell** [comment]
Closing because we no longer support the JavaScript versions of documentation.
