### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by grapgrap** [angular/angular#16980]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I ran angular page in ie11

![image](https://cloud.githubusercontent.com/assets/16932142/26385826/2e80b68a-407d-11e7-962f-3d1c795e5c8b.png)

this mean is 'Cannot read property 'apply' of undefined or null'

![image](https://cloud.githubusercontent.com/assets/16932142/26385829/36e6409c-407d-11e7-8044-f605c33c36a0.png)

this problem occur only ie11.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
OS : Windows 10
Node: 6.10.2
NPM: 4.6.1

* **Angular version:** 4.1.1

@angular/cli: 1.0.1
node: 6.10.2
os: win32 x64
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.1

* **Browser:** IE 11
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.10.2

**Comment by pkozlowski-opensource** [comment]
IE11 doesn't support IE11 so you need to include an appropriate polyfill. Please check:
* https://angular.io/docs/ts/latest/guide/browser-support.html
* https://github.com/zloirock/core-js#ecmascript-6-object
