### ISSUE TITLE
Migration from 4.1.2 to 4.2.0-rc.0 -> cannot find animations.ngsummary in AOT

### ISSUE THREAD

**Issue by karolmie1** [angular/angular#16988]
[x] bug report 
[ ] feature request
[ ] support request 

**Current behavior**
My application is currently powered by angular 4.1.2

I am aware of need of importing animations module, so that's not the problem.

After upgrading to angular 4.2.0-rc.0 application still works, unless i try to make AOT build.
Then I'm left with: 

> ERROR in [at-loader] ./compiled/src/app/app.module.ngsummary.ts:74:22 
>     TS2307: Cannot find module '../../node_modules/@angular/platform-browser/animations.ngsummary'

Indeed, there is no such file, though folder 'animations' exists in that directory.

Dependencies were removed and redownloaded. Problem persists.

**Minimal reproduction of the problem with instructions**
For now I provide hardly minimal example: https://bitbucket.org/kmierzej/fragaria-webapp/branch/angular-upgrade

Then execute: npm run build:prod (won't compile)

**Please tell us about your environment:**
OS: linux
Package manager: yarn/npm (tried both)
Using Webpack as build tool.

* **Language:**
TypeScript 2.3.2 transpiled to ES5

* **Node (for AoT issues):** 
v7.10.0

**Comment by blacksonic** [comment]
I have something very similar when running tests:
`TypeError: undefined is not a constructor (evaluating 'this._compiler.loadAotSummaries(summaries)')`

**Comment by karolmie1** [comment]
Also, on other branch (material-module), on 4.1.2 when I tried to encapsulate animations using stuff into separate module, i've received similar error: `Cannot find module '../../../../node_modules/@angular/platform-browser/animations.ngsummary`, while the file was accessible under: `../../../../node_modules/@angular/animations`

In compile folder, I have 2 samey folders (look similar, but diff shows differences in contents):
 - `@angular/animations/browser`
 - `@angular/platform-browser/animations`

This might be connected.

**Comment by pkozlowski-opensource** [comment]
This issue is 3 yo and we've changed the compilation infrastructure multiple times since then. I'm going to close this one as obsolete for now as we haven't seen other reports and we won't investigate / fix Angular 4.x issues. 

Please open a new issue if you can still reproduce it with Angular 9. Thnx!
