### ISSUE TITLE
css in the picture packing problem

### ISSUE THREAD

**Issue by shaodahong** [angular/angular#16983]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

i use `ng new app`
I set up a div tag in index.html, give it a class box, and then I set this box `background: url ('./assets/images/user.jpg') no-repeat` in styles.css;

then i run ng build, Find the image packed in the root directory

**Expected behavior**

I hope that the picture resources can be unified in the `assets/images` directory or a unified directory, because when I css too much in the picture when this is not well managed！

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

@angular/cli: 1.0.0
* **node** : 7.10.0
* **os** : darwin x64
* **@angular/common** : 4.1.3
* **@angular/compiler** : 4.1.3
* **@angular/core** : 4.1.3
* **@angular/forms** : 4.1.3
* **@angular/http** : 4.1.3
* **@angular/platform-browser** : 4.1.3
* **@angular/platform-browser-dynamic** : 4.1.3
* **@angular/router** : 4.1.3
* **@angular/cli** : 1.0.0
* **@angular/compiler-cli** : 4.1.3

**Comment by chuckjaz** [comment]
Please report this in the https://github.com/angular/angular-cli project.
