### ISSUE TITLE
benchpress: make sure output of JsonFileReporter is consistent between Dart and JS

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1698]
In Dart, we create json files via `toJson` methods (see https://github.com/angular/angular/blob/master/modules/benchpress/src/measure_values.js#L15). However, these are not used in JavaScript, as JavaScript looks for `toJSON` files. 

Change our `toJson` method in `facade/lang` to also look for `toJson` methods (via the third argument of `JSON.toJson` in JavaScript).

**Comment by tbosch** [comment]
Yes, still an issue.

**Comment by mhevery** [comment]
Will not implement.
