### ISSUE TITLE
Make RequestOptions extensible

### ISSUE THREAD

**Issue by jameskleeh** [angular/angular#16987]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently because of the way request options are merged, it is impossible to allow for custom options without copy/pasting the entire Http class and RequestOptions class. This is mostly due to the fact that the `merge` method creates a new `RequestOptions` instance. This feature request is to improve the code so it can be easily extended to add custom options.

**Expected behavior**
I expect that if I extend Http and include my own RequestOptionsArgs interface, the options will not be squashed by the merging functionality.

**What is the motivation / use case for changing the behavior?**
I would like to have custom processing for authorization headers and 401 response handling. I would also like to disable that functionality on a per request basis.

**Please tell us about your environment:**
macOs, IntelliJ IDEA

* **Angular version:** 4.0.3

* **Browser:** All
 
* **Language:** TypeScript 2.2

* **Node (for AoT issues):** `node --version` =   7.7.2

**Comment by jameskleeh** [comment]
Another thought is to simply provide a place on `RequestOptions` where you can supply custom data, `additionalOptions: any`

**Comment by alxhub** [comment]
Sorry, feature requests are not being considered for the deprecated `Http`. Please use `HttpClient` instead (which does have interceptors!)
