### ISSUE TITLE
Angular compiler generates factories for components not found in a template or entry components

### ISSUE THREAD

**Issue by maximusk** [angular/angular#16984]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The component factory is generated for the component not used in a template and not added to the entry components list. See [this screenshot](http://i65.tinypic.com/rlcaxv.png)

**Expected behavior**
The docs say in [Why do we need entry components](https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#why-does-angular-need-_entrycomponents_-):

> If a component isn't an entry component or wasn't found in a template, the compiler **omits** it.

**Minimal reproduction of the problem with instructions**
Go to the [plunker](https://plnkr.co/edit/FRYot5Wz5LGb91dnIjij?p=preview) and open Dev tools->Source tab->plunkerPreviewTarget->ng://->AppModule->AComp.ngfactory.js

* **Angular version:** 4.1.3

**Comment by Toxicable** [comment]
I believe this is mainly focused at AOT since if you ran the same code in AOT you would get an error similar to `Cannot determine the module for class AComp`

**Comment by maximusk** [comment]
@chuckjaz, if it's identified as a bug by a core team I'm willing to prepare a fix, but I'd need some guidance

**Comment by tbosch** [comment]
Angular's jit compiler compiles all components that are mentioned in an `NgModule`, no matter if it is used or not. In that, it is similar to the AOT compiler.

This makes JIT compilation slower, but JIT is not intended for production use anyways, and doing it this way simplifies our internal code a lot.

**Comment by tbosch** [comment]
so this works as expected.

**Comment by maximusk** [comment]
@tbosch , so what's the use for `entryComponents` then? And does it also mean that this phrase in the docs

> If a component isn't an entry component or wasn't found in a template, the compiler omits it.

is not correct?
