### ISSUE TITLE
aio: side nav scrolling

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17009]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Sidenav content does not scroll up until the first menu item is at the top when scrolling the page. Additional spacing is originally there to provide room for the topnav toolbar.

<img width="1133" alt="screen shot 2017-05-25 at 12 09 34 am" src="https://cloud.githubusercontent.com/assets/2958442/26435625/96765324-40de-11e7-9edc-8fd70c336d42.png">

**Expected behavior**
Sidenav menu should scroll up until the first menu item is appropriately placed and then prevent any further scrolling up of the sidenav drawer, while allowing the rest of the content (right side) to continue scrolling.

**Minimal reproduction of the problem with instructions**
In full size view, go to Docs, open sidenav drawer and scroll down.

**Comment by gkalpak** [comment]
closing as a subset of #17096.
