### ISSUE TITLE
Benchpress: report wall clock time from start of first captured event until end of last captured event

### ISSUE THREAD

**Issue by goderbauer** [angular/angular#1700]
We want to know the total duration of a benchmark including time periods where the browser was doing nothing between events. For this, I would like to have a metric that captures the time from the start of the first event to the end of the last event within benchpress' execute function.

Example: When somebody schedules an asynchronous task (duration: 100ms) with a delay of 1s, benchpress right now will only report the actual execution time (100ms). The fact, that it took 1s to execute this is lost.

**Comment by mhevery** [comment]
@tbosch This has not been updated for a while. ls this still relevant?

**Comment by naomiblack** [comment]
obsolete.
