### ISSUE TITLE
aio: search bar on top of sidenav in mobile

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17008]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Search bar from topnav bar is visually on top of the sidenav drawer and accessible.
<img width="310" alt="screen shot 2017-05-25 at 12 02 53 am" src="https://cloud.githubusercontent.com/assets/2958442/26435615/7ed977a0-40de-11e7-8027-3d6141122360.png">

**Expected behavior**
Search bar should be visually behind the sidenav drawer and accessible only when sidenav is closed.

**Minimal reproduction of the problem with instructions**
Open sidenav drawer using hamburger menu in Docs in mobile view.

**Comment by gkalpak** [comment]
On my phone, the top toolbar is always above the sidenav, so everything looks as expected. Where awas this screenshot taken from?

**Comment by gkalpak** [comment]
Or is this an issue with #16228?

**Comment by sjtrimble** [comment]
@gkalpak This is an issue with the design refresh. It's because it removes the fixed toolbar for a more fluid experience (and more space for docs as well).

**Comment by sjtrimble** [comment]
The toolbar has a high z-index which is making the search box lay on top of the sidenav. If I change that for mobile views, the search box lays nicely underneath the sidenav but we loose the logo and sidenav button. I may need help from @gkalpak @petebacondarwin or @wardbell to move those items to the md-sidenav maybe as an `aio-nav-menu`.

**Comment by IgorMinar** [comment]
I can still see this issue: 
![screenshot_20170530-023134](https://cloud.githubusercontent.com/assets/216296/26573230/ce725d12-44d1-11e7-8c2e-26a2cb9bd011.png)

**Comment by gkalpak** [comment]
@IgorMinar: That's what this issue (#17008) is for 😛
