### ISSUE TITLE
Proposal - ReactiveForms: add AbstractControl.getChild<T> method

### ISSUE THREAD

**Issue by snerks** [angular/angular#17000]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`AbstractControl.get` allows a flexible `path` parameter, for specifying the required descendent `AbstractControl` to return.

**Expected behavior**

`AbstractControl.getChild<T>(key: keyof T)` would allow additional type safety, in the case where the required `AbstractControl` is a direct child of the instance `AbstractControl`-derived parent.

_Here, `T` refers to the type of the data model, i.e. the type of `AbstractControl.value`._

_In fact, this method is probably only suitable for `FormGroup`._

Further, the following signature:
`AbstractControl.getChild<T, C extends AbstractControl>(key: keyof T): C | null`
would allow the caller to indicate the expected sub-type of `AbstractControl` to be returned.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Reduce the risk of typos in the string value passed to the proposed `getChild` method.

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Browser:** [ all ]

 
* **Language:** [ TypeScript 2.X ]

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
duplicate #13721

**Comment by snerks** [comment]
I agree that this issue is similar to #13721.

However, I could not see any usage of the `keyof T` constraint, which aims to detect a typo in calling code, in the related Pull Request.

**Comment by Toxicable** [comment]
I have a change that uses key look up on mapped types for that PR for the FormGroup constructor but running into a small issue with FormArray being allowed to have members of different types.
Either way, since the method you're talking about is on AbstractControl both FormControl and FormArray get this method in which, unless I misunderstand keyof usage, you cannot use it keyof lookup in those situations

**Comment by snerks** [comment]
@Toxicable - thanks for a quick reply.

On reflection, I added (see text towards the bottom of my issue):

_In fact, this method is probably only suitable for FormGroup._

I imagined that the "inward" (`keyof` constraint) implementation would look something like this (on `FormGroup`):
```typescript
getChild<T>(key: keyof T): AbstractControl | null {
  return this.get(key);
}
```

Usage:
```typescript
interface Customer {
  firstName: string;
  lastName: string;
}

const customerFormGroup = new FormGroup({
  firstName: "",
  lastName: ""
});

const firstNameAbstractControl = customerFormGroup.getChild<Customer>("firstName"); // works
const lastNameAbstractControl = customerFormGroup.getChild<Customer>("lastWithTypoName"); // compile-time error: lastWithTypoName does not exist on Customer
```

The "outward" constraint on the return type `AbstractControl` subtype would follow your Pull Request's approach.

**Comment by rpbeukes** [comment]
Here is an alternative while we wait for a better implementation - [Angular Typesafe Reactive Forms](https://ruanbeukes.net/Angular-Typesafe-Reactive-Forms/)

**Comment by Da13Harris** [comment]
> I have a change that uses key look up on mapped types for that PR for the FormGroup constructor but running into a small issue with FormArray being allowed to have members of different types.
> Either way, since the method you're talking about is on AbstractControl both FormControl and FormArray get this method in which, unless I misunderstand keyof usage, you cannot use it keyof lookup in those situations

@Toxicable I'm wondering if the issue of different types in an array can be handled using [TypeScript tuples](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple)?

**Comment by AndrewKushnir** [comment]
Thanks for creating this feature request. The `AbstractControl.get` typing should be taken into account while improving types for Reactive Forms, so I think it's a sub-task of #13721, so I'm closing this ticket for now. Thank you.
