### ISSUE TITLE
aio: topnav jumps on Features or Docs to Home, Resources or Events

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17006]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Topnav jumps up when clicking between Features or Docs to Home, Resources or Events and vice versa.

**Expected behavior**
No visual jumps should occur when clicking on menu items on the topnav sidebar.

**

**Comment by IgorMinar** [comment]
Just to clarify: this is not specific to marketing pages. All navigation result in automatic scroll down action after the document is loaded in the viewer, resulting in the header being visually cut off after each navigation: 
![screenshot_20170530-023152](https://cloud.githubusercontent.com/assets/216296/26573328/2cd3bebe-44d2-11e7-9bda-1ebce93576e7.png)
