### ISSUE TITLE
Scroll event can't be detected on version 4

### ISSUE THREAD

**Issue by Radu-Dunarentu** [angular/angular#17015]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report 
[ ] feature request
[ ] support request 
```

**Current behavior**
Can't detect scroll event on 4.0.2

**Expected behavior**
Should be able to detect scroll event using...window:scroll, scroll on elements, hostlistener scroll, etc...

**Minimal reproduction of the problem with instructions**
<div (window:scroll)="increment()">some stuff here</div>
<div (scroll)="increment()">some stuff here</div>
etc...
increment() { this.counter += 1;}
**What is the motivation / use case for changing the behavior?**
Can't do a infinite scroll or use one.

**Please tell us about your environment:**
Windows 10 Pro, webstorm, used angular cli to create the package, 

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [ TypeScript 2.1 ]

"@angular/animations": "^4.0.1",
    "@angular/common": "^4.0.1",
    "@angular/compiler": "^4.0.1",
    "@angular/core": "^4.0.1",
    "@angular/forms": "^4.0.1",
    "@angular/http": "^4.0.1",
    "@angular/platform-browser": "^4.0.1",
    "@angular/platform-browser-dynamic": "^4.0.1",
    "@angular/router": "^4.0.1",

edit: plunker incoming

**Comment by wesleycho** [comment]
You should probably file a Plunker reproduction - my own experience with scroll events and Angular 4 does not agree with the asserted claim that it does not work.

**Comment by Radu-Dunarentu** [comment]
Can't reproduce the issue on a plunker. Closing the issue for now.

**Comment by gtzinos** [comment]
In Angular 4

If you use this scroll event inside a component which is wrapped in a router-outlet then you need to use ViewEncapsulation.Native in your parent component in order to works.

**Comment by nekkon** [comment]
https://plnkr.co/edit/A2GUoQvsEP9zheUfr762?p=info
scroll event is not detected

**Comment by zoechi** [comment]
@nekkon Plunker doesn't work for me, but this should demonstrate how to make it work
https://plnkr.co/edit/H9JBAbJhGzHRRCeakIQj?p=preview

Your original Plunker listens for scroll events on an element that doesn't scroll.
In you case `(window:scroll)="..."` would work because in your example the window content is scrollling, not the `<div>` content where you added the `(scroll)="..."` event binding.

**Comment by raasmasood** [comment]
iv tried to get a scroll event to work on div inside another scroll-able div

https://plnkr.co/edit/Ib0fxBIb7syGdEtQ1Rz4

event doesn't fire.

**Comment by KKHAN1991** [comment]
This still does not work for me either, im using version 5.

**Comment by muffinrecon** [comment]
Comment posted by gtzinos  seems to fire the event, however all the styles are gone.

**Comment by KKHAN1991** [comment]
@muffinrecon do you have a code sample you can show for that?

**Comment by KKHAN1991** [comment]
@muffinrecon thats intended functionality the styles are removed

i found the source of my problem. First need to make sure you use window:scroll to detect changes in the window, "scroll" only detects changes on the element its applied on. 

Trying to detect changing uses material sidenav is a headache, this is where i am having the problem. sidenav container has height of 100% and it causes the scrolling to not be detected for whatever reason.

**Comment by Stradivario** [comment]
It is not working on 5.1.0-beta.1 also.
I have also try but didn't work...

```
    Observable.fromEvent(window, "scroll").subscribe($event => {
      debugger
  });
```

Any suggestions ?

@KKHAN1991 i am also using Angular 2 Material Side navigation :O i will test and see if this is the source of the problem also...

**Comment by Stradivario** [comment]
@KKHAN1991 Confirmed! It is working without Angular 2 Material Sidemenu so what should we do ? to create an issue ?

**Comment by Lardge** [comment]
I have experienced the same issue. And I am also using angular material. This is definitely an issue.

**Comment by Roadirsh** [comment]
Same with Angular 5.2, maybe (scroll) just doesn't exist ? 
If so, what is the recommended way of doing it in Angular ?

**Comment by casvil** [comment]
@Radu-Dunarentu why did you close the issue? Is it solved? 
Thanks

**Comment by jessemorton** [comment]
A relevant comment is here: https://github.com/angular/angular/issues/17033#issuecomment-304296784 I was having trouble with the `(scroll)` on a div until I realized it was a different div that was actually responsible for the scrolling behavior, and therefore the one that needed the listener. Now things are working fine for me.

**Comment by lucasklaassen** [comment]
@jessemorton is right. More specifically if you are using the Angular material sidenav you probably have a div that wraps the entire content of your site so that the side nav can match the height of this content. The `sitewrapper` div you have that wraps your content is the div you need to add the scroll event to.
