### ISSUE TITLE
Angular1.5 transclude "ng-repeat"

### ISSUE THREAD

**Issue by brucewar** [angular/angular#17014]
nested "ng-repeat" in custom directive element, then transclude compiled it in link function. But I want to get the original dom in the custom directive. How do I?

```js
app.directive('column', function ($compile) {
  return {
    restrict: 'E',
    template: '<th></th>',
    replace: true,
    transclude: true,
    link: function (scope, element, attrs, ctrl, transclude) {
      transclude(scope.$parent, function ($transElement, transScope) {
        // "ng-repeat" in $transElement has been compiled
      });
    }
  };
});
```
```html
<column>
  <ul>
    <li ng-repeat="item in [1, 2, 3, 4]">{{item}}</li>
  </ul>
</column>
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

* **Angular version:** 1.5.0
* **Language:** ES5

**Comment by ericmartinezr** [comment]
Wrong repo. You're looking for https://github.com/angular/angular.js
