### ISSUE TITLE
Can't use your latest stable version

### ISSUE THREAD

**Issue by gtzinos** [angular/angular#17011]
I develop a web app using angular latest version. I installed @angular/cli 1.0.5 and now i can't build my project. 

This is a part of the error i got after the install.

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'app/app.component' in 'C:\Users\George Tzinos\Desktop\projects\document_management_frontend\documentManagement\src\app'
 @ ./src/app/app.module.ts 20:0-40
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

My package.json

{
  "name": "appit",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/material": "^2.0.0-beta.5",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/router": "^4.1.3",
    "@types/file-saver": "0.0.1",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "material-design-icons-iconfont": "^3.0.3",
    "ng2-cookies": "^1.0.12",
    "primeng": "^4.0.1",
    "roboto-fontface": "^0.7.0",
    "rxjs": "^5.4.0",
    "socket.io-client": "^2.0.1",
    "typings": "^2.1.1",
    "zone.js": "^0.8.11"
  },
  "devDependencies": {
    "@angular/cli": "1.0.5",
    "@angular/compiler-cli": "^4.1.3",
    "@types/jasmine": "2.5.47",
    "@types/node": "~7.0.22",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

**Comment by wesleycho** [comment]
Sounds like this may be filed in the wrong repository - you should probably reopen this at https://github.com/angular/angular-cli

**Comment by gtzinos** [comment]
Sorry for this. I will open it there.
