### ISSUE TITLE
aio: Static fields don't show up in class declarations.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#17024]
https://aio-staging.firebaseapp.com/api/core/Injector
https://angular.io/docs/ts/latest/api/core/index/Injector-class.html

```
static THROW_IF_NOT_FOUND : _THROW_IF_NOT_FOUND
static NULL : Injector
```

Also have a separate section for static members.

**Comment by petebacondarwin** [comment]
This is fixed by #17040
