### ISSUE TITLE
"Tutorial > Routing" doc broken markup

### ISSUE THREAD

**Issue by rutledgechinfeman** [angular/angular#17027]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://angular.io/docs/ts/latest/tutorial/toh-pt5.html has unrendered code that looks like:

+makeTabs( toh-5/ts/src/app/app.module.ts, toh-5/ts/src/app/app.module.3.ts, null, src/app/app.module.ts (after), src/app/app.module.ts (before)) :marked

**Expected behavior**
This section actually renders as a tabbed code preview panel

**Minimal reproduction of the problem with instructions**
Go to https://angular.io/docs/ts/latest/tutorial/toh-pt5.html, scroll to "Update AppModule" just before "Select a hero in the HeroesComponent"

**What is the motivation / use case for changing the behavior?**
Broken docs

**Please tell us about your environment:**
N/A

* **Angular version:** 2.0.X
N/A

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by rutledgechinfeman** [comment]
![7qklsgo3phe](https://cloud.githubusercontent.com/assets/742791/26472494/fc84a9e4-416b-11e7-8690-f4cefbe18034.png)

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/16913
