### ISSUE TITLE
Files don't load when I use the styleUrls

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#17021]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a CSS file in which I use images, font icons. This file I importing in scss file and I specify this scss in styleUrls.
```js
styleUrls: ['./src/style.scss']
```
I expect the images to load, but this does not happen because the paths to the images are specified relative to the scss file.

But if I just import the file, then the images are loaded.
```js
import './style.scss';
```
You can see example [here](https://github.com/dxvladislavvolkov/webpack-angular).

**Expected behavior**

I expect the images to load when I use styleUrls.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DmitriyKhirniy** [comment]
Please , try to use something like that. 
styles: [require('./src/style.scss').toString()]
Works for me.
