### ISSUE TITLE
Unhandled Promise rejection

### ISSUE THREAD

**Issue by suriyaJaay** [angular/angular#17020]
Hi all,

Could some one tell how to resolve below error. 
 **_see attached image_** 

![uncaught-error](https://cloud.githubusercontent.com/assets/19813670/26453100/3022fd14-4180-11e7-837b-354764d73831.PNG)

am trying to use below directive to close sideBar when user click outside

```
import {Directive, ElementRef, Output, EventEmitter, HostListener} from '@angular/core';
@Directive({
    selector: '[clickOutside]'
})
export class ClickOutsideDirective {
    constructor(private _elementRef: ElementRef) {
    }
    @Output()
    public clickOutside = new EventEmitter<MouseEvent>();
    @HostListener('document:click', ['$event', '$event.target'])
    public onClick(event: MouseEvent, targetElement: HTMLElement): void {
        if (!targetElement) {
            return;
        }
      const clickedInside = this._elementRef.nativeElement.contains(targetElement);
        if (!clickedInside) {
            this.clickOutside.emit(event);
        }
    }
}
```
and the event ll be added as below

`<div (clickOutside)="close($event)"></div>`

the whole directive is take from [https://github.com/chliebel/angular2-click-outside](url)

below are my part of package.json 
```
"dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",
    "angular2-in-memory-web-api": "0.0.20",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "jquery": "^3.1.1",
    "latest-version": "^2.0.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.23"
  }
```
**tsConfig.json**

```
{
  "compilerOptions": {
     "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
```

**_kindly provide solution for this. or suggest any alternative effective way to close sideBar when use click outside_**

am not sure about error after including this directive whether it happen after adding directive or environment version problem. am at very beginning stage of Angular 2. 

any help would be appreciated and it ll be helpful to others also ..

Many thanks for any help

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by suriyaJaay** [comment]
yeah Thank you
