### ISSUE TITLE
In hands-on table when we click on sort, we are encountering an error 

### ISSUE THREAD

**Issue by Gayathrikruti** [angular/angular#17030]
I'm submitting an issue on Hands-on. Kindly look into this issue and suggest some ways to resolve this.

**Current behavior**
Sorting is not happening in handson instead throwing an error

**Expected behavior**
Sorting should happen successfully without any error

**Minimal reproduction of the problem with instructions**

Created a component for Handson as wrapper where in ngoninit we are creating div with handson container and adding events to this as shown below:

*************************************************************************************************************
ngOnInit() {
        
        this.view = document.createElement('div');
        this.view.class = 'handsontable-container';
        this.element.nativeElement.appendChild(this.view);
        let htOptions: any = {
            data: this.data,
            comments: true,
            manualColumnResize: true,
            renderAllRows: this.renderAllRows,
            dropdownMenu: ['filter_by_condition', 'filter_action_bar'],
            filters: true,
            fixedColumnsLeft: this.fixedColumnsLeft,
            manualColumnFreeze: this.manualColumnFreeze,
            height: this.height,
            autoColumnSize: false,
            allowInsertRow: false,
            fillHandle: this.draggable
        };

        eventNames.forEach(eventName => {
            htOptions[eventName] = data => {
                this[eventName].next(data);
            };
        });

        let additionalFields: Array<string> = ['colHeaders', 'colWidths', 'columns'];
        additionalFields.forEach(field => {
            if (this[field]) {
                Object.assign(htOptions, {
                    [field]: this[field]
                });
            }
        });

        if (this.options) {
            Object.assign(htOptions, this.options);
        }

        this.inst = Handsontable(this.view, htOptions);

        if (this.columns && this.columns.length) {
            this.columns.forEach(column => {
                this.parseAutoComplete(column, this.data);
            });
        }
        var thisComp = this;
        this.inst.addHook('afterChange', function (changes) {
            thisComp.notifyChange.emit(changes);
        });
        this.inst.addHook('beforeOnCellMouseDown', function (event, coords, TD) {
            thisComp.notifyBeforeMouseDown.emit({ event: event, coords: coords });
        });                      

        this.inst.addHook('beforeColumnSort', function (event, coords, TD) {            
            
            thisComp.inst.sortColumn = undefined;
            thisComp.notifyBeforeColumnSort.emit({ event: event, coords: coords });
        });

        this.inst.addHook('afterColumnSort', function (event, coords, TD) {           
            thisComp.notifyAfterColumnSort.emit({ event: event, coords: coords });
        });

        this.inst.addHook('beforeFilter', function (event, coords, TD) {
            thisComp.inst.filterColumn = undefined;
            thisComp.notifyBeforeFilter.emit({ event: event, coords: coords });
        });

        this.inst.addHook('afterFilter', function (event, coords, TD) {
            thisComp.notifyAfterFilter.emit({ event: event, coords: coords });
        });
    }

********************************************************************************************************

on click of sort icon it is throwing following error. 
Unhandled exception at line 445, column 17 in http://localhost:xxxx/libs/zone.js/dist/zone.js
 
0x800a139e - JavaScript runtime error: Error: eventTask 'undefined.addEventListener:click': can not transition to 'running', expecting state 'scheduled', was 'notScheduled'.  

**Please tell us about your environment:**
Windows *8.1, Visual Studio 2015

* **Angular version:** 2.0.X
angular version 2.4.0

* **Browser:**
Chrome XX |  IE 11 | Edge Browser
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.10 |  ES5

**Comment by Toxicable** [comment]
I don't know what this "hands-on" is you keep referring to so would you mind explaining what it is. 
Also would you mind producing a minimal reproduction, preferably in plunkr, here's a template to get you started https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by hansl** [comment]
Closing this as it hasn't been answered in over 2 weeks. If you're still encountering this, please submit a new issue with a plnkr that reproduce the error, and explain what "hands-on" is (or link to it). Cheers!
