### ISSUE TITLE
Lazy loaded modules auto detectChanges will only trigger only the second time you load the module using Firefox/IE

### ISSUE THREAD

**Issue by m-dy** [angular/angular#17034]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Angular v4.1.3
SystemJs v0.19.x

Any subscription inside the lazy loaded modules get reflected in the UI immediately.

Angular v4.1.3
SystemJs v0.20.x

Any subscription inside the lazy loaded modules will only get reflected after going out of the module and going back to it.  We have to use manual detect changes to trigger the UI update on the first load of the lazy loaded module.

**Expected behavior**

It should work as expected on the first load of the lazy loaded module, all subscriptions should be reflected in the UI.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7, VS2015, SystemJs 0.20.x, IIS7.5, 

* **Angular version:** 4.1.3

* **Browser:** [Firefox XX | IE XX]

* **Language:** [TypeScript 2.2]

* **Node (for AoT issues):** `node --version` =

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
