### ISSUE TITLE
Calling detectChanges on parent during child's ngOnChanges leads to hooks not called

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#17035]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If `changeDetectionRef.detectChanges` is called in parent component during `ngOnChanges` hook of a child component then child's `ngAfterViewInit` hook is not called

**Expected behavior**

All hooks are called

**Minimal reproduction of the problem with instructions**

See console of the [plunker](https://plnkr.co/edit/T2WtlChLSmUMW5pVERXJ?p=preview)
If `detectChanges` is commented:
```
comp::ngOnInit
child::ngOnChanges
child::ngOnInit
child::ngAfterViewInit
comp::ngAfterViewInit
```
if not:
```
comp::ngOnInit
child::ngOnChanges
comp::ngAfterViewInit
```

**What is the motivation / use case for changing the behavior?**

It's a bug

**Please tell us about your environment:**

* **Angular version:** 4.1.1+

* **Browser:** Chrome 58

 
* **Language:** TypeScript 2.2

**Debug info**
May be it will help.
I tracked it down to these lines of `view.ts::checkAndUpdateView`:
```
  execComponentViewsAction(view, ViewAction.CheckAndUpdate);
  execQueriesAction(
      view, NodeFlags.TypeViewQuery, NodeFlags.DynamicQuery, CheckType.CheckAndUpdate);
  callLifecycleHooksChildrenFirst(
      view, NodeFlags.AfterViewChecked |
          (view.state & ViewState.FirstCheck ? NodeFlags.AfterViewInit : 0));
```

According to `view.state` it is a first check before calling `execComponentViewsAction` and it is not when `callLifecycleHooksChildrenFirst` is called.

**Comment by zhq1230** [comment]
+1, same problem after updating Anguar from 2.4.4 to 4.1.3

**Comment by zorcic** [comment]
+1, also same problem after updating Angular from 4.1.0 to >=4.1.1

**Comment by zorcic** [comment]
This behavior was introduced with pull request #16426.
