### ISSUE TITLE
Scroll event not working inside a router outlet in angular 4

### ISSUE THREAD

**Issue by gtzinos** [angular/angular#17033]
Hello,
I am developing a web app, structured with router outlets. In my app.component.html i have just a router outlet that is matched with a specific component. My pages can't use (scroll) event except if i will use ViewEncapsulation.Native in my app.component.ts. Otherwise if i have a simple div in my app.component.html with more text, then it is works fine.

Check this example. (Without router-outlet)
https://plnkr.co/edit/A2GUoQvsEP9zheUfr762?p=info

**Comment by ericmartinezr** [comment]
Probably I'm misunderstanding your issue, but in your plnkr you're not scrolling the div but the window. If you add `@HostListener('window:scroll', ['$event'])` to your `scrollHandler` function you'll see that it works ([plnkr example](https://plnkr.co/edit/cdi5anMvQsRSHyNBnvqn?p=info)). If you want to scroll the div you have to play a little bit with css ([plnkr example](https://plnkr.co/edit/XLFq9XRzYMbu6UJQWXt3?p=preview)).

**Comment by dloukadakis** [comment]
The scroll event will not be triggered if u register it on an element that doesn't have scrollbar even without angular, in your case you are scrolling the document not the div that has the event listener.

**Comment by gtzinos** [comment]
@ericmartinezr @dloukadakis Thank you guys. Now it works fine!
