### ISSUE TITLE
docs: dependency-injection - AOT rejects lambda in factory 

### ISSUE THREAD

**Issue by nbuso** [angular/angular#17042]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

in the Factory provider docs page:
https://angular.io/docs/ts/latest/guide/dependency-injection.html#!#factory-provider

you are documenting to use a lambda function to implement the *"heroServiceFactory"*
this end dump in ERROR with the static analysis of the code; like:

```
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
```

**What is the motivation / use case for changing the behavior?**

improve documentation

**Please tell us about your environment:**

linux shell

* **Angular version:** 2.0.X

@angular/cli: 1.0.1
node: 6.10.3
os: linux x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

* **Node (for AoT issues):** `node --version` =   
node: 6.10.3

**Comment by wardbell** [comment]
Yes, this works in JIT mode but not AOT. Need to revisit this in rewrite of Dependency Injection guides.

**Comment by jenniferfell** [comment]
filename=https://angular.io/guide/dependency-injection#factory-providers

Looks like a fix was started here: https://github.com/angular/angular/pull/17081

**Comment by petebacondarwin** [comment]
Lambdas are now supported in AOT compilation.
