### ISSUE TITLE
plunkers for api docs

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#17049]
There is a task we had in the past. Let's create an issue so we don't forget on implementing it in the future.

Related issues/PRs:

https://github.com/angular/angular.io/pull/2425
https://github.com/angular/angular/pull/11775

**Comment by petebacondarwin** [comment]
@Foxandxss Does this work now? Is it just a case of updating the content?

**Comment by Foxandxss** [comment]
This was created super long ago, so it probably need a tweak or two

**Comment by IgorMinar** [comment]
#11775 is closed now so I'm closing this issue. If this is not resolved please open a new issue and specify what exactly needs to be done.
