### ISSUE TITLE
Angular2: Dynamic component loader not working properly with index

### ISSUE THREAD

**Issue by phani257** [angular/angular#17047]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

The new component should be inserted as the index specified.
**Minimal reproduction of the problem with instructions**

I have a list of components for which data is fed by asynchronous calls. I am dynamically adding these components to a anchor point based on the row location. If I don't specify the row number, components are added to the view as soon as it gets the data.But I need them to follow based on the row location, which is not happening

switch{
case "grid":
    this.factory = this.componentFactoryResolver.resolveComponentFactory(GridComponent1);
    this.ref = this.coloneanchor.createComponent(component, rowLocation);
    this.ref.instance.gridData = this.favFilterData;
    this.ref.instance.gridTitle = gadget.Name;
    this.ref.changeDetectorRef.detectChanges();

case "donut":

  this.factory = this.componentFactoryResolver.resolveComponentFactory(donut);
    this.ref = this.coloneanchor.createComponent(component, rowLocation);
    this.ref.instance.gridData = this.favFilterData;
    this.ref.instance.gridTitle = gadget.Name;
    this.ref.changeDetectorRef.detectChanges();
}
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7 
* **Angular version:** 2.0.X

2.4
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by dherges** [comment]
Hi @phani257,

you can check a more complex solution at [dherges/ng-content-driven-angular](https://github.com/dherges/ng-content-driven-angular/blob/master/src/app/reactive-content/content-host/content-host.component.ts#L111-L156). It definitely works there and this solution also works with "recursion", i.e. embedding a child dynamic component into `ViewContainerRef` of a parent dynamic components. A [narrative explanation of the approach is also available](https://medium.com/spektrakel-blog/content-driven-angular/home).

**Comment by phani257** [comment]
Yes even for me the components are getting loaded dynamically. The problem is the component is not injected at the specified index even if I provide the index number.

 this.factory = this.componentFactoryResolver.resolveComponentFactory(GridComponent1);
    this.ref = this.coloneanchor.createComponent(component, rowLocation);
    this.ref.changeDetectorRef.detectChanges();

**Comment by alexzuza** [comment]
https://stackoverflow.com/questions/41242124/loading-dynamically-created-components-in-order/44229216#44229216

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by phani257** [comment]
This seems to be an issue for me. Because I am following exactly what is shown in the angular.io doc. Even then the components are not injected at their index value.
