### ISSUE TITLE
FromGroup.values['formControlName'] returns undefined when form control is disabled. FormGroup.controls['formControlName'].value does not

### ISSUE THREAD

**Issue by rgrasso** [angular/angular#17058]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
this.myForm.addControl('quantity', new FormControl({value: '1', disabled: true});
this.myForm.controls['quantity'].value returns '1' as expected
this.myForm.values['quantity'] returns undefined

**Expected behavior**
this.myForm.values['quantity'] should return the value of the control even if the control is disabled

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Behavior should be identical regardless of whether a form control is disabled or not

**Please tell us about your environment:**
Windows 10, npm, apache, Angular 4.1.3

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Windows 10 Chrome Version 58.0.3029.110 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.1

**Comment by Toxicable** [comment]
Could you please provide a minimal reproduction, preferably in plunkr, here's a template to get you started https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by kara** [comment]
Like in native HTML forms, disabled control values are not serialized into the group value of the form. This is [intended behavior](https://github.com/angular/angular/blob/master/packages/forms/test/form_control_spec.ts#L1007).  If you'd like the full group value, including disabled controls, there is a `FormGroup.getRawValue()` method you can use.
