### ISSUE TITLE
Setting name property on any element causes exception on server side rendering

### ISSUE THREAD

**Issue by vikerman** [angular/angular#17050]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Setting the 'name' property on an input element in a template will cause server side renderer to throw an exception.

**Expected behavior**
Do not throw an exception

**Minimal reproduction of the problem with instructions**
<input [name]=''name"></input> in your template will throw an exception on the server side.

We need to handle name specially or just  have separate property bag on the Parse5 Node instead of directly setting properties on it and clobbering Parse5 properties.

**Comment by jelbourn** [comment]
It may be _any_ element, not just inputs, but that probably doesn't affect the fix.
