### ISSUE TITLE
The pipe 'digits' could not be found

### ISSUE THREAD

**Issue by ranouf** [angular/angular#17057]
Package.json:
{
  "name": "WebApplicationBasic",
  "version": "0.0.0",
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "2.0.0-beta.5",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@covalent/core": "1.0.0-beta.4",
    "@types/node": "7.0.18",
    "@angular/flex-layout": "2.0.0-beta.8",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^2.0.5",
    "aspnet-webpack": "^1.0.29",
    "awesome-typescript-loader": "3.1.3",
    "css": "2.2.1",
    "css-loader": "0.28.1",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.0",
    "file-loader": "0.11.1",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "preboot": "4.5.2",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.0.1",
    "style-loader": "0.17.0",
    "to-string-loader": "1.1.5",
    "typescript": "2.3.2",
    "url-loader": "0.5.8",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.0",
    "webpack-merge": "4.1.0",
    "zone.js": "^0.8.4",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.5",
    "angular2-jwt": "^0.2.3",
    "auth0-js": "^8.7.0"
  },
  "devDependencies": {
    "@types/chai": "3.5.2",
    "@types/jasmine": "2.5.47",
    "chai": "3.5.0",
    "jasmine-core": "2.6.1",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3",
    "node-sass": "^4.5.3"
  }
}

Loaded Module:

import { CommonModule } from '@angular/common';
@NgModule({
    imports: [
        CommonModule,   
    ]
})
export class AppModule {
}

I have this error:
Unhandled Promise rejection: Template parse errors:
The pipe 'digits' could not be found 

From what I see on the official angular documentation:
https://angular.io/docs/ts/latest/api/common/index/DecimalPipe-pipe.html

The digit pipe come from CommonModule

Can you help me to find a solution?

Thank you

**Comment by dloukadakis** [comment]
The pipe is called "number" not "digits" you should check the example on:
https://angular.io/docs/ts/latest/api/common/index/DecimalPipe-pipe.html

**Comment by ranouf** [comment]
The pipe digit is from Angular Covalent :).

I will ask on their forum

Thanks
