### ISSUE TITLE
Unable to load transpiler to transpile main.js

### ISSUE THREAD

**Issue by TarasKovalenko** [angular/angular#17066]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Transpiler doesn't work correctly with multiline comments in a bootstrapper file.

**Expected behavior**
Any comments in a bootstrapper file should be skipped, and don't to break a compile process.

**Minimal reproduction of the problem with instructions**
1. Download a [QuickStart seed ](https://angular.io/docs/ts/latest/guide/setup.html)
2. Open **main.ts** file in an any IDE
3. Try to put next code on the bottom this file:

```
/* AOT bootstrap
import { platformBrowser } from '@angular/platform-browser';
import { AppModuleNgFactory } from './app/app.module.ngfactory';
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
*/
```
The after run this app you catch next exception, like this:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:19 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur
	Error: XHR error (404 Not Found) loading http://localhost:3000/traceur
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1055:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:191:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:486:38)
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/main.js
	Error loading http://localhost:3000/main.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1055:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:191:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:486:38)
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/main.js
	Error loading http://localhost:3000/main.js
(anonymous) @ localhost/:19
```
But if you change Multiline Comments on the Single Line Comments:
```
// AOT bootstrap
//import { platformBrowser } from '@angular/platform-browser';
//import { AppModuleNgFactory } from './app/app.module.ngfactory';
//platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```
, it's will be work fine.

**Please tell us about your environment:**
It's reproduced in different environments.

* **Angular version:** 4.0.0

* **Browser:** [all]
 
* **Language:** [TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v7.7.3

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/12967. Although I would recommend you to take the CLI QuickStart Guide. Also I recommend you to look at the `removeComments` property in your [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) file (it could be helpful).

**Comment by TarasKovalenko** [comment]
@ericmartinezr Yep, it's not a big problem to use your recommendations. 
But I think it's a big bug and this should be fixed.

**Comment by ericmartinezr** [comment]
Yes, you're right, but it's not an angular bug but systemjs. It's not angular who's doing the transpilation.

**Comment by TarasKovalenko** [comment]
@ericmartinezr really! Sorry, I don't know about this.
Thanks for the feedback.
