### ISSUE TITLE
Trying to resolve module in object literal.

### ISSUE THREAD

**Issue by debasispanda** [angular/angular#17078]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Build is failing as its trying to resolve the `templateUrl` property in an object literal when building app using **angular cli** . There is an object having a property `templateUrl` and assigned value as empty string. Please find the code below.

```
let defaults: any = {
      isAttached: false,
      get: true,
      handler: '',
      url: '',
      templateUrl: '',
      html: '',
      file: ''
    }
```
**Getting the following error**

```
ERROR in ./src/app/Components/PrintPdf/printpdf.service.ts
Module not found: Error: Can't resolve './' in 'D:\Project\src\app\Components\PrintPdf'
 @ ./src/app/Components/PrintPdf/printpdf.service.ts 54:22-35
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```
**Expected behavior**
As this is property of common object literal not of a component it should behave normally.

**Minimal reproduction of the problem with instructions**
Add a object literal with a property **templateUrl** and build with angular cli. `ng build`

**Environment:**
OS-  Windows 10
IDE- Visual Studio 2015
`node --version` =   v 7.7.4
Package manager- npm
`npm--version` =   v 4.1.2
Angular CLI - v 1.0.1

* **Angular version:** 4.0.X

* **Browser:** n/a
 
* **Language:** TypeScript: 2.2.X

**Comment by SteveVanOpstal** [comment]
Can you reproduce this in a Plunker?

**Comment by debasispanda** [comment]
I believe this issue is with angular cli build. In Plunker I am unable to reproduce as its using systemjs configuration. 
Create a new app using angular cli and add the following code to `app.component.ts` and run `ng build`. You will get the above error. 

```
let data: any = {
      templateUrl: ''
    }
```

**Comment by SteveVanOpstal** [comment]
If you believe it is an issue of angular-cli you should post the issue on their issues page: https://github.com/angular/angular-cli/issues
This is the issues page for the angular framework

**Comment by tytskyi** [comment]
@debasispanda i confirm this happens within cli.

For workaround use class with initial fields values
```
class FileJson {
  public templateUrl = "";
}

// in component
public test: FileJson = new FileJson();
```

**Comment by debasispanda** [comment]
Thanks @tytskyi . I have also created the same issue in angular-cli page. Thank you @SteveVanOpstal for your suggestion.

Closing the issue here. You can follow the same in angular-cli issues.
https://github.com/angular/angular-cli/issues/6498
