### ISSUE TITLE
docs: typo in Setup Anatomy documentation page

### ISSUE THREAD

**Issue by bsfajardo** [angular/angular#17076]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In the Setup Anatomy documentation page (Additional Documentation -> Advanced -> Setup Anatomy) there's a typo in the work "appliation" in the "systemjs.config.extras.js" entry in the table.

**Expected behavior**

The word "appliation" should be corrected to "application".

**Minimal reproduction of the problem with instructions**

Not relevant.

**What is the motivation / use case for changing the behavior?**

To improve documentation.

**Please tell us about your environment:**

Not relevant.

* **Angular version:** 2.0.X

Not relevant.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Not relevant.

* **Node (for AoT issues):** `node --version` =   
Not relevant.

**Comment by dherges** [comment]
@gkalpak @wardbell @matsko This issue should be closed. #17077 was merged.

**Comment by gkalpak** [comment]
Thx, @dherges. I case you didn't know, you can autoclose issues when your PR is merged by mentioning it in your commit message. Here is the [list of keywords][1] that trigger this behavior.
<sub>(Note that `Solves` is not one of them, but it's close :wink:)</sub>

[1]: https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues

**Comment by dherges** [comment]
@gkalpak Ah, yes, in German we say: "knapp daneben ist auch daneben"! :de:
