### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError with ngFor and collections in ReactiveFormsModule

### ISSUE THREAD

**Issue by Cogitaria** [angular/angular#17070]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Exception thrown using *ngFor to iterate over a keys in a map: 

... original error: ExpressionChangedAfterItHasBeenCheckedError

**Expected behavior**

*ngFor should be able to iterate on an Array or Map.entries() or Map.keys() and IMO Map itself. 

**Minimal reproduction of the problem with instructions**

Use *ngFor on a Map<K, V> **entries**() or **keys**() collection crashes with the  ExpressionChangedAfterItHasBeenCheckedError exception. 

**What is the motivation / use case for changing the behavior?**

I would expect *ngFor to work on an entries() or keys() collection on Map<K, V> instance.

If there is a rationale for this error it should be more clearly documented. 
 
**Please tell us about your environment:**

Running application generated with angular-cli on OSX

* **Angular version:** 2.0.X

Angular 2.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by tytskyi** [comment]
Please provide plunker showing reproduction. 
There is not difference if you create an empty array withing `new Array()` or `[]`

**Comment by Cogitaria** [comment]
It's possible older version of NG is causing this to manifest on Array<T> because it works in the provided plunkr.  However, the issue of using map.entries() or map.keys() does exhibit the issue.  Workaround is simple: add a pipe to iterate and return a simple array.
