### ISSUE TITLE
Bug(Animations): ngFor not updating correctly during animation

### ISSUE THREAD

**Issue by macjohnny** [angular/angular#17086]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report 
[ ] feature request
[ ] support request =>
```

**Current behavior**
When using the ngFor directive in an element that is animated, the resulting iteration elements are not updated correctly when the items change before starting the animation. In fact, the new items are placed before the existing items instead of replacing them.
The code
```
<ul [@translateAnimation]="animationState">
    <li *ngFor="let item of items">{{item}}</li>
</ul>
```
produces
![bildschirmfoto 2017-05-29 um 16 08 21](https://cloud.githubusercontent.com/assets/5589029/26552841/3d48d23c-4489-11e7-8607-d4523ac889df.png)
The list is updated correctly AFTER the animation is done.

**Expected behavior**
The ngFor statement would replace the previous elements with the new elements when the list elements are changed before the animation starts.
This was working with Angular 4.1.3

**Minimal reproduction of the problem with instructions**
See this http://embed.plnkr.co/MxKJvH/

**What is the motivation / use case for changing the behavior?**
This is a Bug

**Please tell us about your environment:**
Any

* **Angular version:** 4.2.0-rc.1

* **Browser:** all
 
* **Language:** Typescript@2.2.2

**Comment by macjohnny** [comment]
@matsko could you have a look at this?

**Comment by matsko** [comment]
Yessir. I'll investigate right away.

**Comment by macjohnny** [comment]
@matsko @vicb thanks for fixing this!
