### ISSUE TITLE
Is this the right time to use angular 4?

### ISSUE THREAD

**Issue by shafaqkazmi** [angular/angular#17082]
**I'm submitting a ...**  (check one with "x")
```
[x] FAQ
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
Is this the right time to use Angular 4 for an enterprise SAP or we should stick to angular-2 and wait for a final release of angular-4? I have seen rapid releases of angular-4. (https://github.com/angular/angular/blob/master/CHANGELOG.md)

Please suggest.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
