### ISSUE TITLE
query params disappear on refresh page in route added via router.config.push

### ISSUE THREAD

**Issue by MattiaMalandrone** [angular/angular#17084]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the app.component added a route via : 
```
this.router.config.push({ path: 'romanzi', loadChildren:'app/features/romanzi/romanzi.module#RomanziModule'  });
```
In every path I need query params like : http://localhost:4200/romanzi?pcode=00001
But when refresh page via F5 the query params disappear;

In the default routes defined in app.module there is no problem, so refreshing via F5  while inside http://localhost:4200/dashboard?pcode=00001 the query params still remain
```
const routes: Routes = [
  { path : '' , redirectTo: 'dashboard', pathMatch: 'full' },
  { path: 'dashboard', loadChildren: 'app/dashboard/dashboard.module#DashboardModule' }
];
```
**Expected behavior**
Also in routes added via this.router.config.push(.....) when press F5 the query params must remain

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.1.3 (but present also in 2.0.0 version)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =

**Comment by SteveVanOpstal** [comment]
Can you add a [Plunker](http://plnkr.co/) demonstrating the issue?

At a first glance I would say that it is maybe not possible to `push` to `router.config` (as it is not available anymore in `4.2.0-rc.1`, maybe it shouldn't be used). Try using `resetConfig` instead, maybe that works.

**Comment by MattiaMalandrone** [comment]
Thank you! sorry for the delay! 
I'm preparing the plunker, but I tried also with the resetConfig but the problem persist

**Comment by MattiaMalandrone** [comment]
Here is the plunker : http://plnkr.co/edit/bo4SwxHmoxRLH0Xyz8wB
But I don't know how to add the query param and to simulate the refresh page on http://plnkr_address/romanzi?pcode=00001, I added manually the pcode query param in the place of the params['pcode']

**Comment by MattiaMalandrone** [comment]
Sorry, I undertstood right now....reloading the page while in the path of a lazy module 
```
 http://localhost:4200/romanzi
romanzi is the lazy module
```
it is obvious that the path is unreachable by the routing system
