### ISSUE TITLE
ngModel min validator seems ignored

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#17080]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When an input element has a min value on it, it seems this validator is ignored. 

    <input #m="ngModel" name='price'  type="number" required [(ngModel)]="price" step="0.05" min="0.95">

if you focus and tab out without setting a minimum value of 0.95 it's still valid when it should not be.

**Expected behavior**
The validator should not be true if the minimum value is not reached.

**Minimal reproduction of the problem with instructions**

[here is a plunk](https://plnkr.co/edit/bbDG8H?p=preview) that demonstrates this behaviour

**What is the motivation / use case for changing the behavior?**
validations should be enforced.

* **Angular version:** 4.2.x

**Comment by SteveVanOpstal** [comment]
[Only four Validator directives exist](https://github.com/angular/angular/blob/4.0.0/packages/forms/src/directives/validators.ts):
* required
* minlength
* maxlength
* pattern

So a `min` validator should be made with a custom implementation of Validator.

You can make it yourself: https://stackoverflow.com/a/39848327/531122

Or use a library (like https://github.com/yuyang041060120/ng2-validation) to do it for you.

Although it is marked as experimental, documentation is lacking on this.

**Comment by SanderElias** [comment]
@SteveVanOpstal [documentation of min validator](https://aio-staging.firebaseapp.com/api/forms/MinValidator).

**Comment by SteveVanOpstal** [comment]
The Plunker got me confused as it is loading Angular 4.1.3. I modified the Plunker to version 4.2.0-rc.1 and I am debugging it now. It could have something to do with `MinValidator` using `ParseInt` (See https://github.com/angular/angular/blob/4.2.0-rc.1/packages/forms/src/directives/validators.ts#L133).

**Comment by SteveVanOpstal** [comment]
`ParseInt` seems to be the issue, as it converts the string `'0.95'` into number `0`

**Comment by SanderElias** [comment]
@SteveVanOpstal Yeah, I think that _is_indeed the issue. 
the [validator itself](https://github.com/angular/angular/blob/4.2.0-rc.1/packages/forms/src/validators.ts#L71) should be doing the right thing. I was looking at the wrong spot! good catch!

**Comment by SteveVanOpstal** [comment]
I'm working on a fix and will create a pull request of it

**Comment by Toxicable** [comment]
@SteveVanOpstal  Thanks for pointing that out, I do apologize for my mistake, I remember seeing this when I was making the validator since it was half copy pasted from another old PR (which specifically included this part) I am unsure why I did not change it then, I thought I had.
Anyway, sorry for any inconvenience this has caused

**Comment by SteveVanOpstal** [comment]
@Toxicable Not a problem, it is fixed now.
