### ISSUE TITLE
aio: add "Mapt" to Resources page under Online Training

### ISSUE THREAD

**Issue by packtpartner** [angular/angular#17083]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**What is the motivation / use case for changing the behavior?**
I would like to feature Packt's online training platform, Mapt, under the "Online Training" section on the resources page (https://angular.io/resources/)

Mapt for Angular 2 (https://www.packtpub.com/mapt/search_results?query=angular2&ss_cck_field_available=Available)
Dive in and master Angular 2 with this extensive library of resources.

* **Angular version:** 2.0.X
Angular 2

**Comment by packtpartner** [comment]
@robwormald and @StephenFluin can this be done?

**Comment by StephenFluin** [comment]
Can you ping me directly on twitter or email? We want to get the branding right before we link to you.

**Comment by jenniferfell** [comment]
@packtpartner and @StephenFluin : Did you come to resolution on this?

**Comment by jenniferfell** [comment]
docsarea=resources

**Comment by StephenFluin** [comment]
This issue is stale, closing. Feel free to open a PR with the changes you would like to see, but we'll require the use of the right terminology from our press kit. https://angular.io/presskit
