### ISSUE TITLE
TOC not sticking to the header when the header scrolls away resulting in a space above

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17099]
![screenshot_20170530-023652](https://cloud.githubusercontent.com/assets/216296/26573810/f0de796a-44d3-11e7-87dd-bfe1fd9ab2d4.png)

**Comment by IgorMinar** [comment]
sidenav has the same issue :-(

**Comment by gkalpak** [comment]
This is now obsolete (for the time being at least), because all pages with SideNav and ToC have a fixed header (since in #17155).
