### ISSUE TITLE
PromiseWrapper.reject does not preserve stack traces

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#1709]
My application is throwing an error and I see a nonsensical stack trace instead of a stack leading to the source of the error.

```
The null object does not have a method 'startsWith'. NoSuchMethodError: method not found: 'startsWith' Receiver: null Arguments: ["package"]
dart:async                                               _Completer.completeError
package:angular2/src/facade/async.dart 101:7             _Completer.reject
package:angular2/src/core/application.dart 313:24        bootstrap.<fn>.<fn>
dart:async                                               _ZoneDelegate.runUnary
package:angular2/src/core/zone/vm_turn_zone.dart 147:55  VmTurnZone._onRunUnary.<fn>
package:angular2/src/core/zone/vm_turn_zone.dart 128:16  VmTurnZone._onRunBase
package:angular2/src/core/zone/vm_turn_zone.dart 147:7   VmTurnZone._onRunUnary
dart:async                                               _ZoneDelegate.run
package:angular2/src/core/zone/vm_turn_zone.dart 143:64  VmTurnZone._onRun.<fn>
package:angular2/src/core/zone/vm_turn_zone.dart 128:16  VmTurnZone._onRunBase
package:angular2/src/core/zone/vm_turn_zone.dart 143:16  VmTurnZone._onRun
dart:async                                               _Future.then
package:angular2/src/facade/async.dart 15:20             PromiseWrapper.then
package:angular2/src/core/application.dart 304:20        bootstrap.<fn>
dart:async                                               _ZoneDelegate.run
package:angular2/src/core/zone/vm_turn_zone.dart 143:64  VmTurnZone._onRun.<fn>
package:angular2/src/core/zone/vm_turn_zone.dart 128:16  VmTurnZone._onRunBase
package:angular2/src/core/zone/vm_turn_zone.dart 143:16  VmTurnZone._onRun
dart:async                                               _CustomZone.run
package:angular2/src/core/zone/vm_turn_zone.dart 79:35   VmTurnZone.run
package:angular2/src/core/application.dart 299:8         bootstrap
... <redacted>
```

Going to ```package:angular2/src/core/application.dart 313:24```, which is a reject call: ```bootstrapProcess.reject(err);```

Instead of passing only the error; please pass the error and the stack trace to the user.

**Comment by mhevery** [comment]
Dup of #1407

**Comment by jbdeboer** [comment]
Yes, it is.

**Comment by jbdeboer** [comment]
Talking with @alexeagle, this is a different issue from #1407

**Comment by jbdeboer** [comment]
Repo case: https://github.com/jbdeboer/angular2_stack_traces

Clone that repo, run pub serve.  In the DevTools console, you should see

```
This program will trigger a stack trace. The function origin() 
should be included in the stack trace.
Calling origin
Caught an error: Error:[An exception. Can you see origin() in the stack?] Stack:[null]
```

I expect to see some value in the "Stack" output.

**Comment by jbdeboer** [comment]
I believe the fix is to pass the stack trace to ```Future.error``` in facade/async.dart

and, anywhere you call ```PromiseWrapper.reject```, there are only a handful of places where this occurs in the code.

**Comment by yjbanov** [comment]
@jbdeboer we will fix stacks for `Error` descendants, but not for arbitrary thrown objects (yet), such as strings. In Dart, to capture stack from a non-`Error` you have to use special syntax `catch(e, s)`, which is not supported by TypeScript and not shimmed in ts2dart (there's a separate [discussion](https://github.com/angular/ts2dart/issues/152) and a [proposal](https://github.com/angular/ts2dart/pull/153) just for that).

The good news is that the majority of Dart errors _are_ extending `Error`, e.g. `ArgumentError`, `StateError`, `NoSuchMethodError`. It is unlikely that you would both encounter a thrown non-`Error` _and_ have trouble debugging it.

**Comment by jbdeboer** [comment]
If my repo case (above) is fixed, I am happy for now.

For reference, in our codebase, ~40% of our ```throw``` statements throw an ```Error```. The rest are throwing strings or other ```Exception```s. I would say that both ```Error```s and non-Errors are important.

**Comment by yjbanov** [comment]
@jbdeboer 

Your repro case is throwing a string, which is why I brought it up. We won't fix it by #1924, but we will fix the same repro in the `Error` case.

As for 40%. You don't need a `throw` statement to get a `NoSuchMethodError`, all you need is `foo` to be `null` in `foo.bar`, same goes for things like `RangeError` as it is thrown by the standard library, not your code. So the 40% of `throw` statements in your code constitute a much smaller percentage of total locations in your code that result in exceptions.

I suggest we close this issue with #1924 as it should provide a good enough solution. The remaining cases we will try to fix on the ts2dart side (which are already tracked and being worked on).

**Comment by yjbanov** [comment]
Closing this one. Let's fix the non-`Error` in https://github.com/angular/ts2dart/issues/152.

**Comment by jbdeboer** [comment]
Please keep a tracking bug for this issue open in this repo. The reproduction case I posted is *not* fixed and I am not convinced it is a ts2dart-only bug.
