### ISSUE TITLE
Feature: Add methods to better handle errors in AbstractControl

### ISSUE THREAD

**Issue by dev054** [angular/angular#17090]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting
- [X] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior**

Let's suppose that I have the following control:

`const field = new FormControl('', [Validators.required]);`

To `remove` an error I have to do something like this:

`delete field.errors['required']; // Exception if it's null/undefined`

The safe way:

```
if (field.errors) {
  delete field.errors['required'];
}
```

Actually to `add` an error I have to get what errors I have before add a new using `setErrors` or I'll overwrite the whole errors. 

So, I have to do something like this:

```
const errors = field.errors;
const newErrors = { email: true };

if (errors) {
  newErrors = Object.assign(errors, newErrors);
}

field.setErrors(newErrors);
```

**Expected behavior**
Adding the methods `addErrors` and `removeErrors` in AbstractControl we could have a really better way to manipulate this.

Cleaner syntax:

`addError**s**(obj);`

`removeError**s**(obj);`

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
Could you expand on why you need to use `addErrors` and `removeErrors` rather than using validators? they do this for you.

**Comment by dev054** [comment]
Hey @Toxicable, how would validators help in this case? The idea of `errors` is to set some errors programatically, in other words, you set the error for the `control` or `group` while validators are a completely different thing. Also, extending to the discussion: `validators` (IHMO) needs something like [addValidators](https://github.com/angular/angular/pull/12325) and removeValidators.

**Comment by tytskyi** [comment]
@dev054 the idea of `errors` to be read only for end programmer. If you want to change errors object manually then it means that you do not maintain several properties of `control`: `status`, `valid`, `invalid`. If it's a control of some group - you also do not maintain validity of that parent group. 
You should never do things like `delete field.errors['required'];` This breaks how does form work. If you don't want `required` - then just don't use this `required` on then control. 
Validators are self-responsible, plus they handle validity properties of control and its form group as i wrote above. 
I put small plunker that demonstrates statement above: http://plnkr.co/edit/Kr9YQZ8RWRmN6XZQbFcS?p=preview

Observe that error gets removed each 2 seconds, but control and its form remain invalid.

**Comment by dev054** [comment]
Hey @tytskyi I'm sorry if my issue wasn't clear, however I think you just don't understand what I'm proposing here...

Here we go... currently we have the method `setErrors` in AbstractControl, right?

However, this method just allows you to set the errors instead of appending to the existent or maybe removing... so you have to do some kind of logic to handle if it has some errors before adding or if it's null before removing. So... to get away of this verbosity, I'm suggesting the creation of `addErrors` and `removeErrors` method.. as explained in this issue earlier.

**Comment by superMDguy** [comment]
I would suggested an additional `updateErrors` method, which uses `Object.apply` to modify the existing errors object.  That would ensure backwards compatibility, since some users might be depending on having the errors get overwritten with `setErrors`.

As for deleting errors, I think it would make more sense to just set the error to false. For example if the errors object is set to `{required: false}`, the control would be valid.  That would require modifying https://github.com/angular/angular/blob/master/packages/forms/src/model.ts#L553 to check if each item in the errors object is `true`, instead of just checking if the errors object exists.

I'd be happy to create a PR for this functionality, if others agree.

**Comment by KostyaTretyak** [comment]
> I'd be happy to create a PR for this functionality, if others agree.

@superMDguy, just do it! =)

**Comment by dylhunn** [comment]
PR [was closed](https://github.com/angular/angular/pull/28976#issuecomment-801302343) due to the introduction of non-tree-shakable code, without overwhelming community interest.
