### ISSUE TITLE
Tutorial - Upgrade AngularJS to Angular Typescript npm script is missing

### ISSUE THREAD

**Issue by ido-ran** [angular/angular#17093]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the upgrade tutorial at [Switching to Typescript step](https://angular.io/docs/ts/latest/guide/upgrade.html#!#switching-to-typescript) the code for changing `package.json` to include `tsc:w` script is missing.

This is how it looks like in my browser:
![image](https://cloud.githubusercontent.com/assets/187938/26569915/43d78494-4516-11e7-80a8-b6c6cda43fd3.png)

**Expected behavior**
I guess the example json should look something like this:

```
{
  "scripts": {
     "tsc": "tsc",
    "tsc:w": "tsc -w"
   }
}

```
Because few paragraph bellow this command should be run `npm run tsc:w`.

**Please tell us about your environment:**

Windows 10.

**Comment by gkalpak** [comment]
This section has been slightly reworked (and this isn't an issue any more) in the new (soon-to-be-released) [version][1].

[1]: https://aio-staging.firebaseapp.com/guide/upgrade#switching-to-typescript

**Comment by ido-ran** [comment]
Hi,
I'm looking at the new docs but I still don't see the definition for `tsc:w` in `package.json`.
Also search for 

> to also point to the project root instead of

It looks like it is missing code example too.

**Comment by gkalpak** [comment]
Fair enough :smiley:
