### ISSUE TITLE
Hamburger menu has ugly shadow when focused

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17095]
Is this intentional? I don't remember it before the redesign.

![screenshot_20170530-023141](https://cloud.githubusercontent.com/assets/216296/26573458/ac4f9730-44d2-11e7-9948-b29d1db09fdd.png)

**Comment by Misiu** [comment]
@sjtrimble there's one more bug related to new page:
![angularpagetopbar](https://cloud.githubusercontent.com/assets/1741838/26578852/bdc9dbf6-4531-11e7-909b-f0e05e3879fa.gif)

When navigating to features or docs top bar suddenly jumps a bit, resources works fine.
I've tested this on Chrome 58 and Edge on WIndows 10.

**Comment by gkalpak** [comment]
@Misiu, there is a different issue for that: #17006

**Comment by Misiu** [comment]
@gkalpak didn't saw that earlier. sorry about reposting same issue.

**Comment by gkalpak** [comment]
FWIW, I don't know if it is intentional, but I think it is a good thing to have some style to indicate focus. (Not necessarily the one we have now.)

**Comment by petebacondarwin** [comment]
Actually this is strange. It doesn't appear to be keyboard focus, because as you tab through the nav list it doesn't go away, and you can't actually tab back to the hamburger to make the sidebar disappear.

**Comment by petebacondarwin** [comment]
I can't find any CSS rule that is affecting this...

**Comment by petebacondarwin** [comment]
Possibly `cdk-focussed` or `cdk-keyboard-focussed`

**Comment by IgorMinar** [comment]
@jelbourn could you please help find the culprit? thanks!

**Comment by jelbourn** [comment]
This is the working-as-intended focus treatment for mat-button. You probably wanted `mat-icon-button` here, though.

**Comment by petebacondarwin** [comment]
Using a `mat-icon-button` results in a circular shadow which is no better.

<img width="604" alt="screen shot 2018-10-12 at 10 41 37" src="https://user-images.githubusercontent.com/15655/46861848-8704c900-ce0b-11e8-8d71-e29bfbb27f34.png">

If this is the standard Material design on-focus styling for buttons then I think we should just live with it.
