### ISSUE TITLE
New event listener that listens to multiple HammerJS touch events

### ISSUE THREAD

**Issue by virgil-av** [angular/angular#17107]
Hi, 

   I need some help implementing a new touch event with HammerJS, I have tried too see some information regarding this but nowhere is it explained for ease to follow. 

I created a **hammerjs.ts** file where I can do the overrides and custom events the content looks like: 

```
import { HammerGestureConfig } from '@angular/platform-browser';
import * as Hammer from 'hammerjs';
import { HammerInstance } from "@angular/platform-browser/src/dom/events/hammer_gestures";

// create a class that overrides hammer default config

export class MyHammerConfig extends HammerGestureConfig  {
    events: string[] = ['pinch-pan']; 
    buildHammer(element: HTMLElement): HammerInstance {
    let mc = new Hammer(element, {domEvents: true});
    mc.get('pinch').set({enable: true});
    mc.get('pinch').recognizeWith(mc.get('pan'));
    return mc;
  }
}
```

I added it to **my app.module.ts** in the providers array:
`providers: [{provide: HAMMER_GESTURE_CONFIG, useClass: MyHammerConfig}]`

**Now how to use in my component this event named 'pinch-pan' ?** 

So far I have tried: 
In my TS page:
`@HostListener('pinch-pan', ['$event'])`

In my HTML file: 
`<div class="box middle" (pinch-pan)="doSomething($event)"></div>`

```
doSomething(event){
console.log(event);
}
```

I am stuck can someone please guide me in the right direction on how to use custom hammerjs events.
Thank you.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
