### ISSUE TITLE
need help in router redirect.

### ISSUE THREAD

**Issue by Nikyypatel** [angular/angular#17101]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[  ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**
i need help for the **this.router.navigate['/home']**, when i click this link, i redirect the Home-component,
but it`s just HTML and CSS code, then manually **i refresh browser** then my **JQUERY load** and then enable my functionality, **i need to load JQUERY at a time of redirect** my Home-component, i am getting tired with last two day, i did`t know what should be do. if possible any solution, it could be help for me and other developer.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v7.9.0

Hi guys,

i need help for the **this.router.navigate['/home']**, when i click this link, i redirect the Home-component,
but it`s just HTML and CSS code, then manually **i refresh browser** then my **JQUERY load** and then enable my functionality, **i need to load JQUERY at a time of redirect** my Home-component, i am getting tired with last two day, i did`t know what should be do. if possible any solution, it could be help for me and other developer.

**Comment by roeba** [comment]
Have you even read the text that was already present in the textbox when you created this issue? About guidelines and stuff like

**IF YOU DON'T FILL OUT THE FOLLOWING INFORMATION WE MIGHT CLOSE YOUR ISSUE WITHOUT INVESTIGATING**

**Comment by Nikyypatel** [comment]
@roeba if you did`t know the solution, **stay out from this ticket**, either give the solution. i think you have to read carefully, **are you a good developer???**  i think **NO**, we need solution, not this type of suggestion, and keep in mind this is not social site that whatever you comment, be a mature dear.
have a good time.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by Toxicable** [comment]
@Nikyypatel Sorry but this is not the place for Support requests. 
Also please do not insult other people here, this is not the place for it
