### ISSUE TITLE
reexport constructDependencies function from core/index

### ISSUE THREAD

**Issue by dvabuzyarov** [angular/angular#17114]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The function is marked as exported but not reexported from @angular/core

**Expected behavior**

To be able to export this function from @angular/core

**Minimal reproduction of the problem with instructions**

```typescript
import {constructDependencies, ReflectiveDependency} from '@angular/core';
```
**What is the motivation / use case for changing the behavior?**

For unit testing a class I am creating a DI container with mocked dependencies. In order to create that mocks I need to know what dependencies the tested class has. 
This function reflects a class and returns its dependencies.
So I am doing this

```typescript
export function createInjector(constructor: Function): Injector {
    'use strict';

    const providers = [constructor] as Array<any>;
    const dependecies = constructDependencies(constructor, undefined);
    dependecies.forEach((dependency: ReflectiveDependency) => {
        const keyDisplayName = dependency.key.displayName;
        const mock = createMock(keyDisplayName);
        const provider = {provide: dependency.key.token, useValue: mock};
        providers.push(provider);
    });
    return ReflectiveInjector.resolveAndCreate(providers);
}
```
**Please tell us about your environment:**

Windows, MacOS, WebStorm
* **Angular version:** 4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.10.3

**Comment by pkozlowski-opensource** [comment]
We don't have intention of exporting it as public API for now.
