### ISSUE TITLE
<ng-template> doesn't work with *ngIf ; else syntax

### ISSUE THREAD

**Issue by klinki** [angular/angular#17111]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`<ng-template *ngIf="something; else somethingElse">this is true</ng-template>` doesn't work properly  - only else branch is showed.

**Expected behavior**
It should work in both cases.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/ezqIoOmJ03sRCYG4kvkB?p=preview

Try to click on first toggle button

* **Angular version:** 4.1.3

**Comment by dawidgarus** [comment]
https://angular.io/docs/ts/latest/guide/structural-directives.html#!#ng-container

**Comment by vicb** [comment]
As mentioned in the previous comment `<ng-template>` is used to declare a template. What you want here is to hide/display some nodes:

```html
          <ng-container *ngIf="first; else notFirst">
              Hello World!
          </ng-container>
          <ng-template #notFirst>
              Or Not!
          </ng-template>
```

**Comment by klinki** [comment]
Right. Thanks, I was little bit confused, because lately I've been working with Aurelia and there it works little bit differently. (There everything works with `<template>` tag).

Btw I just noticed it is required to use `<ng-template>` for the second part. It is little bit confusing, since it cannot be used for the first part, but anything else cannot be used for the second :( 

It would be perfect if this could be used:
```html
<ng-container *ngIf="first; else notFirst">
   Hello World!
</ng-container>
<ng-container #notFirst>
  Or Not!
</ng-container>
```

**Comment by trotyl** [comment]
It's OK to use `ng-template` all the time, but in that way the DSL syntax sugar is not available, like:

```typescript
<ng-template [ngIf]="first" [ngIfElse]="notFirst">
  Hello World!
</ng-template>
<ng-template #notFirst>
  Or Not!
</ng-template>
```

**Comment by klinki** [comment]
@trotyl Thanks! I haven't seen that in documentation :(

**Comment by tytskyi** [comment]
@klinki there is an explanation of desugaring of `*` https://angular.io/docs/ts/latest/guide/structural-directives.html#!#asterisk

**Comment by klinki** [comment]
@tytskyi Thanks. I was looking at https://angular.io/docs/ts/latest/api/common/index/NgIf-directive.html#!#ngIfElse-anchor  and unfortunately there is no example with destructured syntax for if-else :(

**Comment by tytskyi** [comment]
@klinki sorry, but there is that example on the page:

`Find on page` -> `Syntax` 

**Syntax**
Simple form:

```html
<div *ngIf="condition">...</div>
<div template="ngIf condition">...</div>
<ng-template [ngIf]="condition"><div>...</div></ng-template>
```

**Comment by klinki** [comment]
@tytskyi Not for `else` block. I was looking specifically for that one, since it is new for me.
