### ISSUE TITLE
Router.url gives "/" on page refresh.

### ISSUE THREAD

**Issue by cedvdb** [angular/angular#17119]
**Bug report** 

**Current behavior**

When starting the app on an url other than the base url, say localhost/test, the router.url is equal to "/".

**Expected behavior**

Expected behavior would be to have the router.url to be the url the user access.  If user access localhost:4200/test then router.url should be "/test" and not "/".

**Minimal reproduction of the problem with instructions**

   https://github.com/cedvdb/Router-thing

 ng new testRoute && ng g s test &&  ng g c test

**app.comp**
```
  constructor(private test:TestService){}
  ngOnInit(){
    test.init();
  }
```
**test.service**

```
  constructor(private router:Router) { }
  init(){
    console.log(this.router.url); // will display "/" whatever the url is on first page load
  }
```

**Module**

```
    RouterModule.forRoot([
      {path: '', component: TestComponent},
      {path: 'test', component:  TestComponent}
    ])
```

Then access localhost:4200/test, the console will display the current url to be "/"

**What is the motivation / use case for changing the behavior?**
 
It is annoying in the following scenario:

You have an app that needs initialization. User access mysite.com/some-url. App save the state of router.url, redirect the user to mysite.com/loading, then upon app initialization redirects the user to mysite.com/some-url. The current behavior will redirect the user to mysite.com.

**Please tell us about your environment:**

* **Angular version:** 4

* **Browser:** [Chrome  | Firefox | others not tested ]

**Comment by vicb** [comment]
This is probably a server configuration error.

**Comment by cedvdb** [comment]
@vicb  It's the default configuration from the cli. 

I understand you want an easier reproduction with a plnkr, but it's impossible to make one that would lead directly to` /test` instead of `/`.
