### ISSUE TITLE
Link to NgModules Guide gives 404

### ISSUE THREAD

**Issue by august-of-wind** [angular/angular#17116]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In the Multiple Components section of the Tutorial, there is a link to an NgModules guide (it says "Read more about Angular modules in the NgModules guide.") 
Clicking it throws a 404 error. The link can be found on this page: https://angular.io/docs/ts/latest/tutorial/toh-pt3.html

**Expected behavior**

Link should point to a valid page.

**Minimal reproduction of the problem with instructions**

Click the NgModules link in the Multiple Components section of the Tutorial
**What is the motivation / use case for changing the behavior?**

This link should point to a valid page. It is confusing to the user if it does not.

**Please tell us about your environment:**

I am on Windows 10 using Chrome

* **Angular version:** 2.0.X

N/A

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

I have encountered this in Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

N/A

* **Node (for AoT issues):** `node --version` =   

N/A

**Comment by ericmartinezr** [comment]
They're working on the new docs over here https://aio-staging.firebaseapp.com/tutorial/toh-pt3 and the link is working fine, they will merge it "soon" to angular.io.

**Comment by august-of-wind** [comment]
Thanks @ericmartinezr, good to know. 👍
