### ISSUE TITLE
Information Missing

### ISSUE THREAD

**Issue by viralstegowl** [angular/angular#17113]
https://angular.io/docs/ts/latest/api/http/Http-class.html <--- This link is not working.

**Comment by ericmartinezr** [comment]
It is working here https://aio-staging.firebaseapp.com/api/http/Http (they're working on the new docs there)

**Comment by tytskyi** [comment]
https://angular.io/docs/ts/latest/api/http/index/Http-class.html

**Comment by viralstegowl** [comment]
@ericmartinezr Is that the new home for angular 4?
This is the domain now : https://aio-staging.firebaseapp.com/ ?

Should I stop using : https://angular.io/ ??

Thank you so much for the reply.

**Comment by ericmartinezr** [comment]
@viralstegowl not really. They're working the docs in aio-staging, when they finish with the new docs they will merge it into angular.io, so don't worry about that 👍

**Comment by viralstegowl** [comment]
@ericmartinezr : Ohh thank you so much sir. Am I right, to directly start with angular 4 and skip AngularJS and angular 2?

**Comment by trotyl** [comment]
@viralstegowl There is no "Angular 2" and "Angular 4" stuff, just different release versions of Angular, see http://angularjs.blogspot.hk/2016/12/ok-let-me-explain-its-going-to-be.html and http://angularjs.blogspot.hk/2017/01/branding-guidelines-for-angular-and.html for more information.

And yes it's right to start with latest version.

**Comment by petebacondarwin** [comment]
Closing as this is not an issue with Angular nor the docs app. We will release the new docs app on to angular.io when we release Angular 4.0.0.

**Comment by viralstegowl** [comment]
@petebacondarwin : Ok thank you sir. Do you have an ETA on that?
