### ISSUE TITLE
FR: ability to configure routes based on something other than order

### ISSUE THREAD

**Issue by natsid** [angular/angular#17127]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently the Angular router checks all the routes in the routes array in depth-first order to find a matching route. It follows the _first_ matching route.

That means that if you have, for example, `{path: '**', component: PageNotFoundComponent}` as the first route in the array, then every URL will match that path without first checking whether it fully matches another route. This works OK when all routes are defined in the same place - you can just make sure to put all the routes in the order you want things to be matched. But it gets a bit sketchy when routes are added to the routes array from different places, different files.

**Expected behavior**
Expect there to be some way to prioritize routes, or look for "fullest" match before choosing a route. At the very least, it would be really helpful to have a way to specify an "otherwise" route that is different from a wildcard route in that it would only match if nothing else does.

**Minimal reproduction of the problem with instructions**
Two examples:

- Wildcard must come _last_ in order to work as an "otherwise" route
- Paths with route parameters must be carefully ordered. Example: if you had both `{path: 'hero/:id', component: HeroDetailComponent}` and `{path: 'hero/add', component: AddHeroComponent}` in that order, a URL of 'hero/add' would always match the 'hero/:id' path first.

**What is the motivation / use case for changing the behavior?**
In our use case, we add routes to the routes array from several different files. To make sure the wildcard route is at the end of the array, we use `unshift()` to add all the other routes to the _beginning_ of the array (rather than `push()` which adds elements to the _end_ of an array). Relying on the exact order of routes seems very error-prone.

* **Angular version:** 4.1.x

* **Browser:** all

Thanks!

**Comment by dawidgarus** [comment]
It's not always obvious which route should come first.
What about `/resource/:id/details` vs `/resource/group/:name`?
Also custom url matcher complicate things a lot.
Maybe sorting routes by path after You add one will be sufficient:
```js
paths = ['hero', 'hero/add', 'hero/:id', '**']
paths.sort().reverse()
// paths = ["hero/add", "hero/:id", "hero", "**"]
```
