### ISSUE TITLE
BUG: *ngIf Doesn't Handle Code Within Containing Div as Expected

### ISSUE THREAD

**Issue by darrenbrett** [angular/angular#17122]
My dev environement:
Angular 2
@angular/cli: 1.0.1
node: 7.4.0
os: darwin x64
MacBook Air

I have some Material2 UI in my Angular 2 app that is designed to allow only certain users (in this case - admins) to be able to select and thus assign roles to a user. If the current user is not an admin, I want to hide the UI altogether. 

Right now, while most of the UI is being disabled  as I would expect, I still see a popup (it just doesn't show any values). So, while a non-admin user can't assign a role (which is good), ideally I don't want the md-checkbox popup happening at all, even if it's a blank popup. This is what I have in my component view:

    <div *ngIf="isAdmin()" class="visit-type-roles-options">
        <md-checkbox *ngFor="let option of roles.options" [(ngModel)]="option.value">
           {{option.role}}
        </md-checkbox>
    </div>
    
The values that are being iterated over look like this in the component:

    roles = {
        enabled: true,
        options: [
            { toolbarLabel: 'R1', role: 'Role 1', value: false },
            { toolbarLabel: 'R2', role: 'Role 2', value: false },
            { toolbarLabel: 'R3', role: 'Role 3', value: false }
        ],
        text: null
    };

The "isAdmin()" function is a simple boolean check, that looks like this:

    isAdmin() {
        return this.hasAdminAccess;
    }
    
As I mentioned, when I set the "hasAdminAccess" to "true" in the component, I see my role options popup in the md-checkbox, as expected. When I set "hasAdminAccess" to "false" however, while the values are hidden (so they can't be selected), I still see a small popup with nothing in it. My expectation here, based on the use of *ngIf in the containing div, is that nothing would appear upon the return of a "falsey" value.

**Comment by z3v0k** [comment]
+1
