### ISSUE TITLE
'keydown.alt.1' doesn't trigger on mac

### ISSUE THREAD

**Issue by studds** [angular/angular#17128]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

1. Add an `@HostListener('keydown.alt.1') onAlt1() { console.log('option/alt-1 pressed'); }`
2. Open the browser, focus the field and press option-1 on Mac (Chrome / Safari)
3. Nothing appears in the console

The underlying problem appears to be that BrowserDomAdapter#getEventKey() returns ¡ for option-1 on mac.

**Expected behavior**

The `HostListener` is triggered and "option/alt-1 pressed" is logged to the console.

**Minimal reproduction of the problem with instructions**

Plunker: http://plnkr.co/edit/yJ65kLBDYx0RBWUyLF23?p=preview

**What is the motivation / use case for changing the behavior?**

Want to be able to use alt key in cross-platform keyboard shortcuts without having to map Mac vs Windows shortcuts.

**Please tell us about your environment:**

Mac OS, Chrome / Safari

* **Angular version:** v4.1.3 (I'm running v2.x locally, but also repros on 4.1.3 in plunker)

* **Browser:** Chrome 58.0.3029.110 | Safari 10.1 (didn't test in FF)

 
* **Language:** Typescript 2.1

**Comment by vicb** [comment]
see also #9419

**Comment by JoostK** [comment]
This was recently brought to our attention again in #45992, for which a PR is being worked on. So I'm going to close this as a dup (even though it's 5 years older).
