### ISSUE TITLE
http.put freezes browser

### ISSUE THREAD

**Issue by jadamsdb** [angular/angular#17121]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Whenever I call an http.put, the screen will freeze until the response comes back.

**Expected behavior**
I would expect the call to be made and not have to wait for the response before I am able to continue with work.

**Please tell us about your environment:**
Windows webpack

* **Angular version:** 2.4.0

* **Browser:** Chrome
 
* **Language:** [TypeScript 2.1.4 | ES5]

**Comment by vicb** [comment]
Could please attach a small repro - easiest is probably to use plunkr as described in the issue template

**Comment by alxhub** [comment]
Yes, please re-open with a reproduction if possible, @jadamsdb.
