### ISSUE TITLE
routerLink does not strip out undefined queryParams (unlike router.navigate)

### ISSUE THREAD

**Issue by kylepl** [angular/angular#17120]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using routerLink with queryParams with undefined values propagates those values to the URL (e.g. foo.com/bar?baz=undefined).

**Expected behavior**
queryParams that have undefined values should be stripped. e.g. instead of navigating to foo.com/bar?baz=undefined it should navigate to foo.com/bar. This is the behaviour of router.navigate.

**Minimal reproduction of the problem with instructions**
*MINIMAL DEMO*
http://plnkr.co/edit/RhIyngSganGyiYVqPqF1

The demo shows navigating the same path, with an undefined queryParams value using both routerLink and router.navigate. Only routerLink sets the value as undefined.

**What is the motivation / use case for changing the behavior?**
I was switching a case from using router.navigate to using routerLink, and the mismatching behaviour was unexpected. I also think this just the continuation of https://github.com/angular/angular/issues/7543.

**Please tell us about your environment:**
Plunkr example encapsulates the issue.

* **Angular version:**
4.1.3

* **Browser:**
Chrome 58.0.3029.110 (64-bit)
 
* **Language:**
Typescript

**Comment by tproenca** [comment]
+1

**Comment by tproenca** [comment]
Any updates on this?

**Comment by jasonaden** [comment]
This appears to be fixed by current version. Please create a new issue if you're still having a problem.
