### ISSUE TITLE
docs: testing - clarify mocking when dependent service depends on Http

### ISSUE THREAD

**Issue by sharikovvladislav** [angular/angular#17126]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am reporting a bug with a documentation, not with Angular itself or with app based on Angular.

Here is the docs: https://angular.io/docs/ts/latest/guide/testing.html#!#component-with-async-service . This docs explains how to unit test service/component which depend on another servers which in turn depends on `Http. 

Docs says that I have to:
1) inject real service in providers
2) get actually injected into the component service
3) setup spy

I run my unit tests and I got error: `Error: No provider for Http!`. This error is confusing (at least for me, for guy who does not have enough experience with Angular 2+).

Since I wrote some units for service which depends on Http I had assumed that I need to import HttpModule, but I was not sure, because docs does not say it. I wrote a post on stackoverflow.com. Here is it: [How to test a service/component which depends on another service which in turn depends on Http service?](https://stackoverflow.com/questions/44272683/how-to-test-a-service-component-which-depends-on-another-service-which-in-turn-d). And @jnizet (thank you very much!) clarified this for me.

So I think there is a bug in the docs, because it is not clarified enough for beginners to obviously understand this error.

**Expected behavior**

It would be awesome if docs will clarify it.

**Minimal reproduction of the problem with instructions**

1. Open [this](https://angular.io/docs/ts/latest/guide/testing.html#!#component-with-async-service)
2. Read the topic
3. Try to implement what docs says
4. Get error and spend time for asking about it in slack/gitter/etc

**What is the motivation / use case for changing the behavior?**

Because now docs are a not enough clarified in that case.

**Please tell us about your environment:**

Does not matter, its about website.
* **Angular version:** 2.0.X

Does not matter, its about website.
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Does not matter.
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular for TypeScript Docs
* **Node (for AoT issues):** `node --version` =   
Does not matter.

**Comment by Foxandxss** [comment]
I would see to add a note that says that if your real service depend on others, you need to import them as well.

**Comment by sharikovvladislav** [comment]
Yes. This would be great!

For example: since, you use real service instead of mock, you have to
import real service dependencies as well.

2017-05-31 13:56 GMT+03:00 Jesús Rodríguez <notifications@github.com>:

**Comment by mgechev** [comment]
We did an improvement in that space with angular.io/errors. As part of the effort we documented the missing providers error. I'll close this issue as fixed :).
