### ISSUE TITLE
docs(aio): tutorial (part 6 | routing) missing code box

### ISSUE THREAD

**Issue by turtleDev** [angular/angular#17134]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
![untitled](https://cloud.githubusercontent.com/assets/12575843/26631577/54e411c6-4629-11e7-83df-d0da5e0156c7.png)

at the end of the section `Refactor routes to a Routing Module`, there's an artefact of build process, and probably a missing code box.

There should have been a code box there that showed the changes described in that section.

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/16913

**Comment by gkalpak** [comment]
@ericmartinezr is right. This has been fixed (as you can see [here][1]) and the fix will be released soon.

[1]: https://aio-staging.firebaseapp.com/tutorial/toh-pt5#update-appmodule
