### ISSUE TITLE
nhandled Promise rejection: Template parse errors: Can't bind to 'ngSelected' since it isn't a known property of 'md-option'. 1. If 'md-option' is an Angular component and it has 'ngSelected' input, then verify that it is part of this module.

### ISSUE THREAD

**Issue by saimzishan** [angular/angular#17130]
<md-select placeholder=""  name="customer_id" formControlName="customer_id"
                             [(ngModel)]="truckList.customer_id">
                    <md-option (click)="onChange(customer.id)" *ngFor="let customer of loadLists; let i = index"
                               [ngSelected]="customer.id == truckList.customer_id" [value]="customer.id" >
                      {{ customer.customer_name }}
                    </md-option>
</md-select>

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
