### ISSUE TITLE
Router: additional navigation to / when opening link in new tab with async calls in guards/resolvers

### ISSUE THREAD

**Issue by karlhaas** [angular/angular#17132]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When:

- we open a link to our application (including a route after #, HashLocationStrategy) in a new browser tab 
- the address bar of the browser first shows the right route
- we are using a resolver (same behavior with guards) that fetches data from the server
- during the execution of the async call, the route changes to /
- after the execution the routes changes back to the original route

This causes that we have an additional entry in the browser history.

If we open a new tab first and copy the href into the browser address bar, then the route does not change to / and there is no additional history entry (empty history).

**Expected behavior**
Same behavior as when we open a new tab and copy the href into the browser address bar. empty history. route does not change in the address bar.

* **Angular version:** 4.1.2

* **Browser:**
Chrome 58, Firefox 53
 
* **Language:** 
TypeScript 2.1

* **Node (for AoT issues):**
v6.10.3

**Comment by vicb** [comment]
Could you please add a small repro. Thanks

**Comment by karlhaas** [comment]
@vicb when I tried to produce a small reproduction repro, I found out that we caused the additional history entry by an redirect instead of an replace navigation. Sorry.
