### ISSUE TITLE
Remove or make configurable the Http Json.stringify formatting

### ISSUE THREAD

**Issue by davidwalschots** [angular/angular#17135]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently Http post function will JSON.stringify the input with a two space indentation format. As found in [Body](https://github.com/angular/angular/blob/master/packages/http/src/body.ts).

**Expected behavior**

I'm requesting that we allow for no formatting to be applied; to reduce the size of the request and keep it consistent with AngularJS behaviour.

**What is the motivation / use case for changing the behavior?**

We're storing certain requests coming from an AngularJS application in a database for further analysis. Within the AngularJS application we send a non-formatted JSON string. We'd like to send the exact format within an Angular application; however this isn't possible, unless you fiddle around with the content-type header before invoking the `Http.post` function.

* **Angular version:** 4.1.2

**Comment by alxhub** [comment]
Fixed in `HttpClient`.
