### ISSUE TITLE
Returning a rejected promise in router Resolver throws an error

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#17148]
Rejecting a resolve will cause an error `ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'ngNavigationCancelingError' of null`. This effectively stops navigation, but is an unintended error.

The problem with this error is that creating an instance of `NgNavigationCancelingError` is a private API. Therefore in user-land there doesn't seem to be a way to reject a resolve.

**Comment by nikkwong** [comment]
I can also confirm the presence of this bug, but for now I got it to work by returning `Observable.fromPromise()` and then using `resolve` or `reject` from that promise as per you usually would.

**Comment by daniel-mcassey-tmsuk** [comment]
Having the same issue

**Comment by mahmood-sajjadi** [comment]
yes same issue here
I found another ugly workaround!

https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L735
`if (isNavigationCancelingError(e)) {`
https://github.com/angular/angular/blob/master/packages/router/src/shared.ts#L100:L104
`export function navigationCancelingError(message: string) {
  const error = Error('NavigationCancelingError: ' + message);
  (error as any)[NAVIGATION_CANCELING_ERROR] = true;
  return error;
}`


so ugly solution is:
`return Observable.throw({message: 'some message', ngNavigationCancelingError: true});`

the important part is : 
`ngNavigationCancelingError: true`
becuse:
https://github.com/angular/angular/blob/master/packages/router/src/shared.ts#L98

Hope it helps someone

**Comment by Dashue** [comment]
+1
