### ISSUE TITLE
Small code fix in Forms documentation example at angular.io

### ISSUE THREAD

**Issue by ashishgaikwad** [angular/angular#17149]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the final example code given at the end of the page for Forms documentation under Guide at https://angular.io/docs/ts/latest/guide/forms.html. The ```hero.ts``` file constructor is empty.
This makes the code in ```hero-form.component.ts``` to initialise empty Hero objects which is not expected as per the example.

**Expected behavior**
The proper code for the ```hero.ts``` file should be 
```
export class Hero {
  constructor(
    public id: number,
    public name: string,
    public power: string,
    public alterEgo?: string
  ) { return this; }
}
```
for the ```new``` keyword based invocation to work fine. For example the line of code
```model = new Hero(18, 'Dr IQ', this.powers[0], 'Chuck Overstreet');``` in the 
```hero-form.component.ts``` file.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by gkalpak** [comment]
The empty constructor works fine (as can be verified in the [live example][1]).

[1]: https://angular.io/resources/live-examples/forms/ts/eplnkr.html

**Comment by ashishgaikwad** [comment]
Thank you for the explanation. I couldn't find the plnkr link yesterday.
