### ISSUE TITLE
Hammer gestures by default prevent event propagation

### ISSUE THREAD

**Issue by darkcircuituk** [angular/angular#17159]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When binding to any gesture (press, pan, etc) the default browser behaviour is stopped regardless of whether event propagation is cancelled or not. Looking at the markup I can see that the touch-action css property is being set to none, which is causing this issue.

**Expected behavior**
The default browser behaviour should continue after the event handler has finished unless the event has been cancelled (i.e. event.preventDefault()). This means that I'd expect the touch-action property to not be set to none unless event.preventDefault() is called.

**Minimal reproduction of the problem with instructions**
The following plunker shows the addition of the touch-action CSS property to the div with the (swipe) action, which means that although the expected function (swipe()) is called on swipe of the 'Hello Angular! v4.1.3' text, the browser swipe to scroll is disabled:
http://plnkr.co/edit/2Y3TsrVbN1qdEgsObtF9?p=preview

**What is the motivation / use case for changing the behavior?**
Current behaviour limits the ability to perform gestures conditionally, i.e. only if a variable is set to a specific value should the browser default behaviour be stopped.

**Please tell us about your environment:**
Windows 10, npm package manager, Apache Cordova environment running on an Android device

* **Angular version:** 2.0.X
Angular 4.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
I'm running ES5, but likely affects all

* **Node (for AoT issues):** `node --version` =   
Node --version = 7.6.0

**Comment by vicb** [comment]
> Looking at the markup I can see that the touch-action css property is being set to none, which is causing this issue.

This is the default Hammer behavior.

You should be able to override it by injecting a custom HAMMER_GESTURE_CONFIG.
