### ISSUE TITLE
Parse5DomAdapter.setStyle throws an error

### ISSUE THREAD

**Issue by rkonstantinov** [angular/angular#17161]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When setting style to an child element of native element an error (`Cannot set property 'style' of undefined`) is throw.
Looking at the code for [`_writeStyleAttribute`](https://github.com/angular/angular/blob/5293794316cc1b0f57d5d88b3fefdf6ae29d0d97/packages/platform-server/src/parse5_adapter.ts#L461) it seem that the style value is assign without checking if the `attribs` field exists (which, if I have follow the flow correctly, usually is added when `importIntoDoc` is called). Thus, maybe changing the `_writeStyleAttribute` similar to the following should be sufficient in addressing this.
```javascript
  _writeStyleAttribute(element: any, styleMap: any) {
    let styleAttrValue = '';
    for (const key in styleMap) {
      const newValue = styleMap[key];
      if (newValue) {
        styleAttrValue += key + ':' + styleMap[key] + ';';
      }
    }
    //element.attribs['style'] = styleAttrValue;
    const attribs = element.attribs || {}; <<<<<
    attribs['style'] = styleAttrValue; <<<<
    element.attribs = attribs; <<<<
  }
```

**Expected behavior**
To be able to set the style :)

**Minimal reproduction of the problem with instructions**
 - In an Angular Universal app (such as https://github.com/ng-seed/universal) create the following component:

```javascript
import { AfterViewInit, Component, ElementRef, Renderer2, ViewChild } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <h1 #container>
      <span>foo</span>
    </h1>
  `
})
export class AppComponent implements AfterViewInit {
  @ViewChild('container') container: ElementRef;

  constructor(private renderer: Renderer2) { }

  ngAfterViewInit(): void {
    // the next line will throw "Cannot set property 'style' of undefined" from Parse5DomAdapter.setStyle method
    this.renderer.setStyle(this.container.nativeElement.children[0], 'background', 'red');
  }
}

```
- During the server rendering phase a `Cannot set property 'style' of undefined` error will be raised.

Thanks

**Comment by adrienboulle** [comment]
@rkonstantinov it's because children[0] is not the span but the text between `#container>` and <span` : `/n     `
You should target the span by a `ViewChild` to be certain to target the right element

**Comment by rkonstantinov** [comment]
Then it behaves differently than the browser DOM implementation as the code works as expected in the browser.
Also if I understood correctly the [children](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children) should return elements, to which setting an attribute should be possible.

**Comment by adrienboulle** [comment]
Indeed that's the way they designed it in the library user by platform-server :
https://github.com/inikulin/parse5/blob/master/lib/tree_adapters/htmlparser2.js
Node.children is just a shorthand to Node.childNodes

For having used quite a lot platform-server in the last two months almost as my full-time job, I can give you an advise, the less you use directly nativeElement the better.
As you can understand, the nativeElement during ssr is not a dom element, so every time you try to use it directly, you take the risk that what you use is not implemented exactly as in the browser or event not implemented at all.
So if you can use a ViewChild, just do it. If you can use the renderer, just do it (it's true even if you dont use platform-browser btw) and if you have no choice, keep in mind that you are not in the browser and cannot expect it to behave the same :)
