### ISSUE TITLE
Unhelpful error message:  Invalid binding Shapes

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#1716]
The error message should explain (a) why the binding is invalid and (b) hints to fix it.

In this case, there are multiple locations in _resolveBindings() that produce the same error
e.g.
```
#0      _resolveBindings (package:angular2/src/di/injector.dart:334:7)
#1      Injector.resolve (package:angular2/src/di/injector.dart:88:28)
#2      Injector.resolveAndCreateChild (package:angular2/src/di/injector.dart:163:34)
#3      _createAppInjector (package:angular2/src/core/application.dart:327:24)
#4      bootstrap.<anonymous closure> (package:angular2/src/core/application.dart:303:9)
```

**Comment by pkozlowski-opensource** [comment]
@jbdeboer I've changed this error message recently, hopefully it is a bit better now, see https://github.com/angular/angular/blob/655ed851f021d5faa6e1d56d19375c8e9ab0bae0/modules/angular2/src/di/exceptions.ts#L164-L165

What would be the ideal wording you would like to see here?
