### ISSUE TITLE
CodeDrops - Double Scroll feature from jquery to Angular - is there a better way to select elements in the dom which have events compared to jquery?

### ISSUE THREAD

**Issue by xtianus79** [angular/angular#17163]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Code example from Jquery to Angular
```

**Current behavior**
The current behavior uses jquery but I have since ported it to Angular and was wondering if there was any better way to select elements in the dom which have events.  My example works but was wondering if there was inherently something else I should be doing to make it a more efficient design

**Expected behavior**
One thing I wasn't able to do is set the selected dom element to a variable or it wouldn't work... confused as to why that is the case. 

**Minimal reproduction of the problem with instructions**
https://embed.plnkr.co/eYz2c8/

this is the jquery example
http://jsfiddle.net/TBnqw/1/

**What is the motivation / use case for changing the behavior?**
Wanting to know in general good use cases of element and id selectors in Angular vs Jquery

* **Angular version:** 2.0.X
4.2+

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
