### ISSUE TITLE
Change detection kicked of 4 times for each XMLHttpRequest

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17167]
@angular/core@4.1.2
zone.js@0.8.11

<img width="1915" alt="screen shot 2017-06-01 at 6 23 01 pm" src="https://cloud.githubusercontent.com/assets/216296/26704890/eaaa019c-46f7-11e7-890a-f1c23acc01d1.png">

We fire change detection for all ReadyStateChange events + the Load event, even if all we are listening on is the Load event.

I looked into this and it seems that there is something wrong with the XHR patch in zone.js or less likely in NgZone.

The issue repro's with @angular/http or even with plain XMLHttpRequest object used as follows:

```
    var xhr = new XMLHttpRequest();
    xhr.open('GET', 'assets/data/data.json');
    xhr.onload = () => {
      console.log(xhr.responseText)
      this.processData(JSON.parse(xhr.responseText));
    };
    xhr.send();
```

If we switch over to using `fetch` (which is patched differently by zone.js), we trigger just one change detection.

**Comment by vicb** [comment]
Have you checked the callback for the `ReadyStateChange` event (could something really listen to it ?)

**Comment by PeterDavidCarter** [comment]
Would I be correct in saying that this has the potential to cause a huge performance issue with medium to large-apps, particularly highly dynamic apps with a number of state changes?

**Comment by Toxicable** [comment]
@PeterDavidCarter it's hard to generalize apps into categories like that for this issue since for example a large app may only use WebSockets exclusively where I assume it would be unaffected by this issue. However, in applications that use Http extensively who also have a large amount of data bound to templates (causing long Change Detection runs), yes this definitely could effect those applications performance

**Comment by gkalpak** [comment]
My guess is that this happens because the [patched `send()`][1] method, adds a [listener for `readystatechange`][2].

[1]: https://github.com/angular/zone.js/blob/89f990a5e1910e6b7e65f9c8d7944fed8bf7e833/lib/browser/browser.ts#L134
[2]: https://github.com/angular/zone.js/blob/89f990a5e1910e6b7e65f9c8d7944fed8bf7e833/lib/browser/browser.ts#L97

**Comment by IgorMinar** [comment]
@vicb nobody is listening on that event as george pointed out it's coming
from a listener registered within the zone itself.

**Comment by vicb** [comment]
or do you mean "a listener registered within the zone itself is listening on that event as George pointed out" ? ;)

**Comment by JiaLiPassion** [comment]
@IgorMinar 

I can't reproduce with angular 4.1.2 and zone.js 0.8.11, 

this is my test code.

```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `<h1>Hello {{name}}</h1><button (click)="test()">Test</button>`,
})
export class AppComponent  { 
  name = 'Angular';
 
  test() {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', 'http://localhost:3000/asprrb/jboss/BrandCodeNameAllSearchAction.do');
    xhr.onload = () => {
      console.log(xhr.responseText);
      //this.processData(JSON.parse(xhr.responseText));
    };
    xhr.send();
  }
}
```

And this the output
<img width="1440" alt="2017-06-03 2 48 54" src="https://cloud.githubusercontent.com/assets/1442575/26737931/3627aaec-4807-11e7-8d0c-daf8e3003127.png">

Is my test code correct?

**Comment by Denhai** [comment]
4.1.3

without aot
![screen shot 2017-06-03 at 11 46 34 am](https://cloud.githubusercontent.com/assets/10227167/26749949/6e9afd76-4856-11e7-9283-c45c72af8a24.png)

with aot
![screen shot 2017-06-03 at 11 46 11 am](https://cloud.githubusercontent.com/assets/10227167/26749955/73f70896-4856-11e7-83bd-63b37ed4a7e3.png)

**Comment by JiaLiPassion** [comment]
@Denhai , can you share your test code? I still can't reproduce with 4.1.3.

**Comment by JiaLiPassion** [comment]
the reason is in `zone.js`, it will add `onreadystatechange` listener to invoke the task.
https://github.com/angular/zone.js/blob/master/lib/browser/browser.ts#L97

```javascript
   var newListener = data.target[XHR_LISTENER] = function () {
                if (data.target.readyState === data.target.DONE) {
                    // sometimes on some browsers XMLHttpRequest will fire onreadystatechange with
                    // readyState=4 multiple times, so we need to check task state here
                    if (!data.aborted && XMLHttpRequest[XHR_SCHEDULED] &&
                        task.state === 'scheduled') {
                        task.invoke();
                    }
                }
            };
            data.target.addEventListener('readystatechange', newListener);
```

And `onreadystatechange` will be triggered 3 times because `readyState` will change 
as `2`, `3`, `4`.

**Comment by 0pt1m1z3r** [comment]
@JiaLiPassion Hi, as I see this problem reappeared.
4 "XHR Ready State Change" and 1 "XHR Load" are triggered.

@angular/core@5.2.11
zone.js@0.8.29

![2019-02-10 01 34 01](https://user-images.githubusercontent.com/4936833/52527093-029c5700-2cd4-11e9-9b83-addcf2856813.png)
