### ISSUE TITLE
component @Input trackBy and default array trackBy

### ISSUE THREAD

**Issue by jerradpatch** [angular/angular#17172]
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Adding or deleting from an array causes no change on a component input.

**Expected behavior**
I would expect the child to be updated when array changes content.

**Minimal reproduction of the problem with instructions**
Obvious.

**What is the motivation / use case for changing the behavior?**
For user experience, ease of the framework use, animation purposes, and performance purposes. It is desirable to add and remove from an array and have a component input update, rather then copy the whole array to a new array (.splice()), or some hack like 

[input]={trackBy: model.length, value: model}.

It is intuitive to expect the component @input to update with content changing and can lead to some head scratching for someone new to the framework. Also, if a developer does do .splice() to get the input to recognize the change in array content, then it can lead to other head scratchers such as animation issues or performance loss in an *ngFor loop (when all templates are reconstructed due to whole array changing).

I would suggest adding a trackBy feature to components @input. In addition, checking an input for an array type and if its an array type then default trackBy length of that array. Also, this default trackBy would not be susceptible to an update every change detection, since an array of the same length would be assumed to have not been modified.

This trackBy feature on an component input can be just as useful for arrays as it could be for nested objects. Imagine:

[input]="objectA"
[input.trackBy]="objectA.ObjectB?.objectC.value1"

* **Angular version:** 4.0.0+

**Comment by dawidgarus** [comment]
You can use `IterableDiffer` to detect changes in array. I think that's what `NgFor` does.
```ts
export class MyComponent implements OnInit, DoCheck {

	@Input()
	private input: Type[];
	private inputDiffer: IterableDiffer<Type>;

	constructor(private differs: IterableDiffers) {}
	
	ngOnInit() {
		this.inputDiffer = this.differs.find(this.input).create<Type>(trackByFunction);
	}
	
	ngDoCheck() {
		const changes: IterableChanges<Type> = this.inputDiffer.diff(this.input);
		// do something with changes
	}
}
```

**Comment by jerradpatch** [comment]
My goal is to update the child component on changes in an input array. If the @input never triggers when the patent updates the array, will diff(this.input) still return changes in the child "inout" array?

**Comment by pkozlowski-opensource** [comment]
@dawidgarus is correct here - we don't want to be diffing deep objects - some form of a differ in a component / directive is the way to go. You can check `NgClass` implementation as an example.
