### ISSUE TITLE
Dynamically/Programmatically add new named router outlets to the template. 

### ISSUE THREAD

**Issue by taigi100** [angular/angular#17173]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no simple solution or workaround to add a new named `router-outlet` at runtime.

**What is the motivation / use case for changing the behavior?**
We have a use case where we need to dinamically display modules ( which needs a router ) at runtime.
We have no clue how many modules need to be added. Imagine something like a pluggable framework.

We found a solution to 'inject' a `router-outlet` tag using a `ng-template` and a `ViewContainerRef`. But we have issues with the `name` attribute. Managed to fix this by making our own `router-outlet` directive, but this is not a good long-term solution.

We do not need binding on it, but some way to programatically set the `router-outlet` name only when it is created. Would be lovely if maybe instead of the `@Attribute` we could have something that can take a string property instead of a string literal.

Note: Not sure if this is a duplicate of : #12522. We need to only set it when created insted of having it as an `@Input` ( that would imply binding would work on it )

**Comment by dawidgarus** [comment]
You can create custom directive:
```ts
export class MyOutletDirective implements OnInit {
  @Input() private name: string;
  constructor(private routerOutletMap: RouterOutletMap, private resolver: ComponentFactoryResolver, private vcRef: ViewContainerRef) {}
  ngOnInit() {
    new RouterOutlet(this.routerOutletMap, this.vcRef, this.resolver, this.name);
  }
}
```
Or use `RouterOutlet` class directly in the way that suits You.

**Comment by taigi100** [comment]
@dawidgarus Thanks! This is what I actually ended up doing, but I'm not sure if it is a good ideea longterm.

**Comment by feibabm** [comment]
@taigi100 Can you wite detaits? I first use angular4.

**Comment by feibabm** [comment]
I am using Angular4

**Comment by DGolverdingen** [comment]
@dawidgarus 

Could you create a Plunker example with angular4+ for this? I am not sure how to get this directive working.

**Comment by taigi100** [comment]
@DGolverdingen 

The constructor of the directive has changed, so you will need to change it a little bit in order to match it

**Comment by 82antu** [comment]
Hi,

I used the same solution (more or less) up to 2 weeks ago.

But now  I m moving towards Angular4, and problems  are unspooling:

with new RouterOutlet Directive (creating a MyOutletDirective a @dawidgarus shown ),   I m able to manage a structure like this:

`http://127.0.0.1:8080/page1/((outlet1:route1)//(outlet2:route2)//(outlet3:route3)))`

But, when I m starting to use deeper path like:

`http://127.0.0.1:8080/page1/((outlet1:route1/(sub-outlet1:sub-route1))//(outlet2:route2/((sub-outet2:sub-route2)))//(outlet3:route3)))`

the the deeper route doesn t works.

After creation of structure with `router.resetConfig(...)`

seems that the attempts of activate the deeper route (with `activatewith` method I suppose), comes after

the constructor of the relative MyOutletDirective.

Instead, for the first level of routes, I have, BEFORE, the  constructor and the OnInit of MyOutletDirective, and, AFTER, I see the call of `activatewith` method.

Any suggestion ?

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by hoofa** [comment]
import { Location } from '@angular/common';
import { Directive, OnInit, OnDestroy, Input, ComponentFactoryResolver, ViewContainerRef, ChangeDetectorRef } from "@angular/core";
import { RouterOutlet, ChildrenOutletContexts } from "@angular/router";

@Directive({
    selector: 'named-outlet',
    exportAs: 'outlet'
})
export class NamedOutletDirective implements OnInit, OnDestroy {
    private outlet: RouterOutlet;
    @Input() private name: string;
    constructor(
        private parentContexts: ChildrenOutletContexts,
        private location: ViewContainerRef,
        private resolver: ComponentFactoryResolver, 
        private changeDetector: ChangeDetectorRef,
    ) {}
    ngOnInit() {
      this.outlet = new RouterOutlet(this.parentContexts, this.location, this.resolver, this.name, this.changeDetector);
      this.outlet.ngOnInit();
    }
    ngOnDestroy() {
      this.outlet.ngOnDestroy();
    }
  }



//use in your page template
//<named-outlet [name]="'outletname'"></named-outlet>

**Comment by hoofa** [comment]
`adf`

**Comment by hoofa** [comment]
import { Location } from '@angular/common';
import { Directive, OnInit, OnDestroy, Input, ComponentFactoryResolver, ViewContainerRef, ChangeDetectorRef } from "@angular/core";
import { RouterOutlet, ChildrenOutletContexts } from "@angular/router";

@Directive({
    selector: 'named-outlet',
    exportAs: 'outlet'
})
export class NamedOutletDirective implements OnInit, OnDestroy {
    private outlet: RouterOutlet;
    @Input() private name: string;
    constructor(
        private parentContexts: ChildrenOutletContexts,
        private location: ViewContainerRef,
        private resolver: ComponentFactoryResolver, 
        private changeDetector: ChangeDetectorRef,
    ) {}
    ngOnInit() {
      this.outlet = new RouterOutlet(this.parentContexts, this.location, this.resolver, this.name, this.changeDetector);
      this.outlet.ngOnInit();
    }
    ngOnDestroy() {
      this.outlet.ngOnDestroy();
    }
  }



//use in your page template
//<named-outlet [name]="'outletname'"></named-outlet>

**Comment by mlc-mlapis** [comment]
@hoofa ... try to format your code.
