### ISSUE TITLE
Renderer2 insertBefore() is doing appendChild()

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/angular#17177]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When you do something like this with platform-server during server rendering:

```
  const renderType: RendererType2 = { id: '-1', encapsulation: ViewEncapsulation.None, styles: [], data: {} };
  const renderer = rendererFactory.createRenderer(doc, renderType);
  const script = renderer.createElement('script');
  renderer.setValue(script, 'function someJavaScriptHere() { }');
  renderer.insertBefore(doc.head, script, null);
```
The script tag is inserted at the very end of the HEAD below other script tags that are in the document.

**Expected behavior**

`insertBefore()` should put the script tag right at the top of the HEAD section of the document.

**Minimal reproduction of the problem with instructions**

1. `git clone https://github.com/angular/preboot`
2. `cd preboot`
3. `npm i`
4. Open test/e2e/e2e.server.gen.ts in an editor and add a script tag to line 26 (in the HEAD)
5. `npm run e2e`
6. Look at the html source. You will see that the inline preboot javascript is injected BELOW you script tag in the head instead of above. You can see [insertBefore being called here](https://github.com/angular/preboot/blob/master/src/server/server-preboot.module.ts#L62)

**What is the motivation / use case for changing the behavior?**

In general, it is important that `insertBefore()` works properly. For me, I need it because my injected inline JavaScript must run before any other JavaScript tags in the HEAD section of the document.

**Please tell us about your environment:**

Mac

* **Angular version:** 4.1.3

* **Browser:** Chrome
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   7.9.0

**Comment by uber5001** [comment]
Isn't this the expected behavior of `insertBefore` in general?

The MDN docs on [Node.insertBefore()](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore) say this:

>     var insertedNode = parentNode.insertBefore(newNode, referenceNode);
> If referenceNode is null, the newNode is inserted at the end of the list of child nodes.

**Comment by jeffwhelpley** [comment]
Oh. Ha. I totally missed that. Thanks, @uber5001!

**Comment by gkalpak** [comment]
(Although adding a script like this [does not necessarily guarantee][1] that it will be run before other, inlined scripts.)

[1]: https://www.html5rocks.com/en/tutorials/speed/script-loading/#toc-dom-rescue

**Comment by jeffwhelpley** [comment]
@gkalpak how so? I am doing this on the server side, not the client side. so in the initial server view, this will be the very first script tag. How can anything else run before it?

**Comment by gkalpak** [comment]
Ah, sorry. If it is on the server side then you'll be fine :smiley:
