### ISSUE TITLE
patchValue to a nested formbuilder

### ISSUE THREAD

**Issue by karoul** [angular/angular#17178]
Hello,

I have a problem in how to patchValue in a nested form , here is the layout of my form :

```
this.addAccForm = this.fb.group({
      accid: ['', Validators.required],
      status: '',
      cyc: this.fb.array([
        this.initCyc(),
      ])
    })

initCyc() {
      return this.fb.group({
        cycid: ['', Validators.required],
        name: ['', Validators.required],
        description: ['', Validators.required],
        status: ['', Validators.required],
        det: this.fb.group({
            dcycid: ['', Validators.required],
            status: ['', Validators.required]
        })
      })
```

I have tried this :
`this.addAccForm.patchValue({cyc: { [0]: {cycid: 1234567 }}});`
to set the value but it does NOT help.
And I need also to change the dcycid control :
`this.addAccForm.patchValue({cyc: { [0]: { det : {dcycid: 9876543}}}});`

Any idea how to perform it ?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by karoul** [comment]
all right , sorry about that.
