### ISSUE TITLE
Angular4 doesn't load npm installed Firebase

### ISSUE THREAD

**Issue by PeterDavidCarter** [angular/angular#17174]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am attempting to use npm installed Firebase with my Angular4 app. I have npm installed the latest version of Firebase (version 4.1.1) and checked it has installed correctly. I have input the following code:

```
import { Component, OnInit } from '@angular/core';

import { initializeApp, database } from 'firebase';


@Component({
  selector: 'dInstruct-app',
  styleUrls: [ './app.component.css' ],
  template: `
    <h1>{{title}}</h1>
    <nav>
      <a routerLink="/dashboard">Dashboard</a>
      <a routerLink="/calendar">Calendar</a>
      <a routerLink="/customers">Customers</a>
      <a routerLink="/accounts">Accounts</a>
    </nav>
    <router-outlet></router-outlet>`
})
export class AppComponent implements OnInit{
  title = 'dInstruct';

  config = {
    apiKey: ...
    authDomain: ...
    databaseURL: ...
    projectId: ...
    storageBucket: ...
    messagingSenderId: ...
  };

  ngOnInit(): void {
    initializeApp(this.config);
    database().ref().on('value', (snapshot: any) => console.log(snapshot.val()));
  }
}
```
However, when I attempt to load the app with the above Firebase code in place, it fails with errors:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:28 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/firebase
    Error: XHR error (404 Not Found) loading http://localhost:3000/firebase
        at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1055:39)
        at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:424:31)
        at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:191:47)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:486:38)
    Error loading http://localhost:3000/firebase as "firebase" from http://localhost:3000/app/app.component.js
        at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1055:39)
        at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:424:31)
        at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:191:47)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:486:38)
    Error loading http://localhost:3000/firebase as "firebase" from http://localhost:3000/app/app.component.js
(anonymous) @ localhost/:28
```

**Expected behavior**

App should load with Firebase code in place.

**Minimal reproduction of the problem with instructions**

See above for steps taken prior to bug occurrence. I am not aware of any way to recreate npm installs via Plunker.

**What is the motivation / use case for changing the behavior?**

I would like to be able to use npm installed Firebase with my Angular4 app.

**Please tell us about your environment:**

Ubuntu 16.04, Atom, npm, ng serve.

* **Angular version:** 2.0.X

4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.1.0

* **Node (for AoT issues):** `node --version` =   

6.9.1

**Comment by PeterDavidCarter** [comment]
This issue appears to be caused by using the Angular Quickstart instead of the angular-cli to generate a project.

**Comment by gkalpak** [comment]
You need to tell SystemJS where to find `firebase`. E.g. adding an entry to the SystemJS config's [`map` property][1].

[1]: https://github.com/angular/quickstart/blob/87ad8f5769c52a623b8e7df679b3960f2aa50e63/src/systemjs.config.js#L12-L29

**Comment by PeterDavidCarter** [comment]
I feel like it might be useful to have this in either the Firebase or Angular documentation if it's not already, as it's caused me some head scratching (though in the end I'm happy I moved the app to the cli anyway).

**Comment by gkalpak** [comment]
Closing since this doesn't fall into the bug report or feature request category, which this issue tracker is suitable for. If you still can't make it work or for future support requests, please post your issues on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

<sub>(If you are wondering why we don't resolve support issues via the issue tracker, [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).)</sub>

**Comment by gkalpak** [comment]
This isn't something specific to Angular or Firebase. It is how SystemJS works (and would require similar handling for any new npm package you want to import, with or without Angular).

BTW, if you plan to use Firebase with Angular, you might want to checkout the [angularfire2][1] project.

[1]: https://github.com/angular/angularfire2/blob/master/README.md

**Comment by PeterDavidCarter** [comment]
Yeah, I had a look at it. At present it seems to be giving some fairly worrying red errors when you install it with the current version of Firebase but I've been told it works fine and looks really useful.

Btw, I know this section is more for function things, but I'm really impressed with how the framework is coming along of late and a few issues with jQueryUI notwithstanding, I'm really happy I moved from Rails.
