### ISSUE TITLE
ngFor last:child pseudo-class not working if there is another element

### ISSUE THREAD

**Issue by omrirz** [angular/angular#17175]
sorry

**Comment by skreborn** [comment]
This is not a bug, and it is unrelated to Angular anyway. This is how CSS works by specification, this is correct behavior. If you would like `:last-child` to work consistently, you need to wrap the elements into a container.

**Comment by tytskyi** [comment]
@omrirz if you want custom css class on last item of ngFor's output use

```html
<div *ngFor="let item of itemList; let isLast = last;" class="border" [class.my-last]="isLast">
  {{ item }}
</div>
```

```css
.border.my-last { border-top: 1px solid red}
```

Where last is implicit local variable of directive. Full list of implicit variables you can find here: https://angular.io/docs/ts/latest/api/common/index/NgForOf-directive.html
