### ISSUE TITLE
Animations: animating from current style on state change regression

### ISSUE THREAD

**Issue by dharders** [angular/angular#17170]
**I'm submitting a ...**  
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**

Changing animation state, mid-flight of another animation, causes the new animation to play from the beginning and not from the current mid-flight style.

**Expected behavior**

On state change, animate from **currently applied** styles/position if we haven't explicitly set a starting style for the transition.

**Minimal reproduction of the problem with instructions**

Plunker with instructions (also see working behavior in 4.2.0-beta.1) 
[https://plnkr.co/edit/yLUWhK?p=preview](https://plnkr.co/edit/yLUWhK?p=preview)

**What is the motivation / use case for changing the behavior?**

Better user experience, smoother animations, restore behavior of 4.2.0-beta.1

**Please tell us about your environment:**

Windows 7, code, yarn, ng cli

* **Angular version:** 4.2.0-rc.2

* **Browser:** 

Tested in Chrome Desktop  58.0.3029.110 (64-bit), iOS Safari 10.2.1
 
* **Language:** Typescript 2.3.4

* **Node (for AoT issues):** `node --version` =   

/cc @matsko

**Comment by dharders** [comment]
Updated plunker to 4.2.3 release:  [https://plnkr.co/edit/yLUWhK?p=preview](https://plnkr.co/edit/yLUWhK?p=preview)

**Comment by dharders** [comment]
Updated plunker to 4.2.4 release: [https://plnkr.co/edit/yLUWhK?p=preview](https://plnkr.co/edit/yLUWhK?p=preview)

/ @matsko

**Comment by dharders** [comment]
Is this regression likely to be fixed soon? I'd prefer not to have to change our large code base to work around it.

It was marked **severity5: regression**, but there has been several releases since. I assumed regressions were a priority for a stable branch. Don't get me wrong, I love Angular and the new Animations module and understand bugs can easily creep in, but confidence in the turn around time of fixes for future production code is worrisome for management. 

Issue still present on latest 4.2.5 release.

Updated plunker: [https://plnkr.co/edit/yLUWhK?p=preview](https://plnkr.co/edit/yLUWhK?p=preview)



/cc @matsko

**Comment by matsko** [comment]
Yes I am working towards it. It has been in the way of few other regressions that just landed in 4.2.5. 
I think that once this one lands then it may fix most of the problem #17856. Once that goes in (I think tomorrow), then you should be able use angular@head and see if it solves the problem.

**Comment by dharders** [comment]
Updated plunker: [https://plnkr.co/edit/yLUWhK?p=preview](https://plnkr.co/edit/yLUWhK?p=preview) to latest 4.3.0-rc.0 release. Issue still present

/cc @matsko

**Comment by dharders** [comment]
Updated  [plunker](https://plnkr.co/edit/yLUWhK?p=preview) to latest 4.3.0 release. Regression still present

**Comment by matsko** [comment]
Alright @dharders I believe I fixed the issue here in this PR: https://github.com/angular/angular/pull/18172

**Comment by matsko** [comment]
Thank you for being persistent with this.

**Comment by dharders** [comment]
Thanks @matsko!

Is there any way to test your PR from the above plunker ? (i.e. does Travis CI generate a build link etc) or do I have to wait until it is merged then link to nightly `@angular/animations-builds` ?

Thanks again, appreciate all your work !

**Comment by matsko** [comment]
I pushed a branch into the builds code so you can test against it:

Use (inside of package.json):

```
"@angular/animations": "git://github.com/angular/animations-builds.git#animation_issue_17170",
"@angular/platform-browser": "git://github.com/angular/platform-browser-builds.git#animation_issue_17170",
```

**Comment by dharders** [comment]
Works perfect. Thanks again!
