### ISSUE TITLE
Is [providers] necessary when doing constructor dependency injection?

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#17182]
Going through [this todo tutorial]() and it has the following:
 
    import {TodoDataService} from './todo-data.service';

    @Component({
     // ...
      providers: [TodoDataService]
    })

     constructor(private todoDataService: TodoDataService) {
     }

IIUC we have to declare the `TodoDataService` in the `providers` array.  Could the Angular DI just read the metadata and the constructor correspondingly and see that this component needs a `TodoDataService`?  The providers array seems redundant ...?

**Comment by uber5001** [comment]
Please ask this on StackOverflow.

from angular/CONTRIBUTING.md:

>Got a Question or Problem?

>Please, do not open issues for the general support questions as we want to keep GitHub issues for bug reports and feature requests. You've got much better chances of getting your question answered on StackOverflow where the questions should be tagged with tag angular.

**Comment by oleersoy** [comment]
Thanks for the heads up.  Posted:

https://stackoverflow.com/questions/44336319/is-providers-necessary-when-doing-constructor-dependency-injection

Spring made this automatic in 4.3:
https://spring.io/blog/2016/03/04/core-container-refinements-in-spring-framework-4-3

**Comment by gkalpak** [comment]
@uber5001, is right. This is not the right place for this kind of questions.

The short answer is that you don't have to specify it if something higher up the injector chain already provides it, but providing it changes the behavior (e.g. creates a new instance of the service on that components injector, instead of sharing any instances created higher up the injector tree.
You can read more about Angular's dependency injection [here][1] and [there][2].

[1]: https://angular.io/docs/ts/latest/guide/dependency-injection.html
[2]: https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html

**Comment by oleersoy** [comment]
It seems like Angular would be simpler if the default behavior was to automatically constructor inject singletons (The way Spring does)?  In other words allow for further configuration, but automatically perform what developers will most likely do 99% of the time automatically.

If Angular already does this, then I don't think this is the place for that type of question, but if it does not, then I think it's OK to keep this issue open ...

**Comment by gkalpak** [comment]
I am not 100% sure I understand what you are talking about, but I think it does what you want. I strongly suggest reading up on how Dependency Injection works in Angular, since it is an important part of the framework.

**Comment by oleersoy** [comment]
Right now if a component needs a `HeroService` somewhere in angular's configuration (Either in component decorator's) provider array or at the component's module level we have to declare a providers array.

Spring used to do this as well via the @Autowired annotation.  The main point is that they realized that 99.999% of the time this is redundant, and eliminated it.  Now if spring sees a constructor like this:

       constructor(private todoDataService: TodoDataService) {
       }

You don't have to tell Spring anywhere that it needs to create a `todoDataService` singleton.  I just does it automatically.

**Comment by oleersoy** [comment]
If we can make this simplification happen it will make angular much friendlier.

**Comment by oleersoy** [comment]
This is actually a feature request.  

If we have a service and a component defined, and the component constructor injects the service then have the default for angular be that the service gets automatically injected without any further configuration necessary.

**Comment by uber5001** [comment]
I'd recommend making a new issue if you want this to be a feature request, and follow the [contributing guidelines for issues](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#issue), and using the [issue template](https://raw.githubusercontent.com/angular/angular/master/.github/ISSUE_TEMPLATE.md).

**Comment by oleersoy** [comment]
https://github.com/angular/angular/issues/17188
