### ISSUE TITLE
Sidenav in material component library is broken

### ISSUE THREAD

**Issue by buffet-time** [angular/angular#17187]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://material.angular.io/components/component/sidenav 
example is broken in documentation

**Expected behavior**
for it to work

**Minimal reproduction of the problem with instructions**
https://material.angular.io/components/component/sidenav

**What is the motivation / use case for changing the behavior?**
https://material.angular.io/components/component/sidenav

**Please tell us about your environment:**
Chrome 64 bit latest (as of 6/2/17, Windows 10 Enterprise 64bit

* **Angular version:** 2.0.X
https://material.angular.io/components/component/sidenav

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jotatoledo** [comment]
this issue should be on the issue tracker of the material repo in my opinion

**Comment by pkozlowski-opensource** [comment]
Please open in https://github.com/angular/material2
