### ISSUE TITLE
Router lazy-loading loads unwanted code for parent path nodes

### ISSUE THREAD

**Issue by bourey** [angular/angular#17183]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Imagine a route configuration like:
```ts
{ path: 'foo', children: [
  { path: '', loadChildren: 'foo_module' },
  { path: 'bar', loadChildren 'bar_module' },
]}
```

If the user navigates directly to /foo/bar/baz, the router will lazy-load UI modules for baz (the page actually under view), but will also lazy-load UI modules for /foo.  This becomes more pathological as the number of path segments grows, and can cause performance issues as un-needed code is downloaded to the browser, and unused route resolves are performed.

**Expected behavior**
In the above case, I want to be able to load only the code for the page actually under view. It might make sense to make this behavior configurable, particularly for route resolves.  For example, one might want a path of '/resource/:resourceId/sub/path' to be able to inherit the resource resolver from the parent node. 

**Minimal reproduction of the problem with instructions**
Download https://github.com/bourey/ngupgrade-example/tree/lazy, run npm start, and navigate to http://localhost:3000/teams/1.  Observe that team_list.* code is downloaded as well.

**What is the motivation / use case for changing the behavior?**
Performance.

**Comment by jotatoledo** [comment]
is the behaviour the same if u change the order of the paths? For example:

```
{ path: 'foo', children: [
  { path: 'bar', loadChildren 'bar_module' },
  { path: '', loadChildren: 'foo_module' },
]}
```

**Comment by jasonaden** [comment]
@bourey It appears the following two options fix this issue:

```
{ path: 'foo', children: [
  { path: 'bar', loadChildren 'bar_module' },
  { path: '', loadChildren: 'foo_module' },
]}
```

or

```
{ path: 'foo', children: [
  { path: '', pathMatch: 'full', loadChildren: 'foo_module' },
  { path: 'bar', loadChildren 'bar_module' }
]}
```

I'll close this issue, but let me know if this doesn't work and we can look in more detail at your exact issue.
