### ISSUE TITLE
[platform-server] console.log in certain lifecycle hooks could cause an infinite loop since it results in a microtask on Node.JS (was: ngAfterViewChecked causes infinite loop)

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular#17180]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
Adding `ngAfterViewChecked() { }` (even if blank) to any Component causes infinite loop and server-render timesout.

**Expected behavior**
Let the zone stabilize and render the application.

**Minimal reproduction of the problem with instructions**
This branch here: 
https://github.com/MarkPieszak/ng-universal-demo/tree/ngAfterViewChecked-bug

You can see the only addition was: https://github.com/MarkPieszak/ng-universal-demo/blob/ngAfterViewChecked-bug/src/app/app.component.ts#L24-L26

**What is the motivation / use case for changing the behavior?**
Lifecycle hooks fix.

**Please tell us about your environment:**
This happens in Node/express and also ASP.NET Core/Node

* **Angular version:** 4.x

* **Node (for AoT issues):** `node --version` =  Any version (tested on 6.x, 7.x, 8.0)

cc/ @alxhub @vikerman @gdi2290

**Comment by alexzuza** [comment]
I think the main problem is the following line

`console.log('this will keep appearing in the node console!');`

Server side generates new microtask after it. It the same as we would write

```
const resolvedPromise = Promise.resolve(null);

@Component({
  selector: 'my-app',
  templateUrl: `./app.component.html`
})
export class AppComponent {
  ngAfterViewChecked() {
    resolvedPromise.then(() => {})
  }
}
```
![reproduction](https://cloud.githubusercontent.com/assets/4223314/26741952/90164e7a-47ec-11e7-990e-a27d99ff339c.gif)

**Comment by gdi2290** [comment]
try replacing the microtask for macrotask in the isStable logic

**Comment by schippie** [comment]
I've been slamming my head in against a wall for 3 whole days before finding that the issue is due to the console.log statement.  @gdi2290 where do I alter the isStable logic?

**Comment by hansl** [comment]
After investigation by Alex and I, we found that Zone hooks up Stream hooks, and `console.log` in Node is basically `process.stdout.write(...)` with `stdout` being a Stream. This results in a Microtask that with it hooks up a change detection... which call the console.log again. Hence the recursion.

We'll be investigating more.

**Comment by hansl** [comment]
This is a Zone issue (rather than change detection one) because any task that would call `console.log` from a begin/end zone hook would also cause this infinite loop.

**Comment by MarkPieszak** [comment]
Saw the same thing, somehow the console is creating another micro task. @hansl 
If you need anything else let me know!

**Comment by JiaLiPassion** [comment]
@hansl , @MarkPieszak , if you want to use `console.log`, please write in this way

```javascript
Zone.root.run(() => {
  console.log(...);
});

```

this will resolve the loop issue.

**Comment by vikerman** [comment]
We need to provide a better way for people to use console.log from server code without going into an infinite loop :)

**Comment by JiaLiPassion** [comment]
@vikerman, I will make a PR to `zone.js` to patch `console.log` and let you review.

**Comment by jamilalisgandarov** [comment]
Same here

**Comment by gdi2290** [comment]
The actionable fix here is to make sure console.log is outside of the angular zone.

Here's how to deal with `ngAfterViewChecked`

```
    const curr = Zone.current;
    const root = (curr.parent || curr);
    root.run(() => console.log('checked'));
```
the problem is that doing anything async within `ngAfterViewChecked` will cause another render with would run `ngAfterViewChecked` again. to get around this is by making sure you don't cause another render until you need to.
```typescript
ngAfterViewChecked() {
   const currentZone = Zone.current;
   const rootZone = (rootZone.parent || currentZone);
  if (!this.alreadyDidAsyncWork) {
      // don't trigger change-detection
      rootZone.run(() => {
        // do async work
        /*
        xhr.get().then((data) => {
           // make sure to trigger change-detection if you need to
           currentZone.run(() => {
             this.data = data;
             this.alreadyDidAsyncWork = true;
           })

        })
        */
      })
  }
}
```

It's also really important to know that you most likely want to use `ngAfterViewInit` rather than `ngAfterViewChecked`. Anything you do within `ngAfterViewChecked` will most likely be a hacky side-effect and should be avoided. If you do use this you need to be aware of everything that's going on and will likely have a lot of if-statements to see if you're in a change detection loop

**Comment by vikerman** [comment]
https://github.com/angular/zone.js/pull/855 should fix this
