### ISSUE TITLE
async test zone: fixture.whenStable supports click + onreadystatechange but not click + onload

### ISSUE THREAD

**Issue by taavo** [angular/angular#17192]
**Summary**
In an async test zone, when a component triggers an XmlHttpRequest through a click, fixture.whenStable works as expected with the XmlHttpRequest#onreadystatechange event but not XmlHttpRequest#onload event. 

Notably this means that HttpModule doesn't work as expected with async test zones.

See plnkr: http://plnkr.co/edit/9l8LwcFIovV5JONv0M7d?p=preview

**Current behavior**
With onreadystatechange, the event indicating that the response has been received is fired before fixture.whenStable, so I'm then able to make assertions based on the behavior of the event handler.

With onload, the event indicating that the response has been received is fired _after_ fixture.whenStable, so I'm unable to make assertions based on the behavior of the event handler. 

This is most obvious when looking at the console.log statements in the plnkr. We see 1. click, 3. whenStable, 2. xhr event handler, instead of 1. click, 2. xhr eventhandler, 3. whenStable. 

**Expected behavior**
I expect the XmlHttpRequest onload behavior to be the same as onreadystatechange; fixture.whenStable should let me make assertions around the behavior of the event handler. 

**Minimal reproduction of the problem with instructions**
Steps to reproduce: http://plnkr.co/edit/9l8LwcFIovV5JONv0M7d?p=preview

Note that it's apparently relevant that the XmlHttpRequest is triggered by a click. If the XmlHttpRequest fires as part of the constructor the correct behavior is observed. I can also produce the correct behavior by triggering the click inside a separate async test zone in a beforeEach, but I don't know zonejs well enough to know if that means anything..

**What is the motivation / use case for changing the behavior?**
I want to use the HttpModule to occasionally make real requests during component testing.

**Please tell us about your environment:**
Tested on a Mac using Chrome 58.

* **Angular version:** 4.0.0 and 4.1.3.

**Comment by taavo** [comment]
Update: For people looking for a workaround, `Observable.ajax()` [uses onreadystatechange](https://github.com/ReactiveX/rxjs/blob/master/src/observable/dom/AjaxObservable.ts#L372). It works as expected and is probably already in your dependencies. I've updated the plnkr.

**Comment by JiaLiPassion** [comment]
@taavo , I can make a PR in `zone.js` to let `onload` work as expected. I will check it later.
