### ISSUE TITLE
import jquery.min.js using angular cli.json

### ISSUE THREAD

**Issue by smartweb2017** [angular/angular#17208]
I added some min.js into angular cli json file like this:
"styles": [
        "styles.css",
        "../node_modules/font-awesome/scss/font-awesome.scss"

      ],
      "scripts": [
        "assets/js/custom.js",
        "assets/js/index-2.js",
        "assets/plugins/chartjs/Chart.min.js",
        "assets/plugins/jquery/jquery.min.js",
        "assets/plugins/metis-menu/metisMenu.min.js",
        "assets/plugins/bootstrap/js/bootstrap.min.js",
        "assets/plugins/slim-scroll/jquery.slimscroll.min.js",        
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/sortablejs/Sortable.js",
        "../node_modules/chart.js/dist/Chart.bundle.min.js",
        "../node_modules/easy-pie-chart/dist/easypiechart.js"

      ],

But i can see follow  errors when run "ng serve " command

WARNING in ./~/raw-loader!./~/source-map-loader!./src/assets/plugins/metis-menu/metisMenu.min.js
Cannot find SourceMap 'metisMenu.js.map': Error: Can't resolve './metisMenu.js.map' in 'C:\train\ccportal\client\src\assets\plugins\metis-menu'
 @ ./~/script-loader!./src/assets/plugins/metis-menu/metisMenu.min.js 1:84-311
 @ multi script-loader!./src/assets/js/custom.js script-loader!./src/assets/js/index-2.js script-loader!./src/assets/plugins/chartjs/Chart.min.js script-loader!./src/assets/plugins/jquery/jquery.min.js script-loader!./src/assets/plugins/metis-menu/metisMenu.min.js script-loader!./src/assets/plugins/bootstrap/js/bootstrap.min.js script-loader!./src/assets/plugins/slim-scroll/jquery.slimscroll.min.js script-loader!./~/jquery/dist/jquery.min.js script-loader!./~/sortablejs/Sortable.js script-loader!./~/chart.js/dist/Chart.bundle.min.js script-loader!./~/easy-pie-chart/dist/easypiechart.js

WARNING in ./~/raw-loader!./~/source-map-loader!./src/assets/plugins/jquery/jquery.min.js
Cannot find SourceMap 'jquery.min.map': Error: Can't resolve './jquery.min.map' in 'C:\train\ccportal\client\src\assets\plugins\jquery'
 @ ./~/script-loader!./src/assets/plugins/jquery/jquery.min.js 1:84-304
 @ multi script-loader!./src/assets/js/custom.js script-loader!./src/assets/js/index-2.js script-loader!./src/assets/plugins/chartjs/Chart.min.js script-loader!./src/assets/plugins/jquery/jquery.min.js script-loader!./src/assets/plugins/metis-menu/metisMenu.min.js script-loader!./src/assets/plugins/bootstrap/js/bootstrap.min.js script-loader!./src/assets/plugins/slim-scroll/jquery.slimscroll.min.js script-loader!./~/jquery/dist/jquery.min.js script-loader!./~/sortablejs/Sortable.js script-loader!./~/chart.js/dist/Chart.bundle.min.js script-loader!./~/easy-pie-chart/dist/easypiechart.js
webpack: Compiled with warnings.

How to fix it?????

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
