### ISSUE TITLE
min and max directives should accept decimal values, not just integers

### ISSUE THREAD

**Issue by jnizet** [angular/angular#17203]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The min and max directives allowing to validate that an input has a min or max value only accept an integer value (the attribute value is parsed as an int, using `parseInt()`).

**Expected behavior**

I would expect them to accept any number, including decimal numbers. I can imagine scientific or math-oriented applications where a number should be, lets' say, between 0.4 and 0.6.

**Minimal reproduction of the problem with instructions**

No reproduction, but the code source is pretty clear: https://github.com/angular/angular/blob/master/packages/forms/src/directives/validators.ts#L133

**What is the motivation / use case for changing the behavior?**

Sometimes, decimal numbers must be entered in a form. A decimal number is properly validated against a min or max value, but the min and max value must be integers, which seems like an unnecessary restriction. 

**Please tell us about your environment:**

* **Angular version:** 4.2.0-RC2

* **Browser:** all

 
* **Language:** all

**Comment by tytskyi** [comment]
@jnizet thank you, and this is a duplication of https://github.com/angular/angular/issues/17080 and there is the fix pending PR https://github.com/angular/angular/pull/17085

**Comment by jnizet** [comment]
@tytskyi Oh, sorry. I swear I searched before submitting :-(

**Comment by vicb** [comment]
Closing as duplicate
