### ISSUE TITLE
docs: DoCheck API documentation has incorrect information

### ISSUE THREAD

**Issue by mertdeg** [angular/angular#17206]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1. Go to https://no-shadow-angular-io.firebaseapp.com/docs/ts/latest/api/core/DoCheck-interface.html
2. Read the part that says "Note that a directive should not implement both DoCheck and OnChanges at the same time. ngOnChanges would not be called when a directive implements DoCheck."

**Expected behavior**
When OnChanges and OnInit is both implemented, Angular will call both of these APIs.

**What is the motivation / use case for changing the behavior?**
To have documentation match the actual behavior of Angular.

**Please tell us about your environment:**
Linux, Chrome

* **Angular version:**
any

* **Browser:** 
all
 
* **Language:*
all

**Comment by siddhant1** [comment]
Is anyone working on this one?

**Comment by petebacondarwin** [comment]
This was actually resolved by https://github.com/angular/angular/pull/8807
