### ISSUE TITLE
aio: content container should expand when TOC not present

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17205]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Content container (md-sidenav-container.sidenav-container) does not expand beyond 82% when TOC is not present which creates extra unwanted white space.

**Expected behavior**
Content container should dynamically expand if TOC is not present.

**Comment by petebacondarwin** [comment]
This is a bit tricky now since the AppComponent no longer has any knowledge of whether there is a TOC or not. I'll take a look and see what can be done.

**Comment by gkalpak** [comment]
Ooops, I have been working on this, but forgot to assign it to me. I have a PR almost ready.

**Comment by petebacondarwin** [comment]
OK, I'll leave it alone then.
