### ISSUE TITLE
Date pipe not work well in costum format without day

### ISSUE THREAD

**Issue by BtShp** [angular/angular#17200]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
in date pipe, format of  "MM/y" or "MM/yyyy" ,
part of the dates with month 10- display like 9:
Ex: 

**Expected behavior**
get the right date...

**Minimal reproduction of the problem with instructions**

in date 01/10/2012, instead of getting 10/2012 ,Im getting 09/2012. instead of 10/2007, Im getting 09/2007. 
in date 10/14 for example it display well...

**What is the motivation / use case for changing the behavior?**
Im using this format alot..

**Please tell us about your environment:**
 HTTP server,

* **Angular version:** 2.0.X
2.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 58.0.3029.110
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3
* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment]
Could you please provide a reproduce scenario in a plunker? We really need one to move forward: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue

**Comment by BtShp** [comment]
Its so simple-
I have List Of dates objects with Date type,
in chrome console it look like 
"2008-11-01T00:00:00"
"2007-10-01T00:00:00"
Im using the pipe in html:
```
 <select id="IndexSelect" class="drop-down-form-control indexselect" [(ngModel)]="revalueModel.acctualIndexDate.AccuIndexValue">
                                        <option [ngValue]="index.AccuIndexValue" *ngFor="let index of indexDates">{{index.IndexDate | date: 'MM/yyyy' }}</option>
</select>
```
when im using format of 'dd/MM/yyyy'' it works well.
Just in 'MM/yyyy' fromat the problem reproduce.
if you still nees reproduce  in plunker pleese tell me.

**Comment by ocombe** [comment]
Yes please, there are a lot of issues that we have to treat, if you take the time to make a plunkr it will be much faster for us to validate the bug

**Comment by BtShp** [comment]
[https://plnkr.co/edit/Ayc8cZGYnJgJE6rJ4j07?p=preview]

**Comment by BtShp** [comment]
https://plnkr.co/edit/Ayc8cZGYnJgJE6rJ4j07?p=preview

**Comment by trotyl** [comment]
Cannot reproduce here (+08:00), seems to be timezone problem. It's better to specify your timezone or `Z` in the ISO format.

**Comment by ocombe** [comment]
It shows 09/2007 for you? It works ok for me, I'm seeing 10/2007
![image](https://user-images.githubusercontent.com/265378/27278485-d5f6e0ce-54e1-11e7-9537-0ba0f3a219fb.png)

This seems like a time zone problem for me

**Comment by BtShp** [comment]
Im seeing 9/2007
![image](https://user-images.githubusercontent.com/23717698/27281448-935961c0-54f4-11e7-98e3-17b391733430.png)

My timezone is GMT+0300

**Comment by BtShp** [comment]
Can I do something with that?

**Comment by ocombe** [comment]
Not yet, but the PR to replace the intl API for angular v5 (see [#10809](https://github.com/angular/angular/issues/10809)) will add a new option to the date pipe that will let you specify the timezone.
