### ISSUE TITLE
aio: animate hamburger menu on docs page

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17215]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Topnav menu changes (hamburger menu displaying) is abrupt compared to the sidenav slide out animation on the initial arrival on the docs page.

**Expected behavior**
Add smoother transition for hamburger icon.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
From home page go to docs page. See how hamburger menu and sidenav transition into the page.

**Comment by gkalpak** [comment]
@sjtrimble, I don't know what kind of animation would look nice on the hamburger, but this is a start: #17335 :smiley:
