### ISSUE TITLE
aio: topnav item focus and active not working properly

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17216]
Reference: https://github.com/angular/angular/issues/16097

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Focus jumps to 'DOCS' nav-item in topnav toolbar instead of active item. Only happens if you click on 'DOCS' and then any other topnav item.

**Expected behavior**
Focus should stay on the relevant active item instead of jumping back to docs regardless of what page you are on.

**Minimal reproduction of the problem with instructions**

- navigate to https://aio-staging.firebaseapp.com/ and add focus style (or navigate to https://pr17155-1ebe8d4a5829628ccf005d60c21a0f4a678b1738.ngbuilds.io/)
- click on the "Docs" menu item in the header
- click on the "Features" menu item

**Comment by gkalpak** [comment]
For reference, the underlying `@angular/material` issue has been fixed on master (angular/material2@3bc82f6dc). We need to wait for it to be released and upgrade.

**Comment by gkalpak** [comment]
Should we temporarily remove the focus styling until a new version of material is released?

**Comment by sjtrimble** [comment]
@gkalpak that is what we had originally done - up to @IgorMinar

**Comment by gkalpak** [comment]
We decided to temporarily remove the focus style until we can upgrade to amterial version that includes https://github.com/angular/material2/commit/3bc82f6dc (hopefully in a couple of days).
