### ISSUE TITLE
clicking on H1 in the TOC should scroll all the way to the top

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17226]
Clicking on H1 doesn't scroll high enough.

Right now we don't show the header, and once #17155 is merged (which makes the header sticky), we scroll just high enough to leave the H1 under the header.

<img width="1912" alt="screen shot 2017-06-05 at 11 40 07 pm" src="https://cloud.githubusercontent.com/assets/216296/26816790/59e25b60-4a48-11e7-8372-1da67664d98a.png">

**Comment by gkalpak** [comment]
This is supposed to be fixed by #17123 (although there still seems to be a tiny offset), but will probably require a new/different fix with the new header layout (#17155).
