### ISSUE TITLE
Bug(animations): Animating Translation does not work in IE 11 / Edge with percentages

### ISSUE THREAD

**Issue by macjohnny** [angular/angular#17239]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 
[ ] feature request
[ ] support request 
```

**Current behavior**
In IE 11 / Edge, when using the animations API for translating an element, the transition is not animated.
```
@Component({
  selector: 'my-app',
  templateUrl: 'src/app.html',
  animations: [
    trigger('translate', [
            state('center', style({transform: 'translate3d(0, 0, 0)'})),
            state('right', style({transform: 'translate3d(100%, 0, 0)'})),
            transition('center => right, right => center',
                animate('900ms ease'))
        ])
    ]
})
```

**Expected behavior**
The translation should be animated smoothly.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/AnLKIlfuz5S6siBZQTIY?p=preview

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.4.0 - 4.2.0-rc.2

* **Browser:** IE 11 / Edge
 
* **Language:** Typescript@2.2.2

**Comment by macjohnny** [comment]
@matsko sorry to bother you again, but could you have a look at this one too?
It is also important for angular material 2, e.g. tabs, etc. see https://github.com/angular/material2/issues/4982

**Comment by macjohnny** [comment]
interestingly, the animation works by double-clicking the toggle-button, i.e. starting the second animation before the first one completes. This means that the animation with translate3d could work in principle, but indeed this issue is a bug.

it does not work when using transitions instead of states either:
https://plnkr.co/edit/7w6BAW4OHeoeKnPljqRj?p=preview

it does work when using keyframes:
https://plnkr.co/edit/6J23FdWPI9Yd3LIWaONT?p=preview

*it does work when using absolute pixel values instead of percentages*:
https://plnkr.co/edit/zM42EuUtGBkmAj7HoAXJ?p=preview

**Comment by macjohnny** [comment]
Seems to be related to the web-animations-js polyfill. See the issue here:
https://github.com/web-animations/web-animations-js/issues/142
and the example here:
https://jsfiddle.net/fu7mrqn0/8/

**Comment by macjohnny** [comment]
Here is a workaround: using translate3d(0%,0,0) instead of translate3d(0,0,0) apparently fixes the problem, see this example: https://plnkr.co/edit/1Ffduxu1N3PJKgHutRuw?p=preview

However, I think this should be fixed in web-animations-js, since translating from translate3d(0,0,0) to translate3d(100px,0,0) works, whereas translating from translate3d(0,0,0) to translate3d(100%,0,0) does not.

**Comment by macjohnny** [comment]
One Problem still remains with Angular animations / IE11: When quickly toggling the animation states by clicking the button in https://jsfiddle.net/5bhbq4ao/ , the box jumps to 100% or 0% translation respectively to start the subsequent animation, whereas in chrome / firefox, the animation smoothly changes direction at the current position without jumping around. 

I believe this is / should be solved in the angular animations API, since the following example https://jsfiddle.net/pafkoa0k/ also jumps around in both, chrome and IE 11, while https://jsfiddle.net/5bhbq4ao/ does work smoothly in chrome, but jumps in IE 11.
@matsko could you have a look at that?

**Comment by matsko** [comment]
I see that Safari is also broken. I'm looking into it.

**Comment by macjohnny** [comment]
@matsko Thanks for the quick response! Your effort is just awesome :-)
What I can observe in my safari is that hitting the toggle button in https://plnkr.co/edit/1Ffduxu1N3PJKgHutRuw?p=preview repeatedly, the animation will eventually jump to the final target state. In chrome, it works like a charm.

**Comment by macjohnny** [comment]
Seems to remain an issue with 4.2.2:
https://plnkr.co/edit/U5gWbH?p=preview

**Comment by matsko** [comment]
This happens to be an issue with the web-animations polyfill. Using a matrix value together with a non-matrix value causes an issue:
https://github.com/web-animations/web-animations-js/issues/144

What's going on here is that when the animation is cancelled then the current value is snapshotted from the element (which ends up being a CSS transform matrix) and then the destination value (which is a regular CSS transform translate3d value) ends up being the final keyframe in the animation. This mix causes the polyfill to mess up.

**Comment by matsko** [comment]
For now you can use CSS matrix values for each state if you want to get away with the cancellation of transform styles working with the polyfill. Hopefully these guys can fix the polyfill soon.

**Comment by macjohnny** [comment]
@matsko thanks a lot for having a look at this and providing a suitable solution! 
so we are left with two open issues in web-animations-js:
web-animations/web-animations-js#142
web-animations/web-animations-js#144

I close this issue, since the angular-related parts seem to work fine.
