### ISSUE TITLE
*ngFor unable to detect changes in string array after execution of ngOnDestroy() in child component

### ISSUE THREAD

**Issue by immanojverma2010** [angular/angular#17237]
I don't know why logs i.e string array is not printing it's value "on Destroy--child" in list item `<li *ngFor="let log of logs"><code>{{ log }}</code></li>` and the same string array prints correctly "On Destroy--child" in `{{ logs.join(', ') }}`.
 <br> That means value is inserted in array, what is the reason it's not printing??<br><br>plz explain, i am totally confused. 

<br>
link for same example: http://plnkr.co/edit/kBHV6AximaHAC26kYEOA?p=gitter 
<br>open this link and run it.

**app.component.ts**

    import { Component, OnInit } from '@angular/core';
    
    @Component({
    	selector: 'app-root',
    	template: `
    	  <h5>Lifecycle Events Log</h5>
    	  {{ logs.join(', ') }}
    	  
    	  <ul>
    	    <li *ngFor="let log of logs">
    	      <code>{{ log }}</code>
    	    </li>
    	  </ul>
    	  
      	  
    	  <app-child 
    	    *ngIf="showChild" 
    	    [name]="name"
    	    (log)="onLog($event)">
    	  </app-child>
    	`
    })
    export class AppComponent implements OnInit {
      name = 'Alice';
      logs: string[] = [];
      showChild = true;
      
      ngOnInit() {
        setTimeout(() => this.updateName(), 3000);
        setTimeout(() => this.hideChild(), 4000);
      }
      
      updateName() {
        this.name = 'Bob';
      }
      
      hideChild() {
        this.showChild = false;
        this.logs.push(`onDestroy--app`);
      }
      
      onLog(data) {
        this.logs.push(data);
      }
      
    }

**child.component.ts**

    import {
      Component,
      Input,
      Output,
      SimpleChange,
      OnChanges, 
      OnInit,
      DoCheck,
      AfterContentInit,
      AfterContentChecked,
      AfterViewInit,
      AfterViewChecked,
      OnDestroy,
      EventEmitter
    } from '@angular/core';
    
    @Component({
    	selector: 'app-child',
    	template: `
    	  <div>
    	    <h4>Child Component</h4>
    	    <p>{{ name }}</p>
        </div>
    	`,
    	styles: [`
    	  :host > div {
    	    border: 2px solid blue;
    	    padding: 0.5rem 1rem;
    	    margin-top: 4rem;
    	  }
    	`]
    })
    export class ChildComponent implements OnChanges, OnInit, DoCheck, AfterContentInit,
      AfterContentChecked, AfterViewInit, AfterViewChecked, OnDestroy {
      
      @Input() name = '';
    
      @Output() log = new EventEmitter<string>();
    
      _verb = 'set';
      _onChangesCounter: number = 0;
      
      // Only called if there is an [input] variable set by parent.
      ngOnChanges(changes: { [propertyName: string]: SimpleChange }) {
        let changesMsgs: string[] = [];
    
        for (let propName in changes) {
          if (propName === 'name') {
            let name = changes['name'].currentValue;
            changesMsgs.push(`name ${this._verb} to "${name}"`);
          } else {
            changesMsgs.push(propName + ' ' + this._verb);
          }
        }
        this.log.emit(`onChanges (${this._onChangesCounter++}): ${changesMsgs.join('; ')}`);
        this._verb = 'changed';
      }
    
      ngOnInit() {
        this.log.emit(`onInit`);
      }
      
      ngDoCheck() {
        this.log.emit(`doCheck`);
      }
    
      ngAfterContentInit() {
        this.log.emit(`afterContentInit`);
      }
    
      ngAfterContentChecked() {
        this.log.emit('afterContentChecked');
      }
    
      ngAfterViewInit() {
        this.log.emit(`afterViewInit`);
      }
    
      ngAfterViewChecked() {
        this.log.emit(`afterViewChecked`);
      }
    
      ngOnDestroy() {
        this.log.emit(`onDestroy--child`);
      }
    }

**Output:**
after all the methods executed

    onChanges (0): name set to "Alice", onInit, doCheck, afterContentInit, afterContentChecked, afterViewInit, afterViewChecked, doCheck, afterContentChecked, afterViewChecked, onChanges (1): name changed to "Bob", doCheck, afterContentChecked, afterViewChecked, onDestroy--app, onDestroy--child

    onChanges (0): name set to "Alice"
    onInit
    doCheck
    afterContentInit
    afterContentChecked
    afterViewInit
    afterViewChecked
    doCheck
    afterContentChecked
    afterViewChecked
    onChanges (1): name changed to "Bob"
    doCheck
    afterContentChecked
    afterViewChecked
    onDestroy--app

**Comment by chuckjaz** [comment]
@immanojverma2010 Can you attach a plunker link to reproduce this with steps to use the plunker?

**Comment by chuckjaz** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).
