### ISSUE TITLE
Search results contain odd ellipses in the middle of the result list

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17233]
<img width="1906" alt="screen shot 2017-06-05 at 11 56 24 pm" src="https://cloud.githubusercontent.com/assets/216296/26817266/c0a3d610-4a4a-11e7-85b1-fa4addfcd356.png">

**Comment by petebacondarwin** [comment]
These are to separate the "top results" from the alphabetic list below. I can change it so that the top results are bold and get rid of the ellipses?
