### ISSUE TITLE
aio: sidenav menu groups should not close automatically on wide display

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17245]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Sidenav menu group collapses when a user selects a men u item outside of the selected sidenav group menu item.

**Expected behavior**
Sidenav groups should not collapse unless the user collapses a menu item.
Per @IgorMinar 

**Minimal reproduction of the problem with instructions**
In wide mode:
- https://aio-staging.firebaseapp.com/docs
- In sidenav click on Tutorial > Introduction
- Then, in sidenav click Fundamentals > Animations

**Comment by wardbell** [comment]
Let's talk about this. We have gone back and forth on this. In fact, it used to work as this issue requests but then we changed it to its current (original) behavior of closing when the user selects. @IgorMinar may not recall that he participated in that decision.

**Comment by IgorMinar** [comment]
The conclusion from our last discussion was:

- on narrow displays:
  - keep the current behavior (collapse all but currently active container)
- on wide displays:
  - do not automatically collapse non-active containers when a menu item is selected

**Comment by sjtrimble** [comment]
I updated the the issue to reflect the above.
