### ISSUE TITLE
aio: docs to homepage sidenav does not close nicely

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17248]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When going from docs to home with an open sidenav, the sidenav does not close nicely and appears to be on top of the toolbar as it transitions.

**Expected behavior**
Smoother transition.

**Minimal reproduction of the problem with instructions**

- Click on https://aio-staging.firebaseapp.com/docs
- Click on the Angular logo home link

**Comment by gkalpak** [comment]
BTW, the same is true when going from a non-sidenav page to a sidenav page (e.g. home to docs). The sidenav shows immediately while the new doc is being fetched in the background, which doesn't look nice.
