### ISSUE TITLE
Use boolean naming convention for environment property

### ISSUE THREAD

**Issue by DavidFrahm** [angular/angular#17241]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Default generated project has environment variable `production` named without the common boolean convention of prefixing with `is`.

Current default generated code sample:

```
export const environment = {
  production: false
};
```

**Expected behavior**

Prefixing with `is`, like this:

```
export const environment = {
  isProduction: false
};
```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

This well-known and established naming convention, which aids in identification, proper use, and more.

**Please tell us about your environment:**

Any

* **Angular version:** 2.0.X

4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript

* **Node (for AoT issues):** `node --version` =   

N/A

**Comment by hansl** [comment]
This is Angular CLI specific, and has nothing to do with Angular itself (the framework). Could you please file this issue on the CLI repo (http://github.com/angular/angular-cli) so we can have the discussion over there?

Thanks.
