### ISSUE TITLE
aio: table border formats inconsistent

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17256]
Text table borders are inconsistent. The header cells have a separating left border. The body cells do not.

![image](https://user-images.githubusercontent.com/129061/26842294-28ec154c-4aa1-11e7-9e07-4e83dcfba393.png)

**My preference** would be to eliminate the inner border in the headers.

**Comment by IgorMinar** [comment]
I wonder if this is intentional...

**Comment by dylhunn** [comment]
This was fixed at some point in the last 5 years.
