### ISSUE TITLE
Search results should be prioritized by currently selected language

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#17258]
Go to https://angular.io/docs/ts/latest/. We're on the `TypeScript` docs. Go to the search box and type in `Lifecycle Hooks` and notice the first result is for the `JavaScript` version. So by default you end up on the JS docs, which in this case searching for what is likely a highly sought after docs page, you land on a page that says it's not yet available in JavaScript.

Just checking a little more, it appears the JS version always comes before the corresponding TS version.

Ideally only the version for the language you have selected should show up. Or add a toggle switch to also show other versions. But for sure the TS version should be prioritized over the JS version.

**Comment by jasonaden** [comment]
@petebacondarwin @IgorMinar FYI.

**Comment by gkalpak** [comment]
This is obsolete in the new (soon-to-be-released) version of the app (https://aio-staging.firebaseapp.com).
