### ISSUE TITLE
aio: upgrade guide titles are confusing

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17259]
There are two guides under "Upgrading" that address AngularJS -> Angular. They are both valuable but cover different aspects of the effort. 

"AngularJS to Angular" describes how to make the conceptual connections between the two products so that someone who knows AngularJS can better understand the continuities when learning Angular.

"Upgrading from AngularJS" is about the NgUpgrade features.

This issue asks us to
1) Create clearer titles for the docs
2) Make the distinction in purpose more evident in the introductions to those guides.

Step #1 can be done before release.

**Comment by jenniferfell** [comment]
I'm going to close this as resolved. It looks like some improvements were made last year, and we made some other changes with v6. 

https://angular.io/guide/ajs-quick-reference
Nav title: Updating from AngularJS -> AngularJS-Angular Concepts
Page title: AngularJS to Angular Concepts: Quick Reference
"This guide helps you transition from AngularJS to Angular by mapping AngularJS syntax to the equivalent Angular syntax."

https://angular.io/guide/ajs-quick-reference
Nav title: Updating from AngularJS -> Upgrading instructions
Page title: Upgrading from AngularJS to Angular
"This guide describes the built-in tools for efficiently migrating AngularJS projects over to the Angular platform, a piece at a time."
