### ISSUE TITLE
aio: odd formatting of module info on API page

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17254]
While all other text on API pages is left justified, the module/package info is centered within an outline box that is itself too faint to read on many screens:

![image](https://user-images.githubusercontent.com/129061/26841479-76806df6-4a9e-11e7-8bef-bb738d81869d.png)

This seems to be easy to fix before release. Could punt if necessary.

**Comment by sjtrimble** [comment]
@wardbell this was intentional and I don't believe it is a blocker?

@IgorMinar thoughts?

**Comment by petebacondarwin** [comment]
I don't know why this is like this. I assume it was a design decision??
I will put them on separate lines and left align them.

**Comment by sjtrimble** [comment]
@petebacondarwin It was a design decision :( a few only have the one item and it might look off if it's left aligned.

**Comment by petebacondarwin** [comment]
We will remove the link to the source code and left align the module name.
Either @gkalpak  or I will fix it.
