### ISSUE TITLE
aio: sidenav text has too little contrast

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17252]
The doc items are the main culprit as seen in this screen shot

![image](https://user-images.githubusercontent.com/129061/26840860-72be6ce2-4a9c-11e7-907c-b68c314c9ba8.png)

Do we need to consult M Sutton?

**Comment by sjtrimble** [comment]
@wardbell this is a dupe for https://github.com/angular/angular/issues/17218 Can you consolidate into that one?

**Comment by wardbell** [comment]
Closed as dup of #17218
