### ISSUE TITLE
aio: glossary definitions re-format

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17265]
The glossary definitions are currently formatted as subsections in a light blue box with a heavy left blue bar.

![image](https://user-images.githubusercontent.com/129061/26844286-bf2adce0-4aa7-11e7-958f-2618c801cb81.png)

Let's pick something less distracting.

https://aio-staging.firebaseapp.com/guide/glossary

**Comment by sjtrimble** [comment]
I personally think we should remove the styling al together. Any reason the content isn't just stand-alone?
