### ISSUE TITLE
change the name of index.html

### ISSUE THREAD

**Issue by rahnemon2011** [angular/angular#17272]
Hi.
I'm a beginner  in Angular.
I'm using Angular 4 and I want to change the name of index.html to a_admin.html; but unfortunately I get the below error.
Cannot GET /
How can I change this file name in angular 2 or 4.
Thanks in advance.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
