### ISSUE TITLE
ng test errors, what is it really doing?

### ISSUE THREAD

**Issue by megamindbrian** [angular/angular#17273]
I love having a diaspora of CLI tools that I have to use just to get something up and running.
Can you tell me what angular-cli.json does?
Why is it when I run ```ng test``` everything works, until I need to add a plugin and suddenly 10 other plugins are needed?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by megamindbrian** [comment]
Always nice to be reminded that no one cares what I think.  Why don't work
on consolidating build stacks instead of closing tickets?
