### ISSUE TITLE
angular-cli.json documentation is poor

### ISSUE THREAD

**Issue by megamindbrian** [angular/angular#17277]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Utilities provided by angular-cli.json are not elaborated on.

**Expected behavior**
I expect everything that angular-cli.json configured automatically to be widely documented.  It currently is not.

**Minimal reproduction of the problem with instructions**
Check out a boiler-plate project such as Tour of Heroes.  Observe the .angular-cli.json has undocumented behavior.

**What is the motivation / use case for changing the behavior?**
Please document and share what configurations are happening by using .angular-cli.json

**Please tell us about your environment:**
Windows

* **Angular version:** 2.0.X
Angular 4

* **Browser:** 
all

* **Language:** 
TypeScript

* **Node (for AoT issues):** `node --version` =   
v7.7.1

**Comment by ericmartinezr** [comment]
Isn't this what you're looking for https://github.com/angular/angular-cli/wiki/angular-cli ? Anyway, the repo for angular-cli is over here https://github.com/angular/angular-cli

**Comment by megamindbrian** [comment]
Kind of.  I did resubmit, but that page doesn't describe if karma plugins
are automatically configured.  I have a bunch listed in package.json
```
        "karma-cli": "latest",
        "karma-jasmine": "latest",
        "karma-jasmine-html-reporter": "latest",
        "karma-sourcemap-loader": "latest",
        "karma-webpack": "latest",

```
Are all of those automatically loaded in the plugins property?  Is that a
karma feature or an angular-cli feature?  If I add a karma plugin is it
guaranteed to be loaded?  If this document was complete, it should say:
```
karma: {
  these 10 settings are configured based on project settings
}

```

**Comment by megamindbrian** [comment]
http://karma-runner.github.io/1.0/config/plugins.html

Found it here.  Automatically loaded unless you specify.  Doesn't change
that the fact that now we have at least 2 commands to run karma.

**Comment by Foxandxss** [comment]
I saw you opened an issue in the CLI repo. Let's continue there.
