### ISSUE TITLE
html sanitize should keep style attribute

### ISSUE THREAD

**Issue by zq8024** [angular/angular#17284]
html sanitize should keep style attribute.
the html content is generated by html rich editor, it is contain the inline style.

**Comment by hansl** [comment]
Could you follow the template and provide a reproduction, please? Thanks.

**Comment by zq8024** [comment]
we use rich html editor to edit some html, just as CMS, and show it to the end user. when set html style, it is    in the 'style' attribute, so we need to keep "style" attribute

**Comment by zq8024** [comment]
we use rich html editor to edit some html, just as CMS, and show it to the end user. when set html style, it is in the 'style' attribute, so we need to keep "style" attribute
