### ISSUE TITLE
Router - service instances registered multiple times in lazyLoaded module (with different URL) 

### ISSUE THREAD

**Issue by montella1507** [angular/angular#17288]
[x ] bug report 

Versions_
@angular/cli: 1.0.0
node: 7.6.0
os: win32 x64
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/animations: 4.1.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.1

Node: v7.6.0
NPM: 4.0.5
Windows 10

Repro steps.
If you have 1 LazyLoaded Module in multiple Paths, for example:

```
 {
        path: '',
        loadChildren: 'app/dashboard/dashboard.module#DashboardModule'
      },
      {
        path: 'dashboard',
        loadChildren: 'app/dashboard/dashboard.module#DashboardModule'
      }
```

All instances (in our example - all Effects) are instanced 2 times. The uniqueness  or Identity of a Module is propably identified only by PATH

Desired functionality.
The identity of a Module (and his injectables) should not be identified only by PATH.

Comment:
**If we need more than 1 Path for the same module and you won't change this behavior, how to use multiple Path, for the same LazyLoaded Module? It is required, especially if this "module" shoudl be default path - like in my example**

**Comment by jasonaden** [comment]
@montella1507 If I'm understanding your issue correctly, I think you should be using a [Redirect](https://angular.io/api/router/Routes#redirects). That way you could only have one `loadChildren` pointing to a given module.
