### ISSUE TITLE
docs: "server" misspelled in VISUAL STUDIO 2015 QUICKSTART

### ISSUE THREAD

**Issue by AmolST** [angular/angular#17283]
Traverse to below mentioned location and find server is misspelled which is marked in **bold**.
 
VISUAL STUDIO 2015 QUICKSTART
Step 5: Build and run the app
For apps that use routing
You'll most likely get a 404 - Page Not Found response from the **serer** for any address other than / or /index.html.

**Comment by Foxandxss** [comment]
Would you like to create a PR to fix it? The file is at `/aio/content/guide/visual-studio-2015.md`

Cheers.
