### ISSUE TITLE
Dynamically Module Loader

### ISSUE THREAD

**Issue by pedro3900** [angular/angular#17287]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This is not a bug, it is some feature that I don´t know if it is possible, right now when you want to include a module/component, you have to defined it manually when you implement it, at his parent or principal module, how it is normal.
**Expected behavior**
I would like to include modules like plugins. I would like that angular can scan one folder and add modules dynamically, I don know if it is possible with angular core, or with any npm module or custom implementation.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I would like this feature to have a more modular and powerful application.

**Please tell us about your environment:**
* **Angular version:** 2.0.X
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
* **Node (for AoT issues):** `node --version` =

**Comment by chuckjaz** [comment]
This sounds similar to #17267. Does #17267 encompass your suggestion? If not, what is not covered?

**Comment by pedro3900** [comment]
It is not exactly the same my target is for example to have a main component who scan a certain folder and include modules inside this folder. 

I am finding 2 ways:
Do it in execution time dinamically (the idea is to build something like a plugin system, we can add a new module to a folder and this functionality will be include).

The other way is do it in build time, and use something like webpack or gulp to load dinamically modules in certain folders. In this way the scan will be done by webpack or gulp not by angular code.

**Comment by jelbourn** [comment]
Tracking the main underlying concern here in #18093
