### ISSUE TITLE
Http.get not working in angular 4

### ISSUE THREAD

**Issue by saravanans-arch** [angular/angular#17286]
**http api request not working in angular 4, i checked my api server all the things, but the api not triggered, but i tried same api in angular 2, it's working fine.** 
```
import { Component } from '@angular/core';
import {Http} from '@angular/http';
import 'rxjs/add/operator/map'

@Component({
    moduleId: module.id,
    selector: 'app',
    templateUrl: 'app.component.html'
})

export class AppComponent{
    constructor(http:Http) {
        http.get('http://localhost:9970/api/users/list')
            .map(res => {
                console.log(res.json());
            })
            .subscribe(res => {
                console.log(res);
            });
    }
}
```

**Comment by deebloo** [comment]
@saravanans-arch Are you getting an error message? Can you provide a plnkr that reproduces the problem?

**Comment by saravanans-arch** [comment]
@deebloo, Thanks for your reply, No i didn't get any error messages. Every thing run fine. But that single line **"http.get('http://localhost:9970/api/users/list')"** only not triggered.

I was tried with all the solutions from internet. finally i switched to angular v2, There it's working fine. But when I'm using @angular (v4) modules. That time only it's not working.

Sorry it's a huge file source, I can't provide with plnkr. Can you plz tell me above that syntax is correct? Do you face this problem before?

**Comment by deebloo** [comment]
Your map isn't returning anything

**Comment by saravanans-arch** [comment]
@deebloo thanks, I was used jwt authentication in my project that one creating issues. Now i created new project without jwt auth. Now it's working fine, But this experience is too strange and mysteries. Thanks for giving your valuable time.

**Comment by Foxandxss** [comment]
Good to hear that you fixed it.

This kind of questions belong to stackoverflow thought.

**Comment by bcherry007** [comment]
Hi ,

I am facing issue with http api calls in angular 4 . i am not getting any errors but still its keep loading not able hit web api .please help me how can i hit web api calls using http.post request.

My Code IS:
this.http.post('/api/demo/login', body, options)
            .map((response: Response) => {
                // login successful if there's a jwt token in the response
                let user = response.json();
                if (user && user.token) {
                    // store user details and jwt token in local storage to keep user logged in between page refreshes
                    localStorage.setItem('currentUser', JSON.stringify(user));
                }
            });
