### ISSUE TITLE
[Feature Request] Component based router configuration

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#17292]
In the refactoring of the hero app we move from one component that does everything to the AppComponent being the shell that performs routing for sub components.  It would be nice to be able to configure the router within the constructor of the AppComponent eliminating the need for another module file (We don't really need it, but the refactoring suggests moving the routing into a dedicated routing module, and the AppComponent shell feels, based on it's description, like a natural home for this).  

This would also complement the approach suggested in:
https://github.com/angular/angular/issues/17267

**Comment by zoechi** [comment]
I think you should just try to get comfortable with modules. 
The way it works now was built for a reason and it's unlikely to change.
Same with #17267

**Comment by oleersoy** [comment]
As you have probably noticed most frameworks that 'just get comfortable' die quickly.  Developers want the simplest most efficient workflow they can get.  Angular is doing an amazing job.  If these suggestions are infeasible due to some real world technical constraint, then please give me a heads up so that I can research that more.

**Comment by zoechi** [comment]
This topic is about beating a dead horse that was beaten to death ~ a million times.
They had good reasons to build it that way, this is why it currently still this way (they initially tried without modules but later added them as they are now).
Building a powerful framework is about weighing advantages and disadvantages. Just because a number of people want something doesn't mean it can be done without hurting other areas of the framework.

**Comment by oleersoy** [comment]
> This topic is about beating a dead horse that was beaten to death ~ a million times.

Well Polymer did it one million and one times and came up with this:
https://www.polymer-project.org/blog/routing

> They had good reasons to build it that way

And the reasons are?

Right now we are sprinkling some parts of the routing into the module and some parts into the component.  And the two approaches are not mutually exclusive, but one is more DRY and has a better user story than the other.  

> Building a powerful framework is about weighing advantages and disadvantages.

And the disadvantageous are?
