### ISSUE TITLE
dgeni link handling is broken by conversion to .ts

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#1729]
...I think this is as simple as telling dgeni to look in .ts files for changes? commit cb87fa0970f9ecd04212c55d158e4021bc1fc541 breaks doc generation with `gulp docs/angular.io`.

**Comment by petebacondarwin** [comment]
I have pushed a few changes that include the TypeScript source files in the doc-gen but there is a bigger problem:

Dgeni uses Traceur to read in the code from the source files. Unfortunately it doesn't understand some TypeScript syntax, which is causing Traceur to fail to parse some parts of the newly migrated files. For example, the change to use optional parameter syntax in the `Binding` class in the  `angular2/src/di/binding` module:

https://github.com/angular/angular/commit/cb87fa0970f9ecd04212c55d158e4021bc1fc541#diff-000abb35148e2a3ea29809a85fd53ceeR203

The proper solution is to migrate over to using TypeScript Language Services to do this parsing and to drop Traceur altogether. I am not sure how much effort this will be - in any case it would be good if I could pair with someone who knows about those services to make it happen faster.

**Comment by alexeagle** [comment]
I can help, are you still working? Or I can set aside tomorrow morning pacific time.

**Comment by naomiblack** [comment]
@mprobst since Alex is out next week (and you're in a Euro time zone again), could you pair with @petebacondarwin please and figure out if this is going to be a big fix or a small one? We are unable to update API docs until it is resolved.

**Comment by mprobst** [comment]
FYI talked to @petebacondarwin, and apparently there is good progress already being made. On standby now, in case something pops up :-)

**Comment by naomiblack** [comment]
@petebacondarwin any update? Wondering if we can push an API doc update for alpha-23

**Comment by petebacondarwin** [comment]
I have a WIP at #1886.
