### ISSUE TITLE
docs: rethink image in life-cycle guide

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#17298]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This picture on the [life-cycle](https://aio-staging.firebaseapp.com/guide/lifecycle-hooks) page does raise more questions as it answers
![image](https://user-images.githubusercontent.com/1249083/26888598-c2d55b90-4bab-11e7-8935-bc4219ebb57b.png)
I could not find an explanation on what the colors mean, or why certain ones are indented.  This raises more questions as it answers.

**Expected behavior**
Remove the image, or add clarifications. Also, only components and directives are mentioned, and iirc the hooks now work on more places.

**Comment by smasala** [comment]
Something that shows which are steps are recurring. I imagine it's those that are fainting portrayed.

![image](https://user-images.githubusercontent.com/1477905/26896994-28bb44d6-4bc7-11e7-92c1-d556c4defa8f.png)

**Comment by ocombe** [comment]
It would be nice to have something similar to what they have in vuejs docs: https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram
![vuejs lifecycle](https://vuejs.org/images/lifecycle.png)

**Comment by jenniferfell** [comment]
Old image was removed. 
Keeping this open as a feature request for a new image, such as the one vuejs docs
filename=https://angular.io/guide/lifecycle-hooks

**Comment by mgechev** [comment]
Looks like the picture is gone now. Closing the issue for now. Feel free to reopen with a new description reflecting the current state of the documentation. Thank you @SanderElias for the suggestion to make Angular better :)
