### ISSUE TITLE
Validator.email may need some rework - Or a new universal email validator is required

### ISSUE THREAD

**Issue by un33k** [angular/angular#17296]
**I'm submitting a ...** 
```
[ x ] feature request

```

**Current behavior**
Create a new email validator that validates the FQDN (in a routable sense) as well

**Expected behavior**
An email validator that finds root@localhost invalid, page@google invalid, but validates page@google.com

**Minimal reproduction of the problem with instructions**
Create a minimal form and add Validator.email as a synchronous validator.

**What is the motivation/use case for changing the behavior?**
While root@localhost is a valid email address, 99% of the usage cases "may" require the FQDN in the email to be validated.

**Please tell us about your environment:**
ng: 4.2.0-rc.2
@angular/cli: 1.1.0-rc.0
node: 6.9.5
os: darwin x64
browser: chrome

**Note:**
My hope is that this request is not just close with a few links to other issues raised against the current email validator.  True;  root@localhost is valid. No question about it.

However, the current email validator is 99% _unusable_ to accommodate the 1% need for emails such as root@localhost.  Send an email to **page@google** and see if **Larry** is going to get it.

> Address not found
> Your message wasn't delivered to page@google because the domain google couldn't be found. Check for typos or unnecessary spaces and try again.

The problem is that the 1% need is checked first in the current validator and therefore it will make the form valid and submittable, even though the probability of the email being invalid is 99%.

So statistically speaking, we  (perhaps) need another validator that sees **page@google** invalid and won't allow our users send an email where the recipient is not found.

Once again, this is a feature request for a new email validator so developers have a choice. Where developers can use the existing Validators.email or perhaps simply use the new, let's say "Validators.routableEmail"!

Thx.

**Comment by tytskyi** [comment]
Would you be happy if we have validator that does what you described, but goes as a separate package in npm?

**Comment by un33k** [comment]
@tytskyi I already use my own version within my own code space. So no immediate need. But for the sake of DRY and not copying the same code into all future projects, it would be great to have it come from a single package. Something like **@angular/contrib**  should be good. Contributed by others, blessed by @angular team.

**Comment by tytskyi** [comment]
`@angular/contrib` could be cool. Generally i would like to not have angular core extended - more features means more bugs and more maintenance. This potentially would postpone releases of the core.

**Comment by un33k** [comment]
@tytskyi not really, neither `@angular/material` nor `@angular/flex-layout` have any direct postponement power over @angular/core.  `@angular/contrib` should not have any either. It was just an idea as many packages &| frameworks also have the `contrib` portion.

**Comment by tytskyi** [comment]
@un33k i meant it will add overhead if implemented under `@angular/form` directly. I am both hands for `@angular/contrib`

**Comment by BioPhoton** [comment]
This sounds amazing!!

**Comment by xaviergxf** [comment]
Any news about changing the current behavior?

**Comment by trotyl** [comment]
> Any news about changing the current behavior?

@xaviergxf The current behavior is expected, see https://github.com/angular/angular/pull/32961.
