### ISSUE TITLE
App crash when there are 2 lazy routes with the same path but different #ModuleName after updating to Angular 4

### ISSUE THREAD

**Issue by Tuizi** [angular/angular#17307]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

It's impossible to have an app with 2 `loadChildren` with the same path, but with a different `#Module` and in differents routes module after migrating to 4.1.3 (from 2.4.0)

Example:
*/admin/admin-routing.module.ts*:
`loadChildren: './dashboard/dashboard.module#AdminDashboardModule'`

*/user/user-routing.module.ts*:
`loadChildren: './dashboard/dashboard.module#UserDashboardModule'`

Then when navigating to **/user/** this error happens: 
`Error: Cannot find 'UserDashboardModule' in './dashboard/dashboard.module' at checkNotEmpty (core.es5.js:5939)`

**Expected behavior**

It was working well with Angular 2.4.0, after migrating to Angular 4.1.3 the issue happens.

**Minimal reproduction of the problem with instructions**

It's very simple to reproduce, I add here only the routes configuration in routing modules files that matters:
*/app/app-routing.module.ts*
```
const routes: Routes = [
  {
    path: 'user',
    loadChildren: './user/user.module#UserModule'
  },
  {
    path: 'admin',
    loadChildren: './admin/admin.module#AdminModule'
  }
];
```

*/app/user/user-routing.module.ts*
```
const routes: Routes = [{
  path: '',
  component: UserComponent,
  children: [{
    path: '',
    loadChildren: './dashboard/dashboard.module#UserDashboardModule'
  }]
}];
```

*/app/admin/admin-routing.module.ts*
```
const routes: Routes = [{
  path: '',
  component: AdminComponent,
  children: [{
    path: '',
    loadChildren: './dashboard/dashboard.module#AdminDashboardModule'
  }]
}];
```

**What is the motivation / use case for changing the behavior?**

It was working with the version 2.0 of Angular

**Please tell us about your environment:** MacOSX, VSCode/Webstorm, Yarn, Angular Cli@1.1.0

* **Angular version:** 4.1.3

* **Browser:** all

 
* **Language:** typescript@2.3.4

* **Node (for AoT issues):** `node --version` =   v7.10.0

**Comment by tytskyi** [comment]
Did you try to separate files?

**Comment by Tuizi** [comment]
Hello tytskyi, what do you mean?

**Comment by tytskyi** [comment]
@Tuizi 
as far as i understand you have 1  file `./dashboard/dashboard.module.ts` where you have 2 modules defined and exported: `AdminDashboardModule` and `UserDashboardModule`. 
Did you try to make 2 files:  `./dashboard/dashboard-admin.module.ts` and  `./dashboard/dashboard-user.module.ts` or something similar?

**Comment by Tuizi** [comment]
This is what I currently have.

I have those files in my solution:
`/app/user/user-routing.module.ts`
`/app/user/dashboard/dashboard.module`

and 

`/app/admin/admin-routing.module.ts` 
`/app/admin/dashboard/dashboard.module`

**Comment by Tuizi** [comment]
But @tytskyi don't worry I already found a workaround, I'm just here to report the issue.

Here is the changes I made for a workaround with minimal changes (changing only filenames)

_/app/user/user-routing.module.ts_
```
const routes: Routes = [{
  path: '',
  component: UserComponent,
  children: [{
    path: '',
    loadChildren: './dashboard/user-dashboard.module#UserDashboardModule'
  }]
}];
```

_/app/admin/admin-routing.module.ts_

```
const routes: Routes = [{
  path: '',
  component: AdminComponent,
  children: [{
    path: '',
    loadChildren: './dashboard/admin-dashboard.module#AdminDashboardModule'
  }]
}];
```

So to summarize, with Angular 4:
2 lazy routes with the same path **crash** the app:
```
//module user-routing
loadChildren: './dashboard/dashboard.module#UserDashboardModule'

// module admin-routing
loadChildren: './dashboard/dashboard.module#AdminDashboardModule'
```

The workaround: Renaming the module file
```
//module user-routing
loadChildren: './dashboard/user-dashboard.module#UserDashboardModule'

// module admin-routing
loadChildren: './dashboard/admin-dashboard.module#AdminDashboardModule'
```

**Comment by vicb** [comment]
I had a quick look at `SystemJsNgModuleLoader`, it seems like you should specify the path from the root of the project.
Could you please try and report ?
Thanks.

**Comment by Tuizi** [comment]
@vicb **Yes**, it works if I put the path from the root of the project.

**Comment by jasonaden** [comment]
Thanks @Tuizi. Closing this as it appears to be resolved.

**Comment by ShankarSumanth** [comment]
Shouldn't this be documented somewhere? I came across this issue very recently (although it was easy to figure out by a search for the routes having same paths) and the error message is not helpful at all.
