### ISSUE TITLE
TestBed / integration test swallows exceptions

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#1731]
@vicb I guess you will be the one most familiar with the topic - as of today any exception in the code executed under integration test (compiler's `integration_spec.js`) seems to be swallowed somewhere (test bed?). By "swallowed" I mean that it doesn't get printed anywhere, a test fails with non-informative:

> Chrome 44.0.2394 (Mac OS X 10.9.5)  should inject promises into directives FAILED
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

Would be there any way of propagating the actual exception to the test failure log? I could dig into this issue, but not sure where to start atm, any help appreciated.

**Comment by vicb** [comment]
Is this JS only ?

**Comment by vicb** [comment]
relates to #864 ?

**Comment by pkozlowski-opensource** [comment]
> Is this JS only 

@vicb hard to say since Dartium crashes in this case :-/

**Comment by jbdeboer** [comment]
Related to #1709?

**Comment by vicb** [comment]
ref https://github.com/mhevery/jasmine-node/issues/267
Not sure if this will help but I'll investigate the `--captureExceptions` flag (found while investigating a zone.js issue)

**Comment by vicb** [comment]
@pkozlowski-opensource could you try to add this to your config:

```
    client: {
      args: ['--captureExceptions']
    },
```

and report if it helps ?

**Comment by pkozlowski-opensource** [comment]
@vicb are you talking about Karma's config here? I've added it to `karma-js.conf.js` but it doesn't seem to help (not I'm not sure how this would be related to jasmine-node....)

**Comment by vicb** [comment]
@pkozlowski-opensource good point !

may be https://github.com/jasmine/jasmine/issues/529

**Comment by jbdeboer** [comment]
Upon further investigation; I don't think this issue affects GT

**Comment by juliemr** [comment]
I think this is pretty obsolete, can we close?
