### ISSUE TITLE
DecimalPipe.transform() is not formatting correctly on IE11

### ISSUE THREAD

**Issue by aldo-roman** [angular/angular#17319]
**I'm submitting a ...** 
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When using the 'number' pipe (which internally is DecimalPipe), it formats correctly
When using the output of DecimalPipe.transform(9999999.99, '1.2-2'), it misses the million separator
9999999.99 gets formated as -> `9999,999.99`

**Expected behavior**
9999999.99 gets always formated as -> `9,999,999.99`

**Minimal reproduction of the problem with instructions**
On IE 11 only:
http://plnkr.co/edit/PbkbaarXmQjuSO7kNe3e?p=preview
Works well on Chrome

**What is the motivation / use case for changing the behavior?**
I need a custom pipe that reuses DecimalPipe with '1.2-2' scale.
On IE11 the number is wrong formatted

**Please tell us about your environment:**
Windows 7, IE11

* **Angular version:** 4.1.X

* **Browser:** IE11
 
* **Language:** Typescript 2.3

**Comment by skreborn** [comment]
Your plunker uses the locale `es-US` - is that by mistake? Using `en-US` fixes the issue for me. [Here's an updated plunker](http://plnkr.co/edit/ShhKqeMkwBOSxolGOJ0g?p=preview).

**Comment by aldo-roman** [comment]
Hi @skreborn, it is not a mistake, we are developing an app that uses `es-US` as locale.

This is the locale I received from Platform service. What is strange is that `es-US` works on built-in pipe but not in custom pipe transform.

**Comment by ocombe** [comment]
Hello, you are correct that it should format the number as `9,999,999.99`. This will be fixed with the PR to replace the intl API for angular v5 (see [#10809](https://github.com/angular/angular/issues/10809)).
