### ISSUE TITLE
Bug(Router): Importing Modules from index.ts in Lazy-Loaded module fails: Unexpected value 'undefined' imported by the module

### ISSUE THREAD

**Issue by macjohnny** [angular/angular#17322]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report 
[ ] feature request
[ ] support request
```

**Current behavior**
When lazy-loading module LazyModule1, which imports ModuleA, which imports ModuleC from **``src/modules/index.ts``**, the module/component cannot be display and fails with the error: ``Uncaught (in promise): Error: Unexpected value 'undefined' imported by the module 'ModuleA'``.
The same error also occurs when changing the import to **``src/modules``** (although this can't be tested in the plunkr).

Interestingly, no error occurs when lazy-loading module LazyModule2, which imports ModuleB, which imports ModuleC from **``src/modules/index2.ts``**.
No error either occurs when changing the import to **``src/modules/moduleC/index``**

What is also interesting is the fact that no problem occurs when building in AOT-mode, while in JIT-mode the error occurs.

**Expected behavior**
The import of modules should not fail in any of the cases described.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/weFJvAZstrzHCK5EWNCu?p=preview

Clicking on "Lazy Module 2" works and shows "Component 2, Component B, Component C", clicking on "Lazy Module 1" fails and shows no output, although it should show "Component 1, Component A, Component C"

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
any

* **Angular version:** 4.1.3, 4.2.0-rc.2

* **Browser:** all
 
* **Language:** Typescript 2.2.2

**Comment by mlc-mlapis** [comment]
Using `barrels` is not recommended. Did you try to do the same without them?

**Comment by macjohnny** [comment]
@mlc-mlapis The error does not occur when changing the import to `src/modules/index2` or `src/modules/moduleC/index`, i.e. it can work with barrels.

**Comment by macjohnny** [comment]
here is an updated plunkr with angular 4.2.4: http://plnkr.co/edit/2lUGIF?p=preview
the problem remains

**Comment by nbuso** [comment]
Hi @macjohnny, we are facing the same problem, did you find any solution apart from running everything with AOT? I was checking your plnkr, and I didn't spot differences between ModuleA and ModuleB, did you understand why only one module is working?

**Comment by macjohnny** [comment]
@nbuso the difference between ModuleA and ModuleB is that in ModuleB, the import of ModuleC is done with `import { ModuleC } from "src/modules/index2";` while in ModuleA, the import of ModuleC is done with `import { ModuleC } from "src/modules/index";`   

In order for it to run with both, JIT and AOT, we ended up importing directly from `import { ModuleC } from "src/modules/moduleC/index";`, which is the file where the module is actually declared. 
hope this helps.

**Comment by macjohnny** [comment]
closing this issue as unresolved
