### ISSUE TITLE
when editing the template and using the attribute i18n receiving a warning: "Attribute i18n is not allowed here"

### ISSUE THREAD

**Issue by yosigolan** [angular/angular#17326]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
when editing the template and using the attribute i18n receiving a warning: "Attribute i18n is not allowed here".
i am working with web storm idea the version 2017.1.3

**Expected behavior**
no warning should appear as i18n is the translation feature of angular

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
i am working with web storm idea the version 2017.1.3

* **Angular version:** 2.0.X
4.1.2

* **Language:** [ES62015]

**Comment by vicb** [comment]
Seems like the bug should be reported to WebStorm ?

**Comment by ocombe** [comment]
@yosigolan do you use the angular language service?

**Comment by yosigolan** [comment]
Thank you @ocombe , this is exactly why i opened this bug at angular repo, since i am USING angular language service and as i understand it should direct webstorm which warnings to show.
@vicb can you approve it?

**Comment by ocombe** [comment]
So I can confirm the issue, @chuckjaz will take a look at this and see if this is a problem with the language service or webstorm.
![capture d ecran 2017-06-12 19 52 43](https://user-images.githubusercontent.com/265378/27048049-9a781c02-4faa-11e7-8afc-49075b9c5409.png)

**Comment by yosigolan** [comment]
great thanks.

**Comment by ocombe** [comment]
@chuckjaz any news on this? It is still present, and by the way we also have this with i18n-... attributes (like `i18n-title`)

**Comment by yosigolan** [comment]
Hey.
can you estimate when will it be fixed?

**Comment by ocombe** [comment]
The priority is very low, so don't hold you breath

**Comment by yosigolan** [comment]
Hey @ocombe 
in angular 6 it is fixed! the warning is not shown any more :)
However....
the attributes translation tags such as i18n-aria-label or i18n-title do produce a warning.
should i open a new issue for it?

Thanks Yosi

**Comment by ocombe** [comment]
Not necessary, this one is still opened

**Comment by JoostK** [comment]
I can no longer reproduce this issue with the latest language service, so closing as resolved at some point.
