### ISSUE TITLE
docs : missing copy files in VISUAL STUDIO 2015 QUICKSTART

### ISSUE THREAD

**Issue by AmolST** [angular/angular#17320]
Under section : Step 3: Copy the QuickStart files into the ASP.NET project folder
In list of minimum files required should contain 3 more items :

1. src\main.ts
2. src\systemjs.config.js
3. src\systemjs-angular-loader.js

**Comment by jenniferfell** [comment]
@StephenFluin @IgorMinar Hi. Any comments on priority for this? My guess is this doc is out-of-date and either obsolete (and can be removed) or requires a rewrite to make it current. Input welcome. Thanks.

**Comment by StephenFluin** [comment]
@jenniferfell It's definitely out of date (talks about TypeScript old version) and needs a rewrite. There's probably some simpler best practices now, possibly involving the following tools built into dotnet.

```1. Download and install .NET core for your platform (Windows, Linux, Mac):
https://www.microsoft.com/net/download/core
2. At the command line:
dotnet new angular
npm install
dotnet run```

**Comment by petebacondarwin** [comment]
The page in question https://angular.io/guide/visual-studio-2015 no longer appears in the navigation.
I suspect that it is either deprecated or overlooked.
Either way, I think given that this guide is outdated, is hard to find on the site, and this issue has had very little traction outside the team, we should just remove the guide from the docs.

What do you think @aikidave ?

**Comment by anirugu** [comment]
I read the given page and it's look like this page is no longer useful. The latest version of VS is 2019 and in latest template (dotnet new angular) it build the app using angular 8.

The page guide user to install npm install -g typescript@latest which I am sure will create trouble.  We can update this to work with latest 5 or 3.1. 

If you guide me I can work on this. This sound interesting.

**Comment by aikidave** [comment]
I think the right thing to do in this case is remove the topic completely. We can discuss with the team/community if a new guide is needed.
