### ISSUE TITLE
Social websites are not showing updated meta tags on share?

### ISSUE THREAD

**Issue by Sathishchary** [angular/angular#17331]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am using  [meta service](https://angular.io/docs/ts/latest/api/platform-browser/index/Meta-class.html) for meta tags update. I am able to update the default tags with meta service in index.html , and I am able to see the updated tags in inspect element console. social sites are showing default meta tags only.
but these updated tags are not showing up in the social websites sharing.

**Expected behavior**

Updated meta tags are there in the index.html . I need to show the updated meta tags on social share. 
I am not able to succeed on that. 
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I need to show the dynamic meta tags on the social sites like fb and twitter etc

**Please tell us about your environment:**

 Operating system : windows 10
  Server: apache server
  backend : Spring Rest API

* **Angular version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =6.9.1

**index.html with default static meta tags** 

```
<html>
<head>
<meta charset="utf-8">
<title>Angular App</title>
<script>document.write('<base href="' + document.location + '" />');</script>
<meta property="twitter:card" content="summary">
<meta property="twitter:site" content="@michlbrmly">
<meta property="twitter:title" content="Grace">
<meta property="twitter:description" content="Grace is the only complete studio album by Jeff Buckley, released on August 23, 1994..">
<meta property="twitter:image" content="https://example.com/vod/images/125/03022017/flight1486153663429_play1.gif">
<meta property="twitter:url" content="https://example.com/AngularApp/#/embed-video/PRIVATE/3867c8e2-85ba-4ca9-9804-b28769e67746">
<meta property="og:title" content="Angular App">
<meta property="og:site_name " content="My Favourite Albums">
<meta property="og:url " content="https://example.com/AngularApp/#/embed-video/PRIVATE/3867c8e2-85ba-4ca9-9804-b28769e67746">
<meta property="og:description" content="Grace is the only complete studio album by Jeff Buckley, released on August 23, 1994..">
<meta property="og:image" content="https://example.com/vod/images/125/03022017/flight1486153663429_play1.gif">
<link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body > <app-root>Loading..</app-root> </body>
</html>
```

**Component for updated tags:**
 I am changing the tags dynamically and its updating in the index.html. added screenshots below.
```
import { Component, ElementRef, OnInit, OnDestroy, Input, Inject, AfterViewInit, Renderer} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Meta, MetaDefinition } from '@angular/platform-browser';

@Component({
  selector: 'app-share-video',
  templateUrl: './share-video.component.html',
})
export ShareVideoComponent implements ngOnInit{
constructor(private router: Router,private metaService: Meta){
}
ngOnInit(){
	this.metaService.updateTag({ content: 'New Updated tags info'}, "property='og:title'");
	this.metaService.updateTag({content:'Embed videos'}, "property ='twitter:card'");
}
}
```
After loading this component, these two tags ('og:title' and 'twitter:card') are updating with with new content. but in the social share fb and other websites are taking default meta tags from index.html when i share the url. these old tags are updated with new tags I am seeing in the inspect element console. I am not seeing the new meta content in the scocial websites.
followed this [Meta Code](https://github.com/angular/angular/pull/12322/files#diff-7979e98d95c45d21e56cf2602244f220R36)
How can i show the updated meta tags in the social websites?
default meta tags in index.html:
![before update tags](https://user-images.githubusercontent.com/12939444/26923112-c6ba8e3e-4c5e-11e7-8c8f-823c2c926694.JPG)
updated meta tags in index.html
![after updated tags](https://user-images.githubusercontent.com/12939444/26923238-21b3c7e2-4c5f-11e7-9b8b-79a2c124c509.png)

facebook is taking default tags not updated tags.
![old tags](https://user-images.githubusercontent.com/12939444/26923850-1736829e-4c61-11e7-9638-9e75823987c8.png)

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
It looks like you need server side rendering, which can be done with Angular Universal: see more here https://angular.io/docs/ts/latest/guide/universal.html

**Comment by Sathishchary** [comment]
Thanks for the info @Toxicable. I am following that angular universal concept

**Comment by parthkharecha** [comment]
@Sathishchary  what is use in back end  side (php or .net etc)

**Comment by Sathishchary** [comment]
we are using java backend with spring REST API.

**Comment by parthkharecha** [comment]
@Sathishchary you are implement angular universal successfully ???

**Comment by Sathishchary** [comment]
@parthkharecha,  No, We are not using angular universal for now, we ended up this issue with creating simple spring web application, we are just sending meta tags from client application to simple web application, there we are generating new url and from that we will redirect to angular app. But this is not good idea. We are looking to change this to angular universal. thanks

**Comment by parthkharecha** [comment]
@Sathishchary thanks to reply.

**Comment by vegaskev** [comment]
@Sathishchary I'd love an update if you happen to have one.

**Comment by EM15** [comment]
Same problem here. Does anyone resolve it for .NET Core?

**Comment by parthkharecha** [comment]
@EM15
I have implementation in laravel hope you get some idea for .Net

https://laraveld3v.blogspot.in/2018/02/server-side-rendering-with-meta-tags-in.html?m=1

**Comment by elSuperRiton** [comment]
Same problem. We've setup an angular universal project ( @ng4 ) and only facebook cannot properly resolve the meta title, desc etc....
Reading the source code the titles appear properly but it seems that facebook cannot resolve it for whatever reason. Any idea ( PS : We also make use of the APP_INITIALIZER in order to render proper version of the website which is using ngx-translate )
