### ISSUE TITLE
Reattached components only route one level deeper when using a RouteReuseStrategy

### ISSUE THREAD

**Issue by matt-psaltis** [angular/angular#17333]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Routing breaks down at grandchildren of the reattached component. If the reattached component is the root, it seems to work ok but in our circumstance at least, we have a component hierarchy where detaching and reattaching from the root doesn't make sense.

**Expected behavior**

In the attached plunker, the reattached component tree should be able to then successfully route and display the Page2 component.

**Minimal reproduction of the problem with instructions**

I have setup an example of the problem here: https://plnkr.co/edit/G8BjuyxUmB15PcpTyGp1?p=preview

The basic route hierarchy is: /admin/secondLevel/crisis-center/page1/page2

The RouteReuseStrategy detaches at /admin/secondLevel/crisis-center

To reproduce:

The page should load and redirect automatically to the Crisis center.

Step 1. Enter some text into the text field in the Crisis center text field. (Don't click the Page 1 button yet)
Step 2. Click the Heroes hyperlink at the top of the page.
Step 3. Click the Crisis Center hyperlink at the top of the page.
Step 4. Note that the text entered in step 1 is re-displayed successfully in the text field. This indicates a successful detach and reattach of the component / route hierarchy.
Step 5. Click Page 1 (The Page 1 component is displayed)
Step 6. Click Page 2

Note that the page 2 routing completes successfully however the component is not displayed.

**What is the motivation / use case for changing the behavior?**

I believe this is a bug in the current attach process. I've attempted to dig in an debug this myself, it seems that the outlet's parentContexts are not configured properly. Exactly why this happens I haven't been able to ascertain.

**Please tell us about your environment:**

* **Angular version:** v4.2.0-rc.2-33ba3e3

Running against github builds.

* **Browser:** Chrome 59.0.3071.86
 
* **Language:** TypeScript

**Comment by PhelanHarris** [comment]
I've run into what I think is the same issue as well. After doing some debugging through the router code it looks like any child router-outlets do not get reactivated when reattaching a component tree, and any child router-outlets that were created after detatching remain active. To see what I mean:

My page hierarchy looks like tab/:tabId/view or tab/:tabId/forms
I am using a custom route reuse strategy to store and load a new (or cached) component when tabId changes. I have a TabComponent at the :tabId level that contains a router-outlet for the view or forms component.

1. I start at tab/1/view
2. I create a new tab and navigate to tab/2/view
3. I navigate back to tab/1/view
4. I try to navigate to tab/1/forms, but the FormsComponent does not appear, I still see the ViewComponent.
5. I navigate back to tab/2/view, and the FormsComponent that I was trying to load in tab 1 appears in that tab's router-outlet.


Hopefully this will be helpful for fixing the bug if the RouteReuseStrategy is something that's going to be supported by the Angular team (which I really hope you guys do).

**Comment by werts** [comment]
@PhelanHarris i think i have the same issure,how can you solve the problem later?

**Comment by PhelanHarris** [comment]
@werts I was never able to solve the problem. Opted to not use a RouteReuseStrategy since it just doesn't work for my use case. I implemented a shared service to cache the data of each tab and then I initialize the component with that data when it's opened. Not ideal, since I'd like switching tabs to be instant, but it works for now.

**Comment by atscott** [comment]
Confirmed in v9 as well: https://stackblitz.com/edit/angular-ivy-s8kzjr?file=src%2Fapp%2Freuse-strategy.ts
I wonder if this is related to #16192...
