### ISSUE TITLE
Basic test fails with error TypeError: null is not an object

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#17337]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am trying to make tests working. I have working tests for isolated environment like services, but cant make tests work for angular component.

I have created simple component exactly like that one in guide and also first simple test
https://angular.io/docs/ts/latest/guide/testing.html

I am not using completely your setup, because i am using webpack, but i have working karma with webpack and phantomjs without any problem for non angular tests. When i run that simple test

```typescript
describe('BannerComponent (inline template)', () =>
{
    let comp: FakeHomeComponent;
    let fixture: ComponentFixture<FakeHomeComponent>;
    let de: DebugElement;
    let el: HTMLElement;

    beforeEach(() =>
    {
        TestBed.configureTestingModule(
        {
            declarations: [FakeHomeComponent], // declare the test component
        });

        fixture = TestBed.createComponent(FakeHomeComponent);

        comp = fixture.componentInstance; // BannerComponent test instance

        // query for the title <h1> by CSS element selector
        de = fixture.debugElement.query(By.css('h1'));
        el = de.nativeElement;
    });

    it('should display original title', () =>
    {
        fixture.detectChanges();
        expect(el.textContent).toContain(comp.title);
    });
});
```

it fails with following error.

TypeError: null is not an object (evaluating 'this.platform.injector') in app/pages/home/home.component.spec.ts (line 18743)
        _createCompilerAndModule@app/pages/home/home.component.spec.ts:18743:44
        _initIfNeeded@app/pages/home/home.component.spec.ts:18705:63
        createComponent@app/pages/home/home.component.spec.ts:18793:27
        createComponent@app/pages/home/home.component.spec.ts:18612:44
        app/pages/home/home.component.spec.ts:35641:106
        invoke@app/pages/home/home.component.spec.ts:15576:31
        onInvoke@app/pages/home/home.component.spec.ts:31371:45
        invoke@app/pages/home/home.component.spec.ts:15575:40
        run@app/pages/home/home.component.spec.ts:15326:49
        app/pages/home/home.component.spec.ts:31070:37
        execute@app/pages/home/home.component.spec.ts:31098:46
        execute@app/pages/home/home.component.spec.ts:31098:46
        app/pages/home/home.component.spec.ts:31095:134
        invokeTask@app/pages/home/home.component.spec.ts:15609:36
        runTask@app/pages/home/home.component.spec.ts:15376:57
        drainMicroTaskQueue@app/pages/home/home.component.spec.ts:15769:42
        run@app/pages/home/home.component.spec.ts:139643:30
        app/pages/home/home.component.spec.ts:139656:32
        flush@app/pages/home/home.component.spec.ts:140011:12
        TypeError: undefined is not an object (evaluating 'fixture.detectChanges') in app/pages/home/home.component.spec.ts (line 35647)
        app/pages/home/home.component.spec.ts:35647:16
        invoke@app/pages/home/home.component.spec.ts:15576:31
        onInvoke@app/pages/home/home.component.spec.ts:31371:45
        invoke@app/pages/home/home.component.spec.ts:15575:40
        run@app/pages/home/home.component.spec.ts:15326:49
        app/pages/home/home.component.spec.ts:31070:37
        execute@app/pages/home/home.component.spec.ts:31098:46
        execute@app/pages/home/home.component.spec.ts:31098:46
        app/pages/home/home.component.spec.ts:31095:134
        invokeTask@app/pages/home/home.component.spec.ts:15609:36
        runTask@app/pages/home/home.component.spec.ts:15376:57
        drainMicroTaskQueue@app/pages/home/home.component.spec.ts:15769:42
        run@app/pages/home/home.component.spec.ts:139643:30
        app/pages/home/home.component.spec.ts:139656:32

I have these imports

```typescript
//also tried these 2
//import 'core-js/es6';
//import 'core-js/es7/reflect';
import 'core-js/client/shim.js';

import 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/toPromise';
import 'rxjs/add/observable/empty';
import 'rxjs/add/observable/fromPromise';
import 'rxjs/add/observable/throw';

import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
```

I have completely abandoned systemjs and i dont want to go back to it. Am i missing something or is there bug?

**Expected behavior**
I hope it should work :)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10, npm 3.7.3, Visual Studio Code

* **Angular version:** 4.1.3

* **Browser:** [Chrome | PhantomJS ]

 
* **Language:** [TypeScript 2.3.4]

* **Node (for AoT issues):** `node --version` = 6.9.4

**Comment by ericmartinezr** [comment]
Does this fix your issue https://github.com/angular/angular/issues/16215 ?

**Comment by kukjevov** [comment]
Awesome 👍 you saved my day, finaly i can go home. One more question, if i understand it correctly it should be called only once for all tests?
