### ISSUE TITLE
<![CDATA[]]> is not respected by curly-brace interpolation

### ISSUE THREAD

**Issue by SterlingMcCall** [angular/angular#17339]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Double curly braces inside of a <![CDATA[]]> block in a template will cause the angular parser to fail. 
If the expression in the curly braces is valid, it will interpolated as if it were not in the CDATA.
If the expression is not valid and is a simple expression, such as {{nonExistantVariable}}, it will fail silently and continue parsing the template.
If the expression is not valid and refers to a field of an invalid variable, such as {{nonExistantObject.nonExistantField}}, angular will throw TypeErrors saying "Cannot read property 'definitelyNonExistantField' of undefined" and the rest of the template will not be parsed. What is very strange is that if there is non-interpolated text as well as "valid" interpolation before this sort of invalid interpolation expression, then everything after (and including) the first set of curly braces will not show up. If this is confusing, add {{nonExistantObject.definitelyNonExistantField}} to line 20 in app.ts in the plunkr (https://plnkr.co/edit/yqBxv0wYPElvgBWZ0TFY?p=preview) and observe.

**Expected behavior**
I would expect that, like property bindings, interpolation would be ignored within CDATA blocks.

**Minimal reproduction of the problem with instructions**
Make a template that contains
```
<![CDATA[
{{blah}}
]]>
```
and observe that the text "{{blah}}" does not appear on the page.

Look at the plunkr (https://plnkr.co/edit/yqBxv0wYPElvgBWZ0TFY?p=preview) for a more complete example.

**What is the motivation / use case for changing the behavior?**
Any use case where {{ }} would be inside of a CDATA block.

**Please tell us about your environment:**
Angular CLI 1.0.0, Webpack with AoT, Linux Mint, IntelliJ IDEA, npm

* **Angular version:** 4.0.0

* **Browser:** Tested on Chrome 58 and Firefox 53. I would assume all browsers.
 
* **Language:** TypeScript 2.2.2

* **Node (for AoT issues):** 6.10.2

**Comment by pkozlowski-opensource** [comment]
This seem to work OK in Angular 7: https://stackblitz.com/edit/angular-p3uhsw

Closing as fixed.
