### ISSUE TITLE
Custom pipe inside ngFor async loop rendering issue

### ISSUE THREAD

**Issue by adadgio** [angular/angular#17334]
I'm submitting what i think is an issue involving `async` data inside `*ngFor` and (custom) pipe(s).

**Current behavior**
The bug manifest when applying a custom pipe to something inside an `*ngFor` loop (loaded with async `Observable`. In this scenario a list in Ionic2 `ion-list` `list-item`.

When NOT using the pipe, loop completes and data is rendered without problems.
````
<div *ngFor="let chat of chatsObservable | async; trackBy: trackByFn">
<p>{{ chat.text }}</p>
</div>
````
<img width="320" alt="qsdqsdqsd" src="https://user-images.githubusercontent.com/502070/26929531-56aa518c-4c5a-11e7-889c-cefd50afaa14.png">

When using the pipe, loop does not *seem* to complete but no errors as throw (no undefined values, etc...) and the template is irregularily rendered. Console logs show different data items that number if list items incompletely rendered suggest.
```
<div *ngFor="let chat of chatsObservable | async; trackBy: trackByFn">
<p>{{ chat.text | atob }}</p>
</div>
```
<img width="320" alt="intouch_-_ionic_lab" src="https://user-images.githubusercontent.com/502070/26929547-5f1e2960-4c5a-11e7-881a-fb407584cfab.png">

Here is the pipe, which is as simple as possible.

```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
    name: 'atob',
})
export class Atob implements PipeTransform {
    transform(text: string) {
         return atob(text);
    }
}
```

**Please tell us about your environment:**
Using chrome, Safari, Firefox or any desktop/mobile browser.

**Angular version:**
Angular 2.4.2, Ionic 3.1.x, and angularfire2

**Comment by adadgio** [comment]
This is not and issue. Its about pure and impure pipes... 

```
@Pipe({
    name: 'atob',
   pure: false,
})
```

**Comment by Toxicable** [comment]
Could you please make a minimal reproduction? A plunkr would be the best, here's a template to get you started: https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by pkozlowski-opensource** [comment]
Closing since we haven't heard back with the reproduce scenario and it is not actionable given the existing problem description.
