### ISSUE TITLE
Add disp attribute to XBM and XLIFF 1.2 too

### ISSUE THREAD

**Issue by jaska45** [angular/angular#17345]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When you run the extract tool to create XLIFF 2.0 there is this new neat feature that saves the variable or experssion inside an interpolation placeholder. If I have this

`<p i18n>Hello {{name}}</p>`

The following source element will be created.

`<source>Hello <ph id="0" equiv="INTERPOLATION" disp="{{name}}"/></source>`

This is very good because without it an essential information (e.g. variable name) would be lost. When disp is there the localization tool can show the pattern in a way that is much more descriptive. Here is a screenshot from a localization tool in the case where variable name coould be read.

![xliff2](https://user-images.githubusercontent.com/10090968/26950823-e9eda7b6-4c53-11e7-8b5a-a96d51ea20c7.png)

As you can see pattern with variable names are pretty easy to read and understand.

However if there are no disp attribute the localization tool can only get the placeholder index and the same project as above would look like this.

![xmb](https://user-images.githubusercontent.com/10090968/26950988-761f72e6-4c54-11e7-8f95-fc180e07b2df.png)

As you can see pattern with only index are harder to read and undestand. Developer can copensate this by adding commens (as seen on both screenshots) but it would be a bit illogical because instead of variable name he or she would have to use 0 or 1 ...

**Expected behavior**

Implement the same feature that is currently in XLIFF 2.0 to XBM and XLIFF 1.2 extractors.

**Minimal reproduction of the problem with instructions**

Extract any interpolated string first to XLIFF 2.0 and then either to XMB or XLIFF 1.2

**What is the motivation / use case for changing the behavior?**

Make localization easier.

**Please tell us about your environment:**

Windows 8.1, VS code 1.12.2

* **Angular version:** 4.2.0-rc.2

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` = v6.9.1

**Comment by ocombe** [comment]
Thanks! I'll add it to the to do list :)

**Comment by jaska45** [comment]
Thanks. In XLIFF 1.2 you could use equiv-text attribute. I don't know about XBM because it is so hard to get any information about that format.

**Comment by ocombe** [comment]
yeah, there is no spec for XMB (I know, I've asked)

**Comment by jaska45** [comment]
As far as I know only Angular uses XMB. I have never seen anybody else using it. XMB is XML (even without official DTD or schema) so it should be safe just add an extra attribute. Something like

`<ph name="INTERPOLATION" disp="{{name}}">`

**Comment by ocombe** [comment]
Actually XMB/XTB was developed by google, for google. It is available for the public through some of google open source projects (closure, angular), but that's about it. The lack of spec isn't helping third party tools to support it...

**Comment by jaska45** [comment]
Thanks. This is not that important because XLIFF 2.0 works fine :-)

I will continue testing the new features. Thank you for implementing the, It seems the the only really important missing piece if the source code (.ts) string extraction. 

I am happy that Angular has this official I18N/L10N method. Most other JS platforms do not have and then you end up with several 3rd party implementations. Hard for developers, hard for localization tool vendors.

**Comment by ocombe** [comment]
Yes, we're working hard on adding those crucial missing features! It's nice that some people like you test the new things and report bugs as well.

**Comment by panuruj** [comment]
@jaska45 I'm glad that XLIFF 2.0 is working out for you. Our team at Microsoft is using it extensively as well. By the way, what is the tool that you have on your screenshots?

**Comment by jaska45** [comment]
It is a new localization tool that is currently on beta. I will send you some information about it.

**Comment by joelmarty** [comment]
@jaska45 i'm very interested in your localization tool too!
