### ISSUE TITLE
[Feature Request] Automatic injection of the BrowserModule

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#17346]
It looks as if the browser module can be automatically injected by the container when the runtime is a browser.

**Comment by Toxicable** [comment]
Please fill out the feature request correctly.
Angular dosen't know it's going to use in a browser at build time so how can it include BrowserModule in the bundle?

**Comment by oleersoy** [comment]
In all the examples I have seen thus far I see this import at the primary module level:

```` js
import { BrowserModule } from '@angular/platform-browser';
````
Post that I have not seen `'@angular/platform-browser';` being used as an import source anywhere else in the examples.  So at least it seems that the need for `{BrowserModule}`could be something that is detected and injected at runtime?

**Comment by pkozlowski-opensource** [comment]
This is a duplicate of the existing issue #10916
