### ISSUE TITLE
Abilitiy to specify UrlResolvers on a per-component basis

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#1734]
Components from different packages may use different url schemes for ```templateUrl```.

To allow an application to use components with different url schemes, the ```UrlResolver``` should be bound per-component (or, for bonus points, per-package) instead of the current implementation where it is a global service injected into the ```Compiler```

**Comment by tbosch** [comment]
This might lead to problems with Dart transformers, as it is hard for them to execute the code that they are transforming. @kegluneq What do you think?

**Comment by vicb** [comment]
Let me comment with the idea I had during the implementation:

For the `UrlResolver` the idea was that it would be simple and have a single responsibility of resolving (ie ~concatenating) URLs.

At that time I added a `ComponentUrlMapper` which responsibility is to return relative path of the component (from the app path).

The idea is that the template Url would be `UrlResolver(UrlResolver(app path, cmp path), template path)` see the [code](https://github.com/angular/angular/blob/0e2047f9ca082e912d195338e7bae9753c908206/modules/angular2/src/core/compiler/compiler.js#L208).

The idea was that the transformer would generate the `ComponentUrlMapper` mappings in Dart. I'm not sure how to generate this for JS.

May be there are better things to do but that was my idea at that time.

**Comment by kegluneq** [comment]
@tbosch agreed, this would be difficult but not impossible. We may be able to use [Isolate#spawnUri](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:isolate.Isolate#id_spawnUri) to execute a generated `main` method that calls a `UrlResolver` implementation which is specified in the `@Component` annotation. I think it would be at least as nasty as it sounds to make it work.

For reference, in https://github.com/angular/angular/pull/1778 I'm working on inlining template code when `templateUrl` values are discovered. The current url resolution doesn't do anything intelligent, it just looks for `templateUrl` relative to the file in which it is defined.

Generating entries for `ComponentUrlMapper` would be much easier but may not be necessary if we can successfully inline templates.

**Comment by mhevery** [comment]
I don't think we are going to do this. We will be doing relative paths. Closing.
