### ISSUE TITLE
aio: sidenav position/height is off for a moment when scrolling on mobile Chrome

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#17355]
When scrolling down/up in Chrome on mobile, the browser's adress bar hides/appears which changes the viewport's height. But the viewport height is not updated until after the scroll movement (which resulted in the address bar to be hidden/shown) has finished. During that scroll, the SideNav's height/position (which depend on the viewport height) are not updated. The sidenav jumps to the correct height/position once the scrolling is over.

**Comment by petebacondarwin** [comment]
Is this a programmatic (i.e. JavaScript) problem or a styling (i.e. CSS) problem?

**Comment by gkalpak** [comment]
I don't know of a way to solve this (either by JS or CSS), so currently it is just _a problem_ :smiley:
BTH, it feels more like a Chrome bug: It should update the viewport height while scrolling instead of only when done scrolling.

**Comment by IgorMinar** [comment]
we now use fullscreen mode so this is not a problem any more. please reopen if I misunderstood the problem.

**Comment by gkalpak** [comment]
Fullscreen mode only applies to "installed" version. When opening in the browser (on mobile), you still get the issue. But since I don't think there is anything we can do atm, I'm happy to keep this closed :smiley:
