### ISSUE TITLE
source map has wrong path

### ISSUE THREAD

**Issue by danibuiza** [angular/angular#17354]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

when loading the compiler.umd.min.js the source map is trying to be retrieved from  /Users/jasonaden/Projects/angular/dist/packages-dist/compiler/bundles/compiler.umd.min.js.map
**Expected behavior**

source map should be relative to the source
**Minimal reproduction of the problem with instructions**

just load the file mentioned above
**What is the motivation / use case for changing the behavior?**

N.A
**Please tell us about your environment:**

all
* **Angular version:** 2.0.X

angular 4.1.3
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =   
not an AOT issue

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/17166

**Comment by hansl** [comment]
Closing as this is a dupe.
