### ISSUE TITLE
Error while compiling with webpack

### ISSUE THREAD

**Issue by zishanj** [angular/angular#17360]
I am using Angular v4.2.0, node v6.10.3, npm v3.10.10. While compiling ts files using webpack I get following error:

> This relative module was not found:
> 
> * ./app/app.module in ./resources/assets/js/main.ts

Above module does exists in correct path and also following warnings:

> WARNING in ./~/@angular/core/@angular/core.es5.js
> 5704:15-36 Critical dependency: the request of a dependency is an expression
> 
> WARNING in ./~/@angular/core/@angular/core.es5.js
> 5720:15-102 Critical dependency: the request of a dependency is an expression

My `app.module.ts` contents:

```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }  from '../components/app';

@NgModule({
  imports:      [ BrowserModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```

Any idea how to solve this issue?

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/11580#issuecomment-282705332

**Comment by zishanj** [comment]
@ericmartinezr any idea about the error:

> This relative module was not found:
> 
> ./app/app.module in ./resources/assets/js/main.ts

Above module does exists in correct path

**Comment by zishanj** [comment]
@ericmartinezr I have tried you suggested solution to resolve the warning message but I am still receiving it.
