### ISSUE TITLE
Keep animation end state when using input params - make state() aware of the params

### ISSUE THREAD

**Issue by MrCroft** [angular/angular#17362]
**I'm submitting a:**
```
[x] feature request
```

**Current behavior**
When using input params, we have something like this in our animation code:
```
const zoomEffect = animation([
    animate('430ms ease-out', style({
        'transform': 'scale( {{ scaleFactor }} )'
    }))
], { params: { scaleFactor: '1' } });

export const magnifyAnimation = trigger('magnify', [
    transition('default => magnified', [ useAnimation(zoomEffect) ], { params: { scaleFactor: '1.3' } }), // <<< which we can also override from the component
    transition('magnified => default', [ useAnimation(zoomEffect) ], { params: { scaleFactor: '1' } })
]);
```
But the final state of the animation isn't kept. The element jumps back to original values as soon as the animation ends.
Normally, we'd also have:
```
    state('default', style({
        'transform': 'scale(1)'
    })),
    state('magnified', style({
        'transform': 'scale(1.3)'
    }))
```
^ but, since we use input params, we should also be able to tell state() about those input params.
As far as I know, there's no way to do that now. Seems to me that this renders input params unusable.

**Expected behavior**
**state()** should know about input params

**What is the motivation / use case for changing the behavior?**
I don't see the use of input params as long as **state()** doesn't know about those params, to be able to keep the animation end state, except maybe for temporary animations.

* **Angular version:** 4.2.0

**Comment by matsko** [comment]
https://github.com/angular/angular/commit/05472cb21be17d9f3ae526ea1a4d6ceb4cad5da7 added this to 5.0 and 4.x.
