### ISSUE TITLE
aio: Service worker duplicate updates

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#17368]
This is the sequence of the logs when two updates happened:

**The Update Now notification is displayed**

![screen shot 2017-06-09 at 19 30 47](https://user-images.githubusercontent.com/15655/26989277-5e06f584-4d4a-11e7-938c-fab0d6cec572.png)

**Click on the update link and page reloads**

![screen shot 2017-06-09 at 19 31 01](https://user-images.githubusercontent.com/15655/26989276-5e04b31e-4d4a-11e7-8afc-734423cbea2e.png)

**The Update Now notification is displayed a second time**

![screen shot 2017-06-09 at 19 31 12](https://user-images.githubusercontent.com/15655/26989275-5e021fdc-4d4a-11e7-897c-9058bd3425a9.png)

**Click on the update link and page reloads**

![screen shot 2017-06-09 at 19 31 24](https://user-images.githubusercontent.com/15655/26989274-5e013f2c-4d4a-11e7-8d41-848b313a8f44.png)

**Comment by gkalpak** [comment]
@alxhub, would 3093c55e9 have fixed this one too?

**Comment by petebacondarwin** [comment]
@gkalpak shall we close this one?
