### ISSUE TITLE
minlength validation for template-driven form not working on IE11

### ISSUE THREAD

**Issue by keyvhinng** [angular/angular#17366]
**I'm submitting a ...**  
[X ] bug report
[ ] feature request
[ ] support request 

**Current behavior**
minlength validation doesn't work on IE11. (Please refer the plunkr link for more details) 

**Expected behavior**
The input field should be invalid when the min length criteria is not valid. 
A red highlighting & tooltip message should appear showing that the input is not valid.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/58DEGjJmxdjiX3Xcl8EF?p=preview

**Please tell us about your environment:**
OS: Windows 7 Enterprise SP1

* **Angular version:** 
4.0.X

* **Browser:** 
IE 11.0.9600.18665
 
* **Language:**
TypeScript 2.3

**Comment by tytskyi** [comment]
@keyvhinng `minlength` attribute is not supported in IE 11, see https://caniuse.com/#search=minlength

**Comment by keyvhinng** [comment]
You're right. Thanks for your response
