### ISSUE TITLE
Bug(Animation): ":leave" transition does not animate from height: * to height 0 in Angular 4.2.0

### ISSUE THREAD

**Issue by macjohnny** [angular/angular#17363]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 
[ ] feature request
[ ] support request 
```
**Current behavior**
With Angular 4.2.0, the `:leave` transition does not animate the height property when starting with `height: "*"`. It does, however, animate, when starting with `height: "!"`
Example code from the [docs](https://angular.io/docs/ts/latest/guide/animations.html#!#automatic-property-calculation):
```
animations: [
  trigger('shrinkOut', [
    state('in', style({height: '*'})),
    transition('* => void', [
      style({height: '*'}),
      animate(250, style({height: 0}))
    ])
  ])
]
```

**Expected behavior**
According to the docs, https://angular.io/docs/ts/latest/guide/animations.html#!#automatic-property-calculation, it should should accept the `*` for automatic property calculation.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/yDHxaz?p=preview

**What is the motivation / use case for changing the behavior?**
Fix a regression bug, as this used to work in Angular 4.1.3

**Please tell us about your environment:**
any

* **Angular version:** 4.2.0

* **Browser:** all
 
* **Language:** Typescript 2.2.2

**Comment by macjohnny** [comment]
@matsko looks like a regression, as this used to work in Angular 4.1.3

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/15507#issuecomment-305074286

**Comment by macjohnny** [comment]
This issue is fixed with https://github.com/angular/angular/commit/185075d
See the updated plunkr: http://plnkr.co/edit/Hzx8W4?p=preview
