### ISSUE TITLE
Easy to break shrinkwrap

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#1737]
At present, the checked-in shrinkwrap file includes qq but our package.json does not, so they are out of sync.

Whenever someone changes package.json, it is easy to do the wrong thing with shrinkwrapping. They might not run the shrinkwrapper, or they might run it with unclean state in node_modules.

We should have some verification in the build that the files are in sync, and maybe also update the instructions so we are more clear on how the process works, for example, when do we update all our deps to head?

**Comment by alexeagle** [comment]
cc: @rkirov

**Comment by vicb** [comment]
@alexeagle the verification has been added in #2394, could we close this issue now ?

**Comment by IgorMinar** [comment]
#2394 makes sure that node_modules and shrinkwrap file are in sync not that package.json and shrinkwrap are in sync.

**Comment by alexeagle** [comment]
That's true, but I think it's less of an issue, since Travis and other users go from the shrinkwrap file, your change to package.json alone would be ignored and whatever you were relying on would break.
Also when I opened this issue, we had more issues with the shrinkwrap instructions being unreliable.
Should we commit to adding that verification? Or else we could close this.

**Comment by mhevery** [comment]
Sounds like this issue can be closed. Re-open if you feel otherwise.
