### ISSUE TITLE
_ngcontent-c0 Added to Style Rules, but not to correct DOM element

### ISSUE THREAD

**Issue by rgant** [angular/angular#17377]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
CSS rule is not applied to component because _ngcontent-c0 is not applied to the correct DOM element.

**Expected behavior**
CSS rule should apply to the `.mat-sidenav-content` div. Either because `_ngcontent-c0` attribute is applied to that element, or because the css rule isn't modified to include that attribute.

**Minimal reproduction of the problem with instructions**

app.component.ts:
```
@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.less']
})
export class AppComponent {  }
```

app.component.less:
```
.app-body .mat-sidenav-content {
    flex: 1;
    background-color: purple;
}
```

app.component.html:
```
<div fxLayout="column" fxLayoutAlign="start" class="app-wrp">
    ...
    <md-sidenav-container class="app-body">
        <!-- <aside> causes issues with sidenav positioning -->
        <md-sidenav #sidenav mode="over">
            Sidenav Here
        </md-sidenav>

        <main>
            <router-outlet></router-outlet>
        </main>
    </md-sidenav-container>
    ...
</div>
```

main.bundle.js style rule:
```
.app-body[_ngcontent-c0]   .mat-sidenav-content[_ngcontent-c0] {
  -webkit-box-flex: 1;
      -ms-flex: 1;
          flex: 1;
  background-color: purple;
}
```

Rendered DOM:
```
<md-sidenav-container _ngcontent-c0 class="app-body mat-sidenav-container mat-sidenav-transition">
    ...
    <div cdk-scrollable class="mat-sidenav-content" ng-reflect-ng-style="[object Object]" style="margin-left: 0px; margin-right: 0px; transform: translate3d(0px, 0px, 0px);">
        <main _ngcontent-c0>…</main>
    </div>
</md-sidenav-container>
```

If I apply the rule to the `main` tag it doesn't work because `.mat-sidenav-content` is what needs the flex style.

**Please tell us about your environment:**

```
$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.1
node: 8.0.0
os: darwin x64
@angular/animations: 4.2.0
@angular/common: 4.2.0
@angular/compiler: 4.2.0
@angular/core: 4.2.0
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.2.0
@angular/http: 4.2.0
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.0
@angular/platform-browser-dynamic: 4.2.0
@angular/router: 4.2.0
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.0
@angular/language-service: 4.2.0
```

* **Angular version:** 4.2.0

* **Browser:** all

 
* **Language:** TypeScript X.X

* **Node (for AoT issues):** `node --version` =  v8.0.0

This might be related to #16676

**Comment by rgant** [comment]
Plunker for the issue: http://plnkr.co/edit/3zegTvjpaDZ5JqKSOFnt

To be clear, to do the flex layout I believe that I must be able to apply a style rule to the .mat-sidenav-content div.

**Comment by tytskyi** [comment]
There is no bug, material component has css encapsulation which protects end user from simple overriding.

FIxed example: http://plnkr.co/edit/zJbk8sMzpj6lW6p1LIs6?p=preview 

Please check this article to see why: https://angular.io/docs/ts/latest/guide/component-styles.html#!#special-selectors

**Comment by rgant** [comment]
The bug here is that material sidenav has encapsulation turned off: https://github.com/angular/material2/blob/master/src/lib/sidenav/sidenav.ts#L330 but the style rule is still being modified to contain the selector.

**Comment by tytskyi** [comment]
You are right, but if you turn off it on the AppComponent then it will work as you expected.

http://plnkr.co/edit/qaWUX7Si07bvHpwAZ2Ds?p=preview

It means that AppComponent still prevents its own styles from leaking to not direct children

**Comment by tytskyi** [comment]
> https://github.com/angular/material2/blob/master/src/lib/sidenav/sidenav.ts#L330 but the style rule is still being modified to contain the selector.

And i see why it is done. Sidebar will project other component via `<ng-content>`. Which is dynamic content. Sidebar wants to style that dynamic content, that's why it must turn off encapsulation.

**Comment by rgant** [comment]
I don't understand encapsulation at all. If all it does is mangle styles then why would it exist? If the only way to style your app is to turn it off, why ever turn it on? It must do something/have some reason that I am not following. So my solution is just to take my styles out of Angular and thus avoid the mangling without the risk of changing a default setting that definitely has ripple effects (sidenav turns it off and it breaks things) that I don't want to be responsible for. 

If the mat-sidenav-container component has encapsulation: ViewEncapsulation.None then I expect that the styles build will note that and not add `[_ngcontent-c0]` to style rules for this component. I don't know how it would know that, but it seems to me that if it cannot, then it shouldn't just change things that can introduce breakage.

I realize I'm using a cutting edge tool chain and there will be problems, but I really hope you guys find a better solution for this.

**Comment by tytskyi** [comment]
@rgant i am sorry you feel uncomfortable with styles encapsulation. I will try to clarify. 

Quote from Angular documentation.

> **/deep/**
> Component styles normally apply only to the HTML in the component's own template.

> Use the `/deep/` selector to force a style down through the child component tree into all the child component views. The `/deep/` selector works to any depth of nested components, and it applies to both the view children and content children of the component.

Which says that default encapsulation strategy allows to style only elements that appear in component's own template.

In your particular example you want to style elements that do not belong to `AppComponent`, but they do belong to other's component template. This is absolute valid solution to turn off encapsulation for this component, use `/deep/` selector, or external stylesheet `styles.css` (as you chosen). Because you want to style 3rd party component. 
Normally if it would be your own side-nav component, then you would go directly to it and edit styles.

Default ViewEncapsulation becomes useful when you write your own component and style it from zero.  There is the problem in css that styles of 1st component will overlap/override styles of 2nd component. In the world without css encapsulation there is number of css methodologies like OOCSS, ACSS, BEM, SMACSS etc to solve this problem. With encapsulation you may choose to not use any of those and still have isolated styles for components.

So for example you can write as simple selectors as `span, .btn` etc. And they will be styled only inside **this** particular component.

**Comment by soniar4i** [comment]
As /deep/ and >>> are now deprecated what are the alternatives now to style 3rd party component? Is any other solution available right now? I'm having the same issue but I can't modify the child item since is a 3rd party.

Thanks!

**Comment by tytskyi** [comment]
@soniar4i for now use `::ng-deep`, that will also be deprecated, but alternative will be provided by the time it is needed

**Comment by JohnyDaison** [comment]
So ng-deep is now deprecated. What is the alternative provided?

**Comment by mlc-mlapis** [comment]
@JohnyDaison ... it's exactly as @tytskyi said. https://github.com/angular/angular/issues/17377#issuecomment-320909996

What else would you like to hear? The specs are going in the direction of CSS Custom Properties as Shadow DOM but in the same moment there is still the requirement for IE support so no way in the actual moment.

**Comment by tytskyi** [comment]
1 year past since then. I now use file `global.scss` where i add global styles in old-school style. I don't use any `ng-deep` things any more.
