### ISSUE TITLE
Prevent double-initialization in generated Dart code

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#1738]
For example

```
export class Dependency {
  constructor(public key: Key) {
    this.key = key;
  }
}
```

results in

```
class Dependency {
  Key key;
  Dependency(this.key) {
    this.key = key;
  }
}
```

Which uses the "initializing formal constructor parameter" `this.key` and then explicitly sets `this.key = key;` This could be collapsed to:

```
class Dependency {
  Key key;
  Dependency(this.key);
}
```

**Comment by kegluneq** [comment]
@vsavkin I'm not sure you're the right person to assign this to, but it looks like you have some background on the generation here.

Feel free to reassign, unassign, etc.

Thanks!

**Comment by mhevery** [comment]
Obsolete, fixed in ts2dart
