### ISSUE TITLE
Animations should still work with values without the `s`

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#17387]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

An animation with `0.2s 10 ease-out` doesn't work on Angular 4.2 and it used to.

**Expected behavior**

That animation should keep working and perhaps print a deprecation message or something.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/nX25SqINJD2Id1NRLPgJ?p=preview

**Comment by matsko** [comment]
This was never documented and intended to work this way. It was just behaved this way in Angular2, but Angular4 fixed the issue. Sorry.
