### ISSUE TITLE
Upgrade to Angular 4.2 causes Ionic Error: Cannot find module '@angular/tsc-wrapped/src/tsc'

### ISSUE THREAD

**Issue by miltonhowe** [angular/angular#17380]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
after updating to Angular 4.2,  ionic serve fails with the following message:
Error: Cannot find module '@angular/tsc-wrapped/src/tsc'

**Expected behavior**
ionic serve should build and run the project as it did/does with Angular 4.1.3 previously

**Minimal reproduction of the problem with instructions**
Install Angular 4.2

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
global packages:
    @ionic/cli-utils : 1.3.0
 You have been opted out of telemetry. To change this, run: cordova telemetry on. 7.0.1
    Ionic CLI        : 3.3.0

local packages:
    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : You have been opted out of telemetry. To change this, run: cordova telemetry on.  android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:
    Node       : v6.10.3
    OS         : Windows 8.1
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

* **Angular version:** 4.2

**Comment by IgorMinar** [comment]
I verified that new and existing non-ionic projects don't have this problem.

Maybe your node_modules got corrupted during the upgrade? I suggest that you verify that you have `node_modules/@angular/tsc-wrapped` at the same version as all the other angular core packages.
