### ISSUE TITLE
compiler ngc output changed with 4.2.0

### ISSUE THREAD

**Issue by axtho** [angular/angular#17381]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
compiling a module with ngc (using 4.2.0), which I am linking (yarn link) to the main app, changes the output (compared to 4.1.3) to the following structure:
<img width="264" alt="bildschirmfoto 2017-06-09 um 21 56 02" src="https://user-images.githubusercontent.com/11181579/26992410-df4964ba-4d5e-11e7-8702-232f77b239d3.png">

It also creates a summary file for each ts file (e.g. index.ngsummary.ts), which it did not do before.

**Expected behavior**
Using 4.1.3 results in the intended output, like so:
<img width="314" alt="bildschirmfoto 2017-06-09 um 21 58 19" src="https://user-images.githubusercontent.com/11181579/26992429-f720630e-4d5e-11e7-854c-ffc92a7bdd3b.png">

**Minimal reproduction of the problem with instructions**
The tsconfig file that ngc reads looks like this:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./src",
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "./dist",
    "sourceMap": true,
    "target": "es5",
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```
The command to compile is `yarn build` from the package.json:
```
"scripts": {
    "clean": "rm -rf ./aot/* && rm -rf ./dist/* && yarn clean:postbuild",
    "clean:postbuild": "find ./src/ -type f -iname *.ngsummary.json -delete && find ./src/ -type f -iname *.ngfactory.ts -delete",
    "build": "yarn run clean && ngc -p tsconfig.json && yarn run clean:postbuild && yarn lint",
    "lint": "tslint \"**/*.ts\" -c tslint.json -e \"**/blueprints/*/files/**/*.ts\" -e \"node_modules/**\" -e \"tmp/**\" -e \"dist/**\"",
    "install:dep": "yarn link"
  },
```

**What is the motivation / use case for changing the behavior?**
I am confused as to why the compiler has changed the output behaviour. I have not read a doc that explains what needs to be done instead. The tsconfig file already uses `baseUrl`, but it seems to be ignored, or otherwise interpreted.

**Please tell us about your environment:**
OS X 10.12.5
PHPStorm 2017.4
yarn

* **Angular version:** 2.0.X
4.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.3.4

* **Node (for AoT issues):** `node --version` =   
8.0.0

**Comment by axtho** [comment]
This is fixed with the latest update:

```
"@angular/compiler-cli@^4.0.0":
  version "4.2.2"
  resolved "https://registry.yarnpkg.com/@angular/compiler-cli/-/compiler-cli-4.2.2.tgz#bc5fa52e34000b678a3c8189ffe2da5fc0017501"
  dependencies:
    "@angular/tsc-wrapped" "4.2.2"
    minimist "^1.2.0"
    reflect-metadata "^0.1.2"

"@angular/compiler@^4.0.0":
  version "4.2.2"
  resolved "https://registry.yarnpkg.com/@angular/compiler/-/compiler-4.2.2.tgz#10c168f8a156397f07ae6ef83a0911e01ed264f8"
  dependencies:
    tslib "^1.7.1"

```

**Comment by pain0486** [comment]
I'm encountering this exact issue on version 5. I run `"node_modules/.bin/ngc" -p tsconfig.json` in the root directory (at the same level as node_modules  folder) and I get dist/src and dist/node_modules
What I want is everything under dist/src to be in dist

compiler versions:
@angular/compiler-cli@^5.2.0": version "5.2.3"
@angular/compiler@^5.2.0": version "5.2.3"
