### ISSUE TITLE
Document correct practice for @View(directives) list in large apps.

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#1739]
Angular2 introduces the 'directives' list in the @View annotation where the component author must list all the directives used in the template.

The default option is to list all directives explicitly for each @View().  This option has significant maintenance overhead by requiring template authors to list out all of the directives they use, include simple directives such as ```If```. This task is more complicated because there is no defined mapping between selector name and class name: e.g. the author uses ```*if``` in their template and now needs to know that ```*if``` is implemented by the ```If``` class.

A second option, presented by @yjbanov, is to extend the @View annotation with an app-specific annotation (e.g. @MyAppView). The child annotation would list common components, saving the template author from the boilerplate of listing basic components. The downside here is that using custom annotations makes static analysis of the source code harder.

**Comment by pkozlowski-opensource** [comment]
@jbdeboer I've opened similar (identical ?) issue some time ago, see https://github.com/angular/angular/issues/1293 

Maybe it would be beneficial to centralise the discussion in one place?

**Comment by jbdeboer** [comment]
Yes. Closed as dup.

In this issue I was trying to be very open to discussion. If the answer is "Yes, the Angular framework demands a verbose list", that is a possible outcome, but we need to be very open about it.
