### ISSUE TITLE
Promise of provider does not work (404 - bad request) for services stored in a subfolder if the file name contains a space 

### ISSUE THREAD

**Issue by alex75it** [angular/angular#17401]
**I'm submitting a ...**  

[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request 

**Current behavior**
When a service is set in a subfolder AND the file name contains a space it is not found by "provider" section of app.modules.ts.
"tsc" compile without errors but there is an error at runtime: Uncaught (in promise) error: Error: No provider for [service name]!

**Expected behavior**
The service should be found and served without any error.
Changing the name of the file replacing the space with an uderscore and correcting the name in the Appmodule.ts and tin the component.ts that use it solve the problem.
It also works if the file is on the root "app" folder.

**Minimal reproduction of the problem with instructions**
Plunker: http://plnkr.co/edit/PdsH0cZ67QXtgncF1BmB?p=info

Using src/services/MyExample.service.ts works
Using src/services/my example.service.ts does not work

**What is the motivation / use case for changing the behavior?**
it should work also with files that contain a space in the name.

**Please tell us about your environment:**
Local: Windows 10, 
Plunker with latest Angular (4.x)

* **Angular version:**
Latest: 4.0.23

* **Browser:**
Chrome (latest) | Maxthon
 
* **Language:** 
TypeScript
ES5

* **Node (for AoT issues):** `
node --version` =   6.0.46

**Comment by alex75it** [comment]
Having a service file in a sub directory with a space in the name cause a Bad Request 404.
Plunker fails just because a file with a space in the name exists.
In a real environment the error is relative only to the specific service file not found.

Using the "services/MyExample.service.ts" file works.
Using the same file renamed in "My Example.service.ts" and changing thew path accordingly in app.ts and myComponent.component.ts make impossible to find it ("promise" fail).

**Comment by IgorMinar** [comment]
this is a typical web behavior and is outside of the scope of Angular.

**Comment by alex75it** [comment]
Hi Igor,
what do you mean by "typical web behavior"?
