### ISSUE TITLE
docs(aio): Style Guide proposal: Input-Set

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#17402]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Prelude**
Back in January I open an issue in [`codelizer`](https://github.com/mgechev/codelyzer) repo (mgechev/codelyzer#222) talking about something like this. I'm still thinking about how this really should be, mostly the `template-get` pattern. However, I would like to open this issue presenting the `Input-set` patter as a Style Guide proposal.

**Expected behavior**
I made a post in dev.to about this.
[Input-Set pattern for Widgets in Angular](https://dev.to/michaeljota/input-set-pattern-for-widgets-in-angular)
It have the title _for Widgets_ but, that just for the convention I manage between the posts, but this could be also aplicable for components. 

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/qQMk8kCH0wWp3yznE6MX?p=preview

**What is the motivation / use case for changing the behavior?**
- Separations of concerns. The template should not be aware of the properties that are being `input`ed, nor the properties that this have. This should concern only to the Component.
- Composability. This patterns allows for the component to compose special properties for the template to consume. 

In the above post you would certainly find some use cases and examples. 

**Please tell us about your environment:**
- Windows 10 CU
- VSCode 1.13 (May's update)

* **Angular version:** +2

* **Browser:** [ all ]
 
* **Language:** [ TypeScript 2.X | ES6/7 ]

**Comment by wardbell** [comment]
Thanks for your thoughts on this. As the editor, I'm declining your suggestion on the grounds that, while it might be a guideline _for you personally_, we are disinclined to be _that_ opinionated on the subject in our Angular style guide.   

Editors have to make choices. I made mine. Thanks again.

**Comment by michaeljota** [comment]
I really glad you take it in consideration. Thanks to you.
