### ISSUE TITLE
ɵDomAnimationEngine and ɵNoopAnimationEngine module missing in animations 4.2.1

### ISSUE THREAD

**Issue by cortopy** [angular/angular#17400]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After upgrading `platform-browser` and `animations` to 4.2.1 I get the following error

```
WARNING in ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
329:2-21 "export 'ɵDomAnimationEngine' was not found in '@angular/animations/browser'

WARNING in ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
382:43-63 "export 'ɵNoopAnimationEngine' was not found in '@angular/animations/browser'

ERROR in /mypath/node_modules/@angular/platform-browser/animations/src/providers.d.ts (8,119): Module '"/mypath/node_modules/@angular/animations/browser"' has no exported member 'ɵDomAnimationEngine'.

```

**Expected behavior**
No typescript errors

**Minimal reproduction of the problem with instructions**
Create angular cli project with 4.2.1 versions of angular packages and run `ng serve`

**Please tell us about your environment:**
Linux

* **Angular version:** 2.0.X
4.2.1
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.3.4

**Comment by dubeboy** [comment]
Hy @cortopy  man I have the same problem did you manage to fix it?

**Comment by Parziphal** [comment]
@dubedoy I installed v4.1.3 and it worked again.

**Comment by cortopy** [comment]
new release 4.2.2 fixed this issue for me

**Comment by jessycormier** [comment]
@cortopy, the new version doesn't fix the issue.

**Comment by Subayan** [comment]
@Parziphal it worked for me, Thanks !

**Comment by fulfillGit** [comment]
As for me, the new version doesn't work correctly.
4.1.3 worked correctly

**Comment by lincolngup** [comment]
@angular/animations 4.2.2 was failing with the message
``
@angular/platform-browser/animations/src/providers.d.ts (8,119): Module @angular/animations/browser has no exported member 'ɵDomAnimationEngine'
``
The issue was resolved by reverting to @angular/animations 4.1.3

**Comment by GaryB432** [comment]
I was surprised when my co-worker built our project and this blew up.  Scrambling and finger-pointing ensued.  I'm afraid I might be missing something about semantic versioning.  Can anyone point me to some **opinionated best practices** for my package.json dependencies? Should we not be using the carets? tildes? for production? I don't think I want to lock down versions because bug fixes.

Also what is that first character of that missing exported member?  is that a theta or something?  Why would someone use such a character in a member name? I'm sure I'm missing some smart reason.

**Comment by nheinbaugh** [comment]
I am seeing both 4.2.2 and 4.1.3 fail.

**Comment by justinmnoor** [comment]
Same issue here with 4.2.2.

I get this error:

`ERROR in /home/ubuntu/myapp/node_modules/@angular/platform-browser/animations/src/providers.d.ts (8,119): Module '"/home/ubuntu/myapp/node_modules/@angular/animations/browser"' has no exported member 'ɵDomAnimationEngine'.`

**Comment by CanadianEngineer** [comment]
I'm getting the same issue with 4.2.2, and 4.1.3. Here's my dependency dump

```
"dependencies": {
		"@angular/animations": "^4.1.3",
		"@angular/common": "^4.1.3",
		"@angular/compiler": "^4.1.3",
		"@angular/core": "^4.1.3",
		"@angular/forms": "^4.1.3",
		"@angular/http": "^4.1.3",
		"@angular/material": "^2.0.0-beta.6",
		"@angular/platform-browser": "^4.1.3",
		"@angular/platform-browser-dynamic": "^4.1.3",
		"@angular/router": "^4.1.3",
		"bootstrap": "^4.0.0-alpha.6",
		"chart.js": "^2.6.0",
		"core-js": "^2.4.1",
		"d3": "^4.9.1",
		"font-awesome": "^4.7.0",
		"jquery": "^3.2.1",
		"material-design-iconic-font": "^2.2.0",
		"ng2-charts": "^1.6.0",
		"ng2-toasty": "^4.0.0",
		"ngx-bootstrap": "^1.7.1",
		"npm": "^5.0.3",
		"process-nextick-args": "^1.0.7",
		"rxjs": "^5.4.0",
		"tether": "^1.4.0",
		"tree-model": "^1.0.6",
		"util-deprecate": "^1.0.2",
		"zone.js": "^0.8.11"
	},
	"devDependencies": {
		"@angular/cli": "^1.1.0",
		"@angular/compiler-cli": "^4.1.3",
		"@compodoc/compodoc": "^1.0.0-beta.9",
		"@types/jasmine": "^2.5.51",
		"@types/node": "^7.0.27",
		"codelyzer": "^3.0.1",
		"html-webpack-plugin": "^2.28.0",
		"jasmine-core": "^2.6.2",
		"jasmine-spec-reporter": "^4.1.0",
		"karma": "^1.7.0",
		"karma-chrome-launcher": "^2.1.1",
		"karma-cli": "^1.0.1",
		"karma-coverage-istanbul-reporter": "^1.3.0",
		"karma-firefox-launcher": "^1.0.1",
		"karma-jasmine": "^1.1.0",
		"karma-jasmine-html-reporter": "^0.2.2",
		"protractor": "^5.1.2",
		"ts-node": "^3.0.4",
		"tslint": "^5.4.2",
		"typescript": "^2.3.4",
		"webpack": "^2.6.1",
		"webpack-dev-server": "^2.4.5"
	}
```

**Comment by jromero-onclick** [comment]
Not working for me too

**Comment by drazik** [comment]
Using `"@angular/animations": "4.1.3"` fixed the issue for me. Be sure that you use **fixed** version, without `^`

**Comment by CanadianEngineer** [comment]
I fixed my error last night. I ran `npm outdated` and saw a LOT was out of date. Ran `npm update && npm start` fixed it. I was running `npm update && npm install && npm start` IIRC. Does installing undo any changes an update does?

@drazik Im not too sure if I tried it with or without `^`.

**Comment by gigeos** [comment]
Indeed set version `^` allow npm to get latest version for same major version. 

e.g: `"@angular/animations": "^4.1.3"` allow npm to get version 4.x.x like 4.2.2 which has an issue;

**Comment by brud** [comment]
fixed `4.1.3` version didn't help, i can't run my project for 5 hours :(

**Comment by drazik** [comment]
Did you try `rm -rf node_modules && npm install` ?

**Comment by CanadianEngineer** [comment]
To expand on @drazik's suggestion
`rm -rf ~/.npm`
`rm -rf ${workspace}/node_modules`
`npm install`
`npm update`
`npm start`

**Comment by itomek** [comment]
Thanks @CanadianEngineer, this worked for me as well. I didn't change any incrementing flags (i.e., ^ or ~) and everything compiled fine.

```
$ npm outdated
$ npm up
```
> I fixed my error last night. I ran npm outdated and saw a LOT was out of date. Ran npm update && npm start fixed it. I was running npm update && npm install && npm start IIRC. Does installing undo any changes an update does?

@drazik Im not too sure if I tried it with or without ^.

**Comment by YegorKh** [comment]
Just done
npm update
Than
npm start

And now everything works fine. 
I had @angular/platform-browser-dynamic@4.0.0
after update
@angular/platform-browser-dynamic@4.2.3

**Comment by MadDeveloper** [comment]
@YegorKh, indeed it works, just don't forget the save option when you update, `npm update --save`, in order to have the `package.json` up to date.

**Comment by MadDeveloper** [comment]
@YegorKh, it works for me thanks! For those who have a team project, don't forget the save option in order to keep the `package.json` up to date: `npm update --save`.

**Comment by angeloneacsu** [comment]
combined @angular/material@2.0.0-beta.7 and @angular/material@4.1.3 does solved my issue

**Comment by italojs** [comment]
i fixed it  running -> ` npm install '@angular/animations"@4.1.3' --save `

**Comment by lfelipeqn** [comment]
After installing @angular/animations@4.1.3 as suggested by @Parziphal it worked.

**Comment by jaycrz** [comment]
Using `"@angular/animations": "4.1.3"` without the '^' works to me.

**Comment by benishak** [comment]
version 4.3.3 have this issue

**Comment by benishak** [comment]
i come from clean install new project

**Comment by sebrojas14** [comment]
....so?

**Comment by AndersGerner** [comment]
Tried 4.1.3 and now it works for me! 😃

**Comment by milleraundra** [comment]
Same problem with 4.3.5. Changing back to 4.1.3 solved it.

**Comment by yugi03** [comment]
Same issue was in 4.3.6. I downgraded it to 4.1.3 and now its working.

**Comment by sublimator** [comment]
Ugh. Thanks all

**Comment by zee92** [comment]
**<agm-map [latitude]="lat" [longitude]="lng">
<agm-map-marker [latitude]="lat" [longitude]="lng"> 
it is showing map but it not showing markers on map. need help to solve the problem. in its old version it was showing through this statement but now it is deprecated.

<sebm-google-map-marker [latitude]="lat" [longitude]="lng"></sebm-google-map-marker> **

**Comment by zee92** [comment]
it works through

<agm-marker [latitude]="lat" [longitude]="lng"> </agm-marker>

**Comment by JinseokJang** [comment]
downgraded from 4.4.3 to 4.1.3 and resolved the issue. thk

**Comment by monkeydj** [comment]
I have node v8.4.0, npm v5.3.0
my project is also using ionic v3.6.0, ionic-app-scripts v2.1.4 with angular v4.1.3
and no solution seems to work
anyone doing the same thing as me?
ps: versioning is always my main problem, *sigh...

**Comment by rifrandz** [comment]
I downgraded to 4.1.3 and it's working.
