### ISSUE TITLE
Router loadChildren is not working with Angular Hybrid

### ISSUE THREAD

**Issue by aminpaks** [angular/angular#17407]
**I'm submitting a bug in either the logic of `router` or `upgrade` ecosystem of Angular.**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Once the module is being lazy loaded and rendered, `UpdgradeComponent` wants to get the injector, it will never resolve the injector from `AngularJS` and the root module and fail.
```
this.$injector = injector.get($INJECTOR); <-- Never resolves
```

**Expected behavior**
Upgraded component works like the root which is the parent.

**Minimal reproduction of the problem with instructions**
You can take a look at this example that created.
Click on `All Ng1` and checkout the console.
http://embed.plnkr.co/FSH7XOlSeRKXJRkUmJGD/

* **Angular version:** 4.1.3 and 1.6

* **Browser:** all
 
* **Language:** TypeScript 2.X

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

I think this is a support issue that should go to StackOverflow. The example could be simplified though as it's a bit confusing. Maybe you could simplify the example even more and make it extremely explicit what is happening. If you don't get an answer over there, please create a new issue with more of a description that walks through the example showing what you're expecting and what you're getting.
