### ISSUE TITLE
QueryList<> interface is not iterable in TypeScript, AGAIN

### ISSUE THREAD

**Issue by tx8821** [angular/angular#17414]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

When I try to iterate the QueryList (e.g. ContentChildren), I get this error: `[ts] Type must have a '[Symbol.iterator]()' method that returns an iterator.`

This is an error:
![tserror](https://user-images.githubusercontent.com/22138773/27025596-24fd3e3c-4f6c-11e7-8b3d-5d3c8aedc7be.png)

I think the issue #7022 is incorrectly closed, as the problem is still present. Even though I'm targeting the ES2015, I still can't use for...of loop. Please fix this.

Note that the docs specifically mention: 

> Implements an iterable interface, therefore it can be used in both ES6 javascript for (var i of items) loops as well as in Angular templates with *ngFor="let i of myList".

**Angular CLI: 1.0.3
Angular: 4.1.2
Typescript: 2.2.2
VS Code 1.13.0**

This is my tsconfig.json:

{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "alwaysStrict": true
  }
}

This is my "tsconfig.app.json:

{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "baseUrl": "",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

**Comment by vicb** [comment]
I don't think there is a way to make TS happy when targeting ES5 (not all browser Angular supports support ES2015 - more specifically `Symbol` here)

If you find a good please send a PR.

In the meantime you can probably cast the list
```ts
class QueryList<T>{
  //...
}

function iter<T>(l: QueryList<T>): QueryList<T> & Iterable<T> {
  return <any>l;
}  

let ql: QueryList<number> = new QueryList();

for (let item of iter(ql)) {
    // item is a number 
}
```

**Comment by oliverjanik** [comment]
Can this be made available when targeting ES5 and downlevelIteration is on?
