### ISSUE TITLE
process for updating dependencies

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#1741]
Now that we are using shrinkwrap, we lock our npm dependencies, and only through a periodic manual process will we ever get bugfixes and improvements in newer versions.

We should do this periodically and ideally automate it, so we just get a PR with a green travis build and rubber-stamp the merge. Such a practice is called "continuous integration" :)

**Comment by alfaproject** [comment]
Can I suggest https://greenkeeper.io/ ?

**Comment by splincode** [comment]
@alexeagle Is the issue relevant?

**Comment by alexeagle** [comment]
Yes, we've been planning to use renovate but haven't gotten time yet...

**Comment by alexeagle** [comment]
Dupe of #20860 (yes we should still do it...)
