### ISSUE TITLE
The initial style() is applied with delay, when using stagger()

### ISSUE THREAD

**Issue by MrCroft** [angular/angular#17412]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
When using stagger(), the initial style() is applied on each individual item, *after* the stagger delay.

**Expected behavior**
The initial style() should be applied to all matching items before stagger() kicks in.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/MWC78V9Hbukl1xD25wW2?p=preview

**Please tell us about your environment:**

* **Angular version:** 4.2.1

* **Browser:** all

**EDIT:** Seems that plnkr isn't working anymore... Noticed this yesterday (June 14th) `GET https://run.plnkr.co/DYWkt10odM0YhhTj/tslib 404 ()` and it's still broken. So, the above example isn't working anymore.

**Comment by maxschwarzmueller** [comment]
Using Angular 4.2.2, the example from [https://angular.io/api/animations/stagger](https://angular.io/api/animations/stagger) also is not working as expected (so do all other tries of getting stagger to work).
All items are shown in the "final position" right from the start and then simply moved into that position via the staggered animation again. Expected behavior of course would be for the elements to not start in their ending state but be animated there.

**Comment by MrCroft** [comment]
@maxschwarzmueller Looking over the [code](https://github.com/matsko/ng4-animations-preview) of [this demo](http://slides.yearofmoo.com/ng4-animations-preview/demo/), I've managed to make it work with something like this:
```
export const fadeInStagger = trigger('fadeIn', [
    transition(':enter', [
        // style({ /* */ }), // << This would actually be applied on the element the trigger is on
        query('.item-class', [ // << this sets initial style on the children we target
            style({ 'opacity': '0' })
        ]),
        query('.item-class', [ // << animate the children that matches the selector
            stagger(100, animate(400, style({ 'opacity': 1 })))
        ])
    ])
]);
```
for:
```
<my-carousel @fadeIn>
    <div class="item-class"
        *ngFor="let item of items">
        <img [src]="item.image" alt="" />
    </div>
</my-carousel>
```
It seems that we also have to query for setting initial style.
Not very intuitive, I'd say.
@matsko In the light of the recent "discovery", I think this is not an issue anymore, but rather the docs need a bit more improvement?

**Comment by matsko** [comment]
Thank you @MrCroft for this. Here's the fix for that https://github.com/angular/angular/pull/17534

**Comment by MrCroft** [comment]
Just realized... my previous comment isn't really related to the issue. Just got tangled in all the things I keep trying lately, with the new stuff that the animations package provides us. Sorry about that @maxschwarzmueller

**Comment by maxschwarzmueller** [comment]
Okay, I misunderstood you, too then ;). Still, the behavior seems to be unintended, you shouldn't have to query the element and change the style before you stagger() in my opinion.

**Comment by MrCroft** [comment]
@maxschwarzmueller  Yes, definitely.
It seems it's fixed now, as Matias mentioned above. Hopefully, it will be published with the next update.
