### ISSUE TITLE
aio: search gives inconsistent search results while entering search query

### ISSUE THREAD

**Issue by fredrik-lundin** [angular/angular#17417]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When searching in the docs, some results show up when you start typing the word, then stops showing up when you typed a part of it, and finally shows up again.

A concrete example is when searching for `trackByFunction`. Up until "TrackB" a result for the `trackByFunction` api docs shows up in the result. When the search query is at "TrackBy", the result is gone. By adding the next letter, so we have "TrackByF", it is showing up again.

**Expected behavior**
The result should show as long as the query string matches what you are searching for

**Minimal reproduction of the problem with instructions**

1. Go to [https://aio-staging.firebaseapp.com/docs](https://aio-staging.firebaseapp.com/docs)
2. Type _TrackB_ in the search bar and notice that you can see the TrackByFunction api docs as a result
3. Type _TrackBy_ and notice how it's gone
4. Type _TrackByF_ and notice how it's back again

![aio-serach-problem](https://user-images.githubusercontent.com/5526934/27029573-319d396a-4f69-11e7-946a-0e49fac1e706.png)

**What is the motivation / use case for changing the behavior?**
Users might miss out on their search results because of this

**Please tell us about your environment:**

- Windows 7

**AIO version:**
- aio-staging build: Version 4.2.1-build.31497+sha.f7422a9.

**Browser:** 

- Chrome (Version 58.0.3029.110 (64-bit))
- Internet Explorer 11 (version 11.0.42)
- Firefox 52.1.2 (32-bit)

**Comment by gkalpak** [comment]
It's true 😳

**Comment by m0uj** [comment]
Please provide a Plunker !

**Comment by fredrik-lundin** [comment]
@m0uj this is an issue on the deployed staging version of the new angular.io site that the angular team is developing, so you can see it on [https://aio-staging.firebaseapp.com/docs](https://aio-staging.firebaseapp.com/docs)

**Comment by m0uj** [comment]
I see, thanks @fredrik-lundin

**Comment by petebacondarwin** [comment]
This appears to be a "feature" of the Lunr search index. Looking into it...

**Comment by fredrik-lundin** [comment]
It's indeed the actual Lunr search that gives back the wrong result:

![serviceworkercall](https://user-images.githubusercontent.com/5526934/27035577-219bdb20-4f82-11e7-8bd0-6812d587d158.PNG)

**Comment by petebacondarwin** [comment]
I am going to upgrade to the latest Lunr and then use a more fine grain query, where I can attach wildcards

**Comment by fredrik-lundin** [comment]
Just noticed that there are still problems with the search results. I was looking for the test guide named _Testing_. It's being found when the input is on _Test_, but fails for _Testi_ and _Testing_.

Should I open a new issue for this or should we keep it here?
@petebacondarwin , @gkalpak

**Comment by gkalpak** [comment]
I believe the underlying issue is the same as #17545 (for which @petebacondarwin has a PR in progress). Let's track it there.

**Comment by fredrik-lundin** [comment]
Yes that looks like the same issue indeed - missed that issue! @gkalpak
