### ISSUE TITLE
"no provider for HeroService" error in current tutorial

### ISSUE THREAD

**Issue by seawolf42** [angular/angular#17428]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the [Heroes tutorial part 5 (routing)](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html), "Add Heroes to the Dashboard" -> "Get Heroes", you are missing a line of code. If you follow the tutorial exactly you receive a JS error: `ERROR Error: Uncaught (in promise): Error: No provider for HeroService!`

**Expected behavior**
No error, and the demo works as expected.

**Minimal reproduction of the problem with instructions**
Described above (current behavior). The fix is to add `providers: [ HeroService ]` in the component definition.

**What is the motivation / use case for changing the behavior?**
Complete the tutorial without unexpected errors.

**Please tell us about your environment:**
all environments

* **Angular version:** 2.0.X
all 2.0.X versions

* **Browser:**
all
 
* **Language:**
all

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by ericmartinezr** [comment]
If you followed the tutorial you'd have found these lines under **Create AppComponent**

>- Add HeroService to the providers array of AppModule because you'll need it in every other view.
>- Remove HeroService from the HeroesComponent providers array since it was promoted.

Even right under the section you mentioned you can find the section **Sharing the HeroService** where you can read the following statement

>Earlier, you removed the HeroService from the providers array of HeroesComponent and added it to the providers array of AppModule. That move created a singleton HeroService instance, available to all components of the app. Angular injects HeroService and you can use it in the DashboardComponent.

**Comment by seawolf42** [comment]
Embarrassing oversight on my part. Thanks!

jeff
