### ISSUE TITLE
Optional and SkipSelf marked parameters can not be used together with null union type

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#17426]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`constructor(@Optional() @SkipSelf() parentModule: LogModule|null) {` fails with

> ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 5:53 in the original .ts file), resolving symbol LogModule in expression-form-not-supported/src/app/log.module.ts
> 
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'expression-form-not-supported/src'
>  @ ./src/main.ts 4:0-74
>  @ multi ./src/main.ts

when building with AOT.

`ng build --aot --prod`

**Expected behavior**
Should not fail.

**Minimal reproduction of the problem with instructions**
https://github.com/CSchulz/angular-expression-form-not-supported

Compile with `ng build --aot --prod`

**What is the motivation / use case for changing the behavior?**
TSLint has a type check rule for finding not needed conditions. If null is not added, it complains of the not needed condition.

Marking it as optional parameter is not "correct", because the definition of the [Decorator](https://github.com/angular/angular/blob/a80ac0a8d3238f483a05252c437d4b321c42f5c7/packages/core/src/di/metadata.ts#L72) tells it injects null instead of undefined.

**Environment:**
@angular/cli: 1.1.1
node: 6.10.2
os: darwin x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

* **Browser:** Chrome 56
 
* **Language:** TypeScript 2.3.4

**Comment by chuckjaz** [comment]
Thanks for reporting this issue. Luckily it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

This was fixed in 4.2
