### ISSUE TITLE
Bind to child component before view rendered

### ISSUE THREAD

**Issue by Twois** [angular/angular#17427]
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**What is the motivation / use case for changing the behavior?**

Prevent redundant markup.

* **Angular version:** 4.0.X

Angular should be able to bind property from parent component to children components, before view rendered.

`<grid-header [grid]="grid">
    <grid-header-item fxFlex="75px" name="Level"></grid-header-item>
    <grid-header-item fxFlex name="Type"></grid-header-item>
    <grid-header-item fxFlex name="Stats"></grid-header-item>
</grid-header>`

In this case, grid-header component should be able to forward the grid object before viewInited. Now ViewChildren and contentChildren decorators can be use to pass the property to the child component, but there are many case when the AfterViewInit lifecycle hook is too late. For example, when the passed data is an object an we want to use it's method in the child compont's template.

grid-header-item component markup:

`<span class="item" (click)="grid.onSortBy(name);">
    {{name}} <span *ngIf="grid.sort == name" class="fa" [ngClass]="grid.getDirection(name)"></span>
</span>`

**Comment by pkozlowski-opensource** [comment]
@Twois it is not very clear from your description on what you are after. Could you try to prepare a very minimal plunker with a real-life use-case? It would help us to better understand this part:

> For example, when the passed data is an object an we want to use it's method in the child compont's template.
