### ISSUE TITLE
Synchronize release cadence of Angular and Angular-CLI whenever possible

### ISSUE THREAD

**Issue by fmorriso** [angular/angular#17425]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, Angular and Angular-CLI are on different release cadences.

**Expected behavior**

Angular and Angular-CLI released (whenever possible) at about the same time.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

The benefit would be that anytime a `ng new` command is executed, the newest released editions of Angular will be referenced in the generated `package.json` file. 

I realize this may not always be possible/desirable, but to whatever extent this is feasible, it would be greatly appreciated by at least this developer.

**Please tell us about your environment:**

* **Angular version:** 4.1.3

Angular-CLI 1.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

* **Node (for AoT issues):** `node --version` =   7.10.0

**Comment by trotyl** [comment]
The version used in `package.json` is `^4.0.0`, it's capable for auto-matching the latest 4.x version, there is no hard-coding for that.

**Comment by IgorMinar** [comment]
> anytime a ng new command is executed, the newest released editions of Angular will be referenced in the generated package.json file.

This is already the case. Whenever `ng new` always uses the newest Angular. We had some reports of regressions related to 4.2.0 so we didn't tag is as `@latest` on npm until a few days later.
