### ISSUE TITLE
FormArray with one disabled FormControl don't keeps updated info in template

### ISSUE THREAD

**Issue by morriq** [angular/angular#17424]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
directly binding template keeps input as disabled

**Expected behavior**
directly binding template keeps input as **enabled**

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/nzpCeKSqsTvOnZHD34bl?p=preview

**Please tell us about your environment:**
Plunker

* **Angular version:** 4.1.3

* **Browser:** Chrome for sure
 
* **Language:** all

**Comment by kfurmann** [comment]
Perhaps the reason lies somewhere around here?
https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_control_directive.ts#L92

I think it's a bug.

**Comment by kara** [comment]
Related to https://github.com/angular/angular/issues/17806
