### ISSUE TITLE
async lifecycle hooks - should angular support 'await ngOnInit' or other hooks

### ISSUE THREAD

**Issue by alex321** [angular/angular#17420]
**I'm submitting a ...**  (check one with "x")
```
[ X ] feature request
```
Hey, I would be interested whether it makes sense to support adding `async` in front of the Angular lifecycle hooks e.g. 
`async ngOnInit() {
     await ...
}`

I saw that being used recently and I immediately sounded an alarm as this would prevent the correct ordering of lifecycle hooks. IMHO I can see why the person used it but I am not sure that it makes sense for Angular to provide that. 
Would it make sense to put any warnings in the docs? Thanks!

**Comment by chuckjaz** [comment]
This seems like an awkward way of executing something in a microtask.

How often are you seeing this?

**Comment by alex321** [comment]
The way people seem to think of it is as a neater way of getting your initial data before the component gets loaded. So instead of using Promise/Observable they revert to async. 

It seems an easy mistake to make as you when you put `async ngOnInit` you completely forget that you don't control the execution of that method. Even this article suggests at the end to use `async` everywhere you'd use a promise:  https://developers.google.com/web/fundamentals/getting-started/primers/async-functions

It's a bit difficult to say how often but it is there on the web 
https://labs.encoded.io/2016/12/08/asyncawait-with-angular/

I think the main place people would think of using it is `ngOnInit` but anything is possible! :)

**Comment by chuckjaz** [comment]
I am not sure that an explicit warning about this is needed as it doesn't interfere with Angular's lifecycle hooks. It is equivalent to saying something like.

```ts
  ngOnInit() {
    Promise.resolved().then(() => ...);
  }
```
which executes the lambda in its own microtask.

**Comment by robwormald** [comment]
@alex321 do you see this as something that works more like `resolve`, where it waits for the promise to return before carrying on with instantiation?

**Comment by alex321** [comment]
@chuckjaz Not quite as it pauses ngOnInit when await is used so it certainly changes the order in which the hooks will finish. Even if that doesn't cause a problem in angular at the moment, I think it is counter intuitive.

@robwormald That is how I interpreted the my teammate's intention - as another way if using a resolve but within a component. I haven't used it myself for the above reason. I just wanted to raise it to understand whether it will cause problems now or in the future. I personally don't love it as I cannot do await ngOnInit even if I wanted to.

**Comment by chuckjaz** [comment]
@alex321 Can you rewrite issue description above to make it clear what you are recommending?

**Comment by alex321** [comment]
@chuckjaz I am quite happy to close this one to be honest as judging from your answers, it's not a problem for someone to use `async ngOnInit` and it is just an awkward/not recommended coding practice.

**Comment by chuckjaz** [comment]
@alex321 Thanks!
