### ISSUE TITLE
Angular2 Throws Security Exceptions under the CSP (Content Security Policy)

### ISSUE THREAD

**Issue by PeEllAvaj** [angular/angular#1744]
I build and evangelize building mobile Chrome Apps using CCA. I do this extensively with Angular 1.x today but right now Angular 2 causes me some problems.  It does not seem to support a "CSP mode" like angular 1x.

This code runs just fine when I include the library locally, but it throws a security error when I put any variables into my templates.

    function AppComponent() {
      this.name = "testing";
    }

    AppComponent.annotations = [
      new angular.Component({
        selector: 'my-app'
      }),
      new angular.View({
        template: '<h1>My first Angular 2 App</h1>'
      })
    ];
    
    document.addEventListener('DOMContentLoaded', function() {
      angular.bootstrap(AppComponent);
    });

This works just fine under the CSP, but when I add the variable to the template:

    function AppComponent() {
      this.name = "testing";
    }

    AppComponent.annotations = [
      new angular.Component({
        selector: 'my-app'
      }),
      new angular.View({
        template: '<h1>My first Angular 2 {{name}} App</h1>'
      })
    ];
    
    document.addEventListener('DOMContentLoaded', function() {
      angular.bootstrap(AppComponent);
    });

I get the following error:

    Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' chrome-extension-resource:". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by calebboyd** [comment]
It looks like you can set the Change Detection interface for CSP environments.

https://github.com/angular/angular/blob/fa28b28d0aec63dd721d2b0821b889c4d73a63db/modules/angular2/src/change_detection/interfaces.ts#L20-L36

**Comment by PeEllAvaj** [comment]
Forgive my ignorance, but how would this be done using ES5?

**Comment by calebboyd** [comment]
I'm pretty sure that is es5 :)

**Comment by alexpods** [comment]
@PeEllAvaj I think you should do something like:

```js
var bind                   = angular.bind;
var ChangeDetection        = angular.ChangeDetection;
var DynamicChangeDetection = angular.DynamicChangeDetection;

document.addEventListener('DOMContentLoaded', function() {
  angular.bootstrap(AppComponent, [bind(ChangeDetection).toClass(DynamicChangeDetection)]);
});
```

but for unknown reasons `angular` (alpha.22) does not contain 'build' function (see [plunker](http://plnkr.co/edit/aZXjLjtnqYdbmu3vAbFr?p=preview)). I think this is the bug. 

/cc @IgorMinar @pkozlowski-opensource

**Comment by azasypkin** [comment]
> but for unknown reasons angular (alpha.22) does not contain bind function (see plunker). I think it's bug.

Looks like not a bug,```bind``` is just defined in  ```angular2/di```, but even with ```bootstrap(MyApp, [bind(ChangeDetection).toClass(DynamicChangeDetection)]);``` I still see CSP errors

**Comment by azasypkin** [comment]
Okay, was able to fix the rest of CSP errors with quick local patch (using real functions instead) at:

https://github.com/angular/angular/blob/c8947d77bf2125b44f8501788318e7eeb1043de7/modules/angular2/src/reflection/reflection_capabilities.ts#L102-L110

So now I can use Angular2 in FxOS apps :)

**Comment by mhevery** [comment]
Already documented: https://angular.io/docs/js/latest/api/change_detection/ChangeDetection-class.html

**Comment by bestander** [comment]
@azasypkin could you please share how you pathed reflection_capabilities?  
Can it be patched in the application or in the source of Angular only?

**Comment by azasypkin** [comment]
@bestander I don't have the patched version anymore, but IIRC I've just replaced ```Function``` with ordinary ```function() {...}```, like:
```
return new Function('o', 'v', 'return o.' + name + ' = v;');
```
converted to:
```
return function(o, v) { return o[name] = v;};
```

There is additional closure, but it was OK for my case.

> Can it be patched in the application or in the source of Angular only?

I was able to do it for Angular itself only.

**Comment by bestander** [comment]
Thanks, @azasypkin .
I suppose we'd better open an issue for Angular to provide a CSP compliant reflection_capabilites module.

**Comment by azasypkin** [comment]
@bestander, yeah, definitely. Maybe we just need to reopen this one.

**Comment by bestander** [comment]
I'll let you do the honours then :)

**Comment by azasypkin** [comment]
Ha-ha, I don't have rights to do this :) But let's ask reporter or Misko.

Hey @PeEllAvaj or @mhevery, can we reopen this issue at least for the tracking purposes?

Angular2 still has  CSP related issues (```new Function```) [1] at least in ```reflection_capabilities.ts``` [2] that prevents us from using the lib in highly restrictive environment, e.g. Firefox OS apps or add-ons.

[1] https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Default_CSP_restrictions#Function_constructor

[2] https://github.com/angular/angular/blob/c2a60f1624ad54c424a2a9f6425420edd84e97b8/modules/angular2/src/core/reflection/reflection_capabilities.ts#L157

**Comment by mhevery** [comment]
This works as expected. To run the Angular 2 in CSP mode you have to switch into Dynamic mode or pre-generate change detectors offline. This all has to be documented, so it is done, docs for this and many other things are missing.

**Comment by IgorMinar** [comment]
@vsavkin for the answer, @wardbell for documentation

**Comment by azasypkin** [comment]
Hey @IgorMinar, @vsavkin and @wardbell did you have any chance to document dynamic mode or pre-generation somewhere?

**Comment by IgorMinar** [comment]
Not yet. The offline template compilation is coming in this month.

**Comment by natizlp** [comment]
Can anyone provide a working example for working in CSP mode?

**Comment by hjliang** [comment]
@natizlp I have a working example https://github.com/hjliang/angular2-csp

**Comment by golear91** [comment]
@hjliang while your example does work, I've been unable to get my much more complex app to run in a CSP environment.  Help would be appreciated
@IgorMinar @mhevery @vsavkin @wardbell

**Comment by xnnkmd** [comment]
As noted in #11939, the issue is not only to make angular work with CSP but to make angular cli work with CSP as well. It would be wonderfull if angular + angular-cli could actually be used to create something secure.
