### ISSUE TITLE
aio: some searched API pages not showing on iPhone

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17449]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

API search doesn’t always work on (my) iPhone.  
1) Type “comp” in search box
2) Pick “compiler” … 

I get the loading indicator but never a page. This is problem only for a few of the matching pages. `COMPILER_OPTIONS` and `CompilerOptions` are fine. So is `platformDynamicServer`. But not `Compiler` or `CompilerFactory` or ...

Works fine on the (my) Mac.

**Comment by gkalpak** [comment]
(It works on my (Android) phone fwiw.)

**Comment by wardbell** [comment]
Just retried on my iPhone today ... both regular and incognito. Worked fine. Closing as "cannot reproduce"
