### ISSUE TITLE
The language switcher in the new angular.io website

### ISSUE THREAD

**Issue by m0uj** [angular/angular#17457]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you select the Chinese Version of the website, The language switcher is also translated to chinese!

**Expected behavior**
The language switcher should be written in english 'English Version' (in the chinese version of the website) but instead it's translated '英文版'.

**Minimal reproduction of the problem with instructions**
Visit the chinese version of the website and take a look at the Language section in the Footer
https://angular.cn/

**Please tell us about your environment:**
CentOS

* **Browser:** 
Tested on Chrome and Firefox

**Comment by Foxandxss** [comment]
This should be reported the to the chinese repo.
