### ISSUE TITLE
`assertionsEnabled()` is always false after move to TS

### ISSUE THREAD

**Issue by rkirov** [angular/angular#1745]
However, assertionEnabled is used as a proxy for developer mode, where extra checks are performed. 

`assertionsEnabled` should be changed to `isProductionMode` as a simple bool and hooked to the right gulp tasks.

**Comment by naomiblack** [comment]
@ttowncompiled are you working on this issue? If not, could you unassign it? @rkirov I am demoting to P2 since this hasn't been touched since it was filed and I don't hear any complaints...

**Comment by naomiblack** [comment]
This needs more design discussion before it can be assigned.

**Comment by mhevery** [comment]
Dup of https://github.com/angular/angular/issues/2830 closing
