### ISSUE TITLE
AoT Compilation - TypeError: "this.compiler.analyzemodulesasync" is not a function

### ISSUE THREAD

**Issue by Davy-F** [angular/angular#17451]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
I am trying to implement AOT compilation to an existing project based on the following guide: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

I've installed comiler-cli and platform-server, and also created a new tsconfig-aot.json.

I then try and call 

`"node_modules/.bin/ngc" -p tsconfig-aot.json`

but it returns the following error:

> C:\Development\AppProject>"node_modules/.bin/ngc" -p tsconfig-aot.json
> TypeError: this.compiler.analyzeModulesAsync is not a function
>     at CodeGenerator.codegen (C:\Development\AppProject\node_modules\@angular\
> compiler-cli\src\codegen.js:32:14)
>     at codegen (C:\Development\AppProject\node_modules\@angular\compiler-cli\s
> rc\main.js:13:81)
>     at Object.main (C:\Development\AppProject\node_modules\@angular\compiler-c
> li\node_modules\@angular\tsc-wrapped\src\main.js:98:16)
>     at main (C:\Development\AppProject\node_modules\@angular\compiler-cli\src\
> main.js:19:16)
>     at Object.<anonymous> (C:\Development\AppProject\node_modules\@angular\com
> piler-cli\src\main.js:35:5)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
> Compilation failed

**Expected behavior**
AOT compilation should be initiated and create the aot NgFactory files.

**Minimal reproduction of the problem with instructions**
Follow the steps here: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Please tell us about your environment:**
Windows 7 

* **Angular version:** 4.0.0

* **Browser:** N/A
 
* **Language:** [TypeScript 2.2.0 | ES5]

* **Node (for AoT issues):** `node --version` =  v6.5.0

**Comment by Davy-F** [comment]
Hmm, seems that calling npm update has fixed this error.

**Comment by aqeelrepoowner** [comment]
Yes it worked for me.

**Comment by naveen4854** [comment]
I am still facing the issue even after npm update
