### ISSUE TITLE
aio: Not mentioned about importing toPromise operator

### ISSUE THREAD

**Issue by laco0416** [angular/angular#17454]
**I'm submitting a ...**  (check one with "x")
```
[x] documentation issue
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In [Http documentation](https://angular.io/guide/http#fall-back-to-promises), `toPromise()` operator is used but it's not imported in any codes in the page. For RxJS beginners, It's difficult a bit to know how to solve `EXCEPTION: TypeError: this.http.get(...).toPromise is not a function`.

**Expected behavior**

Add a tip or a note about it.

cc/ @wardbell

**Comment by dherges** [comment]
There's actually a doc region for the "rxjs-imports" ... I tried to add it ... see the above PR

**Comment by laco0416** [comment]
@dherges Thank you for making a patch! 😄

**Comment by laco0416** [comment]
Solved in https://github.com/angular/angular/commit/bfa788935a66b60bace0053a9190b74bb9c3dfb2. 
Thank you!
