### ISSUE TITLE
aio: console.log for every doc navigation in production

### ISSUE THREAD

**Issue by fredrik-lundin** [angular/angular#17453]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When navigating around the new angular.io docs, each navigation gets printed to the developer console

**Expected behavior**
This should not be logged in production (I guess?)

**Minimal reproduction of the problem with instructions**

1. Go to [https://angular.io/docs](https://angular.io/docs)
2. Open developer console in your browser
3. Navigate between pages

![aio-console-log](https://user-images.githubusercontent.com/5526934/27073820-767906b0-5025-11e7-8e3a-139bd4a4145f.PNG)

**What is the motivation / use case for changing the behavior?**
It just looks like a strange behavior for a production build
 
**Please tell us about your environment:**
- Windows 7

**AIO version:**
- angular.io build: Version 4.2.3-build.31653+sha.dc084a5.

**Browser:** 

- Chrome (Version 58.0.3029.110 (64-bit))
- Internet Explorer 11 (version 11.0.42)
- Firefox 52.1.2 (32-bit)

**Comment by petebacondarwin** [comment]
Let's remove these.

**Comment by IgorMinar** [comment]
yeah. that's fine. let's remove.
