### ISSUE TITLE
Buggy wildcard height animation

### ISSUE THREAD

**Issue by eTallang** [angular/angular#17450]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
A HTML element with an animation that animates the height from a fixed value to a wildcard value that triggers on click will not render correctly if the element is clicked again before the * height animation has finished. 

**Expected behavior**
Clicking the HTML element while it animates from "open" (height *) to "closed" (height e.g. 100px) state, should stop the animation and animate back to the "open" state.

**Minimal reproduction of the problem with instructions**
The plunker below illustrates the issue. If the state of the red square is "open", the height is set to *. If the square is clicked, the state is set to closed, and the height is set to 100px. However, if the square is clicked to go from state "open" to "closed", and the user clicks the square while it animates from the "open" (height *) to the "closed" (height 100px) state, the square appears to be closed (100px height), while the state-property in reality is "open". If the square is clicked again, the height of the square suddenly jumps from 100px to *, and then animates down to 100px (correct state).
https://plnkr.co/edit/lpnxmyVgidhWqjYdTsgb?p=preview

**What is the motivation / use case for changing the behavior?**
This functionality was working in Angular 2.4.9, and is therefore preventing me from updating to Angular 4. I was shown [this issue](https://github.com/angular/angular/issues/15507) and hoped it would fix my problem, however it seems it's still an issue in Angular 4.2.2.

**Please tell us about your environment:**
OS: Windows 10
IDE: Visual Studio Code
Package manager: Yarn

* **Angular version:**
4.2.2

* **Browser:**
Chrome 59.0.3071.86
Firefox 53.0.3 (32-bit)
IE 11.1198
Edge 38.14393.1066.0
 
* **Language:** 
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by macjohnny** [comment]
@eTallang this could be related to https://github.com/angular/angular/issues/17239#issuecomment-306536861

**Comment by eTallang** [comment]
@macjohnny Yes they may be related since they both are reproduced by cancelling an animation in progress. However my bug is also present in Chrome, and has specifically to do with the wildcard property when applied to the height of a HTML element.

**Comment by eTallang** [comment]
@matsko Any updates on this issue? It seems like a major bug in my opinion, so I would think it received a high priority.

**Comment by matsko** [comment]
I'm on it. Sorry for the delay.
