### ISSUE TITLE
aio: the footer background doesn't work well in high resolutions

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#17465]
![](https://puu.sh/wiRvc/4285e95751.png)

**Comment by gkalpak** [comment]
This is sort of by design (cc @sjtrimble).
How high resolutions are we talking about?

**Comment by Foxandxss** [comment]
1440 wide.

**Comment by gkalpak** [comment]
@Foxandxss, afaict the footer background can accomodate for up to 2000px ([source code][1]). This should be enough for the vast majority of usecases. I can't think of an easy way to fix this for any size off the top of my head. @sjtrimble, any ideas?

[1]: https://github.com/angular/angular/blob/b4cd20cbbccf0fe8854cbc540c87d8f425cfe501/aio/src/styles/1-layouts/_footer.scss#L105-L119

**Comment by gkalpak** [comment]
Here is an idea: #17482
