### ISSUE TITLE
ElementBinder class names should be clarified

### ISSUE THREAD

**Issue by juliemr** [angular/angular#1746]
At the moment, `ElementBinder` refers to both https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/element_binder.js and https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/view/element_binder.js

They should be renamed separately, maybe `AppElementBinder` and `DomElementBinder`

cc @tbosch

**Comment by juliemr** [comment]
Oh and there is also
https://github.com/angular/angular/blob/master/modules/angular2/src/render/api.js#L32

**Comment by mhevery** [comment]
This has already happened

**Comment by tbosch** [comment]
No, I think ElementBinders are still not prefixed correctly
