### ISSUE TITLE
i18n: compile app with multi locale

### ISSUE THREAD

**Issue by zh99998** [angular/angular#17468]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

currently AOT i18n can only build one locale at once, to build app with all languages, we must run many build process and dist app in different locale many times, after app grows bigger, it will waste much time and storage.

request to add a multi-locale aot build feature
something like `ng build --aot --locale en,fr,zh-CN`
then build one app (index.html, favicon, assets, polyfills and other non locale-related files)
multi main.bundle.js (or other locale-related files).

**Comment by tomreinartz90** [comment]
+1

**Comment by actra-gschuster** [comment]
If you're using webpack 2 this package might help you out until the ng-team provides a solution:
https://www.npmjs.com/package/@actra-development/actra-ng-i18n-loader

**Comment by zoonman** [comment]
I think this ticket is having a broader request for features:

- [ ] bundling of a number of locales
- [ ] autodetection of browser's locale with fallback to default locale and ability to dynamically switch language from the app
- [ ] autoupdate of messages.xlf and tracking of translation completeness (using `ng serve`)
- [ ] locales path & list option for `.angular-cli.json`

**Comment by trotyl** [comment]
Hi @zoonman, I think currently it's better to contribute your points to https://github.com/angular/angular/issues/20193 for better tracking reason.

**Comment by zoonman** [comment]
Thank you, @trotyl, I will do.

**Comment by SantiagoIlli** [comment]
See [this comment](https://github.com/ngx-translate/core/issues/495#issuecomment-533305639)

**Comment by Ratikant01** [comment]
I personally do not like the way Angular team came up with the i18n support! I hate it when someone says me to build that many separate projects and make them running just to support i18n?!

**Comment by JoostK** [comment]
i18n support has completely changed with Ivy using the `$localize` function, which allows for a cheap post-processing build step instead of a full compilation. Please refer to the docs on [how to configure i18n bundling with the CLI](https://angular.io/guide/i18n-common-merge#define-locales-in-the-build-configuration).
