### ISSUE TITLE
Animations: Nested groups in AOT lead to ERROR in Recursion not supported

### ISSUE THREAD

**Issue by AKuzmanoski** [angular/angular#17467]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using nested groups as `AnimationMetadata` AOT compiler throws the following error:
`ERROR in Recursion not supported, resolving symbol MyComponent`

**Expected behavior**

Nested groups pass AOT compilation process

**Minimal reproduction of the problem with instructions**

```
transition('home => about',
        group([
          query(':enter', group([
            useAnimation(slideFromRight),
            animateChild()
          ]), {optional: true}),
          query(':leave', group([
            useAnimation(slideToLeft),
            animateChild()
          ]), {optional: true})
        ])
      )
```
Then start the angular cli server
`ng serve --aot`

**Workaround**
```
transition('home => about',
        group([
          query(":leave, :enter",
            animateChild(), {optional: true}),
          query(':leave',
            useAnimation(slideToLeft), {optional: true}),
          query(':enter',
            useAnimation(slideFromRight), {optional: true})
        ])
      )
```

**What is the motivation / use case for changing the behavior?**

Nested groups keep code cleaner

**Please tell us about your environment:**

Windows 10
WebStorm 2017.1
@angular/cli: 1.1.1
node: 8.1.0
os: win32 x64
@angular/animations: 4.2.2
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/material: 2.0.0-beta.6-88089a7
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.2
@ngtools/webpack: 1.4.1

* **Angular version:** 2.0.X

yes

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Its compile time error
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.3.4

* **Node (for AoT issues):** `node --version` =   
v8.1.0

**Comment by matsko** [comment]
@chuckjaz any idea what's going on here?

**Comment by DBosley** [comment]
This also happens with nested `query()` calls

**Comment by bogacg** [comment]
Any progress in this front? I'm having same problem in my component 😟

**Comment by bizreach-syo** [comment]
Any update on this? Hope this could be fixed. 😞

**Comment by templth** [comment]
Thanks for the fix! Do you know when it'll be available in a version?

**Comment by hill0826** [comment]
It doesn't look like the fix has made it into a stable release yet, but for now a delegating function can be used as a temporary workaround:

```typescript
export function myFunction(arg: any): any {
    return arg;
}
export function myFunction_1(arg: any): any {
    return myFunction(arg);
}

// Within AOT metadata compilation
myFunction(myFunction('some value')); // Throws recursion error
myFunction_1(myFunction('some value')); // Succeeds
```

I haven't tested this extensively, but it seems to be working for me so far.

**Comment by chuckjaz** [comment]
I am working on getting this cherry-picked into 4.3.x. It is available already on master .

**Comment by bizreach-syo** [comment]
Any update on cherry-pick of this into 4.3.x ?
