### ISSUE TITLE
Property Assignment via Brackets Does Not Error In Template Binding

### ISSUE THREAD

**Issue by silentsod** [angular/angular#17470]
[x ] bug report => search github for a similar issue or PR before submitting

**Current behavior**
If a binding to an object property which does not exist is declared in a template using square bracket notation then the binding succeeds and creates the property on the object.

**Expected behavior**
The binding should not occur through the template per the warning, when using dot properties:
"Bindings cannot contain assignments"

**Minimal reproduction of the problem with instructions**

Have a template with an array of objects and iterate over them using *ngFor, assign a new property to each object in a template binding like so "{{item['count'] = 0}}" and see that it compiles and runs without error or warning.

//our root app component
import {Component, NgModule} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser'

@Component({
  selector: 'my-app',
  template: `
    <div>
      <h2>Hello {{name}}</h2>
      <div class="item" *ngFor="let item of obj"> 
        <span>{{item.name}}</span>
        <span>{{item['count'] ? item['count'] : item['count'] = 0}}</span>
        <button (click)="increment(item)">plus</button>
        <button (click)="decrement(item)">minus</button>
      </div>
    </div>
  `,
})
export class App {
  name:string;
  obj = [{name: 'Hello 1'}, {name: 'Hello 2'}];
  
  constructor() {
    this.name = 'Angular2'
  }
@NgModule({
  imports: [ BrowserModule ],
  declarations: [ App ],
  bootstrap: [ App ]
})
export class AppModule {}

Change the [] property access to . access in the template to see the error occur.

[Plunker reproducing issue](http://plnkr.co/edit/b5fe87kFm2nxs3kabZRo?p=preview)
[Discussion and discovery that this is a bug on SO](https://stackoverflow.com/questions/40424757/set-new-object-property-on-ngfor-angular-2/)

**What is the motivation / use case for changing the behavior?**
Using dot notation yields an error that assignments cannot occur in bindings.

**Please tell us about your environment:**
Plunker

* **Angular version:** 4.2.2

* **Browser:** Tested with (expect all): Chrome 58.0.3029.110 | IE 11
 
* **Language:** [all | TypeScript 2.0.2

**Comment by pkozlowski-opensource** [comment]
Minimal repro: https://ng-run.com/edit/ItEqWZZZUXHZ76qCNDzY

**Comment by JoostK** [comment]
This is actually working as expected, but the output is dependent on the TypeScript compiler options. The `noImplicitAny` or `strict` option needs to be enabled for this code to be considered a type error. This has the exact same behaviour as TypeScript code.
