### ISSUE TITLE
invalid json - http error response

### ISSUE THREAD

**Issue by mydata** [angular/angular#17471]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The error.json() returns the error : 
SyntaxError: Unexpected token E in JSON at position 0
    at Object.parse (<anonymous>)
    at Response.Body.json (http.es5.js:800)

The scenario I am testing is backend API connection is refused and getting 504 - gateway timeout.
I am expecting a error json, which i can parse and identify the data to display a generic message for 50* errors.
**Expected behavior**

error.json() should parse correctly
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All
* **Node (for AoT issues):** `node --version` =   7.9.0

**Comment by hansl** [comment]
Your server is not returning any JSON data, it seems to be text which will fail any JSON parsing. You need to either:

1. configure your backend (or any proxy/gateway in between) to properly return JSON data in case of a 504, or
1. try to parse the response as JSON on the client, and if it fails then consider the response as text, or
1. verify the mimetype of the response in the client to know if it should be JSON or not.

Closing this issue as this is not an Angular issue.
