### ISSUE TITLE
Allow compiler to do shallow render

### ISSUE THREAD

**Issue by dblVs** [angular/angular#17474]
Hello,
I'm submitting this feature request on the compiler to be able to do shallow rendering. 

I what I want is not that different from NO_ERROR_SCHEMA. The differences being is if i have a component used i want to be able to tell if I bound onto it correctly, BUT don't want that component to load its children.

This is mainly for using with TestBed.

Example

```
@Component({
  selector: 'my-comp'
  template: '<p><my-comp-two [someBinding]="1">some transcluded stuff</my-comp-two><p>'
})
class MyComp {}

@Component({
  selector: 'my-comp-two'
  template: `<ng-content></ng-content>
    <some-other-component-i-dont-wanna-render></some-other-component-i-dont-wanna-render>`
})
class MyCompTwo {
  @Input()
  someBinding;
}
```

At the moment I'm using a work around which includes me creating stubs and using those stubs in the test bed. Ultimately I should be able to use a schema that disables the render on the second level rendered components or uses no error schema on them.

There are few issues I can tell right away and those are cases like having component/directives that do template registering by querying content child (something like ngSwitch). Another question mark is transclusion.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Expected behavior**
Fully render first layer of components and shallow render for rest layers.

**What is the motivation / use case for changing the behavior?**
To be able to produce unit tests without having to load the whole component tree.
Benefits:

- MUCH easier way of writing unit tests.
- Potentially in large code bases we don't want our tests to break in small changes in the components. Even in cases of broken component we don't want all the tests to break, but only the only the tests for the component.
- Allows you to test the component in isolation from the module.

**Comment by dblVs** [comment]
***NOTE***
Similar behaviour to [enzyme.shallow](https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md)

**Comment by sharikovvladislav** [comment]
This will be awesome for https://facebook.github.io/jest/docs/en/snapshot-testing.html

**Comment by IgorMinar** [comment]
@vikerman what do you think about this kind of testing approach?

**Comment by sharikovvladislav** [comment]
Also is there any scheme which will not render stuff like nghost/ngcontent/ng-reflect properties?

Example:

```
<diary-page
  changeDetectorRef={[Function ViewRef_]}
  dialogFactory={[Function DialogFactoryService]}
  diaryEntries$={[Function Store]}
  store={[Function Store]}
>
  <common-show-if-logged-in
    _ngcontent-c6=""
  >
    <div
      ng-reflect-ng-switch="true"
    >
      <div>
        <diary-entry-list
          _ngcontent-c6=""
          _nghost-c7=""
          ng-reflect-entries="[object Object],[object Object"
        >
```

it is output of such test:

```
  it('should match snapshot', () => {
    expect(fixture).toMatchSnapshot();
  });
```

I need this for testing purposes.

**Comment by dblVs** [comment]
@sharikovvladislav I'm not sure if we are thinking of the same thing. My idea was to stub out the components within the component I test to be able to run unit test without any interference and also less time/memory compiling the component.

**Comment by getsaf** [comment]
[shallow-render](https://github.com/getsaf/shallow-render) - Angular testing made easy with shallow rendering.

@dblVs I've had the same frustrations with Angular testing. I have also found that the list of 3rd party testing tools for Angular have been lacking. I took the Enzyme approach and wrote a library that does shallow-rendering for Angular called [shallow-render](https://github.com/getsaf/shallow-render). Our goals seem to align here. I wanted to provide my test setup with my component, and the module it lives in and have all child components, pipes, directives and services mocked for me so I could just focus on testing my bindings.

To re-use your example above, here's how you would test `MyComp`:
```typescript
describe('MyComp', () => {
  let shallow: Shallow<MyComp>;

  beforeEach(() => {
    shallow = new Shallow(MyComp, TheModuleMyCompLivesIn); // EVERYTHING in your module is mocked away except for MyComp.
  });

  it('renders Comp2 with someBinding=1`, async () => {
    const {findComponent} = shallow.render();
    const compTwo = findComponent(MyCompTwo);

    expect(compTwo.someBinding).toBe(1);
  });

  it('projects content into MyCompTwo`, async () => {
    const {find} = shallow.render();
    const compTwoElement = find('my-comp-two');

    expect(compTwoElement.nativeElement.innerText).toContain('some transcluded stuff');
  });
})
```

Note that `MyCompTwo`'s template, inputs and outputs are fully mocked (using [ng-mocks](https://github.com/ike18t/ng-mocks)) so it's not actually rendered.

You get lots of control over your mocks and test setup, see the [docs](https://github.com/getsaf/shallow-render/blob/master/README.md) and a folder full of [example usages](https://github.com/getsaf/shallow-render/tree/master/lib/examples) for more details. The rendering is still done with `TestBed`, and you still have access to everything `TestBed` offers.

I currently work in a large Angular project and we've been using this with success. Hopefully, this works for you too.

**Comment by michaeljota** [comment]
I think this is, as #22797, are really needed. However, I don't think how this could land without some assumptions, that are not always wanted when testing. I really like the `shallow-render` but the need to mock all the dependencies remark the need for this to be integrated in Angular. 

I really would like something that _just works_, and needs nothing from me to work. I understand this is really difficult, as it would need to know or assume to know, several parts of the app or component. So, I would like something like this. 

* As Angular Compiler have type information, this could be used to automagically mock all the services for a Component. (Knowing the type information).
* Pipes should return the input value as is, and don't transform anything. (Assuming).
* Other components doesn't matters, as you just want to test just one component (Assuming). 

I understand that mocking something would require to know the test framework to be used, but maybe this could abstract in a way that allow this to be configurable. 

This could allow testing like this:

* Component:
```ts
import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs';
import { startWith } from 'rxjs/operators';

import { AppState } from '../../app-store.module';

import { Hero } from './../shared/hero.model';

import { HeroesDispatcher } from './heroes.dispatcher';
import { selectHeroesList } from './heroes.selectors';

@Component({
  selector: 'app-heroes',
  templateUrl: `
<mat-card>
  <mat-nav-list>
    <ng-container *ngIf="hasHeroes; else: noHeroes">
      <a mat-list-item *ngFor="let hero of heroes | async"
        [routerLink]="['details', hero.id]"
      >
        {{ hero.name }}
      </a>
    </ng-container>
    <ng-template #noHeroes>
      No heroes have been loaded
    </ng-template>
  </mat-nav-list>
</mat-card>
`,
  styleUrls: ['./heroes.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeroesComponent implements OnInit {
  public heroes: Observable<ReadonlyArray<Hero>>;
  public hasHeroes: boolean = false;

  constructor(private readonly store: Store<AppState>) {}

  ngOnInit() {
    this.store.dispatch(new HeroesDispatcher.load());
    this.heroes = this.store
      .select(selectHeroesList)
      .pipe(tap((heroes) => (this.hasHeroes = heroes && heroes.length > 0)));
  }
}
```

* Component Spec:

```ts
describe('HeroesComponent', () => {
  let component: HeroesComponent;
  let fixture: ComponentFixture<HeroesComponent>;

  beforeEach(() => {
    fixture = TestBed.shallowRender(HeroesComponent); // Return a fixture of the component with all the services mocked by the type, and with the others components rendering what's inside only. 
    component = fixture.componentInstance;
  });

  it('should match snapshot without heroes', () => {
    fixture.detectChanges();
    await fixture.whenStable();

    expect(fixture).toMatchSnapshot();
  });

  it('should match template snapshot with stub data', async () => {
    TestBed.provideMock(Store, storeMock);
    fixture = TestBed.shallowRender(HeroesComponent); // Return a fixture of the component with the service mocked with the given mock, and with the others components rendering what's inside only.
    fixture.detectChanges();
    await fixture.whenStable();

    expect(fixture).toMatchSnapshot();
  });
]);

const storeMock = {... a mock to return an array of heroes};
```

* Snapshots
```html
<!-- should match snapshot without heroes -->
<mat-card>
  <mat-nav-list>
    No heroes have been loaded
  </mat-nav-list>
</mat-card>

<!-- should match template snapshot with stub data -->
<mat-card>
  <mat-nav-list>
    <a _ngcontent-c14="" mat-list-item="" ng-reflect-router-link="details,11" href="/details/11">
      Mr. Nice
    </a>
    <a _ngcontent-c14="" mat-list-item="" ng-reflect-router-link="details,12" href="/details/12">
      Narco
    </a>
    <a _ngcontent-c14="" mat-list-item="" ng-reflect-router-link="details,13" href="/details/13">
      Bombasto
    </a>
    <a _ngcontent-c14="" mat-list-item="" ng-reflect-router-link="details,14" href="/details/14">
      Celeritas
    </a>
    <a _ngcontent-c14="" mat-list-item="" ng-reflect-router-link="details,15" href="/details/15">
      Magneta
    </a>
  </mat-nav-list>
</mat-card>
```

I understand this should be documented properly, but I think this could be a really powerful feature for Angular Testing, and will allow to test components insanely fast.

**Comment by dblVs** [comment]
@IgorMinar i'm closing this issue since this is specific use case that has a work around by manually creating the stubs.
