### ISSUE TITLE
Support Directive dependency aliases

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#1747]
I had a request for `directive` aliases, for example:

shared.js
```
export SHARED_DEPS = [Dep1, Dep2, Dep3];
```

component1.js
```
import {SHARED_DEPS} from 'shared.js';

@Component({...})
@View({directives: SHARED_DEPS})
class Component1 {...}
```

component2.js
```
import {SHARED_DEPS} from 'shared.js';
import {AdditionalDep} from 'component2_deps.js';

@Component({...})
@View({directives: [SHARED_DEPS, AdditionalDep]})
class Component2 {...}
```
  
`Component1` would depend on `Dep1`, `Dep2`, and `Dep3`, while `Component2` would be those as well as `AdditionalDep`.

@yjbanov , @mhevery , does Angular 2 Js already support this?

**Comment by yjbanov** [comment]
This should already be supported in reflective mode. There's a bit of a debate going about the `directives` field. Not 100% sure `directives` are here to stay. Let's wait until the dust settles on the topic.

**Comment by pkozlowski-opensource** [comment]
Right, currently there is logic to flatten directives list: https://github.com/angular/angular/blob/28022f472d5dbc231bb5c60da696744da40cf322/modules/angular2/src/core/compiler/compiler.js#L241

**Comment by mhevery** [comment]
Obsolete. Already supported.

**Comment by kegluneq** [comment]
Not yet supported when running statically in the transformer.

**Comment by sigmundch** [comment]
@yjbanov @kegluneq - I'm hitting an issue with the current implementation I have for this, and I was wondering what you think of the possible alternatives here.

The implementation I have is here: https://github.com/angular/angular/compare/master...sigmundch:expand_meta?expand=1

To support code transformers I introduced a new annotation `@DirectiveAliases` that you can use on top-level constants to let the transformer know about them. So you could write:

```dart
@DirectiveAliases
const formDirectives = const [ ... ]
```

The idea behind this is to only include in the generated code those symbols that are explicitly declared as directive aliases.

However, it seems that TypeScript doesn't support decorators on top-level variable declarations. If that's the case, I can't write the `@DirectiveAliases` annotation directly on top of `formDirectives` in `form/directives.js`. I'm evaluating some alternatives:

* include a lot more automatically: for instance, include any const list that looks like a potential target. I think this will be too expensive and has the potential of getting big
* change aliases to be a const object that wraps the list of aliases, for example:

```dart
const formDirectives = const DirectiveAliases(const [ ... ])
```

See also https://github.com/angular/ts2dart/issues/249 for more details on the TypeScript limitations and discussion of other alternatives.

**Comment by yjbanov** [comment]
@alexeagle: do you think it would it be possible to strip unsupported annotations from the TypeScript code prior to handing it off to the TypeScript compiler? I'm assuming it is possible to build an AST prior to analysis.

**Comment by sigmundch** [comment]
(fwiw - the TS parser seems to support it already https://github.com/angular/ts2dart/compare/master...sigmundch:add_decorator_on_top_level?expand=1)

/cc @mprobst (since the discussion is a bit split between the two bugs)

**Comment by alexeagle** [comment]
Looks like the discussion is taking place at https://github.com/angular/ts2dart/issues/249

**Comment by alexeagle** [comment]
To answer the question: I don't think it's a good idea for angular code to
use a superset of TypeScript because ours is not the only build tool that
parses and compiles the code. What about IDEs? running tsc on the command
line?

**Comment by kegluneq** [comment]
As part of this fix, please update the message changed in https://github.com/angular/angular/pull/3153 to reflect the new reality of directive aliases.

Thanks!

**Comment by sigmundch** [comment]
will do, thanks!
