### ISSUE TITLE
docs: FormControlName API documentation errors

### ISSUE THREAD

**Issue by daveriedstra** [angular/angular#17484]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Multiple inappropriate references to `AbstractControl` on the documentation page for `FormControlName`:

> Set value: You can set an initial value for the control when instantiating the FormControl, or you can set it programmatically later using **AbstractControl** or **AbstractControl**.
> 
> Listen to value: If you want to listen to changes in the value of the control, you can subscribe to the **AbstractControl** event. You can also listen to **AbstractControl** to be notified when the validation status is re-calculated.

## Expected behavior
These references should be to their appropriate referees (presumably members of `AbstractControl`)

## Minimal reproduction of the problem with instructions
- visit [https://angular.io/api/forms/FormControlName](https://angular.io/api/forms/FormControlName)
- scroll to bottom of How to Use section
- observe errors

## What is the motivation / use case for changing the behavior?
logical and easily understood documentation

## Please tell us about your environment

<pre><code>
Angular version: 4.2.2

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues: n/a

Others: n/a
</code></pre>

**Comment by kara** [comment]
Yikes, thanks for alerting us @daveriedstra. It looks like the refs are supposed to be (in order):

- setValue
- patchValue
- valueChanges
- statusChanges

**Comment by Linskeyd** [comment]
Added a PR for fixing the above.  Also went ahead and updated a few of the other reactive directives that were present in forms.
