### ISSUE TITLE
When using Forms, Observables, and MdSpinner I get "Uncaught error: macrotask..."

### ISSUE THREAD

**Issue by Goodwine** [angular/angular#17486]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using an `MdSpinner` that is shown when an observable returns a value, and a form that when doing `onSubmit` will call an async service that returns another observable or promise which will eventually hide the spinner, all within a `fakeAsync` zone except for calling the NgForm onSubmit event, then the test will pass but will stay on an infinite loop throwing the following error:

```
Uncaught Error: macroTask 'setInterval': can not transition to 'running', expecting state 'scheduled', was 'notScheduled'.
```

It seems like while the tests themselves are OK, some function called on an interval (one that comes from MdSpinner for animations) is left active somehow.

## Expected behavior
I expected my test to pass without throwing errors after jasmine completed the tests. Or at least get an error saying that I'm at fault and tell me why and what to do.

## Minimal reproduction of the problem with instructions

1. Visit https://plnkr.co/edit/kt3BczWjCUQSeWkwnF20?p=preview
2. Open the browser console.
3. Wait until the test passes.
4. Suddenly the console will start spitting out the exception (from zone.js)

## What is the motivation / use case for changing the behavior?

While the **Current behavior** section may be very obscure, it's actually a pretty easy to come by issue, I'll highlight the use case:

1. User is shown a component.
2. The component calls a service that will load some data `onInit`, an spinny is shown.
3. The service completes and the spinny is hidden, some data is updated in the component instance.
4. This component shows a form based on the data loaded from the service, for example.. pre filled values.
5. When the form is submitted it emits an event listened by the parent component (the one with the spinner)
6. The component will show the spinny again and call a service to save the data from the form.
7. The spinny is hidden at the end.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.2

Browser:
- [x] Chrome (desktop) version 59
- Firefox 53

Others:
rxjs@5.2.0
plugin-typescript@5.2.7/lib/plugin.js
typescript@2.3.4/lib/typescript.js
jasmine/2.4.1
zone.js@0.8.4

</code></pre>

**Comment by JiaLiPassion** [comment]
@Goodwine, it seems the plunker not reproduce the issue now, could you update the plunker? thank you!

**Comment by Goodwine** [comment]
I've updated the Plunkr. I can't reproduce this issue anymore, I remember reading that there were improvements in tests of components with macro tasks so maybe this isn't a problem anymore?

**Comment by jasonaden** [comment]
Closing as it's no longer reproducible.
