### ISSUE TITLE
aio: Where is Angluar Universal Docs on the new AIO

### ISSUE THREAD

**Issue by cheerun** [angular/angular#17489]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is no Angular Universal Docs on the new AIO

## Expected behavior

There should be Angular Universal Docs

## Minimal reproduction of the problem with instructions

connect angular.io and go to DOCS

## What is the motivation / use case for changing the behavior?

none

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

not related

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 
not related

Others:

</code></pre>

**Comment by Foxandxss** [comment]
There is none at this moment. We are working on it. We were busy with the new site and we are now back to docs :)

**Comment by wardbell** [comment]
Closing because duplicates work in progress.
