### ISSUE TITLE
Upgrading from version 4.13 to 4.2.2 classes added to markup with prefix ng-tns-c

### ISSUE THREAD

**Issue by dimmank** [angular/angular#17492]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

After upgrading html markup has classes added with "ng-tns-c"

## Expected behavior

markup should remain clean

## Please tell us about your environment
Windows 10, VS code

<pre><code>
Angular version: 4.2.2
CLI 1.1.1

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  8.1.1
- Platform:  Wiindow

Others:

</code></pre>
![capture](https://user-images.githubusercontent.com/825094/27119323-b0e0f618-50df-11e7-9058-074d5eca1884.PNG)

**Comment by Toxicable** [comment]
What issue has this caused for your application?

**Comment by dimmank** [comment]
@Toxicable 
I have a directive that detects clicks on a certain area of the page, it looks for a specific "exact" class name on the clicked target and it didn't match because of the added class name. I did rewrite the code so it does a split on class name and now works as expected. The new angular.io site runs the version 4.2.1 and their markup is clean. Is this something you can turn off?

**Comment by Toxicable** [comment]
Looks related to the new animations which were released in 4.2.
However it appears to be the namespacing id transitions  as you can see here https://github.com/angular/angular/blob/ed73d4f3ac6b542bf5ea3eb73fbe91e2ceabcdb4/packages/animations/browser/src/render/transition_animation_engine.ts#L112
In which case my guess is that it is essential, but I could be incorrect on this assumption.

/cc @matsko

**Comment by dimmank** [comment]
@Toxicable 
Yes, you are absolutely correct. 
Thank you! 👍 
I think a better solution would have been to add an attribute instead, but those guys probably have a good reason for it. Cheers!
