### ISSUE TITLE
Router-Outlet not clearing immediately.

### ISSUE THREAD

**Issue by spielma** [angular/angular#17499]
![screenshot from 2017-06-14 09-57-34](https://user-images.githubusercontent.com/10120254/27136249-d75facc2-50e8-11e7-9c5f-fd4165e37114.png)

Problem:

Router Outlet doesn't seem to clear until the new route's component has already begun to load.

- attempting to access `this.el.nativeElement.offsetHeight` in ngOnInit (of componentA) returns an inaccurate height.
The element cannot fill the entire router-outlet due to the presence of the other component (componentB) sharing the router-outlet.  

Firstly, IS this the desired behaviour?

Steps to reproduce:
1) Activate a new route.

Circumstances:
-  Placed breakpoint in ngOnInit of the component which is activated.
-  Within feature module ( potentially relevant)

```typescript
const ROUTES: Routes = [
	{
		path: '',
		canActivate: [AuthGaurd],
		canActivateChild: [AuthGaurd],
		component: SalesComponent,
		children: [
			{
				path: 'leads',
				component: LeadsBaseComponent,
				children: [
					componentA
				]
			},
			{
				path: 'workorders',
				component: WorkordersBaseComponent,
				children: [
					componentB
				]
			}
		]
       }
]
```

Hack-around for now:
```css
router-outlet + * + * {
  display: none;
}
```

**Comment by fillmorejl** [comment]
There was defiantly a breaking change with how sub routes and ngOnInit work.  I hope they fix it, it worked fine in version 4.1.3.

**Comment by jasonaden** [comment]
@spielma Please provide a plunker showing the issue. You can use this template:

http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by juanpablodelatorre** [comment]
Same thing is happening to me. This might be relevant: I also have an AuthGuard on canActivateChild.

I'll try to set up a plunkr later today.

**Comment by AndreiBelokopytov** [comment]
Possible reason of this behaviour may be async code running outside Angular zone. In my case it was GoogleApi library. Wrapping its callback in `zone.run` solved my problem with NgOutlet.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by FlamesoFF** [comment]
@AndreiBelokopytov Как это вообще может мешать удалению предыдущего компонента?
