### ISSUE TITLE
    @HostListener - paste in IE11

### ISSUE THREAD

**Issue by boteklub** [angular/angular#17493]
## I'm submitting a part of the code with strange behaviour
<pre><code>
    @HostListener('document:paste', ['$event'])
    onPaste(event) {
        this.paste(event);
    }
</code></pre>

## Current behavior
Chrome, onPaste is attached
IE11, nothing happened

## Expected behavior
On paste event, call onPaste with event obj.

<pre><code>
Angular version: 4.1.3

Browser:
- [ ] IE version 11.296.15063.0
 
For Tooling issues:
- Platform: Windows

**Comment by zoechi** [comment]
Please provide a Plunker as requested in the issue template.

**Comment by tytskyi** [comment]
@boteklub  Please add plunkr, plus try to attach events directly to input. 

As per https://caniuse.com/#search=paste

> IE11: Only fires `copy` event on a valid selection and only `cut` and `paste` in focused editable fields.

**Comment by boteklub** [comment]
Hi, sure. Please, give me some time.

**Comment by boteklub** [comment]
I was unsuccessful run angular 4 app on plunker, but I have attached angular-cli app. Please, try paste something in  Chrome and in IE11.

@tytskyi  Thanks, I found possible solution, in IE I have to be focused in some editable field (in pasteTest project). But still. this should be working without it. There is also possible to add atribute contenteditable="true" to body ... I'm not sure If it will be working.

[pasteTest.zip](https://github.com/angular/angular/files/1074308/pasteTest.zip)

**Comment by zoechi** [comment]
@boteklub The issue template links to an Angular 4 template that is ready-to-use. The "new" button in Plunker also provides an "Angular" template for Angular4.
I wouldn't expect anybody do download and extract a random zip file from the internet.

**Comment by mlaval** [comment]
Scenario reproduced here: https://plnkr.co/edit/9e9USVFBfVkpBzCOhIWu?p=preview

Events behave as per https://caniuse.com/#search=paste

**Comment by ubien** [comment]
The trick is IE11 won't fire paste event unless it's on an element with `contenteditable=true`.  A workaround is to make a hidden contenteditable element and listen for ctrl+v then do `nativeElement.focus()` on the hidden element.  Then `document:paste` fires as expected.
