### ISSUE TITLE
Animation does not work on properties that are specified only in 1 state when animation interupts by new one

### ISSUE THREAD

**Issue by BlindDespair** [angular/angular#17503]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When one animation state contains property that is not specified in another state and change between states happens within transition time of current state change, those properties don't get transitioned back to correct state. Example:
```ts
animations: [
		trigger('state', [
			state(SECTION_STATE.CLOSED, style({
				'height': '0'
			})),
			state(SECTION_STATE.OPENED, style({
			})),
			transition(SECTION_STATE_CHANGE.CLOSE, animate('1500ms ease-out')),
			transition(SECTION_STATE_CHANGE.OPEN, animate('1500ms ease-in'))
		])
	]
```
Animation works properly unless case specified above happens.

## Expected behavior

Properties that are specified only in one state should transition back initial values during 2 changes of state within transition time.

## Minimal reproduction of the problem with instructions

To reproduce create container with children that have their height and put animation with states where height of container is set to 0 and with state where nothing is specified, meaning height should be what it has from its children. Put transition duration to 2 seconds and change state to hide container and during 2 seconds try to change state back.

## What is the motivation / use case for changing the behavior?

In case of height it would be good to save its dynamic nature so it depends on children, other properties like padding are specified in css classes and only changed in 1 state of transition.

## Please tell us about your environment

<pre><code>
Angular version: 4.0.0

Browser:
- [x] Chrome (desktop)Version 58.0.3029.96 (64-bit)
- [x] Firefox version 52.1.0 (64-bit)
 
For Tooling issues:
- Node version: LTS
- Platform: Linux Red hat 6

**Comment by matsko** [comment]
I believe that 23146c920128b3ed48d7e7121d5e618e9da2e53d fixes the problem. The release should be out tomorrow or Thursday.

**Comment by matsko** [comment]
Closing this for now. There have been a few releases so far with this patch and I'm confident that it's gone. Please reopen if anything pops up again.
