### ISSUE TITLE
Tutorial page not displaying source code properly

### ISSUE THREAD

**Issue by seawolf42** [angular/angular#17509]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If a tutorial page is left open for a long time (several days?), code snippets appear as metadata rather than code. For example:
<img width="945" alt="screen shot 2017-06-14 at 07 01 55" src="https://user-images.githubusercontent.com/2721922/27145022-bd6a5f1a-50cf-11e7-8fd4-509131362548.png">

## Expected behavior

The user should see something more like this (clipped from the page after a reload):
<img width="699" alt="screen shot 2017-06-14 at 07 08 46" src="https://user-images.githubusercontent.com/2721922/27145163-600afb44-50d0-11e7-908e-d0a79f553181.png">

## Minimal reproduction of the problem with instructions

Look at the [tutorial's Routing](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html) page, "Refactor routes to a Routing Module" -> "Update AppModule" section in Chrome and leave the tab open for several days. I'm not sure if any other steps are necessary to manifest the issue.

## Please tell us about your environment

<pre><code>
Angular version: N/A

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: N/A
- Platform: OSX 10.12.5
Others:

</code></pre>

**Comment by gkalpak** [comment]
This was an issue with the previous version of the app/content. We have recently (a couple of days ago) released the new version where this is fixed. What I think happened is that you had the old version opened for days, then reloaded and got the new (fixed) version.

Closing, but feel free to open a new issue if you see that again.

**Comment by seawolf42** [comment]
Sounds good, closing sounds fine to me. 

jeff
