### ISSUE TITLE
Translate `select` and `plural` loses references in xliff, xliff2 and xmb files

### ISSUE THREAD

**Issue by CodeAndWeb** [angular/angular#17506]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Translate `select` and `plural` looses references in xliff, xliff2 and xmb files.

I have the following entries in my .html file:

	<span i18n="@@span1">Here we have:
	    {count, plural, =0 {zero} =1 {one}} or {gender, select, m {male} f {female}}
	</span>

	<span i18n="@@span2">Here we have:
	    {gender, select, m {male} f {female}}
	</span>

Note that `span1` and `span2` both use the same `{gender, select, m {male} f {female}}`. The result in xliff now is

      <trans-unit id="span1" datatype="html">
        <source>Here we have:
	         <x id="ICU"/> or <x id="ICU_1"/>
        </source>
        <target/>
        <context-group purpose="location">
          <context context-type="sourcefile">app/dashboard-view/dashboard-view.component.ts</context>
          <context context-type="linenumber">28</context>
        </context-group>
      </trans-unit>
      <trans-unit id="847b0b589338e2d1ec3187b39d01510fce4fe9da" datatype="html">
        <source>{VAR_PLURAL, plural, =0 {zero} =1 {one} }</source>
        <target/>
        <context-group purpose="location">
          <context context-type="sourcefile">app/dashboard-view/dashboard-view.component.ts</context>
          <context context-type="linenumber">29</context>
        </context-group>
      </trans-unit>
      <trans-unit id="14c7055d67771a3b7b6888d282ac092896be06b6" datatype="html">
        <source>{VAR_SELECT, select, m {male} f {female} }</source>
        <target/>
        <context-group purpose="location">
          <context context-type="sourcefile">app/dashboard-view/dashboard-view.component.ts</context>
          <context context-type="linenumber">29</context>
        </context-group>
        <context-group purpose="location">
          <context context-type="sourcefile">app/dashboard-view/dashboard-view.component.ts</context>
          <context context-type="linenumber">34</context>
        </context-group>
      </trans-unit>
      <trans-unit id="span2" datatype="html">
        <source>Here we have:
	         <x id="ICU"/>
        </source>
        <target/>
        <context-group purpose="location">
          <context context-type="sourcefile">app/dashboard-view/dashboard-view.component.ts</context>
          <context context-type="linenumber">33</context>
        </context-group>
      </trans-unit>

The problem is that the reference `<x id="ICU"/>` in `span2` in the second block can't be found. It's not under this block.

From https://angular.io/guide/i18n: 
> The second translation unit, immediately below the first one, contains the select message. Translate that.

In this case:  It's above because it was joined with the translation from `span1` which you can see from the 2 context references in unit `14c7055d67771a3b7b6888d282ac092896be06b6`

## Expected behavior

Add a reference so that the matching translation unit can be found.

## Minimal reproduction of the problem with instructions

See above.

## Please tell us about your environment

<pre><code>
Angular version:  4.2.1
For Tooling issues:
- Node version: 7
- Platform: Mac

Others:
</code></pre>

**Comment by ocombe** [comment]
Ok if I follow your logic, `<x id="ICU"/> or <x id="ICU_1"/>` should both have references using the id `ICU` and `ICU_1`, but instead they have the ids `847b0b589338e2d1ec3187b39d01510fce4fe9da` and `14c7055d67771a3b7b6888d282ac092896be06b6`. That would be more logical yes. Is there a reason for that @vicb ?

**Comment by CodeAndWeb** [comment]
Might be an option - at least there would be a chance to find the reference. 

What about not using the <x id=""/> ? I've tested several translation tools and only one was able to work with the placeholders - the others simply seem to ignore the tags.

**Comment by vicb** [comment]
By design ICU messages are replaced by placeholders when there are inlined in a message.

ie: `"some text {ICU}"` (`{ICU}` being an ICU message) will generates two messages in the message bundle:
- `"some text <placeholder>"`
- `"{ICU}"`

If the ICU message appears on its own `"{ICU}"` then it will generate a single message (`"{ICU}"`)

This is by design so that ICU translation can be re-used: `"some text {ICU}"`, `"some other text {ICU}"` will generate 3 messages:
- `"some text <placeholder>"`
- `"some other text <placeholder>"`
- `"{ICU}"`

Does it explain the behavior you observe or are you observing a different bug ?

**Comment by CodeAndWeb** [comment]
@vicb: Yes - I understand that. The problem is the following: You have no chance of knowing which ICU message is referenced.

* `"some text <placeholderA> <placeholderB>"`
* `"{ICU}"`
* `"{ICU_1}"`
*`"some other text <placeholderA>"`

According to the documentation the ICUs are placed right after the message. So you could assume that in the first message placeholderA references ICU and placeholderB references ICU_1.

But: The ICU from the second placeholder is merged with the first ones. You have no information which one is used.

**Comment by LarsHassler** [comment]
There is an additional problem.
Given the following template:

```html
<span i18n="@@given-i18n-key">some text about {totalCount, plural, =1 {a cat} other {cats}})</span>
```

The following xliff file will be generated:

```xml
<trans-unit id="given-i18n-key" datatype="html">
  <source>some text about <x id="ICU" equiv-text="{totalCount, plural, =1 {...} other {...}}"/>)</source>
</trans-unit>
<trans-unit id="696f53a15a8d23285f2e5583bed6921b27578cea" datatype="html">
  <source>{VAR_PLURAL, plural, =1 {a cat} other {cats} }</source>
</trans-unit>
```

But if we would no refactor the variable name from `totalCount` to `numberOfCats`
The id of the icu message changes from `696f53a15a8d23285f2e5583bed6921b27578cea` to `e1cec494d773d03abe99f930416d5b551f8b9fa4`, because it's a hash of the text content - if i'm not mistaken.
This is a problem for us, as we upload the xliff file to a saas app, where our translation team and agencies are translating it. Which makes it really difficult for them to translate.

Would it be an option to actually sign ids to the ICU messages, which are the parent key plus some suffix - or something similar?
So the xliff file would look like:

```xml
<trans-unit id="given-i18n-key" datatype="html">
  <source>some text about <x id="given-i18n-key__ICU-1"/>)</source>
</trans-unit>
<trans-unit id="given-i18n-key__ICU-1" datatype="html">
  <source>{VAR_PLURAL, plural, =1 {a cat} other {cats} }</source>
</trans-unit>
```

**Comment by ocombe** [comment]
It probably wouldn't help if your saas app doesn't support it. I think that a separate property that links it to its parent id is probably better. There's probably something like that in the xliff spec.

**Comment by LarsHassler** [comment]
I don't think this is a problem with the SaaS.

As stated in the docs (https://angular.io/guide/i18n#set-a-custom-id-for-persistence-and-maintenance) we should use i18n keys everywhere, because otherwise new keys are generated. But for the ICU we can't set any keys, which is a big problem.

**Comment by CodeAndWeb** [comment]
This is not a feature request. It's a bug report

**Comment by petebacondarwin** [comment]
It looks like XLIFF 1.2 has an `xid` attribute that could be used for this. It is not clear whether XLIFF 2.0 has a similar device.
