### ISSUE TITLE
No way to access NgModel from within the component implementing ControlValueAccessor??

### ISSUE THREAD

**Issue by tx8821** [angular/angular#17500]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm creating custom control `MySuperInputComponent` (wrapping over `<input>` tag). My component implements `ControlValueAccessor` and has this provider for `NG_VALUE_ACCESSOR`:

`providers: [{ provide: NG_VALUE_ACCESSOR, useExisting: MySuperInputComponent, multi: true }]`

I want to display validation messages within this component, and for this I need to get access to `NgModel` (to get its `valid`/`invalid`/`errors` properties).

When I inject `NgModel` in the constructor of `MySuperInputComponent`, a get this error:

> Cannot instantiate cyclic dependency! NgModel

**How can I get access to the `NgModel` of my own component?**

## Expected behavior

I should be able to get component's validity status (i.e. access its `NgModel`) from within the component somehow.

Angular version: 4.2.0

**Comment by mlc-mlapis** [comment]
It is not a good idea to get a validation status directly from the custom control. There are some ways but injecting `NgModel`.

**Comment by tx8821** [comment]
Anyone?..

**Comment by tytskyi** [comment]
make sure you really cannot go with another solution, then:

```typescript
constructor(private injector: Injector) {
}

ngOnInit() {
  const model = this.injector.get(NgControl);
  const control = model.control;

  control.statusChanges.subscribe({
    next() => {
      console.log(control.errors)
    }
  });
}
```

**Comment by kara** [comment]
@tx8821 You can inject `NgControl` directly if you set the `valueAccessor` property directly on the control (and don't provide NG_VALUE_ACCESSOR).  `NgControl` is what you'll want because `NgModel` only supports template-driven forms and not reactive form directives like `formControl`.

You can see an example of this alternative setup in the Angular Material select here: https://github.com/angular/material2/blob/master/src/lib/select/select.ts#L332

**Comment by planetmalone** [comment]
I know this is fairly late, but there has been some debate over which approach is considered a better pattern between @tytskyi's approach and @kara's. I was wondering if anyone wanted to weigh in on which one is better and why. If not weigh in, at least site a source. The official documentation seems to be missing this piece.

I personally see the `Injector` as a last resort option, so injecting `NgControl` directly seems the better option on the surface. Are there any benefits to using the `Injector`?

**Comment by crysislinux** [comment]
@planetmalone normally, you will do 
`providers: [{ provide: NG_VALUE_ACCESSOR, useExisting: MySuperInputComponent, multi: true }]`

that's the most common way to provide a new NG_VALUE_ACCESSOR. but once you do that, you cannot inject NgControl here directly.

using Injector changes minimal code to that pattern in my opinion.
