### ISSUE TITLE
Allow short-circuiting `createTypeMap` in DirectiveProcessor

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#1750]
`createTypeMap` walks the import graph looking for classes that extend or implement `Injectable`, which we expect to be slow for large applications. It currently does this in `DirectiveProcessor` for every processed file.

@jakemac53 and I have discussed some potential optimizations for this:
- Create the map once as the first phase of the transform, then serialize it out and read in during `DirectiveProcessor`.
- Allow the user to completely avoid constructing the map by specifing the classes that extend or implement `Injectable`. We can provide this list for the user after running `createTypeMap` once
- Instead of building a comprehensive map prior to beginning the transform, lazily search for specific annotation classes as we encounter them

**Comment by jakemac53** [comment]
Another thing we could do is provide a linter phase, which runs locally in each file and for now just checks if you declare any classes with the blacklisted names and gives a warning? This wouldn't be able to catch package dependencies that declare classes with the blacklisted names though (if they don't have the angular transformer in their pubspec).

**Comment by kegluneq** [comment]
Closed by https://github.com/angular/angular/pull/1772
