### ISSUE TITLE
Validations behave different between mac/chrome and windows/chrome with the html min and html max attributes on inputs

### ISSUE THREAD

**Issue by edgarhsanchez** [angular/angular#17502]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I use the input html element with type="number" min="4" on mac angular detects values less than 4 as an error and adds an error message to the reactive form control's errors collection/array.  However on windows this does not happen.  I'm not sure if it is an html rendering issue or not but I have tested this on chrome on both windows and mac and the issue is the same so my guess is that the Mac uses the same rendering engine for safari, chrome, etc... and that's why it is consistently different from windows/chrome.

## Expected behavior

I would say that the desired behavior is that both windows and mac behave the same in validations.  Either min and max html attributes are ignored or they are adhered to but not behave differently on the platforms as it causes all sorts of headaches and even more bloat as we have to handle this issue differently on both operating systems or browser combinations.

## Minimal reproduction of the problem with instructions

To reproduce this add an input field and set the min value on it.  Then attach a validator to the backing reactive form control.  Then sit back and watch it behave differently between windows/chrome and mac.  

## What is the motivation / use case for changing the behavior?

My motivation is in deep rooted in my love for Angular and the need to have this framework produce excellent products with supporting good practices.  :)

## Please tell us about your environment
I've tested this on Windows/Chrome and Mac/Chrome/Safari with the same effects.
<pre><code>
Angular version: 4.2.

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by danwulff** [comment]
Ran into the same issue of input type="number" fields not causing a form control error with the standard `min` and `max` attributes.

Angular v. 4.2.6
Tested on Windows 10: Chrome, Firefox, Edge and Ubuntu (16.04LTS): Chrome, Firefox. Was unable to see errors on any of these.

Is this a supported feature of Angular/forms? If not this would be a great feature to add ;)

**Comment by kara** [comment]
Can someone add a specific repro case for this in stackblitz or plunker?

**Comment by kara** [comment]
Given that we're not able to repro this and there is no minimal repro, closing for now. The expectation with current code is that min and max errors should never appear, given that the directives were removed.
