### ISSUE TITLE
ngc breaks if run with annotateForClosureCompiler flag on latest TS

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#17516]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

After I updated TS to the latest release (`v2.4`), it seems that `ngc` cannot run the compiler anymore, or tsickle cannot:
```text
W

TypeError: node.getFullStart is not a function
    at Annotator.Rewriter.writeNode (/Users/rolandjitsu/Projects/infarm/core/node_modules/tsickle/build/src/rewriter.js:70:24)
    at Annotator.Rewriter.visit (/Users/rolandjitsu/Projects/infarm/core/node_modules/tsickle/build/src/rewriter.js:53:18)
    at Annotator.maybeProcessEnum (/Users/rolandjitsu/Projects/infarm/core/node_modules/tsickle/build/src/tsickle.js:1188:22)
    at Annotator.maybeProcess (/Users/rolandjitsu/Projects/infarm/core/node_modules/tsickle/build/src/tsickle.js:676:29)
    at Annotator.Rewriter.visit (/Users/rolandjitsu/Projects/infarm/core/node_modules/tsickle/build/src/rewriter.js:52:19)
    at /Users/rolandjitsu/Projects/infarm/core/node_modules/tsickle/build/src/rewriter.js:84:19
    at visitEachNode (/Users/rolandjitsu/Projects/infarm/core/node_modules/typescript/lib/typescript.js:15867:30)
    at Object.forEachChild (/Users/rolandjitsu/Projects/infarm/core/node_modules/typescript/lib/typescript.js:16047:24)
    at Annotator.Rewriter.writeNode (/Users/rolandjitsu/Projects/infarm/core/node_modules/tsickle/build/src/rewriter.js:82:12)
    at Annotator.Rewriter.visit (/Users/rolandjitsu/Projects/infarm/core/node_modules/tsickle/build/src/rewriter.js:53:18)
Compilation failed
```

## Expected behavior

It should be able to run the compilation of TS (and Angular) code.

## Minimal reproduction of the problem with instructions

I cannot share any code due to IP, but I can tell you that removing `annotateForClosureCompiler` from `angularCompilerOptions` fixes the problem (doesn't fix the problem but at least it compiles successfully).

So my `tsconfig.json` looks like:
```json
{
	"angularCompilerOptions": {
		"annotateForClosureCompiler": true,
		"genDir": "../out-tsc/lib-gen-dir/",
		"flatModuleOutFile": "core.js",
		"flatModuleId": "@infarm/core",
		"strictMetadataEmit": true,
		"skipTemplateCodegen": true,
		"debug": true
	},
	"compilerOptions": {
		"baseUrl": "",
		"rootDir": "./",
		"target": "es2015",
                "experimentalDecorators": true,
		"downlevelIteration": true,
		"module": "es2015",
		"moduleResolution": "node",
		"declaration": true,
		"importHelpers": true,
		"noUnusedParameters": true,
		"noUnusedLocals": true,
		"strict": true,
		"sourceMap": true,
		"skipLibCheck": true,
		"inlineSources": true,
		"typeRoots": [
			"node_modules/@types"
		],
		"lib": [
			"es2017",
			"dom"
		],
		"outDir": "../out-tsc/lib-es2015/",
		"types" : [
			"reflect-metadata"
		]
	},
	"files": [
		"index.ts"
	]
}
```

## Please tell us about your environment

<pre><code>
Angular version: 4.2.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.4.0 
- Platform:  Mac 

Others:

</code></pre>

**Comment by chuckjaz** [comment]
I understand that you cannot share the code that is having the problem but can you work on narrowing it down to what language construct is causing Tsickle to crash?

**Comment by rolandjitsu** [comment]
@chuckjaz I'll investigate this week or weekend and I'll post my findings, is that ok?

**Comment by chuckjaz** [comment]
@rolandjitsu Yes.

In the bug information you say that this is "Angular version: 2.4.2". Have you tried to Angular 4? You might also try upgrading the Tsickle to latest. Tsickle uses some internals of TypeScript and needs to be undated if TypeScript changes.

**Comment by rolandjitsu** [comment]
Oh sorry, I meant `4.2.2` 😄

**Comment by Diones** [comment]
Here the same.

* Angular 4.2.3

Also happening after updating to typescript 2.4.0

ps: Changing `annotateForClosureCompiler` as suggested, solves the compilation problem. However, I don't know if that could lead to any side effects. Testing...

**Comment by artemsky** [comment]
```
    "@angular/animations": "^4.2.4",
    "@angular/cli": "^1.2.0",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "typescript": "^2.4.1",
```

Same problem

**Comment by WouterSpaak** [comment]
I've been fighting the same issue with `node.getFullStart is not a function` during a rollup tree shaking build. I pinpointed it down to a string enum, introduced in TypeScript 2.4:

```typescript
@Component({
 // ...
})
export class OptimisticLockComponent implements OnInit {

    /** Determines whether an edit conflict has taken place. */
    hasConflict$: Derivable<OptimisticLock>;

    /**
     * Creates an {@link OptimisticLockComponent} instance.
     * @param {SessionService} session Session instance
     */
    constructor(private session: SessionService) { }

    /**
     * Sets `#noConflict$` to the current activity running edit conflict derivable.
     */
    ngOnInit() {
        this.hasConflict$ = this.session.session.currentActivity$
            .derive(activity => activity && activity.context.dataStore.hasEditConflict$.get())
            .derive(conflict => conflict ? OptimisticLock.Conflict : OptimisticLock.NoConflict);
    }
}

// String Enums do not work right now with Rollup.
export enum OptimisticLock {
    Conflict = 'conflict',
    NoConflict = 'no-conflict',
}
```

Changing it to just string literals works just fine.

```typescript
export class OptimisticLockComponent implements OnInit {

    /** Determines whether an edit conflict has taken place. */
    hasConflict$: Derivable<'conflict' | 'no-conflict'>;

    /**
     * Creates an {@link OptimisticLockComponent} instance.
     * @param {SessionService} session Session instance
     */
    constructor(private session: SessionService) { }

    /**
     * Sets `#noConflict$` to the current activity running edit conflict derivable.
     */
    ngOnInit() {
        this.hasConflict$ = this.session.session.currentActivity$
            .derive(activity => activity && activity.context.dataStore.hasEditConflict$.get())
            .derive(conflict => conflict ? 'conflict' : 'no-conflict');
    }
}
```

(It is worth noting that a `Derivable` is a type from this great state management library: [derivablejs](https://github.com/ds300/derivablejs).)

I quite like the idea of string `enum`s, it seems like a nice, type safe way to work with `*ngSwitch` directives in templates. Of course the compiled implementation is just an object, like so:

```
enum Foo {
  Bar = 'bar';
  Baz = 'baz';
}
```
will compile to
```
const Foo = {
  Bar: 'bar',
  Baz: 'baz'
}
```

I'll continue to look into what `tsickle` does. The original `enum` implementation compiles to a fairly wonkey mess of nested arrays, so perhaps these string `enum`s and their very straightforward implementation might be something `tsickle` chokes on.

For reference, my versions:

```
@angular/cli: 1.1.1
node: 8.1.3
os: win32 x64
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.5

typescript: 2.4.1
tsickle: 0.21.6
rollup: 0.41.6
```

**Comment by chuckjaz** [comment]
Tsickle does not yet support TypeScript 2.4.

Note that TypeScript does *not* follow semantic versioning. Any point release of TypeScript should be treated as a breaking change release as per semantic versioning. Sometimes, patch release are also breaking changes as far as Tsickle is concerned.

**Comment by randyaa** [comment]
any update?

**Comment by chuckjaz** [comment]
Tsickle supports 2.3 and 2.4. We currently plan to support 2.5 in Angular 5.2.

**Comment by pkozlowski-opensource** [comment]
I think that this one is obsolete (we are on TS 3.8)
