### ISSUE TITLE
docs: Lifecycle guide has a misaligned image

### ISSUE THREAD

**Issue by juleskremer** [angular/angular#17510]
<img width="731" alt="screen shot 2017-06-14 at 10 17 28 am" src="https://user-images.githubusercontent.com/12982438/27145482-d3dae268-50ea-11e7-9c51-c35abe03d5d2.png">

**Comment by wardbell** [comment]
If you're referring to the indented blocks in blue, that's actually part of the image itself.

The value of the image itself has been called into question in issue #17298.

We'll rethink it.

**Comment by kapunahelewong** [comment]
See also #17808

**Comment by jenniferfell** [comment]
It looks like this issue was resolved. That image has been removed. 

If this is not resolved to your satisfaction, please reopen or submit a new issue. Thanks for your feedback!
