### ISSUE TITLE
Service worker causes "This site can’t be reached" in Chrome and "Corrupted content" error in Firefox

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17513]
angular.io @ https://github.com/angular/angular/commit/a8afa65a54f9cca5d6cc7880940856b4cf98d49e (but this has been an issue that shows up on and off for a while now, so it's not specific to that commit).

## Repro steps
- go to angular.io => you'll see screenshot 1
- bypass network cache via cmd+shift+r => the site loads
- reload without the bypass => you'll see screenshot 1

Repros both in Firefox and Chrome, just with different error - screenshot 2

Chrome console has some info about what went wrong, but it's not obviously actionable. Screenshot 3&4

The odd thing is that Chrome dev tools claim that there is no service worker installed, yet from the stack traces, it's clear that it's the service worker that causes the error.

## Issues that seem related
- https://github.com/whatwg/fetch/issues/66
- https://github.com/gdg-x/hoverboard/issues/253

### Screenshot 1
<img width="2032" alt="screen shot 2017-06-14 at 10 54 31 am" src="https://user-images.githubusercontent.com/216296/27147934-6af0f84c-50f3-11e7-9aab-5f1c0b75a567.png">

### Screenshot 2
<img width="2032" alt="screen shot 2017-06-14 at 12 09 33 pm" src="https://user-images.githubusercontent.com/216296/27149987-5e8fc8b0-50fa-11e7-9fb4-62d1f35cf628.png">

### Screenshot 3
<img width="2032" alt="screen shot 2017-06-14 at 10 56 23 am" src="https://user-images.githubusercontent.com/216296/27147957-77b60338-50f3-11e7-8f86-dbb6e9e1986a.png">

### Screenshot 4
<img width="2032" alt="screen shot 2017-06-14 at 10 56 03 am" src="https://user-images.githubusercontent.com/216296/27147977-877d0d98-50f3-11e7-914f-b24e53caa427.png">

**Comment by IgorMinar** [comment]
ngsw.log:
```
{
  "state": "READY",
  "lifecycleLog": [
    "manifest 39f963a337863a954dc83992baabfcdfbcddb190 activated",
    "staged manifest 39f963a337863a954dc83992baabfcdfbcddb190 present at initialization",
    "transition from STARTUP to UPDATE_PENDING",
    "updated to manifest 39f963a337863a954dc83992baabfcdfbcddb190",
    "transition from UPDATE_PENDING to READY",
    "cleaned up old version 39f963a337863a954dc83992baabfcdfbcddb190"
  ]
}
```

**Comment by amalshehu** [comment]
Has the same issue.I'm using work box.

**Comment by albandaft** [comment]
Same issue for me with a normal application (no SPA) html + js

**Comment by gkalpak** [comment]
Could this be closed now? The last mention of someone running into this on angular.io was 4 months ago.
(I myself have never seen it.)

**Comment by dmostert** [comment]
Chrome is working for me, but Edge and Samsung browser not working on Android.
Site loads fine the first time, but you can't refresh.

**Comment by IgorMinar** [comment]
@gkalpak no. I haven't seen this in a long time. I think we are good. the Edge and Samsung issue is being tracked separately.

**Comment by TriSysBusinessSoftware** [comment]
It is still happening - see #8206
