### ISSUE TITLE
Component inheritance with ControlValueAccessor is broken in TypeScript 2.4.0

### ISSUE THREAD

**Issue by slavafomin** [angular/angular#17522]
Hello!

I have `CheckboxComponent` class which inherits my custom class `FormComponent` which implements `ControlValueAccessor` interface. This allows me to isolate and reuse common logic related to input management in a single parent (abstract) class which is extended by multiple other concrete components.

This approach worked flawlessly in my application. However, after upgrading to `typescript@2.4.0` this functionality is broken. I'm getting somewhat cryptic error: `TypeError: Object.setPrototypeOf called on null or undefined` at runtime (there are no compilation or any other errors).

- Here, you can find [the complete error message](https://gist.github.com/slavafomin/3e984c169879b074eb9d2d7662036714#file-angular-error-txt).

And here, I'm providing a minimal possible sample of how this could be reproduced:

## CheckboxComponent

```typescript
import {Component} from '@angular/core';
import {NG_VALUE_ACCESSOR} from '@angular/forms';

import {FormComponent} from '../../form-component';


@Component({
  selector: 'my-checkbox',
  templateUrl: './checkbox.component.html',
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: CheckboxComponent,
    multi: true
  }]
})
export class CheckboxComponent extends FormComponent {
}
```

## FormComponent

```typescript
export class FormComponent {
}
```

If I remove `extends FormComponent` or `providers` from metadata, then the error is gone. In other words, **it happens when component extends something and at the same way is registered as `NG_VALUE_ACCESSOR`**.

In previous version of TypeScript (`2.3.4`) it works without hiccups.

- Here, you can find the [output of `yarn list`](https://gist.github.com/slavafomin/3e984c169879b074eb9d2d7662036714#file-yarn-list-txt) command. This should give you an idea of environment in which the error is reproducible.

And I'm testing in Google Chrome `Version 59.0.3071.86 (Official Build) (64-bit)`.

Do you have ideas what could be causing this? Also, is my use case correct?

Thank you!

**Comment by dawidgarus** [comment]
Looks like bug in TypeScript: https://github.com/Microsoft/TypeScript/issues/16506
Also, what I can see from changelog, Angular doesn't support TS 2.4, only 2.3

**Comment by slavafomin** [comment]
@dawidgarus Thanks for the link. If TypeScript `2.4` is not supported by Angular, it must be reflected in the `package.json` generated by NG CLI. Right now, defined version string allows to upgrade past `2.3`.

**Comment by tytskyi** [comment]
@slavafomin i checked with fresh ngcli - `"typescript": "~2.3.3"`. It will not allow to upgrade to 2.4. Only `2.3.x`

**Comment by slavafomin** [comment]
@tytskyi That's nice to hear, thanks for checking this out! Looks like it was changed after I've generated my project. Sadly, we can't make this change working backward.

**Comment by kara** [comment]
Looks like this is encompassed in https://github.com/angular/angular/issues/18454, so closing as a dupe.
