### ISSUE TITLE
Plunkr Templates seem broken: 404 tslib.ts not found

### ISSUE THREAD

**Issue by macjohnny** [angular/angular#17526]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The suggested plunkr template should work fine: 

#### What is the current behavior?
Currently, http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 fails due to an `404 error: tslib.ts not found`

#### What are the steps to reproduce?
Plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by macjohnny** [comment]
See also https://github.com/angular/material2/issues/5143

The solution that seems to work is to adapt the config.js as follows:
```
System.config({
  ...
  map: {
    ...
    'tslib': 'npm:tslib'
  },
  ...
});
```

**Comment by vicb** [comment]
Should be `'tslib': 'npm:tslib@1.6.1'`

`@1.6.1` is for TS <= 2.3.2, see https://www.npmjs.com/package/tslib

**Comment by robwormald** [comment]
This is fixed, thanks @macjohnny 👍

**Comment by Foxandxss** [comment]
We could bump TS too, right?
