### ISSUE TITLE
Feature Request: Allow parent component to control when child in <router-outlet> is loaded

### ISSUE THREAD

**Issue by pcroc** [angular/angular#17529]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
There seems to be no way for a parent component to control the loading of child components into its `<router-outlet>`. In my case I would like to delay loading of child component until the parent has loaded all of its data.

Hiding the `<router-outlet>` within an `*ngIf` condition causes an error that the router outlet could not be found (though this used to be possible with the old router).

Using a resolve guard on the child route to wait for the parent to signal it is ready does not work either, as the guard prevents navigating to the parent.

## Expected behavior
Possible solutions:

1. Allow `<router-outlet>` to be hidden with `*ngIf`
2. `<router-outlet>` exposes an input property to control whether to load the child component
3. An extra lifecycle hook or guard which allows the parent to return a Promise/Observable to indicate when child components can be loaded

## Minimal reproduction of the problem with instructions
I will provide a plunkr if requested, but this is not a bug

## What is the motivation / use case for changing the behavior?
Here is my usecase:
- Parent component displays key information (product name)
- Child component displays some peripheral information (other products of interest)
- Having the peripheral information display before the key information gives a poor user experience
- The child component displays an animation so it is not suitable to just hide the child via CSS

As things are currently, the only possible workarounds I can see are:
1. Tightly couple the child and parent, via a service, so the child explicitly waits for the parent to signal before it does any initialization
2. Do not use the router to control the display of the child component, and instead have the parent explicitly display a specific child component based on the URL

## Please tell us about your environment

<pre><code>
Angular version: 4.2.2

Browser:
- [x] Chrome (desktop) latest version (Ubuntu)
</code></pre>

**Comment by vicb** [comment]
> Allow `<router-outlet>` to be hidden with `*ngIf` 

This should work in 4.2.2, please provide a plunker reproducing the error

**Comment by pcroc** [comment]
You're right, this has been fixed. Not sure why I couldn't get it to work.
Thanks.
