### ISSUE TITLE
Bad UX with annoying tool tips at Angular.io website

### ISSUE THREAD

**Issue by siva636** [angular/angular#17524]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When hovering mouse pointer over a menu item, annoying (and useless in many cases) tool tip pops up and hiding other menu item(s).

## Expected behavior

Tool tips should be removed.

## Minimal reproduction of the problem with instructions

When you hover over 'Forms', tool tip pops up and shows 'Angular Forms' while hiding the next menu item, what is the point here?  Forms chapter will explain about Angular Forms, this is obvious, do you really need to tell that? (see the image bellow)
![image](https://user-images.githubusercontent.com/3191656/27163996-9d92bba4-51a8-11e7-9e62-46501466cc30.png)

When you hover over 'Templates & Data Binding', tool tip pops up and show the same duplicate (useless) information while hiding the next menu (see the bellow image).
![image](https://user-images.githubusercontent.com/3191656/27163851-c27da0ba-51a7-11e7-97df-d17adf3f86bf.png)

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.0 
- Platform: Linux

Others:

</code></pre>

**Comment by alexzuza** [comment]
Also i noticed the next small issue on my iPad
![1](https://user-images.githubusercontent.com/4223314/27167399-a5f32b7c-51b1-11e7-9053-a36822953832.png)

**Comment by m98** [comment]
@alexzuza and @siva636, maybe [angular.io](https://github.com/angular/angular.io) repository is a better place to fill issues about this subject.

**Comment by ericmartinezr** [comment]
@m98 that repo is closed, look at the readme

>This angular.io documentation repository is closed

>Please do not add issues or pull requests to this repo. We are no longer making changes to documentation in this repository. We will no longer process new issues or PRs and we will close them automatically.

**Comment by siva636** [comment]
I also noted that the tool tip hell comes not only on menus but also on source codes in the docs. When we read the codes it may be convenient to move the mouse pointer on the line we read, but here, the tool tip pops up and hides the line we read! (see the image bellow)
![image](https://user-images.githubusercontent.com/3191656/27210091-913cd6e4-526d-11e7-8370-4c17aa98d836.png)

**Comment by siva636** [comment]
[Sorry closed by mistake]

**Comment by siva636** [comment]
I found a temporary solution using Firefox: https://support.mozilla.org/en-US/questions/1081366

**Comment by petebacondarwin** [comment]
We should probably fix the `code-example` tooltip by removing the `title` attribute from the element when the component has initialized.

**Comment by petebacondarwin** [comment]
Closing as the worst offender is fixed and the navigation menu items are a useful accessibility feature. Also as @siva636 points out you can turn these off in FF.

**Comment by siva636** [comment]
**"useful accessibility feature" ?!**

![image](https://user-images.githubusercontent.com/3191656/29442781-6c8ced06-83f1-11e7-8ada-f8dbbebfbf65.png)

**Comment by siva636** [comment]
The technique to disable tooltips on Firefox does not work anymore, we need to fix this anyway.
