### ISSUE TITLE
Export RequestArgs from Http module index

### ISSUE THREAD

**Issue by Pmyl** [angular/angular#17537]
## I'm submitting a ...
<pre><code>[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently if I want to import **RequestArgs** to create a new Request I need to import it from `@angular/http/src/interfaces`

## Expected behavior

I expect to be able to import **RequestArgs** from `@angular/http`. It's the only interface present in `http/src/interfaces.ts` that is not exported by `http/src/index.ts`.

## Please tell us about your environment
<pre><code>Angular version: 4.2.2</code></pre>

**Comment by alxhub** [comment]
Sorry, we're not considering feature requests on `Http`, as it's deprecated.
