### ISSUE TITLE
docs: improvements to 'Ahead-of-Time Compilation'

### ISSUE THREAD

**Issue by Davy-F** [angular/angular#17533]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm currently jumping into AOT and trying to update my application, however the [documentation](https://angular.io/guide/aot-compiler) is still quite confusing. It doesn't state any pre-requisites or dependencies. 

Examples of additional info that would be useful:

- Do I need to install lite-server? lite-server could also benefit from an explanation to why it is required.
- bs-config.aot.json - What/where is this from? I'm guessing it is needed but it is not mentioned in the AOT documentation but is needed for the aot serve script.
- An example package.json which includes the appropriate scripts would also be helpful. I had to manually add the two following scripts:

>     "build:aot": "ngc -p tsconfig-aot.json && rollup -c rollup-config.js",
>     "serve:aot": "lite-server -c bs-config.aot.json",

 and even then I'm not sure if these are correct as it currently errors out.

## Expected behavior

A complete and thorough tutorial on how to implement AOT compilation. 

## Minimal reproduction of the problem with instructions
Read https://angular.io/guide/aot-compiler

## What is the motivation / use case for changing the behavior?
To make the transition and update to AOT a lot easier.

**Comment by dherges** [comment]
First, I think the document should mention `ng` CLI in the first sentences. It should tell that most users should use `ng serve --aot` or `ng build --aot` to switch on AoT.

Second, beginning from "Compile with AOT", I consider the current guide really like an "AOT In-Depth Guide". I think it should be clear and separated an AOT user guide for most end developers and an AOT In-Depth guide for advanced users.

What I, personally, like as a structure for the AOT guide. Wdyt?


## Overview
(keep)
## Ahead-of-time (AOT) vs just-in-time (JIT)
(keep)
## Why do AOT compilation?
(keep)
## Running AOT with the Angular CLI
(write new)
## AOT Best Practices // AOT Development Guidelines
(write new, including:
 - public bound properties
 - `forms.get()`
 - type-checking for template expressions,
 - and so one...

This should include the features/type-checking that comes w/ the `ngfactory` code. I couldn't find anything on the angular.io:
https://medium.com/spektrakel-blog/angular2-going-production-ready-with-ahead-of-time-compilation-aot-developer-experiences-aebaa0228909
https://github.com/AngularClass/angular-starter#aot-donts
https://youtu.be/RXYjPYkFwy4?t=6m44s
... there's probably more out there ... 
)
## AOT In-Depth
(move content from "Compile with AOT" to "Tour of Heroes" here)
### Compile with AOT
...
### Workflow and Convenience Script
### Tour of Heroes

**Comment by Davy-F** [comment]
Thanks for that, @dherges. That would be excellent.

So is angular-cli now the best way to start a new AOT project?

If the documentation could also include some clarification on bs-config.aot.json that would be perfect. I'm confused if it is needed as it's not included in the angular-cli or even mentioned in the AOT documentation? Same with lite-server as it isn't in the dev-dependencies.

**Comment by Davy-F** [comment]
Another thing that would be nice is a .zip file of the example AOT project.

**Comment by dherges** [comment]
Unfortunately, as there is no feedback here, I wrote some guidelines with an example app: [ng-aot-guide](https://github.com/dherges/ng-aot-guide)

@Davy-F FYI! Enjoy!

**Comment by wardbell** [comment]
You make good points.  We'll be reviewing our AOT guides but I don't foresee that coming soon.

We DO plan on explaining the more constrained metadata syntax required by AOT within the next few weeks.

I'll keep this issue open. I

**Comment by dherges** [comment]
Ok!

While this is going to happen, people can read through a story showing AoT with an Angular CLI app:
https://medium.com/spektrakel-blog/angular-writing-aot-friendly-applications-7b64c8afbe3f

**Comment by Davy-F** [comment]
@wardbell Will keep my eyes peeled. I do think a review of the AOT guides would be beneficial though.

@dherges Good stuff. 
We've worked around angular-cli for the meantime and there's no point in us going back now, but appreciate your work on this. Hopefully some others out there can make use of it.

One thing I noticed is that your aot/dist folder contains your ngFactory files whereas our /src folder is copied to aot/src. Our dist folder only contains build.js, which I followed from the official guide. I'm still none the wiser which is the right and wrong way.

Following on from this, another ambiguous issue with the AOT guide is that there is a "copy-dist-files.js" function. 

```
var fs = require('fs');
var resources = [
  'node_modules/core-js/client/shim.min.js',
  'node_modules/zone.js/dist/zone.min.js',
  'src/styles.css'
];
resources.map(function(f) {
  var path = f.split('/');
  var t = 'aot/' + path[path.length-1];
  fs.createReadStream(f).pipe(fs.createWriteStream(t));
});
```

This copies the files to the aot directory. Shouldn't they be copied to the dist folder else why is this called 'copy-dist-files'?

**Comment by fernandojunior** [comment]
More resource

https://blog.angularindepth.com/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5

**Comment by trotyl** [comment]
Obsolete. The AOT guide has been rewritten already.

**Comment by jenniferfell** [comment]
All: As @trotyl mentioned, the AOT doc has been updated and expanded since this issue was opened. We also have a PR open to reorganize the current content to move the compiler options lower in the doc. 

@chembu : Let's put this in your backlog for when you come back to AOT. Let's go through each comment and consider in the context of the current doc. Thanks!

**Comment by jbogarthyde** [comment]
I believe the rewrite and reference PR resolve this issue. If anyone has additional suggestions for improving the AOT doc, please open a new issue.
