### ISSUE TITLE
docs: toh-pt6 - missing Angular-in-memory-web-api NPM dependency

### ISSUE THREAD

**Issue by y3sh** [angular/angular#17535]
## I'm submitting an update request for the tutorial docs

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In following one of the tutorial workflows, the angular in memory web api dependency is missed. As a user, I followed this workflow:

1. Visit https://angular.io/guide/quickstart
2. Complete steps 1-4 (notice the package.json is missing "angular-in-memory-web-api" if entering into the tutorial workflow this way.
3. Read "Next Step" at bottom of page "If you're new to Angular, continue with the tutorial. You can skip the "Setup" step since you're already using the Angular CLI setup."
4. Skipped setup section of the tutorial (still missing in-memory-web-api dependency)
5. Completed tutorial through HTTP: Simulate the web API
6. Error: missing angular-in-memory-web-api 

## Expected behavior

In the tutorial https://angular.io/tutorial/toh-pt6#heroes-and-http, let users know to check for the npm dependency in their package.json if it is not there: `npm install --save angular-in-memory-web-api` dependency.

## Minimal reproduction of the problem with instructions
See Current behavior above.

## What is the motivation / use case for changing the behavior?
Developers learning angular may get stuck at this issue.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [x] Chrome (desktop) version 58.0.3029
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.10.2
- Platform: Mac

Others:
None.
</code></pre>

**Comment by wardbell** [comment]
Probably have similar problem in every sample app that uses the in-mem-web-api. Confirm.

**Comment by steelstring94** [comment]
I have the same problem.  Is there any workaround until this is fixed?

**Comment by y3sh** [comment]
Navigate to your project's folder from the terminal and install the missing dependency with npm:
`npm install --save angular-in-memory-web-api`

**Comment by jenniferfell** [comment]
docarea=tutorial

**Comment by chembu** [comment]
The setup section of the tutorial does not add dependency to in-memory-web-api. instead, HTTP section of the tutorial has instructions to install in-memory-web api. So even if you miss setup instruction in the tutorial, you will still be directed to the step that installs in-memory-web-api.

**Comment by trotyl** [comment]
This one was fixed by https://github.com/angular/angular/pull/19811 as per https://github.com/angular/angular/pull/19811#issuecomment-341901096.
