### ISSUE TITLE
language-service: recognize `template: require("./foo.html")` as a template reference

### ISSUE THREAD

**Issue by mrahhal** [angular/angular#17541]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

One of the ways to solve the issue of consistently loading external templates across different environments is by using webpack + a loader such as [angular2-template-loader](https://github.com/TheLarkInn/angular2-template-loader). This allows us to write the following code:

```ts
@Component({
	selector: 'home-page',
	template: require('./home.html')
})
export class HomePage {
	constructor() {
		this.text = 'foo';
	}
}
```

Which works very well both in development and in production.

## Current behavior
As it is now, the language-service, and in particular [this line of code](https://github.com/angular/angular/blob/5af143e8e43cb1c0d0560c558271f9d3b7201da9/packages/language-service/src/typescript_host.ts#L278), only recognizes a `templateUrl` property as a template reference.

## What is the motivation / use case for changing the behavior?
This of course presents several problems, as the "language-service" won't be able to recognize "./home.html" as a template reference. The problem is more severe when you're using the [vscode-ng-language-service](https://github.com/angular/vscode-ng-language-service) which relies on the language-service to collect template references, as shown in the following issue: angular/vscode-ng-language-service#100.

Would there be any problem if the language-service was able to detect this and recognize the template reference inside the require statement?

I can open a PR if this change is worth considering, as without it some valuable extensions like the [angular/vscode-ng-language-service](https://github.com/angular/vscode-ng-language-service) will never be able to live in a project that uses webpack + require.

**Comment by Toxicable** [comment]
Unless I missed something this method for grabbing a template will not work in AOT

**Comment by mrahhal** [comment]
Can't comment on that, never used AOT really.

**Comment by mrahhal** [comment]
@Toxicable [this](https://github.com/angular/angular-cli/tree/master/packages/%40ngtools/webpack) - and in particular [this line](https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/loader.ts#L310) - suggests that the official webpack AoT plugin actually does exactly that (replaces `templateUrl` with `template: require("...")`.

**Comment by trotyl** [comment]
@mrahhal That's only used in the JIT branch ([here](https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/loader.ts#L467)) or skipCodeGeneration mode for libs ([here](https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/loader.ts#L416)), when under AOT, the template is being compiled to JavaScript code, and the html template will never be loaded to runtime.

**Comment by mrahhal** [comment]
So, not sure why I didn't notice, but "angular2-template-loader" will work with the usual `templateUrl: '...'`. It rewrites this to `template: require("...")` while building. So the problem doesn't apply anymore. Detecting the `require` statement might still be beneficial but not sure if this is worth it anymore.

**Comment by trotyl** [comment]
angular2-template-loader cannot work with AOT either.

**Comment by mrahhal** [comment]
Ah, thanks, makes more sense now.

**Comment by chuckjaz** [comment]
The Angular language service is intended to be used in AOT compliant applications. There are several limitations, beyond the one in this issue, that would prevent the language service from working in a non-AOT'able JIT application.
