### ISSUE TITLE
Wrong date pipe visualization in locale_id 'it' before 1980

### ISSUE THREAD

**Issue by zeniale** [angular/angular#17540]
## I'm submitting a BUG for date pipe with date before year 1980, and month between March and June, with italian LOCALE_ID

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I try to convert date with date pipe and date is between March and June of a year before 1980, i get a wrong conversion. eg: new Date('1979-05-01T22:00:00Z') | date:'dd/MM/yyyy' it returns '01/05/1979'

## Expected behavior
new Date('1979-05-01T22:00:00Z') | date:'dd/MM/yyyy' it should return '02/05/1979'

## Minimal reproduction of the problem with instructions
Here is a live demo:
https://plnkr.co/edit/0lqBNDVUtXMvb0027nLV?p=preview

<pre><code>
Angular version: 4.2.2

Browser:
All Browser
 
</code></pre>

**Comment by ocombe** [comment]
Hello,
I've tried your plunkr in chrome, firefox and edge, and they all show the correct date for me (`Wed May 02 1979 00:00:00 GMT+0200 (Paris, Madrid (heure d’été))`).

What browser did you use? Is your browser using the locale it too? (in my case it's set for the "fr" locale).

I think it's more likely a bug in the intl api than angular. In which case we are working on replacing the intl API (which has many bugs or incorrect implementations across browsers), so that should fix your bug.

**Comment by zeniale** [comment]
Hello,
I tried your plunkr, and I get this result:

> 01/05/1979 23:00 
Wed May 02 1979 00:00:00 GMT+0200 (W. Europe Daylight Time)

My current time zone is (UTC +01:00) Amserdam, Berlin, Bern, Rome, Stockholm, Vienna

If I change te time zone to your (UTC +01:00) Brussels, Copenhagen, Madrid, Paris, I have same result as  you.

That seem is a bug with daylight saving time conversion.

**Comment by ocombe** [comment]
Can you try with the date pipe in v5?

**Comment by ocombe** [comment]
Closing this because of the lack of activity. Don't hesitate to let me know if it should be reopened.

**Comment by Taha-Di-Nero** [comment]
It is not an Angular problem. It is related to the history of Daylight Savings Time (DST) which is specific to each country.

**Comment by zeniale** [comment]
@ocombe 
 Yes, now the date is converted correctly.
The new [format-date.ts](https://sourcegraph.com/github.com/angular/angular@5.0.x/-/blob/packages/common/src/i18n/format_date.ts?utm_source=share#L45:17) method see
