### ISSUE TITLE
[Feature Request] Rename Platform Browser Dynamic

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#17546]
Just call it `boot` or something else short.  Perhaps have a mini naming competition with a list of suggestions.  People can vote with thumbs up on each issue post.

**Comment by hansl** [comment]
`platform-browser-dynamic` actually makes sense semantically; it is a platform (in the Angular sense), for the browser, and is the dynamic (i.e. JIT) counterpart of `platform-browser`. 

Renaming it would be more confusing and there's no compelling reason to do so.
