### ISSUE TITLE
aio: bunch of dgeni warnings that need fixing

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#17549]
https://travis-ci.org/angular/angular/jobs/243431939#L2193-L2207

![screen shot 2017-06-15 at 22 41 20](https://user-images.githubusercontent.com/15655/27203016-cab9517e-521b-11e7-9a78-2d2d01ad5542.png)

**Comment by gkalpak** [comment]
We are [down to one warning][1]:

```
info:    running processor: convertToJsonProcessor
warn:    Title property expected - doc "index" (content)  - from file "index.html" - starting at line 1
info:    running processor: writeFilesProcessor
```

Not sure if there is anything to be done about it. 

[1]: https://travis-ci.org/angular/angular/jobs/257672067#L940-L976

**Comment by petebacondarwin** [comment]
I was thinking we could add in a hidden `h1` tag?

**Comment by petebacondarwin** [comment]
Or perhaps configure the processor to ignore that file?

**Comment by gkalpak** [comment]
We can add a hidden `h1`, but we need to make sure the `TocService` doesn't pick it up.

**Comment by petebacondarwin** [comment]
`<h1 class="no-toc" style="visibility: hidden">`  should do the trick

**Comment by gkalpak** [comment]
Why not `display: none`?

**Comment by petebacondarwin** [comment]
I guess that would work too. (CSS and I, we are like best friends)
