### ISSUE TITLE
SASS is removing support for /deep/

### ISSUE THREAD

**Issue by zoechi** [angular/angular#17557]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior

See also 

- dart-lang/angular2#454
- sass/dart-sass#154

I don't know if node-sass will keep supporting it or what SASS version Angular TS developers might use. 

just to be sure it's on your radar

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by hansl** [comment]
Labeling this as `aio` because they're the only ones using sass in this repo. Thanks!

**Comment by zoechi** [comment]
@hansl This affects all Angular users that use SASS with Angular (at least if they use dart-sass or when `/deep/` support will be removed from other SASS implementations)

**Comment by hansl** [comment]
We'll see how long it takes node-sass to catch up with this. I'm sending this issue to devrel to see if there's anything we can do. Thanks!

**Comment by petebacondarwin** [comment]
There are references to `/deep/` in the [component-styles](https://angular.io/guide/component-styles#deep) page (don't look at the Table of Contents layout problem - it is being fixed).

Ping @wardbell who has had a hand in that doc.

**Comment by petebacondarwin** [comment]
But we are not using it in the `aio` app itself.

**Comment by zoechi** [comment]
@hansl please also check the links in my initial comment. The Dart Angular and the SASS team agreed on a replacement.

**Comment by hansl** [comment]
For those looking around, the replacement suggested by the AngularDart team is `::ng-deep` and it's specific to AngularDart, not SASS itself.

**Comment by Ketec** [comment]
That would be quite disasterous. There is a massive number of third party modules i cannot just go and edit to use alternative replacements.

**Comment by zoechi** [comment]
@Ketec this is why I created the issue, so that there is time to react.

**Comment by IgorMinar** [comment]
this was resolved via b754e60
