### ISSUE TITLE
Add https://github.com/edcarroll/ng2-semantic-ui to the list of resources

### ISSUE THREAD

**Issue by mcosta74** [angular/angular#17559]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior

Have the https://github.com/edcarroll/ng2-semantic-ui listed in the `UI Components` section of https://angular.io/resources

## What is the motivation / use case for changing the behavior?

This library is updated and under active development. It's also a *no jQuery* library and uses only pure Angular code.

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by edcarroll** [comment]
Thanks for this! Have actually already submitted a PR for this (#17523) but doesn't hurt to have an issue too 😄

**Comment by wardbell** [comment]
Closing because of your PR. Keeps the noise down.
