### ISSUE TITLE
layout bug in official website

### ISSUE THREAD

**Issue by RCnowak** [angular/angular#17553]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is a layout problem in official site, at the page https://angular.io/guide/component-styles
http://joxi.ru/KAg55j3HRjQBml

## What is the motivation / use case for changing the behavior?

I found that the problem is the following css-rule for "md-sidenav-container". I think it should be turned off:

aio-shell:not(.view-SideNav) md-sidenav-container.sidenav-container {
    max-width: none;
}

## Please tell us about your environment

<pre><code>

Browser:
- [x] Chrome (desktop) version 58
 
For Tooling issues:
- Platform: Linux

</code></pre>

**Comment by Foxandxss** [comment]
The reason is that for some reason, when we redesigned the nav bar, we took the component styles document out.

When a guide is not "registered" within the nav bar, you get that odd behavior.

Let me investigate.

**Comment by gkalpak** [comment]
Yeah, but I guess it is not intended to have a guide that is not listed in the SideNav, but is only reachable if you know the URL or by searching. We either need to add it to navigation.json (i.e. the SideNav) or remove it entirely (if for some reason we don't need it any more), right?

**Comment by petebacondarwin** [comment]
Don't forget to fix this for `/guide/change-log` as well.

**Comment by petebacondarwin** [comment]
This guide is now back in the navbar and so this one is fixed.
Reopening the changelog one.
