### ISSUE TITLE
Touched - bug

### ISSUE THREAD

**Issue by SearchingSoul** [angular/angular#17555]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Control is marked touched onChange event after the first blur event. 

To be sure:
Step 1: Focus on input
Step 2: Blur
Step 3: Focus
Step 4: Change input  <--- this is when control is marked as touched

Subsequently, this may be a different issue or intended behavior.. I am not sure
Touched bit reverts to false once activated like above.

## Expected behavior

A control is marked touched once the user has triggered a blur event on it.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/bEzEtNc3oPwkwiJ7iWF7?p=preview
Adapted from form validation plunk. Observe field 'Name' 

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by sam-s4s** [comment]
I don't think I understand your bug...

(untouched)
Step 1 - focus on Name
(untouched)
Step 2 - blur (focus on something else, or nothing)
(touched)

And from now on, it's always touched... This seems to be the usual intended behaviour.

**Comment by SearchingSoul** [comment]
@sam-s4s , did u try the plunker on chrome? does it work as expected? Please share your browser version.

I used Chrome Version 59.0.3071.104 (Official Build) (64-bit).

**Comment by sam-s4s** [comment]
Yes, Chrome 58.0.3029.110 (64-bit).

I'l try 59 and see what happens...

**Comment by SearchingSoul** [comment]
As described in the OP. Have a look, hope you notice the click outside the field (might have to look closely). 

![t1](https://user-images.githubusercontent.com/15963977/27275177-efae1728-54f3-11e7-9c37-f060b29cf395.gif)

**Comment by SearchingSoul** [comment]
Ok, I think I did not realise something. The control values are checked only on valueChanges & not on focus or blur events. Will verify that an close this if thats true.

**Comment by SearchingSoul** [comment]
ok.. I was stupid.. thanks @sam-s4s for making me look closely. 

I guess the given logic for reactive forms is not suitable to generate errors after field is marked as touched. May have to find a workaround.

**Comment by sam-s4s** [comment]
Yes, in fact, this is related to an issue I had when trying to make my own wrapper component...

There seemed to be no way to bubble up a touched or dirty event to the parent component.

Because, as you've found out, absolutely no events are emitted when these things happen. The only event is the on value change, which only fires when the actual value changes.

This is the reason I had to write my own version of the forms stuff, including my own touched/dirty/model/validation, etc. What a pain.

Maybe I could be lucky enough to talk to @kara before the next big forms release? :)

**Comment by SearchingSoul** [comment]
I didn't write anything up but heres my hack to make it work.. if it can help someone - use the following in the input if you have followed the reactive form tutorial or the plunker in the OP 

(blur)="onValueChanged($event)  

Don't know any side effects or drawbacks of the above so use at your own risk :)

**Comment by sam-s4s** [comment]
@SearchingSoul can I ask what you're doing? That doesn't seem like a very good solution :D

Obviously then every time the user clicks or tabs off that control, you'll be running your value changed function... even though the value hasn't actually changed!

**Comment by SearchingSoul** [comment]
I was trying to show the field errors right after the input field is marked as 'touched'. I didn't want the field to error out as soon as it got dirty, I wanted it to error out after being touched and that did not happen. 

You are correct that everytime the input is blurred, it will run the value change function and I think thats the easiest way to detect when the field had been marked as touched using the 'onValueChanged' function designed by angular team. I had modified it in the plunker to 
"if (control && control.touched && !control.valid)" from 
"if (control && control.dirty && !control.valid)" in line 82 of reactive.component to do that.
