### ISSUE TITLE
router: metadata on routes

### ISSUE THREAD

**Issue by amcdnl** [angular/angular#17567]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Use Case
Oftentimes in a route definition you want the ability to specify properties that a global listener can observe on. 

For instance, on my route it would be nice to have the ability to have a metadata property that I could attach things like page title to. Then in my app component attach a global route listener that could observe the route change and set the page title in one place vs every page.

## Example
In my route I would specify a `metadata` property to attach misc info to like so:

**dashboard.route.ts**
```javascript
export const routes = [
  { 
    path: '',
    children: [
      {
        path: '',
        component: DashboardComponent,
       metadata: {
          title: 'My Dashboard'
        },
        resolve: {
          data: DashboardResolver
        }
      }
    ]
  }
];
```

then in my app component, I could observe route changes and act appropriately with the new metadata (in this case setting the page title).

**app.component.ts**
```javascript
export class AppComponent {

  constructor(
    private titleService: Title,
    router: Router) {
    
    router.events.subscribe((event: Event) => {
       if(event instanceof NavigationEnd) {
        this.titleService.setTitle(event.metadata.title);
      }
    });
  }

}
```

without this feature I have to manually set the title on every component. There's a variety of use cases that could benefit from this such as permissions, it might look something like:

```javascript
export const routes = [
  { 
    path: '',
    children: [
      {
        path: '',
        component: DashboardComponent,
       metadata: {
          permissions: {
            withAny: [{ type: 'Workspace', action: 'read' }]
          }
        },
        resolve: {
          data: DashboardResolver
        }
      }
    ]
  }
];
```

and then in a global handler you could validate permissions before each transition similar to page title.

There is a use case where the page title idea might not be optimal, such as if you want to set the page title based on the property in a resolve. For instance, in this example I get the dashboard in the resolver and want to set the page title to `Dashboard - ${dashboard.name}`.

**Comment by vicb** [comment]
What you are looking for exists and is the `data` property of the Route config.
The info are merged with the resolved data into the `ActivatedRoute#data`

**Comment by amcdnl** [comment]
Thanks @vicb !
