### ISSUE TITLE
@Inject decorator for factory with InjectionToken parameters

### ISSUE THREAD

**Issue by will421** [angular/angular#17564]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

It raise  

> Decorators are not valid here.

## Minimal reproduction of the problem with instructions

```
export let LABEL_TYPE = new InjectionToken<string>('label.type');

export function labelResolverFactory(labelService: LabelService,@Inject(LABEL_TYPE) type: string){
  return new LabelResolver(labelService,type);
}

export class LabelResolver implements Resolve<Array<Label>> {
  constructor(private labelService: LabelService, private type: string) {
  }

  resolve(route: ActivatedRouteSnapshot) {
    return this.labelService.getLabels(this.type);
  }
}

export let buildingProvider : Provider =   {
    provide: 'buildings',
    useFactory: labelResolverFactory,
    deps: [LabelService,{provide: LABEL_TYPE, useValue: "BUIDLING"}]
  }

```

## What is the motivation / use case for changing the behavior?

Currentluy, AOT does not support arrow method so things like this :

```
export function labelResolverFactory(type: string) {
  return (labelService: LabelService) => {
    return (): Observable<Array<Label>> => {
      return labelService.getLabels(type);
    };
  };
}
export let buildingProvider : Provider =   {
    provide: 'buildings',
    useFactory: labelResolverFactory("BUILDING")
    deps: [LabelService]
  }
```
are not allowed.

This change to @Inject annotation allow for code re-usage in factory.

## Please tell us about your environment
<pre><code>
Angular version: 4.2.2

</code></pre>

**Comment by dherges** [comment]
I don't think this is going to happen. Microsoft/TypeScript#3661

**Comment by kevin-barrientos** [comment]
For anyone looking for a workaround you can try [this](https://stackoverflow.com/a/39281301/3950497):

1. Create a Dependency holder and add it to the providers array
```
@Injectable()
export class YourTokenDepHolder {
  constructor(@Inject(YourToken) public service: Service) {
  }
}
```
2. Create your factory
```
export let YourFactory = (depHolder: YourTokenDepHolder): Service => {
  return depHolder.service;
};
```
3. Add the factory with its dep in the providers array
```
providers: [
    YourTokenDepHolder,
    {
      provide: YourToken,
      useFactory: YourFactory,
      deps: [YourTokenDepHolder],
    },
  ],
```

**Comment by Wilt** [comment]
@kevin-barrientos That results in a cyclic dependency error: 

> Cannot instantiate cyclic dependency!

**Comment by JoostK** [comment]
The original motivation no longer applies to Ivy, it accepts the arrow method in the factory provider.

As for the code for which the invalid decorator was reported, that can actually made to work using the `deps` array:

```ts
export let LABEL_TYPE = new InjectionToken<string>('label.type');

export function labelResolverFactory(labelService: LabelService, type: string){
  return new LabelResolver(labelService,type);
}

export class LabelResolver implements Resolve<Array<Label>> {
  constructor(private labelService: LabelService, private type: string) {
  }

  resolve(route: ActivatedRouteSnapshot) {
    return this.labelService.getLabels(this.type);
  }
}

export let buildingProvider : Provider =   {
    provide: 'buildings',
    useFactory: labelResolverFactory,
    deps: [LabelService, LABEL_TYPE]
  }
```

And the the provider for `{provide: LABEL_TYPE, useValue: "BUIDLING"}` needs to be registered as a provider of its own; that can't be mixed into the `deps` array as was done in the sample code.

Closing as no longer an issue with Ivy.
