### ISSUE TITLE
Doc : Factory with parameter

### ISSUE THREAD

**Issue by will421** [angular/angular#17566]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This guide show how to use factory with parameter.
But this example do not work with AOT as it allow only exported function (not arrow).

## Expected behavior

An example that work with AOT

## What is the motivation / use case for changing the behavior?

Help users with AOT by not showing them exemple that does not work with it.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.2

</code></pre>

**Comment by dherges** [comment]
What guide is actually meant?

Is it the dependency-injection samples which was discussed in #17081 and #17042?

**Comment by will421** [comment]
Yes it is..
Sorry, did not found this one.
