### ISSUE TITLE
aio: Broken link on universal.angular.io

### ISSUE THREAD

**Issue by m98** [angular/angular#17578]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The Universal.angular.io points to version 2 since they merged the Universal API with Angular version 4

On universal.angular.io there is a link with the  text bellow ( download and install Node.js) which points to https://universal.angular.io/quickstart/nodejs.org and it's broken (404)
> make sure you download and install Node.js before getting started

## Expected behavior
We can update the documentation, providing more/better examples, and obviously, all links should work as expected.

**Comment by Foxandxss** [comment]
I am not completely sure that this page is within this repo and it is not part of the AIO project, that for sure.

**Comment by m98** [comment]
I close the issue because of universal.angular.io website is updated and this issue is not there anymore.

**Comment by m98** [comment]
There is still problem, lack of documentation and link to 404 on https://universal.angular.io/quickstart/

**Comment by wardbell** [comment]
This is not a document in the Angular repo. Closing
