### ISSUE TITLE
Unable to bind some attributes on input and textarea elements

### ISSUE THREAD

**Issue by AKArchy** [angular/angular#17579]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm unable to bind some standard HTML attributes to the input or textarea elements due to an "isn't a known property" error.  This includes the following attributes:

For input:

- maxlength
- minlength
- list
- inputmode
- form
- formtarget
- formnovalidate
- formmethod
- formenctype
- formcapture

For textarea:

- maxlength
- minlength
- autocomplete
- form

## Expected behavior

Should be able to bind these attributes since they are standard HTML.  (Most are HTML5 except maxlength on input.)  This is per Mozilla's documentation:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

Some attributes might not be supported by all browsers (esp IE/Edge), but maxlength in particular should work:

http://caniuse.com/#feat=maxlength

## Minimal reproduction of the problem with instructions

1) To any template, add an input or textarea element with a binding for maxlength, like so:

<pre><code>

<input type="text" [maxlength]="maxlength"/> 
<textarea [maxlength]="maxlength"></textarea>

</code></pre>

Or run this example here:
https://plnkr.co/edit/76zlU9244sH5HEAyLqcG

2) Check the dev console and see this error:

<pre><code>
Error: (SystemJS) Error: Template parse errors:
	Can't bind to 'maxlength' since it isn't a known property of 'input'. ("
	    <input type="text" [ERROR ->][maxlength]="maxlength" value="testing" />
	    <textarea [maxlength]="maxlength">
	      Testing
	"): ng:///AppModule/App.html@1:23
	Can't bind to 'maxlength' since it isn't a known property of 'textarea'. ("
	    <input type="text" [maxlength]="maxlength" value="testing" />
	    <textarea [ERROR ->][maxlength]="maxlength">
	      Testing
	    </textarea>
	"): ng:///AppModule/App.html@2:14
	    at syntaxError (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1724:34)
	    at TemplateParser.parse (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:12836:19)
	    at JitCompiler._compileTemplate (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26882:39)
	    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26802:62)
	    at Set.forEach (native)
	    at JitCompiler._compileComponents (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26802:19)
	    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26689:19)
	    at Object.then (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1714:92)
	    at JitCompiler._compileModuleAndComponents (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26688:26)
	    at JitCompiler.compileModuleAsync (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26617:37)
	Error loading https://run.plnkr.co/uRGSabvbsUT3cfOx/src/main.ts
</code></pre>

## What is the motivation / use case for changing the behavior?

I should be able to bind all standard HTML attributes to these elements.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3 (latest)

Browser:
- [ x ] Chrome (desktop) version 58.0.3029.110 (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x ] Firefox version 54.0 (32-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ x ] Edge version 38.14393.1066.0
 
For Tooling issues:
- Node version: 6.10.2
- Platform: Windows 10

Others:

</code></pre>

**Comment by Gillespie59** [comment]
This syntax in a template is used for HTML properties, not attributes. 
If you need to make dynamic attribute, you need to use this syntax :

[attr.colspan]=""

**Comment by AKArchy** [comment]
Thanks, that works!

One question, though: several attributes specific to input and textarea elements work without the "attr." prefix, such as "rows," "size," "step," etc.  What is the criteria for which HTML properties require the "attr." prefix and which ones don't?

**Comment by Gillespie59** [comment]
You should have a look to the HTMLTEXTAREAELEMENT interface : https://www.w3.org/TR/html5/forms.html#the-textarea-element
