### ISSUE TITLE
DatePipe doesn't support local Dates in Safari

### ISSUE THREAD

**Issue by christarczon** [angular/angular#17576]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

There are lots of issues floating around with internationalization and the DatePipe itself but I couldn't find mention of this. Safari 10 isn't supposed to need it but I tried the Intl polyfill and it doesn't seem to affect anything.

## Current behavior
DatePipe formats days off by one, different depending on timezone. Testing by changing my OS timezone, I see that far west timezones like Pacific are fine, eastern hemisphere zones break every date, my Central daylight zone has issues with certain dates.

## Expected behavior
Formatted date should match input.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/Lso5JZgR34UQhlDN35he?p=preview

## What is the motivation / use case for changing the behavior?
Browser consistency

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 10.1.1 and Tech Preview
- [x] Safari (iOS) version 10.3.2
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by wKoza** [comment]
'Note: Where Date is called as a constructor with more than one argument, the specifed arguments represent local time. If UTC is desired, use new Date(Date.UTC(...)) with the same arguments.'
see : [Documentation Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

[https://plnkr.co/edit/4NEddsKYIWmC6Js0Uwws?p=preview](https://plnkr.co/edit/4NEddsKYIWmC6Js0Uwws?p=preview)

**Comment by christarczon** [comment]
Is the DatePipe only meant to support Date objects with UTC values? [The doc](https://angular.io/api/common/DatePipe) doesn't mention it.

**Comment by ocombe** [comment]
There is a third argument to the date pipe (which is not documented yet, it will be once I've removed the intl api) that you can use to set the timezone of the date. For example use "+0100" to set the timezone to GMT+1. Otherwise the date will be shown based on the timezone of the browser.

Does it fix your problem?

**Comment by wKoza** [comment]
@ocombe  Why will you remove the intl api ? and when ?

**Comment by ocombe** [comment]
Because it has a lot of issues that we cannot fix: inconsistencies between browsers, missing features, missing api (in some browsers, which means a polyfill that we don't control either), ... The API is just too immature to be used in Angular.
I'm working on replacing it with our own set of data & features right now (much like what we have in AngularJS), it should be available in v5 if I can finish it in time.

**Comment by wKoza** [comment]
Thanks @ocombe , it's a good news (there are many problems on mobile phones...) . Good luck with the work.

**Comment by martinmcwhorter** [comment]
@ocombe Is there a ticket/branch to track removing/replacing Intl API? 

I personally would be interested in following this work as it will bring many changes with it. 

One issue is the formatting large ( > 32bit signed) numbers.

**Comment by ocombe** [comment]
@martinmcwhorter you can follow it here: https://github.com/angular/angular/issues/10809
Not much to see yet, just a list of issues to fix with the replacement of the intl api. But if you have ideas about what you would like to see fixed, that would be the place to add it
