### ISSUE TITLE
ng-content and textarea compatibility issue

### ISSUE THREAD

**Issue by unsinkable-sam** [angular/angular#17586]
I have a custom `my-textarea` component with the following template:
```
<textarea>
  <ng-content></ng-content>
</textarea>
```
When I test the component and try to place some text in it (as we do with a normal `textarea` html element):
```
<my-textarea>some text</my-textarea>
```
I get an empty `textarea` without the expected string, `some text`, inserted inside the component.
Any idea why could this be happening?
There is probably a compatibility issue between `ng-content` and `textarea`.

**Comment by wKoza** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
