### ISSUE TITLE
angular.io is not rendered in Mobile Safari on iOS 8

### ISSUE THREAD

**Issue by bisubus** [angular/angular#17587]
## I'm submitting a ...

<pre><code>
[x] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

angular.io pages are not not rendered. `undefined is not a function` error is thrown that points to [this line](https://github.com/angular/angular/blob/3e51a1998304ab6a15e5bea6bc66e7a8c636a8ad/packages/core/src/change_detection/change_detection_util.ts#L91).

The problem is likely caused by the way how currently used polyfill library (polyfill.io) polyfills iterators. Even when polyfill.io iterator polyfills are added explicitly to `default` set, the error doesn't go away.

![aio-ios](https://user-images.githubusercontent.com/2905949/27255110-e0794160-539f-11e7-8944-6a9c71fd8b65.png)

## Expected behavior

The page should be rendered normally with all necessary polyfills.

It was possible to make angular.io workable with other polyfill libraries (namely es6-shim and core-js) instead of polyfill.io.

## Minimal reproduction of the problem with instructions
Loading angular.io in Mobile Safari on iOS 8 (or likely a correspondent version of desktop Safari).

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [x] Safari (iOS) version 8
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by IgorMinar** [comment]
I was able to get only ios 10.3 and there the app renders correctly: https://www.webpagetest.org/result/171127_2X_ab9b55077a7aca97ddbcb322991b0e66/

I don't think we need to support older versions than that.

**Comment by bisubus** [comment]
@IgorMinar Upgrade to latest iOS is a big concern for some devices. The problem I see here is that Angular documentation isn't available in any readable form on mobile devices, while this issue could be addressed just by applying proper polyfills.

**Comment by IgorMinar** [comment]
@bisubus  "on mobile devices" is a very vague definition. The site works for most visitors, but it's true that we don't test the site on older devices. Are you on ios8? What version of safari?

**Comment by bisubus** [comment]
@IgorMinar Yes, it is Mobile Safari and iOS 8. I guess it conforms to desktop Safari 8, feature-wise. All non-evergreen browsers are now affected, too. Android 4 built-in browser, highly popular UC Browser, etc. An iOS device was my primary concern because there's no option for third-party browser engines.

As I can see, polyfill.io was discarded, and angular.io currently [doesn't use polyfills at all](https://github.com/angular/angular/blob/master/aio/src/polyfills.ts) (except for IE conditional polyfills). It looks like compatibility problem is currently much bigger than dated iOS versions; I'm unable to precisely estimate but it can affect up to 10% of visitors.

I'm not sure if angular.io home page is a big deal, but considering that documentation is a part of angular.io and no offline documentation is officially provided, allowing users to freely access the documentation would definitely benefit the framework.

**Comment by bisubus** [comment]
@IgorMinar, I investigated the problem further, and it appears that the issue was primarily caused by non-compliant Map polyfills from polyfill.io; Financial-Times/polyfill-service/issues/1409 will likely be fixed shortly.

Currently non-evergreen browsers suffer from #18921 regression in Angular 5.

Another problem that appeared in Angular 5 can be fixed by adding `WeakMap` to [polyfill.io configuration](https://github.com/angular/angular/blob/3def2cc5527a893dbf5e86e6902e9f3f8f98620e/aio/src/index.html#L56).

With minimal efforts these changes can make the website readable again in several percents of browsers (primarily mobile) that are currently unsupported yet still in use.

Considering that there are no other major problems, can PR be expected to be merged for current issue?
