### ISSUE TITLE
getBoundingClientRect() delay

### ISSUE THREAD

**Issue by MrCroft** [angular/angular#17588]
## I'm submitting a ...
```
[x] Bug report
```

## Current behavior
In the code below:
```
  ngOnInit() {
    this.offset = this.el.nativeElement.getBoundingClientRect().width / 3;
    this.doAnimate = true;
  }
```
`this.offset` is actually set **after** `this.doAnimate = true;`

## Expected behavior
property `offset` should be set before `doAnimate`

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/nk43DlXrbqQwbCiCzajX?p=preview
The green div shouldn't have transition applied initially, before translating it to the propper position, since transition depends on `doAnimate`, which should be set to `true` **after** setting the `offset` property.

## Please tell us about your environment
```
Angular version: 4.2.3
```

**Comment by SteveVanOpstal** [comment]
Angular updates the view when it sees fit, therefore you cannot rely on it handling these actions one by one.

You can probably do what you want with https://angular.io/guide/animations.

**Comment by MrCroft** [comment]
@SteveVanOpstal 
**I would have at least expected it to work on `ngAfterViewInit` then - but it doesn't.**
If I simply wrap it like this: `setTimeout(() => { this.doAnimate = true; }, 0);` it works.

This has nothing to do with animations. You might have been misled by my "doAnimate" property, if you've rushed to read.

**The issue is:** when the component instantiates, I need to programmatically set a css property (`transform`) that, otherwise (later on) will be animated on hover, for example (and that animated css property is dynamic). In order to enable/disable the css `transition` I use that `doAnimate` boolean.
```
<div
    [ngStyle]="{
          'transform': 'translate3d(' + offset + 'px, 0, 0)',
          'transition': doAnimate ? '450ms transform' : ''
      }"></div>
```
And I can't use Angular animations because my `offset` value is dynamic and, although since Angular 4.2 we have input params, the `state()` doesn't see the input params (#17362), so I can't keep the animation end state - unless I'd go into `@trigger.done` callback to set the appropriate transform style property when the animation ends.

If you can think of any solution for this, that is not "hacky", I would gladly try it out... But I can't think of any.

**Comment by SteveVanOpstal** [comment]
I'm not sure that I completely get what you want, but do you only want to animate on `hover`?
Because a little css can perform this easily:

``` CSS
div:hover {
  transition: 450ms transform;
}
```

Keep the transform:
``` HTML
<div [ngStyle]="{ 'transform': 'translateX(' + offset + 'px)' }"></div>
```

**not tested**

**Comment by MrCroft** [comment]
Well, if you have `transition` defined only on `:hover`, as soon as you mouse-out, the element snaps back into place, instead of smoothly being translated back.
Plus, if speed also becomes a variable, then the `transition` property would have to be set inline.
I wrote a very simple example to illustrate the issue. In the real application, in addition to shifting the element on mouse over, other elements around it are also shifted to create some space... and shifted back when the mouse leaves the current element.  Plus, the speed is computed at runtime. So, writing css anywhere else except inline, is not an option.

**TL/DR:**
I only created the simplest example to illustrate what I think **it's a bug** I've discovered, because when the component has initialized (or **at least after view init** or after content init), Angular should be able to simply grab the width of the host element, in the order the code is written in... **shouldn't it?**

For the time being, I've managed to do it with angular animations. First I'm setting the desired end-state transform property inline on mouseenter. Then I change the state and input params to animate **from a start value** to the end value. Key here is **always** specify a start value, as we can't use `*` as start in our animation, since I'm also setting transform inline - to have that there for when the animation ends, since `state()` doesn't take input params, hence I can't have states defined. Hopefully, `state()` will also take input params in angular 4.3.

**Comment by SteveVanOpstal** [comment]
> Angular should simply grab the width of the host element, in the order the code is written in... shouldn't it?

What I think that happens in your two examples is this:
1. One update
``` JS
    this.offset = this.el.nativeElement.getBoundingClientRect().width / 3;
    this.doAnimate = true;
    // view update
```
2. Two updates
``` JS
    this.offset = 200;
    // view update
    this.doAnimate = true;
    // view update
```
Depending on the timing of Angular, one of both happens.

**Comment by matsko** [comment]
I understand that this issue a few months old and now both 5.x and 4.x allow for input param values to be passed into states. I'm going to close this for now. Please reopen if you're still unable to get something to work.
