### ISSUE TITLE
routerLinkActive is wrong when URL path with a subfolder in the path has the same root  

### ISSUE THREAD

**Issue by alex75it** [angular/angular#17583]
## I'm submitting a ...
<pre>
[X] Bug report
</pre>

## Current behavior
When the URL contains a part in the path that is defined in a different RouterLink it wrongly sets RouterLinkActive to true.

## Expected behavior
The RouterLinkActive should be false.

## Minimal reproduction of the problem with instructions
<pre><code>
< a routerLink="/aaa"    routerLinkActive="active">AAA< /a >
< a routerLink="/aaa/bbb" routerLinkActive="active">AAA bbb< /a >
</code></pre>
Navigating to "/aaa/bbb" both the link are set as "active".

## What is the motivation / use case for changing the behavior?

I have defined these paths in app-routering-modules.ts:
<code>
const routes: Routes = [
    { path: "aaa", component: AAAListComponent },
    { path: "aaa/stats", component: AAAStatsComponent }
]
</code>
Them work as expected:
- the relative component is called
- the browser URL is set correctly
- the RouterLink or routerLink works

In the ```<a>``` element using routerLinkActive when the URL is "/aaa/stats" both "aaa" and "aaa/stats" are set as "active".  
Error: "aaa" is not the active link route and should not be set as "active".

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3 (latest)

Browser:
- [X] Chrome (desktop), latest version 
- [X] Maxthon, latest version
 
For Tooling issues:
- Node version: 7.x
- TypeScript 2.1.0
- Platform: Windows 

Others:

</code></pre>

**Comment by tytskyi** [comment]
`[routerLinkActiveOptions]="{exact: true}"`

**Comment by alex75it** [comment]
It works.
Many thanks.
