### ISSUE TITLE
docs: ajs-quick-reference broken/missing example 

### ISSUE THREAD

**Issue by tyeth** [angular/angular#17582]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Under *https://angular.io/guide/ajs-quick-reference#bind-to-the-href-property* is the example box with an error message stating:

```
The code sample is missing for
ajs-quick-reference/src/app/app.component.html#router-link
```

## Please tell us about your environment

<pre><code>
Angular version: Latest

Browser:
- [ x] Chrome (desktop) version Latest (linux ubuntu google official)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by tyeth** [comment]
Keep up the great work on Angular, been 2years since I checked in on ko + ng and the ng world has fully blossomed, nice to see.

**Comment by Foxandxss** [comment]
Thanks, will fix.

**Comment by kapunahelewong** [comment]
Hi @tyeth, thanks for this. It has since been fixed (or I can't duplicate). Are you still in need of help with this? If so, please let me know.
