### ISSUE TITLE
Extend @Component.styleUrls to support ViewEncapsulation on each styleUrl

### ISSUE THREAD

**Issue by matthewerwin** [angular/angular#17591]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular loads all stylesheets specified in the styleUrls: string[] using the ViewEncapsulation set at the component level.

## Expected behavior

When using 3rd party libraries such as Bootstrap it may be desirable to only have a portion of the styles for the component set to ViewEncapsulation.None and the rest as Emulated/Native.

By extending Component.styleUrls to allow an array which allows the encapsulation to be specified per stylesheet (while retaining the component default) it will be easily possible to override external styles without making all stylesheets included in the component global/local.

## What is the motivation / use case for changing the behavior?

Increases the use of Emulated/Native over None. 

Avoiding problems where only one or two CSS classes need to override a global style when that component is rendered but where now suddenly all classes across all styleUrls become global (ViewEncapsulation.None) when the majority make sense to remain as scoped (Emulated/Native)

## Please tell us about your environment

<pre><code>
Angular version: 4.2.2

Browser:
- [ X ] Chrome (desktop) version XX
- [ X ] Chrome (Android) version XX
- [ X ] Chrome (iOS) version XX
- [ X ] Firefox version XX
- [ X ] Safari (desktop) version XX
- [ X ] Safari (iOS) version XX
- [ X ] IE version XX
- [ X ] Edge version XX
 
For Tooling issues:
- Node version: 7.4 
- Platform: Mac 

</code></pre>

**Comment by hansl** [comment]
Hi @matthewerwin,

Actually, ViewEncapsulation is a property of the Component itself, not its stylesheet. The Renderer renders the DOM differently, and so it doesn't just affect styles. The whole component is rendered differently, and it's not possible (nor feasible) to support multiple view encapsulation for a single component.

Closing this.
