### ISSUE TITLE
Set Up Performance CI Server

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#176]
Create a jenkins instance on a local workstation to run full suite of performance benchmarks on every commit to master. Results should be reported to an external server with a basic UI for tracking performance progress for each component over time.

Pending [some changes](https://github.com/angular/benchpress/milestones/Q4%202014) to the benchpress runner, and creation of more benchmarks in this project.

**Comment by mhevery** [comment]
Done by @tbosch
