### ISSUE TITLE
Template bug of "Change Log" page.

### ISSUE THREAD

**Issue by dorohin** [angular/angular#17604]
https://angular.io/guide/change-log

Display: 15.6" 1920x1080
Google Chrome	59.0.3071.104
![angular - change log - google chrome 2017-06-19 12 30 59](https://user-images.githubusercontent.com/24988081/27278841-3f0f8c4c-54eb-11e7-90ee-b60cb6fe2665.png)

**Comment by gkalpak** [comment]
This is similar to #17553 (happens because `/guide/change-log` does not appear in the SideNav - i.e. is not included in `navigation.json`).

**Comment by petebacondarwin** [comment]
Closing as a duplicate of #17553

**Comment by petebacondarwin** [comment]
Reopened as the other issue was fixed only for that guide by putting it in the nav.
