### ISSUE TITLE
HTTP Module: 304 status code incorrectly propagated as Error 

### ISSUE THREAD

**Issue by otienoanyango** [angular/angular#17605]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I send an IF-None-Match header with an ETag but when the 304 is returned, http module treats it as an error

## Expected behavior

Return success with empty response body and let the developer handle the propagation of response body. This only applies when the user sends a If-None-Match or similar header, otherwise the browser would normally mask this into a 200 and hence no problem.

## What is the motivation / use case for changing the behavior?

304 should not be an error to be caught because it is not. 

## Please tell us about your environment

<pre><code>
Angular version: 4.1.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>
Using AuthHttp from angular2-jwt to extend Http with jwt but this simply propagates the error, not create it.

**Comment by rodaz** [comment]
Any news with this? Will you fix this, or it's proper behavior?

**Comment by alxhub** [comment]
It's proper behavior. All non-2XX codes are treated as errors.

**Comment by otienoanyango** [comment]
Thanks for the clarification on the angular implementation.
