### ISSUE TITLE
Observable map doesn't perform types conversion?

### ISSUE THREAD

**Issue by xTaz1** [angular/angular#17600]
```
@Injectable()
export class MockService {
  constructor(private http: Http) {
  }
  getMocks(): Observable<MockModel> {
    return this.http.get('some-url').map(r => r.json() as MockModel);
  }
}

@Component({
 ...
})
export class TestComponent implements OnInit {
  constructor(private mockService: MockService) {
  }
  ngOnInit() {
    this.mockService.getMocks().subscribe(r => console.log(typeof r));
  }
}

```

## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Object

## Expected behavior

MockModel

<pre><code>
Angular version: 4.0.0

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.10
- Platform: Linux

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jotatoledo** [comment]
In that case, the return of `r.json()` is basically a `POJO `and its type is just `Object.  If you defined MockModel as a class, then you will have to create a new instance by using the constructor method, not just cast the POJO into the type.

**Comment by xTaz1** [comment]
@jotatoledo r.json() as MockModel

**Comment by Toxicable** [comment]
@xTaz1 you can close it since you opened it.
