### ISSUE TITLE
(click) Event Bug

### ISSUE THREAD

**Issue by GSeriousB** [angular/angular#17602]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In the component's template (separate .html file) I've forgot to write something to the (click) event. It looked like this:  <pre><code>(click)=""</code></pre>

So it didn't render the page. I've solved this error ( (click)="something()" ), but the browser (Microsoft Edge) still displayed in the console the same error and it didn't render the page.

I've reopened Windows PowerShell, entered "ng serve" and it worked.

I think this is angular's bug. Or not?

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [X] Edge version 40.15063.0.0
 
For Tooling issues:
- Node version: 6.10.2
- Platform: Windows 10
- Editor: VS Code

Others:

</code></pre>

**Comment by Toxicable** [comment]
This isn't a bug, read the error you got; it states: `Error: Template parse errors: Empty expressions are not allowed`
