### ISSUE TITLE
@HostBinding always sets lowercase attribute names ignoring original case declaration

### ISSUE THREAD

**Issue by aaroncalderon** [angular/angular#17610]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When usning `@HostBinding('attr.fxLayout') fxLayout = "row wrap";` the attribute is set as `fxlayout="row wrap"` (notice the lowercase __L__ on "fxLayout".

## Expected behavior

When usning `@HostBinding('attr.fxLayout') fxLayout = "row wrap";` the attribute sould be set as `fxLayout="row wrap"` (notice the upercase __L__ on "fxLayout".

## Minimal reproduction of the problem with instructions

To reporduce this issue, include `HostBindig` from `@angular/core`:

```javascript
import {Component, NgModule, VERSION, HostBinding} from '@angular/core'
```

And declare an attribute with `@HostBinding` on your app class with uppercases in the name:

```javascript
 @HostBinding('attr.fxLayout') fxLayout = "row wrap"; 
```

Demo [plunker](http://plnkr.co/edit/9J7weNTz7UmdISPWmCIa?p=info)

## What is the motivation / use case for changing the behavior?

I was trying to use [flex-layout](https://github.com/angular/flex-layout) and I noticed that I was not able to get the desired result when setting the `fxLayout` to __row wrap__, then I noticed that the attibute was set as all lower case on my app selector tag.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [X] Chrome (desktop) version 58.0.3029.110
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.5.0
- Platform: Windows 

Others:

</code></pre>

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/27316724-45c5ef44-55b4-11e7-80c5-8560e4852cf7.png)
![image](https://user-images.githubusercontent.com/6059170/27316729-5a426786-55b4-11e7-982d-435af172df7e.png)


HTML Attribute is not case-sensitive in semantic AFAIK, and `fxLayout` is an `@Input()` rather than an attribute in [LayoutDirective](https://github.com/angular/flex-layout/blob/master/src/lib/flexbox/api/layout.ts#L53), it won't be affected by the attribute anyway.

**Comment by aaroncalderon** [comment]
@trotyl In other words, I'm doing it wrong. :disappointed: 

If anyone would like to poin me in the right direction, I will appreciate it.

Otherwise, I believe this issue sould be closed.

**Comment by aaroncalderon** [comment]
Seems this an issue regarding this topic has been already opened with the [flex-layout community issue #76](https://github.com/angular/flex-layout/issues/76)

**Comment by ThomasBurleson** [comment]
@aaroncalderon - this is not a flex-layout issue. Rather this is a Angular Compiler issue: see https://github.com/angular/angular/issues/14114.
