### ISSUE TITLE
AOT: "Cannot GET /" error

### ISSUE THREAD

**Issue by Davy-F** [angular/angular#17625]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have recently upgraded to Angular4, along with AOT. I mainly followed the [official guide](https://angular.io/guide/aot-compiler#aot-quickstart-source-code) from Angular.io

It took a while to work around the errors, but the app now successfully compiles and creates the aot build and ngfactory files from the src. Due to this, I don't think this error is a problem with the build, but probably more of an issue with my config files and paths. As far as I'm aware though these _should_ be correct. The only one I'm not too sure about is the bs-config,aot.json.

Anyway. I call the following two scripts which compiles and serves the app:

>   "build:aot": "ngc -p tsconfig-aot.json && rollup -c rollup-config.js",
>     "serve:aot": "lite-server -c bs-config.aot.json",

This creates the following log in the command window:
(Note that it doesn't error here)

Command Window:
![image](https://user-images.githubusercontent.com/19592376/27324189-446c9d36-559c-11e7-9124-9f4df777fa1a.png)

However in the browser I get the following error, **"Cannot GET /":**

Browser Output:
![image](https://user-images.githubusercontent.com/19592376/27324099-ed3fdc6c-559b-11e7-9956-389b46d56e84.png)

Unfortunately this is quite an ambiguous error, but I assume that it is because it cannot find the index.html? However my paths seem to be correct (to me anyway!).

Also one thing I noticed is that the index.html file does not get copied to the aot file. Is this default behaviour?

## Expected behavior
The App should run successfully in the browser and load the index.html, after it has compiled successfully with AOT.

## Minimal reproduction of the problem with instructions
Plunker: https://plnkr.co/edit/PJDER8Lm4XyYiuFdlOKh
Unfortunately this won't compile as my app is quite complex, so I have removed certain files and reproduced the config files which I believe might be home to the issue.

I'm hoping that the plunker should be enough to show my AOT config. Apologies!

## Please tell us about your environment

<pre><code>
Angular version: 4.2.2
Typescript version: 2.2.0

Browser:
- [x] Chrome (desktop) version 58.0.3029.110 (64-bit)
 
For Tooling issues:
- Node version: v6.11.0
- NPM version: 3.10.10
- Platform: Windows 7

</code></pre>

As always any help would be kindly appreciated as I've been stuck on this for a while now. Thank you.

**Comment by Davy-F** [comment]
So it turns out I was missing the index.html file in my /aot folder.

```
<!DOCTYPE html>
<html>
  <head>
    <base href="/">
    <title>Yay!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
    <!--<link rel="stylesheet" href="styles.css">-->
 
    <script src="shim.min.js"></script>
    <script src="zone.min.js"></script>
  </head>
 
  <body>
    <my-app>Loading...</my-app>
  </body>
  <script src="dist/build.js"></script>
</html>
```

I'm guessing this is something I had to manually create and wouldn't copy over from the src/index.html?

Now getting the following error, though. Which at least is a bit more helpful...

> ERROR Error: The selector "app" did not match any elements
>     at t.selectRootElement (build.js:1)
>     at t.selectRootElement (build.js:1)
>     at me (build.js:1)
>     at Wn (build.js:1)
>     at Bn (build.js:1)
>     at Br (build.js:1)
>     at Object.dr [as createRootView] (build.js:1)
>     at n.create (build.js:1)
>     at n.create (build.js:1)
>     at n.bootstrap (build.js:1)

**Comment by SteveVanOpstal** [comment]
Is there an index.html located where localhost directs to?
Your Plunker setup indicates that there is a `aot/dist` folder to which you let localhost direct. This folder only seems to contain `aot/dist/build.js`.

**Comment by SteveVanOpstal** [comment]
Ok great. I believe you can close this issue then. Also when you have a question which is not Bug Report, please address them to StackOverflow
