### ISSUE TITLE
Provide a visual signal for external links

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17620]
## Current behavior
Currently inspecting the target url is the only way for a reader of our docs to know if clicking on a link will take them to an external resource. This is time consuming and often leads to readers leaving angular.io unintentionally.

## Expected behavior
I'd like to see a visual cue near each external link that would tell me if clicking on the link will take me to an external resource or not.

Several pages have solved this via arrows pointing up and to the right. The following is from developers.google.com:

---

<img width="621" alt="screen shot 2017-06-19 at 3 24 10 pm" src="https://user-images.githubusercontent.com/216296/27308550-00e4cf68-5504-11e7-968f-2f5c8e48800f.png">

---

In my opinion this particular design is too heavy weight and too distracting, something more lightweight, but still able to communicate the same information would be much more preferable.

**Comment by sjtrimble** [comment]
I haven't seen many pages style external links any differently from internal links. My preferred method is to have all external links open in a new window and all internal stay in the window. If you don't think that's enough, I can come up with some options.

**Comment by IgorMinar** [comment]
@sjtrimble opening external links in a new window is an anti-pattern that should be avoided. The user should be always in control of the tab/window management.

**Comment by IgorMinar** [comment]
This article captures it well: https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/

also this one has more info: https://css-tricks.com/use-target_blank/

**Comment by chouclee** [comment]
This is how GCP does:
<img width="408" alt="screen shot 2017-06-22 at 12 32 46 pm" src="https://user-images.githubusercontent.com/3389485/27452502-91726f50-5747-11e7-9d15-dd8fbcf81b86.png">

```
  .external-link::after {
    font-family: "Material Icons";
    content: "open_in_new";
    display: inline-block;
    height: 13px;
    margin-left: 4px;
    width: 15px;
    position: relative;
  }
```
