### ISSUE TITLE
too complex and bloated to be usefull

### ISSUE THREAD

**Issue by old-coder-404** [angular/angular#17623]
this is ridiculously complex and bloated (130mb for a BASIC sample site?! really?!).
Development time is greatly increased and maintenance is going to be a nightmare.

What happened to simply adding a few js files to the solution?  Have you even looked at how hard it is to add Angular to an existing project? Obscene.

AND This!?!?!
https://medium.com/friendship-dot-js/i-peeked-into-my-node-modules-directory-and-you-wont-believe-what-happened-next-b89f63d21558

## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
And now guess. Does he think it seriously or it is a joke?

**Comment by trotyl** [comment]
Anyway, he cannot distinguish what **Angular CLI** is and what **Angular** is.

**Comment by hansl** [comment]
Hi @old-coder-404,

Seems you have the node_modules size confused with your application size. The 130Mb figure you pointed out is the size of your development environment. For a Node development environment, this is pretty much par for the course. Webpack itself takes 2.3Mb, and rxjs around 7Mb. This is not unusual, and not really unique; [Android Stuio](https://developer.android.com/studio/index.html) is over 460Mb, for example, and Java is over 200Mb itself.

Note that _**it does not affect the size of your application that will be shipped to your users**_. Not every file are actually necessary to build your application or to support your development process. We constantly track the size of what ends up in the browser; with an Angular-CLI new project at the time of this writing, the size of the application in the browser is less than 300kb, non-gzipped (it gets down to 80kb over the wire). This is the metric to track and as far as we know there's nothing to worry there.

As such, closing this issue as answered and also not an issue with Angular itself. Cheers.

----

Nota: the article, besides being 10 months old, is misguided and misleading. It states the following:

> Imagine if the apple you were eating for breakfast had 291 ingredients, or if the car you drove to work had 291 parts. You’d be worried, wouldn’t you? 

The better analogy would be; imagine your breakfast had 5 ingredients, but the kitchen that made it had over 291 parts. That's a bit more reasonable, don't you think?
