### ISSUE TITLE
Memory leak in async pipe

### ISSUE THREAD

**Issue by czterocyty** [angular/angular#17624]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
This is rather informational in Angular 2+ project.

Due to ReactiveX/rxjs#2675 and the fact that AsyncPipe do not clean the reference to `ChangeDetectorRef` - there can be memory leaks. They might be big, as `ChangeDetectorRef` and its subclasses can contain DOM detached elements of previous view.

The problem on rxjs angular boundary lies in passing the closure to rxjs in `AsyncPipe#subscribe`:

This closure is held internally by rxjs `SafeSubscriber` and never released, so it causes that AsyncPipe object cannot be released with its transitive dependencies (ChangeDetectorRef).

```
this._subscription = this._strategy.createSubscription(obj, function (value) { return _this._updateLatestValue(obj, value); });
```

## Expected behavior
There is no yet permanent fix yet, but to limit the memory leakage, I propose to reset `ChangeDetectorRef` too in `onDestroy` method.

## Minimal reproduction of the problem with instructions
See ReactiveX/rxjs#2675 although it is not Angular code

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3, rxjs 5.1.0

Browser:
- [x] Chrome (desktop) version 59
 
For Tooling issues:
- Node version: 6.9
- Platform: Linux
</code></pre>

**Comment by cghislai** [comment]
Using angular6, I can't reproduce the issue. It seems there is a memory leak in the shareReplay operator of rxjs 6 (and probably former versions), tracked there: https://github.com/ReactiveX/rxjs/issues/3336. 

This stackblitz may provide some insight: https://angular-kyver2.stackblitz.io

* The route A uses the shareReplay operator and subscribes using the aync pipe. Instances of this component are never garbage collected.
* The route B (un)subscribes manually using lifecycle hooks and avoid using the shareReplay operator. Instances are garbage collected.
* The route C does not use any share/shareReplay operator and subscribes using the async pipe. I don't understand the behaviour for this one, but it seems that both subscribers are able to receive the emitted values and that the component is correctly garbage collected.
* The route D uses the share operator and subscribes using the async pipe. Instances are correctly garbage collected.
* The route E uses the publishReplay + refcount operators as an alternative to the shareReplay operator and subscribes using the async pipe. Instances are correctly garbage collected.

**Comment by petebacondarwin** [comment]
@cghislai - I could not access your Stackblitz. It would be great if you could recreate it as a useful test environment for this issue.

It looks to me like this is really an upstream issue with RxJS usage - i.e. if you use certain kinds of RxJS operators on observables that you pass to `async` pipe you can get memory leaks.

That being said, it also seems that it would be prudent to apply the fix proposed by @czterocyty in https://github.com/czterocyty/angular/commit/928fd3ee7004f4edb4c0b20bade270571b30c751, which ensures that that `async` pipe is disconnected from the change detector when it is destroyed.

We could really do with a solid reproduction of the memory leak to allow us to test this.

**Comment by cghislai** [comment]
@petebacondarwin indeed, it is by using the shareReplay operator that we obtain memory leak.

The issue has been addressed upstream by the addition of a `refCount` paramter flag, see https://github.com/ReactiveX/rxjs/pull/4059.
Using this parameter, the shareReplay operator will unsubscribe from its upstream observable when there are no longer any downstream subscription, allowing the angular component to be garbage collected.

Ive nevertheless recreated the stackblitz at <a href="https://stackblitz.com/edit/angular-risiq3?file=src/app/app.component.html">https://stackblitz.com/edit/angular-risiq3</a>

In the heap dump, it seems the async pipe is keeping a reference to the component through its change detector `_ref`, so the fix you mentioned might be worth testing. 

Im relinking the rejected mr https://github.com/angular/angular/pull/17629. Im not sure it is a proper solution neither, but it may indeed allow the components to be garbage collected and limit the impact of the memleak.

![image](https://user-images.githubusercontent.com/12647398/90054942-e0c2cc80-dcdc-11ea-874e-bb22dd96f94e.png)



[Heap-20200812T204631.heapsnapshot.zip](https://github.com/angular/angular/files/5065002/Heap-20200812T204631.heapsnapshot.zip)
