### ISSUE TITLE
Angular2+ AOT opens new tab while navigating to a new route(child route)

### ISSUE THREAD

**Issue by aprshenoy** [angular/angular#17626]
## Current behavior
AOT version of app opens 2 tabs. 

We have an application now running in angular2+. we recently started to use AOT ,since then we are seeing a strange behavior. if we click on any link with routing (child routes) it will open a new tab for once and will load complete page in that new tab with corresponding component for the route, if we keep the newly opened tab then from next click onwards route changes will be reflected on that new tab only. if we close the newly opened tab, on next click of any route link it will again open a new tab. in short now it basically operates on 2 tabs. what could be the possible reason.?? i hope my question is clear. Thanks in advance.

## Expected behavior
Should not open the new tab,

## Minimal reproduction of the problem with instructions
Routes

Routes = [
  {
    path: '',
    redirectTo: 'login',
    pathMatch: 'full'
  },
  { path: 'login', component: LoginComponent, canDeactivate: [CanDeactivateGuard] },
  { path: 'app', component: HomeComponent,
    children: [
      { path: '', redirectTo: 'message', pathMatch: 'full' },
      { path: 'xyz', component: xyzComponent, canActivate: [AuthGuard] },     
      { path: 'xyz1', component: xyz1Component, canActivate: [AuthGuard], canDeactivate: [CanDeactivateGuard] },
      { path: 'xyz2', component: xyz2Component, canActivate: [AuthGuard], canDeactivate: [CanDeactivateGuard] },
      { path: 'xyz3', component: xyz3Component, canActivate: [AuthGuard] }]
}
]

 --<li *ngIf="xyz.Visibility"><a data-toggle="collapse" data-target=".navbar-collapse"  href="#" [routerLink]="['/xyz']">{{xyz.DisplayName}}</a></li>
                       -- <li *ngIf="xyz1.Visibility"><a data-toggle="collapse" data-target=".navbar-collapse"  href="#" [routerLink]="['xyz1']">{{xyz2.DisplayName}}</a></li>
                        --<li *ngIf="xyz2.Visibility"><a data-toggle="collapse" data-target=".navbar-collapse"  [routerLink]="['xyz2']">{{xyz2.DisplayName}}</a></li>
                        --<li *ngIf="xyz3.visibility"><a data-toggle="collapse" data-target=".navbar-collapse"  [routerLink]="['xyz3.Visibility']">{{xyz3.DisplayName}}</a></li>

**Comment by Toxicable** [comment]
Your minimal reproduction does not work in isolation. Could you please make a minimal reproduction in plunkr, here's a template to get you started https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by aprshenoy** [comment]
Ok i will try, i dont know how to get the AOT version in plunker. This issue occurs only in AOT

**Comment by Toxicable** [comment]
If it's an AOT only issue then please create a minimal reproduction in a repo, preferably using the CLI. Also please note the part about *minimal* there more complex it is the less likely it is for the issue to be auctioned.

**Comment by aprshenoy** [comment]
down vote
accept
	
HI , i got it working
issue was with the anchor tag

I removed

>  data-toggle="collapse" data-target=".navbar-collapse" 

from my anchor tag and made it look like

> <li ><a> [routerLink]="['XYZ1']">XYZ1</a></li>

it worked, i dont know what was the issue, posting this here so that it may help some one and team can look into this.

**Comment by Toxicable** [comment]
I donn't mean to sound rude since you're trying to help here but without a reason for it happening or a clear situation where it can occur then it's not possible to investigate

**Comment by aprshenoy** [comment]
@Toxicable I understand. For me a situation like this happened when i used `data-toggle="collapse" data-target=".navbar-collapse" ` . when i removed it worked properly, may be this info will help someone, i am not sure if this a bug with angular or aome other isssue in my own application. i will be researching more on this and i will post my findings here. 
Thank you for the response,
