### ISSUE TITLE
aio: need single source of URL redirects for both Firebase & SW

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17636]
Currently, if a documentation URL changes - for any page ... including API URLs - we have to update  redirect configuration for both Firebase (`firebase.json`) and ServiceWorker (the regex in `ngsw-manifest.json`).

Worse, the redirect adjustments in ServiceWorker must be made to a single regex and aren't at all obvious.

This [PR comment](https://github.com/angular/angular/pull/17621#issuecomment-309603778) and the subsequent slack exchange below brought this issue to the fore.

We need a rational solution soon because many more redirects will be popping up quickly.

### Slack exchange on 20 June 2017

WB:
What is the point of the regex in `nsw-manifest.json`?
```    "routes": {
      "^(?!/docs/ts/latest|/styleguide).*/(?!e?plnkr)[^/.]*$": {
        "match": "regex"
      }
    }
```
That looks like something for _internal_ redirects. I don’t know why we worry about those at all. The firebase redirects concern _permalinks_ held by external sources.

If we need redirects for that purpose inside the `nsw-manifest.json`, we have a significant disconnect and maintenance issue, don’t we?

GK:
Once the ServiceWorker is activated, it will handle requests for `angular.io`. Based on that regex, it will route requests to `index.html`.
Only if we tell it not to handle some URL will it let it pass through to Firebase.

So, the Firebase redirects are useful only as long as the SW passes the requests through to the server.

WB: 
This is going to be hell to maintain if we have to worry in ServiceWorker about redirects of this kind. The `cli-quickstart` URL rename is the first of many over the coming years.

I still don’t know what request the SW is going to have to handle here. What happens if we _do not_ make the change you recommend?

GK: 
I think the SW will route `/guide/cli-quickstart` to `index.html`. The URL will remain `/guide/cli-quickstart` and our Document service will try to fetch `/generated/docs/guide/cli-quickstart.json` (and fail with a 404).

We could teach firebase to return `/generated/docs/guide/quickstart.json`, but:
(a) I am not sure this is much more maintainable and
(b) the fact that the URL will remain incorrect, is "bad". 

WB: 
Whereas if SW is disabled for some reason, that link would go to Firebase and be properly redirected?

If that is so, we have bigger problems. This will be unmaintainable. We can’t easily maintain redirects in TWO places.

The URL remains bad only if it doesn’t reach Firebase and redirect and Firebase returns a 301, right?

My thought is … if is necessary to have redirect logic in both SW and Firebase … we need a single source of redirects and a way to generate the SW and Firebase configuration from that.

GK:
> If that is so, we have bigger problems. This will be unmaintainable. We can’t easily maintain redirects in TWO places.

He he, ServiceWorker ain't free :stuck_out_tongue:
:+1: for having one source of truth for redirects if possible.

WB:
Apparently not.  But I’m not happy with your suggestion in my PR either. This feels wrong and we should address it promptly. That said, I’ll make the change you requested for now so we can get over this particular hump.

Note that we will have the **same problem tomorrow** when we figure out how to redirect `change-log`. And lord help us if we change that URL once again.

And let’s not forget that API URL changes are common; they also flow through this logic.

GK:
I am not thrilled about having to make that suggestion either :smiley:
FWIW, we are not exactly duplicating the redirect rules. We are just telling the SW to ignore some paths, so that Firebase (that knows about the redirect rules) can redirect them. But I totally agree that there should be a better, less manual way to generate the "SW don't route these paths" list.

WB: 
The fact that the strategy for SW is slightly different argues even more forcefully for a better way. I’m creating an issue for us.

**Comment by gkalpak** [comment]
Since #42452, we no longer need to manually configure the SW redirects :tada:
(The SW redirect configuration is automatically generated based on the Firebase redirect configuration.)
