### ISSUE TITLE
Support @Ancestor in app injectors

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1763]
Use-case:

```dart
abstract class RpcService {}

class DefaultRpcService implements RpcService {
}

class SpecialRpcService implements RpcService {
  // There's currently no way to publish [SpecialRpcService] as [RpcService]
  // and at the same time have it depend on [RpcService] that comes from
  // the parent injector.
  SpecialRpcService(@Ancestor() RpcService defaultRpcService);
}
```

## Current workaround

In AngularDart 1.x the workaround is to inject the injector and call to parent:

```dart
class SpecialRpcService implements RpcService {
  SpecialRpcService(Injector injector) {
    RpcService defaultRpcService = injector.parent.get(RpcService);
  }
}
```

/cc @mhevery @vsavkin @tbosch

**Comment by vsavkin** [comment]
How often does this situation happen? Cause we can just make the parent property public to make the same workaround possible:

```
const Binding(RpcService, toFactory: (inj) => new SpecialRpcService(inj.parent.get(RpcService)))
```

Another option would be to change Injector to provide the following guarantee: when Binding A requests Dependency A, it gets it from the parent.

**Comment by yjbanov** [comment]
One use-case is the event bus pattern: you want a hierarchy of event buses where a given event bus delegates to its parent event bus. All even buses implement the same interface:

```
class EventBus {
  EventBus(EventBus parent);
}
```

**Comment by mhevery** [comment]
We should make the `parent` public in the injector and leave this issue for later.

**Comment by mhevery** [comment]
Obsolete, new injectors now support this.
