### ISSUE TITLE
docs: quickstart-cli - bad HTML escape chars

### ISSUE THREAD

**Issue by dima74** [angular/angular#17648]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Open page https://angular.io/guide/quickstart#the-src-folder in latest Chrome. There is table with columns `File` and `Purpose`. Purpose for file `index.html` contains text 

> so you never need to add any &amp;lt;script&amp;gt; or &amp;lt;link&amp;gt; tags here manually.

![image](https://user-images.githubusercontent.com/6505554/27356742-63fab9e0-5618-11e7-875b-f9d45c607422.png)

## Expected behavior

Insted it should contains text

> so you never need to add any &lt;script&gt; or &lt;link&gt; tags here manually.

## Minimal reproduction of the problem with instructions

1. Open page https://angular.io/guide/quickstart#the-src-folder in latest Chrome
2. Navigate to table with columns `File` and `Purpose`
3. Find row with `File` column `index.html`
4. Read this row `Purpose` text

**Comment by petebacondarwin** [comment]
An easy fix for you @Foxandxss  :-)

**Comment by apetrosian** [comment]
@petebacondarwin, @Foxandxss, guys, if you don't mind, I've sent a PR to fix this issue
