### ISSUE TITLE
Karma should run formatted Dart code

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1764]
Not sure when this happened, but now Karma runs unformatted Dart code, which is super hard to debug.

/cc @IgorMinar

**Comment by alexeagle** [comment]
I wonder who was formatting the code previously, when ts2dart was a karma preprocessor. Are you sure this was working before? I don't think we were running the dart_style:format package on every file save?

Looked in https://github.com/angular/angular/blob/c1579222bd74f83f73d1d6c7e1636c7ebd0ea3bc/tools/transpiler/karma-ts2dart-preprocessor.js 
https://github.com/angular/angular/blob/c1579222bd74f83f73d1d6c7e1636c7ebd0ea3bc/karma-dart.conf.js

The right fix is to change our broccoli ts2dart wrapper to format every file incrementally. Will take a look.

**Comment by yjbanov** [comment]
No, not 100%. I'm 100% sure I debugged formatted code in the past, but perhaps those were integration tests, not unit tests. The two use different build targets.

**Comment by IgorMinar** [comment]
the code is being formatted in master. it looks like the formatting is not incremental though, which slows down the iteration. I'll open a new issue for that.

**Comment by IgorMinar** [comment]
the new issue: #2036
