### ISSUE TITLE
docs: toh-pt4 - wrong steps in Sec 5 & 6; follow up from angular.io issue #3396

### ISSUE THREAD

**Issue by mccumb01** [angular/angular#17645]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Moved comments here from https://github.com/angular/angular.io/issues/3396

While most of the tutorial is very clear & detailed, some steps or snippets are ambiguous or unclear. 
The author of the previous issue cites "Part 4" (which is now "Part 5")...

1. **Ex: Section 5. Services**
One section in particular (https://angular.io/tutorial/toh-pt4#move-the-mock-hero-data) says:

> In app.component.ts, where you cut the HEROES array, add an uninitialized heroes property:

This is not accurate, because "where you cut the HEROES array" was above outside the class declaration. You need to put the new property below *inside* the class declaration.
The code shown for this doesn't provide context & just says to add: `heroes: Hero[];`

Correct file, but unclear location, and perhaps not an obvious instruction for people new to OOP/Typescript.

2. **Ex: Section 6. Routing**

Begins with **Configure Routes**

> Create a configuration file for the app routes...
> Define the first route as a route to the heroes component: 
> `//Route Code Snippet Here`

Saying "create a file" indicates a *new* file, but it says to do this in `src/app/app.module.ts`.
Just afterward in **Make the router available** you do the exact same work again to import the `RouteModule`, and add the exact same code to the imports array, again in `app.module.ts`, the same file.

So are you supposed to do this twice, in 2 places/files, or just 1? 
Am I "configuring routes" or "making the router available," or both at once? 
It's not clear as written, which makes it easy to break things at this point. 

https://angular.io/tutorial/toh-pt5#configure-routes

3. **Outdated Links** 
Section names and URLs are inconsistent due to changes in tutorial structure. 
Links to "Sec 5. Services" still say "pt4," but it's now "pt5." Links to "Sec. 6 Routes" still say "pt5", etc. 

## Expected behavior

1. At least reword to clarify that the "uninitialized class property" should go inside the class definition, and not "where you cut the HEROES array," which is incorrect. Add context to snippet, unless the goal is to have the learner figure this out for themselves. 

2. Reword to clarify which/how many file(s) and where the code goes. This functionality gets refactored shortly thereafter, but this introduction to routing is rather confusing & easily broken. 

3. Update links so URLs point to the correct section number. Mostly cosmetic since they still work, but for consistency or people jumping in or restarting from the downloaded example this is also a bit confusing.

## What is the motivation / use case for changing the behavior?

Per earlier angular.io issue #3396, the lack of clarity, accuracy & detail in certain code snippets makes it difficult for new learners to follow along. These issues can result in putting code in the wrong place, breaking the app and making it difficult to continue with the tutorial.

## Please tell us about your environment
N/A - documentation issue only. 

 </code></pre>

**Comment by jenniferfell** [comment]
docarea=tutorial

**Comment by chembu** [comment]
Part 3 is fixed.

**Comment by chembu** [comment]
Part 1 and 2 is not valid anymore.
