### ISSUE TITLE
I cannot even get the first part of the QuickStart to display in IE. Just a blank screen! NO App Works!  When I look inside the code that is described my code has way more code in it. I am so sick of out dated tutorials that no longer work. 

### ISSUE THREAD

**Issue by Finnchik** [angular/angular#17649]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Finnchik** [comment]
I am using IE 11, npm 3.10.10 node.js 6.11.0. Sure would be nice if tutorials really worked. I have found that 90 % of the time they don't. I was really hoping on this one. Oh Well....

**Comment by ericmartinezr** [comment]
https://angular.io/guide/quickstart
![image](https://user-images.githubusercontent.com/13039652/27360383-cd40f704-55ee-11e7-91d8-ff9b63f643e1.png)


https://angular.io/guide/browser-support#mandatory-polyfills

**Comment by Finnchik** [comment]
Oh thank you.
I decided to try using VS 2015 and follow that part of the directions which actually added zone.js for polyfills. That made a big difference.


Shawn Marie Austin
Applications and Data Services (ADS)
Washington State Department of Health
Technology Solutions
Town Center 1 – 2 West – 2-W-004 MS 47849
101 Israel Rd SE Tumwater, WA 98504-7814
Phone 360-236-4276
"Success is not failure, Failure is not fatal, It is the courage to continue that Counts."
--- Winston Churchill
