### ISSUE TITLE
new promise object, then function will error when use promise resolve object

### ISSUE THREAD

**Issue by gejun2008** [angular/angular#17655]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

At function create new promise object, when to use then function, compile error.
Typescript:

let test =  new Promise((resolve, reject)=>{
      let resp = {
        'Error':0, 
        'ErrorMessage':''
      }
      resolve(resp);
})

test.then(resp=>{
if(resp.Error)    //compile error 
})

## Expected behavior

Expected no error. Has checked at chrome browser, it's OK.

## Please tell us about your environment

<pre><code>
Angular version: 4.0.1

Browser:
- [x ] Chrome (desktop) version 53
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.10.3 
- Platform: Windows

Others:

</code></pre>
<code>
let test =  new Promise((resolve, reject)=>{
      let resp = {
        'Error':0, 
        'ErrorMessage':''
      }
      resolve(resp);
    });

      test.then((rep)=>{
        if(rep){
          rep.Error
        }
      })
</code>

## compile error below:
ERROR in D:/work/case/angular-airmedia/airmedia-ams/src/SPA/airmedia-ams/src/app/playlist/playlist.service.ts (38,15): Property 'Error' does not exist on
 type '{}'.

ERROR in D:/work/case/angular-airmedia/airmedia-ams/src/SPA/airmedia-ams/src/app/playlist/playlist.service.ts (38,15): Property 'Error' does not exist on
 type '{}'.
webpack: Failed to compile.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
