### ISSUE TITLE
Make Angular compatible with webpack3's ModuleConcatenationPlugin

### ISSUE THREAD

**Issue by briced** [angular/angular#17657]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When compiling an Angular project with webpack3 ModuleConcatenationPlugin, it logs errors and does not optimize the project

<pre><code>
[./src/main.ts] ./src/main.ts + 6 modules 13.9 kB {2} [built]
       ModuleConcatenation (inner): module is used with non-harmony imports from multi ./src/main.ts
       ModuleConcatenation: Cannot concat with ./node_modules/@angular/core/@angular/core.es5.js: dependency variables are used (i. e. ProvidePlugin)
       ModuleConcatenation: Cannot concat with ./node_modules/@angular/platform-browser/@angular/platform-browser.es5.js
[./src/polyfills.ts] ./src/polyfills.ts 2.58 kB {0} [built]
       ModuleConcatenation (inner): module is used with non-harmony imports from multi ./src/polyfills.ts
</code></pre>

## Expected behavior
It should not logs errors, and optimize the final build

## Minimal reproduction of the problem with instructions
Add ModuleConcatenationPlugin in the plugins list in webpack configuration
Add --display-optimization-bailout to the webpack command
Run webpack

(Example project from CLI at https://github.com/briced/angular-ModuleConcatenationPlugin, run 'npm run build')

## What is the motivation / use case for changing the behavior?
Reducing the final bundle's size and cold run time for all angular projects.

## Please tell us about your environment
<pre><code>
Angular version: 4.2.3

For Tooling issues:
- Node version: 8.1.0
- Platform: Linux

Others:
I'm using nvm, but it should not impact the problem.
</code></pre>

**Comment by shlomiassaf** [comment]
@tbosch @mhevery is this planned soon?

The performance gain might be substantial...

@TheLarkInn @sokra can you share some pointers on why this happens?

Angular ESM modules are built by doing:
  - TS to JS via NGC (an angular TS wrapper) (es2015, non bundled with flat angular compiler atrifacts)
  - Rollup JS output to bundle
  - Use TS to downlevel rollup bundle to ESM
  - **Irrelevant**: rollup the ESM bundle to UDM

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. Luckily it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior.
