### ISSUE TITLE
Intermittent router issue - same url, different route matches

### ISSUE THREAD

**Issue by radoslavpetranov** [angular/angular#17654]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm opening the following URL `/cases/new;companyId=2` and I have the following routes for cases:

```
export const CaseRoutes: Routes = [
	{
		path: '',
		component: CaseTableComponent,
		canActivate: [AuthGuard],
		resolve: {
			case: CasesResolver
		}
	},
	{
		path: 'new',
		component: CaseEditComponent,
		canActivate: [AuthGuard],
		resolve: {
			case: CaseResolver
		}
	},
	{
		path: ':id',
		component: CaseInfoComponent,
		canActivate: [AuthGuard],
		resolve: {
			case: CaseResolver
		}
	},
	{
		path: ':id/edit',
		component: CaseEditComponent,
		canActivate: [AuthGuard],
		resolve: {
			case: CaseResolver
		}
	}
];
```

this is then hooked up to the `app.routing` using

```
{
		path: "",
		component: ContentComponent,
		children: [
			....
			{
				path: 'cases',
				children: [
					...CaseRoutes
				]
			},
			....
		]
```

I'm checking the ID in the resolver to trigger one of 2 behaviors depending on whether the user is creating a new case or opening up an existing one. Usually this works fine and the url does indeed hit the `/new` path so `route.params.id` is indeed `null` and we have a `companyId=2`.

![2017-06-20_11h52_18](https://user-images.githubusercontent.com/2715732/27369607-ff0a59b4-5658-11e7-8b2a-f4a472f110a5.jpg)

Every now and then, however, angular would treat `/new;companyId=2` as my `id` param from the `path: ':id'` route so I get this

![2017-06-20_11h51_00](https://user-images.githubusercontent.com/2715732/27369634-1fc03b10-5659-11e7-8355-4ad1f27f56f5.jpg)

As I said, nothing changes on my part - I'm just refreshing the same URL and debugging a completely unrelated problem with one of my forms.

## Expected behavior

I expect to hit the `/new` path every single time I refresh `/cases/new;companyId=2`.

## Minimal reproduction of the problem with instructions
I can't reproduce the issue in the plunker but I've mimicked the same setup in the plunker below and in the screenshots above I show how once the same url is being recognized as an `id` param and the other time it's properly parsed as `/new` + optional param `companyId=2`

http://plnkr.co/edit/BgzdAYEz5jJbF0RhGPEt?p=preview

## What is the motivation / use case for changing the behavior?
I'd expect the router to always behave in the same way in a certain scenario.

## Please tell us about your environment

<pre><code>
@angular/cli: 1.1.0
node: 6.10.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:

</code></pre>

**Comment by Toxicable** [comment]
Can you please provide a minimal reproduction? here's a plunkr to get you started

**Comment by radoslavpetranov** [comment]
I made a plunker with nearly the same setup. This is part of a medium-scale project so understandably I can't  replicate everything I have going on (various resolvers, AuthGuard, full components, etc). Normally the problem happens inside the `case.resolver` (as shown in my screenshots) when I `Ctrl+F5` while the URL is set to `/cases/new;companyId=2` but I don't seem to be able to replicate the behavior in the plunker with the `{ path: '', redirectTo: '/cases/new;companyId=2', pathMatch: 'full' }` path.

http://plnkr.co/edit/BgzdAYEz5jJbF0RhGPEt?p=preview

I'm not sure what can I possibly be doing wrong. I'm wondering if this could somehow be related to when the debugger breaks the cycle? I don't think I've ever been able to reproduce this issue without having a `debugger` in the resolver.

**Comment by radoslavpetranov** [comment]
So I traced this a little on my machine (since I can't reproduce it in the plunker for the life of me) and came up with the following 2 screenshots that illustrate the difference between the 2 matches in the very early stages of triggering the router:

![2017-06-21_12h02_12](https://user-images.githubusercontent.com/2715732/27378974-de919848-5679-11e7-9b5c-1a01df30165f.jpg)

![2017-06-21_12h03_40](https://user-images.githubusercontent.com/2715732/27378981-e3306b0e-5679-11e7-96b5-ff67d02b65c4.jpg)

Notice the difference of `UrlSegment #2` - both the path and the params.

**Comment by radoslavpetranov** [comment]
I need to step out but I believe the issue stems from this part of the code

```
Router.prototype.navigateByUrl = function (url, extras) {
        if (extras === void 0) { extras = { skipLocationChange: false }; }
        var /** @type {?} */ urlTree = url instanceof UrlTree ? url : this.parseUrl(url);
        var /** @type {?} */ mergedTree = this.urlHandlingStrategy.merge(urlTree, this.rawUrlTree);
        return this.scheduleNavigation(mergedTree, 'imperative', extras);
    };
```

**Comment by radoslavpetranov** [comment]
I will confirm this when I get back but I have a feeling the `;` marking the optional params will sometimes get url-encoded and the url parsing code probably fails to detect that hence treating the entire `/new;companyId=2` bit as a url segment with no params.

**Comment by radoslavpetranov** [comment]
Ok false alarm - sorry about that guys. Apparently when using `ngrx-store` and calling the `go` function it's not sufficient to pass 

```
['cases', 'new;companyId=2']
```

so I changed that to 

```
['cases', 'new`, { companyId: 2 }]
```

and everything works fine now.
