### ISSUE TITLE
Breaking change in public compiler api

### ISSUE THREAD

**Issue by tflori** [angular/angular#17653]
## I'm submitting a ...

<pre><code>
[x] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The reflector argument for `PipeResolver` (and others too) was optional. By default it was the global reflector. This has changed in this commit:
https://github.com/angular/angular/commit/50abca4583eb54bcab030a708f65ad11058082d9#diff-3c9d16a1eda3af93f5b54faa3d93a144R28

Of course the compiler crashes now because of insufficient parameters.

## Expected behavior

It is still optional because it is a breaking change for programs relying on this.

## Minimal reproduction of the problem with instructions

To see the problem you can clone https://github.com/tflori/angular-translator-demo and try to compile it but you might know how to reproduce a missing parameter :smile_cat:

## What is the motivation / use case for changing the behavior?

The problem stated out in the commit message was that it was "impossible to compile multiple programs at the same time". I don't understand the problem here: before you can give a reflector but by default it uses the global one; now you have to give one.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2 
- Platform: Linux

Others:

</code></pre>

**Comment by trotyl** [comment]
> One intentional omission from this list is @angular/compiler, which is currently considered a low level api and is subject to internal changes. These changes will not affect any applications or libraries using the higher-level apis (the command line interface or JIT compilation via @angular/platform-browser-dynamic). Only very specific use-cases require direct access to the compiler API (mostly tooling integration for IDEs, linters, etc). If you are working on this kind of integration, please reach out to us first.

`@angular/compiler` is never a part of public APIs, see [PUBLIC_API](https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md) for more information.

**Comment by tflori** [comment]
ok, didn't know that. for me everything that you can use is public api.. I expected at least that it get's mentioned in the changelog. 

do you have a backward compatible solution for this change?

**Comment by vicb** [comment]
As mentioned by @trotyl the compiler is not part of the public API and we do provide support. There will be more changes in the future and we will consider opening the API when it becomes more stable.

**Comment by BorntraegerMarc** [comment]
I agree. Something in the changelog should habe been mentioned.
