### ISSUE TITLE
API to make it easier to render components with floating panels (menu / select)

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1765]
This issue tracks leftover work that fell under the large umbrella of "overlays" #932.

It is desired to be able to build a Component that includes a pop-up / floating panel as _part_ of the component, without having to break up the code into individual components. The idea is to do something similar to the following (just the semantics):

```html
<!-- Template for md-menu component -->
<div class="md-menu-container">
  <div class="md-menu-trigger">
    {{triggerText}}
    <span class="md-menu-trigger-arrow"></span>
  </div>

  <redistribute to="body"> <!--  some mechanism for changing element position -->
    <div class="md-menu-panel" [style.top]="panelTop" [style.left]="panelLeft">
      <content select="md-menu-item"></content>
    </div>
  </div>
</div>
```

Notes:
* This would put the trigger part and the panel part in the same light DOM. This is important for accessibility, as elements in the trigger need to reference elements in the panel for things like `aria-owns` and `aria-activedecendant`. 
* No boilerplate of passing data back and forth data from separate trigger and panel components: content projection and `@Query` / `@Parent` would just work.
* Using a template-based API lets this be platform-specific.

@matanlurey, @jbdeboer please feel free to add your thoughts.

**Comment by jbdeboer** [comment]
This looks closer to the API that we want. Typically we hide the redistribution and content selection logic in a separate component (e.g. ```<g-popup>```) and depend Angular transclusion.

Here you are using the ```content``` tag instead -- is that intentional (e.g. will the other approach not work?) or is there an opportunity for both strategies?

**Comment by jelbourn** [comment]
@jbdeboer could you give an example of what you mean w/ the `g-popup`?

I was trying to get across that `redistribute` is a component with that appends the elements to element matched by the `to` selector. I _think_ this would be straightforward to implement with the custom component Renderer feature @tbosch is working on. 

@tbosch: can you comment on how custom component renders might fit in here?
@mhevery: can you comment with feedback / alternatives?

**Comment by mhevery** [comment]
I think your `redistribute` component is just https://github.com/angular/angular/issues/1492

**Comment by jelbourn** [comment]
@mhevery seems very similar. The difference is being able to add something to the document body (when the bootstrapped app is underneath that). This would be important for cases when the rot component is not at the root of the document, such as during migration, when the Angular 2 root component might only be a small portion of the overall application.

**Comment by mhevery** [comment]
I think this is obsolete. Closing. Re-open if you feel otherwise.
