### ISSUE TITLE
aio: copy button doesn't work correctly in some examples

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#17659]
If you go to [this guide](https://angular.io/guide/dependency-injection) and you copy the first snippet, it will be pasted in one line instead of keeping the file format.

**Comment by axu2** [comment]
Temporary workaround I've been using: just copy and paste the contents of the box.

**Comment by Foxandxss** [comment]
Yes, of course, but the idea is to fix it. I opened the issue so we don't forget.
