### ISSUE TITLE
Language service cannot resolve custom paths

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#17651]
## I'm submitting a ...

<pre><code>
[x] Bug report 
</code></pre>

## Current behavior

If a project has a `paths` option in the tsconfig.json file, it is ignored by the language service resulting in spurious errors.

## Expected behavior

The `paths` should be respected.

## Minimal reproduction of the problem with instructions

In the `toh-pt6.zip` project add the following file:

module.ts
```
import {Component, NgModule} from '@angular/core';

@Component({
  selector: 'path-component',
  template: 'Me!'
})
export class MyComponent {}

@NgModule({
  declarations: [MyComponent]
})
export class Module {}
```

in a directory called `needs-path/some-module` as a sibling to `src`.

Add to the `tsconfig.json` the following:
```
    "baseUrl": ".",
    "paths": {
      "some-module/*": ["../needs-path/some-module/*"]
    }
```

Add: `<path-component></path-component>` to the template of `app.component.ts`.

Expected: No diagnostic.
Received: Diagnostic about `path-component` is not a known element.

**Comment by karptonite** [comment]
This seems to be related to issue #16382, if not exactly a duplicate.

**Comment by chuckjaz** [comment]
duplicate of #16382
