### ISSUE TITLE
ngc not working properly when change path for config file

### ISSUE THREAD

**Issue by vforv** [angular/angular#17670]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[* ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Don't get right pathes when use compiler this way:
$(npm bin)/ngc -p tsc/tsconfig-client-aot.json

## Expected behavior
it should work correctly even if I put config file in another dir.

## What is the motivation / use case for changing the behavior?
I want all my config tsc files to be in one foler, cleaner code

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by chuckjaz** [comment]
Can you provide a repo for this?

The statement "it should work correctly even if I put config file in another dir." however is not correct. All paths in the config file considered relative to the config file not the directory that the command is invoked in so a config file that works in one directory is not guaranteed to work if it is moved.

**Comment by chuckjaz** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).
