### ISSUE TITLE
cheatsheet content clipped on narrow screens

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17678]
https://angular.io/guide/cheatsheet

<img width="413" alt="screen shot 2017-06-21 at 5 34 42 pm" src="https://user-images.githubusercontent.com/216296/27412217-02f60114-56a8-11e7-806a-f8ca2a77d78b.png">

![screen shot 2017-06-13 at 2 09 36 pm](https://user-images.githubusercontent.com/216296/27412267-592b5ade-56a8-11e7-9231-1a877ea3fca1.png)

**Comment by apetrosian** [comment]
Seems like the content is quite wide to fit into table cell w/o  scrolling. As an option, we can rethink the page layout (eliminate table) and format code with `code-example` blocks. I believe it will improve readability.

@IgorMinar, @wardbell What do you think?
