### ISSUE TITLE
Email Validator returns invalid for empty fields

### ISSUE THREAD

**Issue by morriq** [angular/angular#17688]
Hello.

This regexp: https://github.com/angular/angular/blob/f370fd36e0b77bdbeff64e135a51822075934f97/packages/forms/src/validators.ts#L44

makes EMAIL_REGEXP.test('') => false which means it contains Validator.required automatically itself, right? What if I want to check email pattern only if it contains any letter?

**Comment by Toxicable** [comment]
Dup #16183

**Comment by morriq** [comment]
my bad! thx
