### ISSUE TITLE
error when add ng2-opd-popup

### ISSUE THREAD

**Issue by alibahjat** [angular/angular#17686]
hello 
i got this error when serve after i installed ng2-opd-popup 
the error 
`
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not suppor
ted. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/a
pple/Desktop/school websie/school website/node_modules/ng2-opd-popup/node_modules/@angular/core/src/metadata/ng_module.d.ts, r
esolving symbol NgModule in /Users/apple/Desktop/school websie/school website/node_modules/ng2-opd-popup/node_modules/@angular
/core/src/metadata.d.ts, resolving symbol NgModule in /Users/apple/Desktop/school websie/school website/node_modules/ng2-opd-p
opup/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/apple/Desktop/school websie/school website/
node_modules/ng2-opd-popup/node_modules/@angular/core/index.d.ts, resolving symbol PopupModule in /Users/apple/Desktop/school
websie/school website/node_modules/ng2-opd-popup/components/popup/popup.module.d.ts, resolving symbol PopupModule in /Users/ap
ple/Desktop/school websie/school website/node_modules/ng2-opd-popup/components/popup/popup.module.d.ts`

my package json is 
`{
  "name": "ng4-cli",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "populate-db": "./node_modules/.bin/ts-node ./populate-db.ts",
    "batch-server": "./node_modules/.bin/ts-node ./batch-server.ts"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.3",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.7",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@jaspero/ng2-confirmations": "^0.2.9",
    "@types/lodash": "^4.14.36",
    "@types/request": "0.0.30",
    "angular-confirmation-popover": "^3.1.0",
    "angular2-bootstrap-confirm": "^1.0.4",
    "angularfire2": "^4.0.0-rc0",
    "core-js": "^2.4.1",
    "firebase": "^3.9.0",
    "firebase-queue": "^1.5.0",
    "lodash": "^4.15.0",
    "ng-select": "^1.0.0-beta.5",
    "ng2-opd-popup": "^1.1.21",
    "ng2-toasty": "^4.0.3",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
`

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mensahGit** [comment]
In your tsconfig.json, add the following line to the enclosed json object:

**"paths": { "@angular/": ["../node_modules/@angular/"] }**

Hope this saves someone a few hours scouring the web.

All the Best,

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
