### ISSUE TITLE
*ngSkip - Directive for skipping change detection

### ISSUE THREAD

**Issue by jhertz123** [angular/angular#17689]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
N/A
## Expected behavior
In Angular there are some different ways to control "Change Detection". If you have a large page you might remove nodes from the tree by using *ngIf. What I suggest is a new built in directive *ngSkip this would leave the nodes as is, it would not check the node or child nodes if true. But it would still keep the HTML as is to be rendered on the page. Once we want to resume change detection we change the value to true. 

This would allow for
* Not having to re-render large sections of the page 
* Giving the developer more control when to paus change detection
* Implement their own change behavior (I not sure about this point)

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
More control, helps with large applications.

## Please tell us about your environment

<pre><code>
Angular version: 4.0.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX

**Comment by Toxicable** [comment]
You can already do this with Components and OnPush Change Detection Strategy

**Comment by mlc-mlapis** [comment]
Probably the same you can reach by decoposition ... and if are taking about a large page then it should the first step in any case ... and then using `OnPush` strategy on that component because it won't be re-rendered till you pass a new ref on @Input().

**Comment by mlc-mlapis** [comment]
@Toxicable ... 1 sec win.

**Comment by jhertz123** [comment]
If you have a Component with OnPush, can you change it back and forth between that strategy and the regular one? 

What is suggest is a toggle. Let's say you have a tab control. You want your components in the tab to use the regular detection strategy when active. But you don't want it to be included in change detection when not active. Would your suggestion achieve this?

**Comment by Toxicable** [comment]
No our suggestions would not support this. However, I don't see a good case for that specific function. Can you provide a more concrete reason for wanting to be able to dynamically changed between one type of ChangeDetection and another?

**Comment by jhertz123** [comment]
If you have a large page you don't want to re-render the nodes you want to keep them. But you don't want change detection to run on them when they are not active. You can paus and then resume different sections of your page.

**Comment by notsonotso** [comment]
ChangeDetectorRef gives you great control

**Comment by mlc-mlapis** [comment]
Hmmm, I still think that that toggling is just sending a new ref on `@Input()` ... and it cound be just a control object.

**Comment by jhertz123** [comment]
@notsonotso Thanks I will have a look at ChangeDetectorRef.

**Comment by jhertz123** [comment]
@notsonotso Using ChangeDetectorRef you still have to use ChangeDetectionStrategy.OnPush and that would force any child Component to also use OnPush? Or am I wrong?

**Comment by Toxicable** [comment]
You don't need to use OnPush to use ChangeDetectorRef (CDR). However, you're better using OnPush than CDR. I personally see no reason for needing to flip between having CD on and off for anything. Just use OnPush and if you want it to run CD then Push new data to that sub tree.

**Comment by notsonotso** [comment]
@jhertz123 you are wrong, yes.

**Comment by jhertz123** [comment]
@Toxicable But if you just want it to be something like switching views and you don't want to force everything in your view to also use OnPush. Would it not make sense then?

**Comment by jhertz123** [comment]
@notsonotso Thanks, I have to read up more on how it works.

**Comment by jhertz123** [comment]
@notsonotso I have made a working example of a directive that checks if the element is visible and detaches the ChangeDetectorRef when hidden. What confuses me is if I place the directive on a child component the ChangeDetectorRef is attached to the parent component. 

In the example the ChangeDetectorRef has the property ._view.component = "ParentComponent". Where I would expect it to have "SomeChildComponent".

ParentComponent
`
<some-child-component mySkipDirective>
</some-child-component>
`

(Maybe this is not the approprierat place to ask this question, please let me know if that is the case ).

**Comment by jhertz123** [comment]
I think a new * directive might be overkill. I have done my own implementation using ChangeDetectorRef.

Thanks to @notsonotso for the suggestion.
