### ISSUE TITLE
Bootstrap: The binding of bind(VmTurnZone) after resolved bindings is wrong behavior

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1769]
Angular should insert the binding at the *top* of the list of bindings, not at the bottom.

Doing it at the top makes it possible to override VmTurnZone (for testing, for example).

**Comment by matanlurey** [comment]
Hold this PR. Looking for better alternative :)

**Comment by mhevery** [comment]
Related: https://github.com/angular/angular/issues/1594

**Comment by naomiblack** [comment]
Still important but no longer considered blocking by GT.

**Comment by matanlurey** [comment]
This might not be required anymore. Closing for now.
