### ISSUE TITLE
aio: zipper should provide aot stuff

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#17695]
For example, in toh-6, it should contain all the aot related stuff.

**Comment by petebacondarwin** [comment]
It appears that there is no point starting this project if we are going to move the examples over to CLI in general soon. So I am moving this back to the TODO list and assigning it to @juleskremer  to make a call on the decision about reworking examples in CLI.

**Comment by petebacondarwin** [comment]
We have reworked almost all our examples using CLI so this issue is no longer relevant.
