### ISSUE TITLE
npm bug angular4 quickstart

### ISSUE THREAD

**Issue by obarrington** [angular/angular#17698]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I opened the Angular4 quickstart tutorial with no problem. I saved my work, closed out of the terminal, and went home for the night. This morning I opened the terminal to run npm start & continue working on the tutorial but was met with an error. I get exit status 1, npm run build fails on my system. I tried removing the files from my system and starting over from scratch but the same thing happened again. 

## Expected behavior
npm start should just open the app in chrome. 

## Minimal reproduction of the problem with instructions

I don't know how to recreate the issue. I guess download the package following the tutorial directions, work on the tutorial for a bit, save and quit and turn off computer then try again tin the morning. 

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [X] Chrome (desktop) version 58
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.5
- Platform:  Mac

Others:
I'm using the text editor atom
</code></pre>

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
Are you using the CLI? (https://angular.io/guide/quickstart) if not I'd suggest following that.
Error code 1 means almost nothing, try reading through the rest of the error to see if it indicates towards the cause, since there is nothing wrong with the CLI itself as it work find on my machine.
