### ISSUE TITLE
docs: testing guide - bad markdown link 

### ISSUE THREAD

**Issue by Kloranthy** [angular/angular#17709]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

A link in the [testing section of the component interaction guide](https://angular.io/guide/component-interaction#test-it-5) appears as unprocessed markdown.

ex: \[text\](link)

## Expected behavior

The link gets processed by markdown.

ex: [text](link)

## Please tell us about your environment

Google Chrome Version 56.0.2924.87 (64-bit) on Fedora 25

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by wardbell** [comment]
See PR#17754

**Comment by jenniferfell** [comment]
Thank you. Looks like this has been resolved.
