### ISSUE TITLE
npm checksum error for core/http/platform-browser v4.2.4

### ISSUE THREAD

**Issue by clabough** [angular/angular#17708]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

npm package install fails

## Expected behavior

successful package install

## Minimal reproduction of the problem with instructions

`λ npm install @angular/core@4.2.4 -S
npm WARN @angular/http@4.2.3 requires a peer of @angular/core@4.2.3 but none was installed.
npm WARN @angular/platform-browser@4.2.3 requires a peer of @angular/core@4.2.3 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm@5.0.3 (node_modules\npm):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Local Files\project\node_modules\.staging\npm-d304f142\html\dochead.html'

npm ERR! code EINTEGRITY
npm ERR! sha1-4OGzRL1H8dULW1qwPZNffCBNUrg= integrity checksum failed when using sha1: wanted sha1-4OGzRL1H8dULW1qwPZNffCBNUrg= but got sha1-6NZO/nltbKXAhb/ugnirSiPoB0A=. (141963 bytes)

λ npm install @angular/http@4.2.4 -S
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm@5.0.3 (node_modules\npm):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open 'C:\Local Files\project\node_modules\.staging\npm-d304f142\lib\xmas.js'

npm ERR! code EINTEGRITY
npm ERR! sha1-4OGzRL1H8dULW1qwPZNffCBNUrg= integrity checksum failed when using sha1: wanted sha1-4OGzRL1H8dULW1qwPZNffCBNUrg= but got sha1-6NZO/nltbKXAhb/ugnirSiPoB0A=. (141963 bytes)

λ npm install @angular/platform-browser@4.2.4 -S
npm WARN @angular/http@4.2.3 requires a peer of @angular/platform-browser@4.2.3 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @progress/kendo-angular-popup@1.1.0 (node_modules\@progress\kendo-angular-dropdowns\node_modules\@progress\kendo-angular-popup):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Local Files\project\node_modules\.staging\@progress\kendo-angular-popup-dc95abe8\dist\es\services\position.service.metadata.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-gyp@3.6.2 (node_modules\npm\node_modules\node-gyp):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Local Files\project\node_modules\.staging\node-gyp-a4f87b29\gyp\pylib\gyp\generator\analyzer.py'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm@5.0.3 (node_modules\npm):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: EEXIST: file already exists, mkdir 'C:\Local Files\project\node_modules\.staging\npm-d304f142\test\tap'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File exists: C:\Local Files\project\node_modules\.staging\npm-d304f142\test\tap

npm ERR! code EINTEGRITY
npm ERR! sha1-4OGzRL1H8dULW1qwPZNffCBNUrg= integrity checksum failed when using sha1: wanted sha1-4OGzRL1H8dULW1qwPZNffCBNUrg= but got sha1-6NZO/nltbKXAhb/ugnirSiPoB0A=. (141963 bytes)`

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.9.2
- Platform: Windows 
- NPM: 5.0.3

Others:

Other angular/4.2.4 packages installed successfully
</code></pre>

**Comment by IgorMinar** [comment]
I can't reproduce this with npm 5.0.3 or npm 3. yarn also has no issues with the packages.

Maybe your network proxy, on-premise-npm-cache, or other man-in-the-middle is interfering with the download?

Please try to use a vpn to shield yourself from network interference.

If you can reproduce the issue from a machine in the cloud (e.g. a CI, then please file a new issue and provide additional information). thanks
