### ISSUE TITLE
Change Detection not picking up deeply nested route component changes on initial load

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#17700]
## I'm submitting a ...

<pre><code>
[X] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Component not rendered with data. When next change detection happens it redraws correctly

## Expected behavior
Component should render correctly

## Minimal reproduction of the problem with instructions

My use case is very complex and I have not yet been able to reproduce in a simple plnkr. However the code as is had been working for a very long time and the rendering issue appears only from Angular 4.2.0-rc.0 on. (I suspect https://github.com/angular/angular/commit/5d4f5434fd1c387f88ea46332a792ea94f9538da is the cause.)

I have a deeply nested hierarchy of components where each child component is routed to and is lazy loaded. All components use ChangeDetectionStrategy.OnPush and call changeDetectorRef.markForCheck() whenever they receive new data (from observables).

The very first time the page is loaded (e.g. browser refresh) the lowest level component fails to render showing the initial data. Once a change detection cycle occurs, the component is rendered correctly and the problem does not reoccur even as I route away to different components and back. The problem only occurs on the very first initial load in the browser (Very similar to https://github.com/angular/angular/issues/15626 which happens to have been the same code.)

If I change my component to call changeDetectorRef.detectChanges() when it receives new data instead of changeDetectorRef.markForCheck() then the problem goes away, however I don't think I should have to do this as I never did before this Angular version and there were no changes made out of the Angular zone.

## What is the motivation / use case for changing the behavior?

Component should render data as it used to before 4.2.0-rc.0

## Please tell us about your environment

<pre><code>
Angular version: 4.2.0-rc.0 and higher

Browser:
- [X] Chrome (desktop) version latest - didnt check other browsers
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Toxicable** [comment]
Sorry but without some reproduction this is near to un-actionable. I understand your project is complex as you mentioned but without a specific case where this occurs it's very difficulty to guess what could be causing it, there are simply too many variables at play in your application.

**Comment by slubowsky** [comment]
I know, but I am kind of hoping that @vicb will see this, and having authored https://github.com/angular/angular/commit/5d4f5434fd1c387f88ea46332a792ea94f9538da (which I dont know to be the cause but suspect is) and also having participated in working another issue that presented in the same way (https://github.com/angular/angular/issues/15626) would be able to offer some ideas as to whats happening and maybe even realize what needs to change to remove the regression.
I will still try to create a small repo duplicating the issue when I get a chance.

**Comment by slubowsky** [comment]
Haven't tried removing my work around (call detectChanges in ngAfterViewInit) since 4.2.0-rc.0 but as of at least 5.1.0-beta.0 this problem is now fixed and my work around no longer needed, Closing the issue.
