### ISSUE TITLE
Factories are module names are not canonical

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#17705]
## I'm submitting a ...

<pre><code>
[x] Bug report 
</code></pre>

## Current behavior

The name of factories modules in the compiler are not canonical causing simple file comparison for identity to fail causing #17389. PR #17675 fixed this by testing against the module name instead of the file name but this should not be necessary.

**Comment by JoostK** [comment]
Closing as obsolete as factories are being phased out.
