### ISSUE TITLE
Incorrect info about children in ActivatedRoute

### ISSUE THREAD

**Issue by rimlin** [angular/angular#17704]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When i tryed to check childrens of `ActivatedRoute` i get incorrect info about it in console, when i log `route.snapshot.children`. But if in console also log route object and invoke property getter of `children`, then i get correct value.

## Expected behavior

Correct value about childrens in `ActivatedRoute`. 

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/NrNLeGlcIPV0s3gpmP0R?p=preview
Open console, navigate to main and named outlet and you can see,  what with outputting `last child snapshot: ...` exists only 1 children (last value in row).
But, when you open `route:` value and invoke property getter of `snapshot.children` you can see here 2 chdilrens.

## Please tell us about your environment

<pre><code>
Angular version: 4.1.2

Browser:
- [x] Chrome (desktop) version 58.0.3029.110
 
For Tooling issues:
- Node version: v6.2.1
- Platform: Windows 
</code></pre>

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue. This may be due to when you log the value. The snapshot should be updated by the time `NavigationEnd` runs.
