### ISSUE TITLE
aio: Documentation for time-based releasing and deprecation policy

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#17717]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

About Angular's releasing strategy and deprecation policy, a reliable documentation is only an [official blog post](http://angularjs.blogspot.jp/2016/10/versioning-and-releasing-angular.html). 
This is very important information for people using Angular.

## Expected behavior

Releasing and deprecation policy pages in angular.io

I'm sorry if this has already discussed in the team.

cc/ @wardbell

**Comment by jenniferfell** [comment]
Thanks for your feedback. Resolved in v6: https://angular.io/guide/releases
