### ISSUE TITLE
Allow SlicePipe to work with Iterable objects (Symbol.iterator)

### ISSUE THREAD

**Issue by Yona-Appletree** [angular/angular#17711]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, the SlicePipe (and others) can only be used with arrays or strings (see https://angular.io/api/common/SlicePipe).

## Desired behavior
Allow SlicePipe (and other array-operating pipes) to be used with objects that implement `[Symbol.iterator]`. This would also allow direct use with generators, and be consistent with the fact that `ngFor` can work with iterable objects.

## Minimal reproduction of the problem with instructions

    @Component({
    	selector: 'test-component',
    	template: `<div *ngFor="let x of things() | slice:0:1"></div>`
    })
    export class TestComponent {
    	*things() {
    		yield 10;
    		yield 20;
    	}
    }

## What is the motivation / use case for changing the behavior?

`[Symbol.iterator]` is the standard way of having an iterable object in EcmaScript going forward, and is already supported by the built-in collections like `Set`. It seems natural to be able to use it in angular templates without having to use some helper function to convert the data into an array first.

**Comment by JoostK** [comment]
Closing as this hasn't received any interest and can be implemented in user code.
