### ISSUE TITLE
Share module as external lib

### ISSUE THREAD

**Issue by ryanfrnnds** [angular/angular#17715]
Good evening! I'm trying to share a NgModule.
At the root of my project I have:

Componens.d.ts {
    Export * from './lib/HelloWorld';
}

Components.js {
   Exports.HelloWorld = require ('./ lib / HelloWorld') HelloWorld;
}

![image](https://user-images.githubusercontent.com/7664019/27459403-82a07ffc-5784-11e7-89cd-bad7c66f05b7.png)

I have it published in a private repository and install normally with npm install.
I can use HelloWord (with the Component directive). But when I try to use the HelloWordModule (with the Module directive) I have problems.

An img to show how things are
![image](https://user-images.githubusercontent.com/7664019/27459546-2e36274a-5785-11e7-8c78-c2fdb3b1bbac.png)

The error that when used in another Angular project:
![image](https://user-images.githubusercontent.com/7664019/27459602-919d8df0-5785-11e7-8855-1b43fb1ab52c.png)

What is missing? Where did I go wrong?

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by dherges** [comment]
To help you find some info, some links for further reading:

angular/angular-cli/issues#4247
angular/angular-cli/issues#1692
angular/angular-cli/issues#6510
