### ISSUE TITLE
Angular 4 App not working in WPF Web Browser

### ISSUE THREAD

**Issue by Dameon13th** [angular/angular#17719]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
When setting the Source property of the WPF Web Browser a script error is displayed.
Line: 3323
Char: 36
Error: Expected idendtifier
Code: 0
Url: http://[Machine Name]/[Virtual Directory]/polyfills.bundle.js

## Expected behavior
I would expect the Angular web page to display.

## Minimal reproduction of the problem with instructions
1. Followed the Quickstart guide to install the Angular CLI.
2. Ran the Ng Build command from Visual Studio code.
3. Created a simple WPF application that contained a web browser control.
4. Set the Web Browser to navigate to the index.html file.

## What is the motivation / use case for changing the behavior?
It would increase the foot print of places in which Angular can be used.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2
- Platform: Windows

Others:
</code></pre>

**Comment by IgorMinar** [comment]
The error seems to be coming from the "polyfills.bundle.js" files, which means that it's not caused by Angular but rather either by a polyfill you are using or zone.js. Can you please reduce the issue down to the minimal set of dependencies and file an issue against the appropriate project that causes this problem? From what I see, it's not coming from Angular core.
