### ISSUE TITLE
Hidden element doesnt trigger any events.

### ISSUE THREAD

**Issue by leonardotessaroalves** [angular/angular#17727]
Hi, how i can trigger an event on hidden elements? 

i've tried all kind of line codes, but i cant fire the event when the element is hidden
(display:none).
someone can help?

e.g.
`
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import { 
  Directive,
  ElementRef,Renderer,
  AfterViewInit,
  OnInit,
  Output,
  Input,
  EventEmitter,
  forwardRef,
  SimpleChanges,
  HostListener } from '@angular/core';

import * as Choices from 'choices.js';
import * as $ from 'jquery';

@Directive({
  selector: '[choices]',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => ChoicesDirective),
      multi: true
    }
  ]
})
export class ChoicesDirective implements OnInit, AfterViewInit, ControlValueAccessor {

  public choiceEle;
  public selected;
  public Choices:Choices;  

    @Input() choicesConfig:any[];
    @Output() onChange : EventEmitter<any> = new EventEmitter();
    
    

  constructor( private ele : ElementRef, private renderer:Renderer) {}
  
  ngOnInit(){}

  ngAfterViewInit() {    
    this.Choices = new Choices(this.ele.nativeElement, {
      placeholderValue: 'Search...',
      removeItemButton: true,
      duplicateItems: false,      
      noChoicesText: '...',
      itemSelectText: '',
      searchFloor: 2,
      shouldSort: false,     
      callbackOnChange: this.callbackOnChange.bind(this)
    });    
  }        

  ngOnChanges(changes: SimpleChanges) {
    if (!this.choicesConfig) return;    
    this.Choices.setChoices(this.choicesConfig, 'id', 'label', true);
  }  

  @HostListener('click', ['$event'])  
  onClick(){
    this.Choices.toggleDropdown();
  }

  private callbackOnChange() {
    this.propagateChange(this.choiceEle.getValue());
    this.onChange.emit(this.choiceEle.getValue());
  }
}
`

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
