### ISSUE TITLE
Animations: 4.2 breaks auto style computation '*'

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#17729]
## I'm submitting a ...

<pre><code>
[x] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After upgrade to Angular 4.2, where new animation features were introduced, auto style computation `'*'` stopped working. Simple animation where you want to animate `background-color` is not possible because it fails with error:

Firefox: 
>EXCEPTION: Animation to or from an underlying value is not yet supported.

Chrome:
>EXCEPTION: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

This simple animation works in angular 4.1.3

I think it could be related to https://github.com/angular/angular/issues/14752

Also one interesting thing for Firefox. If you enable **dom.animations-api.core.enabled** in Firefox configuration it starts working, but it should work with default configuration. 

## Expected behavior
This should also work in higher version than 4.1.3. 

## Minimal reproduction of the problem with instructions
Working sample with Angular 4.1.3 - https://plnkr.co/edit/ZeRbHV0aZLa9MNT2oixW?p=preview
Broken sample with Angular 4.2.3 - https://plnkr.co/edit/JdctUV6hVfcOhdCbCyMk?p=preview

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 54
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 14
 
For Tooling issues:
- Node version: 7.7.3
- Platform: Windows

Others:

</code></pre>

**Comment by vteivans** [comment]
I'm having the same issue

**Comment by mikeeus** [comment]
Same here. And update on this?

**Comment by kukjevov** [comment]
Hi all, can you verify that it works with 4.3.1? It looks like to me, that https://github.com/angular/angular/commit/d22f8f5 fixes issue. 

Looks like that it is related to https://github.com/angular/angular/issues/17938

I am closing it, if you find that it is still not working let me know i will reopen it.
