### ISSUE TITLE
Minified code breaks when extending a base class with only optional parameters and not calling super

### ISSUE THREAD

**Issue by NielsFestjens** [angular/angular#17726]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When the javascript code is minified and the reflector searches for the parameters of a class that inherits another class but doesn't define a constructor (because the base class has only optional parameters), it returns the parameter of that base class.

## Expected behavior
The reflector should not look at the base class, since the derived class takes all the parameters it needs to satisfy the super call.

## Minimal reproduction of the problem with instructions
    @Injectable()
    export class ErrorInterceptor extends ErrorHandler {
        handleError(error: any) {
            // handle error
        };
    }

IMPORTANT:
The compiled javascript code needs to be minified to trigger the code. This does not occur when the code is not minified.

## What is the motivation / use case for changing the behavior?
The application breaks when we minify our code.

In our dev environment, the constructor of our class looks like this:

	function ErrorInterceptor() {
		return _super !== null && _super.apply(this, arguments) || this;
	}

In release mode, this gets minified, and then it looks like this:

	function t(){return null!==e&&e.apply(this,arguments)||this}

In Angular, the code where it goes wrong is here:

`ReflectionCapabilities._ownParameters` starts like this:

	if (DELEGATE_CTOR.exec(type.toString())) {
		return null;
	}

For the record, `DELEGATE_CTOR` is defined like this:

    DELEGATE_CTOR = /^function\s+\S+\(\)\s*{\s*("use strict";)?\s*(return\s+)?\S+\.apply\(this,\s*arguments\)/;

The minified version gives a match, so the method returns null. The calling method (`ReflectionCapabilities.parameters`) now checks the constructor of the parent, which has a boolean parameter, which it can't resolve, so it returns `[undefined]`.

The normal version does not give a match, because there's more than one space between the `return` and the `_super.apply`. The method then goes on to call its normal code, which results in `[]`, which is what we want.

## Please tell us about your environment

<pre><code>
Angular version: 2.4.2

Browser:
- [x] Chrome (desktop) version 58
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:
</code></pre>

**Comment by trotyl** [comment]
This is working as intended. As per [inheritance rule](https://github.com/angular/angular/issues/11606#issuecomment-262315256), when a child class doesn't define its own constructor, then it will inherit the constructor parameters from its parent.

Besides, as you can see in the [doc](https://angular.io/api/core/ErrorHandler), `ErrorHandler` is not even an `Injectable()` thus should not be extended (but implemented).

Anyway, since the constructor parameter has been removed in 5.0.0 (#18759), it's already fixed and can be closed now.
