### ISSUE TITLE
Injector tree does not take transclusion into account

### ISSUE THREAD

**Issue by oliverhanappi** [angular/angular#17723]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Assume there are the following components (and services they provide):

- ParentComponent
  - Selector: `parent`
  - Providers: `ParentService`
  - Template: `<child><ng-content></ng-content></child>`
- ChildComponent
  - Selector: `child`
  - Providers: `ChildService`
  - Template: `<ng-content></ng-content>`
- GrandChildComponent
  - Selector: `grand-child`
  - Injects: `ParentService` and `ChildService`

Consider the following template:

    <parent>
      <grand-child></grand-child>
    </parent>

The actual component tree is ParentComponent -> ChildComponent -> GrandChildComponent due to the transclusion in the template of the ParentComponent.

My expectation would be that the GrandChildComponent can inject the service ChildService, however Angular reports that there is no provider for ChildService.

## Expected behavior

The component GrandChildComponent should be able to inject the service ChildService because the "resolved" DOM looks like this:

    <parent>
      <child>
        <ng-content> 
          <ng-content> 
            <grand-child>
          </ng-content>
        </ng-content>
      </child>
    </parent>

## Minimal reproduction of the problem with instructions

1. Open http://plnkr.co/edit/Cw8YRbBWL6SA8Fbr767j
2. Click run
3. Inspect the browser console

## What is the motivation / use case for changing the behavior?

This is useful when composing higher level components from other components that already use transclusion and services to communicate with each other.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser: occurs every
- [x] Chrome (desktop) version 58.0.3029.110
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.10.3 
- Platform: Windows 

Others:

</code></pre>

**Comment by kemsky** [comment]
I think it used to work in the past, however it might have been changed silently. I created similar issue for templates #14935.

**Comment by vicb** [comment]
This is working as expected: nodes are only "projected" (moved to a different location) but everything else works relative to their source (= before projection) location.
