### ISSUE TITLE
feat(core): @Volatile() decorator to allow unstable properties for change detection

### ISSUE THREAD

**Issue by trotyl** [angular/angular#17725]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In dev mode, Angular will have additional change detection to make sure all properties not being changed after first change detection.

For example, when we have a getter to call `Map#keys()`, it would throw `ExpressionChangedAfterItHasBeenCheckedError` since it returns a new `Iterator` each time:

```typescript
@Component({
  template: `
    <ul>
      <li *ngFor="let key of keys">{{ key }}</li>
    </ul>
  `,
})
export class App {
  private map: Map<number>
  
  constructor() {
    this.map = new Map([
      ['a', 1],
      ['b', 2],
      ['c', 3],
    ])
  }
  
  get keys() {
    return this.map.keys()
  }
}
```

A live example could be found [here](https://plnkr.co/edit/E5kvFLWNEjN3NVfur7HL?p=preview).

## Expected behavior

Since we know that the new iterator is equal to the old one in semantics, we can tell Angular to ignore its (and its sub-properties') change by adding an `@Volatile()` decorator to the property:

```typescript
@Component({
  template: `
    <ul>
      <li *ngFor="let key of keys">{{ key }}</li>
    </ul>
  `,
})
export class App {
  private map: Map<number>
  
  constructor() {
    this.map = new Map([
      ['a', 1],
      ['b', 2],
      ['c', 3],
    ])
  }
  
  @Volatile()
  get keys() {
    return this.map.keys()
  }
}
```

And no error would be thrown.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/E5kvFLWNEjN3NVfur7HL?p=preview

## What is the motivation / use case for changing the behavior?

This would help with getter-style implementations and some low-level operations.

Relates to:

https://github.com/angular/angular/issues/2246
https://github.com/angular/angular/issues/15464
https://github.com/angular/angular/issues/15721
https://github.com/angular/angular/issues/16049
https://github.com/angular/angular/issues/17070
https://github.com/angular/angular/issues/17347
https://github.com/angular/angular/issues/17572
https://github.com/angular/angular/issues/17724

**Alternatives**:

+ Introduce a `volatile` property in Component Metadata to disable the second-time checking at Component level.

## Please tell us about your environment

<pre><code>
Angular version: not relevant

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: not relevant 
- Platform: not relevant 

Others: none

</code></pre>

**Comment by dawidgarus** [comment]
As a workaround You can convert iterator to array: `Array.from(this.map.keys())`. It seems that angular compare arrays by the content, not reference.

**Comment by trotyl** [comment]
> As a workaround You can convert iterator to array: Array.from(this.map.keys())

This would require the setter-style usage, whenever you change the map, the array needs to be recalculated. I don't think it's user-friendly.

**Comment by trotyl** [comment]
> Other solution would be creating differ for objects with @@iterator property, so collections could be used directly.

And this uses the runtime functionally to solve the debugging problem, even I can have different providers in production mode, it introduces a lot extra complexity.

**Comment by dawidgarus** [comment]
@trotyl no setter needed, just:
```ts
get keys() {
  return Array.from(this.map.keys());
}
```

**Comment by trotyl** [comment]
@dawidgarus Thanks, that does work for this simple case.
But when comes the inline map usage (from [this comment](https://github.com/angular/angular/issues/2246#issuecomment-309735097)), it won't work:

```html
<ul>
  <li *ngFor="let key of map.keys()">{{ key }}: {{ map.get(key) }}</li>
</ul>
```

And there must be some custom pipe to achieve that.

**Comment by dawidgarus** [comment]
@trotyl You can't apply `@Volatile` decorator to inline expression, so it becomes moot.
Custom pipe wouldn't be a bad idea - You could specify which iterator You wan't to use:
```html
<li *ngFor="let entry of map | iterator:'entries'">{{ entry[0] }}: {{ entry[1] }}</li>
```

**Comment by trotyl** [comment]
@dawidgarus That's why it is for marking all the sub-expressions of that property.

The point is, all of those code already works (both dev & prod modes), but people are getting annoyed since some errors (actually can be considered warning as it's still working fine) are raised (in dev mode only). 

Angular shouldn't force user to change a working-fine case to another one just for ignore the error-like warning.

**Comment by ChinesePeanuts** [comment]
Why not simply doing this ? (if it's the issue here)  
```
get map() {
  return Array.from(this.map.entries());
}
```

```
<li *ngFor="let entry of map'">{{ entry[0] }}: {{ entry[1] }}</li>
```

**Comment by trotyl** [comment]
@ChinesePeanuts That is a valid workaround, but just a workaround. No one came to Angular to finding how many workarounds there is, and that's something should not be addicted to.

The proposal here is to get rid of those workarounds in achieving something that already works.

**Comment by ChinesePeanuts** [comment]
@trotyl I understand, and I post it as a workaround (I might not have been so clear).
There should be a proper way to do this, indeed !
