### ISSUE TITLE
The problem of compatibility in angular2 with jquery

### ISSUE THREAD

**Issue by llhm** [angular/angular#17722]
In dev of html pages,i need to do a resizable div and i found a effect in jquery,but finally there is a bug in page that i wanna to use jquery,there is no effect when the page loaded firstly,but it could be used when that page refreshed. I wanna to kown what reason is caused,thanks!

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kondasMajid** [comment]
basically this issues with angular Jquery really needs to be point out the right solution.
@llhm incase you find the solution, kindly share to me
