### ISSUE TITLE
docs: Tab title of docs in browser is prefixed with "link"

### ISSUE THREAD

**Issue by NiklasMerz** [angular/angular#17732]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The document title / title of browsertab contains "link" prefix,

## Expected behavior
Actual section as title

## Minimal reproduction of the problem with instructions
* Open angular.io
*  Click docs
* Tab title not correct

## What is the motivation / use case for changing the behavior?
* Read the docs

## Please tell us about your environment

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 54
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by gkalpak** [comment]
This is again a `textContent` vs `innerText` issue 😞

**Comment by gkalpak** [comment]
Possible solutions:

1. In [doc-viewer][1], use `innerText` and fallback to `textContent` when not available (e.g. old Firefox versions):

```diff
-title = titleEl.textContent.trim();
+title = (titleEl.innerText || titleEl.textContent).trim();
```

2. In [doc-viewer][1], detect the `.class-link` element in the `<h1>` and manually ignore it.

```diff
-title = titleEl.textContent.trim();
+const headerLink = titleEl.firstElementChild;
+const linkText = headerLink && headerLink.textContent || '';
+title = titleEl.textContent.substring(linkText.length).trim();
```

3. In dgeni's [autolink-headings][2] post-processor, add a simple processor (or hatever it's called), that stores the original text content on an attribute:
 
```diff
 const slug = require('rehype-slug');
 const link = require('rehype-autolink-headings');
+const is = require('hast-util-is-element');
+const toString = require('hast-util-to-string');
+const visit = require('unist-util-visit');
 ...
 module.exports = [
   slug,
+  () => tree => {
+    visit(tree, 'element', node => {
+      if (is(node, 'h1')) {
+        node.properties.originalText = toString(node).trim();
+      }
+    });
+  },
   [link, {
     properties: {
```

Then in [doc-viewer][1], use the attribute to retrieve the text content:

```diff
-title = titleEl.textContent.trim();
+title = titleEl.getAttribute('original-text');
```

##
@petebacondarwin, wdyt?

[1]: https://github.com/angular/angular/blob/30f4fe26e02d25eeed7c4b8824b62decd57da3c2/aio/src/app/layout/doc-viewer/doc-viewer.component.ts#L100
[2]: https://github.com/angular/angular/blob/30f4fe26e02d25eeed7c4b8824b62decd57da3c2/aio/tools/transforms/angular-base-package/post-processors/autolink-headings.js#L8

**Comment by wardbell** [comment]
I like (1)

**Comment by petebacondarwin** [comment]
Yes 1
