### ISSUE TITLE
docs: Quickstart screenshot is out of date

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#17735]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The quickstart doesn't correspond to the output of the latest CLI's `ng new`.

https://angular.io/guide/quickstart

It says "Your app greets you with a message:" with "App Works"  in an image box.

The CLI no longer generates "App Works".

## Expected behavior
The message in the box should be " Welcome to app!!"

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4 / 4.4.5
Docs Site Version 4.2.5-build.32090+sha.9344c86.
</pre></code>

**Comment by Foxandxss** [comment]
I will update the quickstart to the latest version which I believe have even a different message.
