### ISSUE TITLE
https://angular.io/tutorial/toh-pt3#add-hero-detail  | Wrong source file name : src/app/app.component.html >  app.component.ts

### ISSUE THREAD

**Issue by jgfet** [angular/angular#17749]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/tutorial/toh-pt3#add-hero-detail
documentation refers to src/app/app.component.html 

## Expected behavior

At this point it's still inlined in selector, so should be app.component.ts
## What is the motivation / use case for changing the behavior?

clarification of appropriate source file to modify at this point in the coding.

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

@angular/cli: 1.1.0
node: 7.9.0
os: darwin x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  7.9.0
- Platform: Mac

Others:
nothing more!

**Comment by wardbell** [comment]
See PR #17752

**Comment by trotyl** [comment]
Obsolete. The new tutorial always use individual html templates.

**Comment by jenniferfell** [comment]
Thanks, @trotyl
