### ISSUE TITLE
Angular 4 Route fails if added parameter with hyphen

### ISSUE THREAD

**Issue by zishanj** [angular/angular#17742]
I am using Angular 4 and if I use hyphen between parameters instead of slash, the route does not work as expected. Here is my route:

`{ path: ':bookId/:pageFrom-:pageTo', component: BookComponent }`

I was expecting to receive the values of `pageFrom` and `pageTo` in separate params but I am receiving it in `pageFrom-:pageTo`.  I have also tried to escape the hyphen with `\` but that also does not work.

**Comment by httpsOmkar** [comment]
You should use router parameter for this for more refer
[Router toutorial](https://angular.io/guide/router#route-parameters-in-the-activatedroute-service)

**Comment by zishanj** [comment]
I am already using it and that's what I have mentioned above. Its taking hyphen as single parameter `pageFrom-:pageTo` instead of 2 separate params.

**Comment by httpsOmkar** [comment]
Use following code this.
```typescript
{ path: ':bookId', component: BookComponent }
```
In your component do 
```typescript
constructor(private _activatedRoute: ActivatedRoute) {
    this._activatedRoute.params.subscribe(v => {
            // You can get param here v['pageFrom'];
            // You can get param here v['pageTo'];
    });
}
```

**Comment by Simon-Briggs** [comment]
Consider using queryParams instead as httpsOmkar mentioned above so the url will be `:bookId?pageFrom=1&pageTo=10` ?

**Comment by zishanj** [comment]
I have other ideas also to implement it like splitting the string later by hyphen.. But I am looking for something more genuine like this `{ path: ':bookId/:pageFrom-:pageTo', component: BookComponent }` which will allow the use of hyphen `-` as separator instead of `/`

**Comment by jasonaden** [comment]
You could use a custom [UrlSerializer](https://angular.io/api/router/UrlSerializer) to parse the URL as you see fit.

**Comment by sushrest** [comment]
@zishanj were you able to find the solution for this usecase. I ended up adding a util function and use regex to extract the required info from the Url, I tried using matcher from angular/router which didn't helped either.

**Comment by zishanj** [comment]
@sushrest Its a very old thread. As far as I remember I have used my custom solution like mentioned in my last comment, probably by splitting the string by hyphen.
