### ISSUE TITLE
Animation Regression between 4.2.0-rc.1 and 4.2.0-rc.2 - Still here in 4.2.4

### ISSUE THREAD

**Issue by toniopelo** [angular/angular#17746]
## I'm submitting a Regression

<pre><code>
[x] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

One animation just doesn't appear. Difficult to explain, better see on the plunker provided after.
You will see that the blue and red block that are coming above the grey one on route change and are supposed to go backward on next route change just disappear on v4.2.0-rc.2 and above.
Explainations are on the plunker

## Expected behavior

The animation should display as it does with Angular v4.2.0-rc.1

## Minimal reproduction of the problem with instructions

See this plunker: https://plnkr.co/edit/0xYfsX7Z2RQyZGmNgPOw?p=preview
Just change the version from 4.2.0-rc.1 to 4.2.0-rc.2 or higher to see the difference in the animations.

## What is the motivation / use case for changing the behavior?

Make it work :D

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chromium (desktop) version 58.0.3029.110
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v7.10.0
- Platform: Linux
</code></pre>

Maybe there is something to do with this issue #17170 
Both regressions appeared on the same time apparently.

Thanks for your help and have a nice day!

**Comment by matsko** [comment]
Excellent find. We now have a proper fix https://github.com/angular/angular/pull/17777

**Comment by toniopelo** [comment]
Thanks! When can we expect this to be released ?
