### ISSUE TITLE
Support 'class' in hostAttributes

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1774]
I want to simply add a css class to the host element of a directive (either `@Component` or `@Directive`):

```js
@Directive({
  selector: 'md-input-container input',
  hostAttributes: {
    'class': 'md-input'
  }
})
```

Any `hostProperties` or user bindings should be in _addition_ to these classes. In cases where there are collisions, the user defined binding should win.

@mhevery @pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
@jelbourn @mhevery this would be trivial to special-case this one (that is - have a special case for _merging_ different classes specified on a host element, will send a PR later today) but the more I think about all the `host*` properties of a `@Component`, the more I'm leaning towards using a string-based syntax, sth like:

```javascript
@Component({
    host: `class="foo bar" [someprop]="soExp" (click)="invokeMe()"`
})
class MyComponent {...}
```

This would be close to what we write in templates, so users don't need to learn new syntax. Shouldn't be hard to implement as we've got already all the parsing logic in a compiler. WDYT?

**Comment by matanlurey** [comment]
I sort of like Pawel's concept. Could go one step further:

```javascript
@Component({
  host: {
    'class': 'foo bar',
    '[someprop]': 'soExp',
    '(click): 'invokeMe()'
  }
})
```

This would likely be more toolable as a +.

**Comment by mhevery** [comment]
@matanlurey, @PascalPrecht  That is a good idea. (I vote for hash). Need to discuss with @vsavkin about how it fits with `actions`.
