### ISSUE TITLE
docs/aio: bug in linkReactiveForms guide /guide/reactive-forms

### ISSUE THREAD

**Issue by omouse** [angular/angular#17744]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
Given the component typescript code:

```typescript
import { Component }              from '@angular/core';
import { FormControl }            from '@angular/forms';
@Component({
  selector: 'hero-detail',
  templateUrl: './hero-detail.component.html'
})
export class HeroDetailComponent1 {
  name = new FormControl();
}
```

And the component template:

```html
<h2>Hero Detail</h2>
<h3><i>Just a FormControl</i></h3>
<label class="center-block">Name:
  <input class="form-control" [formControl]="name">
</label>
```

Angular complains that `formControl` isn't a property of input.

What's more interesting is that later on the template looks like this:

```html
<h2>Hero Detail</h2>
<h3><i>FormControl in a FormGroup</i></h3>
<form [formGroup]="heroForm" novalidate>
  <div class="form-group">
    <label class="center-block">Name:
      <input class="form-control" formControlName="name">
    </label>
  </div>
</form>
```

As you can see, not only does the first HTML template give an error, but it also doesn't match the later HTML template:

    <input class="form-control" [formControl]="name">
    <input class="form-control" formControlName="name">

## Expected behavior

All the examples of Reactive Forms in the guide should work.

**Comment by ericmartinezr** [comment]
https://angular.io/guide/reactive-forms#import-the-reactiveformsmodule

**Comment by omouse** [comment]
@ericmartinezr yes I already have done that. My module does have the ReactiveFormsModule in the `imports` list for the `NgModule` specification.

**Comment by ericmartinezr** [comment]
It works, imported ReactiveFormsModule.
http://plnkr.co/edit/wooB5F2mFC6cSVqcDo12?p=preview

it doesn't work, no ReactiveFormsModule imported.
http://plnkr.co/edit/lc8eyIe6WEif4BuBAK5a?p=preview

**Comment by wardbell** [comment]
We have not yet decided on a mechanism for versioning the docs nor how to budget our efforts.

At the moment, the docs reflect the latest point releases and there is no commitment that doc changes won't be "breaking" (that's an Angular code commitment).

As @ericmartinezr demonstrates, the code does work for the current release of Angular. I'll have to close this issue. But thanks for paying attention.
