### ISSUE TITLE
min Attribute on Input Type Number Not Working

### ISSUE THREAD

**Issue by Tsmith18256** [angular/angular#17758]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using Angular 4.2.4, the `min` attribute on an HTML `input` element with `type="number" is not working with Angular.

The browser sees it correctly and stops the arrows from allowing you to go below the minimum, but Angular still considers it valid when you manually type a number below the min.

## Expected behavior

Angular should consider the element invalid if the `min` rule is violated.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/TGxvz8STg6WAIPWnShpe?p=info

In the above plunker, the button should become disabled when any number below 1 is entered. As it is set up now, it does not work.

If you change `min="1"` to be `pattern="[1-9]\d*"`, the intended behaviour occurs.

## What is the motivation / use case for changing the behavior?

Support for `min` was added to [the form validators](https://github.com/angular/angular/blob/master/packages/forms/src/validators.ts) in 4.2.0.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 53
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.9.0 
- Platform: Mac 10.12.15

Others:
I tried this in Chrome and Firefox with my app and Firefox worked, but not Chrome; however, when I tried the Plunker I made, neither worked.
</code></pre>

**Comment by Toxicable** [comment]
Due to a regression caused by the `min` validator added in 4.2.0 it has since been removed and will be readded at a later time when the issues around the regression can be solved

**Comment by Tsmith18256** [comment]
Thank you @Toxicable, I will close this issue and keep an eye on the related one.
