### ISSUE TITLE
NgTemplateOutletContext doesn't work with closure compiler

### ISSUE THREAD

**Issue by dmitrysteblyuk** [angular/angular#17750]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Context properties are not available in ng-template when using closure compiler

## Expected behavior
Should be available

## Minimal reproduction of the problem with instructions
I forked from official closure demo and added template context test: https://github.com/dmitrysteblyuk/closure-demo

## What is the motivation / use case for changing the behavior?
Now the only working option (for closure compiler) to pass context is not widely used and inconvenient (doesn't allow to use pipes etc).

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser: any
 
For Tooling issues:
- Node version: 7.10.0
- Platform: Windows 10

Others:

</code></pre>

**Comment by vicb** [comment]
Please add guidelines on how to observe the error with your repo.

**Comment by dmitrysteblyuk** [comment]
@vicb you just run like this
$ yarn install
$ yarn run build
$ yarn run serve 
Then you can see which options to pass outlet context fails. They're all listed in test.component.html

**Comment by dmitrysteblyuk** [comment]
Fixed in 4.2.6
