### ISSUE TITLE
aio: <code-tab> tab headings should wrap

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17751]
Right now they truncate which often renders them useless as one cannot tell what file is affected. 

For example, see the code-tab just above https://angular.io/tutorial/toh-pt3#the-road-youve-travelled

**Comment by petebacondarwin** [comment]
I assume you mean the labels on the tabs themselves need to wrap?

**Comment by petebacondarwin** [comment]
This 

![screen shot 2017-07-15 at 22 53 27](https://user-images.githubusercontent.com/15655/28242912-7ab5785e-69b0-11e7-87f1-213c9137d4d1.png)

compared to

![screen shot 2017-07-15 at 22 53 44](https://user-images.githubusercontent.com/15655/28242913-835fe25a-69b0-11e7-9e01-5dc8d1fec8d7.png)

**Comment by petebacondarwin** [comment]
I'm not sure what CSS rules we can employ to fix this... @sjtrimble or @gkalpak  any ideas?

**Comment by gkalpak** [comment]
`white-space: nowrap` should do the trick.
