### ISSUE TITLE
es5build.js broken with alpha22

### ISSUE THREAD

**Issue by mwq27** [angular/angular#1776]
File di.es6, with map di.map, is now di.es6.map, which is breaking the es5build.js.  There are a lot of files which were switched to 
```
file.es6.map
```
instead of 
```
file.map
```

**Comment by aminroosta** [comment]
i have the same problem ...

**Comment by memolog** [comment]
Although I don't think it's good way to fix this issue, as a quick workround, I overwrote the es5build.js as follows:

```
-      fs.readFile(file.path.replace('.js', '.map'), function(error, buffer) {
+      var filePath = file.path.replace('.js', '.map');
+      var exists = fs.existsSync(filePath);
+      filePath = exists ? filePath : file.path.replace('.js', '.es6.map');
+      fs.readFile(filePath, function(error, buffer) {
```
https://gist.github.com/memolog/99e93f473060a77618e8

**Comment by mhevery** [comment]
dup: https://github.com/angular/angular/issues/143
