### ISSUE TITLE
TypeError: Cannot set property 'prototype' of undefined, after typescript is updated to 2.4.0

### ISSUE THREAD

**Issue by djnaumov** [angular/angular#17768]
After typescript is updated from 2.3.3 to 2.4.0

```
Uncaught TypeError: Cannot set property 'prototype' of undefined
    at __extendsFn (index.js:15)
```
Angular version: 4.2.4
Typescript version: 2.4.0

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
