### ISSUE TITLE
AOT compilation error

### ISSUE THREAD

**Issue by YD1722** [angular/angular#17762]
`ERROR in Unexpected value 'null' imported by the module 'AppModule in D:/Git/ng_v4_aot/src/app/app.module.ts'`

project build successfully, but AOT compilation failed.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
