### ISSUE TITLE
Search in v2 documentation

### ISSUE THREAD

**Issue by samized** [angular/angular#17763]
Thanks for separating the old v2 and the new documentation. This is really helpful.
Unfortunately, the search field in the v2 documentation does not work properly:
https://v2.angular.io/docs/ts/latest/

Pressing enter does not trigger search, on any browser. Thanks for fixing ;)

**Comment by petebacondarwin** [comment]
We are not planning to do any further work on the v2 docs as this is not LTS and we have a completely new app for displaying docs from v4 onwards.
