### ISSUE TITLE
QueryParamsHandling documentation

### ISSUE THREAD

**Issue by chriscurnow** [angular/angular#17778]
## I'm submitting a
Documentation Issue or request.

## Current behavior
There is no useful documentation for queryParamsHandling. There is a single line use case under NavigationExtras but this gives no detail regarding the parameters available to use. As far as I can tell there is no other reference to this in the documentation. A query for "queryParamsHandling" at the top level of the angular documentation yields nil results.

## Expected behavior

1.  This option should be documented.
2. I should be able to find references to this option by searching in the documentation.

**Comment by chriscurnow** [comment]
There is mention of **preserveQueryParameters** in the Routing and Navigation but this parameter is deprecated.

**Comment by dgroh** [comment]
What are the other options for **queryParamsHandling** but `merge`?

**Comment by sfdeloach** [comment]
Another option for **queryParamsHandling** is `'preserve'`, which I believe is similar to the deprecated **queryParamsHandling** being set to `true`.

**Comment by niklas-dahl** [comment]
fyi https://github.com/angular/angular/blob/5.0.1/packages/router/src/config.ts#L330

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/20023

**Comment by cWillow** [comment]
I don't think this is complete. There is information in the [Router Link description](https://angular.io/api/router/RouterLink#description) but shouldn't this info also be in the [queryParamsHandling description](https://angular.io/api/router/NavigationExtras#queryParamsHandling), or at least a link to it?

**Comment by lucashfreitas** [comment]
+1. I was just reading the documentation and it does not have enough information about all the available options for **queryParamsHandling**. The documentation only has one example using `'merge'` option but nothing about others options and **side effects**.

[Here's the documentation link](https://angular.io/api/router/NavigationExtras#preserveQueryParams )

**Comment by lucashfreitas** [comment]
@brandonroberts , the official documentation seems to still be incomplete. Can we help with anything to update it? :) [https://angular.io/api/router/NavigationExtras#preserveQueryParams](https://angular.io/api/router/NavigationExtras#preserveQueryParams)
