### ISSUE TITLE
commonJs adapter should use an external library

### ISSUE THREAD

**Issue by rkirov** [angular/angular#1777]
The commonJs adapter is starting to look like a full commonJS shim for the browser environment. Currently it implements event listeners, querySelector etc. At that point we should make its own project or (preferably) reuse an existing one.

ref:
https://github.com/angular/angular/blob/master/modules/angular2/src/dom/parse5_adapter.cjs

**Comment by btford** [comment]
https://github.com/tmpvar/jsdom ?

**Comment by inikulin** [comment]
[PolymerLabs/dom5](https://github.com/PolymerLabs/dom5)?

**Comment by gdi2290** [comment]
parse5 doesn't care about styles (with good reason) but that's limiting for something like server rendered views. Styles won't show up on the initial load until Angular bootstraps the view. JsDom switch to io.js after 3.x so for node support you would have to use 3.x

**Comment by tbosch** [comment]
This might be obsolete with #2657...

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
