### ISSUE TITLE
TestBed.createComponent should error if TestBed.compileComponents is pending

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#17770]
I have seen several people (both inside and outside Google) writing unit tests that use `TestBed.createComponent(...)` immediately after `TestBed.compileComponents()` without waiting for the latter to resolve. This will often silently work, only to someday fail out of the blue because something seemingly unrelated changed. 

`createComponent` should throw an informative error if this occurs. 

This is something that should happen in Angular 5, as it is technically a breaking change (tests that pass today, while wrong, still succeed).

**Comment by alxhub** [comment]
Closing as we've since rewritten the `TestBed` with Ivy, and the cases where `compileComponents()` is necessary are very _very_ slim. In most cases, it actually works synchronously now, and does not even need to be `await`ed.
