### ISSUE TITLE
removing npm postinstall from circle config breaks linting

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#17776]
In [this commit](https://github.com/angular/angular/commit/08ecfd891dc66813fb7819148181bcba5a6fe75c) we removed the `npm postinstall`. During `npm install` it appears there's a failure running `webdriver-manager update`. We get the following in the `npm install` logs:

`npm WARN lifecycle angular-srcs@4.3.0-beta.0~postinstall: cannot run in wd %s %s (wd=%s) angular-srcs@4.3.0-beta.0 node tools/npm/copy-npm-shrinkwrap && webdriver-manager update /root/ng`

After removing `npm postinstall` from `circle/config.yml`, the linting step started failing because `node_modules` was out of sync with the shrinkwrap:

https://circleci.com/gh/angular/angular/15779?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I've added back the `npm run postinstall` to avoid having this error, but we should loop back to confirm this is what we actually want to do.

Note that we are now caching the `bazel` installed version of `node_modules`, which is also not running `npm run postinstall`. Meaning we won't be caching the version of `node_modules` that actually works with linting.

**Comment by IgorMinar** [comment]
I'm not sure if this is still relevant. we'll need to take a closer look

**Comment by gkalpak** [comment]
We are now doing the env setup (including yarn install) is a [single job][1], which all other jobs depend on.
So, I believe this issue is obsolete. (Please, reopen if not.)

[1]: https://github.com/angular/angular/blob/a28b3e33598cf6a9fae685d8c1a1e39b419d1c78/.circleci/config.yml#L123
