### ISSUE TITLE
How to upload files to amazon aws.

### ISSUE THREAD

**Issue by rameshmkll** [angular/angular#17781]
Where can i find the documentation for uploading files to amazon aws s3 using angulr 2.

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
Here's a small example showing how you can upload files https://plnkr.co/edit/kK5rQkK8e2KZohsdhNEq?p=preview

**Comment by pkozlowski-opensource** [comment]
Thnx @Toxicable
