### ISSUE TITLE
[Usage] InjectionToken in shared module

### ISSUE THREAD

**Issue by hintdesk** [angular/angular#17784]
Hi,
I would like to ask how I can feed an Interface Injection into a shared module. The shared module will be published over npm and referenced by real app over npm.

For example, I have a component in a module.  This component receives an instance of interface through injection (Context is here an interface) 

```
constructor(
		@Inject(IceRuntimeContext) private context: Context
	) {
		super();
	}
```

I would like to export this component and his module as shared module so that I can use it in real angular app

```
export class IceCalendarModule {
	static forRoot(): ModuleWithProviders {
		return {
			ngModule: IceCalendarModule,
			providers: [
				//What should I write here???
			]
		}
	}
}
```

In the Angular app (app.module.ts), I import this module
```

imports:[
IceCalendarModule
]
```

declare the token

`export const IceRuntimeContext = new InjectionToken<Context>('Context');`

and declare the providers

```
providers: [
		{ provide: IceRuntimeContext, useClass: MockIceRuntimeContext }
	]
```

But the IceRuntimeContext is not available for my shared module. I received an error saying that "No provider for Context".

**Question**: How should I configure IceCalendarModule so that I can inject the token IceRuntimeContext from external app?

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment]
Here's an example showing how you can provide a class in your module ready for import into another module. It makes no difference if it's coming from npm or not
```
export const IceRuntimeContext = new InjectionToken<Context>('Context');
@NgModule({
  providers: [ {provide: IceRuntimeContext, useClass: Context}  ]
})
export class IceCalendarModule {}
```
Read more here: https://angular.io/guide/ngmodule
and https://angular.io/guide/ngmodule-faq

**Comment by IgorMinar** [comment]
thanks @Toxicable
