### ISSUE TITLE
Angular version 4 - animations broken when you don't specify unit

### ISSUE THREAD

**Issue by NetanelBasal** [angular/angular#17783]
[ x ] Regression (behavior that used to work and stopped working in a new release)

## Current behavior
Recently I updated a project to Angular 4. Suddenly the animation stopped working. After a few attempts, I discovered that if I change the following code:

```
trigger('state', [
  state('...', style({height: 50, paddingTop: 0}))
  state('...', style({height: 10, paddingTop: 10}))
])
```

to:
```
trigger('state', [
  state('...', style({height: '50px', paddingTop: '0px'}))
  state('...', style({height: '10px', paddingTop: '10px'}))
])
```
It's working. I don't know why it was happening. In version 2 it worked. 

The problem is not documented anywhere, so I wanted to spare someone else the trouble.

**Comment by skreborn** [comment]
This seems like a bug indeed, as [`normalizeStyleValue`](https://github.com/angular/angular/blob/master/packages/animations/browser/src/dsl/style_normalization/web_animations_style_normalizer.ts#L17) is still supposed to convert unitless numbers to pixel values.

**Comment by NetanelBasal** [comment]
I'll try to reproduce it when I have time. If I can not, I'll close the issue.

**Comment by NetanelBasal** [comment]
You can tag it as need reproduce.

**Comment by NetanelBasal** [comment]
Could not reproduce the problem in an isolated environment, closing for now.
