### ISSUE TITLE
docs(aio): Misspelling in a 'The root folder' table entry on the Quickstart page

### ISSUE THREAD

**Issue by jlusk** [angular/angular#17795]
<img width="871" alt="screen shot 2017-06-27 at 11 22 55 am" src="https://user-images.githubusercontent.com/13967323/27595564-04b132b2-5b2b-11e7-9306-a872c14f9641.png">

## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

On https://angular.io/guide/quickstart, in the table under heading 'The root folder,'  the Purpose entry for `.angular-cli.json` includes the sentence "In this file you can set several defaults and also configure what files are included when your project is **build**."

## Expected behavior

In this same Purpose entry, the sentence should read: In this file you can set several defaults and also configure what files are included when your project is **built**." Or the structure of the sentence be changed in a way to make 'build' work.

## Minimal reproduction of the problem with instructions

(1) Go to https://angular.io/guide/quickstart
(2) Scroll down to the 'The root folder' heading
(3) View the misspelling in the table under this heading for the `.angular-cli.json` row's Purpose column.

## What is the motivation / use case for changing the behavior?

To correct the spelling in this entry.

## Please tell us about your environment
Production, hitting the website directly.
<pre><code>
Angular version: X.Y.Z

NA
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by hartraft** [comment]
I think this can be closed as it was fixed in [PR#17818](https://github.com/angular/angular/pull/17818/commits/6a1ba194b0f1604ddc93b56d3f35542556cb36fb)
