### ISSUE TITLE
Amazon Silk browser for Amazon fire tablets

### ISSUE THREAD

**Issue by willgilchrist** [angular/angular#17796]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using amazon silk browser on an amazon fire tablet, angular does not operate well.  The HTML will be shown but interactions with the server-side api will not respond.

## Expected behavior

To be able to interact with the forms shown, and receive a success message that data have been submitted and received.  
Current behaviour on Amazon silk tablet is that the form hangs and the message [object ProgressEvent] is shown, instead of a success message.

## Minimal reproduction of the problem with instructions

Example application used - https://github.com/cornflourblue/mean-angular2-registration-login-example  

This application when running, can be launched on the tablet, but cannot successfully interact with the forms.  The forms will not process through to a successful end-result, instead they will hang.

## What is the motivation / use case for changing the behavior?

To enable angular applications which require a log-in (or other form input) to work on the amazon fire tablet family.

## Please tell us about your environment
Mongo DB 3.4
NPM 5.0.3
Node 8.1.2
Windows 10 pro (server)
Amazon fire 7 inch tablet O.S. version 5.4.0.0  (Android 5.1.1; KFFOWI Build/LVY48F)
Amazon silk browser ver 59.1.92.3071.92.10 (client)

<pre><code>
Angular version: 4  (core angular package.json id = 4.2.4)

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

Other browser - Amazon Silk Browser on Amazon fire 7inch tablet.

For Tooling issues:
- Node version: XX 
- Platform: 

Others:

Amazon silk - is a split browser.  http://docs.aws.amazon.com/silk/latest/developerguide/introduction.html  

</code></pre>

**Comment by robwormald** [comment]
So the Silk Browser isn't covered in our Browser Support Matrix, so it's not tested on our CI, nor do I think anyone here has one to test on. 

My totally wild guess would be the Fire does something special with XHR status codes, we've seen that previously with older Android devices. If you can narrow it down further we'd be happy to see what we can do to fix it, but we'll need a bit more support from your end.

**Comment by willgilchrist** [comment]
Hi Rob, I'll investigate the reason.  What would be a good way to do this with a tablet, should I packetsniff the traffic from the server?  Or should I be trying another technique to identify why it isn't being processed correctly.  I would hope to have a solid understanding of the issue by the end of the month.

**Comment by alxhub** [comment]
I'm actually going to close this issue as obsolete, since it's been 3 years, Silk is not supported by Angular, and there's no further information on what changes could be made in `HttpClient` to support it.

@willgilchrist if this is still a concern for you, please feel free to open a fresh issue with more information. Thanks!
