### ISSUE TITLE
Angular 4 animation transition not working as expected

### ISSUE THREAD

**Issue by zishanj** [angular/angular#17802]
I am using latest Angular 4.2 version and have tried a demo on plunker after following animation tutorial to animate `ngIf`. I have seen that the `transition` animate is not working as expected.

`
animations: [
      trigger('animateMe', [
        state('void', style({transform: 'translateY(-100%)'})),
        transition('* => *', animate(1000))
        ])    
    ]
`

These codes were seen working in his video tutorial. Not sure about the version of Angular he was using. I have my [plunker](https://plnkr.co/edit/bAxkxbo3QEo7R5GZpKdW?p=preview)

Is this a known bug or I am missing something?

**Comment by zishanj** [comment]
Gotcha! I have to include `web-animations.min.js` polyfill to support my Safari browser on Mac and it works like a charm.

**Comment by bankotigaurav** [comment]
my code is not working n chrome even if i have included  web-animations.min.js in my polyfill.ts file

**Comment by zishanj** [comment]
It should be included in your HTML header file to load like a normal js file.
-- 
Sent from my Android phone. Please excuse my brevity.On 6/30/17, 1:01 PM bankotigaurav <notifications@github.com> wrote:
my code is not working n chrome even if i have included  web-animations.min.js in my polyfill.ts file

**Comment by zishanj** [comment]
Also check in ur chrome browser developer tools that this file is loaded in the beginning.
-- 
Sent from my Android phone. Please excuse my brevity.On 6/30/17, 1:01 PM bankotigaurav <notifications@github.com> wrote:
my code is not working n chrome even if i have included  web-animations.min.js in my polyfill.ts file

**Comment by bankotigaurav** [comment]
Yes. i have seen that file is loading in the beginning as i have written it in index.html. but animation still not working.
