### ISSUE TITLE
/node_modules/@angular/animations/browser"' has no exported member 'ɵDomAnimationEngine'.

### ISSUE THREAD

**Issue by ahmedhossameldin** [angular/angular#17804]
## I'm submitting a ...

<pre><code>
[x] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 

Ionic Framework: 3.1.1
Ionic App Scripts: 1.3.6
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 7.9.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.10

}
export declare function instantiateSupportedAnimationDriver(): NoopAnimationDriver;
export declare function instantiateDefaultStyleNormalizer(): WebAnimationsStyleNormalizer;

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/17400

**Comment by ahmedhossameldin** [comment]
i figured it out the issue was that  "@angular/animations": "^4.0.2", is upgradable but the "@angular/core": "4.0.2", is not so i just removed the ^ from the "@angular/animations": "4.0.2"

"dependencies": {
        "@angular/animations": "4.0.2",
        "@angular/common": "4.0.2",
        "@angular/compiler": "4.0.2",
        "@angular/compiler-cli": "4.0.2",
        "@angular/core": "4.0.2",
        "@angular/forms": "4.0.2",
        "@angular/http": "4.0.2",
