### ISSUE TITLE
two way binding for query params

### ISSUE THREAD

**Issue by colorpump** [angular/angular#17809]
### 1. route changes -> queryParams get re-read

**works like that**

```typescript
import { ActivatedRoute, Params, Router }   from '@angular/router';

export class SearchComponent implements OnInit
{
  someProperty : string;

  constructor(
    private route: ActivatedRoute
  ) { }

  this.route.queryParams.subscribe( params => {
    this.someProperty = params['someQueryParam'];
  }
```

If I update the URL, this.someProperty gets updated.

### 2. variable value changes, the URL should get updated

**no idea, how this can be done**

In the example above, I want the query parameter 'someQueryParam' to get updated when I change this.someProperty.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by IgorMinar** [comment]
@colorpump please use setters to intercept the update and use the router apis to update the query params as needed. We don't provide an automated way to do this as it could cause data flow issues in the application if done unintentionally.
