### ISSUE TITLE
aio: lifecycle hooks page has a bad image position

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#17808]
![](https://puu.sh/wwlIC/5a517c709b.png)

As an extra, the live example link is too far away from the top.

**Comment by kapunahelewong** [comment]
See also #17298

**Comment by jenniferfell** [comment]
It looks like this was resolved. That image has been removed. All remaining images seem appropriately placed. The live example link is in a clear section about examples. 

If this is not resolved to your satisfaction, please reopen or submit a new issue. Thanks for your feedback!
