### ISSUE TITLE
event.preventDefault() sporadic behaviour

### ISSUE THREAD

**Issue by misterti** [angular/angular#17813]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

HostListener on app component provides event, for example mousedown. When false is returned, or even stopPropagation or preventDefault, event is prevented only the first time. Once true is returned from event handler, the next time false is returned, event will not be prevented, instead default behavior is executed every time.

## Expected behavior

Every time event is prevented with false or respective functions, default behavior should not occur.

## Minimal reproduction of the problem with instructions

<pre>
<code>

import { Injectable, HostListener } from '@angular/core';
import { Component, ViewChild, ForwardRefFn, forwardRef, Inject } from '@angular/core';
import { Nav, Platform } from 'ionic-angular';
import { NavController, NavParams } from 'ionic-angular';

export class MyApp {
  @ViewChild(Nav) nav: NavController;
  @HostListener('mousedown', ['$event'])
  handleEvent(event)
  {
	if (this.sharedService.editorActive)
	{
		event.stopPropagation();
//			event.preventDefault();
		return false;
	}
	return true;
  }
...
</code>
</pre>
With an UI toggle, i can control this.sharedService.editorActive, which upon true, returns false from event handler to prevent default behavior

## What is the motivation / use case for changing the behavior?

Use case is preventing an app from navigating, instead use it to select individual elements on the page, like an editor of somekind.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 54
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.4 
- Platform: 
Windows
Others:

</code></pre>

**Comment by chuckjaz** [comment]
@misterti I am not sure I understand what you are expecting to happen. 

Can you produce a plunkr and steps to demonstrate the issue?

**Comment by pkozlowski-opensource** [comment]
I was trying to reproduce here: http://plnkr.co/edit/K0kzQKaoQqcqSdUpR665?p=preview but could not.

At the same time it is not clear _at all_ what the original scenario so we can't confirm if anything fishy is going on here or not. 

I'm going to close this issue as it is not possible to take it any further based on the info provided. If you still believe that there is a bug please open a new issue with a plunker.
