### ISSUE TITLE
Getting 'ERROR not implemented' when platform-webworker and http used together

### ISSUE THREAD

**Issue by varghesep** [angular/angular#17812]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Receiving the error message *ERROR not implemented* from ```WorkerDomAdapter.prototype.getCookie = function (name) { throw 'not implemented'; };``` in ```platform-webworker.umd.js```

## Expected behavior

The API should return the results.

## Minimal reproduction of the problem with instructions

1. Create a web-worker by following [example](https://stackoverflow.com/questions/40814324/angular-2-web-worker-ui-not-running/40820019#40820019).
2. Create a service and inject into the app component. Use the following code:

```
import { Injectable } from '@angular/core';
import { Headers, Http } from '@angular/http';
import { Observable } from 'rxjs/Observable';

@Injectable()
export class ProductListService 
{
    private headers = new Headers(
        {
            'Content-Type': 'application/json'
        });

    private API_PATH: string = 'http://localhost:5000/api/products';

    constructor(private http: Http)
    {
    }

    getProducts(queryTitle: string, pageNumber: number, pageSize: number): Observable<any>
    {
        return this.http.get(`${this.API_PATH}?pageNumber=${pageNumber}&pageSize=${pageSize}`)
            .map(res => res.json());
    }
}
```

3. Call the ```getProducts``` in the app component.
4. You will see the *ERROR not implemented* error message in the browser.

More details can be found in this [stackoverflow question](https://stackoverflow.com/questions/44780814/error-not-implemented-with-angular4-web-worker).

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 
Windows, .NET Core, SystemJS, Angular4, Typescript
Others:

</code></pre>

**Comment by varghesep** [comment]
This is the same [issue ](https://stackoverflow.com/questions/40585097/angular-2-webworkers-http-uncaught-in-promise-not-implemented)reported by someone else in StackOverflow.

**Comment by hotspurs** [comment]
Same with SSR!

Also, i'm unable to change providers to NoXSRFStrategy (with empty configure method)

**Comment by alxhub** [comment]
Closing as this is obsolete (it concerns `@angular/http` which has been removed in favor of `@angular/common/http`).
