### ISSUE TITLE
AOT genDir compiler option can't be set to ../aot

### ISSUE THREAD

**Issue by snewell92** [angular/angular#17814]
## I'm submitting a ...
```
[x] Bug report
```

## Current behavior
Setting AOT compiler's `genDir` option to `../aot` makes the compiler break.

```
Error at proj/public/aot/app/app.component.ngfactory.ts:10:21:
  Cannot find module './app.component'.
Error at proj/public/aot/app/app.module.ngfactory.ts:10:21:
  Cannot find module './app.module'.      
Error at proj/public/aot/app/app.module.ngfactory.ts:11:21:
  Cannot find module './app.component'.   
```

## Expected behavior
Should be able to compile and resolve the paths to app code correctly, ie all `./*` paths should be mapped to `../{dirOfTsconfig}/`. The directory of the tsconfig can be another option if need be.

## Minimal reproduction of the problem with instructions

[Here's a gist of the relevant code](https://gist.github.com/snewell92/29fb5a94379f1fd6ea33c0f077437148)

```
$ mkdir aot-repro && cd aot-repro && npm init
$ npm install @angular/animations @angular/common @angular/compiler \
  @angular/compiler-cli @angular/core @angular/forms @angular/http \
  @angular/platform-browser @angular/platform-browser-dynamic \
  @angular/platform-server @types/node rxjs typescript zone.js 
$ mkdir -p public/src/app
$ mkdir public/aot
$ mkdir public/dist
$ cd public/src
```

Now from the [aot documentation](https://angular.io/guide/aot-compiler#compile) create a `public/src/main-jit.ts` and a `public/src/main-aot.ts` file. Then, in the `app` folder create a minimal module and  a minimal component for the test app to compile.

Now create two `tsconfig.json` files in `public/src`, one for aot and one for jit just like the docs specify. In both of them make sure to put set the `skipLibCheck: true` compilerOption so you don't run into the rxjs error. **jit compile should output to `../dist` and the aot compile should have its `genDir` set to `../aot`**.

Now in package.json, add the scripts to compiler jit, and compile aot, something like `build-jit` and `build-aot`.

```
$ npm run build-jit
```

should be fine, but

```
$ npm run build-aot
```

will error out.

## Use Case

Full stack (ie multi project) project layout. It's typical to have front end code in a `./public/` folder, and to have several directories in the `public` that the main server application in `./src/` serves. Ideally, rollup bundles for my project would be available to browser script tags via `src=bundles/....js` - with that in mind, it makes sense to put the `aot` output as a sibling of the bundles folder.

```
./
 |-public/
 |   |-aot/
 |   |-dist/
 |   |-src/ <-- all client code
 |      |-app/
 |-src/
    | ... all server code
```

## Environment

```
Angular version: 4.2.4 
Node version: 8.0.0
Platform: Windows
Typescript: 2.4.1
```

## Related issues

#13008

**Comment by snewell92** [comment]
If resolving the path names isn't gonna work, another solution would be to document the limitations of `genDir` in the [aforementioned aot docs](https://angular.io/guide/aot-compiler#compile-with-aot).

As the docs are now, as an end user I expected `genDir` to allow arbitrary placement of `ngc`'s output.

**Comment by JoostK** [comment]
The `genDir` option has bot been around since Angular 5, so closing as obsolete.
