### ISSUE TITLE
Documentation on change detection before / after view composition

### ISSUE THREAD

**Issue by bathejasumeet** [angular/angular#17815]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

**angular forbids changes to the view once data has been composed**
- can you please elaborate why and how this actually works ? Is this also related to testing of template driven forms since directives create the Form Controls/Groups asynchronously?

Others:

Please refer to this stackoverflow question 

 https://stackoverflow.com/questions/44795873/ngzones-and-modified-after-checked-error-in-angular-4

**Comment by fredrik-lundin** [comment]
Documentation [here](https://angular.io/guide/lifecycle-hooks#abide-by-the-unidirectional-data-flow-rule) and [here](https://angular.io/guide/lifecycle-hooks#no-unidirectional-flow-worries-with-aftercontent) is not really giving a good enough explanation (for me at least) or the actual purpose of the behavior.

Would indeed be nice to know more about the reasoning around it.

**Comment by atscott** [comment]
This should be covered in the main tracking issue for documenting change detection #33731
