### ISSUE TITLE
How to retrieve few records initially from the service and then rest of all

### ISSUE THREAD

**Issue by vibingopal** [angular/angular#17821]
Hi Team,

Could you please let me know how to retrieve first few records from the service and then the rest of all records.
I have  a service with datatable where it loads all records into the datatable. Now the service taking long time to retrieve all the records.So for that i need few records retrieved first and then the remaining records. 

Below is my code which calls the service 

this.http.post(serviceURL,request, { headers: headers})
      .map((res: Response) => (res.json()))
      .catch(this.handleError);

Let me know how to implement it using Observables. Thanks

**Comment by gonzofish** [comment]
You should go to [StackOverflow](https://stackoverflow.com/questions/tagged/angular) or [Gitter](https://gitter.im/angular/angular) for this. The GitHub issues isn't the right place to ask this sort of question.

Good luck finding an answer!

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
