### ISSUE TITLE
Change Detection fails to update host bindings

### ISSUE THREAD

**Issue by wizarrc** [angular/angular#17828]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Update a component's host bindings and call `cdRef.detectChanges()`. Host bindings remain the same.

## Expected behavior

Update a component's host bindings and call `cdRef.detectChanges()`. Host bindings are updated.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/4Wvtxsn6wrINf5YLrDOj?p=preview

Notice how the text is changed to match the background color. After an untracked event changes the properties again and a manual call to the change detector is processed, the text is changed, but the background color remains the same.

## What is the motivation / use case for changing the behavior?

The developer expects that all references/bindings inside it's own component are updated during a manual detect changes. The point of a manual detect changes is for managing performance of the component; and by updating the host bindings in the parent component during the `Services.updateRenderer` call, it must also process all other checks for the parent component as well.

**Note:** Injecting `@SkipSelf() cdRef: ChangeDetectorRef` is a workaround for child components only but can be a performance hit. Also, it's impossible to do so on the root component because: "No provider for ChangeDetectorRef" error is displayed.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 15
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by FDIM** [comment]
Looks like workaround with `@SkipSelf` have stopped working with IVY
