### ISSUE TITLE
Enable Partial Change Detection After Event

### ISSUE THREAD

**Issue by wizarrc** [angular/angular#17829]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Event is fired on deeply nested child, event propagates to middle nested child. Full change detection is triggered afterwards.

## Expected behavior

Event is fired on deeply nested child, event propagates to middle nested child. Partial change detection is triggered afterwards starting from middle nested child, the parent-most component the event was handled on.

# Example:

## _User Code:_

**RootComponent:**  root component
**ChildAComponent:** child component of RootComponent
**ChildBComponent:** child component of RootComponent
...
**ChildZComponent:** child component of RootComponent

## _Library Code:_

**ChildA1Component:** child component of ChildAComponent

ChildA1Component fires scroll event, handles event, and propagates additional events to unknown level of parent components. If ChildAComponent doesn't fire off event to RootComponent, it would be better performant to trigger change detection at the ChildAComponent level and not at the RootComponent level as it has many child components to perform change detection on.

I propose two changes:

1. At the component level, enable opt-in tracing, to be able to query the parent-most invalidated component's ChangeDetectorRef. The tracing can be enabled via the component factory's event handler.
2. At the component level, enable opt-in smart change detection, where it automatically traces all events emitted on that component, and instead of triggering a full change detection, it triggers a partial one instead based on tracing data.

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?

Change detection can be expensive for performance critical events such as virtual scrolling, and handling of the events should be contained to only the components where the side-effects occurred. This can be an opt-in behavior and thus be a non-breaking change. The problem with relying only on manual change detection for performance critical events is it first requires to be run outside of the NgZone to avoid full change detection. If the event propagates past the library component outside of your control, but you still want to perform a change detection after all events are handled, there is no way to query where the parent-most component is invalidated, and call their change detector. Additionally, since the event must be called outside of the NgZone, another zone must be implemented to handle their zone-patched callbacks such as `setTimeout`.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 15
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Toxicable** [comment]
I don't see how this behavior cannot be solved with OnPush? Simply make everything OnPush and if the scroll dosen't emit an event which makes a ref change to the @Input's of the other components then CD will not be run on them.
Otherwise you could also run the scroll events outside of Angular's Zone, bringing them into the Zone when you need Angular to run CD

**Comment by wizarrc** [comment]
@Toxicable Two problems with OnPush:

1. The library author can't force the user that wants to use your component to use OnPush, but still wants their code to perform great in any configuration.
2. Change detection still occurs globally with OnPush, it does benefit from several short-circuiting efforts, but in my example, a big user component that is a parent that handled the event still needs to be entirely checked for a performance sensitive scroll event, where it would otherwise be bypassed. The other child components might be bypassed, but the parent component itself might be very large. The user of the code may not care if it's not that performant for their own controls that happen to share with the library component but they do care that their library component scrolls buttery smooth, especially in older browsers where DOM manipulation is expensive and every cycle counts.

**Comment by wizarrc** [comment]
@Toxicable This feature request is really for library authors to squeeze the most performance out of their code for any hostile user environment that they can't control. Anyone using their library and listens to their events won't have to worry about the details, and won't have to know about OnPush and still get high fps scrolling. Now if they build their own components and they perform poorly, at that point, they can choose to learn more advanced platform features, but not because the library author requires them to in order to use it.

**Comment by wizarrc** [comment]
> Otherwise you could also run the scroll events outside of Angular's Zone, bringing them into the Zone when you need Angular to run CD

@Toxicable The problem with running the scroll event outside of Angular's Zone is that you, as a library author, don't know if the changes they made, side-effects, are needed to get refreshed, nor should you require that they not make template invalidating changes, you need to check for the changes, but you want to be smart about the checking, and only check as far back as the side-effects go back. Now if they trigger their own event, a quick fix like getting their parent component using `SkipSelf() cdRef: ChangeDetector` injected in your component's constructor won't do it any good, because that parent's component also needs to be invalidated and scanned for changes, and so on, and so on, all the way down their path. Now that might not be the best approach for them to make, but as a library author, it's not our job to require that they code smart themselves, but instead, work as good as possible given bad conditions.
