### ISSUE TITLE
[feature] Better class binding syntax

### ISSUE THREAD

**Issue by rulrok** [angular/angular#17827]
## I'm submitting a ...

<pre><code>
[ x ] Feature request
</code></pre>

## Current behavior

To bind classes on elements, we can use:

```html
<a class="btn" [class.btn-link]="someCondition" href="#" ></a>
```
or slightly better for some scenarios:

```html
<a class="btn" [ngClass]="{'btn-link' : someCondition}" href="#" ></a>
```

## Expected behavior

Having a more looking-pleasing binding exclusive for classes as it is common work.
For that, I thought on a special syntax with single `{ }` braces (_which I believe is not used currently and assume that doesn't conflict with anything_).

```html
<a class="btn" {btn-link}="someCondition" href="#" ></a>

<!-- the possibility of many classes on one fell swoop -->
<a {btn btn-link yet-another-class}="someCondition" href="#" ></a>
```
### Alternative syntaxes (maybe?)

```html
<a class="btn" |btn-link|="someCondition" href="#" ></a>
<a |btn btn-link yet-another-class|="someCondition" href="#" ></a>
```
```html
<a class="btn" %btn-link%="someCondition" href="#" ></a>
<a %btn btn-link yet-another-class%="someCondition" href="#" ></a>
```
## What is the motivation / use case for changing the behavior?

I find it very cumbersome the way we have to write class binding with angular. 

It pollutes the element with `[class.className]="condition"` which (for me) does not instantaneously pop out as being a class binding compared to `{className} ="condition"`.

I suggest it deserves an special syntax as I can see it being very productive
whilst working alongside with css frameworks.

**Comment by Toxicable** [comment]
The issue I have with that is that `class` is a property of a HTMLElement, therefore it's treated the same as any other property on a HTMLElement. Giving this one specific property it's own specific micro-syntax could cause confusion since it'll be the only property that has it's own syntax which will be inconsistent with the rest of property bindings.

Also, in the situation where we do go ahead with this, what's the argument for now allowing other properties having their own micro-syntax aswell?

**Comment by rulrok** [comment]
Just for the record and precision of the discussion, `class` seems to be a property of `Element` which `HTMLElement` inherits from. 
[Element](https://developer.mozilla.org/en-US/docs/Web/API/Element)
[HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement)

Another observation: `onblur` is defined as a [property](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onblur) which returns the event handler. Thus, technically, should I be able to use `[onblur]="function"` instead of `(blur)="function"`?

> Also, in the situation where we do go ahead with this, what's the argument for now allowing other properties having their own micro-syntax aswell?

For others I would say they are simply not worth it. What I'm trying is to promote `class` to a special level because of its unique multi-valued nature.

property | reason why don't need special syntax
----------|------------
id           | we can already use `id="{{ something }}"` which is simple and effective enough; also, only one name should be used; `class` allows for a list of values.
src          | again, `src="{{ src }}"` if effective enough for something that allows for one value only
style       | it should not be used too often anyway, thus discouraging its usage (which is good)
any other property | They will probably fall into the same reason for `id` or `src`: attributes which allow for single values, different from `class` which allows for a list of values.

I'd say `class` is a more dynamical property than the others can be; also, it allows for a list of classes. I believe that `<a {btn btn-primary}="condition"></a>` would simplify a lot inputting a list of classes based on some condition. Again, taking advantage when building Angular apps together with proper css frameworks.

another advantageous scenario: different sets of classes easily done with different conditions

```html
<a
{btn btn-primary}="conditionA"
{active}="conditionB"
{yet-another-class}="conditionC"
href="#">link</a>
```

In that case they would be additive; supposing `conditionA`, `conditionB`, and `conditionC` all being truthy, we would have:

```html
<a class="btn btn-primary active yet-another-class" href="#">link</a>
```

The major reason for me is avoiding cluttering on the html by trying to simplify the current syntaxes available for class binding.

**Comment by vicb** [comment]
We are -1 on adding micro-syntax.

You can solve this by pre-processing your HTML either outside of Angular or by provinding a custom HtmlParser.
