### ISSUE TITLE
docs(aio): Template reference var scope guidance doesn't match framework's actual behaviour

### ISSUE THREAD

**Issue by alexzuza** [angular/angular#17826]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

According to the docs: https://angular.io/guide/template-syntax#template-reference-variables--var-

> You can refer to a template reference variable anywhere in the template

However, it appears as though **a template reference variable can't be accessed outside of an embedded view**:

    <h2 *ngIf="true" myHighlight #tRefVar="myHighlight">tRefVar is {{tRefVar.foo}}</h2>
    <div>tRefVar is {{tRefVar?.foo}}</div>

If this is expected behaviour, the docs should be updated to reflect that. 

## Expected behavior

Documentation should reflects the real behaviour

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/5jBMU0QEShnbm6quCRa5?p=preview

As you can see in plunker above `tRefVar` template reference variable is always `undefined`

See also https://stackoverflow.com/questions/44811132/how-do-i-combine-a-template-reference-variable-with-ngif/44812573#44812573

## What is the motivation / use case for changing the behavior?

I think it should be more transparent how to use it for users who deal with template reference variable

## Please tell us about your environment
<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version 58
</code></pre>

**Comment by jenniferfell** [comment]
@kapunahelewong Maybe this is already resolved (or will be) in your template syntax work?

**Comment by kapunahelewong** [comment]
@alexzuza Thanks for pointing this out. I've added this to the Template Syntax rewrite and will be sure to specify this point whenever I come across it in the documentation. If you notice this elsewhere before I do, feel free to tag me so I can fix.

**Comment by kapunahelewong** [comment]
Thanks for this @alexzuza. Since the PR merged, Iʻll close this. If you still have outstanding questions/concerns, feel free to reopen and tag me. :)
