### ISSUE TITLE
Error: No Provider for Renderer 2! 

### ISSUE THREAD

**Issue by Hisairnessag3** [angular/angular#17824]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am doing what I believe to be recommended service injection, with Renderer2 onto the component. I get no errors in my compiler but this error in my console on click of a button in the said component.(See stackoverflow post)

## Expected behavior

Refactor my service so it works with migration.

## Minimal reproduction of the problem with instructions

https://stackoverflow.com/questions/44812394/error-no-provider-for-renderer2-angular-v-4-1-3

## What is the motivation / use case for changing the behavior?

Similar recommended practice with original Renderer could be injected like shown.
## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

4.1.3, Still seems to be a problem on latest version.
Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 
Node: 7.10.0
Mac OS Sierra 10.12.1

Others:

</code></pre>

**Comment by Toxicable** [comment]
Could you please provide a minimal reproduction, here's a template to get you started: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by Hisairnessag3** [comment]
Is just deploying the app to qa, and allowing you to reproduce it live advisable? Or would you like me to try and create a sample app in which I can reproduce the issue.

Let me know about that and I will refactor that chunk of code to isolate the problem. Sorry about the delay.

**Comment by ericmartinezr** [comment]
This is simple to reproduce http://plnkr.co/edit/yAg7jT7xhfzNHYsd5VAs?p=preview, this issue has been there for a long time, people have tried to inject all kind of things into services getting the error you see. There was at some time an attempt to allow these things to be injected into services but it ended in nothing sadly :( https://github.com/angular/angular/pull/9393

**Comment by Hisairnessag3** [comment]
@ericmartinezr Thank you for your answer. What is current best practice to do this sort of thing in angular v4+?

**Comment by ericmartinezr** [comment]
@Hisairnessag3 I can only think of passing a reference of the Renderer2 to the service. Something like this

```
@Injectable()
class MyService {
  svcRenderer: Renderer;
}
// ...
class App {
  name:string;
  constructor(svc: MyService, renderer: Renderer2) {
      svc.svcRenderer = renderer;
  }
}
```
That's the only thing that I can come up with (not saying at all this is *the best practice*). I would like to know Pawel's answer too about his last comment on that issue https://github.com/angular/angular/pull/9393#issuecomment-228091311

It would be nice to retake the issue I guess.

cc @pkozlowski-opensource any thought about it? :P

**Comment by Hisairnessag3** [comment]
What is Renderer on the service?  This wouldn't compile? how does the service know what 'Renderer' is? 

Thanks for your help again, happy 4th.

**Comment by ericmartinezr** [comment]
It's just for typings, it shouldn't affect the compilation.

```
import {Injectable, Renderer2} from '@angular/core';

@Injectable()
class MyService {
  svcRenderer: Renderer2;
}
```
PS: It is Renderer2, I forgot the 2 :P

**Comment by Hisairnessag3** [comment]
Still getting the error with this code:


`import {Location} from "@angular/common";
import {Component, Injectable, Renderer2, Inject} from "@angular/core";
import {SerieService} from "../shared/services/serie.service";
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { CategoryService } from "../shared/services/category.service";
import {Router, ActivatedRoute, RouterModule, NavigationEnd} from "@angular/router";

import {Http, HttpModule} from "@angular/http";
import {PageviewService} from "../shared/services/pageview.service";
import {Title, DOCUMENT} from '@angular/platform-browser';
import {SeoService} from '../shared/services/seo.service';

@Injectable()
export class Service {
 svcRenderer: Renderer2;
private metaDescription: HTMLElement;

private headElement: HTMLElement;

private robots: HTMLElement;



constructor(@Inject(DOCUMENT) private document: any,  private titleService: Title){
this.headElement = this.document.head;
this.metaDescription = this.getOrCreateMetaElement('description');

}

 public setMetaDescription(description: string) {
  this.svcRenderer.setAttribute(this.metaDescription, 'content', description)
 }

 public setMetaRobots(robots: string) {
  this.svcRenderer.setAttribute(this.robots, 'content', robots);
 }

 public setTitle(newTitle: string) {
  this.titleService.setTitle(newTitle + ' | Stareable');
 }

 private getOrCreateMetaElement(name: string): HTMLElement {
     let el: HTMLElement;
     el = this.document.querySelector('meta[name=' + name + ']');
     if (el === null) {
         el = this.document.setAttribute('meta');
         this.headElement.appendChild(el);
     }
     return el;
   }

 }




 @Component({
   inputs: ['category'],
   templateUrl: './categories.component.html',
   styleUrls: ['./categories.component.scss'],
   providers: [ Service ]
 })

export class CategoriesComponent {

  public category: string;
  public seriesList: any;
  public message: string;
  public loading: boolean;
  public errorMessage: string;

  private slug:string;

 constructor (
   private renderer: Renderer2,
   private titleService: Title,
   private svc: Service,
   private _router: Router,
   private _activatedRoute: ActivatedRoute,
   private _categoryService: CategoryService,
   private _seriesService: SerieService,
   private _pageviewService: PageviewService,
   private location: Location,
   private _httpService: Http,
   private seoService: SeoService
  ) {
    svc.svcRenderer = renderer;
   this._router.events.subscribe((event) => {
    if (event instanceof NavigationEnd){
        //TODO: FIX TO RECOGNIZE PREVIOUS ROUTE -- THIS WILL CAUSE DUPLICATE REQUESTING URL
        let slug = this._activatedRoute.snapshot.params['slug'];
        this.slug = slug;
        this.category = this._activatedRoute.snapshot.params['slug'];
        this.getSeriesList(slug, null);
     }
  })
}

ngOnInit(){
  let slug = this._activatedRoute.snapshot.params['slug'];
  this.loading = true;
  this.category = this._activatedRoute.snapshot.params['slug'];
  this.getSeriesList(slug,"title");
  this.svc.setTitle(slug);
  this.svc.setMetaDescription(slug);
  this.svc.setMetaRobots('Index, Follow');


 this._pageviewService.addPageview(
 this.location.path(),"CATEGORY",slug,null)
    .subscribe(res => {},err => {});
}`

Let me know if I am missing something stupid. It would be cool to be able to just inject the service with renderer, so I'll defintely stay tuned into developments on that.

**Comment by ericmartinezr** [comment]
@Hisairnessag3 your plnkr is empty, you have to fork it, make it work with your code and then save it.

**Comment by Hisairnessag3** [comment]
By working, do you mean compiling? The reason I ask this is because I get the error on click. I suggested earlier deploying the project to qa, which is reproducible(the error) with this code. That seems to be the easiest solution, no?

**Comment by ericmartinezr** [comment]
@Hisairnessag3 sure, if you can provide a minimal reproduction of the issue it would be even better, but do whatever is the best for you.

**Comment by Hisairnessag3** [comment]
Thanks, I have it deployed at https://backend-dot-qa-stareable.appspot.com. The code is here: https://plnkr.co/edit/b54qZ6zUmPQ3VXogkWXm?p=info.

To reproduce just open your console and click on any of the category buttons at the top.

**Comment by Hisairnessag3** [comment]
Did you have a chance to peek at this? I will post in the gitter aswell.

**Comment by ericmartinezr** [comment]
I did look at it right now,  but I don't see anything related to your issue. I see the error in your webpage, but again, I can't see your code. When you have something reproducible and runnable please go to gitter and post it there 👍

**Comment by Dok11** [comment]
As I can see Renderer2 don't work in services and work in components

**Comment by huncode** [comment]
@ericcarraway I don't know is it a right way to access renderer from service or not... but reading ts https://github.com/angular/angular/blob/5.1.1/packages/core/src/render/api.ts#L142-L190 (version 4.x as well) I've learned to use `RendererFactory2` to get `Renderer2` instance inside the Service.
```ts
class MyService {
  private renderer: Renderer2;
  
  constructor(rendererFactory: RendererFactory2) {
    this.renderer = rendererFactory.createRenderer();
  }
}
```

http://plnkr.co/edit/g16Txn1Y7zejj9xaYttB?p=preview

**Comment by willyboy** [comment]
@huncode That doesn't work as createRenderer requires two arguments; host element and type. Which also explains why it can only be injected into a component, not a service.

**Comment by trotyl** [comment]
@willyboy `rendererFactory.createRenderer(null, null)` would help, if no (concrete) parameters passed, it will just return the default renderer without create a new one.

**Comment by willyboy** [comment]
@trotyl good to know! Thanks!

**Comment by waterplea** [comment]
@trotyl thanks for a great tip! Created a token for it so it could be reused easily:

```
export const DEFAULT_RENDERER = new InjectionToken<Renderer2>(
    'A Renderer2 for global services',
    {
        factory: () => inject(RendererFactory2).createRenderer(null, null),
    },
);
```

**Comment by AndrewKushnir** [comment]
Closing this ticket based on https://github.com/angular/angular/pull/22248#issuecomment-729217323. Thank you.
