### ISSUE TITLE
Distinguish CoreModule from AppModule or drop it

### ISSUE THREAD

**Issue by dancancro** [angular/angular#17825]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The distinction between the roles of [AppModule](https://angular.io/guide/ngmodule-faq#should-i-add-application-wide-providers-to-the-root-appmodule-or-the-root-appcomponent) and [CoreModule](https://angular.io/guide/ngmodule-faq#coremodule) is unclear.

## What is the motivation / use case for changing the behavior?

If the roles are identical - provision of app-wide singletons - then there ought not be two of these and CoreModule should be eliminated. It's just confusing. If the roles are different, the distinction
should be made perfectly clear. From my cursory survey on gitter, it seems that CoreModule
serves only to keep AppModule from getting too big, but this purpose is not at all stated in the Angular docs. If this is in fact its intended and only unique purpose, then it should be called something like "KeepAppModuleFromGettingTooBigModule". "CoreModule" implies that its constituent classes serve a core role that is different from the role of those in the AppModule.

1) It is confusing to have two things that seemingly serve the same purpose and have no discernible advantages over each other. 
2) [Many](https://github.com/jhipster/jhipster-sample-app-ng2/tree/master/src/main/webapp/app) [respectable](https://github.com/akveo/ng2-admin/tree/master/src/app) [example](https://github.com/born2net/Angular-kitchen-sink/tree/master/src/app) [applications](https://github.com/qdouble/angular-webpack2-starter/tree/master/src/app) [have](https://github.com/AngularClass/angular-starter/tree/master/src/app) [no](https://github.com/gothinkster/angular-realworld-example-app) [CoreModule](https://github.com/mgechev/angular-seed/issues/1957#issuecomment-306550924).

**Comment by PoiScript** [comment]
there seem to be two definitions for `CoreModule` now..
[one](https://angular.io/guide/ngmodule-faq#coremodule) is:

> Consider making CoreModule a pure services module with no declarations.

> This page sample departs from that advice by declaring and exporting two components that are only used within the root AppComponent declared by AppModule. Someone following this guideline strictly would have declared these components in the AppModule instead.

[the other one](https://angular.io/guide/styleguide#core-feature-module) is:

> Do gather application-wide, single use components in the CoreModule. Import it once (in the AppModule) when the app starts and never import it anywhere else. (e.g. NavComponent and SpinnerComponent).

**Comment by kapunahelewong** [comment]
Thanks for this @dancancro. We've been working on re-thinking the presentation of the NgModules related documentation and the `CoreModule` topic confused me. The PR is big, so see the [Singleton Services](https://github.com/angular/angular/pull/20306/files#diff-c7b9c02ae1589aa70e42ec141c108131) doc in progress.

If you have ideas on clarifying further, please feel free to comment [#20306](https://github.com/angular/angular/pull/20306).

**Comment by frederikprijck** [comment]
I've always looked at CoreModule vs SharedModule from the point of DI and LazyLoading, where a CoreModule only contains providers and is imported into the AppModule.

SharedModule on the other hand contains anything but providers (unless there's certain providers which should not be singleton in the case of LazyLoading).

In most libraries (aswell as the Angular Router) I see them being implemented as `forRoot` and `forChild` modules. (where forRoot includes the providers in the AppModule (which sounds abit like the CoreModule definition), and forChild acts as how SharedModule is defined in the FAQ.

Looking at this, I'm not sure if there's a need for an explicit Core and SharedModule, in practice I often see multiple modules which either act as a Core- (providers for the root) or SharedModule (declarations, pipes and none-singleton providers).

Don't get me wrong, I do think the idea behind both CoreModule and SharedModule is important, not sure if there's to be only one of them (nor do they have to be named Core or SharedModule)

**Comment by jenniferfell** [comment]
filename=https://angular.io/guide/styleguide
https://angular.io/guide/singleton-services
https://angular.io/guide/ngmodule-faq#coremodule

**Comment by jenniferfell** [comment]
Current text makes a distinction/definition here: 
"CoreModule is a conventional name for an NgModule with providers for the singleton services you load when the application starts."
https://angular.io/guide/ngmodule-faq#coremodule

I didn't review all text around other uses of CoreModule to make sure we're clear in those instances about it being a convention, but some were clear about this. Issue possibly resolved when we merged ngModules update earlier this year.

Keeping open to double-check.

**Comment by frederikprijck** [comment]
Fwiw the CoreModule and ShareModule definition used on AIO (https://angular.io/guide/ngmodule-faq#coremodule) are clear to me.

However, it can still be a bit hard to understand for people not familiar with the reasoning behind it as you need to collect content from a few places before getting the whole picture (singleton services, forRoot, forChild, DI system and lazy loading). But I guess this is due to the fact that it's not something easy.

Afaik both the CoreModule and SharedModule come from a DI perspective in combination with LazyLoading. I currently see quiet some developers blindly using the CoreModule/SharedModule approach without knowing why.

I agree, what I'm talking about is linked at the AIO page regarding CoreModule/SharedModule, but it's not that easy to get the full picture without collecting bits and pieces from a few places.

**Comment by DeborahK** [comment]
Consider reviewing this topic for v6. Now with the `providedIn` feature of the service itself, it seems that the CoreModule is much less useful than prior to v6.

Consider removing the discussion and recommendation of a CoreModule entirely, especially from the Style Guide, and instead recommend using `providedIn`.

**Comment by Dali2579** [comment]
> Consider reviewing this topic for v6. Now with the `providedIn` feature of the service itself, it seems that the CoreModule is much less useful than prior to v6.
> 
> Consider removing the discussion and recommendation of a CoreModule entirely, especially from the Style Guide, and instead recommend using `providedIn`.

I was in the way to ask you this question in your PS course. happy to see your answer here.

**Comment by kapunahelewong** [comment]
Remove CoreModule PR has been merged. Closing this issue. @dancancro if you still have any questions or want to share feedback, please feel free to reopen and tag me.
