### ISSUE TITLE
https://angular.io/guide/testing#the-first-karma-test make it easier to run ng test from quickstart app

### ISSUE THREAD

**Issue by jgfet** [angular/angular#17820]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The setup process if you've taken the quick start project and are starting to try and do testing is extremely painful. 
I've noted my findings just to be able to get ng test to work:
https://stackoverflow.com/a/44810864/495157
plus karma using LTS version of node is a headache too.
https://github.com/angular/angular-cli/issues/3554#issuecomment-311488799

## Expected behavior

re introduce ng init perhaps.. 

## What is the motivation / use case for changing the behavior?

make it so it's easy to convert an npm based project to a ng one, so karma tests can be run on quickstart. That way a user can at least follow along with the website instructions...

## Please tell us about your environment
I can run node in one of two way via nvm but currently am using 6.11.0 in order to facilitate karma
@angular/cli: 1.1.3
node: 6.11.0
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4
/opt/AngularProjects/quickstart>

Angular version: @angular/core@4.2.4 

Browser:
- [x ] Chrome (desktop) version 59.0.3071.115 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.0
- Platform: Mac

Others:

</code></pre>

**Comment by gonzofish** [comment]
Are saying there should be some utility to support converting a non-CLI project to using the CLI?

**Comment by jgfet** [comment]
Yes. It looks like historically there was an **ng init** command.
I think most when learning Angular are used to the ng cli and doing ng test rather than npm test seems more intuitive too.

**Comment by jasonaden** [comment]
This should have now been addressed by changes to the CLI and the documentation on new projects. Please file a new issue if you still have this problem.
