### ISSUE TITLE
aio: roboto font not being installed on machines that don't have it preinstalled

### ISSUE THREAD

**Issue by samirotiv** [angular/angular#17834]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Font is too light and hard to read.

## Expected behavior

Font with a normal weight.

## Minimal reproduction of the problem with instructions
Visit any page, eg. [https://angular.io/guide/ngmodule](https://angular.io/guide/ngmodule)

## What is the motivation / use case for changing the behavior?

Ease of reading and not straining readers' eyes.

## Please tell us about your environment
Chromium, latest. Also cross checked from Firefox/Edge and a few other computers.
<pre><code>

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version XX

**Comment by m98** [comment]
The font used in angular.io is Roboto which is obviously not a problem :sweat_smile:, and font size is 14, font-weight is normal.

The font size and styles looks fine to me

**Comment by tytskyi** [comment]
Do you have browser zoom turned on?

**Comment by samirotiv** [comment]
@Mohammed I was expecting some answer like this. :P Well, I am just
reporting it like a good Samaritan. Up to whoever to decide what to do
about it.

No, I am on the default 100% zoom.

Attaching a screenshot here. It looks very faint from both HiDPI as well as
non HiDPI screens. No idea why. Is the weight Light or something?

[image: Inline image 1]

On Thu, Jun 29, 2017 at 4:31 PM, Oleksandr Tytskyi <notifications@github.com

**Comment by samirotiv** [comment]
Hi,

The problem is that I didn't have the Roboto font installed. I only had Roboto-Light installed on my local machine, and that was the problem. This needs to be fixed so that it gets the Normal & Bold versions from the server if I don't have them installed.

Best,
Samir.

**Comment by gkalpak** [comment]
Wow! 💥 
I would swear we load Roboto. 😕 
Apparently we don't. 😁  
We definitely should! 😇

**Comment by gkalpak** [comment]
This has been fixed in #27250.
