### ISSUE TITLE
No way found to add modules runtime in app module as dependencies. Is it not feasible ?

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#17835]
Hi,

I want to add some module based on some event in my angular application dynamically . Is it feasible in Angular Application ?

Regards
vasuneet

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by IgorMinar** [comment]
you can create new child injectors using a new NgModuleFactory determined at the runtime - this is exactly what the router does.
