### ISSUE TITLE
aio: DI and DI in action has the same h1

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#17839]
That complicates searching for it. Both have the same title so the same result will appear.

**Comment by kapunahelewong** [comment]
The Dependency Injection related titles could use some tech writer attention. They're no longer identical, but could be better.

**Comment by jenniferfell** [comment]
@jbogarthyde started some work on DI editing and titles: https://github.com/angular/angular/pull/21915

**Comment by jenniferfell** [comment]
Page titles are still a problem:

https://angular.io/guide/dependency-injection
Nav title: Angular Dependency Injection
Page title: Angular Dependency Injection

https://angular.io/guide/dependency-injection-in-action
Nav title: DI in Action
Page title: Dependency Injection

PR #21915 will address the titles and some larger organization issues. A smaller PR could be submitted just to address the titles, making the second one into "Dependency injection in action" to match nav and filename.

**Comment by jbogarthyde** [comment]
The DI guide has changed out of all recognition since this was reported.
