### ISSUE TITLE
special characters in the query parameter value in the URL are getting truncated

### ISSUE THREAD

**Issue by manju-reddys** [angular/angular#17830]
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request

</code></pre>

## Current behavior
Special characters in the URL query parameters are getting truncated for example: if I send GET request to `www.google.com/Auth?usename=manju&password=manju#manju$test` the URL that actually goes to the server is `www.google.com/Auth?user=manju&password=manju`

## Expected behavior
Should't truncate the anything in the provided URL

## Minimal reproduction of the problem with instructions

[Reproducible here, Please see the console for the result](https://plnkr.co/edit/woajKo?p=preview)

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [ x] Chrome (desktop) version latest
- [ x] Firefox version latest
- [x ] Edge version latest

**Comment by trotyl** [comment]
It's the expected behavior of XHR or fetch to ignore the fragment part, not specific to Angular. If you're not using fragment, then having it escaped.
[This stackOverflow question](https://stackoverflow.com/questions/13228835/passing-hash-symbol-in-request-parameter-of-url-not-working-in-firefox) may help.

**Comment by m98** [comment]
@manju-reddys  I agree with @trotyl, and if you still believe it's the Angular problem, try to make an XHR request using JavaScript itself, or something like Jquery

**Comment by manju-reddys** [comment]
I agree too, and I wasn't aware of this. Thank you @trotyl for the help link.
