### ISSUE TITLE
enableProdMode, If have any exception, the application will crash (don't re-display data when go to another router)

### ISSUE THREAD

**Issue by Sophia-nguyen** [angular/angular#17833]
Hi all,
I use angular 2.1.2 and I need to customize ErrorHandler.

"AppModule.ts":

```
@Injectable()
class MyErrorHandler implements ErrorHandler {
    handleError(error) {
        console.error("EXCEPTION:", error.message);
        console.error("EXCEPTION:", error.stack);

        setTimeout(() => {
            location.href = "#/error";
            return Observable.of([]);
        });
    }
}
```
or

```
@Injectable()
export class MyErrorHandler {
    private appRef;

    constructor(private injector:Injector) {
        setTimeout(() => this.appRef = injector.get(ApplicationRef));
    }

    handleError(exception) {
        this.appRef.tick();
        console.error('EXCEPTION:', exception);
    }
}
```
When I go to `/about` page and an error occurs. My app will redirect to `/error` page.
Then I go to `/home` or another page. The data of this page don't show on template, just show template without any data.
How can I resolve it?

**Comment by m98** [comment]
Maybe you could ask the question on Stackoverflow, but may I see your router options?

**Comment by Sophia-nguyen** [comment]
Thanks @m98.
I asked question on Stackoverflow but I don't have any solution, here is link: https://stackoverflow.com/questions/44758008/angular-2-when-exception-error-application-crashes-tempalte-dont-show-data

and this is my router: 

```
var allRoutes = [
        {path: "home",component: DashboardComponent},
        {path: "accounts",loadChildren: 'app/components/account/AccountModule#AccountModule'},
		{path: "about",component: AboutComponent},
        {path: "error",component: ErrorComponent}
]

const routers = [{ path: '', canActivateChild: [CanActivateCustom], children: allRoutes }];
export const routing: ModuleWithProviders = RouterModule.forRoot(routers);

```

**Comment by m98** [comment]
You already defined the `about` path correctly, and before doing anything take a look at your `AboutComponent` and make sure you have the right template addressed there! open the `devTools console` and see if you have any error before you redirect to `/error`. also, check `/home` and `DashboardComponent` and compare your `AboutComponent` code with that.

**Comment by Sophia-nguyen** [comment]
Yes, I want
- If I go to any router and an error occurs for that component, `MyErrorHandler ` class with handle and redirect to `error` page.
- After that, I go to another page (`Home page`), if don't have any error, it will work.

But, although the `Home page` don't have any error, the data don't display (it will work correctly if I reload page).  I have to add `this.changeDetectorRef.detectChanges();` after I set data in HomeComponent to make it work.

But this is not a good idea for all component. I want another solution, to make all component can work, I used `applicationRef.tick()` but it doesn't work.
You have any solution for me?
Thank you very much

**Comment by m98** [comment]
Do you have the problem even when you go through `/about` directly from the browser?

I mean, just open `localhost:4200/about` (depends on your server settings) and press `ctrl+r` (refresh) to see if you still get the same problem or not?!

**Comment by Sophia-nguyen** [comment]
yes, `localhost:4200/about` always have problem.

**Comment by m98** [comment]
And what's the error you get on console?

**Comment by Sophia-nguyen** [comment]
`can't get data of undefined`

**Comment by m98** [comment]
@Sophia-nguyen, Did you solve the problem? I might help you easier if I can see the `aboutComponent.ts`

**Comment by Sophia-nguyen** [comment]
Actually my problem was:
- When I go to `/about` page and an error occurs. My app will redirect to `/error` page.
**==> This is the implementation of MyErrorHandler** 
- However after this, when I go back to `/home` or another page. The data of this page don't show on template, just show template without any data.

So whenever I got the error, I expect it will call MyErrorHandler and when I am back to another pages(home,...), I expected it still works as normal but It doesn't

**Comment by m98** [comment]
@Sophia-nguyen 
Okay, then please close the issue as it solved!

**Comment by Sophia-nguyen** [comment]
@m98 
Not yet, I don't want call `detectChanges()` manual at all component. I expected it work  as normal without call detectChanges() whenever I change data in each component.
Please help me!

**Comment by m98** [comment]
I don't know how can I help you if you don't share your codes! 

You need to share your code and other developers might be able to help you...

**Comment by Sophia-nguyen** [comment]
yes, I will crreate one Plunker to share my code.

**Comment by Sophia-nguyen** [comment]
Please view plunker here https://plnkr.co/edit/voZE1VfEvwoOuQYEr8nX?p=preview

And flowing these steps:
1. click home -> show "dashboard" text
2. click error -> show "error " text
=> work correctly

3. click about
=> an error occurs and navigate to error (this is that I expected)

4. click home again
=> it doesn't show "dashboard" text

 **I expected home page work as normal. Should show "dashboard" text.**

**Comment by chuckjaz** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
