### ISSUE TITLE
Compiler should throw an error if I use @HostListener in a service

### ISSUE THREAD

**Issue by adamdport** [angular/angular#17847]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm allowed to put @HostListener in a service, even if it doesn't work

## Expected behavior
The compiler should fail (or at least emit a warning?) telling me that the use of @HostListener within a service (or any other place that doesn't have a host) won't work. 

## What is the motivation / use case for changing the behavior?
Just a quality-of-life improvement

**Comment by vicb** [comment]
That's probably something for linting tools.

@mgechev do you think it would make sense to add such a check to [codelyzer](https://github.com/mgechev/codelyzer)

**Comment by mgechev** [comment]
Added in issue in codelyzer https://github.com/mgechev/codelyzer/issues/363.

**Comment by mgechev** [comment]
@wKoza implemented this rule [here](https://github.com/mgechev/codelyzer/pull/370).

It'll be part of the next release of codelyzer. @vicb I believe we can close this issue.
