### ISSUE TITLE
 Cannot assign to read only property 'participants' of object '[object Object]'

### ISSUE THREAD

**Issue by altreze** [angular/angular#17846]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The follow code throws an exception :
```
  immu(steps: Array<Step>, idx: number, participants: Array<User>): Array<Step> {
    steps[idx].participants = participants;
    return steps;
  }
```
ERROR TypeError: Cannot assign to read only property 'participants' of object '[object Object]'
It seems all objects are frozen in dev mode

## Expected behavior
whilst what follows just work in the browser console (or using node)
```
var immu = function(a, idx, b) {
  a[idx].users = b;
  return a;
};

var one = immu(
  [
    {name: 'test', "users": [1, 2, 3]}, 
    {name: 'test', "users": [0,2,6]},
    {name: 'test', "users": [1, 5]}
  ],
  1,
  [0,0]
);
```

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.10.3
- Platform: Mac / darwin x64
- Angular-cli: 1.0.3

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by altreze** [comment]
Hello @ericmartinezr,
I reported this on Angular/issues because the same described process was working on version 2.x, but no more by now in dev mode.

**Comment by vicb** [comment]
given the error message the issue is in your own code, @ericmartinezr is right.
