### ISSUE TITLE
Missing information in 6- Routing

### ISSUE THREAD

**Issue by olivier1208** [angular/angular#17844]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Just before this anchor https://angular.io/tutorial/toh-pt5#add-routing the app doesn't display heroes as awaited.
This issue "The selector "my-app" did not match any elements.

## Expected behavior
The Heroes should be displayed

## What is the motivation / use case for changing the behavior?
It's needed to change the root index.html file: the tag <app-root> to <my-app>for the app not to crash

## Please tell us about your environment

<pre><code>
Angular version: Latest 

Browser:
- [X ] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: Latest
- Platform: WIn 10 x64

Others:
Need to add this to fix
</code></pre>

**Comment by kapunahelewong** [comment]
Hi @olivier1208 Thanks for this and your patience. This was fixed when the doc was updated for the CLI. So I'm closing it, but if you have outstanding questions, please let me know.
