### ISSUE TITLE
@angular/core is not compatible with Typescript 2.4.1 when activating option strictNullChecks

### ISSUE THREAD

**Issue by AlainD-** [angular/angular#17863]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

when running a project (`ng serve`) which depends on latest Typescript option v2.4 (v2.4.1), but with strictNullChecks = true, a compilation error occurs:

```
ERROR in /Users/AlainD/Sites/toolsuite/node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts (2,22): Class 'DefaultIterableDifferFactory' incorrectly implements interface 'IterableDifferFactory'.
  Types of property 'create' are incompatible.
    Type '<V>(trackByFn?: TrackByFunction<V> | undefined) => DefaultIterableDiffer<V>' is not assignable to type '<V>(trackByFn?: TrackByFunction<V> | undefined) => IterableDiffer<V>'.
      Type 'DefaultIterableDiffer<V>' is not assignable to type 'IterableDiffer<V>'.
        Types of property 'diff' are incompatible.
          Type '(collection: NgIterable<V>) => DefaultIterableDiffer<V> | null' is not assignable to type '(object: NgIterable<V>) => IterableChanges<V> | null'.
            Type 'DefaultIterableDiffer<V> | null' is not assignable to type 'IterableChanges<V> | null'.
              Type 'DefaultIterableDiffer<V>' is not assignable to type 'IterableChanges<V> | null'.
                Type 'DefaultIterableDiffer<V>' is not assignable to type 'IterableChanges<V>'.
                  Types of property 'forEachOperation' are incompatible.
                    Type '(fn: (item: IterableChangeRecord<V>, previousIndex: number | null, currentIndex: number | null) =...' is not assignable to type '(fn: (record: IterableChangeRecord<V>, previousIndex: number, currentIndex: number) => void) => v...'.
                      Types of parameters 'fn' and 'fn' are incompatible.
                        Types of parameters 'previousIndex' and 'previousIndex' are incompatible.
                          Type 'number | null' is not assignable to type 'number'.
                            Type 'null' is not assignable to type 'number'.
(...)
```

## Expected behavior

Add support for Typescript 2.4 with strickNullChecks

## Minimal reproduction of the problem with instructions

- update typescript devDependency version to 2.4.1
- set strickNullChecks: true in tsconfig.json
- run `ng serve`
## Please tell us about your environment

<pre><code>
Angular version: 4.2.4
Typescript version: 2.4.1

tsconfig.json: "strickNullChecks": true

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.1.3 
- Platform: Mac 

Others:

- using yarn
</code></pre>

**Comment by ngfk** [comment]
This is because of typescripts [stricter generic checks](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#stricter-checking-for-generic-functions). A workaround is to disable it by adding `"noStrictGenericChecks": true` to your tsconfig.json.

**Comment by Delagen** [comment]
@ngfk does not work for me ((

**Comment by ngfk** [comment]
@Delagen Try combining with `"skipLibCheck": true`.

**Comment by AlainD-** [comment]
I would recommend to stick with Typescript 2.3.4 instead while these 2 issues are not fixed (the current one + the rxjs one), instead of disabling the checks on the newer version 2.4.1 of TS.

**Comment by Delagen** [comment]
@AlainD- I agree with you, but I want to test my own code through TS 2.4 (string enums and import module functions as needed), I currently have no issues with RxJS

**Comment by MarkPieszak** [comment]
At least from my testing, if you upgrade rxjs to `5.4.2` you should be able to run Angular with TS `2.4`. 

Just remember that you're upgrading at your own risk as I don't believe it has been fully tested &/or is supported at the moment.

**Comment by saulshanabrook** [comment]
@MarkPieszak I upgraded RSJS to `5.4.2` but am still getting some build errors:

```
ERROR in /Users/saul/projects/passit-frontend/node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts (2,22): Class 'DefaultIterableDifferFactory' incorrectly implements interface 'IterableDifferFactory'.
  Types of property 'create' are incompatible.
    Type '<V>(trackByFn?: TrackByFunction<V> | undefined) => DefaultIterableDiffer<V>' is not assignable to type '{ <V>(trackByFn?: TrackByFunction<V> | undefined): IterableDiffer<V>; <V>(_cdr?: ChangeDetectorRe...'.
      Type 'DefaultIterableDiffer<any>' is not assignable to type 'IterableDiffer<any>'.
        Types of property 'diff' are incompatible.
          Type '(collection: NgIterable<any>) => DefaultIterableDiffer<any> | null' is not assignable to type '(object: NgIterable<any>) => IterableChanges<any> | null'.
            Type 'DefaultIterableDiffer<any> | null' is not assignable to type 'IterableChanges<any> | null'.
              Type 'DefaultIterableDiffer<any>' is not assignable to type 'IterableChanges<any> | null'.
                Type 'DefaultIterableDiffer<any>' is not assignable to type 'IterableChanges<any>'.
                  Types of property 'forEachOperation' are incompatible.
                    Type '(fn: (item: IterableChangeRecord<any>, previousIndex: number | null, currentIndex: number | null)...' is not assignable to type '(fn: (record: IterableChangeRecord<any>, previousIndex: number, currentIndex: number) => void) =>...'.
                      Types of parameters 'fn' and 'fn' are incompatible.
                        Types of parameters 'previousIndex' and 'previousIndex' are incompatible.
                          Type 'number | null' is not assignable to type 'number'.
                            Type 'null' is not assignable to type 'number'.

ERROR in /Users/saul/projects/passit-frontend/node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts (10,22): Class 'DefaultIterableDiffer<V>' incorrectly implements interface 'IterableChanges<V>'.
  Types of property 'forEachOperation' are incompatible.
    Type '(fn: (item: IterableChangeRecord<V>, previousIndex: number | null, currentIndex: number | null) =...' is not assignable to type '(fn: (record: IterableChangeRecord<V>, previousIndex: number, currentIndex: number) => void) => v...'.
      Types of parameters 'fn' and 'fn' are incompatible.
        Types of parameters 'previousIndex' and 'previousIndex' are incompatible.
          Type 'number | null' is not assignable to type 'number'.
            Type 'null' is not assignable to type 'number'.

ERROR in /Users/saul/projects/passit-frontend/node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts (10,22): Class 'DefaultIterableDiffer<V>' incorrectly implements interface 'IterableDiffer<V>'.
  Types of property 'diff' are incompatible.
    Type '(collection: NgIterable<V>) => DefaultIterableDiffer<V> | null' is not assignable to type '(object: NgIterable<V>) => IterableChanges<V> | null'.
      Type 'DefaultIterableDiffer<V> | null' is not assignable to type 'IterableChanges<V> | null'.
        Type 'DefaultIterableDiffer<V>' is not assignable to type 'IterableChanges<V> | null'.
          Type 'DefaultIterableDiffer<V>' is not assignable to type 'IterableChanges<V>'.
            Types of property 'forEachOperation' are incompatible.
              Type '(fn: (item: IterableChangeRecord<V>, previousIndex: number | null, currentIndex: number | null) =...' is not assignable to type '(fn: (record: IterableChangeRecord<V>, previousIndex: number, currentIndex: number) => void) => v...'.
                Types of parameters 'fn' and 'fn' are incompatible.
                  Types of parameters 'previousIndex' and 'previousIndex' are incompatible.
                    Type 'number | null' is not assignable to type 'number'.
                      Type 'null' is not assignable to type 'number'.
```

**Comment by AlainD-** [comment]
@MarkPieszak The release of rxjs 5.4.2 only means that there no more errors about rxjs when using Typescript 2.4.1.
It does not mean that the issue with angular 4.2.5<->TS 2.4.1 is magically fixed! :-)

**Comment by MarkPieszak** [comment]
Definitely! That's why I was saying it might not work for everyone just yet :)

**Comment by Delagen** [comment]
New Feature of TS 2.4 make possible instead of using webpack loader for replacing this
```typescript
{
path:         "path",
loadChildren: "./some.module#SomeModule"
}
```
write
```typescript
{
path:         "path",
loadChildren: import("./some.module").then((module) => module.SomeModule)
}
```
or even
```typescript
{
path:         "path",
loadChildren: import(/* webpackChunkName: "app-account-module" */"./view/account/account.module").then((module) => module.AppAccountModule)
}
```
if you want webpack chunk naming (removeComments option must be turned off)
or even
```typescript
{
path:         "path",
loadChildren: async () => (await import(/* webpackChunkName: "app-account-module" */"./view/account/account.module")).AppAccountModule
}
```

**Comment by djnaumov** [comment]
This issue was fixed https://github.com/ReactiveX/rxjs/pull/2722, just install/update last release of rxjs (5.4.2)

**Comment by wulfsberg** [comment]
@djnaumov No. RxJs had the mismatched generics in lift. This one is another, but similar, error in angular core itself.

**Comment by mmc41** [comment]
Yes, this refers to a bug in @angular/core - it is NOT about the RxJs bug.

**Comment by AlainD-** [comment]
Hi, while this is officially fixed, is there any consequence I'm not aware of if I modify directly `node_modules/@angular/core/src/change_detection/differs/iterable_differs.d.ts` by adding `| null` to both types of `previousIndex` and `currentIndex` of the method `forEachOperation` on line 60 (v4.2.6)?

`forEachOperation(fn: (record: IterableChangeRecord<V>, previousIndex: number | null, currentIndex: number | null) => void): void;`

I did the modification to try it, and the compilation errors are gone. But I can't measure the impact of this change.

Thank you.

**Comment by Toxicable** [comment]
@AlainD- Editing type definition files is not going to change anything in the output JS

**Comment by ngfk** [comment]
@AlainD-  I tried the change in source and ran a build. All the tests still passed.

**Comment by AsherBarak** [comment]
This still seems to be broken

**Comment by dimkanewtown** [comment]
Yep, still an issue.

**Comment by shinhwagk** [comment]
set compilerOptions.strict to false into tsconfig.json?

**Comment by DewaldOosthuizen** [comment]
my tsconfig.json looks like this:

{
    "compilerOptions": {
        "module": "es2015",
        "target": "es2015",
        "lib": [
            "es2016",
            "dom"
        ],
        "skipLibCheck": true,
        "moduleResolution": "node",
        "noImplicitAny": false,
        "sourceMap": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "outDir": "./public/js/app"
    },
    "exclude": [
        "node_modules",
        "public/js",
        "assets/app/polyfills.ts"
    ],
    "angularCompilerOptions": {
        "skipMetadataEmit": true
    }
}

Adding the "skipLibCheck": true solved it for me

**Comment by AlainD-** [comment]
Hi Angular team,
is it planned to be fixed soon please ?

I am using the following config today
* `"@angular/core": "4.3.1"`
* `"typescript": "2.4.2"`
* `"compilerOptions": {"strict": true}`
and the errors are still present when `ng serve`.

Changing manually `node_modules/@angular/core/src/change_detection/differs/iterable_differs.d.ts` by adding the 2 missing ` | null` is still my workaround today, but I would like to know if you plan to work on this fix any time soon?

Thank you very much

**Comment by rbirkgit** [comment]
This is preventing us from using typescript 2.4.x. Any fixes in the pipeline?

**Comment by icepeng** [comment]
still cause error on 4.3.4

@angular/cli: 1.3.0
node: 8.2.1
os: linux x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4

Class 'DefaultIterableDifferFactory' incorrectly implements interface 'IterableDifferFactory'.

**Comment by AlainD-** [comment]
Of course it's not fixed :-)
There is an opened PR for this #18457, but still not approved yet.

**Comment by Delagen** [comment]
@chuckjaz when it will be released?

**Comment by nathanmarks** [comment]
This is preventing us from updating to TS 2.4 and using some awesome features like string enums which would greatly benefit our project.

Is there any timeline for when Angular is going to support the latest versions of TS with `strictNullChecks` enabled?

**Comment by Delagen** [comment]
@nathanmarks  Seems latest 5.0 beta fix this

**Comment by AnimaMundi** [comment]
Nice to know that it will be fixed in 5.x, but I would expect something like this would be included in a maintenance release for 4.x as well.

**Comment by peter** [comment]
As of 10:th of October 2017 I cannot compile the latest released version of Angular (4.4.4) with latest TypeScript (2.5.3) and scrictNullChecks. Failures:

Error at node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts:2:22: Class 'DefaultIterableDifferFactory' incorrectly implements interface 'IterableDifferFactory'.
Types of property 'create' are incompatible.
Type '(trackByFn?: TrackByFunction | undefined) => DefaultIterableDiffer' is not assignable to type '{ (trackByFn?: TrackByFunction | undefined): IterableDiffer; (_cdr?: ChangeDetectorRe...'.

Error at node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts:10:22: Class 'DefaultIterableDiffer' incorrectly implements interface 'IterableChanges'.
Types of property 'forEachOperation' are incompatible.
Type '(fn: (item: IterableChangeRecord, previousIndex: number | null, currentIndex: number | null) =...' is not assignable to type '(fn: (record: Iterabl

Error at node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts:10:22: Class 'DefaultIterableDiffer' incorrectly implements interface 'IterableDiffer'.
Types of property 'diff' are incompatible.

**Comment by peter** [comment]
Speaking of which, is Angular 4.4.4 compatible with TypeScript 2.5.3? Is there an official version compatibility/dependency table anywhere for Angular? I haven't found one.

**Comment by JohannesRudolph** [comment]
AFAIK Typescript 2.5 will be supported with angular 5.0

Am 10.10.2017 11:40 AM schrieb "Peter Marklund" <notifications@github.com>:

**Comment by Toxicable** [comment]
4.x is not and will not work with TS 2.5, use 2.3 instead, 2.4 might work for you but 2.3 will work for sure.
5 requires TS 2.4 and is also compatible with 2.5

**Comment by ShadowManu** [comment]
this is not perfect but if some of you need (as I do) to use the newer TS versions, you can combine `.angular-cli.json`'s `typescriptMismatch` and `tsconfig.json`'s `skipLibCheck` if you want the stricter type-checking in your code anyway.

**Comment by rbirkgit** [comment]
I believe you need angular 5.2 to support typescript 2.6

**Comment by benjamin21st** [comment]
Ummm, I'll try upgrading Angular and see if that makes the problem go away. Thanks for pointing that out! I wish there is a compatibility table for TypeScript and Angular :(

**Comment by mawadallah** [comment]
it's not working also with me
any suggestions, this is my tsconfig.ts
`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "skipLibCheck": true,
    "noStrictGenericChecks": true,
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
`

**Comment by kirillgroshkov** [comment]
Update to Angular 6, it supports up to typescript@2.9

**Comment by kirillgroshkov** [comment]
or set `skipLibCheck: true`

**Comment by pkozlowski-opensource** [comment]
Angular is now on [TS 3.1.x](https://github.com/angular/angular/blob/fdaf573073d20d6b19f1bebcdef8eb2f854a4f12/package.json#L130) and its sources are compiled with [strictNullChecks](https://github.com/angular/angular/blob/fdaf573073d20d6b19f1bebcdef8eb2f854a4f12/packages/tsconfig.json#L9) so I think this can be closed now.
