### ISSUE TITLE
Error when using ng-container for children components

### ISSUE THREAD

**Issue by dgroh** [angular/angular#17866]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
We have a list of tabs which are defined in our `ts` file like so:

```
  public tabs = [
    { title: "Tab1", url: "Tab1", component: Tab1ContentComponent },
    { title: "Tab2", url: "Tab2", component: Tab2ContentComponent },
    { title: "tab3", url: "Tab3", component: Tab3ContentComponent }
  ];
```

Here is how we render this list in our **HTML**:

```
<kendo-tabstrip (tabSelect)="select($event)">
  <kendo-tabstrip-tab *ngFor="let tab of tabs; let index = index" [title]="tab.title" [selected]="index === selectedTabIndex">
    <ng-template kendoTabContent>
      <ng-container *ngComponentOutlet="tab.component"></ng-container>
    </ng-template>
  </kendo-tabstrip-tab>
</kendo-tabstrip>
```
We have a dropdown with a list of years and when an year is selected we navigate to the corresponding year in the current tab:

`this.router.navigate(["/Tab1", year]).then(() => this.getValues(year));`

This works for the first navigation, for the second time we get the following error:

 > ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'component' of null

Here is our routing config:

```
const tabsRoutes: Routes = [
    {
        path: "",
        redirectTo: "Tabs",
        pathMatch: "full"
    },
    {
        path: "Tabs",
        component: TabsComponent,
        children: [
            { path: "Tab1", component: Tab1ContentComponent },
            { path: "Tab1/:year", component: Tab1ContentComponent },
            { path: "Tab2", component: Tab2ContentComponent },
            { path: "Tab2/:year", component: Tab2ContentComponent },
            { path: "Tab3", component: Tab3ContentComponent },
            { path: "Tab3/:year", component: Tab3ContentComponent }
        ]
    }
];
```

## Expected behavior
We expect the error not to be thrown. (why it's not thrown for the first navigation?)

The error disapears once we use a `<router-outlet>` for the children components instead of `ng-container`

## Minimal reproduction of the problem with instructions
As we are using kendo ui for angular which requires a specific license, we did not manage to reproduce this in a plunkr.

## What is the motivation / use case for changing the behavior?
We want to load the tabs "dynamically". we wish we could define the route children in the `ts` file where the tabs are defined, so we don't have to create for each new tab a new line in the router config.

## Please tell us about your environment

@angular/cli: 1.1.1
node: 6.11.0
os: win32 x64

Browser:
- [x] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.0
- Platform: Windows

Others:

</code></pre>

**Comment by vicb** [comment]
Please add a minimal repro

**Comment by actra-gschuster** [comment]
Just an idea: try tabs[index].component instead, maybe tab gets nulled somewhere as it's an object.

**Comment by dgroh** [comment]
This usse can be closed, we made it work withchildren `<router-outlet>` instead
