### ISSUE TITLE
Accessing Remote Template (HTML from .Net) in Angular

### ISSUE THREAD

**Issue by niranjan-reddy** [angular/angular#17865]
## My Angular4 Application needs to access a few Templates (dynamically provided by .Net Engine/IIS) and I need to bind data on my Angular4 side after receiving the Template. And it is not working.

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, when I try to access the Remote Template it fails to access them. However, the remote Templates are ready to access.

## Expected behavior
Upon hitting the Remote Template URL or Request, it should receive the remote Template (dynamic template based on user privileges, supplied by .Net Engine on IIS) and then the REST response data is to be bound to the HTML while rendering.

## What is the motivation / use case for changing the behavior?
Customer has existing application in production and wants a new application, that uses several templates from the old existing application. And the template generation logic is to be kept intact.

## Please tell us about your environment
Windows 7 Machines for Application Development.
RAM - 8GB
Intel i5 Machines
Microsoft IIS Version 7.5
Microsoft Visual Studio 2017
.NET Version 4.5
Angular4
Integrated with MVC.Net

<pre><code>
Angular version: 4

Browser:
- [x] Chrome (desktop) version  59.0.3071.104
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.3 
- Platform: Windows 7

Others:

</code></pre>

**Comment by Toxicable** [comment]
What specifically isn't working? Are you getting an error?

**Comment by alfredobialo** [comment]
With your case, angular4 AOT cannot handle dynamic template based on user's privilege, which has got me thinking, so you must resort to using JIT. you should use a better logic in assigning the template URL
`

// Do this in your any partial view (_urls.cshtml) file
const basePartialUrl : string = '@Url.Action("FindPartial","AppPartial")'  ;  // FindPartial should map to a Controller Action in ASP.NET MVC and should return a partial view` 
You can now reference the url in your angular4 Component templateUrl like so



// const partialUrl :string = basePartialUrl+"?id=";

@Component({
selector: 'xui-customer-view-widget',
templateUrl : partialUrl +'customer-template'
})
export class CustomerViewWidget{}

**Comment by dherges** [comment]
If you ask me, I'd take a different architectural approach.

1) The JSON-to-Angular-Router-pattern

```http
GET /user/privileges
Content-Type: application/json

{ "user": "joe", "privileges": [ "a", "b", "c" ] }
```

```ts
const routes: Routes = [
  { path: "/admin", canActivate: CheckPrivilegesGuard, data: { privileges: ["a", "c" ] }},
  { path: "/ordinary-people", canActivate: CheckPrivilegesGuard, data: { privileges: ["a", "b"] }}
];
```

Write a [route guard](https://angular.io/guide/router#milestone-5-route-guards)

1b) The JSON-to-template-switching-pattern:

```html
<span *ngIf="privileges.contains('a')"><foo-component></foo-component></span>
<span *ngIf="privileges.contains('b')"><bar-component></bar-component></span>
```

Possibly w/ [dynamic component loading](https://angular.io/guide/dynamic-component-loader).


2) Fine-grained HTML snippets to view outlets:

```http
GET /custom/view.html
Content-Type: text/html

<h1>foobar</h1>
```

```html
<div [innerHTML]="http.get('/custom/view.html').map(res => res.text()) | async"></div>
```

You could also put HTML snippets in JSON, like:

```json
{
  "one": "<h1>foobar!</h1>",
  "two": "<h2>bar1</h2>",
  "grid": [
     { "title": "First" },
     { "title": "Second" },
     { "title": "Third" }
  ]
}
```

Then render the JSON snippets to designated outlets, possibly building a "dynamic" view with `*ngIf`, `*ngFor`.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
