### ISSUE TITLE
Routing issue with Resolver

### ISSUE THREAD

**Issue by jishansidhu** [angular/angular#17869]
Hi,

When I use make use of Resolver, routing doesn't work.
However, console log from resolver are working fine which means resolver code is ok.
Any suggestions to fix this issue?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jishansidhu** [comment]
Closed
