### ISSUE TITLE
Step by Step Guide - Display Data discontinuity

### ISSUE THREAD

**Issue by drozzy** [angular/angular#1787]
The "DISPLAYING DATA" section in "Step by Step Guide" has got me very confused:
https://angular.io/docs/js/latest/guide/displaying-data.html

First of all, let me ask if there is a complete code for the guide - because that would solve most of my problems. I can even fix most of the mistakes myself. However, without it, I am truly stumped by the following:

1. Page starts off with "Let's walk through how we'd display a property, a list of properties, and then conditionally show content based on state.". What is a "property"? It's like we missed something...

2. "Create an entry point" - Where? The guide says to create "show-properties.html" file, and put the "display" tag in there, but nowhere in the tutorial does it actually say how it's related to "Step 1: Getting started". How is this linked to Index.html?

3. Weird wording: "So you can see Angular dynamically update content, add a line after" "to this" --- those two sentences don't mesh.

4. Next comes the additional script instruction: "Then give the DisplayComponent a starting value for time and a call to update time via setInterval."  But where should the line of code be inserted? Into constructor? Into class? Somewhere else?

5. Needless to say the instruction "Reload the page in your browser and you'll now see the seconds updating automatically." didn't work for me, as I was lost at that point, and my page looked like in Step 1. I tried navigating to "http://localhost:8080/show-properties.html" with no luck.

Questions left unanswered:

1. How are Components and Views related to the "class"? Is there some kind of default where all the code in a single .ts file makes up a "component"? The guide says "By associating your class with elements named 'display' in the DOM, Angular knows to automatically call new on DisplayComponent and bind its properties to that part of the template." --- but how? Is it because the class name should be "capitalize(display) + Component"?
2. Why does the Quickstart tutorial make use of the `<reference path="typings/angular2/angular2.d.ts" />` line, but the Step-by-Step Guide doesn't?
3. The disagreement on the http server between the Quickstart (which recommends npm's http-server) and the Guide (which advocate "python -m SimpleHTTPServer 8000") does not bode well for the consistency of the documentation.

N.B.: I just wanted to point out that I was an intermediate/advanced user of angular1, so if I am stumped by this tutorial, I can't imagine someone new getting very far with it.

**Comment by ghaddon1** [comment]
I would agree... Would nice to see the total solution for each phase.

**Comment by rkirov** [comment]
Can you repost to https://github.com/angular/angular.io

**Comment by drozzy** [comment]
Reposted.
