### ISSUE TITLE
When a ControlValueAccessor binds to another ControlValueAccessor the initial value gets wiped

### ISSUE THREAD

**Issue by willseitz** [angular/angular#17883]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I have  two components implementing ControlValueAccessor and one of them binds it's value to the other the inner one gets undefined instead of the right value in the writeValue method. This value is then chained back up clearing the original data you were binding to. Hopefully this plunkr will be useful: 
https://plnkr.co/edit/ynlJ7fBykSGDiGdMxnd0?p=preview in demostrating the problem. In the plunkr, the problem is that the original 'green' value of thingie is wiped. After the original start up, the bindings work correctly and all the buttons function as expected.

## Expected behavior

I expect that my data would not be wiped out by this form of binding.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/ynlJ7fBykSGDiGdMxnd0?p=preview

## What is the motivation / use case for changing the behavior?

The motivation for this pattern was that we created a custom dropdown that you could bind data to. We also had the notion of a "job dropdown" that had specific behavior. We wanted to use the job-dropdown in multiple places and bind it to data. So the job dropdown bound its value to the dropdown, revealing this bug.

## Please tell us about your environment

<pre><code>
Angular version: 4.1.1 and 4.2.5

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by tytskyi** [comment]
@willseitz please take a look at fixed plunker: https://plnkr.co/edit/awDllluzLTEnoDJr08ED?p=preview

You don't need to "propagate change" in the `writeValue(value: any): void`.

I think `writeValue` if always executed with the `null` for the first time. At this moment you send null to the top model in your example.

**Comment by willseitz** [comment]
Awesome, that was it. My code is working now. Thanks!
