### ISSUE TITLE
compiler.clearCache() / compiler.clearCacheFor(), templates are not cleared

### ISSUE THREAD

**Issue by olezt** [angular/angular#17880]
## I'm submitting a ...

<pre><code>
[x] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

 [compiler.clearCache()](https://angular.io/api/core/Compiler#clearCache) clears the _metadataResolver, _compiledTemplateCache, _compiledHostTemplateCache, _compiledNgModuleCache as supposed but when I route to another page templateURL is not requested again, hence template stays the same. 
Same for [compiler.clearCacheFor()](https://angular.io/api/core/Compiler#clearCacheFor)

How is this possible if cache is cleared?

Updated [Plunker](https://plnkr.co/edit/vvliI4?p=preview) that reproduces the problem.

## Please tell us about your environment
Based on [this stackoverflow answer](https://stackoverflow.com/a/40156489/6835976) this used to work.
<pre><code>Angular versions tried and it is NOT working: 4.2.3 / 4.2.5</code></pre>

**Comment by CarlinhosSousaJunior** [comment]
In my application i have a compiler.clearCache () on login success because my templateUrl is generated by web api according to user profile, and when user profile is changed i need to reload all pages using clearCache (), but im testing and it's not working anymore.

Now i doing this functionality using location.reload() but i think that isn't the best way.

**Comment by tbosch** [comment]
Ddid this work in an older ng version?

**Comment by healkar01** [comment]
Has anything been done about this?

**Comment by lapisanlangit** [comment]
Angular JS 1.xx have this for clear cache 

`    app.run(function ($rootScope, $templateCache) {
            $rootScope.$on('$viewContentLoaded', function () {
                $templateCache.removeAll();
            });
        });`
this code working properly, but why angular 4 `compiler.clearCache ()` doesn't work? any solution?

**Comment by olezt** [comment]
@tbosch As stated on the issue description, based on [this stackoverflow answer](https://stackoverflow.com/a/40156489/6835976), it used to work for Angular 2.0.2. Haven't tried it myself though.

**Comment by CarlinhosSousaJunior** [comment]
Any position about this ? Im waiting this for long time.

**Comment by mostafiz57** [comment]
After Successfully login , I want to reload my Navbar template again . for this I am try to use compiler.clearCache() in my Angualr App (   "@angular/compiler-cli": "~4.1.0" ) but is not working . Has any solution in any upper version ?

**Comment by piyushmanurkar** [comment]
Any update about this?

_ng -v_
**Output:**
Angular CLI: 1.6.8
Node: 9.8.0
OS: darwin x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.1
@angular/cli: 1.6.8
@angular/material: 5.2.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

**Comment by vohrahul** [comment]
Any update on this. Why this issue is not being addressed? It's very tedious to work when it's always caching even in the development mode.

**Comment by ian-harvey** [comment]
What is the status of this issue? How can this method be in the official API when the Angular team knows it does not work?

**Comment by soyjuanmedina** [comment]
Any update or alternative?

**Comment by oxenprogrammer** [comment]
In Angular 5.X we can use the compiler in the same way as 2.0.

Import the compiler:

`import { Compiler } from '@angular/core';`

Inject the Dependency in your component constructor :

`constructor(private _compiler: Compiler) { }`

Clear the cache:

`this._compiler.clearCache();`

As answered  here by https://stackoverflow.com/questions/34808023/how-to-clear-template-cache

**Comment by alxhub** [comment]
This was a bug present in 2.0, but was fixed in 5.0 as @oxenprogrammer mentions. Closing as fixed.
