### ISSUE TITLE
local variable undefined in html template

### ISSUE THREAD

**Issue by margielm** [angular/angular#1789]
Hello,

Looks like local variables are broken in alpha-22. 

This simple code:
````html
<input #newtodo type="text" (keyup)/>
{{newtodo.value}} 
````

is throwing following exception:
````
TypeError: Cannot read property 'value' of undefined in [
	{{newtodo.value}}
	 in MyAppComponent]
````
It was working previously in a version bundled with quick start project.

What is interesting it is that it doesn't work only for, lets call it, bind operations. When I pass local variable to as a parameter to an event, then everything is working:
```html
<form action="#" (submit)="add(newtodo)">
	<input #newtodo type="text" (keyup)/>
```

**Comment by piflex** [comment]
:+1 I encountered this too, the demo example from docs does not work

    <input #myname (keyup)>
    <p>{{myname.value}}</p>

**Comment by igorpan** [comment]
:+1:  I encountered this too, the demo example from docs does not work

    <input #myname (keyup)>
    <p>{{myname.value}}</p>

It throws exactly the same error as for @margielm

**Comment by vicb** [comment]
Was it alpha-22 or alpha-23 ? 
Do you have the code available somewhere ?

**Comment by igorpan** [comment]
It's alpha-22 as that's the one that gets installed when using:

    tsd query angular2 --action install

The code is empty really:

    import {Component, View} from 'angular2/angular2'

    @Component({
	    selector: 'todo-app'
    })
    @View({
    	template: `
    		<h1>Todo</h1>
		<input #myname (keyup)>
		<p>{{myname.value}}</p>
	`
    })
    export class TodoAppComponent {
    }

**Comment by margielm** [comment]
I confirm that the error appears in alpha 22. Just wanted to try in 23 but it is not published yet.
https://code.angularjs.org/2.0.0-alpha.23/

**Comment by vicb** [comment]
fixed in .23

**Comment by mashaly100200** [comment]
it  dose not work after update from alpha 28 to alpha 38 and gave me the same error

**Comment by jessegood** [comment]
@mashaly100200 : I believe that is the same issue reported at https://github.com/angular/angular/issues/3754

**Comment by shikloshi** [comment]
+1 
same issue on alpah 35

**Comment by chkk525** [comment]
+1

**Comment by pkozlowski-opensource** [comment]
@chkk525 there is not much point in +1 on a closed issue... If you see a pb please open a new issue with clear description, steps to reproduce and - ideally - a runnable demo in plunker. See what is the kind of info that we are looking for when it comes to issue reports:  https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue

**Comment by racksen** [comment]
@pkozlowski-opensource
 Attaching events in template throws error. 

e.g  the following template works fine
<input #testname value="Test" />
<p> {{ testname.value }}</p>

but the following one throws error, the moment I add the event
<input #testname value="Test"  (keyup)/>
<p> {{ testname.value }}</p>

**Comment by racksen** [comment]
@pkozlowski-opensource
 Attaching events in template throws error. 

e.g  the following template works fine
```
<input #testname value="Test" />
<p> {{ testname.value }}</p>
```
but the following one throws error, the moment I add the event
```
<input #testname value="Test"  (keyup)/>
<p> {{ testname.value }}</p>
```

**Comment by patilms16** [comment]
I am trying it using alpha.44 

I am getting erroe in colsole as : EXCEPTION: TypeError: Cannot set property 'lastInBinding' of undefined
