### ISSUE TITLE
DI: provide an equivalent to @SkipSelf in Injector.get()

### ISSUE THREAD

**Issue by youdz** [angular/angular#17898]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

It is currently possible, when injecting a dependency in a constructor, to use `@Optional()` to avoid an error when the dependency is not found, and `@SkipSelf()` to search directly on the parent injector. For instance, a typical use case for `@SkipSelf()` is self-nested components that need to inject their parent.
```typescript
export class MyComponent {
  constructor(@Optional() @SkipSelf() parent: MyComponent) {}
}
```
When working with more "dynamic" dependency injection, however, you need to rely on an [Injector](https://github.com/angular/angular/blob/master/packages/core/src/di/injector.ts) object. It offers an equivalent to `@Optional()` by accepting a `notFoundValue`, but there is no way to emulate `@SkipSelf()`. The parent injector is not public, and the only method is `.get()` which will obviously look in this injector first.

## Expected behavior

The `get()` method should accept a third optional argument allowing us to search directly on the parent injector:
```typescript
abstract get<T>(token: Type<T>|InjectionToken<T>, notFoundValue?: T, skipSelf?: boolean): T;
```
It would default to `false`, evidently.

## What is the motivation / use case for changing the behavior?

It should be logical for `Injector` to offer the exact same capabilities as constructor-level dependency injection.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5

</code></pre>

**Comment by darin-cardin** [comment]
Closing in on a year now. Any update on this. it seems like a simple fix, as the functionality already exists.

**Comment by agale123** [comment]
It appears that this functionality was added as part of  #22005 in [this commit](https://github.com/angular/angular/commit/235a235fab45b2c82f8758fc9c0779f62a5b6c04)

So if you want to use the equivalent of @SkipSelf you would write:
`injector.get(Foo, undefined, InjectFlags.SkipSelf)` 

But when I call this from within a Directive and use SkipSelf it is still returning the current instance of the directive.

**Comment by chenlijun99** [comment]
Could it be related to #34066?
