### ISSUE TITLE
How many times is change detection supposed to be run

### ISSUE THREAD

**Issue by conorjohn** [angular/angular#17909]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Brand new app, generated with Angular CLI and only one component (App Component). Enabled prod mode and running ngDoCheck(). It is currently running 2 checks when the app loads. 

## Expected behavior

One check would be logged out on load.

## Minimal reproduction of the problem with instructions

ng new ngCliApp
ng serve
add the following code to app.component.ts
`count: number = 0;

	ngDoCheck(){
	    this.count++;
	    console.log('change detection triggered from APP COMPONENT', this.constructor['name'], ' - ', this.count);
	}`
in main.ts, just to be safe and consistent, make sure prod is enabled:
enableProdMode();

*NB - I have tested with prod on and off but neither have made a difference

## What is the motivation / use case for changing the behavior?

I am trying to optimise the change detection on a much larger app and this is throwing me off on how exactly the change detection is working and trying to debug the problems I have with my existing app and CD. I am trying to pin point some bottle necks in performance and this is making it very difficult to do so. If this is how the change detection is meant to work then that is fine, I just haven't found an explanation anywhere as to why this is the case. The issue isn't specifically with the newly generated app, it's how this behaviour may or may not be affecting my larger application. Any help much appreciated.

## Please tell us about your environment

<pre><code>
Angular version: ^4.0.0 * also appearing on 2.0 version
CLI: "@angular/cli": "1.2.0"

Browser:
- [x] Chrome (desktop) Version 60.0.3112.50 (Official Build) beta (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.9.4 
- Platform: Windows 10 

Others:

</code></pre>

**Comment by IgorMinar** [comment]
In prod mode the change detection should happen just once per trigger (ApplicationRef#tick). In dev mode it should happen twice.
