### ISSUE TITLE
svg g element not allowing transform attribute

### ISSUE THREAD

**Issue by ericj79** [angular/angular#17903]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

in my SVG I have a g element that I am trying to transform to a different spot in the SVG, but the angular compiler will not allow that attribute in the element, even though it is valid.

## Expected behavior

allow the attribute

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/aQLb4z0hxIoH5zQoSbCW?p=preview
the following template should compile: 
```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="0 0 1000 2500" width="1000" height="2500" preserveAspectRatio="xMidYMid">
    <svg:rect id="map" x="0" y="0" height="2500" width="1000" />
    <g class="general">
      <g id="background">
          <path d="M200,100 L800,100 L800,300 L900,300 L900,2400, L100,2400, L100,300 L200,300 Z" />
          <path d="M900,350 l50,0 q0,50 -50,50 Z" stroke="white" />
          <path d="M900,350 l50,0"  />
          <path d="M100,350 l-50,0 q0,50 50,50 Z" stroke="white" />
          <path d="M100,350 l-50,0" />
          <path d="M200,300 l0,50" />
          <path d="M800,300 l0,50" />
          <path d="M250,350 l500,0" />
      </g>
      <g id="chairs">
        <g id="{{section.name}}" *ngFor="let section of chairs" transform="translate({{section.posX}} {{section.posY}})">
        </g>
      </g>
    </g>
</svg>
```

## What is the motivation / use case for changing the behavior?

being able to move the group of svg elements within an svg. Being fully compatible with the svg spec.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2 
- Platform: Windows 10

Others:

</code></pre>

**Comment by zoechi** [comment]
Please provide a Plunker that demonstrates the issue as requested in the issue template.
Your issue doesn't even show how you tried to add the attribute.

**Comment by ericj79** [comment]
Sorry I thought I had. I must have left it in the comments: http://plnkr.co/edit/aQLb4z0hxIoH5zQoSbCW?p=preview

Here is an example template that fails:
<code>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="0 0 1000 2500" width="1000" height="2500" preserveAspectRatio="xMidYMid">
    <svg:rect id="map" x="0" y="0" height="2500" width="1000" />
    <g class="general">
      <g id="background">
          <path d="M200,100 L800,100 L800,300 L900,300 L900,2400, L100,2400, L100,300 L200,300 Z" />
          <path d="M900,350 l50,0 q0,50 -50,50 Z" stroke="white" />
          <path d="M900,350 l50,0"  />
          <path d="M100,350 l-50,0 q0,50 50,50 Z" stroke="white" />
          <path d="M100,350 l-50,0" />
          <path d="M200,300 l0,50" />
          <path d="M800,300 l0,50" />
          <path d="M250,350 l500,0" />
      </g>
      <g id="chairs">
        <g id="{{section.name}}" *ngFor="let section of chairs" transform="translate({{section.posX}} {{section.posY}})">
        </g>
      </g>
    </g>
</svg>
</code>

**Comment by zoechi** [comment]
SVG doesn't have properties. You need to use attribute binding with SVG elements

```html
attr.transform="translate({{section.posX}} {{section.posY}})"
```
or
```
[attr.transform]="'translate(' + section.posX + section.posY + ')'"
```

**Comment by ericj79** [comment]
I thought I had tried that, sorry for the confusion.

**Comment by zoechi** [comment]
No worries, glad to hear you could make it work.
