### ISSUE TITLE
Expose _control in ControlDirective for Custom Form Controls

### ISSUE THREAD

**Issue by mlynch** [angular/angular#1790]
One use case that we have at Ionic (and angular2_material will) is making custom for elements. For example, imagine a 3 state SegmentedControl toggle:

![screenshot 2015-05-09 09 19 23](https://cloud.githubusercontent.com/assets/11214/7550568/8207a96e-f62c-11e4-9782-fde91e7b86c3.png)

This specific one could be built with radios, of course, but assume we want a completely custom control. The markup looks like:

```html
<form [control-group]="form">
  <ion-segment control="mapStyle">
    <ion-segment-button value="standard"></ion-segment-button>
    <ion-segment-button value="hybrid"></ion-segment-button>
    <ion-segment-button value="sat"></ion-segment-button>
  </ion-segment>
</form>
```
The only way I could figure out how to work with the `[control]` attribute to load and save form values was like this (modeled from the checkbox code in [forms/directives](https://github.com/angular/angular/blob/75db2c52411c801afa138800fe20cec3b731184e/modules/angular2/src/forms/directives.js#L78):

```
export class Segment {
  constructor(cd:ControlDirective) {
    cd.valueAccessor = this;
    this.controlDirective = cd;
  }
  writeValue(value) {
    // implement the valueAccessor's writeValue
  }
  select(segmentButton) {
    // Called when a ion-segment-button triggers select on the parent ion-segment
    this.value = segmentButton.value;
    this.controlDirective._control().updateValue(this.value);
  }
}
```

If creating custom form elements continues to be a common need, I think the `ControlDirective` should more easily expose the underlying `Control` instead of having to call `_control()`.

Unless I'm just doing this the wrong way?

**Comment by vsavkin** [comment]
Closed by https://github.com/angular/angular/pull/2926
