### ISSUE TITLE
my js file is not work on angular 4 after i do routing navigate

### ISSUE THREAD

**Issue by sutineeangs** [angular/angular#17906]
Hi, i have a problem about js file is not work after i do routing navigate.
1.this's my script file
```
$(document).on('page:change', function () {
    $('#wsnavtoggle').click(function () {
        $('.wsmenucontainer').toggleClass('wsoffcanvasopener');
        $('.wsmenucontainer').removeClass('wsoffcanvasopener02');
    });
    ....
});
```
2.I include my js file and jquery library on index.html file
```
  <!-- JQUERY -->
  <script src="assets/js/jquery-3.2.1.min.js"></script>
   ....
  <!-- MENU REPONSIVE -->
  <link rel="stylesheet" type="text/css" media="all" href="assets/style/webslidemenu.css">
  <script type="text/javascript" src="assets/js/webslidemenu.js"></script>
```
3.at login-page.component.ts , I use routing navigate in login method
```
login(e) {
 ...
  this.router.navigate(['/main']);
 }
```
4.this is my routing
```
{   
        path: 'member',
        component: MemberPageComponent,
        children: [
            {path: '', redirectTo: 'login', pathMatch: 'full'},
            {path: 'login', component: LoginPageComponent}
        ]
    },

    {
        path: 'main', 
        component: MainPageComponent,
        children: [
            {path: '', redirectTo: 'trade', pathMatch: 'full'},
            {path: 'trade',  component: TradePageComponent}
        ]
    }
```

5.When myapp login successful and navigate to main page, I try to test my script by using slide menu bar, it doesn't work. if I refresh this page, it does work.

I need to make it work after navigate. help me please

**Comment by Foxandxss** [comment]
The questions are more suitable for stackoverflow. This issue tracker is for bugs and features.

**Comment by mistikel** [comment]
I face the same issue, did you manage to fix this? @sutineeangs

**Comment by oky1** [comment]
Same problem.

**Comment by Tobmai** [comment]
same problem

**Comment by mlc-mlapis** [comment]
@sutineeangs ... because `wsnavtoggle` id doesn't exist ... and exists after login and refresh?

**Comment by bachirNdiaye** [comment]
Issue for me (I'm newbie and i'm using angular Js, i don't know if it will be the same): Write the Js code into the controller worked for me

**Comment by desbond** [comment]
Not ideal but instead of router.navigate after login you can do window.location.href

Downside is another slight delay in loading.

**Comment by LegolasTheElves** [comment]
Did you find any solution about this problem?

**Comment by adesheddie** [comment]
I am facing same problem :( No fix even after 1 year ?

**Comment by flendsiva** [comment]
i have the same issue, i tried this issue (6month)

**Comment by Anuj-logiciel** [comment]
@Foxandxss - Could You give any solution here ? Same Issue with me also and not any solution on stackoverflow also.

**Comment by malithkuruwita** [comment]
This answer worked for me.
Check this out

https://stackoverflow.com/a/55675403/6314955

you have to load the script inside component.ts file where you want

**Comment by anhnt2989** [comment]
@malithkuruwita Tks man! Used that solution and it worked ! <3
