### ISSUE TITLE
docs: typo in Tour of Heroes Tutorial

### ISSUE THREAD

**Issue by dima74** [angular/angular#17900]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Open page https://angular.io/tutorial/toh-pt5#update-the-heroescomponent-class. This chapter starts with text

> The HeroesComponent navigates to the **HeroesDetailComponent** in response to 

## Expected behavior

Instead there should be text

> The HeroesComponent navigates to the **HeroDetailComponent** in response to 

because there isn't component `HeroesDetailComponent` in this tutorial, there is only component `HeroDetailComponent`.

**Comment by trotyl** [comment]
This has been fixed by #19811, can be closed now.
