### ISSUE TITLE
Typo in Router documentation of RouteConfigLoadStart

### ISSUE THREAD

**Issue by ralemy** [angular/angular#17901]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In [Router documentation](https://angular.io/guide/router) , this line is seen:

RouteConfigLoadStart	An event triggered after a route has been lazy loaded. 

## Expected behavior

should read

RouteConfigLoadEnd  An event triggered after a route has been lazy loaded.

## Minimal reproduction of the problem with instructions

N/A
## What is the motivation / use case for changing the behavior?

N/A

## Please tell us about your environment
N/A
<pre><code>
Angular version: X.Y.Z

4.2.5
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 N/A
For Tooling issues:
- Node version: XX 
- Platform: 
N/A
Others:

</code></pre>

**Comment by brandonroberts** [comment]
@Foxandxss this one can be closed as resolved.

**Comment by jasonaden** [comment]
Resolved with above PRs
