### ISSUE TITLE
Click listener inside ngFor does not work in combination with HostListener on document

### ISSUE THREAD

**Issue by sschoeb** [angular/angular#17916]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
No more click events fire in ngFor when any component does subscribe to document:mouseup or document:mousedown. 
The problem does only occur when ngFor does loop over a dynamic list of items (see plunkr)

## Expected behavior
Click events should still fire.

## Minimal reproduction of the problem with instructions
- Create a Component with a function which returns a list of items (always creates a new list of items)
- Create a ngFor iterating over the list returned by the function
- Create a click listener inside the ngFor
=> Click listener works fine

- Add a new Component with a @HostListener('document:mouseup')
- Show newly created component
=> Click listener does no more work

Here is a plunker to reproduce:
http://plnkr.co/edit/Gdds3HrTBsN5VY69ve5p?p=preview

## Please tell us about your environment
Angular version: 4.2.5
Browser: All

**Comment by zoechi** [comment]
How can I reproduce in Plunker. When I click on any `CLICK` it adds an entry to `Clicks-Log`.

**Comment by zoechi** [comment]
What `getDynamicItems()` does, is a something you should avoid at all cost in Angular.
It creates a new array every time change detection runs.
Rather assign the array to a field and bind to that field instead
http://plnkr.co/edit/h7FmVLU7OTiZEA7y5m1S?p=preview

**Comment by sschoeb** [comment]
You are right, using a method which returns a new value every time is not a good idea and should be avoided.

BUT: Why does a HostListener on document.mouseup influence a click-event in an ngFor when you iterate over a newly created array? This makes no sense.

**Comment by zoechi** [comment]
I don't really think it makes sense to reason about that. 
Binding to an array that way is not something "that should be avoided", it's something that "should be avoided *at all cost*". This is like similar to an endless loop. Perhaps the browser just doesn't have time to process the events anymore or similar.

**Comment by tytskyi** [comment]
Look at the forked example with `console.count` http://plnkr.co/edit/hAQxaY8s55fq1kdzWKqo?p=preview
When component that listens to global event is enabled - change detection in original component runs on every `mouseup` anywhere. Method `getDynamicItems()` is called number of times which replaces `ngFor` buttons.
I think when you click on the button button gets removed and replaced faster, than angular's `click` event happens, so angular's click event does not event fire.

**Comment by zoechi** [comment]
Sorry, but I won't spend more time investigating this further (I'm not on the Angular team) 
as long as the code binds to a method that returns a new array every time it's called, perhaps someone else.
If you can reproduce without such a construct, then I'd consider this a valid bug as well though.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
