### ISSUE TITLE
Resolved this issue with ng2-opd-popup: Error resolving....'Calling function 'makeDecorator'...

### ISSUE THREAD

**Issue by mensahGit** [angular/angular#17914]
In your tsconfig.json, add the following line to the enclosed json object:

**"paths": { "@angular/*": ["../node_modules/@angular/*"] }**

Hope this saves someone a few hours scouring the web.

All the Best,

**Comment by BeSeech** [comment]
Doesn't help :-/

**Comment by ELIDJEAKA** [comment]
Doesn't work

**Comment by aakritiOpallios** [comment]
@ELIDJEAKA I am also facing same issue ... did you get the fix of this issue ?

**Comment by ELIDJEAKA** [comment]
yes, In your tsconfig.app.json, add the following line to the enclosed json object:
"paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }

**Comment by ELIDJEAKA** [comment]
@aakritiOpallios 
yes, In your tsconfig.app.json, add the following line to the enclosed json object:
**"paths": {
"@angular/": [
"../node_modules/@angular/"
]
}**

**Comment by aakritiOpallios** [comment]
@ELIDJEAKA thanks it worked .. you saved my day

**Comment by abhijitcapital** [comment]
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",    
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }
  }
}

>> the solution is not work for me , please see my tsconfig.json file

**Comment by aakritiOpallios** [comment]
@abhijitcapital you need to change tsconfig.app.json file ... i think you are trying to change tsconfig.json ... change your tsconfig.app.json, add the following line to the enclosed json object:
"paths": {
"@angular/": [
"../node_modules/@angular/"
]
}
