### ISSUE TITLE
Child component inside ngIf

### ISSUE THREAD

**Issue by dsalodki** [angular/angular#17918]
<li *ngIf="...">
<my-app></my-app>

Message that tag unknown

Angular version: 4 latest

Browser:
- [ ] Chrome (desktop) version latest
 
For Tooling issues:
- Node version: latest
- Platform: Windows

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
