### ISSUE TITLE
aio: webpack guide style issue

### ISSUE THREAD

**Issue by PKief** [angular/angular#17912]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There's a wrong style behavior on the webpack guide. If you open [https://angular.io/guide/webpack](https://angular.io/guide/webpack) you can see that the content of the guide overlaps the toc-container on the right side. So it's hard to read that guide.

![image](https://user-images.githubusercontent.com/12248527/27803369-5a0eaa66-6029-11e7-9927-81b0dcbb08cf.png)

## Expected behavior
The text content of the webpack guide must not overlap the toc on the right side.

## Minimal reproduction of the problem with instructions

Open the webpack guide at [https://angular.io/guide/webpack](https://angular.io/guide/webpack) and look at the content and the toc on the right side of the page.

## What is the motivation / use case for changing the behavior?

A better readability of the webpack guide.

## Please tell us about your environment

Browser:
- [x] Chrome (desktop) version 59

**Comment by gkalpak** [comment]
cc @wardbell, @Foxandxss 
Shouldn't `guide/webpack` be is SideNav submenu? 😕

**Comment by Foxandxss** [comment]
Yes, definitely.

**Comment by aravindfz** [comment]
This is because of this [PR](https://github.com/angular/angular/pull/16459)  which removed the max-height property on the md-side-bar

**Comment by gkalpak** [comment]
@aravindfz, the issue is not related to that PR. As pointed above, the root of the problem is https://github.com/angular/angular/issues/17912#issuecomment-312868535 (which means that the guide should be included somewhere in [here][1]).

[1]: https://github.com/angular/angular/blob/master/aio/content/navigation.json
