### ISSUE TITLE
Codes Not Shown On CodePen

### ISSUE THREAD

**Issue by dennis-leeyinghui** [angular/angular#17911]
[](https://material.angularjs.org/latest/demo/gridList#responsive-usage)

I was trying to have a look at the sample codes. But nothing was shown after i pressed "Edit on Codepen" on those three examples.

**Comment by dennis-leeyinghui** [comment]
[Angularjs Org](https://material.angularjs.org/latest/demo/gridList#responsive-usage)

**Comment by Toxicable** [comment]
Wrong Repository, This is the Angular Repo.
It's not then AngularJS Material repo

**Comment by gkalpak** [comment]
@Toxicable is right. Please re-submit on the AngularJS Material repo: https://github.com/angular/material
