### ISSUE TITLE
QueryList.onChange callback never called

### ISSUE THREAD

**Issue by abakirov** [angular/angular#1792]
In example like this ...
```
@Directive({
    selector: "tab"
})
class Tab { }

@Directive({
    selector: "tabs"
})
class Tabs {
    constructor(@Query(Tab) tabs: QueryList<Tab>) {
        tabs.onChange(function () {
            debugger; //never called
        });
    }
}

@Component({
    selector: "my-app"
})
@View({
    template: "<tabs> <tab></tab> </tabs>",
    directives: [Tab, Tabs]
})
class App { }

bootstrap(App);
```

... `onChange` callback is never called using this version:
https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js

Please let me know if I'm doing something wrong or this is not supposed in alpha 22.

Thanks!

**Comment by jhades** [comment]
If tabs is a `@Component` instead of a `@Directive` then `@Query(Tab)` works, just tried a case like that in alpha-31 and it works fine. 

It seems that this does not work only if its a parent `@Directive`querying children directives.

**Comment by mhevery** [comment]
Can someone verify that this is still an issue.
/cc @rkirov

**Comment by jhades** [comment]
It seems this was fixed in alpha-35, I've retested this with a case similar to the tabs example and it no works (in alpha-34 it didn't).
