### ISSUE TITLE
Enter animations are not executed after router animations

### ISSUE THREAD

**Issue by theunreal** [angular/angular#17922]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
when trying to use view-init animations after router animation the view-init animation is not triggered (the content loads without any animation at all)

## Expected behavior
Execute view-init animations after the route animations ends

## Minimal reproduction of the problem with instructions
Router animations (app.components.ts)
```
animations: [
    trigger('routerAnimations', [
      transition('* => *', [
        useAnimation(routerAnimation)
      ])
    ])
  ]
```

My Component animation:
**about.component.html:**

```
<section class="mat-body-1" style="padding:20px" [@stagger]>

  <img src="https://coverfiles.alphacoders.com/608/608.jpg"/>

  <br>
  <h3 >About</h3>

  <p>Loren Ipsum Loren IpsumLoren IpsumLoren IpsumLoren IpsumLoren Ipsum</p>
  <p>Loren IpsumLoren IpsumLoren IpsumLoren Ipsum Loren IpsumLoren IpsumLoren Ipsum</p>
</section>
```
**about.component.ts:**
```
animations: [trigger('stagger', [
    transition('* => *', [
      query('p,img,h3', style({ opacity: 0, transform: 'translateX(-40px)' }), { optional: true}),

      query('p,img,h3', stagger('300ms', [
        animate('300ms 0.2s ease-out', style({ opacity: 1, transform: 'translateX(0)' })),
      ]), { optional: true}),

      query('p,img,h3', [
        animate(300, style('*'))
      ], { optional: true})
    ])
  ])]
```

- When navigating from HomeComponent to AboutComponent, the stagger animation is not triggered (the content is displayed right after the navigation ends)

- When refreshing the browser while in the AboutComponent page, the stagger animations works (elements are entering one by one).

I found a solution to this problem by adding *ngIf="loaded" to the [@stagger] element and adding the following code to my about.component.ts:
```
ngAfterViewInit() {
    this.loaded = true;
  }]
```

## What is the motivation / use case for changing the behavior?
Initial animate of a componen after a route animation ends

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.3
- Platform: Windows

**Comment by matsko** [comment]
@theunreal please test on 4.2.5. There was a fix that went in last week that addressed an issue with `:enter` elements.

**Comment by theunreal** [comment]
@matsko Thanks for your reply. I upgraded to 4.3.0-beta1 but it doesn't seem to solve the issue. when there is a router transition the stagger animation is not working.
The stagger animations works fine without a router animation.

**Comment by matsko** [comment]
OK. Is there any chance you can make a demo plnkr for me? It's hard for me to piece together a demo of this since I don't have all your application code.

**Comment by matsko** [comment]
BTW the animation code you have can be simplified to this:

```ts
    transition('* => *', [
      query('p,img,h3', [
        style({ opacity: 0, transform: 'translateX(-40px)' }), { optional: true}),
        stagger('300ms', [
          animate('300ms 0.2s ease-out', style({ opacity: 1, transform: 'translateX(0)' }))
        ]),
        animate(300, style('*'))
      ]), { optional: true}),
    ])
```

**Comment by theunreal** [comment]
@matsko Thanks about the simplification!

I just created a plunker for you: https://plnkr.co/edit/GwlgaO2YTInR6CuL9ay3?p=preview

Please click on the "Go to about page" button. It should navigate to the about page without triggering any stagger animation for the component elements.
Now change the animation value of the **about page** from `about` to `home` located in the `app.routing.module.ts`.

It will not trigger the router animation (state stays same - home -> home)
and the stagger will start working fine.

Please let me know if there is anything else,
Thanks!

**Comment by matsko** [comment]
Hey can you verify if this is still an issue? Since your plnkr example is using the latest Angular build this may have gotten fixed with a patch that went in yesterday into master that fixed another router animations issue.

**Comment by theunreal** [comment]
@matsko This is still an issue, when router animation executed the stagger won't work (just update app.routing.module.ts aboutComponent animation value to activate the route animation and the stagger will stop working)

**Comment by lionelB** [comment]
it is probably related to #19100

**Comment by matsko** [comment]
This should be fixed now and beta.3 will include it within its release.

c2b3792a3b5fa5215fe2ef7e0ac6511086ffe4c1
