### ISSUE TITLE
aio: ngFor is now ngForOf

### ISSUE THREAD

**Issue by DeborahK** [angular/angular#17921]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This section: https://angular.io/guide/structural-directives#inside-ngfor discusses how ngFor is sugar for *ngFor. However, as of v4, ngFor is deprecated and should be replaced in the docs with ngForOf.

## Expected behavior

Expect docs to be kept up to date with code changes to prevent developer confusion and to remain relevant.

## Minimal reproduction of the problem with instructions

View this section of the documentation: https://angular.io/guide/structural-directives#inside-ngfor

## What is the motivation / use case for changing the behavior?

Docs should be kept up to date.

## Please tell us about your environment

<pre><code>
Angular version: 4+

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Thank you. Good catch. 
https://v4.angular.io/api/common/NgFor
https://angular.io/api/common/NgForOf

This is somewhat pervasive in examples and includes the TOH Tutorial.

**Comment by DeborahK** [comment]
It was great meeting you last week! Thanks for looking into this.

It looks like someone already had fixed this.

The `*ngFor` didn't change. The underlying type `ngFor` (no asterisk) changed to `ngForOf`.

In the docs here: https://angular.io/guide/structural-directives it talks about how the `ngFor` is implemented under the hood.

> <div *ngFor="let hero of heroes; let i=index; let odd=odd; trackBy: trackById" [class.odd]="odd">
>   ({{i}}) {{hero.name}}
> </div>
> 
> <ng-template ngFor let-hero [ngForOf]="heroes" let-i="index" let-odd="odd" [ngForTrackBy]="trackById">
>   <div [class.odd]="odd">({{i}}) {{hero.name}}</div>
> </ng-template>

Notice the `ngForOf` here. So it looks like this was fixed. I'll close the issue.

**Comment by jenniferfell** [comment]
@DeborahK It was great meeting you, too! Thank you so much for your quick and clear clarification on this.  Bonus...it's fixed already. :-)
