### ISSUE TITLE
@ngtools/webpack AotPlugin hangs the process while bundling an AOT build

### ISSUE THREAD

**Issue by mtycholaz** [angular/angular#17925]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Settings up a simple AOT configuration hangs when including the AotPlugin in the tool chain. The result of excluding this plugin is that none of our `.scss` files are transformed correctly. For example scss variables ($variableName) are being included within the AOT output. eg 
`var styles = ['$color[_ngcontent-%COMP%]:   #a4b116[_ngcontent-%COMP%];\r\n$grade-cell-width[_ngcontent-%COMP%]:   200px[_ngcontent-%COMP%]; ...`

## Expected behavior
Including the AotPlugin should not hang the webpack process. If we remove the AotPlugin, it runs to completion. Including the ` --debug --display-error-details ` doesn't appear to make a difference.

## Minimal reproduction of the problem with instructions
1. `ng new angular-aot`
2. Rename `app.component.css` to `app.component.scss`, add some variables/styles (simple h2 with color background as a scss variable will do), and update the app.component.ts styleUrls to the new name (quickly do an ng serve as a sanity check).
3. Add a `tsconfig.aot.json` with the following config:
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "baseUrl": "src",
        "declaration": false,
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
            "es2016",
            "dom"
        ],
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,
        "typeRoots": [
            "./node_modules/@types/"
        ]
    },
    "exclude": [
        "./node_modules",
        "./**/*.e2e.ts",
        "./**/*.spec.ts",
        "./src/test.ts"
    ],
    "angularCompilerOptions": {
        "genDir": "./dist/aot",
        "skipMetadataEmit": true
    }
}
```
4. Run the following command to generate the AOT factories `ngc -p tsconfig.aot.json` 
5. Add a main.aot.ts file with the following configuration.
```
import { platformBrowser } from '@angular/platform-browser';
import { AppModule } from './app/app.module';
import { AppModuleNgFactory } from "../dist/aot/src/app/app.module.ngfactory";

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```
6. Run the following command to re-generate the AOT factories `ngc -p tsconfig.aot.json` 
7. Add a webpack.aot.config.js file with the following config:

```
const ngtools = require("@ngtools/webpack");
const webpack = require('webpack');

module.exports = {

    profile: true,
    devtool: false,
    entry: {
        'build': './dist/out-tsc/src/main.aot.js'
    },
    output: {
        path: __dirname + "/dist",
        filename: "[name]-aot.min.js",
        publicPath: "dist/"
    },
    resolve: {
        extensions: [
            '.ts',
            '.js', '.jpg', '.jpeg', '.gif', '.png', '.css', '.html']
    },
    module: {
        loaders: [
            { test: /\.scss$/, loaders: 'sass-loader' },
            { test: /\.css$/, loader: 'raw-loader' },
            { test: /\.html$/, loader: 'raw-loader' },
            { test: /\.ts$/, loader: '@ngtools/webpack' }
        ],
        exprContextCritical: false
    },
    plugins: [
        new ngtools.AotPlugin({
            tsConfigPath: './tsconfig.aot.json'
        }),
        new webpack.LoaderOptionsPlugin({
            minimize: true,
            debug: false
        })
    ]
};
```
8. Run the following command to bundle everything via webpack `webpack --debug --display-error-details --config webpack.aot.config.js` **Process never finishes, and never reports any errors**
9. Comment out the `new ngtools.AotPlugin({...})` in the `webpack.aot.config.js` file, and webpack will run to completion, as expected. Including the plugin results in the webpack process never finishing.

## Please tell us about your environment

<pre><code>
Angular version: 4.0.0
 
For Tooling issues:
- Node version: 8.0
- Platform: Windows

Others:
package.json file
{
  "name": "angular-aot",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compile": "ngc -p tsconfig.aot.json",
    "webpack:aot": "webpack --debug --display-error-details --config webpack.aot.config.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngtools/webpack": "^1.5.0",
    "core-js": "^2.4.1",
    "raw-loader": "^0.5.1",
    "rxjs": "^5.1.0",
    "sass-loader": "^6.0.6",
    "webpack": "^3.0.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
</code></pre>

**Comment by jusefb** [comment]
I am experiencing the same problem. Files get built and they work but the process never stops.

**Comment by chuckjaz** [comment]
Please report this to the [angular-cli](https://github.com/angular/angular-cli) project as the `AOTPlugin` is part of that project.
