### ISSUE TITLE
Animations broke after updating to 4.2.5

### ISSUE THREAD

**Issue by japalo** [angular/angular#17938]
## I'm submitting a ...

<pre><code>
[ X ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Animations that used to work now throws error:
`Failed to execute 'animate' on 'Element': Partial keyframes are not supported`

## Expected behavior
Animations shouldn't break on update i guess

## Minimal reproduction of the problem with instructions
I am animating a infinity-scrolled list with these animations:
```javascript
    animations: [
        trigger('state', [
            state('dim', style({
                opacity: 0.5,
                marginBottom: '-1.5rem',
                background: 'rgba(0, 0, 0, 0.2)'
            })),
            state('hide', style({
                display: 'none'
            })),
            transition(':enter',
                animate('250ms ease-in',
                    keyframes([
                        style({ transform: 'scale3d(1.02, 1.02, 1.02)', opacity: '0', offset: 0 }),
                        style({ transform: 'scale3d(1, 1, 1)', opacity: '1', offset: 1 })
                    ]),
                ),
            ),
            transition('* => hide',
                animate('350ms ease',
                    keyframes([
                        style({ transform: 'scale3d(1, 1, 1)', opacity: 1, offset: 0 }),
                        style({ opacity: 0, offset: 0.5 }),
                        style({ transform: 'scale3d(1.02, 1.02, 1.02)', opacity: 0, height: 0, offset: 1 })
                    ])
                )
            ),
            transition('* => dim',
                animate('500ms ease-out',
                    keyframes([
                        style({ opacity: 1, offset: 0 }),
                        style({ opacity: 0.5, 'background-color': 'rgba(0, 0, 0, 0.2)', 'margin-bottom': '-1.5rem', offset: 1 })
                    ])
                )
            ),
            transition('dim => *',
                animate('125ms ease-out',
                    keyframes([
                        style({ opacity: 0.5, 'background-color': 'rgba(0, 0, 0, 0.2)', 'margin-bottom': '-1.5rem', offset: 0 }),
                        style({ opacity: 1, offset: 1 }),
                    ])
                )
            ),
            transition('hide => show',
                animate('250ms ease-out',
                    keyframes([
                        style({ height: 0, opacity: 0, offset: 0 }),
                        style({ height: '*', opacity: 1, offset: 1 })
                    ])
                )
            )
        ])
    ]
```

## What is the motivation / use case for changing the behavior?
Animating multiple elements at the time seems to be the case. Something isn't catching up properly. Either the element isn't found or something else has changed with the animations.

The motivation kinda speaks for it self i guess, angular should be able to delegate multiple animations at the same time without crashing.

## Please tell us about your environment

<pre><code>
Angular version:
@angular/cli: 1.2.0
node: 7.6.0
os: darwin x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5

Browser:
- [ X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ X ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.6.0
- Platform: Mac

Others:
Using Angular-cli

**Comment by matsko** [comment]
@japalo any chance you could put all your code into a plnkr? I can then dive in an see what's breaking.

**Comment by japalo** [comment]
Here is a plunker: https://plnkr.co/edit/RXHi9q

**Comment by mikeeus** [comment]
I'm also having this issue with Angular ^4.3.0 and @angular/material 2.0.0-beta.8 when opening a dialog.

**Comment by japalo** [comment]
A fix seems to be on it's way if you look at the commits that @matsko provided. :) Now we wait for a release.

**Comment by mikeeus** [comment]
kk thanks @japalo. I'll just be patient then

**Comment by japalo** [comment]
As a temporary workaround i used these packages:
```
"@angular/animations": "~4.1.0",
"@angular/common": "~4.1.0",
"@angular/compiler": "~4.1.0",
"@angular/core": "~4.1.0",
"@angular/forms": "~4.1.0",
"@angular/http": "~4.1.0",
"@angular/platform-browser": "~4.1.0",
"@angular/platform-browser-dynamic": "~4.1.0",
"@angular/router": "~4.1.0",
"@angular/compiler-cli": "~4.1.0",
```

That fixed the issue for me while i am waiting.

**Comment by matsko** [comment]
@japalo a workaround for 4.3.x is to convert all your CSS properties from `hyphen-case` to `camelCase`.

The fix should go in tomorrow and the release should show up thurs/fri.

**Comment by japalo** [comment]
Oh, so that was the problem? Yikes. Using BEM syntax then really messes things up. It's too late for me to do that (literally thousands of lines of HTML/scss code). Will the fix support hyphen-case?

**Comment by matsko** [comment]
Yes the patch fixes it so that hyphen-case still works.
