### ISSUE TITLE
Router: redirectTo only allows string params on absolute paths

### ISSUE THREAD

**Issue by brumasribera** [angular/angular#17934]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
There is no way to pass string query params on router redirectTo on relative paths.

## Expected behavior
  {
    path: '**',
    redirectTo: 'list?param=true',
  }

## Minimal reproduction of the problem with instructions
It's a similar issue to the following one https://github.com/angular/angular/issues/9921, the fix was done but won't work for non-absolute paths.

## What is the motivation / use case for changing the behavior?
When being redirected I would like to alert somehow that we come from a redirection so that we apply a different configuration to the components.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4
Browser: all

**Comment by bennadel** [comment]
You might be able to use an optional route param instead of query param? Maybe something like:

```js
{
    path: "**",
    redirectTo: "list;param=true"
}
```

... this would then show up in the `paramMap`.

**Comment by SeanPrashad** [comment]
Hi there! I'd love to work on implementing this new feature if it's still available 😁

**Comment by jasonaden** [comment]
@SeanPrashad Still interested in working on this?

**Comment by SeanPrashad** [comment]
Yes please! I've been caught up with work but I'll give it a go in the next few days

**Comment by heinekeg** [comment]
I'll start working on this

**Comment by SeanPrashad** [comment]
Ah please go ahead @heinekeg!

**Comment by Gennady77** [comment]
I seem to have encountered a similar problem. What is the state of this issue?

**Comment by alxhub** [comment]
Closing as a duplicate / solved by #13373.
