### ISSUE TITLE
IE 11 setting input type="text" field to dirty on focus. Angular Reactive Forms

### ISSUE THREAD

**Issue by Vaaceph** [angular/angular#17930]

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and **ensure you provide all of the required information when filling out the issue template**.
