### ISSUE TITLE
Need separate Angular 2 help forum

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#1793]
The current forum at https://groups.google.com/forum/#!forum/angular is mixed with Angular1/2 stuff. This makes it hard to find help because you have to filter through a bunch of irrelevant posts. I tried adding "angular2" to my query but Google Groups seems to think the 2 is meaningless and matches "angular" anyways.

If there is already a new forum, then https://angular.io/docs/js/latest/help.html needs to be updated, because it points to the one linked above.

I searched and couldn't find the previous ticket I thought I'd seen about this, so I'm just throwing my thoughts in here. Sorry for the dupe.

**Comment by viztastic** [comment]
Agreed, an Angular 2 forum would be incredibly helpful. 
+1

**Comment by SekibOmazic** [comment]
@ewinslow You can get some help from gitter channel: https://gitter.im/angular/angular

**Comment by ewinslow** [comment]
Thanks, wasn't aware of that. Will try that next time.

I still think it would be useful to have a forum to serve as good reference material for others.

**Comment by naomiblack** [comment]
We don't have a separate Angular 2 forum, in part because we're not yet prepared to support a large volume of user questions. I've enabled tags on the group -- it's now possible to tag a post as "angular1" or "angular2". You can also enclose a search query in quotes to force a search for only "angular 2" not "angular" alone: https://groups.google.com/forum/#!searchin/angular/%22angular$202%22

**Comment by jomeier** [comment]
Maybe a FAQ would be a good idea for answering the most basic user questions?

**Comment by khalildiouriadservio** [comment]
please some one can help 
I need to send data from angular2 to server spring

if some one had already done it 
thanks

**Comment by rahulraics** [comment]
http://adf.ly/14939473/angualr2

**Comment by rahulraics** [comment]
https://adf.ly/14939473/angualr2

**Comment by rahulraics** [comment]
Hey guys I got some interesting video for angular 2 beginners http://adf.ly/14939473/angualr2.

**Comment by Abdul993** [comment]
Hey guys i need help in implementing web sockets into my signup and login page and i have done that already with http service i want combine both..
thanks in advance..

**Comment by Abdul993** [comment]
can any one please suggest me a good tutorial for angular 2 web-sockets apart from the web-sockets chat applications.
in need 
thanks in advance.

**Comment by DavidJones18** [comment]
I can recommend read the useful article abourt " Why Is Angular The Best Solution For Your 2018 Web App? " - https://softwaredevelopment.ae/angular-best-solution-2018-web-app/
Hope you can find very interesting information for you.

**Comment by VigneswaranMuruganandan** [comment]
how to allow user to add buttons to his text messages in angular 4?

**Comment by steven4489** [comment]
There's a course I can recommend: https://www.webagesolutions.com/courses/angular-2-training

**Comment by mlc-mlapis** [comment]
@babu0104 ... `the issue is size different` ... ??? ... what it means?

**Comment by babu0104** [comment]
HTML to PDF conversion

**Comment by mlc-mlapis** [comment]
@babu0104 ... how is it related to Angular?

Btw ... are you surprised that Base64 encoding is larger?

**Comment by babu0104** [comment]
@mlc-mlapis : Exactly

**Comment by babu0104** [comment]
@mlc-mlapis : Everything is working for me but only thing is how to set dynamic image width
