### ISSUE TITLE
aio: mobile - cache window history & restore on start

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17946]
**Problem:**

App doesn't remember where you were when you relaunch. 

This is especially annoying on iPhone when docviewer is a "home screen app" because, if you switch to another app and switch back, the app restarts on the home page, having forgotten what you were looking at. No real app does that.

Remembering where you were would be nice in any browser.

**Solutions:**

The docviewer can stash the window history to browser local storage (exists on iPhone whereas service worker does not). Can rebuild on launch with `history.pushState`

**Comment by petebacondarwin** [comment]
Something that the Angular Module Toolkit could help with - it seems like a common use case... @alxhub ?

**Comment by IgorMinar** [comment]
We tested this on ios and android when the app is added to the homescreen.

The current behavior is that every time you start the app by taping on the homescreen icon, you get a new instance of the app loaded at the homepage, unless the existing instance is currently opened at the same url as the url stored in the homescreen shortcut.

If we were to change the pwa manifest honored by android to run the app in the fullscreen mode, we'd reopen the app at the last state by reusing the old instance, but we'd prevent users from having multiple instances of the app open concurrently. Maybe this is what we want - we should consider the pros and cons.

Always restoring the old state using an indexdb might also turn out to be undesirable as it willresult in duplicate app instance with the same content open without the user realizing it.

My preference would be to not change the behavior for ios and wait until they support fullscreen, and on android go to the fullscreen mode, but add an ability to share the current url.

**Comment by dylhunn** [comment]
Since Igor's comment, the behavior has changed. The app remember its scroll position between launches on both Android and iOS.
