### ISSUE TITLE
perf(forms): aot generates significant amount of code for each control instance in template

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#17949]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Everything seems to be working as expected, but I wanted to point out a use case that I think is worth optimizing in the compiler or elsewhere. In one of our clients' applications, the AOT version is more than twice as large as the non-AOT version. The main culprit seems to be the code generated from form directives (particularly `DefaultValueAccessor`). For every instance of a form group or control in a template, about 1.3KB is added to the minified bundle. For an application with 20 forms and 15 controls in each form, this would mean an additional 390KB in the minified bundle. 

Gzip certainly improves things since the code is pretty repetitive, but the size is still significant, and gzip doesn't help JS parsing time.

## Expected behavior

It would be nice if the code could be de-duplicated.

## Minimal reproduction of the problem with instructions

1. Check out this repository built with Angular CLI: [https://github.com/jeffbcross/repro-form-aot-bloat](https://github.com/jeffbcross/repro-form-aot-bloat)
1. `$ yarn`
1. Just build with ngc: `./node_modules/.bin/ngc -p src/tsconfig.json`
1. Look at `out-tsc/app/app/app.component.ngfactory.js`
1. Look at the generated code for `View_AppComponent_0` to see repetition
1. Build minified w/CLI: `ng build --prod`
1. Record size of `dist/main.bundle[hash].js`
1. Comment out control2 and control3 in `src/app/app.component.html`
1. Build minified w/CLI: `ng build --prod`
1. Compare size of `dist/main.bundle[hash].js` with bundle size when all controls are present

Or just trust my numbers for main.bundle.js:

State | Flag | Bytes | Bytes gzip 
------|-----|-------|-----------
Fresh checkout | --prod | 7883 | 1831
Comment out whole template, incl. form group | --prod | 2626 | 1074
Fresh checkout | --aot | 40111 | 5294
Comment out 1 control | --aot | 34931 | 5142
Comment out 2 controls | --aot | 29635 | 4805
Comment out all 3 controls | --aot | 24374 | 3997
Comment out whole template, incl. form group | --aot | 21209 | 3390

## What is the motivation / use case for changing the behavior?

Smaller, faster-parsing bundles for apps with many form controls.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5

</code></pre>

**Comment by jeffbcross** [comment]
@robwormald pointed out one simple way to reduce generated code is to use `*ngFor` to stamp out controls, in cases where forms are simple enough for that to work.

**Comment by mhevery** [comment]
This is resolved by ivy and because it is now default I am closing it.
