### ISSUE TITLE
Provide "send feedback" feature for the docs at angular.io

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#1794]
There's no link to report a problem or "improve these docs" from the docs pages themselves. Something like this along the lines of what Google does with screenshots and stuff would be helpful, methinks, for making sure all the docs stay up to date as Angular evolves right now.

**Comment by joshkurz** [comment]
so someone needs to send a PR that improves the docs to improve the docs? Self Improvement.

**Comment by joshkurz** [comment]
Just for the record I totally agree with you @ewinslow.

**Comment by naomiblack** [comment]
This is in the plan for 1.0 and overall support, but unfortunately it will be some time before we get around to docs infra while we focus on the developer preview and core features of the API. In the meantime, you can file issues and submit docs PRs at github.com/angular/angular.io
