### ISSUE TITLE
application breaks when routing accessed from a browser notification

### ISSUE THREAD

**Issue by Neverminder** [angular/angular#17954]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Application breaks when a URL is accessed with `router.navigateByUrl` by clicking browser notification. When the same URL is accessed in any other way everything works fine.

## Expected behavior
Application shouldn't break when accessed from browser notification.

## Minimal reproduction of the problem with instructions
The bug is reproduced in this repository: https://github.com/Neverminder/quickstart

Steps to reproduce expected behavior:
1. Launch the application opening url `/home`
2. Click the "Go to test" button
3. Observe dropdown working on the page `/test`

Steps to reproduce the bug:
1. Launch the application opening url `/home`
2. Click the browser notification that appears
3. Observe dropdown not working and previous component also appearing making the page broken, errors in the javascript console

## What is the motivation / use case for changing the behavior?
The bug should be fixed, otherwise browser notifications are rendered useless with Angular.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Neverminder** [comment]
@IgorMinar @jasonaden Any news about a fix for this bug? It's been a while. Will it be fixed at all?

**Comment by atscott** [comment]
Confirmed in v9 with Ivy on stackblitz: https://stackblitz.com/edit/angular-ivy-btzuuo?file=src%2Fapp%2Fcomponents%2Ftest.component.ts
