### ISSUE TITLE
Angular Reactive Form, in IE 11 input type="text" field get sets to dirty on focus. 

### ISSUE THREAD

**Issue by Vaaceph** [angular/angular#17955]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Issue here is that when you use placeholder and open reactive form on IE , field gets dirty as soon as you focus on it. and due to it validations runs and it creates bug.

## Expected behavior
IE should not set field to dirty, it is working fine on Google Chrome

## Minimal reproduction of the problem with instructions
Check following plnkr to see the bug, first run it on chrome it is working fine then run plnkr on IE u will see the difference and bug.
http://plnkr.co/edit/7JF7UWS2B4EDSgtVP2a3?p=preview

## Please tell us about your environment

<pre><code>
Angular version: 4.0.0

Browser:
- [x] Chrome (desktop) any version support by Angular
- [x] IE version 11

**Comment by himajasuman** [comment]
@Vaaceph this is happening because, 
- "input" event is triggered on focused on an empty input element 
- which calls registerOnChange 
- registerOnChange then calls markAsDirty

This issue is related to https://github.com/angular/angular/issues/17951 I tried debugging ngModel directive but could not find why "input" event is triggered :\

**Comment by Vaaceph** [comment]
@himajasuman , How can I tell angular team to see this bug?

**Comment by mhevery** [comment]
dup of #17951
