### ISSUE TITLE
Failing to denote the local variable in *for="field of fields" should give some kind of error

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#1795]
I was beating my head against the wall trying to figure out what I was doing wrong because this clearly was not unrolling my loop.

`*for="field of fields"` of course needs to be `*for="#field of fields"`  >_<

Silently failing here seems bad. The for directive should at least check at runtime that it is receiving a valid variable declaration and throw if not. I'll leave it to you all to figure out how to send back useful line numbers and such ;)

**Comment by vicb** [comment]
Discussed this with @tbosch, we would need to catch the error at compile time (we don't want to wait for the template to be instantiated) so we probably need to add more metadata to the `Directive`.

**Comment by ewinslow** [comment]
Sounds good! Thanks for looking into it!

**Comment by vicb** [comment]
Should be adressed by https://github.com/angular/angular/issues/2014

**Comment by ewinslow** [comment]
Closing this as duplicate. Reopen if you think we need to...
