### ISSUE TITLE
NGSwitch Doesnt Work With NG-Template Without Warning

### ISSUE THREAD

**Issue by saniyusuf** [angular/angular#17961]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behaviour
When using NGSwitch, I try to wrap each switch case inside a div or Ng-Container for readability. Now this works with ng-container but when you use ng-template it doesn't render and there are no warnings. 

## Expected behaviour
The correct behaviour should be that it should work or that there should be an error thrown by Angular to state that you should use ng-Container instead. 

## Please tell us about your environment

<pre><code>
Angular version: 4.1.3

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform:

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by saniyusuf** [comment]
@vicb Hi Man This is a feature request, not a support ticket. It's a real problem because the code should give out a template error. But it does not.
