### ISSUE TITLE
jsdom and Angular

### ISSUE THREAD

**Issue by mrv777** [angular/angular#17963]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
jsdom is needed for another module that I load in my Angular 4 project.  However, when as soon as I try to start using it I get this error:
<pre><code>
WARNING in ./~/jsdom/lib/jsdom/utils.js
216:21-40 Critical dependency: the request of a dependency is an expression

WARNING in ./~/jsdom/lib/jsdom/living/xmlhttprequest.js
20:23-30 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/jsdom/~/escodegen/~/source-map/lib/source-map/source-map-generator.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/jsdom/~/escodegen/~/source-map/lib/source-map/source-map-consumer.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/jsdom/~/escodegen/~/source-map/lib/source-map/source-node.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/jsdom/~/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression

WARNING in ./~/jsdom/~/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression

WARNING in ./~/jsdom/~/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression

ERROR in ./~/jsdom/lib/jsdom/living/xmlhttprequest.js
Module not found: Error: Can't resolve 'child_process' in '/home/xxx/client/node_modules/jsdom/lib/jsdom/living'
 @ ./~/jsdom/lib/jsdom/living/xmlhttprequest.js 4:18-42
 @ ./~/jsdom/lib/jsdom/browser/Window.js
 @ ./~/jsdom/lib/jsdom.js
 @ ./~/ardor-blockchain/nrs.node.bridge.js
 @ ./src/app/home/home.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://192.xxx.xxx.xxx:22222 ./src/main.ts
webpack: Failed to compile.
</code></pre>

jsdom said to ask here: https://github.com/tmpvar/jsdom/issues/1812

## Expected behavior

I was expecting webpack to compile fine :)

## Minimal reproduction of the problem with instructions
Include the module from these developers: https://nxtforum.org/general-discussion/ardor-node-js-module/msg229979/#msg229979

Then in my home component I do
```
import * as loader from 'ardor-blockchain';
```
and
```
  	loader.init({
	    url: 'http://107.170.3.62:26876',
	    secretPhrase: 'hope peace happen touch easy pretend worthless talk them indeed wheel state',
	    isTestNet: true,
	    chain: '2'
	});
```

## Please tell us about your environment
<pre><code>
Angular version: 4.2.5

Browser:
- All
 
For Tooling issues:
- Node version:v7.8.0
- Platform: Linux
</code></pre>

**Comment by ericmartinezr** [comment]
>I don't know much about webpack and it's not really supported with jsdom, so you're better off filing a bug on the **webpack repo**.

This is angular repo

**Comment by IgorMinar** [comment]
I'm sorry but this issue is not caused by Angular. Please contact the author(s) of webpack or file issue on their issue tracker.
