### ISSUE TITLE
Validators.pattern() erroring out. 

### ISSUE THREAD

**Issue by EliCDavis** [angular/angular#17968]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using Validators.pattern on seemingly any pattern errors out.

## Expected behavior

proper form validation with an error object being returned, application not to break.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/rZ50yauqTN7nzb96UCnr?p=preview

When you have the plunkr loaded, open up the console. I coppied one of your tests from [here](https://github.com/angular/angular/blob/master/packages/forms/test/validators_spec.ts#L251), which seems to do it's job.  Although when you type into the input box the console will begin to flood with *actual* errors.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5

Browser:
- [x] Chrome (desktop) version 58
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 54
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
That's because the third option should be an async validator. So to fix your issue can be solved by passing an array as a the second option, like

```
ip: ['', [Validators.required, val]]
```
Although I agree that the error message could give more clues about what's happening. You can see the [FormControl constructor](https://angular.io/api/forms/FormControl) signature.

**Comment by tytskyi** [comment]
http://plnkr.co/edit/ej4ulw95TVShJpe9Y1mG?p=preview

**Comment by EliCDavis** [comment]
Welp, that's embarrassing thanks for the quick reply! Keep up the good work!
