### ISSUE TITLE
Do not trigger change detection in $http responses when useApplyAsync is enabled

### ISSUE THREAD

**Issue by kseamon** [angular/angular#17975]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When $httpProvider.useApplyAsync is enabled (with the intent of reducing the number of dirty check cycles) in an NgUpgraded application, it has the opposite effect. The NgZone triggers a dirty check for each $http response as well as by the timer meant to coalesce to a single dirty check.

## Expected behavior

When useApplyAsync is enabled, XMLHttpRequests in $http should be executed outside of the Angular zone. The async call to $apply should then be run inside the Angular zone.

## Minimal reproduction of the problem with instructions
1) At startup, enable useApplyAsync in the $httpProvider.
2) Make multiple requests with $http.
3) Observe that each request results in a separate dirty check cycle in addition to another cycle after timeout.

## What is the motivation / use case for changing the behavior?

Bringing startup time of NgUpgraded Angular.js applications back in line with vanilla Angular.js.

## Please tell us about your environment
A reasonably large AngularJS codebase with NgUpgrade+Angular recently added.

<pre><code>
Angular version: all

Browser: all

Others:
If implemented, https://github.com/angular/angular.js/issues/16089 would provide a nice way of implementing this fix.

**Comment by gkalpak** [comment]
Interestingly, with have been thinking about removing `useApplyAsync` (since it shouldn't make any actual difference in AngularJS apps (see angular/angular.js#13128).

@kseamon, would it be possible to achieve the same thing using a custom [$xhrFactory][1]?

[1]: https://docs.angularjs.org/api/ng/service/$xhrFactory

**Comment by kseamon** [comment]
@gkalpak I'm trying to understand 13128 - is it that it doesn't work right now or it will always be enabled?

**Comment by gkalpak** [comment]
@kseamon: It seems that using the `useApplyAsync` flag has no real effect, because essentially it is always "on" (due to how `$q` promises work in AngularJS). So, we were thinking about removing the flag (and keeping the current behavior which is always async anyway).

Have you observed any difference (in a pure AngularJS app) with and without `useApplyAsync`?

**Comment by kseamon** [comment]
Last time I tested was a long time ago when the feature was first introduced (and an experimental version I made before then that was never merged).

The main issue for me now is that zones seem to cause dirty checking to happen on every response regardless of the setting.

**Comment by gkalpak** [comment]
Yeah. I think the excessive digesting comes from Zone.js' patching XMLHttpRequests. (So not directly related to `useApplyAsync` or not.)

Using the new, experimental [`downgradeModule`][1] (docs forthcoming - sorry) should avoid that (but might break other things if you rely on Zone.js triggering digests). 

[1]: https://github.com/angular/angular/blob/b582e2b311a42a8ead96da7a5317626f80a89246/packages/upgrade/src/static/downgrade_module.ts

**Comment by kseamon** [comment]
Yes - my intent was to run the requests outside of the zone then re-enter it after the async

**Comment by JiaLiPassion** [comment]
@kseamon , could you provide a reproduce repo? I would like to check the `zone.js` part.

**Comment by petebacondarwin** [comment]
Closing due to lack of response.
