### ISSUE TITLE
Automatic routing based on folder structure

### ISSUE THREAD

**Issue by feng-xiao** [angular/angular#17970]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Require manually setup routes

## Expected behavior

Automatically create routes based on folder structure.

## What is the motivation / use case for changing the behavior?

It's easier for developer to work on pages without thinking how to create routes.
e.g. with following folder structure, the angular-router will create url **/abc/xyz** 
`/abc/xyz.router-component.ts`

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [x] Edge version 40
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Toxicable** [comment]
Making Routes based on folder structure is very restrictive. For example how would you handle things like: LazyLoaded routes, Redirects, pathMatching type, canActivate, canDeactivate, outlet handling, etc and all the other config that routing requires

**Comment by feng-xiao** [comment]
@Toxicable some of config you mentioned (canActive, canDeactive, etc.) can be done through decorator in the *.router-component.ts file. we can have separate config file for LazyLoaded config.

**Comment by IgorMinar** [comment]
A change like this make the whole project incomprehensible by all the existing tooling (tsc, dgeni, karma, IDEs). I don't expect we'd like to head in this direction. Instead, I I'd like us to leverage ES modules better in the future and do away with NgModules, but that's not an easy undertaking and will take some time to spec out and implement.
