### ISSUE TITLE
Run outside of Angular zone when invokeApply is false

### ISSUE THREAD

**Issue by kseamon** [angular/angular#17973]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Despite an explicit opt out of change detection, $timeout and $interval still trigger change detection via the Angular zone.

## Expected behavior

When invokeApply is specified, the call to setTimeout/setInterval runs outside of the Angular zone and change detection does not occur. 

## Minimal reproduction of the problem with instructions
Call $timeout or $invokeApply with the invokeApply argument set to false.
Observe that Angular and AngularJS change detection has occured.

## What is the motivation / use case for changing the behavior?

We would like our AngularJS codebase to remain performant as we migrate to Angular via NgUpgrade

## Please tell us about your environment
A mostly AngularJS app with NgUpgrade+Angular recently introduced.

<pre><code>
Angular version: all

Browser:
all
 

Others:
If https://github.com/angular/angular.js/issues/16089 is implemented, it would be straightforward to build this fix on top of it.

</code></pre>

**Comment by Toxicable** [comment]
Could you please make a minimal reproduction to show this issue. Preferably in Plunkr, here's a template to get you started: https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by gkalpak** [comment]
For `$interval`, wouldn't just mean changing [this line][1] to something like:

```diff
-setTimeout(() => { this.ngZone.run(() => fn(...args)); });
+const skipApply = angular.isDefined(invokeApply) && !invokeApply;
+const callback = () => fn(...args);
+setTimeout(() => { skipApply ? callback() : this.ngZone.run(callback); });
```

[1]: https://github.com/angular/angular/commit/269bbe0e7d20d40c1f89f69d017360f82e94def3#diff-7b94402d554ad5b4fd57455276d67454R210

**Comment by gkalpak** [comment]
@kseamon: SGTM :grin:

**Comment by gkalpak** [comment]
Given the low demand for this feature and the fact that there is a work-around available, I am going to close this.
