### ISSUE TITLE
Conditionally remove NgModules from workflow

### ISSUE THREAD

**Issue by curlyfro** [angular/angular#17976]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## What is the motivation / use case for changing the behavior?

i understand the idea behind NgModules but there should be a way to opt out of this.  too much plumbing,  too much ceremony -- especially for big apps.  even for small apps -- if i don't care about lazy loading, why should i care about NgModules?  recently, some of my team members have been playing with React.  same core concepts but a lot less plumbing.  after years of angularjs development and an early adopter of angular2, we're considering abandoning angular :(

are you considering easing the development process?

## Please tell us about your environment

<pre><code>
Angular version: 4.2.x

**Comment by Toxicable** [comment]
What specifically don't you like about NgModules? Can you give an example?
How would you logically group your applications features without it?
How would you import Libraries? 1 component at a time?

**Comment by curlyfro** [comment]
if i have a small app, i don't care about logically grouping features.  i should import my component, angular should see my custom tag and recursively discover it's dependencies, etc like the way React does.

and it's even more painful if i have a larger app.  nowadays, even most moderately sized desktop web apps don't need lazy loading.

**Comment by Toxicable** [comment]
Import the component where?
Recursively look through what? React uses JSX, Angular does not.
While you may not care about grouping features and have well organized project structure I personally do and I don't think that your opinion is not the majority here.
Please explain how larger apps need lazy loading less? The goal of lazy loading is to reduce initial bundle size, but lazy loading parts of your application you can reduce this initial bundle substantially, improving loadtimes and user experience. Larger applications have more code, which means larger bundles and the more need to reduce their bundle size, therefore lazy loading is exactly what they need.

**Comment by curlyfro** [comment]
huh? what?  why you making this complicated?

given your angular html template, you should be able to parse and find custom tags, find those custom tag selectors in your 'import's and recursively pull in what you need.  i never said i don't care about well organized code.  i'm a big fan.  however, there have been times, when i either want to (1) prototype something, (2) decide to be lazy, (3) small project, etc, and i don't want to go through the plumbing.  i can't tell you how many times i've created a page and forgot to declare a custom component -- and that's because it's not a natural process.

i know what JSX is -- what's your point?

who said anything about needing lazy loading less for larger apps?  i thought i implied you don't need lazy loading for small desktop apps.

anyway, i hope the process gets streamlined and hope to hear from a core member.

**Comment by mlc-mlapis** [comment]
Hmm, I simply don't understand why NgModule concept is so big problem for you. Yes, it adds some lines of code but there are also advantages on the other side. From the general point of view of the whole app it is just so small thing to add ... and the argument about frequent forgetting to add a custom component to the declaration ... you can't think it seriously.

**Comment by vicb** [comment]
We might make NgModule optional for small apps.
