### ISSUE TITLE
EventEmitter error with alpha.22

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#1797]
Updating an app based on `ng2-play` from alpha 20 to 22, I'm having the following error on every screen with a `Control`:

    TypeError: Cannot read property 'Subject' of undefined
      at new EventEmitter (http://localhost:9000/lib/angular2.js:14930:46)

These lines are the problem : 

    this._subject = new Rx.default.Rx.Subject();
    this._immediateScheduler = Rx.default.Rx.Scheduler.immediate;

As there is no `Rx` property for `default`.

It looks like this was introduced by https://github.com/angular/angular/blame/master/modules/angular2/src/facade/async.ts#L88-L94

The easy way to fix it is to directly access `Subject` on `default`, but I might be missing something.

    this._subject = new Rx.default.Subject();
    this._immediateScheduler = Rx.default.Scheduler.immediate;

Maybe @alexeagle has an idea about this ?

**Comment by cexbrayat** [comment]
It looks like it is related to https://github.com/systemjs/builder/issues/123 

If I force the autodetection with : 
```
var buildConfig = {
    paths: {
      "angular2/*": "node_modules/angular2/es6/prod/*.es6",
      "rx": "node_modules/angular2/node_modules/rx/dist/rx.js"
    },
    meta: {
      'rx': {
        format: 'cjs'
      }
    }
  };
```

then the problem disappear.

@alexeagle @rkirov is this the proper fix and not an issue with Angular ?

**Comment by cexbrayat** [comment]
I'll close the issue, as @SekibOmazic ended up on the same workaround for rx autodetection, and it works for him too.

**Comment by rkirov** [comment]
https://github.com/angular/angular/blob/master/gulpfile.js#L682 we already use this for our bundles. Right now the only officially supported workflows are through the bundles (as we are still in dev preview). When we are ready for custom builds of angular + your app, we will have to document or deal somehow with such special steps.
