### ISSUE TITLE
Docs: Need warning about using detectChanges()

### ISSUE THREAD

**Issue by jdhines** [angular/angular#17986]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In the [Automatic Change Detection](https://angular.io/guide/testing#automatic-change-detection) section of the Testing docs, it states that you can use `ComponentFixtureAutoDetect`, and then at the end of the section say:

> Rather than wonder when the test fixture will or won't perform change detection, the samples in this guide always call detectChanges() explicitly. There is no harm in calling detectChanges() more often than is strictly necessary.

However, if you're testing things that are set in `ngOnInit` and you use Auto Detect, or if you have `fixture.detectChanges` in `beforeEach()`, changes will not be detected in the test.

## Expected behavior
The docs should mention that you shouldn't use both Auto Detect or `detectChanges` in `beforeEach()` AND `detectChanges` in the test itself.

## Minimal reproduction of the problem with instructions
[This post](https://stackoverflow.com/questions/42184545/angular-2-unit-test-service-stub-value-does-not-change) on StackOverflow exactly demonstrates the issue I saw when working through the Testing docs

## What is the motivation / use case for changing the behavior?
Not spending time wondering why tests aren't working when trying to recreate the code from the docs (not just copying/pasting example code)

**Comment by vikerman** [comment]
This is a very corner case (changing a deep property of an injected parameter). While trying to explain this I think we might actually confuse 99% of our other users.

I think `autoDetectChanges` is clear enough name that developers shouldn't feel like it should re-initialize the component every time(running the constructor and `ngOnInit` again).
