### ISSUE TITLE
How can I remove the component wrap html tag??

### ISSUE THREAD

**Issue by lazaro3487** [angular/angular#17987]
Hello everyone on that list. 

Is there any way to remove the <ng-component> html wrapper tag to one component, becaouse that tag breaks my css.

I need a component without a html tag wrapper.

Regards.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

PS: Google ng-container
