### ISSUE TITLE
Document what is <ng-content> tag and how content projection works

### ISSUE THREAD

**Issue by tomchinery** [angular/angular#17983]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
As per https://github.com/angular/angular.io/issues/3099 searching for ng-content on https://angular.io/docs/ts/latest/ doesn't produce any useful results and there doesn't seem to be any detailed description about what it is and how it works.

## Expected behavior
As per https://github.com/angular/angular.io/issues/3099 these points should probably be documented: 
- projection just moves nodes from one place to another, which leads to following conclusions:
  - not possible to use projected content multiple times ([link](https://github.com/angular/angular/issues/13894#issuecomment-272557621))
  - projected nodes/components, will be always created, even if you wrap them into ```*ngIf```, e.g: ```<div *ngIf="false"><ng-content></ng-content></div>```. It is reason for problems in https://github.com/angular/angular/issues/13760 and https://github.com/angular/angular/issues/13921. ([link](https://github.com/angular/angular/issues/13921#issuecomment-272557367))
  - when using ```ViewEncapsulation.Emulated``` (and probably ```Native``` as well?) projected nodes will have encapsulation of the place, where they were created and not where, they are projected
- how to query only subset of nodes using ```<ng-content select="<selector>">```
  - document, that only top-level nodes can be selected by this approach
- document a recipe with template, Tobias referring [here](https://github.com/angular/angular/issues/13059#issuecomment-264598276) to created projected nodes only when they are needed

## Minimal reproduction of the problem with instructions
Search for ng-content on https://angular.io/docs/ts/latest/

## What is the motivation / use case for changing the behavior?
It creates a lot of confusion for users, see:
- https://github.com/angular/angular/issues/13760
- https://github.com/angular/angular/issues/13894
- https://github.com/angular/angular/issues/13921
- https://github.com/angular/angular/issues/12639
- https://github.com/angular/angular/issues/13059

## Please tell us about your environment
N/A

**Comment by cgatian** [comment]
> not possible to use projected content multiple times
Kindly, please include reasoning to why this is intended

**Comment by devoto13** [comment]
@cgatian Because "projection just moves nodes from one place to another". It takes DOM nodes and puts them into new location in the tree. No less, no more ;) 

If you need to use nodes multiple times, you should try projecting `<ng-template>`/passing `TemplateRef` as parameter and rendering it using `ngTemplateOutlet` the amount of times you need.

**Comment by ghetolay** [comment]
I'm encountering lots of peoples using `ng-content` with structural directive and not understanding why it doesn't work.
So I agree that dedicated page doc for `ng-content` would be really nice but I also think that a compiler warning/error could help too.

**Comment by youdz** [comment]
If it helps, I just published a blog post explaining the various edge cases of `<ng-content>`: https://medium.com/claritydesignsystem/ng-content-the-hidden-docs-96a29d70d11b

Some of it can serve as a starting point for the future docs, feel free to use anything you want or like in there. 👍

**Comment by devoto13** [comment]
Also note https://github.com/angular/angular/issues/18691. The behavior, when projecting into `<ng-template>` may change in the future.

**Comment by shairez** [comment]
@devoto13 if I understood #18691 correctly there's a difference between @youdz blog post which suggests that the user will supply the `<ng-template>` rather than hide it in the "shadow dom" of the component.

**Comment by devoto13** [comment]
@shairez #18691 was not implemented, but rejected.

So @youdz's blog post correctly [describes](https://medium.com/claritydesignsystem/ng-content-the-hidden-docs-96a29d70d11b#607f) current behavior. Users will have to wrap projected content into `<ng-template>` or add `*starDirective` (which essentially wraps content into `<ng-template>`) on the client side to allow this content to to be instantiated multiple times or instantiated dynamically after projection.

**Comment by carusog** [comment]
@youdz should be invited to write documentation on the official site. His article is clear and well written, with real world examples that makes the subject very easy to be understood.
That's not always the case with the official documentation.

That said, any advancement on the issue? **Can we help** with the documentation?

**Comment by jenniferfell** [comment]
@youdz and @carusog I'm so sorry for letting this sit for so long. Now that we're past v6, we're returning to open issues. 

Yes, we'd welcome help with the documentation--if you're still interested. Is there anything I can do to help you get started? :-)

**Comment by carusog** [comment]
Hi @jenniferfell thanks for your support. Is there any guide or some guidelines for writing documentation?

**Comment by tuuling** [comment]
Still nothing on this?

I actually got worried that ng-content was not supported in newer versions of angular because it is hardly mentioned anywhere in the docs. It's weird that you keeping pushing new versions of angular without updating the docs. What's even more surprising is that very few people seem to care.. makes me think that hardly anyone uses angular outside of Google anymore?

**Comment by emilio-martinez** [comment]
@tuuling

> What's even more surprising is that very few people seem to care.. makes me think that hardly anyone uses angular outside of Google anymore?

Not sure what makes you draw that conclusion 🤔

Can't speak for everybody outside of Google, but I can take a guess as to why this hasn't been a big deal externally—quite simply `<ng-content>` is pretty much [`<content>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/content) from Shadow DOM v0. There's not much else to it.

If it's replaced with anything, it's likely to be replaced with something like `<ng-slot>` which would, again, be simply mirroring [`<slot>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot) from Shadow DOM v1—but that hasn't happened yet. If it does, I'm sure it'll go through the same deprecation policy as every other part of Angular's API.

**Comment by mlc-mlapis** [comment]
@tuuling ... hmm, the reality is that all the fundamental docs about `<ng-content>` in Angular is just one simple rule. If you know it (and it doesn't matter how did you get it) you have a tendency to suppose that it's so simple that anybody else has to know it. I am talking about my own feeling ...

**Comment by pauldraper** [comment]
@mlc-mlapis it's more than one simple rule. Like ngProjectAs and select.

**Comment by tuuling** [comment]
Last time I checked the "select" property was not even mentioned in the official docs. https://medium.com/claritydesignsystem/ng-content-the-hidden-docs-96a29d70d11b I found about it in here under "Targeted projection"

**Comment by AlexA-1976** [comment]
Please, Angular team document this.

**Comment by jacobweber** [comment]
This would really be helpful. There are thousand blog posts that do a bad job of explaining this, but no official documentation.

**Comment by Splaktar** [comment]
This is very much on the docs team's radar. Please add your 👍  to the OP to indicate your support for documenting this.

**Comment by tuuling** [comment]
> This is very much on the docs team's radar. Please add your 👍 to the OP to indicate your support for documenting this.

This issue is 5 days older than my firstborn daughter. Also GoT season 7 was not even out then.
A lot ofexpectationss were set, but this ticket still has not delivered.

**Comment by Splaktar** [comment]
@tuuling there are a lot of competing priorities and limited resources that the team has to deal with. Not everything can be the highest priority unfortunately. We are working hard to better enable and streamline community contributions to help us keep up with the backlog.

I hope that both you and your daughter are staying safe and healthy during these difficult times.

**Comment by dannymcgee** [comment]
This is not a criticism (I know there's a lot of work to do and a lot of competing priorities), just a funny observation:

I've been using Angular full-time for a year and a half. I've built two custom UI libraries from scratch (4 if you count my unfinished side projects). I've built more components, directives, pipes and services than I can count. I have a copy of this repo and `@angular/components` cloned to my machine for ease of reference when I need to dive into the weeds. I've built custom schematics and even a custom build system with `@angular-devkit`. 

I was today years old when I learned that `ngProjectAs` is a thing.

**Comment by aikidave** [comment]
Hi everyone!

I know this issue has been a long time coming. I have finally created a PR to provide (or start to provide, perhaps) documentation for content projection in Angular. It's currently available here: https://github.com/angular/angular/pull/41143.

There were some competing priorities when I joined the team last year; but I'm still sorry this has taken so long.  And, FWIW, I found @youdz medium article fantastic!

**Comment by aikidave** [comment]
Just an update! PR 41143 has been merged. We now have an official topic on [content projection](https://angular.io/guide/content-projection)! 

I fully expect that we'll need to expand on this topic over time, but I hope you'll all find this topic a good first step--one that hopefully will help other developers understand this feature better and more easily!
