### ISSUE TITLE
[Feature Request] Responsive documentation on angular.io

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#17991]
When reading the documentation it's necessary to scroll from left to right to see the end of the line.  Attached screen shot.  I've created a set of [layout utilties](https://github.com/superflycss/utilities-layout) ( [demo](https://superflycss.github.io/utilities-layout/target/test/html/) ) that makes it very easy to adjust this.

I've been following the approach outlined by [Philip Walton - Solved by Flexbox](https://philipwalton.github.io/solved-by-flexbox/) in general.

Screenshot of desktop view (Notice the documentation moves past the right side of the screen):
![screenshot from 2017-07-07 11-42-28](https://user-images.githubusercontent.com/1163873/27968051-184ae83a-630b-11e7-9ffc-14ac8e4cd2e7.png)

**Comment by gkalpak** [comment]
It should already be responsive. I can't reproduce your screenshot above. This is what I see (even at 444px width):

![router](https://user-images.githubusercontent.com/8604205/27968685-af8c9456-6350-11e7-8da8-0ffb698c70e1.png)

**Comment by oleersoy** [comment]
You are right.  I opened the same window in incognito mode and and it's responsive there.  Clicking the progressive "Update" button on angular.io may have broken broken some of the CSS.
