### ISSUE TITLE
cordova angular unstable

### ISSUE THREAD

**Issue by mob1** [angular/angular#18009]
Hi,
Hybrid mobile app is developed using Angular.. the app is working good in chrome and safari browsers. but the same app packaged with cordova is behaving differently. the issue we see in cordova app is  screens are getting distored and responsiveness of the app is not good.

Came across issues due to change detection , so have upgraded the angular version to 4.2.5 and zone js version to 0.8.12..even after upgraded the app behaviour is same in IOS but android is better.

Any best practice to follow in angular for Cordova plugin calls?..   Any impact in change detection due to "cordova.exec" calls?

Always getting below results in the app for zone name. is this right?

Chrome/Safari - 
window.zone.current
_name: "<root>"
_parent: null

Android/ios
window.zone.current
_name: "<root>"
_parent: null

Angular version :  4.2.5
Cordova, Android, IOS

**Comment by JiaLiPassion** [comment]
you may try to load zone.js cordova patch, you can find details here, https://github.com/angular/zone.js/blob/master/NON-STANDARD-APIS.md

**Comment by mob1** [comment]
thanks for the details. I am trying to wrap all success  and error callbacks with zone.current.wrap. but device ready, back button events are not calling. still checking to resolve.. will update further with details. share if any details for wrapping the device ready events..

**Comment by mob1** [comment]
added zone-patch-cordova.js after cordova.js file load. but zone wrap is not happening automatically. I just printed the below in zone-patch-cordova.js.. but manual wrap of all Cordova.exe calls is working..

<img width="845" alt="screen shot 2017-07-10 at 12 52 45 pm" src="https://user-images.githubusercontent.com/29997233/28003240-c8b60ece-656e-11e7-81df-eb2381971704.png">
<img width="755" alt="screen shot 2017-07-10 at 12 54 18 pm" src="https://user-images.githubusercontent.com/29997233/28003262-f0ac1482-656e-11e7-9cc0-f71e306939ea.png">

**Comment by mob1** [comment]
Hi,
have applied zone.wrap for all cordova.exec calls.. after zone wrap - issue is gone in android and iphone6. but strange that iphone7 the issue is still there. not sure what is misisng.. still checking that. if you have any suggestion - pls share.
