### ISSUE TITLE
Streamline directive definitions with more liberal use of decorators

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#1800]
According to the docs, making a directive that listens for events on the host element is like so:

```ts
@Directive({
  selector: 'input',
  hostListeners: {
    'change': 'onChange($event)',
    'window:resize': 'onResize($event)'
  }
})
class InputDirective {
  onChange(event:Event) {}
  onResize(event:Event) {}
}
```

This seems like it could be streamlined:

 * The listeners are registered far away from where the handlers are defined
 * The registration duplicates a) the method names and b) arguments.
 * The registration uses strings which makes obfuscation and refactoring more difficult.
 * You can listen for global events, too (seems odd that the **host**Listener object lets you do this)
 * Listening for global events depends on a magic string prefix of "window:" (or "document:" or "body:", implied by the docs)

Here's a possible alternative:

```ts
@Directive({
  selector: 'input'
})
class InputDirective {
  @HostListener('change')
  onChange(event: Event) {}
  
  @WindowListener('resize')
  onResize(event: Event) {}
}
```

This doesn't suffer from any of the problems listed above.

You can imagine a similar streamlining for properties. Currently you write:

```ts
@Directive({
  selector: '[dependency]',
  properties: {
    'id':'dependency'
  }
})
class Dependency {
  id:string;
}
```

But using decorators you could write:

```ts
@Directive({
  selector: '[dependency]',
})
class Dependency {
  @Property('dependency')
  id:string;
}
```

I find it a whole lot easier to understand this, not needing to remember constantly what the left and right hand side of the configuration means. E.g. for `{ 'id': 'dependency' }` I cannot tell easily which one of 'id' or 'dependency' is the JS class property and which is the DOM element property. I constantly get this confused in Angular 1, too, with the scope config. Hopefully we can eliminate this rough edge in Angular 2...

**Comment by aciccarello** [comment]
I like the way that looks. I've been a little concerned about having a huge annotation before the class definition. This would be a good way to tie things together. I haven't looked at the decorators/annotations spec yet but I hope they're available on a method level.

**Comment by aciccarello** [comment]
Just noticed a similar suggestion with injectables on [#1451](https://github.com/angular/angular/issues/1451#issuecomment-94545503)

**Comment by pkozlowski-opensource** [comment]
I think that there is some confusion going on regarding #1451 as it mixes up _configuration_ of the DI container with specifying what should be injected from the previously configured DI container.  In this example:

```javascript
@Component()
class MyComponent {
  @Inject(SomeServiceImpl) 
  constructor(someService:SomeServiceImpl) {}
}
```

You don't really need `@Inject(SomeServiceImpl)` - type annotation is enough. But you still need to say what is available in the DI container (this is what `injectables` does in @Component) and using `@Inject` name for this doesn't make sense

**Comment by ewinslow** [comment]
Type annotation is enough only if you type on a concrete class. Agree that in that case any other info should be unnecessary. That would certainly be nice.

`@Inject` may be a poor name. I'm sure we can come up with a better one. Maybe `@Injectables`? It could take an array. This would be decoupled from Component. Seems like a positive to decouple injector configuration from Component configuration actually. WDYT?

**Comment by mhevery** [comment]
This is planned as a short hand for putting everything in `@Component`

**Comment by ewinslow** [comment]
Woo hoo!

**Comment by pkozlowski-opensource** [comment]
Actually, after creating few components I'm more and more warming up to the idea of using annotations to denote properties and events. Ex, instead of:

```java
@Component({
    selector: 'bs-alert',
    properties: ['type', 'dismissible'],
    events: ['dismiss']
})
class BsAlert {
   dismiss = new EventEmmiter();    
   set type(val) {...}
}
```

I would be cool if I could write:

```java
@Component({
    selector: 'bs-alert'
})
class BsAlert {
   @Event()
   dismiss = new EventEmmiter();    

  @Property()
   set type(val) {...}
}
```

The biggest advantage for me would be that I don't have to duplicate property / event names

**Comment by gdi2290** [comment]
:+1: for alternative decorator annotations

**Comment by dsebastien** [comment]
+1 for @Event() & @Property(); feels natural/explicit/intuitive

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/commit/896add7d774775fadb1c4d1f2789913475cf84cc

**Comment by ewinslow** [comment]
Woot!
