### ISSUE TITLE
Change routes before routerAnimation complete

### ISSUE THREAD

**Issue by DanielYKPan** [angular/angular#18006]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[*] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When change routes before routerAnimation complete, page animation gets weird. sometimes would also generate error like
**`query(":leave")` returned zero elements**

## Expected behavior

Prevent route change when routerAnimations are running, or only allow to change route when routerAnimations complete

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by jasonaden** [comment]
@matsko You want to discuss this one?

**Comment by matsko** [comment]
@DanielYKPan #18210 I believe fixes the issue. You can check now to see if the code works by installing package.json with:

```
"@angular/animations": "git://github.com/angular/animations-builds.git#fix_md_input",
"@angular/platform-browser": "git://github.com/angular/platform-browser-builds.git#fix_md_input",
```

**Comment by matsko** [comment]
@DanielYKPan 5.0.0-beta.0 and 4.3.1 are out now. Please test against those. If it's still broken then reopen the issue please.
