### ISSUE TITLE
Add the ability to watch only for changed paramMap in queryParamMap

### ISSUE THREAD

**Issue by dgroh** [angular/angular#18010]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
We have in the URL 2 query parameters: **year** and **contractId**

http://localhost:8001/Page1/year=2018&contractId=2

If I change **year** but not **contractId**, the `subscribe` event is triggered, there I have both parameters, then I have to handle my self the logic to check which parameter has been changed storing them in variables like: "oldYear" and "oldContractId".

## Expected behavior
I wish a subscribe only for the changed parameter, this would make life much easier

example: 

`this.activatedRoute.snapshot.queryParamMap.get("year").subscribe(...)`

## Please tell us about your environment

<pre><code>
Angular version: 4.0

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by jasonaden** [comment]
@dgroh You should be able to just apply a filter here:

```
this.activatedRoute.queryParamMap
  .map(m => m.get('year'))
  .distinctUntilChanged()
  .subscribe(x => ...)
```
