### ISSUE TITLE
Improve documentation for navigate method: navigating from generic component

### ISSUE THREAD

**Issue by dgroh** [angular/angular#18017]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I want to navigate to the current URL with an existing param and from a generic component I want to navigate to the same URL and change its param with the selected value of this component, for example:

`http://localhost:8000/Page1/Page1Child1/<Param1>`

I have a component with a list of years.

I select `2018` for the first time, my URL should look like this:

`http://localhost:8000/Page1/Page1Child1/2018`

I did this by using: `this.router.navigate([this.router.routerState.snapshot.url, 2018])`

For the second time if I select `2019`, my router will look like this:

`http://localhost:8000/Page1/Page1Child1/2018/2019`

I tried to find in the docs how to replace the already existing param without appending the new param to the current URL, but I could not find this, except if I use query parameters.

## Expected behavior

I wish the documentation to tell how to navigate from a component, which does not know what is the current url. I know it's possible with query parameters and there is for that a good documentation.

## Please tell us about your environment

<pre><code>
Angular version: 4.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by jasonaden** [comment]
@dgroh This should work with:

`this.router.navigate(['./', 2018])`

**Comment by jasonaden** [comment]
Re-opened so this can be added to the docs.

**Comment by jasonaden** [comment]
I think this section and the following section covers it pretty well:

https://angular.io/guide/router#relative-navigation

**Comment by dgroh** [comment]
Could you please reopen this? What is the parameter comes **before** the page just after the `base-href`?

For example: I have the base-href `app` following with a contract id. It won't work.

`http://localhost:8080/App/1`

**Comment by jasonaden** [comment]
@dgroh Are you saying there's a bug here? Or still a documentation issue? Does

`this.router.navigate(['/', 1])`

work for your use case? Are you able to get something working or are you in a "broken" state?

**Comment by dgroh** [comment]
Ok, I just got confused with the usage as I was having a bug related to the navigation. I. I'll delete my comment soon to not make other users confused as well. Thank you very much.
