### ISSUE TITLE
AOT compiling issue with node modules

### ISSUE THREAD

**Issue by aminpaks** [angular/angular#18018]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

A simple import of an external `x` module turns into `x/index`

## Expected behavior

All external modules after compilation to be left untouched as before.

## Minimal reproduction of the problem with instructions

I cloned [this project](https://github.com/jasonaden/simple-ui-lib) which is an example of making a FESM library, and added `lodash-es` to demonstrate this issue.

Download this file, install node packages, run `build.sh` and observe that you will receive this warning below which is the result of `ngc` turning `lodash-es/isNil` into `lodash-es/isNil/index`.

<pre><code>'lodash-es/isNil/index' is imported by build/components/box.js, but could not be resolved – treating it as an external dependency</code></pre>

This makes it impossible for `rollup` to resolve the package.

[simple-ui-lib.zip](https://github.com/angular/angular/files/1133491/simple-ui-lib.zip)

## Please tell us about your environment

<pre><code>Angular version: v4.2.x
@angular/compiler@4.2.6

For Tooling issues:
- Node version: v7.10.0
- Platform: Mac
</code></pre>

**Comment by Eddman** [comment]
I have the same issue, NGC generates multiple imports:
@angular/flex-layout -> @angular/flex-layout/index
angular2-jwt -> angular2-jwt/angular2-jwt

I'm not sure that this is problem of NGC at all...may be a problem of TSC....

**Comment by aminpaks** [comment]
Absolutely it's not `tsc`'s fault. I compiled my code with it and it's fine.
This is the way `@angular/compiler` doesn things and it's messy.

**Comment by aminpaks** [comment]
So it turns out that `@angular/compiler@4.1.3` is better, it works fine with targeting `es5` by not okay with `es2015`.

**Comment by gms1** [comment]
in my case, ngc adds '/index' to the imports:
"@sandbox/ng-rollup-base" => "@sandbox/ng-rollup-base/index"

**Comment by aminpaks** [comment]
I found another issue, should I open an other ticket or we can continue here?

**Comment by aminpaks** [comment]
Now ng compiler exports a simple directive with invalid characters:
```js
/**
 * Generated bundle index. Do not edit.
 */
export { AModule } from './a-module';
export { ADirective as ɵa } from './a-directive';
//# sourceMappingURL=index.js.map
```
```
    "@angular/compiler": "^4.3.0",
    "@angular/compiler-cli": "^4.3.0",
    "@angular/core": "^4.3.0",
    "rxjs": "^5.4.2",
    "typescript": "~2.3",
    "zone.js": "^0.8.13"
```

**Comment by chuckjaz** [comment]
@aminpaks This above looks right to me. The latin barred-o (ɵ) is a valid identifier character. We use this extensively in Angular as a symbol that is technically public but should be treated as private.

To avoid this ensure that, in this case, `ADirective` is public from the module index. I recommend creating something like [public_api.ts](https://github.com/angular/angular/blob/master/packages/common/public_api.ts) that exposes the api you wish to have from the package.

**Comment by aminpaks** [comment]
@chuckjaz If it's not exported, probably they should not be exposed, don't you think so?

**Comment by chuckjaz** [comment]
@aminpaks In the case above `ADirective` is exposed through a "private export" because it was mentioned (probably declared) in a `NgModule` declaration. The generated factory needs to have access to it but it should not be part of the public API of the flattened module so the metadata bundler creates a "private export" for it.

I am not sure what you mean by "exposed to Angular module". If you mean declared in the module, then no, it is not sufficient. The module metadata is not used at runtime and can be discarded completely (which the webpack plugin can be configured to do). To be able to create an instance of the class the factory must be able to import it. To import it, it must be exported from a module. Without bundling this can be done with a deep import. With bundling, however, deep imports are not available (as the module structure has been flattened) so the symbols that would have required a deep import are re-exported in the synthetic index as "private export" symbols so the factory class can import them.

**Comment by aminpaks** [comment]
Thanks for the explanation. I didn't know this.
But this `module-x` turns into `module-x/index` is still a bug right? I already found a nother bug not related to this topic. Should I open another issue, or I can explain it here?

**Comment by gms1** [comment]
The error about the wrong imports was already reported here #17171

**Comment by aminpaks** [comment]
Thanks. We can close this ticket I'll follow up [there](https://github.com/angular/angular/issues/17171).

**Comment by pkozlowski-opensource** [comment]
Closing based on https://github.com/angular/angular/issues/18018#issuecomment-318203663
