### ISSUE TITLE
Possibility to delete a parameter using queryParamsHandling: "merge"

### ISSUE THREAD

**Issue by mscu** [angular/angular#18011]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

- Currently it is not possible to explicitly delete a single query parameter using queryParamsHandling: "merge"
- when passing null as value the old value doesn't change

## Expected behavior

Lets say i have two components on one page. Each component is responsible for two parameters:

Component 1 uses parameter a,b
Component 2 uses parameter c,d

I'm using queryParamsHandling: "merge" so that each component only modifies the parameters it is responsible for and the parameters of the other component(s) remain the same.

As query parameters are optional it is legitimate that one component wants to delete a parameter it is responsible for, e.g. Component 1 wants to remove parameter a.

To do so, i would expect that i can pass null to remove the parameter

```typescript
this.router.navigate(['.'], { relativeTo: this.route }, { queryParams: { a : null, b:'x' },  queryParamsHandling: "merge" });
```

--> `old url: a=foobar&b=x&c=y&d=z`
--> `result: b=x&c=y&d=z`

## Current behavior

The url is not changed passing null and it is not possible to remove a parameter with "merge"

--> `old url: a=foobar&b=x&c=y&d=z`
--> `result: a=foobar&b=x&c=y&d=z`

## Workaround

As a workaround i can only pass an empty string '' for parameter a, which has a different meaning and also leaves a parameter in the URL:

 ```typescript
this.router.navigate(['.'], { relativeTo: this.route }, { queryParams: { a : '', b:'x' },  queryParamsHandling: "merge" });
```

--> `old url: a=foobar&b=x&c=y&d=z`
--> `result: a=&b=x&c=y&d=z`

Another workaround is not to use the merge mechanism, but then the components need knowledge about the other parameters that they are not responsible for

**Comment by jasonaden** [comment]
@vicb Do you think we could fix this as a bug fix? Or do we have to call this a feature?

**Comment by jasonaden** [comment]
@mscu This could be done with `queryParamsHandling: 'replace'` and then you can manually merge the old and new query params, removing the key you don't want.

**Comment by mattscu** [comment]
even though you can do this manually i think it is not an uncommon usecase so i'd prefer to have it build in
