### ISSUE TITLE
`@Component('selector')` as shorthand/replacement for `@Component({selector:'selector'})`

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#1801]
So frequently I see `selector` being the only argument to `@Component` or `@Directive` (e.g. `@Component({selector:'selector'})`. I imagine if #1800 is accepted then this will be the case pretty often even in real-world apps.

`@Component('selector')` would be just swell. If you need options you could just pass a second argument.

```
@Component('selector', {
  injectables: [],
})
```

It's a minor issue, but you know how we developers hate boilerplate...

In any case if Angular is not open to this kind of API change at this point, just let me know and I'll stop suggesting them :)

**Comment by pkozlowski-opensource** [comment]
There is an alternative proposal in https://github.com/angular/angular/issues/1451 where we say that a selector could be inferred from a class name. 

I must say that I'm not really big fan of `@Component('selector')` as it essentially replaces named "arguments" with positional ones. On top of this currently one can have components with the sole "selector" argument only for the most basic components - any non trivial component will need to declare directives it is planning on using (in the `directives` argument).

I would rather go with a convention for a selector rather than implement the proposal from this issue.

**Comment by ewinslow** [comment]
Thanks for the reply! My thoughts:

The directives argument is only for the @View annotation, so I think that didn't affect this case.

I would assume that only the selector would be positional. It is really the only required argument. Agree that in general named is better than positional.

I'm not a huge fan of basing the name on the class because that hurts obfuscation.

**Comment by jelbourn** [comment]
Dart doesn't currently support union types, so this proposal wouldn't work there.

**Comment by ewinslow** [comment]
You don't need union types. You just need two arguments.

**Comment by ewinslow** [comment]
E.g. `@Component('name', {...})`

**Comment by jelbourn** [comment]
Selector is going to be optional (See #1662), so it gets kind of awkward without union types.

**Comment by ewinslow** [comment]
Ah well yes that does make things interesting doesn't it? Thanks for the clarification.

**Comment by pkozlowski-opensource** [comment]
@ewinslow right, sorry for the confusion with `directives`. But this doesn't change other parts of my comment. 

> I'm not a huge fan of basing the name on the class because that hurts obfuscation.

Hmm, most of the time you would be exporting those directives, so I don't think you can obfuscate them, can you?

**Comment by ewinslow** [comment]
@pkozlowski-opensource If you can tell the compiler about your whole world ahead of time, it can get rather fancy with bundling modules and rewriting names and such even when those names are needed across modules. I sure hope this continues to be supported :)

**Comment by mhevery** [comment]
I don't think we should support this for now. It makes the types in docs weird. Closing for now.
