### ISSUE TITLE
common/http: expectOne could help to check body and headers

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#18014]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
(following https://github.com/angular/angular/pull/17143#issuecomment-313752114)

Currently to test the body of a request we have to do 

```typescript
const req = http.expectOne({method: 'POST', url: '/api/users/1'});
expect(req.request.body).toEqual(user);
req.flush(user);
```

## Expected behavior

It would be really helpful for developers to something like:

```typescript
http.expectOne({method: 'POST', url: '/api/users/1', body: user}).flush(user);
```

or even:

```typescript
http.expectOne('POST', '/api/users/1', user).flush(user);
```

or even (my favorite):

```typescript
http.expectPost('/api/users/1', user).flush(user);
```

## Please tell us about your environment

<pre><code>
Angular version: 4.3.0-rc.0
</code></pre>

**Comment by alxhub** [comment]
The goal of the `expectOne` API is request matching - its job is to pick an expected request out of the set of active requests, in much the same way a server would. It's not intended to do _assertions_ on the request beyond asserting that a compatible request exists.

For example:

```javascript
const req = http.expectOne({method: 'GET', url: '/api/users/1'});
expect(req.body).toEqual({user});
req.flush({user});
```

**Comment by cexbrayat** [comment]
@alxhub Yes, but couldn't it? It would simplify HTTP tests quite a lot, and make them more readable (compare the current solution with `http.expectPost('/api/users/1', user).flush(user);` for example)

**Comment by alxhub** [comment]
There are simply too many things to assert about the request that we'd have to add to our API.
