### ISSUE TITLE
Out of memory during ng build (prod/aot)

### ISSUE THREAD

**Issue by notsonotso** [angular/angular#18019]
## I'm submitting a ...
[x] Bug report 

## Current behavior
**ng build --prod --aot**  produces 

**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**

The **--max_old_space_size=8192** trick doesn't work anymore. The app has grown considerably lately.

## Expected behavior
Successful build

## Minimal reproduction of the problem with instructions
`ng build --prod --aot`

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5 and 4.2.6
</code></pre>

**Comment by ericmartinezr** [comment]
Wrong repo. You are looking for https://github.com/angular/angular-cli

**Comment by notsonotso** [comment]
@ericcarraway i know, but angular-cli already had this issue reported many times, with no resolution, so now we try this.

**Comment by chuckjaz** [comment]
@notsonotso As recommended by @ericmartinezr, this should be reported to [angular-cli](https://github.com/angular/angular-cli) and tracked there.
