### ISSUE TITLE
Can't resolve '@angular/router/src/utils/tree'

### ISSUE THREAD

**Issue by dgroh** [angular/angular#18028]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After importing `TreeNode<T>` I get the following error;

> Module not found: Error: Can't resolve '@angular/router/src/utils/tree'

**Comment by mlc-mlapis** [comment]
Importing `TreeNode` from where? It is not in public API.

**Comment by dgroh** [comment]
@mlc-mlapis from '@angular/router/src/utils/tree'

I wanted to mock `RoutesRecognized` which asks for TreeNode<ActivatedRouteSnapshot>, I did dis by doing so:

`@Injectable()
export class RouterStub {
  public events: any;

  public readonly url;

  public setRoutesRecognized(routesRecognized: RoutesRecognized) {
    this.events = new Observable(observer => {
      observer.next(routesRecognized);
      observer.complete();
    });
  }

  public navigate(commands: any[], extras?: NavigationExtras) { }
}`

And then:

`  let createRouterStateSnapshot = function (vertragsId) {
    let routerStateSnapshot = jasmine.createSpyObj("RouterStateSnapshot", ["toString", "root"]);
    routerStateSnapshot.root = jasmine.createSpyObj("root", ["firstChild"]);
    routerStateSnapshot.root.firstChild.paramMap = jasmine.createSpyObj("paramMap", ["get"]);
    routerStateSnapshot.root.firstChild.paramMap.get.and.returnValue(vertragsId);

    return <RouterStateSnapshot>routerStateSnapshot;
  };`

And then:

`routerStub.setRoutesRecognized(new RoutesRecognized(0, "", "", createRouterStateSnapshot(null)));`

I don't see any other option than opening an issue, as the docs don't tell anything about mocking `RoutesRecognized`.

**Comment by IgorMinar** [comment]
TreeNode is a private API. Mocking it the way you are trying to do will likely result in a breaking your code when we make an internal change.

I'm not sure what exactly are you trying to do, but maybe we could be more helpful if you opened a new issue proposing a high-level API that is missing that would allow you to write the test you need.

**Comment by dgroh** [comment]
Hello @IgorMinar 

This is what I'm trying to mock, please note the `instaceof RoutesRecognized`

```
  public ngOnInit(): void {
    /*
     * Once the application root initializes, we need to check if there are parameters in the URL
     * The contractId parameter is mandatory and should always be present in the URL
     * In case contractId is not present in the URL, we will use the contractId of the loggedIn user
     * If the user has more than one contract, we will use the first one of the list
     * We also send a list of possible query parameters, for example: ...?year=2017&statusId=23780
     * -----------------------------------------------------------------------------
     * Once we have fetched the contractId, we need to know where this user has to be redirected to
     * For now, as we have only 'Contracts' page, we will redirect the user to it
     * The URL will look like this:
     * http://portal/App/{{contractId}}/Customers/
     * Or with extra query parameters
     * http://portal/App/{{contractId}}/Customers&year=2017&bafaBescheidNumber=23780
     */
    let routerInitializerSubscriber = this.router.events.subscribe(route => {
      if (route instanceof RoutesRecognized) {
        let contractId = Number(route.state.root.firstChild.paramMap.get("contractId"));

        this.vertragService.getVertraege().then((vertraege) => {
          let contract = vertraege.find(v => v.id === contractId);

          this.contracts = contracts;
          this.selectedContract = contract === undefined ? contracts[0] : contract;
        }).then(() => {
          this.router.navigate([this.selectedContract.id.toString() + "/Customers"], { queryParams: this.activatedRoute.snapshot.queryParams });

          routerInitializerSubscriber.unsubscribe();
        });
      }
    });
  }
```

Let me know if it makes sense, then I'll open an issue, for me is very difficult to tell you if it's an issue as i'm starting with angular. For me it's a lack of documentation. In the docs there is documentation for `ActivatedRouterStub`, but once things get more complex, it's very hard to cfreate mocks and to find information (IMO)

**Comment by hmachefe** [comment]
I definitively and completely agree with you, Daniel. I just completed / reactivated a case by StackOverflow to figure out how to gain more control on mocking router including RoutesRecognized events baked as observables :
https://stackoverflow.com/questions/38475342/mocking-router-events-subscribe-angular2

Even proceeding your way does raise failure fron karma:
`Failed: undefined is not an object (evaluating 'router.routerState.root')`
