### ISSUE TITLE
ComponentFactoryResolver not resolving factories in tests

### ISSUE THREAD

**Issue by Gebov** [angular/angular#18029]
## I'm submitting a ...

<pre><code>
[x] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have a component(host) that uses ComponentFactoryResolver to create components dynamically. I have tests for this component that pass entryComponents as described in this issue #10760 so as to get the ComponentFactoryResolver to find the factories of these components and instantiate them in the host's template. 

The problem is that the passed ComponentFactoryResolver is no longer an instance of CodeGenComponentFactoryResolver and calls to resolveComponentFactory return undefined. Hence the factory variable is no longer filled with a factory for that component.

This worked fine with version 4.1.3 and stopped working with version 4.2.0-rc.0. 

### _Component loader host_
``` typescript
import { Component, OnInit, Input, ComponentFactoryResolver, ViewChild, ViewContainerRef, ComponentRef } from "@angular/core";

import { ComponentData } from "./component-data";

@Component({
    selector: "component-loader",
    template: `<div #componentContainer></div>`
})
export class DynamicComponentLoaderComponent implements OnInit {
    @Input() componentData: ComponentData;
    @ViewChild("componentContainer", { read: ViewContainerRef }) viewContainer: ViewContainerRef;

    private _instance: any;
    private _componentRef: ComponentRef<any>;
    get instance() {
        return this._instance;
    }

    constructor(private resolver: ComponentFactoryResolver) { /* empty */ }

    ngOnInit() {
        if (!this.componentData)
            console.error("No component data specified");
        else {
            const factory = this.resolver.resolveComponentFactory(this.componentData.type);
               // ^^^^^^^ <- factory is null

            this._componentRef = this.viewContainer.createComponent(factory, null, this.viewContainer.injector);
            this._instance = this._componentRef.instance;
        }
    }

    destroy(): void {
        this._componentRef.destroy();
    }
}

```

### _ComponentData_
``` typescript
import { Type } from "@angular/core";

export interface ComponentData {
    type: Type<any>;
    properties?: {[property: string]: Object};
}
```

### _Test_
``` typescript
import { Component, ComponentFactoryResolver } from "@angular/core";
import { TestBed, ComponentFixture } from "@angular/core/testing";
import { BrowserDynamicTestingModule } from "@angular/platform-browser-dynamic/testing";

import { DynamicComponentLoaderComponent } from "./dynamic-component-loader.component";
import { ComponentData } from "./component-data";

@Component({
    selector: "test-hosted",
    template: "templ"
})
class HostedComponent {
    content: string;
}

describe("DynamicComponentLoaderComponent tests", () => {
    let fixture: ComponentFixture<DynamicComponentLoaderComponent>;

    beforeEach(() => {
        TestBed.configureTestingModule({
            providers: [ComponentFactoryResolver],
            declarations: [HostedComponent, DynamicComponentLoaderComponent]
        });

        // some sort of hack to get this working
        // https://github.com/angular/angular/issues/10760
        TestBed.overrideModule(BrowserDynamicTestingModule, {
            set: {
                entryComponents: [HostedComponent]
            }
        });
    });

    beforeEach(() => {
        fixture = TestBed.createComponent(DynamicComponentLoaderComponent);
    });

    it("should instantiatе hosted component correctly", () => {
        const content: string = "test";
        const properties = {content: content};
        const data: ComponentData = {
            type: HostedComponent,
            properties: properties
        };
        fixture.componentInstance.componentData = data;
        fixture.detectChanges();
        expect(fixture.componentInstance.viewContainer.length).toBe(1);
        expect(fixture.componentInstance.instance.content).toBe(content);
    });
});
```

## Expected behavior

The provided workaround in #10760 worked until now and this breaks a lot of my tests that actually count on this workaround.

## Minimal reproduction of the problem with instructions

Just copy paste the files and test them with version 4.2.0-rc.0 and above(not-working) or 4.2.0-beta.1 or bellow (working)

## Please tell us about your environment

<pre><code>
Angular version: 4.2.0-rc.0 and above

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Headless Electron for tests
 
For Tooling issues:
- Node version: 6.9.2 
- Platform: Windows

Others:

</code></pre>

**Comment by ndcunningham** [comment]
Same issue was working before since i update past 4.2.x `factory` is always undefined

**Comment by mlaval** [comment]
I couldn't reproduce this issue neither in Angular code base with a new test, nor in a fresh @angular/cli project.
The only thing I changed was removing the `providers: [ComponentFactoryResolver],` from the test file.
After that, the test is running fine.

Please re-open if you have another reproducer.

**Comment by ndcunningham** [comment]
@mlaval is `ComponentFactoryResolver` automatically provided?

I need to get a reference from it so i can create a new Directive for my unit test.
`const myDirective = new myDirective(componentFactoryResolver)`

**Comment by ndcunningham** [comment]
@mlaval thanks. works for me.

**Comment by nikunjtilva** [comment]
I faced same issue. Solution from @marclaval works for me.

**Comment by prabhu-raja** [comment]
I too faced the same issue by removing the providers: [ComponentFactoryResolver], from the test file It works fine.. Thanks @marclaval and ALL

**Comment by pratikbhuta** [comment]
Worked like a charm. Thanks a lot:)
