### ISSUE TITLE
docs: misleading concepts about sanitization in template syntax

### ISSUE THREAD

**Issue by trotyl** [angular/angular#18021]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In [Content security section of template syntax guide](https://angular.io/guide/template-syntax#content-security), it is saying:

```html
<!--
  Angular generates warnings for **these two lines** as it sanitizes them
  WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).
 -->
<p><span>"{{evilTitle}}" is the <i>interpolated</i> evil title.</span></p>
<p>"<span [innerHTML]="evilTitle"></span>" is the <i>property bound</i> evil title.</p>
```

However, Angular would only generate warning for the second line (eg. http://plnkr.co/edit/mVdKNzddtIkSe39s0dUq?p=preview ),

![image](https://user-images.githubusercontent.com/6059170/27994490-da7ef6f2-64f1-11e7-8deb-0b7c50512ebd.png)

but not for the first line (eg. http://plnkr.co/edit/RIwHZCDZTaski9rNKj9X?p=preview ).

![image](https://user-images.githubusercontent.com/6059170/27994495-01627244-64f2-11e7-8dd6-b2083ecce00d.png)

As Angular isn't a string-based template, the sanitization won't happened here at all.

## Expected behavior

Angular documentation should provide correct description about concepts.

So it could separate the descriptions about these two conditions, make it clear that in first case **the HTML-text would just display as is and this is the nature of Angular template rather than the result of sanitization**, in second case **the HTML-text would be sanitized by Angular and the malignant parts have been removed**.

## Minimal reproduction of the problem with instructions

+ Fake description for the first line, which won't be sanitized: http://plnkr.co/edit/RIwHZCDZTaski9rNKj9X?p=preview
+ Real description for the second line, which is indeed sanitized: http://plnkr.co/edit/mVdKNzddtIkSe39s0dUq?p=preview

## What is the motivation / use case for changing the behavior?

Making the documentation correct and clear.

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

Migrated from https://github.com/angular/angular.io/issues/3408

**Comment by kapunahelewong** [comment]
@trotyl Thank you for the clear explanation. I have included your ideas in the PR. ✨

**Comment by kapunahelewong** [comment]
Hi @trotyl! Thanks for bringing this up. Closing this issue since the PR merged. 🎉
