### ISSUE TITLE
An enquiry from a novice to AngularJs

### ISSUE THREAD

**Issue by 8th-coder** [angular/angular#18023]
Hi all!!!

I know I should have get this to somewhere else, like the email group and whatnot, but I could not find any of those information on the tutorial page for novice, so I am gonna put it here. Hope you guys don't mind.

I am so excited about encountering this GREAT GREAT framework of AngularJs. Since I am new to web development and the MEAN stack, everything is fresh and exciting. The Tour of Heros Tutorial is great, but to make a web app exactly like the website for AngularJs (https://angular.io), I wonder what I need to know first and where I can find those knowledge, or if there is even a clone project that I can follow to learn along.

Thank you for your advice in advance and thank you so much , from the bottom of my heart, for all you guys' great work for providing the arguably G.O.A.T framework to the world!!!

**Comment by ocombe** [comment]
Hello, the github issues of this project are only for bugs and feature requests regarding the technical aspect of the framework.
For general questions like yours, you should probably ask on reddit: https://www.reddit.com/r/Angular2/
