### ISSUE TITLE
setControl function raises error on second call (There is no FormControl instance attached to form control element with path)

### ISSUE THREAD

**Issue by Cyberdada** [angular/angular#18027]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When calling setControl a second time on a FormArray,  I get the following error: 
There is no FormControl instance attached to form control element with path: 'roles -> 1 -> role'

## Expected behavior

no error is raised. 

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/WAq2GkeNzfQSOcGuzyDr

in the plunker push the topmost editor toggle button. 
note that the application works, but I get an ugly error.

## What is the motivation / use case for changing the behavior?

My understanding is that you should be able to use setControl to reinitiate a formArray without getting an error

## Please tell us about your environment

<pre><code>
Angular version: 4.2.6

Browser:
- [x ] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 
Windows
Others:

</code></pre>

**Comment by baluragala** [comment]
Hi @Cyberdada,

I have looked into your plunk and played with it too see stack trace. I believe the error is not from angular itself but from angular material ( from MdButtonToggleGroup component ). Please see the highlighted text below. This is the reason you still see that form works but an error in the log. I have tested the setControl locally in my dev without angular MD and I see no error.

Let me know if you have any questions.

ERROR Error: There is no FormControl instance attached to form control element with path: 'roles -> 0 -> role'
    at d (zone.min.js:1)
    at _throwError (shared.ts:144)
    at _noControlError (shared.ts:121)
    **at MdButtonToggleGroup.eval [as _controlValueAccessorChangeFn] (shared.ts:101)
    at MdButtonToggleGroup._emitChangeEvent (button-toggle.ts:424)
    at MdButtonToggleGroup.set [as value] (button-toggle.ts:280)
    at MdButtonToggleGroup.writeValue (button-toggle.ts:384)**
    at setUpControl (shared.ts:57)
    at eval (form_group_directive.ts:214)
    at Array.forEach (<anonymous>)
    at FormGroupDirective._updateDomValue (form_group_directive.ts:209)
    at FormGroup.eval [as _onCollectionChange] (form_group_directive.ts:222)
    at FormGroup.setControl (model.ts:1058)
    at UserDetailComponent.allRoles (app.component.ts:53)
    at Object.eval [as handleEvent] (app.component.html:33)

**Comment by ShiftySituation** [comment]
@Cyberdada in your plunker, you are setting the form array controls to a form group but using them in your template as form controls.

**Comment by Cyberdada** [comment]
Hi Balurgala, 
Yes, you are probably right. :) should I reraise the bug in the Angular Material repo?
I will try to change out the material ToggleGroup, roll my own, and see what happens.

**Comment by Cyberdada** [comment]
I confirmed that this is a MdButtonToggleGroup problem. After changing the input type to md-radio-group, no error is raised. Closing bug here, and raising it in angular/material 2.
