### ISSUE TITLE
Cross-browser-tabs GlobalEventEmitter

### ISSUE THREAD

**Issue by un33k** [angular/angular#18024]
## I'm submitting a ...

<pre><code>
[ x ] Feature request
</code></pre>

## Current behavior
Angular is a good choice for a Single Page APP `(SPA)`, however, whether it is an old browsing habit or a necessity, many people open more than one browser tabs.  It would be great to have a `native` `NG` way of `communicating` between two peer components running in two `different` `tabs`. 

## Expected behavior
Tab #1 Component #1 authenticates the user, then emits an event `marked as` `global`.
Tab #2 Component #N that is subscribed to such an event catches that event and updates its state which results in an authenticated states and redirects to the redirect URL.  Only the primary tab is responsible for persisting the data in localStorage.  The rest of the tabs are slaves.

OR: 

```typescript
import { Injectable, EventEmitter, GlobalEventEmitter, GlobalEventListener } from '@angular/core';

@Injectable()
export class AuthService {
  lang = 'en';
  @Output() langChangeEventLocal = new EventEmitter();
  @Output() langChangeEventGlobal = new GlobalEventEmitter();

  constructor() {
    GlobalEventListener('langChangeEventGlobal').subscribe(lang => {
       // someone else did all the work, so we just let the local folks know about it.
       // no other action is required, such as writing to localStorage or logic to avoid it.
       this.langChangeEventLocal.emit(lang);
    });
  }
  
  setLang(lang: string): {
     this.lang = lang;
     // let the server know
     // get the token from the server
     // store the token in localStorage
     // let everyone locally & globally know about the change
     this.langChangeEventLocal.emit(lang);
     this.langChangeEventGlobal.emit(lang);
  }

}
```

## What is the motivation/use case for changing the behavior?
Currently using a broadcast message lib to communicate between the tabs, but having the ability to simply subscribe to any browser-wide global event would be a nice option to have.  Reduces lot of logic, and simplifies many core components.

## Please tell us about your environment
Browser:
- [ x ] Chrome (desktop) version 58.0.3029.110 (64-bit)

For Tooling issues:
@angular/cli: 1.2.0
node: 6.9.5
os: darwin x64
@angular/*: 4.2.6
@angular/cli: 1.2.0

**Comment by IgorMinar** [comment]
I think this is outside of the scope of Angular. You can use localStorage for this kind of functionality. I'm not sure what Angular could do to make this much better, we'd just add a custom api that simply wraps what's already in the browser without adding much value.

For example we rewrote the http service on top of XHR api because of testability, interception, and ergonomic features we added on top of XHR/fetch.

**Comment by un33k** [comment]
The impression was that since NG already has an ability to communicate with its web workers via `a` messaging layer, then why not extend the messaging so different tabs can communicate through it as well.  localStorage is always a good fallback.
