### ISSUE TITLE
Inject provider with "multi" definition without using "@Inject()" 

### ISSUE THREAD

**Issue by eldadcohen1** [angular/angular#18020]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Create provider with multi definition that extends BaseClass.
The class cannot be resolved without @inject() annotation.

<pre><code>
providers: [
    {provide: BaseClass, useClass: A , multi: true}, 
    {provide: BaseClass, useClass: B , multi: true} 
 ]

//Doesn't Work
constructor(baseClass : BaseClass[]){}

//Works
constructor(@Inject(BaseClass) baseClass : BaseClass[]) {}

</code></pre>

## Expected behavior

Classes should be resolved without explicit declaration of @inject() 

## Minimal reproduction of the problem with instructions
See plunker file src/multi-example and src/app.ts
Work Plunker with @inject() annotation:
https://plnkr.co/edit/NqC1FmuqwyShTH0e0k85?p=preview

Doesn't work Plunker without @inject() annotation:
https://plnkr.co/edit/xalztAue0AiNVN6E1xZV?p=preview

## What is the motivation / use case for changing the behavior?

Create services that are independent angular.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.6

Browser:
- [X] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.7.0 
- Platform: Windows

**Comment by tytskyi** [comment]
@eldadcohen1  remove `[]` it will still inject an array of things

**Comment by tytskyi** [comment]
see article https://blog.thoughtram.io/angular2/2015/11/23/multi-providers-in-angular-2.html

example from the article (observe no mentions of the array)

```typescript
const SOME_TOKEN: OpaqueToken = new OpaqueToken('SomeToken');

var injector = ReflectiveInjector.resolveAndCreate([
  { provide: SOME_TOKEN, useValue: 'dependency one', multi: true },
  { provide: SOME_TOKEN, useValue: 'dependency two', multi: true }
]);

var dependencies = injector.get(SOME_TOKEN);
// dependencies == ['dependency one', 'dependency two']
```

**Comment by eldadcohen1** [comment]
@tytskyi  Thanks 👑

**Comment by Toxicable** [comment]
There is a large difference between `BaseClass[]` and `BaseClass`.
`BaseClass[]` in class form is actually `Array<BaseClass>`, now remember that generics only exist in TypeScript so if we remove the generic we get `Array`. So from how i understand the injector, it will now try use Array as the injection token which just isn't going to give you the expected results.

**Comment by chuckjaz** [comment]
@eldadcohen1 While we could get this to work in AOT, this would not work in JIT. As @Toxicable indicated, generic types are not reified in JavaScript and the type recorded for the parameter is `Array` not `Array<BaseClass>` as we would need to be able to use the type as a token.

**Comment by pkozlowski-opensource** [comment]
Closing as it was already answered / clarified by @chuckjaz and @Toxicable
