### ISSUE TITLE
Provide TypeScript type definitions (.d.ts) for each release

### ISSUE THREAD

**Issue by FloWi** [angular/angular#1803]
Is it possible to include the angular.d.ts in the release archives? It'd be great to have an "all-inclusive-archive" of a release.

**Comment by pkozlowski-opensource** [comment]
Those are available as part of the DefinitelyTyped repo at https://github.com/borisyankov/DefinitelyTyped/tree/master/angular2 but I wonder how this repo handles different APIs for different versions...

I kind of like the idea of distributing type definitions as part of the release

**Comment by FloWi** [comment]
Jep - that's what I thought. I'm currently playing with the webjar - but it has not the latest release packages yet. Therefore I don't know, if the type-definitions of the DefinitelyTyped repo fit to that release.

**Comment by alexeagle** [comment]
Update: we have a generated angular2.d.ts here:
https://gist.github.com/alexeagle/c7e0b05927469666d703

But still have issues to resolve before merging https://github.com/angular/angular/pull/2333 which has the generator.

**Comment by jomeier** [comment]
@alexeagle Is this type definition file also compatible with Alpha 25? The comment says its for Alpha 22.

**Comment by alexeagle** [comment]
Yes, it's generated for alpha.26. That comment is out-of-date in that gist.

**Comment by alexeagle** [comment]
This should be fixed by https://github.com/angular/angular/pull/2333
We now include an `angular2.d.ts` in the dist/ folder which should be included in our release archive.
Closing - @rkirov is there anything remaining in the release documentation to make sure we run `gulp docs` and get the generated file included in our npm push?

**Comment by alexeagle** [comment]
For those following: see https://github.com/borisyankov/DefinitelyTyped/pull/4563 for the DefinitelyTyped distribution.

**Comment by FloWi** [comment]
Thanks guys! Awesome!

**Comment by alexeagle** [comment]
@rkirov the alpha-27 release doesn't include the .d.ts so we are missing something...

**Comment by rkirov** [comment]
https://github.com/angular/angular/blob/master/scripts/publish/npm_publish.sh#L42 needs to copy over the `angular.d.ts` to a typings dir if we are to distribute with `npm`.

But I think using `tsd` infrastructure is more correct than relying on npm for this, since the `angular2.d.ts` file matches the shape of the angular2.js bundle, which is not delivered on npm (but rather lives on code.angularjs.org).

**Comment by naomiblack** [comment]
reassigning to the current (open) milestone, alpha-29

**Comment by alexeagle** [comment]
We need to post a more thorough design, but here's a summary of what @rkirov and I discussed yesterday:
- if you follow our quickstart examples, you are on the "pre-bundled" path, you only fetch our bits from `code.angularjs.org`, and will get the typings from DefinitelyTyped. From http://definitelytyped.org/guides/contributing.html see Versions - it's fine for us to post a typings file corresponding with each release, which I think was the intent of the OP here.
- if you install angular2 via npm, and are coding in TypeScript, then we don't have a good answer for you yet. This is the same problem we have with consuming the ts2dart project in angular. You could code directly against the TS files in the npm distro.
- if you install angular2 via npm, and are coding in ES5/ES6, then the typings are not useful.

So the summary is, agree that the bundled angular2.d.ts doesn't need to be included in the npm distro, at least not until we've worked out the use cases.

**Comment by naomiblack** [comment]
@alexeagle should this issue be closed in that case?

**Comment by alexeagle** [comment]
Last thing to do here is update the release instructions.

**Comment by alexeagle** [comment]
Updated release instructions. We should have a typings file in DefinitelyTyped for each angular2 release.

(https://docs.google.com/document/d/1mUlhZejeOoQXVFKfI9-9CPPWtFRCZOpB76oLHS-v5C4/edit#)
