### ISSUE TITLE
bug(docs): Methods appear many times

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#18039]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
[In Validators' docs](https://angular.io/api/forms/Validators) the `compose` method appears many times.

## Expected behavior
The `compose` method should appear only once.

**Comment by gkalpak** [comment]
This happens due to a bug in our current process of collecting API docs that shows the same signature multiple times for overloaded methods. It will be fixed by #17857 (e.g. https://pr17857-0602593.ngbuilds.io/api/forms/Validators).
