### ISSUE TITLE
Better support for overloaded methods in angular.io

### ISSUE THREAD

**Issue by alxhub** [angular/angular#18037]
The current AIO experience for the `HttpClient` class is pretty broken - the first signature is duplicated for every overload, and jsdocs don't show up. With @petebacondarwin's pending fixes the experience is a lot better (jsdocs work and every signature is shown), but there's still a lot of noise on the page, especially for an API like `HttpClient` which uses a dozen or so overloads per method.

Per a conversation with @IgorMinar, here is what I propose:

* Methods with a significant number of overloads (4)? have the overloads list as collapsible and collapsed by default. We show the implementation signature (which is the actual method definition) and the jsdoc for the overall method.

* Upon expansion, this list shows each signature with a corresponding dedicated jsdoc. Each individual overload is linkable.

This would greatly reduce clutter on the page and allow for much better explanations of the specifics of each overloaded signature.

**Comment by petebacondarwin** [comment]
I didn't realise that there was a single actual implementation method. I guess this is only true for classes and not interfaces, eh?

**Comment by petebacondarwin** [comment]
I'll work on it this week.

**Comment by petebacondarwin** [comment]
This change to dgeni-packages should provide us with the structure to the docs data that we need: https://github.com/angular/dgeni-packages/pull/236

**Comment by petebacondarwin** [comment]
I can render this data in the API docs but I am having difficulty getting an expandable component to wrap the code-example components in our dynamic doc-viewer component. Help @IgorMinar

**Comment by petebacondarwin** [comment]
Discussed with @IgorMinar:

 - we will use an HTML `detail` element for the moment for grouping the overloads
 - we will truncate parameters and return types after their first line in the overview.

**Comment by petebacondarwin** [comment]
Grouped overloads

* Collapsed:

![screen shot 2017-07-12 at 23 06 24](https://user-images.githubusercontent.com/15655/28141975-d48ba990-6756-11e7-9d9c-7ab281d3fca1.png)

* Expanded

![screen shot 2017-07-12 at 23 06 38](https://user-images.githubusercontent.com/15655/28141974-d48ab184-6756-11e7-8a67-49ef5d863c4d.png)

**Comment by petebacondarwin** [comment]
Closed via #18081
