### ISSUE TITLE
TypeError: Cannot read property 'assertPresent' of undefined: All unit tests are failing, using angular, jasmine, and karma

### ISSUE THREAD

**Issue by carterhunt** [angular/angular#18033]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>
I've been stuck for a while trying to fix this error I'm getting when I run any sort of unit test for my project. It returns: 

    TypeError: Cannot read property 'assertPresent' of undefined

even for the most simple tests. Currently, the only test I have included is just testing to see if it will run at all (for which it still fails).

    describe('1st tests', () => {
      it('true is true', () => expect(true).toBe(true));
    });

This is the error in its entirety:

    Error: Cannot read property 'assertPresent' of undefined
    at resetFakeAsyncZone (http://localhost:9876/_karma_webpack_/vendor.bundle.js:51073:18)
    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/vendor.bundle.js:51770:9)
    at attemptSync (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3898:24)
    at ZoneQueueRunner.QueueRunner.run (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3887:9)
    at ZoneQueueRunner.QueueRunner.execute (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3872:10)
    at ZoneQueueRunner.webpackJsonp.../../../../zone.js/dist/jasmine-patch.js.jasmine.QueueRunner.ZoneQueueRunner.execute (http://localhost:9876/_karma_webpack_/vendor.bundle.js:3051:42)
    at Spec.queueRunnerFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:816:35)
    at Spec.execute (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:473:10)
    at Object.fn (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:4975:37)
    at attemptAsync (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3945:24)

This is what my test.ts file looks like:

   ```
 // Need to add these from polyfils here or the tests will fail.
    // TODO: Remove this when RxJS releases a stable version with a correct declaration of `Subject`.
    import { Observable } from 'rxjs/Observable';
    import { Operator } from 'rxjs/Operator';
    
    declare module 'rxjs/Subject' {
      interface Subject<T> {
        lift<R>(operator: Operator<T, R>): Observable<R>;
      }
    }
    
    declare global {
      interface String {
        toCamelCase(): string;
      }
    }
    
    // This file is required by karma.conf.js and loads recursively all the .spec and framework files
    
    import { getTestBed } from '@angular/core/testing';
    import {
      platformBrowserDynamicTesting,
      BrowserDynamicTestingModule
    } from '@angular/platform-browser-dynamic/testing';
    import 'zone.js/dist/long-stack-trace-zone';
    import 'zone.js/dist/async-test';
    import 'zone.js/dist/fake-async-test';
    import 'zone.js/dist/sync-test';
    import 'zone.js/dist/proxy';
    import 'zone.js/dist/jasmine-patch';
    
    // Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
    declare const __karma__: any;
    declare const require: any;
    
    // Prevent Karma from running prematurely.
    __karma__.loaded = function () { };
    
    // First, initialize the Angular testing environment.
    getTestBed().initTestEnvironment(
      BrowserDynamicTestingModule,
      platformBrowserDynamicTesting()
    );
    // Then we find all the tests.
    
    const context = require.context('./', true, /\.spec\.ts$/);
    // And load the modules.
    context.keys().map(context);
    // Finally, start Karma to run the tests.
    __karma__.start();

```
And my karma.conf.js file:
    
  ```
  module.exports = function (config) {
      config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular/cli'],
        plugins: [
          require('karma-jasmine'),
          require('karma-chrome-launcher'),
          require('karma-jasmine-html-reporter'),
          require('karma-coverage-istanbul-reporter'),
          require('@angular/cli/plugins/karma')
        ],
        client:{
          clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        coverageIstanbulReporter: {
          reports: [ 'html', 'lcovonly' ],
          fixWebpackSourcePaths: true
        },
        angularCli: {
          environment: 'dev'
        },
        reporters: ['progress', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Chrome'],
        singleRun: false
      });
    }; 

```
And here is my package.json that details all the specific versions I am running:

`  
      "dependencies": {
        "@angular/animations": "^4.2.5",
        "@angular/cli": "^1.2.0",
        "@angular/common": "^4.2.5",
        "@angular/compiler": "^4.2.5",
        "@angular/core": "^4.2.5",
        "@angular/forms": "^4.2.5",
        "@angular/http": "^4.2.5",
        "@angular/platform-browser": "^4.2.5",
        "@angular/platform-browser-dynamic": "^4.2.5",
        "@angular/router": "^4.2.5",
        "@progress/kendo-angular-buttons": "^1.0.5",
        "@progress/kendo-angular-charts": "^1.2.1",
        "@progress/kendo-angular-dateinputs": "^1.0.5",
        "@progress/kendo-angular-dialog": "^1.0.4",
        "@progress/kendo-angular-dropdowns": "^1.1.1",
        "@progress/kendo-angular-excel-export": "^1.0.3",
        "@progress/kendo-angular-grid": "^1.2.2",
        "@progress/kendo-angular-inputs": "^1.0.6",
        "@progress/kendo-angular-intl": "^1.2.1",
        "@progress/kendo-angular-l10n": "^1.0.2",
        "@progress/kendo-angular-label": "^1.0.2",
        "@progress/kendo-angular-layout": "^1.0.5",
        "@progress/kendo-angular-popup": "^1.1.1",
        "@progress/kendo-angular-scrollview": "^1.0.3",
        "@progress/kendo-angular-sortable": "^1.0.2",
        "@progress/kendo-angular-upload": "^1.1.1",
        "@progress/kendo-data-query": "^1.0.5",
        "@progress/kendo-date-math": "^1.0.3",
        "@progress/kendo-drawing": "^1.1.1",
        "@progress/kendo-file-saver": "^1.0.2", 
    	"@progress/kendo-ui": "^2017.2.621",
        "@progress/kendo-theme-default": "^2.38.0",
        "@progress/telerik-angular-report-viewer": "^1.17.627",
        "bootstrap": "^4.0.0-alpha.6",
        "core-js": "^2.4.1",
        "font-awesome": "~4.7.0",
        "hammerjs": "^2.0.8",
        "jquery": "3.2.1", 
        "lodash": "^4.17.4",
        "moment": "^2.18.1",
        "ng2-toastr": "^4.1.2",
        "numeral": "^2.0.6",
        "reflect-metadata": "^0.1.10",
        "rxjs": "^5.1.0",
        "zone.js": "^0.8.12"
      },
      "devDependencies": {
        "@angular/cli": "1.2.0",
        "@angular/compiler-cli": "^4.2.5",
        "@types/jasmine": "2.5.53",
        "@types/lodash": "^4.14.68",
        "@types/node": "~8.0.7",
        "codelyzer": "~3.1.1",
        "jasmine-core": "~2.6.4",
        "jasmine-spec-reporter": "~4.1.1",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.3.0",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "karma-spec-reporter": "0.0.31",
        "protractor": "~5.1.2",
        "ts-node": "~3.1.0",
        "tslint": "~5.4.3",
        "typescript": "~2.4.1"
      }
    }
`
I've tried everything to fix it but I have no idea why its still here. If anyone has any idea how to address this, your help would be greatly appreciated.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

my best guess is that zone.js was not bundled in your polyfill bundle or the bundle was not loaded. please check that the browser has loaded zones before any of the test files.

**Comment by RoestVrijStaal** [comment]
Too cheap. 

Since you had already dived into it who's responsible for this. You could at least point to the developer/project we could yell at :angry:

**Comment by gkalpak** [comment]
> Too cheap.

🙂 


> You could at least point to the developer/project we could yell at

As already mentioned, @IgorMinar's best guess (and we can only make guesses without an actual, minimal reproduction) is that _"zone.js was not bundled in your polyfill bundle or the bundle was not loaded. please check that the browser has loaded zones before any of the test files."_.

So, before yelling at any developer/project, you might wnat to verify that. In fact, you seem to be missing `import 'node_modules/zone.js/dist/zone.js'` from your `test.ts` file. That is probably what is causing the issues.

<sub>(Please consider not yelling at OSS maintainers/developer. It spoils the fun :smiley:)</sub>

**Comment by pmandapuram** [comment]
Hi
I am getting an error while running test suite which calls a service method.
**Cannot read property 'getAllAttributes' of undefined**

May i know how to write test suites for service that returns a json object

Thanks

===================code=========
import { TestBed, async, inject, ComponentFixture, fakeAsync } from '@angular/core/testing';
import { By }              from '@angular/platform-browser';
import { DebugElement }    from '@angular/core';
import {AttributeManagementService} from './attributeManagament.service';
import { ComponentFixtureAutoDetect } from '@angular/core/testing';
import {} from 'jasmine';
import 'rxjs/Rx';
debugger;

describe('AttributeManagementService', () => {
   let service: ComponentFixture<AttributeManagementService>;
  beforeEach(() => {
  
    TestBed.configureTestingModule({
      providers: [ {provide: AttributeManagementService} ]
    }).compileComponents();
    
  });

    it('should return get all attributes', 
      inject([AttributeManagementService], (service: AttributeManagementService) => {
       
       service.getAllAttributes().subscribe((data) => {
            
              console.log("get attribute list "+data);
              expect(data).toBe([Object]); //data contains array of objects/
        
    });

    }));

**Comment by pmandapuram** [comment]
please help me to sort out the issue.. is there any configurations missing in my application.

Thanks

**Comment by staeke** [comment]
Have you included something like  `import 'zone.js/dist/proxy'`

**Comment by davidwuerfel** [comment]
Using Angular V6 and zone V0.8.26 the `test.ts` need only contain `import 'zone.js/dist/zone-testing';`.

However in my case, the **important** part was: The zone import must come before all other imports. You should not reorder imports (had this problem when using VS code's auto-organize) in `test.ts`.

**Comment by axelboc** [comment]
I use Jest and `jest-preset-angular`, and got this error when importing `jest-preset-angular` _after_ `TestBed` in my Jest set-up file. Inverting the two imports solved it.

**Comment by samherrmann** [comment]
I have the [ordered-imports](https://palantir.github.io/tslint/rules/ordered-imports/) TSLint rule set that changed the import order and consequently this error. Luckily TSLint provides a means to [disable specific rules from specific files](https://palantir.github.io/tslint/usage/rule-flags/). This allowed me to add 
`/* tslint:disable:ordered-imports */` at the top in the `test.ts` file.

**Comment by chrismbarr** [comment]
Same here... but why in the world would changing import order affect test results?  I was able to revert the commit where I re-ordered the imports, but I really don't understand why this could cause issues like this.  I've just disabled the rule for now

**Comment by JoostK** [comment]
@chrismbarr Generally speaking the order of imports is irrelevant. However, some imports refer to modules that have side-effects to e.g. the browser environment, by means of modifying things on `window` for example. `zone.js` is such a module, as it patches the environment with zones.

As a general rule, imports of the form `import "some-module";` do have side-effects (otherwise they would be redundant). As such, those imports must not be reordered. It is a pity that tools such as tslint do not take this into account.

**Comment by smasala** [comment]
Good tip with the ordered imports. Thanks.
