### ISSUE TITLE
Angular CLI ng serve cannot serve files from a folder with %20 in it

### ISSUE THREAD

**Issue by BaileyMillerSSI** [angular/angular#18031]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I cloned a repo that has a space in the root name and my editor placed a %20 in its place. From there performed npm install && ng serve and cannot GET / when navigating to localhost:4200.

## Expected behavior

That either the CLI warn that the repo has an invalid character or handle it gracefully. 

## Minimal reproduction of the problem with instructions

1. Create repo at Visual Studio Online with a space in the name
2. Clone using Visual Studio Code
3. See on windows 10 that it creates a folder with a %20 in the location of the space
4. Run `npm install && ng serve` and see that it cannot serve the index file

## What is the motivation / use case for changing the behavior?

Some users may not understand why their projects are working correctly after cloning repos that allow spaces in their names. As well the CLI does nothing to warn the user or tell them that something happened incorrectly. 

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.0 
- Platform: Windows 10

Others:

</code></pre>
Visual Studio Code with repo's from Visual Studio Online, I don't think that it matters that my tfs repo is an imported repo from a github repo with a valid name.

**Comment by ericmartinezr** [comment]
Repo for angular-cli https://github.com/angular/angular-cli

**Comment by BaileyMillerSSI** [comment]
I am sorry I will move my issue to that repo.
