### ISSUE TITLE
How to access app component function in to another component, wheather it is in parent child relation or not?

### ISSUE THREAD

**Issue by mahivitsit** [angular/angular#18049]
I need to access a function into Equipment Component, which is in App Component.

**Comment by mahivitsit** [comment]
@trotyl I need solution, not your reactions

**Comment by Pinedo11** [comment]
Since it seems to be a shared logic, have you thought about moving that logic to a shared service? This way you could access that function from both sides.

**Comment by mlc-mlapis** [comment]
There are several concepts how to do the principle that it seems you mean. The the right answer is related on the goal you want to reach. Before looking for so specific answer describe your case ... because your question is probably misleading.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
