### ISSUE TITLE
Angular's unattractive if/else syntax

### ISSUE THREAD

**Issue by zilions** [angular/angular#18045]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, Angular expects the following syntax for an if/else statement.

```
<div *ngIf="isValid;else other_content">If statement content</div>
<ng-template #other_content>Else statement content</ng-template>
```

Other popular frameworks, such as VueJS expect a far cleaner syntax, like the following:

```
<span *ngIf="ok">Yes</span>
<span *ngElse>No</span>
```

Why is Angular unable to accept cleaner template syntax for it's if/else statements?

**Comment by robwormald** [comment]
Other than this being a completely subjective opinion, in your suggested syntax, there's no relationship between the two structural directives, so you'd really need to do something like:
```html
<span *ngIf="whatever" #ifBlock>Foo</span>
<span *ngElse="ifBlock">Bar</span>
```
Which isn't necessarily any "cleaner" than the existing syntax, in my (completely subjective...) opinion.

Compare this to ngSwitch, which does have an outer "container" to associate the elements. Having the same functionality for ngIf would require a similar container, and at that point, you might as well just use ngSwitch.

Further, there's nothing special about *ngIf, in the sense it's just a regular old directive. You could absolutely implement your own version that did exactly this! Make it, share it up on github, and then people can bikeshed *your* choice of syntax! 😉
