### ISSUE TITLE
Need load external module

### ISSUE THREAD

**Issue by deblockt** [angular/angular#18048]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I need to load an external module provided by an other js file somewhere. Actualy, I don't have found any solution.

## Expected behavior

Provide the ability to load a module builder into another project at runtime.

## Minimal reproduction of the problem with instructions

I have try to create a module projet names "module-quickstart". 
This project, is builded with webpack and provide a module QuickStartModule.
This module is packaged with webpack on a `module.bundle.js` file, and include all angular dependencies.

On my main app, i have loaded `module.bundle.js` file, and execute code with eval instruction. 
After, I have get QuickStartModule (return a function named t).

I have try to compile this module using
``` typescript
this.compiler.compileModuleAndAllComponentsAsync(module.angularModule);
```

But i have this error : 
```
No NgModule metadata found for 't'
```

I think, this is because, i have two angular loaded (one for the main app, and one for the module). 

Then I hope a solution to answer this crutial problem for my application?

## What is the motivation / use case for changing the behavior?

My project is very modular, and module can be added on runtime. module can be added on by providing js file URL.

## Please tell us about your environment

<pre><code>
Angular version: 4.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

Angular doesn't load code, it is a responsibility of the module loader you are using to do that. For example webpack or system.js can load code via `System.import` api.
