### ISSUE TITLE
AoT imports always everything

### ISSUE THREAD

**Issue by Eddman** [angular/angular#18052]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

AoT compiler generates all imports as "star imports":
`import * as i0 from '@angular/core';`

## Expected behavior

AoT should generate imports like:
`import {moduleProvideDef, NgZone, ....} from '@angular/core';`

## What is the motivation / use case for changing the behavior?

It's working fine, but does not allow Rollup/Webpack to tree-shake correctly. In fact we have to bundle all angular code even if half of it may not be used.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.6
</code></pre>

**Comment by trotyl** [comment]
AFAIK namespace import won't affect tree-shaking in both Webpack & Rollup:

![image](https://user-images.githubusercontent.com/6059170/28061157-2668190c-665c-11e7-9a1f-1aa1a442be27.png)
An example could be found at [Rollup Repl](https://rollupjs.org/repl?version=0.45.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMG1hdGglMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuY29uc29sZS5sb2coJTIwbWF0aC5jdWJlKCUyMDUlMjApJTIwKSUzQiUyMCUyRiUyRiUyMDEyNSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBpc24ndCUyMHVzZWQlMjBhbnl3aGVyZSUyQyUyMHNvJTVDbiUyRiUyRiUyMFJvbGx1cCUyMGV4Y2x1ZGVzJTIwaXQlMjBmcm9tJTIwdGhlJTIwYnVuZGxlLi4uJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBnZXRzJTIwaW5jbHVkZWQlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBjdWJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3QlMkYlMkYlMjByZXdyaXRlJTIwdGhpcyUyMGFzJTIwJTYwc3F1YXJlKCUyMHglMjApJTIwKiUyMHglNjAlNUNuJTVDdCUyRiUyRiUyMGFuZCUyMHNlZSUyMHdoYXQlMjBoYXBwZW5zISU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

And if you're using Angular CLI, you can use `ng build --aot` to check the tree-shaking result:

![image](https://user-images.githubusercontent.com/6059170/28061340-d8aac84e-665c-11e7-8117-d1ba1087b9ce.png)

You can have a search for `unused harmony export`, that's what being removed.

As far as I can tell AOT are working fine with tree-shaking, if you've encounter something wrong and thought it may be a BUG, please provide a minimal reproduction according to the issue template.

**Comment by IgorMinar** [comment]
@trotyl is correct. start imports don't affect webpacks or rollups ability to identify unused symbols. There are other issues unrelated to the start imports that prevent the symbols from being removed. We are working on addressing this stuff.
