### ISSUE TITLE
Just In Time Download of JS files

### ISSUE THREAD

**Issue by eternalstudent2015** [angular/angular#1805]
Dear Friends,

Recently I am going through angular and learned many new things like gulp, gulp-inject, wiredep, browser-sync, jshint, jscs, etc. But since, I tried to learn everything at once, I am bit lost.

I have a very basic question. 
This is the front end of Application.
![app](https://cloud.githubusercontent.com/assets/12291261/7565752/346ccd2a-f810-11e4-9bfe-0f454298a35d.jpg)

This is the index.html

```
<!doctype html>
<html class="no-js" ng-app="eliteAdmin">
<head>
    <meta charset="utf-8">
    <title>Elite Schedule Admin</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="lib/bootstrap/dist/css/bootstrap.united.min.css"/>
    <link rel="stylesheet" href="styles/main.css">
</head>
<body>

<div id="applicationHost" class="container body-content admin-appHost">
    <div data-ng-include="'/app/layout/shell.html'"></div>
</div>

<div id="footer">
    <div class="container">
        <span class="pull-right text-info credit">Elite Schedule Admin - &copy; Steve Michelotti 1</span>
    </div>
</div>

<!-- Vendor Scripts -->
<script src="lib/angular/angular.min.js"></script>
<script src="lib/angular-route/angular-route.min.js"></script>
<script src="lib/lodash/dist/lodash.min.js"></script>
<script src="lib/moment/min/moment.min.js"></script>
<script src="lib/spin.js/spin.js"></script>
<script src="lib/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>

<!-- inject:js -->
<script src="app/app.js"></script>
<script src="app/directives/spinner.directive.js"></script>
<script src="app/home/home.controller.js"></script>
<script src="app/layout/shell.controller.js"></script>
<script src="app/leagues/leagues.controller.js"></script>
<script src="app/services/app-spinner.service.js"></script>
<script src="app/services/elite-api.service.js"></script>
<!-- endinject -->

</body>
</html>
```

Now, I under stand that in index.html, I need all those vendor scripts, because they are needed to work with all partial files that gets loaded, during application usage.

Coming to Application script, which we are injecting into index.html, I have one question.

Assume, I run the application, And application has one of the menu items by name "Leagues". It may so happen, that during this browser session, I may never click and visit "Leagues" screen.

So what is the need of including, following file in index.html, at the outset itself?
"app/leagues/leagues.controller.js"

Can't their be a way, that when a partial is viewed, at that time only(Just In Time), this .js file is downloaded to browser. Is such thing is possible?

Thanks,
Regards,

**Comment by pkozlowski-opensource** [comment]
@eternalstudent2015 this is wrong repo - this one is for Angular 2. Angular 1 repo is available under https://github.com/angular/angular.js. But I can answer your question here - Angular 1 doesn't oficially support on-demand code download, but this is something we are looking into in the 1.5 release time-frame.
