### ISSUE TITLE
"compile on save" doesn't work on my angular project !

### ISSUE THREAD

**Issue by alihasaniGit** [angular/angular#18058]
I created a new angular project by cli (ng new my-app) .. 
but the option "compile on save" doesn't work on my project !
I should be noted that i have two project on my PC, and "auto compile" works correctly for one of them and doesn't work for another .. 

* I changed the project's port but it doesn't work yet  ..
* compileOnSave option is true ..

 Please help me .. 
I'm boring !

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alihasaniGit** [comment]
Excuse me !
OK 
Thanks a lot ..
