### ISSUE TITLE
Cannot pass a function to directive if the function is not defined on the scope

### ISSUE THREAD

**Issue by mhdSid** [angular/angular#18057]
## I'm submitting a ...
[ x ] Bug report 

## Current behavior
We have a TypeScript class used as a component controller that has private and public members.
The component template is populated using $ctrl.controllerMemberName (where controllerMemberName belongs to the controller prototype). 

Within this component template we are passing a function, that is not defined on the scope, to another directive, and once that function is called from the directive, AngularJS throws an error "TypeError: Cannot use 'in' operator to search for '$ctrl'".

`<any data-function-to-be-called='$ctrl.fn()'></any>`   
Doesn't Work (fn belongs to component controller prototype)

`<any data-function-to-be-called='fn()'></any>`  
Works (fn is defined on the scope)

If we do scope.functionName = this.functionName in the component controller, then, it will be called normally without an error.

## Expected behavior
The function should be called properly same as defining it on the scope

## Please tell us about your environment

<pre><code>
Angular version: 1.6.3

Browser:
- [ X ] Chrome (desktop) version  59.0.3071.115
 
For Tooling issues:
- Node version: 7.5.0
- Platform: Mac

**Comment by gkalpak** [comment]
Wrong repo (this one if for Angular 2+). Please re-open on https://github.com/angular/angular.js.
