### ISSUE TITLE
Proposal: support @Inject on ES7 Class Property

### ISSUE THREAD

**Issue by Verdier** [angular/angular#1806]
Most of the time injected services are attached to the instance to be used in instance methods:
```javascript
class AComponent {
  constructor(@Inject(MyService) aService:MyService) {
    this.aService = aService;
  }
}
```
But using ES7 Class Properties (available with both Babel and TypeScript) it would be great to have something like:
```javascript
class AComponent {
  @Inject(MyService)
  aService;
}
```

**Comment by nomack84** [comment]
This could be an improvement. As the property should probably have a type, then the service could be guessed, just like how it works in Java EE.
``` javascript
class AComponent {
  @Inject()
  aService: MyService;
}
```
Even better, if the service implements an interface, like `Service`, then we could use the interface as the type and abstract the service implementation, like this:

``` javascript
interface Service {}
class MyService implements Service  {}

class AComponent {
  @Inject()
  aService: Service;
}
```
I'm not sure if this is possible with TypeScript, just proposing the way it works in JavaEE.

**Comment by pkozlowski-opensource** [comment]
How would this affect unit testing, that is, how one should pass mock dependencies? Reading through https://gist.github.com/jeffmo/054df782c05639da2adb it seems like property initilizers are executed before a constructor (?). If this is true than I should be setting mocks on object instances before a constructor is run (as a constructor might be accessing them). But how I could do without constructing an instance and running a constructor?

@Verdier did you consider how your proposal would work in the unit-testing environment?

**Comment by Verdier** [comment]
@pkozlowski-opensource: the property decorator gives you access to the property descriptor. The decorator could set the `get` function which is responsible of returning the service.

```javascript
function Inject(ServiceCtor) {
 return function(target, key, descriptor) {
  descriptor.get = function () {
   /* return the service instance */
  }
 }
}
```

**Comment by Verdier** [comment]
`get` attribute exists only on accessor properties. But, according to the current babel's implementation of class properties, property initialisers are called before the constructor, but no idea how to override the initialiser... looks like there is no solutions for now, will wait for proposal evolution.
