### ISSUE TITLE
Mechanism for reading dom properties

### ISSUE THREAD

**Issue by zlepper** [angular/angular#18068]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior
Only possible for read/write properties using `@HostBinding`.
Or you have to get the native dom element and read from that, but that prevent you from running in a web-worker. 

## Expected behavior
Ideally I would like something like `@HostBinding`, that i can attach in my component to be able to read a specific property of the DOM element my component is attached to. 

Something like this:
```ts
@Directive({
    selector: '[child]'
})
export class ChildComponent {

    @DomRead('offsetHeight')
    public height: number;

    @DomRead('offsetWidth')
    public width: number;

}
```
I don't think `DomRead` is a good idea for the name, but i hope it gets the point across. 

## What is the motivation / use case for changing the behavior?
Reading dom properties, like [offsetHeight](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight) and [offsetWidth](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth) is extremely crucial to you want to do thing like masonry or drag-to-select. Both of which require knowledge about the size of elements. 
Using `style.height` and `style.width` will not work with dynamically sized elements.

**Comment by robwormald** [comment]
So I understand *why* you're asking this, but there are some technical challenges to be aware of that make this non-trivial.

The current `@HostBinding` / `@HostListener` pair are both reasonably efficient, because:
- in the case of `@HostBinding`, Angular only has to write to the DOM when a value changes (which Angular is already tracking)
- in the case of a `@HostListener`, an *event* is fired that notifies Angular.

What you're proposing doesn't work this way : it would require Angular to continually (effectively, on every change detection run) *poll* the DOM to read a property out of it. In all cases, this is pretty inefficient (nowhere else in Angular do we query the DOM this way), and in the worst case, reading properties can cause the reflows and layout thrashing - see the list here of props that cause reflows - https://gist.github.com/paulirish/5d52fb081b3570c81e3a 

In cases where some event fires to notify a change (say, `resize`) it's possible, but not something we can really do for arbitrary properties.

**Comment by zlepper** [comment]
I see your points, however I would like to make a revised proposal and a couple of counter points:

## Revised proposal:
@Directive({
    selector: '[child]'
})
export class ChildComponent {

    @DomRead('offsetHeight')
    public height: () => Observable<number>;

    @DomRead('offsetWidth')
    public width: () => Observable<number>;

}
Turning the properties into functions that then returns a one-off observable. would move the responsibility of knowing, when a reread would be needed to the user. 
Because angular can indeed not know correctly when things have changed. However the developer who actually implements angular in their project should have knowledge of when sizes changes. (img-load, css props, class changes, resize etc.)
The reason i'm saying this should return an observable is so angular can do the following:
* Batch all the reads
* Switch to DOM context (If we are in WebWorker mode)
* Do all the reads at once (This prevent repeated layout trashing and such)
* Switch back to previous context (e.g. WebWorker mode)
* Push the next value to the observable, and close it. (One-off observables)

The last things means that people have to be explicit *every single time* they want to know the value of the property. Which makes it more clear to them that they are doing something here that could potentially be really really really slow.

As far as what you are worried about with the layout trashing: This happens in vanilla implementations either way. And it happens if we are using ElementRef. I cannot really get worse. A naive implementation of say masonry checks the dom every so often. A more mature implementation knows when it needs to check. 

Also: Big warning on the documentation that this still obeys the laws of the dom, and properties that requires recalculation in vanilla still requires recalculation in angular.

**Comment by zoechi** [comment]
I'd just use a `MutationObserver` and read from `ElementRef.nativeElement`

**Comment by zlepper** [comment]
That doesn't seem to take into consideration that changes to elements can be caused by things happening above the element. Consider the following css:

```css
.foo {
    height: 100px;
}

.bar .foo {
    height: 200;
}
```

Now i measure the height of `.foo` to be 100 and add my mutation observer. 
Then I go and add the `bar` class to a parent element of `.foo`. This has to trigger the mutation observer, but as far as I can read from the mdn docs, it won't, as it only looks down. (Plus all the other things that can cause element sizes to change. 

If you suggestion was meant as for how I could get around it and get implementations working, then yes your solution could work. Provided i don't need/want to be in a webworker. ElementRef.nativeElement is only available in the default renderer afaik.

**Comment by zoechi** [comment]
@zlepper Angular also can't do anything that the browser itself doesn't provide.  
In this case use `ngDoCheck()` which is called every time change detection is run and read the property there. 
I think it's highly unlikely that the Angular team will want something added to Angular that is that inefficient and I also don't see how this would be a common enough use case to justify that.

**Comment by zlepper** [comment]
That's were we disagree. I think the usecase for being able to read the dom is quite high. This question on SO for example has over 17000 views as i'm writing this: https://stackoverflow.com/questions/34919738/getting-element-height-angular-2

Which is why i wrote the second proposal. That removes any requirements for angular to know when is has to check, it falls back to the user.  

And as far as I know, I cannot make new decorators that can latch into angular in the above described way, it has to be part of angular itself.

**Comment by Toxicable** [comment]
>That removes any requirements for angular to know when is has to check, it falls back to the user.

I don't understand what you mean here. If you have an Observable stream of `offsetHeight` then Angular still has to feed that stream with values, meaning we're right back to where we started with layout thrashing.

**Comment by zoechi** [comment]
@zlepper your 2nd proposal ignores that the other decorators like `@ViewChild()` don't read from the DOM, but instead Angular has that information when it compiles the component or when Angular code modifies the DOM already.
There is no point in using an Angular decorator for that use case that is diametral to other Angular decorator uses.
You can just write a few lines of code and be done.

**Comment by zlepper** [comment]
> I don't understand what you mean here. If you have an Observable stream of offsetHeight then Angular still has to feed that stream with values, meaning we're right back to where we started with layout thrashing.

Every call to the bound value would return a new stream. Just like it happens with the http service. This means that angular doesn't read anything before the function call happens, and actually not even until a subscription to the observable hpapens. 

> You can just write a few lines of code and be done.

Can you point me to how i make some parts webworker, and some parts not-webworker then? Because i don't see that anywhere in my search for it. 

> your 2nd proposal ignores that the other decorators like @ViewChild() don't read from the DOM, but instead Angular has that information when it compiles the component or when Angular code modifies the DOM already. 

I'm not saying it should be a decorator, but for me as someone who integrates with angular, it seems to be the same thing. I'm wrong apparently, but that was not obvious to me initially.

**Comment by zoechi** [comment]
Sorry, I don't know about WebWorker.

**Comment by Bidthedog** [comment]
I have a similar use-case, but I'd just like to be able to read the DOM style properties on demand. I've created a directive that allows me to add a css class to element on mouse over. I'm using [animate.css](https://daneden.github.io/animate.css/), which won't apply animations to inline items. I want to detect the display attribute's property and if it's set to 'inline', set it to 'inline-block':

```
import { Directive, ElementRef, HostListener, Input, Renderer, HostBinding, AfterViewInit } from '@angular/core';

@Directive({
  selector: '[animateOnMouseOver]'
})
export class AnimateOnMouseOverDirective implements AfterViewInit {
  @HostBinding('class.animated') animated: boolean = true;

  @HostBinding('style.display') display: string;

  @Input('animateOnMouseOver') animationClass: string;

  @HostListener('mouseenter') onMouseEnter() {
    this.getClassList().add(this.animationClass);
  }

  @HostListener('webkitAnimationEnd')
  @HostListener('mozAnimationEnd')
  @HostListener('MSAnimationEnd')
  @HostListener('oanimationend')
  @HostListener('animationend') onAnimationEnd() {
    this.getClassList().remove(this.animationClass);
  }

  constructor(
    private renderer: Renderer,
    private el: ElementRef
  ) { }

  ngAfterViewInit(): void {
    const e = this.el.nativeElement.style.display;
    if (e === 'inline') {
      this.renderer.setElementStyle(this.el.nativeElement, 'display', 'inline-block');
    }
  }

  private getClassList(): DOMTokenList {
    return this.el.nativeElement.classList as DOMTokenList;
  }
}
```

Is this even possible at the moment? I can't seem to find any way to read the style properties - I've played around with @HostBinding and @Input with no luck.

**Comment by pkozlowski-opensource** [comment]
As @robwormald pointed out reading dom properties as part of the change detection could bring performance of an application to its knees. I don't think that we are going to implement it as:
* already possible to read DOM on the user side;
* such feature would be very easy to miss-use.
