### ISSUE TITLE
4.3.0-rc.0 Animation common scenario problem with child route

### ISSUE THREAD

**Issue by Bretto** [angular/angular#18065]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The animation is not triggered

**Expected behavior**

The animation should be triggered

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/xJXIsZbEsssh5GTicU55?p=preview

**What is the motivation / use case for changing the behavior?**

__Note:__
@matsko, @mlc-mlapis Have already contributed to this issue, this is a follow up of as it was closed: https://github.com/angular/angular/issues/17349
https://github.com/angular/angular/issues/17517

With the shiny new 4.3.0-rc.0 animations it should be simple to do a transition between pages, but as you guest it I can't find a way to do it ! I have create this plunkr http://plnkr.co/edit/xJXIsZbEsssh5GTicU55?p=preview to show my struggle... I think the issue is because I am using a child route but this is such a common scenario that there must be a way to get this to work simply and so the bug report (It could be my ignorance though, let me know, but I have ask around and was recommended to log an issue...)

**Please tell us about your environment:**

os: linux x64

* **Angular version:** 2.0.X

@angular/cli: 1.1.1
@angular/animations: 4.2.0-rc.2
@angular/common: 4.2.0-rc.2
@angular/compiler: 4.2.0-rc.2
@angular/core: 4.2.0-rc.2
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.2.0-rc.2
@angular/http: 4.2.0-rc.2
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.0-rc.2
@angular/platform-browser-dynamic: 4.2.0-rc.2
@angular/router: 4.2.0-rc.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 2.4.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript X.X

* **Node (for AoT issues):** `node --version` =   
node: 7.0.0

**Comment by matsko** [comment]
@Bretto let's start a new issue (since there are three issues that you've posted). There have been a few fixes with querying in the recent versions of Angular. Making a new issue can help us figure out exactly what's broken. Please create a new issue and I'll get to it right away.
