### ISSUE TITLE
Rendering derived components dynamically fails without AOT activated

### ISSUE THREAD

**Issue by bpaetzold** [angular/angular#18060]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Rendering derived components dynamically doesn't work in dev-mode.

## Expected behavior

Rendering derived components dynamically should be possible in dev-mode.

## Minimal reproduction of the problem with instructions

* Create a base-component.
* Create a component wich extends the base component. This component should inject one or another services.
* Create another component, which uses the ComponentFactoryResolver to render the derived component from step 2 dynamically into its template.
* Start `ng serve` and check the result
* You'll get the following error message: `ERROR Error: Uncaught (in promise): Error: Can't resolve all parameters for XXXComponent: ([object Object], ?).`
* Now stop the dev-server and restart with the following command: `ng serve --aot`
* Check the page again, the component should be rendered properly.

## What is the motivation / use case for changing the behavior?

We need to develop a complex process flow model with many derived, dynamically rendered components. It's not possible to develop this efficiently with `ng serve --aot`.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 54.0.1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 40.15063.0.0
 
For Tooling issues:
- Node version: 8.1.2 
- Platform: Windows

Others:

</code></pre>

**Comment by Toxicable** [comment]
Could you create a minimal reproduction and make a github repo for it so we can see this?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
