### ISSUE TITLE
extraProviders not provided from @angular/platform-server#renderModuleFactory 

### ISSUE THREAD

**Issue by alQlagin** [angular/angular#18070]
## I'm submitting a...

<pre><code>
[   ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[   ] Feature request
[   ] Documentation issue or request
[   ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Trying to provide `APP_BASE_HREF` for fixing `URLs requested via Http on the server must be absolute` for `@angular/platform-server`

## Current behavior

`APP_BASE_HREF` is empty

## Expected behavior

Expect `APP_BASE_HREF` to be availiable with provided value 

## Minimal reproduction of the problem with instructions

**service which uses `APP_BASE_HREF`**

```
@Injectable()
export class MyService {
    constructor(private http: Http, @Inject(APP_BASE_HREF) private baseHref: string) {

    }

   makeRequest(){
       return this.http.get(this.baseHref + '/endpoint')
   }
}
```

**value provided with**

```
renderModuleFactory(AppServerModuleNgFactory, {
            document: htmlString,
            url: myUrl,
            extraProviders: [{provide: APP_BASE_HREF, useValue: baseHost}]
        })
```

## Environment

<pre><code>
Angular version: 4.2.6
@angular/core
@angular/platform-server

 
For Tooling issues:
- Node version: 7.2.0  
- Platform: Windows  

</code></pre>

I was trying change in platform-server.js from 
```
function _getPlatform(platformFactory, options) {
    const /** @type {?} */ extraProviders = options.extraProviders ? options.extraProviders : [];
    return platformFactory([
        { provide: INITIAL_CONFIG, useValue: { document: options.document, url: options.url } },
        extraProviders
    ]);
}
```

to
 
```
function _getPlatform(platformFactory, options) {
    const /** @type {?} */ extraProviders = options.extraProviders ? options.extraProviders : [];
    return platformFactory([
        { provide: INITIAL_CONFIG, useValue: { document: options.document, url: options.url } },        
    ].concat(extraProviders));
}
```

This fixes extra providers list in createPlatformFactory result function, but bot solves my request

**Comment by vikerman** [comment]
Can you please provide a repro for this?
