### ISSUE TITLE
Extend AbstractControl

### ISSUE THREAD

**Issue by angular-user** [angular/angular#18071]
Hi there,

Is there any way to extend the basic AbstractControl and use it instead of the existing AbstractControl.
Something like below.
```
class CustomAbstractControl extends AbstractControl {
public label: string;
....
}
```
Regards
Steve

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by angular-user** [comment]
I think even allowing to add some metadata to the Abstractcontrol would open some great possibilities for metabased development. Anyway I had this question asked in Stackoverflow and no replies. So I think this means it is not possible. What is the point of not able to extend certain in-built classes and call it complete framework.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
