### ISSUE TITLE
Docs: add scripts to test if polyfill is required

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#18089]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In the browser support guide, it's only mention what polyfills are needed for each browser.

## Expected behavior
Along the needed polyfill, guide should contain a simple script to test if the polyfill is needed, example for Intl:
```js
window.Intl && window.Intl.NumberFormat && window.Intl.DateTimeFormat
```

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
We can use this scripts to determine if polyfill needs to be loaded, so the app overall would load faster. Angular team knows exactly what features are needed and could provide a test that won't fail in some odd cases, like when feature is partially supported in browser.

**Comment by kapunahelewong** [comment]
Hey @dawidgarus thanks for bringing this point up, but this starts getting out of scope for the docs. Have you tried [https://polyfill.io/](https://polyfill.io/)? It allows you to specify the features you are interested in ([https://polyfill.io/v2/docs/api](https://polyfill.io/v2/docs/api)). That's what we're using for [angular.io](https://angular.io).

Would you mind if we closed this issue?

**Comment by jenniferfell** [comment]
Idea: Within the docs scope, we might want to include a note box or a related resources list at the end with these links:  https://polyfill.io/ and https://polyfill.io/v2/docs/api

**Comment by brandonroberts** [comment]
Since Angular V5, we no longer rely on `Intl` for i18n, so this issue is no longer relevant moving forward.
