### ISSUE TITLE
Adding @angular/animations issues

### ISSUE THREAD

**Issue by pfrendo** [angular/angular#18088]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Application does not start, the issue occurs when I add ```BrowserAnimationsModule``` as an import.

I get the following issues:

```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends [as a] (tslib.es6.js:22)
    at animations.es5.js:19
    at Object.ENVIRONMENT_TYPE.unset (animations.es5.js:47)
    at __webpack_require__ (bootstrap 5ec3f18…:657)
    at fn (bootstrap 5ec3f18…:85)
    at Object.defineProperty.value (app.module.client.ts:6)
    at __webpack_require__ (bootstrap 5ec3f18…:657)
    at fn (bootstrap 5ec3f18…:85)
    at Object.options.path (boot-client.ts:7)
```

```
./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
47:2-18 "export 'AnimationBuilder' was not found in '@angular/animations'
./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
78:2-18 "export 'AnimationFactory' was not found in '@angular/animations'
./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
612:15-31 "export 'AnimationBuilder' was not found in '@angular/animations'
./~/@angular/animations/@angular/animations/browser.es5.js
39:35-45 "export 'ɵPRE_STYLE' was not found in '@angular/animations'
./~/@angular/animations/@angular/animations/browser.es5.js
2214:29-39 "export 'ɵPRE_STYLE' was not found in '@angular/animations'
./~/@angular/animations/@angular/animations/browser.es5.js
3802:97-107 "export 'ɵPRE_STYLE' was not found in '@angular/animations
```

## Expected behavior

I expect that my application starts..

## Environment

<pre><code>
Angular version: 4.2.6

Browser:
- [X] Chrome (desktop) version Latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.3 
- Platform:  Windows

Others:

</code></pre>

**Comment by matsko** [comment]
@jasonaden do we include the polyfills code automatically? It looks like `...something` is causing an issue for us when downlevelled to es5.

**Comment by jasonaden** [comment]
@matsko We don't include them as part of the library. They get included though in the default CLI project AFAIK.

But I'm not sure how `...something` would be causing this issue. Is it an object spread, arguments spread, or rest args? Not that it really matters because I think all of these get downleveled to not need polyfills.

**Comment by ergwun** [comment]
@pfrendo Did you find a workaround for this yet?

**Comment by WendieSulkers** [comment]
@pfrendo same question here: did you find a workaround?

**Comment by butsaty** [comment]
@pfrendo did you solve the problem?

**Comment by millsb** [comment]
@pfrendo I encountered this issue using .NET Core's SPA templates, which separate app and vendor bundles using the webpack DLL plugin. For me, the issue was that I had upgraded the version of angular in `package.json` without re-running the webpack command for the vendor build. So the app bundle was building against the wrong Angular version. Re-building the vendor bundle fixed this.

**Comment by shug1565** [comment]
@millsb thanks. It works. Quick question. Do I always need to run webpack after upgrading a package or just for Angular?

**Comment by millsb** [comment]
I think it would apply to any package upgrades.

**Comment by matsko** [comment]
@pfrendo is this issue still relevant?

**Comment by vicb** [comment]
Closing as obsolete
