### ISSUE TITLE
docs(platform-server): PlatformOptions interface missing in API

### ISSUE THREAD

**Issue by trotyl** [angular/angular#18085]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

No [PlatformOptions](https://github.com/angular/angular/blob/master/packages/platform-server/src/utils.ts#L21-L25) interface found in [API](https://angular.io/api), but it's used in [renderModuleFactory](https://angular.io/api/platform-server/renderModuleFactory) & [renderModule](https://angular.io/api/platform-server/renderModule).

![image](https://user-images.githubusercontent.com/6059170/28150286-38d054ea-67c6-11e7-842d-4cd7f20a643a.png)

## Expected behavior

Since every type used in public API should also be public API, the PlatformOptions interface should be published.

## Minimal reproduction of the problem with instructions

+ Open [API](https://angular.io/api);
+ Search for `PlatformOptions`;
+ Found nothing.

## What is the motivation / use case for changing the behavior?

Make the doc better.

Question in: should [PlatformConfig](https://github.com/angular/angular/blob/master/packages/platform-server/src/tokens.ts#L16-L19) extends [PlatformOptions](https://github.com/angular/angular/blob/master/packages/platform-server/src/utils.ts#L21-L25) or should they be merged?

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
This is actually an issue for the `platform-server` team. It is not being documented because it is not being exported outside the entry point to the platform-server package.
