### ISSUE TITLE
ngComponentOutlet with NgModule is not AoT compatible

### ISSUE THREAD

**Issue by manju-reddys** [angular/angular#18082]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

NgComponentOutlet suppose support dynamic (inline template) component creation to inject the template loaded at runtime.

I have followed the example shown in the document page getting error:
[Document](https://angular.io/api/common/NgComponentOutlet)
My code 

    private createOrUpdateComponent(html: string) {
        @Component({
            selector: 'behavior-description',
            template: html,
            styles: ['p{font-size: .87rem; color: #333;} small{font-size: 13px; color: #666;}']
        })
        class BehaviourDescription {
            constructor( @Inject('behavior') public behaviour: any) { }
        }

        this.descriptionComponent = BehaviourDescription;

        @NgModule({
            imports: [
                CommonModule
            ],
            declarations: [BehaviourDescription],
            entryComponents: [BehaviourDescription],
            providers: [{ provide: 'behavior', useFactory: () => this.behaviour }]
        })
        class RuntimeModule { }
        this.runtimeModule = this.compiler.compileModuleSync(RuntimeModule);
    }
```
Error
```

     vendor.8d19d02….bundle.js:1 ERROR Error: No component factory found for e. Did you add it to 
     @NgModule.entryComponents?
       at Q (vendor.8d19d02….bundle.js:1)
       at t.resolveComponentFactory (vendor.8d19d02….bundle.js:1)
       at t.resolveComponentFactory (vendor.8d19d02….bundle.js:1)
       at t.resolveComponentFactory (vendor.8d19d02….bundle.js:1)
       at t.ngOnChanges (vendor.8d19d02….bundle.js:1)
       at bn (vendor.8d19d02….bundle.js:1)
       at sr (vendor.8d19d02….bundle.js:1)
       at or (vendor.8d19d02….bundle.js:1)
       at jr (vendor.8d19d02….bundle.js:1)
       at Object.o.ɵvid.n [as updateDirectives] (2.2638332….chunk.js:1)

```

## Expected behavior

Suppose to be work as in AoT compile code.

## What is the motivation / use case for changing the behavior?

The template is not predefined in my case and the UI receive the input based on configuration in server and it will be changed while the application is up and running.

## Environment

Angular version: 4.2.4

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  <!-- run `node --version` -->
- Platform:  <!-- Mac, Linux, Windows -->

Others:

**Comment by alexzuza** [comment]
Please add plunker to reproduce your issue

**Comment by Alekcei** [comment]
Jit and Aot https://github.com/angular/angular/issues/15510

**Comment by manju-reddys** [comment]
@alexzuza This issue is after AoT build and I don't think so we can have plunker to this. 
@Alekcei Thanks I'm following that ticket now to see if could find some work-around.

**Comment by Alekcei** [comment]
@alexzuza
  ```value = `<span>Test interpolation {{5 + 6}}</span>`;```
If using  complex component containg attributes. That it will not work.

**Comment by chuckjaz** [comment]
@manju-reddys Can you provide a small repository that reproduces the issue?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
