### ISSUE TITLE
4.3.0-rc.0 Content-Type header missing boundary parameter when posting multipart/form-data content

### ISSUE THREAD

**Issue by simke9445** [angular/angular#18096]
I've been experimenting with uploading files using HttpClient & HttpRequest from HttpClientModule in angular/common/http.

## I'm submitting a...

<pre><code>
[] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Default behavior when uploading a file using a post request with HttpClient is that the Content-Type header of the request is set to detected file type ( e.g. Content-Type=multipart/form-data without the boundary parameter specified).

## Expected behavior

The body and the header should contain the same metadata regarding Content-Type and boundary, and in our case only the body contains the boundary, the header does not, which will result in our request failing.

## What is the motivation / use case for changing the behavior?

In file /packages/common/http/src/xhr.ts the request handling is defined, where we can find one interesting snippet.
<pre><code>
// Auto-detect the Content-Type header if one isn't present already.
if (!req.headers.has('Content-Type')) {
  const detectedType = req.detectContentTypeHeader();
  // Sometimes Content-Type detection fails.
  if (detectedType !== null) {
   xhr.setRequestHeader('Content-Type', detectedType);
  }
 }
</code></pre>
As most browsers will automatically detect the Content-Type and fill out the missing header with proper values for Content-Type & boundary, manually setting the Content-Type will override that behavior, and the submitted request will result in an incomplete Content-Type header.

I've fixed the issue by removing the code section above, and delegating the Content-Type detection to the browser itself, which will properly set the boundary parameter.

## Environment

<pre><code>
Angular version: 4.3.0-rc.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.7.1  
- Platform:  Windows 

</code></pre>

**Comment by alxhub** [comment]
You are correct, `HttpClient` should not set a Content-Type for outgoing `FormData` objects and rely on the browser detecting it correctly.
