### ISSUE TITLE
Form Control for '<select>' do not trigger 'valueChanges' subscription when selection changed

### ISSUE THREAD

**Issue by garkuwa** [angular/angular#18090]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Hi,
I have on template:

//<form [formGroup]="form" >

//<select formControlName="programId" class="form-control input-sm">
  //                        <option [ngValue]='null'>Select Program</option>
    //                      <option *ngFor="let item of this.programs" [value]="item.id">{{item.name}}</option>
 ///</select>

///</form>

 and on component class I'm trying to subscribe for select value changes:

...
ngOnInit() {
    this.form.get('programId').valueChanges.subscribe(()=>{
     alert ('changed')
})
}
..........

 But this observable subscription never triggered (when I change my select option using mouse ). It is working if I subscribe to form valueChanges, but I do not want to receive notifications from all components.

## Expected behavior

I can subscribe to select FromControl and receive notifications when selected option was changed.
 
## Minimal reproduction of the problem with instructions

Look code above

## Environment

<pre><code>
Angular version: 4.2.1

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

Works fine here: https://plnkr.co/edit/StTU4ruyrFEfbgTqycWU?p=preview
Also `*ngFor="let item of this.programs" ` should be `*ngFor="let item of programs" `

**Comment by garkuwa** [comment]
thanks
