### ISSUE TITLE
Quickstart Directions on Angular.io are incorrect

### ISSUE THREAD

**Issue by dogsoldier68** [angular/angular#18099]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Causes an error in git bash (https://angular.io/guide/quickstart#serve)
$ ng serve --open
node_modules appears empty, you may need to run `npm install`

## Expected behavior

browser opens the App

## What is the motivation / use case for changing the behavior?

If you download the example app (by clicking the link, etc), it includes the full /node_modules directory, however if you just follow the directions you don't have a full /node_modules directory, therefore the app fails to launch.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by baluragala** [comment]
Hi @dogsoldier68,
Executing the below command will not only scaffold the project structure and necessary files but also does npm install automatically. For whatever reason auto npm install fails you have to do it manully.
ng new <app-name>

**Comment by Toxicable** [comment]
This looks like something changed in the CLI, it prints out 
>Installing packages for tooling via npm.

But does not actually install the packages.

--
As a work around your can install the packages yourself with `npm install`

**Comment by aravindfz** [comment]
By default ,CLI creates and installs node_modles So which version your using?

**Comment by gkalpak** [comment]
I tried with v1.2.1 and it doesn't indeed install dependencies.

**Comment by gkalpak** [comment]
@dogsoldier68, can you share more info on your environment (OS, node/npm version etc).

**Comment by gkalpak** [comment]
It turns out this was a `@angular/cli` issue. The @filipesilva (from the cli team) has identified the problem and is working on a fix.

What actually happens is that the `ng new` process exits prematurely, while the dependencies are still being installed in the background. If you try to run `ng serve` immediately it will fail, but if you wait for a while (until the dependencies are installed in the background) then everything works as expected.

##
Closing since it is not an angular.io issue per se. Thx for bringing it to our attention, @dogsoldier68

**Comment by filipesilva** [comment]
PR to fix: https://github.com/angular/angular-cli/pull/7033
