### ISSUE TITLE
dynamic component data not synced with outside

### ISSUE THREAD

**Issue by paulluap** [angular/angular#18094]
Experimenting with the dynamic component loading technique showed in the tutorial: 

https://angular.io/guide/dynamic-component-loader

Then I experimented with the data sync. 

https://plnkr.co/edit/LwhQNiApEr9vLzozEbqb?p=preview

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Both the inputs inside and outside the ad box update the ads data. 
But the outside inputs do not update the data in the ad box. 

## Expected behavior

The data in different parts should be synced. 

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/LwhQNiApEr9vLzozEbqb?p=preview

## What is the motivation / use case for changing the behavior?

Nothing seems special in the example, so the data syncing should also work. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by tytskyi** [comment]
See deep `data` property https://plnkr.co/edit/dF7RSoobPYlqc91ofewi?p=preview

**Comment by paulluap** [comment]
@tytskyi Thanks for the solution! 

Not sure if it is documented ?

**Comment by paulluap** [comment]
sorry for the trouble, my mistake...
