### ISSUE TITLE
Support server side rendering

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#1810]
This has been mentioned a few times in passing at various conferences or interviews but I haven't heard of an official way to track status on this feature. I figure this can be the ticket where we get an official word from the core team on the extent to which this is supported, if at all.

Currently my understanding is that this is:
 * possible given the architecture, but still hard
 * there are open problems left to solve
 * the team has been focused on other priorities for the time being.

**Comment by tbosch** [comment]
Hi,
yes, agree with your analysis!

**Comment by tbosch** [comment]
Here is a design doc that is a lot work in progress / place for putting ideas: https://docs.google.com/document/d/1M9FmT05Q6qpsjgvH1XvCm840yn2eWEg0PMskSQz7k4E/edit

**Comment by mhevery** [comment]
This is a too high level, and not actionable goal. We have plans to do something like that, but let's not keep it in the issue tracker.
