### ISSUE TITLE
Open up routing to allow a component to be created, from a URL, and injected into a given location, or equivalent functionality where imperative navigation into multiple dynamically named router outlets is required

### ISSUE THREAD

**Issue by williamBurgeson** [angular/angular#18102]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

I have created a dynamic multiple container for a system I am working on, and I wanted to be able to create arbitrary components, based on the routing system of the current application, from a URL, and in my case, to inject into a given div.

I am aware that routing supports more than one single router outlet, however what I need is either multiple dynamically named outlets, together with the ability to *programmatically* inject from an internal URL into one of these outlets, or a reasonably simple method of implementing this myself.

I managed to do this, and I have adapted the code I wrote and shared it on github; see below:

https://github.com/williamBurgeson/dynamic-route-based-component-creation-sample

Everything outside of the dynamic-component-creator folder is effectively a test harness. The dynamic component creator service takes a URL string and a ViewContainerRef and leans on the existing routing functionality where possible to create and inject the required component.

The vast bulk of the code is copied and pasted straight out of the angular source code as it stood a week or so ago - method by method to avoid pulling down more than necessary. If you diff using a decent tool hopefully it should be clear what is the same and what is different (the differences are mostly due to visibility and ts def files being different from the actual source code). 

The code with the createComponentFromUrl(...) method itself is based on the code in router.runNavigate() from within the angular code.

In terms of the app, if you navigate to "/page" in the browser, this will load the SimpleNoArgs component; if you navigate to "/page/[message]" (ie put a url arg after page) it will load SingleUrlArg component.

Likewise, if you just navigate to the root, and type in these URLs in the text boxes, it will create and inject the given components immediately below. Inside the components themselves everything should be as close as possible as if they had been navigated to directly.

Although the solution I have come up with works (it doesn't support route guards, pre-activation etc, however would be sufficient for our purposes), it is highly undesirable to have to pull and copy so much code from angular, so if you can consider adding some equivalent functionality to angular this could allow us in due course to get rid of our own code and have a much cleaner implementation with less complexity in our own app.

**Comment by Toxicable** [comment]
Can you be a bit more concise and specific on your proposal?
What exactly does your proposal introduce?
What would the API surface look like?

**Comment by williamBurgeson** [comment]
A number of possibilities, but essentially to allow us to programmatically inject components based on an URL (i.e. defined within the routing definitions of the given application) into multiple, dynamically named routers.

1) a solution might be simply to expose 

**router.injectComponent(componentUrl: string, target: ViewContainerRef);** 

in a similar way to how I have implemented in the DynamicComponentCreatorService in the project (where ViewContainerRef is a div or similar referenced with a @ViewChild hook).

2) Or possibly open up the RouterOutlet to expose a dynamic "name" property (or similar), plus a programmatic activateFromUrl (it currently exposes activateWith(...) however these require an ActivatedRoute) - we could then have 

**<router-outlet #routerOutlet>&lt;/router-outlet>** 

within the HTML of a component, and then in the code 

**this.routerOutlet.activateWith('page/hello');**

For this request it's more about the desired functionality - to be able to inject a component defined within the app into a dynamically defined location within the DOM (e.g. a dynamically added RouterOutlet), rather than the precise API definition.

If you run the project it should work as described above. Apologies I should probably have put more of the description into the actual repo readme: the repo was created purely to provide an example of the desired functionality.

The important thing is that any components created and injected using this method should be able to be navigated to directly in the browser as well as within the container.

Hope this helps

**Comment by jasonaden** [comment]
@williamBurgeson I'm not seeing anything in the example you sent. Are there commits missing? There's only the initial CLI commit at that link.

**Comment by williamBurgeson** [comment]
Apologies - my mistake; I had forgotten to commit and push, and I was away for a few days.
