### ISSUE TITLE
[Question] Is server side rendering going to be a real feature or not?

### ISSUE THREAD

**Issue by jbeckton** [angular/angular#18112]
Since the 4.0 release I have noticed there were some docs on angular.io about setting up server side rendering, now they are gone.

I am trying to figure out if Universal / Server Side Rendering is currently production ready or not. Some of the seed projects or examples showing server side rendering are still using beta versions of "@nguniversal/express-engine": "^1.0.0-beta.0". I did find another example that was using the angular cli and it did not use the express engine at all but lazy loaded modules did not render on the server and display with the initial document loaded into the browser..

Some of us have waited a long time for Universal to get merged into the angular core and become a real feature but it does not appear to me like Google is putting it out there as a real feature. This is still an illusive topic, lots of people blogging about it but I don't see much officially on it.

Can someone from Google shed some light on this subject? I would like to know the correct way to implement server side rendering.  It's easy to find articles and blogs on Universal for Angular 2.x but not so much for Universal since it was merged with Angular core in 4.x . It's advertised as a feature but not much of it is documented and there is no official examples, tutorials, seeds or quick start for server side rendering.

**Comment by Toxicable** [comment]
`platform-server` has been in core since 4.0 which is the core part of universal and is production ready.
There is a PR in flight to update the docs for Universal, you can track it here #17573

**Comment by dmitrysteblyuk** [comment]
Here's the example I used to implement rendering on server side (with lazy-loaded modules and all):
https://github.com/mlaval/optimize-angular-app

**Comment by jbeckton** [comment]
Thanks @Toxicable I will keep an eye on that PR.
