### ISSUE TITLE
how to make responsive google map using agm

### ISSUE THREAD

**Issue by vishalbiradar** [angular/angular#18113]
I would like to have my marker/markers appear on the viewport when my screen size decreases, but the angular-google-maps hides the marker/markers when i decrease the screen dimensions and i have to scroll to view the markers.
The current code I am using from agm is not responsive.So how to make it responsive so that the markers will be visible in any screen without dragging them.

```
<agm-map [latitude]="lat" [longitude]="lng">  
 <agm-marker> [latitude]="lat" [longitude]="lng"></agm-marker> 
</agm-map>
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
