### ISSUE TITLE
XHR service should support methods other than GET

### ISSUE THREAD

**Issue by pavelgj** [angular/angular#1811]
Currently `XHR` service only supports GET HTTP method. Please implement support for other methods.

**Comment by pkozlowski-opensource** [comment]
@pavelgj I think that the current XHR service is to be used by the compiler only to fetch templates for directives. @jeffbcross is working on the fully-featured backend-access service.

@tbosch @mhevery I think that we had similar issues already, IMO we should make it very clear that the current XHR is only for the compiler. Happy to send a PR if we all agree that the current service is compiler-private.

**Comment by mhevery** [comment]
as pawel points out that is not our plan.
