### ISSUE TITLE
App not loading in IE9 issue

### ISSUE THREAD

**Issue by stejokrishna** [angular/angular#18116]
## I'm submitting a 
```
[ ] Regression (behavior that used to work and stopped working in a new release)
[*] Bug report <!-- Please search github for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```
## Current behavior
I enabled poly fills to make my app work in IE9, but still app is not working. 

Enabled below poly fills:
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

![angular4_ie9_issue](https://user-images.githubusercontent.com/7432941/27372344-f0cd34ec-5681-11e7-8646-ffd912e32002.PNG)

## Expected behavior
 When poly fills are enabled expect app should start working in IE9. 

## Current behavior
"@angular/cli": "1.2.0",
node: 6.10.0
os: Windows 10 x64
"@angular/animations": "4.2.6",
 "@angular/common": "4.2.6",
 "@angular/compiler": "4.2.6",
 "@angular/core": "4.2.6",
 "@angular/flex-layout": "2.0.0-rc.1",
 "@angular/forms": "4.2.6",
 "@angular/http": "4.2.6",
 "@angular/material": "2.0.0-beta.7",
 "@angular/platform-browser": "4.2.6",
 "@angular/platform-browser-dynamic": "4.2.6",
 "@angular/router": "4.2.6",
"@angular/compiler-cli": "4.2.6",

Browser:
```
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version 9
- [ ] Edge version XX
```

**Comment by trotyl** [comment]
This is an Angular CLI issue and already fixed by https://github.com/angular/angular-cli/pull/6496 in version 1.1:

![image](https://user-images.githubusercontent.com/6059170/28206172-8abcb8d8-68b7-11e7-86e1-e60ce0fc77ec.png)

Please upgrade your CLI version to fix that. If it's an existing project, you may need to change the `polyfills.ts` file manually.
