### ISSUE TITLE
How can we call angular functions  by native javascript  in angular 4 

### ISSUE THREAD

**Issue by jsercao** [angular/angular#18118]
In AnglarJS ,we can  use `angular.element(appElement).scope()` get $scope, and use the `$apply ()`, so as to make the native javascript can directly call angular functions or  two-way binding, but in the Angular 4 how could we call angular functions or  two-way binding by native javascript  or the android native .

For example :

The web is developed by angular 4, used in the android webview, it needs to interact with android,  what's the solution ?

Thank you for your attention !

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
