### ISSUE TITLE
Problem with angular.io website? 

### ISSUE THREAD

**Issue by pwquest** [angular/angular#18125]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

angular.io website no longer loads with CSS formatting on my desktop using Chrome and Firefox.  Get 404 error for file : https://angular.io/styles.1726fb90df194741b2b9.bundle.css.  I am new to all this, so if this is not the place to post this issue, please let me know.  This started happening yesterday afternoon (EDT) and is continuing today.  I am having no issues with any other websites.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 59.0.3071.115 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 54.0.1 (32-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:   Windows 8.1

Others:

</code></pre>

**Comment by Toxicable** [comment]
Works fine for me

**Comment by pwquest** [comment]
Apparently the problem was fixed.  All is working again.  Thanks.

**Comment by rahul2104** [comment]
Uncaught SyntaxError: Unexpected end of input
core.js:4353 Uncaught Error: Angular requires Zone.js prolyfill.
    at new t (core.js:4353)
    at ct (core.js:5543)
    at t.bootstrapModuleFactory (core.js:5362)
    at Object.cDNt (main.ts:11)
    at n (bootstrap 8db9b05a9dd6b7d451d1:54)
    at Object.0 (main.1c33290970b6430d47fa.bundle.js:1)
    at n (bootstrap 8db9b05a9dd6b7d451d1:54)
    at window.webpackJsonp (bootstrap 8db9b05a9dd6b7d451d1:25)
    at main.1c33290970b6430d47fa.bundle.js:1
angular.io/:1 The resource https://angular.io/generated/docs/index.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
angular.io/:1 The resource https://angular.io/generated/navigation.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.

**Comment by petebacondarwin** [comment]
I can reproduce this by removing the service worker...

**Comment by petebacondarwin** [comment]
Created a new issue to track this: 20758
