### ISSUE TITLE
docs(aio): typo in NgModule FAQs

### ISSUE THREAD

**Issue by ThaneshR** [angular/angular#18133]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In https://angular.io/guide/ngmodule-faq#why-does-lazy-loading-create-a-child-injector. The second sentence of the last paragraph begins with
> It can't **added** them to the app root injector ...

Bold emphasis is added by me to highlight the typo.
## Expected behavior
It should be 
> It can't **add** them to the app root injector ...`

Bold emphasis is added by me to highlight the typo.
## What is the motivation / use case for changing the behavior?
Less typo in docs = happier developers

**Comment by Foxandxss** [comment]
Would you like to create a PR to fix it? :)
