### ISSUE TITLE
Karma outputs every message twice

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#1813]
To reproduce:

* Add `console.log('test')` to a test
* Iit that test
* Run `test.unit.js`
* `test` will appear twice

**Comment by IgorMinar** [comment]
I was able to repro this.

@caitp could you take a look at this one as well?

**Comment by IgorMinar** [comment]
I don't think that this is related to any of our build changes. I wonder if it's some kind of karma misconfiguration.

**Comment by IgorMinar** [comment]
I was able to narrow this down to the fact that we run both karma server and runner in a single process and they both log the same thing into the terminal.
