### ISSUE TITLE
Rewrite the broccoli-funnel plugin to be incremental

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#1814]
Similarly to how we changed ts2dart plugin in #1720, we should do the same for [broccoli-funnel](https://github.com/broccolijs/broccoli-funnel).

I suggest we fork funnel, wrap it into DiffingBroccoliPlugin and have it incrementally respond to changes.

Since funnel is a third-party code and DiffingBroccoliPlugin is not on npm yet, likely the best way to do this would be to pull in the fork via npm and wrap it into the DiffingBroccoliPlugin in the angular/angular repo. That way we don't need to have 3rd party code in the angular repo and don't need to export the diffingbroccoliplugin to npm just yet (I still have some bigger changes planned before it goes on npm).

This work should take off about 200-500ms of build latency.

**Comment by IgorMinar** [comment]
cc: @vsavkin

**Comment by caitp** [comment]
@IgorMinar personally I'm finding changes to this to make the initial build significantly slower. Are we sure we want to do this? At the very least, the initial build should behave as it is now, which is sort of tricky.

**Comment by naomiblack** [comment]
@IgorMinar chatted with @caitp and it sounds like you were last working on this. Slipping to alpha-28 -- I'm not sure this is still current. Should it be sent to backlog?

**Comment by IgorMinar** [comment]
work in progress. I ran into blockers during the implementation that I'm addressing. I updated the effort appropriately.

**Comment by IgorMinar** [comment]
I'm not going to finish this before my vacation, so I'm removing it from alpha-30.

**Comment by mhevery** [comment]
Status update?

**Comment by IgorMinar** [comment]
this became a low priority compared to other things (e.g. #3532).

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
