### ISSUE TITLE
HttpObserve should be exported and documented

### ISSUE THREAD

**Issue by jnizet** [angular/angular#18146]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

HttpObserve can't be used in application code, although it's part of the public API

## Expected behavior

HttpObserve should be usable. I should be able to have, for example:

    import { HttpObserve } from '@angular/common/http';
    const observe: HttpObserve = 'body';

I should also be able to know, by reading the documentation, what I can pass as value for the observe attribute of the options.

## Minimal reproduction of the problem with instructions

NA

## What is the motivation / use case for changing the behavior?

Make the development experience better.

## Environment

<pre><code>
Angular version: 4.3.0

</code></pre>

**Comment by alxhub** [comment]
Actually I think it needs to be removed from the public API and inlined. The fewer types we need to expose the better, in my opinion.

**Comment by pablochacin** [comment]
@alxhub . While this issue is solved, maybe by inlining the type, how can I specify the observe attribute in the request options? I'm using Angular 4.2.4. Thanks in advance

**Comment by chriszrc** [comment]
Setting the observe option is now documented here:
https://angular.io/guide/http#reading-the-full-response

**Comment by artuska** [comment]
This does work with the `http`:

```
let config = {
    params: params,
    observe: 'response'
};

let request = this.http.get(path, config);
```

This does not work with the `httpClient`:

```
let config = {
    params: params,
    observe: 'response'
};

let request = this.httpClient.get(path, config);
```

Because `httpClient` is configured to `observe?: "body"`.

Just saying.

**Comment by qubiack** [comment]
The biggest problem with observe is that it doesn't exist in docs. I lose about 2 hours before I found this topic.

**Comment by PhoneixS** [comment]
@artuska If you look into the definition of `httpClient.get()` it's overloaded with `{ observe?: 'body'; }` but also with `{ observe: 'events'; }` , `{ observe: 'response'; }` but typescript can't mach the correct signature.

You can help Typescript declaring the type of config. For example:

```
const config: {
        observe: 'response';
        params: HttpParams;
    } = {
    params: params,
    observe: 'response'
};
```

Then typescript won't complain anymore.

**Comment by miguelleitevieira** [comment]
Hi all,

How I can build a data request with a body and the observe option in a 'application/x-www-form-urlencoded' scenario?

**Comment by AlanObject** [comment]
No matter what I do I never get anything back except the HttpResponse.  My code is:

```
  httpPostMediaReq(path: string, formReq: FormData): Observable<any> {
    const options: {
      observe: 'events';
      reportProgress: boolean;
      withCredentials: boolean;
    } = {
      withCredentials: true,
      reportProgress: true,
      observe: 'events'
    };
    return this.http.post<JsonPoReq>(serverURL + path, formReq, options);
  }
```

Not sure where to go from here.

**Comment by TxOne** [comment]
can not import in 8.0.0

declare type HttpObserve = 'body' | 'events' | 'response';
to
export declare type HttpObserve = 'body' | 'events' | 'response';

use:
import { HttpObserve } from '@angular/common/http';

**Comment by alxhub** [comment]
We should follow through and remove it. The issue is that we explicitly _don't_ want people relying on it, as it's almost impossible to imagine a way that would not result in breaking the type inference that `HttpClient` is trying to do. In almost all cases it's better to pass a literal type value than it is to type something with the full union.
