### ISSUE TITLE
Angular AOT error:TypeError: this.compiler.analyzeModulesAsync is not a function

### ISSUE THREAD

**Issue by ak0arjun** [angular/angular#18148]
Hi, 

I am trying to implement angular application using AOT compiler. I followed article https://angular.io/guide/aot-compiler.
Hence I downloaded the setup did the files changes, created tsconfig-aot.json on compiling the project using command 
node_modules/.bin/ngc -p tsconfig-aot.json It throws error

TypeError: this.compiler.analyzeModulesAsync is not a function
    at CodeGenerator.codegen (/media/arjun/D/Work/TeachingMaterial/anngularJS/angular_aot2/quickstart/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at codegen (/media/arjun/D/Work/TeachingMaterial/anngularJS/angular_aot2/quickstart/node_modules/@angular/compiler-cli/src/main.js:13:81)
    at Object.main (/media/arjun/D/Work/TeachingMaterial/anngularJS/angular_aot2/quickstart/node_modules/@angular/tsc-wrapped/src/main.js:106:16)
    at main (/media/arjun/D/Work/TeachingMaterial/anngularJS/angular_aot2/quickstart/node_modules/@angular/compiler-cli/src/main.js:19:16)
    at Object.<anonymous> (/media/arjun/D/Work/TeachingMaterial/anngularJS/angular_aot2/quickstart/node_modules/@angular/compiler-cli/src/main.js:35:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
Compilation failed

My package.json file
{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "build": "tsc -p src/",
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "serve": "lite-server -c=bs-config.json",
    "serve:e2e": "lite-server -c=bs-config.e2e.json",
    "prestart": "npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run serve\"",
    "pree2e": "npm run build:e2e",
    "e2e": "concurrently \"npm run serve:e2e\" \"npm run protractor\" --kill-others --success first",
    "preprotractor": "webdriver-manager update",
    "protractor": "protractor protractor.config.js",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/compiler-cli": "^4.3.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/platform-server": "^4.3.0",
    "@angular/router": "~4.0.0",
    "angular-in-memory-web-api": "~0.3.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "concurrently": "^3.2.0",
    "lite-server": "^2.2.2",
    "typescript": "~2.1.0",
    "canonical-path": "0.0.2",
    "tslint": "^3.15.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",
    "@types/node": "^6.0.46",
    "@types/jasmine": "2.5.36"
  },
  "repository": {}
}

Node version v7.9.0

OS Ubuntu

Please suggest what should I do to fix it?

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ak0arjun** [comment]
ok
