### ISSUE TITLE
AnimationPlayer hasStarted() not returning expected value

### ISSUE THREAD

**Issue by 0biWanKenobi** [angular/angular#18140]
## I'm submitting a...

<pre><code>

[x ] Bug report 

</code></pre>

## Current behavior
I am trying to make use of the AnimationPlayer's method `hasStarted(),` but it looks like it always return `true`, even after pausing or resetting the player. Even inside the `onDone()` callback, it still returns `true`.

## Expected behavior
`hasStarted()` should return `false` when the player has been paused or resetted, and when it has finished animating its assigned DOM element.

## Minimal reproduction of the problem with instructions
 I created a minimal plunk [here ](https://plnkr.co/edit/2v4eTf207T6WkW5GlnGp?p=info), reproducing the issue.

## What is the motivation / use case for changing the behavior?
I think that the hasStarted() return value should provide better info about the player status.

## Environment

<pre><code>
Angular version: 4.2.6

Browser:
- [x ] Chrome (desktop) version 59.0.3071.115

 
For Tooling issues:
- Node version:  Plunker's
- Platform:  Windows

</code></pre>

**Comment by matsko** [comment]
Looking into this. Thank you for posting it.

**Comment by 0biWanKenobi** [comment]
Hello, this has gotten so old that people are opening duplicate issues (#40472). Any chance it could get fixed? 😅

**Comment by petebacondarwin** [comment]
@0biWanKenobi - @matsko left the team and we don't currently have anyone focussed on animations bugs. If you have any ideas how it might be fixed, that might help to progress a resolution.

**Comment by iRealNirmal** [comment]
@petebacondarwin I am looking into this. I have possible solution for this.

**Comment by iRealNirmal** [comment]
Right now I will fix hasStarted() to return false in case of reset.
I believe returning hasStarted to return false, in case of onDone it is arguable and that decision will take time.
Also not sure right now how many  projects already using it and it will break things for them.

Still if stack holder decides that's it's valid case and they want to cover that as well in this ticket, then I will do it.

**Comment by 0biWanKenobi** [comment]
@iRealNirmal in your pull request, are you.. setting `_started `to `true `in `reset()`? Not sure that's right 😅

**Comment by iRealNirmal** [comment]
It's incorrect I would correct it and set to false. Thanks for bringing it up.
