### ISSUE TITLE
Unable to use any of the decorators @NgModule, @Component, etc

### ISSUE THREAD

**Issue by dvenkatsagar** [angular/angular#18143]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am trying to upgrade my angularjs application to angular. I was following the docs till the manual bootstrapping of the angularjs application i.e 

`angular.bootstrap(...)`

Now after this, I was trying to introduce the "upgrade" version of the bootstraping i.e remove the older bootstrap method introduce a empty `NgModule` with the UpgradeModule and do the bootstrap via platformBrowserDynamic.bootstrapModule().

But for some reason, when I try to do that, the Systemjs doesnt seem to execute the code(I have all the code in one file), and it just fails silently in the browser (blank screen, no errors). 

I have even kept console.logs along the way to be sure if the code was even executing at the point.

To be noted: The code is one single file that Im producing using gulp. So the bootstrapping and Module definitions, imports etc are in the correct order.

## Expected behavior

The expected behavior is to bootstrap the application successfully and load the angularjs application correctly.

## Minimal reproduction of the problem with instructions

1. Include the basic systemjs.config.js which includes the necessary Angular, Angularjs and Rx libraries.
2. Introduce a empty NgModule at the end of the file(The angularjs code is at the top and new code is the end).
3. Manually bootstrap the application with Upgrade module(Bootstrap the Angular Module first, then the Angularjs Modules).
4. Serve the application.

## Environment

<pre><code>
Angular version: 4.2.6
AngularJs version: 1.6.5
Rx: latest
ui-router/angular-hybrid: latest

Browser:
- [x] All Browsers
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.0  
- Platform:  windows 

Others:

</code></pre>

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
