### ISSUE TITLE
Not able to open menu in iPad device

### ISSUE THREAD

**Issue by bjp232004** [angular/angular#18144]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Trying to open menu by using sandwich icon but not able to open it. Nothing happened while clicking on menu icon.

## Expected behavior

Menu should open.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
@bjp232004, can you post a screenshot of how the page looks like and more details on the iPad device?

**Comment by gkalpak** [comment]
Closing since we didn't get any feedback and nobody else complained about this.
If the problem persists, please open a new issue with more details.
