### ISSUE TITLE
Required Input() parameters

### ISSUE THREAD

**Issue by HoumanKml** [angular/angular#18156]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Regardless of whether Input parameters of a component are optional or not, AoT does not throw an error or warning, making it difficult to find out mistakes where a required attribute is not passed down to a component in the template before runtime.

```
@Component({
  selector: 'app-username',
  template: `
    <p>{{username}}</p>
  `,
})
export class UsernameCompoennt implements OnInit {
  @Input() id: string;
  username: string;
  
  constructor(private usernameService: UsernameService) { }

  ngOnInit() {
    this.usernameService.getUsername(id).subscribe(user => this.username = user.name);
  }
};
```

```
<app-name></app-name>
// will be compiled with no warning or error, while the component is essentially useless without name being provided
```

## Expected behavior

AoT will throw a warning or error, because a required input parameter has not been passed down to the component

## What is the motivation / use case for changing the behavior?

Will enable catching errors during compilation

## Environment

<pre><code>
Angular version: 4.2.X

**Comment by Toxicable** [comment]
What if the @Input is optional? how would your proposal handle that case?

**Comment by textbook** [comment]
@Toxicable do you mean how would the author *indicate* that an input is optional? You could use the existing [optional property notation](https://www.typescriptlang.org/docs/handbook/advanced-types.html#optional-parameters-and-properties): `@Input() optional?: any;`.

**Comment by Toxicable** [comment]
@textbook I mean technically how would Angular handle it. For example using the Typescript notation for optional: This approach would require creating AST's out of your Components, which I don't believe it does right now.
Doing so would drag down AOT compilation times which is a metric currently being worked on.

**Comment by HoumanKml** [comment]
@Toxicable Verification of existence of the required attributes could be an optional feature of AoT that can be set with a flag if there are performance concerns. 

Without the option to have the compiler check for these errors, one has to write boiler plate code for every component that somehow informs the 'author' of the code in case s/he has missed a required input parameter, and writing those boilerplate codes is even a bigger waste of time than some performance degrade in the AoT and makes your code unnecessary padded (I believe if you have to write something to catch your own coding mistakes, it means your coding tools could possibly be improved)

**Comment by trotyl** [comment]
@HoumanKml If you really need some property, you can ensure that in selector like:

```typescript
@Component({
    selector: 'app-username[id]'
})
```

This way it would become error when id is not provided in template.

But there still could be other issue, what if user provide an `undefined`/`null` deliberately? Then inside component it's still a `nil` value.

Theoretically this should be covered by type-checking, https://github.com/Microsoft/TypeScript/issues/8476 is a great proposal to handle some problem like this, but unfortunately, it's not suitable for Angular since none of the `@Input()`s are initialized within `constructor`.

And my understanding about the type-checking of Angular compiler is, if it's not an error in compiled `.ngfactory.ts` code raised by `tsc`, then it should not be an error of `ngc`. But if there is, it should be mapping to source of Angular (maybe in `.html` template).

**Comment by HoumanKml** [comment]
@trotyl Thanks! I wasn't aware of that syntax pattern, I will try it out!

I was mostly concerned about programmer caused errors during coding, rather than users not providing a parameter.  In case the property of a component is expected to be provided by a user, one can use `set` to handle parameter input.

**Comment by alxhub** [comment]
@trotyl's example is a recommended way to have a required `@Input` - it's how `NgFor` does it, for example. If the `@Input` is properly typed we should be able to enforce strict null checks against it (not sure if we do currently, but we should be able to). I'm going to consider this resolved :)

**Comment by Andrey-Pavlov** [comment]
Hi guys, it really helped me to enforce required inputs:
```
@Component({
    selector: 'history-section[isGlobalHistory][history][isUserActivity][reportsCount][username]',
})
```
But my e2e tests started to fail because the **history** input is '' (empty string) now. Any thoughts how can I avoid this behavior and why the **history** array became string?
  ```
beforeEach(() => {
    fixture = TestBed.createComponent(HistorySectionComponent);
    comp = fixture.componentInstance;

    comp.history = historyItems;

    fixture.detectChanges();
  });
```
`comp.history === ''`

**Comment by zamzowd** [comment]
I'm getting the same behavior in testing described by @Andrey-Pavlov 

I can run the karma test debugger, and after the `fixture.detectChanges()` call the property value gets set to an empty string.  It does that whether I update the property on the component or not.  If the property is not in the `selector`, then it works as expected.

**Comment by zamzowd** [comment]
I ended up fixing this by using the pattern described here: https://medium.com/@AikoPath/testing-angular-components-with-input-3bd6c07cfaf6

I created a TestHostComponent class with a template invoking the component that I want to test, setting the attribute there.

```typescript
const name = "Test1";
const optionalInput = "Test2";
@Component({
  selector: "host-component",
  template: `<my-component [name]="name"></my-component>`
})
class TestHostComponent {
  @ViewChild(MyComponent) myComponent: MyComponent;
  public name: string = name;
}

...

fixture = TestBed.createComponent(TestHostComponent);
hostComponent = fixture.componentInstance;
component = hostComponent.tableComponent;

component.optionalInput = optionalInput;

fixture.detectChanges();

...

expect(component.name).toEqual(name);
expect(component.optionalInput).toEqual(optionalInput);
```

**Comment by zamzowd** [comment]
Now I'm trying to determine if there's a way to test the fail condition, when the component name is used without the required attribute.

I'm trying:
```typescript
describe("without required inputs", () => {
  beforeEach(() => {
    TestBed
      .configureTestingModule({ schemas: [] })
      .overrideComponent(TestHostComponent, { set: { template: `<my-component></my-component>` } })
      .compileComponents();
  });

  it("should not create", () => {
    const create = function() {
      TestBed.createComponent(TestHostComponent);
    }
    expect(create).toThrow();
  });
});
```
It throws the expected exception ("'my-component' is not a known element") but it's thrown in such a way that the test still fails due to the exception.
