### ISSUE TITLE
Proposal: HttpParams toString method should filter undefined/null value

### ISSUE THREAD

**Issue by leo6104** [angular/angular#18152]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[o] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

this.currentCategory = null;
console.log(new HttpParams().set('category', this.currentCategory).toString()); // 'category=null'

## Expected behavior

this.currentCategory = null;
console.log(new HttpParams().set('category', this.currentCategory).toString()); // ''

## Minimal reproduction of the problem with instructions

https://github.com/angular/angular/blob/master/packages/common/http/src/params.ts#L157
```
return this.map !.get(key) !.map(value => eKey + '=' + this.encoder.encodeValue(value))
              .join('&');
```

## Environment

<pre><code>
Angular version: 4.3.0

Browser:
- [o] Chrome (desktop) version XX
- [o] Chrome (Android) version XX
- [o] Chrome (iOS) version XX
- [o] Firefox version XX
- [o] Safari (desktop) version XX
- [o] Safari (iOS) version XX
- [o] IE version XX
- [o] Edge version XX
 
For Tooling issues:
- Node version: 7.8.0
- Platform:  All

Others:

</code></pre>

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/28244681-85e294e6-6a23-11e7-924c-3f4532275130.png)

It's the correct behavior according to the standard, you'd better raise your concern [here](https://github.com/whatwg/url).
