### ISSUE TITLE
HttpClient not supporting in memory web api

### ISSUE THREAD

**Issue by mmc41** [angular/angular#18150]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The old http module supported an in memory web api using "angular-in-memory-web-api" which is extremely useful for testing and development. 

## Expected behavior
The new HttpClient does not support an in memory web api. This is blocking it's use.

## Environment

<pre><code>
Angular version: 4.3.0

**Comment by notsonotso** [comment]
Duplicate of https://github.com/angular/in-memory-web-api/issues/122

**Comment by Foxandxss** [comment]
Closing as duplicate and not belonging to this repo.

**Comment by wardbell** [comment]
To be fair, it **is an Angular issue** in as much as the Angular documentation makes extensive use of it.

I have [pledged to fix this problem soon](https://github.com/angular/in-memory-web-api/issues/122#issuecomment-323227776).
