### ISSUE TITLE
Table Cell Rendering

### ISSUE THREAD

**Issue by Ratikant01** [angular/angular#18168]
Hello Team,
I am having a scenario where I build my table dynamically and the cells of the table are editable. I also need two-way-binding! Now when I submit the form, I want the table data to be captured as an Object instead of loc.location0; loc.location1 etc.. when submitting the form (submit(form, formvalue)...) Any suggestion?

`<table id="locationTable">
						<tr>
							<th></th>
							<th>Location</th>
						</tr>
						<tbody>
							<tr *ngFor="let loc of locationList; let i = index"
								[attr.data-index]="i">
								<td class="paCheckbox"><input type="checkbox" id="{{i}}"
									name="loc.isChecked{{i}}" [(ngModel)]="loc.isChecked"
								<td class="paLocation"><input type="text" class="form-control"
									name="loc.location{{i}}" [(ngModel)]="loc.location"></td>
							</tr>
						</tbody>`

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
