### ISSUE TITLE
Override routerLink directive and handle click event of own.

### ISSUE THREAD

**Issue by RoshanRoyal** [angular/angular#18164]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Default onclick of router class is called

## Expected behavior

should be able to inherit and register my routerLink directive to app.

 

## What is the motivation / use case for changing the behavior?

I want to handle dynamic tab generation with routing and prefetching as resolvers for tabs.  

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [x ] Firefox version XX
- [x ] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [ x] IE version XX
- [x ] Edge version XX
 
x

**Comment by zoechi** [comment]
Hey @RoshanRoyal ,
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

You can just inject the `Router` and call one of the `router.nativateXxx()` methods in your click handler to do your custom navigation (without using `RouterLink` at all).

**Comment by alxhub** [comment]
@zoechi is correct, instead of `RouterLink` you can imperatively navigate in your own click events.

**Comment by RoshanRoyal** [comment]
But I have a requirement to get this overridden so that I can use it for some context

**Comment by zoechi** [comment]
@RoshanRoyal it should be easy enough to work around. 
You can for example also extend (not tried) or clone and customize the routerLink directive. Why do you think it's necessary that the framework provides this behavior out of the box. 
There doesn't seem broad demand for this feature.

**Comment by RoshanRoyal** [comment]
@zoechi I tried extending it but how to configure my app so that instead of default directive it should pick custom routerLink directive

**Comment by zoechi** [comment]
The easiest way is to use a different selector like `myRouterLink`

I think it's better to move the discussion somewhere else ...

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by RoshanRoyal** [comment]
But I also want to have feature of routerLink like resolvers and all which can get data before landing to page.

**Comment by zoechi** [comment]
Shouln'nt be a problem. This just isn't the place to discuss it
