### ISSUE TITLE
docs: Incorrect variable name in NoopInterceptor

### ISSUE THREAD

**Issue by matkokvesic** [angular/angular#18166]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`intercept` method in `NoopInterceptor` calls `next.handle` with variable `Req` which doesn't exist. 
https://angular.io/guide/http#writing-an-interceptor

## Expected behavior

Call `next.handle` with variable `req` (small caps):

```
import {Injectable} from '@angular/core';
import {HttpEvent, HttpInterceptor, HttpHandler, HttpRequest) from '@angular/common/http';

@Injectable()
export class NoopInterceptor implements HttpInterceptor {
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req);
  }
}
```

## Environment

<pre><code>
Angular version: 4.3.0

Browser:
- [x ] Chrome (desktop) version  59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by gkalpak** [comment]
Fixed in c6ad212a98c401f4de0b81f93b14687aab1abbb6.
