### ISSUE TITLE
Output method decorator

### ISSUE THREAD

**Issue by ghost** [angular/angular#18161]
## I'm submitting a...
[x] Feature request

## What is the motivation / use case for changing the behavior?
Less boiler plate code, hide EventEmitter details

## Proposal

Add an @Output method decorator that would lower to the most suitable event emission code, currently EventEmitter.

It would take an optional binding property name, as usual.

<pre><code>
@Output('click') onClick() {
    return 'The result';
}
</code></pre>

Would lower to:

<pre><code>
@Output() __generated_property$123: EventEmitter &lt;string &gt; = new EventEmitter&lt;string&gt;();

onClick() {
    this.__generated_property$123.emit('The result');
}
</code></pre>

Use-site isn't aware whether or not the @Output binding is a property or method.

**Comment by notsonotso** [comment]
A more general question: Is there a place in the pipeline to do source level or AST transformations like this?

**Comment by trotyl** [comment]
Possibly related to https://github.com/angular/angular/issues/13248
