### ISSUE TITLE
Router-outlet doesn't work for lazy router if use router-outlet how sub-router

### ISSUE THREAD

**Issue by WahlbergRu** [angular/angular#18171]
<pre><code>
[X] Bug report  
[X] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

If I use router-outlet for custom router with directive name, 
than if I use declaration in module with router, that work is fine. But if I declarated and exported component in shared module, component is work, but router-outlet doesn't work in component. 
more inforamtion in this - https://stackoverflow.com/questions/45146621/full-understanding-of-routeroutlet-in-route-with-lazy-route

## Current behavior
Router-outlet don't work if component is declareted in shared.module.ts

## Expected behavior
Router-outlet do work if component is declareted in shared.module.ts

## Minimal reproduction of the problem with instructions
custom rep for testing - https://github.com/Adventure-RPG/Adventure-Client 
If u declarated component in shared and undeclarated in app.modules.ts u can see this bug on link localhost:4201/main(sidebar:inventory)

## What is the motivation / use case for changing the behavior?
I don't wanna make for any router new component with copy/pasta

## Environment

<pre><code>
Angular version: 4.3

Browser:
- [X] Chrome (desktop) version XX

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
