### ISSUE TITLE
IE11 Route Issue with subfolder relative base path

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#18176]
## I'm submitting a...
<pre><code>
[X] Bug report  
</code></pre>

##
There is a bug in the router that prevents applications from loading. This bug is exposed with this combination:

1. Relative `base` in index.html
1. IE11 browser
1. Served from a subfolder

## Setup Steps / Repro
* Clone this repo: https://github.com/StephenFluin/ie11test
* `npm install`
* `ng build -prod`
* cd into `dist` and serve it (ie `python -m SimpleHTTPServer`)
* Visit the site in IE11

## Observed behavior
```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'sub'
Error: Cannot match any routes. URL Segment: 'sub'
```

## Expected Behavior
The app loads as intended
![image](https://user-images.githubusercontent.com/165056/28280181-c2c51df2-6ad7-11e7-82b7-f379807ed035.png)

## Environment
<pre><code>
Angular version:4.3.0
(This is not a new issue with this version and is believe to be this way at least back to 4.0)

Browser:
- [X] IE version 11

 
App Built with
```
@angular/cli: 1.2.0
node: 8.1.3
os: linux x64
@angular/animations: 4.3.0
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.2.0
@angular/compiler-cli: 4.3.0
@angular/language-service: 4.3.0
```

**Comment by densanki** [comment]
Is there any process on this bug? Problem cause issues on productive env.

**Comment by wdy0719** [comment]
Have same issue..

**Comment by felixfontein** [comment]
Same problem here.

**Comment by mdarfilal** [comment]
is there any work around ?

**Comment by Empereol** [comment]
I haven't tested this a bunch but it appears to work...

Use your own factory to provide the `APP_BASE_HREF` token based on the location you want... If you want it relative to the current location just return the `window.location.pathname`

Example:

```ts
// app.module.ts
...
@NgModule({
providers: [
    {
        provide: APP_BASE_HREF,
        useFactory: getBaseHref,
    }
])
...
export function getBaseHref(): string {
    return window.location.pathname;
}
```

**Comment by ffdybuster** [comment]
For my case, I had to cut off everything after the last slash:
``` .ts
export function getBaseHref(): string {
  const path = window.location.pathname;
  const i = path.lastIndexOf('/');
  return i >= 0 ? path.substr(0, i + 1) : path;
}
```
(Also, `import { APP_BASE_HREF } from '@angular/common';` is needed.)

**Comment by densanki** [comment]
Long long ago there was a bug that nerves me yesterday, today and tommorow ....

**Comment by switch120** [comment]
I had the same issue with IE11 only; Angular 5 project. Ultimately the solution @Empereol posted got me through it. I just chose to shorten it to:
```
{
	provide: APP_BASE_HREF,
	useValue: window.location.pathname,
}
```
I also removed the `<base href>` tag from `index.html` just to keep it succinct.

**Comment by helzgate** [comment]
I wish this fix worked for me but unfortunately the issue still occurs using:

IIS 10
angular 6.1.10

**Comment by ffdybuster** [comment]
@helzgate do your routes include slashes (`/`)? This fix only helps if your routes do not (as far as I understand it).

**Comment by helzgate** [comment]
@ffdybuster I'm not sure what you mean.  Yes my routes have slashes, but don't all routes have slashes?

**Comment by ulisesmorenomassachusetts** [comment]
@Empereol answer helped me on Angular 7, IE11 Windows 10

**Comment by atscott** [comment]
Closing as ie11 will not be supported going forward
