### ISSUE TITLE
For HttpClient in 4.3.0, export HttpRequestInit for options

### ISSUE THREAD

**Issue by chunghha** [angular/angular#18175]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

HttpRequestInit is defined for options but not exported unlike HttpHeaders.

## Expected behavior

HttpRequestInit is also exported if it's meant to be so users can set type of options to it within applications.

## What is the motivation / use case for changing the behavior?

Need to set new HttpClient's options type to something for my applications.

## Environment

<pre><code>
Angular version: 4.3.0

**Comment by alxhub** [comment]
Hi @chunghha,

`HttpRequestInit` is a private, internal type. The actual signature of `HttpRequest`'s constructor uses an inlined type, there is no type name associated with it. As long as the object you pass has a signature which is assignable to the inline type, it'll work.

**Comment by chunghha** [comment]
@alxhub thanks for your answer.

I understood about inlined type of HttpRequestInit as you wrote. And I know I can write my http client code to work without its type exported.

But, I still see this request as an enhancement. By HttpRequestInit (or something else) exported, that will help for users 
 
- to do "type check" options passed to.
- little easier to construct options object.

And, I don't see why not exporting HttpRequestInit type as other HttpHeaders, HttpParams types of HttpRequestInit already exported, for the sake of consistency in HttpClient API, imho.

**Comment by alxhub** [comment]
Unfortunately it doesn't work so well, because every possible signature you pass to one of the request methods is slightly different. The same is true of `HttpRequest`'s constructor, there are a couple different forms. Typescript _will_ type check the options when you pass them.

`HttpHeaders` and `HttpParams` are classes meant for use by users, and thus are exported.
