### ISSUE TITLE
Support part files in the dart transformer

### ISSUE THREAD

**Issue by jakemac53** [angular/angular#1817]
There are a few things that need to happen to support using parts, lets collect them here.

- [ ] Add support for discovering angular annotations in parts. 
    - Skip any dart files with a `part of` directive if they are primary inputs (do not output a `.ng.deps` file). 
    - Whenever we find a `part` directive in a primary input load the file and treat any annotations found as if they were in the current file.

**Comment by jbdeboer** [comment]
FYI, We are about to ban ```part of``` from our codebase because is smells bad.

**Comment by jakemac53** [comment]
Ok, but should external developers also be banned from using parts in their angular apps? I am not necessarily opposed to that being the case, but some people really like them.

**Comment by zoechi** [comment]
Why does `part of` smell bad?
`part of` is used in this tutorial even though it doesn't work https://angular.io/docs/dart/latest/guide/displaying-data.html

**Comment by jakemac53** [comment]
People tend use parts to create a single library for their entire package. This means they are essentially creating a single scope for their whole package and are more likely to have naming conflicts. Also since privacy is at the library level in dart then all your private variables can be accessed from other `parts` (sometimes this is useful).

Little things are also annoying like having to find your main library file when you want to add an import, or discover what prefix you used for a particular import. It is much easier to reason about non-part files in general, you generally never have to leave your current file to get a picture of all available classes/variables or import new ones.

You can get nearly all the benefits without the downsides by using exports, and that is definitely what I prefer in my own code.

**Comment by zoechi** [comment]
Sure, I try to avoid parts as well, but Dart is very limited in expressing what should be accessible from where. And there are times where you don't want to have everything in on file. Parts are not perfect, but I still don't see why they would smell.
I don't think it's a good idea for tools to limit Dart limited capabilities even further.

**Comment by jakemac53** [comment]
Yes, I agree that regardless of how you feel about them they shouldn't be banned by angular, which is why I opened this bug :).

**Comment by zoechi** [comment]
:+1:

**Comment by kwalrath** [comment]
I'm converting the docs to use the transformer and (thanks to this bug) not use `part of`, fwiw.
