### ISSUE TITLE
docs(ControlValueAccessor): registerOnTouched() description is misleading

### ISSUE THREAD

**Issue by reppners** [angular/angular#18174]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/api/forms/ControlValueAccessor#members

The documentation about `registerOnTouched(fn: any): void` states

```
Set the function to be called when the control receives a touch event.
```

However I think this is highly misleading and does not really describe what `touched` does mean in the forms context. What I think `touched` does mean is: the control was `visited`. This is also how it seems to be implemented by angular itself as this function is invoked when the `blur` event is detected.

See https://github.com/angular/angular/blob/a0b06befb6972e96ce5b724c14a65f5382bd4eee/packages/forms/src/directives/number_value_accessor.ts#L34

## Expected behavior

Document the intent and purpose of `touched` more like:

`Invoke when the control loses focus to indicate the user visited the control`.

## What is the motivation / use case for changing the behavior?

The documentation should clearly define the intent of `touched` so implementors of the interface clearly know the purpose and when to invoke the function. Maybe `visited` is the more accurate term and `touched` should rather be deprecated for the long term but thats just a proposal.

## Environment

<pre><code>
Angular version: 4.3.0

**Comment by tytskyi** [comment]
> Invoke when the control loses focus to indicate the user visited the control

This description is more misleading than original. `registerOnTouched()` is invoked synchronously during creation of custom control. It receives the function that end developer should execute when she decides control is logically "touched"/"visited".

**Comment by reppners** [comment]
Well that was just meant as an example to paraphrase how it could be documented. Also the sentence refers to the `fn` parameter rather than `registerOnTouched(fn: any): void`.

**Comment by tytskyi** [comment]
I agree that this could have better wording, i got a lot of frustration when i was just getting started with `ControlValueAccessor`.
