### ISSUE TITLE
create next.angular.io + add "next" entry to the version dropdown

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#18189]
## Current behavior

Master branch docs are being published to aio-staging.firebaseapp.com but we don't advertise this anywhere, so nobody can easily find the documentation for the current beta/rc release.

## Expected behavior

- [ ] we should alias aio-staging.firebaseapp.com to next.angular.io
- [ ] add an entry called "next" into the version dropdown that will redirect to next.angular.io.

**Comment by IgorMinar** [comment]
I've setup the dns info already, we just need to wait for the change to propagate and for firebase to provision a cert. ETA 2h.

**Comment by trotyl** [comment]
But why not making *angular.io* being able to view the docs of any minor or patch version just like *angularjs.org*?

![image](https://user-images.githubusercontent.com/6059170/28300546-c8de49b2-6bb2-11e7-8788-f0a6c7e7fef5.png)

**Comment by jnizet** [comment]
The version displayed in the left navbar for next.angular.io should also indicate the actual next version being documented (currently, it shows 4.3.0), and the Next link should be replaced by "Stable" and point back to angular.io, IMHO.

**Comment by gkalpak** [comment]
Closed by #18297.
