### ISSUE TITLE
Support a way to get all the attributes for a directive

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1818]
In the existing material design library for Angular 1, there are some components that use a concept of "responsive attributes". Say you have a component like `md-grid-list`, which has an attribute `cols`. You can specify the value conditionally on screen size, for example:
```
cols-sm="2"     // Small screen size
cols-lt-lg="4"  // Less than large screen size
```

We currently have a way to inject a _single_ attribute (`@Attribute('cols')`), but the number of combinations gets large quickly (this one attribute has 9). One could also set up `properties`, but again it's a lot of boilerplate and unnecessary bindings. 

One solution would be to allow injection of a `<string, string>` attribute map. 

As a workaround, when per-component renderers are supported, the renderer can read the attributes and pass the values back to the directive via an event.

**Comment by gdi2290** [comment]
having `(@Attributes: $attrs)` would also be great for making directives that work both in angular1 and angular2 since you only have `$attrs` in angular1

**Comment by mhevery** [comment]
closing as obsolete, Re-open if you think this is still needed.
