### ISSUE TITLE
Documentation issue, template and template-url

### ISSUE THREAD

**Issue by briankip** [angular/angular#18187]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Documentation does not alert the user that template-url overrides the template directive in the @component decorator, the template-url is there by default in new autogenerated projects.

## Expected behavior

The user should be notified, on the appropriate action to take. Which is to remove the template-url directive.

## Minimal reproduction of the problem with instructions

Documentation found here. 

## What is the motivation / use case for changing the behavior?

New users such as myself cannot follow the tutorial successfully since it does not go as expected. The template will not load as expected. Leading to the user wasting time trying to look for a solution.

## Environment

<pre><code>
Angular version: X.Y.Z

4.3.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
v6.11.1
- Platform:   
Linux

Others:

</code></pre>

**Comment by alxhub** [comment]
This request is unfortunately too vague for us to act on. If you have specific items or examples in the documentation that you would like to see improved, please feel free to reopen the issue and list them. Thanks!
