### ISSUE TITLE
HttpErrorResponse sent by flushed test request should contain the body

### ISSUE THREAD

**Issue by jnizet** [angular/angular#18181]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Flushing a response with a JSON body and an error status, using the HttpClientTestingModule, results in a HttpErrorResponse with a null error, instead of the expected body

## Expected behavior

The error property of the HttpErrorResponse should contain the flushed body

## Minimal reproduction of the problem with instructions

Execute the following jasmine test:

```
import { TestBed } from '@angular/core/testing';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';

fdescribe('Bug', () => {

  let http: HttpTestingController;
  let httpClient: HttpClient;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [ HttpClientTestingModule ]
    });

    http = TestBed.get(HttpTestingController);
    httpClient = TestBed.get(HttpClient);
  });

  it('should send an HttpErrorResponse where the error property is the json body of the flushed response', () => {
    let actualBody;
    httpClient.get('/test').subscribe(null, (resp: HttpErrorResponse) => {
      actualBody = resp.error;
    });

    const testRequest = http.expectOne('/test');
    testRequest.flush({ foo: 'bar' }, { status: 500, statusText: 'Server Error' });

    expect(actualBody).toEqual({ foo : 'bar' });
  });
});
```

I would expect this test to pass, but it fails with

    Expected null to equal Object({ foo: 'bar' })

The error is probably in [this line](https://github.com/angular/angular/blob/37797e2b4e1ddc6560ae6c8364ea678ffbaa3de1/packages/common/http/testing/src/request.ts#L59), which should instead be

    const res = {error: body, headers, status, statusText, url};    

## What is the motivation / use case for changing the behavior?

Fix a bug

## Environment

<pre><code>
Angular version: 4.3.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ychaikin** [comment]
I see it says that this bug was fixed. However, when I flush with the following:
```
const req = httpTestController.expectOne(someUrl);
req.flush({message: 'my error message'}, {status: 500, statusText: 'Server error'});
```
Instead of the object `error: {message: 'my error message'}`, I get a string `error: "{message: 'my error message'}"`

I am using Angular 5.2.9.

Has this not been resolved or got re-introduced?

**Comment by gkalpak** [comment]
Maybe you are using the wrong `responseType` (i.e. `text`). Hard to tell without an actual reproduction.
