### ISSUE TITLE
<embed> tag with [src]="url" fails

### ISSUE THREAD

**Issue by LimeyTX** [angular/angular#18184]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The issue is fully described [here](https://stackoverflow.com/questions/45135788/angular-4-unable-to-embed-a-flash-swf-file).
The template file:
    `<!--<embed width="400" height="300" [src]="url" />--`
    `<div [innerHTML]="html"></div>`

The controller file:

     import { Component, Input, OnInit } from '@angular/core';
     import { DomSanitizer, SafeResourceUrl, SafeUrl, SafeHtml } from '@angular/platform-browser';
     @Component({
         selector: 'animation',
         templateUrl: './animation.component.html'
     })

    export class AnimationComponent implements OnInit {
        @Input()
        private code: string = '';
        private url: SafeResourceUrl;
        private html: SafeHtml;

        constructor(private sanitizer: DomSanitizer) { }

        ngOnInit() {
            let url = `/assets/SWF/${this.code}`;
            let html = `<embed width="400" height="300" src="${url}" />`
            this.url = this.sanitizer.bypassSecurityTrustResourceUrl(url);
            this.html = this.sanitizer.bypassSecurityTrustHtml(html);
        }
    }

This works but if I make the template file use the embed tag instead of the div tag it doesn't display anything.

But here is the odd thing. If I change the  template to 
    `
    <embed width="400" height="300" src="/assets/SWF/Blob.swf" />
    `
it doesn't work. But when I inspect the generated embed in the browser it is EXACTLY the same.

## Expected behavior

It should display the animation in the .swf file

## Environment

<pre><code>
  "dependencies": {
    "@angular/animations": "4.1.2",
    "@angular/common": "4.1.2",
    "@angular/compiler": "4.1.2",
    "@angular/core": "4.1.2",
    "@angular/forms": "4.1.2",
    "@angular/http": "4.1.2",
    "@angular/platform-browser": "4.1.2",
    "@angular/platform-browser-dynamic": "4.1.2",
    "@angular/platform-server": "4.1.2",
    "@angular/router": "4.1.2",
    "@types/node": "7.0.18",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^2.0.5",
    "aspnet-webpack": "^1.0.29",
    "awesome-typescript-loader": "3.1.3",
    "bootstrap": "3.3.7",
    "css": "2.2.1",
    "css-loader": "0.28.1",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.0",
    "file-loader": "0.11.1",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.0",
    "style-loader": "0.17.0",
    "to-string-loader": "1.1.5",
    "typescript": "2.3.2",
    "url-loader": "0.5.8",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.0",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.10"
  },
  "devDependencies": {
    "@types/chai": "3.5.2",
    "@types/jasmine": "2.5.47",
    "chai": "3.5.0",
    "jasmine-core": "2.6.1",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3"
  }
}

Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version Version 59.0.3071.115 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
Probably not related to angular:
- Have you tried to change the property (not the attribute) of an `embed` tag ?
- Have you tried to use attribute bindings ? `[attr.src]="..."`

**Comment by kamalSaiDd** [comment]
I see this issue only with IE but works in Chrome perfectly
