### ISSUE TITLE
Form validation for warnings or other non error types

### ISSUE THREAD

**Issue by BioPhoton** [angular/angular#18195]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior
Currently there is no built in way to handle warnings or other validation types on formControls.
I would like to have a way to configure validation functions that do not create errors and do not effect the valid state of an input but provide the same options as current validation does.

## Expected behavior
I need a way to easy configure FormControls || FormGroups like i do with validators. So i can apply existing validator functions to a "warning" section of the validation. I want "warnings" to utilize all the awesome features of forms like the validation state ('VALID, INVALID, PENDING...') and the errors.

## What is the motivation / use case for changing the behavior?
I want to have an abstract validation logic that can be used for errors and "warnings" in the same way.

## Environment

<pre><code>
Angular version: 4.3.0
</code></pre>

I hope my explanation is good enough. I didn't provide some points of the list i.e. Steps to reproduce as they have no meaning for this issue.

Best 
Michael

**Comment by Toxicable** [comment]
This sounds like a domain related problem and not something Angular should be solving. Since Angular has no idea what a warning should be from one domain to another.

**Comment by BioPhoton** [comment]
Hi @Toxicable, THX for your fast response!

I think angular should provide a way to "validate" input and not invalidate the valid state. Angular should not know what a warning is, but angular should provide a result of a "validation" that i could treat as a warning or what ever without setting the control to invalid.

What do you think?

**Comment by BioPhoton** [comment]
For example i want to set a required validation but only hint the missing value to the user and don't set it to invalid.

**Comment by Toxicable** [comment]
With the current validators you can return an object which you could easily add a property on indicating that it's a warning. For example, lets say we have this validator
Note: this is not how i'd write this validator, it's just for example.
```
 isInAgeRange(control: AbstractControl){
    const value = +control.value;
    return value > 0 ? null : { invalidAgeRange: true };
  }
```
This is your normal kind of validator which takes an input and just returns a normal object. So for your purpose you could change it to be like this.
```
 isInAgeRange(control: AbstractControl){
    const value = +control.value;
    if(value <= 0){
      return { invalidAgeRange: true };
    } else if(value > 0 && < 10) {
      return { invalidAgeRange: true, warning: {value: value, min: 10} };
    } else {
      return null;
    }
  }
```
Then way in a later mapping function you can then check to see if the error has a warning in it and do logic based off that

**Comment by BioPhoton** [comment]
Hi again. Very nice that you investigated time in you detailed answer.

For now i know 3 different way to achieve this:
1. Your approach with the always valid validator that contains "warning" information
2. A custom Validator that is always valid and feeds another service that manages the warning information out of the validator result.
3. Faking an control and use it as worker...

I have no good feeling with 1. and 2. there are many reasons but for me the fact that a cant reuse existing validators is the worst. Consider a required validator with approach 1. or 2... You have to create a second validator containing the same logic to get a warning. 

There fore a made up 3. I know it's not beautiful but at least it solves the redundent logic problem and it provides all the cool features of an input like the state, errors (in this case warnings),  it also let me use the alternative validation states completely encapsulated from the rest of the validation. 

The idea:
Its a directive that reacts to model or view chagnes of an input and maps the new input to a "fake" FromControl. A control without view, or parent formGroup. Later a expose the errors and states of this fake control to the template ofer exportsAs and use it.
 ```typescript
// alternative-validation.directive.ts
@Directive({
    ...
    exportAs: 'alternativeValidation'
})
export class AlternativeValidationDirective {

    @HostListener('input', ['$event'])
    onControlInput($event: KeyboardEvent) {
    ...
        this.updateWarnings(rawValue)
    ...
    }

    writeValue(rawValue: any): void {
    ...
        this.updateWarnings(rawValue)
    ...
    }

    updateWarnings() {
        this.formControl.setValue(value)
        this.warnings = this.formControl.errors
    }
```

 ```
// some.component.html
  <div class="form-group has-feedback" [ngClass]="(vW.invalid && vW.touched)?'has-warning':''">
        <input type="text" [formControlName]="'name'" 
                                        [validatorWarning]="vWNameConfig" #vW="validatorWarning">
          <p *ngIf="vW.warnings.minlength">This field is not really long. Consider using a longer one.</p>
      </div>
```

I also create real code for this. Just quick but you cant see the approach. 

[angular-alternative-validation](https://github.com/BioPhoton/angular-alternative-validation/blob/master/src/validator-warning.directive.ts)

cd into the example folder and ng serve it... 
Would be really cool if you could take a look at the code and also try it out by service the example folder. For me this is the most convenient way to solve this problem. I would be thankful for feedback.

Best,
Michael

**Comment by kara** [comment]
Thanks @BioPhoton for laying out the use case. However, as @Toxicable mentioned, there are existing ways to accomplish what you need with Angular.  If some validation functions created errors and others created warnings, it would make validation more complicated to reason about and to maintain. This doesn't seem to me to be within the scope of core forms, so I'm closing this. But keep in mind, it's always possible to release additions to forms as your own package if you like.

**Comment by BioPhoton** [comment]
@kara  Thx for closing another issue in the great repo! Loving your work on forms! :-)

I have found a way that feels good to me.  
I tried to extend and implement as much angular code as possible. It's a mix of `FormControlName`, `AbstractControlDirective`, `ControlValueAccessor`, `NG_VALIDATORS` and a little bit of `magic-glue`. 

Resources for **angular-alternative-validation**:
- [Github Repository](https://github.com/BioPhoton/angular-alternative-validation)
- [NPM Package](https://www.npmjs.com/package/angular-alternative-validation)
- [Plunker](https://embed.plnkr.co/e3GOAFENPumfy78IWXAw/)
- [Example with @angular/cli](https://github.com/BioPhoton/angular-alternative-validation/tree/master/examples/angular4)
- [Animated Gif](https://raw.githubusercontent.com/BioPhoton/angular-alternative-validation/master/resources/demo.gif)

Maybe it helps someone... :-)

![Animated Gif](https://raw.githubusercontent.com/BioPhoton/angular-alternative-validation/master/resources/demo.gif)

**Comment by benneq** [comment]
I was looking for some warnings, too. And found this solution on StackOverflow:

https://stackoverflow.com/a/40369424/1321564

Looks pretty simple. It just uses the usual validators API, but always returns `null` and instead writes its results into `AbstractControl.warnings`. It's not the most versatile and clean solution, but it's really simple and should work for most scenarios, I guess.

**Comment by BioPhoton** [comment]
@benneq I tried nearly all solutions online. Everything is clumsy or buggy.

Therefor I created this lib:
https://github.com/BioPhoton/angular-alternative-validation

Are there and downsides or bugs?

**Comment by benneq** [comment]
Downsides? Of course, But that‘s not your fault :)
It looks and feels clumsy to use. And it doesn‘t integrate that good with reactive forms that nice.

... And I‘m using reactive forms only. 

I‘m thinking about creating my own custom FormBuilder, which is basically the same as the Angular FormBuilder, but additionally provides two extra extra arrays for warnValidators and asyncWarnValidators.

**Comment by BioPhoton** [comment]
A custom FormBuilder is a cool idea! 😎
How will you implement the actual logic? A custom FormControl or some other concepts?

**Comment by benneq** [comment]
The idea is cool as long as you don't have to maintain the code and adopt the changes made by the Angular team every new version 😆 

I'd really appreciate if the @angular/forms would provide a more flexible API. I really don't like extending framework APIs. But if it's really necessary I'd like to reuse as much code as possible.

I have **not** thought about the "how" yet that much. But I guess I'd do it like that:
- MyFormBuilder extends FormBuilder
- MyFormBuilder should have the exact same API as the original FormBuilder, but:
- It will return instances of MyFormGroup, MyFormControl, MyFormArray
- Each of those should simply extend the original Angular counterparts. But with one simple (hopefully?!) change:
- Every class will get the error logic duplicated. Then there will be the original error logic, plus the copy of it, which then will be called warning.

I want to achieve that the warning logic behaves exactly like the error logic. But of course it wouldn't make the form invalid.
In the end there should be methods like `getWarning`, `hasWarning`, `setWarnings`, just like the error methods we currently have.

I'm not sure yet if that's worth the trouble.
