### ISSUE TITLE
ngc reports a build error when tsc succeeds with same tsconfig

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#18196]
### Reproduction
1. Clone https://github.com/jelbourn/material2/tree/tsc-v-ngc-error
2. `npm i`
3. Run `./node_modules/.bin/tsc -p ./src/cdk/tsconfig-build-tmp.json`. This succeeds.
4. Run `./node_modules/.bin/ngc -p ./src/cdk/tsconfig-build-tmp.json`. This fails with an error:
```
Error at /usr/local/google/home/jelbourn/material2/src/cdk/platform/index.ts:10:9: 
Module '"/usr/local/google/home/jelbourn/material2/src/cdk/platform/platform"' has no exported member 'Platform'.
```

If I change the `files` entry in the aforementioned tsconfig from `platform/index.ts` to `platform.ts` with the same content, `ngc` works. 

(also worth mentioning that the reported file _does_ have exported member 'Platform')

**Comment by chuckjaz** [comment]
As discussed offline, the metadata bundler doesn't handle a file in a directory blow the `tsconfig.json`. It ends up generating synthetic `index.ts` files that imports modules from the  wrong location.

**Comment by chuckjaz** [comment]
To be clear. This is currently not supported and should be reported as an error instead of producing an invalid module.

**Comment by JoostK** [comment]
The original reproduction is no longer available so I can't check for sure whether this has been resolved, but given that the metadata system is no longer used in Ivy I'm closing this as resolved.
