### ISSUE TITLE
Angular 4.3 HttpClient throws 'XMLHttpRequest is not defined' in Node environment (Angular Universal)

### ISSUE THREAD

**Issue by patrickmichalina** [angular/angular#18199]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using HttpClient from `import { HttpClient } from '@angular/common/http'` throws `ReferenceError: XMLHttpRequest is not defined
 ` when rendered using `ngExpressEngine` from `import { ngExpressEngine } from '@nguniversal/express-engine'`

## Expected behavior

To not throw an error just like the original Http client.

## What is the motivation / use case for changing the behavior?

A temporary fix is to use this line of code at the top of the Node server:

`(global as any).XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;`

## Environment

<pre><code>
Angular version: 4.3.0

Browser:
- [x] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by neilhem** [comment]
Yeah, I have the same error when I run app in node using this [tutorial](https://medium.com/@evertonrobertoauler/angular-4-universal-app-with-angular-cli-db8b53bba07d)

**Comment by hiepxanh** [comment]
@patrickmichalina you save my life, I still don't know to put (global as any).XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest to which file until see your question 👍

**Comment by BostjanPisler** [comment]
This might also help: https://github.com/angular/universal-starter/issues/448#issuecomment-333158166
