### ISSUE TITLE
about SEO

### ISSUE THREAD

**Issue by AlicePrincess** [angular/angular#18198]
I create my blog with ng4,but SEO is not friendly to google with SPA,I want to know how to solve

**Comment by robwormald** [comment]
Hi @AlicePrincess, GitHub issues are not for support requests - in the future, please use gitter.im/angular/angular, StackOverflow, etc for help/"how-to" questions.

You might find https://blog.nrwl.io/be-one-with-the-crawler-pt-1-40734d95d4af useful.

Thanks!
