### ISSUE TITLE
[min] and [max] pipes doesn't work

### ISSUE THREAD

**Issue by vadjs** [angular/angular#18204]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Looks like [min] and [max] pipes not working now.

## Expected behavior

Using min and max attributes should add validators for Angular forms.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/MfUJ7wbLsaDT7uOYgD1e?p=preview - here is modified example form that have min/max validators that doen't work.

## What is the motivation / use case for changing the behavior?

Fix non-working code.

## Environment

<pre><code>
Angular version: 4.3.0

Browser:
- ALL
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 8.1.3  
- Platform:  Windows

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/pull/17622

**Comment by vadjs** [comment]
@ericmartinezr Looks like this fix merged 28 days ago and shuld be in 4.3.0. But i tested it in Angular 4.3.0 and this bug still here.

**Comment by tytskyi** [comment]
@vadjs this was revert, those directives are removed in 4x branch

**Comment by kara** [comment]
Min and max validator directives were removed in #17622, as they added breaking changes and this was not appropriate in a minor release. As this is expected, closing the issue.
