### ISSUE TITLE
Entry component scan reports enum references in route data as an internal error.

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#18207]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

If an enum reference is included in the metadata, in a route, for example, the compiler will report an internal error.

## Expected behavior

This should compile correctly.

## Minimal reproduction of the problem with instructions

In a `ng new` application add the following to `app.module.ts`'s `@NgModule` imports:

```ts
    RouterModule.forRoot([{
      path: 'somePath',
      component: AppComponent,
      data: {
        value: SomeEnum.SOME_VALUE1
      }
    }]),
```

where `SomeEnum` is imported from another module.

**Comment by atscott** [comment]
Closing -- this now works in the latest version of Angular with Ivy: https://stackblitz.com/edit/angular-ivy-router-base-s2eght?file=src%2Fapp%2Fapp.module.ts
