### ISSUE TITLE
Classic inheritance, Child component doesn't update Parent Property . Even with ChangeDetectorRef

### ISSUE THREAD

**Issue by titusfx** [angular/angular#18203]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Classic inheritance, Child component doesn't update Parent Property . Even with ChangeDetectorRef

I have a Parent component with an input radio and the checked property is associated with a member variable isActivated.

In the child component on click event I do: this.isActivated =!this.isActivated and it doesn't change the checked. If I implement the same thing in the Parents works.

## Expected behavior

It should checked and unchecked the parent input radio

## Minimal reproduction of the problem with instructions

I tryed to do it on plunker but It throw another error ( in my version it doesn't throw an error )
https://plnkr.co/edit/gLkdo73OHuOVr8TnnJZm?p=info

FILE: nav-item.ts

import { Component, OnInit, Input, Output } from '@angular/core';
@Component({
  selector: 'nav-item',
  template: ` 
  <input type="radio" [checked]="isActivated" />
  `,
})
export class NavItemComponent implements OnInit {
  @Input('activated') isActivated = false;
  ngOnInit(){
    
  }
}
@Component({
  selector: 'nav-item-child',
  template: ``,
})
export class NavItemChildComponent extends NavItemComponent implements OnInit {
  ngOnInit(){
  }
}

FILE: app.ts

//our root app component
import {Component, NgModule, VERSION} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser'
import { NavItemComponent, NavItemChildComponent} from './nav-item.ts'

@Component({
  selector: 'my-app',
  template: `
    <nav-item-child (click)="activateItem($event)"></nav-item-child>

  `,
})
export class App {
  
    activateItem(event){
    this.isActivated = !this.isActivated ;
    
    //this.detector.detectChanges();

  }
}

@NgModule({
  imports: [ BrowserModule ],
  declarations: [ App,
   NavItemComponent, 
   NavItemChildComponent],
  bootstrap: [ App ]
})
export class AppModule {}

## What is the motivation / use case for changing the behavior?

I have a nav-item ( general one ) and I want to every component that inherit from it can behave like it and more ( classical inheritance )

## Environment

<pre><code>
Angular version: 4
  "@angular/core": "^4.0.0",

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
v6.11.0
- Platform:  
Linux
Others:

</code></pre>

**Comment by titusfx** [comment]
I checked [this](https://github.com/angular/angular/issues/11606)
That has similars but differents issues.

**Comment by chuckjaz** [comment]
@titusfx We do not support inheritance of the template which I believe you are implying we should.

We have an exiting issue tracking a potential way to improve this #13766. However, using inheritance in this way is not recommended for Angular. Consider recasting your behavior as a directive instead of a base class.
