### ISSUE TITLE
router.resetConfig() exception: Invalid configuration of route ''

### ISSUE THREAD

**Issue by GuyShaanan** [angular/angular#18214]
## I'm submitting a...
<pre><code>[x] Bug report</code></pre>

## Current behavior
Using router.resetConfig() on versions > 4.1.3 and passing an empty route (`{path: '', component: HomeComponent}`) an exception is thrown in AOT:

![image](https://user-images.githubusercontent.com/7248108/28336437-9bc2f5ec-6c0a-11e7-869b-48ceb4723da7.png)

And somehow the component is undefined:
![image](https://user-images.githubusercontent.com/7248108/28336658-805ccd2c-6c0b-11e7-889b-52cd18ba1997.png)

## Expected behavior
On versions <= 4.1.3 everything works.
No exception is thrown, and component is not undefined:
![image](https://user-images.githubusercontent.com/7248108/28336888-4bb04bde-6c0c-11e7-8eba-c5df00b94974.png)

## Minimal reproduction of the problem with instructions
```
git clone https://github.com/GuyShaanan/_router-config-repro.git
cd _router-config-repro
npm install
npm run start
```
Observe exceptions in console and that component is undefined.

Now change all 4.2.3 versions to 4.1.3 in package.json:
```
sed -i 's/4.2.3/4.1.3/' package.json
rm -rf node_modules/@angular
npm install
npm run start
```
Observe no exception is thrown, and component is not undefined.

## What is the motivation / use case for changing the behavior?
Of course this is a small repro. The exception thrown in the real application actually breaks further navigation.

## Environment

<pre><code>
Angular version > 4.1.3
AOT

Browser:
- [x] Chrome (desktop) version 59
 
For Tooling issues:
- Node version: 6.10.3
- Platform:  Linux
</code></pre>

**Comment by alxhub** [comment]
In your repro you have a circular dependency between `app-routing.module.ts` and `home.component.ts`. This is why `HomeComponent` appears `undefined`. There are probably subtleties between 4.2.x and 4.1.x that cause this to break in one vs the other, but circular deps are not a use case that we support.
