### ISSUE TITLE
Tour of Heroes - 7. HTTP: Not closed <div> tag

### ISSUE THREAD

**Issue by daydr3am** [angular/angular#18219]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Hi!
This is not really an issue, just a not closed div tag on your tutorial page 'Tour of heroes'.
The Error is located above this section: https://angular.io/tutorial/toh-pt6#heroes-and-http

![angular tour of heroes html misstake](https://user-images.githubusercontent.com/18628786/28354757-607b84ac-6c61-11e7-9a7d-e3c858993bc8.png)

I think the page should have look like this:

![angular tour of heroes fixed](https://user-images.githubusercontent.com/18628786/28355064-bf020ef0-6c62-11e7-9788-45638456314c.png)

Now the lower 3/4 of the page are having this div style.

**Comment by gkalpak** [comment]
Thx for reporting, @daydr3am. Would you be interested in submitting a PR? :grin:
(The file that needs to change is [tutorial/toh-pt6.md][1].)

[1]: https://github.com/angular/angular/blob/master/aio/content/tutorial/toh-pt6.md

**Comment by matt24ray** [comment]
https://github.com/angular/angular/pull/18239

**Comment by daydr3am** [comment]
@gkalpak Did it 👍

**Comment by daydr3am** [comment]
Sry did not saw your PR @matt24ray 
Thanks!
