### ISSUE TITLE
Variables outside direct scope prevent dead code elimination

### ISSUE THREAD

**Issue by Pikachews** [angular/angular#18217]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Dead code isn't eliminated from production builds if the conditional statement uses a variable/constant from outside of its direct scope.

## Expected behavior

Dead code should be eliminated from the production build if the conditional statement always fails, even when the conditional statement uses variables or constants outside of its direct scope.

## Minimal reproduction of the problem with instructions

Using Angular CLI:

1. Create a new project
2. Add the following code
3. Build using `ng build --prod`

### Variable/constant within direct scope of conditional statement
**This example works as expected.**
`src/app/app.component.ts`
```typescript
  constructor() {
    let show = false;
    if (show) {
      console.log('hello world! i am dead code!');
    }
  }
```
Results: `console.log` statement does not show up in main bundle. ✔️ OK

### Variable/constant outside direct scope of conditional statement
Move the `let show = false;` statement anywhere outside of the constructor.
Even change it to a const, if you wish.
Results: `console.log` statement **does** show up in the main bundle. ❌ Not OK

This is also the case when using environmental variables exported from `src/environments/environment.ts`.

## What is the motivation / use case for changing the behavior?

Dead code should not show up in production builds.

## Environment

<pre><code>
Angular version: 4.3.0
</code></pre>

**Comment by devoto13** [comment]
I think this should be reported to either https://github.com/angular/angular-cli/ or UglifyJS itself. Angular is not responsible for this type of dead code elimination.

**Comment by alxhub** [comment]
@devoto13 is correct.

**Comment by Pikachews** [comment]
Thanks, I wasn't sure where this should go, so I went with angular. Sorry for the trouble.
