### ISSUE TITLE
What is synchronous response body access in the new HttpClient

### ISSUE THREAD

**Issue by maximusk** [angular/angular#18218]
[The commit that introduced](https://github.com/angular/angular/commit/37797e2) new HttpClient has the following in its description:

> The new API improves significantly on the ergonomics and features of the legacy
> API. A partial list of new features includes:
> 
> * Typed, **synchronous response body access**, including support for JSON body types

I'm curios to know what is meant by synchronous response body access. Can anyone provide an example? I couldn't find anything [in the official docs](https://angular.io/guide/http) and also there's no mentioning of `synchronous` word in the sources comments.

Thanks

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by alxhub** [comment]
Consider the `fetch()` API, which returns a `Promise<Response>`.

Once you have that `Response`, you can access the status and headers, but getting at the body requires a separate asynchronous step: `res.json()` for example returns a `Promise<Object>`, and `res.text()` returns a `Promise<string>`.

In `HttpClient`, `HttpResponse<string>` has a field `.body` of type `string` - there's no need to wait on a `Promise` to see the body once you have the response.

**Comment by maximusk** [comment]
@alxhub , hey, thanks for answering. It is true the fetch API evaluates body asynchronously. But the older http client evaluated body synchronously. So I don't see where the new http client is different. Can you help me understand?
