### ISSUE TITLE
I have a project with more than 4000 lazy loaded modules. How could i process aot build  in a reasonable time?

### ISSUE THREAD

**Issue by jjlgjkkl** [angular/angular#18221]
I have a project with more than 4000 lazy loaded modules. How could i process aot build  in a reasonable time?

any suggestion would be appreciated

**Comment by notsonotso** [comment]
@jjlgjkkl You can wait 3-4 months for the new AOT compiler to arrive. Which is much longer than waiting for a 4000 module compile to complete on the current compiler, if it completes at all: https://github.com/angular/angular-cli/issues/5618

**Comment by kevinphelps** [comment]
You might want to consider splitting that into separate apps and using a reverse proxy to tie it back together in production. I can't imagine an AOT compilation with 4000+ lazy loaded modules ever being fast.

**Comment by istiti** [comment]
4k 😂 Joke
