### ISSUE TITLE
aio: ? Clicks on radiobutton are not seen by change-detection.

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#18227]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
if a click on a radiobutton changes its template variable, it's not seen bij angular.

```
@Component({
  selector: 'my-app',
  template: `<h1>Hello {{name}}</h1>
  <input type="radio" name="sel" #r1> first<br>
  <input type="radio" name="sel" #r2> second<br>
  <div *ngIf="r1.checked">Selected first </div>
  <div *ngIf="r2.checked">Selected second</div>
  `
})
export class AppComponent { name = 'Angular';

  unrelated() {
    console.log('do something')
  }
}
```
[see this in action on plnk](https://plnkr.co/edit/4BaLK6a3b6iE4X9yuaAg?p=preview) there is an added completely unrelated button in there. When that button is clicked, the view is updated as expected.

## Expected behavior
The divs with the ngIf on them should become visible if the corresponding radio is selected. 

## Minimal reproduction of the problem with instructions
See the plunk and code above

**Comment by pkozlowski-opensource** [comment]
@SanderElias why would you expect Angular to run change detection on radio button click? You are not listening to any events (`change` would probably be a good candidate). 

If this one would to be "fixed" than you would have to run CD on _any_ DOM event which obviously would bring performance to the crawl...

**Comment by SanderElias** [comment]
@pkozlowski-opensource I do agree with you, but this thing should work according to docs. If that is indeed the reason it doesn't work. (I did some debugging, and I think you are right!) it should be reflected in the documentation.

**Comment by pkozlowski-opensource** [comment]
It is the reason :-) You should probably do sth along https://plnkr.co/edit/3InszUWFKdpSG7gg4oCU?p=preview if you don't wan't to use forms.

Regarding documentation: not sure where / how this should be documented... Let the documentation team decide...

**Comment by pkozlowski-opensource** [comment]
@SanderElias could you please update the issue title / description to indicate that this is the documentation issue? Also if you've got any suggestion as to _where_ this should be documented, it would be helpful.

**Comment by SanderElias** [comment]
@pkozlowski-opensource Updated the title. I already knew how to work around the issue,  but thanks for the sample anyway. BTW, adding a (dummy click handler)[https://plnkr.co/edit/tkp9bih9hTSuVFMb03NY?p=preview] fixes it also. `(click)="unrelated()"` makes sure it works. But that's just plain ugly. It does kind of support my issue on change-detection.

**Comment by josephperrott** [comment]
Closing as this topic is now covered in our documentation warning against the use of side-effects.
