### ISSUE TITLE
[Feature] Add --outDir / --genDir to NGC CLI

### ISSUE THREAD

**Issue by woppa684** [angular/angular#18220]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Description of the problem
In our (big company) build environment we have to supply the outDir / genDir for ngc through the command line since the tsconfig,json files are in version control and we're working in many different branches (the output path relies on the current branch but is not relative). With the current NGC this doesn't seem possible.

## Feature request
First of all, the real solution to our problem would be to have a good solution for creating reusable component libraries of course (since this is essentially what a lot of people are waiting for, see https://github.com/angular/angular-cli/issues/6510 for example) but in the meantime we have to use NGC directly (as well as gulp, node-sass and gulp-inline-ng2-template of course). Therefore being able to specify the outDir / genDir would already be very helpful.

<pre><code>
Angular version: 4.3.0
</code></pre>

**Comment by alxhub** [comment]
This is the Angular framework repo. The CLI tracks its own issues in their repo, https://github.com/angular/angular-cli. You should file this over there :)

**Comment by woppa684** [comment]
@alxhub sorry, I thought that compiler-cli (where ngc is, right?) and tsc-wrapped were part of this repo and that angular/cli just used these modules. Am I wrong?

**Comment by alxhub** [comment]
@woppa684 ahh I see what you mean. You want to override the `ngc` output directory, not the CLI's directory?

**Comment by woppa684** [comment]
Indeed, angular/cli has an --output-path switch for the build command but ngc itself doesn't, the genDir can only be supplied in the tsconfig.json and I can also not specify --outDir like with tsc-wrapped (which forwards all compiler options after -- to tsc itself).
