### ISSUE TITLE
Add option in Dart transformers to just inline templates

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1822]
This is needed for tests that mock out HTTP (or don't have a server at all). It is also required to be able to use FakeAsync in tests.

/cc @matanlurey

**Comment by matanlurey** [comment]
Even if this isn't used in the build system, it should be an option for transforming tests for a rapid-refresh cycle. Let's chat offline.

**Comment by naomiblack** [comment]
This is also b/21800437

**Comment by TedSander** [comment]
Note this should inline the html template and the styles.

**Comment by TedSander** [comment]
If we use transformers the templateUrl is already inlined. I have a pull request here to do the same for styles.
https://github.com/angular/angular/pull/2599

**Comment by TedSander** [comment]
This should be closed by #2599

**Comment by TedSander** [comment]
I believe this is closed. @yjbanov @naomiblack
