### ISSUE TITLE
Save the state of the complete component

### ISSUE THREAD

**Issue by AbhishekKaura25** [angular/angular#18235]
I am working on a application where the user can open multiple person data and each person details has multiple tabs like address, work etc. I want to save the state of each person so that the user can come back to the same state while switching between those two person. 

For example if person 1 has work tab open and if I switch to person 2 perform some functionalities and come back to person 1 he should still see the work tab.

Is there any way to save the state of the complete component to the person so that I can display it again in angular 4.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
