### ISSUE TITLE
Associated docs examples with appropriate versions of Angular

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#18230]
All the docs examples are currently build against 4.2.x.
Also the plunkers link to the `latest` version, rather than the version of that release of the docs.

**Comment by petebacondarwin** [comment]
We will update the current versions to point to appropriate pinned versions on npm - @Foxandxss will document what files need to change for the next minor/major release.

We will change the Travis builds to run against the local build rather than released npm versions.

**Comment by petebacondarwin** [comment]
We also intend to make the e2e tests fast enough (by splitting them into two shards) that we can then make then non-optional in Travis.

**Comment by gkalpak** [comment]
Is this taken care of by #18238 or is anything still missing?

**Comment by petebacondarwin** [comment]
I am not sure if we have fixed the plunkers situation...

**Comment by IgorMinar** [comment]
We've improved this situation a bit recently, but as far as I know it is not fully resolved because either the example dependencies are unpinned or they are becoming stale without anyone monitoring or taking action.

**Comment by Foxandxss** [comment]
Stackblitz will fix the "live-example" part of it because it will be pinned to the example's package.json. Now, the issue is having that file up to date.

**Comment by petebacondarwin** [comment]
Now we are on StackBlitz this should be solved.
