### ISSUE TITLE
custom EventManagerPlugin

### ISSUE THREAD

**Issue by Delagen** [angular/angular#18232]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
No accessible EventManagerPlugin from exports

## Expected behavior
Allow write custom implementations of EventManagerPlugins

## Environment
Angular version: 4.3.0

**Comment by Delagen** [comment]
https://github.com/angular/angular/issues/16885

**Comment by emilio-martinez** [comment]
This would be extremely helpful.

**Comment by yinnping** [comment]
Is there any update for this feature request?
