### ISSUE TITLE
Update angular.io blog URL

### ISSUE THREAD

**Issue by aciccarello** [angular/angular#18233]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior

Footer of angular.io links blog to https://blog.angularjs.org/

## Expected behavior

Footer blog link should go to https://blog.angular.io/

## Minimal reproduction of the problem with instructions

See footer of https://angular.io/

## What is the motivation / use case for changing the behavior?

The angular blog has moved: http://angularjs.blogspot.com/2017/07/moving-angular-blog.html

## Environment

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by aravindfz** [comment]
@alxhub How to contribute to that blog. Please guide me.

**Comment by daydr3am** [comment]
#18233

**Comment by ooystein** [comment]
Looks like #18252 fixed the links in the top but forgot to update the link in the footer. See #18448 for new PR
