### ISSUE TITLE
TemplateUrl parent directory not parsing right

### ISSUE THREAD

**Issue by zrsio4** [angular/angular#18234]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

With a component in src/folder, defining a template with a templateUrl in the parent folder using a relative url like "../parent.component.html" results in the error:

Unhandled Promise rejection: Failed to load src/folder./parent.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load src/folder./parent.component.html

## Expected behavior

Relative path gets parsed correctly

## Minimal reproduction of the problem with instructions

An Angular project set up like this: http://plnkr.co/edit/VRED060c8BPUohhnUDce?p=info
But since plnkr doesn't seem to acutally use folders, can't quite repro the problem in the plunk.

## What is the motivation / use case for changing the behavior?

Sharing component templates 

## Environment

<pre><code>
Angular version: 4.3.0
Browser:
- [x] Chrome (desktop) version 59.0.3071.115
- [?] Chrome (Android) version XX
- [?] Chrome (iOS) version XX
- [x] Firefox version 54.0.1
- [?] Safari (desktop) version XX
- [?] Safari (iOS) version XX
- [x] IE version 11.413.15063.0
- [x] Edge version 40.15063.0.0
 
For Tooling issues:
- Node version: 6.10.3
- Platform:  Windows 10

Others:
</code></pre>

**Comment by zrsio4** [comment]
If I define templateUrl as "./../parent.component.html", the expected behavior is observed

**Comment by pkozlowski-opensource** [comment]
This seems to be fixed in the latest Angular 9.x: https://stackblitz.com/fork/angular-ivy?file=src%2Fapp%2Fapp.component.ts
