### ISSUE TITLE
Button click event not fired when view changed on focus change

### ISSUE THREAD

**Issue by dobrevad** [angular/angular#18244]
I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Button click event is not fired when the component view changes between the user clicking on the button and the click event being fired.

In particular:
Suppose we have a button click event handler and another element that is shown with ngIf when a form control becomes touched.
We first focus on the form control. Then we click the button and expect that this will fire the button click event. What happens is that instead the focus changes, the form control touched property evaluates to true and this shows the otherwise hidden element. The button click event is never fired.
Then if we click again, the event is fired because the view doesn't change anymore.

## Expected behavior
To always fire the click event and execute the event handler.

## Minimal reproduction of the problem with instructions
Plunker: http://plnkr.co/edit/8kR2T3EUVQT5rgtzo27O?p=preview

Steps to reproduce:
1. Focus on the input. 
2. Click the button.
3. The text above the input is shown.
4. Issue:
[Expected]: to log "button clicked" in the developers console.
[What happens]: the click event is never fired

## Environment
<pre><code>
Angular version: 4.3.1

Check whether this is still an issue in the most recent Angular version: yes

Browser:
- [ x] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
- Platform:  Mac, Linux

</code></pre>

**Comment by Toxicable** [comment]
Works fine here http://plnkr.co/edit/u9zLbGLUrs7kiOSeOJFK?p=preview
when you `div` appeared it moved the button, casuing the click to not occur

**Comment by dobrevad** [comment]
Interesting! Could you explain why  shifting down the elements would cancel the click event?

**Comment by dobrevad** [comment]
Nevermind. I got it. The issue is that the click is composed of mousedown and mouseup.
Since the view is shifting, the mouseup event is never registered on the button and thus no click is fired.

Thank you!

**Comment by HariPrasanth09** [comment]
solution please @dobrevad
