### ISSUE TITLE
404 (Not Found) errors in zone.js

### ISSUE THREAD

**Issue by foo-baar** [angular/angular#18246]
Ok before I give up on my attempt to set up a local environment to run multipul apps from one directory with common/shared resources, I thought to post here in case someone can help.
(nots: there is absolutely rare discussion on any forum about this).

I have this directory structure (locally):

```
|AngularApps
|-App1
|-App2
    |---app
    |---index.html
    |---tsconfig.json
    |---tslint.json
    |---typings.json
    |---systemjs.config.js
|-node_modules
|-package.json
```

And then I use lite-server in root, hence I have modified the path in systemjs.config.js to:
```
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'App2/app',
```
Now when I load the App1 zone.js is not able to find most of my components:
![screen shot 2017-07-20 at 3 11 53 pm](https://user-images.githubusercontent.com/13655874/28411263-d5a482c2-6d5d-11e7-8ab5-504035923778.png)

I couldn't find any topic online pointing to the same.
Idea is to avoid duplicating all resources.

Thanks much in advance for consideration.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by foo-baar** [comment]
Hello @pkozlowski-opensource As I mentioned in my original post I tried all ways before posting here.

Here is the query on stackoverflow https://goo.gl/qAcmkK no one really knows much about it and hence It becomes responsibility of the team to take it up.

If you can point me to the link where its addressed then nothing like it.

But please take ownership.
