### ISSUE TITLE
docs(aio): Simple deploy not working with html templates

### ISSUE THREAD

**Issue by tuhinte** [angular/angular#18255]
Simple deploy not working when we specify some html in templateUrl
https://angular.io/guide/deployment#dev-deploy

**Comment by daydr3am** [comment]
Can you give us some more information? Where do you specify the template Url? In a Component Meta Data?

**Comment by aravindfz** [comment]
Add more information with a working example. Also add some code to it

**Comment by tuhinte** [comment]
Here what I have done:
1. cloned the quickstart setup described in https://angular.io/guide/setup and installed dependencies
2. Deployed successfully in "simplest method". But when I changed default component metadata from
`@Component({
  selector: 'my-app',
  template: `<h1>Hello {{name}}</h1>`,
})`
to
`@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
})`
its unable to load app.component.html(which I have created in the src/app directory) and throws 404 in console. I have extracted inline template to templateUrl app.component.html
This is the simplest way to replicate my problem.

**Comment by tuhinte** [comment]
Yeah, already tried that with fresh quick start setup. It will return following error while ng build:
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'

**Comment by daydr3am** [comment]
Another Problem is, that the Quickstart Example is for local developing purposes. There some restrictions and modifications and maybe this is the reason why it is not possible to build. I would recommend creating a new Application with the CLI. 
You can use this Tutorial:
https://angular.io/guide/quickstart

**Comment by tuhinte** [comment]
Yes, creating app by `ng new`  command works fine. Thanks.
