### ISSUE TITLE
docs(aio): API missing constructor overloads

### ISSUE THREAD

**Issue by rdsedmundo** [angular/angular#18258]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, the documentation from the API doesn't display constructor overloads even if they exist.

## Expected behavior

All overloads should be displayed in the API documentation.

## Minimal reproduction of the problem with instructions

See the documentation for the new HttpRequest API.
https://angular.io/api/common/http/HttpRequest

There's only one constructor descriptor available, but it has 4 overloads, as we can see via the source code.
https://github.com/angular/angular/blob/4.3.1/packages/common/http/src/request.ts#L126-L147

**Comment by petebacondarwin** [comment]
I'll sort this out tomorrow.
