### ISSUE TITLE
Http request status always pending

### ISSUE THREAD

**Issue by limpep** [angular/angular#18256]
## I'm submitting a...
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

When I do a new http request, for example a Http get

```
  getCustomerList(): Observable<CustomerSalesContainer[]>{
    return this.http.get(this.customersListUrl,  this.authService.getAuthToken())
      .map(res => <CustomerSalesContainer[]> res.json())
      //will try very 35 seconds
      .retryWhen(errors=> errors
        .delayWhen(error=>Observable.timer(35000)))
      .timeout(3000)
      .catch(this.handleError)
  }
```

The request is put in a pending state, this seems to happen with the version 4.3.1 and Chrome 59. After refreshing the page and making the request again same issue, however sometimes the request is processed. 

When the request is in the pending status the back server is not being hit.

## Expected behavior

Request to hit the backend. 

## Environment

<pre><code>
@angular/cli: 1.2.1
node: 8.2.0
os: darwin x64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/language-service: 4.3.1
@angular/cli: 1.2.1
@angular/compiler-cli: 4.3.1

Browser:
- [x] Chrome (desktop) version XX

For Tooling issues:
- Node version: 8.2.0
- Platform:  Mac

Others:

**Comment by micksatana** [comment]
Can you try this
[ ] try if http.get() to the localhost url is working, if so..
    [ ] check whether the requesting url is cross-site?
     - in case requesting to another domain name, [ ] make sure cross-origin tag set correctly
    [ ] what is the protocol of the url? http or https?
     - in case of https, [ ] if you navigate in the browser, cert must be green, or [ ] try set to ignore the cert validation

**Comment by alxhub** [comment]
I'll need a reproduction in order to debug this, @micksatana. Please re-open if you have one!

**Comment by limpep** [comment]
@alxhub @micksatana sorry for the late response. This was an issue with the back end server. Mainly to with the Redis client we were using. Thanks.

**Comment by ashish701ranjan** [comment]
@limpep Hi, can you please share what was the problem with your backend server. I am having the same issue. I am using Apache

**Comment by limpep** [comment]
@ashish701ranjan the solution was quite simple before we were using https://github.com/xetorthio/jedis, but then we switched to https://projects.spring.io/spring-data-redis/ and everything started working as expected, hope that helps.
