### ISSUE TITLE
Router without <router-outlet>

### ISSUE THREAD

**Issue by jurito** [angular/angular#18253]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

In an app with custom routing behavior (without _router-outlet_) everything works fine but when navigating from a path with a parameter to the same path with another parameter value.
It then crashes with the error **_TypeError: Cannot read property 'component' of null_** in the router function **_PreActivation.traverseRoutes_**

## Expected behavior

No error, or not being able to use the router without any outlets.

## Minimal reproduction of the problem with instructions

- [plunkr](https://plnkr.co/edit/brxSsU9xjjWJNwwA6VWq?p=preview) (watch the console)
- navigate from crisis center to hero 11 --> **OK**
- navigate from hero 11 to heroes --> **OK**
- navigate from hero 11 to hero 12--> **NavigationError**

All angular libraries updated to version 4.3.1
</code></pre>

**Comment by jurito** [comment]
This issue is solved by adding a '**never**' configuration parameter to the Route's **RunGuardsAndResolvers** configuration option, as seen in [1d7b9f93ec91f488366d86be7c0ce196f32ed956](https://github.com/jurito/angular/commit/1d7b9f93ec91f488366d86be7c0ce196f32ed956) . If desired, i'll submit a pull request.

**Comment by VagrantAI-c** [comment]
Actually the problem is still relevant, any new info on this?

**Comment by maxkorz** [comment]
@jurito could you please pull request your commit? I'd be great to have "never" option for `runGuardsAndResolvers`
