### ISSUE TITLE
Feature: add SelfProvider

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#18251]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, if You wan't to add itself in component's providers list, You have use forwardRef and write something like this:
```ts
const MY_CONTROL_VALUE_ACCESSOR_PROVIDER = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => MyComponent),
  multi: true,
}

@Component({
  providers: [MY_CONTROL_VALUE_ACCESSOR_PROVIDER]
})
export class MyComponent implements ControlValueAccessor {}
```

## Expected behavior
We should able to create provider without explicitly referencing component, like this:
```ts
const CONTROL_VALUE_ACCESSOR_PROVIDER = {
  provide: NG_VALUE_ACCESSOR,
  useSelf: true,
  multi: true,
}

@Component({
  providers: [CONTROL_VALUE_ACCESSOR_PROVIDER]
})
export class MyComponent implements ControlValueAccessor {}
```

```ts
interface SelfProvider {
  provide: any,
  useSelf: true,
  multi?: boolean,
}
```
## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
Using SelfProvider makes code simpler and we can create generic providers which can be used in many components.
For example, there would be no need to create provider for NG_VALUE_ACCESSOR for each component. Making components which work with forms would be easier and programmers would be more encourage to do it.

**Comment by alxhub** [comment]
I don't think this feature will work - we need a real runtime reference to the token being provided.
