### ISSUE TITLE
docs(aio) request: add links to angular subdomains

### ISSUE THREAD

**Issue by loiane** [angular/angular#18257]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## What is the motivation
I believe it would be helpful to add the angular subdomains in the docs as well.
Some people don't know the existence of these links and it would be nice to be able to access other tools for the angular ecosystem from the docs website:
* cli.angular.io
* mobile.angular.io
* universal.angular.io
* protractor.angular.io
* material.angular.io
* and the newest addition blog.angular.io (current blog link still points to old blog)

**Comment by jenniferfell** [comment]
Issue partially resolved. 

**Done:** The Resources page (https://angular.io/resources) currently has links to this: 

cli.angular.io

**Done:** The main Angular site masthead currently has a link to this: 

blog.angular.io (current blog)

**Nothing to do:** This site currently redirects to angular.io:

mobile.angular.io

**To change:** The Resources page currently has these links, which should probably be changed: 

github.com/angular/universal (we should probably replace with link to universal.angular.io)
github.com/angular/material2 (we should probably replace with link to material.angular.io)


**To add:** The Resources page (https://angular.io/resources) does not  have this link: 

protractor.angular.io

**Comment by jenniferfell** [comment]
docsarea=resources

**Comment by LuisReinoso** [comment]
Hi! I could help to solve this isssue.
