### ISSUE TITLE
Flip hostProperties map key-values

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1826]
Currently, `hostProperties` are set like:
```js
hostProperties: {
  'propertyValueExpr': 'propertyName'
}
```

This is problematic because it prevents binding multiple properties / attributes to the same directive instance property. Flipping these would fix this and also make `hostProperties` consistent with `hostAttributes`, which is already in the format
```js
hostAttributes: {
  'attrName': 'attrValue'
}
```

FYI @pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
@jelbourn tend to agree, I also find the current order not very intuitive, was about to propose this myself. Having said this I think that switching to string-based host specification would make this problem go away, see: https://github.com/angular/angular/issues/1774#issuecomment-100617019

**Comment by mhevery** [comment]
Dup of #1774
