### ISSUE TITLE
window.location.hash can cause route event when intended purpose is to navigate to an anchor

### ISSUE THREAD

**Issue by samrantmedia** [angular/angular#18279]
I have a component which has a simple link to navigate to a subsection on the page, using anchor tags. 

<li class="nav-sublist" (click)="goTo('#students')">Students</li>

  goTo(location: string): void {
    window.location.hash = location;
  }

This works well. However, if there is a route that matches '/students' defined. Then instead of navigating to the anchor, it instead navigates to the students page. 

Of course, the workaround for this is simple, use a different name for the anchor tag. However, it seems worth noting. 

The project is using the angular cli 1.2.0, with angular 4.2.5 (chrome browser).

**Comment by mhevery** [comment]
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Comment by samrantmedia** [comment]
ok, thanks. I just tried to recreate on a plunkr and wasn't able to reproduce it there. Maybe it has been resolved in a newer version of angular or maybe the way routing happens in plunkr is different, making it difficult to reproduce. Anyway, really enjoying the angular 2 experience. Keep up the good work.
