### ISSUE TITLE
Throw during i18n extraction if two different contents have the same @@id

### ISSUE THREAD

**Issue by ocombe** [angular/angular#18272]
## I'm submitting a...
[x] Feature request

## Current behavior
If you use custom ids for i18n translations and you have multiple elements with that custom id that have different contents, you will only get one translation extracted.
e.g.: `<div i18n="@id">Hello world</div>` and `<div i18n="@id">Bye world</div>`
Only the first one will be extracted, and they will both be replaced by the same content when you use translations, but will be different in the source language.

## Expected behavior
We should throw an error, or at least print a warning when we extract if we have the same id for different contents.

## What is the motivation / use case for changing the behavior?
Avoid errors.

**Comment by db6edr** [comment]
Please highlight the same id for different contents thing. With the application I'm working on, we do have several elements with the same contents. For those, it must be possible to the use the same custom id without any warning.

**Comment by ocombe** [comment]
Of course, this would only warn if the content is different

**Comment by petebacondarwin** [comment]
Closing as we actually do now register warnings or errors for duplicate messages with different contents.
