### ISSUE TITLE
URLSearchParams should unescape parameters from the rawQuery

### ISSUE THREAD

**Issue by CarstenLeue** [angular/angular#18274]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When passing a rawQuery to the constructor of URLSearchParams and then reading the values via the getter methods, I expect to get the unescaped values. Instead the API returns the escaped value.

Example:
When decoding this query `a=b%20c%20%C3%A4%20%5B%5D` I expect the value of `a` to read `b c ä []`, instead the API returns `b%20c%20%C3%A4%20%5B%5D`.
 
## Expected behavior

I expect to get back the unescaped value.

## Minimal reproduction of the problem with instructions

The following testcases shows the issue

```typescript
    fit('should make sure URL params work as expected', () => {
        const p = new URLSearchParams('');
        const value = 'b c ä []';
        p.set('a', value);
        expect(p.get('a')).toEqual(value);

        const p1 = new URLSearchParams(p.toString());
        expect(p1.get('a')).toEqual(value);
    });
```

This is a plnkr to reproduce

http://plnkr.co/edit/aCPK7vxJBTz0XiKhtwUm?p=preview

## What is the motivation / use case for changing the behavior?
1. the behaviour should be symmetric between setting a value, then reading it vs. reading the value from a raw Query
2. the native URLSearchParams implementation handles this correctly

## Environment

<pre><code>
Angular version: 4.3.0

Browser:
- [x ] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 54.0.1 
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by Toxicable** [comment]
URLSeachParams isn't apart of Angular 
See https://github.com/angular/angular/issues/16378#issuecomment-297888348

**Comment by tytskyi** [comment]
But he imports it in the plunker from `http` package. And then there is a problem. And if i remove that import (use native `URLSearchParams`) then works as expected.

**Comment by Toxicable** [comment]
Oh my mistake. In that case I think this is relevant https://github.com/angular/angular/issues/11058#issuecomment-262852902

**Comment by CarstenLeue** [comment]
Ok, so is the official recommendation to fall back to the native implementation, then?

**Comment by atscott** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. `URLSearchParams` is no longer part of Angular. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
