### ISSUE TITLE
routerLinkActive doesn't work for links in inner router-outlet

### ISSUE THREAD

**Issue by ZwS** [angular/angular#18275]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Links marked with routerLinkActive doesn't become active if they were placed inside child router-outlet and route change was fired by clicking link in parent router-outlet

## Expected behavior

Links should become active if current route matches with route specified in routerLink.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/9PbITFctdokjdO8L16UI?p=preview
try to switch All Categories/Test category. Note that best tab become inactive.

## Environment

<pre><code>
Angular version: 4.2.2

Browser:
- [X] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 54
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by rchod** [comment]
+1 I have the same issue

**Comment by redplane** [comment]
Any updates about this ?
I'm having the same issue.

**Comment by atscott** [comment]
Issue appears to be resolved in v9: https://stackblitz.com/edit/angular-ivy-w8jgjj?file=src/app/app.module.ts
All Categories/Test category links get the 'active' class when clicked/navigated to.
