### ISSUE TITLE
Add scientific number format pipe

### ISSUE THREAD

**Issue by ocombe** [angular/angular#18276]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior
We don't have any way to format a number to a scientific notation

## Expected behavior
Being able to format numbers in scientific notation, ex 40000000 m = 4×10<sup>7</sup> m
This would be a new i18n pipe.

## What is the motivation / use case for changing the behavior?
Being able to format numbers in scientific notation

**Comment by petebacondarwin** [comment]
Scientific notation does not appear to be a major requirement and this could be implemented using third party libraries if required.
