### ISSUE TITLE
Route param auto change when refresh the window.

### ISSUE THREAD

**Issue by lishichao1002** [angular/angular#18273]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If the route param is a blank string, when refresh the window, the url auto change.
before refresh the url is 
`http://localhost:8000/#/bbs/topic/0/0/1/%20`
after refresh the url is
`http://test.gamebean.com:8000/#/bbs/topic/0/0/1/%2520`
one more time
`http://test.gamebean.com:8000/#/bbs/topic/0/0/1/%252520`
every time refresh , the url append with a 25 string.

## Expected behavior

The url keep the same after refresh.

## What is the motivation / use case for changing the behavior?

There is a router config as follow 
```javascript
{
        path: 'topic/:parentId/:childId/:type/:nickname',
        component: TopicComponent
}
```
As ng2 not support the optional router params. I using 0 as the placeholder instead of `parentId` and `childId`. using a blank string instead of `type` and `nickname`

so the url like follow:
```
http://localhost:8000/#/bbs/topic/1/11/1/zhangsan
http://localhost:8000/#/bbs/topic/0/0/1/zhangsan
http://localhost:8000/#/bbs/topic/0/0/1/%20
http://localhost:8000/#/bbs/topic/0/0/%20/%20
``` 
I find the optional router param in [https://github.com/angular/angular/issues/3525](https://github.com/angular/angular/issues/3525) but It does not apply to all of the case.

## Environment

<pre><code>
Angular version: 4.2.2

Browser:
- [x] Chrome (desktop) version 61.0.3128.0

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
You should use matrix params for optional params as described here:

https://angular.io/guide/router#heroes-list-optionally-selecting-a-hero
