### ISSUE TITLE
Docs for angular minimal project setup ?

### ISSUE THREAD

**Issue by paska27** [angular/angular#18281]
`ng new` is great to play with ng.  
But when it comes to real project setup, i would prefer to start it completely blank,  
because project is well maintained and clean when one adds stuff only when it is needed.  
I personally did not found good docs on the matter.  
Should this be added to official angular docs ?  

A boilerplate something like [this](https://github.com/paska27/ng-bare).

**Comment by m0t0r** [comment]
@paska27 this repository is for Angular framework, not Angular CLI, please open issues in appropriate place. To answer your question, `ng new` has `--minimal` flag which will scaffold you a minimal angular app. You can find documentation for `ng new`[here](https://github.com/angular/angular-cli/blob/master/docs/documentation/new.md).
