### ISSUE TITLE
ViewChild / ViewChildren: read multiple directives / tokens of the same element

### ISSUE THREAD

**Issue by macjohnny** [angular/angular#18280]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using `
@ViewChildren(SomeComponent, {
  read: RouterLink
})
` 
you can query for elements of `some-component`  and get their corresponding `routerLink` directive.
In order to simultaneously get multiple directives / tokens of the same element, 
for a single element you would add template references like 
`<some-component routerLink="some-route" #refRouterlink="RouterLink" #refSomeComponent #refElementRef="ElementRef">`  
and for a list of elements like you expect in `ViewChildren` you would have to write a directive like
```
@Directive({
  'selector': 'some-component'
})
class MyDirective {
  constructor(
    public elementRef: ElementRef,
    @Self() @Inject(RouterLink) public routerLink: RouterLink,
    @Self() @Inject(SomeComponent) public someComponent: SomeComponent
  ) { }
}

@Component({
selector: 'my-app', 
template: `
<some-component routerLink="someroute1">
<some-component>
<some-component routerLink="someroute3">
` 
})
class MyAppComponent {

  @ViewChildren(MyDirective) myDirectiveList: QueryList<MyDirective>;

  ngAfterViewInit() {
    this.myDirectiveList.forEach(myDirective => {
      console.log(myDirective.elementRef)
      console.log(myDirective.routerLink)
      console.log(myDirective.someComponent)
    })
  }
}
```
See e.g. https://www.bennadel.com/blog/3087-querying-for-multiple-viewchild-directives-on-a-single-element-in-angular-2-beta-17.htm#comments_49303

## Expected behavior
It would be nice to allow reading a list of tokens in order to allow getting multiple directives / tokens of the same element simultaneously.
This would allow to write e.g. 
``` 
@ViewChildren(SomeComponent, {
  read: [RouterLink, ElementRef, SomeComponent]
}) someComponentTokens
``` 
and use it e.g. 
```
ngAfterViewInit() {
    this.someComponentTokens.forEach(tokens => {
      console.log(tokens[0]) // RouterLink
      console.log(tokens[1]) // ElementRef
      console.log(tokens[2]) // SomeComponent
    })
  }
```

Furthermore it would be nice to be able to use decorators like `@Optional()`, `@SkipSelf()`, etc. in the `read` parameter.  

## What is the motivation / use case for changing the behavior?
Sometimes one wants to query for list of elements of a certain component and also get the corresponding elementRef or other directives that are also put on that element. As soon as the list of elements is dynamic, you can't do that with template references, therefore you need to write a directive as explained above.
Moreover, this directive needs to be limited to the component you are using it in. It will still be applied to content children and all descendants.

**Comment by alexzuza** [comment]
For ViewChild you can take a look at this example
https://medium.com/@a.yurich.zuev/angular-viewchild-how-to-read-multiple-instances-cde38ef19041

**Comment by macjohnny** [comment]
@alexzuza thats an excellent solution you provide!
It would be great if this could become a feature of the angular core, don't you think so?

**Comment by vicb** [comment]
@alexzuza Your solution would not work in AOT (where the code is not evaluated).

**Comment by alexzuza** [comment]
@vicb Thanks for pointing this out. I added caveats to article. @macjohnny I would be glad to see this feature.

**Comment by zoechi** [comment]
@macjohnny Using a custom directive like you showed seems easy enough to me. 

I think extending @ViewChildren this way adds a lot f complexity for little gain. 
```
@ViewChildren(SomeComponent, {
  read: [RouterLink, ElementRef, SomeComponent]
}) someComponentTokens
````
Should it only list elements where all 3 types can be acquired, or where one of them matches?
What should be the type be for `someComponentTokens:QueryList<???>`?

**Comment by macjohnny** [comment]
@zoechi you are right, adding a directive is an easy way to implement this feature. 
however, there should be a section in the docs covering this functionality in order to make developers aware of this possibility, don't you think so?

concerning the extension of `@ViewChildren`, the use of decorators could be a solution to provide the desired metadata, e.g. something like
```
@ViewChildren(SomeComponent, {
  read: [RouterLink, ElementRef, @Optional() @Inject(SomeComponent)]
}) someComponentTokens
```

**Comment by zoechi** [comment]
@macjohnny the docs about this topic are actually quite sparse. It looks to me like there got something lost during recent updates. I'm sure there was more already. 
This would be worth a new issue about the missing docs.

As mentioned, I don't see much value of complicating the API (just my opinion though).

**Comment by macjohnny** [comment]
@zoechi @alexzuza I created a new feature request https://github.com/angular/angular/issues/18729 asking for a section in the docs covering the feature discussed here.
You may comment there too / add thumbs up if you think this would be useful for other developers.
Still keeping this issue open, maybe there are other opinions about it.

**Comment by macjohnny** [comment]
this didn't catch too much attention, so I am closing this issue.

**Comment by ghetolay** [comment]
IMO you shouldn't close that issue because what matters is if it's needed and viable and not how many comments are posted.
It's just low priority and we need to find the right API to express it.
