### ISSUE TITLE
Support finding child classes via @Query

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1828]
When writing
```js
@Query(SomeBaseClass) checkableQuery: QueryList
```

Angular should give you any directives that extend `SomeBaseClass`.

**Comment by matanlurey** [comment]
Is this even possible? I was under the impression that `@Query` did some sort of selector check. How would it know the ancestor chain?

**Comment by mhevery** [comment]
Query works on DI key, which is opaque and it dos not understand inheritance. I don't think there is an easy way to support this. Can you explain your use case?

**Comment by jelbourn** [comment]
I filed this as the behest of @rkirov, who also thought this should work.

I had wanted to have `MdInputContainer` inject a `@Query` for `MdInput`, where there is a `class MdInput` and a `class MdTextarea extends MdInput`. 

I'm doing this now using `@Parent`, so this isn't something I actually need, but I could see how it would be useful.

**Comment by mhevery** [comment]
@rkirov what is the status of this? I don't think we can easily support this.

**Comment by rkirov** [comment]
Yep, we cannot support that is dart because type objects cannot be used in instanceof checks, so we cannot write something like this in dart:

```
directiveInstance is query.requestedDirective
```

Supporting this purely for TS is not worth the extra complexity, so I am closing the issue. If it is needed we can revisit adding custom filter to query.

**Comment by zoechi** [comment]
See also #8580 where a viable workaround is explained
