### ISSUE TITLE
archive/stable/next modes for angular.io

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#18287]
With Angular v5 coming in September, we need to have a solid plan for the docs and their versioning. v4 is LTS so we must keep the docs for v4 around at an easy to find location.

After speaking with @petebacondarwin and @juleskremer here is our proposal:

- Add a "mode" feature to aio app
  - there would be three recognized modes:
    - stable (used by angular.io)
    - next (used by next.angular.io)
    - archive (used by vXX.angulario, e.g. v4.angular.io)
  - the mode feature would control four things within the app:
    - theme (colors used within the header and footer of the app, maybe more? tbd)
      - stable mode would use the current angular.io palette
      - next mode would use slightly different palette (more bright? maybe red?)
      - archive mode would use gray color palette
    -  redirection of all marketing urls to /docs in archive and next mode
       - the marketing pages are irrelevant in the next and archived mode and it's more appropriate to just redirect the visitor to the actual documentation)
       - the redirection should happen via Location service (using history.replaceState) so that we don't interfere with the critical path for TTI and don't need to maintain special firebase hosting config for various environments.
- Mode activation
  - the correct mode should be activated either as a post-build/pre-deploy time or at bootstrap time 
    - in both cases we understand the target environment
    - activating the mode during the pre-deploy time would allow us to better control robots.txt to ban crawling of next and archive app - something we don't do today.
  - for local development assume the default to be the "stable" mode
  - allow mode to be changed using query parameter for development / debugging
- Add robots.txt to all archived and the next deployments to prevent crawling of these
- Adjust the version picker to contain info about next/stable and archived versions and select the one appropriately
  - two new entries should be added to version picker: next and stable
  - all archived versions should be added to the picker as we add them
  - the currently active version should be selected in the dropdown by default
    - if the current version is also stable or next, the version number should be appended to the item in the dropdown menu
    - example dropdown menu content:
       ```
       - next
       - [stable (v4.3.2)]
       - v2
       ```

**Comment by petebacondarwin** [comment]
Looks good. Mode selection should be at deploy time but implementation of app changes should be at runtime. I think this is where you ended up.

**Comment by petebacondarwin** [comment]
I have made a start @IgorMinar in #18297

**Comment by gkalpak** [comment]
Related: #18189, #18324

**Comment by gkalpak** [comment]
Closed by #18297.
