### ISSUE TITLE
FR: Routes Group

### ISSUE THREAD

**Issue by OpsRJ** [angular/angular#18295]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## What is the motivation / use case for changing the behavior?
To help organize routes into logical groups. Each group’s route pattern is prepended to the routes or groups contained within it, and any placeholder arguments in the group pattern are ultimately made available to the nested routes:

```
const appRoutes: Routes = [
{ group: 'users/{id:[0-9]+}' childs: [
{ path: 'edit', component: UserAdmComponent },
{ path: 'delete', component: UserAdmComponent },
{ path: 'reset-password', component: UserAdmComponent },
],
{ path: 'other_path/', component: OtherComponent }
]
```

**Comment by jasonaden** [comment]
Thank you. This is a feature that currently works in the Router, as long as you look up the parameters from your parent.
