### ISSUE TITLE
ngIf fail with boolean variable on @4.3.1

### ISSUE THREAD

**Issue by MikhaelGerbet** [angular/angular#18294]
## I'm submitting a...

<pre><code>
[x ?] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When i do a simple ngIf like this on @4.3.1 : 

```
watch : {{loading}}
<app-component-spin  *ngIf="loading">
```

And when `loading` (boolean) change from true at false in my component, my child component is again visible but the output of watch : {{loading}} = watch : false .

## Expected behavior

same case on @4.2.6 works perfectly.

## Minimal reproduction of the problem with instructions

it's very strange... with plnkr, it works.... but when i up my dependencies from 4.2.6 to 4.3.1 on my project, is not works and without js error ...

https://plnkr.co/edit/imCgsFS2ixz7Wf24Kg1T

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:

@angular/cli: 1.2.3
node: 6.10.3
os: win32 x64
@angular/animations: 4.2.6/4.3.1
@angular/cli: 1.2.3
@angular/common: 4.2.6/4.3.1
@angular/compiler: 4.2.6/4.3.1
@angular/compiler-cli: 4.2.6/4.3.1
@angular/core: 4.2.6/4.3.1
@angular/forms: 4.2.6/4.3.1
@angular/http: 4.2.6/4.3.1
@angular/language-service: 4.2.6/4.3.1
@angular/platform-browser: 4.2.6/4.3.1
@angular/platform-browser-dynamic: 4.2.6/4.3.1
@angular/router: 4.2.6/4.3.1

- Platform:  Windows / Linux debian 

Others:

</code></pre>

**Comment by Toxicable** [comment]
If it works in plunkr then it's unlike an issue with the framework and more likely something else in your project that's interfering somehow.
Unless you can create a minimal reproduction then this is unactionable

**Comment by MikhaelGerbet** [comment]
Thank you, i understood when I wrote the test on plnkr. But, if works with the version @4.2.6 and not with @4.3.1, i have created the issue for people in the same case as me. I have founded the problem. It's when i import jquery like this in me component 

```import * as $ from 'jquery'```

So it's resolved and finaly, this import sintax for jquery don't work's on the last stable release. 

i recommend to import jquery in .angular-cli.json and in your component, you can declare jquery like this : 

```declare let $: any;```

I think, it's a good information the the community.

++
