### ISSUE TITLE
HttpInterceptor - Intercepting Observable value

### ISSUE THREAD

**Issue by nazarkryp** [angular/angular#18291]
Please help me to resolve the following issue.

I have TokenProvider service : getAccessToken(): Observable<AccessToken> {}
If it is necessary it obtains new token using refresh token. (e.g: if token will got expired in 1 hour).
```

intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        const result = this.tokenProvider.getAccessToken()
            .subscribe(accessToken => {
                const request = req.clone({
                    setHeaders: {
                        Authorization: `Bearer ${accessToken}`
                    }
                });
            });
        return next.handle(???);
    }
```
How can I intercept Observable<AccessToken> ???

p.s: I've noticed that people try to obtin new access token using refresh token when error 401 && 403. It seems that people do not know that refresh token has the same lifetime as refresh token. you can use refresh token to get new access token before it has been expired.

**Comment by nazarkryp** [comment]
I've found the solution for such case. Here is my interceptor source. May be usebul for somebody who is in such sitiation.


`
import { Injectable, Injector } from '@angular/core';
import { HttpEvent, HttpInterceptor, HttpHandler, HttpRequest } from '@angular/common/http';
import { Observable } from 'rxjs/Rx';

import { TokenProvider } from './token-provider';
import { AccessToken } from '../../common/models';

import { environment } from '../../../environments/environment';

@Injectable()
export class AuthenticationInterceptor implements HttpInterceptor {
    constructor(
        private injector: Injector) { }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        if (req.url.includes('/authorize')) {
            return next.handle(req);
        }

        const tokenProvider = this.injector.get(TokenProvider);

        return tokenProvider.getAccessToken()
            .flatMap<AccessToken, HttpEvent<any>>((accessToken) => {
                if (!accessToken) {
                    return next.handle(req);
                }

                const request = req.clone({
                    setHeaders: {
                        Authorization: `Bearer ${accessToken.accessToken}`
                    }
                });

                return next.handle(request);
            });
    }
}

`

**Comment by vaibhav-jain** [comment]
@nazarkryp I'm trying to create a HTTP Interceptor but getting errors.

```
ERROR in C:/Users/v930427/workspace/dragoonapp/src/app/app.module.ts (5,9): Module '"C:/Users/v930427/workspace/dragoonapp/node_modules/@angular/http/http"' has no exported member 'HTTP_INTERCEPTORS'.

ERROR in C:/Users/v930427/workspace/dragoonapp/src/app/interceptors/401.interceptor.ts (2,9): Module '"C:/Users/v930427/workspace/dragoonapp/node_modules/@angular/http/http"' has no exported member 'HttpEvent'.

ERROR in C:/Users/v930427/workspace/dragoonapp/src/app/interceptors/401.interceptor.ts (2,20): Module '"C:/Users/v930427/workspace/dragoonapp/node_modules/@angular/http/http"' has no exported member 'HttpInterceptor'.

ERROR in C:/Users/v930427/workspace/dragoonapp/src/app/interceptors/401.interceptor.ts (2,37): Module '"C:/Users/v930427/workspace/dragoonapp/node_modules/@angular/http/http"' has no exported member 'HttpHandler'.

ERROR in C:/Users/v930427/workspace/dragoonapp/src/app/interceptors/401.interceptor.ts (2,50): Module '"C:/Users/v930427/workspace/dragoonapp/node_modules/@angular/http/http"' has no exported member 'HttpRequest'.

ERROR in C:/Users/v930427/workspace/dragoonapp/src/app/interceptors/401.interceptor.ts (6,56): Cannot find name 'Observable'.

ERROR in C:/Users/v930427/workspace/dragoonapp/src/app/app.module.ts (5,9): Module '"C:/Users/v930427/workspace/dragoonapp/node_modules/@angular/http/http"' has no exported member 'HTTP_INTERCEPTORS'.
```

Can someone please help??
