### ISSUE TITLE
@angular/common/http: Issue with OpenID Authorization Flow

### ISSUE THREAD

**Issue by MovGP0** [angular/angular#18299]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Given I have the following code: 
```typescript
        const headers = new HttpHeaders()
            .set("Authorization", "Bearer " + this.oAuthService.getAccessToken());

        this.httpClient
            .get<string>("https://localhost:7001/ping", { headers: headers })
            .subscribe(text => this.handleResponse(text), error => console.error(error));
```
When starting the authentication, the client first sends the following request
```http
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8,de;q=0.6,de-AT;q=0.4
Access-Control-Request-Headers:authorization
Access-Control-Request-Method:GET
Connection:keep-alive
Host:localhost:7001
Origin:https://localhost:6001
Referer:https://localhost:6001/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
```
The server happily replies with the proper 204 status code and without content: 
```http
Access-Control-Allow-Headers:authorization
Access-Control-Allow-Origin:https://localhost:6001
Date:Sun, 23 Jul 2017 09:07:35 GMT
Server:Kestrel
```
After that a second request is done, this time with the proper authentication: 
```http
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8,de;q=0.6,de-AT;q=0.4
Authorization:Bearer <BEARER TOKEN>
Connection:keep-alive
Host:localhost:7001
Origin:https://localhost:6001
Referer:https://localhost:6001/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
```
The response has now status code 200 and the following Headers:
```http
Access-Control-Allow-Origin:https://localhost:6001
Content-Type:text/plain; charset=utf-8
Date:Sun, 23 Jul 2017 09:27:27 GMT
Server:Kestrel
Transfer-Encoding:chunked
X-Robots-Tag:noindex, nofollow
```
and the following content: 
```http
pong
```

Unfortunately, the `text` in the above code example is now `null`, since it apparently sets the response from the first response instead of the second one. 

## Expected behavior
The behavior should match the old HTTP client, which implements this flow correctly. 
```typescript 
        const headers = new Headers()
        headers.set("Authorization", "Bearer " + this.oAuthService.getAccessToken());

        const options = new RequestOptions({ headers: headers });
        this.http
            .get("https://localhost:7001/ping", options)
            .subscribe(result => this.handleResponse(result.text()), error => console.error(error))
```
This client also makes two requests (exactly as the new client), but returns the content from the second response, such that the text is correctly set to `pong`. 

## What is the motivation / use case for changing the behavior?

* OpenID Connect Flows should be supported 
* I consider this a bug, since the old client perfectly works in this scenario

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [X] Chrome (desktop) version 59.0.3071.115
- [?] Chrome (Android) version XX [not tested]
- [?] Chrome (iOS) version XX [not tested]
- [X] Firefox version 54.0.1
- [?] Safari (desktop) version XX [not tested]
- [?] Safari (iOS) version XX [not tested]
- [X] IE version 11.483.15063.0
- [X] Edge version 40.15063.0.0
 
For Tooling issues:
- Node version: v6.4.0
- Platform:  Windows (Mac, Linux)

Others:
- Webserver is Kestrel/ASP.NET Core

**Comment by trotyl** [comment]
The cause you suspected is impossible, there's no way to obtain the response of pre-flight request by XHR or Fetch.

Please provide a minimal reproduction for that problem.

**Comment by MovGP0** [comment]
@trotyl unfortunately, my JavaScript skills are not sufficient to provide a reproduction of this issue. I also have hard time constraints on my current project and can't invest too much time in it.

**Comment by alxhub** [comment]
@MovGP0 the first request is the CORS preflight OPTIONS request, and it has no response body. The second request is the real request and is the only one that `HttpClient` knows about (CORS preflight requests are invisible on the web).

Based on your example, I suspect what's happening is that `HttpClient` is assuming your response is JSON, trying to parse it, and failing (hence the `null`). I'm not sure why this doesn't throw an error. The fact that you use `.get<string>` supports this.


In any case, you need to do something like this instead:

```javascript
this.httpClient
            .get("https://localhost:7001/ping", { headers: headers, responseType: 'text' })
            .subscribe(text => this.handleResponse(text), error => console.error(error));
```

There's no need for `<string>` since `responseType: 'text'` implies that the resulting body type will be `string`.

Let me know if this works, and please re-open the issue if it doesn't.

**Comment by MovGP0** [comment]
setting the `responseType` to `text` indeed solved the problem. I guess the HttpClient should return an error  when the returned IANA media type doesn't match the expected one.

**Comment by alxhub** [comment]
Unfortunately we can't rely on the server returning the correct type. Plenty of valid JSON APIs return `Content-Type: text/plain` :(
