### ISSUE TITLE
httpClient interceptors and AOT

### ISSUE THREAD

**Issue by stonecourier** [angular/angular#18293]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Using Angular 4.3.1 and angular cli 1.2.1 and following guidelines from angular site. We added authorization headers and timings for our services using interceptors. This all works fine. However when we compile for AOT, none of the interceptors run anymore.

## Expected behavior
Interceptors run when using AOT.

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [ X] Chrome (desktop) version  59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by stonecourier** [comment]
Updated a library and it works now.

**Comment by sarahgoldman** [comment]
@stonecourier What library did you update? I'm having the same issue.

**Comment by rkrupinski** [comment]
@stonecourier ☝️
