### ISSUE TITLE
Cannot find EventEmitter in angular2/angular2 in typescript component

### ISSUE THREAD

**Issue by andresdominguez** [angular/angular#1829]
I am trying to use the `EventEmitter` in a Typescript component. I am following the instructions from the website:

```shell
$ npm install -g tsd
$ tsd query angular2 --action install
$ touch app.ts
$ npm install -g typescript@^1.5.0-beta
$ tsc --watch -m commonjs -t es5 --emitDecoratorMetadata app.ts
```

Now add the following lines to app.ts:

```javascript
/// <reference path="typings/angular2/angular2.d.ts" />
import {EventEmitter} from 'angular2/angular2';
```

Expected:
It should compile.

Actual:
```shell
app.ts(2,9): error TS2305: Module '"angular2/angular2"' has no exported member 'EventEmitter'.
message TS6042: Compilation complete. Watching for file changes.
```

**Comment by 0Decoherence** [comment]
How is this a bug? its only because the type script typings are not complete. in 'angular2/angular2' only  bootstrap,Component,View,For,If,NonBindable,Switch , there is no EventEmitter but you can add it yourself for now until the full typescript typings are released.

**Comment by rkirov** [comment]
The current set of typings on tsd are incomplete. With https://github.com/angular/angular/commit/f6eeb9aa668010fe757173426a7e650c934ef346 we are on the right track to have auto-gen'ed complete typings.
