### ISSUE TITLE
`NgClass` asking on form control status throws exception `value is changed after it was checked`

### ISSUE THREAD

**Issue by brachi-wernick** [angular/angular#18298]
## I'm submitting a...
<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
when I have a form control with validation directive that get an *input* and this input may  be *changed* and affect on its validity.
If I have an `ngClass` directive that asks on the form control validity. I get an exception `value is changed after it was checked`, when my control become invalid because changing its inputs.

## Expected behavior
class should be added without getting exception.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/sE2FQDajDrZhs5Xl3RRk?p=preview

In this example I have 2 form controls: name and length.
length defined the max allowed length of the name.
steps to reproduce:
1. enter a name-> for example "abc"
the name control is valid in this step.
2. enter a length=> for example 1
now the name control becomes invalid.

I want to get the class 'invalid' on the `div` wrapping the name control. but I get an exception:
`value is changed after it was checked`

the issue is because this directive usage: ` [ngClass]="{'invalid': !formGroup.controls.name.valid}"`
if I write this way I don't get an exception:
 [class.invalid]="!formGroup.controls.name.valid"

## Environment

<pre><code>
Angular version: 4.3.1
regression from angular 4. works finally in latest angular2 version: 2.4.10

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by zoechi** [comment]
Seems the status is updated by change detection and Angular doesn't like when change detection causes updates to the model. 

A workaround https://plnkr.co/edit/XIuk9YoT5mV16RmzvlHo?p=preview
