### ISSUE TITLE
Angular Router cuts off URL at &

### ISSUE THREAD

**Issue by buu700** [angular/angular#18292]
## I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
```

## Current behavior

I'm not sure of the exact version when this started happening, but it's come to my attention that `router.routerState.snapshot.root.firstChild.url` now no longer includes anything after `&`, e.g. the path `/#foo&bar`[1] will show up as just `foo`.

I'm pretty sure this change is from a version post-4.0, but not 100% sure. In either case, I don't see any mention of this change in the changelog, so if not a bug it's at least an undocumented breaking change.

1: I've only tested with hash-based routing, so it's possible that this is a hash-based-routing-specific bug.

## Expected behavior

Route URL should be `foo&bar`.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/utNwwV0iP4yjx2WVugIo?p=preview

The URL fragment is set to `foo&bar` on line 22 of app.ts

## What is the motivation / use case for changing the behavior?

Correctness.

## Environment

```
Angular version: 4.3.1 and 4.2.4

Browser:
- [x] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
```

Edit: Sorry, was in a rush and forgot to add all the usual required information. Thanks for the reminder @trotyl.

**Comment by trotyl** [comment]
In hash mode, **you're not supposed to manipulate the fragment by yourself**, instead let the `Router` decide how to deal with it:

```typescript
router.navigate(['/foo&bar'])
//...
activatedRoute.snapshot.children[0].params['test']
```

This way it would works fine, which can be found in [Plunker here](https://plnkr.co/edit/CrV7msO02H3ygu6Abxyz?p=preview).

Angular has its own mechanism to mimic the URL by fragment, such as escaping the reserved chars, so it would leads to unexpected behavior when you fail to follow the same way.

**Comment by buu700** [comment]
Thanks, I'm aware of that, and that's how I originally wrote the Plunkr. I changed it specifically to avoid that conversion, which isn't how it behaves when handling a user-entered URL.

**Comment by atscott** [comment]
Hmm, this appears to be working as expected in v9: https://stackblitz.com/edit/angular-ivy-4ei924?file=src%2Fapp%2Fapp.ts

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
