### ISSUE TITLE
type definition of UrlMatcher should allow to return null

### ISSUE THREAD

**Issue by adwd** [angular/angular#18303]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

type definition of `UrlMatcher` is not allow to return null.

## Expected behavior

type definition of `UrlMatcher` is allow to return null.
According to docs and tests, I think `UrlMatcher` should be defined to return null like:

```ts
// angular/packages/router/src/config.ts

export declare type UrlMatcher = (segments: UrlSegment[], group: UrlSegmentGroup, route: Route) => UrlMatchResult | null;

// or

export type UrlMatchResult = {
  consumed: UrlSegment[]; posParams?: {[name: string]: UrlSegment};
} | null;
```

doc and test that `UrlMatcher` returns null:
doc: https://angular.io/api/router/UrlMatcher

```ts
function htmlFiles(url: UrlSegment[]) {
 return url.length === 1 && url[0].path.endsWith('.html') ? ({consumed: url}) : null;
}

const routes = [{ matcher: htmlFiles, component: HtmlCmp }];
```

test: https://github.com/angular/angular/blob/5d4b36f80f295455f4250c4257462b22ce6b3372/packages/router/test/apply_redirects.spec.ts#L586-L602
this test using `as any` cast, so it runs even its `matcher` function returns null.

```ts
const matcher = (s: any, g: any, r: any) => {
  if (s[0].path === 'a') {
    return {consumed: s.slice(0, 2), posParams: {id: s[1]}};
  } else {
    return null;
  }
};

checkRedirect(
    [{
      matcher: matcher,
      component: ComponentA,
      children: [{path: 'b', component: ComponentB}]
    }] as any,
    '/a/1/b', (t: UrlTree) => { expectTreeToBe(t, 'a/1/b'); });
```

## Minimal reproduction of the problem with instructions

I created a plunker, but `typescriptOptions.strict: true` doesn't work. see `app/app-routing.module.ts`
https://plnkr.co/edit/D1H6V8tkBbDXaPmi0SBf

## What is the motivation / use case for changing the behavior?

When I create custom URL matcher with `UrlMatcher`, I have to cast to any that like: 

```ts
function htmlFiles(url: UrlSegment[]) {
 return url.length === 1 && url[0].path.endsWith('.html') ? ({consumed: url}) : null;
}

const routes = [{ matcher: htmlFiles as any, component: HtmlCmp }];
```

without casting, following error occurs 

```
ERROR in path/to/app/app.routes.ts (11,7): Type '({ path: string; redirectTo: string; pathMatch: string; } | { matcher: (url: UrlSegment[]) => { c...' is not assignable to type 'Route[]'.
  Type '{ path: string; redirectTo: string; pathMatch: string; } | { matcher: (url: UrlSegment[]) => { co...' is not assignable to type 'Route'.
    Type '{ matcher: (url: UrlSegment[]) => { consumed: UrlSegment[]; } | null; loadChildren: string; }' is not assignable to type 'Route'.
      Types of property 'matcher' are incompatible.
        Type '(url: UrlSegment[]) => { consumed: UrlSegment[]; } | null' is not assignable to type 'UrlMatcher | undefined'.
          Type '(url: UrlSegment[]) => { consumed: UrlSegment[]; } | null' is not assignable to type 'UrlMatcher'.
            Type '{ consumed: UrlSegment[]; } | null' is not assignable to type 'UrlMatchResult'.
              Type 'null' is not assignable to type 'UrlMatchResult'.
```

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version 59.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v7.10.1  
- Platform: Mac 

Others:

</code></pre>

**Comment by Eyas** [comment]
Is there a reason why this bug was closed? Seems to still be present. Either `UrlMatchResult` should include `null` or `UrlMatcher` return type should include `null`. Am I missing something here?

**Comment by PapaNappa** [comment]
@alxhub can you re-open this issue, please? Or @adwd can you please explain why you closed this issue?

My workaround is to `return null as any;` in the UrlMatcher.
