### ISSUE TITLE
Click method of button added using element Ref dosent work?

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular#18304]
Component

```
 @ViewChild('div') div;
  hello:string = "";
  clickMe(){
   this.msg = "Hello";
  }
  ngAfterViewInit(){
    this.div.nativeElement.innerHTML ="<button (click)='clickMe()'>Click</button><br><p>{{hello}}</p>";
  }
```
Template

`<div #div></div>`

The click method is never fired and also the interpolation in inner html dosent work , tried to force change detection using ngZone to no effect

**Comment by zoechi** [comment]
That's not intended to work. `(click)="..."` or any Angular-specific markup is processed at build time. If you add them at runtime, they have no effect (are added to the DOM as-is but otherwise entirely ignored by Angular)

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
