### ISSUE TITLE
Dynamically created modules importing feature modules having declarations doesn't work

### ISSUE THREAD

**Issue by knkevinlai** [angular/angular#18301]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

1. If dynamically created module (which has dynamically components declared) imports other feature module(s) (which has declarations of other components),
2. then the component factories of the dynamic module compiled by Compiler.compileModuleAndAllComponentsAsync(), will be rendered incorrectly via ViewContainerRef.createComponent(), i.e. the dynamically created component is not rendered, but the first declared component in the feature module will be accidentally rendered instead.

In real case, a feature module can be like MaterialModule in angular-mdc/web

## Expected behavior

- Dynamic component declared in dynamic module should be rendered by ViewContainerRef.createComponent()
- Declared component in feature module should not be rendered

So dynamic module can import feature module (e.g. MaterialModule), and dynamic component's template can use components declared in the feature module.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/SJTXz8DsFp14AhQN6URA?p=preview

Try comment out the exports and declarations of FeatureModule in src/static.ts (line 26, 27) to disable the issue and see the difference

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.2.0
- Platform:  Windows 7

Others:

</code></pre>

**Comment by alexzuza** [comment]
Compiler compiles all components from `ngModule.transitiveModule.modules` modules and collects them in `componentFactories`. If you use `componentFactories[0]` you must be sure that your loading component will be at the first place. I would use something else for that, for example
injector 

`{ provide: LAZY_ENTRY_TOKEN, useValue: LazyComponent }`

or static property
```

export class LazyModule {
 entryComponents = { comp1: LazyComponent1, comp2: LazyComponent2 }
```

**Comment by knkevinlai** [comment]
@alexzuza It works! thanks a lot. I overlook the possibility of selecting an incorrect componentFactory.

I confirm that it is not a bug, and the issue is due to incorrect implementation.

Issue closed.

**Comment by gopalkrish23** [comment]
@knkevinlai I too stuck with the same issue could you please help in this. how did you get solution from 'componentFactories[0]' this?

share a sample code.
