### ISSUE TITLE
i18n translation with nested HTML tags

### ISSUE THREAD

**Issue by lvalladares** [angular/angular#18302]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When i try to generate translation file of a HTML nested tags it change the internal tags with some weird other tags, example: 

This in my html file:

```
<p i18n="instagram-widget.instagram|Instagram name in the foot gallery @@instagramInstagramWidget"
  class="text-muted text-center">
  <i class="fa fa-instagram fa-lg mx-1" aria-hidden="true"></i> 
  Instagram
</p>
```

appears like this in my xlf file after generating it:

`<x id="START_ITALIC_TEXT" ctype="x-i"/><x id="CLOSE_ITALIC_TEXT" ctype="x-i"/> Instagram`

The problem happens when i deploy the app using that messages in angular AOT the nested HTML (in this case a font awesome icon) dissappears, this means all the START_ITALIC_TEXT tag is absolutely ignored

## Expected behavior

The internal HTML tags should remain untouched as static text, or at least be substituted as a wildcard like some kind of variable.

## Minimal reproduction of the problem with instructions

- Create an HTML element with some nested HTML element and try to i18n first one, for example:
`<p i18n> This is a <small>example</small></p>`
- Generate the localization file using `./node_modules/.bin/ng-xi18n --i18nFormat xlf`
- See how the message is stored in the localization file

## What is the motivation / use case for changing the behavior?

I think this is a fairly common use case when you want to translate a text with some `<small>`, `<a>`
 or `<strong>` tags, also covers the case of using font awesome icons

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version 59
- [X] Firefox version 54
 
For Tooling issues:
- Node version: 6.11.1  
- Platform:  Linux

Others:

Angular cli: 1.1.0
</code></pre>

**Comment by vicb** [comment]
The "some weird other tags" are placeholders. 
The replace original tags in the messages so that translators can not change the content of the tags.
They are replaced by the original content when the app is translated.

**Comment by lvalladares** [comment]
@vicb thats the problem, the placeholders doesnt get replaced as i said above.

Afther compiling my app ussing any of the messages files the font awesome icon inside the italics is missing
