### ISSUE TITLE
Angular 4 ngComponentOutlet loads dynamic components, but route content is not being injected

### ISSUE THREAD

**Issue by tomschreck** [angular/angular#18309]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm using ngComponentOutlet directive to dynamically load different components.  Each component loaded in this manner have ng-content areas where content can be injected.  I'm able to successfully load different components based on widths of device, however, route content targeting the ng-content areas are not getting loaded.  

According to documentation, ngComponentOutlet can target optional list of projectable nodes to insert into the content (ng-content) placeholders.  I was able to do this and inject 'static' text nodes into the ng-content areas in each component swapped  out via ngComponentOutlet.  However, I cannot get route content to be injected.

## Expected behavior
My objective is to have a page wrapper component to handle responsive needs like different navigation elements for small/medium/large responsive designs.  My expectation is to be able to inject route content into different ng-content areas in the different 'parent' component dynamically injected based on device widths.

## Minimal reproduction of the problem with instructions
I've created a plunkr that demonstrates this issue:

https://plnkr.co/edit/hOwRX1Ml6gX0S8em6nd5?p=preview

This plunkr has 2 routes (pages 1, & 2).  Route 1 uses `page-wrapper` component which dynamically loads a component based on device width.  I've  added the ability to load 'static' content for route 1 to demonstrate that content can get loaded into the ng-content areas for each component loaded dynamically.

Route 2 uses `page-wrapper-not-responsive` component demonstrating content from page-two-component gets injected into the correct ng-content in parent component.

## _Problem Statement_

why does static content in page-wrapper component gets injected into ng-content placeholders in small/medium/large components yet route content from Page 1 does not?

--

## What is the motivation / use case for changing the behavior?
The motivation is to seamlessly handle responsive navigation needs.  `page-wrapper` component should handle different navigation implementations based on device widths.  I think swapping out parent components based on device widths is a clean way to accomplish this.  I'm very close, I think, to getting this to work.  I just cannot figure out how to inject route content into the appropriate parent component's  ng-content when parent component is dynamically loaded based on device width.  Yet, 'static' content does get injected.  How do you inject route content?

## Environment

<pre><code>
Angular version: 
@angular/cli: 1.0.1
@angular/core: 4.0.3

Browser:
- [X] Chrome (desktop) Version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v7.7.1
- Platform:  Windows

Others:

</code></pre>

**Comment by bob-lee** [comment]
@tomschreck your plunker link seems to be broken..

**Comment by tomschreck** [comment]
@bob-lee - i updated post with URL.  here it is again:  https://plnkr.co/edit/hOwRX1Ml6gX0S8em6nd5?p=preview

**Comment by tomschreck** [comment]
I received an answer on Stackoverflow.  Thanks for your help.  Here's a link to the post:

`https://stackoverflow.com/a/45305076/418549`

**Comment by jasonaden** [comment]
Closing based on above comment.
