### ISSUE TITLE
Does the order in single typescript file matter?

### ISSUE THREAD

**Issue by 0Decoherence** [angular/angular#1830]
In a single typescript file this throws TypeError: Cannot read property 'annotations' of undefined
```typescript
/// <reference path="typings/angular2/angular2.d.ts" />
import {bootstrap, Component, View} from 'angular2/angular2';

@Component({selector:"app"})
@View({template:`<c1></c1><c2></c2>`, directives:[C1,C2]})
class App{}

@Component({selector:"c2"})
@View({template:'i am c2 <br>'})
class C2{}

@Component({selector:"c1"})
@View({template:`i am c1 <br>`})
class C1{}

bootstrap(App);
```
if i define the components before the app such as
```typescript
/// <reference path="typings/angular2/angular2.d.ts" />
import {bootstrap, Component, View} from 'angular2/angular2';

@Component({selector:"c2"})
@View({template:'i am c2 <br>'})
class C2{}

@Component({selector:"c1"})
@View({template:`i am c1 <br>`})
class C1{}

@Component({selector:"app"})
@View({template:`<c1></c1><c2></c2>`, directives:[C1,C2]})
class App{}

bootstrap(App);
```
it works fine.

is this a normal behavior, does the order really matter?

**Comment by pkozlowski-opensource** [comment]
This is more of a TypeScript questions than angular question, but if put this TS code in the [TS playground](http://www.typescriptlang.org/Playground):

```javascript
var baz = [Foo, Bar];

console.log(baz);

class Foo { }
class Bar {}
```

you will see that it is going to be transpiled to:

```javascript
var baz = [Foo, Bar];
console.log(baz);
var Foo = (function () {
    function Foo() {
    }
    return Foo;
})();
var Bar = (function () {
    function Bar() {
    }
    return Bar;
})();
```

and with JS variable hoisting you will get Foo and Bar being undefined at the place of usage. So yes, the order does seem to matter. Feel free to take it with https://github.com/Microsoft/TypeScript if you believe things should be improved on the language level.
