### ISSUE TITLE
ng build --prod fails since today

### ISSUE THREAD

**Issue by BorntraegerMarc** [angular/angular#18313]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Steps:
1. `ng new package-test`
1. `cd .\package-test\`
1. `npm i`
1. `ng build --prod`

then the following output comes out:
```
PS D:\projects\package-test> ng build --prod
Hash: 810afd91f5a111eb79cb
Time: 7641ms
chunk    {0} polyfills.1553fdd8173a081c720c.bundle.js (polyfills) 177 kB {4} [initial] [rendered]
chunk    {1} main.c22b61509cde9fcee2d3.bundle.js (main) 1.1 kB {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.f7457d5ac1e9743fd76f.bundle.js (vendor) 849 kB [initial] [rendered]
chunk    {4} inline.3a7e7a530cd68edb2099.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\projects\package-test\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
```

Happens roughly since today noon UTC +1

## Expected behavior

Production build runs through

## Environment

<pre><code>
Angular version: 4.3.1
CLI version: 1.2.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.9.1 
- Platform: Windows 10 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular-cli/issues/7113. Also this repo is for angular, not angular-cli 👍

**Comment by BorntraegerMarc** [comment]
Thanks a lot :)
