### ISSUE TITLE
unable to set HTTP header authorization

### ISSUE THREAD

**Issue by imtiaz-emu** [angular/angular#18319]
I'm creating a HTTP request with header. But the header doesn't added to the request. 
I'm using a service: **ProjectService** 
```
..... # skip codes
getProjects(): Observable<any> {
    let url = API.MAIN_URL + '/api/project/';
    return this.http.get(url, this.requestHeaders())
      .map(this.extractData)
      .catch(this.handleErrorObservable);
  }

..... # skip codes
requestHeaders(): any {
    let headers = new Headers();
    headers.append('Access-Control-Allow-Origin', '*');
    headers.append('Authorization', 'token ' + localStorage.getItem('token'));
    let options = new RequestOptions({headers: headers});
    return options;
  }
```
Then in my **ProjectComponent** I created an object of that service to call the `getProjects()` method. with some header setting. 
```
ngOnInit() {

    this._projectService.getProjects().subscribe(data => {
        this.projects = data;
      },
      error => this.message = this.errorMessage(error._body));

  } 
```
In my browsers console  I saw that in the request my header is overidden. Thus the `authorization` is not included. That's why it gives me error from server that authorization credentials are not provided. And in header it doesn't contains the `authorization` hash. [Error details here](http://imgur.com/a/EMfQl).
I've posted a question on [StackOverflow](https://stackoverflow.com/questions/45278365/angular2-unable-to-set-http-header-authorization/45282271#45282271) .

**Comment by mhevery** [comment]
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Comment by christianbs** [comment]
i have the same problem with angular 5.0... is there some way to solve that locally?

**Comment by imtiaz-emu** [comment]
@christianbs Did you checked the [stackoverflow](https://stackoverflow.com/questions/45278365/angular2-unable-to-set-http-header-authorization/45282271#45282271) link?

**Comment by christianbs** [comment]
i tried, man, but i still with the problem... that's how i created my headers:

const headers = new Headers({ 'authorization': 'Basic #myhash' });
const options = new RequestOptions({ withCredentials: true, headers: headers });
this.http.post(url, options).map(response => response.json());

Did I do something wrong?
