### ISSUE TITLE
Broken link in Browser Support guide

### ISSUE THREAD

**Issue by ben-coble-sp** [angular/angular#18312]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

On [the browser support page](https://angular.io/guide/browser-support#optional-browser-features-to-polyfill) the Http entry for optional browser features has a broken link. Maybe the Http-Client addition modified some routes and caused this to break?

## Expected behavior

The Http entry for browser features that can be polyfilled should have a correct API reference/guide.

## Minimal reproduction of the problem with instructions

Go to https://angular.io/guide/browser-support#optional-browser-features-to-polyfill and look at the last entry in the table.

## What is the motivation / use case for changing the behavior?

Accurate docs.

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
n/a

Others:

</code></pre>
n/a

**Comment by gkalpak** [comment]
@petebacondarwin, any idea why dgeni doesn't complain?

**Comment by gkalpak** [comment]
Hm...it turns out the link is valid (and in fact the same link works in other places, but it is not converted to an actual anchor tag in this case 😕
