### ISSUE TITLE
elements do not render to the DOM following a `ng-container`

### ISSUE THREAD

**Issue by sgbrown** [angular/angular#18314]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

elements following an ng-container element within a component with an attribute selector do not render to the DOM

## Expected behavior

all elements in the component template should render to the dom

## Minimal reproduction of the problem with instructions

    @Component({
      selector: '[table-body-component]',
      template: `
        <ng-container>
          <tr>
            <td>{{datum.row1}}</td>
          </tr>
          <tr>
            <td>{{datum.row2}}</td>
          </tr>
        </ng-container>
        <tr>
          <td>missing row</td>
        </tr>
      `,
      styles: ['table, tr, td, th {border: 1px solid black} table {border-collapse: collapse}']
     })
     export class TableBodyComponent {
        @Input('table-body-component')
        datum;
      }

https://plnkr.co/edit/80vrf7BEWfi2h1y0ykts?p=preview

In the aforementioned plunker, the tr element with content of 'missing row' does not get rendered in the template for TableBodyComponent.  If you were to not wrap any of the content in a ng-content element, all of the rows would show appropriately.

## What is the motivation / use case for changing the behavior?

I have a use case where there is some complicated logic for tr elements that use varying colspan and rowspan which I want to keep separated into it's own component to keep the code clean and readable and also necessitates the use of ng-container elements to handle the complexity of logic.  

In my use case there actually end up being multiple tbody elements in the table that are repeated using the NgForOf directive.  For this use case to work, I need to use an attribute selector for the component representing the contents of the tbody so that the parent element of the tr elements is the tbody. Since, the only permitted parents of tr are table, tbody, thead and tfoot (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr), having an element that is the name of the component selector as the tag for the parent element is not an option.

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version 56.0.2924.76 (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 52.2.0 (32-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11.0.9600.18738CO
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Seems to be compiler-related, the last `<tr>` never exists in the View Definition:

![image](https://user-images.githubusercontent.com/6059170/28556452-152c6d2c-7139-11e7-93ff-c8e42a57cb64.png)

Made a minimal reproduction in [plunker here](https://plnkr.co/edit/2i5SVAjJFWgN77p9sedD?p=preview), the problem is not relevant to attribute selector.

This may be a parser bug, the wrong result can be observed in the [`Parser#build()`](https://github.com/angular/angular/blob/master/packages/compiler/src/ml_parser/parser.ts#L61) method: 

![image](https://user-images.githubusercontent.com/6059170/28557016-a058c604-713c-11e7-8a2a-b5093ff20341.png)
