### ISSUE TITLE
Model not updating in the template until `detectChanges()` is called

### ISSUE THREAD

**Issue by marknorgate-tengroup** [angular/angular#18320]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
I am working with Angular 4.2.4 and have run into a problem inasmuch as changes to the model in my component class are not being reflected in the view until I manually call `changeDetectorRef.detectChanges()`. The code is not doing anything out of the ordinary, and I have shown this code to a few people and they can't work out why it's not working either. For these reasons, I suspect this may well be a bug.

There are no components in the application using the `OnPush` change detection strategy.

The code of my component looks like this:

<pre><code>
import { ChangeDetectorRef, Component, Inject, OnDestroy, OnInit } from '@angular/core';
import { NavigationService } from '../../services/index';
import { Subscription } from 'rxjs';
import { DiningService } from '../../services/dining.service';

@Component( {
  selector: 'dining',
  templateUrl: './dining.template.html',
} )

export class DiningComponent implements OnInit, OnDestroy {

  moduleName: string = 'Dining';
  headerImage: string = '../../../../assets/images/module_header/dining.jpg';
  introText: string = 'Some introduction text here about Dining module';
  isParentActive: boolean;
  preference: string;
  hotTablesOnly: boolean = false;
  memberBenefitsOnly: boolean = false;
  private route$: Subscription;
  private PAGE_ROUTE: string = 'dining';
  private searchResults: Array<any> = [];
  private currentPage: 1;
  private totalResultsCount: number;
  private isLastPage: boolean;
  private isLoading: boolean = false;

  constructor( @Inject( 'NavigationService' ) private navigationService: NavigationService,
               private changeDetectorRef: ChangeDetectorRef,
               private diningService: DiningService ) {
  }

  public ngOnInit() {
    this.isParentActive = this.navigationService.isParentActive( this.PAGE_ROUTE );

    this.route$ = this.navigationService
                      .getRouterEvents()
                      .subscribe( ( route ) => {
                        this.isParentActive = this.navigationService.isParentActive( this.PAGE_ROUTE, route.url );
                      } );
  }

  public ngOnDestroy() {
    this.route$.unsubscribe();
  }

  protected onSelectDiningPreference( preference ) {
    this.currentPage = 1;
    this.preference = preference;
    this.searchResults = [];
    this.totalResultsCount = 0;
    this.loadNextPage();
  }

  protected loadNextPage() {
    this.isLoading = true;
    this.changeDetectorRef.detectChanges();

    this.diningService.pagedResults$( this.preference, this.currentPage++, {
      memberBenefitsOnly: this.memberBenefitsOnly,
      hotTablesOnly: this.hotTablesOnly
    } )
        .subscribe( ( searchResults ) => {
          this.searchResults = [ ...this.searchResults, ...searchResults.results ];
          this.totalResultsCount = searchResults.totalResultsCounts;
          this.isLastPage = searchResults.isLastPage;
          this.isLoading = false;
        } );
  }

  protected onLoadMoreClicked() {
    this.loadNextPage();
  }

  protected onHotTablesChecked( hotTablesChecked ) {
    this.hotTablesOnly = hotTablesChecked;
    this.onSelectDiningPreference( this.preference );
  }

  protected onMemberBenefitsChecked( memberBenefitsChecked ) {
    this.memberBenefitsOnly = memberBenefitsChecked;
    this.onSelectDiningPreference( this.preference );
  }
}
</code></pre>

As you can see, I am calling `this.isLoading = true` which should show an indicator in the HTML while the HTTP request is going on. Currently, the indicator does not appear until `this.changeDetectorRef.detectChanges()` is called, or we wait long enough for Angular to do the updating. If I `console.log(this.isLoading)` immediately after setting it, it has the expected value of `true`.

## Expected behavior
The expected behaviour is that the indicator should appear immediately in the HTML after `this.isLoading = true` is called, without having to manually tell Angular to detect changes by calling `this.changeDetectorRef.detectChanges()`.

## What is the motivation / use case for changing the behavior?
I should not need to call `changeDetectorRef.detectChanges()` when the model changes!

## Environment
<pre><code>
Angular version: 4.2.4

Browser:
- Chrome for Mac (desktop) version 59.0.3071.115

 
For Tooling issues:
- Node version: 6.11.0
- Platform:  Mac macOS Sierra 10.12

**Comment by marknorgate-tengroup** [comment]
I have solved the problem. It appears that some of the notifications were being sent from outside the Angular zone and Angular was therefore not able to respond immediately.

**Comment by anshulsinha1101** [comment]
> ha
Could you please help me with the solution, even i facing the same issue in angular 7
