### ISSUE TITLE
clearValidators on Control doesn't clear errors.

### ISSUE THREAD

**Issue by apurva1711** [angular/angular#18322]
I am using reactive forms in Angular 4. 

this.form.controls.code.clearValidators();

The above method only clears the validators on the form and if there are any errors previously set on the control are not cleared which results in failing validations when I put check if it has errors.

We have to do following to reset the errors so that validations are completely removed:

this.form.controls.code.setErrors(null);

Is this expected behaviour?

**Comment by kara** [comment]
The `clearValidators` function is just meant to set the validators on the control. It's up to the developer whether validation should be run. If you choose to do so, you can with:

```this.form.updateValueAndValidity()```

**Comment by Daddelbob** [comment]
Thx @kara this helped me.
Might say, that i used it on one specific control with the onlySelf option:

> this.formcontrol.updateValueAndValidity({
      onlySelf: true
    });

**Comment by kanishk30** [comment]
> Thx @kara this helped me.
> Might say, that i used it on one specific control with the onlySelf option:
> 
> > this.formcontrol.updateValueAndValidity({
> > onlySelf: true
> > });

Thanks, it works for me.
