### ISSUE TITLE
Web workers best practices

### ISSUE THREAD

**Issue by Aaron-Sterling** [angular/angular#18328]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular style guide does not include discussion of web workers

## Expected behavior

Some discussion somewhere of how to get web workers to play well with Angular (or whether it's best to avoid them).

## Minimal reproduction of the problem with instructions

All current (unofficial) examples of using web workers in Angular or Ionic projects violate the Angular style guide by putting heavy lifting inside the page, instead of placing it in a provider.

## What is the motivation / use case for changing the behavior?

When does it make sense to define a web worker inside a provider? Or is it better to avoid that, and instead to rely on reactive solutions like BehaviorSubject, so the provider emits when it is ready and the page displays an initial placeholder value in the meantime? (That's what I'm doing now.)

## Environment

<pre><code>
Angular version: X.Y.Z

I'm working in Ionic 3.x, so Angular 4.x. Asking more for general principles and guidance.

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
I also started [a thread](https://forum.ionicframework.com/t/ionic-angular-and-web-workers/99498?u=aaronsterling) on this topic at the Ionic forum.

**Comment by Dzivo** [comment]
Is there any progress on this ? We would definitly like to write our web workers in typescript instead of writing them in JS. Maybe it could be a separate bundle or something :)

**Comment by jbogarthyde** [comment]
See also  #17779,  #23730
