### ISSUE TITLE
Travis is green event if unit test fails !

### ISSUE THREAD

**Issue by vicb** [angular/angular#1832]
see https://travis-ci.org/angular/angular/jobs/62190040

**Comment by vicb** [comment]
At least error in cjs tests are not detected (there is one failure in the current master and Travis is still green)

**Comment by pkozlowski-opensource** [comment]
Seems like it started to break with 92d6aa1 (see https://travis-ci.org/angular/angular/builds/62139867) but I'm not sure how this commit could break things...

But yeh, the build should fail in this case....

**Comment by vicb** [comment]
@mhevery was this solved by your commit ?

**Comment by IgorMinar** [comment]
yeah. that commit looks right.
