### ISSUE TITLE
set base-href with index.html breaks service worker

### ISSUE THREAD

**Issue by zh99998** [angular/angular#18321]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

when base-href includes index.html, and using service worker. it breaks.
```
https://mycard.moe/mobile2/index.html/fontawesome-webfont.674f50d287a8c48dc19b.eot?ngsw-cache-bust=0.7773085530441184
Failed to load resource: the server responded with a status of 404 ()
```

## Expected behavior

it should request `https://mycard.moe/mobile2/fontawesome-webfont......`
not `https://mycard.moe/mobile2/index.html/fontawesome-webfont......`

## Minimal reproduction of the problem with instructions

```
ng build --base-href /mobile2/index.html --aot --prod
```
## What is the motivation / use case for changing the behavior?

1. some static page host service provider can't set index.html as directory index, must request index.html explicitly in url
2. even set base href to / it not works too, since generated ngsw-manifest.json not declare start as index.html by default.  / and /index.html is treated as different resource, / is not cached. **this is another problem**

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version 59
</code></pre>

**Comment by alxhub** [comment]
Hi @zh99998,

Firstly, the `base-href` should be a directory, not a file. I'm not surprised that doesn't work.

Secondly, to get `/` (and other "routes") to work for navigation instead of  `/index.html`, you need to set up a routing configuration for the service worker. See the example in Steven's routing configuration here: https://fluin.io/blog/angular-service-worker
