### ISSUE TITLE
Get access to Angular 4.1 documentation

### ISSUE THREAD

**Issue by pavlovt** [angular/angular#18324]
Hi,

I am using Angular 4.1 and Http service and tried to read the documentation (https://angular.io/docs) about it but it is not available any more (there is information only on Angular 2 and 4.3.1).
I think it is not a good idea to remove this documentation (for versions 4.1 and 4.2) - there are quite a lot of people depending on it.

**Comment by janpio** [comment]
https://angular.io/guide/http unfortunately is not usable for 4.1.x users right now because of that :( There should really be a way to get the old versions of these.

**Comment by peterkrieg** [comment]
This would be particularly useful for NativeScript-Angular users, which is currently behind the latest Angular release.  Would be very nice to select version of Angular to view docs for.

**Comment by janpio** [comment]
(Same for all Ionic users, which is almost never on latest)

**Comment by gkalpak** [comment]
For the `Http` guide specifically, the guide from the archived v2 docs should be (mostly?) the same: https://v2.angular.io/docs/ts/latest/guide/server-communication.html

**Comment by petebacondarwin** [comment]
You can view v4 docs at https://v4.angular.io/docs

**Comment by petebacondarwin** [comment]
But we are not supporting separate docs for different minor versions.
