### ISSUE TITLE
Dates on Firefox Android seem not to work

### ISSUE THREAD

**Issue by auromota** [angular/angular#18337]
I'm not sure if this is a problem related to Firefox or Angular itself, so I'm sorry if it's a Firefox problem. As I couldn't find any issue related to this, I decided to inform you so it can be better evaluated.

## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
I have a Date property in my component. When I bind it to the template using the DatePipe, it works on all devices & browsers I've tried, except for the Firefox on Android. Also the binding using `[(ngModel)]` on an input with `type=date` doesn't seem to work aswell.

## Expected behavior
Date input and binding should work on all platforms.

## Minimal reproduction of the problem with instructions
Open the demo in any device and then open it in Firefox on Android. You'll see that it doesn't even show up in the template.
http://embed.plnkr.co/nsPuuy1GvIRvHZ8GmoTo/

## What is the motivation / use case for changing the behavior?
N/A. It's a pretty basic functionality that seems not to work.

## Environment

<pre><code>
Angular version: 4.2.4

Browser:
Firefox (Android) version 54.0.1

</code></pre>

**Comment by vicb** [comment]
This is most probably related to the Intl API.

Should be solve when #18284 land.
