### ISSUE TITLE
Formatting Error in HTTP Section of Tour of Heroes Tutorial

### ISSUE THREAD

**Issue by cmkawa** [angular/angular#18336]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Information block on Tour of Heroes part 6 continues through to the end of the page. Before the "Heroes and HTTP" header, there is a div tag missing its left angle bracket.

## Expected behavior

The information block preceding "Heroes and HTTP" should terminate before the header rather than continuing through the document.

## Minimal reproduction of the problem with instructions

Access "https://angular.io/tutorial/toh-pt6" and scroll down to the "Heroes and HTTP" section.

## What is the motivation / use case for changing the behavior?

The extended div block makes the information that follows appear to be part of the "backend substitution" that users may skip.

## Environment
Google Chrome

<pre><code>
Angular docs version: 4.3.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1 
- Platform: Windows 

Others:

</code></pre>

**Comment by gkalpak** [comment]
Fixed by c6cf678a0. Works as expected on [staging][1].

[1]: https://next.angular.io/tutorial/toh-pt6
