### ISSUE TITLE
[Hidden] not working in platform-server

### ISSUE THREAD

**Issue by mahmood-sajjadi** [angular/angular#18340]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

hidden attribute is not adding in platform-server so if javascript is disabled (for example when a spider visiting web page) the element is visible but it shouldn't

## Expected behavior

when an element is marked as hidden, the element should be hidden for everyone, In platform-server and client

## Minimal reproduction of the problem with instructions

it is platform-server so it is not reproducible in plunker

create simple textbox and an error message
hide it when textbox is "pristine" or status is "VALID"
`<span [hidden]="form.controls.name.pristine || form.controls.name.status === 'VALID'>EROR should be hidden at the beginning</span>`
build for platform-server

disable javascript in chrome and visit that page

ERROR is visible!!!!

## What is the motivation / use case for changing the behavior?

SEO, serving web page for users who disabled javascript, bots, spiders, ...

## Environment

<pre><code>
Angular version: 4.1.2 to 4.3.1

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v6.11.0  
- Platform: Mac, Ubuntu 

Others:

</code></pre>

**Comment by mahmood-sajjadi** [comment]
I create a custom directive and I saw even my custom directive is not rendered correctly in platform-server, so I believe there is a problem in platform-server and directive life sycle

**Comment by mhevery** [comment]
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Comment by mahmood-sajjadi** [comment]
This issue can not be reproduced in plunker so  I create a GitHub repo so that I create a new ticket
https://github.com/angular/angular/issues/18377

hope I can help
