### ISSUE TITLE
Angular 2 Lazy Routing

### ISSUE THREAD

**Issue by JSASHU** [angular/angular#18343]
## I'm getting an error while implementing lazy routing in Angular 2

import { NgModule }      from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpModule, JsonpModule } from '@angular/http';
import { routing } from "./collections.routing";
import { FormsModule }   from '@angular/forms';
import { MetadataModule } from 'ng2-metadata';
import { CollectionsComponent } from './collections/collections.component';
import { ProductsPipe } from '../collections/pipes/vegNonVeg/vegNonVeg.pipe';
import { SelectedCategoryPipe } from '../collections/pipes/selectedCategory/selectedCategory.pipe';
import { ProductSearchPipe } from '../collections/pipes/productSearch/productSearch.pipe';
import { ProductSortPipe } from '../collections/pipes/productSort/productSort.pipe';
import { TruncatePipe } from '../collections/pipes/truncate/truncate.pipe';
import { SharedModule }       from '../main/shared.module';
import { LoginModule }       from '../login/login.module';

@NgModule({
  imports:      [ CommonModule, SharedModule, HttpModule,JsonpModule,routing, MetadataModule.forRoot(), FormsModule, LoginModule ],
  declarations: [ CollectionsComponent, ProductsPipe, SelectedCategoryPipe, ProductSearchPipe, ProductSortPipe, TruncatePipe ],
  exports:		[ CollectionsComponent, ProductsPipe, SelectedCategoryPipe, ProductSearchPipe, ProductSortPipe, TruncatePipe ]
})
export class CollectionsModule { }

collection.routing.ts

import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { CollectionsComponent } from './collections/collections.component';

const routes: Routes = [
  { path: '', component: CollectionsComponent }
];

export const routing: ModuleWithProviders = RouterModule.forChild(routes);

in main routes.ts
{ path: 'collections', loadChildren: 'app/components/collections/collections.module#CollectionsModule'
}

I am getting 

{id: 22, url: "/collections", error: Error: Component HomeComponent is not part of any NgModule or the module has not been imported into …}

please help me for this.

**Comment by mlc-mlapis** [comment]
@JSASHU ... do you think that it is a bug?

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
