### ISSUE TITLE
When i navigate from one route to another child route internally, my sidebar component doesn't work

### ISSUE THREAD

**Issue by moeidsaleem** [angular/angular#18357]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

On my login i have made a simple authenticate, which when successful will go to the dashboard route which has 
```javascript
this.http.post('/user/authenticate', loginObj)
.map((res) => res.json())
.subscribe((res)=> {
if(res.success == true){
this.router.navigate(['/dashboard']);
}else{
....
}
```
and in my dashboard controller i have something like this 
```html
<div id="wrapper" >
  <app-sidebar ></app-sidebar>
	  <div id="page-wrapper" class="gray-bg">
         <app-header></app-header>
<router-outlet></router-outlet>
</div>
</div>

```
But the main problem is that when i navigate to this route, my <b>Sidebar Component</b> doesn't render and links don't work. I have tried even ngZone on my login submission 
```javascript


```javascript
 this.zone.run(() => { this.router.navigate(['/dashboard']); });
```
But it doesn't even work, i have tried many solutions and check web, can't find the proper answer. If you know any relevance please let me know asap.

## Expected behavior

I want when i navigate internally to my dashboard route, my component should work properly and be responsive. 

## Environment
Angular 4 - latest 
Nodejs 

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by moeidsaleem** [comment]
can you please still help, ?
