### ISSUE TITLE
 URLSearchParams interface page on MDN is not found

### ISSUE THREAD

**Issue by anmary** [angular/angular#18367]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

On https://angular.io/guide/router#parammap-api, the link to the URLSearchParams interface on the MDN returns a 404 not found.

## Expected behavior

Should probably linked to https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams.

## Environment

<pre><code>

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by gkalpak** [comment]
Thx for reporting this. If you feel like submitting a PR, [this is the file][1] you would need to change :wink:

[1]: https://github.com/angular/angular/blob/master/aio/content/guide/router.md
