### ISSUE TITLE
Show key info about an element onmouseover, in https://angular.io/api

### ISSUE THREAD

**Issue by dborisog** [angular/angular#18365]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior

At the moment https://angular.io/api (high-level view of all elements) provides 3 key pieces of information: 
* parent modules, 
* names of elements, 
* types of elements.  

## Expected behavior

4 key pieces of information: 
* parent modules, 
* names of elements, 
* types of elements, and 
* __key information onmouseover__.

## Minimal reproduction of the problem with instructions

* open  https://angular.io/api
* mouse over elements

## What is the motivation / use case for changing the behavior?

For a newbie, this 4th information would speed-up selection of Angular elements and familiarisation with Angular in general.

## Environment

<pre><code>

Browser:
- [x] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
Thx the suggestion. What is the _"key information"_ information you would like to see on mouseover?

**Comment by dborisog** [comment]
@gkalpak 

I am a newbie, so I'm not familiar with the common struggles and rationale behind struggles most of the newbies face while learning Angular. At the moment I just 

I however think that meaning comes from use (hence function), and I'm fond of 4D formalism, where __function__ is delivered by __construction__ located in __space__ and changed over __time__, which allows describing a system through its life cycle.

I doubt __time__ (the change due collaboration) aspect matters here, but __function__ & __construction__ || (__construction & location__) might be rather descriptive. A list of typical tasks / problems / micro-cases this element is solution for may also be very useful.

**Comment by dborisog** [comment]
An example, using text from the docs.
https://angular.io/api/common/NgForOf

Function, explains what an element does (the meaning of an element, why it is used by developers). (copy-paste from the Description section).

Construction (and location) shows how and where to apply it. (copy-paste from the Syntax section) 

    The NgForOf directive instantiates a template once per item from an iterable.

    <li *ngFor="let item of items; index as i; trackBy: trackByFn">...</li>
    <li template="ngFor let item of items; index as i; trackBy: trackByFn">...</li>

**Comment by petebacondarwin** [comment]
I don't think it is a good idea to have all this information in a tooltip. It would be bad UX.
Moreover, it would require a much larger amount of information to be stored in the navigation.json, which must be loaded early in the app and so is size sensitive.

It is pretty easy to click on a link to an API element if it looks like it might be what you want to see the actual documentation page, then hit back if it is not.
