### ISSUE TITLE
Passing the data between parent and child components

### ISSUE THREAD

**Issue by iamsarav** [angular/angular#18368]
I'm facing an issue where passing data from **child component** --> **parent component** --> again to **another**  **child component.** its not updating all the times.

## Current scenario:

My scenario is, from a child component I have to emit a value to another sibling component.
so I am doing following things,

1. Emitting a variable from the child component.
2. catching the variable data on the parent component.
3. again emitting/passing the same data from the parent to children component.

when doing this I have to remove a class from the child component. 
this seems to be not working.

## Environment

<pre><code>
Angular version: 4.x

</code></pre>

**Comment by mlc-mlapis** [comment]
This scenario is so usual that on 99,999% it is not a bug but your mistake.

If you create a plunker to demonstrate and reproduce the problem it would be clear where the problem is. Without it, it's not possible to say anything.

**Comment by tytskyi** [comment]
@iamsarav  please provide the plunker, with minimal reproduction

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
