### ISSUE TITLE
Using a type needed by the injectable class in the injectable class leads to "Can't resolve all parameters for"

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#18371]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Uncaught Error: Can't resolve all parameters for TestComponent: (?).

It seems not to be possible to use the TestComponent type in the ServiceA, when TestComponent needs ServiceA as dependency.

## Expected behavior
It should be okay to inject the ServiceA into the TestComponent

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/6NCQaIqv92RbU7QFqRrD?p=preview

(At the moment there is an issue with resolving dependencies for App, I don't find the mistake, but the rest is like on my local environment)

https://github.com/CSchulz/di-type-error-showcase

Execute npm start and open in your browser.

## What is the motivation / use case for changing the behavior?
I would like to inject all dependencies via constructor and not using the injector instance as workaround.

## Environment
<pre><code>
Angular version: 4.2.6 and latest

Browser:
- [X] Chrome (desktop) version 59
</code></pre>

**Comment by vicb** [comment]
The injector does not support parametrized types `content: Type<AbstractComponent>` -> use `@Inject(aToken) content: Type<AbstractComponent>`

**Comment by CSchulz** [comment]
Uhm, I think there is a missunderstanding, because I call the method and it is no constructor:

```
this._serviceB.open(TestComponent);

class ServiceB {
  public open(content: Type<AbstractComponent>): void {
```

**Comment by CSchulz** [comment]
@vicb Can you please elaborate your statement? I don't get how the injector is the issue in my case.

TestComponent gets ServiceA via DI
```
constructor(private _serviceA: ServiceA) {
```

I am using the TestComponent in ServiceA.
```
this._serviceB.open(TestComponent);

class ServiceB {
  public open(content: Type<AbstractComponent>): void {
```
