### ISSUE TITLE
[Hidden] not working in platform-server

### ISSUE THREAD

**Issue by mahmood-sajjadi** [angular/angular#18377]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

hidden attribute is not adding in platform-server so if javascript is disabled (for example when a spider visiting web page) the element is visible but it shouldn't

## Expected behavior

when an element is marked as hidden, the element should be hidden for everyone, In platform-server and client

## Minimal reproduction of the problem with instructions

this issue originally raised by me https://github.com/angular/angular/issues/18340
this is a platform-server (server env) issue and cannot be reproduced in plunker.
this is a GitHub repo to reproduce: https://github.com/mahmood-sajjadi/ng-universal-demo

step to reproduce:
1) download the code and use the following commands:
`yarn`
`yarn start`

open http://localhost:8000

there is no problem because Angular is running on your browser and everything is working as expected

go to chrome dev-tool settings and disable javascript

refresh the same page (http://localhost:8000)
the folowing error is visible now:
`EROR should be hidden at the beginning`
but it should be hidden, same as the browser with javascript

## What is the motivation / use case for changing the behavior?

SEO, serving web page for users who disabled javascript, bots, spiders, ...

## Environment

<pre><code>
Angular version: 4.1.2 to 4.3.1

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v6.11.0  
- Platform: Mac, Ubuntu 

Others:

</code></pre>

**Comment by mahmood-sajjadi** [comment]
I create a custom directive and I saw even my custom directive is not rendered correctly in platform-server, so I believe there is a problem in platform-server and directive life cycle
There is no issue with custom structural directives or native structural directives like *ngIf

**Comment by gdi2290** [comment]
can you try [attr.hidden]

**Comment by mahmood-sajjadi** [comment]
thank you @gdi2290 
I checked [attr.hidden] there are few issues
1) what about other attribute directives?
2) hidden="false" and hidden="true" both of them are hidden always, so user never will be notified about error

but the result of SSR with your solution is hidden="true", It is not working in the chrome browser but it is a trying to hide the message 👍 

If I change [hidden] to *ngIf it will work as expected

> the issue is why Zone and angular will not wait for the result of an attribute directive

**Comment by mahmood-sajjadi** [comment]
@mhevery @gdi2290 
any update on this issue?

**Comment by Toxicable** [comment]
@mahmood-sajjadi if you use `[attr.hidden]="shouldShow"` where `shouldShow = null` then the attribute will not be appended to the DOM
example here https://plnkr.co/edit/OA8VZxii4gdRlnSesST4?p=preview

**Comment by mahmood-sajjadi** [comment]
thank you @Toxicable 

the problem here is: 
1) what about other attribute directives
2) In this example that I raised the value is something from angular which is true or false, it can't be undefined

I will add new update demo to reproduce this issue with custom attribute directive and I will change the title.

this issue is more generic than [hidden]

**Comment by vikerman** [comment]
You should be using [attr.hidden]. Only attributes get serialized by platform server. There are certain properties that are automatically reflected to attributes in the HTML specs for which something like this may work but for others you need to use [attr.someAttribute]

**Comment by gdi2290** [comment]
`[attr.hidden]=" check ? '' : null "`
if the value is null then the attr should be removed. if it's `''` then it should remain as a boolean attr `<div hidden></div>`
