### ISSUE TITLE
Bindings not working properly after replacing FormArray using setControl() and adding new controls

### ISSUE THREAD

**Issue by HHDanim** [angular/angular#18376]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If you replace a FormArray instance with a new instance in a reactive form using setControl() after the view was rendered, newly inserted controls (using insert()) are not bound to the correct value.

When I call setControl() all existing controls get removed from the view and the form value is reset to an empty array. If I then insert controls into the FormArray they show up in the view and an entry in the form values array is created. But the controls don't bind to the corresponding values: After adding two or more controls the last two inserted controls show the same value in the view and change the same entry of the form values array. If three or more controls are inserted, the first inserted control loses its binding and does not reflect changes to any entry of the array anymore.

If you only use push() to add new controls it seems to work at first sight. But if you delete any control but the last or second last one, bindings are getting twisted.

## Expected behavior

After replacing a FormArray the bindings of added/inserted controls should be set correctly, just as if the FormArray hadn't been replaced.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/aJhJgZedaYgOowe3cUHo?p=preview

Demo using insert():
1. Click "Insert(0)" a few times. The form should now display controls showing consecutive values starting at 0 (bottom-up).
2. Click "Reset". All controls should now be removed from the view and the values array should be empty.
3. Click "Insert(0)" severeal times. The two uppermost controls should now display the same value - which is incorrect. Numbers displayed should start at 1 although 0 is the lowest value in the values array.

Demo using push():
1. Click "Reset"
2. Click "Push" three or more times
3. Click "Remove row" on the first row. The last two inputs should now display the same number, which again is incorrect.

## What is the motivation / use case for changing the behavior?

I want to display an editable list of FormGroups so that the user can add/insert/remove entries as needed. This list needs to be cleared/repopulated if the user selects another item. It feels wrong keeping the initial FormArray instance and calling removeAt() for every entry just to clear the FormArray.

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 54.0.1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by kara** [comment]
Merging this issue into https://github.com/angular/angular/issues/21501, which has the same root cause.
