### ISSUE TITLE
Table does not build properly after filtering

### ISSUE THREAD

**Issue by KGrewe** [angular/angular#18373]
I have got a problem with filtering a table in angular2.
Filtering works perfectly fine, but deleting the filter afterwards [this does happen][1].

The table does not rebuild as planned. The Lines are all over the place but not in the table anymore.

I have tried to simplify the html code. If you need to see more, please ask!

    <table>
       
       
       <tbody *ngFor="let detail of filteredDetails; let posi = index">
           <tr>
               <td (click)="showDetail(detail.itemId)">
                   <div><b>{{detail.itemName}}</b></div>
                   <div>{{detail.itemId}}</div>
               </td>
               
           </tr>
           
           <tr *ngIf="detail.showDetail">
               <td colspan="5">
                    
               </td>
           </tr>
        </tbody>
        
        <tbody>
           <tr>
              <td>
                  
              </td>
              <td colspan="3">
                 <input value="" [(ngModel)]="searchValue" (ngModelChange)="filterDetails()"/>
              </td>
              <td>
                
              </td>
            </tr>
         </tbody>
    </table>

Here is the simplified Typescript Code

    public filteredDetails: POSStockDetailWeb[];
    public searchValue: string;

    //the constructor an the init functions

    filterDetails() {
      if (this.searchValue == null || this.searchValue == "")
        this.filteredDetails = this.POSStock.safePOSStockDetails;
      else {
        console.log(this.searchValue);
        this.filteredDetails = [];
        for (let detail of this.POSStock.safePOSStockDetails) {
          if ((detail.itemId.indexOf(this.searchValue) !== -1) || 
              (detail.itemName.indexOf(this.searchValue) !== -1)) {
            this.filteredDetails[this.filteredDetails.length] = detail;
          }
        }
      }
        
    }

Thank you for your help!

If you need more input please ask!

  [1]: https://i.stack.imgur.com/SsrNW.png

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
