### ISSUE TITLE
Async validator not working without Validator.required

### ISSUE THREAD

**Issue by igogu** [angular/angular#18378]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When you declare a FormControl without Validator.required and an async validator, there is an error.

> ERROR Error: Expected validator to return Promise or Observable. 

with:
`new FormControl(question.value || '',  null,this.AsyncValidator(question)) `

But it's ok if you have:
`new FormControl(question.value || '',  Validators.required, this.AsyncValidator(question)) `
## Expected behavior

the expected behavior would be defining async validators in formcontrol without a required sync validator.

## What is the motivation / use case for changing the behavior?

I need a field without required validation but with an async validation

## Environment

<pre><code>

angular version: 4.3.1

Browser:
- [ x] Chrome (desktop)

 
For Tooling issues:
- Node version: 7.2.0
- Platform:  Linux

</code></pre>

**Comment by jrvaliente** [comment]
I have the same problem, i've tried to set non asycr validators to null or set Validators.maxLength and the problem persist

**Comment by ericmartinezr** [comment]
The problem here is not what you think it is. The error clearly says that you're not returning a Promise nor an Observable in your Async Validador. What's weird is that when you add the Validator.required validator the error dissapears, when imho it should still be there.

[Reproduction](http://plnkr.co/edit/goQQ7nkzM1p943ZSEBdW?p=preview). The sync validator is null, the async validator is not null returning a promise resolving to nothing really, it's just to reproduce the problem. Comment the return and you'll see the error.

**Comment by igogu** [comment]
I wrote the code for reproduce the problem in this [plunkr](http://plnkr.co/edit/EZH1hDRwwTUtqf1PMLOj?p=preview) .
As you can see I have done 2 formControls. one with sync validator required and my async validator, that is not giving any error.

And the another formControl with any sync validator and the same async validator, and it gives the next error that I commented here :

> ERROR Error: Expected validator to return Promise or Observable.

I have written two possibilities of async validator aswell.

**Comment by ericmartinezr** [comment]
@igogu in your `checkCodiFactory` you have the promise wrapped inside a function. If you remove the function it will work (it won't throw the error).

Try this instead

```
  checkCodiFactory(control: AbstractControl){
              return new Promise (resolve => /* ... */);
  }
   
```

**Comment by kara** [comment]
Async validators only run if sync validators pass. So if you add Validators.required with an empty value, it will fail and the async validators won't run (and therefore won't throw an error).
