### ISSUE TITLE
official page to find angular plugins

### ISSUE THREAD

**Issue by shivajivarma** [angular/angular#18375]
Can we have official page, where people can submit Angular plugins. That helps developers to find plugins easily (differentiating from AngularJS). 

It's very hard to search the web for Angular(TS) plugins in the AngularJS dominant world.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shivajivarma** [comment]
like a store for angular plugins...

**Comment by gkalpak** [comment]
There is a list 3rd-party libraries here: https://next.angular.io/resources
As mentioned elsewhere, you can also append `-angularjs` to your search query to exclude AngularJS results.
