### ISSUE TITLE
How use async service into angular httpClient interceptor

### ISSUE THREAD

**Issue by pvitale** [angular/angular#18382]
## I'm submitting a...
[x] Feature request

## Current behavior
Using Angular 4.3.1 and HttpClient, I need to modify the request and response by async service into the HttpInterceptor of httpClient,

Example for modifying the request:
`
export class UseAsyncServiceInterceptor implements HttpInterceptor {

  constructor( private asyncService: AsyncService) { }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    // input request of applyLogic, output is async elaboration on request
    this.asyncService.applyLogic(req).subscribe((modifiedReq) => {
        const newReq = req.clone(modifiedReq);
        return next.handle(newReq);
    });
    /* HERE, I have to return the Observable with next.handle but obviously 
    ** I have a problem because I have to return 
    ** newReq and here is not available. */
  }
}
`

Different problem for the response, but I need again to applyLogic in order to update the response. In this case, the angular guide suggests something like this:

`
return next.handle(req).do(event => {
    if (event instanceof HttpResponse) {
        // your async elaboration
    }
}
`

But the "do() operator—it adds a side effect to an Observable without affecting the values of the stream".

Also, in this scenario, I don't know how to modify the response without adding the complexity of the asyncService.

## Expected behavior
As in angular 1.5, the interceptor should able to update the request and the response with async meccanism. In angularjs the returned object was the promise, and it was able to resolve it after.

## What is the motivation / use case for changing the behavior?
I need to add for all services information into the request/response, and this information are only retrived by async call.

## Environment
Angular version: 4.3.0

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

It looks like you're having a problem with how to use Observables. I would suggest to do some research on `rxjs`  then come back to this

**Comment by pvitale** [comment]
StackOverflow issue: https://stackoverflow.com/questions/45345354/how-use-async-service-into-angular-httpclient-interceptor
