### ISSUE TITLE
`gulp test.unit.js` run test multiple times

### ISSUE THREAD

**Issue by vicb** [angular/angular#1838]
`gulp test.unit.js` used to run test twice and I think @juliemr fixed this.

I have a branch based on the current master, it is even worse:
```
...
[16:37:00] Starting '!test.unit.js/karma-run'...
Chrome 39.0.2171 (Linux): Executed 0 of 1129 SUCCESS (0 secs / 0 secs)
Chrome 39.0.2171 (Linux): Executed 6 of 1129 (skipped 1) SUCCESS (0.013 secs / 0.012 secs)
Chrome 39.0.2171 (Linux): Executed 6 of 1129 (skipped 1) SUCCESS (0.013 secs / 0.012 secs)
Chrome 39.0.2171 (Linux): Executed 6 of 1129 (skipped 1) SUCCESS (0.013 secs / 0.012 secs)
Chrome 39.0.2171 (Linux): Executed 6 of 1129 (skipped 1) SUCCESS (0.016 secs / 0.015 secs)
TOTAL: 12 SUCCESS
```

Is this a known issue ?

/cc @IgorMinar @alexeagle

**Comment by caitp** [comment]
Is this #1759?

**Comment by pkozlowski-opensource** [comment]
@vicb as those test really run twice or is it "just" the reporter going crazy? I saw some issues with this progress reporter in the past, as it uses a trick of going back to a previous line in a terminal and editing it. It can break depending on a terminal and its size....

**Comment by vicb** [comment]
I think they are actually executed twice (exception messages are displayed twice).
Seems like it was executing 4 times because I ended up with 2 karma instances running in parallel.

Closing for now until 1759 gets fixed.
