### ISSUE TITLE
Missing documentation to set up source maps for debugging

### ISSUE THREAD

**Issue by RoestVrijStaal** [angular/angular#18389]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
See https://stackoverflow.com/questions/45314808/angulars-zone-js-hates-raphaeljs 
People suggest that I should look into compiled code but that isn't possible due the incorrect / absent source maps.  
At angular.io I can't find any info how to set those up. 

## Expected behavior
Please cover in the docs how to setup & maintain source maps 

## Minimal reproduction of the problem with instructions
https://encrypted.google.com/search?hl=nl&q=how+to+set+up+source+maps+site%3Aangular.io&oq=how+to+set+up+source+maps+site%3Aangular.io

https://duckduckgo.com/?q=how+to+set+up+source+maps+site%3Aangular.io&ia=web

## What is the motivation / use case for changing the behavior?
Well, imine at StackOverflow for example. 

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [X] Pale Moon: 27.4.0 

For Tooling issues:
- Node version: v8.2.1
- Platform:  Linux

</code></pre>

**Comment by dherges** [comment]
Hi,

this isn't related to Angular in particular. It is really more of an TypeScript / JavaScript bundling topic.

When you are using [Angular CLI](https://github.com/angular/angular-cli), the cli comes w/ first-class source maps support in dev mode!

**Comment by Dok11** [comment]
> When you are using Angular CLI, the cli comes w/ first-class source maps support in dev mode!

Are you sure? Maybe you can give link to manual?
But now I look same this:
![image](https://user-images.githubusercontent.com/2697890/28748108-58c105c6-74b7-11e7-8d27-8756c9e20c3b.png)

and no traces about sorcemaps in dev mode even with `--sourcemap` key

**Comment by dherges** [comment]
Yes, sure. You find the sources under the `ng://` and `webpack://` protocol. However, CSS and HTML sourcemaps seem to be broken currently.

![screen shot 2017-07-30 at 07 47 02](https://user-images.githubusercontent.com/901354/28750966-84cd2dfe-74fb-11e7-9206-b7077850aa3c.png)
![screen shot 2017-07-30 at 07 47 08](https://user-images.githubusercontent.com/901354/28750967-84d1256c-74fb-11e7-9591-7502fe6cbb5d.png)

**Comment by alxhub** [comment]
This is indeed a CLI issue. If you're having trouble with CLI sourcemaps, please open an issue in their repo.

**Comment by RoestVrijStaal** [comment]
@alxhub true, but angular-cli doesn't have its own docs. And it's a part of Angular since you manage an Angular project with it. Otherwise its naming is incorrect.

**Comment by JounQin** [comment]
@alxhub Then what about not using `angular-cli`? I'm trying to build project with webpack by myself, but I can not find anything about how to enable css source map while using `@Component({styles})` or `@Component({styleUrls})`.
