### ISSUE TITLE
Getting router data 'undefined' after upgrading from angular 4.2.4 to 4.3.1

### ISSUE THREAD

**Issue by jupereira0920** [angular/angular#18386]
Hello everyone,

So, with the release of the new version of angular, with the new http module, i upgrade my angular version from 4.2.4 (angular-cli 1.2.1)  to 4.3.1 (angular-cli 1.2.5) to be able to use the new httpclient module. Everything looks fine when while working on development environment , on my machine,  but when i did build for production using angular-cli, I notice that the variable 'data' that i have on my routes, was undefined. 

On a new branch I upgrade only angular-cli and test with angular 4.2.4 with angular-cli 1.2.5, and works perfectly, so i assume, that could be something with angular 4.3.1, here is more details. 

**On server** 

![image](https://user-images.githubusercontent.com/1928942/28690185-3130240e-7310-11e7-90d6-11ba0199aba0.png)

**Local**
 
![image](https://user-images.githubusercontent.com/1928942/28690207-48e0c55e-7310-11e7-8dc3-332f6c543632.png)

The code working on version 4.2.4 
![image](https://user-images.githubusercontent.com/1928942/28690254-6292f08a-7310-11e7-8ce4-6cd8a8649463.png)

With version 4.3.1 on the red arrow i got 'undefined', and to solve it a did the following. 

![image](https://user-images.githubusercontent.com/1928942/28690306-9b6b5122-7310-11e7-8922-093ad326d8ae.png)

It can assign the value of ROUTES['TERMS'] on the route path, but not on the data. 

For Tooling issues:
- Platform: Window

</code></pre>

**Comment by jasonaden** [comment]
This issue should have requested a reproduction. I'm going to close it due to inactivity and no reproduction. If this continues to be a problem, please create a new issue including a repro of the problem.
