### ISSUE TITLE
HttpClient 'Http failure during parsing' error for valid json

### ISSUE THREAD

**Issue by jamiemac87** [angular/angular#18396]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Request throws an error when trying to parse a response of `"ok"` which is considered valid json according to https://jsonlint.com/ 

---

request: 
```
    const requestOptions = Object.assign(
      {}, 
      { responseType: 'json' }, 
      { observe: 'body' as HttpObserve }
    );

    this.httpClient.request('GET', './mockjson.json', requestOptions)
    ...
```

---

error: `"Unexpected token o in JSON at position 0"`

## Expected behavior

No error should be thrown for a response of `"ok"`

## Minimal reproduction of the problem with instructions

https://embed.plnkr.co/klPNUS/

## Environment

<pre><code>
Angular version: 4.3.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
This is definitely a bug, in [`HttpClient`](https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts#L110), Angular already sets the `responseType` to `json`, so that browser would automatically parse the body and provide the parsed JavaScript value as `response`. Then again, [`HttpClient`](https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts#L182) is going to parse the already parsed result if it's a string value.

**Comment by jamiemac87** [comment]
Thanks @alxhub I'll try your workaround

**Comment by Toxicable** [comment]
https://github.com/angular/angular/blob/master/packages/common/http/test/xhr_spec.ts#L95-L100
From what I'm reading here this specifically tests for a situation where the body is unparsed json but responseText is set to 'json' which according to this that's incorrect 
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response

**Comment by jamiemac87** [comment]
how long before this is fixed and merged?

**Comment by mrahhal** [comment]
Anyone has a workaround for this?

**Comment by mrahhal** [comment]
I tried my hand at it, came up with this:

```ts
import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest, HttpResponse } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';

// Remove when https://github.com/angular/angular/pull/18466 gets merged.

@Injectable()
export class WA18396Interceptor implements HttpInterceptor {
	constructor() { }

	intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
		if (req.responseType == 'json') {
			req = req.clone({ responseType: 'text' });

			return next.handle(req).map(response => {
				if (response instanceof HttpResponse) {
					response = response.clone<any>({ body: JSON.parse(response.body) });
				}

				return response;
			});
		}

		return next.handle(req);
	}
}

```

**Comment by jamiemac87** [comment]
This works for me. Pretty much the same as @mrahhal answer only I also found I had to catch and parse the error as well.

```
    return next.handle(clonedRequest)
      .map((event: HttpEvent<any>) => {
        if (event instanceof HttpResponse) {
          return event.clone({
            body: JSON.parse(event.body),
          });
        }
      })
      .catch((error: HttpErrorResponse) => {
          const parsedError = Object.assign({}, error, { error: JSON.parse(error.error) });
          return Observable.throw(new HttpErrorResponse(parsedError));
      });
```

**Comment by codemonkey00** [comment]
I updated our Http to HttpClient and all strings being returned were giving me 'Http failure during parsing'.
Thanks to mrahhal and jamiemac87, I combined your fixes and Json responses as strings are now working.

**Comment by tommy-ly** [comment]
Hey everyone I have a solution, just return an emPTY body

**Comment by dyh333** [comment]
this.http.get(url, {responseType: 'text'})

it works as well.

**Comment by michahell** [comment]
For those who can not change to a text content type (in my case a POST file upload with content type `application/octet-stream`, the following seems like a solution:

```TypeScript
return this.httpClient.request<File>(req)
			//TODO remove when Angular 4.4 Json parse bug is fixed
			.catch((error: HttpErrorResponse) => this.handleAngularJsonBug(error))
```

```TypeScript
private handleAngularJsonBug (error: HttpErrorResponse) {
		this.log.debug('caught file upload error: ', error);

		this.log.debug(`error.message: ${error.message}`);
		const JsonParseError = 'Http failure during parsing for';
		const matches = error.message.match(new RegExp(JsonParseError, 'ig'));
		this.log.debug('JSON parse error matches:', matches);

		if (error.status === 200 && matches.length === 1) {
			// return caughtObs;					// return observable with shit
			return Observable.empty();
		} else {
			this.log.debug('re-throwing ');
			return Observable.throw(error);		// re-throw
		}
	}
```

**Comment by mmanavaz** [comment]
+1 I had the same issue with interceptors.

I have a question on @jamiemac87 and @mrahhal 's answers...I'm getting that any is not a valid data-type for HttpRequest. Is there an easy way to get intelliJ IDE to recognize this datatype for HttpRequest?

**Comment by mrahhal** [comment]
@mmanavaz make sure you're importing from the correct module ('@angular/common/http'), and that you're on latest typescript version. Not sure why it would tell you that otherwise.

**Comment by mmanavaz** [comment]
@mrahhal still getting the same issue...I checked for the correct import and latest Typescript version...both are correct.

**Comment by mmanavaz** [comment]
I was able to figure it out.

**Comment by subinsebastian** [comment]
I also faced the same issue, 
Status Code: 304 Not Modified
Error Message: 'Http failure during parsing'.

Simple explanation as given by @trotyl 
Angular has set `responseType` to `json`,
Therefore when httpClient doesn't find the endpoint's response to be JSON it simply dosen't modify the Component View.
Easy fix(or you may call it a temporary workaround)
Simply make the endpoint to send JSON response.
Eg. if its an express server, you could send `res.json({ mgs: 'Succesfully hit the endpoint' })`,
instead of sending a plain text.

_This workaround will work, or you may opt to use the intercept function as mentioned in above discussions above._

**Comment by trotyl** [comment]
@subinsebastian That's completely irrelevant issue. Plain text is not JSON, what you're looking for is #19413. And all of these issues have already been fixed.

**Comment by leojkwan** [comment]
Ran into same problem making a `put` request to my endpoint. I realized I was sending 200 without a response body. Sending status code `204` made angular http 5.2.8 stop complaining. This problem should not be happening even with a 200, but 204 is the correct code for empty responses.

**Comment by ryanbuening** [comment]
@leojkwan thanks for your comment. I ran into the same issue with Angular 5.2.9.

**Comment by dreamid27** [comment]
> this.http.get(url, {responseType: 'text'})
> 
> it works as well.

Some people may be confusing about this and I'm included, 
this is the reference for he's mean : https://angular.io/guide/http#requesting-non-json-data 

thank for you @dyh333  and sorry my english too bad.

**Comment by akildemir** [comment]
The date is  11.11.2018 and I  am still having the same issue!! Do you guys have any updated solution? Thanks!

**Comment by malkoto1** [comment]
Well, now the date is 28.12.2018 and I have just upgraded to 7.1.4 and the issue is still presented. Stunning...

**Comment by ShemiNechmad** [comment]
Even adding responseType, I dealt with it for days with no success. 
Finally I got it!
Make sure that in your backend script you don't define header as -("Content-Type: application/json); 

Becuase if you turn it to text while backend asks for json, it will return an error...

**Comment by DaniSido** [comment]
Ciao everybody,
I've found the solution adding 'json_encode($var)' to the return statement of my function.

Hope it helps.

**Comment by joylolili** [comment]
Hi,
It works for me to set Headers like 
`let httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/json',
      }),
      responseType: 'text' as 'json'
    };`
Hope it helps.
