### ISSUE TITLE
Animation params do not support math operations

### ISSUE THREAD

**Issue by jiayihu** [angular/angular#18398]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```javascript
export const fade = animation(
  [
    style({ opacity: '{{ from }}' }),
    animate('{{ 1 + timing }}s', style({ opacity: '{{ to }}' })),
  ],
  { params: { from: 1, timing: 1, to: 0 } }
);
```

The previous animation throws:

```
Error: Unable to process animations due to the following failed trigger transitions
@fadeIn has failed due to:
- Please provide a value for the animation param 1 + timing
- The provided timing value "s" is invalid.
```

## Expected behavior

I would expect the binding syntax to support math operations at least, and not just string replacement. Otherwise it's still impossible to make not trivial animations reusable.

Support for booleans also sounds reasonable for me. For instance, it could allow an animation called `fade,` which can accept a boolean param `out` to choose between `0 => 1` opacity animation or the opposite without the need to duplicate the code.

## Environment

<pre><code>
Angular version: 4.3.2

Browser:
All
</code></pre>

**Comment by mattscu** [comment]
you can actually just use a function with parameters instead of a constant

**Comment by jiayihu** [comment]
It could some use cases but it's still limited because you loose the flexibility and reusability of template binding. For instance you are not able to use component properties.

**Comment by erik-slack** [comment]
This is a pain point for me as well.

**Comment by matsko** [comment]
Instead of adding in an animation expression language into animations, the plan is to just expand the syntax to allow inner functions that work off of JS (just like @matthiasscudlik pointed out).

```js
animate(1000, style((element, currentStyles, params) => {
  // use the params
  return { someProp: 'someVal' };
}));
```

That way things like currying and other fancy JS goodness can be put to use:

```js
import {rotate} from 'utils.ts';

transition('* => 90deg', [
  animate('100ms', style(rotate('90')))
])
```

Right now I'm working on a prototype. More stuff will follow as 5.1 comes around.
