### ISSUE TITLE
HttpParams null value gets converted to 'null' query string parameter

### ISSUE THREAD

**Issue by ashgibson** [angular/angular#18394]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If a parameter is set or appended with a null value e.g. .set('param', null), this gets converted to param=null.

## Expected behavior
Either param should equal an empty string or omitted from the the params completely.

## Minimal reproduction of the problem with instructions
        let test = new HttpParams();
        test = test.set('one', '1');
        test = test.set('two', '2');
        test = test.append('one', '3');
        test = test.set('blah', null);

        console.log(test.toString());

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alxhub** [comment]
`null` is explicitly not supported as a value per the typings - only `string` is accepted.
