### ISSUE TITLE
'NgModuleInjector' does not exist on type

### ISSUE THREAD

**Issue by SanthoshKumarKatta** [angular/angular#18393]
Hi,
I have used " https://www.npmjs.com/package/angular2-social-login " for my application to integrate social media authentication and was working with angular2. Now am trying to use the same with angular4 but getting following error -

ERROR in .../angular2-social-login.module.ngfactory.ts (12,57): Property 'NgModuleInjector' does not exist on type 'typeof "../node_modules/@angular/core/src/linker/ng_module_factory.'

This is code -

/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './angular2-social-login.module';
import * as import2 from './socialAuth.service';
import * as import3 from '@angular/core/src/di/injector';
class Angular2SocialLoginModuleInjector extends import0.NgModuleInjector<import1.Angular2SocialLoginModule> {
  _Angular2SocialLoginModule_0:import1.Angular2SocialLoginModule;
  __AuthService_1:import2.SocialAuthService;
  constructor(parent:import3.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _AuthService_1():import2.SocialAuthService {
    if ((this.__AuthService_1 == null)) { (this.__AuthService_1 = new import2.SocialAuthService()); }
    return this.__AuthService_1;
  }
  createInternal():import1.Angular2SocialLoginModule {
    this._Angular2SocialLoginModule_0 = new import1.Angular2SocialLoginModule();
    return this._Angular2SocialLoginModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.Angular2SocialLoginModule)) { return this._Angular2SocialLoginModule_0; }
    if ((token === import2.SocialAuthService)) { return this._AuthService_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Angular2SocialLoginModuleNgFactory:import0.NgModuleFactory<import1.Angular2SocialLoginModule> = new **_import0.NgModuleFactory(Angular2SocialLoginModuleInjector,import1.Angular2SocialLoginModule);_**

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

help me out to resolve this.

Thanks!

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by prkandimalla** [comment]
Thanks eric

**Comment by SanthoshKumarKatta** [comment]
Thanks eric! Posted in stackoverflow. 
https://stackoverflow.com/questions/45363284/ngmoduleinjector-does-not-exist-on-type
