### ISSUE TITLE
Lazy Loading Feature dysfunctional or not Lazy loaded

### ISSUE THREAD

**Issue by ganeshkbhat** [angular/angular#18395]
Lazy Loading Feature dysfunctional or not Lazy loaded

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Lazy loading Module is parsed and loaded in the start of app instantiation. Seems it is not truly Lazy loading

## Expected behavior

The module should not parse during the start of the app.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/BrcvDHJIaJFtMOY4eoWp

```
@NgModule({
  imports: [
    RouterModule.forChild(
      lazyRoutes
    )
  ],
  exports: [
    RouterModule
  ]
})
export class LazyRouteModule { 
  constructor(){
    console.log('lazy Module Already Parsed and Loaded');
  }
}
```

## What is the motivation/use case for changing the behavior?
Behavior not performant leading to unnecessary code bloat (loazy loading) in framework.

## Environment
Any

Angular version: 
https://unpkg.com/@angular/core@4.3.2/bundles/core.umd.js

Browser:
Any

For Tooling issues:
NA

Others:
NA

**Comment by Simon-Briggs** [comment]
You've imported LazyModule in your AppModule imports section.
That causes the LazyModule to be loaded during app instantiation.
Delete that to fix your problem.

**Comment by ganeshkbhat** [comment]
thanks. that was quick and easy and didnt throw an error.
