### ISSUE TITLE
it is showing that the file may harm the computer

### ISSUE THREAD

**Issue by PrasannaLaxmi** [angular/angular#18404]
![issue](https://user-images.githubusercontent.com/27019639/28728056-c789e5f0-73e4-11e7-819c-90cd163dd2b2.png)

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
