### ISSUE TITLE
Is possible to run angular2+ without any server

### ISSUE THREAD

**Issue by saravanans-arch** [angular/angular#18409]
## Is possible to run angular2+ without any server

<pre><code>

## I'm working on (onsenui-angular2 + cordova + angular2+) hybrid mobile app development, 
recently i'm trying to develop my mobile app using with angular2+ scripts. And find a 
onsen-angular2-kitchen-sink project. In my local it's working with ng serve 3000 port, 
So i can see that mobile app in my browser. But when i'm going to run the app in my android mobile 
it's getting  "**index.html**", so it's always showing loading.. only. 
I'm totally any one please help me.

My Project Setup Here.
https://github.com/saravanans-arch/ng2-onsen-cordova-example.git

</pre><code>

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
