### ISSUE TITLE
HttpClient not respecting withCredentials

### ISSUE THREAD

**Issue by MartinSvarrer** [angular/angular#18402]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

HttpClient accepts a `withCredentials` property. Setting the property doesn't do anything when running the application in Chrome (haven't checked other browsers).

## Expected behavior

I would expect a request that includes `withCredentials` to allow returned response header cookies to be set. But as the fetch api seems to be used instead, it requires the `credentials: 'include'` to be set instead of withCredentials property. I would expect HttpClient to choose the correct setting based on the technology used (xhr2 vs fetch).

## Minimal reproduction of the problem with instructions

This snippets assume you have a cookie based authentication service for logging in.

```ts
const body = 'username=admin&password=abc';
const headers = new HttpHeaders({'Content-Type': 'application/x-www-form-urlencoded'});
this.http.post('/auth/login', body, { headers, withCredentials: true })
   .subscribe(value => console.log('success'));
```

Now check if the cookies provided in the response headers are stored in the browser.

## What is the motivation / use case for changing the behavior?

I would like to be able to use a cookie based authentication service.

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version Version 60.0.3112.78 (Officiel version) beta (64-bit)
</code></pre>

**Comment by alxhub** [comment]
`HttpClient` doesn't use `fetch()` at all, I'm not sure where you're seeing that.

Do you get "success" from your example snippet above? `withCredentials` affects whether cookies will be sent with the *outgoing* request, not whether any cookies set by the response will be accepted.

**Comment by MartinSvarrer** [comment]
> HttpClient doesn't use fetch() at all, I'm not sure where you're seeing that.

Sorry, I have misinterpreted the documentation regarding fetch big time! Please ignore anything mentioned regarding fetch. Think my thoughts came from the opening lines in the documentation: 

"Modern browsers support two different APIs for making HTTP requests: the XMLHttpRequest interface and the fetch() API. With HttpClient, @angular/common/http provides a simplified API for HTTP functionality for use with Angular applications, building on top of the XMLHttpRequest interface exposed by browsers."

> Do you get "success" from your example snippet above?

Yes, I get a status code 200 back, and I can see the cookies in the response header when inspecting the request.

> withCredentials affects whether cookies will be sent with the outgoing request, not whether any cookies set by the response will be accepted.

That is not how I read the documentation regarding that feature. Here is an excerpt from [MDN:](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials)

"Note: XmlHttpRequest responses from a different domain cannot set cookie values for their own domain unless withCredentials is set to true before making the request, regardless of Access-Control- header values."

As I write this I realize I have forgotten an important piece of information: The request is a cross domain request. The server does have the `Access-Control-Allow-Credentials: true` and I have successfully managed to retrieve the cookies using the fetch() api. So the server should be configured appropriately.

**Comment by MartinSvarrer** [comment]
Okay I am missing something somewhere, so I will close this as a bug. Cannot successfully make the request using a XHR request, only with fetch. I assumed, HttpClient used fetch under the hood, and after successfully making it work with fetch api, I thought this was a bug.

For anyone interested I am able to make fetch request work as expected:

```ts
fetch('https://foo.local/auth/login', {
      method: 'POST',
      headers: new Headers({ 'Content-Type': 'application/x-www-form-urlencoded' }),
      body: 'username=admin&password=abc',
      credentials: 'include'
    })
    .then(response => console.log('SUCCESS'));
```

But trying a similar approach with XHR requests doesn't work for me as expected, as it will not set cookies from the response headers:

```ts
const xhr = new XMLHttpRequest();
xhr.open('POST', 'https://foo.local/auth/login', true);
xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
xhr.withCredentials = true;
xhr.onload = function () {
  console.log('SUCCESS');
};
xhr.send('username=admin&password=abc');
```
