### ISSUE TITLE
Raw params string is not accepted by HttpClient and HttpRequest

### ISSUE THREAD

**Issue by bisubus** [angular/angular#18403]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Passing `params` option as encoded string results in type error, because only `HttpParams` objects are expected.

## Expected behavior
`params` is accepted as both a string and `HttpParams` instance.

## Minimal reproduction of the problem with instructions
This works as expected:
```
const params = 'foo&bar=&baz=baz';
http.get(url, { params });
```

This results in compilation error:
```
const params = 'foo&bar=&baz=baz';
httpClient.get(url, { params });
```

## What is the motivation / use case for changing the behavior?

Current behavour is a regression from `Http` which allowed to use encoded `params` strings in request options. Considering that `HttpParams` object is just [converted to a string](https://github.com/angular/angular/blob/4f1e4ffa4eefcbfc4af310738ce0f59279f9cc94/packages/common/http/src/request.ts#L210), it could be a string from the beginning.

In the example above  `foo&bar=&baz=baz` params are parsed to `{ foo: null, bar: '', baz: 'baz }` object on the backend. This would be not possible with default `HttpParams` implementation because it makes no difference between nully values and empty strings:

```
const params = new HttpParams({ toString: 'foo&bar=&baz=baz' });
httpClient.get(url, { params }); // url?foo=&bar=&baz=baz
```

This cannot be fixed with custom `HttpUrlEncodingCodec`, because the information about the difference between `foo` and `bar=` is already lost in  `HttpParams` private `map`.

## Environment

<pre><code>
Angular version: 4.3.1

</code></pre>

**Comment by Yura13** [comment]
I have workaround:
```
 const httpParams: HttpParams = new HttpParams()
      .set('password', 'password')
      .set('username', 'username');
const params: string = httpParams.toString();
this.httpClient.post(url, params);
```

**Comment by petebacondarwin** [comment]
Closing https://github.com/angular/angular/pull/20727#issuecomment-763947297
