### ISSUE TITLE
docs(aio): Possible XSS vulnerability when redirecting to plnkr.co from docs (NoScript)

### ISSUE THREAD

**Issue by naltun** [angular/angular#18410]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When reading through the [tutorial](https://angular.io/tutoriall) at `angular.io`, each section of the tutorial has a link to view a live demo of the app at `plnkr.co`. When you open the link, NoScript (a browser extension which adds privacy/XSS protection to the user) sends you to a `404` page and throws this error in the console:
`The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
`
As well as multiple `Content Security Policy: The page's settings blocked the loading of a resource`, regarding GitHub resources from various sites (githubusercontent.com, githubapp.com, github-cloud.s3.amazonaws.com).

## Expected behavior

The desired behavior should be to provide a XSS-safe mode of redirecting from `angular.io` to any relevant third-party sites.

## Minimal reproduction of the problem with instructions
To reproduce this error, the user must have the NoScript browser extension installed, on Firefox; seeing how NoScript is browser-agnostic, the bug should be producible on other modern browsers.

## What is the motivation / use case for changing the behavior?
The motivation for changing this error is that all XSS vulnerabilities should be dealt with, providing the safest, most-secure experience to any user at `angular.io`.

## Environment

<pre><code>
Angular version: 1.6.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 54.0
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1
- Platform: Linux

Others:

</code></pre>

This is site-specific to [Angular.io](angular.io). This can be reproduced by using the NoScript browser extension (modern browser-agnostic).

**Comment by gkalpak** [comment]
The root cause of the issue is that NoScript will, by default, convert cross-site POST requests to GET requests. In this case, it is necessary to do a POST request from `angular.io` to `plnkr.co` and there is obviously no XSS vulnerability here. It is a false alarm and one we can't do much about, I'm afraid.

**Comment by naltun** [comment]
@gkalpak That makes sense. Feel free to close this then, or handle as you see fit. Thanks for the swift response.
