### ISSUE TITLE
Custom Form Controls using CustomValueAccessor not garbage collecting properly

### ISSUE THREAD

**Issue by bd60** [angular/angular#18414]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using a component that implements ControlValueAccessor to make a custom form component, if that component is added/removed from the page via the *ngIf directive, and you have subscribed to the form control's valueChanges event, and you attempt to reset the form and destroy the component, this causes the valueChange subscription to fire more and more everytime the form control is recreated. It appears the formControl is not being garbage collected properly, and I don't see a way to garbage collect it manually.

This does not happen with a standard form element that is destroyed/recreated/reset in the same manner, nor does it happen with a custom form control that is not destroyed/recreated.

## Expected behavior

The valueChange event should not fire everytime the component is destroyed and recreated and the form reset.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/4yE8aHO3tEuu3PtyIQdf?p=preview

Recreated here. Click toggle control to see how resetting, destroying and recreating the form control causes the valueChange event to fire more and more, while the standard element behaves as expected. And a custom control that is not destroyed / recreated also behaves mostly as expected, though the subscription seems to always fire twice for some reason.

## What is the motivation / use case for changing the behavior?

the real use case here is a form that requires a custom form control and that can be toggled between read only and edit mode with a button to throw out changes. I have worked around this by just using CSS classes to hide / show the appropriate element.

## Environment

<pre><code>
Angular version: 4.X.X

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by raysuelzer** [comment]
I think I am having a related issue.  Let's say that I have a form array, with N elements, each with a ControlValueAccessor. I remove an item from my FormArray, it gets removed from the DOM.  But the onChange event in my ControlValueAccessor is fired, which causes an error because of this line in angular forms ``` function cleanUpControl(control, dir) {
    /** @type {?} */ ((dir.valueAccessor)).registerOnChange(function () { return _noControlError(dir); }); /** @type {?} */
    ((dir.valueAccessor)).registerOnTouched(function () { return _noControlError(dir); });```  

So that i *think* happens is:
   ` this.myFormArray.removeAt(index);`

and then after this happens, the onTouched event is called by the ControlValueAccessor.  I'm not sure how to solve the issue, but it seems like the events should be removed, rather than adding an event that just throws an error?

**Comment by tytskyi** [comment]
@bd60 you implement CVA incorrectly, see fixed plunker: http://plnkr.co/edit/knGYaac8aFUds7NnVOuD?p=preview 
I also left few comments to clarify and removed unneded code

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
