### ISSUE TITLE
Should HttpObserve be exposed as well?

### ISSUE THREAD

**Issue by princemaple** [angular/angular#18416]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
it's not exposed

## Expected behavior
maybe it should be exposed

## Minimal reproduction of the problem with instructions
 N/A

## What is the motivation / use case for changing the behavior?
It's already there, `{ observe: HttpObserve }`, might as well expose it.

**Comment by Toxicable** [comment]
duplicate #18146
