### ISSUE TITLE
Angular 4 Dynamic Input Animation Reverts After Animation

### ISSUE THREAD

**Issue by azamanaza** [angular/angular#18423]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular 4.3.2 reverts animation styles with dynamic input when it ends.

## Expected behavior

Unless I change the state or the expression, the element being animated should retain the ending styles when it ends.

## Minimal reproduction of the problem with instructions
https://stackoverflow.com/questions/45377870/angular-4-dynamic-height-animation-reverts-after-animation
https://plnkr.co/edit/xDfS9pFdFHnRBEtfMjx2?p=preview

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version Version 59.0.3071.115 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by azamanaza** [comment]
The issue is actually mentioned here: https://github.com/angular/angular/issues/9668#issuecomment-309051372

**Comment by bob-lee** [comment]
This issue still persists in 5.0.0-beta.3.
@azamanaza  can you tell which previous version it used to worked?
