### ISSUE TITLE
HttpClient should support hybrid type options

### ISSUE THREAD

**Issue by princemaple** [angular/angular#18424]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
HttpClient methods don't support options that are typed as, e.g. `{ observe: 'body' | 'events' }`
`observe` has the type `HttpObserve` which is `'body' | 'events' | 'response'`, which is supposed to accept the above type.
The signature overloading seems to need to repeat the signature of the final definition.

## Expected behavior
HttpClient methods work with options that are typed as, e.g. `{ observe: 'body' | 'events' }`

## Minimal reproduction of the problem with instructions
```typescript
function f(x: string): string;
function f(x: number): number;
// function f(x: string | number): any;
function f(x: string | number): any {
    return x;
}

interface X {
    x: number | string;
}

function x(a: X) {
    f(a.x);  // this reports an error, needs line 3 to fix (which I think is absurd)
}
```
```
Argument of type 'string | number' is not assignable to parameter of type 'number'.
  Type 'string' is not assignable to type 'number'.
```

## What is the motivation / use case for changing the behavior?
I need more flexible typing in writing my app specific wrapper of `HttpClient`.

## Environment

Angular version: 4.3.2

## EDIT
Looks like `HttpClient.request` correctly repeats the final signature before the real implementation.
None of the other methods (`get`, `post`, etc) do the same. Must be missed out.
So my current workaround would be to use `request` for all the things...

**Comment by Delagen** [comment]
HttpClient does not support manual request, overriding observe option

**Comment by artuska** [comment]
This does work with the `http`:

```
let config = {
    params: params,
    observe: 'response'
};

let request = this.http.get(path, config);
```

This does not work with the `httpClient`:

```
let config = {
    params: params,
    observe: 'response'
};

let request = this.httpClient.get(path, config);
```

Because `httpClient` is stricted to `observe?: "body"`.

Just saying.

**Comment by henrahmagix** [comment]
I've had exactly this problem. Confusingly, if you declare the config object inline then there's no type mismatch, and everything works fine.

Is this a TypeScript bug?

---

Using `HttpClient`:
```ts
constructor(private http: HttpClient) {}
```

Inline works:
```ts
this.http.put(path, value, {
    observe: 'response',
});
```

Whereas variable produces a type error:
```ts
const config = {
    observe: 'response',
};
this.http.put(path, value, config)
```
This is what appears in the VS Code tooltip when hovering over `config` (it has red squiggly line under it):
```
const config: {
    observe: string;
}
Argument of type '{ observe: string; }' is not assignable to parameter of type '{ headers?: HttpHeaders | { [header: string]: string | string[]; }; observe?: "body"; params?: HttpParams | { [param: string]: string | string[]; }; reportProgress?: boolean; responseType?: "json"; withCredentials?: boolean; }'.
  Types of property 'observe' are incompatible.
    Type 'string' is not assignable to type '"body"'.ts(2345)
```

---

The overload I get when declaring inline is https://github.com/angular/angular/blob/7.2.15/packages/common/http/src/client.ts#L2567-L2574

The overload I get when using a variable is, I think, is https://github.com/angular/angular/blob/7.2.15/packages/common/http/src/client.ts#L2605-L2612

But when I hover over the `.put` call, the VS Code tooltip shows me the very first overload, which clearly doesn't match the `observe` value: https://github.com/angular/angular/blob/7.2.15/packages/common/http/src/client.ts#L2368-L2374
```
(method) HttpClient.put(url: string, body: any, options: {
    headers?: HttpHeaders | {
        [header: string]: string | string[];
    };
    observe?: "body";
    params?: HttpParams | {
        [param: string]: string | string[];
    };
    reportProgress?: boolean;
    responseType: "arraybuffer";
    withCredentials?: boolean;
}): Observable<...> (+14 overloads)
```
