### ISSUE TITLE
click not working on mobile.

### ISSUE THREAD

**Issue by itayJoseph** [angular/angular#18429]
v4.3.2
Trying to click nothing happens. (devices only / mobile) works fine on desktop????

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
