### ISSUE TITLE
Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by TheParad0X** [angular/angular#18421]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Not sure this is an angular bug or an angular2-jwt one:
When running "ng serve" I get the following error:

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (positi
on 101:22 in the original .ts file), resolving symbol AppModule in C:/dev/.git/[...]app.module.ts

But when I simply save any file and the change detection triggers a reompilation, the error is gone.
The line 101 is the following:

    JwtModule.forRoot({
      config: {
        tokenGetter: () => { // Line 101
          return localStorage.getItem('token');
        },
        whitelistedDomains: ['localhost:8080']
      }
    }),
So my console looks like this in the end:

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: 0a221417cee5f4e344ea
Time: 25991ms
chunk {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 177 kB {5} [initial] [rendered]
chunk {1} main.bundle.js, main.bundle.js.map (main) 95.3 kB {4} [initial] [rendered]
chunk {2} styles.bundle.js, styles.bundle.js.map (styles) 441 kB {5} [initial] [rendered]
chunk {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 443 kB {5} [initial] [rendered]
chunk {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 6.29 MB [initial] [rendered]
chunk {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (positi
on 101:22 in the original .ts file), resolving symbol AppModule in C:/dev/.git/[...]app.module.ts
webpack: Failed to compile.
webpack: Compiling...
Hash: 0a221417cee5f4e344ea
Time: 4136ms
chunk {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 177 kB {5} [initial]
chunk {1} main.bundle.js, main.bundle.js.map (main) 95.3 kB {4} [initial]
chunk {2} styles.bundle.js, styles.bundle.js.map (styles) 441 kB {5} [initial]
chunk {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 443 kB {5} [initial]
chunk {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 6.29 MB [initial]
chunk {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry]
webpack: Compiled successfully.

How come ?

## Environment
<pre><code>
Angular version: 4.3.1
 
For Tooling issues:
- Node version: 8.1.2 
- Platform:  Windows

**Comment by alxhub** [comment]
This seems like a CLI bug, please open an issue over on their repo. github.com/angular/angular-cli
