### ISSUE TITLE
Month in the Date constructor is 0 indexed

### ISSUE THREAD

**Issue by faisalmuhammad** [angular/angular#18420]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When declaring a new Date, the month starts with 0 which is an unusual behavior I believe. The output in the html is displayed "15.01.1988". 

## Minimal reproduction of the problem with instructions

my.component.ts:      `private birthday = new Date(1988, 0, 15);`
my.component.html:  `<p>The hero's birthday is {{ birthday | date:"dd.MM.yyyy" }} </p>`

## What is the motivation / use case for changing the behavior?

The Date constructor should take the month variable starting from 1.

**Comment by pkozlowski-opensource** [comment]
`Date` is part of the ECMAScript standard, nothing to do with Angular: http://www.ecma-international.org/ecma-262/6.0/#sec-date-objects
