### ISSUE TITLE
Cannot enforce id on downgraded component

### ISSUE THREAD

**Issue by Javarome** [angular/angular#18446]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Any `id` set on downgraded component is [overwritten by the downgrade function](https://github.com/angular/angular/blob/master/packages/upgrade/src/common/downgrade_component.ts#L67).

For example when declaring:
```
<my-component id="my-id"></my-component>
```
The compiled output will be: 
```
<my-component id="NG2_UPGRADE_27_0"></my-component>
```

## Expected behavior
The user should be able to use the `id` of its choice, which will not be overwritten. Upgrade ids could be renamed as `ng2-upgrade-id="27_0"`. 

## Minimal reproduction of the problem with instructions

Declare a ng2 component in a ng1 module:
```
angular.module('myNg1module')
   .directive('myComponent', downgradeComponent({component: MyComponent}))
```
then use the component with an HTML id:
```
<my-component id="my-id"></my-component>
```

## What is the motivation / use case for changing the behavior?
Ability for the user to keep on using its existing ids, even on downgraded components.

Otherwise migration could require more significant rewriting of an existing app (to match another discriminator than the `id` in existing JS or CSS code).

## Environment

Angular version: 4.3.2

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
Others:
See [question and workaround on Stackoverflow](https://stackoverflow.com/questions/45432210/how-to-enforce-id-on-angular-2-downgraded-component)

**Comment by gkalpak** [comment]
This used to be necessary [back in the day][1], but not anymore (for a long time).
If anyone wants to take a stub at removing it, please do :smiley:

[1]: https://github.com/angular/angular/commit/cd90e6ed8f1118ce141b1dd41539ec2785482f20
