### ISSUE TITLE
Spy variable not initialised in Testing documentation, section "#spy-stub"

### ISSUE THREAD

**Issue by fardarter** [angular/angular#18447]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In Testing, at https://angular.io/guide/testing#spy-stub the 'spy' variable isn't initialised in the code example.

## Expected behavior

The 'spy' variable should be initialised to prevent compile errors.

## What is the motivation / use case for changing the behavior?

While it may seem obvious to many, for new coders being able to study working code is absolutely crucial and this code won't work from the snippet.

**Comment by petebacondarwin** [comment]
As far as I can tell this issue no longer exists.
