### ISSUE TITLE
After upgrading from Angular 2 to Angular 4 Router Resolve return type mismatch issue. 

### ISSUE THREAD

**Issue by lingarajsureban** [angular/angular#18449]
I have recently upgraded my Angular 2.0.1 application to Angular 4.2.2 version.
after up-gradation when I compile my application I am getting below mentioned errors and my application stopped working.

![image](https://user-images.githubusercontent.com/15012116/28826328-5db81416-76e7-11e7-8ad4-a3a6c26ee860.png)

the reason behind this error is in angular 3.0.0 router Resolve interface is like below
```
export interface Resolve<T> {
    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<any> | Promise<any> | any;
}
```

in Angular 4.XX angular/router Resolve interface is 

```
export interface Resolve<T> {
    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<T> | Promise<T> | T;
}
```

so, it was earlier returning **Any** and in the newer version it is returning **T**, due to this my application is not compiling.

Below is my implementation 

```
@Injectable()
export class TranslatedStringsResolver implements Resolve<TranslatedStringsService> {
    constructor(private translatedStringsService: TranslatedStringsService, private router: Router) {
    }
  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot):Promise<void> {
      console.debug("TranslatedStringsService TranslatedStringsResolver.resolve()");
    return this.translatedStringsService.init2();
  }
}
```

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I compile application getting below errors.
src\app\features\users\shared\user-data-resolvers.service.ts(31,14): error TS2420: Class 'AppRolesResolver' incorrectly implements interface 'Resolve<UserAPIService>'.
  Types of property 'resolve' are incompatible.
    Type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => Observable<AppRole[]>' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => UserAPIService | Observable<UserAP...'.
      Type 'Observable<AppRole[]>' is not assignable to type 'UserAPIService | Observable<UserAPIService> | Promise<UserAPIService>'.
        Type 'Observable<AppRole[]>' is not assignable to type 'Promise<UserAPIService>'.
          Property 'then' is missing in type 'Observable<AppRole[]>'.

src\app\features\accounts\account-list\account-list.component.ts(89,42): error TS2339: Property 'url' does not exist on type 'Event'.
  Property 'url' does not exist on type 'RouteConfigLoadStart'.

## Expected behavior
It should compile without any errors

## Minimal reproduction of the problem with instructions
Upgrade Angular 2 from Angular 4 and if you have used Resolve feature then it will break the compilation and throws the error

## What is the motivation / use case for changing the behavior?
If I degrade to @angular/router to the previous version 3.0.0 then application will work as expected

## Environment

<pre><code>
Angular version: 4.2.2

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by snood1205** [comment]
This was a major version change and was intended as a breaking change to the best of my knowledge.

**Comment by tytskyi** [comment]
@lingarajsureban `Resolve` interface should be of type what your `resolve` method returns.

` implements Resolve<AppRole[]>` `resolve(....): Promise<AppRole[]>` etc.

```typescript
@Injectable()
export class TranslatedStringsResolver implements Resolve<void> {
    constructor(private translatedStringsService: TranslatedStringsService, private router: Router) {
    }
  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot):Promise<void> {
      console.debug("TranslatedStringsService TranslatedStringsResolver.resolve()");
    return this.translatedStringsService.init2();
  }
}
```

**Comment by lingarajsureban** [comment]
Thanks @tytskyi , I tried your suggestion but still it is not working. I debugged the code to see whats happening and I found that execution never enters inside the resolve function only it hits class and exists immediate after that. not sure whats happening here, below is my code for **this.translatedStringsService.init2()**

```
@Injectable()
export class TranslatedStringsService {
     
    constructor(private i18n: TranslateI18Next,
                     private languageDetector: LanguageService) {

        console.debug("TranslatedStringsService constructor");
    }
    
    public init2( ):Promise<void> {
        console.debug("TranslatedStringsService init2()");
        return this.i18n.init({
            debug: false,
            returnEmptyString: false, 
            fallbackLng: 'en-us',
            browserLanguageDetector: this.languageDetector
        });
    }

    public translate( key:string):string {
        return this.i18n.translate(key);
    }
}
```

**Comment by vicb** [comment]
Yep this change was expected, you should fix your code.

**Comment by tytskyi** [comment]
@lingarajsureban sorry, i cannot help you further, since the change was suggested to fix compiler errors. But now there are some errors in the resolving mechanics which i do not have experience with.
