### ISSUE TITLE
Angular does not compile cleanly with TypeScript 2.4

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#18454]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

With stricter checking and improved type inference, TypeScript 2.4 now reports errors in Angular that are not reported in 2.3.

This also produces .d.ts files that are reported as errors by 2.4 as reported here:

  #17863
  #17522

## Expected behavior

Angular compiles cleanly with 2.4.

## Minimal reproduction of the problem with instructions

Upgrade TypeScript to 2.4 and run `build.sh`.

**Comment by danwulff** [comment]
Was this fixed with 4.3.4? https://github.com/angular/angular/pull/18456

**Comment by chuckjaz** [comment]
Not yet. There were a number of improvements but not all of the PRs have landed yet nor have all of them been merged with the 4.3.x branch.

**Comment by xnnkmd** [comment]
@chuckjaz Of all the planned features for newer versions of angular, this is really what I want the most. Any idea of when Angular will work with newest typescript (2.5 currently) ?

**Comment by kiwikern** [comment]
Typescript 2.4.2 is supported now with Angular 5

**Comment by xnnkmd** [comment]
Typescript 2.4.2 is yesterdays news by now....Now we just need typescript 2.6 support :-)

**Comment by chuckjaz** [comment]
We need a change to Tsickle to support both 2.4 and 2.5 for us to be able to shift our dependency to a version of Tsickle we can use. We are working on that now. Hopefully we should get this into this weeks release. If not it should be next week.

**Comment by chuckjaz** [comment]
BTW, this is only for 2.5 support. We are still working to valid 2.6.

**Comment by IgorMinar** [comment]
this is now obsolete
