### ISSUE TITLE
how to use modal of bootstrap in Angular 4? "bootstrap": "4.0.0-alpha.6"

### ISSUE THREAD

**Issue by preservance717** [angular/angular#18471]
how to use modal of bootstrap in Angular 4?
"bootstrap": "4.0.0-alpha.6"

**Comment by zh99998** [comment]
https://stackoverflow.com/a/39914246

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

You can use libraries that offer native, out of the box integration of Angular with Bootstrap 4, ex.: https://ng-bootstrap.github.io/#/components/modal/examples

**Comment by preservance717** [comment]
@pkozlowski-opensource thankyou
