### ISSUE TITLE
Word like text editor

### ISSUE THREAD

**Issue by mahitaande** [angular/angular#18472]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Hi, 
  I am looking for a text editor which offers MS word like features. Currently we are using Telerik RichTextBox, however since silverlight is not actively supported I am thinking of switching to another editor. Below link works only in IE.

http://demos.telerik.com/silverlight/#RichTextBox/TelerikEditor

The text editor should offer features like Rtf support ability, formatting options, customization.
Could you please suggest if there is another angular text editor control that offers word like features.

<pre><code>
Angular version: 1.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX

**Comment by Toxicable** [comment]
It looks like you're in the wrong repo.
This repo is for Angular, which is currently at version 4.3.2
here is the AngularJS repo https://github.com/angular/angular.js which is currently at version 1.6.5

**Comment by mahitaande** [comment]
Thank you for directing me to the angular js repo.

Though I am using Angular 1.3, I am open to using higher versions of angular including Angular 4.

Please let me know if there is a word like text editor with Angular 2 or Angular 4 or is this something I have to build from scratch myself.

Thanks.
