### ISSUE TITLE
Bind property for video src in component cause ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by dujuanxian** [angular/angular#18475]
```html
<video loop muted autoplay #videoPlayer>
    <source src='{{videoUrl}}' type="video/mp4">
</video>
```
```typescript
export class VideoComponent implements OnInit {
    videoUrl:string;
    ngOnInit() {
        this.videoUrl = 'https://www.w3schools.com/html/mov_bbb.mp4';
    }
}
```
Bind property value for video src cause this error:
`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'https://www.w3schools.com/html/mov_bbb.mp4'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?`

I tried to run change detection explicitly after the change, but still got this error
```typescript
ngAfterViewInit() {
    this.videoUrl = 'https://www.w3schools.com/html/mov_bbb.mp4';
    this.cd.detectChanges();
}
```

**Comment by ericmartinezr** [comment]
http://plnkr.co/edit/uUuZp9aNsx3wjNPTjPxF?p=preview it works perfectly fine.

**Comment by pkozlowski-opensource** [comment]
I agree with @ericmartinezr that it works well in a simple plunker and that the problem description sounds fishy. 

@dujuanxian please provide a plunker that reproduces the exact issue, otherwise it is not actionable and will be closed.

**Comment by dujuanxian** [comment]
Hi @ericmartinezr and @pkozlowski-opensource , sorry that it is not angular issue but wrapped with fullpage.js cause this issue in my codebase, sorry for wasting your time.
