### ISSUE TITLE
@angular/compiler-cli >= 4.2.0 (ngc) not generating metadata.json file

### ISSUE THREAD

**Issue by dominique-mueller** [angular/angular#18478]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
We use the Angular Compiler CLI (ngc) in combination with Rollup to generate the correct bundles for our (internal) Angular library, following the Angular Package Format documentation. And `@angular/compiler-cli` works as expected when used in version `4.1.3`, meaning that compilation works, sourcemaps are here, type definitions are getting generated correctly, and the `metadata.json` file gets generated.

Any newer version of `@angular/compiler-cli`, however, does *not* generate the `metadata.json` file (while everything else seems to work properly).

## Expected behavior
The `@angular/compiler-cli` should generate the `metadata.json` file on all versions / newer versions than `4.1.3`.

## Minimal reproduction of the problem with instructions
Trying to run `ngc -p tsconfig.json` in an Angular library project (e.g. https://github.com/dominique-mueller/angular-notifier) with the latest version of `@angular/compiler-cli` results in the problem described above.

Full tsconfig.json for ES5 build:
``` json
{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "./../../build/library-es5", // Result, without the metadata.json file
    "sourceMap": true,
    "stripInternal": true,
    "target": "es5"
  },
  "files": [
    "./../../build/library-inline/index.ts" // Library source (after inlining HTML templates)
  ],
  "angularCompilerOptions": {
    "flatModuleId": "@something/my-lib",
    "flatModuleOutFile": "my-lib.js",
    "genDir": "./../../build/library-es5-gen-dir",
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true
  }
}
```

## What is the motivation / use case for changing the behavior?
**This issue prevents us from from publishing a library using the latest and greatest version of Angular.** In addition, because in version `4.1.3` all Angular dependencies must exist in the same version (otherwise the build fails), this prevents us from using newer Angular features (such as the new HTTP client, amongst others).

## Environment
<pre><code>Angular version:
- Tested with 4.1.3 -- working as expected
- Tested with 4.2.0, 4.3.0 and the latest (4.3.2) -- broken
 
For Tooling issues:
- Node version: 7.10.0
- Platform:  Windows 7 & Windows 10
</code></pre>

**Comment by dominique-mueller** [comment]
Interestingly, most libraries out there - and this includes Angular Material - seem to stick to version `4.1.x` as well ... so maybe this is an already known issue?

**Comment by dinony** [comment]
I'm not sure if it is related, but I'm having [problems](https://github.com/dinony/od-virtualscroll/issues/14) creating fesm using ngc >=4.2.

**Comment by dominique-mueller** [comment]
Just discovered that, weirdly enough, Angular Material 2 seems to create the (nearly empty) metadata.json file manually. See https://github.com/angular/material2/blob/2320532516a113d39a1e1970d88c587156cbb914/tools/package-tools/metadata-reexport.ts#L5 for the code. Is this the recommended way of generating this file? If so, why is it nowhere documented? If not, is this a workaround?

I'm a bit confused right now ... would be nice to have a clear official guideline on how to setup a working build process for Angular libraries.

**Comment by dominique-mueller** [comment]
After analyzing https://github.com/dherges/ng-packagr, it seems that using @angular/tsc-wrapped works as expected. So probably an issue within @angular/compiler-cli wrapping around it?

**Comment by michaelbromley** [comment]
I've been looking into this issue, and isolated the issue to be when the `tsconfig.json` file is not in the project root.

I have put together a minimal reproduction here: https://github.com/michaelbromley/angular-issue-18478

**Comment by stevencohn** [comment]
After upgrading from Angular 4.4.6 to 5.0.0, the ngc compilation of a library we're building has changed drastically. The tsconfig has not changed; it specifies an outDir of something like "../mylib/out-tsc". Under 4.4.6, the ngsummary and ngfactory files were generated in the same directory as the source and the compiler output (.d.td, .js, .js.map, and .metadata.json) went to outDir.

Now under 5.0.0, all files go into "../mylib/out-tsc/src" including the ngsummary and ngfactory but the .metadata.json files are not created at all. In addition, a new folder "../mylib/out-tsc/node_modules" is created with a couple of modules - @angular/common and /core, @types, rxjs, and typescript.

I can't find any documentation that explains why this is different or how to control it if it can be controlled. 

Any thoughts would be greatly appreciated. If this isn't fully baked then we'll need to stay with  4.4.6 until this is resolved.

**Comment by dominique-mueller** [comment]
So, I've updated to Angular 5 and the `ngc` properly emits `metadata.json` files. I'd say we can close this issue then? If anyone else is having this issue, we could re-open if necessary.
