### ISSUE TITLE
Animation with route reuse strategy not working.

### ISSUE THREAD

**Issue by sathish94us** [angular/angular#18477]
Router transitions are not working if the component on which the animation is imposed is routed using route reuse strategy

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by sathish94us** [comment]
@ericmartinezr Angular animations of host are not working if the component is routed using route reuse.

`animations: [
    trigger('routeAnimation', [
      state('*', style({opacity: 1})),
      transition('void => *', [
        style({opacity: 1}),
        animate(0)
      ]),
      transition('* => void', animate(1000, style({opacity: 1})))
    ])
  ]
})
export class ImHomeComponent
{

  @HostBinding('@routeAnimation') routeAnimation = true;
  @HostBinding('style.display') display = "block";
  @HostBinding('style.position') position = "absolute";`

I think this is a bug with angular.

**Comment by Havock94** [comment]
+1 I have the same problem. Component animated correctly before it was reused by ReuseStrategy. Once I set the component to be reused, animations from and to the component stopped working.
