### ISSUE TITLE
Make Use case examples reachable from API Documentation

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/angular#18473]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There no way to get example use case for  `Class/Function/Decorator` from API documentation

## Expected behavior

There Should be a link from API Documentation to Tutorial/Fundamentals/Techniques section (maybe vise versa) To show example use cases

 ### Example 
[@HostListener Documentation](https://angular.io/api/core/HostListener) can have link to [this page](https://angular.io/guide/attribute-directives#respond-to-user-initiated-events)

## What is the motivation / use case for changing the behavior?

Most of times developers know that certain thing can help with some use case and they look up in API documentation but example use case can give insights on how to use it

**Comment by gkalpak** [comment]
Sounds reasonable. (PRs welcome :wink:)

**Comment by jenniferfell** [comment]
@petebacondarwin @jbogarthyde Maybe we can add a standard way to do this in the new API templates and associated style guide.

**Comment by jbogarthyde** [comment]
There is an `@see` tag that can be used to refer to relevant guides/guide sections, as well as to related API elements. I am recommending that people use it.

**Comment by jbogarthyde** [comment]
There is an `@see` tag that can be used to refer to relevant guides/guide sections, as well as to related API elements. I am recommending that people use it.

**Comment by jbogarthyde** [comment]
The new Angular API Reference Guidelines document the use of the `@see` tag, and provide explicit instructions for various kinds of links in API docs (to other API elements, to guides, or to external pages).

In addition, the new API reference templates provide the `@usageNotes` tag as a standard place to put syntax and use-case examples, and the guidelines explain how to incorporate appropriate examples, both inline in the doc comment, and by reference to an external code file with the <code-example> construct.
