### ISSUE TITLE
docs(aio) - yarn post-install failure due to --source-map not being provided in package.json

### ISSUE THREAD

**Issue by mattezell** [angular/angular#18488]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When performing 'yarn' as instructed in AIO master documentation, failure occurs with error in fs module (fs.js:641) on binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);.  Bubbled up error is "TypeError: path must be a string or Buffer".

## Expected behavior

'yarn' installs dependencies without error, including the execution of 'postinstall'.

## Minimal reproduction of the problem with instructions

Pull latest angular repo on Windows 7 machine and attempt to follow the instructions contained within aio\readme.md - beginning with simply running 'yarn'.

## What is the motivation / use case for changing the behavior?

Documentation should build using the documented build process.

## Environment

<pre><code>
Angular version: 4.3.1

For Tooling issues:
- Node version: 6.11.2  
- Platform:  Windows 7 x64

Others:

If you look at the package.json in angular/aio/ you will note that the 'postinstall' has a trailing --source-map, but that there is no output file specified for the --source-map flag for uglifyjs.  Removing the trailing --source-map allows for yarn install without error.  Providing a valid value for --source-map also results in a yarn install without error.

If you debug uglifyjs, --source-map without valid path ARGS.source_map comes through as truthy and so "if(SOURCE_MAP)" is active, though ARGS.source_map does not contain a valid path - hence the error.
</code></pre>

**Comment by gkalpak** [comment]
What version of `yarn` are you using? (I am guessing >=0.25.4 😛)

**Comment by mattezell** [comment]
Yarn Version: 0.27.5

**Comment by gkalpak** [comment]
This is due to a bug in yarn@>=0.25.4 that may install wrong versions in `node_mdules/.bin/`. It has been fixed with yarnpkg/yarn#3877 and should be included in the 0.28.1 release.

In the meantime, you need to use an older version. (We use 0.24.6.)

##
Closing since everything works as expected (as far as aio is concerned :grin:).

**Comment by mattezell** [comment]
You did see that the error isn't actually related to Yarn, right?  The actual error is related to the invalid postinstall, which passes --source-map arg to uglifyjs without actually providing the map path.

I've just installed 0.24.6 as directed and the issue continues.

**Comment by mattezell** [comment]
![image](https://user-images.githubusercontent.com/361409/28886075-c1913a44-777d-11e7-9a68-05542c6899c1.png)

**Comment by gkalpak** [comment]
If you remove `node_modules/` and install again using yarn 0.24.6 everything should work as expected.
The issue happens because yrn 0.27.5 has installed an older version of uglifyjs in `node_modules/.bin/` which has a different API (i.e. expects different command-line arguments).

**Comment by mattezell** [comment]
You da man! Thanks for the education, @gkalpak . 

I've blown away my node_modules and everything is exactly as you described now that I've reran yarn 0.24.6...

Bare minimum, I am hoping that others banging their head in frustration over this error stumble here to get a quick answer (as I couldn't find anything on this specifically last night or this morning) :) 

Thanks again for your assistance!
