### ISSUE TITLE
TypeError: Cannot read property 'component' of null

### ISSUE THREAD

**Issue by dgroh** [angular/angular#18481]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

We have the following route path:

**http://www.test.com/App/12/Customer/Products**

where **12** is the contract id of the customer. It's a valid id.

Once we pass an id, which does not exist, we show the default id, but then we get the following exception, even tho the app still works and is functional:

![image](https://user-images.githubusercontent.com/16785357/28873361-9f46769c-778d-11e7-82ec-0b72595749f9.png)

This happens in `app.component.ts` when navigating with: `this.router.navigate`

We do this navigation in the `ngOnInit`, because we need to retrieve the `contractId` of the current logged in user via `http get` and set this id in the router.

## Expected behavior
Not to have this error:

In:
`this.canDeactivateChecks.push(new CanDeactivate(outlet.component, curr));`

I also can not identify the origin of the error as it's not showing in the stack.

**Comment by dgroh** [comment]
Exact the same:

https://github.com/angular/angular/issues/3979

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by syqal** [comment]
Hi @dgroh ,
Are you able to find the root cause for this issue?

**Comment by bennadel** [comment]
I am also running into this issue -- I think it may be related to this ticket: https://github.com/angular/angular/pull/19374

**Comment by pramodsankarl** [comment]
Looks like this fix did not make it to 6.0.x, but a [similar one](https://github.com/angular/angular/pull/26496) made into 7.0.x
