### ISSUE TITLE
Angular 2 /4 Assign model value from loop index

### ISSUE THREAD

**Issue by saratonite** [angular/angular#18485]
I want to assign model value from the current loop index, but its not working . any idea about this

[Plunker](https://plnkr.co/edit/YccCBF98vCetWXJa1UJX?p=preview)

[please check](https://stackoverflow.com/questions/45461345/angular-2-4-assign-model-value-from-loop-index/45461442?noredirect=1#comment77885809_45461442)

**Comment by robwormald** [comment]
Please take support questions to gitter.im/angular/angular or StackOverflow.
