### ISSUE TITLE
Using Angular4 AOT...Stil we are not getting much benefit in initial page load execution

### ISSUE THREAD

**Issue by vijayKumar2017** [angular/angular#18498]
## Current behavior
Still it is taking 3 to 5 seconds to start execution after page loading

## Expected behavior
Using Ahead of Time compilation, Initial page load should be reduced

## Environment
Angular 4.1.2
angular-cli: "1.0.0-beta.28.3"

Browser:
-Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by snewell92** [comment]
Provide more information to make your issue actionable - also report your JIT vs AOT bundle sizes, as AOT is trying to hit a sweet spot with bundle size / page load optimizations (among other things too).

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
