### ISSUE TITLE
Control visibility [hidden] not work when div have .help-block class

### ISSUE THREAD

**Issue by ictgtvt** [angular/angular#18491]
## Control visibility [hidden] not work when div have .help-block class
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I used control visibility [hidden] for user's name field. But `span` element is alway shown. When I changed `.help-block` to something different like `.help-block1`, it work correctly.
```html
<input type="text"
class="form-control"
placeholder="Name"
[(ngModel)]="user.name"
name="name"
required #name="ngModel"/>
<span [hidden]="name.valid || name.pristine" class="help-block">
Name is required
</span>
 Name valid: {{ name.valid }}
```

## Expected behavior
I don't now why this happen. Is `.help-block` a preserved class name ?

## Environment

<pre><code>
Angular version: 4.3.2
Bootstrap
AdminLTE 2
Webpack 3

Browser:
- [x] Chrome (desktop) version 59.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.10.3 
- Platform:  Mac

</code></pre>
![incorrect](https://user-images.githubusercontent.com/8575747/28886867-2b7cd208-77e5-11e7-9dc2-5594f521c0d5.png)

**Comment by jnizet** [comment]
That's because the .help-block class has the `display: block` css rule, which overrides the hidden property (as per the spec). You can use ng-if, of use hidden on a span wrapping the .help-block.

**Comment by ictgtvt** [comment]
@jnizet I got it. Thank you so much :)
