### ISSUE TITLE
Unit testing HttpClientModule: undefined return value from HttpTestingController.expectOne(url)

### ISSUE THREAD

**Issue by supdegrave** [angular/angular#18499]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
This issue is copied from my [recent question on StackOverflow](https://stackoverflow.com/questions/45446680/unit-testing-httpclientmodule-in-angular-4-3-undefined-return-value-from-httpte). I'm honestly not sure if this is a bug report or a documentation issue. 

I'm trying to understand how to use the mocking functionality provided as part of the new `HttpClientModule`. My test code (as shown in minimal repro, below) matches what's shown in the existing documentation almost exactly. However, the doc example is not complete - for example, at a minimum the import statement for `TestBed` and `inject` is missing. I assume the same is true of `HttpClient` from @angular/common/http. My test code adds these.

This test fails, as req ends up being undefined after the `httpMock.expectOne` call. I'd appreciate any insight into why that might be.

## Expected behavior
I expect the unit test to pass successfully as stated in the [HttpClient documentation](https://github.com/angular/angular/blob/master/aio/content/guide/http.md).  

## Minimal reproduction of the problem with instructions
```typescript
import { TestBed, inject } from '@angular/core/testing';
import { HttpClient } from '@angular/common/http';
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';

describe('HttpClientTestingModule', () => {
  beforeEach(() => TestBed.configureTestingModule({
    imports: [ HttpClientTestingModule ],
    providers: [ HttpClient, HttpTestingController]
  }));

  it('expects a GET request', inject([HttpClient, HttpTestingController], (http: HttpClient, httpMock: HttpTestingController) => {
    http
      .get('/data')
      .subscribe(data => expect(data['name']).toEqual('Test Data'));

    const req = httpMock.expectOne('/data');
    expect(req).toBeDefined();
    expect(req.request.method).toEqual('GET');
    req.flush({name: 'Test Data'});
    httpMock.verify();
  }));
});
```

## What is the motivation / use case for changing the behavior?
`HttpTestingController` should work as documented. Alternately, the documentation should be updated to contain a complete example, if it does in fact work but there's something missing from the code sample above. 

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by supdegrave** [comment]
I got it working, by removing the following from `TestBed.configureTestingModule`: 

`providers: [ HttpClient, HttpTestingController]`

**Comment by jnizet** [comment]
> Why do I need to add my own LogonUserService to the providers collection, but not HttpClient, HttpTestingController

Because this line:

    imports: [HttpClientTestingModule],

adds these providers to the module for you. The HttpClientTestingModule already adds the provider for HttpTestingController, and, since it itself imports HttpClientModule, it also adds the provider for HttpClient. See https://github.com/angular/angular/blob/master/packages/common/http/testing/src/module.ts.

**Comment by supdegrave** [comment]
Thanks @jnizet, that makes sense.
