### ISSUE TITLE
Same error occuring over and over in hero.service.ts Tour of Heroes tutorial

### ISSUE THREAD

**Issue by vkalfieri** [angular/angular#18501]
keep running across this error when trying to compile after reaching the end of Routing section of Tour of Heroes tutorial on angular.io

this is after I have followed the examples in the live example page, and triple checked to make sure I didn't miss any code from what is written there.....

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,11): ',' expected.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,20): ';' expected.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (14,12): ':' expected.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (15,68): ',' expected.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,1): Cannot find name 'getHero'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,9): Cannot find name 'id'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,13): 'number' only refers to a type, but is being used as a value here.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,22): Operator '<' cannot be applied to types 'PromiseConstructor' and 'typeof Hero'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,22): Operator '>' cannot be applied to types 'boolean' and '{ return: any; }'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (15,64): Cannot find name 'id'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero-detail.component.ts (25,38): Expected 0 arguments, but got 1.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero-detail.component.ts (26,24): Type '{}' is not assignable to type 'Hero'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero-detail.component.ts (26,24): Type '{}' is not assignable to type 'Hero'.
  Property 'id' is missing in type '{}'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/app-routing.module.ts (9,42): Type '({ path: string; redirectTo: string; pathmatch: string; } | { path: string; component: typeof Das...' is not assignable to type 'Route[]'.
  Type '{ path: string; redirectTo: string; pathmatch: string; } | { path: string; component: typeof Dash...' is not assignable to type 'Route'.
    Type '{ path: string; redirectTo: string; pathmatch: string; }' is not assignable to type 'Route'.
      Object literal may only specify known properties, and 'pathmatch' does not exist in type 'Route'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero-detail.component.ts (25,38): Expected 0 arguments, but got 1.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero-detail.component.ts (26,24): Type '{}' is not assignable to type 'Hero'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero-detail.component.ts (26,24): Type '{}' is not assignable to type 'Hero'.
  Property 'id' is missing in type '{}'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,11): ',' expected.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,20): ';' expected.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (14,12): ':' expected.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (15,68): ',' expected.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,1): Cannot find name 'getHero'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,9): Cannot find name 'id'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,13): 'number' only refers to a type, but is being used as a value here.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,22): Operator '<' cannot be applied to types 'PromiseConstructor' and 'typeof Hero'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (13,22): Operator '>' cannot be applied to types 'boolean' and '{ return: any; }'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/hero.service.ts (15,64): Cannot find name 'id'.

ERROR in C:/Users/phant/Desktop/angular-tour-of-heroes/src/app/app-routing.module.ts (9,42): Type '({ path: string; redirectTo: string; pathmatch: string; } | { path: string; component: typeof Das...' is not assignable to type 'Route[]'.
  Type '{ path: string; redirectTo: string; pathmatch: string; } | { path: string; component: typeof Dash...' is not assignable to type 'Route'.
    Type '{ path: string; redirectTo: string; pathmatch: string; }' is not assignable to type 'Route'.
      Object literal may only specify known properties, and 'pathmatch' does not exist in type 'Route'.
webpack: Failed to compile.

**Comment by vkalfieri** [comment]
trotyl - why thumbs down? it's an issue, i raised it, i don't see any reason to gimme a thumbs down....

**Comment by trotyl** [comment]
Please checkout https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submission-guidelines .
