### ISSUE TITLE
--prod: Property 'StatusType' does not exist on type 'StatusComponent'.

### ISSUE THREAD

**Issue by dgroh** [angular/angular#18506]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
building the app with `--prod` causes the following error when using enum type in `ngSwitchCase`

> Property 'StatusType' does not exist on type 'StatusComponent'

## Minimal reproduction of the problem with instructions

Create the following enum:

```ts
export enum StatusType {
    manuell = 10,
    unbestaetigt = 20,
    bestaetigt = 30,
    abgelehnt = 40
};
```

Create a template like this:

```html
<div [ngSwitch]="status?.id" >
  <span *ngSwitchCase="StatusType.manuell">bestätigt<i class="icon-status_aktiv"></i></span>
  <span *ngSwitchCase="StatusType.unbestaetigt">offen<i class="icon-status_beantragt"></i></span>
  <span *ngSwitchCase="StatusType.bestaetigt">bestätigt<i class="icon-status_aktiv"></i></span>
  <span *ngSwitchCase="StatusType.abgelehnt">abgelehnt<i class="icon-status_abgelehnt"></i></span>
</div>
```

then run `ng build --prod`

For now, the workaround we are using is to set the enums in public properties in our typescript component file:

```ts
@Component({
  selector: "app-status",
  templateUrl: "./status.component.html",
  styleUrls: ["./status.component.scss"]
})
@StatusTypeDecorator
export class StatusComponent {
  @Input() public status: Status;

  public manuell: StatusType = StatusType.manuell;
  public unbestaetigt: StatusType = StatusType.unbestaetigt;
  public bestaetigt: StatusType = StatusType.bestaetigt;
  public abgelehnt: StatusType = StatusType.abgelehnt;
}
```

**Comment by pkozlowski-opensource** [comment]
> Property 'StatusType' does not exist on type 'StatusComponent'

This is correct - you never expose `StatusType` as a _property_ of your components and templates are evaluated against component _instances_.

**Comment by dgroh** [comment]
In development mode is this error not to be expected? 

Is the workarounf then a correct solution?
