### ISSUE TITLE
using relative path for import, shows error but run well

### ISSUE THREAD

**Issue by yutsengwei** [angular/angular#18503]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/13085558/28914136-3105f47e-786d-11e7-820a-7f0a9090ae6d.png)

I am using relative path for import, the problem is when it needs to be declare on Component or DI to Component(other situations seems ok), always show Error like the picture "Could not resolve @app.animations relative to blabla....."
if DI, it will show Error and the description is question mark in that parameter.
![image](https://user-images.githubusercontent.com/13085558/28915024-52abcba0-7870-11e7-8588-fd7af9fe04bd.png)

actually, it runs well, even I did build --prod, no error show on the terminal, but show error on the screen
## Expected behavior

No error pop.

## Environment
my tsconfig.js looks like this
<pre>
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "paths": {
      "@app.animations":["app/app.animations.ts"]
    },
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
<code>
Angular version: 4.2.1

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

Others:

</code></pre>
WebStorm

**Comment by vicb** [comment]
This is an issue with WebStorm, not Angular.
