### ISSUE TITLE
Custom uppercase directive - Undo action (ctrl + z) issue in IE Version 11 & Edge Browser

### ISSUE THREAD

**Issue by deepak-pd** [angular/angular#18507]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have written a simple uppercase directive to convert all input field values to upper case. Everything works as expected, but in IE 11 & Edge browser, the undo action i.e ctrl + z has unexpected behavior.
 
In case of an input box, the undo action duplicates the characters.
In case of textarea, the undo action converts the characters back to lower case.

## Expected behavior
The undo action should ideally clear the previous characters. This works fine in Chrome browser.
Now I am not sure if this is an issue with Angular or IE browser itself.

## Minimal reproduction of the problem with instructions
I have created a plunker depicting the issue. Please open the below url in IE11 or Edge browser.
https://plnkr.co/edit/371y5kTC6HZRdGr9Dfz2?p=preview

Type in characters in either the input box or textarea and perform (ctrl + z) keyboard action in order to reproduce this issue.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [x] Edge version 25.10586.672.0

**Comment by vicb** [comment]
> Now I am not sure if this is an issue with Angular or IE browser itself.

Could you try without Angular and report ?

**Comment by deepak-pd** [comment]
I tried using jQuery and the issue still persists without Angular. Please have a look at fiddle below:
http://jsfiddle.net/MupXZ/6/

So it means that this is IE browser issue only? Any possible work around you can think of?

**Comment by deepak-pd** [comment]
Okay I solved this issue another way where I don't update DOM as I type but transform it to uppercase using CSS text transform property. However I convert the model value to uppercase.

Here is a plunker for anyone facing similar issue:
https://plnkr.co/edit/1eF3MDSjDTTdNPhoRMvQ?p=preview

Closing this issue as it isn't Angular related.
