### ISSUE TITLE
router-link does not support baseHref

### ISSUE THREAD

**Issue by rkirov** [angular/angular#1850]
The following html
`</router-outlet><a router-link="foo">link</a>`
and config 
```
const {
  'path': 'foo',
  'component': FooCmp,
  'as': 'foo'
}
```
with baseHref `/hello/web` should generate href `/hello/web/foo`, while it generates `/foo` right now.

Similarly `router.navigate('foo')` (router injected into the given component) should act like clicking on that anchor tag.

**Comment by btford** [comment]
Clarification:
```
const {
  'path': 'foo',
  'component': FooCmp,
  'as': 'bar'
}
```

you want to be able to do `router.navigate('bar')`, or `router.navigate('foo')` ? Right now, I assume `navigate` takes a URL.

**Comment by rkirov** [comment]
Right, so for now `router-link` takes component aliases and params, but `navigate` takes urls. Maybe we should make this more explicit by `navigateUrl` and `navigateComponent(componentSymbol or alias, params) .`

For now lets' keep `navigate` taking Url, so `router.navigate('foo')`

**Comment by btford** [comment]
SGTM.

**Comment by IgorMinar** [comment]
I'm unclear about whether this is fix or not. A PR that seems to be fixing the issue was merged already.

**Comment by btford** [comment]
This is fixed in master. Here's a test that proves it: https://github.com/angular/angular/blob/master/modules/angular2/test/router/outlet_spec.ts#L129
