### ISSUE TITLE
Provide a tool that populates AnnotationMatcher settings

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#1851]
Provide a standalone tool users can run to detect custom implementations of `Injectable`, `Directive`, `Component`, and `View` and update `pubspec.yaml` with the appropriate information.

See PR https://github.com/angular/angular/pull/1772 and issue https://github.com/angular/angular/issues/1750 for additional context

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
