### ISSUE TITLE
 async / @input start when data received

### ISSUE THREAD

**Issue by GoNode5** [angular/angular#18512]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

@Component({
  selector: 'my-app',
  template: `
    <div>
      <my-people [people]="people | async"></my-people>
    </div>
  `,
})
export class App {

@Component({
  selector: 'my-people',
  template: `
    <div *ngFor="let person of people">
      {{ person.twitter.name }}
    </div>
  `,
})
export class PeopleComponent {
  
  @Input() people;

*ngFor is used as  guard  ('hack?') until the data arrives

## Expected behavior
I think the responsibility shouldn't be in the html/template but in the component.
Something like, just and idea: @ InputWait it should any act when data is received.

## What is the motivation / use case for changing the behavior?
Less responsibility in html

**Comment by ericmartinezr** [comment]
Look at https://github.com/angular/angular/issues/5689
