### ISSUE TITLE
how to create a scroll of components?

### ISSUE THREAD

**Issue by lukecorf** [angular/angular#18511]
Well... I have a ngFor in my code and I need to create a scroll of itens in this ngFor. But I do not want other components to have scrool too. I need they fixed. look:
```
    <div class="row">
          <img src="https://image.flaticon.com/icons/png/512/56/56763.png" (click)="changeOpt()" alt="" class="menu-bar" width="30px">
    </div>
    <div class="row">
        <div class="col-md-6">
            <h2>Notificação</h2>
            blkasdlkfjaslkjfdlkasjflkasjkldfjlaskjdflaskjdf
        </div>
        <div class="col-md-6 materias-css">
            <disciplina-perfil *ngFor="let item of materias" [nome]="item.nome" [status]="item.status" [professor]="item.professor" [proxProva]="item.proxProva" [img]="item.img" [falta]="item.falta" [nota]="item.nota" >
            </disciplina-perfil>
        </div>
    
    </div>`

```
I need a scroll for disciplina-perfil but the others need stay fixed

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
