### ISSUE TITLE
angular2 loadChildren children navigate?

### ISSUE THREAD

**Issue by neo-hu** [angular/angular#18524]
```
const routes: Routes = [
    { path: 'a1', loadChildren: 'app/a1/a1.module'},
];


#A1Module 

@NgModule({
  imports: [
    CommonModule,
    A1RoutingModule
  ],
....
})
export default class A1Module { }


#A1RoutingModule
const routes: Routes = [
    { path: '', component: A1Component,
    children: [
    {
        path: ':id',
        outlet: 'detail',
        component: A1DetailComponent
      },
    ]
  }
];
export default RouterModule.forChild(routes);
```

this.router.navigate(['a1', {'outlets': {'detail': [1]}}], {'queryParamsHandling': 'merge'}) ERROR?

How do I use the navigate jump page?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
