### ISSUE TITLE
Binding to a large array makes change detection very slow

### ISSUE THREAD

**Issue by aminpaks** [angular/angular#18525]
## I'm submitting a...

<pre><code>[x] Bug report  
[x] Feature request
</code></pre>

## Current behavior
Passing arrays with more than one million elements as an `@Input` binding makes the whole change detection mechanism very slow.

## Expected behavior
Either change detection should work flawlessly, or if the process costs too much there must be an option to specify how to check the changes, maybe we can turn off detection in this case and not detect any changes for that specific input after it's set.

## Minimal reproduction of the problem with instructions
Open [this example](http://embed.plnkr.co/TzjkbxIShyfofQpKi6yS/) and observe.
Note that `Small List` button will set `1000` elements to the Array and the performance will become 10 times faster.

## What is the motivation / use case for changing the behavior?
In large applications there are cases that developer needs to be in charge of controlling every single part of the application. Even though Angular ships with lots of good features and it's a great framework, sometimes the closed mechanism of doing things in its ecosystem makes it difficult to scale.

I hope you understand the motivation.

Thanks in advance.

## Environment

<pre><code>Angular version: 4.3.3

Browser: All 

For Tooling issues:
- Node version: 7.10.0  
- Platform:  macOS Sierra
</code></pre>

**Comment by mlc-mlapis** [comment]
@aminpaks ... use `OnPush` strategy on the component ... your actual plunker doesn't have a sense from a real point of view.

**Comment by dawidgarus** [comment]
You can use observable. Here's example with `observable` pipe for convenience:
https://plnkr.co/edit/vQnQmfkcgfGSlC9lRAi7
It will only detect changes in object identity, not content.
You can also use operators like `take(1)` to stop change detection for specific input.

**Comment by vicb** [comment]
There are multiple ways to solve your issue some of which described in the comments above.

Hard to give a "right" response without a real world use case.

**Comment by aminpaks** [comment]
@mlc-mlapis `OnPush` couldn't fix this issue.
@vicb I'm a bit surprised. If this is a limitation that framework cannot handle directly or either it's recommended to handle it with observable then it has to be documented somewhere along with `@Input` docs!
BTW it doesn't matter if there is no real world use case, the fact that it doesn't work as it should is enough.

**Comment by mlc-mlapis** [comment]
@aminpaks ... how so? This the example what I meant ... https://plnkr.co/edit/P0BCfz

Because of `OnPush` and changes invoked by `setInterval` ... no @Input change ... it is necessary to call `markForCheck()` in the `setInterval`.

**Comment by aminpaks** [comment]
@mlc-mlapis You changed the type of `@Input`. Sorry but your example is not practical, it's a workaround!

**Comment by mlc-mlapis** [comment]
@aminpaks ... this is how `OnPush` works! It's based on a change to object ref.

**Comment by aminpaks** [comment]
@mlc-mlapis I totally understand what you're doing, but this is not the answer I'd accept. Angular is a very good framework, and I'd like to work with `Observable` instead. But your example makes things complicated and it's not practical.

Thanks for your time.

**Comment by mlc-mlapis** [comment]
@aminpaks ... in your original code you pass a big array through `@Input`. Because you also use global (default) ChangeDetection = the whole app is checked then even the primitive big array is checked for a change. It's evident that there is a difference between checking a big and a small array. So what do you expect?

Just the right concept is to eliminate the checking of the big array on each CD cycle. And this is what `OnPush` is doing.

**Comment by aminpaks** [comment]
@mlc-mlapis The part I don't understand is why the change detection works this way. I passed down a list to one component why the whole detection became slow. We are not changing the reference of the input object.

**Comment by mlc-mlapis** [comment]
@aminpaks ... but you are because the BIG ARRAY is the primitive data type and for this the reference is always changed when passed through ... it is JavaScript thing ... you cann't change it. It is the same as if you pass `{myArray: [0,1,2]}` directly as value instead of passing a ref to the variable to which you store the object first.

**Comment by mlc-mlapis** [comment]
@aminpaks ... but you are because the BIG ARRAY is the primitive data type and for this the reference is always changed when passed through ... it is JavaScript thing ... you cann't change it. It is the same as if you pass {myArray: [0,1,2]} directly as value instead of passing a ref to the variable to which you store the object first.

**Comment by aminpaks** [comment]
@mlc-mlapis Big array is primitive data type!? You mean it won't happen if I fill the array with Objects?

**Comment by mlc-mlapis** [comment]
@aminpaks ... exactly.

**Comment by aminpaks** [comment]
@mlc-mlapis Sorry but you're confused, I updated [the example](https://embed.plnkr.co/TzjkbxIShyfofQpKi6yS/) to demonstrate this issue with array of `object`s

**Comment by aminpaks** [comment]
This is not javascript, it's the Angular's change detection works.

**Comment by mlc-mlapis** [comment]
@aminpaks ... I looked around Angular code and it really looks like that the array (and it is not important what data type ... if number, string or object) on `@Input` is really processed as a trivial value and comparison is done on it against the previous value -> and it is the reason why it is so slow on a big array.

The code around the change detection is really complicated and there are probably real reasons why `arrays` are processed by that way. So `OnPush` works on `objects` but not on `arrays`.

**Comment by aminpaks** [comment]
@mlc-mlapis This is inconsistent and lead to misunderstanding, needs documentations. I'd like to know why Arrays and Objects are treated differently. On the other hand if all `@Input`s are being processed with a simple refrence check this shouldn't happen, would you show me where is this in code?

**Comment by aminpaks** [comment]
As far as I know if they keep the reference of previous value and check with that this should not happen:
```js
let list = []
for (let x = 0; x < 1000000; x++) list.push({ id: x });
let list2 = list;
console.log(list2 === list); -> true, and it takes less than 0.01 milliseconds for JS to get this done!
```

**Comment by aminpaks** [comment]
And another comment about `OnPush`, to me it has to work with all type of JavaScript variables (arrays, objects, primitives and so on). That's its only job no?

**Comment by mlc-mlapis** [comment]
@aminpaks ... the line as `let list2 = list` just saves a reference to another variable (it's not a deep copy) and `list2 === list` compares just 2 references ... all of that is very fast = no problem.

But arrays are mutable by default so Angular CD checking compares the elements' value of both arrays to decide if they are the same or not. If the mechanism would check just their references as on objects then it would be very fast also.

As I can imagine `OnPush` can work just with the references because `the reference` is the additional information on which the decision is done ... on objects it is the rule that if the actual and previous references are the same then the object is also the same (without any comparison of their deep internal structures).

All ES6 primitives data types (string, number, boolean, null, undefined, symbol) are immutable and are stored on the stack.

**Comment by aminpaks** [comment]
> But arrays are mutable by default so Angular CD checking compares the elements' value of both arrays to decide if they are the same or not. If the mechanism would check just their references as on objects then it would be very fast also.
Based on your explanation your statement confused me again! I thought Angular change detection only checks for reference of values, no matter what is the type of input.
And checking for all the elements of an input array is a bad idea. I completely disagree with this, I thought they don't, cause that should not be up to framework! This has to be an option for developer to decide if they wanna double check for deep comparison!!!
And note on your explanation about `OnPush`. As far as I understand (waiting for you to point me to the right place to read the source code) it checks if the variable type is an object it won't go further but for arrays it checks all the contained elements, is that right?

**Comment by mlc-mlapis** [comment]
@aminpaks ... as I actually understand then yes ... this is the difference between arrays and objects with `OnPush` strategy. I have not exact explanations why arrays are processed by that way. (There is still another option ... using observable on `@Inputs`.)

> And note on your explanation about OnPush. As far as I understand (waiting for you to point me to the right place to read the source code) it checks if the variable type is an object it won't go further but for arrays it checks all the contained elements, is that right?

**Comment by mlc-mlapis** [comment]
@aminpaks ... and it is also true that `objects` are mutable also as default behaviour. So there should some other reasons why arrays are not taken by the same way as objects.

**Comment by aminpaks** [comment]
@mlc-mlapis exactly, that's why I was expecting an explanation to this behavior!

**Comment by mlc-mlapis** [comment]
@aminpaks ... it's funny because I found out that originally `OnPush` on array `@Input` should behave by the same way as `OnPush` on object `@Input` -> just comparing the references. So either there is something wrong with the plunker we are disussing or there is really a bug.

**Comment by aminpaks** [comment]
@mlc-mlapis Nice! I don't think there's anything wrong with the plunker, the source is clear, there is literally nothing complicated in that code. It has to be a bug.

**Comment by mlc-mlapis** [comment]
@aminpaks ... so we have the explanation already ... thanks to @ghetolay 👏 

This is the code: https://plnkr.co/edit/5eXlJo?p=preview that works correctly even for arrays. The reason?

Angular really tests the mutability on `@Input`. But ... the important is the difference between DEV and PROD mode. If it runs in DEV mode then ` ExpressionChangedAfterItHasBeenCheckedError` is checked after the CD cycle to avoid changing `@Input` during one CD cycle. It looks that inputs for iterable are not checked by reference but by values. This checking is not run in PROD mode.

`export function areIterablesEqual(a: any, b: any, comparator: (a: any, b: any) => boolean)`:
https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/core/src/change_detection/change_detection_util.ts#L89

**Comment by aminpaks** [comment]
@mlc-mlapis This is even worse than a bug if it's a design! This makes no sense to me at all, what happens if developer is working with big lists in DEV mode then? They should turn PROD mode on? WOW!
Honestly it's very discouraging, I'd go with Observables!

**Comment by mlc-mlapis** [comment]
@aminpaks ... yes, for this type of very big arrays, Observable looks like to be a good choice. Or `object @Input`  with a property that contains that big array ... as we discussed above.

It is also true that checking `ExpressionChangedAfterItHasBeenCheckedError` is not possible to do without comparing of all values so ...

**Comment by ericmartinezr** [comment]
>what happens if developer is working with big lists in DEV mode then?

A smart developer will work with a small list. If the dev has to handle a lot of data it will google "pagination" or "virtual/infinite scroll"

**Comment by aminpaks** [comment]
> A smart developer will work with a small list. If the dev has to handle a lot of data it will google "pagination" or "virtual/infinite scroll"

Building a pagination requires to pass all the items and splice them in there. If you mean lazy load them that's another story.

**Comment by aminpaks** [comment]
I'm actually building a virtual scroll, that I ended up finding this issue!!!

**Comment by AvishekNath** [comment]
Very informative conversation. Keep it up!!
