### ISSUE TITLE
Animation background color changes for state when using *

### ISSUE THREAD

**Issue by amaino** [angular/angular#18522]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
This was working for angular 4.1 but is now broken in later versions. We use a pulse animation looping back and forth between two states. The first state uses * to grab the current background color and then fades to the second state that is white it then loops back to the first state and so forth. Previously the color would be kept on the first state but now it is updated to white so the color stays white for the whole animation 

## Expected behavior
Be the same as in 4.1

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/AXzKGgDR9ZHiAQDBCB89
Change to a higher version and see that the loop does not work anymore, click the button to start the animation

## What is the motivation / use case for changing the behavior?
To be able too loop an animation without knowing the color from the beginning.

<pre><code>
Angular version: >4.1
</code></pre>

**Comment by matsko** [comment]
Looks like it's working on Angular master as of now. Please reopen if it's still an issue.
