### ISSUE TITLE
AbstractControlDirective is missing the status property

### ISSUE THREAD

**Issue by BioPhoton** [angular/angular#18526]
## I'm submitting a...

<pre><code>
[x] Bug report  
[x] Feature request
</code></pre>

## Current behavior
I'm extending the AbstractControlDirective to create custom once. 
This class provides i.e. value and valueChanes but only statusChanges and no sstatus property.
For me this looks like a missing/incomplete api.

## Expected behavior
I would see the status getter also in this class. For me it feels incomplete.

## Minimal reproduction of the problem with instructions
No reproduction because it it just an api change request.
But take a look at the provided functions: https://github.com/angular/angular/blob/5293794316cc1b0f57d5d88b3fefdf6ae29d0d97/packages/forms/src/directives/abstract_control_directive.ts#L45

## What is the motivation / use case for changing the behavior?
I want to have a complete reasonable api of the AbstractControlDirective class

## Environment

<pre><code>
@angular/cli: 1.2.2
node: 6.11.1
os: win32 x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.2
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1
 
</code></pre>

**Comment by Toxicable** [comment]
can be closed, fixed via #18539

**Comment by BioPhoton** [comment]
Thx @Toxicable !!
