### ISSUE TITLE
Form Validator.maxLength no error message

### ISSUE THREAD

**Issue by calcelli** [angular/angular#18537]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The form validation maxLength does not display a message

## Expected behavior

The form validation maxLength should display a message

## What is the motivation / use case for changing the behavior?
Let the user know when the form is valid

## Environment

<pre><code>
Angular version: 4.2.5

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: 6.11 
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
Works fine here https://stackblitz.com/edit/angular-max-length-exmaple
enter 3 characters and you'll see the error

**Comment by kara** [comment]
Yeah, it looks like this is working as intended. If you are still having issues with it, feel free to open a new issue with a code repro.
