### ISSUE TITLE
Add support for clearing FormArray

### ISSUE THREAD

**Issue by wanton7** [angular/angular#18531]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Current way of clearing FormArray
```
while (rows.lenght) {
  rows.removeAt(0);
}
```

## Expected behavior

```rows.length = 0;```

## Environment

<pre><code>
Angular version: 4.3

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KostyaTretyak** [comment]
Check this way:
```ts
rows.controls.splice(0)
```

**Comment by sinedsem** [comment]
+1

**Comment by renanmontebelo** [comment]
> Check this way:
> 
> ```ts
> rows.controls.splice(0)
> ```

As per https://angular.io/api/forms/FormArray#adding-or-removing-controls-from-a-form-array this is not recommended.

**Comment by KostyaTretyak** [comment]
> As per [Adding or removing controls from a form array](https://angular.io/api/forms/FormArray#adding-or-removing-controls-from-a-form-array) this is not recommended.


@renanmontebelo, yes, you are right. Now I am not recommended this way.

If we look at the [source of removeAt() method](https://github.com/angular/angular/blob/7.2.7/packages/forms/src/model.ts#L1683-L1687), we can see that for properly way needed to use not only `controls.splice()`.

**Comment by renanmontebelo** [comment]
As of Angular 8+ please use:

`formArray.clear();`

For previous versions the recommended way is 

```
while (formArray.length) {
  formArray.removeAt(0);
}
```

**Comment by trotyl** [comment]
@renanmontebelo `Array`s are in consecutive memory, removing first element costs `O(n)`, and the `while` loop becomes `O(n^2)`, better to remove at end.

**Comment by renanmontebelo** [comment]
@trotyl you're absolutely right, thank you for suggestion. I updated my comment based on your feedback.

**Comment by rammaradolla** [comment]
While loop will take long time to delete all items if array has 100's of items. You can empty both controls and value properties of FormArray like below.

clearFormArray = (formArray: FormArray) => { 
  formArray.controls = [];
  formArray.setValue([]);
 }

**Comment by santoshyadav198613** [comment]
Clear function is already added in angular 8. We will update the doc to showcase.
