### ISSUE TITLE
ViewProviders are not overridden by TestBed configuration

### ISSUE THREAD

**Issue by Karankang007** [angular/angular#18534]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
I have a component which uses a service as its view provider. This component can have sub components or can be used as a child component of another component.
[component.ts](https://gist.github.com/Karankang007/5f0facd761b2bd6f760bda1ca9ba83c8)

Currently, I am trying to unit test this component using karma and jasmine. The spec is as follows:
[componentSpec](https://gist.github.com/Karankang007/7e36e846facc983c45229a1e18d7ae9c#file-expandpanelcomponentspec)

Even though i am providing a mocked providers for my service, angular still uses the real service in tests when creating this component. Using TestBed.overrideComponent with viewProviders also produces the same result.

## Expected behavior
Mocked provider should be applied to view providers as well.

## Minimal reproduction of the problem with instructions
- Create a component with viewProviders
- Mock the provider using TestBed.configureTestingModule configuration
- See that the mocked instance of the provider does not get used during component initialization

## Environment

<pre><code>
Angular version: 4.3.1
Karma: 1.4.1
Jasmine: 2.6.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1
- NPM version: 3.10.10
- Platform:  Windows

</code></pre>

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

If you still feel this is an issue, please create an isolated reproduction of your use-case in [StackBlitz](http://stackblitz.com) and create a new issue.
