### ISSUE TITLE
Support arbitrary number of bindings per ElementInjector

### ISSUE THREAD

**Issue by natebosch** [angular/angular#1853]
# Goal

- remove the limit of 10 bindings per ElementInjector
- Keep the field optimization for sub 10 bindings

# Implementation

Currently the `ElementInjector` uses fields rather then hash map to look up bindings. This is because field reads are faster then hash reads. The break even number is somewhere around 17 fields, where reading Map is faster than linear search on the fields. 

Currently the limit is hard coded to 10 fields, this gives us speed and memory consumption savings. I don't think we should change that limit. Instead we should have a second strategy:

# Large ElementInjector Strategy

If the number of bindings is larger then the hard coded slots we should instead switch to Array strategy where we look up items in the Array rather then linear field search. (Note we completely switch, i.e. don't search fields and fallback to Array, just use Array immediately for large binding sets)

We can store the Array of instances in `ElementInjector` and Array of bindings in the `ProtoElementInjector`. See [Injector Array strategy](https://github.com/angular/angular/blob/5c88f662cd322bd1b3e9b187978f6cfa2906e286/modules/angular2/src/di/injector.ts#L70)

NOTE: Sparse arrays are slower then full Arrays in JavaScript. So we have to create a full array with unused fields set to null. We can further shrink the array by getting the min/max Key.id from all of the bindings. (Assuming that the spread is low, this can produce further savings.)

# Original Tex

We are bumping up against the 10 directive limit on elements in our angulardart app. Since this limit also exists in angular2 we're going to continue to see problems after we migrate.

Most elements have fewer than 10 directives, but some elements are bottlenecks and end up needing to set a lot of context for their children. We've been doing this by having a decorator for each piece of data (some of those decorators bind additional values which count against the directive limit).

**Comment by mhevery** [comment]
@vsavkin please help @vicb with implementation details.

**Comment by vicb** [comment]
I should have something soon (most probably tomorrow).

I have one issue left for Dart: how to create a factory function for an arbitrary number of args ? 
https://github.com/angular/angular/blob/master/modules/angular2/src/reflection/reflection_capabilities.dart#L44

any idea ?

/cc @kegluneq @kevmoo

**Comment by kegluneq** [comment]
I don't know off the top of my head how to make this work at arbitrary length, but this is only an issue for dev code running with `dart:mirrors`. The code generator does not have a limit to the number of arguments.

I can take a look at the reflective code though it may be a bit before I get to it. Would you file an issue and assign to me?

**Comment by mhevery** [comment]
Why does this matter. In practice I don't think people will try to inject
more than 10 items.

Just to be clear we are solving the limit on number of Bindings in
ElementInjector, not the number of args which could be injected.

**Comment by vicb** [comment]
Got that Misko, I'll leave the max number of injected args to 10 for now then.

@kegluneq then no issue for you :)
