### ISSUE TITLE
Clarify Router information about resolve

### ISSUE THREAD

**Issue by softchris** [angular/angular#18538]
When defining the crisisCenterRoutes and the CrisisDetail in particular there should a be a snippet showing something like :
{
  path: 'crisis-center/:id' 
  component : CrisisDetailComponent,
  resolve : [ CrisisDetailResolver ]
}

if you only add CrisisDetailResolver to the providers array for CrisisCenterRoutingModule then resolver is not hit and it doesn't know when it should be applied. This has gone missing from the docs somehow and is quite important to understand the resolve mechanism

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
I assume you are referring the [Fetch data before navigating][1] section. The need to add a `resolve` property is mentioned in the text:

> Import this resolver in the `crisis-center-routing.module.ts` and add a `resolve` object to the `CrisisDetailComponent` route configuration.

And the code is updated in `crisis-center-routing.module.ts` (as can be seen right below _"The relevant Crisis Center code for this milestone follows."_).

##
Are you suggesting the there should be a dedicated snippet?

[1]: https://angular.io/guide/router#fetch-data-before-navigating

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/20023
