### ISSUE TITLE
AOT Compilation starting documentation: missing npm scripts

### ISSUE THREAD

**Issue by pwwpche** [angular/angular#18544]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In [this](https://angular.io/guide/aot-compiler#running-the-application) section, npm script is missing after this line:

`Extend the scripts section of the package.json with these npm scripts:`

However, these missing npm scripts are not missing in package.json. Could we remove this line in case of confusion?

## Expected behavior

Following scripts should be added under that line:
```
    "build:aot": "ngc -p tsconfig-aot.json && rollup -c rollup-config.js",
    "serve:aot": "lite-server -c bs-config.aot.json",
```

**Comment by pwwpche** [comment]
Should we also remove this line from that doc?
`Extend the scripts section of the package.json with these npm scripts:`

**Comment by gkalpak** [comment]
@pwwpche, why remove that line?

**Comment by pwwpche** [comment]
I didn't notice any npm scripts that should be extended into package.json. So I'm not quite sure what scripts that this line is referring to. 

Possibly these scripts are already there so we no longer need to manually add them to package.json?

**Comment by gkalpak** [comment]
Have you seen https://github.com/angular/angular/pull/18547/files?

**Comment by pwwpche** [comment]
They are already in package.json, so I guess this is why the script is removed from the doc.

There is another missing script in that same page. 

` Use the same lite-server employed elsewhere in the documentation:`

Nowhere else on that page states what is this `lite-server` script. 

That's not big deal since it's easy to figure out the lite-server script, but it might be better to also list that on the doc. Guess I should start a different issue for this but it's ok if you're not adding it.

**Comment by gkalpak** [comment]
I see what you mean. Well, it is not exactly clear, because for the most part you use the quickseed boilerplate (which doesn't have the scripts) and then it tells you to download a zip (which does have the scripts). I also realized there was another code-snippet missing.

Submitted #18650 which will hopefully make things more clear (or at least less confusing 😛).

**Comment by pwwpche** [comment]
Awesome! No confusion any more. 

Thanks!
