### ISSUE TITLE
Route properties not consistent in AppComponent; correct in sub-components

### ISSUE THREAD

**Issue by polyglotinc** [angular/angular#18549]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular routing tutorials invariably have Components accessing route parameters (say, /:foo)
via `this.route.snapshot.params['foo']` in their constructor (or maybe ngOnInit).

While this works in components loaded into `<router-outlet></router-outlet>`,
This does not work in AppComponent;
    even though `this.route` is defined, it always has an empty URL.

The url never even updates if you evaluate that expression in `ngAfterViewChecked()`.
The url never even updates if you subscribe to data or url, ala...
`this.route.data.subscribe( data =>{  console.log(data);  });`
`this.route.url.subscribe( url =>{  console.log(url);  });`

_BTW, this is also an issue for other components loaded via the top-level template, but not inside the router-outlet, e.g. a header or footer._
## Expected behavior

Accessing route parameters (and other route properties) should work in AppComponent the same way that they do in other Components.

And in particular, it should not require the obscure technique (that I stumbled onto) of subscribing to events;
if `this.route` gets updated for the following code to work (and it does), it should be updated so that, at the very least, `this.route.url.subscribe` and `this.route.data.subscribe` also work!

```
// in the AppComponent constructor...
router.events
    .filter( e => e instanceof NavigationEnd )
    .forEach( e => {
        console.log( this.route.root.firstChild.snapshot.params['foo'] ); //works!
        console.log( this.route.snapshot.params['foo'] ); // prints undefined
       });
```

## Environment

<pre><code>
Angular version: 4.3.1

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

Please also confirm this is still an issue with the current version (`>5.0.0`).
