### ISSUE TITLE
Directive injects wrong ChangeDetectorRef if inside a content projection

### ISSUE THREAD

**Issue by voithos** [angular/angular#18542]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Note, I'm still working on reproducing this outside of our project. I'm not sure if the specifics of our project have to do with the issue (we're using NgUpgrade), but here's an attempt at describing what I'm observing:

When `ChangeDetectorRef` is injected into a directive that lives insides a component that does content projection (i.e. it is part of that component's ContentChildren), instead of injecting the `ChangeDetectorRef` of whatever component the directive is attached to, it seems to inject the `ChangeDetectorRef` of the top-most component that does the content projection. As an example, if a template has the following:

```
<content-projection-cmp>
  ...
  <custom-component [directiveWithCDRef]="foo"></custom-component>
  ...
</content-projection-cmp>
```

`directiveWithCDRef` will end up injecting `content-projection-cmp`'s change detector, instead of `custom-component`'s change detector. Note that this seems to only occur when done in a directive (a component is able to inject the proper reference at all times).

## Expected behavior
I would expect the directive to inject the `ChangeDetectorRef` of the component that it attaches to, regardless of content-projection context.

Is the intended behavior as I describe, or is it supposed to be otherwise?

## Minimal reproduction of the problem with instructions

I haven't been able to repro this outside of our project, unfortunately (but will keep trying). Here's a plunker that showcases the desired behavior, which isn't happening in our case:

http://plnkr.co/edit/sdA0x3HfTK8onnZPWeTe?p=preview

## Environment

<pre><code>
Angular version: HEAD

</code></pre>

**Comment by kemsky** [comment]
Thats how injection works unfortunately. The same applies to services.

**Comment by voithos** [comment]
I had considered that, but the thing that's confusing me is why the problem doesn't show up in the plunker, which seems to be doing the same thing?

**Comment by tbosch** [comment]
Angular's injection always happens regarding where a component / directive is used in a template, independent of content projection. 

I.e. this is works as intended.

**Comment by voithos** [comment]
Are you saying that the content projection shouldn't affect it? (I.e. that the behavior in the plunker is the expected behavior?)

**Comment by trotyl** [comment]
@tbosch If content projection doesn't influence DI, then why is there `providers` & `viewProviders`?

**Comment by tbosch** [comment]
@trotyl with "content projection" I mean the fact whether the template of a component contains an `<ng-content>` element into which the content children of the component get projected.

There is still a separation between the content and view children, but only based on where these are defined.

**Comment by voithos** [comment]
I think we can actually close this. We've decided to go another route that doesn't suffer from this issue, and in reality this may have been working properly to begin with.
