### ISSUE TITLE
How get js file  in all one and used with REST-service

### ISSUE THREAD

**Issue by aimbin** [angular/angular#18546]
I not  a node.js user.
I want to use angular 4 like 1.x and 2.x, integrated with  deploy jsp or html with apache/tomcat. Call service and show the result.  Is there an official release of js file I can get ?  Or the only way is to use node.js to compile out.

<link href="css/bootstrap.css" rel="stylesheet" />
<link href="css/bootstrap-theme.css" rel="stylesheet" />
<script src="js/jquery-2.2.3.min.js"></script>
<script src="js/angular.min.js"></script>

That what now use the angular with version 1.5.6,  I want to upgrade the version to 4.X

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)
