### ISSUE TITLE
AOT Compilation starting guide: cannot install compiler-cli and platform-server

### ISSUE THREAD

**Issue by pwwpche** [angular/angular#18543]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

At "Compile with AOT" section, after following the setup guide, when running 
```
npm install @angular/compiler-cli @angular/platform-server --save
```
It gives following error:
```
├── UNMET PEER DEPENDENCY @angular/animations@4.3.3
├── UNMET PEER DEPENDENCY @angular/common@4.0.3
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.3
├─┬ @angular/compiler-cli@4.3.3 
│ ├─┬ @angular/tsc-wrapped@4.3.3 
│ │ └─┬ tsickle@0.21.6 
│ │   ├── minimist@1.2.0 
│ │   └─┬ mkdirp@0.5.1 
│ │     └── minimist@0.0.8 
│ ├── minimist@1.2.0 
│ └── reflect-metadata@0.1.10 
├── UNMET PEER DEPENDENCY @angular/core@4.0.3
├── UNMET PEER DEPENDENCY @angular/platform-browser@4.0.3
└─┬ @angular/platform-server@4.3.3 
  ├── parse5@3.0.2 
  ├── tslib@1.7.1 
  └── xhr2@0.1.4 

npm WARN @angular/compiler-cli@4.3.3 requires a peer of @angular/compiler@4.3.3 but none was installed.
npm WARN @angular/compiler-cli@4.3.3 requires a peer of @angular/core@4.3.3 but none was installed.
npm WARN @angular/platform-server@4.3.3 requires a peer of @angular/animations@4.3.3 but none was installed.
npm WARN @angular/platform-server@4.3.3 requires a peer of @angular/core@4.3.3 but none was installed.
npm WARN @angular/platform-server@4.3.3 requires a peer of @angular/common@4.3.3 but none was installed.
npm WARN @angular/platform-server@4.3.3 requires a peer of @angular/compiler@4.3.3 but none was installed.
npm WARN @angular/platform-server@4.3.3 requires a peer of @angular/platform-browser@4.3.3 but none was installed.
```
And when running `node_modules/.bin/ngc -p tsconfig-aot.json`, it shows `this.compiler.analyzeModulesAsync is not a function`

## Expected behavior

`npm install` should run normally and these two commands should not produce error message. 

## Minimal reproduction of the problem with instructions

Follow [this](https://angular.io/guide/aot-compiler) startup guide

Version conflict between angular core and compiler-cli. Change `@angular` dependencies in `package.json` from "~4.0.0" to "^4.3.3" should fix this problem. 

## Environment

<pre><code>
Angular version: 4.0.3
Angular/Compiler-cli version: 4.3.3

For Tooling issues:
- Node version: 6.11.1
- npm version: 3.10.10
- Platform:  Mac
and
- Node version: 6.11.0
- npm version: 3.10.10
- Platform:  Ubuntu

Others:

</code></pre>

**Comment by gkalpak** [comment]
The dependencies should be updated [here][1]. We need to keep this up-to-date (maybe mention it [here][2]).

(cc @Foxandxss)

[1]: https://github.com/angular/quickstart/blob/master/package.json
[2]: https://github.com/angular/angular/blob/10897d64738484036443f6614ad3cbef095da0d5/aio/tools/RELEASE.md

**Comment by Foxandxss** [comment]
Yes we should keep it updated.

**Comment by Foxandxss** [comment]
Quickstart updated, I close this.

**Comment by Vandivier** [comment]
bump

![image](https://user-images.githubusercontent.com/5559355/34089363-77a4b1b0-e37d-11e7-8c98-45062642d897.png)
