### ISSUE TITLE
Pipe documentation

### ISSUE THREAD

**Issue by froodley** [angular/angular#18558]
The documentation for parameterizing a pipe at https://angular.io/guide/pipes#parameterizing-a-pipe does not include details on how to include the parameters in your pipe.  Although it's fairly obvious an example should be documented.

**Comment by jenniferfell** [comment]
Thanks for this submission. Now that v6 is released, we're catching up on open issues. 

It looks like this issue has been resolved, with the addition of the hero birthday example. 

If this is not resolved to your satisfaction, please reopen or submit a new issue. Thanks for your feedback!
