### ISSUE TITLE
Router Animations function is called twice every angular check

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular#18553]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Router animation function used to create custom router animations is called twice every angular check.

## Expected behavior
Router animation function used to create custom router animations should only be called on navigation.

## Minimal reproduction of the problem with instructions
```
<div [@routerAnimations]="prepareRouteTransition(outlet)">
      <router-outlet #outlet="outlet"></router-outlet>
</div>
```
```
public prepareRouteTransition(outlet: RouterOutlet) { // function called every angular check
    return outlet.activatedRouteData['animation'] || null;
}
```

## What is the motivation / use case for changing the behavior?
Performance

## Environment
Angular version: 4.3.3

Browser:
<pre><code>
- [x] Chrome (desktop) version XX
- [?] Chrome (Android) version XX
- [?] Chrome (iOS) version XX
- [?] Firefox version XX
- [?] Safari (desktop) version XX
- [?] Safari (iOS) version XX
- [?] IE version XX
- [?] Edge version XX
 </code></pre>

For Tooling issues:
- Node version: 6.11.0
- Platform:  Windows

Others:
Angular.io lacks a tutorial on router animations.
Only one available seems to be from @matsko at https://www.yearofmoo.com/2017/06/new-wave-of-animation-features.html

**Comment by matsko** [comment]
So are you sure that this happens when dev mode if off (in production)? Dev mode will always run bindings twice to see if they change.

**Comment by Ploppy3** [comment]
My bad I just realized what's happening, if it makes sens to you feel free to close the issue:
- You are right, in dev mode it double the checks
- Since it is a function, it is called once every check

**Comment by matsko** [comment]
Yes this works as expected.
