### ISSUE TITLE
Wrong sample code in the tutorial documentation

### ISSUE THREAD

**Issue by Kulbear** [angular/angular#18551]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Check the official doc [here](https://angular.io/tutorial/toh-pt4#appendix-take-it-slow).

```
getHeroesSlowly(): Promise<Hero[]> {
  return new Promise(resolve => {
    // Simulate server latency with 2 second delay
    setTimeout(() => resolve(this.getHeroes()), 2000);
  });
}
```

## Expected behavior

```
getHeroesSlowly(): Promise<Hero[]> {
  return new Promise(resolve => {
    // Simulate server latency with 2 second delay
    setTimeout(() => resolve(HEROES), 2000); // THIS LINE IS CHANGED
  });
}
```

You can refer to [this](https://angular.io/tutorial/toh-pt4#review-the-app-structure).

![image](https://user-images.githubusercontent.com/14886380/29002747-ed521b24-7adb-11e7-86ae-f319a53cdb10.png)

**Comment by trotyl** [comment]
There is nothing wrong with it, just too verbose...when resolving a Promise, it would be unwrapped automatically:

![snip20170806_3](https://user-images.githubusercontent.com/6059170/29003059-4e007f00-7ae2-11e7-90f2-fba1431b77fb.png)

**Comment by Kulbear** [comment]
There is no `this.getHeroes()` in the original code base.

**Comment by Kulbear** [comment]
Oh, I should not remove the getHeroes method from the HeroService class.
