### ISSUE TITLE
Angular CLI AoT Compiler Errors

### ISSUE THREAD

**Issue by qidaneix** [angular/angular#18564]
I'm learning Angular2+ with the QuickStart of the official web. When I stepped to the `Step 3: Serve the application`, it comes out a error from webpack as follows:
```
ERROR in Error encountered resolving symbol values statically. Function calls are not supp
orted. Consider replacing the function or lambda with a reference to an exported function
(position 194:50 in the original .ts file), resolving symbol NgModule in C:/Users/xiaoj/Do
cuments/my-app/node_modules/@angular/platform-browser/node_modules/@angular/core/core.d.ts
, resolving symbol BrowserModule in C:/Users/xiaoj/Documents/my-app/node_modules/@angular/
platform-browser/platform-browser.d.ts, resolving symbol BrowserModule in C:/Users/xiaoj/D
ocuments/my-app/node_modules/@angular/platform-browser/platform-browser.d.ts
```
and I have done nothing to the code. 

Please provide us with the following information:
OS?
Windows 10. 

angular version?
```
ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.7
node: 6.11.2
os: win32 x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.7
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3
```

**Comment by StephenFluin** [comment]
I just gave this a try and I'm not able to reproduce this. Can you double check that the `ng new` command didn't throw any errors, or commit all of the code into a repository so we can take a closer look?

**Comment by about-code** [comment]
@qidaneix did you by chance write something like 

```
providers: [{
   provide: Foo, useFactory: () => {return new Bar(); }
}]
```
somewhere? If so, then rewrite it e.g. to 
```
providers: [{
   provide: Foo, useFactory() { return new Bar(); }
}]
```
Sadly AoT restricts expressiveness of the language and doesn't allow you to use an anonymous function in the example above.  See other [AoT limitations](https://github.com/rangle/angular-2-aot-sandbox).

**Comment by vicb** [comment]
> doesn't allow you to use an anonymous function in the example above

FYI this should be possible now in the 5.x branch (from 5.0-beta.3 released 2d ago) more sweetness to come.
