### ISSUE TITLE
ActivatedRoute in @angular/router": "^4.3.3" not getting params even in same component.

### ISSUE THREAD

**Issue by dinkarthakur** [angular/angular#18569]
My AppComponent is
```
import { Component } from '@angular/core';
import {ActivatedRoute} from "@angular/router";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor(private route:ActivatedRoute){
    this.route.paramMap.subscribe(x=>console.log(x.keys));
  }

}
```
And app.module.ts is like

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import {RouterModule, Routes} from "@angular/router";

const route:Routes = [{path:':id/:value',component:AppComponent}];

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot(route)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
i make a request like 

> http://localhost:4200/asdf/asdfasdfasdf

i was hoping to get the keys in the log but not getting that its giving empty array [].
also when i did  `this.route.paramMap.subscribe(x=>console.log(x.get('id'))) ` 
i get null. 

this is working fine in case of queryString params 
`this.route.queryParamMap.subscribe(x=>console.log(x.keys))`

and i make request like 

> http://localhost:4200/asdf/asdfasdfasdf?asdf=asdf&kadjshf=asdf

its giving me` ["asdf", "kadjshf"]`

i think there is a issue with 4.3.3

my package.json is

```
"dependencies": {
    "@angular/animations": "^4.3.3",
    "@angular/common": "^4.3.3",
    "@angular/compiler": "^4.3.3",
    "@angular/core": "^4.3.3",
    "@angular/forms": "^4.3.3",
    "@angular/http": "^4.3.3",
    "@angular/platform-browser": "^4.3.3",
    "@angular/platform-browser-dynamic": "^4.3.3",
    "@angular/router": "^4.3.3",
    "core-js": "^2.5.0",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.16"
  }
```

**Comment by jnizet** [comment]
Works fine here: http://plnkr.co/edit/0JI85jX8M9pcJsVtwYLN?p=preview

But of course: you will only see the parameters in the instance of the AppComponent that is associated with the route defining those parameters. Not in the root app component.

**Comment by dinkarthakur** [comment]
Got it. this only works if i have `<router-outlet></router-outlet>` if i remove this stops working. 
Why this is dependent on `<router-outlet></router-outlet>`? if i just need to parse the Url for params i guess i have to use 

> UrlSerializer

Is that so?

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
