### ISSUE TITLE
Empty headers in HTTP Response with Angular 4.3's HttpInterceptor

### ISSUE THREAD

**Issue by TheParad0X** [angular/angular#18563]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This is how I send my HTTP request:
`return this.http.get(url, { observe: 'response' })`

I would like to read the HTTP headers of a HttpResponse in my HttpInterceptor:

```
intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        return next.handle(request)
            .do(event => {
                if (event instanceof HttpResponse) {
                    this.logger.logDebug(event); // Headers are missing here
                }
            })
            .catch((err: HttpErrorResponse) => {
            // Do stuff
    }
}
```

The event seems to have no headers, and even in the Chrome Dev Console I cannot see any headers:

![headers](https://user-images.githubusercontent.com/17595640/29017703-5302d950-7b58-11e7-8616-d5e77bcd1fa1.png)

However, when using Postman, I can see the headers in the response (as expected)

> Connection →keep-alive
> Content-Length →14766
> Content-Type →application/json
> Date →Fri, 04 Aug 2017 14:50:46 GMT
> Server →WildFly/10
> X-Powered-By →Undertow/1

The official docs for HTTP says to get the headers like this:

```
http
  .get<MyJsonData>('/data.json', {observe: 'response'})
  .subscribe(resp => {
    // Here, resp is of type HttpResponse<MyJsonData>.
    // You can inspect its headers:
    console.log(resp.headers.get('X-Custom-Header'));
    // And access the body directly, which is typed as MyJsonData as requested.
    console.log(resp.body.someField);
  });

```

## Expected behavior
I was expecting to see the same headers in Angular as with Postman

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [x] Chrome (desktop) version XX

**Comment by alxhub** [comment]
Can you share the code you're using to actually read the headers? Logging the `HttpHeaders` instance is going to be misleading - headers are lazily parsed from the response header string on first access. It looks like your instance has a `lazyInit` function and is poised to perform this parsing when the headers are first accessed.

**Comment by robwormald** [comment]
If you're not getting them in Chrome Dev Tools, Angular won't be able to access them either.

See: https://github.com/angular/angular/issues/13226 this is likely related to your server side configuration.

**Comment by TheParad0X** [comment]
@robwormald You were right. It was a CORS problem. I needed to explicitely expose my custom header. Thank you

**Comment by smitelij** [comment]
> Logging the HttpHeaders instance is going to be misleading - headers are lazily parsed from the response header string on first access.

Thanks for this info alxhub- I was very confused as to why my headers _appeared_ to be gone from my HttpRequest.

**Comment by lakshay2711** [comment]
@TheParad0X 

Were you able to get the headers response in logger which you have put in HttpInterceptor after you allow cross orign for the custom header in server side?
