### ISSUE TITLE
Lifecycle Hooks are not called for some(second) element with ControlValueAccessor Directive in embeded IE

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/angular#18560]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have a directive which implements `ContrlValueAccessor` to convert any HTMLElement into contenteditable

Lifecycle hooks for second use of same directive within a component are not called like `ngOnInit` , `ngViewAfterChange` , `ngOnChanges` , but methods implemented for `ContrlValueAccessor` are called like `writeValue`

EveryThing works fine for first use of directive

## Expected behavior
All lifecycle hooks should be called

## Minimal reproduction of the problem with instructions
use case is somewhat similar to this 
http://plnkr.co/edit/vZMgT43owGl3I8YPDTLi?p=preview

but could not reproduce outside of our APP

Code works correctly Chrome Edge and Normal IE but issue is in embed IE in MS Office products

## Environment

<pre><code>
Angular version:4.3.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE embedded "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko"
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by abdulkareemnalband** [comment]
Is there a toggle or method call which can enable logging angular events

**Comment by vicb** [comment]
> but could not reproduce outside of our APP

We can not help without a repro.

**Comment by abdulkareemnalband** [comment]
Hi @vicb 
I can understand finding solution without reproducing issue is difficult

But any pointers to debug issue where angular lifecycle hooks are not called for a directive?
