### ISSUE TITLE
angular2 Not able to pass/share Object/properties  to Root Component

### ISSUE THREAD

**Issue by Parth2402patel** [angular/angular#18566]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Working on SPFx based webpart with TypeScript and Anguler.

Have mail render function in MyWebPart.ts calling my angular module

private _renderAnnoucementAsync(): void {
    // Check if enviorment is local or SharePoint
    if (Environment.type === EnvironmentType.SharePoint) {
      let itemID : number = 0;
      let listName : string = '';

      const listContainer: Element = this.domElement.querySelector('#annoucementDetailsContainer');
      //listContainer.innerHTML = `<my-app></my-app>`;
      listContainer.innerHTML = `<my-details-app></my-details-app>`;
      platformBrowserDynamic().bootstrapModule(AppModule);
    }
    else{
      const listContainer: Element = this.domElement.querySelector('#annoucementDetailsContainer');
      //listContainer.innerHTML = `<my-app></my-app>`;
      listContainer.innerHTML = `<my-details-app></my-details-app>`;
      platformBrowserDynamic().bootstrapModule(AppModule);
    }
  }

Also want to pass my object or properties to 'my-details-app' component i guess there is no way to achieve this. 

## Expected behavior
Can able to share @input to child component but not happening with root element.

Also have created Injectable data service like below.

@Injectable()
export class ListDataService {

  /**
   * @function
   * Service constructor
   */
  public context: IWebPartContext;
  constructor(){
      //alert(this.context.pageContext.web.absoluteUrl);
  }

but not successful, i am not able to access or pass any object while calling above service.

We can achieve this using angular 1 but not sure why not working angular 2.

**Comment by mlc-mlapis** [comment]
@Parth2402patel ... not clear what do you want do ... the statement `to pass my object or properties` from outside to the Angular app is very vague. What data you need to pass? Some real data or some configuration during run-time? At the last point, if any other way not possible, even Angular has access to the global objects as `window` or `document`.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
