### ISSUE TITLE
FormControl.setValue triggers valueChanges even if it is called with the current value of the FormControl

### ISSUE THREAD

**Issue by tobias74** [angular/angular#18574]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Situation: I am calling the setValue (or patchValue) on a FormControl. The value I am setting is equal (===) to the current value. 
Result: The form.valueChanges.forEach() executes its callbacks 

## Expected behavior

Calling the setValue-Method with the current value of the FormControl should not trigger valueChanges.forEach-Callbacks, since the value did not change.

Motivation: In my situation I had two input-fields which updated themselves according to the value of the other input-field. Here is how it worked: In case the user entered "2" in the first input field, the second input field would be updated programmatically to the value "pair". In case the user entered "1" in the first input field, the second input field would be programattically updated to "impair". Now the user could also enter "pair" in the second input field. In that case the first input.field would be automatically updated to "2".
Trying to implement this behaviour I ended up with a cyclic callback situation (first input called with setValue triggering second input being called with setValue, which then again tiggered the first input with setValue... all the time with the same values that had already been set.)

I had to implement my own "updateValue"-Method which would check whether the current value of the FormControl is actually different from the value being set, and only triggering events in case the values were different ( I did need the events to fire in case the values were different, because I had to update a second instance of the form, otherwise I could have just used 'emitEvents:false')

I think it would be nice to have a method ( or an option) to prevent events from being fired in case the setValue-Method is called with the actual current value of the FormControl. I twould also be more in tune with the word 'valueChanges'. Currently 'valueChanges' behaves more like a 'valuesSet'

  

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by tytskyi** [comment]
Did you try `control.setValue(value, {emitEvent: false})`?

https://angular.io/api/forms/FormControl#setValue

**Comment by tobias74** [comment]
Using {emitEvent: false} would prevent the event from being fired in all cases. I need to prevent the event only in case the value did not change. In all other cases I need the event to fire.

**Comment by tytskyi** [comment]
@tobias74 see discussion on linked PR. This would be difficult to support for non primitive values.

**Comment by kara** [comment]
@tobias74 I see where you're coming from, but as @tytskyi brought up, this would be difficult to implement well at a framework level with non-primitive values. Your solution of calling `setValue` conditionally based on your own check seems reasonable.
