### ISSUE TITLE
aio: missing descriptions on modules API docs

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#18572]
Although the `description` block is included in the [module template][1] and modules [do have descriptions][2], these don't show up [in the docs][3] 😞 
I tried moving the comment to the `index.ts` file, but still nothing.

[1]: https://github.com/angular/angular/blob/f9f8924c49a8592d1ab97ff4cfc0c73ef78e0cdc/aio/tools/transforms/templates/api/module.template.html#L6
[2]: https://github.com/angular/angular/blob/f9f8924c49a8592d1ab97ff4cfc0c73ef78e0cdc/packages/core/public_api.ts#L9-L13
[3]: https://angular.io/api/core

**Comment by petebacondarwin** [comment]
I think this is because our dgeni config has no way of knowing that a comment block is for a module rather than some subsequent code item.

**Comment by IgorMinar** [comment]
I'm marking this as frequency hard because the ngmodules are usually entry point to exploring a particular group of apis.

**Comment by jenniferfell** [comment]
@petebacondarwin @jbogarthyde Is this resolved by our recent or in-progress API template work?

**Comment by jbogarthyde** [comment]
related test doc in PR #25618

**Comment by petebacondarwin** [comment]
As far as the docs-infrastructure is concerned, this is solved. We just need some content now.

**Comment by gkalpak** [comment]
If the docs-infra side is fixed, I am going to close this. Adding content is another story :smiley:
