### ISSUE TITLE
"Cannot match any routes" after page refresh for a nested child route

### ISSUE THREAD

**Issue by rolucas** [angular/angular#18571]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have the following router config:
<pre><code>
const appRoutes: Routes = [
  { path: '', component: HomeComponent, canActivateChild: [AuthGuard],
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'Dashboard' },
      { path: 'Dashboard', component: DashboardComponent},
      { path: 'TerritoryDefinition', component: TerritoryDefinitionComponent},
      { path: 'TerritoryEditor', component: TerritoryEditorComponent, canDeactivate: [UnsavedDataGuard]},
      { path: 'Setup', component: SetupHomeComponent,
        children: [
          { path: '', pathMatch: 'full', component: SetupDefaultComponent},
          { path: 'SalesOrg', component: SalesOrgSetupComponent },
          { path: 'Cycles', component: TemporalDataComponent },
        ]},
    ]},
  { path: 'Login', component: LoginComponent},
  { path: '', pathMatch: 'full', redirectTo: APP_ROUTE_KEY.LOGIN },
];
</code></pre>
From the home component I can navigate into any of  the child routes no problem including /Setup/Cycles.

If I browser refresh while in /Setup/Cycles I get the "Cannot match any routes. URL Segment: 'Cycles'" exception. On a browser refresh in any of the top level paths (e.g. /TerritoryDefinition or even /Setup) the expected page reloads without problem.

If I add Setup twice to the path this appear to work. E.g. /Setup/Setup/Cycles I can refresh (which should be an invalid path).

I found this similar issue "https://github.com/Greentube/localize-router/issues/25" on the localized router. My app is using normal RouterModule.

## Expected behavior

I would expect the page to reload as normal for the sub-children as for the top level.

## Environment

<pre><code>
Angular version: 2.4.9 (3.4.9 of the router)

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.9.2
- Platform:  Windows

Others:

</code></pre>

**Comment by vicb** [comment]
Without a repro there is nothing we can do.

Until we have a repro, I assume your server is not setup correctly.

Please re-open an issue if you have a valid repro

**Comment by hasannizamani** [comment]
I'm facing the exact same issue, doesn't like any nested route on refresh.
