### ISSUE TITLE
Type Incorrect for animations/query

### ISSUE THREAD

**Issue by Tiedye** [angular/angular#18587]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The first parameter `stateChangeExpr` is only allowed to be a `string`.

## Expected behavior

The first parameter `stateChangeExpr` should be able to be a `string` or a function with the signature `(from, to) => bool`.

## Minimal reproduction of the problem with instructions

Very simple typing error:
```
transition((from, to) => true, []);
```
gives an error.

## What is the motivation / use case for changing the behavior?

It is used in the code to implement `:increment` and `:decrement`, and is stated a valid use in the docs: https://angular.io/api/animations/transition#usage.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by matsko** [comment]
Looking into it. Thank you for reporting.

**Comment by vicb** [comment]
Closing as obsolete and no repro has been provided

**Comment by Tiedye** [comment]
After 30 seconds of investigation it was addressed by https://github.com/angular/angular/commit/590d93b30dfb0fcc6baf380bc155dd07dd121f46 and the issue was never closed.
