### ISSUE TITLE
ngtools/webpack does not emit ngmodule decorator information.

### ISSUE THREAD

**Issue by hans-pragt** [angular/angular#18591]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am trying to integrate AOT compilation into an existing Angular component library. This library has always been packaged using webpack, so I integrated `ngtools/webpack` into my configuration. After resolving the problem of `ngtools/webpack` not inlining / `require`ing external templates and styles, I was still not able to use the resulting JS module. Whenever I try to run an app using this, I would get an error stating that the module class is missing its `NgModule` decorator.

When examining the generated code, I noticed that `ngtools/webpack` has stripped all decorators from the code.

## Expected behavior

`ngtools/webpack` should keep angular-specific decorators.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by IgorMinar** [comment]
can you please file an issue at https://github.com/angular/devkit/issues/new instead?
