### ISSUE TITLE
Not animated style for animations

### ISSUE THREAD

**Issue by MickL** [angular/angular#18603]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the motivation / use case for changing the behavior?
Animating often requires the animated-elements to have certain styles only for the animation. E.g. when reducing the height to 0 the element may need to have `overflow:hidden`. Another example are component-wrappers like `<app-component>` do not work with `opacity` unless they have e.g. `display: block`. This particular styles may only be wanted for the animation, and not for general style. E.g. we need `overflow:hidden` for animating, but keep `overflow:visible` in general because of some tooltips.

This is why it would be nice to have a style() that will not but animated, but just applied for the animation.

## Current behavior
I don't see any possibility of adding styles the last only for the animation but are not animated. I tried adding `display: 'block'` to a state and a transition with no success.

## Expected behavior
New(?) function similiar to `style()` for use within `animate()`

<pre><code>
Angular version: 4.x | 5.x.x

**Comment by Tiedye** [comment]
This should be easy with what we have now, could you share the code that didn't achieve what you wanted?

**Comment by MickL** [comment]
Im pretty sure that e.g. display or position doesn't have any effect:

```
animations: [
    trigger('slideInOut', [
      transition('void => *', [
        style({
          display: 'block',
          position: 'absolute',
          opacity: '1',
        }),
        animate(300, style({
          display: 'block',
          position: 'absolute',
          opacity: '0',
        }))
      ]),
    ])
  ],
```

**Comment by Tiedye** [comment]
I tried this and it worked as expected: http://plnkr.co/edit/Fkm7RFuz8rPp1n42Pq70?p=preview

**Comment by matsko** [comment]
@MickL this works as expected and was intended. @Tiedye's demo demonstrates that it does work. The display and position properties will be carried over throughout the entire animation sequence. In fact you can place follow-up style properties directly after an `animate` step to immediately set styles following a step within the sequence.
