### ISSUE TITLE
Dom nodes memory leak with animations using @HostBinding

### ISSUE THREAD

**Issue by abbazabacto** [angular/angular#18606]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I note while profiling my application that I have detached dom nodes after an animated elements have been removed from dom tree when I am using `@HostBinding`.

## Expected behavior
Detached node should be flushed from memory.

## Minimal reproduction of the problem with instructions
I made an example here:
http://plnkr.co/edit/i1kYmhJaeEvV9JGy2DHX?p=preview

I rewrote the plunk from https://github.com/angular/angular/issues/16239 using @HostBinding. Similar issue still appears, the div elements are still retained.

## What is the motivation / use case for changing the behavior?
I have some memory crash causes by this on my cordova android mobile application.

## Environment

<pre><code>
Angular version: 4.3.3
</code></pre>

**Comment by harishmegharaj** [comment]
Can you please share the solution through plunkr? I'm using angular version 4.3.6, but still facing similar problem of memory leak of DOM
