### ISSUE TITLE
Style directive does not update GUI after window.onresize

### ISSUE THREAD

**Issue by Skuriles** [angular/angular#18602]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

After window onresize event [style] directive does not update without NgZone.run()

## Expected behavior

After changing style property it DOM should be updated

## Minimal reproduction of the problem with instructions
Run plunkr
http://plnkr.co/edit/nlo8IE52AumyOpCcp0W5?p=preview

I've tried some things with setInterval or setTimeout and NgZone.run. 
In my code ngZone.run helped to fix the problem. in Plunkr it doesn't update correctly.

## Environment
Angular version: 4.3.3.

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by ericmartinezr** [comment]
works fine for me http://plnkr.co/edit/93BarXLXEcONYeZYIOMr?p=preview, not a bug.

**Comment by Skuriles** [comment]
Thanks, totally forgot the hostlistener!
