### ISSUE TITLE
Circular dependency on templateUrl non-detected

### ISSUE THREAD

**Issue by millerf** [angular/angular#18608]
[X ] Bug report  

## Current behavior
I added by mistake the same template/templateUrl to a component and one of its childs component.

My browser tab just became unresponsive and I had to hard-kill it.

## Expected behavior

I would expect to have a circular dependency Error

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/vkzxMmLaGCk0JO5msjxu

(See that templateUrl in child.component refers at "parent.template.html" instead of -for example- "child.template.html")

Angular version: 1.4.3

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by alxhub** [comment]
I see the problem here, but unfortunately Angular does allow recursive components, so I don't think we can automatically make this an error.
