### ISSUE TITLE
Nested multiple transclude fails

### ISSUE THREAD

**Issue by harm-less** [angular/angular#18600]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I like the idea of multiple transcluding, but it seems I've run into a possible bug when transclusion happens from a parent component. The errors it gives is:
`Required transclusion slot 'titleSlot' was not filled.`

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/BrPCuekwwbBQARcCmodo?p=preview

## Expected behavior
I expect the Plunker to work as expected because I don't understand the difference between using only the `ng-child` component with its multiple transclusion slots or "sending" the transclusion slots down to the child using another transclude. Did I miss something here?

## What is the motivation / use case for changing the behavior?
The code I'm writing would be much more DRY if this works because it allows me to combine/wrap some of my components into bigger components. 
Another solution I had is to replace the templateUrl using attributes, but that didn't work out (#11144).

## Environment

<pre><code>
Angular version: 1.6.1 (but the Plunker is using 1.6.6)

Browser:
- [x] Chrome (desktop) version Version 59.0.3071.115 (Official Build) (32-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by wosevision** [comment]
Wrong repo – Angular**JS** lives [here](https://github.com/angular/angular.js). This is the 2+ (Angular) one.

**Comment by harm-less** [comment]
Yeah, I just noticed. My bad.
