### ISSUE TITLE
[Question] Can we update Jasmine to 2.3.3, how ?

### ISSUE THREAD

**Issue by vicb** [angular/angular#1860]
For [fakeAsync](https://github.com/angular/angular/pull/1837), jasmine would need to be updated to 2.3.3

Could this cause conflict with other test libs ?

There is no direct jasmine dep in the package.json, how can we update ?

@juliemr ?

Background:
`fakeAsync` fakes timers and before jasmine 2.3.3, it is not possible to cancel a `setInterval` from within its callback. That's not a major issue but would be nice to update jasmine anyway. For now the test is skipped when `global.jasmine` is defined.

**Comment by cssensei** [comment]
Good idea to use the latest version of jasmine for testing. We'll have to refactor some of the tests. Replace the old `runs` and `waitsFor` functions so we can make use of `done`.

**Comment by vicb** [comment]
We do already use `done` via the `AsyncTestCompleter`.

**Comment by cssensei** [comment]
That's great! 

From what I see [here](https://github.com/angular/angular/blob/master/package.json#L87) the used version of jasmine should be already at least 2.2. 
Normally from the [release notes of jasmine](https://github.com/jasmine/jasmine/tree/master/release_notes) there are no breaking changes until 2.3.3.

**Comment by juliemr** [comment]
We're working on upgrading Protractor to 2.3.3 (from 2.1, we skipped 2.2 due to some pending jasmine issues). So yes, I'd say we should go for it.

For unit tests, we get Jasmine through karma-jasmine, I'm not sure if it'll need updates or not. https://github.com/karma-runner/karma-jasmine/blob/master/package.json#L31

**Comment by IgorMinar** [comment]
we'll also need to update the [traceur-jasmine](https://github.com/angular/angular/blob/master/tools/traceur-jasmine/index.js) runtime we use for our cjs tests.

**Comment by vicb** [comment]
Once Jasmine is 2.3.3+, update fakeAsync to re-enable JS tests, ref #1837

**Comment by juliemr** [comment]
Ok, for Protractor this will be done with https://github.com/angular/angular/pull/2044

For karma-jasmine, there is an issue with `iit` or `fit` (neither works). I'm looking in to that.

**Comment by juliemr** [comment]
This is now done for js, cjs, and e2e.

@vicb does anything else need to be done to update fakeAsync? Should we close this?

**Comment by vicb** [comment]
Thanks @juliemr !
I'll close this as I submit the PR to re-enable tests block on 2.3.3 later today
