### ISSUE TITLE
Broken common-http.umd.js

### ISSUE THREAD

**Issue by pavel-blagodov** [angular/angular#18609]
The reason is incorrect globals mapping in rollup.config.js
https://github.com/angular/angular/blob/4.3.x/packages/common/http/rollup.config.js

The correct is:

'@angular/core': 'ng.core',
'rxjs/observable/of': 'Rx.Observable'
'rxjs/operator/concatMap': 'Rx.Observable.prototype'
'rxjs/operator/filter': 'Rx.Observable.prototype'
'rxjs/operator/map': 'Rx.Observable.prototype'
'@angular/common': 'ng.common'
'rxjs/Observable': 'Rx'

here is full example https://github.com/angular/angular/blob/4.3.x/packages/core/rollup.config.js

Also, I don't know why but it uses tslib as dependencies to run ES6's extends. See https://unpkg.com/@angular/common@4.3.3/bundles/common-http.umd.js

**Comment by pavel-blagodov** [comment]
and the moduleName has typo https://github.com/angular/angular/blob/4.3.x/packages/common/http/rollup.config.js#L14
ng.comm**m**on.http

**Comment by trotyl** [comment]
Should have been fixed by #18613?

**Comment by mhevery** [comment]
closed by #18613
