### ISSUE TITLE
CanActivate not called on redirectTo router rule; but no error either

### ISSUE THREAD

**Issue by polyglotinc** [angular/angular#18605]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When defining a route with `redirectTo` and `canActivate` properties, there is no error (as there would be if there were, say, `redirectTo` and `children` properties on the same route).
But, while it is apparently allowed, it is not honored. The `canActivate` is never called, and the `redirectTo` is simply processed.
E.G.
```
{ path:"**",
  //component: MyComponent,
  redirectTo: "foo",
  canActivate: [ MyGuard ]
}
```
If `redirectTo` is commented out and `component` uncommented, `MyGuard` runs just fine.

## Expected behavior

There should either be an error thrown if `canActivate` is not allowed for `redirectTo` routes,
or, `canActivate` should be processed the same way it is for Components.

## What is the motivation / use case for changing the behavior?

Since there is no `resolveRedirectTo` as there was in AngularJS,
and there is no ability to define or invoke a function/service on the `redirectTo` property (to calculate the path to redirect to),
there is a need to invoke that service and redirect programmatically via canActivate (for lack of a better place to put it).

Plus, I would rather see a (bogus) `redirectTo` property rather than a bogus `Component` property (since canActivate is always going to redirect because we are trying to recreate the missing `resolveRedirectTo` facility).

## Environment

<pre><code>
Angular version: 4.3.1

</code></pre>

**Comment by kimkong88** [comment]
Do we have update on this?

**Comment by dhananjaykumar880** [comment]
need updates on it. I am also facing same problem

**Comment by pietrorobbi** [comment]
i've the same problem, any news?

**Comment by danail-vasilev** [comment]
I am also interested in resolving this issue :)

**Comment by alexeygt** [comment]
Same problem. In my case I have external route that is used for embedded views. The following configuration does not work. EmbedRouteGuard is ignored:

```
const appRoutes: Routes = [
  { path: '', redirectTo: '/login', pathMatch: 'full' },
  {
    path: '',
    canActivate: [LoggedInGuard],
    children: [
      {
        path: 'view1',
        component: ViewOneComponent,
      },
      {
        path: 'view2',
        component: ViewTwoComponent,
      },
    ],
  },
  {
    path: 'embed',
    canActivate: [EmbedRouteGuard],
    children: [
      {
        path: '',
        redirectTo: '/view1',
        pathMatch: 'full',
      },
      {
        path: 'view1',
        redirectTo: '/view1',
      },
      {
        path: 'view2',
        redirectTo: '/view2',
      },
    ],
  },
];
```

**Comment by adilkhursheed** [comment]
For me this issue was occurred due to incorrect position of "**" route path. Whenever you are importing "**" route path make sure that you add this in the end of your import list. For example:
`imports: [
    // RouterModule.forRoot(defaultRoute),
    RouterModule.forRoot(sharedRouteTable),
    RouterModule.forRoot(adminRouteTable),// this is secure route array with Canative
    RouterModule.forRoot(websiteRouteTable),
    RouterModule.forRoot([
      /*
        all available routes
      */
      {
        path: "notfound",
        component: ErrorpageComponent
      },
      {
        path: "**",
        // component: ErrorpageComponent
        // , 
        redirectTo: "notfound"
      }])
  ]`

**Comment by mvhecke** [comment]
The current workaround is to create a dummy component and call the redirect logic inside a guard. Not pretty but it does the job.

**Comment by paveldayneko** [comment]
Is there any update regarding this issue?

**Comment by atscott** [comment]
Hi all, I'm updating this to be a feature request / use-case that doesn't have a clear recommendation (docs needed, error message needed). In the meantime, maybe a cleaner solution than a dummy component would be to have a route with an empty children array. This route could still be "activated" and would run the guards, allowing you to redirect properly.

```
const routes = [
  {path: 'redirectMe', children: [], canActivate: [Redirector]},
  {path: 'redirected', component: Redirected},
];
```

https://stackblitz.com/edit/angular-ivy-router-base-nka13t?file=src%2Fapp%2Fapp.module.ts

**Comment by amedriveroperez1984** [comment]
Any update on this?
I'm running on the same issue.
My Guard is not getting executed at all.
In my case I don't want to redirect just validate access to route base on roles.

**Comment by MathRobin** [comment]
Hi! No update about this? I'm running too the same error.
many thanks for your help!

**Comment by Tonio-lavanda** [comment]
I'm using Angular 10 and I experience the same issue, it's a bit crazy to have such an old bug still being there

**Comment by GeorgeKnap** [comment]
this is working solution for me in Angular 11
```
{
    path: '',
    canActivate: [DefaultRouteGuard],
    children: [],
    pathMatch: 'full'
  }
```
in the route guard you have the logic to redirect router however you like.

**Comment by darthsitthiander** [comment]
> this is working solution for me in Angular 11
> ```
> {
>     path: '',
>     canActivate: [DefaultRouteGuard],
>     children: [],
>     pathMatch: 'full'
>   }
> ```
> in the route guard you have the logic to redirect router however you like.

Although this is technically working (and probably the workaround most people are using right now) it is not a solution because you are not using the redirectTo parameter, which handles the redirection logic. So it can be a temporary workaround until an actual fix for this bug comes around.

**Comment by polyglotinc** [comment]
>  So it can be a temporary workaround until an actual fix for this bug comes around.

OMFG...until a fix...I am the one who wrote this original bug report and that was 3 and a half YEARS ago!
I've actually retired since, and a good thing I didn't hold my breath for this and many other bugs to be fixed over the years.
I don't know what IS being worked on but like most programmers, they want to work on new stuff rather than make the existing stuff work correctly.

**Comment by darthsitthiander** [comment]
> >  So it can be a temporary workaround until an actual fix for this bug comes around.
> 
> OMFG...until a fix...I am the one who wrote this original bug report and that was 3 and a half YEARS ago!
> I've actually retired since, and a good thing I didn't hold my breath for this and many other bugs to be fixed over the years.
> I don't know what IS being worked on but like most programmers, they want to work on new stuff rather than make the existing stuff work correctly.

I understand but it still doesn't make it a fix lol. Glad you don't need a fix but it is a part of making Angular better and why we have issue trackers here on Github. I doubt it is a priority to the devs but if you just want a workaround, there already is a site for it called Stackoverflow.

**Comment by polyglotinc** [comment]
> I understand but it still doesn't make it a fix lol. Glad you don't need a fix but it is a part of making Angular better and why we have issue trackers here on Github. I doubt it is a priority to the devs but if you just want a workaround, there already is a site for it called Stackoverflow.

Oh, I agree...there should be bug fixes to make existing features work. I groan at the religious adherence to so-called "agile" thinking and doing multiple full version number releases a year...If were king the practice would be to make APIs stable, and functioning correctly before letting some newbie create new features and break old ones. (Of course, that should go also for all software from Apple, Google, Facebook, Microsoft, etc, etc, etc).

**Comment by darthsitthiander** [comment]
> Oh, I agree...there should be bug fixes to make existing features work. I groan at the religious adherence to so-called "agile" thinking and doing multiple full version number releases a year...If were king the practice would be to make APIs stable, and functioning correctly before letting some newbie create new features and break old ones. (Of course, that should go also for all software from Apple, Google, Facebook, Microsoft, etc, etc, etc).

I agree with this sentiment, although I havent followed Angular in recent years, it seems the initial vision has been worked out and they switched their focus on Flutter which I'm using now. If it stagnates similar to Angular I will be looking for a other framework. It's exciting that there are so many options but also time/energy consuming. Really hope they get their stuff together and get more people to do fixes that they seem to have forgotten about.
