### ISSUE TITLE
Perf: add a benchmark for NgZone 

### ISSUE THREAD

**Issue by vicb** [angular/angular#1861]
/ref #1574, https://github.com/angular/angular/pull/1288#issuecomment-93494991

What we should benchmarks:
- zone.js uses `Promise.then` as the default way to enqueue microtasks (when native Promise are available). When not available, it would use other fallbacks from es6-promise (`MutationObserver`, ...). We should make sure that we pick the fastest way, see [zone.js](https://github.com/angular/zone.js/blob/95c9dc2a632ff8ed941a416f28cc28e16f75bfda/lib/microtask.js#L21) for more details
- The cost of NgZone has indicated in the comment referenced above.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
