### ISSUE TITLE
Type 'IterableIterator<string>' is not an array type or a string type

### ISSUE THREAD

**Issue by avhetman** [angular/angular#18616]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is no support for iterables in the angular project

## Expected behavior

I would like to be able to use IterableIterator<string> types in order to convert then to arrays or iterate over them using for-of loops and not have the "Type 'IterableIterator<string>' is not an array type or a string type" errors.

## Minimal reproduction of the problem with instructions

make a new map, get the keys using map.keys() then try to iterate over the keys using for (key of keys)

## What is the motivation / use case for changing the behavior?

I would like to be able to work with the keys from map objects

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
It appears your issue is not related to Angular.
Could you please provide a minimal reproduction of how this is an Issue with Angular instead of TS/JS

**Comment by trotyl** [comment]
Try enable `downlevelIteration` option in `tsconfig.json`, for better error message, you can track on https://github.com/Microsoft/TypeScript/issues/16022 .

**Comment by avhetman** [comment]
This is related to my PR #18617 where map.keys() returns an IterableIterator<string>. I would have preferred to leave it as is instead of casting it to an Array<string>, since this would conform to JS standards and angular projects like ours have downlevelIteration and can use for-of loops on the IterableIterator. I had to cast it to an Array, because when I went to write the test for the new feature, I could not work with the IterableIterator, it gave me the "Type 'IterableIterator<string>' is not an array type or a string type" when I tried to loop over it.
