### ISSUE TITLE
EXCEPTION: Uncaught (in promise): Error: Access is denied.Error: Access is denied.Angular2

### ISSUE THREAD

**Issue by mohit-kanerika** [angular/angular#18628]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[✔ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[✔ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

My Angular2 or angular4 application is not working with "https" in IE 11 browser. It is working well at Chrome, Firefox, Safari.
I have developed a website in angular2. I deployed my angular2 application at AWS. It is working well with "http" and "https" in Chrome,Firefox,Safari. In IE 11 when I use URL with "http" it is working.
But not working with "https" in IE 11. I got error "EXCEPTION: Uncaught (in promise): Error: Access is denied".

![screenshot 265](https://user-images.githubusercontent.com/20517720/29165361-095d9e90-7de0-11e7-971f-3089f3da249d.png)

## Expected behavior

When I try to access my URL with "http" then it is working in all the browsers.But when I try to access URL with "https",Then It is not working in IE 11.

## Environment

<pre><code>
Angular version: 2.4 or 4

Browser:
- [ ✔] Chrome (desktop) version XX
- [✔ ] Chrome (Android) version XX
- [✔ ] Chrome (iOS) version XX
- [ ✔] Firefox version XX
- [ ✔] Safari (desktop) version XX
- [ ✔] Safari (iOS) version XX
- [ X ] IE version XX
- [ X] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
---
Possible causes:
* https://stackoverflow.com/questions/22098259/access-denied-in-ie-10-and-11-when-ajax-target-is-localhost
* https://stackoverflow.com/questions/13843083/ajax-request-access-is-denied-in-ie

Narrow down the scenario and ask for support on SO.

**Comment by rdurgarao** [comment]
+1, My Page is blank white screen in IE Browser. It working in all other browsers.

Lot of ECMA Scripting errors and promise denied errors.

**Comment by saksham-sg01** [comment]
Did you find any solution yet? @mohit-kanerika 
I'm facing the same error.

**Comment by hoangtranson** [comment]
I met this situation and not have any solution yet.
