### ISSUE TITLE
angular2, assign values to component member variables within router.events.subscribe does not trigger view update?

### ISSUE THREAD

**Issue by mrdulin** [angular/angular#18623]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

assign value to component member variables within `router.events.subscribe()` does not trigger view update.

Even I use `NgZone` and `ChangeDetectorRef`, the view still not update.

## Expected behavior

should be update the view 

## Minimal reproduction of the problem with instructions

My case steps: 

1. when navigate to other route, I will save some datas in service.
2. navigate back, I grab the saved datas from the service and assign to component variable again.
3. the component member variable is bound to `[(ngModel)]` of a `input`.

here is the code snippet: 

```ts
ngOnInit() {
    this.dataSource = new PropertyDataSource(this.paginator, this.propertyService);
    this.displayedColumns = this.tableHeaders.map((header) => header.key);
    this.selectedOption = this.propertyOptions[0];

    this.paginatorService.i18n(this.paginator, 'cn');

    this.router.events.filter((event) => event instanceof NavigationEnd).pairwise()
      .subscribe((events: any) => {
        const prevRouteUrl: string = events[0].url;
        const currentRouteUrl: string = events[1].url;

        if (prevRouteUrl.indexOf(`${currentRouteUrl}/edit`) !== -1) {
          const lastQueryCondition: IQueryCondition = this.propertyService.getQueryCondition();
          const { pageIndex, keyword } = lastQueryCondition;

          //TODO: why view not update???
          this.zone.run(() => {
            this.keyword = keyword;
            this.paginator.pageIndex = pageIndex;
          });
          console.log(this.keyword, this.paginator.pageIndex); // 'a' 0, but view not update
          this.getPropertiesByName(keyword, pageIndex + 1);

        }
      });
  }
```

html: 
```html
<input type="text" name="keyword" placeholder="keyword" [(ngModel)]='keyword' required />
```

__update:__

Even if I save the data to `localStorage`. So the issue is not about the ways I save data.

if I call `detectChanges` like this: 

```ts
...
this.paginator.pageIndex = pageIndex;
this.cdRef.detectChanges();
```

It throws an error: `ERROR Error: Uncaught (in promise): Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges`

## What is the motivation / use case for changing the behavior?

Before navigate to other route, I save some datas in service. 
And after navigate back, the component use these saved data again.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.1
- Platform:  Mac

Others:

</code></pre>

**Comment by Balaraut** [comment]
I think you have insure when you go to the new route first set the data in service use async and await or promises and after that you can change your route. 

Did you checked the data is set in service by adding console.log in service??

**Comment by mrdulin** [comment]
@Balaraut Of course. I `console.log` the saved data from service in the `subscribe` method. 
The datas exist and the assign statement is also correct. But the view does not update.

**Comment by BaluRaut** [comment]
ok, I think you need use the below code:
<code>        let timer = Observable.timer(2000, 5000);
        timer.subscribe(() => this.keyword='angular' ));
</code>

**Comment by BaluRaut** [comment]
You can refer this link : 
<a href="https://stackoverflow.com/questions/36919399/angular-2-view-not-updating-after-model-changes"> https://stackoverflow.com/questions/36919399/angular-2-view-not-updating-after-model-changes </a>

**Comment by mrdulin** [comment]
@Balaraut I tried every method. It still not work. 

By the way, I know `$scope.$digest`, `$scope.$apply`, `$rootScope.$apply`, `$timeout` service of `angular1.x`. 

But this, It doesn't make sense!  I think my case should not do this dirty work. What happened with `angular4.3.3`?

**Comment by Toxicable** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by jasonaden** [comment]
Closing based on above comment.
