### ISSUE TITLE
A simple html table problems with alignment with its dynamic headr, body caused of by component tag

### ISSUE THREAD

**Issue by titusfx** [angular/angular#18626]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Simple table with not alignment. I suppose that the problem of the component tag is not really empty. So cause this effect.

## Expected behavior

A simple html table aligned with its dynamic headr, body, etc.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/uwMm71UtH1FLFqVKfJR8?p=preview

## What is the motivation / use case for changing the behavior?

Use html table aligned with its dynamic headr, body, etc.

## Environment

<pre><code>
Angular version: 4.3.2

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.0
- Platform: Linux

@angular/cli: 1.2.6
node: 6.11.0
os: linux x64
@angular/animations: 4.3.2
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2

Others:

</code></pre>

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by titusfx** [comment]
I don't believe is a support request, the behavior is wrong. It's the simplest example possible using dynamic head and body table and doesn't work. Because the components don't really behave like empty tag. And `sounds like` it's a not understanding of the problem.
