### ISSUE TITLE
HttpClient post demo has some ambiguity

### ISSUE THREAD

**Issue by baihech** [angular/angular#18627]
## I'm submitting a...
<pre><code>
[x ] Documentation issue or request
</code></pre>

## Current behavior
See [post](https://angular.cn/guide/http#发起一个-post-请求) ,the code is:
<pre><code>
const body = {name: 'Brad'};
http
  .post('/api/developers/add', body)
  // See below - subscribe() is still necessary when using post().
  .subscribe(...);
</code></pre>
If so write,the rquest parameter is string"{name: 'Brad'}",not name: "Brad",If it is springMVC, need to write annotation `@RequestBody`,can not automatically match parameters.

## What is the motivation / use case for changing the behavior?
I think the following code might be better.
<pre><code>
const param = new HttpParams().append('name', 'Brad');
http
  .post('/api/developers/add', param)
  // See below - subscribe() is still necessary when using post().
  .subscribe(...);
</code></pre>

**Comment by jenniferfell** [comment]
@trotyl : I see that you gave this a thumbs down. We appreciate your expertise. Can you help us understand what doc is affected and if it's fine as it is today?

https://angular.io/api/common/http/HttpClient#post ?

**Comment by trotyl** [comment]
@jenniferfell The request is about using `application/x-www-form-urlencoded` rather than `application/json` in the HTTP tutorial. Even encoding is application specific, JSON is indeed considered a best practice in web API which provides typing, nesting and confirming serialize behavior in all language.

**Comment by jbogarthyde** [comment]
I'm closing this on the strength of Trotyl's recommendation for best practice.
