### ISSUE TITLE
Component lifecycle Init functions not always called before associated check function

### ISSUE THREAD

**Issue by JSMike** [angular/angular#18631]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Component lifecycle `Init` functions aren't called if `detectChanges` is called from a previous `Init` function.

## Expected behavior
Component lifecycle `Init` functions should run once before lifecycle `Checked` functions.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ywsnta

* Trigger `@Output` event in child component's `ngOnInit`
* Call `cdr.detectChanges()` from parent component on event
* Console log in `ngAfterViewInit` and `ngAfterViewChecked` of the child component.
* You'll notice `ngAfterViewInit` is never called, but `ngAfterViewChecked` is called.

## What is the motivation / use case for changing the behavior?
Passing data from child to parent component, expecting init lifecycle hooks to trigger once.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [ x ] Chrome (desktop) version 60.0.3112.90 
</code></pre>
## Comments:
This may be a regression, need to investigate.  
This may be associated with https://github.com/angular/angular/issues/17572

**Comment by Toxicable** [comment]
Works fine here
https://stackblitz.com/edit/angular-pe1usj?file=app/child.component.ts
You were getting a ExpressionChangedAfterCheckedError since you were mutating a bound value during Change Detection, after fixing that it runs `Init->ViewChecked`

**Comment by JSMike** [comment]
@Toxicable I didn't see any errors in my example, only that the lifecycle event didn't trigger. I was just pointing to the other issue because others may be getting that error if their init functions are getting skipped.

I was under the impression that when you change bound values that you should be using `cdr.detectChanges()`

Is `setTimeout()` really the proper solution? That's just getting the change to apply outside of the current lifecycle and could potentially have unintended side-effects depending on the application. Or is that not the case because of zones?

**Comment by ghetolay** [comment]
I don't know precisely what's going on but you're emitting during `ngOnInit` inside the child meaning it's not created yet and you react to it by calling `detectChanges`. This call will trigger change detection on the parent **and it's children** but remember we're still inside `ngOnInit` at child, child doesn't exist yet. 

I think you're messing up with the view state and that's why it's not recommend to use `ChangeDetectorRef` but I can't be 100% sure because I didn't check deep enough to really see what's going on. It just seems off to me.

**Comment by SanderElias** [comment]
@JSMike Yes, `setTimeout` is the proper solution.  Using the `ChangeDetectorRef` is a code-smell in most cases.

**Comment by chuckjaz** [comment]
This was fixed by #20258
