### ISSUE TITLE
routerLink queryParams and fragment return in opposite order

### ISSUE THREAD

**Issue by Manonna** [angular/angular#18630]
## I'm submitting a...
[x] Bug report 
or
[x] Documentation issue or request
</code></pre>

## Current behavior
When using routerLink with both a fragment and queryParams, routerLink generates a link with first the queryParams and the fragment at the end.

example: 
```
<a [routerLink]="['/user/bob']" [queryParams]="{debug: true}" fragment="education">
  link to user component
</a>
```
generates: /user/bob?debug=true#education

## Expected behavior
According to routerLink documentation, it should be returned in the opposite order: 

/user/bob#education?debug=true

## Minimal reproduction

[https://plnkr.co/edit/xT92m1lGjoGCM3EVa6TG?p=info](https://plnkr.co/edit/xT92m1lGjoGCM3EVa6TG?p=info)

## What is the motivation / use case for changing the behavior?
Either routerLink is behaving incorrectly or the documentation has an error.

## Environment

<pre><code>
@angular/cli: 1.2.4
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/compiler-cli: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/platform-server: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.4

Browser:
- [x] Chrome (iOS) version XX
 
For Tooling issues:
- Node version: 7.4.0
- Platform:  Mac

**Comment by Toxicable** [comment]
Could you please provide a minimal reproduction? Here's a template to get you started https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by Manonna** [comment]
Checkout this plunker:

[https://plnkr.co/edit/xT92m1lGjoGCM3EVa6TG?p=info]

It might also just be a documentation error. As I believe it may be standard convention to have the fragment at the end of the URL. Either way it is not behaving as it should according to the documentation.

**Comment by pacocom** [comment]
Same problems!

**Comment by atscott** [comment]
This is an issue with the documentation, which should be updated to show the fragment part last.
```
         foo://example.com:8042/over/there?name=ferret#nose
         \_/   \______________/\_________/ \_________/ \__/
          |           |            |            |        |
       scheme     authority       path        query   fragment
```
 https://tools.ietf.org/html/rfc3986#section-3
