### ISSUE TITLE
enableLegacyTemplate ignored in AoT compiler

### ISSUE THREAD

**Issue by hotforfeature** [angular/angular#18639]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
```ts
platformBrowserDynamic().bootstrapModule(AppModule, {
  enableLegacyTemplate: false
});
```

Related to #15555, which I realize now only fixed this option for the JIT compiler. The option is ignored for the AOT compiler.

## Expected behavior
Using `enableLegacyTemplate: false` as a bootstrap option should not replace `<template>` elements with `<ng-template>`.

## Minimal reproduction of the problem with instructions
1. Add `enableLegacyTemplate: false` to bootstrap options
2. Use a `<template>` element in an Angular component
3. Run `ng build` (no warnings with JIT compiler)
4. Run `ng build --prod` (template deprecation warning)

## What is the motivation / use case for changing the behavior?
When using web components inside Angular, they need to use native `<template>` elements.

## Environment

<pre><code>
@angular/cli: 1.2.4
node: 8.1.2
os: darwin x64
@angular/cli: 1.2.4
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/compiler-cli: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2
- Platform: Mac
</code></pre>

**Comment by vicb** [comment]
Options for AOT have to be specified in the tsconfig.json
```
{
  "compilerOptions": {
  // ...  
   },
  "angularCompilerOptions": {
    "enableLegacyTemplate": true
  }
}
```

**Comment by MickL** [comment]
@vicb Does not work for me on 4.3.4. Please reopen.
