### ISSUE TITLE
Support mixed usage of /deep/ and > (child combinator)

### ISSUE THREAD

**Issue by vilic** [angular/angular#18643]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently this would result in an error:

```less
:host /deep/ > a {
  ...
}
```

## Expected behavior

Expecting the previous less code to be compiled as something like:

```css
[_nghost-c7] > a {
  ...
}
```

## What is the motivation / use case for changing the behavior?

Directly using `/deep/` without `>` would bring unwanted possibility polluting the style of inner elements.

## Environment

<pre><code>
Angular version: 4.3.3

</code></pre>

**Comment by Bretto** [comment]
I think you should try ::ng-deep as /deep/ is deprecated...

**Comment by vilic** [comment]
@Bretto Thanks a lot!
