### ISSUE TITLE
http Observable<Response> timeout logs a huge error, avoid?

### ISSUE THREAD

**Issue by k1r0s** [angular/angular#18648]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see 

Angular Http service logs a huge error, I'd firstly though was an exception but a console.error(stack)

There's any way to avoid? I has anything to do with the environment?

Thanks

```typescript
  protected deepQuery<Res>(url: string, body: CommonRequestBody): Observable<Res> {
    return this._http.post(url, body.toJson(), this._options)
    .timeout(1000 * this.timeoutSecs)
    .map((data) => this.extractData<Res>(data));
  }

```

```
"@angular/http": "4.2.6",
"rxjs": "5.4.0",
```

**Comment by Toxicable** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
or StaackBlitz: https://stackblitz.com/fork/angular

**Comment by k1r0s** [comment]
Here you are 

http://plnkr.co/edit/a1htU9tTozWIKG6Iptvt?p=preview, how we can handle that error? which isn't an exception

**Comment by mlc-mlapis** [comment]
@k1r0s ... use `catch` ... `throw` operators as: http://plnkr.co/edit/Y1jLnU7t2jLyK9jcKWco?p=preview
