### ISSUE TITLE
Support `prependChild` in Renderer2

### ISSUE THREAD

**Issue by altschuler** [angular/angular#18645]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is `appendChild` which inserts an element at the end of the list of children of a given parent. Then there is `insertBefore` which inserts an element before another *known* element. It is currently not (easily at least, not sure if possible) to insert an element at the beginning of the list of children using only the renderer, ie. falling back to using `someNativeElement.firstChild` or similar.

## Expected behavior

I'm suggesting support for a `Renderer2` method in the style of jQuery's `prependChild`, which will insert a child as the first child of a given parent, regardless of the number of current children (if any).

I image the implementation for the `DomRenderer` would be something along the lines of

```
prependChild(parent: any, newChild: any): void {
  if (parent) {
    // according to the spec, if refChild is null the element
    // is inserted at the end of the list of children, which 
    // would be desired behavior for an empty parent
    parent.insertBefore(newChild, parent.firstChild); 
  }
}
``` 

## What is the motivation / use case for changing the behavior?

In this case I'm building a directive that inserts an element as the first child of the host element (eg an icon as the first child of a button, regardless of any text or other content already present).

**Comment by AndrewKushnir** [comment]
Closing this ticket based on https://github.com/angular/angular/pull/22273#issuecomment-729216858. Thank you.
