### ISSUE TITLE
animations: State change during animation with automatic property calculation (using '*') ignored

### ISSUE THREAD

**Issue by maximilianochs** [angular/angular#18651]
## I'm submitting a...
<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
I'm using the * property to animate the height of an accordion-component. If the animation-state changes during and ongoing transition (from height: * to height: 0px), the animation continues and ignores the new state. The style persists like the state is "closed", even if it is "open".

This only happens when using the * property. If the animation is configured with fixed height values, it respects state changes and cancels / reverts the transition. 

## Expected behavior
The animation should respect the new state, like it does when using fixed values for height.

## Minimal reproduction of the problem with instructions
I made a little example with instructions using stackblitz: https://stackblitz.com/edit/angular-kbh8tf

## What is the motivation / use case for changing the behavior?
Creation of a reusable accordion-component with unknown inner-content.

## Environment

<pre><code>
Angular version: 4.3.4

Browser:
- [x] Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by matsko** [comment]
This should fix it: https://github.com/angular/angular/pull/18787

**Comment by matsko** [comment]
@maximilianochs there should be a release later today, please test against it once it's out.

**Comment by maximilianochs** [comment]
@matsko fixed it for me, thanks 👍
