### ISSUE TITLE
Router 4.3.3 Services are not singletons when navigating with browser address bar

### ISSUE THREAD

**Issue by heike2718** [angular/angular#18652]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When navigating with browser address bar the providers and services are instanciated twice. This is extremely disturbing and may break the application when state must be globally available in the client using rxjs. 

With issue  #12869 the same behaviour when navigating programatically was solved. But the bug can still be observed when using the browser address bar for navigation. 

## Expected behavior
When using the browser address bar for navigation the singletons should not be recreated.

## Minimal reproduction of the problem with instructions
checkout https://github.com/heike2718/routing-project and follow the instructions.

## What is the motivation / use case for changing the behavior?
I don't know which motivation there was to break the singletons when navigating :/

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [X] Chrome (desktop) Version 57.0.2987.98 Built on 8.7, running on Debian 8.8 (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 52.2.0 (64-bit), running on Debian 8.8
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.10.2
- Platform:  Debian 8.8

Others:

**Comment by tytskyi** [comment]
@heike2718 lest narrow what do you mean "manually navigate"? Type "settings" and press enter?

**Comment by heike2718** [comment]
Yes, I mean typing http://localhost:4200/settings in the address bar and press enter.

**Comment by Toxicable** [comment]
Coudl you make a plunkr: https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5
or StackBlitz: https://stackblitz.com/fork/angular
 to reproduce the issue?

**Comment by heike2718** [comment]
@Toxicable I'm not so familliar with plunkr and StackBlitz. I've created this: https://stackblitz.com/edit/angular-3frtma It runs when it is exported but I don't know how to run it in the browser. 

The same sources I've hosted here: https://github.com/heike2718/routing-project

I hope this helps for reproducing. May be I misunderstood some details of routing using the browser URL?

**Comment by Toxicable** [comment]
It runs fine in the browser for me, just click the little "Open" in the top right corner of the window.
Manually navigating, via the window url, does not cause any providers to be instantiated more than once

**Comment by heike2718** [comment]
When I click the open in Firefox it starts bundling app but does not come to an end. 
When I open it with Chromium I get "Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document." Same with edge.
When I click "Open in a new Window" I see "Hello Angular 4". That is not my project. 

So I'm wondering if you really saw my project. Did you see 2 buttons labeled "log in and stay" and "login and navigate to settings"?

**Comment by Toxicable** [comment]
I did see those buttons along with the other content that's in the html and ts files
This was in Chrome

**Comment by heike2718** [comment]
OK now I tested it with Chrome 60... on windows and saw my app. 

When I click "login and stay" and then type .../settings in the address bar and press enter it again runs bundling app, and the accessToken, that should be shown is unknown what means that store has created twice thereby loosing its state. I would expect store not to recreate and see the accessToken, i.e. the behaviour when clicking "login and navigate to settings".

Why does stackblitz bundle the app when changing the route in the browser address bar? Is this the expected behaviour when changing routes via the address bar? The same holds when running the app locally. Seems as if the whole app gets reloaded when changing the URL in the browser.

All routes are configured to belong to / and all other routes than /settings are directed to /home. So I would expect the app not to reload when changing the URL in the adress bar. Did I something misunderstand?

**Comment by heike2718** [comment]
I found this comment on stackoverflow "Browser URL change can only  be caused by 2 factors: Route change inside Angular2 or user manually  type in new URL. You can subscribe to the former. **The latter will reload  the whole application** ... "  

So I understand that reloading the app when manually changing the browser URL seems to be the desired behaviour. Then this is not a bug but a feature?

What would be the best way to handle state in this case?

**Comment by mlc-mlapis** [comment]
@heike2718 ... hmm, I missed what was your idea on the beginning because manual entering URL is just the principal thing ... what would be the other way how to distribute for example some apps' links in emails?

What is your use case when a user enter a route = changing URL manually?

**Comment by heike2718** [comment]
There is no use case to do this. My users shall navigate using the links and actions of my application. But in case they accidentally manipulate the URL  I want to prevent that the application loses state. How can I handle this?

**Comment by mlc-mlapis** [comment]
@heike2718 ... it's not possible. This type of user's action is the same as pressing a reload button. You can theoretically use `BeforeUnloadEvent` implemented by browsers -> warning for users not to finish the action.

**Comment by heike2718** [comment]
OK. Thank you all a lot!
This helped me to understand the subject better. I think the issue can be closed.

Regards Heike.
