### ISSUE TITLE
Allow overriding directive selector in @View

### ISSUE THREAD

**Issue by timjacobi** [angular/angular#1865]
In large scale apps that use directives from different sources name clashes are inevitable. Hence it would be great if you could *rename* directives in the `@View` annotation.
##### Proposed syntax
```JavaScript
import {NgIf} from 'angular2/angular2';
import {ExternalDirective} from 'somewhere/else';

@View({
    template: `<div my-renamed />`,
    directives: {
        'my-renamed': ExternalDirective,
        NgIf, // not renamed, using ES6 short notation
        ...
    }
})
```

**Comment by pkozlowski-opensource** [comment]
Funny, I was about to propose sth similar :-) I guess by "renaming" you mean overriding a selector, right? Syntax will need work, but IMO the idea is here.

**Comment by timjacobi** [comment]
Yes overriding a selector is the more precise way of saying it.

**Comment by mhevery** [comment]
Dup of #915
