### ISSUE TITLE
ResponseContentType define for @angular/common/http

### ISSUE THREAD

**Issue by dahang** [angular/angular#18654]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

not defined and  the options 
## Expected behavior

has similar enum like http.
https://angular.io/api/http/ResponseContentType
and RequestOptions 
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
`HttpClient` has a option for `responseType` of `responseType?: 'arraybuffer'|'blob'|'json'|'text'` you can see this here https://angular.io/api/common/http/HttpClient#constructor

**Comment by dahang** [comment]
@Toxicable  yes I know. but I prefer a defined type.

**Comment by gkalpak** [comment]
May I ask why? :grin:

**Comment by srod** [comment]
The same for me, before using HttpClient, I could type like this :

```typescript
download(fileName: string, arrayBuffer: ResponseContentType.ArrayBuffer): void {
}
```

But not anymore ?

**Comment by trotyl** [comment]
TypeScript 2.4 already supports [String Enums](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#string-enums), you can just wrap it by yourself, no need to change in Angular side. It's assignable:

![image](https://user-images.githubusercontent.com/6059170/32500769-3a3972ba-c411-11e7-93a5-98b6e879268e.png)

**Comment by SaltyDH** [comment]
Seems like a backwards step going from provided enum to having to wrap it ourselves. Similarly for well known headers we should have HttpHeader enums for 'Authorization' etc.

**Comment by michie1** [comment]
https://angular.io/api/http/ResponseContentType should have some information about this in the deprecation notes.

**Comment by alxhub** [comment]
There is no exported type for that in `HttpClient`, it's not an enum but a type union.

**Comment by atodd-geoplan** [comment]
@michie1 no, no it really does not. it says "use @angular/common/http instead" which is not helpful at all

this is an undocumented breaking change (i am currently upgrading from 4.2 > 5) with no fix other than to reference a deprecated lib.

**Comment by dhamotharan19** [comment]
Totally agreeing with @atodd-geoplan point.

**Comment by JosXa** [comment]
You lose out on the autocompletion capabilites and thus the discoverability of different response content types. +1 for @SaltyDH saying it's a step backwards from angular's original `Http` module.

**Comment by fomenkoyegor** [comment]
pipec

**Comment by Halfist** [comment]
Seems like that Angular team encourages us, in order to migrate gracefully, define our own enum with the same name and change import path. Though, it means that one day we'll probably need to change it as well, while if they keep their enum, we don't need to do that.
