### ISSUE TITLE
AOT with route url matcher: Invalid configuration of route '': routes must have either a path or a matcher specified

### ISSUE THREAD

**Issue by vilic** [angular/angular#18662]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Getting error using route URL matcher with AOT enabled:

```
Uncaught Error: Invalid configuration of route '': routes must have either a path or a matcher specified
```

## Expected behavior

No error.

## Minimal reproduction of the problem with instructions

1. Generate a brand new project with `angular-cli` using package manager yarn.
2. Generate a component named `TestComponent`.
3. Import router module with test route using matcher:

  ```ts
  @NgModule({
    declarations: [
      AppComponent,
      TestComponent
    ],
    imports: [
      BrowserModule,
      RouterModule.forRoot([
        {
          matcher(segments: UrlSegment[]) {
            if (segments.length) {
              return {
                consumed: [segments[0]],
              };
            } else {
              return undefined;
            }
          },
          component: TestComponent,
        }
      ])
    ],
    providers: [],
    bootstrap: [AppComponent]
  })
  export class AppModule { }
  ```

4. Run `ng serve` and it should work as expected.
5. Run `ng serve -aot=true` (or ng build -prod), it gives runtime error complaining invalid configuration of route.

## Environment

<pre><code>
Angular version: 4.3.4

Browser:
- [x] Chrome (desktop) version 60.0.3112.90
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.1.2
- Platform: Windows 10
</code></pre>

**Comment by vicb** [comment]
Please attach a small repro. Thanks

**Comment by vilic** [comment]
@vicb https://github.com/vilic/bug-repros/tree/angular-18662

**Comment by jurStv** [comment]
facing this issue too
any updates on this?

**Comment by jurStv** [comment]
@vilic Have you been able to somehow fix this issue? Any workaround?

**Comment by vilic** [comment]
@jurStv No, I tried something like using computed property and quoted property. It did actually make the output look relatively correct to me (at least there would be `matcher` method in the output instead of nothing), but it doesn't actually work.

**Comment by jurStv** [comment]
So sad, that it  can't be fixed somehow :(
But anyways @vilic thanks for your effort. Should wait till @vicb have minute to look into this.

**Comment by TheRationalizer** [comment]
I am seeing the same behaviour when I try to run via a Universal server, it doesn't happen when I access the site being served via `ng serve`

https://github.com/TheRationalizer/QurangularX

**Comment by pardeep-cd** [comment]
@vilic  any updates on this,Have you been able to somehow fix this issue ?

**Comment by vilic** [comment]
@pardeep-cd nope. @hansl @vicb Any updates?

**Comment by DuncanConroy** [comment]
Same issue here since AOT was introduced. This means I can't use AOT at all. If it's to be switched on by default someday, this should be looked into :)
Is there any news on the status @vicb @hansl @vilic?

**Comment by evabat** [comment]
I have exactly the same problem, I even import my route path from a variable in environment (which uses a function to calculate the value of the variable) but no luck. The router in the url displays "undefined" but the console.log shows the variable's value properly. Any help would be appreciated-

**Comment by sn42** [comment]
Got the same problem. Removed the following lines
```
{ path: '', redirectTo: '/dashboard', pathMatch: 'full' },
{ path: '**', redirectTo: '/dashboard' }
```
so the code compiles without errors/warnings. Now, if i manually add the lines again no erros.

**Comment by kgrvr** [comment]
I think you can't provide route path from a variable or from any function. Using this way in case of AOT, on runtime the app throws error.

{ path: 'signin', component: SigninComponent } // This works

const SignIn: string = 'signin';
{ path: SignIn, component: SigninComponent } // This doesn't

I don't know the reason, but this fixes my problem. Will appreciate if someone explains this. Thanks.

**Comment by trichetriche** [comment]
Any news on that issue ? as @kgrvr stated, the AOT build works well with hard coded routes, but I can't seem to be able to use variables.

**Comment by mateusz-sawit** [comment]
You can use only exported consts with AOT. So in @kgrvr example
export const SignIn: string = 'signin';
{ path: SignIn, component: SigninComponent } // This should work

and you can not use functions (even exported) to calculate route, however you can use exported arrays and objects to map paths.

**Comment by trichetriche** [comment]
@mateusz-sawit OK thank you for the Intel, and what happens if I declare a function and give a constant the value returned by the function ?

**Comment by mateusz-sawit** [comment]
I don't remember the result but you will get error or at lest it will not be working. The const in typescript means the value will not change after declaration and the variable is declared after function call. With AOT compiller need to know the value on copile time not execution time so any function will not be called.

**Comment by mateusz-sawit** [comment]
@vilic @trichetriche as matcher is route config which accepts function you can provide exported function. You can find example in doc: https://angular.io/api/router/UrlMatcher

Whenever som NgModule config accepts function for AOT it needs to be exported function not inlined.

Verify if it works and I think thread should be closed

**Comment by kgrvr** [comment]
Well what I tried was not exactly what I posted above.
I tried it with string value in an exported const object from a different file.
And that didn't work. 
I understood what @mateusz-sawit explained above related to function call, but what I as using was a string value from a const exported object.

**Comment by mateusz-sawit** [comment]
Ok so can you post the code you are using? or some small repo.
Here is what is working for me:
```
//app.routing.ts
...
import * as ProductRoutes from "./app.product-routes";

const routes = [
  {
    path: ProductRoutes.PRODUCT1_ROUTE,
    component: Product1Component, 
    canActivate: [AuthGuard]
  },
  {path: '', component: HomeComponent, pathMatch: 'full'},
  // otherwise redirect to home
  {path: '**', redirectTo: ''}
]
@NgModule({
  imports: [
    RouterModule.forRoot(routes)
  ],
  exports: [
    RouterModule
  ]
})
export class AppRoutingModule {}

// app.module.ts
...
import {AppRoutingModule} from './app.routing';
@NgModule({
  imports: [
    AppRoutingModule,
    ....
    ],
  bootstrap: [AppComponent]
})
export class AppModule { }

// app.product-routes.ts
export const PRODUCT1_ROUTE = 'product-1-route';
export const PRODUCT2_ROUTE = 'product-2-route';
export const PRODUCT3_ROUTE = 'product-3-route';
```

**Comment by kgrvr** [comment]
Ya you're exporting each individual constant string.
What I was doing was like this:

`export const RoutingConstant = Object.freeze({
	'signin': 'signin'
});`

**Comment by mateusz-sawit** [comment]
Object.freeze() - you have function call

You probably could use:
export const RoutingConstant = {
   signin: 'signin'
}

**Comment by kgrvr** [comment]
Oh ya, Object.freeze() is a function call. Got it.
Okay will try what you recommended. Thanks. 👍

**Comment by jenniferfell** [comment]
If I understand correctly, the summary is that we could be more clear in these areas of doc:
- In AOT docs
- In router guide
- In API ref for URLMatcher

About this: (clipped from thread above)
You can use only exported consts with AOT. You can not use functions (even exported) to calculate route, however you can use exported arrays and objects to map paths.
I think you can't provide route path from a variable or from any function. Using this way in case of AOT, on runtime the app throws error.

Yes?

**Comment by mateusz-sawit** [comment]
@jenniferfell The 2 sentences  are contradictory - you can use variables and it does not throw exception but variable must be exported.
So the summary is that wherever in NgModule config (including RouterModule, TranslateModule and other) you can use only exported variables and functions (as in case of URLMatcher), but you can not use function to calculate value.

**Comment by Halfist** [comment]
So, does Angular encourages us to avoid using best practice `Object.freeze()` for constants?

**Comment by skwny** [comment]
I just ran into this same issue after compiling AOT. Based on comments above, I gathered that I cannot use function calls to produce values for paths. So for example, I went from this
```
  {
    path: R.str.login(),
    component: Login_Component,
  },
```
to this
```
  {
    path: 'login',
    component: Login_Component,
  },
```
and the error went away.

This obviously leads to reusability, testing and consistency issues so am curious if this is how all routes must be declared for AOT router code to work, or is there something that I am missing?

Thanks.

**Comment by Halfist** [comment]
@skwny, you can use constants instead of functions. This is better than plain strings.

**Comment by skwny** [comment]
@Halfist I can see that as the case for actual constants, but what about for generated route needs?   I'm attempting to use one source for all my routes. E.g. for `/o/:oid`:

```
function oRoute(oid: string) {
  return `o/${oid}`;
}
```

So that can produce `o/:oid` for the angular router paths, or `o/2wijfa09jf0923f` for the navigation action.

**Comment by Halfist** [comment]
@skwny, oh, that seems to be more complicated than my cases. Do you really need to generate them?

**Comment by skwny** [comment]
@Halfist yes , in order to retrieve the url from only one location and not risking inconsistencies.

For example, if I later change my path to `o/:oid/anotherPath`, then I would need to change it all locations that do not use the generated path. If I use the function to generate the path for all uses, I only have to modify the function.

**Comment by atscott** [comment]
Closing, as this should be resolved with the Ivy compiler (released in v9). The following example project shows routes with constants, functions, and enums all working: https://github.com/atscott/aotroutes

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
