### ISSUE TITLE
CLI build-optimizer failure

### ISSUE THREAD

**Issue by buu700** [angular/angular#18666]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`ng eject --aot --prod --build-optimizer --no-sourcemaps` generates a webpack.config.js that tries to use `PurifyPlugin` without importing it (`ReferenceError: PurifyPlugin is not defined`).

`ng build --aot --prod --build-optimizer --no-sourcemaps` fails with this error:

```
 92% chunk asset optimization
<--- Last few GCs --->

[455:0x560e167f5620]   707807 ms: Mark-sweep 1413.1 (1518.5) -> 1413.1 (1502.5) MB, 7277.9 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 7279 ms) last resort
[455:0x560e167f5620]   715214 ms: Mark-sweep 1413.1 (1502.5) -> 1413.1 (1502.5) MB, 7406.3 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x364665b1bbd9 <JS Object>
    2: def_variable [0x364665b02241 <undefined>:3551] [pc=0x4528827ac2b](this=0x1f233b8a5261 <an AST_Function with map 0x127ef311b591>,symbol=0x1f233b8bfc71 <an AST_SymbolFunarg with map 0x150b45cc9009>)
    3: visit [0x364665b02241 <undefined>:3402] [pc=0x45286bed532](this=0x2b8b84e771a1 <a TreeWalker with map 0x3e9d366dda09>,node=0x1f233b8bfc71 <an AST_SymbolFunarg with map 0x150b45cc9009>,de...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [@angular/cli]
 2: 0x560e14f2b97e [@angular/cli]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [@angular/cli]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [@angular/cli]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [@angular/cli]
 6: v8::internal::Factory::NewScopeInfo(int) [@angular/cli]
 7: v8::internal::ScopeInfo::Create(v8::internal::Isolate*, v8::internal::Zone*, v8::internal::Scope*, v8::internal::MaybeHandle<v8::internal::ScopeInfo>) [@angular/cli]
 8: v8::internal::DeclarationScope::AllocateVariables(v8::internal::ParseInfo*, v8::internal::AnalyzeMode) [@angular/cli]
 9: v8::internal::DeclarationScope::Analyze(v8::internal::ParseInfo*, v8::internal::AnalyzeMode) [@angular/cli]
10: v8::internal::Compiler::Analyze(v8::internal::ParseInfo*, v8::internal::ThreadedList<v8::internal::ThreadedListZoneEntry<v8::internal::FunctionLiteral*> >*) [@angular/cli]
11: 0x560e148b8aaa [@angular/cli]
12: 0x560e148b9b2f [@angular/cli]
13: 0x560e148be795 [@angular/cli]
14: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [@angular/cli]
15: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [@angular/cli]
16: 0x452869840bd
../commands/prodbuild.sh: line 10:   455 Aborted                 ng build --aot --prod --build-optimizer --no-sourcemaps
```

## Expected behavior

Both of these commands should work.

## Minimal reproduction of the problem with instructions

* `ng new balls ; cd balls ; ng eject --aot --prod --build-optimizer --no-sourcemaps`

* The `ng build` out of memory error can't be reproduced as easily, so maybe it only happens with sufficiently large projects. I'll get back to you on this one.

## What is the motivation / use case for changing the behavior?

Functioning as documented.

## Environment

<pre><code>
Angular version: 4.3.4
Angular CLI version: 1.3.0

For Tooling issues:
- Node version: 8.2.1
- Platform: Debian Sid x86-64 in a Docker image with 4 GB RAM allocated

Others:

</code></pre>

**Comment by Toxicable** [comment]
Sounds like an issue with the CLI which should be made here https://github.com/angular/angular-cli

**Comment by buu700** [comment]
Oops, thanks!
