### ISSUE TITLE
Proposal: ngc for JIT

### ISSUE THREAD

**Issue by trotyl** [angular/angular#18664]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently most Angular projects are using JIT for development and AOT for production as suggested in [JIT in development, AOT in production](https://angular.io/guide/aot-compiler#jit-in-development-aot-in-production). This works well in most cases (as AOT compiler not being smart enough), but introduce inconsistency between development and release, like we need to **provide different sets of polyfills configuration** for them.

But given that:

- Angular have removed all the dependency of [Metadata Reflection API](https://github.com/rbuckton/reflect-metadata) in all Decorators (https://github.com/angular/angular/commit/d9d00bd9b51e57e90f4419fb95ef498749ec0e02, https://github.com/angular/angular/commit/fcadbf4bf6d00ea5b250a8069e05b3e4bd000a29, https://github.com/angular/angular/commit/cac130eff9b9cb608f2308ae40c42c9cd1850c4d), making the tsc `emitDecoratorMetadata` the only place using it. (Which will still be consumed by Angular compiler);
- Angular compiler has been fully refactored by using [TypeScript transformer API](https://github.com/Microsoft/TypeScript/pull/13940) for compilation process (https://github.com/angular/angular/pull/17388/commits/8054adf1155bff18d5109da83fbcc8f28766f049, https://github.com/angular/angular/pull/18494/commits/e77247984aff0377ca52d0d460c6df97c14119a3, https://github.com/angular/angular/commit/679608db6543c2f9633e33841a6074548006fbe2, https://github.com/angular/angular/commit/27d901a51d1440c2ffa50ee0fb9bfc80e01b1485), it would be easy to integrate `ngc` with other build tools (https://github.com/TypeStrong/ts-loader/pull/535, https://github.com/s-panferov/awesome-typescript-loader/pull/418);
- Angular compiler already supports metadata-only / non-AOT mode ([`skipTemplateCodegen`](https://github.com/angular/angular/blob/619e625ee201d096f1c0801fd4d8d2d5d17c6ac0/packages/tsc-wrapped/src/options.ts#L26)), making it compatible with JIT process.

It's possible to get rid of that problem by using `ngc` for JIT as well.

## Expected behavior

Technically `ngc` for JIT is already fully supported in current implementation, but it would be better to:

- Well documented about the process, currently the `ngc` is hard-coded with AOT process in documentation;
- Allow `angularCompilerOptions` to work with `extends` in `tsconfig.json`, as we may need to change its setting in different environment;
- Making Angular CLI to use Angular compiler (but not AOT) in all conditions, and remove Metadata Reflection API entry in `polyfills.ts`. (AOT should still be made easy to use in all conditions, but not within this proposal);
- Remove the [last dependency](https://github.com/angular/angular/blob/cac130eff9b9cb608f2308ae40c42c9cd1850c4d/packages/core/src/reflection/reflection_capabilities.ts#L92-L93) of Metadata Reflection API. (Will be a breaking change, should be done in a later version)

*(All of the aboves could be made separate proposal if needed.)*

## Minimal reproduction of the problem with instructions

Nil.

## What is the motivation / use case for changing the behavior?

- Fully remove the dependency of Metadata Reflection API (Unified polyfills);
- Do not break any JIT or AOT user;
- Easy to migrate in most build tools.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
Similar plans is already in the works.
The goal is to have AOT the default for development by v5

**Comment by vicb** [comment]
Closing the PR as we will move out from JIT.
