### ISSUE TITLE
split off @angular/http

### ISSUE THREAD

**Issue by tycho01** [angular/angular#18667]
Follow-up on #16752.

## I'm submitting a...
<code>
[x] Feature request
</code>

## Current behavior
`@angular/http` brought the great idea of observable-based HTTP interaction, yet packages it such that it can only be used by Angular.

## Expected behavior
I'd expect any libraries to be usable in as general a context as possible rather than limiting themselves to one particular use-case.

## Minimal reproduction of the problem with instructions
- try to figure out how to use `NgModule` outside of Angular
- ask #16752
- fail to find a way

## What is the motivation / use case for changing the behavior?
Getting cool `Observable` based HTTP from Node / other frameworks / what have you.

## Environment

<pre><code>
Angular version: 5.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
</code></pre>

Note: in that earlier question I was told the same could apply to the Animations package as well. To me that one looked a bit further entrenched into actual Angular rather than just its DI, but yeah, that might be another candidate I suppose.

**Comment by Toxicable** [comment]
`@angular/common/http` is the one you'd be after.
It currently has a dependancy on `@angular/core` and `@angular/platform-browser` as seen here https://github.com/angular/angular/blob/master/packages/common/http/rollup.config.js

**Comment by amitport** [comment]
I think this is a valid expectation, and that it is important to demonstrate that libraries written for Angular can be easily used in other places. When I write a library for Angular, I want to know there is a clean path to use it with other frameworks.

In any case, it depends on https://github.com/angular/angular/issues/324 (something like 'split off @angular/di'), which was closed but can/should be re-opened.

**Comment by Toxicable** [comment]
There is a repo for DI here https://github.com/mgechev/injection-js

**Comment by amitport** [comment]
@Toxicable I know, but `@angular/common/http` (and all `@angular/*`) is not using it

**Comment by Toxicable** [comment]
yeah because because the Angular version needs things specific to Angular

**Comment by amitport** [comment]
I think it's reasonable to expect that `@angular/common/http` won't depend on " things specific to Angular" (by making an `@angular/di` core lib that doesn't). Part of the premise of Angular2+, was being more simple and inter-operable than angularjs. I will be great to see how Angular team manages to make a great http library that works smoothly with angular and can still be used anywhere.

**Comment by DaSchTour** [comment]
@tycho01 you could simply use `Observable.ajax()` which is already part of rxjs

**Comment by robwormald** [comment]
@amitport this isn't something we're likely to prioritize. We rely heavily on DI for HttpClient (and most other @angular/ libraries), and DI enables us to easily change out when running on the server. I'd something I'd like to see eventually, but quite frankly, we have far too much work to do with Angular before focusing on using it with not-Angular.

**Comment by amitport** [comment]
@robwormald, just wanted to note that I didn't suggest that HttpClient won't use DI, but that angular's own core DI lib be portable.

In any case, I hope this will enter the roadmap at some point, but of course it's not urgent. Thank you
