### ISSUE TITLE
Docs: Template Syntax sections claim that no column span property exists.

### ISSUE THREAD

**Issue by LayZeeDK** [angular/angular#18665]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
[The docs](https://angular.io/guide/template-syntax#attribute-binding) mention as an example more than one place that there is no `colspan` *property* and that an `[attr.colspan]` binding **must** be used to bind to this behavior of table cell elements. However, there is actually a `colSpan` property (notice the casing) so even though the examples are fine, the claim that there is no column span property is simply false. In fact, we are able to use a `[colSpan]` property binding.

## Expected behavior
The examples in the docs should not make false claims.

## Minimal reproduction of the problem with instructions
Read https://angular.io/guide/template-syntax#attribute-binding.

## What is the motivation / use case for changing the behavior?
There is a lot of confusion around data binding when *attributes* and *properties* have similar names. While the docs try to solve this, the false claims add to the confusion.

## Environment
<pre><code>
Angular version: 4.4.3
</code></pre>

**Comment by gkalpak** [comment]
For reference, [here][1] is the definition of the `colSpan` property in the HTML5 spec.

[1]: https://www.w3.org/TR/html5/tabular-data.html#htmltablecellelement

**Comment by kapunahelewong** [comment]
Thanks for this very helpful issue, @LayZeeDK. I've updated the Attribute Binding section and added a small bit in the example app for that section to demo the difference. Please feel free to comment on it. I'll keep my eyes open for other instances of this too.

**Comment by LayZeeDK** [comment]
Thank you for getting around to this issue, @kapunahelewong. Unfortunately, you seem to have missed the point I'm trying to make. In fact, the issue is even worse now. Docs now even more explicitly describe that
> Some HTML attributes don't have corresponding properties. colspan is one example.
> https://angular.io/guide/template-syntax#html-attribute-vs-dom-property

This is simply not true. There is a corresponding `colSpan` property on `HTMLTableCellElement`s (`<td>` and `<th>`).

Please rewrite the docs or use an example of an attribute that actually doesn't have a corresponding property.

**Comment by LayZeeDK** [comment]
The error formatting looks weird.
![image](https://user-images.githubusercontent.com/6364586/51285915-03054300-19f1-11e9-8d75-e1e0b1e1136a.png)

**Comment by LayZeeDK** [comment]
Consider including the square brackets property binding syntax:
```
<!-- Notice the colSpan property is camel case -->
<tr><td [colSpan]="1 + 1">Three-Four</td></tr>
```

**Comment by kapunahelewong** [comment]
Ah I see where you mean on the other mention. I'll fix that in #25561, a PR just for that section, Binding Syntax. (I have a bunch for a big rewrite/refactor of Template Syntax). 

Regarding the colors on the Template parse errors message, I think I can correct that via some CSS as there already exist classes for things like shell styling. I'll figure out what to do about it, though.

Fixed the syntax.

Thanks a lot for looking out and explaining everything. I really appreciate it. 💫

**Comment by LayZeeDK** [comment]
In https://pr25561-7d5664e.ngbuilds.io/guide/template-syntax#attribute-binding (current preview build [mentioned](https://github.com/angular/angular/pull/25561#issuecomment-455000946) in the PR) there is no mention at all that there is actually a `colSpan` **property** that we can bind to, using property binding.

**Comment by kapunahelewong** [comment]
@jenniferfell This issue is addressed in the Template Syntax PRs and is can be closed once they are merged. 

Removed backlog milestone.

**Comment by kapunahelewong** [comment]
Hi @LayZeeDK! Since #25770 and #26004 were merged, Iʻm going to close this issue out. If you see anymore points to address on `colSpan`/`colspan`, feel free to re-open or tag me in a new issue. Thanks for working with me on this. :)

**Comment by LayZeeDK** [comment]
I just read through the reworked guide on this topic. I'm alright with the content.

However, the formatting of the error example is still weird
![image](https://user-images.githubusercontent.com/6364586/59950768-343ddf80-9477-11e9-9106-18d2030a1c64.png)

Also mentioned in https://github.com/angular/angular/issues/18665#issuecomment-454987140
