### ISSUE TITLE
Control value isn't reset when a control is hidden with *ngIf

### ISSUE THREAD

**Issue by bhaidar** [angular/angular#18663]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have a control on the form. Attached to it is a directive *ngIf. I show/hide this control based on a certain expression.
When the condition evaluates to true, the control is shown. I type some text into the control.
Few moments later, the condition evaluates to false, hence the control is hidden from display.
Later on, the expression evaluates back to true, the control is shown with the value typed previously.

## Expected behavior
To show control and have a config/setting to clear the value once hidden and re displayed again.

## Minimal reproduction of the problem with instructions
Any sample would do here. Just add an <input type="text" /> and hide/show using *ngIf.

## Environment

<pre><code>
Angular version: ^4.0
Browser:
- [ X] Chrome (desktop) version XX
- [ X] Chrome (Android) version XX
- [ X] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ X] Safari (desktop) version XX
- [ X] Safari (iOS) version XX
- [ X] IE version XX
- [ X] Edge version XX
 
For Tooling issues:
- Node version: v6.11.0
- Platform:  Windows

**Comment by Toxicable** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by bhaidar** [comment]
Hello, thanks for pointing this out to me.

Here is a plunker.
http://embed.plnkr.co/KixLMTgaJRNhVJT3VNou/

When hiding a textbox having text and then showing it again, the data is persisted. 

What I am looking for is a way to clear the text when hiding the textbox using a directive or built-in with ngIf and configurable.

Thanks

**Comment by mlc-mlapis** [comment]
@bhaidar ... I was looking around your plunker and as I know `@ngIf` directive insert/remove a node (<input>) to/from DOM by a design. The operation has no effect on the value of `name` property. Why do you think that it should?

**Comment by ghetolay** [comment]
I agree with @mlc-mlapis, no bug here for me.

You have : 
```
<input type="text" [(ngModel)]="name" *ngIf="display" />
```
```
name = 'some string';
display = true;
```

When `display` is `true` (including first time on load) Angular will create an `input` element and bind `ngModel` value to `name`. 
When `display` is `false` the input is removed and your input doesn't fire any new value on removal so `name` value stay as it is. 

In your example you should just reset yourself the value inside `toggleDisplay()`.

**Comment by bhaidar** [comment]
Thanks guys.  If you look at the beginning of my original request I submitted a Feature Request rather than a bug.

My point is how to make the ngIf function in a sense that when the condition is false (i.e. Hide) to clear the value of the control it is attached to. That's my polint.

Thanks

**Comment by mlc-mlapis** [comment]
@bhaidar ... OK, then for the HTML base tags (when you don't have a hook `onDestroy`) use your code to reset the property. When you have `onDestroy` hook available ... your component or Control Value Accessor ... then use the hook for your processing as a reset of some property.

**Comment by lazarljubenovic** [comment]
I don't think what you suggest is expected behavior. `*ngIf` is a directive which removes a set of elements from the DOM. The fact that some data was bound to a some properties of some elements inside that set should not be connected to the fact that you're changing the view.

Model and view should remain separated. Destroying a view should not have a side-effect of destroying my data; if I want this I'll have to write custom logic for this to happen.

In your case, instead of thinking "I show/hide this control based on a certain expression [and I want this to reflect the model]", you should think "I want to change my model [and this should update the view]".

Your example is pretty basic, so I'm gonna spice it up a little bit so you can see that this approach works better when written in code instead of in templates. 

Say you have a select/option control of two options, A, B and C. When user select either of these, a different set of sub-options is presented to the user. After user fills in sub-options for A, he decides that he made a mistake and wants to choose B. After choosing B, you want to purge those A's options from the model.

Here's a snippet of a possible implementation.

```
public possibleOptions = ['A', 'B', 'C']
public chosenOption$ = this.form.get('path.to.chosen.option').valueChanges
  .do(chosenOption => {
    const notChosenOptions = possibleOptions.filter(o => o != chosenOption)
    notChosenOptions.forEach(o => this.form.get(`path.to.${o}.suboptions`).reset())
  })
```

In your template, you'd subscribe to the `chosenOption$` (using the `async` pipe) and use `ngSwitch` to show only the appropriate set of options. Since async pipe will take care of unsubscribing, you won't have to unsubscribe yourself.

**Comment by Toxicable** [comment]
@bhaidar
NgIf is working as expected.
It's responsibility is to remove/append an element from the DOM.
This does not have anything to do with bound values.
You need your own logic to clear or reset values.

**Comment by rixlabs** [comment]
ngIf is not hiding the element, as @Toxicable explained it remove/append element form the DOM.

In the case you documented the value of the input component is matter of the ngModel you have binded.

I don't see why ngIf would be responsible of cleaning your model values.

**Comment by lazarljubenovic** [comment]
> Maybe add a configuration to clear the value upon hiding. Can be handy sometimes.

@bhaidar This is not in Angular's scope. Lots of things can be "handy" sometimes but do not find place in Angular's souce code. For example, maybe things from `@angular/cdk` are super-handy, but are simply not low-level enough to be a part of the core library.

You can, however, create your own directive which hides element AND resets the associated form control. You can publish it as a library and let others use if you believe it's useful.

**Comment by kara** [comment]
Thanks for taking the time to describe the use case. As other commenters have mentioned, it's expected that the name property would not be updated when the input is removed from the view, unless you add your own logic to do this. 

You suggested adding a special config to make this happen automatically, but I'm not sure it would be worth it given that adding an option to your input would be about the same amount of work as just clearing the property in your class. In addition, we try to keep our core API as lean as possible to avoid adding code size for things that are easily implementable by the developer. For these reasons, I don't think we'll add a feature for this (at least at this time).

**Comment by Makatun** [comment]
Workaround: change "ng-if" to "ng-show" which will leave elements in DOM, Then you can query those elements and reset them on submit in model if they are hidden
