### ISSUE TITLE
Ie is not supported （ie11）

### ISSUE THREAD

**Issue by kouzigege** [angular/angular#18677]
![image](https://user-images.githubusercontent.com/6468887/29270617-4af39cfe-812a-11e7-8b2c-73353c3723ce.png)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Also https://angular.io/guide/browser-support

**Comment by hansl** [comment]
Hi @kouzigege,

It looks like you're using the Angular CLI. Angular (and the Angular CLI) supports IE 11, but you need to enable additional polyfills.  Open the `polyfills.ts` file in your project and uncomment every lines that mention you need them to support IE 11. That should help.

Closing this as answered. Thanks!

**Comment by kouzigege** [comment]
Hi @hansl ,
问题已经ok，谢谢
