### ISSUE TITLE
support destroy component|directive itself

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#18673]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

component can not destroy itself, when I have a component with a close button, clicked to remove itself, I have to write *ngIf in its parent component.

## Expected behavior

support destroy component itself

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ianjstewart** [comment]
+1 would make modals a lot cleaner to implement

**Comment by desfarik** [comment]
+1

**Comment by jatin-Maini** [comment]
+1

**Comment by Kirtlander** [comment]
+1
Why not allow a component to control its own lifetime? Otherwise we have to implement awkward child to parent communication to facilitate. Modals are one example, like an earlier poster said. Dynamically generated components are another, as is in our case.

**Comment by roneen31** [comment]
+1

**Comment by millerbarros** [comment]
+1

**Comment by darkguy2008** [comment]
Whoa, 2019, +1. Looking to use an angular animation for :leave when a video stops using "onended" from within the same component. It sucks to have to do workarounds, how come issues like these keep open for a year or two without resolution?

**Comment by muuvmuuv** [comment]
Anyone has a workaround for that? I'm creating an alert component and don't want to wrap it around a service/module.

**Comment by JoostK** [comment]
We discussed this issue and while we recognise the use-case, it can be achieved today using a structural directive that can then be injected in the component, such that the component can call some `close` method. Having a structural directive is important as it results in an embedded view that can be created and destroyed independently of the rest of the view.

**Comment by JoostK** [comment]
For example, the CDK dialog enables this by injecting `DialogRef` and [calling its `close` method](https://github.com/angular/components/blob/main/src/cdk/dialog/dialog.md). The Material components on top of CDK dialog adds a [`[mat-dialog-close]` directive](https://material.angular.io/components/dialog/api#MatDialogClose) to add closing buttons from within a template.

This may be a bit unsatisfactory as it does require coordination from a parent/cooperating directive to achieve this, but as mentioned before there needs to be some boundary from which a component can be detached.
