### ISSUE TITLE
Angular 4.3.4 released but not mentioned in changelog?

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#18679]
It seems that angular 4.3.4 has been release however there is nothing in the changelog stating this

**Comment by sdornan** [comment]
The changes are on the 4.3.x branch: https://github.com/angular/angular/blob/4.3.x/CHANGELOG.md

**Comment by hansl** [comment]
Thanks, we missed cherry-picking the 4.3.4 CHANGELOG. I fixed it here: https://github.com/angular/angular/commit/cce2ab26259e4a31bdcf45e7f3c318f0c8013239.
