### ISSUE TITLE
Router push pop native like

### ISSUE THREAD

**Issue by yelhouti** [angular/angular#18674]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Ionic Team developped a custom way when navigating between there components/pages, it allows to have a better/native like feel:
+ you have a stack of open pages
+ you can push and pop from the stack
unfortunatly this is different from how the router is build today, a routerLink replace the content of page by another. and when coding an Ionic app what you end up doing is either choose their navController and use ionic custom live cycle hooks or you use the angular router and miss the great UI experience.

## Expected behavior

It would be great if when declaring a route, if the path is nested decide if we want to open on top or replace the current path.
ex:
<pre><code>
const crisisCenterRoutes: Routes = [
  {
    path: 'crisis-center',
    component: CrisisCenterComponent,
    children: [
      {
        path: '',
        component: CrisisListComponent,
        children: [
          {
            path: ':id',
            component: CrisisDetailComponent,
            <b>push: true</b>
          },
          {
            path: '',
            component: CrisisCenterHomeComponent
          }
        ]
      }
    ]
  }
];
</code></pre>

whenever you try accessing the page /crisis-center/1, instead of CrisisDetailComponent opening inside the router-outlet of CrisisListComponent, it creates a new tag <crisis-detail-component> on top of <crisis-list-component> with a nice/customizable animation, this allows to close CrisisDetailComponent  and end up at the same scroll... you left at

**Comment by atscott** [comment]
We worked with the Ionic team to make the `OutletContext` interface used by the `Router` into `publicApi` to allow for fully supported custom router-outlet implementations. Closing, as that's the route that should be used to implement this rather than having it in the router package.
