### ISSUE TITLE
[docs/a11y]: Respect user agent's font size

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#18671]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Setting font size in browser settings does not affect the base font size of the documentation.

## Expected behavior

It should respect user's settings about font-size.

## Minimal reproduction of the problem with instructions

Go to any webpage and change the default font-size on your browser. You won't see any changes on the page.

## What is the motivation / use case for changing the behavior?

It's bad for accessibility. I have difficulties reading the `14px` font-size that the designers have chosen for the documntation on my laptop. 

Inspecting the markup and styles, I see that the font-size was not only placed in the body, but it was again placed to certain values _in pixels_ in other components.

Font-sizes should be specified in ems or rems, and the font-size on `html` element should be set to a percentage. The user should be able to control the desired font-size.

**Comment by IgorMinar** [comment]
I assume that you know that you are still able to increase the font size via `cmd + +` or `ctrl + +`.

But I agree that it would be better if we updated the stylesheets.

**Comment by sjtrimble** [comment]
@petebacondarwin can we close this? I'm having a hard time telling if #31118 was merged or not (I think it was) but just want to double check.

**Comment by petebacondarwin** [comment]
#31118 has landed on both master and 8.0.x so I guess we can close this.
