### ISSUE TITLE
TemplateUrl no reload html

### ISSUE THREAD

**Issue by Eslem** [angular/angular#1867]
When i make a change in the html file of the templateUrl this doesn't update, in Chrome takes some time and in mozilla doesn't update it at all.

**Comment by vicb** [comment]
Does Ctrl+F5 help here ? (cache issue)

**Comment by Eslem** [comment]
No for mozilla

**Comment by Bogatinov** [comment]
I concur with @Eslem, this happens a lot. 
The easiest fix is to Disable Caching in your Dev Tools while they are open.

@vicb CTRL+F5 though it should remove cache, it does not, so the HTML is not updated.

**Comment by pkozlowski-opensource** [comment]
Right, but since those HTML fragments are cached in browser, I'm not sure Angular is part of the solution here.... Closing for now, but happy to re-open if people believe that there is something on the framework level to make things easier...
