### ISSUE TITLE
HttpClient not able to retrieve plain text

### ISSUE THREAD

**Issue by dkosasih** [angular/angular#18672]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request 
```

**Current behavior**
HttpClient does not retrieve API that returns plain text.
HttpClient cannot set responseType: 'text' as Get options as described in the documentaion. 

**Expected behavior**
It should be able to accept plain text from API response.

**Minimal reproduction of the problem with instructions**
```
... ...
constructor(http: HttpClient){}

GetData(){
  // will not accept responseType: 'text' -> would not compile
  return http.get<U>(url, {responseType: 'text')
     .catch((err:HttpErrorResponse) => {
          // will get error here, although the http response code is 200
     });
}
```
Use: webpack
Dev environment run on webpack dev server
running Angular 4.3.1

**Comment by Toxicable** [comment]
Working fine here 
https://stackblitz.com/edit/angular-rh7r9f?file=app%2Fapp.module.ts

**Comment by dkosasih** [comment]
That's right. 
It works when there is no generic code applied to it.
it will work for:
```
http.get(url, {responseType: text'}
```
But, does not work for:
```
http.get<U>(url, {responseType: text'}
```

I will close the bug. 
Thanks for the quick response.

**Comment by Toxicable** [comment]
```
http.get<U>(url, {responseType: text'}
```
dosen't work because the return type is string not `U`

**Comment by dkosasih** [comment]
It's pretty much how mine is being declared
except it does not have the responseType. 
The response type is determine by the type being passed in on the wrapper method and it it does not return the type that the caller ask then it will throw error.
Something like this:
```
   getData<T, U>(url: string, data?: T): Observable<U> { 
        let params = this.appendParams(new HttpParams(), data);
        return this.httpClient.get<U>(url, { headers: this.headers, params: params })
            .pipe(
                catchError(this.handleError<U>())
            );
    }
```

**Comment by huangyanxiong01** [comment]
```ts
return this.http.get(this.url, {responseType: 'arraybuffer'});
````
It's work for me

**Comment by ngocnhan2003** [comment]
`{responseType: 'text' as 'json'}` 
It work for me.

**Comment by jpinedapetplan** [comment]
thanks as 'json'} works

**Comment by SaebAmini** [comment]
The `'text as 'json'` hack isn't required.

The version of `get` that accepts `responseType:'text'` is not generic, since you're already stating the response would be a string.

So instead of:

    return this.http.get<string>(this.url, {responseType: 'text'});

Just use the non-generic one:

    return this.http.get(this.url, {responseType: 'text'});

**Comment by ShubhamJainSJ** [comment]
@SaebAmini @ngocnhan2003 I am trying same responseType: 'text' in HttpOptions but it is not working for POST api call. My server returns a string that is basically a result description but angular httpclient always generates HttpParse error. Any idea how to solve this?

**Comment by ajahuanex** [comment]
> @SaebAmini @ngocnhan2003 I am trying same `responseType: 'text'` in `HttpOptions` but it is not working for POST api call. My server returns a string that is basically a result description but angular `httpclient` always generates HttpParse error. Any idea how to solve this?

Edit file **http.d.ts**

> ...\node_modules\@angular\common\http\http.d.ts

Change

> responseType?: 'json';

   to 

> responseType?: 'json'|'blob' |'text'; 

![Screenshot_1](https://user-images.githubusercontent.com/2767765/60125543-9c2f4700-9751-11e9-99e2-3c4dee7ea912.png)

**Comment by evilbinary** [comment]
```ts
  intercept(req: HttpRequest<any>, next: HttpHandler) {
    let newReq = req;
    newReq = req.clone({
      responseType: 'text' as 'json'
    });

    return next.handle(newReq)
```
