### ISSUE TITLE
Document injectables error

### ISSUE THREAD

**Issue by Eslem** [angular/angular#1868]
In [documentation](https://angular.io/docs/js/latest/guide/displaying-data.html#Create-a-class) the injectables for the component is wrong,  is:
```javascript
@Component({
  ...
  injectables: [DisplayComponent]
})
...
```
and has to be:
```javascript
@Component({
  ...
  injectables: [FriendsService]
})
```

**Comment by vicb** [comment]
Thanks for the report.
What about submitting a PR to https://github.com/angular/angular.io ?

**Comment by Pacane** [comment]
It was fixed in this [PR](https://github.com/angular/angular.io/pull/100)

**Comment by vicb** [comment]
thanks to both of you
