### ISSUE TITLE
Animation filter blur bug in chrome

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular#18687]
I have just tested the issue below with the new animations, it still does not work:
https://github.com/angular/angular/issues/11460

Now it doesn't give an exception anymore, it just will not show the image.

**Comment by matsko** [comment]
@LanderBeeuwsaert ok thanks for bringing that up. Can you please put together a code example on https://stackblitz.com/ please?

**Comment by LanderBeeuwsaert** [comment]
Hey Matsko,

https://angular-teswxe.stackblitz.io/

I've added a code sample, but now I'm completely lost.
When I use the component in my application, the blur effect does not work (same 4.3.4 animations), however on stackblitz it does.
Also, on stackblitz the opacity does not go to 0 each time, which should be the case every time showFirst/showSecond goes true => false, right?
Oh well, if you want you can close, I don't get it but will look for a work-around.

greetz

**Comment by vicb** [comment]
Missing a repro demonstrating the bug, closing
