### ISSUE TITLE
HttpClient doesn't parse an error response in IE11

### ISSUE THREAD

**Issue by alexeikostevich** [angular/angular#18682]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The _error_ field of [HttpErrorResponse](https://angular.io/api/common/http/HttpErrorResponse) represents a not parsed string for a 400 response in IE11.
Chrome and Firefox returns an object instead.

## Expected behavior
IE11 returns an object by analogue with other browsers.

## Minimal reproduction of the problem with instructions
Make a [HttpClient.put](https://angular.io/api/common/http/HttpClient#put) request to an endpoint that returns a 400 response in IE11.
See this [plunker](http://plnkr.co/edit/3v6dJRQHhp09Ut0segdW?p=preview) for an example.

## What is the motivation / use case for changing the behavior?
It is expected to have a consistent behavior across all browsers.

## Environment
Angular version: 4.3.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10
- Platform:  Windows

**Comment by pjayes** [comment]
I've also encountered this problem today with IE9.
After some debugging, the problem seems to be in this line : https://github.com/angular/angular/blob/4.3.5/packages/common/http/src/xhr.ts#L182

**Comment by PascalHonegger** [comment]
I use this workaround for my error parsing until this issue is resolved:
```csharp
const errorObject = (typeof(httpError.error) === 'string') ? JSON.parse(httpError.error) : httpError.error;
```

**Comment by dherges** [comment]
Is error response body parsing implemented altogether?

#### 400 Bad Request

![2017-09-29 13_09_52-developer tools - https___morlk200 agfahealthcare com_u_wound__redirect_fragment](https://user-images.githubusercontent.com/901354/31013715-a6192fca-a517-11e7-8890-8738f0d4e305.png)

![2017-09-29 13_10_30-developer tools - https___morlk200 agfahealthcare com_u_wound__redirect_fragment](https://user-images.githubusercontent.com/901354/31013716-a61971ba-a517-11e7-99fc-f35ff375a470.png)

#### Version

```
"@angular/common@~4.4.3":
  version "4.4.3"
```

**Comment by dherges** [comment]
From looking at [HttpXhrBackend#handle() in packages/common/http/src/xhr.ts#L175-187](https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts#L175-L187), response body parsing is not implemented for "non-ok" responses.

And since `req.requestType = "json"` by default, the [xhr.responseType is text](https://stackoverflow.com/a/7100005)

Is this intended?

Can we change issue header to "HttpClient doesn't parse error response body"?

**Comment by h4k1m0u** [comment]
I'm having the same issue (error returned as a string instead of an object) on `Firefox` on Linux, after I've updated either of `Angular` or `Angular-cli`, as I didn't have any problem with an older version of these two.

**Comment by h4k1m0u** [comment]
I've updated to `Angular-cli` 1.4.9 and now it's working (My previous version was I believe 1.4.4).

**Comment by PascalHonegger** [comment]
Was fixed with pull request #19773 (Angular 4.4.6)

**Comment by alexeikostevich** [comment]
Great news! I have tested in Angular 5.0.1 and can't reproduce the issue anymore. Thank you for looking at this!

**Comment by gkalpak** [comment]
I am closing the issue then. Thx for confirming!
(If anyone is still facing problem, please open a new issue.)
