### ISSUE TITLE
Send event only to targeted directive

### ISSUE THREAD

**Issue by junajan** [angular/angular#1869]
It would be great to have some tool to send events only to specific directive, something like:
```javascript
 $directive("timeAgo").$event("hearthbeat", new Date().getTime());
```
Usecase example: I have one service, which translates dates to more human readable format like "one second ago". In view, there is directive which is calling this service for translation but if I want to update translations in time I have to use $interval in each instance of directive or $broadcast hearthbeat to rootScope and listen on it with directives..

**Comment by vicb** [comment]
Seems like you're targeting ng 1 ?
If it is the case please use https://github.com/angular/angular.js, this repo is ng 2

**Comment by junajan** [comment]
@vicb that was fast reply .. thank you

**Comment by vicb** [comment]
could you please close this if n/a ?

**Comment by junajan** [comment]
sure.. thanks
