### ISSUE TITLE
ngfor checkbox gets crazy

### ISSUE THREAD

**Issue by alexfung888** [angular/angular#18699]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

an array of checkboxes
click a box, and two or three or four boxes change state.
The bound variable is updated correctly, just the screen appearance is crazy. 

## Expected behavior

each box working independent of each other

## Minimal reproduction of the problem with instructions

use *ngFor on a md-checkbox, or on a <td> enclosing md-checkbox

http://plnkr.co/edit/eg1yzFUSyckmj0mK1mq4?p=preview

## What is the motivation / use case for changing the behavior?

To edit an array of booleans

## Environment

<pre><code>
Angular version: 4.3.4

Browser:
- [x ] Chrome (desktop) version 60.0.3112.90
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.4  
- Platform:  W10 64 bit 1703
- CLI 1.3.0
- TS 2.4.2
Others:

As the four examples show:
1) fail no matter control is inside a form or not
2) fail with or without material
3) does not fail without ngFor

</code></pre>

**Comment by vicb** [comment]
In this case you have to use `trackBy` (read the docs for more info):

```
// ts
export class AppComponent {
 
  getIndex(index) {
    return index;
  }
  
}


// html
      <td  *ngFor='let c of c4; let i = index; trackBy: getIndex'>
        <input type='checkbox'
        [(ngModel)]='c4[i]'
        name='c4{{i}}'
          >
      </td>

```

**Comment by alexfung888** [comment]
@vicb
Thanks. I didn't know I need to use trackBy in this situation.

**Comment by alexfung888** [comment]
@vicb I just learn that there is a simpler way to write it:

```
     <td  *ngFor='let c of c4; let i = index; trackBy: i'>
        <input type='checkbox'
        [(ngModel)]='c4[i]'
        name='c4{{i}}'
          >
      </td>
```
I think trackBy: accepts any template expressions, because whatever we write there is translated into 
```
[ngForTrackBy]='xxx'
```

**Comment by alexfung888** [comment]
Oops the information I got is completely wrong. Angular only accepts a function for trackBy.

Must stick with your code.

```ts
  @Input()
  set ngForTrackBy(fn: TrackByFunction<T>) {
    if (isDevMode() && fn != null && typeof fn !== 'function') {
      // TODO(vicb): use a log service once there is a public one available
      if (<any>console && <any>console.warn) {
        console.warn(
            `trackBy must be a function, but received ${JSON.stringify(fn)}. ` +
            `See https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html#!#change-propagation for more information.`);
      }
    }
    this._trackByFn = fn;
  }
```
