### ISSUE TITLE
[bug] Invalid property names in animation styles cause dom bug.

### ISSUE THREAD

**Issue by realappie** [angular/angular#18701]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Making any typos in the styles function doesn't throw any run time errors. So invalid all CSS properties are completely fine. Beside that it creates a weird bug where the element is being duplicated over and over in the DOM. 

Example:
![](https://i.gyazo.com/0749a41efd16148facefe2a4869289f3.gif)

## Expected behavior

A run time error and no weird duplication on the element that's being animated.

## Minimal reproduction of the problem with instructions

1. Spam the only button on the page
2. Thats it

[Reproduction link](https://stackblitz.com/edit/animation-test)

## What is the motivation / use case for changing the behavior?

Its very hard to debug this weird animation bug if there is no error thrown. I made a typo and it took me longer than a month of searching and giving up to finally track the issue. Having any run time error or at least no weird DOM duplication bug would help a lot.

## Environment

<pre><code>
Angular version: 4.3.0 ( But issue was present in recent versions as well)

Browser:
- [x] Chrome (desktop) version 59
- [x] Firefox version 54

**Comment by matsko** [comment]
This should land next week: https://github.com/angular/angular/pull/18718

**Comment by realappie** [comment]
@matsko That was quick! Would you mind having a look at PR [17792](https://github.com/angular/angular/pull/17792)? Its an animations bug fix which has been in the review process since June.

**Comment by Delagen** [comment]
Seems it broke animation for prefixed browsers #18921

**Comment by mhevery** [comment]
Please don't comment on closed issues, instead create new ones referring to this one. @matsko
