### ISSUE TITLE
[Question] How is it possible to render a list of variable components?

### ISSUE THREAD

**Issue by joelrich** [angular/angular#1870]
Is it somehow possible to render a list of variable components? Using switch is not an option since it must be possible to import component types from other modules which are therefore unknown to the core application at compile time.

An example use case might be a notification list which supports different types of notifications. All notification types have it's own component which extend from a base component.

Here are two examples how I imagine this could look like. In the first example it would render a list of notifications with a variable type. The notification data is passed as a single property to each component.
```html
<ul>
    <li *for="#notification of notifications">
        <notification *is="{{notification.type}}" data="{{notification.data}}" />
    </li>
</ul>
```
In the second example it would pass each property of the `notification.data` object as a separate property to the notification component.
```html
<ul>
    <li *for="#notification of notifications">
        <notification *is="{{notification.type}}" *properties="{{notification.data}}" />
    </li>
</ul>
```

Does Angular 2 already support a feature like this? If not, what do you think about it?

**Comment by jelbourn** [comment]
There is the `DynamicComponentLoader` available which can probably do what you're thinking of. To see an example, look at `dialog.js` in the source. The API, though, will definitely be changing.
