### ISSUE TITLE
NgUpgrade should provide convenience for injecting '$scope.$resolve' for working with AngularJS routers

### ISSUE THREAD

**Issue by rkirov** [angular/angular#18716]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, resolved objects need to be injected with:
```typescript
   constructor(@Inject('$scope') public $scope: ng.IScope) {
    this.resolvedObj = this.$scope.$resolve.resolvedName;
```

## Expected behavior

It would be nice to have directly `$resolve`, like:

```typescript
   constructor(@Inject('$resolve') public $resolve: MyResolvedInterface) {
    this.resolvedObj = this.$resolve.resolvedName;
```

**Comment by gkalpak** [comment]
Actually, I was thinking about making the resolved values themselves injectables. E.g. something like:

```ts
// Assuming the following route/state configuration...
state('angular_with_resolve', {
  url: '/angular_with_resolve_route',
  template: '<ng2-component-resolve></ng2-component-resolve>',
  resolve: {
    resolveNg2: getResolvedObj,
  }
});

// ...you would be able to inject `resolveNg2` in `Ng2ComponentResolve` like this...
@Component({
  selector: 'ng2-component-resolve',
  ...
})
class Ng2ComponentResolve {
  constructor(@Inject('resolveNg2') public resolvedObj: MyResolvedInterface) {}
  ...
}
```

Wouldn't that be more close to how it works in Angular?
@rkirov, can you confirm this would be indeed preferrable?

**Comment by petebacondarwin** [comment]
My understanding is that we would need to create a new injector for each instance of a route to be able to inject these resolved values, right?

**Comment by gkalpak** [comment]
Since we would be instantiating a downgraded component, we could add the values on the injector we are already creating [here][1]. (That was my off-the-top-of-my-head idea at least :grin:)

[1]: https://github.com/angular/angular/blob/1e1833198dbe18bcc432ce3acf3aa808cf6b6884/packages/upgrade/src/common/downgrade_component_adapter.ts#L61

**Comment by petebacondarwin** [comment]
I am not sure how that would work - but then I am still in holiday mode so my brain is not back up to speed yet.
How would ngUpgrade know about the resolves for the creation of the downgraded component?

**Comment by gkalpak** [comment]
It would put anything on `scope.$resolve` onto the injector (keys being the string injection tokens and values being the injected values).

**Comment by petebacondarwin** [comment]
Hmm, that's a rather hard-coded approach, no? What if ui-router added a new concept that also needed to be available? Would we have to update ngUpgrade again?

**Comment by gkalpak** [comment]
Yes, that approach is specifically targeting `$resolve` (which has been around in `ngRoute` and `uiRouter` for a while now). The idea is to allow people write hybrid apps that are as close as possible to the final, pure Angular app.

Happy to discuss more generic approaches (but I couldn't come up with one :smiley:).

**Comment by gkalpak** [comment]
Due to the low priority and low demand for this feature, I don't think we will ever get to implementing it at this point.
