### ISSUE TITLE
Document new options for the ngc compiler

### ISSUE THREAD

**Issue by vicb** [angular/angular#18717]
relates to https://github.com/angular/angular/pull/18494

new options are:

```
{
  "angularCompilerOptions": {
    "disableTransformerPipeline": false by default, true to use the 4.x compiler
  }
}
```

- `expectedOut`
- i18n options,
- `genDir` is deprecated and need to be removed

 see details in https://github.com/angular/angular/pull/18494/files#diff-1b0f798b88d8fa078e3656a27bd08117R100

**Comment by kapunahelewong** [comment]
Hey @vicb I'd like to document this, but I'm not sure what to say about the options above. Could you share some thoughts on what I should touch on and where I should put it? Thanks!

**Comment by vicb** [comment]
@kapunahelewong @chuckjaz knows the status - he's the expert for anything compiler related.

**Comment by JoostK** [comment]
- `disableTransformerPipeline` is no longer around.
- `genDir` is not currently documented.
- `expectedOut` is specific to `ngc_wrapped` and not understood by the Angular compiler.
- It's unclear to me the i18n options that this refers to.

Given all the above, I'd consider this non-actionable at this point.
