### ISSUE TITLE
Cannot set production mode when boostrapping AOT

### ISSUE THREAD

**Issue by benoitconfait** [angular/angular#18727]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Enabling production mode is not possible when using bootstrapModuleFactory, as the zone creation set it in locked, thus ending with 

> Cannot enable prod mode after platform setup.

## Expected behavior

The zone creation should just read the **devMode** variable instead of calling the false getter **isDevMode()** that also set the runModeLocked to true.

## Minimal reproduction of the problem with instructions
Using a classic bootstrap file for AOT with the factory:
```
// bootstrap
import { platformBrowser } from '@angular/platform-browser';
import { enableProdMode } from '@angular/core';
import { InvestmentModuleNgFactory } from '../aot/onboarding.investment/app.module.ngfactory';

import 'rxjs/add/operator/map';
import 'rxjs/add/operator/do';

enableProdMode();
platformBrowser().bootstrapModuleFactory(InvestmentModuleNgFactory);
```

The following code is executed from core package **application_ref** ( angular/packages/core/src/application_ref.ts):

  ```
 bootstrapModuleFactory(moduleFactory) {
        return this._bootstrapModuleFactoryWithZone(moduleFactory);
    }

    _bootstrapModuleFactoryWithZone(moduleFactory, ngZone) {
        if (!ngZone)
            ngZone = new NgZone({ enableLongStackTrace: isDevMode() });
...
            });
        });
    }
```

When the zone is created, it calls **isDevMode**, thus locking the application prod mode.

```
function enableProdMode() {
    if (_runModeLocked) {
        throw new Error('Cannot enable prod mode after platform setup.');
    }
    _devMode = false;
}
function isDevMode() {
    _runModeLocked = true;
    return _devMode;
}
```

As _**bootstrapModuleFactoryWithZone** is private, it's impossible to supply a zone to avoid this trigger.

## Environment

<pre><code>
Angular version: 4.3.4  and previous

Browser:
- [ x] Chrome (desktop) version 60.03112.90
- [ x] Firefox version 54.0.1
 
</code></pre>

Likely to happen on every browser.

**Comment by JoostK** [comment]
I don't quite understand the reported issue, as `enableProdMode()` in `main.ts` is exeuted before bootstrap using. Regardless, it's possible to fully customize the NgZone using `BootstrapOptions.ngZone` as it was introduced in #17672, so that should have made the workaround pssobile. I don't think this issue is relevant anymore today, so I'm closing this issue.
