### ISSUE TITLE
Time format failed in edg browser =>  date:"HH:mm:ss" 

### ISSUE THREAD

**Issue by maoguiyou** [angular/angular#18724]
## I'm submitting a...

<pre>{{ time | date:'HH:mm:ss' }}<code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

use datePipe at edg browser {{ time | 'HH:mm:ss'}} , ps: time = 1502847102745
expect string：‘09:31:29 ’    at edg result：‘09:00:8/16/2017 9:35:10 AM:8/16/2017 9:35:10 AM ’

## Expected behavior

{{ time | 'HH:mm:ss'}}  => ‘09:31:29 ’

## Environment

<pre><code>
Angular version: ^2.3.1  && ^4.0.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version 20.10240.17146.0
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ceau** [comment]
you can see this issue [date pipe formatter doesn't format minutes and seconds properly in IE 11.0.9600.18350 and Edge](https://github.com/angular/angular/issues/9524)

**Comment by vicb** [comment]
Closing as this has been fixed in 5.x by @ocombe 

The Date pipe uses the ICU API in 4.x and the implementation are broken.
