### ISSUE TITLE
Doc: Add section about DI / reading multiple directives / tokens of the same element

### ISSUE THREAD

**Issue by macjohnny** [angular/angular#18729]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior
There should be a section in the docs covering how to use DI to read multiple directives / tokens of an element / a list of elements.
Currently, when using `
@ViewChildren(SomeComponent, {
  read: RouterLink
})
` 
you can query for elements of `some-component`  and get their corresponding `routerLink` directive.
In order to simultaneously get multiple directives / tokens of the same element, 
for a single element you would add template references like 
`<some-component routerLink="some-route" #refRouterlink="RouterLink" #refSomeComponent #refElementRef="ElementRef">`  
and for a list of elements like you expect in `ViewChildren` you would have to write a directive like
```
@Directive({
  'selector': 'some-component'
})
class MyDirective {
  constructor(
    public elementRef: ElementRef,
    @Self() @Inject(RouterLink) public routerLink: RouterLink,
    @Self() @Inject(SomeComponent) public someComponent: SomeComponent
  ) { }
}

@Component({
selector: 'my-app', 
template: `
<some-component routerLink="someroute1">
<some-component>
<some-component routerLink="someroute3">
` 
})
class MyAppComponent {

  @ViewChildren(MyDirective) myDirectiveList: QueryList<MyDirective>;

  ngAfterViewInit() {
    this.myDirectiveList.forEach(myDirective => {
      console.log(myDirective.elementRef)
      console.log(myDirective.routerLink)
      console.log(myDirective.someComponent)
    })
  }
}
```
See e.g. https://www.bennadel.com/blog/3087-querying-for-multiple-viewchild-directives-on-a-single-element-in-angular-2-beta-17.htm#comments_49303 and https://github.com/angular/angular/issues/18280

**Comment by zoechi** [comment]
I suggested to create a docs issue. 
My suggestion was about adding docs for `@ViewChild(ren)()` `@ContentChild(ren)()` which seem to got lost during past updates.
Currently there isn't anything else except the class name and the info where the class is declared https://angular.io/api/core/ViewChild

This shouldn't make the original issue's intent less valid. I just wanted to add some context.

**Comment by macjohnny** [comment]
@zoechi the documentation for `@Viewchild` can be found at https://angular.io/api/core/ViewChildDecorator. There should at least be a link in https://angular.io/api/core/ViewChild

**Comment by macjohnny** [comment]
this didn't catch too much attention. in the meantime the `@ViewChil(ren)` decorator docs have been fixed, so I am closing this.
