### ISSUE TITLE
Transformer should warn users if no entry points are provided

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#1872]
See https://github.com/angular/angular/issues/1836

Context: We currently need to run the angular transformer on the angular codebase with no entry points, which is why we have no warnings currently.

Potential solutions:
- Create a "private" transformer in `lib/src/` for the angular codebase that does not require an entry point
- Codegen the necessary files in the angular codebase and check them in so the angular transformer does not need to be run except in consumer code

**Comment by kegluneq** [comment]
A few more details on this:

The phases below refer to those defined in the [Angular 2 Dart Transformer doc][1].

We currently run the full `angular2` transformer on anything that declares an `@Injectable` in order to generate the code to prime the `reflection` layer so we can remove `dart:mirrors` from the app (phases 2, 3, & 4a). If a dependency declares a `@Component` or `@Directive`, we also need to process it to generate `DirectiveMetadata` (phase 4b), `setters` for binding (phase 5) and process its `template` (phase 6). For dependencies we do not need to run phase 1, which removes the import of `dart:mirrors` and replaces it with a call to the generated code.

Fixing this issue would mean splitting the transformer into two:
1. Run on dependencies, encompassing phases 2-6, not requiring `entry_points`
2. Run on the app itself, encompassing all phases, requires `entry_points`.

This will involve some migration pain as `pubspec.yaml`s will need to be changed to refer to the new transformer, so the earlier it can be done the better.

[1]: https://docs.google.com/document/d/1Oe7m96QnOrilxpH1B5o9G_PnfBGovhH-n_o7RU6LYII/edit#heading=h.8kxtxfm4leo6

**Comment by jakemac53** [comment]
If somebody wants to release a package which has no entry points, but just supplies some `@Injectable` classes, then they would need to use this same thing right? If I understand that correctly then my proposed solution would be to simply add a `no_entrypoints` option to the existing transformer. If that option is not supplied then the `entry_points` option must be supplied. Alternatively we could force an `entry_points` option, but allow it to be empty?

**Comment by kegluneq** [comment]
That does seem like an easier solution, I'm all for it.

**Comment by kegluneq** [comment]
With the addition of [targeted transformers][] this is now doable without requiring an additional parameter for packages that only need codegen. My plan looks like this:

1. Packages with no entrypoints use only `angular2/transform/codegen`
2. Packages with entrypoints also use `angular2/transform/reflection_remover`
3. When `--mode=debug`, `reflection_remover` outputs an additional asset whenever it successfully modifies a file.
4. When `--mode=debug`, `reflection_remover` has an additional `AggregateTransformer` phase which looks for these additional assets and reports back if none are found.

[targeted transformers]: https://github.com/angular/angular/wiki/Advanced-Transformer-Configuration

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
