### ISSUE TITLE
Multiple instances are created when a component provides both NG_VALUE_ACCESSOR and NG_VALIDATORS

### ISSUE THREAD

**Issue by mrpmorris** [angular/angular#18734]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When a component is included in a view that provides both NG_VALIDATORS and NG_VALUE_ACCESSOR the constructor is executed 3 times.

## Expected behavior

Only the component in the view should be created, the other providers should use the instance on which they were created.

## Minimal reproduction of the problem with instructions

Run the following plunker and look in the console log for how many instances are created
https://plnkr.co/edit/1Aztv5K2gqIc4erNgRnG?p=preview

## What is the motivation / use case for changing the behavior?

It is not possible to create a component that provides NG_VALUE_ACCESSOR and NG_VALIDATORS at the same time - This is useful for scenarios such as the example, a component that lets the user display reactive form control's errors by specifying a formControlName.

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.2.1  
- Platform:  Windows 10 

Others:

</code></pre>

**Comment by trotyl** [comment]
It's expected, otherwise you'll need `useExisting` instead of `useClass`.

**Comment by kara** [comment]
As @trotyl mentioned, you'll need to switch to `useExisting` when providing if you would like Angular to use the existing instance. Closing, as this works as expected.

**Comment by mrpmorris** [comment]
Ah, thankyou!
