### ISSUE TITLE
GET /app/node_modules/@angular/common/bundles/common.umd.js/http.js 404 (Not Found)

### ISSUE THREAD

**Issue by olegkot** [angular/angular#18735]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm using SystemJS Module loader:
This is the config part of it:
map: {
            'ng-loader': './systemjs.angular.loader.js',

            // our app is within the app folder
            'app': './app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
            '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            'tslib': 'npm:tslib/tslib.js',

            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
        },

My app.module.ts looks like this:
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { UpgradeModule } from '@angular/upgrade/static';
import { HttpClientModule } from "@angular/common/http";
import { SessionServiceA } from "./login/session.service";
import { StorageService } from "./local-storage/storage.service";

@NgModule({
    imports: [
        BrowserModule,
        UpgradeModule,
        HttpClientModule
    ],
    providers: [
        StorageService,
        SessionServiceA
    ]
})

export class AppModule {
    constructor(private upgrade: UpgradeModule) { }
    ngDoBootstrap() {
        this.upgrade.bootstrap(document.body, ['caseApp']);
    }
}

When it tries to import "HttpClientModule" from "@angular/common/http" it fails with the error:

_Unhandled Promise rejection: (SystemJS) XHR error (404 Not Found) loading http://localhost:6061/app/node_modules/@angular/common/bundles/common.umd.js/http.js
	Error: XHR error (404 Not Found) loading http://localhost:6061/app/node_modules/@angular/common/bundles/common.umd.js/http.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:6061/app/node_modules/zone.js/dist/zone.js:1075:39)
	    at ZoneDelegate.invokeTask (http://localhost:6061/app/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:6061/app/node_modules/zone.js/dist/zone.js:191:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:6061/app/node_modules/zone.js/dist/zone.js:498:34)
	    at invokeTask (http://localhost:6061/app/node_modules/zone.js/dist/zone.js:1370:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:6061/app/node_modules/zone.js/dist/zone.js:1388:17)
	Error loading http://localhost:6061/app/node_modules/@angular/common/bundles/common.umd.js/http.js as "@angular/common/http" from http://localhost:6061/app/app.module.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:6061/app/node_modules/@angular/common/bundles/common.umd.js/http.js_

## Expected behavior

HttpClientModule to be imported without errors.

## What is the motivation / use case for changing the behavior?

working on the hybrid AngularJS/Angular app, intend to use HttpClient module in my Angular Services

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Try adding this to your config

```
    '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js',
```

**Comment by olegkot** [comment]
Thank you, Eric. It actually, worked.

**Comment by ymz-rocks** [comment]
Please note! The full configuration is actually

```
  '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js',
  'tslib': 'npm:tslib/tslib.js'
```

Credit to [@yurzui](https://stackoverflow.com/a/45634620/4062197)

**Comment by facundofarias** [comment]
Cool! That was it. Thanks @ymz-rocks

**Comment by kfiryahalom** [comment]
map: {
            // our app is within the app folder
            app: 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js',
            'tslib': 'npm:tslib/tslib.js',

            // other libraries
            'rxjs': 'npm:rxjs',
        },



and its still not working.. any idea?

**Comment by abhisheksaxena741** [comment]
Will it work for Angular 2.2.0 version ?

**Comment by asad-sangla** [comment]
[https://stackoverflow.com/questions/46372269/systemjs-unexpected-token-asp-net-angular-4]

**Comment by asad-sangla** [comment]
[](https://stackoverflow.com/questions/46372269/systemjs-unexpected-token-asp-net-angular-4)

**Comment by asad-sangla** [comment]
[](https://stackoverflow.com/questions/46372269/systemjs-unexpected-token-asp-net-angular-4)

**Comment by asad-sangla** [comment]
[(SystemJS) Unexpected token < ( ASP.net + Angular 4)
](https://stackoverflow.com/questions/46372269/systemjs-unexpected-token-asp-net-angular-4)
