### ISSUE TITLE
ERROR in Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tamit0402** [angular/angular#18746]
/d/NG4-Template/ng4-gui-template (master)
$ ng serve 
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200**
Hash: b6d111819e485b408477
Time: 49517ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 252 kB {5} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 302 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 239 kB {5} [initial] [rendered]
chunk    {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 409 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.88 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Maximum call stack size exceeded
webpack: Failed to compile.

Using dependencies
"dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.25",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "angular-resizable-element": "^1.2.1",
    "angular-tree-component": "^3.8.0",
    "angular2-cookie": "^1.2.6",
    "angular4-color-picker": "^1.4.2",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "ionicons": "^3.0.0",
    "lodash": "^4.17.4",
    "ng-click-outside": "^2.3.5",
    "ng2-ace-editor": "^0.2.3",
    "ng2-bootstrap-modal": "^1.0.1",
    "ng2-charts": "^1.5.0",
    "ng2-interceptors": "^1.3.0-1",
    "ng2-right-click-menu": "^0.0.11",
    "rxjs": "^5.1.0",
    "t-json-viewer": "^1.2.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.4",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/lodash": "^4.14.68",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.4",
    "protractor": # "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }

-

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
