### ISSUE TITLE
The example of 'detectChanges()' is missing in Documentation

### ISSUE THREAD

**Issue by edward9145** [angular/angular#18747]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/api/core/ChangeDetectorRef
The Example of the method 'detectChanges()' is missing.
There is some description of the usage, but no demo source.
looks like it uses the same example as the 'detach()' method.

## Expected behavior

Could you add a live demo example of 'detectChanges()' ?

## Environment

<pre><code>
Angular version: Version 4.3.5-build.33980+sha.b2f4d53.

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
Related issue https://github.com/angular/angular/issues/22370

**Comment by jbogarthyde** [comment]
The current `detach()` example does also show the use of `detectChanges()`. 
Closing this - Please re-open if you have further concerns or suggestions.
