### ISSUE TITLE
Cannot re-export component under a different name

### ISSUE THREAD

**Issue by andrewseguin** [angular/angular#18752]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Failing to AOT compile the Material library when re-exporting a component/module.

```
Type MdAutocomplete in /usr/local/google/home/andrewjs/git/material2/dist/packages/demo-app/material/typings/index.d.ts is part of the declarations of 2 modules: MatAutocompleteModule in /usr/local/google/home/andrewjs/git/material2/dist/packages/demo-app/material/typings/index.d.ts and MdAutocompleteModule in /usr/local/google/home/andrewjs/git/material2/dist/packages/demo-app/material/typings/index.d.ts! Please consider moving MdAutocomplete in /usr/local/google/home/andrewjs/git/material2/dist/packages/demo-app/material/typings/index.d.ts to a higher module that imports MatAutocompleteModule in /usr/local/google/home/andrewjs/git/material2/dist/packages/demo-app/material/typings/index.d.ts and MdAutocompleteModule in /usr/local/google/home/andrewjs/git/material2/dist/packages/demo-app/material/typings/index.d.ts. You can also create a new NgModule that exports and includes MdAutocomplete in /usr/local/google/home/andrewjs/git/material2/dist/packages/demo-app/material/typings/index.d.ts then import that NgModule in MatAutocompleteModule in /usr/local/google/home/andrewjs/git/material2/dist/packages/demo-app/material/typings/index.d.ts and MdAutocompleteModule in /usr/local/google/home/andrewjs/git/material2/dist/packages/demo-app/material/typings/index.d.ts.
```
## Expected behavior

Successful AOT compile

## Minimal reproduction of the problem with instructions

Clone the angular material branch here: https://github.com/andrewseguin/material2/tree/export-issue

Run `gulp aot:build` to initialize the AOT compiler. Error should appear when it hits the `aot:compiler-cli` stage.

Once the `aot:build` errors, the compiler can be run by using `gulp aot:compiler-cli` to see the error

The only [bit of added code](https://github.com/andrewseguin/material2/commit/630ea26c279018395952192bacf207563a396768) is found in `public_api.ts`
```
export {MdAutocomplete as MatAutocomplete};
export {MdAutocompleteModule as MatAutocompleteModule};
```

**Comment by jelbourn** [comment]
@ocombe We're running into this again with Angular Material with our latest build setup / package structure.

**Comment by jelbourn** [comment]
More follow-up: it seems like the problem has to do with the fact that we tried putting the ex-export aliases in our root `@angular/material` "entry-point" while `ngc` is now called individually for each component. So it's something like the compiler not resolving the origin for an alias when it's in a different package (or it just can't find that other package).

We can attempt to work around this by moving the re-exports if it's hard to fix.

**Comment by ocombe** [comment]
the module de-duplication is unique per bundle file, and it's only working if the re-exported module is in one specific file, if you're doing it for multiple packages it might not work
I'll check your setup tomorrow and see if that's the case, and how we can fix it (either in angular or material)

**Comment by jelbourn** [comment]
@ocombe I figured that was the case and just worked around it in https://github.com/angular/material2/pull/7193

**Comment by ocombe** [comment]
Oh nice!

**Comment by jelbourn** [comment]
Not sure if we want to _ever_ support this feature, in which case this issue could track that.

**Comment by tbosch** [comment]
Closing for now. Please reopen when needed.
