### ISSUE TITLE
ElementRef error

### ISSUE THREAD

**Issue by OdaiTu** [angular/angular#18750]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

just inject the  private elementRef: ElementRef in my constrctor

![image](https://user-images.githubusercontent.com/12837840/29420236-16a4c19c-837a-11e7-8088-a58d8837cea2.png)

## Environment

<pre><code>
Angular version: 2.4.10

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by OdaiTu** [comment]
@alexzuza  it works for another component but in this component not

i have a videos component it works fine !
but i copyed the inject and import to news component comes up this error
 see: 

videos component 

![image](https://user-images.githubusercontent.com/12837840/29421324-68c9177c-837d-11e7-97be-acd9f93144dc.png)

![image](https://user-images.githubusercontent.com/12837840/29421333-766ca894-837d-11e7-8623-3ff4b5d3851b.png)
![image](https://user-images.githubusercontent.com/12837840/29421359-85ef8804-837d-11e7-8bdb-02d84070d800.png)



works GooD !!

but the same  import and  private el: ElementRef in another component comes up an error !

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
