### ISSUE TITLE
Not able to read CSRF token in IE11 Angular 4.3.5

### ISSUE THREAD

**Issue by bipinkumarsingh** [angular/angular#18764]
## I'm submitting a issue regarding the CSRF token not working in IE 11  Version 11.0.9600.18697. 

Angular is not able to read the CSRF token in IE 11  Version 11.0.9600.18697. 
Due to this getting "403 Forbidden " in Internet Explorer.
While same is working fine with Chrome Version 56.0.2924.76 .

## Current behavior

I read in Angular documentation that Angular provide in built support for CSRF token , it reads the token from Cookie and sends with the header and Its working fine with Chrome.

The same code is not working in IE ,in above mentioned version.

## Expected behavior

The expected behavior is , same should be working the both the browsers, ie IE and Chrome.

## Minimal reproduction of the problem with instructions

Backend Spring Security Code for CSRF token.

<pre>
<code>
  protected void configure(HttpSecurity http) throws Exception {
	    	CookieCsrfTokenRepository cctr=new CookieCsrfTokenRepository();
	    	cctr.setCookieHttpOnly(false);
	    	http
	    	.addFilterAt(casAuthenticationFilter(), BasicAuthenticationFilter.class)
	    	.cors()
	    		.and()
	    		.csrf().csrfTokenRepository(cctr)
	    		.and()
	    	.logout()
	    			.logoutUrl("/perform_logout")
	    			.logoutSuccessHandler(customLogoutSuccessHandler);
	    }
	    
</code>
</pre>

I tried reading cookie value using following code , but its always return blank value in IE11 while everything works fine in Chrome.

Tried to implement XSRFStrategy , its gives   blacn  xsrfToken value in IE.

<pre>
<code>
export class MyXSRFStrategy implements XSRFStrategy  {
      _cookieName :string = 'XSRF-TOKEN';
       _headerName :string = 'X-XSRF-TOKEN';     
  configureRequest(req) {
        const  xsrfToken = ɵgetDOM().getCookie(this._cookieName);
        console.log("CSRF Token--->>"+xsrfToken);   /// Prints blank value in IE 11 , but prints value in Crome 
        if (xsrfToken) {
            req.headers.set(this._headerName, xsrfToken);
        }
    }
}
</code>
</pre>

Tried to read the cookie in Javascript 
This method returns blank value for the Cookie in IE 11 but  return valid  cookie value in Chrome .

<pre>
<code>
public getCookie(name: string) {
    let ca: Array<string> = document.cookie.split(';');
    let caLen: number = ca.length;
    let cookieName = `${name}=`;
    let c: string;
    for (let i: number = 0; i < caLen; i += 1) {
      c = ca[i].replace(/^\s+/g, '');
      if (c.indexOf(cookieName) == 0) {
        return c.substring(cookieName.length, c.length);
      }
    }
    return '';
  }
</code>
</pre>

## Environment

I am using below versions :

<pre><code>
Angular version: 

@angular/cli: 1.3.0
node: 6.10.2
os: win32 x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.5

Browser:
- [ ] Chrome (desktop) Version 56.0.2924.76 
- [ ] IE version Version 11.0.9600.18697

 
For Tooling issues:
- Node version: 6.10.2  
- Platform:  Windows  7 

Others:

</code></pre>

**Comment by bipinkumarsingh** [comment]
After debugging , I found this is not the issue of Angular
The issue was with Spring  Security.

**Comment by Bosco77** [comment]
Hello Bipinkumarsingh

We have found the same Issue, can you explain where the problem was in Spring Security?
Thank you so much, 
Regards
