### ISSUE TITLE
extracting dataURL or blob from sanitized image data to upload to firebase

### ISSUE THREAD

**Issue by skk2142** [angular/angular#18766]
I'm using angular2 DOM sanitizer to read an image file. I want to upload this file to the firebase storage. However, I am unable to find a way to convert the sanitized image to a blob or something that can be uploaded. 

I'm using the function to read the image file. 
```
readImage2(inputValue: any): Observable<any> {
    var file:File = inputValue.files[0];
    return this.ng2ImgMaxService.compress([file], this.maxImageSize).mergeMap( (result) => {
      const compressedImage = window.URL.createObjectURL(result);
      const compressedImageTrusted=this.sanitizer.bypassSecurityTrustUrl(compressedImage);
      return Observable.create((observer) => {
          observer.next({imageUrl: compressedImageTrusted});
      })
  })
}
```

In this code, I want to upload the compressedImageTrusted file to firebase storage. This file has a type `SafeUrlImpl` which I'm not sure how to convert to something that I can upload to a firebase storage. Any help would be appreciated.

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
