### ISSUE TITLE
recurse function in digest cycle calls apply on non-function

### ISSUE THREAD

**Issue by richbai90** [angular/angular#18762]
## I'm submitting a bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

An object enters the recurse function with a key name of value. If `ast.type` matches `AST.CallExpression` (not sure what determines that) and `ast.fitler` is falsey, the digest cycle attempts to call `apply` on the value which is not a function. 

## Expected behavior

recurse should check that the value of `value` is indeed a function before calling apply. Making the change fixes the issue
```
... : function(scope, locals, assign, inputs) {
          var rhs = right(scope, locals, assign, inputs);
          var value;
          if (rhs.value != null && typeof rhs.value.apply === 'function') { // Make sure that rhs.value.apply exists
            ensureSafeObject(rhs.context, self.expression);
            ensureSafeFunction(rhs.value, self.expression);
            var values = [];
            for (var i = 0; i < args.length; ++i) {
              values.push(ensureSafeObject(args[i](scope, locals, assign, inputs), self.expression));
            }
            value = ensureSafeObject(rhs.value.apply(rhs.context, values), self.expression);
          }
          return context ? {value: value} : value;
        };
```

## Minimal reproduction of the problem with instructions

I am genuinely uncertain how to reproduce the error, it's occurring in an application that I inherited, but it seems to occur during a digest cycle triggered by an asynchronous load of an array of objects, being repeated over in `ng-repeat` Here are the screen shots

![image](https://i.stack.imgur.com/Iocqi.png)
![image](https://i.stack.imgur.com/eaL9B.png)
 
## What is the motivation / use case for changing the behavior?

Fix the error being reported in the console

## Environment

<pre><code>
Angular version: 1.5.7

Browser:
- [x] Chrome (desktop) version 60.0.3112.90
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
It appears your question is for AngularJS
This is the Angular repo
I would advise posting your question on the AngularJS repo instead https://github.com/angular/angular.js

**Comment by jasonaden** [comment]
Closing as this belongs on [AngularJS](https://github.com/angular/angular.js)
