### ISSUE TITLE
Arbitrary "Module build failed: Error".

### ISSUE THREAD

**Issue by Taisho** [angular/angular#18768]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Once `npm start` is running any change to the source code (usually as small as a single line) can trigger "Module build failed: Error" at random. The error given is vague and seems to be totaly unrelated to the most recent changes introduced to the code. This is clealry an error in the build chain, as restarting `npm start ` clears it. It appears quite too often and quickly becomes very annoying. This spoils the development process

```
ERROR in ./src/app/admin/users/users.module.ts                         
Module build failed: Error         
    at WebpackCompilerHost.populateWebpackResolver (/home/tichomir/web-technologies/angularjs/vehicle-check/client/node_modules/@angular/cli/no
de_modules/@ngtools/webpack/src/compiler_host.js:135:51)               
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/tichomir/web-technologies/angularjs/vehicle-check/client/node_modules/@angu
lar/cli/node_modules/@ngtools/webpack/src/plugin.js:371:32)            
    at <anonymous>                                                     
    at process._tickCallback (internal/process/next_tick.js:188:7)     
 @ ./src async                                                                                                                                 
 @ ./~/@angular/core/@angular/core.es5.js                                                                                                      
 @ ./src/main.ts                                                                                                                               
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts  
```                                                                       

## Expected behavior

Changes to the source code should trigger rebuilding the affected component without (unrelated) errors

## Minimal reproduction of the problem with instructions

Run npm start, then begin editing source code of your project

## What is the motivation / use case for changing the behavior?

The development process is spoiled by frequently waiting for complete recompilation of the project

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chromium (desktop) 60.0.3112.101 (Developer Build) (64-bit)
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

In this case, `npm start` doesn't tell anything about the environment you are running in. Also, from the stack trace you pasted it looks like this is an error in Webpack's module resolver, but really unclear how to reproduce this issue.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by Taisho** [comment]
@jasonaden Thanks for your comment. Ultimately I managed to resolve the problem by checking out the project at a new location from our company's SVN repository. Probably some intermediate files left by the automatic build process caused the issue
