### ISSUE TITLE
Allow @NgModule to dictate common html templates & common component code templates trough it's Declarations array

### ISSUE THREAD

**Issue by Jonathan002** [angular/angular#18770]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Environment
Angular version: 4.2.6

Browser:
- [ x  ] Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2  
- Platform:  

Others:

</code></pre>
### Versions.
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
macOS (Sierra)

node: 8.1.2
os: darwin x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/compiler-cli: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/platform-server: 4.2.6
@angular/router: 4.2.6
@angular/tsc-wrapped: 4.2.6
@angular/upgrade: 4.2.6

### Desired functionality.
What would like to see implemented?
I would like @NgModules to be able provide **Declared** components a common html template and common component code template. By adding an object to the **declarations** array, I hope to link up the components to common code template files as shown below:

e.g. someModule.module.ts
```typescript
@NgModule({
  declarations: [
         {
            'html-template': 'some-template-file.html',
            'code-template': 'some-component-template-file.ts',
            'declaration-list-to-apply': [
                     HomeComponent,
                     SomeOtherComponent,
            ]
         },
        RegularComponentWithNoTemplate,
        {}, //adding different templates to these components etc
  ]
})
```

e.g. some-template-file.html

```html
<template-top>
     <!-- add common html code here like header/logo components -->
</template-top>

<!-- specific template code written by the component itself -->

<template-bottom>
      <!-- add common html code here but for bottom of components -->
</template-bottom>
```

e.g. some-component-template-file.ts

```typescript
// common decorator code 
// e.g. add the same animation to all components
@Component({
      animations: [fadeAnimation],
      host: {
           '[@fadeAnimationTrigger]' = 'state' 
      }
})

// common component code 
// e.g. do something OnInit to all components
export commonComponent implements OnInit {
       ngOnInit() {
            //do something repetative... 
      }
}
```

What is the usecase?
The use would be to make development time faster by allowing faster implementation of common code between comonents.

**Comment by pkozlowski-opensource** [comment]
So I _feel_ like this issue is about sharing code between components and I _feel_ like we've got basic building blocks in place:
* one can use _inheritance_ to extend components
* one can create smaller components and use them in other components (_composition_)
* one can create directives to share some low-level behaviour

Given the above and the fact that we are pondering move away from `NgModule`s we are not going to implement this proposal. Thnx for the suggestion though - it _shows_ that creating components it a _bit_ cumbersome and we are trying to improve this. Stay tuned!
