### ISSUE TITLE
Stitch together individual transform properties in animation style({...})

### ISSUE THREAD

**Issue by intellix** [angular/angular#18783]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I've created a coin flip animation that lifts and spins. It's easy to calculate this with keyframes like:

**Scale:** 1, 2, 1
**RotateY:** 0deg, 2700deg, 5400deg

But now my manager walks in and says: Wouldn't it be cool if we could have it go slow-motion as it's reaching it's peak and then fall back down normally again. In my mind I guess the only change I should have to make is the rotate value. I can maybe do something like:

**RotateY**: 0deg, 2700deg, 2800deg, 2900deg, 5400deg

But whilst I'm playing around with these, I also have to get the scale correct using the same calculations as well. It would be awesome if we could declare transform properties individually and have them merged by Angular Animate like:

```ts
keyframes([
  style({
    scale: 1,
    rotateY: 0,
  }),
  style({
    rotateY: 2700,
  }),
  style({
    scale: 2,
    rotateY: 2800,
  }),
  style({
    rotateY: 2900,
  }),
  style({
    scale: 1,
    rotateY: 5400,
  }),
])
```

## Expected behavior

I would expect the above individually supplied transform properties to get stitched together to equal something like the following: 

```ts
keyframes([
  style({
    transform: 'scale(1) rotateY(0deg)',
  }),
  style({
    transform: 'scale(1.5) rotateY(2700deg)',
  }),
  style({
    transform: 'scale(2) rotateY(2800deg)',
  }),
  style({
    transform: 'scale(1.5) rotateY(2900deg)',
  }),
  style({
    transform: 'scale(1) rotateY(5400deg)',
  }),
])
```

## What is the motivation / use case for changing the behavior?

To make working with multiple transform property animations much easier

**Comment by matsko** [comment]
There is something along the lines of this planned shortly after when 5.0.0 is out. The idea here would be that any custom property can be defined and then translated to some CSS equivalent (much like how `rotateX: "..."` would translate into `transform: rotateX(...)`.

**Comment by matsko** [comment]
I did have a prototype of this for 4.0.0 :), but things got busy :(

**Comment by matsko** [comment]
@intellix the plan is to open up `style()`, `animate()` and some other methods to allow a function to be passed in. This way a third party plugin can be created which allows for the CSS transform `x,y,scale,rotate` values.
