### ISSUE TITLE
Lazy Loading error when using AOT and Rollup

### ISSUE THREAD

**Issue by seanishok01** [angular/angular#18785]
## I'm submitting a...

<pre><code>
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[*] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
i am using Angular version 4.03 below is my Package.json. For development mode i use the systemJS and production mode i use AOT and rollup. I am facing error "systemjs.import is not a function"when i do lazy loading module with AOT and rollup but the same works with systemJS. Below are my routing details

## Expected behavior
Lazy loading module should work with AOT and rollup. i am using system js for dev mode and AOT + rollup for production mode. Please provide me fix or alternate syntax to lazy load the module using AOT + rollup without using webpack.

## Minimal reproduction of the problem with instructions
Routing details:
Parent Component:
export const appRoutes: Routes = [
   { path: '', redirectTo: '/today', pathMatch: 'full' },
    { path: 'today', loadChildren: 'app/today/today.module#TodayModule' },
];

Child Component:
export const todayRoutes: Routes = [
    { path: 'today', component: TodayTabsComponent }
];
## Environment

<pre><code>
Angular version: ^4.0.3
Package.Json:
 "dependencies": {
    "@angular/animations": "^4.0.3",
    "@angular/common": "^4.0.3",
    "@angular/compiler": "^4.0.3",
    "@angular/compiler-cli": "^4.0.3",
    "@angular/core": "^4.0.3",
    "@angular/forms": "^4.0.3",
    "@angular/http": "^4.0.3",
    "@angular/platform-browser": "^4.0.3",
    "@angular/platform-browser-dynamic": "^4.0.3",
    "@angular/platform-server": "^4.0.3",
    "@angular/router": "^4.0.3",
    "bootstrap": "3.3.7",
    "core-js": "2.4.1",
    "crypto-js": "^3.1.9-1",
    "rxjs": "5.4.2",
    "systemjs": "0.19.40",
    "zone.js": "^0.8.4",
    "@types/chai": "4.0.1",
    "@types/crypto-js": "3.1.32",
    "@types/mocha": "2.2.41",
    "@types/node": "6.0.46",
    "gulp": "3.9.1",
    "gulp-typescript": "^3.2.0",
    "rimraf": "^2.5.4",
    "rollup": "^0.45.0",
    "rollup-plugin-commonjs": "^8.0.2",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-plugin-uglify": "^2.0.1",
    "typescript": "2.4.1",
    "del": "3.0.0"
  }

Browser:
- [*] Chrome (desktop) version XX
- [*] Chrome (Android) version XX
- [*] Chrome (iOS) version XX
- [*] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [*] IE version XX
- [*] Edge version XX
 
For Tooling issues:
- Node version:v6.10.0
- Platform: Windows

Others:
Visual Studio 2015 Enterprise with Dot net core.
</code></pre>

**Comment by trotyl** [comment]
Code splitting for lazy routes is not a functionality provided by Angular. In Angular CLI, there's specific [webpack loader](https://github.com/angular/angular-cli/blob/9a2e35d5ef4f9f4446e837bb530574dbc1d99209/packages/%40ngtools/webpack/src/lazy_routes.ts#L48-L59) to help with that. Also there're some 3rd-party one like [angular-router-loader](https://www.npmjs.com/package/angular-router-loader).

You can write your own Rollup plugin to do that. But unfortunately, [code splitting for Rollup](https://github.com/rollup/rollup/issues/372) hasn't come yet, you may need to use some workaround to achieve that.

If you don't mind runtime loading, you can provide your own [NgModuleFactoryLoader](https://angular.io/api/core/NgModuleFactoryLoader) which doesn't depend on SystemJS.

**Comment by seanishok01** [comment]
@trotyl Can you please provide me some sample to convert the System JS to webpack loader. Also can you please provide me information about what is runtime loading and how to implement (any sample). Will runtime loading works with AOT and Rollup as well as systemJS?

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
