### ISSUE TITLE
Angular 4 can't set CSRF-TOKEN in header

### ISSUE THREAD

**Issue by Majed93** [angular/angular#18792]
Wondering if anyone here can help me with this issue i have posted on stackoverflow

https://stackoverflow.com/questions/45765990/angular-4-cant-set-csrf-token-in-header

I have a spring boot RESTful service which i making requests to. The response sets the Set-Cookie header with XSRF-TOKEN but when sending a request no headers or cookies are set with CSRF token value.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
