### ISSUE TITLE
Issue in Dynamic component Creation example at Plunker (https://angular.io/generated/live-examples/dynamic-component-loader/eplnkr.html)

### ISSUE THREAD

**Issue by saurabhahuja852** [angular/angular#18797]
## I'm submitting a Documentation issue

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In  example for Dynamic Component Loader (https://angular.io/guide/dynamic-component-loader) at Plunker (https://angular.io/generated/live-examples/dynamic-component-loader/eplnkr.html)  below issue came in console while running

ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'Bombasto'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?

## Expected behavior

There must be no isssue .

## Minimal reproduction of the problem with instructions

1)Click the plunker  link https://angular.io/generated/live-examples/dynamic-component-loader/eplnkr.html
2) Open console .
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version 60.0.3112.101 (Official Build) (32-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
Resolution :+1: 
In ad-banner.component.ts file at link https://angular.io/generated/live-examples/dynamic-component-loader/eplnkr.html 
code inside ngAfterViewInit() method must be surrounded by setTimeout 
setTimeout(()=>{
this.loadComponent();
    this.getAds();
},0)
By doing Angular will process this line of code in next tic for avoiding one-time devMode unidirectional-data-flow-violation error.

**Comment by alexzuza** [comment]
Solution is using `ngOnInit` instead of `ngAfterViewInit`

https://plnkr.co/edit/HhlFcpqjH6ehaQV27PDm?p=preview

**Comment by tom10271** [comment]
I got 
```
Error: (SystemJS) XHR error loading https://run.plnkr.co/ejYBjI2KlHwUqsSq/app/ad-banner.component.ts
	Error: XHR error loading https://run.plnkr.co/ejYBjI2KlHwUqsSq/app/ad-banner.component.ts
	    at Zone.runTask (https://unpkg.com/zone.js@0.7.4/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (https://unpkg.com/zone.js@0.7.4/dist/zone.js:345:33) [<root>]
	Error loading https://run.plnkr.co/ejYBjI2KlHwUqsSq/app/ad-banner.component.ts as "./ad-banner.component" from https://run.plnkr.co/ejYBjI2KlHwUqsSq/app/app.module.ts
	    at Zone.runTask (https://unpkg.com/zone.js@0.7.4/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (https://unpkg.com/zone.js@0.7.4/dist/zone.js:345:33) [<root>]
	Error loading https://run.plnkr.co/ejYBjI2KlHwUqsSq/app/ad-banner.component.ts as "./ad-banner.component" from https://run.plnkr.co/ejYBjI2KlHwUqsSq/app/app.module.ts
```

**Comment by petebacondarwin** [comment]
I think this is a docs issue, rather than the underlying AIO application. @wardbell, @Foxandxss et al?

**Comment by Foxandxss** [comment]
It is a docs issue yes. Angular v4 changed the behavior but the doc wasn't updated.

**Comment by jenniferfell** [comment]
Thank you. I think this issue has been resolved. https://angular.io/guide/dynamic-component-loader#resolving-components now uses ngOnInit. If you are still experiencing a problem, please open a new issue. Thank you.
