### ISSUE TITLE
NGC: `SourceContent` in Sourcemaps is not the actual TS code but rather the transpiled JS

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#18790]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I use `NGC` to compile the TS, and I have set `inlineSources: true` in my tsconfig it seems that the `sourcesContent` in the `.js.map` is the transpiled JS rather than the actual TS sourcecode. 

## Expected behavior
`sourcesContent` to contain TS sourcecode (Same as what `tsc` does)

## Minimal reproduction of the problem with instructions
Typescript source code
```ts
import { Component, NgModule } from "@angular/core";

@Component({
    selector: "my-component",
    template: "<div></div>"
})
export class MyComponent { }

@NgModule({
    declarations: [
        MyComponent
    ]
})
export class MyComponentModule { }
```
tsconfig.json
``` json
"sourceMap": true,
"inlineSources": true
```
outputted .js.map with `ngc`
```js
"sourcesContent": [
        "import { Component, NgModule } from \"@angular/core\";\n\n\nexport class MyComponent {\n\nstatic decorators: DecoratorInvocation[] = [\n{ type: Component, args: [{\n    selector: \"my-component\",\n    template: \"<div></div>\"\n}, ] },\n];\n/** @nocollapse */\nstatic ctorParameters: () => ({type: any, decorators?: DecoratorInvocation[]}|null)[] = () => [\n];\n}\n\n\nexport class MyComponentModule {\n\nstatic decorators: DecoratorInvocation[] = [\n{ type: NgModule, args: [{\n    declarations: [\n        MyComponent\n    ]\n}, ] },\n];\n/** @nocollapse */\nstatic ctorParameters: () => ({type: any, decorators?: DecoratorInvocation[]}|null)[] = () => [\n];\n}\ninterface DecoratorInvocation {\n  type: Function;\n  args?: any[];\n}\n"
    ]
```

outputted .js.map with `tsc`
```js
 "sourcesContent": [
        "import { Component, NgModule } from \"@angular/core\";\n\n@Component({\n    selector: \"my-component\",\n    template: \"<div></div>\"\n})\nexport class MyComponent {\n\n}\n\n@NgModule({\n    declarations: [\n        MyComponent\n    ]\n})\nexport class MyComponentModule {\n\n}"
    ]
```

NB: I have remove some parts from the Sourcemaps files, and tsconfig to only show what is relevant to the issue.

Angular version: 4.3.5

**Comment by jasonaden** [comment]
As far as I know, TypeScript doesn't support going all the way back to the `.ts` sources. You could look at a project like [sorcery](https://github.com/Rich-Harris/sorcery) to fix this issue.

**Comment by alan-agius4** [comment]
So if typescript doesnt supirt this how does rhe sourcemaps with tsc are
fine? Ie with typescript content? As per my example above?
