### ISSUE TITLE
Compile error when using sass variable (import)

### ISSUE THREAD

**Issue by m98** [angular/angular#18802]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[* ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I am trying to add platform-support (server-side rendering) for my Angular web app based on [this simple tutorial](https://coursetro.com/posts/code/68/Make-your-Angular-App-SEO-Friendly-(Angular-4-+-Universal)), everything works as expected until I add a global `.scss` file as my variables (things like colors, sizes,...), the task that builds the project is ` ng build --prod && ngc` and then a server runs it (`ts-node src/server.ts`).

let's say that variable file name is `_global.scss` which places in `src/app/shared/_global.scss`, and here is its content:
```
/* _global.scss*/
$main-color:#6600ff;
$main-background:#eeeeff:
```
now when I run the `ng build --prod && ngc` task, it fails (before having a global scss it was working as expected). Here is what I get:
error image:
![screenshot from 2017-08-21 13-22-44](https://user-images.githubusercontent.com/7496103/29511265-e31a1730-8673-11e7-8915-d098f1c658ba.png)

The error is already in the image above, but here is the error text:
```
Error: Compilation failed. Resource file not found: /home/mohammad/Projects/others/ang4-seo/src/app/shared/_global
    at ModuleResolutionHostAdapter.readResource (/home/mohammad/Projects/others/ang4-seo/node_modules/@angular/compiler-cli/src/compiler_host.js:387:19)
    at CompilerHost.loadResource (/home/mohammad/Projects/others/ang4-seo/node_modules/@angular/compiler-cli/src/compiler_host.js:250:33)
    at Object.get (/home/mohammad/Projects/others/ang4-seo/node_modules/@angular/compiler/bundles/compiler.umd.js:25757:107)
    at DirectiveNormalizer._fetch (/home/mohammad/Projects/others/ang4-seo/node_modules/@angular/compiler/bundles/compiler.umd.js:14104:43)
    at /home/mohammad/Projects/others/ang4-seo/node_modules/@angular/compiler/bundles/compiler.umd.js:14220:68
    at Array.map (native)
    at DirectiveNormalizer._loadMissingExternalStylesheets (/home/mohammad/Projects/others/ang4-seo/node_modules/@angular/compiler/bundles/compiler.umd.js:14220:14)
    at /home/mohammad/Projects/others/ang4-seo/node_modules/@angular/compiler/bundles/compiler.umd.js:14223:26
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
Compilation failed
```

I've read some of @tbosch comments which was saying that `ngc` will not compile `sass/scss`, but I am already doing `build --prod` the project first, and then calling `ngc`. but it seems I got something wrong 

## Expected behavior
First of all the documentation is not covering platform-server and there are some confusions, it would be good if there was a simple tutorial on how to use platform-server, beside that Angular-cli could support it as well; But thanks for the all hard works you're doing.
The current expected behavior for me is that I do expect that support imports (or maybe there is a way that I don't know anything about it!)

## Minimal reproduction of the problem with instructions
Here is the[ tutorial](https://coursetro.com/posts/code/68/Make-your-Angular-App-SEO-Friendly-(Angular-4-+-Universal)) I created the simple new angular app with server-side rendering based on it.
You just need to import a  variable/global `.scss` file into another `.scss` file.

(I even tried to solve the problem by importing the `_global.scss` into `.angular.cli.json` style imports, but it did not work either.)

## Environment
<pre><code>
@angular/cli: 1.3.1
node: 7.10.0
os: linux x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/platform-server: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5

Browser:
- Google Chrome Version 59.0.3071.86 (Official Build) (64-bit)
</code></pre>

**Comment by Toxicable** [comment]
Angular does not directly support SASS. Angular can only deal with CSS to handle styling, SASS must be run through a preprocessor before it can be compiled by Angular, therefore it is likely an issue with the build system you are using rather than Angular

**Comment by m98** [comment]
@Toxicable, yes, I said before that @tbosch said `ngc` will not deal with `scss` and my question is then, how does the platform-server work when the app used `sass`?

I think most websites will use less or sass in order to make their jobs easier and maintainable.

**Comment by Toxicable** [comment]
`platform-server` works exactly the same, the sass must be compiled into css before `platform-server` will touch it

**Comment by m98** [comment]
@Toxicable Thanks for your comment.

I knew it needs that `css` should be already compiled that platform-server works and `ngc` can compile.

But I was thinking the `ngc` will use the already compiled (build --prod) which is in `dist`

Can you please describe how can this be done? As you said for using `platform-server` we need to have `css` compiled.

**Comment by mishra-ankit** [comment]
Have you set .angular-cli as below ?
```
  "defaults": {
    "styleExt": "scss",
    "component": {}
  }
```

**Comment by m98** [comment]
Hello @jeffbcross

Do you have any idea about this? 
I found out it's not a bug, but there should be a way for developers can do it

**Comment by sandangel** [comment]
Can you share your repo? I will give it a try. I think the problem here can be solved with angular-cli stylePreprocessorOptions config.
