### ISSUE TITLE
New HttpClient does not send cookies with PATCH/POST

### ISSUE THREAD

**Issue by zygimantas** [angular/angular#18804]
## I'm submitting a...

<pre><code>
[ x ] Bug report  
</code></pre>

## Current behavior

The request does not contain any cookie headers.

![cookies](https://user-images.githubusercontent.com/102076/29519030-725a125a-8684-11e7-936a-58b5be10ce56.png)

![httprequest](https://user-images.githubusercontent.com/102076/29519034-75b869e2-8684-11e7-8e72-75486935a6a3.png)

![request](https://user-images.githubusercontent.com/102076/29519036-7a25adf0-8684-11e7-94ce-3a8bd4b347db.png)

## Expected behavior

All cookies should be added to request.

## Additional information

Cookies are sent with GET request:

![get_request](https://user-images.githubusercontent.com/102076/29519504-627286b8-8686-11e7-8f2f-b4973b069c72.png)

By the way, I use http interceptor (and interceptor works in general, because "accept-language" header is correctly added):

```
@Injectable()
export class ApiRequesInterceptor implements HttpInterceptor {
    public intercept = (request: HttpRequest<any>, next: HttpHandler) => {
        return next.handle(request.clone({
            setHeaders: {
                accept: "application/json",
                "accept-language": "en",
                "content-type": "application/json"
            },
            withCredentials: true
        }));
    }
}
```

And request code is simple:

```
this.httpClient.patch<CustomModel>(
    `/api/${id}`,
    JSON.stringify(operations));
```

Adding a third parameter has no effect:

```
this.httpClient.patch<CustomModel>(
    `/api/${id}`,
    JSON.stringify(operations),
    { withCredentials: true });
```

Am I missing something?

## Environment

<pre>@angular/cli: 1.3.1
node: 8.1.2
os: win32 x64
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5
@angular/service-worker: 1.0.0-beta.16<code>

Browser:
- [ x ] Chrome (desktop) version XX
 
</code></pre>

**Comment by zygimantas** [comment]
Cookies were not displayed as provisional headers in request.

**Comment by Bngoc** [comment]
it's help you in problem
https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials
