### ISSUE TITLE
ngc: support third-party codegen on install (ngc --init)

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#18810]
Angular libraries ship without codegen (eg. ngfactory.js, ngsummary.js) so users need to compile these with ngc.
Right now this work is done for every run of `ngc` even though the libraries haven't changed. Doing this as an `npm postinstall` step would save time. Also it's needed for bazel.

**Comment by chuckjaz** [comment]
Blocking until runtime localization is available which then will generate a locale independent factories in the prepare step.

**Comment by LinBoLen** [comment]
it works, but it takes me lots of time to figure it out.

**Comment by thesayyn** [comment]
Any update on this ?

**Comment by JoostK** [comment]
I added this to the linker project as somewhat related, but upon further thought it may not be. Nowadays ngcc is precompiling libraries during postinstall, which is what is being requested in this issue. However, ngcc is an interim solution for compatibility, which the linker being the replacement. We are not currently planning to support a caching layer for the linker.

**Comment by alxhub** [comment]
Closing as this is:
1) not something we will support in View Engine, for reasons of deprecation
2) the ultimate state will be that all libraries are shipped in partially compiled format and finalized with the Angular Linker, which is implemented as a Babel plugin. Babel supports caching, so a dedicated build author could implement similar functionality.
