### ISSUE TITLE
In hybrid application, digest error in V1 page breaks change detection in V2 pages

### ISSUE THREAD

**Issue by jdwilliams15** [angular/angular#18815]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Digest error occurs on V1 Page.
Go to V2 page, change detection no longer functional.

## Expected behavior
Change detection shouldn't break.

## Minimal reproduction of the problem with instructions
Example stack trace of error that occurs before break of change detection:
<pre><code>
send[native code]:1
$zone_js$v0_8_16$lib$common$utils__global$className$$prop$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:90757
scheduleTaskrs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:93225
$ZoneDelegate$$scheduleTask$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:92383
$Zone$$scheduleTask$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:92232
$Zone$$scheduleMacroTask$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:92250
$target$onerror$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:10705
$ZoneDelegate$$invoke$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:92366
$Zone$$runGuarded$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:92169
(anonymous function)rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:92149
postMessageAndAwaitResponse[native code]:1
postMessageAndAwaitResponsewebapis.js:79
getMenuValuewebapis.js:1754
$devices$SamsungTizenDevice$$isVoiceGuideEnabled$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:192468
$tts$SpeechSynthesisService$$isSpeechEnabled$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:166951
$tvapp$js$components$tts$announcer$classdecl$var3$$onContentChange$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:166788
$tvapp$tts$SpeakController$$$onChanges$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:166848
triggerOnChangesHook
(anonymous function)

$eval
$apply
flushOnChangesQueue
$digest
$apply
(anonymous function)
completeOutstandingRequest
(anonymous function)
$ZoneDelegate$$invokeTask$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:92395
$Zone$$runTask$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:92198
$ZoneTask$invokeTask$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:92456
$this$invoke$rs=AOExQ6lM_nbmVvSJLVg4ml76oTT5o4aZUg:92443
timer
</code></pre>

## Environment

<pre><code>
Angular version: commit/70628112e85ceadd2e0aa243a659f871cbf29492
</code></pre>

The exception cannot be caught due to the fact that it occurs during call to postMessageAndAwaitResponse which is an async communication with the native client.

**Comment by jdwilliams15** [comment]
I need to make a correction to this, after looking deeper into this, it seems that it's a "digest already in progress" error that's breaking the V2 change detection, not an unhandled exception.

Didn't determine this before as it seems that the original process of the error by Angular was resulting in a TypeError which is what I would end up seeing in the end(not sure whether this is due to Angular or our logic yet. But it happens when the error logger tries to handle the error in angular2$rc$packages$core$src$errors_defaultErrorLogger$.

The digest already in progress error itself seems to happen due to the fact that the plugin api that Tizen devices use generate MessageEvents which will then trigger globalZoneAwareCaptureCallback which will eventually trigger a digest. This digest, it seems, depending on timing, will cause a digest error. 

The original stack after intercepting the error in the error logger:
beginPhase
$digest
[ngZone.onMicroTaskEmpty...rootScope.$digest]
[generatorOrNext]
$rxjs$v5_4_2$src$Subscriber_SafeSubscriber$$__tryOrUnsub$
$rxjs$v5_4_2$src$Subscriber_SafeSubscriber$$next$
rxjs$v5_4_2$src$Subscriber_Subscriber$$_next$
$rxjs$v5_4_2$src$Subscriber_Subscriber$$next$
$rxjs$v5_4_2$src$Subject_Subject$$next$
$angular2$rc$packages$core$src$event_emitter_EventEmitter$$emit$
$angular2$rc$packages$core$src$zone$ng_zone_checkStable$
$angular2$rc$packages$core$src$zone$ng_zone_onLeave$
onInvokeTask
$ZoneDelegate$$invokeTask$
$Zone$$runTask$
$ZoneTask$invokeTask$
$invokeTask$
$globalZoneAwareCaptureCallback$
postMessageAndAwaitResponse@[native code]
postMessageAndAwaitResponse@file:///opt/down/pepper/webapis/webapis.js:79:51
getMenuValue@file:///opt/down/pepper/webapis/webapis.js:1754:54
$tvapp$devices$SamsungTizenDevice$$isVoiceGuideEnabled$
$tvapp$tts$SpeechSynthesisService$$isSpeechEnabled$
$tvapp$js$components$tts$announcer$classdecl$var3$$onContentChange$
$tvapp$tts$SpeakController$$$onChanges$
triggerOnChangesHook

$eval
$apply
flushOnChangesQueue
$digest
$apply

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

(You can use [this template][1] for creating a live reproduction.)

[1]: http://plnkr.co/edit/BXA3Onj8CkbmfuDKXu1N?p=preview
