### ISSUE TITLE
Property Binding to CSS-style has no effect after animations changed the same style 

### ISSUE THREAD

**Issue by FrankStrieter** [angular/angular#18829]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

if i use a defined animation from the animationbuilder to set a css propery the property-bining to this css value has no effect afterwards.

## Expected behavior

if the animation is done any change of the property should change the styles of the element.

## Minimal reproduction of the problem with instructions
template:

```html
<div class="cards-slider" [style.left.px]="offset">
    <cp-card
    *ngFor="let element of array; index as i" [item]="element"
    ></cp-card>
</div>
```

component (excerpt);
```javascript
buildSwipeRightAnimation(additionalOffset) {
 const swipeRightAnimation = this.animationbuilder.build([
  animate('500ms', style({left: this.offset - additionalOffset + 'px'}))
  ]);
  const element = document.getElementsByClassName('cards-slider')[0];
  this.swipeRightAnimationPlayer = swipeRightAnimation.create(element);
}
callAnimation() {
 this.swipeRightAnimationPlayer.play();
}
```

After the animation is done the property-binding of 'offset' to [style.left] updates the value as well, but the browser does not recognize this changes anymore. 

here is a plunkr to show you the behaviour: https://plnkr.co/edit/X5vltRJKXu8YuhhNa3BL

## What is the motivation / use case for changing the behavior?
As a workaround I defined a 2nd animation (with 1ms duration) which runs on every offset-change and sets the offset during the animation.
But this makes the code very strange.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

Others:

</code></pre>

**Comment by matsko** [comment]
With `AnimationBulider` the player is persisted (and so are the styles that are set). This means that `*` properties will only pickup styles that are visually present at the start of the animation (this in case since the player is still alive it will pickup those styles).

You need to destroy the player once it has finished: https://plnkr.co/edit/cnlynN4CoRltCMJsl09H?p=preview

I think the real solution to this is to add a `fillMode` option to `AnimationBuilder`.

**Comment by zohar1000** [comment]
player.destroy() resets the styles back to their values prior to the animation, so after the .destroy() command I have to set the styles one by one to the values where the animation finished. 

for example, if I have an element with width 50px and I want to animate it to 100px, then the code will look like:
`const el = ...  // some element having a width of 50px
const myAnimation = this.animationBuilder.build([
	animate(1000, style({ width: '100px' }))
]);
const player = myAnimation.create(el);
player.onDone(() => {
	// at this point the width is 100px
	player.destroy();
	// at this point the width is back to 50px so I need the next line to set the width again to 100px
	el.style.widtht = '100px';
});
player.play();`


This looks to me like a bug, the animation should be as simple just as the doc says [.](https://angular.io/api/animations/AnimationBuilder).
after the animation is done, the player should release any holding it may have on the element.

**Comment by matsko** [comment]
@Strulle @zohar1000 sorry this is taking a while for me to look at. Could you please create a new demo on http://stackblitz.com/? I can then use their debugging tools and figure this out.

**Comment by gbrlsnchs** [comment]
@zohar1000 I had the same issue as yours. But your own solution seems to work by inverting the order in the `onDone` callback:

```typescript
const el = this.targetElement.nativeElement;
const myAnimation = this.animationBuilder.build([
  animate(1000, style({ width: '100px' }))
]);
const player = myAnimation.create(el);
player.onDone(() => {
  // First set the property, otherwise it won't work or will have undesired behavior.
  el.style.width = '100px';

  // Then destroy the player. The element already has the same value as the one set by the player set,
  // so everything will probably be fine.
  player.destroy();
});
player.play();
```
