### ISSUE TITLE
Generic http.get and http.post functions

### ISSUE THREAD

**Issue by JaimeStill** [angular/angular#18820]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Calling `http.get` and `http.post` does not currently take advantage of the generics feature of typescript.

## Expected behavior

When working with Angular lately, I've been writing a `CoreApiService` that abstracts some of the functionality that gets continuously repeated in my API-facing services. I was wondering if the generic abstractions of http.get and http.post would be able to have some standard utility in the http library?

``` typescript
import { Injectable } from '@angular/core';
import { Http, Response, RequestOptions, Headers } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/throw';

@Injectable()
export class CoreApiService {
    constructor(private http: Http) {}

    extractData(res: Response) {
        return res.json() || {};
    }

    handleError(error: Response | any) {
        let errMsg: string;

        if (error instanceof Response) {
            const body = error.json() || '';
            const err = body.error || body.Message || JSON.stringify(body);
            errMsg = `${err}`;
        } else {
            errMsg = error.message ? error.message : error.toString();
        }

        console.error(errMsg);
        return Observable.throw(errMsg);
    }

    getRequestOptions(): RequestOptions {
        const headers = new Headers({
            'Content-Type': 'application/json'
        });

        return new RequestOptions({ headers: headers });
    }

    get<T>(url: string): Observable<T> {
        return this.http.get(url)
            .map(this.extractData)
            .catch(this.handleError);
    }

    post<T>(url: string, body: string, options?: RequestOptions): Observable<T> {
        return this.http.post(url, body, options ? options : this.getRequestOptions())
            .map(this.extractData)
            .catch(this.handleError);
    }
}
```

Here are two example API calls making use of these functions:   

``` typescript
getThemes() {
    this.coreApi.get<Array<Theme>>('/api/app/getThemes').subscribe(
        themes => {
            this.themes.next(themes);
        },
        error => {
            this.toaster.sendErrorMessage(error);
        });
}

updateSettings() {
    this.coreApi.post<User>('/api/app/updateSettings', JSON.stringify(this.user.value.settings)).subscribe(
        user => {
            this.user.next(user);
            this.toaster.sendSuccessMessage(`Your settings were updated ${user.first}!`);
        },
        error => {
            this.toaster.sendErrorMessage(error);
        });
}
```
## What is the motivation / use case for changing the behavior?

Providing type-safe return values for API calls using the generic language feature of TypeScript. This also greatly simplifies the creation of API-facing service functions.

**Comment by Toxicable** [comment]
`HttpClient` already provides this 
See https://angular.io/guide/http for more info

**Comment by JaimeStill** [comment]
Thanks, I guess it's been a while since I've looked at the documentation!
