### ISSUE TITLE
Angular4 Animation with dynamically created component

### ISSUE THREAD

**Issue by shubhi15** [angular/angular#18825]
I am trying to apply animation while dynamically creating component using componentFactoryResolver  in Angular4.
Using router style :enter and :leave animation I have applied animation on host of my dynamically created component.

## Current behavior
: enter animation is getting applied successfully upon creation of component.
but upon deleting of my dynamically created component as well as container of it
 :leave type animations not getting triggered.

## Expected behavior
 :leave type animations should be triggered.

## Minimal reproduction of the problem with instructions

Dynamically create an angular component on click of button using componentFactoryResolver.
Create animations for this component. Like i have shown below

```ts
 transition(':enter', [  // before 2.1: transition('void => *', [
     animate('2s', keyframes([
         style({opacity: 0, offset: 0}),
         style({opacity: 0.4, offset: 0.3}),
         style({opacity: 0.6, offset: 0.6}),
         style({opacity: 1, offset:1}),
      ]))
    ]),
    transition(':leave', [  // before 2.1: transition('* => void', [
     animate('2s', keyframes([
         style({opacity: 1, offset:0}),
         style({opacity: 0.6, offset: 0.6}),
         style({opacity: 0.4, offset: 0.8}),
         style({opacity: 0, offset: 1})
      ]))
    ])
```

Add a button to remove the component. `:leave` type animation not getting triggered.

**Comment by matsko** [comment]
Hey @shubhi15 any chance you can make a demo of this failure using https://stackblitz.com ? That way I can explore and go into debug detective mode.

**Comment by matsko** [comment]
https://github.com/angular/angular/commit/f42d317d2f17a9948d038bdd410324b4096d2597 could potentially fix the issue. Please see if it passes or not on RC9.

**Comment by matsko** [comment]
Closing this for now. Please reopen if it persists.

**Comment by o-panikarovskiy** [comment]
It persists in 6.1.7

**Comment by dicbrus** [comment]
confirm as well, bug is still here (6.1.3)

**Comment by dicbrus** [comment]
@matsko How to re-open here? seems I've no permissions for that, could you please re-open?

**Comment by kimpixel** [comment]
Exactly same Problem here.

Is there any workarround? I am stuck with this.
