### ISSUE TITLE
@Inject doesn't work with class decorator in the uglified file

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular#18827]
Unfortunately I can't use plnker for demonstration. That is why I cloned AngularStarter project and implemented demo there: https://github.com/tamtakoe/angular2-webpack-starter

Take a look on _src/app/rest-resource.js_
```js
import { HttpClient } from '@angular/common/http';
import { Inject } from '@angular/core';

export function ResourceParams(options) {
  return (target) => {
    const original = target;

    const newConstructor: any = function newCtor(...args) {
      const c: any = function childConstuctor() {
        return original.apply(this, arguments);
      };
      c.prototype = Object.create(original.prototype);
      const instance = new c(...args);

      instance.url = options.url || instance.url;

      return instance;
    };

    newConstructor.prototype = Object.create(target.prototype);

    return newConstructor;
  };
}

export class Resource {
  public url;
  public constructor( @Inject(HttpClient) protected http: HttpClient) {
    // http is not injected if code was uglify (npm run build:prod)
    console.log('HTTP client', http);
  };

  public get() {
    return this.http.get(this.url);
  };
}
```
_src/app/user-resource.js_
```js
import { Resource, ResourceParams } from './rest-resource';

@ResourceParams({
  url: '/users'
})
export class UserResource extends Resource {}
```

How to run demo
```
npm install
npm run build:prod
node ./server.js
open localhost:3001
```

If run build:dev it works OK. 

- Node version: 8.1.4
- Platform: Ubuntu

**Comment by vicb** [comment]
`public constructor( @Inject(HttpClient) protected http: HttpClient)`

`@Inject(HttpClient)` is not required here, `public constructor(protected http: HttpClient)` works equally well.

A lot of our users use uglify without any problem. Seems like a configuration issue on your side.

**Comment by tamtakoe** [comment]
Of course `public constructor(protected http: HttpClient)` doesn't work without `@Inject(HttpClient)` (try to run it).

A lot of user never do something deeper than what is described in a basic documentation or articles. I use well-known Angular starter. I really don't think that the problem is in my configuration.

It seems that my decorator implementation uses... maybe function names for work and uglify breaks it... I don't know exactly how DI works with custom decorators. That is why I created this issue :-)

**Comment by tamtakoe** [comment]
Clarification: it doesn't work with JIT compilation. With AOT it works correct
