### ISSUE TITLE
Remove min/max validators from documentation

### ISSUE THREAD

**Issue by miiihi** [angular/angular#18830]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/api/forms/Validators lists min and max validators as available, but they have been removed with #17551 and #17622

## Expected behavior

Min and max validators should be removed from docs.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Just wasted an hour trying to debug, why min/max validators stopped working...

**Comment by miiihi** [comment]
Actually, the above https://angular.io/api/forms/Validators correctly lists the min and max, as only directives have been removed. Consider adding a comment, that min and max exist only as a functions but not directives...

**Comment by kara** [comment]
As @miiihi mentioned, the validators still exist, but I think a comment in the docs would be helpful.

**Comment by kapunahelewong** [comment]
@kara and @miiihi like this? ^^

**Comment by fmpierce** [comment]
Why did they remove the directives? I can't find a reason anywhere on the web.

**Comment by jenniferfell** [comment]
Issue resolved. Doc updated by PR linked above.
