### ISSUE TITLE
When files change during the brocoli tasks they are not picked up.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1883]
1. Edit and save file
2. Watch kicks in and starts transforming files.
3. While files are being transformed change another file
4. Observe that the second change is lost. (It does not cause the watcher to rerun.)

**Comment by IgorMinar** [comment]
this should already be fixed in master via 23cec1e8e247f8d7f36cad2306fe0b36eae4fc8d. reopen if that's not the case.
