### ISSUE TITLE
Code stopped working after typescript is updated to 2.3.1 and up

### ISSUE THREAD

**Issue by kzhang-dsg** [angular/angular#18833]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Code stopped working after typescript is updated to 2.3.1 and up

## Expected behavior

Code compiles and runs when change the TypeScript version to 2.3.1 and up in config.js

## Minimal reproduction of the problem with instructions

1. Go to Plunker:
http://plnkr.co/edit/ZLesLDcvKvd20BIwziKT?p=preview

2. Notice the demo works fine.

3. Change the TypeScript version to 2.3.1 and up in config.js

4. Notice the demo stopped working.

Note the code used `extends` to extend from a super class, and used `useExisting` to reference itself.

```
@Component({
    selector: 'nested-control',
    providers: [{
        provide: NG_ASYNC_VALIDATORS,
        useExisting: forwardRef(() => NestedComponent),
        multi: true,
    }, {
        provide: NG_VALUE_ACCESSOR, 
        useExisting: forwardRef(() => NestedComponent),
        multi: true
    }],
...
})
export class NestedComponent extends BaseComponent {
...
```

## Environment

<pre><code>
Angular version: 4.x

Browser:
- [x] Chrome (desktop) version 60.0.3112.101
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.9.2  
- Platform:  Linux, Windows 

Others:

</code></pre>

I also submitted an ticket against  Typescript:
https://github.com/Microsoft/TypeScript/issues/17895

**Comment by pkozlowski-opensource** [comment]
We are on TS 3+ now, I don't think that this issue is relevant any more.
