### ISSUE TITLE
Angular 2 Hybrid App Routing Issue - Can't navigate to Angular 1 routes from Angular 2 component

### ISSUE THREAD

**Issue by lvasilev1** [angular/angular#18832]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have an Angular 1-Angular 2 hybrid application that was set-up using the following guides, [Upgrading from Angular JS](https://angular.io/guide/upgrade) and [Migrating Angular 1 Applications to Latest Angular in 5 Simple Steps](https://vsavkin.com/migrating-angular-1-applications-to-angular-2-in-5-simple-steps-40621800a25b). The problem is that, after having navigated to an Angular 2 component, clicking on a link to go back to an Angular 1 module doesn't work. It seems that the Url for the Angular 1 module is truncated and the app simply displays a blank page.

Here is some of my code. I also have a Plunker to demonstrate the issue, though some component names are different from the code below: [https://plnkr.co/edit/JGzY1EhulDlrz7gjHxwY?p=preview](https://plnkr.co/edit/JGzY1EhulDlrz7gjHxwY?p=preview)

My root component looks like this:
` 

    import { NgModule, Component } from '@angular/core';
    import { RouterModule, UrlHandlingStrategy } from '@angular/router';
    import { BrowserModule } from '@angular/platform-browser';
    import { UpgradeModule } from '@angular/upgrade/static';
    import { RouterUpgradeInitializer } from '@angular/router/upgrade';
    import { MyModule } from './Mymodule/my-module';

    export class Ng1Ng2UrlHandlingStrategy implements UrlHandlingStrategy {
        shouldProcessUrl(url: any) {
            return url.toString().startsWith("/Mymodule");
        }

    extract(url: any) {
        return url;
    }

    merge(url: any, whole: any) {
        return url;
    }
    }

    @Component({
        selector: 'root-component',
        template: 
        <router-outlet></router-outlet>
        <div class="ng-view"></div>
  
    })
    export class RootComponent { }

    @NgModule({
        imports: [
            BrowserModule,
            UpgradeModule,
            MyModule,

            RouterModule.forRoot([
            { path: '', pathMatch: 'full', component: HomeComponent },
            { path: 'MyModule/testdata', component: TestDataListComponent }
        ], { useHash: true, initialNavigation: false, enableTracing: true })
        ],
        providers: [
            { provide: UrlHandlingStrategy, useClass: Ng1Ng2UrlHandlingStrategy }
        ],
        bootstrap: [RootComponent],
        declarations: [RootComponent]
    })
    export class Ng2AppModule {
        constructor(public upgrade: UpgradeModule) { }
    }`

And my "main.ts":
`   
 
     import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
     import { setUpLocationSync } from '@angular/router/upgrade';
     import { Ng2AppModule } from "./Angular2/app.rootcomponent";

     // This is the entry point for the AngularJS/Angular hybrid application.
     // It bootstraps the Angular module 'Ng2AppModule', which in turn bootstraps
     // the AngularJS module 'angular1App'.
     platformBrowserDynamic().bootstrapModule(Ng2AppModule).then(ref => {
        const upgrade = (<any>ref.instance).upgrade;
        // bootstrap angular1
        upgrade.bootstrap(document.body, ['angular1App']);
        setUpLocationSync(upgrade);
    });`

'TestDataListComponent' component is very simple:
`

    import { Component } from '@angular/core';

    @Component({
        selector: 'test-data',
        templateUrl: 'App/Angular2/MyModule/testdata-list.component'.html'
    })
    export class TestDataListComponent{

    }`

The way I am linking to the Angular 2 component is in a main menu HTML page. The relevant code is the following:

> <li id="main-menu" class="menu-top-level" ng-mouseover="cur = 'mymodule'">        
    <a ng-reflect-router-link="/Mymodule/testdata" href="#/Mymodule/testdata">
        MyModule
        <span>
            <i class="fa fa-check-square fa-2x"></i>
        </span>
    </a>

As mentioned above, the problem is that once I navigate to an Angular 2 component, clicking on a link to go back to an Angular 1 module simply produces a blank page. One curious thing I have noticed is that the Url in my browser window looks like this:

`
 http://localhost:60813/#/
`

even though when I hover over the link (before I click on it) it has the the correct value, which is:

`
 http://localhost:60813/#/myclients
`

If I click on the link a second time, the URL is correct and the Angular 1 page is displayed fine.

The relevant portion of my Angular 1 module 'angular1App' is:
`

    angular.module("angular1App",
    ["ngRoute",
     "myInterceptorService",
     "ngStorage",
     "ngAnimate",
     "ui.bootstrap",
     "ngResource",
     "SignalR",
     "ui.select",
     "ngSanitize"])
    .config([
        "$routeProvider", "$httpProvider", function($routeProvider, $httpProvider) {

        $httpProvider.interceptors.push("myInterceptorService");

        $routeProvider
            .when('/myclients',
            {
                title: "Client Data",
                controller: "clientDataCtrl",
                templateUrl: "/App/Common/Views/clientData.html"
            })
`

What is the problem here? Why does it not route correctly to my Angular 1 module?

## Minimal reproduction of the problem with instructions

Here is a demo of the problem:
[https://plnkr.co/edit/JGzY1EhulDlrz7gjHxwY?p=preview](https://plnkr.co/edit/JGzY1EhulDlrz7gjHxwY?p=preview)

Steps to reproduce are the following:

1. Click on link "Angular 2 Cars" - the corresponding component is displayed
2. Click on link "Users" or "Groups" - nothing happens
3. Click on "Users" or "Groups" a second time (doesn't matter which one) - the corresponding page is displayed

If you open Developer Tools (F12), you'll notice (in the router logs) how for any of the Angular 1 links the **url** and **path** attributes of the **Router** object are blank, while for the Angular 2 component they have the expected values (look at picture below):

![image](https://user-images.githubusercontent.com/16479217/29573767-6d25fab4-8725-11e7-9d61-2de10d24a924.png)

## What is the motivation / use case for changing the behavior?

The use case is to have an Angular 1-Angular 2 hybrid app and be able to navigate successfully back and forth between Angular 1 modules and Angular 2 components.

## Environment

<pre><code>
Angular version: X.Y.Z

"dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "@angular/upgrade": "^4.2.5",
    "@types/node": "^6.0.79",
    "angular-in-memory-web-api": "~0.3.0",
    "core-js": "^2.4.1",
    "ng-http-interceptor": "^2.0.0",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@types/angular": "^1.6.17",
    "@types/angular-animate": "^1.5.6",
    "@types/angular-cookies": "^1.4.3",
    "@types/angular-mocks": "^1.5.9",
    "@types/angular-resource": "^1.5.8",
    "@types/angular-route": "^1.3.3",
    "@types/angular-sanitize": "^1.3.4",
    "@types/core-js": "^0.9.41",
    "@types/jasmine": "^2.5.47",
    "@types/node": "^6.0.46",
    "angular": "1.5.0",

Browser:
- [x] Chrome (desktop) version 60.0.3112.90 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.2  
- Platform: Windows 8  

Others: Visual Studio 2015, NPM

</code></pre>

**Comment by jrmcdona** [comment]
Did you figure this one out?

**Comment by lvasilev1** [comment]
Nope.
--------------------------------------------
On Wed, 8/23/17, Jordan <notifications@github.com> wrote:

 Subject: Re: [angular/angular] Angular 2 Hybrid App Routing Issue - Can't navigate to Angular 1 routes from Angular 2 component (#18832)
 To: "angular/angular" <angular@noreply.github.com>
 Cc: "lvasilev1" <lougv22@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Wednesday, August 23, 2017, 6:11 PM
 
 Did you figure this one out?
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by brandonroberts** [comment]
@lvasilev1 I ran into this same issue using the Router in a hybrid app. The way `setupLocationSync` provides the URL to the router for navigating doesn't work correctly with hash-based routing. What I did was tweak the source from the `setupLocationSync` to pass the URL from the hash to navigate with. This way the `Router` will handle navigating both scenarios correctly. 

See the `main.ts` with the fix

https://plnkr.co/edit/e7hW2q?p=preview

**Comment by gkalpak** [comment]
@brandonroberts, wouldn't that break when using html5Mode in AngularJS?

**Comment by brandonroberts** [comment]
@gkalpak maybe. His example was specifically using hash routing in both apps. Its possible to check which mode you're in using AngularJS and handle it accordingly, correct?

**Comment by gkalpak** [comment]
Well, it is not very straight forward, but you can keep a reference of `$locationProvider` and then check `$locationProvider.htm5Mode().enabled`. E.g.:

```ts
angular..module('someModule').provider('ng1Html5Mode', class Ng1Html5ModeProvider {
  constructor(private $locationProvider: angular.ILocationProvider) {}
  $get() { return this.$locationProvider.html5Mode().enabled; }
});
```

**Comment by lvasilev1** [comment]
@brandonroberts That seems to work! Thanks so much. I've been struggling with this for weeks. And we do use hash based routing in both apps so it shouldn't be a problem to use what you suggested above.

**Comment by vikrambhatla** [comment]
@brandonroberts I am trying your approach.
We have hybrid application where routes are defined in angular1 app. I am trying to add the routes in angular2 and it doesn't works :(. 
I can paste the application. Please do let me know.
