### ISSUE TITLE
Allow context in AOT compiler

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#18836]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

The AOT compiler (with `tsc-wrapped`) transforms all of the metadata within `@NgModule`, `@Component` etc into hard coded code instructions in TS. While doing so it performs some static evaluation to the code, for example it will take this code:
```ts
@NgModule({
  imports: [ // import Angular's modules
    1 + 1 === 3 ? HttpModule : [],
    1 + 1 === 2 ? FormsModule : [],
  ]
})
export class AppModule {}
```

and evaluate the expressions in the `imports` (since the condition has both left and right primitives)
so the end result is `[]` in the 1st statement and `FormsModule` in the 2nd statement.

This has an impact since the `ngfactory` files that the AOT outputs are part of the bundle so they impact tree shaking.

Now with a more useful example:
 ```ts
@NgModule({
  imports: [ // import Angular's modules
    DEBUG === false ? FormsModule : HttpModule
  ]
})
export class AppModule {}
```

`DEBUG` is an Identifier and not a primitive and as such its is not evaluated in `tsc-wrapepd`.
The end result in the `ngfactory` file is using `HttpModule` so there an evaluation somewhere else.

Its clear that `DEBUG` is not a runtime value and as such it needs to be defined as a context for the compilation process.

This is exactly the `DefinePlugin` in **webpack** but since the AOT compilation runs independently of webpack using the `DefinePlugin` is no good.

I'v briefly seen that in the next version (5) one can use `substituteExpression` to replace the `MetadataValue` for a node, this might be a way to implement this but an external implementation is  not that trivial to integrate.

This feature will allow **Feature Flags** and all sorts of build configuration stuff and aligning it with the `DefinePlugin` will ensure transparent flow.

@tbosch can this get into implementation?

**Comment by chuckjaz** [comment]
@shlomiassaf This works without any compiler modification if you adjust the input to the compiler. If you import from a configuration module that is, at compile time, defined to be,

```
export const DEBUG = true;
```

the template compiler will simplify the code from:

```ts
@NgModule({
 imports: [ // import Angular's modules
   DEBUG ? FormsModule : HttpModule
 ]
})
export class AppModule {}
```

to

```ts
@NgModule({
 imports: [FormsModule]
})
export class AppModule {}
```

if the input the value of `DEBUG` is changed to `false` it is simplified to,

```ts
@NgModule({
 imports: [HttpModule]
})
export class AppModule {}
```

webpack controls the input to the compiler and can either adjust the `.ts` file that produced the `.metadata.json` file that contains the value of `DEBUG` or adjust the content of the `.metadata.json` file directly. Using `substituteExpression` for this is a bit overly elaborate.

**Comment by shlomiassaf** [comment]
@chuckjaz This is correct only for webpack builds, and not out of the box.

For non-webpack builds:
```bash
ngc -p
```
It is not possible.

For webpack builds, the `DefinePlugin` kicks in on raw JS after all loaders have completed and so it is required to use a loader...

Now, I can quickly build a loader but it seems pointless because:
  1. I can either use REGEX or AST
      - AST required an additional TS compilation process and a type checker which is costly and I want to avoid that. `@ngtools` won't let me add transformers nor get the `program`
      - REGEX is not optimal and might miss/false positive.

   2. Even if I implement a plugin, i'm still left with cli option not supported.

**Comment by shlomiassaf** [comment]
@chuckjaz I figured this out...

By using the `hostReplacementPaths` in `@ngtools/webpack` I was able to provide a static compile time (and runtime) value.

Still no CLI support but at least something...
