### ISSUE TITLE
BrowserAnimationsModule down angular hot module remplacement

### ISSUE THREAD

**Issue by maxshutyak** [angular/angular#18835]
when i am import Browser animation module
`import {BrowserAnimationsModule} from '@angular/platform-browser/animations';`
angular-hmr down and i am get the error:

<img width="598" alt="screen shot 2017-08-22 at 11 57 29 pm" src="https://user-images.githubusercontent.com/6385049/29587229-f957dd2a-8795-11e7-9e47-53fca702492a.png">

` "@angularclass/hmr-loader": "^3.0.4",
 "@angularclass/hmr": "^2.1.1",`

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
