### ISSUE TITLE
Reactive form with ngrx - form state does not change while typing in form control

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#18840]
Here's my pet app http://ngx.azurewebsites.net. This is 4.3.5 + ngrx 4 app. I use `ChangeDetectionStrategy.OnPush` in all my container components (but not in presentational ones).

Now, please go to **Videos** => click on **Test 1** link to edit a record => you should see a form. It has a **Save** button which should be enabled once the criteria is met:
```
<button [disabled]="!(vidForm.touched && vidForm.valid) || isWorking" type="submit">Save</button>
```
So when you start typing in **Friendly Url** input for example, the button should become enabled. But it's not for some reason. Now, if the control looses focus, the button changes its state (the form changes its state). So, only after the input looses focus the button gets enabled which is not how it should work I think.

I added this code inside the ctor for testing purposes:
```
    this.vidForm.valueChanges.subscribe(v => {
      this.cd.markForCheck();
      console.log("CD mark");
    });
```
but nothing changes even with CD marking for check. I think it may be a bug somewhere in forms module.

**Comment by Toxicable** [comment]
Could you please provide a minimal reproduction of the issue in isloation in either plunkr or stack blitz
We are unable to change the source code of your website and there are many aspects of your website that may cause issues therefore it's not suitable to use a reproduction.

**Comment by alvipeo** [comment]
Here's the repo - https://github.com/alvipeo/forms-app . I couldn't create a plunker for it, sorry.

**Comment by Toxicable** [comment]
Sorry but without a *minimal* reproduction this issue in *isolation* it is not actionable.
This issue tracker is for reporting issues with Angular not for debugging whole applications

**Comment by alvipeo** [comment]
ok, I'll try to minimize the app. But it's not going to be a plunker.

**Comment by alvipeo** [comment]
ok, I removed everything unrelated - https://github.com/alvipeo/forms-app. now it has the bare minimum to repro the issue.

**Comment by Toxicable** [comment]
I'm sorry but there is still a large amount of code in your repo unrelated to this issue

**Comment by alvipeo** [comment]
I can't remove ngrx from there, otherwise the issue is pointless. The only thing I can remove it's that editor. Will that be enough?

**Comment by alvipeo** [comment]
ok, here's what I found (not sure that's correct).

If I change the button template to

`<button [disabled]="vidForm.pristine || vidForm.invalid || isWorking"...>`

it DOES work.

But isn't this the same as what I had before?

`<button [disabled]="!(vidForm.touched && vidForm.valid) || isWorking" ...>`

... do I have a logic problem? :)

**Comment by Toxicable** [comment]
Yes, you have a logic issue
```
!(false && false) || false //returns true
false || false || false        //returns false
```

**Comment by alvipeo** [comment]
I AM SORRY :( Damn....! gr.....!!!!
