### ISSUE TITLE
Can't test component router events reactions

### ISSUE THREAD

**Issue by karlos1337** [angular/angular#18841]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I want to test the behaviour of a component on a router event emit (GuardsCheckStart) but can't trigger it manually, triggerEvent method is private so can't use it and routerEvents property is readonly so cant overwrite it nor use next method and can't find any documentation about how to do this.

## Expected behavior
Be able to test a component reaction to a router event broadcast.

## What is the motivation / use case for changing the behavior?
Test component behaviour on certain router event broadcast.

## Environment

<pre><code>
Angular version: 4.3.4

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.3.0  
- Platform:  Linux 

Others:

</code></pre>

**Comment by jasonaden** [comment]
For private methods, you can cast to `any` first, then run it. This will avoid TypeScript errors.
