### ISSUE TITLE
Angular 4+ Events are slowing down over time.

### ISSUE THREAD

**Issue by kanchan-kumar** [angular/angular#18845]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

 In my angular SPA application events are getting slower over time.  
 In my Application there are 5 different modules and i am loading these modules using lazy routing  with material 2 nav-bar. 
  For first few minutes it works fine but after some time of using it every event slowing down.

## Expected behavior

Events should not take time more than 100ms .

## Minimal reproduction of the problem with instructions

I have very large SPA application in which i am using many libraries including highcharts, primeng, material 2, angular2-grid etc. I am using angular2-grid for resizable grids. When i am using the context menu of primeng on these grid. Events are getting slowing down.

## What is the motivation / use case for changing the behavior?

Frequently doing resizing of grid, drag/drop from tree to grid, Opening context menu started causing this issue.

## Environment

<pre><code>
Angular version: 4.1.3

Browser:
- [x ] Chrome (desktop) version  60.0.3112.101
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>
![event](https://user-images.githubusercontent.com/7692425/29612876-1145063e-8821-11e7-98aa-612f5b84e617.png)

**Comment by ericmartinezr** [comment]
>When i am using the context menu of primeng on these grid. Events are getting slowing down.

Can you reproduce the issue with pure angular (no libraries)? If not you may want to notify the project owners as this is a huge mix of different libs and it doesn't seem to be an angular issue.

**Comment by vicb** [comment]
Closing as no repro.
