### ISSUE TITLE
Getting module injector error on angular site

### ISSUE THREAD

**Issue by shivajikokate-tudip** [angular/angular#18846]
![screenshot from 2017-08-23 21_08_49](https://user-images.githubusercontent.com/12661507/29625457-59a465be-8849-11e7-9f5a-0f0a51651ea4.png)

**Comment by shivajikokate-tudip** [comment]
I Google for order by clause in angular. After click on your site I got inject error in browser console.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Plus this repo is for angular :+1:
