### ISSUE TITLE
Get select-selectedIndex  and click event under select-option

### ISSUE THREAD

**Issue by ToMakeSense** [angular/angular#18842]
https://stackoverflow.com/questions/38235055/angular2-rc2-select-option-selectedindex

I want get selectedIndex and then get the select data model, then I found I could directly get the selected data model. however, click event under option doesn't work.

```html
<select class="form-control selectpicker" #Code name="Code" [(ngModel)]="model.Code">
    <option value="" selected="selected">--Please select--</option>
    <option *ngFor="let x of Codes" [value]="x.Code" [selected]="x.Code == model.Code" (click)="searchWithCode(x)">{{x.Name}}</option>
</select>
```
``` typescript
searchWithCode(code:any) : void {
    this.model.Name1 = code.Name1;
    this.model.Name2 = code.Name2;
}
```

## Environment
<pre><code>
Angular version: 4.0.3

Browser:
Chrome (desktop) version Version 60.0.3112.101 (Official Build) (64-bit)

For Tooling issues:
- Node version: 
- Platform:  Windows --10
</code></pre>

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ToMakeSense** [comment]
@Toxicable Sorry, I want to reply to the person who answered the question directly. Unfortunately, I don't have enough score(50 reputation at least, but I only have 1 reputation), that's too bad.

**Comment by ToMakeSense** [comment]
I solved this problem, would like to give more infomation when someone who has the same problem and not proficient in javascript like me. use event.target["selectedIndex"] instead of event.target.selectedIndex as event.target.selectedIndex is just work in runtime, as I had add "Please select" ahead, so you can **use event.target["selectedIndex"] - 1 to get the selectedIndex of select**.
