### ISSUE TITLE
In Angular app events are getting slower over time

### ISSUE THREAD

**Issue by kanchan-kumar** [angular/angular#18844]
## Current behavior
<pre><code>
 In my angular SPA application events are getting slower over time.  
 In my Application there are 5 different modules and i am loading these modules using lazy routing  with material 2 nav-bar. 
  For first few minutes it works fine but after some time of using it every event slowing down.
  I am using angular-cli with --prod mode excluding --aot.
  I am using angular 4.3.0 with angular-cli 1.3.0.
</code></pre>
![event](https://user-images.githubusercontent.com/7692425/29610652-86186fa4-8818-11e7-9cf2-87635160c704.png)

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
