### ISSUE TITLE
HttpClient Does Not Work During Server-Side Rendering With Windows Auth 

### ISSUE THREAD

**Issue by yanbu0** [angular/angular#18856]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have an Angular front end running on .Net Core 2.0 and using a Web Api back end.  I have changed one get call on my project to use the new HttpClient.  I implemented an http interceptor to test when the request fires on the server side:
```
if (isPlatformServer(this.platformId)) {
            console.log("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ THIS FIRED ON THE SERVER \n" + JSON.stringify(req));
}
```

Everything works as expected with Windows Authentication turned off.  The get fires off, the interceptor logs "THIS FIRED ON THE SERVER", and the data is returned on the server side render, then again on the client side.  

The issue is, changing nothing else but enabling Windows Authentication, the get request no longer fires off on the server side.  Works fine on client side still, but the request never even fires off server-side, or at least never actually reaches the interceptor.

## Expected behavior

The get request continues to fire server side as it does when Windows Authentication is enabled.  This is the behavior of the old Http function.

## What is the motivation / use case for changing the behavior?

Windows auth is pretty important for developing business applications.

## Environment

<pre><code>
Angular version: 4.3.5

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.4
- Platform:  Windows

Others:

VS 2017 15.3
IISExpress
</code></pre>

**Comment by alxhub** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Angular itself has no notion of what operating system it's running on, what the backend is configured to do, or what the authentication requirements are. Therefore the problem must be that some interceptor is causing the request not to fire, or the backend is dropping it or returning an error.
