### ISSUE TITLE
New router example with Angular2 Quickstart

### ISSUE THREAD

**Issue by pumpk1n** [angular/angular#1885]
Could someone provide a working example of the new router based on https://angular.io/docs/js/latest/quickstart.html? I'm pretty sure it would be useful for many of us!

**Comment by Pacane** [comment]
+1

**Comment by baio** [comment]
+1

**Comment by Pacane** [comment]
Someone gave me this link https://github.com/rkirov/angular2-dart-router-demo for Dart. It seems to be using code around beta23-24

**Comment by rightisleft** [comment]
+1

**Comment by chirino** [comment]
+1

**Comment by zoechi** [comment]
+1 (Dart)

**Comment by geekrumper** [comment]
+1

**Comment by rightisleft** [comment]
I made a fork of the above link. I tried to clean it up a bit, but im getting some odd behavior out of RouterLink

http://stackoverflow.com/questions/30292484/whats-the-proper-way-to-set-a-router-routerlink-in-angular2-dart

**Comment by lnlwd** [comment]
+1

**Comment by dsebastien** [comment]
That article from @PascalPrecht helped me w/ the basics of the component router: http://blog.thoughtram.io/angular/2015/06/16/routing-in-angular-2.html

The most annoying thing for now if you try it out using TypeScript is that the typings (files that describe all types/methods/...) file on DefinitelyTyped is not up to date and does not contain the Router & http: https://github.com/angular/angular/issues/2659 (there's a link in there for a temporary workaround)

**Comment by rolandjitsu** [comment]
I've also got a repo with a working example [here](https://github.com/rolandjitsu/ng2-play). It's up to date with the latest changes and a few workarounds/hacks until the angular team comes up with a good solution for typings.

**Comment by alexeagle** [comment]
We now have a devguide chapter on routing:
https://angular.io/docs/ts/latest/guide/router.html

**Comment by hasnat-babur** [comment]
better start VueJs with webpack and you will see the awesomeness
