### ISSUE TITLE
Runtime Perf Section in Angular.io

### ISSUE THREAD

**Issue by josephliccini** [angular/angular#18854]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There are lots of Runtime perf optimizations that can be used in Angular, but many are not documented, or documented well.

## Expected behavior

Angular.io Runtime Perf Optimizations Section

A lot of the perf documentation is around bundle size, and AoT (which are important of course)

Some Suggestions:
- Zone Blacklist: https://gist.github.com/robwormald/cb12881da7cbc73cf65dd042fad7b0fb
- OnPush Change Detection Strategy advanced cases
- Optimizing component models / templates / pipes for Runtime performance
- Investigating Runtime perf suggestions (demo of Chrome Dev Tools and what is a red flag in the performance analyzer with Angular, etc.)

I am sure there are a lot more than what I've listed.  I'd love to see a large section of documentation about making the fastest angular app during runtime all in one place, on angular.io.  

Thanks!

**Comment by JiaLiPassion** [comment]
@josephliccini , the `Zone BlackList` has been updated.
https://gist.github.com/JiaLiPassion/45664f6a28c8b522fca30c841610c6b4

**Comment by jenniferfell** [comment]
docsarea=performance
docsarea=optimization

Thanks for the suggestion. 

I've added the label "fixed by Ivy" so that we keep track of the dependency. This won't be "fixed" by Ivy, but the details will be affected by Ivy. Definitely something to consider doing as part of -- or after -- Ivy.

**Comment by jenniferfell** [comment]
@mhevery @IgorMinar @StephenFluin @manughub FYI

**Comment by jelbourn** [comment]
This is now being tracked in #34735
