### ISSUE TITLE
Navigating to routes without using [routerLink] and use <a href="/">

### ISSUE THREAD

**Issue by jrmcdona** [angular/angular#18858]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Navigating to a route like this will reload the page:

        <li>
          <a href="/ambassadors/leaderboard">
            <span class='glyphicon glyphicon-star-empty'></span> Leaderboard Test
          </a>
        </li>

Even though this is defined path and component in the routing module.

## Expected behavior

I would expect that routes defined in the router module could be resolved without a [routerLink] attribute and behave link a SPA.  Similar to AngularJS.

## Minimal reproduction of the problem with instructions
Navigate to on your routes like this.  I put my routes in "other section" at the bottom.
```
 <li>
          <a href="/ambassadors/leaderboard">
            <span class='glyphicon glyphicon-star-empty'></span> Leaderboard Test
          </a>
        </li>
```

## What is the motivation / use case for changing the behavior?

We have many sites at our large company.  They are coded in many types of languages. 
They get their navigation from a common header and foot service. Therefore it all comes back as HTML with <a> tags.  These tags do not have [routerLink] on them as the service isn't exactly made to target Angular.   It works fine for us in AngularJS.

## Environment

<pre><code>
Angular version: 4.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  8.2.1
- Platform:  Windows

Others:
Older github issue reference w/ some work arounds but these no longer work:
https://github.com/angular/angular/issues/8409

app.routing.module.ts

```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { AppComponent } from "./app.component";
import { NotFoundComponent } from "./shared/not-found/not-found.component";
import { LeaderboardComponent } from "./leaderboard/leaderboard.component";
import { NavMenuComponent } from "./components/navmenu/navmenu.component";
import { HomeComponent } from "./containers/home/home.component";
import { UsersComponent } from "./containers/users/users.component";
import { UserDetailComponent } from "./components/user-detail/user-detail.component";
import { CounterComponent } from "./containers/counter/counter.component";
import { ChatComponent } from "./containers/chat/chat.component";
import { ConnectionResolver } from "./shared/route.resolver";

const routes: Routes = [
    {
        path: "",
        redirectTo: "home",
        pathMatch: "full"
      },
      {
        path: "ambassadors",
        children: [
          {
            path: "leaderboard",
            component: LeaderboardComponent,
            data: {
              title: "Leaderboard",
              meta: [
                { name: "description", content: "Xbox Ambassadors Leaderboard" }
              ],
              links: [
                {
                  rel: "canonical",
                  href: "http://blogs.example.com/blah/nice"
                },
                {
                  rel: "alternate",
                  hreflang: "es",
                  href: "http://es.example.com/"
                }
              ]
            }
          }
        ]
      },
      {
        path: "home",
        component: HomeComponent,

        data: {
          title: "Home",
          meta: [
            {
              name: "description",
              content: "This is an example Description Meta tag!"
            }
          ],
          links: [
            { rel: "canonical", href: "http://blogs.example.com/blah/nice" },
            { rel: "alternate", hreflang: "es", href: "http://es.example.com/" }
          ]
        }
      }
];

@NgModule({
    imports: [RouterModule.forRoot(routes, {useHash: false})],
    exports: [RouterModule]
})
export class AppRoutingModule { }

```
 package.json

```
"dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "@types/node": "^7.0.12",
    "angular2-template-loader": "0.6.0",
    "aspnet-prerendering": "2.0.3",
    "aspnet-webpack": "^1.0.17",
    "awesome-typescript-loader": "^3.0.0",
    "bootstrap": "^3.3.7",
    "bootstrap-sass": "^3.3.7",
    "core-js": "^2.4.1",
    "css": "^2.2.1",
    "css-loader": "^0.25.0",
    "event-source-polyfill": "^0.0.7",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^2.0.0-rc",
    "file-loader": "^0.9.0",
    "html-loader": "^0.4.4",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^2.2.1",
    "json-loader": "^0.5.4",
    "json-server": "^0.12.0",
    "ng2-signalr": "2.0.4",
    "ngx-bootstrap": "^1.7.1",
    "node-sass": "^4.5.2",
    "preboot": "^4.5.2",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.1",
    "rxjs": "^5.0.1",
    "sass-loader": "^6.0.3",
    "signalr": "^2.2.1",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.5",
    "typescript": "2.3.4",
    "url-loader": "^0.5.7",
    "webpack": "^2.2.0",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1",
    "zone.js": "^0.8.9"
  },
  "devDependencies": {
    "@ngtools/webpack": "^1.3.0",
    "@types/chai": "^3.4.34",
    "@types/jasmine": "^2.5.37",
    "@types/jest": "^19.2.3",
    "chai": "^3.5.0",
    "codelyzer": "^3.0.0-beta.4",
    "jasmine-core": "^2.5.2",
    "jest": "^20.0.0",
    "jest-preset-angular": "^2.0.1"
  }
```

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

You might also try doing this without going to the `/` route first. Use relative routing (`./other_route`) so the router knows you don't just want to go to the root.

**Comment by valivvvv** [comment]
Hello @jasonaden ,
Can you give us a specific answer about this issue. There are many cases where we'd like for <a href=""> to work like [routerLink], if the url is on the same domain. Or maybe point us to documentation related to this case. 

Thank you, looking forward to clear out this issue!

**Comment by jrmcdona** [comment]
@valivvvv the routing framework doesn't work like that.  Use Javascript or a click event if you need to do something different

**Comment by MortPed** [comment]
@jrmcdona well, if you receive dynamic content from a CMS that is not a viable option.
