### ISSUE TITLE
need to pass data from dataservice to component in angular 4?

### ISSUE THREAD

**Issue by hruday11** [angular/angular#18861]
[dataservice.txt](https://github.com/angular/angular/files/1248742/dataservice.txt)

[create-project.txt](https://github.com/angular/angular/files/1248741/create-project.txt)

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
import { Component, OnInit } from '@angular/core'; 
import { DataService } from '../../services/data.service';

import { Scenario } from './step1TS/scenario';
import { Complainces} from './step1TS/complainces';
import { Budget } from './step1TS/budget';
import { Size } from './step1TS/size';
import { Duration } from './step1TS/duration';
import { Role } from './step1TS/role';

@Component({
	selector: 'app-create-projects',
	templateUrl: './create-projects.component.html',
	styleUrls: ['./create-projects.component.css']
})
export class CreateProjectsComponent implements OnInit {
	results : String[];
	selectedScenario : Scenario = new Scenario('Select A Scenario','');
	scenarios = [
	new Scenario('Select A Scenario',''),
	new Scenario('Scenario1','sc1'),
	new Scenario('Scenario2','sc2'), 
	new Scenario('Scenario3','sc3'),
	new Scenario('Scenario4','sc4'),
	new Scenario('Scenario5','sc5'),
	new Scenario('Scenario6','sc6')
	]
	selectedComplainces : Complainces = new Complainces('Type Of Complainces','');
	complainces = [
	new Complainces('Type Of Complainces',''),
	new Complainces('Complainces1','c1'),
	new Complainces('Complainces2','c2'), 
	new Complainces('Complainces3','c3'),
	new Complainces('Complainces4','c4'),
	new Complainces('Complainces5','c5'),
	new Complainces('Complainces6','c6')
	]
	selectedBudget : Budget = new Budget('Select A Budget','');
	budgets = [
	new Budget('Select A Budget',''),
	new Budget('Budget1','b1'),
	new Budget('Budget2','b2'), 
	new Budget('Budget3','b3'),
	new Budget('Budget4','b4'),
	new Budget('Budget5','b5'),
	new Budget('Budget6','b6')
	]
	selectedSize : Size = new Size('Size Of Project','');
	sizes = [
	new Size('Size Of Project',''),
	new Size('Size1','s1'),
	new Size('Size2','s2'), 
	new Size('Size3','s3'),
	new Size('Size4','s4'),
	new Size('Size5','s5'),
	new Size('Size6','s6')
	]
	selectedDuration : Duration = new Duration('Duration Of Project','');
	durations = [
	new Duration('Duration Of Project',''),
	new Duration('Duration1','d1'),
	new Duration('Duration2','d2'), 
	new Duration('Duration3','d3'),
	new Duration('Duration4','d4'),
	new Duration('Duration5','d5'),
	new Duration('Duration6','d6')
	]
	selectedRole : Role = new Role('Type Of Role','');
	roles = [
	new Role('Type Of Role',''),
	new Role('Role1','r1'),
	new Role('Role2','r2'), 
	new Role('Role3','r3'),
	new Role('Role4','r4'),
	new Role('Role5','r5'),
	new Role('Role6','r6')
	]

	constructor(private dataService: DataService ) { 
		
	}

	ngOnInit() {

	}
	public step1Div = true;
	public ErrorAlert = '';
	Step1(){ 
		if(this.selectedScenario.value === ''){
			this.ErrorAlert = "Please Select Anyone Scenarios"; 
		}else if (this.selectedComplainces.value === '') {

			this.ErrorAlert = "Please Select Anyone Complainces";

		}else if (this.selectedBudget.value === '') {

			this.ErrorAlert = "Please Select Anyone Budget";
		}else if (this.selectedSize.value === '') {

			this.ErrorAlert = "Please Select Anyone Size";

		}else if (this.selectedDuration.value === '') {

			this.ErrorAlert = "Please Select Anyone Duration";

		}else if (this.selectedRole.value === '') {

			this.ErrorAlert = "Please Select Anyone Role";

		}else{

			var step1Data = {"Scenario":this.selectedScenario.value,"Complainces":this.selectedComplainces.value,
			"Size":this.selectedSize.value,"Role":this.selectedRole.value,"Budget":this.selectedBudget.value,
			"Duration":this.selectedDuration.value,};

			// var url = "http://192.168.0.5:7003/soa-infra/resources/default/SELECT_DOCs1_L!1.0/RestService/";
			// this.http.get("http://192.168.0.5:7003/soa-infra/resources/default/SELECT_DOCs1_L!1.0/RestService/",step1Data).subscribe(data =>{
				// 	this.results = data['results'];
				// 	console.log(data);
				// })
			
				this.dataService.getDocs().subscribe((data =>{
					console.log(data);
				}))
				console.log(step1Data);

				this.step1Div = false;
			}
		}
	}

the Above is My Component and below is the code for Data Service

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
