### ISSUE TITLE
BIG IDEA. Integrate Virtual Scroll component to angular repository.

### ISSUE THREAD

**Issue by nickorsk2017** [angular/angular#18860]
[ ] Feature request
Hello. I like angular 4, but native scroll is slow.
I suggest integrate virtual scroll  to angular repository, like this
http://rintoj.github.io/angular2-virtual-scroll/#demo

P.S. tracker like "*ngFor="...trackBy:trackByF" - is slow.

**Comment by ghetolay** [comment]
This is definitely a request for cdk not Angular itself.

**Comment by nickorsk2017** [comment]
ghetolay. For large application performance is critical.
Virtual scroll is best for list about > 1000 items.
Is best solution if Angular will have this, because other repositories  often die.

**Comment by chrillewoodz** [comment]
@nickorsk2017 It's really not better if Angular has it.

**Comment by benelliott** [comment]
https://github.com/angular/material2/issues/823
