### ISSUE TITLE
@angular/upgrade should offer more fine grained control over the AngularJS $digest cycle

### ISSUE THREAD

**Issue by burtonjc** [angular/angular#18866]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The `UpgradeModule` runs a full AngularJS `$digest` cycle whenever the NgZone microTask queue is emptied. This is good because it allows a hybrid application to "just work"; however, it can be _very_ bad for large scale production apps that can't afford to have their `$digest` cycles triple throughout the upgrade process.

## Expected behavior

Developers should be able to opt-in to more fine grained control over the `$digest` cycle. Similar to how you can detach the Angular change detector a the component level and then trigger change detection only when it makes since, you should be able to disable automatically running the `$digest` cycle and trigger it only when it makes since. The API could be implemented any number of ways. An option could be disabling automatic `$digests` with a configuration at bootstrap time:
```typescript
upgrade.bootstrap(document.documentElement, ['myApp'], { disableDigests: true });
```
And then it would be ideal for the `UpgradeModule` to also have a helper method to trigger an AngularJS `$digest`. Something like
```typescript
@Component({
...
})
class MyComponent {
  constructor(private upgrade: UpgradeModule) { }

  myFunctionThatNeedsToDigest() {
    ...
    this.upgrade.$digest();
  }
}
```

## What is the motivation / use case for changing the behavior?

For a production application, especially ones dealing with large lists of editable data, `$digest` cycles are expensive. Most of these applications have been optimized to avoid full `$digest`s whenever possible. The `UpgradeModule` is not even an option at the moment for applications like this because it causes the number of `$digest` cycles to increase upwards of 3x for simple actions such as typing in an input box. Instead, it would be ideal to disable the automatic `$digest` call whenever the microTask queue is empty and instead leave it up to the developer to invoke `$digest`.

## Environment

<pre><code>
Angular version: 4.3.1

</code></pre>

**Comment by gkalpak** [comment]
The new [downgradeModule()][1] decouples the change detections of the two frameworks and leaves it up to the developer to manually invoke it when appropriate. (Docs will be added with #18487.)

Leaving this open, because I agree that the following features would be very useful:

1. Making the change detection coupling configurable.
2. Providing an easy way to manually run digests.

[1]: https://next.angular.io/api/upgrade/static/downgradeModule

**Comment by pangwa** [comment]
It would be nice to add an debounce option/callback for executing $digest after zone update. I noticed a large hybrid application got a noticeable performance boost after using debounced version..
`javascript
// 
//   $rootScope.$digest2 = _.debounce($rootScope.$digest, 20)
                    var subscription = _this.ngZone.onMicrotaskEmpty.subscribe(function () { return $rootScope.$digest2(); });  //digest2 is a debounced version of digest
                    $rootScope.$on('$destroy', function () { subscription.unsubscribe(); });
 
`

**Comment by pangwa** [comment]
Another found, no need to set a large debounce time(e.g. 20ms), use 0 to make sure digest happens at next tick will get the same performance boost!
```javascript
$rootScope.$digest2 = _.debounce($rootScope.$digest, 0)
```

**Comment by gkalpak** [comment]
Due to the low priority and low demand for this feature, I don't think we will ever get to implementing it at this point.
It is still possible to choose between the regular `NgUpgradeModule` (which "just works" but might be heavier on performance) and `downgradeLite()` (which has better performance but may require more "manual intervention").
