### ISSUE TITLE
Replace error messages with error codes and a link to angular.io

### ISSUE THREAD

**Issue by ocombe** [angular/angular#18875]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior
We have a lot of error messages in our code, but we could do better:
- there are no rules for error messages, each dev writes them the way he wants, and some of them are not very helpful
- the content of some error messages make them very hard to google because they are too generic
- there is no reference on angular.io for errors
- all of this text increases the payload and *cannot be minified*

Here is the number of errors in the packages that are usually included in an application:
- core: 40
- common: 12
- http: 8
- compiler: 67
- router: 30
- platform-browser: 14
- forms: 21

That's 192 error messages that end up in the vendor bundle for Angular. If we take a rough estimate of 60 bytes per error message, that's ~11.5kb of error messages that cannot be minified !

In AngularJS we had error codes and you could find some help in https://docs.angularjs.org/error. Also the uniqueness of error codes made them very easy to google.

In React they remove the errors from the minified builds and replace them with codes, in production it generates a link to their ["error decoder"](https://facebook.github.io/react/docs/error-decoder.html?invariant=31&args) which contains the unminified error message (read more about this on [their blog](https://facebook.github.io/react/blog/2016/07/11/introducing-reacts-error-code-system.html) and on [their github](https://github.com/facebook/react/tree/master/scripts/error-codes))

## Expected behavior
The error messages should be extracted from bundles and replaced by error codes. The best way to do it would be in ngc with a transformer so that the error messages are removed from production bundles but remain in development.
In production, the errors will throw a generic error message with the code and a link to angular.io that will contain the full error message and, if available, a thorough explanation that will help you to fix it.
In development it would be nice to have the full error message, the error code and the link to angular.io.

We should hopefully be able to decrease the payload for a complete application by at least 10kb.

**Comment by pkozlowski-opensource** [comment]
> That's 192 error messages that end up in the vendor bundle for Angular. If we take a rough estimate of 60 bytes per error message, that's ~11.5kb of error messages that cannot be minified !

@ocombe at one point I did an experiment of replacing all error messages _and_ asserts (we've got those too in the codebase) and saw bigger gains for just core+ common+platform-browser. So, I would expect bigger gains here (probably around 20 - 30kb). To be measured.

In any case I agree that this would be helpful in reducing bundles size 👍

**Comment by vicb** [comment]
Would be really nice to tackle this.
(As for the compiler messages are not part of the AOT app but there is a different effort to improve their usefulness)

**Comment by kapunahelewong** [comment]
@ocombe when this is ready for us to tackle, I'd love to help standardize/compose the error messages and make sure the docs covers them.

**Comment by kapunahelewong** [comment]
@jenniferfell This issue is something to keep in mind for the future.

**Comment by jenniferfell** [comment]
docsarea=errormessages

**Comment by jenniferfell** [comment]
Adding docs/api and aio components, because the solution could involve those areas.

**Comment by ajitsinghkaler** [comment]
@petebacondarwin @gkalpak is this still applicable

**Comment by gkalpak** [comment]
Yes, I believe this is still applicable.

**Comment by aikidave** [comment]
The Angular team has added a lot of new information for understanding error messages. For example: https://angular.io/errors/NG0100

Closing this issue!
