### ISSUE TITLE
Documentation: use Observable instead toPromise() of  in tutorial/toh-pt6 

### ISSUE THREAD

**Issue by CedricLevasseur** [angular/angular#18874]
Please show us an Example of Observable in the Hero Tutorial.
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/tutorial/toh-pt6 only make use of .toPromise()
  ```
getHero(id: number): Promise<Hero> {
    const url = `${this.heroesUrl}/${id}`;
    return this.http.get(url)
      .toPromise()
      .then(response => response.json().data as Hero)
      .catch(this.handleError); 

```
## Expected behavior

As the HTTP technical page (https://angular.io/guide/http) describe it , the tutorial should provide a real example a http.get wih Observable with error management.
```
http
  .get<ItemsResponse>('/api/items')
  .subscribe(
    // Successful responses call the first callback.
    data => {...},
    // Errors will call this callback instead:
    err => {
      console.log('Something went wrong!');
    } 

```

## Minimal reproduction of the problem with instructions
Go to : https://angular.io/tutorial/toh-pt6
## What is the motivation / use case for changing the behavior?

Really help the newbies, as me ! 
Understanding Observables vs Promise is not easy for the early users.
The documentation should be coherent.

## Environment

Angular version: 4 documentation

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Foxandxss** [comment]
There are some changes to the tutorial underway and that is in the list :)

**Comment by kapunahelewong** [comment]
Thanks for reporting this issue. It has since been fixed in one of the recent releases. 

 @CedricLevasseur does it now cover what you'd wanted? If you have any questions, please let me know and we can revisit.

**Comment by CedricLevasseur** [comment]
Perfect ! Thanks
