### ISSUE TITLE
Do not expose comments/TODO's in docs

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#18873]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Go to [DefaultValueAccessor's page](https://angular.io/api/forms/DefaultValueAccessor) and see:

```
@Directive({
  selector:
      'input:not([type=checkbox])[formControlName],textarea[formControlName],input:not([type=checkbox])[formControl],textarea[formControl],input:not([type=checkbox])[ngModel],textarea[ngModel],[ngDefaultControl]',
  // TODO: vsavkin replace the above selector with the one below it once
  // https://github.com/angular/angular/issues/3011 is implemented
  // selector: '[ngModel],[formControl],[formControlName]',
  ...
```

**Comment by Foxandxss** [comment]
@petebacondarwin This seems right in your alley.

**Comment by petebacondarwin** [comment]
Oh bother. That is going to be a pain. It would probably be easier to fix the thing that needed to be "done".

**Comment by petebacondarwin** [comment]
See https://next.angular.io/api/forms/DefaultValueAccessor
