### ISSUE TITLE
HttpClient: ERROR TypeError: CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by dgroh** [angular/angular#18885]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After adding headers to the cloned request and calling `.get` I get the following exception:

![image](https://user-images.githubusercontent.com/16785357/29736789-fdb13a58-8a04-11e7-8ec2-87537a33ca8d.png)

This is my interceptor:

```ts
  public intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

    let request = req.clone({
      setHeaders: {
        ModuleId: this.dnnContext.moduleId,
        TabId: this.dnnContext.tabId
      }
    });

    // Pass on the cloned request instead of the original request.
    return next.handle(request);
  }
```

```ts
@Injectable()
export class ContractService {
  constructor(private httpClient: HttpClient) { }

  public getContracts(): Observable<any> {
    return this.httpClient.get("The Api Url");
  }
}
```

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by aks0020** [comment]
Faced similar issue & found that this error only occurs if you pass `Number` type value in header 
so convert it to string while passing:
```
const authReq = req.clone({
  headers: req.headers.set('ModuleId', this.dnnContext.moduleId.toString()).set('TabId', this.dnnContext.tabId.toString())
});
// Pass on the cloned request instead of the original request.
return next.handle(authReq);
```

**Comment by dgroh** [comment]
@aks0020 it doesn't make sense. It's type safe, if I try to pass a `number`, it won't transpile at all.

So, in my case it's a `string`.

**Comment by aks0020** [comment]
it is type safe but in my case it was coming from global state(class which has 'any' type property)
so it was allowing any type value & it was number 
`const profileIdHeader = this.appState.userProfile.profileId;`
& as it is any type it was not giving any compile error adding toString() fixed for me.

**Comment by aks0020** [comment]
I suggest you to try passing static string val "test" in both your headers. if you are still facing issue with static val & then your case might be different.

**Comment by dgroh** [comment]
In my case is already coming as a `string`, because the types of `tabId` and `moduleId` are already `string` so I think in my case is something different, unfortunately!

**Comment by dgroh** [comment]
Thanks @aks0020 - I created a project apart. as I could not find the issue and it's working now. Closing the issue!

**Comment by dgroh** [comment]
Wow, @aks0020 you were completely right. The ids were coming in as numeric...

**Comment by jagomf** [comment]
@aks0020 you made my day!
That causes all sorts of weird and non-sense problems, been looking around for days..!
