### ISSUE TITLE
Invalid inline CSS @ 5.0.0-beta.4-1c2f3d4

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#18883]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using `ngc` from the latest master (or `angular/compiler-cli-builds`), and compiling components with styles containing properties with a dash (like `line-height`), sometimes invalid code is generated in which objects contain the invalid `line-height` property.

This doesn't seem to always happen though. 

It can be seen in `@angular/material@2.0.0-beta.8`, in the `MdExpansionPanelHeader` component. It contains the following styles array:
```
styles: [".mat-expansion-panel-header{cursor:pointer;display:flex;flex-direction:row;height:48px;line-height:48px;padding:0 24px}.mat-expansion-panel-header.mat-expanded{height:64px;line-height:64px}.mat-expansion-panel-header:focus,.mat-expansion-panel-header:hover{outline:0}.mat-expansion-panel-header.mat-expanded:focus,.mat-expansion-panel-header.mat-expanded:hover{background:inherit}.mat-content{display:flex;flex:1;flex-direction:row;overflow:hidden}.mat-expansion-panel-header-title{display:flex;flex-grow:1;font-size:15px;margin-right:16px}.mat-expansion-panel-header-description{display:flex;flex-grow:2;font-size:15px;margin-right:16px}.mat-expansion-indicator::after{border-style:solid;border-width:0 2px 2px 0;content:'';display:inline-block;padding:3px;transform:rotate(45deg);vertical-align:middle}"],
```

There's a lot of things here but the important ones are `line-height:48px;` and `line-height:64px`.

When compiled through `ngc`, the following code is generated:
```
var styles_MdExpansionPanelHeader = [".mat-expansion-panel-header{cursor:pointer;display:flex;flex-direction:row;height:48px;line-height:48px;padding:0 24px}.mat-expansion-panel-header.mat-expanded{height:64px;line-height:64px}.mat-expansion-panel-header:focus,.mat-expansion-panel-header:hover{outline:0}.mat-expansion-panel-header.mat-expanded:focus,.mat-expansion-panel-header.mat-expanded:hover{background:inherit}.mat-content{display:flex;flex:1;flex-direction:row;overflow:hidden}.mat-expansion-panel-header-title{display:flex;flex-grow:1;font-size:15px;margin-right:16px}.mat-expansion-panel-header-description{display:flex;flex-grow:2;font-size:15px;margin-right:16px}.mat-expansion-indicator::after{border-style:solid;border-width:0 2px 2px 0;content:'';display:inline-block;padding:3px;transform:rotate(45deg);vertical-align:middle}"];
var RenderType_MdExpansionPanelHeader = i0.ɵcrt({ encapsulation: 2, styles: styles_MdExpansionPanelHeader, data: { "animation": [{ type: 7, name: "indicatorRotate", definitions: [{ type: 0, name: "collapsed", styles: { type: 6, styles: { transform: "rotate(0deg)" }, offset: null }, options: undefined }, { type: 0, name: "expanded", styles: { type: 6, styles: { transform: "rotate(180deg)" }, offset: null }, options: undefined }, { type: 1, expr: "expanded <=> collapsed", animation: { type: 4, styles: null, timings: "225ms cubic-bezier(0.4,0.0,0.2,1)" }, options: null }], options: {} }, { type: 7, name: "expansionHeight", definitions: [{ type: 0, name: "collapsed", styles: { type: 6, styles: { height: "48px", line-height: "48px" }, offset: null }, options: undefined }, { type: 0, name: "expanded", styles: { type: 6, styles: { height: "64px", line-height: "68px" }, offset: null }, options: undefined }, { type: 1, expr: "expanded <=> collapsed", animation: { type: 4, styles: null, timings: "225ms cubic-bezier(0.4,0.0,0.2,1)" }, options: null }], options: {} }] } });
```

The important parts are these two objects:
```
{ height: "48px", line-height: "48px" }
{ height: "64px", line-height: "68px" }
```

These are invalid JavaScript because the `line-height` key contains a dash, and should be enclosed in quotes instead (`"line-height"`).

## Expected behavior
Valid JS code should be generated.

## Minimal reproduction of the problem with instructions
Compile AIO with the new `ngc`.

## What is the motivation / use case for changing the behavior?

Invalid code generated.

## Environment

<pre><code>
Angular version: `5.0.0-beta.4-1c2f3d4`

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1
- Platform:  Windows

Others:

</code></pre>
/cc @tbosch

**Comment by filipesilva** [comment]
Correction: this seems to be related to animations instead of the styles array. The `line-height`s that cause error are the ones below.
```
animations: [
    trigger('indicatorRotate', [
        state('collapsed', style({ transform: 'rotate(0deg)' })),
        state('expanded', style({ transform: 'rotate(180deg)' })),
        transition('expanded <=> collapsed', animate(EXPANSION_PANEL_ANIMATION_TIMING)),
    ]),
    trigger('expansionHeight', [
        state('collapsed', style({ height: '48px', 'height': '48px' })),
        state('expanded', style({ height: '64px', 'height': '68px' })),
        transition('expanded <=> collapsed', animate(EXPANSION_PANEL_ANIMATION_TIMING)),
    ]),
],
```

**Comment by vicb** [comment]
@filipesilva Your last message is correct. The culprit does not seem to be the compiler but rather the CSS compiler or the animations.

FYI you can use the `disableTransformerPipeline` option to revert to using the former compiler.

**Comment by tbosch** [comment]
I have a PR to fix this, this s a known issue...

**Comment by tbosch** [comment]
See https://github.com/angular/angular/pull/18788

**Comment by matsko** [comment]
@filipesilva you can also do `lineHeight` and that should work fine.

**Comment by tbosch** [comment]
This is fixed in master now via https://github.com/angular/angular/commit/2fbc92fd2e8c36f506f2c777f12e7cb20d7b5c08
