### ISSUE TITLE
Angular 2 url routing with hash is not working in Firefox 55.0.3(64)

### ISSUE THREAD

**Issue by amarnathjena** [angular/angular#18888]
My project url is like http://localhost:4200 it is routing to home page as http://localhost:4200/#/home
Then there my button for login is like 
<li [routerLink]="['/login']" class="icon-sign-in">Login</li>

But when i am clicking to login button on home page site in firefox, it is redirecting to http://localhost:4200/null and then again auto redirecting to http://localhost:4200/null#/home

**It suppose to go http://localhost:4200/#/login as in Chrome it is going.**

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
