### ISSUE TITLE
DI/Dart: "toFactory"'s dependencies argument should be optional

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1888]
Now:

```dart
Foo createFoo(Bar bar) => new Foo(bar);

const Binding(Foo, toFactory: createFoo, deps: const [Bar]);
```

Proposed:

```dart
Foo createFoo(Bar bar) => new Foo(bar);

const Binding(Foo, toFactory: createFoo);
```

@kegluneq for analyzer reference.

**Comment by yjbanov** [comment]
This requires that we reflect on the `createFoo` function and extract dependencies the same way we extract them from constructors. Should be doable, but only for const bindings that appear in the annotations. Imperative bindings still require that dependencies are listed explicitly.

**Comment by naomiblack** [comment]
this is also b/21131937.

**Comment by naomiblack** [comment]
dup of https://github.com/angular/angular/issues/3183
