### ISSUE TITLE
If a navigation occurs before the previous one is finished, the previous one fails completely

### ISSUE THREAD

**Issue by dbettini** [angular/angular#18882]
## I'm submitting a...

<pre><code>
[ x ] Bug report  
</code></pre>

## Current behavior
If a router navigation occurs before the previous navigation is finished, the previous navigation fails completely. [This](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L696) condition becomes true because `id !== this.navigationId`, and the state is never set. This means that, if that state had some queryParams you're listening to for example, the change is never registered.

## Expected behavior
The state change should resolve until the end.

## Minimal reproduction of the problem with instructions
I'm guessing this is done on purpose, to just skip unnecessary navigations. However, it can result in unexpected, random behaviour. 

What I'm doing here is setting a configuration through queryParams on the first app load. I can not use the [ActivatedRouteSnapshot](https://angular.io/api/router/ActivatedRouteSnapshot), since the [initial state is empty](https://github.com/angular/angular/issues/12157#issuecomment-254964023), so I have to listen to the queryParams observable, and read my configuration when it's available.  

My app is inside an iframe which can receive a new url through postMessage from a parent, so it calls [navigateByUrl](https://angular.io/api/router/Router#navigateByUrl) inside the parent message listener.

What happens is, if the parent immediately schedules navigation (let's say to `/`, the root of the app), the initial navigation sometimes doesn't finish. The queryParams observable subscriber doesn't get any new values. This results in the configuration sometimes not getting set. If I delay the parent postMessage for a second with setTimeout, it always works because the initial navigation that contains queryParams finished.

The way I wanted to tackle this at first was setting [queryParamsHandling](https://angular.io/api/router/NavigationExtras#queryParamsHandling) to `preserve` in my call to navigateByUrl. However, that doesn't help, since the initial navigation was completely rejected, so those queryParams are not available anymore either.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [ x ] Chrome (desktop) version 59

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

We are also looking at a change that would differentiate between `router.navigate` and `router.redirect`. This would allow you to explicitly determine the behavior you want. However, this would be a significant breaking change to `router.navigate` as it currently stands. This might be something that lands in `v6`.
