### ISSUE TITLE
Relative Route in Resolver

### ISSUE THREAD

**Issue by mahmood-sajjadi** [angular/angular#18889]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

for relative navigation we should pass extra parameter like { relativeTo: ActivatedRoute}
however, in Resolver we have access to ActivatedRouteSnapshot and not ActivatedRoute becuse page is not loaded yet
using previous ActivatedRoute is not possible too, because user can navigate to this router from any page and relative navigation from the unknown page is impossible

## Expected behavior

we should be able to navigate relative to the destination in Resolvers

## What is the motivation / use case for changing the behavior?

It will be really useful if we can navigate to another page relative to resolve destination. for example in case of error for error handling. right now the only possible scenarios for error handling in Resolvers are:
1) navigate to known page with absolute URL
2) do nothing and stay in source

## Environment

<pre><code>
Angular version: 4.X.X

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mikeeus** [comment]
Hi @mahmood-sajjadi, I had this problem too. Here's my hacky solution to navigate to the parent given the ActivatedRouteSnapshot:

`

        let url = '';
        let parent = route.parent;

        while (parent) {
          if (parent.url[0]) {
            url = `${parent.url[0].path}/${url}`;
          }
          parent = parent.parent || null;
        }
        this.router.navigate([url]);
`

Hope that helps :)

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

Try the above workaround. I believe adding this feature would be a not-insignificant amount of code which will bloat the router codebase (it's already bigger than we would like). Maybe creating a helper function is the best way to go on this.

**Comment by thejohnfreeman** [comment]
This doesn't do what I want. It reruns every resolver from the parent route on down to the point I wanted to navigate relative-to.
