### ISSUE TITLE
AoT production runtime error when exporting named imports.

### ISSUE THREAD

**Issue by vitorrd** [angular/angular#18897]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When importing the following:

```
import * as moment from 'moment';

export { moment as moment }; // For clarity
```

And using it such as:

`let x = moment();`

The Angular AoT compiler in production (built using **ng build --aot --prod**) will generate code like:

`var x = a[!0]();`

This happened with two imports I renamed for adding them in their own small modules, **moment** and **object-assign**.

## Expected behavior
This should work. It works in all configurations except in **--aot --prod**.

## Minimal reproduction of the problem with instructions
The steps above should suffice. If not reproducible, I can create a small plunkr (I'm on the clock, so the report is all I can do at the moment).

## What is the motivation / use case for changing the behavior?
This should work.

## Environment
angular 4.3.5
angular-cli 1.3.1
moment 2.18.1
object-assign 4.1.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Windows 10

**Comment by chuckjaz** [comment]
I made the following changes to an `ng new` project:

```
diff --git a/package.json b/package.json
index d836fa1..8001de1 100644
--- a/package.json
+++ b/package.json
@@ -21,7 +21,9 @@
     "@angular/platform-browser": "^4.2.4",
     "@angular/platform-browser-dynamic": "^4.2.4",
     "@angular/router": "^4.2.4",
+    "@types/moment": "^2.13.0",
     "core-js": "^2.4.1",
+    "moment": "^2.19.1",
     "rxjs": "^5.4.2",
     "zone.js": "^0.8.14"
   },
diff --git a/src/app/app.module.ts b/src/app/app.module.ts
index f657163..35e2604 100644
--- a/src/app/app.module.ts
+++ b/src/app/app.module.ts
@@ -3,6 +3,8 @@ import { NgModule } from '@angular/core';
 
 import { AppComponent } from './app.component';
 
+import {moment} from './re-exp-moment';
+
 @NgModule({
   declarations: [
     AppComponent
@@ -14,3 +16,7 @@ import { AppComponent } from './app.component';
   bootstrap: [AppComponent]
 })
 export class AppModule { }
+
+var x = moment();
+
+window['asdf'] = x;
```

and the main bundle did not contain the invalid code that you mentioned in your report.

Can you provide a link to a repository that reproduces this?

**Comment by mhevery** [comment]
This issue seems abandoned without any reproducible instruction.  We are closing the issue. If you have reproducible instructions please file a new issue.
