### ISSUE TITLE
How do not reload last page when back?

### ISSUE THREAD

**Issue by SandLZ** [angular/angular#18896]
Router tree:
![image](https://user-images.githubusercontent.com/11996442/29752421-31f53cc4-8b90-11e7-8a0c-a8724bd37481.png)

 i navigate to ScenicComponent from HomeComponent, and back to HomeComponent, HomeComponent call ngOnInit() again, How do not reload the HomeComponent?
Thank!!!

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
