### ISSUE TITLE
HttpClient Progress Event : no total property on progress event

### ISSUE THREAD

**Issue by seedy** [angular/angular#18892]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am **using HttpClient to monitor progress events on a cross domain GET request**. 
I am consuming data from Youtube API and CORS tokens are correctly set.

I followed the guide at https://angular.io/guide/http#listening-to-progress-events
But **I can't obtain events of type DownloadProgress with a total property**.

I tried adding `access-control-allow` and `access-control-expose` headers for `'Content-Length'` : 

```
this.httpClient.get(url,` {
        reportProgress: true,
        observe: 'events',
        headers: new HttpHeaders()
          .set('Content-Type', 'application/json')
          .set('Access-Control-Allow-Headers', 'Content-Length')
          .set('Access-Control-Expose-Headers', 'Content-Length')
      })

```
but I actually receive it and access it through the retrieved response when observing the response object.

Am I missing something?

## Expected behavior

Obtain event.total value on events of type UploadProgress

## Minimal reproduction of the problem with instructions
Almost same code as https://angular.io/guide/http#listening-to-progress-events
- on a 'GET' request
- with event.type === HttpEventType.DownloadProgress

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [x] Chrome (desktop) version 60.0.3112.101
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ToMakeSense** [comment]
I am not sure whether [my case- #18842](https://github.com/angular/angular/issues/18842) is similar to yours, if you declare event to **Event** type, you have to use event["total"] or event.XXX["total"] to get the property value. or you can just set no type(maybe any) of event parameter, then you can use event.total.

**Comment by seedy** [comment]
In your case, you're talking about DOM Events and Angular2's wrapper.
Here I'm having issues with what's likely to be HttpEvents.
Trying to force the type of my event doesn't help though :
````
(event: HttpEvent<any>) => {}
````
no total property in debugger

**Comment by ricio91** [comment]
same issue for  me

**Comment by andyrue** [comment]
I know @seedy isn't using his own API, but in my case I needed to set `headers['Content-Length']` to the file size in my API before sending the response and then I started getting an `event.total` in the Http response in Angular.

**Comment by wnabil** [comment]
@andyrue yes if you set the content length header from the backend you will get the total, Thanks man.

**Comment by gaokun** [comment]
same issue, mark

**Comment by alxhub** [comment]
As @andyrue hinted, `total` is only available if the browser knows how many bytes are coming back before the response completes. This requires the server to send a `Content-Length` header with the response.
