### ISSUE TITLE
PlatformLocation href and origin params

### ISSUE THREAD

**Issue by glebmachine** [angular/angular#18890]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
PlatformLocation object have `href` and `origin`, but they not exists in d.ts

## Expected behavior
PlatformLocation.d.ts have definitions of `href` and `origin`

## What is the motivation / use case for changing the behavior?
Thats weird, i can't to compile code which using `PlatformLocation.href` 

## Environment

<pre><code>

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.3.2
node: 6.9.2
os: darwin x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/flex-layout: 2.0.0-beta.9-ea26752
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/platform-server: 4.3.6
@angular/router: 4.3.5
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.5

Browser:
- All Browsers
- Server
</code></pre>

**Comment by vicb** [comment]
This is the definition for PlatformLocation https://github.com/angular/angular/blob/24bf3e2a251634811096b939e61d63297934579e/packages/common/src/location/platform_location.ts#L32

There is no href nor origin.
