### ISSUE TITLE
v4.3.6 is undocumented

### ISSUE THREAD

**Issue by xnnkmd** [angular/angular#18898]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I can see in npm that a version 4.3.6 has been released but this version is not documented in the changelog. 

## Expected behavior
changelog should describe v4.3.6 (like all other releases).

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular/angular/blob/4.3.x/CHANGELOG.md
