### ISSUE TITLE
Providing a multi-token in a component overrides all providers from the module

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#18894]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

#### Module's providers

```js
    {
      provide: aToken,
      useValue: 'foo',
      multi: true,
    },
    {
      provide: aToken,
      useValue: 'bar',
      multi: true,
    },
```

#### A component in such module

```js
@Component({
  selector: 'my-app',
  template: `Providers: {{ tokens | json }}`,
  providers: [
    {
      provide: aToken,
      useValue: 'baz',
      multi: true,
    }
  ]
})
export class AppComponent  {
  constructor(@Inject(aToken) public tokens: string[]) {}
}
```

#### Rendered

```plain
Providers: [ "baz" ]
```

## Expected behavior

I expect multi-providers to be mixed.

#### Rendered

```plain
Providers: [ "foo", "bar", "baz" ]
```

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/multi-provider-bug?file=app%2Fapp.component.ts

## What is the motivation / use case for changing the behavior?

It's confusing.

The only workaround I could think of is the following.

https://stackblitz.com/edit/multi-provider-bug-workaround?file=app/app.component.ts

We create another token and `useExisting` providers from the module, and then keep adding more.

```js
  providers: [
    {
      provide: anotherToken,
      useExisting: aToken,
      multi: true,
    },
    {
      provide: anotherToken,
      useValue: 'baz',
      multi: true,
    }
  ]
```

A problem with this, however, is that providers are not flattened (which is expected).

#### Rendered

```plain
Providers: [ [ "foo", "bar" ], "baz" ]
```

## Environment

<pre>
Angular version: 4.3.5

Browser: all
</pre>

**Comment by EricABC** [comment]
Same issue with extraProviders in the platform bootstrap being overloaded by the module.  It would be nice to drop in things like HTTP_INTERCEPTORS exported from various environment.\<env\>.ts files (i.e. demoing detached apps with fake data).  In this particular example, by not travelling up the tree it requires me to have internal knowledge about HttpClientModule and how it already registers other interceptors at the module level.

**Comment by alexzuza** [comment]
Component has its own injector which doesn't inherit providers from parent injector. It can only read providers from parent injector if there is no provider in current injector. I think that's why it's not working with `multi` option.

Another workaround

```
export function tokenFactory(aToken) {
  return [...aToken, 'baz'];
}
@Component({
  selector: 'my-app',
  template: `
    Providers: {{ tokens | json }}
  `,
  providers: [
    {
      provide: aToken,
      useFactory: tokenFactory,
      deps: [[new SkipSelf(), aToken]],
    }
  ]
})
export class AppComponent  {
  constructor(@Inject(aToken) public tokens: string[]) {}
}

```

https://stackblitz.com/edit/multi-provider-bug-workaround-tc8rns?file=app/app.component.ts

**Comment by IliaVolk** [comment]
Sad that I have to use such crutch to get interceptors from parent module
```
        // https://github.com/angular/angular/issues/18894
        {
            provide: HTTP_INTERCEPTORS,
            multi: true,
            useFactory(interceptors: HttpInterceptor[]) {
                return new class implements HttpInterceptor {
                    intercept(req: HttpRequest<any>, next: HttpHandler):
                        Observable<HttpEvent<any>> {
                        return interceptors.reduceRight(
                            (next, interceptor) => ({
                                // HttpInterceptorHandler not exported, so use duck typing
                                handle(req: HttpRequest<any>) {
                                    return interceptor.intercept(req, next);
                                },
                            }), next).handle(req);
                    }
                };
            },
            deps: [[new SkipSelf, new Inject(HTTP_INTERCEPTORS)]],
        },
```

**Comment by petebacondarwin** [comment]
Note that this is a general case of #19852, which had a couple of additional votes that might be added to this one.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
