### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by ihabsalem** [angular/angular#18899]
The issue in the animation tutorial, in the following link ->"https://angular.io/api/animations/animation" 

**fade animation** variable has an error which is: 
 

- there is an open '{' but it's not closed inside style parameter function.
-----------------------------------------------------------------------

the current example: 
`var fadeAnimation = animation([
  style({ opacity: '{{ start }}' }),
  animate('{{ time }}',
    style({ opacity: '{{ end }}'))
], { params: { time: '1000ms', start: 0, end: 1 }});`

it should be: 

`var fadeAnimation = animation([
 style({ opacity: '{{ start }}' }),
  animate('{{ time }}',
    style({ opacity: '{{ end }}'}))
], { params: { time: '1000ms', start: 0, end: 1 }});`

**Comment by gkalpak** [comment]
PRs welcome :smiley:

**Comment by tbosch** [comment]
Fixed via e81d1fc3616419b8f109fe1fe87591f241f5afdb
