### ISSUE TITLE
NG-Class content in support docs

### ISSUE THREAD

**Issue by brykayne** [angular/angular#18908]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Page reads: "It's up to you to call setCurrentClassess(), both initially and when the dependent properties change."

## Expected behavior

Change "setCurrentClassess()" to "setCurrentClasses()"

## Minimal reproduction of the problem with instructions
Visit:  https://angular.io/guide/template-syntax#ngclass and search for text above.

## What is the motivation / use case for changing the behavior?

Spelling mistake

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
@brykayne would you mind sending a PR ?

**Comment by FrontEndCoffee** [comment]
It seems that this was fixed in [049c89645b](https://github.com/angular/angular/commit/049c89645b7727475a0de77c104d4163eb578576#diff-fe1da8d4b293de490dd0cef57e6d036b) a while ago.

**Comment by pkozlowski-opensource** [comment]
Closing based on 

> It seems that this was fixed in 049c89645b a while ago.
