### ISSUE TITLE
ngIf not working with material md-select within router (4.3.6 x, 4.3.5 o)

### ISSUE THREAD

**Issue by alanpurple** [angular/angular#18900]
I think this does not need any plunkr code

works fine with 4.3.5

**Comment by Toxicable** [comment]
works fine here https://stackblitz.com/edit/angular-oesegx?file=app%2Fapp.component.ts

**Comment by pkozlowski-opensource** [comment]
> I think this does not need any plunkr code

It certainly does! Please provide one or this issue is not actionable and will be closed.

**Comment by alanpurple** [comment]
Okay, I'll reproduce, plz wati

**Comment by alanpurple** [comment]
I have so many components, and I still can't what's conflicted

**Comment by trotyl** [comment]
If you're submitting an Angular bug, make sure you're not using any library, this is not a valid issue report.

**Comment by alanpurple** [comment]
@trotyl yes I know I didn't aware at first... sorry

**Comment by AlexKhymenko** [comment]
Actually its not working look at plunker https://plnkr.co/edit/fNVPmSWJoPk4ehD3Pu6a?p=preview
First go to 2 route then go to the first route it should dissapear. Or am i doing it wrong???

**Comment by tytskyi** [comment]
@AlexKhymenko `see` is `true` https://plnkr.co/edit/QNFQ6srwAscWl81SYZDm?p=preview

**Comment by AlexKhymenko** [comment]
@tytskyi but it should be false if you open console.log you will see i changed it to false

**Comment by trotyl** [comment]
You're leaking the memory. Each navigation would create a new component instance, and you're modifying the old one's. https://plnkr.co/edit/WCyOVUpNWCsO9dEatkm1?p=preview

![image](https://user-images.githubusercontent.com/6059170/29824533-6620fbc6-8d04-11e7-9bd2-dd6c2a282116.png)

**Comment by AlexKhymenko** [comment]
@trotyl Thank You!!

**Comment by Toxicable** [comment]
Can be closed since there is no issues here with ngIf?

**Comment by alanpurple** [comment]
angular-material 2.0.0-beta.10 released today
still only works with 4.3.5, doesn't work with 4.3.6

and this is nothing related to "subscribe and unsubscribe" things

**Comment by alanpurple** [comment]
many are posted on angular-material2 issue board

sorry for misunderstanding
