### ISSUE TITLE
[ngUpgrade] onInit fires too early on downgraded components 

### ISSUE THREAD

**Issue by rkirov** [angular/angular#18913]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The following component is downgraded and used in an AngularJS application:

```typescript
export class Ng2ComponentBindings implements OnInit, OnChanges {
  @Input() foo: {a: number};

  ngOnInit() {
    console.log('ngInit:', this.foo);
  }

  ngOnChanges() {
    console.log('ngOnChange:', this.foo);
  }
}

ng1module.directive(
  'ng2ComponentBindings',  // lowerCamel when registering.
  downgradeComponent(
      {component: Ng2ComponentBindings, propagateDigest: true}));
```

it is used like this ``` <ng2-component-bindings [foo]="$ctrl.foo"></ng2-component-bindings>```

The order of events is:
- ngOnInit fires
- foo is set
- ngOnChanges fires

## Expected behavior

The order of events should be:
- foo is set
- ngOnChanges fires
- ngOnInit fires

Because that is how a regular Angular component would behave.

**Comment by gkalpak** [comment]
@rkirov, I tried to reproduce this [here][1], but everything seems to work as expected. Maybe this behavior is affected by other stuff, such as structural directives.

What AngularJS/Angular versions are you using?
Can you try to reproduce it in the plnkr (or a sample repo)?

[1]: http://plnkr.co/edit/JCP9CRyhZDsE008Kt1xX?p=preview

**Comment by rkirov** [comment]
Very odd indeed, the example looks very similar to the one I am looking at. Could it be AOT vs JIT? I will debug it a bit more.

**Comment by rkirov** [comment]
Do you have an NgUpgradeLite plunker template? I see the issue with an NgUpgradeLite.

**Comment by gkalpak** [comment]
@rkirov: [ngUpgradeLite template][1].

[1]: http://plnkr.co/edit/tpl:3nibNAT9FNBNGJirmIax

**Comment by gkalpak** [comment]
Oh look, another [ngUpgradeLite template][1] for StackBlitz ✨

[1]: https://stackblitz.com/edit/ngupgradelite-playground

**Comment by rkirov** [comment]
Neat, thanks for the templates!

Here is the repro - https://stackblitz.com/edit/ngupgradelite-playground-2dputs 

console shows:

```
onInit undefined
onChanges ngUpgradeLite
```

**Comment by gkalpak** [comment]
This happens because we manually attach the componen't `hostView` to the `ApplicationRef`...

https://github.com/angular/angular/blob/0f5c70d563b6943623a5940036a52fe077ad3fac/packages/upgrade/src/common/downgrade_component_adapter.ts#L156-L158

...which apparently cause it to be change-detected too soon, before our AngularJS watcher updates the properties and calls the initial `ngOnChanges()`...

https://github.com/angular/angular/blob/0f5c70d563b6943623a5940036a52fe077ad3fac/packages/upgrade/src/common/downgrade_component_adapter.ts#L135-L141

Should be an easy fix.

**Comment by VictorCoding** [comment]
Hello guys,

I'm not sure if this is related to this whole issue but one thing that is happening is that `ngOnChanges` is returning the following on the first run given 

```
{
  currentValue: 9,
  firstChange: true,
  previousValue: 9,
}
```

as you can see, first of all `previousValue` is already set even though it should be undefined and second fo all, `firstChange` is `true`.

Reproduction Demo:

https://stackblitz.com/edit/ngupgradelite-playground-vttjsc

**Comment by gkalpak** [comment]
The `firstChange` value is true, but we explicitly set `previousValue` equal to `currentValue` on first change. That is indeed not very intuitive (and it doesn't seem to be consistent with neither Angular nor AngularJS).

I think we want to be consistent with Angular here, which sets `previousValue` to `undefined`. 

@VictorCoding, would you be interested in submitting a pull request with the fix? (I would be more than happy to provide help and guidance :smiley:)

**Comment by VictorCoding** [comment]
@gkalpak Thanks for the reply and confirmation of the situation. I'm down to give it a shot. I've looked around the code and I might have an idea where I can fix it but if anything comes up I'll reach out. Is this the best place to do that or should I open a new issue?

**Comment by gkalpak** [comment]
That's awesome :heart:

Feel free to open a PR and we can use that to track and discuss the issue. If you want to discuss something before opening the PR, it's preferrable to open a new issue, since this is actually a separate problem.
