### ISSUE TITLE
Cordova angular4 iOS cpu usage is high

### ISSUE THREAD

**Issue by mob1** [angular/angular#18916]
Hi, 
We are using angular 4 and Cordova and have already built the app with more animations and api calls.. we see now more cpu usage in iphone and device also getting  heated.. 

Chrome profiling found few animations running in background and that also corrected.. after correction also same issue exist only in iOS 

Any problem due to zone JS handle for rxjs, Cordova and animation calls?. We have default zone JS chAnge detection only..

Suggest any better way to debug for iOS as similar to chrome? iOS safari web inspector gives time profiler but not able to figure out the animation issues..

Angular -4.2.6
Zone JS - 0.8.16
Cordova iOS - 4.3.0
Rxjs - 0.5.14

**Comment by vovikdrg** [comment]
I am not sure how with those details team would be able to help you.

Look to [this ](https://taco.visualstudio.com/en-us/docs/measure-performance/) and try to profile yourself to see what is the problem. If you find that problem is in framework then add more details. From my personal experience my issues was related to not unsubscribing from observable.

**Comment by mob1** [comment]
thanks for the suggestion.. will profile and provide more details.. any issue reported like this earlier for angular ?

**Comment by vovikdrg** [comment]
@mob1 no, I am pretty sure issue is somewhere in your code, otherwise there would be tons of issues like that. For instance I am in process of my app with ionic (which is using angular) and it working so fast.

**Comment by mob1** [comment]
@vovikdrg , i am checking to unsubscribe all observables but when i checked and it looks like default all observables are unsubscribed. is that correct?.. do we need manually to unsubscribe the rxjs observables?

**Comment by mob1** [comment]
any tools to capture the unsubscribe events?

**Comment by vovikdrg** [comment]
@mob1  it depend what you mean by default :) if we are talking about Http then yes no needs to unsubscribe

**Comment by mob1** [comment]
We have both 1) custom observables 2) angular http ..  when we checked both are unsubscribed automatically after done the completion..

Not sure whether need to do explicit unsubscribe

Can u advice pls

**Comment by vovikdrg** [comment]
@mob1  personally i ended up using [small extension](http://www.bilyachat.com/2017/04/angular-automatically-unsubscribe-from.html) :)

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
