### ISSUE TITLE
Async select field (new syntax)

### ISSUE THREAD

**Issue by altschuler** [angular/angular#18919]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

It's currently not possible to easily select a property of an async object in a template without either
1) Declaring it as a variable in an `ngIf` or using `as`
2) Using the `async` pipe and existential operator, ie `(thing$ | async)?.prop`

## Expected behavior / motivation

It would be very convenient with a new syntax to select properties directly off an observable. In the vein of typescript's existential operator, eg:

Instead of 
```
<h1>{{ (hero$ | async)?.name }}</h1>
<p>{{ (hero$ | async)?.description }}</p>

// Alternatives exist, eg
<ng-template [ngIf]="hero$ | async" let-hero>
  <h1>{{ hero.name}}</h1>
  <p>{{ hero.description}}</p1
</ng-template>
```

It would be nice with

```
<h1>{{ hero$|.name }}</h1>
<p>{{ hero$|.description }}</p>
```

Meaning `obj|.prop` is practically syntax sugar for `(obj | async)?.prop`.

**Comment by Toxicable** [comment]
`|` already has a meaning in an Angular template, it's a pipe
Meaning that your proposed syntax already currently means something to Angular

That aside I don't like the syntax since it blurs the lines between normal objects and Observables where this should be distinct and not ambiguous

**Comment by altschuler** [comment]
`|.` is currently invalid syntax, so it wouldn't conflict with existing syntax. `?` also has a meaning, but `?.` has another. The actual characters were just a suggestion, it could be something else.

I can see your point about it being ambiguous though, you're right it blurs the meaning of what the object is. Would it help if for non-observable objects the property would just be selected as a regular field (`obj.prop`)?

Another approach is simply using a pipe which is async and selects a field. Could be properly typed with typescripts `keyof`. This starts to feel more like something one should implement locally though, and looses the purpose of being short and concise. Eg. `obj | select:'name'`.

**Comment by trotyl** [comment]
How could a syntax bound to a library? `NgIf` is just a normal directive with no special meaning to Angular, it does not even exist in `@angular/core`.

**Comment by pkozlowski-opensource** [comment]
This sounds very similar to the issue #15280 where there is a lot of discussion about pulling out certain property value from an observable. At the end of a day we might not implement the syntax proposed here but the use-case is real.

**Comment by petebacondarwin** [comment]
This is being tracked in the aggregate issue of #43485 for which we need to create a project proposal.
