### ISSUE TITLE
deepest outlet path as string with nested outlets path is parsed as multiple child routes

### ISSUE THREAD

**Issue by Serrulien** [angular/angular#18928]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
```
const routes: Routes = [
  {
    path: 'primary-app',
    component: NestedPrimaryComponent, // contains 1 primary router-outlet (RO) and 1 named RO 'primary-nested' 
    children: [
      {
        path: 'primary-nested',
        component: AnotherComponent
      },
      {
        path: 'primary-nested',
        component: AnotherComponent,
        outlet: 'primary-nested'
      }  
    ]
  },
  {
    path: 'aux-app',
    outlet: 'aux-app',
    component: NestedAuxComponent, // contains 1 primary RO and 1 named RO 'aux-nested'
    children: [
      {
        path: 'primary-nested',
        component: AnotherComponent
      },
      {
        path: 'aux-nested',
        component: AnotherComponent,
        outlet: 'aux-nested'
      }  
    ]
  }
];
```

From `AppComponent's template`: 
- `<a [routerLink]="['/', { outlets: { 'primary': ['primary-app', { outlets: {'primary': 'primary-nested' } } ] } } ]">` navigates to `/primary-app/(p/r/i/m/a/r/y/-/n/e/s/t/e/d)`.

-  `<a [routerLink]="['/', { outlets: { 'primary': ['primary-app', { outlets: {'primary': ['primary-nested'] } } ] } } ]">` navigates to `/primary-app/primary-nested`.

_(3 examples in the plunk, and not only with 'primary' outlets)_

## Expected behavior
Both routerLink directives' command should reach `/primary-app/primary-nested`.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/o0DFop?p=preview

This plunker illustrates this issue with 4 routes (primary RO under aux RO, primary under primary, aux under primary and aux under aux).

In the `Navigations below are absolute` section, you may reproduce that by clicking on the `<a>` tags highlighted by ☝️  emoji.

## What is the motivation / use case for changing the behavior?
The behavior should be the same with and without nested outlets in path as
`[routerLink]="['/', { outlets: { 'primary': 'primary-app' } } ]"` doesn't routes to `/p/r/i/m/a/r/y/-/a/p/p/`:

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [X] Chrome (desktop) version 60.0.3112.113
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 55.0.3
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by Hypenate** [comment]
The Plunker example isn't working.
I have come across the same issue on [Stackoverflow](https://stackoverflow.com/questions/52257514/how-to-navigate-two-outlets-deep).

**Comment by avangel** [comment]
Same issue on my side. The simplest workaround is to manually generate the URL string.

**Comment by avangel** [comment]
Same issue here. To highlight the workaround provided in the issue description, the simple solution is to enclose the deepest outlet values into square brackets `[]`.

As a side note, the official documentation example is enclosing values into square brackets: 
```<a [routerLink]="[{ outlets: { popup: ['compose'] } }]">Contact</a>```
From https://angular.io/guide/router#add-a-secondary-route

**Comment by avangel** [comment]
In the end, I'm not even sure this should be considered a bug: each named outlet destination is a set of commands as well, as for the main navigation API. This seems recursively consistent and allows "outlet branches" at any level in the hierarchy.
