### ISSUE TITLE
Animations with prefixes broken in angular 5.0.0-beta4

### ISSUE THREAD

**Issue by Delagen** [angular/angular#18921]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The provided animation property "-webkit-transform" is not a supported CSS property for animations

## Expected behavior
Works in beta 3

## Minimal reproduction of the problem with instructions
any animation with vendor prefix in different browser (-webkit-transform ...)
-ms in Webkit
-webkit in IE

## Environment

<pre><code>
Angular version: 5.0.0-beta.4

Browser: all
For Tooling issues:
- Node version: 8.4.0
- Platform:  Windows 10 Pro x64

**Comment by Delagen** [comment]
@matsko any comment on how implement animations with support vendor prefixes

**Comment by Delagen** [comment]
Does not work on Safari

**Comment by emilio-martinez** [comment]
This issue is perhaps not isolated to webkit contexts. See https://github.com/angular/angular/issues/20415#issuecomment-348934311 where I'm getting the same but for `transform` without a prefix.

**Comment by matsko** [comment]
It goes both ways (with webkitTransform and when the webkit prefix is missing).

**Comment by matsko** [comment]
This PR handles it: https://github.com/angular/angular/pull/19055
