### ISSUE TITLE
Issue a warning when `display` styles are used in an animation transition

### ISSUE THREAD

**Issue by matsko** [angular/angular#18936]
So it turns out that `display` values are non-animatable properties with respect to web-animations. This means that when `element.animate` is used then all `display` animation styles are not applied at all during the animation life-cycle.

Here is an issue that was posted to the web-animations spec.
https://github.com/w3c/web-animations/issues/195

For Angular to work in harmony with this limitation, two things need to be done here:

1) Issue a warning if a transition sequence makes use of `display` anywhere within style() function calls. The only exception here is if `display` is used in a style that happens on the first frame of the animation.

2) If a `state()` contains display (which is supported) then the styles should be applied immediately when the animation has finished (even if a parent animation is ongoing). This logic should be apart of the WebAnimationsPlayer.

**Comment by dylhunn** [comment]
We have made some improvements here recently.
