### ISSUE TITLE
empty routerLink in ngFor sets the href to <url>/null

### ISSUE THREAD

**Issue by CodingContraption** [angular/angular#18931]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
```
<a *ngFor="let item in items" [routerLink]="" >link</a>
``` 
This code will result in correct routering (staying on the current page), but the href will be set to `http://localhost:4200/null`.

## Expected behavior

I expected the href to show the currently active url, e.g. `http://localhost:4200/some/url`. This behaviour is standard when `[routerLink]=""` is used outside of a loop.

## Minimal reproduction of the problem with instructions

add these 2 lines to a angular app with routerLink:
```
<a *ngFor="let item in items" [routerLink]="" >Link1</a>
<a [routerLink]="" >Link</a>
```

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [X] Chrome (desktop) version 60.0.3112.101
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version 10.1.2 (12603.3.8)
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
Please check this against a current version of Angular and if it continues, submit a new issue. 
If submitting a new issue, please provide a reproduction using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).
