### ISSUE TITLE
Get datas from a parent route element.

### ISSUE THREAD

**Issue by stephanecot** [angular/angular#18930]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior
I have a route, like /parent/1 associated with a component Parent. In this component Parent, I load an object with a Http request using the '1' in the path (and I have a parent.html).
In this parent.html, I have a <router-outlet> tag which is filled when I called the uri /parent/1/child. This child url is associated with the component Child.

My need is simple, I need to get the previously Parent component and, mainly, the data object instancied from the 1 in path.... 
Currently, I get the parent path, I get the path param '1' and I a re-execute the http request to get the same object.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by stephanecot** [comment]
I totally understand your remark, but for me it was a feature request because I didn't find any thing native to communicate between a route component and an sub route component like a @Parent() in the constructor not a stackoverflow hardcoding solution :(

**Comment by jasonaden** [comment]
Closing as support request.
