### ISSUE TITLE
Unresolved dependencies causes the language service to generate odd errors.

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#18937]
## I'm submitting a...
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

When a peer dependency is missing (such as `@angular/cdk`, the language service will sometimes report "Cannot read property 'skipSelf' of null".

## Expected behavior

The error should be reported to explain that the dependency could not be resolve or it should be ignored.

## Minimal reproduction of the problem with instructions

1. Using http://mean.io's cli create the default application: `mean init myApp`.
2. Open `myApp` in VS Code
3. Open `edit-post.component.html`

**Comment by kyliau** [comment]
This has already been fixed some time ago.
