### ISSUE TITLE
When button is submitted give a submitted value on reactive form group to true

### ISSUE THREAD

**Issue by ylligashi** [angular/angular#18934]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I submit the form I do now know if the button is submitted. So this event gives no response.

## Expected behavior

When a button is submitted give a value of submitted: true to a Fromgroup so I can not that the button has already been clicked.

## What is the motivation / use case for changing the behavior?

I do not want to disable the button when a form is invalid, but when a form is submitted I want to show them a message for required fields

## Environment

<pre><code>
Angular version: 4.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
If I understand correctly, what you're looking for is a way to tell if a reactive form has been submitted. You can already achieve this using the `submitted` property on `FormGroupDirective` (see docs [here](https://angular.io/api/forms/FormGroupDirective)). Closing, as this already exists.
