### ISSUE TITLE
Angular2 - DI -> toAsyncFactory example seems to be incorrect (probably a typo)

### ISSUE THREAD

**Issue by anwarhusain** [angular/angular#1894]
Hello team,

In line 6 of the toAsyncFactory example in https://angular.io/docs/js/latest/api/di/Binding-class.html, (as I understand it) the dependency type name should be "Number" and not "String" , or did I get it wrong?

Thanks
Anwar

**Comment by vicb** [comment]
you're right, just submitted a PR. Thanks for the report.
