### ISSUE TITLE
Routing and Navigation Documentiation

### ISSUE THREAD

**Issue by landonwaldner** [angular/angular#18944]
## I'm submitting a...
[ ] Documentation issue or request

In the documentation in the Routing and Navigation page under Milestone 3 under the ActivatedRoute: the one-stop-shop for route information heading, there is a code snippet that calls a getHero function from the getHero service, as shown below: 
`
ngOnInit() {
  this.route.paramMap
    .switchMap((params: ParamMap) =>
      this.service.getHero(params.get('id')))
    .subscribe((hero: Hero) => this.hero = hero);
}
`

The problem is that there is no getHero function that takes a parameter in the getHeroService, as shown below:

`import { Injectable } from '@angular/core';

import { Hero } from './hero';
import { HEROES } from './mock-heroes';

@Injectable()
export class HeroService {
  getHeroes(): Promise<Hero[]> {
    return Promise.resolve(HEROES);
  }

  // See the "Take it slow" appendix
  getHeroesSlowly(): Promise<Hero[]> {
    return new Promise(resolve => {
      // Simulate server latency with 2 second delay
      setTimeout(() => resolve(this.getHeroes()), 2000);
    });
  }
}`

I appreciate the amazing tutorial but can this getHero function be defined so that I can piece together how the above code works. Thanks

**Comment by aravindfz** [comment]
can you share the link of the doc and which version are you refering to?

**Comment by landonwaldner** [comment]
https://angular.io/guide/router#activatedroute-the-one-stop-shop-for-route-information

**Comment by brandonroberts** [comment]
@landonwaldner that code snippet you posted is from the `Services` tutorial. The `getHero` function is defined in the routing tutorial https://angular.io/tutorial/toh-pt5#add-heroservicegethero

**Comment by landonwaldner** [comment]
@brandonroberts I am not referring to the HEROES tutorial (not the services section nor the routing section). I am talking about the Routing and Navigation MILESTONES section that reuses and refactors the code used in the heroes tutorial, including the heroes service. However, there are no instructions to refactor the service to return an observable instead of a promise as the calling code requires.

Since the time that I posted (10 days ago), your documentation commit went through (3 days ago, Sept 5) and the subscribe operator was removed from the above snippet, and other things were changed. Even the heading "ActivatedRoute: the one-stop-shop for route information" isn't there any more. lol At this point, I don't know what to tell you.

**Comment by brandonroberts** [comment]
Yes, the guide has been reworked some. The ActivatedRoute information is still there https://angular.io/guide/router#activated-route

For your example, if you wanted to use a `getHero` function, you'd just add it to the service. The `switchMap` operator will handle it regardless of whether its an observable or promise

```ts
import { Injectable } from '@angular/core';

import { Hero } from './hero';
import { HEROES } from './mock-heroes';

@Injectable()
export class HeroService {
  getHeroes(): Promise<Hero[]> {
    return Promise.resolve(HEROES);
  }

  getHero(id: number): Promise<Hero> {
    return this.getHeroes()
               .then(heroes => heroes.find(hero => hero.id === id));
  }

  // See the "Take it slow" appendix
  getHeroesSlowly(): Promise<Hero[]> {
    return new Promise(resolve => {
      // Simulate server latency with 2 second delay
      setTimeout(() => resolve(this.getHeroes()), 2000);
    });
  }
}
```

**Comment by brandonroberts** [comment]
Closing as resolved. If this is still relevant, please open a new issue.
