### ISSUE TITLE
Nested p Tag inner component html

### ISSUE THREAD

**Issue by sozdemir06** [angular/angular#18940]
if type nested p tag inner any html component 
it is cause template parse error unexpected closing p tag error
I hope fixed next release

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
