### ISSUE TITLE
module.js:491     throw err; how to resolve the issue

### ISSUE THREAD

**Issue by sanjeevmalapati** [angular/angular#18947]
i am using node version 8.4 and npm version is 5.0.3 .
when i installed angular cli in command throw the error

module.js:491   throw err; how to resolve the issue

![node _error](https://user-images.githubusercontent.com/26994009/29857651-4fcebe08-8d77-11e7-905d-bce6ce6b912d.PNG)

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

PS: This is not angular-cli's repo 👍
