### ISSUE TITLE
Microsyntax observable resolve for ngFor

### ISSUE THREAD

**Issue by codefactorydevelopment** [angular/angular#18945]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

At the moment we can resolve observable to variable like:

`*ngIf="foo | async as bar"`

but if we have `*ngFor="let bar of foo.bars"` (foo is async observable) we have to put *ngIf in front of it or have null checks.

## Expected behavior

`*ngFor="let bar of (foo | async as fooResolved) as fooresolved.bars"`

## What is the motivation / use case for changing the behavior?

Split nullchecks from observables resolution.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
I don't think that adding more syntax will help with this.
I personally think you proposed syntax is more complicated and confusing than the current approach.

**Comment by codefactorydevelopment** [comment]
I agree with you that syntax proposed might not be optimal. My motivation here is not to enforce any particular syntax but to conceptually split something that doesnt belong together. Namely, null checks and observables resolving.

Hope it makes sense.

**Comment by codefactorydevelopment** [comment]
i have just noticed, proposed syntax has double `as` where it should be:

`*ngFor="let bar of (foo | async as fooResolved) from fooresolved.bars"`

**Comment by dylhunn** [comment]
I think you can use optional navigation:
```
(foo | async)?.bars
```

Feel free to open a new issue if this doesn't solve your problem.
