### ISSUE TITLE
IE 10 throw unable to get property 'addEventListener' of undefined or null reference

### ISSUE THREAD

**Issue by pavinthan** [angular/angular#18943]
I'm submitting a ...

bug report
Unable to get property 'addEventListener' of undefined or null reference

ag-grid-angular version: 12.0.0
Angular version: 4.3.6
Browser: [ IE 10 ]
Language: [all | TypeScript X.X | ES6/7 | ES5]

[Screenshot](https://ibb.co/nqj4XQ)

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
