### ISSUE TITLE
Support for string interpolation in custom component urlStyles with Webpack

### ISSUE THREAD

**Issue by jbprat** [angular/angular#18953]
## I'm submitting a...

<pre><code>
[X ] Feature request
</code></pre>

## Current behavior

Creating a custom component with a urlStyles array is generating [only support strings](https://angular.io/api/core/Component).
In my project, I would need to be able to interpolate value in a string, which works.
Also, I know that the Angular guidelines about theming advise to create a use classes, but in my case, I may have 50 brands, so loading all the brands style as other url is not acceptable.
```
const brand = 'brand_1';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [`../../theming/${brand}/style.scss`]
})
```

Since this interpolation works, I still have an issue with the way Angular request everything that is in StyleUrls, it basically do it: ```require('../../theming/' + brand + '/style.scss')```.  

Webpack interprets the brand variable as a wildcard,[ following their design](https://webpack.js.org/guides/dependency-management/#require-with-expression) and all the siblings folder are included in the bundle.

## Expected behavior
The new behavior for requesting the content url in stylesUrl should generate the interpolated string before requiring it, avoiding the bundling of all the siblings folders.

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [ x] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX
 
For Tooling issues:
- Node version: 7.10  
- Platform:  Windows 

Others:

</code></pre>

**Comment by Toxicable** [comment]
A path like that is not statically analyzable and therefore not AOT compliant

**Comment by jbprat** [comment]
@Toxicable would there be a way to create a new feature while still keeping the component AOT compliant? 
I understand the way to theme in Angular uses classes more than anything, but it would be nice to be able to have the option to have dynamic value as urlStyles or anywhere else in the angular app.

**Comment by jbprat** [comment]
@mhevery @alexeagle, could I have your opinion on it? I would do the development for such a feature myself and do a pull request !

**Comment by mhevery** [comment]
> A path like that would not be statically analyzable and therefore not AOT compliant

What @Toxicable said.

This would go against a lot of AOT work which we have planned. Sorry, but we are not going to support this.

**Comment by dealflo-christopher-prevoe** [comment]
@Toxicable @mhevery Thanks for your time. 

What about if this was done using some form of AOT variable, resolved during/before AOT, kind of like simple macros in C? This would allow static analysis and still provide the needed variability at build-time.
