### ISSUE TITLE
Getting error while loading UMD module which imports highcharts (“Highcharts JS v5.0.14”) from main module (angular4)

### ISSUE THREAD

**Issue by ijprasath** [angular/angular#18951]
Getting error while loading UMD module which imports highcharts (“Highcharts JS v5.0.14”) from main module (angular4).
[test.zip](https://github.com/angular/angular/files/1263440/test.zip)
Please find the attached sample application code with issue. The application details,
1.	Created the “amat-apf-analytics” UMD module (“amat-apf-analytics.umd.js”) to be utilized across different application. 
“/test/src” folder module will be converted as a single “amat-apf-analytics.umd.js” bundle by using gulp (“test/gulpfile.js” – gulp configuration file).
This “amat-apf-analytics.umd.js” is imported highcharts into it. Highcharts is included as external module in “gulpfile.js” since it is external to the amat-apf-analytics UMD bundle.
2.	Highcharts is configured in “system.config.js”. It will get loaded before loading amat-apf-analytics module.
3.	Main application is located in /test/APF folder and it will load highcharts and amat-apf-analytics from “/test/APF node_modules/”.
4.	While loading getting the below error,
index.html:18 Error: (SystemJS) Cannot read property 'core' of undefined
	TypeError: Cannot read property 'core' of undefined
	    at eval (http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/node_modules/amat-apf-analytics/amat-apf-analytics.umd.js:4:56)
	    at eval (http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/node_modules/amat-apf-analytics/amat-apf-analytics.umd.js:5:2)
	    at eval (<anonymous>)
	    at Object.eval (http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/app/app.module.js:12:28)
	Evaluating http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/node_modules/amat-apf-analytics/amat-apf-analytics.umd.js
	Evaluating http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/app/app.module.js
	Evaluating http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/app/main.js
	Error loading http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/app/main.js
	    at eval (http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/node_modules/amat-apf-analytics/amat-apf-analytics.umd.js:4:56)
	    at eval (http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/node_modules/amat-apf-analytics/amat-apf-analytics.umd.js:5:2)
	    at eval (<anonymous>)
	    at Object.eval (http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/app/app.module.js:12:28)
	Evaluating http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/node_modules/amat-apf-analytics/amat-apf-analytics.umd.js
	Evaluating http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/app/app.module.js
	Evaluating http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/app/main.js
	Error loading http://3nzxfc2.amat.com:20090/apfhome/lib/web/APFAnalytics/app/main.js

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
