### ISSUE TITLE
Angular is complaining about dataUrl with SVG image to be unsafe

### ISSUE THREAD

**Issue by kubal5003** [angular/angular#18950]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using `<img src="{{item.image}}" alt=""/>`and the item.image is set to `dataUrl` containing a valid SVG image Angular is complaining with the following:

`WARNING: sanitizing unsafe URL value data:image(...)`
and then the image won't load:

`GET unsafe:data:image/svg+xml;(...)  with error: net::ERR_UNKNOWN_URL_SCHEME`

## Expected behavior
I would expect Angular to be smart enough to understand data urls & either not sanitize them or do it in a better way. This was perfectly fine simple SVG mock image and still .I need to battle to make it work.

## Minimal reproduction of the problem with instructions

1.  Create a component with property imageUrl. 
2.  Set the value to: `data:image/svg+xml;charset=utf-8;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIj4NCjxjaXJjbGUgY3g9IjI1MCIgY3k9IjI1MCIgcj0iMjEwIiBmaWxsPSIjZmZmIiBzdHJva2U9IiMwMDAiIHN0cm9rZS13aWR0aD0iOCIvPg0KPC9zdmc+`
3.  In your template insert: `<img src="{{imageUrl}}" alt=""/>`

## What is the motivation / use case for changing the behavior?
Make the Angular DomSanitizer more intelligent, so that it doesn't yield false positives.

## Environment
<pre><code>
Angular version: 4.3.0

Browser: (this is not browser specific issue)
 
For Tooling issues: (this is not tooling issue)

Others: (the issue is about Angular behavior that is not setup specific)
</code></pre>

**Comment by ericmartinezr** [comment]
https://angular.io/guide/security#bypass-security-apis

**Comment by kubal5003** [comment]
Thanks for the workaround, but I've already done that and it's working. I still feel that this behavior is not really what it's supposed to be.

**Comment by MurhafSousli** [comment]
Any update on this?

**Comment by chris13524** [comment]
Similar issue here, but it's just prepending `unsafe:` to the URL rather than making the warning. I'm on Angular v5.0.2.

**Comment by DnyaneshwarShivbhakta** [comment]
Any solution to this. I am getting the same issue.

**Comment by rjalvesp** [comment]
> Any solution to this. I am getting the same issue.

Try using DomSanitizer. Quick example here:


`import { DomSanitizer } from '@angular/platform-browser';`

`
srcData: string = '';
constructor(
    private sanitizer: DomSanitizer
  ) { }
`

`this.srcData = this.sanitizer.bypassSecurityTrustResourceUrl(/* your base64 string in here*/);`

**Comment by johnho70** [comment]
I has same problem. I try above code still not working.
<img src="data:image/svg+xml;base64,{{srcData}}">
Is this example work for angular 6

**Comment by sedrak1987** [comment]
thx a lot

**Comment by ctomczyk** [comment]
Following regex in Angular (7.1.4):

<pre><code>var DATA_URL_PATTERN = /^data:(?:image\/(?:bmp|gif|jpeg|jpg|png|tiff|webp)|video\/(?:mpeg|mp4|ogg|webm)|audio\/(?:mp3|oga|ogg|opus));base64,[a-z0-9+\/]+=*$/i;</code></pre>

has definitely missing <code>image/svg+xml</code> mime type.

**Comment by snebjorn** [comment]
I run into this exact problem. But with the **pjpeg** type. `data:image/pjpeg;base64,...`

> GET unsafe:data:image/pjpeg;base64,... net::ERR_UNKNOWN_URL_SCHEME

**Comment by nezed** [comment]
@andersk [this vector](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#You_can_EMBED_SVG_which_can_contain_your_XSS_vector) may be implemented only though `<embed>` or maybe `<object>` tags.
So even following is safe to place inside `<img src=`:
```html
<svg><script xlink:href=data&colon;,window.open('https://www.google.com/')></script>
```

**Comment by Vandivier** [comment]
Related: https://github.com/angular/angular/issues/36650

**Comment by byronigoe** [comment]
FYI, embedding the SVG dataUrl within another SVG element like: `<svg ...><image [attr.xlink:href]="dataUrl" /></svg>` does not produce the warning or cause "unsafe:" to be prefixed.

**Comment by jelbourn** [comment]
This should be obsolete now that https://github.com/angular/angular/pull/45860 removed `data:` url schema checking
