### ISSUE TITLE
aio: Clarify docs on use of entryComponent

### ISSUE THREAD

**Issue by DeborahK** [angular/angular#18957]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Current doc text:
"Most application components are loaded declaratively. Angular uses the component's selector to locate the element in the template. It then creates the HTML representation of the component and inserts it into the DOM at the selected element. These aren't entry components."

## Expected behavior

Recommend changing the first sentence to simply say: "Application components can be loaded declaratively".

## Minimal reproduction of the problem with instructions

Link to the doc section is here: 
https://angular.io/guide/ngmodule-faq#what-is-an-entry-component

## What is the motivation / use case for changing the behavior?

I disagree that "most application components are loaded declaratively". This implies that *most* application components are used as nested (child) components. In many applications, the majority of the components maybe be routed instead.

Stating that "most" components are nested (child) components assumes a composition-based application architecture that many devs may not be using.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kapunahelewong** [comment]
Hi @DeborahK!! Since there's now a new doc just on entry components, would you mind if I closed this?

**Comment by DeborahK** [comment]
Yes. Thanks!
