### ISSUE TITLE
Option element value attribute not binding correctly

### ISSUE THREAD

**Issue by jongunter** [angular/angular#18958]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
1. Create a component with the following HTML:
```
<select [ngModel]="hello" (ngModelChange)="hello = $event">
  <option [value]="1">one</option>
  <option [value]="2">two</option>
  <option [value]="3">three</option>
  <option [value]="true">true</option>
</select>
<pre>
  {{ hello | json }}
</pre>
```
3. Select "two".
4. The variable `hello` is now string `"2"` rather than the number `2`.
5. Select "YES"
6. The variable `hello` is now string `"true"` rather than the boolean `true`.

## Expected behavior
Using the attribute `[value]` with brackets should parse that value as the proper type, not keep it as a string.

## Minimal reproduction of the problem with instructions
See example above.

## What is the motivation / use case for changing the behavior?
This works properly with the `ng-value` directive an AngularJS. I'm expecting the behavior to be the same in Angular.

## Environment
<pre><code>
Angular version: 4.3.6

Browser:
- [x ] Chrome (desktop) version 60.0.3112.101
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by jongunter** [comment]
Of course, I resolved the problem after 2 hours of pulling my hair out, and then typing up this issue. I guess I have to use `[ngValue]` instead or [value]. See the docs here: https://angular.io/api/forms/SelectControlValueAccessor

I found the solution a little too buried in the docs and I'm wondering if others had the same problem finding it.  I tried searching for `ngValue` in the docs and `SelectControlValueAccessor` came up, which I didn't immediately think to check. Maybe create an `ngValue` page that aliases the specific content?  It would make things less confusing for us coming from AngularJS. Or even add this to the "cheat sheet" on the docs.

**Comment by kara** [comment]
@jongunter Glad you were able to track down the problem.

Regarding the docs, the `SelectControlValueAccessor` page is probably the best we can do at this time because API doc pages are based on exported symbols. As there isn't one for `ngValue` (being an input property of the value accessor), we can't create its own page without creating a special guide.  I think that it's sufficient that the correct page comes up when searching "NgValue".  That said, if you think more information could be added to that page, please feel free to submit a PR.

**Comment by jongunter** [comment]
Ok, understandable. Can you at least add it to the upgrade cheat sheet or something? https://angular.io/guide/ajs-quick-reference
