### ISSUE TITLE
Deploying angular 4 app with in subdirectory

### ISSUE THREAD

**Issue by skesani** [angular/angular#18954]
I need a quick help from you, currently my angular 4 app works fine.

for example when i hit url http://localhost:4200 app loads and works everything fine.

my question is i wanted to load my app from the url lets say http://localhost:4200/angular

Could you please let me know how do it ?

I've tried 
ng build --bh/angular/ 

and take that dist and deployed in apache tomcat it is giving me lot of 404 errors.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
