### ISSUE TITLE
Typing error in documentation about Angular Metadata

### ISSUE THREAD

**Issue by GaelGirodon** [angular/angular#18964]
## I'm submitting a...
<pre><code>
[x] Documentation issue or request
</code></pre>

## Current behavior
There's a typing error in the first example of this documentation https://angular.io/guide/metadata about Angular Metadata (3rd line: `div>` and missing closing `'`).
```typescript
@Component({
  selector: 'app-typical',
  template: 'div>A typical component for {{data.name}}</div>
)}
export class TypicalComponent {
  @Input() data: TypicalData;
  constructor(private someService: SomeService) { ... }
}
```

## Expected behavior
Logically, the example should be written as follow (unless I missed something):
```typescript
@Component({
  selector: 'app-typical',
  template: '<div>A typical component for {{data.name}}</div>'
)}
export class TypicalComponent {
  @Input() data: TypicalData;
  constructor(private someService: SomeService) { ... }
}
```

## Minimal reproduction of the problem with instructions
* Go to the documentation (https://angular.io/guide/metadata) and look at the first example

## What is the motivation / use case for changing the behavior?
* The example seems to have a typing error

## Environment
<pre><code>
Angular version: 4.3.6
</code></pre>

**Comment by ericmartinezr** [comment]
This PR fixing the issue https://github.com/angular/angular/pull/18730 was already merged. Not sure when it will be deployed.

**Comment by GaelGirodon** [comment]
Thanks for your reply (and sorry for the report of a problem already solved).
