### ISSUE TITLE
Angular binding object with array from component to view with ngModels

### ISSUE THREAD

**Issue by jechazelle** [angular/angular#18962]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I tried to bind my model (object with array) on my view, but I have a problem when I submit my form : I don't have an array, but many properties.

My Component :

    import { Component, OnInit } from '@angular/core'
    import { Question } from "../../models/question";

    @Component({
        selector   : 'cc-form',
        templateUrl: './cc-form.component.html'
    })    

    export class CcFormComponent implements OnInit {
    public question: Question;

    constructor() {
        this.question = new Question();
    }

    ngOnInit() {
        this.question.setModel({ question: 'test' }); // set title
        this.question.setAnswers(3); // generate an array with 3 objects
    }

    createQuestion(form) {
        console.log(form.value); // return many properties and not object with array
    }

    }

My Template :

    <form #form="ngForm" (ngSubmit)="createQuestion(form)">
        <div class="form-group row" *ngFor="let answer of question.answers; let i = index;">
            <div class="col-sm-12">
                <input type="text"
                       class="form-control"
                       id="answer-text-{{i}}"
                       [ngModel]="question.answers[i].text"
                       name="answer-text-{{i}}">
            </div>
        </div>
    </form>

When I submit my form, I have many properties, but not an array :

<img width="681" alt="incorrect" src="https://user-images.githubusercontent.com/6713790/29896657-1f3b1004-8dde-11e7-9946-3dee0dda2969.png">

## Expected behavior
When I submit my form, I would like to have my object with an array :

<img width="766" alt="correct" src="https://user-images.githubusercontent.com/6713790/29896568-cecec0de-8ddd-11e7-8f1f-b0313374839b.png">

I tried many things from differents posts, but always many properties and no array.

Demo : https://angular-by7uv1.stackblitz.io/

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [X] Chrome (desktop) version 60.0.3112.113 (Build officiel) (64 bits)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.0
- Platform:  Mac

Others: /

</code></pre>

**Comment by kara** [comment]
This is expected behavior for `ngModel`. It registers itself to the parent form using the name attribute supplied.  It sounds like what you need in your form is a `FormArray`, but this is currently only available in reactive forms (see documentation [here](https://angular.io/api/forms/FormArrayName)).  You can either switch to reactive forms or track the 
 [existing issue](https://github.com/angular/angular/issues/9615) for adding this functionality to template-driven forms.
