### ISSUE TITLE
$scope.msg Appearing in Console, Not on DOM

### ISSUE THREAD

**Issue by realph** [angular/angular#1897]
I've ran into a bit of a problem, wherein I've created a `$scope.msg` and it's printing to my console just fine, but it won't render itself on the DOM. I'm using Browserify to require angular and bundle my js.

**index.html**

    <body ng-app="zeroApp" ng-controller="MainCtrl">
      <div class="container">
        <div class="item">
          <h1>{{ msg }}</h1>
        </div>
      </div>
    <script src="./js/app.js"></script>
    </body>

**app.js**

    (function() {
      'use strict';
      var angular = require('angular');
      angular.module('zeroApp', [])
      .controller('MainCtrl', ['$scope', function($scope) {
          $scope.msg = "Hello Angular!";
          console.log($scope.msg);
      }]);
    })();

Any reason why this isn't being exposed to the DOM and my `<h1>` element is empty?

Any help is appreciated. Thanks in advance!

**Comment by vicb** [comment]
This repo is for ng2, please re-open on https://github.com/angular/angular.js
