### ISSUE TITLE
[ngUpgrade] Concurrent $digest occurs when using the AngularJS ngClick directive to open an Angular 2+ route

### ISSUE THREAD

**Issue by chaowentan** [angular/angular#18979]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Our hybrid app uses both the AngularJS and Angular 2+ routers to handle different routes. And when we use the AngularJS ngClick directive to open an Angular 2+ route, concurrent $digest would occur because both the AngularJS ngClick and the Angular 2+ URL change handler (via ngUpgrade) would call `$apply`. Below is the stack trace:

```
errors.js:35 ERROR Error: [$rootScope:inprog] $digest already in progress

(anonymous) (angular.js:67)
beginPhase (angular.js:18557)
$digest (angular.js:17980)
(anonymous) (upgrade_module.ts:246)
schedulerFn (event_emitter.ts:101)
SafeSubscriber.__tryOrUnsub (Subscriber.ts:271)
SafeSubscriber.next (Subscriber.ts:221)
Subscriber._next (Subscriber.ts:152)
Subscriber.next (Subscriber.ts:112)
Subject.next (Subject.ts:78)
EventEmitter.emit (event_emitter.ts:78)
checkStable (ng_zone.ts:237)
onLeave (ng_zone.ts:309)
onInvokeTask (ng_zone.ts:261)
ZoneDelegate.invokeTask (zone.ts:1083)
Zone.runTask (zone.ts:785)
ZoneTask.invokeTask (zone.ts:1173)
invokeTask (events.ts:81)
globalZoneAwareCallback (events.ts:108)
Browser.self.url (angular.js:6400)
setBrowserUrlWithFallback (angular.js:14233)
(anonymous) (angular.js:14368)
$digest (angular.js:18004)
$apply (angular.js:18302)
(anonymous) (angular.js:25792)
dispatch (jquery2.min.js:40)
m.handle (jquery2.min.js:40)
ZoneDelegate.invokeTask (zone.ts:1086)
Zone.runTask (zone.ts:785)
ZoneTask.invokeTask (zone.ts:1173)
invokeTask (events.ts:81)
globalZoneAwareCallback (events.ts:101)
```

## Expected behavior

ngUpgrade should check `$root.$$phase` before calling `$digest`.

**Comment by gkalpak** [comment]
We've been trying to avoid checking `$root.$$phase`, because it often hides errors. Although several people have requested this, so far we haven't found a usecase where this is necessary (and not caused by a bug elsewhere).

Could you provide a **minimal** reproduction (e.g. in a plnkr or a public repo)?
(For plnkr, you can use [this][1] as template.)

[1]: http://plnkr.co/edit/BXA3Onj8CkbmfuDKXu1N?p=preview

**Comment by gkalpak** [comment]
Closing due to lack of reproduction.

**Comment by Matrosskin** [comment]
I have a case when the digest already started by zone.js so the second one digest (started by the scheduler) failed with "$digest already in progress" error.
@gkalpak could you please explain how checking of $root.$$phase can hide an error?

**Comment by gkalpak** [comment]
> @gkalpak could you please explain how checking of $root.$$phase can hide an error?

I mean if multiple `$digest`s are triggered simultaneously, it is often due to some misconfigutration or a programming error.

**Comment by Matrosskin** [comment]
Do you mean that the `$digest` should be called only in one place in the app? So if we use ngUpgrade then  no one other logic in our project should not call `$digest`? Otherwise, we need to spend a lot of energy to control who and under which circumstances call `$digest`. I believe it will be much better to add a little logic to make calling of `$digest` a little smarter - `$digest` is public method so everyone who use it should do it safely. Is not it possible to use something like `$applyAsync`?
I am so sorry if I wrote nonsense because I have not enough technical knowledge but I would like to understand the reasons of current implementation.

**Comment by gkalpak** [comment]
> Do you mean that the $digest should be called only in one place in the app? So if we use ngUpgrade then no one other logic in our project should not call $digest?

Not really. Generally, AngularJS takes care of calling `$digest()` for you, so there should be very few cases where you need to call it yourself (mainly when integrating 3rd-party, non-AngularJS services/widgets that you need to integrate into the `$digest` cycle).
So, if you get a `$digest` inside a `$digest` it is very likely that it is a programming error (i.e. you are calling `$digest` somewhere that you shouldn't).

If we find a legit usecase, where a `$digest` is triggered inside a `$digest` in `ngUpgrade`, then we would consider adding `$rootScope.$$phase` check, but we haven't found one yet.

**Comment by johnwest80** [comment]
So we are running into the same thing.  I have no idea how to reproduce it outside of our codebase, but I can consistently make it happen, and have a stack trace showing that a $digest cycle called another $digest cycle.  Does this stack trace at least provide a beginning that let's us have a further discussion?
![2018-06-05_15-27-50](https://user-images.githubusercontent.com/1585088/40998277-512b0394-68d5-11e8-8fd4-d27ea2d45703.jpeg)

**Comment by johnwest80** [comment]
@thelgevold Hey there, Tor!  By any chance have you ever seen this before at all?

**Comment by johnwest80** [comment]
The ng-click looks to be the impetus for this issue in my example.  It calls $scope.$apply.  Next, inside the ng-click we are navigating to a different route.  Somewhere after this in the call stack another $digest is called, which is where the failure occurs.
![2018-06-05_15-43-26](https://user-images.githubusercontent.com/1585088/40998981-80c440b4-68d7-11e8-84f6-eaaab351f735.jpeg)
![2018-06-05_15-43-58](https://user-images.githubusercontent.com/1585088/40998982-82a51fa2-68d7-11e8-8434-6fcfdbc24830.jpeg)

**Comment by gkalpak** [comment]
That seems unexpected. Can you verify that `setBrowserUrlWithFallback()` is called from inside the Angular zone (i.e. `NgZone.isInAngularZone()` is true)? Also, what line inside `browser.url()` is trigerring `invoke` in Zone.js?

**Comment by johnwest80** [comment]
Here is more information.  Let me know if this helps you get further.  I'm glad to go back and forth as much as necessary to try to get you more information.  
![2018-06-06_08-49-24](https://user-images.githubusercontent.com/1585088/41039394-4e1bd7c2-6967-11e8-9800-7fcca1943d03.jpeg)
![2018-06-06_08-47-19](https://user-images.githubusercontent.com/1585088/41039399-50a4a5fa-6967-11e8-9e5f-0ca6f2d4c002.jpeg)

**Comment by johnwest80** [comment]
can we open this again?

**Comment by gkalpak** [comment]
@johnwest80, can you put a breakpoint at `angular.js:25023` and check the value of `NgZone.isInAngularZone()`?
Also, are you using `UpgradeModule` or `downgradeModule()`?

**Comment by johnwest80** [comment]
Code at 25023 is not called when I click the button that throws the console error (see screenshot for confirmation).  

We are using UpgradeModule.

![2018-06-11_10-05-27](https://user-images.githubusercontent.com/1585088/41236473-3822df78-6d5f-11e8-9004-900038cea933.jpeg)

**Comment by johnwest80** [comment]
It *looks* to my untrained eye like angularjs is starting a $setTimeout, which is going to start a digest cycle.  Meanwhile, angular is wrapping the javascript setTimeout in a zone as well, and starting a digest cycle when it's complete.  The latter zone $digest ends up happening inside the angularjs digest, hence the error.

**Comment by gkalpak** [comment]
> Code at 25023 is not called when I click the button that throws the console error

Hm... your screenshots in https://github.com/angular/angular/issues/18979#issuecomment-395058168 show line 25023 in the call stack.

Line 25021 can only be called by `ngBlur`/`ngFocus`. Does your button click trigger any of those?
(E.g. an input is focused and clicking on the button triggers the input's `ngBlur` directive.)

##
<sub>BTW, the app is not publicly accessible, right?</sub>

**Comment by johnwest80** [comment]
So we have found a "solution", but I'm thinking our issue with with the hack we're doing when we bootstrap.  Below is our code for bootstrapping - we had to put the call in a setinterval so we could wait for some other initialization to finish.  This was probably where the bug was.  We wrapped the actual bootstrap call in ngZone.run and it worked.  

@gkalpak , would you say our problem makes sense in light of what we were doing, and does wrapping it in a zone.run call also make sense as a solution?

    let bootstrapAngularJS = (adapter: UpgradeModule) => {
      // Waits for versioned app url to be resolved (jquery promise from app-bootstrap.js)
      window.appBootstrapPromise.then(() => {
        return window.NativeApp.init();
      })
        .then(() => {
          adapter.bootstrap(document.body, ['redbox'], {
            strictDi: true
          });

          /*
           * Bootstrap order:
           * 1. Ng5 Module
           * 2. Angularjs app
           * 3. Ng5 App Shell component
           * Needed in this order so that our Ng5 App Shell has access to Angularjs
           * components / services we are upgrading. Inside of index.html we are using
           * appInitialized flag to hide the app-shell selector until Angularjs app
           * is bootstrapped. appInitialized flag gets set on rootscope by Angularjs
           * bootstrap process.
           */

          let checkExist = setInterval(() => {
            if ($('app').length) {
              clearInterval(checkExist);
              ngZone.run(() => { <!! ADDED THIS - WRAPPED THE bootstrap call in the zone and it fixed the problem!!
                appRef.bootstrap(AppComponent);
              });
            }
          }, 100);

        });
    };

**Comment by gkalpak** [comment]
It is not clear where `bootstrapAngularJS` is run from. Is it executed from outside the Angular zone?

**Comment by johnwest80** [comment]
Here is where it's executed.

```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app.module';

import { BootstrapService } from './bootstrap';

platformBrowserDynamic().bootstrapModule(AppModule).then((ref: any) => {
  BootstrapService.bootstrap(ref);
});
```

This in turn calls 

```
export class BootstrapService {

  static bootstrap(ref: any) {
    let appRef = ref.injector.get(ApplicationRef);

    let ngZone: NgZone = ref.injector.get(NgZone);

    let bootstrapAngularJS = (adapter: UpgradeModule) => {
          ... what's in the post above
```

**Comment by gkalpak** [comment]
Aha! So, the promise returned by `bootstrapModule()` is outside the Angular zone. That explains why you had to manually enter the zone.

It is not recommended to bootstrap outside the zone. (I know, I know, we got it wrong in the docs (sorry!), but #18487 has been merged yesterday and [we now recommend][1] bootstrapping in the Angular module's `ngDoBootstrap()` mehod (which runs inside the Angular zone).)

So, if you moved the bootstrapping logic inside `ngDoBootstrap()`, you shouldn't need `ngZone.run(...)` any more.

[1]: https://angular.io/api/upgrade/static/UpgradeModule#examples

**Comment by gkalpak** [comment]
Glad you figured it out 👍
Thx for reporting your findings; hopefully this will save someone some time some day :wink:

**Comment by Matrosskin** [comment]
@gkalpak sorry that I annoy you but I need someone who know subject better than I.
In the AngularJS still used $Q and it use `$rootScope.$evalAsync(callback)` to schedule next tick. Here https://github.com/angular/angular.js/blob/master/src/ng/rootScope.js#L1117 we can see that the $digest can be called independently from zonejs, am I right? So looks like it is possible to have situation when at first called $digest by $evalAsync and then inside of queue also called $digest by zonejs? Or it is not matter if all logic executed in the angular zone?

**Comment by gkalpak** [comment]
`$evalAsync()` uses `$browser.defer()`, which in turn uses `setTimeout()`. So, the Angular zone task queue will not be empty before the `$evalAsync()` callback (including the `$digest()` call) is completed.

**Comment by Matrosskin** [comment]
@gkalpak Thank you very much. From your answer I understand that in my case the real problem is in which zone called `$evalAsync()` so I checked where scheduled processing of queue with promises and I found that we add listener for click event on the body in the root zone, so that event triggers long chain of Zone tasks, digest and timers, and at the and we have "digest in progress" error. And it is no matter that the "click" event listener is not related to angular, it cause the problem just because the event triggers zone task in root zone... So moving of the code (where we add event listener) into angular zone solve the problem. @gkalpak could you please say if my thoughts on the right way? (I hope my description is enough understandable). But then it means that any event listener added in the root zone (possibly before angular started) can cause digest error, am I right?

**Comment by gkalpak** [comment]
Your thinking is (almost) correct (if I understand it correctly). Everything that is run outside of the Angular zone is not considered to be part of the Angular app. Since, in a hybrid app, AngularJS is supposed to run inside the Angular zone, having code that calls `$digest()` from outside the Angular zone is a problem.

(It is like having something outside the Angular app, call AngularJS, which is inside the Angular app. This usecase is not supported.)

**Comment by Matrosskin** [comment]
Then it means that the tasks created in root zone and tasks created in angular zone should be processed in different queues and never should be mixed, do I understand you properly? So processing of queue of root tasks can't affect processing of queue of angular tasks? I thought zonejs use one queue for all tasks and digest started even when click event registered in root zone.

**Comment by gkalpak** [comment]
I'm no expert myself, but my understanding is that each zone has its own task queue and `NgZone#onMicrotaskEmpty()` is triggered when the Angular zone drains its microtask queue. `$digest()` should only be triggered for microtasks scheduled in the Angular zone (not the root zone).
(@JiaLiPassion, is the Zone expert :smiley:)

**Comment by Matrosskin** [comment]
@gkalpak @JiaLiPassion sorry guys, If was my wrong assumption - that something goes wrong with queue. Now I checked a little more how processed tasks and now I know for sure that any event handler processed in same zone where it was created, even if for element assigned a few listeners from different zones.

Also, I found who cause using of incorrect zones - it is bluebird promises. Actually at the moment we are testing the patch for bluebird found in zone.js repository. We use bluebird only as module, the native Promise did not replaced, so we used a little modified patch. As digest error appeared only in a few cases and mostly in user browsers - we did not check from the beginning if bluebird is related to issue, but should have done it.

**Comment by Matrosskin** [comment]
@gkalpak @JiaLiPassion sorry guys, If was my wrong assumption - that something goes wrong with queue. Now I checked a little how processed tasks and know for sure that any event handler processed in same zone where it was created, even if on element assigned a few listeners from different zones.

Also, I found who cause using of incorrect zones - it is bluebird promises. Actually at the moment we are testing the patch for bluebird found in zone.js repository. We use bluebird only as module, the native Promise did not replaced, so we used a little modified patch. As digest error appeared only in a few cases and mostly in user browsers - we did not check from the beginning if bluebird is related to issue, but should have done it.

**Comment by icorne** [comment]
I'm running into this issue as well. I'm investingating to see if it's the same issue.

**Comment by mralbobo** [comment]
Would also be interested in these hacks to chase down execution escaping to the root zone. Currently wrestling with something similar sounding.

**Comment by icorne** [comment]
> @icorne if you able to reproduce constantly the issue but can't find where the root zone wrongly used instead of angular zone then I can share with you a few hacks which can potentially help you to find the correct place. (Actually it would be better to do anyway but I have not time at the moment to do it with enough info).

That would be great, do we continue to communicate via this thread or find other means?

**Comment by Matrosskin** [comment]
```
// PART 1.
// Patch 3 methods in zone.js.
// NOTE: The difference between methods only in arguments provided to constructor "new ZoneTask".
Zone.prototype.scheduleMicroTask = function (source, callback, data, customSchedule) {
    var newZoneTask = new ZoneTask(microTask, source, callback, data, customSchedule, null);
    
    // NOTE: In digest error we have stacktrase serted from point where task invoked.
    // We already know that it was started in wrong zone, otherwise there should not be any error.
    // So to understand why it is invoked in wrong zone we should know where the task was created.
    newZoneTask._hack_stacktrace = new Error('hack error').stack;

    // NOTE: Also, it is possible that the task was created by another task.
    // So it means that probably the problem caused by some parent task.
    // To track parent tasks I sstore them in additional property.
    // Also, as I interested only in not "angular" zones then I added this "if".
    var scheduledTask = this.scheduleTask(newZoneTask);
    if (scheduledTask.zone._name != 'angular' && Zone.currentTask) {
        newZoneTask._hack_currentTask = Zone.currentTask;
    }
    
    return scheduledTask;
};
Zone.prototype.scheduleMacroTask = function (source, callback, data, customSchedule, customCancel) {
    var newZoneTask = new ZoneTask(macroTask, source, callback, data, customSchedule, customCancel);

    // HERE SHOULD BE THE SAME CODE AS IN PREVIOUS METHOD.
};
Zone.prototype.scheduleEventTask = function (source, callback, data, customSchedule, customCancel) {
    var newZoneTask = new ZoneTask(eventTask, source, callback, data, customSchedule, customCancel);

    // HERE SHOULD BE THE SAME CODE AS IN PREVIOUS METHOD.
};
```
```
// PART 2.
// Owerride native Error.
var OriginError = window.Error;
window.Error = function(message) { // there also possible 2 more arguments but it is not important to solve digest error.
    var error = new OriginError(message);
    error._hack_currentTask = Zone.currentTask;
    return error;
};
```
```
// PART 3.
// Somewhere in error handler you just need to look on task stored in "error._hack_currentTask"
// and check values of "_hack_stacktrace" and "zone" (possibly you will need to check a few parent tasks).
// INFO: In my project I saw 10 parent tasks maximym so I assume that it should not be difficult
// to find which task was created in wrong zone, then stacktrace should help to understand why it happens.
```
