### ISSUE TITLE
How to check the data type of component properties?

### ISSUE THREAD

**Issue by Leonhelm** [angular/angular#18977]
"@angular/core": "^4.0.0"
"typescript": "~2.3.3"

`@Component({`
`  selector: 'app-parent',`
`  templateUrl: '<app-child [data]="test"></app-child>'`
`})`
`export class ParentComponent {`

`  test: number = 123;`
`}`

`/****/`

`class Test {`
`  name: string`
`}`

`@Component({`
`  selector: 'app-child',`
`  templateUrl: '<div></div>',`
`})`
`export class ChildComponent {`

`  @Input() data: Test;`
`}`

Why does ChildComponent not swear that the data property does not belong to the Test data type?
How can typescript or angular be able to check the incoming properties of a component?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Leonhelm** [comment]
Got it, thanks for the answer!
