### ISSUE TITLE
Location cannot be overridden

### ISSUE THREAD

**Issue by thepian** [angular/angular#18976]
# I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## Current behavior
Location marks the implementation as clearly internal, so the member variables are not in the `location.d.ts`

## Expected behavior
Location definition in `location.d.ts` should have enough information for it to be subclassed.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/ZASGNXoESyGDzEYUjY0a?p=catalogue
```typescript
@Injectable()
class MyLocation extends Location {
  
    // need to define this again, since it's not in the definition for Location
    _platformStrategy: LocationStrategy;

    constructor(platformStrategy: LocationStrategy) {
        super(platformStrategy);
        this._platformStrategy = platformStrategy;
    }
    
    pushState(path: string, query: string = '', restore: Restore = null): void {
        this._platformStrategy.pushState(restore || null, (restore && restore.title) || '', path, query);
    }
}
```

## What is the motivation / use case for changing the behavior?
I want to store state and title with the history.
The Location API is a dumbed down version of the History API without title and state. Since the Router and 3rd party code would be using Location for navigation, I have to provide my own implementation of Location. It isn't sufficient to provide a Strategy as Location doesn't pass additional parameters given to `.go()` and `.replaceState()`.

## Environment

<pre><code>
Angular version: 4.2.4

Browser:
n/a
 
For Tooling issues:
n/a

**Comment by petebacondarwin** [comment]
`Location.go()` and `Location.replaceState()` were updated to pass through the `state` object in https://github.com/angular/angular/commit/c40ae7f7cfb7f498bc142ae267911e07d73baf31 which was released in Angular v6.0.0. 

So in terms of this issue, there is no longer any need to subclass the `Location` class since the `LocationStrategy` will now receive the necessary values and overriding can be done there.
