### ISSUE TITLE
BehaviorSubject instead of Observable

### ISSUE THREAD

**Issue by piernik** [angular/angular#18974]
`ActivatedRoute's` `data` is type of `BehaviorSubject`. `BehaviorSubject` has property `value`. Thanks to it I can access data in simpler way
`const data = this.route.data.value`
instead of
```
const data; 
this.route.data.subscribe(resp=>data=resp);
```
But `data` is set as `Observable` type - not `BehaviorSubject`. It causes compilation errors.
Can You change `data` (and many other properties) type?

**Comment by dmitrysteblyuk** [comment]
I believe you can use ```this.route.snapshot.data```

**Comment by piernik** [comment]
@dmitrysteblyuk You're right - I'll use it.

**Comment by Toxicable** [comment]
Cab be closed?
This is working as expected
