### ISSUE TITLE
RouterLinkActive not setting class when using the address bar

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [angular/angular#18989]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am using a `routerLinkActive` to set a class along with `routerLink` on a button. If I go to the route using the button, the class is applied but if I go to the route through the address bar, the class is not applied.

## Expected behavior

The class in `routerLinkActive` should be applied even when using the address bar

## Minimal reproduction of the problem with instructions

The issue is present in the following file at the particular node of git https://github.com/SayakMukhopadhyay/elitebgs/blob/7e6da91ca51f4d98c8553c84a02f755b30caf10d/src/app/eddb_api/eddb-api.component.html
## What is the motivation / use case for changing the behavior?

To have a fully responsive nav bar

## Environment

<pre><code>
Angular version: 4.3.4

Browser:
- [X] Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 54
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by SayakMukhopadhyay** [comment]
I have done more testing and it seems that this problem is only happening on routes with associated component which has a `ngOnInit` method in it. Is it Issue #14227 ?

**Comment by wandri** [comment]
See my issue, that can be related.

https://github.com/angular/angular/issues/19167

You can try with the hack: [routerLinkActive]="" [ngClass]="rla.isActive?'active':''"  #rla="routerLinkActive"
