### ISSUE TITLE
ng-content can not call Lifecycle hooks

### ISSUE THREAD

**Issue by zhantewei2** [angular/angular#18982]
## Current behavior

My situation as below:
**container.component**:
```js
selector:'example-container',
template:`
 <button (click)='open=!open'>Toggle</button>
 <div *ngIf='open'>
   <ng-content> </ng-content>
 </div>
`
```
**parent.component**
```js

  <example-container>
     <example-child></example-child>
 </example-container>
```
**child.component**
```js
class ChildComponent{
  ngOnInit(){
     //....run once
  }
}
```
childComponent  `ngOnInit()` only be called once, no matter how you click on the `Toggle button`;
Sometimes I need to call them,like this:
```js
 sub:any;
 ngOnInit(){
   this.sub=myObservalbe.subscribe(()=>....);
 }
 ngOnDestroy(){
   this.sub.unsubscribe();
 }
```
But `ngOnDestroy` can not be called,when the `*ngIf=false`;
If I need to use other ways to implement it;
## Environment

<pre><code>
Angular version: 4.3.4

Browser:
- [ ] Chrome/60.0.3112.113

**Comment by Toxicable** [comment]
Here's a Stach Blitz to demo this behaviour
https://stackblitz.com/edit/angular-58yjed?file=app%2Fapp.component.ts

**Comment by robwormald** [comment]
*ngIf destroys the component (because it is removed from the DOM), so it is expected and intended behavior that it fires both the `ngOnInit` and `ngOnDestroy` lifecycle hooks.

**Comment by Toxicable** [comment]
@zhantewei2 As above I attempted to reproduce this but was unable to. Could you please provide a minimal reproduction of the issue?
You can use the Stack Blitz I provided above as a starting point

**Comment by zhantewei2** [comment]
@robwormald  It really has beed removed from the DOM..But `ngOnDestroy` can not be called

**Comment by zhantewei2** [comment]
@Toxicable  you can change `Container` like this:
```js
@Component({
  selector: 'container',
  template: `
  <button (click)='show=!show'>innerToggle</button>
  <div *ngIf='show'>
    <ng-content></ng-content>
  </div>
  `
```
click `innerToggle`  The console has no output

**Comment by mlc-mlapis** [comment]
@zhantewei2 ... once again ... `*ngIf` inserts and removes inner parts to and from DOM so why do you think that `ngOnInit` and `ngOnDestroy` should not be called?

**Comment by Toxicable** [comment]
Here's the reproduction of the issue
https://stackblitz.com/edit/angular-58yjed?file=app%2Fapp.component.ts
What I assume is going on here: Since you're only removing the ref to the content (ng-content) it dosen't actually destroy the projected content.
Not sure if this is the intended behaviour or not.

**Comment by Toxicable** [comment]
It is the expected behaviour, see here: https://github.com/angular/angular/issues/13059#issuecomment-264598276
Thanks @ghetolay for pointing that out

**Comment by zhantewei2** [comment]
Thanks @Toxicable , I think I  know how to do it.
