### ISSUE TITLE
Please remove ngzone shit in the upcoming update

### ISSUE THREAD

**Issue by moeidsaleem** [angular/angular#18984]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

please i beg you i know the fix around for ngzones but believe me this is why developers are moving to alternatives. 
Why the fuck would we be using such a stupid function that doesn't update ui after http.  And have to use a shit like ngzone.
I mean you did a great job with angular 4, angular 2 had much problems for developers but i want you to get rid of ngzone in the upcoming release.
I mean we know angular  focuses on enterprise development but you can make that optional ans let ui update itself after value change. 
I mean we need to focus on functionality rather than thinking about how will my view react to a change. 
I request team angular to listen to public and developers who have been working with angular for long time.  

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by steida** [comment]
Try https://github.com/zeit/next.js

**Comment by jotatoledo** [comment]
Please use the issue template

**Comment by robwormald** [comment]
We're already working on this. More importantly, read the [Code of Conduct](https://github.com/angular/code-of-conduct) before opening any more issues or commenting anywhere else. General nastiness will not be tolerated.
