### ISSUE TITLE
ng build -prod Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'

### ISSUE THREAD

**Issue by x3852** [angular/angular#18990]
Angualr-cli Version
@angular/cli: 1.3.2
node: 6.10.2
os: win32 x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6

Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\CodeWorkSpace\zuche.web.html\src'
resolve './$$_gendir/app/app.module.ngfactory' in 'D:\CodeWorkSpace\zuche.web.html\src'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\app.module.ngfactory.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\app.module.ngfactory doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\app.module.ngfactory]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\app.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\app.module.ngfactory.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\app.module.ngfactory]
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\home.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\home.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/home/home.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\home.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\home.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\home.module.ngfactory.ts.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\home.module.ngfactory.ts doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\home.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\home.module.ngfactory.ts.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\home.module.ngfactory.ts.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\home.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\agent.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\agent.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/home/pages/agent/agent.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\agent.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\agent.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\agent.module.ngfactory.ts.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\agent.module.ngfactory.ts doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\agent.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\agent.module.ngfactory.ts.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\agent.module.ngfactory.ts.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\agent.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\index\index.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\index\index.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/home/pages/agent/index/index.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\index\index.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\index\index.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\index\index.module.ngfactory.ts.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\index\index.module.ngfactory.ts doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\index\index.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\index\index.module.ngfactory.ts.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\index\index.module.ngfactory.ts.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\index\index.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\authentication\authentication.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\sr
c\$$_gendir'
resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\authentication\authentication.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/home/pages/agent/authentication/authentication.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\authentication\authentication.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\authentication\authentication.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\authentication\authentication.module.ngfactory.ts.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\authentication\authentication.module.ngfactory.ts doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\authentication\authentication.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\authentication\authentication.module.ngfactory.ts.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\authentication\authentication.module.ngfactory.ts.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\authentication\authentication.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\merchant\merchant.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'

resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\merchant\merchant.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/home/pages/agent/merchant/merchant.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\merchant\merchant.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\merchant\merchant.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\merchant\merchant.module.ngfactory.ts.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\merchant\merchant.module.ngfactory.ts doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\merchant\merchant.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\merchant\merchant.module.ngfactory.ts.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\merchant\merchant.module.ngfactory.ts.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\merchant\merchant.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\enchashment-apply\enchashment-apply.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.h
tml\src\$$_gendir'
resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\enchashment-apply\enchashment-apply.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/home/pages/agent/enchashment-apply/enchashment-apply.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\enchashment-apply\enchashment-apply.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\enchashment-apply\enchashment-apply.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\enchashment-apply\enchashment-apply.module.ngfactory.ts.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\enchashment-apply\enchashment-apply.module.ngfactory.ts doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\enchashment-apply\enchashment-apply.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\enchashment-apply\enchashment-apply.module.ngfactory.ts.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\enchashment-apply\enchashment-apply.module.ngfactory.ts.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\enchashment-apply\enchashment-apply.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\personal-info\personal-info.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\
$$_gendir'
resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\personal-info\personal-info.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/home/pages/agent/personal-info/personal-info.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\personal-info\personal-info.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\personal-info\personal-info.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\personal-info\personal-info.module.ngfactory.ts.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\personal-info\personal-info.module.ngfactory.ts doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\personal-info\personal-info.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\personal-info\personal-info.module.ngfactory.ts.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\personal-info\personal-info.module.ngfactory.ts.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\personal-info\personal-info.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\carlist\carlist.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\carlist\carlist.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/home/pages/agent/carlist/carlist.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\carlist\carlist.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\carlist\carlist.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\carlist\carlist.module.ngfactory.ts.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\carlist\carlist.module.ngfactory.ts doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\carlist\carlist.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\carlist\carlist.module.ngfactory.ts.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\carlist\carlist.module.ngfactory.ts.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\carlist\carlist.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\order\order.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\order\order.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/home/pages/agent/order/order.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\order\order.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\order\order.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\order\order.module.ngfactory.ts.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\order\order.module.ngfactory.ts doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\order\order.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\order\order.module.ngfactory.ts.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\order\order.module.ngfactory.ts.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\order\order.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir lazy
Module not found: Error: Can't resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\profit\profit.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
resolve 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\profit\profit.module.ngfactory.ts' in 'D:\CodeWorkSpace\zuche.web.html\src\$$_gendir'
  using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir)
    using description file: D:\CodeWorkSpace\zuche.web.html\package.json (relative path: ./src/$$_gendir/app/home/pages/agent/profit/profit.module.ngfactory.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\profit\profit.module.ngfactory.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\profit\profit.module.ngfactory.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\profit\profit.module.ngfactory.ts.js doesn't exist
      as directory
        D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\profit\profit.module.ngfactory.ts doesn't exist
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\profit\profit.module.ngfactory.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\profit\profit.module.ngfactory.ts.ts]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\profit\profit.module.ngfactory.ts.js]
[D:\CodeWorkSpace\zuche.web.html\src\$$_gendir\app\home\pages\agent\profit\profit.module.ngfactory.ts]
 @ ./src/$$_gendir lazy
 @ ./node_modules/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Martin-Wegner** [comment]
https://github.com/angular/angular-cli/issues/7520

**Comment by Chris1308** [comment]
Hey,

i had a similar problem yesterday when i imported my custom library (which is build in Angular Package Format 4.0) to my app. The problem was (i don't know why yet) in my public_api.ts. I had to change
`export * from './my-module'` to `export * from './my-module/index'`.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by jpconsi** [comment]
@Chris1308 solution worked for me.   So, I am using Yeoman angular2-library https://github.com/jvandemo/generator-angular2-library which uses Angular Package Format 4.0   In my library I had the root index which included code for the Module along with these export statements:  
```
export * from './shared';
export * from './helpers';
```

By change those to this, it clear the error

```
export * from './shared/index';
export * from './helpers/index';
```

The error I was getting prior to the change, when running the demo app (ng build --prod) that used the library:

54:42-47 "export 'ɵm' (imported as 'i1') was not found in '@company/inhouse-angular4-library'

WARNING in ./src/$$_gendir/~/@company/inhouse-angular4-library/inhouse-angular4-library.ngfactory.ts
156:51-56 "export 'ɵl' (imported as 'i1') was not found in '@company/inhouse-angular4-library'

WARNING in ./src/$$_gendir/~/@company/inhouse-angular4-library/inhouse-angular4-library.ngfactory.ts
225:34-39 "export 'ɵn' (imported as 'i1') was not found in '@company/inhouse-angular4-library'

WARNING in ./src/$$_gendir/~/@company/inhouse-angular4-library/inhouse-angular4-library.ngfactory.ts
225:42-47 "export 'ɵo' (imported as 'i1') was not found in '@company/inhouse-angular4-library'

WARNING in ./src/$$_gendir/~/@company/inhouse-angular4-library/inhouse-angular4-library.ngfactory.ts
227:56-61 "export 'ɵn' (imported as 'i1') was not found in '@company/inhouse-angular4-library'

WARNING in ./src/$$_gendir/~/@company/inhouse-angular4-library/inhouse-angular4-library.ngfactory.ts
239:33-38 "export 'ɵp' (imported as 'i1') was not found in '@company/inhouse-angular4-library'

WARNING in ./src/$$_gendir/~/@company/inhouse-angular4-library/inhouse-angular4-library.ngfactory.ts
243:47-52 "export 'ɵp' (imported as 'i1') was not found in '@company/inhouse-angular4-library'

WARNING in ./src/$$_gendir/~/@company/inhouse-angular4-library/inhouse-angular4-library.ngfactory.ts
281:33-38 "export 'ɵe' (imported as 'i1') was not found in '@company/inhouse-angular4-library'

WARNING in ./src/$$_gendir/~/@company/inhouse-angular4-library/inhouse-angular4-library.ngfactory.ts
283:59-64 "export 'ɵe' (imported as 'i1') was not found in '@company/inhouse-angular4-library'

ERROR in ./src/$$_gendir/~/@company/inhouse-angular4-library/inhouse-angular4-library.ngfactory.ts
Module not found: Error: Can't resolve '@company/inhouse-angular4-library/helpers/index' in '/home/repo/bb-inhouse-angular4-library/demo/src/$$_gendir/node_modules/@company/inhouse-angular4-library'
 @ ./src/$$_gendir/~/@company/inhouse-angular4-library/inhouse-angular4-library.ngfactory.ts 7:0-320
 @ ./src/$$_gendir/app/app.component.ngfactory.ts
