### ISSUE TITLE
Re-Render page events without reloading page in angular

### ISSUE THREAD

**Issue by gaurav22031987** [angular/angular#18994]
Hi,

I have dropdown to change language. and My API take language parameter and return response based on passed language. I have to call every component ngOnit method when dropdown changes. So need re-render instead of reload.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Chelayos** [comment]
maybe have a look at
https://github.com/ngx-translate
https://medium.com/letsboot/translate-angular-4-apps-with-ngx-translate-83302fb6c10d

and
```
export class YourComponent implements OnInit, AfterViewChecked {

public ngAfterViewChecked() {
	// your re-render logic here

       // *** Example ***
       if(this.lang == 'en')
       switchLanguage('en'); // loads your en.json
    }
}
```

**Comment by Chelayos** [comment]
> "My API take language parameter and return response"
What does your API exactly return? Which type? What information? We need more infos if u need further help ;)

**Comment by pkozlowski-opensource** [comment]
Please direct support questions to an appropriate channel as suggested by @ericmartinezr

**Comment by gaurav22031987** [comment]
Api take language as parameter and returm response based on passes
language. So i have to call every component ngonit method and call all
services again with language specific reaponse and bind new data with evry
components.
