### ISSUE TITLE
404 on route refresh in angular 4

### ISSUE THREAD

**Issue by ihd2911** [angular/angular#19009]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I created a new component in angular 4 added its route 'account'. When i run ng serve. Home page opens and there is a link to account page. On clicking account page link account page opens. If i refresh page , it works

Problem is when i make build with ng build and upload build on apache. If i click on 'account' link, account page opens. But if i refresh or try open account route directly i get 404 error.

If i add 'use hash', then it works with '#', but i don't want this.

I am using angular 4.2.4

## Expected behavior

Every route on build should work on page refresh or directly opened

## Environment

<pre><code>
Angular version: 4.2.4
Apache

**Comment by Toxicable** [comment]
This isn't a problem with Angular.
You need to configure a fallback route on your server to serve up your index.html file when a route cant be matched

**Comment by ihd2911** [comment]
I have tried a recommendation provided by someone over here

https://github.com/mgechev/angular-seed/wiki/Deploying-prod-build-to-Apache-2

**Comment by ihd2911** [comment]
Got it working

Just adding .htaccess in root 

```
<IfModule mod_rewrite.c>
    RewriteEngine on

    # Don't rewrite files or directories
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]

    # Rewrite everything else to index.html
    # to allow html5 state links
    RewriteRule ^ index.html [L]
</IfModule>


```

**Comment by justinasit** [comment]
In case people are using Nginx - this works:

```
location / {
    try_files $uri $uri/ /index.html?$query_string;
}
```

**Comment by odairto** [comment]
If someone are using IIS, this work perfectly for me.

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <rewrite>
        <rules>
            <rule name="angularjs routes" stopProcessing="true">
                <match url=".*" />
                <conditions logicalGrouping="MatchAll">
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                </conditions>
                <action type="Rewrite" url="/**youtsitehere**/" />
            </rule>
        </rules>
    </rewrite>
  </system.webServer>
</configuration>

**Comment by kunalkakkad** [comment]
@odairto  Can you please let me know that where do i need to put the code snippet provided for iis?

**Comment by odairto** [comment]
@kunalkakkad, in web.config of your web application.

**Comment by Prathameshn** [comment]
from angular 2 to angular 6 
add   RouterModule.forRoot(appRoutes,{useHash: true})
in app.module.ts

**Comment by vibinvalsalan** [comment]
@odairto solution worked for me as well.
But I had API in my application which stopped working after adding since they got redirected as well. In order to fix this i had to add one more line in conditions.

**<add input="{URL}" matchType="Pattern" pattern="/API/" negate="true" />**
since all my APIs where running at the location /API/*
found at 
[https://stackoverflow.com/questions/32062924/url-rewriting-breaks-web-api-calls](url)


This is how my rewrite section in web.config looks like

<rewrite>
    <rules>
      <rule name="Angular Routes" stopProcessing="true">
        <match url=".*" />
	  <conditions logicalGrouping="MatchAll">
	    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
	    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
		<add input="{URL}" matchType="Pattern" pattern="/API/" negate="true" />
	  </conditions>
	  <action type="Rewrite" url="/Corp.Traveller.UI/" />
      </rule>
    </rules>
  </rewrite>

**Comment by NickyMwangi** [comment]
> <IfModule mod_rewrite.c> RewriteEngine on # Don't rewrite files or directories RewriteCond %{REQUEST_FILENAME} -f [OR] RewriteCond %{REQUEST_FILENAME} -d RewriteRule ^ - [L] # Rewrite everything else to index.html # to allow html5 state links RewriteRule ^ index.html [L] </IfModule>

Thank you. This saved my day

**Comment by sehranhas** [comment]
What would the F5 equivalent be for handling these 404 errors?

**Comment by tashi-179** [comment]
> Got it working
> 
> Just adding .htaccess in root
> 
> ```
> <IfModule mod_rewrite.c>
>     RewriteEngine on
> 
>     # Don't rewrite files or directories
>     RewriteCond %{REQUEST_FILENAME} -f [OR]
>     RewriteCond %{REQUEST_FILENAME} -d
>     RewriteRule ^ - [L]
> 
>     # Rewrite everything else to index.html
>     # to allow html5 state links
>     RewriteRule ^ index.html [L]
> </IfModule>
> ```

This saved my day. Thank you very much.

**Comment by asmaus** [comment]
> > Got it working
> > Just adding .htaccess in root
> > ```
> > <IfModule mod_rewrite.c>
> >     RewriteEngine on
> > 
> >     # Don't rewrite files or directories
> >     RewriteCond %{REQUEST_FILENAME} -f [OR]
> >     RewriteCond %{REQUEST_FILENAME} -d
> >     RewriteRule ^ - [L]
> > 
> >     # Rewrite everything else to index.html
> >     # to allow html5 state links
> >     RewriteRule ^ index.html [L]
> > </IfModule>
> > ```
> 
> This saved my day. Thank you very much.

With what version of Angular? Thank you.

**Comment by asmaus** [comment]
What version of Angular? Thank you.

**Comment by tashi-179** [comment]
I am attaching the screen shoot.


Thanks. Best Regards

Tashi Dendup, B.Sc Computer science, Sherubtse College, Trashigang

Chief Technical Officer

Mobile: +975-1747-7 <+975%2017%2011%2033%2036>*051*

**Comment by tashi-179** [comment]
Click [Angular Version](https://drive.google.com/file/d/0B_zTfdrPpb_QNDBjUTNpVnByY2xIdTczc1JCWGtFTU1jOXRF/view?usp=sharing) for version details.

**Comment by Gowthamsasikala** [comment]
Hi @tashi-179  i am new to angular , can u tell me which root u r talking about ?
where we have to place the .htaccess file ?
Thanks in advance :)

**Comment by trotyl** [comment]
@Gowthamsasikala This issue doesn't relates to Angular, so it doesn’t matter whether you’re new to Angular. `.htaccess` is a configuration file of Apache web server.

**Comment by ihd2911** [comment]
@Gowthamsasikala Place .htaccess at root of your project

**Comment by parwinderD4D** [comment]
Hi 
I have same issue. Basically i have upload my build ( dist )  folder under sub-folder.
for Example : /home/abc/myapp/public/angular_front/dist/
and i have link my domain name ( Eg:  www.abc.com ) to dist folder.

after that I add  .htaccess under ( /home/abc/myapp/public/    folder ).  
even i also try with (  /home/abc/myapp/public/angular_front/dist/  )  but still i am facing same issue.

could you please let me know what i did wrong here ? 

Thanks

**Comment by jecorrales3** [comment]
@parwinderD4D hey, I've solved this issue following this way:

1.  You have to change in your index
```
<!doctype html>
<html lang="en">
  <head>
<meta charset="utf-8">
    <title>Administrador</title>
    <!-- add a point before the / -->
    <base href="./">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
```
2. Copy your project from the directory of your project (inside dist)
`myproject/dist/(copy this folder, its the same name of your project)`
3. Send your project to your hosting (app its the name of my project). 
![folder-project](https://user-images.githubusercontent.com/25104888/61723500-e0523f00-ad31-11e9-83c8-648bd33f215b.png)

4. Write this code in your htaccess file (as ihd2911 wrote)
```
<IfModule mod_rewrite.c>
    RewriteEngine on

    # Don't rewrite files or directories
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]

    # Rewrite everything else to index.html
    # to allow html5 state links
    RewriteRule ^ index.html [L]
</IfModule>
```

5. Then, you have to cut this file (.htaccess) and put it inside of your folder project in your server.
![screenshot-project](https://user-images.githubusercontent.com/25104888/61723344-92d5d200-ad31-11e9-89fb-3a0cd7ea2585.png)

Tell us if this solve your issue.

**Comment by ihd2911** [comment]
@jecorrales3  Please do not add .htaccess like this, use angular.json file to add htaccess file.

**Comment by jecorrales3** [comment]
> @jecorrales3 Please do not add .htaccess like this, use angular.json file to add htaccess file.

Can you give more information, because I've done this as you said in your comment. Sorry if I'm wrong.

>  Place .htaccess at root of your project

**Comment by ihd2911** [comment]
@jecorrales3 Yes, but we do not need to manually add htaccess everytime we create a build. keep htaccess file in src folder, in angular.json file, add htaccess like following. Whenever build will be created, it will be automatically placed in your dist directory/

```
"assets": [
              "src/favicon.ico",
              "src/assets",
              "src/.htaccess"
            ],
```
