### ISSUE TITLE
[i18n] warn at build time if the locale data are never imported

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#19000]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Compiling in AoT mode an application with a locale can be totally fine, but can crash at runtime as `registerLocaleData` is never called with the proper locale data.

## Expected behavior
I'm sure it's not trivial, but it would be great to have a warning at build time if the locale data 
is never loaded.

## Minimal reproduction of the problem with instructions
`ngc --i18nFile=./messages.fr.xlf --locale=fr --i18nFormat=xlf` with a project where `registerLocaleData(localeFr)` is never called.

This was discussed briefly with @ocombe

**Comment by vicb** [comment]
@cexbrayat If you use the CLI, the data file will be imported automatically (thanks to a recent change from @ocombe).

If you do not use the CLI, we'd better know what you are doing - and we can not assume that there will be a `registerLocaleData(localeFr)` in the code (lazy or http2 loading is one example that comes to my mind).
