### ISSUE TITLE
aio: refactor ToH to use HttpClient API instead of Http API

### ISSUE THREAD

**Issue by jotatoledo** [angular/angular#19002]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The current version of the ToH tutorial still uses the old Http API.

## Expected behavior
New developers should use the new HttpClient API instead of the old during the ToH tutorial.

## What is the motivation / use case for changing the behavior?
Considering that the new HttpClient API should slowly be adopted by developers, it would be reasonable to show new devs only this API instead of the old to avoid confusion.

The most critical area would be [the part 6](https://angular.io/tutorial/toh-pt6) of the tutorial.

**Comment by trotyl** [comment]
Seems already fixed in #19811?
