### ISSUE TITLE
Angular Language Service breaks Typescript intellisense on VS Code

### ISSUE THREAD

**Issue by distante** [angular/angular#19015]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When the Angular Language Service Extension is enabled `*.ts` files intellisense does not work.

## Expected behavior
Intellisense should still work when the extension is enabled.

## Minimal reproduction of the problem with instructions

1. create a new ionic project with `ionic start` and select "conference" (since it is a complete project).
2. Install Angular Language Service.
3. Test intellisense on ts files

Repo: https://github.com/distante/Angular-Language-Service-Breaks-Intellisense

## Environment

<pre><code>
Angular version: 4.1.3

 
For Tooling issues:
- Node version: v6.11.2 
- Platform:  Mac, Windows

Others:
OS: Windows 10 creators update / MacOS Sierra
VS Code version: tested on 1.14.2 and 1.15.1 (32bits and 64bits)
Extensions:
Angular.ng-template
bobjoy.vscode-browser-plus
christian-kohler.path-intellisen
CoenraadS.bracket-pair-colorizer
dbaeumer.vscode-eslint
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.code-runner
helixquar.asciidecorator
jakethashi.vscode-angular2-emmet
johnpapa.Angular2
michelemelluso.code-beautifier
mrmlnc.vscode-apache
rbbit.typescript-hero
Shan.code-settings-sync
vsmobile.cordova-tools
wayou.vscode-todo-highlight
Zignd.html-css-class-completion

</code></pre>

**Comment by lax20attack** [comment]
Works fine for me. v4.3.6, Win 10 x64

**Comment by lazarljubenovic** [comment]
Isn't this more of a VSCode issue?

**Comment by distante** [comment]
Was instructed to post the issue here.

**Comment by kyliau** [comment]
Angular language service is completely separate from Typescript language service. As such, there's no interaction between the two. Please make sure you're using the latest Angular extension from the vscode marketplace.
https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
