### ISSUE TITLE
Cannot use ternary if statement inside [(ngModel)]

### ISSUE THREAD

**Issue by alex-chaliy** [angular/angular#19017]
Trying to user ternary if statement inside ngModel.
```html
<input [(ngModel)]="(mode == 'edit') ? userToUpdate.name_first : newUser.name_first" id="name_first" class="form-control" type="text">
```

This expression binds model only for newUser.name_first `(mode == 'edit') ? userToUpdate.name_first : newUser.name_first`, but doen't bind model to userToUpdate.name_first.

I've been trying to find an answer in stackoverflow but didn't get any result.
Here is the place where I've tried to use the statement: 
https://github.com/alex-chaliy/TeamManager/blob/master/client/src/app/home/home.component.html#L43

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by robwormald** [comment]
@alex-chaliy the basic issue is that `[(ngModel)]="someValue"` is basically just shorthand for the longhand version `<input [ngModel]="someValue" (ngModelChange)="someValue = $event.target.value">` - so while a complex expression like `(mode == 'edit') ? userToUpdate.name_first : newUser.name_first` makes sense for the model => view binding, it doesn't really make sense in the view => model direction. Generally best to resolve the expression in your component code.
