### ISSUE TITLE
Request Ability to Set Default Timezone and Locale for Date Pipe Application Wide 

### ISSUE THREAD

**Issue by jmcclanahan** [angular/angular#19018]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently you have to specify a timezone and/or locale for every instance of the Date pipe you have. Otherwise, according to the docs, "If not specified, the local system timezone of the end-user's browser will be used.". 

## Expected behavior
It would be nice to have a way to set the default values for these fields for the entire app, rather than having to add these to every instance of the date pipe.

## What is the motivation / use case for changing the behavior?
If you have more than a handful of date pipes throughout your app it would good to have a single place to change the timezone and locale rather than having to change all instances each time you want to make a change. In my current application I have hundreds of date pipes scattered throughout the app.

## Environment

<pre><code>
Angular version: 5.0.0-beta.6

**Comment by ocombe** [comment]
You can set the locale with the token `LOCALE_ID`, there's no option for the timezone yet

**Comment by hiepxanh** [comment]
https://medium.com/@markuretsky/extend-angular-datepipe-for-timezone-abbreviations-support-9b65fa0807fb

**Comment by JoostK** [comment]
This has been implemented in #43611.
