### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by micahng** [angular/angular#19024]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm currently having two errors in deploying my project. 

First error: 
ERROR in Error encountered resolving symbol values statically. Could not resolve ./header/header.component relative to /tmp/build_c97b0cf3c8e59fa47cf245b9a6e3c944/src/app/app.module.ts., resolving symbol AppModule in /tmp/build_c97b0cf3c8e59fa47cf245b9a6e3c944/src/app/app.module.ts, resolving symbol AppModule in /tmp/build_c97b0cf3c8e59fa47cf245b9a6e3c944/src/app/app.module.ts
Second error:

ERROR in ./src/main.ts
remote:        Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/tmp/build_c97b0cf3c8e59fa47cf245b9a6e3c944/src'
remote:        @ ./src/main.ts 4:0-74
remote:        @ multi ./src/main.ts

## Environment

<pre><code>
Angular version: 4.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version 60.0.3112.113
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  Mac

Others:

</code></pre>

**Comment by chuckjaz** [comment]
@micahng Your report does not contain enough information for us to determine the problem.

Can you provide link to a repository the demonstrates the issue you are running into.

**Comment by mhevery** [comment]
This issue seems abandoned without any reproducible instruction.  We are closing the issue. If you have reproducible instructions please file a new issue.
