### ISSUE TITLE
could you update the document of Hero Editor  ?

### ISSUE THREAD

**Issue by xiaoCong2014** [angular/angular#19021]
## It's obvious that the document is not up to date .
for example :

At the beginning of the document ,  it uses 'npm start' , why not use 'ng serve'  instead ?

**Comment by michaelbazos** [comment]
@xiaoCong2014 

If you open `package.json` file, you'll notice that `npm start` triggers `ng serve`, with the command `ng` being picked from the `node_modules/.bin` folder. That way, you don't need to have `ng` globally on your system to start the application. Therefore, the documentation is fine on this point.
