### ISSUE TITLE
Angular v5 compiler rewrites imports

### ISSUE THREAD

**Issue by Eddman** [angular/angular#19026]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

I'm using TypeScript `paths` to define a sub-module in my repo:
```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "rootDir": ".",
        "paths": {
            "@my-org/my-sub-module": [
                "./src/my-sub-module/public_api.ts"
            ]
        }
    }
}
```

Then in a `.ts` file I use the import:
```typescript
import {some_class} from '@my-org/my-sub-module';
```

When I compile using NGC it resolves the imports correctly, but sometimes replaces it with relative path in the output files:
```javascript
import { some_class } from "./../my-sub-module/public_api";
```

This is fine for base usage, but once I try to use rollup to bundle packages based on the `paths` it will try to include files that do not belong to my sub-module. The roots in `paths` are passed into `external` option of rollup. But these do not match the rewritten paths anymore...

The code was working fine in Angular **4.3.x.**

## Expected behavior
The imports are never replaced with relative paths. 

## Minimal reproduction of the problem with instructions
Can't find any pattern for which the imports are modified. It seems to be that they are changed once the relative path is shorter then the name in `paths`(?)...

## Environment
<pre><code>Angular version: 5.0.0-beta.6
TypeScript: 2.3.4
</code></pre>

**Comment by Toxicable** [comment]
v5 is currently in beta, the Compiler changes are not done yet.
I'd suggest waiting till RC at least before trying to use it

**Comment by tbosch** [comment]
This is probably related to tsickle trying to find the main imported file. However, this is no longer needed, so we can just flip the flag to false here: https://github.com/angular/angular/blob/master/packages/compiler-cli/src/main.ts#L49

@Toxicable would you have a bit of time to try this, if that fixes this problem?

Same problem seems to be in https://github.com/angular/angular/issues/17171

**Comment by Toxicable** [comment]
@tbosch sure I can take a look

**Comment by Toxicable** [comment]
@tbosch I attempted to reproduce this on v5.0.0-beta.7 but was unable to. I made this repo to show what I was trying: https://github.com/Toxicable/angular-indexmodule-issue
and as you can see in the dist it produced normal imports
https://github.com/Toxicable/angular-indexmodule-issue/blob/master/dist/main.js
The libs you see there are some of the ones people were having issues with in #17171

@Eddman Could you make us a minimal reproduction? maybe there is something slightly different in out tsconfig.json

**Comment by Toxicable** [comment]
@tbosch Ok I've manged to reproduce this, I wasn't using `"annotateForClosureCompiler": true` in my tsconfig  before :/
Anyway so I have this
## v5.0.0-beta.7
**input** 
```
"paths": {
  "submodule": ["./my-module"]
},

//root main.ts
import { name } from 'submodule'
```
**output**
```
import { name } from "./my-module/index";
```
with **`convertIndexImportShorthand: false`**
```
import { name } from "submodule";
```
## v4.4.3
That same code makes the output, but then throws an error
```
import { name } from 'submodule/index';
```
but if we instead use 
**input**
```
import { UIRouterModule} from '@uirouter/angular';
```
**output**
```
import { UIRouterModule } from '@uirouter/angular/index';
```
and with **`convertIndexImportShorthand: false`**
```
import { UIRouterModule } from '@uirouter/angular';
```

**Comment by Kamilius** [comment]
@Toxicable could you specify where exactly this `convertIndexImportShorthand: false` should be specified?

**Comment by Toxicable** [comment]
@Kamilius That's done by changing code in Angular itself since it's an internal setting for tsickle

**Comment by Kamilius** [comment]
@Toxicable got it. When approximately we can get this fix?

**Comment by Toxicable** [comment]
@Kamilius I'm not certain, a decision needs to be made `convertIndexImportShorthand` is indeed going to be switched to `false`, I can't make this decision

**Comment by zhangyulins** [comment]
td




发自网易邮箱大师
On 09/22/2017 18:32, Fabian Wiles wrote:

@Kamilius That's done by changing code in Angular itself since it's an internal setting for tsickle

**Comment by Kamilius** [comment]
@Toxicable maybe you are aware, if there is a version that doesn't have this bug?

**Comment by Toxicable** [comment]
Nope, this hasn't been changed as far as im aware

**Comment by chuckjaz** [comment]
Reproduced @Toxicable's conclusions above. Turning off `convertIndexImportShorthand` fixes this issue.

Current work-arounds include:
1) Use `annotateForClosureCompiler` to `false`.
2) Modify, manually, the `main.js` file in `@angular/compiler-cli/src` to set `convertIndexImportShorthand` to `false`.

Working on a PR to make this change.
