### ISSUE TITLE
exception in Visual Studio while debugging angular app but application launches in browser 

### ISSUE THREAD

**Issue by BugFreeBugs** [angular/angular#19027]
Unhandled exception at line 33893, column 5 in http://localhost:53219/dist/vendor.js?v=RCvRrqPvM2Kc5BlkEQ045FeXR6gPMRIwfn51ludN14I
0x800a138f - JavaScript runtime error: Unable to get property 'apply' of undefined or null reference occurred

**and here is code that start at line** 

function combine(options) {
    **return ((Object)).assign.apply(((Object)), [{}].concat(options));**
}

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
