### ISSUE TITLE
Why not upload the example in the official website document to GitHub ?

### ISSUE THREAD

**Issue by xiaoCong2014** [angular/angular#19020]
## I'm talking about the example source code.
The official website is "https://angular.io/docs" . 
Why not upload the example code ( in the official website document ) to GitHub ?
such as  this download link ---> "https://angular.io/generated/zips/ngmodule/minimal.0.ngmodule.zip"

And what about the source of Hero demo ?

**Comment by ocombe** [comment]
Hello, you can find the code for the examples of angular.io here: https://github.com/angular/angular/tree/master/aio/content/examples
