### ISSUE TITLE
ngc does not produce .ngfactory files since 5.0.0-beta.4

### ISSUE THREAD

**Issue by bukharin** [angular/angular#19022]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Since 5.0.0-beta.4 ngc does not produce .ngfactory.ts files

## Minimal reproduction of the problem with instructions

run `ngc -p tsconfig.aot.json`

My `tsconfig.aot.json`

```
{
    "compilerOptions": {
        "target": "es2015",
        "module": "es2015",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "noEmit": true,
        "noEmitHelpers": true,
        "importHelpers": true,
        "baseUrl": ".",
        "paths": {
            "@angular/*": ["node_modules/@angular/*"]
        },
        "lib": [
            "dom",
            "es6"
        ],
        "types": [
            "node"
        ]
    },
    "exclude": [
        "node_modules",
        "dist",
        "src/platform/browser/main.aot.ts",
        "src/**/*.spec.ts",
        "src/**/*.e2e.ts"
    ],
    "filesGlob": [
        "src/typings/custom-typings.d.ts"
    ],
    "compileOnSave": false,
    "buildOnSave": false,
    "angularCompilerOptions": {
        "genDir": "./src/ngfactory",
        "skipMetadataEmit": true
    }
}

```

After ngc command `./src/ngfactory` is empty. No files produced. No errors and any other information provided to console output.

5.0.0-beta.3 works as expected.

## Environment

Angular version: 5.0.0-beta.4 or higher
 
For Tooling issues:
- Node version: 8.2.1
- Platform:  Windows 10

**Comment by Toxicable** [comment]
It's not meant to produce ngfactory files anymore

**Comment by bukharin** [comment]
@Toxicable how to use ngc now? Is there any doumentation?

**Comment by trotyl** [comment]
> `genDir` should be removed as it is not used starting with v5

from https://github.com/angular/angular/pull/18952#discussion_r136174786

**Comment by bukharin** [comment]
@trotyl no effect. I guess that starting v5 there is a new model for AOT compilation which not documented yet

**Comment by Toxicable** [comment]
It's beta, wait till RC, if you want docs wait till at least GA

**Comment by bukharin** [comment]
@trotyl thanks! That's work. In my case `outDir` was a `dist` folder, which was ignored in VCS root and I didn't notice that files emited there. 

Anyway it would be nice to write about this in changelog.

**Comment by trotyl** [comment]
@bukharin I agree to that, but whether `tsconfig.json` options being part of public API is not quite clear:

> Additionally only the command line usage (not direct use of APIs) of `@angular/compiler-cli` is covered.

From https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md

This may also relates to https://github.com/angular/angular/issues/16861 about the documentation of how angular make use of `tsconfig.json`.

**Comment by ocombe** [comment]
Hello, yes as you said ngc doesn't produce ngfactory files anymore, they stay in memory (we're using typescript transformers now).
And yes genDir is no longer used.
More docs are coming once we're in RC, right now we're focusing on making sure that any breaking change is merged before the first RC so we have less time for docs.

**Comment by steveblue** [comment]
Why can't you give us docs while in `beta`? This is really frustrating. Why do you call it `beta` when we cannot even test the production build? I do not agree with @Toxicable that we should have to wait until GA for docs. We need to be able to test our production build leading up to RC.

**Comment by StephenFluin** [comment]
@steveblue The functioning of AOT hasn't changed significantly, we've made the existing process faster by refactoring it to be a TS transform. Developers should be able to call ngc or use the CLI to create AOT compiled and transpiled builds with these betas. If there are any use cases we are missing, please email me at devrel@angular.io.
