### ISSUE TITLE
Why does ngc only support exported symbols

### ISSUE THREAD

**Issue by maximusk** [angular/angular#19031]
We all know that we need to export a symbol (function/class) from a module if we want to use it in the component/module metadata. 

**The question is why?**

I was thinking that maybe the TS compiler doesn't supply that information, but all symbols are provided in the `sourceFile`. And [this function](https://github.com/angular/angular/blob/fa6b802be4c79f57aa8484fe47f0c860f1226683/packages/tsc-wrapped/src/collector.ts#L301) in the collector compiler checks if a symbol (class) is exported and if not marks a class as error symbol:

```
        ts.forEachChild(sourceFile, function (node) {
            switch (node.kind) {
                case ts.SyntaxKind.ClassDeclaration:
                    var classDeclaration = node;
                    if (classDeclaration.name) {
                        var className = classDeclaration.name.text;
                        if (isExported(classDeclaration)) {
                            locals.define(className, { __symbolic: 'reference', name: exportedName(classDeclaration) });
                        }
                        else {
                            locals.define(className, errorSym('Reference to non-exported class', node, { className: className }));
                        }
                    }
```

Any comments are highly appreciated!

**Comment by vicb** [comment]
ngc generates code that need to reference those symbols which is why they need to be public.

In 5.x there will be a TS transformer that will automatically export symbols that need to be exported. No more manually export !

Hope this helps.

**Comment by maximusk** [comment]
@vicb , appreciate your reply very much. Do you guys maybe have an internal document on that transformer? Or any other info besides sources? I'd like to get familiar with it. Thanks in advance!
