### ISSUE TITLE
StaticReflector change breaks the language service 5.0 used against 4.0

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#19039]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
</code></pre>

## Current behavior

Prior to 3c4eef8a8627d58078a06a2414c8cc06f125f0c5 the 5.0 language service could be used with a 4.0 or 2.0 project allowing one language service for all angular versions.

## Expected behavior

The language service should work with all versions of Angular.

## Minimal reproduction of the problem with instructions

Use the language service 5.0 against a 4.0 project that uses OpaqueToken.

Note that spurious diagnostics are reported bout not being able to resolve the opaque token.

## Recommended fix

Revert the changes in 3c4eef8a8627d58078a06a2414c8cc06f125f0c5 for static_reflector.ts

**Comment by tbosch** [comment]
Closed via https://github.com/angular/angular/commit/c1b029a41390e6b6030a162db83cba01e59681db
