### ISSUE TITLE
benchpress: bundle for G3

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1903]
E.g. bundle via `browserify` and then add explicit exports:

```
var browserify = require('browserify');

var b = browserify(__dirname + '/../../dist/js/cjs/benchpress/common.js').bundle();
b.pipe(process.stdout);
+ append `module.exports = ...` statement.

```

Open questions:

- what `WebDriverAdapter` to use? Does `SeleniumWebDriverAdapter` work? @juliemr 
- the output is about 500k, as we include a lot of things. Is that a problem for G3?

**Comment by juliemr** [comment]
Depends on whether we want it to be consumed by JS or Dart users - from the rest of the issue, I think you're thinking for JS, in which case `SeleniumWebDriverAdapter` should be fine.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
