### ISSUE TITLE
Lack of animation docs

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular#19032]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

The official doc lacks of the new router animations and the 'disabled' attribute information.

The only doc available is from Matsko himself at https://www.yearofmoo.com/2017/06/new-wave-of-animation-features.html.

Therefore I don't know how to listen to animation events on router transition. Is this even possible ?
It would be really cool to be able to to this as it is possible with the basic router transition system.

Thank you for your hard work.

**Comment by matsko** [comment]
Sorry for the animation docs being limited. There have been a variety of bugs with all the new features so the priority has been on getting those fixed.

There are some docs on `@.disabled`:
https://angular.io/api/animations/trigger#disable-animations

Could you elaborate more on "listening on animation events"? The router animation documentation will show up soon as another external post. Once things are more stable with the framework then there will be more guides and docs.

**Comment by Ploppy3** [comment]
Hello, thank you for your response and the link to the disabled docs.

About the events: 
The previous way to do router transition was the following: add the transition to the component `host: {'[@routerAnimations]': ''}` you could listen to animations events such as `(@routerAnimations.done) `
and call a function when the transition finished to start animating the component once fully visible.

With the new animation system, due to the fact that the animation trigger is not on the component but on the div wrapping the router I can't find a way to listen to the `.done` event. There must be something that I'm missing.

---

Also on the latest angular version the (newer) router transition seems broken: with this simple fade-out transition my component disappear but next one never appear due to a `style="display: none;"` in html probably produced by the animation system.

```
export const routerAnimations =
  trigger('routerAnimations', [
    //* Fallback animation
    transition('* => *', [
      query(':leave', [
        animate('.5s ease-in-out', style({ opacity: 0 }))
      ], { optional: true }),
    ]),
    //*/
  ]); 
```

If you think it's a bug I will open an other issue for this.

**Comment by Bretto** [comment]
@Ploppy3 I feel your pain man I have been on this wagon with no docs for months... https://github.com/angular/angular/issues/18939

**Comment by Ploppy3** [comment]
@matsko Any info about my previous comment?

**Comment by Ploppy3** [comment]
@matsko Did I explain it properly in my previous message?

**Comment by Ploppy3** [comment]
@matsko Hello, can you please answer my previous question about the router animation events? Thank you.

**Comment by swftvsn** [comment]
I also tried to find a way to react (in the view that is being animated into router-outlet) when the animation is done. (To kick off further animations and stuff). I ended up doing like this:
  ```
  routerTransitionDone($event) {
    // console.log($event)
    this.routerService.animationEnded(this.router.url)
  }
``` 
``` 
<div [@routerTransition]="getState()" (@routerTransition.done)="routerTransitionDone($event)">
``` 
Where router service is simply 

```
export type TransitionAnimationEnd = {
  url: string
}

@Injectable()
export class RouterService {

  private transitionAnimationEndEventSubject = new Subject<TransitionAnimationEnd>()
  transitionAnimationEndEventObservable = this.transitionAnimationEndEventSubject.asObservable()

  constructor() {

  }

  public animationEnded(url: string) {
    this.transitionAnimationEndEventSubject.next( { url: url } )
  }

}
```
This way I can subscribe in the component to that service and filter on the url. Not pretty at all. Please, please add an interface or something that I can implement or subscribe to to get the notifications.

Like OnRouterAnimationDone or something.

**Comment by Ploppy3** [comment]
@swftvsn I imagined it like this, I don't think of any better way to implement it. I get no answer from the devs but this is a big regression as it used to work with the old system.

@matsko Do you have any news on this?

**Comment by matsko** [comment]
Yes we have a tech-writer who is compiling all the contents for animations. There are plans for basic/advanced animations as well as a guide on routing. Component animations using AnimationBuilder will come around later as well as something on testing.
