### ISSUE TITLE
New version return error after build

### ISSUE THREAD

**Issue by kresogalic8** [angular/angular#19037]
Hey guys, I've upgraded application with version 4.4.0-RC.0 and what I got is this: 

Uncaught Error: No NgModule metadata found for 't'

Do you have something in mind that can resolve this issue?

**Comment by Toxicable** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
