### ISSUE TITLE
Zones & server environment

### ISSUE THREAD

**Issue by vicb** [angular/angular#1904]
If we want to run angular server side, we need to have zones available there.

As of today, zones are not supported in the CJS env.

### Short term:

Port the PR from @mlval (https://github.com/angular/zone.js/pull/78) to zone 0.5.

Then it would be possible to start running server side but a lot of things would not be intercepted. That is not a valid solution for mid-term.

However it can unblock us quickly.

### Mid Term:

Find a proper solution for server side.

May be someting base on [strongloop/zone](https://github.com/strongloop/zone)

Thoughts ?

/cc @tbosch @mhevery @IgorMinar

**Comment by vicb** [comment]
@naomiblack moved this to a.30 I won't have time to work on this before next week

**Comment by vicb** [comment]
I won't have time to work on this and I'll be preparing the move in July.

**Comment by boneskull** [comment]
I'm trying to understand the status of server-side support for Angular 2.  Is this the issue to watch?

**Comment by otodockal** [comment]
Angular Universal

https://github.com/angular/universal
https://github.com/angular/universal-starter

**Comment by mhevery** [comment]
Zone now works on node.
