### ISSUE TITLE
appending header in HttpHeaders from '@angular/common/http' doesn't work

### ISSUE THREAD

**Issue by riyasat** [angular/angular#19044]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When we use:
<pre><code>
let header = new HttpHeaders();
header.append('abc','22');
console.log(header.get('abc'));
</code></pre>
**In console we get null**

## Expected behavior
We should see 22 in console

## Minimal reproduction of the problem with instructions
Plunker gives error when I import HttpClientModule. But here are the steps using angular cli

1. ng new httptest -si
2. cd httptest
3. edit package.json
4. replace all old angular version to current angular version which is 4.4.0-RC.0
5. ssave
6. npm install
7. edit app.module.ts
<pre><code>
   - import { HttpClientModule } from '@angular/common/http';
   - imports:[HttpClientModule] //Added into existing import
</code></pre>
8. edit app.component.ts
<pre><code>
import { HttpClient, HttpHeaders } from '@angular/common/http';
export class AppComponent {
  title = 'app';
  constructor(private http:HttpClient) {
    this.displayHeaders();
  }
  displayHeaders(){
    let header = new HttpHeaders();
    header.append('abc','22');
    

    console.log(header.get('abc'));
  }

}
</code></pre>

**9. ng serve -o**
10. Check the console for output

## What is the motivation / use case for changing the behavior?
no change in expected behavior. We need exact same behavior as 4.3.4

## Environment

<pre><code>
Angular version: 4.4.0-RC.0

yes it is.
Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.0.0
- Platform:  Windows

Others:

</code></pre>

**Comment by shiftSh** [comment]
I have the same issue too, I was oblige to put the result in a variable and use it like:
```ts
let header = new HttpHeaders();
let other_header = header.append('abc','22');
console.log(other_header.get('abc')) // output 22
```

**Comment by trotyl** [comment]
Working as expected, `HttpHeaders` is immutable.

**Comment by riyasat** [comment]
@trotyl I didn't understand your comment. What is expected behaviour for you? for me if we use header.append('abc','22') it should add header to header collection under the hood right ? or I miss understood that?

@shiftSh is not strange? if we have to declare another variable then why should we use **header.append** why not use 
<pre><code>let headerAbc = new HttpHeaders({'abc':'22'});
let headerAbc2 = new HttpHeaders({'abc2':'22'});
</code></pre>

I have found **Workaround** for this problem which is
<pre><code> 
let headers = new HttpHeaders(
{'abc':'22'},
{'abc2':'111'},
{'abc4':'444'}
);

console.log(headers.get('abc4'));//output 444
</code></pre>

**Comment by jotatoledo** [comment]
https://stackoverflow.com/questions/45286764/angular-4-3-httpclient-doesnt-send-header/45286959#45286959

**Comment by riyasat** [comment]
@trotyl thanks for pointing me to httpparam bug. 
I did searched for http header problems before submitting the issue. Now I see that @alxhub checkin changed the syntax of httpheaders and params. Now **append** in both cases doesn't work. 
According to @cexbrayat 

> **_This was fixed by #18490 and released in 5.0.0-beta.6_**

So should we start using beta and leave the stable version which in this case (common/http) is not stable :)

If we cannot  use functions that are on instance of that class why do they exist? 

@jotatoledo  accepted solution at stackoverflow. 
_`const headers = new HttpHeaders().set('Content-Type', 'application/json; charset=utf-8');`_
will not work when adding params or headers with for loop ?

```
let headers = new HttpHeaders();
for(let i=0;i<=5;i++){
headers.append(i.toString(),i.toString())
}

```

**Comment by trotyl** [comment]
The original issue is not a bug, it is fixed for:

> whereas the old Http service allowed to use a simple object literal

But nothing changed for `HttpParams#append` since it's working pretty well.

**Comment by riyasat** [comment]
If it's working then Perfect. 
Do you have working sample link for us?
I followed the documentation https://angular.io/guide/http#configuring-other-parts-of-the-request which only works for one header but not for multiple headers.
Thanks in advance.

**Comment by riyasat** [comment]
@trotyl @jotatoledo Here is a plunker link with reported bug. If any one can fix would be really nice. May be I am doing something wrong here.
https://plnkr.co/edit/VlaQAG4QLa9z3PS8fKMl

Hope that will help if that's a bug.

**Comment by cexbrayat** [comment]
Append returns a clone of the headers https://github.com/angular/angular/blob/fa6b802be4c79f57aa8484fe47f0c860f1226683/packages/common/http/src/headers.ts#L118-L120 

So you need to store the result of the append otherwise it will have no effect, something like `headers = headers.append(i.toString(),i.toString());` in your plunkr. 

Headers and params are immutable in `common/http`, so this works as intended.

**Comment by riyasat** [comment]
@cexbrayat thanks for clarifying the concept behind append. For me this sounds bit odd because append means add or extend something to the existing object in context not clone that object in context and return. But I think it's like "Orange is new Black" phrase. 

It would be much nicer to create JSON object and pass it to constructor. 

```
let headerJson = {
'abc':'1',
'abc2':'2'
}
let headers = new HttpHeaders(headerJson );

```
Well anyway, I hope this discussion will help someone like me to figure-out that how it is meant to be working. 

👍

**Comment by rcanacci** [comment]
@trotyl  - having this same issue and others with HttpHeaders.

That its expected functionality doesn't make it logical, good, or well-thought-out.

`
let header = new HttpHeaders();
header.append('abc','22');
console.log(header.get('abc'));
`

No offense, but that response, while accurate, is also kinda lame. I realize you might not be the person implementing these features, but to me this is complexity for the sake of complexity. What is the advantage of not being able to immediately call a getter on something you've just set and expect it to work... why the backflips. Just seems lame and a concept, while serviceable, that wasn't well thought out.

Perhaps I am missing something... please correct me if that is the case.

**Comment by hassanasad** [comment]
Just to clarify for others, if you want to use `append` method of **HttpHeaders**, use it like:

```
let headers = new HttpHeaders();
headers = headers.append('Authorization', this.authHeader);
headers = headers.append('Accept', 'application/json');
headers = headers.append('Content-Type', 'application/json');
```

**Comment by kenisteward** [comment]
I don't get how this is working for anyone atm. 

https://github.com/swagger-api/swagger-codegen/issues/7342

this issue has this same idea in it and we are properly doing headers=headers.set(); however this.init() is never called when you just do a set which is never setting the internal headers.  Am I missing something?

**Comment by kenisteward** [comment]
Turns out the person still had remnants of the old http module. All is well.

**Comment by VishnuArora007** [comment]
Why we use headers , what's the purpose of using it  ?

**Comment by trotyl** [comment]
@VishnuArora007 You don't need to, just passing a plain object would be enough (if not in `HttpInterceptor`).

```typescript
headers?: HttpHeaders | {
    [header: string]: string | string[];
};
```

**Comment by timaxapa** [comment]
Hi. is it possible to override ```Content-Type``` header using HttpClient ?

**Comment by zinderud** [comment]
this code not working 
```
 let headersConfig = new HttpHeaders();
  headersConfig.append('Accept', 'application/json')
return headersConfig 
```
@riyasat  thanks for share  this code working
```

let headerJson = {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'access-token': window.localStorage.getItem("access-token"),
      'client': window.localStorage.getItem("client"),
      'uid': window.localStorage.getItem("uid")
      };
      let headersConfig = new HttpHeaders(headerJson);
```

**Comment by klinden** [comment]
This is really annoying for anyone trying to upgrade from HttpModule to HttpClientModule

**Comment by gmklaus** [comment]
I bet they're trying to make their API more fluent so you can do stuff like 

```
headers = new HttpHeaders()
   .append('Authorization', this.authHeader)
   .append('Accept', 'application/json')
   .append('Content-Type', 'application/json');
```

Though if you wanted to do that I think it would be easier to do it this way

```
headers = new HttpHeaders({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
```

**Comment by hadirsa** [comment]
Hi, i have the same issue but a little different. i have a class called `QueryParam` that extends `HttpParams` like this :
```
import {HttpParams} from '@angular/common/http';
import {Pagination} from '../pagination/pagination.model'

export class QueryParam extends HttpParams {
    constructor(paginationModel: Pagination, paramMap: Map<string, any>) {
        super(); 
        console.log(paginationModel); //has value

        this.append('pageNumber', (paginationModel.page - 1).toString());  
        this.append('pageSize', paginationModel.itemsPerPage.toString());
        this.append('order', paginationModel.sort());

        console.log(this.get('pageNumber')); // null
        console.log(this.get('pageNumber')); // null
        console.log(this.get('order')); // null 

        paramMap.forEach((value: any, key: string) => {
            this.append(key, value);
        });
    }
}
```
But everything that i set to `HttpParams` is `null`. i have also tried `set` insteed of  `append` but i got same result. 
any idea?

**Comment by Kamikze9110** [comment]
I have this interceptor

intercept(req: HttpRequest<any>, next: any): Observable<HttpSentEvent | HttpHeaderResponse | HttpProgressEvent | HttpResponse<any> | HttpUserEvent<any>> {
        if(!req.url.includes('oauth/token') && req.url.includes('pineapple-admin-core')){
            let headers = new HttpHeaders();
            if(localStorage.getItem('userToken')){
                  headers.set('Authorization', 'Bearer '+localStorage.getItem('userToken'));
            }           

            const cloneReq = req.clone({headers});
            console.log(cloneReq);
            return next.handle(cloneReq);        
        }  
        

          if(!req.url.includes('oauth/token') && req.url.includes('pineapple-admin-core')){

              let headers : HttpHeaders = new HttpHeaders();

              if(localStorage.getItem('userToken')){
                  console.log(localStorage.getItem('userToken'));
                     headers = headers.append('Content-Type',  'application/x-www-form-urlencoded');
                     headers = headers.append('Authorization', 'Bearer '+localStorage.getItem('userToken'));
              }
              const cloneReq = req.clone({headers});
              return next.handle(cloneReq);

          }else if(req.url.includes('oauth/token')){
            return next.handle(req.clone());
          }else{
            this.router.navigateByUrl('/login');
          }
    }
}

And this is my service 

getUserMe(): Observable<any>{
   return this.http.get(this.getMe).catch(this.handleError);
 } 

I have problems when call the api rest because , the token dont adding in the header
this is an screenshot of the error in the navigator

![image](https://user-images.githubusercontent.com/37960956/38166631-26d89da4-3527-11e8-9f3c-30c63091f57e.png)

**Comment by JungleeRaju** [comment]
Issue: Failed to load https://gylwgtz5sj.execute-api.ap-south-1.amazonaws.com/prod: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 403

This is my code 

let headerJson = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, OPTIONS',
      'X-Api-Key': 'vZoOzdwN38aEcFzWoLWW12umK14QrA062tB7H3sZ'
      };
      let headersConfig = new HttpHeaders(headerJson);

this.httpClient.get('https://gylwgtz5sj.execute-api.ap-south-1.amazonaws.com/prod', {headers: headersConfig})
    .subscribe(data => {
      console.log('my data: ', data);
    });

I could not understand what is wrong with code. please help me in resolving this.

**Comment by Ramesh21** [comment]
Issue: Failed to load https://gylwgtz5sj.execute-api.ap-south-1.amazonaws.com/prod: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 403

This is my code

let headerJson = {
'Access-Control-Allow-Origin': '*',
'Access-Control-Allow-Methods': 'GET, OPTIONS',
'X-Api-Key': 'vZoOzdwN38aEcFzWoLWW12umK14QrA062tB7H3sZ'
};
let headersConfig = new HttpHeaders(headerJson);

this.httpClient.get('https://gylwgtz5sj.execute-api.ap-south-1.amazonaws.com/prod', {headers: headersConfig})
.subscribe(data => {
console.log('my data: ', data);
});

I could not understand what is wrong with code. please help me in resolving this.

**Comment by jhonyourangel** [comment]
the design of the `header.append` is wrong, not intuitive and not developer friendly

look at this scenario:

    var array = [1,2,3]
    array.push(4)

as for how you designed the HttpHeaders, the array should work like this:

    var array = [1,2,3]
    array = array.push(4)

witch one makes more sense ?

**Comment by trotyl** [comment]
@jhonyourangel The design can make sure each `HttpInterceptor` does only one-time transformation. So that an interceptor cannot observe the further operation of other interceptors, and cannot change the value asynchronously.

And using `HttpHeaders` is not required outside `HttpInterceptor`, just using plain object and do whatever you want.

**Comment by jhonyourangel** [comment]
Then don’t name it  .append

**Comment by trotyl** [comment]
@jhonyourangel So would [`push`](http://facebook.github.io/immutable-js/docs/#/List/push) and [`insert`](http://facebook.github.io/immutable-js/docs/#/List/insert) be better naming?

Try read the [immutable-js](http://facebook.github.io/immutable-js/docs/#/) APIs you'll understanding it's related to naming.

**Comment by bitixel** [comment]
this is what you came for...
```
let header = new HttpHeaders();
header = header.set('abc','22');
console.log(header.get('abc'));
```

**Comment by chankibiswas** [comment]
Hi, 

I might have a fresh problem. Thanks in advance to anyone who tries to help.

When I'm setting CORS header in following way, I'm getting the header parameter as a value of "Access-Control-Request-Headers".

Code for setting CORS header - 
const httpHeaders = new HttpHeaders().set('Access-Control-Allow-Origin', '*');

Request header - 
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Access-Control-Request-Headers: access-control-allow-origin
Access-Control-Request-Method: GET
Connection: keep-alive
Host: localhost:8080
Origin: http://localhost:4200
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36



If in the code, I replace 'Access-Control-Allow-Origin' with 'Test', the value of 'Access-Control-Request-Headers' comes as 'Test'.

Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Access-Control-Request-Headers: test
Access-Control-Request-Method: GET
Connection: keep-alive
Host: localhost:8080
Origin: http://localhost:4200
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36


It seems very weird to me and I have no clue to solve it.

P.S. - I'm using Angular 6.

**Comment by mlc-mlapis** [comment]
@chankibiswas ... CORS is just a server side config. You can't do anything on a client side for it.

**Comment by chankibiswas** [comment]
@mlc-mlapis 
I'm trying to make a GET request in the server side and getting the following error.

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 403.

So, I guess I need to add in the client side. Please correct me if I'm wrong.

**Comment by mlc-mlapis** [comment]
@chankibiswas ... yes, you are wrong. I can just repeat, that all changes in config are related to a server side (concrete steps depends on the concrete type of the server ... different servers mean usually different places or syntax). You shouldn't do any extra things on a client side to get it work.

**Comment by chankibiswas** [comment]
@mlc-mlapis:

But i'm trying to request from my UI which is in angular, to server side Rest api. So, request from client to server.
Hope I'm clear with my explanation.

**Comment by mlc-mlapis** [comment]
@chankibiswas ... I am sure that I understand what you are doing. This theme was on the table hundreds time here as different issues (but no issues in fact) ... on Gitter channel, ... and the answer is still the same ... it's just a server side thing. You have to correctly config it. That's all. Client side is hard coded directly in binary code of each browser ... to satisfy what specs are requiring.

Read to docs for your server how to do it. Search around old and closed issues, ...

**Comment by chankibiswas** [comment]
@mlc-mlapis 
So, when I say client side, I mean the UI part which is in Angular. It is making requests to server side Rest APIs, which is in Java, Spring boot.
I've checked it multiple times that the request doesn't make it to Server side (My Java code). So, how can a change in server side make any difference?

Sorry, I'm a server side coder and it's my first time coding with Angular. A little more clarity would really help.

**Comment by ro-damasceno** [comment]
Since the HttpHeaders returns a new instance every time you call .append or .set, you should make something like this: 

`
export class MyClass {
         protected headers: HttpHeaders = new HttpHeaders();

         addHeader(key: string, value: string) {
              this.headers = this.headers.append(key, value);
        }

        setHeader(key: string, value: string) {
              this.headers = this.headers.set(key, value);
        }

        getHttpHeaders() {
            return this.headers;
       }
}
`

**Comment by Tianny** [comment]
Since the HttpHeaders returns a new instance every time you call. So call append immediately after <code>new HttpHeaders()</code

```ts
  constructor(private httpClient: HttpClient) {
    const customHeaders: HttpHeaders = new HttpHeaders().append('customHeader', 'customHeaderValue');
    this.dataSource = this.httpClient.get('http://localhost:8000/api/products', {headers: customHeaders});
  }
```
