### ISSUE TITLE
Lazy Load for Prod? 

### ISSUE THREAD

**Issue by diegofalciola** [angular/angular#19045]
Hi @mgechev,
  Are there any plans to merge branch "lazy" into master / implement lazy loading for production any time soon?

Thanks

**Comment by mgechev** [comment]
@diegofalciola that's a wrong channel for communication. Probably you want to open an issue at [mgechev/angular-seed](https://github.com/mgechev/angular-seed).

**Comment by pkozlowski-opensource** [comment]
Thnx @mgechev

**Comment by diegofalciola** [comment]
I'm sorry, not sure how it ended up here :)
Thanks
