### ISSUE TITLE
Multiple sync and async combined conditions in *ngIf does not work as spected.

### ISSUE THREAD

**Issue by PCASME** [angular/angular#19047]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Having a component with this public variables:
<pre><code>
loading: boolean;
items: Observable<[]>;
</pre></code>
and this template:
<pre><code>
&lt;div *ngIf="!loading && (items | async)?.length == 0"&gt;No items found&lt;/div&gt;
&lt;ul&gt;
    &lt;li *ngFor="let item of items | async"&gt;{{item.name}}&lt;/li&gt;
&lt;ul&gt;
</pre></code>

## Expected behavior
Show the message "No items found" when stop loading the items (loading variable is set to false) and items array is empty.

## Minimal reproduction of the problem with instructions
See code above.

## What is the motivation / use case for changing the behavior?
Multiple sync and async combined conditions in *ngIf

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version 60.0.3112.113
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2
- Platform:  Windows 10, Mac OS Sierra

</code></pre>

**Comment by chuckjaz** [comment]
@PCASME Can you provide a plunker or a stackbliz link that demonstrates the issue you are having?

**Comment by PCASME** [comment]
Sorry for the delay...
Here the StackBitz: https://stackblitz.com/edit/angular-19047

It seems that the code works as expected.
Surely it was some error of mine when using the async pipe.

Sorry and thanks.
