### ISSUE TITLE
how to use bypassSecurityTrustScript

### ISSUE THREAD

**Issue by alanhg** [angular/angular#19052]
## bypassSecurityTrustHtml
`bypassSecurityTrustHtml` can guarantee the normal implementation of HTML, but JS does not execute, if I hope HTML run normaly include JS,how to do it?
code like this
```html
<h1 style="color: red" class="btn">
hello world
</h1>
<!-- /.box --><div id="hello"></div>
<!--<embed src='http://player.youku.com/player.php/sid/XMjk1Nzc0MjYxNg==/v.swf' allowFullScreen='true' quality='high' width='480' height='400' align='middle' allowScriptAccess='always' type='application/x-shockwave-flash'>-->

<!--</embed>-->
<hr>
<script>alert('hello')</script>
<hr>
```

And I think security chapter is not clear! 
Link is here [click it](https://angular.io/guide/security)

## bypassSecurityTrustScript
If I do not consider HTML, just want to run JS , And how to use bypassSecurityTrustScript?

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
