### ISSUE TITLE
Angular Routing seems to reload page

### ISSUE THREAD

**Issue by jeremy-seipelt** [angular/angular#19051]
## I'm submitting a

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Dynamically bootstraped angular doesn't use the routing like it should.
When I change states the page gets reloaded. 
I try to set up server side rendering and use AOT compiled angular.

## Expected behavior

Angular should'nt reload the page when you use an "a" tag with an "routerLink" attribute atleast.

## Minimal reproduction of the problem with instructions

Here is the current repo: https://gitlab.com/zmb-lab/Proof_of_Concept_for_SSR

Install the dependencies and run

    $ gulp build

You need to remove my preventDefault event to see the default behaviour.
   
## What is the motivation / use case for changing the behavior?
If you use the angular-router components you should use the router instead of regular html navigation.

## Environment

<pre><code>
Angular version: 4.3.6

For Tooling issues:
- Node version: 8.2.1  
- Platform:macOS  

</code></pre>

**Comment by jasonaden** [comment]
It looks like this is a Universal issue, based on the info provided.

**Comment by thorsten** [comment]
We have the same issue, we use AOT, but no SSR.

**Comment by AndrewKushnir** [comment]
Hello everyone,

We wanted to share that the full application non-destructive hydration would be available in the [developer preview](https://angular.io/guide/releases#developer-preview) mode in the upcoming v16 release of Angular! See additional information in https://github.com/angular/angular/issues/13446#issuecomment-1512125629.

The non-destructive hydration should resolve the issue with the content flickering and loading resources twice. Feel free to open a new ticket if you notice any issues with the new non-destructive hydration.

Thank you.
