### ISSUE TITLE
Links not working for Angular live examples 

### ISSUE THREAD

**Issue by MickeySegal** [angular/angular#19056]
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Links for live examples in Angular tutorial such as https://angular.io/generated/live-examples/toh-pt6/eplnkr.html are broken.  One gets the message:
`{"message":"An internal server error occurred","statusCode":500,"error":"Internal Server Error"}`
## Expected behavior

Loading the live example on Plunker

## Minimal reproduction of the problem with instructions

Click the live example link on https://angular.io/tutorial/toh-pt6.  The link is https://angular.io/generated/live-examples/toh-pt6/eplnkr.html

## What is the motivation / use case for changing the behavior?

It used to work.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
It seems like a plnkr issue. The `eplnkr.html` files contain code like the following:

```html
<html>
  <body>

    <form id="mainForm" method="post" action="https://embed.plnkr.co/?show=preview">
      <input type="hidden" name="source[type]" value="Example Description" />
      <input type="hidden" name="source[url]" value="https://angular.io" />
      <input type="hidden" name="entries[index.html][content]" value="..." />
      <input type="hidden" name="entries[index.html][encoding]" value="utf8" />
      <input type="hidden" name="entries[main.js][content]" value="..." />
      <input type="hidden" name="entries[main.js][encoding]" value="utf8" />
    </form>

    <script type="text/javascript">
      document.getElementById('mainForm').submit();
    </script>

  </body>
</html>
```

That part (creating the form and submitting it to `https://embed.plnkr.co`) works as expected and is supposed to dynamically create a new plnkr. It seems that plnkr is having internal server issues.

(FTW, dynamically creating new plnkrs against `https://plnkr.co/edit/` (which is used in the [AngularJS docs][1]) still works. Note: This requires different syntax.)

[1]: https://docs.angularjs.org/api/ng/function/angular.copy#example

**Comment by ericmartinezr** [comment]
@gkalpak how about starting to move examples to stackblitz? :D

**Comment by gkalpak** [comment]
@ericmartinezr, not for me to decide :grin:

**Comment by gkalpak** [comment]
The live examples are back up now.
