### ISSUE TITLE
Prevent the value parsing in FormControl of type=number

### ISSUE THREAD

**Issue by aldo-roman** [angular/angular#19053]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When a FormControl is declared of `type=number`, its value is always parsed and accessed as a number.
Check:
https://github.com/angular/angular/blob/master/packages/forms/src/directives/number_value_accessor.ts

## Expected behavior
I would like an opt-out mode, so a FormControl of `type=number` does not get parsed.
Perhaps adding a separate attribute would do.

## What is the motivation / use case for changing the behavior?
When using `type=number`, the parse strips out any left-leading zeros.
In my app, we need to get the DOI of our user, which may strat with a zero, so:
1. The user inputs `00001234`
2. The validator gets `1234` and is invalid due to being 4 instead of 8 characters.

My workaround is use `type=text` but displays alphabetic keypad on mobile browsers.

## Environment
<code><pre>
@angular/cli: 1.3.2
node: 8.4.0
os: win32 x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.10
@angular/cli: 1.3.2
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/compiler-cli: 4.3.6
@angular/core: 4.3.6
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/language-service: 4.3.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/service-worker: 1.0.0-beta.16
</code></pre>

**Comment by kara** [comment]
@aldo-roman Thanks for taking the time to describe your issue. This use case sounds a bit too specific for including in core (we are trying to keep our core modules as lean as possible), but there is already a way to implement this in your app. If you create a custom value accessor (in your case, probably an attribute dir that matches number inputs), you should be able to parse the value however you like. In the future, parser/formatter functionality will make this process easier, but for now, creating a value accessor should accomplish what you need.

**Comment by aldo-roman** [comment]
Thanks! I will take a look at value accessors. It's curious I was just reviewing the parser/formatter issue here #3009
