### ISSUE TITLE
data-src converted to src on img tag

### ISSUE THREAD

**Issue by lzychowski** [angular/angular#19054]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

 `data-src` attribute on an `img` tag is converted to `src` attribute when template variable is present

## Expected behavior

`data-src` should not be changed to `src` by angular.

## Minimal reproduction of the problem with instructions

See https://plnkr.co/edit/pzxTaBEG4LbFsRxaj783?p=preview

```
@Component({
  selector: 'my-app',
  template: `
    <div>
      <img data-src="{{img_url}}">
      <img data-src="https://placehold.it/350x250&text=11">
    </div>
  `,
})
export class App {
  name:string;
  constructor() {
    this.img_url = "https://placehold.it/350x250&text=11";
  }
}
```
First `img` tag's `data-src` attribute will be converted to `src`.

## What is the motivation / use case for changing the behavior?

Behavior is breaking integration with owl.carousel2 lazy load functionality.

## Environment

<pre><code>
Angular version: 4.4.0-RC.0

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Currently it works as expected as we are stripping the `data-` prefix in the compiler (the idea behind this was that people could prefix non-standard attributes with bindings). We should probably revisit this but for now you can use explicit attribute binding (`[attr.data-src]="'attr value'"` or `[attr.data-src]="exp"`).

**Comment by lzychowski** [comment]
That worked for me.

Thanks
