### ISSUE TITLE
Tracking issue: Angular BuildTools Convergence (ABC)

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#19058]
We are open-sourcing the toolchain we use internally at Google to build Angular apps at scale.

One-pager: http://g.co/ng/abc

This issue will be used to give updates on progress.

FAQ: how does this relate to Angular CLI? We will evaluate this toolchain with some early adopters first, if it goes well, we will evaluate whether to use it inside the CLI. So long as you haven't ejected from the CLI, such a change should be transparent to users.

**Comment by zh99998** [comment]
sounds like a big news.
will angular-cli moves to ABC and drop recommend of current webpack-based build system ?

**Comment by realappie** [comment]
Looks promising !

Is this going to kill the angular CLI? And will it eventually be a drop in replacement for codebases built with the angular CLI?

**Comment by mlc-mlapis** [comment]
@realappie  Angular CLI is a top layer so it should not be affected a lot but some changes probably could be.

**Comment by alexeagle** [comment]
Updated the description above. It's possible this could be the build system in the CLI one day, but too early to be sure.

**Comment by alexeagle** [comment]
Update: we are starting to accept enterprises in an Early Access Program, to try this out with support from our team.
If you are willing to tolerate risk, missing documentation, and commit to giving feedback, then we'd like to have you use this soon. Fill out https://goo.gl/forms/Tv8lMdH0N3D4yo8Q2 and I'll get in touch once we are ready to support your use cases.

**Comment by crutchcorn** [comment]
Is there any way for individuals to sign up for this program rather than corporations?

**Comment by alexeagle** [comment]
You can fill out the form, but we're interested in applications with
thousands of source files that suffer from slow builds under Angular CLI,
so we might not have capacity to take your use case.

**Comment by GoNode5** [comment]
@alexeagle could you define in time/seconds what you think is a slow build. The fact that the Angular platform degraded JIT, to a old fashioned build/compile/link time experience, even with small projects, I don't know what to expect.  The reason I chose Javascript is because of JIT, wich I don't enjoy anymore in relation to Angular. AngularJS jit was F5 refresh build.  Now ng build --prod is something to execute is low as possible, even with 'small ish?' projects.

**Comment by schmitch** [comment]
I doubt that AnulgarJS jit was F5 refresh + build.
Either your browser loaded for some seconds or it took at least seconds to actually concat all the files.
AOT is the same, than any concat, just that it is more clever which will reduce the browser loading time.

**Comment by mlc-mlapis** [comment]
@GoNode5 ... actually you can have dev time which is < 1 second = you just don't wait at all.

Another story is the whole building to produce some real a completely new build for production or testing server (which is just internal version = the last step before production).

**Comment by alexeagle** [comment]
Our goal is <2s dev roundtrip (50%ile) for a large project, O(thousands) of source files.

**Comment by GoNode5** [comment]
@schmitch You can doubt what you want just look at a hello world ng serve size Angular project... CCompared to AngularJS F5 (cache disabled) . I could add 600KB Angular Code but that wouldn't change much. 
![image](https:// user-images.githubusercontent.com/2210672/33186405-a69f6868-d089-11e7-9684-a0697a945c32.png)

**Comment by schmitch** [comment]
61 requests means that your project was really really small.
if you used systemjs and had 61 requests in a typical angularjs project it means you basically created hello world.
the other route was gulp/grunt and concat everything even that took a while for a decent sized project (more than 200 files js+html)

**Comment by alexeagle** [comment]
Update: we now have a basic devserver ready to try out. I updated the README: https://github.com/alexeagle/angular-bazel-example

The purpose of this devserver is:
- make a very easy getting-started experience, where you just add a `ts_devserver` rule that points to your app sources
- a reference for benchmarks, because this devserver just concatenates the JS sources it scales very well

Much of the smarts are actually in `ibazel`, so it will be pretty easy to swap it out for some other devserver, like webpack, express, or even your Java or PHP backend, etc. We will write some documentation about how to make those other devservers work with `ibazel`.

Thanks to @gregmagolan for most of the work here.

see the [earlier comment](https://github.com/angular/angular/issues/19058#issuecomment-346145316) if you would like official support for using this.

**Comment by mattem** [comment]
@alexeagle That's awesome! My team has already signed up the EAP, and I will definitely explore the example you published further. 
A few questions from a quick glance through it.
* Is there support for using `templateUrl` instead of having the template inline for the component?
* Using a reference to the sass file in `styleUrls` instead of the generated CSS file. Some IDEs (Webstorm for example) have editor support for clicking through to the file there, which is lost when using the css extension.
* Rewriting the `main.ts` file to automatically include the import and bootstrap of the `AppModuleFactory` (like the angular CLI), same as the point above really, the editor picks this up as files importing a file that does not exist.

**Comment by alexeagle** [comment]
Yes, `templateUrl` works just as well as `template`. This just runs `ngc` so all the usual caveats apply from Angular development in some other build toolchain like the CLI.

The `styleUrls` is a good point. It's subtle, because we don't want to magically re-write the file, and by the time Angular's compiler sees the component, there is no longer a .scss file to read. I think the best solution is to omit the extension on style files, just as we do for referencing `.ts` vs `.js` files. It means tools would need to know to look for both, and that means we'd need editor support to evolve. It's a stretch.
The simpler answer is to teach Angular to look for `foo.css` if it can't find `foo.scss` but I think this isn't a general solution because the `scss_binary` rule can produce an output file with a different name from the input.

Importing generated code looks strange, but this is idiomatic in Bazel, and it's what we do internally at Google. However, this particular problem will go away in Angular 6 - the plan is that the factory will be emitted as a static property of the Component class, and so you'll be able to just import the component and we'll know how to resolve the factory from that at runtime.

**Comment by alexeagle** [comment]
It's a big week for ABC launches - we now have browser unit testing using Karma included in the example app. See the spec file

https://github.com/alexeagle/angular-bazel-example/blob/master/src/hello-world/hello-world.component.spec.ts 

and the test target

https://github.com/alexeagle/angular-bazel-example/blob/c0fec902ce74e2ee00b194c7fad9fb5e056a4050/src/hello-world/BUILD.bazel#L37-L45

I also did a major pass over the documentation, adding the devserver, karma testing, formatting, CI, and more. https://github.com/alexeagle/angular-bazel-example/wiki

**Comment by alexeagle** [comment]
Another launch announcement: we have a `rollup_bundle` rule you can use to create a production bundle. See https://github.com/bazelbuild/rules_nodejs#bundlingoptimizing for the doc and https://github.com/alexeagle/angular-bazel-example for an example usage.

At this point we are just missing code-splitting/lazy-loading and Windows support, to have feature parity with Angular CLI.

**Comment by artaommahe** [comment]
> At this point we are just missing code-splitting/lazy-loading and Windows support, to have feature parity with Angular CLI.

what about webpack features like inlining images in ts-files via require + loaders?

**Comment by alexeagle** [comment]
@artaommahe good point, there's probably a long tail of features I'm not aware of. We have solutions for all these things at Google so it's just a matter of finding the idiomatic way to do it, and measuring the demand for which features to add when.

**Comment by schmitch** [comment]
Does this use Closure for the end bundle or still use js tooling?

**Comment by alexeagle** [comment]
The canonical example currently uses Rollup/Uglify, but we also have a work in progress to use Closure Compiler, and I've seen some examples of using Webpack.

**Comment by hiepxanh** [comment]
thank you so much 😍  , that is a lot of information. I will enjoy it just like my favorite movie series and waiting for team's full release 😸

**Comment by martyganz** [comment]
@istiti please see the new features part of @alexeagle's comment up here.

He linked this: https://medium.com/@gregmagolan/production-code-splitting-with-bazel-8a7da242bf83

Looking at Alex's example repository will maybe also help you get started: https://github.com/alexeagle/angular-bazel-example

But please keep in mind that Bazel still might have breaking changes whereas your cli setup will work out of the box :).

**Comment by istiti** [comment]
@martyganz obviously already checked that 2 months ago, thanks but still out of scope to move from cli project. But you are right I should wait for `ng add @angular/bazel`

**Comment by johnbendi** [comment]
`sandbox` symlink to `execroot` does not include `ngfactory` files. More specifically, `ngfactory` and `ngsummary` files exists for material module at `execroot` but only `ngsummary` are symlinked into the `sandbox` which leads the build to fail with:
```
: Error: Could not resolve ./index.ngfactory from /home/johnbendi/.cache/bazel/_bazel_johnbendi/a78f499bf50e18fa3ff9c74610609e4a/sandbox/linux-sandbox/15/execroot/betadeals_frontend/node_modules/@angular/material/card/typings/index.d.ts
: Cannot determine the module for class AppFooterComponent in /home/johnbendi/.cache/bazel/_bazel_johnbendi/a78f499bf50e18fa3ff9c74610609e4a/sandbox/linux-sandbox/15/execroot/betadeals_frontend/src/ts/ng/client/app/components/app-footer/app-footer.component.ts! Add AppFooterComponent tothe NgModule to fix it.
```

**Comment by mattem** [comment]
@johnbendi I experienced the same issue, opened an issue in the example repo but haven't had anything back yet. 
https://github.com/alexeagle/angular-bazel-example/issues/159

**Comment by alexeagle** [comment]
Update time!

- The early access program has kicked off with 8 enterprise users. We aren't looking to provide more direct support right now.
- Early version of [ts_auto_deps](https://github.com/bazelbuild/rules_typescript/tree/master/ts_auto_deps) which automatically creates/maintains BUILD files in subdirectories
- Angular rules now have API documentation. http://angular.github.io/bazel-builds
- [Protractor rule](https://angular.github.io/bazel-builds/src/protractor/protractor_web_test.html) is available.

We are beginning serious design work on making Bazel part of the Angular CLI. As a reminder, this is *not* an alternative to Webpack. You can imagine Bazel as a layer sitting between the Angular CLI and calls to Webpack, avoiding re-doing the Webpack work where possible, and parallelizing Webpack via the DLLPlugin.

**Comment by glebmachine** [comment]
Jesus, can't wait for it!

**Comment by alexeagle** [comment]
Update for September:

- Code splitting and lazy-loading has landed! Read Greg's blog post at https://medium.com/@gregmagolan/code-splitting-and-lazy-loading-with-bazel-9b11ac4de20b
- We now have a guide for adding a Bazel build to an existing Angular CLI application: https://github.com/alexeagle/angular-bazel-example/wiki/Converting-an-Angular-CLI-workspace (note that this forms the basis for an `ng add @angular/bazel` schematic which we hope to add soon)
- Angular is now using Remote Build Execution for one step in our own build. Preliminary results show a 2-3x speedup in build times. Next we are adding remote caching so that our build is truly incremental and massively parallel.
- We have confirmed that a few companies are using this stack now.

We have a significant improvement coming soon in the internals of how we interact with the npm ecosystem that should help with performance and ergonomics, should be in the next update.

**Comment by alexeagle** [comment]
Update from October:

- Bazel is published on npm at https://www.npmjs.com/package/@bazel/bazel - as a result, installing Bazel is no longer a requirement. Our plan is that a developer either installs nodejs/npm/yarn, or Bazel, but no one needs to install both. As proof, Angular's own CI build now runs on a vanilla nodejs container. Note that the Bazel team plans to reduce the size of the binary.
- The nodejs rules now create Bazel build files for each installed npm package. This means that individual Bazel actions can declare "fine-grained" dependencies on which npm packages they need, and makes builds faster by reducing how many input files are needed.
- I gave a talk at AngularMix (it wasn't recorded). I demo'ed a side-by-side of building Angular itself both using local resources on a 16-core machine, and with a remote build execution farm. The latter is an order of magnitude faster. I also showed a preview of "builder" support for Bazel under Angular CLI - on Windows we can `ng serve --prod` and everything including lazy loading works, and runs on Bazel
- @mprobst gave a talk about Bazel at Angular Connect, https://www.youtube.com/watch?v=Qb3tykleV_g
- We are working on Schematics for using Bazel that will be part of the `@angular/bazel` npm package.

**Comment by angryagr** [comment]
Hi,
is it possible to integrate Angular and j2cl. J2cl provides closure files. Can I access the files? Thanks.

**Comment by mgechev** [comment]
Updates from November / early December:

1. We have `ng add` schematics for Angular CLI. This feature is in a *very early stage* but it'll allow more folks to give a try building Angular with Bazel. Find the commit, which introduced the change [here](https://github.com/angular/angular/commit/06d4a0c46ed45cb8861d41a2627798fa6885358a).
1. It's possible to use remote caching with Bazel today! We enabled experimental support in the Angular repository. To reduce latency to the minimum, we'd strongly recommend having the cache in the same network. Check out the setup we did for `angular/angular` [here](https://github.com/angular/angular/pull/27358).
1. We published Bazel's BUILD file formatter and editor as an npm package under `@bazel/buildifier`. Here's the [PR](https://github.com/bazelbuild/rules_nodejs/pull/456).
1. Faster TypeScript compilation by caching of the `ts.Program`. For details see the [commit](https://github.com/bazelbuild/rules_typescript/commit/7cc3475c06aa3dee491e4ef7aafc54ec7b29e458).

**Comment by mgechev** [comment]
Here are further details for what happened in February:

- We no longer depend on the Go toolchain! You might have noticed that the initial build of projects bootstrapped with `@angular/bazel` was quite slow. Well, we used to build the entire Go compiler the first time you run `ng build`. We no longer do that! Instead, we distribute the Go binaries directly.
- We no longer build Angular and Angular Material from source code! This should help you have faster cold build as well.
- If you’ve tried `@angular/bazel` you’ve probably hit the problem that your `@bazel/typescript` version in `package.json` should be the same as the one of the TypeScript rules in your `WORKSPACE` file. You’ll no longer hit this issue! We’re now reusing the rules distributed in `@angular/bazel` so there will be only a single version of them in your project.
- You can find a cool demo of incremental deployment of Angular projects with Kubernetes [here](https://github.com/angular/angular-bazel-example/pull/295/files).
- We conducted Bazel training for the Angular team. You can find the slide deck [here](https://docs.google.com/presentation/d/1OwktccLvV3VvWn3i7H2SuZkBeAQ8z-E5RdJODVLf8SA/preview). Contact us directly if you’re planning to use the deck for training. We’d love to help you be successful and give you more materials/guidelines! Feel free to reach out to me at mgechev@google.com.

**Comment by mgechev** [comment]
Updates for March:

⚡️ **Faster builds**

Previously, using Bazel required building dependencies from sources, such as Angular itself, Material components, and so on. This took a lot of memory and time for the initial build.

We now build Angular applications following the same standard development workflow you’re used to:

- Install dependencies from npm
- Add Angular compiler outputs during the build
- Compile just your source files

👨🏻‍🔧 Better support in Angular CLI
You can add Bazel to your existing project with ng add @angular/bazel@next. The Bazel builder supports CLI applications using the standard build capabilities. For lazy-loading support, you should eject (see below) and alter the functionality.Bazel files (WORKSPACE, BUILD.bazel, etc) are now hidden by default. This makes the transition to Bazel less confusing for users who are new to Bazel. Familiar CLI commands like ng build would continue to work as before.For users who want more control over Bazel configuration, Bazel files could be exposed by running ng build --leaveBazelFilesOnDisk.Unlike the old workflow, ng build under Bazel would produce a prod bundle by default.

🧪 Bazel examples

- We’ve been working on improving the Bazel [example](https://github.com/angular/angular-bazel-example). We introduced differential loading and more robust lazy-loading mechanism using dynamic imports
- We built a demo of the Angular Real World Example application with Bazel

✨ **Tips and tricks**

*Consuming non-UMD bundles in development*

In the example applications, you might have noticed that we’re using UMD bundles in ts_devserver. Frequently we get asked how to use non-UMD bundles. You can achieve this with requirejs. For sample configuration, check this [link](https://github.com/angular/angular-bazel-example/blob/master/src/require.config.js). Currently, we’re working on a more robust way for consumption of non-UMD dependencies.

**Comment by toxik** [comment]
hey, tried to `ng add @angular/bazel@next` but I get the error
```
Schematic input does not validate against the Schema: {}
Errors:

  Data path "" should have required property 'name'.
```

**Comment by mgechev** [comment]
You need to specify the project name with the `--name` command line option.

**Comment by mgechev** [comment]
Updates from April & May:

💥 Angular CLI Bazel opt-in preview

On ng-conf Alex Eagle announced the official opt-in preview of Bazel in Angular CLI! You can give it a try today with the @angular/bazel schematics. For more information, check our new guide on angular.io.

💬 Conference presentations

You can find the ng-conf talk “The Bazel Opt-in Preview is Here!” by Alex Eagle
Alex and Danna Kelmer from the Bazel team spoke on Cloud Next about “Building Web Apps like Google”
Brad Green talked about Bazel during the ng-conf keynote. He also mentioned two of the companies who’re currently building their entire stack with Bazel!
Alex presented this talk also on Google I/O 2019!

✋ Support program

We resumed the enterprise support program! If your company is building a large Angular application and you think that Bazel might be a good fit for you, let us know! We’d love to look at your use case and help you get started. If you want to join, fill this form or respond to this email directly.

💫 New landing page

We created a landing page for Bazel with Angular and published it at bazel.angular.io. There you can find links to documentation, resources, examples, and more! The latest version of the Angular Bazel example is available at bazel.angular.io/example.

👌 Smaller binary

The Bazel team has been working hard to reduce the binary size. Currently, Bazel is below 80MB, and we’re expecting even smaller binary in future releases!

**Comment by bunnyvishal6** [comment]
Why this repo not using Google Cloud Build instead of Circle CI?

**Comment by manekinekko** [comment]
Hey @bunnyvishal6 any particular reason why you are asking this?

**Comment by bunnyvishal6** [comment]
@manekinekko  no particular reason. But as Google Cloud Build getting better, and Angular is also lead by Google, I wonder why it isn't using its own product?

**Comment by sgammon** [comment]
@mgechev / @alexeagle - we are very excited on the progress here, we are an existing Bazel-based company (in part) and we want to pick up angular. is there any substantive update for June or July? we filled out the form as well - RBE support sounds fantastic and we’re already in the alpha there too.

**Comment by mgechev** [comment]
Here are few updates from June!

**📚 Articles**

We posted an [article](https://blog.angular.io/try-bazels-opt-in-preview-in-angular-cli-b9430bd00e82) announcing the Bazel’s opt-in preview. In the post, you can find instructions on how to bootstrap your first Bazel project with the Angular CLI and what are our plans for the next quarter!

Pssst, here’s how to give Bazel a try today:

```
ng new app --collection=@angular/bazel
```

🧰 **Tools**

Create a new Bazel workspace with [@bazel/create](https://www.npmjs.com/package/@bazel/create). Yarn and npm have a shortcut that lets you install a package and invoke a binary using a single command! You can bootstrap a new JavaScript Bazel workspace using:

```
npm init @bazel app
```

Or using yarn:

```
yarn create @bazel app
```

Read more about [npm init](https://docs.npmjs.com/cli/init) and [yarn create](https://yarnpkg.com/en/docs/cli/create).

**📈 Statistics**

Bazel’s adoption has been growing! Here are some numbers from npm:

<table>
  <tr>
   <td><strong>Package name</strong>
   </td>
   <td><strong>Weekly downloads</strong>
   </td>
  </tr>
  <tr>
   <td><a href="https://www.npmjs.com/package/@bazel/typescript">@bazel/typescript</a>
   </td>
   <td>13,723
   </td>
  </tr>
  <tr>
   <td><a href="https://www.npmjs.com/package/@angular/bazel">@angular/bazel</a>
   </td>
   <td>5,964
   </td>
  </tr>
  <tr>
   <td><a href="https://www.npmjs.com/package/@bazel/bazel">@bazel/bazel</a>
   </td>
   <td>5,912
   </td>
  </tr>
</table>

And [rules_nodejs](https://github.com/bazelbuild/rules_nodejs) have over 158,911 downloads since we started the project!

See you next month!

**Comment by bleuscyther** [comment]
@mgechev , thx for the update. What would be a good guide to migrate old projects to bazel? If i start a new one it works perfectly, but i was not able to finish the migration for one of my old ones  2 weeks ago. I would like to give it another go.

**Comment by mgechev** [comment]
There's no such guide yet. You can find a sample application in the [Angular Bazel Example](http://github.com/angular/angular-bazel-example).

I also migrated the [Real World Angular Example](https://github.com/mgechev/real-world-bazel) by the StackBlitz folks.

**Comment by glebmachine** [comment]
Waiting bazel support for stylus!

**Comment by marcus-sa** [comment]
Support for LESS would be great as well!

**Comment by mgechev** [comment]
For August we have a few updates, but most actionable recently!

- New rules for Less - https://github.com/bazelbuild/rules_nodejs/pull/1017
- New rules for Stylus  https://github.com/bazelbuild/rules_nodejs/pull/908
- Better npm module support - https://github.com/bazelbuild/rules_nodejs/pull/997
- Automatic `rollup_bundle` code splitting  https://github.com/bazelbuild/rules_nodejs/pull/839

**Comment by mgechev** [comment]
We have two major Bazel updates for you today!
 
🎉 **Bazel 1.0 is out!**
 
Few key features of the 1.0 release are:

- Semantic Versioning
- Long-Term Support
- Well-rounded features for Angular, Android, Java, and C++

You can read more in the [official announcement](https://opensource.googleblog.com/2019/10/bazel-reaches-10-milestone.html) on the Google Open Source blog. Additionally, you can find a gentle introduction to Bazel and its experimental integration with the CLI in this community post by Ignacio Le Fluk "[Angular + Bazel: Getting ready!](https://dev.to/thisdotmedia/angular-bazel-getting-ready-4b0i)".
 
📣 **Enhanced JavaScript support**
 
Talking about well-rounded features for Angular, Bazel can now run pretty much any module with an executable from npm! You can directly load the binary in your BUILD file and execute an automatically generated rule. For example, you can start an http server with the following short snippet:

```python
load("@npm//http-server:index.bzl", "http_server)

http_server(
    name = "server",
    data = [
        "index.html",
        "app.es5.js",
    ],
    args = ["."],
)
```
 
Read more about the first-class JavaScript support in this [post](https://dev.to/jakeherringbone/layering-in-bazel-for-web-389h) by @alexeagle.

**Comment by glebmachine** [comment]
@alexeagle you added bazel/stylus rule, but, it still unsupported by @angular/bazel builders
Could you please add stylus[, less] support to angular/cli

Looking forward to migrate to bazel toolchain : )

**Comment by afifalfiano** [comment]
Hallo, i'm beginner using bazel on windows, do you know what this problem? and any solution?

![how](https://user-images.githubusercontent.com/47497276/78531538-cdc05d00-780f-11ea-9a55-eaa803340085.jpg)

**Comment by petebacondarwin** [comment]
@afifalfiano - I propose that your core Angular libraries have not been compiled by ngcc to be consumable by the Angular ivy compiler. This is managed for you with the Angular CLI. I don't know much about how it is done if using Bazel directly. I suggest that you try running `ngcc` in your project root to compile all the `node_modules` packages.

**Comment by afifalfiano** [comment]
> @afifalfiano - I propose that your core Angular libraries have not been compiled by ngcc to be consumable by the Angular ivy compiler. This is managed for you with the Angular CLI. I don't know much about how it is done if using Bazel directly. I suggest that you try running `ngcc` in your project root to compile all the `node_modules` packages.

oke, absolutely i got soluction, when first i compile using ngcc and then i build this project using bazel run target, everything running well, but i have another problem, when i running ng serve, my project can't running cause ibazel cant find the file existing bazelisk

**Comment by alexeagle** [comment]
Update here: I published a blog post about Bazel support for Angular along with other frameworks, using an approach that relies less on Angular supporting any Bazel-specific bits.
https://dev.to/bazel/angular-bazel-leaving-angular-labs-51ja

**Comment by afifalfiano** [comment]
@alexeagle Hello Alex, how do I configure an angular environment with bazel? Before using bazel, I use file Replacement in angular.json? any idea?

**Comment by hiepxanh** [comment]
I just successful run the Bazel on my Windows computer, it really amazing, just wonder any kind of "getting start with Bazel and Angular". Because I already read the `BUILD.bazel` but not really family with it

**Comment by literalpie** [comment]
@hiepxanh I believe the best resource available is the example code [here](https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular). If you're looking for a tutorial or guide to get started, I don't think there's a particular one that stands out as the best.

I would recommend the sample code because it is maintained along with the nodejs rules, so it should always be up to date.

**Comment by alexeagle** [comment]
🥇 Here's the final update 🥇

I started this project three years ago with two ambitious requirements:
1. Provide a scalable toolchain for big companies like Google with massive apps beyond the limits of existing OSS tooling
2. Angular team maintains only one toolchain

I think we have reached the first goal. Angular + Bazel has left Angular Labs and has some production usage. We have been maturing this and just reached 2.0 of [rules_nodejs](https://github.com/bazelbuild/rules_nodejs), where this support is maintained, demonstrated, and [documented](https://bazelbuild.github.io/rules_nodejs/examples.html#angular).

However the second requirement is much harder. Angular must maintain the CLI and keep all users updated to the latest. Switching this to Bazel required making it adoptable by the most novice users on small projects. This is the "Convergence" in the project title. It's very hard and was only ever staffed by one engineer (@gregmagolan who's awesome), plus me in part-time.

We didn't achieve Convergence, so Angular team will continue to maintain only the CLI (and the underlying build system called "Architect" aka CLI Builders). You can choose to layer Bazel on top of that underlying build system, continuing to use Architect for compatibility as documented [here](https://bazelbuild.github.io/rules_nodejs/examples.html#angular); that means you can still use Angular-team-supported tooling under Bazel (though with limited benefits). Big thanks to @alan-agius4 for volunteering to support this option.

### What should you do?

If your project fits in Angular CLI, you should use it. Convergence isn't happening. Novice developers will never get the easy turnkey documentation and tools to switch. Bazel will never be the default, so we can close this issue.

Bazel has an on-ramp that requires understanding your build process in detail, and learning some new things like Bazel's configuration language. It's only suitable for projects where someone is willing to take the role of a build system engineer. I believe that extra-large-sized projects already have someone staffed to deal with deficiencies in the OSS toolchains, so in practice if you really need Bazel, you're probably a good fit to adopt it.

You can continue to follow our development in rules_nodejs, or join the `#angular` channel in http://slack.bazel.build

Thanks Angular community you are all awesome. Much ❤️
