### ISSUE TITLE
ResolveEnd urlAfterRedirects is defined as string, but is of type UrlTree

### ISSUE THREAD

**Issue by tiwieso** [angular/angular#19050]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/ZYPx27BgmIRVCjGGVKKZ?p=preview

Go to plunkr, 'Click me!' and take a look at the console.

## What is the motivation / use case for changing the behavior?

ResolveEnd defines the wrong type for the urlAfterRedirects-member.

</code></pre>

**Comment by squadwuschel** [comment]
I've the same Problem, it was working on Angular 4.04 but now with Angular 5 its not a string anymore and the Typing is also wrong! The Typing is  a string and at the Moment I have to use it so: 

       this.router.events.subscribe((url: NavigationEnd) => {
                     if (url && url.url && url.url.includes(this.sxpRouterLinkActive.routeIncludes) || (url && url.urlAfterRedirects && url.urlAfterRedirects["fragment"] && url.urlAfterRedirects["fragment"].includes(this.sxpRouterLinkActive.routeIncludes))) {
                    this.activeClassName = this.sxpRouterLinkActive.activeClass == undefined ? "active" : this.sxpRouterLinkActive.activeClass;
                } else {
                    this.activeClassName = "";
                }     
        });

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

**Comment by jasonaden** [comment]
Please check the current version of the router (`v5`) and file a new issue if needed.
