### ISSUE TITLE
Redirects with auxiliary route prevent further redirects

### ISSUE THREAD

**Issue by BaggersIO** [angular/angular#19069]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using named router outlets in `redirectTo` prevent further redirects. It's mandatory for redirects with auxiliary routes to define the redirect absolute ([apply_redirects.ts#L50](https://github.com/angular/angular/blob/master/packages/router/src/apply_redirects.ts#L50)). But using absolute paths prevents the router from evaluating further redirects ([apply_redirects.ts#L89](https://github.com/angular/angular/blob/master/packages/router/src/apply_redirects.ts#L89)).

**Without named outlets:**
```
       relative              relative              relative

App  - redirect 'a' ->  A  - redirect 'b' ->  B  - redirect 'b2'  =>  /a/b/b2
```

**With named outlets in between**
```
       relative              absolute

App  - redirect 'a' ->  A  - redirect '/a/(b//x:x)'  => /a/(b//x:x)
```

The second redirect to `b2` is missing.

## Expected behavior

Using auxiliary routes should not prevent further redirects. The expected result should be: `/a/(b/b2//x:x)`

With named outlets in between
```
       relative              absolute                         relative

App  - redirect 'a' ->  A  - redirect '/a/(b//x:x)'  ->  B  - redirect 'b2'  ->  /a/(b/b2//x:x)
```

## Minimal reproduction of the problem with instructions

Check out the Plunker to reproduce the bug: http://plnkr.co/edit/xhiQQtfMsLI05dBxNk2e?p=preview

The empty router-outlet in the demo illustrates the missing redirect to `b2`.

## What is the motivation / use case for changing the behavior?

Further (relative) redirects should work as expected, even with auxiliary routes.

## Environment

<pre><code>
Angular version: 4.4.0

Browser:
- [x] Chrome (desktop) version  60.0.3112.113
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
Operating System: MacOS Sierra
</code></pre>

**Comment by BaggersIO** [comment]
Ping @jasonaden :)

**Comment by jasonaden** [comment]
Thanks @BaggersIO. I've noted this as a feature request, as well as a docs issue. If you think you've found how to fix this, please send a PR and I'll take a look.
