### ISSUE TITLE
When running AOT in development mode SourceMap is missing

### ISSUE THREAD

**Issue by steveblue** [angular/angular#19076]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This error appears in the browser console when I put `ngc` in `--watch` mode and run Angular in development mode. 
`DevTools failed to parse SourceMap: http://localhost:4200/Users/misko/work/angular/dist/packages-dist/animations/bundles/animations.umd.min.js.map `

## Expected behavior

Browser is able to find source maps on my local machine.

## Minimal reproduction of the problem with instructions

`$ git clone https://github.com/steveblue/angular2-rollup.git`
`$ git checkout feature/5.0.0`
`$ npm link`
`$ cd ../`
`$ mkdir new-app && cd new-app`
`$ ngr scaffold --angularVersion 5.0.0-beta.6 && npm install`
`$ ngr build dev --watch --serve`

Observe issue in the browser.

## What is the motivation / use case for changing the behavior?

Browser should be able to find source maps on my local machine.

## Environment

<pre><code>
Angular version: 5.0.0-beta.6

Browser:
- [X ] Chrome (desktop) Version 60.0.3112.113 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.0
- Platform:  MacOS

Others:

</code></pre>

**Comment by vicb** [comment]
Should be part of 5.x (also depends in a fix in TS2.4)
