### ISSUE TITLE
AOT in --watch mode should honor --pretty for warnings and errors

### ISSUE THREAD

**Issue by steveblue** [angular/angular#19077]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Errors are monotone in terminal.

## Expected behavior

When using `--pretty` flag, `ngc` should pretty print errors similar to `tsc`

## Minimal reproduction of the problem with instructions

Add `pretty` parameter to "compilerOptions" in tsconfig and set to true. 

## What is the motivation / use case for changing the behavior?

When TypeScript outputs errors in the terminal the error is contextually highlighted and the word `error` is in red. This highlight grabs the attention of developers more than just the standard color of the terminal window.

## Environment

<pre><code>
Angular version: 5.0.0-beta.6

 
For Tooling issues:
- Node version: 6.9.0  
- Platform:  MacOS 

Others:

</code></pre>

**Comment by JoostK** [comment]
WIth Ivy, this looks to be the opposite. Diagnostics are printed with colors by default, but the `pretty` flag is not taken into account.

**Comment by alxhub** [comment]
Closing as resolved for the reason described by Joost - ngtsc only knows how to pretty-print diagnostics.
