### ISSUE TITLE
Spelling error in Angular docs

### ISSUE THREAD

**Issue by swirlsky** [angular/angular#19078]
## I'm submitting a...
[x ] Documentation issue or request

## Current behavior
wrong sentence: "// This component make a request but it can't actually delete a hero."

## Expected behavior
correct sentence: "// This component makes a request but it can't actually delete a hero."

## Minimal reproduction of the problem with instructions
see: https://angular.io/guide/template-syntax#custom-events-with-eventemitter

**Comment by gkalpak** [comment]
Good catch, @swirlsky. Would you be up to submitting a PR with the fix? 
([This is the line][1] you need to edit.)

[1]: https://github.com/angular/angular/blob/3c480e4e639df89b2b2a60c63060e1532eeb3beb/aio/content/examples/template-syntax/src/app/hero-detail.component.ts#L38

**Comment by aravindfz** [comment]
@gkalpak I have raised a PR fixing this [here](https://github.com/angular/angular/pull/19118)
