### ISSUE TITLE
router doesn't detect pushState

### ISSUE THREAD

**Issue by ahmedGomaa90** [angular/angular#19086]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)

## Current behavior
when using history.pushState(), the url changes but the router doesn't trigger at all

## Expected behavior
the router should be able to detect the url changes by using pushState as used to do in previous version (@angular/router 3.4.6).

## Minimal reproduction of the problem with instructions
just use history.pushState() for any route in your app

## What is the motivation / use case for changing the behavior?

Angular version: 4.2.4

Browser:
- [x] Chrome (desktop)

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by tamasfoldi** [comment]
Hi @jasonaden ,

I have created a reproduction, here you can access it. https://stackblitz.com/edit/angular-ywjq7t If you click on Login then click on PUSH STATE button you will see that the url changes but it does not loads the correct module.
