### ISSUE TITLE
ng build --prod  JavaScript heap out of memory

### ISSUE THREAD

**Issue by luomu172** [angular/angular#19082]
ng build --prod  JavaScript heap out of memory

why?   Solution？

**Comment by Toxicable** [comment]
Wrong repo
duplicate https://github.com/angular/angular-cli/issues/5618
duplicate https://github.com/angular/angular-cli/issues/7616

**Comment by luomu172** [comment]
Thank you very much.

**Comment by luomu172** [comment]
Thank you very much.
