### ISSUE TITLE
dynamically add output properties to an angular 4 component

### ISSUE THREAD

**Issue by almogk012** [angular/angular#19084]
[ ] Regressio
[ ] Bug report 
[ ] Feature request
[X ] Documentation issue or request

## Expected behavior

The goal of this module is to provide a generic table to use when we want to make some actions on some data. (for example: we can use this module to create a CRUD table)

What I want to do in the Angular2ActionableTableComponent is to dynamically add output properties according to the columns attribute. In other words, let's say the client has passed as input value this columns = [new Action('edit'), new Action('validate')]. So I want to make something similar to this in the Angular2ActionableTableComponent

**typescript classes:**
`
export class Column{
  constructor(public name: string) {
  }
}

export class Action {
  constructor(public name: string) {
  }
}
`

**component class**
`
import {Component, OnInit, Input} from '@angular/core';
import {Action} from "./models/action.model";
import {Column} from "./models/column.model";

@Component({
   selector: 'app-angular2-actionable-table'
})
export class Angular2ActionableTableComponent {

  @Input() columns: Column[];
  @Input() actions:Action[];
}
`

**html**
`
<app-angular2-actionable-table [columns]="columns" [actions]="actions"></app-angular2-actionable-table>
`

**the trick ?**
`
for(let i=0; i<this.columns.length; i++){
  @Output() Angular2ActionableTableComponent.prototype[this.columns[i].name];
  // The syntax is wrong for sure
}
`

**Result**

`
<app-angular2-actionable-table [columns]="columns" [actions]="actions"
    (edit)="onEdit($event)" (validate)="onValidate($event)">
</app-angular2-actionable-table>
`

## Environment
Angular version: 4.3.2

 
For Tooling issues:
- Node version: 8.1.2  
- Platform: Windows

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
