### ISSUE TITLE
[perf] URL / Style sanitizers (relatively) slow

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#19088]
While investigating performance of a test / sample application I've setup for performance tracking, I've noticed that certain bindings can make sanitizer(s) kick in and slow down views creation significantly (> 10%). Here are the benchpress results from the sample application with and without sanitizer kicking in:

### With sanitizer 

```
    forcedGcAmount |       forcedGcTime |           gcAmount |             gcTime |        majorGcTime |     pureScriptTime |         renderTime |         scriptTime
------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------
           2526.96 |               7.96 |             647.39 |               6.46 |               0.01 |              67.52 |             107.23 |              67.52
           3311.38 |               7.19 |               0.00 |               0.00 |               0.00 |              52.63 |              41.16 |              52.63
================== | ================== | ================== | ================== | ================== | ================== | ================== | ==================
       3279.86+-0% |           7.66+-5% |               0.00 |               0.00 |               0.00 |          32.16+-5% |          40.74+-5% |          32.16+-5%
```

### Without sanitizer

```
forcedGcAmount |       forcedGcTime |           gcAmount |             gcTime |        majorGcTime |     pureScriptTime |         renderTime |         scriptTime
------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------
           2457.92 |               7.08 |             653.82 |               3.56 |               0.02 |              60.17 |             107.35 |              60.17
           3266.50 |               7.02 |               0.00 |               0.00 |               0.00 |              47.50 |              42.82 |              47.50
================== | ================== | ================== | ================== | ================== | ================== | ================== | ==================
       3213.87+-0% |           7.56+-3% |               0.00 |               0.00 |               0.00 |          31.62+-6% |          43.63+-4% |          31.62+-6%
``` 

The observed slowdown for the initial view rendering (~60 ms -> ~67ms) is due to adding just 2 bindings similar to:
* `<div [style.border-color]="item.color">`
* `<img class="icon" src="/assets/icons/{{item.icon}}.png">`

It turns out, though, that 2 above patterns trigger similar code paths where sanitizer uses regular expressions to figure out of a value being sanitized contains URLs. This seems to be the most expensive part of the sanitization work. Still more investigation is required to see how we can mitigate performance impact of various sanitizers. Ideas / experiments to run:
* [ ] rewrite existing code to not use regular expressions 
* [ ] don't use sanitizer when bindings to "safe" styles

**Comment by gkalpak** [comment]
- [ ] try optimizing the regular expressions :grin:

**Comment by vicb** [comment]
> [RegExp] seems to be the most expensive part of the sanitization work

Gut feeling or measured ?

**Comment by pkozlowski-opensource** [comment]
> Gut feeling or measured ?

Educated guess for now :-) Still trying to narrow it down.

**Comment by vicb** [comment]
@pkozlowski-opensource any update on this ?

**Comment by pkozlowski-opensource** [comment]
No longer relevant with all the changes done with ivy / styling instructions.
