### ISSUE TITLE
double options with ngFor chrashes app.

### ISSUE THREAD

**Issue by mikeyii** [angular/angular#19089]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I used double options tag with ngFor app behaved very strange in mobile android platform. It was very strange to find where is problem, because it chrashes other part of application

## Expected behavior
```html
<!-- Describe what the desired behavior would be. -->
Lines below crashes some parts of mobile app.
<datalist id="contacts">
    <option *ngFor="let contact of contacts" [value]="contact.name">{{ contact.address | address }}</option>
    <option *ngFor="let phoneContact of phoneContacts" [value]="contact.name">{{ phoneContact.address | address }}</option>
</datalist>
```

Should works well on mobile android platform or show the error in browser.
## What is the motivation / use case for changing the behavior?

Some people can met it.

## Environment

<pre><code>
Angular version: 4.1.0
Ionic version:3.7.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.9.0
- Platform:  Every

Others:

</code></pre>

**Comment by vicb** [comment]
Please attach a repro

**Comment by vicb** [comment]
Closing as no repro
