### ISSUE TITLE
Select option with 'disabled' attribute is not selected by default when model value is empty

### ISSUE THREAD

**Issue by eosimosu** [angular/angular#19091]
## I'm submitting a...
[x] Bug report  

## Current behavior
When the model is empty, the selected/disabled option is not selected in Chrome/firefox. This works perfectly fine is Safari.

## Minimal reproduction of the problem with instructions
```
<select [(ngModel)]="selectedProject" name="project" id="project">
   <option value="" [selected]=true [disabled]="true">Select project</option>
   <option [value]="role.id" *ngFor="let project of projects">{{project.title}}</option>
</select>
```
## Environment
Angular version: 4.3.2
Issue present in version: 4.2.4

Browser:
- [x] Chrome (desktop) version Version 60.0.3112.113 
- [x] Firefox version 55.0.3 (64-bit)

**Comment by rafaelss95** [comment]
The problem is that you're trying to use `selected` with `ngModel`...

To get the first option, remove the `selected` and simply initialize `selectedProject` with this  value: 

```
@Component({...})

export class ...

  selectedProject = '';
```

See the [demo](http://plnkr.co/edit/ty9PTMczgUcJu2lL4ddv?p=info)

**Comment by eosimosu** [comment]
That works. However, my scenario is a bit more complex than that. The project list is dynamically populated and the options are updated too accordingly, but the moment the list size becomes 0, chrome doesn't select the default option, however safari does.

**Comment by rafaelss95** [comment]
Still can't reproduce this case.

[See here](http://plnkr.co/edit/0VFoYOOPYxHPnshiuAqt?p=preview)... note that I delayed the array by 3 seconds (simulating an API request).

**Comment by eosimosu** [comment]
You're populating the list, not removing the items. Anyways, [http://recordit.co/dm5WT53mvd](this) illustrates the problem... the main problem is that when the list becomes empty, disabled attribute is not selected by default

**Comment by rafaelss95** [comment]
IMHO your issue is misleading, you said nothing about deleting nothing... Anyway, try to create a plunker and demonstrate your issue.

**Comment by eosimosu** [comment]
Actually, the initial issue was that disabled option wasn't selected when the model is empty on startup, but removing `selected` as you suggested fix that.

**Comment by kara** [comment]
@eosimosu Can you create a minimal repro on Stackblitz? A video isn't enough actionable information to look into this.

**Comment by eosimosu** [comment]
@kara here https://stackblitz.com/edit/angular-tguppq

**Comment by kara** [comment]
Thanks for linking to the repro case! I took a look at it, and it actually seems to be working as expected. The select will populate option text only when its model value matches the value for that option. When you clear the array, the model value for the select has not changed.  It does not match the `''` value for the "select project" option, so it does not populate. As you've discovered, you can get the behavior you want by setting the model to match the option value you'd like to populate.

**Comment by select** [comment]
I had a similar problem:
This does not work:
```
<div formGroupName="hardware">
		{{data.model.hardware | json}}
		<label>Platform</label>
		<select formControlName="platform">
			<option [ngValue]="null" selected></option>
			<option *ngFor="let p of platforms">{{p}}</option>
		</select>
		<label>Architecture</label>
		{{formGroup.value.hardware.architecture}}
		<select formControlName="architecture" [attr.disabled]="formGroup.value.hardware.platform ? null: true">
			<option *ngFor="let arch of architectures[formGroup.value.hardware.platform]">{{arch}}</option>
		</select>
	</div>
```
this works, the difference is using the  `[value]` attribute
```
<div formGroupName="hardware">
		{{data.model.hardware | json}}
		<label>Platform</label>
		<select formControlName="platform">
			<option [ngValue]="null" selected></option>
			<option *ngFor="let p of platforms">{{p}}</option>
		</select>
		<label>Architecture</label>
		{{formGroup.value.hardware.architecture}}
		<select formControlName="architecture" [attr.disabled]="formGroup.value.hardware.platform ? null: true">
			<option *ngFor="let arch of architectures[formGroup.value.hardware.platform]" [value]="arch">{{arch}}</option>
		</select>
	</div>
```
