### ISSUE TITLE
"this" in service method points to callers scope when called as function object

### ISSUE THREAD

**Issue by alanpurple** [angular/angular#19092]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

"this" points to callers class instance

## Expected behavior

this should be "service" instance

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/Z2v9IiNNxqck7P91u2VP?p=preview

## Environment

<pre><code>
Angular version: 4.4.0-RC.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by alanpurple** [comment]
so I needed to take HttpClient instance as a parameter since "this.http" is undefined.

```
method(data:SomeType,http:HttpClient){
    return http.post...
}
```

**Comment by tytskyi** [comment]
@alanpurple This is not a bug of angular, but how javascript works.

When you assign method to a variable then method loses context (this).

You have multiple way to solve your problem:

1. Call method as is:

```typescript
? this.heroSearchService.search(term)
```
2. Use bind()
```typescript
this.aa=this.heroSearchService.search.bind(this.heroSearchService);
```

3. Make method to be the "instance method"
```typescript
export class HeroSearchService {

  constructor(private http: Http) {}

  search = (term: string): Observable<Hero[]> => {
    console.log(this);
    return this.http
               .get(`api/heroes/?name=${term}`)
               .map(response => response.json().data as Hero[]);
  }
}
```

4. Use typescript decorator that will bind context (you need to implement that decorator yourself or search for library for that)
```typescript
// note @autobind is your own implementation or 3rd party library
@autobind
search(term: string): Observable<Hero[]> {}
```

**Comment by alanpurple** [comment]
@tytskyi Thank you
