### ISSUE TITLE
`Location` does not have a way to differentiate between Back and Forward buttons pressed

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/angular#19099]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is no way to determine whether browser "back" or "forward" button was pressed.
```ts
import { Location } from '@angular/common';
...
location.subscribe((ev) => {
  console.log(ev.pop); // this is true when both "back" and "forward" button is pressed
  // there is no property that would differentiate between the two: ev.isBack / ev.isForward
});
```

## Expected behavior

There should be a way to differentiate between Back or Forward events.

## What is the motivation / use case for changing the behavior?

Sometimes you only want to act when Back button is pressed, but not when the Forward button is pressed

## Environment

<pre><code>
Angular version: 4.3.2

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   Does not matter
- Platform:  Windows

Others:

</code></pre>

**Comment by danquack** [comment]
Can we get a update on this?

**Comment by atscott** [comment]
In addition to the insufficient votes, this is actually just a limitation of the browser capabilities and isn't something we're able to provide. This type of thing is one of the goals being addressed by the proposed [App history API](https://github.com/WICG/app-history)
