### ISSUE TITLE
Nested animation don't run and start callback is not fired 

### ISSUE THREAD

**Issue by lionelB** [angular/angular#19100]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
when 2 nested component with animation trigger defined on each component, only toplevel animation is run and its start animation callback is called. 

## Expected behavior
each callback should be called

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/Wa7UNmKQkaVMWPNGmoxH?p=preview

## What is the motivation / use case for changing the behavior?
Nested animation are usefull for defined enter animation

## Environment

<pre><code>
Angular version: 4.4.0-RC.0
 
Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by matsko** [comment]
The nested animation being prevented by the parent is by design (see (this article)[https://www.yearofmoo.com/2017/06/new-wave-of-animation-features.html#sub-animations-with-animatechild] to understand how to allow parent/child animations to run).

The start callback should be firing and it is a bug for sure. I will investigate.

**Comment by lionelB** [comment]
@matsko thanks !

**Comment by Bretto** [comment]
Is this related ? https://github.com/angular/angular/issues/17349

**Comment by bob-lee** [comment]
> The nested animation being prevented by the parent is by design

@matsko I am applying slide-left animation on all route transitions including routes in lazy loaded module and all pages are sliding good. But for pages inside lazy loaded module, `animateChild()` doesn't seem to trigger pages' nested animation. Is this a known bug or am I missing something?

**Comment by matsko** [comment]
This guy will fix it for good: https://github.com/angular/angular/issues/19100
