### ISSUE TITLE
Link to full ngUpgrade examples (either based on API docs or guide examples)

### ISSUE THREAD

**Issue by andrewl-telnyx** [angular/angular#19102]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This is in reference to this comment: https://github.com/angular/angular/issues/18712#issuecomment-323355588

@gkalpak asked me to create a separate ticket for this. Currently a weakness in the upgrade documentation is that there are no full examples of what an upgrade would look like in the real world. There are gaps in the explanations for things.
An example of a gap, in [Using AngularJS Component Directives from Angular Code](https://angular.io/guide/upgrade#using-angularjs-component-directives-from-angular-code), it says "Not all kinds of AngularJS directives can be upgraded. The directive really has to be a component directive,". 
It's cool that it says "hey this isn't possible", but it doesn't say...what you're supposed to do when you have a directive that uses the "link" or "compile" properties in order to upgrade it. That's pretty important. The behavior obviously still has to exist in the app you're upgrading, so what is the Angular equivalent way of doing link/compile-- because in this specific example, there is a comment in the UpgradeComponent.prototype.getDirective method that literally asks:
"QUESTION: why not support link.post?"
According to that code (at a glance), directives with a link function SHOULD be ok to use as long as they do not contain a post function-- but if you use a link function, the .notSupported method will be called  with 'compile' because compile gets defined with a valueRef to link.

## Expected behavior

Basically in (our) humble opinions, a full, working example at the end of each ngUpgrade API doc pages would be super helpful. Important topics that I've yet to find good examples of are:

- using an AngularJS service in an Angular service
- using an Angular service in an AngularJS service
- what to do if you have a directive that has a compile or link function
- how to use an AngularJS directive within an Angular component (specifically running into problems using old UI-Router ui-sref directives within an Angular component)

... basically what I'd say to do is go back to the angularjs.org site when it was using AngularJS 1.4 -- because a lot of AngularJS apps in the real world live in that world and need to be upgraded to use AngularJS components before being upgraded-- and literally upgrade the site as it was when it was in that state, to Angular. 

## Minimal reproduction of the problem with instructions

https://github.com/angular/angular/issues/18712

## What is the motivation / use case for changing the behavior?

A less painful upgrade process. 

## Environment

<pre><code>
Angular version: 4.4.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v7.4.0  
- Platform: Mac  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
docsarea=angularjsupgrade

**Comment by jenniferfell** [comment]
@andrewl-telnyx There is a new ngMigration-Forum wiki with new, expanded information and tools to assist with upgrading. 

https://github.com/angular/ngMigration-Forum/wiki/ngUpgrade

The issues area of that repo is also acting as a forum for upgrade discussions. If you're still working on  your upgrade, you may find some information, tools, and people there to help with any specific challenges you're having. 

Also, the main Angular docs were expanded recently: https://angular.io/guide/upgrade-performance

We're looking into integrating or linking the content pieces as well, so continued feedback is definitely still welcome. Thanks.

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
