### ISSUE TITLE
Add `@angular/common/http` package by default in plunker template

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#19104]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
You have to add the `@angular/common/http` package in the plunker's `config`.

## Expected behavior
I'd expect to have `@angular/common/http` package included in `config` by default.

**Comment by robwormald** [comment]
done
