### ISSUE TITLE
Build size for cli-hello-world increased when upgrading TypeScript to 2.4

### ISSUE THREAD

**Issue by tbosch** [angular/angular#19113]
The new `main....bundle.js` contains e.g.
```
    ApplicationRef_.decorators = [
        { type: Injectable },
    ];
    /** @nocollapse */
    ApplicationRef_.ctorParameters = function () {
        return [
            { type: NgZone, },
            { type: Console, },
            { type: Injector, },
            { type: ErrorHandler, },
            { type: ComponentFactoryResolver, },
            { type: ApplicationInitStatus, },
        ];
    };
```
but the old bundle did not.

The new bundle does contain `PURE` annotations though.

Checking the package.json in the generated cli project shows TyperScript 2.3 though, as well as when checking the version in `integration/cli-hello-world/node_modules`.

**Comment by IgorMinar** [comment]
@kara can you please take a look at this one once #19097 lands?

The upgrade of angular/angular to typescript 2.4 caused a size regression in our hello world integration test. My guess is that this is because typescript 2.4 transpiles core/common/.. packages slightly differently than the older version, resulting in build-optimizer not finding the downleveled decorators that should be removed. We might need to adjust the AST check that finds these.

**Comment by IgorMinar** [comment]
the difference between before and after the #19097 change is approximately 31K so we should be looking to decrease the size by this much (currently the size of the main bundle in hello world cli is 172643 bytes, with this change is just below 205000 bytes)

**Comment by kara** [comment]
Yep, it looks like TS 2.4 transpiles slightly differently. Previously, decorators and constructor parameters were left at the top level:

```ts
var ApplicationRef_ = (function (_super) {
   ...
}(ApplicationRef));

ApplicationRef_.decorators = [...];
ApplicationRef_.ctorParameters = function () {...};
```

Now the decorators and constructor parameters are nested inside the IIFE:

```ts
var ApplicationRef_ = (function (_super) {
   ...
   ApplicationRef_.decorators = [...];
   ApplicationRef_.ctorParameters = function () {...};
}(ApplicationRef));
```

Build-optimizer was only doing a shallow check (on the top level) for expression statements, so it couldn't find the decorators nested in the IIFEs to remove them.  I have a [WIP PR](https://github.com/angular/devkit/pull/146) in the devkit repo that addresses the change. Building with the fix, we are back down to ~172 KB.
