### ISSUE TITLE
docs(aio): use-host-property-decorator: case with route animations

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/angular#19110]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Re-opening issue [#393](https://github.com/mgechev/codelyzer/issues/393) here per @mgechev suggestion.

## Expected behavior

Linting error should not be present

## What is the motivation / use case for changing the behavior?

In general setting tslint option `"use-host-property-decorator": true` is a good idea. However, there might be one use case when this is not helpful.
The case when you'd want to use `host` property for route animation is quite common:
```
@Component({
  selector: 'help-page',
  templateUrl: './help.component.html',
  animations: [routerTransition()],
  host: {'[@routerTransition]': ''}
})
export class HelpComponent  { }
```
You would not want to use HostBinding in the class because this property would just be unused, and possibly trigger another linting error.

Perhaps, use-host-property-decorator should have an exception for the animation bindings.
I also feel this should be added to the [style guide](https://angular.io/guide/styleguide#hostlistenerhostbinding-decorators-versus-host-metadata), but not sure where to submit this thought. Any pointers are appreciated!

## Environment

<pre><code>
Angular version: 4.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
@brandonroberts : Do you have any thoughts on this? I wonder if what tslint does/doesn't do is not so much the issue as how Angular itself works...or best practices for Angular?

**Comment by mgechev** [comment]
@DmitryEfimenko given our prioritization process, I'll close the feature request for now. In case we allocate resources in this space we'll reconsider.
