### ISSUE TITLE
Make the backwards compatible implementation of getPluralCase tree-shackable

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#19115]
When https://github.com/angular/angular/commit/30d53a8942f633d92f6c75d9b892ac2e527d989d was merged, we regressed on size of hello world cli app by ~5kb. This was most likely because of the large implementation of the `getPluralCase` function.

@vicb says that the original thinking was that because of the injection constant, the minifier would be able to remove the function if it was not used. This turned out to be true for closure but not for uglify.

There is a simple solution to fix this however. We should implement the getPluralCase as an injectable function that has two implementations - the default lightweight one that uses locale files, and this large backwards compatible one. The backwards compatible implementation would then be provided as a value via the DeprecatedI18nPipesModule NgModule. Once we do it this way, the big implementation will be brought into the app only if the deprecated module is imported.

**Comment by vicb** [comment]
```ts
/* @deprecated from v5*/
export function getPluralCase(...) {...};

@NgModule({
  declarations: [COMMON_DEPRECATED_I18N_PIPES],
  exports: [COMMON_DEPRECATED_I18N_PIPES],
  providers: [{provide: DEPRECATED_PLURAL_FN, useValue: getPluralCase}],
})
export class DeprecatedI18NPipesModule {
}
```

When `@Optional @Inject(DEPRECATED_PLURAL_FN)` is null use the v5 API otherwise use that function.
