### ISSUE TITLE
[Question] How to test directives that have templateUrls

### ISSUE THREAD

**Issue by matthewjh** [angular/angular#1912]
Hi.

I'm currently stuck on trying to unit test a view of a directive that has a templateUrl.

```javascript
@Component({
  selector: 'app',
  injectables: injectorBindings
})
@View({
  templateUrl: 'src/components/app/template.html'
})
export class AppComponent {
  constructor(model: Model) {
    console.log(model);
  }
}
````

````javascript
it('should render the correct template', inject([AsyncTestCompleter, TestBed, XHR], (async, tb, xhr) => {
      var html = '<app></app>';

      tb.createView(TestComponent, {html: html}).then((view) => {
        view.detectChanges();

        expect(DOM.getText(view.rootNodes[0])).toEqual('hi');

        async.done();
      });
  }));
````

The request for the template goes through to `MockXHR#get`, but unfortunately using `xhr.when` and `xhr.flush` doesn't seem to work because `MockXHR#get` is called asynchronously after the call to `tb.createView`.

Does anyone have any ideas?

**Comment by jelbourn** [comment]
This is an open issue: #1610

**Comment by mhevery** [comment]
Also I think it is solved here: https://github.com/angular/angular/blob/master/modules/angular2/src/test_lib/test_bed.ts

Reopen if you think it is not solved.
