### ISSUE TITLE
Angular Form Validations with multiple Routes

### ISSUE THREAD

**Issue by Pontiley** [angular/angular#19125]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Hello All, and dear developers, 

Can you help me please?

I don't find any information. how I can do **Angular forms validations for multiple routes.**
For example, I have one a big form, it contains several sections like tabs, and I can navigate to them in any moment. I use rooting for like navigation.
E.g. I have template, which include <router-outlet></router-outlet> and about 5 tabs. When I fill all inputs I sent data to the server, the server validates my data and if I data had errors, server sent it to front end like JSON which contains errors array with objects like this 
`{"field": "some input", "message": "some error message"}`
I parse this answer, and search form control from the form by a field value, and add error message. But I can do it, **for one tab**, because in the one moment I have active route only one tab, and I have the form control only for this tab, but how I can load other tabs, in a background and get their form control, and set the error message for them?

Are there any ways to solve this problem?

I tried to find an answer on the Internet, but I could not find anything specific. I find only one article with the same problem http://heidloff.net/article/angular-2-form-redux-multiple-routes, but really there is no other option, only how to use  Redux?

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Pontiley** [comment]
OK, thanks for the information. I close this issue.
