### ISSUE TITLE
Overall performance: ngc, rollup, uglify

### ISSUE THREAD

**Issue by kemsky** [angular/angular#19121]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Our project size:
```
github.com/AlDanial/cloc v 1.74  T=0.50 s (1174.0 files/s, 94736.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TypeScript                     382           6244           1929          33758
HTML                           166            367              3           3575
CSS                             39            208             20           1264
-------------------------------------------------------------------------------
SUM:                           587           6819           1952          38597
-------------------------------------------------------------------------------
```

Typescript only compilation:
```
[19:00:48] Starting 'ts'...
[19:00:49] Starting 'compile'...
[19:01:04] Finished 'compile' after 15 s
[19:01:04] Finished 'ts' after 16 s
```

Full production build using `webpack2` with `ts-loader` (JIT mode):
```
[19:40:48] Starting 'build'...
[19:40:48] Starting 'clean-dist'...
[19:40:48] Finished 'clean-dist' after 64 ms
[19:40:48] Starting 'structure'...
[19:40:48] Finished 'structure' after 5.09 ms
[19:40:48] Starting 'webpack'...
Mode: "release"

               Asset     Size  Chunks                    Chunk Names
      main.bundle.js  2.31 MB       0  [emitted]  [big]  main
    vendor.bundle.js   134 kB       1  [emitted]         vendor
  main.bundle.js.map  12.3 MB       0  [emitted]         main
vendor.bundle.js.map   979 kB       1  [emitted]         vendor

[19:41:39] Finished 'webpack' after 51 s
[19:41:39] Starting 'notify'...
[19:41:39] Finished 'notify' after 11 ms
[19:41:39] Finished 'build' after 51 s
```
I'm using `transpile-only` option of `ts-loader` (CI calls typescript compiler in another step to check compilation errors, to make it fail fast).

Full production build using `ngc` and `rollup` (AOT mode):
```
[18:29:03] Starting 'build-aot'...
[18:29:03] Starting 'clean-dist'...
[18:29:03] Finished 'clean-dist' after 33 ms
[18:29:03] Starting 'clean-aot'...
[18:29:03] Finished 'clean-aot' after 127 ms
[18:29:03] Starting 'structure'...
[18:29:03] Finished 'structure' after 2.53 ms
[18:29:03] Starting 'ngc'...
[18:30:52] Finished 'ngc' after 1.82 min
[18:30:52] Starting 'rollup'...
[rollup] Mode: release
[rollup] Tag: DEV
[rollup] Version: 0

Spa_Source/main-aot.js → Spa_Dist/main.bundle.js...
created Spa_Dist/main.bundle.js in 9m 40.5s

[18:40:34] Finished 'rollup' after 9.68 min
[18:40:34] Starting 'notify'...
[18:40:34] Finished 'notify' after 5.72 ms
[18:40:34] Finished 'build-aot' after 12 min
```
![perfmon](https://user-images.githubusercontent.com/3826972/30242333-f6e75614-959c-11e7-95df-b654af25702e.png)

`uglify` settings are the same for both builds.

Disk and CPU usage is low, it means that AOT build does not utilize available resources. 

I've tried the same with RAM disk (`ImDisk`) and ... it makes no difference!

## Expected behavior
12 minutes is just too long and it gets worse on build server.

## What is the motivation / use case for changing the behavior?
This is very slow on high-end hardware i7-6700HQ with SSD. 
Our build server is not so fast, so actual build time is 30 minutes (!) with `ngc` and `rollup` and 2.45 minutes with `webpack2` and `ts-loader`. 15x difference!

## Environment

<pre><code>
Angular version: 4.4.0-RC.0

For Tooling issues:
- Node version: 8.1.3
- Platform:  Windows

**Comment by Toxicable** [comment]
Can you please outline exactly what feature you're requesting here.
Right now this looks like a support request which this Issue tracker is not suitable for
