### ISSUE TITLE
Response.arrayBuffer does not return consistent results

### ISSUE THREAD

**Issue by maximedupre** [angular/angular#19122]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If `ResponseContentType.ArrayBuffer` is specified in `http.get`, the resulting `ArrayBuffer` from `response.arrayBuffer` will have an associated view that is a `Uint8Array`. Without `ResponseContentType.ArrayBuffer`, the associated view is a `Uint16Array`.

## Expected behavior
I think the behaviour should be the same regardless of if `ResponseContentType.ArrayBuffer` is specified or not.

## What is the motivation / use case for changing the behavior?
https://stackoverflow.com/questions/46132165/cant-decode-audio-file-when-returned-by-server/46132488#46132488

## Environment
<pre><code>
Angular version: 4.4.0-RC.0 (but the relevant code has not changed since many versions)

Browser:
Chrome (desktop) version 60.0.3112.113 (Official Build) (64-bit)
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  macOs 12.10.6

**Comment by alxhub** [comment]
Can you send a reproduction, @maximedupre?
