### ISSUE TITLE
@angular/compiler-cli 4.4.0-RC.0 depends on @angular/tsc-wrapped 4.3.6

### ISSUE THREAD

**Issue by dfederm** [angular/angular#19129]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

@angular/compiler-cli 4.4.0-RC.0 depends on @angular/tsc-wrapped 4.3.6

## Expected behavior

@angular/compiler-cli 4.4.0-RC.0 depends on @angular/tsc-wrapped 4.4.0-RC.0

## Minimal reproduction of the problem with instructions

N/A

## What is the motivation / use case for changing the behavior?

Consistent versioning

## Environment

<pre><code>
Angular version: 4.4.0-RC.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alexeagle** [comment]
Still present in today's release:
https://unpkg.com/@angular/compiler-cli@4.4.1/package.json

This is probably not very important since the tsc-wrapped package is being dropped for Angular 5

**Comment by chuckjaz** [comment]
Closing as the current version `@angular/compiler-cli@4.4.6` depends on `@angular/tsc-wrapped@4.4.6` so this appears to have been a transitory issue in RC and not something systemic in our build/release process.
