### ISSUE TITLE
afterViewinit 在设置了 ChangeDetectionStrategy.OnPush 之后

### ISSUE THREAD

**Issue by BengBu-YueZhang** [angular/angular#19131]
TS:
import { Component, OnInit, DoCheck, OnChanges, AfterContentChecked, AfterContentInit, AfterViewInit, AfterViewChecked, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.css'],
  changeDetection: ChangeDetectionStrategy.Default
})
export class TestComponent implements OnInit, DoCheck, OnChanges, AfterContentChecked, AfterContentInit, AfterViewInit, AfterViewChecked {

  public arr: Array<string> = []

  constructor() { }

  ngOnInit() {
    this.arr.push('ngOnInit')
  }

  ngDoCheck() {
    this.arr.push('ngDoCheck')
  }

  ngOnChanges () {
    this.arr.push('ngOnChanges')
  }

  ngAfterContentChecked() {
    this.arr.push('ngAfterContentChecked')
  }

  ngAfterContentInit() {
    this.arr.push('ngAfterContentInit')
  }

  ngAfterViewInit() {
    this.arr.push('ngAfterViewInit')
  }

  ngAfterViewChecked() {
    this.arr.push('ngAfterViewChecked')
  }
}

HTML：
<div>
  <p *ngFor="let item of arr" >{{item}}</p>
</div>

=>

ngOnInit

ngDoCheck

ngAfterContentInit

ngAfterContentChecked

------------------------------------OnPush-------------------------------------

import { Component, OnInit, DoCheck, OnChanges, AfterContentChecked, AfterContentInit, AfterViewInit, AfterViewChecked, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TestComponent implements OnInit, DoCheck, OnChanges, AfterContentChecked, AfterContentInit, AfterViewInit, AfterViewChecked {

  public arr: Array<string> = []

  constructor() { }

  ngOnInit() {
    this.arr.push('ngOnInit')
  }

  ngDoCheck() {
    this.arr.push('ngDoCheck')
  }

  ngOnChanges () {
    this.arr.push('ngOnChanges')
  }

  ngAfterContentChecked() {
    this.arr.push('ngAfterContentChecked')
  }

  ngAfterContentInit() {
    this.arr.push('ngAfterContentInit')
  }

  ngAfterViewInit() {
    this.arr.push('ngAfterViewInit')
  }

  ngAfterViewChecked() {
    this.arr.push('ngAfterViewChecked')
  }
}

=> 

ngOnInit

ngDoCheck

ngAfterContentInit

ngAfterContentChecked

**Comment by mlc-mlapis** [comment]
@BengBu-YueZhang ... can you briefly describe what is the problem?

**Comment by BengBu-YueZhang** [comment]
my English is not good

--------------------------------------
I try to achieve all Angualar Component lifecycle hooks

`import { Component, OnInit, DoCheck, OnChanges, AfterContentChecked, AfterContentInit, AfterViewInit, AfterViewChecked, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TestComponent implements OnInit, DoCheck, OnChanges, AfterContentChecked, AfterContentInit, AfterViewInit, AfterViewChecked {

  public arr: Array<string> = []

  constructor() { }

  ngOnInit() {
    this.arr.push('ngOnInit')
  }

  ngDoCheck() {
    this.arr.push('ngDoCheck')
  }

  ngOnChanges () {
    this.arr.push('ngOnChanges')
  }

  ngAfterContentChecked() {
    this.arr.push('ngAfterContentChecked')
  }

  ngAfterContentInit() {
    this.arr.push('ngAfterContentInit')
  }

  ngAfterViewInit() {
    this.arr.push('ngAfterViewInit')
  }

  ngAfterViewChecked() {
    this.arr.push('ngAfterViewChecked')
  }
}
`
--------------------------------------

 if ChangeDetectionStrategy.Default result **arr** Be equal to

[
ngOnInit,
ngDoCheck,
ngAfterContentInit,
ngAfterContentChecked,
]


ngAfterViewInit(), Not executed, why????? Ask for help， **Thanky**

**Comment by trotyl** [comment]
Could not reproduce.
ChangeDetectionStrategy.Default (http://plnkr.co/edit/rzhpMlGCuu3wSmTi2IB2?p=preview):
![image](https://user-images.githubusercontent.com/6059170/30256073-97819204-96da-11e7-8671-52ea8633322d.png)
ChangeDetectionStrategy.OnPush (http://plnkr.co/edit/UcUOKhD0h7qG8hwuIwtN?p=preview):
![image](https://user-images.githubusercontent.com/6059170/30256095-b7d68f5a-96da-11e7-8cd0-c7df3b6aeee8.png)

Please fill the issue template and **provide a plunker to reproduce your problem**, otherwise it's likely to be closed.

**Comment by BengBu-YueZhang** [comment]
Thanys

**Comment by BengBu-YueZhang** [comment]
Thanks

**Comment by BengBu-YueZhang** [comment]
https://segmentfault.com/q/1010000011110229

**Comment by dmitrysteblyuk** [comment]
All the lifecycle hooks are called regardless change detection strategy. It's just the template is not being updated after you change ```this.arr``` in ```ngAfterViewInit``` for OnPush strategy (because the view is already initialized and checked). That's why we see logs in console but not on page.
To fix it you can do this:

```
constructor (private cdr: ChangeDetectorRef) {}

ngAfterViewInit() {
    this.arr.push('ngAfterViewInit');
    // I believe setTimeout is needed here for this particular case as the view has already been checked
    setTimeout(() => this.cdr.markForCheck(), 0);
}
```

**Comment by BengBu-YueZhang** [comment]
Thanks
