### ISSUE TITLE
Problem to communicate with the Java (Spring Boot) Backend

### ISSUE THREAD

**Issue by lukecorf** [angular/angular#19139]
Node.js Version: 8.2.1
Windows 10
IDE: Intellij
Frameworks: Spring Boot & Angular 4

Well... I need get data from my backend (Java). But Angular terminal show this message error:

[HPM] Error occurred while trying to proxy request /api/dados from localhost:4500 to http:/localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

This is my Angular code:

![a](https://user-images.githubusercontent.com/22321349/30277432-246f78ae-96de-11e7-94f8-345a9c604075.jpg)

And this is my Java Code:

![as](https://user-images.githubusercontent.com/22321349/30277442-2cc70c60-96de-11e7-8b49-a4560972bc44.jpg)

My Tomcat is configurated to 8080 port

![sem titulo](https://user-images.githubusercontent.com/22321349/30277452-3567a668-96de-11e7-82db-f50b57040036.jpg)

And my proxy in angular is configurated like this image:

![asd](https://user-images.githubusercontent.com/22321349/30277464-40ecf632-96de-11e7-88b3-c937980ed8c9.jpg)

Someone can help me please? This is important

**Comment by aravindfz** [comment]
Did you try posting it in stackoverflow?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).


PS: The error message gave you a link, try to read it.

**Comment by veke** [comment]
Have you tried setting proxy ```changeOrigin: true```

**Comment by IgorMinar** [comment]
@ericmartinezr  +1
