### ISSUE TITLE
Angular Not working with restricted CSPs without unsafe-eval

### ISSUE THREAD

**Issue by yadavvineet** [angular/angular#19142]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

All the issues and links are probably more then year old. With more advanced browser and security focus this angular should support strict CSP.

## Current behavior
If my application we have resteicted CSP with script src defined and wihout unsafe-eval. 
When starting the angular application, it fails giving the following error about unsafe-eval not supported.
`EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src http://xxxxxxxx 'unsafe-inline' 'self'". `

I have also tried the Offline template compilation, but there also the error is more or less similar. As mentioned in several posts and answers, it still gives the CSP error. 

`Error: (SystemJS) Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src http://xxxxxx 'unsafe-inline' 'self'".
	
	EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src http://xxxxxx 'unsafe-inline' 'self'".`

## Expected behavior
There should be some way of getting angular work with restricted CSP where unsafe-eval is not allowed due to multiple reasons. 

## Minimal reproduction of the problem with instructions
1. Create an application. 
2. Add the following line in head to enable restricted csp
`    <meta http-equiv="Content-Security-Policy" content="script-src http://xxxxx'unsafe-inline' 'self'">`
3. Browse the application in MS Edge or Chrome ver >60. you will get CSP Error. 

Also, 
Comile the application using offline compiler with following tsconfig.
`
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "skipLibCheck": true,
    "lib": [
      "es2015",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "genDir": "./aot",
    "entryModule": "./ClientApp/app/app.module#AppModule",
    "skipMetadataEmit": true
  },
  "compileOnSave": false,
  "buildOnSave": false
}
`
Execute the statement to compile:  ngc -p path
Do Steps 1-3 above. You get same error.

## What is the motivation / use case for changing the behavior?
In some environments (and probably everyone) should have secure environment and should support CSP. Angular should work in such scenarios. 

Angular version: 4

Browser:
- [X ] Chrome (desktop) version >=60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [X ] Edge version XX
 
Followed standard Quickstart guidelines  provided on site.

**Comment by yadavvineet** [comment]
Please suggest if i am not aware if there is work around for this or ngCsp like functionality

**Comment by robwormald** [comment]
this is more likely to do with SystemJS than Angular, assuming you're using AoT. See https://github.com/systemjs/systemjs/blob/master/docs/production-workflows.md

**Comment by yadavvineet** [comment]
Yes, the issue is with SystemJs. 
Can verify, angular aot and tree shaking working ok. No CSP issues. Hence marking closed
