### ISSUE TITLE
Prerendering + lazy loading friction (Angular 4)

### ISSUE THREAD

**Issue by andrelashley** [angular/angular#19149]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In the context of a SPA which uses server-side pre-rendering (such as implemented in the dotnet generator, see this guide also) and lazy-loaded routes, there is a moment after the app is bootstrapped and the lazy-loaded module is downloaded or downloading when neither the module nor the pre-rendered content are visible. This is jarring enough to make the pre-rendering detrimental rather than beneficial. This feature request is based on an issue that was raised by @daveriedstra about Angular v2.

1. user loads app on lazy-loaded route
2. prerendered content is loaded, user starts reading
3. app core content is loaded and bootstrapped
4. app renders without lazy route -- prerendered content disappears without its replacement
5. app starts downloading the lazy route
6. lazy route finishes loading, is rendered -- content reappears

## Expected behavior

The handover should be seamless. Maybe there could be a configuration where no angular rendering happens until all lazy loading is finished.

## Minimal reproduction of the problem with instructions

1.  Create a new Angular2 project (with pre-rendering or substantial placeholder content)
2. Create a lazy-loaded route and the corresponding router configuration
3. Load corresponding route directly

[repro](https://plnkr.co/edit/aDlmUCUEnk3LE5UQek1F) (uses alerts to illustrate pain points, remove them to see issue in action)

## What is the motivation / use case for changing the behavior?

To reap benefits of both lazy loading and server-side pre-rendering

## Environment
essentially version one of the dotnet generator, but see repro for a more agnostic example.

<pre><code>
Angular version: 4.4.0

- Browser:
   Chrome 60.0.3112.113 (Official Build) (64-bit)
   Firefox 55.0.3 (32-bit)
   Edge 40.15063.0.0

- Language: typescript

- Node (for AoT issues): node --version = v7.9.0

**Comment by daveriedstra** [comment]
original issue: #12951

**Comment by vikerman** [comment]
Set initialNavigation to 'enabled' in the router.

https://github.com/angular/angular/blob/a80ecf6a7770decec565521022f73d6f6686d5d0/packages/router/src/router_module.ts#L217

RouterModule.forRoot([ // ROUTES HERE ], { initialNavigation: 'enabled' })
