### ISSUE TITLE
Promise.resolve() is not a function error

### ISSUE THREAD

**Issue by lakinmohapatra** [angular/angular#19141]
Hi 

I am using a third party library js file . 

It has a statement return Promise.resolve();

At this point , my page is breaking .

I tried by modifying target build to ES6. But it did not work. 

Please advise.

**Comment by gkalpak** [comment]
It seems that you ar not including some of the required polyfills (see [here][1] for more info).

BTW, this issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests. If you are not able to resolve the problem, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

[1]: https://angular.io/guide/browser-support#polyfills
