### ISSUE TITLE
aio: toh live example is broken by angular/common/http

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#19144]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

toh live example is broken. The problem is because of system.config. `@angular/common/http` is not configured.

https://angular.io/generated/live-examples/toh-pt6/eplnkr.html

## Expected behavior

Works well

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

related: #19002

This commit https://github.com/angular/angular/commit/112e777b903bbfc29a79acea11cf7b622f641993 looks solving this issue. Is it not released yet? cc/ @wardbell

**Comment by gkalpak** [comment]
Yeah, that commit fixes the issue (see it in action [here][1]).
It seems that it hasn't been backorted to the stable branch. Let's track it in #19080.

[1]: https://next.angular.io/generated/live-examples/toh-pt6/eplnkr.html.
