### ISSUE TITLE
HTTP-Interceptor get's no info about unsubscribed requests

### ISSUE THREAD

**Issue by tpeter1985** [angular/angular#19156]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Code in "do(...)" of "next.handle(req).do(...)" does not get executed for unsubscribed requests.

## Expected behavior
Execute code in "next.handle(req).do(...)" for unsubscribed requests too.

## Minimal reproduction of the problem with instructions
Mini-Demo that shows code inside "next.handle(req).do(...)" does not get executed when unsubscribed http-requests completed: https://plnkr.co/edit/eS9fZHDrf7e6o4X0uBYk?p=preview

## What is the motivation / use case for changing the behavior?
One of the features of Angulars HTTP-Interceptors (4.3) is to run code before a request is made and after it is completed.
This is good for all kinds of request / response manipulation.
Some monitoring features cannot be implemented with the current implementation because you don't have the possibility to get informed about finished http requests that you have unsubscribed.

My current use cases for this feature:
1) Interceptor with a counter for outstanding requests so that a loading spinner can be shown easily via an *ngIf expression that uses the counter.
2) Possibility to prevent executing multiple requests at the same time for some urls (e.g. user double-clicks).

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [ x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</pre>

**Comment by alxhub** [comment]
This is correct and by design. If you need to handle unsubscription, return a new `Observable` that wraps the one from `next.handle(req)`.

**Comment by tpeter1985** [comment]
Thank you @alxhub, your suggestion works.
It's a really nice interceptor implementation :smiley:
If someone is interested in a simple solution to visualize outstanding http requests: [http://embed.plnkr.co/CAw7Bj/](http://embed.plnkr.co/CAw7Bj/)
The sample now works even if you click _getHeroes()_ multiple times very fast so that the first subscriptions get unsubscribed.
