### ISSUE TITLE
Angular Language Service not recognizing the declartion of all of the component in a module that provides with useFactory

### ISSUE THREAD

**Issue by bluEEil** [angular/angular#19157]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I downloaded the angular project seed from the official docs (The one that uses systemjs without cli)
When angular language service is enabled, it gives me errors for all the components in my core module, the error is:
Angular: Component '<SOMENAME>' is not included in a module and will not be available inside a template. Consider adding to a NgModule declartion

I did some investigating to find why this happens only for all the components and my core module (while in the AppModule and other Feature modules it didn't occur)

I have a defention for providers in my core module that looks like this:

<pre><code>
@NgModules({
...
providers: [
 InitAppService,
{
    provide: APP_INITIALIZER,
    useFactory: (config: InitAppService) => () => config.initApp(), // Init app returns a promise that 
    // resolves when the app is ready. 
   deps: [InitAppService],
   multi: true
}
]
})
...
</code></pre>

I tried playing with this part of the code, but nothing worked except for removing it (the entire object literal use to provide that factory)
When removing that code and recompalling, it all worked again (no errors about the component in core not belonging to any NgModule)

## Expected behavior

I expect the angular language service to recognize my modules even if they provide tokens using useFactory fashion (and thus not giving me error about all the core components)

## Minimal reproduction of the problem with instructions

I gave the best code example I could come with in current behavior part. Sadly Im working in a company that is not connected to the www so I cant get any actual code out. I'm also very limited on time on computers that are connected to www, so I don't have time to write a planker or something like that for this problem at this particular time.

## What is the motivation / use case for changing the behavior?

This kind of errors just overpopulate the errors in the typescript error screen (im using webstorm)
and make the work with angular language service impossible for me (and I imagine for anyone else who counters this erros because of using the useFactory)

## Environment

<pre><code>
Angular version: 4.2.1

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
(Im accually running it on electron, not sure which option to tick but ill just write it here) 

For Tooling issues:
- Node version: 6.9.1  
- Platform:  Windows 7

**Comment by JoostK** [comment]
I can no longer reproduce this even with the View Engine language service, and this is also not an issue with the Ivy language service. So closing as resolved at some point.
