### ISSUE TITLE
suggest:[(ngModel.lazy)] and [(ngModel.eager)]

### ISSUE THREAD

**Issue by xp44mm** [angular/angular#19162]
## Current behavior
`[(ngModel)]` of<input> element be translated to:
```html
<input [value]="currentHero.name"
       (input)="currentHero.name=$event.target.value" >
```
i do not care about always look at inputing change every char, i just ask for last result. so i listen the blur event.
```html
<input [value]="currentHero.name"
       (blur)="currentHero.name=$event.target.value">
```
## Expected behavior
actually watch the  progress that get every char is refered to as **eager**. and watch last reasult of input is refered to as **lazy** so i suggest:

```html
<input [(ngModel.eager)]="currentHero.name">
same as:
<input [(ngModel)]="currentHero.name">
and same as:
<input [value]="currentHero.name"
       (input)="currentHero.name=$event.target.value" >
```
and 
```html
<input [(ngModel.lazy)]="currentHero.name">
same as:
<input [value]="currentHero.name"
       (blur)="currentHero.name=$event.target.value">
```

**Comment by Toxicable** [comment]
I believe this is already handled by https://github.com/angular/angular/pull/18577

**Comment by kara** [comment]
Yep, this use case should be handled by the 'updateOn: blur' option.
