### ISSUE TITLE
NGC problem with dynamic templateUrl

### ISSUE THREAD

**Issue by millerf** [angular/angular#19169]
Hi,

I have been using dynamic templates URL in order to get multiple 'themes' to my application (HTML+CSS)
Unfortunately it works fine when developing (I had to tweak the way to retrieve my templateUrl in order to be able to compile).

But when compiling with ngc I get:
```Error: No template specified for component MozaikApp```

I have been struggling with that for ever now... Anyone can lead me of a nice way to make it work?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by millerf** [comment]
Understood. 

Thanks

**Comment by lianying** [comment]
Hi @millerf ,
     May I ask how you realized "dynamic templates URL" ?  I also need work for a project that have multiple themes (not only difference CSS but also HTML).  Already try many ways but still have no idea.
    
    Thank you very much.
