### ISSUE TITLE
Module constructor does not get called when using TestBed.overrideProvider

### ISSUE THREAD

**Issue by romiholland** [angular/angular#19161]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When you import a module in TestBed.configureTestingModule and then also use TestBed.overrideProvider, the module's constructor is never called even though it is called when running the same code outside of the testing environment. Without TestBed.overrideProvider, the module's constructor is called when one of its services or components is instantiated.

## Expected behavior

A module's constructor should always get called when it is imported (either directly or transitively) in TestBed.configureTestingModule regardless of whether or not TestBed.overrideProvider is used. 

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/j7f97rncK0uhyaW9kEMC?p=preview
## What is the motivation / use case for changing the behavior?

I need to test a component where important set up work is done in its module's constructor (this is the only way of doing this at the moment, see https://github.com/angular/angular/issues/18032). Without this set up work, the component does not work properly and the tests fail even though everything is working properly outside of the test. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
A workaround for this is to manually force the module's constructor to be called using <code>TestBed.get(ModuleWithUsefulConstructor)</code>

**Comment by JoostK** [comment]
This is working as expected now ([StackBlitz using webcontainers](https://stackblitz.com/edit/node-dz3bjn?file=test%2Fsrc%2Fapp%2Fapp.module.ts,test%2Fsrc%2Fapp%2Fapp.module.spec.ts))
