### ISSUE TITLE
how to remove formArray in Reactive forms

### ISSUE THREAD

**Issue by irfanmayo0786** [angular/angular#19168]
e.g for i'm using this code for creating my survey object onload
` 
 ngOnInit() {
    this.survey = new FormGroup({
      surveyName: new FormControl(''),
      sections: new FormArray([
        this.initSection(), 
      ]), 
    });      
  }

  initSection(){
    return new FormGroup({
      sectionTitle : new FormControl('')
    });
  }
`
OutPut is like that
`
{
  "surveyName": "",
  "sections": [
    {
      "sectionTitle": ""
    }
  ]
} 

`
Now i want to delete the Section Array with key how i can do it?

**Comment by irfanmayo0786** [comment]
should i use remove FormControl? on FormArray if yes then how i can do create a formControl for Formarray??

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
