### ISSUE TITLE
*ngFor with trackBy

### ISSUE THREAD

**Issue by xp44mm** [angular/angular#19164]
## Current behavior

```html
<div *ngFor="let hero of heroes; trackBy: trackByHeroes">
  ({{hero.id}}) {{hero.name}}
</div>
```
and `trackByHeroes` is
```javascript
trackByHeroes(index: number, hero: Hero): number { return hero.id; }
```
the problem is the order of `tackBy`'s parameters, which is `(index, value)`. in **es5** `Array.map` the order is `(value, index, array)`. maybe a lot of people will be confused about it.

## Expected behavior

the order of trackBy's parameters should be same to `Array.map` in es5
```javascript
trackBy(value, index?, array?)
```

**Comment by ciesielskico** [comment]
Found that confusing at first, too.

**Comment by vicb** [comment]
not actionnable
