### ISSUE TITLE
[ Documentation Question / Suggestion ]  Advanced Environment Setup.

### ISSUE THREAD

**Issue by anakinjay** [angular/angular#1916]
After a week of trying, I'm still unable to get anything more than the basic 5 min. quick start functioning. I'm about ready to give up on NG2.   

It seems like there's a lot of manual configuration required that isn't actually documented anywhere.  Like manually configuring the typings file, or importing directives from modules other than angular2/angular2.

As a user ready to give your framework a shot, I should be able at the very least to rely on the documentation explaining to me exactly how to setup the framework properly.  There is no documentation on how to setup anything besides the 5 min. quick start.

For example:
my experience of trying to figure out how to read an attribute from a component went like this:

-browse though api documentation
-found Attribute annotation. No clue what "Directive" is, but it looks like the component syntax so, I'll plug it into the constructor
-compiler error.  WHAT DO YOU MEAN you can't compile?  It's right there in the documentation, I copy and pasted it.
-well docs don't say anything about needing to import Attribute, but component and view are listed in the import statement at the top, so I guess i need to add it in there.
-compiler error.  What?  Attribute not found?  It's right in the bloody documentation....
-flips table

dont mean this to sound negative, but my first experience with NG2 has been an extremely bad one, and if it was for me, I'm sure others have had the same experience.

**Comment by vicb** [comment]
Sorry to learn that.

Angular2 is still in its early stage (developer preview) and there are still too many rough edges.

Be sure that we make our best for users to have the best possible experience but angular2 is moving very fast and sometimes we might break some things or need some time for the doc to catch up!

It would really help us help you if you can submit detailed issues / PRs for any issue you might encounter. Either in this repo or on the doc repo at https://github.com/angular/angular.io

Don't give up, you would regret :)

**Comment by anakinjay** [comment]
I'd like to help out as much as possible. I'm not sure what I have to offer in terms of details or PRs since I can get a working angular 2 environment running.

If I do figure it out, I'll definitely submit my notes. :)

I love the direction you guys are headed in.

**Comment by vicb** [comment]
> since I can get a working angular 2 environment running.

You can open a GH issue with what's not working. It could help us improve the docs or the code.

> I love the direction you guys are headed in.

Thanks !

**Comment by vicb** [comment]
@anakinjay also I forgot to mention the gitter channel: https://gitter.im/angular/angular
There are a bunch of early adopters ready to help there.

**Comment by anakinjay** [comment]
thank you so much!   I'll start posting more specific ideas :)  really appreciate the help!
