### ISSUE TITLE
routerLinkActive doesn't work properly at the beginning in Angular 4

### ISSUE THREAD

**Issue by wandri** [angular/angular#19167]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[?] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I start the app, the routerLinkActive is activated but the element doesn't have the "activated" class.

To quickly understand:

The routerLinkActive is in a component displayed in the component A.

![30341632-0b3608f2-97f7-11e7-9411-81d782f1fa0a](https://user-images.githubusercontent.com/15016833/30361444-5a0a0b1c-9857-11e7-81c3-86307a86d2eb.jpg)

RouterLinkActive, activation is true

![30341655-1f99f268-97f7-11e7-9112-8b084e74c833](https://user-images.githubusercontent.com/15016833/30361450-60cd0dc8-9857-11e7-9274-854d3739fc86.jpg)

But in the dom, there is no active class.

![30341676-3655c16c-97f7-11e7-9fa3-5b33f6591f06](https://user-images.githubusercontent.com/15016833/30361452-6552c05e-9857-11e7-87a3-400ba701d122.jpg)

## Expected behavior

When I start the app and the routerLinkActive is activated, the element musst have the "activated" class.

## Minimal reproduction of the problem with instructions

NOT WORKING on angular 4:   https://embed.plnkr.co/WBzIeI/

Working with angular 2: https://embed.plnkr.co/7KMlY2/

## What is the motivation / use case for changing the behavior?

My menu cant get the nested route. So my UI is bad.

## Environment

<pre><code>
Angular version: X.Y.Z

Not working with: Angular 4.3.6

Working with : Angular 2.

Browser:
- [x] Chrome (desktop) version  60.0.3112.113
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by wandri** [comment]
The only way that I have found to make it work is a hack with template variable and ngClass:

`[routerLinkActive]="['']" [ngClass]="rla.isActive?'active':''"  #rla="routerLinkActive"`

**Comment by hugodes** [comment]
Thanks for submiting I have the same problem on one of my projects.

Issue is still here on version 5.0.0-beta.7

**Comment by ntswor** [comment]
I have the same issue too. Currently working with version 4.4.4.
It worked before with version 4.1.3.

The hack provided by @wandri didn't work for me though. Haven't found out why yet.

**Comment by DenisVuyka** [comment]
We had to stick `@angular/router` to `~3.1.1` because of this problem. The entire application just crashes with 4.x or 5.x so far.

**Comment by jasonaden** [comment]
This should be fixed by an update to how this value is determined the first time through. Please open a new issue if your problem persists.

**Comment by wandri** [comment]
That's right. The plunker with angular 5 (previously angular 4) is working as expected.
Thanks.

**Comment by fmpierce** [comment]
I'm using angular 6 and I have the same problem.

**Comment by fmpierce** [comment]
When I moved routerLinkActive="active" to the <li> instead of the <a> it fixed it.

**Comment by gatodeveloper** [comment]
If you are using `this.router.navigated = false` in the router execution, the routerLinkActive class will not be applied.

**Comment by tomtrung** [comment]
> I'm using angular 6 and I have the same problem.

I had the same problem in Angular 6 when routing programmatically, i.e this.router.navigate, but when I used the [routerLink] directive the styles of the activeClass worked again. Hope this helps.
