### ISSUE TITLE
No Compile-Error for HtmlFile

### ISSUE THREAD

**Issue by houcode** [angular/angular#19165]
Is there a possibility to output a error message with angular/typescript, when the data binding or the name of the variable is wrong?

for example:

{{ classname.check().SOMETHINGSTUPID }}
// In this case, attaching "SOMETHINGSTUPID" to my code doesn't output a error or warning.

or also for: "*ngFoorr". theres no compiler error or any kind of warning. 

thank you

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

Angular Language Services can handle that
