### ISSUE TITLE
Rename NgModule to Module

### ISSUE THREAD

**Issue by NikxDa** [angular/angular#19178]
Hey there,
if there is a reason for the behaviour I am mentioning here, please let me know. I couldn't find any sources explaining the topic.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The Decorator for Angular Modules is `NgModule` while the decorator for e.g. Angular Components is `Component`.

## Expected behavior
Rename `NgModule` to `Module`.

## What is the motivation / use case for changing the behavior?
Consistency.

**Comment by mlc-mlapis** [comment]
@NikxDa ... the reason is to differentiate from modules in ES6, ...

**Comment by pkozlowski-opensource** [comment]
Yes, the word `Module` is super-overloaded in IT (well, same applies to `Component` TBH...) so having one more thing named `Module` wouldn't help. Not to mention that it would be a massive breaking change atm...

Thnx for the proposal, but we will pass on it for now.
