### ISSUE TITLE
HttpClient is asynchronous

### ISSUE THREAD

**Issue by undermoodzyx** [angular/angular#19173]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

 The post method of  ```HttpClient```  is asynchronous. ( I haven't test other http methods of ```HttpClient```)

## Expected behavior

Synchronous  method of ```HttpClient```.

## Minimal reproduction of the problem with instructions

Below is a service  using ```HttpClient``` verifies whether the input code is correct.
```
// Angular Service
@Injectable()
export class VerifyCodeService {

  constructor(
    private http: HttpClient
  ) { }

  public checkCode(params: {[key: string]: any}, header: any[]): Observable<any> {
    let headers = new HttpHeaders().set('content-type', 'application/json');
    if (header !== null) {
      for (let i = 0; i < header.length; i++) {
        headers = headers.append(header[i].name, JSON.stringify(header[i].value));
      }
    }

    return this.http.post(this.verifyCodeUrl(), params, { headers });
  }
}
```
In component, the function using ```VerifyCodeService``` to verify code.
```
// Angular Component
constructor(
    private logger: LoggerService,
    private verifyCodeSev: VerifyCodeService
  ) { }

private checkVerifyCode(): boolean {
    if (!this.stepOneFormGroup.get('verifyCode').value) {
      return;
    }

    const postBody = {
      'mobile': this.stepOneFormGroup.get('phoneNum').value,
      'verCode': this.stepOneFormGroup.get('verifyCode').value
    };
    let isSuccessful = false;
    this.verifyCodeSev
      .checkCode(postBody, null)
      .subscribe((data) => {
        this.logger.log(data); // Note: expected data is null
        this.logger.log('should be step one'); // Note: this line should output message first
        if (!data) {
          isSuccessful = true;
        }
      });

    this.logger.log('should be step two'); // Note: this line should output message later
    return isSuccessful;
  }
```
But, the output message is not correct.
![_20170913163828](https://user-images.githubusercontent.com/17587252/30369870-762c1c58-98a8-11e7-9957-8175f3c91346.png)

## Environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version  61.0.3163.79
 
For Tooling issues:
- Node version: v8.1.4  
- Platform:  Windows 64bits

Others:

</code></pre>
### Angular packages
```
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/platform-server": "^4.3.6",
    "@angular/router": "^4.2.4",
```

**Comment by Toxicable** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

---

It appears that you're getting confused between procedural code and async code in JavaScript, this is not a bug with Angular and therefore this is the incorrect place to be asking for help

**Comment by undermoodzyx** [comment]
Thanks, you just remind me of ```async```.
