### ISSUE TITLE
Date class issue

### ISSUE THREAD

**Issue by hansenyuki** [angular/angular#19175]
I think that there is a problem with the class Date.. it always increments the month field by 1. That means when i put new Date(2017,9,13) it transforms to 13/10/2017 in the view.. 

[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
I'm sorry but this issue is not caused by Angular.

---

`Date` is not defined by Angular, therefore this is not an issue with Angular

**Comment by gkalpak** [comment]
@Toxicable, is right. `Date` is a JavaScript built-in (not provide by Angular).
Also, according to [mdn][1], months are zero-indexed:

> **month**
> Integer value representing the month, beginning with 0 for January to 11 for December.

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
