### ISSUE TITLE
Angularjs Client request to REST API in backend for Authantication filter

### ISSUE THREAD

**Issue by sandeep2244** [angular/angular#19174]
I am using Angular-js  as Front-end  So i pass authentication data with Angularjs POST method 

//$http.post('/api/authenticate', { username: username, password: password })
            //    .success(function (response) {
            //        callback(response);
            //    });

        service.SetCredentials = function (username, password) {
            var authdata = Base64.encode(username + ':' + password);
  
            $rootScope.globals = {
                currentUser: {
                    username: username,
                    authdata: authdata
                }
            };
  
            $http.defaults.headers.common['Authorization'] = 'Basic ' + authdata; // jshint ignore:line
            $cookieStore.put('globals', $rootScope.globals);
        };
  
        service.ClearCredentials = function () {
            $rootScope.globals = {};
            $cookieStore.remove('globals');
            $http.defaults.headers.common.Authorization = 'Basic ';
        };

So now in authentication filter where i have to USE @POST annotation and @ PATH annotation  
for  this (//$http.post('/api/authenticate') path 
please suggest me 

Where as BAckend I use 
Jersey REST API Security

and which is refer form this site
https://howtodoinjava.com/jersey/jersey-rest-security/

**Comment by Toxicable** [comment]
This is the Angular Github repository
See https://github.com/angular/angular.js for the AngularJS repository
