### ISSUE TITLE
FormArray.setErrors() does not work as intended

### ISSUE THREAD

**Issue by FabianMeul** [angular/angular#19170]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Setting `formArray.setErrors();` does not set an error.

## Expected behavior
The formArray should populate the `.errors` property and update its valid state accordingly.

## Minimal reproduction of the problem with instructions
[Plnkr](http://plnkr.co/edit/GldbvNaf5UxktlljkI3M?p=preview)

## What is the motivation / use case for changing the behavior?
I'm implementing a validation that requires certain fields of a FormArray to be unique. If they are not, an error should be displayed on the FormArray level. The documentation clearly states that FormArray inherits `.setErrors()` from AbstractControl.

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
`setErrors` does indeed set the errors. The problem in your example is that you're setting the errors in the constructor, before validation has a chance to run in your form control directives. Once that validation happens, your errors will be overwritten.  You can see in the updated plunker that if `setErrors` runs later, the errors update as expected (http://plnkr.co/edit/j1HHJwky17x79d5T4Ln2?p=preview).   If you need to set errors as soon as the form loads, you can normally achieve this by waiting a tick for the next change detection run.

**Comment by felixlindemann** [comment]
> 
> 
> Thanks @kara. I was calling `setErrors()` inside a `(ngModelChange)` event handler, and it was not working... until I waited a tick with `setTimeout()`.

 

Thanks @mrajcok !!! I was stumbling with this issue for about a week!
here is my solution
```
  const control = this.form.get('fieldname');

  const message = 'myMessage';

  const ex: ValidationErrors = { 'required': true };

  setTimeout(() => {

         control.markAsDirty();

         control.markAsTouched();

         control.setErrors(ex);

  }, 1);

```

**Comment by borriej** [comment]
hmm, i also solved this in the end by adding ```setTimeout()```

e.g.
```
    this.authService.login(value)
      .pipe(
        takeUntil(this.destroy$)
      )
      .subscribe(
        res => {
          //
        },
        err => {
          err.error.errors.forEach(error => {
            if (this.form.get(error.source.parameter)) {
              const obj = {};
              obj['backend'] = error.code;
              setTimeout(() => {
                this.form.get(error.source.parameter).setErrors(obj);
              });
            }
          });
          form.enable();
        }
      );
```

**Comment by mohammedzamakhan** [comment]
setTimeout looks an ugly solution. @kara can we re open this issue?

**Comment by ZenwalkerD** [comment]
Hi All,

Recently in my Angular 7.1.x app project, i faced the same problem. Using setTimeOut works. 
Has this issue fixed in Angular 8? 
Kindly patch it up in angular 7 too. 

My package json looks like this:
```

> `"dependencies": {
>     "@agm/core": "^1.0.0-beta.6",
>     "@agm/js-marker-clusterer": "^1.0.0-beta.6",
>     "@agm/snazzy-info-window": "^1.0.0-beta.6",
>     "@angular/animations": "^7.2.15",
>     "@angular/cdk": "^7.3.7",
>     "@angular/common": "~7.1.0",
>     "@angular/compiler": "~7.1.0",
>     "@angular/core": "~7.1.0",
>     "@angular/flex-layout": "^7.0.0-beta.24",
>     "@angular/forms": "~7.1.0",
>     "@angular/material": "^7.3.7",
>     "@angular/platform-browser": "~7.1.0",
>     "@angular/platform-browser-dynamic": "~7.1.0",
>     "@angular/router": "~7.1.0",
>     "@ng-bootstrap/ng-bootstrap": "^4.2.1",
>     "@types/plotly.js": "^1.44.9",
>     "amazon-cognito-identity-js": "^3.0.13",
>     "aws-sdk": "^2.487.0",
>     "bootstrap": "^4.3.1",
>     "chart.js": "^2.8.0",
>     "chartjs-plugin-annotation": "^0.5.7",
>     "chartjs-plugin-zoom": "^0.7.0",
>     "core-js": "^2.6.9",
>     "date-fns": "^1.30.1",
>     "file-saver": "^2.0.2",
>     "font-awesome": "^4.7.0",
>     "gauge-chart": "^0.4.3",
>     "hammerjs": "^2.0.8",
>     "isomorphic-fetch": "^2.2.1",
>     "jquery": "^3.4.1",
>     "js-marker-clusterer": "^1.0.0",
>     "material-design-icons": "^3.0.1",
>     "material-design-icons-iconfont": "^4.0.5",
>     "moment": "^2.24.0",
>     "ng-multiselect-dropdown": "^0.2.3",
>     "ng2-charts": "^1.6.0",
>     "ng2-pdf-viewer": "^5.3.2",
>     "ng2-simple-timer": "^6.0.0",
>     "plotly.js": "^1.48.3",
>     "popper.js": "^1.15.0",
>     "primeicons": "^1.0.0",
>     "primeng": "^7.1.3",
>     "rxjs": "^6.5.2",
>     "rxjs-compat": "^6.5.2",
>     "snazzy-info-window": "^1.1.1",
>     "tslib": "^1.10.0",
>     "zone.js": "^0.8.29"
>   }`

```
Thanks
