### ISSUE TITLE
Browser Back Button is not changing the route in first, third, fifth,... clicks

### ISSUE THREAD

**Issue by MuhammadZaidSE** [angular/angular#19185]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
</code></pre>

## Current behavior
I hava a route like this `/video/:id`
I go to route `/video/id1` , then `/video/id2` , then `/video/id3` , and so on.

After traversing 2 or more dynamic routes like above, I want to go to back page.
But clicking browser back button does nothing in the first click.
In the second click url changes to previous route,
then in third click it does not change the route,
then in the forth click it changes to previous route.

For example, I am at the route `/vodeo/id3`
Browser back click 1 --> does nothing
Browser back click 2 --> changes to previous route `/video/id2`
Browser back click 3 --> does nothing
Browser back click 4 --> changes to previous route `/video/id1`

## Expected behavior
Route should change to previous in every browser back button click
For example if I am at route `/video/id3`
Browser back click 1 --> change to previous route `/video/id2`
Browser back click 2 --> change to previous route `/video/id1`

## Minimal reproduction of the problem with instructions
make a project with `angular cli 1.4.1`
define a route `/video/:id` pointing to a component video-page-component.
make a video-detail-service to get video details by id.
get the video id from route using ParamMap subscription, and get videos details from video-detail-service using video id.
get the next-video-id from details.
make an anchor tag on video-page view with routerLink pointing to next route `/video/next-video-id`
show the other video details also on video-page view.
click on anchor tag to go to next route, and then next again.
now click browser back button to go to previous page.
it will  not go back in first click.
click again on browser back button.
Now it will go to previous route.
now click again on back button, and route will not change, and so on.

## What is the motivation / use case for changing the behavior?
This is a basic routing bug which needs to be resolved.

## Environment

<pre><code>
Angular Cli version: 1.4.1
Angular version: 4.2.4

Browser:
- [x ] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [x ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [x ] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [x ] IE version XX
- [x ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.2
- Platform:  Windows x64

Others:
-OS Version: Windows 10
-package manager: npm, yarn
</code></pre>

**Comment by Toxicable** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by MuhammadZaidSE** [comment]
I have added the code to plunker
http://plnkr.co/edit/8Cm7NEtGxfVLt47O4LGZ

click on next video link 3 times. then click on browser back button to come to 1st page.
keep an eye on video title, when it changes.

**Comment by MuhammadZaidSE** [comment]
Iframe adds history entry when it loads, so when we press back button it just acts inside iframe.
Can anyone help me disabling iframe history entry.

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by suraj021** [comment]
@MuhammadZaidSE I am facing the same problem. How did you solve it?
