### ISSUE TITLE
ErrorHandler methods should not be internal

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#19181]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The default [ErrorHandler](https://github.com/angular/angular/blob/a56468cf2f4566f23abae262176ac36642033de4/packages/core/src/error_handler.ts#L39) uses some internal method for retrieving the error.

For changing just the way how the error is logged, the complete class needs to be reimplemented.

## Expected behavior
Methods for retrieving the context and original error are not internal and can be used in own implementations.

## What is the motivation / use case for changing the behavior?
reuse of existing methods, no copy - paste of source code.

## Environment

<pre><code>
Angular version: 4.3.6
</code></pre>

**Comment by JoostK** [comment]
Currently the `ErrorHandler` can be used as an interface that only has the `handleError` method. Exposing the `@internal` fields would be a breaking change from that perspective. We could in theory change `ErrorHandler` to really be an interface and have some default implementation that exposes those methods, but that would also be a breaking change for users that _do_ extend `ErrorHandler` (which would no longer be allowed if it's just a type).

Overall, the `_findOriginalError` method really is an implementation detail that we don't want to expose as public/overridable API.
