### ISSUE TITLE
I created a new project with angular cli. Didn't edit any code and just went for ng build --prod. It failed quoting Can't resolve './$$_gendir/app/app.module.ngfactory'. Not sure why this issue is coming up.

### ISSUE THREAD

**Issue by Shashikant-Jha** [angular/angular#19191]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jotatoledo** [comment]
Please use the issue template, and most likely your issue should be addressed in the angular cli repo

**Comment by tytskyi** [comment]
@Shashikant-Jha update your cli version or fixate `enhanced-resolve` package as top level dependency with specific version: `npm install enhanced-resolve@3.3.0 --save --save-exact`

See https://github.com/angular/angular-cli/issues/7151

Please close the issue, since there is no bug with angular itself.

**Comment by vicb** [comment]
Please report the issue on the cli repo https://github.com/angular/angular-cli
