### ISSUE TITLE
TestBed injecting real service instead of the provided mock service

### ISSUE THREAD

**Issue by wardbell** [angular/angular#19194]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Testing a component that injects Service A which depends on Service B.
Want to test the component with a mock of Service A (MOCK-OF-A) that itself has no dependencies.

This works when I test the component _as a class_ w/o `TestBed.createComponent`, providing the with the MOCK-OF-A.

But when I test the component using `TestBed.createComponent` with the MOCK-OF-A, the TestBed injects the REAL Service A, not the mock!

I can hardly believe it myself. I've attached a plunker that demonstrates the problem.

I DO hope I've just done something incredibly stupid.

## Expected behavior

Test should use the MOCK-OF-A.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/Z4gj8ErDdKpwrkoV8dua?p=preview

`mock-app` is a  version of the application cutdown for this issue.
It defines the component and the two services (plus a model)

`mock-app.spec` holds two tests, one that works (no TestBed) and one that doesn't.

## Environment

<pre><code>
Angular version: 4.3.6

v4.3.6 is the current version as I write this.

Browser:
- [x] Chrome (desktop) Version 60.0.3112.113
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Mac

**Comment by gkalpak** [comment]
FWIW, this only happens when the component defines its own `providers` array. I assume `TestBed.configureTestingModule()` creates a module whose root injector uses the `MockHeroDetailsService`, but component's injector is still configured with `{provide: HeroDetailsService, useClass: HeroDetailsService}`.

No idea what the right way to solve this is (or if it is even possible)

**Comment by wardbell** [comment]
**YOU ARE RIGHT**. I didn't see that the component had a provider. Embarrassed, chastened, and relieved.

Easily solved with a  override
```
TestBed.overrideComponent(HeroDetailComponent, {
  set: {
    providers: [
      { provide: HeroDetailService, useClass: MockHeroDetailService }
    ]
  }
});
```
Sigh!

**Comment by gkalpak** [comment]
Aha! I (quite embarrassingly) didn't know you can overwrite specific properties like that :grin:
I do now :tada: 👍
