### ISSUE TITLE
Angular 5.0.0-beta.7 i18n extraction not working

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#19198]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using Angular CLI's `ng xi18n` command will extract messages from Angular 4.x to 5.0.0-beta.6 but not on 5.0.0-beta.7.

## Expected behavior

Message extraction should work using beta.7.

## Minimal reproduction of the problem with instructions
```
ng new test-proj
cd test-proj
ng generate component i18n-test
echo "<p i18n>Hello world</p>" > ./src/app/i18n-test/i18n-test.component.html
npm run ng -- xi18n
stat src/messages.xlf # file exists
rm src/messages.xlf
# update to beta.6
npm i @angular/{animations,common,compiler,core,forms,http,platform-browser,platform-browser-dynamic,router,compiler-cli,language-service}@5.0.0-beta.6 typescript@2.5.1
npm run ng -- xi18n
stat src/messages.xlf # file exists
rm src/messages.xlf
# update to beta.7
npm i @angular/{animations,common,compiler,core,forms,http,platform-browser,platform-browser-dynamic,router,compiler-cli,language-service}@5.0.0-beta.7 typescript@2.5.1
npm run ng -- xi18n
stat src/messages.xlf # file does not exist
```

## Environment

<pre><code>
Angular version: 5.0.0-beta.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.1
- Platform:  Windows 

Others:

</code></pre>
/cc @ocombe

**Comment by vicb** [comment]
@ocombe ypu might want to discuss it with @matsko - I think he changed the extraction

**Comment by ocombe** [comment]
This is because genDir has been replaced by outDir in the new pipeline. I've created a fix for the cli.
