### ISSUE TITLE
HttpClient posting number zero not working

### ISSUE THREAD

**Issue by mayrmax** [angular/angular#19195]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Number zero (0) doesn't get sent via post - body.
All other numbers seem to work fine.

## Expected behavior

It should be possible to post a 0 via post - body.

## Minimal reproduction of the problem with instructions

DEMO: https://plnkr.co/edit/YYQfVJYAJjWyy6eMaR5Q?p=preview

Open dev tools and look at the request. 

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by Toxicable** [comment]
works fine here 
https://plnkr.co/edit/Te4F09OZbiwfwcB1VjaL?p=preview
- open dev tools
- clear network log
- click post
- inspect successful request

**Comment by mayrmax** [comment]
you didn't save your plnkr it seems looks the same as mine and still ha sthe problem that there is no body.

**Comment by ssuperczynski** [comment]
@mayrmax see this plnkr https://plnkr.co/edit/GS1LRBkUDdW9n0BpNaRc?p=preview
It works fine

**Comment by Toxicable** [comment]
@mayrmax I think you're right!
see @ssuperczynski it's the same as the one I made, working fine

**Comment by mayrmax** [comment]
see attacked plnkr for clarification:
https://plnkr.co/edit/YYQfVJYAJjWyy6eMaR5Q?p=preview

i can post a 0 but the 0 doesn't get sent as a body as it should be.

**Comment by Konstruktour** [comment]
i'm with @mayrmax - httpbin post should return a 0 but it returns empty data.

think the problem is located in angular/client.ts line 374 
options.body || null
so if body = 0, it will return null...
