### ISSUE TITLE
Center tag not working in Anuglar 4

### ISSUE THREAD

**Issue by vm32666** [angular/angular#19204]
<center></center> not working in Angular 4.

**Comment by pkozlowski-opensource** [comment]
> Deprecated
This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Avoid using it and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center
