### ISSUE TITLE
ViewManager: split `inPlace` host views into root and free host views.

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1920]
Previously, there was only one method called `createInPlaceHostView`,
which would always hijack the given element as the host element. It was used
for bootstrapping a root component as well as in components that directly modify the DOM
and want to place a new Angular component into this custom DOM.

However, this had the following problems:

1. Hijacking an existing element does not allow to move the host view into a ViewPool.
2. Hijacking an existing element requires the user of the `ViewManager` to pass in a selector to 
    this element. We can't allow to pass in the real element as `ViewManager` should be independent
    of the concrete renderer and we should potentially be able to use it in a WebWorker.

Solution:

1. Introduce `createRootHostView` which uses the previous semantics of hijacking an existing element located by a selector, which is by default the selector of the component. This is used during bootstrap.
2. Introduce `createFreeHostView` which creates a new host element but does not attach the created host element anywhere in the DOM (hence the name `free`). This is used by components that modify the DOM directly, and because of this are also able to attach this free host view.

**Comment by matanlurey** [comment]
Could you help clarify if this removes the necessity to query select when inserting dynamically?

**Comment by tbosch** [comment]
Yes, it does. So the idea is that calling `DynamicComponentLoader.loadIntoNewLocation` also creates the host element of the component, but does not attach it. Then a user can manually attach it to the DOM. To get the host element out of the created `ComponentRef` the method `DomRenderer.getHostElement(componentRef.hostView)` can be used.
