### ISSUE TITLE
Performance issue with IE11 when trying to load more records in a single page.

### ISSUE THREAD

**Issue by kkamalesh** [angular/angular#19205]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am displaying the records in a table with pagination and have a button to show all the records in a single table (pagination will be hidden). In IE when i click the show all button it takes more time to load the records where as in other browsers chrome, safari its faster.The records i am trying is 800.

## Expected behavior

Loading of records into table in IE11 should not take more time.

## Environment

<pre><code>
Angular version: 4.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version 11.0
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
I don't think this is an issue with Angular.
If you disagree then please post a **minimal** reproduction of where this performance degradation occurs.

**Comment by kemsky** [comment]
IE is about 10x slower than Chrome, check using `enableDebugTools`. You can try use `OnPush` change detection policy or even disabling change detection for table using `ChangeDetectorRef`.

**Comment by vicb** [comment]
There is nothing we can do without a repro.
