### ISSUE TITLE
Extracting duplicate resolvers causes weird behaviour with AOT compilation

### ISSUE THREAD

**Issue by textbook** [angular/angular#19206]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Assume an existing resolver `MessageResolver`, then create two objects based on it:

```typescript
export const originalResolver = { message: MessageResolver };
export const duplicateResolver = Object.assign({}, originalResolver);
```
Use these as the `resolve` values for two routes:

```typescript
{ path: 'original', component: ChildComponent, resolve: originalResolver },
{ path: 'duplicate', component: ChildComponent, resolve: duplicateResolver },
```

If you're using JIT compilation, you can visit either route and see the resolved data get loaded. But if you're using AOT compilation, when you visit `/duplicate` an empty object `{}` will get resolved instead of the expected data.

## Expected behavior

Both routes should get the correct data resolved, whether using JIT or AOT compilation.

## Minimal reproduction of the problem with instructions

I created a demo app using the Angular CLI (v1.4.2) and published it at https://github.com/textbook/angular-resolver. I have deployed the application to Cloud Foundry so you can see it happen:

 - JIT compiled: https://angular-resolver-jit.apps.pcfone.io
 - AOT compiled: https://angular-resolver-aot.apps.pcfone.io/

Without the above copying using `Object.assign`, the app works correctly in both AOT and JIT.

## What is the motivation / use case for changing the behavior?

Imagine you have different routes that share some base set of resolvers but with other additional resolvers on one or all of them; it would be nice to reduce duplication by extracting the overlap, and (perhaps more importantly) have that behave consistently between JIT and AOT builds.

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [x] Chrome (desktop) version 60.0.3112.113
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 55.0.3
- [x] Safari (desktop) version 10.1.2
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.1
- Platform:  Mac (OS X Sierra)

Others:

</code></pre>

**Comment by textbook** [comment]
I realised this had been open for a while, so I created [a new branch](https://github.com/textbook/angular-resolver/tree/v8) to figure out whether this is still a problem (as of Angular 8.2.3). I've updated the apps and **this issue persists**:

 - JIT compiled: https://angular-resolver-jit.apps.pcfone.io/
 - AOT compiled: https://angular-resolver-aot.apps.pcfone.io/

**Comment by JoostK** [comment]
Hi @textbook, thanks for updating the repro to Angular 8.0. I updated it to Angular 9.0 to test it with Ivy, and the issue has been resolved in Ivy :-)
