### ISSUE TITLE
doc and toString of Activation and ChildActivation events

### ISSUE THREAD

**Issue by jnizet** [angular/angular#19209]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The documentations of ChildActivationStart, ChildActivationEnd, ActivationStart and ActivationEnd are identical:

> Represents the **start of end of** the Resolve phase of routing

(emphasis mine).

I guess it should be **start of** for the start event, and **end of** for the end event.
I also guess there **should** be a difference between Activation and ChildActivation documentations, otherwise what's the point of having these two kinds of events.

Moreover, the toString() method of `ActivationStart` returns:

    return `ChildActivationStart(path: '${path}')`;

instead of (I guess) 

    return `ActivationStart(path: '${path}')`;

The same issue exists for `ActivationEnd`.

Finally, the documentation on those two sets of events has a circular loop: the doc for the start event says:

> See note on {@link ActivationEnd} for use of this experimental API.

and the ActivationEnd doc doesn't have any note, other than

> See note on {@link ActivationStart} for use of this experimental API.

This is all quite confusing.

## Expected behavior

The documentation should really describe what each event actually represents, and the toString() should contain the actual name of the event. There should be a real note on the use of the experimental API.

## Minimal reproduction of the problem with instructions

NA

## What is the motivation / use case for changing the behavior?

Understanding what these events represent

## Environment

<pre><code>
Angular version: 5.0.0.beta.7 (current code on master)

Browser:
NA
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
@jnizet would you mind submitting a PR ?

**Comment by jnizet** [comment]
@vicb I can fix the simple toString issue, but I'm not sure what these events actually represent and when they are fired, so I don't know what the documentation should be, and what the experimental note should be. 

I guess they're in fact not linked to the resolve phase at all, since there is already a ResolveStart event that also has the same documentation.

**Comment by vicb** [comment]
There is already a PR pending for the toString fix.
@jasonaden will improve the doc

**Comment by wKoza** [comment]
@vicb , why have you closed this issue ? This problem (concerning the documentation) is still current.
For the anecdote : https://github.com/angular/angular/pull/19147
