### ISSUE TITLE
Localized pipe not working on routerLink that has outlets

### ISSUE THREAD

**Issue by pfrendo** [angular/angular#19201]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I set up `LocalizeRouterModule` and I try to attach `| localize` pipe to `[routerLink]="[{outlets: { modal: ['login'] } }]"` it gives an error that it can't match any routes.

I tried the following:
 -  `[routerLink]="[{outlets: { modal: ['login'] } }] | localize"`
 -  `[routerLink]="[{outlets: { modal: ['login' | localize] } }]"`
 -  `[routerLink]="[{outlets: { modal: ['login'] }  | localize }]"`

None work.

## Expected behavior

I expect that it should find the localized route and works correctly.

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [X] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
LocalizeRouterModule / localize pipe are not from Angular. 
You should report an issue to that project.

**Comment by pfrendo** [comment]
@vicb my bad :) , leaving a reference to the issue I created on the correct repo in case someone is on this thread

https://github.com/Greentube/localize-router/issues/75
