### ISSUE TITLE
angular async filter error rootScope infdig

### ISSUE THREAD

**Issue by TonyYule** [angular/angular#19211]
I defined the filter to query the data asynchronously, and I can get the results I want data but the console displays the error
` app.register.filter('userDept', function($http,$rootScope) {

    var apiUrl = '../partners/dept?id=';

    var m = new Map();

    // m.set("0000000056530ce501574a7ff6200367", "data1");

    // m.set("a77523a7b5ff44f1b24a23ewfvcb61785424bc53", "data2");

    function userDeptFilter(input, field) {

        if (input) {

            // console.log('input field', input);

            if (m.get(input)) {

                return typeof input !== 'function' ? JSON.parse(m.get(input)) : undefined;

            } else {

                cached[input] = $http({

                    method: 'GET',

                    url: apiUrl + input

                }).success(function (info) {

                    m.set(input,info);

                    return info;

                    // console.log('result for', info);

                });

            }

        }

    }

    userDeptFilter.$stateful = true;

    return userDeptFilter;

});`
The error message
`Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.6/$rootScope/infdig?p0=10&p1=%5B%5D
at angular.js:38
at n.$digest (angular.js:15797)
at n.$apply (angular.js:16030)
at g (angular.js:10545)
at K (angular.js:10717)
at XMLHttpRequest.z.onload (angular.js:10658)

angular.js:38 Uncaught Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.6/$rootScope/infdig?p0=10&p1=%5B%5D
at angular.js:38
at n.$digest (angular.js:15797)
at n.$apply (angular.js:16030)
at g (angular.js:10545)
at K (angular.js:10717)
at XMLHttpRequest.z.onload (angular.js:10658)`
Don't know why, please help! My code reference is modified as follows:[thiis](http://plnkr.co/edit/EK2TYI1NZevojOFDpaOG?p=preview)

**Comment by githubmann** [comment]
report to [angularjs repo](https://github.com/angular/angular.js), will be greater.

**Comment by TonyYule** [comment]
@githubmann  Oh, thank you

**Comment by vicb** [comment]
wrong repo
