### ISSUE TITLE
Component cannot be used in two different modules in Angular

### ISSUE THREAD

**Issue by Gangadharbc** [angular/angular#19214]
'app-header' is not a known element:
1. If 'app-header' is an Angular component, then verify that it is part of this module.
2. If 'app-header' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<app-header></app-header>
Users
<router-outlet></router-outlet>

**Context**:
I have created a component of app-header which includes the routing part. If i include <app-header> in Home, Dashboard component it is working fine but if i include in User is through an error(user is a module which is implemented with lazyload). Can any one help to resolve this.

**Also tried with:**
-->Added the header component in User module, but landed with an error of:
Error: Type HeaderComponent is part of the declarations of 2 modules: AppModule and UserModule! Please consider moving HeaderComponent to a higher module that imports AppModule and UserModule. You can also create a new NgModule that exports and includes HeaderComponent then import that NgModule in AppModule and UserModule.
Error: Type HeaderComponent is part of the declarations of 2 modules: AppModule and UserModule! Please consider moving HeaderComponent to a higher module that imports AppModule and UserModule. You can also create a new NgModule that exports and includes HeaderComponent then import that NgModule in AppModule and UserModule.

-> Created a shared module and included the header component in it, but not succeeded 

Thanks,
Ganga

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
