### ISSUE TITLE
Reactive Forms + AOT in 5.0.0-beta.7 - StaticInjectorError:  No provider for NgForm

### ISSUE THREAD

**Issue by xbtequila** [angular/angular#19219]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When compiling an App with Reactive Forms using AOT in 5.0.0-beta.7 i'm getting the following Error when navigating to the Form: 

## Expected behavior

Reactive Forms should work like in beta.6

## Minimal reproduction of the problem with instructions

test.module.ts
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { TestComponent } from './test.component';

@NgModule({
    declarations: [ TestComponent ],
    imports: [ CommonModule, ReactiveFormsModule ],
    exports: [ TestComponent ],
    providers: [],
})
export class TestModule {}
```

test.component.ts
```
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';

@Component({
    selector: 'app-form',
    templateUrl: './test.component.html',
    styleUrls: ['./test.component.css']
})
export class TestComponent implements OnInit {

    form: FormGroup;

    constructor() { }

    ngOnInit() {
        this.form = new FormGroup({
            name: new FormControl('test')
        });
    }
}
```

test.component.html
```
<form [formGroup]="form">
    <input type="text" formControlName="name">
</form>
```

## Environment

<pre><code>
Angular version: 5.0.0-beta.7

Browser:
- [x] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 10.1.2
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

@angular/cli: 1.5.0-beta.0
node: 7.5.0
os: darwin x64
@angular/animations: 5.0.0-beta.7
@angular/common: 5.0.0-beta.7
@angular/compiler: 5.0.0-beta.7
@angular/core: 5.0.0-beta.7
@angular/forms: 5.0.0-beta.7
@angular/http: 5.0.0-beta.7
@angular/platform-browser: 5.0.0-beta.7
@angular/platform-browser-dynamic: 5.0.0-beta.7
@angular/router: 5.0.0-beta.7
@angular/cli: 1.5.0-beta.0
@angular/compiler-cli: 5.0.0-beta.7
@angular/language-service: 5.0.0-beta.7
typescript: 2.4.2

</code></pre>

**Comment by AustinMatherne** [comment]
Not sure if it's the same bug, but I'm seeing the same error after upgrading from 4.3.6 to 4.4.1.

**Comment by Toxicable** [comment]
Can confirm this for v4.4.1 only when running in AOT
To Reproduce
`ng new noformprovider`
Replce app.component.ts with
```
@Component({
  selector: 'app-root',
  template: `
  <form [formGroup]="g" >
    <input formControlName="name" />
  </form>
  `
})
export class AppComponent{
  g = new FormGroup({
    name: new FormControl('Toxicable')
  });
}
```
`ng serve --aot`
open up browser and inspect console for error:
>No provider for NgForm!

**Comment by alexzuza** [comment]
I think the problem here is `forms.metadata.json` that angular published on npm

Let's see why..  

I compared jit and aot code generated by angular 5.0.0-beta.7.
Angular generates wrong reference to [ControlContainer provider](https://github.com/angular/angular/blob/5.0.0-beta.7/packages/forms/src/directives/reactive_directives/form_group_directive.ts#L20-L23)(`useExisting`) for `FormGroupDirective`

**jit** 

```
jit_providerDef_7(2048,null,jit_ControlContainer_8, null,[jit_FormGroupDirective_6]),
                                                               ^^^^^^^^^^^^^^^^
                                                                  correct
```

**aot**
```

i0.ɵprd(2048, null, i1.ControlContainer, null, [i1.NgForm]),
                                                  ^^^^^
                                                  wrong
```
Then i investigated how angular gets reference and found out the following

**forms.metadata.json angular 4.3.6**

```
"ɵl": {
      "provide": {
        "__symbolic": "reference",
        "name": "ControlContainer"
      },
      "useExisting": {
        "__symbolic": "reference",
        "name": "FormGroupDirective"
      }
},
```
**forms.metadata.json angular  since 4.4.x**

```
"ɵl": {
  "__symbolic": "reference",
    "name": "ɵe"
},
```
where `ɵe`
```
"ɵe": {
  "provide": {
    "__symbolic": "reference",
      "name": "ControlContainer"
  },
  "useExisting": {
    "__symbolic": "reference",
      "name": "NgForm"
  }
},
```

**form.d.ts**
```

export { formDirectiveProvider as ɵe } from './src/directives/ng_form';
...
export { formDirectiveProvider as ɵl } from './src/directives/reactive_directives/form_group_directive';
```

I think it can be related with the fact that `NgForm` directive [declares provider](https://github.com/angular/angular/blob/5.0.0-beta.7/packages/forms/src/directives/reactive_directives/form_group_directive.ts#L63) with the same name as `FormGroupDirective` https://github.com/angular/angular/blob/5.0.0-beta.7/packages/forms/src/directives/ng_form.ts#L21-L25

**Comment by bjornharvold** [comment]
Same here in 4.4.1

**Comment by PierreRochard** [comment]
👍 same here, just updated to 4.4.1

**Comment by fpmk** [comment]
Updated to 4.4.1 and get same error, but reverting to 4.3.6 not helped, removed all cache, node_modules and installed fresh version.

**Comment by alexzuza** [comment]
@fpmk Can you share small repo to reproduce it on 4.3.6?

**Comment by fpmk** [comment]
@alexzuza sorry it was my fault, I have ^4.3.6 and when I start npm install it installs me 4.4.1. 4.3.6 it seems fine.

**Comment by dessalines** [comment]
Verified that this works fine in `4.3.6`, but is broken in `4.4.1`

**Comment by dottodot** [comment]
Yeah same here in 4.4.1. I've reverted to 4.3.6 and that's ok.

**Comment by qaznine** [comment]
+1

**Comment by smoke** [comment]
Same here with 4.4.1 and AOT using `[formControl]="myFormControl"` throws `No provider for NgModel!` and `[formGroup]="myForm"` throws `No provider for NgForm!`

With 4.3.6 all is working.

**Comment by cristhiank** [comment]
Same here with 4.4.1 and AOT. I'm getting 
`ERROR Error: No provider for NgForm!
    at injectionError (core.es5.js?de3d:1169)
    at noProviderError (core.es5.js?de3d:1207)
    at ReflectiveInjector_._throwOrNull (core.es5.js?de3d:2649)
    at ReflectiveInjector_._getByKeyDefault (core.es5.js?de3d:2688)
    at ReflectiveInjector_._getByKey (core.es5.js?de3d:2620)
    at ReflectiveInjector_.get (core.es5.js?de3d:2489)
    at resolveNgModuleDep (core.es5.js?de3d:9489)
    at NgModuleRef_.get (core.es5.js?de3d:10577)
    at resolveNgModuleDep (core.es5.js?de3d:9489)
    at NgModuleRef_.get (core.es5.js?de3d:10577)`

**Comment by ocombe** [comment]
Thanks @alexzuza for tracking the root cause. Working on a fix right now.

**Comment by TahaDiNero** [comment]
@ocombe Any release soon for 4.4.x ??
Thanks

**Comment by bmayen** [comment]
@TahaDiNero "Working on a fix right now" :)

**Comment by ocombe** [comment]
@TahaDiNero I don't know when we will release a new version with the fix, it'll be this week but not sure which day yet

**Comment by TahaDiNero** [comment]
@ocombe @bmayen  This week will be great thanks a lot for all.

**Comment by vicb** [comment]
The release will probably happen later today.
Sorry for the glitch !

**Comment by bukharin** [comment]
I try to update to `4.4.2` but has no effect. I still get `No provider for NgModel!` in AOT mode

**Comment by Toxicable** [comment]
@IgorMinar Can confirm that this is still and issue on v4.4.2
You can reproduce it with the instructions I provided above which produces the error 
>Error: No provider for NgForm!

**Comment by timdoes** [comment]
I can confirm this as well

**Comment by ocombe** [comment]
yes 4.4.2 doesn't include this patch because we had problems with our CI, we'll have another release 4.4.3 tomorrow with it...

**Comment by maximebourdel** [comment]
I think I got the same for 4.2.x
For those who don't know how to set 4.3.6 i did :

- go to package.json
- get the version number from one one the "@angular"
ex :
     "@angular/common": "^4.2.6"
- replace every "^4.2.6" into "~4.3.6"  (be careful tu change the ^ into ~)
- then I ran "npm install"

and it worked for me :)  (checked with "ng -v")

hope it helped.

**Comment by devoto13** [comment]
@maximebourdel Because `^4.2.6` will install `4.4.2` and `~4.3.6` will install `4.3.6`. You can read more about [caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) and other specifications and use [tester](http://jubianchi.github.io/semver-check/) to play with it.

**Comment by feelthescintillation** [comment]
What version will have this issue solved ? I read multiple questions related to same issue stating 
reactive forms failing in AOT.
One more question is AOT not production ready ?

**Comment by mlc-mlapis** [comment]
... it should be 4.4.3.

**Comment by IgorMinar** [comment]
I cherry-picked the fix for the into the 4.4.x branch and I'm about to cut the 4.4.3 release that will resolve this problem.

**Comment by IgorMinar** [comment]
4.4.3 is out

**Comment by danwulff** [comment]
@IgorMinar 4.4.3 fixed the issue for me. Thanks!

**Comment by timdoes** [comment]
I can confirm that v4.4.3 fixed the issue as well.

**Comment by jponeill** [comment]
@IgorMinar Can the fix be made to the 5.0.0-beta.x branch as well?

**Comment by Taha-Di-Nero** [comment]
I confirm problem resolved.
Thanks for all.

**Comment by alexanderknapstein** [comment]
Thanks to all. The update fixes the problem!

**Comment by George35mk** [comment]
run `npm update` and is gona fix the problem

**Comment by spock123** [comment]
Hey guys, no news about a 5.0.0 update as well? We're pretty stuck here as we cannot regress to 4.x because of HttpClientModule use... really hoping for a solution 

Maybe a solution is already out there for 5.0; in that case please disregard this comment.

Thanks again, guys

**Comment by jponeill** [comment]
This still doesn't appear to be fixed in the 5.x branch. Coming soon?

**Comment by intellix** [comment]
Workaround: `npm i @angular/forms@5.0.0-beta.6`

**Comment by andreypelykh** [comment]
I had the same issue with 4.2.4 version. I've just made next steps:
* replace '4.2.4' with '4.4.3' in package.json file (only for angular packages);
* run `npm i` or `yarn`;

 and it works now. Thanks for everyone!

**Comment by filipesilva** [comment]
There has been a report in Angular CLI of another library that suffered from this problem with Angular v5 (https://github.com/angular/angular-cli/issues/9383, more info in https://github.com/psykolm22/angular-google-place/issues/29#issuecomment-360884843). Maybe this is still a problem.

**Comment by jdhines** [comment]
Thanks for this. I was on 4.4.1, and the error I got didn't even point to ng-forms. It just said `No provider for e!`.

**Comment by SalilGokhale** [comment]
I am experiencing this same 'No provider for e!' error on v5.2.7. Any ideas?

**Comment by fontenele** [comment]
The same on 5.2.9

**Comment by salcott** [comment]
--prod flag, `No provider for e!`, 4.4.2, every view which contains a form...

**Comment by cpower1994** [comment]
--prod flag on 5.2.0 giving me the same issue

**Comment by tallcoder** [comment]
I am hitting the same problem with 7.2.7
