### ISSUE TITLE
BrowserAnimationsModule not being parsed as an NgModule

### ISSUE THREAD

**Issue by tme321** [angular/angular#19210]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have a [project](https://github.com/tme321/Unopinionated-Angular) that has 2 code bases.  One is a component library and everything works as I expect.  The project also contains a demo application that uses the library.  The project uses a custom set of build scripts for the library.  The demo uses 2 different webpack configs ejected from the angular cli.  One for development doing Jit and the other is for deployment that should compile the app in aot mode into bundles the same way the cli does.

The issue I have is that the AoT compilation of the demo + library does not work.  Compilation fails with the error "ERROR in Error: BrowserAnimationsModule is not an NgModule".  If I comment out BrowserAnimationsModule from the main App Module the code compiles correctly and boots but then angular fails when the animations try to execute, which makes sense.  But I don't understand why the compilation fails when I include BrowserAnimationsModule.

There is an issue [here](https://github.com/angular/angular/issues/15229) that is the same problem however the fix in that issue was to delete node_modules and reinstall.  I have deleted node_modules, run npm clean cache, and then run npm i multiple times and it never fixes the issue.

I have also tried cloning the repo out into a clean directory and compiling the new copy.  I get the same error when I do that.

This might very well be an issue with my project but I cannot figure it.  I've been trying for 2 days to figure this out and nothing I do works.

The library is built and bundled with the npm scripts build and bundle.  The development jit version of the demo + library is tied to the npm start script.  These both seem to work correctly.

The demo + library compilation and bundling in aot is executed with the npm buildDemo script.  This is the part of the process that fails and shows the compilation error.  Any help here would be much appreciated.

## Expected behavior
AoT compilation to not throw "BrowserAnimationsModule is not an NgModule" error.

## Minimal reproduction of the problem with instructions
Clone the [repo](https://github.com/tme321/Unopinionated-Angular) and after running "npm i" run "npm run buildDemo"

## What is the motivation / use case for changing the behavior?
I want to aot compile the demo + library together so that I can deploy it as part of the documentation.

## Environment

<pre><code>
Angular version: 4.3.6
All of the @angular libraries are on 4.3.6 including the compiler-cli.

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10
- Platform:  Windows 10

Others:
None that I know of.
</code></pre>

**Comment by matsko** [comment]
@chuckjaz can you please look into this?

**Comment by chuckjaz** [comment]
The reference repo seems broken.

I get the following error:

```
/Users/chuckj/bugs/19210/Unopinionated-Angular/node_modules/license-webpack-plugin/dist/LicenseWebpackPlugin.js:54
            throw new LicenseWebpackPluginError_1.LicenseWebpackPluginError(ErrorMessage_1.ErrorMessage.OUTPUT_TEMPLATE_NOT_EXIST, this.options.outputTemplate);
            ^
```

It seems to have hard coded dependencies.

**Comment by mhevery** [comment]
This issue seems abandoned without any reproducible instruction.  We are closing the issue. If you have reproducible instructions please file a new issue.

**Comment by tme321** [comment]
I moved to ngpackagr a long time ago with this repo and haven't had issues with it since.  I didn't realize anyone was still looking at this.  Sorry.
