### ISSUE TITLE
Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator'?

### ISSUE THREAD

**Issue by iTwangcj** [angular/angular#19212]
Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/wangchengjun/www/yooli/mock/ng4-mock/backend/test123/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in /Users/wangchengjun/www/yooli/mock/ng4-mock/backend/test123/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in /Users/wangchengjun/www/yooli/mock/ng4-mock/backend/test123/node_modules/@angular/core/core.d.ts

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Mariusz-v7** [comment]
I'm having exactly the same issue after updating angular from 4.3.4 to 4.4.1

"resolving symbol ɵe in ..../@angular/core/core.d.ts "

@Toxicable are you sure that this is not @angular issue?

**Comment by Toxicable** [comment]
@Mariusz-v7 yup
This is generally casued by some other error with your application.
Unless you can produce a **minimal** reproduction point to Angular specifically causing this error.

**Comment by Mariusz-v7** [comment]
Ok, I can confirm that this is not angular's issue. I've fixed mine by cleaning out whole project and building it from the beginning. Apparently there had to be some leftovers of .js transpiled files.

**Comment by newuser44** [comment]
How was this fixed.  I have the same problem but the internet doesn't seem to explain much of what is going on?   Is it a problem with Angular core or some file that is using angular core?

**Comment by sambhuWeb** [comment]
@Mariusz-v7 is very keen to close the ticket. Seems as he gets bonus for closed ticket. 

This issue is not fixed.
