### ISSUE TITLE
(AOT): ngc generates incorrect import paths for index files

### ISSUE THREAD

**Issue by kemsky** [angular/angular#19228]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Assume we have `index.ts` file re-exporting `Component` class. 
Currently we can import `Component` class from this file:
```typescript
import {Component} from '/components';
import {Component} from '/components/';
import {Component} from '/components/index';
```
First two imports with generate the following js:
```javascript
import {Component} from '/componentsindex';
```

## Expected behavior
Anything except invalid `componentsindex` or at least compilation error.

## Environment

<pre><code>
Angular version: 5.0.0-beta-7

For Tooling issues:
- Node version: 8.3.4
- Platform:  Windows
- TypeScript: 2.5.2

**Comment by Toxicable** [comment]
Can you make a small reposity showcasing this issue

**Comment by alexeagle** [comment]
@tbosch we need to kill the index re-writing feature in tsickle; newer closure compiler doesn't need it

**Comment by chuckjaz** [comment]
@alexeagle The index rewriting was removed. Is this still an issue?

**Comment by alexeagle** [comment]
@kemsky please re-open if it's not fixed in latest 4.x or 5.0 releases.
