### ISSUE TITLE
Side effect on isDevMode()

### ISSUE THREAD

**Issue by delasalle-sio-olivon** [angular/angular#19220]
https://github.com/angular/angular/blob/aeb98dbcdfec5a2e0f7b6ae167a10bd3e15f5096/packages/core/src/application_ref.ts#L65

It look like we could use isDevMode() to know if we are in dev mode. But if we call this before enableProdMode() it just break the app with this side effect. (Just look this)

I don't know if it's a problem, but now you can do what you want.

**Comment by vicb** [comment]
does not seem to be an issue?
