### ISSUE TITLE
HttpClient - 'if' condition always true?

### ISSUE THREAD

**Issue by snerks** [angular/angular#19223]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In the following source code for HttpClient:
[https://github.com/angular/angular/blob/b6431c60e66d0b4cdce17dff64872ddf86e70139/packages/common/http/src/client.ts#L355](https://github.com/angular/angular/blob/b6431c60e66d0b4cdce17dff64872ddf86e70139/packages/common/http/src/client.ts#L355)

The expression appears to evaluate to `true` always, since the result of a double-exclamation on the LHS (`!!options.headers`) will be boolean (`true | false`), such that it is always `!== undefined`.

## Expected behavior

The expression could evaluate to false, to match the intention.

## What is the motivation / use case for changing the behavior?

The intent is unclear, given that the expression appears to always evaluate to `true`.

## Environment

<pre><code>
Angular version: X.Y.Z
N/A

Browser:
N/A
 
For Tooling issues:
N/A

Others:
N/A

**Comment by Toxicable** [comment]
That's not correct, try this in your console
```
!!false

!!true

!!{}

!!undefined
```

**Comment by snerks** [comment]
Results:

`false`
`true`
`true`
`false`

**Comment by gkalpak** [comment]
Good catch, @snerks 😳

This has no effect on the resulting behavior, because the `HttpRequest` ends up with an empty `HttpHeaders` object anyway (just taking different code paths), but makes sense to fix.
(PRs welcome :wink:)

**Comment by snerks** [comment]
Thanks @gkalpak. This leaves the question: what is the intent of the `if` test?

**Comment by gkalpak** [comment]
My guess is that `if (!!options.headers) {` was the intention. Only @alxhub could know for sure :grin:
