### ISSUE TITLE
`gulp test.unit.dart` is not retesting on file changes

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1922]
I currently have to kill and restart karma every time I need to rerun the tests.

**Comment by caitp** [comment]
I've just checked out master, npm installed, and ran `gulp test.unit.dart` --- after the run, opened `modules/angular2/src/transform/directive_metadata_extractor/transformer.dart`, saved the file, and dart was rebuilt and tests run again.

Is there any additional info that we're missing?

**Comment by yjbanov** [comment]
Nope, it simply doesn't work for me. I tried saving a test `*_spec.dart ` file, a `_spec.js` file, a `*.ts` file in `modules`. Nothing triggers Karma to rebuild. I'm going to rebase (and re-npm everything) and try again, but I'm on 666336b, which is quite fresh.

**Comment by vicb** [comment]
works for me on master (Ubuntu)

**Comment by IgorMinar** [comment]
I can't repro this with master and clean npm install. Please reopen if it's still a problem.
