### ISSUE TITLE
"view.disposables[i] is not a function" with zone.RunOutsideAngular

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [angular/angular#19237]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have a custom event manager that allows me to bypass the angular event loop, in short:

```
  addGlobalEventListener(element: string, eventName: string, handler: Function): Function {
    if(eventName.endsWith('out-zone')) {
      eventName = eventName.split('.')[0];
      return this.zone.runOutsideAngular(() => {
          super.addGlobalEventListener(element, eventName, handler);
        });
    } 
    return super.addGlobalEventListener(element, eventName, handler);
  }
```

The above event manager catches this HostListener in Directive 'X':

```
 @HostListener('document:mousemove.out-zone', ['$event'])
  onMouseMove(event: any) {
    if (this.moving && this.allowDrag) {
      this.moveInternal(event.clientX, event.clientY);
    }
  }
```

And so far behaviour is as expected.      Problem is when Directive X is destroyed (via *ngIf), I receive the following error in the browser:

```
<redacted>.html:3 ERROR TypeError: view.disposables[i] is not a function
    at destroyView (core.es5.js:12497)
    at callWithDebugContext (core.es5.js:13475)
    at Object.debugDestroyView [as destroyView] (core.es5.js:13029)
    at ViewContainerRef_.webpackJsonp.../../../core/@angular/core.es5.js.ViewContainerRef_.clear (core.es5.js:10015)
    at NgIf.webpackJsonp.../../../common/@angular/common.es5.js.NgIf._updateView (common.es5.js:1945)
    at NgIf.set [as ngIf] (common.es5.js:1898)
    at updateProp (core.es5.js:11114)
    at checkAndUpdateDirectiveInline (core.es5.js:10806)
    at checkAndUpdateNodeInline (core.es5.js:12349)
    at checkAndUpdateNode (core.es5.js:12288)
```

## Expected behavior
I realize I'm intentionally bypassing the expected logic, but I wonder if there's any way to catch such a case.

## Minimal reproduction of the problem with instructions
1) Create a custom event manager and register in app module like:

```
import { CustomEventManager } from './util/custom-event-manager';
...
  providers: [ { provide: EventManager, useClass: CustomEventManager} ],
```

2) Add a directive with a HostListener that will hit this bypass

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [x] Chrome (desktop) version  60.0.3112.113
 
For Tooling issues:
- Platform:  OSX

</code></pre>

**Comment by JiaLiPassion** [comment]
@PhaedrusTheGreek , if you want to `bypass` some events, you can check this `gist`,
https://gist.github.com/JiaLiPassion/45664f6a28c8b522fca30c841610c6b4

**Comment by pkozlowski-opensource** [comment]
Closing this one as Angular v9 running on ivy is not using code-paths that were throwing (plus @JiaLiPassion offered an alternative approach).
