### ISSUE TITLE
Add getComputedStyle to Renderer2

### ISSUE THREAD

**Issue by Stoom** [angular/angular#19238]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Developers must use `window.getComputedStyle()` to get a rendered component's style as seen in the browser.  This will violate the Angular Universal concept of not using `window`.

## Expected behavior
Add support to `Renderer2` for `getComputedStyle`

## Minimal reproduction of the problem with instructions
Look at Render2 prototypes, getComputedStyle will  not be listed

## What is the motivation / use case for changing the behavior?
I need to get a color value out of a  class that is applied to draw on a canvas with the same color.  I have not found a way with `Renderer2` or `ElementRef` to get the style when a class is applied.

## Environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x]  Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/6515#issuecomment-173353649

>Render should be write only (so that your app would run even in headless mode), for this reason render would never have methods for reading.

Although that's for the old Renderer. I don't think though it's going to be different for Renderer2.

**Comment by Stoom** [comment]
Any suggestions on a browser + universal way to get a rendered view to read from?

**Comment by Toxicable** [comment]
@Stoom you can query it manually by injecting the document

**Comment by Stoom** [comment]
@toxicable is document universal safe? Is window the only non universal safe global to stay away from?

**Comment by Toxicable** [comment]
https://github.com/angular/angular/commit/2f2d5f35bd086abeafceabdd5ff9430221b1917f
yup you just need to inject it

**Comment by Stoom** [comment]
Cool, closing for now.  Thanks for the help.
