### ISSUE TITLE
How to upload file with HttpClient

### ISSUE THREAD

**Issue by baohq110** [angular/angular#19239]
Hi all, 

I'm trying the way to upload file (in form data) using the HttpClient. I still not found yet. Could someone please help me on that? 
Thank so much

//Bao

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by matsko** [comment]
Closing this for now.

**Comment by AKlaus** [comment]
Please treat this request as 

- [x] Documentation issue or request

Uploading files is a common scenario and [the documentation](https://angular.io/guide/http) is lacking so needed guidance in this area.

**Comment by albohlabs** [comment]
@AKlaus I've created #21281. Would be great if you give some feedback.
