### ISSUE TITLE
Error while Running npm start

### ISSUE THREAD

**Issue by jabbar86** [angular/angular#19233]
$ npm start

angular@1.0.0 start C:\Users\Jabbar Memon\Downloads\Angular-2-Tutorials-master\Template
tsc && concurrently "npm run tsc:w" "npm run lite"
node_modules/@angular/core/index.d.ts(26,1): error TS1128: Declaration or statement expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular@1.0.0 start: tsc && concurrently "npm run tsc:w" "npm run lite"
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Jabbar Memon\AppData\Roaming\npm-cache_logs\2017-09-15T06_58_41_281Z-debug.log

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
