### ISSUE TITLE
bug(platform-server): dynamic styles do not get converted from camelCase to kebab-case

### ISSUE THREAD

**Issue by CaerusKaru** [angular/angular#19235]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using HostBinding or NgStyle with platform-server appends the style to the correct element, but does not convert the name of the style to kebab-case as platform-browser does. This leads the browser to not recognize the name of the style.

## Expected behavior

The dynamically applied styles should be transferred to the DOM as kebab-case, not camelCase.

## Minimal reproduction of the problem with instructions

1. Create a component and add a HostBinding for `marginRight`
2. Use @angular/cli to build a commonjs package
3. Render the package using nguniversal/express-engine
4. Turn off JS to prevent bootstrapping
5. Inspect the DOM to find the component with the incorrect styles

## What is the motivation / use case for changing the behavior?

If a user has JS disabled, or if bootstrapping is particularly slow, UX is greatly impacted as styles are not correctly applied throughout the DOM.

## Environment

<pre><code>
Angular version: 5.0.0-beta.7

Browser:
- [ x ] Chrome (desktop) version 61.0.3163.79
 
For Tooling issues:
- Node version: 8.5.0  
- Platform: Linux

**Comment by Toxicable** [comment]
While I can confirm this error in v4.4.1
I cannot get get my local version to render on v5 due to 
>/home/fabian/Downloads/universal-starter/cli/node_modules/@angular/core/bundles/core.umd.js:1322
        throw staticError('\'deps\' required', provider);
        ^
Error: StaticInjectorError[{provide:PlatformLocation, useClass:ServerPlatformLocation}]: 'deps' required

and if I add in `deps` I get 
>Error: StaticInjectorError[PlatformState]: Function/Class not supported

But anyway, as a work around you can do `@HostBinding('style.margin-right')` which works in my testing

@vikerman Could you take a look here?

To Reproduce:
* `git clone https://github.com/angular/universal-starter`
* `cd cli`
* add
```
@Component({
  selector: 'my-comp',
  template: 'my template'
})
export class MyComp{
  @HostBinding('style.margin-right') margin = '2px';
}
```
with `<my-comp></my-comp>` inside `AppComponet`'s template with `MyComp` added to the `AppModule`'s `declarations`
* `npm run build:prerender`

**Comment by CaerusKaru** [comment]
It looks like the problem is here: https://github.com/angular/angular/blob/6279e50d78554781111053e41cafcc8ca50ecc97/packages/platform-server/src/parse5_adapter.ts#L457-L472

In the browser implementation, the code looks like this, where the style is applied directly to the element, thus leveraging the browser's implicit transformation from camel case to dash case:
https://github.com/angular/angular/blob/109229246c4b1233668e150122318d740c74db69/packages/platform-browser/src/dom/dom_renderer.ts#L182-L189

**Comment by jonbonraki** [comment]
Is any Body looking into this?

**Comment by CaerusKaru** [comment]
If @vikerman is too swamped, I can probably get a PR in early next week. But I think he's the only one assigned at the moment.
