### ISSUE TITLE
Apply input placeholder styling from @Input property

### ISSUE THREAD

**Issue by tarikcurto** [angular/angular#19230]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Hi developers! currently i'm develop a search input component. This component is ussed in multiple regions of my application.

Component has '@Inputs' for define bgColor and color of input HTML element.

I usse placeholder for help message. For define placholder color and other CSS properties i need ::-webkit-input-placeholder property.

Problem goes here, when i try to **define color of placeholder as same color of input** (saved in '@input inputColor' property).

## Minimal reproduction of the problem with instructions

<pre><code>
@Component({
  selector: 'app-search-input-component',
  templateUrl: './search-input.component.html',
  styleUrls: ['./search-input.component.less'],
  styles: [
    'input::-webkit-input-placeholder{ color: ' + this.inputColor + ' }' //  <-- **I try this but is undefined :(**
  ],
  host: {
    '[style.display]' : "'flex'"
  }
})
export class SearchInputComponent implements OnInit {

  @Input()
  public placeholder: string = "Search model or manufacturer ...";

  @Input()
  public inputColor: string = '#ffffff'; //  <-- **I need apply to placeholder this color :(**

  @Input()
  public inputBgColor: string = 'rgba(255, 255, 255, 0)';

  @Input()
  public inputPadding: string = '10px';

  @Input()
  public inputBorder: string = '1px solid #ffffff';
</code></pre>
## Environment

<pre><code>
Angular version: 4

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

## 
**A lot of thank's to all for your time!** Tarik Curto

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

https://angular.io/api/core/Renderer2

**Comment by tarikcurto** [comment]
I followed the procedure you've indicated @ericmartinezr .
 - The stackoverflow community has not been able to provide a viable answer to this problem.
 - In other stacksoverflow entries that address this problem they do not get a solution.
 - I read some articles about Renderer2, but class dont has support for append child elements.

I think (and I think you will agree with me) that being able to edit pseudo elements dynamically must be a necessary functionality; at least in a framework of this level of popularity and robustness.

I enclose the sources for you to check for yourselves:
[https://stackoverflow.com/questions/35280118/change-style-of-pseudo-elements-in-angular2/35280715#35280715](https://stackoverflow.com/questions/35280118/change-style-of-pseudo-elements-in-angular2/35280715#35280715)
[https://stackoverflow.com/questions/41645442/dynamically-fill-css-pseudo-element-before-content-with-angular2](https://stackoverflow.com/questions/41645442/dynamically-fill-css-pseudo-element-before-content-with-angular2)

Thanks again for your time and knowledge, i look forward to your decision. - Tarik Curto.

**Comment by ericmartinezr** [comment]
@tarikcurto 

I would follow this issue https://github.com/angular/angular/issues/9343 as it seems to be similar to what you're asking (I think). If it's not, you may want to open a new **feature request** because this was a support request (even though you selected "Doc issue or request"). And it's not my decision, I'm not part of the team  =P

Have a nice weekend
