### ISSUE TITLE
Dynamic edit pseudo elements of HTML element

### ISSUE THREAD

**Issue by tarikcurto** [angular/angular#19234]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When you need to dynamically set the HTML pseudo elements CSS of a component, there is no API or effective solution.

## Expected behavior

API or extension of class (example Renderer2) for put dynamic CSS to pseudo elements.

## Minimal reproduction of the problem with instructions

```
<app-search-input
 [inputPlaceholder]="'Example placeholder'"
 [inputUserColor]="'#fff'"
 [inputPlaceholderColor]="'#000'">
</app-search-input>
<!-- Developer hasn't any method for assign dymanic style to input placeholder ( input::-webkit-input-placeholder{ color: #000;  } ) -->
```

## Environment

<pre><code>
Angular version: 4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment]
A simple workaround would be to use a class
