### ISSUE TITLE
How receive header at blob type?

### ISSUE THREAD

**Issue by cipchk** [angular/angular#19236]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior
 

```typescript
this._http
    .get(environment.SERVER_URL + this.url, {  responseType: 'blob' })
    .subscribe((res: Blob) => {

    });
```

I can see on the network tab that the response include a custom header.

![tim 20170917212305](https://user-images.githubusercontent.com/2987467/30521204-ac15627c-9bee-11e7-897a-edf1aac2e794.png)

my question, how do get the `x-filename` headers?

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/30522731-8b0802f6-9c07-11e7-830a-abf637b82cd3.png)

**Comment by cipchk** [comment]
thx.

**Comment by mtpultz** [comment]
@JayendharPrakash if you haven't figured it out yet.  He means set the `observe` parameter in the get can be set.  In your case `response` to access the body and any headers.  If you have custom headers that aren't showing up have a look at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
