### ISSUE TITLE
RouterLink directive interprets URL path differently compared to parsing a URL

### ISSUE THREAD

**Issue by CarstenLeue** [angular/angular#19247]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Access an angular application via the path

    http://localhost:4200/a/test%20page/b

Construct a link to that page in an angular application via

    <a routerLink="/a/test%20page/b">link</a>

## Expected behavior
I would expect that in both cases the same page gets addressed. In practice the routerLink directive addresses the page "http://localhost:4200/a/test%2520page/b". Reason seems to be that the routerLink directive expects a string of unescaped path segments, instead of a properly escaped URL path.

The sample works with 

    <a routerLink="/a/test page/b">link</a>

However the string "/a/test page/b" is not a path (according to RFC 3986).

## Minimal reproduction of the problem with instructions

This can easily be reproduced in a testcase:

````typescript

    it('should parse URLs', inject([Router], (router: Router) => {
        expect(router).toBeTruthy();

        // parse URL
        const parsedTree: UrlTree = router.parseUrl('/a/test%20page/b');
        const parsedSegments = parsedTree.root.children.primary.segments;

        // handle routerLink directive
        const linkTree: UrlTree = router.createUrlTree(['/a/test%20page/b']);
        const linkSegments = linkTree.root.children.primary.segments;

        expect(parsedSegments).toEqual(linkSegments);
    }));
````

The "router.parseUrl" method will produce unescaped segments, the "router.createUrlTree" produces escaped segments.

## What is the motivation / use case for changing the behavior?

The routerLink should take a URL path for consistency reasons, if the path to navigate to is a single URL path. If it's a sequence of URL segments, these segements should be the unescaped segments (since this is consistent to how the segments are represented in the UrlTree object).

## Environment

<pre><code>
Angular version: 4.4.1

Browser:
- [x] Chrome (desktop) version 60.0.3112.113
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by atscott** [comment]
I can see why the consistency may be desirable, but I don't think it's possible to make the change as people may rely (and do, based on the presubmit results on the linked PR) on the fact that the `routerLink` accepts strings that will be encoded rather than decoded, as in [this example](https://stackblitz.com/edit/angular-ivy-router-base-npw4p9?file=src%2Fapp%2Fapp.component.html).
