### ISSUE TITLE
Variable change in observable subscription doesn't trigger change detection

### ISSUE THREAD

**Issue by MrBlaise** [angular/angular#19241]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Sometimes a variable change inside an observable subscribe method doesn't trigger change detection. Hard to debug, since it doesn't always happen.

My use-case:

Add a payment method -> this will call a service, which will fire an event when finished, until then a spinner is shown -> the component listens on the event and when it fires it downloads the fresh payment methods and sets the loading to false -> sometimes the loading is stuck but the variables are properly set (loading = false) -> I trigger a change detection with something else and it properly updates.

My current workaround is to run it in NgZone.run(), it seems to fix it the problem.

## Expected behavior
It should always trigger change detection when a variable changes, inside the subscription

## Environment

<pre><code>
Angular version: 5.0.0-beta.7

 
For Tooling issues:
- Node version: v8.1.4
- Platform:  macOS 10.12.6

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by LinBoLen** [comment]
First, would you introduce zone monkey-patch in 

[zone-patch-rxjs](https://github.com/angular/zone.js/blob/master/dist/zone-patch-rxjs.js)

**Comment by JiaLiPassion** [comment]
just like @LinBoLen said, `zone.js` has provided the patch for `rxjs`, here is the sample, https://github.com/JiaLiPassion/rxjs-zone

**Comment by MrBlaise** [comment]
So I need to use the latest (master branch) of the zone.js to solve this problem?

**Comment by JiaLiPassion** [comment]
@MrBlaise , yes, you need to update to `zone.js` 0.8.17 and import `zone-patch-rxjs` in `polyfill.ts` after `zone.js`.

**Comment by MrBlaise** [comment]
@JiaLiPassion Thanks it seems to work now, I didn't know about this monkey patch.

**Comment by mlc-mlapis** [comment]
@JiaLiPassion ... applying `zone.js` 0.8.17 and `zone-patch-rxjs` together is just a temporary step? Actually using with SystemJS loader (not CLI) leads to a problem:
```
Uncaught TypeError: Cannot read property 'Scheduler' of undefined ... zone-patch-rxjs.min.js:1
```
if `index.html` contains:
```
...
<script src="node_modules/zone.js/dist/zone.min.js" type="text/javascript"></script>
<script src="node_modules/zone.js/dist/zone-patch-rxjs.min.js" type="text/javascript"></script>
<script src="assets/systemjs/system.js" type="text/javascript"></script>
...
```

**Comment by JiaLiPassion** [comment]
@mlc-mlapis , can you post you full html?

**Comment by mlc-mlapis** [comment]
@JiaLiPassion ... sure. Here is `index.html`:
```
<!DOCTYPE html>
<html>
<head>
	<base href="/" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width" />
	<title>iESO - Dynamic Modules - Angular 4.4.1</title>
	<link rel="icon" href="favicon.ico" />
	<!-- JS Libraries -->
	<script src="node_modules/core-js/client/shim.min.js" type="text/javascript"></script>
	<script src="node_modules/reflect-metadata/Reflect.js" type="text/javascript"></script>
	<script src="node_modules/zone.js/dist/zone.min.js" type="text/javascript"></script>
	<!-- <script src="node_modules/zone.js/dist/zone-patch-rxjs.min.js" type="text/javascript"></script> -->
	<script src="assets/systemjs/system.js" type="text/javascript"></script>
	<script src="app/systemjs.config.js" type="text/javascript"></script>
</head>
<body>
	<script>
		System.import('app/boot').catch(function(err) {
			console.error(err);
		});
	</script>
	<!-- Main Component -->
	<app-main>Loading ...</app-main>
</body>
</html>
```
and here ``
```
System.config({
	baseURL: '.',
	paths: {
		'npm:': 'node_modules/'
	},
	map: {
		'@angular/core': 'npm:@angular/core/bundles/core.umd.min.js',
		'@angular/common': 'npm:@angular/common/bundles/common.umd.min.js',
		'@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.min.js',
		'@angular/http': 'npm:@angular/http/bundles/http.umd.min.js',
		'@angular/router': 'npm:@angular/router/bundles/router.umd.min.js',
		'@angular/forms': 'npm:@angular/forms/bundles/forms.umd.min.js',
		'@angular/animations': 'npm:@angular/animations/bundles/animations.umd.min.js',
		'@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.min.js',
		'@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.min.js',
		'@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.min.js',
		'@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.min.js'
	},
	bundles: {
		"rxjs-bundle/Rx.min.js": [
			"rxjs/*",
			"rxjs/operator/*",
			"rxjs/observable/*",
			"rxjs/add/operator/*",
			"rxjs/add/observable/*",
			"rxjs/symbol/*",
			"rxjs/util/*"
		]
	},
	packages: {
		'app': {
			format: 'cjs',
			defaultExtension: 'js'
		}
	}
});
```

**Comment by JiaLiPassion** [comment]
@mlc-mlapis , `zone-patch-rxjs` will import several libraries from `rxjs`, so you can try to load `zone-patch-rxjs` after load `systemjs` and `systemjs.config.js`

**Comment by mlc-mlapis** [comment]
@JiaLiPassion ... thanks for the tip. I added `"rxjs/scheduler/*"` to `systemjs.config.js` and I am calling `zone-patch-rxjs` as the last script in the `index.html` but the problem is still here. If using `zone-patch-rxjs.js` the error is in the place of line 11 at parameter `global.Rx.Scheduler` ... `(factory(null,null,null,null,null,null,global.Rx,global.Rx.Scheduler,global.Rx,global.Rx,global.Rx.Symbol))`
```
bundles: {
	"rxjs-bundle/Rx.min.js": [
		"rxjs/*",
		"rxjs/operator/*",
		"rxjs/observable/*",
		"rxjs/add/operator/*",
		"rxjs/add/observable/*",
		"rxjs/scheduler/*",
		"rxjs/symbol/*",
		"rxjs/util/*"
	]
},
```

Do you know what is the plan with `zone-patch-rxjs`? Will there be a new version of RxJS with that patch included? Could it be RxJS 5.4.4?

**Comment by mlc-mlapis** [comment]
@JiaLiPassion ... the problem is probably that the first condition `typeof exports === 'object' && typeof module !== 'undefined'` in `zone-patch-rxjs` is not met even `<script src="assets/systemjs/system.js" type="text/javascript"></script>` is loaded in the beginning of `index.html` so SystemJS `required` syntax is not used ... it means `rxjs/scheduler/asap` is not loaded by SystemJS.
```
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(
        require('rxjs/add/observable/bindCallback'),
        ...,
        require('rxjs/scheduler/asap'),
        ...
    ) :	typeof define === 'function' && define.amd ? define(
        [
            'rxjs/add/observable/bindCallback',
            ...
        ], factory) : (factory(
            null,
            ...,
            global.Rx,
            global.Rx.Scheduler,
            global.Rx,
            global.Rx,
            global.Rx.Symbol));
}
```

**Comment by JiaLiPassion** [comment]
@mlc-mlapis , I will try to provide a sample.

> Do you know what is the plan with zone-patch-rxjs? Will there be a new version of RxJS with that patch included? Could it be RxJS 5.4.4?

You mean there are new API in `RxJS 5.4.4`? Sure, if there are any new APIs, I will provide new patch in `zone.js` repo.

**Comment by mlc-mlapis** [comment]
@JiaLiPassion ... thanks for your reply. It would be great if you can check a simple case on your side. The strange thing is that both `exports` and `module` should be defined by SystemJS lib and then the first condition should be fine and `require('rxjs/scheduler/asap')` should be invoked properly.

**Comment by JiaLiPassion** [comment]
@mlc-mlapis , I am not familiar with `SystemJS` config, but if you just load 
```javascript
<script src="node_modules/zone.js/dist/zone.min.js" type="text/javascript"></script>
<script src="node_modules/rxjs/bundles/Rx.js" type="text/javascript"></script>
<script src="./node_modules/zone.js/dist/zone-patch-rxjs.js" type="text/javascript"></script>
```

Everything will be fine.

**Comment by mlc-mlapis** [comment]
@JiaLiPassion ... your syntax is right but there is a problem with Rx.js bundle. It is not possible to use it as UMD bundle loaded as `<script>` with Angular because of the internal structure of Rx.js (or Rx.min.js). There is a long story about it here: https://github.com/angular/angular/issues/9359

**Comment by mlc-mlapis** [comment]
@JiaLiPassion ... I had to do the following steps to solve the problem:
1. Because the original `zone-patch-rxjs.js` was transpiled for `es2015` module format, it was not possible to use it directly ... some in-browser transpiler would be necessary.
2. So I transpiled the source of `lib/rxjs/rxjs.ts` to `zone-patch-rxjs.js` in `commonjs` module format first.
3. Then I configured `systemjs.config.js` for importing that `zone-patch-rxjs.js` using SystemJS loader.
4. And finally importing it in `boot.ts` as `import './zone-patch-rxjs';`.

**Comment by mlc-mlapis** [comment]
@JiaLiPassion ... what were the problems that original `zone-patch-rxjs` in 0.8.17 is solving? I can't find any exact description.

**Comment by JiaLiPassion** [comment]
@mlc-mlapis ,

1. yes, I am the author of the `zone-patch-rxjs`
2. currently I just make `zone-patch-rxjs` as an `umd` module, and I can make a `commonjs` module format version. you can post an issue in `angular/zone.js` repository.
3. `zone.js` 0.8.17 resolve the issue that `Rxjs/Schedular/asap` will not run into correct zone. you can find the changelog here, https://github.com/angular/zone.js/blob/master/CHANGELOG.md

**Comment by mlc-mlapis** [comment]
@JiaLiPassion ... thanks for reply ... I created a new issue for it: https://github.com/angular/zone.js/issues/908
