### ISSUE TITLE
How to redirect before render view?

### ISSUE THREAD

**Issue by xsmartweb** [angular/angular#19245]
## I tried to redirect in constructor function  and ngOnInit function . This is my code, but it is still displaying view before redirect to other route.
<pre><code>
constructor( private router: Router) {
 window.history.back();
}

ngOnInit() {
 this.router.navigate(['/']);
}
</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
