### ISSUE TITLE
Can Angular add Lifecycle hooks at runtime?

### ISSUE THREAD

**Issue by lishichao1002** [angular/angular#19240]
## Can Angular add Lifecycle hooks at runtime?

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Can't add Lifecycle hooks at runtime.

## Expected behavior

add Lifecycle hooks at runtime

## Minimal reproduction of the problem with instructions

```
@Component({
    selector: 'eg-parent',
    template: `
        <h2>Parent Component</h2>

        <many-other-components></many-other-components>

        <eg-child></eg-child>
    `
})
export class ParentComponent {

    ngAfterViewInit() {
        console.log('parent component: ngAfterViewInit', this);
    }

    doManyOtherComponentsOnAllViewInit(){
    }
}
```

```
@Component({
    selector: 'eg-child',
    template: `
        <h3>Child Component</h3>
    `
})
export class ChildComponent {

    constructor(private parent: ParentComponent) {
        console.log(this.parent);

        let _parent: any = this.parent as any;
        if (_parent.ngAfterViewInit) {
            this._ngAfterParentViewInit = _parent.ngAfterViewInit.bind(_parent);
        }
        _parent.ngAfterViewInit = this.ngAfterParentViewInit.bind(this);
    }

    private _ngAfterParentViewInit: Function;

    ngAfterParentViewInit() {
        if (this._ngAfterParentViewInit) {
            this._ngAfterParentViewInit();
        }

        console.log('child component: ngAfterViewInit', this);

        this.parent.doManyOtherComponentsOnAllViewInit();

    }

}
```

If the parent component implements ngAfterViewInit, then the child component can add the hack method.
If the parent component not implements ngAfterViewInit, then the child component can not add the hack method.

So if I want this worked, I have to add a empty ngAfterViewInit method.
Is there another way to do the same job. [plnkr example](https://plnkr.co/edit/N9alczh54rkRZsCe52bm?p=preview)

## Environment

<pre><code>
Angular version: 4.0.0

Browser:
- [x] Chrome (desktop) version latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.9.5
- Platform:  Windows

Others:

</code></pre>

**Comment by vicb** [comment]
Hooks are detected at compile time.
