### ISSUE TITLE
feat(core): support sugar for triggering CD when running without Zone.js

### ISSUE THREAD

**Issue by mhevery** [angular/angular#19252]
# Overview

With https://github.com/angular/angular/pull/17672 it is now possible to run Angular without `zone.js`. If the component is `ON_PUSH` Angular will trigger CD automatically whenever the inputs of the components change. However if the component changes internally, than it requires tha the developer manually trigger CD by invoking `changeDetectorRef.makrForChanges()`, which intern requires that `ChangeDetectiorRef` is injected into the component. This creates a sub-ideal experience. This Proposal attempts to fix it.

## Design

```TypeScript
@Component({
  template: `
    {{state.salutation}} {{name}}!
    <button (click)="bye()">bye</button>
  `,
  changeDetection: ChangeDetectionStrategy.ON_PUSH
})
class MyComponent {
  @Input()
  name: string

  @State()
  state = state({
    salutation: 'Hello'
  });

  bye() {
    this.state.update((state) => state.salutation = 'Bye');
  }
}
```

The basic idea is to separate the properties which are set on component externally using `@Input` and internal component state. By doing so one can better reason about which properties can change from outside and which are intrinsic to the component state. This can be seen in `{{state.salutation}} {{name}}!` where it now can be clear which data is internal and which is external to the component.

The `State` object present a read only version of the internal state. This adds additional level of type safety and prevents accidental change of the state without notifying the framework of the change. (This is shallow, as properties of state are probably not `readonly`, but it is better than no type safety)

```TypeScript
export interface State<T> {
  update(updateFn: (state: T) => void): void;
}

export function state<T>(initialValue: T): Readonly<T>&State<T> {
  return initialValue as any;
}
```

The `@State` annotation is needed to tell the compiler to inject the `changeDetectorRef` into state. In essence this is a property injection (rather than constructor injection) of `ChangeDetectorRef`. 

In the `bye()` method one can see that in order to get a hold of the `writable` version of the state object one would use the `update()` method which takes a callback function. The callback function was invoked with the writable `state` and than it automatically notifies the `ChangeDetectorRef` to perform CD. 

NOTE: The caveat is that when the `update()` methods is called from the constructor it does not yet have a reference to the `ChangeDetectorRef` since the property injector can only run after the constructor is done. In that case the `State` will keep track that a change has occurred and than perform the CD after the `ChangeDetectorRef` has been injected. 

[playground](http://www.typescriptlang.org/play/#src=declare%20var%20Component%3A%20any%3B%0D%0Adeclare%20var%20Input%3A%20any%3B%0D%0Adeclare%20var%20State%3A%20any%3B%0D%0Adeclare%20var%20ChangeDetectionStrategy%3A%20any%3B%0D%0A%0D%0Aexport%20interface%20State%3CT%3E%20%7B%0D%0A%20%20update(updateFn%3A%20(state%3A%20T)%20%3D%3E%20void)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aexport%20function%20state%3CT%3E(initialValue%3A%20T)%3A%20Readonly%3CT%3E%20%26%20State%3CT%3E%20%7B%0D%0A%20%20const%20update%20%3D%20function%20(updateFn%3A%20(state%3A%20T)%20%3D%3E%20void)%20%7B%0D%0A%20%20%20%20update.count%2B%2B%3B%0D%0A%20%20%20%20updateFn(initialValue)%3B%0D%0A%20%20%7D%20as%20%7B%0D%0A%20%20%20%20(updateFn%3A%20(state%3A%20T)%20%3D%3E%20void)%3B%0D%0A%20%20%20%20count%3A%20number%3B%0D%0A%20%20%7D%3B%0D%0A%20%20update.count%20%3D%200%3B%0D%0A%20%20(initialValue%20as%20any%20as%20State%3CT%3E).update%20%3D%20update%3B%0D%0A%20%20return%20initialValue%20as%20any%20as%20Readonly%3CT%3E%20%26%20State%3CT%3E%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0A%40Component(%7B%0D%0A%20%20template%3A%20%60%0D%0A%20%20%20%20%7B%7Bstate.salutation%7D%7D%20%7B%7Bname%7D%7D!%0D%0A%20%20%20%20%3Cbutton%20(click)%3D%22bye()%22%3Ebye%3C%2Fbutton%3E%0D%0A%20%20%60%2C%0D%0A%20%20changeDetection%3A%20ChangeDetectionStrategy.ON_PUSH%0D%0A%7D)%0D%0Aclass%20MyComponent%20%7B%0D%0A%20%20%40Input()%0D%0A%20%20name%3A%20string%0D%0A%0D%0A%20%20%40State()%0D%0A%20%20state%20%3D%20state(%7B%0D%0A%20%20%20%20salutation%3A%20'Hello'%0D%0A%20%20%7D)%3B%0D%0A%0D%0A%20%20bye()%20%7B%0D%0A%20%20%20%20this.state.update((state)%20%3D%3E%20state.salutation%20%3D%20'Bye')%3B%0D%0A%20%20%7D%0D%0A%7D)

**Comment by steveblue** [comment]
So what I have to `import {State, state} from '@angular/core`? Thats just confusing.

**Comment by alvipeo** [comment]
Why not call it `LocalState` then?

**Comment by lazarljubenovic** [comment]
I'm not sure I like this. Firstly, there seems **a lot of boilerplate**, even in definition of the state: we need both a decorator and a custom function. Then, every time we want to update state, we need to think of the implementation detail that we cannot use the usual assignment `=`, but instead a special function. This reminds me too much of `setState` from React, which I was under impression that Angular was trying to avoid.

If we have something like this, the API that I expect from Angular is just a `@State()` decorator.

```
@State() foo = 'bar'
method() { this.foo = 'bar' }
```

This is why I love Angular in the first place: components are **just classes** with hints to Angular in form of metadata which explain to Angular how does this class relate to the view tied to it, plus some more information, such as change detection strategy to use (again, in the view). My class is still just a simple class that represents my model, once you strip down metadata.

As I see it, introduction of this _completely_ breaks that mental model.

Why can't just a new decorator solve this? You mention that currently decorator is needed to tell the compiler to inject CDRef, but why cannot it as the same time serve as a setter that will call `.markForChanges()`? I'm not sure I see the reason for React-like `state` function and `state.update`.

**Comment by ericmartinezr** [comment]
Why not solve this issue through this proposal https://github.com/angular/angular/issues/5689 ?

**Comment by ghetolay** [comment]
What about a *component service* it can inject ChangeDetectorRef.
```ts
@Component({
  template: `{{state.salutation}}`,
  providers: [ State ]
})
class MyComponent {
  constructor(public state: State<MyInterface>){ }

  bye() {
    this.state.update();
  }
}
```

Problem is that you have to add `StateManager` into providers that's why I had that proposal #18015.
Another con is that you can't init the state and use that init value to type it, you need to explicitly define an interface :/. Maybe we can get around that.

**Comment by otodockal** [comment]
@mhevery Have you considered the approach of stenciljs?
https://stenciljs.com/docs/decorators#managing-component-state

Looks very similar.

**Comment by jamieathans** [comment]
The [MobX connector for Angular](https://github.com/mobxjs/mobx-angular) currently works similar to what @lazarljubenovic has proposed.

Given a component

```typescript
import { observable } from 'mobx-angular';

class MyComponent {
  @observable foo = 'bar';
}
```

or service

```typescript
import { observable } from 'mobx-angular';

@Injectable()
class MyStore {
  @observable foo = 'bar';
}
```

and a template that references the observable property

```typescript
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div *mobxAutorun>
      {{ foo }} - {{ store.foo }}
    </div>
  `
})
```

Then the `*mobxAutorun` structural directive will automatically run change detection when the observable property is modified.

I'm currently using this on a project instead of `redux` or `ngrx` with `ChangeDetectionStrategy.OnPush` and it seems to be working well so far.

**Comment by robwormald** [comment]
Closing this as we're still hotly debating this syntax and everybody is freaking out ⏳
