### ISSUE TITLE
Route with parameter conflicts with others

### ISSUE THREAD

**Issue by ninethug** [angular/angular#19255]
Hi,
I have 3 routes, one for the app module, an other for the admin section and a last one for the client side. Here they are :
`-- App routing --
export const routes: Routes = [
    { path: 'admin', loadChildren: 'app/admin/admin.module#AdminModule' },
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: '**', redirectTo: 'home', pathMatch: 'full' }
];

-- Admin routing --
const routes: Routes = [
    { path: 'admin', component: AdminComponent,
        children: [
            { path: '', redirectTo: 'evenements', pathMatch: 'full' },
            { path: 'evenements', component: AdminEventComponent }
        ]
    }
  ];
  
-- Client routing --
const routes: Routes = [
    { path: '', component: CoreComponent,
        children: [
            { path: '', redirectTo: 'home', pathMatch: 'full' },
            { path: 'home', component: HomeComponent },
            { path: ':city', component: HomeComponent }
        ]
    }
  ];`

The problem is that when I try to go to http://myDomain/admin, the router try to resolve /admin as :city which is a parameter in the client routing.

Normally, the router has to check first for a /admin route then if not found resolve it as :city. I asked the same question on stackoverflow, but no one knows how to. Is it a bug ? If not, could you just the explain why ? I found nothing talking about this case in the Angular documentation.
Thanks.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.
