### ISSUE TITLE
Router pathMatch values - Better naming suggestion

### ISSUE THREAD

**Issue by shairez** [angular/angular#19253]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When configuring a route, the current possible values for the `pathMatch` property are `full` and `prefix`

## Expected behavior
Instead of `full` I suggest the name `exact`

And instead of `prefix` I suggest the name `startsWith`.

## What is the motivation / use case for changing the behavior?

As a teacher, teaching about the `pathMatch` property values cause a lot of confusion.

The names `full` and `prefix`, from what I'm seeing when teaching Angular, are not conveying their true meaning.

Studends keep referring to the docs to try and understand what the `pathMatch` values do.

I think `exact` and `startsWith` convey better what will happen when you'll choose them as a `pathMatch` value. 

## Environment

<pre><code>
Angular version: 4.x.x

</code></pre>

**Comment by jasonaden** [comment]
I think this fixes your issue, right? #20775

**Comment by shairez** [comment]
Thanks for the PR @jasonaden , it certainly helps

But this issue is about changing the `prefix` and `full` as I still think it's harder to remember what they do without checking the docs
