### ISSUE TITLE
Angular 4.4.1 new project does not build with -prop -aot

### ISSUE THREAD

**Issue by rekna1** [angular/angular#19257]
## I'm submitting a bug

<pre><code>
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
ng new angular441
cd angular441
ng build -prod -aot

error:
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\projects\Test\angular441\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

## Expected behavior
new project should build

## Minimal reproduction of the problem with instructions
ng new angular441
cd angular441
ng build -prod -aot

## Environment

<pre><code>
@angular/cli: 1.2.3
node: 6.10.3
os: win32 x64
@angular/animations: 4.4.1
@angular/common: 4.4.1
@angular/compiler: 4.4.1
@angular/core: 4.4.1
@angular/forms: 4.4.1
@angular/http: 4.4.1
@angular/platform-browser: 4.4.1
@angular/platform-browser-dynamic: 4.4.1
@angular/router: 4.4.1
@angular/cli: 1.2.3
@angular/compiler-cli: 4.4.1
@angular/language-service: 4.4.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:6.10.3
- Platform:  os: win32 x64

Did not upgrade angular cli... is upgrading angular cli safe for exisiting projects created with older version of angular cli ?

**Comment by ericmartinezr** [comment]
Please report angular-cli's issues on its repo https://github.com/angular/angular-cli. Look for duplicates (it's full of them).

**Comment by anandakumarpalanisamy** [comment]
Hi Team,

Looks like 4.4.1 version is not compatible with running ng build --prod. We are seeing a lot of No providers found issue.

Its only specific to --prod mode build. Normal ng  serve continous to work AS IS.

Note: 4.3.6 version still works even for ng build --prod

Thanks

**Comment by ericmartinezr** [comment]
@anandakumarpalanisamy that issue is not related to the reported one. The one you mention has been already reported https://github.com/angular/angular/issues/19219 and there's already a PR to fix it.

**Comment by rekna1** [comment]
After updating angular-cli it works again, hope doesn't break existing application with previous version

**Comment by vicb** [comment]
4.4.3 should fix all the remaining issues - expect it Tuesday morning PST

**Comment by vicb** [comment]
duplicate
