### ISSUE TITLE
4.4.1 gives Error: No provider for e!. Works fine on 4.3.6

### ISSUE THREAD

**Issue by asksahil** [angular/angular#19254]
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Error appears on the form page when processing the form model. Stacktrace goes back till file vendor js f
No provider for e!

## Expected behavior

Issue disappears in version 4.3.6

## Minimal reproduction of the problem with instructions
NA
-->

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ x] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alexzuza** [comment]
Looks like dup of https://github.com/angular/angular/issues/19219

**Comment by vicb** [comment]
Closing as duplicate.
There is a PR pending to fix this.
Expect a new release later today.
