### ISSUE TITLE
Uncaught (in promise): Error: No provider for e! with prod flag (with ReactiveFormsModule)

### ISSUE THREAD

**Issue by soldiertt** [angular/angular#19267]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using any reactive form with attribute "formGroup" in Angular 4.4.x
And serving it (or building it) with prod flag in angular-cli will result in a blocking Js error.
"Uncaught (in promise): Error: No provider for e!"

## Expected behavior

The form should work without any error

## Minimal reproduction of the problem with instructions

1. Create a new app wit latest angular-cli (1.4.2)
2. In App module, import FormsModule and ReactiveFormsModule.
3. In App component html, add a basic form <code><form [formGroup]="myform"></form></code> and add the corresponding form in component : <code>myform : FormGroup</code>
4. Serve the app with "ng serve --prod"
5. Browse the app, error appears in console logs.

## What is the motivation / use case for changing the behavior?

Using forms.

## Environment
Only with --prod flag "ng serve --prod" or "ng build --prod"

<pre><code>
Angular version: 4.4.X

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2  
- Platform:  Windows

Others:

</code></pre>

**Comment by alexzuza** [comment]
https://github.com/angular/angular/issues/19219#issuecomment-330431900

**Comment by jlowcs** [comment]
Isn't this a regression and not a bug since it was working in 4.3.6?

**Comment by vicb** [comment]
duplicate

**Comment by Jackeysharath** [comment]
Can someone tell me the solutions here is my code?
working fine with local server,
when I move to hosting server the following error arises.
Error: No provider for e!
    at _e (vendor.c6cd506179cfc8072419.bundle.js:1)
    at vendor.c6cd506179cfc8072419.bundle.js:1
    at e._throwOrNull (vendor.c6cd506179cfc8072419.bundle.js:1)
    at e._getByKeyDefault (vendor.c6cd506179cfc8072419.bundle.js:1)
    at e._getByKey (vendor.c6cd506179cfc8072419.bundle.js:1)
    at e.get (vendor.c6cd506179cfc8072419.bundle.js:1)
    at wo (vendor.c6cd506179cfc8072419.bundle.js:1)
    at vendor.c6cd506179cfc8072419.bundle.js:1
    at Mo (vendor.c6cd506179cfc8072419.bundle.js:1)
    at wo (vendor.c6cd506179cfc8072419.bundle.js:1)

## **versions**

Angular CLI: 1.7.4
Node: 6.10.1
OS: win32 x64
Angular: 4.4.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.3.4
webpack: 3.11.0

**## package.json**

{
  "name": "cemsdemo",
  "version": "0.0.1",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --port 7777 --host 192.168.0.169 --open",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.7",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^4.4.7",
    "@angular/compiler": "^4.4.7",
    "@angular/core": "^4.4.7",
    "@angular/forms": "^4.4.7",
    "@angular/http": "^4.4.7",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^4.4.7",
    "@angular/platform-browser-dynamic": "^4.4.7",
    "@angular/router": "^4.4.7",
    "@ng-idle/core": "^2.0.0-beta.15",
    "@ng-idle/keepalive": "^2.0.0-beta.15",
    "@nicky-lenaers/ngx-scroll-to": "^0.6.1",
    "@types/jquery": "^3.3.1",
    "angular2-cookie": "^1.2.6",
    "angular2-moment": "^1.9.0",
    "angular4-datepicker": "^1.0.1",
    "angular4-slimscroll": "^1.0.5",
    "angularfire2": "^4.0.0-rc0",
    "core-js": "^2.5.6",
    "firebase": "^4.13.1",
    "font-awesome": "^4.7.0",
    "intl": "^1.2.5",
    "ng2-owl-carousel": "^0.1.15",
    "ngx-loading": "^1.0.14",
    "ngx-mydatepicker": "^2.4.5",
    "ngx-pagination": "^3.1.1",
    "rxjs": "^5.5.10",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "^4.4.7",
    "@angular/language-service": "^4.4.7",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.109",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.2",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}

**Comment by sameer05k21a0440** [comment]
I'm facing same problem ,please see  
 **package.json**
 ```
"dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/cdk": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "bootstrap": "^4.1.3",
    "core-js": "^2.6.1",
    "echarts": "^4.2.0-rc.2",
    "jquery": "^3.3.1",
    "less": "^3.9.0",
    "marquee-infinite": "0.0.4",
    "mdbootstrap": "^4.6.0",
    "ng-zorro-antd": "^1.8.1",
    "polyfills": "^2.1.1",
    "rxjs": "~6.2.0",
    "rxjs-compat": "^6.2.1",
    "ts-xlsx": "0.0.11",
    "webpack-sources": "^1.3.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.8.8",
    "@angular/cli": "6.1.0",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "^2.8.14",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "har-validator": "^5.1.3",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.7.2"
  }
```
