### ISSUE TITLE
HttpClient POST 'Http failure during parsing' error for valid json

### ISSUE THREAD

**Issue by mleprince** [angular/angular#19266]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

duplicate of #18396 

HttpClient fails to parse text response.

Expected to have been fixed in changelog 4.4.1 but the issue is still here when I use POST request.

## Expected behavior

No error should be thrown for a response of "ok"

## Minimal reproduction of the problem with instructions

We send a POST request with json content-type. The response content-type is text/plain with a "ok" body 

```javascript
    let json = { "id": "1505722661511934" }
    this.http.post("https://url/blabla",json).subscribe()
```

error :  SyntaxError: Unexpected token i in JSON at position 0 at Object.parse 

## Environment

<pre><code>
Angular version: 4.4.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by johnwalshuk** [comment]
I had this issue, the following link resolved it: https://github.com/angular/angular/issues/18680#issuecomment-330425866

**Comment by alxhub** [comment]
The parse error is for the returned JSON, not the object you're sending.
