### ISSUE TITLE
Issue in integrating custom web component in Angular 2

### ISSUE THREAD

**Issue by prithviraju1369** [angular/angular#19268]
Below is my custom component. In Index.html, I am importing the html.
```
<template id="comp-test">
    <style>
        h1{
            color: red;
        }
    </style>
  <div>
    <h1>Custom Component</h1>
  </div>
</template>

<script>
    class CompTest extends HTMLElement{
        constructor(){
            super();
            this.attachShadow({ mode: 'open' });
        }
        connectedCallback() {
            const tmpl = document.currentScript.ownerDocument.getElementById("comp-test");
            this.shadowRoot.appendChild(tmpl.content.cloneNode(true));
          }
    }
    customElements.define('comp-test', CompTest);
</script>
```

It works fine. As, document.currentScript.ownerDocument is current custom template

But when i add the same custom element in Angular 2 + which using Angular-cli, with below configuration changes on app.module.ts

```
import { NgModule,CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
 schemas: [ CUSTOM_ELEMENTS_SCHEMA ],
```
`document.currentScript.ownerDocument` is not current custom template and `document.currentScript.ownerDocument.getElementById("comp-test");` is **null**

**Comment by vicb** [comment]
No reproduction given -> closing the issue.

Please re-open with a repro when you get one.
