### ISSUE TITLE
AOT compiler touches depending libraries and no ngfactory.js files created

### ISSUE THREAD

**Issue by varghesep** [angular/angular#19269]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There are so many issues when I compile my angular app to work with third party libraries like ```ng-bootstrap```. I've described the problem related to ```ng-bootstrap``` [here](https://github.com/ng-bootstrap/ng-bootstrap/issues/1858).

Issues: 

(1) The compiler won't generate the ```ngfactory.js``` files in the ```genDir``` directory. I had to generate the ```ngfactory.js``` files through compiling the ```ts``` files again using a ```gulp``` task.

(2) The compiler touches third party libraries and generates ```ngfactory``` files for them.

![image](https://user-images.githubusercontent.com/12233474/30593940-e4f990f8-9d11-11e7-9e27-5a74f2915ff4.png)

![image](https://user-images.githubusercontent.com/12233474/30593972-f6ae3e5c-9d11-11e7-8b67-9b9b9a6d4012.png)

## Expected behavior

1. Running the ```ngc``` command should generate the ```ngfactory``` files.
2. I assume that the ```ngc``` should create ```ngfactory``` files only for the app, and not for the third party libraries. The ```nglibrary``` file in the app should load the UMD modules like ```core.umd.min``` from the ```node_modules``` folder at run time. If I'm wrong, then creating the ```ngfactory``` files for all the ```ts``` files under ```node_modules``` lead to believe the bundled files from different libraries can't be used with AOT compiled ```ngfactory``` files.

## Minimal reproduction of the problem with instructions

I use Visual Studio 2017, systemjs as a UMD module loader and gulp to run tasks. To generate the AOT compiled files, I run the following command in the project root folder where the ```tsconfig.json``` file is:

```"node_modules/.bin/ngc" -p tsconfig.json```

## What is the motivation / use case for changing the behavior?

The issues may be due to ```ngc``` is not compatible with ```tsc```. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.0 
- Platform:  Windows 10
- Typescript: 2.5.2
- systemjs: 0.19.46
- IDE: Visual Studio 2017
- Angular compiler-cli: 4.4.1

Others:

tsconfig.json file:

Note: wwwroot is the public folder.

**{
  "compileOnSave": false,
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "module": "system",
    "types": [ "" ],
    "rootDir": ".",
    "outDir": "./wwwroot",
    "lib": [
      "es2017",
      "dom"
    ],
    "baseUrl": "./myapp",
    "paths": {
      "app/*": [ "*" ],
    }
  },
  "include": [
    "./myapp/**/*.ts"
  ],
  "exclude": [
    "./node_modules/**/*"
  ],
  "angularCompilerOptions": {
    "genDir": "./wwwroot",
    "skipMetadataEmit": true
  }
}**

</code></pre>

**Comment by alexzuza** [comment]
`genDir` option is deprecated since 4.x and has no effect. Use out `outDir` instead

**Comment by varghesep** [comment]
That worked.
