### ISSUE TITLE
Bug: HTTP GET: Any type of request adds [object Object] to URL 

### ISSUE THREAD

**Issue by xdire** [angular/angular#19260]
## Bug of very strange nature with using @angular Http library
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
When creating custom behavior around HTTP class (extending for example) it happens that some underlying code changing destination url to something like `http://localhost:port/api/v1[object Object]` instead of provided `http://localhost:port/api/v1/user/1`

### Digging into JS code showed that issue is in following code
At file: `node_modules/@angular/http/bundles/http.umd.js`
```javascript
/**
     * Performs any type of http request. First argument is required, and can either be a url or
     * a {\@link Request} instance. If the first argument is a url, an optional {\@link RequestOptions}
     * object can be provided as the 2nd argument. The options object will be merged with the values
     * of {\@link BaseRequestOptions} before performing the request.
     * @param {?} url
     * @param {?=} options
     * @return {?}
     */
    Http.prototype.request = function (url, options) {
        var /** @type {?} */ responseObservable;
        if (typeof url === 'string') {
            responseObservable = httpRequest(this._backend, new Request(mergeOptions(this._defaultOptions, options, RequestMethod.Get, /** @type {?} */ (url))));
        }
        else if (url instanceof Request) {
            responseObservable = httpRequest(this._backend, url);
        }
        else {
            throw new Error('First argument must be a url string or Request instance.');
        }
        return responseObservable;
    };
    /**
     * Performs a request with `get` http method.
     * @param {?} url
     * @param {?=} options
     * @return {?}
     */
    Http.prototype.get = function (url, options) {
        return this.request(new Request(mergeOptions(this._defaultOptions, options, RequestMethod.Get, url)));
    };
```
### Where we can apply additional tuning for determine cause, console will output following:
```
line 1: object
line 2: string
line 3: zone.js:2744 GET http://localhost:8080/api/v1[object%20Object] 404 (Not Found)
line 4: XMLHttpRequest cannot load http://localhost:8080/api/v1[object%20Object]. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3004' is therefore not allowed access. The response had HTTP status code 404.
```

after applying this code at file: `node_modules/@angular/http/bundles/http.umd.js`:
```javascript
// Will be executed second
Http.prototype.request = function (url, options) {
        var /** @type {?} */ responseObservable;
        console.log(typeof url); // HERE will output: "string"
        if (typeof url === 'string') {
            responseObservable = httpRequest(this._backend, new Request(mergeOptions(this._defaultOptions, options, RequestMethod.Get, /** @type {?} */ (url))));
        }
        else if (url instanceof Request) {
            responseObservable = httpRequest(this._backend, url);
        }
        else {
            throw new Error('First argument must be a url string or Request instance.');
        }
        return responseObservable;
    };
// Will be executed first
    Http.prototype.get = function (url, options) {
    	var a = new Request(mergeOptions(this._defaultOptions, options, RequestMethod.Get, url));
    	console.log(typeof a); // HERE will output: "object"
        return this.request(a);
    };
```
### How to fix

Because all methods similarly calling `this.request` abstraction using only signature with first parameter, we can change all named methods to start passing url as a first parameter to `this.request` which will prevent such behavior to appear.

Following code reflects all required changes to make everything work as it's should (at file: `node_modules/@angular/http/bundles/http.umd.js`):
```javascript
    Http.prototype.get = function (url, options) {
    // Here added arg [url] as first parameter passed to request abstraction
        return this.request(url, new Request(mergeOptions(this._defaultOptions, options, RequestMethod.Get, url)));
    };
```

### Notes

It seems like this code inside `Http.prototype.request` can cause mix-ups of unknown nature with Javascript (at file: `node_modules/@angular/http/bundles/http.umd.js`):
```javascript
if (typeof url === 'string') {
            responseObservable = httpRequest(this._backend, new Request(mergeOptions(this._defaultOptions, options, RequestMethod.Get, /** @type {?} */ (url))));
        }
        else if (url instanceof Request) {
            responseObservable = httpRequest(this._backend, url);
        }
```
No HTTP library methods are calling `Http.prototype.request` otherwise than with one type of `Request` parameter which can be passed as a second parameter while first should be `url` of strict type `string`. Or as well string `url` argument can be erased and only request `Http.prototype.request(options)` signature should stay in place.

## Expected behavior
Instead of url `http://localhost:port/api/v1[object Object]` proper url should be called `http://localhost:port/api/v1/user/1`

## Minimal reproduction of the problem with instructions
When creating class which extends HTTP (with proper dependencies):
```typescript
export class Connector extends Http {
    constructor() {

        super(new XHRBackend(new BrowserXhr(), new ResponseOptions(), new FakeStrategy()), new RequestOptions());

    }

    public get(path: string, options?: RequestOptionsArgs): Observable<Response> {

	if(!options)
		options = this.createOptions();

	this.authorize(options);

	const url = String(this.conf.uri + this.conf.prefix + path);
		
	return super.get(url, options);

    }

}
```
and then using it for creating some requests in other class for example:
```typescript
public getById(id: number) : Observable<T> {

		return this._connector.get("/user/".concat(String(id)))
			.map(response => response.json().data as T);

	}
```

## What is the motivation / use case for changing the behavior?
To make things work as they should

## Environment
<pre><code>
Angular version: 4.4.1

Browser:
- [X] Chrome (desktop) version 56/59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 55.0.3
- [X] Safari (desktop) version 10.1.2
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8
- Platform:  Mac

Others:
</code></pre>
## Ending notes

That is my first issue submit, so I hope you will excuse me for any mistakes I made in text or code.

**Comment by Toxicable** [comment]
`Http` will be derecated in v5 in favour of HttpClient, see https://angular.io/guide/http for more 
Would you mind checking with HttpClient to see if the issue persists.

**Comment by xdire** [comment]
I will look at it in next few days, as for now I just passing arguments directly to Http.request instead of using get/post/put, and that pretty much working for 4.4.1.

I don't think I saw HttpClient in 4.4.1 with Quickstart bundle (I am not using Angular client). So probably it'll require additional efforts.

**Comment by Toxicable** [comment]
If you're using the CLI https://angular.io/guide/quickstart#devenv
Then you can already use it just do `import { HttpClient } from '@angular/common/http'`

**Comment by alxhub** [comment]
Extending `Http` is not a supported usage. Use `HttpClient` and interceptors instead.

**Comment by xdire** [comment]
Sorry but can I ask why you mentioned that extending HTTP is not supported usage while it was clearly issue with codebase? :) And as well — why anybody should prevent class extension functionality to make better toolset?

I am sorry that I stopped to contribute to this topic, just loaded with a lot of work. Thank you for understanding.
