### ISSUE TITLE
@angular/compiler-cli@4.4.3 requires typescript@'>=2.1.0 <2.4.0'

### ISSUE THREAD

**Issue by NCC1701M** [angular/angular#19287]
## I'm submitting a...
<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I get the warning @angular/compiler-cli@4.4.3 requires typescript@'>=2.1.0 <2.4.0' but 2.5.2 was found instead. Using this version can result in undefined behaviour and difficult to debug problems.

## Expected behavior
The compiler cli should use a newer version of typescript. Version 4.4.2 doesn't show this warning. Why a backstep?

## Minimal reproduction of the problem with instructions
Run 
```` batch
ng new MyProject
npm i --save-dev typescript@latest
ng build
````
## What is the motivation / use case for changing the behavior?
The tools should use the current stable versions of other tools and not making one or more steps back

## Environment

<pre><code>
@angular/cli: 1.4.2
@angular/animations: 4.4.3
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/platform-server: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.5.2

Browser:
Doesn't matter it's ab build problem
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  Windows 7 x64

</code></pre>

**Comment by mlc-mlapis** [comment]
... hmm, also using Angular 4.4.3 but without the described problem.

**Comment by Toxicable** [comment]
>Using this version can result in undefined behaviour and difficult to debug problems.

Can you give a specific example of some of these problems?
This behavior is as expected, wait till v5 before upgrading to the latest TS version.

**Comment by NCC1701M** [comment]
> Can you give a specific example of some of these problems?
This is a new project. I can't tell any problems but thats also not the reason why I opened the issue. I opened it because version 4.4.2 doesn't had any warnings with TS 2.5.x but version 4.4.3 has. So this - in my opinion - is an undesirable behaviour.

**Comment by lincolngup** [comment]
I received the same error message. From package.json...
```javascript
    "dependencies": {
        "@angular/animations": "^4.4.3",
        "@angular/common": "^4.4.3",
        "@angular/compiler": "^4.4.3",
        "@angular/core": "^4.4.3",
        "@angular/forms": "^4.4.3",
        "@angular/http": "^4.4.3",
        "@angular/platform-browser": "^4.4.3",
        "@angular/platform-browser-dynamic": "^4.4.3",
        "@angular/router": "~4.4.3",
        "core-js": "^2.5.1",
        "rxjs": "^5.4.3",
        "zone.js": "0.8.17"
    },
    "devDependencies": {
        "@angular/cli": "^1.4.2",
        "@angular/compiler-cli": "^4.4.3",
        "@angular/language-service": "^4.4.3",
        "@types/jasmine": "2.6.0",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "^8.0.28",
        "codelyzer": "^3.2.0",
         ...
        "typescript": "^2.3.4"
    }
```

The full error message:
@angular/compiler-cli@4.4.3 requires typescript@'>=2.1.0 <2.4.0' but 2.5.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.
    npm install typescript@'>=2.1.0 <2.4.0'
To disable this warning run "ng set --global warnings.typescriptMismatch=false".

**Comment by IgorMinar** [comment]
This is not related to 4.4.3. The warning is issued by the cli, and it's correct.

Angular v4 is not compatible with Typescript 2.4 or 2.5. It might work in some cases, but we know for sure that there are cases, when using typescript 2.4+ will result in problems and there is no easy way to work around this in Angular v4. In fact, we rewrote most of our TypeScript compiler integration in v5. Angular v5 will be compatible with 2.4 (and likely 2.5 - we still have some testing to do here) so you'll be able to update to that version soon.

**Comment by fljmayer** [comment]
I ran into the same problem. From what can see, Angular CLI drags in Typescript 2.5.2:
```
>npm install typescript@2.2.0
+-- @angular/cli@1.4.3
| `-- @angular-devkit/build-optimizer@0.0.21
|   `-- typescript@2.5.2
`-- typescript@2.2.0  invalid
```
Isn't it a bit inconsistent to first pull in Typescript 2.5.2 and then complain about it?

**Comment by Que8549** [comment]
I am getting the same warning. I am using VS Code v1.16 and it updated my TypeScript to v2.5. Is it possible to get a list of known issues so that we can make a determination if we want to downgrade typescript or not?

**Comment by Tyler-V** [comment]
Still can't use typescript@2.5.2 with latest angular

**Comment by Toxicable** [comment]
@Tyler-V You'll need Angular v5 if you want to use TS 2.5

**Comment by NCC1701M** [comment]
@Toxicable Now I'm using Angular v5. I still got the message, that 

> @angular/compiler-cli@5.0.0 requires typescript@'>=2.4.2 <2.5.0' but 2.6.1 was found instead.

In my opinion: Issue is not fixed -> Issue needs to be reopend

**Comment by ericmartinezr** [comment]
@NCC1701M that's a probably a typo from Fabian. Angualr v5 doesn't work with TS 2.5. There's a PR pending for that https://github.com/angular/angular/pull/20175

**Comment by sarunint** [comment]
Angular is not compatible with TypeScript 2.5 yet. It's likely to be supported in Angular v5.1 (maybe?).

**Comment by IgorMinar** [comment]
Yes. TS 2.5 and 2.6 support is coming.

**Comment by shlomiassaf** [comment]
I compiled a fairly big app with 2.6.1, AOT with minification and no issues.

Didn't have TS features there that are > 2.4.2

I think most issues with > 2.4.2 are decorators emit, and that effect's mostly compilation for libraries since app compile is one shot so the data is kept.

**Comment by Toxicable** [comment]
There are silent issues with `ngc` and TS >2.4
