### ISSUE TITLE
Angular/router conflict with Universal Analytics reports

### ISSUE THREAD

**Issue by Josmorsot** [angular/angular#19284]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Hello!
I'm working on a project using Angular + Universal (we're using Angular 4.3.6), we had implemented Universal Analytics (using TM).
Looking in reports we have notice that a lot of users have, in the  same flow, two "SESSION START".

After investigate I've discovered that this occur when the user arrive with UTM params and browse website.

I thought that maybe this could be the reason why this is happening but I have not found nothing in @angular/router:
https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#do_not_update_the_document_referrer

Someone have any idea?
![image](https://user-images.githubusercontent.com/7818205/30630214-d955bf82-9ddf-11e7-9934-fbcbfe13e8ad.png)

Thanks, Ivan

## Environment

<pre><code>
Angular version: ~4.3.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Josmorsot** [comment]
Hi, are you sure that this is not a BUG?. This occur when session start as "paid" or "referred" after navigate with routerLink, navigate or navigateByUrl.

Thanks

**Comment by Toxicable** [comment]
I don't see any issue here with Angular, if there is then please create a minimal reproduction of the issue where we can see it in isolation, otherwise this is un-actionable.

**Comment by IgorMinar** [comment]
I'm sorry @Josmorsot but as @Toxicable said this issue is hard to act on. If you can create a minimal preproduction or explain what the router is doing that would interfere with analytics then please open a new issue and we'll investigate it.

**Comment by Josmorsot** [comment]
Hi @IgorMinar  @Toxicable. I'm sorry for no response. I can't create a simple snippet to reproduce this issue but I have detected what is happening. Maybe you have any idea about what can I do.

Analitycs flow check url searching UTM, if they are not present get the referrer. Angular is an SPA framework so when users navigate on website the change url (and lose utm) but referrer never change. Finally, this user who access like "paid search" change to referred, because utm are not present and referrer has not change.
