### ISSUE TITLE
Documentation straddles HttpModule and HttpClientModule

### ISSUE THREAD

**Issue by MickeySegal** [angular/angular#19280]
## I'm submitting a...

<pre><code>
[X ] Documentation issue or request
</code></pre>

## Current behavior

The Tutorial at https://angular.io/tutorial/toh-pt6 uses HttpModule, while the Fundamentals information at https://angular.io/guide/http uses HttpClientModule.  

According at least to https://stackoverflow.com/questions/45129790/difference-between-http-and-httpclient-in-angular-4, "Use the HttpClient class from HttpClientModule if you're using Angular 4.3.x and above" and that  HttpModule will be deprecated.

## Expected behavior

It would be good to have the Tutorial use the newer functionality, particularly since the older functionality is to be deprecated.

Until that is implemented, there should be a warning on the Tutorial page that HttpModule is soon to be deprecated, and there should be a warning on the Fundamentals page that HttpClientModule only works if you have Angular 4.3.x or above (ideally with a description of how to check the version).

## Minimal reproduction of the problem with instructions

https://angular.io/tutorial/toh-pt6 uses HttpModule
https://angular.io/guide/http uses HttpClientModule

## What is the motivation / use case for changing the behavior?

There are many differences between HttpModule and HttpClientModule such as in the ways that JSON objects are handled, and it would be good to have examples of using them in a program with the object complexity of the Tutorial.  There are so many interactions with other complex functionality such as RxJS that writing one's first code without the Tutorial is not straightforward.
## Environment

<pre><code>
Angular version: 4.4.1

Browser:
- [X ] Chrome (desktop) version 61.0.3163.91
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by MickeySegal** [comment]
Another problem with this documentation: "results" is used for two different purposes on https://angular.io/guide/http, in both the JSON file and the TypeScript file.  The demos would be more clear if a name is not reused for different items.  One can figure out what when one already understands the material or by tinkering, but it is unwelcoming for explanatory material to use gratuitous ambiguity.

**Comment by MickeySegal** [comment]
Another problem with the documentation is that some environments throw an error for the comma after the last array element in the JSON data on https://angular.io/guide/http
`{
  "results": [
    "Item 1",
    "Item 2",
  ]
}`
It would be safer to just leave out that comma.

**Comment by MickeySegal** [comment]
A version at https://plnkr.co/edit/y0rhIR3NjYToVFCXpubZ?p=preview gets much of the functionality working with HttpClientModule, but two methods in hero.service.ts are not working properly: create and update.

**Comment by agussman** [comment]
Here's another page that confusingly uses both: https://angular.io/guide/ngmodules
