### ISSUE TITLE
When I ran cnpm install, I reported this mistake. How can I solve this problem?

### ISSUE THREAD

**Issue by DickLicha** [angular/angular#19283]
this is error
![image](https://user-images.githubusercontent.com/21870645/30625476-1106bb00-9df6-11e7-8846-badaffe84b8a.png)

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by DickLicha** [comment]
Thank you very much anyway!
