### ISSUE TITLE
Relative navigation to siblings broken with empty/component-less routes

### ISSUE THREAD

**Issue by tiwieso** [angular/angular#19290]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Relative navigation with `'../x'` or `'../../x'` fails when crossing an empty/componentless/lazy-loaded route. 

## Minimal reproduction of the problem with instructions
I created a minimalistic plunkr, that covers this issue.  It's not only related to lazy loaded, but also to componentless empty routes. The  behavior also depends on the existence of deeper child routes, which 'toggles' whether` ../x` or `../../x` router-links will work or fail.

Tested with Angular Version 4.3.6 and 4.4.3 (which is used in plunkr at the time of this writing).

-> [plunkr](http://plnkr.co/edit/Az8r4sH0VXHHEOjSDSiY?p=preview) <-

Just follow the instructions in the plunkr and watch the console.

The plunkr covers another issue with using multiple '..' commands for navigation, e.g.
`[routerLink]="['..','..','home']"`
which will result in urls containing double dots, like `/a/../home` 
 
## Expected behavior
It works in a consistent and expected way:
- empty routes are treated as non-existent, when navigating with '..'-commands/paths
- the existence of activated child routes does not change behavior

## What is the motivation / use case for changing the behavior?
The current implementation is very confusing, and impossible to use correctly without analyzing the activated routes children, as their mere existence change the behavior (see plunkr). This makes a correct static configuration of the links impossible.

## Environment

<pre><code>
Angular version: 4.3.6, 4.4.3

Browser:
- [x ] Chrome (desktop) version 60
</code></pre>

Might be related to #17957

**Comment by tiwieso** [comment]
I updated the plunkr to show a related issue with auxiliary routes affecting the navigation in a different way.

**Comment by bennadel** [comment]
I just ran into this as well. The relative navigation kept trying to add the sibling as a sub-segment of the other sibling. Like, `/sibling-a/(sibling-b)`. Adding the prefix helped.

**Comment by VamsiVempati** [comment]
@bennadel Hi Ben, you mentioned that adding the prefix helped, did it fix the issue with lazy loading and you were able to navigate from ../child-1 to ../child-2 instead of ../child-1/child-2 ? What exactly does adding the prefix mean sorry ? Thanks :)

**Comment by bennadel** [comment]
@VamsiVempati sorry, I have not tried anything with lazy-loading yet.

**Comment by bennadel** [comment]
@VamsiVempati I think that maybe I was getting this issue and this other issue - https://github.com/angular/angular/issues/14662 -- confused when I was talking about "prefix".

**Comment by mtuzinskiy** [comment]
Hi,  any updates on this?  Having the empty route is a very common case

**Comment by atscott** [comment]
Confirmed in Angular 9 as well: https://stackblitz.com/edit/angular-ivy-rmryyb?file=src%2Fapp%2Fapp.module.ts
Similar issues: #12976, #13011

**Comment by atscott** [comment]
`relativeLinkResolution: 'corrected'` is the [fix](https://stackblitz.com/edit/angular-ivy-btgn8s?file=src/app/app.module.ts) for the issue described here. From the B2 component, `[../b1]` is the correct relative link, even when there is a child route present. It works in both cases. I've opened #37355 to make this option the default.
