### ISSUE TITLE
Running Jasmine tests:  TypeError: Cannot read property 'nativeElement' of null

### ISSUE THREAD

**Issue by jrmcdona** [angular/angular#19292]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If you have an *ngIf on an element, you cannot get the element via -> fixture.debugElement.query(By.css('.welcome'));

I am even setting the value of welcome in the beforeEach() method and it still will not resolve to true on *ngIf="welcome"

## Expected behavior
*ngIf should resolve to true and element should be found and not null.

## Minimal reproduction of the problem with instructions
I modified the Angular testing sample:

Please see the WelcomeComponent failure.
https://plnkr.co/edit/txk3ZCOatFKqoRcjOofL?p=preview

To make it fail I added *ngIf to the H3 in welcome.component.ts.  _Without *ngIf it will not fail._
```
@Component({
  selector: 'app-welcome',
  template: '<h3 *ngIf="welcome" class="welcome" ><i>{{welcome}}</i></h3>'
})

In the welcome.component.spec.ts I set the value of welcome so the *ngIf="welcome" shoudl resolve to true.

```
    userService = fixture.debugElement.injector.get(UserService);
    componentUserService = userService;
    // UserService from the root injector
    userService = TestBed.get(UserService);
    
    **comp.welcome = 'test';**

    //  get the "welcome" element by CSS selector (e.g., by class name)
    de = fixture.debugElement.query(By.css('.welcome'));
    el = de.nativeElement;
```

```
## Environment

<pre><code>
@angular/cli: 1.4.1
node: 8.2.1
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/compiler-cli: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/platform-server: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.1
: 1.5.0
typescript: 2.4.1

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
 node: 8.2.1
Windows

Others:
See the modified Angular testing plunkr I created.
</code></pre>

**Comment by MikeSaprykin** [comment]
@jrmcdona - after setting **comp.welcome = 'test';**  - try using 
```fixture.detectChanges()```. This may help you, as by default, in Test components don't run change detection automatically. 
To enable auto change detection - use ```fixture.autoDetectChanges()``` in beforeEach function.

**Comment by spentak** [comment]
Why is this closed? I just started Unit Testing in Angular 5 and this issue immediately presents itself
ie
```
it('should show subscription section', () => {
    fixture.detectChanges();
    const el = fixture.debugElement.query(By.css('#subscription-section')).nativeElement;
    expect(el).toBeTruthy();
  });
```

**Comment by xuelijin** [comment]
I also face same issue when writing unit test in Angular 5. I am using Angular CLI: 1.6.1 and Angular: 5.1.3.
I tried to use **fixture.autoDetectChanges()** in **beforeEach()** function. Test is still failed.

**Comment by shaiTheGuy** [comment]
I ran into a similar problem, I used the following:
```
fixture.whenStable().then(() => {                                                                                                                     
    de = fixture.debugElement.query(By.css('.someElement'));
    el = de.nativeElement;
});
```
worked fine for me.

**Comment by Rajashreegr** [comment]
@spentak were you able to resolve this issue? If yes can you please provide the solution?

**Comment by tomwanzek** [comment]
I can confirm that this issue still exists. `fixture.detectChanges()` does not resolve the problem, that `*ngIf` does not appear to respond to a change in the component properties which drive its condition.

The live component works as expected, it is purely confined to unit tests of the _stand alone_ component. If the component is mock-wrapped in a unit test, it's input changed and the wrapper component change detection triggered, it works as expected in unit tests.

@jrmcdona Can you reopen this issue?

**Comment by tomwanzek** [comment]
Alright, in my case, I just narrowed it down, and one could consider it arguably "expected" behaviour. The component I am testing, has `ChangeDetectionStrategy.onPush`. If I change it to `ChangeDetectionStrategy.default`, the `*ngIf` will respond to forced changes of public component properties, after `fixture.detectChanges()`

**Comment by Owenet** [comment]
Was there ever a suitable resolution for this issue? 

Fast forward several months and it's still prevalent and causing me issues (Angular 5, Karma 1.7.1 and Jasmine 2.8.0)

Thanks

**Comment by raj2033** [comment]
**Workaround**
If you are using `*ngIf` in the element, use `hidden` instead.
`<h2 [hidden]="hideItem"> My Message</h2>`

This error is caused when jasmine could not find that element in the DOM. The most common scenario is using  `*ngIf` in the template. According to [docs](https://angular.io/guide/template-syntax#ngif), *ngIf destroys the element from DOM, if the expression evaluates to false.

**Comment by srix55** [comment]
All, if using change-detection OnPush on the component, refer this ancient issue https://github.com/angular/angular/issues/12313

**Comment by kammanageswararao** [comment]
it('should test click', () => {
    fixture.detectChanges();
    spyOn(component, 'productSelection');
    const el = fixture.debugElement.query(By.css('BPNormal')).nativeElement.click();
    expect(component.productSelection).toHaveBeenCalled();
  });

Hi All,

i am using the above code getting the same error. i.e typeerror cannot read property 'nativeelement' of null.

please help us ?

**Comment by amirensit** [comment]
Hello.
I solved this problem by using `fakeAsync` call.
```
describe('validate Siret ', () => {
            it('should call the method validateSiret() when the blur event is triggered', () => {
                fakeAsync(() => {
                    spyOn(comp, 'validateSiret');
                    fixture.detectChanges();
                    const input: ElementRef = debugElement.query(By.css('#field_cc'));
                    input.nativeElement.blur();
                    tick();
                    expect(comp.validateSiret).toHaveBeenCalled();
                });
            });
        });
```

**Comment by kammanageswararao** [comment]
I resolved this issue few days back.

Thanks for the update

**Comment by amirensit** [comment]
Could you share your solution please ?

**Comment by kammanageswararao** [comment]
Sorry for the late reply.

*Resolution:-*

it('productSelection', async(() => {
spyOn(component, 'productSelection');
const btn = fixture.debugElement.query(By.css('.BPNormal'));
btn.triggerEventHandler('click', *'productSelection'*);
fixture.whenStable().then(() => {
expect(component.productSelection).toHaveBeenCalled();
});
}));

**Comment by felixelgato92** [comment]
Why is this closed? This is still a problem Friday Jan 25, 2019

**Comment by trotyl** [comment]
This issue is closed by the OP him/herself, feel free to open a new issue with minimal reproduction.

**Comment by Harish-Hk** [comment]
@felixelgato92 hey, i guess using fakeAsync() solves the issue as suggested above

**Comment by mbernardes19** [comment]
fakeAsync() solved my problem too, though I'm trying to console.log() before the tick() and after it and it just doesn't appear in the console... Weird.

**Comment by mbernardes19** [comment]
I've found out what was my issue: the element I was trying to get wasn't defined in the template at the moment that I tried to get it. In my case, I was trying to get a button inside a td, but my table was empty because I didn't populate it with mock data.

fakeAsync() and async() just make the compiler keep waiting for something that never comes, until the testing process ends and makes it seem like the test passed, but in reality it just didn't run.

**Comment by chandresh87** [comment]
I have a similar problem and able to solve it by using page object and querySelectorAll

fixture.nativeElement.querySelectorAll('button');
HTML:

 <div *ngIf="isAbbreviationsAvailable(element.description); then caseA else caseB"></div>
  <ng-template #caseA>
    <div>

      <ng-template #popContent class="popover">
       <span id="glossary" >  {{element.description| glossary:glossaryDescription}}</span>
          <button class="close" (click)="p.close()"><img src="assets/icons/close.svg"></button>

      </ng-template>

      <button class="popoverLink" [ngbPopover]="popContent" [autoClose]="false"
              triggers="manual" #p="ngbPopover" (click)="p.open()" placement="top-right bottom-right" container="body"
              html="true" >
        {{split(element.description)[0]}}
      </button>

      /{{split(element.description)[1]}}

    </div>
  </ng-template>
  <ng-template #caseB>{{element.description}}</ng-template>
Test case:

const template: HTMLElement[] = fixture.nativeElement.querySelectorAll('button');
let link: HTMLElement = template[8]

expect(link.textContent.trim()).toEqual('ACC');
