### ISSUE TITLE
Performance - Too many digest calls in a ng4/ng1 upgrade hybrid app

### ISSUE THREAD

**Issue by akagr** [angular/angular#19299]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
A digest call is triggered every time the angular's zone settles. The app I'm working on has an array of 50 largish objects in an ng-repeat. This causes significant degradation in page performance. Even scrolling is affected since it triggers zone updates and, consequently, a digest. I agree that one of the places to look into is fixing the data itself. But the point is, it's smooth sailing on angular 1.6, while it's jittery as hell when angular 4 is introduced via upgrade. Here's some data from google's angular js plugins.

With angular 4 upgrade module:
![image](https://user-images.githubusercontent.com/2797603/30663536-95da5bbc-9e68-11e7-8834-4fe6c06949a3.png)

Without angular 4 upgrade module:
![image](https://user-images.githubusercontent.com/2797603/30663590-bef648d0-9e68-11e7-9046-9988f6c6bf52.png)

Both the screengrabs above were done while scrolling. The page did not have any custom components or behaviour (like virtual scroll, infinite loading) that is dependent on or directly affects scrolling.
I understand why this is happening. I'm not sure if I understand whether it should. I found adding a debounce function to the code which triggers digest on zone settlement yielded a good improvement (~6 digests/second) and the performance drop wasn't noticeable.

## Expected behaviour
I propose that we allow specification of debounce time in arguments of `UpgradeModule.bootstrap` method. This will be used to make sure that digest is triggered at most once in this frame. I can do a PR if that sounds okay.

## Minimal reproduction of the problem with instructions
This is really dependent on the app itself. I did not have success trying to recreate this because I was lacking the complexity/dataset needed for this to happen.

## Environment

<pre><code>
Angular version: 4.4.0-RC.0 / 1.6.2

**Comment by JiaLiPassion** [comment]
@akagr , maybe you can try to disable `zone` when handle event such as `scroll`, here is a `gist`.
https://gist.github.com/JiaLiPassion/45664f6a28c8b522fca30c841610c6b4

**Comment by akagr** [comment]
@JiaLiPassion Thanks! Will check that out. I do have a workaround by unsubscribing that digest event on zone settlement, and adding it back with a debounce. Since there's no data being communicated between the zone and rootscope in that listener, I think it should work well too.

**Comment by gkalpak** [comment]
Indeed if you have a listener for `scroll` events (registered inside the Angular zone), it will trigger a micro task (and subsequently an `onMicrotaskEmpty` emission and finally a `$digest`).

This ensures that the two change detections are wired together and changes propagate across the frameworks, but it does create a few more change detection cycles (on both frameworks).

Apart from blacklisting it, as @JiaLiPassion suggested, you have a couple more options:

1. If you control the code that registers the `scroll` event listener and you can run it outside the Angular zone:

    ```ts
    constructor(elemRef: ElementRef, ngZone: NgZone) {
      ngZone.runOutsideAngular(() => elemRef.nativeElement.addEventListener('scroll', ...));
    }
    ```

2. On 5.x, you can use the new `downgradeModule()` API, which is an alternative to `UpgradeModule` and drops this "Angular zone"<->"$digest" wiring (and also bootstraps AngularJS outside the Angular zone), which results in much fewer change detection cycles.
    (Docs are still work in progress (on #18487), but you can get a preview [here][1].)

In the future, we might indeed make such things configurable, similar to how you sugested, but haven't decided on the API yet. You might want to wait before starting to work on a PR, but it is great to hear you are interested :smiley:

[1]: https://pr18487-aedf0aa.ngbuilds.io/api/upgrade/static/downgradeModule

**Comment by akagr** [comment]
@gkalpak it's awesome to hear about the coming changes in 5. I guess I'll make do with my current debounce solution, and will try to jump on the latest 5 when that becomes available. That sounds like exactly the kind of thing I was looking for :)

**Comment by palmanis** [comment]
Looks like this didn't make it to Angular 5 ?

**Comment by gkalpak** [comment]
What didn't make it?

**Comment by palmanis** [comment]
On 5.x, you can use the new downgradeModule() API, which is an alternative to UpgradeModule and drops this "Angular zone"<->"$digest" wiring (and also bootstraps AngularJS outside the Angular zone), which results in much fewer change detection cycles.

The downgradeModule API, which can prevent enormous number of $digest calls in an Upgraded application.

**Comment by gkalpak** [comment]
It did make it into 5.0.0. (E.g. [look for `downgradeModule()` here][1].)
The docs haven't landed yet, but I am finishing up the PR (#18487) right now.

[1]: https://unpkg.com/@angular/upgrade@5.0.0/bundles/upgrade-static.umd.js

**Comment by palmanis** [comment]
Thank You

**Comment by gkalpak** [comment]
I am going to close this, since it (kind of) works as expected and there are ways to solve this (e.g. blacklisting `scroll` events or using ngUpgrdeLite (a.k.a. `downgradeModule()`)).

**Comment by akagr** [comment]
@gkalpak Just wanna update this ticket about downgradeModule working perfectly. I finally got time to remove that hacky code I put in to unsubscribe observables.

**Comment by sharikovvladislav** [comment]
@gkalpak any chances of this https://github.com/angular/angular/issues/19299#issuecomment-341388955 getting merged to Angular 4.4.x ? :'(

**Comment by gkalpak** [comment]
Nope, sorry :smiley: New features don't get backported to old versions (and the current stable is 6.x :grin:).

**Comment by sharikovvladislav** [comment]
@gkalpak time to refactor :)

well, we upgraded to 5.2.11 like in 10 minutes. we are trying 6.x now.

**Comment by hilnius** [comment]
@sharikovvladislav did you make it work on 6.x ? I'm having $digest errors after upgrading from 5.2.x
