### ISSUE TITLE
Consume .ng_meta.json files

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#1930]
`DirectiveMetadataExtractor` creates `.ng_meta.json` files which are consumed by `TemplateCompiler` but are not otherwise necessary - they are implementation details.

Create a phase that removes these files via `Transform#consumePrimary`

**Comment by sigmundch** [comment]
We should also consume the .aliases.json as part of this as well.

**Comment by sigmundch** [comment]
For debugging though - it's useful to see these files as part of the `--mode=debug` output, so while we could consume the `.aliases.json` files as soon as we read them in `directive_metadata_extractor/extractor.dart`, I rather keep them around and remove them all with the extra phase that consumes the resources.

In polymer we did something similar this with [this transformer](https://github.com/dart-lang/polymer-dart/blob/d2233b982ad8fcbf1722ed4aee63fc91ddb56c7f/lib/src/build/build_filter.dart)

**Comment by jakemac53** [comment]
Without global transformers we actually cannot do this. The files from your package dependencies get deleted before you have a chance to read them.
