### ISSUE TITLE
Improve error messages for the `StaticInjector`

### ISSUE THREAD

**Issue by rkirov** [angular/angular#19302]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When a there is a missing injectable, say `constructor(@Inject('foo') private foo: {})` and no matching provide, the error thrown does not mention the module, nor the dependency path.

The current error on the static injector looks like this:

```
search_videos.ng.html:26 ERROR Error: StaticInjectorError[foo]: 
  StaticInjectorError[foo]: 
    NullInjectorError: No provider for foo!
...
```

## Expected behavior

It would be nice to see

- [ ] The name of the module where the error occurs.
- [ ] The name of the component where the injectable is injected.
- [ ] Any intermediate injectables, like 'A needs B, B needs C, C needs Foo'.

**Comment by mhevery** [comment]
# There are three issues:

## Issue 1: Add the `StaticInjectorError` should add NgModule name.

The error should include the module name as you see here:
```
search_videos.ng.html:26 ERROR Error: StaticInjectorError(RouterModule)[foo]: 
  StaticInjectorError(MyAppModule)[foo]: 
    NullInjectorError: No provider for foo!
...
```

1. Have Injector take additional optional name parameter https://github.com/angular/angular/blob/master/packages/core/src/di/injector.ts#L74
2. Have error message creation include the error https://github.com/angular/angular/blob/master/packages/core/src/di/injector.ts#L125
3. Look for places where "Injector.create" gets invoked an add useful name


## Issue 2: The `NgModuleRef` should handle errors in the same way as `StaticInjector`

1. `get` method of `NgModuleRef_` https://github.com/angular/angular/blob/54e02449549448ebab6f255f2da0b4396665c6f0/packages/core/src/view/refs.ts#L477-L480 should add token information in the same way `StaticInjector` Does https://github.com/angular/angular/blob/master/packages/core/src/di/injector.ts#L241-L251
2. It will probably mean that this code needs to be extracted in some way for re-usability.


## Issue 3: The `NgComponentFactory` should handle errors in the same way as `StaticInjector`

This requires changes to the Compiler and is on @tbosch roadmap.


# Repro steps

```
@Component({ ... })
class MyComponent {
  construct(iDontExist: IDontExist) {}
}

@NgModule({
  declarations: [MyComponent]
})
class MyModule
```

will produce an stack trace which never mentions `MyModule` or `MyComponent`

**Comment by juliemr** [comment]
For our use case, the 'nice to have' "Any intermediate injectables, like 'A needs B, B needs C, C needs Foo'" is pretty critical. Teams are using common components and don't know where ngUpgraded stuff is coming from - and this is exceedingly useful for any unit testing scenario, even ones without ngUpgrade.

**Comment by mhevery** [comment]
Seems like this was fixed by https://github.com/angular/angular/pull/19482 and than reverted. @ocombe can you have a look what is the status of it?

**Comment by ocombe** [comment]
There was a problem with g3 for some applications but I have no idea what it was because I don't have access to that.
Who should I ask for more info?

**Comment by mhevery** [comment]
@ocombe  could you create a new PR and rebase on master.

**Comment by ocombe** [comment]
@mhevery done https://github.com/angular/angular/pull/20817
