### ISSUE TITLE
[feature] Ability to Host listen multiple events with one decorator

### ISSUE THREAD

**Issue by realappie** [angular/angular#19308]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

HostListener currently accept an `eventName` of type `string`. I have a lot of HostListeners that share the exact same functionality (hotkey bindings for different platforms). I was wondering if it would be possible to have `HostListener` accept an array of strings as well. 

So it currently looks like this.

```
  @HostListener('document:keydown.meta.s', ['$event']) saveHotKey($event: KeyboardEvent) {
    $event.preventDefault();
  }
```

It would be awesome if we could use it this way

```
  @HostListener(['document:keydown.meta.s', 'document:keydown.control.s'], ['$event']) saveHotKey($event: KeyboardEvent) {
    $event.preventDefault();
  }
```

Perhaps its by design this is not possible, and I should be looking at a solution such as [angular2-hotkeys](https://github.com/brtnshrdr/angular2-hotkeys)

**Comment by trotyl** [comment]
Why not just apply several decorators on one method? 

```typescript
@HostListener('click', ['$event'])
@HostListener('mouseover', ['$event'])
onEvent(event) {
  console.log(event)
}
```

Example in [Plunker](http://plnkr.co/edit/nSec1SNA0rkTTh9mTZPI?p=preview).

**Comment by ericmartinezr** [comment]
Related
https://github.com/angular/angular/issues/6675
Possible [workaround](https://medium.com/@TheLarkInn/hacking-angular2-binding-multiple-dom-events-f781b14ef676) (besides trotyl's suggestion)

**Comment by realappie** [comment]
@trotyl I didn't know thats possible! 

@ericcarraway Thanks for the possible workaround, funny enough I read that article long time ago!
