### ISSUE TITLE
TS Promise return empty object 

### ISSUE THREAD

**Issue by ar53n** [angular/angular#19309]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[Х] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Current my promise return object class Race and in then i get Race class but it is show empty 

## Expected behavior

Promise should be return not empty object

## Minimal reproduction of the problem with instructions

```javascript
    this.raceService
      .addRace(copyRace)
      .then(data => {
        if (copyRace.entrys) {
          let entryArray = copyRace.entrys.map(entry => {
            delete entry.id;
            entry.race = { id: data.id };
            console.log("Race is copy", data);
            return this.raceEntryService.addRaceEntry(entry)
          });
          return Promise.all(entryArray).then(entry=>{
            console.log('Return entries')
            return new Promise(res=>res(data)) //return data as Race
          })
        } else {
          return new Promise(res=>res(data)) //return data as Race
        }
      })
      .then(race1=>{
             console.log(race1) //get empty race1 but is it really not empty in debugger
             race1.id // i have error and cannot compile Angular application
          })
```

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:   Windows

Others:

</code></pre>

**Comment by Toxicable** [comment]
I'm sorry but this issue is not caused by Angular.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
