### ISSUE TITLE
New FormControl does not deep copy passed in object

### ISSUE THREAD

**Issue by lworkman** [angular/angular#19300]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Not sure if this is a real bug, but when creating a form control based off of an object it uses an object reference and not a copy of the object, leading to the original object being changed.

## Expected behavior
I would expect Angular to deep copy any objects passed in to avoid object mutation.

## Minimal reproduction of the problem with instructions

1. Create an object with at least one property.
2. Create a form control with this object as its value.
3. Declare a reference to the value of the form control.
4. Modify the reference.
5. Set the value on the form control to the reference.

Plunker: https://plnkr.co/edit/TuwJAn0oWF4aSmgcx3S4?p=preview

## What is the motivation / use case for changing the behavior?

Once again, not sure if this is a real issue. A use case I'm running into though is having multiple inputs modifying the form value (one for x.fizz, one for x.buzz, etc.) and not being able to detect if any changes have been made (as I'm comparing the form values to the original object).

**Comment by mlc-mlapis** [comment]
@lworkman ... there is an observable on a form level and also on each form control -> `valueChanges` that allows you to subscribe to those changes.

**Comment by lworkman** [comment]
@mlc-mlapis 

That's a good point, but judging changes based on `valueChanges` can lead to false positives, where someone made changes but then deleted them (say, hit `ctrl-z`).

Another issue with not deep copying passed in objects it that it makes it harder to revert the form.

**Comment by mlc-mlapis** [comment]
@lworkman ... false positives, yes, it could happen but is it really important? Just save / send / whatever another `version` of data. You can see it as a stream of data points. Then you can use undo / redo when you want.

**Comment by realappie** [comment]
There are other places where angular just uses an objects reference, I think its the developers job to  pass a copy of the object to the form.

**Comment by kara** [comment]
If the form control takes an object, it's up to the developer to deep copy if that's the behavior desired.
