### ISSUE TITLE
Uncaught TypeError: Cannot read property 'node' of undefined - with contenteditable

### ISSUE THREAD

**Issue by Sibiraj-S** [angular/angular#19307]
## I'm submitting a...

<pre>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</pre>

## Current behavior
```
bundle.js:21600 Uncaught TypeError: Cannot read property 'node' of undefined
    at Object.B [as getNodeText] (bundle.js:21600)
    at Array.c (bundle.js:19748)
    at Object.e.emit (_vendor.js:275)
    at HTMLDivElement.y (bundle.js:20210)
```

## Minimal reproduction of the problem with instructions
Step 1: Create a simple angular application `ng new myAngularApp`
Step 2: use `contenteditable="true"` in a div/any block with some text in it.
Step 3: then using `CTRL+Z`  on the contenteditable block causes this error

## Environment 

<pre>
Angular version: 4.2.4
AngularCli: 1.4.2

Browser:
- [X] Chrome (desktop) version 61.0.3163.91 (latest) 
- [ ] Chrome (Android) version 
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:   8.5
- Platform:  Windows - x64

Additional Information
This only happens in chrome and especially in normal mode only(working fine in incognito mode)
</pre>

**Comment by Toxicable** [comment]
Works fine here https://stackblitz.com/edit/angular-u9rkez?file=app%2Fapp.component.html

**Comment by Sibiraj-S** [comment]
I am not sure but I get this in chrome normal mode.

**Comment by Sibiraj-S** [comment]
@Toxicable . Can Angular-cli cause this kind of problem?

**Comment by Sibiraj-S** [comment]
In this https://stackblitz.com/edit/angular-azj64g?file=app/app.component.html.  

1. open in new window (live)
2. Inspect element 
3. ctrl+z.


This happens when height is set to contenteditable div

**Comment by chuckjaz** [comment]
@Sibiraj-S I tried the above link both on Windows and Chrome and could not reproduce the issue.

What am I missing?

**Comment by Sibiraj-S** [comment]
>This only happens in chrome and especially in normal mode only(working fine in incognito mode)

I think that was a chrome bug. I cannot reproduce that in my current version of `chrome (62+)` @chuckjaz

**Comment by Sibiraj-S** [comment]
I tried to reproduce but it is unsuccessful. I think that was an error in that version

**Comment by Sibiraj-S** [comment]
Closing as Issue might not be related to angular.
