### ISSUE TITLE
Documentation doesn't show all the inherited public and private methods and attributes

### ISSUE THREAD

**Issue by chrisvelevitch** [angular/angular#19306]
## I'm submitting a...
[x] Documentation issue or request

## Current behavior
For classes that extend other classes, there is no way see all the public and protected methods and attributes.

## Expected behavior
Please include a mechanism to show/hide all the inherited public and protected methods and attributes of a class. This particularly important for deep inheritance trees.

## What is the motivation / use case for changing the behavior?
Other languages that support inheritance have their documentation include a mechanism to show/hide all the inherited public and protected methods and attributes.

## Environment
Angular version: 4.4.3

Browser:
- [x] Chrome (desktop) version 61.0.3163.91

**Comment by chrisvelevitch** [comment]
Also, it would useful to see which other classes subclass the class.

**Comment by gkalpak** [comment]
We do show inherited public properties and methods (not sure about protected ones; @petebacondarwin should know :smiley:)
@chrisvelevitch, do you have a particular example where you've seen this not working?

Having a list of subclassing classes would be a nice addition indeed. Maybe you should open that as a separate feature request.

**Comment by petebacondarwin** [comment]
As far as I can tell there are no public API classes with `protected` members that are subclassed, so this might be why you are not seeing any.
Public inherited members are shown. See https://angular.io/api/forms/NgForm. This extends `ControlContainer` and if you scroll down the overview of the class, just below `resetForm` you can see that the inherited members are displayed.

**Comment by petebacondarwin** [comment]
I will create a PR to list known subclasses.

**Comment by chrisvelevitch** [comment]
@petebacondarwin @gkalpak I noticed this issue with the class Response which extends the Body class, but there is no mention of the methods and properties of Body. In fact, there is no documentation for the Body class.

**Comment by petebacondarwin** [comment]
`Body` is not publicly exported so there is no doc for it.

**Comment by chrisvelevitch** [comment]
Looking at the `@angular/http/src/body.d.ts` file, it is exported, but more importantly, it defines 4 very important methods that must be documented. When I first started using the `Response` class, I couldn't figure out how to access the returned data nor know the types of the data being return from a `http` request because the returned data methods are inherited from the `body` class but were not documented anywhere.

**Comment by petebacondarwin** [comment]
It is exported from its module but not from the "barrel" - https://github.com/angular/angular/blob/master/packages/http/src/index.ts

To include it in the docs it needs to be reexported there. Now we have a new http client library I don't know how many changes this library is receiving.  Perhaps @alxhub can say?

**Comment by trotyl** [comment]
The `Body` class in `@angular/http` is just a mimic of standard [`Body`](https://developer.mozilla.org/en-US/docs/Web/API/Body) class,  just without using `Promise`. There is not important methods that introduced by it at all.

You don't need to care about it specially, just think it as the one in the standard.

**Comment by chrisvelevitch** [comment]
I think there is a serious problem with the state of the documentation. According to the comments in the code:-

[https://github.com/angular/angular/blob/master/packages/http/src/static_response.ts#L35:L35](https://github.com/angular/angular/blob/master/packages/http/src/static_response.ts#L35:L35)

this class has been depreciated but the recommended alternative (`@angular/common/http`) has no `Response` class. So it's not clear what the alternative class name is and the documentation doesn't include the depreciation notice nor a direction to the new class name to use instead. I'm assuming the alternative class is `HttpResponse`.

**Comment by gkalpak** [comment]
@chrisvelevitch, the code you linked is from the master branch (currently 5.x). You are probably looking at the 4.x documentation, where `@angular/http` is not deprecated yet. On the docs for [Angular@next][1], `Response` is indeed [marked as deprecated][2] with a pointer to use the [@angular/common/http][3] package instead.

When deprecating a package over another one, there doesn't necessarily need to be a 1-to-1 mapping from old classes to new classes, but in this case [HttpResponse][4] is indeed the equivalent.

It would definitely be nice to make `@angular/common/http` a link (either to the [package's API docs page][3] or better yet to [/api?query=common/http][5]). PRs welcome :smiley:

[1]: https://next.angular.io
[2]: https://next.angular.io/api/http/Response
[3]: https://next.angular.io/api/common/http
[4]: https://next.angular.io/api/common/http/HttpResponse
[5]: https://next.angular.io/api?query=common/http

**Comment by petebacondarwin** [comment]
@chrisvelevitch please open a new issue (or just provide a PR!) for the documentation change for the `4.6.x` branch if you wish. This issue will be closed when #19343 is merged.
