### ISSUE TITLE
ViewEncapsulation

### ISSUE THREAD

**Issue by acopalipsis** [angular/angular#19319]
You have to add the ability to disable ViewEncapsulation at the application level. In addition, please use only one prefix for all components. The strongest side of the Bank, is a css. ShadowDOM makes web turd

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

I also suggest that you review our [code of conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md) and abide by it.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by acopalipsis** [comment]
Please excuse the turd.. Not the turd - angular is a very competent architecture, built by people who have no relationship to the web.And that's all. I didn't think a turd is an insult, because everywhere there is a smiley-turd.
