### ISSUE TITLE
Error message when Directive declaration fails to make it clearer when reason for failure is that no property matches the selector

### ISSUE THREAD

**Issue by williamBurgeson** [angular/angular#19312]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request

See https://github.com/williamBurgeson/structural-directive-mismatch as an example.

As an Angular developer (but not having worked with AngularJS) I am familiar with Components and Services but haven't done very much with directives.

I got tied up with a problem for quite a long time when I was getting the `Can't bind to 'XXXDirective' since it isn't a known property of 'ng-container'.` even though all the imports, exports, declarations etc seemed to be in order.

In the end my error turned out to be the fact that there needs to be an @Input() property with exactly the same name as the selector.

This isn't really obvious from the error given, and it would be nice to at least amend the error message so that the developer is directed (no pun intended) towards this condition being the reason for the error.

In the repo the penultimate commit is a working system, and then I introduced the error as a demonstration

**Comment by atscott** [comment]
Closing, I believe the error message with Ivy would now be `Property 'xyz' does not exist on type 'XXXDirective'.` If this is not the case, please open a new issue

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
