### ISSUE TITLE
Templateref inside ngIf cannot be accessed from outside

### ISSUE THREAD

**Issue by peterreisz** [angular/angular#19316]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Templateref inside ngIf cannot be accessed from outside:

```ts
export class App {
  log(ref) {
    console.log(ref);
  }
}
```

```html
<button (click)="visible=true">show</button>
<button (click)="visible=false">hide</button>
<button (click)="log(ref)">log</button> <!-- Does not work: logs undefined -->
<div *ngIf="visible">
  <button (click)="log(ref)">log</button> <!-- It works: logs tag-->
  <span #ref>asdfasdf</span>
</div>
```

## Expected behavior

Templateref should be accessible from outside of the ngIf and any other structural directive.
`@ViewChild` also should work.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/XerE9poibEU3os87y5Bs?p=preview

Click show and log button.
Check the javascript console.

## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- [X] Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows

Others:

</code></pre>

**Comment by alexzuza** [comment]
Workaround is

`@ViewChild('ref') ref`

https://plnkr.co/edit/N7MJUyhIWyOQzGytVcJB?p=preview

**Comment by chuckjaz** [comment]
Template reference variables are scoped to the template they are defined in. A structural directive creates a nested template and, therefore, introduces a separate scope. The reason `ref` is undefined is that is is accessing the ref property of the application (as you noted above in you work-around).

**Comment by darkbasic** [comment]
> Workaround is
@ViewChild('ref') ref

This is not very useful if you're inside an *ngFor :)

**Comment by alexzuza** [comment]
@darkbasic I don't see any `*ngFor` in the question

**Comment by darkbasic** [comment]
There is none in fact. I wanted to simply point out that ViewChild is not a Swiss Army Knife and won't provide a solution for all cases. Unfortunately there is still no universal solution if you want to access a template ref inside a structural directive.

**Comment by briancodes** [comment]
@darkbasic When using an ngFor, `@ViewChildren('ref')` would probably work  in this situation

`@ViewChildren('ref') refs: QueryList<ElementRef>;`

You could iterate over the `ref` QueryList when it changes (there's a changes observable on the list), and access the individual elements that way
