### ISSUE TITLE
HttpClient.get() should return `Observable<any>` instead `Observable<Object>`

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#19321]
## I'm submitting a...

<pre><code>
[ x] Feature request
</code></pre>

## Current behavior

In TypeScript definition, [HttpClient.get() returns](https://github.com/angular/angular/blob/1b1d5f10a19adcd1e4c157f3295d70ec7919861a/packages/common/http/src/client.ts#L855) `Observable<Object>`:

```ts
    /**
     * Construct a GET request which interprets the body as JSON and returns it.
     *
     * @return an `Observable` of the body as an `Object`.
     */
    get(url: string, options?: {
        headers?: HttpHeaders;
        observe?: 'body';
        params?: HttpParams;
        reportProgress?: boolean;
        responseType?: 'json';
        withCredentials?: boolean;
    }): Observable<Object>;
```

## Expected behavior

HttpClient.get() should return `Observable<any>`:

```ts
    /**
     * Construct a GET request which interprets the body as JSON and returns it.
     *
     * @return an `Observable` of the body as an `Object`.
     */
    get(url: string, options?: {
        headers?: HttpHeaders;
        observe?: 'body';
        params?: HttpParams;
        reportProgress?: boolean;
        responseType?: 'json';
        withCredentials?: boolean;
    }): Observable<any>;
```

## Minimal reproduction of the problem with instructions

Why TypeScript definition is it not allowed that an array may come from the backend, for example, or text? They also go in the JSON-format.

```ts
getPostsForIndex(): Observable<Post[]>
{
  return this.httpClient
  .get( `/api/posts` )
  .catch( this.handleError.bind(this) );
}
```
> Error: [ts]
Type 'Observable<{} | Object>' is not assignable to type 'Observable<Post[]>'.
  Type '{} | Object' is not assignable to type 'Post[]'.
    Type '{}' is not assignable to type 'Post[]'.
      Property 'includes' is missing in type '{}'.

Even if I try to do `.get<Post[]>( '/api/posts' )` - it also throw error that above.

## Environment

Angular version: 4.4.3

**Comment by KostyaTretyak** [comment]
My TypeScript v2.5.2

**Comment by Brooooooklyn** [comment]
try
```ts
getPostsForIndex(): Observable<Post[]>
{
  return this.httpClient
  .get( `/api/posts` )
  .catch<any>( this.handleError.bind(this) );
}
```

**Comment by KostyaTretyak** [comment]
Even this not works:

```ts
getPostsForIndex(): Observable<Post[]>
{
  return this.httpClient
  .get(`/api/posts`);
}
```

**Comment by KostyaTretyak** [comment]
Whoops, but this works:

```ts
getPostsForIndex(): Observable<Post[]>
{
  return this.httpClient.get<Post[]>(`/api/posts`);
}
```

Sorry for the time spent.

**Comment by LuisJoseSanchez** [comment]
Thank you @KostyaTretyak! I had the same problem, now it's solved :-)

**Comment by grosch** [comment]
@KostyaTretyak Please note what you showed in fact does not work.  You're still just getting back an array of object.  You don't have an actual `Post` object.  Because it's a dictionary, you can access the property name and it looks like you're good.  But if `Post` has a function defined on it, for example, you can't call that function.

**Comment by KostyaTretyak** [comment]
> if `Post` has a function defined on it, for example, you can't call that function.

@grosch, [here](https://stackblitz.com/edit/angular-i6bdpc?file=src%2Fapp%2Fapp.component.ts) `Post` have `method1()` and I can call this.
