### ISSUE TITLE
ngFor with possibility of assign key value like ES6 feature

### ISSUE THREAD

**Issue by titusfx** [angular/angular#19333]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

<tag *ngFor="let keyValue of getAMap() | myPipeToGetKeysAndValue" >

Right now getting key and value of a map, you need to create a pipe instead of having one builtin,

## Expected behavior

<tag *ngFor="let [key, value] of getAMap() | builtInAngularPipeKeysValue" >

[this is a feature of ES6](http://es6-features.org/#ArrayMatching)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
Duplicate of https://github.com/angular/angular/issues/2246#issuecomment-107212606

--


The issue with this is that the order of a `Map` in indeterminate.
