### ISSUE TITLE
AoT compiler should allow generated route paths

### ISSUE THREAD

**Issue by voithos** [angular/angular#19336]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Attempting to generate the (const) `path` of a route, such as:

```
@NgModule({
  imports: [
    RouterModule.forChild([
      {path: getPath(), ...},
    ]),
  ]
)
```

.. where `getPath()` essentially builds a static string, results in an error from the AoT compiler:

```
Error encountered resolving symbol values statically. ... function calls are not supported.
Consider replacing the function or lambda with a reference to an exported function
```

A similar error occurs if an exported `const` is referenced instead of the inline function call.

## Expected behavior
Looking at the normal `.ngfactory.js` file, the ngfactory file imports the file containing the router configuration, at which point the value of the generated route path would be available. Instead of using that, though, it seems like the AoT compiler is statically copying the resolved value of the `path` into the `.ngfactory.js` file.

## What is the motivation / use case for changing the behavior?
Our project has the concept of first-class "URL" objects that encode parameters and path information, and it would be great if the route `path` configuration could be generated from these URL objects.

Besides that, though, I don't quite understand the rationale for the AoT compiler's current behavior as far as it concerns the `path` property, so it seems like it would be nice to remove the limitation if there isn't a good reason for it (although I suspect there may be).

## Environment

<pre><code>
Angular version: HEAD

</code></pre>

**Comment by Toxicable** [comment]
You can reference a `const` aslong as it's exported 
We cannot evaluate functions because AOT is run statically, meaning it's not running your code
see more here https://angular.io/guide/metadata

**Comment by vicb** [comment]
@Toxicable this will be supported in 5.x and we call it "expression lowering". What it does it to rewrite the code to export the value.

**Comment by Toxicable** [comment]
Oh that's good to hear, thansk for the update

**Comment by voithos** [comment]
@vicb Indeed, that's fantastic!

**Comment by chuckjaz** [comment]
@voithos Can you try the `@next` version of Angular to see if the lowering we added works for your use cases?

**Comment by jsgoupil** [comment]
There is a problem with the AOT. It's duplicating the call of my route configuration.
It fails right here:

    throw new Error("Invalid configuration of route '" + fullPath + "'. One of the following must be provided: component, redirectTo, children or loadChildren");

I searched for the token ROUTES and I found this one in the main.bundle.js

    (1024, __WEBPACK_IMPORTED_MODULE_6__angular_router__[\"i\" /* ROUTES */], function () { return [[{ path: \"\", component: __WEBPACK_IMPORTED_MODULE_2__app_component__[\"a\" /* AppComponent */] }, { path: \"areas\" }]]; }, []),


I have created a github repo for this.
https://github.com/jsgoupil/router-aot-error

This works:

    ng serve

This does not work:

    ng serve --aot

I started from the CLI, then added this commit:
https://github.com/jsgoupil/router-aot-error/commit/3c487ae56947159bc96fbb643ede1cd1595fede3

**Comment by chuckjaz** [comment]
@jsgoupil Can you create a separate issue the this. I don't believe these are related.

**Comment by JoostK** [comment]
This is no longer an issue in Ivy. In ViewEngine, it would work if `getPath` were exported (and the compiler generates a readable error if that's not the case)
