### ISSUE TITLE
Observable works in component but not in template (called many times)

### ISSUE THREAD

**Issue by actra-gschuster** [angular/angular#19330]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Given this method in an authentication service:
```
public getDisplayName(): Observable<string> {
    let subject$: ReplaySubject<string> = new ReplaySubject<string>(1);
    console.log('getDisplayName');
    return subject$.asObservable();
}
```

When used in the component:
```
@Component({
    selector:      'my-drawermenu',
    encapsulation: ViewEncapsulation.Emulated,
    templateUrl:   './templates/drawer-menu.template.html',
    styleUrls:     ['./styles/drawer-menu.scss']
})
export class DrawerMenuComponent {
    public authenticationService: AuthenticationService;
    public displayName: string;
    
    
    constructor(authenticationService: AuthenticationService) {
        this.authenticationService = authenticationService;
        
        this.authenticationService.getDisplayName().subscribe((displayName: string): void => {
            this.displayName = displayName;
        });
    }
}
```
it works as expected, I see exactly one log entry in the browser console.

But when used inside the template of the component:
```
<span>{{authenticationService.getDisplayName() | async}}</span>
```
I see more than ONE HUNDRED log entries in the browser console.

## Expected behavior
Method should be called only once.

## Environment

<pre><code>
Angular version: 5.0.0-beta.3

Browser:
- [x] Chrome (desktop) version 61.0.3163.79
 
For Tooling issues:
- Node version: 7.10.1
- Platform: Windows
</code></pre>

**Comment by alexzuza** [comment]
You're returning new Observable every time angular performs change detection

`authenticationService.getDisplayName()`

Consider storing your observable into component property

**Comment by actra-gschuster** [comment]
Yes, that's what I thought of in the first place but it felt not right to declare poperties all over the place.
But shouldn't it be possible for angular to know to not call the method again but the returned observable?
With the async pipe I already told the compiler explicitly that I'm expecting an observable so the change detection should watch that instead of the method.

**Comment by chuckjaz** [comment]
@actra-gschuster When you include the expression `authenticationService.getDisplayName() | async` in your template you are telling Angular evaluate this expression every time change detection is performed. I would therefore expect the expression to be evaluated 100s of times instead of just once.
