### ISSUE TITLE
please support angular-in-memory-web-api compatible with http and httpclient

### ISSUE THREAD

**Issue by lizhuangs** [angular/angular#19335]
now  angular-in-memory-web-api return the response must be like this:
xxx.data
but http and httpclient is xxx,they have not '.data'
could they compatible  with each other.
so we can test easier.
hope for that , Thanks!

**Comment by trotyl** [comment]
https://github.com/angular/in-memory-web-api/blob/master/CHANGELOG.md#045-2017-09-11

**Comment by IgorMinar** [comment]
please update to 0.4.5
