### ISSUE TITLE
CORS support with CSRF

### ISSUE THREAD

**Issue by jrhite** [angular/angular#19349]
https://github.com/angular/angular/blob/0f5c70d563b6943623a5940036a52fe077ad3fac/packages/common/http/src/xsrf.ts#L77-L84

Why isn't this configurable with `.withOptions()`?

I need to use CSRF with CORS and it seems like an oversight that this is not possible with `HttpClientXsrfModule`.

How should this be done, short of writing my own `HttpClientXsrfModule`?

I also asked the same question [here](https://stackoverflow.com/questions/46357225/httpclient-angular-4-4-3-csrf-and-cors) on StackOverflow.

Thanks.

**Comment by jrhite** [comment]
@alxhub any thoughts on this?

thanks!

**Comment by netdeamon** [comment]
Similar to #18859

**Comment by alxhub** [comment]
@jrhite you should write your own interceptor/module. The default module has no way of knowing the set of domains which will honor your same XSRF token.
