### ISSUE TITLE
Component's controller / service cannot be specialized (extended) without creating a new selector (element tag)

### ISSUE THREAD

**Issue by anil789** [angular/angular#1934]
Say there is DataGridComponent Component with its View-Annotation, Component-Annotation and Controller function. It has to be extended as SrollableDataGridComponent. It can only be done by defining a new set of annotations and a new controller function (which can extend the original function). This would be a serious limitation especially when in Angular 2.0 Component means View + Controller. Same can be said if a different service class has to be passed to the Component.

Creating new Component with its one annotation may be OK if the change is significant. But it is often needed to customize a very small part of the controller (by extending it).

I am pretty sure that I am missing something (I understand how to do it in Angular 1.0).

**Comment by mhevery** [comment]
This works as intended. You can write your own decorator which will copy the annotations to the sub-class.
