### ISSUE TITLE
How can i add routes when app in running?

### ISSUE THREAD

**Issue by BoBoRun1981** [angular/angular#19351]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior

![question](https://user-images.githubusercontent.com/31203128/30771979-ded051cc-a085-11e7-8555-b72b82d26b5e.png)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by steveblue** [comment]
This is a support request. You can add new Routes with the `resetConfig()` method on the Router, but you wouldn't necessarily do this after bootstrap, but prior to bootstrap with the `APP_INITIALIZER` provider. If you add Routes after bootstrap, the user will not be able to navigate directly to that route.

**Comment by BoBoRun1981** [comment]
ref #13232
