### ISSUE TITLE
Decorators aren't listed as such in API documentation

### ISSUE THREAD

**Issue by bisubus** [angular/angular#19358]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Some decorators (namely ViewChild, ViewChildren, ContentChild, ContentChildren) are [listed only as types](https://angular.io/api?query=contentchild) in API documentation.

## Expected behavior
Documentation for all decorators is available, like in [Angular 2 documentation](https://v2.angular.io/docs/ts/latest/api/#!?type=decorator)

## What is the motivation / use case for changing the behavior?

New API docs introduce a regression and don't provide consistent documentation for Angular decorators.

**Comment by Toxicable** [comment]
https://angular.io/api/core/ContentChildDecorator

**Comment by bisubus** [comment]
@Toxicable Yes, that's my point. It is listed as an interface, not as a decorator. When a user browses decorators, only core injector decorators are shown, https://angular.io/api?type=decorator

**Comment by Toxicable** [comment]
Because it is a Interface
https://github.com/angular/angular/blob/4.4.3/packages/core/src/metadata/di.ts#L217

**Comment by bisubus** [comment]
@Toxicable But also a decorator function. Interfaces cannot be called. End user uses it as `ContentChild` decorator function (not even as ContentChildDecorator) and would expect it to be listed as a decorator.  I assume it makes sense to document as is for Angular team, but there's is clear regression in documentation from v2 from a user's point of view.

**Comment by lazarljubenovic** [comment]
You're right, we **do** have ["decorator" as a type](https://angular.io/api?type=decorator) but it's not used consistently (as you point out, `ViewChild`, `ViewChildren`, `ContentChild`, `ContentChildren` all seem to be missing).

I guess this is because of the way they are exported. For example, [`Component`](https://github.com/angular/angular/blob/4.4.3/packages/core/src/metadata/directives.ts#L749-L754) is immediatelly exported as a decorator, and since it has `@Annotation` tag, the docs recognize it as such. But [`ContentChildren`](https://github.com/angular/angular/blob/4.4.3/packages/core/src/metadata/di.ts#L190-L195) is exported as a type alias. It looks like we need to tweak precedence of how we label symbols in the docs: make `@Annotation` stronger than `export type`.

**Comment by gkalpak** [comment]
cc @petebacondarwin

**Comment by petebacondarwin** [comment]
We have to do some magic to "guess" that a pair of interface + function are in fact a decorator. I suspect that the structure of the TypeScript that defines these has changed and so our guessing engine is now missing them as decorators. I'll look into it. Thanks for the notification @bisubus

**Comment by lazarljubenovic** [comment]
Can't we use the `@Annotation` JSDoc tag?

**Comment by petebacondarwin** [comment]
Not sure what you mean @lazarljubenovic. The thing is that the information for the decorator doc is spread between the interface and the function so we need to find both. For sure we could ask the developers to use a jsdoc tag to annotate the code for the decorator, but in practice this doesn't need to happen, as long as the code continues to be structured the way we expect it.

**Comment by petebacondarwin** [comment]
In case you are interested the code that does the "guessing" is here: https://github.com/angular/angular/blob/0f5c70d563b6943623a5940036a52fe077ad3fac/aio/tools/transforms/angular-api-package/processors/mergeDecoratorDocs.js

**Comment by petebacondarwin** [comment]
and here is the reason for the failure of our guessing algorithm: https://github.com/angular/angular/blob/0f5c70d563b6943623a5940036a52fe077ad3fac/packages/core/src/metadata/di.ts#L184

```typescript
export type ContentChildren = Query;
```
