### ISSUE TITLE
Calling el.setAttribute results in an error

### ISSUE THREAD

**Issue by kaisbe** [angular/angular#19355]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The thread I started on [StackOverflow](https://stackoverflow.com/questions/46259054/angular-calling-el-setattribute-results-in-an-error) for a while, describes the required information.

## Expected behavior
The thread I started on [StackOverflow](https://stackoverflow.com/questions/46259054/angular-calling-el-setattribute-results-in-an-error) for a while, describes the required information.

## Minimal reproduction of the problem with instructions
The thread I started on [StackOverflow](https://stackoverflow.com/questions/46259054/angular-calling-el-setattribute-results-in-an-error) for a while, describes the required information.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 55.0.3
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.0
- Platform:  linux x64

</code></pre>

**Comment by gkalpak** [comment]
The answer I posted on [StackOverflow][1] just now, explains why.

[1]: https://stackoverflow.com/questions/46259054/angular-calling-el-setattribute-results-in-an-error/46384947#46384947

**Comment by kaisbe** [comment]
@gkalpak Thanks!
