### ISSUE TITLE
Support ViewQuery in addition to Query, clean up work

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1935]
# Goals
- [x] `@Query(Type, {descendants: true})` currently queries light DOM
- [ ] `@ViewQuery(Type, {descendants: true})` should query view DOM
- [x] `QueryList<Type>` should be parametrizable.
- [x] `QueryList.length` length should be defined on `QueryList` as it is convenient to bind to.
- [x] `QueryList.first|last` should have `first` and `last` convenience methods on `QueryList`

**Comment by rkirov** [comment]
Additional item:

- hooking up the observable interface.

**Comment by matanlurey** [comment]
I guess I'll ask as well: anyway to do both shadow *AND* light DOM? ;)

**Comment by rkirov** [comment]
parametrization handle in #2332

**Comment by matanlurey** [comment]
Question:

What would be the best way to query something like this?

```html
<parent>
  <foo></foo>
  <foo></foo>
  <bar></bar>
  <baz></baz>
</parent>
```

If I want to get a reference to all of my components, do I need to `@Query(Foo)`, `@Query(Bar)`, etc? Is there a way to do this imperatively?

**Comment by rkirov** [comment]
@matanlurey We can support a random filter function when your query cannot be expressed through a single directive type, so you can write `@Query(MyFeature.filter) list: QueryList<dynamic>` where `static filter(obj) => obj is Foo || obj is Bar`.

An imperative API would be significantly different as then it probably wouldn't make sense to have a live list.

**Comment by matanlurey** [comment]
@rkirov: +1 for the filter approach.
