### ISSUE TITLE
Render bug

### ISSUE THREAD

**Issue by acopalipsis** [angular/angular#19353]
https://stackblitz.com/edit/angular-a3neen

Open the console and press any button. Why when you click on one button, both are rendered?
What a render is started twice.  This is a bug?

**Comment by mlc-mlapis** [comment]
@acopalipsis ... a click just run CD on the whole app by default.

**Comment by acopalipsis** [comment]
@mlc-mlapis I do not understand...

**Comment by mlc-mlapis** [comment]
@acopalipsis ... yes, ... for all of three:
1. Yes, it is expected. Any CD runs all bindings in the whole app by default.
2. Yes, CD is a short for ChangeDetection.
3. Yes, you have to use `OnPush` strategy to control exactly which component (branch of the whole app's tree should be refreshed).
