### ISSUE TITLE
ngIf, number values and 0

### ISSUE THREAD

**Issue by maxime1992** [angular/angular#19364]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I like to work with streams as much as possible and avoid subscribing by hand to my observables.
The thing is, when I have a stream `Observable<number>` and I use `<div *ngIf="myObs$ | async"></div>` if the value is 0, I do not get into the div. It's obviously not a bug and 0 is coerced as boolean which leads to "false". But I do think it's annoying in this case as it's harder to work with streams of numbers.

For example: 
```html
<div *ngIf="peopleLength$ | async as peopleLength">
  <div [ngPlural]="peopleLength">
    <!-- !!! the following line will never be displayed !!! -->
    <ng-template ngPluralCase="=0">There's currently nobody available</ng-template>
    <ng-template ngPluralCase="=1">There's only one person!</ng-template>
    <ng-template ngPluralCase="other">There are {{ peopleLength }} persons</ng-template>
  </div>
</div>
```

Also, `<div *ngIf="(peopleLength$ | async) >= 0 as peopleLength">` is not an option as `peopleLength` would either be `true` of `false` but definitely not a number (as expected).

## Minimal reproduction of the problem with instructions
Here's a stackblitz repro: https://stackblitz.com/edit/angular-62xuky

## What is the motivation / use case for changing the behavior?
Being able to work with streams of number easily **without having to wrap them into an object**

Angular version: 4.3.6

**Comment by Toxicable** [comment]
I don't see any reasonable way to solve this issue.
I think that it would be unreasonable and would be confusing to make `ngIf` "not render for falsey values, excluding 0"

My suggestion as a work around would be to wrap the value in an object

**Comment by mlc-mlapis** [comment]
@Toxicable ... I think that it was meant also `to render for falsey values ...`. But still probably really so minor importance that it is practically non-sense trying to solve as Angular design.

**Comment by trotyl** [comment]
In AngularJS the custom conversion to boolean is considered a BUG and has already been fixed in https://github.com/angular/angular.js/commit/bdfc9c02d021e08babfbc966a007c71b4946d69d:

> BREAKING CHANGE: values 'f', '0', 'false', 'no', 'n', '[]' are no longer
treated as falsy. Only JavaScript falsy values are now treated as falsy by the
expression parser; there are six of them: false, null, undefined, NaN, 0 and "".

**Comment by pkozlowski-opensource** [comment]
Yep, we've been down this path in AngularJS and we don't want to get there again. `0` is falsy in JS and I ngIf should not have any special-casing for a subset of falsy values.

Closing as won't fix.

**Comment by ghetolay** [comment]
I think what he really wants here is a way to create *template var* (e.g. add prop to context) decoupled from any structural directive (ngIf in this case).
Something like : 
```html
<magic exp="peopleLength$ | async as peopleLength">
<div *ngIf="peopleLength === null">
  <div [ngPlural]="peopleLength">
    <!-- !!! the following line will never be displayed !!! -->
    <ng-template ngPluralCase="=0">There's currently nobody available</ng-template>
    <ng-template ngPluralCase="=1">There's only one person!</ng-template>
    <ng-template ngPluralCase="other">There are {{ peopleLength }} persons</ng-template>
  </div>
</div>
```

I'm not saying I want that, I'm fine doing it inside the component, but op said : 
>I like to work with streams as much as possible and **avoid subscribing by hand to my observables**.

so I think that's the real about of this issue.

**Comment by trotyl** [comment]
That will be related to https://github.com/angular/angular/issues/15280.

**Comment by maxime1992** [comment]
Yessss @ghetolay this is exactly what we've been talking with @victornoel!
But I didn't know how to formulate that. Extracting the observable as you pointed out @ghetolay would be :ok_hand:
