### ISSUE TITLE
fakeAsync Test fails, when using Promise and DOM-Listener

### ISSUE THREAD

**Issue by tovo8296** [angular/angular#19367]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
A Unit test fails when the following conditions are true:
* Test runs with fakeAsync
* Test method calls DOM-Listener on the component with "nativeElement.dispatchEvent"
* Component calls "Promise.then()" on a resolved Promise
* Tests are executed with "ng test" (ie. with source mapping)

The error message is:

<pre>
  Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'ng:///DynamicTestModule/PromiseTestComponent_Host.ngfactory.js'.
            at http://localhost:9876/_karma_webpack_/webpack:/C:/work/mib3/main/node_modules/zone.js/dist/zone.js:2010:1
            at XMLHttpRequest.send (eval at createNamedFn C:/work/mib3/main/node_modules/zone.js/dist/zone.js:1476:1), <anonymous>:3:31)
            at Array.<anonymous> (node_modules/source-map-support/browser-source-map-support.js:107:134)
            at node_modules/source-map-support/browser-source-map-support.js:101:106
            at Array.<anonymous> (node_modules/source-map-support/browser-source-map-support.js:107:501)
            at node_modules/source-map-support/browser-source-map-support.js:101:106
            at a (node_modules/source-map-support/browser-source-map-support.js:101:312)
            at b (node_modules/source-map-support/browser-source-map-support.js:104:356)
            at node_modules/source-map-support/browser-source-map-support.js:105:245
            at Array.map (<anonymous>)
            at Function.f (node_modules/source-map-support/browser-source-map-support.js:105:211)
            at Function.NativeError.prepareStackTrace C:/work/mib3/main/node_modules/zone.js/dist/zone.js:1052:1)
            at ZoneAwareError C:/work/mib3/main/node_modules/zone.js/dist/zone.js:918:1)
            at getStacktraceWithUncaughtError C:/work/mib3/main/node_modules/zone.js/dist/long-stack-trace-zone.js:39:1)
            at new LongStackTrace C:/work/mib3/main/node_modules/zone.js/dist/long-stack-trace-zone.js:33:1)
            at ____________________Elapsed_13_ms__At__Mon_Sep_25_2017_10_13_06_GMT_0200__W__Europe_Daylight_Time_ (http://localhost)
            at Object.onScheduleTask C:/work/mib3/main/node_modules/zone.js/dist/long-stack-trace-zone.js:104:1)
            at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask C:/work/mib3/main/node_modules/zone.js/dist/zone.js:378:1)
            at Object.onScheduleTask C:/work/mib3/main/node_modules/zone.js/dist/zone.js:274:1)
            at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask C:/work/mib3/main/node_modules/zone.js/dist/zone.js:378:1)
            at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask C:/work/mib3/main/node_modules/zone.js/dist/zone.js:209:1)
            at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleEventTask C:/work/mib3/main/node_modules/zone.js/dist/zone.js:235:1)
            at zoneAwareAddListener C:/work/mib3/main/node_modules/zone.js/dist/zone.js:1370:1)
            at HTMLDivElement.addEventListener (eval at createNamedFn C:/work/mib3/main/node_modules/zone.js/dist/zone.js:1476:1), <anonymous>:3:43)
            at DomEventsPlugin.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.DomEventsPlugin.addEventListener C:/work/mib3/main/node_modules/@angular/platform-browser/@angular/platform-browser.es5.js:3076:1)
            at EventManager.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.EventManager.addEventListener C:/work/mib3/main/node_modules/@angular/platform-browser/@angular/platform-browser.es5.js:2414:1)
            at DefaultDomRenderer2.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.DefaultDomRenderer2.listen C:/work/mib3/main/node_modules/@angular/platform-browser/@angular/platform-browser.es5.js:2935:1)

</pre>

## Expected behavior

The unit test should not fail, because there is no error.
Actually it doesn't fail if it's executed without source mapping ('ng test -sm=false')

## Minimal reproduction of the problem with instructions
Here the component and test source files to reproduce it. Run it with "ng test" to see the test failing.
<p>
Component:
<pre>
import {Component, HostListener} from '@angular/core';

@Component({
  selector: 'au3-promise-test',
  template: '<p class="promise-test"></p>',
})
export class PromiseTestComponent {

  @HostListener('pointerdown')
  pointerdown(pointerId: number) {
    const promise = Promise.resolve(true);
    promise.then(() => {
      console.log('*** Inside Promise.then');
    });
  }

}
</pre>

<p>
Test source
<pre>
import {async, ComponentFixture, fakeAsync, TestBed} from '@angular/core/testing';
import { PromiseTestComponent } from './promise-test.component';
import {By} from '@angular/platform-browser';

describe('PromiseTestComponent', () => {
  let component: PromiseTestComponent;
  let fixture: ComponentFixture<PromiseTestComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ PromiseTestComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(PromiseTestComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  fit('should call the pointer listener', fakeAsync(() => {
    const element = fixture.debugElement.query(By.css('.promise-test'));
    element.nativeElement.dispatchEvent(new Event('pointerdown', {'bubbles': true}));
  }));
});

</pre>

## Environment

<pre><code>
Angular version: 4.2.4

Browser:
- [ x] Chrome (desktop) version  60.0.3112.113
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Windows 7

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
