### ISSUE TITLE
Form validation: Submit button is being enabled when input tag has required and pattern fields. 

### ISSUE THREAD

**Issue by dvkrockz** [angular/angular#19368]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior
https://plnkr.co/edit/LFc32H1ARJTYFmiBvVft?p=preview

Form submit button validation works properly if the input tag has required property and checking the !heroForm.form.valid for disabled property.

## Expected behavior

But this does not work as expected when we have required and pattern fields for input element.
Form is still invalid but the submit button is being enabled when we move out of focus without any value in the input field but has some empty spaces.

https://plnkr.co/edit/2ftNUH1xcP6kqMgUnejK?p=preview

## Minimal reproduction of the problem with instructions
Please run both the plunkers ans check for the hero form with name as empty in first example and with some spaces in second example.

## What is the motivation / use case for changing the behavior?
Unexpected behavior, form validation behaves differently. 

## Environment
All browsers  and Angular version: 4.4.3
Live example from https://angular.io/guide/form-validation.

Browser:
All browsers
 
For Tooling issues:
- Node version: ran using plunker. Please find the URLS above.
- Platform:  Windows

**Comment by Toxicable** [comment]
There is a lot of code in your plunks that is unrelated to your reported issue.
Can you please make a **Minimal** reproduction of your issue

**Comment by kara** [comment]
@dvkrockz The problem here is that your plunker is re-defining the `heroForm` template variable in a later form, so it no longer corresponds with your form. If you remove the duplicate template var, it works as expected:

https://plnkr.co/edit/KTbW6ePaVPoSqO473RkP?p=preview
