### ISSUE TITLE
Pipe InvalidPipeArgument errors always reference CurrencyPipe regardless of the Pipe being used.

### ISSUE THREAD

**Issue by PlantPorridge** [angular/angular#19373]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Pipe InvalidPipeArgument errors always reference CurrencyPipe regardless of the Pipe being used.
For example, when using the Decimal Pipe and you provide it with an invalid digit info you will get an error like: 'a is not a valid digit info' for pipe **'CurrencyPipe'** 

## Expected behavior
InvalidPipeArgument errors should reference the Pipe that was being used.

## Minimal reproduction of the problem with instructions
*STEPS TO REPRODUCE*

1. Create a view and add a Decimal Pipe or Percentage Pipe.
2. Give the Pipe an invalid 'digits' input. (e.g. <span>{{5 | number:'a'}}</span>)
3. Observe the console error references Currecy Pipe even though it was not used.

Observe the console in Plnkr: 
http://plnkr.co/edit/mWYSShNIzuui1bZDIEpv?p=preview

## What is the motivation / use case for changing the behavior?
Fixed error logging.

## Environment

<pre><code>
Angular version: 5.0.0-beta.7

Browser:
- [x] Chrome (desktop) version 60.0.3112.113
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.0
- Platform: Mac

Others:

</code></pre>

**Comment by trotyl** [comment]
https://github.com/angular/angular/blob/master/packages/common/src/pipes/number_pipe.ts#L52
https://github.com/angular/angular/blob/master/packages/common/src/pipes/number_pipe.ts#L90

These two lines have incorrect parameters, PR welcome.

**Comment by ocombe** [comment]
Woops this is a bad copy paste :D
Gonna fix it, thanks for reporting!
