### ISSUE TITLE
Fix the testing docs - remove an incorrect paragraph

### ISSUE THREAD

**Issue by shairez** [angular/angular#19380]
## I'm submitting a...
<pre><code>
[x] Documentation issue or request
</code></pre>

## Current behavior
Currently, in the testing docs, the section about "[Always get the service from an injector](https://angular.io/guide/testing#always-get-the-service-from-an-injector)" is not representing the current behavior.

In the code example before that paragraph, on "[Test a component with a dependency](https://angular.io/guide/testing#test-a-component-with-a-dependency)"

You clearly see the use of `useValue` here- 

`providers:    [ {provide: UserService, useValue: userServiceStub } ]`

The problem is, that when we use `useValue` we **do** in fact get the same object reference to the stub.

Here's a plunker which proves it - 
https://plnkr.co/edit/zmT6s9L8ksDFQn9QVPf2?p=preview

I like it this way (not having to "get" the spy/stub again),
Let's not change the implementation, let's just fix the docs.

## Expected behavior

I suggest to remove this paragraph from the docs, as it isn't correct.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/zmT6s9L8ksDFQn9QVPf2?p=preview

## What is the motivation / use case for changing the behavior?
Keeping the docs correct.

## Environment

<pre><code>
Angular version: 4.4.2
</code></pre>

**Comment by trotyl** [comment]
Try https://plnkr.co/edit/6vDYuYSTpHmwBiY4DZ4j?p=preview and type `serviceInjected == serviceProvided`. They're indeed two different instances:

![image](https://user-images.githubusercontent.com/6059170/30813354-d05efdc6-a23f-11e7-88ba-543693fab545.png)

**Comment by shairez** [comment]
You're right, I've made a mistake in the plunker
Closing it.
Thanks!
