### ISSUE TITLE
Complex/odd nested ngFor issue -- I can't think of a brief title

### ISSUE THREAD

**Issue by wnipper** [angular/angular#19386]
## I'm submitting a...
<pre><code>
[X ] Bug report  
</code></pre>

## Current behavior
I have two lists.  One is possible Teams.  The other displays possible Permissions on those Teams.  I have an outer loop that lists the teams.  I have an inner loop that runs each time and lists the permissions.

On the inner loop, the team's id is correct, *except* in my change directive.  In the change directive, it's _always_ the id of the first team in the team array.

Here's the weird thing.  I can't replicate the issue on plunker.  I've got the plunker as close to my code as I can and I can't make it happen there, but it is STILL happening on my server.  It makes about as much sense (absolutely none) that the id for the team would be correct when doing interpolation and wrong when used in the directive.

```
<ng-template #unchecked>
 {{team.id}}  TEAM ID IS CORRECT HERE
    <input type="checkbox" class="filled-in" id="{{permission.id}}" 
          (change)="changePermissionOnTeam(team.id, permission.id)" />
</ng-template>
[...]
    changePermissionOnTeam(teamId, permissionId, $event) {
        console.log(teamId); // TEAM ID IS WRONG HERE
        this.service.changePermissionOnTeam(teamId, permissionId);
    }
```

## Expected behavior
I would expect the team's id to be correct.

## Minimal reproduction of the problem with instructions

[Here's the link to the inexplicably working plunker.](http://plnkr.co/edit/KAGqN010MI0PdGnJTJ8w?p=preview)

## What is the motivation / use case for changing the behavior?
It's a bug (...I think?).

## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- [X] Chrome (desktop) version 60.0.3112.113
- [X] Edge version 40.15063.0.0
 
For Tooling issues:
- Node version: 6.11.0
- Platform:  Windows 10

Others:

n/a
</code></pre>

**Comment by Toxicable** [comment]
Im sorry but if you cant replicate the issue then we cannot investigate the issue you are reporting.

**Comment by wnipper** [comment]
Where can I look in the source to find what's being passed to the directive?

**Comment by wnipper** [comment]
So.  I've tried everything I can think of.  The problem still exists.  I even tried wrapping the checkbox in a template with a declared variable; the declared variable is correct when displayed via interpolation and still the first in the series in the directive.  It seems something is making the change directive cache the value of `team.id`.  I'm going to go back to work on the plunker and see if I can break it.

**Comment by wnipper** [comment]
You can close.  Turns out, it's a problem with MaterializeCSS, not with angular.  Sorry about that.
http://plnkr.co/edit/KAGqN010MI0PdGnJTJ8w?p=preview

**Comment by vicb** [comment]
You could have closed it too :)

Thanks
