### ISSUE TITLE
blob:http://localhost:8080/1bd540ec-970b-4851-b7d5-10323bbdd314 is loaded on load

### ISSUE THREAD

**Issue by praveen4554** [angular/angular#19383]
i never called blob. It is loaded on load and it takes 4 secs to load that can any one help me with this issue

Thanks,
Praveen

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by praveen4554** [comment]
can you help why it takes 4 secs to load

**Comment by pkozlowski-opensource** [comment]
@praveen4554 this is _really_ not the right place to ask this type of support question. See comment from @ericmartinezr
