### ISSUE TITLE
angular2 to struts2 http post, getting data as null

### ISSUE THREAD

**Issue by paddy1205** [angular/angular#19382]
Trying to send http post data to struts 2 action class

`const req = this.http.post('http://localhost:8080/website/actionclassmethod',{ "description": "foo",   
type": "bar", "example": "asdfkkjsdaf kjasdf"  },options) .subscribe(
      res => {        console.log(res);      },
      err => {        console.log("Error occured");      }      );`

struts 2 action:
` <package name="default" extends="struts-default,json-default" namespace="/">
<action name="actionclassmethod" class="actionclass" method="actionclassmethod">
            <result  name ="success" type="json" />
 </action>`

this action class variables( with getter setter) are receiving description, type, and example as null.
It will be great help to get answer. 
Thanks in advance.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by paddy1205** [comment]
its already been there but nobody is there to answer.

**Comment by paddy1205** [comment]
https://stackoverflow.com/questions/45954402/send-and-receive-htttp-post-data-from-angular-2-in-struts

**Comment by pkozlowski-opensource** [comment]
@paddy1205 the fact that the question doesn't have answer on SO doesn't make it more appropriate here. You probably need to re-formulate your question, add more details, narrow down the problem etc.

In any case, it doesn't belong here.
