### ISSUE TITLE
Creating a template directive using DynamicComponentLoader?

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1939]
A template directive (e.g. `*`) lets you attach a `ViewRef` from another location.

What if I want to add a template directive dynamically at runtime?

@jelbourn in case he knows :smile:

**Comment by tbosch** [comment]
Let's talk in person, there might be a little confusion between
ProtoViewRef, ViewRef and ViewContainerRef...

**Comment by mhevery** [comment]
Not an actionable issue, closing. Ping me if you need clarification.
