### ISSUE TITLE
ngOnInit not called when navigating to a route by URL

### ISSUE THREAD

**Issue by mattwilson1024** [angular/angular#19398]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In a hybrid app with both AngularJS and Angular routers & components, the Angular router does not call the appropriate ngOnInit lifecycle method for a component if it is navigated to by:
- directly entering a URL into the browser address bar
- linking to it with a plain hyperlink (`<a href="#/movies`) rather than with a [routerLink]

The router shows the component on the page but the component's ngOnInit lifecycle method doesn't get called until the user clicks on the page or switches tabs. Perhaps change detection is not being triggered somewhere along the line?

## Expected behavior

Whenever a route is navigated to (regardless of whether it is caused by a routerLink, direct URL change, back/forward navigation etc), the component is created and its normal creation lifecycle triggers immediately. 

## Minimal reproduction of the problem with instructions

See https://github.com/mattwilson1024/angular-dual-routers for an example project showing this problem.

1. Checkout the above repo
2. `yarn` or `npm install` to install dependencies
3. `yarn start` or `npm start` to run the app
4. The app starts up on the "Actors" page (`http://localhost:8000/#/actors`)
5. Change the url to `http://localhost:8000/#/movies` in the browser address bar
6. Notice that the Movies list does not start loading immediately (this is the problem)
7. Click the blue area and it kicks into life. 
8. Note that the links work correctly if they use `routerLink` but not if they are changed to plain hyperlinks.

## What is the motivation / use case for changing the behavior?

In this particular scenario, the router / change detection don't seem to work as expected.

## Environment

<pre><code>
Hybrid App (with ngUpgrade)
Angular version: 4.4.3
AngularJS version: 1.6.4

Browser:
- [x] Chrome (desktop) version 61.0.3163.100 for Mac
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by gkalpak** [comment]
I cloned the repo and run the commands, but I coulnd't reproduce the problem. The movies list does get filled (after a couple of seconds). (There are also a lot of typings errors emitted by webpack, but I guess that doesn't affect the app.)

BTW, keep in mind that it is recommended to call `upgrade.bootstrap()` from your AppModule's `ngDoBootstrap()` method (so that AngularJS is bootstrapped inside the Angular zone).

**Comment by mattwilson1024** [comment]
Thank you @gkalpak! 

Moving `upgrade.bootstrap()` to the AppModule's `ngDoBootstrap()` method has fixed the problem :tada:

It seems that the problem was caused by AngularJS running outside the Angular zone - meaning that manual changes to the URL or plain hyperlinks did not trigger change detection.

For anyone who has this issue in the future, the example repo was fixed in this commit: https://github.com/mattwilson1024/angular-dual-routers/commit/212b1f1838bb2f3c75f5e96511d1e026c3b95d71 and I created a branch with the original (broken) setup here: https://github.com/mattwilson1024/angular-dual-routers/tree/bad-bootstrap
