### ISSUE TITLE
ng-bind is working but {{}} doesn't

### ISSUE THREAD

**Issue by zyc017** [angular/angular#19395]
in my code , {{}} doesn't display the value ,but ng-bind works ,even it does't occur every time,any ideas help?

**Comment by trotyl** [comment]
Wrong repo, https://github.com/angular/angular.js.

**Comment by gkalpak** [comment]
This sounds like an AngularJS (1.x) issue. This repo is for Angular (2+).
The AngularJS repo is at https://github.com/angulat/angular.js.

You can reopen the issue there if you think this is a bug in AngularJS itself (providing a minimal reproduction of the problem) or you can ask for help on one of the [general support channels][1].

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
