### ISSUE TITLE
Duplicated path in loadChildren detected

### ISSUE THREAD

**Issue by Viktor-Bredihin** [angular/angular#19397]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have two modules: mobile and desktop, lazy loaded. In each of these modules I have login module, also lazy loaded. Now I'm getting the error 'Duplicated path in loadChildren detected'

## Expected behavior
It should be possible to have the same name module

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Viktor-Bredihin** [comment]
right now I have to write different url just to avoid this error. 
Here is my desktop route: { path: 'login', loadChildren: './login/login.module#LoginModule' }
Here is my mobile route: { path: 'login', loadChildren: '../mobile/login/login.module#LoginModule' }
Otherwise it won't work

**Comment by alanhg** [comment]
I met the same error.
I have to write different URL like you.

According to official doc, write absolute path is a method, but I think it's not a good one

**Comment by alanhg** [comment]
I think it's CLI's fault.

**Comment by moseleman** [comment]
add link at tsconfig.app.json file. like this:
`    "paths": {
      "@shared/*": ["app/shared/*"],
      "@layout/*": ["app/layout/*"],
      "@admin/*": ["app/admin/*"]
`
write absolute path like this:
in admin(server site):
`
import { HomeComponent } from '@admin/home/home.component';
`

in layout(client site):
`
import { HomeComponent } from '@layout/home/home.component';
`

it work for me.

**Comment by wilsoncook** [comment]
the same scenario of mobile and desktop, the same error

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

Please create a reproduction using one of the links above. Describe the difference between the expected and current behavior with the reproduction linked.

**Comment by vicb** [comment]
Closing as no repro has been provided
