### ISSUE TITLE
[aio] landing page layout issue

### ISSUE THREAD

**Issue by NoviceKang** [angular/angular#19402]
![qq 20170926200216](https://user-images.githubusercontent.com/14104274/30859308-adef1eae-a2f5-11e7-8da7-99e12cfe8c43.jpg)

**Comment by kukac7** [comment]
![](https://media.giphy.com/media/t2spMqIRB2oVO/giphy.gif)

**Comment by vicb** [comment]
@NoviceKang what is your device / browser ?

**Comment by NoviceKang** [comment]
Old chrome browser

**Comment by NoviceKang** [comment]
Chromium 55.0.2883.87

**Comment by NoviceKang** [comment]
Other browsers are fine,I don't think it's a big problem!

**Comment by gkalpak** [comment]
OOC, what is your OS, screen resolution and window width?

**Comment by NoviceKang** [comment]
notebook,190*1080,Win10 X64

**Comment by NoviceKang** [comment]
browsers is 32bit

**Comment by NoviceKang** [comment]
It may be that the core is not compatible with HTML5

**Comment by gkalpak** [comment]
I am also on Windows 10 x64 and couldn't reproduce it on any resolution. 
I am afraid we can't do much without a reproduction.

Since nobody else reported this, I am going to close it as non-actionable.
Happy to investigate more if anyone can provide more info.
