### ISSUE TITLE
Language Service. Expected the operants to be of similar type or any.

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#19408]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

```

export type SomeType = string | number;
...
@Component({
...
               template: `<h1 *ngIf="one === two">{{title}}</h1>`
...
export class AppComponent<T extends SomeType> {
    one: T;
    two: SomeType;

...
        console.log(this.one === this.two);
...
```

## Current behavior

Language Service shows error on comparison between `one` and `two`.

## Expected behavior

It's totally ok to compare them because their types are related (typescript shows no errors).

## Minimal reproduction of the problem with instructions

Check [the repo](https://github.com/WiseBird/angular_ls_failing_comparison).

## Environment

<pre><code>
Angular version: 4.3.3

**Comment by vicb** [comment]
Why would it be ok ? 
Closing as work as expected (plus this is a **valid** TS error, not related to Angular)

**Comment by WiseBird** [comment]
@vicb Sorry, but it is not TS error. As you can see I used the same comparison in component's code: `console.log(this.one === this.two);` and TS is ok with it.

**Comment by Toxicable** [comment]
TS is not ok with this see:
https://www.typescriptlang.org/play/#src=var%20num%3A%20number%3B%0D%0Avar%20str%3A%20string%3B%0D%0A%0D%0Anum%20%3D%3D%20str%3B

**Comment by icenold** [comment]
i can confirm this is not a TS error
![image](https://user-images.githubusercontent.com/16298042/61247083-9a7ff000-a70d-11e9-944f-478372b05a8f.png)
