### ISSUE TITLE
Language Service. Component ... must have a template or templateUrl

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#19406]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

I have a simple component with empty template:
```
@Component({
               selector: 'app-home',
               template: ''
           })
export class HomeComponent {
    title = 'Home!';
}
```

## Current behavior

Language service shows error that `Component HomeComponent must have a template or templateUrl`.

## Expected behavior

It has but empty.

## Minimal reproduction of the problem with instructions

Check [the repo](https://github.com/WiseBird/angular_ls_empty_template).

## What is the motivation / use case for changing the behavior?

There are cases when empty template is desirable (e.g. when building DOM with d3) LS shouldn't show error when template is specified as empty.

## Environment

<pre><code>
Angular version: 4.3.3

**Comment by SaturnTeam** [comment]
Why not use directives, if you don't need template?

**Comment by WiseBird** [comment]
Because you may need styles for dynamically created DOM.

**Comment by aitorllj93** [comment]
I have a route /restore which loads an empty RestoreComponent with logic about session restoring and redirect. That's an use case example.
