### ISSUE TITLE
Add a markAllTouched method to AbstractControl

### ISSUE THREAD

**Issue by shairez** [angular/angular#19400]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
To show all the form error messages, we need to implement ourselves a recursive function marking all form controls as `touched`.

## Expected behavior
Having a `markAllTouched` method like @kara Suggested on #11774 would solve this problem.
Recursively marking all children of an AbstractControl as touched.

## What is the motivation / use case for changing the behavior?

When a user submits a form, we want a quick way to display all the invalidation messages at once.

This is a common use case for forms submissions, having to know upfront all the problematic form fields you need to fix.

## Environment

<pre><code>
Angular version: 4.4.3

</code></pre>

**Comment by Splaktar** [comment]
This is what I currently do in a number of different projects:
```
  validateFormAndDisplayErrors(form: FormGroup) {
    Object.keys(form.controls).map((controlName) => {
      form.get(controlName).markAsTouched({onlySelf: true});
    });
  }
```

But it would certainly be nice if this was part of the framework as there may be a more efficient way of doing this. For example, this may be going only 1 level deep where it would be nice to have it go down the whole tree as mentioned in the OP.

**Comment by dominique-mueller** [comment]
Related to https://github.com/angular/angular/issues/11774

**Comment by shairez** [comment]
@dominique-mueller thanks, yep, I also mentioned it in the issue itself

**Comment by dominique-mueller** [comment]
Ah yes, overlooked that one 👍 
Isn't this issue a duplicate then?

**Comment by shairez** [comment]
Not really, because that issue talks about changing current behavior.

I'm suggesting to add a new method

**Comment by juracy** [comment]
My current helper for this (with nested group support):

```typescript
import { FormGroup } from '@angular/forms'

export function markAllTouched(form: FormGroup) {
  Object.keys(form.controls).forEach(field => {
    const control = form.get(field)
    control.markAsTouched({ onlySelf: true })
    if (control instanceof FormGroup) {
      markAllTouched(control)
    }
  })
}
```

**Comment by Splaktar** [comment]
For anyone looking for more explanation, examples, and edge case handling of this, [Loaine's blog post](https://loiane.com/2017/08/angular-reactive-forms-trigger-validation-on-submit/#trigger-validation-of-all-fields-on-submit) on this is quite good.
