### ISSUE TITLE
HttpClient issue when request may return 202 with json or 204

### ISSUE THREAD

**Issue by karptonite** [angular/angular#19413]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
For HttpRequests that may return either a 20x with json or 204 No Content response, it is awkward to set the headers in a way that makes sense. If you use the defaults, a 204 will error because the result body, an empty string, cannot be parsed to JSON. If you set the contentType to 'text', you can avoid that error, but then have to manually call parse on the responses that have content. 

## Expected behavior
Not sure. One alternative is to have some option to indicate that the response body is optional, and return null if it is not set. Another would be to recognize that 204 responses have no content, and not try to parse them--the return type might still be an issue, though.

## What is the motivation / use case for changing the behavior?
The motivating case here is an http patch request, for which [rfc 5789](https://tools.ietf.org/html/rfc5789) suggests returning 204 if the patch was applied, and also allows other status codes, such as 202 Accepted, which should include in the body information on how to check the progress of the request.

This is also somewhat related to issue #19090, another case in which it should be clear from the request (instead of, in the current case, the response code) that there should be no body.

**Comment by lazarljubenovic** [comment]
I'm not 100% sure if empty response are `''`, `undefined`. They're apparently not `null` though as that should actually work.

![image](https://user-images.githubusercontent.com/7661457/31048998-7c0954c6-a62a-11e7-94a9-2bf9428982fa.png)

Either way, I think that expected behavior is not to throw an error in these cases, regardless of the the status code and return `undefined`.

Isn't empty response always _allowed_, even if it's not 204? For example, 201 says "created" but it doesn't have to return anything. (Haven't checked with RFC, speaking from experience.)

**Comment by victornoel** [comment]
I suppose httpclient should not try to parse any body if it receives a 204, no?

**Comment by lazarljubenovic** [comment]
@victormejia I'd go for "not parse any body if it receives an empty string". Or at least have that setting under some config when importing. It's valid to return an empty body for any status, it's just that 204 means that _specifically_.

**Comment by karptonite** [comment]
One possibility is to look at the `Content-Type` header of the response to decide whether to parse. With an empty body, there should be no `Content-Type`, or, at the very least, the `Content-Type` should not be `application/json`. That may be a problem for APIs that incorrectly specify their `Content-Type`, however.

**Comment by trotyl** [comment]
In HTTP **empty body** and **no body** are two completely different scenarios, 204 response has no body, not empty body.

> All 1xx (Informational), 204 (No Content), and 304 (Not Modified) responses do not include a message body.  All other responses do include a message body, although the body might be of zero length.

https://tools.ietf.org/html/rfc7230#section-3.3.3

**Comment by karptonite** [comment]
Also, from the same section, responses to HEAD requests do not include a body, although the headers may indicate that they do, so going exclusively by the `Content-Type` header won't work, unless the request type is also taken into account.
