### ISSUE TITLE
Testing route guards requires boilerplate components

### ISSUE THREAD

**Issue by juliemr** [angular/angular#19428]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

The `RouterTestingModule` should provide some guidance for testing route guards, since they can contain significant application logic. At the moment, a strategy is to set up routes and use blank components:

```ts
   setupModule({
      declarations: [BlankCmp],
      imports: [
        MyGuardModule,
        RouterTestingModule.withRoutes([
          {
            path: 'section/path/page',
            component: BlankCmp,
            canActivate: [MyGuard]
          },
          {
            path: 'section/path/recent',
            component: BlankCmp,
            canActivate: [MyGuard],
            data: {purview: {strategy: PurviewStrategy.RECENT_ONLY}}
          },
          {
            path: 'section/path/recentfolder',
            component: BlankCmp,
            canActivate: [MyGuard],
            data: {
              purview: {
                strategy: PurviewStrategy.RECENT_ONLY,
                supportedTypes: [ResourceType.FOLDERS]
              }
            }
          },
          // etc.
        ]),
      ],
    });
```

This feels heavyweight - at least can we remove the need for the blank components everywhere? Any other ideas for the best guard testing strategy? The same concern roughly applies for route resolvers.

**Comment by guilhermejcgois** [comment]
Any other ideas for the best guard testing strategy? ²

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
