### ISSUE TITLE
Input value coming from a sibling component's output triggers the ExpressionChangedAfterItHasBeenCheckedError error

### ISSUE THREAD

**Issue by pedrus16** [angular/angular#19439]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I get the error `ExpressionChangedAfterItHasBeenCheckedError` when I pass an `ElementRef` from one component to the parent using `@Output` and then pass it down to another component's `@Input`.

Basically doing this:
```
<child (element)="elementRef=$event"></child>
<other-child [element]="elementRef"></other-child>
```
For some reason Angular detects multiple changes in the input and thus give me the error.

## Expected behavior
Angular shouldn't give this error.

## Minimal reproduction of the problem with instructions

Check the console on this plunker:
https://embed.plnkr.co/dRqUALq2dk8hSGJatTMi/

## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- [X] Chrome (Linux) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by alexzuza** [comment]
You can 

1) change ngAfterViewInit to ngOnInit because angular fills static view queries during creation view and therefore your @ViewChild will be filled.

https://plnkr.co/edit/UX6Z6MtloWxZpawKeiXa?p=info

2) Make `EventEmitter` async

`@Output() element: EventEmitter<ElementRef> = new EventEmitter<ElementRef>(true);`

https://plnkr.co/edit/CdMKXfpUSsLj1l8EHpv6?p=preview

3) Promise

4) setTimeout

...

**Comment by mlc-mlapis** [comment]
@pedrus16 ... classical example what not to do ... read https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4

**Comment by pedrus16** [comment]
Making the `EventEmitter` async worked. Thank you!
