### ISSUE TITLE
Add property in all components

### ISSUE THREAD

**Issue by gaurav22031987** [angular/angular#19437]
I am loading global application configuration setting using code in app.module.
<pre>
<code>
GlobalConfiguration,
    {
      provide: APP_INITIALIZER,
      useFactory: loadGlobalConfiguration,
      deps: [GlobalConfiguration],
      multi: true
    }

export function loadGlobalConfiguration(globalConfiguration: GlobalConfiguration): () => Promise<any> {
  return globalConfiguration.load();
}

</code>
</pre>
code in global configuration file
<pre>
<code>
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Rx';

@Injectable()
export class GlobalConfiguration {
  private accountSettings: any;

  load(): () => Promise<any> {
    return (): Promise<any> => {
      return new Promise((resolve, reject) => {
        let accountSettings = {
          useSimpleAccount: true,
          userRegistrationLoginType: 'email'
        };
        this.accountSettings = accountSettings;
        return resolve(this.accountSettings);
      });
    };
  }
  get config(): any {
    return this.accountSettings;
  }
}
</code>
</pre>
So instead of injecting GlobalConfigurationService in every component. I want ConfigurationVariable is accessiable in all component as component property so that i can use on HTML as make some decision on html based on configuration.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
