### ISSUE TITLE
delete of HttpClient causing error callback when backend returns success response

### ISSUE THREAD

**Issue by Yura13** [angular/angular#19432]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Method delete of HttpClient causing error callback when backend returns success response.
If downgrade to 4.3.6 everything works well.
Example of the error message:
```SyntaxError: Unexpected end of JSON input at Object.parse```

Example of code:
```
this.http.delete(`${environment.apiUrl}/Entity/${entity.id}`)
        .subscribe(
             () => { console.log('success')}, 
             () => { console.log('error')}
       );
```
If I have success response, i see message 'error'. So in this case will runs error callback.

## Expected behavior
Should start success callback when backend returns success response.

## Environment

<pre><code>
Angular version: 4.4.x

Browser:
-  Chrome (desktop) version 60.0
 
For Tooling issues:
- Node version: 6.11.3
- Platform:  Windows

**Comment by Toxicable** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by Yura13** [comment]
Sorry, but I am not very good with plunkr.
I found also information about this issue here: 
https://stackoverflow.com/questions/46423086/angular-httpclient-delete-failing-when-parsing-response
Maybe this post will useful for understanding.

**Comment by jonathanp** [comment]
This is probably because your HTTP response payload is empty, or is in a non JSON format. If that's the case then it's the same error as in #18680.

**Comment by vicb** [comment]
no repro -> not actionnable (and most probably a duplicate)
