### ISSUE TITLE
@ngtools. Support paths with TS mappings in templateUrl and styleUrls

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#19436]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

When extending a component I usually need to reuse styles. As components often comes from distant location ts mappings are used to reference them, e.g.:
```
import {LibComponent} from 'lib/lib.component';

@Component({
...
export class AppComponent extends LibComponent {
   ...
}
```

It would be convenient to reference styles in the same manner: `lib/lib.component.css` instead of using full path: `../../../lib/lib.component.css`;

## Current behavior

@ngtools can't resolve styles (or template) when paths use ts mappings.

## Expected behavior

Paths are resolved successfully.

## Minimal reproduction of the problem with instructions

Check [this repo](https://github.com/WiseBird/ngtools_ts_mapping_path).

## What is the motivation / use case for changing the behavior?

Should simplify component inheritance.

## Environment

<pre><code>
Angular version: 4.4.3

**Comment by listepo-alterpost** [comment]
Hi, any news?
