### ISSUE TITLE
HTML5 Video does not play in Safari

### ISSUE THREAD

**Issue by rjriel** [angular/angular#19430]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If I add a video element into a template in an Angular app and attempt to view the video, I get no result. When viewing the same video file in a basic HTML page it works perfectly

## Expected behavior

The HTML5 video should correctly work in Safari.

## Minimal reproduction of the problem with instructions

Create a blank html page that references a file to see that it should work fine
http://plnkr.co/edit/rXT4EC6RTFtGy8xqPk5E

Then create an Angular app with the same code inside the main component
http://plnkr.co/edit/iNNZZ2GeGs18a7RbDEcp

## What is the motivation / use case for changing the behavior?

I have a client which wishes to have a video play as the background of their landing page. This works fine in everything but Safari

## Environment

<pre><code>
Angular version: 4.3.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 11.0
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.5.0 
- Platform:  Mac 

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment]
I can confirm this problem with the latest Angular: https://stackblitz.com/edit/angular-hxy9ae?file=src%2Fapp%2Fapp.component.ts

By opening the above stackblitz one can see that the `autoplay` attribute doesn't have effect. There must be something specific in relation to DOM manipulation and the `<video>` tag but at this point I'm not sure what the root-cause is.

For the record I can reproduce it in Chrome as well, do doesn't seem to be specific to Safari.

**Comment by JeanMeche** [comment]
I'm closing this. Autoplay worked fine the repro on Safari & Chrome. (The video URL needs to be replaced on the repro as it is 404)
