### ISSUE TITLE
Proposal: lifecycle over convention

### ISSUE THREAD

**Issue by bukharin** [angular/angular#1943]
If a component has a onDestroy|onChange... method, angular automatically bind a same lifecycle, without explicit declaration?

``` typescript
@Component({  selector: 'my-component' })
class MyComponent {

  onDestroy() {
    // destroy code here...
  } 

} 
```

**Comment by gdi2290** [comment]
No, Angular checks first if there is a lifecycle annotation before invoking. Or at least that's what I read in the code awhile back

**Comment by bukharin** [comment]
@gdi2290 yes, but it's a proposal to check method existence instead of annotation

**Comment by gdi2290** [comment]
@bukharin oops my bad, I was on mobile and didn't read the title. It seems like there needs to be a strict mode to maintain better static analysis of their code. The annotations are verbose on purpose as a feature but that also seems to be hurting the developer experience (at least for small/toy apps which is what everyone is building right now)

**Comment by yjbanov** [comment]
Related: https://github.com/angular/angular/issues/2120

**Comment by mhevery** [comment]
Working as intended.
