### ISSUE TITLE
Factory providers are called before APP_INITIALIZER is resolved (before bootstrap)

### ISSUE THREAD

**Issue by shipiak** [angular/angular#19448]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Factory providers are called before APP_INITIALIZER is resolved (before bootstrap).
When using pattern with APP_INITIALIZER to load external configuration, config injection works only with services that are NOT provided by factory. 

## Expected behavior
Factory provider functions executed after APP_INITIALIZER resolved.

## Minimal reproduction of the problem with instructions
```
export function initConfiguration(configService: ConfigService): Function {
  return () => configService.load(); // makes http request and returns Promise correctly
}

// this is called before bootstrap - before APP_INITIALIZER resolved
export function serviceFactory(configService: ConfigService){
   return new SomeServiceDependentOnConfig(configService);
}

@NgModule({
  imports: [
    //Some imports here.
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  providers: [
    ConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: initConfiguration,
      deps: [ConfigService],
      multi: true
    },
    {
       // this one does NOT get config injected correctly (json config not yet loaded)
       provide: SomeServiceDependentOnConfig,
       useFactory: serviceFactory,
       deps: [ConfigService]
    },
    {
       // this one does get config injected correctly (json config already loaded)
       provide: SomeOtherServiceDependentOnConfig,
       useClass: SomeOtherServiceDependentOnConfig,
    }
  ]
})
export class AppModule { }


// then 
```

## What is the motivation / use case for changing the behavior?
1. need to use env config that is passed to te app during deployment (DEV,UAT,PROD) not during the build of the app
2. therefore using pattern with APP_INITIALIZER and loading env config using http request (json file)
3. need to use env config values directly in factory function - e.g. if config.value ?  return a() : return b()
4. need to use env config values in services created by factory

PS: Point 1. actually seems to me as kind of a bug itself, as current solution with angular environment config that is being passed to the app during the build is not really environment aware... I always thought that point of environment config is to change behavior of the same build, not that you have to make separate builds for each environment...

## Environment

<pre><code>
Angular version: 4.2.1

Browser:
- [ x] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@shipiak ... isn't the reason the fact that `SomeServiceDependentOnConfig` is used both as a token and also for creation of a new instance in `serviceFactory`? What about to use `TOKEN_ON_CONFIG` as `export declare const MYTOKEN: InjectionToken<(() => void)[]>;` for a token of the provider?

**Comment by shipiak** [comment]
@mlc-mlapis no it is not. I've tried also factory provider with injection token and same issue - factory is called before APP_INITIALIZER is resolved...

**Comment by mlc-mlapis** [comment]
@shipiak ... I tried that also and the factory was not loaded ... btw in general ... nothing in `providers` section  is loaded eagerly ... only on the first use ... so there should be something else in your code what invokes the factory.

**Comment by shipiak** [comment]
@mlc-mlapis Well of course you need to inject those services to some component to see the behavior... Code provided above is not full, I can provide a plunkr if that would be necessary...

**Comment by mlc-mlapis** [comment]
@shipiak ... sure, provide it, please. Without it, it's a bit problem to judge anything. 👍

**Comment by shipiak** [comment]
@mlc-mlapis I am sorry for being hot-headed with the report, you were right. Example above is not enough to reproduce as cause is little bit different than I thought. Issue is not with factory providers, it is bit more complex. 

Here are more details of not waiting for APP_INITIALIZER behaviour in my project: 
- I have service CustomErrorHandler implementing angular/core ErrorHandler
- Then in CoreModule I provide {provide: ErrorHandler, useClass: CustomErrorHandler },
- CustomErrorHandler have other services injected to constructor e.g. ApiService that I use to send error reports to the backend
- I have service ConfigService using APP_INITIALIZER pattern above, that works correctly for all other services except ApiService (ApiService is constructed before APP_INITIALIZER, without proper config)
- As soon as I remove injection of ApiService from CustomErrorHandler constructor everything works correctly also for ApiService

Issue seems to be that ErrorHandler is injected somewhere before APP_INITIALIZER, and this triggers also injection / construction chain of other of my services that are used in ErrorHandler.

I do not even know how correctly name this bug :), but it seems wrong :)

Should I update original report and add plunkr?
Or should I report new one?

Many thanks for help.

**Comment by shipiak** [comment]
https://medium.com/@amcdnl/global-error-handling-with-angular2-6b992bdfb59c

**Comment by mlc-mlapis** [comment]
@shipiak ... I understand all your points above. So the main thing seems to be that we have to decide what was first, chicken or egg? Because `CustomErrorHandler` should be able also to catch an error during APP_INITIALIZER resolving. So what now ...

You have to open a new issue for it, and a plunker is also needed ... but still not sure if it is an issue or a feature request ... but it is the interesting theme which should be resolved clearly ... what is the design that we should follow.
