### ISSUE TITLE
documentation of router outlet

### ISSUE THREAD

**Issue by rberge** [angular/angular#19443]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This is from the current tutorial on routing as of August 27,2017 at this url https://angular.io/guide/router

Router outlet

Given this configuration, when the browser URL for this application becomes /heroes, the router matches that URL to the route path /heroes and displays the HeroListComponent after a RouterOutlet that you've placed in the host view's HTML.

 content_copy
<router-outlet></router-outlet>

## Expected behavior

What is a host view HTML?
In the plunker and download files, there are not very many html files.
I find a router-outlet in app.component.html but it is surrounded by an "if" statement and there is nothing after it.
<% if (routing) { %>
<router-outlet></router-outlet><% } %>

here is an example of the files from the download from the website
(see uploaded screen shot)
![screen shot 2017-09-27 at 11 34 42 am](https://user-images.githubusercontent.com/20893688/30930927-0ef80936-a378-11e7-91cb-2b35a0683c44.png)

I don't understand what the tutorial is saying or why the examples don't match.  Is it possible to review and explain?
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kapunahelewong** [comment]
Hi @rberge, the host view in this case is the template in app/app.component.ts. It hosts anything that is rendered through a `<router-outlet>`. I'm not finding the `if (routing)` in the live example or the download. Can you point me to it? I'd love to help clear things up.

**Comment by rberge** [comment]
Thank you! I am still working on routing so will go back to the tutorial and see how this helps.  I appreciate it.

**Comment by kapunahelewong** [comment]
@rberge ok, let me know if you have any questions or suggestions for improvement. I'm still interested in the if statement you referenced. If you see it again, please let me know so I can take a look.

**Comment by jenniferfell** [comment]
I think the remaining summary is this: Update https://angular.io/guide/router#router-outlet to be more clear about this: the host view in this case is the template in app/app.component.ts. It hosts anything that is rendered through a <router-outlet>.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/angular/angular/pull/20023
