### ISSUE TITLE
Update @angular/benchpress npm package

### ISSUE THREAD

**Issue by guilhermevrs** [angular/angular#19442]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Npm package dates from one year ago.

Issues with typescript compilation when running lib check for benchpress

## Expected behavior

Get the latest state of the code in the npm package.
The typescript problem has already been fixed by https://github.com/angular/angular/pull/18455

**Comment by vicb** [comment]
@guilhermevrs thanks for noticing. We'll fix that.

/cc @IgorMinar

**Comment by junglebarry** [comment]
In the absence of an easy npm installation (latest version is apparently 0.1.0), is there another recommended way to use the current version of benchpress in a project? Being a monorepo, it’s pretty involved to build from source, and there are bug fixes in the latest versions that I’d really like to access. Or am I just being daft and missing something really obvious?

Thanks in advance!

**Comment by IgorMinar** [comment]
I'll schedule this for the next sprint.

**Comment by kiyanwang** [comment]
@IgorMinar is there any update on this?

**Comment by junglebarry** [comment]
@IgorMinar sorry to bump this, but this issue was due to be considered for v6, and that’s come and gone. Is it still under consideration?

**Comment by junglebarry** [comment]
There seems to have been a reasonable amount of activity on the benchpress package recently - is there a plan to release to `npm`?

**Comment by trogowski** [comment]
Can I ask what is the status of Benchpress? Is it actively developed and still used internally by Google? Last update to this part of repo was over 3 months ago (deps update) but the last npm release was over 3 years ago. Is Benchpress no longer maintained or am I missing something?
