### ISSUE TITLE
aio: add open search description to allow browser bar querying

### ISSUE THREAD

**Issue by ShadowManu** [angular/angular#19462]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If you want to search for an API, open the angular.io/api page, focus (click) the input box, and write the API search.

## Expected behavior

Start writing `angular` in the browser bar, hit TAB and write the API search.

## What is the motivation / use case for changing the behavior?

Searching the current API documentation is something (I believe) very common and this can speed that up a lot, particularly searching multiple APIs.

**Comment by gkalpak** [comment]
That would be a nice addition indeed. (Here is [some info][1] for future reference.)

FWIW, you can add this yourself (in Chrome at least). Go to `Settings` > `Manage search engines` > `Add`.
For API docs use: `https://angular.io/api?query=%s`
For general search (API, guides, etc) use: `https://angular.io/?search=%s`

Also, once you are https://angular.io, you can type `/` (which focuses the search box) and type a query.

[1]: https://www.chromium.org/tab-to-search

**Comment by sarunint** [comment]
Tracked in #24107

**Comment by gkalpak** [comment]
Closing in favor of #24107.
