### ISSUE TITLE
[reverted] PR 19225 & 19226

### ISSUE THREAD

**Issue by vicb** [angular/angular#19468]
@tinayuangao could you please take a look at this (DMing you the details)

#19225 and #19226 have been reverted from master

/cc @jasonaden has more details

**Comment by mhevery** [comment]
@tinayuangao what is the status of this?

**Comment by tinayuangao** [comment]
The pr #19842  is pending @matsko 's review. 
Should be merge ready with his approval.

**Comment by tinayuangao** [comment]
Fixed by #19842
