### ISSUE TITLE
Router link redirect to home component, insted to go  to the specified route

### ISSUE THREAD

**Issue by atlabiz** [angular/angular#19460]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

All the links where I have some variable go to home component first instead to go to the specified route
For example, I have a router link like 
`<a routerLink="/crm/admin/add_new_product">  <--- this works ` but

### All that routes have the same problem 
```typescript
  { path:   'pharmacist/:id/dashboard',           component: PharmacistDashboardComponent },
  { path:   'pharmacist/:id/offers',              component: PharmacistOffersComponent },
  { path:   'pharmacist/:id/create_offer',        component: PharmacistCreateOfferComponent },
  { path:   'pharmacist/:id/offers/:oid/edit',    component: PharmacistEditOfferComponent },
  { path:   'pharmacist/:id/offers/:oid/delete',  component: PharmacistDeleteOfferComponent },
  { path:   'pharmacist/:id/settings',            component: PharmacistSettingsComponent },
```

### These routes don't have problem
```typescript
  { path:   'crm/admin/agents',                 component: AdminAllAgentsComponent },
  { path:   'crm/admin/requests',               component: AdminAllRequestsComponent },
  { path:   'crm/admin/pharmacists',            component: AdminAllPharmacistsComponent },
  { path:   'crm/admin/add-pharmacist',         component: AdminAddPharmacistComponent },
  { path:   'crm/admin/edit-pharmacist/:id',    component: AdminEditPharmacistComponent },
```

## Stackoverflow
>  https://stackoverflow.com/questions/46467596/angular-4-routerlink-navigate-to-localhost4200-instead-of-localhost4200-us

`<a routerLink="/crm/admin/edit_product/{{ some_product_id }}">  <--- this is not work works `

The same happens with the `app-routing.module.ts`

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
