### ISSUE TITLE
Router error: Cannot instantiate Token(ComponentRef) synchronously.

### ISSUE THREAD

**Issue by pumpk1n** [angular/angular#1947]
I've built Angular2 and the router from src and I get an error `Cannot instantiate Token(ComponentRef) synchronously. It is provided as a promise! (RouterOutlet -> Router -> Token(ComponentRef))`

The code I use:

```typescript
/// <reference path="../typings/angular2/angular2.d.ts" />

import {Component, View, bootstrap} from 'angular2/angular2';
import {Router, RouterOutlet, RouteConfig, routerInjectables, RouterLink} from 'angular2/router';

@Component({
	selector: 'app'
})
@View({
	template: '<router-outlet></router-outlet>',	
	directives: [ RouterOutlet ]
})	
@RouteConfig([
	{ path: '/', component: Test, as: 'test' }
])
class App { }

@Component({
	selector: 'test'		
})	
@View({
	template: 'test'
})
class Test { }

bootstrap(App, [routerInjectables]);
```

**Comment by gdi2290** [comment]
@pumpk1n it's working fine with my starter kit https://github.com/angular-class/angular2-webpack-starter Are you using Angular2 alpha.23?

**Comment by pumpk1n** [comment]
Nope, I cloned this repo and built it from src. Alpha.23 is kinda buggy (back doesn't work, can't open links directly, etc), that's why I tried to build.

**Comment by gdi2290** [comment]
@pumpk1n can you provide a repo

**Comment by pumpk1n** [comment]
Here it is: https://github.com/pumpk1n/angular2-router-test

**Comment by pumpk1n** [comment]
Since there was a bigger update to the router a couple minutes ago I've updated to the latest rev, but still the same error. 

@btford any idea what's going wrong?

**Comment by vicb** [comment]
@pumpk1n this could be linked to https://github.com/angular/angular/issues/1111 which is a "bug" in Angular.
