### ISSUE TITLE
HttpParams: Documentation inaccurate, or a bug?

### ISSUE THREAD

**Issue by shousper** [angular/angular#19470]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```
this.http.get('http://blah', {
  params: new HttpParams()
    .set('filter[courtSystemId]', courtSystemId)
    .set('filter[parentId]', '')
})
```

Makes a request with:

```
updates=%7B%22param%22:%22filter%5BcourtSystemId%5D%22,%22value%22:%22db8175a6-a8e9-4bd3-adf1-77af4dd3330c%22,%22op%22:%22s%22%7D&updates=%7B%22param%22:%22filter%5BparentId%5D%22,%22value%22:%22%22,%22op%22:%22s%22%7D&cloneFrom=%7B%22updates%22:null,%22cloneFrom%22:null,%22encoder%22:%7B%7D,%22map%22:null%7D&encoder=%7B%7D&map=null
```

As the query string.

## Expected behavior

Although the example is for a `post`, I think this behaviour should be the same, no? I couldn't find any examples for using a `get`. The current working code for a `get` appears to be:

```
const params = new URLSearchParams()
params.set('filter[courtSystemId]', courtSystemId)
params.set('filter[parentId]', '')

this.http.get('http://blah', { params })
```

But as I said, I couldn't find an example of this very easily and was confused by the `post` apparently working quite differently. Using `URLSearchParams` is also less pleasant to use as it doesn't share the same builder pattern design (i.e. the `set` methods don't return `this`).

## Minimal reproduction of the problem with instructions

Please see above.

## What is the motivation / use case for changing the behavior?

This seems like maybe a bug, but maybe just a documentation issue. Could also be I just suck at searching your docs :)

## Environment

<pre><code>
Angular version: 4.4.2

Browser:
- [x] Chrome (desktop) version 60.0.3112.113
 
For Tooling issues:
- Node version: v6.10.2
- Platform:  Mac

Others:
N/A
</code></pre>

**Comment by trotyl** [comment]
Are you mixing old `Http` with new `HttpClient`'s `HttpParams`?

**Comment by shousper** [comment]
Yup, nailed it. Thanks @trotyl! Sorry to waste your time.
