### ISSUE TITLE
Perf: move to RxJS 5.5 lettable operators

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular#19476]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Angular currently use `rxjs/add/operator/x`.

## Expected behavior
Angular 5 should use the [new lettable operators introduced in RxJS 5.5](https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md) to reduce bundles sizes (and to have a better dev experience too).

Otherwise, people using this new way to import RxJS operators will see their bundles sizes increased, as the operators will be imported twice.

## What is the motivation / use case for changing the behavior?
I think it's already somewhere in the pipe, but even if RxJS 5.5 is in beta for now, it's important to plan it for v5, as this may introduce a breaking change, requiring RxJS >= 5.5. Otherwise we'll have to wait for Angular 6.

And as I see v5 is already in RC, it may be a good time to decide about that.

**Comment by Toxicable** [comment]
They don't use that method everywhere
Most places use the `operator.call` method like so: https://github.com/angular/angular/blob/master/packages/common/http/src/client.ts#L414

So it wouldn't change much for the end users since it would effectively be the same.
However it's still a good idea since it would make the code much easier to read and also since it's the recommended method by `rxjs` now

**Comment by IgorMinar** [comment]
Angular core or material don't use `rxjs/add/operator/*` at all. We use the `operator.call` way of invoking operators which is uglier but doesn't monkey-patch Observable prototype or pull in a lot of code.

We will not use lettable operators in core until v6 because that would make the RxJS upgrade a requirement. Given that 5.5 is not stable yet, we can't make the upgrade a requirement.

We are working with rxjs to get 5.5 stable release out, but there are still a few size-related blockers in the way.

**Comment by mmc41** [comment]
@IgorMinar Even though angular 5 core won't use RxJs 5.5, I hope that it is compatible with it so angular 5 apps can freely chose RxjS 5.5 together with Angular 5 ?

**Comment by IgorMinar** [comment]
Yes. rxjs is 5.5 is backwards compatible, so it will work with Angular v2, 4 and 5.

**Comment by cyrilletuzi** [comment]
It will work, but will it be OK relative to bundle sizes, or will it import each operator twice (one from current Angular implementation, the other from the user using the new lettable operators) ?

**Comment by cyrilletuzi** [comment]
And a precision : RxJS 5.5 is backward compatible, so you can upgrade in Angular 2/4/5 without problem, but for using the new lettable operators in TypeScript, you need TS 2.4 minimum, meaning lettable operators can only be use in Angular 5 (as previous versions are not compatible with TS 2.4).

**Comment by cyrilletuzi** [comment]
@IgorMinar I suppose you know, but RxJS 5.5 is now stable. And Angular 5 is not yet, so it's still time.

Consider it will impact Angular community libraries authors and users too : 
- for a library author, who is not confortable with more difficult code (`operators.call`), and want to switch to new lettable operators for performance, the library will have different dependencies requirements (RxJS >= 5.5) than Angular 5, resulting in mess for users,
- or if the library author delay the move, waiting for Angular 6, and library users switch their Angular 5 app to RxJS 5.5 (which will be the case for new projects generated by the CLI), operators will be imported twice, resulting in bigger builds.

**Comment by devoto13** [comment]
@cyrilletuzi Angular has `rxjs` as `peerDependency` and allows to provide any version, including 5.5. And libraries, who need to use >5.5 should specify `"rxjs": ^5.5.0` in their `peerDepencencies` to mitigate problems you described above. I will be up to user than to pick version, which will satisfy their needs and all peer dependencies.

Regarding bundle size. Assuming that previous item is done right and there is a single instance of `rxjs` library in the project, it looks like using lettable operators is introducing overhead over not using them :) [This](https://github.com/ReactiveX/rxjs/blob/master/src/operator/count.ts) is base implementation of the operator (used in both lettable and normal case). And when using not lettable version it will also load [this](https://github.com/ReactiveX/rxjs/blob/master/src/operators/count.ts). So it's 3 line of code overhead per lettable operator used. Which doesn't sound like a lot.

So while I still vote for updating RxJS to 5.5 to make for example [router code](https://github.com/angular/angular/blob/master/packages/router/src/router.ts) readable for mere mortals, it's doesn't seem to cause any serious problems to the eco system if not bumped.

PS And as you said Angular CLI will likely use 5.5 for new projects anyway, so new projects will get it automatically.

**Comment by jasonaden** [comment]
@cyrilletuzi @devoto13 Thanks for the issue. We've been working closely with the rxjs team to get to a final version of 5.5 (completed this morning). So we are updating the peer dependency requirements for Angular 5 here #19345.

A future PR will change the Angular code from using the `.call` syntax to the cleaner lettable operators with `pipe`.

cc @IgorMinar

**Comment by Toxicable** [comment]
just putting in a link here to this since it's relevant: https://github.com/ReactiveX/rxjs/pull/2882

**Comment by IgorMinar** [comment]
Two more relevant links:
- https://github.com/angular/angular/pull/19702/commits/798de6ffa80c2e46731e8315d21071ddeac81d6c (cli will incorporate this change soon)
- https://github.com/angular/devkit/issues/214 (this is to fix size regressions when one imports from rxjs/operators within a cli project)

**Comment by cyrilletuzi** [comment]
Closing, as Angular 5 requires RxJS 5.5 and as comments say internal code doesn't impact performance.
