### ISSUE TITLE
Angular 5 RC0: Unable to locate ngfactory for third-party module during AOT compilation

### ISSUE THREAD

**Issue by tsvetomir** [angular/angular#19478]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior
The compiler is unable to locate the ngfactory file for an _indirectly included_ third-party module.

Compiling the application with AoT compilation produces the following error:
```
> ng build --target production --aot true --build-optimizer true

Date: 2017-09-29T12:19:49.993Z                                                     
Hash: c6ed5bfe57750eabeded
Time: 4450ms
chunk {0} styles.d41d8cd98f00b204e980.bundle.css (styles) 0 bytes {3} [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes {3} [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes {3} [initial] [rendered]
chunk {3} inline.22b7623ed7c5ac6f9a35.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in /home/tsonev/tmp/ng5-test1/src/$$_gendir/node_modules/@progress/kendo-angular-inputs/dist/es/slider/slider.component.ngfactory.ts (19,22): Cannot find module '../../../../kendo-angular-resize-sensor/dist/es/resize-sensor.component.ngfactory'.
ERROR in /home/tsonev/tmp/ng5-test1/src/$$_gendir/node_modules/@progress/kendo-angular-inputs/dist/es/switch/switch.component.ngfactory.ts (15,21): Cannot find module '../../../../kendo-angular-resize-sensor/dist/es/resize-sensor.component.ngfactory'.
```

## Expected behavior
The application should compile normally, as in Angular 4.x and in JIT mode.

## Minimal reproduction of the problem with instructions
1. `git clone git@github.com:tsvetomir/ng5-kendo.git`
1. `git checkout test-case`
1. `npm install`
1. `npm run build`

**Note** that [by referencing (but not including)](https://github.com/tsvetomir/ng5-kendo/blob/master/src/app/app.module.ts#L15) the NgModule in question the error disappears and the compilation succeeds.

## What is the motivation / use case for changing the behavior?
This looks like a regression in the compiler.

## Environment

<pre><code>
Angular version: 5.0.0-rc.0

Browser:
- N/A
 
For Tooling issues:
- Node version: v6.11.3
- Platform:  Linux
- Typescript: 2.4.2

Others:

- Angular CLI: 1.4.4
</code></pre>

**Comment by filipesilva** [comment]
Heya, does this happen with `@angular/cli@1.5.0-beta.2`? CLI 1.4.x does not support Angular 5.

**Comment by daddyman** [comment]
I had the same error message and updating to `@angular/cli@1.5.0-beta.2` did fix it.

**Comment by tsvetomir** [comment]
Thanks, @daddyman - upgrading `@angular/cli` to 1.5.0-beta.2 did the trick.

So not an Angular core issue for sure.

**Comment by dottodot** [comment]
`@angular/cli` 1.5.0 does resolve this issue but if you're using Universal and `LAZY_MODULE_MAP` you'll find this is now broken. 

https://github.com/angular/angular-cli/issues/7901

Unfortunately I fell into the trap of wanting to use some of the new Angular features but now I'm screwed until cli is fixed.
