### ISSUE TITLE
feat: Add clone for HttpErrorResponse

### ISSUE THREAD

**Issue by karptonite** [angular/angular#19486]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

HttpResponse and HttpRequest both have a `clone()` method to help in building interceptors. it would be helpful if HttpErrorResponse had this as well.

## What is the motivation / use case for changing the behavior?
I am building an interceptor for an API that uses [rfc7807](https://tools.ietf.org/html/rfc7807) for API errors. I'd like to have an interceptor inspect the headers for the `application/problem+json` content-type header, and, at the very least, parse the json error. a clone for HttpErrorResponse would make this trivial; it is a bit trickier without it.

**Comment by karptonite** [comment]
Incidentally, I'd be happy to submit a pull request for this if this is an acceptable feature.

**Comment by kuhnroyal** [comment]
Just implemented this on the server and now angular can't handle it xD

**Comment by karptonite** [comment]
@kuhnroyal even without clone for HttpErrorResponse, the interceptor is pretty trivial. The key part of mine looks like this:
```ts
    return next.handle(req).catch((error: HttpErrorResponse) => {
      if (!hasApiProblem(error)) {
        return Observable.throw(error);
      }

      return Observable.throw(
        // in place of clone:
        new HttpErrorResponse({
          error: { ...JSON.parse(error.error), status: error.status },
          headers: error.headers,
          status: error.status,
          statusText: error.statusText,
          url: error.url || undefined,
        }),
      );
    });
```

**Comment by kuhnroyal** [comment]
@karptonite thanks this will help

**Comment by karptonite** [comment]
@kuhnroyal FYI, the latest Angular 5 beta added automatic JSON parsing of error bodies, so if you are trying to use rfc7807, it should automatically decode the errors without the interceptor if you are on the latest beta.

That doesn't mean that there isn't a use case for cloning HttpErrorResponse, but I don't know of one anymore.

**Comment by kuhnroyal** [comment]
@karptonite Thanks for letting me know!

**Comment by marcalj** [comment]
For CORS I need to set the URL again in the error message. So now I can get a proper error message:

```ts
intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(request)
      .pipe(
        retry(3),
        catchError((error: HttpErrorResponse) => {
          if (error.error instanceof ErrorEvent) {
            // A client-side error: Retrigger
            return throwError(error.error);
          } else {
            // Sometimes URL in the Error is null
            if (!error.url) {
              // There's no clone function for HttpErrorResponse
              // @url https://github.com/angular/angular/issues/19486
              error = new HttpErrorResponse({
                error: error.error,
                headers: error.headers,
                status: error.status,
                statusText: error.statusText,
                url: error.url || request.urlWithParams || undefined,
              });
            }

            return throwError(error);
          }
        })
      );
  }
```

**Comment by petebacondarwin** [comment]
Closing as there was very little community interest in this feature, and it is possible to clone an error manually from outside the class.
