### ISSUE TITLE
Service Worker: Freshness strategy doesn't work

### ISSUE THREAD

**Issue by webmaxru** [angular/angular#19489]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Service worker fetches and caches the response, but returns failed one to the client

## Expected behavior
To fetch and return a response to the client + to cache it for offline usage

## Minimal reproduction of the problem with instructions
https://ngsw.surge.sh/
Click "Load my timeline" - it uses "Freshness" strategy - there will be network error
Click "Load favorites" - it uses "Performance" strategy - works as intended

Source: https://github.com/webmaxru/pwatter/tree/ngsw

CC: @alxhub 

## What is the motivation / use case for changing the behavior?
Fix the bug

## Environment

<pre><code>
Angular version: 5.0.0.rc.0

Browser:
- [x] Chrome (desktop) version 61
 

</code></pre>

**Comment by ivancamilov** [comment]
I think this was resolved in 396c2417d95639e858f6e11970ded09817e9e01c, can you confirm, @alxhub?

**Comment by webmaxru** [comment]
Fixed by https://github.com/angular/angular/pull/19519
