### ISSUE TITLE
angular 4 app only loads the first time in IE11

### ISSUE THREAD

**Issue by naivefun** [angular/angular#19498]
The app only bootstrap the first time and then open the same url in other tabs it stops bootstrapping. However if the dev tools is open it will start normally.

There is no js error or any complaint. Angular 4.3.1. Any thoughts?

**Comment by lazarljubenovic** [comment]
Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
