### ISSUE TITLE
Resolve: pre-fetching component data

### ISSUE THREAD

**Issue by ichent** [angular/angular#19496]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Hello, friends.
I have one problem with a resolver. This feature worked well in version 2.1.2, but doesn't work in version 4. For example, I have a route with a resolver and in this resolver I subscribe to a observable which will return a result after 5 seconds delay. After navigating to this route I navigate to this route again in 1 second, but new resolver doesn't start executing. This behavior in version 4. In version 2 it was OK. In version 4 new resolver waits while previous resolver is working.

## Expected behavior

In version 2.1.2 new resolver is executed immediately even now is active resolver.

## Minimal reproduction of the problem with instructions

Here are two live examples. This example has 3 buttons. Now you need to open the Console. Then please press the first button, in 1 second please press the second button, in 1 second please press the third button. Now you can see a difference.

In the example with angular 2.1.2 (https://plnkr.co/edit/eM7npcLL5Z7QZjhf5DPd?p=preview) in the Console you can see:
resolver phrase:  1
resolver phrase:  2
resolver phrase:  3

In the example with angular 4 (https://plnkr.co/edit/F2rHvgB8qIw3eqFXb2Al?p=preview) in the Console you can see:
resolver phrase:  1
resolver phrase:  3

## What is the motivation / use case for changing the behavior?

I want to unsubscribe current request to server and it is well to do in current active resolver.

## Environment

<pre><code>
Angular version: 4.2.5

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.1
- Platform:  Windows

Others:

</code></pre>
OS - window 7. IDE - WebStorm.

**Comment by jasonaden** [comment]
Thank you for this issue. It's unfortunately extremely old at this point and was never addressed specifically.

However, it looks like what you're trying to do is cancel/unsubscribe a current request to the server when a new request comes in that supersedes it. Good news is, this has been addressed! This was a major piece of #25740 where we converted the internals of the router to be a single Observable stream. With this change, and a few follow-up PRs afterwards, when a route changes while navigation is occurring, we will cancel and cleanup the currently running navigation.

I'm going to go ahead and close this issue as it appears the primary reason for it has been addressed. However, if the issue persists, please create a new issue with the updated issue template. In that case you can refer to this issue for more context.
