### ISSUE TITLE
ngNonBindable and ngNoForm are not in the docs

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#19497]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Searching docs for `ngNonBindable` or `ngNoForm` shows no results.

## Expected behavior

It should work.

## What is the motivation / use case for changing the behavior?

Finding it :smile:

**Comment by kapunahelewong** [comment]
@lazarljubenovic I'll find the place for `ngNonBindable` in the template driven forms doc so that will have to be a different PR. Thanks for bringing this up.

**Comment by lazarljubenovic** [comment]
@kapunahelewong Ah, sorry for the confusion -- I said _docs_ but I meant _API_: https://angular.io/api?query=ngnoform. 

Nice to have an explanation about this now! It's a common error that I found solution for on SO or an old issue. Good thing we address it now officially.

**Comment by trotyl** [comment]
@lazarljubenovic I guess part of this proposal is ability to search `Directive`s by `selector`, that could help with `ngNoForm`.

But `ngNonBindable` is not a part of any `Directive`, it's just a special <del>tag</del> attribute similar to `ng-container` or `ng-content`. Not sure how to make it better.

**Comment by lazarljubenovic** [comment]
Ah, I thought it was a directive on its own. I think we need to figure out a way to search things like `ng-container` or a`ng-content` as well, anyway. It's what developers see and what they would search for. 

Maybe at have some keywords for sections of docs which are searchable and lead to a search result for that section? But that's a separate issue/discussion anyway.

**Comment by kapunahelewong** [comment]
@jenniferfell This issue is specifically about the outstanding coverage of `ngNonBindable`. The search part works ok if there's something there to find (like `ngNoForm`), however, you might like to assess the search as you have a great eye for that.

**Comment by jenniferfell** [comment]
Current status: ngNoForm information in included API reference for ngForm. No search results for ngNonBindable. Putting on API reference backlog.

**Comment by narendrasinghrathore** [comment]
ngNonBindable not able to find angular 7 doc, is it renamed or deprecated or alternative ?

@jenniferfell @kapunahelewong

**Comment by kapunahelewong** [comment]
@narendrasinghrathore Good question. Hey, @brandonroberts, would you know the answer to @narendrasinghrathore's question?

**Comment by trotyl** [comment]
`ngNonBindable` is a defacto stable feature, there's no plan to deprecate it, just lacking of proper documentation.

**Comment by narendrasinghrathore** [comment]
@trotyl Thanks fot update. Looking forward to be mentioned in documentation  also.

Regards

**Comment by kapunahelewong** [comment]
Added section about ngNonBindable in the guide (attribute directives doc), as there wasn't an obvious place to put it in the API docs. There is already a section in the API docs (probably added after this issue was submitted) on ngNoForm. So #28577 should close this issue. I can come back and close this when that PR is merged. @lazarljubenovic if you have any more questions or ideas regarding this issue, just let me know. Thanks!

**Comment by tommueller** [comment]
I still cannot find documentation about ngNoForm, why was this closed?
