### ISSUE TITLE
AST.toString() === 'AST'?

### ISSUE THREAD

**Issue by matthewjh** [angular/angular#1949]
Is there any particular reason why subclasses of `AST` do not override the 'abstract' `AST` implementation of `toString`?

For this reason, change detection errors that use `ProtoRecord#expressionAsString`, which is derived from `bindingRecord.ast.toString()` throw unhelpful, garbage errors like this:

`Expression 'AST' has changed after it was checked. Previous value: ''. Current value: ''`

**Comment by matthewjh** [comment]
Actually, it'd probably be better to simply get the expression string from the upstream `ASTWithSource`, and pass it in to the `BindingRecord` constructor, rather than derive it (wastefully) from the AST.

Thoughts? Any reason why this wouldn't work / is a bad idea?

**Comment by matthewjh** [comment]
What do you think, @vicb?

**Comment by vicb** [comment]
I'm not sure if `AST.toString()` is really valuable here, we should probably have a visitor that could transform an AST back to an expression.

`BindingRecord` takes an `AST` so it might not be an `ASTWithSource`.

@vsavkin what do you think ?

**Comment by vsavkin** [comment]
I think the issue was fixed some time ago. @vicb can you reproduce it on master?
