### ISSUE TITLE
Documenation issue - MockBackend

### ISSUE THREAD

**Issue by Bartosz-D3V** [angular/angular#19499]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Documentation for MockBackend contains an error for unit test:
https://angular.io/api/http/testing/MockBackend

```js
it('getHeroes() while server is down', fakeAsync(() => {
       let result: String[];
       let catchedError: any;
       this.heroService.getHeroes()
           .then((heroes: String[]) => result = heroes)
           .catch((error: any) => catchedError = error);
       this.lastConnection.mockRespond(new Response(new ResponseOptions({
         status: 404,
         statusText: 'URL not Found',
       })));
       tick();
       expect(result).toBeUndefined();
       expect(catchedError).toBeDefined();
     }));
```
The above code should test the service when the backend application is not available, by providing a mock error response. Although, the test will fail as the mock response from the server is valid (it does not simulate a error response, but valid response with an error status 404).

## Expected behavior
Instead of using mockRespond it should use mockError.

```js

it('getHeroes() while server is down', fakeAsync(() => {
       let result: String[];
       let catchedError: any;
       this.heroService.getHeroes()
           .then((heroes: String[]) => result = heroes)
           .catch((error: any) => catchedError = error);
       this.lastConnection.mockError(new Response(new ResponseOptions({
         status: 404,
         statusText: 'URL not Found',
       })));
       tick();
       expect(result).toBeUndefined();
       expect(catchedError).toBeDefined();
     }));
```

## Minimal reproduction of the problem with instructions
Simply, run unit tests from Angular documentation:
https://angular.io/api/http/testing/MockBackend

## What is the motivation / use case for changing the behavior?
Documentation should provide correct examples.
It might take a while for new developers to find an issue with failing tests.

## Environment

<pre><code>
Angular version: 4 & 5

Browser:
N/A for documentation issue.
 
For Tooling issues:
N/A for documentation issue.

Others:
This issue exists in Angular 5 page as well: https://next.angular.io/api/http/testing/MockBackend
</code></pre>

**Comment by gkalpak** [comment]
Good catch, @Bartosz-D3V 👍
Would like to submit a PR with the fix?

**Comment by Bartosz-D3V** [comment]
Hi @gkalpak 

Thank you for your response. 
I opened PR with number 19509.

**Comment by alxhub** [comment]
Closing as this is obsolete (it concerns `@angular/http` which has been removed in favor of `@angular/common/http`).
