### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by crowmagnumb** [angular/angular#19502]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Upgrading to Angular 4.4 suddenly all my API calls that return null give the following ...

<pre><code>
SyntaxError: Unexpected end of JSON input SyntaxError: Unexpected end of JSON input at JSON.parse () at XMLHttpRequest.onLoad
</code></pre>

... because HttpClient in common/http now interprets null as an empty string which gives the above parse error.

## Expected behavior

To return to simply returning a null from calls rather than throwing this parse exception.

## Minimal reproduction of the problem with instructions

httpClient.get(url);
httpClient.post(url);

... where the get or post returns a null value with status=200

## What is the motivation / use case for changing the behavior?

Supposedly if all my null responses had status 204 (no-content) then it would be handled fine. BUT this turns out to be VERY complicated to achieve. I have been using this API as is for years with no issues. I am in the middle of converting two very large applications that share this same API from AngularJS to Angular. This has been an **extremely** arduous task claiming me my life for the past month. PLEASE, I beg of you go back to allowing a null response and just treat it as null and NOT as an empty string as all versions of Angular prior to 4.4.4 have done.

I am **completely** stuck now as I can't go back. We threw ourselves wholly into the Angular Material dependency and now with the latest beta-11 if I drop back to Angular 4.4.3 I get the following in trying to build menus ...

<pre><code>
Template parse errors:
There is no directive with "exportAs" set to "mdMenu" 
</code></pre>

... I upgraded to 4.4.4 which fixed that issue but now I am having the above so I can't move forward or backwards. HELP!!

## Environment

<pre><code>
Angular version: 4.4.4

Browser:
- [x] Chrome (desktop) version 60.0.3112.113 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.2.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by robwormald** [comment]
In the simplest case, you should be able to tell angular explicitly what the expected content type is, by passing it in to the request : `http.get(url, { contentType: 'string' })` 

For more complex cases, you can implement an interceptor that could handle this for you. 

If a responseType isn't passed, we default to JSON (because that's what 99% of cases are) - which is probably what's tripping you up. I believe this is the intended behavior cc @alxhub

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/19413

**Comment by crowmagnumb** [comment]
Yes @robwormald I understand that the default response type is JSON, but it has been for a long time, and I banked on it. Only it used to not throw this parse exception and now it does. So it's not because I am making an assumption I don't understand, it's the assumption I have always made and it has been fine until this release.

I also don't see what good could possibly come from trying to parse an empty string **knowing** you will get an exception. Why not say undefined or null.  I guess undefined makes better sense since "null" parses to null.

**Comment by crowmagnumb** [comment]
For now I'm updating lines 1703-1706 in node_modules/@angular/common/@angular/common/http.es5.js ...

                    body = body.replace(XSSI_PREFIX, '');
                    try {
                        body = JSON.parse(body);
                    }

... to read ...

                    body = body.replace(XSSI_PREFIX, '');
                    try {
                        if (body === '') {
                            return undefined;
                        }
                        body = JSON.parse(body);
                    }

... so I can carry on with my epic project upgrade while this is decided on or I can spare the time to look at alternatives. The latter of which I won't have for some time.

Thanks for your time, I'm sorry if I may have sounded a bit brash. I've just encountered every possible hurdle imaginable in this upgrade process and I'm really exhausted.  :(

**Comment by zlepper** [comment]
@robwormald As far as i can see it's not possible to set contentType/responseType, as the typings declaration says it has to be a value of 'json' or undefined.

Typescript error message:
```
ERROR in E:/development/goprojects/src/github.com/zlepper/physicalStore/frontend/src/app/services/lists.service.ts (33,83): Argument of type '{ headers: HttpHeaders; responseType: "string"; }' is not assignable to parameter of type '{ headers?: HttpHeaders | undefined; observe?: "body" | undefined; params?: HttpParams | undefine...'.
  Type '{ headers: HttpHeaders; responseType: "string"; }' is not assignable to type '{ headers?: HttpHeaders | undefined; observe?: "body" | undefined; params?: HttpParams | undefine...'.
    Types of property 'responseType' are incompatible.
      Type '"string"' is not assignable to type '"json" | undefined'.

```

**Comment by alxhub** [comment]
`responseType: "text"` is the incantation you're looking for.

Yes, you will get an error if your server does not respond with valid JSON, unless you specifically tell Angular not to expect JSON.

**Comment by crowmagnumb** [comment]
But null, since there isn't a standard way to represent it, I guess gets translated across the wire as an empty string. My API is returning null which gets turned into an empty string somewhere along the line. It might be via Jackson conversion (I am using Java and Spring on the backend) or I don't know. But I do know that it has been doing it for years and years and years. I have many calls that return either valid JSON or null if nothing found. Which apparently is now, and again only now with this latest release, being interpreted as an empty string and invalid JSON. For these calls, I would have to tell the api, incorrectly, that I am expecting ```responseType: "text"``` and then convert it myself after checking for an empty string. I can't be alone in this.  :) Can someone give me a valid argument as to why ```responseType: "json"``` should throw an exception if encountering an empty string?

**Comment by victornoel** [comment]
@crowmagnumb your API is broken: it should answer 204 if there is no content, adapt your client so that it can deal with by using `responseType: "text"

This is not a bug, `HttpClient` became stricter lately, I suppose to more easily detect this kind of implicit situations where you think something while something else is happening…

(but `HttpClient` is also broken because of https://github.com/angular/angular/issues/19413 because it shouldn't try to parse the body with a 204 status).

**Comment by crowmagnumb** [comment]
Thank you @alxhub!
