### ISSUE TITLE
Cannot Jasmine test components that use ng-content

### ISSUE THREAD

**Issue by jack-bliss** [angular/angular#19508]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When writing unit tests using `TestBed.createComponent` we cannot pass anything to the `ng-content` of the component.

## Expected behavior

We should be able to write comprehensive unit tests for this type of component.

## Minimal reproduction of the problem with instructions

Write any component that utilises `ng-content` and try to unit test it.

## What is the motivation / use case for changing the behavior?

Any component that uses `ng-content` should be testable - there are many different types of components that use this feature, especially UI components.

## Environment

<pre><code>
Angular version: latest

Browser:
- [x] All
 
For Tooling issues:
- Node version: latest  
- Platform:  all 

Others:

</code></pre>

**Comment by dominique-mueller** [comment]
What we do is wrapping the component to be tested in a test component. This allows us to test property and event bindings as well as content projection fairly easily.
Nevertheless, it's a bit of overhead one has to write in this case - but I'm not aware of a better solution ...

**Comment by jackbliss99** [comment]
this is the solution i came too as well. it seems to do the job well enough, and like you say it can do other stuff fairly well. what i'll probably end up doing is putting a folder in the component folder for test components and writing 2 or 3 of them depending on the context.
