### ISSUE TITLE
Angular compiler refers sourceMap in the wrong location

### ISSUE THREAD

**Issue by varghesep** [angular/angular#19503]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After the compiler is deployed and run the app in browser. You will see an error message which can't refer the ```sourcemap``` ```Users/iminar/Dev/angular/dist/packages-dist/compiler/bundles/compiler.umd.min.js.map```

![image](https://user-images.githubusercontent.com/12233474/31050487-15beb7d8-a611-11e7-86e6-cf9f0546a470.png)

## Expected behavior
Should refer in the correct folder.

## Minimal reproduction of the problem with instructions

Deploy the compiler using the command ```npm install @angular/compiler-cli @angular/platform-server --save```

## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.0
- Platform:  Windows

**Comment by mlc-mlapis** [comment]
@varghesep ... you can edit the file and manually change the line to:
```
//# sourceMappingURL=compiler.umd.min.js.map
```
as a temporary solution of the problem.

**Comment by mlc-mlapis** [comment]
@chuckjaz ... the problem was isolated on **compiler** module in 4.x line but now with 5.x line it is a general problem on each Angular module and it is necessary to manually edit each *.min.js (now it is about 28 files) file to remove a non-existed part of paths.

**Comment by JoostK** [comment]
It seems this was an issue for minified UMD bundles until Angular 6.0.0, which is where the packaging was supposedly switched to Bazel. From then onwards, minified UMD bundles no longer contain a `sourceMappingURL`. Since the reported issue is no longer applicable, I'm closing this issue.
