### ISSUE TITLE
Some routes are being redirected in https://next.angular.io

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#19505]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently some routes under https://next.angular.io are being redirected to `/docs`.

## Minimal reproduction of the problem with instructions
Go to https://next.angular.io and try to navigate to `/resources` or `/features` for example.

**Comment by trotyl** [comment]
It's by design:

> redirection of all marketing urls to /docs in archive and next mode
> - the marketing pages are irrelevant in the next and archived mode and it's more appropriate to just redirect the visitor to the actual documentation)
> - the redirection should happen via Location service (using history.replaceState) so that we don't interfere with the critical path for TTI and don't need to maintain special firebase hosting config for various environments.

See https://github.com/angular/angular/issues/18287 for more information.

**Comment by gkalpak** [comment]
@IgorMinar, @petebacondarwin, is there anything actionable here. The current behavior is by design.
(Although, I am not sure why `next.angular.io` should redirect non-docs pages; usually the info will be up-to-date. Should we change that, so that only archived versions redirect?)

**Comment by petebacondarwin** [comment]
I agree that we should not need to redirect anything on next.angular.io, IMO. Over to @IgorMinar and @juleskremer ...

**Comment by IgorMinar** [comment]
@petebacondarwin these redirects were originally setup for "archive" mode and were not intended for the "next" mode. I'm fine disabling the redirects for next, as long as we still redirect when in archive mode (v2.angular.io, v4.angular.io, ...)

**Comment by petebacondarwin** [comment]
I'll update that then.
