### ISSUE TITLE
Angular 4 does not handle multipart responses from servers

### ISSUE THREAD

**Issue by IevhenIkonnykov** [angular/angular#19507]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
It seems that Angular does not provide a convenient way to deat with multipart responses from a server. 

## Expected behavior
It would be nice if Response could return a list of parts for multipart responses, so each part could be processed separately.

## What is the motivation / use case for changing the behavior?
I have a situation when on a GET request the server returns a multipart response. ResponseContentType does not have something like "Multipart" and the response is treated as a one piece. It forces to parse it manually in order to extract bodies of each part.

## Environment

<pre><code>
Angular version: 4.1.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1
- Platform:  Windows

Others:

**Comment by alxhub** [comment]
Processing of HTTP multipart responses is out of scope for `HttpClient`, which aims to abstract common HTTP use cases.

However, you could implement this yourself via interceptors. An interceptor could receive a multipart `HttpResponse` event and split it into many separate `HttpResponse` events or some meta-event which contains an array of them all.

**Comment by Wilt** [comment]
I experimented for fun with parsing a multipart response from a server in an interceptor class and made a quick and dirty solution heavily inspired by this post on stackoverflow: https://stackoverflow.com/a/40657435/1697459
It returns the the first 'application/json' part as the repsonse body from a multipart response (`multipart/mixed` or `multipart/form-data` or `multipart/related`).
Through a map other parsers can be easily added to the class.
I will share the code here maybe it will be an inspiration for some people:

```
import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest, HttpResponse } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable({
  providedIn: 'root',
})

export class MultipartInterceptService implements HttpInterceptor {

  private parserMap = {
    'application/json': JSON.parse,
  };

  private parseMultipart(multipart: string, boundary: string): any {
    const dataArray: string[] = multipart.split(`--${boundary}`);
    dataArray.shift();
    dataArray.forEach((dataBlock) => {
      const rows = dataBlock.split(/\r?\n/).splice(1, 4);
      if (rows.length < 1) {
        return;
      }
      const headers = rows.splice(0, 2);
      const body = rows.join('');
      if (headers.length > 1) {
        const pattern = /Content-Type: ([a-z\/+]+)/g;
        const match = pattern.exec(headers[0]);
        if (match === null) {
          throw Error('Unable to find Content-Type header value');
        }
        const contentType = match[1];
        if (this.parserMap.hasOwnProperty(contentType) === true) {
          return this.parserMap[contentType](body);
        }
      }
    });
    return false;
  }

  private parseResponse(response: HttpResponse<any>): HttpResponse<any> {
    const contentTypeHeaderValue = response.headers.get('Content-Type');
    const body = response.body;
    const contentTypeArray = contentTypeHeaderValue.split(';');
    const contentType = contentTypeArray[0];
    switch (contentType) {
      case 'multipart/related':
      case 'multipart/mixed':
      case 'multipart/form-data':
        const boundary = contentTypeArray[1].split('boundary=')[1];
        const parsed = this.parseMultipart(body, boundary);
        if (parsed === false) {
          throw Error('Unable to parse multipart response');
        }
        return response.clone({ body: parsed });
      default:
        return response;
    }
  }

    // intercept request and add token
  public intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(request)
      .pipe(
        map((response: HttpResponse<any>) => {
          if (response instanceof HttpResponse) {
            return this.parseResponse(response);
          }
        }),
      );
  }
}

```

This code is quick and dirty and experimental so far from production ready, be careful when using it.

**Comment by cmaitrepierre** [comment]
This sample is exactly what i m looking for to extract not json but xml octet-stream (just add '-' to the pattern and remove the json parser as its xml. BR christopher

**Comment by Wilt** [comment]
@cmaitrepierre Nice that it worked for you. I added the dash to the pattern in my example, since it is a commonly used character inside content-types.
