### ISSUE TITLE
Null response from RouteRegistry when using Dart Router and RouterLinker

### ISSUE THREAD

**Issue by rightisleft** [angular/angular#1950]
Here's my main.dart file:
```dart
    import 'package:angular2/angular2.dart';
    import 'package:angular2/router.dart';
    
    import 'package:angular2/src/reflection/reflection.dart' show reflector;
    import 'package:angular2/src/reflection/reflection_capabilities.dart' show ReflectionCapabilities;
    
    
    @Component(
        selector: 'home'
    )
    @View(
        template: '<home><h1>I am Home</h1><a router-link="child">Go Child</a><home>',
        directives: const [RouterOutlet, RouterLink]
    )
    class Home {}
    
    //
    //
    //
    
    @Component(
      selector: 'child'
    )
    @View(
        template: '<child><h1>I am Child</h1><a router-link="home">Go Home</a><child>',
        directives: const [RouterOutlet, RouterLink]
    )
    class Child {}
    
    //
    //
    //
    
    @Component(
      selector: 'index'
    )
    @View(
      template: '''
      <router-outlet></router-outlet>
                ''',
      directives: const [RouterOutlet, RouterLink]
    )
    class Index {
      Router router;
    
      Index(Router this.router) {
        router.config({ 'path': '/child', 'component': Child, 'alias': 'child'});
        router.config({ 'path': '/', 'component': Home, 'alias': 'home'});
      }
    
    }
    
    main() {
      reflector.reflectionCapabilities = new ReflectionCapabilities();
      bootstrap(Index, routerInjectables);
    }
```

In router_link.dart i see newHref coming back as null

```dart
    onAllChangesDone() {
        if (isPresent(this._route) && isPresent(this._params)) {
          var newHref = this._router.generate(this._route, this._params);
          this._href = newHref;
          // Keeping the link on the element to support contextual menu `copy link`
    
          // and other in-browser affordances.
          print('newHref');
          print(newHref);
          DOM.setAttribute(this._domEl, "href", newHref);
        }
```

This results in an error and kills the navigation request.
```dart

String expected
    STACKTRACE:
    #0      BlinkElement.setAttribute_Callback_2 (dart:_blink:7565)
    #1      BlinkElement.setAttribute_Callback_2_ (dart:_blink:7566)
    #2      Element.setAttribute (dart:html:13673)
    #3      BrowserDomAdapter.setAttribute (package:angular2/src/dom/browser_adapter.dart:258:25)
    #4      RouterLink.onAllChangesDone (package:angular2/src/router/router_link.dart:66:23)
```

**Comment by rightisleft** [comment]
Link to example code:
https://github.com/rightisleft/angular2-dart-router-demo

**Comment by rightisleft** [comment]
Just updated to alpha.25 - still getting an error:

```
The null object does not have a method '[]'.

NoSuchMethodError: method not found: '[]'
Receiver: null
Arguments: [0]
STACKTRACE:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      Location.normalizeAbsolutely (package:angular2/src/router/location.dart:28:12)
#3      RouterLink.onAllChangesDone (package:angular2/src/router/router_link.dart:67:26)
#4      DynamicChangeDetector.callOnAllChangesDone (package:angular2/src/change_detection/dynamic_change_detector.dart:116:51)
#5      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:50:47)
#6      AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:65:12)
#7      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:51:10)
#8      AbstractChangeDetector._detectChangesInLightDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:59:12)
#9      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:49:10)
#10     AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:65:12)
#11     AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:51:10)
#12     AbstractChangeDetector.detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:41:10)
#13     LifeCycle.tick (package:angular2/src/core/life_cycle/life_cycle.dart:76:26)
#14     LifeCycle.registerWith.<anonymous closure> (package:angular2/src/core/life_cycle/life_cycle.dart:59:68)
#15     _rootRun (dart:async/zone.dart:895)
#16     _ZoneDelegate.run (dart:async/zone.dart:501)
#17     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:150:20)
#18     _CustomZone.run (dart:async/zone.dart:796)
#19     _CustomZone.runGuarded (dart:async/zone.dart:704)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:729)
#21     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#22     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#23     _ScheduleImmediateHelper._handleMutation (dart:html:42407)
```

**Comment by zoechi** [comment]
+1 Same here

**Comment by pumpk1n** [comment]
Just to be exact: it's not just Dart. Example .ts repo for the same error https://github.com/pumpk1n/angular2-router-test

**Comment by andresaraujo** [comment]
+1 Same error here

I tracked the null valuel to this function:

```dart
//route_registry.dart 

  String generate(String name, Map<String, String> params, hostComponent) {
    //TODO: implement for hierarchical routes
    var componentRecognizer = MapWrapper.get(this._rules, hostComponent);
    return isPresent(componentRecognizer)
        ? componentRecognizer.generate(name, params)
        : null;
  }
```

`componentRecognizer ` results in a null value

where:
name = "child"
params = {}
hostComponent = class Home
_rules = {Index: Instance of 'RouteRecognizer'}

**Comment by rightisleft** [comment]
Is the Router just not ready for action?

**Comment by gdi2290** [comment]
I have a fix here https://github.com/angular/angular/pull/2400

**Comment by DanWahlin** [comment]
Running into this as well with an ES6 version using alpha 26. Any idea when the fix mentioned above or another fix that's already planned will make it in? Tried adding everything I think it might look for (even though I don't think it's all required) but still get the error.

<a href="#" router-link="orders" router-params="">View Orders</a>

The specific error I get is:

TypeError: Cannot read property '0' of null
STACKTRACE:
TypeError: Cannot read property '0' of null
    at execute.Location.normalizeAbsolutely (location.es6:27)
    at execute.RouterLink.onAllChangesDone (router_link.es6:57)
    at DynamicChangeDetector.execute.DynamicChangeDetector.callOnAllChangesDone (angular2.dev.js:21069)
    at DynamicChangeDetector.execute.AbstractChangeDetector._detectChanges (angular2.dev.js:17910)
    at DynamicChangeDetector.execute.AbstractChangeDetector._detectChangesInLightDomChildren (angular2.dev.js:17920)
    at DynamicChangeDetector.execute.AbstractChangeDetector._detectChanges (angular2.dev.js:17908)
    at DynamicChangeDetector.execute.AbstractChangeDetector._detectChangesInShadowDomChildren (angular2.dev.js:17926)
    at DynamicChangeDetector.execute.AbstractChangeDetector._detectChanges (angular2.dev.js:17911)
    at DynamicChangeDetector.execute.AbstractChangeDetector._detectChangesInLightDomChildren (angular2.dev.js:17920)
    at DynamicChangeDetector.execute.AbstractChangeDetector._detectChanges (angular2.dev.js:17908)

**Comment by gdi2290** [comment]
@DanWahlin include this https://gist.github.com/gdi2290/cdf784b2ccf0d7a59ab6 and RouterOutlet seprately then using `routerDirectives`

**Comment by DanWahlin** [comment]
Thanks Patrick! I'll check that out. I didn't want to tweak anything myself but at this point I need to get it working since I'm running out of time so I appreciate the modified script.

**Comment by gdi2290** [comment]
@DanWahlin I would create a folder called `patch_angular2` that exports any directives/services etc that you need to fix so rather than

`import {RouterLink} from 'angular2/router'`;
you can attach `patch_ `
`import {RouterLink} from 'patch_angular2/router'`;
```
patch_angular2/
  router.ts
  router/
    router-link.ts
    router-outlet.ts
```

(I had to do a patch for router-outlet too)
that way when it's fixed you only need to delete the `patch_` and delete the file in your example. The router-link in the gist also fixes a memory leak with router-link

**Comment by DanWahlin** [comment]
Nice - great idea. Thanks! I haven't had a chance to try it yet, but does your router-link patch require the router-outlet patch then or can they run independently?

**Comment by gdi2290** [comment]
they're independent

**Comment by DanWahlin** [comment]
Great - thanks.

**Comment by btford** [comment]
This should have been fixed in alpha-30. See https://github.com/angular/angular/blob/f66ce096d8d908fcc0a643a14412136e74025c3d/modules/angular2/src/router/router_link.ts#L25-L33

**Comment by btford** [comment]
I'm going to close this, but please ping me on this thread if you're heaving trouble and I'll do my best to help.
