### ISSUE TITLE
Language service incorrectly reports .bind on functions as error

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#19500]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Language service reports calling `.bind` in templates as an error.

![image](https://user-images.githubusercontent.com/7661457/31047929-a7ef75b4-a613-11e7-85d8-72577daa4de2.png)

## Expected behavior

Since it work with both `ng serve` and `ng build --prod` and `ng build --prod --build-optimizer`, I guess it's a false alarm. It should not report a false positive.

## Minimal reproduction of the problem with instructions

Try binding in templates to a function.

## What is the motivation / use case for changing the behavior?

Binding directly in templates (has to be done because otherwise `this` is not what we expect it to be).

## Environment

<pre><code>
Angular version: 4.4.3

**Comment by marcellamothe** [comment]
+1

**Comment by ZachRoberts25** [comment]
+1

**Comment by JoostK** [comment]
This was fixed in #34041.
