### ISSUE TITLE
How to reload current route guards?

### ISSUE THREAD

**Issue by Humberd** [angular/angular#19504]
Let's say I have a route that has a guard `AdminGuard`, which lets me in only when I'm an admin.

But when I'm on that page and I click `Logout` the state is propagated in all the app via Observables, but I still am in a route, which I am not supposed to be in, since I've been logged out.

How to "reactivate" curent route guards?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
