### ISSUE TITLE
Some packages are missing ngsummary.js files in 5.0.0-rc.0

### ISSUE THREAD

**Issue by steveblue** [angular/angular#19518]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When updating to 5.0.0-rc.0 some @angular packages are missing properly formatted ngsummary.js files. 

## Expected behavior

Every package includes a ngsummary.js file.

## Minimal reproduction of the problem with instructions

`npm i @angular/forms@5.0.0-rc.0 @angular/animations@5.0.0-rc.0`

Observe these two packages are missing properly formatted ngsummary files.

forms is missing the file completely, while animations is formatted as JSON

node_modules/@angular/animations/animations.ngsummary.js
node_modules/@angular/animations/browser/browser.ngsummary.js
node_modules/@angular/forms/forms.ngsummary.js

## What is the motivation / use case for changing the behavior?

Without these summary files, bundling an app with Closure Compiler fails.

```
[13:52:27] LOG closure compiler started  
[13:52:30] WARN ERROR - Cannot read file node_modules/@angular/animations/animations.ngsummary.js: {1}

ERROR - Cannot read file node_modules/@angular/animations/browser/browser.ngsummary.js: {1}

ERROR - Cannot read file node_modules/@angular/forms/forms.ngsummary.js: {1}

3 error(s), 0 warning(s)
 

```

## Environment

<pre><code>
Angular version: 5.0.0-rc.0

Browser:
N/A
 
For Tooling issues:
- Node version: 6.9.0  
- Platform:  MacOS High Sierra

Others:

</code></pre>

**Comment by steveblue** [comment]
I see that AlexEagle has a post install step to generate the ngsummary files in his demo repository, but this is very confusing because it seems like packages were shipped with ngsummary in 5.0.0-beta.0 https://github.com/alexeagle/angular-bazel-example/blob/master/angular.tsconfig.json

**Comment by steveblue** [comment]
OK, I can see the ngsummary.js files are not packaged with @angular but are generated when ngc runs.

**Comment by steveblue** [comment]
OK, for a moment I thought this was user error but it does not seem to be. ngsummary.js files are not being generated for animations package and forms properly.

**Comment by tbosch** [comment]
In rc.0 we had a mistake of generating .ngsummary.js files always. However, they are now again behind a compiler flag (as they used to be in v4): `enableSummariesForJit` (see https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/api.ts#L32). 

I.e. you seem to have stale files somewhere.

In general, `.ngsummary.js` files are only needed if you do a new kind of testing which we haven't document yet, so you probably don't need them anyways.

**Comment by tbosch** [comment]
Closing for now. Please reopen if there are other issues underneath.

**Comment by steveblue** [comment]
@tbosch as of recently the ngsummary.js files were necessary to optimize with closure compiler in 5.0.0-rc.0, so the flag `enableSummariesForJit` doesn't seem appropriate. Is there a solution for bundling with closure compiler in the works? As of now closure compiler doesn't seem to understand how to interpret the packages like in 4.x.

**Comment by tbosch** [comment]
The `.ngsummary.js` files are definitely not needed to optimize with closure compiler. You might need `.ngsummary.json` files if you do incremental compilations that build ontop of each other. And you definitely need `.ngfactory.js` files as they represent the templates. The last 2 are always generated though.

@alexeagle knows more about the problem with closure compiler and `@angular` packages...

**Comment by alexeagle** [comment]
We are working with the closure compiler team to be sure the next release works with angular 5. For now I recommend cloning what the angular/closure-demo repository does.
If there is something broken wrt. the generated files, please give a specific repro.
