### ISSUE TITLE
IE bug or Ng-grid bug

### ISSUE THREAD

**Issue by kourosh2451** [angular/angular#1951]
This works in chrome but not IE ( not even in IE11)

in the cell-template  when you set style="{{ anything }}"  it does not work in IE.
when you inspect the element you get blank  style=""

in chrome you get exactly what you want.

what is really funny is that if I change the attributes names from style to xstyle 
ie does not delete it.
When I inspect the element I get xstyle="width: whatever"

it is as if ie is doing it on purpose not allowing it.

I tried  ng-style but that got super wierd. 
first of all that broke it for chrome
then it only worked sometime in ie, the databind stopped working.

    $scope.wsGrid = {
        data: 'wsList',
        multiSelect: false,
        enableColumnResize: false, 
        showFilter: false,
        afterSelectionChange: function (rowItem) {
            if (rowItem.selected)
            {
                var floorSideId = rowItem.getProperty('floorSideId');
                if (floorSideId > 0) {
                    $rootScope.gFloorSideId = floorSideId;
                    //document.location.href = '/#/worksheet';
                }
            }
        },
        columnDefs: [
            { field: 'shift', displayName: 'Shift', width: '5%' },
            { field: 'floorSide.name', displayName: 'Floor/Side', width: '10%' },
            { field: 'dateSubmittedToBC', displayName: 'Time Submitted', width: '25%' },
            { field: 'submittedByUser.name', displayName: 'Submitted By', width: '20%' },
            { field: 'naNeeded', displayName: 'NA Need', width: '10%' },
            { field: 'observersNeeded', displayName: 'Observer Need', width: '9%' },
            { displayName: 'Acuity Level',
              cellTemplate: '<div class="progress"  style="height: 100%; margin: 5px 0px 0px 5px;">' +
                                '<div class="bar bar-success" style="width: {{ row.getProperty(\'count08\') * 5 }}px"  title="{{ row.getProperty(\'count08\') }} (0.8) = {{ row.getProperty(\'total08\') }}">' +
                                    '<span class="sr-only">{{ row.getProperty(\'count08\') }}</span>' +
                                '</div>' +
                                '<div class="bar bar-warning" style="width: {{ row.getProperty(\'count10\') * 5 }}px"  title="{{ row.getProperty(\'count10\') }} (1.0) = {{ row.getProperty(\'total10\') }}">' +
                                    '<span class="sr-only">{{ row.getProperty(\'count10\') }}</span>' +
                                '</div>' +
                                '<div class="bar bar-danger" style="width: {{ row.getProperty(\'count13\') * 5 }}px"  title="{{ row.getProperty(\'count13\') }} (1.3) = {{ row.getProperty(\'total13\') }}">' +
                                    '<span class="sr-only">{{ row.getProperty(\'count13\') }}</span>' +
                                '</div>' +
                            '</div>'
            }
        ]
    };

**Comment by pkozlowski-opensource** [comment]
@kourosh2451 this is repository for Angular2, AngularJS repo is at https://github.com/angular/angular.js

But this type of general support questions should be asked using a dedicated support channel, and not opened as issues on GitHub, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
