### ISSUE TITLE
Parse5 incompatibility issue

### ISSUE THREAD

**Issue by ghego1** [angular/angular#19522]
## I'm submitting a...
<pre><code>
[ ] Regression
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When trying to render the app on the node server, however, I get this error:

```
TypeError: str.replace is not a function
    at Function.Serializer.escapeString (/Users/.../node_modules/parse5/lib/serializer/index.js:36:10)
```
The problem is generated by the fact that the renderer passes to `Serializer.escapeString` of the `parse5` lib non string values.

## Expected behavior
Only actual string values should be passed to `Serializer.escapeString`.

There are several issues open on the parse5 repository, but they have declined to fix it as they "expect correctly formed AST as an input" (https://github.com/inikulin/parse5/pull/145).

## Minimal reproduction of the problem with instructions
This problem seems to me to appear with any build of the app using ngx-translate universal.

## What is the motivation / use case for changing the behavior?
Unable to render the app server side

## Environment

<pre><code>
* angular-devkit/build-optimizer v. 0.0.21
* angular-devkit/core v. 0.0.14
* angular-devkit/schematics v. 0.0.24
* angular/animations v. 4.4.4
* angular/cli v. 1.4.3
* angular/common v. 4.4.3
* angular/compiler-cli v. 4.4.3
* angular/compiler v. 4.4.3
* angular/core v. 4.4.3
* angular/forms v. 4.4.3
* angular/http v. 4.4.3
* angular/language-service v. 4.4.3
* angular/platform-browser-dynamic v. 4.4.3
* angular/platform-browser v. 4.4.3
* angular/platform-server v. 4.4.4
* angular/router v. 4.4.3
* angular/tsc-wrapped v. 4.4.3
* ngtools/json-schema v. 1.1.0
* ngtools/webpack v. 1.7.1
* ngx-translate/core v. 8.0.0
* ngx-translate/http-loader v. 2.0.0
* ngx-universal/translate-loader v. 4.0.1
* webpack-concat-plugin v. 1.4.0
* webpack-dev-middleware v. 1.12.0
* webpack-dev-server v. 2.7.1
* webpack-merge v. 4.1.0
* webpack-sources v. 1.0.1
* webpack v. 3.5.6
 
- Node version: 8.6.0
- Platform: Mac

HTTP server: express + @nguniversal/express-engine 5.0.0.beta1
</code></pre>

**Comment by Toxicable** [comment]
In v5 we've moved over to use Domino instead of parse5.
Would you be able to check if this is an issue on rc.0 ?
