### ISSUE TITLE
How to implement efficient infinite scroll using Angular?

### ISSUE THREAD

**Issue by anil789** [angular/angular#1952]
We have been designing a system based on Angular 2.0 and going thru various use-cases. One  common use-case is infinite scroll of a large collection. At a high level we understand how it could be done in Angular 2.0. But things get complicated when we bring data driven rendering into picture (data to view mapping complicated enough to justify the use of imperative logic ). 

It makes us nervous when we hear - "we should not be touching the DOM  when using Angular". In this case, it means - create super-set template and pre-process  data to give the desired effect. Implementing imperative logic in the data-world makes perfect sense until you notice that it leads to a complicated state machine of auxiliary data to give the desired effect to view. One example of auxiliary data is - additional variables required to "show-hide" elements of super-set template. Does it not become more convoluted than DOM manipulation within rendering logic of a View?

Is there another construct of Angular or approach that we should be looking for this use case?

**Comment by gdi2290** [comment]
you're looking for this https://github.com/angular/angular/issues/1693

**Comment by mhevery** [comment]
duplicate
