### ISSUE TITLE
HttpClient 'Http failure during parsing' error for empty or string response in IE

### ISSUE THREAD

**Issue by damirkusar** [angular/angular#19529]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Request throws an error when trying to parse a response of "ok" with no content or simple string returning as body content. 

-> Checked this issue as well. 

## Expected behavior

No error should be thrown for a response of "ok"

## Minimal reproduction of the problem with instructions

`message:"Http failure during parsing for https://run.plnkr.co/preview/cj8bkmsaj000b3b5s7eo3q9ww/mockjson.json"
name: "HttpErrorResponse"
ok: false
status:200
statusText:"OK"`

[https://embed.plnkr.co/ZnJ19zlEjRtmClXUNQbe/](https://embed.plnkr.co/ZnJ19zlEjRtmClXUNQbe/)

## Environment

Angular version: 5.0.0-rc.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Platform:  Windows
- Backend:  .net Core API

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/18680

**Comment by damirkusar** [comment]
Hmm.. thanks..

**Comment by damirkusar** [comment]
Duplication of https://github.com/angular/angular/issues/18680
