### ISSUE TITLE
Angular 4 application is not instanceable multiple times on the same page

### ISSUE THREAD

**Issue by khalid-elabbadi** [angular/angular#19523]
I need to create an angular application that can be instanceated many times on the same html page with parameters. To be more clear, i need to be able to do something like this on the index.html page:

```
<app-root name="rebert" age="25"></app-root>
<app-root name="jean" age="25"></app-root>
<app-root name="carry" age="17"></app-root>
```
that was possible in angularjs. why this beatiful fonctionnality has been removed from angular except if there is something i miss;

This functionnality will help me using angular apps inside liferay 6.2

Thank you

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/1858
https://github.com/angular/angular/issues/7136

**Comment by ocombe** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
