### ISSUE TITLE
Support of override ngsw-worker.js path to ngsw.json

### ISSUE THREAD

**Issue by Delagen** [angular/angular#19524]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Hardcoded as `/ngsw.json?....`

## Expected behavior
Way to override it.

## What is the motivation / use case for changing the behavior?
My app hosted as subdirectory of site, so no way to place ngsw.json to root.
I manually edit file to remove `/` from code.

**Comment by glebcha** [comment]
Proposal - pass as register param.

**Comment by alxhub** [comment]
Fixed!

**Comment by AkiTechiesEra** [comment]
ServiceWorkerModule.register('./ngsw-worker.js', {enabled: environment.production})
  
I simply made period before "/ngsw-worker.js" and everything seems to work.

**Comment by AkiTechiesEra** [comment]
I'm still facing this issue in local production deployment
