### ISSUE TITLE
Lazy Loaded Module does not work with lazy routing

### ISSUE THREAD

**Issue by Jonathan002** [angular/angular#19520]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

**Problem: I have a lazy module that needs to use the app popup router (secondary named outlet) in my app.component.html.**

## Expected behavior

**Lazy module can use the popup router in my app.component.html.**

## Minimal reproduction of the problem with instructions

I have the following in my app component template:

src/app/app.component.html

```html
    <!-- Primary Router -->
    <router-outlet id="main-router"></router-outlet>
    
    <!-- Popup Router -->
    <router-outlet name="app-popup"></router-outlet> <!-- <====== -->
```

### My App Module and it's routes:

/src/app/app-routing.module.ts

```typescript
const appRoutes: Routes = [
      { path: 'lazy',  loadChildren: 'app/lazy/lazy.module#LazyModule' }, // <--------
    ];
    @NgModule({
      imports: [
        CommonModule,
        RouterModule.forRoot(appRoutes),
      ],
      exports: [
        RouterModule
      ],
    })
    export class AppRoutingModule { }
```

/src/app/app.module.ts
```typescript
    @NgModule({
      declarations: [AppComponent],
      imports: [
        BrowserModule,
        AppRoutingModule
      ],
      bootstrap: [AppComponent]
    })
    export class AppModule {}
```

### My Lazy Module and it's routes:

/src/app/lazy/lazy.module.ts
```typescript
    const lazyRoutes: Routes = [
      { path: 'lazy-popup', outlet: 'app-popup', component: LazyPopupComponent },
      { path: '', component: LazyComponent }
    ];
    @NgModule({
      imports: [
        RouterModule.forChild(lazyRoutes)
      ],
      exports: [
          RouterModule
      ]
    })
    export class LazyRoutingModule {}
```

/src/app/lazy/lazy.module.ts
```typescript
    @NgModule({
      imports: [
        CommonModule,
        AppSharedModule,
        LazyRoutingModule
      ],
      declarations: [
        LazyComponent,
        LazyPopupComponent
      ],
      exports: [
        LazyPopupComponent,
        LazyRoutingModule,
      ]
    })
    export class LazyModule {}
```
### How I navigate:
I navigate to the route like this:

/src/app/lazy/lazy.component.html

```html
    <button [routerLink]=" [ '', { outlets: { 'app-popup': ['lazy-popup'] } }] "></button>
```

***
I can't seem to get it to work as I get this error:
```javascript
    core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Cannot match 
    any routes. URL Segment: 'lazy-popup'.
```
Note that this works perfectly though if I import the LazyModule in AppModule below:
```typescript
    @NgModule({
      declarations: [AppComponent],
      imports: [
        BrowserModule,
        AppRoutingModule,
        LazyModule // <-- The routes work now.. But.. this should be lazy.. : (
      ],
      bootstrap: [AppComponent]
    })
    export class AppModule {}
```
Although this defeats the purpose of it being a lazy loaded module. So how can I get the lazy loaded module use the secondary router-outlet named 'app-popup' that exist in the app components html template?

## What is the motivation / use case for changing the behavior?

Getting a lazy module to use a single app wide secondary outlet as a popup.

## Environment
Angular-Cli project

<pre><code>
Angular version: 4.2.4

Browser:
- [ x ] Chrome (desktop) version 61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Mac 

Others:

</code></pre>

**Comment by codart1** [comment]
This issue is really anoying

**Comment by royling** [comment]
same with #10981

**Comment by mlc-mlapis** [comment]
@Jonathan002 ... use the equivalent solution like described here by using `createEmbeddedView` https://stackblitz.com/edit/adv-ng-left-nav

**Comment by jasonaden** [comment]
Closing as a duplicate as well as needing a reproduction (use Plunker or Stackblitz). If you would would like to create a repro that's different than #10981 and not solved by the referenced stackblitz above, please create a new issue.
