### ISSUE TITLE
Failed at the start script 'ng serve' on windows 7 64

### ISSUE THREAD

**Issue by sanjayrathore144** [angular/angular#19528]
i am using node v6.11.3 and npm v3.10.10 on windows 7 64 bit
when i create a new project using angular cli it finishes successfully but when trying to run it using ng serve it show me following error

Failed at the start script 'ng serve'

a complete log of error from npm-debug is

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle testme@0.0.0prestart: testme@0.0.0
6 silly lifecycle testme@0.0.0prestart: no script for prestart, continuing
7 info lifecycle testme@0.0.0start: testme@0.0.0
8 verbose lifecycle testme@0.0.0start: unsafe-perm in lifecycle true
9 verbose lifecycle testme@0.0.0start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\angproducts\testme\node_modules.bin;C:\Program Files\Git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\HPE\LoadRunner\strawberry-perl\perl\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\sanjaylp\AppData\Local\Android\sdk\platform-tools;C:\Program Files\Git\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\sanjaylp\AppData\Roaming\npm
10 verbose lifecycle testme@0.0.0start: CWD: D:\angproducts\testme
11 silly lifecycle testme@0.0.0start: Args: [ '/d /s /c', 'ng serve' ]
12 silly lifecycle testme@0.0.0start: Returned: code: 1 signal: null
13 info lifecycle testme@0.0.0~start: Failed to exec start script
14 verbose stack Error: testme@0.0.0 start: ng serve
14 verbose stack Exit status 1
14 verbose stack at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack at emitTwo (events.js:106:13)
14 verbose stack at EventEmitter.emit (events.js:191:7)
14 verbose stack at ChildProcess. (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack at emitTwo (events.js:106:13)
14 verbose stack at ChildProcess.emit (events.js:191:7)
14 verbose stack at maybeClose (internal/child_process.js:920:16)
14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid testme@0.0.0
16 verbose cwd D:\angproducts\testme
17 error Windows_NT 6.1.7601
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
19 error node v6.11.3
20 error npm v3.10.10
21 error code ELIFECYCLE
22 error testme@0.0.0 start: ng serve
22 error Exit status 1
23 error Failed at the testme@0.0.0 start script 'ng serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the testme package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error ng serve
23 error You can get information on how to open an issue for this project with:
23 error npm bugs testme
23 error Or if that isn't available, you can get their info via:
23 error npm owner ls testme
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

How can the CLI team reproduce the problem?

supporting information:

npm -v prints: v3.10.10
node -v prints: v6.11.3
npm config get registry prints: https://registry.npmjs.org
Windows, OS X/macOS, or Linux?: windows
I don't use a proxy, but have limited or unreliable internet access.
Container:
I develop using Windows 7 64.

**Comment by gkalpak** [comment]
This repo is about the core framework packages. Can you please reopen the issue on https://github.com/angular/angular-cli?
