### ISSUE TITLE
doc: Broken link to master styles in Tour of Heroes tutorial

### ISSUE THREAD

**Issue by jcttrll** [angular/angular#19530]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In the Tour of Heroes tutorial, on page/section https://angular.io/tutorial/toh-pt5#global-application-styles, the link to the master stylesheet ("Ensure that the file contains the master styles provided here.") is broken. It points to https://raw.githubusercontent.com/angular/angular/master/aio/tools/examples/shared/boilerplate/src/styles.css, resulting in a 404.

## Expected behavior

The link should be to the correct URL for the stylesheet:

https://raw.githubusercontent.com/angular/angular/master/aio/tools/examples/shared/boilerplate/common/src/styles.css

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 58.0.3029.110 (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kapunahelewong** [comment]
Thanks for pointing this out, @jcttrll :)
