### ISSUE TITLE
DomEventsPlugin uses Zone directly, errors with ngZone: 'noop'

### ISSUE THREAD

**Issue by robwormald** [angular/angular#19534]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using the new `NoopZone` option to run Angular without Zone.js included, setting up an event handler `<button (click)="doStuff()">` throws with the error:
```
core.umd.js:4412 Uncaught (in promise) ReferenceError: Zone is not defined
    at Function.NgZone.isInAngularZone (VM752 core.umd.js:4412)
    at DomEventsPlugin.addEventListener (VM750 platform-browser.umd.js:3289)
    at EventManager.addEventListener (VM750 platform-browser.umd.js:2366)
    at DefaultDomRenderer2.listen (VM750 platform-browser.umd.js:3020)
    at DebugRenderer2.listen (VM752 core.umd.js:15174)
    at listenToElementOutputs (VM752 core.umd.js:10342)
    at createViewNodes (VM752 core.umd.js:13473)
    at callViewAction (VM752 core.umd.js:13942)
    at execComponentViewsAction (VM752 core.umd.js:13851)
    at createViewNodes (VM752 core.umd.js:13528)
```

Likely root cause tracks back to https://github.com/angular/angular/blob/master/packages/platform-browser/src/dom/events/dom_events.ts#L122-L131

## Expected behavior
ZoneJS should not be required anywhere when using the `'noop'` Zone option.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/R1aTzDtWmNIvNAyaEVp7?p=preview
Add / remove the `<button (click)="doStuff()">` to see the change in behavior.

## Environment
Angular version: 5.x.x

**Comment by JiaLiPassion** [comment]
@robwormald , the error because without load `Zone.js`, `__symbol__` will just return what is passed in. I will fix this one.

**Comment by mhevery** [comment]
@JiaLiPassion  thank you.

**Comment by SanderElias** [comment]
@JiaLiPassion I'm running into this too, do you need help on this?

**Comment by JiaLiPassion** [comment]
@SanderElias , I have posted a PR, thank you very much!

**Comment by SanderElias** [comment]
@JiaLiPassion I noticed just after putting up my message! hence the edit I did! :-D
Thank you for your PR!

**Comment by trotyl** [comment]
Could this be closed? The PR has been merged already.

**Comment by gkalpak** [comment]
Has this been released? Shouldn't we update the min `zone.js` version in `package.json`?

https://github.com/angular/angular/blob/3997d9780615dc323eb357bf7077d0264a1c35e9/packages/core/package.json#L16

**Comment by trotyl** [comment]
@gkalpak Not released yet, but changed to `platform-browser-builds` could confirm the fix: https://plnkr.co/edit/5N3DusGHieqkDR2lKouF?p=preview

**Comment by gkalpak** [comment]
Thx for confirming. I am not questioning the fix, though. My second question was more about whether we need to update the min version is `package.json` (once it has been released), since essentially Angular will require that latest version for `DomEventsPlugin` to work correctly with `noop` ngZone. So saying that it requires `0.8.4` or later is kind of inaccurate.
