### ISSUE TITLE
Proposal: Use Polymer project for Material Design.

### ISSUE THREAD

**Issue by mfrancis107** [angular/angular#1953]
Would it be more beneficial to just use the Material Design web components from the polymer project instead of rewriting Angular Material? If additional functionality is needed we could easily wrap the polymer components in angular components.

**Comment by jonrimmer** [comment]
Personally, I find the Angular 1 Material Design library to be a great source of inspiration and instruction on how to write high-quality components. Having something similar for Angular 2 would be very helpful. Plus being able to use them without taking a dependency on Polymer is a plus.

**Comment by kpko** [comment]
Hi, 

I thought about the exact same thing a few days ago. Angular 2 does work with web components, right? Doesn't polymer provide web components? And isn't the material design library of polymer just a collection of web components? I'm not a polymer expert, but this came into my mind, too.

Does Angular 2 work out of the box with polymer web components?

**Comment by vicb** [comment]
I think one of the problem is that Polymer uses web components... 

When web components are not natively available  (most browsers) Polymer do use a shim which slow things down too much (as of polymer 0.5, not sure about 0.8+).

Angular2 should be faster when web components are not available (it does not use the JS shim).  

> Does Angular 2 work out of the box with polymer web components?

I think we have some remaining opened issues on ng2 and on zone.js but it should short-term.

This is not a comprehensive answer, @jelbourn might have more ?

**Comment by nomack84** [comment]
@vicb Polymer was almost completely rewrited from 0.5 to 0.8/0.9, focusing on performance and the stats are incrediblely promising. For browser which don't natively support WC they made a shim of `Shadow Dom` they call `Shady Dom` which is much more performante than what they have at 0.5. Also, the polyfill they use now is way shorter in size.

**Comment by mhevery** [comment]
There are technical reasons why Angular Material will always perform faster and more predictable then Polymer. One can always use Polymer since WebComponents work in Angular.

**Comment by vicb** [comment]
> One can always use Polymer since WebComponents work in Angular.

@mhevery is this true even when WebComponents are not available natively ? (thinking about polyfill interactions)

**Comment by QuantumInformation** [comment]
+1 for Polymer and angular 2 sharing the same components.

**Comment by naomiblack** [comment]
Naomi from the Angular Material project here. We think it's useful for folks to have the option of both libraries. We're also developing Angular Material in Angular 2 for selfish reasons: it's an excellent proving ground for many of our internal assumptions about the new Angular 2 codebase. 

As a developer, you should feel free to use whichever component library best works for your app.

**Comment by QuantumInformation** [comment]
@naomiblack thanks for joining the discussion:) 

Would it be possible to share the css between both polymer and ng-mat 2?
