### ISSUE TITLE
Lazy loaded loadChildrens shouldn't provided with the same token as the Routes

### ISSUE THREAD

**Issue by tamasmonus-cas** [angular/angular#19545]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
As I could see, now the compiler finds the loadChildrens (the lazily loaded module's paths) via using the `@angular/router's` `ROUTES` InjectionToken. Thus, you can lazy load modules without adding them (via the token or using the `provideRoutes` method) the the global `ROUTES`.

I don't think that it is really a good idea, now I have several modules that I have to load lazily, but I have to load them by myself, so I wrote my own ModuleLoader (like the Router does), but these modules are not connected to any route, thus I didn't want to add the to my config. However, because the compiler uses the same Token I have to and to make sure they won't match to any route I have to make routes with a `matcher` that will always return a zero match. This feels like a really hacky solution.

## Expected behavior
I think it would be much better if the compiler would use a seaparate Token to find the loadChildren, and the RouterModule can provide them from the config it got.

## Environment

<pre><code>
Angular version: 4.3.0

</code></pre>

## Relevant issue
#18786

**Comment by ocombe** [comment]
Hello, this is not a bug. Could you change the type to feature instead ?
Also please provide the correct Angular version, 1.3.0 does not exist, this is most likely the cli version

**Comment by tamasmonus-cas** [comment]
I've just edited the issue. Sorry about the wrong version number.

**Comment by jasonaden** [comment]
Please provide some examples showing what you're trying to do that won't work without this feature. Show how you achieve the same result now, and how you would like to be able to do it to make things simpler. That will help in designing this feature.
