### ISSUE TITLE
AOT: Cannot determine the module for class <...>Component

### ISSUE THREAD

**Issue by actra-gschuster** [angular/angular#19544]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior
Compilation in prod / AOT mode fails with the given error message for EVERY component in my project, even the bootstrapped ApplicationComponent.
All mentioned components are declared in their corresponding modules.
JIT works without any errors / warnings / problems, AOT used to work in earlier versions.
<pre><code>ERROR in Error: Cannot determine the module for class LayoutComponent in C:/path/to/src/code/layout/components/layout/layout.component.ts! Add LayoutComponent to the NgModule to fix it.
Cannot determine the module for class ThemeComponent in C:/path/to/src/code/theme/components/theme/theme.component.ts! Add ThemeComponent to the NgModule to fix it.
Cannot determine the module for class ApplicationComponent in C:/path/to/src/code/application/components/application/application.component.ts! Add ApplicationComponent to the NgModule to fix it.
Cannot determine the module for class ErrorPageComponent in C:/path/to/src/code/application/components/error-page/error-page.component.ts! Add ErrorPageComponent to the NgModule to fix it.
Cannot determine the module for class TranslationDirective in C:/path/to/src/code/application/components/translations/translation.directive.ts! Add TranslationDirective to the NgModule to fix it.
Cannot determine the module for class TranslationsComponent in C:/path/to/src/code/application/components/translations/translations.component.ts! Add TranslationsComponent to the NgModule to fix it.
Cannot determine the module for class DashboardComponent in C:/path/to/src/code/m-m/components/dashboard/dashboard.component.ts! Add DashboardComponent to the NgModule to fix it.
    at syntaxError (C:\path\to\node_modules\@angular\compiler\bundles\compiler.umd.js:503:34)
    at validateAnalyzedModules (C:\path\to\node_modules\@angular\compiler\bundles\compiler.umd.js:29435:15)
    at analyzeAndValidateNgModules (C:\path\to\node_modules\@angular\compiler\bundles\compiler.umd.js:29424:12)
    at AotCompiler.analyzeModulesAsync (C:\path\to\node_modules\@angular\compiler\bundles\compiler.umd.js:28763:46)
    at CodeGenerator.codegen (C:\path\to\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\path\to\node_modules\@angular\compiler-cli\src\ngtools_api.js:70:30)
    at _donePromise.Promise.resolve.then (C:\path\to\node_modules\@ngtools\webpack\src\plugin.js:426:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3</code></pre>

## Expected behavior
Compile the app.

## Environment

<pre><code>
angular: 5.0.0-rc.0
angular-cli: 1.5.0-beta.3
ngtools/webpack: 1.8.0-beta.2
Node: 8.5.0
NPM: 5.3.0
Webpack: 3.6.0
Windows 10
</code></pre>

**Comment by ocombe** [comment]
Hello, we need a way to reproduce the issue, either with a plunker or your code.
Thanks

**Comment by actra-gschuster** [comment]
Sorry for the late reply, been busy all weekend long.
After stripping the app to only contain the app module and component I still receive the error with the latest RC1.
The exact same code - really the same, line by line, char by char - builds fine with Beta.3 through Beta.7.
I don't get it how to setup a plunker, sorry, but I could mail you the complete project including webpack configs etc., just can't publish it in whole as it's a clients project.

src/main.ts:
```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { ApplicationModule } from './code/application/application.module';
import { environment } from './environments/environment';

if(environment.production) {
    enableProdMode();
}

platformBrowserDynamic().bootstrapModule(ApplicationModule);
```


src/code/application/application.module.ts:
```
import {
    Injectable,
    NgModule
} from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';

import {
    ApplicationComponent
} from './components/index';

@NgModule({
    bootstrap:    [
        ApplicationComponent
    ],
    declarations: [
        ApplicationComponent
    ],
    exports:      [
        RouterModule
    ],
    imports:      [
        BrowserModule,
        RouterModule.forRoot([])
    ]
})
@Injectable()
export class ApplicationModule {
}
```


src/code/application/components/application/application.component.ts:
```
import {
    Component,
    ViewEncapsulation
} from '@angular/core';

@Component({
    selector:      'mm-application-application',
    encapsulation: ViewEncapsulation.Emulated,
    styleUrls:     ['./styles/application.scss'],
    templateUrl:   './templates/application.template.html'
})
export class ApplicationComponent {
}
```


src/tsconfig.app.json:
```
{
    "extends":         "../tsconfig.json",
    "compilerOptions": {
        "outDir":  "../out-tsc/app",
        "module":  "es2015",
        "baseUrl": "",
        "types":   [
            "angular",
            "core-js",
            "hammerjs",
            "lodash-es",
            "moment",
            "moment-timezone",
            "node",
            "redux",
            "redux-immutable",
            "redux-logger",
            "redux-persist-transform-filter",
            "rx",
            "rx-angular",
            "uuid",
            "web-animations-js"
        ]
    },
    "exclude":         [
        "test.ts",
        "**/*.spec.ts"
    ]
}
```


tsconfig.json:
```
{
    "compileOnSave":   false,
    "compilerOptions": {
        "outDir":                 "./dist/out-tsc",
        "baseUrl":                "src",
        "sourceMap":              true,
        "declaration":            false,
        "moduleResolution":       "node",
        "emitDecoratorMetadata":  true,
        "experimentalDecorators": true,
        "target":                 "es5",
        "typeRoots":              [
            "node_modules/@types"
        ],
        "types":                  [
            "angular",
            "core-js",
            "hammerjs",
            "jasmine",
            "lodash-es",
            "moment",
            "moment-timezone",
            "node",
            "redux",
            "redux-immutable",
            "redux-logger",
            "redux-persist-transform-filter",
            "rx",
            "rx-angular",
            "source-map",
            "uglify-js",
            "uuid",
            "webpack",
            "web-animations-js"
        ],
        "lib":                    [
            "es2016",
            "dom"
        ]
    }
}
```

**Comment by actra-gschuster** [comment]
I tried to track it down further, latest observations are that after upgrading `@angular/cli` to 1.5.0-beta.4 and `@ngtools/webpack` to 1.8.0-beta.4 the error changes.

5.0.0-rc.0 and 5.0.0-rc.1: Module not found: Error: Can't resolve './$$_gendir/code/application/application.module.ngfactory'
5.0.0-beta.7: No provider for NgForm error (known, see issue)
5.0.0-beta.6: Application compiles as expected

The apps code wasn't changed (not even a char) between the version switches, I can go back and forth and reproduce the error.
Will debug the app now as in the past all "module not found" errors where some odd things that I could resolve myself, albeit I'm wondering why it works in beta.6 but not rc.0/rc.1.

As far as I can tell by now, I think it's something inside `@angular/cli` or `@ngtools/webpack`, not `@angular/*` itself, so feel free to close the issue.
I'll keep you posted if there are any new observations when debugging.

**Comment by mrunks** [comment]
I too am experiencing this error at work. 

We are using the following:
angular/cli  1.50
Node 8.9.0
Windows 10 x64

**Comment by chuckjaz** [comment]
This should be supported but it appears the compiler is not handling the presence of the redundant `@Injectable()` on the module. A work around for this, until I submit a fix, is to remove `@Injectable()` from module classes. It might also be a good idea to remove the `@Injectable()` anywhere it is not the only Angular decorator.

**Comment by lslocum** [comment]
I am having these same issues with my app. I am not using @Injectable in my module. The component is imported, declared, and exported, but it is still throwing the error. I am trying to run ng build --prod, and not an AOT build. This is happening on several components in different modules.

```javascript
import { CUSTOM_ELEMENTS_SCHEMA, NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { DummyComponent } from 'SystemFiles/dummy.component';
// ... other imports

@NgModule({
  imports: [
    DummyRoutingModule,
    // ... other modules
  ],
  declarations: [
    DummyComponent,
    // ... other componets
  ],
  exports: [DummyComponent],
  providers: [
    DummyService,
    // ... other services
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA]
})
export class DummyModule {}
```

**Comment by anandmurali** [comment]
Make sure the import path case matches with the actual file path case. I got the same error, for my MyUserComponent class shown below. Note the case of the import path (all the letters are in lower case).

`import { MyUserComponent } from './user/myusercomponent.component';`

The actual file name of MyUserComponent was

> myUserComponent.component.ts (note that U and C are in upper case)

Once I changed the import statement to the following
`import { MyUserComponent } from './user/myUserComponent.component';`
the error disappeared.

**Comment by lslocum** [comment]
@anandmurali thanks for the tip, but this is not my issue. I am using a barrel file to import from so my paths are irrelevant, and I used the autocomplete feature in VS Code to make sure the paths are correct.

**Comment by HarshaVardhanPVK** [comment]
@lslocum Did you found any fix for this issue?

**Comment by lslocum** [comment]
@HarshaVardhanPVK I was able to get a production APT build to work, but I don't remember how I resolved the issue. Sorry I couldn't be more of a help.

**Comment by roopsundar** [comment]
Yes, path is case sensitive.. I changed and it worked fine

**Comment by fredrik-lundin** [comment]
@anandmurali thank you! A case error in the path was causing my error too.

Should this be considered a bug or is it by design?

**Comment by nixallover** [comment]
@anandmurali Thank you so much! You saved me from some serious frustration.

**Comment by ssuperczynski** [comment]
If you use https://github.com/angular/angular-cli/wiki/stories-create-library to create a library, don't forget to add your project name to the `ng build` command. For example my case:

was: `ng build --prod`
should have been: `ng build <project-name>`

**Comment by donprecious** [comment]
It can be really challenging if you encounter such errors, 
1. ensure that your component where imported in your module, the path is case sensitive, eg ./Layouts is not the same as  ./layout
2. if any class imported a component ensure that the path is correct, like that of case sensitivity

this problem could be caused by some intellisense tool that automatically imports component

**Comment by fabricejumarie** [comment]
I confirm, I solved the same issue by updating component path (previous path was ./user and has been updated to ./User).
So be sure that the path on Build server be identical to the path mentionned in NgModule.

**Comment by hyzx86** [comment]
This problem may be due to the existence of components with the same name in different path.

**Comment by D252874** [comment]
@anandmurali thanks I thought it had nothing to do with my casing but it did but the error is not helpful here if the casing is good for the component but for example not for the routing module for me it still gives that my component had the error.

**Comment by rameshbas** [comment]
Case in the filename import was the culprit. Thanks Murali for pointing out

**Comment by ayoubleb** [comment]
Different components with the same name will cause this issue as well, if not the casing .

**Comment by jitsmaster** [comment]
My case was different casing from several different import paths. Make the casing consistent will fix the issue.

**Comment by joelmeaders** [comment]
I had this issue but with a pipe which had an http service in the constructor. The module that declares my pipes has 12 pipes.

For whatever reason moving the failing pipe to the top of the declarations list fixed my production build. If I move the pipe to the last declaration again the build fails. Angular 8.2.1
