### ISSUE TITLE
The templateUrl property of @View don't work in nw.js(nor in Electron)

### ISSUE THREAD

**Issue by C4Grey** [angular/angular#1954]
A component with template specified via built-in string(using "template" property) works fine, but when I've tried to use "templateUrl", got an error: Failed to load the template "TestComponent". Template is defined in such way: `@View({templateUrl: 'templates/test.html'})`, also tried `@View({templateUrl: './templates/test.html'})` with a same result.
But when I've created a local http server and has specified a template using a http scheme, it started to work: `@View({templateUrl: 'http://localhost:5555/templates/test.html'})`.
Is this a problem within the nw.js/Electron, and I must rely on the such workaround, or it is a bug in the Angular?

**Comment by avstudios** [comment]
I'm using Angular Dart but version 1. And I had similar problem with the nw.js/Electron. I found solution here:
http://stackoverflow.com/questions/28704577/angular-dart-relative-url-resolution-requires-a-valid-base-uri
Please let me know if that will work for you. I would like to switch to Angular 2 but not sure if it will be ready for production in 2 months.

**Comment by C4Grey** [comment]
Found a problem, it was in the [status code check](https://github.com/angular/angular/blob/bb2eda2d151092cdd318cbdbb6b22edc1dd39896/modules/angular2/src/services/xhr_impl.es6#L15).
At first, XHR for a local file in the nw.js will alway return a status code 0, so the dirty way will be to add such condition to this check. But it seems a better way to create a NodeJS-specfic implementation that will be work with the file system.
At second, this check looks a quite strange since it not takes into account the redirect codes(301 and 302) and the 304 status code.

**Comment by mhevery** [comment]
Should be a trivial fix, can you submit a PR?

**Comment by mhevery** [comment]
@naomiblack This is a blocker for Ionic, I have upped the priority and added it to the hot-list.

**Comment by tlancina** [comment]
Thanks! It looks like the [PR](https://github.com/angular/angular/pull/2238) @gdi2290 submitted for this issue already is just waiting on tests.  I'll take a look at it tomorrow.

**Comment by mhevery** [comment]
dup of #2219 (as the PR closes that one.)
