### ISSUE TITLE
Redirection and closing route outlet doesn't work

### ISSUE THREAD

**Issue by picheli20** [angular/angular#19547]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I've a route outlet opened like: `/home(right:account)`

When I try to do a redirection from inside the `account` component to the `/promotions` page and close the route outlet, like this:
```html
<a [routerLink]="['/promotion', { outlets: { right: null } }]">Take me to Promotion</a>
```

I get redirected to the `/promotions(right:account)` page but the account still open

## Expected behavior

It should close the modal outlets and redirect to `/promotions` page from the `account` component

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/PnjMGKsKxFzRQYiK3a7V?p=preview

## What is the motivation / use case for changing the behavior?

If you are using the route outlet, f.e. for modals, you will probably, at some point, need to redirect to another page and close the modal at the same time inside the modal component

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [X] Chrome (desktop) version 60.0.3112.113
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  macOs Sierra

Others:

</code></pre>

**Comment by picheli20** [comment]
I've done a "workaround" redirecting to home page and calling each step at the time.
```js
  justGo (path) {
    this.router.navigate(['/']);
    [].map.call(arguments, (arg, index) => {
      setTimeout(() => this.router.navigate(arg), 50 * (index + 1));
    });
  }
```

And I use like that:

```html
(click)="this.localeService.justGo(['/promotions'], ['', { outlets: { modal: [...] } }])"
```

it's better than reload the entire application

**Comment by cgatian** [comment]
@picheli20 I think this issue is related to #13523

**Comment by picheli20** [comment]
@cgatian yeah true, didn't found this issue! Thanks, I'll be closing this and leave a comment there 😃

**Comment by cgatian** [comment]
@picheli20 Perhaps add your workaround to the conversation
