### ISSUE TITLE
form.reset should also reset the Submitted status of the form

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#19557]
## I'm submitting a...
<pre><code>[x ] Feature request</code></pre>

## Current behavior

Resetting a form using form.reset, doesn't reset the `Submitted` status of the form.

As mentioned by @willshowell at https://github.com/angular/material2/issues/4190#issuecomment-305222426 and https://github.com/angular/material2/issues/4190#issuecomment-311488176
the error state of the form is calculated like this:

`isInvalid && (isTouched || isSubmitted)`

But since the form.reset doesn't reset the Submitted status, the form controls keeps displaying the error classes.

## Expected behavior
form.reset should also reset the `Submitted `status.

**Comment by kara** [comment]
I think what you're looking for is `resetForm()` on the directive itself. `reset()` only resets the form model itself, which doesn't know anything about the directive.
