### ISSUE TITLE
 Module'"/@angular/animations/browser"' has no exported member 'ɵDomAnimationEngine'.

### ISSUE THREAD

**Issue by megetron** [angular/angular#19556]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ x] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

using 4.4.4 version of animation module shows me this:
/Users/guy/proj/client/node_modules/@angular/platform-browser/animations/src/providers.d.ts(8,119): error TS2305: Module '"/Users/guy/proj/casual_shipping/client/node_modules/@angular/animations/browser"' has no exported member 'ɵDomAnimationEngine'.

I tried this with older and lates version of the animation module but it happens anyway. do you have a guess why?

**Comment by matsko** [comment]
@chuckjaz this has popped up before and usually is something AOT/packaging related. Any ideas?

**Comment by chuckjaz** [comment]
We no longer have a symbol called `ɵDomAnimationEngine` in 4.4.4. This could be a version mismatch of the packages.

@megetron Please verify that all the `@angular/*` packages have the same version.

**Comment by chuckjaz** [comment]
Closing because we don't track support questions as issues.
