### ISSUE TITLE
renderer2 selectRootElement overwrites element content

### ISSUE THREAD

**Issue by javahaxxor** [angular/angular#19554]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

InsertAdjacentHTML overwrites the contents of the row I want to attach a sibling to:

`this.renderer.selectRootElement(`#row_${index}`).insertAdjacentHTML('afterend', '<tr><td colspan="4">inserted content</td></tr>');`

element becomes 
```
<tr class="row" id="row_0">::before ::after</tr>
<tr><td colspan="4">inserted content</td></tr>
```

## Expected behavior
```
<tr class="row" id="row_1">
  <td class="col-md-1" id="ticket_state">
    <span class="glyphicon glyphicon-star" style="color: green;"></span> 999
  </td>
  <td class="col-md-2" id="ticket_date">05.05.2015</td>
  <td class="col-md-4" id="ticket_office">AK10007</td>
  <td class="col-md-4" id="ticket_shortdescr"></td>
</tr>
<tr><td colspan="4">inserted content</td></tr>
```

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/weMFbzpxl18fWJqW13mp?p=preview

## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- [ x] Chrome (desktop) version 60.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
`insertAdjacentHTML` is a native method, not provided by `renderer2`. It is `selectRootElement()` that empties the element:

https://github.com/angular/angular/blob/7c5ecb5b5c13b24b1a86c9bd5bb74b709dc2a6e8/packages/platform-browser/src/dom/dom_renderer.ts#L143

**Comment by javahaxxor** [comment]
oh .. then there's this [post](https://stackoverflow.com/questions/36055585/renderer-multiple-selectrootelement-issue-with-plnkr-provided ) which makes me think this is intentional ..

**Comment by ocombe** [comment]
Can you update your issue or create a new one please ? Or close this one if @gkalpak comment fixed the problem

**Comment by chuckjaz** [comment]
`selectRootElement()` is not intended for general use and, as you surmise, and really only useful in bootstrap. We recommend using native DOM calls in this scenario instead of trying to use the renderer.

**Comment by ben-coble-sp** [comment]
@chuckjaz Could we get an update to the documentation for `selectRootElement()`? That's normally the first place someone would go to look for help with the renderer2 and they (aka me) will run into problems before spending more time to locate information from Angular members explaining why/why not to use it. Let me know if you'd prefer that I open a separate issue.

**Comment by hiepxanh** [comment]
i have the same problem, element disappear or empty when I select by renderer2 selectrootelement, no explain why

**Comment by muratcorlu** [comment]
@chuckjaz So, what is the correct way of selecting a DOM element in Angular by also supporting Server Side Rendering via Angular Universal?
