### ISSUE TITLE
Not showing svg when I using *ngIf

### ISSUE THREAD

**Issue by igniens** [angular/angular#19563]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[* ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In google chrome in each place where I am using ngIf and svg in html like this 											<svg class="olymp-happy-face-icon"><use xlink:href="/equestriansnet/icons/icons.svg#olymp-happy-face-icon"></use></svg>
It not shows svg when normaly navigating in page. To see svg icons I need to refresh page. And this not happens in mozila firefox

## Expected behavior

It should show svg icons without refreshing page

## Minimal reproduction of the problem with instructions

`<div *ngIf="yourfunction()">`
    `<svg class="any class"><use xlink:href="svg/location/file.svg#icon"></use></svg>`

`</div>`
`<div *ngIf="!yourfunction()">`
   ` <svg class="any class"><use xlink:href="svg/location/file.svg#icon"></use></svg>`
`</div>`

## What is the motivation / use case for changing the behavior?

I using in in one place to show login page component if not authorized user or using router if authorized, and in another place I showing few buttons or hiding depending if visiting own profile page or someone`s else

## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- [* ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  6.11.2  
- Platform:  Ubuntu 16.10

Others:

</code></pre>

**Comment by Toxicable** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by igniens** [comment]
@Toxicable 
Sorry I don`t have time to do this. Only thing I can add is that this bug works only in chrome (my version is 61.0.3163.100) and other browsers - IE, Firefox, Opera shows everything correctly...

**Comment by ocombe** [comment]
svg elements in Angular have to be prefixed with `svg:` (except for the root `svg` element). I'm not sure if it includes the `use` element, but most likely

can you try with: ` <svg class="any class"><svg:use xlink:href="svg/location/file.svg#icon"></svg:use></svg>`

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by steveblue** [comment]
I can reproduce this issue but not in Firefox, only happens for me in IE9. I will try to reproduce in Github repo since StackBlitz and IE9 don't play nice.

**Comment by McRosbeef** [comment]
> @Toxicable
> Sorry I don`t have time to do this. Only thing I can add is that this bug works only in chrome (my version is 61.0.3163.100) and other browsers - IE, Firefox, Opera shows everything correctly...

Hello did you manage to find a solution, I got the same problem sometimes on some SVG.
If you got any information I would like to hear it. thanks

**Comment by carusog** [comment]
After some research, our team found out [it's probably related a known Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=580809) where the browser doesn't cache SVG images, causing delay or even missing SVG elements especially when added or removed from the DOM tree as a shadow-DOM element. 

You can [see here a very simple (partial) reproduction of the bug](https://stackblitz.com/edit/angular-svg-use). The SVG icon is not missing but you should easily see a delay in appearing back the image on the background.

The only solution we found is to set a cache, different from zero, for SVG images in your server configuration. E.G. for our Nginx configuration it's something similar to the following code snippet.

```nginx
location ~ \.svg$ {
  expires 1d;
}
```
