### ISSUE TITLE
[Bug] Field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by luchillo17** [angular/angular#19569]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
I get an error whenever i use certain specific interface as an Input type, here's the code:
```ts
// src/typings/types.d.
export interface Route {
  id: string; 
  toId: string; 
  fromId: string; 
  clientId: string; 
  organizationId: string; 
  name: string; 
  value: string; 
  isActive: boolean; 
  shippings: Shipping[]; 
  trackings: Tracking[]; 
  routeLines: RouteLine[]; 
  from: City; 
  to: City; 
  client: Client; 
  organization: Organization; 
  createdBy: User; 
  updatedBy: User; 
  version?: number; 
  createdAt: string; 
  updatedAt: string; 
}

// src/app/route-list/route-detail/route-line-list/route-line-list.component.ts
import { ControlPlace, Route, RouteLine } from '../../../../typings/types';

@Component({
  selector: 'app-route-line-list',
  templateUrl: './route-line-list.component.html',
  styleUrls: [ './route-line-list.component.scss' ]
})
export class RouteLineListComponent implements OnInit, OnDestroy {
  @Input() route: Route;
  @Input() controlPlaces: ControlPlace[];
```
**Error:** The error goes away when i change the `Route` interface in the `Input` to any, is funny that only happens with that specific interface, i can even use that interface in other parts of same component, seems like the error happens with `Inputs` here's the error:
![image](https://user-images.githubusercontent.com/9698639/31213518-aa320ee8-a96c-11e7-8c7b-b3e7c2c7174e.png)

## Expected behavior
To build normally.

## Minimal reproduction of the problem with instructions
Not sure how since that `types.d.ts` file was generated through `graphql-code-generator`.

## Environment

<pre><code>
Angular version: 4.4.4

Browser:
- [x] Chrome (desktop) version 61
 
For Tooling issues:
- Node version: 8.6.0, 7.x.x, 6.x.x  
- Platform: Ubuntu 17.04

**Comment by luchillo17** [comment]
Changing the file extension from `.d.ts` to only `.ts` seems to help.

**Comment by ocombe** [comment]
I'm sorry but this issue doesn't seem to be caused by Angular. Please file the issue on the typescript (or graphql-code-generator) repository instead.

**Comment by luchillo17** [comment]
Thanks, since type definitions generated look good to me i'll put this on the TypeScript repo.

**Comment by luchillo17** [comment]
May it have to do with using an `interface` for the Type of an `@Input()`?
