### ISSUE TITLE
Extend numeric pipe with support for useGrouping flag

### ISSUE THREAD

**Issue by babeal** [angular/angular#19564]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The numeric pipe will always use grouping separators to formatting numbers e.g. 
3,123 
10,456
The is because the useGrouping flag of the Intl.formatNumber options defaults to true and there is no way to set this value.

## Expected behavior
The numeric pipe should allow developers to set the useGrouping flag in the pipe options.  The addition of significantDigits as provided by the internationalization api should be looked at as well but usage could be difficult.  

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
We would like to be able to control the number grouping format when using the numeric pipe.  This is a nice to have since we could just create our own and we could also create a pipe that removed the separator characters depending on locale.  However, since the intl library supports this it would be nice to expose these options in the pipe.  

## Environment
N/A
<pre><code>
Angular version: 4.3.5+
</code></pre>

**Comment by ocombe** [comment]
Hello, the numeric pipe has been rewritten completely in Angular 5 and doesn't use the intl api anymore. Each locale now has its own locale config file. You can use the function `registerLocaleData` to overwrite the default values (the default lang is `en-US`.

See the docs for this here: https://next.angular.io/guide/i18n#i18n-pipes

**Comment by ocombe** [comment]
I'm closing this issue since I provided a solution and there hasn't been any reply. Let me know if you need more info.
