### ISSUE TITLE
components in bundle as regular end ngFactory version

### ISSUE THREAD

**Issue by filipbech** [angular/angular#19575]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I build with aot and inspect the output with source-map-explorer I find that some (not all) components are both in $_gendir (as ngFactory) and not. 

## Expected behavior
Only one version of the same components should be present. And all should be ngFactory I guess...

## Minimal reproduction of the problem with instructions
A plunkr really doesn't make sense since the problem is in the build

## What is the motivation / use case for changing the behavior?
for performance I guess...

## Environment

<pre><code>
Angular version: 4.4.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  7.4.
- Platform:  Mac

Others:

</code></pre>

**Comment by filipbech** [comment]
![aot-and-not](https://user-images.githubusercontent.com/1720790/31231780-29fe70aa-a9e8-11e7-863b-8105ab1e1592.png)

**Comment by pkozlowski-opensource** [comment]
Are you sure that those are 2 identical files? Isn't it the case that one file is a component itself (in `app`) and another file is a factory for its view (template). In the screenshoot we can't see the full path but file sizes would suggest that we've got 2 different contents. 

Could you inspect content of both files here to make sure that we are really talking about duplicates?

**Comment by filipbech** [comment]
maybe, but if thats the case why don't we have both version of all the components? 
(I figured it was a dublication because the of the naming)

**Comment by vicb** [comment]
Missing information and no reproduction -> closing.
