### ISSUE TITLE
aio: document process for authoring against different branches (e.g. master and stable)

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#19573]
This should include API docs for the `ng-packages-installer` :-) @gkalpak

**Comment by jenniferfell** [comment]
@petebacondarwin and @gkalpak : Should this also be comp: docs or is this internal doc? Can you double-check my selections for frequency and severity, so this falls into triage correctly? Thanks!

**Comment by petebacondarwin** [comment]
I would say it is docs for the AIO project, so `comp: aio` and `type: docs`.
It needs @gkalpak and me to write these docs.

**Comment by petebacondarwin** [comment]
I don't believe that this is particularly an issue any more. I don't see the docs-authors doing any work against different branches.
