### ISSUE TITLE
http: The _body attribute does not exist in the interface defined in the file static_response

### ISSUE THREAD

**Issue by juliandavidmr** [angular/angular#19576]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The `_body` attribute does not exist in the interface defined in the file [`static_response`](https://github.com/angular/angular/blob/master/packages/http/src/static_response.ts)
but there when it is running, ie when the application is running

## Expected behavior
The `_body` attribute should be accessible in a request

## Minimal reproduction of the problem with instructions
Show the `_body` attribute in a http request, will not be possible because Typescript will not allow transpilation because `_body` does not exist in `static_response.ts`

## What is the motivation / use case for changing the behavior?
Aaccess to variable xxxx is required because it exists in the `Response` object during execution

```ts
    import { Http } from '@angular/http'
    constructor(private http: Http) {
    }

    ...

    let res = await this.http.get("").toPromise()
    let body = res._body    // <=== 
```

## Environment

<pre><code>
Angular version: 4.1.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.6.0  
- Platform:  Windows 

Others:

</code></pre>

**Comment by juliandavidmr** [comment]
The problem is resolved when `_body` is added to `static_response`, ie:

```ts
... 
export declare class Response extends Body {
    _body: any;

    ...
```

**Comment by trotyl** [comment]
`_body` is not a public API. You shouldn't use that at all.

**Comment by juliandavidmr** [comment]
Hi @trotyl, But I do not see another way to get the result of the request in plain text, when I use `res.text` it returns the code of a function, when I try `res.json()` a failure occurs because it can not convert xml.. I do not know what other way I can use :(

**Comment by trotyl** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Response#Methods

> **Body.text()**
> Takes a Response stream and reads it to completion. It returns a promise that resolves with a USVString (text).
