### ISSUE TITLE
Problem with nested divs and scrollbar

### ISSUE THREAD

**Issue by gouldina** [angular/angular#19570]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

A simple piece of html/css involving nested divs and a scrollbar seems to not work correctly under angular 2 where in plain html/css, it does work.
In the example given, when the window is resized smaller, the scrollbar in the div should work whereas a scrollbar is created instead in the main browser window.

## Expected behavior

The scrollbar in the div should work.

## Minimal reproduction of the problem with instructions

I can't get this plnkr to run sorry (never used it before and can't work out why it doesn't run - it works for me locally) but all the code I'm using is in there:

http://plnkr.co/edit/aO63hTKXy4L63Ttt3WPb?p=info

I have also attached a zip of my src folder for the app if that helps.

## What is the motivation / use case for changing the behavior?

It should behave in the same way as plain html/css.

## Environment

<pre><code>
@angular/cli: 1.4.1
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.3
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.1
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4

Browser:
- [x ] Chrome (desktop) Version 60.0.3112.113 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.3
- Platform:  Windows 7
[src.zip](https://github.com/angular/angular/files/1358748/src.zip)

Others:

</code></pre>

**Comment by gouldina** [comment]
[src.zip](https://github.com/angular/angular/files/1358761/src.zip)

**Comment by gouldina** [comment]
apologies - accidentally closed this.

**Comment by ocombe** [comment]
isn't the problem that you use "max_height: 100vh;" instead of "max-height: 100vh;" in your css for body ?

**Comment by gouldina** [comment]
Hi ocombe. Well spotted but it doesn't fix the problem when I change it unfortunately. 

Incidentally, I've tried using Inspect in Google Chrome to look at the css/html in the Angular version (which doesn't work) and a plain HTML/CSS version (which does) and I can't see any differences so I'm slightly baffled.

**Comment by gouldina** [comment]
OK, I've managed to get this to work by moving the max-size:100vh into the .mainDiv css.
