### ISSUE TITLE
http responseType=text should update responseText while loading in progress

### ISSUE THREAD

**Issue by gosplit** [angular/angular#19571]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
http response is null until the request is completed. 

## Expected behavior
 Response observable should be updated during progress if responseType is "text" or "".

Reference: 
"if the value of responseType was set to "text" or the empty string, response can contain the partial text response while the request is still in the loading state."
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response

## What is the motivation / use case for changing the behavior?
I have a legacy http endpoint which would run jobs for 3 mins, and print out job status line by line.  Http.response doesn't update until the connection is done, so users cannot see the job progress.

## Environment

<pre><code>
Angular version: 4.4.4

Others:

</code></pre>

**Comment by skreborn** [comment]
There is a property called [`partialText`](https://angular.io/api/common/http/HttpDownloadProgressEvent#members) that allows for the retrieval of the partial response.

**Comment by ocombe** [comment]
Hello, do you have this problem with the old http module or the new one (from @angular/common/http)?

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
