### ISSUE TITLE
New ng_module is slower than the previous one in G3 (b/68393132)

### ISSUE THREAD

**Issue by tbosch** [angular/angular#19584]
The goal is to speed up the following 2 use cases. We regressed in them, as we used to have individual `ts_library` targets for these, so blaze would only rebuild one of them. As we now have only 1 action, we need to do the caching ourselves.

1. no `.ts` files was changed, only `.html` file (or `.css` file)
2. only a `.ts` file was changed that did not affect the metadata nor the .d.ts

Proposal for 1)
- detect this case by checking whether any `ts.SourceFile` references changed for user `.ts` files, compared to the `oldProgram`
- don't typecheck nor emit these user `ts.SourceFile`s (as emitting them would cause TypeScript to typecheck them as well)
- only typecheck the changed generated files. This is ok as they don't influence each other nor the user code for type checking.
- only emit the changed generated files

Proposal for 2)
- detect that only use `.ts` files changed by checking whether a `GeneratedFile` has changed compared to the `oldProgram`
- typecheck all the files (including all generated files), as we don't know if the changes to the user `.ts` files impacted exported types or not.
- only emit the user `.ts` files (as the generated files didn't change)

A prototype for these 2 proposals shows that they lead to speed on par or better to the old `ng_module` that was based on `ts_library`s.

Implementation notes:

- blaze does not allow to skip writing files. Instead, we can create a cache for `ts.SourceFile` -> `ts.EmitResult` + written files. If don't emit a file, use the `ts.EmitResult` from the cache, and write the files again. This will still save times as the file does not need to go through TypeScript's emit pipeline nor through Tsickle.
- when using Tsickle, we have a special `TsickleEmitResult` which adds more information to `ts.EmitResult`. I.e. when we merge `emitResults` from emitting individual files, we need to be able to merge tsickle emitResults too (using the method in tsickle `tsickle.mergeEmitResult`). A good way of keeping most parts of the compiler-cli independent of tsickle would be to make the `EmitCallback` take a list of files to emit + a list of cached `EmitResults`, and expecting that callback to just return a single `EmitResult`. This way, the callback can be used for merging as well as for emitting.
- we should only keep 1 `oldProgram` cached in the blaze worker, as a program uses quite a bit of memory (e.g. as it includes the old TypeChecker). A good idea is to keep that last program where a `.ts` file was changed around (i.e. don't update `oldProgram` if the compilation was triggered because dependencies changed their `.d.ts` files.
- the current implementation of `createProgram` when passing an `oldProgram` will actually skip writing files that are unchanged. This logic needs to be adjusted to cache the emit result (see above), based on the compiler option `allowEmptyCodegenFiles: true` which is already passed in by bazel only.

**Comment by tbosch** [comment]
A previous version that didn't use an `oldProgram` was created in https://github.com/angular/angular/commit/a22121d65dbc08ca624c94cde67413f4e1d036f1. However, it broke several users as we don't have good coverage for incremental usage of `ng_module` in blaze.

**Comment by alxhub** [comment]
Filing this as a use-case as technically, the compiler needs to support more modes of operation for `ng_module`. However, the plan is to move away from this rule long-term.
