### ISSUE TITLE
[angular http] If a param is null or undefined, http throws a non descriptive error

### ISSUE THREAD

**Issue by eranation** [angular/angular#19580]
source: 
https://github.com/angular/angular/blob/01f711281c297a024ed02f998672e81a0854d427/packages/http/src/static_request.ts#L179

**Steps to reproduce** 
create a new Request object, with params containing one or more undefined or null values 

**Expected behavior**

either 
1. A clear error message (one of your params is undefined) 
2. Or handle gracefully (ignore / don't send that param, or send as empty string)

**Actual behavior:**

Error in the console (if caught)

```
 TypeError: Cannot read property 'toString' of null
    at http.es5.js:1777
    at Array.forEach (<anonymous>)
    at urlEncodeParams (http.es5.js:1771)
    at new Request (http.es5.js:1668)
```

**Comment by alxhub** [comment]
Closing as this is obsolete (it concerns `@angular/http` which has been removed in favor of `@angular/common/http`).
