### ISSUE TITLE
Class methods are lost when passing in obj as component input

### ISSUE THREAD

**Issue by BorntraegerMarc** [angular/angular#19593]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Define a model class:
```ts
export class PatientRoom {
    constructor(public lastName?: string) {
    }

    toString(): string {
      if (this.lastName) {
        return this.lastName;
      }
    }

  get randomString(): string {
    return 'random';
  }
}
```

Define a parent component:
```ts
@Component({
    selector: 'parent',
    template: `<child [patient]="patient"`
})
export class ParentComponent {
  public patient: PatientRoom = new PatientRoom('last');
}
```

Define a child component:
```ts
@Component({
    selector: 'child',
    template: `{{patient.toString()}}` // This line will print out "object object" instead of "last"
})
export class ChildComponent implements OnInit {
  @Input()
  public patient: PatientRoom;

  public ngOnInit(): void {
    console.log(patient.randomString)  // This line will cause a exception -> randomString is not defined
  }
}
```

## Expected behavior

The method calls should work. Does angular serialize and concat the objects somehow?

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [X] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: XX   - [X]
- Platform:   Windows

Others:

</code></pre>

**Comment by NenadJovicic** [comment]
got the same problem when i am trying to get object from ResponseBody
it doesn't map it as my class, even when it got same fields as my class

**Comment by BorntraegerMarc** [comment]
Same problem exists also for `@Output()` events

**Comment by robwormald** [comment]
Can't seem to reproduce this at all - see https://stackblitz.com/edit/angular-qccbwr 

This would absolutely occur if you were to do `<child someProp="{{someClassInstance}}">`, but doing `<child [someProp]="someClassInstance">` should work without issue. We don't serialize or anything like that - the data is passed straight through, as is. 

Please provide a repro of the issue (feel free to just fork off the above one)

**Comment by BorntraegerMarc** [comment]
@robwormald thanks for taking a look. I've published a repo where the issue can be reproduced: https://github.com/BorntraegerMarc/polymer-chat
Especially check my last commit https://github.com/BorntraegerMarc/polymer-chat/commit/7a4730d7a1d64bb6eb6c7ba42a143fbf922f412b -> That is the commit I made the changes to reproduce the issue.

Basically (after you launch the app) the channel list on the left side should display "@testName" but it just ignores the defined getter in https://github.com/BorntraegerMarc/polymer-chat/commit/7a4730d7a1d64bb6eb6c7ba42a143fbf922f412b#diff-696bec6727e373bdf2376672e7164e23R23 and displays the actual property:

![image](https://user-images.githubusercontent.com/7549295/31332564-27b5959c-ace7-11e7-9c84-2a86b5ace1d5.png)

**Comment by trotyl** [comment]
Nothing related to passing, you're getting those object from HTTP.

```typescript
    getChannels(): Promise<Channel[]> {
        return this.http
            .get(this.apiUrl)
            .toPromise()
            .then((res) => {
                return res.json().data as Channel[];
            })
            .catch(this.handleError);
    }

    getChannel(id: number): Promise<Channel> {
        const url = `${this.apiUrl}/${id}`;
        return this.http.get(url)
            .toPromise()
            .then((res) => {
                return res.json().data as Channel;
            })
            .catch(this.handleError);
    }
```

**Comment by BorntraegerMarc** [comment]
@trotyl makes sense. thanks for the fast answer. But I don't see how else the service should pass down the data retrieved. I would expect calling `as Channel[]` would map the existing methods from `Channel` to the data from `res.json().data`. Am I wrong? Or how should we else pass the data to the component from a service without loosing the methods defined in `Channel`?

**Comment by trotyl** [comment]
TypeScript is just something helping you analyze your code with static type checking, it does not have any runtime semantic <sub>(actually there're some in very old versions kept for compatibility)</sub>.

**Comment by BorntraegerMarc** [comment]
mhmm I understand @trotyl . Does angular/typescript suggest a "best practice" on how to achieve what I want to do? Or do you see any other solution?

**Comment by BorntraegerMarc** [comment]
or would you agree to transform this issue into a feature request? For me as a not-that-experienced angular dev it feels like a bug although your point with typescript is totally valid. But essentially the compiled version of angular is behaving differently than what I wanted to define in my TS code...

**Comment by trotyl** [comment]
No, transforming from DTO to model is project-specific. Imaging how to deserialize? How can we know it's a date from a number (timestamp) or string (ISO format)?

And TypeScript's type infos are not available at runtime, so no lib can help you with that.

**Comment by trotyl** [comment]
It could only be possible if you request that Angular should get rid of TypeScript and inventing its own AtScript plus. That could be a valid feature request, but certainly would be closed quickly.

**Comment by BorntraegerMarc** [comment]
A own AtScript plus does not seem feasible if you ask me. I agree. But just a stupid question from my point of view:
If some data comes from the server as `{date: 2012-02-03, number: 3}` -> does the angular compiler not have access to the initial typescript model:
```ts
export class Data {
    constructor(public date: Date; public number: Number) {
    }

  toString() {
    return 'asdf';
  }
}
```

So couldn't we do some kind of:
```ts
.map((res) =>{
  return res.json().data as Data;
}).map((data: Data) => {
  const verificationData = new Data(new Date(), 0); // this part is gonna be tricky to initialize wit generic data
  for (const key in verificationData) {
      if (!data.hasOwnProperty(key)) {
        data.key = verificationData.key; // so here we could at least keep the toString method when fetching data
      }
  }
});
```

Do you think the idea is feasible or makes sense at all? @trotyl

**Comment by trotyl** [comment]
Angular compiler is just for compiling template (with metadata collected), won't do anything about your logic code.

**Comment by mlc-mlapis** [comment]
@BorntraegerMarc ... are you looking for something like "runtime-type-checks"?

https://github.com/vsavkin/RuntimeTypeChecks

It is from Victor Savkin as the light idea what could be possible to do ...

**Comment by BorntraegerMarc** [comment]
@mlc-mlapis that's a good start but I was looking for something more "angular native" like. Well I guess if nobody disagrees with @trotyl I'm gonna close the issue. I have to little knowledge to argue...

**Comment by NenadJovicic** [comment]
I have different use case with same problem.
I am using JWT token, and i send some User (have TS class defined with fields and some methods) object into token. Then I decode it.
I got specific method that will create new User object
```typescript
public loggedInUser: User;

{
      decodedUser: any = jwt_decode(token).user;
      this.loggedInUser = this.createNewUser(tokenUser);
}

createNewUser(tokenUser: any): User {
     const loggedInUser: User = new User();
     loggedInUser.username = tokenUser.username;
     loggedInUser.role = tokenUser.role;
     loggedInUser.name = tokenUser.name;
     // setting some other fields
     return loggedInUser;
}
 ```

Now, this code is in some service (login.service.ts), so that user is stored until that service is killed.

And I have some simple methods inside user.model.ts file 
```typescript
export class User {
   username: string;
   role: string;
   name: string;

   public isRoleAdmin(): boolean {
       return this.role === 'ROLE_ADMIN';
   }

   public isRoleJournalist(): boolean {
       return this.role === 'ROLE_JOURNALIST';
   }
}
```

Now I want to check in some component is loggedInUser ADMIN
I inject that service through constructor
 
```typescript
export class SomeComponent implements OnInit {
   isUserAdmin: boolean;

   constructor(private loginService: LoginService) { }

   ngOnInit() {
      this.isUserAdmin = this.loginService.loggedInUser.isUserAdmin();
   }
}
```

but I get the error, **isUserAdmin is not a function**

**Comment by BorntraegerMarc** [comment]
@trotyl is the error from @NenadJovicic because of the same reason?

**Comment by ericmartinezr** [comment]
@BorntraegerMarc nope, he's just calling `isUserAdmin()` when his function is `isRoleAdmin()`.

**Comment by NenadJovicic** [comment]
@ericmartinezr I mistyped it
this was sample, didn't check it
but when I type code, I use ctrl+space for auto suggesting, so I used proper method in my code
Now I will fix it
