### ISSUE TITLE
Angular cli doesn't build polyfills properly

### ISSUE THREAD

**Issue by lordscales91** [angular/angular#19590]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
with ng serve the app works properly on IE11 (after adjusting polyfills of course), but with ng build it doesn't work

## Expected behavior
ng build should follow the same procedure for generating the files, apparently it doesn't

## Minimal reproduction of the problem with instructions
* Start a new project with ng new
* Adjust the polyfills.ts to support IE
* Build the project with ng build
* Copy the generated files from dist to an HTTP Server (Is that the way to deploy an Angular 2 app, right? I used Apache as HTTP Server)

## What is the motivation / use case for changing the behavior?
Personally I don't care about IE, people should stop using it but my client still uses it and that isn't gonna change anytime soon.

## Environment
Windows 10

<pre><code>
Angular version: 4.3.4
Angular cli: 1.2.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1
- Platform:  Windows

Others:
Apache 2.4 

</code></pre>

**Comment by gkalpak** [comment]
Please open an issue on the [@angular/cli][1] repo.

[1]: https://github.com/angular/angular-cli/issues
