### ISSUE TITLE
Propogate Changes Up

### ISSUE THREAD

**Issue by wisesascha** [angular/angular#1959]
Is it possible to have changes from a sub component be propagated to the parent. I found issue #962, but the code he uses seems out dated. Is there a new way of doing this with events?

**Comment by jelbourn** [comment]
Are you referring to `EventEmitter` events or native DOM events?

For the latter, there are two separate issues: #1168 (bug) and #1040 (proposal).

**Comment by wisesascha** [comment]
I was referring to the event emitter event

**Comment by jelbourn** [comment]
Furthermore, do you mean that `EventEmitter` events currently don't break component boundaries?

**Comment by wisesascha** [comment]
I couldn't find any existing documentation on how to use the EvenEmitter even, as using the 

    @EventEmitter
syntax doesn't seem to work

**Comment by jelbourn** [comment]
The docs show how it is used here: https://angular.io/docs/js/latest/api/annotations/Directive-class.html

**Comment by mhevery** [comment]
not actionable.
