### ISSUE TITLE
Angular 5.0.0-rc.x does not work with angular/flex-layout 2.0.0-beta.9

### ISSUE THREAD

**Issue by mattma** [angular/angular#19598]
<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Angular application works perfect fine with `4.4.4`, rxjs `5.4.3`, typescript `2.3.4`.

```
"@angular/flex-layout": "2.0.0-beta.9",
"@angular/material": "2.0.0-beta.11",
"@angular/cdk": "2.0.0-beta.11",
```

I tried with Angular `5.0.0-beta.6`, `5.0.0-beta.7`, `5.0.0-rc.0`, `5.0.0-rc.1`, the application builds perfectly fine. When run the app in the browser, it has JS errors.

## Current behavior

The angular application cannot be run in the browser. 

![screen shot 2017-10-06 at 11 52 13 am](https://user-images.githubusercontent.com/1148428/31293689-e7c2fed6-aa8c-11e7-92d3-09016e04aac5.png)

## Expected behavior

The angular application should not have any console JS errors.

## What is the motivation / use case for changing the behavior?

I think it is related to `@angular/flex-layout` or `@angular/material` module use any private `Angular` core method that have been removed in `5.0.0`. In `4.x.x` is only the deprecation warning so that it continues to work in `4.x.x.`

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ X] Chrome (desktop) version XX  Latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:

@angular/cli: 1.5.0-beta.3
node: 8.4.0
os: darwin x64
@angular/animations: 5.0.0-rc.1
@angular/cdk: 2.0.0-beta.11
@angular/cli: 1.5.0-beta.3
@angular/common: 5.0.0-rc.1
@angular/compiler: 5.0.0-rc.1
@angular/compiler-cli: 5.0.0-rc.1
@angular/core: 5.0.0-rc.1
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 5.0.0-rc.1
@angular/http: 5.0.0-rc.1
@angular/material: 2.0.0-beta.11
@angular/platform-browser: 5.0.0-rc.1
@angular/platform-browser-dynamic: 5.0.0-rc.1
@angular/platform-server: 5.0.0-rc.1
@angular/router: 5.0.0-rc.1
@angular/service-worker: 1.0.0-beta.16
@angular/language-service: 5.0.0-rc.1
typescript: 2.3.4

**Comment by jelbourn** [comment]
See https://github.com/angular/flex-layout/issues/420
