### ISSUE TITLE
angular.io pages don't print well

### ISSUE THREAD

**Issue by drveresh** [angular/angular#19599]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Many of the documentation pages doesn't a have decent printable format.  Please check these screenshots:
http://prntscr.com/gu640x
http://prntscr.com/gu668q

## Expected behavior

There should be no space around the content.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [Version 61.0.3163.100 (Official Build) (64-bit)] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
This does look bad and should be easily fixed in our CSS. @sjtrimble do you have time to look at this?

**Comment by sjtrimble** [comment]
Yup!

**Comment by sjtrimble** [comment]
@petebacondarwin I did some print format cleanup, but I'm having a hard time with the material sidenav auto-adjusting the margin of the content section. I can get it to not show up when printing, but I can't get the content to move to the left to occupy its space.

**Comment by gkalpak** [comment]
@sjtrimble, see https://github.com/angular/angular/pull/19651#pullrequestreview-68511365.

**Comment by petebacondarwin** [comment]
This was fixed by #19651
