### ISSUE TITLE
Add symlink to `packages\upgrade\static\src` to `create-symlinks.sh`

### ISSUE THREAD

**Issue by maximusk** [angular/angular#19608]
Currently there's only one symlink in [create-symlinks.sh](https://github.com/angular/angular/blob/master/scripts/windows/create-symlinks.sh):

```
cmd <<< "mklink \"..\\..\\packages\\core\\src\\animation\\dsl.ts\" \"..\\..\\..\\animations\\src\\animation_metadata.ts\""
```

When building Angular project another symlink is required:

```
cmd <<< "mklink /j \"..\\..\\packages\\upgrade\\static\\src\" \"..\\..\\packages\\upgrade\\src\""
```

**Comment by ocombe** [comment]
I don't think that the build can be run on windows anyway, too many things use shell scripts that are not windows-compatible.
It'll only be possible once we switch to bazel

**Comment by maximusk** [comment]
I built on windows without any problems using `git bash`. Symlink is the only thing that I had to add.

**Comment by ocombe** [comment]
interesting, let me try that

**Comment by gkalpak** [comment]
There is a long-standing PR for updating the symlinks: #16761

But based on issues like #12454 and #17894 (and my personal experiences from a while back), it seems that it currently not straight forward to build Angular on Windows. But maybe things have changed lately (that would be amazingly awesome :smiley:).

**Comment by ocombe** [comment]
ahah good catch @gkalpak I was about to create a new PR
I'll close this issue then, in favor of #16760
