### ISSUE TITLE
Document that libraries compiled with Angular 5.x are not compatible with Angular 4.x

### ISSUE THREAD

**Issue by tiberiuzuld** [angular/angular#19607]
## I'm submitting a...

<pre><code>
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Compiling the [library angular-gridster2](https://github.com/tiberiuzuld/angular-gridster2) with 
`ngc -p tsconfig-lib.json` from Angular v5.0.0-beta.4 onward to v5.0.0-rc.1 fails at compiling correctly the files.
left 5.0.0-beta.3 - right 5.0.0-rc.1 
![image](https://user-images.githubusercontent.com/15310395/31315634-d57b0036-ac24-11e7-9df1-6d509c36ca6c.png)

People using the library will get a `ERROR in Metadata version mismatch for module ../node_modules/angular-gridster2/dist/index.d.ts, found version 4, expected 3.`
[Issue](https://github.com/tiberiuzuld/angular-gridster2/issues/137)

## Expected behavior

It should compile as in v5.0.0-beta.3
I didn't see any breaking changes in the changelog for tsconfig/compiler

## Minimal reproduction of the problem with instructions

[tsconfig-lib.json](https://github.com/tiberiuzuld/angular-gridster2/blob/master/tsconfig-lib.json)
[repo](https://github.com/tiberiuzuld/angular-gridster2)
1. Clone repo
2. Change version of @angular to 5.0.0-rc.1 in package.json
3. Run `npm install`
4. Run `npm run build-npm`
It does `"build-npm": "gulp inline-templates && ngc -p tsconfig-lib.json"`
5. Check file `./dist/gridster.module.js`

## Environment

<pre><code>
Angular version: 5.0.0-beta.4 onward to 5.0.0-rc.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.50, npm 5.5.1  
- Platform:  Windows 10 

Others:

</code></pre>

**Comment by alexzuza** [comment]
I think people how are using build based on 5.0.0-rc.1 should use that version of angular compiler that supports metadata version 4.
In 5.0.0-rc.1 angular team increased metadata version because they are capturing type aliases in metadata files. https://github.com/angular/angular/commit/a75040d0a15c06cc8250032f044b7df0ed885317

In 5.0.0-beta-4 compiler was switched to transformer based compiler https://github.com/angular/angular/commit/679608db6543c2f9633e33841a6074548006fbe2 So from this moment compiler host is locates in `transformers` folder and `host.getSourceFile` implementation doesn't have such function like `downlevelDecorators` as it was in `TsickleCompilerHost.getSourceFile`

**Comment by ocombe** [comment]
Yes I think that @alexzuza is right. Libraries compiled for Angular v5 are compatible with Angular v5+ because we don't want to ship useless metadata for the libraries when it can be done by the app compiler. Can you confirm this @tbosch ?

**Comment by tiberiuzuld** [comment]
Hi @alexzuza and @ocombe ,
Thank you for the clarification, and I understand why it should be like this, but.

Why this wasn't written somewhere as a breaking change?


Thanks,

**Comment by ocombe** [comment]
It's probably a mistake if it's not in the changelog

**Comment by dgroh** [comment]
I don't find this in the changelog. We have problems now with backward compatibilities. We have Angular 5 packages and Angular 4.3.6 applications. As a workaround I can suggest changing the `metadata.json` by hand. there should be a way to target the metadadata min version, otherwise this is going to be a big problem in future releases.

**Comment by AckerApple** [comment]
I'm getting issue reports from other people, on my package, that Angular5 does not work with my package with error "Module not found".

https://github.com/AckerApple/angular-file/issues/16

I will follow this issue. Perhaps my package should change major version number and build with Angular 5?

**Comment by ocombe** [comment]
if the library is still compiled with v4, it should be compatible for users who are on v5.
It's the other way around that doesn't work (compiled with v5 and used in an app with v4)

**Comment by AckerApple** [comment]
Thank you for the input. I will test further than my current assumptions on the matter.

End all, quite simply I think I rebuild in Angular5 and change major and/or minor version numbers.

Good show good show

**Comment by napindc** [comment]
I'm also getting this 'ERROR in Metadata version mismatch' error

**Comment by KErez** [comment]
So to summarize: If I have an angular 5 component I cannot use it in another angular 4 app?

**Comment by dgroh** [comment]
@KErez - that is correct! Unless you change the `metadata` file by hand, what is not recommended...

**Comment by KErez** [comment]
@dgroh angular continues breaking compatibility. That is very bad practice. So if I want to create or upgrade a small external component I need to upgrade the entire system. That is a shame:(
What should I change in the metadata in order to make it work? Can you point me to an example?

**Comment by aitboudad** [comment]
@KErez there is no breaking compatibility, you can use angular 4 components in angular 5 but not the reverse which is logical to me, angular 5  contains some features that cannot be known in the old version.
it's the same for all libraries that follow semver.

**Comment by AckerApple** [comment]
@KErez, I know it seems like madness and it WAS to me, as I have several Angular packages with people that WERE reporting incompatibility issues about 4 installing packages bundled with Angular 5. 

All those issue reports have gone away once my installers upgraded to Angular5. And again it's NOT a complete incompatibility. You'll get threw it. Upgrade to Angular5 if possible, it's worth it for the performance improvements alone.

**Comment by KErez** [comment]
@AckerApple I agree, it is better to upgrade but everything is a matter of timeframes which I don't have for the main app at that moment. The outcome is that I cannot use angular5 components that we already have. This kind of behaviour was not happened in angularjs and you could use ng1.6 components in ng1.5 app or even earlier versions. The same goes with other libraries. 
Anyway @dgroh mention that I can tweak the metadata file. Do you have an example? What should I tweak there?

**Comment by AckerApple** [comment]
This comment is opinions only:

@KErez AngularJs 1.5 to 1.6 is a MINOR version number change. Angular 4 to 5 is a MAJOR version number change. You can compare bananas to rocks, it’s possible, but a MAJOR version change implies breaking code, a MINOR does not always imply broken code.... you shouldn’t compare the too like you are.

Bottom line, it’s your own fault for using bleeding edge technologies. Technologies that are growing and changing as you are using them. It’s a risk, it’s where the bleeding term comes from.

Which you are now, bleeding time trying to patch a metadata file where instead that time most likely isn’t better spent updating Angular to the latest version

**Comment by zarend** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
