### ISSUE TITLE
Feature request: get reference to a directive applied onto a component

### ISSUE THREAD

**Issue by parker-mike** [angular/angular#19605]
An option to get such a reference would be useful in case of _Attribute Directives_ when there is a need to extend a component that comes from a 3rd party library with some functionality and then execute a Directive's methods on a subset of the components which have this Directive applied.

## Motivation
I'm using Material and I have several tabs with components(like widgets) that should be updated each time the hosting tab is activated. For this purpose I've created a Directive that looks like this:
```
@Directive({ selector: '[actualizable],[actualizer]' })
export class ActualizableDirective
{
    @ContentChildren(ActualizableDirective)
    actualizables: QueryList<ActualizableDirective>;

    @Output()
    actualizer: EventEmitter<any> = new EventEmitter<any>();

    constructor()
    {
    }

    actualize()
    {
        this.actualizables.forEach(a => {
            a.actualize();
        });
        this.actualizer.emit();
    }
}
```
so the template looks like this:
```
…
<md-tab-group (selectChange)="activateTab($event)"
    <md-tab actualizable>
…
```
Now I need the reference to this directive so when the `activateTab` is fired and I get the active tab from  `MdTabChangeEvent`, I can execute the `actualize` method:
```
activateTab(e: MdTabChangeEvent)
{
    e.tab.ActualizableDirective.actualize(); // How do I get to the directive's actualize method?
}
```
I've dug into the tab's JS object and seen that there is a reference to my Directive in an `e.tab.content.viewContainerRef.injector.view.nodes` array, so may be I just don't know how to get to it properly from my code...
## Environment

<pre><code>
Angular version: 4.2.2
Material version: 2.0.0-beta.12
</code></pre>

**Comment by mlc-mlapis** [comment]
@parker-mike ... for those reasons there is possible to use `exportAs` metadata (even with multiple values in the latest Angular ... since 4.4.1) in a directive and use it as:
```
<md-tab actualizable #refActualizable="asActualizable">
```
This syntax is used for example here for `ngModel`: https://github.com/angular/angular/blob/b14c2d1568f9cc634c18fe1ee77a647aa57a012a/packages/forms/src/directives/ng_model.ts#L109

**Comment by parker-mike** [comment]
@mlc-mlapis Yeah, thank you, I'm aware of the `exportAs` property existence and using it in some of my directives, but I didn't find a way to use it in the example given in motivation section.

**Comment by mlc-mlapis** [comment]
@parker-mike ... hmm, you can always use something like:
```
…
<md-tab-group (selectChange)="activateTab($event, refActualizable)">
    <md-tab actualizable #refActualizable="asActualizable">
</md-tab-group>
…
```

**Comment by parker-mike** [comment]
@mlc-mlapis Thanks, but if I have several tabs like this:
```
…
<md-tab-group (selectChange)="activateTab($event, refActualizable)">
    <md-tab actualizable #refActualizable="asActualizable">
    <md-tab actualizable #refActualizable="asActualizable">
    <md-tab actualizable #refActualizable="asActualizable">
    <md-tab actualizable #refActualizable="asActualizable">
</md-tab-group>
…
```
How would the engine know which of the `refActualizable` to pass into `activateTab`?

**Comment by mlc-mlapis** [comment]
@parker-mike ... then you probably need to re-think the structure of that code part and change the logic ... as I guess through some type of shared service ... but this situation is probably a common pattern in MD so there should be also a recommended solution? We don't use MD yet, so ...

**Comment by parker-mike** [comment]
@mlc-mlapis That's why I've asked on stackOverflow, and when seen that nobody is there to answer asked here... Since I didn't find a proper way of doing it, I thought that it would be a useful feature. I thought about shared service, but this way all `Actualizables` will be subscribed to that service and thus will be updated all together regardless to the tab being selected in my example.

**Comment by mlc-mlapis** [comment]
@parker-mike ... probably switch to the MD gitter then: https://gitter.im/angular/material2

I looked at the source here https://github.com/angular/material2/blob/master/src/lib/tabs/tab-group.ts#L141 and there is `selectedTabChange` `@Output()` for that reason, isn't?

**Comment by parker-mike** [comment]
@mlc-mlapis That's the new version of deprecated `selectChange` used in my first example, in the example with several tabs you can see that I've used the `selectedTabChange`. I've opened request under main repository since I believe that this is something that can be useful also in other scenarios and not only with MD tabs.

**Comment by mkoczka** [comment]
I think there is no need to implement something here. You can create query list of directives and find the actual directive.

Your implementation should look like this. (I created the example [here](https://stackblitz.com/edit/angular-jdgaew)).
```
...
<mat-tab-group (selectedTabChange)="activateTab($event)">
    <mat-tab actualizable #refActualizable="asActualizable" label="Tab 1"></mat-tab>
    <mat-tab actualizable #refActualizable="asActualizable" label="Tab 2"></mat-tab>
    <mat-tab actualizable #refActualizable="asActualizable" label="Tab 3"></mat-tab>
    <mat-tab actualizable #refActualizable="asActualizable" label="Tab 4"></mat-tab>
</mat-tab-group>
...
```

```
...
@ViewChildren('refActualizable') actualizables: QueryList<ActualizableDirective[]>;

activateTab(e: MatTabChangeEvent) {
  const actualizable: ActualizableDirective = this.actualizables.find((item, index) => index === e.index);
  actualizable.actualize();
}
...
```

So I think this can be closed.
