### ISSUE TITLE
The browser support page is out of date

### ISSUE THREAD

**Issue by mgol** [angular/angular#19618]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The page at:
https://angular.io/guide/browser-support
mentions Edge 13-14 , iOS 7-10 * Safari 7-10.

## Expected behavior

Safari 11, iOS 11 & Edge 15 have been released and Edge 16 is going to be released in a few days. They should be added to the table.

## Minimal reproduction of the problem with instructions

N/A

## What is the motivation / use case for changing the behavior?

Reflecting the reality that newest browsers are supported.

## Environment
N/A

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kapunahelewong** [comment]
@mgol Thanks for bringing up this issue. We'll check with engineering and make the updates as soon we have confirmation.

**Comment by jenniferfell** [comment]
@IgorMinar is taking a look at this

**Comment by IgorMinar** [comment]
I suggest the following changes to the doc:

- remove all versions under "Edge" and replace them with "The last 2 major versions"
- the same for "Safari" and iOS
- from "Android" drop "Jelly Bean" (it now accounts for 5% of worldwide usage according to https://developer.android.com/about/dashboards/index.html)

These changes will allow us to keep the page up to date even as the new browser versions are released for evergreen browsers and over time we'll slowly phase out support for old non-evergreen browsers as their usage drops.

**Comment by jenniferfell** [comment]
Label for eng input: I have a quick follow-up question out to @IgorMinar directly.

**Comment by IgorMinar** [comment]
Jennifer has concerns about us committing to the latest two versions without specifying numbers.

This is intentional. We don't want to be updating this page every month when a new release of some browser comes out. And besides we need to be compatible with the latest version because that's what people use. So being vague about the exact version numbers is the preferred way to document the browser support.

**Comment by jenniferfell** [comment]
Closed by https://github.com/angular/angular/pull/21606
