### ISSUE TITLE
'Cannot read property 'push' of undefined' error from the official tutorial

### ISSUE THREAD

**Issue by PhucNgo1711** [angular/angular#19614]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I followed this tutorial https://angular.io/tutorial until the very last section: https://angular.io/tutorial/toh-pt6

However, I'm getting the same issue as the "live example" (https://angular.io/generated/live-examples/toh-pt6/eplnkr) put on the tutorial, which is 'Cannot read property 'push' of undefined'

Looks like the error comes from dashboard.component.ts

## Expected behavior

The full page should be displayed as described in the tutorial

## What is the motivation / use case for changing the behavior?

I'm following the tutorial to learn the new Angular

## Environment
Mac OS Sierra 10.12

<pre><code>
Angular version: 4.4.4

Browser:
- [x] Chrome (desktop) version 61.0.3163.100 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lazarljubenovic** [comment]
Funny. When I open the link, I get an error `Cannot read property 'slice' of undefined`.

**Comment by ericmartinezr** [comment]
Already reported over here https://github.com/angular/angular/issues/19602

**Comment by PhucNgo1711** [comment]
Looks like a fully working version of the project can be found at https://github.com/johnpapa/angular-tour-of-heroes

I was able to fix the issue thanks to @ericmartinezr, but there were issues with the search and add function as well
