### ISSUE TITLE
mobile.angular.io now redirects to main page. Where can I find the mobile guides?

### ISSUE THREAD

**Issue by aks1994** [angular/angular#19615]
Previously, mobile.angular.io would load a page with several guides for mobile/PWA development. The pages had a yellow theme.

Now it just redirects to angular.io and I can't seem to find the mobile guides. Is this intentional or a bug? Where can I find the mobile guides?

**Comment by Toxicable** [comment]
Intended. There is work being done to bring the functionality that was found there into the core repo.
Of recent note is bringing the service worker here: https://github.com/angular/angular/pull/19274
This is ongoing at the moment.

**Comment by aks1994** [comment]
Thanks for the quick response.
