### ISSUE TITLE
Proposal:Component not to render <my-tag> to dom

### ISSUE THREAD

**Issue by kgtkr** [angular/angular#19610]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

**Comment by trotyl** [comment]
Duplicate of #18877.

**Comment by kgtkr** [comment]
ok
