### ISSUE TITLE
Cannot use the "new" command inside an Angular CLI project.

### ISSUE THREAD

**Issue by sanjeevgahlot** [angular/angular#19612]
## I'm submitting a issue with opening a new folder with command "ng new my-app" in Mac Terminal.
The message says " You cannot use the new command inside an Angular CLI project."
Kindly help me resolve the issue.
![angular_cli_err](https://user-images.githubusercontent.com/3387892/31318436-445b9e3e-ac70-11e7-88bf-6be78968e319.png)

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Please report angular-cli's related issues in its repo https://github.com/angular/angular-cli. Plus that do a simple search on the repo, the issue was already reported.
