### ISSUE TITLE
Cannot read property 'type' of undefined while embedding UserVoice widget in prod environment

### ISSUE THREAD

**Issue by geetikasharma26** [angular/angular#19627]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
While embedding a uservoice widget, it gives an error " Cannot read property 'type' of undefined" in one of the polyfills( attached screenshot). The widget loads properly in the local environment but gives above mentioned error in prod.

## Expected behavior
The User voice widget should be loaded without errors.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
![uservoice widget error](https://user-images.githubusercontent.com/8762706/31359507-201127e4-acff-11e7-9da5-f5f7eea94fbe.PNG)

**Comment by geetikasharma26** [comment]
Environment:
Angular: 4.3.5
Angular-cli: 1.3.2
Typescript: 2.3.4
We use AOT build as well

**Comment by geetikasharma26** [comment]
Code used to embed UserVoice widget:
window['UserVoice'].push(['embed', '#uv_embedded', {
                mode: 'smartvote',
                height: '100%',
                width: '100%'
            }]);

**Comment by ericmartinezr** [comment]
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by vicb** [comment]
closing as no repro
