### ISSUE TITLE
Preserve stack trace for thrown non-Error objects

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1962]
This is a follow up to #1709 and https://github.com/angular/ts2dart/issues/152.

Make sure we are preserving stack traces for errors that do not descend from `Error`. Make [this repro case](https://github.com/jbdeboer/angular2_stack_traces) work.

(This is Dart only. JS cannot preserve non-`Error` stack traces.)

/cc @jbdeboer

**Comment by jbdeboer** [comment]
+1, thank you.
