### ISSUE TITLE
IE11 : IFrame content change breaks angular 2

### ISSUE THREAD

**Issue by KarthickVaradharajan** [angular/angular#19620]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: 2.4.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.7.4  
- Platform: Windows   

Others:

Windows 7,
VS 2017,
npm
IIS
</code></pre>

**Comment by mlc-mlapis** [comment]
@KarthickVaradharajan ... add details and repro ...

**Comment by chuckjaz** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by fkhasib** [comment]
I am having a similar issue, angular 2 (v4.0.0>) doest work on IE 11 if embedded inside an iframe.
To repeat, 
1- ng new testApp
2- cd testApp
3- npm install
4- ng server
and now create an html file and embed the following
```
<div>
	<iframe id="iframe" src="http://localhost:4200/" style="width:100%;height:100%;"/>
</div>
```
I get the following errors:
![screen shot 2017-12-18 at 8 19 55 pm](https://user-images.githubusercontent.com/4357228/34137484-dca62c34-e430-11e7-8ec4-f3266f89ccf7.png)
