### ISSUE TITLE
test(aio): fix upgrade-phonecat e2e tests

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#19625]
Fix and re-enable the upgrade-phonecat examples e2e tests:

https://github.com/angular/angular/blob/66515412308138ad083bdd91ab2e80cd2bdf7fac/aio/tools/examples/run-example-e2e.js#L25

They have been temporarily disabled on master and 4.4.x to unblock further work on these branches. The issue seems to be some typings that are incompatible with TypeScript 2.5.3.

**Comment by IgorMinar** [comment]
Is this still a problem? I can't tell... @gkalpak ?

**Comment by gkalpak** [comment]
As mentioned above, the tests are not compatible with latest TS (mainly due to bad AngularJS typings).
I intend to fix them after the upgrade to TS 2.6 (to avoid unnecessary work).
#lazy :smiley:

**Comment by IgorMinar** [comment]
ok. thanks!
