### ISSUE TITLE
Poor performance in IE 10+ when using with webcomponent polyfill

### ISSUE THREAD

**Issue by borgitas21** [angular/angular#19626]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

To be honest I'm not sure if this issue must be submitted in this repository or in the webcomponents one.

## Current behavior
For some reason we must use webcomponents + Angular in a project. Since the support for webcomponent is still poor, we are adding the webcomponent polyfill. The polyfill is working fine without Angular but it seems that, when both are working together, the performance is really bad (~20 seconds every route change) . Particularly visible in IE 10+.

## Expected behavior
Better performance when both libraries are working together

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by vicb** [comment]
Closing as no repro. 
Please open a new issue when you can attacha repro. Thanks.
