### ISSUE TITLE
Please update documentation regarding Microtask and Macrotask boolean in NgZone class

### ISSUE THREAD

**Issue by SamAtAllegion** [angular/angular#19623]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently the documentation at: [NgZone Documentation](https://angular.io/api/core/NgZone) is lacking.  I had no idea what a Microtask or Macrotask consisted of and my first place to find it, the documentation, only states that the response is boolean, with no documentation around what might affect those values. 

## Expected behavior

Something akin to the explanations on this SO post I found would be nice to have in the documentation itself: [What does hasPendingMacrotasks and hasPendingMicrotasks check for?](https://stackoverflow.com/questions/43480595/what-does-haspendingmacrotasks-and-haspendingmicrotasks-check-for)

## What is the motivation / use case for changing the behavior?

Better documentation so people lost as to why their Protractor isn't working can know what type of task a Macrotask is in regards to the NgZone. 

## Environment

<pre><code>
Angular version: 4.3.2

Browser:
- [x ] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kapunahelewong** [comment]
Hey @SamAtAllegion thanks for bringing this up. I'll make sure to share this with the docs team so we can address it.

**Comment by jenniferfell** [comment]
Labeled for engineering team input: Would appreciate engineering input on priority of API ref update and priority of potential addition to guide (in addition to API ref clarification here). Guide doesn't discuss ngZone, nor anything specific about micro and macrotasks in an Angular context, except for an external link under tick in the Testing doc: https://angular.io/guide/testing

**Comment by ajitsinghkaler** [comment]
@kapunahelewong @JiaLiPassion added api documentation for ngZone I think we can close this issue now

**Comment by kapunahelewong** [comment]
Thank you, @ajitsinghkaler! @SamAtAllegion, as @ajitsinghkaler says, please do feel free to comment/re-open if your concern hasn't been met.
