### ISSUE TITLE
External library corrupted if i go directly 2 level route of the app using URL navigator field!

### ISSUE THREAD

**Issue by AhmedBHameed** [angular/angular#19628]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The code works fine normally under "ng serve" of Angular-CLI. After making any update or use URL field to navigate 2 level deep of the app, console get errors for all external libraries as not defined.
This is my index.html of all external libraries
```
<head>
  <meta charset="utf-8">
  <!-- IE HTML5 Library -->
  <script src="./assets/js/html5shiv.min.js"></script>
  <!-- Jquery library -->
  <script type="text/javascript" src="./assets/js/jquery-3.2.1.min.js"></script>
  <!-- Google Font and fontawesome -->
  <link href='https://fonts.googleapis.com/css?family=Anton|Passion+One|PT+Sans+Caption' rel='stylesheet' type='text/css'>
  <link href="./assets/sass/font-awesome.min.css" rel="stylesheet">
  <!-- Bootstrap and animate library -->
  <link href="./assets/sass/bootstrap337/css/bootstrap.css" rel="stylesheet">
  <link href="./assets/sass/animate.css" rel="stylesheet">
  <script src="./assets/js/bootstrap337/js/bootstrap.min.js"></script>
  <!-- Moment library -->
  <script src="./assets/js/moment.min.js"></script>
  <!-- Bootstrab notification library -->
  <script src="./assets/js/bootstrap-notify.min.js"></script>

  <!-- CSS file -->
  <link href="./assets/sass/style.css" rel="stylesheet">

  <title>NFC Check In System</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
```
Note that i have 2 deep level of route
URL pointer like this
http://localhost:4200/admin/reports
```
const APP_ROUTES: Routes = [ 
  {path: 'admin', component: CpComponent, children: [
    {path: '', component: AdhomeComponent, data: { title: 'Admin-Panel'}},
    {path: 'reports', component: ReportsComponent, data: { title: 'Admin-Reports'}},
  ]}
];

```
This happened after any code source update or if i go manually to the second level of the app route.
the app work find if i use links of the [routeLink] (i mean if i use the mouse pointer to navigate throw the pages).
Is there any way to pass this issue without including my libraries inside angular-cli.json scripts???

## Expected behavior

It should work fine after update like first time initialized with no issue.

## Console report (ERROR REPORT)
reports:6 GET http://localhost:4200/admin/assets/js/html5shiv.min.js net::ERR_ABORTED
reports:8 GET http://localhost:4200/admin/assets/js/jquery-3.2.1.min.js net::ERR_ABORTED
reports:11 GET http://localhost:4200/admin/assets/sass/font-awesome.min.css net::ERR_ABORTED
reports:13 GET http://localhost:4200/admin/assets/sass/bootstrap337/css/bootstrap.css net::ERR_ABORTED
reports:14 GET http://localhost:4200/admin/assets/sass/animate.css net::ERR_ABORTED
reports:17 GET http://localhost:4200/admin/assets/js/moment.min.js net::ERR_ABORTED
reports:19 GET http://localhost:4200/admin/assets/js/bootstrap-notify.min.js net::ERR_ABORTED
reports:22 GET http://localhost:4200/admin/assets/sass/style.css net::ERR_ABORTED
reports:15 GET http://localhost:4200/admin/assets/js/bootstrap337/js/bootstrap.min.js net::ERR_ABORTED
reports:17 GET http://localhost:4200/admin/assets/js/moment.min.js net::ERR_ABORTED
reports:19 GET http://localhost:4200/admin/assets/js/bootstrap-notify.min.js net::ERR_ABORTED
reports:22 GET http://localhost:4200/admin/assets/sass/style.css net::ERR_ABORTED
core.es5.js:2925 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CpComponent_Host.html:1 ERROR ReferenceError: $ is not defined
    at CpComponent.webpackJsonp.../../../../../src/app/components/cp/cp.component.ts.CpComponent.ngOnInit (cp.component.ts:28)
    at checkAndUpdateDirectiveInline (core.es5.js:10856)
    at checkAndUpdateNodeInline (core.es5.js:12364)
    at checkAndUpdateNode (core.es5.js:12303)
    at debugCheckAndUpdateNode (core.es5.js:13167)
    at debugCheckDirectivesFn (core.es5.js:13108)
    at Object.eval [as updateDirectives] (CpComponent_Host.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13093)
    at checkAndUpdateView (core.es5.js:12270)
    at callViewAction (core.es5.js:12638)
View_CpComponent_Host_0 @ CpComponent_Host.html:1
proxyClass @ compiler.es5.js:15134
webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError @ core.es5.js:13433
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
(anonymous) @ core.es5.js:4819
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4819
(anonymous) @ core.es5.js:4684
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4684
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onHasTask @ core.es5.js:3903
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:445
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:465
webpackJsonp.../../../../zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:289
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:414
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:236
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap ee42b7cb9aff2ac1b9f9:54
0 @ main.ts:11
__webpack_require__ @ bootstrap ee42b7cb9aff2ac1b9f9:54
webpackJsonpCallback @ bootstrap ee42b7cb9aff2ac1b9f9:25
(anonymous) @ main.bundle.js:1
CpComponent_Host.html:1 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 0, nodeDef: {…}, elDef: {…}, elView: {…}}

## Environment
Windows 10
<pre><code>
Angular version: 4.4.4

**Comment by rossbu** [comment]
with Angular 4.4+ , Similar issue found when saving the source code and url is automatically changed 2-level deep url , for example: 
router in html :
    ```
<div class="navbar-header">
      <nav>
        <a class="navbar-brand" routerLinkActive="active" [routerLink]="['/']">User</a>
        <a class="navbar-brand" routerLinkActive="active" [routerLink]="['/about']">About</a>
        <a class="navbar-brand" routerLinkActive="active" [routerLink]="['/cc']">CreditCard</a>
      </nav>
    </div>
```
ng serve and go to `http://localhost:4200/cc`,  works fine.  then modify/update source code ( any ts file for example , browser automatically reload  the page, url is changed to `http://localhost:4200/cc/cc` and  error occurs with below error stack:
cc:20 GET http://localhost:4200/cc/polyfills.bundle.js net::ERR_ABORTED
13:56:12.832 cc:20 GET http://localhost:4200/cc/styles.bundle.js net::ERR_ABORTED
13:56:12.832 cc:20 GET http://localhost:4200/cc/main.bundle.js net::ERR_ABORTED
13:56:12.833 cc:20 GET http://localhost:4200/cc/vendor.bundle.js net::ERR_ABORTED
13:56:12.833 cc:20 GET http://localhost:4200/cc/inline.bundle.js net::ERR_ABORTED
13:56:12.985 cc:20 GET http://localhost:4200/cc/inline.bundle.js net::ERR_ABORTED
13:56:13.000 cc:20 GET http://localhost:4200/cc/polyfills.bundle.js net::ERR_ABORTED
13:56:13.015 cc:20 GET http://localhost:4200/cc/styles.bundle.js net::ERR_ABORTED
13:56:13.032 cc:20 GET http://localhost:4200/cc/vendor.bundle.js net::ERR_ABORTED
13:56:13.050 cc:20 GET http://localhost:4200/cc/main.bundle.js 404 (Not Found)

env:
Chrome
Angular 4.4.4^

expected result:
keep the same url as  http://localhost:4200/cc  after reloading.

**Comment by jasonaden** [comment]
Please update to the latest version of the CLI. I believe there was a fix for this issue on the CLI. If it still doesn't work, please file against the [Angular CLI](https://github.com/angular/angular-cli/issues) project.
