### ISSUE TITLE
How to get data from one component to another using on click button for update functinality

### ISSUE THREAD

**Issue by anitalpatil** [angular/angular#19636]
Hello,

I am doing one crud application, having one employee-list component there listed all employees list, for particular list entry i have added one edit button this edit should call another edit component by passing the employee id (it should retrieve the particular employee details based on passed id) and should able update the employee data. 

Can any one help me out in resolving the above issue.

Regards 

Anita Patil

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
