### ISSUE TITLE
spirit svg not always displayed 

### ISSUE THREAD

**Issue by istiti** [angular/angular#19638]
In whole my app I always have problem to display my svg correctly, sometimes it show all icon, sometime nothing, and sometimes 50% of them are displayed. Dont' understand why.

here is an example when I come on my page, often icons are displayed (but not always) : 
![image](https://user-images.githubusercontent.com/2789203/31384970-984e02c8-adc1-11e7-8773-a4e52c662fb1.png)

then when I navigate trough my app (lazyloading)  to another menu and come back, here's result: 
![image](https://user-images.githubusercontent.com/2789203/31384927-6615a8f6-adc1-11e7-8021-bf8c32a67af0.png)

another GIF in action: here I just switch  tab (lazy loading) inside my app (FYI this GIF is croped you don't see tab where I clicked, it's outside this image) you can see sometimes it show icons sometimes NOT, don't know how linking svg from spirit works but there is one icons never dissapear  called "#mark_all_as_read" from my symbols.svg however all have same syntax: 
![svg error2](https://user-images.githubusercontent.com/2789203/31385296-0fc55abc-adc3-11e7-919c-260994261eda.gif)

I add a icon X from spirite.symbols.svg  inside  index.html just before <body> tag it is always displayed but when I move on a certain module (lazyloading) where I have this same X icon, someties it is displayed, sometimes not ! 

This behavior is same for partically all my icons I use svg in spirit like this : 
```
<svg class="slds-icon slds-icon-text-default slds-icon_x-small slds-m-right_x-small">
  <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="../assets/icons/utility-sprite/svg/symbols.svg#list"></use>
</svg>
```

and the file that im linking is : [symbols.zip](https://github.com/angular/angular/files/1371953/symbols.zip)

don't know if it's angular or angular-cli on `ng s` dev mode, or browser problem 
here I have plunker https://embed.plnkr.co/dQJIX2lMw8WOl9rQepGX/ but it works everytime  (please switch HOME and ABOUT menu)

MORE INFOS:
here is dom when it works: 
![image](https://user-images.githubusercontent.com/2789203/31423900-a2046596-ae57-11e7-842e-f0acd6b5e61b.png)

here when chrome not displayed it:
![image](https://user-images.githubusercontent.com/2789203/31423938-d748466e-ae57-11e7-92a3-388fc5d174d9.png)

My code of menu in a <ul> list  : https://gist.github.com/istiti/9981daf8bc07f121401733bc6272e4a1 

here's code where icon isn't always displayed 
```
<li routerLinkActive="slds-is-active" [routerLinkActiveOptions]="{exact: true}"
              *ngIf="'ACCOUNTING_WRITINGS' | permissions" class="slds-nav-vertical__item">
            <a [routerLink]="['ecriturecomptable']" class="  slds-nav-vertical__action slds-text-link--reset"
               aria-describedby="entity-header">
              <span class="slds-icon_container slds-icon-utility-open_folder slds-line-height_reset">
                <svg class="slds-icon slds-icon-text-default slds-icon_x-small slds-m-right_x-small">
                  <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="../assets/icons/utility-sprite/svg/symbols.svg#list"></use>
                </svg>
              </span>
              <ng-container i18n>Liste écritures comptable</ng-container>
            </a>
          </li>
```

ans this one where icon seems to be always displayed is only with another ngIf : ` *ngIf="('ACCOUNTING_WRITINGS' | permissions:'WRITE') && ecrituresAVerifier?.length"`

ANOTHER IMPORTANT INFO :
it's very weird , when i navigate to a route my browser make TWO http calls to same symbols.svg file 
  when I remove ` && ecrituresAVerifier?.length` in  one of my <li> browser make correctly only ONE call and all my icons seems to be displayed all the time !  NB:It works on firefox event with this second condition in ngIf

to resume: really wonder why with this second condition in a <li> `&& ecrituresAVerifier?.length` in my ngIf the browser make another call If I remove it it make only one call!

> browsers impacted by this bug?

actually tested on chrome last version
it seems it works on FIREFOX all time !

Browser:
- [last ] Chrome (desktop)

angular version & co:
@angular/cli: 1.4.2
node: 6.11.0
os: win32 x64
@angular/* 4.4.3
typescript: 2.3.4

**Comment by chuckjaz** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by rafajpter** [comment]
I have got the same problem. Problem is just in the Chrome. Any solution for this?

**Comment by HannaBabrouskaya** [comment]
Does anyone know the reason/solution? 
It's weird but when I removed *ngIf from the parent element it started working...
