### ISSUE TITLE
FormGroup - registerControl - ExpressionHasChanged Error

### ISSUE THREAD

**Issue by MarkPerryBV** [angular/angular#19634]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I create a empty FormGroup in a parent component then my child components "add" themselves to the FormGroup using `formGroup.registerControl()`. I expect the status of the `FormGroup` to be `VALID` since the control was added using `registerControl`. Currently I get a `expressionhaschanged` error when NOT in prodmode.

## Expected behavior
- I would not get an error
- The formGroup should be "valid"
- The formControl should be "invalid"
- I would need to manually trigger an update of the formState using `.updateValueAndValidity()".

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/JgIXN8OyAWRGWCdlg5xG?p=preview

## What is the motivation / use case for changing the behavior?
I am building a large forms based application and wish to create mini "formControl" components e.g. myTextboxComponent, myDatePickerComponent, myAgeSelector, etc...

I can then use those components without having to create the full formGroup ahead of time. The components are self registering (with the FormGroup) and self initialising (with data for dropdowns etc...). This means the "parent" component does not need ahead of time knowledge of the form.

## Environment
Angular v4.4.4

Browser:
All browsers

## My attempt at debugging the issue
If it helps I *think* the issue comes down to the second check in debug mode causing the FormGroup to trigger ngModelChanges and subsequently the updateValueAndValidity function updates the correct `formGroup.status` to `INVALID`.

First time we check values the `formGroup.status`  is `VALID` as registering the components `FormControl` has had no effect on its parent. During the debugMode another ngModelChanges cycle is run and then updates the `formGroup.status` to "INVALID" as the child control status is `INVALID`.

**Comment by mlc-mlapis** [comment]
@MarkPerryBV ... *DON'T* mix template and reactive based forms together ... especially there is could be a problem with the order of instantiating of the template based form object.

**Comment by MarkPerryBV** [comment]
I am not mixing template and reactive forms together. I am only using the reactive forms style of forms in my project.

**Comment by mlc-mlapis** [comment]
@MarkPerryBV  ... and what is this: `<form ... #form="ngForm">`?

**Comment by MarkPerryBV** [comment]
@mlc-mlapis I need to do that in order to get the "submitted" state of the form. The property `submitted` only exists on `ngForm` and not `FormGroup`.

**Comment by kara** [comment]
@MarkPerryBV This is working as expected. Because of the lifecycle hook you're using, the group's validity will have changed after it was checked. Try moving your `registerControl` call to `ngAfterViewInit` or using `addControl` instead.
