### ISSUE TITLE
Router Angular4

### ISSUE THREAD

**Issue by VSmirnov17** [angular/angular#19639]
Hello.
I'm developing a navigation service.
When I go from one page of the application to another, I save the address and the position of the scroll:

```
    router.events.filter(e => e instanceof RoutesRecognized)
                    .pairwise()
                    .subscribe((e: [RoutesRecognized, RoutesRecognized]) => {    
                        this.prevUrl    = e[0].url;
                        this.saveScroll(this.prevUrl, window.pageYOffset); 
                    });
```
Everything works well if we go the links. But...
If we go to the page using the browser buttons (forward and backward arrows), then window.pageYOffset(window.scrollY) assigned vallue position scroll future page, rather than the current.
I am hope for your help.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mlc-mlapis** [comment]
@VSmirnov17 ... you filtered `router.events.filter(e => e instanceof RoutesRecognized)` but there are also others ...
