### ISSUE TITLE
Server compiles just by right clicking a file in Windows Explorer

### ISSUE THREAD

**Issue by gaurawerma** [angular/angular#19640]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If you right-click or open any .ts file under src directory of the project triggers compilation in long and sometimes infinite loop. I am using Windows Notepad to open the file.

## Expected behavior
The compilation should get triggered only if I modify any relavant file.

## Minimal reproduction of the problem with instructions
I can reproduce this everytime by runing the skeleton application or any other app by running the following commands

ng new my-first-app
cd my-first-app
ng serve --open

Now when the browser is loaded and the application is up and showing in the UI, I just go to the src folder in windows explorer and right click / open any *.ts file. 

The compiler starts buiding the project in loop (sometimes forever). 
I am sharing the command line log in the attached file

[log.txt](https://github.com/angular/angular/files/1372240/log.txt)

## Environment

@angular/cli: 1.4.5
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
typescript: 2.3.4

Browser:
Chrome
 
For Tooling issues:

- Node version: v6.11.3
- Platform:  Windows 7 Professional

Others:

</code></pre>

**Comment by chuckjaz** [comment]
Please report this in the https://github.com/angular/angular-cli project.
