### ISSUE TITLE
Possible For directive change detection bug.

### ISSUE THREAD

**Issue by samccone** [angular/angular#1964]
### ;TLDR

Change detection failing when removing an element from an array that is displayed using the `For` loop directive

-----------

#### Hypothesis

I am removing an element from a list of items that is shown in the DOM via the `For` directive. There is a dirty checking loop that is run ¿before¿ the element is removed however reaches the check **after** the element has been removed, thus causing the Null lookup issue.

##### Template get lookup failure
https://github.com/tastejs/todomvc/commit/f49caec260b462653706ef98cb8900530da78043#diff-34eab039025c337bc6534509702dbb78R25

##### Removal code
https://github.com/tastejs/todomvc/commit/f49caec260b462653706ef98cb8900530da78043#diff-34eab039025c337bc6534509702dbb78R56

#### Stacktrack
![screen shot 2015-05-18 at 2 33 25 pm](https://cloud.githubusercontent.com/assets/883126/7687387/ee2c280a-fd6a-11e4-8862-6878a02ccce5.png)

(**xref** https://github.com/tastejs/todomvc/pull/1304)

thanks guys :heart:

**Comment by vicb** [comment]
@samccone could you try to submit a smaller snippet that triggers the error. It would really help for debugging the issue. Thanks.

**Comment by samccone** [comment]
alright @vicb bug created!

https://github.com/samccone/angular2-base/blob/sjs/bug/app.ts

you can reproduce by ... 

* cloning the repo
* checking out the branch
* `npm i`
* `npm run dev`
* `python -m SimpleHTTPServer `
* visit localhost:8000
* click on a list item
* check the text to nothing
* press enter

:boom: :bug:

**Comment by vicb** [comment]
No :boom: for me after I've fixed :point_down: obvious :bug:

```
  deactivate(element, todo) {
    store.remove(todo);
  }
```

should be

```
  deactivate(element, todo) {
    this.store.remove(todo);
  }
```

**Comment by samccone** [comment]
whoops :tired_face: 

Sorry I am going to work on this reduced test case some more. 

I am still able to get the error 100% of the time on the original todo example that I put together. There must be something that I am overlooking when I am trying to recreate the issue.

**Comment by vicb** [comment]
unless one of your item is `null` in your original example, your should try to dump it.

**Comment by vicb** [comment]
A good solution might be to add a getter for the todos and check if one of them is null on access.

**Comment by mhevery** [comment]
closing. Reopen with small use case

**Comment by samccone** [comment]
Thanks guys, I will reopen when I am able to reproduce on a smaller example.
