### ISSUE TITLE
"engine" specification for node in package.json.

### ISSUE THREAD

**Issue by EvanCarroll** [angular/angular#19648]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The current specification fails if you run a version of node >7.0.0.

## Expected behavior

It works.. Node doesn't change much. We shouldn't be excluding versions because we don't know they work. We should assume they work, unless we know otherwise. The current practice is not future safe.

## Minimal reproduction of the problem with instructions

Install a new version of node, try to build aio.

## Environment
Node 
For Tooling issues:
- Node version: v8.5.0

**Comment by gkalpak** [comment]
Since this does not affect CI (versions are hard-coded there), maybe we could only enforce the minimum version and just print a warning if the user has a newer one. And possibly throw on CI (just in case).
cc @IgorMinar

**Comment by amcdnl** [comment]
I can testify that this does work w/ Node 8.6

**Comment by gkalpak** [comment]
I was about to create a PR to only print a warning (instead of failing) when the node version is higher than the range specified in `engines.node`, when I realized that this is exactly what we are doing already.
So, there is nothing stopping you from using node `8.x`, except that we can't guarantee that it will work (although it probably will) and you will get a warning message that you are using an unsupported version of node.

@EvanCarroll, are you seeing something different (e.g. the script actually erroring instead of just printing the warning message), or is it that the message is too discouraging (giving the impression that it will not work and you _have_ to install a supported version?

**Comment by gkalpak** [comment]
Closing this since we didn't get any feedback and it already works (i.e. prints a warning but doesn't fail when using a newer node version).

**Comment by EvanCarroll** [comment]
I think it still fails @gkalpak 

```
yarn install
yarn install v1.2.0
$ node -e "if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('Please use Yarn instead of NPM to install dependencies. See: https://yarnpkg.com/lang/en/docs/install/')"
[1/5] Validating package.json...
error angular-srcs@5.0.0-rc.7: The engine "node" is incompatible with this module. Expected version ">=6.9.5 <7.0.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by gkalpak** [comment]
Oh, I see. I thought you meant our `check-env` script would fail, but it is yarn that does.

**Comment by petebacondarwin** [comment]
You can work around this via:

```
yarn install --ignore-engines
```

**Comment by ocombe** [comment]
@petebacondarwin but when you run "yarn setup" you don't choose to use this flag or not :(
I tried with `yarn setup -- --ignore-engines` and ` yarn setup --ignore-engines`, it doesn't work

**Comment by EvanCarroll** [comment]
Is it a good idea to ever not support the latest versions of node? I mean if it doesn't work on the latest version of node, isn't the plan to call that reason for it not working a bug. I'm not even sure what the `engine` is for here. Is angular documented anywhere to prefer or require 6.x? And if we only mean to say that Angular is only tested on Node 6.x is the semantic place for that "engine"?

**Comment by gkalpak** [comment]
@EvanCarroll, this is not about Angular itself. It is about what version of node is used to run the scripts that build and test the documentation app (and related data). We can only guarantee that they work with the version that we use and test on CI. We always try to use the current LTS (so will probably switch to 8.x soon).

Just to be clear, the scripts are most likely to work with the latest, non-LTS version, but we don't test against that, so we can't know for sure.

**Comment by IgorMinar** [comment]
upgrade to node 8 is in progress is part of this PR #20807
