### ISSUE TITLE
Validator behavior is different when using ngModel versus FormControl (attribute versus programmatic validators)

### ISSUE THREAD

**Issue by jsgoupil** [angular/angular#19643]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When creating a control with a `ControlValueAccessor`, Angular will take care of calling my control either if the caller uses a `NgModel` or a `FormControl`. However, the usage of validators in either case follow two separate paths making the creator of a control the need to handle too many cases.

As an example:

    @Component({
        selector: 'tn-input1',
        template: '<input type="text" #input (change)="fnChange(input.value)" /> I have {{ validators?.length || 0 }} validators',
        host: {
        },
        providers: [{
            provide: NG_VALUE_ACCESSOR,
            useExisting: InputCVA,
            multi: true
        }]
    })
    export class InputCVA implements ControlValueAccessor {
        @ViewChild('input', { read: ElementRef })
        input: ElementRef;

        fnChange: Function;
        fnTouched: Function;

        constructor(
            @Optional() @Inject(NG_VALIDATORS) public validators: Array<any>
        ) { }

        public writeValue(obj: any): void {
            this.input.nativeElement.value = obj;
        }

        public registerOnChange(fn: any): void {
            this.fnChange = fn;
        }

        public registerOnTouched(fn: any): void {
            this.fnTouched = fn;
        }
    }

    // ...

    myModel1 = 'value1';
    myFormControl1 = new FormControl('value2', Validators.required);

    // ...

    <div>
        <tn-input1 [(ngModel)]="myModel1" required></tn-input1> {{ myModel1 }}
    </div>

    <div>
        <tn-input1 [formControl]="myFormControl1"></tn-input1> {{ myFormControl1.value }}
    </div>

In the first case, my control will display that I have 1 validator. In the second case, my control will display that I have 0 validators.
However, in both cases the tn-input1 will contain the ng-invalid class because it is marked as required. This is where we get different "paths".

In case 1, the "hidden" FormControl gets its validator injected in the AbstractControl constructor. My validators are set via attributes.
In case 2, the formControl gets its validator from the `FormControlDirective.ngOnChanges`. My validators are set via TypeScript code.

When the control itself wants to do some fancy UI work based on the validators associated to the :host, it is now complicated to handle both cases.

## Expected behavior
Provide a way to get the validators from inside the component. The ones applied to the :host.
The only undocumented solution is to go get the NgControl (https://github.com/angular/angular/issues/17500) like NgControlStatus is doing.

## What is the motivation / use case for changing the behavior?
There is a need to display custom validation based on the component itself. Without doing this NgControl hack, I have to do control compositions and forward validation or formControl to children of a parent control.

## Environment

<pre><code>
Angular version: 4.4.3

</code></pre>

**Comment by kara** [comment]
We ran into this on Material too. There's no great one way to check all the validators the top-level control has, especially because multiple validator functions are eventually composed into one aggregate function with no info about the previous individual validators. This will need a design, but definitely something we should fix.

**Comment by AndrewKushnir** [comment]
This should be supported once there is a way to get the list of validators from AbtsractControl-based classes (such as `FormControl`), so I'm closing this issue in favor of #13461 (the ticket that requests `getValidators` API).
