### ISSUE TITLE
Tour of Heroes tutorial part 6 (HTTP) broken - does not display heroes - response.json().data

### ISSUE THREAD

**Issue by orange00** [angular/angular#19644]
## I'm submitting a...

<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The live example of the official Tour of Heroes tutorial, part 6 (HTTP) is broken. 
You can see the issue if you open the live example in plunker, where you will notice that the heroes are 
not being displayed.

The problem seems to be in the 'hero.service.ts'. It would seem that all occurrences 
of  `response.json().data` should be replaced with `response.json()` (.data seems to no longer be 
needed, and it causes errors).

For example, the following code:
```
  getHeroes(): Promise<Hero[]> {
    return this.http.get(this.heroesUrl)  
               .toPromise()
               .then(response => response.json().data as Hero[])
               .catch(this.handleError);
  }
```
should be replaced with the following code:
```
  getHeroes(): Promise<Hero[]> {
    return this.http.get(this.heroesUrl)
               .toPromise()
               .then(response => response.json() as Hero[])
               .catch(this.handleError);
  }
```

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/19602

**Comment by pavelmorozov** [comment]
Same issue with me and same solution. Though it would be nice to know how this bug happen.

Before find this thread I tried to download example application and run it, and it works fine with line
`
.then(response => response.json().data as Hero[])`

though this not works with application I build myself. The response variable contains different data structure. Is this a problem of backwards compatibility?
