### ISSUE TITLE
Pipe are not working as expected

### ISSUE THREAD

**Issue by leonardosalles** [angular/angular#19657]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I use a data binding expression with a ternary inside my pipe are not called, for example:
```
{{active && active.cpf ? active.cpf : '' | cpf}}
```
In this case I need to change that and use this instead:
```
<span *ngIf="active && active.cpf">{{active.cpf | cpf}}</span>
```
I am not sure if use ternary in data binding are a good solution but in I tought that my pipe should be called and then throw an error if is not possible to parse the value.

## Expected behavior
Pipe should be called even with a ternary inside data binding expression.

## Minimal reproduction of the problem with instructions

Create a pipe to transform a string, import it in a shared module, then import this module in your component module, try to use this pipe with a ternary inside the data binding expression.

## What is the motivation / use case for changing the behavior?

Ternary will make my code more cleaner and I don't need to create another element just to wrap the *ngIf.

## Environment

<pre><code>
Angular version: X.Y.Z

Angular 4.3.3

Browser:
- [X] Chrome (desktop) version Latest
- [X] Chrome (Android) version Latest
- [X] Chrome (iOS) version Latest
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  6.11.3  
- Platform:  Windows 8.1

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Did you try using parenthesis?
```
{{(active && active.cpf ? active.cpf : '') | cpf}}
```

**Comment by leonardosalles** [comment]
@ericmartinezr tried now, sorry for that, never imagined to use parenthesis, my bad! Closing the issue, parenthesis solved my problem. Thank you.
