### ISSUE TITLE
Are you accepting official documentation translations?

### ISSUE THREAD

**Issue by CamiloTerevinto** [angular/angular#19654]
## I'm submitting a...

<pre><code>
[ X ] Documentation issue or request
</code></pre>

## Current behavior
Currently, the Tour of Heroes tutorial (what I'm interested in right now) is only available in English and Chinese.

## Expected behavior
For the Tour of Heroes to be available in Spanish.

## What is the motivation / use case for changing the behavior?
I have met a lot of people in tech jobs that do not speak English at a good enough level, given that I'm from Uruguay. You can easily find tutorials of Angular in Spanish, but they are neither as complete or as easy to follow as the Tour of Heroes. 

I do realize this is not enough motivation for you guys, but since I'm a native Spanish speaker, I'm offering to help.

**Comment by ericmartinezr** [comment]
They have this repo https://github.com/angular/angular-es that was active for a long time. I'm not sure what happened to it now.

cc @Foxandxss

**Comment by CamiloTerevinto** [comment]
@ericmartinezr Thanks, I didn't find that in a quick Google search. I can see that it has not been updated for over an year now, so not sure if that's still current.

**Comment by Foxandxss** [comment]
No, we are not.

**Comment by CamiloTerevinto** [comment]
Ok then. Please do let me know if you start accepting.

**Comment by ericmartinezr** [comment]
@CamiloTerevinto this may interest you https://github.com/angular/angular/issues/20542#issuecomment-345679347
