### ISSUE TITLE
Feature request: rename useExisting to useToken for provider's interface

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#19650]
## I'm submitting a...
<pre><code>[x] Feature request
</code></pre>

## Current behavior
`useExisting` a bit confuses:

```ts
{ provide: ClassA, useExisting: ClassB }
```
I am inclined to interpret this as follows: _when DI sees `ClassA`, it return instance of `ClassB` if it existing, as if we wrote like this_:

```ts
{ provide: ClassA, useClass: ClassB }
```

## Expected behavior
It seems to me that `useToken` describes the essence much more clearly:

```ts
{ provide: ClassA, useToken: ClassB }
```
I am inclined to interpret this as follows: _when DI sees `ClassA`, it will continue to search instance of some class for token `ClassB`_.

**Comment by Toxicable** [comment]
`useExisting` makes much more sense to me than `useToken`.
Since `useExisting` uses an existing token rather than making a new one.
Also `useToken` to me indicates that the value passed is the token but it is not, the `provide` value is the token

**Comment by KostyaTretyak** [comment]
> Also `useToken` to me indicates that the value passed is the token but it is not, the `provide` value is the token

@Toxicable, the fact is that when we write `{ provide: ClassA, useExisting: ClassB }` we passing two tokens: ClassA and ClassB.

See [my answer on SO](https://stackoverflow.com/a/46678735/1716560) and [docs](https://angular.io/api/core/ExistingProvider#how-to-use)

**Comment by Toxicable** [comment]
Sure, since you're just effectively pointing `ClassA` to the value of the token of `ClassB`.
However in this specific statement, the token for this object that will be used in DI is only `ClassA` yet behind the scenes it will use `ClassB` to look up the actual thing to be returned

**Comment by pkozlowski-opensource** [comment]
Agree with the @Toxicable line of thinking. Plus it would be a breaking change.

Thnx for the suggestion but we are going to pass on it.
