### ISSUE TITLE
Q: Define a custom DI token (e.g. appDocumentToken)

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1965]
I see Angular defines some constants/tokens to use internally, e.g. `appDocumentToken`.

I could see this also being useful in applications, specifically for injecting things like version numbers, DOM handles, etc. Imagine the following:

```dart
bootstrap(..., [
  bind(versionNumberToken, toValue: '1.0.0-alpha.5'),
  bind(overlayContainer, toValue: document.getElementById('overlay-container'))
]);
```

```dart
class SomeComponent {
  SomeComponent(@Inject(versionNumberToken) String versionNumber) {
    logger.log('Using super application v$versionNumber');
  }
}
```

(This may already work, if so, this should be in DI's docs if possible)

**Comment by vicb** [comment]
@matanlurey a token can be anything already.

**Comment by matanlurey** [comment]
Thanks! I'll leave this open for documentation additions.

**Comment by mhevery** [comment]
I am going to close this, since I want to keep the number of bugs small so that we don't end up in Issue bankruptcy.
