### ISSUE TITLE
Angular tutorial live example not working

### ISSUE THREAD

**Issue by MickeySegal** [angular/angular#19659]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)

</code></pre>

## Current behavior

The live example on the HTTP page of the Angular tutorial opens the code on Plunker but this fails with an error in the Console: 

> Error: Uncaught (in promise): TypeError: Cannot read property 'slice' of undefined
> TypeError: Cannot read property 'slice' of undefined

## Expected behavior

This used to work without errors.

## Minimal reproduction of the problem with instructions

STEPS TO REPRODUCE:
1.  Go to [https://angular.io/tutorial/toh-pt6]
2.  Click the live example link [https://angular.io/generated/live-examples/toh-pt6/eplnkr.html]
3.  Note that some of the functionality in the app is missing.
4.  Open the Console and note the error message. 
## What is the motivation / use case for changing the behavior?

This used to work and it is helpful to have this working example in the tutorial.

## Environment

<pre><code>
Angular version: Not listed in system.js.config.js (it would be helpful if someone could point out where a version or the call to the latest version is specified - this may be the issue here)

Browser:
- [X] Chrome (desktop) version 61.0.3163.100

</code></pre>

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/19602
