### ISSUE TITLE
Generate the angular2.d.ts file along with documentation

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#1966]
As discussed with @petebacondarwin we would like to generate a complete .d.ts file for angular2. TypeScript roadmap indicates they will include .d.ts bundling in their 1.6 release, but we don't want to wait that long, and also want to have the ability to restrict what we emit to be just the public API surface.

Since we already generate the human-readable API doc, it would be great to produce exactly the same data, in the .d.ts representation instead.

The current file was hand-written, and is published to DefinitelyTyped: 
https://github.com/borisyankov/DefinitelyTyped/blob/master/angular2/angular2.d.ts
so that indicates the format the file should have.

This is probably blocked on moving all the code to TypeScript.

**Comment by petebacondarwin** [comment]
@alexeagle - were the documentation comments in this file taken from the source or hand coded?

**Comment by alexeagle** [comment]
They are copied from the source, with a bit of hand-editing (only removing
the @exportedAs IIRC)

**Comment by petebacondarwin** [comment]
Right. I am working on it today.

**Comment by alexeagle** [comment]
Great! You made quick work of that migration from Traceur to Typescript!
