### ISSUE TITLE
angular 4 documentation for offline use

### ISSUE THREAD

**Issue by octodevelopers** [angular/angular#19660]
Hi,

I have a project developed on a computer without instant internet access,
and I would like to run an offline version of the documentation for the newest angular 4.

Iv'e tried to follow the instructions on https://github.com/angular/angular/tree/master/aio without any luck.

is there another way to get it to work? maybe an update is needed there? 
thanks!

**Comment by gkalpak** [comment]
There is no other way atm. The instructions for building it yourself should work, though.
What commands did you try? What issues did you run into?

**Comment by octodevelopers** [comment]
hi,
i have tried yarn setup-local and got:

> Error: find: no such file or directory: c:/Angular/docs/angular/dist/packages-dist

tried also yarn setup and got:

> Error: EPERM: operation not permitted, symlink 'c:\Angular\docs\angular\aio\tools\examples\shared\node_modules' -> 'c:\Angular\docs\angular\aio\content\examples\ajs-quick-reference\node_modules'
>     at Error (native)
>     at Object.fs.symlinkSync (fs.js:1068:18)
>     at Object.createSymlinkSync (c:\Angular\docs\angular\aio\node_modules\fs-extra\lib\ensure\symlink.js:53:25)
>     at exampleFolders.forEach.exampleFolder (c:\Angular\docs\angular\aio\tools\examples\example-boilerplate.js:67:10)
>     at Array.forEach (native)
>     at ExampleBoilerPlate.add (c:\Angular\docs\angular\aio\tools\examples\example-boilerplate.js:57:20)
>     at Object.yargs.usage.command [as builder] (c:\Angular\docs\angular\aio\tools\examples\example-boilerplate.js:90:73)
>     at Object.self.runCommand (c:\Angular\docs\angular\aio\node_modules\yargs\lib\command.js:193:35)
>     at Object.Yargs.self._parseArgs (c:\Angular\docs\angular\aio\node_modules\yargs\yargs.js:990:30)
>     at Object.get [as argv] (c:\Angular\docs\angular\aio\node_modules\yargs\yargs.js:930:19)
> error Command failed with exit code 1.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>

**Comment by gkalpak** [comment]
`yarn setup-local` assumes you have run `./build.sh` (in the project root directory). You don't need this.
`yarn setup` needs to create some symlinks, so you should run it with administrator privileges on Windows.

**Comment by octodevelopers** [comment]
I did run the **yarn setup** as administrator, then after one hour it seems the installation is stuck:

> yarn run v1.1.0
$ yarn install --freeze-lockfile && yarn ~~check-env && yarn boilerplate:remove
warning jshashes@1.0.6: The engine "browser" appears to be invalid.
warning "@angular/cdk@2.0.0-beta.8" has incorrect peer dependency "@angular/core@^4.0.0".
warning "@angular/cdk@2.0.0-beta.8" has incorrect peer dependency "@angular/common@^4.0.0".
warning "@angular/material@2.0.0-beta.8" has incorrect peer dependency "@angular/core@^4.0.0".
warning "@angular/material@2.0.0-beta.8" has incorrect peer dependency "@angular/common@^4.0.0".
warning "@angular/service-worker@1.0.0-beta.16" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/animations@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/common@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/compiler@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/compiler-cli@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/core@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/http@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-browser@^4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-browser-dynamic@^4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-server@^4.0.2".
$ yarn aio-use-npm && yarn example-use-npm
warning jshashes@1.0.6: The engine "browser" appears to be invalid.
warning "@angular/cdk@2.0.0-beta.8" has incorrect peer dependency "@angular/core@^4.0.0".
warning "@angular/cdk@2.0.0-beta.8" has incorrect peer dependency "@angular/common@^4.0.0".
warning "@angular/material@2.0.0-beta.8" has incorrect peer dependency "@angular/core@^4.0.0".
warning "@angular/material@2.0.0-beta.8" has incorrect peer dependency "@angular/common@^4.0.0".
warning "@angular/service-worker@1.0.0-beta.16" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/animations@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/common@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/compiler@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/compiler-cli@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/core@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/http@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-browser@^4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-browser-dynamic@^4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-server@^4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/router@^4.0.2".
warning "@ngtools/webpack@1.6.0" has unmet peer dependency "enhanced-resolve@^3.1.0".
warning "codelyzer@2.0.1" has incorrect peer dependency "@angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "codelyzer@2.0.1" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "@ngtools/webpack@1.7.2" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "html-webpack-plugin@2.30.1" has unmet peer dependency "webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3".
warning "license-webpack-plugin@1.1.0" has incorrect peer dependency "webpack-sources@>= 1.0.0".
warning "extract-text-webpack-plugin@2.0.0-beta.5" has unmet peer dependency "webpack@^2.1.0-beta.19 || ^2.2.0-rc.0".

**Comment by octodevelopers** [comment]
I opened another terminal and tried again with other yarn command, could you maybe write down the orders of the actions I should preform? (starting from cloning the repo, then going inside the aio/ folder and running yarn with admin, etc.) ?

**Comment by kapunahelewong** [comment]
Hey @octodevelopers here are instructions I recently wrote for people new to contributing to the docs. You might be beyond this but it's worth checking:

# Angular.io local setup

Follow these steps when you are setting up the repo locally for the first time.

**In terminal:**

1. `git clone https://github.com/angular/angular.git` 
1. `cd angular`
1. `yarn` 
1. `cd aio`
1. `yarn setup`
1. `yarn start`
1. Open a new terminal tab or window in the same directory.
1. `yarn docs-watch` in new tab.

**In Chrome:**

1. Go to localhost:4200

**Comment by octodevelopers** [comment]
@kapunahelewong thanks, I opened a new folder and tried your guide.
in step 5 it seems stuck again in:

> E:\Work\Angular\docs\3\angular\aio>yarn setup
yarn run v1.1.0
$ yarn install --freeze-lockfile && yarn ~~check-env && yarn boilerplate:remove
warning jshashes@1.0.6: The engine "browser" appears to be invalid.
warning "@angular/cdk@2.0.0-beta.8" has incorrect peer dependency "@angular/core@^4.0.0".
warning "@angular/cdk@2.0.0-beta.8" has incorrect peer dependency "@angular/common@^4.0.0".
warning "@angular/material@2.0.0-beta.8" has incorrect peer dependency "@angular/core@^4.0.0".
warning "@angular/material@2.0.0-beta.8" has incorrect peer dependency "@angular/common@^4.0.0".
warning "@angular/service-worker@1.0.0-beta.16" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/animations@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/common@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/compiler@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/compiler-cli@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/core@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/http@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-browser@^4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-browser-dynamic@^4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-server@^4.0.2".
$ yarn aio-use-npm && yarn example-use-npm
warning jshashes@1.0.6: The engine "browser" appears to be invalid.
warning "@angular/cdk@2.0.0-beta.8" has incorrect peer dependency "@angular/core@^4.0.0".
warning "@angular/cdk@2.0.0-beta.8" has incorrect peer dependency "@angular/common@^4.0.0".
warning "@angular/material@2.0.0-beta.8" has incorrect peer dependency "@angular/core@^4.0.0".
warning "@angular/material@2.0.0-beta.8" has incorrect peer dependency "@angular/common@^4.0.0".
warning "@angular/service-worker@1.0.0-beta.16" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/animations@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/common@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/compiler@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/compiler-cli@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/core@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/http@~4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-browser@^4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-browser-dynamic@^4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/platform-server@^4.0.2".
warning "ng-pwa-tools@0.0.10" has incorrect peer dependency "@angular/router@^4.0.2".
warning "@ngtools/webpack@1.6.0" has unmet peer dependency "enhanced-resolve@^3.1.0".
warning "codelyzer@2.0.1" has incorrect peer dependency "@angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "codelyzer@2.0.1" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "@ngtools/webpack@1.7.2" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "html-webpack-plugin@2.30.1" has unmet peer dependency "webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3".
warning "license-webpack-plugin@1.1.0" has incorrect peer dependency "webpack-sources@>= 1.0.0".
warning "extract-text-webpack-plugin@2.0.0-beta.5" has unmet peer dependency "webpack@^2.1.0-beta.19 || ^2.2.0-rc.0".

any idea?

**Comment by gkalpak** [comment]
No idea :( I can `yarn setup` on Windows without an issue.

**Comment by kapunahelewong** [comment]
Yeah...I'm not sure either.

**Comment by octodevelopers** [comment]
what versions of node, yarn and npm do you have installed?
I've updated recently to node v8.7.0, npm v5.4.2 and yarn v1.2.1

**Comment by petebacondarwin** [comment]
@octodevelopers - I am confident that yarn v1.1.x does not work for our current `yarn.lock` file, so maybe it doesn't work for v1.2.1 either?
That being said, I don't see errors in the print-out you provided, only warnings which are expected, I believe.

**Comment by kapunahelewong** [comment]
@octodevelopers I have:

- node v6.10.2
- yarn v0.22.0
- npm v5.4.2

In addition to what @petebacondarwin said, I think node version 8+ causes an issue. My versions work though.

**Comment by octodevelopers** [comment]
ok, changed everything to be like @kapunahelewong  versions,
then when I tried to **yarn start** I got the error:

 

> ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
> Module build failed: Error: ENOENT: no such file or directory, scandir 'c:\4\angular\aio\node_modules\node-sass\vendor'
>     at Error (native)
>     at Object.fs.readdirSync (fs.js:952:18)
>     at Object.getInstalledBinaries (c:\4\angular\aio\node_modules\node-sass\lib\extensions.js:124:13)
>     at foundBinariesList (c:\4\angular\aio\node_modules\node-sass\lib\errors.js:20:15)
>     at foundBinaries (c:\4\angular\aio\node_modules\node-sass\lib\errors.js:15:5)
>     at Object.module.exports.missingBinary (c:\4\angular\aio\node_modules\node-sass\lib\errors.js:45:5)
>     at module.exports (c:\4\angular\aio\node_modules\node-sass\lib\binding.js:15:30)
>     at Object.<anonymous> (c:\4\angular\aio\node_modules\node-sass\lib\index.js:14:35)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (c:\4\angular\aio\node_modules\sass-loader\lib\loader.js:3:14)
>  @ ./src/styles.scss 4:14-187
>  @ multi ./src/styles.scss
> 
> webpack: Failed to compile.

ideas ? :(

**Comment by gkalpak** [comment]
Try `npm rebuild node-sass`.

**Comment by octodevelopers** [comment]
@gkalpak I did everything from @kapunahelewong 's instructions after cleaning up the environment and **it worked!** (node v6.10.2, yarn v0.22.0, npm v5.4.2)

now I hope that I could move it to the no network computer successfully..

I think that if there was an easier way to host a local angular.io (with the docs, api, tour of heroes, etc.) it could be very appreciated. It could help many developers to have the angular documentation "online" no matter what. 
Also, the site itself can be a nice example for an Angular developed with high standarts website.

maybe for the Angular 5 release, a quick way to have angular.io locally would be released as well. 😃 

Thanks for all the help! 🎉

**Comment by gkalpak** [comment]
Glad you were able to get it work.
In case it wasn't clear, @kapunahelewong's instructions are for authors that want to write docs for angular.io (e.g. API docs or guides, tutorials, etc). You don't need all those steps just for having a local version of the docs. All you need for that is:

1. `git clone https://github.com/angular/angular.git`
2. `cd angular/aio`
3. `yarn build`
4. `yarn http-server dist [-p <port>]`

Obviously, we can't skip steps (1) and (2) and after that it is just one command to build the site and one command to serve it. After step (3), you will have everything you need in the `angular/aio/dist/` directory. If you don't want to use our local `http-server`, you can copy the `dist/` directory anywhere and serve it using any static webserver.

I am not sure how much simpler than that we can make it.

##
Regarding tools versions:
- You can see the version of `node` and `yarn` we are using (and tting on our CI) [here][1]. This doesn't imply that other versions won't work, but we haven't tested with them.
- We have specified "accepted" ranges in the `engines` property of our [package.json][2] and there is [a script][3] (which runs before most commands) that checks your environment based on that. Of course, this requires node dependencies have been installed yet, so it is not very useful if your very first `yarn install` crashes.

If you have ideas on how we could improve the situation for people that want to build the docs themselves, please feel free to share your ideas (or even submit a PR :smiley:).

##
<sub>Closing this, since you were able to run the build successfully.</sub>

[1]: https://github.com/angular/angular/blob/653a211743ce0b9b59f7cf14115a3344f7952e70/scripts/ci/env.sh#L37-L38
[2]: https://github.com/angular/angular/blob/653a211743ce0b9b59f7cf14115a3344f7952e70/aio/package.json#L62-L65
[3]: https://github.com/angular/angular/blob/653a211743ce0b9b59f7cf14115a3344f7952e70/aio/package.json#L38
