### ISSUE TITLE
ASP.NET CORE 2 + ANGULAR 4: NodeInvocationException: Prerendering failed because of error: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by gmattworld** [angular/angular#19667]
I am trying to use ngx-chips for tag-input, but I am having this issue with importing BrowserAnimationsModule.

 
On importing BrowserAnimationsModule, I get the error below:
 
    An unhandled exception occurred while processing the request.

    NodeInvocationException: document is not defined
    ReferenceError: document is not defined
 

Once I comment BrowserAnimationsModule in import under app.module.shared.ts, my app works normal but once I uncomment it, I come up with the same error.

Please how can I trash this, I have been working on this for more than 4days.
Or suggest any other angular 4 tag-input library
I am using ASP.NET Core 2 SPA Template.

Thanks...

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/15098
https://github.com/angular/angular/issues/18635

**Comment by tbosch** [comment]
@ericmartinezr Thanks for the links.

@gmattworld which version of the libraries are you using? Could you verify that you are using versions where the above bugs have been fixed?

**Comment by fhinchey** [comment]
@nawabanjum why would you want to take off pre-rendering. Isn't that a good performance boost?
