### ISSUE TITLE
Create public API doc for pipes

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#1967]
Currently, we have a top-level entry exported, but no public docs.

**Comment by petebacondarwin** [comment]
See https://github.com/angular/angular/blob/master/modules/angular2/pipes.js

If you do a search for `@exportedAs angular2/pipes` then you find all the things that "ought" to be exported there.  (These `@exprtedAs` tags are no longer used and can be removed but provide pointer to what should be exported here).
