### ISSUE TITLE
Write Html content in x -axis and add value in the bar graph

### ISSUE THREAD

**Issue by blackwill123** [angular/angular#19679]
I want to write html content in x-axis eg using of br tags. so if i write br tag then it is displaying br tag in the graph.  I also want to write custom data in bar. see the value  showing in tha bar eg 231k and etc.  I want to write in the x-axis like product removal <br> date: 27/01/2017
![screenshot from 2017-10-12 12-29-49](https://user-images.githubusercontent.com/30776637/31483409-deffd3d4-af49-11e7-9f26-44b6beb6e350.png)

**Comment by ericmartinezr** [comment]
??

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
