### ISSUE TITLE
Can I dynamically change the deploy url when app start ? 

### ISSUE THREAD

**Issue by wuzhouyang** [angular/angular#19678]
I know that I can use the angular-cli to config the deploy-url like `--deploy-url http://xxxxxxx/`, but when I want to change the deploy-url I must to build again. I want to write somethings global like 
<pre><code>
<script type="text/javascript">  
    window['setting'] = {
      'siteurl':'https://xxxxxxxx/'
    }
</script>
</code></pre>
in the root html. And Can I set the deploy-url use the already exist variable when the app start so that I can change the url without build again?

**Comment by mohammedzamakhan** [comment]
You should create this issue in https://github.com/angular/angular-cli repo
