### ISSUE TITLE
Tutorial Chapter 7 - HTTP API broken by change to in-memory-web-api v0.5.0 (5 October 2017)

### ISSUE THREAD

**Issue by ChronosWS** [angular/angular#19676]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When going through Chapter 7 of the Tour of Heroes tutorial, the getHeroes() implementation of hero.service.ts does not return any heroes.

```
getHeroes(): Promise<Hero[]> {
  return this.http.get(this.heroesUrl)
             .toPromise()
             .then(response => response.json().data as Hero[])
             .catch(this.handleError);
}
```

This is because of the following change as indicated on the in-memory-web-api GitHub:

HTTP response data no longer wrapped in object w/ data property

As of v0.5.0 (5 October 2017), the dataEncapsulation configuration default changed from false to true. The HTTP response body holds the data values directly rather than an object that encapsulates those values, {data: ...}. This is a breaking change that affects almost all existing apps!

## Expected behavior
It should return heroes.  Change to the documentation as follows:

`.then(response => response.json().data as Hero[])`

should be

`.then(response => response.json() as Hero[])`

Same applies to getHero(id: number) ...

## What is the motivation / use case for changing the behavior?

Tutorial should work in the "live environment" case, which is using bleeding edge versions of the in-memory-web-api

## Environment
"live environment" on plinkr.co, as linked by the tutorial.

<pre><code>
Angular version: X.Y.Z

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/19602
