### ISSUE TITLE
DecimalPipe uses the syntax `| number`. Rename either the class or the syntax for consistency.

### ISSUE THREAD

**Issue by adamdport** [angular/angular#19689]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Class is called `DecimalPipe` but uses the `| number:'1.2-3'` syntax

## Expected behavior
To maintain consistency, either 
1. rename the class to `NumberPipe`, **or**
1. rename the syntax to `| decimal:'1.2-3'`

## What is the motivation / use case for changing the behavior?
If I want to transform something from outside my template, I need to import the pipe. One would expect to import "NumberPipe". It's strange to call the class something different.

## Environment

<pre><code>
Angular version: 4.4.4

**Comment by vicb** [comment]
This would be a breaking without a lot of added value

> If I want to transform something from outside my template, I need to import the pipe. One would expect to import "NumberPipe". It's strange to call the class something different.

We will actually export the date and number formatting functions used by the pipe so that you can also use them in your code. Using the pipe is not the correct way to do that.

**Comment by adamdport** [comment]
@vicb is there a ticket to track that exporting of functions?
