### ISSUE TITLE
Angularjs SoundManager progressbar issue: Clicking on the progress bar making the player to start from the begining (only in Chrome)

### ISSUE THREAD

**Issue by RameshNaikAspect** [angular/angular#19680]
Bug report: 
## Current behavior
On Angularjs SoundManager2 player If i click on the progress bar then it starts playing from the beginning (**Only in Chrome.** In Firefox this is working fine) 

## Expected behavior
It should start playing from the selected location(time)

## Minimal reproduction of the problem with instructions
We can always reproduce it by playing any **query related url**  
ex: Playing urls like in soundmanager2 https://myown-cloud.net/Adapter/vm/get?key=vm/4700&filename=ovapd229966af22b9sdccd8aagsa8c9f11e7050.wav&Authorization=Bearer%20c53a3b9aa-4f58-47ag5-a0f6f-f14d905ad6789

## What is the motivation / use case for changing the behavior?
User can click on the progress bar to play from the specific time. 

## Environment
Angular version: angular.version.full:"1.4.1"

Browser:
Chrome (desktop) version XX
Version 61.0.3163.100 (Official Build) (64-bit)
 
For Tooling issues:
- Node version: v6.10.2
- Platform:  Windows 

Others:
I posted this issue in couple of forums but not yet got any solutions
https://github.com/scottschiller/SoundManager2/issues/170
https://github.com/perminder-klair/angular-soundmanager2/issues/69

Hope i will get the solution.

**Comment by trotyl** [comment]
Wong repo, this is Angular, not AngularJS.

https://github.com/angular/angular.js

**Comment by gkalpak** [comment]
This is not even an AngularJS issue. It is an issue with the 3rd-party library you are using, so you should report this on _their_ bug tracker/repo.

**Comment by RameshNaikAspect** [comment]
Oh ok will try in other forum. 
Thank you.
