### ISSUE TITLE
Cli build should support loading modules with *.tsx extension.

### ISSUE THREAD

**Issue by majo44** [angular/angular#19691]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
ng build/serve is throwing: `Module not found: Error: Can't resolve error` 
when .ts module is importing the .tsx module.  

## Expected behavior
For compiler there should not be difference in extension of module. 

## Minimal reproduction of the problem with instructions

1. call `ng new testproject`
2. cd testproject
3. rename src\app\app.component.ts to src\app\app.component.tsx
4. add to tsconfig.json compilerOptions
    "jsx": "react",
    "jsxFactory": "h"
5. call `ng build`

As a result I got:
```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './app.component' in 'c:\temp\testproject\src\app'
resolve './app.component' in 'c:\temp\testproject\src\app'
  using description file: c:\temp\testproject\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: c:\temp\testproject\package.json (relative path: ./src/app)
    using description file: c:\temp\testproject\package.json (relative path: ./src/app/app.component)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        c:\temp\testproject\src\app\app.component doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        c:\temp\testproject\src\app\app.component.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        c:\temp\testproject\src\app\app.component.js doesn't exist
      as directory
        c:\temp\testproject\src\app\app.component doesn't exist
[c:\temp\testproject\src\app\app.component]
[c:\temp\testproject\src\app\app.component.ts]
[c:\temp\testproject\src\app\app.component.js]
[c:\temp\testproject\src\app\app.component]
 @ ./src/app/app.module.ts 9:0-47
 @ ./src/main.ts
 @ multi ./src/main.ts
```

## What is the motivation / use case for changing the behavior?
The tsx is providing just extended syntax sugar, which can be used for different porpoises. In my case I'm using mono-repo approach and I'm delivering part of components as web-components where I'm using jsx/tsx.  

## Environment

<pre><code>
Angular version: 5.0.0-rc1
@angular/cli: 1.5.0-beta.4
 
For Tooling issues:
- Node version: v6.11.0
- Platform:  Windows

Others:

</code></pre>

**Comment by josephliccini** [comment]
We also from time to time have to integrate with React components.  `@ngtools/webpack` seems to work fine with `.tsx` in Angular 4 and CLI 1.3.X but I have not tried the new versions of these yet.

**Comment by tbosch** [comment]
Hello, could you reopen this issue in the cli repository?
See https://github.com/angular/angular-cli.
