### ISSUE TITLE
Custom form control in template-driven form doesn't apply correctly initial value

### ISSUE THREAD

**Issue by dobrevad** [angular/angular#19692]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have a custom form control 'counter-input' used in a template-driven form.
I add ngModel on the counter-input.
The counter-input component internally sets an initial value if no value is passed in through ngModel. During initialization FomControl.setValue is called once with the expected value e.g. FormControl.setValue(3). Right after (and before the page is loaded) there's a phantom second call to setValue with "". This results in a inconsistent view and form model. The view shows 3 but the form.model will be empty.

## Expected behavior

The initial value is the one internally set by the component if nothing is provided through the ngModel binding.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/kLeZDaB1HnzUFBU2h8Wk?p=preview
See how the form.value is
{
  "counter": ""
}

But the counter view shows 3.

If instead we had [(ngModel)]="myValue" where myValue is not defined this will result in a form.value: {}
 and view showing 3. This is again not expected given that in the implementation of the ControlValueAccessor writeValue(value: any) method I explicitly check if(!!value)

## Environment

<pre><code>
Angular version: 5.12

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Mac, Linux

Others:

</code></pre>

**Comment by dobrevad** [comment]
This works correctly in reactive forms. The issue is specific to template-driven ones.

**Comment by kara** [comment]
It looks like the reason they're not in sync is that you're only setting `counterValue` if the value coming through `writeValue` is truthy. The top level ngModel determines the value of the component, so given that it's unbound, its value in the model is `''`. Because it's not truthy, the inner `counterValue` variable isn't updated, so it remains 3. 

It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
