### ISSUE TITLE
@Attribute annotation not working

### ISSUE THREAD

**Issue by aomahony** [angular/angular#1969]
I have this code for my component:

```ts
/// <reference path="../typings/angular2/angular2.d.ts" />

import {Component, View, Attribute} from 'angular2/angular2'

@Component({
	selector: "sub-component",
	properties: {
		title: 'title',
		name: 'name'
	}
})

@View({
	template: "<div>This is the title: {{ title }} and the name is {{ name }}</div>"
})

export class SubComponent {
	title: string
	name: string
	
	constructor(@Attribute('title') title: string, @Attribute('name') name: string) {
		this.name = "Ethan"
	}
}
```

I'm running it in Chrome, and when I run it, I get this error:

```
Potentially unhandled rejection [2] No provider for String! (SubComponent -> String)
```

Looks like it's complaining about this line in the Javascript: __metadata('design:paramtypes', [String, String])

**Comment by aomahony** [comment]
Apologies, the first line (with the triple forward slash) wasn't fully copied.  Here it is:

<reference path="../typings/angular2/angular2.d.ts" />

**Comment by vicb** [comment]
I think it should be `String`

also note that :
- the type is not required here `constructor(@Attribute('title') title, @Attribute('name') name)`
- it can not be used to set the attribute

**Comment by mhevery** [comment]
working as intended
