### ISSUE TITLE
Array and nested object params with useAnimation

### ISSUE THREAD

**Issue by elclanrs** [angular/angular#19690]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Cannot pass arrays or nested objects as params with `useAnimation`.

## Expected behavior

Should allow array and nested object params.

## Minimal reproduction of the problem with instructions

First, I defined the animation expecting an array of offsets:

```
const slideInAnimation = animation([
  style({ transform: 'translateX(100%)' }),
  animate('.75s', keyframes([
    style({ transform: 'translateX(0)', offset: '{{ offsets[0] }}' }),
    style({ transform: 'translateX(3%)', offset: '{{ offsets[1] }}' }),
    style({ transform: 'translateX(0%)', offset: '{{ offsets[2] }}' }),
  ]))
]);
```

And when I use it it doesn't work:

```
useAnimation(slideInAnimation, { params: { offsets: [.5, .8, 1] } }); // cannot pass array?
```

I also tried passing an object with numeric keys, like `{ params: { offsets: { 0: .5, 1: .8, 2: 1 } }` and then using `offset.0` instead of `offset[0]` but no luck.

## Environment

<pre><code>
Angular version: 4.4.4

Browser:
- [x] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.2  
- Platform:  macOS Sierra

**Comment by matsko** [comment]
OK I will add this to the work queue. Thank you @elclanrs for reporting it.

**Comment by PoiScript** [comment]
@matsko May I ask how much progress have you made about this feature?
