### ISSUE TITLE
Binding required attribute doesn't update after required set from true to false and hiding the control

### ISSUE THREAD

**Issue by debslord** [angular/angular#19696]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have a form that hides and shows fields and sets fields to be required depending on values of other fields.  However if a field is set to be required and then a value entered on another field results in this changing to false and the control is then hidden with ngIf then the control still thinks it is required.

The issue appears to be around the combination of required and ngIf.  As if I remove the ngIfs it works fine swapping between the different addresses.  

Looking at the form object with the controls, the errors on the control still says it is required.  So it would appear that it doesn't update the required field on a control if it is hidden from the screen - despite it still being in the component on the form object.  

## Expected behavior
The control should only be required if the requited attribute is set to true - no matter what the previous value of this required field was nor whether the field is visible.

## Minimal reproduction of the problem with instructions
I have done a plunker with a basic form hiding and showing an address field and changing it's required property - you can see the save button does not enable if you click home and then work (despite entering the name and work address it thinks the home address is also required)

**Please see plunker below for issue:  
https://plnkr.co/G2Ho4Ufvz39b1IGxCEHF**

** ***UPDATE*** **
This issue is due to the control being hidden before the required update has been changed.  It works if I use a timeout to update the required binding and then hide the controls.  This is by no means a solution!  I don't think I can use detect changes as by this point the control is already hidden and so it will never update the required binding.  

The plunker shows the workaround which is far from ideal -
https://plnkr.co/OjDYzLSM7L0P4oNSiFKb

## What is the motivation / use case for changing the behavior?

Hiding/showing and changing required attribute on fields depending on other user input is needed across multiple scenarios for forms

## Environment

<pre><code>
Angular version: X.Y.Z
@angular/forms": "^4.2.4",

Browser:
- Chrome (desktop) 
 
For Tooling issues:
- Node version: v8.1.4
- Platform:  Windows

**Comment by mlc-mlapis** [comment]
@ebslord ... you probably conditionally link both inputs and evaluation of their validations so if you switch the radio button for one type ... then CD runs once but it is not enough to refresh the conditionally related validation the the second type. You can see the effect if you run the second CD like:
```
setTimeout(() => {
      this.cdr.detectChanges()
    }, 500);
```

**Comment by debslord** [comment]
Thanks for the reply @mlc-mlapis 
Sorry I'm not sure I understand what you mean.  Do you have an example of how I could get this working?
Thank you!

**Comment by mlc-mlapis** [comment]
@debslord ... try to read about `Change Detection` (CD) topic first ... `this.cdr` -> `ChangeDetectorRef` and is taken through DI in the constructor. https://angular.io/api/core/ChangeDetectorRef

**Comment by debslord** [comment]
Thanks for the link.  I did have a quick look after your first message.  Been able to now have a better look and I have tried implementing the detect changes call with a refresh button which obviously wouldn't be ideal in production but I just wanted to see if it worked.  However it doesn't make any difference - unless I have implemented it wrong.  Any advice would be much appreciated!

https://plnkr.co/Q3DsaPkvh8A6o9Vc2XEJ

The issue seems to be around the ngIf as if I remove this on the fields it is fine.

**Comment by trotyl** [comment]
I'm wondering how could Angular not throwing error for using `NgModel` in reactive forms, this should be a bug for letting this code run.

**Comment by debslord** [comment]
Thanks @trotyl I have updated both plunkers now to reflect this change and removed NgModel directive. I will also read a bit more into the different forms in angular as seems a bit of a long way round setting all the control values in the code and then translating them back on save. So I'll have a look if one of the other form modules is more appropriate perhaps and involves less lines of code for a simple edit and save.  

The original issue of the required attribute not updating for controls hidden with ngIf is still happening

**Comment by debslord** [comment]
Not sure if anyone else has come across this but found another better solution than my previous one (which I found actually still had errors)
 
Instead I am now using
**To set the required property:**
    this.heroForm.controls.homeAddress.setValidators(Validators.required);     

**To clear the required property**
      this.heroForm.controls.homeAddress.clearValidators();

**Run after the set/clear**
    this.heroForm.controls.homeAddress.updateValueAndValidity();

Then there is no need for a timeout and the same variable can be used for the required and ngIf to hide/show the control in the HTML.

**Comment by kara** [comment]
It looks like in the original plunker, you're mixing template-driven and reactive strategies, which can often have unexpected results. Generally, if you're using the reactive form directives, we recommend using a more imperative approach using `valueChanges` and `setValidators`, as opposed to mixing them with declarative strategies like `*ngIf` and template bindings to validator directives. From your last comment, it looks like you've come to the same conclusion. 

It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

**Comment by debslord** [comment]
Thanks @kara I am still getting to grips with it all but it's slowly making more sense.  I thought I had got it working much better using setValidators.  However you mention not mixing them with *ngIf, which I am still using to hide/show the controls.  Can you please point me in the direction of a demo or documentation explaining how I should be hiding/showing the controls in a situation like this? It would be much appreciated - thank you!
