### ISSUE TITLE
NG 5.0.0-rc.2: NGC throws error for closures in static methods

### ISSUE THREAD

**Issue by Eddman** [angular/angular#19698]
## I'm submitting a...
<pre><code>[X] Bug report  
</code></pre>

## Current behavior
For class that contains a static method that uses an arrow function in it the NGC throws an error:
```
Error: Error: .../nonce.generator.ts:5:1: Error encountered in metadata generated for exported symbol 'NonceGenerator': 
 .../nonce.generator.ts:18:22: Metadata collected contains an error that will be reported at runtime: Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function.
  {"__symbolic":"error","message":"Function call not supported","line":17,"character":21}
    at node_modules/@angular/compiler-cli/src/metadata/collector.js:663:27
    at Array.forEach (native)
    at validateMetadata (node_modules/@angular/compiler-cli/src/metadata/collector.js:651:42)
    at MetadataCollector.getMetadata (node_modules/@angular/compiler-cli/src/metadata/collector.js:508:17)
    at LowerMetadataCache.getMetadataAndRequests (node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:262:39)
    at LowerMetadataCache.ensureMetadataAndRequests (node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:208:27)
    at LowerMetadataCache.getMetadata (node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:200:21)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataForSourceFile (node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:231:38)
    at TsCompilerAotCompilerTypeCheckHostAdapter.BaseAotCompilerHost.getMetadataFor (node_modules/@angular/compiler-cli/src/compiler_host.js:68:29)
    at StaticSymbolResolver.getModuleMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:31563:62)
```

## Expected behavior

NGC will compile without errors.

## Minimal reproduction of the problem with instructions
Any class that contains a static method (public as well as private) that uses an arrow function like this one:
```typescript
import {Observable} from 'rxjs/Observable';
import {defer} from 'rxjs/observable/defer';
import {of as observableOf} from 'rxjs/observable/of';

export class NonceGenerator {

    public static generateNonce(): Observable<string> {
        return defer(() => { <--------------------------------
            let guidResponse = '';
            // Generation code...
            return observableOf(guidResponse);
        });
    }
}
```
My `tsconfig.json`:
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": false,
        "declaration": true,
        "listFiles": true,
        "sourceMap": false,
        "skipLibCheck": true,
        "lib": [
            "es6",
            "dom"
        ],
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": true,
        "alwaysStrict": true
    },
    "files": [
        "./public_api.ts"
    ],
    "angularCompilerOptions": {
        "annotateForClosureCompiler": true,
        "strictMetadataEmit": true,
        "flatModuleOutFile": "index.js",
        "flatModuleId": "my-module",
        "skipTemplateCodegen": true
    }
}
```

## Environment

<pre><code>Angular version: 5.0.0-rc.2
 
For Tooling issues:
- Node version: v6.11.4
- Platform:  Linux
</code></pre>

**Comment by tbosch** [comment]
This is related to your setting of `strictMetadataEmit`. If you set this to false this error will disappear. Keeping the bug open for @chuckjaz to decide whether this works as intended.

**Comment by Delagen** [comment]
The same error for generic Promise types
{"__symbolic":"error","message":"Could not resolve type","line":23,"character":69,"context":{"typeName":
"Promise"}}

**Comment by Eddman** [comment]
@tbosch Intended? :flushed: So it is intended not to compile valid arrow functions :laughing:?

**Comment by chuckjaz** [comment]
This is intended behavior when you request `strictMetadataEmit`.

The compiler is reporting that metadata was written that would report an error if it was used in a decorator. In this case the method looks like a [macro function](https://angular.io/guide/metadata#macro-functions-and-macro-static-methods) usable inside a decorator (such as [`RouterModule.forRoot()`](https://github.com/angular/angular/blob/master/packages/router/src/router_module.ts#L139)) but it contains an error that will be reported by `ngc` if it is used.

Without `strictMetadataEmit` this error is recorded in the metadata and as long as no one tries to use it in a decorator no error is ever reported.

The purpose of `strictMetadataEmit` is to catch when errors sneak into a metadata that would normally not be reported until the metadata is used. It is very conservative reporting an error when something looks like it could be used in metadata.

This method is obviously not intended for use in a decorator so this error is spurious but the compiler doesn't have enough information to decide this.

You have two options here. First you can change it so it doesn't look like a macro function such as:

```ts
public static generateNonce(): Observable<string> {
  const result = defer(() => {
     let guidResponse = '';
        // Generation code...
         return observableOf(guidResponse);
     });
  return result;
 }
```

which is a bit awkward and introduces a variable for no reason and probably will eventually be refactored back to remove the apparent unnecessary `result`.

The recommended approach is to add `@dynamic` the the function's comment such as:

```ts
// @dynamic
public static generateNonce(): Observable<string> {
  return defer(() => {
     let guidResponse = '';
        // Generation code...
         return observableOf(guidResponse);
     });
 }
```

The error will still be recorded in the metadata but `strictMetadataEmit` will no longer report it as it marks the method as intended for runtime (e.g. dynamic behavior), not static compiler evaluation.

The `@dynanmic` can be anywhere in the method comment but probably should be included at the end such as,

```ts

/**
  * ...
  * @returns an observable  stream of one unique number that will not repeated on subsequent
  * calls (a nonce).
  * @dynamic
  */
public static generateNonce(): Observable<string> {
  return defer(() => {
     let guidResponse = '';
        // Generation code...
         return observableOf(guidResponse);
     });
 }
```

**Comment by mlc-mlapis** [comment]
@chuckjaz ... there is a similar problem with `APP_INITIALIZER` and an exported function for a related provider where without `// @dynamic` on `@NgModule` it is not possible to compile (ngc) when `strictMetadataEmit=true`. ** Do you think that this intended behaviour? ** Following code with `APP_INITIALIZER` is a correct and the only way how to write the code.

```
export function appConfigServiceFactory (config: AppConfig): () => void {
	return () => config.load().then(...);
}
```
```
// @dynamic
@NgModule({
	...,
	providers: [
		AppConfig,
		{
			provide: APP_INITIALIZER,
			useFactory: appConfigServiceFactory,
			deps: [AppConfig],
			multi: true
		}
	],
	...
})
export class AppModule {...}
```

**Comment by Eddman** [comment]
@chuckjaz I'm unable to make it work with `@dynamic`... It is still failing the `ngc` with the same message.

**Comment by dominique-mueller** [comment]
In our case, adding `@dynamic` to the class containing the static methods worked.

**Comment by Eddman** [comment]
@dominique-mueller Indeed, it has to be on the class level for some reason.

**Comment by jainankit102** [comment]
> @chuckjaz ... there is a similar problem with `APP_INITIALIZER` and an exported function for a related provider where without `// @dynamic` on `@NgModule` it is not possible to compile (ngc) when `strictMetadataEmit=true`. **Do you think that this is intended behavior?** Following code with `APP_INITIALIZER` is correct and the only way how to write the code (Angular 5.0.5).
> 
> ```
> export function appConfigServiceFactory (config: AppConfig): () => void {
> 	return () => config.load().then(...);
> }
> ```
> ```
> // @dynamic
> @NgModule({
> 	...,
> 	providers: [
> 		AppConfig,
> 		{
> 			provide: APP_INITIALIZER,
> 			useFactory: appConfigServiceFactory,
> 			deps: [AppConfig],
> 			multi: true
> 		}
> 	],
> 	...
> })
> export class AppModule {...}
> ```

I have also have a same thing... also facing the same problem. Is there any workaround for this?

it would be great help. Thanks in advance.

**Comment by Polyterative** [comment]
still having issues when trying to compila a library with static code in a class

**Comment by internalsystemerror** [comment]
@Polyterative try adding dynamic to the class (above the injector). This seemed to be my issue.
