### ISSUE TITLE
docs(API): bug with link builder on angular.io

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#19701]
## I'm submitting a...

<pre><code>[x] Bug report
</code></pre>

## Current behavior
From [FormGroup](https://angular.io/api/forms/FormGroup#members) API:
> registerControl(name: string, control: AbstractControl): AbstractControl
Registers a control with the group's list of controls.
>
>This method does not update value or validity of the control, so for most cases you'll want to use **FormGroup** instead.

See bold **FormGroup**

## Expected behavior
Should be:
>This method does not update value or validity of the control, so for most cases you'll want to use **addControl()** instead.

Other links are also incorrect.

**Comment by gkalpak** [comment]
The link builder is fine. The links are wrong 😛
Fixed as part of #19709.

**Comment by KostyaTretyak** [comment]
Thank you!
