### ISSUE TITLE
Fragment "#fragment" should not trigger a wildcard redirect route in routes

### ISSUE THREAD

**Issue by r-oconnor** [angular/angular#19708]
## I'm submitting a...

<pre><code>
[  ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[  ] Feature request
[  ] Documentation issue or request
[  ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If I have routes:
<pre><code>
[
    { path: "player/:id", component: PlayerComponent, canActivate: [MyAuthGuard], data: { Admin: [MyAuthGuard.IsAdmin] } },
    { path: "setup", pathMatch: "full", component: SetupComponent, canActivate: [MyAuthGuard], data: { Admin: [MyAuthGuard.IsAdmin] } ),
    { path: "**", redirectTo: "setup"}
], { useHash: false }
</pre></code>

And a fragment activated by a button tag like this: 

<pre><code>
 [routerLink]="['/']" fragment="info"
</pre></code>

And fragment subscription code like so:

<pre><code>
export class PlayerComponent implements AfterViewChecked, OnDestroy {

    routeFragmentSubscription: Subscription;

    constructor(private route: ActivatedRoute, private router: Router) { }
    
    ngAfterViewChecked() {
        this.routeFragmentSubscription = this.route.fragment.subscribe(fragment => {
            if (fragment) {
                let element = document.getElementById(fragment);
                if (element) {
                    element.scrollIntoView();
                }
            }
        });
    }

    ngOnDestroy() {
        this.routeFragmentSubscription.unsubscribe();
    }
}
</pre></code>

Then, while at the route "player/112" I click that button and the route "player/112#info" triggers the wildcard and redirects to "setup#info".

## Expected behavior
With the above setup, I should be able to click the button and have the route remain "player/112#info" and have the page scroll to the id of the fragment in the DOM.

## Environment

<pre><code>
Angular version: 
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",

Browser:
- [x] Chrome (desktop) version 61.0.3163.100 (Official Build) (64-bit)
 
For Tooling issues:
- Node version: v6.2.2
- Platform:  Windows 10

</code></pre>

**Comment by mruanova** [comment]
I want to be able to use both the route parameter for the playerID and the has for the fragment when I do /player/112#info but I don't think that Angular in prepared for this scenario.

**Comment by mruanova** [comment]
I fixed this by adding the ID in the routerLink to match the route.
<button [routerLink]="['/player/1']" fragment="info">INFO</button>
