### ISSUE TITLE
Router upgrade helpers for ngUpgradeLite

### ISSUE THREAD

**Issue by rkirov** [angular/angular#19707]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

The router upgrade helpers (that allow angularJS router to coexist with Angular router) here 
https://github.com/angular/angular/blob/master/packages/router/upgrade/src/upgrade.ts#L60
assume NgUpgrade (trying to inject UpgradeModule).

We need a way to provide the same behavior, but for NgUpgradeLite (i.e. no UpgradeModule) present.

**Comment by rkirov** [comment]
Two things that would be nice to have:

- automatically do this setup, by virtue of calling `downgradeModule`. Roughly, the injectable can attempt to inject `Router` with `@Optional` to see if it is present or not.
- the meat of the logic should be shared with the current implementation.

**Comment by gkalpak** [comment]
Is it only about `setUpLocationSync()`? If so, then all it needs is the two injectors (which are available in `ngUpgradeLite` too). So, you should be able to use it today (as a work-around) with something like:

```ts
setUpLoctionSync({$injector: ng1Injector, injector: ng2Injector});
```

Wiring it up automatically is possible, but I am concerned about people that don't want this to happen. Maybe make it configurable:

```ts
angular.module('myApp', [
  downgradeModule(MyAngularModuleFactory, {
    setUpLocationSync: true/false,
  }),
])
```

WDYT, @rkirov, @petebacondarwin?

**Comment by gkalpak** [comment]
ping @rkirov, @petebacondarwin

**Comment by joelpoloney** [comment]
I got this working with ngUpgradeLite, but it requires a bit more futzing around. Here's an example of doing this in the root AppModule:

```typescript
function dummyBootstrap(element: Element, modules?: string[], config?: any) {}

export class AppModule {
  constructor(private readonly ngZone: NgZone, private readonly injector: Injector) {}
  ngDoBootstrap() {
    // https://github.com/angular/angular/issues/19707
    const $injector = this.injector.get('$injector');
    setUpLocationSync({
      bootstrap: dummyBootstrap,
      injector: this.injector, // Angular injector
      $injector, // AngularJS injector
      ngZone: this.ngZone,
    });

    const router = this.injector.get(Router);
    router.initialNavigation();
  }
}
```

**Comment by petebacondarwin** [comment]
I think you could make a simpler helper of your own:

```typescript
function setUpLocationSyncLite(injector: Injector) {
  const $injector = this.injector.get('$injector');
  const router: Router = injector.get(Router);
  const url = document.createElement('a');

  $injector.get('$rootScope')
      .$on('$locationChangeStart', (_: any, next: string, __: string) => {
        url.href = next;
        router.navigateByUrl(url.pathname + url.search + url.hash);
      });
}

export class AppModule {
  constructor(private readonly injector: Injector) {}
  ngDoBootstrap() {
    setUpLocationSync(this.injector);
    const router = this.injector.get(Router);
    router.initialNavigation();
  }
}
```

**Comment by gkalpak** [comment]
But you won't benefit from `setUpLocationSync()` improvements/changes (e.g. https://github.com/angular/angular/pull/20244/files#diff-3ca33e745c14d1dec4aa63e801cf66d0) 😇

**Comment by petebacondarwin** [comment]
In that case we need to factor out the functionality into a function like I gave above, and then wrap that in UpgradeHeavy.

**Comment by gkalpak** [comment]
Given the low demand for this feature and the fact that there is a work-around available, I am going to close this.
