### ISSUE TITLE
compiler-cli: metadata.json and ngsummary.json going into the wrong output directory

### ISSUE THREAD

**Issue by vikerman** [angular/angular#19718]
## I'm submitting a...

<pre><code>
[] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In angular/universal repo building a module with tsconfig with the following options

"compilerOptions": {
    "outDir": "../../dist/common",
    "rootDir": "./"
},

creates a dist directory with the structure

dist/
  |_common/
       |_common/
       |       |_ index.metadata.json                         --> Wrong
       |       |_index.ngsummary.json                      --> Wrong
       |       |_ src/
       |             |_ transfer_http.metadata.json       -> Wrong
       |             |_ transfer_http.ngsummary.json    -> Wrong
       |_ index.js  --> the above files should be by the side here       

## Expected behavior
*.metadata.json and *.ngsummary.json files should just go to the side of the .js files generated by ngc.

## Minimal reproduction of the problem with instructions
1. git clone git@github.com:angular/universal.git
2. npm install
3. npm run build:common

(Files end up in wrong place in dist/ folder)

Angular version: 5.0.0-rc.2
</code></pre>

**Comment by tbosch** [comment]
Looks like if the `outDir` contains 2 path segments, e.g. `dist/common`, then this problem occurs (doesn't matter how many `..` before them).
