### ISSUE TITLE
Receiving error "xliff parse errors" when trying to compile angular app with i18n for AOT using ngc

### ISSUE THREAD

**Issue by IgorWolbers** [angular/angular#19728]
## I'm submitting a...

<pre><code>
[X ] Bug report  
</code></pre>

## Current behavior
When compiling an angular app with i18n localization as described in the [i18n guide][2] the command consistently returns the message `xliff parse errors:` and then an error for each resource line in the localization file.

## Expected behavior
AOT compilation completes the same as it would when no localization file is passed (using the parameters).

## Minimal reproduction of the problem with instructions
I followed the tutorials/documentation outlined on the angular site: [i18n][2] and [aot][3]. I put together the following reproduction using the [Tour of Heroes Tutorial source code][1] as it is readily available.

1. Download the angular [Tour of Heroes Tutorial source code][1]
2. Extract to some folder that I will now refer to as the `app root` folder.
3. Get latest packages using `npm i`
4. Edit the file `./app/dashboard.component.html`, change the first line from a to b
 a. `<h3>Top Heroes</h3>`
 b. `<h3 i18n="@@HeroListTitle">Top Heroes</h3>`
5. Add a new file named `./src/tsconfig.aot.json` with the following content

		{
		  "compilerOptions": {
			"target": "es5",
			"module": "es2015",
			"moduleResolution": "node",
			"sourceMap": true,
			"emitDecoratorMetadata": true,
			"experimentalDecorators": true,
			"lib": ["es2015", "dom"],
			"noImplicitAny": true,
			"suppressImplicitAnyIndexErrors": true,
			"typeRoots": [
			  "../node_modules/@types/"
			]
		  },
		  "compileOnSave": true,
		  "exclude": [
			"node_modules/*",
			"**/*-aot.ts"
		  ],
		  "angularCompilerOptions": {
		   "genDir": "aot",
		   "skipMetadataEmit" : true
		 }
		}

6. Create the translation file by running this command from the root folder `.\node_modules\.bin\ng-xi18n --locale=en --i18nFormat=xlf --outFile=translations.xlf -p .\src\tsconfig.json`. This produces the file `.\src\translations.xlf` with the following content:

		<?xml version="1.0" encoding="UTF-8" ?>
		<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
		  <file source-language="en" datatype="plaintext" original="ng2.template">
			<body>
			  <trans-unit id="HeroListTitle" datatype="html">
				<source>Top Heroes</source>
				<context-group purpose="location">
				  <context context-type="sourcefile">app\dashboard.component.ts</context>
				  <context context-type="linenumber">1</context>
				</context-group>
			  </trans-unit>
			</body>
		  </file>
		</xliff>

7. Compile the application with the AOT compiler *with* the localization file by running this from the root folder `.\node_modules\.bin\ngc -p .\src\tsconfig.aot.json --i18nFile=.\src\translations.xlf --locale=en --i18nFormat=xlf`. This produces the following message:

		Error: xliff parse errors:
		Message HeroListTitle misses a translation ("
		  <file source-language="en" datatype="plaintext" original="ng2.template">
			<body>
			  [ERROR ->]<trans-unit id="HeroListTitle" datatype="html">
				<source>Top Heroes</source>
				<context-"): i18n@4:6
			at Xliff.load (D:\Angulari18nTesting\i18nTest\node_modules\@angular\compiler\bundles\compiler.umd.js:9382:19)
			at Function.TranslationBundle.load (D:\Angulari18nTesting\i18nTest\node_modules\@angular\compiler\bundles\compiler.umd.js:10671:29)
			at new I18NHtmlParser (D:\Angulari18nTesting\i18nTest\node_modules\@angular\compiler\bundles\compiler.umd.js:10876:35)
			at Object.createAotCompiler (D:\Angulari18nTesting\i18nTest\node_modules\@angular\compiler\bundles\compiler.umd.js:25780:39)
			at Function.CodeGenerator.create (D:\Angulari18nTesting\i18nTest\node_modules\@angular\compiler-cli\src\codegen.js:84:36)
			at codegen (D:\Angulari18nTesting\i18nTest\node_modules\@angular\compiler-cli\src\main.js:13:36)
			at Object.main (D:\Angulari18nTesting\i18nTest\node_modules\@angular\tsc-wrapped\src\main.js:106:16)
			at main (D:\Angulari18nTesting\i18nTest\node_modules\@angular\compiler-cli\src\main.js:19:16)
			at Object.<anonymous> (D:\Angulari18nTesting\i18nTest\node_modules\@angular\compiler-cli\src\main.js:35:5)
			at Module._compile (module.js:569:30)
		Compilation failed

8. If you run `.\node_modules\.bin\ngc -p .\src\tsconfig.aot.json` (*no translation file*) it completes without warning and generates the expected output.

9. I have also tried other translation formats supported by `ng-xi18n` but received similar errors.

10. You can update all the angular packages in the demo/tutorial to the latest (4.4.5) in the `package.json` file but the behavior is the same so it is not necessary when reproducing the behavior.

## What is the motivation / use case for changing the behavior?
Create AOT packages based on my supported localizations.

## Environment

<pre><code>
Angular version: 4.4.5

Browser:
*not applicable*
 
For Tooling issues:
- Node version: 8.1.3
- Platform:  Windows

</code></pre>

[1]:https://angular.io/generated/zips/toh-pt6/toh-pt6.zip
[2]:https://angular.io/guide/i18n 
[3]:https://angular.io/guide/aot-compiler

**Comment by alandroid** [comment]
Add a target tag _(`<target>Top Heroes (Translated)</target>`_) underneath `<sources>` tag

**Comment by ocombe** [comment]
Hello, like @alandroid said you need to add `<target>...</target>` in your xlf file because it is the translation itself. That's why the error message tells you that it is missing the translation.

**Comment by IgorWolbers** [comment]
I read through the documentation one more time, it **is** clearly spelled out but I just missed it. 

Sorry to have wasted your time, thank you for your prompt response, and keep up the awesome work!

**Comment by abhishekspatil** [comment]
I had same issue adding target tag underneath <source> tag in .\src\translations.xlf worked for me.
