### ISSUE TITLE
SelectControlValueAccessor.compareWith: 25 tests for 5 options seems excessive

### ISSUE THREAD

**Issue by pamtbaau** [angular/angular#19723]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using `compareWith` on a `<select>` with only 5 options, `compareWith` function is being called 25 times.

On initialization of the form, 15 runs are tested against `undefined`, 5 against `null` and 5 against an object.

On refresh of the option list, 25 runs are tested against an object in a peculiar order.

This happens both in development and production.

## Expected behavior

I would expect it to test between 1 and max. 5 times depending on the selected option

## Minimal reproduction of the problem with instructions

[demo plunker](https://embed.plnkr.co/rSGExdIewdJpshDs7tSw/) See console for output.

## What is the motivation / use case for changing the behavior?

Performance

## Environment

<pre><code>
Angular version: 4.4.5

Browser:
- [x] Chrome (desktop) version 61.0.3163.100 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Electron version 1.7.8

For Tooling issues:
- Node version:  v8.5.0 
- Platform:  Windows 10  

Others:

</code></pre>

**Comment by Toxicable** [comment]
I don't see an issue here, remember that in debug mode all CD is run twice, so in prod mode you'd only see 12 or 13 calls

**Comment by pamtbaau** [comment]
The numbers mentioned were taken from the plunker in production mode...  

I'm puzzled... Are 12 or 13 calls to compare an id against a list of 5 really to be expected???

Would you consider the following outcome where `compareWith` is run 5 times over the entire set of options after a data refresh and skipping successful hits as being a non-issue?

```
After initialization of view

comparing: id 1 with id undefined
comparing: id 1 with id undefined
comparing: id 2 with id undefined
comparing: id 1 with id undefined
comparing: id 2 with id undefined
comparing: id 3 with id undefined
comparing: id 1 with id undefined
comparing: id 2 with id undefined
comparing: id 3 with id undefined
comparing: id 4 with id undefined
comparing: id 1 with id undefined
comparing: id 2 with id undefined
comparing: id 3 with id undefined
comparing: id 4 with id undefined
comparing: id 5 with id undefined
comparing: id 1 with id null
comparing: id 2 with id null
comparing: id 3 with id null
comparing: id 4 with id null
comparing: id 5 with id null
comparing: id 1 with id 5
comparing: id 2 with id 5
comparing: id 3 with id 5
comparing: id 4 with id 5
comparing: id 5 with id 5 -> true

Refresh data

comparing: id 2 with id 5
comparing: id 3 with id 5
comparing: id 4 with id 5
comparing: id 5 with id 5 -> true
comparing: id 3 with id 5
comparing: id 4 with id 5
comparing: id 5 with id 5 -> true
comparing: id 4 with id 5
comparing: id 5 with id 5 -> true
comparing: id 5 with id 5 -> true
comparing: id 1 with id 5
comparing: id 1 with id 5
comparing: id 2 with id 5
comparing: id 1 with id 5
comparing: id 2 with id 5
comparing: id 3 with id 5
comparing: id 1 with id 5
comparing: id 2 with id 5
comparing: id 3 with id 5
comparing: id 4 with id 5
comparing: id 1 with id 5
comparing: id 2 with id 5
comparing: id 3 with id 5
comparing: id 4 with id 5
comparing: id 5 with id 5 -> true
```

**Comment by kara** [comment]
We should probably take a closer look and see if all these calls are needed or if there's a more efficient way to do this.

**Comment by AndrewKushnir** [comment]
FYI, closing this ticket in favor of #41330, which has more up-to-date repro.
