### ISSUE TITLE
loadChildren not working in children router

### ISSUE THREAD

**Issue by felixlwang** [angular/angular#19737]
Previously, i developed an angular project based on ASP MVC framework. Now I want to change it to Angular-cli. But I met some router problems with the lazy loader in children router.

'Industries' module can't be changed. Wrong code is below:
```
export const appRoutes: Routes = [
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: 'login', component: LoginComponent },
    { path: 'home', component: HomeComponent, canActivate: [AuthGuard],
        children: [
            { path: 'industries', loadChildren: './industries/industries.module', canActivate: [AuthGuard] },
            { path: 'industries1', loadChildren: './industries1/industries1.module', canActivate: [AuthGuard] },
        ]
    }
];

@NgModule({
    imports: [RouterModule.forRoot(appRoutes)],
    exports: [RouterModule]
})

export class AppRoutingModule { }
```

But when I don't the lazy loader, it works fine. The correct code is as below:
```
        children: [
            { path: 'industries', component: IndustriesComponent, canActivate: [AuthGuard] },
            { path: 'industries1', component: Industries1Component, canActivate: [AuthGuard] },
        ]
```

My previous project in ASP MVC, i use the following router in HomeModule. But in Angular-cli, it says "**_Cannot find module_**", please help me.
```
export const homeRoutes: Routes = [
    {
        path: '', component: HomeComponent,
        children: [
            { path: 'industries', loadChildren: 'app/industries/industries.module', canActivate: [AuthGuard] },
            { path: 'industries1', loadChildren: 'app/industries1/industries1.module', canActivate: [AuthGuard] },
        ]
    }
];

@NgModule({
    imports: [
        CommonModule, ReactiveFormsModule, FormsModule,
        RouterModule.forChild(homeRoutes),
    ],
    declarations: [
        HomeComponent,
    ],
})

export default class HomeModule { }
```

@DzmitryShylovich Could you please help me out, i am new to angular. Thanks!

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jasonaden** [comment]
Closing as this is a support request.
