### ISSUE TITLE
Angular freezes without any error when I navigate to next page from an external library callback

### ISSUE THREAD

**Issue by tom10271** [angular/angular#19731]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There are 2 components: Login and Main page. I use Google JS API `gapi` to login. If I navigate to main page once I have logged in successfully from Google, then in Main page it freezes. Yet if I go to Main page without logging in first then main page works. And then if you go back to login page and login with Google api, it redirect to main page with works fine too.

## Expected behavior

It should works consistently if I navigate to another page from an external callback.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/8IJJReAwtAOk8GE3enuS?p=preview

## What is the motivation / use case for changing the behavior?

I want users to login first before navigating to other pages but all broken

## Environment

<pre><code>
Angular version: 4.4.5

Browser:
- [61] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
The condition is:

**Routed component won't perform change detection when navigated from non-Angular zones.**

An minimal reproduction can be found [here](https://plnkr.co/edit/GG25yLqsjn2KHtekdOHp?p=preview).

**Seems this is the expected behavior.**

**Comment by tom10271** [comment]
But How would I use plugins that have interaction and callback like Google JS API in this case? There is no way for me to use Google OAuth with Angular as it is never in Angular's zone.

**Comment by trotyl** [comment]
> Executes the fn function synchronously **within the Angular zone** and returns value returned by the function.
>
> Running functions via run allows you to **reenter Angular zone** from a task that was executed outside of the Angular zone (typically started via runOutsideAngular).

https://angular.io/api/core/NgZone#run

**Comment by trotyl** [comment]
For tracking purpose: duplicate of #18254.
