### ISSUE TITLE
Angular 4 Listening for progress on FireFox after AOT not work

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular#19732]
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## Current behavior

Listening for progress on FireFox after AOT not work.

I want to show progress bar while file is download. I'm using angular 4 with HttpClient.

**WITHOUT AOT** 
I succeed to display progress bar on both chrome and Firefox.

**USING AOT**
 I succeed to display progress bar only with chrome **but not in Firefox**.

## Expected behavior

get on the  progress event the value of loaded and total

## Minimal reproduction of the problem with instructions
**I'm working with:**
"@angular/cli": "^1.4.2",
"@angular/http": "4.3.6",

**I use this script**
"start-prod": "ng serve --base-href /v2/ --prod --deploy-url /v2/ --proxy-config proxy.conf.json"

**My Code**
```
downloadFile(fileName) {

  const headers = new HttpHeaders({'Upgrade-Insecure-Requests': '1'});

  const req = new HttpRequest('GET', 'some-url', {
    reportProgress: true,
    headers: headers,
    responseType: 'blob'
  });

 this.http.request(req).subscribe(event => {
    if (event.type === HttpEventType.DownloadProgress) {
      this.progressPercentage = Math.round(100 * event.loaded / event.total);
    } else if (event instanceof HttpResponse) {
      const data = new Blob([event.body]);
      FileSaver.saveAs(data, fileName);
    }
  },
  this.onDownloadError.bind(this)); };

```

## Environment
<pre><code>
Angular version: 4.3.6

Browser:
- [X] Firefox version 56.0

 
For Tooling issues:
- Node version: 8.4.0
- Platform: Mac 
Others:

</code></pre>

**Comment by Toxicable** [comment]
I'm sorry but reported issues require a plunker or Stack Blitz reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue or with Stack Blitz https://stackblitz.com/
