### ISSUE TITLE
Disabling all controls in a form group, adds all controls to form group values

### ISSUE THREAD

**Issue by bregnvig** [angular/angular#19735]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Using a reactive form with a form group. When all controls in the form group are disabled, the values of the controls are added the the value object of the form group.

E.g I have a form group with two controls. When the first control is disabled, only the second control is part of the value object of the form group. When I disable the second control both controls are part of the form groups value object.

## Expected behavior
If all controls are disabled, the form group has no values.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/cypIb5

Open the plunker and disable both controls using the buttons next to the controls

Code

```typescript
export class App {
  name:string;
  fg: FormGroup;
  content: any
  constructor(fb: FormBuilder) {
    this.name = `Angular! v${VERSION.full}`
    this.fg = fb.group({
      a: ['a'],
      b: ['b']
    });
    this.fg.valueChanges.subscribe(value => this.content = value);
  }
  
  public toggle(name: string) {
    this.fg.get(name).enabled ? this.fg.get(name).disable() : this.fg.get(name).enable()
  }
}
```
The `this.content` will contain the value of a & b, when both controls are disabled.

## What is the motivation / use case for changing the behavior?

Currernt behaviour seems strange

## Environment

Angular version: 4.4.5

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

(Most likely also a problem in the other browsers, just haven't checked)

**Comment by Toxicable** [comment]
dupe #18684

**Comment by kara** [comment]
Closing as dupe
