### ISSUE TITLE
ngForm does not register controls from template

### ISSUE THREAD

**Issue by Delagen** [angular/angular#19738]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
```
{{form.value|json}} {{form.valid}}
<form #form="ngForm">
<ng-container *ngTemplateOutlet="controlsTemplate"></ng-container>
</form

<ng-template #controlsTemplate>
....any ng-form controls
</ng-template>
```

form.value always {} and form.valid always true
No any controls registered in ngForm

## Expected behavior
All controls registered in ngForm

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/G38KWqq7dDBvIcuimq6A?p=preview

## Environment

<pre><code>
Angular version: 4.x or 5-dev
</code></pre>

**Comment by Toxicable** [comment]
`ngTemplateOutlet` Doesn't shift the template into the container, it simple displays it there.
Therefore this is working as intended

**Comment by Delagen** [comment]
@Toxicable Thanks for comment.
