### ISSUE TITLE
Separate HttpClient instances with their own sets of interceptors

### ISSUE THREAD

**Issue by elgs** [angular/angular#19730]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Interceptors seems to be applied to class level of `HttpClient` from `@angular/common/http`.

## Expected behavior

I'm hoping interceptors will be applied to instance level of `HttpClient`.

## What is the motivation / use case for changing the behavior?

A package called `angular2-jwt` provided a separate instance of http called `AuthHttp`, which is great. However, that version of http doesn't support interceptors. Now I'm hoping to implement several instances of http client, each with different sets of interceptors applied, or some without any interceptor at all. It seems right now all interceptors are applied to the `HttpClient` at the class level, which makes it impossible to create separate instances of `HttpClient`s which would have their respective sets of interceptors.

**Comment by alxhub** [comment]
Sorry, this isn't a supported use case for interceptors/`HttpClient` currently.

**Comment by anasanzari** [comment]
+1
