### ISSUE TITLE
Tour of heroes: Should --open parameter be added to start script

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#19746]
Moved from https://github.com/angular/devkit/issues/120 by @winksaville. Tour of heroes needs to be updated to reflect that the server does not open automatically, and that the `--open` flag should be used.

Also see https://github.com/angular/devkit/pull/119#issuecomment-333409358 and https://github.com/angular/devkit/issues/120#issuecomment-336935765 for why CLI projects don't open automatically.

---

In the [Tour of Heros](https://angular.io/tutorial) tutorial [here](https://angular.io/tutorial/toh-pt1#keep-the-app-transpiling-and-running) and [here](https://angular.io/tutorial/toh-pt2#keep-the-app-transpiling-and-running) it says:
```
$ npm start

This command runs the TypeScript compiler in "watch mode",
recompiling automatically when the code changes. The command
simultaneously launches the app in a browser and refreshes the
browser when the code changes.
```
But the start script in package is `"start": "ng serve",` and does not have the `--open` parameter needed to cause the launching of the app in the browser.

I've created PR #119 which adds the --open parameter and this corrects the problem for me.

**Comment by jenniferfell** [comment]
The Tour of Heroes Tutorial has been updated to use the CLI. Instead of npm serve, the Tutorial now uses the CLI ng serve command. 

I'm closing this issue as resolved. Thank you for your feedback!
