### ISSUE TITLE
how to do prototype extend for javascript library in Angular Typescript

### ISSUE THREAD

**Issue by gauthamshettykaup** [angular/angular#19745]
Please let me know on which file I should extend 'Handsontable' in angular 2/4
Please let me know whether I’m following correct approach or not. If not please suggest me correct approach. 

I using some javascript library in Typescript(Angular 4). I've snippet of javascript function:

(function(Handsontable){
  var CustomEditor = Handsontable.editors.BaseEditor.prototype.extend();

  // ...rest of the editor code

  // Put editor in dedicated namespace
  Handsontable.editors.CustomEditor = CustomEditor;

  // Register alias
  Handsontable.editors.registerEditor('theBestEditor', CustomEditor);

})(Handsontable);
I’ve extend this library in typescript file of Angular like this:

declare var Handsontable : any;
constructor (
const autocompleteEditor2 = Handsontable.editors.AutocompleteEditor.prototype.extend();
Handsontable.editors.autocompleteEditor2 = autocompleteEditor2;
Handsontable.editors.registerEditor('autocompleteEditor2', autocompleteEditor2);
)

**Comment by tbosch** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gauthamshettykaup** [comment]
Already posted at StackOverflow using tag angular
