### ISSUE TITLE
Remove default exports hack in async.ts

### ISSUE THREAD

**Issue by rkirov** [angular/angular#1975]
TS and traceur disagreed on the semantics of exporting defaults in the presence of `*` so we needed https://github.com/angular/angular/blob/master/modules/angular2/src/facade/async.ts#L88.

Looks like TS was correct - https://github.com/systemjs/systemjs/pull/432 and traceur will include a fix in the next version. 

We need to update traceur and remove the hack.

**Comment by naomiblack** [comment]
this is some cleanup related to typescriptification...

**Comment by alexeagle** [comment]
I'll also try to clean up our rx typings since that's closely related

**Comment by alexeagle** [comment]
WIP at https://github.com/alexeagle/angular/tree/fix1975

We still have 9 files using Traceur and I have some issues with the Traceur upgrade. Let's put this off till next milestone, perhaps we can remove traceur altogether instead.

**Comment by alexeagle** [comment]
fixed by https://github.com/angular/angular/pull/3630
