### ISSUE TITLE
ngOnInit no longer safe place to change service data

### ISSUE THREAD

**Issue by PRR24** [angular/angular#19755]
## I'm submitting a defect

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior
Changing service variable in a child ngOnInit causes uphill component to trigger ExpressionChangedAfterItHasBeenCheckedError

## Expected behavior
ngOnInit acts as an event handler that can safely change shared data.

## Minimal reproduction of the problem with instructions
- ng new my-app --routing
- ng g component first
- ng g component second
- ng g service shared
---
```
shared.service.ts: Create shared value
@Injectable()
export class SharedService {
  someValue: boolean = false;
}

first.component.ts: Inject SharedService 
export class FirstComponent {
  constructor(public sharedService: SharedService) { }
}

first.component.html:
<div *ngIf="sharedService.someValue">someValue is ON</div>

second.component.ts: Inject SharedService and change shared value on load
export class SecondComponent implements OnInit {
  constructor(public sharedService: SharedService) { }
  ngOnInit() {
    this.sharedService.someValue = true;
  }
}

app.module.ts: Add SharedService to providers:
providers: [ SharedService ],

app-routing.module.ts: Add second component to the route:
const routes: Routes = [
  { path: "**", component: SecondComponent }
];

app.component.html:
<div *ngIf="true"><app-first></app-first></div>
<router-outlet></router-outlet>
```
- ng serve --open

Result: ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.

## Environment
@angular/cli: 1.4.7

<pre><code>
Angular version: 4.4.5
First known repro in 4.2.0
No Repro in 4.1.3

Browser:
- [X] Chrome (desktop) version 60.0.3112.113
 
For Tooling issues:
- Node version: 6.11.2
- Platform:  Linux, Ubuntu 16.04
</code></pre>

**Comment by baruchvlz** [comment]
Its to my understanding that service data should be immutable. You should create a copy of the data in your component and then change/use that.

**Comment by tbosch** [comment]
AFAIK, this has always been our behavior.

Could you create a reproduction on http://plnkr.co? For both an old version of Angular where this worked and now that it doesn't work anymore?

**Comment by PRR24** [comment]
Here you are:
http://plnkr.co/edit/sCHIg16K6vJeCMpZWeCy?p=preview
Please change the angular version in index.html to notice the change from 4.1.3 to 4.2.0

**Comment by trotyl** [comment]
That is the exact same example as demonstrated in [comment here](https://github.com/angular/angular/issues/17572#issuecomment-323465737).

**Comment by PRR24** [comment]
Thank you, closing.
