### ISSUE TITLE
version 4.4.5, duplication of the method in one class

### ISSUE THREAD

**Issue by BzenkoSergey** [angular/angular#19758]
node_modules/@angular/core/@angular/core/core.js

```
class Injector {
    /**
     * Retrieves an instance from the injector based on the provided token.
     * If not found:
     * - Throws an error if no `notFoundValue` that is not equal to
     * Injector.THROW_IF_NOT_FOUND is given
     * - Returns the `notFoundValue` otherwise
     * @abstract
     * @template T
     * @param {?} token
     * @param {?=} notFoundValue
     * @return {?}
     */
    get(token, notFoundValue) { }
    /**
     * @deprecated from v4.0.0 use Type<T> or InjectionToken<T>
     * @suppress {duplicate}
     * @abstract
     * @param {?} token
     * @param {?=} notFoundValue
     * @return {?}
     */
    get(token, notFoundValue) { }
}
```

closure compiler report (advanced mode)

```
ERROR - Class contains duplicate method name "get"
    get(token, notFoundValue) { }
```

**Comment by alexeagle** [comment]
Sounds like a versioning issue, can you include what version of closure compiler so we can repro?

Check out the versioning we've used on https://github.com/angular/closure-demo (including prior commits when it was using Angular 4, assuming you're not ready to upgrade to 5 yet). These ought to work, unless we are missing some testing.

**Comment by tbosch** [comment]
Closing here, please reopen again at https://github.com/angular/closure-demo if this issue still exists.

**Comment by trotyl** [comment]
@tbosch I guess this is indeed an Angular compiler bug, the problem here is that in TypeScript an abstract method is only for type declaration with no output, but when applying `annotateForClosureCompiler: true` it remains like normal method.

Source:

```typescript
abstract class Foo {
  abstract bar(x: number): string;
}
```

ES2015 result with tsc:

```typescript
class Foo {
}
```

ES2015 result with ngc using `annotateForClosureCompiler: false`:

```typescript
class Foo {
}
```

ES2015 result with ngc using `annotateForClosureCompiler: true`:

```typescript
/**
 * @abstract
 */
class Foo {
    /**
     * @abstract
     * @param {?} x
     * @return {?}
     */
    bar(x) { }
}
```

This is not a correct behavior as it violating the TypeScript semantics, not relates to the duplication.

**Comment by BzenkoSergey** [comment]
Okey, but for user it's method duplication.
node_modules/@angular/core/@angular/core/core.js - ES6 version. 
ES standards don't support methods overload or duplication.

reproduce steps:
1. npm i @angular/core@4.4.5
2. go to node_modules/@angular/core/@angular/core/core.js
3. find "class Injector"

**Comment by tbosch** [comment]
Actually, we fixed this in Angular 5 via a change to tsickle here: https://github.com/angular/tsickle/commit/44924fab163ec4338d23955a36123724f15d9f36, which was part of tsickle v0.24.1. However, this was after tsickle was upgraded to TypeScript 2.3, so we would need to create a patch release for tsickle v0.21.x which is used in Angular 4.x.

**Comment by tbosch** [comment]
@BzenkoSergey This should work when using closure though, please follow @alexeagle advice above.

**Comment by BzenkoSergey** [comment]
Thanks!

**Comment by pkozlowski-opensource** [comment]
> Actually, we fixed this in Angular 5 

Sounds like this issue was specific to Angular 4.x and was resolved since so closing.
