### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by barakbd** [angular/angular#19754]
## I'm submitting a...
 Documentation issue or request

## Current behavior

I am trying to understand how to use the new HttpCientModule. The problem is that the old Class/APIs still appear in the latest version. Should I use Response or HttpResponse? How to use HttpResponse for typing a response? How am I supposed to know that URLSearchParams and RequestOptions are deprecated? 

## Expected behavior

Rather than just having documentation with the latest version (e.g. 4.4.5) have a more detailed system ( 4.4.3, 4.4.1 etc.) and in the latest version mention what is going to get deprecated and have a link to the new Class/API.

## Minimal reproduction of the problem with instructions

https://angular.io/api/http/Response 
Should mention that it is going to be deprecated and have a link to 
https://angular.io/api/common/http/HttpResponse

https://angular.io/api/http/RequestOptions
Should mention that it is going to be deprecated and have a link to 
https://angular.io/api/common/http/HttpParams

## What is the motivation / use case for changing the behavior?

Better Documentation, less searching StackOverflow, faster development

**Comment by Toxicable** [comment]
Http is deprecated in v5, see here 
https://next.angular.io/api/http/RequestOptions#deprecation-notes

**Comment by jenniferfell** [comment]
In v5 and v6, the API reference pages now contain a label at the top of the page if the API is "Deprecated" https://angular.io/api/http/Response

As mentioned above, they also contain an explicit section for Deprecation Notes. 

I hope both of these changes meet your needs. If not, please feel free to open a new issue about how we can make deprecation easier and more clear. Thanks again!
