### ISSUE TITLE
Evaluate Template Expression in Component

### ISSUE THREAD

**Issue by jmk4982** [angular/angular#19763]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is no documentation on how to evaluate a Template Expression at runtime, within a component, without rendering.

## Expected behavior

Would like to have documentation on how to call the Template Expression evaluator.

## Minimal reproduction of the problem with instructions
let template = "itemRef.CreatedOn | date : 'yMd'"; // a valid Template Expression
for (let item of this.items) { // where this.items is an Array of objects whose type is not known
   item['CreatedOn_EvaluationResult'] = evaluate([itemRef: item], template); // $eval for a context against a template
}

The real issue isn't just that there isn't a documented Evaluate function, but there is no documentation on all of the components used for the Evaluation process.

## What is the motivation / use case for changing the behavior?
I would like to evaluate a Template Expression against items in an array in order to filter by the result of the Template Expression for each element.

## Environment

<pre><code>
Angular version: latest

Others:
Many of the classes which are part of the parse and evaluation process have absolutely no documentation, such as the Parser, AST, and Compiler.  This makes it difficult to dig deep enough to reproduce whatever functionality that's being evaluated in the ChangeDetection cycle.
</code></pre>

**Comment by tbosch** [comment]
There is no such thing: Angular only compiles expressions as part of templates of components.
We are also not planning on supporting this use case as it is relatively simple to just write plain javascript / typerscript instead.

**Comment by jmk4982** [comment]
One could argue that "relatively simple" is only accurate for those who know how to access all of the directives and pipes (by selector) currently loaded in the relevant ngModule and are familiar with the parse and evaluation pattern for Template Expressions.  Even then, manually recreating and evaluating any expression which the Abstract Syntax Tree can define in a given context is far from trivial without a working knowledge of the Parser/ Visitors.

But if there's no accessible functionality and no intention to expose the Template parser and evaluator, then I guess documentation for them would be a moot point.  Thank you for your time!  Sorry for the trouble :)

**Comment by AndrewBogushevich** [comment]
I have dynamic string param which should evaluated and I want to use pipes like async, date and other. What is the reason of implementing own syntax, parser, etc if angular already has one?
May be a solution in some cases:
https://stackoverflow.com/a/44082399/8092057

**Comment by jmk4982** [comment]
Thank you for the suggestion Andrew! I had actually taken a pass at the dynamic module approach stated in s similar SO thread. My use case, however, requires that I get the value output of the expression without displaying anything to the page. In my case it also seems inefficient to be creating thousands of one-time-use modules for the contents of a scrollable datagdrid.

It would just be super great if Angular exposed the template evaluator as a utility consumable in typescript. Alas.

**Comment by mlc-mlapis** [comment]
@jmk4982 ... so you should use JitCompiler (JIT mode) together with your core app in AOT mode ... so you can get the advantage of a fast and small main app in AOT mode + ad-hod loading of JitCompiler with the ability to compile any HTML template (from CMS for example).
