### ISSUE TITLE
queryParams not loading on IOS + win phone

### ISSUE THREAD

**Issue by eddieedease** [angular/angular#19779]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using url with queryParams like 
`app#start?pin=00032`
, there is a problem with **windows Mobile + IOS devices** don't get the pin value when i use 
`this.pinsend = this.route.queryParams['_value'].pin;` 
in a component.

However, it works on all desktop browsers + android devices

## Expected behavior
 
It should work like in all other browsers/Devices?

## Minimal reproduction of the problem with instructions
' See current section behavior'

## Environment

**Angular 4.4.3**

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x ] Windows phone
 

</code></pre>

**Comment by tbosch** [comment]
Hello,
we need a reproduction for this. Could you create a branch on Github that reproduces this issue e.g. in the IOS simulator?

**Comment by veke** [comment]
That route looks like a fragment. Then it could be in this format: /lorem-route/app#foo=1&bar=2&baz=3 You can read it like this:
```
const frag = this.route.snapshot.fragment;  // if snapshot used, otherwise use subcribe
const params = new URLSearchParams(frag);
console.log(params.get('foo'), params.get('bar'), params.get('baz'))
// logs: 1, 2, 3
```

**Comment by eddieedease** [comment]
Closed as it is working now again, could not tell what we did to make it work again. Could very well be some foolish missing import or such...
