### ISSUE TITLE
ng-container not working as expected

### ISSUE THREAD

**Issue by sdpfigueiredo** [angular/angular#19781]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I need to repeat a component inside another component, let's say:

Component A only accepts, inside its ng-content, a component of type B.

doing something like:

```
<component-a>
    <ng-template ngFor [ngForOf]="items">
        <component-B></component-B>
    </ng-template>
</component-a>
```
or this:

```
<component-a>
    <ng-container *ngFor="let item of items">
        <component-B></component-B>
    </ng-container>
</component-a>
```
does not work...

I can't modify component-a nor compoenent-B and these approaches doesn't render the component-B...

Any ideas how to overcome this?

Thanks.

PS: I may need to add multiple component-B for each item.

## Minimal reproduction of the problem with instructions
I have created a plunker demo: plnkr.co/edit/7jlcpU0Wxxo6YxtrY66l?p=preview you can see the intended result on app.component.html

**Comment by alexzuza** [comment]
`ng-content[select]` only matches top-level child nodes so for me it is working as intended

**Comment by devoto13** [comment]
Maybe `ngProjectAs` on the `ng-container` can resolve your issue?
See [here](https://github.com/angular/angular/blob/f39c9c9e75671a7e235734b6b8aef263f6dff254/modules/%40angular/compiler/test/template_parser_spec.ts#L1082).

**Comment by sdpfigueiredo** [comment]
@devoto13 Many thanks!! that worked!
