### ISSUE TITLE
Deprecated http still used in platform-server

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular#19788]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
`@angular/http`, deprecated in Angular 5, is still used in 3 places of `@angular/platform-server` ([here](https://github.com/angular/angular/blob/c8f742e2880b2101b4a0cdf164643a4dc51e4d4f/packages/platform-server/src/server.ts), [here](https://github.com/angular/angular/blob/14e8e880222431eeccdacac6540574b49903bd79/packages/platform-server/src/http.ts) and [here](https://github.com/angular/angular/blob/6e1896b3338563374df40e15445f6feee0ea66d6/packages/platform-server/test/integration_spec.ts)).

Meaning we have to install a deprecated package for `@angular/platform-server` to work (or it will break), and also getting a bigger build size.

## Expected behavior
`@angular/http` should not be used anymore.

## Environment

<pre><code>
Angular version: 5.0.0-rc.2
</code></pre>

**Comment by manekinekko** [comment]
@vikerman could you check this?

**Comment by alxhub** [comment]
> Meaning we have to install a deprecated package for @angular/platform-server to work (or it will break).

This is correct and expected - we cannot remove the dependency on `@angular/http` from `@angular/platform-server` because some users still use the deprecated feature. This dependency will be removed when `@angular/http` is retired altogether, in Angular 7 or later.

> and also getting a bigger build size.

This isn't the case, thankfully. Just having `@angular/http` installed does not increase the size of your build. If you never import `HttpModule` into your client application, your bundle size won't be affected by its presence.

**Comment by trotyl** [comment]
But all `@angular/http` APIs are `experimental`, the deprecation policy only provide two major version deprecation stage for `stable` APIs, isn't it?

**Comment by vecernik** [comment]
I have the same issue with 6.1.8 and 7-beta.6 for a project using ServerModule: 

Error: Can't resolve all parameters for XHRBackend: (?, ?, ?).

**Comment by tdesvenain** [comment]
I get a similar issue on a 6.1.9 project

ERROR in ../@angular/platform-server/platform-server.ts(72,13): Error during template compile of 'ServerModule'
  Could not resolve @angular/http relative to /home/tde/projects/cuma-maillage/node_modules/@angular/platform-server/platform-server.d.ts..
node_modules/@angular/platform-server/src/http.d.ts(9,138): error TS2307: Cannot find module '@angular/http'.

ERROR in multi ./main.server.ts
Module not found: Error: Can't resolve '/home/tde/projects/cuma-maillage/main.server.ts' in '/home/tde/projects/cuma-maillage'
