### ISSUE TITLE
5.0.0-rc.2 - AOT with ngc: cannot find module

### ISSUE THREAD

**Issue by seanlandsman** [angular/angular#19780]
## I'm submitting a...

<pre><code>
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Taking the Angular quickstart repo as a baseline (https://github.com/angular/quickstart/) and then adding the AOT instructions here: https://angular.io/guide/aot-compiler, the ngc compiler will look for the module factory before its been compiled:

11:05 $ node_modules/.bin/ngc -p tsconfig-aot.json
src/main.ts(2,36): error TS2307: Cannot find module '../aot/src/app/app.module.ngfactory'.

## Expected behavior

The compilation should work as before

## Minimal reproduction of the problem with instructions

Repo of the issue here: https://github.com/seanlandsman/quickstart.git

Instructions:
npm install
./node_modules/.bin/ngc -p tsconfig-aot.json

## What is the motivation / use case for changing the behavior?

This is a regression - this works as expected in previous versions

## Environment

Angular 
<pre><code>
Angular version: 5.0.0-rc.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.7.3X  
- Platform:  OSX Sierra 

Others:

</code></pre>

**Comment by alexzuza** [comment]
Open `main.ts` (i would call it `main-aot.ts`) and change path to `AppModuleNgFactory` like:

`import { AppModuleNgFactory } from './app/app.module.ngfactory';
`

And there is no `genDir` option in angular 5. Use `compilerOptions.outDir` instead:

**tsconfig-aot.ts**
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "outDir": "aot",   <========================== add this
    "typeRoots": [
      "./node_modules/@types/"
    ]
  },
```

**Comment by seanlandsman** [comment]
@alexzuza thanks - the filenames were kept as they are to be inline with the AOT docs above

The trick was the outDir - I must have missed that change

thanks!
