### ISSUE TITLE
Roll out `fullTemplateTypeCheck` in G3

### ISSUE THREAD

**Issue by tbosch** [angular/angular#19792]

**Comment by tbosch** [comment]
See b/67951545

**Comment by henjovr** [comment]
This issues has been created nearly a year ago, any news on the progress?

**Comment by MurlyGopalan** [comment]
Has this been fixed yet ? Please give an update. Thanks.

**Comment by lichunr** [comment]
any update?

**Comment by bennylava10100** [comment]
Any update on this?

**Comment by rsheptolut** [comment]
The name of the issue doesn't make any sense. Please work on this though, because bugs are getting into production and they're completely preventable.

**Comment by vanslly** [comment]
This issue might be unassigned as @tbosch moved on an is working on Gmail

**Comment by vanslly** [comment]
Setting `angularCompilerOptions > fullTemplateTypeCheck=true` only catches some Angular template errors, not all unfortunately... for example:

```
@Component({
    template: `
        <div *ngFor="let item of list">
            {{ item.evil }}
        </div>
    `,
})
export class MyComponent {
    public list: {}[];
}
```

**Comment by petebacondarwin** [comment]
@vanslly - did you mean ngc rather than ngcc? Also are you saying that you do get the desired error when compiling in ivy mode?

**Comment by vanslly** [comment]
@petebacondarwin Apologies, I meant ngc (Angular Compiler); not ngcc (Angular Compatibility Compiler). Yes, I **do** get the desired error when compiling in ivy mode; I don't know if there are edge cases with `__ng__typescheck__`; would be great to get info from the team regarding that.

**Comment by kara** [comment]
Closing this as it's specific to Google and doesn't belong in the public tracker.  @vanslly if you think there's an actionable bug here, please feel free to open a new Github issue (it's likely to be lost here).
