### ISSUE TITLE
(Question) Angular Package Format 4.0 Documentation Location

### ISSUE THREAD

**Issue by shawnHartsell** [angular/angular#19790]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Is the documentation describing the Angular Package Format in another place besides 
[Google Docs?](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit).

Reason I ask is that the link is blocked by my company's proxy 👎 and I would like to easily share this information with other members of my team. I wanted to avoid pasting it into a gist lol

My apologies if this is not the correct repo for this issue.

Thanks!

**Comment by manekinekko** [comment]
Hi, here is a PDF version of the doc: www.transfernow.net/176pf8m02z8z

For any other question, please use stack-overflow (as described [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question))
