### ISSUE TITLE
Strange Guard behavior after  reinstalling node_modules - rxjs 5.5.0 changed  (added minimal reproduction project)

### ISSUE THREAD

**Issue by montella1507** [angular/angular#19799]
Hello we have perfectly working project built on several computers with 2+ days old Node_modules folder.  After deleting reinstalling node_modules yesterday our project is not working anymore.

So propably some "super dependency" is not compatible   with older Angular version.. )
## I'm submitting a...
[ x] Bug report

## Current behavior
Observables, Subjects, dont work correctly..

this code is working like a charm with 2days+ old node_modules:
` canActivate(snapshot: ActivatedRouteSnapshot, state: RouterStateSnapshot) {

    return Observable.of(snapshot.queryParams['code']).switchMap(code => {
      if (!code) {
        return Observable.of(null);
      } else {
        let url = environment.authApiUrl + '/token';
        let body: string = 'client_id=' + environment.client_id + '&grant_type=authorization_code&code=' + code;
        let headers: HttpHeaders = new HttpHeaders({
          'Content-Type': 'application/x-www-form-urlencoded'
        });
        return this.http.post(url, body, { headers: headers, responseType: 'json' })
          .catch(x => Observable.of(null));
      }
    })
      .map(data => {
        if (data === null) {
          console.log('Neplatný autorizační kód, přesměrovávám na LOGIN.')
          window.location.href = environment.loginUrl;
          return false;
        } else {
          this.router.navigate(['/']);
          return this.authService.signIn(data.access_token, data.refresh_token);
        }
      });
  }`

But in newer it doesnt jump to line 20 and it should.

Stacktrace in angular:
`

  | api.onUnhandledError | @ | VM568 polyfills.bundle.js:11229
-- | -- | -- | --
  | handleUnhandledRejection | @ | VM568 polyfills.bundle.js:11253
  | _loop_1 | @ | VM568 polyfills.bundle.js:11243
  | api.microtaskDrainDone | @ | VM568 polyfills.bundle.js:11247
  | drainMicroTaskQueue | @ | VM568 polyfills.bundle.js:11146
  | Promise resolved (async) |   |  
  | scheduleMicroTask | @ | VM568 polyfills.bundle.js:11121
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask | @ | VM568 polyfills.bundle.js:10950
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask | @ | VM568 polyfills.bundle.js:10772
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask | @ | VM568 polyfills.bundle.js:10792
  | scheduleResolveOrReject | @ | VM568 polyfills.bundle.js:11407
  | ZoneAwarePromise.then | @ | VM568 polyfills.bundle.js:11517
  | webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone | @ | VM571 vendor.bundle.js:219874
  | webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule | @ | VM571 vendor.bundle.js:219859
  | bootstrap | @ | VM572 main.bundle.js:35405
  | ../../../../../src/main.ts | @ | VM572 main.bundle.js:35417
  | __webpack_require__ | @ | VM567 inline.bundle.js:55
  | 0 | @ | VM572 main.bundle.js:35710
  | __webpack_require__ | @ | VM567 inline.bundle.js:55
  | webpackJsonpCallback | @ | VM567 inline.bundle.js:26
  | (anonymous) | @ | VM572 main.bundle.js:1

`

Package.json:
`{
    "name": "zdravel-pacient",
    "version": "0.0.1",
    "license": "MIT",
    "angular-cli": {},
    "scripts": {
        "start": "ng serve --port 4201 --e=dev",
        "start-in-da-house": "ng serve --port 4201 --e=house",
        "start-dev": "ng serve --port 4201 --e=dev",
        "start-test": "ng serve --port 4201 --e=test",
        "start-local": "ng serve --port 4201 --e=local",
        "build": "ng build --prod --e=dev",
        "build-dev": "ng build --prod --e=dev",
        "build-test": "ng build --prod --e=test",
        "build-test-aot": "ng build -prod -e=test -aot=true",
        "build-test-aot_JS-heap-out-of-memory-repaired": "node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng serve --port 4201 -prod -e=dev --sm=true -aot=true",
        "build-local": "ng build --prod --e=local",
        "lint": "tslint \"src/**/*.ts\"",
        "test": "ng test",
        "pree2e": "webdriver-manager update",
        "e2e": "protractor"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "4.3.3",
        "@angular/cdk": "2.0.0-beta.10",
        "@angular/common": "4.3.3",
        "@angular/compiler": "./dependency-overrides/compiler-4.3.3-fix.tgz",
        "@angular/compiler-cli": "4.3.3",
        "@angular/core": "4.3.3",
        "@angular/forms": "4.3.3",
        "@angular/http": "4.3.3",
        "@angular/material": "2.0.0-beta.10",
        "@angular/platform-browser": "4.3.3",
        "@angular/platform-browser-dynamic": "4.3.3",
        "@angular/router": "4.3.3",
        "@auth0/angular-jwt": "1.0.0-beta.9",
        "@ngrx/effects": "4.0.1",
        "@ngrx/store": "4.0.0",
        "@ngrx/store-devtools": "4.0.0",
        "@ngrx/store-log-monitor": "^3.0.2",
        "@progress/kendo-angular-charts": "^1.0.0",
        "@progress/kendo-angular-intl": "^1.0.0",
        "@progress/kendo-angular-l10n": "^1.0.0",
        "@progress/kendo-angular-popup": "^1.0.0",
        "@progress/kendo-angular-resize-sensor": "^1.0.0",
        "@progress/kendo-charts": "^1.0.0",
        "@progress/kendo-drawing": "^1.0.0",
        "@progress/kendo-theme-default": "^2.33.2",
        "@progress/kendo-ui": "^2017.2.504",
        "angular-calendar": "^0.7.2",
        "angular2-jwt": "^0.1.27",
        "angular2-perfect-scrollbar": "^2.0.2",
        "angular2-virtual-scroll": "^0.2.0",
        "classlist.js": "^1.1.20150312",
        "cldr-data": "^31.0.2",
        "console-polyfill": "^0.3.0",
        "core-js": "^2.5.0",
        "croppie": "^2.4.1",
        "date-fns": "^1.27.2",
        "flexboxgrid": "^6.3.1",
        "hammerjs": "^2.0.8",
        "intl": "^1.2.5",
        "jquery": "3.1.1",
        "kendo-ui-core": "^2017.2.504",
        "moment": "^2.18.1",
        "ng2-mask": "^1.1.0",
        "ng2-toasty": "^2.2.2",
        "ngx-dropdown": "0.0.22",
        "npm-cli": "^0.1.0",
        "primeng": "^4.1.3",
        "reselect": "2.5.4",
        "rxjs": "^5.4.3",
        "web-animations-js": "^2.2.2",
        "zdravel-carousel": "^3.1.5",
        "zone.js": "^0.8.4"
    },
    "devDependencies": {
        "@angular/cli": "1.4.2",
        "@angular/compiler-cli": "4.3.3",
        "@angular/language-service": "4.1.3",
        "@angularclass/hmr": "^1.2.2",
        "@types/jasmine": "2.5.38",
        "@types/node": "~6.0.60",
        "codelyzer": "~2.0.0",
        "jasmine-core": "~2.5.2",
        "jasmine-spec-reporter": "~3.2.0",
        "karma": "~1.4.1",
        "karma-chrome-launcher": "~2.0.0",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^0.2.0",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "ngrx-store-freeze": "^0.1.9",
        "protractor": "~5.1.0",
        "ts-node": "~2.0.0",
        "tslint": "~4.5.0",
        "typescript": "~2.3.4"
    }
}`

## Expected behavior
Your code (working for weeks) should not stopped working after reinstalling node_modules.. this is NEVER ending story.

## Environment
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.2
node: 7.5.0
os: win32 x64
@angular/animations: 4.3.3
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/compiler-cli: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.4.2
@angular/language-service: 4.1.3
typescript: 2.3.4

Browser:
- [ x] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX
 

## Minimal reproduction steps
1) Download and extract
[AngularBUG.zip](https://github.com/angular/angular/files/1397312/AngularBUG.zip)
2) NPM I
3) ng server --port 4201
4) Navigate in a browser to
http://localhost:4201/login?code=cce20f26-2e1d-4639-b386-fcd5327110db
5) Add breakpoint to  external-login.guard.ts, ln19.. there you would found:

`19: return Observable.of(snapshot.queryParams['code']).switchMap(code => {
 20:   if (!code) {`

it  should jump to Line 20 everytime.. but it throws error... After updating node_modules yesterday.

**Comment by montella1507** [comment]
I have realized, my Guard is not called...  so maybe similar problem like in
https://github.com/angular/angular/issues/19796

**Comment by montella1507** [comment]
I will provide minimal repo in ZIP file soon.

**Comment by montella1507** [comment]
It works with this LOCK file:
[package-lock.zip](https://github.com/angular/angular/files/1397927/package-lock.zip)

I will compare node_modules folders in projects WITH and WITHOUT lock file.

**Comment by montella1507** [comment]
there may be a bug in rxjs 5.5.0  - if i pin the version to "5.4.3" it works. 

I would like to notice @hansl , because angular-cli has for new applications:
    "rxjs": "^5.4.2"

so it would use rxjs 5.5.0 (released 20hours ago) too

**Comment by jayphelps** [comment]
What is the error? I don't see the error itself included, only the stacktrace.

**Comment by montella1507** [comment]
i will close this issue and create new suggestion (pint to 5.4 before fix).
There are problems in 5.5
https://github.com/ReactiveX/rxjs/issues/2977
