### ISSUE TITLE
Can't resolve all parameters for *Service

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#19797]
## I'm submitting a...

<pre><code>
[ X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
With the following classes:

```
@Injectable()
export abstract class AbstractService<T> {

  constructor(
    protected readonly httpClient: HttpClient,
    protected readonly router: Router,
    private readonly endpoint: string
  ) { }
```
```
@Injectable()
export class UserService extends AbstractService<User> {

  constructor(
    protected readonly httpClient: HttpClient,
    protected readonly router: Router
  ) {
    super(httpClient, router, 'users');
  }
```

... I'm getting the following warning:

> Warning: Can't resolve all parameters for AbstractService in ./abstract.service.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x

Not sure why, but if I remove `@Injectable` from `AbstractService` then it works. I really can't say in which version of Angular/AOT it stopped working.

## Environment
```
@angular/cli: 1.4.7
node: 8.1.1
os: linux x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12-4d97271
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.12-4d97271
@angular/material-moment-adapter: 2.0.0-beta.12-4d97271
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/platform-server: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.7
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.4.2
```

**Comment by trotyl** [comment]
Just remove the `@Injectable()` for `AbstractService<T>` class, `@Injectable()` only applies to class being directly used via DI.

**Comment by trotyl** [comment]
It's a feature introduced by https://github.com/angular/angular/pull/19412.

**Comment by rafaelss95** [comment]
Thanks for clarification.

**Comment by giovannipds** [comment]
What should we do when this error happens? I like the idea of abstract services like that.
