### ISSUE TITLE
prefix on component selector and input output

### ISSUE THREAD

**Issue by LinPoLen** [angular/angular#19798]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior

NgModule gives a options `prefix`. it means that compoent/directive selector has a prefix. same as input output. of course final combine result is camelcase in input/output, and dash case in selector

## What is the motivation / use case for changing the behavior?

most of angular components maker will create a prefix, but it is coded in code. when someone forks this project. in order to reuse the component/directive with the consistency, they must rename the prefix by global search.

think about namespace and module. it used for solving this, isn't it?. when there is no namespace. we code almost every class or function with a specific prefix. it's happening on angular

here just mention about css prefix. guilds about css prefix should code with literal. I don't like 
`${cssPrefix}-xxx-yyy-zzz`: 'xxx'
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by LinBoLen** [comment]
actually, it should be a code rule. the input, output, selector has been written in the template. 

another implement is use namespace component `<ns:selector></ns:selector>`. and the namespace of the component can be renamed.

here just want to see how many people have some requirement of this feature.
