### ISSUE TITLE
ElementRef Documentation links to deprecated Renderer class

### ISSUE THREAD

**Issue by literalpie** [angular/angular#19806]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The note at the end of the [ElementRef API](https://angular.io/api/core/ElementRef) links to [Renderer](https://angular.io/api/core/Renderer), which has been deprecated.

## Expected behavior
It should link to [Renderer2](https://angular.io/api/core/Renderer2) which is replacing Renderer

## Minimal reproduction of the problem with instructions
Go to [ElementRef API](https://angular.io/api/core/ElementRef) and look at the warning message at the bottom of the page.

## What is the motivation / use case for changing the behavior?
If people are being pointed to a preferred class, it shouldn't be a deprecated class

**Comment by jasonaden** [comment]
Looks like this was fixed with #19920.

**Comment by jasonaden** [comment]
Ignore above. There was a version that was already closed. But this is still not merged. This issue will be closed when the PR gets merged.
