### ISSUE TITLE
FakeAsync: allow mocking of dates

### ISSUE THREAD

**Issue by vicb** [angular/angular#1980]
ref #1837 

- js: [Jasmine clock](http://jasmine.github.io/2.1/introduction.html#section-Mocking_the_Date)
- dart: [Quiver Clock](https://github.com/google/quiver-dart/blob/6bab7dec34189eee579178eb16d3063c8ae69031/lib/testing/src/async/fake_async.dart#L52)

**Comment by juliemr** [comment]
This has been done for a while.
