### ISSUE TITLE
Nested route animateChild does not play :leave animation in 5.0.0-rc.3

### ISSUE THREAD

**Issue by elclanrs** [angular/angular#19807]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have two nested routes. When I go directly to the nested route, :enter animations play for both routes. When I leave the route only the :leave animation for the first route plays; the nested route disappears immediately.

## Expected behavior

Both :leave animations should play when navigating away from the nested route.

## Minimal reproduction of the problem with instructions

In the example below, both slideins open one after another, playing their :enter animations:

https://angular-slidein-db17ab.stackblitz.io/(slidein:slidein/nested)

(code here https://stackblitz.com/edit/angular-slidein-db17ab?file=app%2Fapp.component.ts)

Now, if you click the backdrop it will navigate to the root route. I slowed down the slide out animation to demonstrate the issue. You can see the nested slidein disappears immediately, but the first slidein plays its animation fine.

## Environment

<pre><code>
Angular version: 5.0.0-rc.3

Browser:
- [x] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.4  
- Platform:  macOS Sierra 

Others:

</code></pre>

**Comment by matsko** [comment]
This should now be fixed via: https://github.com/angular/angular/commit/c2b3792a3b5fa5215fe2ef7e0ac6511086ffe4c1

Beta.3 will have this within its release.

**Comment by elclanrs** [comment]
@matsko, I tried 5.1.0-rc.1 with the same demo, but I still didn't get the result I was expecting. Am I missing something in order to make the child animation play before the parent animation?

**Comment by matsko** [comment]
@elclanrs yes I see that this hasn't been fully fixed yet. Sorry for closing it too early.

I do know what's going on now and I have a fix in mind. I'll update you in the next few days.

**Comment by matsko** [comment]
@elclanrs this fixes it: https://github.com/angular/angular/pull/20787

**Comment by elclanrs** [comment]
@matsko, that seems address the issue, although I still was expecting a different behavior, but I think that may be a different question. Do you know in [this example](https://stackblitz.com/edit/angular-slidein-db17ab-t7vrfx?file=app/app.component.ts) how to make the nested slidein to play the leave animation _first_?

**Comment by elclanrs** [comment]
@matsko, this worked for a while, until I introduced a third slidein, then the leave animations don't play in order, and look buggy.

I updated the example here: https://stackblitz.com/edit/angular-slidein-db17ab-zpw87i?file=app%2Fapp.component.ts

To reproduce the issue, open all three slideins, then click on the backdrop and you should see the buggy animations. If you only open two slideins and click on the backdrop then it works fine; the animations play in order and smoothly.

Is there something I'm missing to make it work?
