### ISSUE TITLE
AOT Unit Tests: Cache NgSummaries loaded in a test

### ISSUE THREAD

**Issue by vikerman** [angular/angular#19817]
We want to make the NgSummary used in a test configurable at a spec level. This would mean that we would end up processing the transitive NgSummary tree per test - which would be too slow.

We should cache all known NgSummary functions with the child tree as the cached value - So that we don't have to walk this tree for every test.

**Comment by tbosch** [comment]
Cache in the `CompilerFactory` and add an argument `ngSummaries` to `configureTestingModule`. This way, the cache is not top level, but only lives between calls to `initTestEnvironment` and `resetTestEnvironment` (which should be called only 1x).

**Comment by tbosch** [comment]
See my PR https://github.com/angular/angular/pull/19996 which @vicb is taking over.
