### ISSUE TITLE
AOT Unit Tests: Error if AOT-ed component is JITed

### ISSUE THREAD

**Issue by vikerman** [angular/angular#19816]
initTestEnvironment now takes in a summary function that can be used to make use of AOT-ed components in unit tests.

There could be a problem when the the summary doesn't link to the Component under test and the test would wrongly end up compiling the Component.

We should add a tree-shakeable flag to the tsickle output for AOT-ed component that indicates that the component has been AOT compiled and JOT compiler should throw and error if it encounters this flag

**Comment by tbosch** [comment]
I think the priority of this is low, as this is just preventing certain user errors, and the implementation is non trivial / needs to be thought through for performance / code size / ... aspects.

**Comment by alxhub** [comment]
Just works with Ivy!
