### ISSUE TITLE
Programatic API to create component and work with TemplateRef

### ISSUE THREAD

**Issue by fkolar** [angular/angular#19812]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently we have easy way how to instantiate a component programatically and once we have an actual component instance we can bind some INPUTs to it and this work. If I want to go even farther and nest different dynamic components I can use nativeElement and its DOM methods to do it (to make component wrap other component).

But the limitation I am having is if the componnet I am instantiating programatically has some ng-template(s) to modify rendered content I have as of now NO way how to pass dynamically created template to my component.

### ex.: I will programatically instantiate MyComponent but I have no way (I just dont know) how to also pass a TemplateRef to the #item

```html
<my-component [value]="data">
  <ng-template #item let-var>
      // my custom template

  <ng-template>
</my-component>
```

## Expected behavior
Ideally what I should be able to do turn any programatically instantiated component to the template or some kind of form and bind it to a other programatically instantiated component.

#### Example
Let's say I have component rendering a list of items and I want to it to modify how items are rendered

in html template I would do something like:

```html
<my-list [list]="data" >
	<ng-template #item let-item>My Name is - {{item.name}}</ng-template>
</my-list>

```
In the code there could be something like:

```ts
let resolvedCompFactory = this.factoryResolver.resolveComponentFactory(MyList);
let myList = this.viewContainer.createComponent(resolvedCompFactory);

let itemDetailFa = this.factoryResolver.resolveComponentFactory(ItemDetail);
let myItemDetail = this.viewContainer.createComponentAsTemplate(itemDetailFa);

// I have have here a way how to bind current context item but this could be just technicallity
myComponent.instance.itemRef = myItemDetail
myComponent.instance.list = ['a', 'b']

```

Others:
Are there at some workaround? I see all the API and code that would help me to do it is private ;-(

Maybe we can have just some API in the first cut:

```ts
let myList = NgConcreteTemplate(viewContainer, factoryResolver)
// named content or template
let content = new NgContent(MyItemDetail, bindingsMap)
content.setTemplateNameI('item');
content.mapVarsToInputs(...);
myList.add(content)
```

The same way I could use this to wrap component with other component

  ```ts
   let content = new NgContent(ButtonComponent, bindingsMap)
   content.add('Click Me');
   somePanelTempalte.add.add(content)
 
  ```
 
  add more component hierarchy:
 
  ```ts
   let containerElement = NgConcreteTemplate(viewContainer, factoryResolver)
   let content = new NgContent(HoverCardComponnet, bindingsMap)
   content.add(createLayout();
   containerElement.add(content)

  ```

I can see `NgContent` is either ElementContent or e.g string in case of button
e.g. In last example HoverCard needs to have ElementContent as it shows some more details

Since Parent (ConcreteTemplate) that is aggregating everything has reference to the viewContainer, resolverFactories, its child elements have access to it to instantiate things. 

Of course while applying bindings you need to have access to Metadata to apply the bindings. When JIT is used its probably easier as you can retrive MetaData for AOT you would probably utilize the outcome of the `"annotationsAs": "static fields"` feature of the _angularCompilerOptions_

**Comment by fkolar** [comment]
Maybe somewhere in the core I could have some _NgTemplate_ representation that would inherit from some generic _ContainerElement_ which is having method to add/remove its content.

I see this **NgTemplate** in this context a such _named template_ which I am passing to the component. And this template needs to have a ability to add its content as well

```ts
class NgTemplate extends NgContainerElement {
	protected templateName: string;
	protected bindingsMap: Map<string, any>;

	constructor (tagName: string, bindings: Map) {
			//....
	}	
	isNamedTemplate( ..){}
}
```
In many cases `<ng-template> `does not have a name but here I want to bind a content  for named templates

The instantiated component could be an instance of this container (or some container) and having ability to dynamically _add / remove_ a content

```ts
class NgConcreteComponent extends NgContainerElement
{
	constructor (tagName: string, bindings: Map) {
			//....
	}	
}
```

Then in the code I could simply instantiate a _NgTemplate_ give it a name just like I would do it in the template.

```html
<my-list [list]="data" >
	<ng-template #item let-item>My Name is - {{item.name}}</ng-template>
</my-list>
```


```ts
let myListComponent: NgConcreteTemplate =...;
let content = new NgTemplate("NgContent", MapUtils.map(...);       
content.setTemplateName('item');
content.add(createTemplateContent(MyDetailItemComponnet));
myListComponent.add(content);
```

When we have a actual representation of Templates, Contents, Components we could also hide the complexity of instantiating new component and all these activities like:

-   resolveComponentFactory(wrapperType) to get a componentFactory
- resolveDirective(wrapperType) to get a metaData
- createComponent(resolvedCompFactory) to add component to the view

could work behind the scenes

why not to have just:

```ts
constructor (component: Componnet) {}

let someConcreteComponentContainer = this.component.new(Type)
someConcreteComponentContainer.setBindings(Map...)
someConcreteComponentContainer.addNameContent(Map...) // or named Template

// or even wrap component with other component

let someChildComponent = this.component.new(Type2)
someChildComponent.setBindings(Map...)

someConcreteComponentContainer.add(someChildComponent)

```

**Comment by jasonaden** [comment]
@fkolar You're right, there's not a good API to achieve what you want at this time. However, there are plans to make something like this happen so you have more flexibility to dynamically create/compile templates.

You're correct that all the APIs that would allow you to do this yourself are currently private. This was intentional, because those APIs have gone through significant changes between v2, v4, and v5. I suggest waiting for updates coming over the next 6 months. If that doesn't work for you, reach out to our Developer Advocates on Twitter (@robwormald and @stephenfluin) who are both familiar with this problem and might be able to point you in a more helpful direction.

I'm going to close this request as we've already got this work in-queue and planned for an upcoming release.

**Comment by sgronblo** [comment]
Aren't you supposed to close it when it has been merged so the progress can be tracked here? I ran into this when trying to figure out how to write test for a component that relies on ng-template. It's now 6 months later, do we have a better story for this available now?

**Comment by antch** [comment]
I'm also not sure why this was closed. It is now over a year later and I do not see any method of achieving this. Hopefully this is not yet another "wait for Ivy" feature...

**Comment by jasonaden** [comment]
@sgronblo @antch Sorry for not having updates here. I believe at the time I originally closed this, there were plans to more immediately enable this type of feature. Some of these plans ended up in Angular Elements. The rest have been deferred to after Ivy lands.

And I understand you don't want to see "wait for Ivy". However, the team is currently focused on Ivy as the highest priority because its impractical to add features to the existing compiler. Especially features that require reasonable complexity to implement, when in Ivy they will be quite straight-forward (such as this feature). Therefore, the unfortunate update is it needs to wait for Ivy.

**Comment by antch** [comment]
Ok, thanks for taking the time to deliver the tough news. I do need to ask though, if these tickets are being closed how are these requests tracked after Ivy is finished?
