### ISSUE TITLE
Change detection is not updating the view when you mark for check.

### ISSUE THREAD

**Issue by greg-md** [angular/angular#19814]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When change detector is marked for check after an external http response(in my case a Facebook SDK callback) continued by a timeout(or a new angular http subscription), the view is not updated with the new values.

If any other event is triggered in browser after that, the view is being updated with new values.

**Note 1**: If we remove the timeout from `setTimeout`(or set a lower value, like `1`), the view will be updated as expected.

**Note 2**: It is the same even if we remove the `ChangeDetectionStrategy.OnPush` strategy.

## Expected behavior

The view should be updated with the new values when we mark for check.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/aPu9e1zwUxSAGVScLYvq?p=preview

1. Click the "Set user" button ==>> User is not displayed after 1 second.
2. Click the "Fire an event" button ==>> User is displayed.

## What is the motivation / use case for changing the behavior?

The view is not updated properly. Have to wait for the next event.

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) version Version 61.0.3163.100 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.2  
- Platform:  Mac

Others:

</code></pre>

**Comment by alexzuza** [comment]
Callback is executed in root zone.  Try using `ngZone.run`

**Comment by greg-md** [comment]
Thank you @alexzuza, it worked. If it's an expected behavior, I can close.

**Comment by gkalpak** [comment]
From a quick look, it seems that `FB.api()` adds a script to the page and executes a callback (which eventually executes your callback). So, since this added script is run outside the Angular zone, you callback is too.

As @alexzuza said, you need to enter the Angular zone again for your change to notify the ChangeDetector. E.g.:

```ts
FB.api('/me', () => {
  // This is run outside the Angular zone. We need to get back in.
  this.ngZone.run(() => {
    setTimeout(() => { ... })
  });
});
```
