### ISSUE TITLE
AOT Unit Tests: Need overrideTemplate support in AOT mode

### ISSUE THREAD

**Issue by vikerman** [angular/angular#19815]
In order to help developers switch to AOT during unit testing we need to make it easier to mock child components.

The way decided would be to have a TestBed.overrideTemplate(Component, newTemplate) function that would JIT compile a new template for an existing AOT-ed component.

**Comment by tbosch** [comment]
See my PR https://github.com/angular/angular/pull/19996 which @vicb is taking over.

**Comment by IgorMinar** [comment]
this was fixed by #20224
