### ISSUE TITLE
docs(aio) PhoneCat upgrade tutorial doesn't work with TypeScript >= 2.2.1

### ISSUE THREAD

**Issue by wags1999** [angular/angular#19813]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In the PhoneCat upgrade tutorial (https://angular.io/guide/upgrade#phonecat-upgrade-tutorial), after "Upgrading the Phone Service", I receive an error in the browser console:
<pre>
Uncaught ReferenceError: exports is not defined
    at phone-list.component.js:2
</pre>
If I downgrade TypeScript to <2.2.1, then everything works.

This is because TypeScript 2.2.1 added functionality that adds a <code>Object.defineProperty(exports, "__esModule", { value: true });</code> at the top of every .js file when the .ts file includes an imports statement.

## Expected behavior
The application runs without error.

## Minimal reproduction of the problem with instructions
Follow the PhoneCat upgrade tutorial through the end of the "Upgrade the Phone Service" section: https://angular.io/guide/upgrade#upgrading-the-phone-service

## What is the motivation / use case for changing the behavior?
It appears the tutorial was valid up until TypeScript 2.2.1 was released.  Now that Typescript 2.2.1+ is out, there needs to be clarification on the best way to import upgraded components into Angular 1 components.

## Environment

<pre><code>
Angular version: 4.3.4

Browser:
- [X] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.4
- Platform:  Windows

Others:

</code></pre>

**Comment by gkalpak** [comment]
If this is still an issue, it will be fixed as part of #19625. Let's track it there.
