### ISSUE TITLE
Http: naked false/0 value is not correctly parsed when using json as response type

### ISSUE THREAD

**Issue by dzonatan** [angular/angular#19825]
## I'm submitting a...

<pre><code>[X] Bug report</code></pre>

## Current behavior

```ts
http.get<boolean>(`/api/canYouSeeMe`)
  .subscribe(x => console.log(x));
```

In such case if backend returns `false` or `0` straight in the body (without any nested object) the console print outs `null`. While `true` or `1` keeps what it is.

Yes. I know that it's strongly recommended for json APIs to return pure values wrapped into some object, but still.. it's not forbidden and seems like javascript supports parsing such values.

And that's happening because of this line:
 https://github.com/angular/angular/blob/230b98d4ddffee4df25f62ff3c9ac39a2329abf6/packages/common/http/src/response.ts#L265

Obviously:
```ts
this.body = true || null; // true
this.body = false || null; // null
this.body = 0 || null; // null
```

## Expected behavior

Keep the **falsy** (`false`, `0`) value unchanged.

## Current workaround

Set the `responseType` to `text` and parse it for yourself.

## Environment

<pre><code>Angular versions: 4.x, 5.0.0-rc.3</code></pre>

**Comment by trotyl** [comment]
Relates to #19195 about request counterpart.

**Comment by michaelsanford** [comment]
Probably related, a naked empty array `[]` appears to get stringified to `"[]"`.
