### ISSUE TITLE
[HttpClientModule] HttpRequest params's property can not delete success in HttpInterceptor

### ISSUE THREAD

**Issue by liaosong** [angular/angular#19821]
The angular version is `5.0.0-rc.2`

My Interceptor as follow
```
export class RequestInterceptor implements HttpInterceptor {

    constructor() {
    }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        const url = req.url
        const id = req.params.get('id')
        let cloneReq: HttpRequest<any>
        if (req.url.indexOf(':id') > -1 && id) {
            cloneReq = req.clone({
                url: url.replace(/:id/, id.toString()),
            })
            cloneReq.params.delete('id')
        } else {
            cloneReq = req.clone({})
        }

        return next.handle(cloneReq)
    }
}
```
The `id` property of `params` is not delete success. The Debug image as follow.
![image](https://user-images.githubusercontent.com/3927282/31813265-5037371c-b5b8-11e7-896b-9db19501f8e9.png)

**Comment by trotyl** [comment]
`HttpParams` are immutable, all methods are stateless.

**Comment by liaosong** [comment]
@trotyl Is there a good way to delete the `id`?

**Comment by trotyl** [comment]
You'll need to assign the new `HttpParams` like url in `.clone()` method.

**Comment by liaosong** [comment]
@trotyl Thanks, It works for me as such code.
```
cloneReq = req.clone({
     url: url.replace(/:id/, id.toString()),
     params: req.params.delete('id'),
 })
```

**Comment by erbsenkoenig** [comment]
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] [HttpClientModule] HttpRequest params's property can not
delete success in HttpInterceptor (#19821)" gesendet am 23.10.2017 04:23:00
.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
