### ISSUE TITLE
Date pipe: add skeleton formats

### ISSUE THREAD

**Issue by JohnKis** [angular/angular#19823]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Date pipe doesn't offer a way to use custom date formats that respect the ordering of the date components according to the locale.

## Expected behavior
There should be a way to specify a custom format while keeping ordering of the locale. In #11661 it was suggested that this should be achievable by adding support for CLDR skeletons (see "Additional Date-Time Formats" in [http://cldr.unicode.org/translation/date-time-patterns](http://cldr.unicode.org/translation/date-time-patterns))

The following example illustrates the expected output of the pipe with and without respecting the ordering of the locale:
```
// LOCALE_ID: 'en-GB'
{{ date | date:'EEE d MMM' }}
// Current: Tue 20 Oct
// Locale ordering: Tue 20 Oct

// LOCALE_ID: 'en-US'
{{ date | date:'EEE d MMM' }}
// Current: Tue 20 Oct
// Locale ordering: Tue, Oct 20

// LOCALE_ID: 'hu-HU'
{{ date | date:'EEE d MMM' }}
// Current: K 20 okt.
// Locale ordering: okt. 20., K
```

## What is the motivation / use case for changing the behavior?
I believe it would be a useful feature for internationalised apps. For instance, I have multiple apps that render only specific date components that cannot be expressed using a standard format.

## Environment

<pre><code>
Angular version: 4.1.3
It is still the case in the most recent Angular version
Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v6.3.0
- Platform: Mac

Others:

</code></pre>

**Comment by ocombe** [comment]
To do that we might have to add the available formats to the extra locale data files: https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/en/ca-generic.json#L333 and then follow this guide to use the correct format: http://www.unicode.org/reports/tr35/tr35-dates.html#availableFormats_appendItems

**Comment by petebacondarwin** [comment]
It doesn't look like there is much interest in this feature, and it would increase the size of our local files and code in `@angular/common` to handle it.
