### ISSUE TITLE
Metadata being output in the wrong location w/ Angular 5

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#19832]
### Steps to reproduce
* Clone https://github.com/jelbourn/metadata-out-repro
* `npm i`
* `./node_modules/.bin/ngc -p ./src/cdk/tsconfig.json`

### Expected behavior
Metadata is output to `dist/packages/cdk`

### Actual behavior
Metadata is output to `dist/packages/cdk/cdk`

The reproduction captures an issue affecting Angular Material when using Angular 5.
cc @tbosch @chuckjaz, originally reported by @crisbeto and @DevVersion

**Comment by Toxicable** [comment]
Without investigating your case specifically (so I could be wrong) it looks like a dupe of this?
https://github.com/angular/angular/issues/19718

**Comment by tbosch** [comment]
Yes, agree.

**Comment by IgorMinar** [comment]
fixed by #19772
