### ISSUE TITLE
ngSubmit not working in IE for Angular 5

### ISSUE THREAD

**Issue by Jeowulf** [angular/angular#19830]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Clicking "enter" does not work in Internet Explorer for Angular 5 on a reactive form with ngSubmit

## Expected behavior

Pressing the enter key would cause my reactive form to trigger the ngSubmit

## Minimal reproduction of the problem with instructions

Steps to reproduce:
1. Create a reactive form
2. Add some standard form input fields
3. In Internet Explorer press enter when filling out the form to see ngSubmit fail to pick up the keypress
## What is the motivation / use case for changing the behavior?

Form submission (this issue existed and was fixed in Angular 4)

## Environment
IE on a windows machine
<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by FHappy** [comment]
+1

**Comment by Jeowulf** [comment]
Issue was with our implementation

**Comment by tan9** [comment]
Same problem here, ngSubmit work on Chrome but no in IE.

After some investigation, we found that IE is more strictly than Chrome since it won't treat `"submit "` same to `"submit"`:
```html
<button type="submit ">A button work in Chrome and not in IE</button>
```
