### ISSUE TITLE
Replace the picture on the official site

### ISSUE THREAD

**Issue by splincode** [angular/angular#19831]
The official website (angular.io) on the map shows the import from Angular2. However, the current stable versions are imported differently from @angular/core. Also, in this picture, in principle, nothing is visible because of the translucent overlap. This can somehow be fixed?

![image](https://user-images.githubusercontent.com/12021443/31831939-d944ce1a-b5cd-11e7-8174-48c0959ed890.png)

**Comment by StephenFluin** [comment]
How's this:

![app-tooling](https://user-images.githubusercontent.com/165056/31840971-63b9ec7e-b59c-11e7-9126-d137e022db1e.png)

**Comment by splincode** [comment]
@StephenFluin, This option looks good, yes

**Comment by splincode** [comment]
The pictures are completely unreadable, very bad guys. Sorry for perfitsionizm, but he needs it, because this is a social project in the first place.

![image](https://user-images.githubusercontent.com/12021443/33287225-16b7ae5c-d3c9-11e7-9f75-ca0f0cbca3cf.png)

**Comment by splincode** [comment]
I suggest doing so for the image:

```
max-width: 100% !important;
width: 400px;
margin-right: 50px;
```

![image](https://user-images.githubusercontent.com/12021443/33287458-bfc16f4c-d3c9-11e7-90c5-93de0e1ba5be.png)
