### ISSUE TITLE
Service worker api docs missing on next.angular.io

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#19838]
https://next.angular.io/api

Please add the service worker entry-point(s) to the dgeni configuration: https://github.com/angular/angular/blob/910735d73279d211938b414f2716ae0614f1d720/aio/tools/transforms/angular-api-package/index.js#L41-L68

**Comment by gkalpak** [comment]
It might also be a good idea to add it as a valid commit-message scope in [CONTRIBUTING.md][1] and in `authors-package`:

https://github.com/angular/angular/blob/910735d73279d211938b414f2716ae0614f1d720/aio/tools/transforms/authors-package/api-package.js#L12-L25

##
Also, was `service-worker` intentionally not included in `test-main.js`? How are the tests run?

https://github.com/angular/angular/blob/910735d73279d211938b414f2716ae0614f1d720/test-main.js#L33-L65

[1]: https://github.com/angular/angular/blob/910735d73279d211938b414f2716ae0614f1d720/CONTRIBUTING.md#scope

**Comment by erbsenkoenig** [comment]
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] Service worker api docs missing on next.angular.io
(#19838)" gesendet am 23.10.2017 11:11:42.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
