### ISSUE TITLE
Translation into Russian documentation

### ISSUE THREAD

**Issue by splincode** [angular/angular#19834]
Hello. I wanted to ask if there is any working group to translate any stable documentation into Russian? I would be very glad to translate into Russian for the beginning developers from Russia, so that the popularity of Angular would increase. But I see that with the localization of the documentation, not everything is as good as it is in the React or Vue. It would be great if the official site had an architecture like MDN - Mozilla, so that it would be easy to bring new changes to any audience (Italian, Spanish, French, Russian).

It would be a significant event, if to the exit Angular 5, there was such an opportunity directly on the official site to deal with the translation of documentation. Or at least through the repository, because I want to engage in the popularization of the framework.

**Comment by juleskremer** [comment]
Hi there, we are currently in the process of moving all docs samples to align with the CLI; after this work is done; I am hopeful to have a method for localization of the docs.  We wanted to hold off until after the CLI alignment so that there was no wasted efforts.

**Comment by luillyfe** [comment]
@juleskremer Any advance in this topic? I am interested.
