### ISSUE TITLE
Can't override providers in rc.2

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#19848]
Simplified version of what I see in aio:
```
@Component({})
class MatIconComponent {
  constructor(http: Http) {}
}

@NgModule({
  providers: [HttpModule]
});
class MatIconModule

@Injectable()
class MyCustomHttp {}

@NgModule({
  imports: [MatIconModule],
  providers: [
    {provide: Http, useClass: MyCustomHttp}
  ]
})
class AppModule {}
```

## Current behavior
in 5.0.0-rc.2 as opposed to 5.0.0-beta.3

## Expected behavior
MatIconComponent is injected with MyCustomHttp and Http doesn't appear anywhere in the generated code, which makes it eligible for tree-shaking.

**Comment by tbosch** [comment]
`Http` is the token here, we always kept references to it (in 4.x and 5.0.0-beta). In general, providers in modules were never tree shakable...

**Comment by tbosch** [comment]
To reproduce, follow the same steps as in https://github.com/angular/angular/issues/19857 for 5.0.0-rc.2 as opposed to 5.0.0-beta.3.

**Comment by IgorMinar** [comment]
Maybe I should reword the problem. In 5.0.0-beta.3 (built at master of #19857) we were able to eliminate `Http` class and many other things it references from the bundle. In 5.0.0-rc.2 the `Http` class is retained.

This is what the class looks like once transpiled:
```
function Http(_backend, _defaultOptions) {
                this._backend = _backend;
                this._defaultOptions = _defaultOptions;
            }
```

**Comment by chuckjaz** [comment]
This appears to be a duplicate of #19857.

The following code is begin emitted by `ng`:

```ts
ResourceListComponentNgFactory = createComponentFactory("aio-resource-list", ResourceListComponent, View_ResourceListComponent_Host_0, {}, {}, []), styles_MatIcon = (createNgModuleFactory(MatIconModule, [], function(_l) {
            return moduleDef([ moduleProvideDef(512, ComponentFactoryResolver, CodegenComponentFactoryResolver, [ [ 8, [] ], [ 3, ComponentFactoryResolver ], NgModuleRef ]), moduleProvideDef(6144, DIR_DOCUMENT, null, [ DOCUMENT$1 ]), moduleProvideDef(4608, bidi_es5_Directionality, bidi_es5_Directionality, [ [ 2, DIR_DOCUMENT ] ]), moduleProvideDef(5120, icon_es5_MatIconRegistry, ICON_REGISTRY_PROVIDER_FACTORY, [ [ 3, icon_es5_MatIconRegistry ], [ 2, Http ], DomSanitizer ]), moduleProvideDef(512, CompatibilityModule, CompatibilityModule, []), moduleProvideDef(512, BidiModule, BidiModule, []), moduleProvideDef(256, MATERIAL_SANITY_CHECKS, !0, []), moduleProvideDef(512, core_es5_MatCommonModule, core_es5_MatCommonModule, [ [ 2, MATERIAL_SANITY_CHECKS ] ]), moduleProvideDef(512, MatIconModule, MatIconModule, []) ]);
        }), [ ".mat-icon{background-repeat:no-repeat;display:inline-block;fill:currentColor;height:24px;width:24px}" ]), RenderType_MatIcon = createRendererType2({
            encapsulation: 2,
            styles: styles_MatIcon,
            data: {}
        })
```

which is invalid for the reasons described in #19857. The `styles` field should be `style: []` and the `styles_MatIcon` should be elided but is, instead, initialized with the result of  a`createComponent` which is invalid as this is a list of styles not a reference to a component factory.

The code generated as input to uglify contains `var style_MatIcon = [];` but was replaced by something in the uglify webpack pipeline as a call to a factory.

**Comment by IgorMinar** [comment]
this problem has the same root cause as #19857 which I documented here: https://github.com/angular/angular/issues/19857#issuecomment-338953836

I'm marking this as resolved.
