### ISSUE TITLE
Reconnect TS sourcemaps 

### ISSUE THREAD

**Issue by kara** [angular/angular#19841]
We temporarily removed sorcery while we were waiting for the new version of tsickle and TS 2.4. Now that these updates are in, we should be able to hook sorcery (or the rollup plugin) back up.

**Comment by jasonaden** [comment]
We will need to put back [this file](https://github.com/angular/angular/blob/4.4.x/scripts/build/map_sources.js) and the calls to it (such as [this one](https://github.com/angular/angular/blob/4.4.x/build.sh#L128)).

**Comment by IgorMinar** [comment]
while we are fixing this we should ensure that we also resolve #14021 as well.

**Comment by IgorMinar** [comment]
This is still a problem.

**Comment by petebacondarwin** [comment]
Note that we have our own library that can do what sorcery did. Currently it is in ngcc: https://github.com/angular/angular/tree/master/packages/compiler-cli/ngcc/src/sourcemaps
But will soon be in ngtsc: https://github.com/angular/angular/pull/37114

**Comment by jelbourn** [comment]
@petebacondarwin can this issue be combined/duplicated into another issue? Maybe a tracking issue for ngtsc?

**Comment by petebacondarwin** [comment]
I think this is obsolete since we now use Bazel to build Angular. So in fact we should close this in favour of #23520, which I will re-open.
