### ISSUE TITLE
Feature Request: JSON Schema for @angular/service-worker

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#19847]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There isn't JSON schema file for `ngsw.json`. 

## Expected behavior

There is that and it should be used in testing of `@angular/service-worker` .

## What is the motivation / use case for changing the behavior?

Angular CLI has a schema for `.angular-cli.json` and it is very useful to validate my JSON file. I think it will be better that ngsw.json has its own schema.

cc/ @alxhub

**Comment by cyrilletuzi** [comment]
PR done in #27859
