### ISSUE TITLE
HttpClient interceptor issue with zonejs v0.8.18

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#19853]
## I'm submitting a...

<pre><code>[x ] Bug report  </code></pre>

## Current behavior
When using interceptor to convert urls to absolute urls with `zonejs v0.8.18` it doesn't work and throw error. It works fine with `zonejs v0.8.17`

## Expected behavior
It should work as as it was working with `zonejs v0.8.17`

## Minimal reproduction of the problem with instructions

```
import { Injectable } from '@angular/core';
import { HttpEvent, HttpInterceptor, HttpHandler, HttpRequest } from '@angular/common/http';

import { Observable } from 'rxjs/Observable';

@Injectable()
export class MyInterceptor implements HttpInterceptor {

    constructor() { }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        let modifiedRequest: any;

        modifiedRequest = req.clone({ headers: req.headers, url: 'https://reqres.in/api/users' + req.url, body: req.body });

        return next.handle(modifiedRequest);
    }
}
```

**Comment by naveedahmed1** [comment]
@ericmartinezr whats wrong with above? Isn't it an issue?

**Comment by JiaLiPassion** [comment]
@naveedahmed1, could you provide a reproduce repo? and the detailed error information. Thanks!

**Comment by JiaLiPassion** [comment]
@naveedahmed1 , I created a project with `angular/cli` and add your `interceptor` with `zone.js 0.8.18`, everything works fine. so please post a reproduce repo.

**Comment by erbsenkoenig** [comment]
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] HttpClient interceptor issue with zonejs v0.8.18
(#19853)" gesendet am 23.10.2017 03:05:20.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by naveedahmed1** [comment]
@JiaLiPassion Thank you so much for your reply. Can you please also try it with server side rendering and confirm if it works? In my case it started working when I disabled SSR but with SSR its not working.

**Comment by erbsenkoenig** [comment]
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] HttpClient interceptor issue with zonejs v0.8.18
(#19853)" gesendet am 23.10.2017 11:31:45.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by naveedahmed1** [comment]
@JiaLiPassion kindly close this issue, it was due to setInterval/clearInterval issue as reported here

https://github.com/angular/zone.js/issues/934

**Comment by erbsenkoenig** [comment]
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] HttpClient interceptor issue with zonejs v0.8.18
(#19853)" gesendet am 23.10.2017 13:44:27.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by JiaLiPassion** [comment]
@naveedahmed1, sure, the https://github.com/angular/zone.js/issues/934 have been fixed, please wait for the next release of `zone.js`.

**Comment by naveedahmed1** [comment]
Thank you so much @JiaLiPassion for the update :)
