### ISSUE TITLE
Angular custom validators priority

### ISSUE THREAD

**Issue by NourEddinKhanjar** [angular/angular#19851]
## I'm submitting a...
[ ] Feature request

## Current behavior
When i apply multiple custom validators directives on template driven forms input, i can not control the ordering of executing the validators.
For example:
"input  type="number" ngModel requiredValidator onlyNumberValidator moreThanTenValidator "

I assumed that directives should never rely on priority:

https://stackoverflow.com/questions/35756253/controlling-order-of-directive-evaluation-in-angular-2

"Component directives may not use the following attributes:
priority and terminal. While Angular 1 components may use these, they are not used in Angular 2 and it is better not to write code that relies on them."

## Expected behavior
Validators should execute in the same orders they declared on the DOM which means the requiredValidator should be the first executed one then the onlyNumberValidator and  moreThanTenValidator.

**Comment by jasonaden** [comment]
Thanks for the issue. As you can see from the StackOverflow post, there isn't an intention to support directive priority. However, in the case of validators they often have a "waterfall" effect where they should be run in a certain sequence.

I've assigned this to the Forms as well as Compiler teams to take a look at and determine if this is something that can/will be supported.
