### ISSUE TITLE
ngc doesn't have an option not to generate source template maps

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#19858]
## I'm submitting a...

<pre><code>
[x] Feature
</code></pre>

## Current behavior
The template source maps we generate make source-map-explorer unusable (see #19840). It would be nice if I had an option via angularCompilerOptions to disable the source map generation just for templates.

ngc does honor the `compilerOptions` sourceMap` flag, but that turns off source maps even for typescript code.

## Expected behavior
I'd like ngc to honor the `compilerOptions` flag as it does today, but allow the template to be disabled just for template source maps via a flag in `angularCompilerOptions`.

## Environment

<pre><code>
Angular version: 5.0.0-rc.2

**Comment by tbosch** [comment]
Soon we will inline the generated code into the .ts file itself. What would we do then? There won't be any .ngfactory files anymore. Where would we then attribute the generated code to?

**Comment by tbosch** [comment]
Closing this as we determined the better option for this use case would be to disable sourcemaps altogether for `ngc`, which is already possible (see the discussion in https://github.com/angular/angular/issues/19840#issuecomment-339833800).
