### ISSUE TITLE
*ngFor bug - referring to unknown properties should throw an error

### ISSUE THREAD

**Issue by shairez** [angular/angular#19863]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using `*ngFor`, for example: 

`*ngFor="let item of items`

When `items` is not defined on the component class we don't see any errors in the console or in the CLI. 

Maybe we've misspelled the collection name? maybe it's just a copy paste mistake? 
Currently the app just shows an empty template without any error message. 

## Expected behavior
The compiler should throw an error if we are referring to an unknown property / collection of the component. 

For example, the language service (via vs code) *DOES* report unknown properties

![image](https://user-images.githubusercontent.com/1430726/31868020-d8ec69e8-b7a1-11e7-8c2b-4eddf1ecc3d1.png)

## Minimal reproduction of the problem with instructions

Here is a demo of the problem - 
https://stackblitz.com/edit/angular-b4hwju

Code is at `app/app.component.ts`

Open the console and see no errors. 

## What is the motivation / use case for changing the behavior?

It could save valuable debugging time if we had a clear error message like the one in the language service. 

## Environment

<pre><code>
Angular version: 5.0.0-rc.1

Browser:
- [x] Chrome (desktop) version  61.0.3163.100

 
For Tooling issues:
- Node version: 6.11.4
- Platform:  Windows

Others:

</code></pre>

**Comment by erbsenkoenig** [comment]
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[angular/angular] *ngFor bug - referring to unknown properties should
throw an error (#19863)" gesendet am 23.10.2017 02:41:43.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by trotyl** [comment]
@erbsenkoenig Could you please cancel the auto-reply to GitHub emails? It would disturb everyone in the repo.

**Comment by erbsenkoenig** [comment]
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] *ngFor bug - referring to unknown properties should throw
an error (#19863)" gesendet am 23.10.2017 06:16:06.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by trotyl** [comment]
Type-checking for templates only available in AOT, not JIT.
It's reported correctly in [AOT Editor](https://edit.ng/#,xVltb9s2EP4rrL84aSMpbothc50g3UsxDGsH9GUbMO8DLdEyY4rUSCqJZ_i_706UZMuSJcctVn.wJPLuee6o4_FErgdBqJJUSSatL2N_YRMxGA8mi9H1z0wIRdZrSRO22TzBpqmcZAL.CfwmgpOnMn6j9NV0IJgl3LKEqHl.NdPB9XrtmjabSSA46gagPLjYZbQGyDg8aUvW32t1b5h.q6JMsA2Za5WQ4Q2VcSaoDlJB7VzpxJs5seGrqSw1fygBL8i72OlfkNdpKnhILVfyPZs38EKlGWJM5U2lfrZG3wwTLLRKj8lwgWPg3SstIo.m6fAC.8EpNIZ90mJMpgO_OYLTAQhuzqeSPeQGhoIaQ_IB_QOxKkKSE.IIj4mxmsuYXAHka2fjdAD2bXITS7echc5vMyZ_1cbs79y8iAGdzv1GiRZWJwc3elW1dYrOlLJgHk0PCLU4.5Zy6axCHzf42o1dCWb80OBLxwYuI_awDTm4YpQsGI3yGJskzFISLqg2zEKQffr4xvsWAmvbhwMHHXec3SP1dEBCJS1YBI33PLKLq4jd8ZB5.cMF4ZJbToVnQirY1ci_rKEtrE099k_G70D9T._Taw89hIGcCVaD5uyKRTErlS23gl3_qMIsgf5J4J7zLsHlkmgmQMl5v2AMzVxoNoe2IOLG7owL9ARO8YnnkUxCYCEkgVHGmWUXzDBiFcngUgVyAqGowSuSaubNMi4sCibMEM_bgvWZgs6bcRBkMl3GPhAHDYKb5_6lf.nNYKz80WUAdDmb59iCiLE0zXQqmEeTGdOVQ_.zHRBVPFZeCjxfywTk9mYiY7Fmq69mhHsXYAKTTRtMqHlqidFhKxlmR._WAMVLfxSEgkMYBmbBEz_h0r_F_D4JHMZReP9CCIOaC_ji4bMwhJKxZywNlx4kJpjiJ4LCaGO29zADRNTSm0t_5L8I3rvmEwDNysACAUMHQN_5L0bFHM9bO.DsKsVUZtmDDW7pHXXNRYoh5I5qUrz_35k2kNthoRjevPRf.C9xFUOZIMjFyvDYlatFyp58E7YUOIDmVk0U.OC8gsw457FbmvAHOXMB60n1TMhQpsl4iAtqY7yGpdTmorwLIMRTWGaFMJjKChoiFI2YJvcLpvMsKJRaEigJQAYWTlNqJ7hM7XLjwg3Uw4udtlRkMZcQ4UpiXwBLFrOmeE2_fAiQK..FV1ZTrNcPY.dZvfHZ_pA.A4JZJiOY5LmEnyVRB26SOKP2kPNm0gOOQn3wKRdQPrUQuI6tlvs1GPcpc7VO0kbttk_eEOj2c1_8UeRetIK6gYe9RlSCvSPSZVuJ0mkjTouGPXljNxmKdAJrldmW8S6aG.BNT7dcTqeTDf02DTLX2u1ILtOJXSaiBnzVAYD72WqXouzbYWmdINGyOTegrQcdRLrnXbQM6Gi0OhHbQ91eghmP.KkEqNtLECqmQ96Wno4jKfWPIBK4_uI3zOlcFUQv3ZKtQhWxk7lK_V4iNYOUcAcopzJVAP1UICXoyQFXqPfSlPnuVJ5Sv58IvvBapv.xNLl2L4l.uD351aBuLwHUdRCXUK.cylIB9FJZCh.up9Lkyv0UzNjP8KVQ78nIVPKEtqeCna5HLdJbvUeVDl2mNEqYz6sajrRwKxYcqq12bD52UFrqqjbyLI01lOQBfIbZlnqq6O5hLaQ8B9K3OEP1fDjosPh.1KjnX7nNIGzjxcK6g_no4vxYuryo7iI8slhvq9WPsqER.4ds.cKBf4ptZY19tI1ftrQ_ymYs1Q_ad2SpfxSRq9MPUh0q_Vtq_S46awSfleD5w83I_8Yf1YR2V9P8voawSpnb5ahgqpab5_5zfxQAarBtbJiA.z5ZlfCKRyiCYaK6e9Ro215IabikMTMkYnMu4aoyTWiakqJju5Hh5Gr7CSBXe8YdBy7BCLzs2bjZuccB2FMEepoJ.9ODZRLfAYDc7q5ku.q4QbWnPnzqFxsY62JzZFzf2agB5PIyNlmSUL06UmlTDZ.72Zzne0M7W1iToNiwn8xUtHJ7WnvHJte_Ag_Gke.jdL3vEZtgxXaTO_04y_d1zkv7_JDacHEWwuqloHBhWivtQyhEZdN5i.WFxWAUnj3gkUT.DmunUqSc9cVRC3nUydTOOci7.A3FY6VVhVA_OZq7Xre7VvohVHw2fJ9JiUdDr3_7SIocHg3RnT3Tzs796qTGcRaMZy1WnL8abP4D).

![image](https://user-images.githubusercontent.com/6059170/32043044-3bc98f64-b9ff-11e7-9e90-f421f7e097fb.png)

**Comment by shairez** [comment]
Thanks @trotyl  !

**Comment by WizardPC** [comment]
I know it's close, but i lost 2hours searching why my dropdown was empty, and i mispelled my collection...

Why it's not possible to have an error ? ngFor can't verify if the collection is undefined and throw an error/warning in the console ?
