### ISSUE TITLE
Angular 5.0.0-rc.3 doesn't compile AOT version

### ISSUE THREAD

**Issue by yuguzura** [angular/angular#19860]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Following this guide
https://angular.io/guide/aot-compiler

Angular ngc compiler doesn't create "aot" directory
 "angularCompilerOptions": {
   "genDir": "aot"
}

## Minimal reproduction of the problem with instructions

Files tsconfig.aot.json and package.json
included in 
https://github.com/yuguzura/angular-issue repo

## Environment

<pre><code>
Angular version:  5.0.0-rc.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.4 
- Platform:  Linux 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/19269#issuecomment-330554724

**Comment by erbsenkoenig** [comment]
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] Angular 5.0.0-rc.3 doesn't compile AOT version (#19860)"
gesendet am 23.10.2017 05:05:11.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
