### ISSUE TITLE
Route param does not allow '@' before it, for example '@:param' will not work

### ISSUE THREAD

**Issue by lansana** [angular/angular#19868]
## I'm submitting a...
[X] Feature request

## Current behavior
Trying to access the path `/@username` in my app, but the catchall route is being caught instead.

## Expected behavior
I want it to navigate to my ProfileModule that is at the `@:username` path.

## Minimal reproduction of the problem with instructions
Add this route to your app routes:

```typescript
const routes: Routes = [
    {
        path: '',
        pathMatch: 'full',
        loadChildren: './home/home.module#HomeModule'
    },
    // ...
    {
        path: '@:username',
        loadChildren: './profile/profile.module#ProfileModule'
    },
    {
        path: '**',
        redirectTo: 'foo'
    }
];

export const AppRoutesModule = RouterModule.forRoot(routes);
```

## Environment

Angular version: 4.3.5

Browser: Chrome (desktop) version 59
 
For Tooling issues:
- Node version: 8.1.2
- Platform:  Mac

Here is the related stackoverflow post I made: https://stackoverflow.com/questions/46880756/angular2-routes-does-not-allow-param-in-route-param

**Comment by erbsenkoenig** [comment]
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[angular/angular] Route param does not allow '@' before it, for example
'@:param' will not work (#19868)" gesendet am 23.10.2017 13:17:12.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by mlc-mlapis** [comment]
@lansana ... where did you find that there is a general pattern like `path: '@:anykey'`.

The only pattern is just `:anykey, usually in the concrete form as `:id` or `route/:id`.

**Comment by lansana** [comment]
@mlc-mlapis I figured the router was smart enough to notice the `:param` from anywhere in the path, sort of like if you do something like `/foo/:id`. 

I don't see why it can't match against `/@:id` if it can do something like `/foo/:id`.

**Comment by lansana** [comment]
@mlc-mlapis Good point, I guess. I changed it from bug to feature request. May just make a pull request... I would really like this.

**Comment by jasonaden** [comment]
Thanks for the request @lansana. I think the use case makes sense, though you could also create a custom `UrlSerializer`. Currently we're using [this one](https://github.com/angular/angular/blob/master/packages/router/src/url_tree.ts#L272).
