### ISSUE TITLE
ngFor updates html comments when there are no changes

### ISSUE THREAD

**Issue by cronon** [angular/angular#19871]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

1. I set up `MutationObserver`
2. I use `ngFor` directive inside my components 
3. When new instance of array is passed into `ngFor`, then `ngFor` updates html comment, regardless whether new instance of array is different from previous one
4. This triggers mutation observer
5. Angular sees asynchronous operation and triggers `doCheck`
6. New instance of array is passed into `ngFor` again, and again `ngFor` updates html comment
This turns into eternal cycle and browser hangs.

## Expected behavior

1. `ngFor` doesn't change html comment, when there are no actual changes
2. `ngFor` changes html comment when old instance of array has been mutated -- it is not crucial for me, just noticed this.

## Minimal reproduction of the problem with instructions

For instance, look here
http://plnkr.co/edit/Lm4c6Jsei0FaO8GyxtRf
uncomment `mo.observe` in `app.component.ts`, run application and see browser hangs

## What is the motivation / use case for changing the behavior?

Allow MutationObserver to be set up on element which uses `ngFor`
In my case, I found this bug when tried to use ResizeObserver in angular application

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) version 62
- [x] Firefox version 56
</code></pre>

I would appreciate at least to see workaround for the issue

**Comment by ricardocasares** [comment]
+1

**Comment by Toxicable** [comment]
Those comments are only there in dev mode
They are removed when you enable prod mode

**Comment by cronon** [comment]
Thanks for answering. Indeed, everything is fine in prod mode :+1: 
However I still want to see the application running in dev mode as well

**Comment by jasonaden** [comment]
I think the only way you could get this to work in dev mode would be to run your MutationObserver outside of the Angular zone. That way it won't trigger change detection. You would then have to determine if the change was meaningful or not yourself, and manually markForCheck to get changes propagated.
