### ISSUE TITLE
HttpClient throws if contentType='json' and response json encoded string

### ISSUE THREAD

**Issue by sod** [angular/angular#19873]
## I'm submitting a...
[x] Bug report

## Current behavior
Our API talks JSON. Everything is json encoded. And sometimes we return json encoded strings. JSON is fine with encoding/decoding strings:

![image](https://user-images.githubusercontent.com/905328/31898670-ea16ddf2-b819-11e7-8e1d-92f748b7b3e3.png)

But [HttpClient blindly does JSON.parse](https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts#L183-L202), even if the browser already decoded it as [mentioned directly above that codeblock](https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts#L181-L182). So the JSON.parse fails just like:

![image](https://user-images.githubusercontent.com/905328/31898712-fa6453ec-b819-11e7-9aa1-7682387f095b.png)

Here is the `HttpClient` code in the debugger:
![image](https://user-images.githubusercontent.com/905328/31899120-1bcca75e-b81b-11e7-9467-4e5ff3c990a7.png)

responseType is json. The response was already decoded. But HttpClient does JSON.parse anyway. 

Here is the same code in the debugger, if the browser returns an json encoded object:

![image](https://user-images.githubusercontent.com/905328/31899394-bab4c680-b81b-11e7-9894-834b5c01ae8c.png)

You see the object `{foo:"bar"}` is already a javascript object, and the only thing preventing `HttpClient` from throwing an JSON.parse error is the condition `typeof body === 'string'`

## Expected behavior
Don't ever JSON.parse, if the browser already parsed it. HttpClient shouldn't throw if accepting json encoded strings.

## Environment

<pre><code>Angular version: 4.3.1
</code></pre>

**Comment by trotyl** [comment]
Could you provide a online reproduction? The description here is duplicate of #18396 and has been fixed by https://github.com/angular/angular/commit/8821723 already.

<sub>The http client codes looks fine in your screenshot since the response should now always be type of string for json responses. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response</sub>

**Comment by trotyl** [comment]
In your screenshot, I can see the `xhr.responseType` is `json`, which should be impossible due to https://github.com/angular/angular/blob/4.4.x/packages/common/http/src/xhr.ts#L117.

**Comment by sod** [comment]
Thx for the fast feedback. We are on `4.3.1`, will try to update to `4.4.6` and try again.

**Comment by sod** [comment]
Searched for http and HttpClient in the changelog but found nothing.

Your commit is indeed listed here
![image](https://user-images.githubusercontent.com/905328/31901688-7468812e-b822-11e7-887e-3645ae247d8e.png)
under `common`.

Well. I updated to 4.4.6 and it works. Thx for the help :)
