### ISSUE TITLE
@ViewChild results are inconsistant during the OnInit lifecycle

### ISSUE THREAD

**Issue by wizarrc** [angular/angular#19872]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`OnInit` lifecycle provides result for `@ViewChild` when not inside template

## Expected behavior

`OnInit` lifecycle not provide result for `@ViewChild` when not inside template

**Updated** Due to feedback, I feel the expected behavior should be a more simplified behavior such as split up `@ViewChild` with `@StaticViewChild` for static queries or better tooling to error when trying to access query properties at inappropriate times such as dynamic queries during the `ngOnInit` lifecycle.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/KxGysUMkHTdO3C09F7Zs?p=preview

Notice how during `OnInit` the values are different depending on where the reference is.

## What is the motivation / use case for changing the behavior?

This adds to inconsistent behavior and leads to hard to find bugs. It's better to fail fast.

Actual issue where this could have been found more easily if it failed fast.
https://github.com/swimlane/ngx-datatable/issues/1066

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version EdgeHTML 16.16299
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alexzuza** [comment]
For me it is expected behavior because static queries [are filled](https://github.com/angular/angular/blob/master/packages/core/src/view/view.ts#L332-L336) during view creation before `ngOnInit` hook is called.

In your case `#template2` is a static query because it is not inside embedded view while  `#template1` is dynamic query since it is located inside structural directive `*ngif`

Staic query can be only ViewChild and ContentChild. VIewChildren/ContentChildren are always dynamic queries

**Comment by wizarrc** [comment]
@alexzuza I was unaware of the difference, good point! It still doesn't solve the usability issue. Maybe some tooling that would provide an error for accessing a dynamic query before the correct lifecycle hook.

**Comment by wizarrc** [comment]
@alexzuza Another thought would be for a future version of Angular, provide `StaticViewChild`, etc for static query optimizations. I guess I was a little too harsh on the expected behavior. I really would prefer a simpler behavior or better tooling that prevents the non-experts to fall into the pit of success.

**Comment by trotyl** [comment]
Since the [API](https://angular.io/api/core/ViewChild) is clear:

> View queries are set before the `ngAfterViewInit` callback is called.

And in [guide](https://angular.io/guide/component-interaction#parent-calls-an-viewchild):

> First, you have to import references to the `ViewChild` decorator and the `AfterViewInit` lifecycle hook.

It's only guaranteed `ngAfterViewInit` hook are safe enough to use. The status in `ngOnInit` is an undefined behavior may change w/o further notice.

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

**Comment by himanshu-singh1995** [comment]
> For me it is expected behavior because static queries are filled during view creation before ngOnInit hook is called.

@alexzuza As this information doesn't seem to be documented anywhere in the  docs, can we rely on this information and use result of static queries in ngOnInIt?

**Comment by dummdidumm** [comment]
[In this part of the official docs](https://angular.io/guide/dynamic-component-loader), they use a `@ViewChild`-variable inside `ngOnInit`, which makes me tend more towards "you can rely on this information".

**Comment by wizarrc** [comment]
Angular 8 Beta 5 will allow the user to specify the timing of when this query is satisified.
#28810
