### ISSUE TITLE
Using 2 Angular app in one project while avoiding conflicts

### ISSUE THREAD

**Issue by GreatHawkeye** [angular/angular#19896]
Hey guys,

I'm using the latest version of angular and for my project's needs, I need to have 2 app living on the same project like so : 

`
    <body>
        <app-header></app-header>
        <app-root></app-root>
    </body>
`

And I include every header.js files and root.js files (these are the projects compiles files)
The issue is there are obviously conflicts between those two files, I'm currently having one about zone.js : `Uncaught Error: Zone already loaded.`

What are the best practices when I want to use 2 app in the same projects while avoiding conflicts?

Thanks!

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
