### ISSUE TITLE
aio linter should ignore .1.* files

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#19893]
Some examples contains extra helper files like:

src/app/heroes/heroes.component.1.ts
src/app/heroes/heroes.component.1.html

etc.

There are some instances where there are .2.xxx and .3.xxx

In any case, at leas the .1.* files needs to be ignored by the linter. There are some of those files that cannot be fixed at all and well, they are helper files, not meant to be run at all.

**Comment by petebacondarwin** [comment]
Linting is still important in all example files, no?
If there are specific instances where the file must break linting rules then those rules can be turned off via inline comments.
