### ISSUE TITLE
@angular/compiler-cli 5.0.0-rc.4/5 outputs to wrong folders => AOT build fails

### ISSUE THREAD

**Issue by actra-gschuster** [angular/angular#19897]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior
Since 5.0.0-rc.4 with the immense changes to compiler-cli an AOT build fails due to generated files (ngsummary etc.) being put to wrong folders.
![wrong-5 0 0-rc 4](https://user-images.githubusercontent.com/23024678/31938472-eb524c30-b8b7-11e7-84c0-b2128f8082b4.png)

## Expected behavior
AOT compilation should output to correct folders so the build works at all.
![correct-5 0 0-rc 3](https://user-images.githubusercontent.com/23024678/31938464-e372db56-b8b7-11e7-99fd-c77ffd6eb8f4.png)

## Other details
Command used for both outputs as seen in the images: `.\node_modules\.bin\ngc -p src\tsconfig.app.json`

./src/tsconfig.app.json:
```
{
    "extends":         "../tsconfig.json",
    "compilerOptions": {
        "baseUrl": "./",
        "module":  "es2015",
        "outDir":  "../dist/out-tsc/app",
        "types":   [
            "angular",
            "core-js",
            "hammerjs",
            "lodash-es",
            "node",
            "redux",
            "redux-immutable",
            "redux-logger",
            "redux-persist-transform-filter",
            "rx",
            "rx-angular",
            "uuid",
            "web-animations-js"
        ]
    },
    "exclude":         [
        "test.ts",
        "**/*.spec.ts"
    ]
}
```

./tsconfig.json
```
{
    "compileOnSave":   false,
    "compilerOptions": {
        "baseUrl":                "src",
        "declaration":            false,
        "emitDecoratorMetadata":  true,
        "experimentalDecorators": true,
        "lib":                    [
            "es2017",
            "dom"
        ],
        "moduleResolution":       "node",
        "outDir":                 "./dist/out-tsc",
        "sourceMap":              true,
        "target":                 "es5",
        "typeRoots":              [
            "node_modules/@types"
        ],
        "types":                  [
            "angular",
            "core-js",
            "hammerjs",
            "jasmine",
            "lodash-es",
            "node",
            "redux",
            "redux-immutable",
            "redux-logger",
            "redux-persist-transform-filter",
            "rx",
            "rx-angular",
            "source-map",
            "uglify-js",
            "uuid",
            "webpack",
            "web-animations-js"
        ]
    }
}
```

## Environment

<pre><code>
Angular: all modules at 5.0.0-rc.5, except for @angular/compiler-cli, which is at 5.0.0-rc.3 for the AOT build to work
angular/cli is at 1.5.0-rc.3
ngtools/webpack is at 1.8.0-rc.3

**Comment by kemsky** [comment]
Yep, the same problem as in #19543

**Comment by tbosch** [comment]
Closing as duplicate.
