### ISSUE TITLE
ATScript over Macros and Traceur

### ISSUE THREAD

**Issue by breandr** [angular/angular#199]
In #133 @kristianmandrup raised using Macros instead of ATScript. From what I've seen, the second biggest issue devs have with 2.0 (after syntax) is ATScript. If we can use Macros to bring in the functionality that would be provided by ATScript (Types, Annotations), surely that would be for the best. Are there limitations to Macros that ATScript overcomes?

Alternatiely, Traceur already has Types and Annotations both as experimental features. Are they something we could leverage?

**Comment by mhevery** [comment]
Valid approach, it is just not what we have chosen. Closing as it is not relevant.
