### ISSUE TITLE
JiT compiler does not use already precompiled by AoT components factories

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#19901]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Runtime compilation dynamic component with template received from backend ignores already existing components factories and JiT recompile every component that provided in imported modules.

## Expected behavior
JiT uses existing factories and compile only new dynamic component.

## What is the motivation / use case for changing the behavior?
I'm forced to use JiT in runtime to compile random markup received from backend. All markup's components are known and already precompiled with AoT in current app (they are added to `entryComponents` list and imported by main module). When JiT starts to compile this markup i'm expecting to see only this particular dynamically created component compilation, but JiT ignores everything and compiles every component that can be used in such templates (anything from modules that are imported in dynamically created one). This takes about 5s on my pc and much more on our customers computes (~100+ components).
Also i cant see any way to not to use JiT for such case cause this markups are unkown, frequently change and there are a thousands of them. And i cant use `angular.io` approach with `factory.create` calls on DOM nodes due to a lot of content projection that is not supported via this method.

## Environment

<pre><code>
Angular version: 4.3.6
</code></pre>

**Comment by chuckjaz** [comment]
The generated component factories are not used automatically by tests. To use them you need to,

1) Turn on `"enableSummariesForJit": true` in `angularCompilerOptions`
2) Import the generated summary module.
3) Register the summary module with the test bed using `TestBed.initTestEnvironment()` passing it as the last parameter.

An, admittedly convoluted, example can be found [here](https://github.com/angular/angular/blob/master/packages/compiler-cli/integrationtest/test/jit_summaries_spec.ts).

This should be documented more clearly and I have created a tracking bug for that (#20223).

The reason the compiler cannot automatically use the generated factories is that the factories do not retain enough information to enable the compiler to use them. They only contain the result of compilation and do not contain the metadata needed by the compiler. This is where summaries come in. The summaries record the information elided from the factory allowing the JIT compiler to generate code using the AOT factory. The JIT compiler also needs to be able to find the summary which is what the call to `TestBed.initTestEnvironment()` does. You need the combination of telling the AOT compiler to generate the summaries and telling the JIT compiler to use the summaries.

**Comment by GianlucaMaggio** [comment]
Hi @chuckjaz,
how can I import the generated summary module? Where can I found it?
