### ISSUE TITLE
[compiler] fullTemplateTypeCheck raises errors in router, forms

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#19905]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Follows #19485 

I'm still having issues when beta testing `fullTemplateTypeCheck` (even if it's better than when I opened #19485 ), here are my findings.

A simple template with a `routerLink`:
```
<a class="nav-item nav-link" routerLink="/races">Races</a>
```
 throws:
```
Directive RouterLinkWithHref, Cannot find name '$event'. Did you mean 'Event'?
```

With forms, too:

```
<div class="row">
  <div class="col-md-4 offset-md-4">
    <h1>Sign up</h1>

    <form (ngSubmit)="register()" [formGroup]="userForm">

      <div class="form-group">
        <label for="login" id="login-label">Login</label>
        <input id="login" class="form-control" formControlName="login">
        <div *ngIf="loginCtrl.dirty && loginCtrl.hasError('required')" id="login-warning">Login is required</div>
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input id="password" class="form-control" type="password" formControlName="password">
        <div *ngIf="passwordCtrl.dirty && passwordCtrl.hasError('required')">Password is required</div>
      </div>

      <div class="form-group">
        <label for="birthYear">Birth year</label>
        <input id="birthYear" class="form-control" type="number" formControlName="birthYear">
        <div *ngIf="birthYearCtrl.dirty && birthYearCtrl.hasError('required')">Birth year is required</div>
      </div>

      <button class="btn btn-primary" type="submit" [disabled]="userForm.invalid">Let's Go!</button>
    </form>
  </div>
</div>
```

raises:

```
register.component.html(5,5): Directive FormGroupDirective, Cannot find name '$event'
register.component.html(9,9): Directive DefaultValueAccessor, Property '_handleInput' does not exist on type 'DefaultValueAccessor'.
register.component.html(9,9): Directive DefaultValueAccessor, Cannot find name '$event'.
register.component.html(9,9): Directive DefaultValueAccessor, Property '_compositionStart' does not exist on type 'DefaultValueAccessor'.
register.component.html(9,9): Directive DefaultValueAccessor, Property '_compositionEnd' does not exist on type 'DefaultValueAccessor'. Did you mean '_compositionMode'?
register.component.html(21,9): Directive ɵbc, Cannot find name '$event'
```

## Environment

<pre><code>
Angular version: 5.0.0-rc.5
 
For Tooling issues:
- Node version: v8.7
- Platform:  Mac
</pre></code>

cc @chuckjaz

**Comment by kemsky** [comment]
It does not support `@HostListener('click', ['$event'])`:

> Directive Button, Cannot find name '$event'. Did you mean 'Event'?

**Comment by tbosch** [comment]
Here is a reproduction: https://github.com/tbosch/ng-repro/tree/issue-19905

**Comment by tbosch** [comment]
Proposed solution:

* Never pass in `null` to the calls of `convertActionBinding` / `convertPropertyBinding` in [type_check_compiler.ts](https://github.com/angular/angular/blob/master/packages/compiler/src/view_compiler/type_check_compiler.ts). Instead, pass in a simple implementation of a `LocalResolver` that returns `o.variable(DYNAMIC_VAR_NAME)` if asked for a local called `EventHandlerVars.event.name`.

**Comment by janerikmai** [comment]
I still get this kind of error in 5.1 with 
```bash
Property '_handleInput' does not exist on type 'DefaultValueAccessor'.
Property '_compositionStart' does not exist on type 'DefaultValueAccessor'.
Property '_compositionEnd' does not exist on type 'DefaultValueAccessor'. Did you mean '_compositionMode'?
```
when doin an AOT build on a simple 
```html
<input [(ngModel)]="value" />
```

where value has Getter and Setter in component, included FormsModule in Module...

any ideas or suggestions?

**Comment by cexbrayat** [comment]
@janerikmai As you can see, the issue is still opened so it's normal that you are still running into it with 5.1. One part of the issue has been resolved (event binding) but some work is left to fix it completely.

**Comment by janerikmai** [comment]
@cexbrayat oh ty, tought the event binding related to banana in a box problem :)

**Comment by josephliccini** [comment]
Tried this in `5.2.0-rc.0` and it is resolved! really enjoying the `fullTemplateTypeCheck` feature now that it is working a lot better 👍
