### ISSUE TITLE
Big idle gaps in JiT compilation

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#19902]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
There is a lot of idle gaps when dynamic component is compilating by JiT.
![image](https://user-images.githubusercontent.com/1944061/31945442-da102a9e-b8d7-11e7-902a-8c2caf0775f8.png)

Performance profile: https://drive.google.com/file/d/0B01Ag1EGUrYpc1ItbHQwb1Z6bDA/view?usp=sharing

## Expected behavior
No gaps, faster compilation

## What is the motivation / use case for changing the behavior?
I'm compiling in runtime markup with a lot of components (~1700 DOM nodes if instert directly in html) and template parsing takes a lot of time.
Also same template dynamically added by angularjs (i'm upgrading ng1 app to ng2+) takes about 3-3.5s instead of 9-10s for ng4

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [ ] Chrome (desktop) version 62.0.3202.62

</code></pre>

**Comment by alexzuza** [comment]
Angular version: 3.4.6?

**Comment by artaommahe** [comment]
fixed

**Comment by artaommahe** [comment]
Currently i'm forced to use angularjs `$compile` service to insert such markups (it's hybrid app) with all markup's components downgraded from angular. And it takes same 3-3.5s to insert and compile as with all-from-angularjs case.

**Comment by mhevery** [comment]
The gaps is waiting on I/O, not actionable.
