### ISSUE TITLE
AOT build hang lazy route loading using new compiler-cli 5.0

### ISSUE THREAD

**Issue by Delagen** [angular/angular#19900]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
On start it hang on initial navigation with url /#/
Without AOT with compiler it works OK

## Expected behavior
Should work as it was in 4.x

## Minimal reproduction of the problem with instructions
Cannot get minimal reproduction due private project, may be it related to rxjs 5.5.0 i am using

## Environment

<pre><code>
Angular version: 5.0.0-rc.5

For Tooling issues:
- Node version: 8.7.0
- Platform:  Windows 10 x64

</code></pre>

**Comment by matsko** [comment]
Hey @Delagen any chance you provide more info so that we can get a reproduction going?

**Comment by Delagen** [comment]
@matsko Bug occurs only in AOT mode.

Tried to demonstrate issue here https://github.com/Delagen/angular-issue19900
`ng build --prod --aot`

**Comment by Delagen** [comment]
Upgraded to rc.6. Seems it only hangs with ServiceWorkerModule. Turned off it. All works fine now )

**Comment by Delagen** [comment]
rc.7 fix ServiceWorker issue, but still hang on lazy route loading

**Comment by matsko** [comment]
@tbosch any idea if this is relative to https://github.com/angular/angular/commit/a869aeecd21c0e9de3595a4da3f6425f5b00e008 ?

**Comment by tbosch** [comment]
@Delagen I just tried with`@angular/*@rc.7` and `@angular/cli@1.5.0-rc.5`.

`ng build --prod --aot` works fine.

`ng serve --aot` logs an error in the console saying that `BrowserModule` cannot be lazy loaded. Looking at your `app2.module.ts` I see that you are importing `BrowserModule` there. You should change it to `CommonModule`, as indicated by the error message. After doing this, the app loads fine.

Are there other errors that you are seeing? If so, please add reproduction steps for them too.

**Comment by tbosch** [comment]
Otherwise this can be closed.

**Comment by Delagen** [comment]
Seems I found the issue in my project. Thanks for assist. Webpack config issue, related that generated code not now typescript source.

**Comment by MashB** [comment]
@Delagen  can you post your solution to resolve this issue ? what exact config changes you did in webpack config ?

**Comment by Delagen** [comment]
@MashB if you are using `angular-cli` I cannot help you.
I use own build pipeline.
