### ISSUE TITLE
HttpTestingController different behavior of the test based on place where verify() was put.

### ISSUE THREAD

**Issue by Philips7** [angular/angular#19903]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Test behaves differently based on place where verify() was put. Not always full path and unexpected requests are shown as well. 

When it is put in afterEach(), sends two errors:
1. First error for expected request with full path. 
2. Second Error for unexpected request without params.

Screen for verify() placed in afterEach(): 
![image](https://user-images.githubusercontent.com/19551727/31948634-b46ed920-b8d7-11e7-9fb2-9b6fdfb49b48.png)

When it it put in the end of test, sends one error:
1. Error for expected request with full path, and none unexpected requests.

Screen for verify() in the end of the test:
![image](https://user-images.githubusercontent.com/19551727/31949121-cf954c7e-b8d8-11e7-9706-aa6077e179a5.png)

## Expected behavior

Test should show expected and unexpected requests with full path regardless of place where verify() was put.

## Minimal reproduction of the problem with instructions

Code for bug reproduction in available on github:
https://github.com/Philips7/HttpTestingController

<pre><code>
import {TestBed, async, inject} from '@angular/core/testing';
import {AppComponent} from './app.component';
import {HttpClientTestingModule, HttpTestingController} from '@angular/common/http/testing';
import {HttpClient, HttpParams} from '@angular/common/http';

describe('AppComponent', () => {
  let httpMock: HttpTestingController;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      declarations: [
        AppComponent
      ],
    });
    httpMock = TestBed.get(HttpTestingController);
  }));

  it('should work fine', inject([HttpClient], (http: HttpClient) => {
    const geocodeResponse = {
      'location': {
        'entity_type': 'subzone',
        'entity_id': 97456,
        'title': 'Rzeszów',
        'latitude': '50.0499990000',
        'longitude': '22.0000000000',
        'city_id': 267,
        'city_name': 'Rzeszów',
        'country_id': 163,
        'country_name': 'Poland'
      }
    };

    const params = new HttpParams()
      .append('lat', '50.04132')
      .append('lon', '21.99901');

    http
      .get('https://developers', {params}).subscribe();

    const req = httpMock
      .expectOne(`https://developers?lat=50.04132&lng=21.99901`);
    expect(req.request.method).toEqual('GET');

    req.flush(geocodeResponse);
    
    // httpMock.verify(); Behaves differently based on place where is placed
  }));

  afterEach( () => {
    httpMock.verify();
  });
});

</code></pre>

## What is the motivation / use case for changing the behavior?

To make tests reliable.

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.6.0  
- Platform: Windows 

Others:

</code></pre>

**Comment by alxhub** [comment]
Hello @Philips7, thank you for the well-documented bug report and reproduction. The behavior in both cases is correct.

This happens because errors from `HttpTestingController` (and most "expectation" frameworks like Jasmine Matchers) are actual `Error`s that get thrown. The rest of the test body isn't executed when this happens.

So if `verify()` is called at the end of the test, the `httpMock.expectOne()` call throws before it has a chance to execute, and only one error is returned.

If `verify()` is called in the `afterEach()` block, however, it _does_ run after the `httpMock.expectOne()` causes the test to fail, and then it notices that the `http.get('https://developers')` has not yet been matched, and throws that error.

Does that make sense?

**Comment by Philips7** [comment]
Yes @alxhub now it makes sense, thanks for response. But another thing that concerns me is removing params from url, when they don't match. In this case: ` lat=50.04132&lng=21.99901` didn't match with `lat=50.04132&lon=21.99901` and they were removed from url. Is this also expected behaviour?

**Comment by desfero** [comment]
@alxhub i'm agree with @Philips7. Such behavior is not what user expect, a simple mistake in naming can cause a huge pain...

**Comment by msegers** [comment]
I'm currently seeing this issue:

https://stackoverflow.com/questions/47517629/angular-testing-a-service-using-httpclient-is-not-working-for-me?noredirect=1#comment81991837_47517629

I actually have no clue what I am doing wrong and the error is not helping me.
As stated in my issue the code just works but the test does not.
