### ISSUE TITLE
Symbols referenced only as a type are not imported in JS output

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#19916]
### Steps to reproduce
* Clone https://github.com/crisbeto/material2/tree/ng-5
* Install all Angular builds at 7bfeac746e717d02e062fe4a65c008060b8b662c or later
* Run `gulp cdk:build:esm` (this is equivalent to running `ngc` on each subpackage under `src/cdk` in the correct order)
* Examine `./dist/packages/cdk/overlay/overlay.js`

You can run `./node_module/.bin/ngc -p ./src/cdk/overlay/tsconfig-build.json` to debug the issue (the gulp task is only needed to build the dependencies).

### Expected
`overlay.js` includes an import:
```ts
import { ScrollStrategyOptions } from './scroll/index';
```

### Actual
The import is missing.

### Comments
In this example, ScrollStrategyOptions is only used in the type space. `tsc` by itself will omit imports from the JS output for symbols imported only for use in types. `ngc`, however, should output JS that includes imports for these symbols, as they are used in the generated code.

cc @chuckjaz @tbosch, fyi @crisbeto

**Comment by tbosch** [comment]
The problem is that your `tsconfig.json` is missing `emitDecoratorMetadata: "true"`. We still need this although we don't let TypeScript emit the usual downleveling. See https://github.com/Microsoft/TypeScript/issues/17516 for more details.

I added `emitDecoratorMetadata: "true"` to `./src/cdk/tsconfig-build.json` and everything is fine.

**Comment by tbosch** [comment]
I also filed an issue against Tsickle to track this: https://github.com/angular/tsickle/issues/635

**Comment by tbosch** [comment]
Reopening as the user should not need to care, i.e. `ngc` should set `emitDecoratorMetadata` in this case automatically, as he didn't had to in Angular 4. https://github.com/angular/angular/pull/19927 will do this.
