### ISSUE TITLE
Compiler CLI requests Angular CLI 1.5+ for builds done via webpack

### ISSUE THREAD

**Issue by FrozenPandaz** [angular/angular#19913]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Compiler-cli throws the following error if Angular CLI 1.5+ is not installed even if build was not done with Angular CLI (.ie via webpack)

Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+

## Expected behavior

Compiler-cli should not throw an error when it is used as a CLI tool or through webpack.

If there is still an issue with using it through @ngtools/webpack, that error should be thrown.

## What is the motivation / use case for changing the behavior?

We only use Angular CLI for unit testing and not building. It should have better error reporting for when it is not used via CLI.

## Environment

<pre><code>
Angular version: 5.0.0-rc.4 and rc.5

@ngtools/webpack: 1.5.5
angular-cli 1.0.0-beta.28.3
(I know this is super old)

Browser:
N/a its build time
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  Mac, Linux

Others:

</code></pre>
I know this is using some really old versions of @ngtools/webpack and angular-cli but it shouldnt throw an error if the build isnt done by angular-cli. I've tested @ngtools/webpack 1.5.5 with rc.3 and it works fine.

**Comment by vapits** [comment]
CLI added support for Angular 4+ after some later versions of yours. I don't think it's an issue, just upgrade your cli, you'll have no breaking changes.

**Comment by gkalpak** [comment]
As far as I understand, this is not about using the CLI, but using some (probably deprecated) APIs without the CLI. So, I agree the message should be more generic and actionable even for people not using the CLI.

**Comment by sarunint** [comment]
#19836 deprecated `ngtools_api`. I believe that `ngtools_api2` is a replacement for it.

**Comment by spock123** [comment]
Have the same issue - not using angular/cli, but using my own webpack build.

Angular RC4 and RC5 aot build is broken - error message:

`ERROR in Error: Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+
`
But I'm, not using the CLI... so what gives?

Using latest @ngtools/webpack 1.7.4, Angular 5 RC4, RC5

**Comment by gkalpak** [comment]
True, but still the error message should be more generic and actionable :grin:

**Comment by hansl** [comment]
The error message is incorrect; you need the new `AngularCompilerPlugin` instead of the `AotPlugin`. Will fix the error message.

**Comment by spock123** [comment]
@hansl  Thank you Hans - that's it!!! cheers

**Comment by epieddy** [comment]
@hansl Where can I find the new AngularCompilerPlugin ? @ngtools/webpack v1.7.4 only has the AotPlugin

**Comment by trotyl** [comment]
@epieddy https://unpkg.com/@ngtools/webpack@1.8.0-rc.8/src/angular_compiler_plugin.js

**Comment by epieddy** [comment]
My bad, npm latest != npm next.  For everyone finding this on Google : npm install --save-dev @ngtools/webpack@next

**Comment by hansl** [comment]
Closing this as fixed.
