### ISSUE TITLE
KeyBoard event is not fired up on ` character

### ISSUE THREAD

**Issue by helgus** [angular/angular#19919]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have such code
 ```
---html---
<input (keypress)="handleTyping($event)">

--- ts   ---
handleTyping(event: KeyboardEvent) {
    const pattern = /[\0-9\]/;
    if (!(pattern.test(event.key) || event.keyCode === 8) ) {
      // invalid character, prevent input
      event.preventDefault();
    }
  }
```
When I type `` symbol - this keyBoardEvent is not even called. Moreover I can type `1 or `s - keyBoardEvent event is not fired and invalid symbols are not prevented

## Expected behavior
It should fire an event when I  press any keyboard button and prevent symbols or buttons that are not allowed.

## Minimal reproduction of the problem with instructions
Steps to reproduce:
1. Implement such method
2. Input to the field any amount of `` and/or any symbols after each `
## What is the motivation / use case for changing the behavior?

Such error allows to input any symbol to strictly-ruled inputs.

<pre><code>
Angular version: 4.3.1

Browser:
- [ x ] Chrome (desktop) version latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x ] Firefox version latest
- [ x ] Safari (desktop) version XX
- [ ] Safari (iOS) version latest
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.2.1
- Platform:  Mac

</code></pre>

**Comment by PaluMacil** [comment]
I've had to work around this with that specific key (hint: just use keydown), but it isn't going to be an Angular issue. It's just how browsers work--sure, it works in Firefox and IE, but Angular can't see something Chrome isn't sending. If you want to file a report, I recommend filing against Chrome. _**However**_, the spec indicates that an event should only be produced by keys that produce a character, so Google has said [they will not fix this](https://bugs.chromium.org/p/chromium/issues/detail?id=9061#c15).

**Comment by PaluMacil** [comment]
It could be that other browsers have dropped support to match Chrome or I could recall wrong that IE and Firefox used to work differently. Regardless, keydown works, and if it doesn't, make sure you're listening at a level that the event will bubble up to. The following is an example that I use in a lot of my early dev to provide a shortcut to a dev page. I set the event to fire on the document level.

```
  @HostListener('document:keydown', ['$event'])
  handleKeyDown(event: KeyboardEvent) {
    if (event.ctrlKey && event.key === '`') {
      if (this.router.isActive('/page/dev', false)) {
        this.router.navigate(['/']);
      } else {
        this.router.navigate(['/page', 'dev']);
      } 
    }
  }
```

**Comment by chuckjaz** [comment]
I'm sorry but this issue is not caused by Angular. See discussion above.
