### ISSUE TITLE
ElementProbe API

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1992]
# GOAL

- simplify debugging in the browser, by allowing adhoc access to the content of the `ElementInjector` in the dev mode

## API

```javascript
window.ngProbe(element:Element) => Probe.fromElement(element);

class Probe {
  static fromElement(element: Element): Probe;

  get element():Element;
  get component():any;
  get context():any;
  get directives():List<any>;
  get(type:Type, visibility?): any;
}
```

## Implementation

In the debug mode only (perf reasons) Angular should use expandos to attach the `ElementInjector` to the DOM Element. The developer can than use the API to get a `Probe` which wraps the `ElementInjector` and allows the user to retrieve the components at that location.

## Tests

This should be enabled by default in tests.

**Comment by juliemr** [comment]
How will this relate to #1812, and the `TestElement` used there?

**Comment by mhevery** [comment]
@juliemr #1812 is about making tests, #1992 is about allowing one to get a hold of the directives, when all you have is an ElementRef. This is useful for pocking around in dev console as well as for Protractor.

**Comment by juliemr** [comment]
As discussed offline, we should eventually use the ngProbe for tests as well when applicable, so we don't have two systems for doing similar things.
