### ISSUE TITLE
Angular 4 - Import BrowserAnimationsModule or NoopAnimationsModule in production mode

### ISSUE THREAD

**Issue by zkewal** [angular/angular#19921]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Getting following error in browser's console while running with --prod flag

> Found the synthetic property @carXposState. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

I have imported BrowserAnimationsModule in app.module.ts and also imported as a part of imports in AppModule
```
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
@NgModule({
  imports: [
    ...
    BrowserAnimationsModule,
    ...
  ],
  declarations: [AppComponent],
  providers: [
    ...
  ],
  bootstrap: [AppComponent]

})

export class AppModule {
...
}
```
I also have included "@angular/animations": "^4.3.2" in my package.json and I am using angular-cli in my application

It works as per expected behavior when running in development mode but when I create a build using ng build --prod and then open in browser the error occurs and the animation also does not happen

## Expected behavior

It should not show that error while running in --prod mode and the animation should work

## What is the motivation / use case for changing the behavior?

I am unable to use animation module in production

## Environment

<pre><code>
Angular version: 4.3.2

Browser:
- [ x ] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.5.0  
- Platform:  Windows 10

Others:

</code></pre>
![animation issue](https://user-images.githubusercontent.com/1589502/31996166-07eb5a56-b9a5-11e7-886d-e7721e60a977.png)

**Comment by zkewal** [comment]
I did further into the issue and created a sample application where it is being replicated.

https://github.com/zkewal/ng-animation

This application is created using angular cli. If we run in development mode then animation works, if we create using production mode then it does not work and gives above mentioned message in browser console.

**Comment by zkewal** [comment]
Here is the url where it is replicated.
https://stackblitz.com/edit/angular-jiwhqx

**Comment by gatimus** [comment]
I am also experiencing this.
Could be related to https://github.com/angular/angular/issues/18751

**Comment by gatimus** [comment]
Never mind, I had a directive with a HostListener for '@myAnimation.done' inside a component with out animations metadata for 'myAnimation' trigger. The error message could be better though.

**Comment by RockGuitarist1** [comment]
Yep still broken. Having the same issue.

**Comment by leolanese** [comment]
I have the same issue, any news?

**Comment by CNaiko** [comment]
I am also experiencing this, any progress?

**Comment by IagoBarboza** [comment]
Also here!

**Comment by chief10** [comment]
Same here

**Comment by matchupinfo** [comment]
same here

**Comment by olivermuc** [comment]
Same here, but with a slightly different setup with <parent> being a custom component and driving the child's ***ngIf**.

Also, the error occurs in non-prod code, too.

```
<parent (swipe)="swipeHandler()">
   <div *ngIf="isActive === child1" [@animSlide]="animationDirection">1</div>
   <div *ngIf="isActive === child2" [@animSlide]="animationDirection">2</div>
   <div *ngIf="isActive === child3" [@animSlide]="animationDirection">3</div>
</parent>
```

The above throws the dreaded 
`Please include either "BrowserAnimationsModule" or "NoopAnimationsModule...`
Error.

However if I replace the child divs with custom child components and use `@HostBinding('@animSlide') public animSlide = 'toLeft';` there is no error. 
But this creates another issue: **I can't dynamically assign an animation direction.**

Any thoughts?

**Comment by zkewal** [comment]
I was able to resolve this issue by statically providing animation states. Previously I had a function which was dynamically generating animation states at the run time, as referenced here:
https://github.com/zkewal/ng-animation/blob/6c19ac90764016cec359b2ef7b3585ce81daaa14/src/app/app.component.ts#L21

Now I store the array of states statically and provide it to decorator @Component/animations.

I am not sure why is this the case. And the error message is definitely not correct because the import of BrowserAnimationsModule is properly done.

**Comment by olivermuc** [comment]
Here is the solution:

```
<parent (swipe)="swipeHandler()" #parent>
	<child *ngIf="isActive === child1" [animDirection]="parent._animateDir">
			Some content.
	</child>
```

**#parent** needed to be set and referenced in its own child comp reference.
Make sure to use setTimeout on changing the `*ngIf="isActive` variable to allow for the child comp to update the input val.

**Comment by earthican** [comment]
I'm getting this same error, even in development mode.
I've included `BrowserAnimationsModule` in my app module and even have `"@angular/animations": "^5.2.7"` in my `package.json`

**Comment by silentsnooc** [comment]
Got the same issue.

**Comment by wilker7ribeiro** [comment]
Here is what I experienced
After upgraded from 5.2.x to 6.x.x
Stopped working:
```
import { fadeInOutAnimation } from '../../shared/animations/fadeInOutAnimation';
import { sidenavAnimations } from './sidenav.animations';

//this line throws "Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application"
const animations = sidenavAnimations.concat(fadeInOutAnimation);

@Component({
  selector: 'app-sidenav',
  templateUrl: './sidenav.component.html',
  styleUrls: ['./sidenav.component.scss'],
  providers: [SidenavService],
  animations: animations
})
```

Fixed with 
`const animations = [...sidenavAnimations, fadeInOutAnimation]`

------------

Also, calling this function stopped working, it throws at runtime:

> TypeError: Cannot read property 'type' of null at visitDslNode (browser.js:441)

```
transition('web-aberta <=> web-fechado', withAnimateChildren(animate(animationTime + ' ease-in-out')))

export function withAnimateChildren(...animations: any[]): any {
  return group([query("@*", [animateChild()], { optional: true }), ...animations]);
}
```
But the equivalent works:
```
transition('web-aberta <=> web-fechado', group([
    query("@*", [animateChild()], { optional: true }),
    animate(animationTime + ' ease-in-out')
]))
```
---
And this throws at compile time:

> Error during template compile of 'SidenavComponent'
>   Function expressions are not supported in decorators in 'sidenavAnimations'

```
const withAnimateChildren = function withAnimateChildren(...animations: AnimationMetadata[]): AnimationGroupMetadata {
  return group([query("@*", [animateChild()], { optional: true }), ...animations]);
}

```

**Comment by Tynoe** [comment]
see comments  https://github.com/angular/angular/issues/18751

**Comment by krysalead** [comment]
Hi, 

Got the same issue and solved it by importing the BrowserAnimationsModule before any module that will need it.

**Comment by BennieMeng** [comment]
same issue

**Comment by diazenal** [comment]
> Hi,
> 
> Got the same issue and solved it by importing the BrowserAnimationsModule before any module that will need it.

it's work !!  thank you @krysalead

**Comment by JoostK** [comment]
Animations had to be statically analyzible in View Engine when using AOT; this is no longer the case with Ivy.
