### ISSUE TITLE
Like a 'Folder Path' routing

### ISSUE THREAD

**Issue by ar53n** [angular/angular#19925]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[х] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>
Hello. I know that no issue, but want to know.

I have one task for create 'folder path' routing in angular. 
I want my routing to look like this:
`http://url/workspace/:workspaceId/...:folderPath/`
where `...:folderPath` infinity folder path.
Finally i want see my path `workspace/home/mydocuments/2017/Italy/../../../..`

I'm try `{path: '..', component: anyComponent}` but it's doesn't work

I found one solution with `matcher` but its `@experemental`. _Will be deprecated this feature and have any solution for this case?_

    function pathMatch(url: UrlSegment[]): UrlMatchResult {
    	if (url.length >= 2 && url[0].path === 'workspace') {
    	    return  ({consumed: url});
        } else { return null }
    }
    
    export const routes: Routes = [
    	{ path: '', component: FolderViewComponent },
    	{ path: 'new', component: FileCreateComponent },
    	{ path: 'workspace', component: WorkSpaceComponent },
    	{ path: 'workspace/:workspaceId', component: WorkSpaceComponent},
    	{ matcher: pathMatch, component: WorkSpaceComponent},
    	{ path: '**', component: FolderViewComponent }
    ];

 Maybe have any good solution for this task?

## Environment

<pre><code>
Angular version: 4.4.Z

Browser:
- [х] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:   Windows

Others:

</code></pre>

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
