### ISSUE TITLE
Feature Request: Unify the toBoolean behavior for boolean attributes

### ISSUE THREAD

**Issue by trotyl** [angular/angular#19929]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

**Warning: this issue may be pedantic.**

Different directives are using different mechanism to convert string to boolean.

In [`NgModel`](https://github.com/angular/angular/blob/master/packages/forms/src/directives/ng_model.ts#L263), the conversion is:

```typescript
const isDisabled = disabledValue === '' || (disabledValue && disabledValue !== 'false');
```

While in  [`RequiredValidator `](https://github.com/angular/angular/blob/master/packages/forms/src/directives/validators.ts#L89):

```typescript
this._required = value != null && value !== false && `${value}` !== 'false';
```

And in [`EmailValidator `](https://github.com/angular/angular/blob/master/packages/forms/src/directives/validators.ts#L158):

```typescript
this._enabled = value === '' || value === true || value === 'true';
```

So that the result is:

Pattern                                       |`[disabled]`|`[required]`|`[email]`
-------------------------------|------------|------------|---------
`<element attribute>`              |`true`          |`true`          |`true`
`<element attribute="true">`  |`true`          |`true`          |`true`
`<element attribute="false">` |`false`         |`false`        |`false`
`<element attribute="foo">`    |`true`         |`true`          |`false`
`<element [attribute]="true">`|`true`         |`true`          |`true`
`<element [attribute]="false">`|`false`         |`false`        |`false`
`<element [attribute]="null">`|`false`         |`false`        |`false`
`<element [attribute]="0">`|`false`         |`true`        |`false`
`<element [attribute]="1">`|`true`         |`true`        |`false`
`<element [attribute]="{}">`|`true`         |`true`        |`false`
`<element [attribute]="{toString:()=>'false'}">`|`true`         |`false`        |`false`

*The object definition is inlined just for demonstration.*

## Expected behavior

Angular should provide a unified mechanism for string -> boolean transformation in boolean attributes.

## Minimal reproduction of the problem with instructions

Likely not needed as a one-line code in console.

## What is the motivation / use case for changing the behavior?

Angular should provide a guideline for how to covert string to boolean in boolean attributes.

## Environment

<pre><code>
Angular version: 5.0.0-rc.5

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Another question is that `NgModel#disbaled` is declared as `boolean` while still accepts `string` value (by design for empty string), is it expected? (Consider we'll have type-checking for inputs some day)

**Comment by dawidgarus** [comment]
Built-in mechanism to sanitize inputs would be nice, something like: `@Input('required', { sanitize: 'boolean' }) private required: boolean`, so one could safely write `<element required>` and always have boolean value in property. Also setter/ngOnChange won't be called if the actual input value will change from one truthy (or falsy) value to another.

**Comment by trotyl** [comment]
Relates to #14761, but this one is not asking for syntax sugar, just the logic.

**Comment by trotyl** [comment]
@dawidgarus Your request is another form of #8968, you should follow it there.

**Comment by LinBoLen** [comment]
in my short-sighted opinions;
already have pipe. this feature looks like not standard.

`<element attribute>` `<element attribute="true">` ... is a sugar for binding string literal. convert it? why? how? only for ngmodel? none of them sounds possible.

**Comment by alan-agius4** [comment]
In think ideally something like this https://github.com/angular/material2/tree/17cc4a198f336e8ebefbb2710d8e80df2595db7e/src/cdk/coercion

**Comment by trotyl** [comment]
@alan-agius4 That's what we choose at last, but it would throwing error for `Symbol` type (an small edge case problem).
