### ISSUE TITLE
Feature request: Use forRoot on lazy-loaded modules.

### ISSUE THREAD

**Issue by hugodes** [angular/angular#19924]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Feature request

It would be great to be able to use the forRoot method on a lazy-loaded module.

## What is the motivation / use case for changing the behavior?

Just because a module is lazy-loaded doesn't mean it shouldn't be configurable, at least to some extent.

## Environment

<pre><code>
Angular version: 4.4.6

**Comment by trotyl** [comment]
There is no `forRoot` stuff in Angular, that just a convention for static methods **designed specifically** for root module. 

If some method was not designed only for root module, then don't name it `forRoot`.

**Comment by hugodes** [comment]
@trotyl Yes you're right, le me rephrase: it would be nice to be able to pass on some config options to a lazy loaded module that we could handle in a method (not necessarily a forRoot one):

```
export class LazyLoadedModule {
  
  static fooMethod(config: Config): ModuleWithProviders {
    return {
      ngModule: LazyLoadedModule,
      providers: [
        {provide: Config, useValue: config }
      ]
    };
  }
}
```

**Comment by trotyl** [comment]
What being loaded at runtime is a `NgModuleFactory`, not a `NgModule`, so it cannot be replaced with `ModuleWithProviders` since the hardness of changing the compilation process. Moreover, **how to transform a string to a method call?** (Would require a complicated DSL).

I'd suggest just using DI to transfer anything relates to the configuration.

**Comment by hugodes** [comment]
Ok clear as water, thanks a bunch !
