### ISSUE TITLE
Incorrect error logging in resolve guards

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#19923]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Regular errors, such as HTTP errors, are correctly be logged as 

```
ERROR HttpErrorResponse
```

When an error occur in a resolve guard, I get a weird stack trace:

```
ERROR Error: Uncaught (in promise): [object Object] 
   at resolvePromise (unpkg.com/zone.js@0.8.12/dist/zone.js:770)
    at resolvePromise (unpkg.com/zone.js@0.8.12/dist/zone.js:741)
    at eval (unpkg.com/zone.js@0.8.12/dist/zone.js:818)
    at ZoneDelegate.invokeTask (unpkg.com/zone.js@0.8.12/dist/zone.js:424)
    at Object.onInvokeTask (unpkg.com/@angular/core@4.3.6/bundles/core.umd.js:3913)
    at ZoneDelegate.invokeTask (unpkg.com/zone.js@0.8.12/dist/zone.js:423)
    at Zone.runTask (unpkg.com/zone.js@0.8.12/dist/zone.js:191)
    at drainMicroTaskQueue (unpkg.com/zone.js@0.8.12/dist/zone.js:584)
    at XMLHttpRequest.ZoneTask.invoke (unpkg.com/zone.js@0.8.12/dist/zone.js:490)
```

## Expected behavior
I expect the resolve error to be logged / handled as any other error, so that we can send it to our error collector (Raygun).

## Minimal reproduction of the problem with instructions
Example of correct error log: https://stackblitz.com/edit/angular-5cl2hn
Example of incorrect error log: https://stackblitz.com/edit/angular-n2gxqp

## Environment
Angular version: tested on both Angular 4.4.4 as Angular 5.0-RC5

Occurs on any fresh CLI generated project.

**Comment by trotyl** [comment]
I guess this should be a feature request.

**Comment by dirkluijk** [comment]
It seems a logging bug to me? :-)

**Comment by jasonaden** [comment]
Is this error specific to guards? Or just uncaught errors in promises? Looks to me like you would have the same issue with an uncaught error in any promise and the stack would be in `resolvePromise` from `zone.js`.

**Comment by dirkluijk** [comment]
@jasonaden The problem seems to be specific to guards. When the HTTP error occurs outside a guard, the logging seems fine.

Here another example: https://stackblitz.com/edit/angular-dmhnvy

**Comment by JiaLiPassion** [comment]
the reason is 

- the correct log is print by `defaultErrorLogger` which will print 
```javascript
((<any>console.error)))(...values)
```
so it will print out all the properties of `HttpErrorResponse`

- the incorrect log is print out by `zone.js` which will output `HttpErrorResponse` itself so it 
will call `HttpErrorResponse.prototype.toString()`.

I will create a issue in `zone.js` and provide a `logger` functionality there. 
so I think you can close this issue here.

**Comment by dirkluijk** [comment]
Thank you @JiaLiPassion.
