### ISSUE TITLE
reportProgress Not Bubbling Up

### ISSUE THREAD

**Issue by rafiwardak2003** [angular/angular#19930]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
This issue is regarding the reportProgress property in the request and there isn't good documentation about it. So I am not sure if this is a bug or how it's intended to work.

I set reportProgress to true in my request, and I have an HTTP interceptor, but the progress event doesn't happen in my service, but happens in the interceptor, which is much lower than what my service receives. Does Angular remove the reportProgress property and only returns me the body at the highest level?

I know the documentation in the method says this:
Construct a GET request which interprets the body as JSON and returns it.

But to expect reportProgress to bubble up, do we have to use the actual http.request method? There should be better documentation on the reportProgress.

My code:

Interceptor:
<pre>
<code>
@Injectable()
export class AuthInterceptorService implements HttpInterceptor {
    constructor(private authService: AuthService,
                private appStateService: AppStateService,
                private router: Router) {
    }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        const url = environment.apiUrl + req.url;
        let headers = req.headers.set('Pragma', 'no-cache');

        if (this.authService.loggedIn) {
            const token = `${(<any>this.authService.currentUser).token_type} ${(<any>this.authService.currentUser).access_token}`;
            headers = headers.set('Authorization', token);
        }

        const authReq = req.clone({ headers, url });
        return next
            .handle(authReq)
            .do((event) => {
                    // Progress work here -- but I want it bubbled up
                },
                (errorResponse: HttpErrorResponse) => {
                    if (errorResponse.status === 401) {
                        this.router.navigate([ '/unauthorized' ]);
                    }

                    if (errorResponse.status === 403) {
                        this.router.navigate([ '/forbidden' ]);
                    }

                    if (errorResponse.status === 500) {
                        this.router.navigate([ '/error' ]);
                    }
                });
    }
}
</code>
</pre>

Service Call:
<pre><code>
@Injectable()
export class DocumentDetailsService {

    constructor(private http: HttpClient) {
    }

    saveDocument(details) {
        return this.http.post('api/v1/documents', details, { reportProgress: true });
    }
}
</code></pre>

And subscribing (reportProgress doesn't happen here... only results/response is returned):
<pre><code>
        this.documentService.saveDocument(details).subscribe(results => {
           // Only results returned - no progress 
        });
</code></pre>

Now if I change the service and do the request in this way, then progress is returned:
<pre><code>
    saveDocument(details) {
        return this.http.request('POST', 'icm/api/v1/documents', details, { reportProgress: true });
    }</code></pre>

But is that how it's supposed to be? Should we not be allowed to use http.get/http.post...?

## Expected behavior
Expect reportProgress to bubble up.

Angular version: 4.4.6

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by rafiwardak2003** [comment]
I read more into the code and played around with it, and I guess you have to observe the events and then it works. Some more documentation on the official doc site would be great. Here's the solution if anyone's having the same issue:

<pre><code>
return this.http.post<IDocumentDetails>('api/v1/documents', details, { reportProgress: true, observe: 'events' });
</code></pre>

**Comment by Itrulia** [comment]
For other people reaching this issue:

This happens if your HttpInterceptor overrides all headers by using `setHeaders`

```
 request.clone({
  setHeaders: {
      Authorization: `Bearer ${token}`
  }
});
```

instead of adding a header via `headers.set`

```
request.clone({
    headers: request.headers.set("Authorization", `Bearer ${token}`)
});
```
