### ISSUE TITLE
routerLinkActive + OnPush + lazy routes = strange behavior

### ISSUE THREAD

**Issue by seangwright** [angular/angular#19934]
## I'm submitting a...

<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using the `routerLinkActive` directive inside a component that is using `ChangeDetectionStrategy.OnPush` and lazy loaded module routes the `routerLinkActive` directive does not update after clicking a link to a lazy loaded route that has not already been loaded.

Also the `OnPush` nav component does not set `routerLinkActive` correctly when the default route loads, the non-`OnPush` nav component works fine.

## Expected behavior
The `routerLinkActive` directive updates the element correctly when navigating to a lazy loaded route for the first time.

## Minimal reproduction of the problem with instructions
My reproduction - https://github.com/seangwright/ng-bug-on-push-routerlinkactive

Live - https://seangwright.github.io/ng-bug-on-push-routerlinkactive/ng-bug-on-push-routerlinkactive

This is a very simple app. There are two lazy routes and two eager routes. There are two navs, one with `OnPush` and one without it.

`npm i && npm start`

## What is the motivation / use case for changing the behavior?
I would prefer to be able to set all my components to `OnPush` for change detection but it doesn't look like this is going to work correctly with the combination I described above.

## Environment

<pre><code>
Angular CLI: 1.5.0-rc.3
Node: 8.6.0
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cli: 1.5.0-rc.3
@angular-devkit/build-optimizer: 0.0.31
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0-rc.3
@schematics/angular: 0.0.48
typescript: 2.3.4
webpack: 3.8.1

Browser:
- [ X] Chrome (desktop) version 61.0.3163
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.6.0
- Platform:  Windows 10 x64

**Comment by trotyl** [comment]
Actually `routerLinkActive` is working fine here, try replace:

```html
<a ... routerLinkActive #rla="routerLinkActive" [class.active]="rla.isActive">
```

to:

```html
<a ... routerLinkActive="active">
```

Then you'll find it update as expected.

The problem here is, `[class.active]="rla.isActive"` is your component's own binding, not `routerLinkActive`'s, so even `rla.isActive` is updated successfully, the `class.active` of your component won't be updated (in `OnPush`).

**Comment by mackelito** [comment]
I have a problem that I think is some kind of race condition..?

```html
<mat-expansion-panel *ngFor="let category of categoryList" (opened)="setActiveCategoryId(category.id)" [expanded]="rla.isActive">
 <mat-expansion-panel-header routerLinkActive="'active'" #rla="routerLinkActive" [routerLink]="['/butik', category.categoryId, category.slug]">{{ category.name }}</mat-expansion-panel-header>
 <p>test</p>
</mat-expansion-panel>
```
I would expect the rla.isActive to be true for 1 item.
the `routerLinkActive="'active'"` does work fine and the element does get class="active"
Any ideas?

**Comment by trotyl** [comment]
It's just the nature of Angular's change detection mechanism. It would only update the view after dirty-checking the bound value.

So since your own component is behind `OnPush`, although `rla.isActive` is changed, but your component won't check its result, then no update is applied to the view of your component.

**Comment by mackelito** [comment]
I see.. do you have any pointers on how I could work around this until we can upgrade to angular5 where it has been solved :)

**Comment by trotyl** [comment]
One hacking way:

```typescript
import { Component, ChangeDetectionStrategy, ChangeDetectorRef, OnDestroy } from '@angular/core';
import { NavigationEnd, Router } from '@angular/router';
import { Subscription } from 'rxjs/Subscription';

@Component({
  selector: 'app-navigation-on-push',
  /* ... */
})
export class NavigationOnPushComponent implements OnDestroy {
  routes = [/* ... */];
  private subscription: Subscription;

  constructor(private cdRef: ChangeDetectorRef, private router: Router) {
    this.subscription = router.events.subscribe(s => {
      if (s instanceof NavigationEnd) {
        setTimeout(() => cdRef.detectChanges());
      }
    });
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
}
```

**Comment by trotyl** [comment]
Some update, this is likely to be a **regression**, it should work before the https://github.com/angular/angular/commit/82417b3ca59aa2e5f41ee12db4cb18970b5b4f47 change (which is a fix of another regression). Could you please update the issue body to reflect it?

**Comment by maxisam** [comment]
I think "RouterLinkActive should expose an Observable version of isActive" is a great idea. Any chance it will be implemented?

**Comment by jasonaden** [comment]
@vicb Can you take a look at this? It appears we regressed with your change #15943.

**Comment by tropetre** [comment]
Any updates on this? The suggested workaround is somehow not working for me despite the class being set.

**Comment by stephanecot** [comment]
same need here

**Comment by studds** [comment]
Is there an ETA for a fix? Or any workaround for this?

**Comment by vincentjames501** [comment]
+1. Just ran into this issue myself.

**Comment by BenLune** [comment]
Hi there,
Here is the way I hacked it, the one proposed above didn't work for me. I'm working with dynamic queryParams for search engine requests driven by urls.
`getActiveQueryParams(key: string): Observable<boolean>{
    return this.activatedRoute.queryParams.pipe(map(queryParams => queryParams && queryParams[key] != null));
  }`

**Comment by kwiniarski97** [comment]
Only workaround I found is to add property `url` and subscribe to router.events and in case of `navigationend` update property and run `cd.detectChanges()`. Then in template you can do whatever you want because you got valid `url`.

**Comment by vasyliv** [comment]
is there any updates?

**Comment by joselcvarela** [comment]
Hey,
I was having this issue and I was working on this during the entire morning but finally I found a simple solution but not elegant.
I am using  `ChangeDetectionStrategy.OnPush` and I am fetching data on guards, so the page only loads if the guard could fetch data successfully. This behavior broken some components since no change detection occurs. So, my solution was to access `routerLinkActive` on typescript (through `ViewChild`) and then in the right place force the update

```
@ViewChild(RouterLinkActive) private rla: RouterLinkActive;
...
@Input() set link(link: string) {
  (this.rla as any).update()
}
```

**Comment by Scipionh** [comment]
Run into the problem today. Angular 9.1.1

**Comment by Stehlert** [comment]
I have the same issue with Angular 9.1.2
