### ISSUE TITLE
bug(service-worker): `/` path is omitted by ngsw-config

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#19945]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, an index path, `/`, is omitted by `ngsw-config` command. It was supported as `routing` in old ngsw version.

```
$ ngsw-config ./src ./src/ngsw.base.json
```

ngsw.base.json 
```
{
  "index": "src/index.html",
  "assetGroups": [
    {
      "name": "site",
      "mode": "prefetch",
      "resources": {
        "files": [
          "/",
          "/favicon.ico",
          "/index.html"
        ],
        "urls": [
          "https://fonts.googleapis.com/**"
        ],
        "versionedFiles": [
          "/*.bundle.css",
          "/*.bundle.js",
          "/*.chunk.js"
        ]
      }
    }
  ]
}
```

Generated ngsw.json
```
{
  "configVersion": 1,
  "index": "/src/index.html",
  "assetGroups": [
    {
      "name": "site",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "urls": [
        "/favicon.ico",
        "/index.html"
      ],
      "patterns": [
        "https:\\/\\/fonts\\.googleapis\\.com\\/.*"
      ]
    }
  ],
  "dataGroups": [],
  "hashTable": {
    "/favicon.ico": "84161b857f5c547e3699ddfbffc6d8d737542e01",
    "/index.html": "e5defb09b5dadd8903d71b868022bf69fc954f39"
  }
}
```

## Expected behavior

`/` should be emitted as `urls` to cache index.html for offline support.

```
{
  "configVersion": 1,
  "index": "/src/index.html",
  "assetGroups": [
    {
      "name": "site",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "urls": [
        "/", // <= should be in here
        "/favicon.ico",
        "/index.html"
      ],
      "patterns": [
        "https:\\/\\/fonts\\.googleapis\\.com\\/.*"
      ]
    }
  ],
  "dataGroups": [],
  "hashTable": {
    "/favicon.ico": "84161b857f5c547e3699ddfbffc6d8d737542e01",
    "/index.html": "e5defb09b5dadd8903d71b868022bf69fc954f39"
  }
}
```

## What is the motivation / use case for changing the behavior?

I tried to migrate my app to new ngsw with https://github.com/angular/angular/pull/19795 as a referrence. But `index.html` is never cached. 

## Environment

Angular CLI: 1.5.0-rc.3
Node: 6.11.2
OS: darwin x64
Angular: 5.0.0-rc.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker
 
cc/ @alxhub @webmaxru

**Comment by webmaxru** [comment]
You don't need to add `/` at all. The routing is done automatically now (there is no need to specify anything for this anymore). I believe you have caching failed because of non-default base-href. Do you pass it as a 3rd parameter to ngsw CLI? In your case it should look like this: `ngsw-config dist src/ngsw.base.json /src`

Offtop: @lacolaco, I'm in Tokyo Nov 13-16. My pleasure to meet you and maybe present something at ngJapan meetup!

**Comment by lacolaco** [comment]
Hmm... I changed `index` property from `/src/index.html` to `/index.html`, but it seems not working well.

generated ngsw.json

```
{
  "configVersion": 1,
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "site",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "urls": [
        "/favicon.ico",
        "/index.html"
      ],
      "patterns": [
        "https:\\/\\/fonts\\.googleapis\\.com\\/.*"
      ]
    }
  ],
  "dataGroups": [],
  "hashTable": {
    "/favicon.ico": "84161b857f5c547e3699ddfbffc6d8d737542e01",
    "/index.html": "e5defb09b5dadd8903d71b868022bf69fc954f39"
  }
}
```

![image](https://user-images.githubusercontent.com/1529180/32061186-f11f289a-baab-11e7-9dcb-5f806948e31b.png)

this project is made by Angular CLI adding ngsw files.

![image](https://user-images.githubusercontent.com/1529180/32061307-3992dd74-baac-11e7-84fc-3dbfa714d218.png)

P.S. @webmaxru I want to see you, too! please send email to suguru.inatomi[at]gmail.com about your trip. Let's adjust our schedule :)

**Comment by webmaxru** [comment]
Try to upgrade to RC.6. Most likely it's the same bug as was in https://github.com/angular/angular/issues/19490

**Comment by lacolaco** [comment]
I already upgraded to RC.6. (see environments in 1st comment)

**Comment by lacolaco** [comment]
still happening in RC.7

**Comment by alxhub** [comment]
Hi @lacolaco,

Once your site loads, please open a tab and access the debugging URL `/ngsw/state`, and paste the contents here.

Thanks!

**Comment by lacolaco** [comment]
@alxhub Thank you. the below is that. 

```
NGSW Debug Info:

Driver state: NORMAL ((nominal))
Latest manifest hash: none
Last update check: never



=== Idle Task Queue ===
Last update tick: never
Last update run: never
Task queue:


Debug log:

```

**Comment by alxhub** [comment]
@lacolaco please have that URL open, refresh your app, wait a few seconds and refresh the debug URL. That log indicates a service worker that has never seen a `fetch`.

**Comment by lacolaco** [comment]
@alxhub that's right. there is no log.

![2017-10-28 10 13 26](https://user-images.githubusercontent.com/1529180/32129900-c28a5fcc-bbc8-11e7-9deb-d0186bbe4db6.gif)

The weird thing is `favicon.ico` is cached correctly. Why not `index.html`?

**Comment by lacolaco** [comment]
Ahhh, sorry, I've enabled service worker's `update on reload` option. I just got actual logs

```
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Hash mismatch (cacheBustedFetchFromNetwork): http://localhost:4200/index.html: expected e5defb09b5dadd8903d71b868022bf69fc954f39, got 002a296589766e144eda3002b7feb8b6e5ee1ac5 (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): http://localhost:4200/index.html: expected e5defb09b5dadd8903d71b868022bf69fc954f39, got 002a296589766e144eda3002b7feb8b6e5ee1ac5 (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (http://localhost:4200/ngsw-worker.js:657:27)
    at <anonymous>)
Latest manifest hash: 1e8cde0a19381fa6a01acbeefefa861865f34a1f
Last update check: 3s374u

=== Version 1e8cde0a19381fa6a01acbeefefa861865f34a1f ===

Clients: 

=== Idle Task Queue ===
Last update tick: 2s28u
Last update run: 3s380u
Task queue:


Debug log:

[8s401u] Error(Hash mismatch (cacheBustedFetchFromNetwork): http://localhost:4200/index.html: expected e5defb09b5dadd8903d71b868022bf69fc954f39, got 002a296589766e144eda3002b7feb8b6e5ee1ac5 (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): http://localhost:4200/index.html: expected e5defb09b5dadd8903d71b868022bf69fc954f39, got 002a296589766e144eda3002b7feb8b6e5ee1ac5 (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (http://localhost:4200/ngsw-worker.js:657:27)
    at <anonymous>) initializeFully for 1e8cde0a19381fa6a01acbeefefa861865f34a1f
```

**Comment by lacolaco** [comment]
Repro: https://github.com/lacolaco/angular-service-worker-example/tree/3f68c1ba33eb6482db0e76f660f1de80d53e6ade

**Comment by lacolaco** [comment]
At 5.0.0 stable, I finally get my offline cache!! I appreciate the team.
