### ISSUE TITLE
Docs should show what replaces deprecated usages

### ISSUE THREAD

**Issue by kassimir** [angular/angular#19948]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, WebStorm informs me that code is deprecated; however, when I check that code in the docs, it says nothing about deprecation or what supersedes it.

## Expected behavior
In order to upgrade, it would be nice to know what I need to upgrade.

## Minimal reproduction of the problem with instructions
Use any @angular/http modules in WebStorm, and it will show you that it's deprecated.  Then check that module in the docs, and notice that it says nothing about deprecation

## What is the motivation / use case for changing the behavior?
I'd like to continue to be at the forefront of Angular's versions, but I'm stumbling on the upgrade, because I have to comb through the code and figure everything out on my own... which my boss isn't too fond of paying me for.

## Environment
<pre><code>
Angular version: 5.0.0.rc6

Browser:
N/A
 
For Tooling issues:
- Platform:  Also, pretty much N/A, but Windows/WebStorm is what I'm using
</code></pre>

**Comment by sarunint** [comment]
Yes, it's deprecated in Angular v5.

https://next.angular.io/api/http/Http

**Comment by kassimir** [comment]
Yes, that page shows that HTTPClient should be used instead; however, there is much more that is deprecated, like RequestOptions, ConnectionBackend, XHRBackend, etc, and none of those say what is replacing it - only to use HTTPClient instead.  That's great, but what is replacing those specific modules?

**Comment by kapunahelewong** [comment]
Hey @kassimir thanks for feedback. Sometimes there's an easy one to one replacement, and in this case there are some other related scenarios. Your issue has sparked some good discussion within the docs team on this and it will take some design work. Thanks for this important feedback and contributing to the discussion.

**Comment by sarunint** [comment]
From my experience, migration from `Http` to `HttpClient` is pretty straightforward.

Still +1 for migration docs though.

**Comment by kassimir** [comment]
> From my experience, migration from Http to HttpClient is pretty straightforward.

Much of it is, yes; however, we have a custom http module that extends the HTTP class. The super() expects a backend and defaultOptions on @angular/http, whereas the super() for common/http only expects httphandler.  So where do the RequestOptions go? I don't know. I have to analyze the new HttpClient code itself to figure this out, because the docs don't mention it. It would be much easier to go to the RequestOptions page with a note that "Hey, these options are now here."

**Comment by trotyl** [comment]
@kassimir Class constructor is not a part of public API, only the usage via DI is guaranteed.

> constructors of injectable classes (services and directives) - please use DI to obtain instances of these classes

Please checkout [PUBLIC_API](https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md) for more information.

**Comment by kapunahelewong** [comment]
@sarunint we also have to consider the implications within the docs and how we communicate these shifts. So there are two parts to consider, the change a developer has to make in their app, but also how and where we make this information clear and available in a consistent way. So code + docs + examples = design thinking/work for all the moving pieces. Hope that helps clarify my use of the phrase "related scenarios".

**Comment by matsko** [comment]
This might be because angular.io is still on the 4.x branch. Once 5.0.0 comes around (sometime next week) it will have the deprecation details about @angular/http.

Please reopen if I didn't address something else here.

**Comment by fidel-ruiz** [comment]
I'm trying to migrate from 4.4,x to 6.0.x RequestMethod and RequestOptions are the ones giving me troubles which are the equivalents for those 2 in the newest angular version. In the first, I could replicate that by creating the enum for HTTP methods, but this workaround is not as easy for the other one, of course, we could migrate everything to use interceptors and all new stuff or rewrite our HTTP helpers logic.
