### ISSUE TITLE
Failed to load chunk x after redeploy

### ISSUE THREAD

**Issue by ScottSpittle** [angular/angular#19944]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If you have your application open and then redeploy it while still viewing it, then navigate to another route an Exception is thrown and the application is no longer usable until you refresh (F5)

## Expected behavior

The new chunks should get loaded in without issue and the user should be able to navigate without being forced to refresh

## Minimal reproduction of the problem with instructions

Follow instructions under # Current behavior

## Environment
Nginx/AWS

<pre><code>
Angular version: X.Y.Z

4.4.6

Browser:
- [ x ] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform: Linux  

Others:

</code></pre>

**Comment by trotyl** [comment]
There is nothing related to Angular, you can report it in Angular CLI if you want.

**Comment by josephliccini** [comment]
You could use `PreloadAllModules` `PreloadStrategy` I think?  That way they are available in browser cache.  I haven't tried this myself but I think that would work?

**Comment by jasonaden** [comment]
Closing as this appears to be CLI related, not an Angular issue.

**Comment by sgruhier** [comment]
any update (even on Angular CLI, I didn't find anything about it)?
