### ISSUE TITLE
No way to get the active locale in AoT i18n

### ISSUE THREAD

**Issue by adrm** [angular/angular#19942]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have been looking for a way to get the active i18n locale at runtime, but I only found how to do so when JIT compiling. I would like to be able to get the active locale with AoT.

## Expected behavior

It should be a way to get the active locale when using AoT i18n.

## What is the motivation / use case for changing the behavior?

Other libraries need to know the locale to be able to configure themselves at runtime.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by spock123** [comment]
`import { LOCALE_ID } from '@angular/core';`

**Comment by adrm** [comment]
Oops, I'm sorry. Looked for it on the docs and asked in the community chat and I couldn't have an answer, so I thought this feature was missing.

I'll try that, thanks a lot!
