### ISSUE TITLE
keypress on firefox, backspace is handled

### ISSUE THREAD

**Issue by thduttonuk** [angular/angular#19943]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Backspace is handled on a keypress in firefox, but not in chrome or edge

## Expected behavior

Firefox should not handle the backspace keypress  event

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/JDBpuNOQ7kZV80OjvNRv?p=preview

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version 56.0.1 (64-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by PaluMacil** [comment]
The html spec says that keypress is valid for keys that produce a character. A browser's interpretation of the spec cannot be worked around by Angular, but you can use keydown or keyup.

**Comment by PaluMacil** [comment]
#19919 from two days ago is the same thing (except about keypress on backtick) and I linked to Google saying some time ago that this is a correct interpretation of the spec.

**Comment by thduttonuk** [comment]
@PaluMacil  Thanks, I was using keypress because I only wanted to handle the event when a key produced a character. I can easily work around it. 

Should Angular not capture the keypress event and only pass the event onto the component when the chars are valid for the HTML spec?

**Comment by trotyl** [comment]
Angular only capture what's emitted, please try google it first:

+ https://stackoverflow.com/questions/31580493/backspace-key-issue-in-firefox
+ https://stackoverflow.com/questions/14050086/firefox-keydown-backspace-issue
+ https://stackoverflow.com/questions/4843472/javascript-listener-keypress-doesnt-detect-backspace
+ https://stackoverflow.com/questions/32972258/firefox-keypress-bug-cant-use-backspace-with-only-letter-input-script
