### ISSUE TITLE
Component lifecycle hooks not firing if another component calls detectChanges during the first component's first ngOnChanges call

### ISSUE THREAD

**Issue by trevorade** [angular/angular#19959]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior

If two components displayed at the same time (the first existing, the second being added to the page) and code run during the second component's `ngOnChanges` results in the first component calling `ChangeDetectorRef.detectChanges`, the second component will not receive `ngOnInit`, `ngAfterContentInit`, nor `ngAfterViewInit`.

## Expected behavior

Even if the first component calls `detectChanges`, the second component should continue to receive lifecycle hooks.

## Minimal reproduction of the problem with instructions

Please see repro and steps here: http://plnkr.co/edit/N9k8TTvKOUpDEVul03pK?p=preview

This is probably not as minimal as it could be.  I boiled down a larger example I was working on.

## What is the motivation / use case for changing the behavior?

This is just an undesirable bug.  This particular repro is slightly convoluted (though I'm actively working on a larger version of this for use with configuring a single application toolbar).  In general, I believe this sort of issue could arise in many more instances.

## Environment

Angular version: 2.4.1 (I'm not sure how to test 2.5 RC in Plunker).

Browser:
- [X] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by jasonaden** [comment]
Please update to a current version of Angular (either `4.4.5` or `5.0.1`). If your problem still exists, update your reproduction and create a new issue.

**Comment by trevorade** [comment]
@jasonaden, OK.  Please update your New Issue template to include a Plknr link with up-to-date Angular links.  It's still on 2.4.1

**Comment by trevorade** [comment]
Still repros.  Created https://github.com/angular/angular/issues/20394
