### ISSUE TITLE
Why use compiler-cli instead of  tsc-wrapped?

### ISSUE THREAD

**Issue by DavidParks8** [angular/angular#19964]
If I am writing a node command line tool that internally compiles angular code, why should I use compiler-cli instead of tsc-wrapped? What is the difference between them?

**Comment by LinBoLen** [comment]
I have github reaction, pls stop to submit the useless issue.

just take a peek into the code of compiler-cli.

**Comment by ocombe** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
