### ISSUE TITLE
angular projects fail on # in the path

### ISSUE THREAD

**Issue by sboden** [angular/angular#19960]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If an angular project is on a path containing a # somewhere it will fail to start up.

## Expected behavior
A # is just like any other character.

## Minimal reproduction of the problem with instructions

mkdir test#
cd test#
ng new hello-app
cd hello-app
ng serve

## What is the motivation / use case for changing the behavior?
A bug report in angular-cli which I debugged to here,
I have a fix for 5.x, I also have a fix for v4.4.x

## Environment

<pre><code>
Angular version: 5.0.0-rc.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.5 (installed to debug v4.4.x)
- Platform:  All

Others:

</code></pre>

**Comment by JoostK** [comment]
I was able to reproduce this in Angular 5.2, but it appears to have since been fixed. Using Angular 9.1 using both View Engine and Ivy this bug does not occur.
