### ISSUE TITLE
Angular2 - Unit test case not able to Mock Service

### ISSUE THREAD

**Issue by jindalrohit** [angular/angular#19972]
I am not able to mock user service, other service which I mocked are working fine. If I am commenting user service then unit test case is working fine. There are many components which are using user service. Unit test cases for all those components are not working in which user service is injected.

**Error : Can't resolve all parameters for AlertService: ([object Object], ?, [object Object], [object Object]).**

Code for Mock user service :

```
@Injectable() 
class MockUserService {   
    private data$: Observable<Object>;   
    readonly user$: Observable<any>;   
    readonly privilege$: Observable<any[]>;    

    constructor() {     
        this.data$ = Observable.of({});
        this.user$ = Observable.of({ me: 'test' });     
        this.privilege$ = Observable.of([{ testing: 'true' }]);   
    }     

    hasPrivilege(privilege): Observable<boolean> {     
        return Observable.of(true);    
    }  
}
```

**I am using the mock service like this :**

`{ provide: UserService, useClass: MockUserService }`

**Comment by aravindfz** [comment]
can you add a working example?

**Comment by jindalrohit** [comment]
It's resolved now.
[Here](https://stackoverflow.com/questions/46968604/angular2-unit-test-case-not-able-to-mock-service/47037915?noredirect=1#comment81050856_47037915)
