### ISSUE TITLE
[routerLink]="foo",the foo is encoded

### ISSUE THREAD

**Issue by eminoda** [angular/angular#19973]
html:
````
<a [routerLink]="headTab.path">{{headTab.path}}
````
ts，component:
````
headTab.path = ['/dotrade', { pzType: 0 }]
````
result:
````
<a _ngcontent-c2="" ng-reflect-router-link="/dotrade;pzType=0" class="" href="....../dotrade;pzType%3D0">/dotrade;pzType=0</a>
````
Question:
why the '='  change to '%3D'

when i change html like this，it will be ok？
````
<a [routerLink]="['/dotrade', { pzType: 0 }]">{{headTab.path}}
<a _ngcontent-c2="" ng-reflect-router-link="/dotrade,[object Object]" class="" href="....../dotrade;pzType=0">/dotrade;pzType=0</a>
````

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by eminoda** [comment]
tks
