### ISSUE TITLE
Site not rendering on some IOS devices [White screen of death?]

### ISSUE THREAD

**Issue by kenji-1996** [angular/angular#19976]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
My application which I have built and uploaded to https://callum.tech/new will not render on some IOS devices, I havnt tested this on a huge array but I have tested it on 2 devices, my personal iPhone 5 running IOS 10.3.3 and my friends iPad which I cannot recall the version.
It will simply render a white page, no matter how many refreshes, or going into 'private' etc it refuses to render.
To eliminate the potential for this being just my phone (when I first discovered the issue) I fully formatted it to factory settings and still same result, tried on multiple locations (aka varying IPs), tried VPN, wifi to mobile etc.

Here is it running on http://browserstack.com and return a white page with no real errors:
https://i.imgur.com/ChHuLaY.png

## Expected behavior
Pages renders like it does in some IOS devices and andriod

## Minimal reproduction of the problem with instructions
Here is my full up to date github of the project: https://github.com/kenji-1996/CallumTech
I am not sure how it can be fully tested, but I cannot even debug the potential console errors because I do not own a mac to use Safari 6 web inspector feature

## What is the motivation / use case for changing the behavior?
I want my site to actually run

##Note
I have had older versions working fine on my phone, i am not sure what point it started breaking

## Environment

<pre><code>
Angular version:  4.4.6, is this the latest?

Browser:
- [x ] Chrome (iOS) version 'CriOS/62/0/3203/70 Mobile/14G60 Safari/602.1
- [x ] Safari (iOS) version 602.1
 
For Tooling issues:
- Node version: v8.4.0
- Platform:  IOS

Others:
- Build using this: ng build --prod --base-href /new/ --build-optimizer

</code></pre>

**Comment by justinotero** [comment]
Hi Kenji-1996, 

I was not able to reproduce this bug on my iPhone 6.

iOS Version: 11.0.3 
Safari Version is coupled with iOS Version
Chrome Version: 62.0.3202.70


> I cannot even debug the potential console errors because I do not own a mac to use Safari 6 web inspector feature

On that note, I'd suggest trying a free trial on http://browserstack.com. This will allow you to emulate a specific device and OS for testing. Hope this helps you move forward a bit.

**Comment by kenji-1996** [comment]
@justinotero Appreciate the link and test, It seems to be hot or miss what devices it works for so ill try and narrow down the problem more and hopefully debug it

**Comment by kenji-1996** [comment]
For some damn reason the fix was to include 'encapsulation: ViewEncapsulation.None' in here:
```
@Component({
    selector: 'app-navbar',
    templateUrl: './navbar.component.html',
    styleUrls: ['./navbar.component.scss'],
    encapsulation: ViewEncapsulation.None
})
```
I have no clue why this is the 'decider' for some phones etc to show my site is this stupid line but this fixed all whitescreen issues.
No error or anything, I just sent hours going over past commits and pulled one that finally worked, narrowed it down to this.

@justinotero thanks so much for the help and the good resource in browser stack i will definatly use that in future for testing!

**Comment by Anupriya20** [comment]
HI guyz,
I have same issue in iOS version 9.3.5 in iPAD safari browser.
I have already included ViewEncapsulation.None line still white screen appearing. No any issue in console.

@Component({
    selector: 'app-root',
    encapsulation: ViewEncapsulation.None,
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
