### ISSUE TITLE
Angular Animation - behaves differently in Routed Component vs. App Component

### ISSUE THREAD

**Issue by CanKattwinkel** [angular/angular#19970]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Animation does not execute when the component is routed. In the reproduction repository you can find two examples of the same Animation that behave differently. If the component is routed the animation doesn't fire in the beginning (second list). If the animation is played in the AppComponent (first list) everything is fine.   

![demo](https://user-images.githubusercontent.com/11500619/32090105-05df448a-baee-11e7-816a-f314adf6266b.png)

Or is this wanted behavior? @matsko maybe you can say something about that.  

## Expected behavior
Animation behaves the same regardless of whether the component is routed or not.

## Minimal reproduction of the problem with instructions
Reproduction demo:
https://cankattwinkel.github.io/animation-issue/
Reproduction src:
https://github.com/CanKattwinkel/animation-issue

## What is the motivation / use case for changing the behavior?
-

## Environment
I have tested with **5.rc6** and the most **recent version of Angular 4**  (src in Repo is 4.4.6)

<pre><code>
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [?] Chrome (iOS) version XX
- [x] Firefox version XX
- [?] Safari (desktop) version XX
- [?] Safari (iOS) version XX
- [?] IE version XX
- [?] Edge version XX

**Comment by CanKattwinkel** [comment]
@petebacondarwin `||` @vicb:
I think you got the ticket reference in the commit message mixed up.  feae55b is not connected to this ticket. Please **re-open.**

**Comment by petebacondarwin** [comment]
Oops. Sorry.

**Comment by matsko** [comment]
I believe this PR with fix this issue #19455. Next week is when it should land.

**Comment by CanKattwinkel** [comment]
@matsko yes i can confirm the issue is fixed. I have bumped the example repository to 5.1.0-rc.1 and the animation is working
