### ISSUE TITLE
How to apply the loading animation  when loadChildren is loading  ?

### ISSUE THREAD

**Issue by huantian2415** [angular/angular#19977]
My app spends 2.5s  on lazyload , beacuse I put 20 components  into one loadChildren. If I divided  those components  into more  loadChildren  ,it  would be  solved;   Anyway, I just want to use one loadChildren .  Although just have no idea  about how to  use the loading animation when loadChildren is loading ;
SOS;

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
