### ISSUE TITLE
Custom validator does not make FormGroup invalid unless there is at least one control enabled.

### ISSUE THREAD

**Issue by kangjinyong** [angular/angular#19971]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Custom form validator does not make the form invalid if all controls are disabled.

## Expected behavior

Validator should execute regardless of state of controls.

## Minimal reproduction of the problem with instructions

"Update" button should be disabled if form is invalid (Sum is not 100). Currently this only happens when there is at least one control enabled in the FromGroup.

https://plnkr.co/edit/yvHOPtF772we45P0VgqN

## What is the motivation / use case for changing the behavior?

Similar to the plunker, I am validating the sum of multiple controls. If the sum is not 100, I do not want the users to be able to save the values.

However, the validator is not executing when there are no controls enabled.

## Environment

<pre><code>
Angular version: 4.2.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 All

For Tooling issues:
- Node version: v6.11.2  
- Platform: Windows 

Others:

</code></pre>

**Comment by djnaumov** [comment]
This happens because of all controls on the form is disabled. Form is think as disabled. It the same behavior if you just call disable on form.
```
this.form.disable();
```

**Comment by kara** [comment]
There are four **mutually-exclusive** validation statuses a form can have: VALID, INVALID, DISABLED, or PENDING. When all your controls are disabled, your form has a status of DISABLED (which means it's exempt from validation checks), so the `invalid` check will be false. I believe what you want in your button condition is `!form.valid` or `form.invalid || form.disabled`.

See more at docs here: https://angular.io/api/forms/AbstractControl#status.
