### ISSUE TITLE
Lambda in loadChildren not handled with target ES2015+

### ISSUE THREAD

**Issue by staeke** [angular/angular#19978]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior/Expected
I added a new ticket for https://github.com/angular/angular/issues/13692 since it's still an issue and that other ticket is closed.

If you have target ES2015+:

Writing 
```
loadChildren: function() {...}
```
works, whereas 
```
loadChildren: () => {...}
```
doesn't. Hence, normally transpiling "fixes" your problem for you. Oh and plunkr does transpile for you (at least I don't know how to turn it off) so it can't be reproduced there.

## Minimal reproduction of the problem with instructions
see above

## Environment
Angular 4.4.6 

Browser:
- [ X] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by trotyl** [comment]
You can provide a GitHub repo to reproduce with clear steps.
Meanwhile, SystemJS do support [configuration for TypeScript](https://github.com/frankwallis/plugin-typescript#configuration).

**Comment by staeke** [comment]
thanks @trotyl here's the plunkr then https://plnkr.co/edit/b7MqM8Ylf58peQRMik37?p=preview

**Comment by Axinet** [comment]
Inline function also not always compiles with no errors. I had to use exported named function as the argument of "loadChildren:". Any chances to add support for lamda/arrow functions here?
