### ISSUE TITLE
HttpTestingController.expectOne() not working with queryparameters

### ISSUE THREAD

**Issue by lenn3k** [angular/angular#19974]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Related to #19903
When testing a request that contains query parameters, the test throws 2 errors:
1. Expected one matching request for criteria "Match URL: ./assets/mock/modules.json", found none.
2. Expected no open requests, found 1: GET ./assets/mock/modules.json

![lgbwi](https://user-images.githubusercontent.com/5948048/32176138-1eeba1c6-bd87-11e7-825c-fdc1410d34f7.png)

Appending the paramters to the expected URL does not work either.

## Expected behavior

Test failure message should show the full path including parameters.
OR
We should be able to specify expected parameters or ignore all.

## Minimal reproduction of the problem with instructions

<pre><code>[example.service.spec.ts]

import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
import { Injector } from '@angular/core';
import { async, TestBed } from '@angular/core/testing';
import { ExampleService } from './example.service';

fdescribe('Create a test suite for the Example Service', () => {
    let injector: Injector;
    let exampleService: ExampleService;
    let httpMock: HttpTestingController;

    beforeEach(() => {
        injector = TestBed.configureTestingModule({
            imports:
                [HttpClientTestingModule],
            providers:
                [ExampleService]
        });
        exampleService = injector.get(ExampleService);
        httpMock = injector.get(HttpTestingController);
    });

    afterEach(() => {
        httpMock.verify();
    });

    it('should not immediately connect to the server', () => {
        httpMock.expectNone({});
    });

    describe('when fetching all stuff', () => {
        it('should make a GET request', async(() => {
            exampleService.getStuff();

            let req = httpMock.expectOne(`./assets/mock/modules.json`);
            expect(req.request.method).toEqual('GET');
            req.flush([]);
        }));
    });
});
</code></pre>

<pre><code>[example.service.ts]

import { HttpClient, HttpParams } from '@angular/common/http';
import { Injectable } from '@angular/core';

@Injectable()
export class ExampleService {

    constructor(private http: HttpClient) {
    }

    getStuff() {
        let params = new HttpParams().append('testparam', 'testvalue')
        return this.http.get('./assets/mock/modules.json', {params}).toPromise().then(value => {
            return value
        })
    }
}
</code></pre>

## What is the motivation / use case for changing the behavior?

Currently it is impossible to test http requests in a service which contain query parameters.

## Environment

<pre><code>
Angular version: 4.4.4

Browser:
- [X] Chrome (desktop) version 61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: V8.4.0  
- Platform: Windows  

Others:

</code></pre>

**Comment by lenn3k** [comment]
The code in this issue seems to work and the actual bug is related to adding params to the http-request.
I will investigate further if this is an actual bug or if there is a different cause.

**Comment by lenn3k** [comment]
Issue related to parameters in the request, not the fact that it returned a promise

**Comment by textbook** [comment]
I just came across the same problem. Fixing the error message would be one improvement, but in my view it would be even better if it matched against [`request.url`](https://angular.io/api/common/http/HttpRequest#url) rather than [`request.urlWithParams`](https://angular.io/api/common/http/HttpRequest#urlWithParams). I'd rather write:

```
const req = httpMock.expectOne({ method: 'GET', url: 'http://example.org' });
expect(req.request.params.get('foo')).toEqual('bar');
```

than:

```
httpMock.expectOne({ method: 'GET', url: 'http://example.org?foo=bar' });
```

not least because it avoids any ordering issues when you have more than one parameter.

---

A current workaround is to use the request matcher function instead:

```
const req = httpMock
    .expectOne(req => req.method === 'GET' && req.url === 'http://example.org');
```

**Comment by samih-dev** [comment]
Hi @lenn3k @textbook 

Did the promise usage works for you? and if yes, can you please provide an example?

Thanks!

**Comment by textbook** [comment]
@samih-dev it's not clear how that's relevant to this issue. Per [this comment](https://github.com/angular/angular/issues/19974#issuecomment-340463015) by the OP it's not about promise vs. observable, and my suggestion is independent of either.

**Comment by samih-dev** [comment]
@textbook, from @lenn3k  comment:
`Issue related to parameters in the request, not the fact that it returned a promise`

I thought he was able to test using promises instead of observable, I need an example test for that as its not working for me, 

This what I exactly meant, 
sorry for not be elaborative enough about this before.

**Comment by juristr** [comment]
Just ran into this as well. What you could do however is to use the following check

```
  it('should add HTTP params', () => {
    service.fetchAll({ name: 'Juri' }).subscribe();

    const req = httpTestingController.expectOne(req => req.params.has('name'));

    req.flush({});
  });
```

Or in a more complex case, where for instance I check whether my service method removes all null/undefined/empty values from the query url, I simply check whether it's the current URL in the `expectOne` and then I access the request and add expect statements for the individual params.

```
  it('should remove null/undefined/empty values from HTTP params', () => {
    service
      .fetchAll({ name: 'Juri', age: null, street: undefined, location: '' })
      .subscribe();

    const req = httpTestingController.expectOne(req => req.url.includes('district'));

    expect(req.request.params.has('name')).toBeTruthy();
    expect(req.request.params.has('age')).toBeFalsy();
    expect(req.request.params.has('street')).toBeFalsy();
    expect(req.request.params.has('location')).toBeFalsy();

    req.flush({});
  });
```

**Comment by textbook** [comment]
@juristr yes, I showed above how you can use the function argument to `expectOne` to get the request handle then assert on the parameters; the point of this feature request is that it shouldn't be necessary. Also, note that one obvious problem with your tests is that you never actually test the *values* of those query parameters.

**Comment by peter-snr** [comment]
Spend over an hour trying to get a single test with a singe query param to work to no avail, have tried all solutions above. Now I am getting...

Error: Expected one matching request for criteria "Match by function: ", found none.

 Other tests without query params work.

Shame, cannot spend any more time on this, test commented out in my code :(

**Comment by gmkumar2005** [comment]
I am able to proceed. This is not a bug.
I had similar issue "Match by function: ", found none.
It is solved after i added empty handler for then() in-case the method returns a Promise and subscribe() in-case method returns a Observable.
`.then(
            (data) => {
                console.log('success');
            }`

`.subscribe(
            () => {
                console.log('success');
            } `

**Comment by TommyCpp** [comment]
I have run into similar issue. I work out by subscribing the http request with a empty function.

For example:
* The following code will produce a `Expected one matching request for criteria "Match URL: http://localhost", found none.` Error
```
   it('should send request',
    inject([HttpClient, HttpTestingController],
      (httpClient: HttpClient, httpTestController: HttpTestingController) => {
        httpClient.get("http://localhost");
        httpTestController.expectOne("http://localhost");
      }));
```

* while the following code will pass
```
  it('should send request',
    inject([HttpClient, HttpTestingController],
      (httpClient: HttpClient, httpTestController: HttpTestingController) => {
        httpClient.get("http://localhost").subscribe((data: any) => {
        });    // **Note I subscribe a function here**.
        httpTestController.expectOne("http://localhost");
      }));
```

**Comment by textbook** [comment]
That's not the same thing at all. The problem you're seeing is that, as documented, the http methods don't make a request until they're subscribed to. You don't actually _have_ any query params.

**Comment by algorys** [comment]
Same thing happens to me for my project:

**Class:**

```typescript
import {Injectable} from '@angular/core';
import {HttpClient, HttpHeaders, HttpParams} from "@angular/common/http";
import {Observable} from "rxjs/Observable";


const BACKEND_PAGINATION_LIMIT = 25;

@Injectable()
/**
 * Class who make requests on Alignak backend
 * Injectable service
 */
export class BackendClient {
  token: string;
  url: string;

  /**
   * @param {HttpClient} http - http client for requests
   */
  constructor(public http: HttpClient) {
    this.updateData()
  }

  /**
   * Update data of backend: {@link url} and {@link token}
   */
  private updateData(){
    this.token = localStorage.getItem('token');
    this.url = localStorage.getItem('url');
  }

  /**
   * GET http function
   * @param {string} endpoint - endpoint of request
   * @param {HttpParams} params - http parameters of request
   * @param {HttpHeaders} headers - http headers of request
   * @returns {Observable<Object>} - observable object
   */
  private get(endpoint: string, params?: HttpParams, headers?: HttpHeaders): Observable<Object> {
    this.updateData();
    if (headers == null){
      headers = new HttpHeaders()
        .set('Accept', 'application/json')
        .set('Authorization', this.token);
    }
    return this.http.get(
      this.url + '/' + endpoint, {headers, params}
    )
  }

  /**
   * Return host data for given endpoint
   * @param {string} endpoint - endpoint of request, default is "host"
   * @returns {Observable<any>} - observable object
   */
  public getHosts(endpoint = 'host'): Observable<any> {
    let params = new HttpParams()
      .set('where', JSON.stringify({'_is_template': false}))
      .set('max_results', JSON.stringify(BACKEND_PAGINATION_LIMIT
    ));

    return this.get(endpoint, params)
  }
}
```

**Test:**

```typescript
import {TestBed, getTestBed} from '@angular/core/testing';
import {HttpHeaders, HttpParams} from "@angular/common/http";
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';

import {BackendClient} from "./client.service";

describe('BackendClient Service', () => {

  let injector: TestBed;
  let service: BackendClient;
  let httpMock: HttpTestingController;

  beforeEach(() => {

    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [BackendClient]
    });
    injector = getTestBed();
    localStorage.setItem('token', 'my-long-token');
    localStorage.setItem('url', 'http://demo.alignak.net:5000');
    service = injector.get(BackendClient);
    httpMock = injector.get(HttpTestingController);
  });

  afterEach(() => {
    httpMock.verify();
  });

  it('Get Hosts from Backend', () => {
    const dummyHosts = [
      {_items: 'Hosts list'}
    ];
    const dummyParams = new HttpParams()
      .append('where', JSON.stringify({'_is_template': false}))
      .append('max_results', JSON.stringify(25));

    service.getHosts().subscribe(
      hosts => {
        expect(hosts.length).toBe(1);
    });

    // ERROR HERE:
    // If I do the following, test complains about not found request but find the same request url name:
    const req = httpMock.expectOne(`${service.url}/host`);
    // FIX: So change to following code fixes issue:
    const req = httpMock.expectOne(req => req.method === 'GET' && req.url === `${service.url}/host`);
    expect(req.request.params.get('where')).toEqual('{"_is_template":false}');
    req.flush(dummyHosts);
  });
});
```

Only [the fix in comment](https://github.com/angular/angular/issues/19974#issuecomment-342827258) help me to solve this problem.
ERROR output:

```bash
Chrome 66.0.3359 (Linux 0.0.0) BackendClient Service Get Hosts from Backend FAILED
	Error: Expected one matching request for criteria "Match URL: http://demo.alignak.net:5000/host", found none.
	    at HttpClientTestingBackend.expectOne (webpack:///node_modules/@angular/common/esm5/http/testing.js:419:0 <- test-config/karma-test-shim.js:138937:19)
	    at UserContext.<anonymous> (webpack:///src/backend/client.service.spec.ts:88:25 <- test-config/karma-test-shim.js:138498:28)
	    at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:388:0 <- test-config/karma-test-shim.js:123739:26)
	    at ProxyZoneSpec.onInvoke (webpack:///node_modules/zone.js/dist/proxy.js:128:0 <- test-config/karma-test-shim.js:126726:39)
	    at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:387:0 <- test-config/karma-test-shim.js:123738:32)
	    at Zone.run (webpack:///node_modules/zone.js/dist/zone.js:138:0 <- test-config/karma-test-shim.js:123489:43)
	    at runInTestZone (webpack:///node_modules/zone.js/dist/jasmine-patch.js:145:0 <- test-config/karma-test-shim.js:126987:34)
	    at UserContext.<anonymous> (webpack:///node_modules/zone.js/dist/jasmine-patch.js:160:0 <- test-config/karma-test-shim.js:127002:20)
	    at <Jasmine>
	    at ZoneDelegate.invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:0 <- test-config/karma-test-shim.js:123772:31)
	    at Zone.runTask (webpack:///node_modules/zone.js/dist/zone.js:188:0 <- test-config/karma-test-shim.js:123539:47)
	    at drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:595:0 <- test-config/karma-test-shim.js:123946:35)
	    at run (webpack:///node_modules/core-js/modules/es6.promise.js:75:0 <- test-config/karma-test-shim.js:122284:22)
	    at webpack:///node_modules/core-js/modules/es6.promise.js:92:0 <- test-config/karma-test-shim.js:122301:30
	    at MutationObserver.flush (webpack:///node_modules/core-js/modules/_microtask.js:18:0 <- test-config/karma-test-shim.js:122519:9)
	Error: Expected no open requests, found 1: GET http://demo.alignak.net:5000/host
	    at HttpClientTestingBackend.verify (webpack:///node_modules/@angular/common/esm5/http/testing.js:477:0 <- test-config/karma-test-shim.js:138995:19)
	    at UserContext.<anonymous> (webpack:///src/backend/client.service.spec.ts:27:13 <- test-config/karma-test-shim.js:138450:18)
	    at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:388:0 <- test-config/karma-test-shim.js:123739:26)
	    at ProxyZoneSpec.onInvoke (webpack:///node_modules/zone.js/dist/proxy.js:128:0 <- test-config/karma-test-shim.js:126726:39)
	    at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:387:0 <- test-config/karma-test-shim.js:123738:32)
	    at Zone.run (webpack:///node_modules/zone.js/dist/zone.js:138:0 <- test-config/karma-test-shim.js:123489:43)
	    at runInTestZone (webpack:///node_modules/zone.js/dist/jasmine-patch.js:145:0 <- test-config/karma-test-shim.js:126987:34)
	    at UserContext.<anonymous> (webpack:///node_modules/zone.js/dist/jasmine-patch.js:160:0 <- test-config/karma-test-shim.js:127002:20)
	    at <Jasmine>
	    at ZoneDelegate.invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:0 <- test-config/karma-test-shim.js:123772:31)
	    at Zone.runTask (webpack:///node_modules/zone.js/dist/zone.js:188:0 <- test-config/karma-test-shim.js:123539:47)
	    at drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:595:0 <- test-config/karma-test-shim.js:123946:35)
	    at run (webpack:///node_modules/core-js/modules/es6.promise.js:75:0 <- test-config/karma-test-shim.js:122284:22)
	    at webpack:///node_modules/core-js/modules/es6.promise.js:92:0 <- test-config/karma-test-shim.js:122301:30
	    at MutationObserver.flush (webpack:///node_modules/core-js/modules/_microtask.js:18:0 <- test-config/karma-test-shim.js:122519:9)
```

**Comment by algorys** [comment]
Another solution works for me:

```typescript
// Obviously, adjust the format of your request url according to your API
let formatedURL = encodeURI(
      'http://my-full-uri/endpoint?foo=bar');
const req = httpMock.expectOne(
      req => req.urlWithParams === formatedURL);
```

**Comment by textbook** [comment]
@algorys the downside of the latter approach is that it is dependent on the order of query parameters being added to the URL, which I don't think is guaranteed if you're building the URL from a `params` object and probably shouldn't be relied on. Obviously if you only have one query parameter that isn't a problem, but it doesn't scale. That's why I suggested checking the URL _without_ query params, then validating those separately.

**Comment by JrPribs** [comment]
I have run into this issue when I have a typo in my expectation when using params. Should the HttpTestingController not indicate that a different url was call than expected, or am I causing it to throw the nondescript error because of my implementation? I was under the impression that `.verify()`  would let me know if the wrong url was called, am I mistaken?

**Comment by debender495** [comment]
let url = "bla?"+dummyParams;
const req = httpTestingController.expectOne(url);
expect(req.request.method).toEqual('GET');
expect(req.request.params.get('foo')).toEqual('bar');
expect(req.request.params.has('foo')).toBeTruthy();

**Comment by meta72** [comment]
@JrPribs this is the same problem I was having just now. I was already beginning to assume that `expectOne()` is buggy, but it's not. 

* `expectOne()` should also test `httpParams` as they might be important in some cases
* you can implement a simple matcher that matches `request.url` instead of `request.urlWithParams` if you don't care
* If you pass a URL without `httpParams` to `expectOne()` it can't print any params when no request matches. It doesn't know any params.
* most importantly: `verify()` should print `httpParams`. Reading `"No match found for https://my-url.com"` on the one hand and `"Open request found for https://my-url.com"` on the other hand is very confusing!

**Comment by tomastrajan** [comment]
Just encountered this too and yes, the error message is very confusing, looking forward to the fix! 👍👍👍

**Comment by Sebastian-G** [comment]
So the following case is currently not solved yet?

```
const requestMatch: RequestMatch = {url: environment.here.api.url, method: 'GET'};
const testRequest: TestRequest = httpMock.expectOne(requestMatch);
```
```
Error: Expected one matching request for criteria "Match method: GET, URL: https://autocomplete.geocoder.api.here.com/6.2/suggest.json", found none.
Error: Expected no open requests, found 1: GET https://autocomplete.geocoder.api.here.com/6.2/suggest.json
```

**Comment by marcellarius** [comment]
This behaviour is absolutely broken, undocumented and unexpected.

It's not just an issue with the HttpTestingController though; if you make a request with a querystring baked into the URL, the `params` object in the request doesn't get populated, and the `request.url` will not get populated. The issue there seems to be the HttpRequest constructor logic. Ideally the `params` should reflect the actual URL params, including any that were already in the `url` string.

My ideal expected behaviour would be to parse the expected URL, then ensure everything matches the request made -- any query string parameters specified in the test expectation would be compared against the actual URL; any not specified would be ignored.

As seems to be usual with Angular, these caveats are not mentioned anywhere in the documentation.

**Comment by marcellarius** [comment]
I wrote this pair of utility functions which should provide a more robust solution for testing requests with parameters:

```typescript
import { HttpParams, HttpRequest } from '@angular/common/http';

export function extractParams(url: string): HttpParams {
  let queryString: string;
  if (url) {
    const qIndex = url.indexOf('?');
    queryString = qIndex >= 0 ? url.slice(qIndex + 1) : '';
  } else {
    queryString = '';
  }

  return new HttpParams({fromString: queryString});
}


export function requestMatcher(match: {url?: string, method?: string, params?: HttpParams | {[key: string]: string | string[]}}): (HttpRequest) => boolean {
  const expectedParams = match.params && (match.params instanceof HttpParams ? match.params : new HttpParams({fromObject: match.params}));
  return (request: HttpRequest<any>) => {
    if (match.method && request.method !== match.method.toUpperCase()) {
      return false;
    }

    if (match.url && match.url !== match.url.split('?')[0]) {
      return false;
    }

    if (expectedParams) {
      const actualParams = extractParams(request.urlWithParams);
      const allExpectedParamsMatch = expectedParams.keys().every(key => {
        const expected = expectedParams.getAll(key);
        const actual = expectedParams.getAll(key);
        return expected && actual && expected.every(value => actual.includes(value));
      });

      if (!allExpectedParamsMatch) {
        return false;
      }
    }

    return true;
  };
}
```

```typescript
const request = httpTestingController.expectOne(requestMatcher({url: '/foo/bar', params: {'test', 'true'}}));

// This will give an HttpParams with all the params, not just the ones explicitly passed to HttpClient.request
const params = extractParams(request.request.urlWithParams);
```

YMMV, they helped me with my test cases.

**Comment by textbook** [comment]
@marcellarius this looks suspicious:

```ts
const expected = expectedParams.getAll(key);
const actual = expectedParams.getAll(key);
return expected && actual && expected.every(value => actual.includes(value));
```

`actualParams` isn't used there at all, `expected` and `actual` are the same array. You should re-review your tests (and the code they cover), they aren't telling you what you think they are.

**Comment by marcellarius** [comment]
Thanks! I've fixed the code snippet above. The value of code review, eh? 

I only needed the single value case for my tests, then figured I'd add checking for multiple values before posting here, but obviously I didn't test that well enough.

I've tightened up the comparison logic for the array check too, so the exact number and order of values must match.

**Comment by textbook** [comment]
@marcellarius the order doesn't (or *shouldn't*, see e.g. https://stackoverflow.com/q/10005335/3001761) matter at all; objects aren't ordered data structures, and `/foo?bar=1&baz=2` is the same as `/foo?baz=2&bar=1`.

**Comment by ruimarques** [comment]
This is quite annoying, just spent some hours until figuring this should be a bug in expectOne. And here it is.

@textbook work-around works fine, thank you.

**Comment by denis111** [comment]
I think something i broken here with toPromise() too. I have a service method which makes two requests and returns promise. For the first request it does (this.api.http is HttpClient):

```typescript
 const resp = await this.api.http
      .get(
        url,
        {
          observe: 'response',
          headers
        }
      ).toPromise();
```
After this line the test fails with that "found none" whether I use request params or not, just:
service.downloadFile('/any/url').then(res => {
      
    });
    const req = httpMock.expectOne('/any/url');

**Comment by textbook** [comment]
@denis111 it's not obvious to me how you think that relates to this issue. As you say, it's not about whether or not there are query parameters. Putting together a minimal example around the code you've posted, the test passes for me, so you'll need to provide something reproducible.

**Comment by denis111** [comment]
@textbook Yes, I also did a minimal example and it works, so I compared with real code and in real code I have another await before the request. So this test will fail with this code in a service, for example:

```typescript
const _ = await Promise.all([]); // just an example instead of real promise
 const resp = await this.api.http
      .get(
        url,
        {
          observe: 'response',
          headers
        }
      ).toPromise();
```

**Comment by IgnacioMaestro** [comment]
> 
> 
> I just came across the same problem. Fixing the error message would be one improvement, but in my view it would be even better if it matched against [`request.url`](https://angular.io/api/common/http/HttpRequest#url) rather than [`request.urlWithParams`](https://angular.io/api/common/http/HttpRequest#urlWithParams). I'd rather write:
> 
> ```
> const req = httpMock.expectOne({ method: 'GET', url: 'http://example.org' });
> expect(req.request.params.get('foo')).toEqual('bar');
> ```
> 
> than:
> 
> ```
> httpMock.expectOne({ method: 'GET', url: 'http://example.org?foo=bar' });
> ```
> 
> not least because it avoids any ordering issues when you have more than one parameter.
> 
> A current workaround is to use the request matcher function instead:
> 
> ```
> const req = httpMock
>     .expectOne(req => req.method === 'GET' && req.url === 'http://example.org');
> ```

I have tried to improve and clarify this solution. 
I have used as a parameter of the method expectOne an arrow function that always return true in order not to filter the requests by url. Afterwards I have checked the request properties and the query parameters sent.
This is my approach:
```
const testRequest: TestRequest = httpTestingController.expectOne((req) => true);
expect(testRequest.request.url).toEqual('http://example.org');
expect(testRequest.request.method).toEqual('GET');
expect(testRequest.request.params.get('param1') ).toEqual('param1Value');
expect(testRequest.request.params.get('param2') ).toEqual('param2Value');
```
I think that the function exepctOne could not receive any params and not check any url (it would be an easier code change) in order not to send a strange arrow function.
It could be like this:

```
const testRequest: TestRequest = httpTestingController.expectOne();
expect(testRequest.request.url).toEqual('http://example.org');
expect(testRequest.request.method).toEqual('GET');
expect(testRequest.request.params.get('param1') ).toEqual('param1Value');
expect(testRequest.request.params.get('param2') ).toEqual('param2Value');
```

**Comment by ajith4u81** [comment]
I came across the same problem. Solved by subscribing to the method first. As a result of calling the method, the open array in the HttpClientTestingBackend is updated

Afterward when httpTestingController.expectOne () is getting called, _match helper function, filter based on the match and it will be a success

      let formatedURL=encodeURI(http://example.org?foo=bar&query=xyz)

     service.getStuff().subscribe((retuenType: any) => {
      expect(retuenType).not.toBe(null);
      expect(JSON.stringify(retuenType)).toEqual(JSON.stringify(mockResponse));
    });

    const req =   ##httpTestingController.expectOne(formatedURL);
    [req.flush(response);](url)
 

![HttpClientTestingBackend](https://user-images.githubusercontent.com/24404050/116023115-e3105f80-a68e-11eb-9928-6428023b29b6.PNG)


Pathmatch method
![pathmatch](https://user-images.githubusercontent.com/24404050/116023160-f4f20280-a68e-11eb-8f36-08ffe2448d13.png)

**Comment by JoostK** [comment]
Hi folks, I've opened #44917 as a bug fix to improve the reported error.

I considered some designs to allow matching an URL without its query parameters, but this didn't work out as nicely as I'd hoped to be a viable alternative to using a closure-based matcher.
