### ISSUE TITLE
Ctrl+Click behaviour to open new tab does not work with RouterLink when component is projected within router-outlet

### ISSUE THREAD

**Issue by rahul-winner** [angular/angular#19987]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Ctrl+Click behaviour to open new tab is still not working when I used routerLink directive within a component which is being rendered within '<router-outlet>'

For example below code works fine and takes me to the #/jobs when I right click on hyperlink
```
<div>
  <app-navigation></app-navigation>
</div>
<div>
	<a routerLink="jobs">My Jobs</a>
</div>
<div>
  <router-outlet></router-outlet>
</div>
```

But below code does not work
```
<div>
  <app-navigation></app-navigation>
</div>
<div>
  <router-outlet></router-outlet>
</div>
```
There is a route to 'home.component.html' present within App Navigation component.

**home.component.html**
```
<div>
	<a routerLink="jobs">My Jobs</a>
</div>
```

I'm using Angular version 4.4.4

Could anyone please help me. 

## Expected behavior

User should be able to right click on a anchor tag and let it open in new tab/window and it should work as per routing.

## Browser:
All Browsers

## Others:
this looks relevant to https://github.com/angular/angular/issues/5908
However, I noticed that this issue is reproducible when component is present within router outlet.

**Comment by Toxicable** [comment]
Please create a minimal reproduction in plunkr or Stack blitz

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
