### ISSUE TITLE
Map files are being written for factories that are not emitted.

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#19986]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

The compiler will write a `.map` file for a factory file that was not emitted.

## Expected behavior

If a factory is not emitted is should not produce a map file.

## Minimal reproduction of the problem with instructions

In the angular sources and the aio directory, run `ngc -p src/tsconfig.app.json`.

Note that a map file was produced for `custom-md-icon-registry.ngfactory.js.map` but there was no file `custom-md-icon-registry.ngfactory.js` written.

## What is the motivation / use case for changing the behavior?

Parsimonious builds.

**Comment by JoostK** [comment]
Closing as obsolete.
