### ISSUE TITLE
[5.0.0-rc.7] Failed to load templateUrl path

### ISSUE THREAD

**Issue by aitboudad** [angular/angular#19994]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When targeting a template from the parent folder I have got the following error (ng serve):

![selection_103](https://user-images.githubusercontent.com/1753742/32127901-ed025770-bb71-11e7-861f-dba7215fb58e.png)

## Expected behavior

it should work

## Minimal reproduction of the problem with instructions

```ts
@Component({
    selector: 'app-ui-select',
    templateUrl: '../ui-select/ui-select.html',
})
export class UiSelect {}
```

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.6.0  
- Platform: Linux

- @angular/cli: 1.5.0-rc.4

**Comment by aitboudad** [comment]
also enabling AOT in dev mode is **really slow** and doesn't able to know the `paths` defined from `tsconfig.json`

**Comment by chuckjaz** [comment]
From a `ng new` I tried (after moving to 5.0.0-rc.7):

```
diff --git a/src/app/app.component.html b/src/app/app.component.html
index 46d517b..a3c0249 100644
--- a/src/app/app.component.html
+++ b/src/app/app.component.html
@@ -18,3 +18,5 @@
   </li>
 </ul>
 
+<app-ui-select></app-ui-select>
+
diff --git a/src/app/app.module.ts b/src/app/app.module.ts
index f657163..c44192b 100644
--- a/src/app/app.module.ts
+++ b/src/app/app.module.ts
@@ -1,11 +1,11 @@
 import { BrowserModule } from '@angular/platform-browser';
 import { NgModule } from '@angular/core';
-
+import { UiSelect } from './test/ui-select';
 import { AppComponent } from './app.component';
 
 @NgModule({
   declarations: [
-    AppComponent
+    AppComponent, UiSelect
   ],
   imports: [
     BrowserModule
diff --git a/src/app/test/ui-select.ts b/src/app/test/ui-select.ts
new file mode 100644
index 0000000..4003b81
--- /dev/null
+++ b/src/app/test/ui-select.ts
@@ -0,0 +1,7 @@
+import {Component} from '@angular/core';
+
+@Component({
+  selector: 'app-ui-select',
+  templateUrl: '../ui-select/ui-select.html',
+})
+export class UiSelect {}
diff --git a/src/app/ui-select/ui-select.html b/src/app/ui-select/ui-select.html
new file mode 100644
index 0000000..68fd764
--- /dev/null
+++ b/src/app/ui-select/ui-select.html
@@ -0,0 +1,5 @@
+<div> 
+
+  UI Select is HERE
+  
+</div>
```

and could not reproduce this. What am I missing?

**Comment by diicar** [comment]
Error 500 ?

**Comment by aitboudad** [comment]
seems related to angular/cli, it occurred when enabling `hmr` env, closing in favor of #8234
