### ISSUE TITLE
Allow option to suppress duplicate errors in angular -cli during AOT compile

### ISSUE THREAD

**Issue by abidmix** [angular/angular#19990]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.

C:\PMLCLI\Phoenix\Phoenix_LMS\Phoenix.Web>ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.4
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/upgrade: 4.4.6
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
typescript: 2.3.4

 Windows (10)

### Repro steps.

![image](https://user-images.githubusercontent.com/12702893/31790638-21cc9388-b4e4-11e7-903e-c99e7be08691.png)

### The log given by the failure.
Duplicate Identifier in component

### Desired functionality.
Allow me to suppress duplicate errors or let duplicate errors not affect the emitting of code in the dist folder. I do not see any duplicate identifier in my code and the ng.factory file is never outputted which leaves me with nothing to debug.

### Mention any other details that might be useful.
In my template I have code like this and I do not see why 'active' is marked as a  a duplicate identifier. This code works perfecttly fine in JIT.

`[ngClass]="{'active': math.Name == subjectVM.SelectedMathDomain,'active': math.Title == subjectVM.SelectedDomain}"` 

https://github.com/angular/angular-cli/issues/8119

**Comment by Toxicable** [comment]
This is a TS error
https://www.typescriptlang.org/play/#src=var%20math%3A%20any%3B%0D%0Avar%20subjectVM%3A%20any%3B%0D%0A%0D%0Avar%20styles%20%3D%20%7B%0D%0A%20%20%20%20'active'%3A%20math.Name%20%3D%3D%20subjectVM.SelectedMathDomain%2C%0D%0A%20%20%20%20'active'%3A%20math.Title%20%3D%3D%20subjectVM.SelectedDomain%0D%0A%7D

As you can see you cannot have 2 props on the same object literal with the same name.
change it to `{'active': (math.Name == subjectVM.SelectedMathDomain || math.Title == subjectVM.SelectedDomain)}`
