### ISSUE TITLE
routerLinkActive and it's options have inconsistent query handling when navigating imperatively - GIF included

### ISSUE THREAD

**Issue by jmarlow4** [angular/angular#19995]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When imperatively navigating:
<pre><code>this._router.navigate([`/${this._tenant.domain}/call-logs`], {
      queryParams: this.params
    });</code></pre>

activeRouterLink configurations on that route (call-logs) doesn't highlight in seemingly inconsistent ways.

here's the code for the routerLink
<pre><code>
a mat-button class="button"
        [routerLink]="[name]"
        [queryParamsHandling]="'preserve'"
        [routerLinkActiveOptions]="{exact: false}"
        routerLinkActive="selected"...
</code></pre>

observe the gif:
![searchroutelinkissue](https://user-images.githubusercontent.com/2195317/32128085-5e720f8e-bb38-11e7-8958-5e5602413a81.gif)

## Expected behavior

The link should keep the "selected" class no matter what the query params are, no matter how it's navigated, if I set the routerLinkActiveOptions to {exact: false}

## Environment
<pre><code>
Angular version: 4.4.4

Browser:
- [X] Chrome (desktop - Mac) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 </code></pre>

**Comment by jasonaden** [comment]
Reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

Please add a reproduction for this issue.

**Comment by jasonaden** [comment]
Closing this issue as no reproduction has been provided. If this is still a problem, please create a new issue.
