### ISSUE TITLE
View component is re-created when navigating away too soon after ParamMap callback.

### ISSUE THREAD

**Issue by bennadel** [angular/angular#19999]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If you have a View component (ie, a component rendered by the Router), and you navigate away from that View component during or directly-after an `activatedRoute.paramMap.subscribe()` callback, the Router (I assume) will destroy the View component as expected; but, then it will re-create the component immediately, run through its life-cycle, and destroy it again (well, the last part in my demo). _However_, it only does this if the route is changed based on:

* Vanilla HREF link.
* Hitting the back button.
* Manually editing the URL.

I _am guessing_ that this is some sort of race-condition in the `ActivatedRoute`.

## Expected behavior
The component should _not be re-created_ right after being destroyed.

## Minimal reproduction of the problem with instructions
* **Plunkr**: http://plnkr.co/edit/BxOabO1uUyWDbHmij1gX?p=preview
* **Blog Post**: https://www.bennadel.com/blog/3361-view-components-may-get-unnecessarily-reinstantiated-under-certain-circumstances-in-angular-4-4-6.htm

## What is the motivation / use case for changing the behavior?
It's clearly a bug; and, may cause unnecessary AJAX requests / calls to the server as the re-creation of the View component runs through the `ngOnInit()` life-cycle.

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) Version 61.0.3163.100 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Mac

Others:

</code></pre>

**Comment by bennadel** [comment]
I just tested my Plunkr in *Firefox* and it seems to work as expected. So, this is something related to *Chrome* perhaps.

**Comment by jasonaden** [comment]
@bennadel Thanks for the issue and the detailed reproduction (and blog post). I don't know of anything that should change this issue for `5.0.0`, but if you haven't tried already can you confirm it also exists there?

**Comment by JoostK** [comment]
I ported this case to [StackBlitz using 13.2.0](https://stackblitz.com/edit/angular-ivy-c8ce2o?file=src%2Fapp%2Fapp.module.ts) which appears to show the expected behavior now:

<img width="178" alt="image" src="https://user-images.githubusercontent.com/123679/170524644-9dc297a3-f3ab-4ad5-bfd2-ce05885fe7b6.png">
