### ISSUE TITLE
Failed to load resource when using Angular Http module in localhost

### ISSUE THREAD

**Issue by Juniuz** [angular/angular#20003]
Hi there,

I have encountered a 404 bad request when calling an API endpoint using Http.get method.  The application is running under http://localhost:56534.  Am I missing an important config that would enable angular application to run in localhost?

Below are the message spitted out in browser's console.
![badrequest](https://user-images.githubusercontent.com/4703222/32141001-f5837632-bcd8-11e7-8a9f-6bc572482eb1.PNG)

I also put up a post in [Stackoverflow](https://stackoverflow.com/questions/46996228/why-does-http-request-failed-to-load-resource-when-using-angular-4-in-localhost), the details of the project are laid out in there.

I'm quite new to Angular and, had no luck in bumping any article that will lead me to solve it?  Any help is greatly appreciated.

**Comment by mlc-mlapis** [comment]
@Juniuz ... as the error message says ... the problem is not the localhost:56534 but `%0A.......%20`.

**Comment by Juniuz** [comment]
@mlc-mlapis you are right, but how did that happen? I have explicitly use http.get('http://localhost:56534/api/MoC/GetStatuses') method like that.  Is there something wrong with my app.routing.ts?

**Comment by mlc-mlapis** [comment]
@Juniuz ... hmm `%0A%20%20%20%20` means new line and 4 spaces ... also 404 means `Not Found` on a server ... + your code samples ... I think that it is not related to Angular at all but related to your ASP.NET back-end.

**Comment by Juniuz** [comment]
@mlc-mlapis Okay, I did invoke this url 'http://localhost:56534/api/moc/GetStatuses' directly in my browser's address bar and test it also in Postman.  I get the json data correctly (screen capture below).

![statuses](https://user-images.githubusercontent.com/4703222/32141681-fc1beee0-bcea-11e7-89a6-d71bbdf5b860.PNG)
 
That's why I'm thinking the issue isn't on the back-end.  Any ideas?

**Comment by mlc-mlapis** [comment]
@Juniuz ... and what about CORS? Do you have a right config? Just test it from a standalone HTML page loaded from different port and vanilla XHR request to `http://localhost:56534/api/moc/GetStatuses` ... and you will see the result. Above direct access on URL is done without CORS in play so ...

**Comment by Juniuz** [comment]
@mlc-mlapis , I don't know about CORS?  what config are you referring to?

**Comment by mlc-mlapis** [comment]
@Juniuz ... google some info for ASP.NET first then. A config is a bit specific for each back-end platform so it is not possible to say general ... but it means the situation when you access REST API from a different host:port (from which an app is loaded) than host:port on which REST API is located.

**Comment by Juniuz** [comment]
@mlc-mlapis thanks for that explanation.  I get what you meant.  In my ASP.NET WebAPI config file, 
` // Web API routes
            config.MapHttpAttributeRoutes();

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{action}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );`

in routeTemplate, configured the route mapping structure for a web API call.  In my case, my app have the same host:port on which REST API is located.

**Comment by mlc-mlapis** [comment]
@Juniuz ... please double check ... ^^^ is OK but still not enough to check. The most important is if the URL which you are using to start your client app ... like `http://localhost:56534/index.html` has the same `http://localhost:56534` `host:port` as the REST API point ... `'http://localhost:56534/api/moc/GetStatuses`.

**Comment by Juniuz** [comment]
Upon further investigation, I believe this isn't related to Http service module nor routing.  Its something with systemjs.config.js loader.  Closed this issue.
