### ISSUE TITLE
using `NoopAnimationsModule` should produce a small bundle size

### ISSUE THREAD

**Issue by aitboudad** [angular/angular#20002]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The `@angular/animations` size is quite large ***100kb*** minified (62kb for animations + 40kb polyfill) even when disabling it by using `NoopAnimationsModule` (60kb).
Before `4.3` it was about 30kb.

## Expected behavior

at least I would like to have a small size when using `NoopAnimationsModule`.

**Comment by IgorMinar** [comment]
I believe that this will get resolved once we land #21576 and #22054

**Comment by trotyl** [comment]
Also, `NoopAnimationsModule` should not belong to `platform-browser` at all, a `noop` implementation shall always be platform-independent.

**Comment by IgorMinar** [comment]
This is still affecting Material as of v10.0.0-rc.0 where using the noop module still results in animations code being pulled into the bundle and increasing the bundle by ~50kb.

**Comment by Kamshak** [comment]
Could someone kindly check the labels again? A 56kb bundle size increase is more than just inconvenient, that's more than a react hello world app. You also get errors when libraries use animations and you don't include NoopAnimationsModule even if the main app doesn't use animations. Basically you can't opt out once a dependency has @ properties

**Comment by unnamed666** [comment]
Any news ? 
I'am trying so hard to drop main.js under 500kb and thats my last option for now i think. Including NoopAnimationsModule adds ~60kb to my main.js file - same as BrowserAnimationsModule.
Without both modules material components wont work but i thought that noop should add a lot less kb ?
Any workarounds to keep eg. material select withouth animation and have smaller bundle ?

**Comment by JeanMeche** [comment]
`Noop` animations doesn't necessary imply no animations at all. Noop still handles state transitions and requires almost the same code base as the fully fledged animations. 

If you'd like to reduce the eager bundle size of your app, we recommend you use the new `provideAnimationsAsync()` provider function introduced in v17.
