### ISSUE TITLE
Convert RequestArgs.body based on Content-Type

### ISSUE THREAD

**Issue by 9ae8sdf76** [angular/angular#20000]
## I'm submitting a...
<pre><code>
[x] Bug report
[x] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

In [Request.constructor()](https://github.com/angular/angular/blob/4.4.6/packages/http/src/static_request.ts#L96) the `requestOptions.body` is taken as-is, regardless of what the content type might actually be. If the `Content-Type` is not provided, `Request.constructor()` very smartly attempts to detect the content type. However, if a content type is provided that does not match the format of the `requestOptions.body` parameter, then naturally Angular cannot send the correct request.

For example:

    const options = new RequestOptionsArgs({headers: new Headers({'Content-Type': 'application/x-form-url-encoded'})});
    http.post('https://example.com/', {foo: 'bar'}, options).subscribe(...);

The above code would send the `Content-Type: application/x-form-url-encoded` with the body being `{'foo': 'bar'}` (essentially, the value returned by the object's toString()).  On the receiving end, in PHP for example, it would parse the post as:

    Array(
        "{'foo': 'bar'}" => ''
    );

No bueno. 

## Expected behavior

Since the `angular/packages/http/src/static_request.ts` already defines a few internal helpers (specifically, `detectContentType()` and `urlEncodeParams()` in the case of `application/x-form-url-encoded`), the solution is already there -- it just needs to be wired up.

## Minimal reproduction of the problem with instructions
The following plnkr demonstrates the current behavior, and how it's received on the server-side:
http://plnkr.co/edit/c4W5cjDgKg9gNdeyuCA3

## What is the motivation / use case for changing the behavior?

1. Consistency in the http API. I can pass an object to `http.get()` for the params, and the `Request.constructor()` does the right thing.
1. I stumbled on not setting the `Content-Type` by digging through the source code on github; it seems that there is a lot of folk out there who think that they have to set the content type to 'application/x-form-url-encoded` and manually process the data.

## Environment

<pre><code>
Angular version: 4.4.6 and master

Browser:
- [x ] Chrome (desktop) version 61.0.3163.100 (Official Build) (64-bit)
 
For Tooling issues:
- Node version: v8.7.0
- Platform:  macOS Sierra 10.12.6 (16G29)

Others:

</code></pre>

**Comment by sarunint** [comment]
Off topic: congratulations on getting the issue number 20000!

**Comment by sarunint** [comment]
Back on topic. I recommend migrating to `HttpClient` introduced in v4.3. It does automatic response parsing, and the API is pretty much the same.

By the way, `@angular/http` is deprecated in v5 and will be completely removed in v6.

**Comment by dohpaz42** [comment]
@sarunint Where is that documented? When I go to http://angular.io/, it's not immediately obvious, nor when I look in the code (I use code more than the website) does it suggest it's deprecated and will be removed. If there is another channel I should pay attention to for when to not use features, I genuinely would like to know.

**Comment by sarunint** [comment]
Oops, sorry if I removed my previous comment. It was my misunderstanding. I thought you ask about automatically parsing the *response*.

But I really recommend migrating to use `HttpClient`, which was introduced in v4.3, since `@angular/http` is going to be deprecated in v5 ([reference](https://next.angular.io/api/http/Http)), and is going to be removed completely in v6 according to Angular's deprecation policy.

The migration shouldn't be much of pain, since the API pretty similar. The most notable change is that you don't need to manually parse the response anymore. (That means mo more `res.json()`)

I'm not sure if this will help with your issue, but this is how `HttpClient` serialise the request body.

https://github.com/angular/angular/blob/7231f5e26a9d319730373ed6ea871d7d7eb2dc6c/packages/common/http/src/request.ts#L237-L259

**Comment by dohpaz42** [comment]
@sarunint Thank you for the reference! I had no idea about next.angular.io; that's awesome! 

As for `HttpClient`, it does not appear to address my issue. The `serializeBody` method, in my use case, would return a JSON string. Nothing in the constructor appears to look at the content type either.

So, I believe that this ticket would apply to `HttpClient` as well.

**Comment by alxhub** [comment]
Hello all!

For the deprecated `Http` I don't think we should do this, as features aren't being developed there.

For `HttpClient` I will consider this as a feature request.
