### ISSUE TITLE
Angular 4 Unhandled Promise rejection: Failed to load %0A%20%20%20%20%20%20%20%20%3Ch1%3EHello%20there%3C/h1%3E%0A%20%20%20%20

### ISSUE THREAD

**Issue by Juniuz** [angular/angular#20009]
I have an ASP.NET MVC project using Angular 4 for web components.  Before the application load successfully, but now I'm experiencing an unhandled exception thrown by zone.js api.onUnhandledError @ zone.js:690 (screen shots below)

![badrequest](https://user-images.githubusercontent.com/4703222/32149187-693e4a3e-bd65-11e7-9dae-d8d3db3669b3.PNG)

**zone.js** exception
![api onunhandlederror](https://user-images.githubusercontent.com/4703222/32149201-91f4da56-bd65-11e7-9fc1-f2c1f414288b.PNG)

**package.json**
`{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "build": "tsc -p src/",
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "serve": "lite-server -c=bs-config.json",
    "serve:e2e": "lite-server -c=bs-config.e2e.json",
    "prestart": "npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run serve\"",
    "pree2e": "npm run build:e2e",
    "e2e": "concurrently \"npm run serve:e2e\" \"npm run protractor\" --kill-others --success first",
    "preprotractor": "webdriver-manager update",
    "protractor": "protractor protractor.config.js",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~4.3.4",
    "@angular/compiler": "~4.3.4",
    "@angular/core": "~4.3.4",
    "@angular/forms": "~4.3.4",
    "@angular/http": "~4.3.4",
    "@angular/platform-browser": "~4.3.4",
    "@angular/platform-browser-dynamic": "~4.3.4",
    "@angular/router": "~4.3.4",

    "angular-in-memory-web-api": "~0.3.0",
    "systemjs": "0.19.40",
    "core-js": "^2.4.1",
    "rxjs": "5.0.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "concurrently": "^3.2.0",
    "lite-server": "^2.2.2",
    "typescript": "~2.1.0",

    "canonical-path": "0.0.2",
    "tslint": "^3.15.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",

    "@types/node": "^6.0.46",
    "@types/jasmine": "2.5.36"
  },
  "repository": {}
}
`

**systemjs.config.js**
`(function (global) {
    System.config({
        //baseURL: '/',
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
                //meta: {
                //    './*.js': {
                //        loader: 'systemjs-angular-loader.js'
                //    }
                //},
            },
            rxjs: {
                defaultExtension: 'js'
            }
        }
    });
})(this);
`

**app.component.ts**
`import { Component } from '@angular/core';

@Component({
    selector: 'moc-landing',
    template: `
        <h1>Hello there..</h1>
    `
    //templateUrl: './app/Components/home.component.html',
    //styleUrls: ['./app/Components/home.component.css']
})
export class AppComponent { }
`

**app.module.ts**
`
import { NgModule } from '@angular/core';
import { APP_BASE_HREF } from '@angular/common';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { routing } from './app.routing';
import { HomeComponent } from './Components/home.component';

@NgModule({
    imports: [BrowserModule, routing],
    declarations: [AppComponent, HomeComponent],
    providers: [{ provide: APP_BASE_HREF, useValue: '/' }],
    bootstrap: [AppComponent]
})
export class AppModule {}
`

**Index.cshtml**
`@{
    ViewBag.Title = "Landing Page";
}
<moc-landing></moc-landing>
`

I'm banging my head on the wall, before this is working, and I didn't update any of the config files (systemjs.config.js, packages.config, etc.)  What could go wrong? Please help.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by vanchisel** [comment]
It's interesting. I just had a similar issue as you did with **failed to load** and **localhost %20%20** _whatever_. A google search brought me to this post. Without any solution I decided to go back to the last component I created. Well, it turns out I had `templateUrl: ' '` which should have have been `template: '<ng-content></ng-content>'`.

So I hope this will help anyone. :-)
