### ISSUE TITLE
TypeScript-ify: router

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2001]

**Comment by naomiblack** [comment]
This cannot be started until `core` and `services` are done.

**Comment by btford** [comment]
Supposedly we are unblocked on this now. I want to work with @IgorMinar and @matsko on this as soon as our build-related work is in a good state.

**Comment by naomiblack** [comment]
Moving this to M10 since it doesn't look likely to land by Monday, given build work at higher priority.

**Comment by jeffbcross** [comment]
@matsko you haven't started on this, have you? I just chatted with @btford, and am planning to tackle it this afternoon.

**Comment by matsko** [comment]
@jeffbcross no I haven't started on it yet. You're welcome to take it over. I was planning on doing it on Monday with Brian.

**Comment by btford** [comment]
We should get this done ASAP so that I can return to #2165.

**Comment by matsko** [comment]
@btford do what you can with Jeff today. I won't be of much help since I haven't done the TS integration stuff yet and I'm not there in person with you today.
