### ISSUE TITLE
Loading third party library specific to component only.

### ISSUE THREAD

**Issue by rxysm** [angular/angular#20012]
To load third party libraries in component is easy but what if have a library like `https://apis.google.com/js/client.js` & have to use instance of that library after loading. I didn't find the best way in angular 4 to work with easily with specific components as per my R&D. So Can someone please look into that & let me know the thoughts & better approach for this.

## LIke I have to use after loading script...
<pre><code>
gapi.client.load('youtube', 'v3',<ANY CALLBACK>);
</code></pre>

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
