### ISSUE TITLE
docs(aio): typo in guide/architecture

### ISSUE THREAD

**Issue by theGivingTree** [angular/angular#20016]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

"The export of *AppComponent* is just to show how to export;"

## Expected behavior

"The export of *AppModule* is just to show how to export;"

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
`AppComponent` is actually correct. See [here][1] for more info. #20073 has improved the wording to avoid confusion.

[1]: https://github.com/angular/angular/pull/20073#pullrequestreview-73492075
