### ISSUE TITLE
View template is not refreshing when model values got changes in angular 4

### ISSUE THREAD

**Issue by RajendraPrasadP** [angular/angular#20015]
model values are appending every time in the template when modifying the model,
but when I print the model in the console it is giving the updated values only, in view previous model values and new values both are showing.
How can I fix this issue.
I am new to angular 4. Please help.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
