### ISSUE TITLE
*ngFor not working inconsistently with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by nicolae536** [angular/angular#20026]
## I'm submitting a bug for *ngFor with ChangeDetectionStrategy.OnPush

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I implemented a form which renders using a json configuration and I'm facing the current problem.
I maintain the layout which is the order of the elements in an array with objects and inside each array item I have a lines property which is a matrix.
I'm using 3 nested ` *ngFor` directives to render this layout in components, also using `ChangeDetectionStrategy.OnPush.`
I have the following case I want to create a new layout when the elements from this layout get updated.
I'm doing this because I can configure links between components and those links might change the layout.

1. First behavior when all dom nodes are rerendered on reference change
The current behavior I update all the references to arrays with new Array references.
All `*ngFor` directives re-render the dome under them. If I also mark the components which have `*ngFor` for change detection check.
If I don't mark the components but i change all the array references the dom is not updated until I click somewhere else on the screen.

2. Second problem onPush not detecting reference change
If I change as reference only the changed nodes and mark the components which contain the `*ngFor `directives for check the only the changed references are re-rendered. 
If I don't mark the components for check and I want to change only the references which are changed the dom is not updated until I click somewhere on the screen.

I don't change the inner elements from arrays as reference because I'm making sure that when I do this also a re-render needs to be done.
## Expected behavior

I would expect `OnPush `to behave consistently with` *ngFor.` When I change a reference in the array to rerender that node only when i change the array.length to re-render the changed references inside the array. Also I don't understand why do I need to mark for check the component which contains a` *ngFor` with an input which is changed as reference, I would expect the `ngFor `to rerender the array if the reference changed, right now I find it a little bit confusing.  

## Minimal reproduction of the problem with instructions

As reproduction I have this [repository ](https://github.com/nicolae536/ngt-configurable-form)which is public. i cannot add this in plunker is pretty big already and hard to write.
Steps to reproduce.
1. Clone the repo switch to the master branch
2. yarn install
3. yarn start
4. Go to file `src/lib/models/ngt-form-schema.ts`
5. Search for function `changeLayoutIfNeeded`
6. The code under this comment "TODO 1.Bug report for all domes rerendered when this reference changed" if is uncommented you will have the first described behavior.
6+.The line bellow "TODO 2.Bug report for why do I need to mark for check when i'm changing only references with OnPush" this comment works for now and rerendes the correct nodes but I don't understand why do I need to mark components which have `*ngFor` inside them for change detection.

## What is the motivation / use case for changing the behavior?

I building this component for a application which uses a lot of forms and i need a scaleable solution.
Also that application has 200+ components that's why I need to use OnPush strategy also I like to be as efficient as possible.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
Windows, 
Webstorm, 
node 6.9.6.
I'm using angular cli.
"@angular/animations": "~4.4.4",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "~4.4.4",
    "@angular/compiler": "~4.4.4",
    "@angular/core": "~4.4.4",
    "@angular/forms": "~4.4.4",
    "@angular/http": "~4.4.4",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "~4.4.4",
    "@angular/platform-browser-dynamic": "~4.4.4",
    "@angular/router": "~4.4.4",
    "@ngrx/store": "~4.1.0",
    "@ngrx/store-devtools": "^4.0.0",
    "core-js": "~2.4.1",
    "hammerjs": "~2.0.8",
    "reveal.js": "^3.5.0",
    "rxjs": "~5.4.2",
    "web-animations-js": "~2.3.1",
    "zone.js": "~0.8.14"
Others:

</code></pre>
Also i'm not sure if this is a bug, I think this is inconsistent on how it works now. Or maybe I don't understand that well how the change detection works and when he decides to re-render nodes.

**Comment by nicolae536** [comment]
I updated the repository, use master branch, I didn't notice that I'm locally on another branch

**Comment by jasonaden** [comment]
@nicolae536 This is a very large example to go through. I would like to see a much simpler reproduction as currently we would basically need to debug your code in order to find out what's wrong.

It sounds to me like the reference to the array might be changing, but the objects inside the array are not. But I can't tell from your description whether you're just expecting changes in the number of items, or changes to the values that are being bound to.

If you still feel there's a problem here, please create a reproduction specific to this problem and create a new issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

**Comment by divya130** [comment]
hi , can anyone help me with this??
ngFor does not update when array is updated
my scenario is 
<div ngFor = "d of arr">
arr gets updated
but arr1 doesnt gets update
<div ngFor = "e of d.arr1">

</div>
</div>
