### ISSUE TITLE
angular.io website can't be reached.

### ISSUE THREAD

**Issue by Oranji-Aka** [angular/angular#20025]
## I'm submitting a...

<pre><code>
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

angular.io website can't be reached.
worker-basic.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
    at worker-basic.min.js:1
    at <anonymous>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Working fine for me with Chrome Version 61.0.3163.100 (Official Build) (64-bit), and Firefox 56.0.2 (64-bit)

**Comment by Oranji-Aka** [comment]
situation back to normal, thank you
