### ISSUE TITLE
mouseover and mousedown events

### ISSUE THREAD

**Issue by fbcarpinato** [angular/angular#20020]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I am trying to bind in the same <td> element the mouseover and the mousedown events, but i noticed that the mousedown event doesn't gets triggered.

## Expected behavior
I expected to see both events triggering the component methods.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/ldabq29e2vK1ksntt3zT

## What is the motivation / use case for changing the behavior?
Trying to simulate a selection on the mouse click and over.

## Environment

<pre><code>
Angular version: 4.0

Browser:
- [x] Chrome (desktop) version  62.0.3202.75
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.5
- Platform:  Linux

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
The plnkr is throwing a lot of errors in the console. In any case, this is working fine for me  https://stackblitz.com/edit/angular-8ak8at?file=app%2Fapp.component.html

**Comment by mlc-mlapis** [comment]
@fbcarpinato ... read spec: https://www.w3schools.com/jsref/dom_obj_event.asp

**Comment by fbcarpinato** [comment]
I am doing the exact same thing, but the mouseover event gets fired multiple times and the mousedown never

**Comment by mlc-mlapis** [comment]
@fbcarpinato ... so, this one is working: https://plnkr.co/edit/wgrNkwOymWz1kyTQEzzF?p=preview

**Comment by fbcarpinato** [comment]
You were right, i found that i am creating the element inside a ngFor directive, and i think that this is the issue
