### ISSUE TITLE
Update contributing.md to mention email address requirements and CLA

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#20034]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, the doc Contributing to Angular does not discuss the email address that you use for the CLA and for submitting PRs (git commits). 

## Expected behavior

The section "Submitting a Pull Request (PR)" could be enhanced by adding some information about checking the email address associated with your Angular git commits. If there are any dependencies on (or relationship to) the email used for the CLA, those should also be mentioned. 

## Minimal reproduction of the problem with instructions

See https://github.com/angular/angular/blob/master/CONTRIBUTING.md

## What is the motivation / use case for changing the behavior?

If someone is only working in one github repo, this doesn't matter. If someone works in multiple github repos using the same identity, this doesn't matter. It does matter if they want to keep their Angular work and identity separate from other github repo work. If things aren't set up correctly, I also believe that attempts to submit PRs will fail indicating that the CLA has not been signed, when it was signed but under a different identity. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment]
This is not urgent. I'm fine with assiging this to @jabogart, to put in her backlog when she has a gap in other work. Not urgent, but I think it's an easy update to share what we learned. Minimally, encourage contributors to check the email used and refer them to github help for more information.

**Comment by jenniferfell** [comment]
I think this is part of the resolution: https://help.github.com/articles/setting-your-commit-email-address-in-git/

Users can set the email address for a single repo to be different from their github default and from other repos.

**Comment by jabogart** [comment]
... and here’s a good example of why this needs more clarity. You referenced me as @jabogart, which works and got me this email— but that is the git id I use for Adobe, and I got this message in my Adobe mail. Not ideal!

--jb

On Oct 30, 2017, at 12:28 PM, Jennifer Fell <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this is part of the resolution: https://help.github.com/articles/setting-your-commit-email-address-in-git/<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.github.com%2Farticles%2Fsetting-your-commit-email-address-in-git%2F&data=02%7C01%7C%7C8d09f247463a488b4b4708d51fcc6fc6%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C636449885273112759&sdata=jlgJlYc1VsZW9tYYVeXPVuAW%2BA9e9JXD9X%2FbqHvrTMw%3D&reserved=0>

Users can set the email address for a single repo to be different from their github default and from other repos.

**Comment by jenniferfell** [comment]
@gkalpak Can you reassign this to @jbogarthyde. Thanks! (Or if you can't, please let me know who can. Sorry to be an inconvenience and have gotten this wrong before.)

**Comment by gkalpak** [comment]
@jenniferfell: @jabogarthyde can't be assigned, because she is not a member of the angular organization. I think @juleskremer (among others) can invite her to join the org.

**Comment by jenniferfell** [comment]
Some other links that might be helpful for anyone with more than one github identity who is contributing to Angular. Sharing here so we have them handy when we update the Contributing doc. 
https://stackoverflow.com/questions/37245303/what-does-usera-committed-with-userb-13-days-ago-on-github-mean
https://help.github.com/articles/setting-your-commit-email-address-in-git/
https://help.github.com/articles/about-commit-email-addresses/
https://help.github.com/articles/blocking-command-line-pushes-that-expose-your-personal-email-address/

**Comment by jbogarthyde** [comment]
Created PR #21754 with proposed fix.
