### ISSUE TITLE
feature request(docs): migrate plunkr examples to StackBlitz

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#20045]
Since the docs are moving to use the CLI as per #19510 it would make it easier for people learning Angular to see examples in Stack Blitz.
Due to it's UI being similar to VSC it, since Stack Blitz uses the CLI to handle bundling and it's auto-completion / TS support it would make the transition from browser to local projects much easier.

**Comment by gkalpak** [comment]
Right! Fixed in #20165.
