### ISSUE TITLE
Please provide docker image for angular-cli,angular-material and angular-firebase

### ISSUE THREAD

**Issue by gagandeep531** [angular/angular#20048]
## I'm submitting a...

<pre><code>
[ ] Feature request
</code></pre>

## Current behavior

I am trying to build a docker image for angular 4 application using angular cli and angular-material but ng build command cannot recognize the same.

## Expected behavior

There should be official docker image on hub.docker.com so that angular app and easily be containerized for deployment

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
Thanks for the request. However, this isn't something we're looking at supporting at this time. But it's certainly something that the community could create and put out. If you were to do so, speak to our Developer Relations team so they are aware of it.
