### ISSUE TITLE
5.0.0 cannot be bundled with current version of Closure Compiler

### ISSUE THREAD

**Issue by steveblue** [angular/angular#20044]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Closure Compiler cannot interpret @angular packages in 5.0.0. The only working solution is based off a fork by @gregmagolan that was rejected in a PR by the Closure Compiler team. There is no published solution for writing a closure .conf that is compatible with the latest version of Closure Compiler, but it is possible with Greg's fork and 5.0.0 with a bunch of monkeying around with closure conf. 

## Expected behavior

Angular packages are interpretable by Closure Compiler. In 4.x @angular can be bundled with Closure Compiler and .conf can be formatted to lazyload Angular bundles. The expectation is that same can be done with Angular 5.x. We should not have to rely on a fork of Closure Compiler to make this happen. 

## Minimal reproduction of the problem with instructions
Look at Alex Eagle's demo repo. It relies on the fork.

## What is the motivation / use case for changing the behavior?
At my company, using the fork would violate our open source software policy that has to include an acceptable license at a specific version. Besides, this is just good practice. 

## Environment

<pre><code>
Angular version: 5.0.0-rc.x, any RC.

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.0
- Platform:  Mac OS

Others:

</code></pre>

**Comment by jasonaden** [comment]
@alexeagle We should look at how to get this fixed. We should have gotten that done before `5.0.0` came out unfortunately.

**Comment by alexeagle** [comment]
@thelgevold says he has gotten this working, and might send a PR against angular/closure-demo indicating what needs to be changed to work with the released closure compiler.

**Comment by steveblue** [comment]
Does this mean we can deprecate @gregmagolan 's fork and `--package_json_entry_names es2015` @thelgevold ? it would be awesome to see how to do it.

**Comment by thelgevold** [comment]
@alexeagle @steveblue I have made a PR with an upgrade here: https://github.com/angular/closure-demo/pull/27

**Comment by thelgevold** [comment]
Depending on your app, you may need to add externs for some of the globals in Angular as well,

Example:

```
/**
* @fileoverview This is an externs file.
* @externs
*/

var System;
var Hammer;
var global;
var COMPILED;
```

I am thinking this extern definition should eventually be added to the Angular source?

**Comment by steveblue** [comment]
Yeah @thelgevold thats the point I was trying to make. `COMPILED` should probably be added to the Angular source and not required extern by another app. I get the others, except always wondered where `global` comes from.

**Comment by steveblue** [comment]
Thanks to everyone who made this happen! Closing.

```
[20:35:10] LOG @angular/compiler started  
[20:35:12] LOG @angular/compiler compiled ngfactory   
[20:35:15] LOG closure compiler started  
[20:35:32] LOG compiled manifest   
[20:35:32] LOG optimizing bundles for production   
[20:35:38] LOG closure compiler optimized project bundles   
[20:35:38] LOG Build is ready   
```
