### ISSUE TITLE
Error when trying to serve project

### ISSUE THREAD

**Issue by tomavic** [angular/angular#20059]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

 I got an error when trying to serve my Ionic project, This is random issue I found it many times
<pre><code>
ERROR TypeError: Cannot read property 'length' of null at HttpHeaders.applyUpdate (http.es5.js:481)
</code></pre>

Actually this happens whentry to use
 ``` { provide: HTTP_INTERCEPTORS, useClass: MyInterceptor, multi: true }, ``` 
in my app.module.ts

when I comment it the error disappers

P.S It was working before it's just today I found that!
## Expected behavior

It should run normally as any ionic project

## Environment

<pre><code>
Angular version: latest

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alxhub** [comment]
Can you give me a reproduction, @tomavic?

**Comment by tomavic** [comment]
Hi @alxhub 

Could you explain?

**Comment by tomavic** [comment]
@alxhub Hi Alex any updates on this?
I am getting in my console : 
Cannot read property 'length' of null at HttpHeaders.applyUpdate (vendor.js:54210)

I checked #18743 and it may be caused because value passed to header.set() is not string


Here is code snippet:

```
    let token = localStorage.getItem('authToken') || "";
    let loginInfo = this.localUser.getInfoForHeader() || "";

    const authReq = req.clone({    
      headers: req.headers.set('X-Auth-Token', token).append('X-Login-Info', loginInfo)               
    });
```

Calues of Token and Login Info headers are empty till user logs in,
The question now is : How can I update values of headers after app initialization ?

**Comment by tomavic** [comment]
@alxhub please check this part of Angular docs

https://angular.io/guide/http#setting-new-headers

I am trying to do the same exactly, and I am getting my headers values from other service, which it depends on user if he logged in or not

It seems that values of headers are not updated, and may be this what causes the problem !!

I don't know, could you check this?
