### ISSUE TITLE
@angular/compiler-cli 5.0.0-rc.x ignoring class field initializations

### ISSUE THREAD

**Issue by udos86** [angular/angular#20053]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Maybe I am missing something really crucial here but to me it seems that `@angular/compiler-cli@5.0.0-rc.x` totally disregards class field initializations.

Given a simple dummy class that defines and initializes some `config` property:
```
export class DummyClass {

    config: object  = {};

    constructor () {}
} 
```

When being transpiled with stable `@angular/compiler-cli@4.4.6` JavaScript output is generated as expected:
```
var DummyClass = /** @class */ (function () {
    function DummyClass() {
        this.config = {};
    }
    return DummyClass;
}());
```

However when using latest `@angular/compiler-cli@5.0.0-rc.x` the class field gets completely removed from the transpiled JavaScript code:
```
var DummyClass = /** @class */ (function () {
    function DummyClass() {
    }
    return DummyClass;
}());
```

## Expected behavior

Class field initializations should not be ignored

## Environment

<pre><code>
Angular version: 5.0.0-rc.9

TypeScript version: 2.5.3

TypeScript configuration:
{
  "compilerOptions": {
    "baseUrl": "../",
    "paths": {
      "@ng-dynamic-forms/*": [
        "dist/@ng-dynamic-forms/*"
      ]
    },
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2015",
      "dom"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "outDir": "../dist/@ng-dynamic-forms",
    "removeComments": false,
    "rootDir": ".",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [],
    "types": []
  }
  "files": [
    "./public_api.ts"
  ],
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "flatModuleId": "@ng-dynamic-forms/core",
    "flatModuleOutFile": "core.js",
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true
  }
}

</code></pre>

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/issues/19587, do not use TypeScript 2.5 for now.

**Comment by udos86** [comment]
@trotyl Alright, thank you very much!
