### ISSUE TITLE
Language Service can't find component from local module imported with forRoot

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#20050]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When local module imported with `forRoot` Language Service can't recognize components from it and throws error: `ng: 'lib-component' is not a known element: ...`.

## Expected behavior

LS should be able to correctly find components form modules imported with `forRoot`.

## Minimal reproduction of the problem with instructions

Folder structure:
```
root
- lib
  - lib.module.ts
- src
  - app
    - root
      - app.component.ts
    - app.module.ts
```

Shared module:
```ts
@NgModule({
              declarations: [ LibComponent ],
              exports: [ LibComponent ],
          })
export class LibModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: this,
            providers: [ ],
        };
    }
}
```

AppModule:
```ts
@NgModule({
              imports: [
                  BrowserModule,

                  LibModule.forRoot(),
              ],
              declarations: [ AppComponent ],
              bootstrap: [ AppComponent ],
          })
export class AppModule { }
```

`AppComponent`'s template:
```html
<h1>
    {{title}}
</h1>
<lib-component></lib-component> <-- error is shown here
```

You can find a repo [here](https://github.com/WiseBird/angular_ls_for_root).

## Environment

<pre><code>
Angular version: 4.4.6 or 5.0.0-rc.9

 
For Tooling issues:
- Node version: 7.6.0  
- Platform:  Linux computer 4.4.0-21-generic

Others:

IDE: WS-173.3415.27
</code></pre>

**Comment by WiseBird** [comment]
Found a cause: I used `this` for `ngModule` property. Apparently tsc wrapper's evaluator doesn't support this.

@chuckjaz how do you think, whats better: to close this issue or to turn it into feature request to support such syntax (it actually convenient and more copy-past friendly)?

**Comment by schippie** [comment]
@WiseBird I don't think this issues should be closed since I've noticed it also happens when you use the name of the NgModule typescript class. In both instances it is unable to resolve the components when they are provided using a static method that returns a `ModuleWithProviders`

**Comment by joeflateau** [comment]
Still appears to be broken in language service 8. I'm working around by importing the module twice, first by class then by forRoot:


```
imports: [MyModule, MyModule.forRoot()]
```

**Comment by hamfastgamgee** [comment]
Definitely is still happening in 10.1.  We have a local shared library, and this issue confused the heck out of me for an hour in a new tiny app (only one page) we're doing that was importing that shared library through forRoot().  Our flagship apps have a SharedModule layer that is importing the shared library without forRoot() and then AppModule imports forRoot(), so we didn't see the behaivor there.  I ended up doing a conditional import without forRoot() in dev builds only and an import with forRoot() in all builds, but I'm honestly not sure that's "better" than just importing the shared library without forRoot() all the time like in the workaround from the previous comment.

**Comment by JoostK** [comment]
I can't reproduce using the View Engine-based language service, and this class of issues is eliminated in the new Ivy language service now that's driven by the compiler directly.
