### ISSUE TITLE
TypeScript-ify: angular2_material

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2005]
- [ ] code
- [ ] examples

This cannot be started until `core` (#1997), `services` (#2002) , `directives` (#1998) and `forms`(#1999) are done.

**Comment by naomiblack** [comment]
dialog is still outstanding. everything else is done. blocked by https://github.com/angular/angular/issues/2127

**Comment by jelbourn** [comment]
Done via 0f3a8f369af447e52c686fe09435c8ca14e8e19c and c8947d77bf2125b44f8501788318e7eeb1043de7
