### ISSUE TITLE
Allow guards and redirect in Route object

### ISSUE THREAD

**Issue by Assafz1983** [angular/angular#20056]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When you define a route to register to the routerModule, you may configure a guard.
However, when you configure this route to the redirect - the guard is ignored.

## Expected behavior
I guess it has a good reason, but maybe it should be considered to allow guards to redirect routes since I find this very useful.

## What is the motivation / use case for changing the behavior?
For example - I have a SSO login option. The way my SSO provider works, is to send the login token to a pre-configured URL, that I can 'catch' in my router. It has the same URL for success login and to ERROR, so I would like a guard to go back to login page when it is an error, or redirect to the main page (after saving the token) when it is success.

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2
- Platform:  Mac (however, irrelevant)

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

I realize this is a feature request, but it sounds like you can produce an example of what you're currently doing, then show what you would like changed with the new behavior.
