### ISSUE TITLE
Angular does not work with `module: "system"` (5.0 AOT - No dependencies/imports in *.ngfactory.js files)

### ISSUE THREAD

**Issue by marcinpiekarski** [angular/angular#20057]
## I'm submitting a...

<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After compiling with ngc, ngfactory.js files don't have declared dependencies/imports (I belive so), there are only multiple commas after *var* keyword. Also setters look like not properly generated.

I've noticed that new compiler generates ngfactory.js files for modules as well (before upgrade there had been only ngfactory.TS files for modules [Angular 4.4.6])

**Generated contact-information.component.ngfactory.js**
```
 var , , , styles_ContactInformationComponent, RenderType_ContactInformationComponent, ContactInformationComponentNgFactory;
    return {
        setters: [
            function (_1) {
                 = _1;
            },
            function (_2) {
                 = _2;
            },
            function (_3) {
                 = _3;
            }
        ],
```

## Expected behavior
ngfactory.js files should contain proper imports/deps.

**Generated contact-information.component.ngfactory.js**
```
var i0, i1, i2, styles_ContactInformationComponent, RenderType_ContactInformationComponent, ContactInformationComponentNgFactory;
    return {
        setters: [
            function (i0_1) {
                i0 = i0_1;
            },
            function (i1_1) {
                i1 = i1_1;
            },
            function (i2_1) {
                i2 = i2_1;
            }
        ],
```

## Minimal reproduction of the problem with instructions

To compile application I simply use the following function in gulp:
```
const {main: ngc} = require('@angular/compiler-cli/src/main');

function compileApplication() {
                log('compiling with ngc');

                const args = [
                    '-p', `${dir}/tsconfig.json`,
                    '-locale', lang
                ];

                return ngc(args);
            }
```

**tsconfig.json**
```
{
  "files": [
    "auth-app/auth.ts",
    "auth-app/auth-aot.ts"
  ],
  "include": [
    "shared/app/declarations.d.ts"
  ],
  "compilerOptions": {
    "rootDir": ".",
    "module": "system",
    "target": "es5",
    "lib": [
      "es6",
      "dom"
    ],
    "inlineSourceMap": true,
    "inlineSources": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": false,
    "importHelpers": true,
    "baseUrl": ".",
    "paths": {
      "shared/*": [
        "shared/*"
      ]
    },
    "types": []
  },
  "angularCompilerOptions": {
    "genDir": ".",
    "skipMetadataEmit": true
  }
}
```

## Environment
Angular version: 5.0.0rc-9
 
For Tooling issues:
- Node version: 6.11.3 
- Platform:  Windows

Others:
package manager: npm (3.10.10)

**Comment by tbosch** [comment]
Hello,
sorry, but that is not enough information to reproduce. Could you create a branch on Github so we can investigate?
Also, which TypeScript version are you using?

**Comment by tbosch** [comment]
Oh, I think we don't support `"module": "system",`. Could you try with `module: "commonjs"` or `module: "es2015"`?

**Comment by tbosch** [comment]
Verified that this happens all the time when using `module: "system"`.

**Comment by tbosch** [comment]
This is actually a bug in TypeScript, see https://github.com/Microsoft/TypeScript/issues/19618

**Comment by tbosch** [comment]
As SystemJS does support commonjs as inpurt, the workaround is to use `module: "commonjs"`.

**Comment by marcinpiekarski** [comment]
Before upgrading Angular 4.4.6 to 5.0rc9 I was using typescript 2.5.3, but compiler-cli requires typescript 2.4.2-2.5 so I downgraded to 2.4.2 version.

With Angular 4.4.6 and TS 2.5.3 everything is ok, but with 5.0rc-9 and TS 2.4.2 I get this issue (the same tsconfig). 

I will try your solution on Monday because now I'm on holiday without access to the project repository.

Thanks anyway for the tip. I really appreciate your help.

**Comment by marcinpiekarski** [comment]
changing module to commonjs in tsconfig solved the problem :)

Thanks once again :)
