### ISSUE TITLE
Confusing property highlight in the description of Reactive forms - More FormControls section.

### ISSUE THREAD

**Issue by gr4vitonn** [angular/angular#20058]
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request

## Current behavior

In [(reactive forms)](https://angular.io/guide/reactive-forms#more-formcontrols) page, More FormControls section you can find the following description:

> Reminder: Ignore the many mentions of form-group, form-control, center-block, and checkbox in this markup. Those are bootstrap CSS classes that Angular itself ignores. Pay attention to the formGroupName and formControlName attributes. They are the Angular directives that bind the HTML controls to the Angular FormGroup and FormControl properties in the component class.

## Expected behavior

In the mentioned description the `formGroupName ` should be replaced to `[formGroup]` according to the provided example.

## What is the motivation / use case for changing the behavior?

To clarify the provided description.

**Comment by jenniferfell** [comment]
@kara @kapunahelewong Can you assess and confirm, please? Thanks.

**Comment by kapunahelewong** [comment]
Thank you for this @gr4vitonn. I'm closing this as the PR for the fix was merged. If you have any outstanding questions, please feel free to tag me. Thanks!

**Comment by gr4vitonn** [comment]
Thank you @kapunahelewong for the proper issue handling.

**Comment by kapunahelewong** [comment]
Aw, thank you @gr4vitonn. That means a lot.
