### ISSUE TITLE
Async validator gets called many times when using formGroup directive

### ISSUE THREAD

**Issue by dzonatan** [angular/angular#20052]
## I'm submitting a...
<pre><code>[X] Bug report</code></pre>

## Current behavior
When building dynamic forms in the way [it's documented](https://angular.io/guide/dynamic-form) the async validator of specific control gets called as many times as there are `[formGroup]` directive usages. That's happening because each `[formGroup]` binding triggers tree validation update.
https://github.com/angular/angular/blob/3a8665409d92cf8b970873ef09a127e01e3f353f/packages/forms/src/directives/reactive_directives/form_group_directive.ts#L161

## Expected behavior
Not sure how it should be solved but current approach of building dynamic forms as described in docs isn't that good when having some async validators. Most often async validators are network related so they could have a huge impact on performance.

## Minimal reproduction of the problem with instructions
https://embed.plnkr.co/f6mQwCavntShsG04NJHX 
Open the console and reload the preview. You should see ~6 `validating...` console prints. It increases with every new question added to `question.service.ts`. Think about more complex form with ~20 fields.

Plunker was taken from https://angular.io/guide/dynamic-form and just added async validator to `question-control.service.ts`. Nothing more was changed.

**Comment by jhourlad** [comment]
Actually, this also happens with FormControl and validator is being called with each keyboard event.

**Comment by kara** [comment]
Looks like same core problem as https://github.com/angular/angular/issues/20052

**Comment by dzonatan** [comment]
@kara you have referenced to this issue.

**Comment by jhourlad** [comment]
Just adding note that Angular's workaround for this is to use `updateOn: blur|submit`. Only thing I noticed is that the data update comes really late if doing `updateOn: submit` inside a `submit` form event (sounds redundant, huh?)

**Comment by guillep2k** [comment]
This bug is somehow being addressed at #21500 .

**Comment by dzonatan** [comment]
@kara was this issue closed by mistake?

**Comment by alexluecke** [comment]
![](https://media.giphy.com/media/kgMxiqygP3IAXfSEKl/giphy.gif)
