### ISSUE TITLE
Prod build FontAwesome font not found 

### ISSUE THREAD

**Issue by suresh2018** [angular/angular#20068]
localhost working fine ,But Prod and dev build FontAwesome font not found . im using ng 5 rc 9 & clic rc.3.

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
