### ISSUE TITLE
Tests appear to run multiple times

### ISSUE THREAD

**Issue by jscharett** [angular/angular#20060]
## I'm submitting a...
[X ] Bug report

## Current behavior
When running tests in Chrome, the tests appear to run multiple times.  The number of tests run appears to be correct, however, putting in console statements show multiple logs.  When running test in the Chrome browser, the console statements only show once in the browser, however show multiple times in the cli window.  Running ChromeHeadless shows multiple log statements in the output even though there is only 1 log in the it/describe.

## Expected behavior
Tests run only once.

## Minimal reproduction of the problem with instructions
run ng test or ng test --cc

## What is the motivation / use case for changing the behavior?
Console output should only show correctly.  Tests should only run once.  I can't tell if the tests are actually running multiple times or if its simply a reporting issue.

## Environment
@angular/cli: 1.4.9
node: 6.9.3
os: win32 x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.5.3

**Comment by jscharett** [comment]
Adding a global counter like `window.i++` shows that i only increments once, though its output multiple times in the console.  Guessing its a reporting issue?

**Comment by jasonaden** [comment]
@jscharett Please try this with the current version of the CLI (`1.5.0`). If the issue persists, please file against the CLI project [angular/angular-cli](https://github.com/angular/angular-cli).

**Comment by jscharett** [comment]
My apologies.  I don't know why I filed here and not the cli.  Will check 1.5.0.  Thanks
