### ISSUE TITLE
TypeScript-ify: benchmarks

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2006]
- [ ] change_detection
- [ ] compiler
- [ ] costs
- [ ] di
- [ ] element_injector
- [ ] largetable
- [ ] naive_infinite_scroll
- [ ] tree

**Comment by naomiblack** [comment]
This cannot be started until `core` (#1997), `services` (#2002) , `directives` (#1998) and `forms`(#1999) are done.

**Comment by jeffbcross** [comment]
This is done, and @ttowncompiled has opened a new issue for the next milestone (10) to ts-ify benchmarks external
