### ISSUE TITLE
Changing baseHref in Angular along with the Upgrade Module to work with AngularJS router causes infinite redirect

### ISSUE THREAD

**Issue by zbuhler** [angular/angular#20061]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If using the Angular router and the AngularJS router together with the Upgrade Module you can define routes that each router will handle and the other router will, since the route is not defined, go to its sink state and not populate the router-outlet or ng-view respectively. This works great except for if you want to host your app anywhere but root. As soon as you define a baseHref things will go haywire and you get in a (seemingly) infinite redirect between the two frameworks. _(For more information on the project set-up you can visit Victor Savkin's [tutorial](https://blog.nrwl.io/using-ngupgrade-like-a-pro-lazy-loading-angularjs-applications-469819f5c86))_.

## Expected behavior
You should be able to define a baseHref and have the two routers still play nice with each other just like they do when hosted at root.

## Minimal reproduction of the problem with instructions

Detailed steps along with some things I've tried to fix the problem are on [StackOverflow](https://stackoverflow.com/questions/46899392/changing-basehref-in-angular-along-with-the-upgrade-module-to-work-with-angularj) but to summarize:

* Clone the [repo](https://github.com/zbuhler/ngUpgradeBaseHref) _(bare bones Angular-CLI project demonstrating the issue. I would have used plunker but SystemJS appears to rely on the ```<base>``` tag which makes it so I can't demonstrate the problem)_
 * ```npm install```
 * ```ng serve```
 * Navigate to [http://localhost:4200](http://localhost:4200)
 * View it working normally by clicking back and forth on any of the links.
 * Change the .angular-cli.json file like so adding a baseHref-
```
"defaults": {
"styleExt": "css",
"component": {
},
"build": {
  "baseHref": "/"
}
```
to
```
"defaults": {
"styleExt": "css",
"component": {
},
"build": {
  "baseHref": "/sub/"
}
```
 * See it break when clicking on any of the two AngularJS links (navigate from Angular to an AngularJS page)

## What is the motivation / use case for changing the behavior?

Not everyone's app is hosted at root and you should be able to use routing along with the Upgrade Module whether it is or not.

## Environment

<pre><code>
Angular version: 4.4.6 (using CLI Project)

Browser:
- [X] Chrome (desktop) version 61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 55.0
- [X] Safari (desktop) version 11.0
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

To aid in debugging I have enableTracing: true in the app module and some console.log statements in AngularJS for the $locationChangeStart and $locationChangeSuccess events so you can see the order of events regarding navigation.

**Comment by zbuhler** [comment]
Thanks for the pull request! The logic on this is pretty sound but there is a problem with the commit as is. If pulled in as is you will still get the infinite redirect.

Until the url.href is set (like it is on ```url.href = next;```) ```url.protocol``` and ```url.host``` will not be set properly (":" and "" respectively). The logic for setting the baseHref most likely needs to be put in the ```$locationChangeStart``` **AFTER** the ```url.href = next;```.

**Comment by jahumes** [comment]
Thanks! I will resubmit a fix for this.

**Comment by jahumes** [comment]
I have submitted a fix for the issues listed. Please recheck to see if this fixes this bug.

**Comment by BBlackwo** [comment]
Any update on this?
