### ISSUE TITLE
ContentChildren "descendants" documentation is unclear

### ISSUE THREAD

**Issue by aciccarello** [angular/angular#20074]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The current description of the [ContentChildren](https://angular.io/api/core/ContentChildren) metadata properties gives the following description for the `descendants` property:

> descendants - include only direct children or all descendants.

While this describes what it does, it is unclear which strategy is used on `descendents: true`

## Expected behavior

The documentation should say that setting `descendents` to true includes all descendants.

I know this is small but took a bit of digging around the example to figure out. I'd be willing to submit a PR.

**Comment by kapunahelewong** [comment]
@aciccarello Thanks for bringing this up. We'd love a PR. Would you please tag me in it and I'll review it?

**Comment by pkozlowski-opensource** [comment]
For anyone looking at this issue / working on a doc - the actual behaviour / governing rules are quite subtle, please see https://github.com/angular/angular/issues/14769#issuecomment-356609267

Also, any documentation update should contain mention from https://github.com/angular/angular/issues/13002#issuecomment-263981202

**Comment by pkozlowski-opensource** [comment]
@kapunahelewong actually, after discussing this some more with @mhevery we want to change the current behaviour, as it is just too confusing. A new proposal is here: https://github.com/angular/angular/issues/14769#issuecomment-356901874

Given the above we should hold off any work on documentation till #14769 is resolved - otherwise we would be documenting a "moving target"

**Comment by kapunahelewong** [comment]
@jenniferfell fyi^^

**Comment by pkozlowski-opensource** [comment]
@kapunahelewong with the ivy out I believe that, finally, we are ready to properly document this one! The broad-strokes description is here: https://github.com/angular/angular/issues/14769#issuecomment-356901874

Don't hesitate to ping me when you (or anyone else) starts to work on this and more info is needed.

**Comment by kapunahelewong** [comment]
Thank you very much, @pkozlowski-opensource!!

**Comment by ajitsinghkaler** [comment]
@kapunahelewong @pkozlowski-opensource I'm thinking of starting on it can you please detail this out

**Comment by pkozlowski-opensource** [comment]
@ajitsinghkaler most of the details are here: https://github.com/angular/angular/issues/14769#issuecomment-356901874
