### ISSUE TITLE
Template Parse errors in templates are missing the error message itself

### ISSUE THREAD

**Issue by tbosch** [angular/angular#20076]
**Reproduction**
```
<template let-x></template>
```
Leads to the error message:
```
Error at /Users/tbosch/projects/repro/issue-19485/src/index.html(1,11):  ("<template [ERROR ->]let-x></template>")
```

Expected:
```
Error at /Users/tbosch/projects/repro/issue-19485/src/index.html(1,11): "let-" is only supported on ng-template elements. ("<template [ERROR ->]let-x></template>")
```

**Note: HTML errors are reported correctly**
E.g.
```
<input></input>
```
Results in
```
Error: Template parse errors:
Void elements do not have end tags "input" ("<input>[ERROR ->]</input>"): /Users/tbosch/projects/repro/issue-19485/src/index.html@0:7
```

(b/68742933)

**Analysis**
This bug has been there since we used the new transformer based compiler.

In `ParseError.contextualMessage` [see parse_util.ts](https://github.com/angular/angular/blob/master/packages/compiler/src/parse_util.ts#L121) we don't include `this.msg`. However, this method is used in [program.ts](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/program.ts#L524) to create diagnostics.

**Proposed solution**
Change `ParseError.contextualMessage` to include `this.msg` as a prefix.

**Comment by aayusharora** [comment]
Hi @tbosch Can I work on this ?

**Comment by aayusharora** [comment]
@tbosch It seems it is already resolved. You can close this.
![screen shot 2017-11-03 at 9 16 58 pm](https://user-images.githubusercontent.com/12194719/32409168-ba2d6428-c1cc-11e7-9bb4-50af7545b5e7.png)

**Comment by chuckjaz** [comment]
@aayusharora Normally I would jump at the chance for some help here but this is a high priority bug for us internally so I took it.

Thanks for the offer and let me know if you want something else to work on.
