### ISSUE TITLE
Documentation Deploy to IIS Rewrite Rule not working

### ISSUE THREAD

**Issue by Magnusri** [angular/angular#20070]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The documentation at https://angular.io/guide/deployment#production-servers under IIS is outdated, showing redirection to the route "/src/" which does not work as intended.

## Expected behavior
Adding the rewrite rule should make the Angular application able to refresh when on routes without problems.

## Change suggestion
Change the IIS redirection rewrite action to:
action type="Rewrite" url="/"

## Environment
Running Angular 4.2.4 on IIS Server on Windows Server 2016

**Comment by IgorMinar** [comment]
@johnpapa @wardbell could you please help updating the IIS info? thanks!

**Comment by kapunahelewong** [comment]
Closing as this was updated in the above PR. Thanks for this @Magnusri. If you have any outstanding questions, just let me know.
