### ISSUE TITLE
Prerender compilation omits hash from css background url paths in index.html

### ISSUE THREAD

**Issue by michaelcm** [angular/angular#20080]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
After running `npm run build:prerender`, the resulting index.html file has the pre-rendered styles included at the top (as expected), but the background image filename in this style block is lacking the hash suffix that is present both on the images themselves, and the dynamic styles. Have seen the issue with .jpg and .svg files, perhaps more.

Generated CSS: `[_nghost-c0]{background:url(IMG_1901.jpg);}`
Expected filename: `IMG_1901.733fee1cd7a2cb0b98d6.jpg`

The directory was stripped off the beginning of the file paths correctly, since the images with a hash in their name are served from the root.

## Expected behavior
The image filenames included in the static index.html should be the hashed image filename used everywhere else.

## Minimal reproduction of the problem with instructions
*STEPS TO REPRODUCE*
1. Start with https://github.com/angular/universal-starter (current version used in testing comes with @angular 5.0.0-rc8).
2. Run `npm install`
3. Place an image with this filename at `src/images/IMG_1901.jpg`
4. Within home.component.ts, add `styles: [':host{ background: url("../../images/IMG_1901.jpg"); }']` to the component definition (after template). Note that it also occurs with an external file, and with scss styles.
5. Run `npm run build:prerender`.
6. Observe the contents of `dist/browser/index.html` either directly, or in the browser with `npm run serve:prerender`.

## Environment
<pre><code>Angular version: 5.0.0-rc.8

Other relevant packages:
- @angular/cli 1.5.0-rc.6
- @angular/core 5.0.0-rc.8
- @nguniversal/express-engine 5.0.0-beta.4

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v8.8.0
- Platform:  Mac/Unix/Windows (all)
</code></pre>

**Comment by vikerman** [comment]
Can you explain which tool is adding the hashes to the image?

**Comment by filipesilva** [comment]
I **think** this is a CLI issue, where inline styles do not get preprocessed like styleUrls. If you get a fingerprint on the image with the styleUrl, can you open an issue in https://github.com/angular/angular-cli instead please?

**Comment by alxhub** [comment]
I agree with @filipesilva.
