### ISSUE TITLE
Hi Angular team, we have upgraded our solution to Angular 4.4.6 today and getting error - ERROR in this.compiler.compileAll is not a function  ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Code\Shield.Web\src'

### ISSUE THREAD

**Issue by sachindave1978** [angular/angular#20083]
Have upgraded to Angular 4.4.6 and got the below error for 

ng build --prod

ERROR in this.compiler.compileAll is not a function  ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Code\Shield.Web\src'
 @ ./src/main.ts 4:0-74 @ multi ./src/main.ts "0.8.11"

**Comment by dhardtke** [comment]
See my issue https://github.com/angular/angular/issues/20082

**Comment by Toxicable** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by foxjazz** [comment]
Stuff like this happens when the json file is fubar. My recommendation is to create a new project, and compare the json files between the old and new and make similar.
