### ISSUE TITLE
TypeScript-ify: examples

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2008]
- [x] benchpress
- [x] forms
- [x] gestures
- [x] hello_world
- [x] key_events
- [x] material
- [x] sourcemap
- [x] todo
- [x] e2e_test

**Comment by naomiblack** [comment]
This cannot be started until `core` (#1997), `services` (#2002) , `directives` (#1998) and `forms`(#1999) are done.

**Comment by vicb** [comment]
material needs the source code to be TSified first

**Comment by vicb** [comment]
should e2e be tsified as well ?

**Comment by vicb** [comment]
`form` use the `EventEmitter` which has a different API in js vs Dart.
Any plan on unifying those ? 

/cc @vsavkin

**Comment by vicb** [comment]
Ok that's `ObservableWrapper` for forms... will update

**Comment by jeffbcross** [comment]
@ttowncompiled is working on the e2e test typscriptification

**Comment by jeffbcross** [comment]
@ttowncompiled has finished the remaining examples
