### ISSUE TITLE
How to get rid of dozens of ngSwitchCase?

### ISSUE THREAD

**Issue by gavinasd** [angular/angular#20088]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Hey guys, I am using anuglar 4.x and @angular/cli to develop my own website. I have met the following problem. 

I have a list-component to display different component based on their type. Currently, my code is like:
`
`
    <div [ngSwitch]="type">

    <component-one  *ngSwitchCase="......"
            [someInput]="..."
            (someOutput)="..."
    ></component-one>

    <component-two  *ngSwitchCase="......"
            [someInput]="..."
            (someOutput)="..."
    ></component-two>

    <component-three  *ngSwitchCase="......"
            [someInput]="..."
            (someOutput)="..."
    ></component-three>

    <component-four  *ngSwitchCase="......"
            [someInput]="..."
            (someOutput)="..."
    ></component-four>

    <component-five  *ngSwitchCase="......"
            [someInput]="..."
            (someOutput)="..."
    ></component-five>

    <component-six  *ngSwitchCase="......"
            [someInput]="..."
            (someOutput)="..."
    ></component-six>
    </div>
`
It is very simple. What I try to do is using ngSwitch to display different component based on the 'type' variable. And every component can communicate with its parent component using @Input() and @Output(). 

## Expected behavior

These code runs correctly. But since I got dozens of component to display, the code get larger and larger and looks like a mess. Therefore, I try to use the dynamic component mechanism and I found that dynamic component doesn't support @Input and  @Output. Moreover, dynamically added component won't trigger ngOnChanges function(according to this issue https://github.com/angular/angular/issues/8903). All these problems  block my way to using dynamic component. 

What should I do to improve my code, making it cleaner? Thanks a lot.

## Minimal reproduction of the problem with instructions

It should be reproduced every time.

## What is the motivation / use case for changing the behavior?

better code

## Environment

<pre><code>
Angular version: 4.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by baruchvlz** [comment]
Wouldn't you be able to achieve this same thing using the Router?

**Comment by lazarljubenovic** [comment]
> What should I do to improve my code, making it cleaner? Thanks a lot.

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gavinasd** [comment]
@baruchvlz Because I need the child-component to interact with the parent-component. 

If I use the router-outlet, can it interact with the parent-component? For example, if a variable in parent-component changes, the child-component in ngSwitch will change automatically. But router-outlet can not change util the url has been changed.

That is why I don't use router. Do you have any suggestion? Thanks a lot.

**Comment by vicb** [comment]
as @lazarljubenovic this issue tracker is not for support request
