### ISSUE TITLE
Implementing RSA encryption？

### ISSUE THREAD

**Issue by LING36** [angular/angular#20092]
How does angular4.0 use RSA to implement encryption?

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

You shouldn't encrypt anything on the client, leave that for your server to handle
