### ISSUE TITLE
HammerJS regression (HammerInput)

### ISSUE THREAD

**Issue by zygimantas** [angular/angular#20098]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have:

```
@HostListener("swipeleft", ["$event"])
public onHostSwipe(input: HammerInput): void { ... }
```

With 5.0.0 I am getting an
```Uncaught ReferenceError: HammerInput is not defined``` **runtime error**. Compiles without any warnings.

Maybe compiler decided that HammerInput was not required for my application and did not include in build?

"@ types/hammerjs" is added to devDependencies and "hammerjs" to dependencies.

## Expected behavior

No error, as in 4.x.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 41 (16)
 
For Tooling issues:
- Node version: v8.7.0
- Platform:  Windows

</code></pre>

**Comment by zygimantas** [comment]
Related https://github.com/angular/material2/issues/7873

**Comment by vicb** [comment]
`HammerInput` has never been an angular/angular thing.
Not sure where it comes/came from, maybe material has you mentioned ?
