### ISSUE TITLE
TypeScript-ify: Tests

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2009]
- [x] dom
- [x] renderer
- [x] change-detection
- [x] core
- [x] di
- [x] directives
- [x] facade
- [x] forms
- [x] mock
- [x] reflection
- [x] router
- [x] services
- [x] test_lib

**Comment by naomiblack** [comment]
This cannot be started until `core` (#1997), `services` (#2002) , `directives` (#1998), `mock` (#2000), and `test_lib` (#2003)  are in.

**Comment by naomiblack** [comment]
@jeffbcross and @tbosch are resolving the remaining tests in https://github.com/angular/angular/pull/2212

**Comment by jeffbcross** [comment]
Router src & tests are passing in JS locally...

**Comment by naomiblack** [comment]
@juliemr will move the .es6 to .ts and verify that this all still works, so we can remove dependency on traceur

**Comment by jeffbcross** [comment]
Actually, @ttowncompiled is working on the e2e_tests inside benchmarks, @juliemr is off the hook.

**Comment by jeffbcross** [comment]
All unit tests have been ported to typescript
