### ISSUE TITLE
angular.cn has a bug on the stage-jump

### ISSUE THREAD

**Issue by Flymachine** [angular/angular#20094]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I left-click a link in a DOC page to jump to a certain stage which in same page, It doesnot work.

## Expected behavior

It need to work when I left-click the link.

## Minimal reproduction of the problem with instructions

any link to jump to a centain stage, or, in the orther hand, link to a centain heading.
## What is the motivation / use case for changing the behavior?

I found the links is the label like `<a href="tutorial#我们要构建出什么">我们要构建出什么</a>`.
this bug does not exist in `v2.angular.cn`.

I get the HTML code and found this:
`<h2 translation-result="" id="我们要构建出什么"><a title="Link to this heading" class="header-link" aria-hidden="true" href="tutorial#我们要构建出什么">`

In fact, chinese words should not be used in the attributes,  id in particular, of the html label mostly.
So, the link does not work. (In v2.angular.cn, the id only has english words in the HTML code.)

## Environment
In `https://angular.cn/`, like `https://angular.cn/tutorial`
<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version 56.02
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows 

Others:

</code></pre>

**Comment by StephenFluin** [comment]
Moved to the angular-cn repo.
