### ISSUE TITLE
Angular v4 API documentation

### ISSUE THREAD

**Issue by sarunint** [angular/angular#20090]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, https://angular.io shows only the latest version API.

## Expected behavior

As Angular v4 is still the current LTS. There should be v4 API reference on the web site too. (Something like https://angularjs.org)

**Comment by trotyl** [comment]
Will be fixed by #20089?

**Comment by lacolaco** [comment]
@trotyl I think so. v4 doc is existing as v4.angular.io. this is an issue only about navigation.

**Comment by istiti** [comment]
@sarunint wonder what is the reason to stay on v4 lts instead v5?

**Comment by lacolaco** [comment]
maybe 3rd party libraries, tools, and other complex reasons... v5 apps in today are so happy case.

**Comment by sarunint** [comment]
Oh, I didn't realise about https://v4.angular.io. That's good to know.

@istiti I personally upgraded to v5 already and I strongly suggest everyone to do so, but there are many people out there that aren't comfortable to upgrade to v5 yet.
