### ISSUE TITLE
Angular4 and Prerender.io

### ISSUE THREAD

**Issue by sunderkasajal1203** [angular/angular#20099]
HI

I am trying to use prerender.io for my angular 4 application but i am not able to render my html pages

followed this
 https://github.com/prerender/prerender/tree/chrome and angular.io/guide/quickstart
for prerender and angular 4 respectively

I have set up both things on my local Then through cmd i ran the two applications separately on different ports
localhost:3000 for prerender and
/localhost:4200 for angular

And then i used this url http://localhost:3000/http://localhost:4200 to render the page but it does not seem to load at allIs prerender.io compatible with Angular 2 and Angular 4 or only with AngularJs?

Regards
Sajal

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
