### ISSUE TITLE
angular-update-guide and npm v5, typescript version problem.

### ISSUE THREAD

**Issue by Stexxen** [angular/angular#20104]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The Site at https://angular-update-guide.firebaseapp.com/ referred to in your [blog](https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced)
recommends the following command to upgrade 

`npm install @angular/{animations,common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router}@next typescript@2.4.2 rxjs@'^5.5.2'
`

I'm using npm v5.5 and this updates package.json to 

`    "typescript": "^2.4.2"`

not

`    "typescript": "~2.4.2"`

So the next time `npm update` is run this will now update typescript to 2.6.2, which is outside your supported ranges of typescript@'>=2.4.2 <2.5.0' that the CLI reports.

## Minimal reproduction of the problem with instructions
This just requires npm v5+ and I think is related to this issue https://github.com/npm/npm/issues/16813

## Environment

<pre><code>
Angular version: 5.0.0
For Tooling issues:
- Node version: 8.6.0
- NPM version: 5.5.1
- Platform:  Mac

Others:

</code></pre>

**Comment by StephenFluin** [comment]
@Stexxen You are right, I'll get this fixed right away.  I'm closing this issue as it's not part of angular/angular, but do you know the right npm command? Even npm install typescript@'=2.4.2' still seems to resolve to `^2.4.2'.

**Comment by Stexxen** [comment]
@StephenFluin Unfortunately I'm not sure there is a correct npm command, as per the issue https://github.com/npm/npm/issues/16813 it appears the original behaviour was unintended and no longer exists.
