### ISSUE TITLE
Multipart request ==> Impossible to specify the content type of a specific part

### ISSUE THREAD

**Issue by stephanecot** [angular/angular#20100]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

I'am using angular 4.4.x

I have a form of this type:
const formData: FormData = new FormData();
formData.append('files', file);
formData.append("data", JSON.stringify(data));

When I post my request with HttClient, the requestPart has no content type and this is causing an error with my Spring MVC rest controller.

I have found on the net, an exemple like that:
formData.append("data", new Blob(JSON.stringify(data)), {type: 'application/json'});

But it is not supported in my angular project.

**Comment by lazarljubenovic** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
