### ISSUE TITLE
Invalid regular expression: /^[_A-Za-zÀ-ÖØ-öø-˿Ͱ-ͽͿ-῿‌-‍⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-��-󯰀-�:]

### ISSUE THREAD

**Issue by krivochenko** [angular/angular#20109]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I build universal application without using Angular-cli. Without AoT everything works fine, but when I build application with AoT, I get error:

```
SyntaxError: Invalid regular expression: /^[_A-Za-zÀ-ÖØ-öø-˿Ͱ-ͽͿ-῿‌-‍⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-��-󯰀-�:][-._A-Za-z0-9·À-ÖØ-öø-˿̀-ͽͿ-῿‌‍‿⁀⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-��-󯰀-�:]*$/: Range out of order in character class
``` 
Peace of compiled code, which cause error, accords to code from `domino/lib/xmlnames.js`:
```
// Most names will be ASCII only. Try matching against simple regexps first
var simplename = /^[_:A-Za-z][-.:\w]+$/;
var simpleqname = /^([_A-Za-z][-.\w]+|[_A-Za-z][-.\w]+:[_A-Za-z][-.\w]+)$/;

// If the regular expressions above fail, try more complex ones that work
// for any identifiers using codepoints from the Unicode BMP
var ncnamestartchars = "_A-Za-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02ff\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD";
var ncnamechars = "-._A-Za-z0-9\u00B7\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02ff\u0300-\u037D\u037F-\u1FFF\u200C\u200D\u203f\u2040\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD";

var ncname = "[" + ncnamestartchars + "][" + ncnamechars + "]*";
var namestartchars = ncnamestartchars + ":";
var namechars = ncnamechars + ":";
var name = new RegExp("^[" + namestartchars + "]" + "[" + namechars + "]*$");
var qname = new RegExp("^(" + ncname + "|" + ncname + ":" + ncname + ")$");
```
## Expected behavior
Success compilation with AoT

## Minimal reproduction of the problem with instructions

```
//webpack.config.json
...
    return new AngularCompilerPlugin({
        tsConfigPath: root('./src/tsconfig.server.aot.json'),
    });
...
```

```
//tsconfig.server.aot.json
{
  "extends": "./tsconfig.server.json",
  "angularCompilerOptions": {
    "entryModule": "./app/server-app.module#ServerAppModule"
  },
  "include": [
    "main.server.prod.ts",
    "./app/server-app.module.ts"
  ]
}
```
```
//tsconfig.server.json
{
  "extends": "../tsconfig.json",
  "angularCompilerOptions": {
    "entryModule": "./app/server-app.module#ServerAppModule"
  },
  "include": [
    "main.server.dev.ts"
  ]
}
```
```
//tsconfig.json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "es2015",
    "target": "es5",
    "noImplicitAny": false,
    "sourceMap": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```
## Environment
<pre><code>Angular version: 5.0.0

For Tooling issues:
- Node version: v8.9.0
- Platform:  Linux in docker container
</code></pre>

**Comment by gkalpak** [comment]
This sounds similar to #19475. I don't think it is an Angular issue. Probably something messes up the RegExp in the build pipeline.

**Comment by krivochenko** [comment]
Should I open issue [here](https://github.com/angular/angular-cli/tree/master/packages/%40ngtools/webpack)? 

Also I created small [repository](https://github.com/krivochenko/angular-starter) for reproducing issue.

**Comment by vicb** [comment]
@krivochenko as George mentioned above this issue has already been reported. It's most probably an issue with some external build tool and some help in investigating the issue would be great.

Only leaving the issue opened so that people can search for it - the Angular team has no current plan to investigate this for now.

**Comment by gkalpak** [comment]
It is probably something that transforms the code in a way that it shouldn't (and it is not unlikely to be caused by something in `@ngtools/webpack`, so I would open an issue [there][1].

That said, it would be better for domino to escape the Unicode code-units in the RegExp (and it would avoid the problem altogether afaict. E.g.:

```diff
-var ncnamechars = "-._A-Za-z0-9\u00B7\u00C0-\u00D6\u...
+var ncnamechars = "-._A-Za-z0-9\\u00B7\\u00C0-\\u00D6\u...
``` 

[1]: https://github.com/angular/angular-cli/tree/master/packages/%40ngtools/webpack

**Comment by krivochenko** [comment]
Ok. I opened issue [#106](https://github.com/fgnass/domino/issues/106) in repository of domino.  As I understood, it's not possible to compile Angular 5 application with AoT for now. Or I missed something?

**Comment by aitboudad** [comment]
just make sure to define `domino` as [externals](https://github.com/angular/universal-starter/blob/master/webpack.server.config.js#L16) on your webpack config

**Comment by krivochenko** [comment]
@aitboudad I'm not sure that I correct understand with property. Could you give me some example, how to do it?

**Comment by aitboudad** [comment]
@krivochenko see https://webpack.js.org/configuration/externals/ or use [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) plugin

**Comment by krivochenko** [comment]
@aitboudad webpack-node-externals allows me exclude all modules from node_modules folder. This is not what I need. I tried to use `externals`:
```
externals: /^(domino|\$)$/i
```
and got error `ReferenceError: domino is not defined`
What I do wrong?

**Comment by trotyl** [comment]
> As I understood, it's not possible to compile Angular 5 application with AoT for now.

Please note the fact that, this problem cannot be reproduced on Angular CLI or ejected webpack configuration for server-side rendering, so while it's not sure what the problem is, there seems nothing wrong for Angular 5 with or without AOT.

**Comment by aitboudad** [comment]
@krivochenko that's how I solved the `Invalid regular expression` issue

> and got error ReferenceError: domino is not defined
What I do wrong?

 I have no idea sorry!

**Comment by krivochenko** [comment]
@trotyl ok, I can rephrase:
>As I understood, it's not possible to compile Angular 5 application with AoT without using CLI for now.

**Comment by krivochenko** [comment]
Just for experiment I used webpack-node-externals:
```
externals: [nodeExternals()]
```
On server-side everything works good, but I see `Uncaught SyntaxError: Invalid regular expression: /^[_A-Za-zÀ-ÖØ-öø-˿Ͱ-ͽͿ-῿‌-‍⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-��-󯰀-�:][-._A-Za-z0-9·À-ÖØ-öø-˿̀-ͽͿ-῿‌‍‿⁀⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-��-󯰀-�:]*$/: Range out of order in character class` on the client-side. As I know domino is used for server-side rendering. So why it was included in my client.js?

**Comment by krivochenko** [comment]
I solved it by avoid using minification for server.js. I compile it with AoT, but without `-p` flag. So
> It's possible to compile Angular 5 application with AoT without using CLI.

Sorry, for spent your time. For me there is only one secret: how Domino turned out in client chunk. Somewhere in my configs there is mistake. 

Thanks for help.

**Comment by gkalpak** [comment]
For anyone landing here, [this thread][1] seems relevant.
(Thx @chuckeles for pointing out.)

[1]: https://github.com/mishoo/UglifyJS2/issues/54#issuecomment-26230544

**Comment by julienR2** [comment]
I still get the same issue on angular 5.0.2, using webpack build. I ended up doing the same as @krivochenko, not using minification for the server files, but I don't feel it is the proper solution..
I'd be interested if anyone find a better workaround

**Comment by gkalpak** [comment]
@julienR2, have you checked out [that thread][1]?

[1]: https://github.com/mishoo/UglifyJS2/issues/54#issuecomment-26230544

**Comment by julienR2** [comment]
@gkalpak thanks, I saw your previous message about it. I tried to add the utf8 charset to my scripts tags, but I still have the issue.. :/

**Comment by odahcam** [comment]
This was how I solved my case:

![image](https://user-images.githubusercontent.com/3942006/34959353-4eff58e4-fa1d-11e7-9735-98bd35b71c61.png)

**Comment by odahcam** [comment]
@krivochenko how did you managed to "build without the `-p` flag"? I'm building with Webpack and I can't figure out what that means. 😕

**Comment by odahcam** [comment]
Seems like building with `UglifyJSPlugin` before `AngularCompilerPlugin` solves this issue, but creates another:

```
09:04:28 ERR] Connection id "0HLATJ89A3R9B", Request id "0HLATJ89A3R9B:00000001": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: No NgModule metadata found for 'function (){}'.
Error: No NgModule metadata found for 'function (){}'.
```

Some people reported real problems with modules, but I can see none wrong here. I have no idea of what is that error. Also, some people have said that this could be a problem with @ngtools/aspnetcore-engine but I really have no idea.

**Comment by SwamyKottur** [comment]
Use UglifyJsPlugin from here rather uglifyjs-webpack-plugin than webpack one. This fixes the regex issue.

new UglifyJsPlugin({
        uglifyOptions: {
          ie8: false,
          mangle: {
            safari10: true,
          },
          output: {
            ascii_only: true,
            comments: false,
            beautify: false,
            webkit: true,
          },
        },
      }),

**Comment by StefanRein** [comment]
@krivochenko 
This worked for me:

I found, that for **server side** you need to install the npm package of the UglifyJsPlugin and it does NOT work with `webpack.optimize.UglifyJsPlugin`:

I installed: `"uglifyjs-webpack-plugin": "1.2.5"`

This one is only for the **webpack.client.js**

```javascript

const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
module.exports = {
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: false,
            uglifyOptions: {
                ecma: 5,
                output: {
                    comments: false
                }
            }
        })
    ]
};
```
