### ISSUE TITLE
angular 5 common/http is missing RequestOptionsArgs

### ISSUE THREAD

**Issue by fredriklindell** [angular/angular#20106]
angular 5 

new common/http is missing RequestOptionsArgs interface which exists in the deprecated http library

**Comment by Stexxen** [comment]
A different Interface is used. Some refactoring is required.

See https://angular.io/api/common/http/HttpClient

**Comment by alxhub** [comment]
Hi @fredriklindell,

`HttpClient` is not a drop-in replacement for `Http` and is not API-compatible.
