### ISSUE TITLE
Angular 5 & 4.4.x - Router Navigate does not activate onInit after external request

### ISSUE THREAD

**Issue by elporfirio** [angular/angular#20112]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
On external javascript API response, (created as Observable) the router.navigate method, does not activate lifecycle events "OnInit" or "ngAfterViewInit"

## Expected behavior
After a response from external JS API, like Facebook, Gigya, etc. And navigate to route, the lifecycle should be triggered.

## Minimal reproduction of the problem with instructions
This is a Router issue, please go to next repo with minimal environment:

[https://github.com/elporfirio/angular4-router-issue](https://github.com/elporfirio/angular4-router-issue)

1. Install and ng-serve
2. Enter to:  http://localhost:4200/
3. Press Click me ! (for xhr request) and everything works good (you should see 2 alerts)
4. Press Click me for Error (for api js request) and lyfecycle stop working

In file [service HelperService](https://github.com/elporfirio/angular4-router-issue/blob/master/src/app/helper-service.service.ts) exist 2 methods

First One a simple XHR works fine, but the other one use a JS API after complete a request (success/error no matter). The navigate redirects but the lifecycle is not activated.

## What is the motivation / use case for changing the behavior?
After navigate the component should work normally, as on type url.

## Environment

<pre><code>
Angular version: 5.0  and 4.x

    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"

Browser:
- [X] Chrome (desktop) Versión 61.0.3163.100 (Build oficial) (64 bits)
- [X] Safari (desktop) Versión 11.0.1 (12604.3.5.1.1)
 
For Tooling issues:
- Node version: v6.11.3
- Platform:  MacOS Sierra

</code></pre>

**Comment by elporfirio** [comment]
Alternative solution for keep working untill bug resolve, listen router event methods on component.

```
  constructor(private router: Router) {
    router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        this.ngOnInit();
      }
      // Instance of should be: 
      // NavigationEnd
      // NavigationCancel
      // NavigationError
      // RoutesRecognized
    });
  }
```

**Comment by WandererInVoids** [comment]
@elporfirio can u run u code in ngZone like: 
`return Observable.create(observer => {
       ngZone.run(() => {
         // your code
         })
})`

**Comment by elporfirio** [comment]
@WandererInVoids nope, it doesn't work.

**Comment by WandererInVoids** [comment]
@elporfirio can u use full path for navigate not relative when u use 
`this.router.navigate(['someroute']) //is relative`
`this.router.navigate(['/someroute']) //is absolute` try this one

**Comment by elporfirio** [comment]
[Last fix proposed by me](https://github.com/angular/angular/issues/20112#issuecomment-341474541), router listener it doesn't work, after first one the rest of routes stop working "ngInit() " and "ngAfterViewinit()"

@WandererInVoids  your [solution](https://github.com/angular/angular/issues/20112#issuecomment-341737114) still not working , please consider download the example and try it :) before and answer. Thanks you

**Comment by matthew-ch** [comment]
The following works (I tried):
```typescript
// in your HelperService
        if (result.status === 'FAIL') {
          this.zone.run(() => {
            observer.error(result.errorDetails || result.errorMessage);
          });
        } else {
          this.zone.run(() => {
            observer.next(result);
            observer.complete();
          });
        }
```
Of course you need to inject `NgZone`.

**Comment by elporfirio** [comment]
thank you @matthew-ch  it is works :D router navigate is enabled again.

```
return Observable.create(observer => {
      gigyaParams.callback = (result) => {
        if (result.status === 'FAIL') {
          this.ngZone.run(() => {
            observer.error(result.errorDetails || result.errorMessage);
          });
        } else {
          this.ngZone.run(() => {
            observer.next(result);
            observer.complete();
          });
        }
      };
      gigya.accounts.login(gigyaParams);
    });
```

**Comment by elporfirio** [comment]
thank you @matthew-ch it is works :D router navigate is enabled again.

```
return Observable.create(observer => {
      gigyaParams.callback = (result) => {
        if (result.status === 'FAIL') {
          this.ngZone.run(() => {
            observer.error(result.errorDetails || result.errorMessage);
          });
        } else {
          this.ngZone.run(() => {
            observer.next(result);
            observer.complete();
          });
        }
      };
      gigya.accounts.login(gigyaParams);
    });
```

**Comment by royalfint** [comment]
agh. I have the same issue and was exploring this topic for the last 3 hours and still can't get how you solved the issue. 
I have following code in my constructor function:
`constructor(private HTTP: Http){
    this.getSubbed();
    /*
    this.getFires().subscribe(data => {
      console.log("get data called")
      this.data = data;
    })
    */
    this.getFires();
    /*
    return this.http.get(this.apiUrl).map((res: Response) => res.json())
    */
    
    this.getAddresses().subscribe(data2 => { //has to be called once, otherwise will crash the app
      console.log("addresses got fetched!")
      console.log(data2);
      this.group = [CreateNewAutocompleteGroup(
        'Поиск',
        'completer',
        data2,
        {titleKey: 'label', childrenKey: null}
      )];
      this.addresses = data2;
    })
  }`
that's how I handle requests. and after requests are made and I go to any page OnInit simply doesnt get called. Any ideas?

**Comment by elporfirio** [comment]
@royalfint  My subscribe() method is on "`ngOnInit()`" and others in "`ngAfterViewInit()`".  

do not forget implement:

```
export class MyCustomClassComponent implements OnInit, AfterViewInit, OnChanges {
    // Code
  ngOnInit() {
  }

  ngAfterViewInit() {
    // subcribe method here
  }
}
```

Reference here: https://angular.io/guide/lifecycle-hooks

**Comment by royalfint** [comment]
please look into my code https://github.com/royalfint/fire24 . I have been trying to fix this problem for the last 18 hours..

**Comment by elporfirio** [comment]
@royalfint well this is not stackoverflow, next try add error method to your `subcribe()`

instead only:

```javascript
this.getAddresses().subscribe(data2 => {
  // code
});
````

change to:

```javascript
this.getAddresses().subscribe(data2 => {
}, error => {alert('error!'), console.log(error) });
```

for see what is happening on failure

**Comment by Iaromir** [comment]
quick fix
`constructor(private zone: NgZone) {}
  this.getAddress.subscribe((data)=>{
      ... //Logic here
     return this.zone.run(() => this.router.navigate(['/']));
  })
`

**Comment by barrychapman** [comment]
Where did you guys add the `return Observable.create(observer => { ngZone.run(() => { // your code }) })`?

I have the same issue

**Comment by elporfirio** [comment]
> Where did you guys add the `return Observable.create(observer => { ngZone.run(() => { // your code }) })`?
> 
> I have the same issue

@barrychapman In any observable manually created for external libraries async request, like aws-sdk, or firebase-sdk, catchoom, etc.
