### ISSUE TITLE
Running two Angular projects is making one projects access another project data

### ISSUE THREAD

**Issue by thiagofmleite** [angular/angular#20118]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm having a really bizarre error while running two Angular projects: Both projects are equals, except by a config constant that makes it access an API. While running a project A on port 4200 and project B on any other port (8080, for example), if I access http://localhost:4200, then on the same browser tab access http://localhost:8080, they will load their specific content. But, if I press to go back to the previous URL, the project A will load with project B content.

**Comment by vicb** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by thiagofmleite** [comment]
Just find a solution, adding cache control

`headers.append('Cache-control', 'no-cache');
headers.append('Cache-control', 'no-store');
headers.append('Expires', '0');
headers.append('Pragma', 'no-cache');`
