### ISSUE TITLE
Server Side Rendering with Router Guards

### ISSUE THREAD

**Issue by sopretty** [angular/angular#20110]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I created a Guard on "/login" to check if the user can access or not to the page.
It's working well without Server Side Rendering but if I use it (with ng-universal), the guard is executed twice : once on the server which return login page and once again on the client side.
Therefor, the login page is displayed for 1 second (html returned from server) then refresh.

## Expected behavior
Is there any solution to execute the guard only on time (on the server side) when this is the first call and use the guard on client side on next calls ?

Thank you,
SoPretty.

**Comment by xban1x** [comment]
You can always check if you are running on server or on client. And SSR will never work for pages behind auth.

**Comment by vikerman** [comment]
Closing based on above answer.
