### ISSUE TITLE
RouteReuseStrategy impossible to store/retrieve siblings AND ALSO a non-sibling

### ISSUE THREAD

**Issue by Thorski** [angular/angular#20114]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If routing includes a route with no children, and also a route with children, it is impossible to store and retrieve the correct DetachedRouteHandle in a custom RouteReuseStrategy if all routes are to be detached and if the user navigates among the siblings and the parent.   This is because the router is checking the full tree to the stored DetachedRouteHandle , but this may not match if coming from a sibling when it was stored navigating to a non-sibling or vice versa.

## Expected behavior

There needs to be a way to reuse components without rebuilding them no matter how navigated to.

## Minimal reproduction of the problem with instructions

If I have these routes defined:
<pre><code>
const routes: Routes = [
  { path: '', redirectTo: '/dashboard', pathMatch: 'full' },
  { path: 'dashboard',  component: DashboardComponent, data:{key: 'keyDashboard'}},
  { path: 'pages',
    component: PagesComponent,
    data: {key: 'keyPages'},
    children: [
      { path: 'A', component: PagesAComponent, data:{key: 'keyA'} },
      { path: 'B', component: PagesBComponent, data:{key: 'keyB'} },
    ]}
];
</code></pre>

And a user navigates in order from dashboard to pages/A to dashboard to pages/B to pages/A, there is no way to not re-create the PagesAComponent.

This is because the router is checking the full tree, but when navigating to/from a child such as pages/A to a sibling it asks to store the route from below the parent 'pages' (just 'A' or 'B' in this case), but when navigating to a non-sibling it stores a route tree of 'pages/A' or 'pages/B'.

Here is a plunker: http://embed.plnkr.co/DpYadGWx6PRHzSUKX2pK/

Click on dashboard, then pages/A, change value, then dashboard, then pages/B, then pages/A. A is re-constructed at this point.

For a key in CustomReuseStrategy I am currently using the catenation of 'keys' defined in the router data (see computeSnapshotKey). If I simply use the leaf 'key' (which does uniquely identify) the component I will get the angular error complaining it can't attach to a non-identical route. This is because the DetachedRouteHandle represents pages/A instead of just A which is expected.   

There is no way to reuse the children in this routing case.

## What is the motivation / use case for changing the behavior?

Applications must save state when switching between components.   This should work for any routing scenario.

## Environment

<pre><code>
Angular version: 4.3.6 

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

</code></pre>

**Comment by gianmarcov** [comment]
It's related to my reported issue #20072

**Comment by nbuso** [comment]
The RouteReuseStrategy in the plunkr will lead to 'Error: Cannot reattach ActivatedRouteSnapshot created from a different route' jumping from a child route (1/a) to another sibling (2) and back to the first parent (1).
I found implementing the RouteReuseStrategy a bit combersome having children routes and maybe redirects.

Is there a guidance on how to implement the reuse strategy in these cases?

+1 as a bug

**Comment by Thorski** [comment]
This is still broken.  Any plan to make custom RouteReuseStrategy work correctly in complex cases?

**Comment by atscott** [comment]
Confirmed in v10 as well: https://stackblitz.com/edit/angular-ivy-p88ykn?file=src%2Fapp%2Fdashboard.component.ts

**Comment by Thorski** [comment]
> Confirmed in v10 as well: https://stackblitz.com/edit/angular-ivy-p88ykn?file=src%2Fapp%2Fdashboard.component.ts

@atscott Thank you for converting my plunker to stackblitz.

**Comment by atscott** [comment]
Fixed by #43791
