### ISSUE TITLE
[ngSwitch] not working

### ISSUE THREAD

**Issue by TaylorZaneKirk** [angular/angular#20113]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Always uses the *ngSwitchDefault option

## Expected behavior

Should correctly trigger on valid switch option

## Minimal reproduction of the problem with instructions

HTML:
```
<ng-container *ngFor='let col of columns' [ngSwitch]="col.prop">

                <!-- Column with Pipe(s) -->
                <div *ngSwitchCase="'CustmVal'">
                    <ngx-datatable-column prop="{{col.prop}}">
                            <ng-template ngx-datatable-cell-template let-value="value" let-isSelected="isSelected" >
                                <span>{{value | currency:'USD':true:'4.2-2'}}</span>
                            </ng-template>
                    </ngx-datatable-column>
                </div>

                <!-- Actions Column -->
                <div *ngSwitchCase="'Actions'">
                    <ngx-datatable-column prop="{{col.prop}}">
                            <ng-template ngx-datatable-cell-template let-value="value" let-isSelected="isSelected" >
                                <span>LOL</span>
                            </ng-template>
                    </ngx-datatable-column>
                </div>

                <!-- Basic column -->
                <div *ngSwitchDefault>
                    <ngx-datatable-column prop="{{col.prop}}"></ngx-datatable-column>
                </div>
            
            
        </ng-container>
```

columns:
```
private columns: any[] = [
        {prop: "Actions"},
        {prop: "AWB"},
        {prop: "CustmVal"},
]
```

## What is the motivation / use case for changing the behavior?

Each column in my table could be implemented differently. I need an effective way of implementing the logic to choose which column implementation that particular column needs.

## Environment

<pre><code>
@angular/cli: 1.4.2
node: 6.11.2
os: win32 x64
@angular/animations: 4.4.4
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.5.3

Browser:
- [ x ] Chrome (desktop) version Version 61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.2  
- Platform:  Windows

Others:

</code></pre>

**Comment by lazarljubenovic** [comment]
How are datatables inside `ngSwitch` _minimal_ reproduction?

**Comment by TaylorZaneKirk** [comment]
@lazarljubenovic The content within the divs that hold the *ngSwitchCase directive should be inconsequential.

Did I not follow the guidelines laid out by the Angular documentation in regards to using [ngSwitch]?

**Comment by TaylorZaneKirk** [comment]
Solution found, just had to restructure.

```
<ng-container *ngFor='let col of columns'>
            <ngx-datatable-column [ngSwitch]="col.prop" prop="{{col.prop}}">
                    <ng-template *ngSwitchCase="'CustmVal'" ngx-datatable-cell-template let-value="value" let-isSelected="isSelected">
                            <span>{{value | currency:'USD':true:'4.2-2'}}</span>
                    </ng-template>
                    <ng-template *ngSwitchCase="'Actions'" ngx-datatable-cell-template let-value="value" let-isSelected="isSelected">
                            <span>LOL</span>
                    </ng-template>
                    <ng-template *ngSwitchDefault ngx-datatable-cell-template let-value="value" let-isSelected="isSelected">
                            <span>{{value}}</span>
                    </ng-template>
            </ngx-datatable-column>
        </ng-container>
```

Closing now
