### ISSUE TITLE
Can not import nothing from '@angular/common/locales/*'

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#20126]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I can't import nothing from `'@angular/common/locales/*'`.

## Expected behavior
Run a plunker following the [guide](https://angular.io/guide/i18n) without any problem.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/MoFoqiGvdRd2W45Lfr9Y

Others:
I thought it could be because the `common/locales` wasn't registered in `config.js`, so I added this line (`'@angular/common/locales': 'npm:@angular/common' + angularVersion + '/bundles/common-locales.umd.js'`) - just copied the common/http line - and the error keeps there.

**Comment by ericmartinezr** [comment]
Working just fine here https://stackblitz.com/edit/angular-gduxoq?file=app/app.component.ts

**Comment by rafaelss95** [comment]
Oh, so the problem is with PLUNKER. Thanks.

**Comment by alexzuza** [comment]
@rafaelss95 The problem is not with PLUNKER.

http://plnkr.co/edit/noKZoYCEM0zlo6Ci8BT8?p=preview
