### ISSUE TITLE
Feature request: reexport

### ISSUE THREAD

**Issue by scein** [angular/angular#20122]
## I'm submitting a...
<pre><code>
[ x] Feature request
</code></pre>

## Current behavior
In a shared module, it's common to reexport using import/export.

In many situations, this gets out of hand quickly, such as with Material 2.

## Expected behavior
I'd like to see a reexport feature, which would both import and export.

This could be a simple pre-processor step which lowers into import/export.

Example:
```
@NgModule({
 reexport:  [
    MatProgressBarModule,
    MatIconModule,
    MatButtonModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatCardModule,
    ... many, many more here...
    MatListModule,
    MatLineModule,
    MatCommonModule,
    MatSnackBarModule,
    ]
})
export class SomeKindOfSharedModule { }
```
## What is the motivation / use case for changing the behavior?
Less code to maintain, fewer things to remember.

Originally motived by a Material component failing silently due to a lack of export in the shared module.

**Comment by Toxicable** [comment]
There is no need for this feature
Just use the same array for both

```
const REXPORTS = [
  MatButtonModule,
  MatCheckboxModule
]

@NgModule({
  imports: [
    REXPORTS 
  ],
  exports: [
    REXPORTS 
  ]
})
```

**Comment by scein** [comment]
No nothing for anything. Reexport also communicates better the intention.
