### ISSUE TITLE
Need JitCompilerFactory in Angular 5

### ISSUE THREAD

**Issue by jackzard** [angular/angular#20125]
## I'm submitting a...
<pre><code>
[ x] Feature request
</code></pre>

## Current behavior
no factory for JitCompilerFactory like Angular 4

## Expected behavior
export JitCompilerFactory in Angular 5 or alternative

## Example code in Angular 4
<pre><code>
import {CommonModule} from '@angular/common'
import {Compiler, NgModule} from '@angular/core'
import {JitCompilerFactory} from '@angular/compiler'
import {DynamicComponent} from './dynamic.component'
import {DynamicComponentModule} from './dynamic.module'

export function compilerFactory() {
    return new JitCompilerFactory([{useDebug: false, useJit: true}]).createCompiler()
}

@NgModule({
    imports: [
        CommonModule,
    ],
    declarations: [
        DynamicComponent
    ],
    exports: [
        DynamicComponent
    ],
    providers: [
        DynamicComponentModule,
        {provide: Compiler, useFactory: compilerFactory}
    ],
})
export class DynamicModule {
}

</code></pre>

## Environment

<pre><code>
Angular version: 5.0.0
 
For Tooling issues:
- Node version: 8.4.0
- Platform:  Windows

**Comment by sarunint** [comment]
Everything in `@angular/compiler` is not part of the public API and changes are subjected to happen.

**Comment by maximusk** [comment]
I'd add that we need either JIT compiler that uses decorator or AOT compiler that uses static analysis, but **in runtime**

**Comment by trotyl** [comment]
@maximusk That's being discussed at #15510 & #15275, we don't need duplicate issue for tracking.

**Comment by maximusk** [comment]
@trotyl , I didn't create the issue. So do you know what Angular team plans to do with the compiler? I saw a doc once that stated that there were plans to move to AOT runtime

**Comment by trotyl** [comment]
@maximusk AFAIK there's no plan for runtime AOT, but most of it could be covered by `@angular/elements`, which is based on the dynamic template solution used in angular.io.

**Comment by maximusk** [comment]
@trotyl , just checked [the sources](https://github.com/robwormald/angular-elements/blob/master/src/demos/now-cards/now-card-feed.ngelement.ts):

```
import {NowCardFeedNgFactory} from '../../ngfactory/src/demos/now-cards/now-card-feed.ngfactory'

nge.define(NowCardFeedNgFactory);
```

it imports pre-compiled factory. Can you maybe clarify what approach exactly from `@angular/elements` can be used?

**Comment by trotyl** [comment]
@maximusk Angular Elements will wrap your Angular component into a web component, possibility you can have a look of the [introduction in Angular MIX](http://link.zhihu.com/?target=https%3A//www.youtube.com/watch%3Fv%3DljsOPm4MMEo%26index%3D8%26list%3DPLgRm9JfK2F3qeHLHtrIVqNef0LT04UD05), which can demonstrate it clearly.

**Comment by maximusk** [comment]
@trotyl, thanks, I've watched the talk and the idea behind the `@angular/elements`, however, I haven't found anything related to the runtime compilation in the sources. As I understand it's still a concept that's why it imports compiled factory instead of compiling the component.

**Comment by gkalpak** [comment]
I think there is some confusion here. Neither angular.io nor `@angular/elements` deal with aot-vs-jit compilation. (Both can work with either and prefer aot for the known reasons :grin:)

**Comment by trotyl** [comment]
Sorry for not make it clear, I'm just talking about dynamic HTML in runtime, not runtime AOT.

**Comment by maximusk** [comment]
@gkalpak , @trotyl 

Let's clarify what we're talking about here. You can have **a string** like this:
```
@Component({
   template: `<span>generated on the fly: {{name}}</span>`
});
class MyComp {}
```
and we want to get `mycom.ngfactory`.

This factory can be generated by Angular View Compiler which takes component metadata (template) as an input. This metadata can be obtained using either Jit or AOT compiler. Jit compiler requires evaluation of the code so that `Component` gets executed and attaches metadata to a class. AOT compiler doesn't need evaluation and works with AST produced by TypeScript (through transforms as I understand in the v5). So when I said:

> I'd add that we need either JIT compiler that uses decorator or AOT compiler that uses static analysis, but in runtime

I meant that we need any of the two to be able to produce factory in runtime if the component template is unknown during build.

**Comment by trotyl** [comment]
@maximusk I guess it's clear now, but still seems a duplication to me.

**Comment by mlc-mlapis** [comment]
@trotyl ... you are right ... but the main problem here is that for R5 there is just minimum or none info about that thing ... and I mean not only the exact code but also no conceptual idea for today or the nearest future. We all know that AOT mode is the right way but today there are still real edge cases where it is really the only way to compile some part of template on-demand in run-time ... and it could be fine ... why not in fact ... if you accept all factors that limit you from performance or sizing point of view.

**Comment by trotyl** [comment]
@mlc-mlapis I didn't mean the request itself is wrong, but just the content is duplicate.

Actually there're many problem about the expansibility of Angular view layer. For example: https://github.com/angular/angular/blob/master/packages/core/src/view/refs.ts#L196-L197, the signature is said to be `ViewRef` while the real requirement being `ViewRef_`, so user cannot simply make its own `TemplateRef` by what the type definition is.

There could be several requests like: Open compiler API, open view engine API, make Angular's view layer really expansible by not hacking any more... All of them could be valid, but should still follow the way of working (fill the template, no dup, ...)

**Comment by mlc-mlapis** [comment]
@trotyl ... yeap, so many open areas ... but especially `ViewRef_` / `ViewRef` story is not a new thing, if I remember ... would be interesting to review the whole evolution path maybe to understand all factors.

**Comment by claygifford** [comment]
how do you just add it... and move on.
Cannot upgrade to angular 5 until you add this feature

**Comment by ocombe** [comment]
You should not use it as a constructor, use the injector instead. See my comment here: https://github.com/angular/angular/issues/20639#issuecomment-347149868

**Comment by VSmirnov17** [comment]
I have 2 errors:
![selection_153](https://user-images.githubusercontent.com/23501851/33316887-94c5a6e6-d446-11e7-9538-fbe4fc37fd72.png)
![selection_154](https://user-images.githubusercontent.com/23501851/33316889-94e6cbbe-d446-11e7-8045-72b60ac57aa8.png)

Errors occur when I build project with --aot (ng serve --aot)
If not --aot - all good

**Comment by ocombe** [comment]
If you have an problem post the comments in the issue #20639, thanks.

**Comment by claygifford** [comment]
ocombe your code does work...

core.js:1427 ERROR Error: StaticInjectorError[JitCompiler]: 
  StaticInjectorError[JitCompiler]: 
    NullInjectorError: No provider for JitCompiler!
