### ISSUE TITLE
AOT does not compile when importing modules from other packages

### ISSUE THREAD

**Issue by ng-state** [angular/angular#20139]
I have simple package

```ts
import { Inject, Injector, ModuleWithProviders, NgModule, InjectionToken } from '@angular/core';
import { CommonModule } from '@angular/common';
import { StateHistoryComponent } from './state/state-history';

@NgModule({
    imports: [CommonModule],
    declarations: [StateHistoryComponent],
    exports: [StateHistoryComponent],
})
export class StoreModule {
}
```
i compile it using 
```
ngc -p tsconfig.dist.json
```

tsconfig:
```

{
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": true,
    "stripInternal": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "es2015",
    "moduleResolution": "node",
    "noEmitOnError": false,
    "outDir": "./release",
    "rootDir": ".",
    "sourceMap": true,
    "inlineSources": true,
    "lib": ["es2015", "dom"],
    "target": "es5",
    "skipLibCheck": true
  },
  "files": [
    "index.ts"
  ],
  "angularCompilerOptions": {
    "annotationsAs": "decorators",
    "genDir": "./release",
    "skipMetadataEmit" : true
  }
}
```
after importing it into my app
```ts
@NgModule({
  imports: [
    CommonModule,
    BrowserModule,
    FormsModule,
    RouterModule.forRoot(routes, { useHash: true }),
    StoreModule,
  ],
  declarations: [
    AppComponent,
    TodosComponent,
    TodoDescription,
    RouterHistoryTestComponent
  ],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule {
}
```

I got error:

```ts
ERROR in Error: Unexpected value 'StoreModule in C:/tmp/ng-state-example-app/node_modules/ng-state/src/ng-state.module.d.ts' imported by the module 'AppModule in C:/tmp/ng-state-example-app/src/app/app.modu
le.ts'. Please add a @NgModule annotation.
```

I imported empty module after hitting my head to the wall when trying to get real module to work with AOT with error:
```
"Calling function 'StoreModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule"
```
more details on Angular CLI git: https://github.com/angular/angular-cli/issues/8311

Dev build runs just FINE and everything works at runtime. Webpack is also able to compile AOT without any problem (before 5.0.0 because now ngc-webapck module need to be updated). 

This waste of time really drives me crazy. Whats drives me even more that after updating ng-state package to Angular 5.0.0 I did not check AOT before publishing package and more than 400 people relies on this package for state managment

Any ideas how to fix BOTH of them?

p.s. if you want to reproduce it please visit:
```
https://github.com/ng-state
```

and you will have everything there: store and example app it self

**Comment by icepeng** [comment]
I had a similar problem.
https://github.com/flauc/angular2-notifications/issues/262
angular2-notifications module didn't work with ng5, so I found workaround here.

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

>ERROR in Error: Unexpected value 'StoreModule in C:/tmp/ng-state-example-app/node_modules/ng-state/src/ng-state.module.d.ts' imported by the module 'AppModule in C:/tmp/ng-state-example-app/src/app/app.modu
le.ts'. Please add a @NgModule annotation.

This is likely an issue with how `ng-state` is published, from the looks if it you're importing the typing declaration not the actual symbol

>"Calling function 'SotreModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule"

This has been dicussed many times on how to solve.
You're likely using a function in your metadata and by extension anywhere in your "forRoot" method

**Comment by ng-state** [comment]
Thanks for quick response. Please tell me which  function is not exported?

```ts
import { Inject, Injector, ModuleWithProviders, NgModule, InjectionToken } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Dispatcher } from './services/dispatcher';
import { Router } from '@angular/router';
import { RouterState } from './state/router-state';
import { ServiceLocator } from './helpers/service-locator';
import { State } from './state/state';
import { StateHistory } from './state/history';
import { StateHistoryComponent } from './state/state-history';
import { Store } from './store/store';

export const INITIAL_STATE = new InjectionToken('INITIAL_STATE');
export const COLLECT_HISTORY = new InjectionToken('COLLECT_HISTORY');
export const STORE_HISTORY_ITEMS = new InjectionToken('STORE_HISTORY_ITEMS');
export const IS_PROD = new InjectionToken('IS_PROD');

export function stateFactory(initialState) {
    return new State(initialState);
}

export function storeFactory(state: State<any>) {
    return new Store(state);
}

export function historyFactory(store: Store<any>) {
    return new StateHistory(store);
}

export function routerStateFactory(store: Store<any>, router: Router) {
    return new RouterState(store, router);
}

@NgModule({
    imports: [CommonModule],
    declarations: [StateHistoryComponent],
    exports: [StateHistoryComponent]
})
export class StoreModule {
    static provideStore(initialState: any, isProd?: boolean, collectHistory?: boolean, storeHistoryItems?: number): ModuleWithProviders {
        return {
            ngModule: StoreModule,
            providers: [
                { provide: STORE_HISTORY_ITEMS, useValue: storeHistoryItems },
                { provide: COLLECT_HISTORY, useValue: collectHistory },
                { provide: INITIAL_STATE, useValue: initialState },
                { provide: IS_PROD, useValue: isProd },
                { provide: State, useFactory: stateFactory, deps: [INITIAL_STATE] },
                { provide: Store, useFactory: storeFactory, deps: [State] },
                { provide: StateHistory, useFactory: historyFactory, deps: [Store, INITIAL_STATE] },
                { provide: RouterState, useFactory: routerStateFactory, deps: [Store, Router] },
                Dispatcher
            ]
        };
    }

    constructor(
        injector: Injector,
        stateHistory: StateHistory,
        routerState: RouterState,
        @Inject(INITIAL_STATE) initialState: any,
        @Inject(STORE_HISTORY_ITEMS) storeHistoryItems: any,
        @Inject(COLLECT_HISTORY) collectHistory: any,
        @Inject(IS_PROD) isProd: any
    ) {
        if (storeHistoryItems !== undefined) {
            StateHistory.collectHistory = collectHistory;
        }

        if (collectHistory !== undefined) {
            StateHistory.storeHistoryItems = storeHistoryItems;
        }

        ServiceLocator.injector = injector;
        stateHistory.init(initialState);
        routerState.init();

        if (!isProd) {
            (<any>window).state = StateHistory;
        }
    }
}
```

**Comment by ng-state** [comment]
BWT

```
ERROR in Error: Unexpected value 'StoreModule in C:/tmp/ng-state-example-app/node_modules/ng-state/src/ng-state.module.d.ts' imported by the module 'AppModule in C:/tmp/ng-state-example-app/src/app/app.modu
le.ts'. Please add a @NgModule annotation.
```

this is how exported code looks like - do not see anything there

```js
var __decorate = (undefined && undefined.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (undefined && undefined.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var INITIAL_STATE = new _angular_core.InjectionToken('INITIAL_STATE');
var COLLECT_HISTORY = new _angular_core.InjectionToken('COLLECT_HISTORY');
var STORE_HISTORY_ITEMS = new _angular_core.InjectionToken('STORE_HISTORY_ITEMS');
var IS_PROD = new _angular_core.InjectionToken('IS_PROD');
var StoreModule = (function () {
    function StoreModule() {
    }
    StoreModule.prototype.ngOnDestroy = function () {
    };
    StoreModule = __decorate([
        _angular_core.NgModule({
            imports: [_angular_common.CommonModule],
            declarations: [StateHistoryComponent],
            exports: [StateHistoryComponent]
        }),
        __metadata("design:paramtypes", [])
    ], StoreModule);
    return StoreModule;
}());

exports.StoreModule = StoreModule;
```

it looks EXACTLY like RouterModule

**Comment by Toxicable** [comment]
>ERROR in Error: Unexpected value 'StoreModule in .../ng-state.module.d.ts' 

it's looking at .d.ts not the js file.

>Thanks for quick response. Please tell me which function is not exported?

My guess is that it's probably your duplicated function and duplicated provide's

**Comment by mlc-mlapis** [comment]
... what is the line `(<any>window).state = StateHistory;`?

**Comment by ng-state** [comment]
mlc-mlapis - i was trying to comment all code inside - same it fails getting inside...

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/32366682-2a6d0ada-c04d-11e7-9083-f77be209e1ad.png)

Seems you're publishing `.ngsummary.json` in your package, that does not seems right, instead `.metadata.json` should be published.

**Comment by ng-state** [comment]
trotyl - how to get compiled to get metadata.json file? 

tsconfig
```

{
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": true,
    "stripInternal": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "es2015",
    "moduleResolution": "node",
    "noEmitOnError": false,
    "outDir": "./release",
    "rootDir": ".",
    "sourceMap": true,
    "inlineSources": true,
    "lib": ["es2015", "dom"],
    "target": "es5",
    "skipLibCheck": true
  },
  "files": [
    "index.ts"
  ],
  "angularCompilerOptions": {
    "annotationsAs": "decorators",
    "genDir": "./release",
    "skipMetadataEmit" : true
  }
}
```
package.json commands
```
"build:js": "ngc -p tsconfig.dist.json",
    "build:umd": "rollup -c rollup.config.js",
    "build:uglify": "uglifyjs -c --screw-ie8 --comments -o ./release/bundles/store.min.umd.js ./release/bundles/store.umd.js",
    "prebuild": "npm run clean:pre",
    "postbuild": "npm run clean:post && npm run copy",
    "build": "npm run build:js && npm run build:umd && npm run build:uglify"
```

**Comment by ng-state** [comment]
Toxicable

any idea how how to fix it? Because i just import package from npm.

**Comment by Toxicable** [comment]
>any idea how how to fix it? Because i just import package from npm?

My knowledge for correct package formatting is little so Im not the one to help you there

>duplicated function and provider's? Can you be more exact with sample peace of code or point th eplace where?

Whops sorry, I misread your src, State and Store and very similar :P

Although something else that "might" cause an issue is that you're providing one extra param than this function is asking for 
https://github.com/ng-state/store/blob/master/src/ng-state.module.ts#L53

**Comment by ng-state** [comment]
Toxicable 
I have removed that parasm still same error. I think it just cannot get inside for soem reason. Maybe for the same reason that it refferences .d.ts instead of .js

Not sure how to fix it

**Comment by ng-state** [comment]
I finally go through that step
thanks trotyl 
I removed '"skipMetadataEmit" : true'. It was there for webpack because ngc-webapck for some reason does not require metadata....

no I have different problem:
https://github.com/angular/angular-cli/issues/7110

anyway Angular keeps failing again and again. For instance i support React also and even if they reqriten all in 16.0 mygration was - install new package - DONE

Yesterday I bounced 3 hours also by trying to understand wh metada stopped beying generated and you know why - in 5.0.0 angular stopped looking at strictMetadataEmit option in typescript - Why we did not see any warnings? do we have to read ALL changelog every time where line you MIGHT needed is somwhere in between hundreds of others?

**Comment by ng-state** [comment]
Upgrading to typescript 2.6.2 solved problem above with rxjs - we should ignore CLI warning about typescript version < 2.5.0 

ticket can be closed

thanks

**Comment by mlc-mlapis** [comment]
@ng-state ... what RxJS problem do you mean that could be solve using typescript 2.6.2? ... Btw, the latest TS is 2.6.1.

**Comment by ng-state** [comment]
mlc-mlapis yes 2.6.1
problem was:
```
ERROR in ./node_modules/rxjs/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
```

described in https://github.com/angular/angular-cli/issues/7110

**Comment by mlc-mlapis** [comment]
@ng-state ... thanks. And just to be sure ... did you try to solve the problem just via:
```
import { BoundCallbackObservable } from 'rxjs/observable/BoundCallbackObservable';
```
instead of TS 2.6.1?

**Comment by ng-state** [comment]
mlc-mlapis i do not use BoundCallbackObservable at all
But i tried adding all other usages of rxjs that way - not helped.

**Comment by mlc-mlapis** [comment]
@ng-state ... OK, thanks.

**Comment by vicb** [comment]
Support request -> closing.
