### ISSUE TITLE
Angular2 & jQuery Datatables - Issue with using Angular 2 Components inside render function for column definition

### ISSUE THREAD

**Issue by Abhishek-Kanitkar** [angular/angular#20135]
I am using jQuery DataTables plugin inside Angular 2 project, as it is by far the best & most robust plugin for Datagrid.

I am facing following issue when using Angular 2 custom components inside the template string returned from render function. Here is code snippet

    @Component({
      selector: 'my-custom-grid',
      templateUrl: './my-custom-grid.html',
      styleUrls: ['./my-custom-grid.less'],
      encapsulation: ViewEncapsulation.None
    })

    export class MyCustomGridComponent implements OnInit {

      constructor() {}

      ngOnInit() {}

      dataGridConfig:any = {

        "paging": false,
        "info": false,
        "destroy": true,
        "columns": [
            { 
              data: 'customerName',
              title: 'CUSTOMER NAME',
              render: function(data, type){

                return "<span *ngIf='someBoolean'>Welcome Text</span><my-
                 new-component></my-new-component>";
              }
            }                
          ],
          "fixedHeader": true,    
          "scrollX": true,
          "scrollCollapse": true,
          "dom": 't',
          "order": [[ 1, 'asc' ]],
          "responsive": false
          };   
    }
The problem is *ngIf & are not compiled by Angular 2 when I use them inside render function as above.

Why is this happening ? Is there any way to use Angular 2/4 custom components & structural directive inside render function of jQuery Datatables ?

Thanks in advance !

**Comment by Toxicable** [comment]
Only templates inside `template` or found at the `templateUrl` are compiled.
This will not be compiled
>return "<span *ngIf='someBoolean'>Welcome Text</span><my-
             new-component></my-new-component>";
