### ISSUE TITLE
[compiler-cli] allow providing a program in performCompilation

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#20130]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

in `compiler-cli` the function `performCompilation` does compilation.
If the resource loader in the compiler host is async this function can not be used because the program is created within it and `loadNgStructureAsync` is not invoked.

## Expected behavior

Make `performCompilation` usable for async compilations

## What is the motivation / use case for changing the behavior?

With this is place it is fairly simple to create a compilation process with webpack and it's loaders.
I know `@ngtools/webpack` does that but it is enclosed and so one can not hook to replace/change/update resources.

The main use case is library generation where this will help inlining resources, updating code and other tasks usually running post compilation via gulp.

Since `performCompilation` accepts transforms the whole library generation process is doable with TS! which is super cool!

Also, this will help simply the code in `@ngtools/webpack` as it will be able to use the function [see source code comment](https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/angular_compiler_plugin.ts#L844-L847)

If this is acceptable, I have a [PR ready](https://github.com/shlomiassaf/angular/tree/performCompilation-accpet-program) with an extra `program` parameter that if exists will skip program creation and use the supplied program.

or, another approach with [this PR](https://github.com/shlomiassaf/angular/tree/performCompilation-accept-program-2-fn) that does not change the API (even if not breaking) but adds an explicit `performCompilationAsync` function

cc @alexeagle @tbosch @filipesilva @hansl

**Comment by dherges** [comment]
Let me ask, will this PR allow to do resource inlining as a [custom transformer](https://github.com/shlomiassaf/angular/blob/9d8fcf8f447c2373439cb141c2b840b96ae027af/packages/compiler-cli/src/transformers/api.ts#L208-L211)?

Use case is:

Before Transform:

```ts
@Component({
  templateUrl: './foo.component.html'
})
export class FooComponent {}
```

After Transform, before ngc compilation:

```ts
@Component({
  template: '<h1>Content from foo.component.html here...</h1>'
})
export class FooComponent {}
```

Is this already possible with the current `@angular/compiler-cli` API?

**Comment by shlomiassaf** [comment]
@dherges you can do it today, if you have sync resource loaders.

**Comment by alxhub** [comment]
Closing as obsolete, and in general our compiler APIs are internal and not meant for 3rd party consumption.
